LLVM: AArch64MCExpr.cpp File Reference
LLVM API Documentation
AArch64MCExpr.cpp File Reference
#include "AArch64MCExpr.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCELF.h"
#include "llvm/Object/ELF.h"
Macros
#define DEBUG_TYPE "aarch64mcexpr"
Functions
static void fixELFSymbolsInTLSFixupsImpl (const MCExpr *Expr, MCAssembler &Asm)
static void AddValueSymbolsImpl (const MCExpr *Value, MCAssembler *Asm)
Macro Definition Documentation
#define DEBUG_TYPE "aarch64mcexpr"
Definition at line 15 of file AArch64MCExpr.cpp.
Function Documentation
static void AddValueSymbolsImpl (const MCExpr * Value, MCAssembler * Asm) static
Definition at line 150 of file AArch64MCExpr.cpp.
References llvm::HexStyle::Asm, llvm::MCExpr::Binary, llvm::MCExpr::Constant, llvm::MCExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCAssembler::getOrCreateSymbolData(), llvm::MCBinaryExpr::getRHS(), llvm::AArch64MCExpr::getSubExpr(), llvm_unreachable, llvm::MCExpr::SymbolRef, llvm::MCExpr::Target, and llvm::MCExpr::Unary.
Referenced by llvm::AArch64MCExpr::AddValueSymbols().
static void fixELFSymbolsInTLSFixupsImpl (const MCExpr * Expr, MCAssembler & Asm) static
Definition at line 85 of file AArch64MCExpr.cpp.
References llvm::HexStyle::Asm, llvm::MCExpr::Binary, llvm::MCExpr::Constant, llvm::MCExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCAssembler::getOrCreateSymbolData(), llvm::MCBinaryExpr::getRHS(), llvm::AArch64MCExpr::getSubExpr(), llvm::MCSymbolRefExpr::getSymbol(), llvm_unreachable, llvm::MCELF::SetType(), llvm::ELF::STT_TLS, llvm::MCExpr::SymbolRef, llvm::MCExpr::Target, and llvm::MCExpr::Unary.
Referenced by llvm::AArch64MCExpr::fixELFSymbolsInTLSFixups().