LLVM: AArch64BranchFixupPass.cpp File Reference
LLVM API Documentation
AArch64BranchFixupPass.cpp File Reference
#include "AArch64.h"
#include "AArch64InstrInfo.h"
#include "Utils/AArch64BaseInfo.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/ADT/Statistic.h"
Macros
#define DEBUG_TYPE "aarch64-branch-fixup"
Functions
STATISTIC (NumSplit,"Number of uncond branches inserted")
STATISTIC (NumCBrFixed,"Number of cond branches fixed")
static unsigned UnknownPadding (unsigned LogAlign, unsigned KnownBits)
static bool BBHasFallthrough (MachineBasicBlock *MBB)
Macro Definition Documentation
#define DEBUG_TYPE "aarch64-branch-fixup"
Definition at line 15 of file AArch64BranchFixupPass.cpp.
Function Documentation
static bool BBHasFallthrough (MachineBasicBlock * MBB) static
Return true if the specified basic block can fallthrough into the block immediately after it.
Definition at line 237 of file AArch64BranchFixupPass.cpp.
References llvm::A64InvertCondCode(), llvm::MachineInstrBuilder::addOperand(), llvm::MachineBasicBlock::addSuccessor(), llvm::MachineBasicBlock::back(), BB, llvm::MachineBasicBlock::begin(), llvm::tgtok::Bits, llvm::BuildMI(), CC, llvm::dbgs(), DEBUG, llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::MachineInstr::eraseFromParent(), llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getMBB(), llvm::MachineBasicBlock::getNumber(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), i, I, llvm::MachineBasicBlock::insert(), int, llvm::isIntN(), llvm::MachineOperand::isMBB(), llvm_unreachable, llvm::A64CC::MI, llvm::next(), llvm::prior(), llvm::MachineOperand::setImm(), llvm::MachineOperand::setMBB(), llvm::MachineBasicBlock::splice(), llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_end(), TII, and llvm::MachineBasicBlock::transferSuccessors().
STATISTIC (NumSplit , "Number of uncond branches inserted")
STATISTIC (NumCBrFixed , "Number of cond branches fixed")
static unsigned UnknownPadding (unsigned LogAlign, unsigned KnownBits) inline static
Return the worst case padding that could result from unknown offset bits. This does not include alignment padding caused by known offset bits.
Parameters
LogAlign log2(alignment)
KnownBits Number of known low offset bits.
Definition at line 36 of file AArch64BranchFixupPass.cpp.
References BB, llvm::tgtok::Bits, llvm::countTrailingZeros(), llvm::dbgs(), DEBUG, llvm::format(), llvm::MachineBasicBlock::getNumber(), llvm::A64CC::MI, TII, and verify.