LLVM: AliasAnalysisCounter.cpp File Reference
LLVM API Documentation
AliasAnalysisCounter.cpp File Reference
#include "llvm/Analysis/Passes.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Assembly/Writer.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
Functions
INITIALIZE_AG_PASS (AliasAnalysisCounter, AliasAnalysis,"count-aa","Count Alias Analysis Query Responses", false, true, false) ModulePass *llvm
Variables
static cl::opt< bool > PrintAll ("count-aa-print-all-queries", cl::ReallyHidden, cl::init(true))
static cl::opt< bool > PrintAllFailures ("count-aa-print-all-failed-queries", cl::ReallyHidden)
Function Documentation
INITIALIZE_AG_PASS (AliasAnalysisCounter , AliasAnalysis , "count-aa" , "Count Alias Analysis Query Responses" , false , true , false)
Definition at line 119 of file AliasAnalysisCounter.cpp.
References llvm::errs(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getInstruction(), PrintAll, PrintAllFailures, and llvm::WriteAsOperand().
Variable Documentation
cl::opt<bool> PrintAll("count-aa-print-all-queries", cl::ReallyHidden, cl::init(true)) static
Referenced by INITIALIZE_AG_PASS().
cl::opt<bool> PrintAllFailures("count-aa-print-all-failed-queries", cl::ReallyHidden) static
Referenced by INITIALIZE_AG_PASS().