LLVM: AliasAnalysisEvaluator.cpp File Reference
LLVM API Documentation
AliasAnalysisEvaluator.cpp File Reference
#include "llvm/Analysis/Passes.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Assembly/Writer.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/InstIterator.h"
#include "llvm/Support/raw_ostream.h"
Functions
INITIALIZE_PASS_BEGIN (AAEval,"aa-eval","Exhaustive Alias Analysis Precision Evaluator", false, true) INITIALIZE_PASS_END(AAEval
static void PrintResults (const char *Msg, bool P, const Value *V1, const Value *V2, const Module *M)
static void PrintModRefResults (const char *Msg, bool P, Instruction *I, Value *Ptr, Module *M)
static void PrintModRefResults (const char *Msg, bool P, CallSite CSA, CallSite CSB, Module *M)
static void PrintLoadStoreResults (const char *Msg, bool P, const Value *V1, const Value *V2, const Module *M)
static bool isInterestingPointer (Value *V)
static void PrintPercent (unsigned Num, unsigned Sum)
Variables
static cl::opt< bool > PrintAll ("print-all-alias-modref-info", cl::ReallyHidden)
static cl::opt< bool > PrintNoAlias ("print-no-aliases", cl::ReallyHidden)
static cl::opt< bool > PrintMayAlias ("print-may-aliases", cl::ReallyHidden)
static cl::opt< bool > PrintPartialAlias ("print-partial-aliases", cl::ReallyHidden)
static cl::opt< bool > PrintMustAlias ("print-must-aliases", cl::ReallyHidden)
static cl::opt< bool > PrintNoModRef ("print-no-modref", cl::ReallyHidden)
static cl::opt< bool > PrintMod ("print-mod", cl::ReallyHidden)
static cl::opt< bool > PrintRef ("print-ref", cl::ReallyHidden)
static cl::opt< bool > PrintModRef ("print-modref", cl::ReallyHidden)
static cl::opt< bool > EvalTBAA ("evaluate-tbaa", cl::ReallyHidden)
aa eval
aa Exhaustive Alias Analysis Precision Evaluator
aa Exhaustive Alias Analysis Precision false
Function Documentation
INITIALIZE_PASS_BEGIN (AAEval , "aa-eval" , "Exhaustive Alias Analysis Precision Evaluator" , false , true)
static bool isInterestingPointer (Value * V) inline static
Definition at line 137 of file AliasAnalysisEvaluator.cpp.
References llvm::AliasAnalysis::alias(), llvm::Function::arg_begin(), llvm::Function::arg_end(), llvm::SetVector< T, Vector, Set >::begin(), llvm::SetVector< T, Vector, Set >::end(), llvm::errs(), EvalTBAA, F(), llvm::AliasAnalysis::getLocation(), llvm::AliasAnalysis::getModRefInfo(), llvm::Value::getName(), llvm::GlobalValue::getParent(), llvm::Value::getType(), llvm::AliasAnalysis::getTypeStoreSize(), I, llvm::SetVector< T, Vector, Set >::insert(), llvm::inst_begin(), llvm::inst_end(), llvm::Type::isPointerTy(), llvm::Type::isSized(), llvm::AliasAnalysis::MayAlias, llvm::AliasAnalysis::Mod, llvm::AliasAnalysis::ModRef, llvm::AliasAnalysis::MustAlias, llvm::AliasAnalysis::NoAlias, llvm::AliasAnalysis::NoModRef, llvm::User::op_begin(), llvm::User::op_end(), llvm::AliasAnalysis::PartialAlias, PrintLoadStoreResults(), PrintMayAlias, PrintMod, PrintModRef, PrintModRefResults(), PrintMustAlias, PrintNoAlias, PrintNoModRef, PrintPartialAlias, PrintRef, PrintResults(), llvm::AliasAnalysis::Ref, llvm::SetVector< T, Vector, Set >::size(), llvm::StringRef::size(), and llvm::AliasAnalysis::UnknownSize.
static void PrintLoadStoreResults (const char * Msg, bool P, const Value * V1, const Value * V2, const Module * M) inline static
Definition at line 129 of file AliasAnalysisEvaluator.cpp.
References llvm::errs().
Referenced by isInterestingPointer().
static void PrintModRefResults (const char * Msg, bool P, Instruction * I, Value * Ptr, Module * M) inline static
Definition at line 110 of file AliasAnalysisEvaluator.cpp.
References llvm::errs(), and llvm::WriteAsOperand().
Referenced by isInterestingPointer().
static void PrintModRefResults (const char * Msg, bool P, CallSite CSA, CallSite CSB, Module * M) inline static
Definition at line 120 of file AliasAnalysisEvaluator.cpp.
References llvm::errs(), and llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getInstruction().
static void PrintPercent (unsigned Num, unsigned Sum) static
Definition at line 326 of file AliasAnalysisEvaluator.cpp.
References llvm::errs(), M, and Sum.
static void PrintResults (const char * Msg, bool P, const Value * V1, const Value * V2, const Module * M) static
Definition at line 91 of file AliasAnalysisEvaluator.cpp.
References llvm::errs(), std::swap(), and llvm::WriteAsOperand().
Referenced by isInterestingPointer().
Variable Documentation
aa eval
Definition at line 86 of file AliasAnalysisEvaluator.cpp.
cl::opt<bool> EvalTBAA("evaluate-tbaa", cl::ReallyHidden) static
Referenced by isInterestingPointer().
aa Exhaustive Alias Analysis Precision Evaluator
Definition at line 86 of file AliasAnalysisEvaluator.cpp.
Referenced by CommitValueTo(), and EvaluateStaticConstructor().
aa Exhaustive Alias Analysis Precision false
Definition at line 86 of file AliasAnalysisEvaluator.cpp.
cl::opt<bool> PrintAll("print-all-alias-modref-info", cl::ReallyHidden) static
cl::opt<bool> PrintMayAlias("print-may-aliases", cl::ReallyHidden) static
Referenced by isInterestingPointer().
cl::opt<bool> PrintMod("print-mod", cl::ReallyHidden) static
Referenced by isInterestingPointer().
cl::opt<bool> PrintModRef("print-modref", cl::ReallyHidden) static
Referenced by isInterestingPointer().
cl::opt<bool> PrintMustAlias("print-must-aliases", cl::ReallyHidden) static
Referenced by isInterestingPointer().
cl::opt<bool> PrintNoAlias("print-no-aliases", cl::ReallyHidden) static
Referenced by isInterestingPointer().
cl::opt<bool> PrintNoModRef("print-no-modref", cl::ReallyHidden) static
Referenced by isInterestingPointer().
cl::opt<bool> PrintPartialAlias("print-partial-aliases", cl::ReallyHidden) static
Referenced by isInterestingPointer().
cl::opt<bool> PrintRef("print-ref", cl::ReallyHidden) static
Referenced by isInterestingPointer().