LLVM: AMDGPUAsmPrinter.cpp File Reference
LLVM API Documentation
AMDGPUAsmPrinter.cpp File Reference
#include "AMDGPUAsmPrinter.h"
#include "AMDGPU.h"
#include "R600Defines.h"
#include "R600MachineFunctionInfo.h"
#include "R600RegisterInfo.h"
#include "SIDefines.h"
#include "SIMachineFunctionInfo.h"
#include "SIRegisterInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/Support/ELF.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
Functions
static AsmPrinter * createAMDGPUAsmPrinterPass (TargetMachine &tm, MCStreamer &Streamer)
void LLVMInitializeR600AsmPrinter ()
Detailed Description
The AMDGPUAsmPrinter is used to print both assembly string and also binary code. When passed an MCAsmStreamer it prints assembly and when passed an MCObjectStreamer it outputs binary code.
Definition in file AMDGPUAsmPrinter.cpp.
Function Documentation
static AsmPrinter* createAMDGPUAsmPrinterPass (TargetMachine & tm, MCStreamer & Streamer) static
Definition at line 39 of file AMDGPUAsmPrinter.cpp.
Referenced by LLVMInitializeR600AsmPrinter().
void LLVMInitializeR600AsmPrinter ()
Definition at line 44 of file AMDGPUAsmPrinter.cpp.
References createAMDGPUAsmPrinterPass(), llvm::TargetRegistry::RegisterAsmPrinter(), and llvm::TheAMDGPUTarget.