LLVM: APFloat.cpp File Reference
LLVM API Documentation
APFloat.cpp File Reference
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/APSInt.h"
#include "llvm/ADT/FoldingSet.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include <cstring>
#include <limits.h>
Classes
struct llvm::fltSemantics
struct decimalInfo
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define PackCategoriesIntoKey(_lhs, _rhs) ((_lhs) * 4 + (_rhs))
#define COMPILE_TIME_ASSERT(cond) extern int CTAssert[(cond) ? 1 : -1]
Functions
COMPILE_TIME_ASSERT (integerPartWidth%4==0)
static unsigned int partCountForBits (unsigned int bits)
static unsigned int decDigitValue (unsigned int c)
static int readExponent (StringRef::iterator begin, StringRef::iterator end)
static int totalExponent (StringRef::iterator p, StringRef::iterator end, int exponentAdjustment)
static StringRef::iterator skipLeadingZeroesAndAnyDot (StringRef::iterator begin, StringRef::iterator end, StringRef::iterator *dot)
static void interpretDecimal (StringRef::iterator begin, StringRef::iterator end, decimalInfo *D)
static lostFraction trailingHexadecimalFraction (StringRef::iterator p, StringRef::iterator end, unsigned int digitValue)
static lostFraction lostFractionThroughTruncation (const integerPart *parts, unsigned int partCount, unsigned int bits)
static lostFraction shiftRight (integerPart *dst, unsigned int parts, unsigned int bits)
static lostFraction combineLostFractions (lostFraction moreSignificant, lostFraction lessSignificant)
static unsigned int HUerrBound (bool inexactMultiply, unsigned int HUerr1, unsigned int HUerr2)
static integerPart ulpsFromBoundary (const integerPart *parts, unsigned int bits, bool isNearest)
static unsigned int powerOf5 (integerPart *dst, unsigned int power)
static unsigned int partAsHex (char *dst, integerPart part, unsigned int count, const char *hexDigitChars)
static char * writeUnsignedDecimal (char *dst, unsigned int n)
static char * writeSignedDecimal (char *dst, int value)
Variables
const unsigned int llvm::maxExponent = 16383
const unsigned int llvm::maxPrecision = 113
const unsigned int llvm::maxPowerOfFiveExponent = maxExponent + maxPrecision - 1
const unsigned int llvm::maxPowerOfFiveParts
static const char hexDigitsLower [] = "0123456789abcdef0"
static const char hexDigitsUpper [] = "0123456789ABCDEF0"
static const char infinityL [] = "infinity"
static const char infinityU [] = "INFINITY"
static const char NaNL [] = "nan"
static const char NaNU [] = "NAN"
Macro Definition Documentation
#define COMPILE_TIME_ASSERT (cond) extern int CTAssert[(cond) ? 1 : -1]
Definition at line 38 of file APFloat.cpp.
#define PackCategoriesIntoKey (_lhs, _rhs) ((_lhs) * 4 + (_rhs))
A macro used to combine two fcCategory enums into one key which can be used in a switch statement to classify how the interaction of two APFloat's categories affects an operation.
TODO: If clang source code is ever allowed to use constexpr in its own codebase, change this into a static inline function.
Definition at line 34 of file APFloat.cpp.
Referenced by llvm::APFloat::compare(), and llvm::APFloat::semanticsPrecision().
Function Documentation
static lostFraction combineLostFractions (lostFraction moreSignificant, lostFraction lessSignificant) static
Definition at line 376 of file APFloat.cpp.
References llvm::lfExactlyHalf, llvm::lfExactlyZero, llvm::lfLessThanHalf, and llvm::lfMoreThanHalf.
Referenced by llvm::APFloat::semanticsPrecision().
COMPILE_TIME_ASSERT (integerPartWidth% 4 = =0)
static unsigned int decDigitValue (unsigned int c) inline static
Definition at line 106 of file APFloat.cpp.
Referenced by llvm::APFloat::convertFromZeroExtendedInteger(), interpretDecimal(), readExponent(), and totalExponent().
static unsigned int HUerrBound (bool inexactMultiply, unsigned int HUerr1, unsigned int HUerr2) static
Definition at line 397 of file APFloat.cpp.
Referenced by llvm::APFloat::convertFromZeroExtendedInteger().
static void interpretDecimal (StringRef::iterator begin, StringRef::iterator end, decimalInfo * D) static
Definition at line 251 of file APFloat.cpp.
References decDigitValue(), llvm::sys::path::end(), decimalInfo::exponent, decimalInfo::firstSigDigit, decimalInfo::lastSigDigit, decimalInfo::normalizedExponent, p, readExponent(), and skipLeadingZeroesAndAnyDot().
Referenced by llvm::APFloat::convertFromZeroExtendedInteger().
static lostFraction lostFractionThroughTruncation (const integerPart * parts, unsigned int partCount, unsigned int bits) static
Definition at line 341 of file APFloat.cpp.
References llvm::integerPartWidth, llvm::lfExactlyHalf, llvm::lfExactlyZero, llvm::lfLessThanHalf, llvm::lfMoreThanHalf, llvm::APInt::tcExtractBit(), and llvm::APInt::tcLSB().
Referenced by llvm::APFloat::convert(), llvm::APFloat::convertFromZeroExtendedInteger(), llvm::APFloat::convertToHexString(), llvm::APFloat::convertToInteger(), and shiftRight().
static unsigned int partAsHex (char * dst, integerPart part, unsigned int count, const char * hexDigitChars) static
Definition at line 527 of file APFloat.cpp.
References llvm::integerPartWidth, and result.
Referenced by llvm::APFloat::convertToHexString().
static unsigned int partCountForBits (unsigned int bits) inline static
Definition at line 99 of file APFloat.cpp.
References llvm::integerPartWidth.
Referenced by llvm::APFloat::convert(), llvm::APFloat::convertFromZeroExtendedInteger(), llvm::APFloat::convertToInteger(), llvm::APFloat::getSmallestNormalized(), llvm::APFloat::Profile(), llvm::APFloat::semanticsPrecision(), and llvm::APFloat::toString().
static unsigned int powerOf5 (integerPart * dst, unsigned int power) static
Definition at line 456 of file APFloat.cpp.
References llvm::maxPowerOfFiveParts, n, pc, result, llvm::APInt::tcAssign(), and llvm::APInt::tcFullMultiply().
Referenced by llvm::APFloat::convertFromZeroExtendedInteger().
static int readExponent (StringRef::iterator begin, StringRef::iterator end) static
Definition at line 117 of file APFloat.cpp.
References llvm::sys::path::begin(), decDigitValue(), llvm::sys::path::end(), int, and p.
Referenced by interpretDecimal().
static lostFraction shiftRight (integerPart * dst, unsigned int parts, unsigned int bits) static
Definition at line 363 of file APFloat.cpp.
References lostFractionThroughTruncation(), and llvm::APInt::tcShiftRight().
Referenced by llvm::APFloat::convert(), and llvm::APFloat::semanticsPrecision().
static StringRef::iterator skipLeadingZeroesAndAnyDot (StringRef::iterator begin, StringRef::iterator end, StringRef::iterator * dot) static
Definition at line 210 of file APFloat.cpp.
References llvm::sys::path::begin(), llvm::sys::path::end(), and p.
Referenced by llvm::APFloat::convertFromZeroExtendedInteger(), and interpretDecimal().
static int totalExponent (StringRef::iterator p, StringRef::iterator end, int exponentAdjustment) static
Definition at line 161 of file APFloat.cpp.
References decDigitValue(), llvm::sys::path::end(), and p.
Referenced by llvm::APFloat::convertFromZeroExtendedInteger().
static lostFraction trailingHexadecimalFraction (StringRef::iterator p, StringRef::iterator end, unsigned int digitValue) static
Definition at line 310 of file APFloat.cpp.
References llvm::hexDigitValue(), llvm::lfExactlyHalf, llvm::lfExactlyZero, llvm::lfLessThanHalf, and llvm::lfMoreThanHalf.
Referenced by llvm::APFloat::convertFromZeroExtendedInteger().
static integerPart ulpsFromBoundary (const integerPart * parts, unsigned int bits, bool isNearest) static
Definition at line 411 of file APFloat.cpp.
References llvm::integerPartWidth.
Referenced by llvm::APFloat::convertFromZeroExtendedInteger().
static char* writeSignedDecimal (char * dst, int value) static
Definition at line 563 of file APFloat.cpp.
References llvm::APInt::getNumWords(), llvm::APInt::getRawData(), llvm::APInt::tcAssign(), llvm::APInt::tcClearBit(), llvm::APInt::tcIsZero(), llvm::APInt::tcSet(), llvm::APInt::tcSetBit(), and writeUnsignedDecimal().
Referenced by llvm::APFloat::convertToHexString().
static char* writeUnsignedDecimal (char * dst, unsigned int n) static
Definition at line 545 of file APFloat.cpp.
References p.
Referenced by writeSignedDecimal().
Variable Documentation
const char hexDigitsLower[] = "0123456789abcdef0" static
Definition at line 516 of file APFloat.cpp.
Referenced by llvm::APFloat::convertToHexString().
const char hexDigitsUpper[] = "0123456789ABCDEF0" static
Definition at line 517 of file APFloat.cpp.
const char infinityL[] = "infinity" static
Definition at line 518 of file APFloat.cpp.
const char infinityU[] = "INFINITY" static
Definition at line 519 of file APFloat.cpp.
const char NaNL[] = "nan" static
Definition at line 520 of file APFloat.cpp.
const char NaNU[] = "NAN" static
Definition at line 521 of file APFloat.cpp.