LLVM: APInt.cpp File Reference
LLVM API Documentation
APInt.cpp File Reference
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/FoldingSet.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include <cmath>
#include <cstdlib>
#include <cstring>
#include <limits>
Macros
#define DEBUG_TYPE "apint"
#define COMPILE_TIME_ASSERT(cond) extern int CTAssert[(cond) ? 1 : -1]
Functions
static uint64_t * getClearedMemory (unsigned numWords)
static uint64_t * getMemory (unsigned numWords)
static unsigned getDigit (char cdigit, uint8_t radix)
A utility function that converts a character to a digit.
static bool add_1 (uint64_t dest[], uint64_t x[], unsigned len, uint64_t y)
static bool sub_1 (uint64_t x[], unsigned len, uint64_t y)
static bool add (uint64_t *dest, const uint64_t *x, const uint64_t *y, unsigned len)
General addition of 64-bit integer arrays.
static bool sub (uint64_t *dest, const uint64_t *x, const uint64_t *y, unsigned len)
Generalized subtraction of 64-bit integer arrays.
static uint64_t mul_1 (uint64_t dest[], uint64_t x[], unsigned len, uint64_t y)
Multiply a multi-digit APInt by a single digit (64-bit) integer.
static void mul (uint64_t dest[], uint64_t x[], unsigned xlen, uint64_t y[], unsigned ylen)
Generalized multiplicate of integer arrays.
static void lshrNear (uint64_t *Dst, uint64_t *Src, unsigned Words, unsigned Shift)
static void KnuthDiv (unsigned *u, unsigned *v, unsigned *q, unsigned *r, unsigned m, unsigned n)
COMPILE_TIME_ASSERT (integerPartWidth%2==0)
Macro Definition Documentation
#define COMPILE_TIME_ASSERT (cond) extern int CTAssert[(cond) ? 1 : -1]
Definition at line 2272 of file APInt.cpp.
#define DEBUG_TYPE "apint"
Definition at line 15 of file APInt.cpp.
Function Documentation
static bool add (uint64_t * dest, const uint64_t * x, const uint64_t * y, unsigned len) static
General addition of 64-bit integer arrays.
add - This function adds the integer array x to the integer array Y and places the result in dest.
Returns
the carry out from the addition
Definition at line 237 of file APInt.cpp.
References i.
Referenced by llvm::APInt::operator+(), and llvm::APInt::operator+=().
static bool add_1 (uint64_t dest[], uint64_t x[], unsigned len, uint64_t y) static
add_1 - This function adds a single "digit" integer, y, to the multiple "digit" integer array, x[]. x[] is modified to reflect the addition and 1 is returned if there is a carry out, otherwise 0 is returned.
Returns
the carry of the addition.
Definition at line 182 of file APInt.cpp.
References i, and y.
Referenced by llvm::APInt::operator++().
COMPILE_TIME_ASSERT (integerPartWidth% 2 = =0)
static uint64_t* getClearedMemory (unsigned numWords) inline static
A utility function for allocating memory, checking for allocation failures, and ensuring the contents are zeroed.
Definition at line 33 of file APInt.cpp.
References llvm::Intrinsic::memset, and result.
Referenced by getDigit(), KnuthDiv(), and llvm::APInt::sshl_ov().
static unsigned getDigit (char cdigit, uint8_t radix) inline static
A utility function that converts a character to a digit.
Definition at line 49 of file APInt.cpp.
References llvm::ArrayRef< T >::data(), getClearedMemory(), getMemory(), llvm::APInt::getNumWords(), i, llvm::Intrinsic::memcpy, llvm::APInt::pVal, llvm::ArrayRef< T >::size(), val, and llvm::APInt::VAL.
Referenced by llvm::APInt::sshl_ov().
static uint64_t* getMemory (unsigned numWords) inline static
A utility function for allocating memory and checking for allocation failure. The content is not zeroed.
Definition at line 42 of file APInt.cpp.
References result.
Referenced by llvm::APInt::APInt(), getDigit(), llvm::APInt::operator*=(), llvm::APInt::operator^=(), llvm::APInt::sext(), llvm::APInt::trunc(), and llvm::APInt::zext().
static void KnuthDiv (unsigned * u, unsigned * v, unsigned * q, unsigned * r, unsigned m, unsigned n) static
Implementation of Knuth's Algorithm D (Division of nonnegative integers) from "Art of Computer Programming, Volume 2", section 4.3.1, p. 272. The variables here have the same names as in the algorithm. Comments explain the algorithm and any deviation from it.
Definition at line 1487 of file APInt.cpp.
References b, llvm::APInt::clearAllBits(), llvm::APInt::countLeadingZeros(), llvm::dbgs(), DEBUG, getClearedMemory(), llvm::APInt::getNumWords(), i, if(), j(), llvm::Intrinsic::memset, n, llvm::APInt::pVal, result, shift, and llvm::APInt::VAL.
static void lshrNear (uint64_t * Dst, uint64_t * Src, unsigned Words, unsigned Shift) static
Perform a logical right-shift from Src to Dst, which must be equal or non-overlapping, of Words words, by Shift, which must be less than 64.
Definition at line 767 of file APInt.cpp.
References I, and Shift.
Referenced by llvm::APInt::byteSwap(), and llvm::APInt::lshr().
static void mul (uint64_t dest[], uint64_t x[], unsigned xlen, uint64_t y[], unsigned ylen) static
Generalized multiplicate of integer arrays.
Multiplies integer array x by integer array y and stores the result into the integer array dest. Note that dest's size must be >= xlen + ylen.
Definition at line 325 of file APInt.cpp.
References i, j(), and mul_1().
Referenced by llvm::LLLexer::getFilename(), and llvm::APInt::operator*=().
static uint64_t mul_1 (uint64_t dest[], uint64_t x[], unsigned len, uint64_t y) static
Multiply a multi-digit APInt by a single digit (64-bit) integer.
Multiplies an integer array, x, by a uint64_t integer and places the result into dest.
Returns
the carry out of the multiplication.
Definition at line 291 of file APInt.cpp.
References i.
Referenced by mul().
static bool sub (uint64_t * dest, const uint64_t * x, const uint64_t * y, unsigned len) static
Generalized subtraction of 64-bit integer arrays.
Subtracts the integer array y from the integer array x
Returns
returns the borrow out.
Definition at line 264 of file APInt.cpp.
References i.
Referenced by llvm::APInt::operator-(), and llvm::APInt::operator-=().
static bool sub_1 (uint64_t x[], unsigned len, uint64_t y) static
sub_1 - This function subtracts a single "digit" (64-bit word), y, from the multi-digit integer array, x[], propagating the borrowed 1 value until no further borrowing is neeeded or it runs out of "digits" in x. The result is 1 if "borrowing" exhausted the digits in x, or 0 if x was not exhausted. In other words, if y > x then this function returns 1, otherwise 0.
Returns
the borrow out of the subtraction
Definition at line 210 of file APInt.cpp.
References i, llvm::X, and y.
Referenced by llvm::APInt::operator--().