LLVM: ArgumentPromotion.cpp File Reference
LLVM API Documentation
ArgumentPromotion.cpp File Reference
#include "llvm/Transforms/IPO.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/CallGraph.h"
#include "llvm/Analysis/CallGraphSCCPass.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/CFG.h"
#include "llvm/Support/CallSite.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <set>
Macros
#define DEBUG_TYPE "argpromotion"
Functions
STATISTIC (NumArgumentsPromoted,"Number of pointer arguments promoted")
STATISTIC (NumAggregatesPromoted,"Number of aggregate arguments promoted")
STATISTIC (NumByValArgsPromoted,"Number of byval arguments promoted")
STATISTIC (NumArgumentsDead,"Number of dead pointer args eliminated")
INITIALIZE_PASS_BEGIN (ArgPromotion,"argpromotion","Promote 'by reference' arguments to scalars", false, false) INITIALIZE_PASS_END(ArgPromotion
static bool AllCallersPassInValidPointerForArgument (Argument *Arg)
static bool IsPrefix (const ArgPromotion::IndicesVector &Prefix, const ArgPromotion::IndicesVector &Longer)
static bool PrefixIn (const ArgPromotion::IndicesVector &Indices, std::set< ArgPromotion::IndicesVector > &Set)
Checks if Indices, or a prefix of Indices, is in Set.
static void MarkIndicesSafe (const ArgPromotion::IndicesVector &ToMark, std::set< ArgPromotion::IndicesVector > &Safe)
Variables
argpromotion
Promote by reference arguments to scalars
Promote by reference arguments to false
Macro Definition Documentation
#define DEBUG_TYPE "argpromotion"
Definition at line 32 of file ArgumentPromotion.cpp.
Function Documentation
static bool AllCallersPassInValidPointerForArgument (Argument * Arg) static
AllCallersPassInValidPointerForArgument - Return true if we can prove that all callees pass in a valid pointer for the specified function argument.
Definition at line 217 of file ArgumentPromotion.cpp.
References llvm::Argument::getArgNo(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getArgument(), llvm::Argument::getParent(), llvm::Value::isDereferenceablePointer(), llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by MarkIndicesSafe().
INITIALIZE_PASS_BEGIN (ArgPromotion , "argpromotion" , "Promote 'by reference' arguments to scalars" , false , false)
static bool IsPrefix (const ArgPromotion::IndicesVector & Prefix, const ArgPromotion::IndicesVector & Longer) static
Returns true if Prefix is a prefix of longer. That means, Longer has a size that is greater than or equal to the size of prefix, and each of the elements in Prefix is the same as the corresponding elements in Longer.
This means it also returns true when Prefix and Longer are equal!
Definition at line 240 of file ArgumentPromotion.cpp.
References llvm::lltok::equal.
Referenced by MarkIndicesSafe(), and PrefixIn().
static void MarkIndicesSafe (const ArgPromotion::IndicesVector & ToMark, std::set< ArgPromotion::IndicesVector > & Safe) static
Mark the given indices (ToMark) as safe in the given set of indices (Safe). Marking safe usually means adding ToMark to Safe. However, if there is already a prefix of Indices in Safe, Indices are implicitely marked safe already. Furthermore, any indices that Indices is itself a prefix of, are removed from Safe (since they are implicitely safe because of Indices now).
Definition at line 268 of file ArgumentPromotion.cpp.
References llvm::object::advance(), AllCallersPassInValidPointerForArgument(), llvm::Function::arg_begin(), llvm::Function::arg_end(), B, llvm::SmallVectorTemplateCommon< T >::back(), BB, llvm::BasicBlock::begin(), llvm::Function::begin(), llvm::Call, llvm::AliasAnalysis::canBasicBlockModify(), llvm::AliasAnalysis::canInstructionRangeModify(), llvm::SmallVectorImpl< T >::clear(), llvm::Function::copyAttributesFrom(), llvm::AliasAnalysis::copyValue(), llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::Function::Create(), llvm::GetElementPtrInst::Create(), llvm::CallInst::Create(), llvm::InvokeInst::Create(), llvm::dbgs(), DEBUG, llvm::AliasAnalysis::deleteValue(), llvm::SmallVectorBase::empty(), llvm::BasicBlock::end(), llvm::Instruction::eraseFromParent(), llvm::GlobalValue::ExternalLinkage, F(), llvm::BasicBlock::front(), llvm::ConstantInt::get(), llvm::FunctionType::get(), llvm::LoadInst::getAlignment(), llvm::Function::getAttributes(), llvm::Function::getBasicBlockList(), llvm::Value::getContext(), llvm::Type::getContext(), llvm::Function::getContext(), llvm::StructType::getElementType(), llvm::AttributeSet::getFnAttributes(), llvm::Module::getFunctionList(), llvm::Function::getFunctionType(), llvm::GetElementPtrInst::getIndexedType(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::GlobalValue::getLinkage(), llvm::AliasAnalysis::getLocation(), llvm::Instruction::getMetadata(), llvm::Value::getName(), llvm::StructType::getNumElements(), llvm::GetElementPtrInst::getNumIndices(), llvm::User::getNumOperands(), llvm::CallGraphNode::getNumReferences(), llvm::User::getOperand(), llvm::AttributeSet::getParamAttributes(), llvm::Argument::getParent(), llvm::Instruction::getParent(), llvm::GlobalValue::getParent(), llvm::AttributeSet::getRetAttributes(), llvm::FunctionType::getReturnType(), llvm::Value::getType(), llvm::AttributeSet::hasAttributes(), i, I, llvm::idf_ext_begin(), llvm::idf_ext_end(), llvm::GetElementPtrInst::idx_begin(), llvm::GetElementPtrInst::idx_end(), llvm::ARM_PROC::IE, llvm::iplist< NodeTy, Traits >::insert(), IsPrefix(), llvm::Type::isStructTy(), llvm::FunctionType::isVarArg(), llvm::SPII::Load, llvm::LLVMContext::MD_tbaa, llvm::User::op_begin(), llvm::User::op_end(), P, llvm::pred_begin(), llvm::pred_end(), PrefixIn(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::CallGraphNode::replaceCallEdge(), llvm::AliasAnalysis::replaceWithNewValue(), llvm::LoadInst::setAlignment(), llvm::Instruction::setMetadata(), llvm::Value::setName(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::Value::takeName(), llvm::Instruction::use_back(), llvm::Value::use_back(), llvm::Value::use_begin(), llvm::Value::use_empty(), llvm::Value::use_end(), and llvm::utostr().
static bool PrefixIn (const ArgPromotion::IndicesVector & Indices, std::set< ArgPromotion::IndicesVector > & Set) static
Checks if Indices, or a prefix of Indices, is in Set.
Definition at line 249 of file ArgumentPromotion.cpp.
References IsPrefix().
Referenced by MarkIndicesSafe().
STATISTIC (NumArgumentsPromoted , "Number of pointer arguments promoted")
STATISTIC (NumAggregatesPromoted , "Number of aggregate arguments promoted")
STATISTIC (NumByValArgsPromoted , "Number of byval arguments promoted")
STATISTIC (NumArgumentsDead , "Number of dead pointer args eliminated")
Variable Documentation
argpromotion
Definition at line 92 of file ArgumentPromotion.cpp.
Promote by reference arguments to false
Definition at line 92 of file ArgumentPromotion.cpp.
Promote by reference arguments to scalars
Definition at line 92 of file ArgumentPromotion.cpp.