LLVM: ARMAsmPrinter.cpp File Reference
LLVM API Documentation
ARMAsmPrinter.cpp File Reference
#include "ARMAsmPrinter.h"
#include "ARM.h"
#include "ARMBuildAttrs.h"
#include "ARMConstantPoolValue.h"
#include "ARMFPUName.h"
#include "ARMMachineFunctionInfo.h"
#include "ARMTargetMachine.h"
#include "ARMTargetObjectFile.h"
#include "InstPrinter/ARMInstPrinter.h"
#include "MCTargetDesc/ARMAddressingModes.h"
#include "MCTargetDesc/ARMMCExpr.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/Assembly/Writer.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
#include "llvm/DebugInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCELFStreamer.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstBuilder.h"
#include "llvm/MC/MCObjectStreamer.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ELF.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/Mangler.h"
#include "llvm/Target/TargetMachine.h"
#include <cctype>
#include "ARMGenMCPseudoLowering.inc"
Macros
#define DEBUG_TYPE "asm-printer"
Functions
static ARMBuildAttrs::CPUArch getArchForCPU (StringRef CPU, const ARMSubtarget *Subtarget)
static MCSymbol * getPICLabel (const char *Prefix, unsigned FunctionNumber, unsigned LabelId, MCContext &Ctx)
static MCSymbolRefExpr::VariantKind getModifierVariantKind (ARMCP::ARMCPModifier Modifier)
void LLVMInitializeARMAsmPrinter ()
Variables
cl::opt< bool > EnableARMEHABI
Macro Definition Documentation
#define DEBUG_TYPE "asm-printer"
Definition at line 15 of file ARMAsmPrinter.cpp.
Function Documentation
static ARMBuildAttrs::CPUArch getArchForCPU (StringRef CPU, const ARMSubtarget * Subtarget) static
Definition at line 586 of file ARMAsmPrinter.cpp.
References llvm::ARMBuildAttrs::ABI_align8_needed, llvm::ARMBuildAttrs::ABI_align8_preserved, llvm::ARMBuildAttrs::ABI_FP_denormal, llvm::ARMBuildAttrs::ABI_FP_exceptions, llvm::ARMBuildAttrs::ABI_FP_number_model, llvm::ARMBuildAttrs::ABI_HardFP_use, llvm::ARMBuildAttrs::ABI_VFP_args, llvm::ARMBuildAttrs::Advanced_SIMD_arch, llvm::ARMBuildAttrs::AllowDIVExt, llvm::ARMBuildAttrs::AllowDIVIfExists, llvm::ARMBuildAttrs::Allowed, llvm::ARMBuildAttrs::AllowHPFP, llvm::ARMBuildAttrs::AllowIEE754, llvm::ARMBuildAttrs::AllowMP, llvm::ARMBuildAttrs::AllowNeonARMv8, llvm::ARMBuildAttrs::AllowThumb32, llvm::ARMBuildAttrs::AllowTZ, llvm::ARMBuildAttrs::AllowTZVirtualization, llvm::ARMBuildAttrs::AllowVirtualization, llvm::ARMBuildAttrs::ApplicationProfile, llvm::ARMBuildAttrs::ARM_ISA_use, llvm::ARMBuildAttrs::CPU_arch, llvm::ARMBuildAttrs::CPU_arch_profile, llvm::ARMBuildAttrs::CPU_name, llvm::ARMBuildAttrs::DIV_use, llvm::ARMTargetStreamer::emitAttribute(), llvm::ARMTargetStreamer::emitFPU(), llvm::MCStreamer::EmitIntValue(), llvm::ARMTargetStreamer::emitTextAttribute(), llvm::ARMTargetStreamer::finishAttributeSection(), llvm::TargetOptions::FloatABIType, llvm::ARMBuildAttrs::FP_HP_extension, llvm::ARMElfTargetObjectFile::getAttributesSection(), llvm::ARMSubtarget::getCPUString(), llvm::AsmPrinter::getObjFileLowering(), llvm::MCStreamer::getTargetStreamer(), llvm::FloatABI::Hard, llvm::ARMBuildAttrs::HardFPAAPCS, llvm::ARMBuildAttrs::HardFPSinglePrecision, llvm::ARMSubtarget::hasARMOps(), llvm::ARMSubtarget::hasCrypto(), llvm::ARMSubtarget::hasD16(), llvm::ARMSubtarget::hasDivide(), llvm::ARMSubtarget::hasDivideInARMMode(), llvm::ARMSubtarget::hasFP16(), llvm::ARMSubtarget::hasFPARMv8(), llvm::ARMSubtarget::hasMPExtension(), llvm::ARMSubtarget::hasNEON(), llvm::MCStreamer::hasRawTextSupport(), llvm::ARMSubtarget::hasThumb2(), llvm::ARMSubtarget::hasThumb2DSP(), llvm::ARMSubtarget::hasTrustZone(), llvm::ARMSubtarget::hasV4TOps(), llvm::ARMSubtarget::hasV5TEOps(), llvm::ARMSubtarget::hasV5TOps(), llvm::ARMSubtarget::hasV6MOps(), llvm::ARMSubtarget::hasV6Ops(), llvm::ARMSubtarget::hasV6T2Ops(), llvm::ARMSubtarget::hasV7Ops(), llvm::ARMSubtarget::hasV8Ops(), llvm::ARMSubtarget::hasVFP2(), llvm::ARMSubtarget::hasVFP3(), llvm::ARMSubtarget::hasVFP4(), llvm::ARMSubtarget::hasVirtualization(), llvm::ARMSubtarget::isAAPCS_ABI(), llvm::ARMSubtarget::isAClass(), llvm::ARMSubtarget::isFPOnlySP(), llvm::ARMSubtarget::isMClass(), llvm::ARMSubtarget::isRClass(), llvm::ARMSubtarget::isThumb1Only(), llvm::ARMBuildAttrs::MicroControllerProfile, llvm::ARMBuildAttrs::MPextension_use, llvm::TargetOptions::NoInfsFPMath, llvm::TargetOptions::NoNaNsFPMath, llvm::ARMBuildAttrs::Not_Allowed, llvm::TargetMachine::Options, llvm::AsmPrinter::OutStreamer, llvm::ARMBuildAttrs::RealTimeProfile, llvm::MCStreamer::SwitchSection(), llvm::ARMTargetStreamer::switchVendor(), llvm::ARMBuildAttrs::THUMB_ISA_use, llvm::AsmPrinter::TM, llvm::TargetOptions::UnsafeFPMath, llvm::ARMBuildAttrs::v4, llvm::ARMBuildAttrs::v4T, llvm::ARMBuildAttrs::v5T, llvm::ARMBuildAttrs::v5TE, llvm::ARMBuildAttrs::v5TEJ, llvm::ARMBuildAttrs::v6, llvm::ARMBuildAttrs::v6S_M, llvm::ARMBuildAttrs::v6T2, llvm::ARMBuildAttrs::v7, llvm::ARMBuildAttrs::v7E_M, llvm::ARMBuildAttrs::v8, and llvm::ARMBuildAttrs::Virtualization_use.
static MCSymbolRefExpr::VariantKind getModifierVariantKind (ARMCP::ARMCPModifier Modifier) static
Definition at line 765 of file ARMAsmPrinter.cpp.
References llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), llvm::MachineModuleInfoMachO::getGVStubEntry(), llvm::MachineModuleInfoMachO::getHiddenGVStubEntry(), llvm::MachineModuleInfo::getObjFileInfo(), llvm::TargetMachine::getRelocationModel(), llvm::AsmPrinter::getSymbol(), llvm::AsmPrinter::GetSymbolWithGlobalValueBase(), llvm::ARMCP::GOT, llvm::ARMCP::GOTOFF, llvm::ARMCP::GOTTPOFF, llvm::ARMSubtarget::GVIsIndirectSymbol(), llvm::GlobalValue::hasHiddenVisibility(), llvm::GlobalValue::hasInternalLinkage(), llvm::ARMSubtarget::isTargetDarwin(), llvm_unreachable, llvm::AsmPrinter::MMI, llvm::ARMCP::no_modifier, llvm::ARMCP::TLSGD, llvm::AsmPrinter::TM, llvm::ARMCP::TPOFF, llvm::MCSymbolRefExpr::VK_ARM_GOT, llvm::MCSymbolRefExpr::VK_ARM_GOTOFF, llvm::MCSymbolRefExpr::VK_ARM_GOTTPOFF, llvm::MCSymbolRefExpr::VK_ARM_TLSGD, llvm::MCSymbolRefExpr::VK_ARM_TPOFF, and llvm::MCSymbolRefExpr::VK_None.
Referenced by llvm::ARMAsmPrinter::EmitMachineConstantPoolValue().
static MCSymbol* getPICLabel (const char * Prefix, unsigned FunctionNumber, unsigned LabelId, MCContext & Ctx) static
Definition at line 756 of file ARMAsmPrinter.cpp.
References llvm::MCContext::GetOrCreateSymbol().
Referenced by llvm::ARMAsmPrinter::EmitInstruction(), and llvm::ARMAsmPrinter::EmitMachineConstantPoolValue().
void LLVMInitializeARMAsmPrinter ()
Definition at line 1789 of file ARMAsmPrinter.cpp.
References llvm::TheARMTarget, llvm::TheThumbTarget, llvm::X, and Y.
Variable Documentation
cl::opt<bool> EnableARMEHABI
Referenced by llvm::ARMELFMCAsmInfo::ARMELFMCAsmInfo(), and llvm::ARMAsmPrinter::EmitJump2Table().