LLVM: ARMAsmBackend.cpp File Reference
LLVM API Documentation
ARMAsmBackend.cpp File Reference
#include "MCTargetDesc/ARMMCTargetDesc.h"
#include "MCTargetDesc/ARMAddressingModes.h"
#include "MCTargetDesc/ARMBaseInfo.h"
#include "MCTargetDesc/ARMFixupKinds.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDirectives.h"
#include "llvm/MC/MCELFObjectWriter.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixupKindInfo.h"
#include "llvm/MC/MCMachObjectWriter.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/ELF.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MachO.h"
#include "llvm/Support/raw_ostream.h"
Functions
static unsigned getRelaxedOpcode (unsigned Op)
static unsigned adjustFixupValue (const MCFixup &Fixup, uint64_t Value, MCContext *Ctx=NULL)
static unsigned getFixupKindNumBytes (unsigned Kind)
getFixupKindNumBytes - The number of bytes the fixup may change.
Function Documentation
static unsigned adjustFixupValue (const MCFixup & Fixup, uint64_t Value, MCContext * Ctx = NULL) static
Definition at line 254 of file ARMAsmBackend.cpp.
References llvm::ARM_PROC::A, llvm::MCSymbol::AliasedSymbol(), llvm::HexStyle::Asm, llvm::ARM::fixup_arm_adr_pcrel_12, llvm::ARM::fixup_arm_blx, llvm::ARM::fixup_arm_condbl, llvm::ARM::fixup_arm_condbranch, llvm::ARM::fixup_arm_ldst_pcrel_12, llvm::ARM::fixup_arm_movt_hi16, llvm::ARM::fixup_arm_movt_hi16_pcrel, llvm::ARM::fixup_arm_movw_lo16, llvm::ARM::fixup_arm_movw_lo16_pcrel, llvm::ARM::fixup_arm_pcrel_10, llvm::ARM::fixup_arm_pcrel_10_unscaled, llvm::ARM::fixup_arm_thumb_bcc, llvm::ARM::fixup_arm_thumb_bl, llvm::ARM::fixup_arm_thumb_blx, llvm::ARM::fixup_arm_thumb_br, llvm::ARM::fixup_arm_thumb_cb, llvm::ARM::fixup_arm_thumb_cp, llvm::ARM::fixup_arm_uncondbl, llvm::ARM::fixup_arm_uncondbranch, llvm::ARM::fixup_t2_adr_pcrel_12, llvm::ARM::fixup_t2_condbranch, llvm::ARM::fixup_t2_ldst_pcrel_12, llvm::ARM::fixup_t2_movt_hi16, llvm::ARM::fixup_t2_movt_hi16_pcrel, llvm::ARM::fixup_t2_movw_lo16, llvm::ARM::fixup_t2_movw_lo16_pcrel, llvm::ARM::fixup_t2_pcrel_10, llvm::ARM::fixup_t2_uncondbranch, llvm::ARM::fixup_thumb_adr_pcrel_10, llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::MCAssembler::getContext(), llvm::MCFixup::getKind(), llvm::MCFixup::getLoc(), llvm::ARM_AM::getSOImmVal(), llvm::MCValue::getSymA(), llvm::MCSymbolRefExpr::getSymbol(), i, I, llvm::MCAssembler::isThumbFunc(), and llvm_unreachable.
Referenced by getFixupKindNumBytes().
static unsigned getFixupKindNumBytes (unsigned Kind) static
getFixupKindNumBytes - The number of bytes the fixup may change.
Definition at line 561 of file ARMAsmBackend.cpp.
References adjustFixupValue(), llvm::MachO::CPU_TYPE_ARM, llvm::createARMELFObjectWriter(), llvm::createARMMachObjectWriter(), llvm::ARM::fixup_arm_adr_pcrel_12, llvm::ARM::fixup_arm_blx, llvm::ARM::fixup_arm_condbl, llvm::ARM::fixup_arm_condbranch, llvm::ARM::fixup_arm_ldst_pcrel_12, llvm::ARM::fixup_arm_movt_hi16, llvm::ARM::fixup_arm_movt_hi16_pcrel, llvm::ARM::fixup_arm_movw_lo16, llvm::ARM::fixup_arm_movw_lo16_pcrel, llvm::ARM::fixup_arm_pcrel_10, llvm::ARM::fixup_arm_pcrel_10_unscaled, llvm::ARM::fixup_arm_thumb_bcc, llvm::ARM::fixup_arm_thumb_bl, llvm::ARM::fixup_arm_thumb_blx, llvm::ARM::fixup_arm_thumb_br, llvm::ARM::fixup_arm_thumb_cb, llvm::ARM::fixup_arm_thumb_cp, llvm::ARM::fixup_arm_uncondbl, llvm::ARM::fixup_arm_uncondbranch, llvm::ARM::fixup_t2_adr_pcrel_12, llvm::ARM::fixup_t2_condbranch, llvm::ARM::fixup_t2_ldst_pcrel_12, llvm::ARM::fixup_t2_movt_hi16, llvm::ARM::fixup_t2_movt_hi16_pcrel, llvm::ARM::fixup_t2_movw_lo16, llvm::ARM::fixup_t2_movw_lo16_pcrel, llvm::ARM::fixup_t2_pcrel_10, llvm::ARM::fixup_t2_uncondbranch, llvm::ARM::fixup_thumb_adr_pcrel_10, llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::MCFixup::getKind(), llvm::MCFixup::getOffset(), i, llvm_unreachable, and llvm::ARMBuildAttrs::Section.
static unsigned getRelaxedOpcode (unsigned Op) static
Definition at line 151 of file ARMAsmBackend.cpp.
References llvm::X86II::DF, llvm::MCInst::dump_pretty(), llvm::ARM::fixup_arm_thumb_bcc, llvm::ARM::fixup_arm_thumb_br, llvm::ARM::fixup_arm_thumb_cp, llvm::ARM::fixup_thumb_adr_pcrel_10, llvm::MCFixup::getKind(), llvm::MCInst::getOpcode(), i, llvm_unreachable, llvm::report_fatal_error(), llvm::MCInst::setOpcode(), llvm::raw_svector_ostream::str(), llvm::MCObjectWriter::Write16(), llvm::MCObjectWriter::Write32(), and llvm::MCObjectWriter::Write8().