LLVM: ARMConstantIslandPass.cpp File Reference
LLVM API Documentation
ARMConstantIslandPass.cpp File Reference
#include "ARM.h"
#include "ARMMachineFunctionInfo.h"
#include "MCTargetDesc/ARMAddressingModes.h"
#include "Thumb2InstrInfo.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "arm-cp-islands"
Functions
STATISTIC (NumCPEs,"Number of constpool entries")
STATISTIC (NumSplit,"Number of uncond branches inserted")
STATISTIC (NumCBrFixed,"Number of cond branches fixed")
STATISTIC (NumUBrFixed,"Number of uncond branches fixed")
STATISTIC (NumTBs,"Number of table branches generated")
STATISTIC (NumT2CPShrunk,"Number of Thumb2 constantpool instructions shrunk")
STATISTIC (NumT2BrShrunk,"Number of Thumb2 immediate branches shrunk")
STATISTIC (NumCBZ,"Number of CBZ / CBNZ formed")
STATISTIC (NumJTMoved,"Number of jump table destination blocks moved")
STATISTIC (NumJTInserted,"Number of jump table intermediate blocks inserted")
static unsigned UnknownPadding (unsigned LogAlign, unsigned KnownBits)
static bool BBHasFallthrough (MachineBasicBlock *MBB)
static bool CompareMBBNumbers (const MachineBasicBlock *LHS, const MachineBasicBlock *RHS)
static bool BBIsJumpedOver (MachineBasicBlock *MBB)
static unsigned getUnconditionalBrDisp (int Opc)
Variables
static cl::opt< bool > AdjustJumpTableBlocks ("arm-adjust-jump-tables", cl::Hidden, cl::init(true), cl::desc("Adjust basic block layout to better use TB[BH]"))
static cl::opt< bool > AlignConstantIslands ("arm-align-constant-islands", cl::Hidden, cl::init(true), cl::desc("Align constant islands in code"))
Macro Definition Documentation
#define DEBUG_TYPE "arm-cp-islands"
Definition at line 16 of file ARMConstantIslandPass.cpp.
Function Documentation
static bool BBHasFallthrough (MachineBasicBlock * MBB) static
BBHasFallthrough - Return true if the specified basic block can fallthrough into the block immediately after it.
Definition at line 568 of file ARMConstantIslandPass.cpp.
References Align, AlignConstantIslands, B, llvm::MachineBasicBlock::back(), llvm::MachineBasicBlock::begin(), llvm::tgtok::Bits, llvm::MachineBasicBlock::empty(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::MachineFunction::ensureAlignment(), llvm::MachineOperand::getIndex(), llvm::MachineBasicBlock::getNumber(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), i, I, if(), llvm::isPowerOf2_32(), llvm_unreachable, llvm::Log2_32(), llvm::A64CC::MI, llvm::next(), llvm::MachineBasicBlock::push_back(), size, llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_end(), and TII.
Referenced by getUnconditionalBrDisp().
static bool BBIsJumpedOver (MachineBasicBlock * MBB) static
BBIsJumpedOver - Return true of the specified basic block's only predecessor unconditionally branches to its only successor.
Definition at line 1057 of file ARMConstantIslandPass.cpp.
References B, llvm::MachineBasicBlock::back(), BB, llvm::dbgs(), DEBUG, llvm::MachineOperand::getIndex(), llvm::MachineOperand::getMBB(), llvm::MachineBasicBlock::getNumber(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), i, llvm::MachineOperand::isCPI(), j(), llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_size(), llvm::MachineOperand::setIndex(), llvm::MachineBasicBlock::succ_begin(), and llvm::MachineBasicBlock::succ_size().
Referenced by getUnconditionalBrDisp().
static bool CompareMBBNumbers (const MachineBasicBlock * LHS, const MachineBasicBlock * RHS) static
CompareMBBNumbers - Little predicate function to sort the WaterList by MBB ID.
Definition at line 844 of file ARMConstantIslandPass.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), llvm::ARMCC::AL, B, llvm::BuildMI(), llvm::dbgs(), DEBUG, llvm::MachineBasicBlock::end(), llvm::format(), llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineOperand::getImm(), llvm::MachineBasicBlock::getNumber(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineBasicBlock::insert(), llvm::A64CC::MI, llvm::next(), llvm::OffsetToAlignment(), llvm::MachineFunction::RenumberBlocks(), llvm::MachineBasicBlock::splice(), TII, llvm::MachineBasicBlock::transferSuccessors(), and UnknownPadding().
static unsigned getUnconditionalBrDisp (int Opc) inline static
getUnconditionalBrDisp - Returns the maximum displacement that can fit in the specific unconditional branch instruction.
Definition at line 1164 of file ARMConstantIslandPass.cpp.
References llvm::MachineInstrBuilder::addConstantPoolIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), llvm::ARMCC::AL, llvm::HexagonInstrInfo::AnalyzeBranch(), B, llvm::MachineBasicBlock::back(), BB, BBHasFallthrough(), BBIsJumpedOver(), llvm::MachineBasicBlock::begin(), llvm::tgtok::Bits, llvm::BuildMI(), CC, llvm::dbgs(), DEBUG, llvm::SmallVectorBase::empty(), llvm::MachineBasicBlock::empty(), llvm::MachineBasicBlock::end(), llvm::ARMCC::EQ, llvm::MachineInstr::eraseFromParent(), llvm::format(), llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::getInstrPredicate(), llvm::getITInstrPredicate(), llvm::MachineJumpTableInfo::getJumpTables(), llvm::getKillRegState(), llvm::MachineOperand::getMBB(), llvm::MachineBasicBlock::getNumber(), llvm::MachineInstr::getNumExplicitOperands(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::ARMCC::getOppositeCondition(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), i, llvm::MachineBasicBlock::insert(), int, llvm::isARMLowRegister(), llvm::MachineOperand::isCPI(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isKill(), llvm::MachineInstr::isPredicable(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUse(), j(), llvm_unreachable, llvm::A64CC::MI, llvm::MachineBasicBlock::moveAfter(), llvm::ARMCC::NE, llvm::next(), llvm::prior(), llvm::MachineBasicBlock::removeSuccessor(), llvm::MachineJumpTableInfo::ReplaceMBBInJumpTable(), result, llvm::MachineBasicBlock::setAlignment(), llvm::MachineInstr::setDesc(), llvm::MachineOperand::setImm(), llvm::MachineOperand::setIndex(), llvm::MachineOperand::setMBB(), TII, UnknownPadding(), and llvm::MachineBasicBlock::updateTerminator().
STATISTIC (NumCPEs , "Number of constpool entries")
STATISTIC (NumSplit , "Number of uncond branches inserted")
STATISTIC (NumCBrFixed , "Number of cond branches fixed")
STATISTIC (NumUBrFixed , "Number of uncond branches fixed")
STATISTIC (NumTBs , "Number of table branches generated")
STATISTIC (NumT2CPShrunk , "Number of Thumb2 constantpool instructions shrunk")
STATISTIC (NumT2BrShrunk , "Number of Thumb2 immediate branches shrunk")
STATISTIC (NumCBZ , "Number of CBZ / CBNZ formed")
STATISTIC (NumJTMoved , "Number of jump table destination blocks moved")
STATISTIC (NumJTInserted , "Number of jump table intermediate blocks inserted")
static unsigned UnknownPadding (unsigned LogAlign, unsigned KnownBits) inline static
UnknownPadding - Return the worst case padding that could result from unknown offset bits. This does not include alignment padding caused by known offset bits.
Parameters
LogAlign log2(alignment)
KnownBits Number of known low offset bits.
Definition at line 66 of file ARMConstantIslandPass.cpp.
References BB, llvm::tgtok::Bits, llvm::countTrailingZeros(), llvm::dbgs(), DEBUG, llvm::format(), llvm::MachineBasicBlock::getNumber(), llvm::MachineInstr::getParent(), i, llvm_unreachable, llvm::A64CC::MI, TII, and verify.
Referenced by CompareMBBNumbers(), and getUnconditionalBrDisp().
Variable Documentation
cl::opt<bool> AdjustJumpTableBlocks("arm-adjust-jump-tables", cl::Hidden, cl::init(true), cl::desc("Adjust basic block layout to better use TB[BH]")) static
Referenced by llvm::createARMConstantIslandPass().
cl::opt<bool> AlignConstantIslands("arm-align-constant-islands", cl::Hidden, cl::init(true), cl::desc("Align constant islands in code")) static
Referenced by BBHasFallthrough(), and llvm::createARMConstantIslandPass().