LLVM: ARMCodeEmitter.cpp File Reference
LLVM API Documentation
ARMCodeEmitter.cpp File Reference
#include "ARM.h"
#include "ARMBaseInstrInfo.h"
#include "ARMConstantPoolValue.h"
#include "ARMRelocations.h"
#include "ARMSubtarget.h"
#include "ARMTargetMachine.h"
#include "MCTargetDesc/ARMAddressingModes.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/JITCodeEmitter.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/PassManager.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <iomanip>
#include "ARMGenCodeEmitter.inc"
Macros
#define DEBUG_TYPE "jit"
Functions
STATISTIC (NumEmitted,"Number of machine instructions emitted")
static unsigned getAddrModeUPBits (unsigned Mode)
static unsigned convertNEONDataProcToThumb (unsigned Binary)
Macro Definition Documentation
#define DEBUG_TYPE "jit"
Definition at line 15 of file ARMCodeEmitter.cpp.
Function Documentation
static unsigned convertNEONDataProcToThumb (unsigned Binary) static
convertNEONDataProcToThumb - Convert the ARM mode encoding for a NEON data-processing instruction to the corresponding Thumb encoding.
Definition at line 1807 of file ARMCodeEmitter.cpp.
References llvm::ARMCC::AL, llvm::ARMII::CondShift, llvm::ARMII::FormMask, llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), llvm::MCInstrDesc::getOperandConstraint(), llvm::ARMBaseInstrInfo::getPredicate(), llvm::MachineOperand::getReg(), llvm::ARMBaseInstrInfo::getRegisterInfo(), I, llvm::ARMII::NGetLnFrm, llvm::ARMII::RegRdShift, llvm::MCOI::TIED_TO, and llvm::MCInstrDesc::TSFlags.
static unsigned getAddrModeUPBits (unsigned Mode) static
Definition at line 1252 of file ARMCodeEmitter.cpp.
References llvm::ARM_AM::add, llvm::ARMJITInfo::addJumpTableBaseAddr(), llvm::ARM_AM::asr, llvm::ARMII::CondShift, llvm::ARMII::D_BitShift, llvm::ARM_AM::da, llvm::ARM_AM::db, DEBUG, llvm::errs(), llvm::ARMII::ExtRotImmShift, llvm::ARMII::FormMask, llvm::ARM_AM::getAM4SubMode(), llvm::ARM_AM::getAM5Offset(), llvm::ARM_AM::getAM5Op(), llvm::JITCodeEmitter::getCurrentPCValue(), llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::ARM_AM::getLoadStoreMultipleSubMode(), llvm::MCInstrDesc::getNumDefs(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MCInstrDesc::getOperandConstraint(), llvm::ARMBaseInstrInfo::getPredicate(), llvm::MachineOperand::getReg(), llvm::ARMBaseInstrInfo::getRegisterInfo(), llvm::ARM_AM::getSORegShOp(), i, llvm::ARM_AM::ia, llvm::ARM_AM::ib, llvm::ARMII::IndexModeMask, llvm::MachineOperand::isImm(), llvm::MachineOperand::isImplicit(), llvm::MCOperandInfo::isOptionalDef(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::MCOperandInfo::isPredicate(), llvm::MachineOperand::isReg(), llvm_unreachable, llvm::ARMII::M_BitShift, llvm::ARMII::N_BitShift, llvm::MCInstrDesc::Opcode, llvm::MCInstrDesc::OpInfo, llvm::ARMII::P_BitShift, llvm::ARMII::RegRdHiShift, llvm::ARMII::RegRdLoShift, llvm::ARMII::RegRdShift, llvm::ARMII::RegRnShift, llvm::ARMII::RegRsShift, llvm::ARM::reloc_arm_absolute, llvm::ARM::reloc_arm_pic_jt, llvm::ARMII::ShiftShift, llvm::MCOI::TIED_TO, llvm::MCInstrDesc::TSFlags, llvm::ARMII::U_BitShift, llvm::ARMII::VFPBinaryFrm, llvm::ARMII::VFPConv1Frm, llvm::ARMII::VFPConv2Frm, llvm::ARMII::VFPConv3Frm, llvm::ARMII::VFPConv4Frm, llvm::ARMII::VFPConv5Frm, and llvm::ARMII::W_BitShift.
STATISTIC (NumEmitted , "Number of machine instructions emitted")