LLVM: ARMELFStreamer.cpp File Reference
LLVM API Documentation
ARMELFStreamer.cpp File Reference
#include "ARMBuildAttrs.h"
#include "ARMFPUName.h"
#include "ARMRegisterInfo.h"
#include "ARMUnwindOp.h"
#include "ARMUnwindOpAsm.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Twine.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCELF.h"
#include "llvm/MC/MCELFStreamer.h"
#include "llvm/MC/MCELFSymbolFlags.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstPrinter.h"
#include "llvm/MC/MCObjectStreamer.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ELF.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include "ARMFPUName.def"
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define ARM_FPU_NAME(NAME, ID) case ARM::ID: return NAME;
Functions
static std::string GetAEABIUnwindPersonalityName (unsigned Index)
static const char * GetFPUName (unsigned ID)
MCStreamer * llvm::createMCAsmStreamer (MCContext &Ctx, formatted_raw_ostream &OS, bool isVerboseAsm, bool useLoc, bool useCFI, bool useDwarfDirectory, MCInstPrinter *InstPrint, MCCodeEmitter *CE, MCAsmBackend *TAB, bool ShowInst)
MCELFStreamer * llvm::createARMELFStreamer (MCContext &Context, MCAsmBackend &TAB, raw_ostream &OS, MCCodeEmitter *Emitter, bool RelaxAll, bool NoExecStack, bool IsThumb)
Macro Definition Documentation
#define ARM_FPU_NAME (NAME, ID) case ARM::ID: return NAME;
Function Documentation
static std::string GetAEABIUnwindPersonalityName (unsigned Index) static
Definition at line 48 of file ARMELFStreamer.cpp.
References llvm::NUM_PERSONALITY_INDEX.
Referenced by GetFPUName().
static const char* GetFPUName (unsigned ID) static
Definition at line 53 of file ARMELFStreamer.cpp.
References llvm::ARMBuildAttrs::Advanced_SIMD_arch, llvm::AEABI_UNWIND_CPP_PR0, llvm::ARMBuildAttrs::AllowFPARMv8A, llvm::ARMBuildAttrs::AllowFPv2, llvm::ARMBuildAttrs::AllowFPv3A, llvm::ARMBuildAttrs::AllowFPv3B, llvm::ARMBuildAttrs::AllowFPv4A, llvm::ARMBuildAttrs::AllowFPv4B, llvm::ARMBuildAttrs::AllowNeon, llvm::ARMBuildAttrs::AllowNeon2, llvm::ARMBuildAttrs::AllowNeonARMv8, llvm::tgtok::Bit, llvm::MCELFStreamer::ChangeSection(), llvm::ARMBuildAttrs::CPU_name, llvm::MCFixup::Create(), llvm::MCSymbolRefExpr::Create(), llvm::X86II::DF, llvm::ELF_Other_ThumbFunc, llvm::MCELFStreamer::EmitAssemblerFlag(), llvm::MCObjectStreamer::EmitBytes(), llvm::MCObjectStreamer::EmitInstruction(), llvm::MCELFStreamer::EmitValueImpl(), llvm::StringRef::empty(), llvm::EXIDX_CANTUNWIND, llvm::ARMBuildAttrs::File, llvm::ARMTargetStreamer::finishAttributeSection(), llvm::MCELFStreamer::FinishImpl(), GetAEABIUnwindPersonalityName(), llvm::MCDataFragment::getContents(), llvm::SectionKind::getDataRel(), llvm::MCRegisterInfo::getEncodingValue(), llvm::MCSectionELF::getEntrySize(), llvm::MCDataFragment::getFixups(), llvm::MCSymbolData::getFlags(), llvm::MCSectionELF::getGroup(), llvm::MCFixup::getKindForSize(), llvm::SectionKind::getMetadata(), llvm::MCSymbol::getName(), llvm::MCSymbol::getSection(), llvm::MCSectionELF::getSectionName(), i, llvm::ARM::INVALID_FPU, llvm_unreachable, llvm::StringRef::lower(), llvm::MCAF_Code16, llvm::MCAF_Code32, llvm::MCAF_Code64, llvm::MCAF_SubsectionsViaSymbols, llvm::MCAF_SyntaxUnified, MRI, llvm::NUM_PERSONALITY_INDEX, llvm::cl::Prefix, llvm::MCInstPrinter::printRegName(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::report_fatal_error(), S, llvm::ARMBuildAttrs::Section, llvm::MCELF::SetBinding(), llvm::MCSymbolData::setExternal(), llvm::MCSymbolData::setFlags(), llvm::MCELF::SetType(), llvm::MCSymbol::setVariableValue(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::ELF::STB_LOCAL, llvm::tgtok::String, llvm::ELF::STT_NOTYPE, llvm::ARMBuildAttrs::Symbol, Type, llvm::ARMBuildAttrs::VFP_arch, llvm::MCSymbolRefExpr::VK_ARM_NONE, and llvm::MCSymbolRefExpr::VK_ARM_PREL31.