LLVM: ARMFastISel.cpp File Reference
LLVM API Documentation
ARMFastISel.cpp File Reference
#include "ARM.h"
#include "ARMBaseInstrInfo.h"
#include "ARMCallingConv.h"
#include "ARMConstantPoolValue.h"
#include "ARMSubtarget.h"
#include "ARMTargetMachine.h"
#include "MCTargetDesc/ARMAddressingModes.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/FastISel.h"
#include "llvm/CodeGen/FunctionLoweringInfo.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/Support/CallSite.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/GetElementPtrTypeIterator.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include "ARMGenFastISel.inc"
#include "ARMGenCallingConv.inc"
Namespaces
llvm
List of target independent CodeGen pass IDs.
Functions
static ARMCC::CondCodes getComparePred (CmpInst::Predicate Pred)
Variables
cl::opt< bool > EnableARMLongCalls
Function Documentation
static ARMCC::CondCodes getComparePred (CmpInst::Predicate Pred) static
Definition at line 1289 of file ARMFastISel.cpp.
References llvm::ISD::ADD, llvm::AddDefaultCC(), llvm::AddDefaultPred(), llvm::MachineInstrBuilder::addExternalSymbol(), llvm::MachineInstrBuilder::addGlobalAddress(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::MachineInstrBuilder::addRegMask(), llvm::CCValAssign::AExt, llvm::ARMCC::AL, llvm::CCState::AnalyzeCallOperands(), llvm::CCState::AnalyzeCallResult(), llvm::CCState::AnalyzeReturn(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_begin(), llvm::Function::arg_begin(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_end(), llvm::Function::arg_end(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_size(), llvm::CallingConv::ARM_AAPCS, llvm::CallingConv::ARM_AAPCS_VFP, llvm::CallingConv::ARM_APCS, llvm::array_lengthof(), llvm::ARM_AM::asr, llvm::CCValAssign::BCvt, llvm::ISD::BITCAST, llvm::XCoreISD::BL, llvm::BuildMI(), llvm::Attribute::ByVal, llvm::CallingConv::C, llvm::Call, CC, llvm::TargetRegisterClass::contains(), llvm::TargetOpcode::COPY, llvm::ARMConstantPoolConstant::Create(), llvm::RegState::Define, llvm::dyn_cast(), llvm::ARMCC::EQ, llvm::MachineInstr::eraseFromParent(), llvm::GlobalValue::ExternalLinkage, F(), llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FADD, llvm::CallingConv::Fast, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, llvm::TargetOptions::FloatABIType, llvm::ARMISD::FMSTAT, llvm::ISD::FMUL, llvm::Intrinsic::frameaddress, llvm::ISD::FSUB, llvm::CCValAssign::Full, llvm::ARMCC::GE, llvm::MCInstrInfo::get(), llvm::ConstantInt::get(), llvm::MemIntrinsic::getAlignment(), llvm::LoadInst::getAlignment(), llvm::Function::getAttributes(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledValue(), llvm::CallInst::getCalledValue(), llvm::TargetInstrInfo::getCallFrameDestroyOpcode(), llvm::TargetInstrInfo::getCallFrameSetupOpcode(), llvm::Function::getCallingConv(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCallingConv(), llvm::BranchInst::getCondition(), llvm::Value::getContext(), llvm::MemIntrinsic::getDestAddressSpace(), llvm::SequentialType::getElementType(), llvm::ARMBaseRegisterInfo::getFrameRegister(), llvm::ARMFunctionInfo::getGlobalBaseReg(), llvm::MachineOperand::getImm(), llvm::Type::getInt32PtrTy(), llvm::Type::getInt32Ty(), llvm::IntrinsicInst::getIntrinsicID(), llvm::CmpInst::getInversePredicate(), llvm::getKillRegState(), llvm::MemIntrinsic::getLength(), llvm::TargetLoweringBase::getLibcallCallingConv(), llvm::TargetLoweringBase::getLibcallName(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::CCState::getNextStackOffset(), llvm::User::getNumOperands(), llvm::MachineInstr::getNumOperands(), llvm::Instruction::getOpcode(), llvm::MachineInstr::getOpcode(), llvm::User::getOperand(), llvm::MachineInstr::getOperand(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::CmpInst::getPredicate(), llvm::MemIntrinsic::getRawDest(), llvm::MemTransferInst::getRawSource(), llvm::MachineOperand::getReg(), llvm::MCRegisterInfo::getRegClass(), llvm::TargetLoweringBase::getRegClassFor(), llvm::TargetMachine::getRegisterInfo(), llvm::TargetMachine::getRelocationModel(), llvm::GetReturnInfo(), llvm::APInt::getSExtValue(), llvm::EVT::getSimpleVT(), llvm::MVT::getSizeInBits(), llvm::ARM_AM::getSOImmVal(), llvm::ARM_AM::getSORegOpc(), llvm::MemTransferInst::getSourceAddressSpace(), llvm::BranchInst::getSuccessor(), llvm::ARM_AM::getT2SOImmVal(), llvm::GlobalValue::getType(), llvm::Value::getType(), llvm::CCValAssign::getValNo(), llvm::TargetLoweringBase::getValueType(), llvm::CCValAssign::getValVT(), llvm::ConstantInt::getZExtValue(), llvm::APInt::getZExtValue(), llvm::CallingConv::GHC, llvm::PPCISD::GlobalBaseReg, llvm::ARMCP::GOT, llvm::ARMCP::GOTOFF, GPRArgRegs, llvm::ARMCC::GT, llvm::FloatABI::Hard, llvm::AttributeSet::hasAttribute(), llvm::ARMSubtarget::hasDivide(), llvm::GlobalValue::hasHiddenVisibility(), llvm::GlobalValue::hasLocalLinkage(), llvm::Value::hasOneUse(), llvm::ARMSubtarget::hasV6Ops(), llvm::ARMSubtarget::hasVFP2(), llvm::ARMCC::HI, llvm::ARMCC::HS, i, I, llvm::MVT::i1, llvm::MVT::i128, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::RegState::Implicit, llvm::Attribute::InReg, int, llvm::ARMSubtarget::isAAPCS_ABI(), llvm::Type::isArrayTy(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), llvm::MachineOperand::isImm(), llvm::Type::isIntegerTy(), llvm::CCValAssign::isMemLoc(), llvm::CCValAssign::isRegLoc(), llvm::EVT::isSimple(), llvm::Type::isStructTy(), llvm::CallInst::isTailCall(), llvm::ARMSubtarget::isTargetELF(), llvm::CmpInst::isUnsigned(), llvm::FunctionType::isVarArg(), llvm::Function::isVarArg(), llvm::MVT::isVector(), llvm::Type::isVectorTy(), llvm::MVT::isVoid, llvm::Type::isVoidTy(), llvm::MemIntrinsic::isVolatile(), IT, llvm::TargetOpcode::KILL, llvm::ARMCC::LE, llvm_unreachable, llvm::ARMCC::LO, llvm::SPII::Load, llvm::ARMCC::LS, llvm::ARM_AM::lsl, llvm::ARM_AM::lsr, llvm::ARMCC::LT, llvm::Intrinsic::memcpy, llvm::Intrinsic::memmove, llvm::Intrinsic::memset, llvm::ARMCC::MI, llvm::ARMII::MO_PLT, MRI, llvm::ARMCC::NE, llvm::CCValAssign::needsCustom(), llvm::Attribute::Nest, llvm::ARM_AM::no_shift, llvm::TargetMachine::Options, llvm::ISD::OR, llvm::APIntOps::Or(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::paramHasAttr(), llvm::Reloc::PIC_, llvm::ARMCC::PL, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), R2, llvm::SmallVectorImpl< T >::reserve(), llvm::AArch64ISD::Ret, llvm::GC::Return, llvm::RTLIB::SDIV_I128, llvm::RTLIB::SDIV_I16, llvm::RTLIB::SDIV_I32, llvm::RTLIB::SDIV_I64, llvm::RTLIB::SDIV_I8, llvm::MCID::Select, llvm::MachineFrameInfo::setFrameAddressIsTaken(), llvm::ARMFunctionInfo::setGlobalBaseReg(), llvm::ISD::ArgFlagsTy::setOrigAlign(), llvm::ISD::ArgFlagsTy::setSExt(), llvm::ISD::ArgFlagsTy::setZExt(), llvm::CCValAssign::SExt, llvm::Attribute::SExt, Shift, llvm::MVT::SimpleTy, llvm::SmallVectorTemplateCommon< T >::size(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::RTLIB::SREM_I128, llvm::RTLIB::SREM_I16, llvm::RTLIB::SREM_I32, llvm::RTLIB::SREM_I64, llvm::RTLIB::SREM_I8, llvm::SPII::Store, llvm::Attribute::StructRet, llvm::ISD::SUB, std::swap(), llvm::A64SE::SXTB, llvm::A64SE::SXTH, llvm::SystemZISD::TM, llvm::ISD::TRAP, llvm::Intrinsic::trap, llvm::RTLIB::UDIV_I128, llvm::RTLIB::UDIV_I16, llvm::RTLIB::UDIV_I32, llvm::RTLIB::UDIV_I64, llvm::RTLIB::UDIV_I8, llvm::RTLIB::UNKNOWN_LIBCALL, llvm::RTLIB::UREM_I128, llvm::RTLIB::UREM_I16, llvm::RTLIB::UREM_I32, llvm::RTLIB::UREM_I64, llvm::RTLIB::UREM_I8, llvm::ARMSubtarget::useNaClTrap(), llvm::A64SE::UXTB, llvm::A64SE::UXTH, llvm::ARMCC::VC, llvm::ARMISD::VMOVDRR, llvm::ARMISD::VMOVRRD, llvm::ARMCC::VS, llvm::CCValAssign::ZExt, and llvm::Attribute::ZExt.
Variable Documentation
cl::opt<bool> EnableARMLongCalls
Referenced by FPCCToARMCC().