LLVM: ARMISelDAGToDAG.cpp File Reference
LLVM API Documentation
ARMISelDAGToDAG.cpp File Reference
#include "ARM.h"
#include "ARMBaseInstrInfo.h"
#include "ARMTargetMachine.h"
#include "MCTargetDesc/ARMAddressingModes.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetOptions.h"
#include "ARMGenDAGISel.inc"
Macros
#define DEBUG_TYPE "arm-isel"
Enumerations
enum AddrMode2Type
Functions
static bool isInt32Immediate (SDNode *N, unsigned &Imm)
static bool isInt32Immediate (SDValue N, unsigned &Imm)
static bool isOpcWithIntImmediate (SDNode *N, unsigned Opc, unsigned &Imm)
static bool isScaledConstantInRange (SDValue Node, int Scale, int RangeMin, int RangeMax, int &ScaledConstant)
Check whether a particular node is a constant value representable as (N * Scale) where (N in [RangeMin, RangeMax).
static SDValue getAL (SelectionDAG *CurDAG)
getAL - Returns a ARMCC::AL immediate node.
static unsigned getVLDSTRegisterUpdateOpcode (unsigned Opc)
Variables
static cl::opt< bool > DisableShifterOp ("disable-shifter-op", cl::Hidden, cl::desc("Disable isel of shifter-op"), cl::init(false))
static cl::opt< bool > CheckVMLxHazard ("check-vmlx-hazard", cl::Hidden, cl::desc("Check fp vmla / vmls hazard at isel time"), cl::init(true))
Macro Definition Documentation
#define DEBUG_TYPE "arm-isel"
Definition at line 14 of file ARMISelDAGToDAG.cpp.
Enumeration Type Documentation
enum AddrMode2Type
Definition at line 57 of file ARMISelDAGToDAG.cpp.
Function Documentation
static SDValue getAL (SelectionDAG * CurDAG) inline static
getAL - Returns a ARMCC::AL immediate node.
Definition at line 1444 of file ARMISelDAGToDAG.cpp.
References llvm::ARMCC::AL, Align, llvm::LSBaseSDNode::getAddressingMode(), llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::LoadSDNode::getExtensionType(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::LoadSDNode::getOffset(), llvm::EVT::getSimpleVT(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::A64DB::LD, N, llvm::MVT::Other, llvm::ISD::PRE_DEC, llvm::ISD::PRE_INC, llvm::TargetOpcode::REG_SEQUENCE, llvm::ISD::SEXTLOAD, llvm::MVT::SimpleTy, llvm::ISD::UNINDEXED, and llvm::NVPTX::PTXLdStInstCode::V2.
Referenced by getVLDSTRegisterUpdateOpcode().
static unsigned getVLDSTRegisterUpdateOpcode (unsigned Opc) static
Definition at line 1678 of file ARMISelDAGToDAG.cpp.
References llvm::ISD::ADD, Align, llvm::ISD::AND, llvm::Intrinsic::arm_ldrexd, llvm::Intrinsic::arm_neon_vld1, llvm::Intrinsic::arm_neon_vld2, llvm::Intrinsic::arm_neon_vld2lane, llvm::Intrinsic::arm_neon_vld3, llvm::Intrinsic::arm_neon_vld3lane, llvm::Intrinsic::arm_neon_vld4, llvm::Intrinsic::arm_neon_vld4lane, llvm::Intrinsic::arm_neon_vst1, llvm::Intrinsic::arm_neon_vst2, llvm::Intrinsic::arm_neon_vst2lane, llvm::Intrinsic::arm_neon_vst3, llvm::Intrinsic::arm_neon_vst3lane, llvm::Intrinsic::arm_neon_vst4, llvm::Intrinsic::arm_neon_vst4lane, llvm::Intrinsic::arm_neon_vtbl2, llvm::Intrinsic::arm_neon_vtbl3, llvm::Intrinsic::arm_neon_vtbl4, llvm::Intrinsic::arm_neon_vtbx2, llvm::Intrinsic::arm_neon_vtbx3, llvm::Intrinsic::arm_neon_vtbx4, llvm::Intrinsic::arm_strexd, llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_XOR, llvm::ISD::ATOMIC_STORE, llvm::ISD::ATOMIC_SWAP, llvm::ISD::BasicBlock, llvm::ARMISD::BRCOND, llvm::ARMISD::BUILD_VECTOR, llvm::ISD::CONCAT_VECTORS, llvm::ISD::Constant, llvm::CountTrailingOnes_32(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::dyn_cast(), llvm::TargetOpcode::EXTRACT_SUBREG, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FrameIndex, llvm::ConstantInt::get(), getAL(), llvm::InlineAsm::getFlagWord(), llvm::InlineAsm::getFlagWordForMatchingOp(), llvm::InlineAsm::getFlagWordForRegClass(), llvm::SDNode::getGluedNode(), llvm::SDNode::getGluedUser(), llvm::Type::getInt32Ty(), llvm::InlineAsm::getKind(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::InlineAsm::getNumOperandRegisters(), llvm::SDNode::getNumOperands(), llvm::SDNode::getNumValues(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MemSDNode::getOrdering(), getReg(), llvm::SDValue::getResNo(), llvm::ARM_AM::getShiftOpcForNode(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::ARM_AM::getSOImmVal(), llvm::ARM_AM::getSORegOpc(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::Glue, llvm::SDNode::hasOneUse(), llvm::InlineAsm::hasRegClassConstraint(), i, I, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::X86II::Imm16, llvm::TargetOpcode::IMPLICIT_DEF, llvm::ISD::INLINEASM, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::EVT::is128BitVector(), llvm::EVT::is64BitVector(), isInt32Immediate(), llvm::SDNode::isMachineOpcode(), isOpcWithIntImmediate(), llvm::isPowerOf2_32(), llvm::ARM_AM::isSOImmTwoPartVal(), llvm::ARM_AM::isThumbImmShiftedVal(), llvm::InlineAsm::isUseOperandTiedToDef(), llvm_unreachable, llvm::ISD::LOAD, llvm::Log2_32(), llvm::ARM_AM::lsl, MRI, llvm::ISD::MUL, N, llvm::SDNode::op_begin(), llvm::SDNode::op_end(), llvm::ISD::OR, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::ISD::Register, llvm::AArch64ISD::SBFX, llvm::MCID::Select, llvm::SDNode::setNodeId(), llvm::ISD::SHL, llvm::MVT::SimpleTy, llvm::SmallVectorTemplateCommon< T >::size(), llvm::ARMISD::SMLAL, SMLAL(), llvm::ISD::SMUL_LOHI, llvm::ISD::SRA, llvm::ISD::SRL, T1, llvm::AArch64ISD::UBFX, llvm::ARMISD::UMLAL, llvm::ISD::UMUL_LOHI, llvm::MVT::Untyped, llvm::MVT::v16i8, llvm::MVT::v1i64, llvm::MVT::v2f32, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v8i16, llvm::MVT::v8i64, llvm::MVT::v8i8, llvm::ARMISD::VLD1_UPD, llvm::ARMISD::VLD2_UPD, llvm::ARMISD::VLD2DUP, llvm::ARMISD::VLD2DUP_UPD, llvm::ARMISD::VLD2LN_UPD, llvm::ARMISD::VLD3_UPD, llvm::ARMISD::VLD3DUP, llvm::ARMISD::VLD3DUP_UPD, llvm::ARMISD::VLD3LN_UPD, llvm::ARMISD::VLD4_UPD, llvm::ARMISD::VLD4DUP, llvm::ARMISD::VLD4DUP_UPD, llvm::ARMISD::VLD4LN_UPD, llvm::ARMISD::VMOVRRD, llvm::ARMISD::VST1_UPD, llvm::ARMISD::VST2_UPD, llvm::ARMISD::VST2LN_UPD, llvm::ARMISD::VST3_UPD, llvm::ARMISD::VST3LN_UPD, llvm::ARMISD::VST4_UPD, llvm::ARMISD::VST4LN_UPD, llvm::ARMISD::VTBL1, llvm::ARMISD::VTBL2, llvm::ARMISD::VTRN, llvm::ARMISD::VUZP, llvm::ARMISD::VZIP, and llvm::ISD::XOR.
static bool isInt32Immediate (SDNode * N, unsigned & Imm) static
isInt32Immediate - This method tests to see if the node is a 32-bit constant operand. If so Imm will receive the 32-bit value.
Definition at line 282 of file ARMISelDAGToDAG.cpp.
References llvm::ISD::Constant, llvm::SDNode::getOpcode(), llvm::SDNode::getValueType(), llvm::MVT::i32, and N.
Referenced by getVLDSTRegisterUpdateOpcode(), isInt32Immediate(), and isOpcWithIntImmediate().
static bool isInt32Immediate (SDValue N, unsigned & Imm) static
Definition at line 292 of file ARMISelDAGToDAG.cpp.
References llvm::SDValue::getNode(), and isInt32Immediate().
static bool isOpcWithIntImmediate (SDNode * N, unsigned Opc, unsigned & Imm) static
Definition at line 299 of file ARMISelDAGToDAG.cpp.
References llvm::SDValue::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), and isInt32Immediate().
Referenced by getVLDSTRegisterUpdateOpcode(), and isScaledConstantInRange().
static bool isScaledConstantInRange (SDValue Node, int Scale, int RangeMin, int RangeMax, int & ScaledConstant) static
Check whether a particular node is a constant value representable as (N * Scale) where (N in [RangeMin, RangeMax).
Parameters
ScaledConstant [out] - On success, the pre-scaled constant value.
Definition at line 308 of file ARMISelDAGToDAG.cpp.
References llvm::ARM_AM::add, llvm::ISD::ADD, Align, llvm::ISD::AND, CheckVMLxHazard, llvm::ISD::CopyToReg, llvm::countTrailingZeros(), DisableShifterOp, llvm::dyn_cast(), llvm::ISD::FrameIndex, llvm::LSBaseSDNode::getAddressingMode(), llvm::ARM_AM::getAM2Opc(), llvm::ARM_AM::getAM3Opc(), llvm::ARM_AM::getAM5Opc(), llvm::SDNode::getMachineOpcode(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::MCInstrDesc::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::RegisterSDNode::getReg(), llvm::ARM_AM::getShiftOpcForNode(), llvm::EVT::getSizeInBits(), llvm::ARM_AM::getSORegOpc(), llvm::ConstantSDNode::getZExtValue(), llvm::SDValue::hasOneUse(), llvm::SDNode::hasOneUse(), I, llvm::MVT::i32, int, llvm::ARMBaseInstrInfo::isFpMLxInstruction(), llvm::SDNode::isMachineOpcode(), llvm::ConstantSDNode::isNullValue(), isOpcWithIntImmediate(), llvm::isPowerOf2_32(), llvm::ISD::LOAD, llvm::Log2_32(), llvm::ARM_AM::lsl, llvm::MCInstrDesc::mayStore(), llvm::ISD::MUL, N, NC, llvm::ARM_AM::no_shift, llvm::CodeGenOpt::None, llvm::ISD::OR, llvm::ARMISD::PIC_ADD, llvm::ISD::POST_INC, llvm::ISD::PRE_INC, Shift, llvm::ISD::SHL, llvm::ISD::SRL, llvm::ARM_AM::sub, llvm::ISD::SUB, std::swap(), llvm::ISD::TargetConstantPool, llvm::ISD::TargetGlobalAddress, TII, llvm::SystemZISD::TM, llvm::SDNode::use_begin(), llvm::ARMISD::VMOVRRD, and llvm::ARMISD::Wrapper.
Variable Documentation
cl::opt<bool> CheckVMLxHazard("check-vmlx-hazard", cl::Hidden, cl::desc("Check fp vmla / vmls hazard at isel time"), cl::init(true)) static
Referenced by isScaledConstantInRange().
cl::opt<bool> DisableShifterOp("disable-shifter-op", cl::Hidden, cl::desc("Disable isel of shifter-op"), cl::init(false)) static
Referenced by isScaledConstantInRange().