LLVM: ARMJITInfo.cpp File Reference
LLVM API Documentation
ARMJITInfo.cpp File Reference
#include "ARMJITInfo.h"
#include "ARM.h"
#include "ARMConstantPoolValue.h"
#include "ARMRelocations.h"
#include "ARMSubtarget.h"
#include "llvm/CodeGen/JITCodeEmitter.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Memory.h"
#include "llvm/Support/raw_ostream.h"
#include <cstdlib>
Macros
#define DEBUG_TYPE "jit"
#define __USER_LABEL_PREFIX__
#define GETASMPREFIX2(X) #X
#define GETASMPREFIX(X) GETASMPREFIX2(X)
#define ASMPREFIX GETASMPREFIX(__USER_LABEL_PREFIX__)
Functions
void ARMCompilationCallback ()
void ARMCompilationCallbackC (intptr_t StubAddr)
Variables
static TargetJITInfo::JITCompilerFn JITCompilerFunction
Macro Definition Documentation
#define __USER_LABEL_PREFIX__
Definition at line 39 of file ARMJITInfo.cpp.
#define ASMPREFIX GETASMPREFIX(__USER_LABEL_PREFIX__)
Definition at line 43 of file ARMJITInfo.cpp.
#define DEBUG_TYPE "jit"
Definition at line 14 of file ARMJITInfo.cpp.
#define GETASMPREFIX (X) GETASMPREFIX2(X)
Definition at line 42 of file ARMJITInfo.cpp.
#define GETASMPREFIX2 (X) #X
Definition at line 41 of file ARMJITInfo.cpp.
Function Documentation
void ARMCompilationCallback ()
Definition at line 106 of file ARMJITInfo.cpp.
References llvm_unreachable.
Referenced by llvm::ARMJITInfo::emitFunctionStub(), and llvm::ARMJITInfo::getLazyResolverFunction().
void ARMCompilationCallbackC (intptr_t StubAddr)
ARMCompilationCallbackC - This is the target-specific function invoked by the function stub when we did not know the real target of a call. This function must locate the start of the stub or call site and pass it into the JIT compiler function.
Definition at line 116 of file ARMJITInfo.cpp.
References JITCompilerFunction, llvm_unreachable, llvm::sys::Memory::setRangeExecutable(), and llvm::sys::Memory::setRangeWritable().
Variable Documentation
TargetJITInfo::JITCompilerFn JITCompilerFunction static
JITCompilerFunction - This contains the address of the JIT function used to compile a function lazily.
Definition at line 35 of file ARMJITInfo.cpp.
Referenced by ARMCompilationCallbackC(), and llvm::ARMJITInfo::getLazyResolverFunction().