LLVM: ARMLoadStoreOptimizer.cpp File Reference
LLVM API Documentation
ARMLoadStoreOptimizer.cpp File Reference
#include "ARM.h"
#include "ARMBaseInstrInfo.h"
#include "ARMBaseRegisterInfo.h"
#include "ARMMachineFunctionInfo.h"
#include "MCTargetDesc/ARMAddressingModes.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/CodeGen/SelectionDAGNodes.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetRegisterInfo.h"
Namespaces
llvm
List of target independent CodeGen pass IDs.
llvm::ARM_AM
ARM_AM - ARM Addressing Mode Stuff.
Macros
#define DEBUG_TYPE "arm-ldst-opt"
Functions
STATISTIC (NumLDMGened,"Number of ldm instructions generated")
STATISTIC (NumSTMGened,"Number of stm instructions generated")
STATISTIC (NumVLDMGened,"Number of vldm instructions generated")
STATISTIC (NumVSTMGened,"Number of vstm instructions generated")
STATISTIC (NumLdStMoved,"Number of load / store instructions moved")
STATISTIC (NumLDRDFormed,"Number of ldrd created before allocation")
STATISTIC (NumSTRDFormed,"Number of strd created before allocation")
STATISTIC (NumLDRD2LDM,"Number of ldrd instructions turned back into ldm")
STATISTIC (NumSTRD2STM,"Number of strd instructions turned back into stm")
STATISTIC (NumLDRD2LDR,"Number of ldrd instructions turned back into ldr's")
STATISTIC (NumSTRD2STR,"Number of strd instructions turned back into str's")
static int getLoadStoreMultipleOpcode (int Opcode, ARM_AM::AMSubMode Mode)
AMSubMode llvm::ARM_AM::getLoadStoreMultipleSubMode (int Opcode)
static bool isT2i32Load (unsigned Opc)
static bool isi32Load (unsigned Opc)
static bool isT2i32Store (unsigned Opc)
static bool isi32Store (unsigned Opc)
static bool definesCPSR (MachineInstr *MI)
static bool isMatchingDecrement (MachineInstr *MI, unsigned Base, unsigned Bytes, unsigned Limit, ARMCC::CondCodes Pred, unsigned PredReg)
static bool isMatchingIncrement (MachineInstr *MI, unsigned Base, unsigned Bytes, unsigned Limit, ARMCC::CondCodes Pred, unsigned PredReg)
static unsigned getLSMultipleTransferSize (MachineInstr *MI)
static unsigned getUpdatingLSMultipleOpcode (unsigned Opc, ARM_AM::AMSubMode Mode)
static unsigned getPreIndexedLoadStoreOpcode (unsigned Opc, ARM_AM::AddrOpc Mode)
static unsigned getPostIndexedLoadStoreOpcode (unsigned Opc, ARM_AM::AddrOpc Mode)
static bool isMemoryOp (const MachineInstr *MI)
static int getMemoryOpOffset (const MachineInstr *MI)
static void InsertLDR_STR (MachineBasicBlock &MBB, MachineBasicBlock::iterator &MBBI, int Offset, bool isDef, DebugLoc dl, unsigned NewOpc, unsigned Reg, bool RegDeadKill, bool RegUndef, unsigned BaseReg, bool BaseKill, bool BaseUndef, bool OffKill, bool OffUndef, ARMCC::CondCodes Pred, unsigned PredReg, const TargetInstrInfo *TII, bool isT2)
static bool IsSafeAndProfitableToMove (bool isLd, unsigned Base, MachineBasicBlock::iterator I, MachineBasicBlock::iterator E, SmallPtrSet< MachineInstr *, 4 > &MemOps, SmallSet< unsigned, 4 > &MemRegs, const TargetRegisterInfo *TRI)
static void concatenateMemOperands (MachineInstr *MI, MachineInstr *Op0, MachineInstr *Op1)
Copy Op0 and Op1 operands into a new array assigned to MI.
Macro Definition Documentation
#define DEBUG_TYPE "arm-ldst-opt"
Definition at line 15 of file ARMLoadStoreOptimizer.cpp.
Function Documentation
static void concatenateMemOperands (MachineInstr * MI, MachineInstr * Op0, MachineInstr * Op1) static
Copy Op0 and Op1 operands into a new array assigned to MI.
Definition at line 1639 of file ARMLoadStoreOptimizer.cpp.
References llvm::ARM_AM::add, llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::ARMCC::AL, Align, llvm::MachineFunction::allocateMemRefsArray(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::clear(), llvm::SmallVectorImpl< T >::clear(), llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::dbgs(), DEBUG, llvm::RegState::Define, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::erase(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::find(), llvm::MCInstrInfo::get(), llvm::ARM_AM::getAM3Opc(), llvm::Function::getContext(), llvm::MachineInstr::getDebugLoc(), llvm::getInstrPredicate(), llvm::Type::getInt64Ty(), getLoadStoreMultipleOpcode(), getLSMultipleTransferSize(), getMemoryOpOffset(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), getReg(), llvm::TargetInstrInfo::getRegClass(), llvm::MachineInstr::hasOneMemOperand(), i, llvm::ARM_AM::ia, llvm::SmallSet< T, N, C >::insert(), llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::MachineInstr::isCall(), llvm::MachineInstr::isDebugValue(), isi32Load(), isMemoryOp(), IsSafeAndProfitableToMove(), llvm::MachineInstr::isTerminator(), llvm::MachineInstr::memoperands_begin(), llvm::MachineInstr::memoperands_empty(), llvm::MachineInstr::memoperands_end(), llvm::A64CC::MI, MRI, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::pop_back(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::ARMRI::RegPairEven, llvm::ARMRI::RegPairOdd, llvm::MachineInstr::setMemRefs(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::size(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::MachineBasicBlock::splice(), and llvm::ARM_AM::sub.
static bool definesCPSR (MachineInstr * MI) static
Definition at line 595 of file ARMLoadStoreOptimizer.cpp.
References llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), i, llvm::MachineOperand::isDead(), llvm::MachineOperand::isDef(), and llvm::MachineOperand::isReg().
Referenced by llvm::ARMTargetLowering::AdjustInstrPostInstrSelection(), isMatchingDecrement(), and isMatchingIncrement().
static int getLoadStoreMultipleOpcode (int Opcode, ARM_AM::AMSubMode Mode) static
Definition at line 141 of file ARMLoadStoreOptimizer.cpp.
References llvm::ARM_AM::da, llvm::ARM_AM::db, llvm::ARM_AM::ia, llvm::ARM_AM::ib, and llvm_unreachable.
Referenced by concatenateMemOperands(), and isi32Store().
static unsigned getLSMultipleTransferSize (MachineInstr * MI) inline static
Definition at line 675 of file ARMLoadStoreOptimizer.cpp.
References llvm::MachineInstr::getDesc(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getNumOperands(), and llvm::MachineInstr::getOpcode().
Referenced by concatenateMemOperands(), getPostIndexedLoadStoreOpcode(), getUpdatingLSMultipleOpcode(), and InsertLDR_STR().
static int getMemoryOpOffset (const MachineInstr * MI) static
Definition at line 1128 of file ARMLoadStoreOptimizer.cpp.
References llvm::ARM_AM::getAM3Offset(), llvm::ARM_AM::getAM3Op(), llvm::ARM_AM::getAM5Offset(), llvm::ARM_AM::getAM5Op(), llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), and llvm::ARM_AM::sub.
Referenced by concatenateMemOperands(), and InsertLDR_STR().
static unsigned getPostIndexedLoadStoreOpcode (unsigned Opc, ARM_AM::AddrOpc Mode) static
Definition at line 898 of file ARMLoadStoreOptimizer.cpp.
References llvm::ARM_AM::add, llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::RegState::Define, llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::erase(), llvm::MCInstrInfo::get(), llvm::ARM_AM::getAM2Opc(), llvm::ARM_AM::getAM5Offset(), llvm::MachineInstr::getDebugLoc(), llvm::getDefRegState(), llvm::MachineOperand::getImm(), llvm::getInstrPredicate(), llvm::getKillRegState(), getLSMultipleTransferSize(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), getPreIndexedLoadStoreOpcode(), llvm::MachineOperand::getReg(), I, isi32Load(), isi32Store(), llvm::MachineOperand::isKill(), isMatchingDecrement(), isMatchingIncrement(), llvm_unreachable, llvm::A64CC::MI, llvm::next(), llvm::ARM_AM::no_shift, llvm::prior(), llvm::ARM_AM::sub, and TII.
static unsigned getPreIndexedLoadStoreOpcode (unsigned Opc, ARM_AM::AddrOpc Mode) static
Definition at line 873 of file ARMLoadStoreOptimizer.cpp.
References llvm::ARM_AM::add, and llvm_unreachable.
Referenced by getPostIndexedLoadStoreOpcode().
static unsigned getUpdatingLSMultipleOpcode (unsigned Opc, ARM_AM::AMSubMode Mode) static
Definition at line 711 of file ARMLoadStoreOptimizer.cpp.
References llvm::MachineInstrBuilder::addOperand(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::ARM_AM::da, llvm::ARM_AM::db, llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::erase(), llvm::MachineInstr::getDebugLoc(), llvm::getDefRegState(), llvm::getInstrPredicate(), llvm::getKillRegState(), llvm::ARM_AM::getLoadStoreMultipleSubMode(), getLSMultipleTransferSize(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), i, I, llvm::ARM_AM::ia, llvm::ARM_AM::ib, llvm::MachineOperand::isKill(), isMatchingDecrement(), isMatchingIncrement(), llvm_unreachable, llvm::MachineInstr::memoperands_begin(), llvm::MachineInstr::memoperands_end(), llvm::A64CC::MI, llvm::next(), llvm::prior(), llvm::MachineInstr::setMemRefs(), and TII.
static void InsertLDR_STR (MachineBasicBlock & MBB, MachineBasicBlock::iterator & MBBI, int Offset, bool isDef, DebugLoc dl, unsigned NewOpc, unsigned Reg, bool RegDeadKill, bool RegUndef, unsigned BaseReg, bool BaseKill, bool BaseUndef, bool OffKill, bool OffUndef, ARMCC::CondCodes Pred, unsigned PredReg, const TargetInstrInfo * TII, bool isT2) static
Definition at line 1152 of file ARMLoadStoreOptimizer.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::ARMCC::AL, llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::BuildMI(), llvm::SmallVectorImpl< T >::clear(), llvm::MachineInstr::copyImplicitOps(), llvm::MachineBasicBlock::empty(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::MachineBasicBlock::erase(), llvm::MCInstrInfo::get(), llvm::TargetMachine::getDataLayout(), llvm::getDeadRegState(), llvm::getDefRegState(), llvm::MachineFunction::getInfo(), llvm::TargetMachine::getInstrInfo(), llvm::getInstrPredicate(), llvm::getKillRegState(), llvm::MachineBasicBlock::getLastNonDebugInstr(), getLSMultipleTransferSize(), getMemoryOpOffset(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::TargetMachine::getRegisterInfo(), llvm::TargetMachine::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::getUndefRegState(), llvm::ARMSubtarget::hasV5TOps(), i, I, llvm::MachineOperand::isDead(), llvm::MachineOperand::isDef(), isi32Load(), llvm::MachineOperand::isKill(), isMemoryOp(), llvm::MachineOperand::isUndef(), llvm::A64CC::MI, MRI, llvm::prior(), llvm::MachineInstr::setDesc(), llvm::MachineOperand::setReg(), llvm::SmallVectorTemplateCommon< T >::size(), TII, and llvm::SystemZISD::TM.
static bool isi32Load (unsigned Opc) static
Definition at line 270 of file ARMLoadStoreOptimizer.cpp.
References isT2i32Load().
Referenced by concatenateMemOperands(), getPostIndexedLoadStoreOpcode(), InsertLDR_STR(), and isi32Store().
static bool isi32Store (unsigned Opc) static
Definition at line 278 of file ARMLoadStoreOptimizer.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::BuildMI(), llvm::SmallSet< T, N, C >::count(), llvm::ARM_AM::da, llvm::ARM_AM::db, llvm::MachineInstr::definesRegister(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::MachineBasicBlock::erase(), llvm::MachineInstr::findRegisterUseOperand(), llvm::getDefRegState(), llvm::getKillRegState(), getLoadStoreMultipleOpcode(), llvm::MachineOperand::getReg(), llvm::ARM_AM::getSOImmVal(), llvm::ARM_AM::getT2SOImmVal(), i, I, llvm::ARM_AM::ia, llvm::ARM_AM::ib, llvm::RegState::ImplicitDefine, llvm::SmallSet< T, N, C >::insert(), isi32Load(), llvm::MachineOperand::isKill(), isT2i32Store(), llvm::MachineOperand::isUndef(), llvm::MachineOperandIteratorBase::isValid(), j(), llvm::A64CC::MI, llvm::prior(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::ArrayRef< T >::size(), llvm::MachineBasicBlock::size(), and TII.
Referenced by getPostIndexedLoadStoreOpcode().
static bool isMatchingDecrement (MachineInstr * MI, unsigned Base, unsigned Bytes, unsigned Limit, ARMCC::CondCodes Pred, unsigned PredReg) static
Definition at line 609 of file ARMLoadStoreOptimizer.cpp.
References definesCPSR(), llvm::MachineOperand::getImm(), llvm::getInstrPredicate(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), and llvm::MachineOperand::getReg().
Referenced by getPostIndexedLoadStoreOpcode(), and getUpdatingLSMultipleOpcode().
static bool isMatchingIncrement (MachineInstr * MI, unsigned Base, unsigned Bytes, unsigned Limit, ARMCC::CondCodes Pred, unsigned PredReg) static
Definition at line 642 of file ARMLoadStoreOptimizer.cpp.
References definesCPSR(), llvm::MachineOperand::getImm(), llvm::getInstrPredicate(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), and llvm::MachineOperand::getReg().
Referenced by getPostIndexedLoadStoreOpcode(), and getUpdatingLSMultipleOpcode().
static bool isMemoryOp (const MachineInstr * MI) static
isMemoryOp - Returns true if instruction is a memory operation that this pass is capable of operating on.
Definition at line 1063 of file ARMLoadStoreOptimizer.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineMemOperand::getAlignment(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::hasOneMemOperand(), i, llvm::MachineOperand::isReg(), llvm::MachineOperand::isUndef(), llvm::MachineMemOperand::isVolatile(), llvm::MachineInstr::memoperands_begin(), and llvm::prior().
Referenced by concatenateMemOperands(), and InsertLDR_STR().
static bool IsSafeAndProfitableToMove (bool isLd, unsigned Base, MachineBasicBlock::iterator I, MachineBasicBlock::iterator E, SmallPtrSet< MachineInstr *, 4 > & MemOps, SmallSet< unsigned, 4 > & MemRegs, const TargetRegisterInfo * TRI) static
Definition at line 1591 of file ARMLoadStoreOptimizer.cpp.
References llvm::SmallSet< T, N, C >::count(), llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::MachineOperand::getReg(), llvm::SmallSet< T, N, C >::insert(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), j(), llvm::TargetRegisterInfo::regsOverlap(), and llvm::SmallSet< T, N, C >::size().
Referenced by concatenateMemOperands().
static bool isT2i32Load (unsigned Opc) static
Definition at line 266 of file ARMLoadStoreOptimizer.cpp.
Referenced by isi32Load().
static bool isT2i32Store (unsigned Opc) static
Definition at line 274 of file ARMLoadStoreOptimizer.cpp.
Referenced by isi32Store().
STATISTIC (NumLDMGened , "Number of ldm instructions generated")
STATISTIC (NumSTMGened , "Number of stm instructions generated")
STATISTIC (NumVLDMGened , "Number of vldm instructions generated")
STATISTIC (NumVSTMGened , "Number of vstm instructions generated")
STATISTIC (NumLdStMoved , "Number of load / store instructions moved")
STATISTIC (NumLDRDFormed , "Number of ldrd created before allocation")
STATISTIC (NumSTRDFormed , "Number of strd created before allocation")
STATISTIC (NumLDRD2LDM , "Number of ldrd instructions turned back into ldm")
STATISTIC (NumSTRD2STM , "Number of strd instructions turned back into stm")
STATISTIC (NumLDRD2LDR , "Number of ldrd instructions turned back into ldr's")
STATISTIC (NumSTRD2STR , "Number of strd instructions turned back into str's")