LLVM: ARMMCExpr.cpp File Reference
LLVM API Documentation
ARMMCExpr.cpp File Reference
#include "ARMMCExpr.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
Macros
#define DEBUG_TYPE "armmcexpr"
Functions
static void AddValueSymbols_ (const MCExpr *Value, MCAssembler *Asm)
Macro Definition Documentation
#define DEBUG_TYPE "armmcexpr"
Definition at line 10 of file ARMMCExpr.cpp.
Function Documentation
static void AddValueSymbols_ (const MCExpr * Value, MCAssembler * Asm) static
Definition at line 45 of file ARMMCExpr.cpp.
References llvm::HexStyle::Asm, llvm::MCExpr::Binary, llvm::MCExpr::Constant, llvm::MCExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCAssembler::getOrCreateSymbolData(), llvm::MCBinaryExpr::getRHS(), llvm::ARMMCExpr::getSubExpr(), llvm_unreachable, llvm::MCExpr::SymbolRef, llvm::MCExpr::Target, and llvm::MCExpr::Unary.
Referenced by llvm::ARMMCExpr::AddValueSymbols().