LLVM: ARMMCCodeEmitter.cpp File Reference
LLVM API Documentation
ARMMCCodeEmitter.cpp File Reference
#include "MCTargetDesc/ARMMCTargetDesc.h"
#include "MCTargetDesc/ARMAddressingModes.h"
#include "MCTargetDesc/ARMBaseInfo.h"
#include "MCTargetDesc/ARMFixupKinds.h"
#include "MCTargetDesc/ARMMCExpr.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/raw_ostream.h"
#include "ARMGenMCCodeEmitter.inc"
Macros
#define DEBUG_TYPE "mccodeemitter"
Functions
STATISTIC (MCNumEmitted,"Number of MC instructions emitted.")
STATISTIC (MCNumCPRelocations,"Number of constant pool relocations created.")
static uint32_t getBranchTargetOpValue (const MCInst &MI, unsigned OpIdx, unsigned FixupKind, SmallVectorImpl< MCFixup > &Fixups)
static int32_t encodeThumbBLOffset (int32_t offset)
static bool HasConditionalBranch (const MCInst &MI)
Return true if this branch has a non-always predication.
static bool EvaluateAsPCRel (const MCExpr *Expr)
Macro Definition Documentation
#define DEBUG_TYPE "mccodeemitter"
Definition at line 14 of file ARMMCCodeEmitter.cpp.
Function Documentation
static int32_t encodeThumbBLOffset (int32_t offset) static
Definition at line 492 of file ARMMCCodeEmitter.cpp.
References llvm::ARM::fixup_arm_thumb_bcc, llvm::ARM::fixup_arm_thumb_bl, llvm::ARM::fixup_arm_thumb_blx, llvm::ARM::fixup_arm_thumb_br, llvm::ARM::fixup_arm_thumb_cb, getBranchTargetOpValue(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isExpr(), and S.
static bool EvaluateAsPCRel (const MCExpr * Expr) static
Definition at line 890 of file ARMMCCodeEmitter.cpp.
References llvm::LibFunc::abs, llvm::ARM_AM::add, Align, llvm::ARM_AM::asr, llvm::MCExpr::Binary, llvm::countLeadingZeros(), llvm::countTrailingZeros(), llvm::MCFixup::Create(), llvm::ARM::fixup_arm_movt_hi16, llvm::ARM::fixup_arm_movt_hi16_pcrel, llvm::ARM::fixup_arm_movw_lo16, llvm::ARM::fixup_arm_movw_lo16_pcrel, llvm::ARM::fixup_arm_pcrel_10, llvm::ARM::fixup_arm_pcrel_10_unscaled, llvm::ARM::fixup_arm_thumb_cp, llvm::ARM::fixup_t2_movt_hi16, llvm::ARM::fixup_t2_movt_hi16_pcrel, llvm::ARM::fixup_t2_movw_lo16, llvm::ARM::fixup_t2_movw_lo16_pcrel, llvm::ARM::fixup_t2_pcrel_10, llvm::ARMII::FormMask, llvm::ARM_AM::getAM2Offset(), llvm::ARM_AM::getAM2Op(), llvm::ARM_AM::getAM2ShiftOpc(), llvm::ARM_AM::getAM3Offset(), llvm::ARM_AM::getAM3Op(), llvm::ARM_AM::getAM5Offset(), llvm::ARM_AM::getAM5Op(), getBranchTargetOpValue(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::ARMMCExpr::getKind(), llvm::MCExpr::getKind(), llvm::MCInst::getLoc(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCInstrDesc::getSize(), llvm::ARM_AM::getSORegOffset(), llvm::ARM_AM::getSORegShOp(), llvm::ARMMCExpr::getSubExpr(), I, llvm::X86II::Imm8, llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), isReg(), llvm::MCOperand::isReg(), llvm_unreachable, llvm::ARM_AM::lsl, llvm::ARM_AM::lsr, llvm::ARMII::Pseudo, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::ARMII::RegRsShift, llvm::ARM_AM::ror, llvm::ARM_AM::rrx, llvm::MCExpr::SymbolRef, llvm::MCExpr::Target, llvm::MCInstrDesc::TSFlags, llvm::ARMMCExpr::VK_ARM_HI16, and llvm::ARMMCExpr::VK_ARM_LO16.
static uint32_t getBranchTargetOpValue (const MCInst & MI, unsigned OpIdx, unsigned FixupKind, SmallVectorImpl< MCFixup > & Fixups) static
getBranchTargetOpValue - Helper function to get the branch target operand, which is either an immediate or requires a fixup.
Definition at line 474 of file ARMMCCodeEmitter.cpp.
References llvm::MCFixup::Create(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getLoc(), llvm::MCInst::getOperand(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by encodeThumbBLOffset(), EvaluateAsPCRel(), HasConditionalBranch(), and LowerDextDins().
static bool HasConditionalBranch (const MCInst & MI) static
Return true if this branch has a non-always predication.
Definition at line 565 of file ARMMCCodeEmitter.cpp.
References llvm::ARMCC::AL, llvm::MCFixup::Create(), false, llvm::ARM::fixup_arm_adr_pcrel_12, llvm::ARM::fixup_arm_blx, llvm::ARM::fixup_arm_condbl, llvm::ARM::fixup_arm_condbranch, llvm::ARM::fixup_arm_ldst_pcrel_12, llvm::ARM::fixup_arm_uncondbl, llvm::ARM::fixup_arm_uncondbranch, llvm::ARM::fixup_t2_adr_pcrel_12, llvm::ARM::fixup_t2_condbranch, llvm::ARM::fixup_t2_ldst_pcrel_12, llvm::ARM::fixup_t2_pcrel_10, llvm::ARM::fixup_t2_uncondbranch, llvm::ARM::fixup_thumb_adr_pcrel_10, getBranchTargetOpValue(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getLoc(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::ARM_AM::getSOImmVal(), i, I, llvm::X86II::Imm8, llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
STATISTIC (MCNumEmitted , "Number of MC instructions emitted.")
STATISTIC (MCNumCPRelocations , "Number of constant pool relocations created.")