LLVM: ARMMachObjectWriter.cpp File Reference
LLVM API Documentation
ARMMachObjectWriter.cpp File Reference
#include "MCTargetDesc/ARMMCTargetDesc.h"
#include "MCTargetDesc/ARMBaseInfo.h"
#include "MCTargetDesc/ARMFixupKinds.h"
#include "llvm/ADT/Twine.h"
#include "llvm/MC/MCAsmLayout.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixup.h"
#include "llvm/MC/MCFixupKindInfo.h"
#include "llvm/MC/MCMachOSymbolFlags.h"
#include "llvm/MC/MCMachObjectWriter.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MachO.h"
Functions
static bool getARMFixupKindMachOInfo (unsigned Kind, unsigned &RelocType, unsigned &Log2Size)
Function Documentation
static bool getARMFixupKindMachOInfo (unsigned Kind, unsigned & RelocType, unsigned & Log2Size) static
Definition at line 63 of file ARMMachObjectWriter.cpp.
References llvm::ARM_PROC::A, llvm::MachObjectWriter::addRelocation(), llvm::MachO::ARM_RELOC_BR24, llvm::MachO::ARM_RELOC_HALF, llvm::MachO::ARM_RELOC_HALF_SECTDIFF, llvm::MachO::ARM_RELOC_LOCAL_SECTDIFF, llvm::MachO::ARM_RELOC_PAIR, llvm::MachO::ARM_RELOC_SECTDIFF, llvm::MachO::ARM_RELOC_VANILLA, llvm::MachO::ARM_THUMB_RELOC_BR22, llvm::HexStyle::Asm, B, llvm::MachObjectWriter::doesSymbolRequireExternRelocation(), llvm::MCContext::FatalError(), llvm::ARM::fixup_arm_adr_pcrel_12, llvm::ARM::fixup_arm_blx, llvm::ARM::fixup_arm_condbl, llvm::ARM::fixup_arm_condbranch, llvm::ARM::fixup_arm_ldst_pcrel_12, llvm::ARM::fixup_arm_movt_hi16, llvm::ARM::fixup_arm_movt_hi16_pcrel, llvm::ARM::fixup_arm_movw_lo16, llvm::ARM::fixup_arm_movw_lo16_pcrel, llvm::ARM::fixup_arm_pcrel_10, llvm::ARM::fixup_arm_thumb_bl, llvm::ARM::fixup_arm_thumb_blx, llvm::ARM::fixup_arm_thumb_br, llvm::ARM::fixup_arm_uncondbl, llvm::ARM::fixup_arm_uncondbranch, llvm::ARM::fixup_t2_movt_hi16, llvm::ARM::fixup_t2_movt_hi16_pcrel, llvm::ARM::fixup_t2_movw_lo16, llvm::ARM::fixup_t2_movw_lo16_pcrel, llvm::ARM::fixup_t2_uncondbranch, llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm::MCValue::getConstant(), llvm::MCAssembler::getContext(), llvm::MCSymbolData::getFlags(), llvm::MCSymbolData::getFragment(), llvm::MCAsmLayout::getFragmentOffset(), llvm::MCSymbolData::getIndex(), llvm::MCFixup::getKind(), llvm::MCFixup::getLoc(), llvm::MCSymbol::getName(), llvm::MCFixup::getOffset(), llvm::MCSectionData::getOrdinal(), llvm::MCFragment::getParent(), llvm::MCSymbol::getSection(), llvm::MachObjectWriter::getSectionAddress(), llvm::MachObjectWriter::getSectionAddressMap(), llvm::MCAssembler::getSectionData(), llvm::MCValue::getSymA(), llvm::MCValue::getSymB(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCSymbolData::getSymbol(), llvm::MachObjectWriter::getSymbolAddress(), llvm::MCAssembler::getSymbolData(), llvm::MCAsmLayout::getSymbolOffset(), llvm::MCSymbol::getVariableValue(), llvm::MCValue::isAbsolute(), llvm::MachObjectWriter::isFixupKindPCRel(), llvm::MCSymbol::isUndefined(), llvm::MCSymbol::isVariable(), llvm::Log2_32(), llvm::MachO::any_relocation_info::r_word0, llvm::MachO::any_relocation_info::r_word1, llvm::report_fatal_error(), llvm::SF_ThumbFunc, and llvm::MCSymbolData::Symbol.