LLVM: ARMSubtarget.cpp File Reference
LLVM API Documentation
ARMSubtarget.cpp File Reference
#include "ARMSubtarget.h"
#include "ARMBaseInstrInfo.h"
#include "ARMBaseRegisterInfo.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetOptions.h"
#include "ARMGenSubtargetInfo.inc"
Macros
#define GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_CTOR
Enumerations
enum AlignMode { DefaultAlign, StrictAlign, NoStrictAlign }
enum ITMode { DefaultIT, RestrictedIT, NoRestrictedIT }
Variables
static cl::opt< bool > ReserveR9 ("arm-reserve-r9", cl::Hidden, cl::desc("Reserve R9, making it unavailable as GPR"))
static cl::opt< bool > ArmUseMOVT ("arm-use-movt", cl::init(true), cl::Hidden)
static cl::opt< bool > UseFusedMulOps ("arm-use-mulops", cl::init(true), cl::Hidden)
static cl::opt< AlignMode > Align (cl::desc("Load/store alignment support"), cl::Hidden, cl::init(DefaultAlign), cl::values(clEnumValN(DefaultAlign,"arm-default-align","Generate unaligned accesses only on hardware/OS ""combinations that are known to support them"), clEnumValN(StrictAlign,"arm-strict-align","Disallow all unaligned memory accesses"), clEnumValN(NoStrictAlign,"arm-no-strict-align","Allow unaligned memory accesses"), clEnumValEnd))
static cl::opt< ITMode > IT (cl::desc("IT block support"), cl::Hidden, cl::init(DefaultIT), cl::ZeroOrMore, cl::values(clEnumValN(DefaultIT,"arm-default-it","Generate IT block based on arch"), clEnumValN(RestrictedIT,"arm-restrict-it","Disallow deprecated IT based on ARMv8"), clEnumValN(NoRestrictedIT,"arm-no-restrict-it","Allow IT blocks based on ARMv7"), clEnumValEnd))
Macro Definition Documentation
#define GET_SUBTARGETINFO_CTOR
Definition at line 25 of file ARMSubtarget.cpp.
#define GET_SUBTARGETINFO_TARGET_DESC
Definition at line 24 of file ARMSubtarget.cpp.
Enumeration Type Documentation
enum AlignMode
Enumerator
DefaultAlign
StrictAlign
NoStrictAlign
Definition at line 41 of file ARMSubtarget.cpp.
enum ITMode
Enumerator
DefaultIT
RestrictedIT
NoRestrictedIT
Definition at line 60 of file ARMSubtarget.cpp.
Variable Documentation
cl::opt<AlignMode> Align(cl::desc("Load/store alignment support"), cl::Hidden, cl::init(DefaultAlign), cl::values(clEnumValN(DefaultAlign,"arm-default-align","Generate unaligned accesses only on hardware/OS ""combinations that are known to support them"),clEnumValN(StrictAlign,"arm-strict-align","Disallow all unaligned memory accesses"),clEnumValN(NoStrictAlign,"arm-no-strict-align","Allow unaligned memory accesses"),clEnumValEnd)) static
Referenced by llvm::AttrBuilder::addAlignmentAttr(), llvm::AttrBuilder::addStackAlignmentAttr(), AdjustStackOffset(), llvm::Recycler< llvm::MachineInstr >::Allocate(), llvm::ArrayRecycler< llvm::MachineOperand >::allocate(), llvm::MCContext::Allocate(), llvm::MipsTargetLowering::MipsCC::analyzeReturn(), llvm::Attribute::Attribute(), BBHasFallthrough(), BuildVectorFromScalar(), llvm::MipsTargetLowering::MipsCC::byval_end(), canFoldInAddressingMode(), clampStackAlignment(), computeBytesPoppedByCallee(), llvm::ComputeMaskedBits(), llvm::SelectionDAG::ComputeMaskedBits(), concatenateMemOperands(), countOperands(), llvm::createARMConstantIslandPass(), llvm::MachineFrameInfo::CreateFixedObject(), llvm::IRBuilderBase::CreateMemSet(), llvm::createMipsConstantIslandPass(), llvm::SelectionDAG::CreateStackTemporary(), llvm::DataLayout::DataLayout(), llvm::XCoreFrameLowering::eliminateCallFramePseudoInstr(), llvm::Thumb1FrameLowering::eliminateCallFramePseudoInstr(), llvm::AArch64FrameLowering::eliminateCallFramePseudoInstr(), llvm::AsmPrinter::EmitBasicBlockStart(), llvm::RuntimeDyldImpl::emitCommonSymbols(), llvm::AsmPrinter::EmitConstantPool(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::AsmPrinter::EmitGlobalVariable(), EmitMonitor(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), enforceKnownAlignment(), llvm::MachineFrameInfo::ensureMaxAlignment(), llvm::MachineFrameInfo::estimateStackSize(), EvaluateAsPCRel(), ExpandUnalignedLoad(), FindMemType(), fixupFuncForFI(), FPCCToARMCC(), getAL(), llvm::GlobalValue::getAlignment(), llvm::AlignAttributeImpl::getAlignment(), llvm::ARMFunctionInfo::getArgRegsSaveSize(), getBlockNum(), getBuildPairElt(), llvm::PPCTargetLowering::getByValTypeAlignment(), llvm::X86TargetLowering::getByValTypeAlignment(), getComparePred(), GetConstantPoolSizeInBytes(), getDRegFromQReg(), llvm::SelectionDAG::getGLOBAL_OFFSET_TABLE(), llvm::MachineFrameInfo::getMaxAlignment(), llvm::SelectionDAG::getMemcpy(), getMemcpyLoadsAndStores(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SelectionDAG::getMemmove(), getMemmoveLoadsAndStores(), llvm::MipsInstrInfo::GetMemOperand(), llvm::SelectionDAG::getMemset(), getMemsetStores(), llvm::getObjectSize(), llvm::getOrEnforceKnownAlignment(), llvm::DataLayout::getPointerTypeSizeInBits(), llvm::DataLayout::getPreferredTypeAlignmentShift(), llvm::NVPTXTargetLowering::getPrototype(), GetRegistersForValue(), llvm::object::MachOObjectFile::getSectionAlignment(), llvm::AttrBuilder::getStackAlignment(), llvm::SelectionDAG::getTargetConstantPool(), llvm::SelectionDAG::getTargetJumpTable(), getTruncatedArgReg(), llvm::ARMInstrInfo::getUnindexedOpcode(), getVLDSTRegisterUpdateOpcode(), llvm::Attribute::getWithAlignment(), llvm::Attribute::getWithStackAlignment(), llvm::Hexagon_CCState::HandleByVal(), llvm::CCState::HandleByVal(), HandleByValArgument(), llvm::SelectionDAG::InferPtrAlignment(), INITIALIZE_PASS(), insertVector(), llvm::MipsTargetLowering::MipsCC::intArgRegs(), isADDADDMUL(), IsBetterCannonical(), llvm::isSafeToLoadUnconditionally(), isScaledConstantInRange(), isSequentialInRange(), isXor1OfSetCC(), llvm::RuntimeDyldImpl::loadObject(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SelectionDAGBuilder::LowerCallTo(), MarkBlocksLiveIn(), memsetStore(), llvm::StoreInst::operator new(), false::IntervalSorter::operator()(), ConsecutiveMemoryChainSorter::operator()(), llvm::BitcodeReader::ParseTriple(), llvm::Recycler< llvm::MachineInstr >::PrintStats(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::ARMSubtarget::resetSubtargetFeatures(), llvm::RoundUpToAlignment(), llvm::PEI::runOnMachineFunction(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), llvm::FunctionLoweringInfo::set(), llvm::MachineBasicBlock::setAlignment(), llvm::MCSymbolData::setCommon(), llvm::TargetLoweringBase::setJumpBufAlignment(), llvm::MachineFrameInfo::setLocalFrameMaxAlign(), llvm::TargetLoweringBase::setMinFunctionAlignment(), llvm::TargetLoweringBase::setMinStackArgumentAlignment(), llvm::MachineFrameInfo::setObjectAlignment(), llvm::TargetLoweringBase::setPrefFunctionAlignment(), llvm::TargetLoweringBase::setPrefLoopAlignment(), speculatePHINodeLoads(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), tryToMakeAllocaBePromotable(), useSinCos(), llvm::InstCombiner::visitLoadInst(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), llvm::MachObjectWriter::WriteNlist(), and XFormVExtractWithShuffleIntoLoad().
cl::opt<bool> ArmUseMOVT("arm-use-movt", cl::init(true), cl::Hidden) static
Referenced by llvm::ARMSubtarget::resetSubtargetFeatures().
cl::opt<ITMode> IT(cl::desc("IT block support"), cl::Hidden, cl::init(DefaultIT), cl::ZeroOrMore, cl::values(clEnumValN(DefaultIT,"arm-default-it","Generate IT block based on arch"),clEnumValN(RestrictedIT,"arm-restrict-it","Disallow deprecated IT based on ARMv8"),clEnumValN(NoRestrictedIT,"arm-no-restrict-it","Allow IT blocks based on ARMv7"),clEnumValEnd)) static
Referenced by createPrivateNonConstGlobalForString(), FindInitTrampoline(), FoldBitCast(), GetCaseResults(), getComparePred(), llvm::ConstantDataSequential::isElementTypeCompatible(), LLVMGetTargetFromName(), llvm::iplist< Argument >::remove(), llvm::ARMSubtarget::resetSubtargetFeatures(), llvm::InstCombiner::visitAdd(), and llvm::InstCombiner::visitCallInst().
cl::opt<bool> ReserveR9("arm-reserve-r9", cl::Hidden, cl::desc("Reserve R9, making it unavailable as GPR")) static
Referenced by llvm::ARMSubtarget::ARMSubtarget(), and llvm::ARMSubtarget::resetSubtargetFeatures().
cl::opt<bool> UseFusedMulOps("arm-use-mulops", cl::init(true), cl::Hidden) static
Referenced by llvm::ARMSubtarget::ARMSubtarget().