LLVM: AsmLexer.cpp File Reference
LLVM API Documentation
AsmLexer.cpp File Reference
#include "llvm/MC/MCParser/AsmLexer.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/SMLoc.h"
#include <cctype>
#include <cerrno>
#include <cstdio>
#include <cstdlib>
Functions
static bool IsIdentifierChar (char c)
LexIdentifier: [a-zA-Z_.][a-zA-Z0-9_$.@?]*.
static void SkipIgnoredIntegerSuffix (const char *&CurPtr)
static unsigned doLookAhead (const char *&CurPtr, unsigned DefaultRadix)
Function Documentation
static unsigned doLookAhead (const char *& CurPtr, unsigned DefaultRadix) static
Definition at line 217 of file AsmLexer.cpp.
References llvm::StringRef::getAsInteger(), llvm::AsmToken::Integer, llvm::LibFunc::isdigit, SkipIgnoredIntegerSuffix(), llvm::StringRef::startswith(), llvm::AsmToken::String, llvm::StringRef::substr(), and llvm::MCAsmLexer::TokStart.
static bool IsIdentifierChar (char c) static
LexIdentifier: [a-zA-Z_.][a-zA-Z0-9_$.@?]*.
Definition at line 142 of file AsmLexer.cpp.
References llvm::AsmToken::Dot, llvm::AsmToken::EndOfStatement, llvm::AsmToken::Eof, llvm::AsmToken::Identifier, llvm::LibFunc::isdigit, llvm::AsmLexer::LexToken(), llvm::AsmToken::Slash, and llvm::MCAsmLexer::TokStart.
static void SkipIgnoredIntegerSuffix (const char *& CurPtr) static
Definition at line 205 of file AsmLexer.cpp.
Referenced by doLookAhead().