LLVM: AsmPrinterInlineAsm.cpp File Reference
LLVM API Documentation
AsmPrinterInlineAsm.cpp File Reference
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/ADT/OwningPtr.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/Twine.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCTargetAsmParser.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
Macros
#define DEBUG_TYPE "asm-printer"
Functions
static void srcMgrDiagHandler (const SMDiagnostic &Diag, void *diagInfo)
static void EmitMSInlineAsmStr (const char *AsmStr, const MachineInstr *MI, MachineModuleInfo *MMI, int InlineAsmVariant, AsmPrinter *AP, unsigned LocCookie, raw_ostream &OS)
static void EmitGCCInlineAsmStr (const char *AsmStr, const MachineInstr *MI, MachineModuleInfo *MMI, int InlineAsmVariant, int AsmPrinterVariant, AsmPrinter *AP, unsigned LocCookie, raw_ostream &OS)
Macro Definition Documentation
#define DEBUG_TYPE "asm-printer"
Definition at line 14 of file AsmPrinterInlineAsm.cpp.
Function Documentation
static void EmitGCCInlineAsmStr (const char * AsmStr, const MachineInstr * MI, MachineModuleInfo * MMI, int InlineAsmVariant, int AsmPrinterVariant, AsmPrinter * AP, unsigned LocCookie, raw_ostream & OS) static
Definition at line 238 of file AsmPrinterInlineAsm.cpp.
References llvm::InlineAsm::AD_ATT, llvm::LLVMContext::emitError(), EmitMSInlineAsmStr(), llvm::lltok::Error, llvm::StringRef::getAsInteger(), llvm::Module::getContext(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getInlineAsmDialect(), llvm::MachineOperand::getMBB(), llvm::MachineOperand::getMetadata(), llvm::MachineModuleInfo::getModule(), llvm::InlineAsm::getNumOperandRegisters(), llvm::MDNode::getNumOperands(), llvm::MachineInstr::getNumOperands(), llvm::MDNode::getOperand(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getSymbolName(), i, llvm::MachineOperand::isDef(), llvm::MachineInstr::isInlineAsm(), llvm::InlineAsm::isMemKind(), llvm::MachineOperand::isMetadata(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isSymbol(), llvm::A64CC::MI, llvm::AsmPrinter::PrintAsmMemoryOperand(), llvm::AsmPrinter::PrintAsmOperand(), llvm::AsmPrinter::PrintSpecial(), llvm::report_fatal_error(), llvm::raw_string_ostream::str(), llvm::raw_svector_ostream::str(), llvm::LibFunc::strchr, and llvm::raw_ostream::write().
static void EmitMSInlineAsmStr (const char * AsmStr, const MachineInstr * MI, MachineModuleInfo * MMI, int InlineAsmVariant, AsmPrinter * AP, unsigned LocCookie, raw_ostream & OS) static
Definition at line 140 of file AsmPrinterInlineAsm.cpp.
References llvm::LLVMContext::emitError(), llvm::lltok::Error, llvm::Module::getContext(), llvm::MachineOperand::getImm(), llvm::MachineModuleInfo::getModule(), llvm::InlineAsm::getNumOperandRegisters(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::InlineAsm::isMemKind(), llvm::MachineOperand::isMetadata(), llvm::AsmPrinter::PrintAsmMemoryOperand(), llvm::AsmPrinter::PrintAsmOperand(), llvm::report_fatal_error(), llvm::raw_string_ostream::str(), and llvm::raw_ostream::write().
Referenced by EmitGCCInlineAsmStr().
static void srcMgrDiagHandler (const SMDiagnostic & Diag, void * diagInfo) static
srcMgrDiagHandler - This callback is invoked when the SourceMgr for an inline asm has an error in it. diagInfo is a pointer to the SrcMgrDiagInfo struct above.
Definition at line 49 of file AsmPrinterInlineAsm.cpp.
References llvm::SourceMgr::AddNewSourceBuffer(), llvm::StringRef::back(), llvm::createMCAsmParser(), llvm::StringRef::empty(), llvm::LLVMContext::getInlineAsmDiagnosticContext(), llvm::LLVMContext::getInlineAsmDiagnosticHandler(), llvm::SMDiagnostic::getLineNo(), llvm::MemoryBuffer::getMemBuffer(), llvm::MemoryBuffer::getMemBufferCopy(), MII, llvm::report_fatal_error(), llvm::MCAsmParser::Run(), llvm::MCAsmParser::setAssemblerDialect(), llvm::SourceMgr::setDiagHandler(), llvm::MCAsmParser::setTargetParser(), llvm::StringRef::size(), llvm::SrcMgr, llvm::StringRef::substr(), and llvm::SystemZISD::TM.