LLVM: AsmParser.cpp File Reference
LLVM API Documentation
AsmParser.cpp File Reference
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/Twine.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCDwarf.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInstPrinter.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCParser/AsmCond.h"
#include "llvm/MC/MCParser/AsmLexer.h"
#include "llvm/MC/MCParser/MCAsmParser.h"
#include "llvm/MC/MCParser/MCParsedAsmOperand.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCTargetAsmParser.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/raw_ostream.h"
#include <cctype>
#include <set>
#include <string>
#include <vector>
Namespaces
llvm
List of target independent CodeGen pass IDs.
Enumerations
enum { DEFAULT_ADDRSPACE = 0 }
Functions
MCAsmParserExtension * llvm::createDarwinAsmParser ()
MCAsmParserExtension * llvm::createELFAsmParser ()
MCAsmParserExtension * llvm::createCOFFAsmParser ()
static unsigned getBinOpPrecedence (AsmToken::TokenKind K, MCBinaryExpr::Opcode &Kind)
static bool isIdentifierChar (char c)
static bool isOperator (AsmToken::TokenKind kind)
static bool isUsedIn (const MCSymbol *Sym, const MCExpr *Value)
static bool isValidEncoding (int64_t Encoding)
static int rewritesSort (const AsmRewrite *AsmRewriteA, const AsmRewrite *AsmRewriteB)
Variables
static cl::opt< bool > FatalAssemblerWarnings ("fatal-assembler-warnings", cl::desc("Consider warnings as error"))
Enumeration Type Documentation
anonymous enum
Enumerator
DEFAULT_ADDRSPACE
Definition at line 478 of file AsmParser.cpp.
Function Documentation
static unsigned getBinOpPrecedence (AsmToken::TokenKind K, MCBinaryExpr::Opcode & Kind) static
Definition at line 1033 of file AsmParser.cpp.
References llvm::MCBinaryExpr::Add, llvm::AsmToken::Amp, llvm::AsmToken::AmpAmp, llvm::MCBinaryExpr::And, llvm::AsmToken::Caret, llvm::AsmToken::Colon, llvm::MCBinaryExpr::Create(), llvm::MCBinaryExpr::Div, llvm::SourceMgr::DK_Note, llvm::AsmToken::Dot, llvm::NVPTXISD::Dummy, DWARF2_FLAG_IS_STMT, DWARF2_LINE_DEFAULT_IS_STMT, llvm::AsmToken::EndOfStatement, llvm::AsmToken::Eof, llvm::MCBinaryExpr::EQ, llvm::AsmToken::Equal, llvm::AsmToken::EqualEqual, llvm::lltok::Error, llvm::errs(), llvm::AsmToken::ExclaimEqual, llvm::SourceMgr::FindBufferContainingLoc(), llvm::SourceMgr::FindLineNumber(), llvm::SMDiagnostic::getColumnNo(), llvm::SMDiagnostic::getKind(), llvm::SMDiagnostic::getLineContents(), llvm::AsmToken::getLoc(), llvm::SMDiagnostic::getLoc(), llvm::SMDiagnostic::getMessage(), llvm::SourceMgr::getParentIncludeLoc(), llvm::SMDiagnostic::getRanges(), llvm::SMDiagnostic::getSourceMgr(), llvm::StringMapEntry< ValueTy >::getValue(), llvm::AsmToken::Greater, llvm::AsmToken::GreaterEqual, llvm::AsmToken::GreaterGreater, llvm::MCBinaryExpr::GT, llvm::MCBinaryExpr::GTE, llvm::AsmToken::Hash, i, llvm::APFloat::IEEEdouble, llvm::APFloat::IEEEsingle, llvm::AsmToken::Integer, llvm::MCSymbol::isUndefined(), llvm::MCSymbol::isVariable(), llvm::MCBinaryExpr::LAnd, llvm::AsmToken::Less, llvm::AsmToken::LessEqual, llvm::AsmToken::LessGreater, llvm::AsmToken::LessLess, llvm::MCBinaryExpr::LOr, llvm::StringRef::lower(), llvm::MCBinaryExpr::LT, llvm::MCBinaryExpr::LTE, M, llvm::MCGenDwarfLabelEntry::Make(), llvm::MCSA_Global, llvm::MCSA_LazyReference, llvm::MCSA_NoDeadStrip, llvm::MCSA_PrivateExtern, llvm::MCSA_Reference, llvm::MCSA_SymbolResolver, llvm::MCSA_WeakDefAutoPrivate, llvm::MCSA_WeakDefinition, llvm::MCSA_WeakReference, llvm::AsmToken::Minus, llvm::MCBinaryExpr::Mod, llvm::MCBinaryExpr::Mul, llvm::MCBinaryExpr::NE, llvm::MCBinaryExpr::Or, llvm::AsmToken::Percent, llvm::AsmToken::Pipe, llvm::AsmToken::PipePipe, llvm::AsmToken::Plus, llvm::SMDiagnostic::print(), llvm::SourceMgr::PrintIncludeStack(), llvm::MCBinaryExpr::Shl, llvm::MCBinaryExpr::Shr, llvm::StringRef::size(), llvm::AsmToken::Slash, llvm::SrcMgr, llvm::AsmToken::Star, llvm::raw_svector_ostream::str(), llvm::AsmToken::String, llvm::MCBinaryExpr::Sub, llvm::StringRef::substr(), and llvm::MCBinaryExpr::Xor.
static bool isIdentifierChar (char c) static
Definition at line 1689 of file AsmParser.cpp.
References llvm::ARM_PROC::A, llvm::sys::path::begin(), llvm::StringRef::data(), llvm::StringRef::empty(), llvm::sys::path::const_iterator::end, llvm::sys::path::end(), llvm::lltok::Error, I, llvm::LibFunc::isdigit, it, M, llvm::StringRef::size(), llvm::StringRef::slice(), llvm::AsmToken::String, and llvm::StringRef::substr().
Referenced by isValidEncoding().
static bool isOperator (AsmToken::TokenKind kind) static
Definition at line 1802 of file AsmParser.cpp.
References llvm::ARM_PROC::A, llvm::SourceMgr::AddNewSourceBuffer(), llvm::AsmToken::Amp, llvm::AsmToken::AmpAmp, llvm::AsmToken::Caret, llvm::AsmToken::Comma, llvm::AsmToken::Dot, llvm::AsmToken::EndOfStatement, llvm::AsmToken::Eof, llvm::AsmToken::Equal, llvm::AsmToken::EqualEqual, llvm::AsmToken::Exclaim, llvm::AsmToken::ExclaimEqual, llvm::MemoryBuffer::getMemBufferCopy(), llvm::SourceMgr::getMemoryBuffer(), llvm::AsmToken::Greater, llvm::AsmToken::GreaterEqual, llvm::AsmToken::GreaterGreater, llvm::AsmToken::Less, llvm::AsmToken::LessEqual, llvm::AsmToken::LessGreater, llvm::AsmToken::LessLess, llvm::AsmToken::LParen, llvm::A64CC::MI, llvm::AsmToken::Minus, llvm::AsmToken::Percent, llvm::AsmToken::Pipe, llvm::AsmToken::PipePipe, llvm::AsmToken::Plus, llvm::AsmToken::RParen, llvm::AsmToken::Slash, llvm::AsmToken::Space, llvm::SrcMgr, llvm::AsmToken::Star, llvm::raw_svector_ostream::str(), and llvm::AsmToken::Tilde.
static bool isUsedIn (const MCSymbol * Sym, const MCExpr * Value) static
Definition at line 2027 of file AsmParser.cpp.
References llvm::AsmToken::At, llvm::MCExpr::Binary, llvm::APFloat::bitcastToAPInt(), llvm::APFloat::changeSign(), llvm::AsmToken::Comma, llvm::StringRef::compare_lower(), llvm::MCExpr::Constant, llvm::APFloat::convertFromString(), Debug, llvm::AsmToken::Dollar, DWARF2_FLAG_BASIC_BLOCK, DWARF2_FLAG_EPILOGUE_BEGIN, DWARF2_FLAG_IS_STMT, DWARF2_FLAG_PROLOGUE_END, DWARF2_LINE_DEFAULT_IS_STMT, llvm::AsmToken::EndOfStatement, llvm::lltok::Error, llvm::APInt::getBitWidth(), llvm::APFloat::getInf(), llvm::MCExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::APInt::getLimitedValue(), llvm::APFloat::getNaN(), llvm::SMLoc::getPointer(), llvm::MCBinaryExpr::getRHS(), llvm::MCSymbol::getVariableValue(), i, llvm::AsmToken::Identifier, llvm::AsmToken::Integer, is, llvm::isIntN(), llvm::isPowerOf2_64(), llvm::isUIntN(), llvm::MCSymbol::isUndefined(), llvm::MCSymbol::isUsed(), llvm::SMLoc::isValid(), llvm::MCSymbol::isVariable(), llvm_unreachable, llvm::MCSA_NoDeadStrip, llvm::AsmToken::Minus, llvm::APFloat::opInvalidOp, llvm::AsmToken::Plus, llvm::AsmToken::Real, Register, llvm::APFloat::rmNearestTiesToEven, S, llvm::MCSymbol::setUsed(), llvm::StringRef::size(), llvm::AsmToken::String, llvm::MCExpr::SymbolRef, llvm::MCExpr::Target, and llvm::MCExpr::Unary.
static bool isValidEncoding (int64_t Encoding) static
Definition at line 2912 of file AsmParser.cpp.
References llvm::ARM_PROC::A, llvm::SourceMgr::AddNewSourceBuffer(), llvm::AOK_Align, llvm::AOK_Emit, llvm::LCOMM::ByteAlignment, llvm::AsmToken::Comma, llvm::StringRef::data(), llvm::dwarf::DW_EH_PE_absptr, llvm::dwarf::DW_EH_PE_omit, llvm::dwarf::DW_EH_PE_pcrel, llvm::dwarf::DW_EH_PE_sdata2, llvm::dwarf::DW_EH_PE_sdata4, llvm::dwarf::DW_EH_PE_sdata8, llvm::dwarf::DW_EH_PE_signed, llvm::dwarf::DW_EH_PE_udata2, llvm::dwarf::DW_EH_PE_udata4, llvm::dwarf::DW_EH_PE_udata8, llvm::dyn_cast(), llvm::AsmCond::ElseCond, llvm::AsmCond::ElseIfCond, llvm::StringRef::empty(), llvm::AsmToken::EndOfStatement, llvm::AsmToken::Eof, llvm::AsmToken::Equal, llvm::lltok::Error, llvm::StringRef::front(), llvm::AsmToken::getIdentifier(), llvm::AsmToken::getLoc(), llvm::MemoryBuffer::getMemBufferCopy(), llvm::SourceMgr::getMemoryBuffer(), llvm::SMLoc::getPointer(), llvm::MCConstantExpr::getValue(), i, I, llvm::AsmToken::Identifier, llvm::AsmCond::IfCond, is, llvm::LibFunc::isdigit, isIdentifierChar(), llvm::isIntN(), llvm::isPowerOf2_64(), llvm::MCSymbol::isTemporary(), llvm::isUIntN(), llvm::MCSymbol::isUndefined(), llvm::Log2_64(), llvm::A64CC::MI, llvm::LCOMM::NoAlignment, llvm::AsmCond::NoCond, llvm::NVPTX::PTXLdStInstCode::Signed, llvm::StringRef::size(), llvm::StringRef::slice(), llvm::SrcMgr, llvm::raw_svector_ostream::str(), llvm::AsmToken::String, and llvm::StringRef::substr().
static int rewritesSort (const AsmRewrite * AsmRewriteA, const AsmRewrite * AsmRewriteB) static
Definition at line 4098 of file AsmParser.cpp.
References llvm::AOK_Align, llvm::AOK_Delete, llvm::AOK_DotOperator, llvm::AOK_Emit, llvm::AOK_Imm, llvm::AOK_ImmPrefix, llvm::AOK_Input, llvm::AOK_Output, llvm::AOK_SizeDirective, llvm::AOK_Skip, llvm::array_pod_sort(), llvm::AsmRewritePrecedence, llvm::SmallVectorImpl< T >::assign(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::StringRef::data(), llvm::StringRef::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::AsmToken::Eof, llvm::SmallVectorImpl< T >::erase(), llvm::MCInstrInfo::get(), llvm::MemoryBuffer::getBufferEnd(), llvm::MemoryBuffer::getBufferStart(), llvm::MCParsedAsmOperand::getConstraint(), llvm::SMLoc::getFromPointer(), llvm::MCParsedAsmOperand::getMCOperandNum(), llvm::SourceMgr::getMemoryBuffer(), llvm::MCInstrDesc::getNumDefs(), llvm::MCParsedAsmOperand::getOpDecl(), llvm::SMLoc::getPointer(), llvm::MCParsedAsmOperand::getReg(), llvm::MCParsedAsmOperand::getSymName(), i, I, llvm::MCParsedAsmOperand::isImm(), llvm::MCParsedAsmOperand::isReg(), j(), llvm::AsmRewrite::Kind, llvm_unreachable, llvm::AsmRewrite::Loc, llvm::MCInstrDesc::mayStore(), MII, llvm::MCParsedAsmOperand::needAddressOf(), llvm::MCInstPrinter::printRegName(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorImpl< T >::resize(), llvm::StringRef::size(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::SrcMgr, llvm::StringRef::str(), and llvm::raw_string_ostream::str().
Variable Documentation
cl::opt<bool> FatalAssemblerWarnings("fatal-assembler-warnings", cl::desc("Consider warnings as error")) static