LLVM: AutoUpgrade.cpp File Reference
LLVM API Documentation
AutoUpgrade.cpp File Reference
#include "llvm/AutoUpgrade.h"
#include "llvm/DebugInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/CFG.h"
#include "llvm/Support/CallSite.h"
#include "llvm/Support/ErrorHandling.h"
#include <cstring>
Functions
static bool UpgradeSSE41Function (Function *F, Intrinsic::ID IID, Function *&NewFn)
static bool UpgradeIntrinsicFunction1 (Function *F, Function *&NewFn)
Function Documentation
static bool UpgradeIntrinsicFunction1 (Function * F, Function *& NewFn) static
Definition at line 45 of file AutoUpgrade.cpp.
References llvm::Function::arg_begin(), llvm::Function::arg_size(), llvm::Function::Create(), llvm::Intrinsic::ctlz, llvm::Intrinsic::ctpop, llvm::Intrinsic::cttz, F(), llvm::FunctionType::get(), llvm::Function::getContext(), llvm::Intrinsic::getDeclaration(), llvm::Type::getInt1Ty(), llvm::GlobalValue::getLinkage(), llvm::Intrinsic::getName(), llvm::Value::getName(), llvm::GlobalValue::getParent(), llvm::Function::getReturnType(), llvm::Intrinsic::objectsize, llvm::Value::setName(), llvm::StringRef::size(), llvm::StringRef::startswith(), llvm::StringRef::substr(), UpgradeSSE41Function(), llvm::Intrinsic::x86_sse41_ptestc, llvm::Intrinsic::x86_sse41_ptestnzc, llvm::Intrinsic::x86_sse41_ptestz, llvm::Intrinsic::x86_xop_vfrcz_sd, and llvm::Intrinsic::x86_xop_vfrcz_ss.
Referenced by llvm::UpgradeIntrinsicFunction().
static bool UpgradeSSE41Function (Function * F, Intrinsic::ID IID, Function *& NewFn) static
Definition at line 31 of file AutoUpgrade.cpp.
References llvm::VectorType::get(), llvm::Function::getContext(), llvm::Intrinsic::getDeclaration(), llvm::Type::getFloatTy(), llvm::Function::getFunctionType(), llvm::Value::getName(), llvm::FunctionType::getParamType(), llvm::GlobalValue::getParent(), and llvm::Value::setName().
Referenced by UpgradeIntrinsicFunction1().