LLVM: BitcodeReader.cpp File Reference
LLVM API Documentation
BitcodeReader.cpp File Reference
#include "llvm/Bitcode/ReaderWriter.h"
#include "BitcodeReader.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/AutoUpgrade.h"
#include "llvm/Bitcode/LLVMBitCodes.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/OperandTraits.h"
#include "llvm/IR/Operator.h"
#include "llvm/Support/DataStream.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/raw_ostream.h"
Classes
struct llvm::OperandTraits< ConstantPlaceHolder >
Namespaces
llvm
List of target independent CodeGen pass IDs.
Enumerations
enum { SWITCH_INST_MAGIC = 0x4B5 }
Functions
template<typename StrTy >
static bool ConvertToString (ArrayRef< uint64_t > Record, unsigned Idx, StrTy &Result)
static GlobalValue::LinkageTypes GetDecodedLinkage (unsigned Val)
static GlobalValue::VisibilityTypes GetDecodedVisibility (unsigned Val)
static GlobalVariable::ThreadLocalMode GetDecodedThreadLocalMode (unsigned Val)
static int GetDecodedCastOpcode (unsigned Val)
static int GetDecodedBinaryOpcode (unsigned Val, Type *Ty)
static AtomicRMWInst::BinOp GetDecodedRMWOperation (unsigned Val)
static AtomicOrdering GetDecodedOrdering (unsigned Val)
static SynchronizationScope GetDecodedSynchScope (unsigned Val)
static void decodeLLVMAttributesForBitcode (AttrBuilder &B, uint64_t EncodedAttrs)
This fills an AttrBuilder object with the LLVM attributes that have been decoded from the given integer. This function must stay in sync with 'encodeLLVMAttributesForBitcode'.
static Attribute::AttrKind GetAttrFromCode (uint64_t Code)
static APInt ReadWideAPInt (ArrayRef< uint64_t > Vals, unsigned TypeBits)
Enumeration Type Documentation
anonymous enum
Enumerator
SWITCH_INST_MAGIC
Definition at line 30 of file BitcodeReader.cpp.
Function Documentation
template<typename StrTy > static bool ConvertToString (ArrayRef< uint64_t > Record, unsigned Idx, StrTy & Result) static
ConvertToString - Convert a string from a record into an std::string, return true on failure.
Definition at line 65 of file BitcodeReader.cpp.
References i, and llvm::ArrayRef< T >::size().
Referenced by GetAttrFromCode(), llvm::BitcodeReader::ParseBitcodeInto(), and ReadWideAPInt().
static void decodeLLVMAttributesForBitcode (AttrBuilder & B, uint64_t EncodedAttrs) static
This fills an AttrBuilder object with the LLVM attributes that have been decoded from the given integer. This function must stay in sync with 'encodeLLVMAttributesForBitcode'.
Definition at line 438 of file BitcodeReader.cpp.
References llvm::AttrBuilder::addAlignmentAttr(), llvm::AttrBuilder::addRawValue(), B, llvm::SmallVectorImpl< T >::clear(), llvm::BitstreamEntry::EndBlock, llvm::BitstreamEntry::Error, llvm::BitcodeReader::Error(), i, llvm::BitstreamEntry::ID, llvm::BitcodeReader::InvalidMultipleBlocks, llvm::BitcodeReader::InvalidRecord, llvm::isPowerOf2_32(), llvm::BitstreamEntry::Kind, llvm::BitcodeReader::MalformedBlock, llvm::bitc::PARAMATTR_BLOCK_ID, llvm::bitc::PARAMATTR_CODE_ENTRY, llvm::bitc::PARAMATTR_CODE_ENTRY_OLD, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::BitstreamEntry::Record, llvm::SmallVectorTemplateCommon< T >::size(), llvm::BitstreamEntry::SubBlock, and llvm::error_code::success().
static Attribute::AttrKind GetAttrFromCode (uint64_t Code) static
Definition at line 513 of file BitcodeReader.cpp.
References llvm::AttrBuilder::addAlignmentAttr(), llvm::AttrBuilder::addAttribute(), llvm::NamedMDNode::addOperand(), llvm::AttrBuilder::addStackAlignmentAttr(), llvm::Attribute::Alignment, llvm::Attribute::AlwaysInline, llvm::bitc::ATTR_KIND_ALIGNMENT, llvm::bitc::ATTR_KIND_ALWAYS_INLINE, llvm::bitc::ATTR_KIND_BUILTIN, llvm::bitc::ATTR_KIND_BY_VAL, llvm::bitc::ATTR_KIND_COLD, llvm::bitc::ATTR_KIND_IN_REG, llvm::bitc::ATTR_KIND_INLINE_HINT, llvm::bitc::ATTR_KIND_MIN_SIZE, llvm::bitc::ATTR_KIND_NAKED, llvm::bitc::ATTR_KIND_NEST, llvm::bitc::ATTR_KIND_NO_ALIAS, llvm::bitc::ATTR_KIND_NO_BUILTIN, llvm::bitc::ATTR_KIND_NO_CAPTURE, llvm::bitc::ATTR_KIND_NO_DUPLICATE, llvm::bitc::ATTR_KIND_NO_IMPLICIT_FLOAT, llvm::bitc::ATTR_KIND_NO_INLINE, llvm::bitc::ATTR_KIND_NO_RED_ZONE, llvm::bitc::ATTR_KIND_NO_RETURN, llvm::bitc::ATTR_KIND_NO_UNWIND, llvm::bitc::ATTR_KIND_NON_LAZY_BIND, llvm::bitc::ATTR_KIND_OPTIMIZE_FOR_SIZE, llvm::bitc::ATTR_KIND_OPTIMIZE_NONE, llvm::bitc::ATTR_KIND_READ_NONE, llvm::bitc::ATTR_KIND_READ_ONLY, llvm::bitc::ATTR_KIND_RETURNED, llvm::bitc::ATTR_KIND_RETURNS_TWICE, llvm::bitc::ATTR_KIND_S_EXT, llvm::bitc::ATTR_KIND_SANITIZE_ADDRESS, llvm::bitc::ATTR_KIND_SANITIZE_MEMORY, llvm::bitc::ATTR_KIND_SANITIZE_THREAD, llvm::bitc::ATTR_KIND_STACK_ALIGNMENT, llvm::bitc::ATTR_KIND_STACK_PROTECT, llvm::bitc::ATTR_KIND_STACK_PROTECT_REQ, llvm::bitc::ATTR_KIND_STACK_PROTECT_STRONG, llvm::bitc::ATTR_KIND_STRUCT_RET, llvm::bitc::ATTR_KIND_UW_TABLE, llvm::bitc::ATTR_KIND_Z_EXT, B, BB, llvm::SmallVectorTemplateCommon< T >::begin(), llvm::Attribute::Builtin, llvm::Attribute::ByVal, llvm::SmallVectorImpl< char >::clear(), llvm::SmallVectorImpl< T >::clear(), llvm::tgtok::Code, llvm::Attribute::Cold, llvm::BitcodeReader::ConflictingMETADATA_KINDRecords, ConvertToString(), llvm::StructType::create(), llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::dyn_cast(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::BitstreamEntry::EndBlock, llvm::BitstreamEntry::Error, llvm::BitcodeReader::Error(), llvm::MDString::get(), llvm::IntegerType::get(), llvm::FunctionType::get(), llvm::StructType::get(), llvm::ArrayType::get(), llvm::VectorType::get(), llvm::PointerType::get(), llvm::Type::getDoubleTy(), llvm::Type::getFloatTy(), llvm::Type::getFP128Ty(), llvm::Type::getHalfTy(), llvm::Type::getLabelTy(), llvm::Type::getMetadataTy(), llvm::Type::getPPC_FP128Ty(), llvm::Type::getVoidTy(), llvm::MDNode::getWhenValsUnresolved(), llvm::Type::getX86_FP80Ty(), llvm::Type::getX86_MMXTy(), i, llvm::BitstreamEntry::ID, llvm::Attribute::InlineHint, llvm::Attribute::InReg, llvm::BitcodeReader::InvalidMultipleBlocks, llvm::BitcodeReader::InvalidRecord, llvm::BitcodeReader::InvalidType, llvm::BitcodeReader::InvalidTYPETable, llvm::BitcodeReader::InvalidValue, llvm::Type::isMetadataTy(), llvm::Type::isVoidTy(), llvm::BitstreamEntry::Kind, llvm::BitcodeReader::MalformedBlock, llvm::bitc::METADATA_BLOCK_ID, llvm::bitc::METADATA_FN_NODE, llvm::bitc::METADATA_KIND, llvm::bitc::METADATA_NAME, llvm::bitc::METADATA_NAMED_NODE, llvm::bitc::METADATA_NODE, llvm::bitc::METADATA_STRING, llvm::Attribute::MinSize, llvm::Attribute::Naked, llvm::Attribute::Nest, llvm::Attribute::NoAlias, llvm::Attribute::NoBuiltin, llvm::Attribute::NoCapture, llvm::Attribute::NoDuplicate, llvm::Attribute::NoImplicitFloat, llvm::Attribute::NoInline, llvm::Attribute::None, llvm::Attribute::NonLazyBind, llvm::Attribute::NoRedZone, llvm::Attribute::NoReturn, llvm::Attribute::NoUnwind, llvm::Attribute::OptimizeForSize, llvm::Attribute::OptimizeNone, llvm::bitc::PARAMATTR_GROUP_BLOCK_ID, llvm::bitc::PARAMATTR_GRP_CODE_ENTRY, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::Attribute::ReadNone, llvm::Attribute::ReadOnly, llvm::BitstreamEntry::Record, llvm::Attribute::Returned, llvm::Attribute::ReturnsTwice, llvm::Attribute::SanitizeAddress, llvm::Attribute::SanitizeMemory, llvm::Attribute::SanitizeThread, llvm::StructType::setBody(), llvm::Value::setName(), llvm::StructType::setName(), llvm::Attribute::SExt, llvm::SmallVectorTemplateCommon< T >::size(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::Attribute::StackAlignment, llvm::Attribute::StackProtect, llvm::Attribute::StackProtectReq, llvm::Attribute::StackProtectStrong, llvm::SmallString< InternalLen >::str(), llvm::tgtok::String, llvm::Attribute::StructRet, llvm::BitstreamEntry::SubBlock, llvm::error_code::success(), llvm::bitc::TYPE_BLOCK_ID_NEW, llvm::bitc::TYPE_CODE_ARRAY, llvm::bitc::TYPE_CODE_DOUBLE, llvm::bitc::TYPE_CODE_FLOAT, llvm::bitc::TYPE_CODE_FP128, llvm::bitc::TYPE_CODE_FUNCTION, llvm::bitc::TYPE_CODE_FUNCTION_OLD, llvm::bitc::TYPE_CODE_HALF, llvm::bitc::TYPE_CODE_INTEGER, llvm::bitc::TYPE_CODE_LABEL, llvm::bitc::TYPE_CODE_METADATA, llvm::bitc::TYPE_CODE_NUMENTRY, llvm::bitc::TYPE_CODE_OPAQUE, llvm::bitc::TYPE_CODE_POINTER, llvm::bitc::TYPE_CODE_PPC_FP128, llvm::bitc::TYPE_CODE_STRUCT_ANON, llvm::bitc::TYPE_CODE_STRUCT_NAME, llvm::bitc::TYPE_CODE_STRUCT_NAMED, llvm::bitc::TYPE_CODE_VECTOR, llvm::bitc::TYPE_CODE_VOID, llvm::bitc::TYPE_CODE_X86_FP80, llvm::bitc::TYPE_CODE_X86_MMX, llvm::Attribute::UWTable, llvm::bitc::VALUE_SYMTAB_BLOCK_ID, llvm::bitc::VST_CODE_BBENTRY, llvm::bitc::VST_CODE_ENTRY, and llvm::Attribute::ZExt.
static int GetDecodedBinaryOpcode (unsigned Val, Type * Ty) static
Definition at line 134 of file BitcodeReader.cpp.
References llvm::APIntOps::And(), llvm::bitc::BINOP_ADD, llvm::bitc::BINOP_AND, llvm::bitc::BINOP_ASHR, llvm::bitc::BINOP_LSHR, llvm::bitc::BINOP_MUL, llvm::bitc::BINOP_OR, llvm::bitc::BINOP_SDIV, llvm::bitc::BINOP_SHL, llvm::bitc::BINOP_SREM, llvm::bitc::BINOP_SUB, llvm::bitc::BINOP_UDIV, llvm::bitc::BINOP_UREM, llvm::bitc::BINOP_XOR, llvm::Type::isFPOrFPVectorTy(), llvm::APIntOps::Or(), and llvm::APIntOps::Xor().
Referenced by llvm::BitcodeReader::ParseTriple(), and ReadWideAPInt().
static int GetDecodedCastOpcode (unsigned Val) static
Definition at line 116 of file BitcodeReader.cpp.
References llvm::bitc::CAST_ADDRSPACECAST, llvm::bitc::CAST_BITCAST, llvm::bitc::CAST_FPEXT, llvm::bitc::CAST_FPTOSI, llvm::bitc::CAST_FPTOUI, llvm::bitc::CAST_FPTRUNC, llvm::bitc::CAST_INTTOPTR, llvm::bitc::CAST_PTRTOINT, llvm::bitc::CAST_SEXT, llvm::bitc::CAST_SITOFP, llvm::bitc::CAST_TRUNC, llvm::bitc::CAST_UITOFP, and llvm::bitc::CAST_ZEXT.
Referenced by llvm::BitcodeReader::ParseTriple(), and ReadWideAPInt().
static GlobalValue::LinkageTypes GetDecodedLinkage (unsigned Val) static
Definition at line 75 of file BitcodeReader.cpp.
References llvm::GlobalValue::AppendingLinkage, llvm::GlobalValue::AvailableExternallyLinkage, llvm::GlobalValue::CommonLinkage, llvm::GlobalValue::DLLExportLinkage, llvm::GlobalValue::DLLImportLinkage, llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::ExternalWeakLinkage, llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::LinkerPrivateLinkage, llvm::GlobalValue::LinkerPrivateWeakLinkage, llvm::GlobalValue::LinkOnceAnyLinkage, llvm::GlobalValue::LinkOnceODRLinkage, llvm::GlobalValue::PrivateLinkage, llvm::GlobalValue::WeakAnyLinkage, and llvm::GlobalValue::WeakODRLinkage.
Referenced by ReadWideAPInt().
static AtomicOrdering GetDecodedOrdering (unsigned Val) static
Definition at line 175 of file BitcodeReader.cpp.
References llvm::Acquire, llvm::AcquireRelease, llvm::Monotonic, llvm::NotAtomic, llvm::bitc::ORDERING_ACQREL, llvm::bitc::ORDERING_ACQUIRE, llvm::bitc::ORDERING_MONOTONIC, llvm::bitc::ORDERING_NOTATOMIC, llvm::bitc::ORDERING_RELEASE, llvm::bitc::ORDERING_SEQCST, llvm::bitc::ORDERING_UNORDERED, llvm::Release, llvm::SequentiallyConsistent, and llvm::Unordered.
Referenced by llvm::BitcodeReader::ParseTriple().
static AtomicRMWInst::BinOp GetDecodedRMWOperation (unsigned Val) static
Definition at line 158 of file BitcodeReader.cpp.
References llvm::AtomicRMWInst::Add, llvm::AtomicRMWInst::And, llvm::AtomicRMWInst::BAD_BINOP, llvm::AtomicRMWInst::Max, llvm::AtomicRMWInst::Min, llvm::AtomicRMWInst::Nand, llvm::AtomicRMWInst::Or, llvm::bitc::RMW_ADD, llvm::bitc::RMW_AND, llvm::bitc::RMW_MAX, llvm::bitc::RMW_MIN, llvm::bitc::RMW_NAND, llvm::bitc::RMW_OR, llvm::bitc::RMW_SUB, llvm::bitc::RMW_UMAX, llvm::bitc::RMW_UMIN, llvm::bitc::RMW_XCHG, llvm::bitc::RMW_XOR, llvm::AtomicRMWInst::Sub, llvm::AtomicRMWInst::UMax, llvm::AtomicRMWInst::UMin, llvm::AtomicRMWInst::Xchg, and llvm::AtomicRMWInst::Xor.
Referenced by llvm::BitcodeReader::ParseTriple().
static SynchronizationScope GetDecodedSynchScope (unsigned Val) static
Definition at line 188 of file BitcodeReader.cpp.
References llvm::CrossThread, llvm::UndefValue::get(), llvm::Type::getInt32Ty(), LLVM_DELETED_FUNCTION, s, llvm::SingleThread, llvm::bitc::SYNCHSCOPE_CROSSTHREAD, and llvm::bitc::SYNCHSCOPE_SINGLETHREAD.
Referenced by llvm::BitcodeReader::ParseTriple().
static GlobalVariable::ThreadLocalMode GetDecodedThreadLocalMode (unsigned Val) static
Definition at line 105 of file BitcodeReader.cpp.
References llvm::GlobalVariable::GeneralDynamicTLSModel, llvm::GlobalVariable::InitialExecTLSModel, llvm::GlobalVariable::LocalDynamicTLSModel, llvm::GlobalVariable::LocalExecTLSModel, and llvm::GlobalVariable::NotThreadLocal.
Referenced by ReadWideAPInt().
static GlobalValue::VisibilityTypes GetDecodedVisibility (unsigned Val) static
Definition at line 96 of file BitcodeReader.cpp.
References llvm::GlobalValue::DefaultVisibility, llvm::GlobalValue::HiddenVisibility, and llvm::GlobalValue::ProtectedVisibility.
Referenced by ReadWideAPInt().
static APInt ReadWideAPInt (ArrayRef< uint64_t > Vals, unsigned TypeBits) static
Definition at line 1128 of file BitcodeReader.cpp.
References llvm::lltok::APFloat, llvm::Function::back(), llvm::ArrayRef< T >::begin(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::Function::begin(), llvm::BitsToDouble(), llvm::BitsToFloat(), llvm::bitc::BLOCKINFO_BLOCK_ID, llvm::c_str(), llvm::SmallVectorImpl< T >::clear(), llvm::bitc::CONSTANTS_BLOCK_ID, ConvertToString(), llvm::Function::Create(), llvm::bitc::CST_CODE_AGGREGATE, llvm::bitc::CST_CODE_BLOCKADDRESS, llvm::bitc::CST_CODE_CE_BINOP, llvm::bitc::CST_CODE_CE_CAST, llvm::bitc::CST_CODE_CE_CMP, llvm::bitc::CST_CODE_CE_EXTRACTELT, llvm::bitc::CST_CODE_CE_GEP, llvm::bitc::CST_CODE_CE_INBOUNDS_GEP, llvm::bitc::CST_CODE_CE_INSERTELT, llvm::bitc::CST_CODE_CE_SELECT, llvm::bitc::CST_CODE_CE_SHUFFLEVEC, llvm::bitc::CST_CODE_CE_SHUFVEC_EX, llvm::bitc::CST_CODE_CSTRING, llvm::bitc::CST_CODE_DATA, llvm::bitc::CST_CODE_FLOAT, llvm::bitc::CST_CODE_INLINEASM, llvm::bitc::CST_CODE_INLINEASM_OLD, llvm::bitc::CST_CODE_INTEGER, llvm::bitc::CST_CODE_NULL, llvm::bitc::CST_CODE_SETTYPE, llvm::bitc::CST_CODE_STRING, llvm::bitc::CST_CODE_UNDEF, llvm::bitc::CST_CODE_WIDE_INTEGER, llvm::BitcodeReader::decodeSignRotatedValue(), llvm::GlobalValue::DefaultVisibility, llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::Function::empty(), llvm::ArrayRef< T >::end(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::Function::end(), llvm::BitstreamEntry::EndBlock, llvm::BitstreamEntry::Error, llvm::BitcodeReader::Error(), llvm::GlobalValue::ExternalLinkage, llvm::bitc::FUNCTION_BLOCK_ID, llvm::A64CC::GE, llvm::InlineAsm::get(), llvm::ConstantInt::get(), llvm::ConstantFP::get(), llvm::ConstantArray::get(), llvm::VectorType::get(), llvm::ConstantStruct::get(), llvm::ConstantVector::get(), llvm::ConstantDataArray::get(), llvm::ConstantDataVector::get(), llvm::BlockAddress::get(), llvm::ConstantExpr::get(), llvm::UndefValue::get(), getBitWidth(), llvm::ConstantExpr::getCast(), GetDecodedBinaryOpcode(), GetDecodedCastOpcode(), GetDecodedLinkage(), GetDecodedThreadLocalMode(), GetDecodedVisibility(), llvm::SequentialType::getElementType(), llvm::ConstantExpr::getExtractElement(), llvm::ConstantExpr::getFCmp(), llvm::ConstantExpr::getGetElementPtr(), llvm::ConstantExpr::getICmp(), llvm::ConstantExpr::getInsertElement(), llvm::Type::getInt1Ty(), llvm::Type::getInt32Ty(), llvm::Type::getInt8Ty(), llvm::Constant::getNullValue(), llvm::VectorType::getNumElements(), llvm::GlobalValue::getParent(), llvm::ConstantExpr::getSelect(), llvm::ConstantExpr::getShuffleVector(), llvm::ConstantDataArray::getString(), i, I, llvm::BitstreamEntry::ID, llvm::APFloat::IEEEdouble, llvm::APFloat::IEEEhalf, llvm::APFloat::IEEEquad, llvm::APFloat::IEEEsingle, llvm::BitcodeReader::InsufficientFunctionProtos, llvm::GlobalValue::InternalLinkage, llvm::BitcodeReader::InvalidConstantReference, llvm::BitcodeReader::InvalidID, llvm::BitcodeReader::InvalidRecord, llvm::BitcodeReader::InvalidTypeForValue, llvm::BitcodeReader::InvalidValue, llvm::Type::isDoubleTy(), llvm::PossiblyExactOperator::IsExact, llvm::Type::isFloatTy(), llvm::Type::isFP128Ty(), llvm::Type::isFPOrFPVectorTy(), llvm::Type::isHalfTy(), llvm::Type::isIntegerTy(), llvm::Type::isPointerTy(), llvm::Type::isPPC_FP128Ty(), llvm::Type::isX86_FP80Ty(), llvm::BitstreamEntry::Kind, llvm::BitcodeReader::MalformedBlock, llvm::BitcodeReader::MalformedGlobalInitializerSet, llvm::bitc::METADATA_BLOCK_ID, llvm::bitc::MODULE_BLOCK_ID, llvm::bitc::MODULE_CODE_ALIAS, llvm::bitc::MODULE_CODE_ASM, llvm::bitc::MODULE_CODE_DATALAYOUT, llvm::bitc::MODULE_CODE_DEPLIB, llvm::bitc::MODULE_CODE_FUNCTION, llvm::bitc::MODULE_CODE_GCNAME, llvm::bitc::MODULE_CODE_GLOBALVAR, llvm::bitc::MODULE_CODE_PURGEVALS, llvm::bitc::MODULE_CODE_SECTIONNAME, llvm::bitc::MODULE_CODE_TRIPLE, llvm::bitc::MODULE_CODE_VERSION, llvm::OverflowingBinaryOperator::NoSignedWrap, llvm::GlobalVariable::NotThreadLocal, llvm::OverflowingBinaryOperator::NoUnsignedWrap, llvm::bitc::OBO_NO_SIGNED_WRAP, llvm::bitc::OBO_NO_UNSIGNED_WRAP, llvm::bitc::PARAMATTR_BLOCK_ID, llvm::bitc::PARAMATTR_GROUP_BLOCK_ID, llvm::bitc::PEO_EXACT, llvm::APFloat::PPCDoubleDouble, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::BitstreamEntry::Record, S, llvm::ARMBuildAttrs::Section, llvm::GlobalValue::setAlignment(), llvm::Function::setAttributes(), llvm::Function::setCallingConv(), llvm::Function::setGC(), llvm::GlobalValue::setLinkage(), llvm::GlobalValue::setSection(), llvm::GlobalValue::setUnnamedAddr(), llvm::GlobalValue::setVisibility(), llvm::ArrayRef< T >::size(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::BitstreamEntry::SubBlock, llvm::error_code::success(), llvm::swap(), TLM, transform, llvm::bitc::TYPE_BLOCK_ID_NEW, llvm::UpgradeBitCastExpr(), llvm::UpgradeGlobalVariable(), llvm::UpgradeIntrinsicFunction(), llvm::bitc::USELIST_BLOCK_ID, llvm::bitc::USELIST_CODE_ENTRY, llvm::bitc::VALUE_SYMTAB_BLOCK_ID, and llvm::APFloat::x87DoubleExtended.
Referenced by llvm::BitcodeReader::ParseTriple().