LLVM: BranchProbabilityInfo.cpp File Reference
LLVM API Documentation
BranchProbabilityInfo.cpp File Reference
#include "llvm/Analysis/BranchProbabilityInfo.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/Support/CFG.h"
#include "llvm/Support/Debug.h"
Functions
INITIALIZE_PASS_BEGIN (BranchProbabilityInfo,"branch-prob","Branch Probability Analysis", false, true) INITIALIZE_PASS_END(BranchProbabilityInfo
static uint32_t getMaxWeightFor (BasicBlock *BB)
Variables
branch prob
branch Branch Probability Analysis
branch Branch Probability false
static const uint32_t LBH_TAKEN_WEIGHT = 124
static const uint32_t LBH_NONTAKEN_WEIGHT = 4
static const uint32_t UR_TAKEN_WEIGHT = 1
Unreachable-terminating branch taken weight.
static const uint32_t UR_NONTAKEN_WEIGHT = 1024*1024 - 1
Unreachable-terminating branch not-taken weight.
static const uint32_t CC_TAKEN_WEIGHT = 4
Weight for a branch taken going into a cold block.
static const uint32_t CC_NONTAKEN_WEIGHT = 64
Weight for a branch not-taken into a cold block.
static const uint32_t PH_TAKEN_WEIGHT = 20
static const uint32_t PH_NONTAKEN_WEIGHT = 12
static const uint32_t ZH_TAKEN_WEIGHT = 20
static const uint32_t ZH_NONTAKEN_WEIGHT = 12
static const uint32_t FPH_TAKEN_WEIGHT = 20
static const uint32_t FPH_NONTAKEN_WEIGHT = 12
static const uint32_t IH_TAKEN_WEIGHT = 1024 * 1024 - 1
Invoke-terminating normal branch taken weight.
static const uint32_t IH_NONTAKEN_WEIGHT = 1
Invoke-terminating normal branch not-taken weight.
static const uint32_t NORMAL_WEIGHT = 16
static const uint32_t MIN_WEIGHT = 1
Function Documentation
static uint32_t getMaxWeightFor (BasicBlock * BB) static
Definition at line 115 of file BranchProbabilityInfo.cpp.
References BB, llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::BasicBlock::begin(), CC_NONTAKEN_WEIGHT, CC_TAKEN_WEIGHT, llvm::Attribute::Cold, llvm::LoopBase< BlockT, LoopT >::contains(), llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::BasicBlock::end(), llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_UNO, FPH_NONTAKEN_WEIGHT, FPH_TAKEN_WEIGHT, llvm::BranchInst::getCondition(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::ConstantInt::getLimitedValue(), llvm::LoopInfo::getLoopFor(), llvm::Instruction::getMetadata(), llvm::MDNode::getNumOperands(), llvm::TerminatorInst::getNumSuccessors(), llvm::User::getOperand(), llvm::MDNode::getOperand(), llvm::CmpInst::getPredicate(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), i, I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, IH_NONTAKEN_WEIGHT, IH_TAKEN_WEIGHT, llvm::Constant::isAllOnesValue(), llvm::BranchInst::isConditional(), llvm::ICmpInst::isEquality(), llvm::FCmpInst::isEquality(), llvm::ConstantInt::isOne(), llvm::Type::isPointerTy(), llvm::CmpInst::isTrueWhenEqual(), llvm::ConstantInt::isZero(), LBH_NONTAKEN_WEIGHT, LBH_TAKEN_WEIGHT, llvm::LLVMContext::MD_prof, MIN_WEIGHT, NORMAL_WEIGHT, PH_NONTAKEN_WEIGHT, PH_TAKEN_WEIGHT, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorImpl< T >::reserve(), llvm::BranchProbabilityInfo::setEdgeWeight(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::succ_begin(), llvm::succ_end(), std::swap(), UR_NONTAKEN_WEIGHT, UR_TAKEN_WEIGHT, ZH_NONTAKEN_WEIGHT, and ZH_TAKEN_WEIGHT.
INITIALIZE_PASS_BEGIN (BranchProbabilityInfo , "branch-prob" , "Branch Probability Analysis" , false , true)
Variable Documentation
branch Branch Probability Analysis
Definition at line 30 of file BranchProbabilityInfo.cpp.
const uint32_t CC_NONTAKEN_WEIGHT = 64 static
Weight for a branch not-taken into a cold block.
This is the weight for a branch not taken toward a block marked cold.
Definition at line 84 of file BranchProbabilityInfo.cpp.
Referenced by getMaxWeightFor().
const uint32_t CC_TAKEN_WEIGHT = 4 static
Weight for a branch taken going into a cold block.
This is the weight for a branch taken toward a block marked cold. A block is marked cold if it's postdominated by a block containing a call to a cold function. Cold functions are those marked with attribute 'cold'.
Definition at line 78 of file BranchProbabilityInfo.cpp.
Referenced by getMaxWeightFor().
branch Branch Probability false
Definition at line 30 of file BranchProbabilityInfo.cpp.
const uint32_t FPH_NONTAKEN_WEIGHT = 12 static
Definition at line 93 of file BranchProbabilityInfo.cpp.
Referenced by getMaxWeightFor().
const uint32_t FPH_TAKEN_WEIGHT = 20 static
Definition at line 92 of file BranchProbabilityInfo.cpp.
Referenced by getMaxWeightFor().
const uint32_t IH_NONTAKEN_WEIGHT = 1 static
Invoke-terminating normal branch not-taken weight.
This is the weight for branching to the unwind destination of an invoke instruction. This is essentially never taken.
Definition at line 106 of file BranchProbabilityInfo.cpp.
Referenced by getMaxWeightFor().
const uint32_t IH_TAKEN_WEIGHT = 1024 * 1024 - 1 static
Invoke-terminating normal branch taken weight.
This is the weight for branching to the normal destination of an invoke instruction. We expect this to happen most of the time. Set the weight to an absurdly high value so that nested loops subsume it.
Definition at line 100 of file BranchProbabilityInfo.cpp.
Referenced by getMaxWeightFor().
const uint32_t LBH_NONTAKEN_WEIGHT = 4 static
Definition at line 56 of file BranchProbabilityInfo.cpp.
Referenced by getMaxWeightFor().
const uint32_t LBH_TAKEN_WEIGHT = 124 static
Definition at line 55 of file BranchProbabilityInfo.cpp.
Referenced by getMaxWeightFor().
const uint32_t MIN_WEIGHT = 1 static
Definition at line 113 of file BranchProbabilityInfo.cpp.
Referenced by getMaxWeightFor().
const uint32_t NORMAL_WEIGHT = 16 static
Definition at line 110 of file BranchProbabilityInfo.cpp.
Referenced by getMaxWeightFor().
const uint32_t PH_NONTAKEN_WEIGHT = 12 static
Definition at line 87 of file BranchProbabilityInfo.cpp.
Referenced by getMaxWeightFor().
const uint32_t PH_TAKEN_WEIGHT = 20 static
Definition at line 86 of file BranchProbabilityInfo.cpp.
Referenced by getMaxWeightFor().
branch prob
Definition at line 30 of file BranchProbabilityInfo.cpp.
const uint32_t UR_NONTAKEN_WEIGHT = 1024*1024 - 1 static
Unreachable-terminating branch not-taken weight.
This is the weight for a branch not being taken toward a block that terminates (eventually) in unreachable. Such a branch is essentially never taken. Set the weight to an absurdly high value so that nested loops don't easily subsume it.
Definition at line 70 of file BranchProbabilityInfo.cpp.
Referenced by getMaxWeightFor().
const uint32_t UR_TAKEN_WEIGHT = 1 static
Unreachable-terminating branch taken weight.
This is the weight for a branch being taken to a block that terminates (eventually) in unreachable. These are predicted as unlikely as possible.
Definition at line 62 of file BranchProbabilityInfo.cpp.
Referenced by getMaxWeightFor().
const uint32_t ZH_NONTAKEN_WEIGHT = 12 static
Definition at line 90 of file BranchProbabilityInfo.cpp.
Referenced by getMaxWeightFor().
const uint32_t ZH_TAKEN_WEIGHT = 20 static
Definition at line 89 of file BranchProbabilityInfo.cpp.
Referenced by getMaxWeightFor().