LLVM: CFG.cpp File Reference
LLVM API Documentation
CFG.cpp File Reference
#include "llvm/Analysis/CFG.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/Analysis/Dominators.h"
#include "llvm/Analysis/LoopInfo.h"
Functions
static const Loop * getOutermostLoop (const LoopInfo *LI, const BasicBlock *BB)
static bool loopContainsBoth (const LoopInfo *LI, const BasicBlock *BB1, const BasicBlock *BB2)
static bool isPotentiallyReachableInner (SmallVectorImpl< BasicBlock * > &Worklist, BasicBlock *StopBB, const DominatorTree *DT, const LoopInfo *LI)
Function Documentation
static const Loop* getOutermostLoop (const LoopInfo * LI, const BasicBlock * BB) static
Definition at line 119 of file CFG.cpp.
References llvm::LoopInfo::getLoopFor(), and llvm::LoopBase< BlockT, LoopT >::getParentLoop().
Referenced by isPotentiallyReachableInner(), and loopContainsBoth().
static bool isPotentiallyReachableInner (SmallVectorImpl< BasicBlock * > & Worklist, BasicBlock * StopBB, const DominatorTree * DT, const LoopInfo * LI) static
Definition at line 136 of file CFG.cpp.
References BB, llvm::DominatorTree::dominates(), llvm::SmallVectorBase::empty(), getOutermostLoop(), I, llvm::SmallSet< T, N, C >::insert(), llvm::DominatorTree::isReachableFromEntry(), loopContainsBoth(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::succ_begin(), and llvm::succ_end().
Referenced by llvm::isPotentiallyReachable().
static bool loopContainsBoth (const LoopInfo * LI, const BasicBlock * BB1, const BasicBlock * BB2) static
Definition at line 129 of file CFG.cpp.
References getOutermostLoop(), and L2.
Referenced by isPotentiallyReachableInner().