LLVM: llvm::sys::path::const_iterator Class Reference
LLVM API Documentation
llvm::sys::path::const_iterator Class Reference
Path iterator.
#include <Path.h>
Public Types
typedef const StringRef value_type
typedef ptrdiff_t difference_type
typedef value_type & reference
typedef value_type * pointer
typedef std::bidirectional_iterator_tag iterator_category
Public Member Functions
reference operator* () const
pointer operator-> () const
const_iterator & operator++ ()
const_iterator & operator++ (int)
const_iterator & operator-- ()
const_iterator & operator-- (int)
bool operator== (const const_iterator &RHS) const
bool operator!= (const const_iterator &RHS) const
ptrdiff_t operator- (const const_iterator &RHS) const
Difference in bytes between this and RHS.
Friends
const_iterator begin (StringRef path)
Get begin iterator over path.
const_iterator end (StringRef path)
Get end iterator over path.
Detailed Description
Path iterator.
This is a bidirectional iterator that iterates over the individual components in path. The forward traversal order is as follows:
The root-name element, if present.
The root-directory element, if present.
Each successive filename element, if present.
Dot, if one or more trailing non-root slash characters are present. The backwards traversal order is the reverse of forward traversal.
Iteration examples. Each component is separated by ',':
/          => /
/foo       => /,foo
foo/       => foo,.
/foo/bar   => /,foo,bar
../        => ..,.
C:\foo\bar => C:,/,foo,bar
Definition at line 50 of file Path.h.
Member Typedef Documentation
typedef ptrdiff_t llvm::sys::path::const_iterator::difference_type
Definition at line 61 of file Path.h.
typedef std::bidirectional_iterator_tag llvm::sys::path::const_iterator::iterator_category
Definition at line 64 of file Path.h.
typedef value_type* llvm::sys::path::const_iterator::pointer
Definition at line 63 of file Path.h.
typedef value_type& llvm::sys::path::const_iterator::reference
Definition at line 62 of file Path.h.
typedef const StringRef llvm::sys::path::const_iterator::value_type
Definition at line 60 of file Path.h.
Member Function Documentation
bool llvm::sys::path::const_iterator::operator!= (const const_iterator & RHS) const
Definition at line 276 of file Path.cpp.
Referenced by operator->().
reference llvm::sys::path::const_iterator::operator* () const inline
Definition at line 66 of file Path.h.
const_iterator & llvm::sys::path::const_iterator::operator++ ()
Definition at line 188 of file Path.cpp.
References llvm::StringRef::endswith(), llvm::StringRef::find_first_of(), llvm::sys::path::is_separator(), llvm::StringRef::size(), llvm::StringRef::slice(), and llvm::StringRef::substr().
Referenced by operator->().
const_iterator& llvm::sys::path::const_iterator::operator++ (int)
ptrdiff_t llvm::sys::path::const_iterator::operator- (const const_iterator & RHS) const
Difference in bytes between this and RHS.
Definition at line 280 of file Path.cpp.
Referenced by operator->().
const_iterator & llvm::sys::path::const_iterator::operator-- ()
Definition at line 241 of file Path.cpp.
References llvm::sys::path::is_separator(), llvm::StringRef::size(), llvm::StringRef::slice(), and llvm::StringRef::substr().
Referenced by operator->().
const_iterator& llvm::sys::path::const_iterator::operator-- (int)
pointer llvm::sys::path::const_iterator::operator-> () const inline
Definition at line 67 of file Path.h.
References operator!=(), operator++(), operator-(), operator--(), and operator==().
bool llvm::sys::path::const_iterator::operator== (const const_iterator & RHS) const
Definition at line 271 of file Path.cpp.
References llvm::StringRef::begin().
Referenced by operator->().
Friends And Related Function Documentation
const_iterator begin (StringRef path) friend
Get begin iterator over path.
Parameters
path Input path.
Returns
Iterator initialized with the first component of path.
Definition at line 173 of file Path.cpp.
Referenced by llvm::sys::path::append(), IsPointerOffset(), llvm::sys::path::rend(), llvm::sys::path::root_directory(), llvm::sys::path::root_name(), and llvm::sys::path::root_path().
const_iterator end (StringRef path) friend
Get end iterator over path.
Parameters
path Input path.
Returns
Iterator initialized to the end of path.
Definition at line 181 of file Path.cpp.
Referenced by llvm::sys::path::append(), llvm::PBQPBuilderWithCoalescing::build(), llvm::DWARFDebugLine::LineTable::dump(), llvm::sys::path::filename(), llvm::MipsRegisterInfo::getReservedRegs(), isIdentifierChar(), IsPointerOffset(), isSimpleLoadStore(), llvm::opt::OptTable::PrintHelp(), llvm::RuntimeDyldELF::processRelocationRef(), llvm::sys::path::rbegin(), llvm::sys::path::rend(), llvm::sys::path::root_directory(), llvm::sys::path::root_name(), llvm::sys::path::root_path(), and llvm::MCJIT::~MCJIT().
The documentation for this class was generated from the following files:
Path.h
Path.cpp