LLVM: llvm::VLIWPacketizerList Class Reference
LLVM API Documentation
llvm::VLIWPacketizerList Class Reference
#include <DFAPacketizer.h>
Public Member Functions
VLIWPacketizerList (MachineFunction &MF, MachineLoopInfo &MLI, MachineDominatorTree &MDT, bool IsPostRA)
virtual ~VLIWPacketizerList ()
void PacketizeMIs (MachineBasicBlock *MBB, MachineBasicBlock::iterator BeginItr, MachineBasicBlock::iterator EndItr)
DFAPacketizer * getResourceTracker ()
virtual MachineBasicBlock::iterator addToPacket (MachineInstr *MI)
void endPacket (MachineBasicBlock *MBB, MachineInstr *MI)
virtual void initPacketizerState ()
virtual bool ignorePseudoInstruction (MachineInstr *I, MachineBasicBlock *MBB)
virtual bool isSoloInstruction (MachineInstr *MI)
virtual bool isLegalToPacketizeTogether (SUnit *SUI, SUnit *SUJ)
virtual bool isLegalToPruneDependencies (SUnit *SUI, SUnit *SUJ)
Protected Attributes
const TargetMachine & TM
const MachineFunction & MF
const TargetInstrInfo * TII
DefaultVLIWScheduler * VLIWScheduler
std::vector< MachineInstr * > CurrentPacketMIs
DFAPacketizer * ResourceTracker
std::map< MachineInstr *, SUnit * > MIToSUnit
Detailed Description
Definition at line 92 of file DFAPacketizer.h.
Constructor & Destructor Documentation
VLIWPacketizerList::VLIWPacketizerList (MachineFunction & MF, MachineLoopInfo & MLI, MachineDominatorTree & MDT, bool IsPostRA)
Definition at line 128 of file DFAPacketizer.cpp.
References llvm::TargetInstrInfo::CreateTargetScheduleState(), llvm::TargetMachine::getInstrInfo(), ResourceTracker, TII, TM, and VLIWScheduler.
VLIWPacketizerList::~VLIWPacketizerList () virtual
Definition at line 137 of file DFAPacketizer.cpp.
References ResourceTracker, and VLIWScheduler.
Member Function Documentation
virtual MachineBasicBlock::iterator llvm::VLIWPacketizerList::addToPacket (MachineInstr * MI) inline virtual
Definition at line 125 of file DFAPacketizer.h.
References llvm::A64CC::MI, MII, and llvm::DFAPacketizer::reserveResources().
Referenced by PacketizeMIs().
void VLIWPacketizerList::endPacket (MachineBasicBlock * MBB, MachineInstr * MI)
Definition at line 147 of file DFAPacketizer.cpp.
References llvm::DFAPacketizer::clearResources(), CurrentPacketMIs, llvm::finalizeBundle(), and ResourceTracker.
Referenced by PacketizeMIs().
DFAPacketizer* llvm::VLIWPacketizerList::getResourceTracker () inline
Definition at line 122 of file DFAPacketizer.h.
virtual bool llvm::VLIWPacketizerList::ignorePseudoInstruction (MachineInstr * I, MachineBasicBlock * MBB) inline virtual
Definition at line 141 of file DFAPacketizer.h.
Referenced by PacketizeMIs().
virtual void llvm::VLIWPacketizerList::initPacketizerState () inline virtual
Definition at line 138 of file DFAPacketizer.h.
Referenced by PacketizeMIs().
virtual bool llvm::VLIWPacketizerList::isLegalToPacketizeTogether (SUnit * SUI, SUnit * SUJ) inline virtual
Definition at line 154 of file DFAPacketizer.h.
Referenced by PacketizeMIs().
virtual bool llvm::VLIWPacketizerList::isLegalToPruneDependencies (SUnit * SUI, SUnit * SUJ) inline virtual
Definition at line 160 of file DFAPacketizer.h.
Referenced by PacketizeMIs().
virtual bool llvm::VLIWPacketizerList::isSoloInstruction (MachineInstr * MI) inline virtual
Definition at line 148 of file DFAPacketizer.h.
Referenced by PacketizeMIs().
void VLIWPacketizerList::PacketizeMIs (MachineBasicBlock * MBB, MachineBasicBlock::iterator BeginItr, MachineBasicBlock::iterator EndItr)
Definition at line 158 of file DFAPacketizer.cpp.
References addToPacket(), llvm::DFAPacketizer::canReserveResources(), CurrentPacketMIs, endPacket(), llvm::ScheduleDAGInstrs::enterRegion(), llvm::ScheduleDAGInstrs::exitRegion(), llvm::ScheduleDAGInstrs::finishBlock(), llvm::SUnit::getInstr(), i, ignorePseudoInstruction(), initPacketizerState(), isLegalToPacketizeTogether(), isLegalToPruneDependencies(), isSoloInstruction(), llvm::A64CC::MI, MIToSUnit, ResourceTracker, llvm::DefaultVLIWScheduler::schedule(), llvm::ScheduleDAGInstrs::startBlock(), llvm::ScheduleDAG::SUnits, and VLIWScheduler.
Member Data Documentation
std::vector<MachineInstr*> llvm::VLIWPacketizerList::CurrentPacketMIs protected
Definition at line 102 of file DFAPacketizer.h.
Referenced by endPacket(), and PacketizeMIs().
const MachineFunction& llvm::VLIWPacketizerList::MF protected
Definition at line 95 of file DFAPacketizer.h.
std::map<MachineInstr*, SUnit*> llvm::VLIWPacketizerList::MIToSUnit protected
Definition at line 107 of file DFAPacketizer.h.
Referenced by PacketizeMIs().
DFAPacketizer* llvm::VLIWPacketizerList::ResourceTracker protected
Definition at line 104 of file DFAPacketizer.h.
Referenced by endPacket(), PacketizeMIs(), VLIWPacketizerList(), and ~VLIWPacketizerList().
const TargetInstrInfo* llvm::VLIWPacketizerList::TII protected
Definition at line 96 of file DFAPacketizer.h.
Referenced by VLIWPacketizerList().
const TargetMachine& llvm::VLIWPacketizerList::TM protected
Definition at line 94 of file DFAPacketizer.h.
Referenced by VLIWPacketizerList().
DefaultVLIWScheduler* llvm::VLIWPacketizerList::VLIWScheduler protected
Definition at line 99 of file DFAPacketizer.h.
Referenced by PacketizeMIs(), VLIWPacketizerList(), and ~VLIWPacketizerList().
The documentation for this class was generated from the following files:
DFAPacketizer.h
DFAPacketizer.cpp