LLVM: llvm::AggressiveAntiDepBreaker Class Reference
LLVM API Documentation
llvm::AggressiveAntiDepBreaker Class Reference
Class AggressiveAntiDepBreaker.
#include <AggressiveAntiDepBreaker.h>
Public Member Functions
AggressiveAntiDepBreaker (MachineFunction &MFi, const RegisterClassInfo &RCI, TargetSubtargetInfo::RegClassVector &CriticalPathRCs)
~AggressiveAntiDepBreaker ()
void StartBlock (MachineBasicBlock *BB)
Start - Initialize anti-dep breaking for a new basic block.
unsigned BreakAntiDependencies (const std::vector< SUnit > &SUnits, MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned InsertPosIndex, DbgValueVector &DbgValues)
void Observe (MachineInstr *MI, unsigned Count, unsigned InsertPosIndex)
void FinishBlock ()
Finish - Finish anti-dep breaking for a basic block.
Public Member Functions inherited from llvm::AntiDepBreaker
virtual ~AntiDepBreaker ()
void UpdateDbgValue (MachineInstr *MI, unsigned OldReg, unsigned NewReg)
Additional Inherited Members
Public Types inherited from llvm::AntiDepBreaker
typedef std::vector< std::pair< MachineInstr *, MachineInstr * > > DbgValueVector
Detailed Description
Class AggressiveAntiDepBreaker.
Definition at line 117 of file AggressiveAntiDepBreaker.h.
Constructor & Destructor Documentation
AggressiveAntiDepBreaker::AggressiveAntiDepBreaker (MachineFunction & MFi, const RegisterClassInfo & RCI, TargetSubtargetInfo::RegClassVector & CriticalPathRCs)
Definition at line 116 of file AggressiveAntiDepBreaker.cpp.
References llvm::dbgs(), DEBUG, llvm::BitVector::find_first(), llvm::BitVector::find_next(), llvm::TargetRegisterInfo::getAllocatableSet(), llvm::MCRegisterInfo::getName(), i, llvm::BitVector::none(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::AggressiveAntiDepState::IsLive().
AggressiveAntiDepBreaker::~AggressiveAntiDepBreaker ()
Definition at line 142 of file AggressiveAntiDepBreaker.cpp.
Member Function Documentation
unsigned AggressiveAntiDepBreaker::BreakAntiDependencies (const std::vector< SUnit > & SUnits, MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned InsertPosIndex, DbgValueVector & DbgValues) virtual
BreakAntiDependencies - Identifiy anti-dependencies along the critical path of the ScheduleDAG and break them by renaming registers.
BreakAntiDependencies - Identifiy anti-dependencies within the ScheduleDAG and break them by renaming registers.
Implements llvm::AntiDepBreaker.
Definition at line 697 of file AggressiveAntiDepBreaker.cpp.
References llvm::SDep::Anti, AntiDepEdges(), llvm::BitVector::any(), CriticalPathStep(), llvm::SDep::Data, llvm::dbgs(), DEBUG, llvm::MachineInstr::dump(), llvm::MachineInstr::findRegisterDefOperand(), llvm::AggressiveAntiDepState::GetDefIndices(), llvm::SUnit::getDepth(), llvm::AggressiveAntiDepState::GetGroup(), llvm::SUnit::getInstr(), llvm::AggressiveAntiDepState::GetKillIndices(), llvm::SDep::getKind(), llvm::MCRegisterInfo::getName(), llvm::MCRegisterInfo::getNumRegs(), llvm::SDep::getReg(), llvm::AggressiveAntiDepState::GetRegRefs(), llvm::SDep::getSUnit(), i, I, llvm::MachineRegisterInfo::isAllocatable(), llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isImplicit(), llvm::MachineInstr::isKill(), llvm::AggressiveAntiDepState::IsLive(), llvm::SUnit::Latency, llvm::A64CC::MI, llvm::AggressiveAntiDepState::RegisterReference::Operand, llvm::SDep::Output, P, llvm::SUnit::Preds, S, llvm::MachineOperand::setReg(), llvm::BitVector::test(), llvm::AggressiveAntiDepState::UnionGroups(), and llvm::AntiDepBreaker::UpdateDbgValue().
void AggressiveAntiDepBreaker::FinishBlock () virtual
Finish - Finish anti-dep breaking for a basic block.
Implements llvm::AntiDepBreaker.
Definition at line 184 of file AggressiveAntiDepBreaker.cpp.
void AggressiveAntiDepBreaker::Observe (MachineInstr * MI, unsigned Count, unsigned InsertPosIndex) virtual
Observe - Update liveness information to account for the current instruction, which will not be scheduled.
Implements llvm::AntiDepBreaker.
Definition at line 189 of file AggressiveAntiDepBreaker.cpp.
References llvm::dbgs(), DEBUG, llvm::MachineInstr::dump(), llvm::MachineInstr::findRegisterDefOperand(), llvm::MachineInstr::findRegisterUseOperand(), llvm::AggressiveAntiDepState::GetDefIndices(), llvm::AggressiveAntiDepState::GetGroup(), llvm::MCRegisterInfo::getName(), llvm::MachineInstr::getNumOperands(), llvm::MCRegisterInfo::getNumRegs(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), i, llvm::MachineOperand::isDef(), llvm::MachineOperand::isImplicit(), llvm::AggressiveAntiDepState::IsLive(), llvm::MachineOperand::isReg(), llvm::MachineInstr::isRegTiedToUseOperand(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::A64CC::MI, and llvm::AggressiveAntiDepState::UnionGroups().
void AggressiveAntiDepBreaker::StartBlock (MachineBasicBlock * BB) virtual
Start - Initialize anti-dep breaking for a new basic block.
Implements llvm::AntiDepBreaker.
Definition at line 146 of file AggressiveAntiDepBreaker.cpp.
References llvm::MachineBasicBlock::back(), BB, llvm::MachineBasicBlock::empty(), llvm::TargetRegisterInfo::getCalleeSavedRegs(), llvm::AggressiveAntiDepState::GetDefIndices(), llvm::MachineFunction::getFrameInfo(), llvm::AggressiveAntiDepState::GetKillIndices(), llvm::MCRegisterInfo::getNumRegs(), llvm::MachineFrameInfo::getPristineRegs(), I, llvm::MachineInstr::isReturn(), llvm::MCRegAliasIterator::isValid(), llvm::MachineBasicBlock::size(), llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_end(), llvm::BitVector::test(), and llvm::AggressiveAntiDepState::UnionGroups().
The documentation for this class was generated from the following files:
AggressiveAntiDepBreaker.h
AggressiveAntiDepBreaker.cpp