LLVM: llvm::ManagedStaticBase Class Reference
LLVM API Documentation
llvm::ManagedStaticBase Class Reference
ManagedStaticBase - Common base class for ManagedStatic instances.
#include <ManagedStatic.h>
Public Member Functions
bool isConstructed () const
isConstructed - Return true if this object has not been created yet.
void destroy () const
Protected Member Functions
void RegisterManagedStatic (void *(*creator)(), void(*deleter)(void *)) const
Protected Attributes
void * Ptr
void(* DeleterFn)(void *)
const ManagedStaticBase * Next
Detailed Description
ManagedStaticBase - Common base class for ManagedStatic instances.
Definition at line 39 of file ManagedStatic.h.
Member Function Documentation
void ManagedStaticBase::destroy () const
Definition at line 59 of file ManagedStatic.cpp.
References DeleterFn, Next, and Ptr.
Referenced by llvm::llvm_shutdown().
bool llvm::ManagedStaticBase::isConstructed () const inline
isConstructed - Return true if this object has not been created yet.
Definition at line 50 of file ManagedStatic.h.
Referenced by llvm::PluginLoader::getNumPlugins(), llvm::PluginLoader::getPlugin(), llvm::sys::DynamicLibrary::SearchForAddressOfSymbol(), and llvm::PrettyStackTraceEntry::~PrettyStackTraceEntry().
void ManagedStaticBase::RegisterManagedStatic (void *(*)() creator, void(*)(void *) deleter) const protected
Definition at line 22 of file ManagedStatic.cpp.
References DeleterFn, llvm::llvm_acquire_global_lock(), llvm::llvm_is_multithreaded(), llvm::llvm_release_global_lock(), llvm::sys::MemoryFence(), Next, Ptr, StaticList, TsanHappensBefore, TsanIgnoreWritesBegin, and TsanIgnoreWritesEnd.
Member Data Documentation
void(* llvm::ManagedStaticBase::DeleterFn) (void *) mutable protected
Definition at line 44 of file ManagedStatic.h.
Referenced by destroy(), and RegisterManagedStatic().
const ManagedStaticBase* llvm::ManagedStaticBase::Next mutable protected
Definition at line 45 of file ManagedStatic.h.
Referenced by destroy(), and RegisterManagedStatic().
void* llvm::ManagedStaticBase::Ptr mutable protected
Definition at line 43 of file ManagedStatic.h.
Referenced by destroy(), and RegisterManagedStatic().
The documentation for this class was generated from the following files:
ManagedStatic.h
ManagedStatic.cpp