LLVM: llvm::SimplifyFortifiedLibCalls Class Reference
LLVM API Documentation
llvm::SimplifyFortifiedLibCalls Class Reference abstract
#include <BuildLibCalls.h>
Public Member Functions
virtual ~SimplifyFortifiedLibCalls ()
bool fold (CallInst *CI, const DataLayout *TD, const TargetLibraryInfo *TLI)
Protected Member Functions
virtual void replaceCall (Value *With)=0
virtual bool isFoldable (unsigned SizeCIOp, unsigned SizeArgOp, bool isString) const =0
Protected Attributes
CallInst * CI
Detailed Description
SimplifyFortifiedLibCalls - Helper class for folding checked library calls (e.g. __strcpy_chk) into their unchecked counterparts.
Definition at line 113 of file BuildLibCalls.h.
Constructor & Destructor Documentation
SimplifyFortifiedLibCalls::~SimplifyFortifiedLibCalls () virtual
Definition at line 467 of file BuildLibCalls.cpp.
Member Function Documentation
bool SimplifyFortifiedLibCalls::fold (CallInst * CI, const DataLayout * TD, const TargetLibraryInfo * TLI)
Definition at line 469 of file BuildLibCalls.cpp.
References B, CI, llvm::IRBuilder< preserveNames, T, Inserter >::CreateIntCast(), llvm::IRBuilderBase::CreateMemCpy(), llvm::IRBuilderBase::CreateMemMove(), llvm::IRBuilderBase::CreateMemSet(), llvm::EmitStrCpy(), llvm::EmitStrNCpy(), llvm::CallInst::getArgOperand(), llvm::CallInst::getCalledFunction(), llvm::BasicBlock::getContext(), llvm::Function::getFunctionType(), llvm::Type::getInt8PtrTy(), llvm::IRBuilderBase::getInt8Ty(), llvm::DataLayout::getIntPtrType(), llvm::Value::getName(), llvm::FunctionType::getNumParams(), llvm::FunctionType::getParamType(), llvm::Instruction::getParent(), llvm::FunctionType::getReturnType(), isFoldable(), llvm::Type::isIntegerTy(), llvm::Type::isPointerTy(), replaceCall(), llvm::AArch64ISD::Ret, and llvm::StringRef::substr().
virtual bool llvm::SimplifyFortifiedLibCalls::isFoldable (unsigned SizeCIOp, unsigned SizeArgOp, bool isString) const protected pure virtual
Referenced by fold().
virtual void llvm::SimplifyFortifiedLibCalls::replaceCall (Value * With) protected pure virtual
Referenced by fold().
Member Data Documentation
CallInst* llvm::SimplifyFortifiedLibCalls::CI protected
Definition at line 115 of file BuildLibCalls.h.
Referenced by fold().
The documentation for this class was generated from the following files:
BuildLibCalls.h
BuildLibCalls.cpp