LLVM: llvm::Interval Class Reference
LLVM API Documentation
llvm::Interval Class Reference
#include <ImmutableIntervalMap.h>
Public Types
typedef std::vector< BasicBlock * >::iterator succ_iterator
typedef std::vector< BasicBlock * >::iterator pred_iterator
typedef std::vector< BasicBlock * >::iterator node_iterator
Public Member Functions
Interval (int64_t S, int64_t E)
int64_t getStart () const
int64_t getEnd () const
Interval (BasicBlock *Header)
Interval (const Interval &I)
BasicBlock * getHeaderNode () const
bool contains (BasicBlock *BB) const
contains - Find out if a basic block is in this interval
bool isSuccessor (BasicBlock *BB) const
isSuccessor - find out if a basic block is a successor of this Interval
bool operator== (const Interval &I) const
bool isLoop () const
isLoop - Find out if there is a back edge in this interval...
void print (raw_ostream &O) const
print - Show contents in human readable format...
Public Attributes
std::vector< BasicBlock * > Nodes
std::vector< BasicBlock * > Successors
std::vector< BasicBlock * > Predecessors
Detailed Description
Interval Class - An Interval is a set of nodes defined such that every node in the interval has all of its predecessors in the interval (except for the header)
Definition at line 21 of file ImmutableIntervalMap.h.
Member Typedef Documentation
typedef std::vector<BasicBlock*>::iterator llvm::Interval::node_iterator
Definition at line 45 of file Interval.h.
typedef std::vector<BasicBlock*>::iterator llvm::Interval::pred_iterator
Definition at line 44 of file Interval.h.
typedef std::vector<BasicBlock*>::iterator llvm::Interval::succ_iterator
Definition at line 43 of file Interval.h.
Constructor & Destructor Documentation
llvm::Interval::Interval (int64_t S, int64_t E) inline
Definition at line 27 of file ImmutableIntervalMap.h.
llvm::Interval::Interval (BasicBlock * Header) inline
Definition at line 47 of file Interval.h.
References Nodes.
llvm::Interval::Interval (const Interval & I) inline
Definition at line 51 of file Interval.h.
Member Function Documentation
bool llvm::Interval::contains (BasicBlock * BB) const inline
contains - Find out if a basic block is in this interval
Definition at line 72 of file Interval.h.
References i.
Referenced by isLoop(), and llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::operator++().
int64_t llvm::Interval::getEnd () const inline
Definition at line 30 of file ImmutableIntervalMap.h.
Referenced by llvm::ImutIntervalAVLFactory< llvm::ImutIntervalInfo< ValT > >::Find(), llvm::ImutIntervalInfo< T >::isContainedIn(), llvm::ImutIntervalInfo< T >::isEqual(), and llvm::ImutIntervalInfo< T >::isLess().
BasicBlock* llvm::Interval::getHeaderNode () const inline
Definition at line 54 of file Interval.h.
Referenced by llvm::getNodeHeader(), and llvm::IntervalPartition::print().
int64_t llvm::Interval::getStart () const inline
Definition at line 29 of file ImmutableIntervalMap.h.
Referenced by llvm::ImutIntervalAVLFactory< llvm::ImutIntervalInfo< ValT > >::Find(), llvm::ImutIntervalInfo< T >::isContainedIn(), llvm::ImutIntervalInfo< T >::isEqual(), and llvm::ImutIntervalInfo< T >::isLess().
bool Interval::isLoop () const
isLoop - Find out if there is a back edge in this interval...
Definition at line 29 of file Interval.cpp.
References contains(), I, llvm::pred_begin(), and llvm::pred_end().
Referenced by operator==().
bool llvm::Interval::isSuccessor (BasicBlock * BB) const inline
isSuccessor - find out if a basic block is a successor of this Interval
Definition at line 81 of file Interval.h.
References i.
Referenced by llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::operator++().
bool llvm::Interval::operator== (const Interval & I) const inline
Equality operator. It is only valid to compare two intervals from the same partition, because of this, all we have to check is the header node for equality.
Definition at line 93 of file Interval.h.
References isLoop(), and print().
void Interval::print (raw_ostream & O) const
print - Show contents in human readable format...
Definition at line 40 of file Interval.cpp.
References I, Nodes, Predecessors, and Successors.
Referenced by operator==().
Member Data Documentation
std::vector<BasicBlock*> llvm::Interval::Nodes
Nodes - The basic blocks in this interval.
Definition at line 58 of file Interval.h.
Referenced by llvm::addNodeToInterval(), Interval(), llvm::IntervalPartition::print(), and print().
std::vector<BasicBlock*> llvm::Interval::Predecessors
Predecessors - List of BasicBlocks that have this Interval's header block as one of their successors.
Definition at line 69 of file Interval.h.
Referenced by llvm::IntervalPartition::print(), and print().
std::vector<BasicBlock*> llvm::Interval::Successors
Successors - List of BasicBlocks that are reachable directly from nodes in this interval, but are not in the interval themselves. These nodes necessarily must be header nodes for other intervals.
Definition at line 64 of file Interval.h.
Referenced by llvm::IntervalIterator< NodeTy, OrigContainer_t, GT, IGT >::operator++(), llvm::IntervalPartition::print(), and print().
The documentation for this class was generated from the following files:
ImmutableIntervalMap.h
Interval.h
Interval.cpp