LLVM: llvm::SystemZSelectionDAGInfo Class Reference
LLVM API Documentation
llvm::SystemZSelectionDAGInfo Class Reference
#include <SystemZSelectionDAGInfo.h>
Public Member Functions
SystemZSelectionDAGInfo (const SystemZTargetMachine &TM)
~SystemZSelectionDAGInfo ()
virtual SDValue EmitTargetCodeForMemcpy (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Dst, SDValue Src, SDValue Size, unsigned Align, bool IsVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const LLVM_OVERRIDE
virtual SDValue EmitTargetCodeForMemset (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Dst, SDValue Byte, SDValue Size, unsigned Align, bool IsVolatile, MachinePointerInfo DstPtrInfo) const LLVM_OVERRIDE
virtual std::pair< SDValue, SDValue > EmitTargetCodeForMemcmp (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Src1, SDValue Src2, SDValue Size, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const LLVM_OVERRIDE
virtual std::pair< SDValue, SDValue > EmitTargetCodeForMemchr (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Src, SDValue Char, SDValue Length, MachinePointerInfo SrcPtrInfo) const LLVM_OVERRIDE
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrcpy (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Dest, SDValue Src, MachinePointerInfo DestPtrInfo, MachinePointerInfo SrcPtrInfo, bool isStpcpy) const LLVM_OVERRIDE
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrcmp (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Src1, SDValue Src2, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const LLVM_OVERRIDE
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrlen (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Src, MachinePointerInfo SrcPtrInfo) const LLVM_OVERRIDE
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrnlen (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Src, SDValue MaxLength, MachinePointerInfo SrcPtrInfo) const LLVM_OVERRIDE
Public Member Functions inherited from llvm::TargetSelectionDAGInfo
TargetSelectionDAGInfo (const TargetMachine &TM)
virtual ~TargetSelectionDAGInfo ()
virtual SDValue EmitTargetCodeForMemmove (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const
Additional Inherited Members
Protected Member Functions inherited from llvm::TargetSelectionDAGInfo
const DataLayout * getDataLayout () const
Detailed Description
Definition at line 23 of file SystemZSelectionDAGInfo.h.
Constructor & Destructor Documentation
SystemZSelectionDAGInfo::SystemZSelectionDAGInfo (const SystemZTargetMachine & TM) explicit
Definition at line 21 of file SystemZSelectionDAGInfo.cpp.
SystemZSelectionDAGInfo::~SystemZSelectionDAGInfo ()
Definition at line 25 of file SystemZSelectionDAGInfo.cpp.
Member Function Documentation
std::pair< SDValue, SDValue > SystemZSelectionDAGInfo::EmitTargetCodeForMemchr (SelectionDAG & DAG, SDLoc dl, SDValue Chain, SDValue Src, SDValue Char, SDValue Length, MachinePointerInfo SrcPtrInfo) const virtual
EmitTargetCodeForMemchr - Emit target-specific code that performs a memchr, in cases where that is faster than a libcall. The first returned SDValue is the result of the memchr and the second is the chain. Both SDValues can be null if a normal libcall should be used.
Reimplemented from llvm::TargetSelectionDAGInfo.
Definition at line 208 of file SystemZSelectionDAGInfo.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::SystemZ::CCMASK_SRST, llvm::SystemZ::CCMASK_SRST_FOUND, EmitTargetCodeForStrcpy(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::MVT::Glue, llvm::MVT::i32, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SystemZISD::SEARCH_STRING, llvm::SystemZISD::SELECT_CCMASK, and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by EmitTargetCodeForMemcmp().
std::pair< SDValue, SDValue > SystemZSelectionDAGInfo::EmitTargetCodeForMemcmp (SelectionDAG & DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const virtual
EmitTargetCodeForMemcmp - Emit target-specific code that performs a memcmp, in cases where that is faster than a libcall. The first returned SDValue is the result of the memcmp and the second is the chain. Both SDValues can be null if a normal libcall should be used.
Reimplemented from llvm::TargetSelectionDAGInfo.
Definition at line 193 of file SystemZSelectionDAGInfo.cpp.
References addIPMSequence(), emitCLC(), EmitTargetCodeForMemchr(), and llvm::SDValue::getValue().
Referenced by addIPMSequence().
SDValue SystemZSelectionDAGInfo::EmitTargetCodeForMemcpy (SelectionDAG & DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const virtual
EmitTargetCodeForMemcpy - Emit target-specific code that performs a memcpy. This can be used by targets to provide code sequences for cases that don't fit the target's parameters for simple loads/stores and can be more efficient than using a library call. This function can return a null SDValue if the target declines to use custom code and a different lowering strategy should be used.
If AlwaysInline is true, the size is constant and the target should not emit any calls and is strongly encouraged to attempt to emit inline code even if it is beyond the usual threshold because this intrinsic is being expanded in a place where calls are not feasible (e.g. within the prologue for another call). If the target chooses to decline an AlwaysInline request here, legalize will resort to using simple loads and stores.
Reimplemented from llvm::TargetSelectionDAGInfo.
Definition at line 57 of file SystemZSelectionDAGInfo.cpp.
References emitMemMem(), llvm::SystemZISD::MVC, and llvm::SystemZISD::MVC_LOOP.
Referenced by emitMemMem().
SDValue SystemZSelectionDAGInfo::EmitTargetCodeForMemset (SelectionDAG & DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, MachinePointerInfo DstPtrInfo) const virtual
EmitTargetCodeForMemset - Emit target-specific code that performs a memset. This can be used by targets to provide code sequences for cases that don't fit the target's parameters for simple stores and can be more efficient than using a library call. This function can return a null SDValue if the target declines to use custom code and a different lowering strategy should be used.
Reimplemented from llvm::TargetSelectionDAGInfo.
Definition at line 87 of file SystemZSelectionDAGInfo.cpp.
References llvm::ISD::ADD, llvm::CountPopulation_64(), llvm::dyn_cast(), emitMemMem(), llvm::findLastSet(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getStore(), llvm::SDValue::getValueType(), llvm::MachinePointerInfo::getWithOffset(), llvm::ConstantSDNode::getZExtValue(), memsetStore(), llvm::SystemZISD::MVC, llvm::SystemZISD::MVC_LOOP, llvm::MVT::Other, llvm::ISD::TokenFactor, llvm::SystemZISD::XC, and llvm::SystemZISD::XC_LOOP.
Referenced by memsetStore().
std::pair< SDValue, SDValue > SystemZSelectionDAGInfo::EmitTargetCodeForStrcmp (SelectionDAG & DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const virtual
EmitTargetCodeForStrcmp - Emit target-specific code that performs a strcmp, in cases where that is faster than a libcall. The first returned SDValue is the result of the strcmp and the second is the chain. Both SDValues can be null if a normal libcall should be used.
Reimplemented from llvm::TargetSelectionDAGInfo.
Definition at line 249 of file SystemZSelectionDAGInfo.cpp.
References addIPMSequence(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::MVT::i32, llvm::MVT::Other, and llvm::SystemZISD::STRCMP.
Referenced by EmitTargetCodeForStrcpy().
std::pair< SDValue, SDValue > SystemZSelectionDAGInfo::EmitTargetCodeForStrcpy (SelectionDAG & DAG, SDLoc DL, SDValue Chain, SDValue Dest, SDValue Src, MachinePointerInfo DestPtrInfo, MachinePointerInfo SrcPtrInfo, bool isStpcpy) const virtual
EmitTargetCodeForStrcpy - Emit target-specific code that performs a strcpy or stpcpy, in cases where that is faster than a libcall. The first returned SDValue is the result of the copy (the start of the destination string for strcpy, a pointer to the null terminator for stpcpy) and the second is the chain. Both SDValues can be null if a normal libcall should be used.
Reimplemented from llvm::TargetSelectionDAGInfo.
Definition at line 238 of file SystemZSelectionDAGInfo.cpp.
References EmitTargetCodeForStrcmp(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::i32, llvm::MVT::Other, and llvm::SystemZISD::STPCPY.
Referenced by EmitTargetCodeForMemchr().
std::pair< SDValue, SDValue > SystemZSelectionDAGInfo::EmitTargetCodeForStrlen (SelectionDAG & DAG, SDLoc DL, SDValue Chain, SDValue Src, MachinePointerInfo SrcPtrInfo) const virtual
Reimplemented from llvm::TargetSelectionDAGInfo.
Definition at line 279 of file SystemZSelectionDAGInfo.cpp.
References EmitTargetCodeForStrnlen(), getBoundedStrlen(), llvm::SelectionDAG::getConstant(), and llvm::SDValue::getValueType().
Referenced by getBoundedStrlen().
std::pair< SDValue, SDValue > SystemZSelectionDAGInfo::EmitTargetCodeForStrnlen (SelectionDAG & DAG, SDLoc DL, SDValue Chain, SDValue Src, SDValue MaxLength, MachinePointerInfo SrcPtrInfo) const virtual
Reimplemented from llvm::TargetSelectionDAGInfo.
Definition at line 286 of file SystemZSelectionDAGInfo.cpp.
References llvm::ISD::ADD, getBoundedStrlen(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValueType(), and llvm::SelectionDAG::getZExtOrTrunc().
Referenced by EmitTargetCodeForStrlen().
The documentation for this class was generated from the following files:
SystemZSelectionDAGInfo.h
SystemZSelectionDAGInfo.cpp