LLVM: llvm::MipsTargetLowering::MipsCC Class Reference
LLVM API Documentation
llvm::MipsTargetLowering::MipsCC Class Reference
#include <MipsISelLowering.h>
Public Types
enum SpecialCallingConvType { Mips16RetHelperConv, NoSpecialCallingConv }
typedef SmallVectorImpl< ByValArgInfo >::const_iterator byval_iterator
Public Member Functions
MipsCC (CallingConv::ID CallConv, bool IsO32, bool IsFP64, CCState &Info, SpecialCallingConvType SpecialCallingConv=NoSpecialCallingConv)
void analyzeCallOperands (const SmallVectorImpl< ISD::OutputArg > &Outs, bool IsVarArg, bool IsSoftFloat, const SDNode *CallNode, std::vector< ArgListEntry > &FuncArgs)
void analyzeFormalArguments (const SmallVectorImpl< ISD::InputArg > &Ins, bool IsSoftFloat, Function::const_arg_iterator FuncArg)
void analyzeCallResult (const SmallVectorImpl< ISD::InputArg > &Ins, bool IsSoftFloat, const SDNode *CallNode, const Type *RetTy) const
void analyzeReturn (const SmallVectorImpl< ISD::OutputArg > &Outs, bool IsSoftFloat, const Type *RetTy) const
const CCState & getCCInfo () const
bool hasByValArg () const
hasByValArg - Returns true if function has byval arguments.
unsigned regSize () const
regSize - Size (in number of bits) of integer registers.
unsigned numIntArgRegs () const
numIntArgRegs - Number of integer registers available for calls.
unsigned reservedArgArea () const
const uint16_t * intArgRegs () const
Return pointer to array of integer argument registers.
byval_iterator byval_begin () const
byval_iterator byval_end () const
Detailed Description
MipsCC - This class provides methods used to analyze formal and call arguments and inquire about calling convention information.
Definition at line 340 of file MipsISelLowering.h.
Member Typedef Documentation
typedef SmallVectorImpl<ByValArgInfo>::const_iterator llvm::MipsTargetLowering::MipsCC::byval_iterator
Definition at line 383 of file MipsISelLowering.h.
Member Enumeration Documentation
enum llvm::MipsTargetLowering::MipsCC::SpecialCallingConvType
Enumerator
Mips16RetHelperConv
NoSpecialCallingConv
Definition at line 342 of file MipsISelLowering.h.
Constructor & Destructor Documentation
MipsTargetLowering::MipsCC::MipsCC (CallingConv::ID CallConv, bool IsO32, bool IsFP64, CCState & Info, MipsCC::SpecialCallingConvType SpecialCallingConv_ = NoSpecialCallingConv)
Definition at line 3227 of file MipsISelLowering.cpp.
References llvm::CCState::AllocateStack(), analyzeCallOperands(), and reservedArgArea().
Member Function Documentation
void MipsTargetLowering::MipsCC::analyzeCallOperands (const SmallVectorImpl< ISD::OutputArg > & Outs, bool IsVarArg, bool IsSoftFloat, const SDNode * CallNode, std::vector< ArgListEntry > & FuncArgs)
Definition at line 3238 of file MipsISelLowering.cpp.
References analyzeFormalArguments(), llvm::dbgs(), llvm::CallingConv::Fast, llvm::CCValAssign::Full, llvm::EVT::getEVTString(), I, llvm::ISD::ArgFlagsTy::isByVal(), llvm_unreachable, and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::MipsTargetLowering::getOpndList(), and MipsCC().
void MipsTargetLowering::MipsCC::analyzeCallResult (const SmallVectorImpl< ISD::InputArg > & Ins, bool IsSoftFloat, const SDNode * CallNode, const Type * RetTy) const
Definition at line 3333 of file MipsISelLowering.cpp.
References analyzeReturn().
Referenced by analyzeFormalArguments(), and llvm::MipsTargetLowering::getOpndList().
void MipsTargetLowering::MipsCC::analyzeFormalArguments (const SmallVectorImpl< ISD::InputArg > & Ins, bool IsSoftFloat, Function::const_arg_iterator FuncArg)
Definition at line 3276 of file MipsISelLowering.cpp.
References llvm::object::advance(), analyzeCallResult(), analyzeReturn(), llvm::dbgs(), llvm::CCValAssign::Full, llvm::EVT::getEVTString(), I, llvm::ISD::ArgFlagsTy::isByVal(), llvm_unreachable, originalTypeIsF128(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by analyzeCallOperands().
void MipsTargetLowering::MipsCC::analyzeReturn (const SmallVectorImpl< ISD::OutputArg > & Outs, bool IsSoftFloat, const Type * RetTy) const
Definition at line 3339 of file MipsISelLowering.cpp.
References llvm::CCState::addLoc(), llvm::MipsTargetLowering::ByValArgInfo::Address, Align, llvm::CCState::AllocateStack(), llvm::ISD::ArgFlagsTy::getByValAlign(), llvm::ISD::ArgFlagsTy::getByValSize(), llvm::CCValAssign::getMem(), llvm::MipsTargetLowering::ByValArgInfo::NumRegs, regSize(), and llvm::RoundUpToAlignment().
Referenced by analyzeCallResult(), analyzeFormalArguments(), and llvm::MipsTargetLowering::getOpndList().
byval_iterator llvm::MipsTargetLowering::MipsCC::byval_begin () const inline
Definition at line 384 of file MipsISelLowering.h.
byval_iterator llvm::MipsTargetLowering::MipsCC::byval_end () const inline
Definition at line 385 of file MipsISelLowering.h.
References Align, and llvm::CallingConv::Fast.
const CCState& llvm::MipsTargetLowering::MipsCC::getCCInfo () const inline
Definition at line 365 of file MipsISelLowering.h.
Referenced by intArgRegs().
bool llvm::MipsTargetLowering::MipsCC::hasByValArg () const inline
hasByValArg - Returns true if function has byval arguments.
Definition at line 368 of file MipsISelLowering.h.
Referenced by llvm::MipsSETargetLowering::EmitInstrWithCustomInserter().
const uint16_t * MipsTargetLowering::MipsCC::intArgRegs () const
Return pointer to array of integer argument registers.
Definition at line 3375 of file MipsISelLowering.cpp.
References llvm::ISD::ADD, addLiveIn(), llvm::MipsTargetLowering::ByValArgInfo::Address, Align, llvm::CCState::AllocateReg(), CC, CC_MipsO32_FP32(), CC_MipsO32_FP64(), llvm::MachineFrameInfo::CreateFixedObject(), llvm::MVT::f64, llvm::CallingConv::Fast, llvm::MipsTargetLowering::ByValArgInfo::FirstIdx, llvm::ISD::ArgFlagsTy::getByValAlign(), llvm::ISD::ArgFlagsTy::getByValSize(), getCCInfo(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getExtLoad(), llvm::CCState::getFirstUnallocated(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMemcpy(), llvm::CCState::getNextStackOffset(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::TargetLoweringBase::getRegClassFor(), llvm::SelectionDAG::getRegister(), llvm::SelectionDAG::getStore(), llvm::SDValue::getValue(), I, llvm::MVT::i32, llvm::MVT::i64, int, intArgRegs(), Mips16RetHelperConv, Mips64DPRegs, Mips64IntRegs, numIntArgRegs(), llvm::MipsTargetLowering::ByValArgInfo::NumRegs, llvm::ISD::OR, originalTypeIsF128(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), regSize(), reservedArgArea(), llvm::RoundUpToAlignment(), llvm::MipsFunctionInfo::setVarArgsFrameIndex(), Shift, llvm::ISD::SHL, llvm::SPII::Store, and llvm::ISD::ZEXTLOAD.
Referenced by intArgRegs().
unsigned MipsTargetLowering::MipsCC::numIntArgRegs () const
numIntArgRegs - Number of integer registers available for calls.
Definition at line 3367 of file MipsISelLowering.cpp.
References llvm::array_lengthof().
Referenced by intArgRegs().
unsigned llvm::MipsTargetLowering::MipsCC::regSize () const inline
regSize - Size (in number of bits) of integer registers.
Definition at line 371 of file MipsISelLowering.h.
Referenced by analyzeReturn(), and intArgRegs().
unsigned MipsTargetLowering::MipsCC::reservedArgArea () const
reservedArgArea - The size of the area the caller reserves for register arguments. This is 16-byte if ABI is O32.
Definition at line 3371 of file MipsISelLowering.cpp.
References llvm::CallingConv::Fast.
Referenced by intArgRegs(), and MipsCC().
The documentation for this class was generated from the following files:
MipsISelLowering.h
MipsISelLowering.cpp