LLVM: llvm::MipsInstrInfo Class Reference
LLVM API Documentation
llvm::MipsInstrInfo Class Reference abstract
#include <MipsInstrInfo.h>
Public Types
enum BranchType {
BT_None, BT_NoBranch, BT_Uncond, BT_Cond,
BT_CondUncond, BT_Indirect
}
Public Member Functions
MipsInstrInfo (MipsTargetMachine &TM, unsigned UncondBrOpc)
virtual bool AnalyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify) const
Branch Analysis.
virtual unsigned RemoveBranch (MachineBasicBlock &MBB) const
virtual unsigned InsertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, const SmallVectorImpl< MachineOperand > &Cond, DebugLoc DL) const
virtual bool ReverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const
BranchType AnalyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify, SmallVectorImpl< MachineInstr * > &BranchInstrs) const
virtual void insertNoop (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI) const
Insert nop instruction when hazard condition is found.
virtual const MipsRegisterInfo & getRegisterInfo () const =0
virtual unsigned getOppositeBranchOpc (unsigned Opc) const =0
unsigned GetInstSizeInBytes (const MachineInstr *MI) const
Return the number of bytes of code the specified instruction may be.
virtual void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const
virtual void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const
virtual void storeRegToStack (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI, int64_t Offset) const =0
virtual void loadRegFromStack (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned DestReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI, int64_t Offset) const =0
MachineInstrBuilder genInstrWithNewOpc (unsigned NewOpc, MachineBasicBlock::iterator I) const
Static Public Member Functions
static const MipsInstrInfo * create (MipsTargetMachine &TM)
Protected Member Functions
bool isZeroImm (const MachineOperand &op) const
MachineMemOperand * GetMemOperand (MachineBasicBlock &MBB, int FI, unsigned Flag) const
Protected Attributes
MipsTargetMachine & TM
unsigned UncondBrOpc
Detailed Description
Definition at line 29 of file MipsInstrInfo.h.
Member Enumeration Documentation
enum llvm::MipsInstrInfo::BranchType
Enumerator
BT_None
BT_NoBranch
BT_Uncond
BT_Cond
BT_CondUncond
BT_Indirect
Definition at line 36 of file MipsInstrInfo.h.
Constructor & Destructor Documentation
MipsInstrInfo::MipsInstrInfo (MipsTargetMachine & TM, unsigned UncondBrOpc) explicit
Definition at line 33 of file MipsInstrInfo.cpp.
Member Function Documentation
bool MipsInstrInfo::AnalyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify) const virtual
Branch Analysis.
Definition at line 86 of file MipsInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::X86ISD::BT, BT_Indirect, BT_None, llvm::BuildMI(), i, InsertBranch(), isReg(), and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by llvm::createMipsDelaySlotFillerPass(), and ReverseBranchCondition().
MipsInstrInfo::BranchType MipsInstrInfo::AnalyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify, SmallVectorImpl< MachineInstr * > & BranchInstrs) const
Definition at line 184 of file MipsInstrInfo.cpp.
References llvm::SmallVectorTemplateCommon< T >::begin(), BT_Cond, BT_CondUncond, BT_Indirect, BT_NoBranch, BT_None, BT_Uncond, llvm::MachineInstr::eraseFromParent(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), I, llvm::SmallVectorImpl< T >::insert(), llvm::MachineInstr::isIndirectBranch(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::pop_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::MachineBasicBlock::rbegin(), llvm::MachineBasicBlock::rend(), and UncondBrOpc.
const MipsInstrInfo * MipsInstrInfo::create (MipsTargetMachine & TM) static
Definition at line 37 of file MipsInstrInfo.cpp.
References llvm::createMips16InstrInfo(), llvm::createMipsSEInstrInfo(), llvm::MipsTargetMachine::getSubtargetImpl(), and llvm::MipsSubtarget::inMips16Mode().
Referenced by llvm::MipsTargetMachine::setHelperClassesMips16(), and llvm::MipsTargetMachine::setHelperClassesMipsSE().
MachineInstrBuilder MipsInstrInfo::genInstrWithNewOpc (unsigned NewOpc, MachineBasicBlock::iterator I) const
Create an instruction which has the same operands and memory operands as MI but has a new opcode.
Definition at line 285 of file MipsInstrInfo.cpp.
References llvm::MachineInstrBuilder::addOperand(), llvm::BuildMI(), I, and llvm::MachineInstrBuilder::setMemRefs().
Referenced by loadRegFromStackSlot().
unsigned MipsInstrInfo::GetInstSizeInBytes (const MachineInstr * MI) const
Return the number of bytes of code the specified instruction may be.
Definition at line 268 of file MipsInstrInfo.cpp.
References llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::TargetMachine::getMCAsmInfo(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MCInstrDesc::getSize(), llvm::MachineOperand::getSymbolName(), llvm::MachineFunction::getTarget(), and llvm::TargetOpcode::INLINEASM.
Referenced by getNonDebugInstr().
MachineMemOperand * MipsInstrInfo::GetMemOperand (MachineBasicBlock & MBB, int FI, unsigned Flag) const protected
Definition at line 57 of file MipsInstrInfo.cpp.
References Align, BB, llvm::MachineOperand::CreateImm(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getNumExplicitOperands(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), i, and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by llvm::Mips16InstrInfo::loadRegFromStack(), llvm::MipsSEInstrInfo::loadRegFromStack(), loadRegFromStackSlot(), llvm::Mips16InstrInfo::storeRegToStack(), and llvm::MipsSEInstrInfo::storeRegToStack().
virtual unsigned llvm::MipsInstrInfo::getOppositeBranchOpc (unsigned Opc) const pure virtual
Implemented in llvm::MipsSEInstrInfo, and llvm::Mips16InstrInfo.
Referenced by getNonDebugInstr(), and ReverseBranchCondition().
virtual const MipsRegisterInfo& llvm::MipsInstrInfo::getRegisterInfo () const pure virtual
getRegisterInfo - TargetInstrInfo is a superset of MRegister info. As such, whenever a client has an instance of instruction info, it should always be able to get register info as well (through this method).
Implemented in llvm::MipsSEInstrInfo, and llvm::Mips16InstrInfo.
unsigned MipsInstrInfo::InsertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, const SmallVectorImpl< MachineOperand > & Cond, DebugLoc DL) const virtual
Definition at line 117 of file MipsInstrInfo.cpp.
References llvm::MachineInstrBuilder::addMBB(), llvm::BuildMI(), llvm::SmallVectorBase::empty(), RemoveBranch(), llvm::SmallVectorTemplateCommon< T >::size(), and UncondBrOpc.
Referenced by AnalyzeBranch().
void MipsInstrInfo::insertNoop (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const virtual
Insert nop instruction when hazard condition is found.
insertNoop - If data hazard condition is found insert the target nop instruction.
Definition at line 51 of file MipsInstrInfo.cpp.
References llvm::BuildMI().
Referenced by isZeroImm().
bool MipsInstrInfo::isZeroImm (const MachineOperand & op) const protected
Definition at line 44 of file MipsInstrInfo.cpp.
References llvm::MachineOperand::getImm(), insertNoop(), and llvm::MachineOperand::isImm().
Referenced by llvm::MipsSEInstrInfo::isLoadFromStackSlot(), llvm::MipsSEInstrInfo::isStoreToStackSlot(), and loadRegFromStackSlot().
virtual void llvm::MipsInstrInfo::loadRegFromStack (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, unsigned DestReg, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI, int64_t Offset) const pure virtual
Implemented in llvm::MipsSEInstrInfo, and llvm::Mips16InstrInfo.
Referenced by loadRegFromStackSlot().
virtual void llvm::MipsInstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const inline virtual
Definition at line 94 of file MipsInstrInfo.h.
References BB, llvm::createMips16InstrInfo(), llvm::createMipsSEInstrInfo(), llvm::ISD::FrameIndex, genInstrWithNewOpc(), GetMemOperand(), I, isZeroImm(), loadRegFromStack(), llvm::A64CC::MI, storeRegToStack(), and TM.
unsigned MipsInstrInfo::RemoveBranch (MachineBasicBlock & MBB) const virtual
Definition at line 149 of file MipsInstrInfo.cpp.
References llvm::MachineBasicBlock::erase(), I, llvm::MachineBasicBlock::rbegin(), removed, llvm::MachineBasicBlock::rend(), and ReverseBranchCondition().
Referenced by InsertBranch().
bool MipsInstrInfo::ReverseBranchCondition (SmallVectorImpl< MachineOperand > & Cond) const virtual
ReverseBranchCondition - Return the inverse opcode of the specified Branch instruction.
Definition at line 175 of file MipsInstrInfo.cpp.
References AnalyzeBranch(), getOppositeBranchOpc(), and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by RemoveBranch().
virtual void llvm::MipsInstrInfo::storeRegToStack (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI, int64_t Offset) const pure virtual
Implemented in llvm::MipsSEInstrInfo, and llvm::Mips16InstrInfo.
Referenced by loadRegFromStackSlot(), and storeRegToStackSlot().
virtual void llvm::MipsInstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const inline virtual
Definition at line 86 of file MipsInstrInfo.h.
References storeRegToStack().
Member Data Documentation
MipsTargetMachine& llvm::MipsInstrInfo::TM protected
Definition at line 32 of file MipsInstrInfo.h.
Referenced by llvm::MipsSEInstrInfo::adjustStackPtr(), llvm::MipsSEInstrInfo::loadImmediate(), and loadRegFromStackSlot().
unsigned llvm::MipsInstrInfo::UncondBrOpc protected
Definition at line 33 of file MipsInstrInfo.h.
Referenced by AnalyzeBranch(), and InsertBranch().
The documentation for this class was generated from the following files:
MipsInstrInfo.h
MipsInstrInfo.cpp