LLVM: AllocaSlices::SliceBuilder Class Reference
LLVM API Documentation
AllocaSlices::SliceBuilder Class Reference
Builder for the alloca slices.
Public Member Functions
SliceBuilder (const DataLayout &DL, AllocaInst &AI, AllocaSlices &S)
Public Member Functions inherited from llvm::PtrUseVisitor< SliceBuilder >
PtrUseVisitor (const DataLayout &DL)
PtrInfo visitPtr (Instruction &I)
Recursively visit the uses of the given pointer.
Friends
class PtrUseVisitor< SliceBuilder >
class InstVisitor< SliceBuilder >
Additional Inherited Members
Protected Member Functions inherited from llvm::PtrUseVisitor< SliceBuilder >
void visitStoreInst (StoreInst &SI)
void visitBitCastInst (BitCastInst &BC)
void visitPtrToIntInst (PtrToIntInst &I)
void visitGetElementPtrInst (GetElementPtrInst &GEPI)
void visitDbgInfoIntrinsic (DbgInfoIntrinsic &I)
void visitMemIntrinsic (MemIntrinsic &I)
void visitIntrinsicInst (IntrinsicInst &II)
void visitCallSite (CallSite CS)
Protected Member Functions inherited from llvm::InstVisitor< SliceBuilder >
void visit (Iterator Start, Iterator End)
void visit (Module &M)
void visit (Function &F)
void visit (BasicBlock &BB)
void visit (Module *M)
void visit (Function *F)
void visit (BasicBlock *BB)
void visit (Instruction *I)
void visit (Instruction &I)
void visitModule (Module &M)
void visitFunction (Function &F)
void visitBasicBlock (BasicBlock &BB)
void visitReturnInst (ReturnInst &I)
void visitBranchInst (BranchInst &I)
void visitSwitchInst (SwitchInst &I)
void visitIndirectBrInst (IndirectBrInst &I)
void visitResumeInst (ResumeInst &I)
void visitUnreachableInst (UnreachableInst &I)
void visitICmpInst (ICmpInst &I)
void visitFCmpInst (FCmpInst &I)
void visitAllocaInst (AllocaInst &I)
void visitLoadInst (LoadInst &I)
void visitStoreInst (StoreInst &I)
void visitAtomicCmpXchgInst (AtomicCmpXchgInst &I)
void visitAtomicRMWInst (AtomicRMWInst &I)
void visitFenceInst (FenceInst &I)
void visitGetElementPtrInst (GetElementPtrInst &I)
void visitPHINode (PHINode &I)
void visitTruncInst (TruncInst &I)
void visitZExtInst (ZExtInst &I)
void visitSExtInst (SExtInst &I)
void visitFPTruncInst (FPTruncInst &I)
void visitFPExtInst (FPExtInst &I)
void visitFPToUIInst (FPToUIInst &I)
void visitFPToSIInst (FPToSIInst &I)
void visitUIToFPInst (UIToFPInst &I)
void visitSIToFPInst (SIToFPInst &I)
void visitPtrToIntInst (PtrToIntInst &I)
void visitIntToPtrInst (IntToPtrInst &I)
void visitBitCastInst (BitCastInst &I)
void visitAddrSpaceCastInst (AddrSpaceCastInst &I)
void visitSelectInst (SelectInst &I)
void visitVAArgInst (VAArgInst &I)
void visitExtractElementInst (ExtractElementInst &I)
void visitInsertElementInst (InsertElementInst &I)
void visitShuffleVectorInst (ShuffleVectorInst &I)
void visitExtractValueInst (ExtractValueInst &I)
void visitInsertValueInst (InsertValueInst &I)
void visitLandingPadInst (LandingPadInst &I)
void visitDbgDeclareInst (DbgDeclareInst &I)
void visitDbgValueInst (DbgValueInst &I)
void visitDbgInfoIntrinsic (DbgInfoIntrinsic &I)
void visitMemSetInst (MemSetInst &I)
void visitMemCpyInst (MemCpyInst &I)
void visitMemMoveInst (MemMoveInst &I)
void visitMemTransferInst (MemTransferInst &I)
void visitMemIntrinsic (MemIntrinsic &I)
void visitVAStartInst (VAStartInst &I)
void visitVAEndInst (VAEndInst &I)
void visitVACopyInst (VACopyInst &I)
void visitIntrinsicInst (IntrinsicInst &I)
void visitCallInst (CallInst &I)
void visitInvokeInst (InvokeInst &I)
void visitCastInst (CastInst &I)
void visitBinaryOperator (BinaryOperator &I)
void visitCmpInst (CmpInst &I)
void visitTerminatorInst (TerminatorInst &I)
void visitUnaryInstruction (UnaryInstruction &I)
void visitCallSite (CallSite CS)
void visitInstruction (Instruction &I)
Protected Member Functions inherited from llvm::detail::PtrUseVisitorBase
PtrUseVisitorBase (const DataLayout &DL)
void enqueueUsers (Instruction &I)
Enqueue the users of this instruction in the visit worklist.
bool adjustOffsetForGEP (GetElementPtrInst &GEPI)
Walk the operands of a GEP and adjust the offset as appropriate.
Protected Attributes inherited from llvm::detail::PtrUseVisitorBase
const DataLayout & DL
PtrInfo PI
The info collected about the pointer being visited thus far.
SmallVector< UseToVisit, 8 > Worklist
The worklist of to-visit uses.
SmallPtrSet< Use *, 8 > VisitedUses
A set of visited uses to break cycles in unreachable code.
Use * U
The use currently being visited.
bool IsOffsetKnown
True if we have a known constant offset for the use currently being visited.
APInt Offset
The constant offset of the use if that is known.
Detailed Description
Builder for the alloca slices.
This class builds a set of alloca slices by recursively visiting the uses of an alloca and making a slice for each load and store at each offset.
Definition at line 313 of file SROA.cpp.
Constructor & Destructor Documentation
AllocaSlices::SliceBuilder::SliceBuilder (const DataLayout & DL, AllocaInst & AI, AllocaSlices & S) inline
Definition at line 328 of file SROA.cpp.
References B, llvm::sys::path::begin(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::ConvertDebugDeclareToDebugValue(), llvm::dbgs(), DEBUG, llvm::dump(), llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::sys::path::end(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::Instruction::eraseFromParent(), F(), foldSelectInst(), llvm::detail::PtrUseVisitorBase::PtrInfo::getAbortingInst(), llvm::CallInst::getArgOperand(), llvm::Value::getContext(), llvm::Instruction::getDebugLoc(), llvm::detail::PtrUseVisitorBase::PtrInfo::getEscapingInst(), llvm::MDNode::getIfExists(), llvm::IntrinsicInst::getIntrinsicID(), llvm::MemIntrinsic::getLength(), llvm::ConstantInt::getLimitedValue(), llvm::APInt::getLimitedValue(), llvm::User::getOperand(), llvm::PassRegistry::getPassRegistry(), getPointerOperand(), llvm::MemIntrinsic::getRawDest(), llvm::MemTransferInst::getRawSource(), llvm::Value::getType(), llvm::ConstantInt::getValue(), llvm::StoreInst::getValueOperand(), llvm::DbgValueInst::getVariable(), llvm::APInt::getZExtValue(), I, llvm::initializeSROAPass(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::insert(), llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::DIBuilder::insertDbgValueIntrinsic(), llvm::detail::PtrUseVisitorBase::PtrInfo::isAborted(), llvm::detail::PtrUseVisitorBase::PtrInfo::isEscaped(), llvm::Type::isIntegerTy(), llvm::APInt::isNegative(), llvm::LoadInst::isSimple(), llvm::StoreInst::isSimple(), llvm::Type::isSingleValueType(), llvm::MemIntrinsic::isVolatile(), llvm::LoadInst::isVolatile(), llvm::StoreInst::isVolatile(), llvm::Intrinsic::lifetime_end, llvm::Intrinsic::lifetime_start, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::LoadAndStorePromoter::run(), S, llvm::Instruction::setDebugLoc(), llvm::tie(), llvm::APInt::uge(), llvm::APInt::ugt(), llvm::Value::use_begin(), llvm::Value::use_empty(), llvm::Value::use_end(), and llvm::PtrUseVisitor< DerivedT >::visitPtr().
Friends And Related Function Documentation
friend class InstVisitor< SliceBuilder > friend
Definition at line 315 of file SROA.cpp.
friend class PtrUseVisitor< SliceBuilder > friend
Definition at line 314 of file SROA.cpp.
The documentation for this class was generated from the following file:
SROA.cpp