LLVM: llvm::TGLexer Class Reference
LLVM API Documentation
llvm::TGLexer Class Reference
TGLexer - TableGen Lexer class.
#include <TGLexer.h>
Public Types
typedef std::map< std::string, SMLoc > DependenciesMapTy
Public Member Functions
TGLexer (SourceMgr &SrcMgr)
~TGLexer ()
tgtok::TokKind Lex ()
const DependenciesMapTy & getDependencies () const
tgtok::TokKind getCode () const
const std::string & getCurStrVal () const
int64_t getCurIntVal () const
SMLoc getLoc () const
Detailed Description
TGLexer - TableGen Lexer class.
Definition at line 62 of file TGLexer.h.
Member Typedef Documentation
typedef std::map<std::string, SMLoc> llvm::TGLexer::DependenciesMapTy
Definition at line 79 of file TGLexer.h.
Constructor & Destructor Documentation
TGLexer::TGLexer (SourceMgr & SrcMgr)
Definition at line 29 of file TGLexer.cpp.
References llvm::MemoryBuffer::getBufferStart(), and llvm::SourceMgr::getMemoryBuffer().
llvm::TGLexer::~TGLexer () inline
Definition at line 86 of file TGLexer.h.
Member Function Documentation
tgtok::TokKind llvm::TGLexer::getCode () const inline
Definition at line 96 of file TGLexer.h.
int64_t llvm::TGLexer::getCurIntVal () const inline
Definition at line 104 of file TGLexer.h.
References llvm::tgtok::IntVal.
const std::string& llvm::TGLexer::getCurStrVal () const inline
Definition at line 98 of file TGLexer.h.
References llvm::tgtok::CodeFragment, llvm::tgtok::Id, llvm::tgtok::StrVal, and llvm::tgtok::VarName.
const DependenciesMapTy& llvm::TGLexer::getDependencies () const inline
Definition at line 92 of file TGLexer.h.
Referenced by llvm::TGParser::getDependencies().
SMLoc TGLexer::getLoc () const
Definition at line 36 of file TGLexer.cpp.
References llvm::SourceMgr::AddIncludeFile(), llvm::StringRef::begin(), llvm::tgtok::Bit, llvm::tgtok::Bits, llvm::StringSwitch< T, R >::Case(), llvm::tgtok::Class, llvm::tgtok::Code, llvm::tgtok::CodeFragment, llvm::tgtok::colon, llvm::tgtok::comma, llvm::tgtok::Dag, llvm::tgtok::Def, llvm::StringSwitch< T, R >::Default(), llvm::tgtok::Defm, llvm::SourceMgr::DK_Note, llvm::StringRef::end(), llvm::tgtok::Eof, llvm::tgtok::equal, llvm::tgtok::Error, llvm::tgtok::Field, llvm::SourceMgr::FindBufferContainingLoc(), llvm::tgtok::Foreach, llvm::MemoryBuffer::getBufferEnd(), llvm::MemoryBuffer::getBufferStart(), llvm::SMLoc::getFromPointer(), llvm::SourceMgr::getMemoryBuffer(), llvm::SourceMgr::getParentIncludeLoc(), llvm::SMLoc::getPointer(), llvm::tgtok::greater, i, llvm::tgtok::Id, llvm::tgtok::In, llvm::tgtok::Int, llvm::tgtok::IntVal, llvm::LibFunc::isdigit, llvm::tgtok::l_brace, llvm::tgtok::l_paren, llvm::tgtok::l_square, llvm::tgtok::less, llvm::tgtok::Let, Lex(), llvm::tgtok::List, llvm::tgtok::minus, llvm::tgtok::MultiClass, llvm::tgtok::paste, llvm::tgtok::period, llvm::tgtok::plus, llvm::PrintError(), llvm::SourceMgr::PrintMessage(), llvm::tgtok::question, llvm::tgtok::r_brace, llvm::tgtok::r_paren, llvm::tgtok::r_square, llvm::tgtok::semi, llvm::tgtok::String, llvm::LibFunc::strtoll, llvm::LibFunc::strtoull, llvm::tgtok::StrVal, llvm::tgtok::VarName, llvm::tgtok::XADD, llvm::tgtok::XCast, llvm::tgtok::XConcat, llvm::tgtok::XEmpty, llvm::tgtok::XEq, llvm::tgtok::XForEach, llvm::tgtok::XHead, llvm::tgtok::XIf, llvm::tgtok::XSHL, llvm::tgtok::XSRA, llvm::tgtok::XSRL, llvm::tgtok::XStrConcat, llvm::tgtok::XSubst, and llvm::tgtok::XTail.
Referenced by llvm::TGParser::TokError().
tgtok::TokKind llvm::TGLexer::Lex () inline
Definition at line 88 of file TGLexer.h.
Referenced by getLoc().
The documentation for this class was generated from the following files:
TGLexer.h
TGLexer.cpp