LLVM: llvm::MipsInstPrinter Class Reference
LLVM API Documentation
llvm::MipsInstPrinter Class Reference
#include <MipsInstPrinter.h>
Public Member Functions
MipsInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printInstruction (const MCInst *MI, raw_ostream &O)
virtual void printRegName (raw_ostream &OS, unsigned RegNo) const
printRegName - Print the assembler register name.
virtual void printInst (const MCInst *MI, raw_ostream &O, StringRef Annot)
bool printAliasInstr (const MCInst *MI, raw_ostream &OS)
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
void setCommentStream (raw_ostream &OS)
setCommentStream - Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
uint64_t getAvailableFeatures () const
void setAvailableFeatures (uint64_t Value)
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
StringRef markup (StringRef a, StringRef b) const
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
HexStyle::Style getPrintHexStyleHex () const
void setPrintImmHex (HexStyle::Style Value)
format_object1< int64_t > formatImm (const int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object1< int64_t > formatDec (const int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object1< int64_t > formatHex (const int64_t Value) const
format_object1< uint64_t > formatHex (const uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
uint64_t AvailableFeatures
The current set of available features.
bool UseMarkup
True if we are printing marked up assembly.
bool PrintImmHex
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle
Which style to use for printing hexadecimal values.
Detailed Description
Definition at line 78 of file MipsInstPrinter.h.
Constructor & Destructor Documentation
llvm::MipsInstPrinter::MipsInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) inline
Definition at line 80 of file MipsInstPrinter.h.
References llvm::A64CC::MI.
Member Function Documentation
static const char* llvm::MipsInstPrinter::getRegisterName (unsigned RegNo) static
Referenced by llvm::MipsAsmPrinter::emitFrameDirective(), llvm::MipsAsmPrinter::PrintAsmMemoryOperand(), llvm::MipsAsmPrinter::PrintAsmOperand(), llvm::MipsAsmPrinter::printOperand(), and printRegName().
bool llvm::MipsInstPrinter::printAliasInstr (const MCInst * MI, raw_ostream & OS)
Referenced by printInst().
void MipsInstPrinter::printInst (const MCInst * MI, raw_ostream & OS, StringRef Annot) virtual
printInst - Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 77 of file MipsInstPrinter.cpp.
References llvm::MCInst::getOpcode(), printAliasInstr(), llvm::MCInstPrinter::printAnnotation(), and printInstruction().
void llvm::MipsInstPrinter::printInstruction (const MCInst * MI, raw_ostream & O)
Referenced by printInst().
void MipsInstPrinter::printRegName (raw_ostream & OS, unsigned RegNo) const virtual
printRegName - Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 73 of file MipsInstPrinter.cpp.
References getRegisterName(), and llvm::StringRef::lower().
Referenced by printExpr().
The documentation for this class was generated from the following files:
MipsInstPrinter.h
MipsInstPrinter.cpp