LLVM: llvm::DIEEntry Class Reference
LLVM API Documentation
llvm::DIEEntry Class Reference
#include <DIE.h>
Public Member Functions
DIEEntry (DIE *E)
DIE * getEntry () const
virtual void EmitValue (AsmPrinter *AP, dwarf::Form Form) const
virtual unsigned SizeOf (AsmPrinter *AP, dwarf::Form Form) const
virtual void print (raw_ostream &O) const
Public Member Functions inherited from llvm::DIEValue
DIEValue (unsigned T)
virtual ~DIEValue ()
unsigned getType () const
void dump () const
Static Public Member Functions
static unsigned getRefAddrSize (AsmPrinter *AP)
Returns size of a ref_addr entry.
static bool classof (const DIEValue *E)
Additional Inherited Members
Public Types inherited from llvm::DIEValue
enum {
isInteger, isString, isExpr, isLabel,
isDelta, isEntry, isBlock
}
Protected Attributes inherited from llvm::DIEValue
unsigned Type
Detailed Description
DIEEntry - A pointer to another debug information entry. An instance of this class can also be used as a proxy for a debug information entry not yet defined (ie. types.)
Definition at line 383 of file DIE.h.
Constructor & Destructor Documentation
llvm::DIEEntry::DIEEntry (DIE * E) inline explicit
Definition at line 386 of file DIE.h.
Member Function Documentation
static bool llvm::DIEEntry::classof (const DIEValue * E) inline static
Definition at line 407 of file DIE.h.
References llvm::DIEValue::getType().
void DIEEntry::EmitValue (AsmPrinter * AP, dwarf::Form Form) const virtual
EmitValue - Emit debug information entry offset.
Implements llvm::DIEValue.
Definition at line 380 of file DIE.cpp.
References llvm::AsmPrinter::EmitInt32().
DIE* llvm::DIEEntry::getEntry () const inline
Definition at line 390 of file DIE.h.
Referenced by llvm::CompileUnit::addDIEEntry(), and llvm::DwarfDebug::emitDIE().
unsigned DIEEntry::getRefAddrSize (AsmPrinter * AP) static
Returns size of a ref_addr entry.
Definition at line 384 of file DIE.cpp.
References llvm::AsmPrinter::getDataLayout(), llvm::AsmPrinter::getDwarfDebug(), llvm::DwarfDebug::getDwarfVersion(), and llvm::DataLayout::getPointerSize().
Referenced by llvm::DwarfDebug::emitDIE().
void DIEEntry::print (raw_ostream & O) const virtual
Implements llvm::DIEValue.
Definition at line 395 of file DIE.cpp.
References llvm::format().
virtual unsigned llvm::DIEEntry::SizeOf (AsmPrinter * AP, dwarf::Form Form) const inline virtual
SizeOf - Determine size of debug information entry in bytes.
Implements llvm::DIEValue.
Definition at line 398 of file DIE.h.
The documentation for this class was generated from the following files:
DIE.h
DIE.cpp