LLVM: llvm::RecordRecTy Class Reference
LLVM API Documentation
llvm::RecordRecTy Class Reference
#include <Record.h>
Public Member Functions
Record * getRecord () const
virtual Init * convertValue (UnsetInit *UI)
virtual Init * convertValue (BitInit *BI)
virtual Init * convertValue (BitsInit *BI)
virtual Init * convertValue (IntInit *II)
virtual Init * convertValue (StringInit *SI)
virtual Init * convertValue (ListInit *LI)
virtual Init * convertValue (VarBitInit *VB)
virtual Init * convertValue (UnOpInit *UI)
virtual Init * convertValue (BinOpInit *UI)
virtual Init * convertValue (TernOpInit *UI)
virtual Init * convertValue (DefInit *DI)
virtual Init * convertValue (DagInit *DI)
virtual Init * convertValue (TypedInit *VI)
virtual Init * convertValue (VarInit *VI)
virtual Init * convertValue (FieldInit *FI)
virtual std::string getAsString () const
virtual bool typeIsConvertibleTo (const RecTy *RHS) const
virtual bool baseClassOf (const RecTy *) const
Public Member Functions inherited from llvm::RecTy
RecTyKind getRecTyKind () const
RecTy (RecTyKind K)
virtual ~RecTy ()
void print (raw_ostream &OS) const
void dump () const
ListRecTy * getListTy ()
getListTy - Returns the type representing list<this>.
Static Public Member Functions
static bool classof (const RecTy *RT)
static RecordRecTy * get (Record *R)
Friends
class Record
Additional Inherited Members
Public Types inherited from llvm::RecTy
enum RecTyKind {
BitRecTyKind, BitsRecTyKind, IntRecTyKind, StringRecTyKind,
ListRecTyKind, DagRecTyKind, RecordRecTyKind
}
Subclass discriminator (for dyn_cast<> et al.)
Detailed Description
RecordRecTy - '[classname]' - Represent an instance of a class, such as: (R32 X = EAX).
Definition at line 369 of file Record.h.
Member Function Documentation
bool RecordRecTy::baseClassOf (const RecTy * RHS) const virtual
Reimplemented from llvm::RecTy.
Definition at line 358 of file Record.cpp.
References llvm::dyn_cast(), getRecord(), i, llvm::Record::isSubClassOf(), and llvm::PPCISD::SC.
static bool llvm::RecordRecTy::classof (const RecTy * RT) inline static
Definition at line 374 of file Record.h.
References llvm::RecTy::getRecTyKind(), and llvm::RecTy::RecordRecTyKind.
virtual Init* llvm::RecordRecTy::convertValue (UnsetInit * UI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 382 of file Record.h.
virtual Init* llvm::RecordRecTy::convertValue (BitInit * BI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 383 of file Record.h.
virtual Init* llvm::RecordRecTy::convertValue (BitsInit * BI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 384 of file Record.h.
virtual Init* llvm::RecordRecTy::convertValue (IntInit * II) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 385 of file Record.h.
virtual Init* llvm::RecordRecTy::convertValue (StringInit * SI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 386 of file Record.h.
virtual Init* llvm::RecordRecTy::convertValue (ListInit * LI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 387 of file Record.h.
virtual Init* llvm::RecordRecTy::convertValue (VarBitInit * VB) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 388 of file Record.h.
virtual Init* llvm::RecordRecTy::convertValue (UnOpInit * UI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 389 of file Record.h.
References llvm::RecTy::convertValue().
virtual Init* llvm::RecordRecTy::convertValue (BinOpInit * UI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 390 of file Record.h.
References llvm::RecTy::convertValue().
virtual Init* llvm::RecordRecTy::convertValue (TernOpInit * UI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 391 of file Record.h.
References llvm::RecTy::convertValue().
Init * RecordRecTy::convertValue (DefInit * DI) virtual
Reimplemented from llvm::RecTy.
Definition at line 342 of file Record.cpp.
References llvm::DefInit::getDef(), and llvm::Record::isSubClassOf().
virtual Init* llvm::RecordRecTy::convertValue (DagInit * DI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 393 of file Record.h.
References llvm::RecTy::convertValue().
Init * RecordRecTy::convertValue (TypedInit * VI) virtual
Reimplemented from llvm::RecTy.
Definition at line 349 of file Record.cpp.
References llvm::TypedInit::getType().
virtual Init* llvm::RecordRecTy::convertValue (VarInit * VI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 395 of file Record.h.
References llvm::RecTy::convertValue().
virtual Init* llvm::RecordRecTy::convertValue (FieldInit * FI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 396 of file Record.h.
References llvm::RecTy::convertValue(), and llvm::RecTy::getAsString().
RecordRecTy * RecordRecTy::get (Record * R) static
Definition at line 334 of file Record.cpp.
References llvm::dyn_cast(), llvm::Record::getDefInit(), and llvm::TypedInit::getType().
Referenced by GetNewAnonymousName(), and llvm::resolveTypes().
std::string RecordRecTy::getAsString () const virtual
Implements llvm::RecTy.
Definition at line 338 of file Record.cpp.
Record* llvm::RecordRecTy::getRecord () const inline
Definition at line 380 of file Record.h.
Referenced by baseClassOf().
virtual bool llvm::RecordRecTy::typeIsConvertibleTo (const RecTy * RHS) const inline virtual
typeIsConvertibleTo - Return true if all values of 'this' type can be converted to the specified type.
Implements llvm::RecTy.
Definition at line 400 of file Record.h.
References llvm::RecTy::baseClassOf(), llvm::resolveTypes(), and T1.
Friends And Related Function Documentation
friend class Record friend
Definition at line 372 of file Record.h.
The documentation for this class was generated from the following files:
Record.h
Record.cpp