LLVM: llvm::SwitchInst Class Reference
LLVM API Documentation
llvm::SwitchInst Class Reference
#include <Instructions.h>
Classes
class CaseIt
class CaseIteratorT
Public Types
typedef CaseIteratorT< const SwitchInst, const ConstantInt, const BasicBlock > ConstCaseIt
Public Types inherited from llvm::Instruction
enum OperationEquivalenceFlags { CompareIgnoringAlignment = 1<<0, CompareUsingScalarTypes = 1<<1 }
enum TermOps
enum BinaryOps
enum MemoryOps
enum CastOps
enum OtherOps
Public Types inherited from llvm::User
typedef Use * op_iterator
typedef const Use * const_op_iterator
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal, BasicBlockVal, FunctionVal, GlobalAliasVal,
GlobalVariableVal, UndefValueVal, BlockAddressVal, ConstantExprVal,
ConstantAggregateZeroVal, ConstantDataArrayVal, ConstantDataVectorVal, ConstantIntVal,
ConstantFPVal, ConstantArrayVal, ConstantStructVal, ConstantVectorVal,
ConstantPointerNullVal, MDNodeVal, MDStringVal, InlineAsmVal,
PseudoSourceValueVal, FixedStackPseudoSourceValueVal, InstructionVal, ConstantFirstVal = FunctionVal,
ConstantLastVal = ConstantPointerNullVal
}
typedef value_use_iterator< User > use_iterator
typedef value_use_iterator< const User > const_use_iterator
Public Member Functions
~SwitchInst ()
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Provide fast operand accessors.
Value * getCondition () const
void setCondition (Value *V)
BasicBlock * getDefaultDest () const
void setDefaultDest (BasicBlock *DefaultCase)
unsigned getNumCases () const
CaseIt case_begin ()
ConstCaseIt case_begin () const
CaseIt case_end ()
ConstCaseIt case_end () const
CaseIt case_default ()
ConstCaseIt case_default () const
CaseIt findCaseValue (const ConstantInt *C)
ConstCaseIt findCaseValue (const ConstantInt *C) const
ConstantInt * findCaseDest (BasicBlock *BB)
void addCase (ConstantInt *OnVal, BasicBlock *Dest)
void removeCase (CaseIt i)
unsigned getNumSuccessors () const
BasicBlock * getSuccessor (unsigned idx) const
void setSuccessor (unsigned idx, BasicBlock *NewSucc)
Public Member Functions inherited from llvm::TerminatorInst
unsigned getNumSuccessors () const
BasicBlock * getSuccessor (unsigned idx) const
void setSuccessor (unsigned idx, BasicBlock *B)
Public Member Functions inherited from llvm::Instruction
~Instruction ()
Instruction * use_back ()
const Instruction * use_back () const
const BasicBlock * getParent () const
BasicBlock * getParent ()
void removeFromParent ()
void eraseFromParent ()
void insertBefore (Instruction *InsertPos)
void insertAfter (Instruction *InsertPos)
void moveBefore (Instruction *MovePos)
unsigned getOpcode () const
getOpcode() returns a member of one of the enums like Instruction::Add.
const char * getOpcodeName () const
bool isTerminator () const
bool isBinaryOp () const
bool isShift ()
bool isCast () const
bool isLogicalShift () const
bool isArithmeticShift () const
isArithmeticShift - Return true if this is an arithmetic shift right.
bool hasMetadata () const
bool hasMetadataOtherThanDebugLoc () const
MDNode * getMetadata (unsigned KindID) const
MDNode * getMetadata (StringRef Kind) const
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
void getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
void setMetadata (unsigned KindID, MDNode *Node)
void setMetadata (StringRef Kind, MDNode *Node)
void setDebugLoc (const DebugLoc &Loc)
setDebugLoc - Set the debug location information for this instruction.
const DebugLoc & getDebugLoc () const
getDebugLoc - Return the debug location for this node as a DebugLoc.
void setHasUnsafeAlgebra (bool B)
void setHasNoNaNs (bool B)
void setHasNoInfs (bool B)
void setHasNoSignedZeros (bool B)
void setHasAllowReciprocal (bool B)
void setFastMathFlags (FastMathFlags FMF)
bool hasUnsafeAlgebra () const
Determine whether the unsafe-algebra flag is set.
bool hasNoNaNs () const
Determine whether the no-NaNs flag is set.
bool hasNoInfs () const
Determine whether the no-infs flag is set.
bool hasNoSignedZeros () const
Determine whether the no-signed-zeros flag is set.
bool hasAllowReciprocal () const
Determine whether the allow-reciprocal flag is set.
FastMathFlags getFastMathFlags () const
void copyFastMathFlags (const Instruction *I)
Copy I's fast-math flags.
bool isAssociative () const
bool isCommutative () const
bool isIdempotent () const
bool isNilpotent () const
bool mayWriteToMemory () const
bool mayReadFromMemory () const
bool mayReadOrWriteMemory () const
bool mayThrow () const
bool mayReturn () const
bool mayHaveSideEffects () const
Instruction * clone () const
bool isIdenticalTo (const Instruction *I) const
bool isIdenticalToWhenDefined (const Instruction *I) const
bool isSameOperationAs (const Instruction *I, unsigned flags=0) const
Determine if one instruction is the same operation as another.
bool isUsedOutsideOfBlock (const BasicBlock *BB) const
Public Member Functions inherited from llvm::User
~User ()
void operator delete (void *Usr)
operator delete - free memory allocated for User and Use objects
void operator delete (void *, unsigned)
placement delete - required by std, but never called.
void operator delete (void *, unsigned, bool)
placement delete - required by std, but never called.
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
void dropAllReferences ()
void replaceUsesOfWith (Value *From, Value *To)
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
dump - Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O, AssemblyAnnotationWriter *AAW=0) const
Type * getType () const
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
void setName (const Twine &Name)
void takeName (Value *V)
void replaceAllUsesWith (Value *V)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
User * use_back ()
const User * use_back () const
bool hasOneUse () const
bool hasNUses (unsigned N) const
bool hasNUsesOrMore (unsigned N) const
bool isUsedInBasicBlock (const BasicBlock *BB) const
unsigned getNumUses () const
void addUse (Use &U)
unsigned getValueID () const
unsigned getRawSubclassOptionalData () const
void clearSubclassOptionalData ()
bool hasSameSubclassOptionalData (const Value *V) const
void intersectOptionalDataWith (const Value *V)
bool hasValueHandle () const
Value * stripPointerCasts ()
Strips off any unneeded pointer casts, all-zero GEPs and aliases from the specified value, returning the original uncasted value.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strips off any unneeded pointer casts and all-zero GEPs from the specified value, returning the original uncasted value.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strips off unneeded pointer casts and all-constant GEPs from the specified value, returning the original pointer value.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Strips like stripInBoundsConstantOffsets but also accumulates the constant offset stripped.
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strips off unneeded pointer casts and any in-bounds offsets from the specified value, returning the original pointer value.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer () const
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Public Member Functions inherited from llvm::ilist_node< Instruction >
Instruction * getPrevNode ()
Get the previous node, or 0 for the list head.
const Instruction * getPrevNode () const
Get the previous node, or 0 for the list head.
Instruction * getNextNode ()
Get the next node, or 0 for the list tail.
const Instruction * getNextNode () const
Get the next node, or 0 for the list tail.
Static Public Member Functions
static SwitchInst * Create (Value *Value, BasicBlock *Default, unsigned NumCases, Instruction *InsertBefore=0)
static SwitchInst * Create (Value *Value, BasicBlock *Default, unsigned NumCases, BasicBlock *InsertAtEnd)
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::TerminatorInst
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Instruction
static const char * getOpcodeName (unsigned OpCode)
static bool isTerminator (unsigned OpCode)
static bool isBinaryOp (unsigned Opcode)
static bool isShift (unsigned Opcode)
Determine if the Opcode is one of the shift instructions.
static bool isCast (unsigned OpCode)
Determine if the OpCode is one of the CastInst instructions.
static bool isAssociative (unsigned op)
static bool isCommutative (unsigned op)
static bool isIdempotent (unsigned op)
static bool isNilpotent (unsigned op)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Static Public Attributes
static const unsigned DefaultPseudoIndex = static_cast<unsigned>(~0L-1)
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
Protected Member Functions
virtual SwitchInst * clone_impl () const
Protected Member Functions inherited from llvm::TerminatorInst
TerminatorInst (Type *Ty, Instruction::TermOps iType, Use *Ops, unsigned NumOps, Instruction *InsertBefore=0)
TerminatorInst (Type *Ty, Instruction::TermOps iType, Use *Ops, unsigned NumOps, BasicBlock *InsertAtEnd)
~TerminatorInst ()
Protected Member Functions inherited from llvm::Instruction
void setInstructionSubclassData (unsigned short D)
unsigned getSubclassDataFromInstruction () const
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, Instruction *InsertBefore=0)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, BasicBlock *InsertAtEnd)
Protected Member Functions inherited from llvm::User
void * operator new (size_t s, unsigned Us)
User (Type *ty, unsigned vty, Use *OpList, unsigned NumOps)
Use * allocHungoffUses (unsigned) const
void dropHungoffUses ()
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
virtual void printCustom (raw_ostream &O) const
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Member Functions inherited from llvm::ilist_node< Instruction >
ilist_node ()
Additional Inherited Members
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::User
Use * OperandList
unsigned NumOperands
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Detailed Description
SwitchInst - Multiway switch
Definition at line 2449 of file Instructions.h.
Member Typedef Documentation
typedef CaseIteratorT<const SwitchInst, const ConstantInt, const BasicBlock> llvm::SwitchInst::ConstCaseIt
Definition at line 2572 of file Instructions.h.
Constructor & Destructor Documentation
SwitchInst::~SwitchInst ()
Definition at line 3337 of file Instructions.cpp.
References llvm::User::dropHungoffUses().
Member Function Documentation
void SwitchInst::addCase (ConstantInt * OnVal, BasicBlock * Dest)
addCase - Add an entry to the switch instruction... Note: This action invalidates case_end(). Old case_end() iterator will point to the added case.
addCase - Add an entry to the switch instruction...
Definition at line 3344 of file Instructions.cpp.
References llvm::User::NumOperands, llvm::SwitchInst::CaseIt::setSuccessor(), and llvm::SwitchInst::CaseIt::setValue().
Referenced by FindPhiPredForUseInBlock(), FitWeights(), FunctionNumber(), llvm::BitcodeReader::ParseTriple(), SimplifyBranchOnICmpChain(), and TryToSimplifyUncondBranchWithICmpInIt().
CaseIt llvm::SwitchInst::case_begin () inline
Returns a read/write iterator that points to the first case in SwitchInst.
Definition at line 2629 of file Instructions.h.
Referenced by ComputeRange(), ConvertAtomicSynchScope(), llvm::createCorrelatedValuePropagationPass(), EliminateDeadSwitchCases(), FindLIVLoopCondition(), ForwardSwitchConditionToPHI(), isTrivialLoopExitBlock(), operator<<(), llvm::AssemblyWriter::printInstruction(), SwitchToLookupTable(), TurnSwitchRangeIntoICmp(), ValuesOverlap(), llvm::Interpreter::visitSwitchInst(), llvm::InstCombiner::visitSwitchInst(), and WriteInstruction().
ConstCaseIt llvm::SwitchInst::case_begin () const inline
Returns a read-only iterator that points to the first case in the SwitchInst.
Definition at line 2634 of file Instructions.h.
CaseIt llvm::SwitchInst::case_default () inline
Returns an iterator that points to the default case. Note: this iterator allows to resolve successor only. Attempt to resolve case value causes an assertion. Also note, that increment and decrement also causes an assertion and makes iterator invalid.
Definition at line 2653 of file Instructions.h.
Referenced by EliminateDeadSwitchCases(), ReplaceUsesOfWith(), and TryToSimplifyUncondBranchWithICmpInIt().
ConstCaseIt llvm::SwitchInst::case_default () const inline
Definition at line 2656 of file Instructions.h.
CaseIt llvm::SwitchInst::case_end () inline
Returns a read/write iterator that points one past the last in the SwitchInst.
Definition at line 2640 of file Instructions.h.
Referenced by ComputeRange(), ConvertAtomicSynchScope(), llvm::createCorrelatedValuePropagationPass(), EliminateDeadSwitchCases(), FindLIVLoopCondition(), ForwardSwitchConditionToPHI(), isTrivialLoopExitBlock(), operator<<(), llvm::AssemblyWriter::printInstruction(), SwitchToLookupTable(), TurnSwitchRangeIntoICmp(), ValuesOverlap(), llvm::Interpreter::visitSwitchInst(), llvm::InstCombiner::visitSwitchInst(), and WriteInstruction().
ConstCaseIt llvm::SwitchInst::case_end () const inline
Returns a read-only iterator that points one past the last in the SwitchInst.
Definition at line 2645 of file Instructions.h.
static bool llvm::SwitchInst::classof (const Instruction * I) inline static
Definition at line 2717 of file Instructions.h.
References llvm::Instruction::getOpcode().
static bool llvm::SwitchInst::classof (const Value * V) inline static
Definition at line 2720 of file Instructions.h.
References llvm::AllocaInst::classof().
SwitchInst * SwitchInst::clone_impl () const protected virtual
Implements llvm::TerminatorInst.
Definition at line 3664 of file Instructions.cpp.
static SwitchInst* llvm::SwitchInst::Create (Value * Value, BasicBlock * Default, unsigned NumCases, Instruction * InsertBefore = 0) inline static
Definition at line 2595 of file Instructions.h.
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateSwitch(), FindPhiPredForUseInBlock(), FunctionNumber(), MarkBlocksLiveIn(), and llvm::BitcodeReader::ParseTriple().
static SwitchInst* llvm::SwitchInst::Create (Value * Value, BasicBlock * Default, unsigned NumCases, BasicBlock * InsertAtEnd) inline static
Definition at line 2599 of file Instructions.h.
References llvm::UnaryInstruction::DECLARE_TRANSPARENT_OPERAND_ACCESSORS().
llvm::SwitchInst::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Provide fast operand accessors.
ConstantInt* llvm::SwitchInst::findCaseDest (BasicBlock * BB) inline
findCaseDest - Finds the unique case value for a given successor. Returns null if the successor is not found, not unique, or is the default case.
Definition at line 2679 of file Instructions.h.
References BB, and i.
Referenced by ReplaceUsesOfWith(), and TryToSimplifyUncondBranchWithICmpInIt().
CaseIt llvm::SwitchInst::findCaseValue (const ConstantInt * C) inline
findCaseValue - Search all of the case values for the specified constant. If it is explicitly handled, return the case iterator of it, otherwise return default case iterator to indicate that it is handled by the default handler.
Definition at line 2664 of file Instructions.h.
References i.
Referenced by EliminateDeadSwitchCases(), llvm::SparseSolver::getOrInitValueState(), ReplaceUsesOfWith(), SimplifySwitchOnSelect(), and TryToSimplifyUncondBranchWithICmpInIt().
ConstCaseIt llvm::SwitchInst::findCaseValue (const ConstantInt * C) const inline
Definition at line 2670 of file Instructions.h.
References i.
Value* llvm::SwitchInst::getCondition () const inline
Definition at line 2610 of file Instructions.h.
References llvm::User::getOperand().
Referenced by ConvertAtomicSynchScope(), llvm::createCorrelatedValuePropagationPass(), EliminateDeadSwitchCases(), FindLIVLoopCondition(), FindPhiPredForUseInBlock(), ForwardSwitchConditionToPHI(), GetCaseResults(), llvm::SparseSolver::getOrInitValueState(), llvm::CmpInst::isFalseWhenEqual(), isTrivialLoopExitBlock(), operator<<(), llvm::AssemblyWriter::printInstruction(), SwitchToLookupTable(), TryToSimplifyUncondBranchWithICmpInIt(), TurnSwitchRangeIntoICmp(), llvm::SelectionDAGBuilder::UpdateSplitBlock(), llvm::Interpreter::visitSwitchInst(), llvm::InstCombiner::visitSwitchInst(), and WriteInstruction().
BasicBlock* llvm::SwitchInst::getDefaultDest () const inline
Definition at line 2613 of file Instructions.h.
References llvm::User::getOperand().
Referenced by ConvertAtomicSynchScope(), llvm::CmpInst::isFalseWhenEqual(), operator<<(), llvm::AssemblyWriter::printInstruction(), SwitchToLookupTable(), TryToSimplifyUncondBranchWithICmpInIt(), TurnSwitchRangeIntoICmp(), llvm::SelectionDAGBuilder::UpdateSplitBlock(), llvm::Interpreter::visitSwitchInst(), and WriteInstruction().
unsigned llvm::SwitchInst::getNumCases () const inline
getNumCases - return the number of 'cases' in this switch instruction, except the default case
Definition at line 2623 of file Instructions.h.
References llvm::User::getNumOperands().
Referenced by ConvertAtomicSynchScope(), llvm::createCorrelatedValuePropagationPass(), EliminateDeadSwitchCases(), FindLIVLoopCondition(), operator<<(), ShouldBuildLookupTable(), SimplifySwitchOnSelect(), SwitchToLookupTable(), TryToSimplifyUncondBranchWithICmpInIt(), TurnSwitchRangeIntoICmp(), llvm::SelectionDAGBuilder::UpdateSplitBlock(), and ValuesOverlap().
unsigned llvm::SwitchInst::getNumSuccessors () const inline
Definition at line 2706 of file Instructions.h.
References llvm::User::getNumOperands().
Referenced by FitWeights(), and SwitchToLookupTable().
BasicBlock* llvm::SwitchInst::getSuccessor (unsigned idx) const inline
Definition at line 2707 of file Instructions.h.
References llvm::User::getOperand().
Referenced by FindPhiPredForUseInBlock(), FitWeights(), and SwitchToLookupTable().
void SwitchInst::removeCase (CaseIt i)
removeCase - This method removes the specified case and its successor from the switch instruction. Note that this operation may reorder the remaining cases at index idx and above. Note: This action invalidates iterators for all cases following the one removed, including the case_end() iterator.
removeCase - This method removes the specified case and its successor from the switch instruction.
Definition at line 3359 of file Instructions.cpp.
References llvm::User::allocHungoffUses(), llvm::SwitchInst::CaseIteratorT< SwitchInstTy, ConstantIntTy, BasicBlockTy >::getCaseIndex(), llvm::Value::getContext(), llvm::User::getNumOperands(), llvm::Value::getType(), llvm::Type::getVoidTy(), i, llvm::cl::init(), llvm::Type::isPointerTy(), llvm::User::NumOperands, llvm::User::OperandList, llvm::Use::set(), llvm::Value::SubclassOptionalData, and llvm::Use::zap().
Referenced by llvm::createCorrelatedValuePropagationPass(), EliminateDeadSwitchCases(), FindPhiPredForUseInBlock(), and ValuesOverlap().
void llvm::SwitchInst::setCondition (Value * V) inline
Definition at line 2611 of file Instructions.h.
References llvm::User::setOperand().
Referenced by llvm::createCorrelatedValuePropagationPass(), FindPhiPredForUseInBlock(), and llvm::InstCombiner::visitSwitchInst().
void llvm::SwitchInst::setDefaultDest (BasicBlock * DefaultCase) inline
Definition at line 2617 of file Instructions.h.
References llvm::User::setOperand().
Referenced by FindPhiPredForUseInBlock().
void llvm::SwitchInst::setSuccessor (unsigned idx, BasicBlock * NewSucc) inline
Definition at line 2711 of file Instructions.h.
References llvm::User::setOperand().
Referenced by FitWeights(), and llvm::SwitchInst::CaseIt::setSuccessor().
Member Data Documentation
const unsigned llvm::SwitchInst::DefaultPseudoIndex = static_cast<unsigned>(~0L-1) static
Definition at line 2481 of file Instructions.h.
The documentation for this class was generated from the following files:
Instructions.h
Instructions.cpp