LLVM: llvm::ImmutableMap< KeyT, ValT, ValInfo >::iterator Class Reference
LLVM API Documentation
llvm::ImmutableMap< KeyT, ValT, ValInfo >::iterator Class Reference
#include <ImmutableMap.h>
Public Types
typedef ptrdiff_t difference_type
typedef ImmutableMap< KeyT, ValT, ValInfo >::value_type value_type
typedef ImmutableMap< KeyT, ValT, ValInfo >::value_type_ref reference
typedef iterator::value_type * pointer
typedef std::bidirectional_iterator_tag iterator_category
Public Member Functions
iterator::reference operator* () const
iterator::pointer operator-> () const
key_type_ref getKey () const
data_type_ref getData () const
iterator & operator++ ()
iterator operator++ (int)
iterator & operator-- ()
iterator operator-- (int)
bool operator== (const iterator &RHS) const
bool operator!= (const iterator &RHS) const
Friends
class ImmutableMap
Detailed Description
template<typename KeyT, typename ValT, typename ValInfo = ImutKeyValueInfo<KeyT,ValT>>
class llvm::ImmutableMap< KeyT, ValT, ValInfo >::iterator
Definition at line 206 of file ImmutableMap.h.
Member Typedef Documentation
template<typename KeyT, typename ValT, typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> typedef ptrdiff_t llvm::ImmutableMap< KeyT, ValT, ValInfo >::iterator::difference_type
Definition at line 214 of file ImmutableMap.h.
template<typename KeyT, typename ValT, typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> typedef std::bidirectional_iterator_tag llvm::ImmutableMap< KeyT, ValT, ValInfo >::iterator::iterator_category
Definition at line 218 of file ImmutableMap.h.
template<typename KeyT, typename ValT, typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> typedef iterator::value_type* llvm::ImmutableMap< KeyT, ValT, ValInfo >::iterator::pointer
Definition at line 217 of file ImmutableMap.h.
template<typename KeyT, typename ValT, typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> typedef ImmutableMap<KeyT,ValT,ValInfo>::value_type_ref llvm::ImmutableMap< KeyT, ValT, ValInfo >::iterator::reference
Definition at line 216 of file ImmutableMap.h.
template<typename KeyT, typename ValT, typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> typedef ImmutableMap<KeyT,ValT,ValInfo>::value_type llvm::ImmutableMap< KeyT, ValT, ValInfo >::iterator::value_type
Definition at line 215 of file ImmutableMap.h.
Member Function Documentation
template<typename KeyT, typename ValT, typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> data_type_ref llvm::ImmutableMap< KeyT, ValT, ValInfo >::iterator::getData () const inline
Definition at line 224 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::getValue().
template<typename KeyT, typename ValT, typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> key_type_ref llvm::ImmutableMap< KeyT, ValT, ValInfo >::iterator::getKey () const inline
Definition at line 223 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::getValue().
template<typename KeyT, typename ValT, typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> bool llvm::ImmutableMap< KeyT, ValT, ValInfo >::iterator::operator!= (const iterator & RHS) const inline
Definition at line 232 of file ImmutableMap.h.
template<typename KeyT, typename ValT, typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> iterator::reference llvm::ImmutableMap< KeyT, ValT, ValInfo >::iterator::operator* () const inline
Definition at line 220 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::getValue().
template<typename KeyT, typename ValT, typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> iterator& llvm::ImmutableMap< KeyT, ValT, ValInfo >::iterator::operator++ () inline
Definition at line 226 of file ImmutableMap.h.
template<typename KeyT, typename ValT, typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> iterator llvm::ImmutableMap< KeyT, ValT, ValInfo >::iterator::operator++ (int) inline
Definition at line 227 of file ImmutableMap.h.
template<typename KeyT, typename ValT, typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> iterator& llvm::ImmutableMap< KeyT, ValT, ValInfo >::iterator::operator-- () inline
Definition at line 228 of file ImmutableMap.h.
template<typename KeyT, typename ValT, typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> iterator llvm::ImmutableMap< KeyT, ValT, ValInfo >::iterator::operator-- (int) inline
Definition at line 229 of file ImmutableMap.h.
template<typename KeyT, typename ValT, typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> iterator::pointer llvm::ImmutableMap< KeyT, ValT, ValInfo >::iterator::operator-> () const inline
Definition at line 221 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::getValue().
template<typename KeyT, typename ValT, typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> bool llvm::ImmutableMap< KeyT, ValT, ValInfo >::iterator::operator== (const iterator & RHS) const inline
Definition at line 231 of file ImmutableMap.h.
Friends And Related Function Documentation
template<typename KeyT, typename ValT, typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> friend class ImmutableMap friend
Definition at line 211 of file ImmutableMap.h.
The documentation for this class was generated from the following file:
ImmutableMap.h