LLVM: llvm::objcarc::ARCRuntimeEntryPoints Class Reference
LLVM API Documentation
llvm::objcarc::ARCRuntimeEntryPoints Class Reference
#include <ARCRuntimeEntryPoints.h>
Public Types
enum EntryPointType {
EPT_AutoreleaseRV, EPT_Release, EPT_Retain, EPT_RetainBlock,
EPT_Autorelease, EPT_StoreStrong, EPT_RetainRV, EPT_RetainAutorelease,
EPT_RetainAutoreleaseRV
}
Public Member Functions
ARCRuntimeEntryPoints ()
~ARCRuntimeEntryPoints ()
void Initialize (Module *M)
Constant * get (const EntryPointType entry)
Detailed Description
Declarations for ObjC runtime functions and constants. These are initialized lazily to avoid cluttering up the Module with unused declarations.
Definition at line 32 of file ARCRuntimeEntryPoints.h.
Member Enumeration Documentation
enum llvm::objcarc::ARCRuntimeEntryPoints::EntryPointType
Enumerator
EPT_AutoreleaseRV
EPT_Release
EPT_Retain
EPT_RetainBlock
EPT_Autorelease
EPT_StoreStrong
EPT_RetainRV
EPT_RetainAutorelease
EPT_RetainAutoreleaseRV
Definition at line 34 of file ARCRuntimeEntryPoints.h.
Constructor & Destructor Documentation
llvm::objcarc::ARCRuntimeEntryPoints::ARCRuntimeEntryPoints () inline
Definition at line 46 of file ARCRuntimeEntryPoints.h.
llvm::objcarc::ARCRuntimeEntryPoints::~ARCRuntimeEntryPoints () inline
Definition at line 57 of file ARCRuntimeEntryPoints.h.
Member Function Documentation
Constant* llvm::objcarc::ARCRuntimeEntryPoints::get (const EntryPointType entry) inline
Definition at line 72 of file ARCRuntimeEntryPoints.h.
References llvm::AttributeSet::addAttribute(), EPT_Autorelease, EPT_AutoreleaseRV, EPT_Release, EPT_Retain, EPT_RetainAutorelease, EPT_RetainAutoreleaseRV, EPT_RetainBlock, EPT_RetainRV, EPT_StoreStrong, llvm::FunctionType::get(), llvm::Module::getContext(), llvm::Type::getInt8Ty(), llvm::Module::getOrInsertFunction(), llvm::PointerType::getUnqual(), llvm::Type::getVoidTy(), llvm_unreachable, llvm::Attribute::NoCapture, and llvm::Attribute::NoUnwind.
void llvm::objcarc::ARCRuntimeEntryPoints::Initialize (Module * M) inline
Definition at line 59 of file ARCRuntimeEntryPoints.h.
References M.
The documentation for this class was generated from the following file:
ARCRuntimeEntryPoints.h