LLVM: llvm::MCMachObjectTargetWriter Class Reference
LLVM API Documentation
llvm::MCMachObjectTargetWriter Class Reference abstract
#include <MCMachObjectWriter.h>
Public Member Functions
virtual ~MCMachObjectTargetWriter ()
Lifetime Management
virtual void reset ()
Accessors
bool is64Bit () const
bool useAggressiveSymbolFolding () const
uint32_t getCPUType () const
uint32_t getCPUSubtype () const
unsigned getLocalDifferenceRelocationType () const
API
virtual void RecordRelocation (MachObjectWriter *Writer, const MCAssembler &Asm, const MCAsmLayout &Layout, const MCFragment *Fragment, const MCFixup &Fixup, MCValue Target, uint64_t &FixedValue)=0
Protected Member Functions
MCMachObjectTargetWriter (bool Is64Bit_, uint32_t CPUType_, uint32_t CPUSubtype_, bool UseAggressiveSymbolFolding_=false)
void setLocalDifferenceRelocationType (unsigned Type)
Detailed Description
Definition at line 27 of file MCMachObjectWriter.h.
Constructor & Destructor Documentation
MCMachObjectTargetWriter::MCMachObjectTargetWriter (bool Is64Bit_, uint32_t CPUType_, uint32_t CPUSubtype_, bool UseAggressiveSymbolFolding_ = false) protected
Definition at line 14 of file MCMachObjectTargetWriter.cpp.
MCMachObjectTargetWriter::~MCMachObjectTargetWriter () virtual
Definition at line 21 of file MCMachObjectTargetWriter.cpp.
Referenced by setLocalDifferenceRelocationType().
Member Function Documentation
uint32_t llvm::MCMachObjectTargetWriter::getCPUSubtype () const inline
Definition at line 61 of file MCMachObjectWriter.h.
uint32_t llvm::MCMachObjectTargetWriter::getCPUType () const inline
Definition at line 60 of file MCMachObjectWriter.h.
unsigned llvm::MCMachObjectTargetWriter::getLocalDifferenceRelocationType () const inline
Definition at line 62 of file MCMachObjectWriter.h.
References llvm::HexStyle::Asm, and RecordRelocation().
bool llvm::MCMachObjectTargetWriter::is64Bit () const inline
Definition at line 58 of file MCMachObjectWriter.h.
virtual void llvm::MCMachObjectTargetWriter::RecordRelocation (MachObjectWriter * Writer, const MCAssembler & Asm, const MCAsmLayout & Layout, const MCFragment * Fragment, const MCFixup & Fixup, MCValue Target, uint64_t & FixedValue) pure virtual
Referenced by llvm::MachObjectWriter::addRelocation(), and getLocalDifferenceRelocationType().
virtual void llvm::MCMachObjectTargetWriter::reset () inline virtual
Definition at line 51 of file MCMachObjectWriter.h.
Referenced by llvm::MachObjectWriter::MachObjectWriter().
void llvm::MCMachObjectTargetWriter::setLocalDifferenceRelocationType (unsigned Type) inline protected
Definition at line 41 of file MCMachObjectWriter.h.
References Type, and ~MCMachObjectTargetWriter().
bool llvm::MCMachObjectTargetWriter::useAggressiveSymbolFolding () const inline
Definition at line 59 of file MCMachObjectWriter.h.
The documentation for this class was generated from the following files:
MCMachObjectWriter.h
MCMachObjectTargetWriter.cpp