LLVM: llvm::CallGraphSCC Class Reference
LLVM API Documentation
llvm::CallGraphSCC Class Reference
CallGraphSCC - This is a single SCC that a CallGraphSCCPass is run on.
#include <CallGraphSCCPass.h>
Public Types
typedef std::vector< CallGraphNode * >::const_iterator iterator
Public Member Functions
CallGraphSCC (void *context)
void initialize (CallGraphNode *const *I, CallGraphNode *const *E)
bool isSingular () const
unsigned size () const
void ReplaceNode (CallGraphNode *Old, CallGraphNode *New)
iterator begin () const
iterator end () const
Detailed Description
CallGraphSCC - This is a single SCC that a CallGraphSCCPass is run on.
Definition at line 83 of file CallGraphSCCPass.h.
Member Typedef Documentation
typedef std::vector<CallGraphNode*>::const_iterator llvm::CallGraphSCC::iterator
Definition at line 100 of file CallGraphSCCPass.h.
Constructor & Destructor Documentation
llvm::CallGraphSCC::CallGraphSCC (void * context) inline
Definition at line 87 of file CallGraphSCCPass.h.
Member Function Documentation
iterator llvm::CallGraphSCC::begin () const inline
Definition at line 101 of file CallGraphSCCPass.h.
Referenced by llvm::createArgumentPromotionPass(), llvm::createFunctionAttrsPass(), llvm::createPruneEHPass(), determinePointerReadAttrs(), llvm::CallGraphSCCPass::getAnalysisUsage(), and llvm::Inliner::runOnSCC().
iterator llvm::CallGraphSCC::end () const inline
Definition at line 102 of file CallGraphSCCPass.h.
Referenced by llvm::createArgumentPromotionPass(), llvm::createFunctionAttrsPass(), llvm::createPruneEHPass(), determinePointerReadAttrs(), llvm::CallGraphSCCPass::getAnalysisUsage(), and llvm::Inliner::runOnSCC().
void llvm::CallGraphSCC::initialize (CallGraphNode *const * I, CallGraphNode *const * E) inline
Definition at line 89 of file CallGraphSCCPass.h.
bool llvm::CallGraphSCC::isSingular () const inline
Definition at line 93 of file CallGraphSCCPass.h.
Referenced by llvm::Inliner::runOnSCC().
void CallGraphSCC::ReplaceNode (CallGraphNode * Old, CallGraphNode * New)
ReplaceNode - This informs the SCC and the pass manager that the specified Old node has been deleted, and New is to be used in its place.
Definition at line 512 of file CallGraphSCCPass.cpp.
References i, and llvm::scc_iterator< GraphT, GT >::ReplaceNode().
Referenced by llvm::createArgumentPromotionPass().
unsigned llvm::CallGraphSCC::size () const inline
Definition at line 94 of file CallGraphSCCPass.h.
The documentation for this class was generated from the following files:
CallGraphSCCPass.h
CallGraphSCCPass.cpp