LLVM: llvm::UnsetInit Class Reference
LLVM API Documentation
llvm::UnsetInit Class Reference
#include <Record.h>
Public Member Functions
virtual Init * convertInitializerTo (RecTy *Ty) const
virtual Init * getBit (unsigned Bit) const
virtual bool isComplete () const
virtual std::string getAsString () const
getAsString - Convert this value to a string form.
Public Member Functions inherited from llvm::Init
InitKind getKind () const
virtual ~Init ()
void print (raw_ostream &OS) const
print - Print out this value.
virtual std::string getAsUnquotedString () const
void dump () const
virtual Init * convertInitializerBitRange (const std::vector< unsigned > &Bits) const
virtual Init * convertInitListSlice (const std::vector< unsigned > &Elements) const
virtual RecTy * getFieldType (const std::string &FieldName) const
virtual Init * getFieldInit (Record &R, const RecordVal *RV, const std::string &FieldName) const
virtual Init * resolveReferences (Record &R, const RecordVal *RV) const
virtual Init * getBitVar () const
virtual unsigned getBitNum () const
Static Public Member Functions
static bool classof (const Init *I)
static UnsetInit * get ()
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind {
IK_BitInit, IK_BitsInit, IK_FirstTypedInit, IK_DagInit,
IK_DefInit, IK_FieldInit, IK_IntInit, IK_ListInit,
IK_FirstOpInit, IK_BinOpInit, IK_TernOpInit, IK_UnOpInit,
IK_LastOpInit, IK_StringInit, IK_VarInit, IK_VarListElementInit,
IK_LastTypedInit, IK_UnsetInit, IK_VarBitInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::Init
Init (InitKind K)
Detailed Description
UnsetInit - ? - Represents an uninitialized value
Definition at line 593 of file Record.h.
Member Function Documentation
static bool llvm::UnsetInit::classof (const Init * I) inline static
Definition at line 600 of file Record.h.
References llvm::Init::getKind().
virtual Init* llvm::UnsetInit::convertInitializerTo (RecTy * Ty) const inline virtual
convertInitializerTo - This virtual function is a simple call-back function that should be overridden to call the appropriate RecTy::convertValue method.
Implements llvm::Init.
Definition at line 605 of file Record.h.
References llvm::RecTy::convertValue().
UnsetInit * UnsetInit::get () static
Definition at line 433 of file Record.cpp.
Referenced by llvm::BitsRecTy::convertValue(), fixBitInit(), GetNewAnonymousName(), llvm::Record::getValueAsBitOrUnset(), llvm::Record::isValueUnset(), and llvm::RecordVal::RecordVal().
virtual std::string llvm::UnsetInit::getAsString () const inline virtual
getAsString - Convert this value to a string form.
Implements llvm::Init.
Definition at line 614 of file Record.h.
virtual Init* llvm::UnsetInit::getBit (unsigned Bit) const inline virtual
getBit - This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 609 of file Record.h.
virtual bool llvm::UnsetInit::isComplete () const inline virtual
isComplete - This virtual method should be overridden by values that may not be completely specified yet.
Reimplemented from llvm::Init.
Definition at line 613 of file Record.h.
The documentation for this class was generated from the following files:
Record.h
Record.cpp