LLVM: llvm::DIEAbbrev Class Reference
LLVM API Documentation
llvm::DIEAbbrev Class Reference
#include <DIE.h>
Public Member Functions
DIEAbbrev (dwarf::Tag T, uint16_t C)
dwarf::Tag getTag () const
unsigned getNumber () const
uint16_t getChildrenFlag () const
const SmallVectorImpl< DIEAbbrevData > & getData () const
void setChildrenFlag (uint16_t CF)
void setNumber (unsigned N)
void AddAttribute (dwarf::Attribute Attribute, dwarf::Form Form)
void Profile (FoldingSetNodeID &ID) const
void Emit (AsmPrinter *AP) const
void print (raw_ostream &O)
void dump ()
Public Member Functions inherited from llvm::FoldingSetImpl::Node
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Detailed Description
DIEAbbrev - Dwarf abbreviation, describes the organization of a debug information object.
Definition at line 56 of file DIE.h.
Constructor & Destructor Documentation
llvm::DIEAbbrev::DIEAbbrev (dwarf::Tag T, uint16_t C) inline
Definition at line 74 of file DIE.h.
Member Function Documentation
void llvm::DIEAbbrev::AddAttribute (dwarf::Attribute Attribute, dwarf::Form Form) inline
AddAttribute - Adds another set of attribute information to the abbreviation.
Definition at line 86 of file DIE.h.
References llvm::DIEAbbrevData::DIEAbbrevData(), llvm::dump(), llvm::DIEAbbrevData::Profile(), and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by llvm::DIE::addValue().
void DIEAbbrev::dump ()
Definition at line 103 of file DIE.cpp.
References llvm::dbgs().
void DIEAbbrev::Emit (AsmPrinter * AP) const
Emit - Print the abbreviation using the specified asm printer.
Definition at line 60 of file DIE.cpp.
References llvm::dwarf::AttributeString(), llvm::dwarf::ChildrenString(), llvm::AsmPrinter::EmitULEB128(), llvm::dwarf::FormEncodingString(), llvm::DIEAbbrevData::getAttribute(), llvm::DIEAbbrevData::getForm(), i, N, and llvm::dwarf::TagString().
Referenced by llvm::DwarfUnits::emitUnits().
uint16_t llvm::DIEAbbrev::getChildrenFlag () const inline
Definition at line 79 of file DIE.h.
Referenced by llvm::DwarfUnits::computeSizeAndOffset(), and llvm::DwarfDebug::emitDIE().
const SmallVectorImpl<DIEAbbrevData>& llvm::DIEAbbrev::getData () const inline
Definition at line 80 of file DIE.h.
Referenced by llvm::DwarfUnits::computeSizeAndOffset(), llvm::DwarfDebug::emitDIE(), llvm::DIE::findAttribute(), and getDIEStringAttr().
unsigned llvm::DIEAbbrev::getNumber () const inline
Definition at line 78 of file DIE.h.
Referenced by llvm::DwarfUnits::assignAbbrevNumber(), llvm::DwarfUnits::emitUnits(), and llvm::DIE::getAbbrevNumber().
dwarf::Tag llvm::DIEAbbrev::getTag () const inline
Definition at line 77 of file DIE.h.
Referenced by llvm::DwarfDebug::emitDIE(), and llvm::DIE::getTag().
void DIEAbbrev::print (raw_ostream & O)
Definition at line 86 of file DIE.cpp.
References llvm::dwarf::AttributeString(), llvm::dwarf::ChildrenString(), llvm::format(), llvm::dwarf::FormEncodingString(), llvm::DIEAbbrevData::getAttribute(), llvm::DIEAbbrevData::getForm(), i, N, and llvm::dwarf::TagString().
void DIEAbbrev::Profile (FoldingSetNodeID & ID) const
Profile - Used to gather unique data for the abbreviation folding set.
Definition at line 49 of file DIE.cpp.
References llvm::FoldingSetNodeID::AddInteger(), i, N, and llvm::DIEAbbrevData::Profile().
void llvm::DIEAbbrev::setChildrenFlag (uint16_t CF) inline
Definition at line 81 of file DIE.h.
Referenced by llvm::DIE::addChild().
void llvm::DIEAbbrev::setNumber (unsigned N) inline
Definition at line 82 of file DIE.h.
References N.
Referenced by llvm::DwarfUnits::assignAbbrevNumber().
The documentation for this class was generated from the following files:
DIE.h
DIE.cpp