LLVM: llvm::RegisterScheduler Class Reference
LLVM API Documentation
llvm::RegisterScheduler Class Reference
#include <SchedulerRegistry.h>
Public Types
typedef ScheduleDAGSDNodes *(* FunctionPassCtor) (SelectionDAGISel *, CodeGenOpt::Level)
Public Member Functions
RegisterScheduler (const char *N, const char *D, FunctionPassCtor C)
~RegisterScheduler ()
RegisterScheduler * getNext () const
Public Member Functions inherited from llvm::MachinePassRegistryNode
MachinePassRegistryNode (const char *N, const char *D, MachinePassCtor C)
MachinePassRegistryNode * getNext () const
MachinePassRegistryNode ** getNextAddress ()
const char * getName () const
const char * getDescription () const
MachinePassCtor getCtor () const
void setNext (MachinePassRegistryNode *N)
Static Public Member Functions
static RegisterScheduler * getList ()
static FunctionPassCtor getDefault ()
static void setDefault (FunctionPassCtor C)
static void setListener (MachinePassRegistryListener *L)
Static Public Attributes
static MachinePassRegistry Registry
Detailed Description
Definition at line 34 of file SchedulerRegistry.h.
Member Typedef Documentation
typedef ScheduleDAGSDNodes*(* llvm::RegisterScheduler::FunctionPassCtor) (SelectionDAGISel *, CodeGenOpt::Level)
Definition at line 36 of file SchedulerRegistry.h.
Constructor & Destructor Documentation
llvm::RegisterScheduler::RegisterScheduler (const char * N, const char * D, FunctionPassCtor C) inline
Definition at line 41 of file SchedulerRegistry.h.
References llvm::MachinePassRegistry::Add().
llvm::RegisterScheduler::~RegisterScheduler () inline
Definition at line 44 of file SchedulerRegistry.h.
References llvm::MachinePassRegistry::Remove().
Member Function Documentation
static FunctionPassCtor llvm::RegisterScheduler::getDefault () inline static
Definition at line 55 of file SchedulerRegistry.h.
References llvm::MachinePassRegistry::getDefault().
Referenced by FindSplitPointForStackProtector().
static RegisterScheduler* llvm::RegisterScheduler::getList () inline static
Definition at line 52 of file SchedulerRegistry.h.
References llvm::MachinePassRegistry::getList().
RegisterScheduler* llvm::RegisterScheduler::getNext () const inline
Definition at line 49 of file SchedulerRegistry.h.
References llvm::MachinePassRegistryNode::getNext().
static void llvm::RegisterScheduler::setDefault (FunctionPassCtor C) inline static
Definition at line 58 of file SchedulerRegistry.h.
References llvm::MachinePassRegistry::setDefault().
Referenced by FindSplitPointForStackProtector().
static void llvm::RegisterScheduler::setListener (MachinePassRegistryListener * L) inline static
Definition at line 61 of file SchedulerRegistry.h.
References llvm::createBURRListDAGScheduler(), llvm::createDAGLinearizer(), llvm::createDefaultScheduler(), llvm::createFastDAGScheduler(), llvm::createHybridListDAGScheduler(), llvm::createILPListDAGScheduler(), llvm::createSourceListDAGScheduler(), llvm::createVLIWDAGScheduler(), and llvm::MachinePassRegistry::setListener().
Member Data Documentation
MachinePassRegistry RegisterScheduler::Registry static
RegisterScheduler class - Track the registration of instruction schedulers.
Definition at line 39 of file SchedulerRegistry.h.
The documentation for this class was generated from the following files:
SchedulerRegistry.h
SelectionDAGISel.cpp