LLVM: llvm::GlobalValue Class Reference
LLVM API Documentation
llvm::GlobalValue Class Reference abstract
#include <GlobalValue.h>
Public Types
enum LinkageTypes {
ExternalLinkage = 0, AvailableExternallyLinkage, LinkOnceAnyLinkage, LinkOnceODRLinkage,
WeakAnyLinkage, WeakODRLinkage, AppendingLinkage, InternalLinkage,
PrivateLinkage, LinkerPrivateLinkage, LinkerPrivateWeakLinkage, DLLImportLinkage,
DLLExportLinkage, ExternalWeakLinkage, CommonLinkage
}
An enumeration for the kinds of linkage for global values.
enum VisibilityTypes { DefaultVisibility = 0, HiddenVisibility, ProtectedVisibility }
An enumeration for the kinds of visibility of global values.
Public Types inherited from llvm::Constant
enum PossibleRelocationsTy { NoRelocation = 0, LocalRelocation = 1, GlobalRelocations = 2 }
Public Types inherited from llvm::User
typedef Use * op_iterator
typedef const Use * const_op_iterator
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal, BasicBlockVal, FunctionVal, GlobalAliasVal,
GlobalVariableVal, UndefValueVal, BlockAddressVal, ConstantExprVal,
ConstantAggregateZeroVal, ConstantDataArrayVal, ConstantDataVectorVal, ConstantIntVal,
ConstantFPVal, ConstantArrayVal, ConstantStructVal, ConstantVectorVal,
ConstantPointerNullVal, MDNodeVal, MDStringVal, InlineAsmVal,
PseudoSourceValueVal, FixedStackPseudoSourceValueVal, InstructionVal, ConstantFirstVal = FunctionVal,
ConstantLastVal = ConstantPointerNullVal
}
typedef value_use_iterator< User > use_iterator
typedef value_use_iterator< const User > const_use_iterator
Public Member Functions
~GlobalValue ()
unsigned getAlignment () const
void setAlignment (unsigned Align)
bool hasUnnamedAddr () const
void setUnnamedAddr (bool Val)
VisibilityTypes getVisibility () const
bool hasDefaultVisibility () const
bool hasHiddenVisibility () const
bool hasProtectedVisibility () const
void setVisibility (VisibilityTypes V)
bool hasSection () const
const std::string & getSection () const
void setSection (StringRef S)
bool use_empty_except_constants ()
Determine if the usage of this global value is empty except for transitively dead constants.
PointerType * getType () const
getType - Global values are always pointers.
bool hasExternalLinkage () const
bool hasAvailableExternallyLinkage () const
bool hasLinkOnceLinkage () const
bool hasWeakLinkage () const
bool hasAppendingLinkage () const
bool hasInternalLinkage () const
bool hasPrivateLinkage () const
bool hasLinkerPrivateLinkage () const
bool hasLinkerPrivateWeakLinkage () const
bool hasLocalLinkage () const
bool hasDLLImportLinkage () const
bool hasDLLExportLinkage () const
bool hasExternalWeakLinkage () const
bool hasCommonLinkage () const
void setLinkage (LinkageTypes LT)
LinkageTypes getLinkage () const
bool isDiscardableIfUnused () const
bool mayBeOverridden () const
bool isWeakForLinker () const
virtual void copyAttributesFrom (const GlobalValue *Src)
virtual void destroyConstant ()
Override from Constant class.
bool isDeclaration () const
virtual void removeFromParent ()=0
virtual void eraseFromParent ()=0
Module * getParent ()
const Module * getParent () const
Materialization
Materialization is used to construct functions only as they're needed. This is useful to reduce memory usage in LLVM or parsing work done by the BitcodeReader to load the Module.
bool isMaterializable () const
bool isDematerializable () const
bool Materialize (std::string *ErrInfo=0)
void Dematerialize ()
Public Member Functions inherited from llvm::Constant
bool isNullValue () const
bool isAllOnesValue () const
bool isNegativeZeroValue () const
bool isZeroValue () const
Return true if the value is negative zero or null value.
bool canTrap () const
bool isThreadDependent () const
isThreadDependent - Return true if the value can vary between threads.
bool isConstantUsed () const
PossibleRelocationsTy getRelocationInfo () const
Constant * getAggregateElement (unsigned Elt) const
Constant * getAggregateElement (Constant *Elt) const
Constant * getSplatValue () const
const APInt & getUniqueInteger () const
virtual void replaceUsesOfWithOnConstant (Value *, Value *, Use *)
void removeDeadConstantUsers () const
Public Member Functions inherited from llvm::User
~User ()
void operator delete (void *Usr)
operator delete - free memory allocated for User and Use objects
void operator delete (void *, unsigned)
placement delete - required by std, but never called.
void operator delete (void *, unsigned, bool)
placement delete - required by std, but never called.
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
void dropAllReferences ()
void replaceUsesOfWith (Value *From, Value *To)
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
dump - Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O, AssemblyAnnotationWriter *AAW=0) const
Type * getType () const
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
void setName (const Twine &Name)
void takeName (Value *V)
void replaceAllUsesWith (Value *V)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
User * use_back ()
const User * use_back () const
bool hasOneUse () const
bool hasNUses (unsigned N) const
bool hasNUsesOrMore (unsigned N) const
bool isUsedInBasicBlock (const BasicBlock *BB) const
unsigned getNumUses () const
void addUse (Use &U)
unsigned getValueID () const
unsigned getRawSubclassOptionalData () const
void clearSubclassOptionalData ()
bool hasSameSubclassOptionalData (const Value *V) const
void intersectOptionalDataWith (const Value *V)
bool hasValueHandle () const
Value * stripPointerCasts ()
Strips off any unneeded pointer casts, all-zero GEPs and aliases from the specified value, returning the original uncasted value.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strips off any unneeded pointer casts and all-zero GEPs from the specified value, returning the original uncasted value.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strips off unneeded pointer casts and all-constant GEPs from the specified value, returning the original pointer value.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Strips like stripInBoundsConstantOffsets but also accumulates the constant offset stripped.
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strips off unneeded pointer casts and any in-bounds offsets from the specified value, returning the original pointer value.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer () const
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Static Public Member Functions
static LinkageTypes getLinkOnceLinkage (bool ODR)
static LinkageTypes getWeakLinkage (bool ODR)
static bool isExternalLinkage (LinkageTypes Linkage)
static bool isAvailableExternallyLinkage (LinkageTypes Linkage)
static bool isLinkOnceLinkage (LinkageTypes Linkage)
static bool isWeakLinkage (LinkageTypes Linkage)
static bool isAppendingLinkage (LinkageTypes Linkage)
static bool isInternalLinkage (LinkageTypes Linkage)
static bool isPrivateLinkage (LinkageTypes Linkage)
static bool isLinkerPrivateLinkage (LinkageTypes Linkage)
static bool isLinkerPrivateWeakLinkage (LinkageTypes Linkage)
static bool isLocalLinkage (LinkageTypes Linkage)
static bool isDLLImportLinkage (LinkageTypes Linkage)
static bool isDLLExportLinkage (LinkageTypes Linkage)
static bool isExternalWeakLinkage (LinkageTypes Linkage)
static bool isCommonLinkage (LinkageTypes Linkage)
static bool isDiscardableIfUnused (LinkageTypes Linkage)
static bool mayBeOverridden (LinkageTypes Linkage)
static bool isWeakForLinker (LinkageTypes Linkage)
static StringRef getRealLinkageName (StringRef Name)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Constant
static bool classof (const Value *V)
static Constant * getNullValue (Type *Ty)
static Constant * getAllOnesValue (Type *Ty)
Get the all ones value.
static Constant * getIntegerValue (Type *Ty, const APInt &V)
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Protected Member Functions
GlobalValue (Type *ty, ValueTy vty, Use *Ops, unsigned NumOps, LinkageTypes linkage, const Twine &Name)
Protected Member Functions inherited from llvm::Constant
Constant (Type *ty, ValueTy vty, Use *Ops, unsigned NumOps)
void destroyConstantImpl ()
Protected Member Functions inherited from llvm::User
void * operator new (size_t s, unsigned Us)
User (Type *ty, unsigned vty, Use *OpList, unsigned NumOps)
Use * allocHungoffUses (unsigned) const
void dropHungoffUses ()
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
virtual void printCustom (raw_ostream &O) const
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Attributes
LinkageTypes Linkage: 5
unsigned Visibility: 2
unsigned Alignment: 16
unsigned UnnamedAddr: 1
Module * Parent
std::string Section
Protected Attributes inherited from llvm::User
Use * OperandList
unsigned NumOperands
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Additional Inherited Members
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Detailed Description
Definition at line 29 of file GlobalValue.h.
Member Enumeration Documentation
enum llvm::GlobalValue::LinkageTypes
An enumeration for the kinds of linkage for global values.
Enumerator
ExternalLinkage
Externally visible function.
AvailableExternallyLinkage
Available for inspection, not emission.
LinkOnceAnyLinkage
Keep one copy of function when linking (inline)
LinkOnceODRLinkage
Same, but only replaced by something equivalent.
WeakAnyLinkage
Keep one copy of named function when linking (weak)
WeakODRLinkage
Same, but only replaced by something equivalent.
AppendingLinkage
Special purpose, only applies to global arrays.
InternalLinkage
Rename collisions when linking (static functions).
PrivateLinkage
Like Internal, but omit from symbol table.
LinkerPrivateLinkage
Like Private, but linker removes.
LinkerPrivateWeakLinkage
Like LinkerPrivate, but weak.
DLLImportLinkage
Function to be imported from DLL.
DLLExportLinkage
Function to be accessible from DLL.
ExternalWeakLinkage
ExternalWeak linkage description.
CommonLinkage
Tentative definitions.
Definition at line 33 of file GlobalValue.h.
enum llvm::GlobalValue::VisibilityTypes
An enumeration for the kinds of visibility of global values.
Enumerator
DefaultVisibility
The GV is visible.
HiddenVisibility
The GV is hidden.
ProtectedVisibility
The GV is protected.
Definition at line 52 of file GlobalValue.h.
Constructor & Destructor Documentation
llvm::GlobalValue::GlobalValue (Type * ty, ValueTy vty, Use * Ops, unsigned NumOps, LinkageTypes linkage, const Twine & Name) inline protected
Definition at line 59 of file GlobalValue.h.
References llvm::Value::setName().
llvm::GlobalValue::~GlobalValue () inline
Definition at line 75 of file GlobalValue.h.
References llvm::Constant::removeDeadConstantUsers().
Member Function Documentation
static bool llvm::GlobalValue::classof (const Value * V) inline static
Definition at line 290 of file GlobalValue.h.
References llvm::Value::FunctionVal, llvm::Value::getValueID(), llvm::Value::GlobalAliasVal, and llvm::Value::GlobalVariableVal.
void GlobalValue::copyAttributesFrom (const GlobalValue * Src) virtual
copyAttributesFrom - copy all additional attributes (those not needed to create a GlobalValue) from the GlobalValue Src to this one.
Reimplemented in llvm::Function, and llvm::GlobalVariable.
Definition at line 51 of file Globals.cpp.
References getAlignment(), getSection(), getVisibility(), hasUnnamedAddr(), setAlignment(), setSection(), setUnnamedAddr(), and setVisibility().
Referenced by llvm::CloneModule(), llvm::GlobalVariable::copyAttributesFrom(), llvm::Function::copyAttributesFrom(), copyGVAttributes(), and isWeakForLinker().
void GlobalValue::Dematerialize ()
Dematerialize - If this GlobalValue is read in, and if the GVMaterializer supports it, release the memory for the function, and set it up to be materialized lazily. If !isDematerializable(), this method is a noop.
Definition at line 39 of file Globals.cpp.
References llvm::Module::Dematerialize(), and getParent().
Referenced by getArrayElements(), and getRealLinkageName().
void GlobalValue::destroyConstant () virtual
Override from Constant class.
Override destroyConstant to make sure it doesn't get called on GlobalValue's because they shouldn't be treated like other constants.
Reimplemented from llvm::Constant.
Definition at line 45 of file Globals.cpp.
References llvm_unreachable.
Referenced by getRealLinkageName().
virtual void llvm::GlobalValue::eraseFromParent () pure virtual
eraseFromParent - This method unlinks 'this' from the containing module and deletes it.
Implemented in llvm::Function, llvm::GlobalVariable, and llvm::GlobalAlias.
Referenced by getRealLinkageName(), and isLessConstraining().
unsigned llvm::GlobalValue::getAlignment () const inline
Definition at line 79 of file GlobalValue.h.
References Align, Alignment, and setAlignment().
Referenced by canBeHidden(), checkInterfaceFunction(), llvm::ConstantFoldBinaryInstruction(), ConvertAtomicSynchScope(), copyAttributesFrom(), copyGVAttributes(), createCast(), llvm::NVPTXAsmPrinter::doFinalization(), ftostr(), GetConstantPoolSizeInBytes(), getGVAlignmentLog2(), llvm::DataLayout::getPreferredAlignment(), getVCmpEQInst(), IsBetterCannonical(), isLessConstraining(), llvm::SystemZSubtarget::isPC32DBLSymbol(), isWordAligned(), llvm::AArch64TargetLowering::LowerGlobalAddressELFSmall(), llvm::AssemblyWriter::printFunction(), llvm::AssemblyWriter::printGlobal(), setAlignment(), SRAGlobal(), stripRegisterPrefix(), and llvm::ObjectSizeOffsetVisitor::visitGlobalVariable().
LinkageTypes llvm::GlobalValue::getLinkage () const inline
Definition at line 218 of file GlobalValue.h.
References Linkage.
Referenced by canBeHidden(), checkInterfaceFunction(), llvm::CloneFunction(), ConvertAtomicSynchScope(), createCast(), llvm::createDeadArgHackingPass(), llvm::AsmPrinter::doInitialization(), ftostr(), getEncodedLinkage(), llvm::Inliner::getInlineThreshold(), INITIALIZE_PASS(), InstallGlobalCtors(), isLessConstraining(), isZeroLengthArray(), makeVisible(), MarkIndicesSafe(), NumRetVals(), llvm::AssemblyWriter::printAlias(), llvm::AssemblyWriter::printFunction(), llvm::AssemblyWriter::printGlobal(), and UpgradeIntrinsicFunction1().
static LinkageTypes llvm::GlobalValue::getLinkOnceLinkage (bool ODR) inline static
Definition at line 111 of file GlobalValue.h.
References LinkOnceAnyLinkage, and LinkOnceODRLinkage.
Module* llvm::GlobalValue::getParent () inline
getParent - Get the module that this global value is contained inside of...
Definition at line 286 of file GlobalValue.h.
References Parent.
Referenced by llvm::PBQPBuilderWithCoalescing::build(), changeToUnreachable(), checkInterfaceFunction(), CollectBSwapParts(), ComputePostOrders(), createCast(), llvm::createDeadArgHackingPass(), llvm::createDwarfEHPass(), llvm::IRBuilderBase::CreateGlobalString(), llvm::IRBuilderBase::CreateLifetimeEnd(), llvm::IRBuilderBase::CreateLifetimeStart(), llvm::IRBuilderBase::CreateMemCpy(), llvm::IRBuilderBase::CreateMemMove(), llvm::IRBuilderBase::CreateMemSet(), llvm::createPPCCTRLoopsVerify(), createPrivateNonConstGlobalForString(), cse(), Dematerialize(), llvm::EmitFPutC(), llvm::EmitFPutS(), llvm::AsmPrinter::EmitFunctionHeader(), llvm::EmitFWrite(), llvm::AsmPrinter::EmitGlobalVariable(), llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc(), llvm::EmitMemChr(), llvm::EmitMemCmp(), llvm::EmitMemCpyChk(), llvm::EmitPutChar(), llvm::EmitPutS(), llvm::EmitStrChr(), llvm::EmitStrCpy(), llvm::EmitStrLen(), llvm::EmitStrNCmp(), llvm::EmitStrNCpy(), llvm::EmitStrNLen(), llvm::EmitUnaryFloatFnCall(), enqueueUsersInWorklist(), llvm::GlobalAlias::eraseFromParent(), llvm::GlobalVariable::eraseFromParent(), llvm::CodeExtractor::extractCodeRegion(), llvm::MCFunction::find(), llvm::findAllNVVMAnnotation(), llvm::findOneNVVMAnnotation(), forceRenaming(), GenerateARCBBEntranceAnnotation(), GenerateARCBBTerminatorAnnotation(), generateUnsignedDivisionCode(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getCaller(), llvm::GCModuleInfo::getFunctionInfo(), getMemSetPatternValue(), llvm::Trace::getModule(), getModuleFromVal(), llvm::CallGraph::getOrInsertFunction(), getParent(), llvm::MCJIT::getPointerToFunction(), llvm::SparcTargetLowering::getSRetArgSize(), llvm::GlobalAlias::GlobalAlias(), llvm::GlobalVariable::GlobalVariable(), HandleByValArgument(), hasReturnsTwiceAttr(), INITIALIZE_PASS(), llvm::InlineFunction(), InstallGlobalCtors(), llvm::AnalysisManager::invalidateAll(), llvm::isAllocaPromotable(), isAtomic(), isContiguous(), isDematerializable(), llvm::isImageReadOnly(), llvm::isImageWriteOnly(), llvm::SpecialCaseList::isIn(), isInterestingPointer(), isLessConstraining(), isMaterializable(), llvm::isSampler(), isZeroLengthArray(), llvm::linkShadowStackGC(), llvm::lintFunction(), LLVMGetNextFunction(), LLVMGetNextGlobal(), LLVMGetPreviousFunction(), LLVMGetPreviousGlobal(), nvptx::LowerConstant(), lowerConstant(), llvm::LowerDbgDeclare(), llvm::IntrinsicLowering::LowerToByteSwap(), MarkIndicesSafe(), Materialize(), NumRetVals(), operator<<(), OptimizeGlobalAddressOfMalloc(), PerformHeapAllocSRoA(), llvm::Value::print(), llvm::AssemblyWriter::printFunction(), llvm::AssemblyWriter::printGlobal(), PrintOps(), ProcessUAddIdiom(), ProcessUGT_ADDCST_ADD(), promoteSingleBlockAlloca(), ReadWideAPInt(), llvm::GlobalAlias::removeFromParent(), llvm::GlobalVariable::removeFromParent(), ReplaceCallWith(), rewriteSingleStoreAlloca(), llvm::JIT::runFunction(), llvm::NVPTXLowerAggrCopies::runOnFunction(), llvm::StackProtector::runOnFunction(), setUsedInitializer(), SRAGlobal(), StackMallocSizeClass(), SwitchToLookupTable(), tryToMakeAllocaBePromotable(), TryToShrinkGlobalToBoolean(), llvm::UpgradeIntrinsicCall(), UpgradeIntrinsicFunction1(), UpgradeSSE41Function(), usedInOneFunc(), llvm::verifyFunction(), llvm::InstCombiner::visitCallInst(), and llvm::InstCombiner::visitFPTrunc().
const Module* llvm::GlobalValue::getParent () const inline
Definition at line 287 of file GlobalValue.h.
References Parent.
static StringRef llvm::GlobalValue::getRealLinkageName (StringRef Name) inline static
getRealLinkageName - If special LLVM prefix that is used to inform the asm printer to not emit usual symbol prefix before the symbol name is used then return linkage name after skipping this special LLVM prefix.
Definition at line 235 of file GlobalValue.h.
References Dematerialize(), destroyConstant(), llvm::StringRef::empty(), eraseFromParent(), isDeclaration(), isDematerializable(), isMaterializable(), Materialize(), removeFromParent(), and llvm::StringRef::substr().
Referenced by llvm::CompileUnit::createGlobalVariableDIE(), fixupSubprogramName(), and llvm::CompileUnit::getOrCreateSubprogramDIE().
const std::string& llvm::GlobalValue::getSection () const inline
Definition at line 96 of file GlobalValue.h.
References Section.
Referenced by checkInterfaceFunction(), ConvertAtomicSynchScope(), copyAttributesFrom(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), ftostr(), llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileMachO::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), isLessConstraining(), isSuitableForBSS(), LTOModule::makeLTOModule(), llvm::AssemblyWriter::printFunction(), and llvm::AssemblyWriter::printGlobal().
PointerType* llvm::GlobalValue::getType () const inline
getType - Global values are always pointers.
Definition at line 107 of file GlobalValue.h.
References llvm::Value::getType().
Referenced by llvm::Interpreter::callExternalFunction(), canDemoteGlobalVar(), checkInterfaceFunction(), CommitValueTo(), createCast(), llvm::createDeadArgHackingPass(), llvm::createMergeFunctionsPass(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::ExecutionEngine::emitGlobals(), llvm::AsmPrinter::EmitGlobalVariable(), llvm::ExecutionEngine::EmitGlobalVariable(), FindInitTrampoline(), ftostr(), FunctionNumber(), getComparePred(), getFunctionName(), llvm::SelectionDAG::getGlobalAddress(), llvm::GetGlobalTypeString(), llvm::JIT::getMemoryForGV(), llvm::Module::getOrInsertFunction(), llvm::Module::getOrInsertGlobal(), llvm::DataLayout::getPreferredAlignment(), llvm::SelectionDAG::InferPtrAlignment(), INITIALIZE_PASS(), InstallGlobalCtors(), IsBetterCannonical(), IsConstantOffsetFromGlobal(), llvm::HexagonTargetObjectFile::IsGlobalInSmallSection(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), llvm::SpecialCaseList::isIn(), isLeakCheckerRoot(), isLessConstraining(), isZeroLengthArray(), OptimizeGlobalAddressOfMalloc(), llvm::AssemblyWriter::printAlias(), llvm::AssemblyWriter::printGlobal(), llvm::LLParser::Run(), llvm::GlobalAlias::setAliasee(), llvm::GlobalVariable::setInitializer(), SRAGlobal(), TryToShrinkGlobalToBoolean(), llvm::ObjectSizeOffsetVisitor::visitGlobalVariable(), and llvm::ExecutionEngine::~ExecutionEngine().
VisibilityTypes llvm::GlobalValue::getVisibility () const inline
Definition at line 87 of file GlobalValue.h.
References Visibility.
Referenced by ConvertAtomicSynchScope(), copyAttributesFrom(), createCast(), llvm::AsmPrinter::doFinalization(), llvm::AsmPrinter::EmitFunctionHeader(), llvm::AsmPrinter::EmitGlobalVariable(), ftostr(), getEncodedVisibility(), isLessConstraining(), llvm::AssemblyWriter::printAlias(), llvm::AssemblyWriter::printFunction(), and llvm::AssemblyWriter::printGlobal().
static LinkageTypes llvm::GlobalValue::getWeakLinkage (bool ODR) inline static
Definition at line 114 of file GlobalValue.h.
References WeakAnyLinkage, and WeakODRLinkage.
bool llvm::GlobalValue::hasAppendingLinkage () const inline
Definition at line 204 of file GlobalValue.h.
References isAppendingLinkage(), and Linkage.
Referenced by llvm::NVPTXAsmPrinter::doFinalization(), llvm::ExecutionEngine::emitGlobals(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), and isLessConstraining().
bool llvm::GlobalValue::hasAvailableExternallyLinkage () const inline
Definition at line 195 of file GlobalValue.h.
References isAvailableExternallyLinkage(), and Linkage.
Referenced by llvm::X86Subtarget::ClassifyGlobalReference(), llvm::createMergeFunctionsPass(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), getComparePred(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::JIT::getOrEmitGlobalVariable(), llvm::JIT::getPointerToFunction(), llvm::MCJIT::getPointerToFunction(), llvm::ARMSubtarget::GVIsIndirectSymbol(), isDeclaration(), llvm::HexagonTargetObjectFile::IsGlobalInSmallSection(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), isLessConstraining(), isNonGhostDeclaration(), llvm::JIT::runJITOnFunction(), shouldInternalize(), and stripRegisterPrefix().
bool llvm::GlobalValue::hasCommonLinkage () const inline
Definition at line 215 of file GlobalValue.h.
References isCommonLinkage(), and Linkage.
Referenced by canBeHidden(), llvm::X86Subtarget::ClassifyGlobalReference(), getComparePred(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::ARMSubtarget::GVIsIndirectSymbol(), llvm::PPCSubtarget::hasLazyResolverStub(), isLessConstraining(), and stripRegisterPrefix().
bool llvm::GlobalValue::hasDefaultVisibility () const inline
Definition at line 88 of file GlobalValue.h.
References DefaultVisibility, and Visibility.
Referenced by bindsLocally(), llvm::X86Subtarget::ClassifyGlobalReference(), computeBytesPoppedByCallee(), and EmitTailCallStoreRetAddr().
bool llvm::GlobalValue::hasDLLExportLinkage () const inline
Definition at line 213 of file GlobalValue.h.
References isDLLExportLinkage(), and Linkage.
Referenced by llvm::ExecutionEngine::emitGlobals(), and isLessConstraining().
bool llvm::GlobalValue::hasDLLImportLinkage () const inline
Definition at line 212 of file GlobalValue.h.
References isDLLImportLinkage(), and Linkage.
Referenced by llvm::X86Subtarget::ClassifyGlobalReference(), llvm::ExecutionEngine::emitGlobals(), EmitTailCallStoreRetAddr(), and isLessConstraining().
bool llvm::GlobalValue::hasExternalLinkage () const inline
Definition at line 194 of file GlobalValue.h.
References isExternalLinkage(), and Linkage.
Referenced by canBeHidden(), llvm::createMergeFunctionsPass(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::ExecutionEngine::emitGlobals(), llvm::TargetLoweringObjectFile::getKindForGlobal(), isLessConstraining(), llvm::AssemblyWriter::printGlobal(), llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal(), and TryToShrinkGlobalToBoolean().
bool llvm::GlobalValue::hasExternalWeakLinkage () const inline
Definition at line 214 of file GlobalValue.h.
References isExternalWeakLinkage(), and Linkage.
Referenced by canBeHidden(), llvm::ExecutionEngine::emitGlobals(), llvm::JIT::getPointerToFunction(), llvm::MCJIT::getPointerToFunction(), and isLessConstraining().
bool llvm::GlobalValue::hasHiddenVisibility () const inline
Definition at line 89 of file GlobalValue.h.
References HiddenVisibility, and Visibility.
Referenced by canBeHidden(), llvm::X86Subtarget::ClassifyGlobalReference(), EmitTailCallStoreRetAddr(), getComparePred(), llvm::ARMTargetLowering::getJumpTableEncoding(), getModifierVariantKind(), llvm::TargetMachine::getTLSModel(), llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference(), llvm::AArch64Subtarget::GVIsIndirectSymbol(), llvm::ARMSubtarget::GVIsIndirectSymbol(), llvm::PPCSubtarget::hasLazyResolverStub(), and stripRegisterPrefix().
bool llvm::GlobalValue::hasInternalLinkage () const inline
Definition at line 205 of file GlobalValue.h.
References isInternalLinkage(), and Linkage.
Referenced by canDemoteGlobalVar(), getModifierVariantKind(), llvm::MipsTargetLowering::getOpndList(), GetSymbolFromOperand(), llvm::X86AsmPrinter::printSymbolOperand(), llvm::X86AsmPrinter::runOnMachineFunction(), and stripRegisterPrefix().
bool llvm::GlobalValue::hasLinkerPrivateLinkage () const inline
Definition at line 207 of file GlobalValue.h.
References isLinkerPrivateLinkage(), and Linkage.
Referenced by llvm::Mangler::getNameWithPrefix().
bool llvm::GlobalValue::hasLinkerPrivateWeakLinkage () const inline
Definition at line 208 of file GlobalValue.h.
References isLinkerPrivateWeakLinkage(), and Linkage.
Referenced by canBeHidden(), and llvm::Mangler::getNameWithPrefix().
bool llvm::GlobalValue::hasLinkOnceLinkage () const inline
Definition at line 198 of file GlobalValue.h.
References isLinkOnceLinkage(), and Linkage.
Referenced by canBeHidden(), llvm::PPCSubtarget::hasLazyResolverStub(), isLessConstraining(), and makeVisible().
bool llvm::GlobalValue::hasLocalLinkage () const inline
Definition at line 211 of file GlobalValue.h.
References isLocalLinkage(), and Linkage.
Referenced by AddressIsTaken(), bindsLocally(), llvm::CallGraph::CallGraph(), llvm::X86Subtarget::ClassifyGlobalReference(), computeBytesPoppedByCallee(), llvm::createArgumentPromotionPass(), createCast(), llvm::createDeadArgHackingPass(), llvm::createGlobalsModRefPass(), llvm::createMergeFunctionsPass(), llvm::createPPCCTRLoopsVerify(), llvm::ExecutionEngine::emitGlobals(), EmitTailCallStoreRetAddr(), forceRenaming(), llvm::TargetLoweringObjectFileMachO::getCFIPersonalitySymbol(), getComparePred(), llvm::Inliner::getInlineThreshold(), getIntrinsicIDForCall(), llvm::ARMTargetLowering::getJumpTableEncoding(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::Module::getOrInsertFunction(), llvm::TargetTransformInfo::getReductionCost(), llvm::TargetMachine::getTLSModel(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference(), llvm::AArch64Subtarget::GVIsIndirectSymbol(), llvm::ARMSubtarget::GVIsIndirectSymbol(), hasUsesToReplace(), IsBetterCannonical(), isLessConstraining(), makeVisible(), mayHaveOtherReferences(), NumRetVals(), RemoveNestAttribute(), llvm::Inliner::runOnSCC(), llvm::ExecutionEngine::runStaticConstructorsDestructors(), llvm::FastISel::SelectInstruction(), llvm::TargetLoweringObjectFileMachO::shouldEmitUsedDirectiveFor(), shouldInternalize(), SRAGlobal(), and TryToShrinkGlobalToBoolean().
bool llvm::GlobalValue::hasPrivateLinkage () const inline
Definition at line 206 of file GlobalValue.h.
References isPrivateLinkage(), and Linkage.
Referenced by llvm::NVPTXAsmPrinter::doFinalization(), llvm::Mangler::getNameWithPrefix(), and isLeakCheckerRoot().
bool llvm::GlobalValue::hasProtectedVisibility () const inline
Definition at line 90 of file GlobalValue.h.
References ProtectedVisibility, and Visibility.
Referenced by canBeHidden(), and EmitTailCallStoreRetAddr().
bool llvm::GlobalValue::hasSection () const inline
Definition at line 95 of file GlobalValue.h.
Referenced by checkInterfaceFunction(), ConvertAtomicSynchScope(), llvm::NVPTXAsmPrinter::doFinalization(), ftostr(), getGVAlignmentLog2(), IsBetterCannonical(), LTOModule::makeLTOModule(), llvm::AssemblyWriter::printFunction(), llvm::AssemblyWriter::printGlobal(), and llvm::TargetLoweringObjectFile::SectionForGlobal().
bool llvm::GlobalValue::hasUnnamedAddr () const inline
Definition at line 84 of file GlobalValue.h.
References UnnamedAddr.
Referenced by canBeHidden(), copyAttributesFrom(), llvm::createMergeFunctionsPass(), llvm::AsmPrinter::doInitialization(), llvm::TargetLoweringObjectFile::getKindForGlobal(), IsBetterCannonical(), isLessConstraining(), llvm::AssemblyWriter::printFunction(), llvm::AssemblyWriter::printGlobal(), and TryToShrinkGlobalToBoolean().
bool llvm::GlobalValue::hasWeakLinkage () const inline
Definition at line 201 of file GlobalValue.h.
References isWeakLinkage(), and Linkage.
Referenced by canBeHidden(), llvm::createMergeFunctionsPass(), llvm::PPCSubtarget::hasLazyResolverStub(), and isLessConstraining().
static bool llvm::GlobalValue::isAppendingLinkage (LinkageTypes Linkage) inline static
Definition at line 130 of file GlobalValue.h.
References AppendingLinkage.
Referenced by hasAppendingLinkage().
static bool llvm::GlobalValue::isAvailableExternallyLinkage (LinkageTypes Linkage) inline static
Definition at line 121 of file GlobalValue.h.
References AvailableExternallyLinkage.
Referenced by hasAvailableExternallyLinkage().
static bool llvm::GlobalValue::isCommonLinkage (LinkageTypes Linkage) inline static
Definition at line 158 of file GlobalValue.h.
References CommonLinkage.
Referenced by hasCommonLinkage().
bool GlobalValue::isDeclaration () const
isDeclaration - Return true if the primary definition of this global value is outside of the current translation unit.
Definition at line 66 of file Globals.cpp.
References F().
Referenced by AddressIsTaken(), assureFPCallStub(), llvm::Interpreter::callFunction(), llvm::CallGraph::CallGraph(), llvm::X86Subtarget::ClassifyGlobalReference(), CommitValueTo(), LTOCodeGenerator::compile(), computeBytesPoppedByCallee(), ConvertAtomicSynchScope(), llvm::createAlwaysInlinerPass(), llvm::createDeadArgHackingPass(), llvm::createFunctionAttrsPass(), llvm::createGlobalsModRefPass(), llvm::createMergeFunctionsPass(), llvm::createPruneEHPass(), cxxDtorIsEmpty(), determinePointerReadAttrs(), llvm::AsmPrinter::doFinalization(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::ExecutionEngine::emitGlobals(), llvm::AsmPrinter::EmitGlobalVariable(), EmitTailCallStoreRetAddr(), llvm::AnalysisResolver::findImplPass(), FindInitTrampoline(), llvm::MCJIT::findModuleForSymbol(), FPCCToARMCC(), getArrayElements(), getCalledFunction(), llvm::GCModuleInfo::getFunctionInfo(), llvm::Inliner::getInlineThreshold(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::JIT::getOrEmitGlobalVariable(), llvm::JIT::getPointerToFunction(), llvm::MCJIT::getPointerToFunction(), getRealLinkageName(), llvm::TargetMachine::getTLSModel(), llvm::ARMSubtarget::GVIsIndirectSymbol(), llvm::GlobalVariable::hasInitializer(), llvm::PPCSubtarget::hasLazyResolverStub(), INITIALIZE_PASS(), llvm::InlineFunction(), isContiguous(), isDeclaration(), llvm::BitcodeReader::isDematerializable(), llvm::isFreeCall(), llvm::HexagonTargetObjectFile::IsGlobalInSmallSection(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), isLessConstraining(), llvm::BitcodeReader::isMaterializable(), isNonGhostDeclaration(), llvm::TargetLowering::isOffsetFoldingLegal(), llvm::lintFunction(), llvm::AssemblyWriter::printFunction(), llvm::Inliner::removeDeadFunctions(), RemoveNestAttribute(), llvm::FPPassManager::runOnFunction(), llvm::Mips16HardFloat::runOnModule(), llvm::MipsOs16::runOnModule(), llvm::Inliner::runOnSCC(), llvm::ExecutionEngine::runStaticConstructorsDestructors(), shouldInternalize(), stripRegisterPrefix(), useFuncSeen(), llvm::verifyFunction(), and llvm::Interpreter::visitCallSite().
bool GlobalValue::isDematerializable () const
isDematerializable - Returns true if this function was loaded from a GVMaterializer that's still attached to its Module and that knows how to dematerialize the function.
Definition at line 33 of file Globals.cpp.
References getParent(), and llvm::Module::isDematerializable().
Referenced by getRealLinkageName().
static bool llvm::GlobalValue::isDiscardableIfUnused (LinkageTypes Linkage) inline static
isDiscardableIfUnused - Whether the definition of this global may be discarded if it is not used in its compilation unit.
Definition at line 164 of file GlobalValue.h.
References isLinkOnceLinkage(), and isLocalLinkage().
Referenced by makeVisible(), and TryToShrinkGlobalToBoolean().
bool llvm::GlobalValue::isDiscardableIfUnused () const inline
Definition at line 220 of file GlobalValue.h.
References Linkage.
static bool llvm::GlobalValue::isDLLExportLinkage (LinkageTypes Linkage) inline static
Definition at line 152 of file GlobalValue.h.
References DLLExportLinkage.
Referenced by hasDLLExportLinkage().
static bool llvm::GlobalValue::isDLLImportLinkage (LinkageTypes Linkage) inline static
Definition at line 149 of file GlobalValue.h.
References DLLImportLinkage.
Referenced by hasDLLImportLinkage().
static bool llvm::GlobalValue::isExternalLinkage (LinkageTypes Linkage) inline static
Definition at line 118 of file GlobalValue.h.
References ExternalLinkage.
Referenced by hasExternalLinkage(), and llvm::GlobalAlias::isValidLinkage().
static bool llvm::GlobalValue::isExternalWeakLinkage (LinkageTypes Linkage) inline static
Definition at line 155 of file GlobalValue.h.
References ExternalWeakLinkage.
Referenced by hasExternalWeakLinkage().
static bool llvm::GlobalValue::isInternalLinkage (LinkageTypes Linkage) inline static
Definition at line 133 of file GlobalValue.h.
References InternalLinkage.
Referenced by hasInternalLinkage(), and isLocalLinkage().
static bool llvm::GlobalValue::isLinkerPrivateLinkage (LinkageTypes Linkage) inline static
Definition at line 139 of file GlobalValue.h.
References LinkerPrivateLinkage.
Referenced by hasLinkerPrivateLinkage(), and isLocalLinkage().
static bool llvm::GlobalValue::isLinkerPrivateWeakLinkage (LinkageTypes Linkage) inline static
Definition at line 142 of file GlobalValue.h.
References LinkerPrivateWeakLinkage.
Referenced by hasLinkerPrivateWeakLinkage(), and isLocalLinkage().
static bool llvm::GlobalValue::isLinkOnceLinkage (LinkageTypes Linkage) inline static
Definition at line 124 of file GlobalValue.h.
References LinkOnceAnyLinkage, and LinkOnceODRLinkage.
Referenced by hasLinkOnceLinkage(), isDiscardableIfUnused(), and llvm::GlobalAlias::isValidLinkage().
static bool llvm::GlobalValue::isLocalLinkage (LinkageTypes Linkage) inline static
Definition at line 145 of file GlobalValue.h.
References isInternalLinkage(), isLinkerPrivateLinkage(), isLinkerPrivateWeakLinkage(), and isPrivateLinkage().
Referenced by hasLocalLinkage(), isDiscardableIfUnused(), and llvm::GlobalAlias::isValidLinkage().
bool GlobalValue::isMaterializable () const
isMaterializable - If this function's Module is being lazily streamed in functions from disk or some other source, this method can be used to check to see if the function has been read in yet or not.
Definition at line 30 of file Globals.cpp.
References getParent(), and llvm::Module::isMaterializable().
Referenced by llvm::X86Subtarget::ClassifyGlobalReference(), getArrayElements(), getRealLinkageName(), llvm::ARMSubtarget::GVIsIndirectSymbol(), llvm::PPCSubtarget::hasLazyResolverStub(), isDeclaration(), isLessConstraining(), isNonGhostDeclaration(), llvm::BitcodeReader::Materialize(), llvm::BitcodeReader::MaterializeModule(), llvm::AssemblyWriter::printAlias(), llvm::AssemblyWriter::printFunction(), llvm::AssemblyWriter::printGlobal(), and llvm::legacy::FunctionPassManager::run().
static bool llvm::GlobalValue::isPrivateLinkage (LinkageTypes Linkage) inline static
Definition at line 136 of file GlobalValue.h.
References PrivateLinkage.
Referenced by hasPrivateLinkage(), and isLocalLinkage().
static bool llvm::GlobalValue::isWeakForLinker (LinkageTypes Linkage) inline static
isWeakForLinker - Whether the definition of this global may be replaced at link time. NB: Using this method outside of the code generators is almost always a mistake: when working at the IR level use mayBeOverridden instead as it knows about ODR semantics.
Definition at line 183 of file GlobalValue.h.
References AvailableExternallyLinkage, CommonLinkage, ExternalWeakLinkage, LinkerPrivateWeakLinkage, LinkOnceAnyLinkage, LinkOnceODRLinkage, WeakAnyLinkage, and WeakODRLinkage.
Referenced by llvm::X86Subtarget::ClassifyGlobalReference(), computeBytesPoppedByCallee(), llvm::createDeadArgHackingPass(), llvm::AsmPrinter::EmitJumpTableInfo(), EmitTailCallStoreRetAddr(), FPCCToARMCC(), llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), llvm::ARMSubtarget::GVIsIndirectSymbol(), IsBetterCannonical(), isLessConstraining(), llvm::TargetLowering::isOffsetFoldingLegal(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), and stripRegisterPrefix().
bool llvm::GlobalValue::isWeakForLinker () const inline
Definition at line 226 of file GlobalValue.h.
References copyAttributesFrom(), isWeakForLinker(), and Linkage.
Referenced by llvm::GlobalVariable::hasUniqueInitializer(), and isWeakForLinker().
static bool llvm::GlobalValue::isWeakLinkage (LinkageTypes Linkage) inline static
Definition at line 127 of file GlobalValue.h.
References WeakAnyLinkage, and WeakODRLinkage.
Referenced by hasWeakLinkage(), and llvm::GlobalAlias::isValidLinkage().
bool GlobalValue::Materialize (std::string * ErrInfo = 0)
Materialize - make sure this GlobalValue is fully read. If the module is corrupt, this returns true and fills in the optional string with information about the problem. If successful, this returns false.
Definition at line 36 of file Globals.cpp.
References getParent(), and llvm::Module::Materialize().
Referenced by getArrayElements(), llvm::JIT::getPointerToFunction(), getRealLinkageName(), llvm::BitcodeReader::materializeForwardReferencedFunctions(), and llvm::legacy::FunctionPassManager::run().
static bool llvm::GlobalValue::mayBeOverridden (LinkageTypes Linkage) inline static
mayBeOverridden - Whether the definition of this global may be replaced by something non-equivalent at link time. For example, if a function has weak linkage then the code defining it may be replaced by different code.
Definition at line 171 of file GlobalValue.h.
References CommonLinkage, ExternalWeakLinkage, LinkerPrivateWeakLinkage, LinkOnceAnyLinkage, and WeakAnyLinkage.
Referenced by AddressIsTaken(), CommitValueTo(), createCast(), llvm::createDeadArgHackingPass(), llvm::createFunctionAttrsPass(), llvm::createMergeFunctionsPass(), llvm::createPruneEHPass(), determinePointerReadAttrs(), llvm::InlineCostAnalysis::getInlineCost(), INITIALIZE_PASS(), and llvm::ObjectSizeOffsetVisitor::visitGlobalAlias().
bool llvm::GlobalValue::mayBeOverridden () const inline
Definition at line 224 of file GlobalValue.h.
References Linkage, and mayBeOverridden().
Referenced by llvm::GlobalVariable::hasDefinitiveInitializer(), mayBeOverridden(), and llvm::GlobalAlias::resolveAliasedGlobal().
virtual void llvm::GlobalValue::removeFromParent () pure virtual
removeFromParent - This method unlinks 'this' from the containing module, but does not delete it.
Implemented in llvm::Function, llvm::GlobalVariable, and llvm::GlobalAlias.
Referenced by getRealLinkageName().
void GlobalValue::setAlignment (unsigned Align)
Definition at line 58 of file Globals.cpp.
References Alignment, getAlignment(), and llvm::Log2_32().
Referenced by checkInterfaceFunction(), copyAttributesFrom(), copyGVAttributes(), createCast(), FunctionNumber(), getAlignment(), getMemSetPatternValue(), ReadWideAPInt(), llvm::LLParser::Run(), and SRAGlobal().
void llvm::GlobalValue::setLinkage (LinkageTypes LT) inline
Definition at line 217 of file GlobalValue.h.
References Linkage, and llvm::A64CC::LT.
Referenced by createCast(), FunctionNumber(), getFunctionName(), hasUsesToReplace(), INITIALIZE_PASS(), isLessConstraining(), LLVMSetLinkage(), makeVisible(), ReadWideAPInt(), RemoveNestAttribute(), and llvm::LLParser::Run().
void llvm::GlobalValue::setSection (StringRef S) inline
Definition at line 97 of file GlobalValue.h.
References S, and use_empty_except_constants().
Referenced by assureFPCallStub(), checkInterfaceFunction(), copyAttributesFrom(), createFPFnStub(), FunctionNumber(), ReadWideAPInt(), llvm::LLParser::Run(), and setUsedInitializer().
void llvm::GlobalValue::setUnnamedAddr (bool Val) inline
Definition at line 85 of file GlobalValue.h.
References UnnamedAddr.
Referenced by checkInterfaceFunction(), copyAttributesFrom(), llvm::IRBuilderBase::CreateGlobalString(), createPrivateGlobalForString(), FunctionNumber(), getFunctionName(), getMemSetPatternValue(), IsBetterCannonical(), isLessConstraining(), ReadWideAPInt(), llvm::LLParser::Run(), and TryToShrinkGlobalToBoolean().
void llvm::GlobalValue::setVisibility (VisibilityTypes V) inline
Definition at line 93 of file GlobalValue.h.
References Visibility.
Referenced by copyAttributesFrom(), createPrivateNonConstGlobalForString(), FunctionNumber(), isLessConstraining(), makeVisible(), ReadWideAPInt(), and llvm::LLParser::Run().
bool llvm::GlobalValue::use_empty_except_constants ()
Determine if the usage of this global value is empty except for transitively dead constants.
If the usage is empty (except transitively dead constants), then this global value can be safely deleted since the destructor will delete the dead constants as well.
Referenced by setSection().
Member Data Documentation
unsigned llvm::GlobalValue::Alignment protected
Definition at line 70 of file GlobalValue.h.
Referenced by getAlignment(), and setAlignment().
LinkageTypes llvm::GlobalValue::Linkage protected
Definition at line 68 of file GlobalValue.h.
Referenced by getLinkage(), hasAppendingLinkage(), hasAvailableExternallyLinkage(), hasCommonLinkage(), hasDLLExportLinkage(), hasDLLImportLinkage(), hasExternalLinkage(), hasExternalWeakLinkage(), hasInternalLinkage(), hasLinkerPrivateLinkage(), hasLinkerPrivateWeakLinkage(), hasLinkOnceLinkage(), hasLocalLinkage(), hasPrivateLinkage(), hasWeakLinkage(), isDiscardableIfUnused(), isWeakForLinker(), mayBeOverridden(), llvm::GlobalAlias::operator new(), and setLinkage().
Module* llvm::GlobalValue::Parent protected
Definition at line 72 of file GlobalValue.h.
Referenced by getParent(), llvm::GlobalAlias::GlobalAlias(), llvm::GlobalVariable::GlobalVariable(), and llvm::GlobalAlias::operator new().
std::string llvm::GlobalValue::Section protected
Definition at line 73 of file GlobalValue.h.
Referenced by getSection().
unsigned llvm::GlobalValue::UnnamedAddr protected
Definition at line 71 of file GlobalValue.h.
Referenced by hasUnnamedAddr(), and setUnnamedAddr().
unsigned llvm::GlobalValue::Visibility protected
Definition at line 69 of file GlobalValue.h.
Referenced by getVisibility(), hasDefaultVisibility(), hasHiddenVisibility(), hasProtectedVisibility(), and setVisibility().
The documentation for this class was generated from the following files:
GlobalValue.h
Globals.cpp