LLVM: llvm::ResourcePriorityQueue Class Reference
LLVM API Documentation
llvm::ResourcePriorityQueue Class Reference
#include <ResourcePriorityQueue.h>
Public Member Functions
ResourcePriorityQueue (SelectionDAGISel *IS)
~ResourcePriorityQueue ()
bool isBottomUp () const
void initNodes (std::vector< SUnit > &sunits)
void addNode (const SUnit *SU)
void updateNode (const SUnit *SU)
void releaseState ()
unsigned getLatency (unsigned NodeNum) const
unsigned getNumSolelyBlockNodes (unsigned NodeNum) const
signed SUSchedulingCost (SUnit *SU)
void initNumRegDefsLeft (SUnit *SU)
void updateNumRegDefsLeft (SUnit *SU)
signed regPressureDelta (SUnit *SU, bool RawPressure=false)
signed rawRegPressureDelta (SUnit *SU, unsigned RCId)
bool empty () const
virtual void push (SUnit *U)
virtual SUnit * pop ()
virtual void remove (SUnit *SU)
virtual void dump (ScheduleDAG *DAG) const
void scheduledNode (SUnit *Node)
scheduledNode - Main resource tracking point.
bool isResourceAvailable (SUnit *SU)
void reserveResources (SUnit *SU)
Keep track of available resources.
Public Member Functions inherited from llvm::SchedulingPriorityQueue
SchedulingPriorityQueue (bool rf=false)
virtual ~SchedulingPriorityQueue ()
bool hasReadyFilter () const
virtual bool tracksRegPressure () const
virtual bool isReady (SUnit *) const
void push_all (const std::vector< SUnit * > &Nodes)
virtual void unscheduledNode (SUnit *)
void setCurCycle (unsigned Cycle)
unsigned getCurCycle () const
Detailed Description
Definition at line 38 of file ResourcePriorityQueue.h.
Constructor & Destructor Documentation
ResourcePriorityQueue::ResourcePriorityQueue (SelectionDAGISel * IS)
Definition at line 43 of file ResourcePriorityQueue.cpp.
References llvm::ISD::CopyFromReg, llvm::ISD::CopyToReg, llvm::TargetInstrInfo::CreateTargetScheduleState(), llvm::TargetRegisterClass::getID(), llvm::TargetMachine::getInstrInfo(), llvm::SDValue::getNode(), llvm::SUnit::getNode(), llvm::SDNode::getNumOperands(), llvm::TargetRegisterInfo::getNumRegClasses(), llvm::SDNode::getNumValues(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getRegClassFor(), llvm::TargetMachine::getRegisterInfo(), llvm::TargetRegisterInfo::getRegPressureLimit(), llvm::SDValue::getResNo(), llvm::SDNode::getSimpleValueType(), llvm::SelectionDAGISel::getTargetLowering(), llvm::TargetLoweringBase::getTargetMachine(), i, I, llvm::ISD::INLINEASM, llvm::SDNode::isMachineOpcode(), llvm::TargetLoweringBase::isTypeLegal(), llvm::SelectionDAGISel::MF, llvm::SUnit::Preds, llvm::TargetRegisterInfo::regclass_begin(), llvm::TargetRegisterInfo::regclass_end(), llvm::SUnit::Succs, and llvm::ISD::TokenFactor.
llvm::ResourcePriorityQueue::~ResourcePriorityQueue () inline
Definition at line 80 of file ResourcePriorityQueue.h.
Member Function Documentation
void llvm::ResourcePriorityQueue::addNode (const SUnit * SU) inline virtual
Implements llvm::SchedulingPriorityQueue.
Definition at line 88 of file ResourcePriorityQueue.h.
void ResourcePriorityQueue::dump (ScheduleDAG * DAG) const virtual
Reimplemented from llvm::SchedulingPriorityQueue.
Definition at line 646 of file ResourcePriorityQueue.cpp.
References llvm::dbgs(), llvm::SUnit::dump(), empty(), llvm::SUnit::getHeight(), and pop().
Referenced by remove().
bool llvm::ResourcePriorityQueue::empty () const inline virtual
Implements llvm::SchedulingPriorityQueue.
Definition at line 119 of file ResourcePriorityQueue.h.
References llvm::dump(), and getSingleUnscheduledPred().
Referenced by dump(), and pop().
unsigned llvm::ResourcePriorityQueue::getLatency (unsigned NodeNum) const inline
Definition at line 98 of file ResourcePriorityQueue.h.
unsigned llvm::ResourcePriorityQueue::getNumSolelyBlockNodes (unsigned NodeNum) const inline
Definition at line 103 of file ResourcePriorityQueue.h.
void ResourcePriorityQueue::initNodes (std::vector< SUnit > & sunits) virtual
Initialize nodes.
Implements llvm::SchedulingPriorityQueue.
Definition at line 169 of file ResourcePriorityQueue.cpp.
References i, initNumRegDefsLeft(), and llvm::SUnit::NodeQueueId.
void ResourcePriorityQueue::initNumRegDefsLeft (SUnit * SU)
InitNumRegDefsLeft - Determine the # of regs defined by this node.
Definition at line 548 of file ResourcePriorityQueue.cpp.
References llvm::ISD::CopyFromReg, llvm::MCInstrInfo::get(), llvm::SUnit::getNode(), llvm::MCInstrDesc::getNumDefs(), llvm::TargetOpcode::IMPLICIT_DEF, llvm::ISD::INLINEASM, llvm::SUnit::isAvailable, N, llvm::SUnit::NumRegDefsLeft, and push().
Referenced by initNodes().
bool llvm::ResourcePriorityQueue::isBottomUp () const inline virtual
Implements llvm::SchedulingPriorityQueue.
Definition at line 84 of file ResourcePriorityQueue.h.
bool ResourcePriorityQueue::isResourceAvailable (SUnit * SU)
Check if scheduling of this SU is possible in the current packet.
Definition at line 247 of file ResourcePriorityQueue.cpp.
References llvm::DFAPacketizer::canReserveResources(), llvm::TargetOpcode::EXTRACT_SUBREG, llvm::MCInstrInfo::get(), llvm::SDNode::getGluedNode(), llvm::SDNode::getMachineOpcode(), llvm::SUnit::getNode(), i, I, llvm::TargetOpcode::IMPLICIT_DEF, llvm::TargetOpcode::INSERT_SUBREG, llvm::SDNode::isMachineOpcode(), llvm::TargetOpcode::REG_SEQUENCE, and llvm::TargetOpcode::SUBREG_TO_REG.
Referenced by reserveResources(), and SUSchedulingCost().
SUnit * ResourcePriorityQueue::pop () virtual
Main access point - returns next instructions to be placed in scheduling sequence.
Implements llvm::SchedulingPriorityQueue.
Definition at line 599 of file ResourcePriorityQueue.cpp.
References DisableDFASched, empty(), I, llvm::next(), llvm::prior(), SUSchedulingCost(), and std::swap().
Referenced by dump().
void ResourcePriorityQueue::push (SUnit * U) virtual
Implements llvm::SchedulingPriorityQueue.
Definition at line 232 of file ResourcePriorityQueue.cpp.
References I, llvm::SUnit::NodeNum, and llvm::SUnit::Succs.
Referenced by initNumRegDefsLeft().
signed ResourcePriorityQueue::rawRegPressureDelta (SUnit * SU, unsigned RCId)
Definition at line 327 of file ResourcePriorityQueue.cpp.
References llvm::TargetRegisterClass::getID(), llvm::SDValue::getNode(), llvm::SUnit::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getNumValues(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getRegClassFor(), llvm::SDValue::getResNo(), llvm::SDNode::getSimpleValueType(), i, llvm::SDNode::isMachineOpcode(), and llvm::TargetLoweringBase::isTypeLegal().
Referenced by regPressureDelta().
signed ResourcePriorityQueue::regPressureDelta (SUnit * SU, bool RawPressure = false)
Estimates change in reg pressure from this SU. It is achieved by trivial tracking of defined and used vregs in dependent instructions. The RawPressure flag makes this function to ignore existing reg file sizes, and report raw def/use balance.
Definition at line 361 of file ResourcePriorityQueue.cpp.
References llvm::TargetRegisterClass::getID(), llvm::SUnit::getNode(), I, llvm::SDNode::isMachineOpcode(), rawRegPressureDelta(), llvm::TargetRegisterInfo::regclass_begin(), and llvm::TargetRegisterInfo::regclass_end().
Referenced by SUSchedulingCost().
void llvm::ResourcePriorityQueue::releaseState () inline virtual
Implements llvm::SchedulingPriorityQueue.
Definition at line 94 of file ResourcePriorityQueue.h.
void ResourcePriorityQueue::remove (SUnit * SU) virtual
Implements llvm::SchedulingPriorityQueue.
Definition at line 633 of file ResourcePriorityQueue.cpp.
References dump(), I, llvm::prior(), and std::swap().
void ResourcePriorityQueue::reserveResources (SUnit * SU)
Keep track of available resources.
Definition at line 290 of file ResourcePriorityQueue.cpp.
References llvm::DFAPacketizer::clearResources(), llvm::TargetOpcode::EXTRACT_SUBREG, llvm::MCInstrInfo::get(), llvm::SDNode::getGluedNode(), llvm::SDNode::getMachineOpcode(), llvm::SUnit::getNode(), llvm::TargetOpcode::IMPLICIT_DEF, llvm::TargetOpcode::INSERT_SUBREG, llvm::SDNode::isMachineOpcode(), isResourceAvailable(), llvm::MCSchedModel::IssueWidth, llvm::TargetOpcode::REG_SEQUENCE, llvm::DFAPacketizer::reserveResources(), llvm::InstrItineraryData::SchedModel, and llvm::TargetOpcode::SUBREG_TO_REG.
Referenced by scheduledNode().
void ResourcePriorityQueue::scheduledNode (SUnit * Node) virtual
scheduledNode - Main resource tracking point.
Main resource tracking point.
Reimplemented from llvm::SchedulingPriorityQueue.
Definition at line 472 of file ResourcePriorityQueue.cpp.
References llvm::DFAPacketizer::clearResources(), llvm::TargetRegisterClass::getID(), llvm::SDValue::getNode(), llvm::SUnit::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getNumValues(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getRegClassFor(), llvm::SDValue::getResNo(), llvm::SDNode::getSimpleValueType(), i, I, llvm::SDNode::isMachineOpcode(), llvm::TargetLoweringBase::isTypeLegal(), numberCtrlDepsInSU(), numberCtrlPredInSU(), llvm::SUnit::NumPreds, llvm::SUnit::NumRegDefsLeft, llvm::SUnit::Preds, reserveResources(), and llvm::SUnit::Succs.
signed ResourcePriorityQueue::SUSchedulingCost (SUnit * SU)
Single cost function reflecting benefit of scheduling SU in the current cycle.
Returns single number reflecting benefit of scheduling SU in the current cycle.
Definition at line 402 of file ResourcePriorityQueue.cpp.
References llvm::ISD::CopyFromReg, llvm::ISD::CopyToReg, llvm::MCInstrInfo::get(), llvm::SUnit::getHeight(), llvm::SUnit::getNode(), llvm::ISD::INLINEASM, llvm::MCInstrDesc::isCall(), isResourceAvailable(), llvm::SUnit::isScheduled, llvm::SUnit::isScheduleHigh, N, llvm::SUnit::NodeNum, PriorityFour, PriorityOne, PriorityThree, regPressureDelta(), RegPressureThreshold, ScaleOne, ScaleTwo, and llvm::ISD::TokenFactor.
Referenced by pop().
void llvm::ResourcePriorityQueue::updateNode (const SUnit * SU) inline virtual
Implements llvm::SchedulingPriorityQueue.
Definition at line 92 of file ResourcePriorityQueue.h.
void llvm::ResourcePriorityQueue::updateNumRegDefsLeft (SUnit * SU)
The documentation for this class was generated from the following files:
ResourcePriorityQueue.h
ResourcePriorityQueue.cpp