LLVM: llvm::LLParser Class Reference
LLVM API Documentation
llvm::LLParser Class Reference
#include <LLParser.h>
Public Types
typedef LLLexer::LocTy LocTy
Public Member Functions
LLParser (MemoryBuffer *F, SourceMgr &SM, SMDiagnostic &Err, Module *m)
bool Run ()
Run: module ::= toplevelentity*.
LLVMContext & getContext ()
Detailed Description
Definition at line 86 of file LLParser.h.
Member Typedef Documentation
typedef LLLexer::LocTy llvm::LLParser::LocTy
Definition at line 88 of file LLParser.h.
Constructor & Destructor Documentation
llvm::LLParser::LLParser (MemoryBuffer * F, SourceMgr & SM, SMDiagnostic & Err, Module * m) inline
Definition at line 135 of file LLParser.h.
Member Function Documentation
LLVMContext& llvm::LLParser::getContext () inline
Definition at line 140 of file LLParser.h.
References B, BB, CC, llvm::lltok::Error, llvm::LLLexer::Error(), f(), F(), FunctionNumber(), llvm::LLLexer::getKind(), llvm::LLLexer::getLoc(), I, isAtomic(), llvm::lltok::kw_arcp, llvm::lltok::kw_fast, llvm::lltok::kw_ninf, llvm::lltok::kw_nnan, llvm::lltok::kw_nsz, llvm::LLLexer::Lex(), llvm::ValID::Loc, N, p, P, llvm::FastMathFlags::setAllowReciprocal(), llvm::FastMathFlags::setNoInfs(), llvm::FastMathFlags::setNoNaNs(), llvm::FastMathFlags::setNoSignedZeros(), llvm::FastMathFlags::setUnsafeAlgebra(), T, and TLM.
bool LLParser::Run ()
Run: module ::= toplevelentity*.
Definition at line 38 of file LLParser.cpp.
References llvm::AttrBuilder::addAlignmentAttr(), llvm::AttrBuilder::addAttribute(), llvm::AttributeSet::addAttributes(), llvm::NamedMDNode::addOperand(), llvm::AttrBuilder::addStackAlignmentAttr(), llvm::Attribute::Alignment, llvm::Attribute::AlwaysInline, llvm::Module::appendModuleInlineAsm(), llvm::lltok::APSInt, llvm::lltok::AttrGrpID, B, llvm::Module::begin(), llvm::Attribute::Builtin, llvm::AttrBuilder::clear(), llvm::Attribute::Cold, llvm::lltok::comma, llvm::ValID::ConstantVal, llvm::Function::Create(), llvm::MDNode::deleteTemporary(), llvm::GlobalValue::DLLImportLinkage, llvm::dyn_cast(), llvm::Module::end(), llvm::lltok::Eof, llvm::lltok::equal, llvm::lltok::exclaim, llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::ExternalWeakLinkage, F(), llvm::MDString::get(), llvm::MDNode::get(), llvm::BlockAddress::get(), llvm::PointerType::getAddressSpace(), llvm::Module::getAliasList(), llvm::LLLexer::getAPSIntVal(), llvm::SequentialType::getElementType(), llvm::AttributeSet::getFnAttributes(), llvm::Module::getFunction(), llvm::Module::getGlobalList(), llvm::LLLexer::getKind(), llvm::APInt::getLimitedValue(), llvm::LLLexer::getLoc(), llvm::Value::getName(), llvm::Module::getNamedValue(), llvm::Module::getOrInsertNamedMetadata(), llvm::LLLexer::getStrVal(), llvm::MDNode::getTemporary(), llvm::GlobalValue::getType(), llvm::Value::getType(), getTypeString(), llvm::LLLexer::getUIntVal(), llvm::Function::getValueSymbolTable(), llvm::Module::getValueSymbolTable(), llvm::Module::global_end(), llvm::lltok::GlobalID, llvm::lltok::GlobalVar, i, I, llvm::GlobalVariable::InitialExecTLSModel, llvm::Attribute::InlineHint, llvm::Type::isFunctionTy(), llvm::Type::isLabelTy(), llvm::Type::isPointerTy(), llvm::APSInt::isSigned(), llvm::GlobalAlias::isValidLinkage(), llvm::ValID::Kind, llvm::lltok::kw_addrspace, llvm::lltok::kw_alias, llvm::lltok::kw_align, llvm::lltok::kw_alignstack, llvm::lltok::kw_alwaysinline, llvm::lltok::kw_appending, llvm::lltok::kw_asm, llvm::lltok::kw_attributes, llvm::lltok::kw_bitcast, llvm::lltok::kw_builtin, llvm::lltok::kw_byval, llvm::lltok::kw_cold, llvm::lltok::kw_common, llvm::lltok::kw_constant, llvm::lltok::kw_datalayout, llvm::lltok::kw_declare, llvm::lltok::kw_default, llvm::lltok::kw_define, llvm::lltok::kw_deplibs, llvm::lltok::kw_dllexport, llvm::lltok::kw_dllimport, llvm::lltok::kw_extern_weak, llvm::lltok::kw_external, llvm::lltok::kw_externally_initialized, llvm::lltok::kw_getelementptr, llvm::lltok::kw_global, llvm::lltok::kw_hidden, llvm::lltok::kw_initialexec, llvm::lltok::kw_inlinehint, llvm::lltok::kw_inreg, llvm::lltok::kw_internal, llvm::lltok::kw_linker_private, llvm::lltok::kw_linker_private_weak, llvm::lltok::kw_linkonce, llvm::lltok::kw_linkonce_odr, llvm::lltok::kw_localdynamic, llvm::lltok::kw_localexec, llvm::lltok::kw_minsize, llvm::lltok::kw_module, llvm::lltok::kw_naked, llvm::lltok::kw_nest, llvm::lltok::kw_noalias, llvm::lltok::kw_nobuiltin, llvm::lltok::kw_nocapture, llvm::lltok::kw_noduplicate, llvm::lltok::kw_noimplicitfloat, llvm::lltok::kw_noinline, llvm::lltok::kw_nonlazybind, llvm::lltok::kw_noredzone, llvm::lltok::kw_noreturn, llvm::lltok::kw_nounwind, llvm::lltok::kw_optnone, llvm::lltok::kw_optsize, llvm::lltok::kw_private, llvm::lltok::kw_protected, llvm::lltok::kw_readnone, llvm::lltok::kw_readonly, llvm::lltok::kw_returned, llvm::lltok::kw_returns_twice, llvm::lltok::kw_sanitize_address, llvm::lltok::kw_sanitize_memory, llvm::lltok::kw_sanitize_thread, llvm::lltok::kw_section, llvm::lltok::kw_signext, llvm::lltok::kw_sret, llvm::lltok::kw_ssp, llvm::lltok::kw_sspreq, llvm::lltok::kw_sspstrong, llvm::lltok::kw_target, llvm::lltok::kw_thread_local, llvm::lltok::kw_triple, llvm::lltok::kw_type, llvm::lltok::kw_unnamed_addr, llvm::lltok::kw_uwtable, llvm::lltok::kw_weak, llvm::lltok::kw_weak_odr, llvm::lltok::kw_zeroext, llvm::lltok::lbrace, llvm::LLLexer::Lex(), llvm_unreachable, llvm::ValID::Loc, llvm::GlobalVariable::LocalDynamicTLSModel, llvm::GlobalVariable::LocalExecTLSModel, llvm::lltok::LocalVar, llvm::lltok::LocalVarID, llvm::ValueSymbolTable::lookup(), llvm::lltok::lsquare, llvm::AttrBuilder::merge(), llvm::lltok::MetadataVar, llvm::Attribute::MinSize, N, llvm::Attribute::Naked, llvm::Attribute::NoBuiltin, llvm::Attribute::NoDuplicate, llvm::Attribute::NoImplicitFloat, llvm::Attribute::NoInline, llvm::None, llvm::Attribute::NonLazyBind, llvm::Attribute::NoRedZone, llvm::Attribute::NoReturn, llvm::GlobalVariable::NotThreadLocal, llvm::Attribute::NoUnwind, llvm::Attribute::OptimizeForSize, llvm::Attribute::OptimizeNone, llvm::iplist< NodeTy, Traits >::push_back(), llvm::lltok::rbrace, llvm::Attribute::ReadNone, llvm::Attribute::ReadOnly, llvm::AttributeSet::removeAttribute(), llvm::AttributeSet::removeAttributes(), llvm::Value::replaceAllUsesWith(), llvm::Attribute::ReturnsTwice, llvm::lltok::rsquare, llvm::Attribute::SanitizeAddress, llvm::Attribute::SanitizeMemory, llvm::Attribute::SanitizeThread, llvm::GlobalValue::setAlignment(), llvm::GlobalVariable::setConstant(), llvm::Module::setDataLayout(), llvm::GlobalVariable::setExternallyInitialized(), llvm::GlobalVariable::setInitializer(), llvm::GlobalValue::setLinkage(), llvm::Instruction::setMetadata(), llvm::GlobalValue::setSection(), llvm::Module::setTargetTriple(), llvm::GlobalVariable::setThreadLocalMode(), llvm::GlobalValue::setUnnamedAddr(), llvm::GlobalValue::setVisibility(), llvm::iplist< NodeTy, Traits >::splice(), llvm::Attribute::StackProtect, llvm::Attribute::StackProtectReq, llvm::Attribute::StackProtectStrong, llvm::lltok::StringConstant, llvm::ValID::StrVal, T, llvm::ValID::t_Constant, llvm::ValID::t_GlobalName, llvm::ValID::t_LocalID, llvm::ValID::t_LocalName, TLM, llvm::ValID::UIntVal, llvm::UpgradeCallsToIntrinsic(), llvm::UpgradeDebugInfo(), llvm::UpgradeInstWithTBAATag(), and llvm::Attribute::UWTable.
Referenced by llvm::ParseAssembly().
The documentation for this class was generated from the following files:
LLParser.h
LLParser.cpp