LLVM: llvm::ThumbTargetMachine Class Reference
LLVM API Documentation
llvm::ThumbTargetMachine Class Reference
#include <ARMTargetMachine.h>
Public Member Functions
ThumbTargetMachine (const Target &T, StringRef TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
virtual const ARMBaseRegisterInfo * getRegisterInfo () const
returns either Thumb1RegisterInfo or Thumb2RegisterInfo
virtual const ARMTargetLowering * getTargetLowering () const
virtual const ARMSelectionDAGInfo * getSelectionDAGInfo () const
virtual const ARMBaseInstrInfo * getInstrInfo () const
returns either Thumb1InstrInfo or Thumb2InstrInfo
virtual const ARMFrameLowering * getFrameLowering () const
returns either Thumb1FrameLowering or ARMFrameLowering
virtual const DataLayout * getDataLayout () const
Public Member Functions inherited from llvm::ARMBaseTargetMachine
ARMBaseTargetMachine (const Target &T, StringRef TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
virtual ARMJITInfo * getJITInfo ()
virtual const ARMSubtarget * getSubtargetImpl () const
virtual const InstrItineraryData * getInstrItineraryData () const
virtual void addAnalysisPasses (PassManagerBase &PM)
Register ARM analysis passes with a pass manager.
virtual TargetPassConfig * createPassConfig (PassManagerBase &PM)
virtual bool addCodeEmitter (PassManagerBase &PM, JITCodeEmitter &MCE)
Public Member Functions inherited from llvm::LLVMTargetMachine
virtual bool addPassesToEmitFile (PassManagerBase &PM, formatted_raw_ostream &Out, CodeGenFileType FileType, bool DisableVerify=true, AnalysisID StartAfter=0, AnalysisID StopAfter=0)
virtual bool addPassesToEmitMachineCode (PassManagerBase &PM, JITCodeEmitter &MCE, bool DisableVerify=true)
virtual bool addPassesToEmitMC (PassManagerBase &PM, MCContext *&Ctx, raw_ostream &OS, bool DisableVerify=true)
Public Member Functions inherited from llvm::TargetMachine
virtual ~TargetMachine ()
const Target & getTarget () const
const StringRef getTargetTriple () const
const StringRef getTargetCPU () const
const StringRef getTargetFeatureString () const
void resetTargetOptions (const MachineFunction *MF) const
Reset the target options based on the function's attributes.
const MCAsmInfo * getMCAsmInfo () const
template<typename STC >
const STC & getSubtarget () const
virtual const TargetIntrinsicInfo * getIntrinsicInfo () const
bool hasMCRelaxAll () const
void setMCRelaxAll (bool Value)
bool hasMCSaveTempLabels () const
void setMCSaveTempLabels (bool Value)
bool hasMCNoExecStack () const
hasMCNoExecStack - Check whether an executable stack is not needed.
void setMCNoExecStack (bool Value)
setMCNoExecStack - Set whether an executabel stack is not needed.
bool hasMCUseLoc () const
hasMCUseLoc - Check whether we should use dwarf's .loc directive.
void setMCUseLoc (bool Value)
setMCUseLoc - Set whether all we should use dwarf's .loc directive.
bool hasMCUseCFI () const
hasMCUseCFI - Check whether we should use dwarf's .cfi_* directives.
void setMCUseCFI (bool Value)
setMCUseCFI - Set whether all we should use dwarf's .cfi_* directives.
bool hasMCUseDwarfDirectory () const
void setMCUseDwarfDirectory (bool Value)
Reloc::Model getRelocationModel () const
CodeModel::Model getCodeModel () const
TLSModel::Model getTLSModel (const GlobalValue *GV) const
CodeGenOpt::Level getOptLevel () const
void setOptLevel (CodeGenOpt::Level Level) const
Overrides the optimization level.
void setFastISel (bool Enable)
bool shouldPrintMachineCode () const
Additional Inherited Members
Public Types inherited from llvm::TargetMachine
enum CodeGenFileType { CGFT_AssemblyFile, CGFT_ObjectFile, CGFT_Null }
Static Public Member Functions inherited from llvm::TargetMachine
static bool getAsmVerbosityDefault ()
static void setAsmVerbosityDefault (bool)
static bool getDataSections ()
static bool getFunctionSections ()
static void setDataSections (bool)
setDataSections - Set if the data are emit into separate sections.
static void setFunctionSections (bool)
Public Attributes inherited from llvm::TargetMachine
TargetOptions Options
Protected Member Functions inherited from llvm::LLVMTargetMachine
LLVMTargetMachine (const Target &T, StringRef TargetTriple, StringRef CPU, StringRef FS, TargetOptions Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
void initAsmInfo ()
Protected Member Functions inherited from llvm::TargetMachine
TargetMachine (const Target &T, StringRef TargetTriple, StringRef CPU, StringRef FS, const TargetOptions &Options)
Protected Attributes inherited from llvm::ARMBaseTargetMachine
ARMSubtarget Subtarget
Protected Attributes inherited from llvm::TargetMachine
const Target & TheTarget
TheTarget - The Target that this machine was created for.
std::string TargetTriple
std::string TargetCPU
std::string TargetFS
MCCodeGenInfo * CodeGenInfo
const MCAsmInfo * AsmInfo
unsigned MCRelaxAll: 1
unsigned MCNoExecStack: 1
unsigned MCSaveTempLabels: 1
unsigned MCUseLoc: 1
unsigned MCUseCFI: 1
unsigned MCUseDwarfDirectory: 1
Detailed Description
ThumbTargetMachine - Thumb target machine. Due to the way architectures are handled, this represents both Thumb-1 and Thumb-2.
Definition at line 104 of file ARMTargetMachine.h.
Constructor & Destructor Documentation
ThumbTargetMachine::ThumbTargetMachine (const Target & T, StringRef TT, StringRef CPU, StringRef FS, const TargetOptions & Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
Definition at line 96 of file ARMTargetMachine.cpp.
References llvm::LLVMTargetMachine::initAsmInfo(), and llvm::SystemZISD::TM.
Member Function Documentation
virtual const DataLayout* llvm::ThumbTargetMachine::getDataLayout () const inline virtual
Reimplemented from llvm::TargetMachine.
Definition at line 141 of file ARMTargetMachine.h.
virtual const ARMFrameLowering* llvm::ThumbTargetMachine::getFrameLowering () const inline virtual
returns either Thumb1FrameLowering or ARMFrameLowering
Reimplemented from llvm::TargetMachine.
Definition at line 138 of file ARMTargetMachine.h.
References llvm::OwningPtr< T >::get().
virtual const ARMBaseInstrInfo* llvm::ThumbTargetMachine::getInstrInfo () const inline virtual
returns either Thumb1InstrInfo or Thumb2InstrInfo
Reimplemented from llvm::TargetMachine.
Definition at line 134 of file ARMTargetMachine.h.
References llvm::OwningPtr< T >::get().
virtual const ARMBaseRegisterInfo* llvm::ThumbTargetMachine::getRegisterInfo () const inline virtual
returns either Thumb1RegisterInfo or Thumb2RegisterInfo
Reimplemented from llvm::TargetMachine.
Definition at line 121 of file ARMTargetMachine.h.
virtual const ARMSelectionDAGInfo* llvm::ThumbTargetMachine::getSelectionDAGInfo () const inline virtual
Reimplemented from llvm::TargetMachine.
Definition at line 129 of file ARMTargetMachine.h.
virtual const ARMTargetLowering* llvm::ThumbTargetMachine::getTargetLowering () const inline virtual
Reimplemented from llvm::ARMBaseTargetMachine.
Definition at line 125 of file ARMTargetMachine.h.
The documentation for this class was generated from the following files:
ARMTargetMachine.h
ARMTargetMachine.cpp