LLVM: llvm::MCAtom Class Reference
LLVM API Documentation
llvm::MCAtom Class Reference abstract
Represents a contiguous range of either instructions (a TextAtom) or data (a DataAtom). Address ranges are expressed as closed intervals.
#include <MCAtom.h>
Public Types
enum AtomKind { TextAtom, DataAtom }
Public Member Functions
virtual ~MCAtom ()
AtomKind getKind () const
uint64_t getBeginAddr () const
Get the start address of the atom.
uint64_t getEndAddr () const
Get the end address, i.e. the last one inside the atom.
Atom modification methods:
When modifying a TextAtom, keep instruction boundaries in mind. For instance, split must me given the start address of an instruction.
virtual MCAtom * split (uint64_t SplitPt)=0
Splits the atom in two at a given address.
virtual void truncate (uint64_t TruncPt)=0
Truncates an atom, discarding everything after TruncPt.
Naming:
This is mostly for display purposes, and may contain anything that hints at what the atom contains: section or symbol name, BB start address, ..
StringRef getName () const
void setName (StringRef NewName)
Protected Member Functions
MCAtom (AtomKind K, MCModule *P, uint64_t B, uint64_t E)
Atom remapping helpers
void remap (uint64_t NewBegin, uint64_t NewEnd)
Remap the atom, using the given range, updating Begin/End. One or both of the bounds can remain the same, but overlapping with other atoms in the module is still forbidden.
void remapForTruncate (uint64_t TruncPt)
Remap the atom to prepare for a truncation at TruncPt. Equivalent to:
void remapForSplit (uint64_t SplitPt, uint64_t &LBegin, uint64_t &LEnd, uint64_t &RBegin, uint64_t &REnd)
Remap the atom to prepare for a split at SplitPt. The bounds for the resulting atoms are returned in {L,R}{Begin,End}. The current atom is truncated to LEnd.
Protected Attributes
const AtomKind Kind
std::string Name
MCModule * Parent
uint64_t Begin
uint64_t End
Friends
class MCModule
Detailed Description
Represents a contiguous range of either instructions (a TextAtom) or data (a DataAtom). Address ranges are expressed as closed intervals.
Definition at line 34 of file MCAtom.h.
Member Enumeration Documentation
enum llvm::MCAtom::AtomKind
Enumerator
TextAtom
DataAtom
Definition at line 39 of file MCAtom.h.
Constructor & Destructor Documentation
virtual llvm::MCAtom::~MCAtom () inline virtual
Definition at line 37 of file MCAtom.h.
llvm::MCAtom::MCAtom (AtomKind K, MCModule * P, uint64_t B, uint64_t E) inline protected
Definition at line 78 of file MCAtom.h.
References remap(), remapForSplit(), and remapForTruncate().
Member Function Documentation
uint64_t llvm::MCAtom::getBeginAddr () const inline
Get the start address of the atom.
Definition at line 43 of file MCAtom.h.
References Begin.
Referenced by llvm::yaml::ScalarTraits< MCModuleYAML::OpcodeEnum >::input(), RemoveDupsFromAddressVector(), and llvm::MCBasicBlock::splitBasicBlock().
uint64_t llvm::MCAtom::getEndAddr () const inline
Get the end address, i.e. the last one inside the atom.
Definition at line 45 of file MCAtom.h.
References End, split(), and truncate().
Referenced by AtomComp(), AtomCompInv(), llvm::yaml::ScalarTraits< MCModuleYAML::OpcodeEnum >::input(), RemoveDupsFromAddressVector(), and llvm::MCBasicBlock::splitBasicBlock().
AtomKind llvm::MCAtom::getKind () const inline
Definition at line 40 of file MCAtom.h.
References Kind.
Referenced by llvm::MCTextAtom::classof(), llvm::MCDataAtom::classof(), and llvm::yaml::ScalarTraits< MCModuleYAML::OpcodeEnum >::input().
StringRef llvm::MCAtom::getName () const inline
Definition at line 67 of file MCAtom.h.
References Name.
Referenced by RemoveDupsFromAddressVector(), llvm::MCTextAtom::split(), and llvm::MCDataAtom::split().
void MCAtom::remap (uint64_t NewBegin, uint64_t NewEnd) protected
Remap the atom, using the given range, updating Begin/End. One or both of the bounds can remain the same, but overlapping with other atoms in the module is still forbidden.
Definition at line 20 of file MCAtom.cpp.
References Parent.
Referenced by llvm::MCDataAtom::addData(), llvm::MCTextAtom::addInst(), MCAtom(), remapForSplit(), and remapForTruncate().
void MCAtom::remapForSplit (uint64_t SplitPt, uint64_t & LBegin, uint64_t & LEnd, uint64_t & RBegin, uint64_t & REnd) protected
Remap the atom to prepare for a split at SplitPt. The bounds for the resulting atoms are returned in {L,R}{Begin,End}. The current atom is truncated to LEnd.
Definition at line 30 of file MCAtom.cpp.
References Begin, End, and remap().
Referenced by MCAtom(), llvm::MCTextAtom::split(), and llvm::MCDataAtom::split().
void MCAtom::remapForTruncate (uint64_t TruncPt) protected
Remap the atom to prepare for a truncation at TruncPt. Equivalent to:
// Bound checks
remap(Begin, TruncPt);
Definition at line 24 of file MCAtom.cpp.
References Begin, End, and remap().
Referenced by MCAtom(), llvm::MCTextAtom::truncate(), and llvm::MCDataAtom::truncate().
void llvm::MCAtom::setName (StringRef NewName) inline
Definition at line 68 of file MCAtom.h.
References Name, and llvm::StringRef::str().
Referenced by llvm::MCObjectDisassembler::buildModule(), RemoveDupsFromAddressVector(), llvm::MCTextAtom::split(), and llvm::MCDataAtom::split().
virtual MCAtom* llvm::MCAtom::split (uint64_t SplitPt) pure virtual
Splits the atom in two at a given address.
Parameters
SplitPt Address at which to start a new atom, splitting this one.
Returns
The newly created atom starting at SplitPt.
Implemented in llvm::MCDataAtom, and llvm::MCTextAtom.
Referenced by llvm::MCDataAtom::getData(), getEndAddr(), and llvm::MCTextAtom::size().
virtual void llvm::MCAtom::truncate (uint64_t TruncPt) pure virtual
Truncates an atom, discarding everything after TruncPt.
Parameters
TruncPt Last byte address to be contained in this atom.
Implemented in llvm::MCDataAtom, and llvm::MCTextAtom.
Referenced by llvm::MCDataAtom::getData(), getEndAddr(), and llvm::MCTextAtom::size().
Friends And Related Function Documentation
friend class MCModule friend
Definition at line 77 of file MCAtom.h.
Member Data Documentation
uint64_t llvm::MCAtom::Begin protected
Definition at line 75 of file MCAtom.h.
Referenced by llvm::MCDataAtom::addData(), llvm::MCTextAtom::addInst(), AtomCompInv(), llvm::MCModule::createDataAtom(), getBeginAddr(), remapForSplit(), remapForTruncate(), and llvm::MCDataAtom::truncate().
uint64_t llvm::MCAtom::End protected
Definition at line 75 of file MCAtom.h.
Referenced by llvm::MCDataAtom::addData(), llvm::MCTextAtom::addInst(), AtomCompInv(), llvm::MCModule::createDataAtom(), getEndAddr(), remapForSplit(), and remapForTruncate().
const AtomKind llvm::MCAtom::Kind protected
Definition at line 72 of file MCAtom.h.
Referenced by getKind().
std::string llvm::MCAtom::Name protected
Definition at line 73 of file MCAtom.h.
Referenced by getName(), and setName().
MCModule* llvm::MCAtom::Parent protected
Definition at line 74 of file MCAtom.h.
Referenced by remap(), llvm::MCTextAtom::split(), and llvm::MCDataAtom::split().
The documentation for this class was generated from the following files:
MCAtom.h
MCAtom.cpp