LLVM: llvm::MCAsmLexer Class Reference
LLVM API Documentation
llvm::MCAsmLexer Class Reference abstract
#include <MCAsmLexer.h>
Public Member Functions
virtual ~MCAsmLexer ()
const AsmToken & Lex ()
virtual StringRef LexUntilEndOfStatement ()=0
SMLoc getLoc () const
getLoc - Get the current source location.
const AsmToken & getTok ()
getTok - Get the current (last) lexed token.
const SMLoc & getErrLoc ()
getErrLoc - Get the current error location
const std::string & getErr ()
getErr - Get the current error string
AsmToken::TokenKind getKind () const
getKind - Get the kind of current token.
bool is (AsmToken::TokenKind K) const
is - Check if the current token has kind K.
bool isNot (AsmToken::TokenKind K) const
isNot - Check if the current token has kind K.
void setSkipSpace (bool val)
setSkipSpace - Set whether spaces should be ignored by the lexer
Protected Member Functions
MCAsmLexer ()
virtual AsmToken LexToken ()=0
void SetError (const SMLoc &errLoc, const std::string &err)
Protected Attributes
const char * TokStart
bool SkipSpace
Detailed Description
MCAsmLexer - Generic assembler lexer interface, for use by target specific assembly lexers.
Definition at line 108 of file MCAsmLexer.h.
Constructor & Destructor Documentation
MCAsmLexer::MCAsmLexer () protected
Definition at line 15 of file MCAsmLexer.cpp.
MCAsmLexer::~MCAsmLexer () virtual
Definition at line 19 of file MCAsmLexer.cpp.
Member Function Documentation
const std::string& llvm::MCAsmLexer::getErr () inline
getErr - Get the current error string
Definition at line 158 of file MCAsmLexer.h.
const SMLoc& llvm::MCAsmLexer::getErrLoc () inline
getErrLoc - Get the current error location
Definition at line 153 of file MCAsmLexer.h.
AsmToken::TokenKind llvm::MCAsmLexer::getKind () const inline
getKind - Get the kind of current token.
Definition at line 163 of file MCAsmLexer.h.
References llvm::AsmToken::getKind().
SMLoc MCAsmLexer::getLoc () const
getLoc - Get the current source location.
Definition at line 22 of file MCAsmLexer.cpp.
References llvm::SMLoc::getFromPointer(), and TokStart.
const AsmToken& llvm::MCAsmLexer::getTok () inline
getTok - Get the current (last) lexed token.
Definition at line 148 of file MCAsmLexer.h.
Referenced by llvm::MCAsmParser::getTok().
bool llvm::MCAsmLexer::is (AsmToken::TokenKind K) const inline
is - Check if the current token has kind K.
Definition at line 166 of file MCAsmLexer.h.
References llvm::AsmToken::is().
bool llvm::MCAsmLexer::isNot (AsmToken::TokenKind K) const inline
isNot - Check if the current token has kind K.
Definition at line 169 of file MCAsmLexer.h.
References llvm::AsmToken::isNot().
const AsmToken& llvm::MCAsmLexer::Lex () inline
Lex - Consume the next token from the input stream and return it.
The lexer will continuosly return the end-of-file token once the end of the main input file has been reached.
Definition at line 138 of file MCAsmLexer.h.
References llvm::AsmToken::getLoc().
virtual AsmToken llvm::MCAsmLexer::LexToken () protected pure virtual
Implemented in llvm::AsmLexer.
virtual StringRef llvm::MCAsmLexer::LexUntilEndOfStatement () pure virtual
Implemented in llvm::AsmLexer.
void llvm::MCAsmLexer::SetError (const SMLoc & errLoc, const std::string & err) inline protected
Definition at line 126 of file MCAsmLexer.h.
Referenced by llvm::AsmLexer::setBuffer().
void llvm::MCAsmLexer::setSkipSpace (bool val) inline
setSkipSpace - Set whether spaces should be ignored by the lexer
Definition at line 172 of file MCAsmLexer.h.
References val.
Member Data Documentation
bool llvm::MCAsmLexer::SkipSpace protected
Definition at line 120 of file MCAsmLexer.h.
Referenced by llvm::AsmLexer::LexToken().
const char* llvm::MCAsmLexer::TokStart protected
Definition at line 119 of file MCAsmLexer.h.
Referenced by doLookAhead(), getLoc(), IsIdentifierChar(), llvm::AsmLexer::LexToken(), llvm::AsmLexer::LexUntilEndOfLine(), llvm::AsmLexer::LexUntilEndOfStatement(), and llvm::AsmLexer::setBuffer().
The documentation for this class was generated from the following files:
MCAsmLexer.h
MCAsmLexer.cpp