LLVM: llvm::SectionMemoryManager Class Reference
LLVM API Documentation
llvm::SectionMemoryManager Class Reference
#include <SectionMemoryManager.h>
Public Member Functions
SectionMemoryManager ()
virtual ~SectionMemoryManager ()
virtual uint8_t * allocateCodeSection (uintptr_t Size, unsigned Alignment, unsigned SectionID, StringRef SectionName)
Allocates a memory block of (at least) the given size suitable for executable code.
virtual uint8_t * allocateDataSection (uintptr_t Size, unsigned Alignment, unsigned SectionID, StringRef SectionName, bool isReadOnly)
Allocates a memory block of (at least) the given size suitable for executable code.
virtual bool finalizeMemory (std::string *ErrMsg=0)
Update section-specific memory permissions and other attributes.
virtual void invalidateInstructionCache ()
Invalidate instruction cache for code sections.
Public Member Functions inherited from llvm::RTDyldMemoryManager
RTDyldMemoryManager ()
virtual ~RTDyldMemoryManager ()
virtual void registerEHFrames (uint8_t *Addr, uint64_t LoadAddr, size_t Size)
virtual void deregisterEHFrames (uint8_t *Addr, uint64_t LoadAddr, size_t Size)
virtual uint64_t getSymbolAddress (const std::string &Name)
virtual void * getPointerToNamedFunction (const std::string &Name, bool AbortOnFailure=true)
virtual void notifyObjectLoaded (ExecutionEngine *EE, const ObjectImage *)
Detailed Description
This is a simple memory manager which implements the methods called by the RuntimeDyld class to allocate memory for section-based loading of objects, usually those generated by the MCJIT execution engine.
This memory manager allocates all section memory as read-write. The RuntimeDyld will copy JITed section memory into these allocated blocks and perform any necessary linking and relocations.
Any client using this memory manager MUST ensure that section-specific page permissions have been applied before attempting to execute functions in the JITed object. Permissions can be applied either by calling MCJIT::finalizeObject or by calling SectionMemoryManager::finalizeMemory directly. Clients of MCJIT should call MCJIT::finalizeObject.
Definition at line 38 of file SectionMemoryManager.h.
Constructor & Destructor Documentation
llvm::SectionMemoryManager::SectionMemoryManager () inline
Definition at line 43 of file SectionMemoryManager.h.
References allocateCodeSection(), allocateDataSection(), finalizeMemory(), invalidateInstructionCache(), and ~SectionMemoryManager().
llvm::SectionMemoryManager::~SectionMemoryManager () virtual
Definition at line 167 of file SectionMemoryManager.cpp.
References i, and llvm::sys::Memory::releaseMappedMemory().
Referenced by SectionMemoryManager().
Member Function Documentation
uint8_t * llvm::SectionMemoryManager::allocateCodeSection (uintptr_t Size, unsigned Alignment, unsigned SectionID, StringRef SectionName) virtual
Allocates a memory block of (at least) the given size suitable for executable code.
The value of Alignment must be a power of two. If Alignment is zero a default alignment of 16 will be used.
Implements llvm::RTDyldMemoryManager.
Definition at line 31 of file SectionMemoryManager.cpp.
References llvm::sys::Memory::allocateMappedMemory(), llvm::sys::MemoryBlock::base(), i, llvm::sys::Memory::MF_READ, llvm::sys::Memory::MF_WRITE, and llvm::sys::MemoryBlock::size().
Referenced by SectionMemoryManager().
uint8_t * llvm::SectionMemoryManager::allocateDataSection (uintptr_t Size, unsigned Alignment, unsigned SectionID, StringRef SectionName, bool isReadOnly) virtual
Allocates a memory block of (at least) the given size suitable for executable code.
The value of Alignment must be a power of two. If Alignment is zero a default alignment of 16 will be used.
Implements llvm::RTDyldMemoryManager.
Definition at line 21 of file SectionMemoryManager.cpp.
Referenced by SectionMemoryManager().
bool llvm::SectionMemoryManager::finalizeMemory (std::string * ErrMsg = 0) virtual
Update section-specific memory permissions and other attributes.
This method is called when object loading is complete and section page permissions can be applied. It is up to the memory manager implementation to decide whether or not to act on this method. The memory manager will typically allocate all sections as read-write and then apply specific permissions when this method is called. Code sections cannot be executed until this function has been called. In addition, any cache coherency operations needed to reliably use the memory are also performed.
Returns
true if an error occurred, false otherwise.
Implements llvm::RTDyldMemoryManager.
Definition at line 105 of file SectionMemoryManager.cpp.
References i, invalidateInstructionCache(), llvm::error_code::message(), llvm::sys::Memory::MF_EXEC, llvm::sys::Memory::MF_READ, llvm::sys::Memory::protectMappedMemory(), and llvm::error_code::success().
Referenced by SectionMemoryManager().
void llvm::SectionMemoryManager::invalidateInstructionCache () virtual
Invalidate instruction cache for code sections.
Some platforms with separate data cache and instruction cache require explicit cache flush, otherwise JIT code manipulations (like resolved relocations) will get to the data cache but not to the instruction cache.
This method is called from finalizeMemory.
Definition at line 161 of file SectionMemoryManager.cpp.
References i, and llvm::sys::Memory::InvalidateInstructionCache().
Referenced by finalizeMemory(), and SectionMemoryManager().
The documentation for this class was generated from the following files:
SectionMemoryManager.h
SectionMemoryManager.cpp