LLVM: llvm::MachineBlockFrequencyInfo Class Reference
LLVM API Documentation
llvm::MachineBlockFrequencyInfo Class Reference
#include <MachineBlockFrequencyInfo.h>
Public Member Functions
MachineBlockFrequencyInfo ()
~MachineBlockFrequencyInfo ()
void getAnalysisUsage (AnalysisUsage &AU) const
bool runOnMachineFunction (MachineFunction &F)
BlockFrequency getBlockFreq (const MachineBasicBlock *MBB) const
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const
createPrinterPass - Get a function printer pass.
virtual void assignPassManager (PMStack &PMS, PassManagerType T)
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
Detailed Description
MachineBlockFrequencyInfo pass uses BlockFrequencyImpl implementation to estimate machine basic block frequencies.
Definition at line 30 of file MachineBlockFrequencyInfo.h.
Constructor & Destructor Documentation
MachineBlockFrequencyInfo::MachineBlockFrequencyInfo ()
Definition at line 31 of file MachineBlockFrequencyInfo.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeMachineBlockFrequencyInfoPass().
MachineBlockFrequencyInfo::~MachineBlockFrequencyInfo ()
Definition at line 37 of file MachineBlockFrequencyInfo.cpp.
Member Function Documentation
void MachineBlockFrequencyInfo::getAnalysisUsage (AnalysisUsage & AU) const virtual
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
For MachineFunctionPasses, calling AU.preservesCFG() indicates that the pass does not modify the MachineBasicBlock CFG.
Reimplemented from llvm::MachineFunctionPass.
Definition at line 41 of file MachineBlockFrequencyInfo.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::MachineFunctionPass::getAnalysisUsage(), and llvm::AnalysisUsage::setPreservesAll().
BlockFrequency MachineBlockFrequencyInfo::getBlockFreq (const MachineBasicBlock * MBB) const
getblockFreq - Return block frequency. Return 0 if we don't have the information. Please note that initial frequency is equal to 1024. It means that we should not rely on the value itself, but only on the comparison to the other block frequencies. We do this to avoid using of floating points.
Definition at line 54 of file MachineBlockFrequencyInfo.cpp.
Referenced by llvm::PBQPBuilderWithCoalescing::build(), llvm::VirtRegAuxInfo::calculateSpillWeightAndHint(), false::IntervalSorter::operator()(), runOnMachineFunction(), and llvm::SpillPlacement::Node::update().
bool MachineBlockFrequencyInfo::runOnMachineFunction (MachineFunction & MF) virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 47 of file MachineBlockFrequencyInfo.cpp.
References getBlockFreq().
Member Data Documentation
machine block Machine Block Frequency true char MachineBlockFrequencyInfo::ID = 0 static
Definition at line 36 of file MachineBlockFrequencyInfo.h.
The documentation for this class was generated from the following files:
MachineBlockFrequencyInfo.h
MachineBlockFrequencyInfo.cpp