LLVM: llvm::DWARFTypeUnit Class Reference
LLVM API Documentation
llvm::DWARFTypeUnit Class Reference
#include <DWARFTypeUnit.h>
Public Member Functions
DWARFTypeUnit (const DWARFDebugAbbrev *DA, StringRef IS, StringRef AS, StringRef RS, StringRef SS, StringRef SOS, StringRef AOS, const RelocAddrMap *M, bool LE)
uint32_t getSize () const LLVM_OVERRIDE
Size in bytes of the compile unit header.
void dump (raw_ostream &OS)
Public Member Functions inherited from llvm::DWARFUnit
DWARFUnit (const DWARFDebugAbbrev *DA, StringRef IS, StringRef AS, StringRef RS, StringRef SS, StringRef SOS, StringRef AOS, const RelocAddrMap *M, bool LE)
virtual ~DWARFUnit ()
StringRef getStringSection () const
StringRef getStringOffsetSection () const
void setAddrOffsetSection (StringRef AOS, uint32_t Base)
void setRangesSection (StringRef RS, uint32_t Base)
bool getAddrOffsetSectionItem (uint32_t Index, uint64_t &Result) const
bool getStringOffsetSectionItem (uint32_t Index, uint32_t &Result) const
DataExtractor getDebugInfoExtractor () const
DataExtractor getStringExtractor () const
const RelocAddrMap * getRelocMap () const
bool extract (DataExtractor debug_info, uint32_t *offset_ptr)
bool extractRangeList (uint32_t RangeListOffset, DWARFDebugRangeList &RangeList) const
void clear ()
uint32_t getOffset () const
uint32_t getFirstDIEOffset () const
uint32_t getNextUnitOffset () const
size_t getDebugInfoSize () const
Size in bytes of the .debug_info data associated with this compile unit.
uint32_t getLength () const
uint16_t getVersion () const
const DWARFAbbreviationDeclarationSet * getAbbreviations () const
uint8_t getAddressByteSize () const
uint64_t getBaseAddress () const
void setBaseAddress (uint64_t base_addr)
const DWARFDebugInfoEntryMinimal * getCompileUnitDIE (bool extract_cu_die_only=true)
const char * getCompilationDir ()
uint64_t getDWOId ()
void buildAddressRangeTable (DWARFDebugAranges *debug_aranges, bool clear_dies_if_already_not_parsed, uint32_t CUOffsetInAranges)
DWARFDebugInfoEntryInlinedChain getInlinedChainForAddress (uint64_t Address)
Protected Member Functions
bool extractImpl (DataExtractor debug_info, uint32_t *offset_ptr) LLVM_OVERRIDE
Detailed Description
Definition at line 17 of file DWARFTypeUnit.h.
Constructor & Destructor Documentation
llvm::DWARFTypeUnit::DWARFTypeUnit (const DWARFDebugAbbrev * DA, StringRef IS, StringRef AS, StringRef RS, StringRef SS, StringRef SOS, StringRef AOS, const RelocAddrMap * M, bool LE) inline
Definition at line 22 of file DWARFTypeUnit.h.
Member Function Documentation
void DWARFTypeUnit::dump (raw_ostream & OS)
Definition at line 25 of file DWARFTypeUnit.cpp.
References llvm::DWARFDebugInfoEntryMinimal::dump(), llvm::format(), llvm::DWARFUnit::getAbbreviations(), llvm::DWARFUnit::getAddressByteSize(), llvm::DWARFUnit::getCompileUnitDIE(), llvm::DWARFUnit::getLength(), llvm::DWARFUnit::getNextUnitOffset(), llvm::DWARFUnit::getOffset(), and llvm::DWARFUnit::getVersion().
Referenced by getSize().
bool DWARFTypeUnit::extractImpl (DataExtractor debug_info, uint32_t * offset_ptr) protected virtual
Reimplemented from llvm::DWARFUnit.
Definition at line 16 of file DWARFTypeUnit.cpp.
References llvm::DWARFUnit::extractImpl(), llvm::DWARFUnit::getLength(), llvm::DataExtractor::getU32(), and llvm::DataExtractor::getU64().
Referenced by getSize().
uint32_t llvm::DWARFTypeUnit::getSize () const inline virtual
Size in bytes of the compile unit header.
Reimplemented from llvm::DWARFUnit.
Definition at line 26 of file DWARFTypeUnit.h.
References dump(), extractImpl(), llvm::DWARFUnit::getSize(), and LLVM_OVERRIDE.
The documentation for this class was generated from the following files:
DWARFTypeUnit.h
DWARFTypeUnit.cpp