LLVM: llvm::yaml::Scanner Class Reference
LLVM API Documentation
llvm::yaml::Scanner Class Reference
Scans YAML tokens from a MemoryBuffer.
Public Member Functions
Scanner (const StringRef Input, SourceMgr &SM)
Scanner (MemoryBuffer *Buffer, SourceMgr &SM_)
Token & peekNext ()
Parse the next token and return it without popping it.
Token getNext ()
Parse the next token and pop it from the queue.
void printError (SMLoc Loc, SourceMgr::DiagKind Kind, const Twine &Message, ArrayRef< SMRange > Ranges=None)
void setError (const Twine &Message, StringRef::iterator Position)
void setError (const Twine &Message)
bool failed ()
Returns true if an error occurred while parsing.
Detailed Description
Scans YAML tokens from a MemoryBuffer.
Definition at line 260 of file YAMLParser.cpp.
Constructor & Destructor Documentation
Scanner::Scanner (const StringRef Input, SourceMgr & SM)
Definition at line 705 of file YAMLParser.cpp.
References llvm::SourceMgr::AddNewSourceBuffer(), llvm::MemoryBuffer::getBufferEnd(), llvm::MemoryBuffer::getBufferStart(), and llvm::MemoryBuffer::getMemBuffer().
Scanner::Scanner (MemoryBuffer * Buffer, SourceMgr & SM_)
Definition at line 720 of file YAMLParser.cpp.
References llvm::SourceMgr::AddNewSourceBuffer().
Member Function Documentation
bool llvm::yaml::Scanner::failed () inline
Returns true if an error occurred while parsing.
Definition at line 292 of file YAMLParser.cpp.
References decodeUTF8(), and llvm::yaml::skip().
Token Scanner::getNext ()
Parse the next token and pop it from the queue.
Definition at line 762 of file YAMLParser.cpp.
References llvm::iplist< NodeTy, Traits >::empty(), i, peekNext(), llvm::iplist< NodeTy, Traits >::pop_front(), and llvm::AArch64ISD::Ret.
Referenced by llvm::yaml::dumpTokens(), and llvm::yaml::scanTokens().
Token & Scanner::peekNext ()
Parse the next token and return it without popping it.
Definition at line 735 of file YAMLParser.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::iplist< NodeTy, Traits >::clear(), llvm::iplist< NodeTy, Traits >::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::iplist< NodeTy, Traits >::front(), and llvm::ilist< NodeTy >::push_back().
Referenced by getNext().
void llvm::yaml::Scanner::printError (SMLoc Loc, SourceMgr::DiagKind Kind, const Twine & Message, ArrayRef< SMRange > Ranges = None) inline
Definition at line 271 of file YAMLParser.cpp.
References llvm::SourceMgr::PrintMessage().
void llvm::yaml::Scanner::setError (const Twine & Message, StringRef::iterator Position) inline
Definition at line 276 of file YAMLParser.cpp.
References llvm::SourceMgr::DK_Error, and llvm::SMLoc::getFromPointer().
Referenced by is_ns_word_char(), and wasEscaped().
void llvm::yaml::Scanner::setError (const Twine & Message) inline
Definition at line 287 of file YAMLParser.cpp.
The documentation for this class was generated from the following file:
YAMLParser.cpp