LLVM: llvm::StringMapEntry< ValueTy > Class Template Reference
LLVM API Documentation
llvm::StringMapEntry< ValueTy > Class Template Reference
#include <StringMap.h>
Public Member Functions
StringMapEntry (unsigned strLen)
StringMapEntry (unsigned strLen, const ValueTy &V)
StringRef getKey () const
const ValueTy & getValue () const
ValueTy & getValue ()
void setValue (const ValueTy &V)
const char * getKeyData () const
StringRef first () const
template<typename AllocatorTy >
void Destroy (AllocatorTy &Allocator)
void Destroy ()
Destroy this object, releasing memory back to the malloc allocator.
Public Member Functions inherited from llvm::StringMapEntryBase
StringMapEntryBase (unsigned Len)
unsigned getKeyLength () const
Static Public Member Functions
template<typename AllocatorTy , typename InitType >
static StringMapEntry * Create (const char *KeyStart, const char *KeyEnd, AllocatorTy &Allocator, InitType InitVal)
template<typename AllocatorTy >
static StringMapEntry * Create (const char *KeyStart, const char *KeyEnd, AllocatorTy &Allocator)
template<typename InitType >
static StringMapEntry * Create (const char *KeyStart, const char *KeyEnd, InitType InitVal)
Create - Create a StringMapEntry with normal malloc/free.
static StringMapEntry * Create (const char *KeyStart, const char *KeyEnd)
static StringMapEntry & GetStringMapEntryFromValue (ValueTy &V)
static const StringMapEntry & GetStringMapEntryFromValue (const ValueTy &V)
static StringMapEntry & GetStringMapEntryFromKeyData (const char *KeyData)
Public Attributes
ValueTy second
Detailed Description
template<typename ValueTy>
class llvm::StringMapEntry< ValueTy >
StringMapEntry - This is used to represent one value that is inserted into a StringMap. It contains the Value itself and the key: the string length and data.
Definition at line 27 of file StringMap.h.
Constructor & Destructor Documentation
template<typename ValueTy> llvm::StringMapEntry< ValueTy >::StringMapEntry (unsigned strLen) inline explicit
Definition at line 123 of file StringMap.h.
template<typename ValueTy> llvm::StringMapEntry< ValueTy >::StringMapEntry (unsigned strLen, const ValueTy & V) inline
Definition at line 125 of file StringMap.h.
Member Function Documentation
template<typename ValueTy> template<typename AllocatorTy , typename InitType > static StringMapEntry* llvm::StringMapEntry< ValueTy >::Create (const char * KeyStart, const char * KeyEnd, AllocatorTy & Allocator, InitType InitVal) inline static
Create - Create a StringMapEntry for the specified key and default construct the value.
Definition at line 147 of file StringMap.h.
References llvm::StringMapEntryInitializer< ValueTy >::Initialize(), and llvm::Intrinsic::memcpy.
Referenced by llvm::StringPool::intern(), and llvm::Value::setName().
template<typename ValueTy> template<typename AllocatorTy > static StringMapEntry* llvm::StringMapEntry< ValueTy >::Create (const char * KeyStart, const char * KeyEnd, AllocatorTy & Allocator) inline static
Definition at line 177 of file StringMap.h.
template<typename ValueTy> template<typename InitType > static StringMapEntry* llvm::StringMapEntry< ValueTy >::Create (const char * KeyStart, const char * KeyEnd, InitType InitVal) inline static
Create - Create a StringMapEntry with normal malloc/free.
Definition at line 184 of file StringMap.h.
References llvm::ARM_PROC::A.
template<typename ValueTy> static StringMapEntry* llvm::StringMapEntry< ValueTy >::Create (const char * KeyStart, const char * KeyEnd) inline static
Definition at line 190 of file StringMap.h.
template<typename ValueTy> template<typename AllocatorTy > void llvm::StringMapEntry< ValueTy >::Destroy (AllocatorTy & Allocator) inline
Destroy - Destroy this StringMapEntry, releasing memory back to the specified allocator.
Definition at line 217 of file StringMap.h.
Referenced by llvm::PooledStringPtr::clear(), llvm::StringMap< std::pair< llvm::Type *, llvm::SMLoc > >::erase(), llvm::Value::setName(), llvm::Value::takeName(), llvm::Value::~Value(), and llvm::ValueSymbolTable::~ValueSymbolTable().
template<typename ValueTy> void llvm::StringMapEntry< ValueTy >::Destroy () inline
Destroy this object, releasing memory back to the malloc allocator.
Definition at line 224 of file StringMap.h.
References llvm::ARM_PROC::A.
template<typename ValueTy> StringRef llvm::StringMapEntry< ValueTy >::first () const inline
Definition at line 142 of file StringMap.h.
template<typename ValueTy> StringRef llvm::StringMapEntry< ValueTy >::getKey () const inline
Definition at line 128 of file StringMap.h.
Referenced by getFunctionName(), llvm::Value::getName(), llvm::MCContext::GetOrCreateSymbol(), llvm::StringMap< std::pair< llvm::Type *, llvm::SMLoc > >::insert(), and LTOModule::makeLTOModule().
template<typename ValueTy> const char* llvm::StringMapEntry< ValueTy >::getKeyData () const inline
getKeyData - Return the start of the string data that is the key for this value. The string data is always stored immediately after the StringMapEntry object.
Definition at line 140 of file StringMap.h.
Referenced by llvm::PooledStringPtr::begin(), llvm::PooledStringPtr::end(), llvm::ConstantDataSequential::getImpl(), llvm::TargetIntrinsicInfo::getIntrinsicID(), llvm::Function::getIntrinsicID(), and WriteValueSymbolTable().
template<typename ValueTy> static StringMapEntry& llvm::StringMapEntry< ValueTy >::GetStringMapEntryFromKeyData (const char * KeyData) inline static
GetStringMapEntryFromKeyData - Given key data that is known to be embedded into a StringMapEntry, return the StringMapEntry itself.
Definition at line 209 of file StringMap.h.
template<typename ValueTy> static StringMapEntry& llvm::StringMapEntry< ValueTy >::GetStringMapEntryFromValue (ValueTy & V) inline static
GetStringMapEntryFromValue - Given a value that is known to be embedded into a StringMapEntry, return the StringMapEntry itself.
Definition at line 196 of file StringMap.h.
References llvm::StringMapEntry< ValueTy >::second.
template<typename ValueTy> static const StringMapEntry& llvm::StringMapEntry< ValueTy >::GetStringMapEntryFromValue (const ValueTy & V) inline static
Definition at line 203 of file StringMap.h.
template<typename ValueTy> const ValueTy& llvm::StringMapEntry< ValueTy >::getValue () const inline
Definition at line 132 of file StringMap.h.
Referenced by llvm::PooledStringPtr::clear(), llvm::MDString::get(), getBinOpPrecedence(), llvm::ConstantDataSequential::getImpl(), llvm::StringToOffsetTable::GetOrAddStringOffset(), llvm::DwarfDebug::getOrCreateSourceID(), llvm::MCContext::GetOrCreateSymbol(), llvm::StringPool::intern(), llvm::SpecialCaseList::isIn(), llvm::PooledStringPtr::operator=(), llvm::PooledStringPtr::PooledStringPtr(), and llvm::ValueSymbolTable::~ValueSymbolTable().
template<typename ValueTy> ValueTy& llvm::StringMapEntry< ValueTy >::getValue () inline
Definition at line 133 of file StringMap.h.
template<typename ValueTy> void llvm::StringMapEntry< ValueTy >::setValue (const ValueTy & V) inline
Definition at line 135 of file StringMap.h.
Referenced by llvm::sys::getHostCPUName(), llvm::StringToOffsetTable::GetOrAddStringOffset(), llvm::MCContext::GetOrCreateSymbol(), LTOModule::makeLTOModule(), llvm::Value::setName(), llvm::Value::takeName(), llvm::GCModuleInfo::~GCModuleInfo(), and llvm::ValueSymbolTable::~ValueSymbolTable().
Member Data Documentation
template<typename ValueTy> ValueTy llvm::StringMapEntry< ValueTy >::second
Definition at line 121 of file StringMap.h.
Referenced by llvm::RuntimeDyldImpl::addRelocationForSymbol(), GetOptionInfo(), getOptionPred(), llvm::PassRegistry::getPassInfo(), llvm::StringMapEntry< ValueTy >::GetStringMapEntryFromValue(), llvm::RuntimeDyldImpl::getSymbolAddress(), llvm::RuntimeDyldImpl::getSymbolLoadAddress(), llvm::StringMapEntryInitializer< ValueTy >::Initialize(), llvm::StringMap< std::pair< llvm::Type *, llvm::SMLoc > >::lookup(), LookupOption(), llvm::RuntimeDyldMachO::processRelocationRef(), llvm::RuntimeDyldELF::processRelocationRef(), and llvm::RuntimeDyldImpl::resolveExternalSymbols().
The documentation for this class was generated from the following file:
StringMap.h