LLVM: llvm::NVPTXRegisterInfo Class Reference
LLVM API Documentation
llvm::NVPTXRegisterInfo Class Reference
#include <NVPTXRegisterInfo.h>
Public Member Functions
NVPTXRegisterInfo (const NVPTXSubtarget &st)
virtual const uint16_t * getCalleeSavedRegs (const MachineFunction *MF=0) const
NVPTX Callee Saved Registers.
virtual const TargetRegisterClass *const * getCalleeSavedRegClasses (const MachineFunction *MF) const
virtual BitVector getReservedRegs (const MachineFunction &MF) const
virtual void eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=NULL) const
virtual int getDwarfRegNum (unsigned RegNum, bool isEH) const
virtual unsigned getFrameRegister (const MachineFunction &MF) const
virtual unsigned getRARegister () const
ManagedStringPool * getStrPool () const
const char * getName (unsigned RegNo) const
Detailed Description
Definition at line 31 of file NVPTXRegisterInfo.h.
Constructor & Destructor Documentation
NVPTXRegisterInfo::NVPTXRegisterInfo (const NVPTXSubtarget & st)
Definition at line 74 of file NVPTXRegisterInfo.cpp.
Member Function Documentation
void NVPTXRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = NULL) const virtual
Definition at line 99 of file NVPTXRegisterInfo.cpp.
References llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::ISD::FrameIndex, llvm::MachineFunction::getFrameInfo(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), and llvm::A64CC::MI.
const TargetRegisterClass *const * NVPTXRegisterInfo::getCalleeSavedRegClasses (const MachineFunction * MF) const virtual
Definition at line 89 of file NVPTXRegisterInfo.cpp.
const uint16_t * NVPTXRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF = 0) const virtual
NVPTX Callee Saved Registers.
Definition at line 82 of file NVPTXRegisterInfo.cpp.
int NVPTXRegisterInfo::getDwarfRegNum (unsigned RegNum, bool isEH) const virtual
Definition at line 116 of file NVPTXRegisterInfo.cpp.
unsigned NVPTXRegisterInfo::getFrameRegister (const MachineFunction & MF) const virtual
Definition at line 120 of file NVPTXRegisterInfo.cpp.
const char* llvm::NVPTXRegisterInfo::getName (unsigned RegNo) const inline
Definition at line 66 of file NVPTXRegisterInfo.h.
References llvm::c_str(), llvm::ManagedStringPool::getManagedString(), llvm::getNVPTXRegClassName(), llvm::getNVPTXRegClassStr(), and getStrPool().
unsigned NVPTXRegisterInfo::getRARegister () const virtual
Definition at line 124 of file NVPTXRegisterInfo.cpp.
BitVector NVPTXRegisterInfo::getReservedRegs (const MachineFunction & MF) const virtual
Definition at line 94 of file NVPTXRegisterInfo.cpp.
ManagedStringPool* llvm::NVPTXRegisterInfo::getStrPool () const inline
Definition at line 62 of file NVPTXRegisterInfo.h.
Referenced by getName().
The documentation for this class was generated from the following files:
NVPTXRegisterInfo.h
NVPTXRegisterInfo.cpp