LLVM: llvm::value_use_iterator< UserTy > Class Template Reference
LLVM API Documentation
llvm::value_use_iterator< UserTy > Class Template Reference
#include <Use.h>
Public Types
typedef super::reference reference
typedef super::pointer pointer
Public Member Functions
value_use_iterator ()
bool operator== (const _Self &x) const
bool operator!= (const _Self &x) const
bool atEnd () const
atEnd - return true if this iterator is equal to use_end() on the value.
_Self & operator++ ()
_Self operator++ (int)
UserTy * operator* () const
UserTy * operator-> () const
Use & getUse () const
unsigned getOperandNo () const
Friends
class Value
Detailed Description
template<typename UserTy>
class llvm::value_use_iterator< UserTy >
Definition at line 168 of file Use.h.
Member Typedef Documentation
template<typename UserTy> typedef super::pointer llvm::value_use_iterator< UserTy >::pointer
Definition at line 178 of file Use.h.
template<typename UserTy> typedef super::reference llvm::value_use_iterator< UserTy >::reference
Definition at line 177 of file Use.h.
Constructor & Destructor Documentation
template<typename UserTy> llvm::value_use_iterator< UserTy >::value_use_iterator () inline
Definition at line 180 of file Use.h.
Member Function Documentation
template<typename UserTy> bool llvm::value_use_iterator< UserTy >::atEnd () const inline
atEnd - return true if this iterator is equal to use_end() on the value.
Definition at line 190 of file Use.h.
template<typename UserTy > unsigned llvm::value_use_iterator< UserTy >::getOperandNo () const
getOperandNo - Return the operand # of this use in its User. Defined in User.h
Definition at line 199 of file User.h.
Referenced by NumRetVals().
template<typename UserTy> Use& llvm::value_use_iterator< UserTy >::getUse () const inline
Definition at line 210 of file Use.h.
References DEFINE_SIMPLE_CONVERSION_FUNCTIONS.
Referenced by llvm::createMergeFunctionsPass(), llvm::InstCombiner::DoOneIteration(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getArgumentNo(), llvm::PHINode::getIncomingBlock(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::isCallee(), LLVMGetFirstUse(), OptimizeGlobalAddressOfMalloc(), and llvm::BitcodeReaderValueList::ResolveConstantForwardRefs().
template<typename UserTy> bool llvm::value_use_iterator< UserTy >::operator!= (const _Self & x) const inline
Definition at line 185 of file Use.h.
References llvm::operator==().
template<typename UserTy> UserTy* llvm::value_use_iterator< UserTy >::operator* () const inline
Definition at line 203 of file Use.h.
template<typename UserTy> _Self& llvm::value_use_iterator< UserTy >::operator++ () inline
Definition at line 193 of file Use.h.
template<typename UserTy> _Self llvm::value_use_iterator< UserTy >::operator++ (int) inline
Definition at line 198 of file Use.h.
template<typename UserTy> UserTy* llvm::value_use_iterator< UserTy >::operator-> () const inline
Definition at line 208 of file Use.h.
template<typename UserTy> bool llvm::value_use_iterator< UserTy >::operator== (const _Self & x) const inline
Definition at line 182 of file Use.h.
Friends And Related Function Documentation
template<typename UserTy> friend class Value friend
Definition at line 175 of file Use.h.
The documentation for this class was generated from the following files:
Use.h
User.h