LLVM: llvm::object::ObjectFile Class Reference
LLVM API Documentation
llvm::object::ObjectFile Class Reference abstract
#include <ObjectFile.h>
Public Member Functions
virtual symbol_iterator begin_symbols () const =0
virtual symbol_iterator end_symbols () const =0
virtual symbol_iterator begin_dynamic_symbols () const =0
virtual symbol_iterator end_dynamic_symbols () const =0
virtual section_iterator begin_sections () const =0
virtual section_iterator end_sections () const =0
virtual library_iterator begin_libraries_needed () const =0
virtual library_iterator end_libraries_needed () const =0
virtual uint8_t getBytesInAddress () const =0
The number of bytes used to represent an address in this object file format.
virtual StringRef getFileFormatName () const =0
virtual unsigned getArch () const =0
virtual StringRef getLoadName () const =0
Public Member Functions inherited from llvm::object::Binary
virtual ~Binary ()
StringRef getData () const
StringRef getFileName () const
unsigned int getType () const
bool isObject () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isLittleEndian () const
Static Public Member Functions
static ObjectFile * createObjectFile (StringRef ObjectPath)
Create ObjectFile from path.
static ObjectFile * createObjectFile (MemoryBuffer *Object)
static bool classof (const Binary *v)
static ObjectFile * createCOFFObjectFile (MemoryBuffer *Object)
static ObjectFile * createELFObjectFile (MemoryBuffer *Object)
static ObjectFile * createMachOObjectFile (MemoryBuffer *Object)
Protected Member Functions
ObjectFile (unsigned int Type, MemoryBuffer *source)
const uint8_t * base () const
virtual error_code getSymbolNext (DataRefImpl Symb, SymbolRef &Res) const =0
virtual error_code getSymbolName (DataRefImpl Symb, StringRef &Res) const =0
virtual error_code getSymbolAddress (DataRefImpl Symb, uint64_t &Res) const =0
virtual error_code getSymbolFileOffset (DataRefImpl Symb, uint64_t &Res) const =0
virtual error_code getSymbolAlignment (DataRefImpl Symb, uint32_t &Res) const
virtual error_code getSymbolSize (DataRefImpl Symb, uint64_t &Res) const =0
virtual error_code getSymbolType (DataRefImpl Symb, SymbolRef::Type &Res) const =0
virtual error_code getSymbolFlags (DataRefImpl Symb, uint32_t &Res) const =0
virtual error_code getSymbolSection (DataRefImpl Symb, section_iterator &Res) const =0
virtual error_code getSymbolValue (DataRefImpl Symb, uint64_t &Val) const =0
virtual error_code getSectionNext (DataRefImpl Sec, SectionRef &Res) const =0
virtual error_code getSectionName (DataRefImpl Sec, StringRef &Res) const =0
virtual error_code getSectionAddress (DataRefImpl Sec, uint64_t &Res) const =0
virtual error_code getSectionSize (DataRefImpl Sec, uint64_t &Res) const =0
virtual error_code getSectionContents (DataRefImpl Sec, StringRef &Res) const =0
virtual error_code getSectionAlignment (DataRefImpl Sec, uint64_t &Res) const =0
virtual error_code isSectionText (DataRefImpl Sec, bool &Res) const =0
virtual error_code isSectionData (DataRefImpl Sec, bool &Res) const =0
virtual error_code isSectionBSS (DataRefImpl Sec, bool &Res) const =0
virtual error_code isSectionRequiredForExecution (DataRefImpl Sec, bool &Res) const =0
virtual error_code isSectionVirtual (DataRefImpl Sec, bool &Res) const =0
virtual error_code isSectionZeroInit (DataRefImpl Sec, bool &Res) const =0
virtual error_code isSectionReadOnlyData (DataRefImpl Sec, bool &Res) const =0
virtual error_code sectionContainsSymbol (DataRefImpl Sec, DataRefImpl Symb, bool &Result) const =0
virtual relocation_iterator section_rel_begin (DataRefImpl Sec) const =0
virtual relocation_iterator section_rel_end (DataRefImpl Sec) const =0
virtual section_iterator getRelocatedSection (DataRefImpl Sec) const
virtual error_code getRelocationNext (DataRefImpl Rel, RelocationRef &Res) const =0
virtual error_code getRelocationAddress (DataRefImpl Rel, uint64_t &Res) const =0
virtual error_code getRelocationOffset (DataRefImpl Rel, uint64_t &Res) const =0
virtual symbol_iterator getRelocationSymbol (DataRefImpl Rel) const =0
virtual error_code getRelocationType (DataRefImpl Rel, uint64_t &Res) const =0
virtual error_code getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > &Result) const =0
virtual error_code getRelocationValueString (DataRefImpl Rel, SmallVectorImpl< char > &Result) const =0
virtual error_code getRelocationHidden (DataRefImpl Rel, bool &Result) const
virtual error_code getLibraryNext (DataRefImpl Lib, LibraryRef &Res) const =0
virtual error_code getLibraryPath (DataRefImpl Lib, StringRef &Res) const =0
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBuffer *Source)
Friends
class SymbolRef
class SectionRef
class RelocationRef
class LibraryRef
Additional Inherited Members
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive, ID_MachOUniversalBinary, ID_StartObjects, ID_COFF,
ID_ELF32L, ID_ELF32B, ID_ELF64L, ID_ELF64B,
ID_MachO32L, ID_MachO32B, ID_MachO64L, ID_MachO64B,
ID_EndObjects
}
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBuffer * Data
Detailed Description
ObjectFile - This class is the base class for all object file types. Concrete instances of this object are created by createObjectFile, which figures out which type to create.
Definition at line 266 of file ObjectFile.h.
Constructor & Destructor Documentation
ObjectFile::ObjectFile (unsigned int Type, MemoryBuffer * source) protected
Definition at line 26 of file ObjectFile.cpp.
Member Function Documentation
const uint8_t* llvm::object::ObjectFile::base () const inline protected
Definition at line 274 of file ObjectFile.h.
Referenced by llvm::object::COFFObjectFile::COFFObjectFile(), llvm::object::COFFObjectFile::getRvaPtr(), llvm::object::ELFObjectFile< ELFT >::getSectionContents(), llvm::object::COFFObjectFile::getSymbolAuxData(), llvm::object::COFFObjectFile::section_rel_begin(), and llvm::object::COFFObjectFile::section_rel_end().
virtual symbol_iterator llvm::object::ObjectFile::begin_dynamic_symbols () const pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, and llvm::object::MachOObjectFile.
virtual library_iterator llvm::object::ObjectFile::begin_libraries_needed () const pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, and llvm::object::MachOObjectFile.
virtual section_iterator llvm::object::ObjectFile::begin_sections () const pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, and llvm::object::MachOObjectFile.
Referenced by llvm::ObjectImageCommon::begin_sections(), llvm::MCObjectDisassembler::buildModule(), llvm::DWARFContextInMemory::DWARFContextInMemory(), llvm::RuntimeDyldImpl::emitSection(), and llvm::MCObjectSymbolizer::findRelocationAt().
virtual symbol_iterator llvm::object::ObjectFile::begin_symbols () const pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, and llvm::object::MachOObjectFile.
Referenced by llvm::ObjectImageCommon::begin_symbols(), llvm::MCObjectDisassembler::getEntrypoint(), RemoveDupsFromAddressVector(), and llvm::MCObjectSymbolizer::tryAddingSymbolicOperand().
static bool llvm::object::ObjectFile::classof (const Binary * v) inline static
Definition at line 382 of file ObjectFile.h.
References llvm::object::Binary::isObject().
ObjectFile * llvm::ObjectFile::createCOFFObjectFile (MemoryBuffer * Object) static
Definition at line 933 of file COFFObjectFile.cpp.
References llvm::object::COFFObjectFile::COFFObjectFile().
Referenced by llvm::object::createBinary(), and createObjectFile().
ObjectFile * llvm::ObjectFile::createELFObjectFile (MemoryBuffer * Object) static
Definition at line 21 of file ELFObjectFile.cpp.
References llvm::countTrailingZeros(), llvm::ELF::ELFCLASS32, llvm::ELF::ELFCLASS64, llvm::ELF::ELFDATA2LSB, llvm::ELF::ELFDATA2MSB, llvm::MemoryBuffer::getBufferStart(), llvm::object::getElfArchType(), llvm_unreachable, and llvm::report_fatal_error().
Referenced by llvm::object::createBinary(), and createObjectFile().
ObjectFile * llvm::object::ObjectFile::createMachOObjectFile (MemoryBuffer * Object) static
Definition at line 1582 of file MachOObjectFile.cpp.
References llvm::MemoryBuffer::getBuffer(), llvm::object::MachOObjectFile::MachOObjectFile(), Magic, llvm::OwningPtr< T >::reset(), llvm::AArch64ISD::Ret, llvm::StringRef::slice(), and llvm::OwningPtr< T >::take().
Referenced by llvm::object::createBinary(), createObjectFile(), and llvm::object::MachOUniversalBinary::ObjectForArch::getAsObjectFile().
ObjectFile * ObjectFile::createObjectFile (StringRef ObjectPath) static
Create ObjectFile from path.
Returns
Pointer to ObjectFile subclass to handle this type of object.
Parameters
ObjectPath The path to the object file. ObjectPath.isObject must return true.
Definition at line 79 of file ObjectFile.cpp.
References llvm::ARMBuildAttrs::File, llvm::MemoryBuffer::getFile(), and llvm::OwningPtr< T >::take().
Referenced by llvm::DWARFUnit::getDWOId(), LLVMCreateObjectFile(), and llvm::ObjectImageCommon::ObjectImageCommon().
ObjectFile * ObjectFile::createObjectFile (MemoryBuffer * Object) static
Definition at line 40 of file ObjectFile.cpp.
References llvm::sys::fs::file_magic::archive, llvm::sys::fs::file_magic::bitcode, llvm::sys::fs::file_magic::coff_import_library, llvm::sys::fs::file_magic::coff_object, createCOFFObjectFile(), createELFObjectFile(), createMachOObjectFile(), llvm::sys::fs::file_magic::elf_core, llvm::sys::fs::file_magic::elf_executable, llvm::sys::fs::file_magic::elf_relocatable, llvm::sys::fs::file_magic::elf_shared_object, llvm::MemoryBuffer::getBuffer(), llvm::MemoryBuffer::getBufferSize(), llvm::sys::fs::identify_magic(), llvm_unreachable, llvm::sys::fs::file_magic::macho_bundle, llvm::sys::fs::file_magic::macho_core, llvm::sys::fs::file_magic::macho_dsym_companion, llvm::sys::fs::file_magic::macho_dynamic_linker, llvm::sys::fs::file_magic::macho_dynamically_linked_shared_lib, llvm::sys::fs::file_magic::macho_dynamically_linked_shared_lib_stub, llvm::sys::fs::file_magic::macho_executable, llvm::sys::fs::file_magic::macho_fixed_virtual_memory_shared_lib, llvm::sys::fs::file_magic::macho_object, llvm::sys::fs::file_magic::macho_preload_executable, llvm::sys::fs::file_magic::macho_universal_binary, llvm::sys::fs::file_magic::pecoff_executable, llvm::sys::fs::file_magic::unknown, and llvm::sys::fs::file_magic::windows_resource.
virtual symbol_iterator llvm::object::ObjectFile::end_dynamic_symbols () const pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, and llvm::object::MachOObjectFile.
virtual library_iterator llvm::object::ObjectFile::end_libraries_needed () const pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, and llvm::object::MachOObjectFile.
virtual section_iterator llvm::object::ObjectFile::end_sections () const pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, and llvm::object::MachOObjectFile.
Referenced by llvm::MCObjectDisassembler::buildModule(), llvm::DWARFContextInMemory::DWARFContextInMemory(), llvm::RuntimeDyldImpl::emitSection(), llvm::ObjectImageCommon::end_sections(), and llvm::MCObjectSymbolizer::findRelocationAt().
virtual symbol_iterator llvm::object::ObjectFile::end_symbols () const pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, and llvm::object::MachOObjectFile.
Referenced by llvm::ObjectImageCommon::end_symbols(), llvm::MCObjectDisassembler::getEntrypoint(), RemoveDupsFromAddressVector(), and llvm::MCObjectSymbolizer::tryAddingSymbolicOperand().
virtual unsigned llvm::object::ObjectFile::getArch () const pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, and llvm::object::MachOObjectFile.
Referenced by llvm::ObjectImageCommon::getArch().
virtual uint8_t llvm::object::ObjectFile::getBytesInAddress () const pure virtual
The number of bytes used to represent an address in this object file format.
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, and llvm::object::MachOObjectFile.
virtual StringRef llvm::object::ObjectFile::getFileFormatName () const pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, and llvm::object::MachOObjectFile.
Referenced by llvm::DWARFContextInMemory::DWARFContextInMemory().
virtual error_code llvm::object::ObjectFile::getLibraryNext (DataRefImpl Lib, LibraryRef & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::LibraryRef::getNext().
virtual error_code llvm::object::ObjectFile::getLibraryPath (DataRefImpl Lib, StringRef & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::LibraryRef::getPath().
virtual StringRef llvm::object::ObjectFile::getLoadName () const pure virtual
For shared objects, returns the name which this object should be loaded from at runtime. This corresponds to DT_SONAME on ELF and LC_ID_DYLIB (install name) on MachO.
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, and llvm::object::MachOObjectFile.
section_iterator ObjectFile::getRelocatedSection (DataRefImpl Sec) const protected virtual
Reimplemented in llvm::object::ELFObjectFile< ELFT >.
Definition at line 36 of file ObjectFile.cpp.
References SectionRef.
Referenced by llvm::object::SectionRef::getRelocatedSection().
virtual error_code llvm::object::ObjectFile::getRelocationAddress (DataRefImpl Rel, uint64_t & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, and llvm::object::MachOObjectFile.
Referenced by llvm::object::RelocationRef::getAddress().
virtual error_code llvm::object::ObjectFile::getRelocationHidden (DataRefImpl Rel, bool & Result) const inline protected virtual
Reimplemented in llvm::object::MachOObjectFile.
Definition at line 339 of file ObjectFile.h.
References llvm::object::object_error::success.
Referenced by llvm::object::RelocationRef::getHidden().
virtual error_code llvm::object::ObjectFile::getRelocationNext (DataRefImpl Rel, RelocationRef & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, and llvm::object::MachOObjectFile.
Referenced by llvm::object::RelocationRef::getNext().
virtual error_code llvm::object::ObjectFile::getRelocationOffset (DataRefImpl Rel, uint64_t & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, and llvm::object::MachOObjectFile.
Referenced by llvm::object::RelocationRef::getOffset().
virtual symbol_iterator llvm::object::ObjectFile::getRelocationSymbol (DataRefImpl Rel) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, and llvm::object::MachOObjectFile.
Referenced by llvm::object::RelocationRef::getSymbol().
virtual error_code llvm::object::ObjectFile::getRelocationType (DataRefImpl Rel, uint64_t & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, and llvm::object::MachOObjectFile.
Referenced by llvm::object::RelocationRef::getType().
virtual error_code llvm::object::ObjectFile::getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > & Result) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, and llvm::object::MachOObjectFile.
Referenced by llvm::object::RelocationRef::getTypeName().
virtual error_code llvm::object::ObjectFile::getRelocationValueString (DataRefImpl Rel, SmallVectorImpl< char > & Result) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::ELFObjectFile< ELFT >, and llvm::object::MachOObjectFile.
Referenced by llvm::object::RelocationRef::getValueString().
virtual error_code llvm::object::ObjectFile::getSectionAddress (DataRefImpl Sec, uint64_t & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SectionRef::getAddress().
virtual error_code llvm::object::ObjectFile::getSectionAlignment (DataRefImpl Sec, uint64_t & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SectionRef::getAlignment().
virtual error_code llvm::object::ObjectFile::getSectionContents (DataRefImpl Sec, StringRef & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SectionRef::getContents().
virtual error_code llvm::object::ObjectFile::getSectionName (DataRefImpl Sec, StringRef & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SectionRef::getName().
virtual error_code llvm::object::ObjectFile::getSectionNext (DataRefImpl Sec, SectionRef & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SectionRef::getNext().
virtual error_code llvm::object::ObjectFile::getSectionSize (DataRefImpl Sec, uint64_t & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SectionRef::getSize().
virtual error_code llvm::object::ObjectFile::getSymbolAddress (DataRefImpl Symb, uint64_t & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SymbolRef::getAddress().
error_code ObjectFile::getSymbolAlignment (DataRefImpl Symb, uint32_t & Res) const protected virtual
Reimplemented in llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Definition at line 30 of file ObjectFile.cpp.
References llvm::object::object_error::success.
Referenced by llvm::object::SymbolRef::getAlignment().
virtual error_code llvm::object::ObjectFile::getSymbolFileOffset (DataRefImpl Symb, uint64_t & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SymbolRef::getFileOffset().
virtual error_code llvm::object::ObjectFile::getSymbolFlags (DataRefImpl Symb, uint32_t & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SymbolRef::getFlags().
virtual error_code llvm::object::ObjectFile::getSymbolName (DataRefImpl Symb, StringRef & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SymbolRef::getName().
virtual error_code llvm::object::ObjectFile::getSymbolNext (DataRefImpl Symb, SymbolRef & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SymbolRef::getNext().
virtual error_code llvm::object::ObjectFile::getSymbolSection (DataRefImpl Symb, section_iterator & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SymbolRef::getSection().
virtual error_code llvm::object::ObjectFile::getSymbolSize (DataRefImpl Symb, uint64_t & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SymbolRef::getSize().
virtual error_code llvm::object::ObjectFile::getSymbolType (DataRefImpl Symb, SymbolRef::Type & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SymbolRef::getType().
virtual error_code llvm::object::ObjectFile::getSymbolValue (DataRefImpl Symb, uint64_t & Val) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SymbolRef::getValue().
virtual error_code llvm::object::ObjectFile::isSectionBSS (DataRefImpl Sec, bool & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SectionRef::isBSS().
virtual error_code llvm::object::ObjectFile::isSectionData (DataRefImpl Sec, bool & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SectionRef::isData().
virtual error_code llvm::object::ObjectFile::isSectionReadOnlyData (DataRefImpl Sec, bool & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SectionRef::isReadOnlyData().
virtual error_code llvm::object::ObjectFile::isSectionRequiredForExecution (DataRefImpl Sec, bool & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SectionRef::isRequiredForExecution().
virtual error_code llvm::object::ObjectFile::isSectionText (DataRefImpl Sec, bool & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SectionRef::isText().
virtual error_code llvm::object::ObjectFile::isSectionVirtual (DataRefImpl Sec, bool & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SectionRef::isVirtual().
virtual error_code llvm::object::ObjectFile::isSectionZeroInit (DataRefImpl Sec, bool & Res) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SectionRef::isZeroInit().
virtual relocation_iterator llvm::object::ObjectFile::section_rel_begin (DataRefImpl Sec) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SectionRef::begin_relocations().
virtual relocation_iterator llvm::object::ObjectFile::section_rel_end (DataRefImpl Sec) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SectionRef::end_relocations().
virtual error_code llvm::object::ObjectFile::sectionContainsSymbol (DataRefImpl Sec, DataRefImpl Symb, bool & Result) const protected pure virtual
Implemented in llvm::object::COFFObjectFile, llvm::object::MachOObjectFile, and llvm::object::ELFObjectFile< ELFT >.
Referenced by llvm::object::SectionRef::containsSymbol().
Friends And Related Function Documentation
friend class LibraryRef friend
Definition at line 345 of file ObjectFile.h.
Referenced by llvm::object::ELFObjectFile< ELFT >::begin_libraries_needed(), llvm::object::ELFObjectFile< ELFT >::end_libraries_needed(), and llvm::object::ELFObjectFile< ELFT >::getLibraryNext().
friend class RelocationRef friend
Definition at line 325 of file ObjectFile.h.
Referenced by llvm::object::ELFObjectFile< ELFT >::getRelocationNext(), llvm::object::MachOObjectFile::getRelocationNext(), llvm::object::COFFObjectFile::getRelocationNext(), llvm::object::ELFObjectFile< ELFT >::section_rel_begin(), llvm::object::MachOObjectFile::section_rel_begin(), llvm::object::COFFObjectFile::section_rel_begin(), llvm::object::ELFObjectFile< ELFT >::section_rel_end(), llvm::object::MachOObjectFile::section_rel_end(), and llvm::object::COFFObjectFile::section_rel_end().
friend class SectionRef friend
Definition at line 302 of file ObjectFile.h.
Referenced by llvm::object::MachOObjectFile::begin_sections(), llvm::object::ELFObjectFile< ELFT >::begin_sections(), llvm::object::COFFObjectFile::begin_sections(), llvm::object::MachOObjectFile::end_sections(), llvm::object::ELFObjectFile< ELFT >::end_sections(), llvm::object::COFFObjectFile::end_sections(), llvm::object::ELFObjectFile< ELFT >::getRelocatedSection(), getRelocatedSection(), llvm::object::MachOObjectFile::getRelocationSection(), llvm::object::ELFObjectFile< ELFT >::getSectionNext(), llvm::object::MachOObjectFile::getSectionNext(), llvm::object::COFFObjectFile::getSectionNext(), llvm::object::ELFObjectFile< ELFT >::getSymbolSection(), llvm::object::MachOObjectFile::getSymbolSection(), and llvm::object::COFFObjectFile::getSymbolSection().
friend class SymbolRef friend
Definition at line 286 of file ObjectFile.h.
Referenced by llvm::object::ELFObjectFile< ELFT >::begin_dynamic_symbols(), llvm::object::MachOObjectFile::begin_symbols(), llvm::object::ELFObjectFile< ELFT >::begin_symbols(), llvm::object::COFFObjectFile::begin_symbols(), llvm::object::ELFObjectFile< ELFT >::end_dynamic_symbols(), llvm::object::MachOObjectFile::end_symbols(), llvm::object::ELFObjectFile< ELFT >::end_symbols(), llvm::object::COFFObjectFile::end_symbols(), llvm::object::ELFObjectFile< ELFT >::getRelocationSymbol(), llvm::object::MachOObjectFile::getRelocationSymbol(), llvm::object::COFFObjectFile::getRelocationSymbol(), llvm::object::ELFObjectFile< ELFT >::getSymbolNext(), llvm::object::MachOObjectFile::getSymbolNext(), and llvm::object::COFFObjectFile::getSymbolNext().
The documentation for this class was generated from the following files:
ObjectFile.h
COFFObjectFile.cpp
ELFObjectFile.cpp
MachOObjectFile.cpp
ObjectFile.cpp