LLVM: llvm::MCLabel Class Reference
LLVM API Documentation
llvm::MCLabel Class Reference
#include <MCLabel.h>
Public Member Functions
unsigned getInstance () const
getInstance - Get the current instance of this Directional Local Label.
unsigned incInstance ()
void print (raw_ostream &OS) const
print - Print the value to the stream OS.
void dump () const
dump - Print the value to stderr.
Friends
class MCContext
Detailed Description
MCLabel - Instances of this class represent a label name in the MC file, and MCLabel are created and unique'd by the MCContext class. MCLabel should only be constructed for valid instances in the object file.
Definition at line 26 of file MCLabel.h.
Member Function Documentation
void MCLabel::dump () const
dump - Print the value to stderr.
Definition at line 20 of file MCLabel.cpp.
References llvm::dbgs(), and print().
Referenced by incInstance().
unsigned llvm::MCLabel::getInstance () const inline
getInstance - Get the current instance of this Directional Local Label.
Definition at line 39 of file MCLabel.h.
Referenced by llvm::MCContext::CreateTempSymbol(), and print().
unsigned llvm::MCLabel::incInstance () inline
incInstance - Increment the current instance of this Directional Local Label.
Definition at line 43 of file MCLabel.h.
References dump(), and print().
Referenced by llvm::MCContext::CreateTempSymbol().
void MCLabel::print (raw_ostream & OS) const
print - Print the value to the stream OS.
Definition at line 15 of file MCLabel.cpp.
References getInstance().
Referenced by dump(), incInstance(), and llvm::operator<<().
Friends And Related Function Documentation
friend class MCContext friend
Definition at line 31 of file MCLabel.h.
The documentation for this class was generated from the following files:
MCLabel.h
MCLabel.cpp