LLVM: llvm::RecordKeeper Class Reference
LLVM API Documentation
llvm::RecordKeeper Class Reference
#include <Record.h>
Public Member Functions
~RecordKeeper ()
const std::map< std::string, Record * > & getClasses () const
const std::map< std::string, Record * > & getDefs () const
Record * getClass (const std::string &Name) const
Record * getDef (const std::string &Name) const
void addClass (Record *R)
void addDef (Record *R)
void removeClass (const std::string &Name)
void removeDef (const std::string &Name)
std::vector< Record * > getAllDerivedDefinitions (const std::string &ClassName) const
void dump () const
Detailed Description
Definition at line 1647 of file Record.h.
Constructor & Destructor Documentation
llvm::RecordKeeper::~RecordKeeper () inline
Definition at line 1651 of file Record.h.
References for, and I.
Member Function Documentation
void llvm::RecordKeeper::addClass (Record * R) inline
Definition at line 1671 of file Record.h.
References llvm::Record::getName(), and llvm::MipsISD::Ins.
void llvm::RecordKeeper::addDef (Record * R) inline
Definition at line 1676 of file Record.h.
References llvm::Record::getName(), and llvm::MipsISD::Ins.
void RecordKeeper::dump () const
Definition at line 1995 of file Record.cpp.
References llvm::errs().
std::vector< Record * > RecordKeeper::getAllDerivedDefinitions (const std::string & ClassName) const
getAllDerivedDefinitions - This method returns all concrete definitions that derive from the specified class name. If a class with the specified name does not exist, an exception is thrown.
getAllDerivedDefinitions - This method returns all concrete definitions that derive from the specified class name. If a class with the specified name does not exist, an error is printed and true is returned.
Definition at line 2017 of file Record.cpp.
References llvm::sys::path::begin(), llvm::tgtok::Class, llvm::sys::path::end(), I, and llvm::PrintFatalError().
Record* llvm::RecordKeeper::getClass (const std::string & Name) const inline
Definition at line 1663 of file Record.h.
References I.
const std::map<std::string, Record*>& llvm::RecordKeeper::getClasses () const inline
Definition at line 1660 of file Record.h.
Referenced by llvm::operator<<().
Record* llvm::RecordKeeper::getDef (const std::string & Name) const inline
Definition at line 1667 of file Record.h.
References I.
const std::map<std::string, Record*>& llvm::RecordKeeper::getDefs () const inline
Definition at line 1661 of file Record.h.
Referenced by llvm::operator<<().
void llvm::RecordKeeper::removeClass (const std::string & Name) inline
removeClass - Remove, but do not delete, the specified record.
Definition at line 1684 of file Record.h.
void llvm::RecordKeeper::removeDef (const std::string & Name) inline
removeDef - Remove, but do not delete, the specified record.
Definition at line 1690 of file Record.h.
References llvm::RecTy::dump().
The documentation for this class was generated from the following files:
Record.h
Record.cpp