LLVM: llvm::X86Disassembler::X86GenericDisassembler Class Reference
LLVM API Documentation
llvm::X86Disassembler::X86GenericDisassembler Class Reference
#include <X86Disassembler.h>
Public Member Functions
X86GenericDisassembler (const MCSubtargetInfo &STI, DisassemblerMode mode, const MCInstrInfo *MII)
DecodeStatus getInstruction (MCInst &instr, uint64_t &size, const MemoryObject &region, uint64_t address, raw_ostream &vStream, raw_ostream &cStream) const
getInstruction - See MCDisassembler.
Public Member Functions inherited from llvm::MCDisassembler
MCDisassembler (const MCSubtargetInfo &STI)
Constructor - Performs initial setup for the disassembler.
virtual ~MCDisassembler ()
bool tryAddingSymbolicOperand (MCInst &Inst, int64_t Value, uint64_t Address, bool IsBranch, uint64_t Offset, uint64_t InstSize) const
void tryAddingPcLoadReferenceComment (int64_t Value, uint64_t Address) const
void setSymbolizer (OwningPtr< MCSymbolizer > &Symzer)
void setupForSymbolicDisassembly (LLVMOpInfoCallback GetOpInfo, LLVMSymbolLookupCallback SymbolLookUp, void *DisInfo, MCContext *Ctx, OwningPtr< MCRelocationInfo > &RelInfo)
Sets up an external symbolizer that uses the C API callbacks.
LLVMOpInfoCallback getLLVMOpInfoCallback () const
LLVMSymbolLookupCallback getLLVMSymbolLookupCallback () const
void * getDisInfoBlock () const
MCContext * getMCContext () const
const MCSubtargetInfo & getSubtargetInfo () const
Additional Inherited Members
Public Types inherited from llvm::MCDisassembler
enum DecodeStatus { Fail = 0, SoftFail = 1, Success = 3 }
Public Attributes inherited from llvm::MCDisassembler
raw_ostream * CommentStream
Protected Attributes inherited from llvm::MCDisassembler
const MCSubtargetInfo & STI
OwningPtr< MCSymbolizer > Symbolizer
Detailed Description
X86GenericDisassembler - Generic disassembler for all X86 platforms. All each platform class should have to do is subclass the constructor, and provide a different disassemblerMode value.
Definition at line 103 of file X86Disassembler.h.
Constructor & Destructor Documentation
X86GenericDisassembler::X86GenericDisassembler (const MCSubtargetInfo & STI, DisassemblerMode mode, const MCInstrInfo * MII)
Constructor - Initializes the disassembler.
Parameters
mode - The X86 architecture mode to decode for.
Definition at line 75 of file X86Disassembler.cpp.
Member Function Documentation
MCDisassembler::DecodeStatus X86GenericDisassembler::getInstruction (MCInst & instr, uint64_t & size, const MemoryObject & region, uint64_t address, raw_ostream & vStream, raw_ostream & cStream) const virtual
getInstruction - See MCDisassembler.
Implements llvm::MCDisassembler.
Definition at line 115 of file X86Disassembler.cpp.
References llvm::MCDisassembler::CommentStream, decodeInstruction(), llvm::MCDisassembler::Fail, InternalInstruction::length, logger(), llvm::nulls(), InternalInstruction::readerCursor, regionReader(), ret(), llvm::MCDisassembler::Success, and translateInstruction().
The documentation for this class was generated from the following files:
X86Disassembler.h
X86Disassembler.cpp