LLVM: llvm::ObjectBufferStream Class Reference
LLVM API Documentation
llvm::ObjectBufferStream Class Reference
#include <ObjectBuffer.h>
Public Member Functions
ObjectBufferStream ()
virtual ~ObjectBufferStream ()
raw_ostream & getOStream ()
void flush ()
Public Member Functions inherited from llvm::ObjectBuffer
ObjectBuffer ()
ObjectBuffer (MemoryBuffer *Buf)
virtual ~ObjectBuffer ()
MemoryBuffer * getMemBuffer () const
const char * getBufferStart () const
size_t getBufferSize () const
StringRef getBuffer () const
Protected Attributes
SmallVector< char, 4096 > SV
raw_svector_ostream OS
Protected Attributes inherited from llvm::ObjectBuffer
OwningPtr< MemoryBuffer > Buffer
Detailed Description
ObjectBufferStream - This class encapsulates the SmallVector and raw_svector_ostream needed to generate an object using MC code emission while providing a common ObjectBuffer interface for access to the memory once the object has been generated.
Definition at line 59 of file ObjectBuffer.h.
Constructor & Destructor Documentation
llvm::ObjectBufferStream::ObjectBufferStream () inline
Definition at line 62 of file ObjectBuffer.h.
virtual llvm::ObjectBufferStream::~ObjectBufferStream () inline virtual
Definition at line 63 of file ObjectBuffer.h.
Member Function Documentation
void llvm::ObjectBufferStream::flush () inline
Definition at line 66 of file ObjectBuffer.h.
References llvm::ObjectBuffer::Buffer, and llvm::MemoryBuffer::getMemBuffer().
Referenced by llvm::MCJIT::emitObject().
raw_ostream& llvm::ObjectBufferStream::getOStream () inline
Definition at line 65 of file ObjectBuffer.h.
Referenced by llvm::MCJIT::emitObject().
Member Data Documentation
raw_svector_ostream llvm::ObjectBufferStream::OS protected
Definition at line 78 of file ObjectBuffer.h.
SmallVector<char, 4096> llvm::ObjectBufferStream::SV protected
Definition at line 77 of file ObjectBuffer.h.
The documentation for this class was generated from the following files:
ObjectBuffer.h
ExecutionEngine.cpp