LLVM: llvm::SplitEditor Class Reference
LLVM API Documentation
llvm::SplitEditor Class Reference
#include <SplitKit.h>
Public Types
enum ComplementSpillMode { SM_Partition, SM_Size, SM_Speed }
Public Member Functions
SplitEditor (SplitAnalysis &SA, LiveIntervals &, VirtRegMap &, MachineDominatorTree &, MachineBlockFrequencyInfo &)
Create a new SplitEditor for editing the LiveInterval analyzed by SA.
void reset (LiveRangeEdit &, ComplementSpillMode=SM_Partition)
reset - Prepare for a new split.
unsigned openIntv ()
Create a new virtual register and live interval.
unsigned currentIntv () const
currentIntv - Return the current interval index.
void selectIntv (unsigned Idx)
selectIntv - Select a previously opened interval index.
SlotIndex enterIntvBefore (SlotIndex Idx)
SlotIndex enterIntvAfter (SlotIndex Idx)
SlotIndex enterIntvAtEnd (MachineBasicBlock &MBB)
void useIntv (const MachineBasicBlock &MBB)
useIntv - indicate that all instructions in MBB should use OpenLI.
void useIntv (SlotIndex Start, SlotIndex End)
useIntv - indicate that all instructions in range should use OpenLI.
SlotIndex leaveIntvAfter (SlotIndex Idx)
SlotIndex leaveIntvBefore (SlotIndex Idx)
SlotIndex leaveIntvAtTop (MachineBasicBlock &MBB)
void overlapIntv (SlotIndex Start, SlotIndex End)
void finish (SmallVectorImpl< unsigned > *LRMap=0)
void dump () const
dump - print the current interval maping to dbgs().
void splitSingleBlock (const SplitAnalysis::BlockInfo &BI)
void splitLiveThroughBlock (unsigned MBBNum, unsigned IntvIn, SlotIndex LeaveBefore, unsigned IntvOut, SlotIndex EnterAfter)
void splitRegInBlock (const SplitAnalysis::BlockInfo &BI, unsigned IntvIn, SlotIndex LeaveBefore)
void splitRegOutBlock (const SplitAnalysis::BlockInfo &BI, unsigned IntvOut, SlotIndex EnterAfter)
Detailed Description
SplitEditor - Edit machine code and LiveIntervals for live range splitting.
Create a SplitEditor from a SplitAnalysis.
Start a new live interval with openIntv.
Mark the places where the new interval is entered using enterIntv*
Mark the ranges where the new interval is used with useIntv*
Mark the places where the interval is exited with exitIntv*.
Finish the current interval with closeIntv and repeat from 2.
Rewrite instructions with finish().
Definition at line 211 of file SplitKit.h.
Member Enumeration Documentation
enum llvm::SplitEditor::ComplementSpillMode
ComplementSpillMode - Select how the complement live range should be created. SplitEditor automatically creates interval 0 to contain anything that isn't added to another interval. This complement interval can get quite complicated, and it can sometimes be an advantage to allow it to overlap the other intervals. If it is going to spill anyway, no registers are wasted by keeping a value in two places at the same time.
Enumerator
SM_Partition
SM_Partition(Default) - Try to create the complement interval so it doesn't overlap any other intervals, and the original interval is partitioned. This may require a large number of back copies and extra PHI-defs. Only segments marked with overlapIntv will be overlapping.
SM_Size
SM_Size - Overlap intervals to minimize the number of inserted COPY instructions. Copies to the complement interval are hoisted to their common dominator, so only one COPY is required per value in the complement interval. This also means that no extra PHI-defs need to be inserted in the complement interval.
SM_Speed
SM_Speed - Overlap intervals to minimize the expected execution frequency of the inserted copies. This is very similar to SM_Size, but the complement interval may get some extra PHI-defs.
Definition at line 229 of file SplitKit.h.
Constructor & Destructor Documentation
SplitEditor::SplitEditor (SplitAnalysis & SA, LiveIntervals & lis, VirtRegMap & vrm, MachineDominatorTree & mdt, MachineBlockFrequencyInfo & mbfi)
Create a new SplitEditor for editing the LiveInterval analyzed by SA.
Create a new SplitEditor for editing the LiveInterval analyzed by SA. Newly created intervals will be appended to newIntervals.
Definition at line 325 of file SplitKit.cpp.
Member Function Documentation
unsigned llvm::SplitEditor::currentIntv () const inline
currentIntv - Return the current interval index.
Definition at line 365 of file SplitKit.h.
References llvm::dump().
void SplitEditor::dump () const
dump - print the current interval maping to dbgs().
Definition at line 362 of file SplitKit.cpp.
References llvm::LiveRange::addSegment(), llvm::IntervalMap< KeyT, ValT, N, Traits >::begin(), llvm::BuildMI(), llvm::LiveRangeEdit::canRematerializeAt(), llvm::IntervalMap< SlotIndex, unsigned >::const_iterator, llvm::TargetOpcode::COPY, llvm::dbgs(), llvm::tgtok::Def, llvm::VNInfo::def, llvm::IntervalMap< KeyT, ValT, N, Traits >::empty(), llvm::MCInstrInfo::get(), llvm::LiveRangeEdit::get(), llvm::SlotIndex::getDeadSlot(), llvm::LiveIntervals::getInterval(), llvm::LiveRangeEdit::getParent(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer(), llvm::LiveRangeEdit::getReg(), llvm::SlotIndex::getRegSlot(), llvm::LiveIntervals::getSlotIndexes(), llvm::LiveIntervals::getVNInfoAllocator(), llvm::LiveRange::getVNInfoAt(), I, llvm::VNInfo::id, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::insert(), llvm::SlotIndexes::insertMachineInstrInMaps(), llvm::SlotIndex::isValid(), llvm::LiveInterval::reg, llvm::LiveRangeEdit::rematerializeAt(), llvm::NVPTX::PTXCvtMode::RM, and llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::setInt().
Referenced by enterIntvAtEnd(), leaveIntvAtTop(), overlapIntv(), and useIntv().
SlotIndex SplitEditor::enterIntvAfter (SlotIndex Idx)
enterIntvAfter - Enter the open interval after the instruction at Idx. Return the beginning of the new live range.
Definition at line 498 of file SplitKit.cpp.
References llvm::dbgs(), DEBUG, llvm::VNInfo::def, llvm::SlotIndex::getBoundaryIndex(), llvm::LiveIntervals::getInstructionFromIndex(), llvm::MachineInstr::getParent(), llvm::LiveRangeEdit::getParent(), llvm::LiveRange::getVNInfoAt(), llvm::VNInfo::id, llvm::A64CC::MI, and llvm::next().
Referenced by splitLiveThroughBlock(), and splitRegOutBlock().
SlotIndex SplitEditor::enterIntvAtEnd (MachineBasicBlock & MBB)
enterIntvAtEnd - Enter the open interval at the end of MBB. Use the open interval from he inserted copy to the MBB end. Return the beginning of the new live range.
Definition at line 516 of file SplitKit.cpp.
References llvm::dbgs(), DEBUG, llvm::VNInfo::def, dump(), llvm::SplitAnalysis::getLastSplitPointIter(), llvm::LiveIntervals::getMBBEndIdx(), llvm::MachineBasicBlock::getNumber(), llvm::LiveRangeEdit::getParent(), llvm::SlotIndex::getPrevSlot(), llvm::LiveRange::getVNInfoAt(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::insert().
Referenced by splitLiveThroughBlock().
SlotIndex SplitEditor::enterIntvBefore (SlotIndex Idx)
enterIntvBefore - Enter the open interval before the instruction at Idx. If the parent interval is not live before Idx, a COPY is not inserted. Return the beginning of the new live range.
Definition at line 481 of file SplitKit.cpp.
References llvm::dbgs(), DEBUG, llvm::VNInfo::def, llvm::SlotIndex::getBaseIndex(), llvm::LiveIntervals::getInstructionFromIndex(), llvm::MachineInstr::getParent(), llvm::LiveRangeEdit::getParent(), llvm::LiveRange::getVNInfoAt(), llvm::VNInfo::id, and llvm::A64CC::MI.
Referenced by llvm::createGreedyRegisterAllocator(), splitLiveThroughBlock(), splitRegInBlock(), splitRegOutBlock(), and splitSingleBlock().
void SplitEditor::finish (SmallVectorImpl< unsigned > * LRMap = 0)
finish - after all the new live ranges have been created, compute the remaining live range, and rewrite instructions to use the new registers.
Parameters
LRMap When not null, this vector will map each live range in Edit back to the indices returned by openIntv. There may be extra indices created by dead code elimination.
Definition at line 1046 of file SplitKit.cpp.
References llvm::LiveRangeEdit::begin(), llvm::LiveRangeEdit::calculateRegClassAndHint(), llvm::ConnectedVNInfoEqClasses::Classify(), llvm::SmallVectorImpl< T >::clear(), llvm::LiveRangeEdit::createEmptyInterval(), llvm::dbgs(), DEBUG, llvm::VNInfo::def, llvm::LiveRangeEdit::didRematerialize(), llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::LiveRangeEdit::end(), llvm::LiveRangeEdit::get(), llvm::LiveIntervals::getInterval(), llvm::VirtRegMap::getMachineFunction(), llvm::LiveRangeEdit::getParent(), i, I, llvm::VNInfo::isUnused(), j(), llvm_unreachable, llvm::IntervalMap< KeyT, ValT, N, Traits >::lookup(), llvm::SplitAnalysis::Loops, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::LiveRange::RenumberValues(), llvm::SmallVectorImpl< T >::resize(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::LiveRangeEdit::size(), SM_Partition, SM_Size, SM_Speed, llvm::LiveRange::vni_begin(), and llvm::LiveRange::vni_end().
Referenced by llvm::createGreedyRegisterAllocator().
SlotIndex SplitEditor::leaveIntvAfter (SlotIndex Idx)
leaveIntvAfter - Leave the open interval after the instruction at Idx. Return the end of the live range.
Definition at line 546 of file SplitKit.cpp.
References llvm::dbgs(), DEBUG, llvm::VNInfo::def, llvm::SlotIndex::getBoundaryIndex(), llvm::LiveIntervals::getInstructionFromIndex(), llvm::SlotIndex::getNextSlot(), llvm::MachineInstr::getParent(), llvm::LiveRangeEdit::getParent(), llvm::LiveRangeEdit::getReg(), llvm::LiveRange::getVNInfoAt(), llvm::VNInfo::id, llvm::SlotIndex::isSameInstr(), llvm::A64CC::MI, llvm::next(), and llvm::MachineInstr::readsVirtualRegister().
Referenced by llvm::createGreedyRegisterAllocator(), splitRegInBlock(), and splitSingleBlock().
SlotIndex SplitEditor::leaveIntvAtTop (MachineBasicBlock & MBB)
leaveIntvAtTop - Leave the interval at the top of MBB. Add liveness from the MBB top to the copy. Return the end of the live range.
Definition at line 596 of file SplitKit.cpp.
References llvm::MachineBasicBlock::begin(), llvm::dbgs(), DEBUG, llvm::VNInfo::def, dump(), llvm::LiveIntervals::getMBBStartIdx(), llvm::MachineBasicBlock::getNumber(), llvm::LiveRangeEdit::getParent(), llvm::LiveRange::getVNInfoAt(), llvm::IntervalMap< KeyT, ValT, N, Traits >::insert(), and llvm::MachineBasicBlock::SkipPHIsAndLabels().
Referenced by splitLiveThroughBlock().
SlotIndex SplitEditor::leaveIntvBefore (SlotIndex Idx)
leaveIntvBefore - Leave the open interval before the instruction at Idx. Return the end of the live range.
Definition at line 577 of file SplitKit.cpp.
References llvm::dbgs(), DEBUG, llvm::VNInfo::def, llvm::SlotIndex::getBaseIndex(), llvm::LiveIntervals::getInstructionFromIndex(), llvm::SlotIndex::getNextSlot(), llvm::MachineInstr::getParent(), llvm::LiveRangeEdit::getParent(), llvm::LiveRange::getVNInfoAt(), llvm::VNInfo::id, and llvm::A64CC::MI.
Referenced by splitLiveThroughBlock(), splitRegInBlock(), and splitSingleBlock().
unsigned SplitEditor::openIntv ()
Create a new virtual register and live interval.
Create a new virtual register and live interval. Return the interval index, starting from 1. Interval index 0 is the implicit complement interval.
Definition at line 463 of file SplitKit.cpp.
References llvm::LiveRangeEdit::createEmptyInterval(), llvm::LiveRangeEdit::empty(), and llvm::LiveRangeEdit::size().
Referenced by llvm::createGreedyRegisterAllocator(), splitRegInBlock(), splitRegOutBlock(), and splitSingleBlock().
void SplitEditor::overlapIntv (SlotIndex Start, SlotIndex End)
overlapIntv - Indicate that all instructions in range should use the open interval, but also let the complement interval be live.
This doubles the register pressure, but is sometimes required to deal with register uses after the last valid split point.
The Start index should be a return value from a leaveIntv* call, and End should be in the same basic block. The parent interval must have the same value across the range.
Definition at line 614 of file SplitKit.cpp.
References llvm::LiveRangeCalc::addLiveInBlock(), llvm::MachineInstr::addRegisterDead(), llvm::LiveRange::addSegment(), llvm::MachineInstr::allDefsAreDead(), llvm::LiveRangeEdit::begin(), llvm::LiveRange::begin(), llvm::MachineBasicBlock::begin(), llvm::IntervalMap< KeyT, ValT, N, Traits >::begin(), llvm::LiveRangeCalc::calculateValues(), llvm::IntervalMap< SlotIndex, unsigned >::const_iterator, llvm::dbgs(), llvm::RegState::Dead, DEBUG, llvm::tgtok::Def, llvm::VNInfo::def, llvm::LiveRangeEdit::didRematerialize(), llvm::MachineDominatorTree::dominates(), dump(), llvm::LiveRangeEdit::eliminateDeadDefs(), llvm::SmallVectorBase::empty(), llvm::LiveRangeEdit::end(), llvm::LiveRange::end(), llvm::MachineInstr::eraseFromParent(), llvm::LiveRangeCalc::extend(), llvm::LiveRange::extendInBlock(), llvm::MachineDominatorTree::findNearestCommonDominator(), llvm::LiveRangeEdit::get(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LiveIntervals::getInstructionFromIndex(), llvm::LiveIntervals::getInstructionIndex(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getInt(), llvm::LiveIntervals::getInterval(), llvm::SplitAnalysis::getLastSplitPointIter(), llvm::LoopBase< BlockT, LoopT >::getLoopDepth(), llvm::LiveIntervals::getMBBEndIdx(), llvm::LiveIntervals::getMBBFromIndex(), llvm::SlotIndexes::getMBBRange(), llvm::SlotIndex::getNextSlot(), llvm::MachineBasicBlock::getNumber(), llvm::LiveRange::getNumValNums(), llvm::MachineInstr::getParent(), llvm::LiveRangeEdit::getParent(), llvm::MachineOperand::getParent(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer(), llvm::SlotIndex::getPrevSlot(), llvm::LiveRangeEdit::getReg(), llvm::SlotIndex::getRegSlot(), llvm::LiveIntervals::getSlotIndexes(), llvm::MachineOperand::getSubReg(), llvm::LiveRange::getValNumInfo(), llvm::LiveRange::getVNInfoAt(), llvm::LiveRange::getVNInfoBefore(), i, I, llvm::VNInfo::id, llvm::IntervalMap< KeyT, ValT, N, Traits >::insert(), llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isEarlyClobber(), llvm::VNInfo::isPHIDef(), llvm::MachineOperand::isUndef(), llvm::VNInfo::isUnused(), llvm::IntervalMap< SlotIndex, unsigned >::iterator, llvm::RegState::Kill, llvm::LiveRange::liveAt(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::lookup(), llvm::IntervalMap< KeyT, ValT, N, Traits >::lookup(), llvm::SplitAnalysis::Loops, Loops, llvm::A64CC::MI, llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_end(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::LiveInterval::reg, llvm::MachineRegisterInfo::reg_begin(), llvm::MachineRegisterInfo::reg_end(), llvm::LiveIntervals::RemoveMachineInstrFromMaps(), llvm::LiveRange::removeValNo(), llvm::LiveRangeCalc::setLiveOutValue(), llvm::MachineOperand::setReg(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::tie(), llvm::LiveRange::vni_begin(), and llvm::LiveRange::vni_end().
Referenced by splitRegInBlock(), and splitSingleBlock().
void SplitEditor::reset (LiveRangeEdit & LRE, ComplementSpillMode SM = SM_Partition)
reset - Prepare for a new split.
Definition at line 342 of file SplitKit.cpp.
References llvm::LiveRangeEdit::anyRematerializable(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::clear(), llvm::IntervalMap< KeyT, ValT, N, Traits >::clear(), llvm::VirtRegMap::getMachineFunction(), llvm::LiveIntervals::getSlotIndexes(), llvm::LiveIntervals::getVNInfoAllocator(), and llvm::LiveRangeCalc::reset().
Referenced by llvm::createGreedyRegisterAllocator().
void SplitEditor::selectIntv (unsigned Idx)
selectIntv - Select a previously opened interval index.
Definition at line 474 of file SplitKit.cpp.
References llvm::dbgs(), DEBUG, and size.
Referenced by splitLiveThroughBlock(), splitRegInBlock(), and splitRegOutBlock().
void SplitEditor::splitLiveThroughBlock (unsigned MBBNum, unsigned IntvIn, SlotIndex LeaveBefore, unsigned IntvOut, SlotIndex EnterAfter)
splitLiveThroughBlock - Split CurLI in the given block such that it enters the block in IntvIn and leaves it in IntvOut. There may be uses in the block, but they will be ignored when placing split points.
Parameters
MBBNum Block number.
IntvIn Interval index entering the block.
LeaveBefore When set, leave IntvIn before this point.
IntvOut Interval index leaving the block.
EnterAfter When set, enter IntvOut after this point.
Definition at line 1182 of file SplitKit.cpp.
References llvm::dbgs(), DEBUG, enterIntvAfter(), enterIntvAtEnd(), enterIntvBefore(), llvm::SlotIndex::getBaseIndex(), llvm::MachineFunction::getBlockNumbered(), llvm::SlotIndex::getBoundaryIndex(), llvm::SplitAnalysis::getLastSplitPoint(), llvm::VirtRegMap::getMachineFunction(), llvm::SlotIndexes::getMBBRange(), llvm::LiveIntervals::getSlotIndexes(), leaveIntvAtTop(), leaveIntvBefore(), selectIntv(), llvm::tie(), and useIntv().
Referenced by llvm::createGreedyRegisterAllocator().
void SplitEditor::splitRegInBlock (const SplitAnalysis::BlockInfo & BI, unsigned IntvIn, SlotIndex LeaveBefore)
splitRegInBlock - Split CurLI in the given block such that it enters the block in IntvIn and leaves it on the stack (or not at all). Split points are placed in a way that avoids putting uses in the stack interval. This may require creating a local interval when there is interference.
Parameters
BI Block descriptor.
IntvIn Interval index entering the block. Not 0.
LeaveBefore When set, leave IntvIn before this point.
Definition at line 1286 of file SplitKit.cpp.
References llvm::dbgs(), DEBUG, enterIntvBefore(), llvm::SplitAnalysis::BlockInfo::FirstInstr, llvm::SlotIndex::getBoundaryIndex(), llvm::SplitAnalysis::getLastSplitPoint(), llvm::SlotIndexes::getMBBRange(), llvm::MachineBasicBlock::getNumber(), llvm::LiveIntervals::getSlotIndexes(), llvm::SplitAnalysis::BlockInfo::LastInstr, leaveIntvAfter(), leaveIntvBefore(), llvm::SplitAnalysis::BlockInfo::LiveIn, llvm::SplitAnalysis::BlockInfo::LiveOut, llvm::SplitAnalysis::BlockInfo::MBB, openIntv(), overlapIntv(), selectIntv(), llvm::tie(), and useIntv().
Referenced by llvm::createGreedyRegisterAllocator().
void SplitEditor::splitRegOutBlock (const SplitAnalysis::BlockInfo & BI, unsigned IntvOut, SlotIndex EnterAfter)
splitRegOutBlock - Split CurLI in the given block such that it enters the block on the stack (or isn't live-in at all) and leaves it in IntvOut. Split points are placed to avoid interference and such that the uses are not in the stack interval. This may require creating a local interval when there is interference.
Parameters
BI Block descriptor.
IntvOut Interval index leaving the block.
EnterAfter When set, enter IntvOut after this point.
Definition at line 1378 of file SplitKit.cpp.
References llvm::dbgs(), DEBUG, enterIntvAfter(), enterIntvBefore(), llvm::SplitAnalysis::BlockInfo::FirstInstr, llvm::SlotIndex::getBaseIndex(), llvm::SplitAnalysis::getLastSplitPoint(), llvm::SlotIndexes::getMBBRange(), llvm::MachineBasicBlock::getNumber(), llvm::LiveIntervals::getSlotIndexes(), llvm::SplitAnalysis::BlockInfo::LastInstr, llvm::SplitAnalysis::BlockInfo::LiveIn, llvm::SplitAnalysis::BlockInfo::LiveOut, llvm::SplitAnalysis::BlockInfo::MBB, openIntv(), selectIntv(), llvm::tie(), and useIntv().
Referenced by llvm::createGreedyRegisterAllocator().
void SplitEditor::splitSingleBlock (const SplitAnalysis::BlockInfo & BI)
splitSingleBlock - Split CurLI into a separate live interval around the uses in a single block. This is intended to be used as part of a larger split, and doesn't call finish().
Definition at line 1155 of file SplitKit.cpp.
References enterIntvBefore(), llvm::SplitAnalysis::BlockInfo::FirstInstr, llvm::SplitAnalysis::getLastSplitPoint(), llvm::MachineBasicBlock::getNumber(), llvm::SplitAnalysis::BlockInfo::LastInstr, leaveIntvAfter(), leaveIntvBefore(), llvm::SplitAnalysis::BlockInfo::LiveOut, llvm::SplitAnalysis::BlockInfo::MBB, openIntv(), overlapIntv(), and useIntv().
Referenced by llvm::createGreedyRegisterAllocator().
void SplitEditor::useIntv (const MachineBasicBlock & MBB)
useIntv - indicate that all instructions in MBB should use OpenLI.
Definition at line 535 of file SplitKit.cpp.
References llvm::LiveIntervals::getMBBEndIdx(), and llvm::LiveIntervals::getMBBStartIdx().
Referenced by llvm::createGreedyRegisterAllocator(), splitLiveThroughBlock(), splitRegInBlock(), splitRegOutBlock(), and splitSingleBlock().
void SplitEditor::useIntv (SlotIndex Start, SlotIndex End)
useIntv - indicate that all instructions in range should use OpenLI.
Definition at line 539 of file SplitKit.cpp.
References llvm::dbgs(), DEBUG, dump(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::insert().
The documentation for this class was generated from the following files:
SplitKit.h
SplitKit.cpp