LLVM: llvm::ConstantAggrUniqueMap< TypeClass, ConstantClass > Class Template Reference
LLVM API Documentation
llvm::ConstantAggrUniqueMap< TypeClass, ConstantClass > Class Template Reference
#include <ConstantsContext.h>
Public Types
typedef ArrayRef< Constant * > Operands
typedef std::pair< TypeClass *, Operands > LookupKey
typedef DenseMap< ConstantClass *, char, MapInfo > MapTy
Public Member Functions
MapTy::iterator map_begin ()
MapTy::iterator map_end ()
void freeConstants ()
ConstantClass * getOrCreate (TypeClass *Ty, Operands V)
MapTy::iterator find (LookupKey Lookup)
Find the constant by lookup key.
void insert (ConstantClass *CP)
Insert the constant into its proper slot.
void remove (ConstantClass *CP)
Remove this constant from the map.
void dump () const
Detailed Description
template<class TypeClass, class ConstantClass>
class llvm::ConstantAggrUniqueMap< TypeClass, ConstantClass >
Definition at line 651 of file ConstantsContext.h.
Member Typedef Documentation
template<class TypeClass, class ConstantClass> typedef std::pair<TypeClass*, Operands> llvm::ConstantAggrUniqueMap< TypeClass, ConstantClass >::LookupKey
Definition at line 654 of file ConstantsContext.h.
template<class TypeClass, class ConstantClass> typedef DenseMap<ConstantClass *, char, MapInfo> llvm::ConstantAggrUniqueMap< TypeClass, ConstantClass >::MapTy
Definition at line 694 of file ConstantsContext.h.
template<class TypeClass, class ConstantClass> typedef ArrayRef<Constant*> llvm::ConstantAggrUniqueMap< TypeClass, ConstantClass >::Operands
Definition at line 653 of file ConstantsContext.h.
Member Function Documentation
template<class TypeClass, class ConstantClass> void llvm::ConstantAggrUniqueMap< TypeClass, ConstantClass >::dump () const inline
Definition at line 767 of file ConstantsContext.h.
template<class TypeClass, class ConstantClass> MapTy::iterator llvm::ConstantAggrUniqueMap< TypeClass, ConstantClass >::find (LookupKey Lookup) inline
Find the constant by lookup key.
Definition at line 750 of file ConstantsContext.h.
Referenced by llvm::ConstantStruct::replaceUsesOfWithOnConstant().
template<class TypeClass, class ConstantClass> void llvm::ConstantAggrUniqueMap< TypeClass, ConstantClass >::freeConstants () inline
Definition at line 706 of file ConstantsContext.h.
Referenced by llvm::LLVMContextImpl::~LLVMContextImpl().
template<class TypeClass, class ConstantClass> ConstantClass* llvm::ConstantAggrUniqueMap< TypeClass, ConstantClass >::getOrCreate (TypeClass * Ty, Operands V) inline
getOrCreate - Return the specified constant from the map, creating it if necessary.
Definition at line 732 of file ConstantsContext.h.
Referenced by llvm::ConstantStruct::get().
template<class TypeClass, class ConstantClass> void llvm::ConstantAggrUniqueMap< TypeClass, ConstantClass >::insert (ConstantClass * CP) inline
Insert the constant into its proper slot.
Definition at line 755 of file ConstantsContext.h.
Referenced by llvm::ConstantStruct::replaceUsesOfWithOnConstant().
template<class TypeClass, class ConstantClass> MapTy::iterator llvm::ConstantAggrUniqueMap< TypeClass, ConstantClass >::map_begin () inline
Definition at line 703 of file ConstantsContext.h.
Referenced by llvm::LLVMContextImpl::~LLVMContextImpl().
template<class TypeClass, class ConstantClass> MapTy::iterator llvm::ConstantAggrUniqueMap< TypeClass, ConstantClass >::map_end () inline
Definition at line 704 of file ConstantsContext.h.
Referenced by llvm::ConstantStruct::replaceUsesOfWithOnConstant(), and llvm::LLVMContextImpl::~LLVMContextImpl().
template<class TypeClass, class ConstantClass> void llvm::ConstantAggrUniqueMap< TypeClass, ConstantClass >::remove (ConstantClass * CP) inline
Remove this constant from the map.
Definition at line 760 of file ConstantsContext.h.
Referenced by llvm::ConstantArray::destroyConstant(), llvm::ConstantStruct::destroyConstant(), llvm::ConstantVector::destroyConstant(), and llvm::ConstantStruct::replaceUsesOfWithOnConstant().
The documentation for this class was generated from the following file:
ConstantsContext.h