LLVM: llvm::MipsMCInstLower Class Reference
LLVM API Documentation
llvm::MipsMCInstLower Class Reference
MipsMCInstLower - This class is used to lower an MachineInstr into an.
#include <MipsMCInstLower.h>
Public Member Functions
MipsMCInstLower (MipsAsmPrinter &asmprinter)
void Initialize (MCContext *C)
void Lower (const MachineInstr *MI, MCInst &OutMI) const
MCOperand LowerOperand (const MachineOperand &MO, unsigned offset=0) const
Detailed Description
MipsMCInstLower - This class is used to lower an MachineInstr into an.
Definition at line 26 of file MipsMCInstLower.h.
Constructor & Destructor Documentation
MipsMCInstLower::MipsMCInstLower (MipsAsmPrinter & asmprinter)
Definition at line 28 of file MipsMCInstLower.cpp.
Member Function Documentation
void MipsMCInstLower::Initialize (MCContext * C)
Definition at line 31 of file MipsMCInstLower.cpp.
References llvm::MCConstantExpr::Create(), llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateAdd(), llvm::MCOperand::CreateExpr(), llvm::MachineOperand::getBlockAddress(), llvm::AsmPrinter::GetBlockAddressSymbol(), llvm::AsmPrinter::GetCPISymbol(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getIndex(), llvm::AsmPrinter::GetJTISymbol(), llvm::MachineOperand::getMBB(), llvm::MachineOperand::getOffset(), llvm::AsmPrinter::getSymbol(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getSymbolName(), llvm::MachineOperand::getTargetFlags(), llvm_unreachable, llvm::MipsII::MO_ABS_HI, llvm::MipsII::MO_ABS_LO, llvm::MachineOperand::MO_BlockAddress, llvm::MipsII::MO_CALL_HI16, llvm::MipsII::MO_CALL_LO16, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MipsII::MO_DTPREL_HI, llvm::MipsII::MO_DTPREL_LO, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::MipsII::MO_GOT, llvm::MipsII::MO_GOT16, llvm::MipsII::MO_GOT_CALL, llvm::MipsII::MO_GOT_DISP, llvm::MipsII::MO_GOT_HI16, llvm::MipsII::MO_GOT_LO16, llvm::MipsII::MO_GOT_OFST, llvm::MipsII::MO_GOT_PAGE, llvm::MipsII::MO_GOTTPREL, llvm::MipsII::MO_GPOFF_HI, llvm::MipsII::MO_GPOFF_LO, llvm::MipsII::MO_GPREL, llvm::MipsII::MO_HIGHER, llvm::MipsII::MO_HIGHEST, llvm::MachineOperand::MO_JumpTableIndex, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MipsII::MO_NO_FLAG, llvm::MipsII::MO_TLSGD, llvm::MipsII::MO_TLSLDM, llvm::MipsII::MO_TPREL_HI, llvm::MipsII::MO_TPREL_LO, llvm::ARMBuildAttrs::Symbol, llvm::MCSymbolRefExpr::VK_Mips_ABS_HI, llvm::MCSymbolRefExpr::VK_Mips_ABS_LO, llvm::MCSymbolRefExpr::VK_Mips_CALL_HI16, llvm::MCSymbolRefExpr::VK_Mips_CALL_LO16, llvm::MCSymbolRefExpr::VK_Mips_DTPREL_HI, llvm::MCSymbolRefExpr::VK_Mips_DTPREL_LO, llvm::MCSymbolRefExpr::VK_Mips_GOT, llvm::MCSymbolRefExpr::VK_Mips_GOT16, llvm::MCSymbolRefExpr::VK_Mips_GOT_CALL, llvm::MCSymbolRefExpr::VK_Mips_GOT_DISP, llvm::MCSymbolRefExpr::VK_Mips_GOT_HI16, llvm::MCSymbolRefExpr::VK_Mips_GOT_LO16, llvm::MCSymbolRefExpr::VK_Mips_GOT_OFST, llvm::MCSymbolRefExpr::VK_Mips_GOT_PAGE, llvm::MCSymbolRefExpr::VK_Mips_GOTTPREL, llvm::MCSymbolRefExpr::VK_Mips_GPOFF_HI, llvm::MCSymbolRefExpr::VK_Mips_GPOFF_LO, llvm::MCSymbolRefExpr::VK_Mips_GPREL, llvm::MCSymbolRefExpr::VK_Mips_HIGHER, llvm::MCSymbolRefExpr::VK_Mips_HIGHEST, llvm::MCSymbolRefExpr::VK_Mips_TLSGD, llvm::MCSymbolRefExpr::VK_Mips_TLSLDM, llvm::MCSymbolRefExpr::VK_Mips_TPREL_HI, llvm::MCSymbolRefExpr::VK_Mips_TPREL_LO, and llvm::MCSymbolRefExpr::VK_None.
Referenced by llvm::MipsAsmPrinter::EmitFunctionBodyStart().
void MipsMCInstLower::Lower (const MachineInstr * MI, MCInst & OutMI) const
Definition at line 154 of file MipsMCInstLower.cpp.
References llvm::MCInst::addOperand(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), i, llvm::MCOperand::isValid(), LowerOperand(), and llvm::MCInst::setOpcode().
Referenced by llvm::MipsAsmPrinter::EmitInstruction().
MCOperand MipsMCInstLower::LowerOperand (const MachineOperand & MO, unsigned offset = 0) const
Definition at line 128 of file MipsMCInstLower.cpp.
References llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getType(), llvm::MachineOperand::isImplicit(), llvm_unreachable, llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_JumpTableIndex, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_Register, and llvm::MachineOperand::MO_RegisterMask.
Referenced by Lower(), and llvm::MipsAsmPrinter::runOnMachineFunction().
The documentation for this class was generated from the following files:
MipsMCInstLower.h
MipsMCInstLower.cpp