LLVM: llvm::TargetLoweringObjectFile Class Reference
LLVM API Documentation
llvm::TargetLoweringObjectFile Class Reference abstract
#include <TargetLoweringObjectFile.h>
Public Member Functions
MCContext & getContext () const
TargetLoweringObjectFile ()
virtual ~TargetLoweringObjectFile ()
virtual void Initialize (MCContext &ctx, const TargetMachine &TM)
virtual void emitPersonalityValue (MCStreamer &Streamer, const TargetMachine &TM, const MCSymbol *Sym) const
virtual void emitModuleFlags (MCStreamer &, ArrayRef< Module::ModuleFlagEntry >, Mangler *, const TargetMachine &) const
emitModuleFlags - Emit the module flags that the platform cares about.
virtual bool shouldEmitUsedDirectiveFor (const GlobalValue *GV, Mangler *) const
virtual const MCSection * getSectionForConstant (SectionKind Kind) const
const MCSection * SectionForGlobal (const GlobalValue *GV, SectionKind Kind, Mangler *Mang, const TargetMachine &TM) const
const MCSection * SectionForGlobal (const GlobalValue *GV, Mangler *Mang, const TargetMachine &TM) const
virtual const MCSection * getExplicitSectionGlobal (const GlobalValue *GV, SectionKind Kind, Mangler *Mang, const TargetMachine &TM) const =0
virtual const MCSection * getSpecialCasedSectionGlobals (const GlobalValue *GV, Mangler *Mang, SectionKind Kind) const
virtual const MCExpr * getTTypeGlobalReference (const GlobalValue *GV, Mangler *Mang, MachineModuleInfo *MMI, unsigned Encoding, MCStreamer &Streamer) const
MCSymbol * getSymbol (Mangler &M, const GlobalValue *GV) const
virtual MCSymbol * getCFIPersonalitySymbol (const GlobalValue *GV, Mangler *Mang, MachineModuleInfo *MMI) const
const MCExpr * getTTypeReference (const MCSymbolRefExpr *Sym, unsigned Encoding, MCStreamer &Streamer) const
virtual const MCSection * getStaticCtorSection (unsigned Priority=65535) const
virtual const MCSection * getStaticDtorSection (unsigned Priority=65535) const
virtual const MCExpr * getDebugThreadLocalSymbol (const MCSymbol *Sym) const
Create a symbol reference to describe the given TLS variable when emitting the address in debug info.
Public Member Functions inherited from llvm::MCObjectFileInfo
void InitMCObjectFileInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, MCContext &ctx)
bool isFunctionEHFrameSymbolPrivate () const
bool getSupportsWeakOmittedEHFrame () const
bool getCommDirectiveSupportsAlignment () const
unsigned getPersonalityEncoding () const
unsigned getLSDAEncoding () const
unsigned getFDEEncoding (bool CFI) const
unsigned getTTypeEncoding () const
unsigned getCompactUnwindDwarfEHFrameOnly () const
const MCSection * getTextSection () const
const MCSection * getDataSection () const
const MCSection * getBSSSection () const
const MCSection * getLSDASection () const
const MCSection * getCompactUnwindSection () const
const MCSection * getDwarfAbbrevSection () const
const MCSection * getDwarfInfoSection () const
const MCSection * getDwarfLineSection () const
const MCSection * getDwarfFrameSection () const
const MCSection * getDwarfPubNamesSection () const
const MCSection * getDwarfPubTypesSection () const
const MCSection * getDwarfGnuPubNamesSection () const
const MCSection * getDwarfGnuPubTypesSection () const
const MCSection * getDwarfDebugInlineSection () const
const MCSection * getDwarfStrSection () const
const MCSection * getDwarfLocSection () const
const MCSection * getDwarfARangesSection () const
const MCSection * getDwarfRangesSection () const
const MCSection * getDwarfMacroInfoSection () const
const MCSection * getDwarfAccelNamesSection () const
const MCSection * getDwarfAccelObjCSection () const
const MCSection * getDwarfAccelNamespaceSection () const
const MCSection * getDwarfAccelTypesSection () const
const MCSection * getDwarfInfoDWOSection () const
const MCSection * getDwarfAbbrevDWOSection () const
const MCSection * getDwarfStrDWOSection () const
const MCSection * getDwarfLineDWOSection () const
const MCSection * getDwarfLocDWOSection () const
const MCSection * getDwarfStrOffDWOSection () const
const MCSection * getDwarfAddrSection () const
const MCSection * getTLSExtraDataSection () const
const MCSection * getTLSDataSection () const
const MCSection * getTLSBSSSection () const
const MCSection * getStackMapSection () const
const MCSection * getDataRelSection () const
const MCSection * getDataRelLocalSection () const
const MCSection * getDataRelROSection () const
const MCSection * getDataRelROLocalSection () const
const MCSection * getMergeableConst4Section () const
const MCSection * getMergeableConst8Section () const
const MCSection * getMergeableConst16Section () const
const MCSection * getTLSTLVSection () const
const MCSection * getTLSThreadInitSection () const
const MCSection * getCStringSection () const
const MCSection * getUStringSection () const
const MCSection * getTextCoalSection () const
const MCSection * getConstTextCoalSection () const
const MCSection * getConstDataSection () const
const MCSection * getDataCoalSection () const
const MCSection * getDataCommonSection () const
const MCSection * getDataBSSSection () const
const MCSection * getFourByteConstantSection () const
const MCSection * getEightByteConstantSection () const
const MCSection * getSixteenByteConstantSection () const
const MCSection * getLazySymbolPointerSection () const
const MCSection * getNonLazySymbolPointerSection () const
const MCSection * getDrectveSection () const
const MCSection * getPDataSection () const
const MCSection * getXDataSection () const
const MCSection * getEHFrameSection ()
Static Public Member Functions
static SectionKind getKindForGlobal (const GlobalValue *GV, const TargetMachine &TM)
Protected Member Functions
virtual const MCSection * SelectSectionForGlobal (const GlobalValue *GV, SectionKind Kind, Mangler *Mang, const TargetMachine &TM) const
Additional Inherited Members
Protected Attributes inherited from llvm::MCObjectFileInfo
bool CommDirectiveSupportsAlignment
bool SupportsWeakOmittedEHFrame
bool IsFunctionEHFrameSymbolPrivate
unsigned PersonalityEncoding
unsigned LSDAEncoding
unsigned FDEEncoding
unsigned FDECFIEncoding
unsigned TTypeEncoding
unsigned EHSectionType
Section flags for eh_frame.
unsigned EHSectionFlags
unsigned CompactUnwindDwarfEHFrameOnly
const MCSection * TextSection
const MCSection * DataSection
const MCSection * BSSSection
BSSSection - Section that is default initialized to zero.
const MCSection * ReadOnlySection
const MCSection * StaticCtorSection
const MCSection * StaticDtorSection
const MCSection * LSDASection
const MCSection * CompactUnwindSection
const MCSection * DwarfAbbrevSection
const MCSection * DwarfInfoSection
const MCSection * DwarfLineSection
const MCSection * DwarfFrameSection
const MCSection * DwarfPubTypesSection
const MCSection * DwarfDebugInlineSection
const MCSection * DwarfStrSection
const MCSection * DwarfLocSection
const MCSection * DwarfARangesSection
const MCSection * DwarfRangesSection
const MCSection * DwarfMacroInfoSection
const MCSection * DwarfPubNamesSection
const MCSection * DwarfAccelNamesSection
const MCSection * DwarfAccelObjCSection
const MCSection * DwarfAccelNamespaceSection
const MCSection * DwarfAccelTypesSection
const MCSection * DwarfInfoDWOSection
These are used for the Fission separate debug information files.
const MCSection * DwarfAbbrevDWOSection
const MCSection * DwarfStrDWOSection
const MCSection * DwarfLineDWOSection
const MCSection * DwarfLocDWOSection
const MCSection * DwarfStrOffDWOSection
const MCSection * DwarfAddrSection
const MCSection * DwarfGnuPubNamesSection
Sections for newer gnu pubnames and pubtypes.
const MCSection * DwarfGnuPubTypesSection
const MCSection * TLSExtraDataSection
const MCSection * TLSDataSection
const MCSection * TLSBSSSection
const MCSection * StackMapSection
StackMap section.
const MCSection * EHFrameSection
const MCSection * DataRelSection
const MCSection * DataRelLocalSection
const MCSection * DataRelROSection
const MCSection * DataRelROLocalSection
const MCSection * MergeableConst4Section
const MCSection * MergeableConst8Section
const MCSection * MergeableConst16Section
const MCSection * TLSTLVSection
const MCSection * TLSThreadInitSection
const MCSection * CStringSection
const MCSection * UStringSection
const MCSection * TextCoalSection
const MCSection * ConstTextCoalSection
const MCSection * ConstDataSection
const MCSection * DataCoalSection
const MCSection * DataCommonSection
const MCSection * DataBSSSection
const MCSection * FourByteConstantSection
const MCSection * EightByteConstantSection
const MCSection * SixteenByteConstantSection
const MCSection * LazySymbolPointerSection
const MCSection * NonLazySymbolPointerSection
const MCSection * DrectveSection
const MCSection * PDataSection
const MCSection * XDataSection
Detailed Description
Definition at line 35 of file TargetLoweringObjectFile.h.
Constructor & Destructor Documentation
llvm::TargetLoweringObjectFile::TargetLoweringObjectFile () inline
Definition at line 45 of file TargetLoweringObjectFile.h.
References emitPersonalityValue(), Initialize(), llvm::SystemZISD::TM, and ~TargetLoweringObjectFile().
TargetLoweringObjectFile::~TargetLoweringObjectFile () virtual
Definition at line 47 of file TargetLoweringObjectFile.cpp.
Referenced by TargetLoweringObjectFile().
Member Function Documentation
virtual void llvm::TargetLoweringObjectFile::emitModuleFlags (MCStreamer & , ArrayRef< Module::ModuleFlagEntry > , Mangler * , const TargetMachine &) const inline virtual
emitModuleFlags - Emit the module flags that the platform cares about.
Reimplemented in llvm::TargetLoweringObjectFileCOFF, and llvm::TargetLoweringObjectFileMachO.
Definition at line 59 of file TargetLoweringObjectFile.h.
Referenced by llvm::AsmPrinter::doFinalization(), llvm::TargetLoweringObjectFileCOFF::~TargetLoweringObjectFileCOFF(), and llvm::TargetLoweringObjectFileMachO::~TargetLoweringObjectFileMachO().
void TargetLoweringObjectFile::emitPersonalityValue (MCStreamer & Streamer, const TargetMachine & TM, const MCSymbol * Sym) const virtual
Reimplemented in llvm::TargetLoweringObjectFileELF.
Definition at line 116 of file TargetLoweringObjectFile.cpp.
Referenced by llvm::DwarfCFIException::EndModule(), and TargetLoweringObjectFile().
MCSymbol * TargetLoweringObjectFile::getCFIPersonalitySymbol (const GlobalValue * GV, Mangler * Mang, MachineModuleInfo * MMI) const virtual
Reimplemented in llvm::TargetLoweringObjectFileMachO, llvm::TargetLoweringObjectFileELF, and llvm::X86_64MachoTargetObjectFile.
Definition at line 111 of file TargetLoweringObjectFile.cpp.
References getSymbol().
Referenced by llvm::DwarfCFIException::BeginFunction(), llvm::Win64Exception::EndFunction(), getSpecialCasedSectionGlobals(), and getSymbol().
MCContext& llvm::TargetLoweringObjectFile::getContext () const inline
Definition at line 43 of file TargetLoweringObjectFile.h.
Referenced by getTTypeGlobalReference(), getTTypeReference(), llvm::HexagonTargetObjectFile::Initialize(), llvm::MipsTargetObjectFile::Initialize(), llvm::linkErlangGCPrinter(), and llvm::AMDGPUAsmPrinter::runOnMachineFunction().
const MCExpr * TargetLoweringObjectFile::getDebugThreadLocalSymbol (const MCSymbol * Sym) const virtual
Create a symbol reference to describe the given TLS variable when emitting the address in debug info.
Definition at line 331 of file TargetLoweringObjectFile.cpp.
References llvm::MCSymbolRefExpr::Create().
Referenced by llvm::CompileUnit::createGlobalVariableDIE(), and getStaticDtorSection().
virtual const MCSection* llvm::TargetLoweringObjectFile::getExplicitSectionGlobal (const GlobalValue * GV, SectionKind Kind, Mangler * Mang, const TargetMachine & TM) const pure virtual
getExplicitSectionGlobal - Targets should implement this method to assign a section to globals with an explicit section specfied. The implementation of this method can assume that GV->hasSection() is true.
Implemented in llvm::TargetLoweringObjectFileCOFF, llvm::NVPTXTargetObjectFile, llvm::TargetLoweringObjectFileMachO, and llvm::TargetLoweringObjectFileELF.
Referenced by SectionForGlobal().
SectionKind TargetLoweringObjectFile::getKindForGlobal (const GlobalValue * GV, const TargetMachine & TM) static
getKindForGlobal - Classify the specified global variable into a set of target independent categories embodied in SectionKind.
getKindForGlobal - This is a top-level target-independent classifier for a global variable. Given an global variable and information from TM, it classifies the global in a variety of ways that make various target implementations simpler. The target implementation is free to ignore this extra info of course.
Definition at line 127 of file TargetLoweringObjectFile.cpp.
References llvm::dyn_cast(), llvm::SectionKind::getBSS(), llvm::SectionKind::getBSSExtern(), llvm::SectionKind::getBSSLocal(), llvm::SectionKind::getCommon(), llvm::TargetMachine::getDataLayout(), llvm::SectionKind::getDataNoRel(), llvm::SectionKind::getDataRel(), llvm::SectionKind::getDataRelLocal(), llvm::GlobalVariable::getInitializer(), llvm::SectionKind::getMergeable1ByteCString(), llvm::SectionKind::getMergeable2ByteCString(), llvm::SectionKind::getMergeable4ByteCString(), llvm::SectionKind::getMergeableConst(), llvm::SectionKind::getMergeableConst16(), llvm::SectionKind::getMergeableConst4(), llvm::SectionKind::getMergeableConst8(), llvm::SectionKind::getReadOnly(), llvm::SectionKind::getReadOnlyWithRel(), llvm::SectionKind::getReadOnlyWithRelLocal(), llvm::Constant::getRelocationInfo(), llvm::TargetMachine::getRelocationModel(), llvm::SectionKind::getText(), llvm::SectionKind::getThreadBSS(), llvm::SectionKind::getThreadData(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::Constant::GlobalRelocations, llvm::GlobalValue::hasAvailableExternallyLinkage(), llvm::GlobalValue::hasCommonLinkage(), llvm::GlobalValue::hasExternalLinkage(), llvm::GlobalValue::hasLocalLinkage(), llvm::GlobalValue::hasUnnamedAddr(), llvm::GlobalVariable::isConstant(), llvm::GlobalValue::isDeclaration(), IsNullTerminatedString(), isSuitableForBSS(), llvm::GlobalVariable::isThreadLocal(), llvm_unreachable, llvm::Constant::LocalRelocation, llvm::Constant::NoRelocation, llvm::TargetOptions::NoZerosInBSS, llvm::TargetMachine::Options, SectionForGlobal(), and llvm::Reloc::Static.
Referenced by llvm::AsmPrinter::EmitGlobalVariable(), INITIALIZE_PASS(), llvm::HexagonTargetObjectFile::IsGlobalInSmallSection(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), SectionForGlobal(), and shouldEmitUsedDirectiveFor().
const MCSection * TargetLoweringObjectFile::getSectionForConstant (SectionKind Kind) const virtual
getSectionForConstant - Given a constant with the SectionKind, return a section that it should be placed in.
getSectionForConstant - Given a mergable constant with the specified size and relocation information, return a section that it should be placed in.
Reimplemented in llvm::TargetLoweringObjectFileMachO, llvm::NVPTXTargetObjectFile, and llvm::TargetLoweringObjectFileELF.
Definition at line 291 of file TargetLoweringObjectFile.cpp.
References llvm::MCObjectFileInfo::DataSection, getTTypeGlobalReference(), llvm::SectionKind::isReadOnly(), and llvm::MCObjectFileInfo::ReadOnlySection.
Referenced by llvm::AsmPrinter::EmitConstantPool(), llvm::AsmPrinter::EmitJumpTableInfo(), and shouldEmitUsedDirectiveFor().
virtual const MCSection* llvm::TargetLoweringObjectFile::getSpecialCasedSectionGlobals (const GlobalValue * GV, Mangler * Mang, SectionKind Kind) const inline virtual
getSpecialCasedSectionGlobals - Allow the target to completely override section assignment of a global.
Definition at line 107 of file TargetLoweringObjectFile.h.
References getCFIPersonalitySymbol(), getSymbol(), getTTypeGlobalReference(), getTTypeReference(), and M.
virtual const MCSection* llvm::TargetLoweringObjectFile::getStaticCtorSection (unsigned Priority = 65535) const inline virtual
Reimplemented in llvm::TargetLoweringObjectFileELF.
Definition at line 135 of file TargetLoweringObjectFile.h.
References llvm::MCObjectFileInfo::StaticCtorSection.
Referenced by llvm::AsmPrinter::EmitSpecialLLVMGlobal().
virtual const MCSection* llvm::TargetLoweringObjectFile::getStaticDtorSection (unsigned Priority = 65535) const inline virtual
Reimplemented in llvm::TargetLoweringObjectFileELF.
Definition at line 140 of file TargetLoweringObjectFile.h.
References getDebugThreadLocalSymbol(), SelectSectionForGlobal(), and llvm::MCObjectFileInfo::StaticDtorSection.
Referenced by llvm::AsmPrinter::EmitSpecialLLVMGlobal().
MCSymbol * TargetLoweringObjectFile::getSymbol (Mangler & M, const GlobalValue * GV) const
Return the MCSymbol for the specified global value. This symbol is the main label that is the address of the global
Return the MCSymbol for the specified global value. This symbol is the main label that is the address of the global.
Definition at line 102 of file TargetLoweringObjectFile.cpp.
References getCFIPersonalitySymbol(), llvm::Mangler::getNameWithPrefix(), llvm::MCContext::GetOrCreateSymbol(), and llvm::SmallString< InternalLen >::str().
Referenced by getCFIPersonalitySymbol(), getSpecialCasedSectionGlobals(), llvm::AsmPrinter::getSymbol(), and getTTypeGlobalReference().
const MCExpr * TargetLoweringObjectFile::getTTypeGlobalReference (const GlobalValue * GV, Mangler * Mang, MachineModuleInfo * MMI, unsigned Encoding, MCStreamer & Streamer) const virtual
getTTypeGlobalReference - Return an MCExpr to use for a reference to the specified global variable from exception handling information.
Reimplemented in llvm::TargetLoweringObjectFileMachO, llvm::TargetLoweringObjectFileELF, llvm::ARMElfTargetObjectFile, and llvm::X86_64MachoTargetObjectFile.
Definition at line 302 of file TargetLoweringObjectFile.cpp.
References llvm::MCSymbolRefExpr::Create(), getContext(), getSymbol(), and getTTypeReference().
Referenced by llvm::AsmPrinter::EmitTTypeReference(), getSectionForConstant(), getSpecialCasedSectionGlobals(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), and llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference().
const MCExpr * TargetLoweringObjectFile::getTTypeReference (const MCSymbolRefExpr * Sym, unsigned Encoding, MCStreamer & Streamer) const
Definition at line 312 of file TargetLoweringObjectFile.cpp.
References llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateSub(), llvm::MCContext::CreateTempSymbol(), llvm::dwarf::DW_EH_PE_absptr, llvm::dwarf::DW_EH_PE_pcrel, llvm::MCStreamer::EmitLabel(), getContext(), and llvm::report_fatal_error().
Referenced by getSpecialCasedSectionGlobals(), llvm::TargetLoweringObjectFileELF::getTTypeGlobalReference(), llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference(), and getTTypeGlobalReference().
void TargetLoweringObjectFile::Initialize (MCContext & ctx, const TargetMachine & TM) virtual
Initialize - this method must be called before any actual lowering is done. This specifies the current context for codegen, and gives the lowering implementations a chance to set up their default sections.
Reimplemented in llvm::NVPTXTargetObjectFile, llvm::ARMElfTargetObjectFile, llvm::MipsTargetObjectFile, llvm::HexagonTargetObjectFile, and llvm::XCoreTargetObjectFile.
Definition at line 40 of file TargetLoweringObjectFile.cpp.
References llvm::TargetMachine::getCodeModel(), llvm::TargetMachine::getRelocationModel(), llvm::TargetMachine::getTargetTriple(), and llvm::MCObjectFileInfo::InitMCObjectFileInfo().
Referenced by llvm::X86_64MachoTargetObjectFile::getCFIPersonalitySymbol(), llvm::XCoreTargetObjectFile::Initialize(), llvm::HexagonTargetObjectFile::Initialize(), llvm::MipsTargetObjectFile::Initialize(), llvm::ARMElfTargetObjectFile::Initialize(), llvm::NVPTXTargetObjectFile::Initialize(), and TargetLoweringObjectFile().
const MCSection * TargetLoweringObjectFile::SectionForGlobal (const GlobalValue * GV, SectionKind Kind, Mangler * Mang, const TargetMachine & TM) const
SectionForGlobal - This method computes the appropriate section to emit the specified global variable or function definition. This should not be passed external (or available externally) globals.
Definition at line 255 of file TargetLoweringObjectFile.cpp.
References getExplicitSectionGlobal(), llvm::GlobalValue::hasSection(), and SelectSectionForGlobal().
Referenced by llvm::AsmPrinter::EmitGlobalVariable(), llvm::ARMAsmPrinter::EmitStartOfAsmFile(), getKindForGlobal(), SectionForGlobal(), and shouldEmitUsedDirectiveFor().
const MCSection* llvm::TargetLoweringObjectFile::SectionForGlobal (const GlobalValue * GV, Mangler * Mang, const TargetMachine & TM) const inline
SectionForGlobal - This method computes the appropriate section to emit the specified global variable or function definition. This should not be passed external (or available externally) globals.
Definition at line 91 of file TargetLoweringObjectFile.h.
References getExplicitSectionGlobal(), getKindForGlobal(), and SectionForGlobal().
const MCSection * TargetLoweringObjectFile::SelectSectionForGlobal (const GlobalValue * GV, SectionKind Kind, Mangler * Mang, const TargetMachine & TM) const protected virtual
Reimplemented in llvm::TargetLoweringObjectFileCOFF, llvm::TargetLoweringObjectFileMachO, llvm::TargetLoweringObjectFileELF, llvm::HexagonTargetObjectFile, and llvm::MipsTargetObjectFile.
Definition at line 269 of file TargetLoweringObjectFile.cpp.
References llvm::MCObjectFileInfo::BSSSection, llvm::MCObjectFileInfo::getDataSection(), llvm::MCObjectFileInfo::getTextSection(), llvm::SectionKind::isBSS(), llvm::SectionKind::isReadOnly(), llvm::SectionKind::isText(), llvm::SectionKind::isThreadLocal(), and llvm::MCObjectFileInfo::ReadOnlySection.
Referenced by getStaticDtorSection(), and SectionForGlobal().
virtual bool llvm::TargetLoweringObjectFile::shouldEmitUsedDirectiveFor (const GlobalValue * GV, Mangler *) const inline virtual
shouldEmitUsedDirectiveFor - This hook allows targets to selectively decide not to emit the UsedDirective for some symbols in llvm.used. FIXME: REMOVE this (rdar://7071300)
Reimplemented in llvm::TargetLoweringObjectFileMachO.
Definition at line 67 of file TargetLoweringObjectFile.h.
References getKindForGlobal(), getSectionForConstant(), and SectionForGlobal().
Referenced by llvm::AsmPrinter::EmitSpecialLLVMGlobal(), and llvm::TargetLoweringObjectFileMachO::~TargetLoweringObjectFileMachO().
The documentation for this class was generated from the following files:
TargetLoweringObjectFile.h
TargetLoweringObjectFile.cpp