LLVM: llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t > Class Template Reference
LLVM API Documentation
llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t > Class Template Reference
#include <InstIterator.h>
Public Types
typedef std::bidirectional_iterator_tag iterator_category
typedef IIty value_type
typedef signed difference_type
typedef IIty * pointer
typedef IIty & reference
Public Member Functions
InstIterator ()
template<typename A , typename B , typename C , typename D >
InstIterator (const InstIterator< A, B, C, D > &II)
template<typename A , typename B , typename C , typename D >
InstIterator (InstIterator< A, B, C, D > &II)
template<class M >
InstIterator (M &m)
template<class M >
InstIterator (M &m, bool)
BBIty & getBasicBlockIterator ()
BIty & getInstructionIterator ()
reference operator* () const
pointer operator-> () const
bool operator== (const InstIterator &y) const
bool operator!= (const InstIterator &y) const
InstIterator & operator++ ()
InstIterator operator++ (int)
InstIterator & operator-- ()
InstIterator operator-- (int)
bool atEnd () const
Detailed Description
template<class _BB_t, class _BB_i_t, class _BI_t, class _II_t>
class llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t >
Definition at line 31 of file InstIterator.h.
Member Typedef Documentation
template<class _BB_t, class _BB_i_t, class _BI_t, class _II_t> typedef signed llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t >::difference_type
Definition at line 42 of file InstIterator.h.
template<class _BB_t, class _BB_i_t, class _BI_t, class _II_t> typedef std::bidirectional_iterator_tag llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t >::iterator_category
Definition at line 40 of file InstIterator.h.
template<class _BB_t, class _BB_i_t, class _BI_t, class _II_t> typedef IIty* llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t >::pointer
Definition at line 43 of file InstIterator.h.
template<class _BB_t, class _BB_i_t, class _BI_t, class _II_t> typedef IIty& llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t >::reference
Definition at line 44 of file InstIterator.h.
template<class _BB_t, class _BB_i_t, class _BI_t, class _II_t> typedef IIty llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t >::value_type
Definition at line 41 of file InstIterator.h.
Constructor & Destructor Documentation
template<class _BB_t, class _BB_i_t, class _BI_t, class _II_t> llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t >::InstIterator () inline
Definition at line 47 of file InstIterator.h.
template<class _BB_t, class _BB_i_t, class _BI_t, class _II_t> template<typename A , typename B , typename C , typename D > llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t >::InstIterator (const InstIterator< A, B, C, D > & II) inline
Definition at line 51 of file InstIterator.h.
template<class _BB_t, class _BB_i_t, class _BI_t, class _II_t> template<typename A , typename B , typename C , typename D > llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t >::InstIterator (InstIterator< A, B, C, D > & II) inline
Definition at line 55 of file InstIterator.h.
template<class _BB_t, class _BB_i_t, class _BI_t, class _II_t> template<class M > llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t >::InstIterator (M & m) inline
Definition at line 58 of file InstIterator.h.
template<class _BB_t, class _BB_i_t, class _BI_t, class _II_t> template<class M > llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t >::InstIterator (M & m, bool) inline
Definition at line 66 of file InstIterator.h.
Member Function Documentation
template<class _BB_t, class _BB_i_t, class _BI_t, class _II_t> bool llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t >::atEnd () const inline
Definition at line 105 of file InstIterator.h.
Referenced by llvm::constant_iterator::atEnd(), and llvm::constant_iterator::operator++().
template<class _BB_t, class _BB_i_t, class _BI_t, class _II_t> BBIty& llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t >::getBasicBlockIterator () inline
Definition at line 71 of file InstIterator.h.
Referenced by ComputePostOrders().
template<class _BB_t, class _BB_i_t, class _BI_t, class _II_t> BIty& llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t >::getInstructionIterator () inline
Definition at line 72 of file InstIterator.h.
Referenced by ComputePostOrders().
template<class _BB_t, class _BB_i_t, class _BI_t, class _II_t> bool llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t >::operator!= (const InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t > & y) const inline
Definition at line 80 of file InstIterator.h.
template<class _BB_t, class _BB_i_t, class _BI_t, class _II_t> reference llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t >::operator* () const inline
Definition at line 74 of file InstIterator.h.
Referenced by llvm::InstIterator< const iplist< BasicBlock >, Function::const_iterator, BasicBlock::const_iterator, const Instruction >::operator->().
template<class _BB_t, class _BB_i_t, class _BI_t, class _II_t> InstIterator& llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t >::operator++ () inline
Definition at line 84 of file InstIterator.h.
template<class _BB_t, class _BB_i_t, class _BI_t, class _II_t> InstIterator llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t >::operator++ (int) inline
Definition at line 89 of file InstIterator.h.
template<class _BB_t, class _BB_i_t, class _BI_t, class _II_t> InstIterator& llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t >::operator-- () inline
Definition at line 93 of file InstIterator.h.
template<class _BB_t, class _BB_i_t, class _BI_t, class _II_t> InstIterator llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t >::operator-- (int) inline
Definition at line 101 of file InstIterator.h.
template<class _BB_t, class _BB_i_t, class _BI_t, class _II_t> pointer llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t >::operator-> () const inline
Definition at line 75 of file InstIterator.h.
template<class _BB_t, class _BB_i_t, class _BI_t, class _II_t> bool llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t >::operator== (const InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t > & y) const inline
Definition at line 77 of file InstIterator.h.
Referenced by llvm::InstIterator< const iplist< BasicBlock >, Function::const_iterator, BasicBlock::const_iterator, const Instruction >::operator!=().
The documentation for this class was generated from the following file:
InstIterator.h