LLVM: llvm::SCEVUnknown Class Reference
LLVM API Documentation
llvm::SCEVUnknown Class Reference
#include <ScalarEvolutionExpressions.h>
Public Member Functions
Value * getValue () const
bool isSizeOf (Type *&AllocTy) const
bool isAlignOf (Type *&AllocTy) const
bool isOffsetOf (Type *&STy, Constant *&FieldNo) const
Type * getType () const
Public Member Functions inherited from llvm::SCEV
SCEV (const FoldingSetNodeIDRef ID, unsigned SCEVTy)
unsigned getSCEVType () const
Type * getType () const
bool isZero () const
bool isOne () const
bool isAllOnesValue () const
bool isNonConstantNegative () const
void print (raw_ostream &OS) const
void dump () const
Public Member Functions inherited from llvm::FoldingSetImpl::Node
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static bool classof (const SCEV *S)
Methods for support type inquiry through isa, cast, and dyn_cast:
Friends
class ScalarEvolution
Additional Inherited Members
Public Types inherited from llvm::SCEV
enum NoWrapFlags {
FlagAnyWrap = 0, FlagNW = (1 << 0), FlagNUW = (1 << 1), FlagNSW = (1 << 2),
NoWrapMask = (1 << 3) -1
}
Protected Attributes inherited from llvm::SCEV
unsigned short SubclassData
Detailed Description
SCEVUnknown - This means that we are dealing with an entirely unknown SCEV value, and only represent it as its LLVM Value. This is the "bottom" value for the analysis.
Definition at line 409 of file ScalarEvolutionExpressions.h.
Member Function Documentation
static bool llvm::SCEVUnknown::classof (const SCEV * S) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 445 of file ScalarEvolutionExpressions.h.
References llvm::SCEV::getSCEVType(), and llvm::scUnknown.
Type* llvm::SCEVUnknown::getType () const inline
Definition at line 442 of file ScalarEvolutionExpressions.h.
Value* llvm::SCEVUnknown::getValue () const inline
Definition at line 430 of file ScalarEvolutionExpressions.h.
Referenced by isOffsetOf(), llvm::SCEV::print(), llvm::SCEVExpander::setChainedPhi(), and llvm::SCEVParameterRewriter::visitUnknown().
bool SCEVUnknown::isAlignOf (Type *& AllocTy) const
Definition at line 404 of file ScalarEvolution.cpp.
References llvm::SCEVCastExpr::Ty.
Referenced by llvm::SCEV::print().
bool SCEVUnknown::isOffsetOf (Type *& STy, Constant *& FieldNo) const
Definition at line 429 of file ScalarEvolution.cpp.
References llvm::Argument::getArgNo(), llvm::APInt::getBitWidth(), llvm::SCEVUDivExpr::getLHS(), llvm::SCEVAddRecExpr::getLoop(), llvm::LoopBase< BlockT, LoopT >::getLoopDepth(), llvm::LoopInfo::getLoopDepth(), llvm::User::getNumOperands(), llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVCastExpr::getOperand(), llvm::User::getOperand(), llvm::SCEVNAryExpr::getOperand(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::SCEVUDivExpr::getRHS(), llvm::SCEV::getSCEVType(), llvm::Value::getType(), llvm::SCEVConstant::getValue(), llvm::ConstantInt::getValue(), getValue(), i, int, llvm::Type::isArrayTy(), llvm::Type::isPointerTy(), llvm::Type::isStructTy(), llvm_unreachable, llvm::scAddExpr, llvm::scAddRecExpr, llvm::scConstant, llvm::scMulExpr, llvm::scSignExtend, llvm::scSMaxExpr, llvm::scTruncate, llvm::scUDivExpr, llvm::scUMaxExpr, llvm::scUnknown, llvm::scZeroExtend, llvm::SCEVCastExpr::Ty, and llvm::X.
Referenced by llvm::SCEV::print().
bool SCEVUnknown::isSizeOf (Type *& AllocTy) const
isSizeOf, isAlignOf, isOffsetOf - Test whether this is a special constant representing a type size, alignment, or field offset in a target-independent manner, and hasn't happened to have been folded with other operations into something unrecognizable. This is mainly only useful for pretty-printing and other situations where it isn't absolutely required for these to succeed.
Definition at line 387 of file ScalarEvolution.cpp.
Referenced by llvm::SCEV::print().
Friends And Related Function Documentation
friend class ScalarEvolution friend
Definition at line 410 of file ScalarEvolutionExpressions.h.
The documentation for this class was generated from the following files:
ScalarEvolutionExpressions.h
ScalarEvolution.cpp