LLVM: llvm::GetElementPtrInst Class Reference
LLVM API Documentation
llvm::GetElementPtrInst Class Reference
#include <Instructions.h>
Public Member Functions
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
SequentialType * getType () const
unsigned getAddressSpace () const
Returns the address space of this instruction's pointer type.
op_iterator idx_begin ()
const_op_iterator idx_begin () const
op_iterator idx_end ()
const_op_iterator idx_end () const
Value * getPointerOperand ()
const Value * getPointerOperand () const
Type * getPointerOperandType () const
unsigned getPointerAddressSpace () const
Returns the address space of the pointer operand.
unsigned getNumIndices () const
bool hasIndices () const
bool hasAllZeroIndices () const
bool hasAllConstantIndices () const
void setIsInBounds (bool b=true)
bool isInBounds () const
isInBounds - Determine whether the GEP has the inbounds flag.
bool accumulateConstantOffset (const DataLayout &DL, APInt &Offset) const
Accumulate the constant address offset of this GEP if possible.
Public Member Functions inherited from llvm::Instruction
~Instruction ()
Instruction * use_back ()
const Instruction * use_back () const
const BasicBlock * getParent () const
BasicBlock * getParent ()
void removeFromParent ()
void eraseFromParent ()
void insertBefore (Instruction *InsertPos)
void insertAfter (Instruction *InsertPos)
void moveBefore (Instruction *MovePos)
unsigned getOpcode () const
getOpcode() returns a member of one of the enums like Instruction::Add.
const char * getOpcodeName () const
bool isTerminator () const
bool isBinaryOp () const
bool isShift ()
bool isCast () const
bool isLogicalShift () const
bool isArithmeticShift () const
isArithmeticShift - Return true if this is an arithmetic shift right.
bool hasMetadata () const
bool hasMetadataOtherThanDebugLoc () const
MDNode * getMetadata (unsigned KindID) const
MDNode * getMetadata (StringRef Kind) const
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
void getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
void setMetadata (unsigned KindID, MDNode *Node)
void setMetadata (StringRef Kind, MDNode *Node)
void setDebugLoc (const DebugLoc &Loc)
setDebugLoc - Set the debug location information for this instruction.
const DebugLoc & getDebugLoc () const
getDebugLoc - Return the debug location for this node as a DebugLoc.
void setHasUnsafeAlgebra (bool B)
void setHasNoNaNs (bool B)
void setHasNoInfs (bool B)
void setHasNoSignedZeros (bool B)
void setHasAllowReciprocal (bool B)
void setFastMathFlags (FastMathFlags FMF)
bool hasUnsafeAlgebra () const
Determine whether the unsafe-algebra flag is set.
bool hasNoNaNs () const
Determine whether the no-NaNs flag is set.
bool hasNoInfs () const
Determine whether the no-infs flag is set.
bool hasNoSignedZeros () const
Determine whether the no-signed-zeros flag is set.
bool hasAllowReciprocal () const
Determine whether the allow-reciprocal flag is set.
FastMathFlags getFastMathFlags () const
void copyFastMathFlags (const Instruction *I)
Copy I's fast-math flags.
bool isAssociative () const
bool isCommutative () const
bool isIdempotent () const
bool isNilpotent () const
bool mayWriteToMemory () const
bool mayReadFromMemory () const
bool mayReadOrWriteMemory () const
bool mayThrow () const
bool mayReturn () const
bool mayHaveSideEffects () const
Instruction * clone () const
bool isIdenticalTo (const Instruction *I) const
bool isIdenticalToWhenDefined (const Instruction *I) const
bool isSameOperationAs (const Instruction *I, unsigned flags=0) const
Determine if one instruction is the same operation as another.
bool isUsedOutsideOfBlock (const BasicBlock *BB) const
Public Member Functions inherited from llvm::User
~User ()
void operator delete (void *Usr)
operator delete - free memory allocated for User and Use objects
void operator delete (void *, unsigned)
placement delete - required by std, but never called.
void operator delete (void *, unsigned, bool)
placement delete - required by std, but never called.
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
void dropAllReferences ()
void replaceUsesOfWith (Value *From, Value *To)
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
dump - Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O, AssemblyAnnotationWriter *AAW=0) const
Type * getType () const
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
void setName (const Twine &Name)
void takeName (Value *V)
void replaceAllUsesWith (Value *V)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
User * use_back ()
const User * use_back () const
bool hasOneUse () const
bool hasNUses (unsigned N) const
bool hasNUsesOrMore (unsigned N) const
bool isUsedInBasicBlock (const BasicBlock *BB) const
unsigned getNumUses () const
void addUse (Use &U)
unsigned getValueID () const
unsigned getRawSubclassOptionalData () const
void clearSubclassOptionalData ()
bool hasSameSubclassOptionalData (const Value *V) const
void intersectOptionalDataWith (const Value *V)
bool hasValueHandle () const
Value * stripPointerCasts ()
Strips off any unneeded pointer casts, all-zero GEPs and aliases from the specified value, returning the original uncasted value.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strips off any unneeded pointer casts and all-zero GEPs from the specified value, returning the original uncasted value.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strips off unneeded pointer casts and all-constant GEPs from the specified value, returning the original pointer value.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Strips like stripInBoundsConstantOffsets but also accumulates the constant offset stripped.
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strips off unneeded pointer casts and any in-bounds offsets from the specified value, returning the original pointer value.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer () const
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Public Member Functions inherited from llvm::ilist_node< Instruction >
Instruction * getPrevNode ()
Get the previous node, or 0 for the list head.
const Instruction * getPrevNode () const
Get the previous node, or 0 for the list head.
Instruction * getNextNode ()
Get the next node, or 0 for the list tail.
const Instruction * getNextNode () const
Get the next node, or 0 for the list tail.
Static Public Member Functions
static GetElementPtrInst * Create (Value *Ptr, ArrayRef< Value * > IdxList, const Twine &NameStr="", Instruction *InsertBefore=0)
static GetElementPtrInst * Create (Value *Ptr, ArrayRef< Value * > IdxList, const Twine &NameStr, BasicBlock *InsertAtEnd)
static GetElementPtrInst * CreateInBounds (Value *Ptr, ArrayRef< Value * > IdxList, const Twine &NameStr="", Instruction *InsertBefore=0)
static GetElementPtrInst * CreateInBounds (Value *Ptr, ArrayRef< Value * > IdxList, const Twine &NameStr, BasicBlock *InsertAtEnd)
static Type * getIndexedType (Type *Ptr, ArrayRef< Value * > IdxList)
static Type * getIndexedType (Type *Ptr, ArrayRef< Constant * > IdxList)
static Type * getIndexedType (Type *Ptr, ArrayRef< uint64_t > IdxList)
static unsigned getPointerOperandIndex ()
static Type * getGEPReturnType (Value *Ptr, ArrayRef< Value * > IdxList)
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Instruction
static const char * getOpcodeName (unsigned OpCode)
static bool isTerminator (unsigned OpCode)
static bool isBinaryOp (unsigned Opcode)
static bool isShift (unsigned Opcode)
Determine if the Opcode is one of the shift instructions.
static bool isCast (unsigned OpCode)
Determine if the OpCode is one of the CastInst instructions.
static bool isAssociative (unsigned op)
static bool isCommutative (unsigned op)
static bool isIdempotent (unsigned op)
static bool isNilpotent (unsigned op)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Protected Member Functions
virtual GetElementPtrInst * clone_impl () const
Protected Member Functions inherited from llvm::Instruction
void setInstructionSubclassData (unsigned short D)
unsigned getSubclassDataFromInstruction () const
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, Instruction *InsertBefore=0)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, BasicBlock *InsertAtEnd)
Protected Member Functions inherited from llvm::User
void * operator new (size_t s, unsigned Us)
User (Type *ty, unsigned vty, Use *OpList, unsigned NumOps)
Use * allocHungoffUses (unsigned) const
void dropHungoffUses ()
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
virtual void printCustom (raw_ostream &O) const
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Member Functions inherited from llvm::ilist_node< Instruction >
ilist_node ()
Additional Inherited Members
Public Types inherited from llvm::Instruction
enum OperationEquivalenceFlags { CompareIgnoringAlignment = 1<<0, CompareUsingScalarTypes = 1<<1 }
enum TermOps
enum BinaryOps
enum MemoryOps
enum CastOps
enum OtherOps
Public Types inherited from llvm::User
typedef Use * op_iterator
typedef const Use * const_op_iterator
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal, BasicBlockVal, FunctionVal, GlobalAliasVal,
GlobalVariableVal, UndefValueVal, BlockAddressVal, ConstantExprVal,
ConstantAggregateZeroVal, ConstantDataArrayVal, ConstantDataVectorVal, ConstantIntVal,
ConstantFPVal, ConstantArrayVal, ConstantStructVal, ConstantVectorVal,
ConstantPointerNullVal, MDNodeVal, MDStringVal, InlineAsmVal,
PseudoSourceValueVal, FixedStackPseudoSourceValueVal, InstructionVal, ConstantFirstVal = FunctionVal,
ConstantLastVal = ConstantPointerNullVal
}
typedef value_use_iterator< User > use_iterator
typedef value_use_iterator< const User > const_use_iterator
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::User
Use * OperandList
unsigned NumOperands
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Detailed Description
GetElementPtrInst - an instruction for type-safe pointer arithmetic to access elements of arrays and structs
Definition at line 709 of file Instructions.h.
Member Function Documentation
bool GetElementPtrInst::accumulateConstantOffset (const DataLayout & DL, APInt & Offset) const
Accumulate the constant address offset of this GEP if possible.
This routine accepts an APInt into which it will accumulate the constant offset of this GEP if the GEP is in fact constant. If the GEP is not all-constant, it returns false and the value of the offset APInt is undefined (it is not preserved!). The APInt passed into this routine must be at least as wide as the IntPtr type for the address space of the base GEP pointer.
Definition at line 1430 of file Instructions.cpp.
References ExtractElement(), llvm::Value::getType(), and llvm::Value::setName().
Referenced by llvm::detail::PtrUseVisitorBase::adjustOffsetForGEP(), and llvm::InstCombiner::visitGetElementPtrInst().
static bool llvm::GetElementPtrInst::classof (const Instruction * I) inline static
Definition at line 863 of file Instructions.h.
References llvm::Instruction::getOpcode().
static bool llvm::GetElementPtrInst::classof (const Value * V) inline static
Definition at line 866 of file Instructions.h.
References llvm::AllocaInst::classof().
GetElementPtrInst * GetElementPtrInst::clone_impl () const protected virtual
Implements llvm::Instruction.
Definition at line 3511 of file Instructions.cpp.
References llvm::User::getNumOperands().
static GetElementPtrInst* llvm::GetElementPtrInst::Create (Value * Ptr, ArrayRef< Value * > IdxList, const Twine & NameStr = "", Instruction * InsertBefore = 0) inline static
Definition at line 726 of file Instructions.h.
References llvm::ArrayRef< T >::size().
Referenced by BuildNew(), llvm::IRBuilder< true, TargetFolder >::CreateConstGEP1_32(), llvm::IRBuilder< true, TargetFolder >::CreateConstGEP1_64(), llvm::IRBuilder< true, TargetFolder >::CreateConstGEP2_32(), llvm::IRBuilder< true, TargetFolder >::CreateConstGEP2_64(), llvm::IRBuilder< true, TargetFolder >::CreateGEP(), llvm::NoFolder::CreateGetElementPtr(), llvm::CodeExtractor::findInputsOutputs(), FindPhiPredForUseInBlock(), FunctionNumber(), llvm::ConstantExpr::getAsInstruction(), MarkBlocksLiveIn(), MarkIndicesSafe(), llvm::BitcodeReader::ParseTriple(), llvm::PHITransAddr::PHITranslateWithInsertion(), RewriteHeapSROALoadUser(), SRAGlobal(), and llvm::InstCombiner::visitGetElementPtrInst().
static GetElementPtrInst* llvm::GetElementPtrInst::Create (Value * Ptr, ArrayRef< Value * > IdxList, const Twine & NameStr, BasicBlock * InsertAtEnd) inline static
Definition at line 733 of file Instructions.h.
References llvm::ArrayRef< T >::size().
static GetElementPtrInst* llvm::GetElementPtrInst::CreateInBounds (Value * Ptr, ArrayRef< Value * > IdxList, const Twine & NameStr = "", Instruction * InsertBefore = 0) inline static
Create an "inbounds" getelementptr. See the documentation for the "inbounds" flag in LangRef.html for details.
Definition at line 743 of file Instructions.h.
References setIsInBounds().
Referenced by llvm::IRBuilder< true, TargetFolder >::CreateConstInBoundsGEP1_32(), llvm::IRBuilder< true, TargetFolder >::CreateConstInBoundsGEP1_64(), llvm::IRBuilder< true, TargetFolder >::CreateConstInBoundsGEP2_32(), llvm::IRBuilder< true, TargetFolder >::CreateConstInBoundsGEP2_64(), llvm::IRBuilder< true, TargetFolder >::CreateInBoundsGEP(), llvm::NoFolder::CreateInBoundsGetElementPtr(), llvm::ConstantExpr::getAsInstruction(), isCompatibleAggregate(), llvm::InstCombiner::visitAllocaInst(), llvm::InstCombiner::visitBitCast(), and llvm::InstCombiner::visitGetElementPtrInst().
static GetElementPtrInst* llvm::GetElementPtrInst::CreateInBounds (Value * Ptr, ArrayRef< Value * > IdxList, const Twine & NameStr, BasicBlock * InsertAtEnd) inline static
Definition at line 751 of file Instructions.h.
References llvm::UnaryInstruction::DECLARE_TRANSPARENT_OPERAND_ACCESSORS(), and setIsInBounds().
llvm::GetElementPtrInst::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
unsigned llvm::GetElementPtrInst::getAddressSpace () const inline
Returns the address space of this instruction's pointer type.
Definition at line 769 of file Instructions.h.
static Type* llvm::GetElementPtrInst::getGEPReturnType (Value * Ptr, ArrayRef< Value * > IdxList) inline static
GetGEPReturnType - Returns the pointer type returned by the GEP instruction, which may be a vector of pointers.
Definition at line 813 of file Instructions.h.
References llvm::checkGEPType(), llvm::VectorType::get(), llvm::PointerType::get(), llvm::Type::getPointerAddressSpace(), llvm::Value::getType(), and llvm::Type::isVectorTy().
Type * GetElementPtrInst::getIndexedType (Type * Ptr, ArrayRef< Value * > IdxList) static
getIndexedType - Returns the type of the element that would be loaded with a load instruction with the specified parameters.
Null is returned if the indices are invalid for the specified pointer type.
Definition at line 1384 of file Instructions.cpp.
References getIndexedTypeInternal().
Referenced by CastGEPIndices(), ConstantFoldGetElementPtrImpl(), FunctionNumber(), llvm::ConstantExpr::getGetElementPtr(), MarkIndicesSafe(), and SimplifyGEPInst().
Type * GetElementPtrInst::getIndexedType (Type * Ptr, ArrayRef< Constant * > IdxList) static
Definition at line 1388 of file Instructions.cpp.
References getIndexedTypeInternal().
Type * GetElementPtrInst::getIndexedType (Type * Ptr, ArrayRef< uint64_t > IdxList) static
Definition at line 1393 of file Instructions.cpp.
References getIndexedTypeInternal().
unsigned llvm::GetElementPtrInst::getNumIndices () const inline
Definition at line 827 of file Instructions.h.
References llvm::User::getNumOperands().
Referenced by MarkIndicesSafe(), and llvm::InstCombiner::visitGetElementPtrInst().
unsigned llvm::GetElementPtrInst::getPointerAddressSpace () const inline
Returns the address space of the pointer operand.
Definition at line 807 of file Instructions.h.
Referenced by llvm::InstCombiner::visitGetElementPtrInst().
Value* llvm::GetElementPtrInst::getPointerOperand () inline
Definition at line 790 of file Instructions.h.
References llvm::User::getOperand().
Referenced by getGEPInductionOperand(), llvm::DenseMapInfo< ComparableFunction >::getHashValue(), and llvm::Interpreter::visitGetElementPtrInst().
const Value* llvm::GetElementPtrInst::getPointerOperand () const inline
Definition at line 793 of file Instructions.h.
References llvm::User::getOperand().
static unsigned llvm::GetElementPtrInst::getPointerOperandIndex () inline static
Definition at line 796 of file Instructions.h.
Type* llvm::GetElementPtrInst::getPointerOperandType () const inline
getPointerOperandType - Method to return the pointer operand as a PointerType.
Definition at line 802 of file Instructions.h.
References getPointerOperand().
Referenced by isCompatibleAggregate(), tryToMakeAllocaBePromotable(), and llvm::InstCombiner::visitGetElementPtrInst().
SequentialType* llvm::GetElementPtrInst::getType () const inline
Definition at line 764 of file Instructions.h.
References llvm::Value::getType().
Referenced by llvm::FenceInst::FenceInst(), llvm::InstCombiner::FoldCmpLoadFromIndexedGlobal(), getGEPInductionOperand(), isCompatibleAggregate(), and llvm::InstCombiner::visitGetElementPtrInst().
bool GetElementPtrInst::hasAllConstantIndices () const
hasAllConstantIndices - Return true if all of the indices of this GEP are constant integers. If so, the result pointer and the first operand have a constant offset between them.
Definition at line 1414 of file Instructions.cpp.
References llvm::User::getNumOperands(), llvm::User::getOperand(), and i.
Referenced by isCompatibleAggregate(), and isSafeAndProfitableToSinkLoad().
bool GetElementPtrInst::hasAllZeroIndices () const
hasAllZeroIndices - Return true if all of the indices of this GEP are zeros. If so, the result pointer and the first operand have the same value, just potentially different types.
Definition at line 1400 of file Instructions.cpp.
References llvm::User::getNumOperands(), llvm::User::getOperand(), and i.
bool llvm::GetElementPtrInst::hasIndices () const inline
Definition at line 831 of file Instructions.h.
References b, and llvm::User::getNumOperands().
op_iterator llvm::GetElementPtrInst::idx_begin () inline
Definition at line 785 of file Instructions.h.
References llvm::User::op_begin().
Referenced by MarkIndicesSafe(), and llvm::InstCombiner::visitGetElementPtrInst().
const_op_iterator llvm::GetElementPtrInst::idx_begin () const inline
Definition at line 786 of file Instructions.h.
References llvm::User::op_begin().
op_iterator llvm::GetElementPtrInst::idx_end () inline
Definition at line 787 of file Instructions.h.
References llvm::User::op_end().
Referenced by MarkIndicesSafe(), and llvm::InstCombiner::visitGetElementPtrInst().
const_op_iterator llvm::GetElementPtrInst::idx_end () const inline
Definition at line 788 of file Instructions.h.
References llvm::User::op_end().
bool GetElementPtrInst::isInBounds () const
isInBounds - Determine whether the GEP has the inbounds flag.
Definition at line 1426 of file Instructions.cpp.
Referenced by llvm::InstCombiner::FoldCmpLoadFromIndexedGlobal(), and llvm::InstCombiner::visitGetElementPtrInst().
void GetElementPtrInst::setIsInBounds (bool b = true)
setIsInBounds - Set or clear the inbounds flag on this GEP instruction. See LangRef.html for the meaning of inbounds on a getelementptr.
Definition at line 1422 of file Instructions.cpp.
Referenced by BuildNew(), CreateInBounds(), and llvm::PHITransAddr::PHITranslateWithInsertion().
The documentation for this class was generated from the following files:
Instructions.h
Instructions.cpp