LLVM: llvm::CriticalAntiDepBreaker Class Reference
LLVM API Documentation
llvm::CriticalAntiDepBreaker Class Reference
#include <CriticalAntiDepBreaker.h>
Public Member Functions
CriticalAntiDepBreaker (MachineFunction &MFi, const RegisterClassInfo &)
~CriticalAntiDepBreaker ()
void StartBlock (MachineBasicBlock *BB)
Start - Initialize anti-dep breaking for a new basic block.
unsigned BreakAntiDependencies (const std::vector< SUnit > &SUnits, MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned InsertPosIndex, DbgValueVector &DbgValues)
void Observe (MachineInstr *MI, unsigned Count, unsigned InsertPosIndex)
void FinishBlock ()
Finish - Finish anti-dep breaking for a basic block.
Public Member Functions inherited from llvm::AntiDepBreaker
virtual ~AntiDepBreaker ()
void UpdateDbgValue (MachineInstr *MI, unsigned OldReg, unsigned NewReg)
Additional Inherited Members
Public Types inherited from llvm::AntiDepBreaker
typedef std::vector< std::pair< MachineInstr *, MachineInstr * > > DbgValueVector
Detailed Description
Definition at line 34 of file CriticalAntiDepBreaker.h.
Constructor & Destructor Documentation
CriticalAntiDepBreaker::CriticalAntiDepBreaker (MachineFunction & MFi, const RegisterClassInfo & RCI)
Definition at line 30 of file CriticalAntiDepBreaker.cpp.
CriticalAntiDepBreaker::~CriticalAntiDepBreaker ()
Definition at line 41 of file CriticalAntiDepBreaker.cpp.
Member Function Documentation
unsigned CriticalAntiDepBreaker::BreakAntiDependencies (const std::vector< SUnit > & SUnits, MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned InsertPosIndex, DbgValueVector & DbgValues) virtual
BreakAntiDependencies - Identifiy anti-dependencies along the critical path of the ScheduleDAG and break them by renaming registers.
Implements llvm::AntiDepBreaker.
Definition at line 406 of file CriticalAntiDepBreaker.cpp.
References llvm::SDep::Anti, CriticalPathStep(), llvm::SDep::Data, llvm::dbgs(), DEBUG, llvm::SUnit::getDepth(), llvm::SUnit::getInstr(), llvm::MCRegisterInfo::getName(), llvm::MachineInstr::getNumOperands(), llvm::MCRegisterInfo::getNumRegs(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineInstr::hasExtraDefRegAllocReq(), i, I, llvm::MachineRegisterInfo::isAllocatable(), llvm::MachineInstr::isCall(), llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isDef(), llvm::TargetInstrInfo::isPredicated(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUse(), llvm::SUnit::Latency, P, llvm::SUnit::Preds, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::TargetRegisterInfo::regsOverlap(), llvm::BitVector::test(), and llvm::AntiDepBreaker::UpdateDbgValue().
Referenced by CriticalPathStep().
void CriticalAntiDepBreaker::FinishBlock () virtual
Finish - Finish anti-dep breaking for a basic block.
Implements llvm::AntiDepBreaker.
Definition at line 89 of file CriticalAntiDepBreaker.cpp.
References llvm::BitVector::reset().
void CriticalAntiDepBreaker::Observe (MachineInstr * MI, unsigned Count, unsigned InsertPosIndex) virtual
Observe - Update liveness information to account for the current instruction, which will not be scheduled.
Implements llvm::AntiDepBreaker.
Definition at line 94 of file CriticalAntiDepBreaker.cpp.
References llvm::MCRegisterInfo::getNumRegs(), and llvm::MachineInstr::isDebugValue().
void CriticalAntiDepBreaker::StartBlock (MachineBasicBlock * BB) virtual
Start - Initialize anti-dep breaking for a new basic block.
Implements llvm::AntiDepBreaker.
Definition at line 44 of file CriticalAntiDepBreaker.cpp.
References llvm::MachineBasicBlock::back(), llvm::TargetRegisterInfo::getCalleeSavedRegs(), llvm::MachineFunction::getFrameInfo(), llvm::MCRegisterInfo::getNumRegs(), llvm::MachineFrameInfo::getPristineRegs(), i, I, llvm::MachineInstr::isReturn(), llvm::MCRegAliasIterator::isValid(), llvm::BitVector::reset(), llvm::MachineBasicBlock::size(), llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_end(), and llvm::BitVector::test().
The documentation for this class was generated from the following files:
CriticalAntiDepBreaker.h
CriticalAntiDepBreaker.cpp