LLVM: llvm::NVPTXFloatMCExpr Class Reference
LLVM API Documentation
llvm::NVPTXFloatMCExpr Class Reference
#include <NVPTXMCExpr.h>
Public Types
enum VariantKind { VK_NVPTX_None, VK_NVPTX_SINGLE_PREC_FLOAT, VK_NVPTX_DOUBLE_PREC_FLOAT }
Public Types inherited from llvm::MCExpr
enum ExprKind {
Binary, Constant, SymbolRef, Unary,
Target
}
Public Member Functions
void PrintImpl (raw_ostream &OS) const
bool EvaluateAsRelocatableImpl (MCValue &Res, const MCAsmLayout *Layout) const
void AddValueSymbols (MCAssembler *) const
const MCSection * FindAssociatedSection () const
void fixELFSymbolsInTLSFixups (MCAssembler &Asm) const
Accessors
VariantKind getKind () const
getOpcode - Get the kind of this expression.
APFloat getAPFloat () const
getSubExpr - Get the child of this expression.
Public Member Functions inherited from llvm::MCExpr
ExprKind getKind () const
void print (raw_ostream &OS) const
void dump () const
bool EvaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout, const SectionAddrMap &Addrs) const
bool EvaluateAsAbsolute (int64_t &Res) const
bool EvaluateAsAbsolute (int64_t &Res, const MCAssembler &Asm) const
bool EvaluateAsAbsolute (int64_t &Res, const MCAsmLayout &Layout) const
bool EvaluateAsRelocatable (MCValue &Res, const MCAsmLayout &Layout) const
const MCSection * FindAssociatedSection () const
Static Public Member Functions
static bool classof (const MCExpr *E)
Construction
static const NVPTXFloatMCExpr * Create (VariantKind Kind, APFloat Flt, MCContext &Ctx)
static const NVPTXFloatMCExpr * CreateConstantFPSingle (APFloat Flt, MCContext &Ctx)
static const NVPTXFloatMCExpr * CreateConstantFPDouble (APFloat Flt, MCContext &Ctx)
Static Public Member Functions inherited from llvm::MCTargetExpr
static bool classof (const MCExpr *E)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCTargetExpr
MCTargetExpr ()
virtual ~MCTargetExpr ()
Protected Member Functions inherited from llvm::MCExpr
MCExpr (ExprKind _Kind)
bool EvaluateAsRelocatableImpl (MCValue &Res, const MCAssembler *Asm, const MCAsmLayout *Layout, const SectionAddrMap *Addrs, bool InSet) const
Detailed Description
Definition at line 20 of file NVPTXMCExpr.h.
Member Enumeration Documentation
enum llvm::NVPTXFloatMCExpr::VariantKind
Enumerator
VK_NVPTX_None
VK_NVPTX_SINGLE_PREC_FLOAT
VK_NVPTX_DOUBLE_PREC_FLOAT
Definition at line 22 of file NVPTXMCExpr.h.
Member Function Documentation
void llvm::NVPTXFloatMCExpr::AddValueSymbols (MCAssembler *) const inline virtual
Implements llvm::MCTargetExpr.
Definition at line 69 of file NVPTXMCExpr.h.
static bool llvm::NVPTXFloatMCExpr::classof (const MCExpr * E) inline static
Definition at line 77 of file NVPTXMCExpr.h.
References llvm::MCExpr::getKind(), and llvm::MCExpr::Target.
const NVPTXFloatMCExpr * NVPTXFloatMCExpr::Create (VariantKind Kind, APFloat Flt, MCContext & Ctx) static
Definition at line 18 of file NVPTXMCExpr.cpp.
Referenced by CreateConstantFPDouble(), and CreateConstantFPSingle().
static const NVPTXFloatMCExpr* llvm::NVPTXFloatMCExpr::CreateConstantFPDouble (APFloat Flt, MCContext & Ctx) inline static
Definition at line 47 of file NVPTXMCExpr.h.
References Create(), and VK_NVPTX_DOUBLE_PREC_FLOAT.
Referenced by llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc().
static const NVPTXFloatMCExpr* llvm::NVPTXFloatMCExpr::CreateConstantFPSingle (APFloat Flt, MCContext & Ctx) inline static
Definition at line 42 of file NVPTXMCExpr.h.
References Create(), and VK_NVPTX_SINGLE_PREC_FLOAT.
Referenced by llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc().
bool llvm::NVPTXFloatMCExpr::EvaluateAsRelocatableImpl (MCValue & Res, const MCAsmLayout * Layout) const inline virtual
Implements llvm::MCTargetExpr.
Definition at line 65 of file NVPTXMCExpr.h.
const MCSection* llvm::NVPTXFloatMCExpr::FindAssociatedSection () const inline virtual
Implements llvm::MCTargetExpr.
Definition at line 70 of file NVPTXMCExpr.h.
void llvm::NVPTXFloatMCExpr::fixELFSymbolsInTLSFixups (MCAssembler & Asm) const inline virtual
Implements llvm::MCTargetExpr.
Definition at line 75 of file NVPTXMCExpr.h.
APFloat llvm::NVPTXFloatMCExpr::getAPFloat () const inline
getSubExpr - Get the child of this expression.
Definition at line 60 of file NVPTXMCExpr.h.
References PrintImpl().
Referenced by PrintImpl().
VariantKind llvm::NVPTXFloatMCExpr::getKind () const inline
getOpcode - Get the kind of this expression.
Definition at line 57 of file NVPTXMCExpr.h.
void NVPTXFloatMCExpr::PrintImpl (raw_ostream & OS) const virtual
Implements llvm::MCTargetExpr.
Definition at line 22 of file NVPTXMCExpr.cpp.
References llvm::APFloat::bitcastToAPInt(), llvm::APFloat::convert(), getAPFloat(), llvm::APInt::getZExtValue(), llvm::APFloat::IEEEdouble, llvm::APFloat::IEEEsingle, llvm_unreachable, llvm::APFloat::rmNearestTiesToEven, llvm::utohexstr(), VK_NVPTX_DOUBLE_PREC_FLOAT, and VK_NVPTX_SINGLE_PREC_FLOAT.
Referenced by getAPFloat().
The documentation for this class was generated from the following files:
NVPTXMCExpr.h
NVPTXMCExpr.cpp