LLVM: llvm::ARMConstantPoolConstant Class Reference
LLVM API Documentation
llvm::ARMConstantPoolConstant Class Reference
#include <ARMConstantPoolValue.h>
Public Member Functions
const GlobalValue * getGV () const
const BlockAddress * getBlockAddress () const
virtual int getExistingMachineCPValue (MachineConstantPool *CP, unsigned Alignment)
virtual bool hasSameValue (ARMConstantPoolValue *ACPV)
virtual void addSelectionDAGCSEId (FoldingSetNodeID &ID)
virtual void print (raw_ostream &O) const
print - Implement operator<<
bool equals (const ARMConstantPoolConstant *A) const
Public Member Functions inherited from llvm::ARMConstantPoolValue
virtual ~ARMConstantPoolValue ()
ARMCP::ARMCPModifier getModifier () const
const char * getModifierText () const
bool hasModifier () const
bool mustAddCurrentAddress () const
unsigned getLabelId () const
unsigned char getPCAdjustment () const
bool isGlobalValue () const
bool isExtSymbol () const
bool isBlockAddress () const
bool isLSDA () const
bool isMachineBasicBlock () const
virtual unsigned getRelocationInfo () const
bool equals (const ARMConstantPoolValue *A) const
void print (raw_ostream *O) const
void dump () const
Public Member Functions inherited from llvm::MachineConstantPoolValue
MachineConstantPoolValue (Type *ty)
virtual ~MachineConstantPoolValue ()
Type * getType () const
Static Public Member Functions
static ARMConstantPoolConstant * Create (const Constant *C, unsigned ID)
static ARMConstantPoolConstant * Create (const GlobalValue *GV, ARMCP::ARMCPModifier Modifier)
static ARMConstantPoolConstant * Create (const Constant *C, unsigned ID, ARMCP::ARMCPKind Kind, unsigned char PCAdj)
static ARMConstantPoolConstant * Create (const Constant *C, unsigned ID, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress)
static bool classof (const ARMConstantPoolValue *APV)
Additional Inherited Members
Protected Member Functions inherited from llvm::ARMConstantPoolValue
ARMConstantPoolValue (Type *Ty, unsigned id, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress)
ARMConstantPoolValue (LLVMContext &C, unsigned id, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress)
template<typename Derived >
int getExistingMachineCPValueImpl (MachineConstantPool *CP, unsigned Alignment)
Detailed Description
ARMConstantPoolConstant - ARM-specific constant pool values for Constants, Functions, and BlockAddresses.
Definition at line 135 of file ARMConstantPoolValue.h.
Member Function Documentation
void ARMConstantPoolConstant::addSelectionDAGCSEId (FoldingSetNodeID & ID) virtual
Reimplemented from llvm::ARMConstantPoolValue.
Definition at line 174 of file ARMConstantPoolValue.cpp.
References llvm::FoldingSetNodeID::AddPointer(), and llvm::ARMConstantPoolValue::addSelectionDAGCSEId().
static bool llvm::ARMConstantPoolConstant::classof (const ARMConstantPoolValue * APV) inline static
Definition at line 177 of file ARMConstantPoolValue.h.
References llvm::ARMConstantPoolValue::isBlockAddress(), llvm::ARMConstantPoolValue::isGlobalValue(), and llvm::ARMConstantPoolValue::isLSDA().
ARMConstantPoolConstant * ARMConstantPoolConstant::Create (const Constant * C, unsigned ID) static
Definition at line 127 of file ARMConstantPoolValue.cpp.
References llvm::ARMCP::CPValue, and llvm::ARMCP::no_modifier.
Referenced by duplicateCPV(), FPCCToARMCC(), getComparePred(), and llvm::ARMTargetLowering::getJumpTableEncoding().
ARMConstantPoolConstant * ARMConstantPoolConstant::Create (const GlobalValue * GV, ARMCP::ARMCPModifier Modifier) static
Definition at line 133 of file ARMConstantPoolValue.cpp.
References llvm::ARMCP::CPValue, llvm::Value::getContext(), and llvm::Type::getInt32Ty().
ARMConstantPoolConstant * ARMConstantPoolConstant::Create (const Constant * C, unsigned ID, ARMCP::ARMCPKind Kind, unsigned char PCAdj) static
Definition at line 141 of file ARMConstantPoolValue.cpp.
References llvm::ARMCP::no_modifier.
ARMConstantPoolConstant * ARMConstantPoolConstant::Create (const Constant * C, unsigned ID, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress) static
Definition at line 148 of file ARMConstantPoolValue.cpp.
bool llvm::ARMConstantPoolConstant::equals (const ARMConstantPoolConstant * A) const inline
Definition at line 181 of file ARMConstantPoolValue.h.
References llvm::ARMConstantPoolValue::equals().
const BlockAddress * ARMConstantPoolConstant::getBlockAddress () const
Definition at line 160 of file ARMConstantPoolValue.cpp.
int ARMConstantPoolConstant::getExistingMachineCPValue (MachineConstantPool * CP, unsigned Alignment) virtual
Reimplemented from llvm::ARMConstantPoolValue.
Definition at line 164 of file ARMConstantPoolValue.cpp.
const GlobalValue * ARMConstantPoolConstant::getGV () const
Definition at line 156 of file ARMConstantPoolValue.cpp.
bool ARMConstantPoolConstant::hasSameValue (ARMConstantPoolValue * ACPV) virtual
hasSameValue - Return true if this ARM constpool value can share the same constantpool entry as another ARM constpool value.
Reimplemented from llvm::ARMConstantPoolValue.
Definition at line 169 of file ARMConstantPoolValue.cpp.
References llvm::dyn_cast(), and llvm::ARMConstantPoolValue::hasSameValue().
void ARMConstantPoolConstant::print (raw_ostream & O) const virtual
print - Implement operator<<
Reimplemented from llvm::ARMConstantPoolValue.
Definition at line 179 of file ARMConstantPoolValue.cpp.
References llvm::ARMConstantPoolValue::ARMConstantPoolValue(), llvm::ARMCP::CPExtSymbol, llvm::ARMConstantPoolValue::print(), S, and s.
The documentation for this class was generated from the following files:
ARMConstantPoolValue.h
ARMConstantPoolValue.cpp