LLVM: llvm::ConstantSDNode Class Reference
LLVM API Documentation
llvm::ConstantSDNode Class Reference
#include <SelectionDAGNodes.h>
Public Member Functions
const ConstantInt * getConstantIntValue () const
const APInt & getAPIntValue () const
uint64_t getZExtValue () const
int64_t getSExtValue () const
bool isOne () const
bool isNullValue () const
bool isAllOnesValue () const
Public Member Functions inherited from llvm::SDNode
unsigned getOpcode () const
bool isTargetOpcode () const
bool isTargetMemoryOpcode () const
bool isMachineOpcode () const
unsigned getMachineOpcode () const
bool getHasDebugValue () const
getHasDebugValue - get this bit.
void setHasDebugValue (bool b)
setHasDebugValue - set this bit.
bool use_empty () const
bool hasOneUse () const
size_t use_size () const
int getNodeId () const
void setNodeId (int Id)
setNodeId - Set unique node id.
unsigned getIROrder () const
void setIROrder (unsigned Order)
const DebugLoc getDebugLoc () const
getDebugLoc - Return the source location info.
void setDebugLoc (const DebugLoc dl)
use_iterator use_begin () const
bool hasNUsesOfValue (unsigned NUses, unsigned Value) const
bool hasAnyUseOfValue (unsigned Value) const
bool isOnlyUserOf (SDNode *N) const
bool isOperandOf (SDNode *N) const
bool isPredecessorOf (const SDNode *N) const
bool hasPredecessor (const SDNode *N) const
bool hasPredecessorHelper (const SDNode *N, SmallPtrSet< const SDNode *, 32 > &Visited, SmallVectorImpl< const SDNode * > &Worklist) const
unsigned getNumOperands () const
uint64_t getConstantOperandVal (unsigned Num) const
const SDValue & getOperand (unsigned Num) const
op_iterator op_begin () const
op_iterator op_end () const
SDVTList getVTList () const
SDNode * getGluedNode () const
const SDNode * getGluedMachineNode () const
SDNode * getGluedUser () const
unsigned getNumValues () const
EVT getValueType (unsigned ResNo) const
MVT getSimpleValueType (unsigned ResNo) const
unsigned getValueSizeInBits (unsigned ResNo) const
value_iterator value_begin () const
value_iterator value_end () const
std::string getOperationName (const SelectionDAG *G=0) const
void print_types (raw_ostream &OS, const SelectionDAG *G) const
void print_details (raw_ostream &OS, const SelectionDAG *G) const
void print (raw_ostream &OS, const SelectionDAG *G=0) const
void printr (raw_ostream &OS, const SelectionDAG *G=0) const
void printrFull (raw_ostream &O, const SelectionDAG *G=0) const
void printrWithDepth (raw_ostream &O, const SelectionDAG *G=0, unsigned depth=100) const
void dump () const
dump - Dump this node, for debugging.
void dumpr () const
dumpr - Dump (recursively) this node and its use-def subgraph.
void dump (const SelectionDAG *G) const
void dumpr (const SelectionDAG *G) const
void dumprFull (const SelectionDAG *G=0) const
void dumprWithDepth (const SelectionDAG *G=0, unsigned depth=100) const
void Profile (FoldingSetNodeID &ID) const
void addUse (SDUse &U)
Public Member Functions inherited from llvm::FoldingSetImpl::Node
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Public Member Functions inherited from llvm::ilist_node< SDNode >
SDNode * getPrevNode ()
Get the previous node, or 0 for the list head.
const SDNode * getPrevNode () const
Get the previous node, or 0 for the list head.
SDNode * getNextNode ()
Get the next node, or 0 for the list tail.
const SDNode * getNextNode () const
Get the next node, or 0 for the list tail.
Static Public Member Functions
static bool classof (const SDNode *N)
Static Public Member Functions inherited from llvm::SDNode
static use_iterator use_end ()
static const char * getIndexedModeName (ISD::MemIndexedMode AM)
Friends
class SelectionDAG
Additional Inherited Members
Public Types inherited from llvm::SDNode
typedef SDUse * op_iterator
typedef const EVT * value_iterator
Protected Member Functions inherited from llvm::SDNode
SDNode (unsigned Opc, unsigned Order, const DebugLoc dl, SDVTList VTs, const SDValue *Ops, unsigned NumOps)
SDNode (unsigned Opc, unsigned Order, const DebugLoc dl, SDVTList VTs)
void InitOperands (SDUse *Ops, const SDValue &Op0)
InitOperands - Initialize the operands list of this with 1 operand.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1)
InitOperands - Initialize the operands list of this with 2 operands.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1, const SDValue &Op2)
InitOperands - Initialize the operands list of this with 3 operands.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1, const SDValue &Op2, const SDValue &Op3)
InitOperands - Initialize the operands list of this with 4 operands.
void InitOperands (SDUse *Ops, const SDValue *Vals, unsigned N)
InitOperands - Initialize the operands list of this with N operands.
void DropOperands ()
Protected Member Functions inherited from llvm::ilist_node< SDNode >
ilist_node ()
Static Protected Member Functions inherited from llvm::SDNode
static SDVTList getSDVTList (EVT VT)
Protected Attributes inherited from llvm::SDNode
uint16_t SubclassData: 14
Detailed Description
Definition at line 1246 of file SelectionDAGNodes.h.
Member Function Documentation
static bool llvm::ConstantSDNode::classof (const SDNode * N) inline static
Definition at line 1264 of file SelectionDAGNodes.h.
References llvm::ISD::Constant, llvm::SDNode::getOpcode(), and llvm::ISD::TargetConstant.
const APInt& llvm::ConstantSDNode::getAPIntValue () const inline
Definition at line 1256 of file SelectionDAGNodes.h.
References llvm::ConstantInt::getValue().
Referenced by llvm::TargetLowering::BuildExactSDIV(), llvm::SelectionDAGISel::CheckAndMask(), llvm::SelectionDAGISel::CheckOrMask(), combineShlAddConstant(), llvm::SelectionDAG::getNode(), isBSwapHWordElement(), isConstantSplatVector(), IsSingleInstrConstant(), isTruncateOf(), isTruncWithZeroHighBitsInput(), isXor1OfSetCC(), llvm::TargetLowering::LowerAsmOperandForConstraint(), MatchRotateHalf(), partitionShuffleOfConcats(), performANDCombine(), PerformORCombine(), PerformSHLCombine(), llvm::TargetLowering::TargetLoweringOpt::ShrinkDemandedConstant(), SkipExtensionForVMULL(), and tryFoldToZero().
const ConstantInt* llvm::ConstantSDNode::getConstantIntValue () const inline
Definition at line 1255 of file SelectionDAGNodes.h.
int64_t llvm::ConstantSDNode::getSExtValue () const inline
Definition at line 1258 of file SelectionDAGNodes.h.
References llvm::ConstantInt::getSExtValue().
Referenced by llvm::SITargetLowering::AdjustInstrPostInstrSelection(), adjustSubwordCmp(), adjustZeroCmp(), canFoldInAddressingMode(), CheckInteger(), createCMovFP(), llvm::createXCoreISelDag(), FoldMaskAndShiftToScale(), getFusedLdStOpcode(), Is_PostInc_S4_Offset(), isExtendedBUILD_VECTOR(), llvm::TargetLowering::isGAPlusOffset(), IsS11_0_Offset(), IsS11_1_Offset(), IsS11_2_Offset(), IsS11_3_Offset(), IsU6_0_Offset(), IsU6_1_Offset(), IsU6_2_Offset(), llvm::ARMTargetLowering::LowerAsmOperandForConstraint(), OffsetFitsS11(), PerformMULCombine(), performORCombine(), PerformOrCombine(), and shouldSwapCmpOperands().
uint64_t llvm::ConstantSDNode::getZExtValue () const inline
Definition at line 1257 of file SelectionDAGNodes.h.
References llvm::ConstantInt::getZExtValue().
Referenced by AddCombineToVPADDL(), adjustForTestUnderMask(), adjustSubwordCmp(), checkBoolTestSetCCCombine(), countOperands(), llvm::createAMDGPUISelDag(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::HexagonSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset(), FoldOperand(), getCodeAddrSpace(), getFusedLdStOpcode(), getGatherNode(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), llvm::SelectionDAG::getMemset(), getMGatherNode(), getMScatterNode(), llvm::SelectionDAG::getNode(), getScatterNode(), getVLDSTRegisterUpdateOpcode(), insertDAGNode(), isAllOnes(), isBLACompatibleAddress(), isBSwapHWordElement(), isConstantSplatVector(), isFloatingPointZero(), isScaledConstantInRange(), isSimpleShift(), isTruncateOf(), llvm::AArch64TargetLowering::LowerAsmOperandForConstraint(), llvm::PPCTargetLowering::LowerAsmOperandForConstraint(), llvm::TargetLowering::LowerAsmOperandForConstraint(), LowerATOMIC_FENCE(), LowerScalarImmediateShift(), LowerVectorIntExtend(), maskMatters(), MatchRotateHalf(), ConsecutiveMemoryChainSorter::operator()(), performANDCombine(), PerformAndCombine(), PerformBFICombine(), PerformMulCombine(), performORCombine(), PerformORCombine(), performSELECTCombine(), performSRACombine(), PerformZExtCombine(), shouldSwapCmpOperands(), and llvm::TargetLowering::SimplifyDemandedBits().
bool llvm::ConstantSDNode::isAllOnesValue () const inline
Definition at line 1262 of file SelectionDAGNodes.h.
References llvm::Constant::isAllOnesValue().
Referenced by isAllOnes(), isZeroOrAllOnes(), MatchRotateHalf(), partitionShuffleOfConcats(), llvm::SITargetLowering::PerformDAGCombine(), and tryFoldToZero().
bool llvm::ConstantSDNode::isNullValue () const inline
Definition at line 1261 of file SelectionDAGNodes.h.
References llvm::Constant::isNullValue().
Referenced by llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), llvm::SelectionDAG::getMemset(), isConstantSplatVector(), isScaledConstantInRange(), isTruncWithZeroHighBitsInput(), isZero(), isZeroOrAllOnes(), MatchRotateHalf(), partitionShuffleOfConcats(), and llvm::SITargetLowering::PerformDAGCombine().
bool llvm::ConstantSDNode::isOne () const inline
Definition at line 1260 of file SelectionDAGNodes.h.
References llvm::ConstantInt::isOne().
Referenced by combineShlAddConstant(), and partitionShuffleOfConcats().
Friends And Related Function Documentation
friend class SelectionDAG friend
Definition at line 1248 of file SelectionDAGNodes.h.
The documentation for this class was generated from the following file:
SelectionDAGNodes.h