LLVM: llvm::DWARFContextInMemory Class Reference
LLVM API Documentation
llvm::DWARFContextInMemory Class Reference
#include <DWARFContext.h>
Public Member Functions
DWARFContextInMemory (object::ObjectFile *)
~DWARFContextInMemory ()
virtual bool isLittleEndian () const
virtual uint8_t getAddressSize () const
virtual const Section & getInfoSection ()
virtual const std::map< object::SectionRef, Section > & getTypesSections ()
virtual StringRef getAbbrevSection ()
virtual const Section & getLocSection ()
virtual StringRef getARangeSection ()
virtual StringRef getDebugFrameSection ()
virtual const Section & getLineSection ()
virtual StringRef getStringSection ()
virtual StringRef getRangeSection ()
virtual StringRef getPubNamesSection ()
virtual StringRef getPubTypesSection ()
virtual StringRef getGnuPubNamesSection ()
virtual StringRef getGnuPubTypesSection ()
virtual const Section & getInfoDWOSection ()
virtual StringRef getAbbrevDWOSection ()
virtual StringRef getStringDWOSection ()
virtual StringRef getStringOffsetDWOSection ()
virtual StringRef getRangeDWOSection ()
virtual StringRef getAddrSection ()
Public Member Functions inherited from llvm::DWARFContext
DWARFContext ()
virtual ~DWARFContext ()
virtual void dump (raw_ostream &OS, DIDumpType DumpType=DIDT_All)
unsigned getNumCompileUnits ()
Get the number of compile units in this context.
unsigned getNumTypeUnits ()
Get the number of compile units in this context.
unsigned getNumDWOCompileUnits ()
Get the number of compile units in the DWO context.
DWARFCompileUnit * getCompileUnitAtIndex (unsigned index)
Get the compile unit at the specified index for this compile unit.
DWARFTypeUnit * getTypeUnitAtIndex (unsigned index)
Get the type unit at the specified index for this compile unit.
DWARFCompileUnit * getDWOCompileUnitAtIndex (unsigned index)
Get the compile unit at the specified index for the DWO compile units.
const DWARFDebugAbbrev * getDebugAbbrev ()
Get a pointer to the parsed DebugAbbrev object.
const DWARFDebugLoc * getDebugLoc ()
Get a pointer to the parsed DebugLoc object.
const DWARFDebugAbbrev * getDebugAbbrevDWO ()
Get a pointer to the parsed dwo abbreviations object.
const DWARFDebugAranges * getDebugAranges ()
Get a pointer to the parsed DebugAranges object.
const DWARFDebugFrame * getDebugFrame ()
Get a pointer to the parsed frame information object.
const DWARFDebugLine::LineTable * getLineTableForCompileUnit (DWARFCompileUnit *cu)
Get a pointer to a parsed line table corresponding to a compile unit.
virtual DILineInfo getLineInfoForAddress (uint64_t Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier())
virtual DILineInfoTable getLineInfoForAddressRange (uint64_t Address, uint64_t Size, DILineInfoSpecifier Specifier=DILineInfoSpecifier())
virtual DIInliningInfo getInliningInfoForAddress (uint64_t Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier())
Public Member Functions inherited from llvm::DIContext
DIContextKind getKind () const
DIContext (DIContextKind K)
virtual ~DIContext ()
Additional Inherited Members
Public Types inherited from llvm::DIContext
enum DIContextKind { CK_DWARF }
Static Public Member Functions inherited from llvm::DWARFContext
static bool classof (const DIContext *DICtx)
static bool isSupportedVersion (unsigned version)
Static Public Member Functions inherited from llvm::DIContext
static DIContext * getDWARFContext (object::ObjectFile *)
getDWARFContext - get a context for binary DWARF data.
Detailed Description
DWARFContextInMemory is the simplest possible implementation of a DWARFContext. It assumes all content is available in memory and stores pointers to it.
Definition at line 177 of file DWARFContext.h.
Constructor & Destructor Documentation
DWARFContextInMemory::DWARFContextInMemory (object::ObjectFile * Obj)
Definition at line 575 of file DWARFContext.cpp.
References llvm::object::ObjectFile::begin_sections(), llvm::StringSwitch< T, R >::Case(), consumeCompressedDebugSectionHeader(), llvm::DWARFContext::Section::Data, llvm::dbgs(), DEBUG, llvm::StringSwitch< T, R >::Default(), llvm::object::ObjectFile::end_sections(), llvm::errs(), llvm::StringRef::find_first_not_of(), llvm::format(), llvm::MemoryBuffer::getBuffer(), llvm::object::ObjectFile::getFileFormatName(), i, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::insert(), llvm::zlib::isAvailable(), llvm::object::Binary::isELF(), llvm::DWARFContext::Section::Relocs, llvm::COFF::SectionSize, llvm::StringRef::startswith(), llvm::zlib::StatusOK, llvm::StringRef::substr(), llvm::OwningPtr< T >::take(), Type, and llvm::zlib::uncompress().
DWARFContextInMemory::~DWARFContextInMemory ()
Definition at line 715 of file DWARFContext.cpp.
References llvm::DeleteContainerPointers().
Member Function Documentation
virtual StringRef llvm::DWARFContextInMemory::getAbbrevDWOSection () inline virtual
Implements llvm::DWARFContext.
Definition at line 228 of file DWARFContext.h.
virtual StringRef llvm::DWARFContextInMemory::getAbbrevSection () inline virtual
Implements llvm::DWARFContext.
Definition at line 214 of file DWARFContext.h.
virtual uint8_t llvm::DWARFContextInMemory::getAddressSize () const inline virtual
Implements llvm::DWARFContext.
Definition at line 209 of file DWARFContext.h.
virtual StringRef llvm::DWARFContextInMemory::getAddrSection () inline virtual
Implements llvm::DWARFContext.
Definition at line 234 of file DWARFContext.h.
virtual StringRef llvm::DWARFContextInMemory::getARangeSection () inline virtual
Implements llvm::DWARFContext.
Definition at line 216 of file DWARFContext.h.
virtual StringRef llvm::DWARFContextInMemory::getDebugFrameSection () inline virtual
Implements llvm::DWARFContext.
Definition at line 217 of file DWARFContext.h.
virtual StringRef llvm::DWARFContextInMemory::getGnuPubNamesSection () inline virtual
Implements llvm::DWARFContext.
Definition at line 223 of file DWARFContext.h.
virtual StringRef llvm::DWARFContextInMemory::getGnuPubTypesSection () inline virtual
Implements llvm::DWARFContext.
Definition at line 224 of file DWARFContext.h.
virtual const Section& llvm::DWARFContextInMemory::getInfoDWOSection () inline virtual
Implements llvm::DWARFContext.
Definition at line 227 of file DWARFContext.h.
virtual const Section& llvm::DWARFContextInMemory::getInfoSection () inline virtual
Implements llvm::DWARFContext.
Definition at line 210 of file DWARFContext.h.
virtual const Section& llvm::DWARFContextInMemory::getLineSection () inline virtual
Implements llvm::DWARFContext.
Definition at line 218 of file DWARFContext.h.
virtual const Section& llvm::DWARFContextInMemory::getLocSection () inline virtual
Implements llvm::DWARFContext.
Definition at line 215 of file DWARFContext.h.
virtual StringRef llvm::DWARFContextInMemory::getPubNamesSection () inline virtual
Implements llvm::DWARFContext.
Definition at line 221 of file DWARFContext.h.
virtual StringRef llvm::DWARFContextInMemory::getPubTypesSection () inline virtual
Implements llvm::DWARFContext.
Definition at line 222 of file DWARFContext.h.
virtual StringRef llvm::DWARFContextInMemory::getRangeDWOSection () inline virtual
Implements llvm::DWARFContext.
Definition at line 233 of file DWARFContext.h.
virtual StringRef llvm::DWARFContextInMemory::getRangeSection () inline virtual
Implements llvm::DWARFContext.
Definition at line 220 of file DWARFContext.h.
virtual StringRef llvm::DWARFContextInMemory::getStringDWOSection () inline virtual
Implements llvm::DWARFContext.
Definition at line 229 of file DWARFContext.h.
virtual StringRef llvm::DWARFContextInMemory::getStringOffsetDWOSection () inline virtual
Implements llvm::DWARFContext.
Definition at line 230 of file DWARFContext.h.
virtual StringRef llvm::DWARFContextInMemory::getStringSection () inline virtual
Implements llvm::DWARFContext.
Definition at line 219 of file DWARFContext.h.
virtual const std::map<object::SectionRef, Section>& llvm::DWARFContextInMemory::getTypesSections () inline virtual
Implements llvm::DWARFContext.
Definition at line 211 of file DWARFContext.h.
virtual bool llvm::DWARFContextInMemory::isLittleEndian () const inline virtual
Implements llvm::DWARFContext.
Definition at line 208 of file DWARFContext.h.
The documentation for this class was generated from the following files:
DWARFContext.h
DWARFContext.cpp