LLVM: llvm::JITMemoryManager Class Reference
LLVM API Documentation
llvm::JITMemoryManager Class Reference abstract
#include <JITMemoryManager.h>
Public Member Functions
JITMemoryManager ()
virtual ~JITMemoryManager ()
virtual void setMemoryWritable ()=0
virtual void setMemoryExecutable ()=0
virtual void setPoisonMemory (bool poison)=0
virtual void AllocateGOT ()=0
bool isManagingGOT () const
isManagingGOT - Return true if the AllocateGOT method is called.
virtual uint8_t * getGOTBase () const =0
virtual uint8_t * startFunctionBody (const Function *F, uintptr_t &ActualSize)=0
virtual uint8_t * allocateStub (const GlobalValue *F, unsigned StubSize, unsigned Alignment)=0
virtual void endFunctionBody (const Function *F, uint8_t *FunctionStart, uint8_t *FunctionEnd)=0
virtual uint8_t * allocateSpace (intptr_t Size, unsigned Alignment)=0
virtual uint8_t * allocateGlobal (uintptr_t Size, unsigned Alignment)=0
allocateGlobal - Allocate memory for a global.
virtual void deallocateFunctionBody (void *Body)=0
virtual bool CheckInvariants (std::string &)
virtual size_t GetDefaultCodeSlabSize ()
virtual size_t GetDefaultDataSlabSize ()
virtual size_t GetDefaultStubSlabSize ()
virtual unsigned GetNumCodeSlabs ()
virtual unsigned GetNumDataSlabs ()
virtual unsigned GetNumStubSlabs ()
Public Member Functions inherited from llvm::RTDyldMemoryManager
RTDyldMemoryManager ()
virtual ~RTDyldMemoryManager ()
virtual uint8_t * allocateCodeSection (uintptr_t Size, unsigned Alignment, unsigned SectionID, StringRef SectionName)=0
virtual uint8_t * allocateDataSection (uintptr_t Size, unsigned Alignment, unsigned SectionID, StringRef SectionName, bool IsReadOnly)=0
virtual void registerEHFrames (uint8_t *Addr, uint64_t LoadAddr, size_t Size)
virtual void deregisterEHFrames (uint8_t *Addr, uint64_t LoadAddr, size_t Size)
virtual uint64_t getSymbolAddress (const std::string &Name)
virtual void * getPointerToNamedFunction (const std::string &Name, bool AbortOnFailure=true)
virtual void notifyObjectLoaded (ExecutionEngine *EE, const ObjectImage *)
virtual bool finalizeMemory (std::string *ErrMsg=0)=0
Static Public Member Functions
static JITMemoryManager * CreateDefaultMemManager ()
Protected Attributes
bool HasGOT
Detailed Description
JITMemoryManager - This interface is used by the JIT to allocate and manage memory for the code generated by the JIT. This can be reimplemented by clients that have a strong desire to control how the layout of JIT'd memory works.
Definition at line 26 of file JITMemoryManager.h.
Constructor & Destructor Documentation
llvm::JITMemoryManager::JITMemoryManager () inline
Definition at line 31 of file JITMemoryManager.h.
References AllocateGOT(), CreateDefaultMemManager(), setMemoryExecutable(), setMemoryWritable(), setPoisonMemory(), and ~JITMemoryManager().
JITMemoryManager::~JITMemoryManager () virtual
Definition at line 45 of file JITMemoryManager.cpp.
References llvm::BumpPtrAllocator::Allocate(), llvm::RTDyldMemoryManager::allocateCodeSection(), llvm::RTDyldMemoryManager::allocateDataSection(), allocateGlobal(), AllocateGOT(), llvm::sys::Memory::AllocateRWX(), allocateSpace(), allocateStub(), B, llvm::sys::MemoryBlock::base(), CheckInvariants(), llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::dbgs(), deallocateFunctionBody(), DEBUG, endFunctionBody(), F(), llvm::RTDyldMemoryManager::finalizeMemory(), GetDefaultCodeSlabSize(), GetDefaultDataSlabSize(), GetDefaultStubSlabSize(), getGOTBase(), GetNumCodeSlabs(), GetNumDataSlabs(), llvm::BumpPtrAllocator::GetNumSlabs(), GetNumStubSlabs(), llvm::RTDyldMemoryManager::getPointerToNamedFunction(), HasGOT, i, I, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::Intrinsic::memset, llvm::MemSlab::NextPtr, llvm::sys::Memory::ReleaseRWX(), llvm::report_fatal_error(), result, llvm::RoundUpToAlignment(), llvm::sys::Memory::setExecutable(), setMemoryExecutable(), setMemoryWritable(), setPoisonMemory(), llvm::sys::Memory::setWritable(), llvm::sys::MemoryBlock::size(), llvm::MemSlab::Size, size, and startFunctionBody().
Referenced by JITMemoryManager().
Member Function Documentation
virtual uint8_t* llvm::JITMemoryManager::allocateGlobal (uintptr_t Size, unsigned Alignment) pure virtual
allocateGlobal - Allocate memory for a global.
Referenced by isManagingGOT(), and ~JITMemoryManager().
virtual void llvm::JITMemoryManager::AllocateGOT () pure virtual
AllocateGOT - If the current table requires a Global Offset Table, this method is invoked to allocate it. This method is required to set HasGOT to true.
Referenced by isNonGhostDeclaration(), JITMemoryManager(), and ~JITMemoryManager().
virtual uint8_t* llvm::JITMemoryManager::allocateSpace (intptr_t Size, unsigned Alignment) pure virtual
allocateSpace - Allocate a memory block of the given size. This method cannot be called between calls to startFunctionBody and endFunctionBody.
Referenced by isManagingGOT(), and ~JITMemoryManager().
virtual uint8_t* llvm::JITMemoryManager::allocateStub (const GlobalValue * F, unsigned StubSize, unsigned Alignment) pure virtual
allocateStub - This method is called by the JIT to allocate space for a function stub (used to handle limited branch displacements) while it is JIT compiling a function. For example, if foo calls bar, and if bar either needs to be lazily compiled or is a native function that exists too far away from the call site to work, this method will be used to make a thunk for it. The stub should be "close" to the current function body, but should not be included in the 'actualsize' returned by startFunctionBody.
Referenced by isManagingGOT(), and ~JITMemoryManager().
virtual bool llvm::JITMemoryManager::CheckInvariants (std::string &) inline virtual
CheckInvariants - For testing only. Return true if all internal invariants are preserved, or return false and set ErrorStr to a helpful error message.
Definition at line 121 of file JITMemoryManager.h.
Referenced by ~JITMemoryManager().
JITMemoryManager * JITMemoryManager::CreateDefaultMemManager () static
CreateDefaultMemManager - This is used to create the default JIT Memory Manager if the client does not provide one to the JIT.
Definition at line 901 of file JITMemoryManager.cpp.
Referenced by getPointerToNamedFunction(), isNonGhostDeclaration(), and JITMemoryManager().
virtual void llvm::JITMemoryManager::deallocateFunctionBody (void * Body) pure virtual
deallocateFunctionBody - Free the specified function body. The argument must be the return value from a call to startFunctionBody() that hasn't been deallocated yet. This is never called when the JIT is currently emitting a function.
Referenced by isManagingGOT(), and ~JITMemoryManager().
virtual void llvm::JITMemoryManager::endFunctionBody (const Function * F, uint8_t * FunctionStart, uint8_t * FunctionEnd) pure virtual
endFunctionBody - This method is called when the JIT is done codegen'ing the specified function. At this point we know the size of the JIT compiled function. This passes in FunctionStart (which was returned by the startFunctionBody method) and FunctionEnd which is a pointer to the actual end of the function. This method should mark the space allocated and remember where it is in case the client wants to deallocate it.
Referenced by isManagingGOT(), and ~JITMemoryManager().
virtual size_t llvm::JITMemoryManager::GetDefaultCodeSlabSize () inline virtual
GetDefaultCodeSlabSize - For testing only. Returns DefaultCodeSlabSize from DefaultJITMemoryManager.
Definition at line 127 of file JITMemoryManager.h.
Referenced by ~JITMemoryManager().
virtual size_t llvm::JITMemoryManager::GetDefaultDataSlabSize () inline virtual
GetDefaultDataSlabSize - For testing only. Returns DefaultCodeSlabSize from DefaultJITMemoryManager.
Definition at line 133 of file JITMemoryManager.h.
Referenced by ~JITMemoryManager().
virtual size_t llvm::JITMemoryManager::GetDefaultStubSlabSize () inline virtual
GetDefaultStubSlabSize - For testing only. Returns DefaultCodeSlabSize from DefaultJITMemoryManager.
Definition at line 139 of file JITMemoryManager.h.
Referenced by ~JITMemoryManager().
virtual uint8_t* llvm::JITMemoryManager::getGOTBase () const pure virtual
getGOTBase - If this is managing a Global Offset Table, this method should return a pointer to its base.
Referenced by isManagingGOT(), and ~JITMemoryManager().
virtual unsigned llvm::JITMemoryManager::GetNumCodeSlabs () inline virtual
GetNumCodeSlabs - For testing only. Returns the number of MemoryBlocks allocated for code.
Definition at line 145 of file JITMemoryManager.h.
Referenced by ~JITMemoryManager().
virtual unsigned llvm::JITMemoryManager::GetNumDataSlabs () inline virtual
GetNumDataSlabs - For testing only. Returns the number of MemoryBlocks allocated for data.
Definition at line 151 of file JITMemoryManager.h.
Referenced by ~JITMemoryManager().
virtual unsigned llvm::JITMemoryManager::GetNumStubSlabs () inline virtual
GetNumStubSlabs - For testing only. Returns the number of MemoryBlocks allocated for function stubs.
Definition at line 157 of file JITMemoryManager.h.
Referenced by ~JITMemoryManager().
bool llvm::JITMemoryManager::isManagingGOT () const inline
isManagingGOT - Return true if the AllocateGOT method is called.
Definition at line 61 of file JITMemoryManager.h.
References allocateGlobal(), allocateSpace(), allocateStub(), deallocateFunctionBody(), endFunctionBody(), F(), getGOTBase(), HasGOT, and startFunctionBody().
virtual void llvm::JITMemoryManager::setMemoryExecutable () pure virtual
setMemoryExecutable - When code generation is done and we're ready to start execution, the code pages may need permissions changed.
Referenced by JITMemoryManager(), and ~JITMemoryManager().
virtual void llvm::JITMemoryManager::setMemoryWritable () pure virtual
setMemoryWritable - When code generation is in progress, the code pages may need permissions changed.
Referenced by JITMemoryManager(), and ~JITMemoryManager().
virtual void llvm::JITMemoryManager::setPoisonMemory (bool poison) pure virtual
setPoisonMemory - Setting this flag to true makes the memory manager garbage values over freed memory. This is useful for testing and debugging, and may be turned on by default in debug mode.
Referenced by JITMemoryManager(), and ~JITMemoryManager().
virtual uint8_t* llvm::JITMemoryManager::startFunctionBody (const Function * F, uintptr_t & ActualSize) pure virtual
startFunctionBody - When we start JITing a function, the JIT calls this method to allocate a block of free RWX memory, which returns a pointer to it. If the JIT wants to request a block of memory of at least a certain size, it passes that value as ActualSize, and this method returns a block with at least that much space. If the JIT doesn't know ahead of time how much space it will need to emit the function, it passes 0 for the ActualSize. In either case, this method is required to pass back the size of the allocated block through ActualSize. The JIT will be careful to not write more than the returned ActualSize bytes of memory.
Referenced by isManagingGOT(), and ~JITMemoryManager().
Member Data Documentation
bool llvm::JITMemoryManager::HasGOT protected
Definition at line 28 of file JITMemoryManager.h.
Referenced by isManagingGOT(), and ~JITMemoryManager().
The documentation for this class was generated from the following files:
JITMemoryManager.h
JITMemoryManager.cpp