LLVM: llvm::MCInstrInfo Class Reference
LLVM API Documentation
llvm::MCInstrInfo Class Reference
#include <MCInstrInfo.h>
Public Member Functions
void InitMCInstrInfo (const MCInstrDesc *D, const unsigned *NI, const char *ND, unsigned NO)
unsigned getNumOpcodes () const
const MCInstrDesc & get (unsigned Opcode) const
const char * getName (unsigned Opcode) const
getName - Returns the name for the instructions with the given opcode.
Detailed Description
MCInstrInfo - Interface to description of machine instruction set
Definition at line 26 of file MCInstrInfo.h.
Member Function Documentation
const MCInstrDesc& llvm::MCInstrInfo::get (unsigned Opcode) const inline
get - Return the machine instruction descriptor that corresponds to the specified instruction opcode.
Definition at line 48 of file MCInstrInfo.h.
Referenced by llvm::MachineBasicBlock::addLiveIn(), canClobberPhysRegDefs(), canClobberReachingPhysRegUse(), checkAndUpdateEFLAGSKill(), CheckForPhysRegDependency(), llvm::ScheduleDAG::clearDAG(), clobbersAnyYmmReg(), combineRestoreADD(), combineRestoreOR(), combineRestoreSETHIi(), llvm::ScheduleDAGSDNodes::computeOperandLatency(), concatenateMemOperands(), countOperands(), createAArch64MCInstPrinter(), llvm::createAMDGPUISelDag(), createARMMCRelocationInfo(), llvm::createSparcDelaySlotFillerPass(), llvm::SplitEditor::dump(), dumpMachineInstrRangeWithSlotIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), llvm::AArch64TargetLowering::emitAtomicBinary(), llvm::PPCTargetLowering::EmitAtomicBinary(), llvm::AArch64TargetLowering::emitAtomicBinaryMinMax(), llvm::AArch64TargetLowering::emitAtomicCmpSwap(), llvm::InstrEmitter::EmitDbgValue(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::HexagonFrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::AArch64FrameLowering::emitFrameMemOps(), emitIncrement(), llvm::SparcTargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::MachineRegisterInfo::EmitLiveInCopies(), llvm::Thumb2RegisterInfo::emitLoadConstPool(), llvm::Thumb1RegisterInfo::emitLoadConstPool(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), EmitMonitor(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), EmitPCMPSTRI(), EmitPCMPSTRM(), emitPostLd(), emitPostSt(), llvm::HexagonFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::emitRegUpdate(), llvm::MSP430TargetLowering::EmitShiftInstr(), emitSPUpdate(), emitThumbConstant(), llvm::emitThumbRegPlusImmediate(), emitThumbRegPlusImmInReg(), EmitXBegin(), llvm::MCInstrAnalysis::evaluateBranch(), expandPseudoDIV(), llvm::FastISel::FastEmitInst_(), llvm::FastISel::FastEmitInst_extractsubreg(), llvm::FastISel::FastEmitInst_i(), llvm::FastISel::FastEmitInst_ii(), llvm::FastISel::FastEmitInst_r(), llvm::FastISel::FastEmitInst_rf(), llvm::FastISel::FastEmitInst_ri(), llvm::FastISel::FastEmitInst_rii(), llvm::FastISel::FastEmitInst_rr(), llvm::FastISel::FastEmitInst_rri(), llvm::FastISel::FastEmitInst_rrii(), llvm::FastISel::FastEmitInst_rrr(), llvm::finalizeBundle(), findInsertLocation(), foldPatchpoint(), FuseInst(), FuseTwoAddrInst(), getComparePred(), getCopyOrBitcastDefUseIdx(), GetCostForDef(), llvm::ARMFrameLowering::getFrameIndexOffset(), getItineraryLatency(), getLatency(), getPhysicalRegisterVT(), getPostIndexedLoadStoreOpcode(), getPseudoCMOVOpc(), getRealVLDOpcode(), llvm::FastISel::getRegForValue(), llvm::ARMTargetLowering::getSchedulingPreference(), getTruncatedArgReg(), llvm::ARMInstrInfo::getUnindexedOpcode(), HandleVRSaveUpdate(), llvm::ResourcePriorityQueue::initNumRegDefsLeft(), InsertLDR_STR(), InsertNewDef(), instIsBreakpoint(), llvm::MCInstrAnalysis::isBranch(), llvm::MCInstrAnalysis::isCall(), isCalleeLoad(), llvm::MCInstrAnalysis::isConditionalBranch(), isHardwareLoop(), llvm::MCInstrAnalysis::isIndirectBranch(), isLoadFromGOTOrConstantPool(), llvm::ResourcePriorityQueue::isResourceAvailable(), llvm::MCInstrAnalysis::isReturn(), isSourceDefinedByImplicitDef(), llvm::MCInstrAnalysis::isTerminator(), llvm::MCInstrAnalysis::isUnconditionalBranch(), llvm::FastISel::leaveLocalValueArea(), llvm::linkErlangGC(), loadFromStack(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), lowerVECTOR_SHUFFLE_VSHF(), llvm::PPCRegisterInfo::lowerVRSAVERestore(), llvm::PPCRegisterInfo::lowerVRSAVESpilling(), MakeM0Inst(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), Mips16WhichOp8uOr16simm(), operator<<(), llvm::PPCHazardRecognizer970::PPCHazardRecognizer970(), llvm::X86ATTInstPrinter::printInst(), llvm::X86IntelInstPrinter::printInst(), ProcessSourceNode(), regsAreCompatible(), RemoveUnusedGlue(), replaceFI(), llvm::ARMTargetLowering::ReplaceNodeResults(), llvm::ResourcePriorityQueue::reserveResources(), llvm::MSP430FrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZFrameLowering::restoreCalleeSavedRegisters(), llvm::X86FrameLowering::restoreCalleeSavedRegisters(), rewritesSort(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::Thumb1RegisterInfo::saveScavengerRegister(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::FunctionLoweringInfo::set(), llvm::XCoreFrameLowering::spillCalleeSavedRegisters(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::SystemZFrameLowering::spillCalleeSavedRegisters(), llvm::MSP430FrameLowering::spillCalleeSavedRegisters(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), storeToStack(), and llvm::ResourcePriorityQueue::SUSchedulingCost().
const char* llvm::MCInstrInfo::getName (unsigned Opcode) const inline
getName - Returns the name for the instructions with the given opcode.
Definition at line 54 of file MCInstrInfo.h.
Referenced by llvm::HexagonInstPrinter::getOpcodeName(), llvm::MCInstPrinter::getOpcodeName(), llvm::MachineInstr::print(), and x86DisassemblerGetInstrName().
unsigned llvm::MCInstrInfo::getNumOpcodes () const inline
Definition at line 43 of file MCInstrInfo.h.
void llvm::MCInstrInfo::InitMCInstrInfo (const MCInstrDesc * D, const unsigned * NI, const char * ND, unsigned NO) inline
InitMCInstrInfo - Initialize MCInstrInfo, called by TableGen auto-generated routines. DO NOT USE.
Definition at line 35 of file MCInstrInfo.h.
The documentation for this class was generated from the following file:
MCInstrInfo.h