LLVM: llvm::LinkingMemoryManager Class Reference
LLVM API Documentation
llvm::LinkingMemoryManager Class Reference
#include <MCJIT.h>
Public Member Functions
LinkingMemoryManager (MCJIT *Parent, RTDyldMemoryManager *MM)
virtual uint64_t getSymbolAddress (const std::string &Name)
virtual uint8_t * allocateCodeSection (uintptr_t Size, unsigned Alignment, unsigned SectionID, StringRef SectionName)
virtual uint8_t * allocateDataSection (uintptr_t Size, unsigned Alignment, unsigned SectionID, StringRef SectionName, bool IsReadOnly)
virtual void notifyObjectLoaded (ExecutionEngine *EE, const ObjectImage *Obj)
virtual void registerEHFrames (uint8_t *Addr, uint64_t LoadAddr, size_t Size)
virtual void deregisterEHFrames (uint8_t *Addr, uint64_t LoadAddr, size_t Size)
virtual bool finalizeMemory (std::string *ErrMsg=0)
Public Member Functions inherited from llvm::RTDyldMemoryManager
RTDyldMemoryManager ()
virtual ~RTDyldMemoryManager ()
virtual void * getPointerToNamedFunction (const std::string &Name, bool AbortOnFailure=true)
Detailed Description
Definition at line 29 of file lib/ExecutionEngine/MCJIT/MCJIT.h.
Constructor & Destructor Documentation
llvm::LinkingMemoryManager::LinkingMemoryManager (MCJIT * Parent, RTDyldMemoryManager * MM) inline
Definition at line 31 of file lib/ExecutionEngine/MCJIT/MCJIT.h.
References getSymbolAddress().
Member Function Documentation
virtual uint8_t* llvm::LinkingMemoryManager::allocateCodeSection (uintptr_t Size, unsigned Alignment, unsigned SectionID, StringRef SectionName) inline virtual
Allocate a memory block of (at least) the given size suitable for executable code. The SectionID is a unique identifier assigned by the JIT engine, and optionally recorded by the memory manager to access a loaded section.
Implements llvm::RTDyldMemoryManager.
Definition at line 37 of file lib/ExecutionEngine/MCJIT/MCJIT.h.
virtual uint8_t* llvm::LinkingMemoryManager::allocateDataSection (uintptr_t Size, unsigned Alignment, unsigned SectionID, StringRef SectionName, bool IsReadOnly) inline virtual
Allocate a memory block of (at least) the given size suitable for data. The SectionID is a unique identifier assigned by the JIT engine, and optionally recorded by the memory manager to access a loaded section.
Implements llvm::RTDyldMemoryManager.
Definition at line 42 of file lib/ExecutionEngine/MCJIT/MCJIT.h.
virtual void llvm::LinkingMemoryManager::deregisterEHFrames (uint8_t * Addr, uint64_t LoadAddr, size_t Size) inline virtual
Reimplemented from llvm::RTDyldMemoryManager.
Definition at line 58 of file lib/ExecutionEngine/MCJIT/MCJIT.h.
virtual bool llvm::LinkingMemoryManager::finalizeMemory (std::string * ErrMsg = 0) inline virtual
This method is called when object loading is complete and section page permissions can be applied. It is up to the memory manager implementation to decide whether or not to act on this method. The memory manager will typically allocate all sections as read-write and then apply specific permissions when this method is called. Code sections cannot be executed until this function has been called. In addition, any cache coherency operations needed to reliably use the memory are also performed.
Returns true if an error occurred, false otherwise.
Implements llvm::RTDyldMemoryManager.
Definition at line 64 of file lib/ExecutionEngine/MCJIT/MCJIT.h.
uint64_t LinkingMemoryManager::getSymbolAddress (const std::string & Name) virtual
This method returns the address of the specified function or variable. It is used to resolve symbols during module linking.
Reimplemented from llvm::RTDyldMemoryManager.
Definition at line 532 of file MCJIT.cpp.
Referenced by LinkingMemoryManager(), and llvm::MCJIT::Register().
virtual void llvm::LinkingMemoryManager::notifyObjectLoaded (ExecutionEngine * EE, const ObjectImage *) inline virtual
This method is called after an object has been loaded into memory but before relocations are applied to the loaded sections. The object load may have been initiated by MCJIT to resolve an external symbol for another object that is being finalized. In that case, the object about which the memory manager is being notified will be finalized immediately after the memory manager returns from this call.
Memory managers which are preparing code for execution in an external address space can use this call to remap the section addresses for the newly loaded object.
Reimplemented from llvm::RTDyldMemoryManager.
Definition at line 49 of file lib/ExecutionEngine/MCJIT/MCJIT.h.
virtual void llvm::LinkingMemoryManager::registerEHFrames (uint8_t * Addr, uint64_t LoadAddr, size_t Size) inline virtual
Register the EH frames with the runtime so that c++ exceptions work.
Addr parameter provides the local address of the EH frame section data, while LoadAddr provides the address of the data in the target address space. If the section has not been remapped (which will usually be the case for local execution) these two values will be the same.
Reimplemented from llvm::RTDyldMemoryManager.
Definition at line 54 of file lib/ExecutionEngine/MCJIT/MCJIT.h.
The documentation for this class was generated from the following files:
lib/ExecutionEngine/MCJIT/MCJIT.h
MCJIT.cpp