LLVM: llvm::MCDwarfLineAddr Class Reference
LLVM API Documentation
llvm::MCDwarfLineAddr Class Reference
#include <MCDwarf.h>
Static Public Member Functions
static void Encode (MCContext &Context, int64_t LineDelta, uint64_t AddrDelta, raw_ostream &OS)
Utility function to encode a Dwarf pair of LineDelta and AddrDeltas.
static void Emit (MCStreamer *MCOS, int64_t LineDelta, uint64_t AddrDelta)
Utility function to emit the encoding to a streamer.
Detailed Description
Definition at line 229 of file MCDwarf.h.
Member Function Documentation
void MCDwarfLineAddr::Emit (MCStreamer * MCOS, int64_t LineDelta, uint64_t AddrDelta) static
Utility function to emit the encoding to a streamer.
Definition at line 355 of file MCDwarf.cpp.
References llvm::MCStreamer::EmitBytes(), Encode(), llvm::MCStreamer::getContext(), and llvm::raw_svector_ostream::str().
Referenced by llvm::MCDwarfFileTable::EmitCU(), llvm::MCObjectStreamer::EmitDwarfAdvanceLineAddr(), and llvm::MCStreamer::EmitDwarfSetLineAddr().
void MCDwarfLineAddr::Encode (MCContext & Context, int64_t LineDelta, uint64_t AddrDelta, raw_ostream & OS) static
Utility function to encode a Dwarf pair of LineDelta and AddrDeltas.
Definition at line 365 of file MCDwarf.cpp.
References llvm::dwarf::DW_LNE_end_sequence, llvm::dwarf::DW_LNS_advance_line, llvm::dwarf::DW_LNS_advance_pc, llvm::dwarf::DW_LNS_const_add_pc, llvm::dwarf::DW_LNS_copy, llvm::dwarf::DW_LNS_extended_op, DWARF2_LINE_BASE, DWARF2_LINE_OPCODE_BASE, DWARF2_LINE_RANGE, llvm::encodeSLEB128(), llvm::encodeULEB128(), MAX_SPECIAL_ADDR_DELTA, and ScaleAddrDelta().
Referenced by Emit(), and llvm::MCAssembler::Finish().
The documentation for this class was generated from the following files:
MCDwarf.h
MCDwarf.cpp