LLVM: llvm::Registry< T, U > Class Template Reference
LLVM API Documentation
llvm::Registry< T, U > Class Template Reference
#include <Registry.h>
Classes
class Add
class iterator
class listener
class node
Public Types
typedef U traits
typedef U::entry entry
Static Public Member Functions
static iterator begin ()
static iterator end ()
Friends
class node
class listener
Detailed Description
template<typename T, typename U = RegistryTraits<T>>
class llvm::Registry< T, U >
A global registry used in conjunction with static constructors to make pluggable components (like targets or garbage collectors) "just work" when linked with an executable.
Definition at line 58 of file Registry.h.
Member Typedef Documentation
template<typename T , typename U = RegistryTraits<T>> typedef U::entry llvm::Registry< T, U >::entry
Definition at line 61 of file Registry.h.
template<typename T , typename U = RegistryTraits<T>> typedef U llvm::Registry< T, U >::traits
Definition at line 60 of file Registry.h.
Member Function Documentation
template<typename T , typename U = RegistryTraits<T>> static iterator llvm::Registry< T, U >::begin () inline static
Definition at line 118 of file Registry.h.
Referenced by llvm::AsmPrinter::isBlockOnlyReachableByFallthrough(), and llvm::GCModuleInfo::~GCModuleInfo().
template<typename T , typename U = RegistryTraits<T>> static iterator llvm::Registry< T, U >::end () inline static
Definition at line 119 of file Registry.h.
Referenced by llvm::AsmPrinter::isBlockOnlyReachableByFallthrough(), and llvm::GCModuleInfo::~GCModuleInfo().
Friends And Related Function Documentation
template<typename T , typename U = RegistryTraits<T>> friend class listener friend
Definition at line 78 of file Registry.h.
template<typename T , typename U = RegistryTraits<T>> friend class node friend
Definition at line 75 of file Registry.h.
The documentation for this class was generated from the following file:
Registry.h