LLVM: llvm::MipsReginfo Class Reference
LLVM API Documentation
llvm::MipsReginfo Class Reference
#include <MipsReginfo.h>
Public Member Functions
MipsReginfo ()
void emitMipsReginfoSectionCG (MCStreamer &OS, const TargetLoweringObjectFile &TLOF, const MipsSubtarget &MST) const
Detailed Description
Definition at line 18 of file MipsReginfo.h.
Constructor & Destructor Documentation
llvm::MipsReginfo::MipsReginfo () inline
Definition at line 21 of file MipsReginfo.h.
References emitMipsReginfoSectionCG().
Member Function Documentation
void MipsReginfo::emitMipsReginfoSectionCG (MCStreamer & OS, const TargetLoweringObjectFile & TLOF, const MipsSubtarget & MST) const
Definition at line 43 of file MipsReginfo.cpp.
References llvm::MCStreamer::EmitIntValue(), llvm::MipsTargetObjectFile::getReginfoSection(), llvm::MCStreamer::hasRawTextSupport(), llvm::MipsSubtarget::isABI_N64(), llvm::MipsSubtarget::isABI_O32(), llvm_unreachable, and llvm::MCStreamer::SwitchSection().
Referenced by llvm::MipsAsmPrinter::EmitEndOfAsmFile(), and MipsReginfo().
The documentation for this class was generated from the following files:
MipsReginfo.h
MipsReginfo.cpp