LLVM: llvm::RegionNode Class Reference
LLVM API Documentation
llvm::RegionNode Class Reference
A RegionNode represents a subregion or a BasicBlock that is part of a Region.
#include <RegionInfo.h>
Public Member Functions
RegionNode (Region *Parent, BasicBlock *Entry, bool isSubRegion=0)
Create a RegionNode.
Region * getParent () const
Get the parent Region of this RegionNode.
BasicBlock * getEntry () const
Get the entry BasicBlock of this RegionNode.
template<class T >
T * getNodeAs () const
Get the content of this RegionNode.
bool isSubRegion () const
Is this RegionNode a subregion?
template<>
BasicBlock * getNodeAs () const
template<>
Region * getNodeAs () const
Protected Attributes
PointerIntPair< BasicBlock *, 1, bool > entry
Region * parent
The parent Region of this RegionNode.
Detailed Description
A RegionNode represents a subregion or a BasicBlock that is part of a Region.
Definition at line 56 of file RegionInfo.h.
Constructor & Destructor Documentation
llvm::RegionNode::RegionNode (Region * Parent, BasicBlock * Entry, bool isSubRegion = 0) inline
Create a RegionNode.
Parameters
Parent The parent of this RegionNode.
Entry The entry BasicBlock of the RegionNode. If this RegionNode represents a BasicBlock, this is the BasicBlock itself. If it represents a subregion, this is the entry BasicBlock of the subregion.
isSubRegion If this RegionNode represents a SubRegion.
Definition at line 86 of file RegionInfo.h.
Member Function Documentation
BasicBlock* llvm::RegionNode::getEntry () const inline
Get the entry BasicBlock of this RegionNode.
If this RegionNode represents a BasicBlock this is just the BasicBlock itself, otherwise we return the entry BasicBlock of the Subregion
Returns
The entry BasicBlock of this RegionNode.
Definition at line 105 of file RegionInfo.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer().
Referenced by llvm::Region::getEntry().
template<class T > T* llvm::RegionNode::getNodeAs () const inline
Get the content of this RegionNode.
This can be either a BasicBlock or a subregion. Before calling getNodeAs() check the type of the content with the isSubRegion() function call.
Returns
The content of this RegionNode.
Referenced by buildExtractionBlockSet(), llvm::DOTGraphTraits< RegionInfo * >::getEdgeAttributes(), llvm::DOTGraphTraits< RegionNode * >::getNodeLabel(), and llvm::operator<<().
template<> BasicBlock* llvm::RegionNode::getNodeAs () const inline
Definition at line 129 of file RegionInfo.h.
template<> Region* llvm::RegionNode::getNodeAs () const inline
Definition at line 135 of file RegionInfo.h.
Region* llvm::RegionNode::getParent () const inline
Get the parent Region of this RegionNode.
The parent Region is the Region this RegionNode belongs to. If for example a BasicBlock is element of two Regions, there exist two RegionNodes for this BasicBlock. Each with the getParent() function pointing to the Region this RegionNode belongs to.
Returns
Get the parent Region of this RegionNode.
Definition at line 97 of file RegionInfo.h.
Referenced by llvm::Region::getParent().
bool llvm::RegionNode::isSubRegion () const inline
Is this RegionNode a subregion?
Returns
True if it contains a subregion. False if it contains a BasicBlock.
Definition at line 120 of file RegionInfo.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getInt(), and llvm::operator<<().
Referenced by buildExtractionBlockSet(), llvm::DOTGraphTraits< RegionInfo * >::getEdgeAttributes(), llvm::DOTGraphTraits< RegionNode * >::getNodeLabel(), and llvm::operator<<().
Member Data Documentation
PointerIntPair<BasicBlock*, 1, bool> llvm::RegionNode::entry protected
This is the entry basic block that starts this region node. If this is a BasicBlock RegionNode, then entry is just the basic block, that this RegionNode represents. Otherwise it is the entry of this (Sub)RegionNode.
In the BBtoRegionNode map of the parent of this node, BB will always map to this node no matter which kind of node this one is.
The node can hold either a Region or a BasicBlock. Use one bit to save, if this RegionNode is a subregion or BasicBlock RegionNode.
Definition at line 71 of file RegionInfo.h.
Referenced by llvm::Region::clearNodeCache(), llvm::Region::contains(), llvm::Region::getEnteringBlock(), llvm::Region::getNameStr(), and llvm::Region::replaceEntry().
Region* llvm::RegionNode::parent protected
The parent Region of this RegionNode.
See also
getParent()
Definition at line 75 of file RegionInfo.h.
Referenced by llvm::Region::addSubRegion(), llvm::Region::clearNodeCache(), llvm::Region::getDepth(), and llvm::Region::removeSubRegion().
The documentation for this class was generated from the following file:
RegionInfo.h