LLVM: llvm::GCOVFile Class Reference
LLVM API Documentation
llvm::GCOVFile Class Reference
#include <GCOV.h>
Public Member Functions
GCOVFile ()
~GCOVFile ()
~GCOVFile - Delete GCOVFile and its content.
bool read (GCOVBuffer &Buffer)
read - Read GCOV buffer.
void dump ()
dump - Dump GCOVFile content to dbgs() for debugging purposes.
void collectLineCounts (FileInfo &FI)
Detailed Description
GCOVFile - Collects coverage information for one pair of coverage file (.gcno and .gcda).
Definition at line 194 of file GCOV.h.
Constructor & Destructor Documentation
llvm::GCOVFile::GCOVFile () inline
Definition at line 196 of file GCOV.h.
References llvm::dump(), and llvm::LibFunc::read.
GCOVFile::~GCOVFile ()
~GCOVFile - Delete GCOVFile and its content.
Definition at line 28 of file GCOV.cpp.
References llvm::DeleteContainerPointers().
Member Function Documentation
void GCOVFile::collectLineCounts (FileInfo & FI)
collectLineCounts - Collect line counts. This must be used after reading .gcno and .gcda files.
Definition at line 95 of file GCOV.cpp.
References I, llvm::FileInfo::setProgramCount(), and llvm::FileInfo::setRunCount().
void GCOVFile::dump ()
dump - Dump GCOVFile content to dbgs() for debugging purposes.
Definition at line 87 of file GCOV.cpp.
References I.
bool GCOVFile::read (GCOVBuffer & Buffer)
read - Read GCOV buffer.
Definition at line 43 of file GCOV.cpp.
References llvm::GCOVBuffer::advanceCursor(), llvm::NVPTXISD::Dummy, llvm::errs(), i, llvm::GCOV::InvalidGCOV, isGCDAFile(), isGCNOFile(), llvm::GCOVFunction::read(), llvm::GCOVBuffer::readFunctionTag(), llvm::GCOVBuffer::readGCOVFormat(), llvm::GCOVBuffer::readInt(), llvm::GCOVBuffer::readObjectTag(), and llvm::GCOVBuffer::readProgramTag().
The documentation for this class was generated from the following files:
GCOV.h
GCOV.cpp