LLVM: llvm::StackProtector Class Reference
LLVM API Documentation
llvm::StackProtector Class Reference
#include <StackProtector.h>
Public Types
enum SSPLayoutKind { SSPLK_None, SSPLK_LargeArray, SSPLK_SmallArray, SSPLK_AddrOf }
typedef ValueMap< const AllocaInst *, SSPLayoutKind > SSPLayoutMap
A mapping of AllocaInsts to their required SSP layout.
Public Member Functions
StackProtector ()
StackProtector (const TargetMachine *TM)
virtual void getAnalysisUsage (AnalysisUsage &AU) const
SSPLayoutKind getSSPLayout (const AllocaInst *AI) const
virtual bool runOnFunction (Function &Fn)
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const
createPrinterPass - Get a function printer pass.
virtual void assignPassManager (PMStack &PMS, PassManagerType T)
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
Definition at line 32 of file StackProtector.h.
Member Typedef Documentation
typedef ValueMap<const AllocaInst *, SSPLayoutKind> llvm::StackProtector::SSPLayoutMap
A mapping of AllocaInsts to their required SSP layout.
Definition at line 48 of file StackProtector.h.
Member Enumeration Documentation
enum llvm::StackProtector::SSPLayoutKind
SSPLayoutKind. Stack Smashing Protection (SSP) rules require that vulnerable stack allocations are located close the stack protector.
Enumerator
SSPLK_None
Did not trigger a stack protector. No effect on data layout.
SSPLK_LargeArray
Array or nested array >= SSP-buffer-size. Closest to the stack protector.
SSPLK_SmallArray
Array or nested array < SSP-buffer-size. 2nd closest to the stack protector.
SSPLK_AddrOf
The address of this allocation is exposed and triggered protection. 3rd closest to the protector.
Definition at line 36 of file StackProtector.h.
Constructor & Destructor Documentation
llvm::StackProtector::StackProtector () inline
Definition at line 108 of file StackProtector.h.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeStackProtectorPass().
llvm::StackProtector::StackProtector (const TargetMachine * TM) inline
Definition at line 111 of file StackProtector.h.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeStackProtectorPass().
Member Function Documentation
virtual void llvm::StackProtector::getAnalysisUsage (AnalysisUsage &) const inline virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job. If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 117 of file StackProtector.h.
References llvm::AnalysisUsage::addPreserved(), getSSPLayout(), and runOnFunction().
StackProtector::SSPLayoutKind StackProtector::getSSPLayout (const AllocaInst * AI) const
Definition at line 57 of file StackProtector.cpp.
References llvm::ValueMap< KeyT, ValueT, Config >::lookup(), and SSPLK_None.
Referenced by getAnalysisUsage().
bool StackProtector::runOnFunction (Function & F) virtual
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
Implements llvm::FunctionPass.
Definition at line 61 of file StackProtector.cpp.
References BB, llvm::BasicBlock::begin(), llvm::Function::begin(), llvm::dyn_cast(), llvm::StructType::element_begin(), llvm::StructType::element_end(), llvm::BasicBlock::end(), llvm::Function::end(), llvm::StringRef::getAsInteger(), llvm::AttributeSet::getAttribute(), llvm::Function::getAttributes(), llvm::User::getOperand(), llvm::GlobalValue::getParent(), llvm::TargetMachine::getTargetLowering(), llvm::Attribute::getValueAsString(), llvm::AttributeSet::hasAttribute(), I, llvm::ARM_PROC::IE, llvm::ValueMap< KeyT, ValueT, Config >::insert(), llvm::Triple::isOSDarwin(), llvm::Attribute::isStringAttribute(), SSPLK_AddrOf, SSPLK_LargeArray, SSPLK_SmallArray, llvm::A64DB::ST, llvm::Attribute::StackProtect, llvm::Attribute::StackProtectReq, llvm::Attribute::StackProtectStrong, llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by getAnalysisUsage().
Member Data Documentation
char StackProtector::ID = 0 static
Definition at line 107 of file StackProtector.h.
The documentation for this class was generated from the following files:
StackProtector.h
StackProtector.cpp