LLVM: llvm::FindUsedTypes Class Reference
LLVM API Documentation
llvm::FindUsedTypes Class Reference
#include <FindUsedTypes.h>
Public Member Functions
FindUsedTypes ()
const SetVector< Type * > & getTypes () const
void print (raw_ostream &o, const Module *M) const
bool runOnModule (Module &M)
run - This incorporates all types used by the specified module
virtual void getAnalysisUsage (AnalysisUsage &AU) const
getAnalysisUsage - We do not modify anything.
Public Member Functions inherited from llvm::ModulePass
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const
createPrinterPass - Get a module printer pass.
virtual void assignPassManager (PMStack &PMS, PassManagerType T)
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
ModulePass (char &pid)
virtual ~ModulePass ()
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
Definition at line 25 of file FindUsedTypes.h.
Constructor & Destructor Documentation
llvm::FindUsedTypes::FindUsedTypes () inline
Definition at line 29 of file FindUsedTypes.h.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeFindUsedTypesPass().
Member Function Documentation
virtual void llvm::FindUsedTypes::getAnalysisUsage (AnalysisUsage & AU) const inline virtual
getAnalysisUsage - We do not modify anything.
Reimplemented from llvm::Pass.
Definition at line 59 of file FindUsedTypes.h.
References llvm::AnalysisUsage::setPreservesAll().
const SetVector<Type *>& llvm::FindUsedTypes::getTypes () const inline
getTypes - After the pass has been run, return the set containing all of the types used in the module.
Definition at line 36 of file FindUsedTypes.h.
References M, print(), and runOnModule().
void FindUsedTypes::print (raw_ostream & o, const Module * M) const virtual
Print the types found in the module. If the optional Module parameter is passed in, then the types are printed symbolically if possible, using the symbol table from the module.
Reimplemented from llvm::Pass.
Definition at line 95 of file FindUsedTypes.cpp.
References I.
Referenced by getTypes().
bool FindUsedTypes::runOnModule (Module & M) virtual
run - This incorporates all types used by the specified module
Implements llvm::ModulePass.
Definition at line 59 of file FindUsedTypes.cpp.
References llvm::Module::begin(), llvm::Module::end(), F(), llvm::Value::getType(), llvm::Module::global_begin(), llvm::Module::global_end(), I, llvm::ARM_PROC::IE, llvm::inst_begin(), llvm::inst_end(), llvm::A64CC::MI, llvm::User::op_begin(), and llvm::User::op_end().
Referenced by getTypes().
Member Data Documentation
char FindUsedTypes::ID = 0 static
Definition at line 28 of file FindUsedTypes.h.
The documentation for this class was generated from the following files:
FindUsedTypes.h
FindUsedTypes.cpp