LLVM: llvm::ScheduleDAGSDNodes::RegDefIter Class Reference
LLVM API Documentation
llvm::ScheduleDAGSDNodes::RegDefIter Class Reference
#include <ScheduleDAGSDNodes.h>
Public Member Functions
RegDefIter (const SUnit *SU, const ScheduleDAGSDNodes *SD)
bool IsValid () const
MVT GetValue () const
const SDNode * GetNode () const
unsigned GetIdx () const
void Advance ()
Detailed Description
RegDefIter - In place iteration over the values defined by an SUnit. This does not need copies of the iterator or any other STLisms. The iterator creates itself, rather than being provided by the SchedDAG.
Definition at line 133 of file ScheduleDAGSDNodes.h.
Constructor & Destructor Documentation
ScheduleDAGSDNodes::RegDefIter::RegDefIter (const SUnit * SU, const ScheduleDAGSDNodes * SD)
Definition at line 552 of file ScheduleDAGSDNodes.cpp.
References Advance().
Member Function Documentation
void ScheduleDAGSDNodes::RegDefIter::Advance ()
Definition at line 560 of file ScheduleDAGSDNodes.cpp.
References llvm::SDNode::getGluedNode(), llvm::SDNode::getSimpleValueType(), and llvm::SDNode::hasAnyUseOfValue().
Referenced by GetIdx(), and RegDefIter().
unsigned llvm::ScheduleDAGSDNodes::RegDefIter::GetIdx () const inline
Definition at line 153 of file ScheduleDAGSDNodes.h.
References Advance().
Referenced by GetCostForDef().
const SDNode* llvm::ScheduleDAGSDNodes::RegDefIter::GetNode () const inline
Definition at line 149 of file ScheduleDAGSDNodes.h.
Referenced by GetCostForDef().
MVT llvm::ScheduleDAGSDNodes::RegDefIter::GetValue () const inline
Definition at line 144 of file ScheduleDAGSDNodes.h.
References IsValid().
Referenced by GetCostForDef().
bool llvm::ScheduleDAGSDNodes::RegDefIter::IsValid () const inline
Definition at line 142 of file ScheduleDAGSDNodes.h.
Referenced by CalcNodeSethiUllmanNumber(), and GetValue().
The documentation for this class was generated from the following files:
ScheduleDAGSDNodes.h
ScheduleDAGSDNodes.cpp