LLVM: llvm::TargetMachine Class Reference
LLVM API Documentation
llvm::TargetMachine Class Reference
#include <TargetMachine.h>
Public Types
enum CodeGenFileType { CGFT_AssemblyFile, CGFT_ObjectFile, CGFT_Null }
Public Member Functions
virtual ~TargetMachine ()
const Target & getTarget () const
const StringRef getTargetTriple () const
const StringRef getTargetCPU () const
const StringRef getTargetFeatureString () const
virtual const TargetSubtargetInfo * getSubtargetImpl () const
void resetTargetOptions (const MachineFunction *MF) const
Reset the target options based on the function's attributes.
virtual const TargetInstrInfo * getInstrInfo () const
virtual const TargetFrameLowering * getFrameLowering () const
virtual const TargetLowering * getTargetLowering () const
virtual const TargetSelectionDAGInfo * getSelectionDAGInfo () const
virtual const DataLayout * getDataLayout () const
const MCAsmInfo * getMCAsmInfo () const
template<typename STC >
const STC & getSubtarget () const
virtual const TargetRegisterInfo * getRegisterInfo () const
virtual const TargetIntrinsicInfo * getIntrinsicInfo () const
virtual TargetJITInfo * getJITInfo ()
virtual const InstrItineraryData * getInstrItineraryData () const
bool hasMCRelaxAll () const
void setMCRelaxAll (bool Value)
bool hasMCSaveTempLabels () const
void setMCSaveTempLabels (bool Value)
bool hasMCNoExecStack () const
hasMCNoExecStack - Check whether an executable stack is not needed.
void setMCNoExecStack (bool Value)
setMCNoExecStack - Set whether an executabel stack is not needed.
bool hasMCUseLoc () const
hasMCUseLoc - Check whether we should use dwarf's .loc directive.
void setMCUseLoc (bool Value)
setMCUseLoc - Set whether all we should use dwarf's .loc directive.
bool hasMCUseCFI () const
hasMCUseCFI - Check whether we should use dwarf's .cfi_* directives.
void setMCUseCFI (bool Value)
setMCUseCFI - Set whether all we should use dwarf's .cfi_* directives.
bool hasMCUseDwarfDirectory () const
void setMCUseDwarfDirectory (bool Value)
Reloc::Model getRelocationModel () const
CodeModel::Model getCodeModel () const
TLSModel::Model getTLSModel (const GlobalValue *GV) const
CodeGenOpt::Level getOptLevel () const
void setOptLevel (CodeGenOpt::Level Level) const
Overrides the optimization level.
void setFastISel (bool Enable)
bool shouldPrintMachineCode () const
virtual void addAnalysisPasses (PassManagerBase &)
Register analysis passes for this target with a pass manager.
virtual bool addPassesToEmitFile (PassManagerBase &, formatted_raw_ostream &, CodeGenFileType, bool=true, AnalysisID=0, AnalysisID=0)
virtual bool addPassesToEmitMachineCode (PassManagerBase &, JITCodeEmitter &, bool=true)
virtual bool addPassesToEmitMC (PassManagerBase &, MCContext *&, raw_ostream &, bool=true)
Static Public Member Functions
static bool getAsmVerbosityDefault ()
static void setAsmVerbosityDefault (bool)
static bool getDataSections ()
static bool getFunctionSections ()
static void setDataSections (bool)
setDataSections - Set if the data are emit into separate sections.
static void setFunctionSections (bool)
Public Attributes
TargetOptions Options
Protected Member Functions
TargetMachine (const Target &T, StringRef TargetTriple, StringRef CPU, StringRef FS, const TargetOptions &Options)
Protected Attributes
const Target & TheTarget
TheTarget - The Target that this machine was created for.
std::string TargetTriple
std::string TargetCPU
std::string TargetFS
MCCodeGenInfo * CodeGenInfo
const MCAsmInfo * AsmInfo
unsigned MCRelaxAll: 1
unsigned MCNoExecStack: 1
unsigned MCSaveTempLabels: 1
unsigned MCUseLoc: 1
unsigned MCUseCFI: 1
unsigned MCUseDwarfDirectory: 1
Detailed Description
TargetMachine - Primary interface to the complete machine description for the target machine. All target-specific information should be accessible through this interface.
Definition at line 61 of file Target/TargetMachine.h.
Member Enumeration Documentation
enum llvm::TargetMachine::CodeGenFileType
CodeGenFileType - These enums are meant to be passed into addPassesToEmitFile to indicate what type of file to emit, and returned by it to indicate what type of file could actually be made.
Enumerator
CGFT_AssemblyFile
CGFT_ObjectFile
CGFT_Null
Definition at line 253 of file Target/TargetMachine.h.
Constructor & Destructor Documentation
TargetMachine::TargetMachine (const Target & T, StringRef TargetTriple, StringRef CPU, StringRef FS, const TargetOptions & Options) protected
Definition at line 47 of file TargetMachine.cpp.
TargetMachine::~TargetMachine () virtual
Definition at line 61 of file TargetMachine.cpp.
References AsmInfo, and CodeGenInfo.
Member Function Documentation
virtual void llvm::TargetMachine::addAnalysisPasses (PassManagerBase &) inline virtual
Register analysis passes for this target with a pass manager.
Reimplemented in llvm::LLVMTargetMachine, llvm::PPCTargetMachine, llvm::X86TargetMachine, llvm::AMDGPUTargetMachine, llvm::XCoreTargetMachine, llvm::MipsTargetMachine, and llvm::ARMBaseTargetMachine.
Definition at line 248 of file Target/TargetMachine.h.
Referenced by accumulateAndSortLibcalls().
virtual bool llvm::TargetMachine::addPassesToEmitFile (PassManagerBase & , formatted_raw_ostream & , CodeGenFileType , bool = true, AnalysisID = 0, AnalysisID = 0) inline virtual
addPassesToEmitFile - Add passes to the specified pass manager to get the specified file emitted. Typically this will involve several steps of code generation. This method should return true if emission of this file type is not supported, or false on success.
Reimplemented in llvm::LLVMTargetMachine, and llvm::CPPTargetMachine.
Definition at line 263 of file Target/TargetMachine.h.
Referenced by accumulateAndSortLibcalls(), and LLVMTargetMachineEmit().
virtual bool llvm::TargetMachine::addPassesToEmitMachineCode (PassManagerBase & , JITCodeEmitter & , bool = true) inline virtual
addPassesToEmitMachineCode - Add passes to the specified pass manager to get machine code emitted. This uses a JITCodeEmitter object to handle actually outputting the machine code and resolving things like the address of functions. This method returns true if machine code emission is not supported.
Reimplemented in llvm::LLVMTargetMachine, and llvm::NVPTXTargetMachine.
Definition at line 278 of file Target/TargetMachine.h.
virtual bool llvm::TargetMachine::addPassesToEmitMC (PassManagerBase & , MCContext *& , raw_ostream & , bool = true) inline virtual
addPassesToEmitMC - Add passes to the specified pass manager to get machine code emitted with the MCJIT. This method returns true if machine code is not supported. It fills the MCContext Ctx pointer which can be used to build custom MCStreamer.
Reimplemented in llvm::LLVMTargetMachine, and llvm::NVPTXTargetMachine.
Definition at line 289 of file Target/TargetMachine.h.
bool TargetMachine::getAsmVerbosityDefault () static
getAsmVerbosityDefault - Returns the default value of asm verbosity.
Definition at line 172 of file TargetMachine.cpp.
References llvm::AsmVerbosityDefault().
Referenced by getVerboseAsm().
CodeModel::Model TargetMachine::getCodeModel () const
getCodeModel - Returns the code model. The choices are small, kernel, medium, large, and target default.
Definition at line 99 of file TargetMachine.cpp.
References CodeGenInfo, llvm::CodeModel::Default, and llvm::MCCodeGenInfo::getCodeModel().
Referenced by checkAndUpdateEFLAGSKill(), llvm::X86Subtarget::ClassifyGlobalReference(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::X86TargetLowering::getStackCookieLocation(), llvm::TargetLoweringObjectFile::Initialize(), llvm::X86TargetLowering::isLegalAddressingMode(), lowerGR128Binary(), LowerINSERT_SUBVECTOR(), and llvm::SparcTargetLowering::makeAddress().
virtual const DataLayout* llvm::TargetMachine::getDataLayout () const inline virtual
Reimplemented in llvm::ThumbTargetMachine, llvm::X86_64TargetMachine, llvm::ARMTargetMachine, llvm::X86_32TargetMachine, llvm::HexagonTargetMachine, llvm::MipsTargetMachine, llvm::AMDGPUTargetMachine, llvm::PPCTargetMachine, llvm::SparcTargetMachine, llvm::AArch64TargetMachine, llvm::NVPTXTargetMachine, llvm::XCoreTargetMachine, llvm::SystemZTargetMachine, llvm::MSP430TargetMachine, and llvm::CPPTargetMachine.
Definition at line 123 of file Target/TargetMachine.h.
Referenced by accumulateAndSortLibcalls(), countOperands(), llvm::createARMJITCodeEmitterPass(), llvm::createX86JITCodeEmitterPass(), llvm::AsmPrinter::EmitAlignment(), EmitCamlGlobal(), llvm::AsmPrinter::EmitConstantPool(), llvm::SystemZAsmPrinter::EmitEndOfAsmFile(), llvm::AArch64AsmPrinter::EmitEndOfAsmFile(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::AsmPrinter::EmitGlobalConstant(), emitGlobalConstantArray(), emitGlobalConstantDataSequential(), emitGlobalConstantFP(), emitGlobalConstantImpl(), emitGlobalConstantLargeInt(), emitGlobalConstantStruct(), emitGlobalConstantVector(), llvm::AsmPrinter::EmitGlobalVariable(), llvm::AsmPrinter::EmitJumpTableInfo(), llvm::SystemZAsmPrinter::EmitMachineConstantPoolValue(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), llvm::TargetLoweringObjectFileELF::emitPersonalityValue(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), llvm::ARMAsmPrinter::EmitXXStructor(), llvm::AsmPrinter::getDataLayout(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::Mangler::getNameWithPrefix(), llvm::AsmPrinter::GetSizeOfEncodedValue(), llvm::TargetInstrInfo::getStackSlotRange(), llvm::SelectionDAGBuilder::init(), InsertLDR_STR(), llvm::HexagonTargetObjectFile::IsGlobalInSmallSection(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), isRepeatedByteSequence(), llvm::linkErlangGCPrinter(), LLVMTargetMachineEmit(), nvptx::LowerConstant(), lowerConstant(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), parseMemoryOperand(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
bool TargetMachine::getDataSections () static
getDataSections - Return true if data objects should be emitted into their own section, corresponds to -fdata-sections.
Definition at line 184 of file TargetMachine.cpp.
References DataSections.
Referenced by llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal().
virtual const TargetFrameLowering* llvm::TargetMachine::getFrameLowering () const inline virtual
Reimplemented in llvm::ThumbTargetMachine, llvm::ARMTargetMachine, llvm::HexagonTargetMachine, llvm::MipsTargetMachine, llvm::NVPTXTargetMachine, llvm::PPCTargetMachine, llvm::X86TargetMachine, llvm::MSP430TargetMachine, llvm::AArch64TargetMachine, llvm::SystemZTargetMachine, llvm::SparcTargetMachine, llvm::AMDGPUTargetMachine, and llvm::XCoreTargetMachine.
Definition at line 120 of file Target/TargetMachine.h.
Referenced by AdjustStackOffset(), CalculateStackSlotSize(), llvm::ARMBaseRegisterInfo::canRealignStack(), checkNumAlignedDPRCS2Regs(), ConstantAddressBlock(), llvm::CompileUnit::constructVariableDIE(), llvm::createNVPTXPrologEpilogPass(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::Thumb1RegisterInfo::eliminateFrameIndex(), llvm::X86RegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), emitDebugValueComment(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), EmitTailCallStoreRetAddr(), llvm::MachineFrameInfo::estimateStackSize(), ExpandUnalignedLoad(), FuncIsMadeTailCallSafe(), llvm::MSP430RegisterInfo::getCalleeSavedRegs(), GetDSubRegs(), llvm::AArch64RegisterInfo::getFrameRegister(), llvm::MSP430RegisterInfo::getFrameRegister(), llvm::XCoreRegisterInfo::getFrameRegister(), llvm::SystemZRegisterInfo::getFrameRegister(), llvm::MipsRegisterInfo::getFrameRegister(), llvm::HexagonRegisterInfo::getFrameRegister(), llvm::PPCRegisterInfo::getFrameRegister(), llvm::X86RegisterInfo::getFrameRegister(), llvm::ARMBaseRegisterInfo::getFrameRegister(), llvm::AMDGPUInstrInfo::getIndirectIndexEnd(), llvm::MipsTargetLowering::getOpndList(), llvm::PPCRegisterInfo::getRegPressureLimit(), llvm::MipsRegisterInfo::getRegPressureLimit(), llvm::X86RegisterInfo::getRegPressureLimit(), llvm::ARMBaseRegisterInfo::getRegPressureLimit(), llvm::AArch64RegisterInfo::getReservedRegs(), llvm::MSP430RegisterInfo::getReservedRegs(), llvm::XCoreRegisterInfo::getReservedRegs(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::MipsRegisterInfo::getReservedRegs(), llvm::SystemZRegisterInfo::getReservedRegs(), llvm::X86RegisterInfo::getReservedRegs(), llvm::ARMBaseRegisterInfo::getReservedRegs(), llvm::ARMBaseRegisterInfo::hasBasePointer(), llvm::X86RegisterInfo::hasReservedSpillSlot(), INITIALIZE_PASS(), llvm::Mips16RegisterInfo::intRegClass(), lookupCandidateBaseReg(), LowerADJUST_TRAMPOLINE(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), LowerVASTART(), llvm::PPCRegisterInfo::needsFrameBaseReg(), llvm::ARMBaseRegisterInfo::needsFrameBaseReg(), llvm::PPCRegisterInfo::needsStackRealignment(), llvm::ARMBaseRegisterInfo::needsStackRealignment(), llvm::MachineFrameInfo::print(), llvm::X86FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::R600TargetLowering::ReplaceNodeResults(), llvm::XCoreRegisterInfo::requiresRegisterScavenging(), llvm::R600InstrInfo::reserveIndirectRegisters(), llvm::PEI::runOnMachineFunction(), and llvm::AArch64RegisterInfo::useFPForScavengingIndex().
bool TargetMachine::getFunctionSections () static
getFunctionSections - Return true if functions should be emitted into their own section, corresponding to -ffunction-sections.
Definition at line 180 of file TargetMachine.cpp.
References FunctionSections.
Referenced by llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal().
virtual const TargetInstrInfo* llvm::TargetMachine::getInstrInfo () const inline virtual
Reimplemented in llvm::ThumbTargetMachine, llvm::X86_64TargetMachine, llvm::X86_32TargetMachine, llvm::ARMTargetMachine, llvm::MipsTargetMachine, llvm::NVPTXTargetMachine, llvm::MSP430TargetMachine, llvm::AMDGPUTargetMachine, llvm::SystemZTargetMachine, llvm::PPCTargetMachine, llvm::HexagonTargetMachine, llvm::X86TargetMachine, llvm::SparcTargetMachine, llvm::AArch64TargetMachine, and llvm::XCoreTargetMachine.
Definition at line 119 of file Target/TargetMachine.h.
Referenced by addLiveInRegs(), llvm::LLVMTargetMachine::addPassesToEmitFile(), llvm::LLVMTargetMachine::addPassesToEmitMC(), adjCycles(), llvm::SITargetLowering::AdjustInstrPostInstrSelection(), llvm::ARMTargetLowering::AdjustInstrPostInstrSelection(), AdjustStackOffset(), llvm::SITargetLowering::analyzeImmediate(), llvm::VirtRegAuxInfo::calculateSpillWeightAndHint(), checkAndUpdateEFLAGSKill(), clobbersAnyYmmReg(), combineRestoreSETHIi(), llvm::createAMDGPUISelDag(), llvm::createARMJITCodeEmitterPass(), llvm::createBURRListDAGScheduler(), llvm::createHybridListDAGScheduler(), llvm::createILPListDAGScheduler(), llvm::createMipsDelaySlotFillerPass(), llvm::createMSP430BranchSelectionPass(), llvm::createR600ExpandSpecialInstrsPass(), llvm::createSILowerControlFlowPass(), llvm::createSourceListDAGScheduler(), llvm::createSparcDelaySlotFillerPass(), llvm::createSystemZLongBranchPass(), llvm::createSystemZShortenInstPass(), llvm::ScheduleDAGMI::dumpSchedule(), llvm::Mips16FrameLowering::eliminateCallFramePseudoInstr(), llvm::MipsSEFrameLowering::eliminateCallFramePseudoInstr(), llvm::MSP430FrameLowering::eliminateCallFramePseudoInstr(), llvm::XCoreFrameLowering::eliminateCallFramePseudoInstr(), llvm::Thumb1FrameLowering::eliminateCallFramePseudoInstr(), llvm::PPCFrameLowering::eliminateCallFramePseudoInstr(), llvm::AArch64FrameLowering::eliminateCallFramePseudoInstr(), llvm::AArch64RegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::Thumb1RegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::ARMBaseRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), llvm::AArch64TargetLowering::emitAtomicBinary(), llvm::PPCTargetLowering::EmitAtomicBinary(), llvm::AArch64TargetLowering::emitAtomicBinaryMinMax(), llvm::AArch64TargetLowering::emitAtomicCmpSwap(), emitComments(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::Mips16FrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::HexagonFrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::SystemZFrameLowering::emitEpilogue(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::AArch64FrameLowering::emitFrameMemOps(), llvm::AsmPrinter::EmitFunctionBody(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::SparcTargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::Thumb2RegisterInfo::emitLoadConstPool(), llvm::Thumb1RegisterInfo::emitLoadConstPool(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), EmitMonitor(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), emitPostSt(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::HexagonFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::MSP430TargetLowering::EmitShiftInstr(), llvm::RegScavenger::enterBasicBlock(), llvm::finalizeBundle(), llvm::TargetInstrInfo::foldMemoryOperand(), FoldOperand(), getBlockNum(), getCopyOrBitcastDefUseIdx(), GetDSubRegs(), getFPReg(), llvm::ARMFrameLowering::getFrameIndexOffset(), llvm::ARMHazardRecognizer::getHazardType(), llvm::MSP430InstrInfo::GetInstSizeInBytes(), getNewValueJumpOpcode(), llvm::SDNode::getOperationName(), getPseudoCMOVOpc(), llvm::ARMTargetLowering::getSchedulingPreference(), getTruncatedArgReg(), hasVGPROperands(), increaseCounters(), llvm::ConvergingVLIWScheduler::initialize(), INITIALIZE_PASS(), InsertLDR_STR(), llvm::Mips16RegisterInfo::intRegClass(), isCompareZero(), isCopy(), isFpMulInstruction(), isHardwareLoop(), isMSALoadOrStore(), isNodeChanged(), isNopCopy(), isSourceDefinedByImplicitDef(), isUnsafeToMoveAcross(), llvm::linkErlangGC(), LoopIsOuterMostWithPredecessor(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), llvm::R600TargetLowering::LowerOperation(), lowerVECTOR_SHUFFLE_VSHF(), llvm::PPCRegisterInfo::lowerVRSAVERestore(), llvm::PPCRegisterInfo::lowerVRSAVESpilling(), llvm::MachineSSAUpdater::MachineSSAUpdater(), MatchingStackOffset(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), llvm::ARMBaseRegisterInfo::materializeFrameBaseRegister(), Mips16WhichOp8uOr16simm(), false::IntervalSorter::operator()(), llvm::SITargetLowering::PostISelFolding(), llvm::PPCHazardRecognizer970::PPCHazardRecognizer970(), llvm::MachineInstr::print(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::MachineRegisterInfo::recomputeRegClass(), regsAreCompatible(), replaceFI(), llvm::ARMTargetLowering::ReplaceNodeResults(), llvm::Thumb1RegisterInfo::resolveFrameIndex(), llvm::ARMBaseRegisterInfo::resolveFrameIndex(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), llvm::XCoreFrameLowering::restoreCalleeSavedRegisters(), llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters(), llvm::HexagonFrameLowering::restoreCalleeSavedRegisters(), llvm::MSP430FrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZFrameLowering::restoreCalleeSavedRegisters(), llvm::X86FrameLowering::restoreCalleeSavedRegisters(), llvm::PPCFrameLowering::restoreCalleeSavedRegisters(), restoreCRs(), llvm::PEI::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::MachineTraceMetrics::runOnMachineFunction(), llvm::LiveIntervals::runOnMachineFunction(), llvm::Mips16RegisterInfo::saveScavengerRegister(), llvm::Thumb1RegisterInfo::saveScavengerRegister(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::FunctionLoweringInfo::set(), llvm::XCoreFrameLowering::spillCalleeSavedRegisters(), llvm::HexagonFrameLowering::spillCalleeSavedRegisters(), llvm::MipsSEFrameLowering::spillCalleeSavedRegisters(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::SystemZFrameLowering::spillCalleeSavedRegisters(), llvm::MSP430FrameLowering::spillCalleeSavedRegisters(), llvm::X86FrameLowering::spillCalleeSavedRegisters(), llvm::PPCFrameLowering::spillCalleeSavedRegisters(), llvm::MachineBasicBlock::SplitCriticalEdge(), UpdateCPSRUse(), llvm::MachineFunction::verify(), llvm::VLIWPacketizerList::VLIWPacketizerList(), llvm::VLIWResourceModel::VLIWResourceModel(), and llvm::Spiller::~Spiller().
virtual const InstrItineraryData* llvm::TargetMachine::getInstrItineraryData () const inline virtual
getInstrItineraryData - Returns instruction itinerary data for the target or specific subtarget.
Reimplemented in llvm::MipsTargetMachine, llvm::PPCTargetMachine, llvm::X86TargetMachine, llvm::AMDGPUTargetMachine, llvm::HexagonTargetMachine, and llvm::ARMBaseTargetMachine.
Definition at line 155 of file Target/TargetMachine.h.
Referenced by llvm::ARMTargetLowering::ARMTargetLowering(), llvm::ARMBaseInstrInfo::CreateTargetHazardRecognizer(), llvm::PPCInstrInfo::CreateTargetHazardRecognizer(), llvm::R600InstrInfo::CreateTargetScheduleState(), llvm::HexagonInstrInfo::CreateTargetScheduleState(), INITIALIZE_PASS(), LoopIsOuterMostWithPredecessor(), and regsAreCompatible().
virtual const TargetIntrinsicInfo* llvm::TargetMachine::getIntrinsicInfo () const inline virtual
getIntrinsicInfo - If intrinsic information is available, return it. If not, return null.
Reimplemented in llvm::AMDGPUTargetMachine.
Definition at line 145 of file Target/TargetMachine.h.
Referenced by llvm::SDNode::getOperationName(), and llvm::SelectionDAGISel::SelectCodeCommon().
virtual TargetJITInfo* llvm::TargetMachine::getJITInfo () inline virtual
getJITInfo - If this target supports a JIT, return information for it, otherwise return null.
Reimplemented in llvm::X86_64TargetMachine, llvm::X86_32TargetMachine, llvm::MipsTargetMachine, llvm::SparcTargetMachine, llvm::PPCTargetMachine, llvm::X86TargetMachine, and llvm::ARMBaseTargetMachine.
Definition at line 150 of file Target/TargetMachine.h.
Referenced by llvm::createARMJITCodeEmitterPass(), and llvm::JIT::createJIT().
const MCAsmInfo* llvm::TargetMachine::getMCAsmInfo () const inline
getMCAsmInfo - Return target specific asm information.
Definition at line 127 of file Target/TargetMachine.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile(), addPassesToGenerateCode(), llvm::TargetPassConfig::addPassesToHandleExceptions(), llvm::MSP430InstrInfo::GetInstSizeInBytes(), llvm::MipsInstrInfo::GetInstSizeInBytes(), llvm::AArch64InstrInfo::getInstSizeInBytes(), llvm::ARMBaseInstrInfo::GetInstSizeInBytes(), llvm::SystemZInstrInfo::getInstSizeInBytes(), llvm::PPCInstrInfo::GetInstSizeInBytes(), llvm::MachineFunction::getJTISymbol(), llvm::Mangler::getNameWithPrefix(), and matchPair().
CodeGenOpt::Level TargetMachine::getOptLevel () const
getOptLevel - Returns the optimization level: None, Less, Default, or Aggressive.
Definition at line 161 of file TargetMachine.cpp.
References CodeGenInfo, llvm::CodeGenOpt::Default, and llvm::MCCodeGenInfo::getOptLevel().
Referenced by addLiveInRegs(), llvm::HexagonTargetMachine::addPassesForOptimizations(), addPassesToGenerateCode(), llvm::XCoreTargetMachine::createPassConfig(), llvm::ARMBaseTargetMachine::createPassConfig(), llvm::AArch64TargetMachine::createPassConfig(), llvm::MSP430TargetMachine::createPassConfig(), llvm::PPCTargetMachine::createPassConfig(), llvm::X86TargetMachine::createPassConfig(), llvm::HexagonTargetMachine::createPassConfig(), llvm::NVPTXTargetMachine::createPassConfig(), llvm::HexagonFrameLowering::emitEpilogue(), llvm::TargetPassConfig::getOptLevel(), isUnsafeToMoveAcross(), OffsetFitsS11(), regsAreCompatible(), llvm::X86TargetLowering::resetOperationActions(), and llvm::SystemZTargetMachine::SystemZTargetMachine().
virtual const TargetRegisterInfo* llvm::TargetMachine::getRegisterInfo () const inline virtual
getRegisterInfo - If register information is available, return it. If not, return null. This is kept separate from RegInfo until RegInfo has details of graph coloring register allocation removed from it.
Reimplemented in llvm::ThumbTargetMachine, llvm::ARMTargetMachine, llvm::MipsTargetMachine, llvm::AArch64TargetMachine, llvm::NVPTXTargetMachine, llvm::X86TargetMachine, llvm::PPCTargetMachine, llvm::SystemZTargetMachine, llvm::MSP430TargetMachine, llvm::AMDGPUTargetMachine, llvm::XCoreTargetMachine, llvm::HexagonTargetMachine, and llvm::SparcTargetMachine.
Definition at line 140 of file Target/TargetMachine.h.
Referenced by addLiveInRegs(), llvm::LLVMTargetMachine::addPassesToEmitFile(), llvm::LLVMTargetMachine::addPassesToEmitMC(), addPassesToGenerateCode(), llvm::CompileUnit::addRegisterOffset(), llvm::CompileUnit::addRegisterOp(), adjCycles(), AdjustStackOffset(), llvm::SITargetLowering::analyzeImmediate(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::DwarfDebug::beginFunction(), llvm::PBQPBuilder::build(), llvm::PBQPBuilderWithCoalescing::build(), llvm::VirtRegAuxInfo::calculateSpillWeightAndHint(), canFoldInAddressingMode(), checkAndUpdateEFLAGSKill(), checkNumAlignedDPRCS2Regs(), llvm::TargetSchedModel::computeOutputLatency(), llvm::createAMDGPUISelDag(), llvm::createBURRListDAGScheduler(), llvm::createHybridListDAGScheduler(), llvm::createILPListDAGScheduler(), llvm::createNVPTXPrologEpilogPass(), llvm::createSILowerControlFlowPass(), llvm::createSourceListDAGScheduler(), llvm::createSparcDelaySlotFillerPass(), llvm::PPCFrameLowering::determineFrameLayout(), llvm::Thumb1FrameLowering::eliminateCallFramePseudoInstr(), emitDebugValueComment(), llvm::ARMAsmPrinter::EmitDwarfRegOp(), llvm::AsmPrinter::EmitDwarfRegOp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::MipsAsmPrinter::emitFrameDirective(), llvm::AsmPrinter::emitImplicitDef(), llvm::ARMAsmPrinter::EmitJump2Table(), emitKill(), llvm::AMDGPUAsmPrinter::EmitProgramInfoR600(), llvm::AMDGPUAsmPrinter::EmitProgramInfoSI(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::HexagonFrameLowering::emitPrologue(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), EmitTailCallStoreRetAddr(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::RegScavenger::enterBasicBlock(), llvm::MipsFrameLowering::estimateStackSize(), llvm::MachineFrameInfo::estimateStackSize(), llvm::finalizeBundle(), llvm::TargetLoweringBase::findRepresentativeClass(), llvm::TargetInstrInfo::foldMemoryOperand(), FPCCToARMCC(), getComparePred(), getCopyOrBitcastDefUseIdx(), GetDSubRegs(), llvm::X86FrameLowering::getFrameIndexOffset(), llvm::X86FrameLowering::getFrameIndexReference(), llvm::TargetFrameLowering::getFrameIndexReference(), getMemcpyLoadsAndStores(), getNewValueJumpOpcode(), getOpenCLAlignment(), llvm::MipsTargetLowering::getOpndList(), llvm::MachineFrameInfo::getPristineRegs(), getPseudoCMOVOpc(), llvm::PPCTargetLowering::getRegForInlineAsmConstraint(), llvm::TargetLowering::getRegForInlineAsmConstraint(), llvm::X86TargetLowering::getReturnAddressFrameIndex(), llvm::TargetInstrInfo::getStackSlotRange(), llvm::MachineRegisterInfo::getTargetRegisterInfo(), llvm::Hexagon_CCState::HandleByVal(), HandleVRSaveUpdate(), llvm::ARMFrameLowering::hasFP(), llvm::AArch64FrameLowering::hasFP(), hasVGPROperands(), llvm::Hexagon_CCState::Hexagon_CCState(), increaseCounters(), llvm::RegPressureTracker::init(), llvm::LLVMTargetMachine::initAsmInfo(), INITIALIZE_PASS(), InsertLDR_STR(), isADDADDMUL(), isCopy(), isFpMulInstruction(), isLocalCall(), isNopCopy(), llvm::TargetInstrInfo::isSchedulingBoundary(), llvm::DwarfDebug::isSubprogramContext(), isUnsafeToMoveAcross(), isXor1OfSetCC(), llvm::LiveRegMatrix::LiveRegMatrix(), lookupCandidateBaseReg(), LoopIsOuterMostWithPredecessor(), LowerADJUST_TRAMPOLINE(), llvm::AArch64TargetLowering::LowerCall(), llvm::SITargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), LowerINTRINSIC_W_CHAIN(), llvm::AArch64TargetLowering::LowerTLSDescCall(), llvm::MachineFunction::MachineFunction(), MatchingStackOffset(), parseMemoryOperand(), parsePhysicalReg(), llvm::MachineOperand::print(), llvm::MachineFunction::print(), llvm::MachineBasicBlock::print(), llvm::MachineInstr::print(), llvm::AArch64AsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::printOperand(), llvm::MipsAsmPrinter::printSavedRegsBitmask(), llvm::SystemZFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::XCoreFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), regsAreCompatible(), llvm::PPCFrameLowering::replaceFPWithRealFP(), llvm::X86TargetLowering::resetOperationActions(), llvm::ARMFrameLowering::ResolveFrameIndexReference(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), llvm::PEI::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::MachineTraceMetrics::runOnMachineFunction(), llvm::RegisterClassInfo::runOnMachineFunction(), llvm::LiveStacks::runOnMachineFunction(), llvm::LiveIntervals::runOnMachineFunction(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::MachineFunction::verify(), and llvm::Spiller::~Spiller().
Reloc::Model TargetMachine::getRelocationModel () const
getRelocationModel - Returns the code generation relocation model. The choices are static, PIC, and dynamic-no-pic, and target default.
Definition at line 91 of file TargetMachine.cpp.
References CodeGenInfo, llvm::Reloc::Default, and llvm::MCCodeGenInfo::getRelocationModel().
Referenced by CalculateTailCallSPDiff(), checkAndUpdateEFLAGSKill(), llvm::createARMJITCodeEmitterPass(), llvm::createPPCJITCodeEmitterPass(), llvm::createX86JITCodeEmitterPass(), llvm::ARMAsmPrinter::EmitJumpTable(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), llvm::ARMAsmPrinter::EmitStartOfAsmFile(), EmitTailCallStoreRetAddr(), expandf64Toi32(), llvm::X86InstrInfo::foldMemoryOperandImpl(), FPCCToARMCC(), getComparePred(), llvm::ARMTargetLowering::getJumpTableEncoding(), llvm::TargetLoweringObjectFile::getKindForGlobal(), GetLabelAccessInfo(), getModifierVariantKind(), llvm::MipsTargetLowering::getOpndList(), getTLSModel(), llvm::ARMInstrInfo::getUnindexedOpcode(), llvm::X86InstrInfo::hasHighOperandLatency(), llvm::PPCSubtarget::hasLazyResolverStub(), llvm::TargetLoweringObjectFile::Initialize(), llvm::X86TargetLowering::isLegalAddressingMode(), llvm::X86Subtarget::IsLegalToCallImmediateAddr(), isLocalCall(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::AArch64TargetLowering::LowerGlobalAddressELFSmall(), lowerGR128Binary(), LowerToTLSExecModel(), MatchingStackOffset(), PrepareCall(), llvm::AArch64AsmPrinter::printSymbolicAddress(), llvm::ARMTargetLowering::ReplaceNodeResults(), useSinCos(), and llvm::X86TargetMachine::X86TargetMachine().
virtual const TargetSelectionDAGInfo* llvm::TargetMachine::getSelectionDAGInfo () const inline virtual
Reimplemented in llvm::ThumbTargetMachine, llvm::X86_64TargetMachine, llvm::X86_32TargetMachine, llvm::ARMTargetMachine, llvm::MipsTargetMachine, llvm::NVPTXTargetMachine, llvm::HexagonTargetMachine, llvm::SystemZTargetMachine, llvm::MSP430TargetMachine, llvm::X86TargetMachine, llvm::PPCTargetMachine, llvm::SparcTargetMachine, llvm::AArch64TargetMachine, and llvm::XCoreTargetMachine.
Definition at line 122 of file Target/TargetMachine.h.
template<typename STC > const STC& llvm::TargetMachine::getSubtarget () const inline
getSubtarget - This method returns a pointer to the specified type of TargetSubtargetInfo. In debug builds, it verifies that the object being returned is of the correct type.
Definition at line 132 of file Target/TargetMachine.h.
Referenced by llvm::AArch64AsmPrinter::AArch64AsmPrinter(), llvm::AArch64TargetLowering::AArch64TargetLowering(), llvm::MipsTargetMachine::addAnalysisPasses(), llvm::ScheduleDAGInstrs::addPhysRegDataDeps(), llvm::ScheduleDAGInstrs::addVRegUseDeps(), adjCycles(), llvm::MipsSEInstrInfo::adjustStackPtr(), llvm::AMDGPUAsmPrinter::AMDGPUAsmPrinter(), llvm::ARMAsmPrinter::ARMAsmPrinter(), llvm::ARMTargetLowering::ARMTargetLowering(), llvm::X86InstrInfo::breakPartialRegDependency(), llvm::ScheduleDAGInstrs::buildSchedGraph(), llvm::R600InstrInfo::buildSlotOfVectorInstruction(), canFoldInAddressingMode(), llvm::X86InstrInfo::canInsertSelect(), checkNumAlignedDPRCS2Regs(), llvm::X86InstrInfo::classifyLEAReg(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::copyPhysReg(), llvm::createAMDGPUISelDag(), llvm::createARMJITCodeEmitterPass(), llvm::createDefaultScheduler(), llvm::ARM::createFastISel(), llvm::PPC::createFastISel(), llvm::createGlobalBaseRegPass(), llvm::createNVPTXISelDag(), createPPCAsmPrinterPass(), llvm::PPCInstrInfo::CreateTargetHazardRecognizer(), llvm::PPCInstrInfo::CreateTargetPostRAHazardRecognizer(), llvm::R600InstrInfo::CreateTargetScheduleState(), llvm::HexagonInstrInfo::CreateTargetScheduleState(), createTLOF(), llvm::createX86JITCodeEmitterPass(), llvm::ScheduleDAGMI::dumpSchedule(), llvm::AMDGPUAsmPrinter::EmitProgramInfoR600(), llvm::AMDGPUAsmPrinter::EmitProgramInfoSI(), llvm::X86InstrInfo::expandPostRAPseudo(), FindBaseOffset(), llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::X86RegisterInfo::getCalleeSavedRegs(), llvm::X86RegisterInfo::getCallPreservedMask(), GetDSubRegs(), llvm::X86InstrInfo::getExecutionDomain(), llvm::X86InstrInfo::getGlobalBaseReg(), GetLabelAccessInfo(), getLoadStoreRegOpcode(), llvm::X86RegisterInfo::getPointerRegClass(), llvm::X86RegisterInfo::getRegPressureLimit(), llvm::X86RegisterInfo::getReservedRegs(), llvm::ARMInstrInfo::getUnindexedOpcode(), gvNeedsNonLazyPtr(), llvm::X86InstrInfo::hasHighOperandLatency(), llvm::HexagonAsmPrinter::HexagonAsmPrinter(), llvm::MipsTargetObjectFile::Initialize(), llvm::ARMElfTargetObjectFile::Initialize(), llvm::R600SchedStrategy::initialize(), INITIALIZE_PASS(), InsertLDR_STR(), llvm::X86InstrInfo::isCoalescableExtInstr(), isCopy(), isFpMulInstruction(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::MipsAsmPrinter::MipsAsmPrinter(), ConsecutiveMemoryChainSorter::operator()(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PPCTargetLowering(), PrepareCall(), RemoveUnusedGlue(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::MachineTraceMetrics::runOnMachineFunction(), llvm::ScheduleDAGInstrs::ScheduleDAGInstrs(), llvm::X86InstrInfo::setExecutionDomain(), llvm::X86InstrInfo::shouldScheduleAdjacent(), llvm::SparcTargetLowering::SparcTargetLowering(), llvm::SystemZAsmPrinter::SystemZAsmPrinter(), llvm::TargetPassConfig::TargetPassConfig(), llvm::X86InstrInfo::unfoldMemoryOperand(), UpdateCPSRUse(), llvm::X86AsmPrinter::X86AsmPrinter(), llvm::X86JITInfo::X86JITInfo(), llvm::X86RegisterInfo::X86RegisterInfo(), llvm::X86TargetLowering::X86TargetLowering(), and llvm::AMDGPUTargetMachine::~AMDGPUTargetMachine().
virtual const TargetSubtargetInfo* llvm::TargetMachine::getSubtargetImpl () const inline virtual
getSubtargetImpl - virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
Reimplemented in llvm::MipsTargetMachine, llvm::PPCTargetMachine, llvm::NVPTXTargetMachine, llvm::AArch64TargetMachine, llvm::X86TargetMachine, llvm::AMDGPUTargetMachine, llvm::MSP430TargetMachine, llvm::SystemZTargetMachine, llvm::ARMBaseTargetMachine, llvm::HexagonTargetMachine, llvm::SparcTargetMachine, and llvm::XCoreTargetMachine.
Definition at line 103 of file Target/TargetMachine.h.
const Target& llvm::TargetMachine::getTarget () const inline
Definition at line 95 of file Target/TargetMachine.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile(), llvm::LLVMTargetMachine::addPassesToEmitMC(), llvm::EngineBuilder::create(), llvm::ConvergingVLIWScheduler::initialize(), and llvm::MachineOperand::print().
const StringRef llvm::TargetMachine::getTargetCPU () const inline
Definition at line 98 of file Target/TargetMachine.h.
const StringRef llvm::TargetMachine::getTargetFeatureString () const inline
Definition at line 99 of file Target/TargetMachine.h.
virtual const TargetLowering* llvm::TargetMachine::getTargetLowering () const inline virtual
Reimplemented in llvm::ThumbTargetMachine, llvm::X86_64TargetMachine, llvm::X86_32TargetMachine, llvm::ARMTargetMachine, llvm::MipsTargetMachine, llvm::NVPTXTargetMachine, llvm::SystemZTargetMachine, llvm::HexagonTargetMachine, llvm::MSP430TargetMachine, llvm::AMDGPUTargetMachine, llvm::X86TargetMachine, llvm::PPCTargetMachine, llvm::SparcTargetMachine, llvm::AArch64TargetMachine, llvm::ARMBaseTargetMachine, and llvm::XCoreTargetMachine.
Definition at line 121 of file Target/TargetMachine.h.
Referenced by accumulateAndSortLibcalls(), addPassesToGenerateCode(), llvm::SelectionDAG::ComputeMaskedBits(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::SelectionDAG::CreateStackTemporary(), llvm::ScheduleDAGMI::dumpSchedule(), llvm::AsmPrinter::EmitJumpTableInfo(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SelectionDAG::FoldSetCC(), getBlockNum(), getBuildPairElt(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantPool(), llvm::SelectionDAG::getGlobalAddress(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemmove(), llvm::SelectionDAG::getMemset(), llvm::AsmPrinter::getObjFileLowering(), llvm::SelectionDAG::getShiftAmountOperand(), llvm::SelectionDAGISel::getTargetLowering(), llvm::TargetPassConfig::getTargetLowering(), llvm::CCState::HandleByVal(), INITIALIZE_PASS(), llvm::TargetInstrInfo::isSchedulingBoundary(), LoopIsOuterMostWithPredecessor(), llvm::MachineFunction::MachineFunction(), MarkBlocksLiveIn(), llvm::StackProtector::runOnFunction(), and llvm::SelectionDAGISel::runOnMachineFunction().
const StringRef llvm::TargetMachine::getTargetTriple () const inline
Definition at line 97 of file Target/TargetMachine.h.
Referenced by accumulateAndSortLibcalls(), llvm::LLVMTargetMachine::addPassesToEmitFile(), llvm::LLVMTargetMachine::addPassesToEmitMC(), canCombineSinCosLibcall(), llvm::AsmPrinter::getTargetTriple(), llvm::TargetLoweringObjectFile::Initialize(), and InitLibcallNames().
TLSModel::Model TargetMachine::getTLSModel (const GlobalValue * GV) const
getTLSModel - Returns the TLS model which should be used for the given global variable.
Definition at line 123 of file TargetMachine.cpp.
References llvm::TLSModel::GeneralDynamic, getRelocationModel(), getSelectedTLSModel(), llvm::GlobalValue::hasHiddenVisibility(), llvm::GlobalValue::hasLocalLinkage(), llvm::TLSModel::InitialExec, llvm::GlobalValue::isDeclaration(), isDeclaration(), llvm::TLSModel::LocalDynamic, llvm::TLSModel::LocalExec, Options, llvm::Reloc::PIC_, and llvm::TargetOptions::PositionIndependentExecutable.
Referenced by llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::getJumpTableEncoding(), llvm::SparcTargetLowering::LowerGlobalTLSAddress(), llvm::AArch64TargetLowering::LowerGlobalTLSAddress(), lowerGR128Binary(), LowerLabelRef(), LowerToTLSExecModel(), and llvm::AArch64AsmPrinter::printSymbolicAddress().
bool llvm::TargetMachine::hasMCNoExecStack () const inline
hasMCNoExecStack - Check whether an executable stack is not needed.
Definition at line 176 of file Target/TargetMachine.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile(), and llvm::LLVMTargetMachine::addPassesToEmitMC().
bool llvm::TargetMachine::hasMCRelaxAll () const inline
hasMCRelaxAll - Check whether all machine code instructions should be relaxed.
Definition at line 161 of file Target/TargetMachine.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile(), and llvm::LLVMTargetMachine::addPassesToEmitMC().
bool llvm::TargetMachine::hasMCSaveTempLabels () const inline
hasMCSaveTempLabels - Check whether temporary labels will be preserved (i.e., not treated as temporary).
Definition at line 169 of file Target/TargetMachine.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile(), and llvm::LLVMTargetMachine::addPassesToEmitMC().
bool llvm::TargetMachine::hasMCUseCFI () const inline
hasMCUseCFI - Check whether we should use dwarf's .cfi_* directives.
Definition at line 188 of file Target/TargetMachine.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile().
bool llvm::TargetMachine::hasMCUseDwarfDirectory () const inline
hasMCUseDwarfDirectory - Check whether we should use .file directives with explicit directories.
Definition at line 195 of file Target/TargetMachine.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile().
bool llvm::TargetMachine::hasMCUseLoc () const inline
hasMCUseLoc - Check whether we should use dwarf's .loc directive.
Definition at line 182 of file Target/TargetMachine.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile(), llvm::DwarfDebug::beginFunction(), llvm::AsmPrinter::EmitFunctionBody(), and llvm::DwarfDebug::getOrCreateSourceID().
void TargetMachine::resetTargetOptions (const MachineFunction * MF) const
Reset the target options based on the function's attributes.
Definition at line 67 of file TargetMachine.cpp.
References DisableTailCalls(), F(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getTarget(), Options, and RESET_OPTION.
Referenced by llvm::SelectionDAGISel::runOnMachineFunction().
void TargetMachine::setAsmVerbosityDefault (bool V) static
setAsmVerbosityDefault - Set the default value of asm verbosity. Default is false.
Definition at line 176 of file TargetMachine.cpp.
References llvm::AsmVerbosityDefault().
void TargetMachine::setDataSections (bool V) static
setDataSections - Set if the data are emit into separate sections.
Definition at line 192 of file TargetMachine.cpp.
References DataSections.
void llvm::TargetMachine::setFastISel (bool Enable) inline
Definition at line 220 of file Target/TargetMachine.h.
References llvm::TargetOptions::EnableFastISel.
Referenced by addPassesToGenerateCode(), llvm::OptLevelChanger::OptLevelChanger(), and llvm::OptLevelChanger::~OptLevelChanger().
void TargetMachine::setFunctionSections (bool V) static
setFunctionSections - Set if the functions are emit into separate sections.
Definition at line 188 of file TargetMachine.cpp.
References FunctionSections.
void llvm::TargetMachine::setMCNoExecStack (bool Value) inline
setMCNoExecStack - Set whether an executabel stack is not needed.
Definition at line 179 of file Target/TargetMachine.h.
void llvm::TargetMachine::setMCRelaxAll (bool Value) inline
setMCRelaxAll - Set whether all machine code instructions should be relaxed.
Definition at line 165 of file Target/TargetMachine.h.
void llvm::TargetMachine::setMCSaveTempLabels (bool Value) inline
setMCSaveTempLabels - Set whether temporary labels will be preserved (i.e., not treated as temporary).
Definition at line 173 of file Target/TargetMachine.h.
void llvm::TargetMachine::setMCUseCFI (bool Value) inline
setMCUseCFI - Set whether all we should use dwarf's .cfi_* directives.
Definition at line 191 of file Target/TargetMachine.h.
Referenced by llvm::HexagonTargetMachine::HexagonTargetMachine(), and llvm::PPCTargetMachine::PPCTargetMachine().
void llvm::TargetMachine::setMCUseDwarfDirectory (bool Value) inline
setMCUseDwarfDirectory - Set whether all we should use .file directives with explicit directories.
Definition at line 199 of file Target/TargetMachine.h.
void llvm::TargetMachine::setMCUseLoc (bool Value) inline
setMCUseLoc - Set whether all we should use dwarf's .loc directive.
Definition at line 185 of file Target/TargetMachine.h.
void TargetMachine::setOptLevel (CodeGenOpt::Level Level) const
Overrides the optimization level.
Definition at line 167 of file TargetMachine.cpp.
References CodeGenInfo, and llvm::MCCodeGenInfo::setOptLevel().
Referenced by llvm::OptLevelChanger::OptLevelChanger(), and llvm::OptLevelChanger::~OptLevelChanger().
bool llvm::TargetMachine::shouldPrintMachineCode () const inline
Definition at line 222 of file Target/TargetMachine.h.
References llvm::TargetOptions::PrintMachineCode.
Referenced by llvm::TargetPassConfig::printAndVerify().
Member Data Documentation
const MCAsmInfo* llvm::TargetMachine::AsmInfo protected
AsmInfo - Contains target specific asm information.
Definition at line 83 of file Target/TargetMachine.h.
Referenced by llvm::LLVMTargetMachine::initAsmInfo(), and ~TargetMachine().
MCCodeGenInfo* llvm::TargetMachine::CodeGenInfo protected
CodeGenInfo - Low level target information such as relocation model. Non-const to allow resetting optimization level per-function.
Definition at line 79 of file Target/TargetMachine.h.
Referenced by getCodeModel(), getOptLevel(), getRelocationModel(), llvm::LLVMTargetMachine::LLVMTargetMachine(), setOptLevel(), and ~TargetMachine().
unsigned llvm::TargetMachine::MCNoExecStack protected
Definition at line 86 of file Target/TargetMachine.h.
unsigned llvm::TargetMachine::MCRelaxAll protected
Definition at line 85 of file Target/TargetMachine.h.
unsigned llvm::TargetMachine::MCSaveTempLabels protected
Definition at line 87 of file Target/TargetMachine.h.
unsigned llvm::TargetMachine::MCUseCFI protected
Definition at line 89 of file Target/TargetMachine.h.
unsigned llvm::TargetMachine::MCUseDwarfDirectory protected
Definition at line 90 of file Target/TargetMachine.h.
unsigned llvm::TargetMachine::MCUseLoc protected
Definition at line 88 of file Target/TargetMachine.h.
TargetOptions llvm::TargetMachine::Options mutable
Definition at line 105 of file Target/TargetMachine.h.
Referenced by llvm::TargetPassConfig::addMachinePasses(), AdjustStackOffset(), llvm::ARMTargetLowering::ARMTargetLowering(), CalculateParameterAndLinkageAreaSize(), CalculateStackSlotSize(), canCombineSinCosLibcall(), llvm::ARMBaseRegisterInfo::cannotEliminateFrame(), checkVSELConstraints(), collectFailStats(), llvm::ARM::createFastISel(), CreatePrologue(), llvm::PPCFrameLowering::eliminateCallFramePseudoInstr(), llvm::PPCFrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitPrologue(), EmitTailCallStoreRetAddr(), llvm::DwarfDebug::endFunction(), expandf64Toi32(), FPCCToARMCC(), FuncIsMadeTailCallSafe(), getArchForCPU(), getBuildPairElt(), llvm::X86_64MachoTargetObjectFile::getCFIPersonalitySymbol(), getComparePred(), llvm::TargetLoweringObjectFile::getKindForGlobal(), GetNegatedExpression(), llvm::SelectionDAG::getNode(), llvm::X86TargetLowering::getSetCCResultType(), getTLSModel(), llvm::MipsFrameLowering::hasFP(), llvm::SparcFrameLowering::hasFP(), llvm::XCoreFrameLowering::hasFP(), llvm::ARMFrameLowering::hasFP(), llvm::MSP430FrameLowering::hasFP(), llvm::SystemZFrameLowering::hasFP(), llvm::X86FrameLowering::hasFP(), llvm::AArch64FrameLowering::hasFP(), llvm::MipsTargetObjectFile::Initialize(), IsCCallConvention(), llvm::AArch64TargetLowering::IsEligibleForTailCallOptimization(), llvm::isInTailCallPosition(), isLocalCall(), isXor1OfSetCC(), llvm::AArch64TargetLowering::LowerCall(), llvm::AArch64TargetLowering::LowerFormalArguments(), llvm::MipsSubtarget::mipsSEUsesSoftFloat(), llvm::MipsTargetLowering::MipsTargetLowering(), llvm::PPCFrameLowering::needsFP(), llvm::OptLevelChanger::OptLevelChanger(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformFMinFMaxCombine(), PerformSELECT_CCCombine(), PerformSELECTCombine(), PerformSTORECombine(), llvm::PPCTargetLowering::PPCTargetLowering(), llvm::PPCFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::PPCFrameLowering::processFunctionBeforeFrameFinalized(), llvm::X86TargetLowering::resetOperationActions(), resetTargetOptions(), and llvm::SelectionDAGISel::runOnMachineFunction().
std::string llvm::TargetMachine::TargetCPU protected
Definition at line 74 of file Target/TargetMachine.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile(), and llvm::LLVMTargetMachine::addPassesToEmitMC().
std::string llvm::TargetMachine::TargetFS protected
Definition at line 75 of file Target/TargetMachine.h.
std::string llvm::TargetMachine::TargetTriple protected
TargetTriple, TargetCPU, TargetFS - Triple string, CPU name, and target feature strings the TargetMachine instance is created with.
Definition at line 73 of file Target/TargetMachine.h.
Referenced by llvm::LLVMTargetMachine::initAsmInfo().
const Target& llvm::TargetMachine::TheTarget protected
TheTarget - The Target that this machine was created for.
Definition at line 69 of file Target/TargetMachine.h.
Referenced by llvm::LLVMTargetMachine::initAsmInfo().
The documentation for this class was generated from the following files:
Target/TargetMachine.h
TargetMachine.cpp