LLVM: llvm::error_condition Class Reference
LLVM API Documentation
llvm::error_condition Class Reference
#include <system_error.h>
Public Types
typedef void(* unspecified_bool_type) ()
Public Member Functions
error_condition ()
error_condition (int _val, const error_category &_cat)
template<class E >
error_condition (E _e, typename enable_if_c< is_error_condition_enum< E >::value >::type *=0)
void assign (int _val, const error_category &_cat)
template<class E >
enable_if_c< is_error_condition_enum< E >::value, error_condition & >::type operator= (E _e)
void clear ()
int value () const
const error_category & category () const
std::string message () const
operator unspecified_bool_type () const
Static Public Member Functions
static void unspecified_bool_true ()
Detailed Description
Definition at line 667 of file system_error.h.
Member Typedef Documentation
typedef void(* llvm::error_condition::unspecified_bool_type) ()
Definition at line 707 of file system_error.h.
Constructor & Destructor Documentation
llvm::error_condition::error_condition () inline
Definition at line 672 of file system_error.h.
llvm::error_condition::error_condition (int _val, const error_category & _cat) inline
Definition at line 674 of file system_error.h.
template<class E > llvm::error_condition::error_condition (E _e, typename enable_if_c< is_error_condition_enum< E >::value >::type * = 0) inline
Definition at line 678 of file system_error.h.
References llvm::make_error_condition().
Member Function Documentation
void llvm::error_condition::assign (int _val, const error_category & _cat) inline
Definition at line 683 of file system_error.h.
const error_category& llvm::error_condition::category () const inline
Definition at line 704 of file system_error.h.
References message().
Referenced by llvm::operator<(), and llvm::operator==().
void llvm::error_condition::clear () inline
Definition at line 697 of file system_error.h.
References llvm::generic_category().
std::string llvm::error_condition::message () const
Definition at line 111 of file system_error.cpp.
llvm::error_condition::operator unspecified_bool_type () const inline
Definition at line 710 of file system_error.h.
template<class E > enable_if_c< is_error_condition_enum<E>::value, error_condition& >::type llvm::error_condition::operator= (E _e) inline
Definition at line 694 of file system_error.h.
References llvm::make_error_condition().
static void llvm::error_condition::unspecified_bool_true () inline static
Definition at line 708 of file system_error.h.
int llvm::error_condition::value () const inline
Definition at line 702 of file system_error.h.
Referenced by llvm::operator<(), and llvm::operator==().
The documentation for this class was generated from the following files:
system_error.h
system_error.cpp