LLVM: llvm::XCoreInstPrinter Class Reference
LLVM API Documentation
llvm::XCoreInstPrinter Class Reference
#include <XCoreInstPrinter.h>
Public Member Functions
XCoreInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
void printInstruction (const MCInst *MI, raw_ostream &O)
virtual void printRegName (raw_ostream &OS, unsigned RegNo) const
printRegName - Print the assembler register name.
virtual void printInst (const MCInst *MI, raw_ostream &O, StringRef Annot)
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
void setCommentStream (raw_ostream &OS)
setCommentStream - Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
uint64_t getAvailableFeatures () const
void setAvailableFeatures (uint64_t Value)
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
StringRef markup (StringRef a, StringRef b) const
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
HexStyle::Style getPrintHexStyleHex () const
void setPrintImmHex (HexStyle::Style Value)
format_object1< int64_t > formatImm (const int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object1< int64_t > formatDec (const int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object1< int64_t > formatHex (const int64_t Value) const
format_object1< uint64_t > formatHex (const uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
uint64_t AvailableFeatures
The current set of available features.
bool UseMarkup
True if we are printing marked up assembly.
bool PrintImmHex
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle
Which style to use for printing hexadecimal values.
Detailed Description
Definition at line 24 of file XCoreInstPrinter.h.
Constructor & Destructor Documentation
llvm::XCoreInstPrinter::XCoreInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) inline
Definition at line 26 of file XCoreInstPrinter.h.
References getRegisterName(), llvm::A64CC::MI, printInst(), printInstruction(), and printRegName().
Member Function Documentation
static const char* llvm::XCoreInstPrinter::getRegisterName (unsigned RegNo) static
Referenced by printRegName(), and XCoreInstPrinter().
void XCoreInstPrinter::printInst (const MCInst * MI, raw_ostream & OS, StringRef Annot) virtual
printInst - Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 31 of file XCoreInstPrinter.cpp.
References llvm::A64CC::MI, llvm::MCInstPrinter::printAnnotation(), printInstruction(), and llvm::report_fatal_error().
Referenced by XCoreInstPrinter().
void llvm::XCoreInstPrinter::printInstruction (const MCInst * MI, raw_ostream & O)
Referenced by printInst(), and XCoreInstPrinter().
void XCoreInstPrinter::printRegName (raw_ostream & OS, unsigned RegNo) const virtual
printRegName - Print the assembler register name.
Reimplemented from llvm::MCInstPrinter.
Definition at line 27 of file XCoreInstPrinter.cpp.
References getRegisterName(), and llvm::StringRef::lower().
Referenced by printExpr(), and XCoreInstPrinter().
The documentation for this class was generated from the following files:
XCoreInstPrinter.h
XCoreInstPrinter.cpp