LLVM: llvm::DwarfUnits Class Reference
LLVM API Documentation
llvm::DwarfUnits Class Reference
Collects and handles information specific to a particular collection of units.
#include <DwarfDebug.h>
Public Member Functions
DwarfUnits (AsmPrinter *AP, FoldingSet< DIEAbbrev > *AS, std::vector< DIEAbbrev * > &A, const char *Pref, BumpPtrAllocator &DA)
unsigned computeSizeAndOffset (DIE *Die, unsigned Offset)
Compute the size and offset of a DIE given an incoming Offset.
void computeSizeAndOffsets ()
Compute the size and offset of all the DIEs.
void assignAbbrevNumber (DIEAbbrev &Abbrev)
Define a unique number for the abbreviation.
void addUnit (CompileUnit *CU)
Add a unit to the list of CUs.
void emitUnits (DwarfDebug *DD, const MCSection *USection, const MCSection *ASection, const MCSymbol *ASectionSym)
Emit all of the units to the section listed with the given abbreviation section.
void emitStrings (const MCSection *StrSection, const MCSection *OffsetSection, const MCSymbol *StrSecSym)
Emit all of the strings to the section given.
void emitAddresses (const MCSection *AddrSection)
Emit all of the addresses to the section given.
MCSymbol * getStringPoolSym ()
Returns the entry into the start of the pool.
MCSymbol * getStringPoolEntry (StringRef Str)
Returns an entry into the string pool with the given string text.
unsigned getStringPoolIndex (StringRef Str)
Returns the index into the string pool with the given string text.
StrPool * getStringPool ()
Returns the string pool.
unsigned getAddrPoolIndex (const MCExpr *Sym)
Returns the index into the address pool with the given label/symbol.
unsigned getAddrPoolIndex (const MCSymbol *Sym)
AddrPool * getAddrPool ()
Returns the address pool.
Detailed Description
Collects and handles information specific to a particular collection of units.
Definition at line 221 of file DwarfDebug.h.
Constructor & Destructor Documentation
llvm::DwarfUnits::DwarfUnits (AsmPrinter * AP, FoldingSet< DIEAbbrev > * AS, std::vector< DIEAbbrev * > & A, const char * Pref, BumpPtrAllocator & DA) inline
Definition at line 251 of file DwarfDebug.h.
Member Function Documentation
void llvm::DwarfUnits::addUnit (CompileUnit * CU) inline
Add a unit to the list of CUs.
Definition at line 268 of file DwarfDebug.h.
References llvm::X86II::DD, and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by llvm::DwarfDebug::getOrCreateSourceID().
void DwarfUnits::assignAbbrevNumber (DIEAbbrev & Abbrev)
Define a unique number for the abbreviation.
Definition at line 275 of file DwarfDebug.cpp.
References llvm::DIEAbbrev::getNumber(), and llvm::DIEAbbrev::setNumber().
unsigned DwarfUnits::computeSizeAndOffset (DIE * Die, unsigned Offset)
Compute the size and offset of a DIE given an incoming Offset.
Definition at line 1928 of file DwarfDebug.cpp.
References llvm::dwarf::DW_CHILDREN_yes, llvm::DIE::getAbbrev(), llvm::DIE::getAbbrevNumber(), llvm::DIE::getChildren(), llvm::DIEAbbrev::getChildrenFlag(), llvm::DIEAbbrev::getData(), llvm::DIE::getOffset(), llvm::MCAsmInfo::getULEB128Size(), llvm::DIE::getValues(), i, j(), M, N, llvm::DIE::setOffset(), llvm::DIE::setSize(), and llvm::SmallVectorTemplateCommon< T >::size().
void DwarfUnits::computeSizeAndOffsets ()
Compute the size and offset of all the DIEs.
Definition at line 1970 of file DwarfDebug.cpp.
References emitSectionSym(), GenerateGnuPubSections, llvm::MCObjectFileInfo::getDataSection(), llvm::MCObjectFileInfo::getDwarfAbbrevDWOSection(), llvm::MCObjectFileInfo::getDwarfAbbrevSection(), llvm::MCObjectFileInfo::getDwarfAddrSection(), llvm::MCObjectFileInfo::getDwarfARangesSection(), llvm::MCObjectFileInfo::getDwarfGnuPubNamesSection(), llvm::MCObjectFileInfo::getDwarfGnuPubTypesSection(), llvm::MCObjectFileInfo::getDwarfInfoSection(), llvm::MCObjectFileInfo::getDwarfLineSection(), llvm::MCObjectFileInfo::getDwarfLocSection(), llvm::MCObjectFileInfo::getDwarfMacroInfoSection(), llvm::MCObjectFileInfo::getDwarfPubNamesSection(), llvm::MCObjectFileInfo::getDwarfPubTypesSection(), llvm::MCObjectFileInfo::getDwarfRangesSection(), llvm::MCObjectFileInfo::getDwarfStrDWOSection(), llvm::MCObjectFileInfo::getDwarfStrSection(), llvm::AsmPrinter::getObjFileLowering(), llvm::MCObjectFileInfo::getTextSection(), I, and llvm::DwarfDebug::useSplitDwarf().
Referenced by shouldAddODRHash().
void DwarfUnits::emitAddresses (const MCSection * AddrSection)
Emit all of the addresses to the section given.
Definition at line 2619 of file DwarfDebug.cpp.
References llvm::MCStreamer::AddComment(), llvm::sys::path::begin(), llvm::MCContext::CreateTempSymbol(), llvm::dwarf::DW_ATE_signed, llvm::dwarf::DW_ATE_signed_char, llvm::dwarf::DW_OP_consts, llvm::dwarf::DW_OP_constu, llvm::dwarf::DW_OP_deref, llvm::dwarf::DW_OP_plus_uconst, llvm::AsmPrinter::EmitDwarfRegOp(), llvm::AsmPrinter::EmitInt8(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitLabel(), llvm::AsmPrinter::EmitLabelDifference(), llvm::AsmPrinter::EmitSLEB128(), emitStrings(), llvm::MCStreamer::EmitSymbolValue(), llvm::AsmPrinter::EmitULEB128(), llvm::MCStreamer::EmitValue(), llvm::sys::path::end(), for, llvm::DIVariable::getAddrElement(), llvm::DotDebugLocEntry::getBeginSym(), llvm::MCStreamer::getContext(), llvm::AsmPrinter::getDataLayout(), llvm::MCObjectFileInfo::getDwarfLocSection(), llvm::MCObjectFileInfo::getDwarfStrSection(), llvm::DotDebugLocEntry::getEndSym(), llvm::DotDebugLocEntry::getInt(), llvm::DotDebugLocEntry::getLoc(), llvm::DIVariable::getNumAddrElements(), llvm::AsmPrinter::getObjFileLowering(), llvm::MachineLocation::getOffset(), llvm::DataLayout::getPointerSize(), llvm::MachineLocation::getReg(), llvm::AsmPrinter::GetTempSymbol(), llvm::DIVariable::getType(), llvm::DotDebugLocEntry::getVariable(), llvm::DIVariable::hasComplexAddress(), i, I, index, llvm::DotDebugLocEntry::isEmpty(), llvm::DIVariable::isIndirect(), llvm::DotDebugLocEntry::isInt(), llvm::DotDebugLocEntry::isLocation(), llvm::DotDebugLocEntry::isMerged(), llvm::MachineLocation::isReg(), llvm_unreachable, llvm::DotDebugLocEntry::Merge(), N, llvm::DIBuilder::OpDeref, llvm::DIBuilder::OpPlus, llvm::AsmPrinter::OutStreamer, llvm::MCStreamer::SwitchSection(), and llvm::DwarfDebug::useSplitDwarf().
Referenced by llvm::DwarfDebug::endModule().
void DwarfUnits::emitStrings (const MCSection * StrSection, const MCSection * OffsetSection = NULL, const MCSymbol * StrSecSym = NULL)
Emit all of the strings to the section given.
Definition at line 2576 of file DwarfDebug.cpp.
References llvm::array_pod_sort(), llvm::MCStreamer::EmitBytes(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitLabel(), llvm::StringPool::empty(), i, I, llvm::AsmPrinter::OutStreamer, size, and llvm::MCStreamer::SwitchSection().
Referenced by emitAddresses().
void DwarfUnits::emitUnits (DwarfDebug * DD, const MCSection * USection, const MCSection * ASection, const MCSymbol * ASectionSym)
Emit all of the units to the section listed with the given abbreviation section.
Definition at line 2156 of file DwarfDebug.cpp.
References llvm::MCStreamer::AddComment(), llvm::DwarfAccelTable::AddName(), llvm::StringMap< ValueTy, AllocatorTy >::begin(), llvm::X86II::DE, llvm::dwarf::DW_ATOM_die_offset, llvm::dwarf::DW_ATOM_die_tag, llvm::dwarf::DW_ATOM_type_flags, llvm::dwarf::DW_LNE_set_address, llvm::DIEAbbrev::Emit(), llvm::DwarfAccelTable::Emit(), llvm::DwarfDebug::emitDIE(), llvm::CompileUnit::emitHeader(), llvm::AsmPrinter::EmitInt32(), llvm::AsmPrinter::EmitInt8(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitSymbolValue(), llvm::AsmPrinter::EmitULEB128(), emitUnits(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::DwarfAccelTable::FinalizeTable(), llvm::A64CC::GE, llvm::CompileUnit::getAccelNames(), llvm::CompileUnit::getAccelNamespace(), llvm::CompileUnit::getAccelObjC(), llvm::CompileUnit::getAccelTypes(), llvm::CompileUnit::getCUDie(), llvm::AsmPrinter::getDataLayout(), llvm::MCObjectFileInfo::getDwarfAbbrevSection(), llvm::MCObjectFileInfo::getDwarfAccelNamespaceSection(), llvm::MCObjectFileInfo::getDwarfAccelNamesSection(), llvm::MCObjectFileInfo::getDwarfAccelObjCSection(), llvm::MCObjectFileInfo::getDwarfAccelTypesSection(), llvm::MCObjectFileInfo::getDwarfInfoSection(), llvm::CompileUnit::getHeaderSize(), llvm::MCSection::getLabelBeginName(), llvm::MCSection::getLabelEndName(), llvm::DIEAbbrev::getNumber(), llvm::AsmPrinter::getObjFileLowering(), llvm::DataLayout::getPointerSize(), llvm::DIE::getSize(), llvm::AsmPrinter::GetTempSymbol(), llvm::CompileUnit::getUniqueID(), i, I, N, llvm::AsmPrinter::OutStreamer, llvm::ARMBuildAttrs::Section, llvm::MCStreamer::SwitchSection(), and llvm::DwarfDebug::useSplitDwarf().
Referenced by emitUnits().
AddrPool* llvm::DwarfUnits::getAddrPool () inline
Returns the address pool.
Definition at line 302 of file DwarfDebug.h.
unsigned DwarfUnits::getAddrPoolIndex (const MCExpr * Sym)
Returns the index into the address pool with the given label/symbol.
Definition at line 265 of file DwarfDebug.cpp.
References P.
Referenced by llvm::CompileUnit::addLabelAddress(), llvm::CompileUnit::addOpAddress(), and llvm::CompileUnit::createGlobalVariableDIE().
unsigned DwarfUnits::getAddrPoolIndex (const MCSymbol * Sym)
Definition at line 261 of file DwarfDebug.cpp.
References llvm::MCSymbolRefExpr::Create(), and llvm::AsmPrinter::OutContext.
StrPool* llvm::DwarfUnits::getStringPool () inline
Returns the string pool.
Definition at line 294 of file DwarfDebug.h.
MCSymbol * DwarfUnits::getStringPoolEntry (StringRef Str)
Returns an entry into the string pool with the given string text.
Definition at line 242 of file DwarfDebug.cpp.
References llvm::AsmPrinter::GetTempSymbol().
Referenced by llvm::CompileUnit::addAccelName(), llvm::CompileUnit::addAccelNamespace(), llvm::CompileUnit::addAccelObjC(), llvm::CompileUnit::addAccelType(), llvm::CompileUnit::addLocalString(), llvm::CompileUnit::addString(), and llvm::DwarfAccelTable::FinalizeTable().
unsigned DwarfUnits::getStringPoolIndex (StringRef Str)
Returns the index into the string pool with the given string text.
Definition at line 251 of file DwarfDebug.cpp.
References llvm::AsmPrinter::GetTempSymbol().
Referenced by llvm::CompileUnit::addString().
MCSymbol * DwarfUnits::getStringPoolSym ()
Returns the entry into the start of the pool.
Definition at line 238 of file DwarfDebug.cpp.
References llvm::AsmPrinter::GetTempSymbol().
Referenced by llvm::CompileUnit::addLocalString(), llvm::CompileUnit::addString(), and llvm::DwarfAccelTable::FinalizeTable().
The documentation for this class was generated from the following files:
DwarfDebug.h
DwarfDebug.cpp