LLVM: llvm::AggressiveAntiDepState Class Reference
LLVM API Documentation
llvm::AggressiveAntiDepState Class Reference
#include <AggressiveAntiDepBreaker.h>
Classes
struct RegisterReference
Public Member Functions
AggressiveAntiDepState (const unsigned TargetRegs, MachineBasicBlock *BB)
std::vector< unsigned > & GetKillIndices ()
GetKillIndices - Return the kill indices.
std::vector< unsigned > & GetDefIndices ()
GetDefIndices - Return the define indices.
std::multimap< unsigned, RegisterReference > & GetRegRefs ()
GetRegRefs - Return the RegRefs map.
unsigned GetGroup (unsigned Reg)
void GetGroupRegs (unsigned Group, std::vector< unsigned > &Regs, std::multimap< unsigned, AggressiveAntiDepState::RegisterReference > *RegRefs)
unsigned UnionGroups (unsigned Reg1, unsigned Reg2)
unsigned LeaveGroup (unsigned Reg)
bool IsLive (unsigned Reg)
IsLive - Return true if Reg is live.
Detailed Description
Class AggressiveAntiDepState Contains all the state necessary for anti-dep breaking.
Definition at line 37 of file AggressiveAntiDepBreaker.h.
Constructor & Destructor Documentation
AggressiveAntiDepState::AggressiveAntiDepState (const unsigned TargetRegs, MachineBasicBlock * BB)
Definition at line 42 of file AggressiveAntiDepBreaker.cpp.
References i, and llvm::MachineBasicBlock::size().
Member Function Documentation
std::vector<unsigned>& llvm::AggressiveAntiDepState::GetDefIndices () inline
GetDefIndices - Return the define indices.
Definition at line 84 of file AggressiveAntiDepBreaker.h.
Referenced by llvm::AggressiveAntiDepBreaker::BreakAntiDependencies(), CriticalPathStep(), llvm::AggressiveAntiDepBreaker::Observe(), and llvm::AggressiveAntiDepBreaker::StartBlock().
unsigned AggressiveAntiDepState::GetGroup (unsigned Reg)
Definition at line 60 of file AggressiveAntiDepBreaker.cpp.
Referenced by llvm::AggressiveAntiDepBreaker::BreakAntiDependencies(), CriticalPathStep(), GetGroupRegs(), GetRegRefs(), llvm::AggressiveAntiDepBreaker::Observe(), and UnionGroups().
void AggressiveAntiDepState::GetGroupRegs (unsigned Group, std::vector< unsigned > & Regs, std::multimap< unsigned, AggressiveAntiDepState::RegisterReference > * RegRefs)
Definition at line 68 of file AggressiveAntiDepBreaker.cpp.
References GetGroup().
Referenced by CriticalPathStep(), and GetRegRefs().
std::vector<unsigned>& llvm::AggressiveAntiDepState::GetKillIndices () inline
GetKillIndices - Return the kill indices.
Definition at line 81 of file AggressiveAntiDepBreaker.h.
Referenced by llvm::AggressiveAntiDepBreaker::BreakAntiDependencies(), CriticalPathStep(), and llvm::AggressiveAntiDepBreaker::StartBlock().
std::multimap<unsigned, RegisterReference>& llvm::AggressiveAntiDepState::GetRegRefs () inline
GetRegRefs - Return the RegRefs map.
Definition at line 87 of file AggressiveAntiDepBreaker.h.
References GetGroup(), GetGroupRegs(), IsLive(), LeaveGroup(), and UnionGroups().
Referenced by llvm::AggressiveAntiDepBreaker::BreakAntiDependencies(), and CriticalPathStep().
bool AggressiveAntiDepState::IsLive (unsigned Reg)
IsLive - Return true if Reg is live.
Definition at line 106 of file AggressiveAntiDepBreaker.cpp.
References llvm::AggressiveAntiDepBreaker::AggressiveAntiDepBreaker().
Referenced by llvm::AggressiveAntiDepBreaker::BreakAntiDependencies(), CriticalPathStep(), GetRegRefs(), and llvm::AggressiveAntiDepBreaker::Observe().
unsigned AggressiveAntiDepState::LeaveGroup (unsigned Reg)
Definition at line 95 of file AggressiveAntiDepBreaker.cpp.
Referenced by CriticalPathStep(), and GetRegRefs().
unsigned AggressiveAntiDepState::UnionGroups (unsigned Reg1, unsigned Reg2)
Definition at line 79 of file AggressiveAntiDepBreaker.cpp.
References GetGroup().
Referenced by llvm::AggressiveAntiDepBreaker::BreakAntiDependencies(), CriticalPathStep(), GetRegRefs(), llvm::AggressiveAntiDepBreaker::Observe(), and llvm::AggressiveAntiDepBreaker::StartBlock().
The documentation for this class was generated from the following files:
AggressiveAntiDepBreaker.h
AggressiveAntiDepBreaker.cpp