LLVM: llvm::ReversePostOrderTraversal< GraphT, GT > Class Template Reference
LLVM API Documentation
llvm::ReversePostOrderTraversal< GraphT, GT > Class Template Reference
#include <PostOrderIterator.h>
Public Types
typedef std::vector< NodeType * >::reverse_iterator rpo_iterator
Public Member Functions
ReversePostOrderTraversal (GraphT G)
rpo_iterator begin ()
rpo_iterator end ()
Detailed Description
template<class GraphT, class GT = GraphTraits<GraphT>>
class llvm::ReversePostOrderTraversal< GraphT, GT >
Definition at line 259 of file PostOrderIterator.h.
Member Typedef Documentation
template<class GraphT, class GT = GraphTraits<GraphT>> typedef std::vector<NodeType*>::reverse_iterator llvm::ReversePostOrderTraversal< GraphT, GT >::rpo_iterator
Definition at line 266 of file PostOrderIterator.h.
Constructor & Destructor Documentation
template<class GraphT, class GT = GraphTraits<GraphT>> llvm::ReversePostOrderTraversal< GraphT, GT >::ReversePostOrderTraversal (GraphT G) inline
Definition at line 268 of file PostOrderIterator.h.
Member Function Documentation
template<class GraphT, class GT = GraphTraits<GraphT>> rpo_iterator llvm::ReversePostOrderTraversal< GraphT, GT >::begin () inline
Definition at line 273 of file PostOrderIterator.h.
Referenced by collectFailStats(), isOnlyReachableViaThisEdge(), isUnmovableInstruction(), and UpdateCPSRUse().
template<class GraphT, class GT = GraphTraits<GraphT>> rpo_iterator llvm::ReversePostOrderTraversal< GraphT, GT >::end () inline
Definition at line 274 of file PostOrderIterator.h.
Referenced by collectFailStats(), isOnlyReachableViaThisEdge(), isUnmovableInstruction(), and UpdateCPSRUse().
The documentation for this class was generated from the following file:
PostOrderIterator.h