LLVM: llvm::NVPTXInstrInfo Class Reference
LLVM API Documentation
llvm::NVPTXInstrInfo Class Reference
#include <NVPTXInstrInfo.h>
Public Member Functions
NVPTXInstrInfo (NVPTXTargetMachine &TM)
virtual const NVPTXRegisterInfo & getRegisterInfo () const
virtual void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const
virtual bool isMoveInstr (const MachineInstr &MI, unsigned &SrcReg, unsigned &DestReg) const
bool isLoadInstr (const MachineInstr &MI, unsigned &AddrSpace) const
bool isStoreInstr (const MachineInstr &MI, unsigned &AddrSpace) const
bool isReadSpecialReg (MachineInstr &MI) const
virtual bool CanTailMerge (const MachineInstr *MI) const
virtual bool AnalyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify) const
virtual unsigned RemoveBranch (MachineBasicBlock &MBB) const
virtual unsigned InsertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, const SmallVectorImpl< MachineOperand > &Cond, DebugLoc DL) const
unsigned getLdStCodeAddrSpace (const MachineInstr &MI) const
Detailed Description
Definition at line 26 of file NVPTXInstrInfo.h.
Constructor & Destructor Documentation
NVPTXInstrInfo::NVPTXInstrInfo (NVPTXTargetMachine & TM) explicit
Definition at line 31 of file NVPTXInstrInfo.cpp.
Member Function Documentation
bool NVPTXInstrInfo::AnalyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify) const virtual
AnalyzeBranch - Analyze the branching code at the end of MBB, returning true if it cannot be understood (e.g. it's a switch dispatch or isn't implemented for a target). Upon success, this returns false and returns with the following information in various cases:
If this block ends with no branches (it just falls through to its succ) just return false, leaving TBB/FBB null.
If this block ends with only an unconditional branch, it sets TBB to be the destination block.
If this block ends with an conditional branch and it falls through to an successor block, it sets TBB to be the branch destination block and a list of operands that evaluate the condition. These operands can be passed to other TargetInstrInfo methods to create new branches.
If this block ends with an conditional branch and an unconditional block, it returns the 'true' destination in TBB, the 'false' destination in FBB, and a list of operands that evaluate the condition. These operands can be passed to other TargetInstrInfo methods to create new branches.
Note that RemoveBranch and InsertBranch must be implemented to support cases where this method returns success.
Definition at line 169 of file NVPTXInstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), I, and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by getRegisterInfo().
bool NVPTXInstrInfo::CanTailMerge (const MachineInstr * MI) const virtual
Definition at line 133 of file NVPTXInstrInfo.cpp.
References llvm::MachineInstr::getOpcode(), isLoadInstr(), isStoreInstr(), and llvm::NVPTX::PTXLdStInstCode::SHARED.
Referenced by getRegisterInfo().
void NVPTXInstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const virtual
Definition at line 34 of file NVPTXInstrInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::getKillRegState(), llvm::MachineBasicBlock::getParent(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm_unreachable, MRI, and llvm::report_fatal_error().
Referenced by getRegisterInfo().
unsigned llvm::NVPTXInstrInfo::getLdStCodeAddrSpace (const MachineInstr & MI) const inline
Definition at line 71 of file NVPTXInstrInfo.h.
References llvm::MachineOperand::getImm(), and llvm::MachineInstr::getOperand().
Referenced by isLoadInstr(), and isStoreInstr().
virtual const NVPTXRegisterInfo& llvm::NVPTXInstrInfo::getRegisterInfo () const inline virtual
Definition at line 33 of file NVPTXInstrInfo.h.
References AnalyzeBranch(), CanTailMerge(), copyPhysReg(), I, InsertBranch(), isLoadInstr(), isMoveInstr(), isReadSpecialReg(), isStoreInstr(), llvm::A64CC::MI, and RemoveBranch().
Referenced by llvm::NVPTXTargetMachine::getRegisterInfo().
unsigned NVPTXInstrInfo::InsertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, const SmallVectorImpl< MachineOperand > & Cond, DebugLoc DL) const virtual
Definition at line 250 of file NVPTXInstrInfo.cpp.
References llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::SmallVectorBase::empty(), getReg(), and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by getRegisterInfo().
bool NVPTXInstrInfo::isLoadInstr (const MachineInstr & MI, unsigned & AddrSpace) const
Definition at line 111 of file NVPTXInstrInfo.cpp.
References llvm::MachineInstr::getDesc(), getLdStCodeAddrSpace(), llvm::NVPTX::isLoadMask, llvm::NVPTX::isLoadShift, and llvm::MCInstrDesc::TSFlags.
Referenced by CanTailMerge(), and getRegisterInfo().
bool NVPTXInstrInfo::isMoveInstr (const MachineInstr & MI, unsigned & SrcReg, unsigned & DestReg) const virtual
Definition at line 67 of file NVPTXInstrInfo.cpp.
References dest, llvm::MachineInstr::getDesc(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isReg(), llvm::NVPTX::SimpleMoveMask, llvm::NVPTX::SimpleMoveShift, and llvm::MCInstrDesc::TSFlags.
Referenced by getRegisterInfo().
bool NVPTXInstrInfo::isReadSpecialReg (MachineInstr & MI) const
Definition at line 90 of file NVPTXInstrInfo.cpp.
References llvm::MachineInstr::getOpcode().
Referenced by getRegisterInfo().
bool NVPTXInstrInfo::isStoreInstr (const MachineInstr & MI, unsigned & AddrSpace) const
Definition at line 122 of file NVPTXInstrInfo.cpp.
References llvm::MachineInstr::getDesc(), getLdStCodeAddrSpace(), llvm::NVPTX::isStoreMask, llvm::NVPTX::isStoreShift, and llvm::MCInstrDesc::TSFlags.
Referenced by CanTailMerge(), and getRegisterInfo().
unsigned NVPTXInstrInfo::RemoveBranch (MachineBasicBlock & MBB) const virtual
Definition at line 226 of file NVPTXInstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), and I.
Referenced by getRegisterInfo().
The documentation for this class was generated from the following files:
NVPTXInstrInfo.h
NVPTXInstrInfo.cpp