LLVM: llvm::BinaryOperator Class Reference
LLVM API Documentation
llvm::BinaryOperator Class Reference
#include <InstrTypes.h>
Public Member Functions
void * operator new (size_t s)
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
DEFINE_HELPERS (Add, NSW) DEFINE_HELPERS(Add
NUW DEFINE_HELPERS (Sub, NSW) DEFINE_HELPERS(Sub
NUW NUW DEFINE_HELPERS (Mul, NSW) DEFINE_HELPERS(Mul
NUW NUW NUW DEFINE_HELPERS (Shl, NSW) DEFINE_HELPERS(Shl
NUW NUW NUW NUW DEFINE_HELPERS (SDiv, Exact) DEFINE_HELPERS(UDiv
NUW NUW NUW NUW Exact DEFINE_HELPERS (AShr, Exact) DEFINE_HELPERS(LShr
BinaryOps getOpcode () const
bool swapOperands ()
void setHasNoUnsignedWrap (bool b=true)
void setHasNoSignedWrap (bool b=true)
void setIsExact (bool b=true)
bool hasNoUnsignedWrap () const
hasNoUnsignedWrap - Determine whether the no unsigned wrap flag is set.
bool hasNoSignedWrap () const
hasNoSignedWrap - Determine whether the no signed wrap flag is set.
bool isExact () const
isExact - Determine whether the exact flag is set.
Public Member Functions inherited from llvm::Instruction
~Instruction ()
Instruction * use_back ()
const Instruction * use_back () const
const BasicBlock * getParent () const
BasicBlock * getParent ()
void removeFromParent ()
void eraseFromParent ()
void insertBefore (Instruction *InsertPos)
void insertAfter (Instruction *InsertPos)
void moveBefore (Instruction *MovePos)
unsigned getOpcode () const
getOpcode() returns a member of one of the enums like Instruction::Add.
const char * getOpcodeName () const
bool isTerminator () const
bool isBinaryOp () const
bool isShift ()
bool isCast () const
bool isLogicalShift () const
bool isArithmeticShift () const
isArithmeticShift - Return true if this is an arithmetic shift right.
bool hasMetadata () const
bool hasMetadataOtherThanDebugLoc () const
MDNode * getMetadata (unsigned KindID) const
MDNode * getMetadata (StringRef Kind) const
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
void getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
void setMetadata (unsigned KindID, MDNode *Node)
void setMetadata (StringRef Kind, MDNode *Node)
void setDebugLoc (const DebugLoc &Loc)
setDebugLoc - Set the debug location information for this instruction.
const DebugLoc & getDebugLoc () const
getDebugLoc - Return the debug location for this node as a DebugLoc.
void setHasUnsafeAlgebra (bool B)
void setHasNoNaNs (bool B)
void setHasNoInfs (bool B)
void setHasNoSignedZeros (bool B)
void setHasAllowReciprocal (bool B)
void setFastMathFlags (FastMathFlags FMF)
bool hasUnsafeAlgebra () const
Determine whether the unsafe-algebra flag is set.
bool hasNoNaNs () const
Determine whether the no-NaNs flag is set.
bool hasNoInfs () const
Determine whether the no-infs flag is set.
bool hasNoSignedZeros () const
Determine whether the no-signed-zeros flag is set.
bool hasAllowReciprocal () const
Determine whether the allow-reciprocal flag is set.
FastMathFlags getFastMathFlags () const
void copyFastMathFlags (const Instruction *I)
Copy I's fast-math flags.
bool isAssociative () const
bool isCommutative () const
bool isIdempotent () const
bool isNilpotent () const
bool mayWriteToMemory () const
bool mayReadFromMemory () const
bool mayReadOrWriteMemory () const
bool mayThrow () const
bool mayReturn () const
bool mayHaveSideEffects () const
Instruction * clone () const
bool isIdenticalTo (const Instruction *I) const
bool isIdenticalToWhenDefined (const Instruction *I) const
bool isSameOperationAs (const Instruction *I, unsigned flags=0) const
Determine if one instruction is the same operation as another.
bool isUsedOutsideOfBlock (const BasicBlock *BB) const
Public Member Functions inherited from llvm::User
~User ()
void operator delete (void *Usr)
operator delete - free memory allocated for User and Use objects
void operator delete (void *, unsigned)
placement delete - required by std, but never called.
void operator delete (void *, unsigned, bool)
placement delete - required by std, but never called.
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
void dropAllReferences ()
void replaceUsesOfWith (Value *From, Value *To)
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
dump - Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O, AssemblyAnnotationWriter *AAW=0) const
Type * getType () const
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
void setName (const Twine &Name)
void takeName (Value *V)
void replaceAllUsesWith (Value *V)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
User * use_back ()
const User * use_back () const
bool hasOneUse () const
bool hasNUses (unsigned N) const
bool hasNUsesOrMore (unsigned N) const
bool isUsedInBasicBlock (const BasicBlock *BB) const
unsigned getNumUses () const
void addUse (Use &U)
unsigned getValueID () const
unsigned getRawSubclassOptionalData () const
void clearSubclassOptionalData ()
bool hasSameSubclassOptionalData (const Value *V) const
void intersectOptionalDataWith (const Value *V)
bool hasValueHandle () const
Value * stripPointerCasts ()
Strips off any unneeded pointer casts, all-zero GEPs and aliases from the specified value, returning the original uncasted value.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strips off any unneeded pointer casts and all-zero GEPs from the specified value, returning the original uncasted value.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strips off unneeded pointer casts and all-constant GEPs from the specified value, returning the original pointer value.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Strips like stripInBoundsConstantOffsets but also accumulates the constant offset stripped.
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strips off unneeded pointer casts and any in-bounds offsets from the specified value, returning the original pointer value.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer () const
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Public Member Functions inherited from llvm::ilist_node< Instruction >
Instruction * getPrevNode ()
Get the previous node, or 0 for the list head.
const Instruction * getPrevNode () const
Get the previous node, or 0 for the list head.
Instruction * getNextNode ()
Get the next node, or 0 for the list tail.
const Instruction * getNextNode () const
Get the next node, or 0 for the list tail.
Static Public Member Functions
static BinaryOperator * Create (BinaryOps Op, Value *S1, Value *S2, const Twine &Name=Twine(), Instruction *InsertBefore=0)
static BinaryOperator * Create (BinaryOps Op, Value *S1, Value *S2, const Twine &Name, BasicBlock *InsertAtEnd)
static BinaryOperator * CreateNSW (BinaryOps Opc, Value *V1, Value *V2, const Twine &Name="")
static BinaryOperator * CreateNSW (BinaryOps Opc, Value *V1, Value *V2, const Twine &Name, BasicBlock *BB)
static BinaryOperator * CreateNSW (BinaryOps Opc, Value *V1, Value *V2, const Twine &Name, Instruction *I)
static BinaryOperator * CreateNUW (BinaryOps Opc, Value *V1, Value *V2, const Twine &Name="")
static BinaryOperator * CreateNUW (BinaryOps Opc, Value *V1, Value *V2, const Twine &Name, BasicBlock *BB)
static BinaryOperator * CreateNUW (BinaryOps Opc, Value *V1, Value *V2, const Twine &Name, Instruction *I)
static BinaryOperator * CreateExact (BinaryOps Opc, Value *V1, Value *V2, const Twine &Name="")
static BinaryOperator * CreateExact (BinaryOps Opc, Value *V1, Value *V2, const Twine &Name, BasicBlock *BB)
static BinaryOperator * CreateExact (BinaryOps Opc, Value *V1, Value *V2, const Twine &Name, Instruction *I)
NUW NUW NUW NUW Exact static Exact BinaryOperator * CreateNeg (Value *Op, const Twine &Name="", Instruction *InsertBefore=0)
static BinaryOperator * CreateNeg (Value *Op, const Twine &Name, BasicBlock *InsertAtEnd)
static BinaryOperator * CreateNSWNeg (Value *Op, const Twine &Name="", Instruction *InsertBefore=0)
static BinaryOperator * CreateNSWNeg (Value *Op, const Twine &Name, BasicBlock *InsertAtEnd)
static BinaryOperator * CreateNUWNeg (Value *Op, const Twine &Name="", Instruction *InsertBefore=0)
static BinaryOperator * CreateNUWNeg (Value *Op, const Twine &Name, BasicBlock *InsertAtEnd)
static BinaryOperator * CreateFNeg (Value *Op, const Twine &Name="", Instruction *InsertBefore=0)
static BinaryOperator * CreateFNeg (Value *Op, const Twine &Name, BasicBlock *InsertAtEnd)
static BinaryOperator * CreateNot (Value *Op, const Twine &Name="", Instruction *InsertBefore=0)
static BinaryOperator * CreateNot (Value *Op, const Twine &Name, BasicBlock *InsertAtEnd)
static bool isNeg (const Value *V)
static bool isFNeg (const Value *V, bool IgnoreZeroSign=false)
static bool isNot (const Value *V)
static const Value * getNegArgument (const Value *BinOp)
static Value * getNegArgument (Value *BinOp)
static const Value * getFNegArgument (const Value *BinOp)
static Value * getFNegArgument (Value *BinOp)
static const Value * getNotArgument (const Value *BinOp)
static Value * getNotArgument (Value *BinOp)
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Instruction
static const char * getOpcodeName (unsigned OpCode)
static bool isTerminator (unsigned OpCode)
static bool isBinaryOp (unsigned Opcode)
static bool isShift (unsigned Opcode)
Determine if the Opcode is one of the shift instructions.
static bool isCast (unsigned OpCode)
Determine if the OpCode is one of the CastInst instructions.
static bool isAssociative (unsigned op)
static bool isCommutative (unsigned op)
static bool isIdempotent (unsigned op)
static bool isNilpotent (unsigned op)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Protected Member Functions
void init (BinaryOps iType)
BinaryOperator (BinaryOps iType, Value *S1, Value *S2, Type *Ty, const Twine &Name, Instruction *InsertBefore)
BinaryOperator (BinaryOps iType, Value *S1, Value *S2, Type *Ty, const Twine &Name, BasicBlock *InsertAtEnd)
virtual BinaryOperator * clone_impl () const LLVM_OVERRIDE
Protected Member Functions inherited from llvm::Instruction
void setInstructionSubclassData (unsigned short D)
unsigned getSubclassDataFromInstruction () const
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, Instruction *InsertBefore=0)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, BasicBlock *InsertAtEnd)
Protected Member Functions inherited from llvm::User
void * operator new (size_t s, unsigned Us)
User (Type *ty, unsigned vty, Use *OpList, unsigned NumOps)
Use * allocHungoffUses (unsigned) const
void dropHungoffUses ()
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
virtual void printCustom (raw_ostream &O) const
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Member Functions inherited from llvm::ilist_node< Instruction >
ilist_node ()
Additional Inherited Members
Public Types inherited from llvm::Instruction
enum OperationEquivalenceFlags { CompareIgnoringAlignment = 1<<0, CompareUsingScalarTypes = 1<<1 }
enum TermOps
enum BinaryOps
enum MemoryOps
enum CastOps
enum OtherOps
Public Types inherited from llvm::User
typedef Use * op_iterator
typedef const Use * const_op_iterator
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal, BasicBlockVal, FunctionVal, GlobalAliasVal,
GlobalVariableVal, UndefValueVal, BlockAddressVal, ConstantExprVal,
ConstantAggregateZeroVal, ConstantDataArrayVal, ConstantDataVectorVal, ConstantIntVal,
ConstantFPVal, ConstantArrayVal, ConstantStructVal, ConstantVectorVal,
ConstantPointerNullVal, MDNodeVal, MDStringVal, InlineAsmVal,
PseudoSourceValueVal, FixedStackPseudoSourceValueVal, InstructionVal, ConstantFirstVal = FunctionVal,
ConstantLastVal = ConstantPointerNullVal
}
typedef value_use_iterator< User > use_iterator
typedef value_use_iterator< const User > const_use_iterator
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::User
Use * OperandList
unsigned NumOperands
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Detailed Description
Definition at line 138 of file InstrTypes.h.
Constructor & Destructor Documentation
BinaryOperator::BinaryOperator (BinaryOps iType, Value * S1, Value * S2, Type * Ty, const Twine & Name, Instruction * InsertBefore) protected
Definition at line 1732 of file Instructions.cpp.
References init(), and llvm::Value::setName().
Referenced by Create(), CreateFNeg(), CreateNeg(), and CreateNot().
BinaryOperator::BinaryOperator (BinaryOps iType, Value * S1, Value * S2, Type * Ty, const Twine & Name, BasicBlock * InsertAtEnd) protected
Definition at line 1745 of file Instructions.cpp.
References init(), and llvm::Value::setName().
Member Function Documentation
static bool llvm::BinaryOperator::classof (const Instruction * I) inline static
Definition at line 362 of file InstrTypes.h.
References llvm::Instruction::isBinaryOp().
static bool llvm::BinaryOperator::classof (const Value * V) inline static
Definition at line 365 of file InstrTypes.h.
References llvm::TerminatorInst::classof().
BinaryOperator * BinaryOperator::clone_impl () const protected virtual
Implements llvm::Instruction.
Definition at line 3515 of file Instructions.cpp.
References llvm::CmpInst::Create(), and llvm::CmpInst::getOpcode().
BinaryOperator * BinaryOperator::Create (BinaryOps Op, Value * S1, Value * S2, const Twine & Name = Twine(), Instruction * InsertBefore = 0) static
Create() - Construct a binary instruction, given the opcode and the two operands. Optionally (if InstBefore is specified) insert the instruction into a BasicBlock right before the specified instruction. The specified Instruction is allowed to be a dereferenced end iterator.
Definition at line 1834 of file Instructions.cpp.
References BinaryOperator(), and llvm::Value::getType().
Referenced by BuildNew(), ClearSubclassDataAfterReassociation(), llvm::InstCombiner::commonIDivTransforms(), Create(), llvm::NoFolder::CreateBinOp(), llvm::IRBuilder< true, TargetFolder >::CreateBinOp(), llvm::CastInst::CreateFPCast(), llvm::CastInst::CreateIntegerCast(), llvm::CastInst::CreatePointerCast(), llvm::CastInst::CreateSExtOrBitCast(), llvm::CastInst::CreateTruncOrBitCast(), llvm::IRBuilder< true, TargetFolder >::CreateUnreachable(), llvm::CastInst::CreateZExtOrBitCast(), DecomposeSimpleLinearExpr(), FindScalarElement(), llvm::InstCombiner::FoldSelectIntoOp(), llvm::InstCombiner::FoldSelectOpOp(), llvm::InstCombiner::FoldShiftByConstant(), FunctionNumber(), llvm::ConstantExpr::getAsInstruction(), isAlwaysFoldable(), isLoopInvariant(), isSafeAndProfitableToSinkLoad(), LinearizeExprTree(), llvm::BitcodeReader::ParseTriple(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitFPTrunc(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitXor(), and llvm::InstCombiner::visitZExt().
BinaryOperator * BinaryOperator::Create (BinaryOps Op, Value * S1, Value * S2, const Twine & Name, BasicBlock * InsertAtEnd) static
Create() - Construct a binary instruction, given the opcode and the two operands. Also automatically insert this instruction to the end of the BasicBlock specified.
Definition at line 1842 of file Instructions.cpp.
References Create(), llvm::BasicBlock::getInstList(), and llvm::iplist< NodeTy, Traits >::push_back().
static BinaryOperator* llvm::BinaryOperator::CreateExact (BinaryOps Opc, Value * V1, Value * V2, const Twine & Name = "") inline static
Definition at line 232 of file InstrTypes.h.
References setIsExact().
static BinaryOperator* llvm::BinaryOperator::CreateExact (BinaryOps Opc, Value * V1, Value * V2, const Twine & Name, BasicBlock * BB) inline static
Definition at line 238 of file InstrTypes.h.
References setIsExact().
static BinaryOperator* llvm::BinaryOperator::CreateExact (BinaryOps Opc, Value * V1, Value * V2, const Twine & Name, Instruction * I) inline static
Definition at line 244 of file InstrTypes.h.
References setIsExact().
BinaryOperator * BinaryOperator::CreateFNeg (Value * Op, const Twine & Name = "", Instruction * InsertBefore = 0) static
Definition at line 1890 of file Instructions.cpp.
References BinaryOperator(), llvm::Value::getType(), llvm::ConstantFP::getZeroValueForNegation(), and zero().
Referenced by llvm::NoFolder::CreateFNeg(), llvm::IRBuilder< true, TargetFolder >::CreateFNeg(), and llvm::InstCombiner::visitFPTrunc().
BinaryOperator * BinaryOperator::CreateFNeg (Value * Op, const Twine & Name, BasicBlock * InsertAtEnd) static
Definition at line 1897 of file Instructions.cpp.
References BinaryOperator(), llvm::Value::getType(), llvm::ConstantFP::getZeroValueForNegation(), and zero().
BinaryOperator * BinaryOperator::CreateNeg (Value * Op, const Twine & Name = "", Instruction * InsertBefore = 0) static
Helper functions to construct and inspect unary operations (NEG and NOT) via binary operators SUB and XOR:
CreateNeg, CreateNot - Create the NEG and NOT instructions out of SUB and XOR instructions.
Definition at line 1850 of file Instructions.cpp.
References BinaryOperator(), llvm::Value::getType(), llvm::ConstantFP::getZeroValueForNegation(), and zero().
Referenced by llvm::NoFolder::CreateNeg(), llvm::IRBuilder< true, TargetFolder >::CreateNeg(), EmitAddTreeOfValues(), NegateValue(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitSDiv(), and llvm::InstCombiner::visitSub().
BinaryOperator * BinaryOperator::CreateNeg (Value * Op, const Twine & Name, BasicBlock * InsertAtEnd) static
Definition at line 1858 of file Instructions.cpp.
References BinaryOperator(), llvm::Value::getType(), llvm::ConstantFP::getZeroValueForNegation(), and zero().
BinaryOperator * BinaryOperator::CreateNot (Value * Op, const Twine & Name = "", Instruction * InsertBefore = 0) static
Definition at line 1904 of file Instructions.cpp.
References BinaryOperator(), llvm::Constant::getAllOnesValue(), llvm::Value::getType(), and llvm::APIntOps::Xor().
Referenced by llvm::NoFolder::CreateNot(), llvm::IRBuilder< true, TargetFolder >::CreateNot(), OptimizeGlobalAddressOfMalloc(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithCastAndCast(), llvm::InstCombiner::visitOr(), and llvm::InstCombiner::visitSub().
BinaryOperator * BinaryOperator::CreateNot (Value * Op, const Twine & Name, BasicBlock * InsertAtEnd) static
Definition at line 1911 of file Instructions.cpp.
References BinaryOperator(), llvm::Constant::getAllOnesValue(), llvm::Value::getType(), and llvm::APIntOps::Xor().
static BinaryOperator* llvm::BinaryOperator::CreateNSW (BinaryOps Opc, Value * V1, Value * V2, const Twine & Name = "") inline static
Definition at line 194 of file InstrTypes.h.
References setHasNoSignedWrap().
static BinaryOperator* llvm::BinaryOperator::CreateNSW (BinaryOps Opc, Value * V1, Value * V2, const Twine & Name, BasicBlock * BB) inline static
Definition at line 200 of file InstrTypes.h.
References setHasNoSignedWrap().
static BinaryOperator* llvm::BinaryOperator::CreateNSW (BinaryOps Opc, Value * V1, Value * V2, const Twine & Name, Instruction * I) inline static
Definition at line 206 of file InstrTypes.h.
References setHasNoSignedWrap().
BinaryOperator * BinaryOperator::CreateNSWNeg (Value * Op, const Twine & Name = "", Instruction * InsertBefore = 0) static
Definition at line 1866 of file Instructions.cpp.
References llvm::Value::getType(), llvm::ConstantFP::getZeroValueForNegation(), and zero().
Referenced by llvm::NoFolder::CreateNSWNeg().
BinaryOperator * BinaryOperator::CreateNSWNeg (Value * Op, const Twine & Name, BasicBlock * InsertAtEnd) static
Definition at line 1872 of file Instructions.cpp.
References llvm::Value::getType(), llvm::ConstantFP::getZeroValueForNegation(), and zero().
static BinaryOperator* llvm::BinaryOperator::CreateNUW (BinaryOps Opc, Value * V1, Value * V2, const Twine & Name = "") inline static
Definition at line 213 of file InstrTypes.h.
References setHasNoUnsignedWrap().
static BinaryOperator* llvm::BinaryOperator::CreateNUW (BinaryOps Opc, Value * V1, Value * V2, const Twine & Name, BasicBlock * BB) inline static
Definition at line 219 of file InstrTypes.h.
References setHasNoUnsignedWrap().
static BinaryOperator* llvm::BinaryOperator::CreateNUW (BinaryOps Opc, Value * V1, Value * V2, const Twine & Name, Instruction * I) inline static
Definition at line 225 of file InstrTypes.h.
References setHasNoUnsignedWrap().
BinaryOperator * BinaryOperator::CreateNUWNeg (Value * Op, const Twine & Name = "", Instruction * InsertBefore = 0) static
Definition at line 1878 of file Instructions.cpp.
References llvm::Value::getType(), llvm::ConstantFP::getZeroValueForNegation(), and zero().
Referenced by llvm::NoFolder::CreateNUWNeg().
BinaryOperator * BinaryOperator::CreateNUWNeg (Value * Op, const Twine & Name, BasicBlock * InsertAtEnd) static
Definition at line 1884 of file Instructions.cpp.
References llvm::Value::getType(), llvm::ConstantFP::getZeroValueForNegation(), and zero().
llvm::BinaryOperator::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Transparently provide more efficient getOperand methods.
llvm::BinaryOperator::DEFINE_HELPERS (Add , NSW)
NUW llvm::BinaryOperator::DEFINE_HELPERS (Sub , NSW)
NUW NUW llvm::BinaryOperator::DEFINE_HELPERS (Mul , NSW)
NUW NUW NUW llvm::BinaryOperator::DEFINE_HELPERS (Shl , NSW)
NUW NUW NUW NUW llvm::BinaryOperator::DEFINE_HELPERS (SDiv , Exact)
NUW NUW NUW NUW Exact llvm::BinaryOperator::DEFINE_HELPERS (AShr , Exact)
const Value * BinaryOperator::getFNegArgument (const Value * BinOp) static
Definition at line 1965 of file Instructions.cpp.
Referenced by llvm::FastISel::FastEmitBranch(), and RightDistributesOverLeft().
Value * BinaryOperator::getFNegArgument (Value * BinOp) static
Definition at line 1961 of file Instructions.cpp.
References llvm::User::getOperand().
const Value * BinaryOperator::getNegArgument (const Value * BinOp) static
getNegArgument, getNotArgument - Helper functions to extract the unary argument of a NEG, FNEG or NOT operation implemented via Sub, FSub, or Xor.
Definition at line 1957 of file Instructions.cpp.
Referenced by createAndInstr(), and RightDistributesOverLeft().
Value * BinaryOperator::getNegArgument (Value * BinOp) static
Definition at line 1953 of file Instructions.cpp.
References llvm::User::getOperand().
const Value * BinaryOperator::getNotArgument (const Value * BinOp) static
Definition at line 1980 of file Instructions.cpp.
Referenced by dyn_castNotVal(), OptimizeAndOrXor(), and llvm::InstCombiner::visitSelectInst().
Value * BinaryOperator::getNotArgument (Value * BinOp) static
Definition at line 1969 of file Instructions.cpp.
References llvm::User::getOperand(), isConstantAllOnes(), and isNot().
BinaryOps llvm::BinaryOperator::getOpcode () const inline
Definition at line 326 of file InstrTypes.h.
References b, and llvm::Instruction::getOpcode().
Referenced by buildMultiplyTree(), ClearSubclassDataAfterReassociation(), llvm::InstCombiner::commonIDivTransforms(), ConvertToSInt(), createPrivateNonConstGlobalForString(), cse(), llvm::expandDivision(), llvm::expandDivisionUpTo32Bits(), llvm::expandRemainder(), llvm::expandRemainderUpTo32Bits(), FactorizeBinOp(), FindScalarElement(), llvm::InstCombiner::FoldICmpDivCst(), llvm::InstCombiner::FoldICmpShrCst(), llvm::InstCombiner::FoldOrOfICmps(), llvm::InstCombiner::FoldSelectIntoOp(), llvm::InstCombiner::FoldShiftByConstant(), llvm::CastInst::isIntegerCast(), isLoopInvariant(), llvm::CastInst::isLosslessCast(), llvm::CastInst::isNoopCast(), isSafeAndProfitableToSinkLoad(), LinearizeExprTree(), MaintainNoSignedWrap(), matchPairwiseReduction(), matchPairwiseReductionAtLevel(), matchVectorSplittingReduction(), RightDistributesOverLeft(), SimplifyAssociativeBinOp(), SimplifyICmpInst(), swapMayExposeCSEOpportunities(), llvm::Interpreter::visitBinaryOperator(), llvm::InstCombiner::visitFPTrunc(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitXor(), and llvm::InstCombiner::visitZExt().
bool BinaryOperator::hasNoSignedWrap () const
hasNoSignedWrap - Determine whether the no signed wrap flag is set.
Definition at line 2013 of file Instructions.cpp.
Referenced by BuildNew(), ClearSubclassDataAfterReassociation(), cse(), llvm::InstCombiner::FoldSelectIntoOp(), llvm::InstCombiner::FoldShiftByConstant(), llvm::DenseMapInfo< SimpleValue >::getTombstoneKey(), patchReplacementInstruction(), ShrinkDemandedConstant(), SimplifyICmpInst(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitShl(), and llvm::InstCombiner::visitSub().
bool BinaryOperator::hasNoUnsignedWrap () const
hasNoUnsignedWrap - Determine whether the no unsigned wrap flag is set.
Definition at line 2009 of file Instructions.cpp.
Referenced by BuildNew(), cse(), llvm::InstCombiner::FoldSelectIntoOp(), llvm::InstCombiner::FoldShiftByConstant(), llvm::DenseMapInfo< SimpleValue >::getTombstoneKey(), patchReplacementInstruction(), ShrinkDemandedConstant(), SimplifyICmpInst(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitShl(), and llvm::InstCombiner::visitSub().
void BinaryOperator::init (BinaryOps iType) protected
Definition at line 1759 of file Instructions.cpp.
References llvm::APIntOps::And(), llvm::User::getOperand(), llvm::Value::getType(), llvm::APIntOps::Or(), and llvm::APIntOps::Xor().
Referenced by BinaryOperator().
bool BinaryOperator::isExact () const
isExact - Determine whether the exact flag is set.
Definition at line 2017 of file Instructions.cpp.
Referenced by BuildNew(), cse(), llvm::InstCombiner::FoldICmpDivCst(), llvm::InstCombiner::FoldICmpShrCst(), llvm::InstCombiner::FoldSelectIntoOp(), llvm::InstCombiner::FoldShiftByConstant(), foldUDivPow2Cst(), foldUDivShl(), SimplifyICmpInst(), llvm::InstCombiner::visitAShr(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitLShr(), llvm::InstCombiner::visitSDiv(), and llvm::InstCombiner::visitUDiv().
bool BinaryOperator::isFNeg (const Value * V, bool IgnoreZeroSign = false) static
Definition at line 1934 of file Instructions.cpp.
References llvm::Instruction::hasNoSignedZeros().
Referenced by llvm::getComplexity(), RightDistributesOverLeft(), llvm::FastISel::SelectOperator(), llvm::InstCombiner::visitFMul(), and llvm::InstCombiner::visitFPTrunc().
bool BinaryOperator::isNeg (const Value * V) static
isNeg, isFNeg, isNot - Check if the given Value is a NEG, FNeg, or NOT instruction.
Definition at line 1926 of file Instructions.cpp.
Referenced by buildMultiplyTree(), createAndInstr(), llvm::getComplexity(), isUnmovableInstruction(), LinearizeExprTree(), NegateValue(), RightDistributesOverLeft(), and ShouldBreakUpSubtract().
bool BinaryOperator::isNot (const Value * V) static
Definition at line 1945 of file Instructions.cpp.
References isConstantAllOnes(), and llvm::APIntOps::Xor().
Referenced by dyn_castNotVal(), llvm::getComplexity(), getNotArgument(), isFreeToInvert(), isUnmovableInstruction(), OptimizeAndOrXor(), and llvm::InstCombiner::visitSelectInst().
void* llvm::BinaryOperator::operator new (size_t s) inline
Definition at line 149 of file InstrTypes.h.
References DECLARE_TRANSPARENT_OPERAND_ACCESSORS, llvm::User::Op(), and s.
void BinaryOperator::setHasNoSignedWrap (bool b = true)
setHasNoSignedWrap - Set or clear the nsw flag on this instruction, which must be an operator which supports this flag. See LangRef.html for the meaning of this flag.
Definition at line 2001 of file Instructions.cpp.
Referenced by ClearSubclassDataAfterReassociation(), llvm::NoFolder::CreateAdd(), llvm::NoFolder::CreateMul(), llvm::NoFolder::CreateNeg(), CreateNSW(), llvm::NoFolder::CreateShl(), llvm::NoFolder::CreateSub(), llvm::IRBuilder< true, TargetFolder >::CreateUnreachable(), cse(), llvm::InstCombiner::FoldShiftByConstant(), llvm::ConstantExpr::getAsInstruction(), GetShiftedValue(), isSafeAndProfitableToSinkLoad(), patchReplacementInstruction(), llvm::PHITransAddr::PHITranslateWithInsertion(), ShrinkDemandedConstant(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitShl(), and llvm::InstCombiner::visitSub().
void BinaryOperator::setHasNoUnsignedWrap (bool b = true)
setHasNoUnsignedWrap - Set or clear the nsw flag on this instruction, which must be an operator which supports this flag. See LangRef.html for the meaning of this flag.
Definition at line 1997 of file Instructions.cpp.
Referenced by llvm::NoFolder::CreateAdd(), llvm::NoFolder::CreateMul(), llvm::NoFolder::CreateNeg(), CreateNUW(), llvm::NoFolder::CreateShl(), llvm::NoFolder::CreateSub(), llvm::IRBuilder< true, TargetFolder >::CreateUnreachable(), cse(), llvm::InstCombiner::FoldShiftByConstant(), llvm::ConstantExpr::getAsInstruction(), GetShiftedValue(), isSafeAndProfitableToSinkLoad(), llvm::PHITransAddr::PHITranslateWithInsertion(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitShl(), and llvm::InstCombiner::visitSub().
void BinaryOperator::setIsExact (bool b = true)
setIsExact - Set or clear the exact flag on this instruction, which must be an operator which supports this flag. See LangRef.html for the meaning of this flag.
Definition at line 2005 of file Instructions.cpp.
Referenced by CreateExact(), cse(), llvm::InstCombiner::FoldSelectIntoOp(), llvm::InstCombiner::FoldShiftByConstant(), foldUDivPow2Cst(), foldUDivShl(), llvm::ConstantExpr::getAsInstruction(), GetShiftedValue(), isSafeAndProfitableToSinkLoad(), ShrinkDemandedConstant(), llvm::InstCombiner::visitAShr(), and llvm::InstCombiner::visitLShr().
bool BinaryOperator::swapOperands ()
swapOperands - Exchange the two operands to this instruction. This instruction is safe to use on any binary instruction and does not modify the semantics of the instruction. If the instruction cannot be reversed (ie, it's a Div), then return true.
Definition at line 1990 of file Instructions.cpp.
References llvm::Instruction::isCommutative(), and llvm::swap().
Referenced by ClearSubclassDataAfterReassociation(), LinearizeExprTree(), and llvm::InstCombiner::visitXor().
The documentation for this class was generated from the following files:
InstrTypes.h
Instructions.cpp