LLVM: llvm::SmallPtrSet< PtrType, SmallSize > Class Template Reference
LLVM API Documentation
llvm::SmallPtrSet< PtrType, SmallSize > Class Template Reference
#include <SmallPtrSet.h>
Public Types
typedef SmallPtrSetIterator< PtrType > iterator
typedef SmallPtrSetIterator< PtrType > const_iterator
Public Member Functions
SmallPtrSet ()
SmallPtrSet (const SmallPtrSet &that)
template<typename It >
SmallPtrSet (It I, It E)
bool insert (PtrType Ptr)
bool erase (PtrType Ptr)
bool count (PtrType Ptr) const
count - Return true if the specified pointer is in the set.
template<typename IterT >
void insert (IterT I, IterT E)
iterator begin () const
iterator end () const
const SmallPtrSet< PtrType, SmallSize > & operator= (const SmallPtrSet< PtrType, SmallSize > &RHS)
void swap (SmallPtrSet< PtrType, SmallSize > &RHS)
swap - Swaps the elements of two sets.
Public Member Functions inherited from llvm::SmallPtrSetImpl
bool LLVM_ATTRIBUTE_UNUSED_RESULT empty () const
unsigned size () const
void clear ()
Additional Inherited Members
Protected Member Functions inherited from llvm::SmallPtrSetImpl
SmallPtrSetImpl (const void **SmallStorage, const SmallPtrSetImpl &that)
SmallPtrSetImpl (const void **SmallStorage, unsigned SmallSize)
~SmallPtrSetImpl ()
bool insert_imp (const void *Ptr)
bool erase_imp (const void *Ptr)
bool count_imp (const void *Ptr) const
void swap (SmallPtrSetImpl &RHS)
void CopyFrom (const SmallPtrSetImpl &RHS)
Static Protected Member Functions inherited from llvm::SmallPtrSetImpl
static void * getTombstoneMarker ()
static void * getEmptyMarker ()
Protected Attributes inherited from llvm::SmallPtrSetImpl
const void ** SmallArray
SmallArray - Points to a fixed size set of buckets, used in 'small mode'.
const void ** CurArray
unsigned CurArraySize
CurArraySize - The allocated size of CurArray, always a power of two.
unsigned NumElements
unsigned NumTombstones
Detailed Description
template<class PtrType, unsigned SmallSize>
class llvm::SmallPtrSet< PtrType, SmallSize >
SmallPtrSet - This class implements a set which is optimized for holding SmallSize or less elements. This internally rounds up SmallSize to the next power of two if it is not already a power of two. See the comments above SmallPtrSetImpl for details of the algorithm.
Definition at line 236 of file SmallPtrSet.h.
Member Typedef Documentation
template<class PtrType, unsigned SmallSize> typedef SmallPtrSetIterator<PtrType> llvm::SmallPtrSet< PtrType, SmallSize >::const_iterator
Definition at line 275 of file SmallPtrSet.h.
template<class PtrType, unsigned SmallSize> typedef SmallPtrSetIterator<PtrType> llvm::SmallPtrSet< PtrType, SmallSize >::iterator
Definition at line 274 of file SmallPtrSet.h.
Constructor & Destructor Documentation
template<class PtrType, unsigned SmallSize> llvm::SmallPtrSet< PtrType, SmallSize >::SmallPtrSet () inline
Definition at line 243 of file SmallPtrSet.h.
template<class PtrType, unsigned SmallSize> llvm::SmallPtrSet< PtrType, SmallSize >::SmallPtrSet (const SmallPtrSet< PtrType, SmallSize > & that) inline
Definition at line 244 of file SmallPtrSet.h.
template<class PtrType, unsigned SmallSize> template<typename It > llvm::SmallPtrSet< PtrType, SmallSize >::SmallPtrSet (It I, It E) inline
Definition at line 247 of file SmallPtrSet.h.
Member Function Documentation
template<class PtrType, unsigned SmallSize> iterator llvm::SmallPtrSet< PtrType, SmallSize >::begin () const inline
Definition at line 276 of file SmallPtrSet.h.
Referenced by accumulateAndSortLibcalls(), AllGlobalLoadUsesSimpleEnoughForHeapSRA(), llvm::PMTopLevelManager::collectLastUses(), llvm::ObjectSizeOffsetEvaluator::compute(), ConvertAtomicSynchScope(), llvm::createCodeGenPreparePass(), llvm::JIT::createJIT(), llvm::createLoopSimplifyPass(), llvm::createObjCARCOptPass(), DeleteTriviallyDeadInstructions(), llvm::objcarc::FindDependencies(), llvm::findPHICopyInsertPoint(), FindPredecessorAutoreleaseWithSafePath(), FindPredecessorRetainWithSafePath(), llvm::InlineFunction(), isAlwaysFoldable(), isProfitableChain(), isSafeToMove(), MarkBlocksLiveIn(), matchPair(), llvm::SelectionDAG::MorphNodeTo(), promoteSingleBlockAlloca(), llvm::MemoryDependenceAnalysis::removeInstruction(), llvm::ARMTargetLowering::ReplaceNodeResults(), setUsedInitializer(), shouldInternalize(), sortOpts(), and llvm::LLVMContextImpl::~LLVMContextImpl().
template<class PtrType, unsigned SmallSize> bool llvm::SmallPtrSet< PtrType, SmallSize >::count (PtrType Ptr) const inline
count - Return true if the specified pointer is in the set.
Definition at line 264 of file SmallPtrSet.h.
Referenced by AddressIsTaken(), AdjustStackOffset(), AllGlobalLoadUsesSimpleEnoughForHeapSRA(), areAllUsesIn(), bothUsedInPHI(), llvm::DominanceFrontier::calculate(), CanPropagatePredecessorsForPHIs(), llvm::DomTreeNodeBase< llvm::MachineBasicBlock >::compare(), ComputePostOrders(), concatenateMemOperands(), llvm::LoopBase< BasicBlock, Loop >::contains(), llvm::createCodeGenPreparePass(), llvm::createFunctionAttrsPass(), llvm::createLICMPass(), llvm::createPruneEHPass(), DeleteTriviallyDeadInstructions(), determinePointerReadAttrs(), llvm::LiveRangeEdit::didRematerialize(), DominatesMergePoint(), llvm::InstCombiner::DoOneIteration(), dumpMachineInstrRangeWithSlotIndex(), llvm::objcarc::FindDependencies(), llvm::FindFunctionBackedges(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::findNearestCommonDominator(), llvm::findPHICopyInsertPoint(), FoldTwoEntryPHINode(), getArrayElements(), getBlockNum(), getDebugLocEntry(), hasAddressTakenAndUsed(), hasMultipleUsesOf(), hasOutsideLoopUser(), llvm::SDNode::hasPredecessorHelper(), INITIALIZE_PASS(), INITIALIZE_PASS_BEGIN(), llvm::SparseSolver::isBlockExecutable(), isContiguous(), llvm::IVUsers::isIVUserOrOperand(), isLifetimeStart(), isProfitableToFoldUnconditional(), IsSafeAndProfitableToMove(), isSimplifiedLoopNest(), llvm::ShuffleVectorSDNode::isSplatMask(), llvm::MCAssembler::isThumbFunc(), llvm::MachineModuleInfo::isUsedFunction(), LinearizeExprTree(), LowerInterruptReturn(), MarkBlocksLiveIn(), MarkIndicesSafe(), matchPair(), operator<<(), promoteSingleBlockAlloca(), regsAreCompatible(), llvm::removeUnreachableBlocks(), llvm::LiveVariables::runOnMachineFunction(), SafeToMergeTerminators(), setUsedInitializer(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), StripSymbolNames(), llvm::InstCombiner::visitLandingPadInst(), and llvm::JITMemoryManager::~JITMemoryManager().
template<class PtrType, unsigned SmallSize> iterator llvm::SmallPtrSet< PtrType, SmallSize >::end () const inline
Definition at line 279 of file SmallPtrSet.h.
Referenced by accumulateAndSortLibcalls(), AllGlobalLoadUsesSimpleEnoughForHeapSRA(), llvm::PMTopLevelManager::collectLastUses(), llvm::ObjectSizeOffsetEvaluator::compute(), ConvertAtomicSynchScope(), llvm::JIT::createJIT(), llvm::createLoopSimplifyPass(), DeleteTriviallyDeadInstructions(), llvm::objcarc::FindDependencies(), llvm::InlineFunction(), isAlwaysFoldable(), isProfitableChain(), isSafeToMove(), MarkBlocksLiveIn(), llvm::SelectionDAG::MorphNodeTo(), promoteSingleBlockAlloca(), llvm::MemoryDependenceAnalysis::removeInstruction(), llvm::ARMTargetLowering::ReplaceNodeResults(), setUsedInitializer(), shouldInternalize(), sortOpts(), and llvm::LLVMContextImpl::~LLVMContextImpl().
template<class PtrType, unsigned SmallSize> bool llvm::SmallPtrSet< PtrType, SmallSize >::erase (PtrType Ptr) inline
erase - If the set contains the specified pointer, remove it and return true, otherwise return false.
Definition at line 259 of file SmallPtrSet.h.
Referenced by ComputePostOrders(), llvm::createCodeGenPreparePass(), llvm::JIT::createJIT(), llvm::FindFunctionBackedges(), llvm::FoldBranchToCommonDest(), getCopyOrBitcastDefUseIdx(), isLocalCopy(), isOneUseSetCC(), llvm::ShuffleVectorSDNode::isSplatMask(), matchPair(), llvm::LoopBase< BasicBlock, Loop >::removeBlockFromLoop(), setUsedInitializer(), and llvm::LLVMContext::~LLVMContext().
template<class PtrType, unsigned SmallSize> bool llvm::SmallPtrSet< PtrType, SmallSize >::insert (PtrType Ptr) inline
insert - This returns true if the pointer was new to the set, false if it was already in the set.
Definition at line 253 of file SmallPtrSet.h.
Referenced by llvm::LoopBase< BasicBlock, Loop >::addBlockEntry(), AddReachableCodeToWorklist(), AddressIsTaken(), llvm::IVUsers::AddUsersImpl(), AllUsesOfValueWillTrapIfNull(), analyzeGlobalAux(), areAllUsesIn(), AreAnyUnderlyingObjectsAnAlloca(), buildMultiplyTree(), llvm::DominanceFrontier::calculate(), llvm::VirtRegAuxInfo::calculateSpillWeightAndHint(), canTrapImpl(), llvm::collectUsedGlobalVariables(), CommitValueTo(), llvm::DomTreeNodeBase< llvm::MachineBasicBlock >::compare(), LTOCodeGenerator::compile(), llvm::ObjectSizeOffsetEvaluator::compute(), ComputePostOrders(), concatenateMemOperands(), ConstantFoldConstantExpressionImpl(), ConvertAtomicSynchScope(), llvm::MachineBasicBlock::CorrectExtraCFGEdges(), llvm::createArgumentPromotionPass(), llvm::createCodeGenPreparePass(), llvm::createFunctionAttrsPass(), llvm::JIT::createJIT(), llvm::createLICMPass(), llvm::createLoopDeletionPass(), llvm::createLoopInstSimplifyPass(), llvm::createLoopSimplifyPass(), llvm::createPruneEHPass(), cxxDtorIsEmpty(), DeadPHICycle(), DeleteTriviallyDeadInstructions(), llvm::SCEVAddRecExpr::delinearize(), determinePointerReadAttrs(), DominatesMergePoint(), dumpMachineInstrRangeWithSlotIndex(), DumpNodesr(), llvm::AsmPrinter::EmitJumpTableInfo(), llvm::DwarfDebug::endFunction(), llvm::DwarfDebug::endModule(), enqueueUsersInWorklist(), llvm::Eval(), llvm::CodeExtractor::extractCodeRegion(), llvm::FastISel::FastEmitZExtFromI1(), llvm::DIBuilder::finalize(), FindBaseOffset(), llvm::objcarc::FindDependencies(), llvm::FindFunctionBackedges(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::findNearestCommonDominator(), findNonImmUse(), llvm::findPHICopyInsertPoint(), FindUsedValues(), findUsedValues(), llvm::FoldBranchToCommonDest(), llvm::ScalarEvolution::forgetLoop(), llvm::ScalarEvolution::forgetValue(), FunctionNumber(), getAdjustedPtr(), getBlockNum(), getCopyOrBitcastDefUseIdx(), getDebugLocEntry(), getFPReg(), getInputChainForNode(), llvm::LexicalScopes::getMachineBasicBlocks(), llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), GetStringLengthH(), getUnderlyingObjects(), llvm::GetUnderlyingObjects(), HandleInlinedInvoke(), hasAddressTakenAndUsed(), hasConcreteDef(), hasConcreteDefImpl(), llvm::SDNode::hasPredecessorHelper(), llvm::SCEVExpander::hoistIVInc(), INITIALIZE_PASS(), INITIALIZE_PASS_BEGIN(), llvm::PMTopLevelManager::initializeAllAnalysisInfo(), InlineCallIfPossible(), insertVector(), isAlwaysFoldable(), llvm::CoalescerPair::isCoalescable(), isContiguous(), isDereferenceablePointer(), isFullCopyOf(), isHighCostExpansion(), isLessConstraining(), isLifetimeStart(), IsNonLocalValue(), isOnlyUsedInEntryBlock(), isProfitableChain(), isSafeToMove(), isSimpleEnoughValueToCommit(), isSimplifiedLoopNest(), isSourceDefinedByImplicitDef(), llvm::ShuffleVectorSDNode::isSplatMask(), IsStoredObjCPointer(), llvm::Constant::isThreadDependent(), isZero(), iterateChainSucc(), LinearizeExprTree(), LoadUsesSimpleEnoughForHeapSRA(), llvm::LoopBase< BasicBlock, Loop >::LoopBase(), LowerInterruptReturn(), markAliveBlocks(), MarkBlocksLiveIn(), llvm::LiveRangeEdit::markRematerialized(), matchPair(), MergeAliasResults(), llvm::SelectionDAG::MorphNodeTo(), operator<<(), OptimizeCmpExpression(), PHIsEqualValue(), ProfitableToMerge(), promoteSingleBlockAlloca(), PushDefUseChildren(), pushIVUsers(), PushLoopPHIs(), llvm::RecursivelyDeleteDeadPHINode(), regsAreCompatible(), RemoveDeadConstant(), removeFinishedSplitUses(), RemoveUnusedGlue(), llvm::LiveRange::RenumberValues(), llvm::ARMTargetLowering::ReplaceNodeResults(), llvm::GlobalAlias::resolveAliasedGlobal(), llvm::SelectionDAGISel::runOnMachineFunction(), setUsedInitializer(), llvm::LiveIntervals::shrinkToUses(), AllocaSlices::SliceBuilder::SliceBuilder(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), sortOpts(), llvm::Value::stripAndAccumulateInBoundsConstantOffsets(), stripAndComputeConstantOffsets(), SwitchToLookupTable(), llvm::LiveIntervals::HMEditor::updateAllRanges(), ValueIsOnlyUsedLocallyOrStoredToOneGlobal(), ValuesOverlap(), llvm::LoopBase< BlockT, LoopT >::verifyLoop(), llvm::InstCombiner::visitLandingPadInst(), llvm::InstCombiner::visitPHINode(), llvm::JITMemoryManager::~JITMemoryManager(), and llvm::LLVMContext::~LLVMContext().
template<class PtrType, unsigned SmallSize> template<typename IterT > void llvm::SmallPtrSet< PtrType, SmallSize >::insert (IterT I, IterT E) inline
Definition at line 269 of file SmallPtrSet.h.
template<class PtrType, unsigned SmallSize> const SmallPtrSet<PtrType, SmallSize>& llvm::SmallPtrSet< PtrType, SmallSize >::operator= (const SmallPtrSet< PtrType, SmallSize > & RHS) inline
Definition at line 286 of file SmallPtrSet.h.
template<class PtrType, unsigned SmallSize> void llvm::SmallPtrSet< PtrType, SmallSize >::swap (SmallPtrSet< PtrType, SmallSize > & RHS) inline
swap - Swaps the elements of two sets.
Definition at line 292 of file SmallPtrSet.h.
Referenced by std::swap().
The documentation for this class was generated from the following file:
SmallPtrSet.h