LLVM: llvm::LexicalScopes Class Reference
LLVM API Documentation
llvm::LexicalScopes Class Reference
#include <LexicalScopes.h>
Public Member Functions
LexicalScopes ()
virtual ~LexicalScopes ()
virtual void initialize (const MachineFunction &)
initialize - Scan machine function and constuct lexical scope nest.
virtual void releaseMemory ()
releaseMemory - release memory.
bool empty ()
empty - Return true if there is any lexical scope information available.
bool isCurrentFunctionScope (const LexicalScope *LS)
LexicalScope * getCurrentFunctionScope () const
getCurrentFunctionScope - Return lexical scope for the current function.
void getMachineBasicBlocks (DebugLoc DL, SmallPtrSet< const MachineBasicBlock *, 4 > &MBBs)
bool dominates (DebugLoc DL, MachineBasicBlock *MBB)
LexicalScope * findLexicalScope (DebugLoc DL)
ArrayRef< LexicalScope * > getAbstractScopesList () const
getAbstractScopesList - Return a reference to list of abstract scopes.
LexicalScope * findAbstractScope (const MDNode *N)
findAbstractScope - Find an abstract scope or return NULL.
LexicalScope * findInlinedScope (DebugLoc DL)
LexicalScope * findLexicalScope (const MDNode *N)
findLexicalScope - Find regular lexical scope or return NULL.
void dump ()
dump - Print data structures to dbgs().
Detailed Description
LexicalScopes - This class provides interface to collect and use lexical scoping information from machine instruction.
Definition at line 45 of file LexicalScopes.h.
Constructor & Destructor Documentation
llvm::LexicalScopes::LexicalScopes () inline
Definition at line 47 of file LexicalScopes.h.
References initialize(), releaseMemory(), and ~LexicalScopes().
LexicalScopes::~LexicalScopes () virtual
Definition at line 28 of file LexicalScopes.cpp.
References releaseMemory().
Referenced by LexicalScopes().
Member Function Documentation
bool LexicalScopes::dominates (DebugLoc DL, MachineBasicBlock * MBB)
dominates - Return true if DebugLoc's lexical scope dominates at least one machine instruction's lexical scope in a given machine basic block.
Definition at line 292 of file LexicalScopes.cpp.
References llvm::MachineBasicBlock::begin(), llvm::LexicalScope::dominates(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getParent(), I, and llvm::DebugLoc::isUnknown().
Referenced by getCurrentFunctionScope().
void llvm::LexicalScopes::dump ()
dump - Print data structures to dbgs().
Referenced by findLexicalScope(), and llvm::LexicalScope::setDFSIn().
bool llvm::LexicalScopes::empty () inline
empty - Return true if there is any lexical scope information available.
Definition at line 57 of file LexicalScopes.h.
Referenced by llvm::DwarfDebug::beginFunction(), and llvm::DwarfDebug::endFunction().
LexicalScope* llvm::LexicalScopes::findAbstractScope (const MDNode * N) inline
findAbstractScope - Find an abstract scope or return NULL.
Definition at line 88 of file LexicalScopes.h.
Referenced by llvm::DwarfDebug::endFunction(), and llvm::DwarfDebug::endModule().
LexicalScope* llvm::LexicalScopes::findInlinedScope (DebugLoc DL) inline
findInlinedScope - Find an inlined scope for the given DebugLoc or return NULL.
Definition at line 94 of file LexicalScopes.h.
Referenced by getDebugLocEntry().
LexicalScope * LexicalScopes::findLexicalScope (DebugLoc DL)
findLexicalScope - Find lexical scope, either regular or inlined, for the given DebugLoc. Return NULL if not found.
Definition at line 116 of file LexicalScopes.cpp.
References llvm::SmallVectorTemplateCommon< T >::back(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::LexicalScope::closeInsnRange(), llvm::X86II::DB, llvm::LexicalScope::dominates(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::LexicalScope::extendInsnRange(), llvm::LexicalScope::getChildren(), llvm::Function::getContext(), llvm::DILexicalBlock::getContext(), llvm::LexicalScope::getDFSOut(), llvm::DebugLoc::getFromDILexicalBlock(), llvm::DebugLoc::getFromDILocation(), llvm::MachineFunction::getFunction(), getMachineBasicBlocks(), llvm::DILexicalBlockFile::getScope(), llvm::DebugLoc::getScopeAndInlinedAt(), llvm::DIDescriptor::isLexicalBlock(), llvm::DIDescriptor::isLexicalBlockFile(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::lookup(), N, llvm::LexicalScope::openInsnRange(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::pop_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), S, llvm::LexicalScope::setDFSIn(), and llvm::LexicalScope::setDFSOut().
Referenced by llvm::DwarfDebug::endModule(), getCurrentFunctionScope(), and getDebugLocEntry().
LexicalScope* llvm::LexicalScopes::findLexicalScope (const MDNode * N) inline
findLexicalScope - Find regular lexical scope or return NULL.
Definition at line 99 of file LexicalScopes.h.
References dump(), M, and N.
ArrayRef<LexicalScope *> llvm::LexicalScopes::getAbstractScopesList () const inline
getAbstractScopesList - Return a reference to list of abstract scopes.
Definition at line 83 of file LexicalScopes.h.
Referenced by llvm::DwarfDebug::endFunction().
LexicalScope* llvm::LexicalScopes::getCurrentFunctionScope () const inline
getCurrentFunctionScope - Return lexical scope for the current function.
Definition at line 66 of file LexicalScopes.h.
References dominates(), findLexicalScope(), and getMachineBasicBlocks().
Referenced by llvm::DwarfDebug::beginFunction(), llvm::DwarfDebug::endFunction(), llvm::DwarfDebug::endInstruction(), and getDebugLocEntry().
void LexicalScopes::getMachineBasicBlocks (DebugLoc DL, SmallPtrSet< const MachineBasicBlock *, 4 > & MBBs)
getMachineBasicBlocks - Populate given set using machine basic blocks which have machine instructions that belong to lexical scope identified by DebugLoc.
Definition at line 268 of file LexicalScopes.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::MachineFunction::begin(), llvm::SmallPtrSetImpl::clear(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::MachineFunction::end(), llvm::LexicalScope::getRanges(), I, and llvm::SmallPtrSet< PtrType, SmallSize >::insert().
Referenced by findLexicalScope(), and getCurrentFunctionScope().
void LexicalScopes::initialize (const MachineFunction & Fn) virtual
initialize - Scan machine function and constuct lexical scope nest.
Definition at line 43 of file LexicalScopes.cpp.
References llvm::MachineFunction::begin(), llvm::MachineFunction::end(), llvm::MachineInstr::getDebugLoc(), I, llvm::ARM_PROC::IE, llvm::MachineInstr::isDebugValue(), llvm::DebugLoc::isUnknown(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and releaseMemory().
Referenced by llvm::DwarfDebug::beginFunction(), and LexicalScopes().
bool llvm::LexicalScopes::isCurrentFunctionScope (const LexicalScope * LS) inline
isCurrentFunctionScope - Return true if given lexical scope represents current function.
Definition at line 61 of file LexicalScopes.h.
Referenced by llvm::DwarfDebug::endModule(), and llvm::DwarfDebug::isSubprogramContext().
void LexicalScopes::releaseMemory () virtual
releaseMemory - release memory.
Definition at line 33 of file LexicalScopes.cpp.
References llvm::DeleteContainerSeconds().
Referenced by initialize(), LexicalScopes(), and ~LexicalScopes().
The documentation for this class was generated from the following files:
LexicalScopes.h
LexicalScopes.cpp