LLVM: llvm::DFAPacketizer Class Reference
LLVM API Documentation
llvm::DFAPacketizer Class Reference
#include <DFAPacketizer.h>
Public Member Functions
DFAPacketizer (const InstrItineraryData *I, const int(*SIT)[2], const unsigned *SET)
void clearResources ()
bool canReserveResources (const llvm::MCInstrDesc *MID)
void reserveResources (const llvm::MCInstrDesc *MID)
bool canReserveResources (llvm::MachineInstr *MI)
void reserveResources (llvm::MachineInstr *MI)
const InstrItineraryData * getInstrItins () const
Detailed Description
Definition at line 43 of file DFAPacketizer.h.
Constructor & Destructor Documentation
DFAPacketizer::DFAPacketizer (const InstrItineraryData * I, const int(*) SIT[2], const unsigned * SET)
Definition at line 34 of file DFAPacketizer.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::count(), and i.
Member Function Documentation
bool DFAPacketizer::canReserveResources (const llvm::MCInstrDesc * MID)
Definition at line 66 of file DFAPacketizer.cpp.
References llvm::InstrItineraryData::beginStage(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::count(), llvm::MCInstrDesc::getSchedClass(), and llvm::InstrStage::getUnits().
Referenced by canReserveResources(), clearResources(), llvm::ResourcePriorityQueue::isResourceAvailable(), and llvm::VLIWPacketizerList::PacketizeMIs().
bool DFAPacketizer::canReserveResources (llvm::MachineInstr * MI)
Definition at line 91 of file DFAPacketizer.cpp.
References canReserveResources(), and llvm::MachineInstr::getDesc().
void llvm::DFAPacketizer::clearResources () inline
Definition at line 62 of file DFAPacketizer.h.
References canReserveResources(), llvm::A64CC::MI, and reserveResources().
Referenced by llvm::VLIWPacketizerList::endPacket(), llvm::ResourcePriorityQueue::reserveResources(), llvm::VLIWResourceModel::reset(), llvm::VLIWResourceModel::resetDFA(), llvm::ResourcePriorityQueue::scheduledNode(), and llvm::VLIWResourceModel::VLIWResourceModel().
const InstrItineraryData* llvm::DFAPacketizer::getInstrItins () const inline
Definition at line 82 of file DFAPacketizer.h.
void DFAPacketizer::reserveResources (const llvm::MCInstrDesc * MID)
Definition at line 78 of file DFAPacketizer.cpp.
References llvm::InstrItineraryData::beginStage(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::count(), llvm::MCInstrDesc::getSchedClass(), and llvm::InstrStage::getUnits().
Referenced by llvm::VLIWPacketizerList::addToPacket(), clearResources(), reserveResources(), and llvm::ResourcePriorityQueue::reserveResources().
void DFAPacketizer::reserveResources (llvm::MachineInstr * MI)
Definition at line 98 of file DFAPacketizer.cpp.
References llvm::MachineInstr::getDesc(), and reserveResources().
The documentation for this class was generated from the following files:
DFAPacketizer.h
DFAPacketizer.cpp