LLVM: llvm::RegScavenger Class Reference
LLVM API Documentation
llvm::RegScavenger Class Reference
#include <RegisterScavenging.h>
Public Member Functions
RegScavenger ()
void enterBasicBlock (MachineBasicBlock *mbb)
void initRegState ()
void forward ()
forward - Move the internal MBB iterator and update register states.
void forward (MachineBasicBlock::iterator I)
void unprocess ()
void unprocess (MachineBasicBlock::iterator I)
Unprocess instructions until you reach the provided iterator.
void skipTo (MachineBasicBlock::iterator I)
skipTo - Move the internal MBB iterator but do not update register states.
MachineBasicBlock::iterator getCurrentPosition () const
void getRegsUsed (BitVector &used, bool includeReserved)
getRegsUsed - return all registers currently in use in used.
BitVector getRegsAvailable (const TargetRegisterClass *RC)
unsigned FindUnusedReg (const TargetRegisterClass *RegClass) const
void addScavengingFrameIndex (int FI)
Add a scavenging frame index.
bool isScavengingFrameIndex (int FI) const
Query whether a frame index is a scavenging frame index.
void getScavengingFrameIndices (SmallVectorImpl< int > &A) const
Get an array of scavenging frame indices.
unsigned scavengeRegister (const TargetRegisterClass *RegClass, MachineBasicBlock::iterator I, int SPAdj)
unsigned scavengeRegister (const TargetRegisterClass *RegClass, int SPAdj)
void setUsed (unsigned Reg)
setUsed - Set the register and its sub-registers as being used.
Detailed Description
Definition at line 31 of file RegisterScavenging.h.
Constructor & Destructor Documentation
llvm::RegScavenger::RegScavenger () inline
Definition at line 75 of file RegisterScavenging.h.
References enterBasicBlock(), forward(), and initRegState().
Member Function Documentation
void llvm::RegScavenger::addScavengingFrameIndex (int FI) inline
Add a scavenging frame index.
Definition at line 128 of file RegisterScavenging.h.
References llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by llvm::PPCFrameLowering::addScavengingSpillSlot(), llvm::MipsSEFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::XCoreFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::ARMFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan(), and llvm::SystemZFrameLowering::processFunctionBeforeFrameFinalized().
void RegScavenger::enterBasicBlock (MachineBasicBlock * mbb)
enterBasicBlock - Start tracking liveness from the begin of the specific basic block.
Definition at line 70 of file RegisterScavenging.cpp.
References llvm::TargetRegisterInfo::getCalleeSavedRegs(), llvm::TargetMachine::getInstrInfo(), llvm::MachineInstr::getNumOperands(), llvm::MCRegisterInfo::getNumRegs(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::TargetMachine::getRegisterInfo(), llvm::MachineOperand::getRegMask(), llvm::MachineFunction::getTarget(), i, initRegState(), llvm::MachineOperand::isDead(), llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isKill(), llvm::TargetInstrInfo::isPredicated(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRegMask(), llvm::MachineOperand::isUndef(), llvm::MachineOperand::isUse(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::A64CC::MI, llvm::BitVector::reset(), llvm::BitVector::resize(), llvm::BitVector::set(), llvm::SystemZISD::TM, and llvm::MachineRegisterInfo::tracksLiveness().
Referenced by AdjustStackOffset(), isHardwareLoop(), llvm::Mips16InstrInfo::loadImmediate(), and RegScavenger().
unsigned RegScavenger::FindUnusedReg (const TargetRegisterClass * RegClass) const
FindUnusedReg - Find a unused register of the specified register class. Return 0 if none is found.
Definition at line 258 of file RegisterScavenging.cpp.
References llvm::TargetRegisterClass::begin(), llvm::dbgs(), DEBUG, llvm::TargetRegisterClass::end(), llvm::MCRegisterInfo::getName(), and I.
Referenced by getCurrentPosition().
void RegScavenger::forward ()
forward - Move the internal MBB iterator and update register states.
Definition at line 171 of file RegisterScavenging.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::MachineBasicBlock::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), i, I, llvm::ARM_PROC::IE, llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUndef(), llvm::MachineOperand::isUse(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm_unreachable, llvm::A64CC::MI, llvm::next(), setUsed(), llvm::BitVector::test(), and llvm::MachineFunction::verify().
Referenced by AdjustStackOffset(), forward(), isHardwareLoop(), llvm::Mips16InstrInfo::loadImmediate(), and RegScavenger().
void llvm::RegScavenger::forward (MachineBasicBlock::iterator I) inline
forward - Move the internal MBB iterator and update register states until it has processed the specific iterator.
Definition at line 91 of file RegisterScavenging.h.
References llvm::MachineBasicBlock::begin(), forward(), I, and unprocess().
MachineBasicBlock::iterator llvm::RegScavenger::getCurrentPosition () const inline
Definition at line 112 of file RegisterScavenging.h.
References FindUnusedReg(), getRegsAvailable(), getRegsUsed(), and used.
Referenced by AdjustStackOffset().
BitVector RegScavenger::getRegsAvailable (const TargetRegisterClass * RC)
getRegsAvailable - Return all available registers in the register class in Mask.
Definition at line 271 of file RegisterScavenging.cpp.
References llvm::TargetRegisterClass::begin(), llvm::BitVector::clearBitsNotInMask(), llvm::TargetRegisterClass::end(), llvm::BitVector::find_first(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::MCRegisterInfo::getNumRegs(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getRegMask(), i, I, llvm::MachineOperand::isDef(), llvm::MachineOperand::isKill(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRegMask(), llvm::MachineOperand::isUndef(), llvm::MCRegAliasIterator::isValid(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::A64CC::MI, llvm::BitVector::none(), llvm::BitVector::reset(), llvm::BitVector::set(), and llvm::BitVector::test().
Referenced by getCurrentPosition(), llvm::Mips16InstrInfo::loadImmediate(), and scavengeRegister().
void RegScavenger::getRegsUsed (BitVector & used, bool includeReserved)
getRegsUsed - return all registers currently in use in used.
Definition at line 249 of file RegisterScavenging.cpp.
References llvm::BitVector::flip(), llvm::MachineRegisterInfo::getReservedRegs(), and llvm::BitVector::reset().
Referenced by getCurrentPosition().
void llvm::RegScavenger::getScavengingFrameIndices (SmallVectorImpl< int > & A) const inline
Get an array of scavenging frame indices.
Definition at line 143 of file RegisterScavenging.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), I, llvm::ARM_PROC::IE, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and scavengeRegister().
Referenced by AdjustStackOffset().
void RegScavenger::initRegState ()
initRegState - allow resetting register state info for multiple passes over/within the same function.
Definition at line 46 of file RegisterScavenging.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::BitVector::find_first(), llvm::BitVector::find_next(), llvm::MachineFunction::getFrameInfo(), llvm::MachineBasicBlock::getParent(), llvm::MachineFrameInfo::getPristineRegs(), I, llvm::ARM_PROC::IE, llvm::MachineBasicBlock::livein_begin(), llvm::MachineBasicBlock::livein_end(), llvm::BitVector::set(), and setUsed().
Referenced by enterBasicBlock(), and RegScavenger().
bool llvm::RegScavenger::isScavengingFrameIndex (int FI) const inline
Query whether a frame index is a scavenging frame index.
Definition at line 133 of file RegisterScavenging.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::end(), I, and llvm::ARM_PROC::IE.
Referenced by AdjustStackOffset(), llvm::Thumb1RegisterInfo::eliminateFrameIndex(), and llvm::ARMBaseRegisterInfo::eliminateFrameIndex().
unsigned RegScavenger::scavengeRegister (const TargetRegisterClass * RegClass, MachineBasicBlock::iterator I, int SPAdj)
scavengeRegister - Make a register of the specific register class available and do the appropriate bookkeeping. SPAdj is the stack adjustment due to call frame, it's passed along to eliminateFrameIndex(). Returns the scavenged register.
Definition at line 361 of file RegisterScavenging.cpp.
References llvm::BitVector::any(), llvm::dbgs(), DEBUG, llvm::TargetRegisterInfo::eliminateFrameIndex(), llvm::ISD::FrameIndex, llvm::TargetRegisterInfo::getAllocatableSet(), getFrameIndexOperandNum(), llvm::MCRegisterInfo::getName(), llvm::MachineOperand::getReg(), getRegsAvailable(), i, llvm::MachineOperand::isReg(), llvm::MachineOperand::isUndef(), llvm::MachineOperand::isUse(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::TargetInstrInfo::loadRegFromStackSlot(), llvm::prior(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::BitVector::reset(), llvm::TargetRegisterInfo::saveScavengerRegister(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::TargetInstrInfo::storeRegToStackSlot().
Referenced by AdjustStackOffset(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), getScavengingFrameIndices(), isHardwareLoop(), and scavengeRegister().
unsigned llvm::RegScavenger::scavengeRegister (const TargetRegisterClass * RegClass, int SPAdj) inline
Definition at line 156 of file RegisterScavenging.h.
References llvm::MachineRegisterInfo::isReserved(), llvm::BitVector::reset(), scavengeRegister(), setUsed(), and llvm::BitVector::test().
void RegScavenger::setUsed (unsigned Reg)
setUsed - Set the register and its sub-registers as being used.
setUsed - Tell the scavenger a register is used.
Definition at line 33 of file RegisterScavenging.cpp.
References llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::MCRegAliasIterator::isValid(), and llvm::BitVector::reset().
Referenced by AdjustStackOffset(), forward(), initRegState(), scavengeRegister(), and unprocess().
void llvm::RegScavenger::skipTo (MachineBasicBlock::iterator I) inline
skipTo - Move the internal MBB iterator but do not update register states.
Definition at line 106 of file RegisterScavenging.h.
References I.
void RegScavenger::unprocess ()
Invert the behavior of forward() on the current instruction (undo the changes to the available registers made by forward()).
Definition at line 152 of file RegisterScavenging.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineInstr::isDebugValue(), llvm::A64CC::MI, and setUsed().
Referenced by AdjustStackOffset(), forward(), and unprocess().
void llvm::RegScavenger::unprocess (MachineBasicBlock::iterator I) inline
Unprocess instructions until you reach the provided iterator.
Definition at line 101 of file RegisterScavenging.h.
References unprocess().
The documentation for this class was generated from the following files:
RegisterScavenging.h
RegisterScavenging.cpp