LLVM: llvm::LiveRangeEdit Class Reference
LLVM API Documentation
llvm::LiveRangeEdit Class Reference
#include <LiveRangeEdit.h>
Classes
class Delegate
Callback methods for LiveRangeEdit owners.
struct Remat
Remat - Information needed to rematerialize at a specific location.
Public Types
typedef SmallVectorImpl< unsigned >::const_iterator iterator
Iterator for accessing the new registers added by this edit.
Public Member Functions
LiveRangeEdit (LiveInterval *parent, SmallVectorImpl< unsigned > &newRegs, MachineFunction &MF, LiveIntervals &lis, VirtRegMap *vrm, Delegate *delegate=0)
~LiveRangeEdit ()
LiveInterval & getParent () const
unsigned getReg () const
iterator begin () const
iterator end () const
unsigned size () const
bool empty () const
unsigned get (unsigned idx) const
ArrayRef< unsigned > regs () const
LiveInterval & createEmptyIntervalFrom (unsigned OldReg)
createEmptyIntervalFrom - Create a new empty interval based on OldReg.
unsigned createFrom (unsigned OldReg)
createFrom - Create a new virtual register based on OldReg.
LiveInterval & createEmptyInterval ()
unsigned create ()
bool anyRematerializable (AliasAnalysis *)
bool checkRematerializable (VNInfo *VNI, const MachineInstr *DefMI, AliasAnalysis *)
bool canRematerializeAt (Remat &RM, SlotIndex UseIdx, bool cheapAsAMove)
SlotIndex rematerializeAt (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned DestReg, const Remat &RM, const TargetRegisterInfo &, bool Late=false)
void markRematerialized (const VNInfo *ParentVNI)
bool didRematerialize (const VNInfo *ParentVNI) const
didRematerialize - Return true if ParentVNI was rematerialized anywhere.
void eraseVirtReg (unsigned Reg)
void eliminateDeadDefs (SmallVectorImpl< MachineInstr * > &Dead, ArrayRef< unsigned > RegsBeingSpilled=None)
void calculateRegClassAndHint (MachineFunction &, const MachineLoopInfo &, const MachineBlockFrequencyInfo &)
Detailed Description
Definition at line 36 of file LiveRangeEdit.h.
Member Typedef Documentation
typedef SmallVectorImpl<unsigned>::const_iterator llvm::LiveRangeEdit::iterator
Iterator for accessing the new registers added by this edit.
Definition at line 136 of file LiveRangeEdit.h.
Constructor & Destructor Documentation
llvm::LiveRangeEdit::LiveRangeEdit (LiveInterval * parent, SmallVectorImpl< unsigned > & newRegs, MachineFunction & MF, LiveIntervals & lis, VirtRegMap * vrm, Delegate * delegate = 0) inline
Create a LiveRangeEdit for breaking down parent into smaller pieces.
Parameters
parent The register being spilled or split.
newRegs List to receive any new registers created. This needn't be empty initially, any existing registers are ignored.
MF The MachineFunction the live range edit is taking place in.
lis The collection of all live intervals in this function.
vrm Map of virtual registers to physical registers for this function. If NULL, no virtual register map updates will be done. This could be the case if called before Regalloc.
Definition at line 114 of file LiveRangeEdit.h.
References llvm::MachineRegisterInfo::setDelegate().
llvm::LiveRangeEdit::~LiveRangeEdit () inline
Definition at line 127 of file LiveRangeEdit.h.
References llvm::MachineRegisterInfo::resetDelegate().
Member Function Documentation
bool LiveRangeEdit::anyRematerializable (AliasAnalysis * aa)
anyRematerializable - Return true if any parent values may be rematerializable. This function must be called before any rematerialization is attempted.
Definition at line 75 of file LiveRangeEdit.cpp.
References llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::SlotIndex::getRegSlot(), llvm::LiveRange::getVNInfoAt(), i, llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::MachineOperand::isReg(), llvm::SlotIndex::isSameInstr(), MRI, and llvm::MachineOperand::readsReg().
Referenced by create(), operator<<(), and llvm::SplitEditor::reset().
iterator llvm::LiveRangeEdit::begin () const inline
Definition at line 137 of file LiveRangeEdit.h.
References llvm::SmallVectorTemplateCommon< T, typename >::begin().
Referenced by llvm::createGreedyRegisterAllocator(), llvm::SplitEditor::finish(), and llvm::SplitEditor::overlapIntv().
void LiveRangeEdit::calculateRegClassAndHint (MachineFunction & MF, const MachineLoopInfo & Loops, const MachineBlockFrequencyInfo & MBFI)
calculateRegClassAndHint - Recompute register class and hint for each new register.
Definition at line 408 of file LiveRangeEdit.cpp.
References llvm::VirtRegAuxInfo::calculateSpillWeightAndHint(), llvm::dbgs(), DEBUG, llvm::MCRegisterClass::getName(), llvm::MCRegisterInfo::getRegClass(), llvm::MachineFunction::getTarget(), I, MRI, llvm::LiveInterval::reg, and size().
Referenced by didRematerialize(), dumpMachineInstrRangeWithSlotIndex(), and llvm::SplitEditor::finish().
bool LiveRangeEdit::canRematerializeAt (Remat & RM, SlotIndex UseIdx, bool cheapAsAMove)
canRematerializeAt - Determine if ParentVNI can be rematerialized at UseIdx. It is assumed that parent_.getVNINfoAt(UseIdx) == ParentVNI. When cheapAsAMove is set, only cheap remats are allowed.
Definition at line 117 of file LiveRangeEdit.cpp.
References llvm::VNInfo::def, llvm::MachineInstr::isAsCheapAsAMove(), llvm::LiveRangeEdit::Remat::OrigMI, and llvm::LiveRangeEdit::Remat::ParentVNI.
Referenced by llvm::SplitEditor::dump(), operator<<(), and llvm::LiveRangeEdit::Remat::Remat().
bool LiveRangeEdit::checkRematerializable (VNInfo * VNI, const MachineInstr * DefMI, AliasAnalysis * aa)
checkRematerializable - Manually add VNI to the list of rematerializable values if DefMI may be rematerializable.
Definition at line 50 of file LiveRangeEdit.cpp.
References aa, llvm::VNInfo::def, getParent(), I, llvm::VNInfo::isUnused(), and TII.
Referenced by create(), and operator<<().
unsigned llvm::LiveRangeEdit::create () inline
Definition at line 159 of file LiveRangeEdit.h.
References anyRematerializable(), checkRematerializable(), createFrom(), and getReg().
Referenced by llvm::Spiller::~Spiller().
LiveInterval& llvm::LiveRangeEdit::createEmptyInterval () inline
create - Create a new register with the same class and original slot as parent.
Definition at line 155 of file LiveRangeEdit.h.
References createEmptyIntervalFrom(), and getReg().
Referenced by llvm::SplitEditor::finish(), and llvm::SplitEditor::openIntv().
LiveInterval & LiveRangeEdit::createEmptyIntervalFrom (unsigned OldReg)
createEmptyIntervalFrom - Create a new empty interval based on OldReg.
Definition at line 33 of file LiveRangeEdit.cpp.
References llvm::MCRegisterInfo::getRegClass(), and MRI.
Referenced by createEmptyInterval(), eliminateDeadDefs(), and regs().
unsigned LiveRangeEdit::createFrom (unsigned OldReg)
createFrom - Create a new virtual register based on OldReg.
Definition at line 42 of file LiveRangeEdit.cpp.
References llvm::MCRegisterInfo::getRegClass(), and MRI.
Referenced by create(), dumpMachineInstrRangeWithSlotIndex(), operator<<(), and regs().
bool llvm::LiveRangeEdit::didRematerialize (const VNInfo * ParentVNI) const inline
didRematerialize - Return true if ParentVNI was rematerialized anywhere.
Definition at line 205 of file LiveRangeEdit.h.
References calculateRegClassAndHint(), llvm::SmallPtrSet< PtrType, SmallSize >::count(), eliminateDeadDefs(), eraseVirtReg(), and llvm::None.
Referenced by llvm::SplitEditor::finish(), and llvm::SplitEditor::overlapIntv().
void LiveRangeEdit::eliminateDeadDefs (SmallVectorImpl< MachineInstr * > & Dead, ArrayRef< unsigned > RegsBeingSpilled = None)
eliminateDeadDefs - Try to delete machine instructions that are now dead (allDefsAreDead returns true). This may cause live intervals to be trimmed and further dead efs to be eliminated. RegsBeingSpilled lists registers currently being spilled by the register allocator. These registers should not be split into new intervals as currently those new intervals are not guaranteed to spill.
Definition at line 332 of file LiveRangeEdit.cpp.
References llvm::SetVector< T, Vector, Set >::back(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::ConnectedVNInfoEqClasses::Classify(), createEmptyIntervalFrom(), llvm::dbgs(), DEBUG, llvm::ConnectedVNInfoEqClasses::Distribute(), llvm::SmallVectorBase::empty(), llvm::SetVector< T, Vector, Set >::empty(), i, MRI, llvm::SetVector< T, Vector, Set >::pop_back(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::LiveInterval::reg, llvm::LiveRange::RenumberValues(), and llvm::ArrayRef< T >::size().
Referenced by didRematerialize(), dumpMachineInstrRangeWithSlotIndex(), llvm::CoalescerPair::isCoalescable(), operator<<(), and llvm::SplitEditor::overlapIntv().
bool llvm::LiveRangeEdit::empty () const inline
Definition at line 140 of file LiveRangeEdit.h.
References size().
Referenced by llvm::createGreedyRegisterAllocator(), and llvm::SplitEditor::openIntv().
iterator llvm::LiveRangeEdit::end () const inline
Definition at line 138 of file LiveRangeEdit.h.
References llvm::SmallVectorTemplateCommon< T, typename >::end().
Referenced by llvm::createGreedyRegisterAllocator(), llvm::SplitEditor::finish(), and llvm::SplitEditor::overlapIntv().
void LiveRangeEdit::eraseVirtReg (unsigned Reg)
eraseVirtReg - Notify the delegate that Reg is no longer in use, and try to erase it from LIS.
Definition at line 160 of file LiveRangeEdit.cpp.
References llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::allDefsAreDead(), llvm::MachineInstr::canFoldAsLoad(), llvm::dbgs(), llvm::RegState::Dead, DEBUG, llvm::LiveRange::empty(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getParent(), llvm::MachineOperand::getReg(), llvm::SlotIndex::getRegSlot(), llvm::MachineOperand::getSubReg(), llvm::LiveRange::getVNInfoAt(), i, I, llvm::SetVector< T, Vector, Set >::insert(), llvm::MachineInstr::isBundled(), llvm::MachineInstr::isCopy(), llvm::MachineOperand::isDef(), llvm::MachineInstr::isInlineAsm(), llvm::LiveQueryResult::isKill(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::MachineOperand::isReg(), llvm::MachineInstr::isSafeToMove(), llvm::MachineOperand::isUndef(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::TargetOpcode::KILL, llvm::A64CC::MI, MRI, llvm::MachineInstr::operands_begin(), llvm::MachineInstr::operands_end(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::LiveRange::Query(), llvm::MachineInstr::readsVirtualRegister(), llvm::LiveInterval::reg, llvm::SetVector< T, Vector, Set >::remove(), llvm::MachineInstr::RemoveOperand(), llvm::LiveRange::removeValNo(), llvm::MachineInstr::setDesc(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and TII.
Referenced by didRematerialize(), dumpMachineInstrRangeWithSlotIndex(), and operator<<().
unsigned llvm::LiveRangeEdit::get (unsigned idx) const inline
Definition at line 141 of file LiveRangeEdit.h.
Referenced by llvm::createGreedyRegisterAllocator(), llvm::SplitEditor::dump(), llvm::SplitEditor::finish(), and llvm::SplitEditor::overlapIntv().
LiveInterval& llvm::LiveRangeEdit::getParent () const inline
Definition at line 129 of file LiveRangeEdit.h.
Referenced by checkRematerializable(), llvm::SplitEditor::dump(), dumpMachineInstrRangeWithSlotIndex(), llvm::SplitEditor::enterIntvAfter(), llvm::SplitEditor::enterIntvAtEnd(), llvm::SplitEditor::enterIntvBefore(), llvm::SplitEditor::finish(), getReg(), llvm::SplitEditor::leaveIntvAfter(), llvm::SplitEditor::leaveIntvAtTop(), llvm::SplitEditor::leaveIntvBefore(), llvm::SplitEditor::overlapIntv(), and llvm::Spiller::~Spiller().
unsigned llvm::LiveRangeEdit::getReg () const inline
Definition at line 133 of file LiveRangeEdit.h.
References getParent(), and llvm::LiveInterval::reg.
Referenced by create(), createEmptyInterval(), llvm::SplitEditor::dump(), dumpMachineInstrRangeWithSlotIndex(), isFullCopyOf(), llvm::SplitEditor::leaveIntvAfter(), operator<<(), and llvm::SplitEditor::overlapIntv().
void llvm::LiveRangeEdit::markRematerialized (const VNInfo * ParentVNI) inline
markRematerialized - explicitly mark a value as rematerialized after doing it manually.
Definition at line 200 of file LiveRangeEdit.h.
References llvm::SmallPtrSet< PtrType, SmallSize >::insert().
Referenced by operator<<().
ArrayRef<unsigned> llvm::LiveRangeEdit::regs () const inline
Definition at line 143 of file LiveRangeEdit.h.
References createEmptyIntervalFrom(), createFrom(), and llvm::makeArrayRef().
Referenced by llvm::createGreedyRegisterAllocator().
SlotIndex LiveRangeEdit::rematerializeAt (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, unsigned DestReg, const Remat & RM, const TargetRegisterInfo & tri, bool Late = false)
rematerializeAt - Rematerialize RM.ParentVNI into DestReg by inserting an instruction into MBB before MI. The new instruction is mapped, but liveness is not updated. Return the SlotIndex of the new instruction.
Definition at line 147 of file LiveRangeEdit.cpp.
References llvm::LiveRangeEdit::Remat::OrigMI, llvm::LiveRangeEdit::Remat::ParentVNI, and TII.
Referenced by llvm::SplitEditor::dump(), operator<<(), and llvm::LiveRangeEdit::Remat::Remat().
unsigned llvm::LiveRangeEdit::size () const inline
Definition at line 139 of file LiveRangeEdit.h.
References llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by calculateRegClassAndHint(), llvm::createGreedyRegisterAllocator(), empty(), llvm::SplitEditor::finish(), and llvm::SplitEditor::openIntv().
The documentation for this class was generated from the following files:
LiveRangeEdit.h
LiveRangeEdit.cpp