LLVM: llvm::OwningArrayPtr< T > Class Template Reference
LLVM API Documentation
llvm::OwningArrayPtr< T > Class Template Reference
#include <OwningPtr.h>
Public Member Functions
OwningArrayPtr (T *P=0)
~OwningArrayPtr ()
void reset (T *P=0)
T * take ()
T & operator[] (std::ptrdiff_t i) const
T * get () const
LLVM_EXPLICIT operator bool () const
bool operator! () const
void swap (OwningArrayPtr &RHS)
Detailed Description
template<class T>
class llvm::OwningArrayPtr< T >
OwningArrayPtr smart pointer - OwningArrayPtr provides the same functionality as OwningPtr, except that it works for array types.
Definition at line 92 of file OwningPtr.h.
Constructor & Destructor Documentation
template<class T> llvm::OwningArrayPtr< T >::OwningArrayPtr (T * P = 0) inline explicit
Definition at line 97 of file OwningPtr.h.
template<class T> llvm::OwningArrayPtr< T >::~OwningArrayPtr () inline
Definition at line 108 of file OwningPtr.h.
Member Function Documentation
template<class T> T* llvm::OwningArrayPtr< T >::get () const inline
Definition at line 135 of file OwningPtr.h.
Referenced by llvm::zlib::uncompress().
template<class T> LLVM_EXPLICIT llvm::OwningArrayPtr< T >::operator bool () const inline
Definition at line 136 of file OwningPtr.h.
template<class T> bool llvm::OwningArrayPtr< T >::operator! () const inline
Definition at line 137 of file OwningPtr.h.
template<class T> T& llvm::OwningArrayPtr< T >::operator[] (std::ptrdiff_t i) const inline
Definition at line 130 of file OwningPtr.h.
template<class T> void llvm::OwningArrayPtr< T >::reset (T * P = 0) inline
reset - Change the current pointee to the specified pointer. Note that calling this with any pointer (including a null pointer) deletes the current pointer.
Definition at line 115 of file OwningPtr.h.
Referenced by llvm::ComputeEditDistance(), and llvm::RegisterClassInfo::runOnMachineFunction().
template<class T> void llvm::OwningArrayPtr< T >::swap (OwningArrayPtr< T > & RHS) inline
Definition at line 139 of file OwningPtr.h.
Referenced by llvm::swap().
template<class T> T* llvm::OwningArrayPtr< T >::take () inline
take - Reset the owning pointer to null and return its pointer. This does not delete the pointer before returning it.
Definition at line 124 of file OwningPtr.h.
The documentation for this class was generated from the following file:
OwningPtr.h