LLVM: llvm::SplitAnalysis Class Reference
LLVM API Documentation
llvm::SplitAnalysis Class Reference
#include <SplitKit.h>
Classes
struct BlockInfo
Public Types
typedef SmallPtrSet< const MachineBasicBlock *, 16 > BlockPtrSet
Public Member Functions
SplitAnalysis (const VirtRegMap &vrm, const LiveIntervals &lis, const MachineLoopInfo &mli)
void analyze (const LiveInterval *li)
bool didRepairRange () const
void clear ()
const LiveInterval & getParent () const
getParent - Return the last analyzed interval.
SlotIndex getLastSplitPoint (unsigned Num)
MachineBasicBlock::iterator getLastSplitPointIter (MachineBasicBlock *)
getLastSplitPointIter - Returns the last split point as an iterator.
bool isOriginalEndpoint (SlotIndex Idx) const
ArrayRef< SlotIndex > getUseSlots () const
ArrayRef< BlockInfo > getUseBlocks () const
unsigned getNumThroughBlocks () const
getNumThroughBlocks - Return the number of through blocks.
bool isThroughBlock (unsigned MBB) const
isThroughBlock - Return true if CurLI is live through MBB without uses.
const BitVector & getThroughBlocks () const
getThroughBlocks - Return the set of through blocks.
unsigned getNumLiveBlocks () const
getNumLiveBlocks - Return the number of blocks where CurLI is live.
unsigned countLiveBlocks (const LiveInterval *li) const
bool shouldSplitSingleBlock (const BlockInfo &BI, bool SingleInstrs) const
Public Attributes
const MachineFunction & MF
const VirtRegMap & VRM
const LiveIntervals & LIS
const MachineLoopInfo & Loops
const TargetInstrInfo & TII
Detailed Description
SplitAnalysis - Analyze a LiveInterval, looking for live range splitting opportunities.
Definition at line 42 of file SplitKit.h.
Member Typedef Documentation
typedef SmallPtrSet<const MachineBasicBlock*, 16> llvm::SplitAnalysis::BlockPtrSet
Definition at line 186 of file SplitKit.h.
Constructor & Destructor Documentation
SplitAnalysis::SplitAnalysis (const VirtRegMap & vrm, const LiveIntervals & lis, const MachineLoopInfo & mli)
Definition at line 42 of file SplitKit.cpp.
Referenced by llvm::SplitAnalysis::BlockInfo::isOneInstr().
Member Function Documentation
void SplitAnalysis::analyze (const LiveInterval * li)
analyze - set CurLI to the specified interval, and analyze how it may be split.
Definition at line 313 of file SplitKit.cpp.
References clear().
Referenced by llvm::createGreedyRegisterAllocator(), and llvm::SplitAnalysis::BlockInfo::isOneInstr().
void SplitAnalysis::clear ()
clear - clear all data structures so SplitAnalysis is ready to analyze a new interval.
Definition at line 53 of file SplitKit.cpp.
References llvm::MachineBasicBlock::begin(), llvm::BitVector::clear(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::getBlockNumbered(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::LiveIntervals::getInstructionIndex(), llvm::MachineBasicBlock::getLandingPadSuccessor(), llvm::LiveIntervals::getMBBEndIdx(), llvm::LiveRange::getVNInfoBefore(), I, llvm::SlotIndex::isEarlierInstr(), llvm::LiveIntervals::isLiveInToMBB(), LIS, and MF.
Referenced by analyze(), and didRepairRange().
unsigned SplitAnalysis::countLiveBlocks (const LiveInterval * li) const
countLiveBlocks - Return the number of blocks where li is live. This is guaranteed to return the same number as getNumLiveBlocks() after calling analyze(li).
Definition at line 276 of file SplitKit.cpp.
References llvm::LiveRange::advanceTo(), llvm::LiveRange::begin(), llvm::LiveRange::empty(), llvm::LiveRange::end(), llvm::LiveIntervals::getMBBEndIdx(), llvm::LiveIntervals::getMBBFromIndex(), and LIS.
Referenced by llvm::createGreedyRegisterAllocator(), getLastSplitPointIter(), and getNumLiveBlocks().
bool llvm::SplitAnalysis::didRepairRange () const inline
didRepairRange() - Returns true if CurLI was invalid and has been repaired by analyze(). This really shouldn't happen, but sometimes the coalescer can create live ranges that end in mid-air.
Definition at line 130 of file SplitKit.h.
References clear().
Referenced by llvm::createGreedyRegisterAllocator().
SlotIndex llvm::SplitAnalysis::getLastSplitPoint (unsigned Num) inline
getLastSplitPoint - Return the base index of the last valid split point in the basic block numbered Num.
Definition at line 141 of file SplitKit.h.
References getLastSplitPointIter(), and isOriginalEndpoint().
Referenced by llvm::createGreedyRegisterAllocator(), getLastSplitPointIter(), llvm::SplitEditor::splitLiveThroughBlock(), llvm::SplitEditor::splitRegInBlock(), llvm::SplitEditor::splitRegOutBlock(), and llvm::SplitEditor::splitSingleBlock().
MachineBasicBlock::iterator SplitAnalysis::getLastSplitPointIter (MachineBasicBlock * MBB)
getLastSplitPointIter - Returns the last split point as an iterator.
Definition at line 114 of file SplitKit.cpp.
References llvm::array_pod_sort(), llvm::LiveRange::begin(), llvm::BitVector::clear(), countLiveBlocks(), llvm::dbgs(), DEBUG, llvm::LiveRange::empty(), llvm::LiveRange::end(), llvm::MachineBasicBlock::end(), llvm::SplitAnalysis::BlockInfo::FirstDef, llvm::SplitAnalysis::BlockInfo::FirstInstr, llvm::LiveIntervals::getInstructionFromIndex(), llvm::LiveIntervals::getInstructionIndex(), getLastSplitPoint(), llvm::LiveIntervals::getMBBEndIdx(), llvm::LiveIntervals::getMBBFromIndex(), llvm::SlotIndexes::getMBBRange(), llvm::MachineBasicBlock::getNumber(), llvm::MachineFunction::getNumBlockIDs(), getNumLiveBlocks(), llvm::MachineFunction::getRegInfo(), llvm::SlotIndex::getRegSlot(), llvm::LiveIntervals::getSlotIndexes(), I, llvm::SlotIndex::isSameInstr(), llvm::SplitAnalysis::BlockInfo::LastInstr, LIS, llvm::SplitAnalysis::BlockInfo::LiveIn, llvm::SplitAnalysis::BlockInfo::LiveOut, llvm::SplitAnalysis::BlockInfo::MBB, MF, MRI, llvm::LiveInterval::reg, llvm::BitVector::resize(), llvm::BitVector::set(), llvm::tie(), llvm::MachineRegisterInfo::use_nodbg_begin(), llvm::MachineRegisterInfo::use_nodbg_end(), llvm::LiveRange::vni_begin(), and llvm::LiveRange::vni_end().
Referenced by llvm::SplitEditor::enterIntvAtEnd(), getLastSplitPoint(), and llvm::SplitEditor::overlapIntv().
unsigned llvm::SplitAnalysis::getNumLiveBlocks () const inline
getNumLiveBlocks - Return the number of blocks where CurLI is live.
Definition at line 177 of file SplitKit.h.
References countLiveBlocks(), getNumThroughBlocks(), and getUseBlocks().
Referenced by llvm::createGreedyRegisterAllocator(), and getLastSplitPointIter().
unsigned llvm::SplitAnalysis::getNumThroughBlocks () const inline
getNumThroughBlocks - Return the number of through blocks.
Definition at line 168 of file SplitKit.h.
Referenced by llvm::createGreedyRegisterAllocator(), and getNumLiveBlocks().
const LiveInterval& llvm::SplitAnalysis::getParent () const inline
getParent - Return the last analyzed interval.
Definition at line 137 of file SplitKit.h.
Referenced by llvm::createGreedyRegisterAllocator().
const BitVector& llvm::SplitAnalysis::getThroughBlocks () const inline
getThroughBlocks - Return the set of through blocks.
Definition at line 174 of file SplitKit.h.
Referenced by llvm::createGreedyRegisterAllocator().
ArrayRef<BlockInfo> llvm::SplitAnalysis::getUseBlocks () const inline
getUseBlocks - Return an array of BlockInfo objects for the basic blocks where CurLI has uses.
Definition at line 165 of file SplitKit.h.
Referenced by llvm::createGreedyRegisterAllocator(), and getNumLiveBlocks().
ArrayRef<SlotIndex> llvm::SplitAnalysis::getUseSlots () const inline
getUseSlots - Return an array of SlotIndexes of instructions using CurLI. This include both use and def operands, at most one entry per instruction.
Definition at line 161 of file SplitKit.h.
Referenced by llvm::createGreedyRegisterAllocator().
bool SplitAnalysis::isOriginalEndpoint (SlotIndex Idx) const
isOriginalEndpoint - Return true if the original live range was killed or (re-)defined at Idx. Idx should be the 'def' slot for a normal kill/def, and 'use' for an early-clobber def. This can be used to recognize code inserted by earlier live range splitting.
Definition at line 299 of file SplitKit.cpp.
References llvm::LiveRange::begin(), llvm::LiveRange::empty(), llvm::sys::path::end(), llvm::LiveRange::end(), llvm::LiveRange::find(), llvm::LiveIntervals::getInterval(), llvm::VirtRegMap::getOriginal(), I, LIS, llvm::LiveInterval::reg, and VRM.
Referenced by getLastSplitPoint().
bool llvm::SplitAnalysis::isThroughBlock (unsigned MBB) const inline
isThroughBlock - Return true if CurLI is live through MBB without uses.
Definition at line 171 of file SplitKit.h.
References llvm::BitVector::test().
bool SplitAnalysis::shouldSplitSingleBlock (const BlockInfo & BI, bool SingleInstrs) const
shouldSplitSingleBlock - Returns true if it would help to create a local live range for the instructions in BI. There is normally no benefit to creating a live range for a single instruction, but it does enable register class inflation if the instruction has a restricted register class.
Parameters
BI The block to be isolated.
SingleInstrs True when single instructions should be isolated.
Definition at line 1137 of file SplitKit.cpp.
References llvm::SplitAnalysis::BlockInfo::FirstInstr, llvm::LiveIntervals::getInstructionFromIndex(), llvm::MachineInstr::isCopyLike(), llvm::SplitAnalysis::BlockInfo::isOneInstr(), llvm::SplitAnalysis::BlockInfo::LiveIn, and llvm::SplitAnalysis::BlockInfo::LiveOut.
Referenced by llvm::createGreedyRegisterAllocator().
Member Data Documentation
const LiveIntervals& llvm::SplitAnalysis::LIS
Definition at line 46 of file SplitKit.h.
Referenced by clear(), countLiveBlocks(), getLastSplitPointIter(), and isOriginalEndpoint().
const MachineLoopInfo& llvm::SplitAnalysis::Loops
Definition at line 47 of file SplitKit.h.
Referenced by llvm::SplitEditor::finish(), and llvm::SplitEditor::overlapIntv().
const MachineFunction& llvm::SplitAnalysis::MF
Definition at line 44 of file SplitKit.h.
Referenced by clear(), and getLastSplitPointIter().
const TargetInstrInfo& llvm::SplitAnalysis::TII
Definition at line 48 of file SplitKit.h.
const VirtRegMap& llvm::SplitAnalysis::VRM
Definition at line 45 of file SplitKit.h.
Referenced by isOriginalEndpoint().
The documentation for this class was generated from the following files:
SplitKit.h
SplitKit.cpp