LLVM: llvm::sys::SmartRWMutex< mt_only > Class Template Reference
LLVM API Documentation
llvm::sys::SmartRWMutex< mt_only > Class Template Reference
#include <RWMutex.h>
Public Member Functions
SmartRWMutex ()
bool reader_acquire ()
bool reader_release ()
bool writer_acquire ()
bool writer_release ()
Public Member Functions inherited from llvm::sys::RWMutexImpl
RWMutexImpl ()
Default Constructor.
~RWMutexImpl ()
Destructor.
bool reader_acquire ()
Unconditionally acquire the lock in reader mode.
bool reader_release ()
Unconditionally release the lock in reader mode.
bool writer_acquire ()
Unconditionally acquire the lock in writer mode.
bool writer_release ()
Unconditionally release the lock in write mode.
Detailed Description
template<bool mt_only>
class llvm::sys::SmartRWMutex< mt_only >
SmartMutex - An R/W mutex with a compile time constant parameter that indicates whether this mutex should become a no-op when we're not running in multithreaded mode.
Definition at line 88 of file RWMutex.h.
Constructor & Destructor Documentation
template<bool mt_only> llvm::sys::SmartRWMutex< mt_only >::SmartRWMutex () inline explicit
Definition at line 91 of file RWMutex.h.
Member Function Documentation
template<bool mt_only> bool llvm::sys::SmartRWMutex< mt_only >::reader_acquire () inline
Definition at line 93 of file RWMutex.h.
References llvm::llvm_is_multithreaded(), and llvm::sys::RWMutexImpl::reader_acquire().
Referenced by llvm::sys::SmartScopedReader< mt_only >::SmartScopedReader().
template<bool mt_only> bool llvm::sys::SmartRWMutex< mt_only >::reader_release () inline
Definition at line 103 of file RWMutex.h.
References llvm::llvm_is_multithreaded(), and llvm::sys::RWMutexImpl::reader_release().
Referenced by llvm::sys::SmartScopedReader< mt_only >::~SmartScopedReader().
template<bool mt_only> bool llvm::sys::SmartRWMutex< mt_only >::writer_acquire () inline
Definition at line 114 of file RWMutex.h.
References llvm::llvm_is_multithreaded(), and llvm::sys::RWMutexImpl::writer_acquire().
Referenced by llvm::sys::SmartScopedWriter< mt_only >::SmartScopedWriter().
template<bool mt_only> bool llvm::sys::SmartRWMutex< mt_only >::writer_release () inline
Definition at line 125 of file RWMutex.h.
References llvm::llvm_is_multithreaded(), and llvm::sys::RWMutexImpl::writer_release().
Referenced by llvm::sys::SmartScopedWriter< mt_only >::~SmartScopedWriter().
The documentation for this class was generated from the following file:
RWMutex.h