LLVM: llvm::AArch64Subtarget Class Reference
LLVM API Documentation
llvm::AArch64Subtarget Class Reference
#include <AArch64Subtarget.h>
Public Member Functions
AArch64Subtarget (StringRef TT, StringRef CPU, StringRef FS)
virtual bool enableMachineScheduler () const
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
bool GVIsIndirectSymbol (const GlobalValue *GV, Reloc::Model RelocM) const
bool isTargetELF () const
bool isTargetLinux () const
bool hasFPARMv8 () const
bool hasNEON () const
bool hasCrypto () const
const std::string & getCPUString () const
Protected Attributes
bool HasFPARMv8
bool HasNEON
bool HasCrypto
Triple TargetTriple
TargetTriple - What processor and OS we're targeting.
std::string CPUString
CPUString - String name of used CPU.
Detailed Description
Definition at line 29 of file AArch64Subtarget.h.
Constructor & Destructor Documentation
AArch64Subtarget::AArch64Subtarget (StringRef TT, StringRef CPU, StringRef FS)
This constructor initializes the data members to match that of the specified triple.
Definition at line 31 of file AArch64Subtarget.cpp.
References CPUString, llvm::StringRef::empty(), llvm::X86II::FS, and ParseSubtargetFeatures().
Member Function Documentation
virtual bool llvm::AArch64Subtarget::enableMachineScheduler () const inline virtual
Definition at line 51 of file AArch64Subtarget.h.
References llvm::X86II::FS, GVIsIndirectSymbol(), and ParseSubtargetFeatures().
const std::string& llvm::AArch64Subtarget::getCPUString () const inline
Definition at line 68 of file AArch64Subtarget.h.
References CPUString.
bool AArch64Subtarget::GVIsIndirectSymbol (const GlobalValue * GV, Reloc::Model RelocM) const
Definition at line 55 of file AArch64Subtarget.cpp.
References llvm::GlobalValue::hasHiddenVisibility(), llvm::GlobalValue::hasLocalLinkage(), and llvm::Reloc::Static.
Referenced by enableMachineScheduler(), llvm::AArch64TargetLowering::LowerGlobalAddressELFSmall(), and llvm::AArch64AsmPrinter::printSymbolicAddress().
bool llvm::AArch64Subtarget::hasCrypto () const inline
Definition at line 66 of file AArch64Subtarget.h.
References HasCrypto.
bool llvm::AArch64Subtarget::hasFPARMv8 () const inline
Definition at line 64 of file AArch64Subtarget.h.
References HasFPARMv8.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), and llvm::AArch64TargetLowering::SaveVarArgRegisters().
bool llvm::AArch64Subtarget::hasNEON () const inline
Definition at line 65 of file AArch64Subtarget.h.
References HasNEON.
Referenced by llvm::AArch64TargetLowering::AArch64TargetLowering(), PerformORCombine(), and PerformShiftCombine().
bool llvm::AArch64Subtarget::isTargetELF () const inline
Definition at line 61 of file AArch64Subtarget.h.
References llvm::Triple::isOSBinFormatELF().
Referenced by createTLOF(), and llvm::AArch64AsmPrinter::EmitEndOfAsmFile().
bool llvm::AArch64Subtarget::isTargetLinux () const inline
Definition at line 62 of file AArch64Subtarget.h.
References llvm::Triple::isOSLinux().
Referenced by createTLOF().
void llvm::AArch64Subtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options. Definition of function is auto generated by tblgen.
Referenced by AArch64Subtarget(), and enableMachineScheduler().
Member Data Documentation
std::string llvm::AArch64Subtarget::CPUString protected
CPUString - String name of used CPU.
Definition at line 40 of file AArch64Subtarget.h.
Referenced by AArch64Subtarget(), and getCPUString().
bool llvm::AArch64Subtarget::HasCrypto protected
Definition at line 34 of file AArch64Subtarget.h.
Referenced by hasCrypto().
bool llvm::AArch64Subtarget::HasFPARMv8 protected
Definition at line 32 of file AArch64Subtarget.h.
Referenced by hasFPARMv8().
bool llvm::AArch64Subtarget::HasNEON protected
Definition at line 33 of file AArch64Subtarget.h.
Referenced by hasNEON().
Triple llvm::AArch64Subtarget::TargetTriple protected
TargetTriple - What processor and OS we're targeting.
Definition at line 37 of file AArch64Subtarget.h.
The documentation for this class was generated from the following files:
AArch64Subtarget.h
AArch64Subtarget.cpp