LLVM: llvm::object::SymbolRef Class Reference
LLVM API Documentation
llvm::object::SymbolRef Class Reference
#include <ObjectFile.h>
Public Types
enum Type {
ST_Unknown, ST_Data, ST_Debug, ST_File,
ST_Function, ST_Other
}
Public Member Functions
SymbolRef ()
enum Flags LLVM_ENUM_INT_TYPE (unsigned)
SymbolRef (DataRefImpl SymbolP, const ObjectFile *Owner)
bool operator== (const SymbolRef &Other) const
bool operator< (const SymbolRef &Other) const
error_code getNext (SymbolRef &Result) const
error_code getName (StringRef &Result) const
error_code getAddress (uint64_t &Result) const
error_code getFileOffset (uint64_t &Result) const
error_code getAlignment (uint32_t &Result) const
Get the alignment of this symbol as the actual value (not log 2).
error_code getSize (uint64_t &Result) const
error_code getType (SymbolRef::Type &Result) const
error_code getFlags (uint32_t &Result) const
Get symbol flags (bitwise OR of SymbolRef::Flags)
error_code getSection (section_iterator &Result) const
Get section this symbol is defined in reference to. Result is end_sections() if it is undefined or is an absolute symbol.
error_code getValue (uint64_t &Val) const
Get value of the symbol in the symbol table.
DataRefImpl getRawDataRefImpl () const
Friends
class SectionRef
Detailed Description
SymbolRef - This is a value type class that represents a single symbol in the list of symbols in the object file.
Definition at line 178 of file ObjectFile.h.
Member Enumeration Documentation
enum llvm::object::SymbolRef::Type
Enumerator
ST_Unknown
ST_Data
ST_Debug
ST_File
ST_Function
ST_Other
Definition at line 186 of file ObjectFile.h.
Constructor & Destructor Documentation
llvm::object::SymbolRef::SymbolRef () inline
Definition at line 184 of file ObjectFile.h.
llvm::object::SymbolRef::SymbolRef (DataRefImpl SymbolP, const ObjectFile * Owner) inline
Definition at line 393 of file ObjectFile.h.
Member Function Documentation
error_code llvm::object::SymbolRef::getAddress (uint64_t & Result) const inline
Returns the symbol virtual address (i.e. address at which it will be mapped).
Definition at line 413 of file ObjectFile.h.
References llvm::object::ObjectFile::getSymbolAddress().
error_code llvm::object::SymbolRef::getAlignment (uint32_t & Result) const inline
Get the alignment of this symbol as the actual value (not log 2).
Definition at line 421 of file ObjectFile.h.
References llvm::object::ObjectFile::getSymbolAlignment().
error_code llvm::object::SymbolRef::getFileOffset (uint64_t & Result) const inline
Definition at line 417 of file ObjectFile.h.
References llvm::object::ObjectFile::getSymbolFileOffset().
error_code llvm::object::SymbolRef::getFlags (uint32_t & Result) const inline
Get symbol flags (bitwise OR of SymbolRef::Flags)
Definition at line 429 of file ObjectFile.h.
References llvm::object::ObjectFile::getSymbolFlags().
error_code llvm::object::SymbolRef::getName (StringRef & Result) const inline
Definition at line 409 of file ObjectFile.h.
References llvm::object::ObjectFile::getSymbolName().
error_code llvm::object::SymbolRef::getNext (SymbolRef & Result) const inline
Definition at line 405 of file ObjectFile.h.
References llvm::object::ObjectFile::getSymbolNext().
DataRefImpl llvm::object::SymbolRef::getRawDataRefImpl () const inline
Definition at line 445 of file ObjectFile.h.
Referenced by llvm::object::ELFObjectFile< ELFT >::getSymbolVersion().
error_code llvm::object::SymbolRef::getSection (section_iterator & Result) const inline
Get section this symbol is defined in reference to. Result is end_sections() if it is undefined or is an absolute symbol.
Definition at line 433 of file ObjectFile.h.
References llvm::object::ObjectFile::getSymbolSection().
error_code llvm::object::SymbolRef::getSize (uint64_t & Result) const inline
Definition at line 425 of file ObjectFile.h.
References llvm::object::ObjectFile::getSymbolSize().
error_code llvm::object::SymbolRef::getType (SymbolRef::Type & Result) const inline
Definition at line 437 of file ObjectFile.h.
References llvm::object::ObjectFile::getSymbolType().
error_code llvm::object::SymbolRef::getValue (uint64_t & Val) const inline
Get value of the symbol in the symbol table.
Definition at line 441 of file ObjectFile.h.
References llvm::object::ObjectFile::getSymbolValue().
enum Flags llvm::object::SymbolRef::LLVM_ENUM_INT_TYPE (unsigned) inline
Definition at line 195 of file ObjectFile.h.
References llvm::Intrinsic::getName(), llvm::Intrinsic::getType(), llvm::object::operator<(), and llvm::object::operator==().
bool llvm::object::SymbolRef::operator< (const SymbolRef & Other) const inline
Definition at line 401 of file ObjectFile.h.
bool llvm::object::SymbolRef::operator== (const SymbolRef & Other) const inline
Definition at line 397 of file ObjectFile.h.
Friends And Related Function Documentation
friend class SectionRef friend
Definition at line 179 of file ObjectFile.h.
The documentation for this class was generated from the following file:
ObjectFile.h