LLVM: llvm::MachineSchedRegistry Class Reference
LLVM API Documentation
llvm::MachineSchedRegistry Class Reference
#include <MachineScheduler.h>
Public Types
typedef ScheduleDAGInstrs *(* ScheduleDAGCtor) (MachineSchedContext *)
typedef ScheduleDAGCtor FunctionPassCtor
Public Member Functions
MachineSchedRegistry (const char *N, const char *D, ScheduleDAGCtor C)
~MachineSchedRegistry ()
MachineSchedRegistry * getNext () const
Public Member Functions inherited from llvm::MachinePassRegistryNode
MachinePassRegistryNode (const char *N, const char *D, MachinePassCtor C)
MachinePassRegistryNode * getNext () const
MachinePassRegistryNode ** getNextAddress ()
const char * getName () const
const char * getDescription () const
MachinePassCtor getCtor () const
void setNext (MachinePassRegistryNode *N)
Static Public Member Functions
static MachineSchedRegistry * getList ()
static void setListener (MachinePassRegistryListener *L)
Static Public Attributes
static MachinePassRegistry Registry
Detailed Description
MachineSchedRegistry provides a selection of available machine instruction schedulers.
Definition at line 115 of file MachineScheduler.h.
Member Typedef Documentation
typedef ScheduleDAGCtor llvm::MachineSchedRegistry::FunctionPassCtor
Definition at line 120 of file MachineScheduler.h.
typedef ScheduleDAGInstrs*(* llvm::MachineSchedRegistry::ScheduleDAGCtor) (MachineSchedContext *)
Definition at line 117 of file MachineScheduler.h.
Constructor & Destructor Documentation
llvm::MachineSchedRegistry::MachineSchedRegistry (const char * N, const char * D, ScheduleDAGCtor C) inline
Definition at line 124 of file MachineScheduler.h.
References llvm::MachinePassRegistry::Add().
llvm::MachineSchedRegistry::~MachineSchedRegistry () inline
Definition at line 128 of file MachineScheduler.h.
References llvm::MachinePassRegistry::Remove().
Member Function Documentation
static MachineSchedRegistry* llvm::MachineSchedRegistry::getList () inline static
Definition at line 135 of file MachineScheduler.h.
References llvm::MachinePassRegistry::getList().
MachineSchedRegistry* llvm::MachineSchedRegistry::getNext () const inline
Definition at line 132 of file MachineScheduler.h.
References llvm::MachinePassRegistryNode::getNext().
static void llvm::MachineSchedRegistry::setListener (MachinePassRegistryListener * L) inline static
Definition at line 138 of file MachineScheduler.h.
References llvm::MachinePassRegistry::setListener().
Member Data Documentation
MachinePassRegistry MachineSchedRegistry::Registry static
Definition at line 122 of file MachineScheduler.h.
The documentation for this class was generated from the following files:
MachineScheduler.h
MachineScheduler.cpp