LLVM: llvm::MemSDNode Class Reference
LLVM API Documentation
llvm::MemSDNode Class Reference
Abstact virtual class for operations for memory operations.
#include <SelectionDAGNodes.h>
Public Member Functions
MemSDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTs, EVT MemoryVT, MachineMemOperand *MMO)
MemSDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTs, const SDValue *Ops, unsigned NumOps, EVT MemoryVT, MachineMemOperand *MMO)
bool readMem () const
bool writeMem () const
unsigned getOriginalAlignment () const
Returns alignment and volatility of the memory access.
unsigned getAlignment () const
unsigned getRawSubclassData () const
bool isVolatile () const
bool isNonTemporal () const
bool isInvariant () const
AtomicOrdering getOrdering () const
SynchronizationScope getSynchScope () const
const Value * getSrcValue () const
Returns the SrcValue and offset that describes the location of the access.
int64_t getSrcValueOffset () const
const MDNode * getTBAAInfo () const
Returns the TBAAInfo that describes the dereference.
const MDNode * getRanges () const
Returns the Ranges that describes the dereference.
EVT getMemoryVT () const
getMemoryVT - Return the type of the in-memory value.
MachineMemOperand * getMemOperand () const
const MachinePointerInfo & getPointerInfo () const
unsigned getAddressSpace () const
getAddressSpace - Return the address space for the associated pointer
void refineAlignment (const MachineMemOperand *NewMMO)
const SDValue & getChain () const
const SDValue & getBasePtr () const
Public Member Functions inherited from llvm::SDNode
unsigned getOpcode () const
bool isTargetOpcode () const
bool isTargetMemoryOpcode () const
bool isMachineOpcode () const
unsigned getMachineOpcode () const
bool getHasDebugValue () const
getHasDebugValue - get this bit.
void setHasDebugValue (bool b)
setHasDebugValue - set this bit.
bool use_empty () const
bool hasOneUse () const
size_t use_size () const
int getNodeId () const
void setNodeId (int Id)
setNodeId - Set unique node id.
unsigned getIROrder () const
void setIROrder (unsigned Order)
const DebugLoc getDebugLoc () const
getDebugLoc - Return the source location info.
void setDebugLoc (const DebugLoc dl)
use_iterator use_begin () const
bool hasNUsesOfValue (unsigned NUses, unsigned Value) const
bool hasAnyUseOfValue (unsigned Value) const
bool isOnlyUserOf (SDNode *N) const
bool isOperandOf (SDNode *N) const
bool isPredecessorOf (const SDNode *N) const
bool hasPredecessor (const SDNode *N) const
bool hasPredecessorHelper (const SDNode *N, SmallPtrSet< const SDNode *, 32 > &Visited, SmallVectorImpl< const SDNode * > &Worklist) const
unsigned getNumOperands () const
uint64_t getConstantOperandVal (unsigned Num) const
const SDValue & getOperand (unsigned Num) const
op_iterator op_begin () const
op_iterator op_end () const
SDVTList getVTList () const
SDNode * getGluedNode () const
const SDNode * getGluedMachineNode () const
SDNode * getGluedUser () const
unsigned getNumValues () const
EVT getValueType (unsigned ResNo) const
MVT getSimpleValueType (unsigned ResNo) const
unsigned getValueSizeInBits (unsigned ResNo) const
value_iterator value_begin () const
value_iterator value_end () const
std::string getOperationName (const SelectionDAG *G=0) const
void print_types (raw_ostream &OS, const SelectionDAG *G) const
void print_details (raw_ostream &OS, const SelectionDAG *G) const
void print (raw_ostream &OS, const SelectionDAG *G=0) const
void printr (raw_ostream &OS, const SelectionDAG *G=0) const
void printrFull (raw_ostream &O, const SelectionDAG *G=0) const
void printrWithDepth (raw_ostream &O, const SelectionDAG *G=0, unsigned depth=100) const
void dump () const
dump - Dump this node, for debugging.
void dumpr () const
dumpr - Dump (recursively) this node and its use-def subgraph.
void dump (const SelectionDAG *G) const
void dumpr (const SelectionDAG *G) const
void dumprFull (const SelectionDAG *G=0) const
void dumprWithDepth (const SelectionDAG *G=0, unsigned depth=100) const
void Profile (FoldingSetNodeID &ID) const
void addUse (SDUse &U)
Public Member Functions inherited from llvm::FoldingSetImpl::Node
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Public Member Functions inherited from llvm::ilist_node< SDNode >
SDNode * getPrevNode ()
Get the previous node, or 0 for the list head.
const SDNode * getPrevNode () const
Get the previous node, or 0 for the list head.
SDNode * getNextNode ()
Get the next node, or 0 for the list tail.
const SDNode * getNextNode () const
Get the next node, or 0 for the list tail.
Static Public Member Functions
static bool classof (const SDNode *N)
Static Public Member Functions inherited from llvm::SDNode
static use_iterator use_end ()
static const char * getIndexedModeName (ISD::MemIndexedMode AM)
Protected Attributes
MachineMemOperand * MMO
MMO - Memory reference information.
Protected Attributes inherited from llvm::SDNode
uint16_t SubclassData: 14
Additional Inherited Members
Public Types inherited from llvm::SDNode
typedef SDUse * op_iterator
typedef const EVT * value_iterator
Protected Member Functions inherited from llvm::SDNode
SDNode (unsigned Opc, unsigned Order, const DebugLoc dl, SDVTList VTs, const SDValue *Ops, unsigned NumOps)
SDNode (unsigned Opc, unsigned Order, const DebugLoc dl, SDVTList VTs)
void InitOperands (SDUse *Ops, const SDValue &Op0)
InitOperands - Initialize the operands list of this with 1 operand.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1)
InitOperands - Initialize the operands list of this with 2 operands.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1, const SDValue &Op2)
InitOperands - Initialize the operands list of this with 3 operands.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1, const SDValue &Op2, const SDValue &Op3)
InitOperands - Initialize the operands list of this with 4 operands.
void InitOperands (SDUse *Ops, const SDValue *Vals, unsigned N)
InitOperands - Initialize the operands list of this with N operands.
void DropOperands ()
Protected Member Functions inherited from llvm::ilist_node< SDNode >
ilist_node ()
Static Protected Member Functions inherited from llvm::SDNode
static SDVTList getSDVTList (EVT VT)
Detailed Description
Abstact virtual class for operations for memory operations.
Definition at line 971 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
MemSDNode::MemSDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTs, EVT MemoryVT, MachineMemOperand * MMO)
Definition at line 6059 of file SelectionDAG.cpp.
References encodeMemSDNodeFlags(), llvm::MachineMemOperand::getSize(), llvm::EVT::getStoreSize(), llvm::MachineMemOperand::isInvariant(), llvm::MachineMemOperand::isNonTemporal(), isNonTemporal(), llvm::MachineMemOperand::isVolatile(), isVolatile(), MMO, llvm::SDNode::SubclassData, and llvm::ISD::UNINDEXED.
MemSDNode::MemSDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTs, const SDValue * Ops, unsigned NumOps, EVT MemoryVT, MachineMemOperand * MMO)
Definition at line 6070 of file SelectionDAG.cpp.
References encodeMemSDNodeFlags(), llvm::MachineMemOperand::getSize(), llvm::EVT::getStoreSize(), llvm::MachineMemOperand::isInvariant(), llvm::MachineMemOperand::isNonTemporal(), llvm::MachineMemOperand::isVolatile(), isVolatile(), MMO, llvm::SDNode::SubclassData, and llvm::ISD::UNINDEXED.
Member Function Documentation
static bool llvm::MemSDNode::classof (const SDNode * N) inline static
Definition at line 1059 of file SelectionDAGNodes.h.
References llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_XOR, llvm::ISD::ATOMIC_STORE, llvm::ISD::ATOMIC_SWAP, llvm::SDNode::getOpcode(), llvm::SDNode::isTargetMemoryOpcode(), llvm::ISD::LOAD, llvm::ISD::PREFETCH, and llvm::ISD::STORE.
unsigned llvm::MemSDNode::getAddressSpace () const inline
getAddressSpace - Return the address space for the associated pointer
Definition at line 1041 of file SelectionDAGNodes.h.
Referenced by ConstantAddressBlock(), llvm::createAMDGPUISelDag(), ExpandUnalignedStore(), findUser(), llvm::SITargetLowering::LowerOperation(), llvm::AMDGPUTargetLowering::LowerSTORE(), and llvm::R600TargetLowering::ReplaceNodeResults().
unsigned llvm::MemSDNode::getAlignment () const inline
Definition at line 995 of file SelectionDAGNodes.h.
References llvm::MachineMemOperand::getAlignment().
Referenced by adjustSubwordCmp(), BuildVectorFromScalar(), canFoldInAddressingMode(), ConstantAddressBlock(), EltsFromConsecutiveLoads(), llvm::MipsSETargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), ExpandUnalignedLoad(), ExpandUnalignedStore(), getBuildPairElt(), GetFPLibCall(), llvm::SelectionDAG::getIndexedLoad(), isConstantSplatVector(), isTruncateOf(), isWordAligned(), LowerF128Load(), LowerF128Store(), lowerFP_TO_SINT_STORE(), llvm::MipsTargetLowering::lowerLOAD(), llvm::NVPTXTargetLowering::LowerOperation(), llvm::MipsTargetLowering::lowerSTORE(), ConsecutiveMemoryChainSorter::operator()(), partitionShuffleOfConcats(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformLOADCombine(), PerformSTORECombine(), PerformVMOVRRDCombine(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifySetCC(), SkipLoadExtensionForVMULL(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), llvm::AMDGPUTargetLowering::SplitVectorStore(), and XFormVExtractWithShuffleIntoLoad().
const SDValue& llvm::MemSDNode::getBasePtr () const inline
Definition at line 1054 of file SelectionDAGNodes.h.
References llvm::ISD::STORE.
Referenced by FindBaseOffset(), isConsecutiveLS(), and ConsecutiveMemoryChainSorter::operator()().
const SDValue& llvm::MemSDNode::getChain () const inline
Definition at line 1053 of file SelectionDAGNodes.h.
Referenced by adjustSubwordCmp(), BuildVectorFromScalar(), canFoldInAddressingMode(), EltsFromConsecutiveLoads(), llvm::MipsSETargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), ExpandUnalignedLoad(), ExpandUnalignedStore(), ExtendUsesToFormExtLoad(), findConsecutiveLoad(), findUser(), getAL(), getBuildPairElt(), GetFPLibCall(), llvm::SelectionDAG::getIndexedLoad(), llvm::SelectionDAG::getIndexedStore(), getVCmpEQInst(), llvm::SelectionDAG::isConsecutiveLoad(), isConstantSplatVector(), isLoadIncOrDecStore(), isOneUseSetCC(), isTruncateOf(), isValidIndexedLoad(), isWordAligned(), LowerF128Load(), LowerF128Store(), lowerFP_TO_SINT_STORE(), lowerGR128Binary(), llvm::MipsTargetLowering::lowerLOAD(), llvm::SITargetLowering::LowerOperation(), llvm::NVPTXTargetLowering::LowerOperation(), lowerUnalignedIntStore(), OffsetFitsS11(), ConsecutiveMemoryChainSorter::operator()(), partitionShuffleOfConcats(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformLOADCombine(), PerformSINT_TO_FPCombine(), PerformSTORECombine(), PerformVMOVRRDCombine(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifySetCC(), SkipLoadExtensionForVMULL(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), and llvm::AMDGPUTargetLowering::SplitVectorStore().
MachineMemOperand* llvm::MemSDNode::getMemOperand () const inline
getMemOperand - Return a MachineMemOperand object describing the memory reference performed by operation.
Definition at line 1034 of file SelectionDAGNodes.h.
Referenced by canFoldInAddressingMode(), CombineBaseUpdate(), CombineVLDDUP(), llvm::createAMDGPUISelDag(), createLoadLR(), createStoreLR(), ExpandUnalignedLoad(), ExtendUsesToFormExtLoad(), getBuildPairElt(), GetFPLibCall(), getFusedLdStOpcode(), llvm::SelectionDAG::getIndexedStore(), isConstantSplatVector(), isOneUseSetCC(), isTruncateOf(), lowerGR128Binary(), llvm::NVPTXTargetLowering::LowerOperation(), OffsetFitsS11(), ConsecutiveMemoryChainSorter::operator()(), llvm::PPCTargetLowering::PerformDAGCombine(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::R600TargetLowering::ReplaceNodeResults(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), and llvm::AMDGPUTargetLowering::SplitVectorStore().
EVT llvm::MemSDNode::getMemoryVT () const inline
getMemoryVT - Return the type of the in-memory value.
Definition at line 1030 of file SelectionDAGNodes.h.
Referenced by AddNodeIDCustom(), adjustSubwordCmp(), BuildVectorFromScalar(), canFoldInAddressingMode(), CombineBaseUpdate(), CombineVLDDUP(), llvm::SelectionDAG::ComputeMaskedBits(), ConstantAddressBlock(), llvm::createAMDGPUISelDag(), createLoadLR(), createStoreLR(), llvm::MipsSETargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), ExpandUnalignedLoad(), ExpandUnalignedStore(), ExtendUsesToFormExtLoad(), FindBaseOffset(), findConsecutiveLoad(), findUser(), getAL(), getCodeAddrSpace(), GetFPLibCall(), getFusedLdStOpcode(), llvm::SelectionDAG::getIndexedLoad(), llvm::SelectionDAG::getIndexedStore(), getVCmpEQInst(), getVLDSTRegisterUpdateOpcode(), isConsecutiveLS(), isConstantSplatVector(), isLoadIncOrDecStore(), isNaturalMemoryOperand(), isOneUseSetCC(), isScaledConstantInRange(), isTruncateOf(), isValidIndexedLoad(), isWordAligned(), lowerGR128Binary(), llvm::MSP430TargetLowering::LowerJumpTable(), llvm::MipsTargetLowering::lowerLOAD(), llvm::NVPTXTargetLowering::LowerOperation(), llvm::MipsTargetLowering::lowerSTORE(), maskMatters(), OffsetFitsS11(), ConsecutiveMemoryChainSorter::operator()(), partitionShuffleOfConcats(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformLOADCombine(), PerformSTORECombine(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::R600TargetLowering::ReplaceNodeResults(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifySetCC(), SkipLoadExtensionForVMULL(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), and llvm::AMDGPUTargetLowering::SplitVectorStore().
AtomicOrdering llvm::MemSDNode::getOrdering () const inline
Definition at line 1012 of file SelectionDAGNodes.h.
Referenced by getVLDSTRegisterUpdateOpcode().
unsigned llvm::MemSDNode::getOriginalAlignment () const inline
Returns alignment and volatility of the memory access.
Definition at line 992 of file SelectionDAGNodes.h.
References llvm::MachineMemOperand::getBaseAlignment().
Referenced by FindBaseOffset().
const MachinePointerInfo& llvm::MemSDNode::getPointerInfo () const inline
Definition at line 1036 of file SelectionDAGNodes.h.
References llvm::MachineMemOperand::getPointerInfo().
Referenced by AddNodeIDCustom(), adjustSubwordCmp(), BuildVectorFromScalar(), canFoldInAddressingMode(), ConstantAddressBlock(), EltsFromConsecutiveLoads(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), ExpandUnalignedLoad(), ExpandUnalignedStore(), getBuildPairElt(), GetFPLibCall(), llvm::SelectionDAG::getIndexedLoad(), llvm::SelectionDAG::getIndexedStore(), isConstantSplatVector(), isDispSafeForFrameIndex(), isTruncateOf(), isWordAligned(), LowerF128Load(), lowerFP_TO_SINT_STORE(), llvm::NVPTXTargetLowering::LowerOperation(), ConsecutiveMemoryChainSorter::operator()(), partitionShuffleOfConcats(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformLOADCombine(), PerformSTORECombine(), PerformVMOVRRDCombine(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifySetCC(), and SkipLoadExtensionForVMULL().
const MDNode* llvm::MemSDNode::getRanges () const inline
Returns the Ranges that describes the dereference.
Definition at line 1027 of file SelectionDAGNodes.h.
References llvm::MachineMemOperand::getRanges().
Referenced by llvm::SelectionDAG::ComputeMaskedBits().
unsigned llvm::MemSDNode::getRawSubclassData () const inline
getRawSubclassData - Return the SubclassData value, which contains an encoding of the volatile flag, as well as bits used by subclasses. This function should only be used to compute a FoldingSetNodeID value.
Definition at line 1002 of file SelectionDAGNodes.h.
Referenced by AddNodeIDCustom(), and llvm::SelectionDAG::getIndexedStore().
const Value* llvm::MemSDNode::getSrcValue () const inline
Returns the SrcValue and offset that describes the location of the access.
Definition at line 1020 of file SelectionDAGNodes.h.
References llvm::MachineMemOperand::getValue().
Referenced by ConstantAddressBlock(), llvm::createAMDGPUISelDag(), FindBaseOffset(), getCodeAddrSpace(), and maskMatters().
int64_t llvm::MemSDNode::getSrcValueOffset () const inline
Definition at line 1021 of file SelectionDAGNodes.h.
References llvm::MachineMemOperand::getOffset().
Referenced by FindBaseOffset(), and maskMatters().
SynchronizationScope llvm::MemSDNode::getSynchScope () const inline
Definition at line 1015 of file SelectionDAGNodes.h.
const MDNode* llvm::MemSDNode::getTBAAInfo () const inline
Returns the TBAAInfo that describes the dereference.
Definition at line 1024 of file SelectionDAGNodes.h.
References llvm::MachineMemOperand::getTBAAInfo().
Referenced by BuildVectorFromScalar(), canFoldInAddressingMode(), llvm::MipsSETargetLowering::EmitInstrWithCustomInserter(), ExpandUnalignedLoad(), ExpandUnalignedStore(), FindBaseOffset(), getBuildPairElt(), GetFPLibCall(), isConstantSplatVector(), isTruncateOf(), maskMatters(), ConsecutiveMemoryChainSorter::operator()(), PerformSTORECombine(), and ShrinkLoadReplaceStoreWithStore().
bool llvm::MemSDNode::isInvariant () const inline
Definition at line 1010 of file SelectionDAGNodes.h.
Referenced by BuildVectorFromScalar(), canFoldInAddressingMode(), EltsFromConsecutiveLoads(), llvm::MipsSETargetLowering::EmitInstrWithCustomInserter(), ExpandUnalignedLoad(), getBuildPairElt(), isTruncateOf(), llvm::NVPTXTargetLowering::LowerOperation(), maskMatters(), ConsecutiveMemoryChainSorter::operator()(), partitionShuffleOfConcats(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformLOADCombine(), PerformSTORECombine(), PerformVMOVRRDCombine(), ShrinkLoadReplaceStoreWithStore(), and SkipLoadExtensionForVMULL().
bool llvm::MemSDNode::isNonTemporal () const inline
Definition at line 1009 of file SelectionDAGNodes.h.
Referenced by adjustSubwordCmp(), BuildVectorFromScalar(), canFoldInAddressingMode(), ConstantAddressBlock(), EltsFromConsecutiveLoads(), llvm::MipsSETargetLowering::EmitInstrWithCustomInserter(), ExpandUnalignedLoad(), ExpandUnalignedStore(), getBuildPairElt(), GetFPLibCall(), llvm::SelectionDAG::getIndexedLoad(), isConstantSplatVector(), isLoadIncOrDecStore(), isTruncateOf(), isWordAligned(), lowerFP_TO_SINT_STORE(), llvm::NVPTXTargetLowering::LowerOperation(), MemSDNode(), ConsecutiveMemoryChainSorter::operator()(), partitionShuffleOfConcats(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformLOADCombine(), PerformSTORECombine(), PerformVMOVRRDCombine(), ShrinkLoadReplaceStoreWithStore(), SkipLoadExtensionForVMULL(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), and llvm::AMDGPUTargetLowering::SplitVectorStore().
bool llvm::MemSDNode::isVolatile () const inline
Definition at line 1008 of file SelectionDAGNodes.h.
Referenced by adjustSubwordCmp(), BuildVectorFromScalar(), canFoldInAddressingMode(), ConstantAddressBlock(), EltsFromConsecutiveLoads(), llvm::MipsSETargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), ExpandUnalignedLoad(), ExpandUnalignedStore(), ExtendUsesToFormExtLoad(), FindBaseOffset(), getBuildPairElt(), getCodeAddrSpace(), GetFPLibCall(), llvm::SelectionDAG::getIndexedLoad(), isCalleeLoad(), isConstantSplatVector(), isSlicingProfitable(), isTruncateOf(), isWordAligned(), lowerFP_TO_SINT_STORE(), llvm::NVPTXTargetLowering::LowerOperation(), maskMatters(), MemSDNode(), ConsecutiveMemoryChainSorter::operator()(), partitionShuffleOfConcats(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformLOADCombine(), PerformSINT_TO_FPCombine(), PerformSTORECombine(), PerformVMOVRRDCombine(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifySetCC(), SkipLoadExtensionForVMULL(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), llvm::AMDGPUTargetLowering::SplitVectorStore(), and XFormVExtractWithShuffleIntoLoad().
bool llvm::MemSDNode::readMem () const inline
Definition at line 988 of file SelectionDAGNodes.h.
References llvm::MachineMemOperand::isLoad().
void llvm::MemSDNode::refineAlignment (const MachineMemOperand * NewMMO) inline
refineAlignment - Update this MemSDNode's MachineMemOperand information to reflect the alignment of NewMMO, if it has a greater alignment. This must only be used when the new alignment applies to all users of this MachineMemOperand.
Definition at line 1049 of file SelectionDAGNodes.h.
References llvm::MachineMemOperand::refineAlignment().
Referenced by llvm::PPCTargetLowering::PerformDAGCombine().
bool llvm::MemSDNode::writeMem () const inline
Definition at line 989 of file SelectionDAGNodes.h.
References llvm::MachineMemOperand::isStore().
Member Data Documentation
MachineMemOperand* llvm::MemSDNode::MMO protected
MMO - Memory reference information.
Definition at line 978 of file SelectionDAGNodes.h.
Referenced by MemSDNode().
The documentation for this class was generated from the following files:
SelectionDAGNodes.h
SelectionDAG.cpp