LLVM: llvm::AMDGPUMCInstLower Class Reference
LLVM API Documentation
llvm::AMDGPUMCInstLower Class Reference
#include <AMDGPUMCInstLower.h>
Public Member Functions
AMDGPUMCInstLower (MCContext &ctx)
void lower (const MachineInstr *MI, MCInst &OutMI) const
Lower a MachineInstr to an MCInst.
Detailed Description
Definition at line 20 of file AMDGPUMCInstLower.h.
Constructor & Destructor Documentation
AMDGPUMCInstLower::AMDGPUMCInstLower (MCContext & ctx)
Definition at line 34 of file AMDGPUMCInstLower.cpp.
Member Function Documentation
void AMDGPUMCInstLower::lower (const MachineInstr * MI, MCInst & OutMI) const
Lower a MachineInstr to an MCInst.
Definition at line 38 of file AMDGPUMCInstLower.cpp.
References llvm::MCInst::addOperand(), llvm::APFloat::convertToFloat(), llvm::MCSymbolRefExpr::Create(), llvm::MCOperand::CreateExpr(), llvm::MCOperand::CreateFPImm(), llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), llvm::MachineOperand::getFPImm(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getNumExplicitOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::APFloat::getSemantics(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getType(), llvm::ConstantFP::getValueAPF(), i, llvm::APFloat::IEEEsingle, llvm_unreachable, llvm::MachineOperand::MO_FPImmediate, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_Register, and llvm::MCInst::setOpcode().
Referenced by llvm::AMDGPUAsmPrinter::EmitInstruction().
The documentation for this class was generated from the following files:
AMDGPUMCInstLower.h
AMDGPUMCInstLower.cpp