LLVM: llvm::MachineConstantPoolValue Class Reference
LLVM API Documentation
llvm::MachineConstantPoolValue Class Reference abstract
#include <MachineConstantPool.h>
Public Member Functions
MachineConstantPoolValue (Type *ty)
virtual ~MachineConstantPoolValue ()
Type * getType () const
virtual unsigned getRelocationInfo () const =0
virtual int getExistingMachineCPValue (MachineConstantPool *CP, unsigned Alignment)=0
virtual void addSelectionDAGCSEId (FoldingSetNodeID &ID)=0
virtual void print (raw_ostream &O) const =0
print - Implement operator<<
Detailed Description
Abstract base class for all machine specific constantpool value subclasses.
Definition at line 36 of file MachineConstantPool.h.
Constructor & Destructor Documentation
llvm::MachineConstantPoolValue::MachineConstantPoolValue (Type * ty) inline explicit
Definition at line 41 of file MachineConstantPool.h.
virtual llvm::MachineConstantPoolValue::~MachineConstantPoolValue () inline virtual
Definition at line 42 of file MachineConstantPool.h.
Member Function Documentation
virtual void llvm::MachineConstantPoolValue::addSelectionDAGCSEId (FoldingSetNodeID & ID) pure virtual
Implemented in llvm::ARMConstantPoolMBB, llvm::ARMConstantPoolSymbol, llvm::ARMConstantPoolConstant, llvm::ARMConstantPoolValue, and llvm::SystemZConstantPoolValue.
Referenced by AddNodeIDCustom(), llvm::SelectionDAG::getConstantPool(), and getType().
virtual int llvm::MachineConstantPoolValue::getExistingMachineCPValue (MachineConstantPool * CP, unsigned Alignment) pure virtual
Implemented in llvm::ARMConstantPoolMBB, llvm::ARMConstantPoolSymbol, llvm::ARMConstantPoolConstant, llvm::ARMConstantPoolValue, and llvm::SystemZConstantPoolValue.
Referenced by llvm::MachineConstantPool::getConstantPoolIndex(), and getType().
virtual unsigned llvm::MachineConstantPoolValue::getRelocationInfo () const pure virtual
getRelocationInfo - This method classifies the entry according to whether or not it may generate a relocation entry. This must be conservative, so if it might codegen to a relocatable entry, it should say so. The return values are the same as Constant::getRelocationInfo().
Implemented in llvm::ARMConstantPoolValue, and llvm::SystemZConstantPoolValue.
Referenced by llvm::MachineConstantPoolEntry::getAlignment(), and getType().
Type* llvm::MachineConstantPoolValue::getType () const inline
getType - get type of this MachineConstantPoolValue.
Definition at line 46 of file MachineConstantPool.h.
References addSelectionDAGCSEId(), getExistingMachineCPValue(), getRelocationInfo(), and print().
Referenced by llvm::SystemZAsmPrinter::EmitMachineConstantPoolValue(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), llvm::MachineConstantPoolEntry::getAlignment(), and llvm::SelectionDAG::getConstantPool().
virtual void llvm::MachineConstantPoolValue::print (raw_ostream & O) const pure virtual
print - Implement operator<<
Implemented in llvm::ARMConstantPoolMBB, llvm::ARMConstantPoolSymbol, llvm::ARMConstantPoolConstant, llvm::ARMConstantPoolValue, and llvm::SystemZConstantPoolValue.
Referenced by llvm::MachineConstantPool::getConstants(), getType(), and llvm::operator<<().
The documentation for this class was generated from the following files:
MachineConstantPool.h
MachineFunction.cpp