LLVM: llvm::BitcodeReader Class Reference
LLVM API Documentation
llvm::BitcodeReader Class Reference
#include <BitcodeReader.h>
Public Types
enum ErrorType {
BitcodeStreamInvalidSize, ConflictingMETADATA_KINDRecords, CouldNotFindFunctionInStream, ExpectedConstant,
InsufficientFunctionProtos, InvalidBitcodeSignature, InvalidBitcodeWrapperHeader, InvalidConstantReference,
InvalidID, InvalidInstructionWithNoBB, InvalidRecord, InvalidTypeForValue,
InvalidTYPETable, InvalidType, MalformedBlock, MalformedGlobalInitializerSet,
InvalidMultipleBlocks, NeverResolvedValueFoundInFunction, InvalidValue
}
Public Member Functions
error_code Error (ErrorType E)
BitcodeReader (MemoryBuffer *buffer, LLVMContext &C)
BitcodeReader (DataStreamer *streamer, LLVMContext &C)
~BitcodeReader ()
void materializeForwardReferencedFunctions ()
void FreeState ()
void setBufferOwned (bool Owned)
virtual bool isMaterializable (const GlobalValue *GV) const
virtual bool isDematerializable (const GlobalValue *GV) const
virtual error_code Materialize (GlobalValue *GV)
virtual error_code MaterializeModule (Module *M)
virtual void Dematerialize (GlobalValue *GV)
error_code ParseBitcodeInto (Module *M)
Main interface to parsing a bitcode buffer.
error_code ParseTriple (std::string &Triple)
Cheap mechanism to just extract module triple.
Public Member Functions inherited from llvm::GVMaterializer
virtual ~GVMaterializer ()
Static Public Member Functions
static uint64_t decodeSignRotatedValue (uint64_t V)
Additional Inherited Members
Protected Member Functions inherited from llvm::GVMaterializer
GVMaterializer ()
Detailed Description
Definition at line 125 of file BitcodeReader.h.
Member Enumeration Documentation
enum llvm::BitcodeReader::ErrorType
Enumerator
BitcodeStreamInvalidSize
ConflictingMETADATA_KINDRecords
CouldNotFindFunctionInStream
ExpectedConstant
InsufficientFunctionProtos
InvalidBitcodeSignature
InvalidBitcodeWrapperHeader
InvalidConstantReference
InvalidID
InvalidInstructionWithNoBB
InvalidRecord
InvalidTypeForValue
InvalidTYPETable
InvalidType
MalformedBlock
MalformedGlobalInitializerSet
InvalidMultipleBlocks
NeverResolvedValueFoundInFunction
InvalidValue
Definition at line 199 of file BitcodeReader.h.
Constructor & Destructor Documentation
llvm::BitcodeReader::BitcodeReader (MemoryBuffer * buffer, LLVMContext & C) inline explicit
Definition at line 226 of file BitcodeReader.h.
Referenced by llvm::getBitcodeTargetTriple(), llvm::getLazyBitcodeModule(), and llvm::getStreamedBitcodeModule().
llvm::BitcodeReader::BitcodeReader (DataStreamer * streamer, LLVMContext & C) inline explicit
Definition at line 232 of file BitcodeReader.h.
llvm::BitcodeReader::~BitcodeReader () inline
Definition at line 238 of file BitcodeReader.h.
Member Function Documentation
uint64_t BitcodeReader::decodeSignRotatedValue (uint64_t V) static
decodeSignRotatedValue - Decode a signed value stored with the sign bit in the LSB for dense VBR encoding.
Definition at line 1065 of file BitcodeReader.cpp.
References Error(), ExpectedConstant, and llvm::error_code::success().
Referenced by ReadWideAPInt().
void BitcodeReader::Dematerialize (GlobalValue *) virtual
Dematerialize - If the given GlobalValue is read in, and if the GVMaterializer supports it, release the memory for the GV, and set it up to be materialized lazily. If the Materializer doesn't support this capability, this method is a noop.
Reimplemented from llvm::GVMaterializer.
Definition at line 3102 of file BitcodeReader.cpp.
References llvm::Function::deleteBody(), llvm::dyn_cast(), and isDematerializable().
error_code llvm::BitcodeReader::Error (ErrorType E) inline
Definition at line 222 of file BitcodeReader.h.
Referenced by decodeLLVMAttributesForBitcode(), decodeSignRotatedValue(), GetAttrFromCode(), MaterializeModule(), ParseBitcodeInto(), ParseTriple(), and ReadWideAPInt().
void BitcodeReader::FreeState ()
Definition at line 41 of file BitcodeReader.cpp.
References llvm::BitcodeReaderValueList::clear(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::clear(), llvm::BitcodeReaderMDValueList::clear(), and llvm::swap().
bool BitcodeReader::isDematerializable (const GlobalValue * GV) const virtual
isDematerializable - True if GV has been materialized and can be dematerialized back to whatever backing store this GVMaterializer uses.
Implements llvm::GVMaterializer.
Definition at line 3095 of file BitcodeReader.cpp.
References llvm::dyn_cast(), and llvm::GlobalValue::isDeclaration().
Referenced by Dematerialize().
bool BitcodeReader::isMaterializable (const GlobalValue * GV) const virtual
isMaterializable - True if GV can be materialized from whatever backing store this GVMaterializer uses and has not been materialized yet.
Implements llvm::GVMaterializer.
Definition at line 3052 of file BitcodeReader.cpp.
References llvm::GlobalValue::isDeclaration().
error_code BitcodeReader::Materialize (GlobalValue * GV) virtual
Materialize - make sure the given GlobalValue is fully read.
Implements llvm::GVMaterializer.
Definition at line 3060 of file BitcodeReader.cpp.
References llvm::dyn_cast(), I, llvm::GlobalValue::isMaterializable(), llvm::error_code::success(), and llvm::UpgradeIntrinsicCall().
Referenced by MaterializeModule().
void BitcodeReader::materializeForwardReferencedFunctions ()
Definition at line 34 of file BitcodeReader.cpp.
References F(), and llvm::GlobalValue::Materialize().
error_code BitcodeReader::MaterializeModule (Module * M) virtual
MaterializeModule - make sure the entire Module has been completely read.
Implements llvm::GVMaterializer.
Definition at line 3115 of file BitcodeReader.cpp.
References llvm::Function::begin(), BitcodeStreamInvalidSize, ConflictingMETADATA_KINDRecords, CouldNotFindFunctionInStream, llvm::StreamingMemoryObject::dropLeadingBytes(), Error(), ExpectedConstant, F(), I, llvm::ARM_PROC::IE, InsufficientFunctionProtos, InvalidBitcodeSignature, InvalidBitcodeWrapperHeader, InvalidConstantReference, InvalidID, InvalidInstructionWithNoBB, InvalidMultipleBlocks, InvalidRecord, InvalidType, InvalidTypeForValue, InvalidTYPETable, InvalidValue, llvm::isBitcode(), llvm::isBitcodeWrapper(), llvm::GlobalValue::isMaterializable(), llvm::isRawBitcode(), LLVM_OVERRIDE, llvm_unreachable, MalformedBlock, MalformedGlobalInitializerSet, Materialize(), message(), NeverResolvedValueFoundInFunction, llvm::StreamingMemoryObject::readBytes(), llvm::StreamingMemoryObject::setKnownObjectSize(), llvm::SkipBitcodeWrapperHeader(), llvm::error_code::success(), llvm::swap(), llvm::UpgradeDebugInfo(), llvm::UpgradeInstWithTBAATag(), and llvm::UpgradeIntrinsicCall().
error_code BitcodeReader::ParseBitcodeInto (Module * M)
Main interface to parsing a bitcode buffer.
Returns
true if an error occurred.
Definition at line 1934 of file BitcodeReader.cpp.
References llvm::BitstreamCursor::AF_DontAutoprocessAbbrevs, llvm::bitc::BLOCKINFO_BLOCK_ID, llvm::SmallVectorImpl< T >::clear(), ConvertToString(), llvm::BitstreamEntry::EndBlock, llvm::BitstreamEntry::Error, Error(), llvm::BitstreamEntry::ID, InvalidBitcodeSignature, InvalidMultipleBlocks, InvalidRecord, llvm::BitstreamEntry::Kind, M, MalformedBlock, llvm::bitc::MODULE_BLOCK_ID, llvm::bitc::MODULE_CODE_TRIPLE, llvm::BitstreamEntry::Record, S, llvm::BitstreamEntry::SubBlock, and llvm::error_code::success().
Referenced by llvm::getStreamedBitcodeModule().
error_code BitcodeReader::ParseTriple (std::string & Triple)
Cheap mechanism to just extract module triple.
Returns
true if an error occurred.
Definition at line 2038 of file BitcodeReader.cpp.
References llvm::ARM_PROC::A, llvm::Acquire, llvm::AcquireRelease, llvm::SwitchInst::addCase(), llvm::LandingPadInst::addClause(), llvm::IndirectBrInst::addDestination(), llvm::PHINode::addIncoming(), Align, llvm::FastMathFlags::AllowReciprocal, llvm::FastMathFlags::any(), llvm::Function::arg_begin(), llvm::Function::arg_end(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::BasicBlock::back(), BB, llvm::SmallVectorTemplateCommon< T >::begin(), llvm::LandingPadInst::Catch, llvm::SmallVectorImpl< T >::clear(), llvm::error_code::clear(), llvm::bitc::CONSTANTS_BLOCK_ID, CouldNotFindFunctionInStream, llvm::BasicBlock::Create(), llvm::BinaryOperator::Create(), llvm::CastInst::Create(), llvm::GetElementPtrInst::Create(), llvm::CallInst::Create(), llvm::SelectInst::Create(), llvm::ExtractElementInst::Create(), llvm::InsertElementInst::Create(), llvm::ExtractValueInst::Create(), llvm::InsertValueInst::Create(), llvm::PHINode::Create(), llvm::LandingPadInst::Create(), llvm::ReturnInst::Create(), llvm::BranchInst::Create(), llvm::SwitchInst::Create(), llvm::IndirectBrInst::Create(), llvm::InvokeInst::Create(), llvm::ResumeInst::Create(), llvm::Reloc::Default, llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::BasicBlock::empty(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::BitstreamEntry::EndBlock, llvm::GlobalVariable::eraseFromParent(), llvm::BitstreamEntry::Error, Error(), F(), llvm::LandingPadInst::Filter, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::find(), llvm::AtomicRMWInst::FIRST_BINOP, llvm::bitc::FUNC_CODE_DEBUG_LOC, llvm::bitc::FUNC_CODE_DEBUG_LOC_AGAIN, llvm::bitc::FUNC_CODE_DECLAREBLOCKS, llvm::bitc::FUNC_CODE_INST_ALLOCA, llvm::bitc::FUNC_CODE_INST_ATOMICRMW, llvm::bitc::FUNC_CODE_INST_BINOP, llvm::bitc::FUNC_CODE_INST_BR, llvm::bitc::FUNC_CODE_INST_CALL, llvm::bitc::FUNC_CODE_INST_CAST, llvm::bitc::FUNC_CODE_INST_CMP, llvm::bitc::FUNC_CODE_INST_CMP2, llvm::bitc::FUNC_CODE_INST_CMPXCHG, llvm::bitc::FUNC_CODE_INST_EXTRACTELT, llvm::bitc::FUNC_CODE_INST_EXTRACTVAL, llvm::bitc::FUNC_CODE_INST_FENCE, llvm::bitc::FUNC_CODE_INST_GEP, llvm::bitc::FUNC_CODE_INST_INBOUNDS_GEP, llvm::bitc::FUNC_CODE_INST_INDIRECTBR, llvm::bitc::FUNC_CODE_INST_INSERTELT, llvm::bitc::FUNC_CODE_INST_INSERTVAL, llvm::bitc::FUNC_CODE_INST_INVOKE, llvm::bitc::FUNC_CODE_INST_LANDINGPAD, llvm::bitc::FUNC_CODE_INST_LOAD, llvm::bitc::FUNC_CODE_INST_LOADATOMIC, llvm::bitc::FUNC_CODE_INST_PHI, llvm::bitc::FUNC_CODE_INST_RESUME, llvm::bitc::FUNC_CODE_INST_RET, llvm::bitc::FUNC_CODE_INST_SELECT, llvm::bitc::FUNC_CODE_INST_SHUFFLEVEC, llvm::bitc::FUNC_CODE_INST_STORE, llvm::bitc::FUNC_CODE_INST_STOREATOMIC, llvm::bitc::FUNC_CODE_INST_SWITCH, llvm::bitc::FUNC_CODE_INST_UNREACHABLE, llvm::bitc::FUNC_CODE_INST_VAARG, llvm::bitc::FUNC_CODE_INST_VSELECT, llvm::bitc::FUNCTION_BLOCK_ID, llvm::DebugLoc::get(), llvm::ConstantInt::get(), llvm::BlockAddress::get(), llvm::UndefValue::get(), getBitWidth(), GetDecodedBinaryOpcode(), GetDecodedCastOpcode(), GetDecodedOrdering(), GetDecodedRMWOperation(), GetDecodedSynchScope(), llvm::SequentialType::getElementType(), llvm::BasicBlock::getInstList(), llvm::Type::getInt1Ty(), llvm::Type::getInt32Ty(), llvm::Value::getType(), i, I, llvm::BitstreamEntry::ID, InvalidBitcodeSignature, InvalidID, InvalidInstructionWithNoBB, InvalidRecord, InvalidTypeForValue, InvalidValue, llvm::Type::isFPOrFPVectorTy(), llvm::Type::isVoidTy(), llvm::BitstreamEntry::Kind, llvm::AtomicRMWInst::LAST_BINOP, llvm::makeArrayRef(), MalformedBlock, llvm::LLVMContext::MD_tbaa, llvm::bitc::METADATA_ATTACHMENT, llvm::bitc::METADATA_ATTACHMENT_ID, llvm::bitc::METADATA_BLOCK_ID, llvm::bitc::MODULE_BLOCK_ID, llvm::Monotonic, NeverResolvedValueFoundInFunction, llvm::FastMathFlags::NoInfs, llvm::FastMathFlags::NoNaNs, llvm::FastMathFlags::NoSignedZeros, llvm::NotAtomic, llvm::bitc::OBO_NO_SIGNED_WRAP, llvm::bitc::OBO_NO_UNSIGNED_WRAP, llvm::bitc::PEO_EXACT, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::iplist< NodeTy, Traits >::push_back(), ReadWideAPInt(), llvm::BitstreamEntry::Record, llvm::Release, llvm::Value::replaceAllUsesWith(), llvm::FastMathFlags::setAllowReciprocal(), llvm::LandingPadInst::setCleanup(), llvm::Instruction::setDebugLoc(), llvm::Instruction::setFastMathFlags(), llvm::Instruction::setMetadata(), llvm::FastMathFlags::setNoInfs(), llvm::FastMathFlags::setNoNaNs(), llvm::FastMathFlags::setNoSignedZeros(), llvm::FastMathFlags::setUnsafeAlgebra(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::BasicBlock::size(), llvm::BitstreamEntry::SubBlock, llvm::error_code::success(), llvm::swap(), SWITCH_INST_MAGIC, llvm::APInt::ule(), llvm::Unordered, llvm::FastMathFlags::UnsafeAlgebra, llvm::UpgradeBitCastInst(), and llvm::bitc::VALUE_SYMTAB_BLOCK_ID.
Referenced by llvm::getBitcodeTargetTriple().
void llvm::BitcodeReader::setBufferOwned (bool Owned) inline
setBufferOwned - If this is true, the reader will destroy the MemoryBuffer when the reader is destroyed.
Definition at line 248 of file BitcodeReader.h.
References llvm::tgtok::Code, F(), llvm::Intrinsic::getAttributes(), llvm::BitcodeReaderValueList::getValueFwdRef(), llvm::BitcodeReaderMDValueList::getValueFwdRef(), i, llvm::Type::isMetadataTy(), M, and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by llvm::getBitcodeTargetTriple(), llvm::getStreamedBitcodeModule(), and llvm::ParseBitcodeFile().
The documentation for this class was generated from the following files:
BitcodeReader.h
BitcodeReader.cpp