LLVM: llvm::ArrayRef< T > Class Template Reference
LLVM API Documentation
llvm::ArrayRef< T > Class Template Reference
#include <ArrayRef.h>
Public Types
typedef const T * iterator
typedef const T * const_iterator
typedef size_t size_type
typedef std::reverse_iterator< iterator > reverse_iterator
Public Member Functions
Constructors
ArrayRef ()
Construct an empty ArrayRef.
ArrayRef (NoneType)
Construct an empty ArrayRef from None.
ArrayRef (const T &OneElt)
Construct an ArrayRef from a single element.
ArrayRef (const T *data, size_t length)
Construct an ArrayRef from a pointer and length.
ArrayRef (const T *begin, const T *end)
Construct an ArrayRef from a range.
template<typename U >
ArrayRef (const SmallVectorTemplateCommon< T, U > &Vec)
template<typename A >
ArrayRef (const std::vector< T, A > &Vec)
Construct an ArrayRef from a std::vector.
template<size_t N>
LLVM_CONSTEXPR ArrayRef (const T(&Arr)[N])
Construct an ArrayRef from a C array.
Simple Operations
iterator begin () const
iterator end () const
reverse_iterator rbegin () const
reverse_iterator rend () const
bool empty () const
empty - Check if the array is empty.
const T * data () const
size_t size () const
size - Get the array size.
const T & front () const
front - Get the first element.
const T & back () const
back - Get the last element.
bool equals (ArrayRef RHS) const
equals - Check for element-wise equality.
ArrayRef< T > slice (unsigned N) const
slice(n) - Chop off the first N elements of the array.
ArrayRef< T > slice (unsigned N, unsigned M) const
Operator Overloads
const T & operator[] (size_t Index) const
Expensive Operations
std::vector< T > vec () const
Conversion operators
operator std::vector< T > () const
Detailed Description
template<typename T>
class llvm::ArrayRef< T >
ArrayRef - Represent a constant reference to an array (0 or more elements consecutively in memory), i.e. a start pointer and a length. It allows various APIs to take consecutive elements easily and conveniently.
This class does not own the underlying data, it is expected to be used in situations where the data resides in some other buffer, whose lifetime extends past that of the ArrayRef. For this reason, it is not in general safe to store an ArrayRef.
This is intended to be trivially copyable, so it should be passed by value.
Definition at line 31 of file ArrayRef.h.
Member Typedef Documentation
template<typename T> typedef const T* llvm::ArrayRef< T >::const_iterator
Definition at line 34 of file ArrayRef.h.
template<typename T> typedef const T* llvm::ArrayRef< T >::iterator
Definition at line 33 of file ArrayRef.h.
template<typename T> typedef std::reverse_iterator<iterator> llvm::ArrayRef< T >::reverse_iterator
Definition at line 37 of file ArrayRef.h.
template<typename T> typedef size_t llvm::ArrayRef< T >::size_type
Definition at line 35 of file ArrayRef.h.
Constructor & Destructor Documentation
template<typename T> llvm::ArrayRef< T >::ArrayRef () inline
Construct an empty ArrayRef.
Definition at line 51 of file ArrayRef.h.
Referenced by llvm::ArrayRef< uint8_t >::ArrayRef().
template<typename T> llvm::ArrayRef< T >::ArrayRef (NoneType) inline
Construct an empty ArrayRef from None.
Definition at line 54 of file ArrayRef.h.
template<typename T> llvm::ArrayRef< T >::ArrayRef (const T & OneElt) inline
Construct an ArrayRef from a single element.
Definition at line 57 of file ArrayRef.h.
template<typename T> llvm::ArrayRef< T >::ArrayRef (const T * data, size_t length) inline
Construct an ArrayRef from a pointer and length.
Definition at line 61 of file ArrayRef.h.
template<typename T> llvm::ArrayRef< T >::ArrayRef (const T * begin, const T * end) inline
Construct an ArrayRef from a range.
Definition at line 65 of file ArrayRef.h.
template<typename T> template<typename U > llvm::ArrayRef< T >::ArrayRef (const SmallVectorTemplateCommon< T, U > & Vec) inline
Construct an ArrayRef from a SmallVector. This is templated in order to avoid instantiating SmallVectorTemplateCommon<T> whenever we copy-construct an ArrayRef.
Definition at line 72 of file ArrayRef.h.
template<typename T> template<typename A > llvm::ArrayRef< T >::ArrayRef (const std::vector< T, A > & Vec) inline
Construct an ArrayRef from a std::vector.
Definition at line 78 of file ArrayRef.h.
template<typename T> template<size_t N> LLVM_CONSTEXPR llvm::ArrayRef< T >::ArrayRef (const T(&) Arr[N]) inline
Construct an ArrayRef from a C array.
Definition at line 83 of file ArrayRef.h.
Member Function Documentation
template<typename T> const T& llvm::ArrayRef< T >::back () const inline
back - Get the last element.
Definition at line 118 of file ArrayRef.h.
Referenced by llvm::ConstantFoldInstOperands(), llvm::createGreedyRegisterAllocator(), and llvm::isAllocaPromotable().
template<typename T> iterator llvm::ArrayRef< T >::begin () const inline
Definition at line 97 of file ArrayRef.h.
Referenced by llvm::SpillPlacement::addConstraints(), llvm::SpillPlacement::addLinks(), llvm::SpillPlacement::addPrefSpill(), llvm::AllocationOrder::AllocationOrder(), buildExtractionBlockSet(), buildFixItLine(), BuildSubAggregate(), llvm::LiveIntervals::checkRegMaskInterference(), LTOCodeGenerator::compile(), llvm::SchedDFSResult::compute(), llvm::ScheduleDAGMI::computeCyclicCriticalPath(), llvm::ComputeLinearIndex(), llvm::ConstantArray::ConstantArray(), ConstantFoldGetElementPtrImpl(), llvm::ConstantStruct::ConstantStruct(), llvm::ConstantVector::ConstantVector(), containsReg(), llvm::convertUTF16ToUTF8String(), llvm::DIBuilder::createComplexVariable(), llvm::CallInst::CreateFree(), llvm::createGreedyRegisterAllocator(), llvm::discoverAndMapSubloop(), llvm::DwarfAccelTable::Atom::dump(), llvm::ScheduleDAGMI::dumpSchedule(), llvm::TargetLoweringObjectFileMachO::emitModuleFlags(), llvm::TargetLoweringObjectFileCOFF::emitModuleFlags(), llvm::FenceInst::FenceInst(), llvm::FindInsertedValue(), llvm::gep_type_begin(), llvm::AttributeSetNode::get(), llvm::AttributeSet::get(), llvm::ConstantArray::get(), llvm::MachineTraceMetrics::Ensemble::getLoopFor(), llvm::ARMBaseRegisterInfo::getRegAllocationHints(), llvm::TargetRegisterInfo::getRegAllocationHints(), llvm::ShuffleVectorInst::getShuffleMask(), getTypePartition(), INITIALIZE_PASS(), llvm::RegPressureTracker::initLiveThru(), llvm::ScheduleDAGMI::initQueues(), llvm::isAllocaPromotable(), isHorizontalBinOp(), isIntegerWideningViable(), isVectorPromotionViable(), LowerVECTOR_SHUFFLEv8i8(), llvm::makeArrayRef(), ProfileBitsInit(), ProfileDagInit(), ProfileListInit(), ReadWideAPInt(), llvm::ArrayRef< uint8_t >::rend(), llvm::MutableArrayRef< T >::rend(), llvm::MachineModuleInfo::setCallSiteLandingPad(), llvm::PMTopLevelManager::setLastUser(), llvm::MachineInstr::setPhysRegsDeadExcept(), llvm::SimplifyCall(), llvm::SelectionDAG::TransferDbgValues(), UpdateAnalysisInformation(), llvm::object::yaml::BinaryRef::writeAsHex(), and llvm::CallInst::~CallInst().
template<typename T> const T* llvm::ArrayRef< T >::data () const inline
Definition at line 106 of file ArrayRef.h.
Referenced by llvm::MutableArrayRef< T >::back(), llvm::MutableArrayRef< T >::begin(), llvm::MutableArrayRef< T >::data(), llvm::MutableArrayRef< T >::end(), llvm::MutableArrayRef< T >::front(), llvm::ConstantDataArray::get(), llvm::ConstantDataVector::get(), getDigit(), llvm::ConstantExpr::getGetElementPtr(), llvm::SelectionDAG::getMachineNode(), llvm::object::MachOObjectFile::getSectionFinalSegmentName(), llvm::object::MachOObjectFile::getSectionName(), llvm::object::COFFObjectFile::getSectionSize(), llvm::makeArrayRef(), llvm::MutableArrayRef< T >::operator[](), llvm::StructType::setBody(), llvm::ArrayRef< uint8_t >::slice(), llvm::MutableArrayRef< T >::slice(), SymbolicallyEvaluateGEP(), llvm::MD5::update(), llvm::object::yaml::BinaryRef::writeAsBinary(), and llvm::object::yaml::BinaryRef::writeAsHex().
template<typename T> bool llvm::ArrayRef< T >::empty () const inline
empty - Check if the array is empty.
Definition at line 104 of file ArrayRef.h.
Referenced by llvm::SpillPlacement::addLinks(), llvm::ArrayRef< uint8_t >::back(), llvm::MutableArrayRef< T >::back(), buildFixItLine(), computeExcessPressureDelta(), llvm::ConstantFoldExtractValueInstruction(), ConstantFoldGetElementPtrImpl(), llvm::ConstantFoldInsertValueInstruction(), llvm::convertUTF16ToUTF8String(), llvm::StructType::create(), CriticalPathStep(), llvm::FindInsertedValue(), llvm::ArrayRef< uint8_t >::front(), llvm::MutableArrayRef< T >::front(), llvm::AttributeSetNode::get(), llvm::AttributeSet::get(), llvm::ConstantArray::get(), llvm::ConstantStruct::get(), llvm::ConstantVector::get(), getIndexedTypeInternal(), llvm::Intrinsic::getName(), llvm::DIBuilder::getOrCreateArray(), llvm::Intrinsic::getType(), llvm::ConstantStruct::getTypeForElements(), isContiguous(), isInBoundsIndices(), llvm::object::yaml::operator==(), llvm::PrintMessage(), llvm::PromoteMemToReg(), pushDepHeight(), and truncateToSize().
template<typename T> iterator llvm::ArrayRef< T >::end () const inline
Definition at line 98 of file ArrayRef.h.
Referenced by llvm::SpillPlacement::addConstraints(), llvm::SpillPlacement::addLinks(), llvm::SpillPlacement::addPrefSpill(), llvm::AllocationOrder::AllocationOrder(), buildExtractionBlockSet(), buildFixItLine(), BuildSubAggregate(), llvm::LiveIntervals::checkRegMaskInterference(), LTOCodeGenerator::compile(), llvm::SchedDFSResult::compute(), llvm::ScheduleDAGMI::computeCyclicCriticalPath(), llvm::ComputeLinearIndex(), llvm::ConstantArray::ConstantArray(), ConstantFoldGetElementPtrImpl(), llvm::ConstantStruct::ConstantStruct(), llvm::ConstantVector::ConstantVector(), containsReg(), llvm::convertUTF16ToUTF8String(), llvm::DIBuilder::createComplexVariable(), llvm::CallInst::CreateFree(), llvm::createGreedyRegisterAllocator(), llvm::discoverAndMapSubloop(), llvm::DwarfAccelTable::Atom::dump(), llvm::ScheduleDAGMI::dumpSchedule(), llvm::TargetLoweringObjectFileMachO::emitModuleFlags(), llvm::TargetLoweringObjectFileCOFF::emitModuleFlags(), llvm::FenceInst::FenceInst(), llvm::FindInsertedValue(), llvm::gep_type_end(), llvm::AttributeSetNode::get(), llvm::AttributeSet::get(), llvm::ConstantArray::get(), llvm::MachineTraceMetrics::Ensemble::getLoopFor(), llvm::ARMBaseRegisterInfo::getRegAllocationHints(), llvm::TargetRegisterInfo::getRegAllocationHints(), llvm::ShuffleVectorInst::getShuffleMask(), getTypePartition(), INITIALIZE_PASS(), llvm::RegPressureTracker::initLiveThru(), llvm::ScheduleDAGMI::initQueues(), llvm::isAllocaPromotable(), isHorizontalBinOp(), isIntegerWideningViable(), isVectorPromotionViable(), LowerVECTOR_SHUFFLEv8i8(), llvm::makeArrayRef(), ProfileBitsInit(), ProfileDagInit(), ProfileListInit(), llvm::ArrayRef< uint8_t >::rbegin(), llvm::MutableArrayRef< T >::rbegin(), ReadWideAPInt(), llvm::MachineModuleInfo::setCallSiteLandingPad(), llvm::PMTopLevelManager::setLastUser(), llvm::MachineInstr::setPhysRegsDeadExcept(), llvm::SimplifyCall(), llvm::SelectionDAG::TransferDbgValues(), UpdateAnalysisInformation(), llvm::object::yaml::BinaryRef::writeAsHex(), and llvm::CallInst::~CallInst().
template<typename T> bool llvm::ArrayRef< T >::equals (ArrayRef< T > RHS) const inline
equals - Check for element-wise equality.
Definition at line 124 of file ArrayRef.h.
Referenced by llvm::operator==().
template<typename T> const T& llvm::ArrayRef< T >::front () const inline
front - Get the first element.
Definition at line 112 of file ArrayRef.h.
Referenced by llvm::PBQPBuilderWithCoalescing::build(), llvm::createGreedyRegisterAllocator(), DecodeFixedType(), llvm::ConstantVector::get(), isContiguous(), and llvm::PrintMessage().
template<typename T> llvm::ArrayRef< T >::operator std::vector< T > () const inline
Definition at line 164 of file ArrayRef.h.
template<typename T> const T& llvm::ArrayRef< T >::operator[] (size_t Index) const inline
Definition at line 149 of file ArrayRef.h.
template<typename T> reverse_iterator llvm::ArrayRef< T >::rbegin () const inline
Definition at line 100 of file ArrayRef.h.
Referenced by getNoopInput(), and llvm::ScheduleDAGMI::initQueues().
template<typename T> reverse_iterator llvm::ArrayRef< T >::rend () const inline
Definition at line 101 of file ArrayRef.h.
Referenced by getNoopInput(), and llvm::ScheduleDAGMI::initQueues().
template<typename T> size_t llvm::ArrayRef< T >::size () const inline
size - Get the array size.
Definition at line 109 of file ArrayRef.h.
Referenced by llvm::MachineModuleInfo::addCatchTypeInfo(), llvm::MachineModuleInfo::addFilterTypeInfo(), llvm::RegPressureTracker::addLiveRegs(), llvm::MutableArrayRef< T >::back(), llvm::object::yaml::BinaryRef::binary_size(), llvm::PBQPBuilder::build(), BuildNew(), CanEvaluateShuffled(), CastGEPIndices(), llvm::ComputeEditDistance(), computeExcessPressureDelta(), computeMaxPressureDelta(), llvm::ConstantArray::ConstantArray(), llvm::ConstantFoldCall(), ConstantFoldGetElementPtrImpl(), llvm::ConstantFoldInstOperands(), llvm::ConstantFoldLoadThroughGEPIndices(), llvm::ConstantStruct::ConstantStruct(), llvm::ConstantVector::ConstantVector(), ConvertToString(), llvm::convertUTF16ToUTF8String(), llvm::GetElementPtrConstantExpr::Create(), llvm::ConstantArrayCreator< ConstantClass, TypeClass >::create(), llvm::GetElementPtrInst::Create(), llvm::CallInst::Create(), llvm::InvokeInst::Create(), llvm::MDBuilder::createBranchWeights(), llvm::CallInst::CreateFree(), llvm::IRBuilder< true, TargetFolder >::CreateGEP(), llvm::createGreedyRegisterAllocator(), llvm::IRBuilder< true, TargetFolder >::CreateInBoundsGEP(), createPHIsForSplitLoopExit(), llvm::MDBuilder::createTBAAStructNode(), CriticalPathStep(), DecodeIITType(), llvm::RegPressureTracker::decreaseRegPressure(), llvm::SelectionDAG::DeleteNode(), llvm::dumpRegSetPressure(), llvm::ScheduleDAGMI::dumpSchedule(), llvm::LiveRangeEdit::eliminateDeadDefs(), llvm::MCDwarfFrameEmitter::Emit(), EmitEncodingByte(), llvm::MutableArrayRef< T >::end(), llvm::DwarfDebug::endFunction(), llvm::LiveIntervals::extendToIndices(), llvm::DWARFDebugInfoEntryMinimal::extractFast(), llvm::FenceInst::FenceInst(), llvm::FindInsertedValue(), FitWeights(), llvm::FunctionType::get(), llvm::AttributeSet::get(), llvm::ConstantArray::get(), llvm::ConstantStruct::get(), llvm::ConstantVector::get(), llvm::ConstantDataArray::get(), llvm::ConstantDataVector::get(), getDigit(), llvm::ConstantExpr::getGetElementPtr(), llvm::DataLayout::getIndexedOffset(), llvm::ExtractValueInst::getIndexedType(), getIndexedTypeInternal(), llvm::Intrinsic::getIntrinsicInfoTableEntries(), llvm::SelectionDAG::getMachineNode(), llvm::IntegerType::getMask(), llvm::SourceMgr::GetMessage(), llvm::Intrinsic::getName(), llvm::SelectionDAG::getNode(), getNoopInput(), llvm::ConstantExpr::getOpcodeName(), llvm::TargetTransformInfo::getReductionCost(), llvm::ARMBaseRegisterInfo::getRegAllocationHints(), llvm::MachineTraceMetrics::Trace::getResourceDepth(), llvm::MachineTraceMetrics::Trace::getResourceLength(), llvm::object::COFFObjectFile::getSectionSize(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::MDNode::getTemporary(), llvm::ConstantStruct::getTypeForElements(), llvm::RegPressureTracker::getUpwardPressureDelta(), getVLDSTRegisterUpdateOpcode(), llvm::ConstantExpr::getWithOperands(), llvm::hasUTF16ByteOrderMark(), llvm::RegPressureTracker::increaseRegPressure(), llvm::InterferenceCache::init(), isContiguous(), llvm::X86TargetLowering::IsDesirableToPromoteOp(), isFunctionLocalValue(), isi32Store(), isInBoundsIndices(), isLocalCopy(), isReverseMask(), isVTBLMask(), MarkBlocksLiveIn(), llvm::AllocationOrder::next(), llvm::MutableArrayRef< T >::operator[](), PoisonShadowPartialRightRedzone(), llvm::DwarfAccelTable::HashDataContents::print(), llvm::PrintMessage(), ProcessSDDbgValues(), llvm::AttributeSetNode::Profile(), ProfileBitsInit(), ProfileListInit(), pushDepHeight(), ReadWideAPInt(), llvm::LiveIntervals::repairIntervalsInRange(), llvm::MDNode::replaceOperandWith(), llvm::RegisterClassInfo::runOnMachineFunction(), llvm::StructType::setBody(), SimplifyGEPInst(), llvm::ArrayRef< uint8_t >::slice(), llvm::MutableArrayRef< T >::slice(), llvm::SplitBlockPredecessors(), llvm::SplitLandingPadPredecessors(), StackMallocSizeClass(), SymbolicallyEvaluateGEP(), llvm::MD5::update(), UpdatePHINodes(), updatePhysDepsDownwards(), llvm::ScheduleDAGMI::updatePressureDiffs(), llvm::object::yaml::BinaryRef::writeAsBinary(), llvm::object::yaml::BinaryRef::writeAsHex(), llvm::CallInst::~CallInst(), and llvm::LiveDebugVariables::~LiveDebugVariables().
template<typename T> ArrayRef<T> llvm::ArrayRef< T >::slice (unsigned N) const inline
slice(n) - Chop off the first N elements of the array.
Definition at line 134 of file ArrayRef.h.
Referenced by BuildNew(), CastGEPIndices(), llvm::ConstantFoldExtractValueInstruction(), llvm::ConstantFoldInsertValueInstruction(), llvm::ConstantFoldInstOperands(), DecodeFixedType(), llvm::FindInsertedValue(), llvm::ConstantExpr::getAsInstruction(), llvm::ConstantExpr::getWithOperands(), isContiguous(), and SimplifyGEPInst().
template<typename T> ArrayRef<T> llvm::ArrayRef< T >::slice (unsigned N, unsigned M) const inline
slice(n, m) - Chop off the first N elements of the array, and keep M elements in the array.
Definition at line 141 of file ArrayRef.h.
template<typename T> std::vector<T> llvm::ArrayRef< T >::vec () const inline
Definition at line 157 of file ArrayRef.h.
The documentation for this class was generated from the following file:
ArrayRef.h