LLVM: llvm::MCObjectFileInfo Class Reference
LLVM API Documentation
llvm::MCObjectFileInfo Class Reference
#include <MCObjectFileInfo.h>
Public Member Functions
void InitMCObjectFileInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, MCContext &ctx)
bool isFunctionEHFrameSymbolPrivate () const
bool getSupportsWeakOmittedEHFrame () const
bool getCommDirectiveSupportsAlignment () const
unsigned getPersonalityEncoding () const
unsigned getLSDAEncoding () const
unsigned getFDEEncoding (bool CFI) const
unsigned getTTypeEncoding () const
unsigned getCompactUnwindDwarfEHFrameOnly () const
const MCSection * getTextSection () const
const MCSection * getDataSection () const
const MCSection * getBSSSection () const
const MCSection * getLSDASection () const
const MCSection * getCompactUnwindSection () const
const MCSection * getDwarfAbbrevSection () const
const MCSection * getDwarfInfoSection () const
const MCSection * getDwarfLineSection () const
const MCSection * getDwarfFrameSection () const
const MCSection * getDwarfPubNamesSection () const
const MCSection * getDwarfPubTypesSection () const
const MCSection * getDwarfGnuPubNamesSection () const
const MCSection * getDwarfGnuPubTypesSection () const
const MCSection * getDwarfDebugInlineSection () const
const MCSection * getDwarfStrSection () const
const MCSection * getDwarfLocSection () const
const MCSection * getDwarfARangesSection () const
const MCSection * getDwarfRangesSection () const
const MCSection * getDwarfMacroInfoSection () const
const MCSection * getDwarfAccelNamesSection () const
const MCSection * getDwarfAccelObjCSection () const
const MCSection * getDwarfAccelNamespaceSection () const
const MCSection * getDwarfAccelTypesSection () const
const MCSection * getDwarfInfoDWOSection () const
const MCSection * getDwarfAbbrevDWOSection () const
const MCSection * getDwarfStrDWOSection () const
const MCSection * getDwarfLineDWOSection () const
const MCSection * getDwarfLocDWOSection () const
const MCSection * getDwarfStrOffDWOSection () const
const MCSection * getDwarfAddrSection () const
const MCSection * getTLSExtraDataSection () const
const MCSection * getTLSDataSection () const
const MCSection * getTLSBSSSection () const
const MCSection * getStackMapSection () const
const MCSection * getDataRelSection () const
const MCSection * getDataRelLocalSection () const
const MCSection * getDataRelROSection () const
const MCSection * getDataRelROLocalSection () const
const MCSection * getMergeableConst4Section () const
const MCSection * getMergeableConst8Section () const
const MCSection * getMergeableConst16Section () const
const MCSection * getTLSTLVSection () const
const MCSection * getTLSThreadInitSection () const
const MCSection * getCStringSection () const
const MCSection * getUStringSection () const
const MCSection * getTextCoalSection () const
const MCSection * getConstTextCoalSection () const
const MCSection * getConstDataSection () const
const MCSection * getDataCoalSection () const
const MCSection * getDataCommonSection () const
const MCSection * getDataBSSSection () const
const MCSection * getFourByteConstantSection () const
const MCSection * getEightByteConstantSection () const
const MCSection * getSixteenByteConstantSection () const
const MCSection * getLazySymbolPointerSection () const
const MCSection * getNonLazySymbolPointerSection () const
const MCSection * getDrectveSection () const
const MCSection * getPDataSection () const
const MCSection * getXDataSection () const
const MCSection * getEHFrameSection ()
Protected Attributes
bool CommDirectiveSupportsAlignment
bool SupportsWeakOmittedEHFrame
bool IsFunctionEHFrameSymbolPrivate
unsigned PersonalityEncoding
unsigned LSDAEncoding
unsigned FDEEncoding
unsigned FDECFIEncoding
unsigned TTypeEncoding
unsigned EHSectionType
Section flags for eh_frame.
unsigned EHSectionFlags
unsigned CompactUnwindDwarfEHFrameOnly
const MCSection * TextSection
const MCSection * DataSection
const MCSection * BSSSection
BSSSection - Section that is default initialized to zero.
const MCSection * ReadOnlySection
const MCSection * StaticCtorSection
const MCSection * StaticDtorSection
const MCSection * LSDASection
const MCSection * CompactUnwindSection
const MCSection * DwarfAbbrevSection
const MCSection * DwarfInfoSection
const MCSection * DwarfLineSection
const MCSection * DwarfFrameSection
const MCSection * DwarfPubTypesSection
const MCSection * DwarfDebugInlineSection
const MCSection * DwarfStrSection
const MCSection * DwarfLocSection
const MCSection * DwarfARangesSection
const MCSection * DwarfRangesSection
const MCSection * DwarfMacroInfoSection
const MCSection * DwarfPubNamesSection
const MCSection * DwarfAccelNamesSection
const MCSection * DwarfAccelObjCSection
const MCSection * DwarfAccelNamespaceSection
const MCSection * DwarfAccelTypesSection
const MCSection * DwarfInfoDWOSection
These are used for the Fission separate debug information files.
const MCSection * DwarfAbbrevDWOSection
const MCSection * DwarfStrDWOSection
const MCSection * DwarfLineDWOSection
const MCSection * DwarfLocDWOSection
const MCSection * DwarfStrOffDWOSection
const MCSection * DwarfAddrSection
const MCSection * DwarfGnuPubNamesSection
Sections for newer gnu pubnames and pubtypes.
const MCSection * DwarfGnuPubTypesSection
const MCSection * TLSExtraDataSection
const MCSection * TLSDataSection
const MCSection * TLSBSSSection
const MCSection * StackMapSection
StackMap section.
const MCSection * EHFrameSection
const MCSection * DataRelSection
const MCSection * DataRelLocalSection
const MCSection * DataRelROSection
const MCSection * DataRelROLocalSection
const MCSection * MergeableConst4Section
const MCSection * MergeableConst8Section
const MCSection * MergeableConst16Section
const MCSection * TLSTLVSection
const MCSection * TLSThreadInitSection
const MCSection * CStringSection
const MCSection * UStringSection
const MCSection * TextCoalSection
const MCSection * ConstTextCoalSection
const MCSection * ConstDataSection
const MCSection * DataCoalSection
const MCSection * DataCommonSection
const MCSection * DataBSSSection
const MCSection * FourByteConstantSection
const MCSection * EightByteConstantSection
const MCSection * SixteenByteConstantSection
const MCSection * LazySymbolPointerSection
const MCSection * NonLazySymbolPointerSection
const MCSection * DrectveSection
const MCSection * PDataSection
const MCSection * XDataSection
Detailed Description
Definition at line 25 of file MCObjectFileInfo.h.
Member Function Documentation
const MCSection* llvm::MCObjectFileInfo::getBSSSection () const inline
Definition at line 221 of file MCObjectFileInfo.h.
References BSSSection.
bool llvm::MCObjectFileInfo::getCommDirectiveSupportsAlignment () const inline
Definition at line 204 of file MCObjectFileInfo.h.
References CommDirectiveSupportsAlignment.
Referenced by llvm::AsmPrinter::EmitGlobalVariable().
unsigned llvm::MCObjectFileInfo::getCompactUnwindDwarfEHFrameOnly () const inline
Definition at line 215 of file MCObjectFileInfo.h.
References CompactUnwindDwarfEHFrameOnly.
Referenced by EmitEncodingByte().
const MCSection* llvm::MCObjectFileInfo::getCompactUnwindSection () const inline
Definition at line 223 of file MCObjectFileInfo.h.
References CompactUnwindSection.
Referenced by llvm::MCDwarfFrameEmitter::Emit().
const MCSection* llvm::MCObjectFileInfo::getConstDataSection () const inline
Definition at line 324 of file MCObjectFileInfo.h.
References ConstDataSection.
const MCSection* llvm::MCObjectFileInfo::getConstTextCoalSection () const inline
Definition at line 321 of file MCObjectFileInfo.h.
References ConstTextCoalSection.
Referenced by llvm::ARMAsmPrinter::EmitStartOfAsmFile().
const MCSection* llvm::MCObjectFileInfo::getCStringSection () const inline
Definition at line 318 of file MCObjectFileInfo.h.
References CStringSection.
const MCSection* llvm::MCObjectFileInfo::getDataBSSSection () const inline
Definition at line 327 of file MCObjectFileInfo.h.
References DataBSSSection.
const MCSection* llvm::MCObjectFileInfo::getDataCoalSection () const inline
Definition at line 325 of file MCObjectFileInfo.h.
References DataCoalSection.
const MCSection* llvm::MCObjectFileInfo::getDataCommonSection () const inline
Definition at line 326 of file MCObjectFileInfo.h.
References DataCommonSection.
const MCSection* llvm::MCObjectFileInfo::getDataRelLocalSection () const inline
Definition at line 295 of file MCObjectFileInfo.h.
References DataRelLocalSection.
const MCSection* llvm::MCObjectFileInfo::getDataRelROLocalSection () const inline
Definition at line 299 of file MCObjectFileInfo.h.
References DataRelROLocalSection.
const MCSection* llvm::MCObjectFileInfo::getDataRelROSection () const inline
Definition at line 298 of file MCObjectFileInfo.h.
References DataRelROSection.
const MCSection* llvm::MCObjectFileInfo::getDataRelSection () const inline
ELF specific sections.
Definition at line 294 of file MCObjectFileInfo.h.
References DataRelSection.
Referenced by llvm::SystemZAsmPrinter::EmitEndOfAsmFile(), llvm::AArch64AsmPrinter::EmitEndOfAsmFile(), and llvm::X86AsmPrinter::EmitEndOfAsmFile().
const MCSection* llvm::MCObjectFileInfo::getDataSection () const inline
Definition at line 220 of file MCObjectFileInfo.h.
References DataSection.
Referenced by llvm::DwarfUnits::computeSizeAndOffsets(), EmitCamlGlobal(), and llvm::TargetLoweringObjectFile::SelectSectionForGlobal().
const MCSection* llvm::MCObjectFileInfo::getDrectveSection () const inline
COFF specific sections.
Definition at line 346 of file MCObjectFileInfo.h.
References DrectveSection.
Referenced by llvm::X86AsmPrinter::EmitEndOfAsmFile().
const MCSection* llvm::MCObjectFileInfo::getDwarfAbbrevDWOSection () const inline
Definition at line 265 of file MCObjectFileInfo.h.
References DwarfAbbrevDWOSection.
Referenced by llvm::DwarfUnits::computeSizeAndOffsets().
const MCSection* llvm::MCObjectFileInfo::getDwarfAbbrevSection () const inline
Definition at line 226 of file MCObjectFileInfo.h.
References DwarfAbbrevSection.
Referenced by llvm::DwarfUnits::computeSizeAndOffsets(), llvm::MCGenDwarfInfo::Emit(), EmitGenDwarfAbbrev(), and llvm::DwarfUnits::emitUnits().
const MCSection* llvm::MCObjectFileInfo::getDwarfAccelNamespaceSection () const inline
Definition at line 256 of file MCObjectFileInfo.h.
References DwarfAccelNamespaceSection.
Referenced by llvm::DwarfUnits::emitUnits().
const MCSection* llvm::MCObjectFileInfo::getDwarfAccelNamesSection () const inline
Definition at line 250 of file MCObjectFileInfo.h.
References DwarfAccelNamesSection.
Referenced by llvm::DwarfUnits::emitUnits().
const MCSection* llvm::MCObjectFileInfo::getDwarfAccelObjCSection () const inline
Definition at line 253 of file MCObjectFileInfo.h.
References DwarfAccelObjCSection.
Referenced by llvm::DwarfUnits::emitUnits().
const MCSection* llvm::MCObjectFileInfo::getDwarfAccelTypesSection () const inline
Definition at line 259 of file MCObjectFileInfo.h.
References DwarfAccelTypesSection.
Referenced by llvm::DwarfUnits::emitUnits().
const MCSection* llvm::MCObjectFileInfo::getDwarfAddrSection () const inline
Definition at line 280 of file MCObjectFileInfo.h.
References DwarfAddrSection.
Referenced by llvm::DwarfUnits::computeSizeAndOffsets(), and llvm::DwarfDebug::endModule().
const MCSection* llvm::MCObjectFileInfo::getDwarfARangesSection () const inline
Definition at line 243 of file MCObjectFileInfo.h.
References DwarfARangesSection.
Referenced by llvm::DwarfUnits::computeSizeAndOffsets(), llvm::MCGenDwarfInfo::Emit(), and EmitGenDwarfAranges().
const MCSection* llvm::MCObjectFileInfo::getDwarfDebugInlineSection () const inline
Definition at line 238 of file MCObjectFileInfo.h.
References DwarfDebugInlineSection.
const MCSection* llvm::MCObjectFileInfo::getDwarfFrameSection () const inline
Definition at line 229 of file MCObjectFileInfo.h.
References DwarfFrameSection.
Referenced by llvm::MCDwarfFrameEmitter::Emit().
const MCSection* llvm::MCObjectFileInfo::getDwarfGnuPubNamesSection () const inline
Definition at line 232 of file MCObjectFileInfo.h.
References DwarfGnuPubNamesSection.
Referenced by computeIndexValue(), and llvm::DwarfUnits::computeSizeAndOffsets().
const MCSection* llvm::MCObjectFileInfo::getDwarfGnuPubTypesSection () const inline
Definition at line 235 of file MCObjectFileInfo.h.
References DwarfGnuPubTypesSection.
Referenced by computeIndexValue(), and llvm::DwarfUnits::computeSizeAndOffsets().
const MCSection* llvm::MCObjectFileInfo::getDwarfInfoDWOSection () const inline
Definition at line 262 of file MCObjectFileInfo.h.
References DwarfInfoDWOSection.
const MCSection* llvm::MCObjectFileInfo::getDwarfInfoSection () const inline
Definition at line 227 of file MCObjectFileInfo.h.
References DwarfInfoSection.
Referenced by computeIndexValue(), llvm::DwarfUnits::computeSizeAndOffsets(), llvm::MCGenDwarfInfo::Emit(), EmitGenDwarfInfo(), and llvm::DwarfUnits::emitUnits().
const MCSection* llvm::MCObjectFileInfo::getDwarfLineDWOSection () const inline
Definition at line 271 of file MCObjectFileInfo.h.
References DwarfLineDWOSection.
const MCSection* llvm::MCObjectFileInfo::getDwarfLineSection () const inline
Definition at line 228 of file MCObjectFileInfo.h.
References DwarfLineSection.
Referenced by llvm::DwarfUnits::computeSizeAndOffsets(), llvm::MCDwarfFileTable::Emit(), and EmitDwarfLineTable().
const MCSection* llvm::MCObjectFileInfo::getDwarfLocDWOSection () const inline
Definition at line 274 of file MCObjectFileInfo.h.
References DwarfLocDWOSection.
const MCSection* llvm::MCObjectFileInfo::getDwarfLocSection () const inline
Definition at line 242 of file MCObjectFileInfo.h.
References DwarfLocSection.
Referenced by llvm::DwarfUnits::computeSizeAndOffsets(), and llvm::DwarfUnits::emitAddresses().
const MCSection* llvm::MCObjectFileInfo::getDwarfMacroInfoSection () const inline
Definition at line 245 of file MCObjectFileInfo.h.
References DwarfMacroInfoSection.
Referenced by llvm::DwarfUnits::computeSizeAndOffsets().
const MCSection* llvm::MCObjectFileInfo::getDwarfPubNamesSection () const inline
Definition at line 230 of file MCObjectFileInfo.h.
References DwarfPubNamesSection.
Referenced by computeIndexValue(), and llvm::DwarfUnits::computeSizeAndOffsets().
const MCSection* llvm::MCObjectFileInfo::getDwarfPubTypesSection () const inline
Definition at line 231 of file MCObjectFileInfo.h.
References DwarfPubTypesSection.
Referenced by computeIndexValue(), and llvm::DwarfUnits::computeSizeAndOffsets().
const MCSection* llvm::MCObjectFileInfo::getDwarfRangesSection () const inline
Definition at line 244 of file MCObjectFileInfo.h.
References DwarfRangesSection.
Referenced by llvm::DwarfUnits::computeSizeAndOffsets().
const MCSection* llvm::MCObjectFileInfo::getDwarfStrDWOSection () const inline
Definition at line 268 of file MCObjectFileInfo.h.
References DwarfStrDWOSection.
Referenced by llvm::DwarfUnits::computeSizeAndOffsets().
const MCSection* llvm::MCObjectFileInfo::getDwarfStrOffDWOSection () const inline
Definition at line 277 of file MCObjectFileInfo.h.
References DwarfStrOffDWOSection.
const MCSection* llvm::MCObjectFileInfo::getDwarfStrSection () const inline
Definition at line 241 of file MCObjectFileInfo.h.
References DwarfStrSection.
Referenced by llvm::DwarfUnits::computeSizeAndOffsets(), and llvm::DwarfUnits::emitAddresses().
const MCSection* llvm::MCObjectFileInfo::getEHFrameSection () inline
Definition at line 350 of file MCObjectFileInfo.h.
References EHFrameSection.
const MCSection* llvm::MCObjectFileInfo::getEightByteConstantSection () const inline
Definition at line 331 of file MCObjectFileInfo.h.
References EightByteConstantSection.
unsigned llvm::MCObjectFileInfo::getFDEEncoding (bool CFI) const inline
Definition at line 210 of file MCObjectFileInfo.h.
References FDEEncoding.
Referenced by EmitEncodingByte().
const MCSection* llvm::MCObjectFileInfo::getFourByteConstantSection () const inline
Definition at line 328 of file MCObjectFileInfo.h.
References FourByteConstantSection.
const MCSection* llvm::MCObjectFileInfo::getLazySymbolPointerSection () const inline
Definition at line 337 of file MCObjectFileInfo.h.
References LazySymbolPointerSection.
Referenced by GetAnonSym().
unsigned llvm::MCObjectFileInfo::getLSDAEncoding () const inline
Definition at line 209 of file MCObjectFileInfo.h.
References LSDAEncoding.
Referenced by llvm::DwarfCFIException::BeginFunction(), and llvm::Win64Exception::BeginFunction().
const MCSection* llvm::MCObjectFileInfo::getLSDASection () const inline
Definition at line 222 of file MCObjectFileInfo.h.
References LSDASection.
Referenced by llvm::DwarfException::EmitExceptionTable().
const MCSection* llvm::MCObjectFileInfo::getMergeableConst16Section () const inline
Definition at line 308 of file MCObjectFileInfo.h.
References MergeableConst16Section.
const MCSection* llvm::MCObjectFileInfo::getMergeableConst4Section () const inline
Definition at line 302 of file MCObjectFileInfo.h.
References MergeableConst4Section.
const MCSection* llvm::MCObjectFileInfo::getMergeableConst8Section () const inline
Definition at line 305 of file MCObjectFileInfo.h.
References MergeableConst8Section.
const MCSection* llvm::MCObjectFileInfo::getNonLazySymbolPointerSection () const inline
Definition at line 340 of file MCObjectFileInfo.h.
References NonLazySymbolPointerSection.
Referenced by llvm::ARMAsmPrinter::EmitEndOfAsmFile(), and GetAnonSym().
const MCSection* llvm::MCObjectFileInfo::getPDataSection () const inline
Definition at line 347 of file MCObjectFileInfo.h.
References PDataSection.
Referenced by llvm::getWin64EHFuncTableSection().
unsigned llvm::MCObjectFileInfo::getPersonalityEncoding () const inline
Definition at line 208 of file MCObjectFileInfo.h.
References PersonalityEncoding.
Referenced by llvm::DwarfCFIException::BeginFunction(), llvm::Win64Exception::BeginFunction(), and llvm::DwarfCFIException::EndModule().
const MCSection* llvm::MCObjectFileInfo::getSixteenByteConstantSection () const inline
Definition at line 334 of file MCObjectFileInfo.h.
References SixteenByteConstantSection.
const MCSection* llvm::MCObjectFileInfo::getStackMapSection () const inline
Definition at line 290 of file MCObjectFileInfo.h.
References StackMapSection.
Referenced by llvm::StackMaps::serializeToStackMapSection().
bool llvm::MCObjectFileInfo::getSupportsWeakOmittedEHFrame () const inline
Definition at line 201 of file MCObjectFileInfo.h.
References SupportsWeakOmittedEHFrame.
const MCSection* llvm::MCObjectFileInfo::getTextCoalSection () const inline
Definition at line 320 of file MCObjectFileInfo.h.
References TextCoalSection.
Referenced by llvm::ARMAsmPrinter::EmitStartOfAsmFile(), and stripRegisterPrefix().
const MCSection* llvm::MCObjectFileInfo::getTextSection () const inline
Definition at line 219 of file MCObjectFileInfo.h.
References TextSection.
Referenced by llvm::DwarfDebug::beginModule(), llvm::DwarfUnits::computeSizeAndOffsets(), EmitCamlGlobal(), llvm::ARMAsmPrinter::EmitStartOfAsmFile(), and llvm::TargetLoweringObjectFile::SelectSectionForGlobal().
const MCSection* llvm::MCObjectFileInfo::getTLSBSSSection () const inline
Definition at line 288 of file MCObjectFileInfo.h.
References TLSBSSSection.
Referenced by llvm::AsmPrinter::EmitGlobalVariable().
const MCSection* llvm::MCObjectFileInfo::getTLSDataSection () const inline
Definition at line 287 of file MCObjectFileInfo.h.
References TLSDataSection.
const MCSection* llvm::MCObjectFileInfo::getTLSExtraDataSection () const inline
Definition at line 284 of file MCObjectFileInfo.h.
References TLSExtraDataSection.
Referenced by llvm::AsmPrinter::EmitGlobalVariable().
const MCSection* llvm::MCObjectFileInfo::getTLSThreadInitSection () const inline
Definition at line 315 of file MCObjectFileInfo.h.
References TLSThreadInitSection.
const MCSection* llvm::MCObjectFileInfo::getTLSTLVSection () const inline
MachO specific sections.
Definition at line 314 of file MCObjectFileInfo.h.
References TLSTLVSection.
unsigned llvm::MCObjectFileInfo::getTTypeEncoding () const inline
Definition at line 213 of file MCObjectFileInfo.h.
References TTypeEncoding.
Referenced by llvm::DwarfException::EmitExceptionTable().
const MCSection* llvm::MCObjectFileInfo::getUStringSection () const inline
Definition at line 319 of file MCObjectFileInfo.h.
References UStringSection.
const MCSection* llvm::MCObjectFileInfo::getXDataSection () const inline
Definition at line 348 of file MCObjectFileInfo.h.
References XDataSection.
Referenced by llvm::getWin64EHTableSection(), and getWin64EHTableSection().
void MCObjectFileInfo::InitMCObjectFileInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, MCContext & ctx)
Definition at line 674 of file MCObjectFileInfo.cpp.
References llvm::Triple::arm, CommDirectiveSupportsAlignment, CompactUnwindDwarfEHFrameOnly, CompactUnwindSection, llvm::Triple::Cygwin, llvm::dwarf::DW_EH_PE_absptr, DwarfAccelNamespaceSection, DwarfAccelNamesSection, DwarfAccelObjCSection, DwarfAccelTypesSection, EHFrameSection, EHSectionFlags, EHSectionType, llvm::Triple::ELF, FDECFIEncoding, FDEEncoding, llvm::Triple::getArch(), llvm::MCContext::getCOFFSection(), llvm::SectionKind::getDataRel(), llvm::MCContext::getELFSection(), llvm::Triple::getEnvironment(), llvm::MCContext::getMachOSection(), llvm::Triple::getOS(), llvm::SectionKind::getReadOnly(), IsFunctionEHFrameSymbolPrivate, llvm::Triple::isOSDarwin(), LSDAEncoding, llvm::Triple::MachO, llvm::Triple::MinGW32, PersonalityEncoding, llvm::Triple::ppc, llvm::Triple::ppc64, llvm::MachO::S_COALESCED, SupportsWeakOmittedEHFrame, T, llvm::Triple::thumb, TTypeEncoding, llvm::Triple::UnknownArch, llvm::Triple::Win32, llvm::Triple::x86, and llvm::Triple::x86_64.
Referenced by llvm::TargetLoweringObjectFile::Initialize().
bool llvm::MCObjectFileInfo::isFunctionEHFrameSymbolPrivate () const inline
Definition at line 198 of file MCObjectFileInfo.h.
References IsFunctionEHFrameSymbolPrivate.
Referenced by EmitEncodingByte(), and llvm::DwarfCFIException::EndModule().
Member Data Documentation
const MCSection* llvm::MCObjectFileInfo::BSSSection protected
BSSSection - Section that is default initialized to zero.
Definition at line 67 of file MCObjectFileInfo.h.
Referenced by getBSSSection(), llvm::XCoreTargetObjectFile::Initialize(), llvm::NVPTXTargetObjectFile::Initialize(), llvm::NVPTXTargetObjectFile::NVPTXTargetObjectFile(), and llvm::TargetLoweringObjectFile::SelectSectionForGlobal().
bool llvm::MCObjectFileInfo::CommDirectiveSupportsAlignment protected
CommDirectiveSupportsAlignment - True if .comm supports alignment. This is a hack for as long as we support 10.4 Tiger, whose assembler doesn't support alignment on comm.
Definition at line 30 of file MCObjectFileInfo.h.
Referenced by getCommDirectiveSupportsAlignment(), and InitMCObjectFileInfo().
unsigned llvm::MCObjectFileInfo::CompactUnwindDwarfEHFrameOnly protected
CompactUnwindDwarfEHFrameOnly - Compact unwind encoding indicating that we should emit only an EH frame.
Definition at line 56 of file MCObjectFileInfo.h.
Referenced by getCompactUnwindDwarfEHFrameOnly(), and InitMCObjectFileInfo().
const MCSection* llvm::MCObjectFileInfo::CompactUnwindSection protected
CompactUnwindSection - If exception handling is supported by the target and the target can support a compact representation of the CIE and FDE, this is the section to emit them into.
Definition at line 90 of file MCObjectFileInfo.h.
Referenced by getCompactUnwindSection(), and InitMCObjectFileInfo().
const MCSection* llvm::MCObjectFileInfo::ConstDataSection protected
Definition at line 178 of file MCObjectFileInfo.h.
Referenced by getConstDataSection().
const MCSection* llvm::MCObjectFileInfo::ConstTextCoalSection protected
Definition at line 177 of file MCObjectFileInfo.h.
Referenced by getConstTextCoalSection().
const MCSection* llvm::MCObjectFileInfo::CStringSection protected
Definition at line 174 of file MCObjectFileInfo.h.
Referenced by getCStringSection().
const MCSection* llvm::MCObjectFileInfo::DataBSSSection protected
Definition at line 181 of file MCObjectFileInfo.h.
Referenced by getDataBSSSection().
const MCSection* llvm::MCObjectFileInfo::DataCoalSection protected
Definition at line 179 of file MCObjectFileInfo.h.
Referenced by getDataCoalSection().
const MCSection* llvm::MCObjectFileInfo::DataCommonSection protected
Definition at line 180 of file MCObjectFileInfo.h.
Referenced by getDataCommonSection().
const MCSection* llvm::MCObjectFileInfo::DataRelLocalSection protected
Definition at line 155 of file MCObjectFileInfo.h.
Referenced by getDataRelLocalSection().
const MCSection* llvm::MCObjectFileInfo::DataRelROLocalSection protected
Definition at line 157 of file MCObjectFileInfo.h.
Referenced by getDataRelROLocalSection().
const MCSection* llvm::MCObjectFileInfo::DataRelROSection protected
Definition at line 156 of file MCObjectFileInfo.h.
Referenced by getDataRelROSection().
const MCSection* llvm::MCObjectFileInfo::DataRelSection protected
ELF specific sections.
Definition at line 154 of file MCObjectFileInfo.h.
Referenced by getDataRelSection().
const MCSection* llvm::MCObjectFileInfo::DataSection protected
DataSection - Section directive for standard data.
Definition at line 64 of file MCObjectFileInfo.h.
Referenced by getDataSection(), llvm::NVPTXTargetObjectFile::getExplicitSectionGlobal(), llvm::TargetLoweringObjectFile::getSectionForConstant(), llvm::XCoreTargetObjectFile::Initialize(), llvm::NVPTXTargetObjectFile::Initialize(), and llvm::NVPTXTargetObjectFile::NVPTXTargetObjectFile().
const MCSection* llvm::MCObjectFileInfo::DrectveSection protected
COFF specific sections.
Definition at line 190 of file MCObjectFileInfo.h.
Referenced by getDrectveSection().
const MCSection* llvm::MCObjectFileInfo::DwarfAbbrevDWOSection protected
Definition at line 121 of file MCObjectFileInfo.h.
Referenced by getDwarfAbbrevDWOSection().
const MCSection* llvm::MCObjectFileInfo::DwarfAbbrevSection protected
Definition at line 94 of file MCObjectFileInfo.h.
Referenced by getDwarfAbbrevSection(), llvm::NVPTXTargetObjectFile::Initialize(), and llvm::NVPTXTargetObjectFile::NVPTXTargetObjectFile().
const MCSection* llvm::MCObjectFileInfo::DwarfAccelNamespaceSection protected
Definition at line 116 of file MCObjectFileInfo.h.
Referenced by getDwarfAccelNamespaceSection(), and InitMCObjectFileInfo().
const MCSection* llvm::MCObjectFileInfo::DwarfAccelNamesSection protected
DwarfAccelNamesSection, DwarfAccelObjCSection, DwarfAccelNamespaceSection, DwarfAccelTypesSection - If we use the DWARF accelerated hash tables then we want to emit these sections.
Definition at line 114 of file MCObjectFileInfo.h.
Referenced by getDwarfAccelNamesSection(), and InitMCObjectFileInfo().
const MCSection* llvm::MCObjectFileInfo::DwarfAccelObjCSection protected
Definition at line 115 of file MCObjectFileInfo.h.
Referenced by getDwarfAccelObjCSection(), and InitMCObjectFileInfo().
const MCSection* llvm::MCObjectFileInfo::DwarfAccelTypesSection protected
Definition at line 117 of file MCObjectFileInfo.h.
Referenced by getDwarfAccelTypesSection(), and InitMCObjectFileInfo().
const MCSection* llvm::MCObjectFileInfo::DwarfAddrSection protected
Definition at line 126 of file MCObjectFileInfo.h.
Referenced by getDwarfAddrSection().
const MCSection* llvm::MCObjectFileInfo::DwarfARangesSection protected
Definition at line 102 of file MCObjectFileInfo.h.
Referenced by getDwarfARangesSection(), llvm::NVPTXTargetObjectFile::Initialize(), and llvm::NVPTXTargetObjectFile::NVPTXTargetObjectFile().
const MCSection* llvm::MCObjectFileInfo::DwarfDebugInlineSection protected
Definition at line 99 of file MCObjectFileInfo.h.
Referenced by getDwarfDebugInlineSection(), llvm::NVPTXTargetObjectFile::Initialize(), and llvm::NVPTXTargetObjectFile::NVPTXTargetObjectFile().
const MCSection* llvm::MCObjectFileInfo::DwarfFrameSection protected
Definition at line 97 of file MCObjectFileInfo.h.
Referenced by getDwarfFrameSection(), llvm::NVPTXTargetObjectFile::Initialize(), and llvm::NVPTXTargetObjectFile::NVPTXTargetObjectFile().
const MCSection* llvm::MCObjectFileInfo::DwarfGnuPubNamesSection protected
Sections for newer gnu pubnames and pubtypes.
Definition at line 129 of file MCObjectFileInfo.h.
Referenced by getDwarfGnuPubNamesSection().
const MCSection* llvm::MCObjectFileInfo::DwarfGnuPubTypesSection protected
Definition at line 130 of file MCObjectFileInfo.h.
Referenced by getDwarfGnuPubTypesSection().
const MCSection* llvm::MCObjectFileInfo::DwarfInfoDWOSection protected
These are used for the Fission separate debug information files.
Definition at line 120 of file MCObjectFileInfo.h.
Referenced by getDwarfInfoDWOSection().
const MCSection* llvm::MCObjectFileInfo::DwarfInfoSection protected
Definition at line 95 of file MCObjectFileInfo.h.
Referenced by getDwarfInfoSection(), llvm::NVPTXTargetObjectFile::Initialize(), and llvm::NVPTXTargetObjectFile::NVPTXTargetObjectFile().
const MCSection* llvm::MCObjectFileInfo::DwarfLineDWOSection protected
Definition at line 123 of file MCObjectFileInfo.h.
Referenced by getDwarfLineDWOSection().
const MCSection* llvm::MCObjectFileInfo::DwarfLineSection protected
Definition at line 96 of file MCObjectFileInfo.h.
Referenced by getDwarfLineSection(), llvm::NVPTXTargetObjectFile::Initialize(), and llvm::NVPTXTargetObjectFile::NVPTXTargetObjectFile().
const MCSection* llvm::MCObjectFileInfo::DwarfLocDWOSection protected
Definition at line 124 of file MCObjectFileInfo.h.
Referenced by getDwarfLocDWOSection().
const MCSection* llvm::MCObjectFileInfo::DwarfLocSection protected
Definition at line 101 of file MCObjectFileInfo.h.
Referenced by getDwarfLocSection(), llvm::NVPTXTargetObjectFile::Initialize(), and llvm::NVPTXTargetObjectFile::NVPTXTargetObjectFile().
const MCSection* llvm::MCObjectFileInfo::DwarfMacroInfoSection protected
Definition at line 104 of file MCObjectFileInfo.h.
Referenced by getDwarfMacroInfoSection(), llvm::NVPTXTargetObjectFile::Initialize(), and llvm::NVPTXTargetObjectFile::NVPTXTargetObjectFile().
const MCSection* llvm::MCObjectFileInfo::DwarfPubNamesSection protected
Definition at line 107 of file MCObjectFileInfo.h.
Referenced by getDwarfPubNamesSection().
const MCSection* llvm::MCObjectFileInfo::DwarfPubTypesSection protected
Definition at line 98 of file MCObjectFileInfo.h.
Referenced by getDwarfPubTypesSection(), llvm::NVPTXTargetObjectFile::Initialize(), and llvm::NVPTXTargetObjectFile::NVPTXTargetObjectFile().
const MCSection* llvm::MCObjectFileInfo::DwarfRangesSection protected
Definition at line 103 of file MCObjectFileInfo.h.
Referenced by getDwarfRangesSection(), llvm::NVPTXTargetObjectFile::Initialize(), and llvm::NVPTXTargetObjectFile::NVPTXTargetObjectFile().
const MCSection* llvm::MCObjectFileInfo::DwarfStrDWOSection protected
Definition at line 122 of file MCObjectFileInfo.h.
Referenced by getDwarfStrDWOSection().
const MCSection* llvm::MCObjectFileInfo::DwarfStrOffDWOSection protected
Definition at line 125 of file MCObjectFileInfo.h.
Referenced by getDwarfStrOffDWOSection().
const MCSection* llvm::MCObjectFileInfo::DwarfStrSection protected
Definition at line 100 of file MCObjectFileInfo.h.
Referenced by getDwarfStrSection(), llvm::NVPTXTargetObjectFile::Initialize(), and llvm::NVPTXTargetObjectFile::NVPTXTargetObjectFile().
const MCSection* llvm::MCObjectFileInfo::EHFrameSection protected
EHFrameSection - EH frame section. It is initialized on demand so it can be overwritten (with uniquing).
Definition at line 150 of file MCObjectFileInfo.h.
Referenced by getEHFrameSection(), llvm::NVPTXTargetObjectFile::Initialize(), InitMCObjectFileInfo(), and llvm::NVPTXTargetObjectFile::NVPTXTargetObjectFile().
unsigned llvm::MCObjectFileInfo::EHSectionFlags protected
Definition at line 52 of file MCObjectFileInfo.h.
Referenced by InitMCObjectFileInfo().
unsigned llvm::MCObjectFileInfo::EHSectionType protected
Section flags for eh_frame.
Definition at line 51 of file MCObjectFileInfo.h.
Referenced by InitMCObjectFileInfo().
const MCSection* llvm::MCObjectFileInfo::EightByteConstantSection protected
Definition at line 183 of file MCObjectFileInfo.h.
Referenced by getEightByteConstantSection().
unsigned llvm::MCObjectFileInfo::FDECFIEncoding protected
Definition at line 47 of file MCObjectFileInfo.h.
Referenced by InitMCObjectFileInfo().
unsigned llvm::MCObjectFileInfo::FDEEncoding protected
Definition at line 46 of file MCObjectFileInfo.h.
Referenced by getFDEEncoding(), and InitMCObjectFileInfo().
const MCSection* llvm::MCObjectFileInfo::FourByteConstantSection protected
Definition at line 182 of file MCObjectFileInfo.h.
Referenced by getFourByteConstantSection().
bool llvm::MCObjectFileInfo::IsFunctionEHFrameSymbolPrivate protected
IsFunctionEHFrameSymbolPrivate - This flag is set to true if the "EH_frame" symbol for EH information should be an assembler temporary (aka private linkage, aka an L or .L label) or false if it should be a normal non-.globl label. This defaults to true.
Definition at line 40 of file MCObjectFileInfo.h.
Referenced by InitMCObjectFileInfo(), and isFunctionEHFrameSymbolPrivate().
const MCSection* llvm::MCObjectFileInfo::LazySymbolPointerSection protected
Definition at line 185 of file MCObjectFileInfo.h.
Referenced by getLazySymbolPointerSection().
unsigned llvm::MCObjectFileInfo::LSDAEncoding protected
Definition at line 45 of file MCObjectFileInfo.h.
Referenced by getLSDAEncoding(), and InitMCObjectFileInfo().
const MCSection* llvm::MCObjectFileInfo::LSDASection protected
LSDASection - If exception handling is supported by the target, this is the section the Language Specific Data Area information is emitted to.
Definition at line 85 of file MCObjectFileInfo.h.
Referenced by getLSDASection(), llvm::NVPTXTargetObjectFile::Initialize(), and llvm::NVPTXTargetObjectFile::NVPTXTargetObjectFile().
const MCSection* llvm::MCObjectFileInfo::MergeableConst16Section protected
Definition at line 160 of file MCObjectFileInfo.h.
Referenced by getMergeableConst16Section(), and llvm::XCoreTargetObjectFile::Initialize().
const MCSection* llvm::MCObjectFileInfo::MergeableConst4Section protected
Definition at line 158 of file MCObjectFileInfo.h.
Referenced by getMergeableConst4Section(), and llvm::XCoreTargetObjectFile::Initialize().
const MCSection* llvm::MCObjectFileInfo::MergeableConst8Section protected
Definition at line 159 of file MCObjectFileInfo.h.
Referenced by getMergeableConst8Section(), and llvm::XCoreTargetObjectFile::Initialize().
const MCSection* llvm::MCObjectFileInfo::NonLazySymbolPointerSection protected
Definition at line 186 of file MCObjectFileInfo.h.
Referenced by getNonLazySymbolPointerSection().
const MCSection* llvm::MCObjectFileInfo::PDataSection protected
Definition at line 191 of file MCObjectFileInfo.h.
Referenced by getPDataSection().
unsigned llvm::MCObjectFileInfo::PersonalityEncoding protected
PersonalityEncoding, LSDAEncoding, FDEEncoding, TTypeEncoding - Some encoding values for EH.
Definition at line 44 of file MCObjectFileInfo.h.
Referenced by getPersonalityEncoding(), and InitMCObjectFileInfo().
const MCSection* llvm::MCObjectFileInfo::ReadOnlySection protected
ReadOnlySection - Section that is readonly and can contain arbitrary initialized data. Targets are not required to have a readonly section. If they don't, various bits of code will fall back to using the data section for constants.
Definition at line 73 of file MCObjectFileInfo.h.
Referenced by llvm::TargetLoweringObjectFile::getSectionForConstant(), llvm::NVPTXTargetObjectFile::getSectionForConstant(), llvm::XCoreTargetObjectFile::Initialize(), llvm::NVPTXTargetObjectFile::Initialize(), llvm::NVPTXTargetObjectFile::NVPTXTargetObjectFile(), and llvm::TargetLoweringObjectFile::SelectSectionForGlobal().
const MCSection* llvm::MCObjectFileInfo::SixteenByteConstantSection protected
Definition at line 184 of file MCObjectFileInfo.h.
Referenced by getSixteenByteConstantSection().
const MCSection* llvm::MCObjectFileInfo::StackMapSection protected
StackMap section.
Definition at line 146 of file MCObjectFileInfo.h.
Referenced by getStackMapSection().
const MCSection* llvm::MCObjectFileInfo::StaticCtorSection protected
StaticCtorSection - This section contains the static constructor pointer list.
Definition at line 77 of file MCObjectFileInfo.h.
Referenced by llvm::TargetLoweringObjectFile::getStaticCtorSection(), llvm::NVPTXTargetObjectFile::Initialize(), and llvm::NVPTXTargetObjectFile::NVPTXTargetObjectFile().
const MCSection* llvm::MCObjectFileInfo::StaticDtorSection protected
StaticDtorSection - This section contains the static destructor pointer list.
Definition at line 81 of file MCObjectFileInfo.h.
Referenced by llvm::TargetLoweringObjectFile::getStaticDtorSection(), llvm::NVPTXTargetObjectFile::Initialize(), and llvm::NVPTXTargetObjectFile::NVPTXTargetObjectFile().
bool llvm::MCObjectFileInfo::SupportsWeakOmittedEHFrame protected
SupportsWeakEmptyEHFrame - True if target object file supports a weak_definition of constant 0 for an omitted EH frame.
Definition at line 34 of file MCObjectFileInfo.h.
Referenced by getSupportsWeakOmittedEHFrame(), and InitMCObjectFileInfo().
const MCSection* llvm::MCObjectFileInfo::TextCoalSection protected
Definition at line 176 of file MCObjectFileInfo.h.
Referenced by getTextCoalSection().
const MCSection* llvm::MCObjectFileInfo::TextSection protected
TextSection - Section directive for standard text.
Definition at line 60 of file MCObjectFileInfo.h.
Referenced by getTextSection(), llvm::NVPTXTargetObjectFile::Initialize(), and llvm::NVPTXTargetObjectFile::NVPTXTargetObjectFile().
const MCSection* llvm::MCObjectFileInfo::TLSBSSSection protected
TLSBSSSection - Section directive for Thread Local uninitialized data. Null if this target doesn't support a BSS section. ELF and MachO only.
Definition at line 143 of file MCObjectFileInfo.h.
Referenced by getTLSBSSSection(), and llvm::XCoreTargetObjectFile::Initialize().
const MCSection* llvm::MCObjectFileInfo::TLSDataSection protected
TLSDataSection - Section directive for Thread Local data. ELF, MachO and COFF.
Definition at line 138 of file MCObjectFileInfo.h.
Referenced by getTLSDataSection(), and llvm::XCoreTargetObjectFile::Initialize().
const MCSection* llvm::MCObjectFileInfo::TLSExtraDataSection protected
Definition at line 134 of file MCObjectFileInfo.h.
Referenced by getTLSExtraDataSection().
const MCSection* llvm::MCObjectFileInfo::TLSThreadInitSection protected
TLSThreadInitSection - Section for thread local data initialization functions.
Definition at line 172 of file MCObjectFileInfo.h.
Referenced by getTLSThreadInitSection().
const MCSection* llvm::MCObjectFileInfo::TLSTLVSection protected
MachO specific sections.TLSTLVSection - Section for thread local structure information. Contains the source code name of the variable, visibility and a pointer to the initial value (.tdata or .tbss).
Definition at line 168 of file MCObjectFileInfo.h.
Referenced by getTLSTLVSection().
unsigned llvm::MCObjectFileInfo::TTypeEncoding protected
Definition at line 48 of file MCObjectFileInfo.h.
Referenced by getTTypeEncoding(), and InitMCObjectFileInfo().
const MCSection* llvm::MCObjectFileInfo::UStringSection protected
Definition at line 175 of file MCObjectFileInfo.h.
Referenced by getUStringSection().
const MCSection* llvm::MCObjectFileInfo::XDataSection protected
Definition at line 192 of file MCObjectFileInfo.h.
Referenced by getXDataSection().
The documentation for this class was generated from the following files:
MCObjectFileInfo.h
MCObjectFileInfo.cpp