LLVM: llvm::PassManagerPrettyStackEntry Class Reference
LLVM API Documentation
llvm::PassManagerPrettyStackEntry Class Reference
#include <LegacyPassManagers.h>
Public Member Functions
PassManagerPrettyStackEntry (Pass *p)
PassManagerPrettyStackEntry (Pass *p, Value &v)
PassManagerPrettyStackEntry (Pass *p, Module &m)
virtual void print (raw_ostream &OS) const
print - Emit information about this stack frame to OS.
Public Member Functions inherited from llvm::PrettyStackTraceEntry
PrettyStackTraceEntry ()
virtual ~PrettyStackTraceEntry ()
const PrettyStackTraceEntry * getNextEntry () const
getNextEntry - Return the next entry in the list of frames.
Detailed Description
PassManagerPrettyStackEntry - This is used to print informative information about what pass is running when/if a stack trace is generated.
Definition at line 117 of file LegacyPassManagers.h.
Constructor & Destructor Documentation
llvm::PassManagerPrettyStackEntry::PassManagerPrettyStackEntry (Pass * p) inline explicit
Definition at line 122 of file LegacyPassManagers.h.
llvm::PassManagerPrettyStackEntry::PassManagerPrettyStackEntry (Pass * p, Value & v) inline
Definition at line 124 of file LegacyPassManagers.h.
llvm::PassManagerPrettyStackEntry::PassManagerPrettyStackEntry (Pass * p, Module & m) inline
Definition at line 126 of file LegacyPassManagers.h.
References print().
Member Function Documentation
void PassManagerPrettyStackEntry::print (raw_ostream & OS) const virtual
print - Emit information about this stack frame to OS.
Implements llvm::PrettyStackTraceEntry.
Definition at line 121 of file LegacyPassManager.cpp.
References llvm::dbgs(), llvm::Pass::dumpPassStructure(), F(), llvm::raw_ostream::indent(), M, N, P, llvm::PMT_BasicBlockPassManager, llvm::AnalysisUsage::setPreservesAll(), and llvm::WriteAsOperand().
Referenced by PassManagerPrettyStackEntry().
The documentation for this class was generated from the following files:
LegacyPassManagers.h
LegacyPassManager.cpp