LLVM: llvm::GCModuleInfo Class Reference
LLVM API Documentation
llvm::GCModuleInfo Class Reference
#include <GCMetadata.h>
Public Types
typedef list_type::const_iterator iterator
Public Member Functions
GCModuleInfo ()
~GCModuleInfo ()
void clear ()
iterator begin () const
iterator end () const
GCFunctionInfo & getFunctionInfo (const Function &F)
Public Member Functions inherited from llvm::ImmutablePass
virtual void initializePass ()
virtual ImmutablePass * getAsImmutablePass ()
bool runOnModule (Module &)
ImmutablePass (char &pid)
virtual ~ImmutablePass ()
Public Member Functions inherited from llvm::ModulePass
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const
createPrinterPass - Get a module printer pass.
virtual void assignPassManager (PMStack &PMS, PassManagerType T)
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
ModulePass (char &pid)
virtual ~ModulePass ()
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
GCModuleInfo - Garbage collection metadata for a whole module.
Definition at line 164 of file GCMetadata.h.
Member Typedef Documentation
typedef list_type::const_iterator llvm::GCModuleInfo::iterator
Definition at line 176 of file GCMetadata.h.
Constructor & Destructor Documentation
GCModuleInfo::GCModuleInfo ()
Definition at line 59 of file GCMetadata.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeGCModuleInfoPass().
GCModuleInfo::~GCModuleInfo ()
Definition at line 64 of file GCMetadata.cpp.
References llvm::Registry< T, U >::begin(), clear(), llvm::dbgs(), llvm::Registry< T, U >::end(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::StringMap< ValueTy, AllocatorTy >::GetOrCreateValue(), I, llvm_unreachable, M, S, and llvm::StringMapEntry< ValueTy >::setValue().
Member Function Documentation
iterator llvm::GCModuleInfo::begin () const inline
begin/end - Iterators for used strategies.
Definition at line 190 of file GCMetadata.h.
Referenced by clear(), llvm::AsmPrinter::doFinalization(), llvm::AsmPrinter::doInitialization(), and INITIALIZE_PASS_BEGIN().
void GCModuleInfo::clear ()
clear - Resets the pass. Any pass, which uses GCModuleInfo, should call it in doFinalization().
Definition at line 104 of file GCMetadata.cpp.
References begin(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::clear(), llvm::StringMap< ValueTy, AllocatorTy >::clear(), end(), and I.
Referenced by DescKind(), and ~GCModuleInfo().
iterator llvm::GCModuleInfo::end () const inline
Definition at line 191 of file GCMetadata.h.
References F().
Referenced by clear(), llvm::AsmPrinter::doFinalization(), llvm::AsmPrinter::doInitialization(), and INITIALIZE_PASS_BEGIN().
GCFunctionInfo & GCModuleInfo::getFunctionInfo (const Function & F)
get - Look up function metadata.
Definition at line 90 of file GCMetadata.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::end(), F(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::find(), llvm::Function::getGC(), llvm::GlobalValue::getParent(), llvm::Function::hasGC(), I, llvm::GlobalValue::isDeclaration(), and S.
Referenced by DescKind(), and INITIALIZE_PASS_BEGIN().
Member Data Documentation
char GCModuleInfo::ID = 0 static
Definition at line 178 of file GCMetadata.h.
Referenced by llvm::GCFunctionInfo::~GCFunctionInfo().
The documentation for this class was generated from the following files:
GCMetadata.h
GCMetadata.cpp