LLVM: llvm::object::LibraryRef Class Reference
LLVM API Documentation
llvm::object::LibraryRef Class Reference
#include <ObjectFile.h>
Public Member Functions
LibraryRef ()
LibraryRef (DataRefImpl LibraryP, const ObjectFile *Owner)
bool operator== (const LibraryRef &Other) const
bool operator< (const LibraryRef &Other) const
error_code getNext (LibraryRef &Result) const
error_code getPath (StringRef &Result) const
DataRefImpl getRawDataRefImpl () const
Friends
class SectionRef
Detailed Description
LibraryRef - This is a value type class that represents a single library in the list of libraries needed by a shared or dynamic object.
Definition at line 239 of file ObjectFile.h.
Constructor & Destructor Documentation
llvm::object::LibraryRef::LibraryRef () inline
Definition at line 245 of file ObjectFile.h.
References llvm::object::operator<(), and llvm::object::operator==().
llvm::object::LibraryRef::LibraryRef (DataRefImpl LibraryP, const ObjectFile * Owner) inline
Definition at line 590 of file ObjectFile.h.
Member Function Documentation
error_code llvm::object::LibraryRef::getNext (LibraryRef & Result) const inline
Definition at line 602 of file ObjectFile.h.
References llvm::object::ObjectFile::getLibraryNext().
error_code llvm::object::LibraryRef::getPath (StringRef & Result) const inline
Definition at line 606 of file ObjectFile.h.
References llvm::object::ObjectFile::getLibraryPath().
DataRefImpl llvm::object::LibraryRef::getRawDataRefImpl () const
bool llvm::object::LibraryRef::operator< (const LibraryRef & Other) const inline
Definition at line 598 of file ObjectFile.h.
bool llvm::object::LibraryRef::operator== (const LibraryRef & Other) const inline
Definition at line 594 of file ObjectFile.h.
Friends And Related Function Documentation
friend class SectionRef friend
Definition at line 240 of file ObjectFile.h.
The documentation for this class was generated from the following file:
ObjectFile.h