LLVM: llvm::ValueHandleBase Class Reference
LLVM API Documentation
llvm::ValueHandleBase Class Reference
#include <ValueHandle.h>
Public Member Functions
ValueHandleBase (HandleBaseKind Kind)
ValueHandleBase (HandleBaseKind Kind, Value *V)
ValueHandleBase (HandleBaseKind Kind, const ValueHandleBase &RHS)
~ValueHandleBase ()
Value * operator= (Value *RHS)
Value * operator= (const ValueHandleBase &RHS)
Value * operator-> () const
Value & operator* () const
Static Public Member Functions
static void ValueIsDeleted (Value *V)
static void ValueIsRAUWd (Value *Old, Value *New)
Protected Types
enum HandleBaseKind { Assert, Callback, Tracking, Weak }
Protected Member Functions
Value * getValPtr () const
void setValPtrInt (unsigned K)
unsigned getValPtrInt () const
Static Protected Member Functions
static bool isValid (Value *V)
Friends
class Value
Detailed Description
ValueHandleBase - This is the common base class of value handles. ValueHandle's are smart pointers to Value's that have special behavior when the value is deleted or ReplaceAllUsesWith'd. See the specific handles below for details.
Definition at line 41 of file ValueHandle.h.
Member Enumeration Documentation
enum llvm::ValueHandleBase::HandleBaseKind protected
HandleBaseKind - This indicates what sub class the handle actually is. This is to avoid having a vtable for the light-weight handle pointers. The fully general Callback version does have a vtable.
Enumerator
Assert
Callback
Tracking
Weak
Definition at line 47 of file ValueHandle.h.
Constructor & Destructor Documentation
llvm::ValueHandleBase::ValueHandleBase (HandleBaseKind Kind) inline explicit
Definition at line 66 of file ValueHandle.h.
llvm::ValueHandleBase::ValueHandleBase (HandleBaseKind Kind, Value * V) inline
Definition at line 68 of file ValueHandle.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer(), and isValid().
llvm::ValueHandleBase::ValueHandleBase (HandleBaseKind Kind, const ValueHandleBase & RHS) inline
Definition at line 73 of file ValueHandle.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer(), and isValid().
llvm::ValueHandleBase::~ValueHandleBase () inline
Definition at line 78 of file ValueHandle.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer(), and isValid().
Member Function Documentation
Value* llvm::ValueHandleBase::getValPtr () const inline protected
Definition at line 103 of file ValueHandle.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer().
Referenced by llvm::IVStrideUse::getUser(), llvm::DenseMapInfo< ValueMapCallbackVH< KeyT, ValueT, Config > >::isEqual(), llvm::WeakVH::operator Value *(), llvm::CallbackVH::operator Value *(), llvm::AssertingVH< ValueTy >::operator ValueTy *(), llvm::TrackingVH< ValueTy >::operator ValueTy *(), operator*(), llvm::AssertingVH< const llvm::MDNode >::operator*(), llvm::TrackingVH< ValueTy >::operator*(), operator->(), llvm::AssertingVH< const llvm::MDNode >::operator->(), llvm::TrackingVH< ValueTy >::operator->(), llvm::AssertingVH< const llvm::MDNode >::operator=(), and llvm::TrackingVH< ValueTy >::operator=().
unsigned llvm::ValueHandleBase::getValPtrInt () const inline protected
Definition at line 106 of file ValueHandle.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getInt().
static bool llvm::ValueHandleBase::isValid (Value * V) inline static protected
Definition at line 108 of file ValueHandle.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getInt(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer(), llvm::tgtok::List, llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::setPointer(), ValueIsDeleted(), and ValueIsRAUWd().
Referenced by operator=(), ValueHandleBase(), and ~ValueHandleBase().
Value& llvm::ValueHandleBase::operator* () const inline
Definition at line 100 of file ValueHandle.h.
References getValPtr().
Value* llvm::ValueHandleBase::operator-> () const inline
Definition at line 99 of file ValueHandle.h.
References getValPtr().
Value* llvm::ValueHandleBase::operator= (Value * RHS) inline
Definition at line 83 of file ValueHandle.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer(), isValid(), and llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::setPointer().
Referenced by llvm::WeakVH::operator=(), llvm::MMIAddrLabelMapCallbackPtr::setPtr(), and llvm::CallbackVH::setValPtr().
Value* llvm::ValueHandleBase::operator= (const ValueHandleBase & RHS) inline
Definition at line 91 of file ValueHandle.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer(), isValid(), and llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::setPointer().
void llvm::ValueHandleBase::setValPtrInt (unsigned K) inline protected
Definition at line 105 of file ValueHandle.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::setInt().
void ValueHandleBase::ValueIsDeleted (Value * V) static
Definition at line 620 of file Value.cpp.
References Assert, llvm::dbgs(), llvm::Value::getContext(), llvm::Value::getName(), llvm::Value::getType(), llvm_unreachable, llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::ValueHandles.
Referenced by isValid(), and llvm::Value::~Value().
void ValueHandleBase::ValueIsRAUWd (Value * Old, Value * New) static
Definition at line 677 of file Value.cpp.
References Assert, llvm::dbgs(), llvm::Value::getContext(), llvm::Value::getName(), llvm::Value::getType(), llvm_unreachable, llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::ValueHandles.
Referenced by isExitBlock(), isValid(), llvm::Value::replaceAllUsesWith(), and llvm::SSAUpdater::RewriteUse().
Friends And Related Function Documentation
friend class Value friend
Definition at line 42 of file ValueHandle.h.
The documentation for this class was generated from the following files:
ValueHandle.h
Value.cpp