LLVM: llvm::MachinePassRegistryListener Class Reference
LLVM API Documentation
llvm::MachinePassRegistryListener Class Reference abstract
#include <MachinePassRegistry.h>
Public Member Functions
MachinePassRegistryListener ()
virtual ~MachinePassRegistryListener ()
virtual void NotifyAdd (const char *N, MachinePassCtor C, const char *D)=0
virtual void NotifyRemove (const char *N)=0
Detailed Description
MachinePassRegistryListener - Listener to adds and removals of nodes in registration list.
Definition at line 35 of file MachinePassRegistry.h.
Constructor & Destructor Documentation
llvm::MachinePassRegistryListener::MachinePassRegistryListener () inline
Definition at line 38 of file MachinePassRegistry.h.
virtual llvm::MachinePassRegistryListener::~MachinePassRegistryListener () inline virtual
Definition at line 39 of file MachinePassRegistry.h.
References N, NotifyAdd(), and NotifyRemove().
Member Function Documentation
virtual void llvm::MachinePassRegistryListener::NotifyAdd (const char * N, MachinePassCtor C, const char * D) pure virtual
Implemented in llvm::RegisterPassParser< RegistryClass >.
Referenced by ~MachinePassRegistryListener().
virtual void llvm::MachinePassRegistryListener::NotifyRemove (const char * N) pure virtual
Implemented in llvm::RegisterPassParser< RegistryClass >.
Referenced by ~MachinePassRegistryListener().
The documentation for this class was generated from the following files:
MachinePassRegistry.h
MachinePassRegistry.cpp