LLVM: llvm::LoopBase< BlockT, LoopT > Class Template Reference
LLVM API Documentation
llvm::LoopBase< BlockT, LoopT > Class Template Reference
#include <LoopInfo.h>
Public Types
typedef std::vector< LoopT * >::const_iterator iterator
typedef std::vector< LoopT * >::const_reverse_iterator reverse_iterator
typedef std::vector< BlockT * >::const_iterator block_iterator
typedef std::pair< const BlockT *, const BlockT * > Edge
Edge type.
Public Member Functions
LoopBase ()
Loop ctor - This creates an empty loop.
~LoopBase ()
unsigned getLoopDepth () const
BlockT * getHeader () const
LoopT * getParentLoop () const
void setParentLoop (LoopT *L)
setParentLoop is a raw interface for bypassing addChildLoop.
bool contains (const LoopT *L) const
bool contains (const BlockT *BB) const
template<class InstT >
bool contains (const InstT *Inst) const
const std::vector< LoopT * > & getSubLoops () const
std::vector< LoopT * > & getSubLoopsVector ()
iterator begin () const
iterator end () const
reverse_iterator rbegin () const
reverse_iterator rend () const
bool empty () const
const std::vector< BlockT * > & getBlocks () const
block_iterator block_begin () const
block_iterator block_end () const
unsigned getNumBlocks () const
getNumBlocks - Get the number of blocks in this loop in constant time.
bool isLoopExiting (const BlockT *BB) const
unsigned getNumBackEdges () const
void getExitingBlocks (SmallVectorImpl< BlockT * > &ExitingBlocks) const
BlockT * getExitingBlock () const
void getExitBlocks (SmallVectorImpl< BlockT * > &ExitBlocks) const
BlockT * getExitBlock () const
void getExitEdges (SmallVectorImpl< Edge > &ExitEdges) const
getExitEdges - Return all pairs of (inside_block,outside_block).
BlockT * getLoopPreheader () const
BlockT * getLoopPredecessor () const
BlockT * getLoopLatch () const
void addBasicBlockToLoop (BlockT *NewBB, LoopInfoBase< BlockT, LoopT > &LI)
void replaceChildLoopWith (LoopT *OldChild, LoopT *NewChild)
void addChildLoop (LoopT *NewChild)
LoopT * removeChildLoop (iterator I)
void addBlockEntry (BlockT *BB)
void reverseBlock (unsigned from)
reverseBlocks - interface to reverse Blocks[from, end of loop] in this loop
void reserveBlocks (unsigned size)
reserveBlocks- interface to do reserve() for Blocks
void moveToHeader (BlockT *BB)
void removeBlockFromLoop (BlockT *BB)
void verifyLoop () const
verifyLoop - Verify loop structure
void verifyLoopNest (DenseSet< const LoopT * > *Loops) const
verifyLoop - Verify loop structure of this loop and all nested loops.
void print (raw_ostream &OS, unsigned Depth=0) const
Protected Member Functions
LoopBase (BlockT *BB)
Friends
class LoopInfoBase< BlockT, LoopT >
Detailed Description
template<class BlockT, class LoopT>
class llvm::LoopBase< BlockT, LoopT >
LoopBase class - Instances of this class are used to represent loops that are detected in the flow graph
Definition at line 57 of file LoopInfo.h.
Member Typedef Documentation
template<class BlockT, class LoopT> typedef std::vector<BlockT*>::const_iterator llvm::LoopBase< BlockT, LoopT >::block_iterator
Definition at line 139 of file LoopInfo.h.
template<class BlockT, class LoopT> typedef std::pair<const BlockT*, const BlockT*> llvm::LoopBase< BlockT, LoopT >::Edge
Edge type.
Definition at line 206 of file LoopInfo.h.
template<class BlockT, class LoopT> typedef std::vector<LoopT *>::const_iterator llvm::LoopBase< BlockT, LoopT >::iterator
Definition at line 127 of file LoopInfo.h.
template<class BlockT, class LoopT> typedef std::vector<LoopT *>::const_reverse_iterator llvm::LoopBase< BlockT, LoopT >::reverse_iterator
Definition at line 129 of file LoopInfo.h.
Constructor & Destructor Documentation
template<class BlockT, class LoopT> llvm::LoopBase< BlockT, LoopT >::LoopBase () inline
Loop ctor - This creates an empty loop.
Definition at line 79 of file LoopInfo.h.
template<class BlockT, class LoopT> llvm::LoopBase< BlockT, LoopT >::~LoopBase () inline
Definition at line 80 of file LoopInfo.h.
template<class BlockT, class LoopT> llvm::LoopBase< BlockT, LoopT >::LoopBase (BlockT * BB) inline explicit protected
Definition at line 321 of file LoopInfo.h.
Member Function Documentation
template<class BlockT, class LoopT> void llvm::LoopBase< BlockT, LoopT >::addBasicBlockToLoop (BlockT * NewBB, LoopInfoBase< BlockT, LoopT > & LIB)
addBasicBlockToLoop - This method is used by other analyses to update loop information. NewBB is set to be a new member of the current loop. Because of this, it is added as a member of all parent loops, and is added to the specified LoopInfo object as being in the current basic block. It is not valid to replace the loop header with this method.
Definition at line 185 of file LoopInfoImpl.h.
References llvm::LoopBase< BlockT, LoopT >::replaceChildLoopWith().
Referenced by CloneLoop(), getGEPInductionOperand(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), PlaceSplitBlockCarefully(), llvm::UnrollLoop(), and UpdateAnalysisInformation().
template<class BlockT, class LoopT> void llvm::LoopBase< BlockT, LoopT >::addBlockEntry (BlockT * BB) inline
addBlockEntry - This adds a basic block directly to the basic block list. This should only be used by transformations that create new loops. Other transformations should use addBasicBlockToLoop.
Definition at line 273 of file LoopInfo.h.
Referenced by PlaceSplitBlockCarefully().
template<class BlockT, class LoopT> void llvm::LoopBase< BlockT, LoopT >::addChildLoop (LoopT * NewChild) inline
addChildLoop - Add the specified loop to be a child of this loop. This updates the loop depth of the new child.
Definition at line 252 of file LoopInfo.h.
Referenced by getGEPInductionOperand(), llvm::LPPassManager::insertLoop(), and PlaceSplitBlockCarefully().
template<class BlockT, class LoopT> iterator llvm::LoopBase< BlockT, LoopT >::begin () const inline
Definition at line 130 of file LoopInfo.h.
Referenced by llvm::GraphTraits< const MachineLoop * >::child_begin(), llvm::GraphTraits< MachineLoop * >::child_begin(), llvm::GraphTraits< const Loop * >::child_begin(), llvm::GraphTraits< Loop * >::child_begin(), CloneLoop(), llvm::createHexagonHardwareLoops(), llvm::createLICMPass(), llvm::createLoopDeletionPass(), llvm::createPPCCTRLoopsVerify(), llvm::ScalarEvolution::forgetLoop(), getBlockNum(), LoopIsOuterMostWithPredecessor(), PrintChildLoopComment(), PrintLoopInfo(), llvm::LoopBase< BasicBlock, Loop >::removeChildLoop(), llvm::LoopInfoBase< llvm::MachineBasicBlock, llvm::MachineLoop >::removeLoop(), and llvm::LoopInfo::updateUnloop().
template<class BlockT, class LoopT> block_iterator llvm::LoopBase< BlockT, LoopT >::block_begin () const inline
Definition at line 140 of file LoopInfo.h.
Referenced by ApproximateLoopSize(), areAllUsesIn(), BlockDominatesAnExit(), CloneLoop(), llvm::createLICMPass(), llvm::createLoopDeletionPass(), llvm::createLoopSimplifyPass(), llvm::createPPCCTRLoopsVerify(), deleteIfDeadInstruction(), FindLIVLoopCondition(), getBlockNum(), isStridedPtr(), mayLoopAccessLocation(), PlaceSplitBlockCarefully(), and llvm::LoopInfo::updateUnloop().
template<class BlockT, class LoopT> block_iterator llvm::LoopBase< BlockT, LoopT >::block_end () const inline
Definition at line 141 of file LoopInfo.h.
Referenced by ApproximateLoopSize(), areAllUsesIn(), BlockDominatesAnExit(), CloneLoop(), llvm::createLICMPass(), llvm::createLoopDeletionPass(), llvm::createLoopSimplifyPass(), llvm::createPPCCTRLoopsVerify(), deleteIfDeadInstruction(), FindLIVLoopCondition(), getBlockNum(), isStridedPtr(), mayLoopAccessLocation(), PlaceSplitBlockCarefully(), and llvm::LoopInfo::updateUnloop().
template<class BlockT, class LoopT> bool llvm::LoopBase< BlockT, LoopT >::contains (const LoopT * L) const inline
contains - Return true if the specified loop is contained within in this loop.
Definition at line 104 of file LoopInfo.h.
Referenced by areAllUsesIn(), canConstantEvolve(), canFoldIVIncExpr(), CloneLoop(), CloneLoopBlocks(), ConnectProlog(), llvm::LoopBase< BasicBlock, Loop >::contains(), ConvertToSInt(), llvm::createHexagonHardwareLoops(), llvm::createLICMPass(), llvm::createLoopInstSimplifyPass(), llvm::createLoopSimplifyPass(), llvm::createPPCCTRLoopsVerify(), DeleteTriviallyDeadInstructions(), llvm::Loop::dump(), EvaluateExpression(), FindPHIToPartitionLoops(), llvm::ScalarEvolution::forgetValue(), genLoopLimit(), llvm::ScalarEvolution::getAddRecExpr(), llvm::ScalarEvolution::getLoopDisposition(), getMaxWeightFor(), llvm::LoopBase< BasicBlock, Loop >::getNumBackEdges(), hasOutsideLoopUser(), hasUsesOutsideLoop(), llvm::SCEVExpander::hoistIVInc(), llvm::InsertPreheaderForLoop(), InstructionStoresToFI(), isExitBlock(), isExitingLoop(), isInteresting(), isLoadFromGOTOrConstantPool(), llvm::LoopBase< BasicBlock, Loop >::isLoopExiting(), isSimpleLoadStore(), isSourceDefinedByImplicitDef(), isTrivialLoopExitBlockHelper(), IVUseShouldUsePostIncValue(), PickMostRelevantLoop(), PlaceSplitBlockCarefully(), llvm::LoopInfo::replacementPreservesLCSSAForm(), ReplaceUsesOfWith(), shouldSpeculateInstrs(), llvm::UnrollLoop(), and llvm::LoopBlocksTraversal::visitPreorder().
template<class BlockT, class LoopT> bool llvm::LoopBase< BlockT, LoopT >::contains (const BlockT * BB) const inline
contains - Return true if the specified basic block is in this loop.
Definition at line 112 of file LoopInfo.h.
template<class BlockT, class LoopT> template<class InstT > bool llvm::LoopBase< BlockT, LoopT >::contains (const InstT * Inst) const inline
contains - Return true if the specified instruction is in this loop.
Definition at line 119 of file LoopInfo.h.
template<class BlockT, class LoopT> bool llvm::LoopBase< BlockT, LoopT >::empty () const inline
Definition at line 134 of file LoopInfo.h.
Referenced by emitBasicBlockLoopComments(), and llvm::LoopInfo::updateUnloop().
template<class BlockT, class LoopT> iterator llvm::LoopBase< BlockT, LoopT >::end () const inline
Definition at line 131 of file LoopInfo.h.
Referenced by llvm::GraphTraits< const MachineLoop * >::child_end(), llvm::GraphTraits< MachineLoop * >::child_end(), llvm::GraphTraits< const Loop * >::child_end(), llvm::GraphTraits< Loop * >::child_end(), CloneLoop(), llvm::createHexagonHardwareLoops(), llvm::createLICMPass(), llvm::createLoopDeletionPass(), llvm::createPPCCTRLoopsVerify(), llvm::ScalarEvolution::forgetLoop(), getBlockNum(), LoopIsOuterMostWithPredecessor(), PrintChildLoopComment(), PrintLoopInfo(), llvm::LoopInfoBase< llvm::MachineBasicBlock, llvm::MachineLoop >::removeLoop(), and llvm::LoopInfo::updateUnloop().
template<class BlockT, class LoopT> const std::vector<BlockT*>& llvm::LoopBase< BlockT, LoopT >::getBlocks () const inline
getBlocks - Get a list of the basic blocks which make up this loop.
Definition at line 138 of file LoopInfo.h.
Referenced by CloneLoop(), llvm::createHexagonHardwareLoops(), InstructionStoresToFI(), PlaceSplitBlockCarefully(), shouldSpeculateInstrs(), and llvm::UnrollLoop().
template<class BlockT , class LoopT > BlockT * llvm::LoopBase< BlockT, LoopT >::getExitBlock () const
getExitBlock - If getExitBlocks would return exactly one block, return that block. Otherwise return null.
Definition at line 76 of file LoopInfoImpl.h.
References llvm::LoopBase< BlockT, LoopT >::getExitEdges(), and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by genLoopLimit(), and llvm::LoopBase< BasicBlock, Loop >::getNumBackEdges().
template<class BlockT, class LoopT > void llvm::LoopBase< BlockT, LoopT >::getExitBlocks (SmallVectorImpl< BlockT * > & ExitBlocks) const
getExitBlocks - Return all of the successor blocks of this loop. These are the blocks outside of the current loop which are branched to.
Definition at line 62 of file LoopInfoImpl.h.
References I, and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by BlockDominatesAnExit(), llvm::createLICMPass(), llvm::createLoopInstSimplifyPass(), llvm::createLoopSimplifyPass(), llvm::LoopBase< BlockT, LoopT >::getExitingBlock(), llvm::LoopBase< BasicBlock, Loop >::getNumBackEdges(), INITIALIZE_PASS(), LoopIsOuterMostWithPredecessor(), and PrintLoopInfo().
template<class BlockT , class LoopT > void llvm::LoopBase< BlockT, LoopT >::getExitEdges (SmallVectorImpl< Edge > & ExitEdges) const
getExitEdges - Return all pairs of (inside_block,outside_block).
Definition at line 87 of file LoopInfoImpl.h.
References I, and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by llvm::LoopBase< BlockT, LoopT >::getExitBlock().
template<class BlockT , class LoopT > BlockT * llvm::LoopBase< BlockT, LoopT >::getExitingBlock () const
getExitingBlock - If getExitingBlocks would return exactly one block, return that block. Otherwise return null.
Definition at line 49 of file LoopInfoImpl.h.
References llvm::LoopBase< BlockT, LoopT >::getExitBlocks(), and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by canExpandBackedgeTakenCount(), llvm::createHexagonHardwareLoops(), FindLoopCounter(), genLoopLimit(), getLoopTest(), llvm::LoopBase< BasicBlock, Loop >::getNumBackEdges(), and llvm::UnrollRuntimeLoopProlog().
template<class BlockT, class LoopT > void llvm::LoopBase< BlockT, LoopT >::getExitingBlocks (SmallVectorImpl< BlockT * > & ExitingBlocks) const
getExitingBlocks - Return all blocks inside the loop that have successors outside of the loop. These are the blocks inside of the current loop which branch out. The returned list is always unique.
Definition at line 33 of file LoopInfoImpl.h.
References I, and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by llvm::Region::contains(), llvm::createLoopDeletionPass(), llvm::createLoopSimplifyPass(), llvm::createPPCCTRLoopsVerify(), llvm::ScalarEvolution::forgetValue(), llvm::LoopBase< BasicBlock, Loop >::getNumBackEdges(), InstructionStoresToFI(), isAlwaysFoldable(), and PlaceSplitBlockCarefully().
template<class BlockT, class LoopT> BlockT* llvm::LoopBase< BlockT, LoopT >::getHeader () const inline
Definition at line 95 of file LoopInfo.h.
Referenced by ApproximateLoopSize(), areAllUsesIn(), llvm::LoopBlocksTraversal::begin(), BuildConstantFromSCEV(), canConstantEvolve(), canFoldIVIncExpr(), CloneLoop(), CloneLoopBlocks(), CollectSubexprs(), llvm::Region::contains(), ConvertToSInt(), llvm::createHexagonHardwareLoops(), llvm::createLICMPass(), llvm::createLoopDeletionPass(), llvm::createLoopInstSimplifyPass(), llvm::createLoopSimplifyPass(), llvm::createLoopStrengthReducePass(), llvm::createPPCCTRLoopsVerify(), deleteIfDeadInstruction(), DoInitialMatch(), emitBasicBlockLoopComments(), llvm::LoopBlocksTraversal::end(), EvaluateConstantChrecAtConstant(), EvaluateExpression(), llvm::SCEVExpander::expandCodeFor(), FindLoopCounter(), FindPHIToPartitionLoops(), llvm::ScalarEvolution::forgetValue(), genLoopLimit(), llvm::ScalarEvolution::getAddRecExpr(), llvm::ScalarEvolution::getBlockDisposition(), getBlockNum(), getLoopPhiForCounter(), getMaxWeightFor(), llvm::LoopBase< BasicBlock, Loop >::getNumBackEdges(), llvm::SCEVExpander::getOrInsertCanonicalInductionVariable(), hasUsesOutsideLoop(), llvm::SCEVExpander::hoistIVInc(), INITIALIZE_PASS(), llvm::InsertPreheaderForLoop(), InstructionStoresToFI(), isAlwaysFoldable(), isExistingPhi(), isExitingLoop(), isLoadFromGOTOrConstantPool(), llvm::ScalarEvolution::isLoopBackedgeGuardedByCond(), llvm::ScalarEvolution::isLoopEntryGuardedByCond(), isLoopInvariant(), isProfitableChain(), isSimpleLoadStore(), isSimplifiedLoopNest(), isSourceDefinedByImplicitDef(), isTrivialLoopExitBlock(), llvm::IVUsers::IVUsers(), IVUseShouldUsePostIncValue(), LoopIsOuterMostWithPredecessor(), llvm::SplitEditor::overlapIntv(), PickMostRelevantLoop(), PlaceSplitBlockCarefully(), llvm::SCEV::print(), llvm::IVUsers::print(), PrintLoopInfo(), PrintParentLoopComment(), pushDepHeight(), PushLoopPHIs(), llvm::SCEVExpander::replaceCongruentIVs(), llvm::LPPassManager::runOnFunction(), shouldSpeculateInstrs(), llvm::ScalarEvolution::SimplifyICmpOperands(), llvm::simplifyLoopIVs(), SolveQuadraticEquation(), llvm::UnrollLoop(), and llvm::UnrollRuntimeLoopProlog().
template<class BlockT, class LoopT> unsigned llvm::LoopBase< BlockT, LoopT >::getLoopDepth () const inline
getLoopDepth - Return the nesting level of this loop. An outer-most loop has depth 1, for consistency with loop depth values used for basic blocks, where depth 0 is used for blocks not inside any loops.
Definition at line 88 of file LoopInfo.h.
Referenced by emitBasicBlockLoopComments(), llvm::ScalarEvolution::getAddRecExpr(), getPointerOperand(), llvm::SCEVUnknown::isOffsetOf(), llvm::SplitEditor::overlapIntv(), PrintParentLoopComment(), and UpdateAnalysisInformation().
template<class BlockT , class LoopT > BlockT * llvm::LoopBase< BlockT, LoopT >::getLoopLatch () const
getLoopLatch - If there is a single latch block for this loop, return it. A latch block is a block that contains a branch back to the header.
Definition at line 154 of file LoopInfoImpl.h.
References llvm::LoopBase< BlockT, LoopT >::addBasicBlockToLoop(), and N.
Referenced by ApproximateLoopSize(), areAllUsesIn(), CloneLoopBlocks(), ConnectProlog(), llvm::createHexagonHardwareLoops(), llvm::createLoopSimplifyPass(), FindLoopCounter(), genLoopLimit(), getLoopTest(), llvm::SCEVExpander::hoistIVInc(), isAlwaysFoldable(), llvm::ScalarEvolution::isLoopBackedgeGuardedByCond(), isLoopInvariant(), isProfitableChain(), IVUseShouldUsePostIncValue(), needsLFTR(), PlaceSplitBlockCarefully(), llvm::SCEVExpander::replaceCongruentIVs(), ReplaceUsesOfWith(), shouldSpeculateInstrs(), llvm::UnrollLoop(), and llvm::UnrollRuntimeLoopProlog().
template<class BlockT , class LoopT > BlockT * llvm::LoopBase< BlockT, LoopT >::getLoopPredecessor () const
getLoopPredecessor - If the given loop's header has exactly one unique predecessor outside the loop, return it. Otherwise return null. This is less strict that the loop "preheader" concept, which requires the predecessor to have exactly one successor.
Definition at line 128 of file LoopInfoImpl.h.
References N.
Referenced by isLoadFromGOTOrConstantPool(), llvm::ScalarEvolution::isLoopEntryGuardedByCond(), and SolveQuadraticEquation().
template<class BlockT , class LoopT > BlockT * llvm::LoopBase< BlockT, LoopT >::getLoopPreheader () const
getLoopPreheader - If there is a preheader for this loop, return it. A loop has a preheader if there is only one edge to the header of the loop from outside of the loop. If this is the case, the block branching to the header of the loop is the preheader node.
This method returns null if there is no preheader for the loop.
Definition at line 106 of file LoopInfoImpl.h.
Referenced by areAllUsesIn(), CloneLoopBlocks(), llvm::createHexagonHardwareLoops(), llvm::createLICMPass(), llvm::createLoopDeletionPass(), llvm::createLoopSimplifyPass(), llvm::createPPCCTRLoopsVerify(), deleteIfDeadInstruction(), llvm::SCEVExpander::expandCodeFor(), genLoopLimit(), getMemSetPatternValue(), llvm::SCEVExpander::hoistIVInc(), isAlwaysFoldable(), isLoadFromGOTOrConstantPool(), isLoopInvariant(), isSimpleLoadStore(), PlaceSplitBlockCarefully(), shouldSpeculateInstrs(), llvm::UnrollLoop(), and llvm::UnrollRuntimeLoopProlog().
template<class BlockT, class LoopT> unsigned llvm::LoopBase< BlockT, LoopT >::getNumBackEdges () const inline
getNumBackEdges - Calculate the number of back edges to the loop header
Definition at line 164 of file LoopInfo.h.
Referenced by llvm::createLoopSimplifyPass(), deleteIfDeadInstruction(), and PlaceSplitBlockCarefully().
template<class BlockT, class LoopT> unsigned llvm::LoopBase< BlockT, LoopT >::getNumBlocks () const inline
getNumBlocks - Get the number of blocks in this loop in constant time.
Definition at line 144 of file LoopInfo.h.
Referenced by areAllUsesIn(), llvm::LoopBlocksTraversal::begin(), deleteIfDeadInstruction(), getBlockNum(), llvm::LoopBlocksDFS::isComplete(), isSimpleLoadStore(), and llvm::LoopBlocksDFS::LoopBlocksDFS().
template<class BlockT, class LoopT> LoopT* llvm::LoopBase< BlockT, LoopT >::getParentLoop () const inline
Definition at line 96 of file LoopInfo.h.
Referenced by BuildConstantFromSCEV(), CloneLoop(), CloneLoopBlocks(), ConvertToSInt(), llvm::createHexagonHardwareLoops(), llvm::createLICMPass(), llvm::createPPCCTRLoopsVerify(), llvm::Loop::dump(), emitBasicBlockLoopComments(), llvm::SCEVExpander::expandCodeFor(), getGEPInductionOperand(), getOutermostLoop(), getPointerOperand(), INITIALIZE_PASS(), llvm::LPPassManager::insertLoopIntoQueue(), isLoopInvariant(), LoopIsOuterMostWithPredecessor(), llvm::Region::outermostLoopInRegion(), PlaceSplitBlockCarefully(), llvm::ScalarEvolution::print(), PrintParentLoopComment(), SolveQuadraticEquation(), llvm::UnrollRuntimeLoopProlog(), and llvm::LoopInfo::updateUnloop().
template<class BlockT, class LoopT> const std::vector<LoopT *>& llvm::LoopBase< BlockT, LoopT >::getSubLoops () const inline
iterator/begin/end - Return the loops contained entirely within this loop.
Definition at line 125 of file LoopInfo.h.
Referenced by PlaceSplitBlockCarefully().
template<class BlockT, class LoopT> std::vector<LoopT *>& llvm::LoopBase< BlockT, LoopT >::getSubLoopsVector () inline
Definition at line 126 of file LoopInfo.h.
template<class BlockT, class LoopT> bool llvm::LoopBase< BlockT, LoopT >::isLoopExiting (const BlockT * BB) const inline
isLoopExiting - True if terminator in the block can branch to another block that is outside of the current loop.
Definition at line 151 of file LoopInfo.h.
Referenced by llvm::VirtRegAuxInfo::calculateSpillWeightAndHint(), and shouldSpeculateInstrs().
template<class BlockT, class LoopT> void llvm::LoopBase< BlockT, LoopT >::moveToHeader (BlockT * BB) inline
moveToHeader - This method is used to move BB (which must be part of this loop) to be the loop header of the loop (the block that dominates all others).
Definition at line 291 of file LoopInfo.h.
Referenced by PlaceSplitBlockCarefully(), and shouldSpeculateInstrs().
template<class BlockT , class LoopT > void llvm::LoopBase< BlockT, LoopT >::print (raw_ostream & OS, unsigned Depth = 0) const
Definition at line 318 of file LoopInfoImpl.h.
References BB, llvm::sys::path::begin(), llvm::sys::path::end(), i, I, llvm::raw_ostream::indent(), and llvm::WriteAsOperand().
Referenced by llvm::LoopInfoBase< llvm::MachineBasicBlock, llvm::MachineLoop >::isNotAlreadyContainedIn(), llvm::operator<<(), llvm::LoopInfo::releaseMemory(), and llvm::LoopBase< BasicBlock, Loop >::removeBlockFromLoop().
template<class BlockT, class LoopT> reverse_iterator llvm::LoopBase< BlockT, LoopT >::rbegin () const inline
Definition at line 132 of file LoopInfo.h.
Referenced by addLoopIntoQueue(), and getLoopBackedgeTakenCounts().
template<class BlockT, class LoopT> void llvm::LoopBase< BlockT, LoopT >::removeBlockFromLoop (BlockT * BB) inline
removeBlockFromLoop - This removes the specified basic block from the current loop, updating the Blocks as appropriate. This does not update the mapping in the LoopInfo class.
Definition at line 306 of file LoopInfo.h.
Referenced by PlaceSplitBlockCarefully().
template<class BlockT, class LoopT> LoopT* llvm::LoopBase< BlockT, LoopT >::removeChildLoop (iterator I) inline
removeChildLoop - This removes the specified child from being a subloop of this loop. The loop is not deleted, as it will presumably be inserted into another loop.
Definition at line 261 of file LoopInfo.h.
Referenced by PlaceSplitBlockCarefully(), and llvm::LoopInfo::updateUnloop().
template<class BlockT, class LoopT> reverse_iterator llvm::LoopBase< BlockT, LoopT >::rend () const inline
Definition at line 133 of file LoopInfo.h.
Referenced by addLoopIntoQueue(), and getLoopBackedgeTakenCounts().
template<class BlockT , class LoopT> void llvm::LoopBase< BlockT, LoopT >::replaceChildLoopWith (LoopT * OldChild, LoopT * NewChild)
replaceChildLoopWith - This is used when splitting loops up. It replaces the OldChild entry in our children list with NewChild, and updates the parent pointer of OldChild to be null and the NewChild to be this loop. This updates the loop depth of the new child.
Definition at line 209 of file LoopInfoImpl.h.
References I.
Referenced by llvm::LoopBase< BlockT, LoopT >::addBasicBlockToLoop().
template<class BlockT, class LoopT> void llvm::LoopBase< BlockT, LoopT >::reserveBlocks (unsigned size) inline
reserveBlocks- interface to do reserve() for Blocks
Definition at line 284 of file LoopInfo.h.
template<class BlockT, class LoopT> void llvm::LoopBase< BlockT, LoopT >::reverseBlock (unsigned from) inline
reverseBlocks - interface to reverse Blocks[from, end of loop] in this loop
Definition at line 279 of file LoopInfo.h.
template<class BlockT, class LoopT> void llvm::LoopBase< BlockT, LoopT >::setParentLoop (LoopT * L) inline
setParentLoop is a raw interface for bypassing addChildLoop.
Definition at line 99 of file LoopInfo.h.
template<class BlockT , class LoopT > void llvm::LoopBase< BlockT, LoopT >::verifyLoop () const
verifyLoop - Verify loop structure
Definition at line 222 of file LoopInfoImpl.h.
References BB, llvm::sys::path::begin(), llvm::df_begin(), llvm::df_end(), llvm::df_ext_begin(), llvm::df_ext_end(), llvm::SmallVectorBase::empty(), llvm::sys::path::end(), getParent(), i, I, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), N, llvm::A64CC::NE, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by llvm::LoopBase< BasicBlock, Loop >::removeBlockFromLoop(), and llvm::LPPassManager::runOnFunction().
template<class BlockT , class LoopT> void llvm::LoopBase< BlockT, LoopT >::verifyLoopNest (DenseSet< const LoopT * > * Loops) const
verifyLoop - Verify loop structure of this loop and all nested loops.
Definition at line 307 of file LoopInfoImpl.h.
References llvm::sys::path::begin(), llvm::sys::path::end(), I, and llvm::DenseSet< ValueT, ValueInfoT >::insert().
Referenced by llvm::LoopBase< BasicBlock, Loop >::removeBlockFromLoop().
Friends And Related Function Documentation
template<class BlockT, class LoopT> friend class LoopInfoBase< BlockT, LoopT > friend
Definition at line 320 of file LoopInfo.h.
The documentation for this class was generated from the following files:
LoopInfo.h
LoopInfoImpl.h