LLVM: llvm::IntervalMapImpl::NodeRef Class Reference
LLVM API Documentation
llvm::IntervalMapImpl::NodeRef Class Reference
#include <IntervalMap.h>
Public Member Functions
NodeRef ()
NodeRef - Create a null ref.
LLVM_EXPLICIT operator bool () const
operator bool - Detect a null ref.
template<typename NodeT >
NodeRef (NodeT *p, unsigned n)
NodeRef - Create a reference to the node p with n elements.
unsigned size () const
size - Return the number of elements in the referenced node.
void setSize (unsigned n)
setSize - Update the node size.
NodeRef & subtree (unsigned i) const
template<typename NodeT >
NodeT & get () const
get - Dereference as a NodeT reference.
bool operator== (const NodeRef &RHS) const
bool operator!= (const NodeRef &RHS) const
Detailed Description
Definition at line 486 of file IntervalMap.h.
Constructor & Destructor Documentation
llvm::IntervalMapImpl::NodeRef::NodeRef () inline
NodeRef - Create a null ref.
Definition at line 496 of file IntervalMap.h.
template<typename NodeT > llvm::IntervalMapImpl::NodeRef::NodeRef (NodeT * p, unsigned n) inline
NodeRef - Create a reference to the node p with n elements.
Definition at line 503 of file IntervalMap.h.
Member Function Documentation
template<typename NodeT > NodeT& llvm::IntervalMapImpl::NodeRef::get () const inline
get - Dereference as a NodeT reference.
Definition at line 522 of file IntervalMap.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer().
Referenced by llvm::IntervalMap< SlotIndex, unsigned >::find(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::operator--(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::pathFillFind().
LLVM_EXPLICIT llvm::IntervalMapImpl::NodeRef::operator bool () const inline
operator bool - Detect a null ref.
Definition at line 499 of file IntervalMap.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getOpaqueValue().
bool llvm::IntervalMapImpl::NodeRef::operator!= (const NodeRef & RHS) const inline
Definition at line 533 of file IntervalMap.h.
References llvm::operator==().
bool llvm::IntervalMapImpl::NodeRef::operator== (const NodeRef & RHS) const inline
Definition at line 526 of file IntervalMap.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer().
void llvm::IntervalMapImpl::NodeRef::setSize (unsigned n) inline
setSize - Update the node size.
Definition at line 511 of file IntervalMap.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::setInt().
unsigned llvm::IntervalMapImpl::NodeRef::size () const inline
size - Return the number of elements in the referenced node.
Definition at line 508 of file IntervalMap.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getInt().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), llvm::IntervalMapImpl::Path::getLeftSibling(), and llvm::IntervalMapImpl::Path::moveLeft().
NodeRef& llvm::IntervalMapImpl::NodeRef::subtree (unsigned i) const inline
subtree - Access the i'th subtree reference in a branch node. This depends on branch nodes storing the NodeRef array as their first member.
Definition at line 516 of file IntervalMap.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer().
Referenced by llvm::IntervalMapImpl::Path::getLeftSibling(), llvm::IntervalMapImpl::Path::getRightSibling(), llvm::IntervalMapImpl::Path::moveLeft(), llvm::IntervalMapImpl::Path::moveRight(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::pathFillFind().
The documentation for this class was generated from the following file:
IntervalMap.h