LLVM: llvm::SDNode Class Reference
LLVM API Documentation
llvm::SDNode Class Reference
#include <SelectionDAGNodes.h>
Classes
class use_iterator
Public Types
typedef SDUse * op_iterator
typedef const EVT * value_iterator
Public Member Functions
unsigned getOpcode () const
bool isTargetOpcode () const
bool isTargetMemoryOpcode () const
bool isMachineOpcode () const
unsigned getMachineOpcode () const
bool getHasDebugValue () const
getHasDebugValue - get this bit.
void setHasDebugValue (bool b)
setHasDebugValue - set this bit.
bool use_empty () const
bool hasOneUse () const
size_t use_size () const
int getNodeId () const
void setNodeId (int Id)
setNodeId - Set unique node id.
unsigned getIROrder () const
void setIROrder (unsigned Order)
const DebugLoc getDebugLoc () const
getDebugLoc - Return the source location info.
void setDebugLoc (const DebugLoc dl)
use_iterator use_begin () const
bool hasNUsesOfValue (unsigned NUses, unsigned Value) const
bool hasAnyUseOfValue (unsigned Value) const
bool isOnlyUserOf (SDNode *N) const
bool isOperandOf (SDNode *N) const
bool isPredecessorOf (const SDNode *N) const
bool hasPredecessor (const SDNode *N) const
bool hasPredecessorHelper (const SDNode *N, SmallPtrSet< const SDNode *, 32 > &Visited, SmallVectorImpl< const SDNode * > &Worklist) const
unsigned getNumOperands () const
uint64_t getConstantOperandVal (unsigned Num) const
const SDValue & getOperand (unsigned Num) const
op_iterator op_begin () const
op_iterator op_end () const
SDVTList getVTList () const
SDNode * getGluedNode () const
const SDNode * getGluedMachineNode () const
SDNode * getGluedUser () const
unsigned getNumValues () const
EVT getValueType (unsigned ResNo) const
MVT getSimpleValueType (unsigned ResNo) const
unsigned getValueSizeInBits (unsigned ResNo) const
value_iterator value_begin () const
value_iterator value_end () const
std::string getOperationName (const SelectionDAG *G=0) const
void print_types (raw_ostream &OS, const SelectionDAG *G) const
void print_details (raw_ostream &OS, const SelectionDAG *G) const
void print (raw_ostream &OS, const SelectionDAG *G=0) const
void printr (raw_ostream &OS, const SelectionDAG *G=0) const
void printrFull (raw_ostream &O, const SelectionDAG *G=0) const
void printrWithDepth (raw_ostream &O, const SelectionDAG *G=0, unsigned depth=100) const
void dump () const
dump - Dump this node, for debugging.
void dumpr () const
dumpr - Dump (recursively) this node and its use-def subgraph.
void dump (const SelectionDAG *G) const
void dumpr (const SelectionDAG *G) const
void dumprFull (const SelectionDAG *G=0) const
void dumprWithDepth (const SelectionDAG *G=0, unsigned depth=100) const
void Profile (FoldingSetNodeID &ID) const
void addUse (SDUse &U)
Public Member Functions inherited from llvm::FoldingSetImpl::Node
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Public Member Functions inherited from llvm::ilist_node< SDNode >
SDNode * getPrevNode ()
Get the previous node, or 0 for the list head.
const SDNode * getPrevNode () const
Get the previous node, or 0 for the list head.
SDNode * getNextNode ()
Get the next node, or 0 for the list tail.
const SDNode * getNextNode () const
Get the next node, or 0 for the list tail.
Static Public Member Functions
static use_iterator use_end ()
static const char * getIndexedModeName (ISD::MemIndexedMode AM)
Protected Member Functions
SDNode (unsigned Opc, unsigned Order, const DebugLoc dl, SDVTList VTs, const SDValue *Ops, unsigned NumOps)
SDNode (unsigned Opc, unsigned Order, const DebugLoc dl, SDVTList VTs)
void InitOperands (SDUse *Ops, const SDValue &Op0)
InitOperands - Initialize the operands list of this with 1 operand.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1)
InitOperands - Initialize the operands list of this with 2 operands.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1, const SDValue &Op2)
InitOperands - Initialize the operands list of this with 3 operands.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1, const SDValue &Op2, const SDValue &Op3)
InitOperands - Initialize the operands list of this with 4 operands.
void InitOperands (SDUse *Ops, const SDValue *Vals, unsigned N)
InitOperands - Initialize the operands list of this with N operands.
void DropOperands ()
Protected Member Functions inherited from llvm::ilist_node< SDNode >
ilist_node ()
Static Protected Member Functions
static SDVTList getSDVTList (EVT VT)
Protected Attributes
uint16_t SubclassData: 14
Friends
class SelectionDAG
struct ilist_traits< SDNode >
Detailed Description
SDNode - Represents one node in the SelectionDAG.
Definition at line 306 of file SelectionDAGNodes.h.
Member Typedef Documentation
typedef SDUse* llvm::SDNode::op_iterator
Definition at line 559 of file SelectionDAGNodes.h.
typedef const EVT* llvm::SDNode::value_iterator
Definition at line 626 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
llvm::SDNode::SDNode (unsigned Opc, unsigned Order, const DebugLoc dl, SDVTList VTs, const SDValue * Ops, unsigned NumOps) inline protected
Definition at line 701 of file SelectionDAGNodes.h.
References llvm::checkForCycles(), and i.
llvm::SDNode::SDNode (unsigned Opc, unsigned Order, const DebugLoc dl, SDVTList VTs) inline protected
This constructor adds no operands itself; operands can be set later with InitOperands.
Definition at line 718 of file SelectionDAGNodes.h.
Member Function Documentation
void llvm::SDNode::addUse (SDUse & U) inline
addUse - This method should only be used by the SDUse class.
Definition at line 693 of file SelectionDAGNodes.h.
Referenced by llvm::SDValue::dumpr().
void SDNode::DropOperands () protected
DropOperands - Release the operands and set this node to have zero operands.
Definition at line 5177 of file SelectionDAG.cpp.
References I.
Referenced by llvm::SelectionDAG::DeleteNode().
void SDNode::dump () const
dump - Dump this node, for debugging.
Definition at line 328 of file SelectionDAGDumper.cpp.
Referenced by canFoldInAddressingMode(), CheckForLiveRegDef(), llvm::SelectionDAG::DeleteNode(), llvm::ScheduleDAGSDNodes::dumpNode(), DumpNodes(), llvm::InstrEmitter::EmitDbgValue(), ExpandUnalignedLoad(), findGluedUser(), getBuildPairElt(), GetFPLibCall(), getFusedLdStOpcode(), llvm::MipsDAGToDAGISel::getGlobalBaseReg(), getVCmpEQInst(), getVLDSTRegisterUpdateOpcode(), isOneUseSetCC(), isValidIndexedLoad(), llvm::AMDGPUTargetLowering::LowerOperation(), maskMatters(), llvm::DAGTypeLegalizer::run(), and llvm::SelectionDAGISel::SelectCodeCommon().
void SDNode::dump (const SelectionDAG * G) const
dump - Dump this node, for debugging. The given SelectionDAG allows target-specific nodes to be printed in human-readable form.
Definition at line 329 of file SelectionDAGDumper.cpp.
References llvm::dbgs(), and print().
void SDNode::dumpr () const
dumpr - Dump (recursively) this node and its use-def subgraph.
Definition at line 591 of file SelectionDAGDumper.cpp.
References llvm::dbgs(), DumpNodesr(), and once().
void SDNode::dumpr (const SelectionDAG * G) const
dumpr - Dump (recursively) this node and its use-def subgraph. The given SelectionDAG allows target-specific nodes to be printed in human-readable form.
Definition at line 596 of file SelectionDAGDumper.cpp.
References llvm::dbgs(), DumpNodesr(), and once().
void SDNode::dumprFull (const SelectionDAG * G = 0) const
dumprFull - printrFull to dbgs(). The given SelectionDAG allows target-specific nodes to be printed in human-readable form. Unlike dumpr, this will print the whole DAG, including children that appear multiple times.
Definition at line 637 of file SelectionDAGDumper.cpp.
References dumprWithDepth().
Referenced by llvm::SelectionDAG::AssignTopologicalOrder(), and llvm::ShuffleVectorSDNode::isSplatMask().
void SDNode::dumprWithDepth (const SelectionDAG * G = 0, unsigned depth = 100) const
dumprWithDepth - printrWithDepth to dbgs(). The given SelectionDAG allows target-specific nodes to be printed in human-readable form. Unlike dumpr, this will print children that appear multiple times wherever they are used.
Definition at line 633 of file SelectionDAGDumper.cpp.
References llvm::dbgs(), and printrWithDepth().
Referenced by dumprFull().
uint64_t SDNode::getConstantOperandVal (unsigned Num) const
getConstantOperandVal - Helper method returns the integer value of a ConstantSDNode operand.
Definition at line 6248 of file SelectionDAG.cpp.
Referenced by llvm::InstrEmitter::EmitDbgValue(), findEXTRHalf(), findMaskedBFI(), findUser(), getBuildPairElt(), GetFPLibCall(), getVCmpEQInst(), isCalleeLoad(), lowerMSABitClearImm(), lowerMSASplatImm(), PerformANDCombine(), PerformBrCondCombine(), PerformCMOVCombine(), PerformSETCCCombine(), PerformSRACombine(), SubIdx2Lane(), tryCombineToBFI(), tryCombineToLargerBFI(), and useSinCos().
const DebugLoc llvm::SDNode::getDebugLoc () const inline
getDebugLoc - Return the source location info.
Definition at line 431 of file SelectionDAGNodes.h.
Referenced by countOperands(), llvm::InstrEmitter::EmitDbgValue(), llvm::SDLoc::getDebugLoc(), and llvm::SelectionDAG::SelectNodeTo().
const SDNode* llvm::SDNode::getGluedMachineNode () const inline
Definition at line 579 of file SelectionDAGNodes.h.
References getGluedNode(), isMachineOpcode(), and N.
SDNode* llvm::SDNode::getGluedNode () const inline
getGluedNode - If this node has a glue operand, return the node to which the glue operand points. Otherwise return NULL.
Definition at line 570 of file SelectionDAGNodes.h.
References llvm::MVT::Glue.
Referenced by llvm::ScheduleDAGSDNodes::RegDefIter::Advance(), canClobberPhysRegDefs(), CheckForLiveRegDef(), llvm::ScheduleDAGSDNodes::computeLatency(), llvm::ScheduleDAGSDNodes::dumpNode(), llvm::ScheduleDAGSDNodes::EmitSchedule(), FindCallSeqStart(), getGluedMachineNode(), llvm::ScheduleDAGSDNodes::getGraphNodeLabel(), getNodeRegMask(), getVLDSTRegisterUpdateOpcode(), isOperandOf(), llvm::ResourcePriorityQueue::isResourceAvailable(), llvm::SelectionDAGBuilder::LowerCallOperands(), RemoveUnusedGlue(), and llvm::ResourcePriorityQueue::reserveResources().
SDNode* llvm::SDNode::getGluedUser () const inline
getGluedUser - If this node has a glue value with a user, return the user (there is at most one). Otherwise return NULL.
Definition at line 595 of file SelectionDAGNodes.h.
References llvm::MVT::Glue.
Referenced by AddCombineTo64bitMLAL(), llvm::InstrEmitter::EmitDbgValue(), findGluedUser(), and getVLDSTRegisterUpdateOpcode().
bool llvm::SDNode::getHasDebugValue () const inline
getHasDebugValue - get this bit.
Definition at line 395 of file SelectionDAGNodes.h.
Referenced by ProcessSDDbgValues(), and llvm::SelectionDAG::TransferDbgValues().
const char * SDNode::getIndexedModeName (ISD::MemIndexedMode AM) static
Definition at line 318 of file SelectionDAGDumper.cpp.
References llvm::ISD::POST_DEC, llvm::ISD::POST_INC, llvm::ISD::PRE_DEC, and llvm::ISD::PRE_INC.
unsigned llvm::SDNode::getIROrder () const inline
getIROrder - Return the node ordering.
Definition at line 424 of file SelectionDAGNodes.h.
Referenced by llvm::SDLoc::getIROrder(), getNodeRegMask(), ProcessSourceNode(), and llvm::SelectionDAG::SelectNodeTo().
unsigned llvm::SDNode::getMachineOpcode () const inline
getMachineOpcode - This may only be called if isMachineOpcode returns true. It returns the MachineInstr opcode value that the node's opcode corresponds to.
Definition at line 389 of file SelectionDAGNodes.h.
Referenced by llvm::SITargetLowering::AdjustInstrPostInstrSelection(), llvm::SITargetLowering::analyzeImmediate(), llvm::ARMBaseInstrInfo::areLoadsFromSameBasePtr(), llvm::X86InstrInfo::areLoadsFromSameBasePtr(), llvm::ScheduleDAGSDNodes::BuildSchedGraph(), CalcNodeSethiUllmanNumber(), canClobberPhysRegDefs(), canClobberReachingPhysRegUse(), canEnableCoalescing(), CheckForPhysRegDependency(), llvm::ScheduleDAG::clearDAG(), llvm::ScheduleDAGSDNodes::computeLatency(), llvm::ScheduleDAGSDNodes::computeOperandLatency(), countOperands(), llvm::createAMDGPUISelDag(), llvm::InstrEmitter::EmitDbgValue(), FindCallSeqStart(), FoldOperand(), GetCostForDef(), llvm::TargetInstrInfo::getInstrLatency(), llvm::ARMBaseInstrInfo::getOperandLatency(), llvm::TargetInstrInfo::getOperandLatency(), getOperationName(), getPhysicalRegisterVT(), llvm::ARMTargetLowering::getSchedulingPreference(), getVCmpEQInst(), IsChainDependent(), isNodeChanged(), llvm::ResourcePriorityQueue::isResourceAvailable(), isScaledConstantInRange(), llvm::ScheduleDAGSDNodes::newSUnit(), llvm::SITargetLowering::PostISelFolding(), RemoveUnusedGlue(), llvm::ResourcePriorityQueue::reserveResources(), llvm::ARMBaseInstrInfo::shouldScheduleLoadsNear(), llvm::X86InstrInfo::shouldScheduleLoadsNear(), and llvm::X86InstrInfo::unfoldMemoryOperand().
int llvm::SDNode::getNodeId () const inline
getNodeId - Return the unique node id.
Definition at line 417 of file SelectionDAGNodes.h.
Referenced by llvm::SelectionDAG::AssignTopologicalOrder(), canClobberPhysRegDefs(), canEnableCoalescing(), CheckForLiveRegDef(), FindCallSeqStart(), findGluedUser(), findNonImmUse(), llvm::ScheduleDAGSDNodes::getCustomGraphFeatures(), insertDAGNode(), InsertDAGNode(), isLoadIncOrDecStore(), isOperandOf(), RemoveUnusedGlue(), llvm::DAGTypeLegalizer::run(), and WalkChainUsers().
unsigned llvm::SDNode::getNumOperands () const inline
getNumOperands - Return the number of values used by this operation.
Definition at line 548 of file SelectionDAGNodes.h.
Referenced by AddCombineTo64bitMLAL(), AddCombineToVPADDL(), AddGlue(), AddNodeIDNode(), llvm::ISD::allOperandsUndef(), llvm::SelectionDAG::AssignTopologicalOrder(), CheckForLiveRegDef(), CheckForMaskedLoad(), CloneNodeWithValues(), CombineBaseUpdate(), countOperands(), llvm::createAMDGPUISelDag(), DumpNodes(), DumpNodesr(), llvm::InstrEmitter::EmitDbgValue(), llvm::SDNodeIterator::end(), ExpandUnalignedLoad(), FindCallSeqStart(), findNonImmUse(), findUser(), llvm::SelectionDAG::FoldConstantArithmetic(), FoldOperand(), llvm::PPC::get_VSPLTI_elt(), getBuildPairElt(), getCodeAddrSpace(), getInputChainForNode(), getNodeRegMask(), getTargetShuffleMask(), getVLDSTRegisterUpdateOpcode(), HandleMergeInputChains(), hasPredecessorHelper(), llvm::ISD::isBuildVectorAllOnes(), llvm::ISD::isBuildVectorAllZeros(), IsChainDependent(), isConstantOrUndefBUILD_VECTOR(), llvm::BuildVectorSDNode::isConstantSplat(), isConstantSplatVector(), isExtendedBUILD_VECTOR(), isNodeChanged(), llvm::X86TargetLowering::isNoopAddrSpaceCast(), isOneUseSetCC(), isOpcWithIntImmediate(), llvm::SDValue::isOperandOf(), isOperandOf(), llvm::ISD::isScalarToVector(), llvm::ShuffleVectorSDNode::isSplatMask(), isSplatVector(), isXor1OfSetCC(), llvm::ARMTargetLowering::LowerAsmOperandForConstraint(), llvm::NVPTXTargetLowering::LowerCall(), lowerDSPIntr(), llvm::SparcTargetLowering::LowerF128Op(), llvm::AArch64TargetLowering::LowerF128ToCall(), llvm::HexagonTargetLowering::LowerINLINEASM(), LowerInterruptReturn(), llvm::NVPTXTargetLowering::LowerOperation(), MoveBelowOrigChain(), OffsetFitsS11(), ConsecutiveMemoryChainSorter::operator()(), partitionShuffleOfConcats(), performANDCombine(), PerformBUILD_VECTORCombine(), PerformSELECTCombine(), performSRACombine(), PerformSTORECombine(), print(), printrWithDepthHelper(), llvm::ResourcePriorityQueue::rawRegPressureDelta(), llvm::SDValue::reachesChainWithoutSideEffects(), RemoveUnusedGlue(), ReplaceATOMIC_OP_64(), replaceInChain(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), llvm::DAGTypeLegalizer::run(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::ResourcePriorityQueue::scheduledNode(), llvm::SelectionDAGISel::SelectCodeCommon(), SubIdx2Lane(), llvm::X86InstrInfo::unfoldMemoryOperand(), llvm::SelectionDAG::UnrollVectorOp(), llvm::SelectionDAG::UpdateNodeOperands(), useDivRem(), VerifyNodeCommon(), and WillBeConstantPoolLoad().
unsigned llvm::SDNode::getNumValues () const inline
getNumValues - Return the number of values defined/returned by this operator.
Definition at line 605 of file SelectionDAGNodes.h.
Referenced by AddCombineTo64bitMLAL(), AddGlue(), llvm::ScheduleDAGSDNodes::BuildSchedGraph(), BURRSort(), CalcNodeSethiUllmanNumber(), canChangeToInt(), canClobberPhysRegDefs(), llvm::InstrEmitter::CountResults(), llvm::SelectionDAG::DeleteNode(), doNotCSE(), llvm::InstrEmitter::EmitDbgValue(), ExpandUnalignedLoad(), findGluedUser(), findGlueUse(), findUser(), GetFPLibCall(), llvm::ARMTargetLowering::getSchedulingPreference(), llvm::SelectionDAGBuilder::getValueImpl(), GetVBR(), getVLDSTRegisterUpdateOpcode(), HandleMergeInputChains(), hasAnyUseOfValue(), hasNUsesOfValue(), InsertFenceForAtomic(), isADDADDMUL(), isConstantSplatVector(), llvm::SelectionDAGISel::IsLegalToFold(), llvm::X86TargetLowering::isNoopAddrSpaceCast(), isOneUseSetCC(), isOperandOf(), isTruncateOf(), LowerInterruptReturn(), llvm::MipsTargetLowering::LowerOperationWrapper(), llvm::DAGTypeLegalizer::NoteDeletion(), PerformCMOVCombine(), print_types(), llvm::ResourcePriorityQueue::rawRegPressureDelta(), RemoveUnusedGlue(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), llvm::DAGTypeLegalizer::run(), llvm::ResourcePriorityQueue::scheduledNode(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::TargetLowering::TargetLoweringOpt::ShrinkDemandedOp(), llvm::X86InstrInfo::unfoldMemoryOperand(), llvm::SelectionDAG::UnrollVectorOp(), useSinCos(), and VerifyNodeCommon().
unsigned llvm::SDNode::getOpcode () const inline
getOpcode - Return the SelectionDAG opcode value for this node. For pre-isel nodes (those for which isMachineOpcode returns false), these are the opcode values in the ISD and <target>ISD namespaces. For post-isel opcodes, see getMachineOpcode.
Definition at line 369 of file SelectionDAGNodes.h.
Referenced by AddCombineTo64bitMLAL(), AddCombineToVPADDL(), AddNodeIDCustom(), AddNodeIDNode(), llvm::SITargetLowering::analyzeImmediate(), llvm::ScheduleDAGSDNodes::BuildSchedGraph(), CalcNodeSethiUllmanNumber(), canEnableCoalescing(), canFoldInAddressingMode(), CanFoldXORWithAllOnes(), CheckAndImm(), CheckForLiveRegDef(), CheckForMaskedLoad(), CheckForPhysRegDependency(), CheckOpcode(), CheckOrImm(), llvm::AddrSpaceCastSDNode::classof(), llvm::MemSDNode::classof(), llvm::AtomicSDNode::classof(), llvm::MemIntrinsicSDNode::classof(), llvm::ShuffleVectorSDNode::classof(), llvm::ConstantSDNode::classof(), llvm::ConstantFPSDNode::classof(), llvm::GlobalAddressSDNode::classof(), llvm::FrameIndexSDNode::classof(), llvm::JumpTableSDNode::classof(), llvm::ConstantPoolSDNode::classof(), llvm::TargetIndexSDNode::classof(), llvm::BasicBlockSDNode::classof(), llvm::BuildVectorSDNode::classof(), llvm::SrcValueSDNode::classof(), llvm::MDNodeSDNode::classof(), llvm::RegisterSDNode::classof(), llvm::RegisterMaskSDNode::classof(), llvm::BlockAddressSDNode::classof(), llvm::EHLabelSDNode::classof(), llvm::ExternalSymbolSDNode::classof(), llvm::CondCodeSDNode::classof(), llvm::CvtRndSatSDNode::classof(), llvm::VTSDNode::classof(), llvm::LSBaseSDNode::classof(), llvm::LoadSDNode::classof(), llvm::StoreSDNode::classof(), CloneNodeWithValues(), CombineBaseUpdate(), combineSelectAndUse(), CombineVLDDUP(), llvm::ScheduleDAGSDNodes::computeLatency(), llvm::ScheduleDAGSDNodes::computeOperandLatency(), countOperands(), llvm::createAMDGPUISelDag(), llvm::createNVPTXISelDag(), llvm::createXCoreISelDag(), llvm::SelectionDAG::DeleteNode(), doNotCSE(), EltsFromConsecutiveLoads(), llvm::InstrEmitter::EmitDbgValue(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), Expand64BitShift(), expandDisp(), ExpandUnalignedLoad(), ExtendUsesToFormExtLoad(), FindCallSeqStart(), findConsecutiveLoad(), findGluedUser(), findMUL_LOHI(), findUser(), FoldMaskAndShiftToScale(), getARMIndexedAddressParts(), getAtomicLoadArithTargetConstant(), getBuildPairElt(), getCodeAddrSpace(), GetCostForDef(), GetFPLibCall(), getFusedLdStOpcode(), llvm::MipsDAGToDAGISel::getGlobalBaseReg(), getIndexedAddressParts(), llvm::SelectionDAG::getNode(), getOperationName(), llvm::ARMTargetLowering::getPostIndexedAddressParts(), getT2IndexedAddressParts(), getTargetShuffleMask(), GetVBR(), getVCmpEQInst(), getVLDSTRegisterUpdateOpcode(), HandleMergeInputChains(), hasOnlyLiveInOpers(), hasOnlyLiveOutUses(), isADDADDMUL(), isAddSubSExt(), isAddSubZExt(), isBitwiseInverse(), llvm::ISD::isBuildVectorAllOnes(), llvm::ISD::isBuildVectorAllZeros(), isCalleeLoad(), IsChainDependent(), isConditionalZeroOrAllOnes(), isConstantOrUndef(), isConstantSplatVector(), isExtendedBUILD_VECTOR(), llvm::X86TargetLowering::isGAPlusOffset(), llvm::TargetLowering::isGAPlusOffset(), isInt32Immediate(), isInt64Immediate(), isIntS16Immediate(), llvm::X86TargetLowering::isNoopAddrSpaceCast(), isOneUseSetCC(), isOpcWithIntImmediate(), llvm::ScheduleDAGSDNodes::isPassiveNode(), isScalarLoadToVector(), llvm::ISD::isScalarToVector(), isScaledConstantInRange(), isSignExtended(), IsSingleInstrConstant(), isSlicingProfitable(), isSplatVector(), isTruncateOf(), isValidIndexedLoad(), isVectorAllOnes(), isX86LogicalCmp(), isXor1OfSetCC(), isZeroExtended(), llvm::ARMTargetLowering::LowerAsmOperandForConstraint(), llvm::AArch64TargetLowering::LowerBUILD_VECTOR(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SelectionDAGBuilder::LowerCallOperands(), LowerEXTRACT_VECTOR_ELT_SSE4(), llvm::HexagonTargetLowering::LowerINLINEASM(), LowerInterruptReturn(), llvm::MSP430TargetLowering::LowerJumpTable(), LowerShift(), LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLEv8i8(), LowerVectorAllZeroTest(), maskMatters(), BaseIndexOffset::match(), MatchRotateHalf(), OffsetFitsS11(), ConsecutiveMemoryChainSorter::operator()(), OptimizeConditionalInDecrement(), partitionShuffleOfConcats(), performANDCombine(), PerformARMBUILD_VECTORCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::MipsSETargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PerformDAGCombine(), llvm::MipsTargetLowering::PerformDAGCombine(), llvm::ARMTargetLowering::PerformDAGCombine(), llvm::AArch64TargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::X86TargetLowering::PerformDAGCombine(), performDivRemCombine(), PerformExtendCombine(), PerformEXTRACT_VECTOR_ELTCombine(), PerformFMinFMaxCombine(), PerformFORCombine(), performIntegerAbsCombine(), PerformMulCombine(), performORCombine(), PerformOrCombine(), PerformSELECTCombine(), PerformShiftCombine(), PerformShuffleCombine(), performSRACombine(), PerformSTORECombine(), PerformVCVTCombine(), PerformVDIVCombine(), performVSELECTCombine(), performXORCombine(), llvm::SDValue::reachesChainWithoutSideEffects(), RemoveUnusedGlue(), ReplaceATOMIC_OP_64(), replaceInChain(), ReplaceINTRINSIC_W_CHAIN(), llvm::R600TargetLowering::ReplaceNodeResults(), llvm::XCoreTargetLowering::ReplaceNodeResults(), llvm::SparcTargetLowering::ReplaceNodeResults(), llvm::ARMTargetLowering::ReplaceNodeResults(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), resetVRegCycle(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), llvm::DAGTypeLegalizer::run(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::SelectionDAGISel::SelectCodeCommon(), selectMADD(), selectMSUB(), shouldUseLA(), llvm::TargetLowering::SimplifyDemandedBits(), SkipExtensionForVMULL(), SplitVSETCC(), tryCombineToBFI(), tryCombineToEXTR(), llvm::SelectionDAG::UnrollVectorOp(), useDivRem(), useSinCos(), VerifyNodeCommon(), WalkChainUsers(), WidenMaskArithmetic(), and WillBeConstantPoolLoad().
const SDValue& llvm::SDNode::getOperand (unsigned Num) const inline
Definition at line 554 of file SelectionDAGNodes.h.
Referenced by AddCombineTo64bitMLAL(), AddCombineToVPADDL(), AddGlue(), llvm::SITargetLowering::AdjustInstrPostInstrSelection(), llvm::ISD::allOperandsUndef(), llvm::SITargetLowering::analyzeImmediate(), llvm::ARMBaseInstrInfo::areLoadsFromSameBasePtr(), llvm::X86InstrInfo::areLoadsFromSameBasePtr(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), canClobberPhysRegDefs(), canEnableCoalescing(), canFoldInAddressingMode(), CanFoldXORWithAllOnes(), CheckAndImm(), CheckForLiveRegDef(), CheckForMaskedLoad(), CheckForPhysRegDependency(), CheckOrImm(), CloneNodeWithValues(), CMPEQCombine(), CombineBaseUpdate(), combineSelectAndUseCommutative(), combineShlAddConstant(), CombineVLDDUP(), CommuteVectorShuffle(), Compact8x32ShuffleNode(), llvm::ScheduleDAGSDNodes::computeOperandLatency(), countOperands(), llvm::createAMDGPUISelDag(), llvm::createMSP430ISelDag(), llvm::createXCoreISelDag(), DumpNodes(), DumpNodesr(), llvm::InstrEmitter::EmitDbgValue(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), Expand64BitShift(), ExpandBITCAST(), ExpandUnalignedLoad(), ExtendUsesToFormExtLoad(), ExtractBitFromMaskVector(), FindCallSeqStart(), findEXTRHalf(), findNonImmUse(), findUser(), llvm::SelectionDAG::FoldConstantArithmetic(), FoldMaskAndShiftToScale(), FoldOperand(), llvm::PPC::get_VSPLTI_elt(), getARMIndexedAddressParts(), getAtomicLoadArithTargetConstant(), getBuildPairElt(), getCodeAddrSpace(), GetCostForDef(), getCTPOP16BitCounts(), llvm::DOTGraphTraits< SelectionDAG * >::getEdgeAttributes(), llvm::DOTGraphTraits< SelectionDAG * >::getEdgeTarget(), getExtractVEXTRACTImmediate(), GetFPLibCall(), getFusedLdStOpcode(), getIndexedAddressParts(), getInputChainForNode(), getInsertVINSERTImmediate(), llvm::SelectionDAG::getNode(), getNodeRegMask(), llvm::SDValue::getOperand(), llvm::ARMBaseInstrInfo::getOperandLatency(), getOperationName(), getShuffleScalarElt(), getT2IndexedAddressParts(), getTargetShuffleMask(), getVCmpEQInst(), getVLDSTRegisterUpdateOpcode(), HandleMergeInputChains(), hasNormalLoadOperand(), hasOnlyLiveInOpers(), hasOnlyLiveOutUses(), hasPredecessorHelper(), isADDADDMUL(), isAddSubSExt(), isAddSubZExt(), llvm::PPC::isAllNegativeZeroVector(), isBitwiseInverse(), isBSwapHWordElement(), llvm::ISD::isBuildVectorAllOnes(), llvm::ISD::isBuildVectorAllZeros(), isCalleeLoad(), IsChainDependent(), isConditionalZeroOrAllOnes(), llvm::SelectionDAG::isConsecutiveLoad(), isConstantOrUndefBUILD_VECTOR(), llvm::BuildVectorSDNode::isConstantSplat(), isConstantSplatVector(), isDispSafeForFrameIndex(), isExtendedBUILD_VECTOR(), llvm::X86TargetLowering::isGAPlusOffset(), llvm::TargetLowering::isGAPlusOffset(), llvm::AArch64TargetLowering::isKnownShuffleVector(), isLoadIncOrDecStore(), isLocalCall(), isNodeChanged(), llvm::X86TargetLowering::isNoopAddrSpaceCast(), isOneUseSetCC(), isOpcWithIntImmediate(), llvm::SDValue::isOperandOf(), isOperandOf(), isScalarLoadToVector(), llvm::ISD::isScalarToVector(), isScaledConstantInRange(), IsSingleInstrConstant(), isSlicingProfitable(), llvm::ShuffleVectorSDNode::isSplatMask(), isSplatVector(), isTruncateOf(), isValidIndexedLoad(), isVectorAllOnes(), isVectorShiftLeft(), isVectorShiftRight(), isVEXTRACTIndex(), isVINSERTIndex(), isWordAligned(), isXor1OfSetCC(), isZeroShuffle(), llvm::ARMTargetLowering::LowerAsmOperandForConstraint(), LowerATOMIC_STORE(), LowerAVXExtend(), llvm::AArch64TargetLowering::LowerBUILD_VECTOR(), llvm::NVPTXTargetLowering::LowerCall(), llvm::SelectionDAGBuilder::LowerCallOperands(), lowerCTPOP32BitElements(), LowerCTTZ(), lowerDSPIntr(), lowerGR128Binary(), llvm::HexagonTargetLowering::LowerINLINEASM(), LowerINSERT_SUBVECTOR(), LowerInterruptReturn(), llvm::MSP430TargetLowering::LowerJumpTable(), LowerLabelRef(), LowerLOAD_SUB(), lowerMSABinaryBitImmIntr(), lowerMSABitClear(), lowerMSABitClearImm(), lowerMSACopyIntr(), lowerMSALoadIntr(), lowerMSASplatZExt(), lowerMSAStoreIntr(), llvm::NVPTXTargetLowering::LowerOperation(), LowerScalarImmediateShift(), LowerShift(), llvm::MSP430TargetLowering::LowerShifts(), LowerSIGN_EXTEND(), LowerSIGN_EXTEND_AVX512(), llvm::MipsTargetLowering::lowerSTORE(), LowerVAARG(), LowerVECTOR_SHUFFLE_128v4(), LowerVECTOR_SHUFFLE_256(), lowerVECTOR_SHUFFLE_ILVEV(), lowerVECTOR_SHUFFLE_ILVL(), lowerVECTOR_SHUFFLE_ILVOD(), lowerVECTOR_SHUFFLE_ILVR(), lowerVECTOR_SHUFFLE_PCKEV(), lowerVECTOR_SHUFFLE_PCKOD(), lowerVECTOR_SHUFFLE_SHF(), lowerVECTOR_SHUFFLE_VSHF(), LowerVECTOR_SHUFFLEtoBlend(), LowerVECTOR_SHUFFLEv16i8(), LowerVECTOR_SHUFFLEv32i8(), LowerVECTOR_SHUFFLEv8i16(), LowerVectorAllZeroTest(), LowerXALUO(), LowerZERO_EXTEND_AVX512(), maskMatters(), BaseIndexOffset::match(), MatchRotateHalf(), OffsetFitsS11(), ConsecutiveMemoryChainSorter::operator()(), llvm::SDNodeIterator::operator*(), OptimizeConditionalInDecrement(), partitionShuffleOfConcats(), PerformADCCombine(), performADDCombine(), PerformADDCombine(), PerformAddCombine(), performANDCombine(), PerformANDCombine(), PerformAndCombine(), PerformARMBUILD_VECTORCombine(), PerformBFICombine(), PerformBrCondCombine(), PerformBTCombine(), PerformBUILD_VECTORCombine(), llvm::ARMTargetLowering::PerformCMOVCombine(), PerformCMOVCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PerformDAGCombine(), llvm::ARMTargetLowering::PerformDAGCombine(), llvm::AArch64TargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performDivRemCombine(), performDSPShiftCombine(), PerformExtendCombine(), PerformEXTRACT_VECTOR_ELTCombine(), PerformFADDCombine(), PerformFANDCombine(), PerformFANDNCombine(), PerformFMACombine(), PerformFMinFMaxCombine(), PerformFORCombine(), PerformFSUBCombine(), PerformInsertEltCombine(), performIntegerAbsCombine(), PerformIntrinsicCombine(), PerformISDSETCCCombine(), performMULCombine(), PerformMULCombine(), PerformMulCombine(), performORCombine(), PerformORCombine(), PerformOrCombine(), PerformSELECT_CCCombine(), performSELECTCombine(), PerformSELECTCombine(), performSETCCCombine(), PerformSETCCCombine(), PerformShiftCombine(), performShiftToAllZeros(), PerformSHLCombine(), PerformShuffleCombine256(), PerformSIGN_EXTEND_INREGCombine(), PerformSINT_TO_FPCombine(), performSRACombine(), PerformSRACombine(), PerformSTORECombine(), PerformSUBCombine(), PerformSubCombine(), PerformVCVTCombine(), PerformVDIVCombine(), PerformVDUPLANECombine(), PerformVECTOR_SHUFFLECombine(), PerformVMOVDRRCombine(), PerformVMOVRRDCombine(), PerformVMULCombine(), performVSELECTCombine(), PerformVZEXT_MOVLCombine(), performVZEXTCombine(), performXORCombine(), PerformXorCombine(), PerformZExtCombine(), print(), printrWithDepthHelper(), PromoteSplat(), llvm::ResourcePriorityQueue::rawRegPressureDelta(), llvm::SDValue::reachesChainWithoutSideEffects(), RemoveUnusedGlue(), ReplaceATOMIC_BINARY_64(), ReplaceATOMIC_LOAD(), ReplaceATOMIC_OP_64(), replaceInChain(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::R600TargetLowering::ReplaceNodeResults(), llvm::SparcTargetLowering::ReplaceNodeResults(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), ReplaceREADCYCLECOUNTER(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), RewriteAsNarrowerShuffle(), llvm::DAGTypeLegalizer::run(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::ResourcePriorityQueue::scheduledNode(), llvm::SelectionDAGISel::SelectCodeCommon(), selectMADD(), selectMSUB(), llvm::TargetLowering::TargetLoweringOpt::ShrinkDemandedOp(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifySetCC(), SkipExtensionForVMULL(), llvm::SelectionDAG::SplitVectorOperand(), SplitVSETCC(), SubIdx2Lane(), tryCombineToBFI(), tryCombineToEXTR(), tryCombineToLargerBFI(), tryFoldToZero(), llvm::X86InstrInfo::unfoldMemoryOperand(), llvm::SelectionDAG::UnrollVectorOp(), llvm::SelectionDAG::UpdateNodeOperands(), useDivRem(), useSinCos(), ValueHasExactlyOneBitSet(), VerifyNodeCommon(), WidenMaskArithmetic(), WillBeConstantPoolLoad(), and XFormVExtractWithShuffleIntoLoad().
std::string SDNode::getOperationName (const SelectionDAG * G = 0) const
getOperationName - Return the opcode of this operation for printing.
Definition at line 33 of file SelectionDAGDumper.cpp.
References llvm::ISD::ADD, llvm::ISD::ADDC, llvm::ISD::ADDE, llvm::ISD::ADDRSPACECAST, llvm::ISD::ADJUST_TRAMPOLINE, llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_FENCE, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_XOR, llvm::ISD::ATOMIC_STORE, llvm::ISD::ATOMIC_SWAP, llvm::ISD::BasicBlock, llvm::ISD::BITCAST, llvm::ISD::BlockAddress, llvm::ISD::BR, llvm::ISD::BR_CC, llvm::ISD::BR_JT, llvm::ISD::BRCOND, llvm::ISD::BRIND, llvm::ISD::BSWAP, llvm::ISD::BUILD_PAIR, llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, llvm::ISD::CALLSEQ_END, llvm::ISD::CALLSEQ_START, llvm::ISD::CARRY_FALSE, llvm::ISD::CONCAT_VECTORS, llvm::ISD::CONDCODE, llvm::ISD::Constant, llvm::ISD::ConstantFP, llvm::ISD::ConstantPool, llvm::ISD::CONVERT_RNDSAT, llvm::ISD::CopyFromReg, llvm::ISD::CopyToReg, llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::ISD::CVT_FF, llvm::ISD::CVT_FS, llvm::ISD::CVT_FU, llvm::ISD::CVT_SF, llvm::ISD::CVT_SS, llvm::ISD::CVT_SU, llvm::ISD::CVT_UF, llvm::ISD::CVT_US, llvm::ISD::CVT_UU, llvm::ISD::DEBUGTRAP, llvm::ISD::DELETED_NODE, llvm::ISD::DYNAMIC_STACKALLOC, llvm::ISD::EH_LABEL, llvm::ISD::EH_RETURN, llvm::ISD::EH_SJLJ_LONGJMP, llvm::ISD::EH_SJLJ_SETJMP, llvm::ISD::EntryToken, llvm::ISD::ExternalSymbol, llvm::ISD::EXTRACT_ELEMENT, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FCEIL, llvm::ISD::FCOPYSIGN, llvm::ISD::FCOS, llvm::ISD::FDIV, llvm::ISD::FEXP, llvm::ISD::FEXP2, llvm::ISD::FFLOOR, llvm::ISD::FGETSIGN, llvm::ISD::FLOG, llvm::ISD::FLOG10, llvm::ISD::FLOG2, llvm::ISD::FLT_ROUNDS_, llvm::ISD::FMA, llvm::ISD::FMUL, llvm::ISD::FNEARBYINT, llvm::ISD::FNEG, llvm::ISD::FP16_TO_FP32, llvm::ISD::FP32_TO_FP16, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_ROUND_INREG, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FPOW, llvm::ISD::FPOWI, llvm::ISD::FRAME_TO_ARGS_OFFSET, llvm::ISD::FRAMEADDR, llvm::ISD::FrameIndex, llvm::ISD::FREM, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::ISD::FSIN, llvm::ISD::FSINCOS, llvm::ISD::FSQRT, llvm::ISD::FSUB, llvm::ISD::FTRUNC, llvm::TargetMachine::getInstrInfo(), llvm::TargetMachine::getIntrinsicInfo(), getMachineOpcode(), llvm::Intrinsic::getName(), getOpcode(), getOperand(), llvm::SelectionDAG::getTarget(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::TargetLowering::getTargetNodeName(), llvm::ISD::GLOBAL_OFFSET_TABLE, llvm::ISD::GlobalAddress, llvm::ISD::GlobalTLSAddress, llvm::ISD::HANDLENODE, llvm::ISD::INIT_TRAMPOLINE, llvm::ISD::INLINEASM, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, isMachineOpcode(), llvm::ISD::JumpTable, llvm::ISD::LIFETIME_END, llvm::ISD::LIFETIME_START, llvm_unreachable, llvm::ISD::LOAD, llvm::ISD::MDNODE_SDNODE, llvm::ISD::MERGE_VALUES, llvm::ISD::MUL, llvm::ISD::MULHS, llvm::ISD::MULHU, llvm::Intrinsic::num_intrinsics, llvm::ISD::OR, llvm::ISD::PCMARKER, llvm::ISD::PREFETCH, llvm::ISD::READCYCLECOUNTER, llvm::ISD::Register, llvm::ISD::RegisterMask, llvm::ISD::RETURNADDR, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SADDO, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SDIV, llvm::ISD::SDIVREM, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::ISD::SETEQ, llvm::ISD::SETFALSE, llvm::ISD::SETFALSE2, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETTRUE, llvm::ISD::SETTRUE2, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, llvm::ISD::SETUO, llvm::ISD::SHL, llvm::ISD::SHL_PARTS, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SINT_TO_FP, llvm::ISD::SMUL_LOHI, llvm::ISD::SMULO, llvm::ISD::SRA, llvm::ISD::SRA_PARTS, llvm::ISD::SRCVALUE, llvm::ISD::SREM, llvm::ISD::SRL, llvm::ISD::SRL_PARTS, llvm::ISD::SSUBO, llvm::ISD::STACKRESTORE, llvm::ISD::STACKSAVE, llvm::ISD::STORE, llvm::ISD::SUB, llvm::ISD::SUBC, llvm::ISD::SUBE, llvm::ISD::TargetBlockAddress, llvm::ISD::TargetConstant, llvm::ISD::TargetConstantFP, llvm::ISD::TargetConstantPool, llvm::ISD::TargetExternalSymbol, llvm::ISD::TargetFrameIndex, llvm::ISD::TargetGlobalAddress, llvm::ISD::TargetGlobalTLSAddress, llvm::ISD::TargetIndex, llvm::ISD::TargetJumpTable, TII, llvm::ISD::TokenFactor, llvm::ISD::TRAP, llvm::ISD::TRUNCATE, llvm::ISD::UADDO, llvm::ISD::UDIV, llvm::ISD::UDIVREM, llvm::ISD::UINT_TO_FP, llvm::ISD::UMUL_LOHI, llvm::ISD::UMULO, llvm::ISD::UNDEF, llvm::ISD::UREM, llvm::ISD::USUBO, llvm::utostr(), llvm::ISD::VAARG, llvm::ISD::VACOPY, llvm::ISD::VAEND, llvm::ISD::VALUETYPE, llvm::ISD::VASTART, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::VSELECT, llvm::ISD::XOR, and llvm::ISD::ZERO_EXTEND.
Referenced by llvm::DOTGraphTraits< SelectionDAG * >::getSimpleNodeLabel(), and print_types().
static SDVTList llvm::SDNode::getSDVTList (EVT VT) inline static protected
Definition at line 696 of file SelectionDAGNodes.h.
References llvm::AArch64ISD::Ret.
MVT llvm::SDNode::getSimpleValueType (unsigned ResNo) const inline
Return the type of a specified result as a simple type.
Definition at line 616 of file SelectionDAGNodes.h.
Referenced by llvm::ScheduleDAGSDNodes::RegDefIter::Advance(), CalcNodeSethiUllmanNumber(), CommuteVectorShuffle(), Compact8x32ShuffleNode(), countOperands(), ExpandUnalignedLoad(), ExtractBitFromMaskVector(), getCodeAddrSpace(), getFusedLdStOpcode(), getInsertVINSERTImmediate(), getShufflePALIGNRImmediate(), getShufflePSHUFHWImmediate(), getShufflePSHUFLWImmediate(), getShuffleSHUFImmediate(), getShuffleVPERM2X128Immediate(), isCalleeLoad(), isDivRemLibcallAvailable(), isSinCosLibcallAvailable(), isVectorShift(), isVectorShiftLeft(), isVectorShiftRight(), isVEXTRACTIndex(), isVINSERTIndex(), LowerAVXExtend(), LowerINSERT_SUBVECTOR(), LowerSIGN_EXTEND(), LowerSIGN_EXTEND_AVX512(), LowerVECTOR_SHUFFLE_128v4(), LowerVECTOR_SHUFFLE_256(), LowerVECTOR_SHUFFLEtoBlend(), LowerVECTOR_SHUFFLEv32i8(), PerformVCVTCombine(), PerformVDIVCombine(), PromoteSplat(), llvm::ResourcePriorityQueue::rawRegPressureDelta(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), RewriteAsNarrowerShuffle(), llvm::ResourcePriorityQueue::scheduledNode(), useDivRem(), and useSinCos().
unsigned llvm::SDNode::getValueSizeInBits (unsigned ResNo) const inline
getValueSizeInBits - Returns MVT::getSizeInBits(getValueType(ResNo)).
Definition at line 622 of file SelectionDAGNodes.h.
Referenced by BuildVectorFromScalar(), canFoldInAddressingMode(), and isSlicingProfitable().
EVT llvm::SDNode::getValueType (unsigned ResNo) const inline
getValueType - Return the type of a specified result.
Definition at line 609 of file SelectionDAGNodes.h.
Referenced by AddCombineTo64bitMLAL(), AddCombineToVPADDL(), AddGlue(), AddNodeIDCustom(), llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), BuildVectorFromScalar(), canClobberPhysRegDefs(), canFoldInAddressingMode(), CanFoldXORWithAllOnes(), CheckForPhysRegDependency(), CombineBaseUpdate(), combineSelectAndUse(), CombineVLDDUP(), llvm::InstrEmitter::CountResults(), llvm::createAMDGPUISelDag(), createLoadLR(), llvm::SelectionDAG::DeleteNode(), doNotCSE(), llvm::InstrEmitter::EmitDbgValue(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), Expand64BitShift(), ExpandBITCAST(), ExpandUnalignedLoad(), ExtendUsesToFormExtLoad(), findGluedUser(), findUser(), llvm::SelectionDAG::FoldConstantArithmetic(), FoldOperand(), getARMIndexedAddressParts(), getBuildPairElt(), getCodeAddrSpace(), getCTPOP16BitCounts(), GetFPLibCall(), getPhysicalRegisterVT(), llvm::ARMTargetLowering::getSchedulingPreference(), getT2IndexedAddressParts(), GetTLSADDR(), GetVBR(), getVCmpEQInst(), getVLDSTRegisterUpdateOpcode(), HandleMergeInputChains(), hasNormalLoadOperand(), isADDADDMUL(), isBSwapHWordElement(), llvm::ISD::isBuildVectorAllOnes(), isConditionalZeroOrAllOnes(), llvm::SelectionDAG::isConsecutiveLoad(), isConstantOrUndefBUILD_VECTOR(), llvm::BuildVectorSDNode::isConstantSplat(), isConstantSplatVector(), isExtendedBUILD_VECTOR(), isInt32Immediate(), isInt64Immediate(), isIntS16Immediate(), llvm::SelectionDAGISel::IsLegalToFold(), isOneUseSetCC(), isOpcWithIntImmediate(), isOperandOf(), isSequentialInRange(), isShuffleHigh128VectorInsertLow(), isShuffleLow128VectorInsertHigh(), isSlicingProfitable(), llvm::PPC::isSplatShuffleMask(), isSplatVector(), isTruncateOf(), isValidIndexedLoad(), isVMerge(), llvm::PPC::isVSLDOIShuffleMask(), isWordAligned(), isXor1OfSetCC(), isZeroShuffle(), LowerADDC_ADDE_SUBC_SUBE(), llvm::ARMTargetLowering::LowerAsmOperandForConstraint(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), llvm::NVPTXTargetLowering::LowerCall(), LowerCTPOP(), lowerCTPOP16BitElements(), lowerCTPOP32BitElements(), LowerCTTZ(), lowerDSPIntr(), LowerDYNAMIC_STACKALLOC(), LowerEXTRACT_VECTOR_ELT_SSE4(), LowerINTRINSIC_W_CHAIN(), LowerLabelRef(), LowerLOAD_SUB(), lowerMSABinaryBitImmIntr(), lowerMSABitClear(), lowerMSABitClearImm(), lowerMSACopyIntr(), lowerMSALoadIntr(), lowerMSASplatImm(), lowerMSASplatZExt(), lowerMSAStoreIntr(), llvm::NVPTXTargetLowering::LowerOperation(), llvm::HexagonTargetLowering::LowerSELECT_CC(), LowerShift(), llvm::MipsTargetLowering::lowerSTORE(), LowerToTLSExecModel(), LowerToTLSLocalDynamicModel(), LowerVAARG(), lowerVECTOR_SHUFFLE_VSHF(), LowerXALUO(), LowerZERO_EXTEND_AVX512(), maskMatters(), MatchRotateHalf(), OffsetFitsS11(), ConsecutiveMemoryChainSorter::operator()(), partitionShuffleOfConcats(), PerformADCCombine(), performADDCombine(), PerformAddCombine(), performADDECombine(), performANDCombine(), PerformANDCombine(), PerformAndCombine(), PerformARMBUILD_VECTORCombine(), PerformBFICombine(), PerformBUILD_VECTORCombine(), llvm::ARMTargetLowering::PerformCMOVCombine(), PerformCMOVCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::SITargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performDivRemCombine(), PerformExtendCombine(), PerformEXTRACT_VECTOR_ELTCombine(), PerformFADDCombine(), PerformFMACombine(), PerformFMinFMaxCombine(), PerformFSUBCombine(), PerformInsertEltCombine(), performIntegerAbsCombine(), PerformIntrinsicCombine(), PerformISDSETCCCombine(), PerformLOADCombine(), performMULCombine(), PerformMULCombine(), PerformMulCombine(), performORCombine(), PerformORCombine(), PerformOrCombine(), PerformSELECT_CCCombine(), PerformSELECTCombine(), performSETCCCombine(), PerformSExtCombine(), PerformShiftCombine(), performShiftToAllZeros(), performSHLCombine(), PerformShuffleCombine(), PerformShuffleCombine256(), PerformSIGN_EXTEND_INREGCombine(), PerformSINT_TO_FPCombine(), performSRACombine(), PerformSRACombine(), performSRLCombine(), PerformSubCombine(), performSUBECombine(), PerformVCVTCombine(), PerformVDIVCombine(), PerformVDUPLANECombine(), PerformVECTOR_SHUFFLECombine(), PerformVMOVDRRCombine(), PerformVMOVRRDCombine(), PerformVMULCombine(), performVSELECTCombine(), PerformVZEXT_MOVLCombine(), performVZEXTCombine(), performXORCombine(), PerformXORCombine(), PerformXorCombine(), PerformZExtCombine(), print_types(), RemoveUnusedGlue(), llvm::SelectionDAG::ReplaceAllUsesWith(), ReplaceATOMIC_BINARY_64(), ReplaceATOMIC_OP_64(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::SparcTargetLowering::ReplaceNodeResults(), llvm::PPCTargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::DAGTypeLegalizer::run(), llvm::PPCTargetLowering::SelectAddressRegImm(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::X86InstrInfo::shouldScheduleLoadsNear(), SkipExtensionForVMULL(), SplitVSETCC(), tryCombineToBFI(), tryCombineToEXTR(), tryCombineToLargerBFI(), llvm::X86InstrInfo::unfoldMemoryOperand(), llvm::SelectionDAG::UnrollVectorOp(), useDivRem(), useSinCos(), VerifyNodeCommon(), WidenMaskArithmetic(), and XFormVExtractWithShuffleIntoLoad().
SDVTList llvm::SDNode::getVTList () const inline
Definition at line 563 of file SelectionDAGNodes.h.
References llvm::X.
Referenced by AddNodeIDNode(), llvm::SITargetLowering::AdjustInstrPostInstrSelection(), combineShlAddConstant(), llvm::createAMDGPUISelDag(), llvm::SelectionDAG::DeleteNode(), ExpandUnalignedLoad(), findUser(), FoldOperand(), getCodeAddrSpace(), isConstantSplatVector(), isNodeChanged(), isOneUseSetCC(), lowerGR128Binary(), LowerINTRINSIC_W_CHAIN(), llvm::SITargetLowering::LowerOperation(), LowerXALUO(), maskMatters(), performANDCombine(), PerformBrCondCombine(), PerformCMOVCombine(), llvm::R600TargetLowering::PerformDAGCombine(), PerformSETCCCombine(), performSRACombine(), llvm::R600TargetLowering::ReplaceNodeResults(), and tryFoldToZero().
bool SDNode::hasAnyUseOfValue (unsigned Value) const
hasAnyUseOfValue - Return true if there are any use of the indicated value. This method ignores uses of other values defined by this operation.
Definition at line 6138 of file SelectionDAG.cpp.
References getNumValues(), use_begin(), and use_end().
Referenced by llvm::ARMTargetLowering::AdjustInstrPostInstrSelection(), llvm::ScheduleDAGSDNodes::RegDefIter::Advance(), CalcNodeSethiUllmanNumber(), canClobberPhysRegDefs(), canFoldInAddressingMode(), checkBoolTestSetCCCombine(), combineShlAddConstant(), EltsFromConsecutiveLoads(), llvm::InstrEmitter::EmitDbgValue(), findGluedUser(), getAtomicLoadArithTargetConstant(), getFusedLdStOpcode(), isConstantSplatVector(), partitionShuffleOfConcats(), performDivRemCombine(), RemoveUnusedGlue(), llvm::SelectionDAG::ReplaceAllUsesWith(), and tryFoldToZero().
bool SDNode::hasNUsesOfValue (unsigned NUses, unsigned Value) const
hasNUsesOfValue - Return true if there are exactly NUSES uses of the indicated value. This method ignores uses of other values defined by this operation.
Definition at line 6119 of file SelectionDAG.cpp.
References getNumValues(), use_begin(), and use_end().
Referenced by llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), isLoadIncOrDecStore(), llvm::X86TargetLowering::isNoopAddrSpaceCast(), LowerInterruptReturn(), LowerVectorBroadcast(), ConsecutiveMemoryChainSorter::operator()(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformSTORECombine(), and XFormVExtractWithShuffleIntoLoad().
bool llvm::SDNode::hasOneUse () const inline
hasOneUse - Return true if there is exactly one use of this node.
Definition at line 406 of file SelectionDAGNodes.h.
References llvm::next().
Referenced by canChangeToInt(), canFoldInAddressingMode(), combineSelectAndUseCommutative(), combineShlAddConstant(), countOperands(), llvm::SelectionDAG::dump(), DumpNodes(), FoldMaskAndShiftToScale(), getBuildPairElt(), getFusedLdStOpcode(), getVCmpEQInst(), getVLDSTRegisterUpdateOpcode(), isAddSubSExt(), isAddSubZExt(), isBSwapHWordElement(), isConstantSplatVector(), isOneUseSetCC(), isScaledConstantInRange(), isSlicingProfitable(), isTruncateOf(), isTruncWithZeroHighBitsInput(), isValidIndexedLoad(), isXor1OfSetCC(), LowerInterruptReturn(), LowerVectorAllZeroTest(), MatchRotateHalf(), OffsetFitsS11(), ConsecutiveMemoryChainSorter::operator()(), PerformADDCombineWithOperands(), PerformARMBUILD_VECTORCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformEXTRACT_VECTOR_ELTCombine(), PerformMulCombine(), PerformSTORECombine(), PerformSUBCombine(), PerformSubCombine(), PerformVMOVRRDCombine(), shouldUseLA(), llvm::TargetLowering::TargetLoweringOpt::ShrinkDemandedOp(), llvm::TargetLowering::SimplifyDemandedBits(), and llvm::TargetLowering::SimplifySetCC().
bool SDNode::hasPredecessor (const SDNode * N) const
hasPredecessor - Return true if N is a predecessor of this node. N is either an operand of this node, or can be reached by recursively traversing up the operands. NOTE: This is an expensive method. Use it carefully.
Definition at line 6214 of file SelectionDAG.cpp.
References hasPredecessorHelper().
Referenced by isPredecessorOf().
bool SDNode::hasPredecessorHelper (const SDNode * N, SmallPtrSet< const SDNode *, 32 > & Visited, SmallVectorImpl< const SDNode * > & Worklist) const
hasPredecesorHelper - Return true if N is a predecessor of this node. N is either an operand of this node, or can be reached by recursively traversing up the operands. In this helper the Visited and worklist sets are held externally to cache predecessors over multiple invocations. If you want to test for multiple predecessors this method is preferable to multiple calls to hasPredecessor. Be sure to clear Visited and Worklist if the DAG changes. NOTE: This is still very expensive. Use carefully.
Definition at line 6221 of file SelectionDAG.cpp.
References llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::SmallVectorBase::empty(), llvm::SmallPtrSetImpl::empty(), llvm::SDValue::getNode(), getNumOperands(), getOperand(), i, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), M, llvm::SmallVectorImpl< T >::pop_back_val(), and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by canFoldInAddressingMode(), and hasPredecessor().
void llvm::SDNode::InitOperands (SDUse * Ops, const SDValue & Op0) inline protected
InitOperands - Initialize the operands list of this with 1 operand.
Definition at line 725 of file SelectionDAGNodes.h.
References llvm::checkForCycles().
Referenced by llvm::SelectionDAG::getMachineNode(), and llvm::SelectionDAG::MorphNodeTo().
void llvm::SDNode::InitOperands (SDUse * Ops, const SDValue & Op0, const SDValue & Op1) inline protected
InitOperands - Initialize the operands list of this with 2 operands.
Definition at line 734 of file SelectionDAGNodes.h.
References llvm::checkForCycles().
void llvm::SDNode::InitOperands (SDUse * Ops, const SDValue & Op0, const SDValue & Op1, const SDValue & Op2) inline protected
InitOperands - Initialize the operands list of this with 3 operands.
Definition at line 745 of file SelectionDAGNodes.h.
References llvm::checkForCycles().
void llvm::SDNode::InitOperands (SDUse * Ops, const SDValue & Op0, const SDValue & Op1, const SDValue & Op2, const SDValue & Op3) inline protected
InitOperands - Initialize the operands list of this with 4 operands.
Definition at line 759 of file SelectionDAGNodes.h.
References llvm::checkForCycles().
void llvm::SDNode::InitOperands (SDUse * Ops, const SDValue * Vals, unsigned N) inline protected
InitOperands - Initialize the operands list of this with N operands.
Definition at line 775 of file SelectionDAGNodes.h.
References llvm::checkForCycles(), i, and N.
bool llvm::SDNode::isMachineOpcode () const inline
isMachineOpcode - Test if this node has a post-isel opcode, directly corresponding to a MachineInstr opcode.
Definition at line 384 of file SelectionDAGNodes.h.
Referenced by llvm::SITargetLowering::analyzeImmediate(), llvm::ARMBaseInstrInfo::areLoadsFromSameBasePtr(), llvm::X86InstrInfo::areLoadsFromSameBasePtr(), llvm::ScheduleDAGSDNodes::BuildSchedGraph(), CalcNodeSethiUllmanNumber(), canClobberPhysRegDefs(), CheckForLiveRegDef(), CheckForPhysRegDependency(), llvm::MachineSDNode::classof(), llvm::ScheduleDAG::clearDAG(), llvm::ScheduleDAGSDNodes::computeLatency(), llvm::ScheduleDAGSDNodes::computeOperandLatency(), countOperands(), llvm::createAMDGPUISelDag(), llvm::createNVPTXISelDag(), llvm::SelectionDAG::DeleteNode(), llvm::InstrEmitter::EmitNode(), FindCallSeqStart(), findGluedUser(), FoldOperand(), GetCostForDef(), getFusedLdStOpcode(), llvm::MipsDAGToDAGISel::getGlobalBaseReg(), getGluedMachineNode(), llvm::TargetInstrInfo::getInstrLatency(), llvm::ARMBaseInstrInfo::getOperandLatency(), llvm::TargetInstrInfo::getOperandLatency(), getOperationName(), llvm::ARMTargetLowering::getSchedulingPreference(), getVCmpEQInst(), getVLDSTRegisterUpdateOpcode(), IsChainDependent(), llvm::ResourcePriorityQueue::isResourceAvailable(), isScaledConstantInRange(), isValidIndexedLoad(), maskMatters(), llvm::ScheduleDAGSDNodes::newSUnit(), OffsetFitsS11(), llvm::ResourcePriorityQueue::rawRegPressureDelta(), llvm::ResourcePriorityQueue::regPressureDelta(), RemoveUnusedGlue(), llvm::ResourcePriorityQueue::reserveResources(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), llvm::ResourcePriorityQueue::scheduledNode(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::X86InstrInfo::unfoldMemoryOperand(), and WalkChainUsers().
bool SDNode::isOnlyUserOf (SDNode * N) const
isOnlyUserOf - Return true if this node is the only use of N.
Definition at line 6151 of file SelectionDAG.cpp.
References I, use_begin(), and use_end().
Referenced by buildFromShuffleMostly().
bool SDNode::isOperandOf (SDNode * N) const
isOperandOf - Return true if this node is an operand of N.
Definition at line 6173 of file SelectionDAG.cpp.
References llvm::SDUse::getNode(), and i.
bool llvm::SDNode::isPredecessorOf (const SDNode * N) const inline
isPredecessorOf - Return true if this node is a predecessor of N. NOTE: Implemented on top of hasPredecessor and every bit as expensive. Use carefully.
Definition at line 523 of file SelectionDAGNodes.h.
References hasPredecessor().
Referenced by canFoldInAddressingMode(), CombineBaseUpdate(), llvm::PPCTargetLowering::getPreIndexedAddressParts(), and partitionShuffleOfConcats().
bool llvm::SDNode::isTargetMemoryOpcode () const inline
isTargetMemoryOpcode - Test if this node has a target-specific memory-referencing opcode (in the <target>ISD namespace and greater than FIRST_TARGET_MEMORY_OPCODE).
Definition at line 378 of file SelectionDAGNodes.h.
References llvm::ISD::FIRST_TARGET_MEMORY_OPCODE.
Referenced by AddNodeIDCustom(), llvm::MemSDNode::classof(), and llvm::MemIntrinsicSDNode::classof().
bool llvm::SDNode::isTargetOpcode () const inline
isTargetOpcode - Test if this node has a target-specific opcode (in the <target>ISD namespace).
Definition at line 373 of file SelectionDAGNodes.h.
References llvm::ISD::BUILTIN_OP_END.
op_iterator llvm::SDNode::op_begin () const inline
Definition at line 560 of file SelectionDAGNodes.h.
Referenced by AddNodeIDNode(), ExtractSubVector(), findConsecutiveLoad(), FoldOperand(), llvm::SelectionDAG::getNode(), getVLDSTRegisterUpdateOpcode(), isConstantSplatVector(), llvm::SelectionDAGISel::IsLegalToFold(), LowerINTRINSIC_WO_CHAIN(), llvm::SelectionDAG::MorphNodeTo(), ConsecutiveMemoryChainSorter::operator()(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::SelectionDAG::RemoveDeadNodes(), llvm::DAGTypeLegalizer::run(), and VerifyNodeCommon().
op_iterator llvm::SDNode::op_end () const inline
Definition at line 561 of file SelectionDAGNodes.h.
Referenced by findConsecutiveLoad(), FoldOperand(), llvm::SelectionDAG::getNode(), getVLDSTRegisterUpdateOpcode(), llvm::SelectionDAGISel::IsLegalToFold(), LowerINTRINSIC_WO_CHAIN(), llvm::SelectionDAG::MorphNodeTo(), ConsecutiveMemoryChainSorter::operator()(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::SelectionDAG::RemoveDeadNodes(), and VerifyNodeCommon().
void SDNode::print (raw_ostream & OS, const SelectionDAG * G = 0) const
Definition at line 642 of file SelectionDAGDumper.cpp.
References llvm::SDValue::getNode(), getNumOperands(), getOperand(), i, print_details(), print_types(), and llvm::NVPTX::PTXCvtMode::RN.
Referenced by dump(), and printrWithDepthHelper().
void SDNode::print_details (raw_ostream & OS, const SelectionDAG * G) const
Definition at line 347 of file SelectionDAGDumper.cpp.
References i, llvm::APFloat::IEEEdouble, llvm::APFloat::IEEEsingle, llvm::next(), s, and llvm::WriteAsOperand().
Referenced by llvm::DOTGraphTraits< SelectionDAG * >::getSimpleNodeLabel(), print(), and printr().
void SDNode::print_types (raw_ostream & OS, const SelectionDAG * G) const
Definition at line 334 of file SelectionDAGDumper.cpp.
References llvm::EVT::getEVTString(), getNumValues(), getOperationName(), getValueType(), i, and llvm::MVT::Other.
Referenced by print(), and printr().
void SDNode::printr (raw_ostream & OS, const SelectionDAG * G = 0) const
Definition at line 549 of file SelectionDAGDumper.cpp.
References print_details(), and print_types().
Referenced by DumpNodesr().
void SDNode::printrFull (raw_ostream & O, const SelectionDAG * G = 0) const
printrFull - Print a SelectionDAG node and all children down to the leaves. The given SelectionDAG allows target-specific nodes to be printed in human-readable form. Unlike printr, this will print the whole DAG, including children that appear multiple times.
Definition at line 628 of file SelectionDAGDumper.cpp.
References printrWithDepth().
Referenced by llvm::SelectionDAGISel::SelectCodeCommon().
void SDNode::printrWithDepth (raw_ostream & O, const SelectionDAG * G = 0, unsigned depth = 100) const
printrWithDepth - Print a SelectionDAG node and children up to depth "depth." The given SelectionDAG allows target-specific nodes to be printed in human-readable form. Unlike printr, this will print children that appear multiple times wherever they are used.
Definition at line 623 of file SelectionDAGDumper.cpp.
References printrWithDepthHelper().
Referenced by dumprWithDepth(), llvm::MipsSETargetLowering::PerformDAGCombine(), and printrFull().
void SDNode::Profile (FoldingSetNodeID & ID) const
Profile - Gather unique data for the node.
Definition at line 6083 of file SelectionDAG.cpp.
References AddNodeIDNode(), i, and llvm::MVT::LAST_VALUETYPE.
void llvm::SDNode::setDebugLoc (const DebugLoc dl) inline
setDebugLoc - Set source location info. Try to avoid this, putting it in the constructor is preferable.
Definition at line 435 of file SelectionDAGNodes.h.
Referenced by llvm::SelectionDAG::SelectNodeTo().
void llvm::SDNode::setHasDebugValue (bool b) inline
setHasDebugValue - set this bit.
Definition at line 398 of file SelectionDAGNodes.h.
References b.
Referenced by llvm::SelectionDAG::AddDbgValue().
void llvm::SDNode::setIROrder (unsigned Order) inline
setIROrder - Set the node ordering.
Definition at line 428 of file SelectionDAGNodes.h.
Referenced by llvm::NVPTXTargetLowering::LowerFormalArguments(), and llvm::SelectionDAG::SelectNodeTo().
void llvm::SDNode::setNodeId (int Id) inline
setNodeId - Set unique node id.
Definition at line 420 of file SelectionDAGNodes.h.
References llvm::tgtok::Id.
Referenced by llvm::SelectionDAG::AssignTopologicalOrder(), CheckForLiveRegDef(), llvm::createAMDGPUISelDag(), llvm::createNVPTXISelDag(), findGluedUser(), getFusedLdStOpcode(), llvm::MipsDAGToDAGISel::getGlobalBaseReg(), getVCmpEQInst(), getVLDSTRegisterUpdateOpcode(), HandleMergeInputChains(), insertDAGNode(), InsertDAGNode(), llvm::SelectionDAGISel::IsLegalToFold(), isOperandOf(), isValidIndexedLoad(), maskMatters(), OffsetFitsS11(), RemoveUnusedGlue(), llvm::DAGTypeLegalizer::run(), llvm::SelectionDAGISel::SelectCodeCommon(), and llvm::SelectionDAG::SelectNodeTo().
use_iterator llvm::SDNode::use_begin () const inline
use_begin/use_end - Provide iteration support to walk over all uses of an SDNode.
Definition at line 496 of file SelectionDAGNodes.h.
Referenced by llvm::AArch64TargetLowering::addTokenForArgument(), llvm::SelectionDAG::AssignTopologicalOrder(), canFoldInAddressingMode(), CMPEQCombine(), CombineBaseUpdate(), CombineVLDDUP(), countOperands(), llvm::createAMDGPUISelDag(), ExtendUsesToFormExtLoad(), findConsecutiveLoad(), findGluedUser(), findGlueUse(), findUser(), getBuildPairElt(), hasAnyUseOfValue(), HasNoSignedComparisonUses(), hasNUsesOfValue(), llvm::X86TargetLowering::IsDesirableToPromoteOp(), isLoadIncOrDecStore(), llvm::X86TargetLowering::isNoopAddrSpaceCast(), isOnlyUserOf(), isScaledConstantInRange(), isSlicingProfitable(), isXor1OfSetCC(), LowerEXTRACT_VECTOR_ELT_SSE4(), LowerInterruptReturn(), LowerVectorAllZeroTest(), MatchRotateHalf(), MayFoldIntoStore(), OffsetFitsS11(), ConsecutiveMemoryChainSorter::operator()(), PerformARMBUILD_VECTORCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformEXTRACT_VECTOR_ELTCombine(), PerformMulCombine(), PerformSELECTCombine(), RemoveUnusedGlue(), llvm::SelectionDAG::ReplaceAllUsesOfValuesWith(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::DAGTypeLegalizer::run(), SubIdx2Lane(), useDivRem(), useSinCos(), and WalkChainUsers().
bool llvm::SDNode::use_empty () const inline
use_empty - Return true if there are no uses of this node.
Definition at line 402 of file SelectionDAGNodes.h.
Referenced by canFoldInAddressingMode(), llvm::SelectionDAG::DeleteNode(), getInputChainForNode(), GetVBR(), getVCmpEQInst(), isOneUseSetCC(), llvm::SelectionDAG::MorphNodeTo(), ConsecutiveMemoryChainSorter::operator()(), llvm::SelectionDAG::RemoveDeadNodes(), llvm::SelectionDAGISel::runOnMachineFunction(), and llvm::SelectionDAGISel::SelectCodeCommon().
static use_iterator llvm::SDNode::use_end () inline static
Definition at line 500 of file SelectionDAGNodes.h.
References isOperandOf(), and N.
Referenced by llvm::AArch64TargetLowering::addTokenForArgument(), llvm::SelectionDAG::AssignTopologicalOrder(), canFoldInAddressingMode(), CMPEQCombine(), CombineBaseUpdate(), CombineVLDDUP(), countOperands(), llvm::createAMDGPUISelDag(), ExtendUsesToFormExtLoad(), findConsecutiveLoad(), findGluedUser(), findGlueUse(), findUser(), hasAnyUseOfValue(), HasNoSignedComparisonUses(), hasNUsesOfValue(), llvm::X86TargetLowering::IsDesirableToPromoteOp(), isLoadIncOrDecStore(), llvm::X86TargetLowering::isNoopAddrSpaceCast(), isOnlyUserOf(), isSlicingProfitable(), LowerInterruptReturn(), LowerVectorAllZeroTest(), OffsetFitsS11(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformEXTRACT_VECTOR_ELTCombine(), PerformSELECTCombine(), RemoveUnusedGlue(), llvm::SelectionDAG::ReplaceAllUsesOfValuesWith(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::DAGTypeLegalizer::run(), SubIdx2Lane(), useDivRem(), useSinCos(), and WalkChainUsers().
size_t llvm::SDNode::use_size () const inline
use_size - Return the number of uses of this node. This method takes time proportional to the number of uses.
Definition at line 413 of file SelectionDAGNodes.h.
Referenced by findGluedUser().
value_iterator llvm::SDNode::value_begin () const inline
Definition at line 627 of file SelectionDAGNodes.h.
Referenced by lowerDSPIntr().
value_iterator llvm::SDNode::value_end () const inline
Definition at line 628 of file SelectionDAGNodes.h.
References llvm::dump(), and G.
Referenced by lowerDSPIntr().
Friends And Related Function Documentation
friend struct ilist_traits< SDNode > friend
Definition at line 358 of file SelectionDAGNodes.h.
friend class SelectionDAG friend
Definition at line 357 of file SelectionDAGNodes.h.
Member Data Documentation
uint16_t llvm::SDNode::SubclassData protected
SubclassData - This member is defined by this class, but is not used for anything. Subclasses can use it to hold whatever state they find useful. This field is initialized to zero by the ctor.
Definition at line 324 of file SelectionDAGNodes.h.
Referenced by llvm::MemSDNode::MemSDNode().
The documentation for this class was generated from the following files:
SelectionDAGNodes.h
SelectionDAG.cpp
SelectionDAGDumper.cpp