LLVM: llvm::object::Binary Class Reference
LLVM API Documentation
llvm::object::Binary Class Reference
#include <Binary.h>
Public Member Functions
virtual ~Binary ()
StringRef getData () const
StringRef getFileName () const
unsigned int getType () const
bool isObject () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isLittleEndian () const
Protected Types
enum {
ID_Archive, ID_MachOUniversalBinary, ID_StartObjects, ID_COFF,
ID_ELF32L, ID_ELF32B, ID_ELF64L, ID_ELF64B,
ID_MachO32L, ID_MachO32B, ID_MachO64L, ID_MachO64B,
ID_EndObjects
}
Protected Member Functions
Binary (unsigned int Type, MemoryBuffer *Source)
Static Protected Member Functions
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes
MemoryBuffer * Data
Detailed Description
Definition at line 27 of file Binary.h.
Member Enumeration Documentation
anonymous enum protected
Enumerator
ID_Archive
ID_MachOUniversalBinary
ID_StartObjects
ID_COFF
ID_ELF32L
ID_ELF32B
ID_ELF64L
ID_ELF64B
ID_MachO32L
ID_MachO32B
ID_MachO64L
ID_MachO64B
ID_EndObjects
Definition at line 39 of file Binary.h.
Constructor & Destructor Documentation
Binary::Binary (unsigned int Type, MemoryBuffer * Source) protected
Definition at line 33 of file Binary.cpp.
Binary::~Binary () virtual
Definition at line 29 of file Binary.cpp.
References Data.
Referenced by getMachOType().
Member Function Documentation
StringRef Binary::getData () const
Definition at line 37 of file Binary.cpp.
References Data, and llvm::MemoryBuffer::getBuffer().
Referenced by llvm::object::MachOUniversalBinary::ObjectForArch::getAsObjectFile(), llvm::ObjectImageCommon::getData(), getMachOType(), llvm::object::getPtr(), llvm::object::MachOObjectFile::getSectionContents(), llvm::object::MachOObjectFile::getStringTableData(), llvm::object::MachOUniversalBinary::MachOUniversalBinary(), llvm::object::MachOUniversalBinary::ObjectForArch::ObjectForArch(), and llvm::object::MachOObjectFile::ReadULEB128s().
static unsigned int llvm::object::Binary::getELFType (bool isLE, bool is64Bits) inline static protected
Definition at line 59 of file Binary.h.
References ID_ELF32B, ID_ELF32L, ID_ELF64B, and ID_ELF64L.
Referenced by llvm::object::ELFObjectFile< ELFT >::classof().
StringRef Binary::getFileName () const
Definition at line 41 of file Binary.cpp.
References Data, and llvm::MemoryBuffer::getBufferIdentifier().
Referenced by llvm::object::MachOUniversalBinary::ObjectForArch::getAsObjectFile(), getMachOType(), and llvm::object::Archive::Child::getMemoryBuffer().
static unsigned int llvm::object::Binary::getMachOType (bool isLE, bool is64Bits) inline static protected
Definition at line 66 of file Binary.h.
References getData(), getFileName(), ID_MachO32B, ID_MachO32L, ID_MachO64B, ID_MachO64L, and ~Binary().
Referenced by llvm::object::MachOObjectFile::is64Bit().
unsigned int llvm::object::Binary::getType () const inline
Definition at line 80 of file Binary.h.
Referenced by llvm::object::ELFObjectFile< ELFT >::classof(), and llvm::object::MachOObjectFile::is64Bit().
bool llvm::object::Binary::isArchive () const inline
Definition at line 87 of file Binary.h.
References ID_Archive.
Referenced by llvm::object::Archive::classof().
bool llvm::object::Binary::isCOFF () const inline
Definition at line 103 of file Binary.h.
References ID_COFF.
Referenced by llvm::object::COFFObjectFile::classof().
bool llvm::object::Binary::isELF () const inline
Definition at line 95 of file Binary.h.
References ID_ELF32L, and ID_ELF64B.
Referenced by llvm::DWARFContextInMemory::DWARFContextInMemory(), and llvm::MCObjectSymbolizer::findRelocationAt().
bool llvm::object::Binary::isLittleEndian () const inline
Definition at line 107 of file Binary.h.
References llvm::object::createBinary(), ID_ELF32B, ID_ELF64B, ID_MachO32B, ID_MachO64B, and llvm::Sched::Source.
Referenced by llvm::object::MachOObjectFile::getPlainRelocationExternal(), llvm::object::getPlainRelocationLength(), llvm::object::getPlainRelocationPCRel(), llvm::object::MachOObjectFile::getPlainRelocationSymbolNum(), llvm::object::getPlainRelocationType(), llvm::object::getStruct(), and llvm::RuntimeDyldImpl::loadObject().
bool llvm::object::Binary::isMachO () const inline
Definition at line 99 of file Binary.h.
References ID_MachO32L, and ID_MachO64B.
Referenced by llvm::object::MachOObjectFile::classof().
bool llvm::object::Binary::isMachOUniversalBinary () const inline
Definition at line 91 of file Binary.h.
References ID_MachOUniversalBinary.
Referenced by llvm::object::MachOUniversalBinary::classof().
bool llvm::object::Binary::isObject () const inline
Definition at line 83 of file Binary.h.
References ID_EndObjects, and ID_StartObjects.
Referenced by llvm::object::ObjectFile::classof().
Member Data Documentation
MemoryBuffer* llvm::object::Binary::Data protected
Definition at line 35 of file Binary.h.
Referenced by llvm::object::Archive::begin_children(), llvm::object::COFFObjectFile::COFFObjectFile(), getData(), getFileName(), llvm::object::Archive::Child::getNext(), llvm::object::COFFObjectFile::getSymbolAuxData(), llvm::object::COFFObjectFile::section_rel_end(), and ~Binary().
The documentation for this class was generated from the following files:
Binary.h
Binary.cpp