LLVM: llvm::MCDwarfLoc Class Reference
LLVM API Documentation
llvm::MCDwarfLoc Class Reference
#include <MCDwarf.h>
Public Member Functions
unsigned getFileNum () const
getFileNum - Get the FileNum of this MCDwarfLoc.
unsigned getLine () const
getLine - Get the Line of this MCDwarfLoc.
unsigned getColumn () const
getColumn - Get the Column of this MCDwarfLoc.
unsigned getFlags () const
getFlags - Get the Flags of this MCDwarfLoc.
unsigned getIsa () const
getIsa - Get the Isa of this MCDwarfLoc.
unsigned getDiscriminator () const
getDiscriminator - Get the Discriminator of this MCDwarfLoc.
void setFileNum (unsigned fileNum)
setFileNum - Set the FileNum of this MCDwarfLoc.
void setLine (unsigned line)
setLine - Set the Line of this MCDwarfLoc.
void setColumn (unsigned column)
setColumn - Set the Column of this MCDwarfLoc.
void setFlags (unsigned flags)
setFlags - Set the Flags of this MCDwarfLoc.
void setIsa (unsigned isa)
setIsa - Set the Isa of this MCDwarfLoc.
void setDiscriminator (unsigned discriminator)
setDiscriminator - Set the Discriminator of this MCDwarfLoc.
Friends
class MCContext
class MCLineEntry
Detailed Description
MCDwarfLoc - Instances of this class represent the information from a dwarf .loc directive.
Definition at line 76 of file MCDwarf.h.
Member Function Documentation
unsigned llvm::MCDwarfLoc::getColumn () const inline
getColumn - Get the Column of this MCDwarfLoc.
Definition at line 117 of file MCDwarf.h.
unsigned llvm::MCDwarfLoc::getDiscriminator () const inline
getDiscriminator - Get the Discriminator of this MCDwarfLoc.
Definition at line 126 of file MCDwarf.h.
unsigned llvm::MCDwarfLoc::getFileNum () const inline
getFileNum - Get the FileNum of this MCDwarfLoc.
Definition at line 111 of file MCDwarf.h.
unsigned llvm::MCDwarfLoc::getFlags () const inline
getFlags - Get the Flags of this MCDwarfLoc.
Definition at line 120 of file MCDwarf.h.
unsigned llvm::MCDwarfLoc::getIsa () const inline
getIsa - Get the Isa of this MCDwarfLoc.
Definition at line 123 of file MCDwarf.h.
unsigned llvm::MCDwarfLoc::getLine () const inline
getLine - Get the Line of this MCDwarfLoc.
Definition at line 114 of file MCDwarf.h.
void llvm::MCDwarfLoc::setColumn (unsigned column) inline
setColumn - Set the Column of this MCDwarfLoc.
Definition at line 135 of file MCDwarf.h.
Referenced by llvm::MCContext::setCurrentDwarfLoc().
void llvm::MCDwarfLoc::setDiscriminator (unsigned discriminator) inline
setDiscriminator - Set the Discriminator of this MCDwarfLoc.
Definition at line 144 of file MCDwarf.h.
Referenced by llvm::MCContext::setCurrentDwarfLoc().
void llvm::MCDwarfLoc::setFileNum (unsigned fileNum) inline
setFileNum - Set the FileNum of this MCDwarfLoc.
Definition at line 129 of file MCDwarf.h.
Referenced by llvm::MCContext::setCurrentDwarfLoc().
void llvm::MCDwarfLoc::setFlags (unsigned flags) inline
setFlags - Set the Flags of this MCDwarfLoc.
Definition at line 138 of file MCDwarf.h.
Referenced by llvm::MCContext::setCurrentDwarfLoc().
void llvm::MCDwarfLoc::setIsa (unsigned isa) inline
setIsa - Set the Isa of this MCDwarfLoc.
Definition at line 141 of file MCDwarf.h.
References llvm::isa().
Referenced by llvm::MCContext::setCurrentDwarfLoc().
void llvm::MCDwarfLoc::setLine (unsigned line) inline
setLine - Set the Line of this MCDwarfLoc.
Definition at line 132 of file MCDwarf.h.
Referenced by llvm::MCContext::setCurrentDwarfLoc().
Friends And Related Function Documentation
friend class MCContext friend
Definition at line 99 of file MCDwarf.h.
friend class MCLineEntry friend
Definition at line 100 of file MCDwarf.h.
The documentation for this class was generated from the following file:
MCDwarf.h