LLVM: llvm::MachineModuleInfoMachO Class Reference
LLVM API Documentation
llvm::MachineModuleInfoMachO Class Reference
#include <MachineModuleInfoImpls.h>
Public Member Functions
MachineModuleInfoMachO (const MachineModuleInfo &)
StubValueTy & getFnStubEntry (MCSymbol *Sym)
StubValueTy & getGVStubEntry (MCSymbol *Sym)
StubValueTy & getHiddenGVStubEntry (MCSymbol *Sym)
SymbolListTy GetFnStubList () const
Accessor methods to return the set of stubs in sorted order.
SymbolListTy GetGVStubList () const
SymbolListTy GetHiddenGVStubList () const
Public Member Functions inherited from llvm::MachineModuleInfoImpl
virtual ~MachineModuleInfoImpl ()
Additional Inherited Members
Public Types inherited from llvm::MachineModuleInfoImpl
typedef PointerIntPair< MCSymbol *, 1, bool > StubValueTy
typedef std::vector< std::pair< MCSymbol *, StubValueTy > > SymbolListTy
Static Protected Member Functions inherited from llvm::MachineModuleInfoImpl
static SymbolListTy GetSortedStubs (const DenseMap< MCSymbol *, StubValueTy > &)
Detailed Description
MachineModuleInfoMachO - This is a MachineModuleInfoImpl implementation for MachO targets.
Definition at line 25 of file MachineModuleInfoImpls.h.
Constructor & Destructor Documentation
llvm::MachineModuleInfoMachO::MachineModuleInfoMachO (const MachineModuleInfo &) inline
Definition at line 43 of file MachineModuleInfoImpls.h.
Member Function Documentation
StubValueTy& llvm::MachineModuleInfoMachO::getFnStubEntry (MCSymbol * Sym) inline
Definition at line 45 of file MachineModuleInfoImpls.h.
Referenced by GetSymbolFromOperand().
SymbolListTy llvm::MachineModuleInfoMachO::GetFnStubList () const inline
Accessor methods to return the set of stubs in sorted order.
Definition at line 61 of file MachineModuleInfoImpls.h.
References llvm::MachineModuleInfoImpl::GetSortedStubs().
Referenced by llvm::X86AsmPrinter::EmitEndOfAsmFile(), and GetAnonSym().
StubValueTy& llvm::MachineModuleInfoMachO::getGVStubEntry (MCSymbol * Sym) inline
Definition at line 50 of file MachineModuleInfoImpls.h.
Referenced by GetAnonSym(), llvm::TargetLoweringObjectFileMachO::getCFIPersonalitySymbol(), getModifierVariantKind(), GetSymbolFromOperand(), and llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference().
SymbolListTy llvm::MachineModuleInfoMachO::GetGVStubList () const inline
Definition at line 64 of file MachineModuleInfoImpls.h.
References llvm::MachineModuleInfoImpl::GetSortedStubs().
Referenced by llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::ARMAsmPrinter::EmitEndOfAsmFile(), and GetAnonSym().
StubValueTy& llvm::MachineModuleInfoMachO::getHiddenGVStubEntry (MCSymbol * Sym) inline
Definition at line 55 of file MachineModuleInfoImpls.h.
Referenced by getModifierVariantKind(), GetSymbolFromOperand(), and llvm::TargetLoweringObjectFileMachO::getTTypeGlobalReference().
SymbolListTy llvm::MachineModuleInfoMachO::GetHiddenGVStubList () const inline
Definition at line 67 of file MachineModuleInfoImpls.h.
References llvm::MachineModuleInfoImpl::GetSortedStubs().
Referenced by llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::ARMAsmPrinter::EmitEndOfAsmFile(), and GetAnonSym().
The documentation for this class was generated from the following files:
MachineModuleInfoImpls.h
MachineModuleInfoImpls.cpp