LLVM: llvm::DenseSet< ValueT, ValueInfoT >::Iterator Class Reference
LLVM API Documentation
llvm::DenseSet< ValueT, ValueInfoT >::Iterator Class Reference
#include <DenseSet.h>
Public Types
typedef MapTy::iterator::difference_type difference_type
typedef ValueT value_type
typedef value_type * pointer
typedef value_type & reference
typedef std::forward_iterator_tag iterator_category
Public Member Functions
Iterator (const typename MapTy::iterator &i)
ValueT & operator* ()
ValueT * operator-> ()
Iterator & operator++ ()
bool operator== (const Iterator &X) const
bool operator!= (const Iterator &X) const
Friends
class DenseSet
Detailed Description
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>>
class llvm::DenseSet< ValueT, ValueInfoT >::Iterator
Definition at line 64 of file DenseSet.h.
Member Typedef Documentation
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> typedef MapTy::iterator::difference_type llvm::DenseSet< ValueT, ValueInfoT >::Iterator::difference_type
Definition at line 68 of file DenseSet.h.
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> typedef std::forward_iterator_tag llvm::DenseSet< ValueT, ValueInfoT >::Iterator::iterator_category
Definition at line 72 of file DenseSet.h.
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> typedef value_type* llvm::DenseSet< ValueT, ValueInfoT >::Iterator::pointer
Definition at line 70 of file DenseSet.h.
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> typedef value_type& llvm::DenseSet< ValueT, ValueInfoT >::Iterator::reference
Definition at line 71 of file DenseSet.h.
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> typedef ValueT llvm::DenseSet< ValueT, ValueInfoT >::Iterator::value_type
Definition at line 69 of file DenseSet.h.
Constructor & Destructor Documentation
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> llvm::DenseSet< ValueT, ValueInfoT >::Iterator::Iterator (const typename MapTy::iterator & i) inline
Definition at line 74 of file DenseSet.h.
Referenced by llvm::DenseSet< llvm::Value * >::begin(), llvm::DenseSet< llvm::Value * >::end(), and llvm::DenseSet< llvm::Value * >::find().
Member Function Documentation
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> bool llvm::DenseSet< ValueT, ValueInfoT >::Iterator::operator!= (const Iterator & X) const inline
Definition at line 81 of file DenseSet.h.
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> ValueT& llvm::DenseSet< ValueT, ValueInfoT >::Iterator::operator* () inline
Definition at line 76 of file DenseSet.h.
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> Iterator& llvm::DenseSet< ValueT, ValueInfoT >::Iterator::operator++ () inline
Definition at line 79 of file DenseSet.h.
References I.
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> ValueT* llvm::DenseSet< ValueT, ValueInfoT >::Iterator::operator-> () inline
Definition at line 77 of file DenseSet.h.
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> bool llvm::DenseSet< ValueT, ValueInfoT >::Iterator::operator== (const Iterator & X) const inline
Definition at line 80 of file DenseSet.h.
Friends And Related Function Documentation
template<typename ValueT, typename ValueInfoT = DenseMapInfo<ValueT>> friend class DenseSet friend
Definition at line 66 of file DenseSet.h.
The documentation for this class was generated from the following file:
DenseSet.h