LLVM: llvm::PredIterator< Ptr, USE_iterator > Class Template Reference
LLVM API Documentation
llvm::PredIterator< Ptr, USE_iterator > Class Template Reference
#include <CFG.h>
Public Types
typedef super::pointer pointer
typedef super::reference reference
Public Member Functions
PredIterator ()
PredIterator (Ptr *bb)
PredIterator (Ptr *bb, bool)
bool operator== (const Self &x) const
bool operator!= (const Self &x) const
reference operator* () const
pointer * operator-> () const
Self & operator++ ()
Self operator++ (int)
unsigned getOperandNo () const
Use & getUse () const
Detailed Description
template<class Ptr, class USE_iterator>
class llvm::PredIterator< Ptr, USE_iterator >
Definition at line 29 of file Support/CFG.h.
Member Typedef Documentation
template<class Ptr , class USE_iterator > typedef super::pointer llvm::PredIterator< Ptr, USE_iterator >::pointer
Definition at line 43 of file Support/CFG.h.
template<class Ptr , class USE_iterator > typedef super::reference llvm::PredIterator< Ptr, USE_iterator >::reference
Definition at line 44 of file Support/CFG.h.
Constructor & Destructor Documentation
template<class Ptr , class USE_iterator > llvm::PredIterator< Ptr, USE_iterator >::PredIterator () inline
Definition at line 46 of file Support/CFG.h.
template<class Ptr , class USE_iterator > llvm::PredIterator< Ptr, USE_iterator >::PredIterator (Ptr * bb) inline explicit
Definition at line 47 of file Support/CFG.h.
template<class Ptr , class USE_iterator > llvm::PredIterator< Ptr, USE_iterator >::PredIterator (Ptr * bb, bool) inline
Definition at line 50 of file Support/CFG.h.
Member Function Documentation
template<class Ptr , class USE_iterator > unsigned llvm::PredIterator< Ptr, USE_iterator >::getOperandNo () const inline
getOperandNo - Return the operand number in the predecessor's terminator of the successor.
Definition at line 73 of file Support/CFG.h.
template<class Ptr , class USE_iterator > Use& llvm::PredIterator< Ptr, USE_iterator >::getUse () const inline
getUse - Return the operand Use in the predecessor's terminator of the successor.
Definition at line 79 of file Support/CFG.h.
template<class Ptr , class USE_iterator > bool llvm::PredIterator< Ptr, USE_iterator >::operator!= (const Self & x) const inline
Definition at line 53 of file Support/CFG.h.
References llvm::PredIterator< Ptr, USE_iterator >::operator==().
template<class Ptr , class USE_iterator > reference llvm::PredIterator< Ptr, USE_iterator >::operator* () const inline
Definition at line 55 of file Support/CFG.h.
Referenced by llvm::PredIterator< Ptr, USE_iterator >::operator->(), and llvm::SuccIterator< TerminatorInst *, BasicBlock >::operator->().
template<class Ptr , class USE_iterator > Self& llvm::PredIterator< Ptr, USE_iterator >::operator++ () inline
Definition at line 61 of file Support/CFG.h.
template<class Ptr , class USE_iterator > Self llvm::PredIterator< Ptr, USE_iterator >::operator++ (int) inline
Definition at line 67 of file Support/CFG.h.
template<class Ptr , class USE_iterator > pointer* llvm::PredIterator< Ptr, USE_iterator >::operator-> () const inline
Definition at line 59 of file Support/CFG.h.
References llvm::PredIterator< Ptr, USE_iterator >::operator*().
template<class Ptr , class USE_iterator > bool llvm::PredIterator< Ptr, USE_iterator >::operator== (const Self & x) const inline
Definition at line 52 of file Support/CFG.h.
Referenced by llvm::PredIterator< Ptr, USE_iterator >::operator!=(), and llvm::SuccIterator< TerminatorInst *, BasicBlock >::operator!=().
The documentation for this class was generated from the following file:
Support/CFG.h