LLVM: llvm::Mips16RegisterInfo Class Reference
LLVM API Documentation
llvm::Mips16RegisterInfo Class Reference
#include <Mips16RegisterInfo.h>
Public Member Functions
Mips16RegisterInfo (const MipsSubtarget &Subtarget)
bool requiresRegisterScavenging (const MachineFunction &MF) const
bool requiresFrameIndexScavenging (const MachineFunction &MF) const
bool useFPForScavengingIndex (const MachineFunction &MF) const
bool saveScavengerRegister (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, MachineBasicBlock::iterator &UseMI, const TargetRegisterClass *RC, unsigned Reg) const
virtual const TargetRegisterClass * intRegClass (unsigned Size) const
Return GPR register class.
Public Member Functions inherited from llvm::MipsRegisterInfo
MipsRegisterInfo (const MipsSubtarget &Subtarget)
void adjustMipsStackFrame (MachineFunction &MF) const
Adjust the Mips stack frame.
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind) const
Code Generation virtual methods...
unsigned getRegPressureLimit (const TargetRegisterClass *RC, MachineFunction &MF) const
const uint16_t * getCalleeSavedRegs (const MachineFunction *MF=0) const
Mips Callee Saved Registers.
const uint32_t * getCallPreservedMask (CallingConv::ID) const
BitVector getReservedRegs (const MachineFunction &MF) const
virtual bool trackLivenessAfterRegAlloc (const MachineFunction &MF) const
void eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=NULL) const
Stack Frame Processing Methods.
void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS=NULL) const
unsigned getFrameRegister (const MachineFunction &MF) const
Debug information queries.
Additional Inherited Members
Static Public Member Functions inherited from llvm::MipsRegisterInfo
static unsigned getRegisterNumbering (unsigned RegEnum)
static unsigned getPICCallReg ()
Get PIC indirect call register.
static const uint32_t * getMips16RetHelperMask ()
Protected Attributes inherited from llvm::MipsRegisterInfo
const MipsSubtarget & Subtarget
Detailed Description
Definition at line 22 of file Mips16RegisterInfo.h.
Constructor & Destructor Documentation
Mips16RegisterInfo::Mips16RegisterInfo (const MipsSubtarget & Subtarget)
Definition at line 44 of file Mips16RegisterInfo.cpp.
References requiresRegisterScavenging().
Member Function Documentation
const TargetRegisterClass * Mips16RegisterInfo::intRegClass (unsigned Size) const virtual
Return GPR register class.
Implements llvm::MipsRegisterInfo.
Definition at line 75 of file Mips16RegisterInfo.cpp.
References llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), DEBUG, llvm::errs(), llvm::ISD::FrameIndex, llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), llvm::TargetMachine::getFrameLowering(), llvm::MachineOperand::getImm(), llvm::TargetMachine::getInstrInfo(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getTarget(), llvm::TargetFrameLowering::hasFP(), llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isReg(), llvm::Mips16InstrInfo::loadImmediate(), llvm::A64CC::MI, TII, and llvm::Mips16InstrInfo::validImmediate().
bool Mips16RegisterInfo::requiresFrameIndexScavenging (const MachineFunction & MF) const
Definition at line 52 of file Mips16RegisterInfo.cpp.
References useFPForScavengingIndex().
Referenced by requiresRegisterScavenging().
bool Mips16RegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const virtual
Reimplemented from llvm::MipsRegisterInfo.
Definition at line 48 of file Mips16RegisterInfo.cpp.
References requiresFrameIndexScavenging().
Referenced by Mips16RegisterInfo().
bool Mips16RegisterInfo::saveScavengerRegister (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, MachineBasicBlock::iterator & UseMI, const TargetRegisterClass * RC, unsigned Reg) const
Definition at line 62 of file Mips16RegisterInfo.cpp.
References llvm::TargetInstrInfo::copyPhysReg(), llvm::TargetMachine::getInstrInfo(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getTarget(), and TII.
Referenced by useFPForScavengingIndex().
bool Mips16RegisterInfo::useFPForScavengingIndex (const MachineFunction & MF) const
Definition at line 57 of file Mips16RegisterInfo.cpp.
References saveScavengerRegister().
Referenced by requiresFrameIndexScavenging().
The documentation for this class was generated from the following files:
Mips16RegisterInfo.h
Mips16RegisterInfo.cpp