LLVM: llvm::sys::fs::directory_entry Class Reference
LLVM API Documentation
llvm::sys::fs::directory_entry Class Reference
#include <FileSystem.h>
Public Member Functions
directory_entry (const Twine &path, file_status st=file_status())
directory_entry ()
void assign (const Twine &path, file_status st=file_status())
void replace_filename (const Twine &filename, file_status st=file_status())
const std::string & path () const
error_code status (file_status &result) const
bool operator== (const directory_entry &rhs) const
bool operator!= (const directory_entry &rhs) const
bool operator< (const directory_entry &rhs) const
bool operator<= (const directory_entry &rhs) const
bool operator> (const directory_entry &rhs) const
bool operator>= (const directory_entry &rhs) const
Detailed Description
directory_entry - A single entry in a directory. Caches the status either from the result of the iteration syscall, or the first time status is called.
Definition at line 792 of file FileSystem.h.
Constructor & Destructor Documentation
llvm::sys::fs::directory_entry::directory_entry (const Twine & path, file_status st = file_status()) inline explicit
Definition at line 797 of file FileSystem.h.
llvm::sys::fs::directory_entry::directory_entry () inline
Definition at line 801 of file FileSystem.h.
Member Function Documentation
void llvm::sys::fs::directory_entry::assign (const Twine & path, file_status st = file_status()) inline
Definition at line 803 of file FileSystem.h.
References llvm::sys::path::filename(), and llvm::Twine::str().
bool llvm::sys::fs::directory_entry::operator!= (const directory_entry & rhs) const inline
Definition at line 814 of file FileSystem.h.
References llvm::sys::operator<(), llvm::operator<=(), llvm::operator>(), and llvm::operator>=().
bool llvm::sys::fs::directory_entry::operator< (const directory_entry & rhs) const
bool llvm::sys::fs::directory_entry::operator<= (const directory_entry & rhs) const
bool llvm::sys::fs::directory_entry::operator== (const directory_entry & rhs) const inline
Definition at line 813 of file FileSystem.h.
bool llvm::sys::fs::directory_entry::operator> (const directory_entry & rhs) const
bool llvm::sys::fs::directory_entry::operator>= (const directory_entry & rhs) const
const std::string& llvm::sys::fs::directory_entry::path () const inline
Definition at line 810 of file FileSystem.h.
References llvm::sys::fs::status().
Referenced by llvm::sys::fs::directory_iterator::directory_iterator(), and llvm::sys::fs::identify_magic().
void llvm::sys::fs::directory_entry::replace_filename (const Twine & filename, file_status st = file_status())
Definition at line 819 of file Path.cpp.
References llvm::sys::path::append(), and llvm::sys::path::remove_filename().
error_code llvm::sys::fs::directory_entry::status (file_status & result) const
Definition at line 1025 of file Path.cpp.
References llvm::sys::fs::status().
Referenced by llvm::sys::fs::identify_magic().
The documentation for this class was generated from the following files:
FileSystem.h
Path.cpp