LLVM: llvm::VirtRegMap Class Reference
LLVM API Documentation
llvm::VirtRegMap Class Reference
#include <VirtRegMap.h>
Public Types
enum { NO_PHYS_REG = 0, NO_STACK_SLOT = (1L << 30)-1, MAX_STACK_SLOT = (1L << 18)-1 }
Public Member Functions
VirtRegMap ()
virtual bool runOnMachineFunction (MachineFunction &MF)
virtual void getAnalysisUsage (AnalysisUsage &AU) const
MachineFunction & getMachineFunction () const
MachineRegisterInfo & getRegInfo () const
const TargetRegisterInfo & getTargetRegInfo () const
void grow ()
bool hasPhys (unsigned virtReg) const
returns true if the specified virtual register is mapped to a physical register
unsigned getPhys (unsigned virtReg) const
returns the physical register mapped to the specified virtual register
void assignVirt2Phys (unsigned virtReg, unsigned physReg)
creates a mapping for the specified virtual register to the specified physical register
void clearVirt (unsigned virtReg)
clears the specified virtual register's, physical register mapping
void clearAllVirt ()
clears all virtual to physical register mappings
bool hasPreferredPhys (unsigned VirtReg)
returns true if VirtReg is assigned to its preferred physreg.
bool hasKnownPreference (unsigned VirtReg)
returns true if VirtReg has a known preferred register. This returns false if VirtReg has a preference that is a virtual register that hasn't been assigned yet.
void setIsSplitFromReg (unsigned virtReg, unsigned SReg)
records virtReg is a split live interval from SReg.
unsigned getPreSplitReg (unsigned virtReg) const
returns the live interval virtReg is split from.
unsigned getOriginal (unsigned VirtReg) const
bool isAssignedReg (unsigned virtReg) const
returns true if the specified virtual register is not mapped to a stack slot or rematerialized.
int getStackSlot (unsigned virtReg) const
returns the stack slot mapped to the specified virtual register
int assignVirt2StackSlot (unsigned virtReg)
create a mapping for the specifed virtual register to the next available stack slot
void assignVirt2StackSlot (unsigned virtReg, int frameIndex)
create a mapping for the specified virtual register to the specified stack slot
void print (raw_ostream &OS, const Module *M=0) const
void dump () const
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const
createPrinterPass - Get a function printer pass.
virtual void assignPassManager (PMStack &PMS, PassManagerType T)
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
Detailed Description
Definition at line 32 of file VirtRegMap.h.
Member Enumeration Documentation
anonymous enum
Enumerator
NO_PHYS_REG
NO_STACK_SLOT
MAX_STACK_SLOT
Definition at line 34 of file VirtRegMap.h.
Constructor & Destructor Documentation
llvm::VirtRegMap::VirtRegMap () inline
Definition at line 71 of file VirtRegMap.h.
References runOnMachineFunction().
Member Function Documentation
void llvm::VirtRegMap::assignVirt2Phys (unsigned virtReg, unsigned physReg) inline
creates a mapping for the specified virtual register to the specified physical register
Definition at line 105 of file VirtRegMap.h.
References llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::TargetRegisterInfo::isVirtualRegister(), and NO_PHYS_REG.
Referenced by llvm::RegAllocBase::allocatePhysRegs(), and llvm::LiveRegMatrix::assign().
int VirtRegMap::assignVirt2StackSlot (unsigned virtReg)
create a mapping for the specifed virtual register to the next available stack slot
Definition at line 99 of file VirtRegMap.cpp.
References llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::TargetRegisterInfo::isVirtualRegister(), and NO_STACK_SLOT.
Referenced by dumpMachineInstrRangeWithSlotIndex(), getStackSlot(), and llvm::Spiller::~Spiller().
void VirtRegMap::assignVirt2StackSlot (unsigned virtReg, int frameIndex)
create a mapping for the specified virtual register to the specified stack slot
Definition at line 107 of file VirtRegMap.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getObjectIndexBegin(), llvm::TargetRegisterInfo::isVirtualRegister(), and NO_STACK_SLOT.
void llvm::VirtRegMap::clearAllVirt () inline
clears all virtual to physical register mappings
Definition at line 124 of file VirtRegMap.h.
References llvm::IndexedMap< T, ToIndexT >::clear(), grow(), hasKnownPreference(), and hasPreferredPhys().
void llvm::VirtRegMap::clearVirt (unsigned virtReg) inline
clears the specified virtual register's, physical register mapping
Definition at line 116 of file VirtRegMap.h.
References llvm::TargetRegisterInfo::isVirtualRegister(), and NO_PHYS_REG.
Referenced by llvm::LiveRegMatrix::unassign().
void VirtRegMap::dump () const
Definition at line 139 of file VirtRegMap.cpp.
References llvm::dbgs(), getAnalysisUsage(), ID, llvm::MachineFunctionPass::MachineFunctionPass(), MRI, print(), runOnMachineFunction(), TII, and llvm::SystemZISD::TM.
Referenced by getStackSlot().
virtual void llvm::VirtRegMap::getAnalysisUsage (AnalysisUsage & AU) const inline virtual
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
For MachineFunctionPasses, calling AU.preservesCFG() indicates that the pass does not modify the MachineBasicBlock CFG.
Reimplemented from llvm::MachineFunctionPass.
Definition at line 75 of file VirtRegMap.h.
References llvm::MachineFunctionPass::getAnalysisUsage(), and llvm::AnalysisUsage::setPreservesAll().
Referenced by dump().
MachineFunction& llvm::VirtRegMap::getMachineFunction () const inline
Definition at line 80 of file VirtRegMap.h.
Referenced by llvm::AllocationOrder::AllocationOrder(), findInsertLocation(), llvm::SplitEditor::finish(), llvm::RegAllocBase::init(), llvm::SplitEditor::reset(), and llvm::SplitEditor::splitLiveThroughBlock().
unsigned llvm::VirtRegMap::getOriginal (unsigned VirtReg) const inline
getOriginal - Return the original virtual register that VirtReg descends from through splitting. A register that was not created by splitting is its own original. This operation is idempotent.
Definition at line 151 of file VirtRegMap.h.
References getPreSplitReg().
Referenced by dumpMachineInstrRangeWithSlotIndex(), isFullCopyOf(), and llvm::SplitAnalysis::isOriginalEndpoint().
unsigned llvm::VirtRegMap::getPhys (unsigned virtReg) const inline
returns the physical register mapped to the specified virtual register
Definition at line 98 of file VirtRegMap.h.
References llvm::TargetRegisterInfo::isVirtualRegister().
Referenced by llvm::LiveIntervals::addKillFlags(), llvm::ARMBaseRegisterInfo::getRegAllocationHints(), llvm::TargetRegisterInfo::getRegAllocationHints(), hasPhys(), hasPreferredPhys(), llvm::LiveDebugVariables::splitRegister(), and llvm::LiveRegMatrix::unassign().
unsigned llvm::VirtRegMap::getPreSplitReg (unsigned virtReg) const inline
returns the live interval virtReg is split from.
Definition at line 143 of file VirtRegMap.h.
Referenced by getOriginal().
MachineRegisterInfo& llvm::VirtRegMap::getRegInfo () const inline
Definition at line 85 of file VirtRegMap.h.
Referenced by llvm::RegAllocBase::init().
int llvm::VirtRegMap::getStackSlot (unsigned virtReg) const inline
returns the stack slot mapped to the specified virtual register
Definition at line 168 of file VirtRegMap.h.
References assignVirt2StackSlot(), dump(), llvm::TargetRegisterInfo::isVirtualRegister(), M, and print().
Referenced by dumpMachineInstrRangeWithSlotIndex(), isAssignedReg(), and llvm::LiveDebugVariables::splitRegister().
const TargetRegisterInfo& llvm::VirtRegMap::getTargetRegInfo () const inline
Definition at line 86 of file VirtRegMap.h.
References grow().
Referenced by llvm::AllocationOrder::AllocationOrder(), and llvm::RegAllocBase::init().
void VirtRegMap::grow ()
Definition at line 67 of file VirtRegMap.cpp.
References llvm::MachineFrameInfo::CreateSpillStackObject(), llvm::TargetRegisterClass::getAlignment(), llvm::MachineFunction::getFrameInfo(), llvm::MachineRegisterInfo::getNumVirtRegs(), llvm::MachineFunction::getRegInfo(), and llvm::TargetRegisterClass::getSize().
Referenced by clearAllVirt(), and getTargetRegInfo().
bool VirtRegMap::hasKnownPreference (unsigned VirtReg)
returns true if VirtReg has a known preferred register. This returns false if VirtReg has a preference that is a virtual register that hasn't been assigned yet.
Definition at line 90 of file VirtRegMap.cpp.
References hasPhys(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::TargetRegisterInfo::isVirtualRegister(), and MRI.
Referenced by clearAllVirt().
bool llvm::VirtRegMap::hasPhys (unsigned virtReg) const inline
returns true if the specified virtual register is mapped to a physical register
Definition at line 92 of file VirtRegMap.h.
References getPhys(), and NO_PHYS_REG.
Referenced by llvm::RegAllocBase::allocatePhysRegs(), llvm::LiveRegMatrix::assign(), llvm::ARMBaseRegisterInfo::getRegAllocationHints(), and hasKnownPreference().
bool VirtRegMap::hasPreferredPhys (unsigned VirtReg)
returns true if VirtReg is assigned to its preferred physreg.
Definition at line 81 of file VirtRegMap.cpp.
References getPhys(), llvm::TargetRegisterInfo::isVirtualRegister(), and MRI.
Referenced by clearAllVirt().
bool llvm::VirtRegMap::isAssignedReg (unsigned virtReg) const inline
returns true if the specified virtual register is not mapped to a stack slot or rematerialized.
Definition at line 158 of file VirtRegMap.h.
References getStackSlot(), NO_PHYS_REG, and NO_STACK_SLOT.
Referenced by llvm::LiveDebugVariables::splitRegister().
void VirtRegMap::print (raw_ostream & O, const Module * M = 0) const virtual
print - Print out the internal state of the pass. This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 117 of file VirtRegMap.cpp.
References llvm::MCRegisterClass::getName(), llvm::MCRegisterInfo::getRegClass(), i, llvm::TargetRegisterInfo::index2VirtReg(), MRI, NO_PHYS_REG, and NO_STACK_SLOT.
Referenced by dump(), getStackSlot(), and llvm::operator<<().
bool VirtRegMap::runOnMachineFunction (MachineFunction & MF) virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 53 of file VirtRegMap.cpp.
References llvm::HexagonInstrInfo::getRegisterInfo(), MRI, and TII.
Referenced by dump(), and VirtRegMap().
void llvm::VirtRegMap::setIsSplitFromReg (unsigned virtReg, unsigned SReg) inline
records virtReg is a split live interval from SReg.
Definition at line 138 of file VirtRegMap.h.
Member Data Documentation
char VirtRegMap::ID = 0 static
Definition at line 70 of file VirtRegMap.h.
Referenced by dump().
The documentation for this class was generated from the following files:
VirtRegMap.h
VirtRegMap.cpp