LLVM: llvm::Spiller Class Reference
LLVM API Documentation
llvm::Spiller Class Reference abstract
#include <Spiller.h>
Public Member Functions
virtual ~Spiller ()=0
virtual void spill (LiveRangeEdit &LRE)=0
spill - Spill the LRE.getParent() live interval.
Detailed Description
Spiller interface.
Implementations are utility classes which insert spill or remat code on demand.
Definition at line 24 of file Spiller.h.
Constructor & Destructor Documentation
Spiller::~Spiller () pure virtual
Definition at line 45 of file Spiller.cpp.
References llvm::VirtRegMap::assignVirt2StackSlot(), llvm::MachineInstrSpan::begin(), llvm::LiveRangeEdit::create(), llvm::dbgs(), DEBUG, llvm::MachineInstrSpan::end(), llvm::Pass::getAnalysis(), llvm::MachineFunction::getFrameInfo(), llvm::TargetMachine::getInstrInfo(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::LiveRangeEdit::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::TargetMachine::getRegisterInfo(), llvm::MachineFunction::getTarget(), llvm::huge_valf, i, llvm::LiveIntervals::InsertMachineInstrRangeInMaps(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), llvm::MachineInstr::isRegTiedToDefOperand(), llvm::TargetRegisterInfo::isStackSlot(), llvm::MachineOperand::isUse(), llvm::TargetInstrInfo::loadRegFromStackSlot(), llvm::next(), pass, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::LiveInterval::reg, llvm::MachineRegisterInfo::reg_begin(), llvm::MachineRegisterInfo::reg_end(), llvm::MachineOperand::setIsKill(), llvm::MachineOperand::setReg(), llvm::SmallVectorTemplateCommon< T >::size(), spill, llvm::TargetInstrInfo::storeRegToStackSlot(), and llvm::LiveInterval::weight.
Member Function Documentation
virtual void llvm::Spiller::spill (LiveRangeEdit & LRE) pure virtual
spill - Spill the LRE.getParent() live interval.
The documentation for this class was generated from the following files:
Spiller.h
Spiller.cpp