LLVM: llvm::MachinePassRegistry Class Reference
LLVM API Documentation
llvm::MachinePassRegistry Class Reference
#include <MachinePassRegistry.h>
Public Member Functions
MachinePassRegistryNode * getList ()
MachinePassCtor getDefault ()
void setDefault (MachinePassCtor C)
void setDefault (StringRef Name)
setDefault - Set the default constructor by name.
void setListener (MachinePassRegistryListener *L)
void Add (MachinePassRegistryNode *Node)
void Remove (MachinePassRegistryNode *Node)
Detailed Description
MachinePassRegistry - Track the registration of machine passes.
Definition at line 84 of file MachinePassRegistry.h.
Member Function Documentation
void MachinePassRegistry::Add (MachinePassRegistryNode * Node)
Add - Adds a function pass to the registration list.
Definition at line 36 of file MachinePassRegistry.cpp.
References llvm::MachinePassRegistryNode::getCtor(), llvm::MachinePassRegistryNode::getDescription(), llvm::MachinePassRegistryNode::getName(), llvm::tgtok::List, and llvm::MachinePassRegistryNode::setNext().
Referenced by llvm::MachineSchedRegistry::MachineSchedRegistry(), llvm::RegisterRegAlloc::RegisterRegAlloc(), and llvm::RegisterScheduler::RegisterScheduler().
MachinePassCtor llvm::MachinePassRegistry::getDefault () inline
Definition at line 100 of file MachinePassRegistry.h.
References llvm::Reloc::Default.
Referenced by llvm::RegisterRegAlloc::getDefault(), and llvm::RegisterScheduler::getDefault().
MachinePassRegistryNode* llvm::MachinePassRegistry::getList () inline
Definition at line 99 of file MachinePassRegistry.h.
References llvm::tgtok::List.
Referenced by llvm::RegisterRegAlloc::getList(), llvm::RegisterScheduler::getList(), and llvm::MachineSchedRegistry::getList().
void MachinePassRegistry::Remove (MachinePassRegistryNode * Node)
Remove - Removes a function pass from the registration list.
Definition at line 47 of file MachinePassRegistry.cpp.
References llvm::MachinePassRegistryNode::getName(), I, and llvm::tgtok::List.
Referenced by llvm::MachineSchedRegistry::~MachineSchedRegistry(), llvm::RegisterRegAlloc::~RegisterRegAlloc(), and llvm::RegisterScheduler::~RegisterScheduler().
void llvm::MachinePassRegistry::setDefault (MachinePassCtor C) inline
Definition at line 101 of file MachinePassRegistry.h.
Referenced by llvm::RegisterRegAlloc::setDefault(), and llvm::RegisterScheduler::setDefault().
void MachinePassRegistry::setDefault (StringRef Name)
setDefault - Set the default constructor by name.
Definition at line 22 of file MachinePassRegistry.cpp.
References llvm::MachinePassRegistryNode::getNext().
void llvm::MachinePassRegistry::setListener (MachinePassRegistryListener * L) inline
Definition at line 103 of file MachinePassRegistry.h.
Referenced by llvm::RegisterRegAlloc::setListener(), llvm::RegisterScheduler::setListener(), and llvm::MachineSchedRegistry::setListener().
The documentation for this class was generated from the following files:
MachinePassRegistry.h
MachinePassRegistry.cpp