LLVM: llvm::MCLineSection Class Reference
LLVM API Documentation
llvm::MCLineSection Class Reference
#include <MCDwarf.h>
Public Types
typedef std::vector< MCLineEntry > MCLineEntryCollection
typedef MCLineEntryCollection::iterator iterator
typedef MCLineEntryCollection::const_iterator const_iterator
typedef std::map< unsigned, MCLineEntryCollection > MCLineDivisionMap
Public Member Functions
MCLineSection ()
void addLineEntry (const MCLineEntry &LineEntry, unsigned CUID)
bool containEntriesForID (unsigned CUID) const
const MCLineEntryCollection & getMCLineEntries (unsigned CUID) const
Detailed Description
MCLineSection - Instances of this class represent the line information for a section where machine instructions have been assembled after seeing .loc directives. This is the information used to build the dwarf line table for a section.
Definition at line 178 of file MCDwarf.h.
Member Typedef Documentation
typedef MCLineEntryCollection::const_iterator llvm::MCLineSection::const_iterator
Definition at line 196 of file MCDwarf.h.
typedef MCLineEntryCollection::iterator llvm::MCLineSection::iterator
Definition at line 195 of file MCDwarf.h.
typedef std::map<unsigned, MCLineEntryCollection> llvm::MCLineSection::MCLineDivisionMap
Definition at line 197 of file MCDwarf.h.
typedef std::vector<MCLineEntry> llvm::MCLineSection::MCLineEntryCollection
Definition at line 194 of file MCDwarf.h.
Constructor & Destructor Documentation
llvm::MCLineSection::MCLineSection () inline
Definition at line 187 of file MCDwarf.h.
Member Function Documentation
void llvm::MCLineSection::addLineEntry (const MCLineEntry & LineEntry, unsigned CUID) inline
Definition at line 190 of file MCDwarf.h.
Referenced by llvm::MCLineEntry::Make().
bool llvm::MCLineSection::containEntriesForID (unsigned CUID) const inline
Definition at line 206 of file MCDwarf.h.
Referenced by EmitDwarfLineTable().
const MCLineEntryCollection& llvm::MCLineSection::getMCLineEntries (unsigned CUID) const inline
Definition at line 210 of file MCDwarf.h.
Referenced by EmitDwarfLineTable().
The documentation for this class was generated from the following file:
MCDwarf.h