LLVM: llvm::MCLineEntry Class Reference
LLVM API Documentation
llvm::MCLineEntry Class Reference
#include <MCDwarf.h>
Public Member Functions
MCLineEntry (MCSymbol *label, const MCDwarfLoc loc)
MCSymbol * getLabel () const
Public Member Functions inherited from llvm::MCDwarfLoc
unsigned getFileNum () const
getFileNum - Get the FileNum of this MCDwarfLoc.
unsigned getLine () const
getLine - Get the Line of this MCDwarfLoc.
unsigned getColumn () const
getColumn - Get the Column of this MCDwarfLoc.
unsigned getFlags () const
getFlags - Get the Flags of this MCDwarfLoc.
unsigned getIsa () const
getIsa - Get the Isa of this MCDwarfLoc.
unsigned getDiscriminator () const
getDiscriminator - Get the Discriminator of this MCDwarfLoc.
void setFileNum (unsigned fileNum)
setFileNum - Set the FileNum of this MCDwarfLoc.
void setLine (unsigned line)
setLine - Set the Line of this MCDwarfLoc.
void setColumn (unsigned column)
setColumn - Set the Column of this MCDwarfLoc.
void setFlags (unsigned flags)
setFlags - Set the Flags of this MCDwarfLoc.
void setIsa (unsigned isa)
setIsa - Set the Isa of this MCDwarfLoc.
void setDiscriminator (unsigned discriminator)
setDiscriminator - Set the Discriminator of this MCDwarfLoc.
Static Public Member Functions
static void Make (MCStreamer *MCOS, const MCSection *Section)
Detailed Description
MCLineEntry - Instances of this class represent the line information for the dwarf line table entries. Which is created after a machine instruction is assembled and uses an address from a temporary label created at the current address in the current section and the info from the last .loc directive seen as stored in the context.
Definition at line 154 of file MCDwarf.h.
Constructor & Destructor Documentation
llvm::MCLineEntry::MCLineEntry (MCSymbol * label, const MCDwarfLoc loc) inline
Definition at line 163 of file MCDwarf.h.
Member Function Documentation
MCSymbol* llvm::MCLineEntry::getLabel () const inline
Definition at line 166 of file MCDwarf.h.
References llvm::ARMBuildAttrs::Section.
void MCLineEntry::Make (MCStreamer * MCOS, const MCSection * Section) static
Definition at line 65 of file MCDwarf.cpp.
References llvm::MCLineSection::addLineEntry(), llvm::MCContext::addMCLineSection(), llvm::MCContext::ClearDwarfLocSeen(), llvm::MCContext::CreateTempSymbol(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::getContext(), llvm::MCContext::getCurrentDwarfLoc(), llvm::MCContext::getDwarfCompileUnitID(), llvm::MCContext::getDwarfLocSeen(), llvm::MCContext::getMCLineSections(), and llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::lookup().
Referenced by llvm::MCObjectStreamer::EmitBytes(), llvm::MCObjectStreamer::EmitDwarfLocDirective(), llvm::AsmPrinter::EmitFunctionBody(), llvm::MCObjectStreamer::EmitInstruction(), and llvm::MCObjectStreamer::EmitValueImpl().
The documentation for this class was generated from the following files:
MCDwarf.h
MCDwarf.cpp