LLVM: llvm::DwarfAccelTable Class Reference
LLVM API Documentation
llvm::DwarfAccelTable Class Reference
#include <DwarfAccelTable.h>
Classes
struct Atom
struct HashDataContents
Public Member Functions
DwarfAccelTable (ArrayRef< DwarfAccelTable::Atom >)
~DwarfAccelTable ()
void AddName (StringRef, DIE *, char=0)
void FinalizeTable (AsmPrinter *, StringRef)
void Emit (AsmPrinter *, MCSymbol *, DwarfUnits *)
void print (raw_ostream &O)
void dump ()
Detailed Description
Definition at line 68 of file DwarfAccelTable.h.
Constructor & Destructor Documentation
DwarfAccelTable::DwarfAccelTable (ArrayRef< DwarfAccelTable::Atom > atomList)
Definition at line 28 of file DwarfAccelTable.cpp.
DwarfAccelTable::~DwarfAccelTable ()
Definition at line 32 of file DwarfAccelTable.cpp.
Referenced by llvm::DwarfAccelTable::HashDataContents::print().
Member Function Documentation
void DwarfAccelTable::AddName (StringRef Name, DIE * die, char Flags = 0)
Definition at line 34 of file DwarfAccelTable.cpp.
References llvm::array_pod_sort(), i, and p.
Referenced by llvm::DwarfUnits::emitUnits(), and llvm::DwarfAccelTable::HashDataContents::print().
void llvm::DwarfAccelTable::dump () inline
Definition at line 249 of file DwarfAccelTable.h.
References llvm::dbgs(), and print().
Referenced by llvm::DwarfAccelTable::Atom::dump(), and llvm::DwarfAccelTable::HashDataContents::print().
void DwarfAccelTable::Emit (AsmPrinter * Asm, MCSymbol * SecBegin, DwarfUnits * D)
Definition at line 210 of file DwarfAccelTable.cpp.
Referenced by llvm::DwarfUnits::emitUnits(), and llvm::DwarfAccelTable::HashDataContents::print().
void DwarfAccelTable::FinalizeTable (AsmPrinter * Asm, StringRef Prefix)
Definition at line 69 of file DwarfAccelTable.cpp.
References llvm::ARM_PROC::A, llvm::MCStreamer::AddComment(), llvm::HexStyle::Asm, llvm::dwarf::AtomTypeString(), llvm::sys::path::begin(), llvm::StringMap< ValueTy, AllocatorTy >::begin(), compareDIEs(), llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateSub(), llvm::X86II::DE, llvm::AsmPrinter::EmitInt16(), llvm::AsmPrinter::EmitInt32(), llvm::AsmPrinter::EmitInt8(), llvm::MCStreamer::EmitLabel(), llvm::AsmPrinter::EmitSectionOffset(), llvm::MCStreamer::EmitValue(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::DwarfAccelTable::Atom::form, llvm::dwarf::FormEncodingString(), llvm::MCStreamer::getContext(), llvm::DwarfUnits::getStringPoolEntry(), llvm::DwarfUnits::getStringPoolSym(), llvm::AsmPrinter::GetTempSymbol(), HI, i, index, llvm::AsmPrinter::OutStreamer, size, and llvm::DwarfAccelTable::Atom::type.
Referenced by llvm::DwarfUnits::emitUnits(), and llvm::DwarfAccelTable::HashDataContents::print().
void DwarfAccelTable::print (raw_ostream & O)
Definition at line 228 of file DwarfAccelTable.cpp.
References llvm::sys::path::begin(), llvm::StringMap< ValueTy, AllocatorTy >::begin(), llvm::X86II::DE, llvm::StringMap< ValueTy, AllocatorTy >::end(), HI, and i.
Referenced by llvm::DwarfAccelTable::Atom::dump(), dump(), and llvm::DwarfAccelTable::HashDataContents::print().
The documentation for this class was generated from the following files:
DwarfAccelTable.h
DwarfAccelTable.cpp