LLVM: llvm::yaml::Output Class Reference
LLVM API Documentation
llvm::yaml::Output Class Reference
#include <YAMLTraits.h>
Public Member Functions
Output (llvm::raw_ostream &, void *Ctxt=NULL)
virtual ~Output ()
virtual bool outputting () const
virtual bool mapTag (StringRef, bool)
virtual void beginMapping ()
virtual void endMapping ()
virtual bool preflightKey (const char *key, bool, bool, bool &, void *&)
virtual void postflightKey (void *)
virtual unsigned beginSequence ()
virtual void endSequence ()
virtual bool preflightElement (unsigned, void *&)
virtual void postflightElement (void *)
virtual unsigned beginFlowSequence ()
virtual bool preflightFlowElement (unsigned, void *&)
virtual void postflightFlowElement (void *)
virtual void endFlowSequence ()
virtual void beginEnumScalar ()
virtual bool matchEnumScalar (const char *, bool)
virtual void endEnumScalar ()
virtual bool beginBitSetScalar (bool &)
virtual bool bitSetMatch (const char *, bool)
virtual void endBitSetScalar ()
virtual void scalarString (StringRef &)
virtual void setError (const Twine &message)
virtual bool canElideEmptySequence ()
void beginDocuments ()
bool preflightDocument (unsigned)
void postflightDocument ()
void endDocuments ()
Public Member Functions inherited from llvm::yaml::IO
IO (void *Ctxt=NULL)
virtual ~IO ()
template<typename T >
void enumCase (T &Val, const char *Str, const T ConstVal)
template<typename T >
void enumCase (T &Val, const char *Str, const uint32_t ConstVal)
template<typename T >
void bitSetCase (T &Val, const char *Str, const T ConstVal)
template<typename T >
void bitSetCase (T &Val, const char *Str, const uint32_t ConstVal)
void * getContext ()
void setContext (void *)
template<typename T >
void mapRequired (const char *Key, T &Val)
template<typename T >
llvm::enable_if_c< has_SequenceTraits< T >::value, void >::type mapOptional (const char *Key, T &Val)
template<typename T >
llvm::enable_if_c<!has_SequenceTraits< T >::value, void >::type mapOptional (const char *Key, T &Val)
template<typename T >
void mapOptional (const char *Key, T &Val, const T &Default)
Static Public Member Functions
static bool classof (const IO *io)
Detailed Description
The Output class is used to generate a yaml document from in-memory structs and vectors.
Definition at line 823 of file YAMLTraits.h.
Constructor & Destructor Documentation
Output::Output (llvm::raw_ostream & yout, void * Ctxt = NULL)
Definition at line 395 of file YAMLTraits.cpp.
Output::~Output () virtual
Definition at line 406 of file YAMLTraits.cpp.
Member Function Documentation
bool Output::beginBitSetScalar (bool & DoClear) virtual
Implements llvm::yaml::IO.
Definition at line 531 of file YAMLTraits.cpp.
void Output::beginDocuments ()
Definition at line 448 of file YAMLTraits.cpp.
Referenced by llvm::yaml::operator<<().
void Output::beginEnumScalar () virtual
Implements llvm::yaml::IO.
Definition at line 513 of file YAMLTraits.cpp.
unsigned Output::beginFlowSequence () virtual
Implements llvm::yaml::IO.
Definition at line 482 of file YAMLTraits.cpp.
References llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
void Output::beginMapping () virtual
Implements llvm::yaml::IO.
Definition at line 413 of file YAMLTraits.cpp.
References llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
unsigned Output::beginSequence () virtual
Implements llvm::yaml::IO.
Definition at line 465 of file YAMLTraits.cpp.
References llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
bool Output::bitSetMatch (const char * Str, bool Matches) virtual
Implements llvm::yaml::IO.
Definition at line 539 of file YAMLTraits.cpp.
bool Output::canElideEmptySequence () virtual
Implements llvm::yaml::IO.
Definition at line 592 of file YAMLTraits.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::StringRef::begin(), llvm::SmallVectorBase::empty(), llvm::sys::path::end(), llvm::StringRef::end(), llvm::StringRef::equals(), llvm::format(), llvm::getAsSignedInteger(), llvm::getAsUnsignedInteger(), i, input, n, N, output, s, llvm::NVPTX::PTXLdStInstCode::Scalar, llvm::StringRef::size(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::LibFunc::strlen, and llvm::LibFunc::strtod.
static bool llvm::yaml::Output::classof (const IO * io) inline static
Definition at line 828 of file YAMLTraits.h.
References message(), output, llvm::yaml::IO::outputting(), and s.
void Output::endBitSetScalar () virtual
Implements llvm::yaml::IO.
Definition at line 549 of file YAMLTraits.cpp.
void Output::endDocuments ()
Definition at line 461 of file YAMLTraits.cpp.
Referenced by llvm::yaml::operator<<().
void Output::endEnumScalar () virtual
Implements llvm::yaml::IO.
Definition at line 526 of file YAMLTraits.cpp.
References llvm_unreachable.
void Output::endFlowSequence () virtual
Implements llvm::yaml::IO.
Definition at line 491 of file YAMLTraits.cpp.
References llvm::SmallVectorTemplateBase< T, isPodLike >::pop_back().
void Output::endMapping () virtual
Implements llvm::yaml::IO.
Definition at line 426 of file YAMLTraits.cpp.
References llvm::SmallVectorTemplateBase< T, isPodLike >::pop_back().
void Output::endSequence () virtual
Implements llvm::yaml::IO.
Definition at line 471 of file YAMLTraits.cpp.
References llvm::SmallVectorTemplateBase< T, isPodLike >::pop_back().
bool Output::mapTag (StringRef Tag, bool Use) virtual
Implements llvm::yaml::IO.
Definition at line 418 of file YAMLTraits.cpp.
bool Output::matchEnumScalar (const char * Str, bool Match) virtual
Implements llvm::yaml::IO.
Definition at line 517 of file YAMLTraits.cpp.
bool Output::outputting () const virtual
Implements llvm::yaml::IO.
Definition at line 409 of file YAMLTraits.cpp.
void Output::postflightDocument ()
Definition at line 458 of file YAMLTraits.cpp.
Referenced by llvm::yaml::operator<<().
void Output::postflightElement (void *) virtual
Implements llvm::yaml::IO.
Definition at line 479 of file YAMLTraits.cpp.
void Output::postflightFlowElement (void *) virtual
Implements llvm::yaml::IO.
Definition at line 509 of file YAMLTraits.cpp.
void Output::postflightKey (void *) virtual
Implements llvm::yaml::IO.
Definition at line 441 of file YAMLTraits.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorTemplateBase< T, isPodLike >::pop_back(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
bool Output::preflightDocument (unsigned index)
Definition at line 452 of file YAMLTraits.cpp.
Referenced by llvm::yaml::operator<<().
bool Output::preflightElement (unsigned , void *&) virtual
Implements llvm::yaml::IO.
Definition at line 475 of file YAMLTraits.cpp.
bool Output::preflightFlowElement (unsigned , void *&) virtual
Implements llvm::yaml::IO.
Definition at line 496 of file YAMLTraits.cpp.
References i.
bool Output::preflightKey (const char * key, bool Required, bool SameAsDefault, bool & UseDefault, void *&) virtual
Implements llvm::yaml::IO.
Definition at line 430 of file YAMLTraits.cpp.
void Output::scalarString (StringRef & S) virtual
Implements llvm::yaml::IO.
Definition at line 553 of file YAMLTraits.cpp.
References llvm::StringRef::back(), llvm::StringRef::data(), llvm::StringRef::empty(), llvm::StringRef::find_first_not_of(), llvm::StringRef::front(), i, j(), llvm::StringRef::npos, and llvm::StringRef::size().
void Output::setError (const Twine & message) virtual
Implements llvm::yaml::IO.
Definition at line 589 of file YAMLTraits.cpp.
The documentation for this class was generated from the following files:
YAMLTraits.h
YAMLTraits.cpp