LLVM: llvm::ConstantInt Class Reference
LLVM API Documentation
llvm::ConstantInt Class Reference
Class for constant integers.
#include <Constants.h>
Public Member Functions
const APInt & getValue () const
Return the constant's value.
unsigned getBitWidth () const
getBitWidth - Return the bitwidth of this constant.
uint64_t getZExtValue () const
Return the zero extended value.
int64_t getSExtValue () const
Return the sign extended value.
bool equalsInt (uint64_t V) const
Determine if this constant's value is same as an unsigned char.
IntegerType * getType () const
bool isNegative () const
bool isZero () const
bool isOne () const
Determine if the value is one.
bool isMinusOne () const
Determine if the value is all ones.
bool isMaxValue (bool isSigned) const
Determine if the value is maximal.
bool isMinValue (bool isSigned) const
Determine if the value is minimal.
bool uge (uint64_t Num) const
Determine if the value is greater or equal to the given number.
uint64_t getLimitedValue (uint64_t Limit=~0ULL) const
Get the constant's value with a saturation limit.
Public Member Functions inherited from llvm::Constant
bool isNullValue () const
bool isAllOnesValue () const
bool isNegativeZeroValue () const
bool isZeroValue () const
Return true if the value is negative zero or null value.
bool canTrap () const
bool isThreadDependent () const
isThreadDependent - Return true if the value can vary between threads.
bool isConstantUsed () const
PossibleRelocationsTy getRelocationInfo () const
Constant * getAggregateElement (unsigned Elt) const
Constant * getAggregateElement (Constant *Elt) const
Constant * getSplatValue () const
const APInt & getUniqueInteger () const
virtual void destroyConstant ()
virtual void replaceUsesOfWithOnConstant (Value *, Value *, Use *)
void removeDeadConstantUsers () const
Public Member Functions inherited from llvm::User
~User ()
void operator delete (void *Usr)
operator delete - free memory allocated for User and Use objects
void operator delete (void *, unsigned)
placement delete - required by std, but never called.
void operator delete (void *, unsigned, bool)
placement delete - required by std, but never called.
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
void dropAllReferences ()
void replaceUsesOfWith (Value *From, Value *To)
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
dump - Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O, AssemblyAnnotationWriter *AAW=0) const
Type * getType () const
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
void setName (const Twine &Name)
void takeName (Value *V)
void replaceAllUsesWith (Value *V)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
User * use_back ()
const User * use_back () const
bool hasOneUse () const
bool hasNUses (unsigned N) const
bool hasNUsesOrMore (unsigned N) const
bool isUsedInBasicBlock (const BasicBlock *BB) const
unsigned getNumUses () const
void addUse (Use &U)
unsigned getValueID () const
unsigned getRawSubclassOptionalData () const
void clearSubclassOptionalData ()
bool hasSameSubclassOptionalData (const Value *V) const
void intersectOptionalDataWith (const Value *V)
bool hasValueHandle () const
Value * stripPointerCasts ()
Strips off any unneeded pointer casts, all-zero GEPs and aliases from the specified value, returning the original uncasted value.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strips off any unneeded pointer casts and all-zero GEPs from the specified value, returning the original uncasted value.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strips off unneeded pointer casts and all-constant GEPs from the specified value, returning the original pointer value.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Strips like stripInBoundsConstantOffsets but also accumulates the constant offset stripped.
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strips off unneeded pointer casts and any in-bounds offsets from the specified value, returning the original pointer value.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer () const
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Static Public Member Functions
static ConstantInt * getTrue (LLVMContext &Context)
static ConstantInt * getFalse (LLVMContext &Context)
static Constant * getTrue (Type *Ty)
static Constant * getFalse (Type *Ty)
static Constant * get (Type *Ty, uint64_t V, bool isSigned=false)
static ConstantInt * get (IntegerType *Ty, uint64_t V, bool isSigned=false)
Get a ConstantInt for a specific value.
static ConstantInt * getSigned (IntegerType *Ty, int64_t V)
Get a ConstantInt for a specific signed value.
static Constant * getSigned (Type *Ty, int64_t V)
static ConstantInt * get (LLVMContext &Context, const APInt &V)
static ConstantInt * get (IntegerType *Ty, StringRef Str, uint8_t radix)
static Constant * get (Type *Ty, const APInt &V)
static bool isValueValidForType (Type *Ty, uint64_t V)
Determine if the value is in range for the given type.
static bool isValueValidForType (Type *Ty, int64_t V)
static bool classof (const Value *V)
Methods to support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::Constant
static bool classof (const Value *V)
static Constant * getNullValue (Type *Ty)
static Constant * getAllOnesValue (Type *Ty)
Get the all ones value.
static Constant * getIntegerValue (Type *Ty, const APInt &V)
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Protected Member Functions
void * operator new (size_t s)
Protected Member Functions inherited from llvm::Constant
Constant (Type *ty, ValueTy vty, Use *Ops, unsigned NumOps)
void destroyConstantImpl ()
Protected Member Functions inherited from llvm::User
void * operator new (size_t s, unsigned Us)
User (Type *ty, unsigned vty, Use *OpList, unsigned NumOps)
Use * allocHungoffUses (unsigned) const
void dropHungoffUses ()
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
virtual void printCustom (raw_ostream &O) const
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Additional Inherited Members
Public Types inherited from llvm::Constant
enum PossibleRelocationsTy { NoRelocation = 0, LocalRelocation = 1, GlobalRelocations = 2 }
Public Types inherited from llvm::User
typedef Use * op_iterator
typedef const Use * const_op_iterator
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal, BasicBlockVal, FunctionVal, GlobalAliasVal,
GlobalVariableVal, UndefValueVal, BlockAddressVal, ConstantExprVal,
ConstantAggregateZeroVal, ConstantDataArrayVal, ConstantDataVectorVal, ConstantIntVal,
ConstantFPVal, ConstantArrayVal, ConstantStructVal, ConstantVectorVal,
ConstantPointerNullVal, MDNodeVal, MDStringVal, InlineAsmVal,
PseudoSourceValueVal, FixedStackPseudoSourceValueVal, InstructionVal, ConstantFirstVal = FunctionVal,
ConstantLastVal = ConstantPointerNullVal
}
typedef value_use_iterator< User > use_iterator
typedef value_use_iterator< const User > const_use_iterator
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::User
Use * OperandList
unsigned NumOperands
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Detailed Description
Class for constant integers.
This is the shared class of boolean and integer constants. This class represents both boolean and integral constants.
Definition at line 51 of file Constants.h.
Member Function Documentation
static bool llvm::ConstantInt::classof (const Value * V) inline static
Methods to support type inquiry through isa, cast, and dyn_cast.
Definition at line 223 of file Constants.h.
References llvm::Value::ConstantIntVal, and llvm::Value::getValueID().
bool llvm::ConstantInt::equalsInt (uint64_t V) const inline
Determine if this constant's value is same as an unsigned char.
A helper method that can be used to determine if the constant contained within is equal to a constant. This only works for very small values, because this is all that can be represented with all types.
Definition at line 132 of file Constants.h.
Referenced by areAllUsesIn().
Constant * ConstantInt::get (Type * Ty, uint64_t V, bool isSigned = false) static
If Ty is a vector type, return a Constant with a splat of the given value. Otherwise return a ConstantInt for the given value.
Definition at line 492 of file Constants.cpp.
References llvm::Type::getScalarType(), and llvm::ConstantVector::getSplat().
Referenced by llvm::Module::addModuleFlag(), AddOne(), AddWithOverflow(), AnalyzeLoadFromClobberingMemInst(), BitCastConstantVector(), llvm::X86TargetLowering::BuildFILD(), checkInterfaceFunction(), CoerceAvailableValueToLoadType(), CollectInsertionElements(), CollectShuffleElements(), CollectSingleShuffleElements(), CollectSubexprs(), CommitValueTo(), llvm::InstCombiner::commonShiftTransforms(), llvm::ObjectSizeOffsetEvaluator::compute(), llvm::ComputeMultiple(), computePointerICmp(), ConnectProlog(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCall(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCompareInstruction(), ConstantFoldConvertToInt(), ConstantFoldGetElementPtrImpl(), llvm::ConstantFoldInsertElementInstruction(), llvm::ConstantFoldInstOperands(), llvm::ConstantFoldLoadFromConstPtr(), llvm::ConstantFoldSelectInstruction(), llvm::ConstantFoldShuffleVectorInstruction(), convertMemSetToLoop(), ConvertShiftToMul(), ConvertToSInt(), convertTransferToLoop(), llvm::IRBuilder< true, TargetFolder >::CreateAnd(), createAndInstr(), llvm::DIBuilder::createArrayType(), llvm::DIBuilder::createArtificialType(), llvm::IRBuilder< true, TargetFolder >::CreateAShr(), llvm::DIBuilder::createBasicType(), llvm::MDBuilder::createBranchWeights(), llvm::DIBuilder::createClassType(), llvm::DIBuilder::createCompileUnit(), llvm::DIBuilder::createComplexVariable(), llvm::IRBuilder< true, TargetFolder >::CreateConstGEP1_32(), llvm::IRBuilder< true, TargetFolder >::CreateConstGEP1_64(), llvm::IRBuilder< true, TargetFolder >::CreateConstGEP2_32(), llvm::IRBuilder< true, TargetFolder >::CreateConstGEP2_64(), llvm::IRBuilder< true, TargetFolder >::CreateConstInBoundsGEP1_32(), llvm::IRBuilder< true, TargetFolder >::CreateConstInBoundsGEP1_64(), llvm::IRBuilder< true, TargetFolder >::CreateConstInBoundsGEP2_32(), llvm::IRBuilder< true, TargetFolder >::CreateConstInBoundsGEP2_64(), llvm::DIBuilder::createEnumerationType(), llvm::DIBuilder::createEnumerator(), llvm::DIBuilder::createForwardDecl(), llvm::DIBuilder::createFriend(), llvm::DIBuilder::createFunction(), llvm::IRBuilder< true, TargetFolder >::CreateGlobalStringPtr(), llvm::DIBuilder::createGlobalVariable(), llvm::DIBuilder::createImportedDeclaration(), createImportedModule(), llvm::DIBuilder::createInheritance(), llvm::DIBuilder::createLexicalBlock(), llvm::DIBuilder::createLocalVariable(), llvm::createLoopSimplifyPass(), llvm::createLoopVectorizePass(), llvm::IRBuilder< true, TargetFolder >::CreateLShr(), createMalloc(), llvm::DIBuilder::createMemberPointerType(), llvm::DIBuilder::createMemberType(), llvm::DIBuilder::createMethod(), llvm::DIBuilder::createNameSpace(), llvm::createNVVMReflectPass(), llvm::DIBuilder::createObjCIVar(), llvm::DIBuilder::createObjCProperty(), llvm::DIBuilder::createObjectPointerType(), llvm::IRBuilder< true, TargetFolder >::CreateOr(), llvm::DIBuilder::createPointerType(), createPrivateNonConstGlobalForString(), CreatePrologue(), llvm::DIBuilder::createQualifiedType(), llvm::MDBuilder::createRange(), llvm::DIBuilder::createReferenceType(), llvm::IRBuilder< true, TargetFolder >::CreateShl(), llvm::createSjLjEHPreparePass(), llvm::DIBuilder::createStaticMemberType(), llvm::DIBuilder::createStaticVariable(), llvm::DIBuilder::createStructType(), llvm::DIBuilder::createSubroutineType(), llvm::MDBuilder::createTBAANode(), llvm::MDBuilder::createTBAAScalarTypeNode(), llvm::MDBuilder::createTBAAStructNode(), llvm::MDBuilder::createTBAAStructTagNode(), llvm::MDBuilder::createTBAAStructTypeNode(), llvm::DIBuilder::createTemplateTypeParameter(), llvm::DIBuilder::createTypedef(), llvm::DIBuilder::createUnionType(), llvm::DIBuilder::createUnspecifiedType(), llvm::IRBuilder< true, TargetFolder >::CreateVectorSplat(), llvm::DIBuilder::createVectorType(), llvm::createXCoreISelDag(), llvm::IRBuilder< true, TargetFolder >::CreateXor(), cse(), decomposeBitTestICmp(), DecomposeSimpleLinearExpr(), deleteIfDeadInstruction(), dyn_castFoldableMul(), dyn_castNotVal(), llvm::EmitFWrite(), llvm::EmitGEPOffset(), llvm::Thumb2RegisterInfo::emitLoadConstPool(), llvm::Thumb1RegisterInfo::emitLoadConstPool(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), emitPostSt(), llvm::EmitStrChr(), EvaluateConstantChrecAtConstant(), EvaluateGEPOffsetExpression(), ExpandUnalignedLoad(), ExtractConstantBytes(), FactorOutConstant(), llvm::FastISel::FastEmit_ri_(), llvm::CodeExtractor::findInputsOutputs(), FindPhiPredForUseInBlock(), llvm::InstCombiner::FoldAndOfFCmps(), llvm::InstCombiner::FoldAndOfICmps(), FoldBitCast(), llvm::InstCombiner::FoldCmpLoadFromIndexedGlobal(), llvm::InstCombiner::FoldICmpAddOpCst(), llvm::InstCombiner::FoldICmpShrCst(), FoldOperationIntoSelectOperand(), llvm::InstCombiner::FoldOrOfFCmps(), FoldReinterpretLoadFromConstPtr(), foldSelectICmpAnd(), llvm::InstCombiner::FoldShiftByConstant(), foldUDivNegCst(), foldUDivPow2Cst(), foldUDivShl(), FunctionNumber(), GatherConstantCompares(), genLoopLimit(), getAISize(), llvm::ConstantExpr::getAlignOf(), llvm::Constant::getAllOnesValue(), llvm::DebugLoc::getAsMDNode(), llvm::ConstantExpr::getBinOpIdentity(), GetCaseResults(), getComparePred(), llvm::LazyValueInfo::getConstant(), llvm::SelectionDAG::getConstant(), llvm::ScalarEvolution::getConstant(), GetConstantInt(), llvm::LazyValueInfo::getConstantOnEdge(), getEdgeValueLocal(), llvm::ConstantDataSequential::getElementAsConstant(), getFalse(), getFoldedAlignOf(), getFoldedSizeOf(), getFunctionName(), getGEPInductionOperand(), llvm::getICmpValue(), llvm::IRBuilderBase::getInt(), llvm::IRBuilderBase::getInt1(), llvm::IRBuilderBase::getInt16(), llvm::IRBuilderBase::getInt32(), llvm::IRBuilderBase::getInt64(), llvm::IRBuilderBase::getInt8(), llvm::Constant::getIntegerValue(), getKnownConstant(), getLogBase2Vector(), GetMemInstValueForLoad(), llvm::MDNode::getMostGenericTBAA(), llvm::ScalarEvolution::getMulExpr(), llvm::Constant::getNullValue(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), llvm::ConstantExpr::getOffsetOf(), getOne(), llvm::DIBuilder::getOrCreateSubrange(), llvm::FastISel::getRegForValue(), GetSelectFoldableConstant(), GetShiftedValue(), llvm::ScalarEvolution::getSignedRange(), llvm::ConstantExpr::getSizeOf(), llvm::ScalarEvolution::getSMaxExpr(), GetTagConstant(), getTrue(), llvm::ScalarEvolution::getUMaxExpr(), getUnconditionalBrDisp(), getVLDSTRegisterUpdateOpcode(), GlobalWasGeneratedByAsan(), HandleByValArgument(), llvm::SCEVExpander::hoistIVInc(), INITIALIZE_PASS(), llvm::InlineFunction(), llvm::DIBuilder::insertDbgValueIntrinsic(), insertVector(), InstallGlobalCtors(), llvm::isBytewiseValue(), isCompatibleAggregate(), isInterestingMemoryAccess(), IsNonLocalValue(), isOnlyReachableViaThisEdge(), isPossibleSelfRead(), llvm::FastISel::leaveLocalValueArea(), llvm::linkShadowStackGC(), LLVMConstInt(), LLVMConstIntOfArbitraryPrecision(), LLVMConstIntOfString(), LLVMConstIntOfStringAndSize(), LowerBSWAP(), LowerCTLZ(), LowerCTPOP(), llvm::IntrinsicLowering::LowerIntrinsicCall(), LowerSIGN_EXTEND_AVX512(), MarkBlocksLiveIn(), MarkIndicesSafe(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::ObjectSizeOffsetEvaluator::ObjectSizeOffsetEvaluator(), OptimizeCmpExpression(), llvm::BitcodeReader::ParseTriple(), PerformHeapAllocSRoA(), PickMostRelevantLoop(), PoisonShadowPartialRightRedzone(), ReadWideAPInt(), reduceToSingleValueType(), llvm::replaceDbgDeclareForAlloca(), llvm::ARMTargetLowering::ReplaceNodeResults(), ReplaceUsesOfWith(), llvm::JIT::runFunction(), llvm::NVPTXLowerAggrCopies::runOnFunction(), shouldMergeGEPs(), ShrinkDemandedConstant(), SimplifyCondBranchToCondBranch(), SimplifyDiv(), SimplifyFCmpInst(), SimplifyICmpInst(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), SolveQuadraticEquation(), SplitAddRecs(), StackMallocSizeClass(), stripAndComputeConstantOffsets(), SubOne(), SubWithOverflow(), SwitchToLookupTable(), SymbolicallyEvaluateBinop(), SymbolicallyEvaluateGEP(), tryMergeRange(), TryToOptimizeStoreOfMallocToGlobal(), TryToShrinkGlobalToBoolean(), TurnSwitchRangeIntoICmp(), llvm::UnrollRuntimeLoopProlog(), llvm::UpgradeIntrinsicCall(), useSinCos(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAllocaInst(), llvm::ObjectSizeOffsetEvaluator::visitAllocaInst(), llvm::InstCombiner::visitAllocSite(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitSDiv(), llvm::InstCombiner::visitSelectInstWithICmp(), llvm::InstCombiner::visitSExt(), llvm::InstCombiner::visitShuffleVectorInst(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitTrunc(), llvm::InstCombiner::visitXor(), llvm::InstCombiner::visitZExt(), and llvm::BasicBlock::~BasicBlock().
ConstantInt * ConstantInt::get (IntegerType * Ty, uint64_t V, bool isSigned = false) static
Get a ConstantInt for a specific value.
Return a ConstantInt with the specified integer value for the specified type. If the type is wider than 64 bits, the value will be zero-extended to fit the type, unless isSigned is true, in which case the value will be interpreted as a 64-bit signed integer and sign-extended to fit the type.
Definition at line 502 of file Constants.cpp.
References llvm::IntegerType::getBitWidth(), and llvm::Type::getContext().
ConstantInt * ConstantInt::get (LLVMContext & Context, const APInt & V) static
Return a ConstantInt with the specified value and an implied Type. The type is the integer type that corresponds to the bit width of the value.
Definition at line 482 of file Constants.cpp.
References llvm::IntegerType::get(), llvm::APInt::getBitWidth(), and llvm::LLVMContext::pImpl.
ConstantInt * ConstantInt::get (IntegerType * Ty, StringRef Str, uint8_t radix) static
Return a ConstantInt constructed from the string strStart with the given radix.
Definition at line 527 of file Constants.cpp.
References llvm::IntegerType::getBitWidth(), and llvm::Type::getContext().
Constant * ConstantInt::get (Type * Ty, const APInt & V) static
If Ty is a vector type, return a Constant with a splat of the given value. Otherwise return a ConstantInt for the given value.
Definition at line 515 of file Constants.cpp.
References llvm::Type::getContext(), llvm::Type::getScalarType(), llvm::ConstantVector::getSplat(), and getType().
unsigned llvm::ConstantInt::getBitWidth () const inline
getBitWidth - Return the bitwidth of this constant.
Definition at line 110 of file Constants.h.
References llvm::APInt::getBitWidth().
Referenced by emitGlobalConstantLargeInt(), foldSelectICmpAnd(), llvm::SelectionDAG::getConstant(), MultiplyOverflows(), ProcessUGT_ADDCST_ADD(), SimplifyICmpInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), and llvm::InstCombiner::visitUDiv().
ConstantInt * ConstantInt::getFalse (LLVMContext & Context) static
Definition at line 445 of file Constants.cpp.
References get(), llvm::Type::getInt1Ty(), llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::TheFalseVal.
Referenced by llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCompareInstruction(), llvm::createCorrelatedValuePropagationPass(), FindMostPopularDest(), FunctionNumber(), getFalse(), llvm::IRBuilderBase::getFalse(), getKnownConstant(), HandleByValArgument(), isOnlyReachableViaThisEdge(), isTrivialLoopExitBlock(), operator new(), OptimizeGlobalAddressOfMalloc(), SimplifyFCmpInst(), SimplifyICmpInst(), llvm::ScalarEvolution::SimplifyICmpOperands(), TryToShrinkGlobalToBoolean(), TryToSimplifyUncondBranchWithICmpInIt(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitICmpInst(), and llvm::SelectionDAGBuilder::visitSwitchCase().
Constant * ConstantInt::getFalse (Type * Ty) static
Definition at line 464 of file Constants.cpp.
References llvm::dyn_cast(), llvm::Type::getContext(), llvm::SequentialType::getElementType(), getFalse(), llvm::VectorType::getNumElements(), llvm::ConstantVector::getSplat(), and llvm::Type::isIntegerTy().
uint64_t llvm::ConstantInt::getLimitedValue (uint64_t Limit = ~0ULL) const inline
Get the constant's value with a saturation limit.
getLimitedValue - If the value is smaller than the specified limit, return it, otherwise return the limit value. This causes the value to saturate to the limit.
Returns
the min of the value of the constant and the specified value
Definition at line 218 of file Constants.h.
References llvm::APInt::getLimitedValue().
Referenced by CanEvaluateShifted(), CanEvaluateShuffled(), dyn_castFoldableMul(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), llvm::InstCombiner::FoldICmpShrCst(), llvm::InstCombiner::FoldShiftByConstant(), getFCmpValue(), getMaxWeightFor(), isCompatibleAggregate(), reduceToSingleValueType(), AllocaSlices::SliceBuilder::SliceBuilder(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), and llvm::InstCombiner::visitUDiv().
int64_t llvm::ConstantInt::getSExtValue () const inline
Return the sign extended value.
Return the constant as a 64-bit integer value after it has been sign extended as appropriate for the type of this constant. Note that this method can assert if the value does not fit in 64 bits.
Definition at line 124 of file Constants.h.
References llvm::APInt::getSExtValue().
Referenced by canFoldIVIncExpr(), EvaluateGEPOffsetExpression(), getComparePred(), GetOffsetFromIndex(), llvm::ConstantSDNode::getSExtValue(), isAlwaysFoldable(), isIndexInRangeOfSequentialType(), OptimizeCmpExpression(), and X86ChooseCmpImmediateOpcode().
ConstantInt * ConstantInt::getSigned (IntegerType * Ty, int64_t V) static
Get a ConstantInt for a specific signed value.
Return a ConstantInt with the specified value for the specified type. The value V will be canonicalized to a an unsigned APInt. Accessing it with either getSExtValue() or getZExtValue() will yield a correctly sized and signed value for the type Ty.
Definition at line 507 of file Constants.cpp.
Referenced by llvm::InstCombiner::FoldOrOfICmps(), generateUnsignedDivisionCode(), getComparePred(), INITIALIZE_PASS(), insertFastDiv(), operator new(), llvm::InstCombiner::visitLShr(), and llvm::InstCombiner::visitOr().
Constant * ConstantInt::getSigned (Type * Ty, int64_t V) static
Definition at line 511 of file Constants.cpp.
ConstantInt * ConstantInt::getTrue (LLVMContext & Context) static
Definition at line 438 of file Constants.cpp.
References get(), llvm::Type::getInt1Ty(), llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::TheTrueVal.
Referenced by CloneLoop(), llvm::ComputeMaskedBits(), llvm::ConstantFoldCompareInstruction(), llvm::createCorrelatedValuePropagationPass(), llvm::SelectionDAGBuilder::EmitBranchForMergedCondition(), FindInitTrampoline(), FindLIVLoopCondition(), FindMostPopularDest(), FunctionNumber(), getFCmpValue(), getGEPInductionOperand(), getKnownConstant(), getTrue(), llvm::IRBuilderBase::getTrue(), isOnlyReachableViaThisEdge(), isTrivialLoopExitBlock(), operator new(), OptimizeGlobalAddressOfMalloc(), ReplaceUsesOfWith(), llvm::SelectionDAGBuilder::ShouldEmitAsBranches(), SimplifyFCmpInst(), SimplifyICmpInst(), TryToSimplifyUncondBranchWithICmpInIt(), TurnSwitchRangeIntoICmp(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitFree(), llvm::InstCombiner::visitICmpInst(), and llvm::SelectionDAGBuilder::visitSwitchCase().
Constant * ConstantInt::getTrue (Type * Ty) static
Definition at line 452 of file Constants.cpp.
References llvm::dyn_cast(), llvm::Type::getContext(), llvm::SequentialType::getElementType(), llvm::VectorType::getNumElements(), llvm::ConstantVector::getSplat(), getTrue(), and llvm::Type::isIntegerTy().
IntegerType* llvm::ConstantInt::getType () const inline
getType - Specialize the getType() method to always return an IntegerType, which reduces the amount of casting needed in parts of the compiler.
Definition at line 139 of file Constants.h.
References llvm::Value::getType(), and isValueValidForType().
Referenced by llvm::IRBuilderBase::CreateLifetimeEnd(), llvm::IRBuilderBase::CreateLifetimeStart(), emitGlobalConstantLargeInt(), llvm::InstCombiner::FoldAndOfICmps(), llvm::FoldBranchToCommonDest(), FoldCondBranchOnPHI(), llvm::InstCombiner::FoldICmpAddOpCst(), get(), GetConstantInt(), getFCmpValue(), llvm::SCEVConstant::getType(), llvm::ConstantExpr::getWithOperands(), INITIALIZE_PASS(), insertVector(), isContiguous(), isRunOfOnes(), reduceToSingleValueType(), ShrinkDemandedConstant(), SwitchToLookupTable(), tryMergeRange(), and llvm::InstCombiner::visitICmpInstWithInstAndIntCst().
const APInt& llvm::ConstantInt::getValue () const inline
Return the constant's value.
Return the constant as an APInt value reference. This allows clients to obtain a copy of the value, with all its precision in tact.
Definition at line 105 of file Constants.h.
Referenced by llvm::GEPOperator::accumulateConstantOffset(), llvm::CompileUnit::addConstantValue(), AddOne(), CanEvaluateShifted(), canFoldIVIncExpr(), CommitValueTo(), llvm::computeMaskedBitsLoad(), llvm::ComputeMultiple(), computePointerICmp(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldInsertElementInstruction(), llvm::ConstantFoldTerminator(), ConstantIntSortPredicate(), deleteIfDeadInstruction(), DemandedBitsLHSMask(), emitDebugValueComment(), emitGlobalConstantLargeInt(), EvaluateExpression(), ExtractBranchMetadata(), FactorOutConstant(), llvm::InstCombiner::FoldAndOfICmps(), llvm::InstCombiner::FoldICmpAddOpCst(), llvm::InstCombiner::FoldICmpDivCst(), foldLogOpOfMaskedICmps(), llvm::InstCombiner::FoldOrOfICmps(), llvm::InstCombiner::FoldOrWithConstants(), foldSelectICmpAnd(), GatherConstantCompares(), gcd(), llvm::ConstantSDNode::getAPIntValue(), GetBranchWeights(), GetCaseResults(), llvm::SelectionDAG::getConstant(), getConstantPart(), getEdgeValueLocal(), getExactSDiv(), getFCmpValue(), llvm::MDNode::getMostGenericRange(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), getPointerOperand(), llvm::LazyValueInfo::getPredicateOnEdge(), GetShiftedValue(), llvm::ScalarEvolution::getSmallConstantTripCount(), llvm::ScalarEvolution::getSmallConstantTripMultiple(), getTypeOfMaskedICmp(), HasAddOverflow(), HasSubOverflow(), INITIALIZE_PASS(), isAlwaysFoldable(), isContiguous(), isDereferenceablePointer(), llvm::ConstantExpr::isGEPWithNoNotionalOverIndexing(), isHighOnes(), isIndexInRangeOfSequentialType(), isLikelyComplexAddressComputation(), llvm::SCEV::isNonConstantNegative(), llvm::SCEVUnknown::isOffsetOf(), isRemainderZero(), isRunOfOnes(), isSignBitCheck(), isSimpleLoadStore(), llvm::FullDependence::isSplitable(), isStridedPtr(), MaintainNoSignedWrap(), minAPInt(), MultiplyOverflows(), ProcessUGT_ADDCST_ADD(), sdiv(), ShrinkDemandedConstant(), SimplifyICmpInst(), AllocaSlices::SliceBuilder::SliceBuilder(), SolveQuadraticEquation(), srem(), SubOne(), SwitchToLookupTable(), tryMergeRange(), ValuesOverlap(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAnd(), llvm::ObjectSizeOffsetVisitor::visitCallSite(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitSelectInstWithICmp(), llvm::InstCombiner::visitSub(), and llvm::InstCombiner::visitXor().
uint64_t llvm::ConstantInt::getZExtValue () const inline
Return the zero extended value.
Return the constant as a 64-bit unsigned integer value after it has been zero extended as appropriate for the type of this constant. Note that this method can assert if the value does not fit in 64 bits.
Definition at line 116 of file Constants.h.
References llvm::APInt::getZExtValue().
Referenced by llvm::GEPOperator::accumulateConstantOffset(), AnalyzeLoadFromClobberingMemInst(), cacheAnnotationFromMD(), CanEvaluateShifted(), llvm::CloneFunction(), CollectInsertionElements(), CollectSubexprs(), CommitValueTo(), llvm::ComputeMultiple(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::MachineInstr::emitError(), EvaluateGEPOffsetExpression(), EvaluateStoreInto(), ExpandUnalignedLoad(), ExtractConstantBytes(), llvm::InstCombiner::FoldCmpLoadFromIndexedGlobal(), FoldCondBranchOnPHI(), llvm::InstCombiner::FoldShiftByConstant(), getArrayElements(), getComparePred(), llvm::getConstantStringInfo(), getMemCmpLoad(), llvm::Module::getModuleFlagsMetadata(), GetOffsetFromIndex(), GetShiftedValue(), llvm::ScalarEvolution::getSmallConstantTripCount(), llvm::ScalarEvolution::getSmallConstantTripMultiple(), getTruncatedArgReg(), llvm::ConstantSDNode::getZExtValue(), llvm::CompositeType::indexValid(), INITIALIZE_PASS(), isAlwaysFoldable(), isCompatibleAggregate(), isDereferenceablePointer(), isGEPKnownNonNull(), llvm::ConstantExpr::isGEPWithNoNotionalOverIndexing(), isOnlyReachableViaThisEdge(), isSimpleLoadStore(), IsUserOfGlobalSafeForSRA(), matchPairwiseReduction(), matchVectorSplittingReduction(), OptimizeGlobalAddressOfMalloc(), RemoveNestAttribute(), ShrinkDemandedConstant(), tryToMakeAllocaBePromotable(), llvm::Interpreter::visitAllocaInst(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), and llvm::InstCombiner::visitTrunc().
bool llvm::ConstantInt::isMaxValue (bool isSigned) const inline
Determine if the value is maximal.
This function will return true iff this constant represents the largest value that may be represented by the constant's type.
Returns
true iff this is the largest value that may be represented by this type.
Definition at line 185 of file Constants.h.
References llvm::APInt::isMaxSignedValue(), and llvm::APInt::isMaxValue().
Referenced by isSignBitCheck().
bool llvm::ConstantInt::isMinusOne () const inline
Determine if the value is all ones.
This function will return true iff every bit in this constant is set to true.
Returns
true iff this constant's bits are all set to true.
Definition at line 176 of file Constants.h.
References llvm::APInt::isAllOnesValue().
bool llvm::ConstantInt::isMinValue (bool isSigned) const inline
Determine if the value is minimal.
This function will return true iff this constant represents the smallest value that may be represented by this constant's type.
Returns
true if this is the smallest value that may be represented by this type.
Definition at line 197 of file Constants.h.
References llvm::APInt::isMinSignedValue(), and llvm::APInt::isMinValue().
bool llvm::ConstantInt::isNegative () const inline
Definition at line 155 of file Constants.h.
References llvm::APInt::isNegative().
Referenced by llvm::InstCombiner::FoldICmpDivCst(), HasAddOverflow(), HasSubOverflow(), tryToMakeAllocaBePromotable(), and llvm::InstCombiner::visitICmpInstWithInstAndIntCst().
bool llvm::ConstantInt::isOne () const inline
Determine if the value is one.
This is just a convenience method to make client code smaller for a common case. It also correctly performs the comparison without the potential for an assertion from getZExtValue().
Definition at line 168 of file Constants.h.
Referenced by llvm::ConstantFoldCastInstruction(), llvm::createCorrelatedValuePropagationPass(), deleteIfDeadInstruction(), llvm::FoldBranchToCommonDest(), llvm::InstCombiner::FoldICmpDivCst(), getMaxWeightFor(), isAlwaysFoldable(), llvm::ConstantSDNode::isOne(), IsOneHotValue(), isSelect01(), and isSignTest().
bool ConstantInt::isValueValidForType (Type * Ty, uint64_t V) static
Determine if the value is in range for the given type.
This static method returns true if the type Ty is big enough to represent the value V. This can be used to avoid having the get method assert when V is larger than Ty can represent. Note that there are two versions of this method, one for unsigned and one for signed integers. Although ConstantInt canonicalizes everything to an unsigned integer, the signed version avoids callers having to convert a signed quantity to the appropriate unsigned type before calling the method.
Returns
true if V is a valid value for type Ty
Definition at line 1159 of file Constants.cpp.
References llvm::Type::getIntegerBitWidth(), llvm::Type::isIntegerTy(), and ll.
Referenced by getType(), llvm::X86TargetLowering::LowerAsmOperandForConstraint(), and llvm::ConstantFP::operator new().
bool ConstantInt::isValueValidForType (Type * Ty, int64_t V) static
Definition at line 1169 of file Constants.cpp.
References llvm::Type::getIntegerBitWidth(), llvm::Type::isIntegerTy(), and ll.
bool llvm::ConstantInt::isZero () const inline
This is just a convenience method to make client code smaller for a common code. It also correctly performs the comparison without the potential for an assertion from getZExtValue().
Definition at line 160 of file Constants.h.
Referenced by llvm::GEPOperator::accumulateConstantOffset(), deleteIfDeadInstruction(), evaluateFCmpRelation(), EvaluateGEPOffsetExpression(), evaluateICmpRelation(), FactorOutConstant(), FindMostPopularDest(), llvm::InstCombiner::FoldAndOfICmps(), llvm::InstCombiner::FoldICmpAddOpCst(), llvm::InstCombiner::FoldICmpDivCst(), llvm::InstCombiner::FoldOrOfICmps(), foldSelectICmpAnd(), llvm::getConstantStringInfo(), getFCmpValue(), getMaxWeightFor(), getMergedGlobalExpr(), GetOffsetFromIndex(), getTruncatedArgReg(), getTypeOfMaskedICmp(), InstructionDereferencesPointer(), isDereferenceablePointer(), isSelect01(), isSignBitCheck(), isSignTest(), isSimpleEnoughPointerToCommit(), llvm::FastISel::leaveLocalValueArea(), llvm::SCEVExpander::replaceCongruentIVs(), SimplifyICmpInst(), llvm::InstCombiner::visitAllocSite(), and llvm::InstCombiner::visitICmpInstWithInstAndIntCst().
void* llvm::ConstantInt::operator new (size_t s) inline protected
Definition at line 59 of file Constants.h.
References getFalse(), getSigned(), getTrue(), and s.
bool llvm::ConstantInt::uge (uint64_t Num) const inline
Determine if the value is greater or equal to the given number.
This function will return true iff this constant represents a value with active bits bigger than 64 bits or a value greater than the given uint64_t value.
Returns
true iff this constant is greater or equal to the given number.
Definition at line 209 of file Constants.h.
References llvm::APInt::getActiveBits(), and llvm::APInt::getZExtValue().
Referenced by llvm::InstCombiner::FoldShiftByConstant(), isSimpleLoadStore(), and llvm::InstCombiner::visitICmpInstWithInstAndIntCst().
The documentation for this class was generated from the following files:
Constants.h
Constants.cpp