LLVM: llvm::VAStartInst Class Reference
LLVM API Documentation
llvm::VAStartInst Class Reference
#include <IntrinsicInst.h>
Public Member Functions
Value * getArgList () const
Public Member Functions inherited from llvm::IntrinsicInst
Intrinsic::ID getIntrinsicID () const
Public Member Functions inherited from llvm::CallInst
~CallInst ()
bool isTailCall () const
void setTailCall (bool isTC=true)
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Value)
Provide fast operand accessors.
unsigned getNumArgOperands () const
Value * getArgOperand (unsigned i) const
void setArgOperand (unsigned i, Value *v)
CallingConv::ID getCallingConv () const
void setCallingConv (CallingConv::ID CC)
const AttributeSet & getAttributes () const
void setAttributes (const AttributeSet &Attrs)
void addAttribute (unsigned i, Attribute::AttrKind attr)
addAttribute - adds the attribute to the list of attributes.
void removeAttribute (unsigned i, Attribute attr)
removeAttribute - removes the attribute from the list of attributes.
bool hasFnAttr (Attribute::AttrKind A) const
Determine whether this call has the given attribute.
bool paramHasAttr (unsigned i, Attribute::AttrKind A) const
Determine whether the call or the callee has the given attributes.
unsigned getParamAlignment (unsigned i) const
Extract the alignment for a call or parameter (0=unknown).
bool isNoBuiltin () const
Return true if the call should not be treated as a call to a builtin.
bool isNoInline () const
Return true if the call should not be inlined.
void setIsNoInline ()
bool canReturnTwice () const
Return true if the call can return twice.
void setCanReturnTwice ()
bool doesNotAccessMemory () const
Determine if the call does not access memory.
void setDoesNotAccessMemory ()
bool onlyReadsMemory () const
Determine if the call does not access or only reads memory.
void setOnlyReadsMemory ()
bool doesNotReturn () const
Determine if the call cannot return.
void setDoesNotReturn ()
bool doesNotThrow () const
Determine if the call cannot unwind.
void setDoesNotThrow ()
bool cannotDuplicate () const
Determine if the call cannot be duplicated.
void setCannotDuplicate ()
bool hasStructRetAttr () const
Determine if the call returns a structure through first pointer argument.
bool hasByValArgument () const
Determine if any call argument is an aggregate passed by value.
Function * getCalledFunction () const
const Value * getCalledValue () const
Value * getCalledValue ()
void setCalledFunction (Value *Fn)
setCalledFunction - Set the function called.
bool isInlineAsm () const
isInlineAsm - Check if this call is an inline asm statement.
Public Member Functions inherited from llvm::Instruction
~Instruction ()
Instruction * use_back ()
const Instruction * use_back () const
const BasicBlock * getParent () const
BasicBlock * getParent ()
void removeFromParent ()
void eraseFromParent ()
void insertBefore (Instruction *InsertPos)
void insertAfter (Instruction *InsertPos)
void moveBefore (Instruction *MovePos)
unsigned getOpcode () const
getOpcode() returns a member of one of the enums like Instruction::Add.
const char * getOpcodeName () const
bool isTerminator () const
bool isBinaryOp () const
bool isShift ()
bool isCast () const
bool isLogicalShift () const
bool isArithmeticShift () const
isArithmeticShift - Return true if this is an arithmetic shift right.
bool hasMetadata () const
bool hasMetadataOtherThanDebugLoc () const
MDNode * getMetadata (unsigned KindID) const
MDNode * getMetadata (StringRef Kind) const
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
void getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
void setMetadata (unsigned KindID, MDNode *Node)
void setMetadata (StringRef Kind, MDNode *Node)
void setDebugLoc (const DebugLoc &Loc)
setDebugLoc - Set the debug location information for this instruction.
const DebugLoc & getDebugLoc () const
getDebugLoc - Return the debug location for this node as a DebugLoc.
void setHasUnsafeAlgebra (bool B)
void setHasNoNaNs (bool B)
void setHasNoInfs (bool B)
void setHasNoSignedZeros (bool B)
void setHasAllowReciprocal (bool B)
void setFastMathFlags (FastMathFlags FMF)
bool hasUnsafeAlgebra () const
Determine whether the unsafe-algebra flag is set.
bool hasNoNaNs () const
Determine whether the no-NaNs flag is set.
bool hasNoInfs () const
Determine whether the no-infs flag is set.
bool hasNoSignedZeros () const
Determine whether the no-signed-zeros flag is set.
bool hasAllowReciprocal () const
Determine whether the allow-reciprocal flag is set.
FastMathFlags getFastMathFlags () const
void copyFastMathFlags (const Instruction *I)
Copy I's fast-math flags.
bool isAssociative () const
bool isCommutative () const
bool isIdempotent () const
bool isNilpotent () const
bool mayWriteToMemory () const
bool mayReadFromMemory () const
bool mayReadOrWriteMemory () const
bool mayThrow () const
bool mayReturn () const
bool mayHaveSideEffects () const
Instruction * clone () const
bool isIdenticalTo (const Instruction *I) const
bool isIdenticalToWhenDefined (const Instruction *I) const
bool isSameOperationAs (const Instruction *I, unsigned flags=0) const
Determine if one instruction is the same operation as another.
bool isUsedOutsideOfBlock (const BasicBlock *BB) const
Public Member Functions inherited from llvm::User
~User ()
void operator delete (void *Usr)
operator delete - free memory allocated for User and Use objects
void operator delete (void *, unsigned)
placement delete - required by std, but never called.
void operator delete (void *, unsigned, bool)
placement delete - required by std, but never called.
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
void dropAllReferences ()
void replaceUsesOfWith (Value *From, Value *To)
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
dump - Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O, AssemblyAnnotationWriter *AAW=0) const
Type * getType () const
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
void setName (const Twine &Name)
void takeName (Value *V)
void replaceAllUsesWith (Value *V)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
User * use_back ()
const User * use_back () const
bool hasOneUse () const
bool hasNUses (unsigned N) const
bool hasNUsesOrMore (unsigned N) const
bool isUsedInBasicBlock (const BasicBlock *BB) const
unsigned getNumUses () const
void addUse (Use &U)
unsigned getValueID () const
unsigned getRawSubclassOptionalData () const
void clearSubclassOptionalData ()
bool hasSameSubclassOptionalData (const Value *V) const
void intersectOptionalDataWith (const Value *V)
bool hasValueHandle () const
Value * stripPointerCasts ()
Strips off any unneeded pointer casts, all-zero GEPs and aliases from the specified value, returning the original uncasted value.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strips off any unneeded pointer casts and all-zero GEPs from the specified value, returning the original uncasted value.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strips off unneeded pointer casts and all-constant GEPs from the specified value, returning the original pointer value.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Strips like stripInBoundsConstantOffsets but also accumulates the constant offset stripped.
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strips off unneeded pointer casts and any in-bounds offsets from the specified value, returning the original pointer value.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer () const
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Public Member Functions inherited from llvm::ilist_node< Instruction >
Instruction * getPrevNode ()
Get the previous node, or 0 for the list head.
const Instruction * getPrevNode () const
Get the previous node, or 0 for the list head.
Instruction * getNextNode ()
Get the next node, or 0 for the list tail.
const Instruction * getNextNode () const
Get the next node, or 0 for the list tail.
Static Public Member Functions
static bool classof (const IntrinsicInst *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::IntrinsicInst
static bool classof (const CallInst *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::CallInst
static CallInst * Create (Value *Func, ArrayRef< Value * > Args, const Twine &NameStr="", Instruction *InsertBefore=0)
static CallInst * Create (Value *Func, ArrayRef< Value * > Args, const Twine &NameStr, BasicBlock *InsertAtEnd)
static CallInst * Create (Value *F, const Twine &NameStr="", Instruction *InsertBefore=0)
static CallInst * Create (Value *F, const Twine &NameStr, BasicBlock *InsertAtEnd)
static Instruction * CreateMalloc (Instruction *InsertBefore, Type *IntPtrTy, Type *AllocTy, Value *AllocSize, Value *ArraySize=0, Function *MallocF=0, const Twine &Name="")
static Instruction * CreateMalloc (BasicBlock *InsertAtEnd, Type *IntPtrTy, Type *AllocTy, Value *AllocSize, Value *ArraySize=0, Function *MallocF=0, const Twine &Name="")
static Instruction * CreateFree (Value *Source, Instruction *InsertBefore)
CreateFree - Generate the IR for a call to the builtin free function.
static Instruction * CreateFree (Value *Source, BasicBlock *InsertAtEnd)
static bool classof (const Instruction *I)
static bool classof (const Value *V)
Static Public Member Functions inherited from llvm::Instruction
static const char * getOpcodeName (unsigned OpCode)
static bool isTerminator (unsigned OpCode)
static bool isBinaryOp (unsigned Opcode)
static bool isShift (unsigned Opcode)
Determine if the Opcode is one of the shift instructions.
static bool isCast (unsigned OpCode)
Determine if the OpCode is one of the CastInst instructions.
static bool isAssociative (unsigned op)
static bool isCommutative (unsigned op)
static bool isIdempotent (unsigned op)
static bool isNilpotent (unsigned op)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Additional Inherited Members
Public Types inherited from llvm::Instruction
enum OperationEquivalenceFlags { CompareIgnoringAlignment = 1<<0, CompareUsingScalarTypes = 1<<1 }
enum TermOps
enum BinaryOps
enum MemoryOps
enum CastOps
enum OtherOps
Public Types inherited from llvm::User
typedef Use * op_iterator
typedef const Use * const_op_iterator
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal, BasicBlockVal, FunctionVal, GlobalAliasVal,
GlobalVariableVal, UndefValueVal, BlockAddressVal, ConstantExprVal,
ConstantAggregateZeroVal, ConstantDataArrayVal, ConstantDataVectorVal, ConstantIntVal,
ConstantFPVal, ConstantArrayVal, ConstantStructVal, ConstantVectorVal,
ConstantPointerNullVal, MDNodeVal, MDStringVal, InlineAsmVal,
PseudoSourceValueVal, FixedStackPseudoSourceValueVal, InstructionVal, ConstantFirstVal = FunctionVal,
ConstantLastVal = ConstantPointerNullVal
}
typedef value_use_iterator< User > use_iterator
typedef value_use_iterator< const User > const_use_iterator
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
Protected Member Functions inherited from llvm::CallInst
virtual CallInst * clone_impl () const
Protected Member Functions inherited from llvm::Instruction
void setInstructionSubclassData (unsigned short D)
unsigned getSubclassDataFromInstruction () const
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, Instruction *InsertBefore=0)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, BasicBlock *InsertAtEnd)
Protected Member Functions inherited from llvm::User
void * operator new (size_t s, unsigned Us)
User (Type *ty, unsigned vty, Use *OpList, unsigned NumOps)
Use * allocHungoffUses (unsigned) const
void dropHungoffUses ()
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
virtual void printCustom (raw_ostream &O) const
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Member Functions inherited from llvm::ilist_node< Instruction >
ilist_node ()
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::User
Use * OperandList
unsigned NumOperands
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Detailed Description
VAStartInst - This represents the llvm.va_start intrinsic.
Definition at line 273 of file IntrinsicInst.h.
Member Function Documentation
static bool llvm::VAStartInst::classof (const IntrinsicInst * I) inline static
Definition at line 275 of file IntrinsicInst.h.
References llvm::IntrinsicInst::getIntrinsicID(), and llvm::Intrinsic::vastart.
static bool llvm::VAStartInst::classof (const Value * V) inline static
Definition at line 278 of file IntrinsicInst.h.
References llvm::IntrinsicInst::classof().
Value* llvm::VAStartInst::getArgList () const inline
Definition at line 282 of file IntrinsicInst.h.
References llvm::CallInst::getArgOperand().
The documentation for this class was generated from the following file:
IntrinsicInst.h