LLVM: llvm::AliasSet Class Reference
LLVM API Documentation
llvm::AliasSet Class Reference
#include <AliasSetTracker.h>
Classes
class iterator
Define an iterator for alias sets... this is just a forward iterator.
Public Member Functions
bool isRef () const
Accessors...
bool isMod () const
bool isMustAlias () const
bool isMayAlias () const
bool isVolatile () const
bool isForwardingAliasSet () const
void mergeSetIn (AliasSet &AS, AliasSetTracker &AST)
iterator begin () const
iterator end () const
bool empty () const
void print (raw_ostream &OS) const
void dump () const
bool aliasesPointer (const Value *Ptr, uint64_t Size, const MDNode *TBAAInfo, AliasAnalysis &AA) const
bool aliasesUnknownInst (Instruction *Inst, AliasAnalysis &AA) const
Public Member Functions inherited from llvm::ilist_node< AliasSet >
AliasSet * getPrevNode ()
Get the previous node, or 0 for the list head.
const AliasSet * getPrevNode () const
Get the previous node, or 0 for the list head.
AliasSet * getNextNode ()
Get the next node, or 0 for the list tail.
const AliasSet * getNextNode () const
Get the next node, or 0 for the list tail.
Friends
class AliasSetTracker
struct ilist_sentinel_traits< AliasSet >
Additional Inherited Members
Protected Member Functions inherited from llvm::ilist_node< AliasSet >
ilist_node ()
Detailed Description
Definition at line 35 of file AliasSetTracker.h.
Member Function Documentation
bool AliasSet::aliasesPointer (const Value * Ptr, uint64_t Size, const MDNode * TBAAInfo, AliasAnalysis & AA) const
aliasesPointer - Return true if the specified pointer "may" (or must) alias one of the members in the set.
Definition at line 143 of file AliasSetTracker.cpp.
References llvm::AliasAnalysis::alias(), begin(), end(), llvm::AliasAnalysis::getModRefInfo(), i, I, and llvm::AliasAnalysis::NoModRef.
bool AliasSet::aliasesUnknownInst (Instruction * Inst, AliasAnalysis & AA) const
Definition at line 179 of file AliasSetTracker.cpp.
References begin(), C1, end(), llvm::AliasAnalysis::getModRefInfo(), i, I, llvm::Instruction::mayReadOrWriteMemory(), and llvm::AliasAnalysis::NoModRef.
iterator llvm::AliasSet::begin () const inline
Definition at line 175 of file AliasSetTracker.h.
Referenced by llvm::AliasSetTracker::add(), aliasesPointer(), aliasesUnknownInst(), llvm::AliasSetTracker::clear(), llvm::AliasSetTracker::containsPointer(), llvm::createLICMPass(), llvm::AliasSetTracker::deleteValue(), print(), and llvm::AliasSetTracker::print().
void AliasSet::dump () const
Definition at line 592 of file AliasSetTracker.cpp.
References llvm::dbgs(), and print().
Referenced by empty(), and llvm::AliasSetTracker::end().
bool llvm::AliasSet::empty () const inline
Definition at line 177 of file AliasSetTracker.h.
References dump(), and print().
Referenced by llvm::createLICMPass(), print(), and llvm::AliasSetTracker::remove().
iterator llvm::AliasSet::end () const inline
Definition at line 176 of file AliasSetTracker.h.
Referenced by llvm::AliasSetTracker::add(), aliasesPointer(), aliasesUnknownInst(), llvm::AliasSetTracker::clear(), llvm::AliasSetTracker::containsPointer(), llvm::createLICMPass(), llvm::AliasSetTracker::deleteValue(), print(), and llvm::AliasSetTracker::print().
bool llvm::AliasSet::isForwardingAliasSet () const inline
isForwardingAliasSet - Return true if this alias set should be ignored as part of the AliasSetTracker object.
Definition at line 166 of file AliasSetTracker.h.
References mergeSetIn().
Referenced by llvm::createLICMPass().
bool llvm::AliasSet::isMayAlias () const inline
Definition at line 158 of file AliasSetTracker.h.
bool llvm::AliasSet::isMod () const inline
Definition at line 156 of file AliasSetTracker.h.
Referenced by llvm::createLICMPass().
bool llvm::AliasSet::isMustAlias () const inline
Definition at line 157 of file AliasSetTracker.h.
Referenced by llvm::createLICMPass(), and mergeSetIn().
bool llvm::AliasSet::isRef () const inline
Accessors...
Definition at line 155 of file AliasSetTracker.h.
bool llvm::AliasSet::isVolatile () const inline
Definition at line 162 of file AliasSetTracker.h.
Referenced by llvm::AliasSetTracker::add(), llvm::createLICMPass(), and print().
void AliasSet::mergeSetIn (AliasSet & AS, AliasSetTracker & AST)
mergeSetIn - Merge the specified alias set into this alias set...
mergeSetIn - Merge the specified alias set into this alias set.
Definition at line 31 of file AliasSetTracker.cpp.
References llvm::AliasAnalysis::alias(), llvm::AliasSetTracker::getAliasAnalysis(), I, isMustAlias(), llvm::Instruction::mayWriteToMemory(), llvm::AliasAnalysis::MustAlias, llvm::AliasAnalysis::NoAlias, P, and std::swap().
Referenced by llvm::AliasSetTracker::clear(), llvm::AliasSetTracker::containsPointer(), and isForwardingAliasSet().
void AliasSet::print (raw_ostream & OS) const
Definition at line 550 of file AliasSetTracker.cpp.
References begin(), empty(), end(), i, I, isVolatile(), llvm_unreachable, and llvm::WriteAsOperand().
Referenced by dump(), llvm::AliasSetTracker::dump(), empty(), llvm::AliasSetTracker::end(), and llvm::operator<<().
Friends And Related Function Documentation
friend class AliasSetTracker friend
Definition at line 36 of file AliasSetTracker.h.
Referenced by llvm::AliasSetTracker::dump().
friend struct ilist_sentinel_traits< AliasSet > friend
Definition at line 222 of file AliasSetTracker.h.
The documentation for this class was generated from the following files:
AliasSetTracker.h
AliasSetTracker.cpp