LLVM: llvm::Mips16HardFloat Class Reference
LLVM API Documentation
llvm::Mips16HardFloat Class Reference
#include <Mips16HardFloat.h>
Public Member Functions
Mips16HardFloat (MipsTargetMachine &TM_)
virtual const char * getPassName () const
virtual bool runOnModule (Module &M)
Public Member Functions inherited from llvm::ModulePass
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const
createPrinterPass - Get a module printer pass.
virtual void assignPassManager (PMStack &PMS, PassManagerType T)
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
ModulePass (char &pid)
virtual ~ModulePass ()
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Protected Attributes
const TargetMachine & TM
const MipsSubtarget & Subtarget
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
Definition at line 28 of file Mips16HardFloat.h.
Constructor & Destructor Documentation
llvm::Mips16HardFloat::Mips16HardFloat (MipsTargetMachine & TM_) inline
Definition at line 33 of file Mips16HardFloat.h.
Member Function Documentation
virtual const char* llvm::Mips16HardFloat::getPassName () const inline virtual
getPassName - Return a nice clean name for a pass. This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 37 of file Mips16HardFloat.h.
References M, and runOnModule().
bool llvm::Mips16HardFloat::runOnModule (Module & M) virtual
runOnModule - Virtual method overriden by subclasses to process the module being operated on.
Implements llvm::ModulePass.
Definition at line 489 of file Mips16HardFloat.cpp.
References llvm::Module::begin(), createFPFnStub(), DEBUG, llvm::Module::end(), llvm::errs(), F(), fixupFPReturnAndCall(), llvm::Function::hasFnAttribute(), llvm::GlobalValue::isDeclaration(), removeUseSoftFloat(), and whichFPParamVariantNeeded().
Referenced by getPassName().
Member Data Documentation
char llvm::Mips16HardFloat::ID = 0 static
Definition at line 31 of file Mips16HardFloat.h.
const MipsSubtarget& llvm::Mips16HardFloat::Subtarget protected
Definition at line 47 of file Mips16HardFloat.h.
const TargetMachine& llvm::Mips16HardFloat::TM protected
Keep a pointer to the MipsSubtarget around so that we can make the right decision when generating code for different targets.
Definition at line 46 of file Mips16HardFloat.h.
The documentation for this class was generated from the following files:
Mips16HardFloat.h
Mips16HardFloat.cpp