LLVM: llvm::SpecialCaseList Class Reference
LLVM API Documentation
llvm::SpecialCaseList Class Reference
#include <SpecialCaseList.h>
Classes
struct Entry
Public Member Functions
~SpecialCaseList ()
bool isIn (const Function &F, const StringRef Category=StringRef()) const
bool isIn (const GlobalVariable &G, const StringRef Category=StringRef()) const
bool isIn (const GlobalAlias &GA, const StringRef Category=StringRef()) const
bool isIn (const Module &M, const StringRef Category=StringRef()) const
Static Public Member Functions
static SpecialCaseList * create (const StringRef Path, std::string &Error)
static SpecialCaseList * create (const MemoryBuffer *MB, std::string &Error)
static SpecialCaseList * createOrDie (const StringRef Path)
Detailed Description
Definition at line 59 of file SpecialCaseList.h.
Constructor & Destructor Documentation
llvm::SpecialCaseList::~SpecialCaseList ()
Definition at line 160 of file SpecialCaseList.cpp.
References I, and llvm::ARM_PROC::IE.
Member Function Documentation
SpecialCaseList * llvm::SpecialCaseList::create (const StringRef Path, std::string & Error) static
Parses the special case list from a file. If Path is empty, returns an empty special case list. On failure, returns 0 and writes an error message to string.
Definition at line 54 of file SpecialCaseList.cpp.
References llvm::StringRef::empty(), llvm::lltok::Error, llvm::ARMBuildAttrs::File, llvm::OwningPtr< T >::get(), and llvm::MemoryBuffer::getFile().
Referenced by createOrDie().
SpecialCaseList * llvm::SpecialCaseList::create (const MemoryBuffer * MB, std::string & Error) static
Parses the special case list from a memory buffer. On failure, returns 0 and writes an error message to string.
Definition at line 66 of file SpecialCaseList.cpp.
References llvm::OwningPtr< T >::take().
SpecialCaseList * llvm::SpecialCaseList::createOrDie (const StringRef Path) static
Parses the special case list from a file. On failure, reports a fatal error.
Definition at line 74 of file SpecialCaseList.cpp.
References llvm::SmallVectorTemplateCommon< T >::begin(), create(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::lltok::Error, llvm::MemoryBuffer::getBuffer(), I, llvm::ARM_PROC::IE, llvm::Regex::isLiteralERE(), llvm::Regex::isValid(), llvm::cl::Prefix, llvm::report_fatal_error(), llvm::SplitString(), and llvm::LibFunc::strlen.
Referenced by checkInterfaceFunction(), createPrivateNonConstGlobalForString(), and INITIALIZE_PASS().
bool llvm::SpecialCaseList::isIn (const Function & F, const StringRef Category = StringRef()) const
Returns whether either this function or its source file are listed in the given category, which may be omitted to search the empty category.
Definition at line 172 of file SpecialCaseList.cpp.
References llvm::Value::getName(), and llvm::GlobalValue::getParent().
Referenced by INITIALIZE_PASS(), and isIn().
bool llvm::SpecialCaseList::isIn (const GlobalVariable & G, const StringRef Category = StringRef()) const
Returns whether this global, its type or its source file are listed in the given category, which may be omitted to search the empty category.
Definition at line 188 of file SpecialCaseList.cpp.
References llvm::GetGlobalTypeString(), llvm::Value::getName(), llvm::GlobalValue::getParent(), and isIn().
bool llvm::SpecialCaseList::isIn (const GlobalAlias & GA, const StringRef Category = StringRef()) const
Returns whether this global alias is listed in the given category, which may be omitted to search the empty category.
If GA aliases a function, the alias's name is matched as a function name would be. Similarly, aliases of globals are matched like globals.
Definition at line 195 of file SpecialCaseList.cpp.
References llvm::SequentialType::getElementType(), llvm::GetGlobalTypeString(), llvm::Value::getName(), llvm::GlobalValue::getParent(), llvm::GlobalValue::getType(), and isIn().
bool llvm::SpecialCaseList::isIn (const Module & M, const StringRef Category = StringRef()) const
Returns whether this module is listed in the given category, which may be omitted to search the empty category.
Definition at line 207 of file SpecialCaseList.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::Module::getModuleIdentifier(), llvm::StringMapEntry< ValueTy >::getValue(), I, and llvm::ARMBuildAttrs::Section.
The documentation for this class was generated from the following files:
SpecialCaseList.h
SpecialCaseList.cpp