LLVM: llvm::PBQPBuilderWithCoalescing Class Reference
LLVM API Documentation
llvm::PBQPBuilderWithCoalescing Class Reference
Extended builder which adds coalescing constraints to a problem.
#include <RegAllocPBQP.h>
Public Member Functions
virtual PBQPRAProblem * build (MachineFunction *mf, const LiveIntervals *lis, const MachineBlockFrequencyInfo *mbfi, const RegSet &vregs)
Public Member Functions inherited from llvm::PBQPBuilder
PBQPBuilder ()
Default constructor.
virtual ~PBQPBuilder ()
Clean up a PBQPBuilder.
Additional Inherited Members
Public Types inherited from llvm::PBQPBuilder
typedef std::set< unsigned > RegSet
Detailed Description
Extended builder which adds coalescing constraints to a problem.
Definition at line 140 of file RegAllocPBQP.h.
Member Function Documentation
PBQPRAProblem * PBQPBuilderWithCoalescing::build (MachineFunction * mf, const LiveIntervals * lis, const MachineBlockFrequencyInfo * mbfi, const RegSet & vregs) virtual
Build a PBQP instance to represent the register allocation problem for the given MachineFunction.
Reimplemented from llvm::PBQPBuilder.
Definition at line 313 of file RegAllocPBQP.cpp.
References PBQP::Graph::addEdge(), llvm::AnalysisUsage::addPreserved(), llvm::AnalysisUsage::addRequired(), llvm::AnalysisUsage::addRequiredID(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::PBQPBuilder::build(), llvm::calculateSpillWeightsAndHints(), llvm::createInlineSpiller(), llvm::dbgs(), DEBUG, PBQP::Graph::dump(), llvm::LiveRange::empty(), llvm::sys::path::const_iterator::end, llvm::sys::path::end(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), PBQP::Graph::findEdge(), llvm::ArrayRef< T >::front(), g, llvm::PBQPRAProblem::getAllowedSet(), llvm::MachineFunctionPass::getAnalysisUsage(), llvm::MachineBlockFrequencyInfo::getBlockFreq(), PBQP::Matrix::getCols(), PBQP::Graph::getEdgeCosts(), PBQP::Graph::getEdgeNode1(), llvm::PBQPRAProblem::getGraph(), llvm::Module::getModuleIdentifier(), llvm::Value::getName(), llvm::MCRegisterInfo::getName(), PBQP::Graph::getNodeCosts(), llvm::PBQPRAProblem::getNodeForVReg(), llvm::GlobalValue::getParent(), llvm::PBQPRAProblem::getPRegForOption(), llvm::TargetRegisterClass::getRawAllocationOrder(), llvm::MachineFunction::getRegInfo(), llvm::TargetMachine::getRegisterInfo(), PBQP::Matrix::getRows(), PBQP::Solution::getSelection(), llvm::LiveIntervals::getSpillWeight(), llvm::MachineFunction::getTarget(), llvm::PBQPRAProblem::getVRegForNode(), i, llvm::TargetRegisterInfo::index2VirtReg(), PBQP::Graph::invalidEdgeId(), llvm::MachineRegisterInfo::isAllocatable(), llvm::PBQPRAProblem::isPRegOption(), llvm::PBQPRAProblem::isSpillOption(), j(), llvm_unreachable, node, PBQP::Graph::nodesBegin(), PBQP::Graph::nodesEnd(), p, pbqpDumpGraphs, problem, llvm::LiveInterval::reg, llvm::Intrinsic::round, llvm::AnalysisUsage::setPreservesCFG(), llvm::SmallVectorTemplateCommon< T, typename >::size(), PBQP::HeuristicSolver< HImpl >::solve(), llvm::StringRef::str(), std::swap(), and llvm::OwningPtr< T >::take().
The documentation for this class was generated from the following files:
RegAllocPBQP.h
RegAllocPBQP.cpp