LLVM: llvm::PPCScoreboardHazardRecognizer Class Reference
LLVM API Documentation
llvm::PPCScoreboardHazardRecognizer Class Reference
#include <PPCHazardRecognizers.h>
Public Member Functions
PPCScoreboardHazardRecognizer (const InstrItineraryData *ItinData, const ScheduleDAG *DAG_)
virtual HazardType getHazardType (SUnit *SU, int Stalls)
virtual void EmitInstruction (SUnit *SU)
virtual void AdvanceCycle ()
virtual void Reset ()
Public Member Functions inherited from llvm::ScoreboardHazardRecognizer
ScoreboardHazardRecognizer (const InstrItineraryData *ItinData, const ScheduleDAG *DAG, const char *ParentDebugType="")
virtual bool atIssueLimit () const
virtual void RecedeCycle ()
Public Member Functions inherited from llvm::ScheduleHazardRecognizer
ScheduleHazardRecognizer ()
virtual ~ScheduleHazardRecognizer ()
unsigned getMaxLookAhead () const
bool isEnabled () const
virtual void EmitNoop ()
Additional Inherited Members
Public Types inherited from llvm::ScheduleHazardRecognizer
enum HazardType { NoHazard, Hazard, NoopHazard }
Protected Attributes inherited from llvm::ScheduleHazardRecognizer
unsigned MaxLookAhead
Detailed Description
PPCScoreboardHazardRecognizer - This class implements a scoreboard-based hazard recognizer for generic PPC processors.
Definition at line 26 of file PPCHazardRecognizers.h.
Constructor & Destructor Documentation
llvm::PPCScoreboardHazardRecognizer::PPCScoreboardHazardRecognizer (const InstrItineraryData * ItinData, const ScheduleDAG * DAG_) inline
Definition at line 29 of file PPCHazardRecognizers.h.
References AdvanceCycle(), EmitInstruction(), getHazardType(), and Reset().
Member Function Documentation
void PPCScoreboardHazardRecognizer::AdvanceCycle () virtual
AdvanceCycle - This callback is invoked whenever the next top-down instruction to be scheduled cannot issue in the current cycle, either because of latency or resource conflicts. This should increment the internal state of the hazard recognizer so that previously "Hazard" instructions will now not be hazards.
Reimplemented from llvm::ScoreboardHazardRecognizer.
Definition at line 40 of file PPCHazardRecognizers.cpp.
References llvm::ScoreboardHazardRecognizer::AdvanceCycle().
Referenced by PPCScoreboardHazardRecognizer().
void PPCScoreboardHazardRecognizer::EmitInstruction (SUnit *) virtual
EmitInstruction - This callback is invoked when an instruction is emitted, to advance the hazard state.
Reimplemented from llvm::ScoreboardHazardRecognizer.
Definition at line 26 of file PPCHazardRecognizers.cpp.
References llvm::ScoreboardHazardRecognizer::EmitInstruction(), and llvm::ScheduleDAG::getInstrDesc().
Referenced by PPCScoreboardHazardRecognizer().
ScheduleHazardRecognizer::HazardType PPCScoreboardHazardRecognizer::getHazardType (SUnit * m, int Stalls) virtual
getHazardType - Return the hazard type of emitting this node. There are three possible results. Either:
NoHazard: it is legal to issue this instruction on this cycle.
Hazard: issuing this instruction would stall the machine. If some other instruction is available, issue it first.
NoopHazard: issuing this instruction would break the program. If some other instruction can be issued, do so, otherwise issue a noop.
Reimplemented from llvm::ScoreboardHazardRecognizer.
Definition at line 36 of file PPCHazardRecognizers.cpp.
References llvm::ScoreboardHazardRecognizer::getHazardType().
Referenced by PPCScoreboardHazardRecognizer().
void PPCScoreboardHazardRecognizer::Reset () virtual
Reset - This callback is invoked when a new block of instructions is about to be schedule. The hazard state should be set to an initialized state.
Reimplemented from llvm::ScoreboardHazardRecognizer.
Definition at line 44 of file PPCHazardRecognizers.cpp.
References llvm::ScoreboardHazardRecognizer::Reset().
Referenced by PPCScoreboardHazardRecognizer().
The documentation for this class was generated from the following files:
PPCHazardRecognizers.h
PPCHazardRecognizers.cpp