LLVM: llvm::DomTreeNodeBase< NodeT > Class Template Reference
LLVM API Documentation
llvm::DomTreeNodeBase< NodeT > Class Template Reference
#include <Dominators.h>
Public Types
typedef std::vector< DomTreeNodeBase< NodeT > * >::iterator iterator
typedef std::vector< DomTreeNodeBase< NodeT > * >::const_iterator const_iterator
Public Member Functions
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
NodeT * getBlock () const
DomTreeNodeBase< NodeT > * getIDom () const
const std::vector< DomTreeNodeBase< NodeT > * > & getChildren () const
DomTreeNodeBase (NodeT *BB, DomTreeNodeBase< NodeT > *iDom)
DomTreeNodeBase< NodeT > * addChild (DomTreeNodeBase< NodeT > *C)
size_t getNumChildren () const
void clearAllChildren ()
bool compare (const DomTreeNodeBase< NodeT > *Other) const
void setIDom (DomTreeNodeBase< NodeT > *NewIDom)
unsigned getDFSNumIn () const
unsigned getDFSNumOut () const
Friends
template<class N >
class DominatorTreeBase
struct PostDominatorTree
Detailed Description
template<class NodeT>
class llvm::DomTreeNodeBase< NodeT >
Definition at line 64 of file Dominators.h.
Member Typedef Documentation
template<class NodeT> typedef std::vector<DomTreeNodeBase<NodeT> *>::const_iterator llvm::DomTreeNodeBase< NodeT >::const_iterator
Definition at line 75 of file Dominators.h.
template<class NodeT> typedef std::vector<DomTreeNodeBase<NodeT> *>::iterator llvm::DomTreeNodeBase< NodeT >::iterator
Definition at line 73 of file Dominators.h.
Constructor & Destructor Documentation
template<class NodeT> llvm::DomTreeNodeBase< NodeT >::DomTreeNodeBase (NodeT * BB, DomTreeNodeBase< NodeT > * iDom) inline
Definition at line 88 of file Dominators.h.
Member Function Documentation
template<class NodeT> DomTreeNodeBase<NodeT>* llvm::DomTreeNodeBase< NodeT >::addChild (DomTreeNodeBase< NodeT > * C) inline
Definition at line 91 of file Dominators.h.
Referenced by llvm::DominatorTreeBase< llvm::MachineBasicBlock >::addNewBlock(), llvm::Calculate(), and llvm::DominatorTreeBase< llvm::MachineBasicBlock >::getNodeForBlock().
template<class NodeT> iterator llvm::DomTreeNodeBase< NodeT >::begin () inline
Definition at line 77 of file Dominators.h.
Referenced by llvm::DominanceFrontier::calculate(), llvm::GraphTraits< MachineDomTreeNode * >::child_begin(), llvm::GraphTraits< DomTreeNode * >::child_begin(), llvm::Region::clearNodeCache(), llvm::DomTreeNodeBase< llvm::MachineBasicBlock >::compare(), llvm::createEarlyCSEPass(), llvm::createGlobalBaseRegPass(), llvm::emitSPUpdate(), llvm::CodeExtractor::findInputsOutputs(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::getDescendants(), isSafeToMove(), promoteSingleBlockAlloca(), shouldSpeculateInstrs(), and llvm::DominatorTreeBase< llvm::MachineBasicBlock >::updateDFSNumbers().
template<class NodeT> const_iterator llvm::DomTreeNodeBase< NodeT >::begin () const inline
Definition at line 79 of file Dominators.h.
template<class NodeT> void llvm::DomTreeNodeBase< NodeT >::clearAllChildren () inline
Definition at line 100 of file Dominators.h.
template<class NodeT> bool llvm::DomTreeNodeBase< NodeT >::compare (const DomTreeNodeBase< NodeT > * Other) const inline
Definition at line 104 of file Dominators.h.
Referenced by llvm::DominatorTreeBase< llvm::MachineBasicBlock >::compare().
template<class NodeT> iterator llvm::DomTreeNodeBase< NodeT >::end () inline
Definition at line 78 of file Dominators.h.
Referenced by llvm::DominanceFrontier::calculate(), llvm::GraphTraits< MachineDomTreeNode * >::child_end(), llvm::GraphTraits< DomTreeNode * >::child_end(), llvm::Region::clearNodeCache(), llvm::DomTreeNodeBase< llvm::MachineBasicBlock >::compare(), llvm::createEarlyCSEPass(), llvm::createGlobalBaseRegPass(), llvm::emitSPUpdate(), llvm::CodeExtractor::findInputsOutputs(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::getDescendants(), isSafeToMove(), promoteSingleBlockAlloca(), shouldSpeculateInstrs(), and llvm::DominatorTreeBase< llvm::MachineBasicBlock >::updateDFSNumbers().
template<class NodeT> const_iterator llvm::DomTreeNodeBase< NodeT >::end () const inline
Definition at line 80 of file Dominators.h.
template<class NodeT> NodeT* llvm::DomTreeNodeBase< NodeT >::getBlock () const inline
Definition at line 82 of file Dominators.h.
Referenced by llvm::LoopInfoBase< BlockT, LoopT >::Analyze(), llvm::DominanceFrontier::calculate(), llvm::LiveRangeCalc::calculateValues(), llvm::Region::clearNodeCache(), llvm::DominatorTree::compare(), llvm::createEarlyCSEPass(), llvm::createGlobalBaseRegPass(), llvm::createLICMPass(), llvm::emitSPUpdate(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::findNearestCommonDominator(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::getDescendants(), llvm::DOTGraphTraits< DomTreeNode * >::getNodeLabel(), InstructionStoresToFI(), isProfitableChain(), llvm::operator<<(), promoteSingleBlockAlloca(), and shouldSpeculateInstrs().
template<class NodeT> const std::vector<DomTreeNodeBase<NodeT>*>& llvm::DomTreeNodeBase< NodeT >::getChildren () const inline
Definition at line 84 of file Dominators.h.
Referenced by llvm::createLICMPass(), llvm::createLoopSimplifyPass(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::eraseNode(), and InstructionStoresToFI().
template<class NodeT> unsigned llvm::DomTreeNodeBase< NodeT >::getDFSNumIn () const inline
getDFSNumIn/getDFSNumOut - These are an internal implementation detail, do not call them.
Definition at line 140 of file Dominators.h.
Referenced by llvm::operator<<().
template<class NodeT> unsigned llvm::DomTreeNodeBase< NodeT >::getDFSNumOut () const inline
Definition at line 141 of file Dominators.h.
Referenced by llvm::operator<<().
template<class NodeT> DomTreeNodeBase<NodeT>* llvm::DomTreeNodeBase< NodeT >::getIDom () const inline
Definition at line 83 of file Dominators.h.
Referenced by llvm::LiveRangeCalc::calculateValues(), llvm::Region::clearNodeCache(), llvm::createLoopSimplifyPass(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::eraseNode(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::findNearestCommonDominator(), isSimplifiedLoopNest(), llvm::MergeBasicBlockIntoOnlyPred(), promoteSingleBlockAlloca(), and shouldSpeculateInstrs().
template<class NodeT> size_t llvm::DomTreeNodeBase< NodeT >::getNumChildren () const inline
Definition at line 96 of file Dominators.h.
Referenced by llvm::DomTreeNodeBase< llvm::MachineBasicBlock >::compare().
template<class NodeT> void llvm::DomTreeNodeBase< NodeT >::setIDom (DomTreeNodeBase< NodeT > * NewIDom) inline
Definition at line 122 of file Dominators.h.
Referenced by llvm::DominatorTreeBase< llvm::MachineBasicBlock >::changeImmediateDominator().
Friends And Related Function Documentation
template<class NodeT> template<class N > friend class DominatorTreeBase friend
Definition at line 70 of file Dominators.h.
template<class NodeT> friend struct PostDominatorTree friend
Definition at line 71 of file Dominators.h.
The documentation for this class was generated from the following file:
Dominators.h