LLVM: llvm::MCRelaxableFragment Class Reference
LLVM API Documentation
llvm::MCRelaxableFragment Class Reference
#include <MCAssembler.h>
Public Member Functions
MCRelaxableFragment (const MCInst &_Inst, MCSectionData *SD=0)
virtual SmallVectorImpl< char > & getContents ()
virtual const SmallVectorImpl< char > & getContents () const
const MCInst & getInst () const
void setInst (const MCInst &Value)
SmallVectorImpl< MCFixup > & getFixups ()
const SmallVectorImpl< MCFixup > & getFixups () const
virtual bool hasInstructions () const
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
fixup_iterator fixup_begin ()
const_fixup_iterator fixup_begin () const
fixup_iterator fixup_end ()
const_fixup_iterator fixup_end () const
Public Member Functions inherited from llvm::MCEncodedFragmentWithFixups
MCEncodedFragmentWithFixups (MCFragment::FragmentType FType, MCSectionData *SD=0)
virtual ~MCEncodedFragmentWithFixups ()
Public Member Functions inherited from llvm::MCEncodedFragment
MCEncodedFragment (MCFragment::FragmentType FType, MCSectionData *SD=0)
virtual ~MCEncodedFragment ()
virtual uint8_t getBundlePadding () const
Get the padding size that must be inserted before this fragment. Used for bundling. By default, no padding is inserted. Note that padding size is restricted to 8 bits. This is an optimization to reduce the amount of space used for each fragment. In practice, larger padding should never be required.
virtual void setBundlePadding (uint8_t N)
Set the padding size for this fragment. By default it's a no-op, and only some fragments have a meaningful implementation.
Public Member Functions inherited from llvm::MCFragment
MCFragment ()
virtual ~MCFragment ()
FragmentType getKind () const
MCSectionData * getParent () const
void setParent (MCSectionData *Value)
MCSymbolData * getAtom () const
void setAtom (MCSymbolData *Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
virtual bool alignToBundleEnd () const
Should this fragment be placed at the end of an aligned bundle?
virtual void setAlignToBundleEnd (bool V)
void dump ()
Public Member Functions inherited from llvm::ilist_node< MCFragment >
MCFragment * getPrevNode ()
Get the previous node, or 0 for the list head.
const MCFragment * getPrevNode () const
Get the previous node, or 0 for the list head.
MCFragment * getNextNode ()
Get the next node, or 0 for the list tail.
const MCFragment * getNextNode () const
Get the next node, or 0 for the list tail.
Static Public Member Functions
static bool classof (const MCFragment *F)
Static Public Member Functions inherited from llvm::MCEncodedFragmentWithFixups
static bool classof (const MCFragment *F)
Static Public Member Functions inherited from llvm::MCEncodedFragment
static bool classof (const MCFragment *F)
Additional Inherited Members
Public Types inherited from llvm::MCEncodedFragmentWithFixups
typedef SmallVectorImpl< MCFixup >::const_iterator const_fixup_iterator
typedef SmallVectorImpl< MCFixup >::iterator fixup_iterator
Public Types inherited from llvm::MCFragment
enum FragmentType {
FT_Align, FT_Data, FT_CompactEncodedInst, FT_Fill,
FT_Relaxable, FT_Org, FT_Dwarf, FT_DwarfFrame,
FT_LEB
}
Protected Member Functions inherited from llvm::MCFragment
MCFragment (FragmentType _Kind, MCSectionData *_Parent=0)
Protected Member Functions inherited from llvm::ilist_node< MCFragment >
ilist_node ()
Detailed Description
A relaxable fragment holds on to its MCInst, since it may need to be relaxed during the assembler layout and relaxation stage.
Definition at line 285 of file MCAssembler.h.
Constructor & Destructor Documentation
llvm::MCRelaxableFragment::MCRelaxableFragment (const MCInst & _Inst, MCSectionData * SD = 0) inline
Definition at line 298 of file MCAssembler.h.
Member Function Documentation
static bool llvm::MCRelaxableFragment::classof (const MCFragment * F) inline static
Definition at line 324 of file MCAssembler.h.
References llvm::MCFragment::FT_Relaxable, and llvm::MCFragment::getKind().
fixup_iterator llvm::MCRelaxableFragment::fixup_begin () inline virtual
Implements llvm::MCEncodedFragmentWithFixups.
Definition at line 318 of file MCAssembler.h.
References llvm::SmallVectorTemplateCommon< T >::begin().
Referenced by llvm::MCAssembler::Finish().
const_fixup_iterator llvm::MCRelaxableFragment::fixup_begin () const inline virtual
Implements llvm::MCEncodedFragmentWithFixups.
Definition at line 319 of file MCAssembler.h.
References llvm::SmallVectorTemplateCommon< T >::begin().
fixup_iterator llvm::MCRelaxableFragment::fixup_end () inline virtual
Implements llvm::MCEncodedFragmentWithFixups.
Definition at line 321 of file MCAssembler.h.
References llvm::SmallVectorTemplateCommon< T >::end().
Referenced by llvm::MCAssembler::Finish().
const_fixup_iterator llvm::MCRelaxableFragment::fixup_end () const inline virtual
Implements llvm::MCEncodedFragmentWithFixups.
Definition at line 322 of file MCAssembler.h.
References llvm::SmallVectorTemplateCommon< T >::end().
virtual SmallVectorImpl<char>& llvm::MCRelaxableFragment::getContents () inline virtual
Implements llvm::MCEncodedFragment.
Definition at line 302 of file MCAssembler.h.
Referenced by llvm::MCObjectStreamer::EmitInstToFragment(), and llvm::MCAssembler::Finish().
virtual const SmallVectorImpl<char>& llvm::MCRelaxableFragment::getContents () const inline virtual
Implements llvm::MCEncodedFragment.
Definition at line 303 of file MCAssembler.h.
SmallVectorImpl<MCFixup>& llvm::MCRelaxableFragment::getFixups () inline virtual
Implements llvm::MCEncodedFragmentWithFixups.
Definition at line 308 of file MCAssembler.h.
Referenced by llvm::MCELFStreamer::EmitIdent(), llvm::MCObjectStreamer::EmitInstToFragment(), and llvm::MCAssembler::Finish().
const SmallVectorImpl<MCFixup>& llvm::MCRelaxableFragment::getFixups () const inline virtual
Implements llvm::MCEncodedFragmentWithFixups.
Definition at line 312 of file MCAssembler.h.
const MCInst& llvm::MCRelaxableFragment::getInst () const inline
Definition at line 305 of file MCAssembler.h.
Referenced by llvm::MCFragment::dump(), and llvm::MCAssembler::Finish().
virtual bool llvm::MCRelaxableFragment::hasInstructions () const inline virtual
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
Reimplemented from llvm::MCFragment.
Definition at line 316 of file MCAssembler.h.
void llvm::MCRelaxableFragment::setInst (const MCInst & Value) inline
Definition at line 306 of file MCAssembler.h.
Referenced by llvm::MCAssembler::Finish().
The documentation for this class was generated from the following files:
MCAssembler.h
MCAssembler.cpp