LLVM: llvm::SystemZAsmPrinter Class Reference
LLVM API Documentation
llvm::SystemZAsmPrinter Class Reference
#include <SystemZAsmPrinter.h>
Public Member Functions
SystemZAsmPrinter (TargetMachine &TM, MCStreamer &Streamer)
virtual const char * getPassName () const LLVM_OVERRIDE
virtual void EmitInstruction (const MachineInstr *MI) LLVM_OVERRIDE
EmitInstruction - Targets should implement this to emit instructions.
virtual void EmitMachineConstantPoolValue (MachineConstantPoolValue *MCPV) LLVM_OVERRIDE
virtual bool PrintAsmOperand (const MachineInstr *MI, unsigned OpNo, unsigned AsmVariant, const char *ExtraCode, raw_ostream &OS) LLVM_OVERRIDE
virtual bool PrintAsmMemoryOperand (const MachineInstr *MI, unsigned OpNo, unsigned AsmVariant, const char *ExtraCode, raw_ostream &OS) LLVM_OVERRIDE
virtual void EmitEndOfAsmFile (Module &M) LLVM_OVERRIDE
Public Member Functions inherited from llvm::AsmPrinter
virtual ~AsmPrinter ()
const DwarfDebug * getDwarfDebug () const
bool isVerbose () const
unsigned getFunctionNumber () const
const TargetLoweringObjectFile & getObjFileLowering () const
getObjFileLowering - Return information about object file lowering.
const DataLayout & getDataLayout () const
getDataLayout - Return information about data layout.
StringRef getTargetTriple () const
getTargetTriple - Return the target triple string.
const MCSection * getCurrentSection () const
getCurrentSection() - Return the current section we are emitting to.
MCSymbol * getSymbol (const GlobalValue *GV) const
void getAnalysisUsage (AnalysisUsage &AU) const
bool doInitialization (Module &M)
bool doFinalization (Module &M)
virtual bool runOnMachineFunction (MachineFunction &MF)
void SetupMachineFunction (MachineFunction &MF)
void EmitFunctionHeader ()
void EmitFunctionBody ()
void emitPrologLabel (const MachineInstr &MI)
CFIMoveType needsCFIMoves ()
bool needsSEHMoves ()
bool needsRelocationsForDwarfStringPool () const
virtual void EmitConstantPool ()
void EmitJumpTableInfo ()
virtual void EmitGlobalVariable (const GlobalVariable *GV)
EmitGlobalVariable - Emit the specified global variable to the .s file.
bool EmitSpecialLLVMGlobal (const GlobalVariable *GV)
void EmitAlignment (unsigned NumBits, const GlobalValue *GV=0) const
void EmitBasicBlockStart (const MachineBasicBlock *MBB) const
void EmitGlobalConstant (const Constant *CV)
Print a general LLVM constant to the .s file.
virtual void EmitStartOfAsmFile (Module &)
virtual void EmitFunctionBodyStart ()
virtual void EmitFunctionBodyEnd ()
virtual void EmitFunctionEntryLabel ()
virtual void EmitXXStructor (const Constant *CV)
virtual bool isBlockOnlyReachableByFallthrough (const MachineBasicBlock *MBB) const
virtual void emitImplicitDef (const MachineInstr *MI) const
MCSymbol * GetTempSymbol (StringRef Name, unsigned ID) const
MCSymbol * GetTempSymbol (StringRef Name) const
MCSymbol * GetSymbolWithGlobalValueBase (const GlobalValue *GV, StringRef Suffix, bool ForcePrivate=true) const
MCSymbol * GetExternalSymbolSymbol (StringRef Sym) const
MCSymbol * GetCPISymbol (unsigned CPID) const
GetCPISymbol - Return the symbol for the specified constant pool entry.
MCSymbol * GetJTISymbol (unsigned JTID, bool isLinkerPrivate=false) const
GetJTISymbol - Return the symbol for the specified jump table entry.
MCSymbol * GetJTSetSymbol (unsigned UID, unsigned MBBID) const
MCSymbol * GetBlockAddressSymbol (const BlockAddress *BA) const
MCSymbol * GetBlockAddressSymbol (const BasicBlock *BB) const
void printOffset (int64_t Offset, raw_ostream &OS) const
printOffset - This is just convenient handler for printing offsets.
void EmitInt8 (int Value) const
void EmitInt16 (int Value) const
void EmitInt32 (int Value) const
void EmitLabelDifference (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Size) const
void EmitLabelOffsetDifference (const MCSymbol *Hi, uint64_t Offset, const MCSymbol *Lo, unsigned Size) const
void EmitLabelPlusOffset (const MCSymbol *Label, uint64_t Offset, unsigned Size, bool IsSectionRelative=false) const
void EmitLabelReference (const MCSymbol *Label, unsigned Size, bool IsSectionRelative=false) const
void EmitSLEB128 (int64_t Value, const char *Desc=0) const
EmitSLEB128 - emit the specified signed leb128 value.
void EmitULEB128 (uint64_t Value, const char *Desc=0, unsigned PadTo=0) const
EmitULEB128 - emit the specified unsigned leb128 value.
void EmitCFAByte (unsigned Val) const
EmitCFAByte - Emit a .byte 42 directive for a DW_CFA_xxx value.
void EmitEncodingByte (unsigned Val, const char *Desc=0) const
unsigned GetSizeOfEncodedValue (unsigned Encoding) const
GetSizeOfEncodedValue - Return the size of the encoding in bytes.
void EmitTTypeReference (const GlobalValue *GV, unsigned Encoding) const
EmitReference - Emit reference to a ttype global with a specified encoding.
void EmitSectionOffset (const MCSymbol *Label, const MCSymbol *SectionLabel) const
virtual unsigned getISAEncoding ()
virtual void EmitDwarfRegOp (const MachineLocation &MLoc, bool Indirect) const
EmitDwarfRegOp - Emit dwarf register operation.
void emitCFIInstruction (const MCCFIInstruction &Inst) const
Emit frame instruction to describe the layout of the frame.
virtual void PrintSpecial (const MachineInstr *MI, raw_ostream &OS, const char *Code) const
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const
createPrinterPass - Get a function printer pass.
virtual void assignPassManager (PMStack &PMS, PassManagerType T)
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Additional Inherited Members
Public Types inherited from llvm::AsmPrinter
enum CFIMoveType { CFI_M_None, CFI_M_EH, CFI_M_Debug }
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Public Attributes inherited from llvm::AsmPrinter
TargetMachine & TM
const MCAsmInfo * MAI
const MCInstrInfo * MII
MCContext & OutContext
MCStreamer & OutStreamer
const MachineFunction * MF
The current machine function.
MachineModuleInfo * MMI
MMI - This is a pointer to the current MachineModuleInfo.
Mangler * Mang
MCSymbol * CurrentFnSym
MCSymbol * CurrentFnSymForSize
Protected Member Functions inherited from llvm::AsmPrinter
AsmPrinter (TargetMachine &TM, MCStreamer &Streamer)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
Detailed Description
Definition at line 24 of file SystemZAsmPrinter.h.
Constructor & Destructor Documentation
llvm::SystemZAsmPrinter::SystemZAsmPrinter (TargetMachine & TM, MCStreamer & Streamer) inline
Definition at line 29 of file SystemZAsmPrinter.h.
References llvm::TargetMachine::getSubtarget().
Member Function Documentation
void SystemZAsmPrinter::EmitEndOfAsmFile (Module &) virtual
EmitEndOfAsmFile - This virtual method can be overridden by targets that want to emit something at the end of their file.
Reimplemented from llvm::AsmPrinter.
Definition at line 213 of file SystemZAsmPrinter.cpp.
References llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitSymbolValue(), llvm::TargetMachine::getDataLayout(), llvm::MCObjectFileInfo::getDataRelSection(), llvm::MachineModuleInfoELF::GetGVStubList(), llvm::MachineModuleInfo::getObjFileInfo(), llvm::AsmPrinter::getObjFileLowering(), llvm::DataLayout::getPointerSize(), i, llvm::SystemZSubtarget::isTargetELF(), llvm::AsmPrinter::MMI, llvm::AsmPrinter::OutStreamer, llvm::MCStreamer::SwitchSection(), and llvm::AsmPrinter::TM.
void SystemZAsmPrinter::EmitInstruction (const MachineInstr *) virtual
EmitInstruction - Targets should implement this to emit instructions.
Reimplemented from llvm::AsmPrinter.
Definition at line 69 of file SystemZAsmPrinter.cpp.
References llvm::MCInstBuilder::addExpr(), llvm::MCInstBuilder::addImm(), llvm::MCInstBuilder::addReg(), llvm::ISD::BR, llvm::MCStreamer::EmitInstruction(), llvm::MachineFunction::getContext(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::SystemZMC::getRegAsGR32(), llvm::SystemZMC::getRegAsGRH32(), LOWER_HIGH, LOWER_LOW, lowerRIEfLow(), llvm::AsmPrinter::MF, llvm::AsmPrinter::OutStreamer, llvm::GC::Return, and llvm::MCSymbolRefExpr::VK_PLT.
void SystemZAsmPrinter::EmitMachineConstantPoolValue (MachineConstantPoolValue * MCPV) virtual
Reimplemented from llvm::AsmPrinter.
Definition at line 172 of file SystemZAsmPrinter.cpp.
References llvm::MCSymbolRefExpr::Create(), llvm::MCStreamer::EmitValue(), llvm::TargetMachine::getDataLayout(), llvm::SystemZConstantPoolValue::getGlobalValue(), llvm::SystemZConstantPoolValue::getModifier(), getModifierVariantKind(), llvm::AsmPrinter::getSymbol(), llvm::MachineConstantPoolValue::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, and llvm::AsmPrinter::TM.
Referenced by getModifierVariantKind().
virtual const char* llvm::SystemZAsmPrinter::getPassName () const inline virtual
getPassName - Return a nice clean name for a pass. This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 35 of file SystemZAsmPrinter.h.
References LLVM_OVERRIDE, M, and llvm::A64CC::MI.
bool SystemZAsmPrinter::PrintAsmMemoryOperand (const MachineInstr * MI, unsigned OpNo, unsigned AsmVariant, const char * ExtraCode, raw_ostream & OS) virtual
PrintAsmMemoryOperand - Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address. Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Reimplemented from llvm::AsmPrinter.
Definition at line 202 of file SystemZAsmPrinter.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), and llvm::SystemZInstPrinter::printAddress().
bool SystemZAsmPrinter::PrintAsmOperand (const MachineInstr * MI, unsigned OpNo, unsigned AsmVariant, const char * ExtraCode, raw_ostream & O) virtual
PrintAsmOperand - Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant. Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
PrintAsmOperand - Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant. Targets should override this to format as appropriate.
Reimplemented from llvm::AsmPrinter.
Definition at line 185 of file SystemZAsmPrinter.cpp.
References llvm::MachineFunction::getContext(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::isImm(), llvm::AsmPrinter::MF, and llvm::SystemZInstPrinter::printOperand().
The documentation for this class was generated from the following files:
SystemZAsmPrinter.h
SystemZAsmPrinter.cpp