LLVM: llvm::GVMaterializer Class Reference
LLVM API Documentation
llvm::GVMaterializer Class Reference abstract
#include <GVMaterializer.h>
Public Member Functions
virtual ~GVMaterializer ()
virtual bool isMaterializable (const GlobalValue *GV) const =0
virtual bool isDematerializable (const GlobalValue *GV) const =0
virtual error_code Materialize (GlobalValue *GV)=0
virtual void Dematerialize (GlobalValue *)
virtual error_code MaterializeModule (Module *M)=0
Protected Member Functions
GVMaterializer ()
Detailed Description
Definition at line 29 of file GVMaterializer.h.
Constructor & Destructor Documentation
llvm::GVMaterializer::GVMaterializer () inline protected
Definition at line 31 of file GVMaterializer.h.
References isDematerializable(), isMaterializable(), Materialize(), and ~GVMaterializer().
GVMaterializer::~GVMaterializer () virtual
Definition at line 18 of file GVMaterializer.cpp.
Referenced by GVMaterializer().
Member Function Documentation
virtual void llvm::GVMaterializer::Dematerialize (GlobalValue *) inline virtual
Dematerialize - If the given GlobalValue is read in, and if the GVMaterializer supports it, release the memory for the GV, and set it up to be materialized lazily. If the Materializer doesn't support this capability, this method is a noop.
Reimplemented in llvm::BitcodeReader.
Definition at line 53 of file GVMaterializer.h.
References M, and MaterializeModule().
virtual bool llvm::GVMaterializer::isDematerializable (const GlobalValue * GV) const pure virtual
isDematerializable - True if GV has been materialized and can be dematerialized back to whatever backing store this GVMaterializer uses.
Implemented in llvm::BitcodeReader.
Referenced by GVMaterializer().
virtual bool llvm::GVMaterializer::isMaterializable (const GlobalValue * GV) const pure virtual
isMaterializable - True if GV can be materialized from whatever backing store this GVMaterializer uses and has not been materialized yet.
Implemented in llvm::BitcodeReader.
Referenced by GVMaterializer().
virtual error_code llvm::GVMaterializer::Materialize (GlobalValue * GV) pure virtual
Materialize - make sure the given GlobalValue is fully read.
Implemented in llvm::BitcodeReader.
Referenced by GVMaterializer().
virtual error_code llvm::GVMaterializer::MaterializeModule (Module * M) pure virtual
MaterializeModule - make sure the entire Module has been completely read.
Implemented in llvm::BitcodeReader.
Referenced by Dematerialize().
The documentation for this class was generated from the following files:
GVMaterializer.h
GVMaterializer.cpp