LLVM: llvm::DIEBlock Class Reference
LLVM API Documentation
llvm::DIEBlock Class Reference
DIEBlock - A block of values. Primarily used for location expressions.
#include <DIE.h>
Public Member Functions
DIEBlock ()
unsigned ComputeSize (AsmPrinter *AP)
dwarf::Form BestForm () const
virtual void EmitValue (AsmPrinter *AP, dwarf::Form Form) const
virtual unsigned SizeOf (AsmPrinter *AP, dwarf::Form Form) const
virtual void print (raw_ostream &O) const
Public Member Functions inherited from llvm::DIEValue
DIEValue (unsigned T)
virtual ~DIEValue ()
unsigned getType () const
void dump () const
Public Member Functions inherited from llvm::DIE
DIE (unsigned Tag)
virtual ~DIE ()
DIEAbbrev & getAbbrev ()
const DIEAbbrev & getAbbrev () const
unsigned getAbbrevNumber () const
dwarf::Tag getTag () const
unsigned getOffset () const
unsigned getSize () const
const std::vector< DIE * > & getChildren () const
const SmallVectorImpl< DIEValue * > & getValues () const
DIE * getParent () const
const DIE * getCompileUnit () const
const DIE * getCompileUnitOrNull () const
void setOffset (unsigned O)
void setSize (unsigned S)
void addValue (dwarf::Attribute Attribute, dwarf::Form Form, DIEValue *Value)
void addChild (DIE *Child)
DIEValue * findAttribute (uint16_t Attribute)
void print (raw_ostream &O, unsigned IndentCount=0) const
void dump ()
Static Public Member Functions
static bool classof (const DIEValue *E)
Additional Inherited Members
Public Types inherited from llvm::DIEValue
enum {
isInteger, isString, isExpr, isLabel,
isDelta, isEntry, isBlock
}
Protected Attributes inherited from llvm::DIEValue
unsigned Type
Protected Attributes inherited from llvm::DIE
unsigned Offset
unsigned Size
DIEAbbrev Abbrev
std::vector< DIE * > Children
DIE * Parent
SmallVector< DIEValue *, 12 > Values
Detailed Description
DIEBlock - A block of values. Primarily used for location expressions.
Definition at line 417 of file DIE.h.
Constructor & Destructor Documentation
llvm::DIEBlock::DIEBlock () inline
Definition at line 420 of file DIE.h.
Member Function Documentation
dwarf::Form llvm::DIEBlock::BestForm () const inline
BestForm - Choose the best form for data.
Definition at line 428 of file DIE.h.
Referenced by llvm::CompileUnit::addBlock().
static bool llvm::DIEBlock::classof (const DIEValue * E) inline static
Definition at line 444 of file DIE.h.
References llvm::DIEValue::getType().
unsigned DIEBlock::ComputeSize (AsmPrinter * AP)
ComputeSize - calculate the size of the block.
Definition at line 406 of file DIE.cpp.
References llvm::DIEAbbrevData::getForm(), i, and N.
Referenced by llvm::CompileUnit::addBlock().
void DIEBlock::EmitValue (AsmPrinter * Asm, dwarf::Form Form) const virtual
EmitValue - Emit block data.
Implements llvm::DIEValue.
Definition at line 418 of file DIE.cpp.
References llvm::AsmPrinter::EmitInt16(), llvm::AsmPrinter::EmitInt32(), llvm::AsmPrinter::EmitInt8(), llvm::AsmPrinter::EmitULEB128(), llvm::DIEAbbrevData::getForm(), i, llvm_unreachable, and N.
void DIEBlock::print (raw_ostream & O) const virtual
Implements llvm::DIEValue.
Definition at line 445 of file DIE.cpp.
References llvm::DIE::print().
unsigned DIEBlock::SizeOf (AsmPrinter * AP, dwarf::Form Form) const virtual
SizeOf - Determine size of block data in bytes.
Implements llvm::DIEValue.
Definition at line 434 of file DIE.cpp.
References llvm::MCAsmInfo::getULEB128Size(), and llvm_unreachable.
The documentation for this class was generated from the following files:
DIE.h
DIE.cpp