LLVM: llvm::SparcTargetMachine Class Reference
LLVM API Documentation
llvm::SparcTargetMachine Class Reference
#include <SparcTargetMachine.h>
Public Member Functions
SparcTargetMachine (const Target &T, StringRef TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL, bool is64bit)
virtual const SparcInstrInfo * getInstrInfo () const
virtual const TargetFrameLowering * getFrameLowering () const
virtual const SparcSubtarget * getSubtargetImpl () const
virtual const SparcRegisterInfo * getRegisterInfo () const
virtual const SparcTargetLowering * getTargetLowering () const
virtual const SparcSelectionDAGInfo * getSelectionDAGInfo () const
virtual SparcJITInfo * getJITInfo ()
virtual const DataLayout * getDataLayout () const
virtual TargetPassConfig * createPassConfig (PassManagerBase &PM)
virtual bool addCodeEmitter (PassManagerBase &PM, JITCodeEmitter &JCE)
Public Member Functions inherited from llvm::LLVMTargetMachine
virtual void addAnalysisPasses (PassManagerBase &PM)
Register analysis passes for this target with a pass manager.
virtual bool addPassesToEmitFile (PassManagerBase &PM, formatted_raw_ostream &Out, CodeGenFileType FileType, bool DisableVerify=true, AnalysisID StartAfter=0, AnalysisID StopAfter=0)
virtual bool addPassesToEmitMachineCode (PassManagerBase &PM, JITCodeEmitter &MCE, bool DisableVerify=true)
virtual bool addPassesToEmitMC (PassManagerBase &PM, MCContext *&Ctx, raw_ostream &OS, bool DisableVerify=true)
Public Member Functions inherited from llvm::TargetMachine
virtual ~TargetMachine ()
const Target & getTarget () const
const StringRef getTargetTriple () const
const StringRef getTargetCPU () const
const StringRef getTargetFeatureString () const
void resetTargetOptions (const MachineFunction *MF) const
Reset the target options based on the function's attributes.
const MCAsmInfo * getMCAsmInfo () const
template<typename STC >
const STC & getSubtarget () const
virtual const TargetIntrinsicInfo * getIntrinsicInfo () const
virtual const InstrItineraryData * getInstrItineraryData () const
bool hasMCRelaxAll () const
void setMCRelaxAll (bool Value)
bool hasMCSaveTempLabels () const
void setMCSaveTempLabels (bool Value)
bool hasMCNoExecStack () const
hasMCNoExecStack - Check whether an executable stack is not needed.
void setMCNoExecStack (bool Value)
setMCNoExecStack - Set whether an executabel stack is not needed.
bool hasMCUseLoc () const
hasMCUseLoc - Check whether we should use dwarf's .loc directive.
void setMCUseLoc (bool Value)
setMCUseLoc - Set whether all we should use dwarf's .loc directive.
bool hasMCUseCFI () const
hasMCUseCFI - Check whether we should use dwarf's .cfi_* directives.
void setMCUseCFI (bool Value)
setMCUseCFI - Set whether all we should use dwarf's .cfi_* directives.
bool hasMCUseDwarfDirectory () const
void setMCUseDwarfDirectory (bool Value)
Reloc::Model getRelocationModel () const
CodeModel::Model getCodeModel () const
TLSModel::Model getTLSModel (const GlobalValue *GV) const
CodeGenOpt::Level getOptLevel () const
void setOptLevel (CodeGenOpt::Level Level) const
Overrides the optimization level.
void setFastISel (bool Enable)
bool shouldPrintMachineCode () const
Additional Inherited Members
Public Types inherited from llvm::TargetMachine
enum CodeGenFileType { CGFT_AssemblyFile, CGFT_ObjectFile, CGFT_Null }
Static Public Member Functions inherited from llvm::TargetMachine
static bool getAsmVerbosityDefault ()
static void setAsmVerbosityDefault (bool)
static bool getDataSections ()
static bool getFunctionSections ()
static void setDataSections (bool)
setDataSections - Set if the data are emit into separate sections.
static void setFunctionSections (bool)
Public Attributes inherited from llvm::TargetMachine
TargetOptions Options
Protected Member Functions inherited from llvm::LLVMTargetMachine
LLVMTargetMachine (const Target &T, StringRef TargetTriple, StringRef CPU, StringRef FS, TargetOptions Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
void initAsmInfo ()
Protected Member Functions inherited from llvm::TargetMachine
TargetMachine (const Target &T, StringRef TargetTriple, StringRef CPU, StringRef FS, const TargetOptions &Options)
Protected Attributes inherited from llvm::TargetMachine
const Target & TheTarget
TheTarget - The Target that this machine was created for.
std::string TargetTriple
std::string TargetCPU
std::string TargetFS
MCCodeGenInfo * CodeGenInfo
const MCAsmInfo * AsmInfo
unsigned MCRelaxAll: 1
unsigned MCNoExecStack: 1
unsigned MCSaveTempLabels: 1
unsigned MCUseLoc: 1
unsigned MCUseCFI: 1
unsigned MCUseDwarfDirectory: 1
Detailed Description
Definition at line 29 of file SparcTargetMachine.h.
Constructor & Destructor Documentation
SparcTargetMachine::SparcTargetMachine (const Target & T, StringRef TT, StringRef CPU, StringRef FS, const TargetOptions & Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL, bool is64bit)
SparcTargetMachine ctor - Create an ILP32 architecture model
Definition at line 28 of file SparcTargetMachine.cpp.
References llvm::LLVMTargetMachine::initAsmInfo(), and llvm::SystemZISD::TM.
Member Function Documentation
bool SparcTargetMachine::addCodeEmitter (PassManagerBase & , JITCodeEmitter &) virtual
addCodeEmitter - This pass should be overridden by the target to add a code emitter, if supported. If this is not supported, 'true' should be returned.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 68 of file SparcTargetMachine.cpp.
References llvm::createSparcDelaySlotFillerPass(), and llvm::createSparcJITCodeEmitterPass().
Referenced by getDataLayout().
TargetPassConfig * SparcTargetMachine::createPassConfig (PassManagerBase & PM) virtual
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
Targets may override this to extend TargetPassConfig.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 59 of file SparcTargetMachine.cpp.
References llvm::createSparcISelDag().
Referenced by getDataLayout().
virtual const DataLayout* llvm::SparcTargetMachine::getDataLayout () const inline virtual
Reimplemented from llvm::TargetMachine.
Definition at line 60 of file SparcTargetMachine.h.
References addCodeEmitter(), and createPassConfig().
virtual const TargetFrameLowering* llvm::SparcTargetMachine::getFrameLowering () const inline virtual
Reimplemented from llvm::TargetMachine.
Definition at line 44 of file SparcTargetMachine.h.
virtual const SparcInstrInfo* llvm::SparcTargetMachine::getInstrInfo () const inline virtual
Reimplemented from llvm::TargetMachine.
Definition at line 43 of file SparcTargetMachine.h.
virtual SparcJITInfo* llvm::SparcTargetMachine::getJITInfo () inline virtual
getJITInfo - If this target supports a JIT, return information for it, otherwise return null.
Reimplemented from llvm::TargetMachine.
Definition at line 57 of file SparcTargetMachine.h.
virtual const SparcRegisterInfo* llvm::SparcTargetMachine::getRegisterInfo () const inline virtual
getRegisterInfo - If register information is available, return it. If not, return null. This is kept separate from RegInfo until RegInfo has details of graph coloring register allocation removed from it.
Reimplemented from llvm::TargetMachine.
Definition at line 48 of file SparcTargetMachine.h.
References llvm::SparcInstrInfo::getRegisterInfo().
virtual const SparcSelectionDAGInfo* llvm::SparcTargetMachine::getSelectionDAGInfo () const inline virtual
Reimplemented from llvm::TargetMachine.
Definition at line 54 of file SparcTargetMachine.h.
virtual const SparcSubtarget* llvm::SparcTargetMachine::getSubtargetImpl () const inline virtual
getSubtargetImpl - virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
Reimplemented from llvm::TargetMachine.
Definition at line 47 of file SparcTargetMachine.h.
virtual const SparcTargetLowering* llvm::SparcTargetMachine::getTargetLowering () const inline virtual
Reimplemented from llvm::TargetMachine.
Definition at line 51 of file SparcTargetMachine.h.
The documentation for this class was generated from the following files:
SparcTargetMachine.h
SparcTargetMachine.cpp