LLVM: llvm::ARMTargetStreamer Class Reference
LLVM API Documentation
llvm::ARMTargetStreamer Class Reference abstract
#include <MCStreamer.h>
Public Member Functions
virtual void emitFnStart ()=0
virtual void emitFnEnd ()=0
virtual void emitCantUnwind ()=0
virtual void emitPersonality (const MCSymbol *Personality)=0
virtual void emitHandlerData ()=0
virtual void emitSetFP (unsigned FpReg, unsigned SpReg, int64_t Offset=0)=0
virtual void emitPad (int64_t Offset)=0
virtual void emitRegSave (const SmallVectorImpl< unsigned > &RegList, bool isVector)=0
virtual void switchVendor (StringRef Vendor)=0
virtual void emitAttribute (unsigned Attribute, unsigned Value)=0
virtual void emitTextAttribute (unsigned Attribute, StringRef String)=0
virtual void emitFPU (unsigned FPU)=0
virtual void finishAttributeSection ()=0
Public Member Functions inherited from llvm::MCTargetStreamer
virtual ~MCTargetStreamer ()
void setStreamer (MCStreamer *S)
Additional Inherited Members
Protected Attributes inherited from llvm::MCTargetStreamer
MCStreamer * Streamer
Detailed Description
Definition at line 78 of file MCStreamer.h.
Member Function Documentation
virtual void llvm::ARMTargetStreamer::emitAttribute (unsigned Attribute, unsigned Value) pure virtual
Referenced by getArchForCPU().
virtual void llvm::ARMTargetStreamer::emitCantUnwind () pure virtual
Referenced by llvm::ARMException::EndFunction().
virtual void llvm::ARMTargetStreamer::emitFnEnd () pure virtual
Referenced by llvm::ARMException::EndFunction().
virtual void llvm::ARMTargetStreamer::emitFnStart () pure virtual
Referenced by llvm::ARMException::BeginFunction().
virtual void llvm::ARMTargetStreamer::emitFPU (unsigned FPU) pure virtual
Referenced by getArchForCPU().
virtual void llvm::ARMTargetStreamer::emitHandlerData () pure virtual
Referenced by llvm::ARMException::EndFunction().
virtual void llvm::ARMTargetStreamer::emitPad (int64_t Offset) pure virtual
Referenced by llvm::ARMAsmPrinter::EmitJump2Table().
virtual void llvm::ARMTargetStreamer::emitPersonality (const MCSymbol * Personality) pure virtual
Referenced by llvm::ARMException::EndFunction().
virtual void llvm::ARMTargetStreamer::emitRegSave (const SmallVectorImpl< unsigned > & RegList, bool isVector) pure virtual
Referenced by llvm::ARMAsmPrinter::EmitJump2Table().
virtual void llvm::ARMTargetStreamer::emitSetFP (unsigned FpReg, unsigned SpReg, int64_t Offset = 0) pure virtual
Referenced by llvm::ARMAsmPrinter::EmitJump2Table().
virtual void llvm::ARMTargetStreamer::emitTextAttribute (unsigned Attribute, StringRef String) pure virtual
Referenced by getArchForCPU().
virtual void llvm::ARMTargetStreamer::finishAttributeSection () pure virtual
Referenced by getArchForCPU(), and GetFPUName().
virtual void llvm::ARMTargetStreamer::switchVendor (StringRef Vendor) pure virtual
Referenced by getArchForCPU().
The documentation for this class was generated from the following files:
MCStreamer.h
MCStreamer.cpp