LLVM: llvm::SCEVCastExpr Class Reference
LLVM API Documentation
llvm::SCEVCastExpr Class Reference
#include <ScalarEvolutionExpressions.h>
Public Member Functions
const SCEV * getOperand () const
Type * getType () const
Public Member Functions inherited from llvm::SCEV
SCEV (const FoldingSetNodeIDRef ID, unsigned SCEVTy)
unsigned getSCEVType () const
Type * getType () const
bool isZero () const
bool isOne () const
bool isAllOnesValue () const
bool isNonConstantNegative () const
void print (raw_ostream &OS) const
void dump () const
Public Member Functions inherited from llvm::FoldingSetImpl::Node
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static bool classof (const SCEV *S)
Methods for support type inquiry through isa, cast, and dyn_cast:
Protected Member Functions
SCEVCastExpr (const FoldingSetNodeIDRef ID, unsigned SCEVTy, const SCEV *op, Type *ty)
Protected Attributes
const SCEV * Op
Type * Ty
Protected Attributes inherited from llvm::SCEV
unsigned short SubclassData
Additional Inherited Members
Public Types inherited from llvm::SCEV
enum NoWrapFlags {
FlagAnyWrap = 0, FlagNW = (1 << 0), FlagNUW = (1 << 1), FlagNSW = (1 << 2),
NoWrapMask = (1 << 3) -1
}
Detailed Description
SCEVCastExpr - This is the base class for unary cast operator classes.
Definition at line 57 of file ScalarEvolutionExpressions.h.
Constructor & Destructor Documentation
SCEVCastExpr::SCEVCastExpr (const FoldingSetNodeIDRef ID, unsigned SCEVTy, const SCEV * op, Type * ty) protected
Definition at line 335 of file ScalarEvolution.cpp.
References llvm::SCEV::getType(), llvm::Type::isIntegerTy(), llvm::Type::isPointerTy(), Op, llvm::scSignExtend, llvm::scTruncate, llvm::scZeroExtend, and Ty.
Member Function Documentation
static bool llvm::SCEVCastExpr::classof (const SCEV * S) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 70 of file ScalarEvolutionExpressions.h.
References llvm::SCEV::getSCEVType(), llvm::scSignExtend, llvm::scTruncate, and llvm::scZeroExtend.
const SCEV* llvm::SCEVCastExpr::getOperand () const inline
Definition at line 66 of file ScalarEvolutionExpressions.h.
Referenced by BuildConstantFromSCEV(), llvm::SCEVAddRecExpr::evaluateAtIteration(), llvm::ScalarEvolution::getAddExpr(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), getPointerOperand(), llvm::SCEVExpander::hoistIVInc(), llvm::SCEVUnknown::isOffsetOf(), llvm::SCEV::print(), llvm::SCEVParameterRewriter::visitSignExtendExpr(), llvm::SCEVApplyRewriter::visitSignExtendExpr(), llvm::SCEVParameterRewriter::visitTruncateExpr(), llvm::SCEVApplyRewriter::visitTruncateExpr(), llvm::SCEVParameterRewriter::visitZeroExtendExpr(), and llvm::SCEVApplyRewriter::visitZeroExtendExpr().
Type* llvm::SCEVCastExpr::getType () const inline
Definition at line 67 of file ScalarEvolutionExpressions.h.
Referenced by BuildConstantFromSCEV(), llvm::SCEVAddRecExpr::delinearize(), llvm::SCEVAddRecExpr::evaluateAtIteration(), llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getAddRecExpr(), llvm::ScalarEvolution::getMulExpr(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), getPointerOperand(), llvm::ScalarEvolution::getSMaxExpr(), llvm::ScalarEvolution::getUMaxExpr(), llvm::SCEVExpander::hoistIVInc(), llvm::SCEV::print(), llvm::SCEVParameterRewriter::visitSignExtendExpr(), llvm::SCEVApplyRewriter::visitSignExtendExpr(), llvm::SCEVParameterRewriter::visitTruncateExpr(), llvm::SCEVApplyRewriter::visitTruncateExpr(), llvm::SCEVParameterRewriter::visitZeroExtendExpr(), and llvm::SCEVApplyRewriter::visitZeroExtendExpr().
Member Data Documentation
const SCEV* llvm::SCEVCastExpr::Op protected
Definition at line 59 of file ScalarEvolutionExpressions.h.
Referenced by BuildConstantFromSCEV(), llvm::ScalarEvolution::getSignedRange(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::ScalarEvolution::getTruncateExpr(), llvm::ScalarEvolution::getUDivExpr(), llvm::ScalarEvolution::getZeroExtendExpr(), and SCEVCastExpr().
Type* llvm::SCEVCastExpr::Ty protected
Definition at line 60 of file ScalarEvolutionExpressions.h.
Referenced by llvm::ScalarEvolution::getAddExpr(), llvm::ScalarEvolution::getEffectiveSCEVType(), llvm::ScalarEvolution::getMulExpr(), llvm::ScalarEvolution::getNegativeSCEV(), llvm::ScalarEvolution::getNotSCEV(), llvm::ScalarEvolution::getOffsetOfExpr(), llvm::ScalarEvolution::getSignedRange(), getSignExtendAddRecStart(), llvm::ScalarEvolution::getSignExtendExpr(), llvm::ScalarEvolution::getSizeOfExpr(), llvm::ScalarEvolution::getTruncateExpr(), llvm::ScalarEvolution::getUDivExpr(), llvm::ScalarEvolution::getUnsignedRange(), llvm::ScalarEvolution::getZeroExtendExpr(), llvm::SCEVUnknown::isAlignOf(), llvm::SCEVUnknown::isOffsetOf(), and SCEVCastExpr().
The documentation for this class was generated from the following files:
ScalarEvolutionExpressions.h
ScalarEvolution.cpp