LLVM: llvm::X86COFFMachineModuleInfo Class Reference
LLVM API Documentation
llvm::X86COFFMachineModuleInfo Class Reference
#include <X86COFFMachineModuleInfo.h>
Public Types
typedef DenseSet< MCSymbol const * >::const_iterator externals_iterator
Public Types inherited from llvm::MachineModuleInfoImpl
typedef PointerIntPair< MCSymbol *, 1, bool > StubValueTy
typedef std::vector< std::pair< MCSymbol *, StubValueTy > > SymbolListTy
Public Member Functions
X86COFFMachineModuleInfo (const MachineModuleInfo &)
virtual ~X86COFFMachineModuleInfo ()
void addExternalFunction (MCSymbol *Symbol)
externals_iterator externals_begin () const
externals_iterator externals_end () const
Public Member Functions inherited from llvm::MachineModuleInfoImpl
virtual ~MachineModuleInfoImpl ()
Additional Inherited Members
Static Protected Member Functions inherited from llvm::MachineModuleInfoImpl
static SymbolListTy GetSortedStubs (const DenseMap< MCSymbol *, StubValueTy > &)
Detailed Description
X86COFFMachineModuleInfo - This is a MachineModuleInfoImpl implementation for X86 COFF targets.
Definition at line 27 of file X86COFFMachineModuleInfo.h.
Member Typedef Documentation
typedef DenseSet<MCSymbol const *>::const_iterator llvm::X86COFFMachineModuleInfo::externals_iterator
Definition at line 37 of file X86COFFMachineModuleInfo.h.
Constructor & Destructor Documentation
llvm::X86COFFMachineModuleInfo::X86COFFMachineModuleInfo (const MachineModuleInfo &) inline
Definition at line 30 of file X86COFFMachineModuleInfo.h.
References ~X86COFFMachineModuleInfo().
X86COFFMachineModuleInfo::~X86COFFMachineModuleInfo () virtual
Definition at line 18 of file X86COFFMachineModuleInfo.cpp.
Referenced by X86COFFMachineModuleInfo().
Member Function Documentation
void llvm::X86COFFMachineModuleInfo::addExternalFunction (MCSymbol * Symbol) inline
Definition at line 33 of file X86COFFMachineModuleInfo.h.
References llvm::DenseSet< ValueT, ValueInfoT >::insert().
externals_iterator llvm::X86COFFMachineModuleInfo::externals_begin () const inline
Definition at line 38 of file X86COFFMachineModuleInfo.h.
References llvm::DenseSet< ValueT, ValueInfoT >::begin().
Referenced by llvm::X86AsmPrinter::EmitEndOfAsmFile().
externals_iterator llvm::X86COFFMachineModuleInfo::externals_end () const inline
Definition at line 39 of file X86COFFMachineModuleInfo.h.
References llvm::DenseSet< ValueT, ValueInfoT >::end().
Referenced by llvm::X86AsmPrinter::EmitEndOfAsmFile().
The documentation for this class was generated from the following files:
X86COFFMachineModuleInfo.h
X86COFFMachineModuleInfo.cpp