LLVM: llvm::constant_iterator Class Reference
LLVM API Documentation
llvm::constant_iterator Class Reference
#include <ConstantsScanner.h>
Public Member Functions
constant_iterator (const Function *F)
constant_iterator (const Function *F, bool)
bool operator== (const _Self &x) const
bool operator!= (const _Self &x) const
pointer operator* () const
pointer operator-> () const
_Self & operator++ ()
_Self operator++ (int)
bool atEnd () const
Detailed Description
Definition at line 25 of file ConstantsScanner.h.
Constructor & Destructor Documentation
llvm::constant_iterator::constant_iterator (const Function * F) inline
Definition at line 39 of file ConstantsScanner.h.
References llvm::User::getNumOperands(), llvm::inst_end(), and operator++().
Referenced by llvm::constant_begin(), and llvm::constant_end().
llvm::constant_iterator::constant_iterator (const Function * F, bool) inline
Definition at line 46 of file ConstantsScanner.h.
Member Function Documentation
bool llvm::constant_iterator::atEnd () const inline
Definition at line 80 of file ConstantsScanner.h.
References llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t >::atEnd().
bool llvm::constant_iterator::operator!= (const _Self & x) const inline
Definition at line 52 of file ConstantsScanner.h.
References operator==().
pointer llvm::constant_iterator::operator* () const inline
Definition at line 54 of file ConstantsScanner.h.
References llvm::User::getOperand().
Referenced by operator->().
_Self& llvm::constant_iterator::operator++ () inline
Definition at line 60 of file ConstantsScanner.h.
References llvm::InstIterator< _BB_t, _BB_i_t, _BI_t, _II_t >::atEnd(), and llvm::User::getNumOperands().
Referenced by constant_iterator().
_Self llvm::constant_iterator::operator++ (int) inline
Definition at line 76 of file ConstantsScanner.h.
pointer llvm::constant_iterator::operator-> () const inline
Definition at line 58 of file ConstantsScanner.h.
References operator*().
bool llvm::constant_iterator::operator== (const _Self & x) const inline
Definition at line 50 of file ConstantsScanner.h.
Referenced by operator!=().
The documentation for this class was generated from the following file:
ConstantsScanner.h