LLVM: llvm::NVPTXSubtarget Class Reference
LLVM API Documentation
llvm::NVPTXSubtarget Class Reference
#include <NVPTXSubtarget.h>
Public Member Functions
NVPTXSubtarget (const std::string &TT, const std::string &CPU, const std::string &FS, bool is64Bit)
bool hasBrkPt () const
bool hasAtomRedG32 () const
bool hasAtomRedS32 () const
bool hasAtomRedG64 () const
bool hasAtomRedS64 () const
bool hasAtomRedGen32 () const
bool hasAtomRedGen64 () const
bool hasAtomAddF32 () const
bool hasVote () const
bool hasDouble () const
bool reqPTX20 () const
bool hasF32FTZ () const
bool hasFMAF32 () const
bool hasFMAF64 () const
bool hasLDG () const
bool hasLDU () const
bool hasGenericLdSt () const
bool hasHWROT32 () const
bool hasSWROT32 () const
bool hasROT32 () const
bool hasROT64 () const
bool is64Bit () const
unsigned int getSmVersion () const
NVPTX::DrvInterface getDrvInterface () const
std::string getTargetName () const
unsigned getPTXVersion () const
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
std::string getDataLayout () const
Detailed Description
Definition at line 27 of file NVPTXSubtarget.h.
Constructor & Destructor Documentation
NVPTXSubtarget::NVPTXSubtarget (const std::string & TT, const std::string & CPU, const std::string & FS, bool is64Bit)
This constructor initializes the data members to match that of the specified module.
Definition at line 26 of file NVPTXSubtarget.cpp.
References llvm::NVPTX::CUDA, llvm::Triple::getOS(), llvm_unreachable, llvm::NVPTX::NVCL, llvm::Triple::NVCL, ParseSubtargetFeatures(), and T.
Member Function Documentation
std::string llvm::NVPTXSubtarget::getDataLayout () const inline
Definition at line 78 of file NVPTXSubtarget.h.
References is64Bit(), and p.
NVPTX::DrvInterface llvm::NVPTXSubtarget::getDrvInterface () const inline
Definition at line 71 of file NVPTXSubtarget.h.
unsigned llvm::NVPTXSubtarget::getPTXVersion () const inline
Definition at line 74 of file NVPTXSubtarget.h.
References ParseSubtargetFeatures().
unsigned int llvm::NVPTXSubtarget::getSmVersion () const inline
Definition at line 70 of file NVPTXSubtarget.h.
Referenced by llvm::NVPTXTargetLowering::getPrototype(), llvm::NVPTXTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerFormalArguments(), and llvm::NVPTXTargetLowering::LowerReturn().
std::string llvm::NVPTXSubtarget::getTargetName () const inline
Definition at line 72 of file NVPTXSubtarget.h.
bool llvm::NVPTXSubtarget::hasAtomAddF32 () const inline
Definition at line 53 of file NVPTXSubtarget.h.
bool llvm::NVPTXSubtarget::hasAtomRedG32 () const inline
Definition at line 47 of file NVPTXSubtarget.h.
bool llvm::NVPTXSubtarget::hasAtomRedG64 () const inline
Definition at line 49 of file NVPTXSubtarget.h.
bool llvm::NVPTXSubtarget::hasAtomRedGen32 () const inline
Definition at line 51 of file NVPTXSubtarget.h.
bool llvm::NVPTXSubtarget::hasAtomRedGen64 () const inline
Definition at line 52 of file NVPTXSubtarget.h.
bool llvm::NVPTXSubtarget::hasAtomRedS32 () const inline
Definition at line 48 of file NVPTXSubtarget.h.
bool llvm::NVPTXSubtarget::hasAtomRedS64 () const inline
Definition at line 50 of file NVPTXSubtarget.h.
bool llvm::NVPTXSubtarget::hasBrkPt () const inline
Definition at line 46 of file NVPTXSubtarget.h.
bool llvm::NVPTXSubtarget::hasDouble () const inline
Definition at line 55 of file NVPTXSubtarget.h.
bool llvm::NVPTXSubtarget::hasF32FTZ () const inline
Definition at line 57 of file NVPTXSubtarget.h.
bool llvm::NVPTXSubtarget::hasFMAF32 () const inline
Definition at line 58 of file NVPTXSubtarget.h.
bool llvm::NVPTXSubtarget::hasFMAF64 () const inline
Definition at line 59 of file NVPTXSubtarget.h.
bool llvm::NVPTXSubtarget::hasGenericLdSt () const inline
Definition at line 62 of file NVPTXSubtarget.h.
bool llvm::NVPTXSubtarget::hasHWROT32 () const inline
Definition at line 63 of file NVPTXSubtarget.h.
Referenced by hasROT32().
bool llvm::NVPTXSubtarget::hasLDG () const inline
Definition at line 60 of file NVPTXSubtarget.h.
bool llvm::NVPTXSubtarget::hasLDU () const inline
Definition at line 61 of file NVPTXSubtarget.h.
bool llvm::NVPTXSubtarget::hasROT32 () const inline
Definition at line 65 of file NVPTXSubtarget.h.
References hasHWROT32(), and hasSWROT32().
Referenced by llvm::NVPTXTargetLowering::NVPTXTargetLowering().
bool llvm::NVPTXSubtarget::hasROT64 () const inline
Definition at line 66 of file NVPTXSubtarget.h.
Referenced by llvm::NVPTXTargetLowering::NVPTXTargetLowering().
bool llvm::NVPTXSubtarget::hasSWROT32 () const inline
Definition at line 64 of file NVPTXSubtarget.h.
Referenced by hasROT32().
bool llvm::NVPTXSubtarget::hasVote () const inline
Definition at line 54 of file NVPTXSubtarget.h.
bool llvm::NVPTXSubtarget::is64Bit () const inline
Definition at line 68 of file NVPTXSubtarget.h.
Referenced by getDataLayout().
void llvm::NVPTXSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
Referenced by getPTXVersion(), and NVPTXSubtarget().
bool llvm::NVPTXSubtarget::reqPTX20 () const inline
Definition at line 56 of file NVPTXSubtarget.h.
The documentation for this class was generated from the following files:
NVPTXSubtarget.h
NVPTXSubtarget.cpp