LLVM: llvm::LibCallSimplifierImpl Class Reference
LLVM API Documentation
llvm::LibCallSimplifierImpl Class Reference
Public Member Functions
LibCallSimplifierImpl (const DataLayout *TD, const TargetLibraryInfo *TLI, const LibCallSimplifier *LCS, bool UnsafeFPShrink=false)
Value * optimizeCall (CallInst *CI)
LibCallOptimization * lookupOptimization (CallInst *CI)
bool hasFloatVersion (StringRef FuncName)
Detailed Description
Definition at line 1910 of file SimplifyLibCalls.cpp.
Constructor & Destructor Documentation
llvm::LibCallSimplifierImpl::LibCallSimplifierImpl (const DataLayout * TD, const TargetLibraryInfo * TLI, const LibCallSimplifier * LCS, bool UnsafeFPShrink = false) inline
Definition at line 1921 of file SimplifyLibCalls.cpp.
References UnsafeFPShrink.
Member Function Documentation
bool llvm::LibCallSimplifierImpl::hasFloatVersion (StringRef FuncName)
Definition at line 1936 of file SimplifyLibCalls.cpp.
References FuncName, llvm::TargetLibraryInfo::getLibFunc(), and llvm::TargetLibraryInfo::has().
LibCallOptimization * llvm::LibCallSimplifierImpl::lookupOptimization (CallInst * CI)
Definition at line 1999 of file SimplifyLibCalls.cpp.
References llvm::LibFunc::abs, llvm::Abs, llvm::LibFunc::acos, llvm::LibFunc::acosh, llvm::LibFunc::asin, llvm::LibFunc::asinh, llvm::LibFunc::atan, llvm::LibFunc::atanh, llvm::LibFunc::cbrt, llvm::LibFunc::ceil, llvm::LibFunc::cos, llvm::LibFunc::cosf, llvm::LibFunc::cosh, llvm::LibFunc::cosl, llvm::LibFunc::cospi, llvm::LibFunc::cospif, llvm::StringRef::endswith(), llvm::ErrorReporting, llvm::ErrorReporting0(), llvm::ErrorReporting1(), llvm::LibFunc::exp, llvm::LibFunc::exp10, llvm::LibFunc::exp2, llvm::Intrinsic::exp2, llvm::LibFunc::exp2l, llvm::LibFunc::expm1, llvm::LibFunc::fabs, llvm::LibFunc::ffs, llvm::FFS, llvm::LibFunc::ffsl, llvm::LibFunc::ffsll, llvm::LibFunc::fiprintf, llvm::LibFunc::floor, llvm::LibFunc::fprintf, llvm::FPrintF, llvm::LibFunc::fputc, llvm::LibFunc::fputs, llvm::FPuts, llvm::LibFunc::fwrite, llvm::FWrite, llvm::CallInst::getCalledFunction(), llvm::TargetLibraryInfo::getLibFunc(), llvm::Value::getName(), llvm::TargetLibraryInfo::has(), llvm::LibFunc::isascii, llvm::IsAscii, llvm::LibFunc::isdigit, llvm::IsDigit, llvm::LibFunc::labs, llvm::LibFunc::llabs, llvm::LibFunc::log, llvm::LibFunc::log10, llvm::LibFunc::log1p, llvm::LibFunc::log2, llvm::LibFunc::logb, llvm::LibFunc::memcmp, llvm::MemCmp, llvm::LibFunc::memcpy, llvm::MemCpy, llvm::LibFunc::memcpy_chk, llvm::MemCpyChk, llvm::LibFunc::memmove, llvm::MemMove, llvm::MemMoveChk, llvm::LibFunc::memset, llvm::MemSet, llvm::MemSetChk, llvm::LibFunc::nearbyint, llvm::LibFunc::perror, llvm::LibFunc::pow, llvm::Intrinsic::pow, llvm::LibFunc::powf, llvm::LibFunc::powl, llvm::LibFunc::printf, llvm::PrintF, llvm::LibFunc::puts, llvm::Puts, llvm::LibFunc::rint, llvm::LibFunc::round, llvm::LibFunc::sin, llvm::SinCosPi, llvm::LibFunc::sinh, llvm::LibFunc::sinpi, llvm::LibFunc::sinpif, llvm::LibFunc::sprintf, llvm::SPrintF, llvm::LibFunc::sqrt, llvm::LibFunc::stpcpy, llvm::StpCpy, llvm::StpCpyChk, llvm::LibFunc::strcat, llvm::StrCat, llvm::LibFunc::strchr, llvm::StrChr, llvm::LibFunc::strcmp, llvm::StrCmp, llvm::LibFunc::strcpy, llvm::StrCpy, llvm::StrCpyChk, llvm::LibFunc::strcspn, llvm::StrCSpn, llvm::LibFunc::strlen, llvm::StrLen, llvm::LibFunc::strncat, llvm::StrNCat, llvm::LibFunc::strncmp, llvm::StrNCmp, llvm::LibFunc::strncpy, llvm::StrNCpy, llvm::StrNCpyChk, llvm::LibFunc::strpbrk, llvm::StrPBrk, llvm::LibFunc::strrchr, llvm::StrRChr, llvm::LibFunc::strspn, llvm::StrSpn, llvm::LibFunc::strstr, llvm::StrStr, llvm::StrTo, llvm::LibFunc::strtod, llvm::LibFunc::strtof, llvm::LibFunc::strtol, llvm::LibFunc::strtold, llvm::LibFunc::strtoll, llvm::LibFunc::strtoul, llvm::LibFunc::strtoull, llvm::LibFunc::tan, llvm::LibFunc::tanh, llvm::LibFunc::toascii, llvm::ToAscii, llvm::LibFunc::trunc, llvm::UnaryDoubleFP(), UnsafeFPShrink, llvm::UnsafeUnaryDoubleFP(), and llvm::LibFunc::vfprintf.
Value * llvm::LibCallSimplifierImpl::optimizeCall (CallInst * CI)
Definition at line 2174 of file SimplifyLibCalls.cpp.
The documentation for this class was generated from the following file:
SimplifyLibCalls.cpp