LLVM: llvm::DAGTypeLegalizer Class Reference
LLVM API Documentation
llvm::DAGTypeLegalizer Class Reference
#include <LegalizeTypes.h>
Public Types
enum NodeIdFlags { ReadyToProcess = 0, NewNode = -1, Unanalyzed = -2, Processed = -3 }
Public Member Functions
DAGTypeLegalizer (SelectionDAG &dag)
bool run ()
void NoteDeletion (SDNode *Old, SDNode *New)
SelectionDAG & getDAG () const
Detailed Description
DAGTypeLegalizer - This takes an arbitrary SelectionDAG as input and hacks on it until only value types the target machine can handle are left. This involves promoting small sizes to large sizes or splitting up large values into small values.
Definition at line 35 of file LegalizeTypes.h.
Member Enumeration Documentation
enum llvm::DAGTypeLegalizer::NodeIdFlags
Enumerator
ReadyToProcess
ReadyToProcess - All operands have been processed, so this node is ready to be handled.
NewNode
NewNode - This is a new node, not before seen, that was created in the process of legalizing some other node.
Unanalyzed
Unanalyzed - This node's ID needs to be set to the number of its unprocessed operands.
Processed
Processed - This is a node that has already been processed.
Definition at line 41 of file LegalizeTypes.h.
Constructor & Destructor Documentation
llvm::DAGTypeLegalizer::DAGTypeLegalizer (SelectionDAG & dag) inline explicit
Definition at line 123 of file LegalizeTypes.h.
References llvm::MVT::LAST_VALUETYPE, and llvm::MVT::MAX_ALLOWED_VALUETYPE.
Referenced by llvm::SelectionDAG::LegalizeTypes().
Member Function Documentation
SelectionDAG& llvm::DAGTypeLegalizer::getDAG () const inline
Definition at line 142 of file LegalizeTypes.h.
References llvm::tgtok::Code, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::EVT::getScalarType(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::SelectionDAG::getZeroExtendInReg(), llvm::HexagonISD::Hi, llvm::EVT::isInteger(), llvm::EVT::isVector(), llvm::A64DB::LD, llvm::HexagonISD::Lo, llvm::ISD::SIGN_EXTEND_INREG, and llvm::A64DB::ST.
Referenced by run().
void llvm::DAGTypeLegalizer::NoteDeletion (SDNode * Old, SDNode * New) inline
Definition at line 135 of file LegalizeTypes.h.
References llvm::SDNode::getNumValues(), and i.
Referenced by run().
bool DAGTypeLegalizer::run ()
run - This is the main entry point for the type legalizer. This does a top-down traversal of the dag, legalizing types as it goes. Returns "true" if it made any changes.
Definition at line 179 of file LegalizeTypes.cpp.
References llvm::ISD::ADD, llvm::SelectionDAG::allnodes_begin(), llvm::SelectionDAG::allnodes_end(), llvm::ISD::ANY_EXTEND, llvm::SmallVectorImpl< T >::append(), llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::back(), llvm::ISD::BITCAST, llvm::TargetLoweringBase::Custom, llvm::SelectionDAG::DAGUpdateListener, llvm::dbgs(), DEBUG, llvm::NVPTXISD::Dummy, llvm::SDNode::dump(), llvm::SmallVectorBase::empty(), llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::empty(), EnableExpensiveChecks, llvm::ISD::EXTRACT_ELEMENT, getDAG(), llvm::TargetLoweringBase::getExtendForContent(), llvm::EVT::getIntegerVT(), llvm::SDValue::getNode(), llvm::SDNode::getNodeId(), llvm::SDNode::getNumOperands(), llvm::SDNode::getNumValues(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getRoot(), llvm::EVT::getSizeInBits(), llvm::EVT::getTypeForEVT(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::HexagonISD::Hi, i, I, llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::insert(), llvm::TargetLowering::ArgListEntry::isSExt, llvm::EVT::isVector(), llvm::TargetLowering::ArgListEntry::isZExt, llvm_unreachable, llvm::HexagonISD::Lo, M, llvm::ISD::MUL, N, NewNode, llvm::TargetLowering::ArgListEntry::Node, NoteDeletion(), llvm::SDNode::op_begin(), llvm::ISD::OR, llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::pop_back(), Processed, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), ReadyToProcess, llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::remove(), llvm::SelectionDAG::RemoveDeadNodes(), llvm::SDValue::setNode(), llvm::SDNode::setNodeId(), llvm::SelectionDAG::setRoot(), llvm::ISD::SHL, llvm::SmallVectorTemplateCommon< T >::size(), llvm::ISD::SRL, llvm::SPII::Store, llvm::ISD::TRUNCATE, llvm::TargetLowering::ArgListEntry::Ty, llvm::TargetLoweringBase::TypeExpandFloat, llvm::TargetLoweringBase::TypeExpandInteger, llvm::TargetLoweringBase::TypeLegal, llvm::TargetLoweringBase::TypePromoteInteger, llvm::TargetLoweringBase::TypeScalarizeVector, llvm::TargetLoweringBase::TypeSoftenFloat, llvm::TargetLoweringBase::TypeSplitVector, llvm::TargetLoweringBase::TypeWidenVector, Unanalyzed, llvm::SelectionDAG::UpdateNodeOperands(), llvm::SDNode::use_begin(), llvm::SDValue::use_empty(), llvm::SDNode::use_end(), and llvm::ISD::ZERO_EXTEND.
The documentation for this class was generated from the following files:
LegalizeTypes.h
LegalizeFloatTypes.cpp
LegalizeIntegerTypes.cpp
LegalizeTypes.cpp
LegalizeTypesGeneric.cpp
LegalizeVectorTypes.cpp