LLVM: llvm::HexagonInstPrinter Class Reference
LLVM API Documentation
llvm::HexagonInstPrinter Class Reference
#include <HexagonInstPrinter.h>
Public Member Functions
HexagonInstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
virtual void printInst (const MCInst *MI, raw_ostream &O, StringRef Annot)
void printInst (const HexagonMCInst *MI, raw_ostream &O, StringRef Annot)
virtual StringRef getOpcodeName (unsigned Opcode) const
void printInstruction (const MCInst *MI, raw_ostream &O)
StringRef getRegName (unsigned RegNo) const
void printOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O) const
void printImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O) const
void printExtOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O) const
void printUnsignedImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O) const
void printNegImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O) const
void printNOneImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O) const
void printMEMriOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O) const
void printFrameIndexOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O) const
void printBranchOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O) const
void printCallOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O) const
void printAbsAddrOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O) const
void printPredicateOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O) const
void printGlobalOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O) const
void printJumpTable (const MCInst *MI, unsigned OpNo, raw_ostream &O) const
void printConstantPool (const MCInst *MI, unsigned OpNo, raw_ostream &O) const
void printSymbolHi (const MCInst *MI, unsigned OpNo, raw_ostream &O) const
void printSymbolLo (const MCInst *MI, unsigned OpNo, raw_ostream &O) const
const MCInstrInfo & getMII () const
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
void setCommentStream (raw_ostream &OS)
setCommentStream - Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
virtual void printRegName (raw_ostream &OS, unsigned RegNo) const
printRegName - Print the assembler register name.
uint64_t getAvailableFeatures () const
void setAvailableFeatures (uint64_t Value)
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
StringRef markup (StringRef a, StringRef b) const
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
HexStyle::Style getPrintHexStyleHex () const
void setPrintImmHex (HexStyle::Style Value)
format_object1< int64_t > formatImm (const int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object1< int64_t > formatDec (const int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object1< int64_t > formatHex (const int64_t Value) const
format_object1< uint64_t > formatHex (const uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
Protected Member Functions
void printSymbol (const MCInst *MI, unsigned OpNo, raw_ostream &O, bool hi) const
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
Static Protected Attributes
static const char PacketPadding = '\t'
Additional Inherited Members
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
uint64_t AvailableFeatures
The current set of available features.
bool UseMarkup
True if we are printing marked up assembly.
bool PrintImmHex
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle
Which style to use for printing hexadecimal values.
Detailed Description
Definition at line 23 of file HexagonInstPrinter.h.
Constructor & Destructor Documentation
llvm::HexagonInstPrinter::HexagonInstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) inline explicit
Definition at line 25 of file HexagonInstPrinter.h.
References getOpcodeName(), getRegisterName(), getRegName(), llvm::A64CC::MI, printAbsAddrOperand(), printBranchOperand(), printCallOperand(), printConstantPool(), printExtOperand(), printFrameIndexOperand(), printGlobalOperand(), printImmOperand(), printInst(), printInstruction(), printJumpTable(), printMEMriOperand(), printNegImmOperand(), printNOneImmOperand(), printOperand(), printPredicateOperand(), and printUnsignedImmOperand().
Member Function Documentation
const MCInstrInfo& llvm::HexagonInstPrinter::getMII () const inline
Definition at line 70 of file HexagonInstPrinter.h.
References printSymbol().
StringRef HexagonInstPrinter::getOpcodeName (unsigned Opcode) const virtual
Definition at line 32 of file HexagonInstPrinter.cpp.
References llvm::MCInstrInfo::getName().
Referenced by HexagonInstPrinter().
static const char* llvm::HexagonInstPrinter::getRegisterName (unsigned RegNo) static
Referenced by getRegName(), HexagonInstPrinter(), llvm::HexagonAsmPrinter::printAddrModeBasePlusOffset(), printFrameIndexOperand(), printMEMriOperand(), printOperand(), and llvm::HexagonAsmPrinter::printOperand().
StringRef HexagonInstPrinter::getRegName (unsigned RegNo) const
Definition at line 36 of file HexagonInstPrinter.cpp.
References getRegisterName().
Referenced by HexagonInstPrinter().
void HexagonInstPrinter::printAbsAddrOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O) const
Definition at line 188 of file HexagonInstPrinter.cpp.
Referenced by HexagonInstPrinter().
void HexagonInstPrinter::printBranchOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O) const
Definition at line 177 of file HexagonInstPrinter.cpp.
References llvm_unreachable.
Referenced by HexagonInstPrinter().
void HexagonInstPrinter::printCallOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O) const
Definition at line 184 of file HexagonInstPrinter.cpp.
Referenced by HexagonInstPrinter().
void HexagonInstPrinter::printConstantPool (const MCInst * MI, unsigned OpNo, raw_ostream & O) const
Definition at line 170 of file HexagonInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::isExpr(), and printOperand().
Referenced by HexagonInstPrinter().
void HexagonInstPrinter::printExtOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O) const
Definition at line 116 of file HexagonInstPrinter.cpp.
References llvm::HexagonMCInst::isConstExtended(), llvm::A64CC::MI, and printOperand().
Referenced by HexagonInstPrinter().
void HexagonInstPrinter::printFrameIndexOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O) const
Definition at line 148 of file HexagonInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), and getRegisterName().
Referenced by HexagonInstPrinter().
void HexagonInstPrinter::printGlobalOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O) const
Definition at line 156 of file HexagonInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::isExpr(), and printOperand().
Referenced by HexagonInstPrinter().
void HexagonInstPrinter::printImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O) const
Definition at line 103 of file HexagonInstPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), and llvm_unreachable.
Referenced by HexagonInstPrinter(), and printOperand().
void HexagonInstPrinter::printInst (const MCInst * MI, raw_ostream & OS, StringRef Annot) virtual
printInst - Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 40 of file HexagonInstPrinter.cpp.
Referenced by HexagonInstPrinter(), and printInst().
void HexagonInstPrinter::printInst (const HexagonMCInst * MI, raw_ostream & O, StringRef Annot)
Definition at line 45 of file HexagonInstPrinter.cpp.
References llvm::MCInst::getOpcode(), llvm::HexagonMCInst::isPacketEnd(), llvm::HexagonMCInst::isPacketStart(), PacketPadding, llvm::MCInstPrinter::printAnnotation(), printInst(), printInstruction(), llvm::MCInst::setOpcode(), and llvm::HexagonMCInst::setPacketStart().
void llvm::HexagonInstPrinter::printInstruction (const MCInst * MI, raw_ostream & O)
Referenced by HexagonInstPrinter(), and printInst().
void HexagonInstPrinter::printJumpTable (const MCInst * MI, unsigned OpNo, raw_ostream & O) const
Definition at line 163 of file HexagonInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::isExpr(), and printOperand().
Referenced by HexagonInstPrinter().
void HexagonInstPrinter::printMEMriOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O) const
Definition at line 139 of file HexagonInstPrinter.cpp.
References llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), and getRegisterName().
Referenced by HexagonInstPrinter().
void HexagonInstPrinter::printNegImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O) const
Definition at line 129 of file HexagonInstPrinter.cpp.
References llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
Referenced by HexagonInstPrinter().
void HexagonInstPrinter::printNOneImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O) const
Definition at line 134 of file HexagonInstPrinter.cpp.
Referenced by HexagonInstPrinter().
void HexagonInstPrinter::printOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O) const
Definition at line 88 of file HexagonInstPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm_unreachable, and printImmOperand().
Referenced by HexagonInstPrinter(), printConstantPool(), printExtOperand(), printGlobalOperand(), printJumpTable(), and printSymbol().
void HexagonInstPrinter::printPredicateOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O) const
Definition at line 192 of file HexagonInstPrinter.cpp.
Referenced by HexagonInstPrinter().
void HexagonInstPrinter::printSymbol (const MCInst * MI, unsigned OpNo, raw_ostream & O, bool hi) const protected
Definition at line 196 of file HexagonInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::isImm(), and printOperand().
Referenced by getMII(), printSymbolHi(), and printSymbolLo().
void llvm::HexagonInstPrinter::printSymbolHi (const MCInst * MI, unsigned OpNo, raw_ostream & O) const inline
Definition at line 65 of file HexagonInstPrinter.h.
References printSymbol().
void llvm::HexagonInstPrinter::printSymbolLo (const MCInst * MI, unsigned OpNo, raw_ostream & O) const inline
Definition at line 67 of file HexagonInstPrinter.h.
References printSymbol().
void HexagonInstPrinter::printUnsignedImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O) const
Definition at line 124 of file HexagonInstPrinter.cpp.
References llvm::MCOperand::getImm(), and llvm::MCInst::getOperand().
Referenced by HexagonInstPrinter().
Member Data Documentation
const char HexagonInstPrinter::PacketPadding = '\t' static protected
Definition at line 78 of file HexagonInstPrinter.h.
Referenced by printInst().
The documentation for this class was generated from the following files:
HexagonInstPrinter.h
HexagonInstPrinter.cpp