LLVM: llvm::DIContext Class Reference
LLVM API Documentation
llvm::DIContext Class Reference abstract
#include <DIContext.h>
Public Types
enum DIContextKind { CK_DWARF }
Public Member Functions
DIContextKind getKind () const
DIContext (DIContextKind K)
virtual ~DIContext ()
virtual void dump (raw_ostream &OS, DIDumpType DumpType=DIDT_All)=0
virtual DILineInfo getLineInfoForAddress (uint64_t Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier())=0
virtual DILineInfoTable getLineInfoForAddressRange (uint64_t Address, uint64_t Size, DILineInfoSpecifier Specifier=DILineInfoSpecifier())=0
virtual DIInliningInfo getInliningInfoForAddress (uint64_t Address, DILineInfoSpecifier Specifier=DILineInfoSpecifier())=0
Static Public Member Functions
static DIContext * getDWARFContext (object::ObjectFile *)
getDWARFContext - get a context for binary DWARF data.
Detailed Description
Definition at line 127 of file DIContext.h.
Member Enumeration Documentation
enum llvm::DIContext::DIContextKind
Enumerator
CK_DWARF
Definition at line 129 of file DIContext.h.
Constructor & Destructor Documentation
llvm::DIContext::DIContext (DIContextKind K) inline
Definition at line 134 of file DIContext.h.
References llvm::DIDT_All, and llvm::dump().
DIContext::~DIContext () virtual
Definition at line 14 of file DIContext.cpp.
Member Function Documentation
virtual void llvm::DIContext::dump (raw_ostream & OS, DIDumpType DumpType = DIDT_All) pure virtual
Implemented in llvm::DWARFContext.
DIContext * DIContext::getDWARFContext (object::ObjectFile * Obj) static
getDWARFContext - get a context for binary DWARF data.
Definition at line 16 of file DIContext.cpp.
Referenced by llvm::DWARFUnit::getDWOId().
virtual DIInliningInfo llvm::DIContext::getInliningInfoForAddress (uint64_t Address, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) pure virtual
Implemented in llvm::DWARFContext.
DIContextKind llvm::DIContext::getKind () const inline
Definition at line 132 of file DIContext.h.
Referenced by llvm::DWARFContext::classof().
virtual DILineInfo llvm::DIContext::getLineInfoForAddress (uint64_t Address, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) pure virtual
Implemented in llvm::DWARFContext.
virtual DILineInfoTable llvm::DIContext::getLineInfoForAddressRange (uint64_t Address, uint64_t Size, DILineInfoSpecifier Specifier = DILineInfoSpecifier()) pure virtual
Implemented in llvm::DWARFContext.
The documentation for this class was generated from the following files:
DIContext.h
DIContext.cpp