LLVM: llvm::ARMBaseInstrInfo Class Reference
LLVM API Documentation
llvm::ARMBaseInstrInfo Class Reference abstract
#include <ARMBaseInstrInfo.h>
Public Member Functions
bool hasNOP () const
virtual unsigned getUnindexedOpcode (unsigned Opc) const =0
virtual MachineInstr * convertToThreeAddress (MachineFunction::iterator &MFI, MachineBasicBlock::iterator &MBBI, LiveVariables *LV) const
virtual const ARMBaseRegisterInfo & getRegisterInfo () const =0
const ARMSubtarget & getSubtarget () const
ScheduleHazardRecognizer * CreateTargetHazardRecognizer (const TargetMachine *TM, const ScheduleDAG *DAG) const
ScheduleHazardRecognizer * CreateTargetPostRAHazardRecognizer (const InstrItineraryData *II, const ScheduleDAG *DAG) const
virtual bool AnalyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify=false) const
virtual unsigned RemoveBranch (MachineBasicBlock &MBB) const
virtual unsigned InsertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, const SmallVectorImpl< MachineOperand > &Cond, DebugLoc DL) const
virtual bool ReverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const
bool isPredicated (const MachineInstr *MI) const
ARMCC::CondCodes getPredicate (const MachineInstr *MI) const
virtual bool PredicateInstruction (MachineInstr *MI, const SmallVectorImpl< MachineOperand > &Pred) const
virtual bool SubsumesPredicate (const SmallVectorImpl< MachineOperand > &Pred1, const SmallVectorImpl< MachineOperand > &Pred2) const
virtual bool DefinesPredicate (MachineInstr *MI, std::vector< MachineOperand > &Pred) const
virtual bool isPredicable (MachineInstr *MI) const
virtual unsigned GetInstSizeInBytes (const MachineInstr *MI) const
virtual unsigned isLoadFromStackSlot (const MachineInstr *MI, int &FrameIndex) const
virtual unsigned isStoreToStackSlot (const MachineInstr *MI, int &FrameIndex) const
virtual unsigned isLoadFromStackSlotPostFE (const MachineInstr *MI, int &FrameIndex) const
virtual unsigned isStoreToStackSlotPostFE (const MachineInstr *MI, int &FrameIndex) const
virtual void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const
virtual void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const
virtual void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const
virtual bool expandPostRAPseudo (MachineBasicBlock::iterator MI) const
virtual void reMaterialize (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned DestReg, unsigned SubIdx, const MachineInstr *Orig, const TargetRegisterInfo &TRI) const
MachineInstr * duplicate (MachineInstr *Orig, MachineFunction &MF) const
MachineInstr * commuteInstruction (MachineInstr *, bool=false) const
commuteInstruction - Handle commutable instructions.
const MachineInstrBuilder & AddDReg (MachineInstrBuilder &MIB, unsigned Reg, unsigned SubIdx, unsigned State, const TargetRegisterInfo *TRI) const
virtual bool produceSameValue (const MachineInstr *MI0, const MachineInstr *MI1, const MachineRegisterInfo *MRI) const
virtual bool areLoadsFromSameBasePtr (SDNode *Load1, SDNode *Load2, int64_t &Offset1, int64_t &Offset2) const
virtual bool shouldScheduleLoadsNear (SDNode *Load1, SDNode *Load2, int64_t Offset1, int64_t Offset2, unsigned NumLoads) const
virtual bool isSchedulingBoundary (const MachineInstr *MI, const MachineBasicBlock *MBB, const MachineFunction &MF) const
virtual bool isProfitableToIfCvt (MachineBasicBlock &MBB, unsigned NumCycles, unsigned ExtraPredCycles, const BranchProbability &Probability) const
virtual bool isProfitableToIfCvt (MachineBasicBlock &TMBB, unsigned NumT, unsigned ExtraT, MachineBasicBlock &FMBB, unsigned NumF, unsigned ExtraF, const BranchProbability &Probability) const
virtual bool isProfitableToDupForIfCvt (MachineBasicBlock &MBB, unsigned NumCycles, const BranchProbability &Probability) const
virtual bool isProfitableToUnpredicate (MachineBasicBlock &TMBB, MachineBasicBlock &FMBB) const
virtual bool analyzeCompare (const MachineInstr *MI, unsigned &SrcReg, unsigned &SrcReg2, int &CmpMask, int &CmpValue) const
virtual bool optimizeCompareInstr (MachineInstr *CmpInstr, unsigned SrcReg, unsigned SrcReg2, int CmpMask, int CmpValue, const MachineRegisterInfo *MRI) const
virtual bool analyzeSelect (const MachineInstr *MI, SmallVectorImpl< MachineOperand > &Cond, unsigned &TrueOp, unsigned &FalseOp, bool &Optimizable) const
virtual MachineInstr * optimizeSelect (MachineInstr *MI, bool) const
virtual bool FoldImmediate (MachineInstr *UseMI, MachineInstr *DefMI, unsigned Reg, MachineRegisterInfo *MRI) const
virtual unsigned getNumMicroOps (const InstrItineraryData *ItinData, const MachineInstr *MI) const
virtual int getOperandLatency (const InstrItineraryData *ItinData, const MachineInstr *DefMI, unsigned DefIdx, const MachineInstr *UseMI, unsigned UseIdx) const
virtual int getOperandLatency (const InstrItineraryData *ItinData, SDNode *DefNode, unsigned DefIdx, SDNode *UseNode, unsigned UseIdx) const
std::pair< uint16_t, uint16_t > getExecutionDomain (const MachineInstr *MI) const
VFP/NEON execution domains.
void setExecutionDomain (MachineInstr *MI, unsigned Domain) const
unsigned getPartialRegUpdateClearance (const MachineInstr *, unsigned, const TargetRegisterInfo *) const
void breakPartialRegDependency (MachineBasicBlock::iterator, unsigned, const TargetRegisterInfo *TRI) const
unsigned getNumLDMAddresses (const MachineInstr *MI) const
Get the number of addresses by LDM or VLDM or zero for unknown.
bool isFpMLxInstruction (unsigned Opcode) const
bool isFpMLxInstruction (unsigned Opcode, unsigned &MulOpc, unsigned &AddSubOpc, bool &NegAcc, bool &HasLane) const
bool canCauseFpMLxStall (unsigned Opcode) const
bool isSwiftFastImmShift (const MachineInstr *MI) const
Protected Member Functions
ARMBaseInstrInfo (const ARMSubtarget &STI)
Detailed Description
Definition at line 30 of file ARMBaseInstrInfo.h.
Constructor & Destructor Documentation
ARMBaseInstrInfo::ARMBaseInstrInfo (const ARMSubtarget & STI) explicit protected
Definition at line 90 of file ARMBaseInstrInfo.cpp.
References llvm::array_lengthof(), CreateTargetHazardRecognizer(), i, llvm::SmallSet< T, N, C >::insert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::insert(), and ARM_MLxEntry::MLxOpc.
Member Function Documentation
const MachineInstrBuilder & ARMBaseInstrInfo::AddDReg (MachineInstrBuilder & MIB, unsigned Reg, unsigned SubIdx, unsigned State, const TargetRegisterInfo * TRI) const
Definition at line 772 of file ARMBaseInstrInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::MCRegisterInfo::getSubReg(), llvm::TargetRegisterInfo::isPhysicalRegister(), and storeRegToStackSlot().
Referenced by getPredicate(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), loadRegFromStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), and storeRegToStackSlot().
bool ARMBaseInstrInfo::AnalyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify = false) const virtual
Definition at line 272 of file ARMBaseInstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::SmallVectorBase::empty(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), I, llvm::isCondBranchOpcode(), llvm::isIndirectBranchOpcode(), llvm::isJumpTableBranchOpcode(), isPredicated(), llvm::isUncondBranchOpcode(), llvm::next(), and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by getSubtarget().
bool ARMBaseInstrInfo::analyzeCompare (const MachineInstr * MI, unsigned & SrcReg, unsigned & SrcReg2, int & CmpMask, int & CmpValue) const virtual
analyzeCompare - For a comparison instruction, return the source registers in SrcReg and SrcReg2 if having two register operands, and the value it compares against in CmpValue. Return true if the comparison instruction can be analyzed.
Definition at line 2114 of file ARMBaseInstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), and llvm::MachineOperand::getReg().
Referenced by isProfitableToDupForIfCvt(), and llvm::rewriteARMFrameIndex().
bool ARMBaseInstrInfo::analyzeSelect (const MachineInstr * MI, SmallVectorImpl< MachineOperand > & Cond, unsigned & TrueOp, unsigned & FalseOp, bool & Optimizable) const virtual
Definition at line 1704 of file ARMBaseInstrInfo.cpp.
References llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by isProfitableToDupForIfCvt().
bool ARMBaseInstrInfo::areLoadsFromSameBasePtr (SDNode * Load1, SDNode * Load2, int64_t & Offset1, int64_t & Offset2) const virtual
areLoadsFromSameBasePtr - This is used by the pre-regalloc scheduler to determine if two loads are loading from the same base address. It should only return true if the base pointers are the same and the only differences between the two addresses is the offset. It also returns the offsets by reference.
areLoadsFromSameBasePtr - This is used by the pre-regalloc scheduler to determine if two loads are loading from the same base address. It should only return true if the base pointers are the same and the only differences between the two addresses is the offset. It also returns the offsets by reference.
FIXME: remove this in favor of the MachineInstr interface once pre-RA-sched is permanently disabled.
Definition at line 1413 of file ARMBaseInstrInfo.cpp.
References llvm::SDNode::getMachineOpcode(), llvm::SDNode::getOperand(), llvm::SDNode::isMachineOpcode(), and llvm::ARMSubtarget::isThumb1Only().
Referenced by getPredicate().
void ARMBaseInstrInfo::breakPartialRegDependency (MachineBasicBlock::iterator MI, unsigned OpNum, const TargetRegisterInfo * TRI) const
Definition at line 4300 of file ARMBaseInstrInfo.cpp.
References llvm::AddDefaultPred(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstr::addRegisterKilled(), llvm::BuildMI(), llvm::MachineOperand::getReg(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::MCRegisterInfo::isSuperRegister(), and llvm::A64CC::MI.
Referenced by getPartialRegUpdateClearance(), and isProfitableToDupForIfCvt().
bool llvm::ARMBaseInstrInfo::canCauseFpMLxStall (unsigned Opcode) const inline
canCauseFpMLxStall - Return true if an instruction of the specified opcode will cause stalls when scheduled after (within 4-cycle window) a fp MLA / MLS instruction.
Definition at line 314 of file ARMBaseInstrInfo.h.
References llvm::SmallSet< T, N, C >::count(), and isSwiftFastImmShift().
Referenced by llvm::ARMHazardRecognizer::getHazardType().
MachineInstr * ARMBaseInstrInfo::commuteInstruction (MachineInstr * MI, bool NewMI = false) const
commuteInstruction - Handle commutable instructions.
Definition at line 1644 of file ARMBaseInstrInfo.cpp.
References llvm::ARMCC::AL, CC, llvm::TargetInstrInfo::commuteInstruction(), llvm::MachineInstr::findFirstPredOperandIdx(), llvm::getInstrPredicate(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::ARMCC::getOppositeCondition(), and llvm::A64CC::MI.
Referenced by getPredicate().
MachineInstr * ARMBaseInstrInfo::convertToThreeAddress (MachineFunction::iterator & MFI, MachineBasicBlock::iterator & MBBI, LiveVariables * LV) const virtual
Definition at line 122 of file ARMBaseInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::ARMII::AddrMode2, llvm::ARMII::AddrMode3, llvm::ARMII::AddrModeMask, llvm::LiveVariables::addVirtualRegisterDead(), llvm::LiveVariables::addVirtualRegisterKilled(), llvm::BuildMI(), EnableARM3Addr, llvm::ARM_AM::getAM2Offset(), llvm::ARM_AM::getAM2Op(), llvm::ARM_AM::getAM2ShiftOpc(), llvm::ARM_AM::getAM3Offset(), llvm::ARM_AM::getAM3Op(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::ARM_AM::getSOImmVal(), llvm::ARM_AM::getSORegOpc(), getUnindexedOpcode(), llvm::LiveVariables::getVarInfo(), i, llvm::ARMII::IndexModeMask, llvm::ARMII::IndexModePost, llvm::ARMII::IndexModePre, llvm::ARMII::IndexModeShift, llvm::MachineOperand::isDead(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isKill(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUse(), llvm::TargetRegisterInfo::isVirtualRegister(), j(), llvm::LiveVariables::VarInfo::Kills, llvm_unreachable, llvm::MachineInstr::mayStore(), llvm::A64CC::MI, llvm::MachineInstr::readsRegister(), llvm::LiveVariables::VarInfo::removeKill(), llvm::MachineOperand::setIsDead(), llvm::ARM_AM::sub, and llvm::MCInstrDesc::TSFlags.
void ARMBaseInstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const virtual
Reimplemented in llvm::Thumb2InstrInfo, and llvm::Thumb1InstrInfo.
Definition at line 650 of file ARMBaseInstrInfo.cpp.
References llvm::AddDefaultCC(), llvm::AddDefaultPred(), llvm::MachineInstrBuilder::addReg(), llvm::MachineInstr::addRegisterDefined(), llvm::MachineInstr::addRegisterKilled(), llvm::BuildMI(), llvm::SmallSet< T, N, C >::count(), llvm::getKillRegState(), getRegisterInfo(), llvm::MCRegisterInfo::getSubReg(), i, llvm::SmallSet< T, N, C >::insert(), llvm::ARMSubtarget::isThumb2(), and llvm::TargetRegisterInfo::regsOverlap().
Referenced by llvm::Thumb2InstrInfo::copyPhysReg(), and getPredicate().
ScheduleHazardRecognizer * ARMBaseInstrInfo::CreateTargetHazardRecognizer (const TargetMachine * TM, const ScheduleDAG * DAG) const
Definition at line 104 of file ARMBaseInstrInfo.cpp.
References llvm::TargetInstrInfo::CreateTargetHazardRecognizer(), CreateTargetPostRAHazardRecognizer(), and llvm::TargetMachine::getInstrItineraryData().
Referenced by ARMBaseInstrInfo(), and getSubtarget().
ScheduleHazardRecognizer * ARMBaseInstrInfo::CreateTargetPostRAHazardRecognizer (const InstrItineraryData * II, const ScheduleDAG * DAG) const
Definition at line 114 of file ARMBaseInstrInfo.cpp.
References llvm::TargetInstrInfo::CreateTargetPostRAHazardRecognizer(), llvm::ARMSubtarget::hasVFP2(), and llvm::ARMSubtarget::isThumb2().
Referenced by CreateTargetHazardRecognizer(), and getSubtarget().
bool ARMBaseInstrInfo::DefinesPredicate (MachineInstr * MI, std::vector< MachineOperand > & Pred) const virtual
Definition at line 502 of file ARMBaseInstrInfo.cpp.
References llvm::MachineOperand::clobbersPhysReg(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), i, llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), and llvm::MachineOperand::isRegMask().
Referenced by getPredicate().
MachineInstr * ARMBaseInstrInfo::duplicate (MachineInstr * Orig, MachineFunction & MF) const
Definition at line 1305 of file ARMBaseInstrInfo.cpp.
References llvm::TargetInstrInfo::duplicate(), duplicateCPV(), llvm::MachineOperand::getIndex(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::A64CC::MI, llvm::MachineOperand::setImm(), and llvm::MachineOperand::setIndex().
Referenced by getPredicate().
bool ARMBaseInstrInfo::expandPostRAPseudo (MachineBasicBlock::iterator MI) const virtual
Definition at line 1165 of file ARMBaseInstrInfo.cpp.
References llvm::AddDefaultPred(), llvm::dbgs(), DEBUG, llvm::MachineInstr::findRegisterDefOperandIdx(), llvm::TargetRegisterInfo::getMatchingSuperReg(), getRegisterInfo(), llvm::RegState::Implicit, llvm::ARMSubtarget::isCortexA15(), llvm::A64CC::MI, and WidenVMOVS.
Referenced by getPredicate().
bool ARMBaseInstrInfo::FoldImmediate (MachineInstr * UseMI, MachineInstr * DefMI, unsigned Reg, MachineRegisterInfo * MRI) const virtual
FoldImmediate - 'Reg' is known to be defined by a move immediate instruction, try to fold the immediate into the use instruction.
Definition at line 2462 of file ARMBaseInstrInfo.cpp.
References llvm::AddDefaultCC(), llvm::AddDefaultPred(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::getKillRegState(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::ARM_AM::getSOImmTwoPartFirst(), llvm::ARM_AM::getSOImmTwoPartSecond(), llvm::ARM_AM::getT2SOImmTwoPartFirst(), llvm::ARM_AM::getT2SOImmTwoPartSecond(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), llvm::MCInstrDesc::hasOptionalDef(), llvm::MachineOperand::isDead(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isKill(), llvm::ARM_AM::isSOImmTwoPartVal(), llvm::ARM_AM::isT2SOImmTwoPartVal(), llvm::MachineInstr::setDesc(), llvm::MachineOperand::setIsKill(), and llvm::MachineOperand::setReg().
Referenced by isProfitableToDupForIfCvt().
std::pair< uint16_t, uint16_t > ARMBaseInstrInfo::getExecutionDomain (const MachineInstr * MI) const
VFP/NEON execution domains.
Definition at line 3942 of file ARMBaseInstrInfo.cpp.
References llvm::ARMII::DomainMask, llvm::ARMII::DomainNEON, llvm::ARMII::DomainNEONA8, llvm::ARMII::DomainVFP, ExeGeneric, ExeNEON, ExeVFP, llvm::MachineInstr::getDesc(), llvm::MachineInstr::getOpcode(), isPredicated(), and llvm::MCInstrDesc::TSFlags.
Referenced by isProfitableToDupForIfCvt().
unsigned ARMBaseInstrInfo::GetInstSizeInBytes (const MachineInstr * MI) const virtual
GetInstSize - Returns the size of the specified MachineInstr.
GetInstSize - Return the size of the specified MachineInstr.
Definition at line 550 of file ARMBaseInstrInfo.cpp.
References llvm::TargetOpcode::BUNDLE, llvm::TargetOpcode::DBG_VALUE, llvm::TargetOpcode::EH_LABEL, llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineFunction::getJumpTableInfo(), llvm::MachineJumpTableInfo::getJumpTables(), llvm::TargetMachine::getMCAsmInfo(), getNumJTEntries(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MCInstrDesc::getSize(), llvm::MachineOperand::getSymbolName(), llvm::MachineFunction::getTarget(), I, llvm::TargetOpcode::IMPLICIT_DEF, llvm::ISD::INLINEASM, llvm::MachineBasicBlock::instr_end(), llvm::MachineInstr::isLabel(), llvm::MachineInstr::isPredicable(), llvm::TargetOpcode::KILL, llvm::A64CC::MI, and llvm::TargetOpcode::PROLOG_LABEL.
Referenced by GetFunctionSizeInBytes(), and getPredicate().
unsigned ARMBaseInstrInfo::getNumLDMAddresses (const MachineInstr * MI) const
Get the number of addresses by LDM or VLDM or zero for unknown.
Definition at line 2823 of file ARMBaseInstrInfo.cpp.
References I, llvm::MachineInstr::memoperands_begin(), and llvm::MachineInstr::memoperands_end().
Referenced by isProfitableToDupForIfCvt().
unsigned ARMBaseInstrInfo::getNumMicroOps (const InstrItineraryData * ItinData, const MachineInstr * MI) const virtual
Definition at line 2833 of file ARMBaseInstrInfo.cpp.
References llvm::tgtok::Class, llvm::MachineInstr::getDesc(), llvm::MCInstrDesc::getNumDefs(), llvm::InstrItineraryData::getNumMicroOps(), getNumMicroOpsSwiftLdSt(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getNumOperands(), llvm::MCInstrDesc::getOpcode(), llvm::MachineInstr::getOpcode(), llvm::InstrItineraryData::getOperandCycle(), llvm::InstrItineraryData::getOperandLatency(), getOperandLatency(), llvm::MCInstrDesc::getSchedClass(), llvm::MachineInstr::hasOneMemOperand(), llvm::InstrItineraryData::hasPipelineForwarding(), int, llvm::InstrItineraryData::isEmpty(), llvm_unreachable, llvm::MCInstrDesc::mayLoad(), llvm::MCInstrDesc::mayStore(), and llvm::MachineInstr::memoperands_begin().
Referenced by getOperandLatency(), and isProfitableToDupForIfCvt().
int ARMBaseInstrInfo::getOperandLatency (const InstrItineraryData * ItinData, const MachineInstr * DefMI, unsigned DefIdx, const MachineInstr * UseMI, unsigned UseIdx) const virtual
Definition at line 3470 of file ARMBaseInstrInfo.cpp.
References adjustDefLatency(), llvm::ARMISD::FMSTAT, llvm::Function::getAttributes(), getBundledDefMI(), getBundledUseMI(), llvm::MachineInstr::getDesc(), llvm::MachineFunction::getFunction(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), getRegisterInfo(), llvm::MachineInstr::hasOneMemOperand(), llvm::MachineInstr::isBranch(), llvm::MachineInstr::isBundle(), llvm::MachineInstr::isCopyLike(), llvm::InstrItineraryData::isEmpty(), llvm::MachineOperand::isImplicit(), llvm::MachineInstr::isImplicitDef(), llvm::MachineInstr::isInsertSubreg(), llvm::MachineInstr::isRegSequence(), llvm::MachineInstr::memoperands_begin(), and llvm::Attribute::OptimizeForSize.
Referenced by getNumMicroOps(), getOperandLatency(), and isProfitableToDupForIfCvt().
int ARMBaseInstrInfo::getOperandLatency (const InstrItineraryData * ItinData, SDNode * DefNode, unsigned DefIdx, SDNode * UseNode, unsigned UseIdx) const virtual
Definition at line 3561 of file ARMBaseInstrInfo.cpp.
References adjustDefLatency(), llvm::tgtok::Class, llvm::convertAddSubFlagsOpcode(), llvm::ARMII::DomainGeneral, llvm::ARMII::DomainMask, llvm::ARMII::DomainNEON, llvm::ARMII::DomainVFP, llvm::dyn_cast(), llvm::ARM_AM::getAM2Offset(), llvm::ARM_AM::getAM2ShiftOpc(), llvm::MachineInstr::getDesc(), llvm::SDNode::getMachineOpcode(), getNumMicroOps(), llvm::InstrItineraryData::getNumMicroOps(), llvm::MCInstrDesc::getOpcode(), llvm::MachineInstr::getOpcode(), llvm::SDNode::getOperand(), llvm::InstrItineraryData::getOperandCycle(), getOperandLatency(), llvm::MachineInstr::getParent(), llvm::MCInstrDesc::getSchedClass(), llvm::InstrItineraryData::getStageLatency(), llvm::MCInstrDesc::hasImplicitDefOfPhysReg(), llvm::MachineInstr::hasOneMemOperand(), I, llvm::MachineBasicBlock::instr_end(), llvm::MachineInstr::isBundle(), llvm::MCInstrDesc::isCall(), llvm::MachineInstr::isCopyLike(), llvm::InstrItineraryData::isEmpty(), llvm::MachineInstr::isImplicitDef(), llvm::MachineInstr::isInsertSubreg(), llvm::SDNode::isMachineOpcode(), llvm::MachineInstr::isRegSequence(), llvm::ARM_AM::lsl, llvm::ARM_AM::lsr, llvm::MCInstrDesc::mayLoad(), llvm::MachineInstr::mayLoad(), llvm::MachineInstr::memoperands_begin(), llvm::MachineSDNode::memoperands_begin(), llvm::MachineSDNode::memoperands_empty(), llvm::A64CC::MI, MRI, llvm::MCInstrDesc::Opcode, and llvm::MCInstrDesc::TSFlags.
unsigned ARMBaseInstrInfo::getPartialRegUpdateClearance (const MachineInstr * MI, unsigned OpNum, const TargetRegisterInfo * TRI) const
Definition at line 4238 of file ARMBaseInstrInfo.cpp.
References breakPartialRegDependency(), llvm::MachineInstr::definesRegister(), llvm::MachineInstr::findRegisterUseOperandIdx(), llvm::TargetRegisterInfo::getMatchingSuperReg(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::MachineOperand::readsReg(), llvm::MachineInstr::readsVirtualRegister(), and SwiftPartialUpdateClearance.
Referenced by isProfitableToDupForIfCvt(), and setExecutionDomain().
ARMCC::CondCodes llvm::ARMBaseInstrInfo::getPredicate (const MachineInstr * MI) const inline
Definition at line 77 of file ARMBaseInstrInfo.h.
References AddDReg(), llvm::ARMCC::AL, areLoadsFromSameBasePtr(), commuteInstruction(), copyPhysReg(), DefinesPredicate(), duplicate(), expandPostRAPseudo(), llvm::MachineInstr::findFirstPredOperandIdx(), llvm::ISD::FrameIndex, llvm::MachineOperand::getImm(), GetInstSizeInBytes(), llvm::MachineInstr::getOperand(), I, isLoadFromStackSlot(), isLoadFromStackSlotPostFE(), isPredicable(), isProfitableToIfCvt(), isSchedulingBoundary(), isStoreToStackSlot(), isStoreToStackSlotPostFE(), loadRegFromStackSlot(), MRI, PredicateInstruction(), produceSameValue(), reMaterialize(), shouldScheduleLoadsNear(), storeRegToStackSlot(), and SubsumesPredicate().
Referenced by convertNEONDataProcToThumb(), llvm::createARMJITCodeEmitterPass(), and getAddrModeUPBits().
virtual const ARMBaseRegisterInfo& llvm::ARMBaseInstrInfo::getRegisterInfo () const pure virtual
Implemented in llvm::Thumb2InstrInfo, llvm::ARMInstrInfo, and llvm::Thumb1InstrInfo.
Referenced by convertNEONDataProcToThumb(), copyPhysReg(), llvm::createARMJITCodeEmitterPass(), expandPostRAPseudo(), getAddrModeUPBits(), GetDSubRegs(), llvm::ARMHazardRecognizer::getHazardType(), getOperandLatency(), loadRegFromStackSlot(), optimizeCompareInstr(), setExecutionDomain(), and storeRegToStackSlot().
const ARMSubtarget& llvm::ARMBaseInstrInfo::getSubtarget () const inline
Definition at line 50 of file ARMBaseInstrInfo.h.
References AnalyzeBranch(), CreateTargetHazardRecognizer(), CreateTargetPostRAHazardRecognizer(), InsertBranch(), isPredicated(), llvm::A64CC::MI, RemoveBranch(), ReverseBranchCondition(), and llvm::SystemZISD::TM.
Referenced by llvm::ARMHazardRecognizer::getHazardType(), and isPredicable().
virtual unsigned llvm::ARMBaseInstrInfo::getUnindexedOpcode (unsigned Opc) const pure virtual
Implemented in llvm::ARMInstrInfo, llvm::Thumb2InstrInfo, and llvm::Thumb1InstrInfo.
Referenced by convertToThreeAddress().
bool ARMBaseInstrInfo::hasNOP () const
Definition at line 4334 of file ARMBaseInstrInfo.cpp.
Referenced by llvm::ARMInstrInfo::getNoopForMachoTarget().
unsigned ARMBaseInstrInfo::InsertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, const SmallVectorImpl< MachineOperand > & Cond, DebugLoc DL) const virtual
Definition at line 392 of file ARMBaseInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::ARMCC::AL, B, llvm::BuildMI(), llvm::SmallVectorBase::empty(), llvm::MachineFunction::getInfo(), llvm::MachineBasicBlock::getParent(), getReg(), llvm::ARMFunctionInfo::isThumb2Function(), llvm::ARMFunctionInfo::isThumbFunction(), ReverseBranchCondition(), and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by getSubtarget().
bool llvm::ARMBaseInstrInfo::isFpMLxInstruction (unsigned Opcode) const inline
isFpMLxInstruction - Return true if the specified opcode is a fp MLA / MLS instruction.
Definition at line 300 of file ARMBaseInstrInfo.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::count().
Referenced by llvm::ARMHazardRecognizer::getHazardType(), and isScaledConstantInRange().
bool ARMBaseInstrInfo::isFpMLxInstruction (unsigned Opcode, unsigned & MulOpc, unsigned & AddSubOpc, bool & NegAcc, bool & HasLane) const
isFpMLxInstruction - This version also returns the multiply opcode and the addition / subtraction opcode to expand to. Return true for 'HasLane' for the MLX instructions with an extra lane operand.
Definition at line 3907 of file ARMBaseInstrInfo.cpp.
References ARM_MLxEntry::AddSubOpc, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), ARM_MLxEntry::HasLane, I, ARM_MLxEntry::MulOpc, and ARM_MLxEntry::NegAcc.
unsigned ARMBaseInstrInfo::isLoadFromStackSlot (const MachineInstr * MI, int & FrameIndex) const virtual
Definition at line 1111 of file ARMBaseInstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), llvm::MachineOperand::isFI(), llvm::MachineOperand::isImm(), and llvm::MachineOperand::isReg().
Referenced by getPredicate().
unsigned ARMBaseInstrInfo::isLoadFromStackSlotPostFE (const MachineInstr * MI, int & FrameIndex) const virtual
Definition at line 1159 of file ARMBaseInstrInfo.cpp.
References llvm::NVPTXISD::Dummy, and llvm::MachineInstr::mayLoad().
Referenced by getPredicate().
bool ARMBaseInstrInfo::isPredicable (MachineInstr * MI) const virtual
isPredicable - Return true if the specified instruction can be predicated. By default, this returns true for every instruction with a PredicateOperand.
Definition at line 520 of file ARMBaseInstrInfo.cpp.
References llvm::ARMII::DomainMask, llvm::ARMII::DomainNEON, llvm::MachineInstr::getDesc(), llvm::MachineFunction::getInfo(), getNumJTEntries(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), getSubtarget(), llvm::MachineInstr::isPredicable(), llvm::ARMFunctionInfo::isThumb2Function(), llvm::isV8EligibleForIT(), LLVM_ATTRIBUTE_NOINLINE, llvm::ARMSubtarget::restrictIT(), and llvm::MCInstrDesc::TSFlags.
Referenced by getPredicate().
bool ARMBaseInstrInfo::isPredicated (const MachineInstr * MI) const
Definition at line 437 of file ARMBaseInstrInfo.cpp.
References llvm::ARMCC::AL, llvm::MachineInstr::findFirstPredOperandIdx(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), I, llvm::MachineBasicBlock::instr_end(), llvm::MachineInstr::isBundle(), llvm::A64CC::MI, and PredicateInstruction().
Referenced by AnalyzeBranch(), getExecutionDomain(), getSubtarget(), optimizeCompareInstr(), and setExecutionDomain().
virtual bool llvm::ARMBaseInstrInfo::isProfitableToDupForIfCvt (MachineBasicBlock & MBB, unsigned NumCycles, const BranchProbability & Probability) const inline virtual
Definition at line 180 of file ARMBaseInstrInfo.h.
References analyzeCompare(), analyzeSelect(), breakPartialRegDependency(), FoldImmediate(), getExecutionDomain(), getNumLDMAddresses(), getNumMicroOps(), getOperandLatency(), getPartialRegUpdateClearance(), isProfitableToUnpredicate(), optimizeCompareInstr(), optimizeSelect(), and setExecutionDomain().
bool ARMBaseInstrInfo::isProfitableToIfCvt (MachineBasicBlock & MBB, unsigned NumCycles, unsigned ExtraPredCycles, const BranchProbability & Probability) const virtual
Definition at line 1568 of file ARMBaseInstrInfo.cpp.
References llvm::BranchProbability::getDenominator(), llvm::ARMSubtarget::getMispredictionPenalty(), and llvm::BranchProbability::getNumerator().
Referenced by getPredicate(), and isSchedulingBoundary().
bool ARMBaseInstrInfo::isProfitableToIfCvt (MachineBasicBlock & TMBB, unsigned NumT, unsigned ExtraT, MachineBasicBlock & FMBB, unsigned NumF, unsigned ExtraF, const BranchProbability & Probability) const virtual
Definition at line 1584 of file ARMBaseInstrInfo.cpp.
References llvm::BranchProbability::getDenominator(), llvm::ARMSubtarget::getMispredictionPenalty(), and llvm::BranchProbability::getNumerator().
bool ARMBaseInstrInfo::isProfitableToUnpredicate (MachineBasicBlock & TMBB, MachineBasicBlock & FMBB) const virtual
Definition at line 1608 of file ARMBaseInstrInfo.cpp.
References llvm::ARMSubtarget::isSwift().
Referenced by isProfitableToDupForIfCvt().
bool ARMBaseInstrInfo::isSchedulingBoundary (const MachineInstr * MI, const MachineBasicBlock * MBB, const MachineFunction & MF) const virtual
Definition at line 1524 of file ARMBaseInstrInfo.cpp.
References llvm::MachineInstr::definesRegister(), llvm::MachineBasicBlock::end(), I, llvm::MachineInstr::isCall(), llvm::MachineInstr::isDebugValue(), llvm::MachineInstr::isLabel(), isProfitableToIfCvt(), llvm::MachineInstr::isTerminator(), and llvm::A64CC::MI.
Referenced by getPredicate().
unsigned ARMBaseInstrInfo::isStoreToStackSlot (const MachineInstr * MI, int & FrameIndex) const virtual
Definition at line 920 of file ARMBaseInstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), llvm::MachineOperand::isFI(), llvm::MachineOperand::isImm(), and llvm::MachineOperand::isReg().
Referenced by getPredicate().
unsigned ARMBaseInstrInfo::isStoreToStackSlotPostFE (const MachineInstr * MI, int & FrameIndex) const virtual
Definition at line 968 of file ARMBaseInstrInfo.cpp.
References llvm::NVPTXISD::Dummy, loadRegFromStackSlot(), and llvm::MachineInstr::mayStore().
Referenced by getPredicate().
bool ARMBaseInstrInfo::isSwiftFastImmShift (const MachineInstr * MI) const
Returns true if the instruction has a shift by immediate that can be executed in one cycle less.
Definition at line 4338 of file ARMBaseInstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::ARM_AM::getSORegOffset(), llvm::ARM_AM::getSORegShOp(), llvm::ARM_AM::lsl, and llvm::ARM_AM::lsr.
Referenced by canCauseFpMLxStall().
void ARMBaseInstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const virtual
Reimplemented in llvm::Thumb2InstrInfo, and llvm::Thumb1InstrInfo.
Definition at line 975 of file ARMBaseInstrInfo.cpp.
References llvm::AddDefaultPred(), AddDReg(), llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), Align, llvm::BuildMI(), llvm::RegState::DefineNoRead, llvm::MachineBasicBlock::end(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), getRegisterInfo(), llvm::TargetRegisterClass::getSize(), llvm::ARMSubtarget::hasV5TEOps(), llvm::RegState::ImplicitDefine, llvm::TargetRegisterInfo::isPhysicalRegister(), llvm_unreachable, and llvm::MachineMemOperand::MOLoad.
Referenced by getPredicate(), isStoreToStackSlotPostFE(), and llvm::Thumb2InstrInfo::loadRegFromStackSlot().
bool ARMBaseInstrInfo::optimizeCompareInstr (MachineInstr * CmpInstr, unsigned SrcReg, unsigned SrcReg2, int CmpMask, int CmpValue, const MachineRegisterInfo * MRI) const virtual
optimizeCompareInstr - Convert the instruction to set the zero flag so that we can remove a "comparison with zero"; Remove a redundant CMP instruction if the flags can be updated in the same way by an earlier instruction such as SUB.
optimizeCompareInstr - Convert the instruction supplying the argument to the comparison into one that sets the zero bit in the flags register; Remove a redundant Compare instruction if an earlier instruction can set the flags in the same way as Compare. E.g. SUBrr(r1,r2) and CMPrr(r1,r2). We also handle the case where two operands are swapped: SUBrr(r1,r2) and CMPrr(r2,r1), by updating the condition code of instructions which use the flags.
Definition at line 2228 of file ARMBaseInstrInfo.cpp.
References llvm::ARMCC::AL, B, llvm::MachineBasicBlock::begin(), CC, llvm::MachineOperand::clobbersPhysReg(), llvm::MachineBasicBlock::end(), llvm::ARMCC::EQ, llvm::MachineInstr::eraseFromParent(), llvm::ARMCC::GE, llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), getRegisterInfo(), getSwappedCondition(), llvm::MachineRegisterInfo::getUniqueVRegDef(), llvm::ARMCC::GT, i, I, llvm::MachineOperand::isDef(), isPredicated(), isRedundantFlagInstr(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRegMask(), isSuitableForMask(), llvm::ARMCC::LE, llvm::ARMCC::LT, llvm::A64CC::MI, llvm::MachineInstr::modifiesRegister(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::MachineInstr::readsRegister(), llvm::MachineOperand::setIsDef(), llvm::MachineOperand::setReg(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_end(), llvm::MachineRegisterInfo::use_begin(), llvm::MachineRegisterInfo::use_end(), llvm::ARMCC::VC, and llvm::ARMCC::VS.
Referenced by isProfitableToDupForIfCvt(), and isRedundantFlagInstr().
MachineInstr * ARMBaseInstrInfo::optimizeSelect (MachineInstr * MI, bool PreferFalse) const virtual
Definition at line 1725 of file ARMBaseInstrInfo.cpp.
References llvm::AddDefaultCC(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addOperand(), llvm::BuildMI(), canFoldIntoMOVCC(), llvm::MachineRegisterInfo::constrainRegClass(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::ARMCC::getOppositeCondition(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::MachineInstr::hasOptionalDef(), i, llvm::A64CC::MI, MRI, llvm::MachineOperand::setImplicit(), and llvm::MachineInstr::tieOperands().
Referenced by isProfitableToDupForIfCvt().
bool ARMBaseInstrInfo::PredicateInstruction (MachineInstr * MI, const SmallVectorImpl< MachineOperand > & Pred) const virtual
Definition at line 454 of file ARMBaseInstrInfo.cpp.
References llvm::MachineInstr::findFirstPredOperandIdx(), llvm::getMatchingCondBranchOpcode(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), getReg(), llvm::isUncondBranchOpcode(), llvm::A64CC::MI, llvm::MachineInstr::setDesc(), llvm::MachineOperand::setImm(), llvm::MachineOperand::setReg(), and SubsumesPredicate().
Referenced by getPredicate(), and isPredicated().
bool ARMBaseInstrInfo::produceSameValue (const MachineInstr * MI0, const MachineInstr * MI1, const MachineRegisterInfo * MRI) const virtual
Definition at line 1320 of file ARMBaseInstrInfo.cpp.
References llvm::MachineConstantPoolEntry::ConstVal, llvm::MachineFunction::getConstantPool(), llvm::MachineConstantPool::getConstants(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getIndex(), llvm::MachineInstr::getNumOperands(), llvm::MachineOperand::getOffset(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getVRegDef(), llvm::ARMConstantPoolValue::hasSameValue(), i, llvm::MachineInstr::IgnoreVRegDefs, llvm::MachineOperand::isIdenticalTo(), llvm::MachineInstr::isIdenticalTo(), llvm::MachineConstantPoolEntry::isMachineConstantPoolEntry(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::MachineConstantPoolEntry::MachineCPVal, and llvm::MachineConstantPoolEntry::Val.
Referenced by getPredicate().
void ARMBaseInstrInfo::reMaterialize (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, unsigned DestReg, unsigned SubIdx, const MachineInstr * Orig, const TargetRegisterInfo & TRI) const virtual
Definition at line 1277 of file ARMBaseInstrInfo.cpp.
References llvm::MachineInstrBuilder::addConstantPoolIndex(), llvm::MachineInstrBuilder::addImm(), llvm::BuildMI(), llvm::MachineFunction::CloneMachineInstr(), duplicateCPV(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getIndex(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineBasicBlock::insert(), llvm::MachineInstr::memoperands_begin(), llvm::MachineInstr::memoperands_end(), llvm::MachineInstr::setMemRefs(), and llvm::MachineInstr::substituteRegister().
Referenced by duplicateCPV(), and getPredicate().
unsigned ARMBaseInstrInfo::RemoveBranch (MachineBasicBlock & MBB) const virtual
Definition at line 363 of file ARMBaseInstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), I, llvm::isCondBranchOpcode(), and llvm::isUncondBranchOpcode().
Referenced by getSubtarget().
bool ARMBaseInstrInfo::ReverseBranchCondition (SmallVectorImpl< MachineOperand > & Cond) const virtual
Definition at line 431 of file ARMBaseInstrInfo.cpp.
References CC, and llvm::ARMCC::getOppositeCondition().
Referenced by getSubtarget(), and InsertBranch().
void ARMBaseInstrInfo::setExecutionDomain (MachineInstr * MI, unsigned Domain) const
Definition at line 4032 of file ARMBaseInstrInfo.cpp.
References llvm::AddDefaultPred(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::RegState::Define, ExeNEON, getCorrespondingDRegAndLane(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getDesc(), getImplicitSPRUseForDPRUse(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), getPartialRegUpdateClearance(), llvm::MachineOperand::getReg(), getRegisterInfo(), llvm::getUndefRegState(), i, llvm::RegState::Implicit, isPredicated(), llvm_unreachable, llvm::A64CC::MI, llvm::MachineInstr::readsRegister(), llvm::MachineInstr::RemoveOperand(), llvm::MachineInstr::setDesc(), and llvm::RegState::Undef.
Referenced by isProfitableToDupForIfCvt().
bool ARMBaseInstrInfo::shouldScheduleLoadsNear (SDNode * Load1, SDNode * Load2, int64_t Offset1, int64_t Offset2, unsigned NumLoads) const virtual
shouldScheduleLoadsNear - This is a used by the pre-regalloc scheduler to determine (in conjunction with areLoadsFromSameBasePtr) if two loads should be scheduled togther. On some targets if two loads are loading from addresses in the same cache line, it's better if they are scheduled together. This function takes two integers that represent the load offsets from the common base address. It returns true if it decides it's desirable to schedule the two loads together. "NumLoads" is the number of loads that have already been scheduled after Load1.
shouldScheduleLoadsNear - This is a used by the pre-regalloc scheduler to determine (in conjunction with areLoadsFromSameBasePtr) if two loads should be scheduled togther. On some targets if two loads are loading from addresses in the same cache line, it's better if they are scheduled together. This function takes two integers that represent the load offsets from the common base address. It returns true if it decides it's desirable to schedule the two loads together. "NumLoads" is the number of loads that have already been scheduled after Load1.
FIXME: remove this in favor of the MachineInstr interface once pre-RA-sched is permanently disabled.
Definition at line 1494 of file ARMBaseInstrInfo.cpp.
References llvm::SDNode::getMachineOpcode(), and llvm::ARMSubtarget::isThumb1Only().
Referenced by getPredicate().
void ARMBaseInstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const virtual
Reimplemented in llvm::Thumb2InstrInfo, and llvm::Thumb1InstrInfo.
Definition at line 784 of file ARMBaseInstrInfo.cpp.
References llvm::AddDefaultPred(), AddDReg(), llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), Align, llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::getKillRegState(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), getRegisterInfo(), llvm::TargetRegisterClass::getSize(), llvm::ARMSubtarget::hasV5TEOps(), llvm_unreachable, and llvm::MachineMemOperand::MOStore.
Referenced by AddDReg(), getPredicate(), and llvm::Thumb2InstrInfo::storeRegToStackSlot().
bool ARMBaseInstrInfo::SubsumesPredicate (const SmallVectorImpl< MachineOperand > & Pred1, const SmallVectorImpl< MachineOperand > & Pred2) const virtual
Definition at line 476 of file ARMBaseInstrInfo.cpp.
References llvm::ARMCC::AL, llvm::ARMCC::EQ, llvm::ARMCC::GE, llvm::ARMCC::GT, llvm::ARMCC::HI, llvm::ARMCC::HS, llvm::ARMCC::LE, llvm::ARMCC::LO, llvm::ARMCC::LS, llvm::ARMCC::LT, and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by getPredicate(), and PredicateInstruction().
The documentation for this class was generated from the following files:
ARMBaseInstrInfo.h
ARMBaseInstrInfo.cpp