LLVM: llvm::MCSectionCOFF Class Reference
LLVM API Documentation
llvm::MCSectionCOFF Class Reference
MCSectionCOFF - This represents a section on Windows.
#include <MCSectionCOFF.h>
Public Member Functions
bool ShouldOmitSectionDirective (StringRef Name, const MCAsmInfo &MAI) const
StringRef getSectionName () const
virtual std::string getLabelBeginName () const
virtual std::string getLabelEndName () const
unsigned getCharacteristics () const
int getSelection () const
const MCSectionCOFF * getAssocSection () const
void setSelection (int Selection, const MCSectionCOFF *Assoc=0) const
virtual void PrintSwitchToSection (const MCAsmInfo &MAI, raw_ostream &OS, const MCExpr *Subsection) const
virtual bool UseCodeAlign () const
virtual bool isVirtualSection () const
Public Member Functions inherited from llvm::MCSection
virtual ~MCSection ()
SectionKind getKind () const
SectionVariant getVariant () const
virtual bool isBaseAddressKnownZero () const
Static Public Member Functions
static bool classof (const MCSection *S)
Friends
class MCContext
Additional Inherited Members
Public Types inherited from llvm::MCSection
enum SectionVariant { SV_COFF = 0, SV_ELF, SV_MachO }
Protected Member Functions inherited from llvm::MCSection
MCSection (SectionVariant V, SectionKind K)
Protected Attributes inherited from llvm::MCSection
SectionVariant Variant
SectionKind Kind
Detailed Description
MCSectionCOFF - This represents a section on Windows.
Definition at line 25 of file MCSectionCOFF.h.
Member Function Documentation
static bool llvm::MCSectionCOFF::classof (const MCSection * S) inline static
Definition at line 90 of file MCSectionCOFF.h.
References llvm::MCSection::getVariant(), and llvm::MCSection::SV_COFF.
const MCSectionCOFF* llvm::MCSectionCOFF::getAssocSection () const inline
Definition at line 80 of file MCSectionCOFF.h.
References isVirtualSection(), PrintSwitchToSection(), setSelection(), and UseCodeAlign().
Referenced by write_uint32_le().
unsigned llvm::MCSectionCOFF::getCharacteristics () const inline
Definition at line 78 of file MCSectionCOFF.h.
References Characteristics.
Referenced by computeSectionKind(), isVirtualSection(), and PrintSwitchToSection().
virtual std::string llvm::MCSectionCOFF::getLabelBeginName () const inline virtual
Implements llvm::MCSection.
Definition at line 72 of file MCSectionCOFF.h.
References llvm::StringRef::str().
virtual std::string llvm::MCSectionCOFF::getLabelEndName () const inline virtual
Implements llvm::MCSection.
Definition at line 75 of file MCSectionCOFF.h.
References llvm::StringRef::str().
StringRef llvm::MCSectionCOFF::getSectionName () const inline
Definition at line 71 of file MCSectionCOFF.h.
Referenced by computeSectionKind(), llvm::MCWin64EHUnwindEmitter::GetSectionSuffix(), PrintSwitchToSection(), and write_uint32_le().
int llvm::MCSectionCOFF::getSelection () const inline
Definition at line 79 of file MCSectionCOFF.h.
Referenced by computeSectionKind().
bool MCSectionCOFF::isVirtualSection () const virtual
isVirtualSection - Check whether this section is "virtual", that is has no actual object file contents.
Implements llvm::MCSection.
Definition at line 97 of file MCSectionCOFF.cpp.
References getCharacteristics().
Referenced by getAssocSection().
void MCSectionCOFF::PrintSwitchToSection (const MCAsmInfo & MAI, raw_ostream & OS, const MCExpr * Subsection) const virtual
Implements llvm::MCSection.
Definition at line 42 of file MCSectionCOFF.cpp.
References getCharacteristics(), llvm::MCSection::getKind(), getSectionName(), llvm::COFF::IMAGE_COMDAT_SELECT_ANY, llvm::COFF::IMAGE_COMDAT_SELECT_ASSOCIATIVE, llvm::COFF::IMAGE_COMDAT_SELECT_EXACT_MATCH, llvm::COFF::IMAGE_COMDAT_SELECT_LARGEST, llvm::COFF::IMAGE_COMDAT_SELECT_NEWEST, llvm::COFF::IMAGE_COMDAT_SELECT_NODUPLICATES, llvm::COFF::IMAGE_COMDAT_SELECT_SAME_SIZE, and ShouldOmitSectionDirective().
Referenced by getAssocSection().
void MCSectionCOFF::setSelection (int Selection, const MCSectionCOFF * Assoc = 0) const
Definition at line 31 of file MCSectionCOFF.cpp.
References llvm::COFF::IMAGE_COMDAT_SELECT_ASSOCIATIVE.
Referenced by computeSectionKind(), and getAssocSection().
bool MCSectionCOFF::ShouldOmitSectionDirective (StringRef Name, const MCAsmInfo & MAI) const
ShouldOmitSectionDirective - Decides whether a '.section' directive should be printed before the section name
Definition at line 21 of file MCSectionCOFF.cpp.
Referenced by PrintSwitchToSection().
bool MCSectionCOFF::UseCodeAlign () const virtual
Implements llvm::MCSection.
Definition at line 93 of file MCSectionCOFF.cpp.
References llvm::MCSection::getKind(), and llvm::SectionKind::isText().
Referenced by getAssocSection().
Friends And Related Function Documentation
friend class MCContext friend
Definition at line 51 of file MCSectionCOFF.h.
The documentation for this class was generated from the following files:
MCSectionCOFF.h
MCSectionCOFF.cpp