LLVM: llvm::SDDbgValue Class Reference
LLVM API Documentation
llvm::SDDbgValue Class Reference
#include <SDNodeDbgValue.h>
Public Types
enum DbgValueKind { SDNODE = 0, CONST = 1, FRAMEIX = 2 }
Public Member Functions
SDDbgValue (MDNode *mdP, SDNode *N, unsigned R, uint64_t off, DebugLoc dl, unsigned O)
SDDbgValue (MDNode *mdP, const Value *C, uint64_t off, DebugLoc dl, unsigned O)
SDDbgValue (MDNode *mdP, unsigned FI, uint64_t off, DebugLoc dl, unsigned O)
DbgValueKind getKind ()
MDNode * getMDPtr ()
SDNode * getSDNode ()
unsigned getResNo ()
const Value * getConst ()
unsigned getFrameIx ()
uint64_t getOffset ()
DebugLoc getDebugLoc ()
unsigned getOrder ()
void setIsInvalidated ()
bool isInvalidated ()
Detailed Description
SDDbgValue - Holds the information from a dbg_value node through SDISel. We do not use SDValue here to avoid including its header.
Definition at line 30 of file SDNodeDbgValue.h.
Member Enumeration Documentation
enum llvm::SDDbgValue::DbgValueKind
Enumerator
SDNODE
CONST
FRAMEIX
Definition at line 32 of file SDNodeDbgValue.h.
Constructor & Destructor Documentation
llvm::SDDbgValue::SDDbgValue (MDNode * mdP, SDNode * N, unsigned R, uint64_t off, DebugLoc dl, unsigned O) inline
Definition at line 54 of file SDNodeDbgValue.h.
References N, and SDNODE.
llvm::SDDbgValue::SDDbgValue (MDNode * mdP, const Value * C, uint64_t off, DebugLoc dl, unsigned O) inline
Definition at line 63 of file SDNodeDbgValue.h.
References CONST.
llvm::SDDbgValue::SDDbgValue (MDNode * mdP, unsigned FI, uint64_t off, DebugLoc dl, unsigned O) inline
Definition at line 71 of file SDNodeDbgValue.h.
References FRAMEIX.
Member Function Documentation
const Value* llvm::SDDbgValue::getConst () inline
Definition at line 90 of file SDNodeDbgValue.h.
References CONST.
Referenced by llvm::InstrEmitter::EmitDbgValue().
DebugLoc llvm::SDDbgValue::getDebugLoc () inline
Definition at line 99 of file SDNodeDbgValue.h.
Referenced by llvm::InstrEmitter::EmitDbgValue(), and llvm::SelectionDAG::TransferDbgValues().
unsigned llvm::SDDbgValue::getFrameIx () inline
Definition at line 93 of file SDNodeDbgValue.h.
References FRAMEIX.
Referenced by llvm::InstrEmitter::EmitDbgValue().
DbgValueKind llvm::SDDbgValue::getKind () inline
Definition at line 78 of file SDNodeDbgValue.h.
Referenced by llvm::InstrEmitter::EmitDbgValue(), and llvm::SelectionDAG::TransferDbgValues().
MDNode* llvm::SDDbgValue::getMDPtr () inline
Definition at line 81 of file SDNodeDbgValue.h.
Referenced by llvm::InstrEmitter::EmitDbgValue(), and llvm::SelectionDAG::TransferDbgValues().
uint64_t llvm::SDDbgValue::getOffset () inline
Definition at line 96 of file SDNodeDbgValue.h.
Referenced by llvm::InstrEmitter::EmitDbgValue(), and llvm::SelectionDAG::TransferDbgValues().
unsigned llvm::SDDbgValue::getOrder () inline
Definition at line 103 of file SDNodeDbgValue.h.
Referenced by llvm::SelectionDAG::TransferDbgValues().
unsigned llvm::SDDbgValue::getResNo () inline
Definition at line 87 of file SDNodeDbgValue.h.
References SDNODE.
Referenced by llvm::InstrEmitter::EmitDbgValue().
SDNode* llvm::SDDbgValue::getSDNode () inline
Definition at line 84 of file SDNodeDbgValue.h.
References SDNODE.
Referenced by llvm::InstrEmitter::EmitDbgValue().
bool llvm::SDDbgValue::isInvalidated () inline
Definition at line 109 of file SDNodeDbgValue.h.
void llvm::SDDbgValue::setIsInvalidated () inline
Definition at line 108 of file SDNodeDbgValue.h.
Member Data Documentation
const Value* llvm::SDDbgValue::Const
Definition at line 44 of file SDNodeDbgValue.h.
unsigned llvm::SDDbgValue::FrameIx
Definition at line 45 of file SDNodeDbgValue.h.
SDNode* llvm::SDDbgValue::Node
Definition at line 41 of file SDNodeDbgValue.h.
unsigned llvm::SDDbgValue::ResNo
Definition at line 42 of file SDNodeDbgValue.h.
struct { ... } llvm::SDDbgValue::s
The documentation for this class was generated from the following file:
SDNodeDbgValue.h