LLVM: llvm::MCRegAliasIterator Class Reference
LLVM API Documentation
llvm::MCRegAliasIterator Class Reference
#include <MCRegisterInfo.h>
Public Member Functions
MCRegAliasIterator (unsigned Reg, const MCRegisterInfo *MCRI, bool IncludeSelf)
bool isValid () const
unsigned operator* () const
void advance ()
void operator++ ()
Detailed Description
MCRegAliasIterator enumerates all registers aliasing Reg. If IncludeSelf is set, Reg itself is included in the list. This iterator does not guarantee any ordering or that entries are unique.
Definition at line 555 of file MCRegisterInfo.h.
Constructor & Destructor Documentation
llvm::MCRegAliasIterator::MCRegAliasIterator (unsigned Reg, const MCRegisterInfo * MCRI, bool IncludeSelf) inline
Definition at line 565 of file MCRegisterInfo.h.
References llvm::MCRegisterInfo::DiffListIterator::isValid(), and llvm::MCRegUnitRootIterator::isValid().
Member Function Documentation
void llvm::MCRegAliasIterator::advance () inline
Definition at line 589 of file MCRegisterInfo.h.
References llvm::MCRegisterInfo::DiffListIterator::isValid(), and llvm::MCRegUnitRootIterator::isValid().
bool llvm::MCRegAliasIterator::isValid () const inline
Definition at line 580 of file MCRegisterInfo.h.
References llvm::MCRegisterInfo::DiffListIterator::isValid().
Referenced by addLiveInRegs(), llvm::ScheduleDAGInstrs::addPhysRegDataDeps(), llvm::ScheduleDAGInstrs::addPhysRegDeps(), llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::addRegisterKilled(), llvm::DwarfDebug::beginFunction(), CheckForLiveRegDef(), llvm::MachineBasicBlock::computeRegisterLiveness(), llvm::createSparcDelaySlotFillerPass(), CriticalPathStep(), findDeadCallerSavedReg(), findHoistingInsertPosAndDeps(), llvm::RegScavenger::getRegsAvailable(), llvm::SparcRegisterInfo::getReservedRegs(), llvm::X86RegisterInfo::getReservedRegs(), llvm::Hexagon_CCState::HandleByVal(), llvm::CCState::HandleByVal(), INITIALIZE_PASS(), InstructionStoresToFI(), llvm::MachineRegisterInfo::isConstantPhysReg(), isNopCopy(), llvm::MachineInstr::print(), printModifiedFPRAsmOperand(), printModifiedGPRAsmOperand(), llvm::RegisterClassInfo::runOnMachineFunction(), llvm::RegScavenger::setUsed(), llvm::CriticalAntiDepBreaker::StartBlock(), and llvm::AggressiveAntiDepBreaker::StartBlock().
unsigned llvm::MCRegAliasIterator::operator* () const inline
Definition at line 584 of file MCRegisterInfo.h.
References llvm::MCRegisterInfo::DiffListIterator::isValid().
void llvm::MCRegAliasIterator::operator++ () inline
Definition at line 607 of file MCRegisterInfo.h.
References llvm::object::advance().
The documentation for this class was generated from the following file:
MCRegisterInfo.h