LLVM: llvm::LiveIntervalUnion::Query Class Reference
LLVM API Documentation
llvm::LiveIntervalUnion::Query Class Reference
#include <LiveIntervalUnion.h>
Public Member Functions
Query ()
Query (LiveInterval *VReg, LiveIntervalUnion *LIU)
void clear ()
void init (unsigned UTag, LiveInterval *VReg, LiveIntervalUnion *LIU)
LiveInterval & virtReg () const
bool checkInterference ()
unsigned collectInterferingVRegs (unsigned MaxInterferingRegs=UINT_MAX)
bool isSeenInterference (LiveInterval *VReg) const
NDEBUG.
bool seenAllInterferences () const
bool seenUnspillableVReg () const
const SmallVectorImpl< LiveInterval * > & interferingVRegs () const
Detailed Description
Query interferences between a single live virtual register and a live interval union.
Definition at line 105 of file LiveIntervalUnion.h.
Constructor & Destructor Documentation
llvm::LiveIntervalUnion::Query::Query () inline
Definition at line 117 of file LiveIntervalUnion.h.
Referenced by interferingVRegs().
llvm::LiveIntervalUnion::Query::Query (LiveInterval * VReg, LiveIntervalUnion * LIU) inline
Definition at line 119 of file LiveIntervalUnion.h.
Member Function Documentation
bool llvm::LiveIntervalUnion::Query::checkInterference () inline
Definition at line 155 of file LiveIntervalUnion.h.
References collectInterferingVRegs(), and isSeenInterference().
Referenced by llvm::LiveRegMatrix::checkInterference().
void llvm::LiveIntervalUnion::Query::clear () inline
Definition at line 124 of file LiveIntervalUnion.h.
References llvm::SmallVectorImpl< T >::clear().
Referenced by init(), llvm::LiveIntervalUnion::Array::size(), and llvm::LiveIntervalUnion::Array::~Array().
unsigned LiveIntervalUnion::Query::collectInterferingVRegs (unsigned MaxInterferingRegs = UINT_MAX)
Definition at line 119 of file LiveIntervalUnion.cpp.
References llvm::LiveRange::size().
Referenced by checkInterference(), llvm::createGreedyRegisterAllocator(), and isSeenInterference().
void llvm::LiveIntervalUnion::Query::init (unsigned UTag, LiveInterval * VReg, LiveIntervalUnion * LIU) inline
Definition at line 135 of file LiveIntervalUnion.h.
References llvm::LiveIntervalUnion::changedSince(), clear(), and llvm::LiveIntervalUnion::getTag().
Referenced by llvm::LiveRegMatrix::query(), and llvm::LiveIntervalUnion::Array::~Array().
const SmallVectorImpl<LiveInterval*>& llvm::LiveIntervalUnion::Query::interferingVRegs () const inline
Definition at line 171 of file LiveIntervalUnion.h.
References LLVM_DELETED_FUNCTION, and Query().
Referenced by llvm::createGreedyRegisterAllocator().
bool LiveIntervalUnion::Query::isSeenInterference (LiveInterval * VReg) const
NDEBUG.
Definition at line 103 of file LiveIntervalUnion.cpp.
References collectInterferingVRegs(), and I.
Referenced by checkInterference().
bool llvm::LiveIntervalUnion::Query::seenAllInterferences () const inline
Definition at line 165 of file LiveIntervalUnion.h.
Referenced by llvm::createGreedyRegisterAllocator().
bool llvm::LiveIntervalUnion::Query::seenUnspillableVReg () const inline
Definition at line 168 of file LiveIntervalUnion.h.
LiveInterval& llvm::LiveIntervalUnion::Query::virtReg () const inline
Definition at line 149 of file LiveIntervalUnion.h.
The documentation for this class was generated from the following files:
LiveIntervalUnion.h
LiveIntervalUnion.cpp