LLVM: llvm::LiveRegUnits Class Reference
LLVM API Documentation
llvm::LiveRegUnits Class Reference
#include <LiveRegUnits.h>
Public Member Functions
LiveRegUnits ()
Constructs a new empty LiveRegUnits set.
void init (const TargetRegisterInfo *TRI)
void clear ()
bool empty () const
void addReg (unsigned Reg, const MCRegisterInfo &MCRI)
Adds a register to the set.
void removeReg (unsigned Reg, const MCRegisterInfo &MCRI)
Removes a register from the set.
void removeRegsInMask (const MachineOperand &Op, const MCRegisterInfo &MCRI)
Removes registers clobbered by the regmask operand Op.
bool contains (unsigned Reg, const MCRegisterInfo &MCRI) const
Returns true if register Reg (or one of its super register) is contained in the set.
void stepBackward (const MachineInstr &MI, const MCRegisterInfo &MCRI)
Simulates liveness when stepping backwards over an instruction(bundle): Remove Defs, add uses.
void stepForward (const MachineInstr &MI, const MCRegisterInfo &MCRI)
Simulates liveness when stepping forward over an instruction(bundle): Remove killed-uses, add defs.
void addLiveIns (const MachineBasicBlock *MBB, const MCRegisterInfo &MCRI)
Adds all registers in the live-in list of block BB.
Detailed Description
A set of live register units with functions to track liveness when walking backward/forward through a basic block.
Definition at line 31 of file LiveRegUnits.h.
Constructor & Destructor Documentation
llvm::LiveRegUnits::LiveRegUnits () inline
Constructs a new empty LiveRegUnits set.
Definition at line 38 of file LiveRegUnits.h.
Member Function Documentation
void LiveRegUnits::addLiveIns (const MachineBasicBlock * MBB, const MCRegisterInfo & MCRI)
Adds all registers in the live-in list of block BB.
Definition at line 105 of file LiveRegUnits.cpp.
References addReg(), llvm::A64CC::LE, llvm::MachineBasicBlock::livein_begin(), and llvm::MachineBasicBlock::livein_end().
Referenced by contains(), and RemoveKills().
void llvm::LiveRegUnits::addReg (unsigned Reg, const MCRegisterInfo & MCRI) inline
Adds a register to the set.
Definition at line 50 of file LiveRegUnits.h.
References llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::insert(), and llvm::MCRegisterInfo::DiffListIterator::isValid().
Referenced by addLiveIns(), stepBackward(), stepForward(), and UpdatePredRedefs().
void llvm::LiveRegUnits::clear () inline
Definition at line 45 of file LiveRegUnits.h.
References llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::clear().
Referenced by RemoveKills().
bool llvm::LiveRegUnits::contains (unsigned Reg, const MCRegisterInfo & MCRI) const inline
Returns true if register Reg (or one of its super register) is contained in the set.
Definition at line 66 of file LiveRegUnits.h.
References addLiveIns(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::count(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::A64CC::MI, stepBackward(), and stepForward().
Referenced by RemoveKills(), and UpdatePredRedefs().
bool llvm::LiveRegUnits::empty () const inline
Definition at line 47 of file LiveRegUnits.h.
References llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::empty().
Referenced by MaySpeculate().
void llvm::LiveRegUnits::init (const TargetRegisterInfo * TRI) inline
Definition at line 40 of file LiveRegUnits.h.
References llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::clear(), llvm::MCRegisterInfo::getNumRegs(), and llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::setUniverse().
Referenced by RemoveKills().
void llvm::LiveRegUnits::removeReg (unsigned Reg, const MCRegisterInfo & MCRI) inline
Removes a register from the set.
Definition at line 56 of file LiveRegUnits.h.
References llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::erase(), llvm::MCRegisterInfo::DiffListIterator::isValid(), and removeRegsInMask().
Referenced by stepBackward(), stepForward(), and UpdatePredRedefs().
void LiveRegUnits::removeRegsInMask (const MachineOperand & Op, const MCRegisterInfo & MCRI)
Removes registers clobbered by the regmask operand Op.
We assume the high bits of a physical super register are not preserved unless the instruction has an implicit-use operand reading the super-register or a register unit for the upper bits is available.
Definition at line 36 of file LiveRegUnits.cpp.
References llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::begin(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::end(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::erase(), and operClobbersUnit().
Referenced by removeReg(), stepBackward(), and stepForward().
void LiveRegUnits::stepBackward (const MachineInstr & MI, const MCRegisterInfo & MCRI)
Simulates liveness when stepping backwards over an instruction(bundle): Remove Defs, add uses.
Definition at line 47 of file LiveRegUnits.cpp.
References addReg(), llvm::MachineOperandIteratorBase::isValid(), removeReg(), and removeRegsInMask().
Referenced by contains(), and RemoveKills().
void LiveRegUnits::stepForward (const MachineInstr & MI, const MCRegisterInfo & MCRI)
Simulates liveness when stepping forward over an instruction(bundle): Remove killed-uses, add defs.
Uses with kill flag get removed from the set, defs added. If possible use StepBackward() instead of this function because some kill flags may be missing.
Definition at line 76 of file LiveRegUnits.cpp.
References addReg(), i, llvm::MachineOperandIteratorBase::isValid(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), removeReg(), removeRegsInMask(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by contains(), and RemoveKills().
The documentation for this class was generated from the following files:
LiveRegUnits.h
LiveRegUnits.cpp