LLVM: llvm::AliasSetTracker Class Reference
LLVM API Documentation
llvm::AliasSetTracker Class Reference
#include <AliasSetTracker.h>
Public Types
typedef ilist< AliasSet >::iterator iterator
typedef ilist< AliasSet >::const_iterator const_iterator
Public Member Functions
AliasSetTracker (AliasAnalysis &aa)
~AliasSetTracker ()
bool add (Value *Ptr, uint64_t Size, const MDNode *TBAAInfo)
bool add (LoadInst *LI)
bool add (StoreInst *SI)
bool add (VAArgInst *VAAI)
bool add (Instruction *I)
void add (BasicBlock &BB)
void add (const AliasSetTracker &AST)
bool addUnknown (Instruction *I)
bool remove (Value *Ptr, uint64_t Size, const MDNode *TBAAInfo)
bool remove (LoadInst *LI)
bool remove (StoreInst *SI)
bool remove (VAArgInst *VAAI)
bool remove (Instruction *I)
void remove (AliasSet &AS)
bool removeUnknown (Instruction *I)
void clear ()
const ilist< AliasSet > & getAliasSets () const
AliasSet & getAliasSetForPointer (Value *P, uint64_t Size, const MDNode *TBAAInfo, bool *New=0)
AliasSet * getAliasSetForPointerIfExists (Value *P, uint64_t Size, const MDNode *TBAAInfo)
bool containsPointer (Value *P, uint64_t Size, const MDNode *TBAAInfo) const
AliasAnalysis & getAliasAnalysis () const
void deleteValue (Value *PtrVal)
void copyValue (Value *From, Value *To)
const_iterator begin () const
const_iterator end () const
iterator begin ()
iterator end ()
void print (raw_ostream &OS) const
void dump () const
Friends
class AliasSet
Detailed Description
Definition at line 280 of file AliasSetTracker.h.
Member Typedef Documentation
typedef ilist<AliasSet>::const_iterator llvm::AliasSetTracker::const_iterator
Definition at line 392 of file AliasSetTracker.h.
typedef ilist<AliasSet>::iterator llvm::AliasSetTracker::iterator
Definition at line 391 of file AliasSetTracker.h.
Constructor & Destructor Documentation
llvm::AliasSetTracker::AliasSetTracker (AliasAnalysis & aa) inline explicit
AliasSetTracker ctor - Create an empty collection of AliasSets, and use the specified alias analysis object to disambiguate load and store addresses.
Definition at line 309 of file AliasSetTracker.h.
llvm::AliasSetTracker::~AliasSetTracker () inline
Definition at line 310 of file AliasSetTracker.h.
References llvm::ARM_AM::add, BB, and I.
Member Function Documentation
bool AliasSetTracker::add (Value * Ptr, uint64_t Size, const MDNode * TBAAInfo)
add methods - These methods are used to add different types of instructions to the alias sets. Adding a new instruction can result in one of three actions happening:
If the instruction doesn't alias any other sets, create a new set.
If the instruction aliases exactly one set, add it to the set
If the instruction aliases multiple sets, merge the sets, and add the instruction to the result.
These methods return true if inserting the instruction resulted in the addition of a new alias set (i.e., the pointer did not alias anything).
Definition at line 292 of file AliasSetTracker.cpp.
Referenced by dump(), and isSimpleLoadStore().
bool AliasSetTracker::add (LoadInst * LI)
Definition at line 299 of file AliasSetTracker.cpp.
References llvm::Instruction::getMetadata(), llvm::User::getOperand(), llvm::LoadInst::getOrdering(), llvm::Value::getType(), llvm::AliasAnalysis::getTypeStoreSize(), llvm::LoadInst::isVolatile(), llvm::LLVMContext::MD_tbaa, and llvm::Monotonic.
bool AliasSetTracker::add (StoreInst * SI)
Definition at line 311 of file AliasSetTracker.cpp.
References llvm::Instruction::getMetadata(), llvm::User::getOperand(), llvm::StoreInst::getOrdering(), llvm::Value::getType(), llvm::AliasAnalysis::getTypeStoreSize(), llvm::StoreInst::isVolatile(), llvm::LLVMContext::MD_tbaa, and llvm::Monotonic.
bool AliasSetTracker::add (VAArgInst * VAAI)
Definition at line 324 of file AliasSetTracker.cpp.
References llvm::Instruction::getMetadata(), llvm::User::getOperand(), llvm::LLVMContext::MD_tbaa, and llvm::AliasAnalysis::UnknownSize.
bool AliasSetTracker::add (Instruction * I)
Definition at line 350 of file AliasSetTracker.cpp.
References llvm::ARM_AM::add.
void AliasSetTracker::add (BasicBlock & BB)
Definition at line 361 of file AliasSetTracker.cpp.
References llvm::ARM_AM::add, llvm::BasicBlock::begin(), llvm::BasicBlock::end(), and I.
void AliasSetTracker::add (const AliasSetTracker & AST)
Definition at line 366 of file AliasSetTracker.cpp.
References llvm::ARM_AM::add, llvm::AliasSet::begin(), begin(), llvm::AliasSet::end(), end(), i, I, llvm::AliasSet::isVolatile(), and llvm::X.
bool AliasSetTracker::addUnknown (Instruction * I)
Definition at line 333 of file AliasSetTracker.cpp.
References llvm::Instruction::mayReadOrWriteMemory().
const_iterator llvm::AliasSetTracker::begin () const inline
Definition at line 394 of file AliasSetTracker.h.
References llvm::iplist< NodeTy >::begin().
Referenced by add(), llvm::createLICMPass(), and isSimpleLoadStore().
iterator llvm::AliasSetTracker::begin () inline
Definition at line 397 of file AliasSetTracker.h.
References llvm::iplist< NodeTy >::begin().
void AliasSetTracker::clear ()
Definition at line 201 of file AliasSetTracker.cpp.
References llvm::AliasSet::begin(), llvm::AliasSet::end(), I, and llvm::AliasSet::mergeSetIn().
bool AliasSetTracker::containsPointer (Value * Ptr, uint64_t Size, const MDNode * TBAAInfo) const
containsPointer - Return true if the specified location is represented by this alias set, false otherwise. This does not modify the AST object or alias sets.
Definition at line 238 of file AliasSetTracker.cpp.
References llvm::AliasSet::begin(), llvm::AliasSet::end(), I, and llvm::AliasSet::mergeSetIn().
void AliasSetTracker::copyValue (Value * From, Value * To)
copyValue - This method should be used whenever a preexisting value in the program is copied or cloned, introducing a new value. Note that it is ok for clients that use this method to introduce the same value multiple times: if the tracker already knows about a value, it will ignore the request.
Definition at line 523 of file AliasSetTracker.cpp.
References llvm::AliasAnalysis::copyValue().
Referenced by llvm::createLICMPass(), and dump().
void AliasSetTracker::deleteValue (Value * PtrVal)
deleteValue method - This method is used to remove a pointer value from the AliasSetTracker entirely. It should be used when an instruction is deleted from the program to update the AST. If you don't use this, you would have dangling pointers to deleted instructions.
Definition at line 484 of file AliasSetTracker.cpp.
References llvm::AliasSet::begin(), llvm::AliasAnalysis::deleteValue(), llvm::AliasSet::end(), I, and llvm::Instruction::mayReadOrWriteMemory().
Referenced by llvm::createLICMPass(), dump(), promoteSingleBlockAlloca(), and rewriteSingleStoreAlloca().
void AliasSetTracker::dump () const
Definition at line 593 of file AliasSetTracker.cpp.
References add(), llvm::AnalysisUsage::addRequired(), llvm::AliasSet::AliasSetTracker, copyValue(), llvm::dbgs(), deleteValue(), llvm::errs(), F(), llvm::PassRegistry::getPassRegistry(), I, INITIALIZE_AG_DEPENDENCY, INITIALIZE_PASS_BEGIN(), llvm::initializeAliasSetPrinterPass(), llvm::inst_begin(), llvm::inst_end(), llvm::AliasSet::print(), print(), and llvm::AnalysisUsage::setPreservesAll().
const_iterator llvm::AliasSetTracker::end () const inline
Definition at line 395 of file AliasSetTracker.h.
References llvm::iplist< NodeTy >::end().
Referenced by add(), llvm::createLICMPass(), and isSimpleLoadStore().
iterator llvm::AliasSetTracker::end () inline
Definition at line 398 of file AliasSetTracker.h.
References llvm::AliasSet::dump(), llvm::iplist< NodeTy >::end(), and llvm::AliasSet::print().
AliasAnalysis& llvm::AliasSetTracker::getAliasAnalysis () const inline
getAliasAnalysis - Return the underlying alias analysis object used by this tracker.
Definition at line 373 of file AliasSetTracker.h.
Referenced by llvm::AliasSet::mergeSetIn().
AliasSet & AliasSetTracker::getAliasSetForPointer (Value * Pointer, uint64_t Size, const MDNode * TBAAInfo, bool * New = 0)
getAliasSetForPointer - Return the alias set that the specified pointer lives in. If the New argument is non-null, this method sets the value to true if a new alias set is created to contain the pointer (because the pointer didn't alias anything).
getAliasSetForPointer - Return the alias set that the specified pointer lives in.
Definition at line 267 of file AliasSetTracker.cpp.
AliasSet* llvm::AliasSetTracker::getAliasSetForPointerIfExists (Value * P, uint64_t Size, const MDNode * TBAAInfo) inline
getAliasSetForPointerIfExists - Return the alias set containing the location specified if one exists, otherwise return null.
Definition at line 361 of file AliasSetTracker.h.
const ilist<AliasSet>& llvm::AliasSetTracker::getAliasSets () const inline
getAliasSets - Return the alias sets that are active.
Definition at line 349 of file AliasSetTracker.h.
References P.
void AliasSetTracker::print (raw_ostream & OS) const
Definition at line 583 of file AliasSetTracker.cpp.
References llvm::AliasSet::begin(), llvm::AliasSet::end(), I, and llvm::Value::print().
Referenced by dump(), and llvm::operator<<().
bool AliasSetTracker::remove (Value * Ptr, uint64_t Size, const MDNode * TBAAInfo)
remove methods - These methods are used to remove all entries that might be aliased by the specified instruction. These methods return true if any alias sets were eliminated.
Definition at line 423 of file AliasSetTracker.cpp.
bool AliasSetTracker::remove (LoadInst * LI)
Definition at line 430 of file AliasSetTracker.cpp.
References llvm::Instruction::getMetadata(), llvm::User::getOperand(), llvm::Value::getType(), llvm::AliasAnalysis::getTypeStoreSize(), and llvm::LLVMContext::MD_tbaa.
bool AliasSetTracker::remove (StoreInst * SI)
Definition at line 439 of file AliasSetTracker.cpp.
References llvm::Instruction::getMetadata(), llvm::User::getOperand(), llvm::Value::getType(), llvm::AliasAnalysis::getTypeStoreSize(), and llvm::LLVMContext::MD_tbaa.
bool AliasSetTracker::remove (VAArgInst * VAAI)
Definition at line 448 of file AliasSetTracker.cpp.
References llvm::Instruction::getMetadata(), llvm::User::getOperand(), llvm::LLVMContext::MD_tbaa, and llvm::AliasAnalysis::UnknownSize.
bool AliasSetTracker::remove (Instruction * I)
Definition at line 467 of file AliasSetTracker.cpp.
void AliasSetTracker::remove (AliasSet & AS)
remove - Remove the specified (potentially non-empty) alias set from the tracker.
Definition at line 395 of file AliasSetTracker.cpp.
References llvm::AliasSet::empty(), and P.
bool AliasSetTracker::removeUnknown (Instruction * I)
Definition at line 457 of file AliasSetTracker.cpp.
References llvm::Instruction::mayReadOrWriteMemory().
Friends And Related Function Documentation
friend class AliasSet friend
Definition at line 404 of file AliasSetTracker.h.
The documentation for this class was generated from the following files:
AliasSetTracker.h
AliasSetTracker.cpp