LLVM: llvm::AArch64MachineFunctionInfo Class Reference
LLVM API Documentation
llvm::AArch64MachineFunctionInfo Class Reference
#include <AArch64MachineFunctionInfo.h>
Public Member Functions
AArch64MachineFunctionInfo ()
AArch64MachineFunctionInfo (MachineFunction &MF)
unsigned getBytesInStackArgArea () const
void setBytesInStackArgArea (unsigned bytes)
unsigned getArgumentStackToRestore () const
void setArgumentStackToRestore (unsigned bytes)
unsigned getInitialStackAdjust () const
void setInitialStackAdjust (unsigned bytes)
unsigned getNumLocalDynamicTLSAccesses () const
void incNumLocalDynamicTLSAccesses ()
int getVariadicGPRIdx () const
void setVariadicGPRIdx (int Idx)
unsigned getVariadicGPRSize () const
void setVariadicGPRSize (unsigned Size)
int getVariadicFPRIdx () const
void setVariadicFPRIdx (int Idx)
unsigned getVariadicFPRSize () const
void setVariadicFPRSize (unsigned Size)
int getVariadicStackIdx () const
void setVariadicStackIdx (int Idx)
int getFramePointerOffset () const
void setFramePointerOffset (int Idx)
Public Member Functions inherited from llvm::MachineFunctionInfo
virtual ~MachineFunctionInfo ()
Detailed Description
This class is derived from MachineFunctionInfo and contains private AArch64 target-specific information for each MachineFunction.
Definition at line 23 of file AArch64MachineFunctionInfo.h.
Constructor & Destructor Documentation
llvm::AArch64MachineFunctionInfo::AArch64MachineFunctionInfo () inline
Definition at line 89 of file AArch64MachineFunctionInfo.h.
llvm::AArch64MachineFunctionInfo::AArch64MachineFunctionInfo (MachineFunction & MF) inline explicit
Definition at line 101 of file AArch64MachineFunctionInfo.h.
Member Function Documentation
unsigned llvm::AArch64MachineFunctionInfo::getArgumentStackToRestore () const inline
Definition at line 116 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64FrameLowering::emitEpilogue().
unsigned llvm::AArch64MachineFunctionInfo::getBytesInStackArgArea () const inline
Definition at line 113 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64TargetLowering::IsEligibleForTailCallOptimization(), and llvm::AArch64TargetLowering::LowerCall().
int llvm::AArch64MachineFunctionInfo::getFramePointerOffset () const inline
Definition at line 142 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64FrameLowering::emitEpilogue(), and llvm::AArch64FrameLowering::resolveFrameIndexReference().
unsigned llvm::AArch64MachineFunctionInfo::getInitialStackAdjust () const inline
Definition at line 121 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64FrameLowering::emitEpilogue(), and llvm::AArch64FrameLowering::resolveFrameIndexReference().
unsigned llvm::AArch64MachineFunctionInfo::getNumLocalDynamicTLSAccesses () const inline
Definition at line 124 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::emitSPUpdate().
int llvm::AArch64MachineFunctionInfo::getVariadicFPRIdx () const inline
Definition at line 133 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64TargetLowering::LowerVASTART().
unsigned llvm::AArch64MachineFunctionInfo::getVariadicFPRSize () const inline
Definition at line 136 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64TargetLowering::LowerVASTART().
int llvm::AArch64MachineFunctionInfo::getVariadicGPRIdx () const inline
Definition at line 127 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64TargetLowering::LowerVASTART().
unsigned llvm::AArch64MachineFunctionInfo::getVariadicGPRSize () const inline
Definition at line 130 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64TargetLowering::LowerVASTART().
int llvm::AArch64MachineFunctionInfo::getVariadicStackIdx () const inline
Definition at line 139 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64TargetLowering::LowerVASTART().
void llvm::AArch64MachineFunctionInfo::incNumLocalDynamicTLSAccesses () inline
Definition at line 125 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64TargetLowering::LowerGlobalTLSAddress().
void llvm::AArch64MachineFunctionInfo::setArgumentStackToRestore (unsigned bytes) inline
Definition at line 117 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64TargetLowering::LowerFormalArguments().
void llvm::AArch64MachineFunctionInfo::setBytesInStackArgArea (unsigned bytes) inline
Definition at line 114 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64TargetLowering::LowerFormalArguments().
void llvm::AArch64MachineFunctionInfo::setFramePointerOffset (int Idx) inline
Definition at line 143 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64FrameLowering::emitPrologue().
void llvm::AArch64MachineFunctionInfo::setInitialStackAdjust (unsigned bytes) inline
Definition at line 122 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64FrameLowering::emitPrologue().
void llvm::AArch64MachineFunctionInfo::setVariadicFPRIdx (int Idx) inline
Definition at line 134 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64TargetLowering::SaveVarArgRegisters().
void llvm::AArch64MachineFunctionInfo::setVariadicFPRSize (unsigned Size) inline
Definition at line 137 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64TargetLowering::SaveVarArgRegisters().
void llvm::AArch64MachineFunctionInfo::setVariadicGPRIdx (int Idx) inline
Definition at line 128 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64TargetLowering::SaveVarArgRegisters().
void llvm::AArch64MachineFunctionInfo::setVariadicGPRSize (unsigned Size) inline
Definition at line 131 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64TargetLowering::SaveVarArgRegisters().
void llvm::AArch64MachineFunctionInfo::setVariadicStackIdx (int Idx) inline
Definition at line 140 of file AArch64MachineFunctionInfo.h.
Referenced by llvm::AArch64TargetLowering::SaveVarArgRegisters().
The documentation for this class was generated from the following files:
AArch64MachineFunctionInfo.h
AArch64MachineFunctionInfo.cpp