LLVM: llvm::XCoreMCInstLower Class Reference
LLVM API Documentation
llvm::XCoreMCInstLower Class Reference
This class is used to lower an MachineInstr into an MCInst.
#include <XCoreMCInstLower.h>
Public Member Functions
XCoreMCInstLower (class AsmPrinter &asmprinter)
void Initialize (Mangler *mang, MCContext *C)
void Lower (const MachineInstr *MI, MCInst &OutMI) const
MCOperand LowerOperand (const MachineOperand &MO, unsigned offset=0) const
Detailed Description
This class is used to lower an MachineInstr into an MCInst.
Definition at line 25 of file XCoreMCInstLower.h.
Constructor & Destructor Documentation
XCoreMCInstLower::XCoreMCInstLower (class AsmPrinter & asmprinter)
Definition at line 27 of file XCoreMCInstLower.cpp.
Member Function Documentation
void XCoreMCInstLower::Initialize (Mangler * mang, MCContext * C)
Definition at line 30 of file XCoreMCInstLower.cpp.
References llvm::MCConstantExpr::Create(), llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateAdd(), llvm::MCOperand::CreateExpr(), llvm::MachineOperand::getBlockAddress(), llvm::AsmPrinter::GetBlockAddressSymbol(), llvm::AsmPrinter::GetCPISymbol(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getIndex(), llvm::AsmPrinter::GetJTISymbol(), llvm::MachineOperand::getMBB(), llvm::MachineOperand::getOffset(), llvm::AsmPrinter::getSymbol(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getSymbolName(), llvm_unreachable, M, llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_JumpTableIndex, llvm::MachineOperand::MO_MachineBasicBlock, llvm::ARMBuildAttrs::Symbol, and llvm::MCSymbolRefExpr::VK_None.
void XCoreMCInstLower::Lower (const MachineInstr * MI, MCInst & OutMI) const
Definition at line 107 of file XCoreMCInstLower.cpp.
References llvm::MCInst::addOperand(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), i, llvm::MCOperand::isValid(), LowerOperand(), and llvm::MCInst::setOpcode().
MCOperand XCoreMCInstLower::LowerOperand (const MachineOperand & MO, unsigned offset = 0) const
Definition at line 81 of file XCoreMCInstLower.cpp.
References llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getType(), llvm::MachineOperand::isImplicit(), llvm_unreachable, llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_JumpTableIndex, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_Register, and llvm::MachineOperand::MO_RegisterMask.
Referenced by Lower().
The documentation for this class was generated from the following files:
XCoreMCInstLower.h
XCoreMCInstLower.cpp