LLVM: llvm::MachineLocation Class Reference
LLVM API Documentation
llvm::MachineLocation Class Reference
#include <MachineLocation.h>
Public Member Functions
enum LLVM_ENUM_INT_TYPE (uint32_t)
MachineLocation ()
MachineLocation (unsigned R)
Create a direct register location.
MachineLocation (unsigned R, int O)
Create a register-indirect location with an offset.
bool operator== (const MachineLocation &Other) const
bool isIndirect () const
bool isReg () const
unsigned getReg () const
int getOffset () const
void setIsRegister (bool Is)
void setRegister (unsigned R)
void setOffset (int O)
void set (unsigned R)
Make this location a direct register location.
void set (unsigned R, int O)
Make this location a register-indirect+offset location.
void dump ()
Detailed Description
Definition at line 25 of file MachineLocation.h.
Constructor & Destructor Documentation
llvm::MachineLocation::MachineLocation () inline
Definition at line 36 of file MachineLocation.h.
llvm::MachineLocation::MachineLocation (unsigned R) inline explicit
Create a direct register location.
Definition at line 39 of file MachineLocation.h.
llvm::MachineLocation::MachineLocation (unsigned R, int O) inline
Create a register-indirect location with an offset.
Definition at line 42 of file MachineLocation.h.
Member Function Documentation
void llvm::MachineLocation::dump ()
Referenced by set().
int llvm::MachineLocation::getOffset () const inline
Definition at line 55 of file MachineLocation.h.
Referenced by llvm::CompileUnit::addAddress(), llvm::CompileUnit::addBlockByrefAddress(), llvm::CompileUnit::addComplexAddress(), llvm::DwarfUnits::emitAddresses(), and llvm::AsmPrinter::EmitDwarfRegOp().
unsigned llvm::MachineLocation::getReg () const inline
Definition at line 54 of file MachineLocation.h.
Referenced by llvm::CompileUnit::addAddress(), llvm::CompileUnit::addBlockByrefAddress(), llvm::CompileUnit::addComplexAddress(), llvm::DwarfUnits::emitAddresses(), llvm::ARMAsmPrinter::EmitDwarfRegOp(), and llvm::AsmPrinter::EmitDwarfRegOp().
bool llvm::MachineLocation::isIndirect () const inline
Returns
true iff this is a register-indirect location.
Definition at line 52 of file MachineLocation.h.
Referenced by llvm::AsmPrinter::EmitDwarfRegOp().
bool llvm::MachineLocation::isReg () const inline
Definition at line 53 of file MachineLocation.h.
Referenced by llvm::CompileUnit::addAddress(), llvm::CompileUnit::addBlockByrefAddress(), llvm::CompileUnit::addComplexAddress(), llvm::DwarfUnits::emitAddresses(), and llvm::ARMAsmPrinter::EmitDwarfRegOp().
enum llvm::MachineLocation::LLVM_ENUM_INT_TYPE (uint32_t) inline
Definition at line 31 of file MachineLocation.h.
bool llvm::MachineLocation::operator== (const MachineLocation & Other) const inline
Definition at line 45 of file MachineLocation.h.
void llvm::MachineLocation::set (unsigned R) inline
Make this location a direct register location.
Definition at line 60 of file MachineLocation.h.
Referenced by getDebugLocEntry().
void llvm::MachineLocation::set (unsigned R, int O) inline
Make this location a register-indirect+offset location.
Definition at line 66 of file MachineLocation.h.
References dump().
void llvm::MachineLocation::setIsRegister (bool Is) inline
Definition at line 56 of file MachineLocation.h.
void llvm::MachineLocation::setOffset (int O) inline
Definition at line 58 of file MachineLocation.h.
void llvm::MachineLocation::setRegister (unsigned R) inline
Definition at line 57 of file MachineLocation.h.
The documentation for this class was generated from the following file:
MachineLocation.h