LLVM: llvm::DataStreamer Class Reference
LLVM API Documentation
llvm::DataStreamer Class Reference abstract
#include <DataStream.h>
Public Member Functions
virtual size_t GetBytes (unsigned char *buf, size_t len)=0
virtual ~DataStreamer ()
Detailed Description
Definition at line 24 of file DataStream.h.
Constructor & Destructor Documentation
llvm::DataStreamer::~DataStreamer () virtual
Definition at line 47 of file DataStream.cpp.
References llvm::sys::ChangeStdinToBinary(), GetBytes(), LLVM_OVERRIDE, llvm::sys::fs::openFileForRead(), llvm::LibFunc::read, and llvm::error_code::success().
Member Function Documentation
virtual size_t llvm::DataStreamer::GetBytes (unsigned char * buf, size_t len) pure virtual
Fetch bytes [start-end) from the stream, and write them to the buffer pointed to by buf. Returns the number of bytes actually written.
Referenced by llvm::sys::getHostCPUName(), llvm::StreamingMemoryObject::StreamingMemoryObject(), and ~DataStreamer().
The documentation for this class was generated from the following files:
DataStream.h
DataStream.cpp