LLVM: llvm::cl::generic_parser_base Class Reference
LLVM API Documentation
llvm::cl::generic_parser_base Class Reference abstract
#include <CommandLine.h>
Classes
class GenericOptionInfo
Public Member Functions
virtual ~generic_parser_base ()
virtual unsigned getNumOptions () const =0
virtual const char * getOption (unsigned N) const =0
virtual const char * getDescription (unsigned N) const =0
virtual size_t getOptionWidth (const Option &O) const
virtual const GenericOptionValue & getOptionValue (unsigned N) const =0
virtual void printOptionInfo (const Option &O, size_t GlobalWidth) const
void printGenericOptionDiff (const Option &O, const GenericOptionValue &V, const GenericOptionValue &Default, size_t GlobalWidth) const
template<class AnyOptionValue >
void printOptionDiff (const Option &O, const AnyOptionValue &V, const AnyOptionValue &Default, size_t GlobalWidth) const
void initialize (Option &O)
void getExtraOptionNames (SmallVectorImpl< const char * > &OptionNames)
enum ValueExpected getValueExpectedFlagDefault () const
unsigned findOption (const char *Name)
Protected Attributes
bool hasArgStr
Detailed Description
Definition at line 531 of file CommandLine.h.
Constructor & Destructor Documentation
virtual llvm::cl::generic_parser_base::~generic_parser_base () inline virtual
Definition at line 541 of file CommandLine.h.
References llvm::Reloc::Default, llvm::cl::OptionCategory::getDescription(), and N.
Member Function Documentation
unsigned generic_parser_base::findOption (const char * Name)
Definition at line 1235 of file CommandLine.cpp.
References i, and llvm::LibFunc::strcmp.
Referenced by llvm::PassNameParser::passRegistered().
virtual const char* llvm::cl::generic_parser_base::getDescription (unsigned N) const pure virtual
Implemented in llvm::cl::parser< DataType >, llvm::cl::parser< RegistryClass::FunctionPassCtor >, llvm::cl::parser< const U::entry * >, and llvm::cl::parser< const PassInfo * >.
void llvm::cl::generic_parser_base::getExtraOptionNames (SmallVectorImpl< const char * > & OptionNames) inline
Definition at line 586 of file CommandLine.h.
References i, and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
virtual unsigned llvm::cl::generic_parser_base::getNumOptions () const pure virtual
Implemented in llvm::cl::parser< DataType >, llvm::cl::parser< RegistryClass::FunctionPassCtor >, llvm::cl::parser< const U::entry * >, and llvm::cl::parser< const PassInfo * >.
virtual const char* llvm::cl::generic_parser_base::getOption (unsigned N) const pure virtual
Implemented in llvm::cl::parser< DataType >, llvm::cl::parser< RegistryClass::FunctionPassCtor >, llvm::cl::parser< const U::entry * >, and llvm::cl::parser< const PassInfo * >.
virtual const GenericOptionValue& llvm::cl::generic_parser_base::getOptionValue (unsigned N) const pure virtual
Implemented in llvm::cl::parser< DataType >, llvm::cl::parser< RegistryClass::FunctionPassCtor >, llvm::cl::parser< const U::entry * >, and llvm::cl::parser< const PassInfo * >.
size_t generic_parser_base::getOptionWidth (const Option & O) const virtual
Definition at line 1247 of file CommandLine.cpp.
References llvm::cl::Option::ArgStr, llvm::cl::Option::hasArgStr(), i, and llvm::LibFunc::strlen.
enum ValueExpected llvm::cl::generic_parser_base::getValueExpectedFlagDefault () const inline
Definition at line 596 of file CommandLine.h.
References llvm::cl::ValueDisallowed, and llvm::cl::ValueRequired.
void llvm::cl::generic_parser_base::initialize (Option & O) inline
Definition at line 579 of file CommandLine.h.
References llvm::cl::Option::hasArgStr().
Referenced by llvm::PassNameParser::initialize(), llvm::RegistryParser< T, U >::initialize(), and llvm::RegisterPassParser< RegistryClass >::initialize().
void generic_parser_base::printGenericOptionDiff (const Option & O, const GenericOptionValue & V, const GenericOptionValue & Default, size_t GlobalWidth) const
Definition at line 1292 of file CommandLine.cpp.
References llvm::cl::Option::ArgStr, llvm::cl::GenericOptionValue::compare(), i, llvm::raw_ostream::indent(), j(), llvm::outs(), and llvm::LibFunc::strlen.
template<class AnyOptionValue > void llvm::cl::generic_parser_base::printOptionDiff (const Option & O, const AnyOptionValue & V, const AnyOptionValue & Default, size_t GlobalWidth) const inline
Definition at line 573 of file CommandLine.h.
Referenced by llvm::cl::OptionDiffPrinter< DT, DT >::print(), and llvm::cl::printOptionDiff().
void generic_parser_base::printOptionInfo (const Option & O, size_t GlobalWidth) const virtual
Reimplemented in llvm::PassNameParser.
Definition at line 1264 of file CommandLine.cpp.
References llvm::cl::Option::ArgStr, llvm::cl::Option::hasArgStr(), llvm::cl::Option::HelpStr, i, llvm::raw_ostream::indent(), llvm::outs(), printHelpStr(), and llvm::LibFunc::strlen.
Referenced by llvm::PassNameParser::printOptionInfo().
Member Data Documentation
bool llvm::cl::generic_parser_base::hasArgStr protected
Definition at line 620 of file CommandLine.h.
The documentation for this class was generated from the following files:
CommandLine.h
CommandLine.cpp