LLVM: llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::iterator Class Reference
LLVM API Documentation
llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::iterator Class Reference
#include <ImmutableMap.h>
Public Member Functions
value_type_ref operator* () const
value_type * operator-> () const
key_type_ref getKey () const
data_type_ref getData () const
iterator & operator++ ()
iterator operator++ (int)
iterator & operator-- ()
iterator operator-- (int)
bool operator== (const iterator &RHS) const
bool operator!= (const iterator &RHS) const
Friends
class ImmutableMapRef
Detailed Description
template<typename KeyT, typename ValT, typename ValInfo = ImutKeyValueInfo<KeyT,ValT>>
class llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::iterator
Definition at line 380 of file ImmutableMap.h.
Member Function Documentation
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> data_type_ref llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::iterator::getData () const inline
Definition at line 392 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::getValue().
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> key_type_ref llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::iterator::getKey () const inline
Definition at line 391 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::getValue().
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> bool llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::iterator::operator!= (const iterator & RHS) const inline
Definition at line 400 of file ImmutableMap.h.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> value_type_ref llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::iterator::operator* () const inline
Definition at line 388 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::getValue().
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> iterator& llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::iterator::operator++ () inline
Definition at line 395 of file ImmutableMap.h.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> iterator llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::iterator::operator++ (int) inline
Definition at line 396 of file ImmutableMap.h.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> iterator& llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::iterator::operator-- () inline
Definition at line 397 of file ImmutableMap.h.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> iterator llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::iterator::operator-- (int) inline
Definition at line 398 of file ImmutableMap.h.
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> value_type* llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::iterator::operator-> () const inline
Definition at line 389 of file ImmutableMap.h.
References llvm::ImutAVLTree< ImutInfo >::getValue().
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> bool llvm::ImmutableMapRef< KeyT, ValT, ValInfo >::iterator::operator== (const iterator & RHS) const inline
Definition at line 399 of file ImmutableMap.h.
Friends And Related Function Documentation
template<typename KeyT , typename ValT , typename ValInfo = ImutKeyValueInfo<KeyT,ValT>> friend class ImmutableMapRef friend
Definition at line 385 of file ImmutableMap.h.
The documentation for this class was generated from the following file:
ImmutableMap.h