LLVM: llvm::yaml::Node Class Reference
LLVM API Documentation
llvm::yaml::Node Class Reference
Abstract base class for all Nodes.
#include <YAMLParser.h>
Public Types
enum NodeKind {
NK_Null, NK_Scalar, NK_KeyValue, NK_Mapping,
NK_Sequence, NK_Alias
}
Public Member Functions
Node (unsigned int Type, OwningPtr< Document > &, StringRef Anchor, StringRef Tag)
StringRef getAnchor () const
Get the value of the anchor attached to this node. If it does not have one, getAnchor().size() will be 0.
StringRef getRawTag () const
Get the tag as it was written in the document. This does not perform tag resolution.
std::string getVerbatimTag () const
Get the verbatium tag for a given Node. This performs tag resoluton and substitution.
SMRange getSourceRange () const
void setSourceRange (SMRange SR)
Token & peekNext ()
Token getNext ()
Node * parseBlockNode ()
BumpPtrAllocator & getAllocator ()
void setError (const Twine &Message, Token &Location) const
bool failed () const
virtual void skip ()
unsigned int getType () const
void * operator new (size_t Size, BumpPtrAllocator &Alloc, size_t Alignment=16) throw ()
void operator delete (void *Ptr, BumpPtrAllocator &Alloc, size_t) throw ()
Protected Member Functions
void operator delete (void *) throw ()
virtual ~Node ()
Protected Attributes
OwningPtr< Document > & Doc
SMRange SourceRange
Detailed Description
Abstract base class for all Nodes.
Definition at line 107 of file YAMLParser.h.
Member Enumeration Documentation
enum llvm::yaml::Node::NodeKind
Enumerator
NK_Null
NK_Scalar
NK_KeyValue
NK_Mapping
NK_Sequence
NK_Alias
Definition at line 110 of file YAMLParser.h.
Constructor & Destructor Documentation
Node::Node (unsigned int Type, OwningPtr< Document > & D, StringRef Anchor, StringRef Tag)
Definition at line 1604 of file YAMLParser.cpp.
References llvm::SMLoc::getFromPointer(), peekNext(), and SourceRange.
virtual llvm::yaml::Node::~Node () inline protected virtual
Definition at line 165 of file YAMLParser.h.
Member Function Documentation
bool Node::failed () const
Definition at line 1677 of file YAMLParser.cpp.
References Doc.
Referenced by llvm::yaml::KeyValueNode::getValue(), and llvm::yaml::SequenceNode::increment().
BumpPtrAllocator & Node::getAllocator ()
Definition at line 1669 of file YAMLParser.cpp.
References Doc.
Referenced by llvm::yaml::KeyValueNode::getKey(), and llvm::yaml::KeyValueNode::getValue().
StringRef llvm::yaml::Node::getAnchor () const inline
Get the value of the anchor attached to this node. If it does not have one, getAnchor().size() will be 0.
Definition at line 124 of file YAMLParser.h.
Token Node::getNext ()
Definition at line 1661 of file YAMLParser.cpp.
References Doc.
Referenced by llvm::yaml::KeyValueNode::getKey(), llvm::yaml::KeyValueNode::getValue(), and llvm::yaml::SequenceNode::increment().
StringRef llvm::yaml::Node::getRawTag () const inline
Get the tag as it was written in the document. This does not perform tag resolution.
Definition at line 128 of file YAMLParser.h.
Referenced by getVerbatimTag().
SMRange llvm::yaml::Node::getSourceRange () const inline
Definition at line 134 of file YAMLParser.h.
Referenced by llvm::yaml::Stream::printError().
unsigned int llvm::yaml::Node::getType () const inline
Definition at line 147 of file YAMLParser.h.
Referenced by llvm::yaml::NullNode::classof(), llvm::yaml::ScalarNode::classof(), llvm::yaml::KeyValueNode::classof(), llvm::yaml::MappingNode::classof(), llvm::yaml::SequenceNode::classof(), llvm::yaml::AliasNode::classof(), and getVerbatimTag().
std::string Node::getVerbatimTag () const
Get the verbatium tag for a given Node. This performs tag resoluton and substitution.
Definition at line 1613 of file YAMLParser.cpp.
References Doc, llvm::StringRef::empty(), llvm::StringRef::find_last_of(), getRawTag(), getType(), llvm_move, NK_Mapping, NK_Null, NK_Scalar, NK_Sequence, llvm::AArch64ISD::Ret, setError(), llvm::StringRef::startswith(), llvm::StringRef::substr(), T, and llvm::yaml::Token::TK_Tag.
void llvm::yaml::Node::operator delete (void * Ptr, BumpPtrAllocator & Alloc, size_t) throw () inline
Definition at line 155 of file YAMLParser.h.
void llvm::yaml::Node::operator delete (void *) throw () inline protected
Definition at line 163 of file YAMLParser.h.
void* llvm::yaml::Node::operator new (size_t Size, BumpPtrAllocator & Alloc, size_t Alignment = 16) throw () inline
Definition at line 149 of file YAMLParser.h.
Node * Node::parseBlockNode ()
Definition at line 1665 of file YAMLParser.cpp.
References Doc.
Referenced by llvm::yaml::KeyValueNode::getKey(), llvm::yaml::KeyValueNode::getValue(), and llvm::yaml::SequenceNode::increment().
Token & Node::peekNext ()
Definition at line 1657 of file YAMLParser.cpp.
References Doc.
Referenced by llvm::yaml::KeyValueNode::getKey(), llvm::yaml::KeyValueNode::getValue(), llvm::yaml::SequenceNode::increment(), and Node().
void Node::setError (const Twine & Message, Token & Location) const
Definition at line 1673 of file YAMLParser.cpp.
References Doc.
Referenced by llvm::yaml::ScalarNode::getValue(), llvm::yaml::KeyValueNode::getValue(), getVerbatimTag(), and llvm::yaml::SequenceNode::increment().
void llvm::yaml::Node::setSourceRange (SMRange SR) inline
Definition at line 135 of file YAMLParser.h.
References llvm::yaml::Stream::failed().
virtual void llvm::yaml::Node::skip () inline virtual
Reimplemented in llvm::yaml::SequenceNode, llvm::yaml::MappingNode, and llvm::yaml::KeyValueNode.
Definition at line 145 of file YAMLParser.h.
Referenced by llvm::yaml::KeyValueNode::skip(), and llvm::yaml::Document::skip().
Member Data Documentation
OwningPtr<Document>& llvm::yaml::Node::Doc protected
Definition at line 160 of file YAMLParser.h.
Referenced by failed(), getAllocator(), llvm::yaml::KeyValueNode::getKey(), getNext(), llvm::yaml::KeyValueNode::getValue(), getVerbatimTag(), parseBlockNode(), peekNext(), and setError().
SMRange llvm::yaml::Node::SourceRange protected
Definition at line 161 of file YAMLParser.h.
Referenced by Node().
The documentation for this class was generated from the following files:
YAMLParser.h
YAMLParser.cpp