LLVM: llvm::SystemZConstantPoolValue Class Reference
LLVM API Documentation
llvm::SystemZConstantPoolValue Class Reference
#include <SystemZConstantPoolValue.h>
Public Member Functions
virtual unsigned getRelocationInfo () const LLVM_OVERRIDE
virtual int getExistingMachineCPValue (MachineConstantPool *CP, unsigned Alignment) LLVM_OVERRIDE
virtual void addSelectionDAGCSEId (FoldingSetNodeID &ID) LLVM_OVERRIDE
virtual void print (raw_ostream &O) const LLVM_OVERRIDE
print - Implement operator<<
const GlobalValue * getGlobalValue () const
SystemZCP::SystemZCPModifier getModifier () const
Public Member Functions inherited from llvm::MachineConstantPoolValue
MachineConstantPoolValue (Type *ty)
virtual ~MachineConstantPoolValue ()
Type * getType () const
Static Public Member Functions
static SystemZConstantPoolValue * Create (const GlobalValue *GV, SystemZCP::SystemZCPModifier Modifier)
Protected Member Functions
SystemZConstantPoolValue (const GlobalValue *GV, SystemZCP::SystemZCPModifier Modifier)
Detailed Description
A SystemZ-specific constant pool value. At present, the only defined constant pool values are offsets of thread-local variables (written x).
Definition at line 29 of file SystemZConstantPoolValue.h.
Constructor & Destructor Documentation
SystemZConstantPoolValue::SystemZConstantPoolValue (const GlobalValue * GV, SystemZCP::SystemZCPModifier Modifier) protected
Definition at line 19 of file SystemZConstantPoolValue.cpp.
Referenced by Create().
Member Function Documentation
void SystemZConstantPoolValue::addSelectionDAGCSEId (FoldingSetNodeID & ID) virtual
Implements llvm::MachineConstantPoolValue.
Definition at line 55 of file SystemZConstantPoolValue.cpp.
References llvm::FoldingSetNodeID::AddInteger(), and llvm::FoldingSetNodeID::AddPointer().
SystemZConstantPoolValue * SystemZConstantPoolValue::Create (const GlobalValue * GV, SystemZCP::SystemZCPModifier Modifier) static
Definition at line 24 of file SystemZConstantPoolValue.cpp.
References SystemZConstantPoolValue().
Referenced by lowerGR128Binary().
int SystemZConstantPoolValue::getExistingMachineCPValue (MachineConstantPool * CP, unsigned Alignment) virtual
Implements llvm::MachineConstantPoolValue.
Definition at line 40 of file SystemZConstantPoolValue.cpp.
References llvm::MachineConstantPool::getConstants(), and I.
Referenced by getRelocationInfo().
const GlobalValue* llvm::SystemZConstantPoolValue::getGlobalValue () const inline
Definition at line 49 of file SystemZConstantPoolValue.h.
Referenced by llvm::SystemZAsmPrinter::EmitMachineConstantPoolValue().
SystemZCP::SystemZCPModifier llvm::SystemZConstantPoolValue::getModifier () const inline
Definition at line 50 of file SystemZConstantPoolValue.h.
Referenced by llvm::SystemZAsmPrinter::EmitMachineConstantPoolValue().
unsigned SystemZConstantPoolValue::getRelocationInfo () const virtual
getRelocationInfo - This method classifies the entry according to whether or not it may generate a relocation entry. This must be conservative, so if it might codegen to a relocatable entry, it should say so. The return values are the same as Constant::getRelocationInfo().
Implements llvm::MachineConstantPoolValue.
Definition at line 29 of file SystemZConstantPoolValue.cpp.
References getExistingMachineCPValue(), llvm_unreachable, and llvm::SystemZCP::NTPOFF.
void SystemZConstantPoolValue::print (raw_ostream & O) const virtual
print - Implement operator<<
Implements llvm::MachineConstantPoolValue.
Definition at line 60 of file SystemZConstantPoolValue.cpp.
References int.
The documentation for this class was generated from the following files:
SystemZConstantPoolValue.h
SystemZConstantPoolValue.cpp