LLVM: llvm::TargetLoweringObjectFileELF Class Reference
LLVM API Documentation
llvm::TargetLoweringObjectFileELF Class Reference
#include <TargetLoweringObjectFileImpl.h>
Public Member Functions
virtual ~TargetLoweringObjectFileELF ()
virtual void emitPersonalityValue (MCStreamer &Streamer, const TargetMachine &TM, const MCSymbol *Sym) const
virtual const MCSection * getSectionForConstant (SectionKind Kind) const
virtual const MCSection * getExplicitSectionGlobal (const GlobalValue *GV, SectionKind Kind, Mangler *Mang, const TargetMachine &TM) const
virtual const MCSection * SelectSectionForGlobal (const GlobalValue *GV, SectionKind Kind, Mangler *Mang, const TargetMachine &TM) const
virtual const MCExpr * getTTypeGlobalReference (const GlobalValue *GV, Mangler *Mang, MachineModuleInfo *MMI, unsigned Encoding, MCStreamer &Streamer) const
virtual MCSymbol * getCFIPersonalitySymbol (const GlobalValue *GV, Mangler *Mang, MachineModuleInfo *MMI) const
void InitializeELF (bool UseInitArray_)
virtual const MCSection * getStaticCtorSection (unsigned Priority=65535) const
virtual const MCSection * getStaticDtorSection (unsigned Priority=65535) const
Public Member Functions inherited from llvm::TargetLoweringObjectFile
MCContext & getContext () const
TargetLoweringObjectFile ()
virtual ~TargetLoweringObjectFile ()
virtual void Initialize (MCContext &ctx, const TargetMachine &TM)
virtual void emitModuleFlags (MCStreamer &, ArrayRef< Module::ModuleFlagEntry >, Mangler *, const TargetMachine &) const
emitModuleFlags - Emit the module flags that the platform cares about.
virtual bool shouldEmitUsedDirectiveFor (const GlobalValue *GV, Mangler *) const
const MCSection * SectionForGlobal (const GlobalValue *GV, SectionKind Kind, Mangler *Mang, const TargetMachine &TM) const
const MCSection * SectionForGlobal (const GlobalValue *GV, Mangler *Mang, const TargetMachine &TM) const
virtual const MCSection * getSpecialCasedSectionGlobals (const GlobalValue *GV, Mangler *Mang, SectionKind Kind) const
MCSymbol * getSymbol (Mangler &M, const GlobalValue *GV) const
const MCExpr * getTTypeReference (const MCSymbolRefExpr *Sym, unsigned Encoding, MCStreamer &Streamer) const
virtual const MCExpr * getDebugThreadLocalSymbol (const MCSymbol *Sym) const
Create a symbol reference to describe the given TLS variable when emitting the address in debug info.
Public Member Functions inherited from llvm::MCObjectFileInfo
void InitMCObjectFileInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, MCContext &ctx)
bool isFunctionEHFrameSymbolPrivate () const
bool getSupportsWeakOmittedEHFrame () const
bool getCommDirectiveSupportsAlignment () const
unsigned getPersonalityEncoding () const
unsigned getLSDAEncoding () const
unsigned getFDEEncoding (bool CFI) const
unsigned getTTypeEncoding () const
unsigned getCompactUnwindDwarfEHFrameOnly () const
const MCSection * getTextSection () const
const MCSection * getDataSection () const
const MCSection * getBSSSection () const
const MCSection * getLSDASection () const
const MCSection * getCompactUnwindSection () const
const MCSection * getDwarfAbbrevSection () const
const MCSection * getDwarfInfoSection () const
const MCSection * getDwarfLineSection () const
const MCSection * getDwarfFrameSection () const
const MCSection * getDwarfPubNamesSection () const
const MCSection * getDwarfPubTypesSection () const
const MCSection * getDwarfGnuPubNamesSection () const
const MCSection * getDwarfGnuPubTypesSection () const
const MCSection * getDwarfDebugInlineSection () const
const MCSection * getDwarfStrSection () const
const MCSection * getDwarfLocSection () const
const MCSection * getDwarfARangesSection () const
const MCSection * getDwarfRangesSection () const
const MCSection * getDwarfMacroInfoSection () const
const MCSection * getDwarfAccelNamesSection () const
const MCSection * getDwarfAccelObjCSection () const
const MCSection * getDwarfAccelNamespaceSection () const
const MCSection * getDwarfAccelTypesSection () const
const MCSection * getDwarfInfoDWOSection () const
const MCSection * getDwarfAbbrevDWOSection () const
const MCSection * getDwarfStrDWOSection () const
const MCSection * getDwarfLineDWOSection () const
const MCSection * getDwarfLocDWOSection () const
const MCSection * getDwarfStrOffDWOSection () const
const MCSection * getDwarfAddrSection () const
const MCSection * getTLSExtraDataSection () const
const MCSection * getTLSDataSection () const
const MCSection * getTLSBSSSection () const
const MCSection * getStackMapSection () const
const MCSection * getDataRelSection () const
const MCSection * getDataRelLocalSection () const
const MCSection * getDataRelROSection () const
const MCSection * getDataRelROLocalSection () const
const MCSection * getMergeableConst4Section () const
const MCSection * getMergeableConst8Section () const
const MCSection * getMergeableConst16Section () const
const MCSection * getTLSTLVSection () const
const MCSection * getTLSThreadInitSection () const
const MCSection * getCStringSection () const
const MCSection * getUStringSection () const
const MCSection * getTextCoalSection () const
const MCSection * getConstTextCoalSection () const
const MCSection * getConstDataSection () const
const MCSection * getDataCoalSection () const
const MCSection * getDataCommonSection () const
const MCSection * getDataBSSSection () const
const MCSection * getFourByteConstantSection () const
const MCSection * getEightByteConstantSection () const
const MCSection * getSixteenByteConstantSection () const
const MCSection * getLazySymbolPointerSection () const
const MCSection * getNonLazySymbolPointerSection () const
const MCSection * getDrectveSection () const
const MCSection * getPDataSection () const
const MCSection * getXDataSection () const
const MCSection * getEHFrameSection ()
Additional Inherited Members
Static Public Member Functions inherited from llvm::TargetLoweringObjectFile
static SectionKind getKindForGlobal (const GlobalValue *GV, const TargetMachine &TM)
Protected Attributes inherited from llvm::MCObjectFileInfo
bool CommDirectiveSupportsAlignment
bool SupportsWeakOmittedEHFrame
bool IsFunctionEHFrameSymbolPrivate
unsigned PersonalityEncoding
unsigned LSDAEncoding
unsigned FDEEncoding
unsigned FDECFIEncoding
unsigned TTypeEncoding
unsigned EHSectionType
Section flags for eh_frame.
unsigned EHSectionFlags
unsigned CompactUnwindDwarfEHFrameOnly
const MCSection * TextSection
const MCSection * DataSection
const MCSection * BSSSection
BSSSection - Section that is default initialized to zero.
const MCSection * ReadOnlySection
const MCSection * StaticCtorSection
const MCSection * StaticDtorSection
const MCSection * LSDASection
const MCSection * CompactUnwindSection
const MCSection * DwarfAbbrevSection
const MCSection * DwarfInfoSection
const MCSection * DwarfLineSection
const MCSection * DwarfFrameSection
const MCSection * DwarfPubTypesSection
const MCSection * DwarfDebugInlineSection
const MCSection * DwarfStrSection
const MCSection * DwarfLocSection
const MCSection * DwarfARangesSection
const MCSection * DwarfRangesSection
const MCSection * DwarfMacroInfoSection
const MCSection * DwarfPubNamesSection
const MCSection * DwarfAccelNamesSection
const MCSection * DwarfAccelObjCSection
const MCSection * DwarfAccelNamespaceSection
const MCSection * DwarfAccelTypesSection
const MCSection * DwarfInfoDWOSection
These are used for the Fission separate debug information files.
const MCSection * DwarfAbbrevDWOSection
const MCSection * DwarfStrDWOSection
const MCSection * DwarfLineDWOSection
const MCSection * DwarfLocDWOSection
const MCSection * DwarfStrOffDWOSection
const MCSection * DwarfAddrSection
const MCSection * DwarfGnuPubNamesSection
Sections for newer gnu pubnames and pubtypes.
const MCSection * DwarfGnuPubTypesSection
const MCSection * TLSExtraDataSection
const MCSection * TLSDataSection
const MCSection * TLSBSSSection
const MCSection * StackMapSection
StackMap section.
const MCSection * EHFrameSection
const MCSection * DataRelSection
const MCSection * DataRelLocalSection
const MCSection * DataRelROSection
const MCSection * DataRelROLocalSection
const MCSection * MergeableConst4Section
const MCSection * MergeableConst8Section
const MCSection * MergeableConst16Section
const MCSection * TLSTLVSection
const MCSection * TLSThreadInitSection
const MCSection * CStringSection
const MCSection * UStringSection
const MCSection * TextCoalSection
const MCSection * ConstTextCoalSection
const MCSection * ConstDataSection
const MCSection * DataCoalSection
const MCSection * DataCommonSection
const MCSection * DataBSSSection
const MCSection * FourByteConstantSection
const MCSection * EightByteConstantSection
const MCSection * SixteenByteConstantSection
const MCSection * LazySymbolPointerSection
const MCSection * NonLazySymbolPointerSection
const MCSection * DrectveSection
const MCSection * PDataSection
const MCSection * XDataSection
Detailed Description
Definition at line 35 of file TargetLoweringObjectFileImpl.h.
Constructor & Destructor Documentation
virtual llvm::TargetLoweringObjectFileELF::~TargetLoweringObjectFileELF () inline virtual
Definition at line 39 of file TargetLoweringObjectFileImpl.h.
References emitPersonalityValue(), getCFIPersonalitySymbol(), getExplicitSectionGlobal(), getSectionForConstant(), getStaticCtorSection(), getStaticDtorSection(), getTTypeGlobalReference(), InitializeELF(), SelectSectionForGlobal(), and llvm::SystemZISD::TM.
Member Function Documentation
void TargetLoweringObjectFileELF::emitPersonalityValue (MCStreamer & Streamer, const TargetMachine & TM, const MCSymbol * Sym) const virtual
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 63 of file TargetLoweringObjectFileImpl.cpp.
References llvm::StringRef::begin(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::MCConstantExpr::Create(), llvm::MCStreamer::EmitELFSize(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitSymbolAttribute(), llvm::MCStreamer::EmitSymbolValue(), llvm::MCStreamer::EmitValueToAlignment(), llvm::StringRef::end(), llvm::TargetMachine::getDataLayout(), llvm::SectionKind::getDataRel(), llvm::MCSymbol::getName(), llvm::DataLayout::getPointerABIAlignment(), llvm::DataLayout::getPointerSize(), getTTypeGlobalReference(), llvm::SmallVectorImpl< char >::insert(), llvm::MCSA_ELF_TypeObject, llvm::MCSA_Hidden, llvm::MCSA_Weak, llvm::cl::Prefix, and llvm::MCStreamer::SwitchSection().
Referenced by ~TargetLoweringObjectFileELF().
MCSymbol * TargetLoweringObjectFileELF::getCFIPersonalitySymbol (const GlobalValue * GV, Mangler * Mang, MachineModuleInfo * MMI) const virtual
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 47 of file TargetLoweringObjectFileImpl.cpp.
References llvm::dwarf::DW_EH_PE_absptr, llvm::dwarf::DW_EH_PE_pcrel, llvm::Intrinsic::getName(), and llvm::report_fatal_error().
Referenced by ~TargetLoweringObjectFileELF(), and llvm::TargetLoweringObjectFileMachO::~TargetLoweringObjectFileMachO().
const MCSection * TargetLoweringObjectFileELF::getExplicitSectionGlobal (const GlobalValue * GV, SectionKind Kind, Mangler * Mang, const TargetMachine & TM) const virtual
getExplicitSectionGlobal - Targets should implement this method to assign a section to globals with an explicit section specfied. The implementation of this method can assume that GV->hasSection() is true.
Implements llvm::TargetLoweringObjectFile.
Definition at line 204 of file TargetLoweringObjectFileImpl.cpp.
References getELFKindForNamedSection(), getELFSectionFlags(), getELFSectionType(), and llvm::GlobalValue::getSection().
Referenced by getELFSectionFlags(), llvm::TargetLoweringObjectFileCOFF::~TargetLoweringObjectFileCOFF(), ~TargetLoweringObjectFileELF(), and llvm::TargetLoweringObjectFileMachO::~TargetLoweringObjectFileMachO().
const MCSection * TargetLoweringObjectFileELF::getSectionForConstant (SectionKind Kind) const virtual
getSectionForConstant - Given a constant with the SectionKind, return a section that it should be placed in.
getSectionForConstant - Given a mergeable constant with the specified size and relocation information, return a section that it should be placed in.
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 331 of file TargetLoweringObjectFileImpl.cpp.
References llvm::SectionKind::isMergeableConst16(), llvm::SectionKind::isMergeableConst4(), llvm::SectionKind::isMergeableConst8(), llvm::SectionKind::isReadOnly(), llvm::SectionKind::isReadOnlyWithRel(), and llvm::SectionKind::isReadOnlyWithRelLocal().
Referenced by SelectSectionForGlobal(), ~TargetLoweringObjectFileELF(), and llvm::TargetLoweringObjectFileMachO::~TargetLoweringObjectFileMachO().
const MCSection * TargetLoweringObjectFileELF::getStaticCtorSection (unsigned Priority = 65535) const virtual
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 347 of file TargetLoweringObjectFileImpl.cpp.
References llvm::SectionKind::getDataRel(), UseInitArray(), and llvm::utostr().
Referenced by ~TargetLoweringObjectFileELF().
const MCSection * TargetLoweringObjectFileELF::getStaticDtorSection (unsigned Priority = 65535) const virtual
Reimplemented from llvm::TargetLoweringObjectFile.
Definition at line 367 of file TargetLoweringObjectFileImpl.cpp.
References llvm::SectionKind::getDataRel(), UseInitArray(), and llvm::utostr().
Referenced by ~TargetLoweringObjectFileELF().
const MCExpr * TargetLoweringObjectFileELF::getTTypeGlobalReference (const GlobalValue * GV, Mangler * Mang, MachineModuleInfo * MMI, unsigned Encoding, MCStreamer & Streamer) const virtual
getTTypeGlobalReference - Return an MCExpr to use for a reference to the specified type info global variable from exception handling information.
Reimplemented from llvm::TargetLoweringObjectFile.
Reimplemented in llvm::ARMElfTargetObjectFile.
Definition at line 91 of file TargetLoweringObjectFileImpl.cpp.
References llvm::MCSymbolRefExpr::Create(), llvm::dwarf::DW_EH_PE_indirect, llvm::MachineModuleInfoELF::getGVStubEntry(), llvm::Mangler::getNameWithPrefix(), llvm::MachineModuleInfo::getObjFileInfo(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer(), llvm::TargetLoweringObjectFile::getTTypeGlobalReference(), llvm::TargetLoweringObjectFile::getTTypeReference(), and llvm::GlobalValue::hasLocalLinkage().
Referenced by emitPersonalityValue(), ~TargetLoweringObjectFileELF(), and llvm::TargetLoweringObjectFileMachO::~TargetLoweringObjectFileMachO().
void TargetLoweringObjectFileELF::InitializeELF (bool UseInitArray_)
Definition at line 387 of file TargetLoweringObjectFileImpl.cpp.
References llvm::TargetLoweringObjectFileMachO::emitModuleFlags(), llvm::SectionKind::getDataRel(), and UseInitArray().
Referenced by llvm::MipsTargetObjectFile::Initialize(), and ~TargetLoweringObjectFileELF().
const MCSection * TargetLoweringObjectFileELF::SelectSectionForGlobal (const GlobalValue * GV, SectionKind Kind, Mangler * Mang, const TargetMachine & TM) const virtual
Reimplemented from llvm::TargetLoweringObjectFile.
Reimplemented in llvm::HexagonTargetObjectFile, and llvm::MipsTargetObjectFile.
Definition at line 237 of file TargetLoweringObjectFileImpl.cpp.
References Align, llvm::SmallString< InternalLen >::append(), llvm::StringRef::begin(), llvm::StringRef::end(), llvm::TargetMachine::getDataLayout(), llvm::TargetMachine::getDataSections(), getELFSectionFlags(), getELFSectionType(), llvm::TargetMachine::getFunctionSections(), llvm::MCSymbol::getName(), llvm::DataLayout::getPreferredAlignment(), getSectionForConstant(), getSectionPrefixForGlobal(), llvm::SectionKind::isBSS(), llvm::SectionKind::isCommon(), llvm::SectionKind::isDataNoRel(), llvm::SectionKind::isDataRel(), llvm::SectionKind::isDataRelLocal(), llvm::SectionKind::isMergeable1ByteCString(), llvm::SectionKind::isMergeable2ByteCString(), llvm::SectionKind::isMergeable4ByteCString(), llvm::SectionKind::isMergeableConst(), llvm::SectionKind::isMergeableConst16(), llvm::SectionKind::isMergeableConst4(), llvm::SectionKind::isMergeableConst8(), llvm::SectionKind::isReadOnly(), llvm::SectionKind::isReadOnlyWithRel(), llvm::SectionKind::isReadOnlyWithRelLocal(), llvm::SectionKind::isText(), llvm::SectionKind::isThreadBSS(), llvm::SectionKind::isThreadData(), llvm::GlobalValue::isWeakForLinker(), llvm::cl::Prefix, llvm::SmallString< InternalLen >::str(), llvm::LibFunc::strlen, and llvm::utostr().
Referenced by getSectionPrefixForGlobal(), llvm::MipsTargetObjectFile::SelectSectionForGlobal(), llvm::HexagonTargetObjectFile::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileCOFF::~TargetLoweringObjectFileCOFF(), ~TargetLoweringObjectFileELF(), and llvm::TargetLoweringObjectFileMachO::~TargetLoweringObjectFileMachO().
The documentation for this class was generated from the following files:
TargetLoweringObjectFileImpl.h
TargetLoweringObjectFileImpl.cpp