LLVM: llvm::GCOVFunction Class Reference
LLVM API Documentation
llvm::GCOVFunction Class Reference
GCOVFunction - Collects function information.
#include <GCOV.h>
Public Member Functions
GCOVFunction ()
~GCOVFunction ()
~GCOVFunction - Delete GCOVFunction and its content.
bool read (GCOVBuffer &Buffer, GCOV::GCOVFormat Format)
StringRef getFilename () const
void dump ()
dump - Dump GCOVFunction content to dbgs() for debugging purposes.
void collectLineCounts (FileInfo &FI)
Detailed Description
GCOVFunction - Collects function information.
Definition at line 208 of file GCOV.h.
Constructor & Destructor Documentation
llvm::GCOVFunction::GCOVFunction () inline
Definition at line 210 of file GCOV.h.
References llvm::LibFunc::read.
GCOVFunction::~GCOVFunction ()
~GCOVFunction - Delete GCOVFunction and its content.
Definition at line 107 of file GCOV.cpp.
References llvm::DeleteContainerPointers().
Member Function Documentation
void GCOVFunction::collectLineCounts (FileInfo & FI)
collectLineCounts - Collect line counts. This must be used after reading .gcno and .gcda files.
Definition at line 233 of file GCOV.cpp.
References I.
void GCOVFunction::dump ()
dump - Dump GCOVFunction content to dbgs() for debugging purposes.
Definition at line 224 of file GCOV.cpp.
References llvm::dbgs(), and I.
StringRef llvm::GCOVFunction::getFilename () const inline
Definition at line 213 of file GCOV.h.
References llvm::dump().
bool GCOVFunction::read (GCOVBuffer & Buff, GCOV::GCOVFormat Format)
read - Read a function from the buffer. Return false if buffer cursor does not point to a function tag.
Definition at line 113 of file GCOV.cpp.
References llvm::GCOVBlock::addCount(), llvm::GCOVBlock::addLine(), llvm::NVPTXISD::Dummy, llvm::errs(), F(), llvm::GCOV::GCDA_402, llvm::GCOV::GCDA_404, llvm::GCOV::GCNO_402, llvm::GCOV::GCNO_404, llvm::GCOVBuffer::getCursor(), llvm::GCOVBlock::getNumEdges(), i, llvm::GCOVBuffer::readArcTag(), llvm::GCOVBuffer::readBlockTag(), llvm::GCOVBuffer::readEdgeTag(), llvm::GCOVBuffer::readInt(), llvm::GCOVBuffer::readInt64(), llvm::GCOVBuffer::readLineTag(), and llvm::GCOVBuffer::readString().
Referenced by llvm::GCOVFile::read().
The documentation for this class was generated from the following files:
GCOV.h
GCOV.cpp