LLVM: llvm::SmallBitVector::reference Class Reference
LLVM API Documentation
llvm::SmallBitVector::reference Class Reference
#include <SmallBitVector.h>
Public Member Functions
reference (SmallBitVector &b, unsigned Idx)
reference & operator= (reference t)
reference & operator= (bool t)
operator bool () const
Detailed Description
Definition at line 58 of file SmallBitVector.h.
Constructor & Destructor Documentation
llvm::SmallBitVector::reference::reference (SmallBitVector & b, unsigned Idx) inline
Definition at line 63 of file SmallBitVector.h.
Referenced by llvm::SmallBitVector::operator[]().
Member Function Documentation
llvm::SmallBitVector::reference::operator bool () const inline
Definition at line 78 of file SmallBitVector.h.
reference& llvm::SmallBitVector::reference::operator= (reference t) inline
Definition at line 65 of file SmallBitVector.h.
Referenced by llvm::SmallBitVector::operator=().
reference& llvm::SmallBitVector::reference::operator= (bool t) inline
Definition at line 70 of file SmallBitVector.h.
References llvm::SmallBitVector::reset(), and llvm::SmallBitVector::set().
The documentation for this class was generated from the following file:
SmallBitVector.h