LLVM: llvm::MSP430InstPrinter Class Reference
LLVM API Documentation
llvm::MSP430InstPrinter Class Reference
#include <MSP430InstPrinter.h>
Public Member Functions
MSP430InstPrinter (const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI)
virtual void printInst (const MCInst *MI, raw_ostream &O, StringRef Annot)
void printInstruction (const MCInst *MI, raw_ostream &O)
void printOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O, const char *Modifier=0)
void printPCRelImmOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
void printSrcMemOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O, const char *Modifier=0)
void printCCOperand (const MCInst *MI, unsigned OpNo, raw_ostream &O)
Public Member Functions inherited from llvm::MCInstPrinter
MCInstPrinter (const MCAsmInfo &mai, const MCInstrInfo &mii, const MCRegisterInfo &mri)
virtual ~MCInstPrinter ()
void setCommentStream (raw_ostream &OS)
setCommentStream - Specify a stream to emit comments to.
StringRef getOpcodeName (unsigned Opcode) const
virtual void printRegName (raw_ostream &OS, unsigned RegNo) const
printRegName - Print the assembler register name.
uint64_t getAvailableFeatures () const
void setAvailableFeatures (uint64_t Value)
bool getUseMarkup () const
void setUseMarkup (bool Value)
StringRef markup (StringRef s) const
Utility functions to make adding mark ups simpler.
StringRef markup (StringRef a, StringRef b) const
bool getPrintImmHex () const
void setPrintImmHex (bool Value)
HexStyle::Style getPrintHexStyleHex () const
void setPrintImmHex (HexStyle::Style Value)
format_object1< int64_t > formatImm (const int64_t Value) const
Utility function to print immediates in decimal or hex.
format_object1< int64_t > formatDec (const int64_t Value) const
Utility functions to print decimal/hexadecimal values.
format_object1< int64_t > formatHex (const int64_t Value) const
format_object1< uint64_t > formatHex (const uint64_t Value) const
Static Public Member Functions
static const char * getRegisterName (unsigned RegNo)
Additional Inherited Members
Protected Member Functions inherited from llvm::MCInstPrinter
void printAnnotation (raw_ostream &OS, StringRef Annot)
Utility function for printing annotations.
Protected Attributes inherited from llvm::MCInstPrinter
raw_ostream * CommentStream
const MCAsmInfo & MAI
const MCInstrInfo & MII
const MCRegisterInfo & MRI
uint64_t AvailableFeatures
The current set of available features.
bool UseMarkup
True if we are printing marked up assembly.
bool PrintImmHex
True if we are printing immediates as hex.
HexStyle::Style PrintHexStyle
Which style to use for printing hexadecimal values.
Detailed Description
Definition at line 22 of file MSP430InstPrinter.h.
Constructor & Destructor Documentation
llvm::MSP430InstPrinter::MSP430InstPrinter (const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI) inline
Definition at line 24 of file MSP430InstPrinter.h.
References getRegisterName(), llvm::A64CC::MI, printCCOperand(), printInst(), printInstruction(), printOperand(), printPCRelImmOperand(), and printSrcMemOperand().
Member Function Documentation
static const char* llvm::MSP430InstPrinter::getRegisterName (unsigned RegNo) static
Referenced by MSP430InstPrinter(), printOperand(), and printSrcMemOperand().
void MSP430InstPrinter::printCCOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 88 of file MSP430InstPrinter.cpp.
References CC, MSP430CC::COND_E, MSP430CC::COND_GE, MSP430CC::COND_HS, MSP430CC::COND_L, MSP430CC::COND_LO, MSP430CC::COND_NE, llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), and llvm_unreachable.
Referenced by MSP430InstPrinter().
void MSP430InstPrinter::printInst (const MCInst * MI, raw_ostream & OS, StringRef Annot) virtual
printInst - Print the specified MCInst to the specified raw_ostream.
Implements llvm::MCInstPrinter.
Definition at line 28 of file MSP430InstPrinter.cpp.
References llvm::MCInstPrinter::printAnnotation(), and printInstruction().
Referenced by MSP430InstPrinter().
void llvm::MSP430InstPrinter::printInstruction (const MCInst * MI, raw_ostream & O)
Referenced by MSP430InstPrinter(), and printInst().
void MSP430InstPrinter::printOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O, const char * Modifier = 0)
Definition at line 45 of file MSP430InstPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), and llvm::MCOperand::isReg().
Referenced by MSP430InstPrinter().
void MSP430InstPrinter::printPCRelImmOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O)
Definition at line 34 of file MSP430InstPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isExpr(), and llvm::MCOperand::isImm().
Referenced by MSP430InstPrinter().
void MSP430InstPrinter::printSrcMemOperand (const MCInst * MI, unsigned OpNo, raw_ostream & O, const char * Modifier = 0)
Definition at line 59 of file MSP430InstPrinter.cpp.
References llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRegisterName(), llvm::MCOperand::isExpr(), and llvm::MCOperand::isImm().
Referenced by MSP430InstPrinter().
The documentation for this class was generated from the following files:
MSP430InstPrinter.h
MSP430InstPrinter.cpp