LLVM: llvm::DenseMap< KeyT, ValueT, KeyInfoT > Class Template Reference
LLVM API Documentation
llvm::DenseMap< KeyT, ValueT, KeyInfoT > Class Template Reference
#include <DenseMap.h>
Inherits llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >.
Public Member Functions
DenseMap (unsigned NumInitBuckets=0)
DenseMap (const DenseMap &other)
template<typename InputIt >
DenseMap (const InputIt &I, const InputIt &E)
~DenseMap ()
void swap (DenseMap &RHS)
DenseMap & operator= (const DenseMap &other)
void copyFrom (const DenseMap &other)
void init (unsigned InitBuckets)
void grow (unsigned AtLeast)
void shrink_and_clear ()
Public Member Functions inherited from llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
bool LLVM_ATTRIBUTE_UNUSED_RESULT empty () const
unsigned size () const
void resize (size_t Size)
Grow the densemap so that it has at least Size buckets. Does not shrink.
void clear ()
bool count (const KeyT &Val) const
count - Return true if the specified key is in the map.
iterator find (const KeyT &Val)
const_iterator find (const KeyT &Val) const
iterator find_as (const LookupKeyT &Val)
const_iterator find_as (const LookupKeyT &Val) const
ValueT lookup (const KeyT &Val) const
std::pair< iterator, bool > insert (const std::pair< KeyT, ValueT > &KV)
void insert (InputIt I, InputIt E)
insert - Range insertion of pairs.
bool erase (const KeyT &Val)
void erase (iterator I)
value_type & FindAndConstruct (const KeyT &Key)
ValueT & operator[] (const KeyT &Key)
bool isPointerIntoBucketsArray (const void *Ptr) const
const void * getPointerIntoBucketsArray () const
size_t getMemorySize () const
Friends
class DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT >
Additional Inherited Members
Public Types inherited from llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >
typedef KeyT key_type
typedef ValueT mapped_type
typedef BucketT value_type
typedef DenseMapIterator< KeyT, ValueT, KeyInfoT > iterator
typedef DenseMapIterator< KeyT, ValueT, KeyInfoT, true > const_iterator
Protected Types inherited from llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >
typedef std::pair< KeyT, ValueT > BucketT
Protected Member Functions inherited from llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >
DenseMapBase ()
void destroyAll ()
void initEmpty ()
void moveFromOldBuckets (BucketT *OldBucketsBegin, BucketT *OldBucketsEnd)
void copyFrom (const DenseMapBase< OtherBaseT, KeyT, ValueT, KeyInfoT > &other)
void swap (DenseMapBase &RHS)
Static Protected Member Functions inherited from llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >
static unsigned getHashValue (const KeyT &Val)
static unsigned getHashValue (const LookupKeyT &Val)
static const KeyT getEmptyKey ()
static const KeyT getTombstoneKey ()
Detailed Description
template<typename KeyT, typename ValueT, typename KeyInfoT = DenseMapInfo<KeyT>>
class llvm::DenseMap< KeyT, ValueT, KeyInfoT >
Definition at line 534 of file DenseMap.h.
Constructor & Destructor Documentation
template<typename KeyT, typename ValueT, typename KeyInfoT = DenseMapInfo<KeyT>> llvm::DenseMap< KeyT, ValueT, KeyInfoT >::DenseMap (unsigned NumInitBuckets = 0) inline explicit
Definition at line 549 of file DenseMap.h.
template<typename KeyT, typename ValueT, typename KeyInfoT = DenseMapInfo<KeyT>> llvm::DenseMap< KeyT, ValueT, KeyInfoT >::DenseMap (const DenseMap< KeyT, ValueT, KeyInfoT > & other) inline
Definition at line 553 of file DenseMap.h.
template<typename KeyT, typename ValueT, typename KeyInfoT = DenseMapInfo<KeyT>> template<typename InputIt > llvm::DenseMap< KeyT, ValueT, KeyInfoT >::DenseMap (const InputIt & I, const InputIt & E) inline
Definition at line 566 of file DenseMap.h.
template<typename KeyT, typename ValueT, typename KeyInfoT = DenseMapInfo<KeyT>> llvm::DenseMap< KeyT, ValueT, KeyInfoT >::~DenseMap () inline
Definition at line 571 of file DenseMap.h.
Member Function Documentation
template<typename KeyT, typename ValueT, typename KeyInfoT = DenseMapInfo<KeyT>> void llvm::DenseMap< KeyT, ValueT, KeyInfoT >::copyFrom (const DenseMap< KeyT, ValueT, KeyInfoT > & other) inline
Definition at line 598 of file DenseMap.h.
template<typename KeyT, typename ValueT, typename KeyInfoT = DenseMapInfo<KeyT>> void llvm::DenseMap< KeyT, ValueT, KeyInfoT >::grow (unsigned AtLeast) inline
Definition at line 618 of file DenseMap.h.
Referenced by llvm::FunctionLoweringInfo::InvalidatePHILiveOutRegInfo().
template<typename KeyT, typename ValueT, typename KeyInfoT = DenseMapInfo<KeyT>> void llvm::DenseMap< KeyT, ValueT, KeyInfoT >::init (unsigned InitBuckets) inline
Definition at line 609 of file DenseMap.h.
template<typename KeyT, typename ValueT, typename KeyInfoT = DenseMapInfo<KeyT>> DenseMap& llvm::DenseMap< KeyT, ValueT, KeyInfoT >::operator= (const DenseMap< KeyT, ValueT, KeyInfoT > & other) inline
Definition at line 583 of file DenseMap.h.
template<typename KeyT, typename ValueT, typename KeyInfoT = DenseMapInfo<KeyT>> void llvm::DenseMap< KeyT, ValueT, KeyInfoT >::shrink_and_clear () inline
Definition at line 635 of file DenseMap.h.
template<typename KeyT, typename ValueT, typename KeyInfoT = DenseMapInfo<KeyT>> void llvm::DenseMap< KeyT, ValueT, KeyInfoT >::swap (DenseMap< KeyT, ValueT, KeyInfoT > & RHS) inline
Definition at line 576 of file DenseMap.h.
Referenced by EvaluateExpression(), and llvm::DenseSet< llvm::Value * >::swap().
Friends And Related Function Documentation
template<typename KeyT, typename ValueT, typename KeyInfoT = DenseMapInfo<KeyT>> friend class DenseMapBase< DenseMap, KeyT, ValueT, KeyInfoT > friend
Definition at line 541 of file DenseMap.h.
The documentation for this class was generated from the following file:
DenseMap.h