LLVM: llvm::RecTy Class Reference
LLVM API Documentation
llvm::RecTy Class Reference abstract
#include <Record.h>
Public Types
enum RecTyKind {
BitRecTyKind, BitsRecTyKind, IntRecTyKind, StringRecTyKind,
ListRecTyKind, DagRecTyKind, RecordRecTyKind
}
Subclass discriminator (for dyn_cast<> et al.)
Public Member Functions
RecTyKind getRecTyKind () const
RecTy (RecTyKind K)
virtual ~RecTy ()
virtual std::string getAsString () const =0
void print (raw_ostream &OS) const
void dump () const
virtual bool typeIsConvertibleTo (const RecTy *RHS) const =0
ListRecTy * getListTy ()
getListTy - Returns the type representing list<this>.
virtual Init * convertValue (UnsetInit *UI)
virtual Init * convertValue (BitInit *BI)
virtual Init * convertValue (BitsInit *BI)
virtual Init * convertValue (IntInit *II)
virtual Init * convertValue (StringInit *SI)
virtual Init * convertValue (ListInit *LI)
virtual Init * convertValue (UnOpInit *UI)
virtual Init * convertValue (BinOpInit *UI)
virtual Init * convertValue (TernOpInit *UI)
virtual Init * convertValue (VarBitInit *VB)
virtual Init * convertValue (DefInit *DI)
virtual Init * convertValue (DagInit *DI)
virtual Init * convertValue (TypedInit *TI)
virtual Init * convertValue (VarInit *VI)
virtual Init * convertValue (FieldInit *FI)
virtual bool baseClassOf (const RecTy *) const
Detailed Description
Definition at line 69 of file Record.h.
Member Enumeration Documentation
enum llvm::RecTy::RecTyKind
Subclass discriminator (for dyn_cast<> et al.)
Enumerator
BitRecTyKind
BitsRecTyKind
IntRecTyKind
StringRecTyKind
ListRecTyKind
DagRecTyKind
RecordRecTyKind
Definition at line 72 of file Record.h.
Constructor & Destructor Documentation
llvm::RecTy::RecTy (RecTyKind K) inline
Definition at line 90 of file Record.h.
virtual llvm::RecTy::~RecTy () inline virtual
Definition at line 91 of file Record.h.
References getAsString().
Member Function Documentation
bool RecTy::baseClassOf (const RecTy * RHS) const virtual
Reimplemented in llvm::RecordRecTy, llvm::ListRecTy, llvm::IntRecTy, llvm::BitsRecTy, and llvm::BitRecTy.
Definition at line 98 of file Record.cpp.
References getRecTyKind().
Referenced by llvm::BitRecTy::baseClassOf(), llvm::BitsRecTy::baseClassOf(), convertValue(), llvm::BitRecTy::typeIsConvertibleTo(), llvm::BitsRecTy::typeIsConvertibleTo(), llvm::IntRecTy::typeIsConvertibleTo(), llvm::StringRecTy::typeIsConvertibleTo(), llvm::ListRecTy::typeIsConvertibleTo(), llvm::DagRecTy::typeIsConvertibleTo(), and llvm::RecordRecTy::typeIsConvertibleTo().
virtual Init* llvm::RecTy::convertValue (UnsetInit * UI) inline virtual
Reimplemented in llvm::RecordRecTy, llvm::DagRecTy, llvm::ListRecTy, llvm::StringRecTy, llvm::IntRecTy, llvm::BitsRecTy, and llvm::BitRecTy.
Definition at line 105 of file Record.h.
Referenced by llvm::UnsetInit::convertInitializerTo(), llvm::BitInit::convertInitializerTo(), llvm::BitsInit::convertInitializerTo(), llvm::IntInit::convertInitializerTo(), llvm::StringInit::convertInitializerTo(), llvm::ListInit::convertInitializerTo(), llvm::OpInit::convertInitializerTo(), llvm::VarInit::convertInitializerTo(), llvm::VarBitInit::convertInitializerTo(), llvm::VarListElementInit::convertInitializerTo(), llvm::DefInit::convertInitializerTo(), llvm::FieldInit::convertInitializerTo(), llvm::DagInit::convertInitializerTo(), convertValue(), llvm::BitRecTy::convertValue(), llvm::BitsRecTy::convertValue(), llvm::IntRecTy::convertValue(), llvm::StringRecTy::convertValue(), llvm::ListRecTy::convertValue(), llvm::DagRecTy::convertValue(), llvm::RecordRecTy::convertValue(), llvm::BitsRecTy::getNumBits(), and llvm::RecordVal::RecordVal().
virtual Init* llvm::RecTy::convertValue (BitInit * BI) inline virtual
Reimplemented in llvm::RecordRecTy, llvm::DagRecTy, llvm::ListRecTy, llvm::StringRecTy, llvm::IntRecTy, llvm::BitsRecTy, and llvm::BitRecTy.
Definition at line 106 of file Record.h.
virtual Init* llvm::RecTy::convertValue (BitsInit * BI) inline virtual
Reimplemented in llvm::RecordRecTy, llvm::DagRecTy, llvm::ListRecTy, llvm::StringRecTy, llvm::IntRecTy, llvm::BitsRecTy, and llvm::BitRecTy.
Definition at line 107 of file Record.h.
virtual Init* llvm::RecTy::convertValue (IntInit * II) inline virtual
Reimplemented in llvm::RecordRecTy, llvm::DagRecTy, llvm::ListRecTy, llvm::StringRecTy, llvm::IntRecTy, llvm::BitsRecTy, and llvm::BitRecTy.
Definition at line 108 of file Record.h.
virtual Init* llvm::RecTy::convertValue (StringInit * SI) inline virtual
Reimplemented in llvm::RecordRecTy, llvm::DagRecTy, llvm::ListRecTy, llvm::StringRecTy, llvm::IntRecTy, llvm::BitsRecTy, and llvm::BitRecTy.
Definition at line 109 of file Record.h.
virtual Init* llvm::RecTy::convertValue (ListInit * LI) inline virtual
Reimplemented in llvm::RecordRecTy, llvm::DagRecTy, llvm::ListRecTy, llvm::StringRecTy, llvm::IntRecTy, llvm::BitsRecTy, and llvm::BitRecTy.
Definition at line 110 of file Record.h.
virtual Init* llvm::RecTy::convertValue (UnOpInit * UI) inline virtual
Reimplemented in llvm::RecordRecTy, llvm::DagRecTy, llvm::ListRecTy, llvm::StringRecTy, llvm::IntRecTy, llvm::BitsRecTy, and llvm::BitRecTy.
Definition at line 111 of file Record.h.
References convertValue().
virtual Init* llvm::RecTy::convertValue (BinOpInit * UI) inline virtual
Reimplemented in llvm::RecordRecTy, llvm::DagRecTy, llvm::ListRecTy, llvm::StringRecTy, llvm::IntRecTy, llvm::BitsRecTy, and llvm::BitRecTy.
Definition at line 114 of file Record.h.
References convertValue().
virtual Init* llvm::RecTy::convertValue (TernOpInit * UI) inline virtual
Reimplemented in llvm::RecordRecTy, llvm::DagRecTy, llvm::ListRecTy, llvm::StringRecTy, llvm::IntRecTy, llvm::BitsRecTy, and llvm::BitRecTy.
Definition at line 117 of file Record.h.
References convertValue().
virtual Init* llvm::RecTy::convertValue (VarBitInit * VB) inline virtual
Reimplemented in llvm::RecordRecTy, llvm::DagRecTy, llvm::ListRecTy, llvm::StringRecTy, llvm::IntRecTy, llvm::BitsRecTy, and llvm::BitRecTy.
Definition at line 120 of file Record.h.
virtual Init* llvm::RecTy::convertValue (DefInit * DI) inline virtual
Reimplemented in llvm::RecordRecTy, llvm::DagRecTy, llvm::ListRecTy, llvm::StringRecTy, llvm::IntRecTy, llvm::BitsRecTy, and llvm::BitRecTy.
Definition at line 121 of file Record.h.
virtual Init* llvm::RecTy::convertValue (DagInit * DI) inline virtual
Reimplemented in llvm::RecordRecTy, llvm::DagRecTy, llvm::ListRecTy, llvm::StringRecTy, llvm::IntRecTy, llvm::BitsRecTy, and llvm::BitRecTy.
Definition at line 122 of file Record.h.
virtual Init* llvm::RecTy::convertValue (TypedInit * TI) inline virtual
Reimplemented in llvm::RecordRecTy, llvm::DagRecTy, llvm::ListRecTy, llvm::StringRecTy, llvm::IntRecTy, llvm::BitsRecTy, and llvm::BitRecTy.
Definition at line 123 of file Record.h.
virtual Init* llvm::RecTy::convertValue (VarInit * VI) inline virtual
Reimplemented in llvm::RecordRecTy, llvm::DagRecTy, llvm::ListRecTy, llvm::StringRecTy, llvm::IntRecTy, llvm::BitsRecTy, and llvm::BitRecTy.
Definition at line 124 of file Record.h.
References convertValue().
virtual Init* llvm::RecTy::convertValue (FieldInit * FI) inline virtual
Reimplemented in llvm::RecordRecTy, llvm::DagRecTy, llvm::ListRecTy, llvm::StringRecTy, llvm::IntRecTy, llvm::BitsRecTy, and llvm::BitRecTy.
Definition at line 127 of file Record.h.
References baseClassOf(), and convertValue().
void RecTy::dump () const
Definition at line 90 of file Record.cpp.
References llvm::errs().
Referenced by llvm::Init::getAsUnquotedString(), llvm::Record::isAnonymous(), print(), llvm::RecordKeeper::removeDef(), and llvm::RecordVal::setValue().
virtual std::string llvm::RecTy::getAsString () const pure virtual
Implemented in llvm::RecordRecTy, llvm::DagRecTy, llvm::ListRecTy, llvm::StringRecTy, llvm::IntRecTy, llvm::BitsRecTy, and llvm::BitRecTy.
Referenced by llvm::BitsInit::allInComplete(), llvm::IntInit::convertInitializerTo(), llvm::ListInit::convertInitializerTo(), llvm::BitsRecTy::convertValue(), llvm::ListRecTy::convertValue(), llvm::RecordRecTy::convertValue(), llvm::SubMultiClassReference::dump(), EvaluateOperation(), llvm::DagInit::getArgName(), llvm::Init::getAsUnquotedString(), llvm::VarBitInit::getBitNum(), llvm::DefInit::getDef(), llvm::VarListElementInit::getElementNum(), GetNewAnonymousName(), llvm::UnOpInit::getOperand(), llvm::BinOpInit::getRHS(), llvm::TernOpInit::isComplete(), print(), llvm::Init::print(), and ~RecTy().
ListRecTy * RecTy::getListTy ()
getListTy - Returns the type representing list<this>.
Definition at line 92 of file Record.cpp.
Referenced by llvm::ListRecTy::get(), and print().
RecTyKind llvm::RecTy::getRecTyKind () const inline
Definition at line 88 of file Record.h.
Referenced by baseClassOf(), llvm::BitsRecTy::baseClassOf(), llvm::IntRecTy::baseClassOf(), llvm::BitRecTy::classof(), llvm::BitsRecTy::classof(), llvm::IntRecTy::classof(), llvm::StringRecTy::classof(), llvm::ListRecTy::classof(), llvm::DagRecTy::classof(), and llvm::RecordRecTy::classof().
void llvm::RecTy::print (raw_ostream & OS) const inline
Definition at line 94 of file Record.h.
References dump(), getAsString(), getListTy(), and typeIsConvertibleTo().
Referenced by llvm::operator<<(), and llvm::RecordVal::setValue().
virtual bool llvm::RecTy::typeIsConvertibleTo (const RecTy * RHS) const pure virtual
typeIsConvertibleTo - Return true if all values of 'this' type can be converted to the specified type.
Implemented in llvm::RecordRecTy, llvm::DagRecTy, llvm::ListRecTy, llvm::StringRecTy, llvm::IntRecTy, llvm::BitsRecTy, and llvm::BitRecTy.
Referenced by llvm::BitsRecTy::convertValue(), llvm::IntRecTy::convertValue(), llvm::DagRecTy::convertValue(), GetNewAnonymousName(), print(), and llvm::resolveTypes().
The documentation for this class was generated from the following files:
Record.h
Record.cpp