LLVM: llvm::SystemZInstrInfo Class Reference
LLVM API Documentation
llvm::SystemZInstrInfo Class Reference
#include <SystemZInstrInfo.h>
Public Member Functions
SystemZInstrInfo (SystemZTargetMachine &TM)
virtual unsigned isLoadFromStackSlot (const MachineInstr *MI, int &FrameIndex) const LLVM_OVERRIDE
virtual unsigned isStoreToStackSlot (const MachineInstr *MI, int &FrameIndex) const LLVM_OVERRIDE
virtual bool isStackSlotCopy (const MachineInstr *MI, int &DestFrameIndex, int &SrcFrameIndex) const LLVM_OVERRIDE
virtual bool AnalyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify) const LLVM_OVERRIDE
virtual unsigned RemoveBranch (MachineBasicBlock &MBB) const LLVM_OVERRIDE
virtual unsigned InsertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, const SmallVectorImpl< MachineOperand > &Cond, DebugLoc DL) const LLVM_OVERRIDE
bool analyzeCompare (const MachineInstr *MI, unsigned &SrcReg, unsigned &SrcReg2, int &Mask, int &Value) const LLVM_OVERRIDE
bool optimizeCompareInstr (MachineInstr *CmpInstr, unsigned SrcReg, unsigned SrcReg2, int Mask, int Value, const MachineRegisterInfo *MRI) const LLVM_OVERRIDE
virtual bool isPredicable (MachineInstr *MI) const LLVM_OVERRIDE
virtual bool isProfitableToIfCvt (MachineBasicBlock &MBB, unsigned NumCycles, unsigned ExtraPredCycles, const BranchProbability &Probability) const LLVM_OVERRIDE
virtual bool isProfitableToIfCvt (MachineBasicBlock &TMBB, unsigned NumCyclesT, unsigned ExtraPredCyclesT, MachineBasicBlock &FMBB, unsigned NumCyclesF, unsigned ExtraPredCyclesF, const BranchProbability &Probability) const LLVM_OVERRIDE
virtual bool PredicateInstruction (MachineInstr *MI, const SmallVectorImpl< MachineOperand > &Pred) const LLVM_OVERRIDE
virtual void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const LLVM_OVERRIDE
virtual void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const LLVM_OVERRIDE
virtual void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIdx, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const LLVM_OVERRIDE
virtual MachineInstr * convertToThreeAddress (MachineFunction::iterator &MFI, MachineBasicBlock::iterator &MBBI, LiveVariables *LV) const
virtual MachineInstr * foldMemoryOperandImpl (MachineFunction &MF, MachineInstr *MI, const SmallVectorImpl< unsigned > &Ops, int FrameIndex) const
virtual MachineInstr * foldMemoryOperandImpl (MachineFunction &MF, MachineInstr *MI, const SmallVectorImpl< unsigned > &Ops, MachineInstr *LoadMI) const
virtual bool expandPostRAPseudo (MachineBasicBlock::iterator MBBI) const LLVM_OVERRIDE
virtual bool ReverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const LLVM_OVERRIDE
const SystemZRegisterInfo & getRegisterInfo () const
uint64_t getInstSizeInBytes (const MachineInstr *MI) const
SystemZII::Branch getBranchInfo (const MachineInstr *MI) const
void getLoadStoreOpcodes (const TargetRegisterClass *RC, unsigned &LoadOpcode, unsigned &StoreOpcode) const
unsigned getOpcodeForOffset (unsigned Opcode, int64_t Offset) const
unsigned getLoadAndTest (unsigned Opcode) const
bool isRxSBGMask (uint64_t Mask, unsigned BitSize, unsigned &Start, unsigned &End) const
unsigned getCompareAndBranch (unsigned Opcode, const MachineInstr *MI=0) const
void loadImmediate (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned Reg, uint64_t Value) const
Detailed Description
Definition at line 113 of file SystemZInstrInfo.h.
Constructor & Destructor Documentation
SystemZInstrInfo::SystemZInstrInfo (SystemZTargetMachine & TM) explicit
Definition at line 43 of file SystemZInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::SystemZMC::CallFrameSize, llvm::MachineFunction::CloneMachineInstr(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFrameInfo(), llvm::MachineOperand::getImm(), llvm::getKillRegState(), llvm::MachineFrameInfo::getMaxCallFrameSize(), getOpcodeForOffset(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineBasicBlock::insert(), isHighReg(), llvm::MachineOperand::isKill(), llvm::A64CC::MI, llvm::MachineInstr::setDesc(), llvm::MachineOperand::setImm(), llvm::MachineOperand::setReg(), and llvm::RegState::Undef.
Member Function Documentation
bool SystemZInstrInfo::AnalyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify) const virtual
Definition at line 241 of file SystemZInstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MCID::Branch, llvm::SystemZII::BranchNormal, llvm::SystemZII::Branch::CCMask, llvm::SystemZ::CCMASK_ANY, llvm::SystemZII::Branch::CCValid, llvm::SmallVectorImpl< T >::clear(), llvm::MachineOperand::CreateImm(), llvm::SmallVectorBase::empty(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::eraseFromParent(), getBranchInfo(), llvm::MachineOperand::getMBB(), I, llvm::MachineBasicBlock::isLayoutSuccessor(), llvm::MachineOperand::isMBB(), llvm::next(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::SystemZII::Branch::Target, and llvm::SystemZII::Branch::Type.
bool SystemZInstrInfo::analyzeCompare (const MachineInstr * MI, unsigned & SrcReg, unsigned & SrcReg2, int & Mask, int & Value) const
Definition at line 399 of file SystemZInstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumExplicitOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineInstr::isCompare(), llvm::MachineOperand::isImm(), and llvm::MachineOperand::isReg().
MachineInstr * SystemZInstrInfo::convertToThreeAddress (MachineFunction::iterator & MFI, MachineBasicBlock::iterator & MBBI, LiveVariables * LV) const virtual
Definition at line 674 of file SystemZInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addOperand(), llvm::MachineInstrBuilder::addReg(), allOnes(), llvm::APIntOps::And(), llvm::BuildMI(), llvm::MachineRegisterInfo::constrainRegClass(), llvm::TargetRegisterClass::contains(), finishConvertToThreeAddress(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::getKillRegState(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::MachineOperand::getSubReg(), I, interpretAndImmediate(), llvm::MachineOperand::isKill(), isRxSBGMask(), llvm::TargetRegisterInfo::isVirtualRegister(), and MRI.
void SystemZInstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const virtual
Definition at line 553 of file SystemZInstrInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::getKillRegState(), llvm::MipsISD::LDR, and llvm_unreachable.
bool SystemZInstrInfo::expandPostRAPseudo (MachineBasicBlock::iterator MBBI) const virtual
Definition at line 872 of file SystemZInstrInfo.cpp.
References llvm::HexagonISD::ADJDYNALLOC, CFI, isHighReg(), llvm::A64DB::LD, and llvm::A64DB::ST.
MachineInstr * SystemZInstrInfo::foldMemoryOperandImpl (MachineFunction & MF, MachineInstr * MI, const SmallVectorImpl< unsigned > & Ops, int FrameIndex) const virtual
Definition at line 747 of file SystemZInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::SystemZII::getAccessSize(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFrameInfo(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumExplicitOperands(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::MachineMemOperand::getSize(), llvm::SystemZII::HasIndex, llvm::MachineInstr::hasOneMemOperand(), I, llvm::isInt< 8 >(), isSimpleBD12Move(), llvm::MachineMemOperand::isVolatile(), llvm::A64DB::LD, llvm::MachineInstr::memoperands_begin(), MVC, llvm::SystemZII::SimpleBDXLoad, llvm::SystemZII::SimpleBDXStore, llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::MCInstrDesc::TSFlags.
MachineInstr * SystemZInstrInfo::foldMemoryOperandImpl (MachineFunction & MF, MachineInstr * MI, const SmallVectorImpl< unsigned > & Ops, MachineInstr * LoadMI) const virtual
Definition at line 865 of file SystemZInstrInfo.cpp.
SystemZII::Branch SystemZInstrInfo::getBranchInfo (const MachineInstr * MI) const
Definition at line 1041 of file SystemZInstrInfo.cpp.
References llvm::ISD::BR, llvm::MCID::Branch, llvm::SystemZII::BranchC, llvm::SystemZII::BranchCG, llvm::SystemZII::BranchCL, llvm::SystemZII::BranchCLG, llvm::SystemZII::BranchCT, llvm::SystemZII::BranchCTG, llvm::SystemZII::BranchNormal, llvm::SystemZ::CCMASK_ANY, llvm::SystemZ::CCMASK_CMP_NE, llvm::SystemZ::CCMASK_ICMP, llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), and llvm_unreachable.
Referenced by AnalyzeBranch(), and RemoveBranch().
unsigned SystemZInstrInfo::getCompareAndBranch (unsigned Opcode, const MachineInstr * MI = 0) const
Definition at line 1206 of file SystemZInstrInfo.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), llvm::isInt< 8 >(), and llvm::isUInt< 8 >().
uint64_t SystemZInstrInfo::getInstSizeInBytes (const MachineInstr * MI) const
Definition at line 1031 of file SystemZInstrInfo.cpp.
References llvm::MachineInstr::getDesc(), llvm::TargetMachine::getMCAsmInfo(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MCInstrDesc::getSize(), llvm::MachineOperand::getSymbolName(), llvm::MachineFunction::getTarget(), and llvm::TargetOpcode::INLINEASM.
unsigned SystemZInstrInfo::getLoadAndTest (unsigned Opcode) const
Definition at line 1148 of file SystemZInstrInfo.cpp.
References llvm::MipsISD::LDR, and llvm::A64CC::LT.
void SystemZInstrInfo::getLoadStoreOpcodes (const TargetRegisterClass * RC, unsigned & LoadOpcode, unsigned & StoreOpcode) const
Definition at line 1088 of file SystemZInstrInfo.cpp.
References llvm::A64DB::LD, llvm::A64CC::LE, llvm_unreachable, and llvm::A64DB::ST.
Referenced by loadRegFromStackSlot(), and storeRegToStackSlot().
unsigned SystemZInstrInfo::getOpcodeForOffset (unsigned Opcode, int64_t Offset) const
Definition at line 1121 of file SystemZInstrInfo.cpp.
References llvm::SystemZII::Has20BitOffset, llvm::SystemZII::Is128Bit, and llvm::MCInstrDesc::TSFlags.
Referenced by llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::SystemZFrameLowering::emitEpilogue(), forceReg(), and SystemZInstrInfo().
const SystemZRegisterInfo& llvm::SystemZInstrInfo::getRegisterInfo () const inline
Definition at line 210 of file SystemZInstrInfo.h.
Referenced by llvm::SystemZTargetMachine::getRegisterInfo().
unsigned SystemZInstrInfo::InsertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, const SmallVectorImpl< MachineOperand > & Cond, DebugLoc DL) const virtual
Definition at line 363 of file SystemZInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::BuildMI(), llvm::SmallVectorBase::empty(), and llvm::SmallVectorTemplateCommon< T >::size().
unsigned SystemZInstrInfo::isLoadFromStackSlot (const MachineInstr * MI, int & FrameIndex) const virtual
Definition at line 206 of file SystemZInstrInfo.cpp.
References isSimpleMove(), and llvm::SystemZII::SimpleBDXLoad.
bool SystemZInstrInfo::isPredicable (MachineInstr * MI) const virtual
Definition at line 506 of file SystemZInstrInfo.cpp.
References getConditionalMove(), llvm::MachineInstr::getOpcode(), llvm::SystemZTargetMachine::getSubtargetImpl(), llvm::SystemZSubtarget::hasLoadStoreOnCond(), and isProfitableToIfCvt().
bool SystemZInstrInfo::isProfitableToIfCvt (MachineBasicBlock & MBB, unsigned NumCycles, unsigned ExtraPredCycles, const BranchProbability & Probability) const virtual
Definition at line 515 of file SystemZInstrInfo.cpp.
Referenced by isPredicable().
bool SystemZInstrInfo::isProfitableToIfCvt (MachineBasicBlock & TMBB, unsigned NumCyclesT, unsigned ExtraPredCyclesT, MachineBasicBlock & FMBB, unsigned NumCyclesF, unsigned ExtraPredCyclesF, const BranchProbability & Probability) const virtual
Definition at line 523 of file SystemZInstrInfo.cpp.
References PredicateInstruction().
bool SystemZInstrInfo::isRxSBGMask (uint64_t Mask, unsigned BitSize, unsigned & Start, unsigned & End) const
Definition at line 1178 of file SystemZInstrInfo.cpp.
References allOnes(), and isStringOfOnes().
Referenced by convertToThreeAddress(), and insertDAGNode().
bool SystemZInstrInfo::isStackSlotCopy (const MachineInstr * MI, int & DestFrameIndex, int & SrcFrameIndex) const virtual
Definition at line 216 of file SystemZInstrInfo.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::isFI(), and MVC.
unsigned SystemZInstrInfo::isStoreToStackSlot (const MachineInstr * MI, int & FrameIndex) const virtual
Definition at line 211 of file SystemZInstrInfo.cpp.
References isSimpleMove(), and llvm::SystemZII::SimpleBDXStore.
void SystemZInstrInfo::loadImmediate (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned Reg, uint64_t Value) const
Definition at line 1230 of file SystemZInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::SystemZ::isImmLH(), llvm::SystemZ::isImmLL(), llvm::isInt< 16 >(), and llvm::isInt< 32 >().
Referenced by llvm::SystemZRegisterInfo::eliminateFrameIndex().
void SystemZInstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIdx, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const virtual
Definition at line 606 of file SystemZInstrInfo.cpp.
References llvm::addFrameReference(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), and getLoadStoreOpcodes().
bool SystemZInstrInfo::optimizeCompareInstr (MachineInstr * CmpInstr, unsigned SrcReg, unsigned SrcReg2, int Mask, int Value, const MachineRegisterInfo * MRI) const
Definition at line 483 of file SystemZInstrInfo.cpp.
References llvm::MachineInstr::getDesc(), llvm::SystemZTargetMachine::getRegisterInfo(), llvm::SystemZII::IsLogical, removeIPMBasedCompare(), and llvm::MCInstrDesc::TSFlags.
bool SystemZInstrInfo::PredicateInstruction (MachineInstr * MI, const SmallVectorImpl< MachineOperand > & Pred) const virtual
Definition at line 533 of file SystemZInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), CC, getConditionalMove(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::SystemZTargetMachine::getSubtargetImpl(), llvm::SystemZSubtarget::hasLoadStoreOnCond(), llvm::RegState::Implicit, llvm::A64CC::MI, llvm::MachineInstr::setDesc(), and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by isProfitableToIfCvt().
unsigned SystemZInstrInfo::RemoveBranch (MachineBasicBlock & MBB) const virtual
Definition at line 333 of file SystemZInstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), getBranchInfo(), I, llvm::MachineOperand::isMBB(), ReverseBranchCondition(), and llvm::SystemZII::Branch::Target.
bool SystemZInstrInfo::ReverseBranchCondition (SmallVectorImpl< MachineOperand > & Cond) const virtual
Definition at line 356 of file SystemZInstrInfo.cpp.
References llvm::SmallVectorTemplateCommon< T >::size().
Referenced by RemoveBranch().
void SystemZInstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const virtual
Definition at line 589 of file SystemZInstrInfo.cpp.
References llvm::addFrameReference(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::getKillRegState(), and getLoadStoreOpcodes().
The documentation for this class was generated from the following files:
SystemZInstrInfo.h
SystemZInstrInfo.cpp