LLVM: llvm::DebugLoc Class Reference
LLVM API Documentation
llvm::DebugLoc Class Reference
#include <DebugLoc.h>
Public Member Functions
DebugLoc ()
bool isUnknown () const
isUnknown - Return true if this is an unknown location.
unsigned getLine () const
unsigned getCol () const
MDNode * getScope (const LLVMContext &Ctx) const
MDNode * getInlinedAt (const LLVMContext &Ctx) const
void getScopeAndInlinedAt (MDNode *&Scope, MDNode *&IA, const LLVMContext &Ctx) const
getScopeAndInlinedAt - Return both the Scope and the InlinedAt values.
MDNode * getAsMDNode (const LLVMContext &Ctx) const
bool operator== (const DebugLoc &DL) const
bool operator!= (const DebugLoc &DL) const
void dump (const LLVMContext &Ctx) const
Static Public Member Functions
static DebugLoc get (unsigned Line, unsigned Col, MDNode *Scope, MDNode *InlinedAt=0)
static DebugLoc getFromDILocation (MDNode *N)
getFromDILocation - Translate the DILocation quad into a DebugLoc.
static DebugLoc getFromDILexicalBlock (MDNode *N)
getFromDILexicalBlock - Translate the DILexicalBlock into a DebugLoc.
Friends
struct DenseMapInfo< DebugLoc >
Detailed Description
DebugLoc - Debug location id. This is carried by Instruction, SDNode, and MachineInstr to compactly encode file/line/scope information for an operation.
Definition at line 28 of file DebugLoc.h.
Constructor & Destructor Documentation
llvm::DebugLoc::DebugLoc () inline
Definition at line 56 of file DebugLoc.h.
References getFromDILexicalBlock(), getFromDILocation(), and N.
Referenced by getFromDILexicalBlock(), and getFromDILocation().
Member Function Documentation
void DebugLoc::dump (const LLVMContext & Ctx) const
Definition at line 133 of file DebugLoc.cpp.
References llvm::dbgs(), dump(), getCol(), getFromDILocation(), getInlinedAt(), getLine(), llvm::hash_combine(), and isUnknown().
Referenced by dump(), and operator!=().
DebugLoc DebugLoc::get (unsigned Line, unsigned Col, MDNode * Scope, MDNode * InlinedAt = 0) static
get - Get a new DebugLoc that corresponds to the specified line/col scope/inline location.
Definition at line 74 of file DebugLoc.cpp.
References llvm::Value::getContext(), llvm::LLVMContextImpl::getOrAddScopeInlinedAtIdxEntry(), llvm::LLVMContextImpl::getOrAddScopeRecordIdxEntry(), and llvm::LLVMContext::pImpl.
Referenced by llvm::MipsSEFrameLowering::emitEpilogue(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), getFnDebugLoc(), getNewValueJumpOpcode(), lowerVECTOR_SHUFFLE_VSHF(), llvm::BitcodeReader::ParseTriple(), llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters(), and updateInlinedAtInfo().
MDNode * DebugLoc::getAsMDNode (const LLVMContext & Ctx) const
getAsMDNode - This method converts the compressed DebugLoc node into a DILocation compatible MDNode.
Definition at line 100 of file DebugLoc.cpp.
References llvm::ConstantInt::get(), llvm::MDNode::get(), getCol(), llvm::Value::getContext(), llvm::Type::getInt32Ty(), getLine(), getScopeAndInlinedAt(), and isUnknown().
Referenced by getCol(), and updateInlinedAtInfo().
unsigned llvm::DebugLoc::getCol () const inline
Definition at line 76 of file DebugLoc.h.
References getAsMDNode(), getInlinedAt(), getScope(), and getScopeAndInlinedAt().
Referenced by llvm::DwarfDebug::beginFunction(), llvm::DwarfDebug::beginInstruction(), dump(), llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc(), getAsMDNode(), printDebugLoc(), updateInlinedAtInfo(), and WriteFunction().
DebugLoc DebugLoc::getFromDILexicalBlock (MDNode * N) static
getFromDILexicalBlock - Translate the DILexicalBlock into a DebugLoc.
Definition at line 126 of file DebugLoc.cpp.
References DebugLoc(), llvm::DILexicalBlock::getColumnNumber(), llvm::DILexicalBlock::getContext(), and llvm::DILexicalBlock::getLineNumber().
Referenced by DebugLoc(), and llvm::LexicalScopes::findLexicalScope().
DebugLoc DebugLoc::getFromDILocation (MDNode * N) static
getFromDILocation - Translate the DILocation quad into a DebugLoc.
Definition at line 117 of file DebugLoc.cpp.
References DebugLoc(), llvm::DILocation::getColumnNumber(), llvm::DILocation::getLineNumber(), llvm::DILocation::getOrigLocation(), and llvm::DILocation::getScope().
Referenced by DebugLoc(), dump(), llvm::LexicalScopes::findLexicalScope(), getDebugLocEntry(), getScopeNode(), LLVMSetCurrentDebugLocation(), llvm::MachineInstr::print(), printDebugLoc(), llvm::DIVariable::printExtendedName(), llvm::Instruction::setMetadata(), and updateInlinedAtInfo().
MDNode * DebugLoc::getInlinedAt (const LLVMContext & Ctx) const
getInlinedAt - This returns the InlinedAt pointer for this DebugLoc, or null if invalid or not present.
Definition at line 37 of file DebugLoc.cpp.
References llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::ScopeInlinedAtRecords.
Referenced by dump(), getCol(), getScopeNode(), printDebugLoc(), and updateInlinedAtInfo().
unsigned llvm::DebugLoc::getLine () const inline
Definition at line 72 of file DebugLoc.h.
Referenced by llvm::DwarfDebug::beginFunction(), llvm::DwarfDebug::beginInstruction(), dump(), llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc(), getAsMDNode(), getFunctionName(), printDebugLoc(), updateInlinedAtInfo(), and WriteFunction().
MDNode * DebugLoc::getScope (const LLVMContext & Ctx) const
getScope - This returns the scope pointer for this DebugLoc, or null if invalid.
Definition at line 20 of file DebugLoc.cpp.
References llvm::LLVMContext::pImpl, llvm::LLVMContextImpl::ScopeInlinedAtRecords, and llvm::LLVMContextImpl::ScopeRecords.
Referenced by llvm::DwarfDebug::beginFunction(), llvm::DwarfDebug::beginInstruction(), llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc(), llvm::DwarfDebug::endModule(), getCol(), getFunctionName(), getScopeNode(), isNonGhostDeclaration(), printDebugLoc(), and updateInlinedAtInfo().
void DebugLoc::getScopeAndInlinedAt (MDNode *& Scope, MDNode *& IA, const LLVMContext & Ctx) const
getScopeAndInlinedAt - Return both the Scope and the InlinedAt values.
Return both the Scope and the InlinedAt values.
Definition at line 49 of file DebugLoc.cpp.
References llvm::LLVMContext::pImpl, llvm::LLVMContextImpl::ScopeInlinedAtRecords, and llvm::LLVMContextImpl::ScopeRecords.
Referenced by llvm::LexicalScopes::findLexicalScope(), getAsMDNode(), getCol(), and WriteFunction().
bool llvm::DebugLoc::isUnknown () const inline
isUnknown - Return true if this is an unknown location.
Definition at line 70 of file DebugLoc.h.
Referenced by llvm::DwarfDebug::beginFunction(), llvm::DwarfDebug::beginInstruction(), llvm::ConvertDebugDeclareToDebugValue(), llvm::LexicalScopes::dominates(), llvm::InstCombiner::DoOneIteration(), dump(), llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc(), fixupLineNumbers(), getAsMDNode(), getFunctionName(), getTruncatedArgReg(), llvm::Instruction::hasMetadata(), llvm::LexicalScopes::initialize(), llvm::MachineInstr::isIdenticalTo(), isNonGhostDeclaration(), llvm::MachineInstr::print(), printDebugLoc(), llvm::DIVariable::printExtendedName(), llvm::SelectionDAG::SelectNodeTo(), llvm::IRBuilderBase::SetInstDebugLocation(), and WriteFunction().
bool llvm::DebugLoc::operator!= (const DebugLoc & DL) const inline
Definition at line 100 of file DebugLoc.h.
References dump().
bool llvm::DebugLoc::operator== (const DebugLoc & DL) const inline
Definition at line 97 of file DebugLoc.h.
Friends And Related Function Documentation
friend struct DenseMapInfo< DebugLoc > friend
Definition at line 29 of file DebugLoc.h.
The documentation for this class was generated from the following files:
DebugLoc.h
DebugLoc.cpp