LLVM: llvm::IntegerType Class Reference
LLVM API Documentation
llvm::IntegerType Class Reference
Integer representation type.
#include <DerivedTypes.h>
Public Types
enum { MIN_INT_BITS = 1, MAX_INT_BITS = (1<<23)-1 }
This enum is just used to hold constants we need for IntegerType.
Public Types inherited from llvm::Type
enum TypeID {
VoidTyID = 0, HalfTyID, FloatTyID, DoubleTyID,
X86_FP80TyID, FP128TyID, PPC_FP128TyID, LabelTyID,
MetadataTyID, X86_MMXTyID, IntegerTyID, FunctionTyID,
StructTyID, ArrayTyID, PointerTyID, VectorTyID,
NumTypeIDs, LastPrimitiveTyID = X86_MMXTyID, FirstDerivedTyID = IntegerTyID
}
typedef Type *const * subtype_iterator
typedef std::reverse_iterator< subtype_iterator > subtype_reverse_iterator
Public Member Functions
unsigned getBitWidth () const
Get the number of bits in this IntegerType.
uint64_t getBitMask () const
uint64_t getSignBit () const
APInt getMask () const
Get a bit mask for this type.
bool isPowerOf2ByteWidth () const
Is this a power-of-2 byte-width IntegerType ?
Public Member Functions inherited from llvm::Type
void print (raw_ostream &O) const
void dump () const
LLVMContext & getContext () const
getContext - Return the LLVMContext in which this type was uniqued.
TypeID getTypeID () const
bool isVoidTy () const
isVoidTy - Return true if this is 'void'.
bool isHalfTy () const
isHalfTy - Return true if this is 'half', a 16-bit IEEE fp type.
bool isFloatTy () const
isFloatTy - Return true if this is 'float', a 32-bit IEEE fp type.
bool isDoubleTy () const
isDoubleTy - Return true if this is 'double', a 64-bit IEEE fp type.
bool isX86_FP80Ty () const
isX86_FP80Ty - Return true if this is x86 long double.
bool isFP128Ty () const
isFP128Ty - Return true if this is 'fp128'.
bool isPPC_FP128Ty () const
isPPC_FP128Ty - Return true if this is powerpc long double.
bool isFloatingPointTy () const
const fltSemantics & getFltSemantics () const
bool isX86_MMXTy () const
isX86_MMXTy - Return true if this is X86 MMX.
bool isFPOrFPVectorTy () const
bool isLabelTy () const
isLabelTy - Return true if this is 'label'.
bool isMetadataTy () const
isMetadataTy - Return true if this is 'metadata'.
bool isIntegerTy () const
bool isIntegerTy (unsigned Bitwidth) const
isIntegerTy - Return true if this is an IntegerType of the given width.
bool isIntOrIntVectorTy () const
bool isFunctionTy () const
bool isStructTy () const
bool isArrayTy () const
bool isPointerTy () const
bool isPtrOrPtrVectorTy () const
bool isVectorTy () const
bool canLosslesslyBitCastTo (Type *Ty) const
Determine if this type could be losslessly bitcast to Ty.
bool isEmptyTy () const
bool isPrimitiveType () const
bool isDerivedType () const
bool isFirstClassType () const
bool isSingleValueType () const
bool isAggregateType () const
bool isSized () const
unsigned getPrimitiveSizeInBits () const
unsigned getScalarSizeInBits ()
int getFPMantissaWidth () const
const Type * getScalarType () const
Type * getScalarType ()
subtype_iterator subtype_begin () const
subtype_iterator subtype_end () const
subtype_reverse_iterator subtype_rbegin () const
subtype_reverse_iterator subtype_rend () const
Type * getContainedType (unsigned i) const
unsigned getNumContainedTypes () const
unsigned getIntegerBitWidth () const
Type * getFunctionParamType (unsigned i) const
unsigned getFunctionNumParams () const
bool isFunctionVarArg () const
StringRef getStructName () const
unsigned getStructNumElements () const
Type * getStructElementType (unsigned N) const
Type * getSequentialElementType () const
uint64_t getArrayNumElements () const
Type * getArrayElementType () const
unsigned getVectorNumElements () const
Type * getVectorElementType () const
Type * getPointerElementType () const
unsigned getPointerAddressSpace () const
Get the address space of this pointer or pointer vector type.
PointerType * getPointerTo (unsigned AddrSpace=0)
Static Public Member Functions
static IntegerType * get (LLVMContext &C, unsigned NumBits)
Get or create an IntegerType instance.
static bool classof (const Type *T)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::Type
static Type * getPrimitiveType (LLVMContext &C, TypeID IDNumber)
getPrimitiveType - Return a type based on an identifier.
static Type * getVoidTy (LLVMContext &C)
static Type * getLabelTy (LLVMContext &C)
static Type * getHalfTy (LLVMContext &C)
static Type * getFloatTy (LLVMContext &C)
static Type * getDoubleTy (LLVMContext &C)
static Type * getMetadataTy (LLVMContext &C)
static Type * getX86_FP80Ty (LLVMContext &C)
static Type * getFP128Ty (LLVMContext &C)
static Type * getPPC_FP128Ty (LLVMContext &C)
static Type * getX86_MMXTy (LLVMContext &C)
static IntegerType * getIntNTy (LLVMContext &C, unsigned N)
static IntegerType * getInt1Ty (LLVMContext &C)
static IntegerType * getInt8Ty (LLVMContext &C)
static IntegerType * getInt16Ty (LLVMContext &C)
static IntegerType * getInt32Ty (LLVMContext &C)
static IntegerType * getInt64Ty (LLVMContext &C)
static PointerType * getHalfPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getFloatPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getDoublePtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getX86_FP80PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getFP128PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getPPC_FP128PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getX86_MMXPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getIntNPtrTy (LLVMContext &C, unsigned N, unsigned AS=0)
static PointerType * getInt1PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt8PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt16PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt32PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt64PtrTy (LLVMContext &C, unsigned AS=0)
Protected Member Functions
IntegerType (LLVMContext &C, unsigned NumBits)
Protected Member Functions inherited from llvm::Type
Type (LLVMContext &C, TypeID tid)
~Type ()
void setTypeID (TypeID ID)
unsigned getSubclassData () const
void setSubclassData (unsigned val)
Friends
class LLVMContextImpl
Additional Inherited Members
Protected Attributes inherited from llvm::Type
unsigned NumContainedTys
Type *const * ContainedTys
Detailed Description
Integer representation type.
Class to represent integer types. Note that this class is also used to represent the built-in integer types: Int1Ty, Int8Ty, Int16Ty, Int32Ty and Int64Ty.
Definition at line 37 of file DerivedTypes.h.
Member Enumeration Documentation
anonymous enum
This enum is just used to hold constants we need for IntegerType.
Enumerator
MIN_INT_BITS
Minimum number of bits that can be specified.
MAX_INT_BITS
Maximum number of bits that can be specified Note that bit width is stored in the Type classes SubclassData field which has 23 bits. This yields a maximum bit width of 8,388,607 bits.
Definition at line 46 of file DerivedTypes.h.
Constructor & Destructor Documentation
llvm::IntegerType::IntegerType (LLVMContext & C, unsigned NumBits) inline explicit protected
Definition at line 41 of file DerivedTypes.h.
References llvm::Type::setSubclassData().
Member Function Documentation
static bool llvm::IntegerType::classof (const Type * T) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 88 of file DerivedTypes.h.
References llvm::Type::getTypeID(), and llvm::Type::IntegerTyID.
IntegerType * IntegerType::get (LLVMContext & C, unsigned NumBits) static
Get or create an IntegerType instance.
This static method is the primary way of constructing an IntegerType. If an IntegerType with the same NumBits value was previously instantiated, that instance will be returned. Otherwise a new one will be created. Only one instance with a given NumBits value is ever created.
Definition at line 305 of file Type.cpp.
References llvm::Type::getInt16Ty(), llvm::Type::getInt1Ty(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::Type::getInt8Ty(), llvm::LLVMContextImpl::IntegerTypes, llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::TypeAllocator.
Referenced by BinomialCoefficient(), BitCastConstantVector(), llvm::bypassSlowDivision(), CanShareConstantPoolEntry(), checkInterfaceFunction(), CoerceAvailableValueToLoadType(), CollectInsertionElements(), CommitValueTo(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldInsertElementInstruction(), llvm::ConstantFoldSelectInstruction(), llvm::ConstantFoldShuffleVectorInstruction(), createPrivateNonConstGlobalForString(), llvm::MDBuilder::createRange(), llvm::MDBuilder::createTBAAScalarTypeNode(), llvm::MDBuilder::createTBAAStructNode(), llvm::MDBuilder::createTBAAStructTagNode(), llvm::MDBuilder::createTBAAStructTypeNode(), DecodeFixedType(), ExtractConstantBytes(), llvm::FastISel::FastEmit_ri_(), FoldBitCast(), llvm::ConstantInt::get(), llvm::TypeBuilder< types::i< num_bits >, cross >::get(), getAccessType(), GetAttrFromCode(), llvm::VectorType::getExtendedElementVectorType(), llvm::LLLexer::getFilename(), getFoldedAlignOf(), getFoldedSizeOf(), llvm::VectorType::getInteger(), llvm::Type::getIntNTy(), llvm::DataLayout::getIntPtrType(), GetLoadValueForLoad(), getMemCmpLoad(), GetMemInstValueForLoad(), llvm::MDNode::getMostGenericTBAA(), getPreStartForSignExtend(), llvm::ScalarEvolution::getSignedRange(), llvm::ScalarEvolution::getSignExtendExpr(), GetStoreValueForLoad(), llvm::VectorType::getTruncatedElementVectorType(), llvm::EVT::getTypeForEVT(), llvm::ScalarEvolution::getUDivExpr(), llvm::ScalarEvolution::getZeroExtendExpr(), INITIALIZE_PASS(), isAddRecSExtable(), isAddSExtable(), isCompatibleAggregate(), isMulSExtable(), LLVMIntTypeInContext(), llvm::TargetLowering::ParseConstraints(), ProcessUGT_ADDCST_ADD(), reduceToSingleValueType(), stripAndComputeConstantOffsets(), and llvm::InstCombiner::visitICmpInstWithInstAndIntCst().
uint64_t llvm::IntegerType::getBitMask () const inline
getBitMask - Return a bitmask with ones set for all of the bits that can be set by an unsigned version of this type. This is 0xFF for i8, 0xFFFF for i16, etc.
Definition at line 66 of file DerivedTypes.h.
References getBitWidth().
Referenced by insertFastDiv().
unsigned llvm::IntegerType::getBitWidth () const inline
Get the number of bits in this IntegerType.
Definition at line 61 of file DerivedTypes.h.
References llvm::Type::getSubclassData().
Referenced by llvm::bypassSlowDivision(), CollectBSwapParts(), llvm::ARMTargetLowering::ExpandInlineAsm(), llvm::X86TargetLowering::ExpandInlineAsm(), extractInteger(), llvm::InstCombiner::FoldAndOfICmps(), FoldReinterpretLoadFromConstPtr(), llvm::ConstantInt::get(), getBitMask(), GetCaseResults(), getFCmpValue(), getSignBit(), insertInteger(), insertVector(), InstructionDereferencesPointer(), isCompatibleAggregate(), isRunOfOnes(), LLVMConstIntOfArbitraryPrecision(), llvm::ObjectSizeOffsetVisitor::ObjectSizeOffsetVisitor(), llvm::Constant::removeDeadConstantUsers(), llvm::InstCombiner::visitAdd(), llvm::Interpreter::visitAShr(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), and llvm::InstCombiner::visitSelectInstWithICmp().
APInt IntegerType::getMask () const
Get a bit mask for this type.
For example, this is 0xFF for an 8 bit integer, 0xFFFF for i16, etc.
Returns
a bit mask with ones set for all the bits of this type.
Definition at line 333 of file Type.cpp.
References llvm::Type::ContainedTys, llvm::Type::FunctionTyID, llvm::APInt::getAllOnesValue(), getBitWidth(), llvm::Type::getContext(), i, llvm::Type::NumContainedTys, llvm::Type::setSubclassData(), llvm::ArrayRef< T >::size(), and llvm::Type::Type().
Referenced by getSignBit().
uint64_t llvm::IntegerType::getSignBit () const inline
getSignBit - Return a uint64_t with just the most significant bit set (the sign bit, if the value is treated as a signed number).
Definition at line 72 of file DerivedTypes.h.
References getBitWidth(), getMask(), and isPowerOf2ByteWidth().
bool IntegerType::isPowerOf2ByteWidth () const
Is this a power-of-2 byte-width IntegerType ?
This method determines if the width of this IntegerType is a power-of-2 in terms of 8 bit bytes.
Returns
true if this is a power-of-2 byte width.
Definition at line 328 of file Type.cpp.
References getBitWidth(), and llvm::isPowerOf2_32().
Referenced by getSignBit().
Friends And Related Function Documentation
friend class LLVMContextImpl friend
Definition at line 38 of file DerivedTypes.h.
The documentation for this class was generated from the following files:
DerivedTypes.h
Type.cpp