LLVM: llvm::MipsSEFrameLowering Class Reference
LLVM API Documentation
llvm::MipsSEFrameLowering Class Reference
#include <MipsSEFrameLowering.h>
Public Member Functions
MipsSEFrameLowering (const MipsSubtarget &STI)
void emitPrologue (MachineFunction &MF) const
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const
void eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator I) const
bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const
bool hasReservedCallFrame (const MachineFunction &MF) const
void processFunctionBeforeCalleeSavedScan (MachineFunction &MF, RegScavenger *RS) const
unsigned ehDataReg (unsigned I) const
Public Member Functions inherited from llvm::MipsFrameLowering
MipsFrameLowering (const MipsSubtarget &sti, unsigned Alignment)
bool hasFP (const MachineFunction &MF) const
Public Member Functions inherited from llvm::TargetFrameLowering
TargetFrameLowering (StackDirection D, unsigned StackAl, int LAO, unsigned TransAl=1, bool StackReal=true)
virtual ~TargetFrameLowering ()
StackDirection getStackGrowthDirection () const
unsigned getStackAlignment () const
unsigned getTransientStackAlignment () const
bool isStackRealignable () const
int getOffsetOfLocalArea () const
virtual bool isFPCloseToIncomingSP () const
virtual const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const
virtual bool targetHandlesStackFrameRounding () const
virtual void adjustForSegmentedStacks (MachineFunction &MF) const
virtual void adjustForHiPEPrologue (MachineFunction &MF) const
virtual bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const
virtual bool canSimplifyCallFramePseudos (const MachineFunction &MF) const
virtual int getFrameIndexOffset (const MachineFunction &MF, int FI) const
virtual int getFrameIndexReference (const MachineFunction &MF, int FI, unsigned &FrameReg) const
virtual void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS=NULL) const
Additional Inherited Members
Public Types inherited from llvm::TargetFrameLowering
enum StackDirection { StackGrowsUp, StackGrowsDown }
Static Public Member Functions inherited from llvm::MipsFrameLowering
static const MipsFrameLowering * create (MipsTargetMachine &TM, const MipsSubtarget &ST)
Protected Member Functions inherited from llvm::MipsFrameLowering
uint64_t estimateStackSize (const MachineFunction &MF) const
Protected Attributes inherited from llvm::MipsFrameLowering
const MipsSubtarget & STI
Detailed Description
Definition at line 21 of file MipsSEFrameLowering.h.
Constructor & Destructor Documentation
llvm::MipsSEFrameLowering::MipsSEFrameLowering (const MipsSubtarget & STI) inline explicit
Definition at line 23 of file MipsSEFrameLowering.h.
References ehDataReg(), eliminateCallFramePseudoInstr(), emitEpilogue(), emitPrologue(), hasReservedCallFrame(), I, llvm::A64CC::MI, processFunctionBeforeCalleeSavedScan(), and spillCalleeSavedRegisters().
Member Function Documentation
unsigned MipsSEFrameLowering::ehDataReg (unsigned I) const
Definition at line 260 of file MipsSEFrameLowering.cpp.
References I.
Referenced by MipsSEFrameLowering().
void MipsSEFrameLowering::eliminateCallFramePseudoInstr (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const virtual
eliminateCallFramePseudoInstr - This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them). It is responsible for eliminating these instructions, replacing them with concrete instructions. This method need only be implemented if using call frame setup/destroy pseudo instructions.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 487 of file MipsSEFrameLowering.cpp.
References llvm::MipsSEInstrInfo::adjustStackPtr(), llvm::MachineBasicBlock::erase(), llvm::TargetMachine::getInstrInfo(), llvm::MachineFunction::getTarget(), and processFunctionBeforeCalleeSavedScan().
Referenced by hasReservedCallFrame(), and MipsSEFrameLowering().
void MipsSEFrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const virtual
Implements llvm::TargetFrameLowering.
Definition at line 387 of file MipsSEFrameLowering.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MipsFunctionInfo::callsEhReturn(), llvm::DebugLoc::get(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MipsFunctionInfo::getEhDataRegFI(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::TargetMachine::getInstrInfo(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::TargetMachine::getRegisterInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getTarget(), i, and spillCalleeSavedRegisters().
Referenced by MipsSEFrameLowering().
void MipsSEFrameLowering::emitPrologue (MachineFunction & MF) const virtual
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
Implements llvm::TargetFrameLowering.
Definition at line 271 of file MipsSEFrameLowering.cpp.
References llvm::MachineModuleInfo::addFrameInst(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addReg(), llvm::MachineFrameInfo::adjustsStack(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MipsFunctionInfo::callsEhReturn(), llvm::MCCFIInstruction::createDefCfaOffset(), llvm::MCCFIInstruction::createDefCfaRegister(), llvm::MCCFIInstruction::createOffset(), llvm::MCContext::CreateTempSymbol(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::front(), llvm::DebugLoc::get(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineModuleInfo::getContext(), llvm::MCRegisterInfo::getDwarfRegNum(), llvm::MipsFunctionInfo::getEhDataRegFI(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::TargetMachine::getInstrInfo(), llvm::MachineFunction::getMMI(), llvm::MachineFrameInfo::getObjectOffset(), llvm::TargetMachine::getRegisterInfo(), llvm::MCContext::getRegisterInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getTarget(), i, I, llvm::MachineBasicBlock::isLiveIn(), MRI, llvm::TargetOpcode::PROLOG_LABEL, and std::swap().
Referenced by MipsSEFrameLowering().
bool MipsSEFrameLowering::hasReservedCallFrame (const MachineFunction & MF) const virtual
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function. This eliminates the need for add/sub sp brackets around call sites. Returns true if the call frame is included as part of the stack frame.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 474 of file MipsSEFrameLowering.cpp.
References eliminateCallFramePseudoInstr(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getMaxCallFrameSize(), llvm::MachineFrameInfo::hasVarSizedObjects(), and llvm::isInt< 16 >().
Referenced by MipsSEFrameLowering().
void MipsSEFrameLowering::processFunctionBeforeCalleeSavedScan (MachineFunction & MF, RegScavenger * RS) const virtual
processFunctionBeforeCalleeSavedScan - This method is called immediately before PrologEpilogInserter scans the physical registers used to determine what callee saved registers should be spilled. This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 506 of file MipsSEFrameLowering.cpp.
References llvm::RegScavenger::addScavengingFrameIndex(), llvm::MipsFunctionInfo::callsEhReturn(), llvm::MipsFunctionInfo::createEhDataRegsFI(), llvm::MachineFrameInfo::CreateStackObject(), llvm::TargetRegisterClass::getAlignment(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getRegInfo(), llvm::TargetRegisterClass::getSize(), llvm::isInt< 16 >(), MRI, and llvm::MachineRegisterInfo::setPhysRegUsed().
Referenced by eliminateCallFramePseudoInstr(), and MipsSEFrameLowering().
bool MipsSEFrameLowering::spillCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const virtual
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot(). Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 443 of file MipsSEFrameLowering.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::MachineFunction::begin(), llvm::MachineFunction::getFrameInfo(), llvm::TargetMachine::getInstrInfo(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getTarget(), i, llvm::MachineFrameInfo::isReturnAddressTaken(), and llvm::TargetInstrInfo::storeRegToStackSlot().
Referenced by emitEpilogue(), and MipsSEFrameLowering().
The documentation for this class was generated from the following files:
MipsSEFrameLowering.h
MipsSEFrameLowering.cpp