LLVM: llvm::MDNode Class Reference
LLVM API Documentation
llvm::MDNode Class Reference
MDNode - a tuple of other values.
#include <Metadata.h>
Public Member Functions
void replaceOperandWith (unsigned i, Value *NewVal)
replaceOperandWith - Replace a specific operand.
Value * getOperand (unsigned i) const LLVM_READONLY
getOperand - Return specified operand.
unsigned getNumOperands () const
getNumOperands - Return number of MDNode operands.
bool isFunctionLocal () const
isFunctionLocal - Return whether MDNode is local to a function.
const Function * getFunction () const
void Profile (FoldingSetNodeID &ID) const
bool isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
dump - Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O, AssemblyAnnotationWriter *AAW=0) const
Type * getType () const
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
void setName (const Twine &Name)
void takeName (Value *V)
void replaceAllUsesWith (Value *V)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
User * use_back ()
const User * use_back () const
bool hasOneUse () const
bool hasNUses (unsigned N) const
bool hasNUsesOrMore (unsigned N) const
bool isUsedInBasicBlock (const BasicBlock *BB) const
unsigned getNumUses () const
void addUse (Use &U)
unsigned getValueID () const
unsigned getRawSubclassOptionalData () const
void clearSubclassOptionalData ()
bool hasSameSubclassOptionalData (const Value *V) const
void intersectOptionalDataWith (const Value *V)
bool hasValueHandle () const
Value * stripPointerCasts ()
Strips off any unneeded pointer casts, all-zero GEPs and aliases from the specified value, returning the original uncasted value.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strips off any unneeded pointer casts and all-zero GEPs from the specified value, returning the original uncasted value.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strips off unneeded pointer casts and all-constant GEPs from the specified value, returning the original pointer value.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Strips like stripInBoundsConstantOffsets but also accumulates the constant offset stripped.
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strips off unneeded pointer casts and any in-bounds offsets from the specified value, returning the original pointer value.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer () const
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Public Member Functions inherited from llvm::FoldingSetImpl::Node
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static MDNode * get (LLVMContext &Context, ArrayRef< Value * > Vals)
static MDNode * getWhenValsUnresolved (LLVMContext &Context, ArrayRef< Value * > Vals, bool isFunctionLocal)
static MDNode * getIfExists (LLVMContext &Context, ArrayRef< Value * > Vals)
static MDNode * getTemporary (LLVMContext &Context, ArrayRef< Value * > Vals)
static void deleteTemporary (MDNode *N)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
static MDNode * getMostGenericTBAA (MDNode *A, MDNode *B)
Methods for metadata merging.
static MDNode * getMostGenericFPMath (MDNode *A, MDNode *B)
static MDNode * getMostGenericRange (MDNode *A, MDNode *B)
Friends
class MDNodeOperand
class LLVMContextImpl
struct FoldingSetTrait< MDNode >
Additional Inherited Members
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal, BasicBlockVal, FunctionVal, GlobalAliasVal,
GlobalVariableVal, UndefValueVal, BlockAddressVal, ConstantExprVal,
ConstantAggregateZeroVal, ConstantDataArrayVal, ConstantDataVectorVal, ConstantIntVal,
ConstantFPVal, ConstantArrayVal, ConstantStructVal, ConstantVectorVal,
ConstantPointerNullVal, MDNodeVal, MDStringVal, InlineAsmVal,
PseudoSourceValueVal, FixedStackPseudoSourceValueVal, InstructionVal, ConstantFirstVal = FunctionVal,
ConstantLastVal = ConstantPointerNullVal
}
typedef value_use_iterator< User > use_iterator
typedef value_use_iterator< const User > const_use_iterator
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
Protected Member Functions inherited from llvm::Value
virtual void printCustom (raw_ostream &O) const
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Detailed Description
MDNode - a tuple of other values.
Definition at line 73 of file Metadata.h.
Member Function Documentation
static bool llvm::MDNode::classof (const Value * V) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 164 of file Metadata.h.
References llvm::ARM_PROC::A, B, llvm::Value::getSubclassDataFromValue(), llvm::Value::getValueID(), llvm::Value::MDNodeVal, and llvm::Value::setValueSubclassData().
void MDNode::deleteTemporary (MDNode * N) static
deleteTemporary - Deallocate a node created by getTemporary. The node must not have any users.
Definition at line 292 of file Metadata.cpp.
References llvm::Value::getContext(), llvm::Value::getSubclassDataFromValue(), llvm::LLVMContextImpl::MDNodeSet, llvm::LLVMContextImpl::NonUniquedMDNodes, llvm::LLVMContext::pImpl, llvm::LeakDetector::removeGarbageObject(), and llvm::Value::use_empty().
Referenced by llvm::BitcodeReaderMDValueList::AssignValue(), llvm::MDBuilder::createAnonymousTBAARoot(), llvm::MapValue(), llvm::DIType::replaceAllUsesWith(), and llvm::LLParser::Run().
MDNode * MDNode::get (LLVMContext & Context, ArrayRef< Value * > Vals) static
Definition at line 268 of file Metadata.cpp.
Referenced by llvm::DICompositeType::addMember(), llvm::Module::addModuleFlag(), llvm::DebugRecVH::allUsesReplacedWith(), AppendMDNodeToInstForPtr(), AppendMDNodeToSourcePtr(), llvm::cleanseInlinedVariable(), llvm::MDBuilder::createAnonymousTBAARoot(), llvm::DIBuilder::createArrayType(), llvm::DIBuilder::createArtificialType(), llvm::DIBuilder::createBasicType(), llvm::MDBuilder::createBranchWeights(), llvm::DIBuilder::createClassType(), llvm::DIBuilder::createCompileUnit(), llvm::DIBuilder::createComplexVariable(), llvm::DIBuilder::createEnumerationType(), llvm::DIBuilder::createEnumerator(), llvm::DIBuilder::createFile(), createFilePathPair(), llvm::MDBuilder::createFPMath(), llvm::DIBuilder::createFriend(), llvm::DIBuilder::createFunction(), llvm::DIBuilder::createGlobalVariable(), llvm::DIBuilder::createImportedDeclaration(), createImportedModule(), llvm::DIBuilder::createInheritance(), llvm::createInlinedVariable(), llvm::DIBuilder::createLexicalBlock(), llvm::DIBuilder::createLexicalBlockFile(), llvm::DIBuilder::createLocalVariable(), llvm::DIBuilder::createMemberPointerType(), llvm::DIBuilder::createMemberType(), llvm::DIBuilder::createMethod(), llvm::DIBuilder::createNameSpace(), llvm::createObjCARCOptPass(), llvm::DIBuilder::createObjCIVar(), llvm::DIBuilder::createObjCProperty(), llvm::DIBuilder::createObjectPointerType(), llvm::DIBuilder::createPointerType(), llvm::DIBuilder::createQualifiedType(), llvm::MDBuilder::createRange(), llvm::DIBuilder::createReferenceType(), llvm::DIBuilder::createStaticMemberType(), llvm::DIBuilder::createStaticVariable(), llvm::DIBuilder::createStructType(), llvm::DIBuilder::createSubroutineType(), llvm::MDBuilder::createTBAANode(), llvm::MDBuilder::createTBAARoot(), llvm::MDBuilder::createTBAAScalarTypeNode(), llvm::MDBuilder::createTBAAStructNode(), llvm::MDBuilder::createTBAAStructTagNode(), llvm::MDBuilder::createTBAAStructTypeNode(), llvm::DIBuilder::createTemplateTypeParameter(), llvm::DIBuilder::createTypedef(), llvm::DIBuilder::createUnionType(), llvm::DIBuilder::createUnspecifiedParameter(), llvm::DIBuilder::createUnspecifiedType(), llvm::DIBuilder::createVectorType(), llvm::DebugRecVH::deleted(), FunctionNumber(), getArrayElements(), llvm::DebugLoc::getAsMDNode(), getMostGenericRange(), getMostGenericTBAA(), llvm::DIBuilder::getOrCreateArray(), llvm::DIBuilder::getOrCreateSubrange(), INITIALIZE_PASS(), llvm::DIBuilder::insertDbgValueIntrinsic(), llvm::DIBuilder::insertDeclare(), LLVMMDNodeInContext(), llvm::MapValue(), llvm::LLParser::Run(), StripSymbolNames(), llvm::BranchInst::swapSuccessors(), llvm::UpgradeInstWithTBAATag(), and llvm::UpgradeIntrinsicCall().
const Function * MDNode::getFunction () const
Definition at line 190 of file Metadata.cpp.
References assertLocalFunction(), F(), llvm::LibFunc::free, getFunctionForValue(), llvm::Value::getSubclassDataFromValue(), i, and llvm::Value::setValueSubclassData().
Referenced by llvm::ValueEnumerator::incorporateFunction(), llvm::ValueEnumerator::print(), llvm::Value::print(), and llvm::WriteAsOperandInternal().
MDNode * MDNode::getIfExists (LLVMContext & Context, ArrayRef< Value * > Vals) static
Definition at line 278 of file Metadata.cpp.
Referenced by llvm::FindAllocaDbgDeclare(), and AllocaSlices::SliceBuilder::SliceBuilder().
MDNode * MDNode::getMostGenericFPMath (MDNode * A, MDNode * B) static
Definition at line 408 of file Metadata.cpp.
References B, llvm::APFloat::cmpLessThan, llvm::APFloat::compare(), and getOperand().
Referenced by patchReplacementInstruction().
MDNode * MDNode::getMostGenericRange (MDNode * A, MDNode * B) static
Definition at line 454 of file Metadata.cpp.
References llvm::ARM_PROC::A, addRange(), get(), llvm::Value::getContext(), getNumOperands(), getOperand(), llvm::ConstantInt::getValue(), i, llvm::ConstantRange::isFullSet(), llvm::SmallVectorImpl< T >::resize(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::APInt::slt(), and tryMergeRange().
Referenced by patchReplacementInstruction().
MDNode * MDNode::getMostGenericTBAA (MDNode * A, MDNode * B) static
Methods for metadata merging.
Definition at line 556 of file TypeBasedAliasAnalysis.cpp.
References llvm::ARM_PROC::A, B, llvm::IntegerType::get(), llvm::ConstantInt::get(), get(), llvm::Value::getContext(), getNumOperands(), getOperand(), isStructPathTBAA(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::AArch64ISD::Ret, and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by llvm::createLICMPass(), patchReplacementInstruction(), and llvm::InstCombiner::visitStoreInst().
unsigned llvm::MDNode::getNumOperands () const inline
getNumOperands - Return number of MDNode operands.
Definition at line 146 of file Metadata.h.
Referenced by llvm::Module::addModuleFlag(), AppendMDNodeToSourcePtr(), assertLocalFunction(), cacheAnnotationFromMD(), llvm::cleanseInlinedVariable(), llvm::TypeFinder::clear(), llvm::computeMaskedBitsLoad(), llvm::ConstantFoldTerminator(), llvm::DIBuilder::createArtificialType(), llvm::createInlinedVariable(), llvm::createObjCARCContractPass(), llvm::DIBuilder::createObjectPointerType(), llvm::MachineInstr::emitError(), EmitGCCInlineAsmStr(), llvm::TargetLoweringObjectFileMachO::emitModuleFlags(), llvm::TargetLoweringObjectFileCOFF::emitModuleFlags(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), getArrayElements(), GetBranchWeights(), getField(), getFunctionName(), llvm::Loop::getLoopID(), getMaxWeightFor(), llvm::Module::getModuleFlagsMetadata(), getMostGenericRange(), getMostGenericTBAA(), INITIALIZE_PASS(), llvm::Loop::isAnnotatedParallel(), isContiguous(), isStructPathTBAA(), LLVMGetMDNodeOperands(), llvm::ValueEnumerator::print(), llvm::Loop::setLoopID(), llvm::UpgradeInstWithTBAATag(), ValuesOverlap(), VerifySubsetOf(), llvm::WriteConstantInternal(), WriteMDNode(), and llvm::WriteMDNodeComment().
Value * MDNode::getOperand (unsigned i) const
getOperand - Return specified operand.
Definition at line 307 of file Metadata.cpp.
References getOperandPtr().
Referenced by llvm::Module::addModuleFlag(), AppendMDNodeToSourcePtr(), assertLocalFunction(), cacheAnnotationFromMD(), llvm::cleanseInlinedVariable(), llvm::TypeFinder::clear(), llvm::computeMaskedBitsLoad(), llvm::ConstantFoldTerminator(), llvm::DIBuilder::createArtificialType(), llvm::createInlinedVariable(), llvm::createObjCARCContractPass(), llvm::DIBuilder::createObjectPointerType(), llvm::MachineInstr::emitError(), EmitGCCInlineAsmStr(), llvm::TargetLoweringObjectFileMachO::emitModuleFlags(), llvm::TargetLoweringObjectFileCOFF::emitModuleFlags(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), llvm::FindAvailableLoadedValue(), getArrayElements(), GetBranchWeights(), getField(), llvm::FPMathOperator::getFPAccuracy(), getFunctionName(), llvm::Loop::getLoopID(), getMaxWeightFor(), llvm::Module::getModuleFlagsMetadata(), getMostGenericFPMath(), getMostGenericRange(), getMostGenericTBAA(), HasBranchWeights(), INITIALIZE_PASS(), llvm::Loop::isAnnotatedParallel(), isContiguous(), isStructPathTBAA(), isTBAAVtableAccess(), LLVMGetMDNodeOperands(), llvm::ValueEnumerator::print(), llvm::MachineInstr::print(), llvm::Loop::setLoopID(), llvm::DICompositeType::setTypeArray(), llvm::UpgradeInstWithTBAATag(), ValuesOverlap(), VerifySubsetOf(), WriteMDNode(), and llvm::WriteMDNodeComment().
MDNode * MDNode::getTemporary (LLVMContext & Context, ArrayRef< Value * > Vals) static
getTemporary - Return a temporary MDNode, for use in constructing cyclic MDNode structures. A temporary MDNode is not uniqued, may be RAUW'd, and must be manually deleted with deleteTemporary.
Definition at line 282 of file Metadata.cpp.
References llvm::LeakDetector::addGarbageObject(), llvm::Value::getSubclassDataFromValue(), llvm::LibFunc::malloc, N, and llvm::ArrayRef< T >::size().
Referenced by llvm::MDBuilder::createAnonymousTBAARoot(), llvm::DIBuilder::createCompileUnit(), llvm::DIBuilder::createForwardDecl(), llvm::DIBuilder::createFunction(), llvm::DIBuilder::createMethod(), llvm::BitcodeReaderMDValueList::getValueFwdRef(), llvm::MapValue(), and llvm::LLParser::Run().
MDNode * MDNode::getWhenValsUnresolved (LLVMContext & Context, ArrayRef< Value * > Vals, bool isFunctionLocal) static
Definition at line 272 of file Metadata.cpp.
Referenced by GetAttrFromCode().
bool llvm::MDNode::isFunctionLocal () const inline
isFunctionLocal - Return whether MDNode is local to a function.
Definition at line 149 of file Metadata.h.
References llvm::Value::getSubclassDataFromValue().
Referenced by llvm::NamedMDNode::addOperand(), assertLocalFunction(), llvm::ValueEnumerator::incorporateFunction(), llvm::ValueEnumerator::print(), llvm::WriteAsOperandInternal(), and WriteMDNode().
bool MDNode::isTBAAVtableAccess () const
Check whether MDNode is a vtable access.
Definition at line 537 of file TypeBasedAliasAnalysis.cpp.
References getOperand(), and isStructPathTBAA().
void MDNode::Profile (FoldingSetNodeID & ID) const
Profile - calculate a unique identifier for this MDNode to collapse duplicates
Definition at line 312 of file Metadata.cpp.
References llvm::FoldingSetNodeID::AddPointer(), llvm::FoldingSetNodeID::ComputeHash(), F(), llvm::Type::getContext(), getFunctionForValue(), llvm::Value::getSubclassDataFromValue(), llvm::Value::getType(), i, isFunctionLocalValue(), llvm::LLVMContextImpl::MDNodeSet, N, llvm::LLVMContextImpl::NonUniquedMDNodes, llvm::LLVMContext::pImpl, llvm::Value::replaceAllUsesWith(), llvm::MDNodeOperand::set(), and llvm::Value::setValueSubclassData().
Referenced by llvm::FoldingSetTrait< MDNode >::Equals().
void MDNode::replaceOperandWith (unsigned i, Value * NewVal)
replaceOperandWith - Replace a specific operand.
Definition at line 108 of file Metadata.cpp.
References llvm::Type::getContext(), llvm::Type::getMetadataTy(), getOperandPtr(), llvm::Value::getSubclassDataFromValue(), llvm::Value::getType(), i, llvm::LLVMContextImpl::MDNodeSet, llvm::Value::MDNodeVal, llvm::LLVMContextImpl::NonUniquedMDNodes, llvm::LLVMContext::pImpl, llvm::MDNodeOperand::setAsFirstOperand(), llvm::Value::setValueSubclassData(), and llvm::ArrayRef< T >::size().
Referenced by llvm::MDBuilder::createAnonymousTBAARoot(), llvm::DIDescriptor::replaceFunctionField(), llvm::DICompositeType::setContainingType(), and llvm::DICompositeType::setTypeArray().
Friends And Related Function Documentation
friend struct FoldingSetTrait< MDNode > friend
Definition at line 78 of file Metadata.h.
friend class LLVMContextImpl friend
Definition at line 77 of file Metadata.h.
friend class MDNodeOperand friend
Definition at line 76 of file Metadata.h.
The documentation for this class was generated from the following files:
Metadata.h
TypeBasedAliasAnalysis.cpp
Metadata.cpp