LLVM: llvm::MipsSubtarget Class Reference
LLVM API Documentation
llvm::MipsSubtarget Class Reference
#include <MipsSubtarget.h>
Public Types
enum MipsABIEnum {
UnknownABI, O32, N32, N64,
EABI
}
Public Member Functions
virtual bool enablePostRAScheduler (CodeGenOpt::Level OptLevel, AntiDepBreakMode &Mode, RegClassVector &CriticalPathRCs) const
bool isABI_EABI () const
Only O32 and EABI supported right now.
bool isABI_N64 () const
bool isABI_N32 () const
bool isABI_O32 () const
unsigned getTargetABI () const
MipsSubtarget (const std::string &TT, const std::string &CPU, const std::string &FS, bool little, Reloc::Model RM, MipsTargetMachine *TM)
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
bool hasMips32 () const
bool hasMips32r2 () const
bool hasMips64 () const
bool hasMips64r2 () const
bool isLittle () const
bool isFP64bit () const
bool isNotFP64bit () const
bool isGP64bit () const
bool isGP32bit () const
bool isSingleFloat () const
bool isNotSingleFloat () const
bool hasVFPU () const
bool inMips16Mode () const
bool inMips16ModeDefault () const
bool inMips16HardFloat () const
bool inMicroMipsMode () const
bool hasDSP () const
bool hasDSPR2 () const
bool hasMSA () const
bool isLinux () const
bool useSmallSection () const
bool hasStandardEncoding () const
bool mipsSEUsesSoftFloat () const
bool enableLongBranchPass () const
bool hasSEInReg () const
Features related to the presence of specific instructions.
bool hasCondMov () const
bool hasSwap () const
bool hasBitCount () const
bool hasFPIdx () const
bool hasExtractInsert () const
const InstrItineraryData & getInstrItineraryData () const
bool allowMixed16_32 () const
bool os16 () const
unsigned stackAlignment () const
const MipsReginfo & getMReginfo () const
Reloc::Model getRelocationModel () const
void resetSubtarget (MachineFunction *MF)
Reset the subtarget for the Mips target.
Static Public Member Functions
static bool useConstantIslands ()
Protected Types
enum MipsArchEnum { Mips32, Mips32r2, Mips64, Mips64r2 }
enum { NoOverride, Mips16Override, NoMips16Override }
Protected Attributes
MipsArchEnum MipsArchVersion
MipsABIEnum MipsABI
bool IsLittle
bool IsSingleFloat
bool IsFP64bit
bool IsGP64bit
bool HasVFPU
bool IsLinux
bool UseSmallSection
bool HasSEInReg
Features related to the presence of specific instructions.
bool HasCondMov
bool HasSwap
bool HasBitCount
bool HasFPIdx
bool InMips16Mode
bool InMips16HardFloat
bool PreviousInMips16Mode
bool InMicroMipsMode
bool HasDSP
bool HasDSPR2
bool AllowMixed16_32
bool Os16
bool HasMSA
InstrItineraryData InstrItins
MipsReginfo MRI
Reloc::Model RM
enum llvm::MipsSubtarget:: { ... } OverrideMode
MipsTargetMachine * TM
Detailed Description
Definition at line 32 of file MipsSubtarget.h.
Member Enumeration Documentation
anonymous enum protected
Enumerator
NoOverride
Mips16Override
NoMips16Override
Definition at line 129 of file MipsSubtarget.h.
enum llvm::MipsSubtarget::MipsABIEnum
Enumerator
UnknownABI
O32
N32
N64
EABI
Definition at line 37 of file MipsSubtarget.h.
enum llvm::MipsSubtarget::MipsArchEnum protected
Enumerator
Mips32
Mips32r2
Mips64
Mips64r2
Definition at line 43 of file MipsSubtarget.h.
Constructor & Destructor Documentation
MipsSubtarget::MipsSubtarget (const std::string & TT, const std::string & CPU, const std::string & FS, bool little, Reloc::Model RM, MipsTargetMachine * TM)
This constructor initializes the data members to match that of the specified triple.
Definition at line 64 of file MipsSubtarget.cpp.
References HasBitCount, hasMips64(), hasMSA(), InMips16Mode, inMips16Mode(), InstrItins, isABI_EABI(), isABI_N32(), isABI_N64(), isABI_O32(), isFP64bit(), IsLinux, MipsABI, N64, O32, ParseSubtargetFeatures(), PreviousInMips16Mode, llvm::report_fatal_error(), RM, llvm::Reloc::Static, UnknownABI, and UseSmallSection.
Referenced by getTargetABI().
Member Function Documentation
bool llvm::MipsSubtarget::allowMixed16_32 () const inline
Definition at line 210 of file MipsSubtarget.h.
References AllowMixed16_32, and inMips16ModeDefault().
Referenced by llvm::MipsTargetMachine::addAnalysisPasses(), enableLongBranchPass(), and llvm::MipsAsmPrinter::runOnMachineFunction().
bool llvm::MipsSubtarget::enableLongBranchPass () const inline
Definition at line 197 of file MipsSubtarget.h.
References allowMixed16_32(), and hasStandardEncoding().
Referenced by llvm::MipsTargetMachine::addAnalysisPasses().
bool MipsSubtarget::enablePostRAScheduler (CodeGenOpt::Level OptLevel, AntiDepBreakMode & Mode, RegClassVector & CriticalPathRCs) const virtual
Definition at line 115 of file MipsSubtarget.cpp.
References llvm::CodeGenOpt::Aggressive, llvm::TargetSubtargetInfo::ANTIDEP_NONE, and hasMips64().
const InstrItineraryData& llvm::MipsSubtarget::getInstrItineraryData () const inline
Definition at line 209 of file MipsSubtarget.h.
References InstrItins.
const MipsReginfo& llvm::MipsSubtarget::getMReginfo () const inline
Definition at line 223 of file MipsSubtarget.h.
References MRI.
Referenced by llvm::MipsAsmPrinter::EmitEndOfAsmFile().
Reloc::Model llvm::MipsSubtarget::getRelocationModel () const inline
Definition at line 226 of file MipsSubtarget.h.
References resetSubtarget(), and RM.
Referenced by assureFPCallStub(), createFPFnStub(), emitELFHeaderFlagsCG(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), and fixupFPReturnAndCall().
unsigned llvm::MipsSubtarget::getTargetABI () const inline
Definition at line 143 of file MipsSubtarget.h.
References llvm::X86II::FS, llvm::support::little, MipsABI, MipsSubtarget(), and ParseSubtargetFeatures().
Referenced by llvm::MipsAsmPrinter::getCurrentABIString().
bool llvm::MipsSubtarget::hasBitCount () const inline
Definition at line 205 of file MipsSubtarget.h.
References HasBitCount.
Referenced by llvm::MipsTargetLowering::MipsTargetLowering().
bool llvm::MipsSubtarget::hasCondMov () const inline
Definition at line 203 of file MipsSubtarget.h.
References HasCondMov.
bool llvm::MipsSubtarget::hasDSP () const inline
Definition at line 187 of file MipsSubtarget.h.
References HasDSP.
Referenced by llvm::MipsSETargetLowering::getRepRegClassFor(), llvm::MipsSETargetLowering::MipsSETargetLowering(), and performDSPShiftCombine().
bool llvm::MipsSubtarget::hasDSPR2 () const inline
Definition at line 188 of file MipsSubtarget.h.
References HasDSPR2.
Referenced by llvm::MipsSETargetLowering::MipsSETargetLowering(), performSRACombine(), and performSRLCombine().
bool llvm::MipsSubtarget::hasExtractInsert () const inline
Definition at line 207 of file MipsSubtarget.h.
References hasMips32r2(), and inMips16Mode().
Referenced by lowerFABS64(), lowerFCOPYSIGN64(), performANDCombine(), and performORCombine().
bool llvm::MipsSubtarget::hasFPIdx () const inline
Definition at line 206 of file MipsSubtarget.h.
References HasFPIdx.
bool llvm::MipsSubtarget::hasMips32 () const inline
Definition at line 155 of file MipsSubtarget.h.
References Mips32.
Referenced by performADDECombine(), and performSUBECombine().
bool llvm::MipsSubtarget::hasMips32r2 () const inline
Definition at line 156 of file MipsSubtarget.h.
References Mips32r2, and Mips64r2.
Referenced by emitELFHeaderFlagsCG(), hasExtractInsert(), and llvm::MipsTargetLowering::MipsTargetLowering().
bool llvm::MipsSubtarget::hasMips64 () const inline
Definition at line 158 of file MipsSubtarget.h.
References Mips64.
Referenced by emitELFHeaderFlagsCG(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), enablePostRAScheduler(), lowerFABS64(), lowerFCOPYSIGN64(), MipsSubtarget(), parsePhysicalReg(), and stackAlignment().
bool llvm::MipsSubtarget::hasMips64r2 () const inline
Definition at line 159 of file MipsSubtarget.h.
References Mips64r2.
Referenced by emitELFHeaderFlagsCG(), and llvm::MipsTargetLowering::MipsTargetLowering().
bool llvm::MipsSubtarget::hasMSA () const inline
Definition at line 189 of file MipsSubtarget.h.
References HasMSA.
Referenced by llvm::MipsTargetLowering::getOpndList(), isConstantOrUndefBUILD_VECTOR(), llvm::MipsSETargetLowering::MipsSETargetLowering(), MipsSubtarget(), performANDCombine(), performORCombine(), performSRACombine(), and performXORCombine().
bool llvm::MipsSubtarget::hasSEInReg () const inline
Features related to the presence of specific instructions.
Definition at line 202 of file MipsSubtarget.h.
References HasSEInReg.
Referenced by llvm::MipsTargetLowering::MipsTargetLowering().
bool llvm::MipsSubtarget::hasStandardEncoding () const inline
Definition at line 193 of file MipsSubtarget.h.
References inMips16Mode(), and mipsSEUsesSoftFloat().
Referenced by enableLongBranchPass().
bool llvm::MipsSubtarget::hasSwap () const inline
Definition at line 204 of file MipsSubtarget.h.
References HasSwap.
Referenced by llvm::MipsTargetLowering::MipsTargetLowering().
bool llvm::MipsSubtarget::hasVFPU () const inline
Definition at line 168 of file MipsSubtarget.h.
References HasVFPU.
bool llvm::MipsSubtarget::inMicroMipsMode () const inline
Definition at line 186 of file MipsSubtarget.h.
References InMicroMipsMode.
Referenced by emitELFHeaderFlagsCG(), and llvm::MipsAsmPrinter::EmitFunctionEntryLabel().
bool llvm::MipsSubtarget::inMips16HardFloat () const inline
Definition at line 183 of file MipsSubtarget.h.
References InMips16HardFloat, and inMips16Mode().
Referenced by llvm::MipsTargetLowering::getOpndList(), llvm::Mips16TargetLowering::Mips16TargetLowering(), and originalTypeIsF128().
bool llvm::MipsSubtarget::inMips16Mode () const inline
Definition at line 169 of file MipsSubtarget.h.
References InMips16Mode, llvm_unreachable, Mips16Override, NoMips16Override, and NoOverride.
Referenced by llvm::MipsTargetMachine::addAnalysisPasses(), llvm::MipsFrameLowering::create(), llvm::MipsInstrInfo::create(), llvm::MipsTargetLowering::create(), llvm::createMipsConstantIslandPass(), llvm::createMipsISelDag(), emitELFHeaderFlagsCG(), llvm::MipsAsmPrinter::EmitFunctionBodyEnd(), llvm::MipsAsmPrinter::EmitFunctionBodyStart(), llvm::MipsAsmPrinter::EmitFunctionEntryLabel(), emitGPDisp(), llvm::MipsAsmPrinter::EmitInstruction(), llvm::MipsRegisterInfo::getFrameRegister(), llvm::MipsFunctionInfo::getGlobalBaseReg(), llvm::MipsTargetMachine::getInstrItineraryData(), llvm::MipsRegisterInfo::getReservedRegs(), hasExtractInsert(), hasStandardEncoding(), inMips16HardFloat(), llvm::MipsAsmPrinter::MipsAsmPrinter(), MipsSubtarget(), parsePhysicalReg(), and resetSubtarget().
bool llvm::MipsSubtarget::inMips16ModeDefault () const inline
Definition at line 180 of file MipsSubtarget.h.
References InMips16Mode.
Referenced by allowMixed16_32().
bool llvm::MipsSubtarget::isABI_EABI () const inline
Only O32 and EABI supported right now.
Definition at line 139 of file MipsSubtarget.h.
References EABI.
Referenced by llvm::MipsAsmPrinter::EmitStartOfAsmFile(), and MipsSubtarget().
bool llvm::MipsSubtarget::isABI_N32 () const inline
Definition at line 141 of file MipsSubtarget.h.
References N32.
Referenced by llvm::MipsRegisterInfo::getCalleeSavedRegs(), llvm::MipsRegisterInfo::getCallPreservedMask(), llvm::MipsTargetObjectFile::Initialize(), and MipsSubtarget().
bool llvm::MipsSubtarget::isABI_N64 () const inline
Definition at line 140 of file MipsSubtarget.h.
References N64.
Referenced by llvm::MipsSEInstrInfo::adjustStackPtr(), llvm::MipsFunctionInfo::createEhDataRegsFI(), llvm::MipsReginfo::emitMipsReginfoSectionCG(), llvm::MipsRegisterInfo::getCalleeSavedRegs(), llvm::MipsRegisterInfo::getCallPreservedMask(), llvm::MipsRegisterInfo::getFrameRegister(), llvm::MipsFunctionInfo::getGlobalBaseReg(), llvm::MipsRegisterInfo::getPointerRegClass(), llvm::MipsTargetObjectFile::Initialize(), isMSALoadOrStore(), llvm::MipsSEInstrInfo::loadImmediate(), and MipsSubtarget().
bool llvm::MipsSubtarget::isABI_O32 () const inline
Definition at line 142 of file MipsSubtarget.h.
References O32.
Referenced by emitELFHeaderFlagsCG(), emitGPDisp(), llvm::MipsReginfo::emitMipsReginfoSectionCG(), and MipsSubtarget().
bool llvm::MipsSubtarget::isFP64bit () const inline
Definition at line 162 of file MipsSubtarget.h.
References IsFP64bit.
Referenced by llvm::MipsRegisterInfo::getCalleeSavedRegs(), llvm::MipsRegisterInfo::getCallPreservedMask(), llvm::MipsTargetLowering::getOpndList(), llvm::MipsRegisterInfo::getReservedRegs(), lowerVECTOR_SHUFFLE_VSHF(), llvm::MipsSETargetLowering::MipsSETargetLowering(), MipsSubtarget(), and parsePhysicalReg().
bool llvm::MipsSubtarget::isGP32bit () const inline
Definition at line 165 of file MipsSubtarget.h.
References IsGP64bit.
Referenced by llvm::MipsAsmPrinter::EmitStartOfAsmFile().
bool llvm::MipsSubtarget::isGP64bit () const inline
Definition at line 164 of file MipsSubtarget.h.
References IsGP64bit.
Referenced by llvm::MipsAsmPrinter::PrintAsmOperand().
bool llvm::MipsSubtarget::isLinux () const inline
Definition at line 190 of file MipsSubtarget.h.
References IsLinux.
bool llvm::MipsSubtarget::isLittle () const inline
Definition at line 161 of file MipsSubtarget.h.
References IsLittle.
Referenced by assureFPCallStub(), createFPFnStub(), llvm::MipsSETargetLowering::EmitInstrWithCustomInserter(), llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), llvm::MipsTargetLowering::getOpndList(), isConstantOrUndefBUILD_VECTOR(), llvm::MipsTargetLowering::lowerLOAD(), lowerMSABitClearImm(), llvm::MipsTargetLowering::lowerSTORE(), performDSPShiftCombine(), performORCombine(), and llvm::MipsAsmPrinter::PrintAsmOperand().
bool llvm::MipsSubtarget::isNotFP64bit () const inline
Definition at line 163 of file MipsSubtarget.h.
References IsFP64bit.
bool llvm::MipsSubtarget::isNotSingleFloat () const inline
Definition at line 167 of file MipsSubtarget.h.
References IsSingleFloat.
bool llvm::MipsSubtarget::isSingleFloat () const inline
Definition at line 166 of file MipsSubtarget.h.
References IsSingleFloat.
Referenced by llvm::MipsRegisterInfo::getCalleeSavedRegs(), llvm::MipsRegisterInfo::getCallPreservedMask(), llvm::MipsSETargetLowering::MipsSETargetLowering(), and parsePhysicalReg().
bool MipsSubtarget::mipsSEUsesSoftFloat () const
Definition at line 169 of file MipsSubtarget.cpp.
References InMips16HardFloat, llvm::TargetMachine::Options, TM, and llvm::TargetOptions::UseSoftFloat.
Referenced by llvm::MipsTargetLowering::getOpndList(), hasStandardEncoding(), and llvm::MipsSETargetLowering::MipsSETargetLowering().
bool llvm::MipsSubtarget::os16 () const inline
Definition at line 213 of file MipsSubtarget.h.
References Os16, and useConstantIslands().
void llvm::MipsSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options. Definition of function is auto generated by tblgen.
Referenced by getTargetABI(), and MipsSubtarget().
void MipsSubtarget::resetSubtarget (MachineFunction * MF)
Reset the subtarget for the Mips target.
Definition at line 129 of file MipsSubtarget.cpp.
References llvm::dbgs(), DEBUG, llvm::Function::getAttributes(), llvm::MachineFunction::getFunction(), llvm::AttributeSet::hasAttribute(), inMips16Mode(), Mips16Override, NoMips16Override, NoOverride, OverrideMode, PreviousInMips16Mode, llvm::MipsTargetMachine::setHelperClassesMips16(), llvm::MipsTargetMachine::setHelperClassesMipsSE(), and TM.
Referenced by getRelocationModel().
unsigned llvm::MipsSubtarget::stackAlignment () const inline
Definition at line 220 of file MipsSubtarget.h.
References hasMips64().
bool MipsSubtarget::useConstantIslands () static
Definition at line 173 of file MipsSubtarget.cpp.
References llvm::dbgs(), DEBUG, and Mips16ConstantIslands.
Referenced by llvm::createMipsConstantIslandPass(), llvm::MipsAsmPrinter::MipsAsmPrinter(), and os16().
bool llvm::MipsSubtarget::useSmallSection () const inline
Definition at line 191 of file MipsSubtarget.h.
References UseSmallSection.
Referenced by llvm::MipsRegisterInfo::getReservedRegs(), and llvm::MipsTargetObjectFile::IsGlobalInSmallSection().
Member Data Documentation
bool llvm::MipsSubtarget::AllowMixed16_32 protected
Definition at line 109 of file MipsSubtarget.h.
Referenced by allowMixed16_32().
bool llvm::MipsSubtarget::HasBitCount protected
Definition at line 88 of file MipsSubtarget.h.
Referenced by hasBitCount(), and MipsSubtarget().
bool llvm::MipsSubtarget::HasCondMov protected
Definition at line 82 of file MipsSubtarget.h.
Referenced by hasCondMov().
bool llvm::MipsSubtarget::HasDSP protected
Definition at line 106 of file MipsSubtarget.h.
Referenced by hasDSP().
bool llvm::MipsSubtarget::HasDSPR2 protected
Definition at line 106 of file MipsSubtarget.h.
Referenced by hasDSPR2().
bool llvm::MipsSubtarget::HasFPIdx protected
Definition at line 91 of file MipsSubtarget.h.
Referenced by hasFPIdx().
bool llvm::MipsSubtarget::HasMSA protected
Definition at line 117 of file MipsSubtarget.h.
Referenced by hasMSA().
bool llvm::MipsSubtarget::HasSEInReg protected
Features related to the presence of specific instructions.
Definition at line 79 of file MipsSubtarget.h.
Referenced by hasSEInReg().
bool llvm::MipsSubtarget::HasSwap protected
Definition at line 85 of file MipsSubtarget.h.
Referenced by hasSwap().
bool llvm::MipsSubtarget::HasVFPU protected
Definition at line 68 of file MipsSubtarget.h.
Referenced by hasVFPU().
bool llvm::MipsSubtarget::InMicroMipsMode protected
Definition at line 103 of file MipsSubtarget.h.
Referenced by inMicroMipsMode().
bool llvm::MipsSubtarget::InMips16HardFloat protected
Definition at line 97 of file MipsSubtarget.h.
Referenced by inMips16HardFloat(), and mipsSEUsesSoftFloat().
bool llvm::MipsSubtarget::InMips16Mode protected
Definition at line 94 of file MipsSubtarget.h.
Referenced by inMips16Mode(), inMips16ModeDefault(), and MipsSubtarget().
InstrItineraryData llvm::MipsSubtarget::InstrItins protected
Definition at line 119 of file MipsSubtarget.h.
Referenced by getInstrItineraryData(), and MipsSubtarget().
bool llvm::MipsSubtarget::IsFP64bit protected
Definition at line 62 of file MipsSubtarget.h.
Referenced by isFP64bit(), and isNotFP64bit().
bool llvm::MipsSubtarget::IsGP64bit protected
Definition at line 65 of file MipsSubtarget.h.
Referenced by isGP32bit(), and isGP64bit().
bool llvm::MipsSubtarget::IsLinux protected
Definition at line 71 of file MipsSubtarget.h.
Referenced by isLinux(), and MipsSubtarget().
bool llvm::MipsSubtarget::IsLittle protected
Definition at line 54 of file MipsSubtarget.h.
Referenced by isLittle().
bool llvm::MipsSubtarget::IsSingleFloat protected
Definition at line 59 of file MipsSubtarget.h.
Referenced by isNotSingleFloat(), and isSingleFloat().
MipsABIEnum llvm::MipsSubtarget::MipsABI protected
Definition at line 51 of file MipsSubtarget.h.
Referenced by getTargetABI(), and MipsSubtarget().
MipsArchEnum llvm::MipsSubtarget::MipsArchVersion protected
Definition at line 48 of file MipsSubtarget.h.
MipsReginfo llvm::MipsSubtarget::MRI protected
Definition at line 122 of file MipsSubtarget.h.
Referenced by getMReginfo().
bool llvm::MipsSubtarget::Os16 protected
Definition at line 114 of file MipsSubtarget.h.
Referenced by os16().
enum { ... } llvm::MipsSubtarget::OverrideMode
Referenced by resetSubtarget().
bool llvm::MipsSubtarget::PreviousInMips16Mode protected
Definition at line 100 of file MipsSubtarget.h.
Referenced by MipsSubtarget(), and resetSubtarget().
Reloc::Model llvm::MipsSubtarget::RM protected
Definition at line 125 of file MipsSubtarget.h.
Referenced by getRelocationModel(), and MipsSubtarget().
MipsTargetMachine* llvm::MipsSubtarget::TM protected
Definition at line 131 of file MipsSubtarget.h.
Referenced by mipsSEUsesSoftFloat(), and resetSubtarget().
bool llvm::MipsSubtarget::UseSmallSection protected
Definition at line 74 of file MipsSubtarget.h.
Referenced by MipsSubtarget(), and useSmallSection().
The documentation for this class was generated from the following files:
MipsSubtarget.h
MipsSubtarget.cpp