LLVM: llvm::AsmPrinter Class Reference
LLVM API Documentation
llvm::AsmPrinter Class Reference
#include <AsmPrinter.h>
Public Types
enum CFIMoveType { CFI_M_None, CFI_M_EH, CFI_M_Debug }
Public Member Functions
virtual ~AsmPrinter ()
const DwarfDebug * getDwarfDebug () const
bool isVerbose () const
unsigned getFunctionNumber () const
const TargetLoweringObjectFile & getObjFileLowering () const
getObjFileLowering - Return information about object file lowering.
const DataLayout & getDataLayout () const
getDataLayout - Return information about data layout.
StringRef getTargetTriple () const
getTargetTriple - Return the target triple string.
const MCSection * getCurrentSection () const
getCurrentSection() - Return the current section we are emitting to.
MCSymbol * getSymbol (const GlobalValue *GV) const
void getAnalysisUsage (AnalysisUsage &AU) const
bool doInitialization (Module &M)
bool doFinalization (Module &M)
virtual bool runOnMachineFunction (MachineFunction &MF)
void SetupMachineFunction (MachineFunction &MF)
void EmitFunctionHeader ()
void EmitFunctionBody ()
void emitPrologLabel (const MachineInstr &MI)
CFIMoveType needsCFIMoves ()
bool needsSEHMoves ()
bool needsRelocationsForDwarfStringPool () const
virtual void EmitConstantPool ()
void EmitJumpTableInfo ()
virtual void EmitGlobalVariable (const GlobalVariable *GV)
EmitGlobalVariable - Emit the specified global variable to the .s file.
bool EmitSpecialLLVMGlobal (const GlobalVariable *GV)
void EmitAlignment (unsigned NumBits, const GlobalValue *GV=0) const
void EmitBasicBlockStart (const MachineBasicBlock *MBB) const
void EmitGlobalConstant (const Constant *CV)
Print a general LLVM constant to the .s file.
virtual void EmitStartOfAsmFile (Module &)
virtual void EmitEndOfAsmFile (Module &)
virtual void EmitFunctionBodyStart ()
virtual void EmitFunctionBodyEnd ()
virtual void EmitInstruction (const MachineInstr *)
EmitInstruction - Targets should implement this to emit instructions.
virtual void EmitFunctionEntryLabel ()
virtual void EmitMachineConstantPoolValue (MachineConstantPoolValue *MCPV)
virtual void EmitXXStructor (const Constant *CV)
virtual bool isBlockOnlyReachableByFallthrough (const MachineBasicBlock *MBB) const
virtual void emitImplicitDef (const MachineInstr *MI) const
MCSymbol * GetTempSymbol (StringRef Name, unsigned ID) const
MCSymbol * GetTempSymbol (StringRef Name) const
MCSymbol * GetSymbolWithGlobalValueBase (const GlobalValue *GV, StringRef Suffix, bool ForcePrivate=true) const
MCSymbol * GetExternalSymbolSymbol (StringRef Sym) const
MCSymbol * GetCPISymbol (unsigned CPID) const
GetCPISymbol - Return the symbol for the specified constant pool entry.
MCSymbol * GetJTISymbol (unsigned JTID, bool isLinkerPrivate=false) const
GetJTISymbol - Return the symbol for the specified jump table entry.
MCSymbol * GetJTSetSymbol (unsigned UID, unsigned MBBID) const
MCSymbol * GetBlockAddressSymbol (const BlockAddress *BA) const
MCSymbol * GetBlockAddressSymbol (const BasicBlock *BB) const
void printOffset (int64_t Offset, raw_ostream &OS) const
printOffset - This is just convenient handler for printing offsets.
void EmitInt8 (int Value) const
void EmitInt16 (int Value) const
void EmitInt32 (int Value) const
void EmitLabelDifference (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Size) const
void EmitLabelOffsetDifference (const MCSymbol *Hi, uint64_t Offset, const MCSymbol *Lo, unsigned Size) const
void EmitLabelPlusOffset (const MCSymbol *Label, uint64_t Offset, unsigned Size, bool IsSectionRelative=false) const
void EmitLabelReference (const MCSymbol *Label, unsigned Size, bool IsSectionRelative=false) const
void EmitSLEB128 (int64_t Value, const char *Desc=0) const
EmitSLEB128 - emit the specified signed leb128 value.
void EmitULEB128 (uint64_t Value, const char *Desc=0, unsigned PadTo=0) const
EmitULEB128 - emit the specified unsigned leb128 value.
void EmitCFAByte (unsigned Val) const
EmitCFAByte - Emit a .byte 42 directive for a DW_CFA_xxx value.
void EmitEncodingByte (unsigned Val, const char *Desc=0) const
unsigned GetSizeOfEncodedValue (unsigned Encoding) const
GetSizeOfEncodedValue - Return the size of the encoding in bytes.
void EmitTTypeReference (const GlobalValue *GV, unsigned Encoding) const
EmitReference - Emit reference to a ttype global with a specified encoding.
void EmitSectionOffset (const MCSymbol *Label, const MCSymbol *SectionLabel) const
virtual unsigned getISAEncoding ()
virtual void EmitDwarfRegOp (const MachineLocation &MLoc, bool Indirect) const
EmitDwarfRegOp - Emit dwarf register operation.
void emitCFIInstruction (const MCCFIInstruction &Inst) const
Emit frame instruction to describe the layout of the frame.
virtual void PrintSpecial (const MachineInstr *MI, raw_ostream &OS, const char *Code) const
virtual bool PrintAsmOperand (const MachineInstr *MI, unsigned OpNo, unsigned AsmVariant, const char *ExtraCode, raw_ostream &OS)
virtual bool PrintAsmMemoryOperand (const MachineInstr *MI, unsigned OpNo, unsigned AsmVariant, const char *ExtraCode, raw_ostream &OS)
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const
createPrinterPass - Get a function printer pass.
virtual void assignPassManager (PMStack &PMS, PassManagerType T)
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Public Attributes
TargetMachine & TM
const MCAsmInfo * MAI
const MCInstrInfo * MII
MCContext & OutContext
MCStreamer & OutStreamer
const MachineFunction * MF
The current machine function.
MachineModuleInfo * MMI
MMI - This is a pointer to the current MachineModuleInfo.
Mangler * Mang
MCSymbol * CurrentFnSym
MCSymbol * CurrentFnSymForSize
Protected Member Functions
AsmPrinter (TargetMachine &TM, MCStreamer &Streamer)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
AsmPrinter - This class is intended to be used as a driving class for all asm writers.
Definition at line 58 of file AsmPrinter.h.
Member Enumeration Documentation
enum llvm::AsmPrinter::CFIMoveType
Enumerator
CFI_M_None
CFI_M_EH
CFI_M_Debug
Definition at line 194 of file AsmPrinter.h.
Constructor & Destructor Documentation
AsmPrinter::AsmPrinter (TargetMachine & TM, MCStreamer & Streamer) explicit protected
Definition at line 96 of file AsmPrinter.cpp.
References CurrentFnSym, CurrentFnSymForSize, llvm::MCStreamer::isVerboseAsm(), MF, and MMI.
AsmPrinter::~AsmPrinter () virtual
Definition at line 108 of file AsmPrinter.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::begin(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::end(), getGCMap(), I, and OutStreamer.
Member Function Documentation
bool AsmPrinter::doFinalization (Module & M) virtual
doFinalization - Shut down the asmprinter. If you override this in your pass, you must make sure to call it explicitly.
Reimplemented from llvm::Pass.
Reimplemented in llvm::NVPTXAsmPrinter.
Definition at line 881 of file AsmPrinter.cpp.
References llvm::MCStreamer::AddBlankLine(), llvm::Module::alias_begin(), llvm::Module::alias_end(), llvm::GCModuleInfo::begin(), llvm::Module::begin(), llvm::MCSymbolRefExpr::Create(), DbgTimerName, llvm::GlobalValue::DefaultVisibility, DWARFGroupName, EHTimerName, llvm::MCStreamer::EmitAssignment(), EmitEndOfAsmFile(), EmitGlobalVariable(), llvm::TargetLoweringObjectFile::emitModuleFlags(), llvm::MCStreamer::EmitSymbolAttribute(), llvm::SmallVectorBase::empty(), llvm::GCModuleInfo::end(), llvm::Module::end(), llvm::DwarfException::EndModule(), llvm::DwarfDebug::endModule(), F(), llvm::MCStreamer::Finish(), llvm::MCStreamer::Flush(), llvm::Module::getFunction(), llvm::Module::getModuleFlagsMetadata(), llvm::MCSymbol::getName(), llvm::MCAsmInfo::getNonexecutableStackSection(), getObjFileLowering(), getSymbol(), llvm::GlobalValue::getVisibility(), llvm::MCAsmInfo::getWeakRefDirective(), llvm::Module::global_begin(), llvm::Module::global_end(), llvm::MCAsmInfo::hasSetDirective(), I, llvm::GlobalValue::isDeclaration(), MAI, Mang, llvm::MCSA_Global, llvm::MCSA_WeakReference, llvm::A64CC::MI, MMI, OutContext, OutStreamer, llvm::report_fatal_error(), llvm::MCStreamer::reset(), S, llvm::MCStreamer::SwitchSection(), T, llvm::TimePassesIsEnabled, TM, and llvm::Value::use_empty().
Referenced by llvm::NVPTXAsmPrinter::doFinalization(), GetAnonSym(), isVerbose(), and stripRegisterPrefix().
bool AsmPrinter::doInitialization (Module & M) virtual
doInitialization - Set up the AsmPrinter when we are working on a new module. If your pass overrides this, it must make sure to explicitly call this implementation.
Reimplemented from llvm::Pass.
Reimplemented in llvm::NVPTXAsmPrinter.
Definition at line 158 of file AsmPrinter.cpp.
References llvm::MCStreamer::AddBlankLine(), llvm::MCStreamer::AddComment(), llvm::GlobalStatus::analyzeGlobal(), llvm::MachineModuleInfo::AnalyzeModule(), llvm::GlobalValue::AppendingLinkage, llvm::ExceptionHandling::ARM, llvm::GlobalValue::AvailableExternallyLinkage, llvm::GCModuleInfo::begin(), llvm::GlobalValue::CommonLinkage, llvm::GlobalValue::DLLExportLinkage, llvm::GlobalValue::DLLImportLinkage, llvm::MCAsmInfo::doesSupportDebugInformation(), llvm::ExceptionHandling::DwarfCFI, llvm::MCStreamer::EmitFileDirective(), EmitStartOfAsmFile(), llvm::MCStreamer::EmitSymbolAttribute(), llvm::GCModuleInfo::end(), llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::ExternalWeakLinkage, llvm::MCAsmInfo::getExceptionHandlingType(), llvm::GlobalValue::getLinkage(), llvm::MCAsmInfo::getLinkOnceDirective(), llvm::Module::getModuleIdentifier(), llvm::Module::getModuleInlineAsm(), getObjFileLowering(), llvm::MCAsmInfo::getWeakDefDirective(), llvm::X86II::GS, llvm::MCAsmInfo::hasSingleParameterDotFile(), llvm::GlobalValue::hasUnnamedAddr(), I, llvm::MCStreamer::InitStreamer(), llvm::GlobalValue::InternalLinkage, llvm::GlobalStatus::IsCompared, llvm::GlobalValue::LinkerPrivateLinkage, llvm::GlobalValue::LinkerPrivateWeakLinkage, llvm::GlobalValue::LinkOnceAnyLinkage, llvm::GlobalValue::LinkOnceODRLinkage, llvm_unreachable, MAI, Mang, llvm::MCSA_Global, llvm::MCSA_Weak, llvm::MCSA_WeakDefAutoPrivate, llvm::MCSA_WeakDefinition, llvm::A64CC::MI, MMI, llvm::ExceptionHandling::None, OutContext, OutStreamer, llvm::GlobalValue::PrivateLinkage, llvm::ExceptionHandling::SjLj, TM, llvm::GlobalValue::WeakAnyLinkage, llvm::GlobalValue::WeakODRLinkage, and llvm::ExceptionHandling::Win64.
Referenced by isVerbose().
void AsmPrinter::EmitAlignment (unsigned NumBits, const GlobalValue * GV = 0) const
EmitAlignment - Emit an alignment directive to the specified power of two boundary. For example, if you pass in 3 here, you will get an 8 byte alignment. If a global value is specified, and if that global has an explicit alignment requested, it will override the alignment request if required for correctness.
Definition at line 1481 of file AsmPrinter.cpp.
References llvm::MCStreamer::EmitCodeAlignment(), llvm::MCStreamer::EmitValueToAlignment(), getCurrentSection(), llvm::TargetMachine::getDataLayout(), getGVAlignmentLog2(), llvm::MCSection::getKind(), llvm::SectionKind::isText(), OutStreamer, and TM.
Referenced by llvm::HexagonAsmPrinter::EmitAlignment(), EmitBasicBlockStart(), EmitCamlGlobal(), EmitConstantPool(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::ARMAsmPrinter::EmitEndOfAsmFile(), llvm::DwarfException::EmitExceptionTable(), EmitFunctionHeader(), EmitGlobalVariable(), llvm::ARMAsmPrinter::EmitInstruction(), EmitJumpTableInfo(), EmitSpecialLLVMGlobal(), and llvm::linkErlangGCPrinter().
void AsmPrinter::EmitBasicBlockStart (const MachineBasicBlock * MBB) const
EmitBasicBlockStart - This method prints the label for the specified MachineBasicBlock, an alignment (if present) and a comment describing it if appropriate.
Definition at line 2128 of file AsmPrinter.cpp.
References llvm::MCStreamer::AddComment(), Align, BB, EmitAlignment(), emitBasicBlockLoopComments(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitRawText(), llvm::MCStreamer::EmitSymbolAttribute(), llvm::MachineModuleInfo::getAddrLabelSymbolToEmit(), llvm::MachineBasicBlock::getAlignment(), llvm::MachineBasicBlock::getBasicBlock(), llvm::MCAsmInfo::getCommentString(), llvm::MCAsmInfo::getHiddenDeclarationVisibilityAttr(), llvm::MCAsmInfo::getHiddenVisibilityAttr(), llvm::MachineBasicBlock::getNumber(), llvm::MCAsmInfo::getProtectedVisibilityAttr(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineBasicBlock::hasAddressTaken(), llvm::MCStreamer::hasRawTextSupport(), llvm::GlobalValue::HiddenVisibility, i, isBlockOnlyReachableByFallthrough(), isVerbose(), MAI, llvm::MCSA_Invalid, MMI, OutStreamer, llvm::MachineBasicBlock::pred_empty(), and llvm::GlobalValue::ProtectedVisibility.
Referenced by EmitFunctionBody().
void AsmPrinter::EmitCFAByte (unsigned Val) const
EmitCFAByte - Emit a .byte 42 directive for a DW_CFA_xxx value.
Definition at line 53 of file AsmPrinterDwarf.cpp.
References llvm::MCStreamer::AddComment(), llvm::dwarf::CallFrameString(), llvm::dwarf::DW_CFA_offset, llvm::MCStreamer::EmitIntValue(), isVerbose(), and OutStreamer.
Referenced by EmitLabelReference().
void AsmPrinter::emitCFIInstruction (const MCCFIInstruction & Inst) const
Emit frame instruction to describe the layout of the frame.
Definition at line 172 of file AsmPrinterDwarf.cpp.
References llvm::MCStreamer::EmitCFIDefCfa(), llvm::MCStreamer::EmitCFIDefCfaOffset(), llvm::MCStreamer::EmitCFIDefCfaRegister(), llvm::MCStreamer::EmitCFIOffset(), llvm::MCStreamer::EmitCFIRegister(), llvm::MCStreamer::EmitCFIWindowSave(), llvm::MCCFIInstruction::getOffset(), llvm::MCCFIInstruction::getOperation(), llvm::MCCFIInstruction::getRegister(), llvm::MCCFIInstruction::getRegister2(), llvm_unreachable, llvm::MCCFIInstruction::OpDefCfa, llvm::MCCFIInstruction::OpDefCfaOffset, llvm::MCCFIInstruction::OpDefCfaRegister, llvm::MCCFIInstruction::OpOffset, llvm::MCCFIInstruction::OpRegister, llvm::MCCFIInstruction::OpWindowSave, and OutStreamer.
Referenced by emitPrologLabel(), and getISAEncoding().
void AsmPrinter::EmitConstantPool () virtual
EmitConstantPool - Print to the current output stream assembly representations of the constants in the constant pool MCP. This is used to print out constants which have been "spilled to memory" by the code generator.
Reimplemented in llvm::MipsAsmPrinter, and llvm::ARMAsmPrinter.
Definition at line 1028 of file AsmPrinter.cpp.
References Align, llvm::MachineConstantPoolEntry::ConstVal, EmitAlignment(), EmitGlobalConstant(), llvm::MCStreamer::EmitLabel(), EmitMachineConstantPoolValue(), llvm::MCStreamer::EmitZeros(), llvm::MachineConstantPoolEntry::getAlignment(), llvm::MachineFunction::getConstantPool(), llvm::MachineConstantPool::getConstants(), GetCPISymbol(), llvm::TargetMachine::getDataLayout(), llvm::SectionKind::getMergeableConst(), llvm::SectionKind::getMergeableConst16(), llvm::SectionKind::getMergeableConst4(), llvm::SectionKind::getMergeableConst8(), getObjFileLowering(), llvm::SectionKind::getReadOnlyWithRel(), llvm::SectionKind::getReadOnlyWithRelLocal(), llvm::MachineConstantPoolEntry::getRelocationInfo(), llvm::TargetLoweringObjectFile::getSectionForConstant(), llvm::MachineConstantPoolEntry::getType(), llvm::DataLayout::getTypeAllocSize(), i, llvm::MachineConstantPoolEntry::isMachineConstantPoolEntry(), j(), llvm_unreachable, llvm::Log2_32(), llvm::MachineConstantPoolEntry::MachineCPVal, MF, OutStreamer, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), S, llvm::SmallVectorTemplateCommon< T >::size(), llvm::MCStreamer::SwitchSection(), TM, and llvm::MachineConstantPoolEntry::Val.
Referenced by llvm::MipsAsmPrinter::EmitConstantPool(), and EmitFunctionHeader().
void AsmPrinter::EmitDwarfRegOp (const MachineLocation & MLoc, bool Indirect) const virtual
EmitDwarfRegOp - Emit dwarf register operation.
Reimplemented in llvm::ARMAsmPrinter.
Definition at line 832 of file AsmPrinter.cpp.
References llvm::MCStreamer::AddComment(), llvm::dwarf::DW_OP_breg0, llvm::dwarf::DW_OP_bregx, llvm::dwarf::DW_OP_deref, llvm::dwarf::DW_OP_reg0, llvm::dwarf::DW_OP_regx, EmitInt8(), EmitSLEB128(), EmitULEB128(), llvm::MCRegisterInfo::getDwarfRegNum(), llvm::MachineLocation::getOffset(), llvm::MachineLocation::getReg(), llvm::TargetMachine::getRegisterInfo(), llvm::MachineLocation::isIndirect(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::dwarf::OperationEncodingString(), OutStreamer, and TM.
Referenced by llvm::DwarfUnits::emitAddresses(), llvm::ARMAsmPrinter::EmitDwarfRegOp(), and getISAEncoding().
void AsmPrinter::EmitEncodingByte (unsigned Val, const char * Desc = 0) const
EmitEncodingByte - Emit a .byte 42 directive that corresponds to an encoding. If verbose assembly output is enabled, we output comments describing the encoding. Desc is a string saying what the encoding is specifying (e.g. "LSDA").
EmitEncodingByte - Emit a .byte 42 directive that corresponds to an encoding. If verbose assembly output is enabled, we output comments describing the encoding. Desc is an optional string saying what the encoding is specifying (e.g. "LSDA").
Definition at line 95 of file AsmPrinterDwarf.cpp.
References llvm::MCStreamer::AddComment(), DecodeDWARFEncoding(), llvm::MCStreamer::EmitIntValue(), isVerbose(), and OutStreamer.
Referenced by llvm::DwarfException::EmitExceptionTable(), and EmitLabelReference().
virtual void llvm::AsmPrinter::EmitEndOfAsmFile (Module &) inline virtual
EmitEndOfAsmFile - This virtual method can be overridden by targets that want to emit something at the end of their file.
Reimplemented in llvm::MipsAsmPrinter, llvm::ARMAsmPrinter, llvm::X86AsmPrinter, llvm::AArch64AsmPrinter, and llvm::SystemZAsmPrinter.
Definition at line 258 of file AsmPrinter.h.
Referenced by doFinalization().
void AsmPrinter::EmitFunctionBody ()
EmitFunctionBody - This method emits the body and trailer for a function.
Definition at line 692 of file AsmPrinter.cpp.
References llvm::MCStreamer::AddBlankLine(), llvm::MCStreamer::AddComment(), BB, llvm::MachineFunction::begin(), llvm::Function::begin(), llvm::DwarfDebug::beginInstruction(), llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateSub(), llvm::MCContext::CreateTempSymbol(), CurrentFnSym, CurrentFnSymForSize, llvm::TargetOpcode::DBG_VALUE, DbgTimerName, DWARFGroupName, llvm::TargetOpcode::EH_LABEL, EHTimerName, EmitBasicBlockStart(), emitComments(), emitDebugValueComment(), llvm::MCStreamer::EmitELFSize(), EmitFunctionBodyEnd(), EmitFunctionBodyStart(), emitImplicitDef(), EmitInstruction(), llvm::MCStreamer::EmitInstruction(), EmitJumpTableInfo(), emitKill(), llvm::MCStreamer::EmitLabel(), emitPrologLabel(), llvm::MCStreamer::EmitRawText(), llvm::MachineFunction::end(), llvm::Function::end(), llvm::DwarfException::EndFunction(), llvm::MachineModuleInfo::EndFunction(), llvm::DwarfDebug::endFunction(), llvm::DwarfDebug::endInstruction(), F(), llvm::TargetOpcode::GC_LABEL, GetBlockAddressSymbol(), llvm::MCStreamer::GetCommentOS(), getCurrentSection(), llvm::MachineFunction::getFunction(), llvm::TargetMachine::getInstrInfo(), llvm::TargetInstrInfo::getNoopForMachoTarget(), llvm::MCInst::getOpcode(), llvm::BasicBlock::hasAddressTaken(), llvm::MachineModuleInfo::hasDebugInfo(), llvm::MCAsmInfo::hasDotTypeDotSizeDirective(), llvm::TargetMachine::hasMCUseLoc(), llvm::MCAsmInfo::hasSubsectionsViaSymbols(), i, I, llvm::ARM_PROC::IE, llvm::TargetOpcode::IMPLICIT_DEF, llvm::TargetOpcode::INLINEASM, llvm::MCSymbol::isDefined(), llvm::MachineInstr::isPrologLabel(), isVerbose(), llvm::TargetOpcode::KILL, MAI, llvm::MCLineEntry::Make(), MF, MMI, OutContext, OutStreamer, llvm::TargetOpcode::PROLOG_LABEL, T, llvm::TimePassesIsEnabled, and TM.
Referenced by llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::X86AsmPrinter::runOnMachineFunction(), and runOnMachineFunction().
virtual void llvm::AsmPrinter::EmitFunctionBodyEnd () inline virtual
EmitFunctionBodyEnd - Targets can override this to emit stuff after the last basic block in the function.
Reimplemented in llvm::MipsAsmPrinter, and llvm::ARMAsmPrinter.
Definition at line 266 of file AsmPrinter.h.
Referenced by EmitFunctionBody().
virtual void llvm::AsmPrinter::EmitFunctionBodyStart () inline virtual
EmitFunctionBodyStart - Targets can override this to emit stuff before the first basic block in the function.
Reimplemented in llvm::MipsAsmPrinter.
Definition at line 262 of file AsmPrinter.h.
Referenced by EmitFunctionBody().
void AsmPrinter::EmitFunctionEntryLabel () virtual
EmitFunctionEntryLabel - Emit the label that is the entrypoint for the function. This can be overridden by targets as required to do custom stuff.
Reimplemented in llvm::MipsAsmPrinter, and llvm::ARMAsmPrinter.
Definition at line 501 of file AsmPrinter.cpp.
References CurrentFnSym, llvm::MCStreamer::EmitLabel(), llvm::MCSymbol::getName(), llvm::MCSymbol::isUndefined(), OutStreamer, and llvm::report_fatal_error().
Referenced by EmitFunctionHeader(), EmitInstruction(), and stripRegisterPrefix().
void AsmPrinter::EmitFunctionHeader ()
EmitFunctionHeader - This method emits the header for the current function.
Definition at line 448 of file AsmPrinter.cpp.
References llvm::MCStreamer::AddComment(), llvm::DwarfException::BeginFunction(), llvm::DwarfDebug::beginFunction(), CurrentFnSym, DbgTimerName, DWARFGroupName, EHTimerName, EmitAlignment(), EmitConstantPool(), EmitFunctionEntryLabel(), EmitGlobalConstant(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitSymbolAttribute(), F(), llvm::MachineFunction::getAlignment(), llvm::MCStreamer::GetCommentOS(), llvm::MachineFunction::getFunction(), getObjFileLowering(), llvm::GlobalValue::getParent(), llvm::Function::getPrefixData(), llvm::GlobalValue::getVisibility(), llvm::MCAsmInfo::hasDotTypeDotSizeDirective(), llvm::Function::hasPrefixData(), i, isVerbose(), MAI, Mang, llvm::MCSA_ELF_TypeFunction, MF, MMI, OutStreamer, llvm::MCStreamer::SwitchSection(), T, llvm::MachineModuleInfo::takeDeletedSymbolsForFunction(), llvm::TimePassesIsEnabled, TM, and llvm::WriteAsOperand().
Referenced by llvm::X86AsmPrinter::runOnMachineFunction(), and runOnMachineFunction().
void AsmPrinter::EmitGlobalConstant (const Constant * CV)
Print a general LLVM constant to the .s file.
EmitGlobalConstant - Print a general LLVM constant to the .s file.
Definition at line 1968 of file AsmPrinter.cpp.
References emitGlobalConstantImpl(), llvm::MCStreamer::EmitIntValue(), llvm::TargetMachine::getDataLayout(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::MCAsmInfo::hasSubsectionsViaSymbols(), MAI, OutStreamer, and TM.
Referenced by EmitConstantPool(), EmitFunctionHeader(), EmitGlobalVariable(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::MipsAsmPrinter::EmitInstruction(), and EmitXXStructor().
void AsmPrinter::EmitGlobalVariable (const GlobalVariable * GV) virtual
EmitGlobalVariable - Emit the specified global variable to the .s file.
Definition at line 282 of file AsmPrinter.cpp.
References llvm::MCStreamer::AddBlankLine(), Align, llvm::MCConstantExpr::Create(), EmitAlignment(), llvm::MCStreamer::EmitCommonSymbol(), llvm::MCStreamer::EmitELFSize(), EmitGlobalConstant(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitLocalCommonSymbol(), EmitSpecialLLVMGlobal(), llvm::MCStreamer::EmitSymbolAttribute(), llvm::MCStreamer::EmitSymbolValue(), llvm::MCStreamer::EmitTBSSSymbol(), llvm::MCStreamer::EmitZerofill(), llvm::MCObjectFileInfo::getCommDirectiveSupportsAlignment(), llvm::MCStreamer::GetCommentOS(), llvm::TargetMachine::getDataLayout(), llvm::SequentialType::getElementType(), GetExternalSymbolSymbol(), getGVAlignmentLog2(), llvm::GlobalVariable::getInitializer(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::MCAsmInfo::getLCOMMDirectiveAlignmentType(), llvm::MCSymbol::getName(), getObjFileLowering(), llvm::MCContext::GetOrCreateSymbol(), llvm::GlobalValue::getParent(), llvm::DataLayout::getPointerTypeSize(), getSymbol(), llvm::MCObjectFileInfo::getTLSBSSSection(), llvm::MCObjectFileInfo::getTLSExtraDataSection(), llvm::GlobalValue::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::GlobalValue::getVisibility(), llvm::MCAsmInfo::hasDotTypeDotSizeDirective(), llvm::GlobalVariable::hasInitializer(), llvm::MCAsmInfo::hasMachoTBSSDirective(), llvm::MCAsmInfo::hasMachoZeroFillDirective(), llvm::SectionKind::isBSSExtern(), llvm::SectionKind::isBSSLocal(), llvm::SectionKind::isCommon(), llvm::GlobalValue::isDeclaration(), llvm::SectionKind::isThreadBSS(), llvm::SectionKind::isThreadData(), llvm::SectionKind::isThreadLocal(), isVerbose(), MAI, Mang, llvm::MCSA_ELF_TypeObject, llvm::MCSA_Global, llvm::MCSA_Local, llvm::LCOMM::NoAlignment, OutContext, OutStreamer, llvm::TargetLoweringObjectFile::SectionForGlobal(), llvm::DwarfDebug::setSymbolSize(), llvm::MCStreamer::SwitchSection(), TM, and llvm::WriteAsOperand().
Referenced by doFinalization().
void AsmPrinter::emitImplicitDef (const MachineInstr * MI) const virtual
emitImplicitDef - Targets can override this to customize the output of IMPLICIT_DEF instructions in verbose mode.
emitImplicitDef - This method emits the specified machine instruction that is an implicit def.
Definition at line 549 of file AsmPrinter.cpp.
References llvm::MCStreamer::AddBlankLine(), llvm::MCStreamer::AddComment(), llvm::MCRegisterInfo::getName(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::TargetMachine::getRegisterInfo(), OutStreamer, and TM.
Referenced by EmitFunctionBody(), and EmitXXStructor().
virtual void llvm::AsmPrinter::EmitInstruction (const MachineInstr *) inline virtual
EmitInstruction - Targets should implement this to emit instructions.
Reimplemented in llvm::MipsAsmPrinter, llvm::ARMAsmPrinter, llvm::X86AsmPrinter, llvm::AArch64AsmPrinter, llvm::AMDGPUAsmPrinter, llvm::HexagonAsmPrinter, and llvm::SystemZAsmPrinter.
Definition at line 269 of file AsmPrinter.h.
References EmitFunctionEntryLabel(), EmitMachineConstantPoolValue(), and llvm_unreachable.
Referenced by EmitFunctionBody().
void AsmPrinter::EmitInt16 (int Value) const
EmitInt16 - Emit a short directive and value.
Definition at line 1389 of file AsmPrinter.cpp.
References llvm::MCStreamer::EmitIntValue(), and OutStreamer.
Referenced by computeIndexValue(), EmitCamlGlobal(), llvm::CompileUnit::emitHeader(), llvm::DIEBlock::EmitValue(), EmitXXStructor(), llvm::DwarfAccelTable::FinalizeTable(), and llvm::linkErlangGCPrinter().
void AsmPrinter::EmitInt32 (int Value) const
EmitInt32 - Emit a long directive and value.
Definition at line 1395 of file AsmPrinter.cpp.
References llvm::MCStreamer::EmitIntValue(), and OutStreamer.
Referenced by computeIndexValue(), llvm::DwarfDebug::emitDIE(), llvm::DwarfUnits::emitUnits(), llvm::DIEEntry::EmitValue(), llvm::DIEBlock::EmitValue(), EmitXXStructor(), and llvm::DwarfAccelTable::FinalizeTable().
void AsmPrinter::EmitInt8 (int Value) const
EmitInt8 - Emit a byte directive and value.
Definition at line 1383 of file AsmPrinter.cpp.
References llvm::MCStreamer::EmitIntValue(), and OutStreamer.
Referenced by computeIndexValue(), llvm::DwarfUnits::emitAddresses(), llvm::DwarfDebug::emitDIE(), llvm::ARMAsmPrinter::EmitDwarfRegOp(), EmitDwarfRegOp(), llvm::CompileUnit::emitHeader(), llvm::DwarfUnits::emitUnits(), llvm::DIEBlock::EmitValue(), EmitXXStructor(), and llvm::DwarfAccelTable::FinalizeTable().
void AsmPrinter::EmitJumpTableInfo ()
EmitJumpTableInfo - Print assembly representations of the jump tables used by the current function to the current output stream.
Definition at line 1108 of file AsmPrinter.cpp.
References llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateSub(), llvm::MachineJumpTableInfo::EK_BlockAddress, llvm::MachineJumpTableInfo::EK_Custom32, llvm::MachineJumpTableInfo::EK_GPRel32BlockAddress, llvm::MachineJumpTableInfo::EK_GPRel64BlockAddress, llvm::MachineJumpTableInfo::EK_Inline, llvm::MachineJumpTableInfo::EK_LabelDifference32, EmitAlignment(), llvm::MCStreamer::EmitAssignment(), llvm::MCStreamer::EmitDataRegion(), llvm::MCStreamer::EmitGPRel32Value(), llvm::MCStreamer::EmitGPRel64Value(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitValue(), F(), llvm::TargetMachine::getDataLayout(), llvm::MachineJumpTableInfo::getEntryAlignment(), llvm::MachineJumpTableInfo::getEntryKind(), llvm::MachineJumpTableInfo::getEntrySize(), llvm::MachineFunction::getFunction(), GetJTISymbol(), GetJTSetSymbol(), llvm::MachineFunction::getJumpTableInfo(), llvm::MachineJumpTableInfo::getJumpTables(), llvm::MCAsmInfo::getLinkerPrivateGlobalPrefix(), llvm::MachineBasicBlock::getNumber(), getObjFileLowering(), llvm::TargetLowering::getPICJumpTableRelocBaseExpr(), llvm::SectionKind::getReadOnly(), llvm::TargetLoweringObjectFile::getSectionForConstant(), llvm::MachineBasicBlock::getSymbol(), llvm::TargetMachine::getTargetLowering(), llvm::MCAsmInfo::hasSetDirective(), llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::GlobalValue::isWeakForLinker(), llvm_unreachable, llvm::Log2_32(), llvm::TargetLowering::LowerCustomJumpTableEntry(), MAI, Mang, llvm::MCDR_DataRegionEnd, llvm::MCDR_DataRegionJT32, MF, OutContext, OutStreamer, llvm::MCStreamer::SwitchSection(), and TM.
Referenced by EmitFunctionBody().
void AsmPrinter::EmitLabelDifference (const MCSymbol * Hi, const MCSymbol * Lo, unsigned Size) const
EmitLabelDifference - Emit something like ".long Hi-Lo" where the size in bytes of the directive is specified by Size and Hi/Lo specify the labels. This implicitly uses .set if it is available.
Definition at line 1402 of file AsmPrinter.cpp.
References llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateSub(), llvm::MCStreamer::EmitAssignment(), llvm::MCStreamer::EmitSymbolValue(), llvm::MCStreamer::EmitValue(), GetTempSymbol(), llvm::MCAsmInfo::hasSetDirective(), MAI, OutContext, and OutStreamer.
Referenced by computeIndexValue(), llvm::DwarfUnits::emitAddresses(), llvm::DwarfDebug::emitDIE(), llvm::DwarfException::EmitExceptionTable(), EmitSectionOffset(), llvm::DIEDelta::EmitValue(), and EmitXXStructor().
void AsmPrinter::EmitLabelOffsetDifference (const MCSymbol * Hi, uint64_t Offset, const MCSymbol * Lo, unsigned Size) const
EmitLabelOffsetDifference - Emit something like ".long Hi+Offset-Lo" where the size in bytes of the directive is specified by Size and Hi/Lo specify the labels. This implicitly uses .set if it is available.
Definition at line 1424 of file AsmPrinter.cpp.
References llvm::MCConstantExpr::Create(), llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateAdd(), llvm::MCBinaryExpr::CreateSub(), llvm::MCStreamer::EmitAssignment(), llvm::MCStreamer::EmitSymbolValue(), llvm::MCStreamer::EmitValue(), GetTempSymbol(), llvm::MCAsmInfo::hasSetDirective(), MAI, OutContext, and OutStreamer.
Referenced by llvm::DwarfDebug::emitDIE(), and EmitXXStructor().
void AsmPrinter::EmitLabelPlusOffset (const MCSymbol * Label, uint64_t Offset, unsigned Size, bool IsSectionRelative = false) const
EmitLabelPlusOffset - Emit something like ".long Label+Offset" where the size in bytes of the directive is specified by Size and Label specifies the label. This implicitly uses .set if it is available.
Definition at line 1454 of file AsmPrinter.cpp.
References llvm::MCConstantExpr::Create(), llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateAdd(), llvm::MCStreamer::EmitCOFFSecRel32(), llvm::MCStreamer::EmitValue(), MAI, llvm::MCAsmInfo::needsDwarfSectionOffsetDirective(), OutContext, and OutStreamer.
Referenced by llvm::DwarfDebug::emitDIE(), EmitLabelReference(), EmitXXStructor(), and llvm::linkErlangGCPrinter().
void llvm::AsmPrinter::EmitLabelReference (const MCSymbol * Label, unsigned Size, bool IsSectionRelative = false) const inline
EmitLabelReference - Emit something like ".long Label" where the size in bytes of the directive is specified by Size and Label specifies the label.
Definition at line 375 of file AsmPrinter.h.
References EmitCFAByte(), EmitEncodingByte(), EmitLabelPlusOffset(), EmitSectionOffset(), EmitSLEB128(), EmitTTypeReference(), EmitULEB128(), and GetSizeOfEncodedValue().
Referenced by llvm::DIELabel::EmitValue().
void AsmPrinter::EmitMachineConstantPoolValue (MachineConstantPoolValue * MCPV) virtual
Reimplemented in llvm::ARMAsmPrinter, and llvm::SystemZAsmPrinter.
Definition at line 1979 of file AsmPrinter.cpp.
References llvm_unreachable.
Referenced by EmitConstantPool(), llvm::MipsAsmPrinter::EmitInstruction(), and EmitInstruction().
void AsmPrinter::emitPrologLabel (const MachineInstr & MI)
Definition at line 664 of file AsmPrinter.cpp.
References CFI_M_None, llvm::ExceptionHandling::DwarfCFI, emitCFIInstruction(), llvm::MCStreamer::EmitCompactUnwindEncoding(), llvm::MachineModuleInfo::getCompactUnwindEncoding(), llvm::MCAsmInfo::getExceptionHandlingType(), llvm::MachineModuleInfo::getFrameInstructions(), llvm::MachineOperand::getMCSymbol(), llvm::MachineFunction::getMMI(), llvm::MachineInstr::getOperand(), I, MAI, MF, MMI, needsCFIMoves(), and OutStreamer.
Referenced by EmitFunctionBody(), and runOnMachineFunction().
void AsmPrinter::EmitSectionOffset (const MCSymbol * Label, const MCSymbol * SectionLabel) const
EmitSectionOffset - Emit the 4-byte offset of Label from the start of its section. This can be done with a special directive if the target supports it (e.g. cygwin) or by emitting it as an offset from a label at the start of the section.
SectionLabel is a temporary label emitted at the start of the section that Label lives in.
Definition at line 141 of file AsmPrinterDwarf.cpp.
References llvm::MCStreamer::EmitCOFFSecRel32(), EmitLabelDifference(), llvm::MCStreamer::EmitSymbolValue(), llvm::MCSymbol::getSection(), llvm::MCSection::isBaseAddressKnownZero(), llvm::MCSymbol::isInSection(), MAI, llvm::MCAsmInfo::needsDwarfSectionOffsetDirective(), OutStreamer, and llvm::ARMBuildAttrs::Section.
Referenced by computeIndexValue(), llvm::DwarfDebug::emitDIE(), llvm::CompileUnit::emitHeader(), EmitLabelReference(), and llvm::DwarfAccelTable::FinalizeTable().
void AsmPrinter::EmitSLEB128 (int64_t Value, const char * Desc = 0) const
EmitSLEB128 - emit the specified signed leb128 value.
Definition at line 36 of file AsmPrinterDwarf.cpp.
References llvm::MCStreamer::AddComment(), llvm::MCStreamer::EmitSLEB128IntValue(), isVerbose(), and OutStreamer.
Referenced by llvm::DwarfUnits::emitAddresses(), EmitDwarfRegOp(), llvm::DwarfException::EmitExceptionTable(), EmitLabelReference(), and llvm::DIEInteger::EmitValue().
bool AsmPrinter::EmitSpecialLLVMGlobal (const GlobalVariable * GV)
EmitSpecialLLVMGlobal - Check to see if the specified global is a special global used by LLVM. If so, emit it and return true, otherwise do nothing and return false.
Definition at line 1261 of file AsmPrinter.cpp.
References Align, llvm::SmallVectorTemplateCommon< T >::begin(), llvm::dyn_cast(), EmitAlignment(), llvm::MCStreamer::EmitIdent(), llvm::MCStreamer::EmitSymbolAttribute(), EmitXXStructor(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::MCStreamer::getCurrentSection(), llvm::TargetMachine::getDataLayout(), llvm::SequentialType::getElementType(), llvm::GlobalVariable::getInitializer(), llvm::ConstantInt::getLimitedValue(), llvm::Value::getName(), llvm::Module::getNamedMetadata(), llvm::StructType::getNumElements(), llvm::User::getNumOperands(), llvm::MDNode::getNumOperands(), getObjFileLowering(), llvm::User::getOperand(), llvm::MDNode::getOperand(), llvm::MCContext::GetOrCreateSymbol(), llvm::DataLayout::getPointerPrefAlignment(), llvm::MCStreamer::getPreviousSection(), llvm::TargetMachine::getRelocationModel(), llvm::GlobalValue::getSection(), llvm::TargetLoweringObjectFile::getStaticCtorSection(), llvm::TargetLoweringObjectFile::getStaticDtorSection(), getSymbol(), llvm::ConstantArray::getType(), llvm::CompositeType::getTypeAtIndex(), llvm::GlobalValue::hasAppendingLinkage(), llvm::GlobalValue::hasAvailableExternallyLinkage(), llvm::MCAsmInfo::hasIdentDirective(), llvm::GlobalVariable::hasInitializer(), llvm::MCAsmInfo::hasNoDeadStrip(), llvm::MCAsmInfo::hasStaticCtorDtorReferenceInStaticMode(), i, llvm::tgtok::List, llvm::Log2_32(), M, MAI, Mang, llvm::MCSA_NoDeadStrip, llvm::MCSA_Reference, N, OutContext, OutStreamer, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), S, llvm::TargetLoweringObjectFile::shouldEmitUsedDirectiveFor(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::Reloc::Static, llvm::Value::stripPointerCasts(), llvm::MCStreamer::SwitchSection(), and TM.
Referenced by EmitGlobalVariable().
virtual void llvm::AsmPrinter::EmitStartOfAsmFile (Module &) inline virtual
EmitStartOfAsmFile - This virtual method can be overridden by targets that want to emit something at the start of their file.
Reimplemented in llvm::MipsAsmPrinter, llvm::ARMAsmPrinter, and llvm::X86AsmPrinter.
Definition at line 254 of file AsmPrinter.h.
Referenced by doInitialization(), and llvm::HexagonAsmPrinter::printSymbolLo().
void AsmPrinter::EmitTTypeReference (const GlobalValue * GV, unsigned Encoding) const
EmitReference - Emit reference to a ttype global with a specified encoding.
Definition at line 122 of file AsmPrinterDwarf.cpp.
References llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitValue(), getObjFileLowering(), GetSizeOfEncodedValue(), llvm::TargetLoweringObjectFile::getTTypeGlobalReference(), Mang, MMI, and OutStreamer.
Referenced by EmitLabelReference(), llvm::DwarfException::EmitTypeInfos(), and llvm::ARMException::EndFunction().
void AsmPrinter::EmitULEB128 (uint64_t Value, const char * Desc = 0, unsigned PadTo = 0) const
EmitULEB128 - emit the specified unsigned leb128 value.
EmitULEB128 - emit the specified signed leb128 value.
Definition at line 44 of file AsmPrinterDwarf.cpp.
References llvm::MCStreamer::AddComment(), llvm::MCStreamer::EmitULEB128IntValue(), isVerbose(), and OutStreamer.
Referenced by llvm::DIEAbbrev::Emit(), llvm::DwarfUnits::emitAddresses(), llvm::DwarfDebug::emitDIE(), llvm::ARMAsmPrinter::EmitDwarfRegOp(), EmitDwarfRegOp(), llvm::DwarfException::EmitExceptionTable(), EmitLabelReference(), llvm::DwarfException::EmitTypeInfos(), llvm::DwarfUnits::emitUnits(), llvm::DIEInteger::EmitValue(), and llvm::DIEBlock::EmitValue().
virtual void llvm::AsmPrinter::EmitXXStructor (const Constant * CV) inline virtual
EmitXXStructor - Targets can override this to change how global constants that are part of a C++ static/global constructor list are emitted.
Reimplemented in llvm::ARMAsmPrinter.
Definition at line 280 of file AsmPrinter.h.
References BB, EmitGlobalConstant(), emitImplicitDef(), EmitInt16(), EmitInt32(), EmitInt8(), EmitLabelDifference(), EmitLabelOffsetDifference(), EmitLabelPlusOffset(), GetBlockAddressSymbol(), GetCPISymbol(), GetExternalSymbolSymbol(), GetJTISymbol(), GetJTSetSymbol(), GetSymbolWithGlobalValueBase(), GetTempSymbol(), llvm::HexagonISD::Hi, isBlockOnlyReachableByFallthrough(), llvm::HexagonISD::Lo, and printOffset().
Referenced by EmitSpecialLLVMGlobal().
void AsmPrinter::getAnalysisUsage (AnalysisUsage & AU) const virtual
getAnalysisUsage - Record analysis usage.
Reimplemented from llvm::MachineFunctionPass.
Definition at line 149 of file AsmPrinter.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::MachineFunctionPass::getAnalysisUsage(), isVerbose(), and llvm::AnalysisUsage::setPreservesAll().
Referenced by isVerbose().
MCSymbol * AsmPrinter::GetBlockAddressSymbol (const BlockAddress * BA) const
GetBlockAddressSymbol - Return the MCSymbol used to satisfy BlockAddress uses of the specified basic block.
Definition at line 2010 of file AsmPrinter.cpp.
References llvm::MachineModuleInfo::getAddrLabelSymbol(), llvm::BlockAddress::getBasicBlock(), and MMI.
Referenced by EmitFunctionBody(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), EmitXXStructor(), llvm::MSP430MCInstLower::GetBlockAddressSymbol(), llvm::SystemZMCInstLower::getExpr(), llvm::HexagonLowerToMC(), llvm::XCoreMCInstLower::Initialize(), llvm::MipsMCInstLower::Initialize(), nvptx::LowerConstant(), lowerConstant(), llvm::AArch64AsmPrinter::lowerOperand(), llvm::ARMAsmPrinter::lowerOperand(), llvm::LowerPPCMachineInstrToMCInst(), llvm::MipsAsmPrinter::printOperand(), llvm::AArch64AsmPrinter::printSymbolicAddress(), and SimplifyShortMoveForm().
MCSymbol * AsmPrinter::GetBlockAddressSymbol (const BasicBlock * BB) const
Definition at line 2014 of file AsmPrinter.cpp.
References llvm::MachineModuleInfo::getAddrLabelSymbol(), and MMI.
MCSymbol * AsmPrinter::GetCPISymbol (unsigned CPID) const
GetCPISymbol - Return the symbol for the specified constant pool entry.
Definition at line 2019 of file AsmPrinter.cpp.
References getFunctionNumber(), llvm::MCContext::GetOrCreateSymbol(), llvm::MCAsmInfo::getPrivateGlobalPrefix(), MAI, and OutContext.
Referenced by EmitConstantPool(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::MipsAsmPrinter::EmitInstruction(), EmitXXStructor(), llvm::SystemZMCInstLower::getExpr(), llvm::HexagonLowerToMC(), llvm::XCoreMCInstLower::Initialize(), llvm::MipsMCInstLower::Initialize(), llvm::AArch64AsmPrinter::lowerOperand(), llvm::ARMAsmPrinter::lowerOperand(), llvm::LowerPPCMachineInstrToMCInst(), llvm::HexagonAsmPrinter::printConstantPool(), llvm::HexagonAsmPrinter::printOperand(), llvm::ARMAsmPrinter::printOperand(), llvm::AArch64AsmPrinter::printSymbolicAddress(), llvm::X86AsmPrinter::printSymbolOperand(), and SimplifyShortMoveForm().
const MCSection * AsmPrinter::getCurrentSection () const
getCurrentSection() - Return the current section we are emitting to.
Definition at line 143 of file AsmPrinter.cpp.
References llvm::MCStreamer::getCurrentSection(), and OutStreamer.
Referenced by EmitAlignment(), EmitFunctionBody(), and isVerbose().
const DataLayout & AsmPrinter::getDataLayout () const
getDataLayout - Return information about data layout.
Definition at line 134 of file AsmPrinter.cpp.
References llvm::TargetMachine::getDataLayout(), and TM.
Referenced by llvm::CompileUnit::addConstantFPValue(), llvm::CompileUnit::addConstantValue(), llvm::CompileUnit::constructVariableDIE(), llvm::CompileUnit::createGlobalVariableDIE(), llvm::DwarfUnits::emitAddresses(), llvm::DwarfException::EmitExceptionTable(), llvm::CompileUnit::emitHeader(), llvm::DwarfUnits::emitUnits(), llvm::DIEInteger::EmitValue(), llvm::DIEEntry::getRefAddrSize(), llvm::DwarfDebug::isSubprogramContext(), isVerbose(), llvm::DIEInteger::SizeOf(), llvm::DIEExpr::SizeOf(), llvm::DIELabel::SizeOf(), and llvm::DIEDelta::SizeOf().
const DwarfDebug* llvm::AsmPrinter::getDwarfDebug () const inline
Definition at line 126 of file AsmPrinter.h.
Referenced by llvm::DIEEntry::getRefAddrSize().
MCSymbol * AsmPrinter::GetExternalSymbolSymbol (StringRef Sym) const
GetExternalSymbolSymbol - Return the MCSymbol for the specified ExternalSymbol.
Definition at line 2052 of file AsmPrinter.cpp.
References llvm::Mangler::getNameWithPrefix(), llvm::MCContext::GetOrCreateSymbol(), Mang, OutContext, and llvm::SmallString< InternalLen >::str().
Referenced by llvm::Win64Exception::BeginFunction(), EmitGlobalVariable(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), EmitXXStructor(), llvm::SystemZMCInstLower::getExpr(), llvm::MSP430MCInstLower::GetExternalSymbolSymbol(), llvm::HexagonLowerToMC(), llvm::MipsMCInstLower::Initialize(), llvm::XCoreMCInstLower::Initialize(), llvm::AArch64AsmPrinter::lowerOperand(), llvm::ARMAsmPrinter::lowerOperand(), llvm::HexagonAsmPrinter::printOperand(), llvm::ARMAsmPrinter::printOperand(), llvm::MipsAsmPrinter::printOperand(), and llvm::X86AsmPrinter::printSymbolOperand().
unsigned AsmPrinter::getFunctionNumber () const
getFunctionNumber - Return a unique ID for the current function.
Definition at line 125 of file AsmPrinter.cpp.
References llvm::MachineFunction::getFunctionNumber(), and MF.
Referenced by llvm::DwarfCFIException::BeginFunction(), llvm::ARMException::BeginFunction(), llvm::Win64Exception::BeginFunction(), llvm::DwarfDebug::beginFunction(), emitBasicBlockLoopComments(), llvm::DwarfException::EmitExceptionTable(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), llvm::DwarfCFIException::EndFunction(), llvm::ARMException::EndFunction(), llvm::Win64Exception::EndFunction(), llvm::DwarfDebug::endFunction(), llvm::MSP430MCInstLower::GetConstantPoolIndexSymbol(), GetCPISymbol(), GetJTSetSymbol(), llvm::MSP430MCInstLower::GetJumpTableSymbol(), llvm::DwarfDebug::isSubprogramContext(), isVerbose(), llvm::ARMAsmPrinter::printOperand(), and llvm::MipsAsmPrinter::printOperand().
virtual unsigned llvm::AsmPrinter::getISAEncoding () inline virtual
getISAEncoding - Get the value for DW_AT_APPLE_isa. Zero if no isa encoding specified.
Reimplemented in llvm::ARMAsmPrinter.
Definition at line 418 of file AsmPrinter.h.
References llvm::InlineAsm::AD_ATT, llvm::tgtok::Code, emitCFIInstruction(), EmitDwarfRegOp(), llvm::tgtok::List, PrintAsmMemoryOperand(), PrintAsmOperand(), and PrintSpecial().
Referenced by llvm::CompileUnit::getOrCreateSubprogramDIE().
MCSymbol * AsmPrinter::GetJTISymbol (unsigned JTID, bool isLinkerPrivate = false) const
GetJTISymbol - Return the symbol for the specified jump table entry.
Definition at line 2026 of file AsmPrinter.cpp.
References llvm::MachineFunction::getJTISymbol(), MF, and OutContext.
Referenced by EmitJumpTableInfo(), EmitXXStructor(), llvm::SystemZMCInstLower::getExpr(), llvm::HexagonLowerToMC(), llvm::MipsMCInstLower::Initialize(), llvm::XCoreMCInstLower::Initialize(), llvm::AArch64AsmPrinter::lowerOperand(), llvm::ARMAsmPrinter::lowerOperand(), llvm::LowerPPCMachineInstrToMCInst(), llvm::HexagonAsmPrinter::printJumpTable(), llvm::HexagonAsmPrinter::printOperand(), llvm::ARMAsmPrinter::printOperand(), llvm::X86AsmPrinter::printSymbolOperand(), and SimplifyShortMoveForm().
MCSymbol * AsmPrinter::GetJTSetSymbol (unsigned UID, unsigned MBBID) const
GetJTSetSymbol - Return the symbol for the specified jump table .set FIXME: privatize to AsmPrinter.
Definition at line 2032 of file AsmPrinter.cpp.
References getFunctionNumber(), llvm::MCContext::GetOrCreateSymbol(), llvm::MCAsmInfo::getPrivateGlobalPrefix(), MAI, and OutContext.
Referenced by EmitJumpTableInfo(), and EmitXXStructor().
const TargetLoweringObjectFile & AsmPrinter::getObjFileLowering () const
getObjFileLowering - Return information about object file lowering.
Definition at line 129 of file AsmPrinter.cpp.
References llvm::TargetLoweringBase::getObjFileLowering(), llvm::TargetMachine::getTargetLowering(), and TM.
Referenced by llvm::DwarfCFIException::BeginFunction(), llvm::Win64Exception::BeginFunction(), llvm::DwarfDebug::beginModule(), computeIndexValue(), llvm::DwarfUnits::computeSizeAndOffsets(), llvm::CompileUnit::createGlobalVariableDIE(), doFinalization(), doInitialization(), llvm::DwarfUnits::emitAddresses(), EmitCamlGlobal(), EmitConstantPool(), llvm::SystemZAsmPrinter::EmitEndOfAsmFile(), llvm::AArch64AsmPrinter::EmitEndOfAsmFile(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::ARMAsmPrinter::EmitEndOfAsmFile(), llvm::MipsAsmPrinter::EmitEndOfAsmFile(), llvm::DwarfException::EmitExceptionTable(), EmitFunctionHeader(), EmitGlobalVariable(), EmitJumpTableInfo(), EmitSpecialLLVMGlobal(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), llvm::ARMAsmPrinter::EmitStartOfAsmFile(), EmitTTypeReference(), llvm::DwarfUnits::emitUnits(), llvm::Win64Exception::EndFunction(), llvm::DwarfCFIException::EndModule(), llvm::DwarfDebug::endModule(), getArchForCPU(), getSymbol(), isVerbose(), llvm::linkErlangGCPrinter(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), and llvm::MipsAsmPrinter::runOnMachineFunction().
unsigned AsmPrinter::GetSizeOfEncodedValue (unsigned Encoding) const
GetSizeOfEncodedValue - Return the size of the encoding in bytes.
Definition at line 109 of file AsmPrinterDwarf.cpp.
References llvm::dwarf::DW_EH_PE_absptr, llvm::dwarf::DW_EH_PE_omit, llvm::dwarf::DW_EH_PE_udata2, llvm::dwarf::DW_EH_PE_udata4, llvm::dwarf::DW_EH_PE_udata8, llvm::TargetMachine::getDataLayout(), llvm::DataLayout::getPointerSize(), llvm_unreachable, and TM.
Referenced by llvm::DwarfException::EmitExceptionTable(), EmitLabelReference(), and EmitTTypeReference().
MCSymbol * AsmPrinter::getSymbol (const GlobalValue * GV) const
Definition at line 277 of file AsmPrinter.cpp.
References getObjFileLowering(), llvm::TargetLoweringObjectFile::getSymbol(), and Mang.
Referenced by llvm::CompileUnit::createGlobalVariableDIE(), doFinalization(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), EmitGlobalVariable(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::SystemZAsmPrinter::EmitMachineConstantPoolValue(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), EmitSpecialLLVMGlobal(), llvm::ARMAsmPrinter::EmitXXStructor(), llvm::ARMException::EndFunction(), llvm::DwarfCFIException::EndModule(), llvm::SystemZMCInstLower::getExpr(), llvm::MSP430MCInstLower::GetGlobalAddressSymbol(), getModifierVariantKind(), GetSymbolFromOperand(), llvm::HexagonLowerToMC(), llvm::XCoreMCInstLower::Initialize(), llvm::MipsMCInstLower::Initialize(), isVerbose(), nvptx::LowerConstant(), lowerConstant(), llvm::AArch64AsmPrinter::lowerOperand(), llvm::ARMAsmPrinter::lowerOperand(), llvm::HexagonAsmPrinter::printGlobalOperand(), llvm::HexagonAsmPrinter::printOperand(), llvm::ARMAsmPrinter::printOperand(), llvm::MipsAsmPrinter::printOperand(), llvm::AArch64AsmPrinter::printSymbolicAddress(), llvm::X86AsmPrinter::printSymbolOperand(), SetupMachineFunction(), and shouldCreateTypeUnit().
MCSymbol * AsmPrinter::GetSymbolWithGlobalValueBase (const GlobalValue * GV, StringRef Suffix, bool ForcePrivate = true) const
GetSymbolWithGlobalValueBase - Return the MCSymbol for a symbol with global value name as its base, with the specified suffix, and where the symbol is forced to have private linkage if ForcePrivate is true.
Definition at line 2041 of file AsmPrinter.cpp.
References llvm::SmallString< InternalLen >::append(), llvm::StringRef::begin(), llvm::StringRef::end(), llvm::Mangler::getNameWithPrefix(), llvm::MCContext::GetOrCreateSymbol(), Mang, OutContext, and llvm::SmallString< InternalLen >::str().
Referenced by EmitXXStructor(), getModifierVariantKind(), and llvm::X86AsmPrinter::printSymbolOperand().
StringRef AsmPrinter::getTargetTriple () const
getTargetTriple - Return the target triple string.
Definition at line 138 of file AsmPrinter.cpp.
References llvm::TargetMachine::getTargetTriple(), and TM.
Referenced by llvm::DwarfDebug::DwarfDebug(), and isVerbose().
MCSymbol * AsmPrinter::GetTempSymbol (StringRef Name, unsigned ID) const
GetTempSymbol - Return the MCSymbol corresponding to the assembler temporary label with the specified stem and unique ID.
Definition at line 1997 of file AsmPrinter.cpp.
References llvm::MCContext::GetOrCreateSymbol(), llvm::MCAsmInfo::getPrivateGlobalPrefix(), MAI, and OutContext.
Referenced by llvm::DwarfCFIException::BeginFunction(), llvm::ARMException::BeginFunction(), llvm::Win64Exception::BeginFunction(), llvm::DwarfDebug::beginFunction(), computeIndexValue(), llvm::CompileUnit::constructVariableDIE(), llvm::DwarfUnits::emitAddresses(), llvm::DwarfException::EmitExceptionTable(), llvm::CompileUnit::emitHeader(), EmitLabelDifference(), EmitLabelOffsetDifference(), emitSectionSym(), llvm::DwarfUnits::emitUnits(), EmitXXStructor(), llvm::DwarfCFIException::EndFunction(), llvm::ARMException::EndFunction(), llvm::Win64Exception::EndFunction(), llvm::DwarfDebug::endFunction(), llvm::DwarfAccelTable::FinalizeTable(), llvm::DwarfDebug::getOrCreateSourceID(), llvm::DwarfUnits::getStringPoolEntry(), llvm::DwarfUnits::getStringPoolIndex(), llvm::DwarfUnits::getStringPoolSym(), llvm::DwarfDebug::isSubprogramContext(), and shouldAddODRHash().
MCSymbol * AsmPrinter::GetTempSymbol (StringRef Name) const
GetTempSymbol - Return an assembler temporary label with the specified stem.
Definition at line 2004 of file AsmPrinter.cpp.
References llvm::MCContext::GetOrCreateSymbol(), llvm::MCAsmInfo::getPrivateGlobalPrefix(), MAI, and OutContext.
bool AsmPrinter::isBlockOnlyReachableByFallthrough (const MachineBasicBlock * MBB) const virtual
isBlockOnlyReachableByFallthough - Return true if the basic block has exactly one predecessor and the control transfer mechanism between the predecessor and this block is a fall-through.
Reimplemented in llvm::MipsAsmPrinter, and llvm::HexagonAsmPrinter.
Definition at line 2193 of file AsmPrinter.cpp.
References llvm::Registry< T, U >::begin(), llvm::MachineBasicBlock::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::end(), llvm::Registry< T, U >::end(), llvm::MachineBasicBlock::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::find(), llvm::MachineBasicBlock::getFirstTerminator(), getGCMap(), llvm::MachineOperand::getMBB(), llvm::GCStrategy::getName(), I, llvm::ARM_PROC::IE, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::insert(), llvm::MachineInstr::isBranch(), llvm::MachineInstr::isIndirectBranch(), llvm::MachineOperand::isJTI(), llvm::MachineBasicBlock::isLandingPad(), llvm::MachineBasicBlock::isLayoutSuccessor(), llvm::MachineOperand::isMBB(), llvm::A64CC::MI, OP, llvm::MachineInstr::operands_begin(), llvm::MachineInstr::operands_end(), llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_empty(), llvm::MachineBasicBlock::pred_end(), llvm::report_fatal_error(), S, llvm::LibFunc::strcmp, and llvm::GCStrategy::usesMetadata().
Referenced by EmitBasicBlockStart(), EmitXXStructor(), and llvm::HexagonAsmPrinter::isBlockOnlyReachableByFallthrough().
bool llvm::AsmPrinter::isVerbose () const inline
isVerbose - Return true if assembly output should contain comments.
Definition at line 130 of file AsmPrinter.h.
References doFinalization(), doInitialization(), getAnalysisUsage(), getCurrentSection(), getDataLayout(), getFunctionNumber(), getObjFileLowering(), getSymbol(), getTargetTriple(), and M.
Referenced by computeIndexValue(), EmitBasicBlockStart(), EmitCFAByte(), llvm::DwarfDebug::emitDIE(), EmitEncodingByte(), EmitFunctionBody(), EmitFunctionHeader(), emitGlobalConstantDataSequential(), emitGlobalConstantFP(), emitGlobalConstantImpl(), EmitGlobalVariable(), EmitSLEB128(), EmitULEB128(), getAnalysisUsage(), and SetupMachineFunction().
AsmPrinter::CFIMoveType AsmPrinter::needsCFIMoves ()
Definition at line 644 of file AsmPrinter.cpp.
References CFI_M_Debug, CFI_M_EH, CFI_M_None, llvm::ExceptionHandling::DwarfCFI, llvm::MCAsmInfo::getExceptionHandlingType(), llvm::MachineFunction::getFunction(), llvm::MachineModuleInfo::hasDebugInfo(), MAI, MF, MMI, and llvm::Function::needsUnwindTableEntry().
Referenced by llvm::DwarfCFIException::BeginFunction(), and emitPrologLabel().
bool AsmPrinter::needsRelocationsForDwarfStringPool () const
needsRelocationsForDwarfStringPool - Specifies whether the object format expects to use relocations to refer to debug entries. Alternatively we emit section offsets in bytes from the start of the string pool.
Definition at line 660 of file AsmPrinter.cpp.
References llvm::MCAsmInfo::doesDwarfUseRelocationsAcrossSections(), and MAI.
Referenced by llvm::CompileUnit::addLocalString(), and llvm::CompileUnit::addString().
bool AsmPrinter::needsSEHMoves ()
Definition at line 655 of file AsmPrinter.cpp.
References llvm::MCAsmInfo::getExceptionHandlingType(), llvm::MachineFunction::getFunction(), MAI, MF, llvm::Function::needsUnwindTableEntry(), and llvm::ExceptionHandling::Win64.
Referenced by llvm::Win64Exception::BeginFunction().
bool AsmPrinter::PrintAsmMemoryOperand (const MachineInstr * MI, unsigned OpNo, unsigned AsmVariant, const char * ExtraCode, raw_ostream & OS) virtual
PrintAsmMemoryOperand - Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address. Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Reimplemented in llvm::MipsAsmPrinter, llvm::X86AsmPrinter, llvm::ARMAsmPrinter, llvm::AArch64AsmPrinter, llvm::HexagonAsmPrinter, and llvm::SystemZAsmPrinter.
Definition at line 547 of file AsmPrinterInlineAsm.cpp.
Referenced by EmitGCCInlineAsmStr(), EmitMSInlineAsmStr(), and getISAEncoding().
bool AsmPrinter::PrintAsmOperand (const MachineInstr * MI, unsigned OpNo, unsigned AsmVariant, const char * ExtraCode, raw_ostream & O) virtual
PrintAsmOperand - Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant. Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
PrintAsmOperand - Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant. Targets should override this to format as appropriate.
Reimplemented in llvm::MipsAsmPrinter, llvm::X86AsmPrinter, llvm::ARMAsmPrinter, llvm::AArch64AsmPrinter, llvm::HexagonAsmPrinter, and llvm::SystemZAsmPrinter.
Definition at line 521 of file AsmPrinterInlineAsm.cpp.
References llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getType(), and llvm::MachineOperand::MO_Immediate.
Referenced by EmitGCCInlineAsmStr(), EmitMSInlineAsmStr(), getISAEncoding(), llvm::NVPTXAsmPrinter::ignoreLoc(), llvm::HexagonAsmPrinter::PrintAsmOperand(), llvm::AArch64AsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::PrintAsmOperand(), llvm::X86AsmPrinter::PrintAsmOperand(), llvm::MipsAsmPrinter::PrintAsmOperand(), and stripRegisterPrefix().
void AsmPrinter::printOffset (int64_t Offset, raw_ostream & OS) const
printOffset - This is just convenient handler for printing offsets.
Definition at line 1984 of file AsmPrinter.cpp.
Referenced by EmitXXStructor(), llvm::HexagonAsmPrinter::printOperand(), llvm::ARMAsmPrinter::printOperand(), and llvm::X86AsmPrinter::printSymbolOperand().
void AsmPrinter::PrintSpecial (const MachineInstr * MI, raw_ostream & OS, const char * Code) const virtual
PrintSpecial - Print information related to the specified machine instr that is independent of the operand, and may be independent of the instr itself. This can be useful for portably encoding the comment character or other bits of target-specific knowledge into the asmstrings. The syntax used is ${:comment}. Targets can override this to add support for their own strange codes.
Definition at line 492 of file AsmPrinterInlineAsm.cpp.
References llvm::A64CC::MI, llvm::report_fatal_error(), llvm::raw_string_ostream::str(), and llvm::LibFunc::strcmp.
Referenced by EmitGCCInlineAsmStr(), and getISAEncoding().
virtual bool llvm::AsmPrinter::runOnMachineFunction (MachineFunction & MF) inline virtual
runOnMachineFunction - Emit the specified function out to the OutStreamer.
Implements llvm::MachineFunctionPass.
Reimplemented in llvm::X86AsmPrinter, llvm::MipsAsmPrinter, llvm::AArch64AsmPrinter, llvm::ARMAsmPrinter, and llvm::AMDGPUAsmPrinter.
Definition at line 169 of file AsmPrinter.h.
References EmitFunctionBody(), EmitFunctionHeader(), emitPrologLabel(), llvm::A64CC::MI, and SetupMachineFunction().
Referenced by llvm::ARMAsmPrinter::runOnMachineFunction(), llvm::AArch64AsmPrinter::runOnMachineFunction(), and llvm::MipsAsmPrinter::runOnMachineFunction().
void AsmPrinter::SetupMachineFunction (MachineFunction & MF)
SetupMachineFunction - This should be called when a new MachineFunction is being processed from runOnMachineFunction.
Definition at line 1003 of file AsmPrinter.cpp.
References CurrentFnSym, CurrentFnSymForSize, llvm::MachineFunction::getFunction(), getSymbol(), isVerbose(), MF, S, and s.
Referenced by llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::X86AsmPrinter::runOnMachineFunction(), and runOnMachineFunction().
Member Data Documentation
MCSymbol* llvm::AsmPrinter::CurrentFnSym
The symbol for the current function. This is recalculated at the beginning of each call to runOnMachineFunction().
Definition at line 93 of file AsmPrinter.h.
Referenced by AsmPrinter(), llvm::Win64Exception::BeginFunction(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), EmitFunctionBody(), llvm::MipsAsmPrinter::EmitFunctionBodyEnd(), llvm::ARMAsmPrinter::EmitFunctionEntryLabel(), llvm::MipsAsmPrinter::EmitFunctionEntryLabel(), EmitFunctionEntryLabel(), EmitFunctionHeader(), llvm::X86AsmPrinter::runOnMachineFunction(), and SetupMachineFunction().
MCSymbol* llvm::AsmPrinter::CurrentFnSymForSize
The symbol used to represent the start of the current function for the purpose of calculating its size (e.g. using the .size directive). By default, this is equal to CurrentFnSym.
Definition at line 98 of file AsmPrinter.h.
Referenced by AsmPrinter(), EmitFunctionBody(), and SetupMachineFunction().
const MCAsmInfo* llvm::AsmPrinter::MAI
Target Asm Printer information.
Definition at line 66 of file AsmPrinter.h.
Referenced by llvm::DwarfException::ComputeCallSiteTable(), doFinalization(), doInitialization(), EmitBasicBlockStart(), emitDebugValueComment(), llvm::DwarfDebug::emitDIE(), llvm::DwarfException::EmitExceptionTable(), EmitFunctionBody(), EmitFunctionHeader(), EmitGlobalConstant(), EmitGlobalVariable(), llvm::ARMAsmPrinter::EmitInstruction(), EmitJumpTableInfo(), EmitLabelDifference(), EmitLabelOffsetDifference(), EmitLabelPlusOffset(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), emitPrologLabel(), EmitSectionOffset(), EmitSpecialLLVMGlobal(), llvm::DwarfCFIException::EndModule(), llvm::MSP430MCInstLower::GetConstantPoolIndexSymbol(), GetCPISymbol(), GetJTSetSymbol(), llvm::MSP430MCInstLower::GetJumpTableSymbol(), llvm::DwarfDebug::getOrCreateSourceID(), GetSymbolFromOperand(), GetTempSymbol(), needsCFIMoves(), needsRelocationsForDwarfStringPool(), needsSEHMoves(), llvm::ARMAsmPrinter::printOperand(), and llvm::MipsAsmPrinter::printOperand().
Mangler* llvm::AsmPrinter::Mang
Name-mangler for global names.
Definition at line 88 of file AsmPrinter.h.
Referenced by llvm::DwarfCFIException::BeginFunction(), doFinalization(), doInitialization(), EmitCamlGlobal(), EmitFunctionHeader(), EmitGlobalVariable(), EmitJumpTableInfo(), EmitSpecialLLVMGlobal(), llvm::ARMAsmPrinter::EmitStartOfAsmFile(), EmitTTypeReference(), llvm::Win64Exception::EndFunction(), GetExternalSymbolSymbol(), getSymbol(), GetSymbolFromOperand(), and GetSymbolWithGlobalValueBase().
const MachineFunction* llvm::AsmPrinter::MF
The current machine function.
Definition at line 81 of file AsmPrinter.h.
Referenced by llvm::CompileUnit::addRegisterOffset(), AsmPrinter(), llvm::ARMException::BeginFunction(), llvm::DwarfDebug::beginInstruction(), llvm::DwarfException::ComputeCallSiteTable(), llvm::CompileUnit::constructVariableDIE(), emitComments(), EmitConstantPool(), emitDebugValueComment(), llvm::MipsAsmPrinter::emitFrameDirective(), EmitFunctionBody(), llvm::MipsAsmPrinter::EmitFunctionBodyStart(), EmitFunctionHeader(), llvm::SystemZAsmPrinter::EmitInstruction(), llvm::X86AsmPrinter::EmitInstruction(), llvm::ARMAsmPrinter::EmitJump2Table(), llvm::ARMAsmPrinter::EmitJumpTable(), EmitJumpTableInfo(), emitPrologLabel(), llvm::ARMException::EndFunction(), getFunctionNumber(), GetJTISymbol(), llvm::DwarfDebug::isSubprogramContext(), nvptx::LowerConstant(), lowerConstant(), needsCFIMoves(), needsSEHMoves(), llvm::SystemZAsmPrinter::PrintAsmOperand(), llvm::AArch64AsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::PrintAsmOperand(), llvm::ARMAsmPrinter::printOperand(), llvm::MipsAsmPrinter::printSavedRegsBitmask(), llvm::X86AsmPrinter::printSymbolOperand(), and SetupMachineFunction().
const MCInstrInfo* llvm::AsmPrinter::MII
Definition at line 68 of file AsmPrinter.h.
Referenced by llvm::HexagonAsmPrinter::EmitInstruction().
MachineModuleInfo* llvm::AsmPrinter::MMI
MMI - This is a pointer to the current MachineModuleInfo.
Definition at line 84 of file AsmPrinter.h.
Referenced by AsmPrinter(), doFinalization(), doInitialization(), EmitBasicBlockStart(), llvm::SystemZAsmPrinter::EmitEndOfAsmFile(), llvm::AArch64AsmPrinter::EmitEndOfAsmFile(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::ARMAsmPrinter::EmitEndOfAsmFile(), EmitFunctionBody(), EmitFunctionHeader(), emitPrologLabel(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), EmitTTypeReference(), GetBlockAddressSymbol(), getMachOMMI(), getModifierVariantKind(), needsCFIMoves(), and llvm::X86AsmPrinter::printSymbolOperand().
MCContext& llvm::AsmPrinter::OutContext
OutContext - This is the context for the output file that we are streaming. This owns all of the global MC-related objects for the generated translation unit.
Definition at line 72 of file AsmPrinter.h.
Referenced by doFinalization(), doInitialization(), EmitCamlGlobal(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::ARMAsmPrinter::EmitEndOfAsmFile(), llvm::DwarfException::EmitExceptionTable(), EmitFunctionBody(), EmitGlobalVariable(), llvm::X86AsmPrinter::EmitInstruction(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::ARMAsmPrinter::EmitJump2Table(), llvm::ARMAsmPrinter::EmitJumpTable(), EmitJumpTableInfo(), EmitLabelDifference(), EmitLabelOffsetDifference(), EmitLabelPlusOffset(), llvm::SystemZAsmPrinter::EmitMachineConstantPoolValue(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), EmitSpecialLLVMGlobal(), llvm::ARMAsmPrinter::EmitStartOfAsmFile(), llvm::ARMAsmPrinter::EmitXXStructor(), llvm::Win64Exception::EndFunction(), llvm::DwarfUnits::getAddrPoolIndex(), GetCPISymbol(), GetExternalSymbolSymbol(), GetJTISymbol(), GetJTSetSymbol(), GetSymbolFromOperand(), GetSymbolRef(), GetSymbolWithGlobalValueBase(), GetTempSymbol(), llvm::HexagonLowerToMC(), nvptx::LowerConstant(), lowerConstant(), llvm::AArch64AsmPrinter::lowerOperand(), llvm::ARMAsmPrinter::lowerOperand(), llvm::LowerPPCMachineInstrToMCInst(), llvm::AArch64AsmPrinter::lowerSymbolOperand(), llvm::ARMAsmPrinter::printOperand(), llvm::X86AsmPrinter::printSymbolOperand(), and llvm::MipsAsmPrinter::runOnMachineFunction().
MCStreamer& llvm::AsmPrinter::OutStreamer
OutStreamer - This is the MCStreamer object for the file we are generating. This contains the transient state for the current translation unit that we are generating (such as the current section etc).
Definition at line 78 of file AsmPrinter.h.
Referenced by llvm::DwarfCFIException::BeginFunction(), llvm::ARMException::BeginFunction(), llvm::Win64Exception::BeginFunction(), llvm::DwarfDebug::beginFunction(), llvm::DwarfDebug::beginInstruction(), computeIndexValue(), doFinalization(), doInitialization(), llvm::DwarfUnits::emitAddresses(), llvm::HexagonAsmPrinter::EmitAlignment(), EmitAlignment(), emitBasicBlockLoopComments(), EmitBasicBlockStart(), EmitCamlGlobal(), EmitCFAByte(), emitCFIInstruction(), EmitConstantPool(), emitDebugValueComment(), llvm::DwarfDebug::emitDIE(), llvm::ARMAsmPrinter::EmitDwarfRegOp(), EmitDwarfRegOp(), EmitEncodingByte(), llvm::SystemZAsmPrinter::EmitEndOfAsmFile(), llvm::AArch64AsmPrinter::EmitEndOfAsmFile(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::ARMAsmPrinter::EmitEndOfAsmFile(), llvm::MipsAsmPrinter::EmitEndOfAsmFile(), llvm::DwarfException::EmitExceptionTable(), llvm::MipsAsmPrinter::emitFrameDirective(), EmitFunctionBody(), llvm::ARMAsmPrinter::EmitFunctionBodyEnd(), llvm::MipsAsmPrinter::EmitFunctionBodyEnd(), llvm::MipsAsmPrinter::EmitFunctionBodyStart(), llvm::ARMAsmPrinter::EmitFunctionEntryLabel(), llvm::MipsAsmPrinter::EmitFunctionEntryLabel(), EmitFunctionEntryLabel(), EmitFunctionHeader(), EmitGlobalConstant(), emitGlobalConstantArray(), emitGlobalConstantDataSequential(), emitGlobalConstantFP(), emitGlobalConstantImpl(), emitGlobalConstantLargeInt(), emitGlobalConstantStruct(), emitGlobalConstantVector(), EmitGlobalVariable(), llvm::CompileUnit::emitHeader(), emitImplicitDef(), llvm::SystemZAsmPrinter::EmitInstruction(), llvm::HexagonAsmPrinter::EmitInstruction(), llvm::AArch64AsmPrinter::EmitInstruction(), llvm::X86AsmPrinter::EmitInstruction(), llvm::ARMAsmPrinter::EmitInstruction(), llvm::MipsAsmPrinter::EmitInstruction(), EmitInt16(), EmitInt32(), EmitInt8(), llvm::ARMAsmPrinter::EmitJump2Table(), llvm::ARMAsmPrinter::EmitJumpTable(), EmitJumpTableInfo(), emitKill(), EmitLabelDifference(), EmitLabelOffsetDifference(), EmitLabelPlusOffset(), llvm::SystemZAsmPrinter::EmitMachineConstantPoolValue(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), llvm::AMDGPUAsmPrinter::EmitProgramInfoR600(), llvm::AMDGPUAsmPrinter::EmitProgramInfoSI(), emitPrologLabel(), EmitSectionOffset(), emitSectionSym(), EmitSLEB128(), EmitSpecialLLVMGlobal(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), llvm::ARMAsmPrinter::EmitStartOfAsmFile(), llvm::MipsAsmPrinter::EmitStartOfAsmFile(), llvm::DwarfUnits::emitStrings(), EmitTTypeReference(), llvm::DwarfException::EmitTypeInfos(), EmitULEB128(), llvm::DwarfUnits::emitUnits(), llvm::DIEInteger::EmitValue(), llvm::DIEExpr::EmitValue(), llvm::ARMAsmPrinter::EmitXXStructor(), llvm::DwarfCFIException::EndFunction(), llvm::ARMException::EndFunction(), llvm::Win64Exception::EndFunction(), llvm::DwarfDebug::endFunction(), llvm::DwarfDebug::endInstruction(), llvm::DwarfCFIException::EndModule(), llvm::DwarfAccelTable::FinalizeTable(), getArchForCPU(), getCurrentSection(), llvm::DwarfDebug::getOrCreateSourceID(), llvm::linkErlangGCPrinter(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), llvm::X86AsmPrinter::runOnMachineFunction(), shouldAddODRHash(), llvm::ARMException::~ARMException(), and ~AsmPrinter().
TargetMachine& llvm::AsmPrinter::TM
Target machine description.
Definition at line 62 of file AsmPrinter.h.
Referenced by llvm::CompileUnit::addRegisterOffset(), llvm::CompileUnit::addRegisterOp(), llvm::DwarfDebug::beginFunction(), llvm::CompileUnit::constructVariableDIE(), doFinalization(), doInitialization(), EmitAlignment(), EmitCamlGlobal(), emitComments(), EmitConstantPool(), emitDebugValueComment(), llvm::ARMAsmPrinter::EmitDwarfRegOp(), EmitDwarfRegOp(), llvm::SystemZAsmPrinter::EmitEndOfAsmFile(), llvm::AArch64AsmPrinter::EmitEndOfAsmFile(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::MipsAsmPrinter::emitFrameDirective(), EmitFunctionBody(), EmitFunctionHeader(), EmitGlobalConstant(), emitGlobalConstantArray(), emitGlobalConstantDataSequential(), emitGlobalConstantFP(), emitGlobalConstantImpl(), emitGlobalConstantLargeInt(), emitGlobalConstantStruct(), emitGlobalConstantVector(), EmitGlobalVariable(), emitImplicitDef(), llvm::ARMAsmPrinter::EmitJumpTable(), EmitJumpTableInfo(), emitKill(), llvm::SystemZAsmPrinter::EmitMachineConstantPoolValue(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), llvm::AMDGPUAsmPrinter::EmitProgramInfoR600(), llvm::AMDGPUAsmPrinter::EmitProgramInfoSI(), EmitSpecialLLVMGlobal(), llvm::ARMAsmPrinter::EmitStartOfAsmFile(), llvm::ARMAsmPrinter::EmitXXStructor(), llvm::DwarfCFIException::EndModule(), getArchForCPU(), getDataLayout(), getModifierVariantKind(), getObjFileLowering(), llvm::DwarfDebug::getOrCreateSourceID(), GetSizeOfEncodedValue(), getTargetTriple(), isRepeatedByteSequence(), llvm::DwarfDebug::isSubprogramContext(), llvm::linkErlangGCPrinter(), nvptx::LowerConstant(), lowerConstant(), llvm::MipsAsmPrinter::printSavedRegsBitmask(), llvm::AArch64AsmPrinter::printSymbolicAddress(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), and llvm::MipsAsmPrinter::runOnMachineFunction().
The documentation for this class was generated from the following files:
AsmPrinter.h
AsmPrinter.cpp
AsmPrinterDwarf.cpp
AsmPrinterInlineAsm.cpp