LLVM: llvm::HexagonSubtarget Class Reference
LLVM API Documentation
llvm::HexagonSubtarget Class Reference
#include <HexagonSubtarget.h>
Public Types
enum HexagonArchEnum {
V1, V2, V3, V4,
V5
}
Public Member Functions
HexagonSubtarget (StringRef TT, StringRef CPU, StringRef FS)
const InstrItineraryData & getInstrItineraryData () const
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
bool hasV2TOps () const
bool hasV2TOpsOnly () const
bool hasV3TOps () const
bool hasV3TOpsOnly () const
bool hasV4TOps () const
bool hasV4TOpsOnly () const
bool useMemOps () const
bool hasV5TOps () const
bool hasV5TOpsOnly () const
bool modeIEEERndNear () const
bool isSubtargetV2 () const
const std::string & getCPUString () const
unsigned getSmallDataThreshold () const
const HexagonArchEnum & getHexagonArchVersion () const
Public Attributes
HexagonArchEnum HexagonArchVersion
std::string CPUString
InstrItineraryData InstrItins
Detailed Description
Definition at line 29 of file HexagonSubtarget.h.
Member Enumeration Documentation
enum llvm::HexagonSubtarget::HexagonArchEnum
Enumerator
V1
V2
V3
V4
V5
Definition at line 35 of file HexagonSubtarget.h.
Constructor & Destructor Documentation
HexagonSubtarget::HexagonSubtarget (StringRef TT, StringRef CPU, StringRef FS)
Definition at line 49 of file HexagonSubtarget.cpp.
References CPUString, DisableMemOps, EnableIEEERndNear, EnableMemOps, EnableV3, HexagonArchVersion, InstrItins, llvm_unreachable, ParseSubtargetFeatures(), V2, V3, V4, and V5.
Member Function Documentation
const std::string& llvm::HexagonSubtarget::getCPUString () const inline
Definition at line 67 of file HexagonSubtarget.h.
References CPUString.
const HexagonArchEnum& llvm::HexagonSubtarget::getHexagonArchVersion () const inline
Definition at line 73 of file HexagonSubtarget.h.
References HexagonArchVersion.
Referenced by llvm::HexagonRegisterInfo::getCalleeSavedRegClasses(), and llvm::HexagonRegisterInfo::getCalleeSavedRegs().
const InstrItineraryData& llvm::HexagonSubtarget::getInstrItineraryData () const inline
getInstrItins - Return the instruction itineraies based on subtarget selection.
Definition at line 48 of file HexagonSubtarget.h.
References llvm::X86II::FS, InstrItins, and ParseSubtargetFeatures().
unsigned llvm::HexagonSubtarget::getSmallDataThreshold () const inline
Definition at line 70 of file HexagonSubtarget.h.
References Hexagon_SMALL_DATA_THRESHOLD.
bool llvm::HexagonSubtarget::hasV2TOps () const inline
Definition at line 55 of file HexagonSubtarget.h.
References V2.
bool llvm::HexagonSubtarget::hasV2TOpsOnly () const inline
Definition at line 56 of file HexagonSubtarget.h.
References V2.
bool llvm::HexagonSubtarget::hasV3TOps () const inline
Definition at line 57 of file HexagonSubtarget.h.
References V3.
bool llvm::HexagonSubtarget::hasV3TOpsOnly () const inline
Definition at line 58 of file HexagonSubtarget.h.
References V3.
bool llvm::HexagonSubtarget::hasV4TOps () const inline
Definition at line 59 of file HexagonSubtarget.h.
References V4.
Referenced by areCombinableOperations(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::HexagonFrameLowering::emitEpilogue(), getPredicatedRegister(), GetStoreValueOperand(), llvm::HexagonInstrInfo::isConditionalALU32(), llvm::HexagonInstrInfo::isConditionalLoad(), llvm::HexagonInstrInfo::isConditionalStore(), llvm::HexagonInstrInfo::isConstExtended(), llvm::HexagonInstrInfo::isExtendable(), llvm::HexagonInstrInfo::isOperandExtended(), llvm::HexagonInstrInfo::isPredicable(), and llvm::HexagonInstrInfo::mayBeNewStore().
bool llvm::HexagonSubtarget::hasV4TOpsOnly () const inline
Definition at line 60 of file HexagonSubtarget.h.
References V4.
bool llvm::HexagonSubtarget::hasV5TOps () const inline
Definition at line 62 of file HexagonSubtarget.h.
References V5.
Referenced by llvm::HexagonTargetLowering::HexagonTargetLowering(), and llvm::HexagonTargetLowering::isFPImmLegal().
bool llvm::HexagonSubtarget::hasV5TOpsOnly () const inline
Definition at line 63 of file HexagonSubtarget.h.
References V5.
bool llvm::HexagonSubtarget::isSubtargetV2 () const inline
Definition at line 66 of file HexagonSubtarget.h.
References V2.
Referenced by llvm::HexagonTargetLowering::HexagonTargetLowering().
bool llvm::HexagonSubtarget::modeIEEERndNear () const inline
Definition at line 64 of file HexagonSubtarget.h.
void llvm::HexagonSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options. Definition of function is auto generated by tblgen.
Referenced by getInstrItineraryData(), and HexagonSubtarget().
bool llvm::HexagonSubtarget::useMemOps () const inline
Definition at line 61 of file HexagonSubtarget.h.
References V4.
Member Data Documentation
std::string llvm::HexagonSubtarget::CPUString
Definition at line 40 of file HexagonSubtarget.h.
Referenced by getCPUString(), and HexagonSubtarget().
HexagonArchEnum llvm::HexagonSubtarget::HexagonArchVersion
Definition at line 39 of file HexagonSubtarget.h.
Referenced by getHexagonArchVersion(), and HexagonSubtarget().
InstrItineraryData llvm::HexagonSubtarget::InstrItins
Definition at line 41 of file HexagonSubtarget.h.
Referenced by getInstrItineraryData(), and HexagonSubtarget().
The documentation for this class was generated from the following files:
HexagonSubtarget.h
HexagonSubtarget.cpp