LLVM: llvm::DWARFDebugAranges Class Reference
LLVM API Documentation
llvm::DWARFDebugAranges Class Reference
#include <DWARFDebugAranges.h>
Public Member Functions
void clear ()
void generate (DWARFContext *CTX)
void appendRange (uint32_t CUOffset, uint64_t LowPC, uint64_t HighPC)
uint32_t findAddress (uint64_t Address) const
Detailed Description
Definition at line 21 of file DWARFDebugAranges.h.
Member Function Documentation
void DWARFDebugAranges::appendRange (uint32_t CUOffset, uint64_t LowPC, uint64_t HighPC)
Definition at line 73 of file DWARFDebugAranges.cpp.
References i, and j().
Referenced by llvm::DWARFDebugInfoEntryMinimal::buildAddressRangeTable(), and clear().
void llvm::DWARFDebugAranges::clear () inline
Definition at line 23 of file DWARFDebugAranges.h.
References appendRange(), llvm::DenseSet< ValueT, ValueInfoT >::clear(), findAddress(), generate(), and llvm::operator<().
Referenced by generate().
uint32_t DWARFDebugAranges::findAddress (uint64_t Address) const
Definition at line 135 of file DWARFDebugAranges.cpp.
References llvm::sys::path::begin(), and llvm::sys::path::end().
Referenced by clear().
void DWARFDebugAranges::generate (DWARFContext * CTX)
Definition at line 50 of file DWARFDebugAranges.cpp.
References clear(), llvm::DWARFContext::getARangeSection(), llvm::DWARFContext::getCompileUnitAtIndex(), llvm::DWARFContext::getNumCompileUnits(), i, llvm::DenseSet< ValueT, ValueInfoT >::insert(), llvm::DWARFContext::isLittleEndian(), and n.
Referenced by clear(), and llvm::DWARFContext::getDebugAranges().
The documentation for this class was generated from the following files:
DWARFDebugAranges.h
DWARFDebugAranges.cpp