LLVM: llvm::SparcFrameLowering Class Reference
LLVM API Documentation
llvm::SparcFrameLowering Class Reference
#include <SparcFrameLowering.h>
Public Member Functions
SparcFrameLowering (const SparcSubtarget &ST)
void emitPrologue (MachineFunction &MF) const
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const
void eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator I) const
bool hasReservedCallFrame (const MachineFunction &MF) const
bool hasFP (const MachineFunction &MF) const
void processFunctionBeforeCalleeSavedScan (MachineFunction &MF, RegScavenger *RS=NULL) const
Public Member Functions inherited from llvm::TargetFrameLowering
TargetFrameLowering (StackDirection D, unsigned StackAl, int LAO, unsigned TransAl=1, bool StackReal=true)
virtual ~TargetFrameLowering ()
StackDirection getStackGrowthDirection () const
unsigned getStackAlignment () const
unsigned getTransientStackAlignment () const
bool isStackRealignable () const
int getOffsetOfLocalArea () const
virtual bool isFPCloseToIncomingSP () const
virtual const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const
virtual bool targetHandlesStackFrameRounding () const
virtual void adjustForSegmentedStacks (MachineFunction &MF) const
virtual void adjustForHiPEPrologue (MachineFunction &MF) const
virtual bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const
virtual bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const
virtual bool canSimplifyCallFramePseudos (const MachineFunction &MF) const
virtual int getFrameIndexOffset (const MachineFunction &MF, int FI) const
virtual int getFrameIndexReference (const MachineFunction &MF, int FI, unsigned &FrameReg) const
virtual void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS=NULL) const
Additional Inherited Members
Public Types inherited from llvm::TargetFrameLowering
enum StackDirection { StackGrowsUp, StackGrowsDown }
Detailed Description
Definition at line 24 of file SparcFrameLowering.h.
Constructor & Destructor Documentation
llvm::SparcFrameLowering::SparcFrameLowering (const SparcSubtarget & ST) inline explicit
Definition at line 27 of file SparcFrameLowering.h.
References eliminateCallFramePseudoInstr(), emitEpilogue(), emitPrologue(), hasFP(), hasReservedCallFrame(), I, and processFunctionBeforeCalleeSavedScan().
Member Function Documentation
void SparcFrameLowering::eliminateCallFramePseudoInstr (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const virtual
eliminateCallFramePseudoInstr - This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them). It is responsible for eliminating these instructions, replacing them with concrete instructions. This method need only be implemented if using call frame setup/destroy pseudo instructions.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 127 of file SparcFrameLowering.cpp.
References llvm::MachineBasicBlock::erase(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), hasReservedCallFrame(), I, and llvm::A64CC::MI.
Referenced by emitPrologue(), and SparcFrameLowering().
void SparcFrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const virtual
Implements llvm::TargetFrameLowering.
Definition at line 142 of file SparcFrameLowering.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::SparcSubtarget::getAdjustedFrameSize(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::TargetMachine::getInstrInfo(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getTarget(), int, and llvm::SparcMachineFunctionInfo::isLeafProc().
Referenced by SparcFrameLowering().
void SparcFrameLowering::emitPrologue (MachineFunction & MF) const virtual
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
Implements llvm::TargetFrameLowering.
Definition at line 81 of file SparcFrameLowering.cpp.
References llvm::MachineModuleInfo::addFrameInst(), llvm::BuildMI(), llvm::MCCFIInstruction::createDefCfaRegister(), llvm::MCCFIInstruction::createRegister(), llvm::MCContext::CreateTempSymbol(), llvm::MCCFIInstruction::createWindowSave(), eliminateCallFramePseudoInstr(), llvm::MachineFunction::front(), llvm::SparcSubtarget::getAdjustedFrameSize(), llvm::MachineModuleInfo::getContext(), llvm::MCRegisterInfo::getDwarfRegNum(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getInfo(), llvm::TargetMachine::getInstrInfo(), llvm::MachineFunction::getMMI(), llvm::MCContext::getRegisterInfo(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getTarget(), int, llvm::SparcMachineFunctionInfo::isLeafProc(), MRI, and llvm::TargetOpcode::PROLOG_LABEL.
Referenced by SparcFrameLowering().
bool SparcFrameLowering::hasFP (const MachineFunction & MF) const virtual
hasFP - Return true if the specified function should have a dedicated frame pointer register. For most targets this is true only if the function has variable sized allocas or if frame pointer elimination is disabled.
Implements llvm::TargetFrameLowering.
Definition at line 174 of file SparcFrameLowering.cpp.
References llvm::TargetOptions::DisableFramePointerElim(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getTarget(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::MachineFrameInfo::isFrameAddressTaken(), and llvm::TargetMachine::Options.
Referenced by SparcFrameLowering(), and verifyLeafProcRegUse().
bool SparcFrameLowering::hasReservedCallFrame (const MachineFunction & MF) const virtual
hasReservedCallFrame - Under normal circumstances, when a frame pointer is not required, we reserve argument space for call sites in the function immediately on entry to the current function. This eliminates the need for add/sub sp brackets around call sites. Returns true if the call frame is included as part of the stack frame.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 166 of file SparcFrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), and llvm::MachineFrameInfo::hasVarSizedObjects().
Referenced by eliminateCallFramePseudoInstr(), and SparcFrameLowering().
void SparcFrameLowering::processFunctionBeforeCalleeSavedScan (MachineFunction & MF, RegScavenger * RS = NULL) const virtual
processFunctionBeforeCalleeSavedScan - This method is called immediately before PrologEpilogInserter scans the physical registers used to determine what callee saved registers should be spilled. This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 243 of file SparcFrameLowering.cpp.
References DisableLeafProc, llvm::MachineFunction::getInfo(), and llvm::SparcMachineFunctionInfo::setLeafProc().
Referenced by SparcFrameLowering(), and verifyLeafProcRegUse().
The documentation for this class was generated from the following files:
SparcFrameLowering.h
SparcFrameLowering.cpp