LLVM: llvm::LLLexer Class Reference
LLVM API Documentation
llvm::LLLexer Class Reference
#include <LLLexer.h>
Public Types
typedef SMLoc LocTy
Public Member Functions
LLLexer (MemoryBuffer *StartBuf, SourceMgr &SM, SMDiagnostic &, LLVMContext &C)
~LLLexer ()
lltok::Kind Lex ()
LocTy getLoc () const
lltok::Kind getKind () const
const std::string & getStrVal () const
Type * getTyVal () const
unsigned getUIntVal () const
const APSInt & getAPSIntVal () const
const APFloat & getAPFloatVal () const
bool Error (LocTy L, const Twine &Msg) const
bool Error (const Twine &Msg) const
std::string getFilename () const
Detailed Description
Definition at line 29 of file LLLexer.h.
Member Typedef Documentation
typedef SMLoc llvm::LLLexer::LocTy
Definition at line 54 of file LLLexer.h.
Constructor & Destructor Documentation
LLLexer::LLLexer (MemoryBuffer * StartBuf, SourceMgr & SM, SMDiagnostic & Err, LLVMContext & C) explicit
Definition at line 160 of file LLLexer.cpp.
References llvm::MemoryBuffer::getBufferStart().
llvm::LLLexer::~LLLexer () inline
Definition at line 48 of file LLLexer.h.
Member Function Documentation
bool LLLexer::Error (LocTy L, const Twine & Msg) const
Definition at line 32 of file LLLexer.cpp.
References llvm::SourceMgr::DK_Error, llvm::SourceMgr::GetMessage(), llvm::hexDigitValue(), and i.
Referenced by getAPFloatVal(), llvm::LLParser::getContext(), and getFilename().
bool llvm::LLLexer::Error (const Twine & Msg) const inline
Definition at line 65 of file LLLexer.h.
References Error(), getFilename(), and getLoc().
Referenced by Error().
const APFloat& llvm::LLLexer::getAPFloatVal () const inline
Definition at line 61 of file LLLexer.h.
References Error().
Referenced by FunctionNumber().
const APSInt& llvm::LLLexer::getAPSIntVal () const inline
Definition at line 60 of file LLLexer.h.
Referenced by FunctionNumber(), and llvm::LLParser::Run().
std::string LLLexer::getFilename () const
Definition at line 166 of file LLLexer.cpp.
References llvm::ARM_AM::add, align, llvm::APIntOps::And(), llvm::lltok::APFloat, llvm::lltok::APSInt, llvm::APIntOps::ashr(), llvm::LibFunc::atof, llvm::lltok::AttrGrpID, attributes, llvm::lltok::backslash, llvm::BitsToDouble(), c, llvm::Call, call(), llvm::lltok::comma, common, llvm::lltok::dotdotdot, llvm::lltok::Eof, llvm::lltok::equal, llvm::lltok::Error, Error(), llvm::lltok::exclaim, ExtractElement(), fastcc, llvm::IntegerType::get(), llvm::APInt::getActiveBits(), llvm::MemoryBuffer::getBufferEnd(), llvm::MemoryBuffer::getBufferIdentifier(), llvm::Type::getDoubleTy(), llvm::Type::getFloatTy(), llvm::Type::getFP128Ty(), llvm::Type::getHalfTy(), llvm::Type::getLabelTy(), llvm::Type::getMetadataTy(), llvm::APInt::getMinSignedBits(), llvm::Type::getPPC_FP128Ty(), llvm::Type::getVoidTy(), llvm::Type::getX86_FP80Ty(), llvm::Type::getX86_MMXTy(), llvm::lltok::GlobalID, llvm::lltok::GlobalVar, llvm::lltok::greater, llvm::APFloat::IEEEhalf, llvm::APFloat::IEEEquad, INSTKEYWORD, llvm::LibFunc::isdigit, isLabelChar(), isLabelTail(), KEYWORD, llvm::lltok::kw_cc, llvm::lltok::LabelStr, llvm::lltok::lbrace, llvm::lltok::less, llvm_unreachable, llvm::SPII::Load, load, llvm::lltok::LocalVar, llvm::lltok::LocalVarID, llvm::lltok::lparen, llvm::APIntOps::lshr(), llvm::lltok::lsquare, llvm::IntegerType::MAX_INT_BITS, llvm::lltok::MetadataVar, llvm::IntegerType::MIN_INT_BITS, mul(), nounwind, one, or, llvm::APIntOps::Or(), llvm::TargetOpcode::PHI, llvm::APFloat::PPCDoubleDouble, llvm::lltok::rbrace, readnone, readonly, llvm::AArch64ISD::Ret, ret(), llvm::lltok::rparen, llvm::lltok::rsquare, sdiv(), select(), llvm::MCID::Select, llvm::APIntOps::shl(), srem(), llvm::lltok::star, llvm::SPII::Store, store, llvm::lltok::StringConstant, sub, target, to, trunc, llvm::APInt::trunc(), type, llvm::lltok::Type, TYPEKEYWORD, llvm::APIntOps::udiv(), llvm::APIntOps::umax(), llvm::APIntOps::umin(), UnEscapeLexed(), llvm::APIntOps::urem(), llvm::APFloat::x87DoubleExtended, and llvm::APIntOps::Xor().
Referenced by Error().
lltok::Kind llvm::LLLexer::getKind () const inline
Definition at line 56 of file LLLexer.h.
Referenced by FunctionNumber(), llvm::LLParser::getContext(), and llvm::LLParser::Run().
LocTy llvm::LLLexer::getLoc () const inline
Definition at line 55 of file LLLexer.h.
References llvm::SMLoc::getFromPointer().
Referenced by Error(), FunctionNumber(), llvm::LLParser::getContext(), and llvm::LLParser::Run().
const std::string& llvm::LLLexer::getStrVal () const inline
Definition at line 57 of file LLLexer.h.
Referenced by FunctionNumber(), and llvm::LLParser::Run().
Type* llvm::LLLexer::getTyVal () const inline
Definition at line 58 of file LLLexer.h.
unsigned llvm::LLLexer::getUIntVal () const inline
Definition at line 59 of file LLLexer.h.
Referenced by FunctionNumber(), and llvm::LLParser::Run().
lltok::Kind llvm::LLLexer::Lex () inline
Definition at line 50 of file LLLexer.h.
Referenced by FunctionNumber(), llvm::LLParser::getContext(), if(), and llvm::LLParser::Run().
The documentation for this class was generated from the following files:
LLLexer.h
LLLexer.cpp