LLVM: llvm::RegionInfo Class Reference
LLVM API Documentation
llvm::RegionInfo Class Reference
Analysis that detects all canonical Regions.
#include <RegionInfo.h>
Public Member Functions
RegionInfo ()
~RegionInfo ()
Region * getRegionFor (BasicBlock *BB) const
Get the smallest region that contains a BasicBlock.
void setRegionFor (BasicBlock *BB, Region *R)
Set the smallest region that surrounds a basic block.
Region * operator[] (BasicBlock *BB) const
A shortcut for getRegionFor().
BasicBlock * getMaxRegionExit (BasicBlock *BB) const
Return the exit of the maximal refined region, that starts at a BasicBlock.
Region * getCommonRegion (Region *A, Region *B) const
Find the smallest region that contains two regions.
Region * getCommonRegion (BasicBlock *A, BasicBlock *B) const
Find the smallest region that contains two basic blocks.
Region * getCommonRegion (SmallVectorImpl< Region * > &Regions) const
Find the smallest region that contains a set of regions.
Region * getCommonRegion (SmallVectorImpl< BasicBlock * > &BBs) const
Find the smallest region that contains a set of basic blocks.
Region * getTopLevelRegion () const
void splitBlock (BasicBlock *NewBB, BasicBlock *OldBB)
Update RegionInfo after a basic block was split.
void clearNodeCache ()
Clear the Node Cache for all Regions.
FunctionPass interface
virtual bool runOnFunction (Function &F)
virtual void getAnalysisUsage (AnalysisUsage &AU) const
virtual void print (raw_ostream &OS, const Module *) const
virtual void verifyAnalysis () const
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const
createPrinterPass - Get a function printer pass.
virtual void assignPassManager (PMStack &PMS, PassManagerType T)
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
Analysis that detects all canonical Regions.
The RegionInfo pass detects all canonical regions in a function. The Regions are connected using the parent relation. This builds a Program Structure Tree.
Definition at line 577 of file RegionInfo.h.
Constructor & Destructor Documentation
RegionInfo::RegionInfo () explicit
Definition at line 687 of file RegionInfo.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeRegionInfoPass().
Referenced by llvm::createRegionInfoPass().
RegionInfo::~RegionInfo ()
Definition at line 692 of file RegionInfo.cpp.
References llvm::Calculate(), llvm::Function::getEntryBlock(), and llvm::DominatorTree::getNode().
Member Function Documentation
void llvm::RegionInfo::clearNodeCache () inline
Clear the Node Cache for all Regions.
See also
Region::clearNodeCache()
Definition at line 725 of file RegionInfo.h.
References llvm::Region::clearNodeCache().
Referenced by llvm::RGPassManager::runOnFunction().
void RegionInfo::getAnalysisUsage (AnalysisUsage &) const virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job. If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 722 of file RegionInfo.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::AnalysisUsage::addRequiredTransitive(), and llvm::AnalysisUsage::setPreservesAll().
Region * RegionInfo::getCommonRegion (Region * A, Region * B) const
Find the smallest region that contains two regions.
Parameters
A The first region.
B The second region.
Returns
The smallest region containing A and B.
Definition at line 798 of file RegionInfo.cpp.
References B, llvm::Region::contains(), and llvm::Region::getParent().
Referenced by getCommonRegion().
Region* llvm::RegionInfo::getCommonRegion (BasicBlock * A, BasicBlock * B) const inline
Find the smallest region that contains two basic blocks.
Parameters
A The first basic block.
B The second basic block.
Returns
The smallest region that contains A and B.
Definition at line 696 of file RegionInfo.h.
Region * RegionInfo::getCommonRegion (SmallVectorImpl< Region * > & Regions) const
Find the smallest region that contains a set of regions.
Parameters
Regions A vector of regions.
Returns
The smallest region that contains all regions in Regions.
Definition at line 810 of file RegionInfo.cpp.
References llvm::SmallVectorTemplateCommon< T >::back(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::SmallVectorTemplateCommon< T >::end(), getCommonRegion(), I, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::pop_back(), and ret().
Region * RegionInfo::getCommonRegion (SmallVectorImpl< BasicBlock * > & BBs) const
Find the smallest region that contains a set of basic blocks.
Parameters
BBs A vector of basic blocks.
Returns
The smallest region that contains all basic blocks in BBS.
Definition at line 822 of file RegionInfo.cpp.
References llvm::SmallVectorTemplateCommon< T >::back(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::SmallVectorTemplateCommon< T >::end(), getCommonRegion(), getRegionFor(), I, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::pop_back(), and ret().
BasicBlock * RegionInfo::getMaxRegionExit (BasicBlock * BB) const
Return the exit of the maximal refined region, that starts at a BasicBlock.
Parameters
BB The BasicBlock the refined region starts.
Definition at line 759 of file RegionInfo.cpp.
References BB, llvm::Region::contains(), llvm::DominatorTree::dominates(), llvm::Region::getEntry(), llvm::Region::getExit(), llvm::Region::getParent(), getRegionFor(), llvm::pred_begin(), llvm::pred_end(), llvm::succ_begin(), and llvm::succ_end().
Region * RegionInfo::getRegionFor (BasicBlock * BB) const
Get the smallest region that contains a BasicBlock.
Parameters
BB The basic block.
Returns
The smallest region, that contains BB or NULL, if there is no region containing BB.
Definition at line 745 of file RegionInfo.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::find(), and I.
Referenced by getCommonRegion(), llvm::DOTGraphTraits< RegionInfo * >::getEdgeAttributes(), llvm::Region::getExpandedRegion(), getMaxRegionExit(), llvm::Region::getSubRegionNode(), operator[](), llvm::DOTGraphTraits< RegionInfo * >::printRegionCluster(), and splitBlock().
Region* llvm::RegionInfo::getTopLevelRegion () const inline
Definition at line 712 of file RegionInfo.h.
Referenced by llvm::DOTGraphTraits< RegionInfo * >::addCustomGraphFeatures(), llvm::GraphTraits< RegionInfo * >::getEntryNode(), llvm::DOTGraphTraits< RegionInfo * >::getNodeLabel(), llvm::DOTGraphTraits< RegionInfo * >::printRegionCluster(), and llvm::RGPassManager::runOnFunction().
Region * RegionInfo::operator[] (BasicBlock * BB) const
A shortcut for getRegionFor().
Parameters
BB The basic block.
Returns
The smallest region, that contains BB or NULL, if there is no region containing BB.
Definition at line 755 of file RegionInfo.cpp.
References getRegionFor().
void RegionInfo::print (raw_ostream & O, const Module * M) const virtual
print - Print out the internal state of the pass. This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 729 of file RegionInfo.cpp.
References llvm::Region::print(), and printStyle.
bool RegionInfo::runOnFunction (Function & F) virtual
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
Implements llvm::FunctionPass.
Definition at line 707 of file RegionInfo.cpp.
References llvm::Calculate(), llvm::X86II::DF, and llvm::Function::getEntryBlock().
void RegionInfo::setRegionFor (BasicBlock * BB, Region * R)
Set the smallest region that surrounds a basic block.
Parameters
BB The basic block surrounded by a region.
R The smallest region that surrounds BB.
Definition at line 751 of file RegionInfo.cpp.
References BB.
Referenced by llvm::Region::addSubRegion(), and splitBlock().
void RegionInfo::splitBlock (BasicBlock * NewBB, BasicBlock * OldBB)
Update RegionInfo after a basic block was split.
Parameters
NewBB The basic block that was created before OldBB.
OldBB The old basic block.
Definition at line 833 of file RegionInfo.cpp.
References llvm::Region::getEntry(), llvm::Region::getParent(), getRegionFor(), ID, INITIALIZE_PASS_BEGIN(), INITIALIZE_PASS_DEPENDENCY, llvm::Region::isTopLevelRegion(), llvm::Region::replaceEntry(), and setRegionFor().
void RegionInfo::verifyAnalysis () const virtual
verifyAnalysis() - This member can be implemented by a analysis pass to check state of analysis information.
Reimplemented from llvm::Pass.
Definition at line 735 of file RegionInfo.cpp.
References VerifyRegionInfo.
Member Data Documentation
char RegionInfo::ID = 0 static
Definition at line 645 of file RegionInfo.h.
Referenced by splitBlock().
The documentation for this class was generated from the following files:
RegionInfo.h
RegionInfo.cpp