LLVM: llvm::UnOpInit Class Reference
LLVM API Documentation
llvm::UnOpInit Class Reference
#include <Record.h>
Public Types
enum UnaryOp { CAST, HEAD, TAIL, EMPTY }
Public Member Functions
virtual OpInit * clone (std::vector< Init * > &Operands) const
virtual int getNumOperands () const
virtual Init * getOperand (int i) const
UnaryOp getOpcode () const
Init * getOperand () const
virtual Init * Fold (Record *CurRec, MultiClass *CurMultiClass) const
virtual Init * resolveReferences (Record &R, const RecordVal *RV) const
virtual std::string getAsString () const
getAsString - Convert this value to a string form.
Public Member Functions inherited from llvm::OpInit
virtual Init * convertInitializerTo (RecTy *Ty) const
virtual Init * resolveListElementReference (Record &R, const RecordVal *RV, unsigned Elt) const
virtual Init * getBit (unsigned Bit) const
Public Member Functions inherited from llvm::TypedInit
RecTy * getType () const
virtual Init * convertInitializerBitRange (const std::vector< unsigned > &Bits) const
virtual Init * convertInitListSlice (const std::vector< unsigned > &Elements) const
virtual RecTy * getFieldType (const std::string &FieldName) const
Public Member Functions inherited from llvm::Init
InitKind getKind () const
virtual ~Init ()
virtual bool isComplete () const
void print (raw_ostream &OS) const
print - Print out this value.
virtual std::string getAsUnquotedString () const
void dump () const
virtual Init * getFieldInit (Record &R, const RecordVal *RV, const std::string &FieldName) const
virtual Init * getBitVar () const
virtual unsigned getBitNum () const
Static Public Member Functions
static bool classof (const Init *I)
static UnOpInit * get (UnaryOp opc, Init *lhs, RecTy *Type)
Static Public Member Functions inherited from llvm::OpInit
static bool classof (const Init *I)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind {
IK_BitInit, IK_BitsInit, IK_FirstTypedInit, IK_DagInit,
IK_DefInit, IK_FieldInit, IK_IntInit, IK_ListInit,
IK_FirstOpInit, IK_BinOpInit, IK_TernOpInit, IK_UnOpInit,
IK_LastOpInit, IK_StringInit, IK_VarInit, IK_VarListElementInit,
IK_LastTypedInit, IK_UnsetInit, IK_VarBitInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::OpInit
OpInit (InitKind K, RecTy *Type)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T)
Protected Member Functions inherited from llvm::Init
Init (InitKind K)
Detailed Description
UnOpInit - !op (X) - Transform an init.
Definition at line 882 of file Record.h.
Member Enumeration Documentation
enum llvm::UnOpInit::UnaryOp
Enumerator
CAST
HEAD
TAIL
EMPTY
Definition at line 884 of file Record.h.
Member Function Documentation
static bool llvm::UnOpInit::classof (const Init * I) inline static
Definition at line 896 of file Record.h.
References llvm::Init::getKind(), and Type.
virtual OpInit* llvm::UnOpInit::clone (std::vector< Init * > & Operands) const inline virtual
Implements llvm::OpInit.
Definition at line 902 of file Record.h.
References get(), and llvm::Intrinsic::getType().
Init * UnOpInit::Fold (Record * CurRec, MultiClass * CurMultiClass) const virtual
Implements llvm::OpInit.
Definition at line 751 of file Record.cpp.
References llvm::sys::path::begin(), llvm::StringRef::begin(), llvm::sys::path::end(), llvm::StringRef::end(), llvm::IntInit::get(), llvm::StringInit::get(), llvm::ListInit::get(), llvm::VarInit::get(), llvm::DefInit::get(), getDef(), llvm::Record::getLoc(), llvm::Record::getRecords(), llvm::Intrinsic::getType(), llvm::RecordVal::getType(), llvm::Record::getValue(), llvm::Record::isTemplateArg(), llvm::PrintFatalError(), llvm::QualifyName(), and llvm::MultiClass::Rec.
UnOpInit * UnOpInit::get (UnaryOp opc, Init * lhs, RecTy * Type) static
Definition at line 740 of file Record.cpp.
References I.
Referenced by clone(), llvm::StringRecTy::convertValue(), llvm::DagRecTy::convertValue(), GetNewAnonymousName(), and resolveReferences().
std::string UnOpInit::getAsString () const virtual
getAsString - Convert this value to a string form.
Implements llvm::Init.
Definition at line 869 of file Record.cpp.
References llvm::Intrinsic::getType().
virtual int llvm::UnOpInit::getNumOperands () const inline virtual
Implements llvm::OpInit.
Definition at line 908 of file Record.h.
UnaryOp llvm::UnOpInit::getOpcode () const inline
Definition at line 914 of file Record.h.
Referenced by llvm::StringRecTy::convertValue(), and llvm::DagRecTy::convertValue().
virtual Init* llvm::UnOpInit::getOperand (int i) const inline virtual
Implements llvm::OpInit.
Definition at line 909 of file Record.h.
Referenced by llvm::StringRecTy::convertValue(), and llvm::DagRecTy::convertValue().
Init* llvm::UnOpInit::getOperand () const inline
Definition at line 915 of file Record.h.
References llvm::RecTy::getAsString().
Init * UnOpInit::resolveReferences (Record & R, const RecordVal * RV) const virtual
resolveReferences - This method is used by classes that refer to other variables which may not be defined at the time the expression is formed. If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 861 of file Record.cpp.
References get(), llvm::Intrinsic::getType(), and llvm::Init::resolveReferences().
The documentation for this class was generated from the following files:
Record.h
Record.cpp