LLVM: llvm::APFloat Class Reference
LLVM API Documentation
llvm::APFloat Class Reference
A self-contained host- and target-independent arbitrary-precision floating-point software implementation.
#include <APFloat.h>
Public Types
enum cmpResult { cmpLessThan, cmpEqual, cmpGreaterThan, cmpUnordered }
IEEE-754R 5.11: Floating Point Comparison Relations.
enum roundingMode {
rmNearestTiesToEven, rmTowardPositive, rmTowardNegative, rmTowardZero,
rmNearestTiesToAway
}
IEEE-754R 4.3: Rounding-direction attributes.
enum opStatus {
opOK = 0x00, opInvalidOp = 0x01, opDivByZero = 0x02, opOverflow = 0x04,
opUnderflow = 0x08, opInexact = 0x10
}
enum fltCategory { fcInfinity, fcNaN, fcNormal, fcZero }
Category of internally-represented number.
enum uninitializedTag { uninitialized }
Convenience enum used to construct an uninitialized APFloat.
typedef signed short ExponentType
A signed type to represent a floating point numbers unbiased exponent.
Public Member Functions
bool needsCleanup () const
Returns whether this instance allocated memory.
void Profile (FoldingSetNodeID &NID) const
void Emit (Serializer &S) const
Used by the Bitcode serializer to emit APInts to Bitcode.
bool operator== (const APFloat &) const LLVM_DELETED_FUNCTION
cmpResult compare (const APFloat &) const
bool bitwiseIsEqual (const APFloat &) const
Bitwise comparison for equality (QNaNs compare equal, 0!=-0).
unsigned int convertToHexString (char *dst, unsigned int hexDigits, bool upperCase, roundingMode) const
APFloat & operator= (const APFloat &)
void toString (SmallVectorImpl< char > &Str, unsigned FormatPrecision=0, unsigned FormatMaxPadding=3) const
bool getExactInverse (APFloat *inv) const
Constructors
APFloat (const fltSemantics &)
APFloat (const fltSemantics &, StringRef)
APFloat (const fltSemantics &, integerPart)
APFloat (const fltSemantics &, uninitializedTag)
APFloat (const fltSemantics &, const APInt &)
APFloat (double d)
APFloat (float f)
APFloat (const APFloat &)
~APFloat ()
Arithmetic
opStatus add (const APFloat &, roundingMode)
opStatus subtract (const APFloat &, roundingMode)
opStatus multiply (const APFloat &, roundingMode)
opStatus divide (const APFloat &, roundingMode)
opStatus remainder (const APFloat &)
IEEE remainder.
opStatus mod (const APFloat &, roundingMode)
C fmod, or llvm frem.
opStatus fusedMultiplyAdd (const APFloat &, const APFloat &, roundingMode)
opStatus roundToIntegral (roundingMode)
opStatus next (bool nextDown)
IEEE-754R 5.3.1: nextUp/nextDown.
Sign operations.
void changeSign ()
void clearSign ()
void copySign (const APFloat &)
Conversions
opStatus convert (const fltSemantics &, roundingMode, bool *)
opStatus convertToInteger (integerPart *, unsigned int, bool, roundingMode, bool *) const
opStatus convertToInteger (APSInt &, roundingMode, bool *) const
opStatus convertFromAPInt (const APInt &, bool, roundingMode)
opStatus convertFromSignExtendedInteger (const integerPart *, unsigned int, bool, roundingMode)
opStatus convertFromZeroExtendedInteger (const integerPart *, unsigned int, bool, roundingMode)
opStatus convertFromString (StringRef, roundingMode)
APInt bitcastToAPInt () const
double convertToDouble () const
float convertToFloat () const
IEEE-754R 5.7.2 General operations.
bool isNegative () const
bool isNormal () const
bool isFinite () const
bool isZero () const
Returns true if and only if the float is plus or minus zero.
bool isDenormal () const
bool isInfinity () const
IEEE-754R isInfinite(): Returns true if and only if the float is infinity.
bool isNaN () const
Returns true if and only if the float is a quiet or signaling NaN.
bool isSignaling () const
Returns true if and only if the float is a signaling NaN.
Static Public Member Functions
static unsigned int semanticsPrecision (const fltSemantics &)
static APFloat ReadVal (Deserializer &D)
Used by the Bitcode deserializer to deserialize APInts.
Convenience "constructors"
static APFloat getZero (const fltSemantics &Sem, bool Negative=false)
static APFloat getInf (const fltSemantics &Sem, bool Negative=false)
static APFloat getNaN (const fltSemantics &Sem, bool Negative=false, unsigned type=0)
static APFloat getQNaN (const fltSemantics &Sem, bool Negative=false, const APInt *payload=0)
Factory for QNaN values.
static APFloat getSNaN (const fltSemantics &Sem, bool Negative=false, const APInt *payload=0)
Factory for SNaN values.
static APFloat getLargest (const fltSemantics &Sem, bool Negative=false)
static APFloat getSmallest (const fltSemantics &Sem, bool Negative=false)
static APFloat getSmallestNormalized (const fltSemantics &Sem, bool Negative=false)
static APFloat getAllOnesValue (unsigned BitWidth, bool isIEEE=false)
Static Public Attributes
Floating Point Semantics.
static const fltSemantics IEEEhalf = { 15, -14, 11 }
static const fltSemantics IEEEsingle = { 127, -126, 24 }
static const fltSemantics IEEEdouble = { 1023, -1022, 53 }
static const fltSemantics IEEEquad = { 16383, -16382, 113 }
static const fltSemantics PPCDoubleDouble = { 1023, -1022 + 53, 53 + 53 }
static const fltSemantics x87DoubleExtended = { 16383, -16382, 64 }
static const fltSemantics Bogus = { 0, 0, 0 }
Friends
hash_code hash_value (const APFloat &Arg)
Overload to compute a hash code for an APFloat value.
Simple Queries
fltCategory getCategory () const
const fltSemantics & getSemantics () const
bool isNonZero () const
bool isFiniteNonZero () const
bool isPosZero () const
bool isNegZero () const
bool isSmallest () const
bool isLargest () const
Detailed Description
A self-contained host- and target-independent arbitrary-precision floating-point software implementation.
APFloat uses bignum integer arithmetic as provided by static functions in the APInt class. The library will work with bignum integers whose parts are any unsigned type at least 16 bits wide, but 64 bits is recommended.
Written for clarity rather than speed, in particular with a view to use in the front-end of a cross compiler so that target arithmetic can be correctly performed on the host. Performance should nonetheless be reasonable, particularly for its intended use. It may be useful as a base implementation for a run-time library during development of a faster target-specific one.
All 5 rounding modes in the IEEE-754R draft are handled correctly for all implemented operations. Currently implemented operations are add, subtract, multiply, divide, fused-multiply-add, conversion-to-float, conversion-to-integer and conversion-from-integer. New rounding modes (e.g. away from zero) can be added with three or four lines of code.
Four formats are built-in: IEEE single precision, double precision, quadruple precision, and x87 80-bit extended double (when operating with full extended precision). Adding a new format that obeys IEEE semantics only requires adding two lines of code: a declaration and definition of the format.
All operations return the status of that operation as an exception bit-mask, so multiple operations can be done consecutively with their results or-ed together. The returned status can be useful for compiler diagnostics; e.g., inexact, underflow and overflow can be easily diagnosed on constant folding, and compiler optimizers can determine what exceptions would be raised by folding operations and optimize, or perhaps not optimize, accordingly.
At present, underflow tininess is detected after rounding; it should be straight forward to add support for the before-rounding case too.
The library reads hexadecimal floating point numbers as per C99, and correctly rounds if necessary according to the specified rounding mode. Syntax is required to have been validated by the caller. It also converts floating point numbers to hexadecimal text as per the C99 a and A conversions. The output precision (or alternatively the natural minimal precision) can be specified; if the requested precision is less than the natural precision the output is correctly rounded for the specified rounding mode.
It also reads decimal floating point numbers and correctly rounds according to the specified rounding mode.
Conversion to decimal text is not currently implemented.
Non-zero finite numbers are represented internally as a sign bit, a 16-bit signed exponent, and the significand as an array of integer parts. After normalization of a number of precision P the exponent is within the range of the format, and if the number is not denormal the P-th bit of the significand is set as an explicit integer bit. For denormals the most significant bit is shifted right so that the exponent is maintained at the format's minimum, so that the smallest denormal has just the least significant bit of the significand set. The sign of zeroes and infinities is significant; the exponent and significand of such numbers is not stored, but has a known implicit (deterministic) value: 0 for the significands, 0 for zero exponent, all 1 bits for infinity exponent. For NaNs the sign and significand are deterministic, although not really meaningful, and preserved in non-conversion operations. The exponent is implicitly all 1 bits.
APFloat does not provide any exception handling beyond default exception handling. We represent Signaling NaNs via IEEE-754R 2008 6.2.1 should clause by encoding Signaling NaNs with the first bit of its trailing significand as 0.
TODO
Some features that may or may not be worth adding:
Binary to decimal conversion (hard).
Optional ability to detect underflow tininess before rounding.
New formats: x87 in single and double precision mode (IEEE apart from extended exponent range) (hard).
New operations: sqrt, IEEE remainder, C90 fmod, nexttoward.
Definition at line 122 of file APFloat.h.
Member Typedef Documentation
typedef signed short llvm::APFloat::ExponentType
A signed type to represent a floating point numbers unbiased exponent.
Definition at line 126 of file APFloat.h.
Member Enumeration Documentation
enum llvm::APFloat::cmpResult
IEEE-754R 5.11: Floating Point Comparison Relations.
Enumerator
cmpLessThan
cmpEqual
cmpGreaterThan
cmpUnordered
Definition at line 147 of file APFloat.h.
enum llvm::APFloat::fltCategory
Category of internally-represented number.
Enumerator
fcInfinity
fcNaN
fcNormal
fcZero
Definition at line 176 of file APFloat.h.
enum llvm::APFloat::opStatus
IEEE-754R 7: Default exception handling.
opUnderflow or opOverflow are always returned or-ed with opInexact.
Enumerator
opOK
opInvalidOp
opDivByZero
opOverflow
opUnderflow
opInexact
Definition at line 166 of file APFloat.h.
enum llvm::APFloat::roundingMode
IEEE-754R 4.3: Rounding-direction attributes.
Enumerator
rmNearestTiesToEven
rmTowardPositive
rmTowardNegative
rmTowardZero
rmNearestTiesToAway
Definition at line 155 of file APFloat.h.
enum llvm::APFloat::uninitializedTag
Convenience enum used to construct an uninitialized APFloat.
Enumerator
uninitialized
Definition at line 184 of file APFloat.h.
Constructor & Destructor Documentation
APFloat::APFloat (const fltSemantics & ourSemantics)
Definition at line 788 of file APFloat.cpp.
References initialize().
APFloat::APFloat (const fltSemantics & ourSemantics, StringRef text)
Definition at line 799 of file APFloat.cpp.
References initialize().
APFloat::APFloat (const fltSemantics & ourSemantics, integerPart value)
Definition at line 778 of file APFloat.cpp.
References initialize(), llvm::lfExactlyZero, and llvm::fltSemantics::precision.
APFloat::APFloat (const fltSemantics & ourSemantics, uninitializedTag tag)
Definition at line 794 of file APFloat.cpp.
References initialize().
APFloat::APFloat (const fltSemantics & Sem, const APInt & API)
Definition at line 3415 of file APFloat.cpp.
APFloat::APFloat (double d) explicit
Definition at line 3423 of file APFloat.cpp.
References llvm::sys::path::append(), llvm::SmallVectorImpl< T >::append(), llvm::StringRef::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::APInt::doubleToBits(), llvm::StringRef::end(), llvm::SmallVectorImpl< T >::erase(), llvm::APInt::getActiveBits(), llvm::APInt::getBitWidth(), I, N, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::APInt::trunc(), and llvm::APInt::udiv().
APFloat::APFloat (float f) explicit
Definition at line 3419 of file APFloat.cpp.
References llvm::APInt::floatToBits().
APFloat::APFloat (const APFloat & rhs)
Definition at line 804 of file APFloat.cpp.
References initialize().
APFloat::~APFloat ()
Definition at line 809 of file APFloat.cpp.
Member Function Documentation
APFloat::opStatus APFloat::add (const APFloat & rhs, roundingMode rounding_mode)
Definition at line 1642 of file APFloat.cpp.
Referenced by llvm::ConstantFoldBinaryInstruction(), llvm::ExecutionEngine::getConstantValue(), llvm::SelectionDAG::getNode(), and getSNaN().
APInt APFloat::bitcastToAPInt () const
Definition at line 3050 of file APFloat.cpp.
Referenced by llvm::CompileUnit::addConstantFPValue(), emitGlobalConstantFP(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), ExpandUnalignedLoad(), FoldOperand(), ftostr(), llvm::ExecutionEngine::getConstantValue(), llvm::ARM_AM::getFP32Imm(), llvm::ARM_AM::getFP64Imm(), GetFPLibCall(), llvm::SelectionDAG::getNode(), getOpenCLAlignment(), getSNaN(), llvm::HexagonLowerToMC(), llvm::A64Imms::isFPImm(), isUsedIn(), llvm::NVPTXFloatMCExpr::PrintImpl(), and llvm::WriteConstantInternal().
bool APFloat::bitwiseIsEqual (const APFloat & rhs) const
Bitwise comparison for equality (QNaNs compare equal, 0!=-0).
Definition at line 755 of file APFloat.cpp.
References i, and p.
Referenced by ftostr(), getSNaN(), llvm::ConstantFP::isExactlyValue(), llvm::X86TargetLowering::isFPImmLegal(), and llvm::DenseMapAPFloatKeyInfo::KeyTy::operator==().
void APFloat::changeSign ()
Definition at line 1589 of file APFloat.cpp.
Referenced by GetNegatedExpression(), llvm::ConstantFP::getNegativeZero(), llvm::SelectionDAG::getNode(), getSNaN(), isUsedIn(), and llvm::X86TargetLowering::resetOperationActions().
void APFloat::clearSign ()
Definition at line 1596 of file APFloat.cpp.
Referenced by llvm::SelectionDAG::getNode(), getSNaN(), and llvm::InstCombiner::visitFCmpInst().
APFloat::cmpResult APFloat::compare (const APFloat & rhs) const
IEEE comparison with another floating point number (NaNs compare unordered, 0==-0).
Definition at line 1859 of file APFloat.cpp.
References llvm_unreachable, PackCategoriesIntoKey, and result.
Referenced by llvm::ConstantFoldCompareInstruction(), llvm::MDNode::getMostGenericFPMath(), getSNaN(), and llvm::InstCombiner::visitFCmpInst().
APFloat::opStatus APFloat::convert (const fltSemantics & toSemantics, roundingMode rounding_mode, bool * losesInfo)
APFloat::convert - convert a value of one floating point type to another. The return value corresponds to the IEEE754 exceptions. *losesInfo records whether the transformation lost information, i.e. whether converting the result back to the original type will produce the original value (this is almost the same as return value==fsOK, but there are edge cases where this is not so).
Definition at line 1938 of file APFloat.cpp.
References llvm::lfExactlyZero, lostFractionThroughTruncation(), llvm::fltSemantics::minExponent, partCountForBits(), llvm::fltSemantics::precision, shift, shiftRight(), llvm::APInt::tcAssign(), llvm::APInt::tcExtract(), llvm::APInt::tcIncrement(), llvm::APInt::tcLSB(), llvm::APInt::tcMSB(), llvm::APInt::tcNegate(), llvm::APInt::tcSet(), llvm::APInt::tcSetBit(), and llvm::APInt::tcShiftLeft().
Referenced by ConstantFoldBinaryFP(), llvm::ConstantFoldCall(), llvm::ConstantFoldCastInstruction(), ConstantFoldFP(), convertToDouble(), emitDebugValueComment(), FitsInFPType(), ftostr(), FunctionNumber(), llvm::ConstantFP::get(), llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getNode(), getOpenCLAlignment(), getSNaN(), llvm::hash_value(), llvm::ConstantFP::isExactlyValue(), llvm::ConstantFPSDNode::isExactlyValue(), llvm::ConstantFP::isValueValidForType(), llvm::ARMAsmPrinter::lowerOperand(), llvm::NVPTXFloatMCExpr::PrintImpl(), llvm::X86TargetLowering::resetOperationActions(), semanticsPrecision(), llvm::InstCombiner::visitFCmpInst(), and llvm::WriteConstantInternal().
APFloat::opStatus APFloat::convertFromAPInt (const APInt & Val, bool isSigned, roundingMode rounding_mode)
Definition at line 2238 of file APFloat.cpp.
References llvm::APInt::getNumWords(), llvm::APInt::getRawData(), and llvm::APInt::isNegative().
Referenced by llvm::ConstantFoldCastInstruction(), llvm::InstCombiner::FoldFCmp_IntToFP_Cst(), llvm::ExecutionEngine::getConstantValue(), llvm::SelectionDAG::getNode(), getSNaN(), roundToIntegral(), and useSinCos().
APFloat::opStatus APFloat::convertFromSignExtendedInteger (const integerPart * src, unsigned int srcCount, bool isSigned, roundingMode rounding_mode)
Definition at line 2258 of file APFloat.cpp.
References llvm::integerPartWidth, llvm::sys::fs::status(), llvm::APInt::tcAssign(), llvm::APInt::tcExtractBit(), and llvm::APInt::tcNegate().
Referenced by getSNaN().
APFloat::opStatus APFloat::convertFromString (StringRef str, roundingMode rounding_mode)
Definition at line 2611 of file APFloat.cpp.
References llvm::StringRef::begin(), llvm::StringRef::empty(), p, and llvm::StringRef::size().
Referenced by getSNaN(), and isUsedIn().
APFloat::opStatus APFloat::convertFromZeroExtendedInteger (const integerPart * parts, unsigned int width, bool isSigned, roundingMode rounding_mode)
Definition at line 2286 of file APFloat.cpp.
References llvm::sys::path::begin(), llvm::StringRef::begin(), decDigitValue(), llvm::sys::path::end(), llvm::StringRef::end(), llvm::StringRef::equals(), llvm::Intrinsic::exp, decimalInfo::exponent, decimalInfo::firstSigDigit, llvm::APInt::getRawData(), getZero(), llvm::hexDigitValue(), HUerrBound(), llvm::integerPartWidth, interpretDecimal(), decimalInfo::lastSigDigit, llvm::lfExactlyZero, llvm::lfLessThanHalf, lostFractionThroughTruncation(), llvm::makeArrayRef(), llvm::maxPowerOfFiveParts, decimalInfo::normalizedExponent, p, partCountForBits(), powerOf5(), llvm::fltSemantics::precision, s, skipLeadingZeroesAndAnyDot(), llvm::APInt::tcExtract(), llvm::APInt::tcExtractBit(), llvm::APInt::tcMultiplyPart(), totalExponent(), trailingHexadecimalFraction(), ulpsFromBoundary(), and val.
Referenced by getSNaN(), mod(), and remainder().
double APFloat::convertToDouble () const
Definition at line 3082 of file APFloat.cpp.
References llvm::ARM_AM::add, llvm::APInt::bitsToDouble(), convert(), llvm::APInt::getBitWidth(), llvm::APInt::getRawData(), i, initialize(), and llvm_unreachable.
Referenced by llvm::ConstantFoldCall(), emitDebugValueComment(), ftostr(), getOpenCLAlignment(), getSNaN(), and llvm::ARMAsmPrinter::lowerOperand().
float APFloat::convertToFloat () const
Definition at line 3073 of file APFloat.cpp.
References llvm::APInt::bitsToFloat().
Referenced by emitDebugValueComment(), FoldOperand(), ftostr(), llvm::FPMathOperator::getFPAccuracy(), getOpenCLAlignment(), getSNaN(), and llvm::AMDGPUMCInstLower::lower().
unsigned int APFloat::convertToHexString (char * dst, unsigned int hexDigits, bool upperCase, roundingMode rounding_mode) const
Write out a hexadecimal representation of the floating point value to DST, which must be of sufficient size, in the C99 form [-]0xh.hhhhp[+-]d. Return the number of characters written, excluding the terminating NUL.
Definition at line 2663 of file APFloat.cpp.
References hexDigitsLower, llvm::hexDigitValue(), llvm::integerPartWidth, lostFractionThroughTruncation(), llvm::Intrinsic::memcpy, llvm::Intrinsic::memset, p, partAsHex(), shift, and writeSignedDecimal().
Referenced by getSNaN().
APFloat::opStatus APFloat::convertToInteger (integerPart * parts, unsigned int width, bool isSigned, roundingMode rounding_mode, bool * isExact) const
Definition at line 2157 of file APFloat.cpp.
References partCountForBits(), llvm::APInt::tcSetLeastSignificantBits(), and llvm::APInt::tcShiftLeft().
Referenced by llvm::ConstantFoldCastInstruction(), ConstantFoldConvertToInt(), ConvertToSInt(), llvm::ExecutionEngine::getConstantValue(), llvm::SelectionDAG::getNode(), llvm::FastISel::getRegForValue(), getSNaN(), isConstVecPow2(), mod(), and remainder().
APFloat::opStatus APFloat::convertToInteger (APSInt & result, roundingMode rounding_mode, bool * isExact) const
Definition at line 2191 of file APFloat.cpp.
References llvm::APInt::getBitWidth(), llvm::APInt::getNumWords(), llvm::APSInt::isSigned(), llvm::lfExactlyZero, lostFractionThroughTruncation(), llvm::fltSemantics::precision, llvm::sys::fs::status(), llvm::APInt::tcExtract(), and llvm::APInt::tcMSB().
void APFloat::copySign (const APFloat & rhs)
Definition at line 1603 of file APFloat.cpp.
References llvm::lfExactlyZero.
Referenced by llvm::SelectionDAG::getNode(), getSNaN(), and roundToIntegral().
APFloat::opStatus APFloat::divide (const APFloat & rhs, roundingMode rounding_mode)
Definition at line 1675 of file APFloat.cpp.
References llvm::lfExactlyZero.
Referenced by llvm::ConstantFoldBinaryInstruction(), getBuildPairElt(), llvm::ExecutionEngine::getConstantValue(), getExactInverse(), llvm::SelectionDAG::getNode(), getSNaN(), mod(), and remainder().
void llvm::APFloat::Emit (Serializer & S) const
Used by the Bitcode serializer to emit APInts to Bitcode.
Referenced by getSNaN().
APFloat::opStatus APFloat::fusedMultiplyAdd (const APFloat & multiplicand, const APFloat & addend, roundingMode rounding_mode)
Definition at line 1771 of file APFloat.cpp.
References isFiniteNonZero(), and llvm::lfExactlyZero.
Referenced by llvm::SelectionDAG::getNode(), and getSNaN().
APFloat APFloat::getAllOnesValue (unsigned BitWidth, bool isIEEE = false) static
Returns a float which is bitcasted from an all one value int.
Parameters
BitWidth - Select float type
isIEEE - If 128 bit number, select between PPC and IEEE
Definition at line 3320 of file APFloat.cpp.
References llvm::lltok::APFloat, llvm::APInt::getAllOnesValue(), llvm::integerPartWidth, llvm_unreachable, llvm::Intrinsic::memset, and llvm::APInt::tcSet().
Referenced by llvm::Constant::getAllOnesValue(), and getSNaN().
fltCategory llvm::APFloat::getCategory () const inline
Definition at line 396 of file APFloat.h.
bool APFloat::getExactInverse (APFloat * inv) const
If this value has an exact multiplicative inverse, store it in inv and return true.
Definition at line 3714 of file APFloat.cpp.
References divide(), isDenormal(), isFiniteNonZero(), and llvm::fltSemantics::precision.
Referenced by CvtFDivConstToReciprocal(), and isNegZero().
static APFloat llvm::APFloat::getInf (const fltSemantics & Sem, bool Negative = false) inline static
Factory for Positive and Negative Infinity.
Parameters
Negative True iff the number should be negative.
Definition at line 221 of file APFloat.h.
References uninitialized.
Referenced by llvm::ConstantFP::getInfinity(), and isUsedIn().
APFloat APFloat::getLargest (const fltSemantics & Sem, bool Negative = false) static
Returns the largest finite number in the given semantics.
Parameters
Negative - True iff the number should be negative
Definition at line 3377 of file APFloat.cpp.
Referenced by getSNaN().
static APFloat llvm::APFloat::getNaN (const fltSemantics & Sem, bool Negative = false, unsigned type = 0) inline static
Factory for QNaN values.
Parameters
Negative - True iff the NaN generated should be negative.
type - The unspecified fill bits for creating the NaN, 0 by default. The value is truncated as necessary.
Definition at line 232 of file APFloat.h.
References getQNaN(), and type.
Referenced by isUsedIn().
static APFloat llvm::APFloat::getQNaN (const fltSemantics & Sem, bool Negative = false, const APInt * payload = 0) inline static
Factory for QNaN values.
Definition at line 243 of file APFloat.h.
Referenced by getNaN().
const fltSemantics& llvm::APFloat::getSemantics () const inline
Definition at line 397 of file APFloat.h.
Referenced by llvm::ConstantFP::ConstantFP(), CvtFDivConstToReciprocal(), llvm::InstCombiner::FoldFCmp_IntToFP_Cst(), ftostr(), FunctionNumber(), llvm::ConstantFP::get(), getBuildPairElt(), llvm::ConstantFP::isExactlyValue(), llvm::ConstantFPSDNode::isExactlyValue(), llvm::A64Imms::isFPImm(), llvm::ConstantFP::isValueValidForType(), and llvm::AMDGPUMCInstLower::lower().
APFloat APFloat::getSmallest (const fltSemantics & Sem, bool Negative = false) static
Returns the smallest (by magnitude) finite number in the given semantics. Might be denormalized, which implies a relative loss of precision.
Parameters
Negative - True iff the number should be negative
Definition at line 3387 of file APFloat.cpp.
Referenced by getSNaN().
APFloat APFloat::getSmallestNormalized (const fltSemantics & Sem, bool Negative = false) static
Returns the smallest (by magnitude) normalized finite number in the given semantics.
Parameters
Negative - True iff the number should be negative
Definition at line 3397 of file APFloat.cpp.
References llvm::integerPartWidth, llvm::fltSemantics::minExponent, partCountForBits(), and llvm::fltSemantics::precision.
Referenced by getSNaN(), and llvm::InstCombiner::visitFCmpInst().
static APFloat llvm::APFloat::getSNaN (const fltSemantics & Sem, bool Negative = false, const APInt * payload = 0) inline static
Factory for SNaN values.
Definition at line 249 of file APFloat.h.
References add(), bitcastToAPInt(), bitwiseIsEqual(), changeSign(), clearSign(), compare(), convert(), convertFromAPInt(), convertFromSignExtendedInteger(), convertFromString(), convertFromZeroExtendedInteger(), convertToDouble(), convertToFloat(), convertToHexString(), convertToInteger(), copySign(), divide(), Emit(), fusedMultiplyAdd(), getAllOnesValue(), getLargest(), getSmallest(), getSmallestNormalized(), LLVM_DELETED_FUNCTION, mod(), multiply(), next(), operator==(), Profile(), ReadVal(), remainder(), roundToIntegral(), S, and subtract().
static APFloat llvm::APFloat::getZero (const fltSemantics & Sem, bool Negative = false) inline static
Factory for Positive and Negative Zero.
Parameters
Negative True iff the number should be negative.
Definition at line 212 of file APFloat.h.
References uninitialized.
Referenced by convertFromZeroExtendedInteger(), llvm::ExecutionEngine::getConstantValue(), llvm::Constant::getNullValue(), and llvm::X86TargetLowering::resetOperationActions().
bool APFloat::isDenormal () const
IEEE-754R isSubnormal(): Returns true if and only if the float is a denormal.
Definition at line 687 of file APFloat.cpp.
References llvm::APInt::tcExtractBit().
Referenced by getExactInverse(), isNormal(), and isZero().
bool llvm::APFloat::isFinite () const inline
Returns true if and only if the current value is zero, subnormal, or normal.
This means that the value is not infinite or NaN.
Definition at line 373 of file APFloat.h.
References isInfinity(), and isNaN().
Referenced by isFiniteNonZero().
bool llvm::APFloat::isFiniteNonZero () const inline
Definition at line 399 of file APFloat.h.
References isFinite(), and isZero().
Referenced by CvtFDivConstToReciprocal(), fusedMultiplyAdd(), getExactInverse(), llvm::hash_value(), isContiguous(), isFMulOrFDivWithConstant(), isNormal(), mod(), semanticsPrecision(), and llvm::InstCombiner::visitFMul().
bool llvm::APFloat::isInfinity () const inline
IEEE-754R isInfinite(): Returns true if and only if the float is infinity.
Definition at line 383 of file APFloat.h.
References fcInfinity.
Referenced by isFinite().
bool APFloat::isLargest () const
Returns true if and only if the number has the largest possible finite magnitude in the current semantics.
Definition at line 747 of file APFloat.cpp.
Referenced by isNegZero().
bool llvm::APFloat::isNaN () const inline
Returns true if and only if the float is a quiet or signaling NaN.
Definition at line 386 of file APFloat.h.
References fcNaN, and isSignaling().
Referenced by llvm::InstCombiner::FoldFCmp_IntToFP_Cst(), llvm::hash_value(), isFinite(), and llvm::ConstantFP::isNaN().
bool llvm::APFloat::isNegative () const inline
IEEE-754R isSignMinus: Returns true if and only if the current value is negative.
This applies to zeros and NaNs as well.
Definition at line 361 of file APFloat.h.
Referenced by llvm::InstCombiner::FoldFCmp_IntToFP_Cst(), getBuildPairElt(), isContiguous(), llvm::A64Imms::isFPImm(), llvm::ConstantFP::isNegative(), isNegZero(), and isPosZero().
bool llvm::APFloat::isNegZero () const inline
Definition at line 401 of file APFloat.h.
References getExactInverse(), hash_value, isLargest(), isNegative(), isSmallest(), isZero(), operator=(), and toString().
Referenced by llvm::SystemZTargetLowering::isFPImmLegal(), and parsePhysicalReg().
bool llvm::APFloat::isNonZero () const inline
Definition at line 398 of file APFloat.h.
References fcZero.
bool llvm::APFloat::isNormal () const inline
IEEE-754R isNormal: Returns true if and only if the current value is normal.
This implies that the current value of the float is not zero, subnormal, infinite, or NaN following the definition of normality from IEEE-754R.
Definition at line 367 of file APFloat.h.
References isDenormal(), and isFiniteNonZero().
Referenced by isNormalFp(), and llvm::InstCombiner::visitFDiv().
bool llvm::APFloat::isPosZero () const inline
Definition at line 400 of file APFloat.h.
References isNegative(), and isZero().
bool APFloat::isSignaling () const
Returns true if and only if the float is a signaling NaN.
Definition at line 3743 of file APFloat.cpp.
References llvm::APInt::tcExtractBit().
Referenced by isNaN().
bool APFloat::isSmallest () const
Returns true if and only if the number has the smallest possible non-zero magnitude in the current semantics.
Definition at line 694 of file APFloat.cpp.
References i, and llvm::integerPartWidth.
Referenced by isNegZero().
bool llvm::APFloat::isZero () const inline
Returns true if and only if the float is plus or minus zero.
Definition at line 376 of file APFloat.h.
References fcZero, and isDenormal().
Referenced by llvm::InstCombiner::FoldFCmp_IntToFP_Cst(), getBuildPairElt(), isFiniteNonZero(), llvm::SystemZTargetLowering::isFPImmLegal(), isNegZero(), isPosZero(), llvm::ConstantFP::isZero(), parsePhysicalReg(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitSelectInst(), and llvm::InstCombiner::visitSub().
APFloat::opStatus APFloat::mod (const APFloat & rhs, roundingMode rounding_mode)
C fmod, or llvm frem.
Definition at line 1731 of file APFloat.cpp.
References convertFromZeroExtendedInteger(), convertToInteger(), divide(), llvm::integerPartWidth, isFiniteNonZero(), isZero(), and multiply().
Referenced by llvm::ConstantFoldBinaryInstruction(), llvm::ExecutionEngine::getConstantValue(), llvm::SelectionDAG::getNode(), and getSNaN().
APFloat::opStatus APFloat::multiply (const APFloat & rhs, roundingMode rounding_mode)
Definition at line 1656 of file APFloat.cpp.
References llvm::lfExactlyZero.
Referenced by llvm::ConstantFoldBinaryInstruction(), llvm::ExecutionEngine::getConstantValue(), llvm::SelectionDAG::getNode(), getSNaN(), mod(), and remainder().
bool llvm::APFloat::needsCleanup () const inline
Returns whether this instance allocated memory.
Definition at line 204 of file APFloat.h.
APFloat::opStatus APFloat::next (bool nextDown)
IEEE-754R 5.3.1: nextUp/nextDown.
IEEE-754R 2008 5.3.1: nextUp/nextDown.
NOTE since nextDown(x) = -nextUp(-x), we only implement nextUp with appropriate sign switching before/after the computation.
Definition at line 3756 of file APFloat.cpp.
References result, llvm::APInt::tcDecrement(), llvm::APInt::tcSet(), and llvm::APInt::tcSetBit().
Referenced by getSNaN().
APFloat & APFloat::operator= (const APFloat & rhs)
Definition at line 673 of file APFloat.cpp.
References initialize().
Referenced by isNegZero().
bool llvm::APFloat::operator== (const APFloat &) const
The definition of equality is not straightforward for floating point, so we won't use operator==. Use one of the following, or write whatever it is you really mean.
Referenced by getSNaN().
void APFloat::Profile (FoldingSetNodeID & NID) const
Used to insert APFloat objects, or objects that contain APFloat objects, into FoldingSets.
Definition at line 815 of file APFloat.cpp.
References llvm::FoldingSetNodeID::Add(), and partCountForBits().
Referenced by getSNaN().
static APFloat llvm::APFloat::ReadVal (Deserializer & D) static
Used by the Bitcode deserializer to deserialize APInts.
Referenced by getSNaN().
APFloat::opStatus APFloat::remainder (const APFloat & rhs)
IEEE remainder.
Definition at line 1694 of file APFloat.cpp.
References convertFromZeroExtendedInteger(), convertToInteger(), divide(), llvm::integerPartWidth, isZero(), and multiply().
Referenced by getSNaN().
APFloat::opStatus APFloat::roundToIntegral (roundingMode rounding_mode)
Definition at line 1815 of file APFloat.cpp.
References llvm::ARM_AM::add, convertFromAPInt(), copySign(), and llvm::NextPowerOf2().
Referenced by llvm::SelectionDAG::getNode(), and getSNaN().
unsigned int APFloat::semanticsPrecision (const fltSemantics & semantics) static
Definition at line 826 of file APFloat.cpp.
References bit, cmp, combineLostFractions(), convert(), i, isFiniteNonZero(), llvm::lfExactlyHalf, llvm::lfExactlyZero, llvm::lfLessThanHalf, llvm::lfMoreThanHalf, llvm_unreachable, llvm::fltSemantics::minExponent, PackCategoriesIntoKey, partCountForBits(), llvm::fltSemantics::precision, shiftRight(), llvm::sys::fs::status(), llvm::APInt::tcAdd(), llvm::APInt::tcAssign(), llvm::APInt::tcCompare(), llvm::APInt::tcExtractBit(), llvm::APInt::tcFullMultiply(), llvm::APInt::tcIncrement(), llvm::APInt::tcIsZero(), llvm::APInt::tcLSB(), llvm::APInt::tcMSB(), llvm::APInt::tcSet(), llvm::APInt::tcSetBit(), llvm::APInt::tcSetLeastSignificantBits(), llvm::APInt::tcShiftLeft(), and llvm::APInt::tcSubtract().
Referenced by llvm::A64Imms::isFPImm().
APFloat::opStatus APFloat::subtract (const APFloat & rhs, roundingMode rounding_mode)
Definition at line 1649 of file APFloat.cpp.
Referenced by llvm::ConstantFoldBinaryInstruction(), llvm::ExecutionEngine::getConstantValue(), llvm::SelectionDAG::getNode(), getSNaN(), and llvm::hash_value().
void APFloat::toString (SmallVectorImpl< char > & Str, unsigned FormatPrecision = 0, unsigned FormatMaxPadding = 3) const
Converts this value into a decimal string.
Parameters
FormatPrecision The maximum number of digits of precision to output. If there are fewer digits available, zero padding will not be used unless the value is integral and small enough to be expressed in FormatPrecision digits. 0 means to use the natural precision of the number.
FormatMaxPadding The maximum number of zeros to consider inserting before falling back to scientific notation. 0 means to always use scientific notation.
Number Precision MaxPadding Result
1.01E+4 5 2 10100 1.01E+4 4 2 1.01E+4 1.01E+4 5 1 1.01E+4 1.01E-2 5 2 0.0101 1.01E-2 4 2 0.0101 1.01E-2 4 1 1.01E-2
Definition at line 3511 of file APFloat.cpp.
References llvm::sys::path::append(), llvm::APInt::countTrailingZeros(), d, llvm::SmallVectorBase::empty(), llvm::Intrinsic::exp, llvm::APInt::getBitWidth(), llvm::APInt::getZExtValue(), I, int, llvm::APInt::lshr(), llvm::makeArrayRef(), partCountForBits(), llvm::fltSemantics::precision, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::APInt::udivrem(), and llvm::APInt::zext().
Referenced by emitGlobalConstantFP(), and isNegZero().
Friends And Related Function Documentation
hash_code hash_value (const APFloat & Arg) friend
Overload to compute a hash code for an APFloat value.
Note that the use of hash codes for floating point values is in general frought with peril. Equality is hard to define for these values. For example, should negative and positive zero hash to different codes? Are they equal or not? This hash value implementation specifically emphasizes producing different codes for different inputs in order to be used in canonicalization and memoization. As such, equality is bitwiseIsEqual, and 0 != -0.
See friend declaration above.
This additional declaration is required in order to compile LLVM with IBM xlC compiler.
Referenced by isNegZero().
Member Data Documentation
const fltSemantics llvm::APFloat::Bogus = { 0, 0, 0 } static
A Pseudo fltsemantic used to construct APFloats that cannot conflict with anything real.
Definition at line 140 of file APFloat.h.
Referenced by llvm::ConstantFoldCastInstruction(), llvm::DenseMapAPFloatKeyInfo::getEmptyKey(), and llvm::DenseMapAPFloatKeyInfo::getTombstoneKey().
const fltSemantics llvm::APFloat::IEEEdouble = { 1023, -1022, 53 } static
Definition at line 133 of file APFloat.h.
Referenced by llvm::X86TargetLowering::BuildFILD(), llvm::ConstantFoldCall(), llvm::ConstantFoldCastInstruction(), emitDebugValueComment(), llvm::SelectionDAG::EVTToAPFloatSemantics(), ftostr(), FunctionNumber(), llvm::ConstantFP::get(), getBinOpPrecedence(), getDRegFromQReg(), llvm::Type::getFltSemantics(), llvm::SelectionDAG::getNode(), llvm::Constant::getNullValue(), getOpenCLAlignment(), llvm::ConstantFP::isValueValidForType(), LookThroughFPExtensions(), llvm::AArch64TargetLowering::LowerBUILD_VECTOR(), LowerFP_EXTEND(), llvm::ARMAsmPrinter::lowerOperand(), llvm::SDNode::print_details(), llvm::NVPTXFloatMCExpr::PrintImpl(), ReadWideAPInt(), TypeToFloatSemantics(), llvm::InstCombiner::visitFCmpInst(), and llvm::WriteConstantInternal().
const fltSemantics llvm::APFloat::IEEEhalf = { 15, -14, 11 } static
Definition at line 131 of file APFloat.h.
Referenced by ConstantFoldBinaryFP(), llvm::ConstantFoldCall(), llvm::ConstantFoldCastInstruction(), ConstantFoldFP(), llvm::SelectionDAG::EVTToAPFloatSemantics(), FunctionNumber(), llvm::ConstantFP::get(), llvm::LLLexer::getFilename(), llvm::Type::getFltSemantics(), llvm::Constant::getNullValue(), llvm::ConstantFP::isValueValidForType(), LookThroughFPExtensions(), ReadWideAPInt(), TypeToFloatSemantics(), llvm::InstCombiner::visitFCmpInst(), and llvm::WriteConstantInternal().
const fltSemantics llvm::APFloat::IEEEquad = { 16383, -16382, 113 } static
Definition at line 134 of file APFloat.h.
Referenced by llvm::ConstantFoldCastInstruction(), llvm::SelectionDAG::EVTToAPFloatSemantics(), llvm::ConstantFP::get(), llvm::LLLexer::getFilename(), llvm::Type::getFltSemantics(), llvm::Constant::getNullValue(), llvm::ConstantFP::isValueValidForType(), ReadWideAPInt(), TypeToFloatSemantics(), llvm::InstCombiner::visitFCmpInst(), and llvm::WriteConstantInternal().
const fltSemantics llvm::APFloat::IEEEsingle = { 127, -126, 24 } static
Definition at line 132 of file APFloat.h.
Referenced by llvm::ConstantFoldCall(), llvm::ConstantFoldCastInstruction(), llvm::SelectionDAG::EVTToAPFloatSemantics(), ftostr(), FunctionNumber(), llvm::ConstantFP::get(), getBinOpPrecedence(), getDRegFromQReg(), getF32Constant(), llvm::Type::getFltSemantics(), llvm::SelectionDAG::getNode(), llvm::Constant::getNullValue(), getOpenCLAlignment(), llvm::ConstantFP::isValueValidForType(), LookThroughFPExtensions(), llvm::AMDGPUMCInstLower::lower(), llvm::AArch64TargetLowering::LowerBUILD_VECTOR(), LowerFP_EXTEND(), llvm::SDNode::print_details(), llvm::NVPTXFloatMCExpr::PrintImpl(), ReadWideAPInt(), TypeToFloatSemantics(), llvm::InstCombiner::visitFCmpInst(), and llvm::WriteConstantInternal().
const fltSemantics llvm::APFloat::PPCDoubleDouble = { 1023, -1022 + 53, 53 + 53 } static
Definition at line 135 of file APFloat.h.
Referenced by llvm::ConstantFoldCastInstruction(), llvm::SelectionDAG::EVTToAPFloatSemantics(), llvm::ConstantFP::get(), llvm::LLLexer::getFilename(), llvm::Type::getFltSemantics(), GetFPLibCall(), llvm::Constant::getNullValue(), llvm::ConstantFP::isValueValidForType(), ReadWideAPInt(), TypeToFloatSemantics(), llvm::InstCombiner::visitFCmpInst(), and llvm::WriteConstantInternal().
const fltSemantics llvm::APFloat::x87DoubleExtended = { 16383, -16382, 64 } static
Definition at line 136 of file APFloat.h.
Referenced by llvm::ConstantFoldCastInstruction(), llvm::SelectionDAG::EVTToAPFloatSemantics(), llvm::ConstantFP::get(), llvm::ExecutionEngine::getConstantValue(), llvm::LLLexer::getFilename(), llvm::Type::getFltSemantics(), llvm::Constant::getNullValue(), llvm::ConstantFP::isValueValidForType(), ReadWideAPInt(), llvm::X86TargetLowering::resetOperationActions(), TypeToFloatSemantics(), llvm::InstCombiner::visitFCmpInst(), and llvm::WriteConstantInternal().
The documentation for this class was generated from the following files:
APFloat.h
APFloat.cpp