LLVM: llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug > Class Template Reference
LLVM API Documentation
llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug > Class Template Reference
#include <MachineRegisterInfo.h>
Public Types
typedef std::iterator< std::forward_iterator_tag, MachineInstr, ptrdiff_t >::reference reference
typedef std::iterator< std::forward_iterator_tag, MachineInstr, ptrdiff_t >::pointer pointer
Public Member Functions
defusechain_iterator (const defusechain_iterator &I)
defusechain_iterator ()
bool operator== (const defusechain_iterator &x) const
bool operator!= (const defusechain_iterator &x) const
bool atEnd () const
atEnd - return true if this iterator is equal to reg_end() on the value.
defusechain_iterator & operator++ ()
defusechain_iterator operator++ (int)
MachineInstr * skipInstruction ()
MachineInstr * skipBundle ()
MachineOperand & getOperand () const
unsigned getOperandNo () const
MachineInstr & operator* () const
MachineInstr * operator-> () const
Friends
class MachineRegisterInfo
Detailed Description
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug>
class llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug >
reg_begin/reg_end - Provide iteration support to walk over all definitions and uses of a register within the MachineFunction that corresponds to this MachineRegisterInfo object.
defusechain_iterator - This class provides iterator support for machine operands in the function that use or define a specific register. If ReturnUses is true it returns uses of registers, if ReturnDefs is true it returns defs. If neither are true then you are silly and it always returns end(). If SkipDebug is true it skips uses marked Debug when incrementing.
Definition at line 204 of file MachineRegisterInfo.h.
Member Typedef Documentation
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug> typedef std::iterator<std::forward_iterator_tag, MachineInstr, ptrdiff_t>::pointer llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug >::pointer
Definition at line 574 of file MachineRegisterInfo.h.
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug> typedef std::iterator<std::forward_iterator_tag, MachineInstr, ptrdiff_t>::reference llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug >::reference
Definition at line 572 of file MachineRegisterInfo.h.
Constructor & Destructor Documentation
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug> llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug >::defusechain_iterator (const defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug > & I) inline
Definition at line 576 of file MachineRegisterInfo.h.
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug> llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug >::defusechain_iterator () inline
Definition at line 577 of file MachineRegisterInfo.h.
Member Function Documentation
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug> bool llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug >::atEnd () const inline
atEnd - return true if this iterator is equal to reg_end() on the value.
Definition at line 587 of file MachineRegisterInfo.h.
Referenced by llvm::MachineRegisterInfo::getVRegDef(), and llvm::MachineTraceMetrics::Ensemble::verify().
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug> MachineOperand& llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug >::getOperand () const inline
Definition at line 634 of file MachineRegisterInfo.h.
Referenced by VerifyPHIs().
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug> unsigned llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug >::getOperandNo () const inline
getOperandNo - Return the operand # of this MachineOperand in its MachineInstr.
Definition at line 641 of file MachineRegisterInfo.h.
Referenced by llvm::FastISel::tryToFoldLoad(), and llvm::MachineTraceMetrics::Ensemble::verify().
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug> bool llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug >::operator!= (const defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug > & x) const inline
Definition at line 582 of file MachineRegisterInfo.h.
References llvm::operator==().
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug> MachineInstr& llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug >::operator* () const inline
Definition at line 647 of file MachineRegisterInfo.h.
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug> defusechain_iterator& llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug >::operator++ () inline
Definition at line 590 of file MachineRegisterInfo.h.
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug> defusechain_iterator llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug >::operator++ (int) inline
Definition at line 611 of file MachineRegisterInfo.h.
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug> MachineInstr* llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug >::operator-> () const inline
Definition at line 652 of file MachineRegisterInfo.h.
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug> bool llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug >::operator== (const defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug > & x) const inline
Definition at line 579 of file MachineRegisterInfo.h.
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug> MachineInstr* llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug >::skipBundle () inline
Definition at line 626 of file MachineRegisterInfo.h.
References llvm::getBundleStart(), and llvm::A64CC::MI.
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug> MachineInstr* llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug >::skipInstruction () inline
skipInstruction - move forward until reaching a different instruction. Return the skipped instruction that is no longer pointed to, or NULL if already pointing to end().
Definition at line 618 of file MachineRegisterInfo.h.
References llvm::A64CC::MI.
Referenced by findUseBetween(), and llvm::LiveIntervals::HMEditor::updateAllRanges().
Friends And Related Function Documentation
template<bool ReturnUses, bool ReturnDefs, bool SkipDebug> friend class MachineRegisterInfo friend
Definition at line 569 of file MachineRegisterInfo.h.
The documentation for this class was generated from the following file:
MachineRegisterInfo.h