LLVM: llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass > Class Template Reference
LLVM API Documentation
llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass > Class Template Reference
#include <Argument.h>
Public Member Functions
SymbolTableListTraits ()
ItemParentClass * getListOwner ()
void addNodeToList (ValueSubClass *V)
void removeNodeFromList (ValueSubClass *V)
void transferNodesFromList (ilist_traits< ValueSubClass > &L2, ilist_iterator< ValueSubClass > first, ilist_iterator< ValueSubClass > last)
template<typename TPtr >
void setSymTabObject (TPtr *, TPtr)
Public Member Functions inherited from llvm::ilist_node_traits< ValueSubClass >
void addNodeToList (ValueSubClass *)
void removeNodeFromList (ValueSubClass *)
void transferNodesFromList (ilist_node_traits &, ilist_iterator< ValueSubClass >, ilist_iterator< ValueSubClass >)
Static Public Member Functions
static iplist< ValueSubClass > & getList (ItemParentClass *Par)
static ValueSymbolTable * getSymTab (ItemParentClass *Par)
static ValueSymbolTable * toPtr (ValueSymbolTable *P)
static ValueSymbolTable * toPtr (ValueSymbolTable &R)
Static Public Member Functions inherited from llvm::ilist_nextprev_traits< ValueSubClass >
static ValueSubClass * getPrev (ValueSubClass *N)
static const ValueSubClass * getPrev (const ValueSubClass *N)
static ValueSubClass * getNext (ValueSubClass *N)
static const ValueSubClass * getNext (const ValueSubClass *N)
static void setPrev (ValueSubClass *N, ValueSubClass *Prev)
static void setNext (ValueSubClass *N, ValueSubClass *Next)
Static Public Member Functions inherited from llvm::ilist_sentinel_traits< ValueSubClass >
static ValueSubClass * createSentinel ()
createSentinel - create the dynamic sentinel
static void destroySentinel (ValueSubClass *N)
destroySentinel - deallocate the dynamic sentinel
static ValueSubClass * provideInitialHead ()
static ValueSubClass * ensureHead (ValueSubClass *&Head)
static void noteHead (ValueSubClass *NewHead, ValueSubClass *Sentinel)
noteHead - stash the sentinel into its default location
Static Public Member Functions inherited from llvm::ilist_node_traits< ValueSubClass >
static ValueSubClass * createNode (const ValueSubClass &V)
static void deleteNode (ValueSubClass *V)
Detailed Description
template<typename ValueSubClass, typename ItemParentClass>
class llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >
Definition at line 25 of file Argument.h.
Constructor & Destructor Documentation
template<typename ValueSubClass, typename ItemParentClass> llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::SymbolTableListTraits () inline
Definition at line 44 of file SymbolTableListTraits.h.
Member Function Documentation
template<typename ValueSubClass, typename ItemParentClass > void llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::addNodeToList (ValueSubClass * V)
Definition at line 67 of file SymbolTableListTraitsImpl.h.
References getSymTab(), llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::removeNodeFromList(), and llvm::A64DB::ST.
Referenced by llvm::SymbolTableListTraits< BasicBlock, Function >::getSymTab(), and llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::setSymTabObject().
template<typename ValueSubClass, typename ItemParentClass> static iplist<ValueSubClass>& llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::getList (ItemParentClass * Par) inline static
Definition at line 56 of file SymbolTableListTraits.h.
template<typename ValueSubClass, typename ItemParentClass> ItemParentClass* llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::getListOwner () inline
getListOwner - Return the object that owns this list. If this is a list of instructions, it returns the BasicBlock that owns them.
Definition at line 48 of file SymbolTableListTraits.h.
template<typename ValueSubClass, typename ItemParentClass> static ValueSymbolTable* llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::getSymTab (ItemParentClass * Par) inline static
Definition at line 60 of file SymbolTableListTraits.h.
template<typename ValueSubClass, typename ItemParentClass > void llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::removeNodeFromList (ValueSubClass * V)
Definition at line 78 of file SymbolTableListTraitsImpl.h.
References getSymTab(), llvm::A64DB::ST, and llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::transferNodesFromList().
Referenced by llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::addNodeToList(), and llvm::SymbolTableListTraits< BasicBlock, Function >::getSymTab().
template<typename ValueSubClass , typename ItemParentClass > template<typename TPtr > void llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::setSymTabObject (TPtr * Dest, TPtr Src)
setSymTabObject - This is called when (f.e.) the parent of a basic block changes. This requires us to remove all the instruction symtab entries from the current function and reinsert them into the new function.
Definition at line 30 of file SymbolTableListTraitsImpl.h.
References llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::addNodeToList(), llvm::iplist< NodeTy, Traits >::begin(), llvm::iplist< NodeTy, Traits >::empty(), llvm::iplist< NodeTy, Traits >::end(), getSymTab(), and I.
Referenced by llvm::SymbolTableListTraits< BasicBlock, Function >::getSymTab(), and llvm::BasicBlock::~BasicBlock().
template<typename ValueSubClass, typename ItemParentClass> static ValueSymbolTable* llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::toPtr (ValueSymbolTable * P) inline static
Definition at line 72 of file SymbolTableListTraits.h.
Referenced by llvm::SymbolTableListTraits< BasicBlock, Function >::getSymTab().
template<typename ValueSubClass, typename ItemParentClass> static ValueSymbolTable* llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::toPtr (ValueSymbolTable & R) inline static
Definition at line 73 of file SymbolTableListTraits.h.
template<typename ValueSubClass, typename ItemParentClass > void llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::transferNodesFromList (ilist_traits< ValueSubClass > & L2, ilist_iterator< ValueSubClass > first, ilist_iterator< ValueSubClass > last)
Definition at line 87 of file SymbolTableListTraitsImpl.h.
References getSymTab().
Referenced by llvm::SymbolTableListTraits< BasicBlock, Function >::getSymTab(), and llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::removeNodeFromList().
The documentation for this class was generated from the following files:
Argument.h
SymbolTableListTraits.h
SymbolTableListTraitsImpl.h