LLVM: llvm::MCOperandInfo Class Reference
LLVM API Documentation
llvm::MCOperandInfo Class Reference
#include <MCInstrDesc.h>
Public Member Functions
bool isLookupPtrRegClass () const
Currently no other information.
bool isPredicate () const
bool isOptionalDef () const
Public Attributes
int16_t RegClass
uint8_t Flags
Flags - These are flags from the MCOI::OperandFlags enum.
uint8_t OperandType
OperandType - Information about the type of the operand.
uint32_t Constraints
Detailed Description
MCOperandInfo - This holds information about one operand of a machine instruction, indicating the register class for register operands, etc.
Definition at line 58 of file MCInstrDesc.h.
Member Function Documentation
bool llvm::MCOperandInfo::isLookupPtrRegClass () const inline
Currently no other information.
isLookupPtrRegClass - Set if this operand is a pointer value and it requires a callback to look up its register class.
Definition at line 79 of file MCInstrDesc.h.
References llvm::MCOI::LookupPtrRegClass.
Referenced by llvm::TargetInstrInfo::getRegClass().
bool llvm::MCOperandInfo::isOptionalDef () const inline
isOptionalDef - Set if this operand is a optional def.
Definition at line 87 of file MCInstrDesc.h.
References llvm::MCOI::OptionalDef.
Referenced by llvm::ARMTargetLowering::AdjustInstrPostInstrSelection(), llvm::TargetSchedModel::computeOperandLatency(), countOperands(), getAddrModeUPBits(), getRealVLDOpcode(), matchPair(), llvm::MachineInstr::print(), and VerifyLowRegs().
bool llvm::MCOperandInfo::isPredicate () const inline
isPredicate - Set if this is one of the operands that made up of the predicate operand that controls an isPredicable() instruction.
Definition at line 83 of file MCInstrDesc.h.
References llvm::MCOI::Predicate.
Referenced by llvm::MachineInstr::findFirstPredOperandIdx(), getAddrModeUPBits(), llvm::MachineInstr::print(), and VerifyLowRegs().
Member Data Documentation
uint32_t llvm::MCOperandInfo::Constraints
Lower 16 bits are used to specify which constraints are set. The higher 16 bits are used to specify the value of constraints (4 bits each).
Definition at line 74 of file MCInstrDesc.h.
Referenced by llvm::MCInstrDesc::getOperandConstraint().
uint8_t llvm::MCOperandInfo::Flags
Flags - These are flags from the MCOI::OperandFlags enum.
Definition at line 67 of file MCInstrDesc.h.
uint8_t llvm::MCOperandInfo::OperandType
OperandType - Information about the type of the operand.
Definition at line 70 of file MCInstrDesc.h.
Referenced by getInstDesc().
int16_t llvm::MCOperandInfo::RegClass
RegClass - This specifies the register class enumeration of the operand if the operand is a register. If isLookupPtrRegClass is set, then this is an index that is passed to TargetRegisterInfo::getPointerRegClass(x) to get a dynamic register class.
Definition at line 64 of file MCInstrDesc.h.
Referenced by AddThumb1SBit(), llvm::R600InstrInfo::AnalyzeBranch(), llvm::SITargetLowering::analyzeImmediate(), llvm::createAMDGPUISelDag(), llvm::createSIMCCodeEmitter(), llvm::SIInstrInfo::getOpRegClass(), llvm::TargetInstrInfo::getRegClass(), and isNodeChanged().
The documentation for this class was generated from the following file:
MCInstrDesc.h