LLVM: llvm::object::Archive::Symbol Class Reference
LLVM API Documentation
llvm::object::Archive::Symbol Class Reference
#include <Archive.h>
Public Member Functions
bool operator== (const Symbol &other) const
Symbol (const Archive *p, uint32_t symi, uint32_t stri)
error_code getName (StringRef &Result) const
error_code getMember (child_iterator &Result) const
Symbol getNext () const
Detailed Description
Definition at line 124 of file Archive.h.
Constructor & Destructor Documentation
llvm::object::Archive::Symbol::Symbol (const Archive * p, uint32_t symi, uint32_t stri) inline
Definition at line 134 of file Archive.h.
References llvm::object::ArchiveMemberHeader::getName().
Member Function Documentation
error_code Archive::Symbol::getMember (child_iterator & Result) const
Definition at line 333 of file Archive.cpp.
References llvm::object::Archive::K_BSD, llvm::object::Archive::K_GNU, llvm_unreachable, llvm::object::object_error::parse_failed, and llvm::object::object_error::success.
Referenced by llvm::object::Archive::findSym().
error_code Archive::Symbol::getName (StringRef & Result) const
Definition at line 328 of file Archive.cpp.
References llvm::object::object_error::success.
Referenced by llvm::object::Archive::findSym().
Archive::Symbol Archive::Symbol::getNext () const
Definition at line 378 of file Archive.cpp.
References t.
Referenced by llvm::object::Archive::symbol_iterator::operator++().
bool llvm::object::Archive::Symbol::operator== (const Symbol & other) const inline
Definition at line 130 of file Archive.h.
The documentation for this class was generated from the following files:
Archive.h
Archive.cpp