LLVM: llvm::PPCFrameLowering Class Reference
LLVM API Documentation
llvm::PPCFrameLowering Class Reference
#include <PPCFrameLowering.h>
Public Member Functions
PPCFrameLowering (const PPCSubtarget &sti)
unsigned determineFrameLayout (MachineFunction &MF, bool UpdateMF=true, bool UseEstimate=false) const
void emitPrologue (MachineFunction &MF) const
void emitEpilogue (MachineFunction &MF, MachineBasicBlock &MBB) const
bool hasFP (const MachineFunction &MF) const
bool needsFP (const MachineFunction &MF) const
void replaceFPWithRealFP (MachineFunction &MF) const
void processFunctionBeforeCalleeSavedScan (MachineFunction &MF, RegScavenger *RS=NULL) const
void processFunctionBeforeFrameFinalized (MachineFunction &MF, RegScavenger *RS=NULL) const
void addScavengingSpillSlot (MachineFunction &MF, RegScavenger *RS) const
bool spillCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const
void eliminateCallFramePseudoInstr (MachineFunction &MF, MachineBasicBlock &MBB, MachineBasicBlock::iterator I) const
bool restoreCalleeSavedRegisters (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > &CSI, const TargetRegisterInfo *TRI) const
bool targetHandlesStackFrameRounding () const
const SpillSlot * getCalleeSavedSpillSlots (unsigned &NumEntries) const
Public Member Functions inherited from llvm::TargetFrameLowering
TargetFrameLowering (StackDirection D, unsigned StackAl, int LAO, unsigned TransAl=1, bool StackReal=true)
virtual ~TargetFrameLowering ()
StackDirection getStackGrowthDirection () const
unsigned getStackAlignment () const
unsigned getTransientStackAlignment () const
bool isStackRealignable () const
int getOffsetOfLocalArea () const
virtual bool isFPCloseToIncomingSP () const
virtual void adjustForSegmentedStacks (MachineFunction &MF) const
virtual void adjustForHiPEPrologue (MachineFunction &MF) const
virtual bool hasReservedCallFrame (const MachineFunction &MF) const
virtual bool canSimplifyCallFramePseudos (const MachineFunction &MF) const
virtual int getFrameIndexOffset (const MachineFunction &MF, int FI) const
virtual int getFrameIndexReference (const MachineFunction &MF, int FI, unsigned &FrameReg) const
Static Public Member Functions
static unsigned getReturnSaveOffset (bool isPPC64, bool isDarwinABI)
static unsigned getFramePointerSaveOffset (bool isPPC64, bool isDarwinABI)
static unsigned getBasePointerSaveOffset (bool isPPC64, bool isDarwinABI)
static unsigned getLinkageSize (bool isPPC64, bool isDarwinABI)
static unsigned getMinCallArgumentsSize (bool isPPC64, bool isDarwinABI)
static unsigned getMinCallFrameSize (bool isPPC64, bool isDarwinABI)
Additional Inherited Members
Public Types inherited from llvm::TargetFrameLowering
enum StackDirection { StackGrowsUp, StackGrowsDown }
Detailed Description
Definition at line 25 of file PPCFrameLowering.h.
Constructor & Destructor Documentation
llvm::PPCFrameLowering::PPCFrameLowering (const PPCSubtarget & sti) inline
Definition at line 29 of file PPCFrameLowering.h.
References addScavengingSpillSlot(), determineFrameLayout(), eliminateCallFramePseudoInstr(), emitEpilogue(), emitPrologue(), hasFP(), I, llvm::A64CC::MI, needsFP(), processFunctionBeforeCalleeSavedScan(), processFunctionBeforeFrameFinalized(), replaceFPWithRealFP(), restoreCalleeSavedRegisters(), and spillCalleeSavedRegisters().
Member Function Documentation
void PPCFrameLowering::addScavengingSpillSlot (MachineFunction & MF, RegScavenger * RS) const
Definition at line 1154 of file PPCFrameLowering.cpp.
References llvm::RegScavenger::addScavengingFrameIndex(), llvm::MachineFrameInfo::CreateStackObject(), determineFrameLayout(), llvm::TargetRegisterClass::getAlignment(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getMaxAlignment(), llvm::TargetRegisterClass::getSize(), llvm::TargetFrameLowering::getStackAlignment(), hasNonRISpills(), hasSpills(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::isInt< 16 >(), llvm::PPCSubtarget::isPPC64(), spillsCR(), and spillsVRSAVE().
Referenced by PPCFrameLowering(), and processFunctionBeforeFrameFinalized().
unsigned PPCFrameLowering::determineFrameLayout (MachineFunction & MF, bool UpdateMF = true, bool UseEstimate = false) const
determineFrameLayout - Determine the size of the frame and maximum call frame size.
Definition at line 198 of file PPCFrameLowering.cpp.
References llvm::MachineFrameInfo::adjustsStack(), DisableRedZone(), llvm::MachineFrameInfo::estimateStackSize(), llvm::Function::getAttributes(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFrameInfo::getMaxAlignment(), llvm::MachineFrameInfo::getMaxCallFrameSize(), getMinCallFrameSize(), llvm::TargetMachine::getRegisterInfo(), llvm::TargetFrameLowering::getStackAlignment(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getTarget(), llvm::PPCRegisterInfo::hasBasePointer(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::PPCSubtarget::isDarwinABI(), llvm::PPCSubtarget::isPPC64(), llvm::PPCSubtarget::isSVR4ABI(), llvm::Attribute::NoRedZone, llvm::MachineFrameInfo::setMaxCallFrameSize(), and llvm::MachineFrameInfo::setStackSize().
Referenced by addScavengingSpillSlot(), emitPrologue(), llvm::PPCRegisterInfo::needsFrameBaseReg(), and PPCFrameLowering().
void PPCFrameLowering::eliminateCallFramePseudoInstr (MachineFunction & MF, MachineBasicBlock & MBB, MachineBasicBlock::iterator MI) const virtual
eliminateCallFramePseudoInstr - This method is called during prolog/epilog code insertion to eliminate call frame setup and destroy pseudo instructions (but only if the Target is using them). It is responsible for eliminating these instructions, replacing them with concrete instructions. This method need only be implemented if using call frame setup/destroy pseudo instructions.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1298 of file PPCFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineBasicBlock::erase(), llvm::MachineInstr::getDebugLoc(), llvm::TargetMachine::getInstrInfo(), llvm::MachineFunction::getTarget(), llvm::TargetOptions::GuaranteedTailCallOpt, I, llvm::isInt< 16 >(), llvm::PPCSubtarget::isPPC64(), llvm::RegState::Kill, llvm::A64CC::MI, llvm::TargetMachine::Options, and TII.
Referenced by PPCFrameLowering(), and restoreCRs().
void PPCFrameLowering::emitEpilogue (MachineFunction & MF, MachineBasicBlock & MBB) const virtual
Implements llvm::TargetFrameLowering.
Definition at line 646 of file PPCFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::SmallVectorBase::empty(), llvm::MachineBasicBlock::end(), llvm::CallingConv::Fast, llvm::DebugLoc::get(), llvm::PPCFunctionInfo::getBasePointerSaveIndex(), getBasePointerSaveOffset(), llvm::Function::getCallingConv(), llvm::MachineFunction::getFrameInfo(), llvm::PPCFunctionInfo::getFramePointerSaveIndex(), getFramePointerSaveOffset(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineFunction::getInfo(), llvm::TargetMachine::getInstrInfo(), llvm::getKillRegState(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::PPCFunctionInfo::getMinReservedArea(), llvm::PPCFunctionInfo::getMustSaveCRs(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineOperand::getOffset(), llvm::TargetMachine::getRegisterInfo(), getReturnSaveOffset(), llvm::MachineFrameInfo::getStackSize(), llvm::PPCFunctionInfo::getTailCallSPDelta(), llvm::MachineFunction::getTarget(), llvm::TargetOptions::GuaranteedTailCallOpt, llvm::PPCRegisterInfo::hasBasePointer(), llvm::PPCFunctionInfo::hasFastCall(), hasFP(), llvm::MachineFrameInfo::hasVarSizedObjects(), i, llvm::PPCSubtarget::isDarwinABI(), llvm::MachineOperand::isImm(), llvm::isInt< 16 >(), llvm::PPCSubtarget::isPPC64(), llvm::PPCSubtarget::isSVR4ABI(), llvm::RegState::Kill, llvm::A64DB::LD, llvm::PPCFunctionInfo::mustSaveLR(), MustSaveLR(), llvm::TargetMachine::Options, llvm::SmallVectorTemplateCommon< T, typename >::size(), and TII.
Referenced by PPCFrameLowering().
void PPCFrameLowering::emitPrologue (MachineFunction & MF) const virtual
emitProlog/emitEpilog - These methods insert prolog and epilog code into the function.
Implements llvm::TargetFrameLowering.
Definition at line 333 of file PPCFrameLowering.cpp.
References llvm::MachineModuleInfo::addFrameInst(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MCCFIInstruction::createDefCfaOffset(), llvm::MCCFIInstruction::createDefCfaRegister(), llvm::MCCFIInstruction::createOffset(), llvm::MCContext::CreateTempSymbol(), determineFrameLayout(), llvm::SmallVectorBase::empty(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::front(), llvm::PPCFunctionInfo::getBasePointerSaveIndex(), getBasePointerSaveOffset(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineModuleInfo::getContext(), llvm::MCRegisterInfo::getDwarfRegNum(), llvm::MachineFunction::getFrameInfo(), llvm::PPCFunctionInfo::getFramePointerSaveIndex(), getFramePointerSaveOffset(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::TargetMachine::getInstrInfo(), llvm::getKillRegState(), llvm::MachineFrameInfo::getMaxAlignment(), llvm::MachineFunction::getMMI(), llvm::PPCFunctionInfo::getMustSaveCRs(), llvm::MachineFrameInfo::getObjectOffset(), llvm::TargetMachine::getRegisterInfo(), llvm::MCContext::getRegisterInfo(), getReturnSaveOffset(), llvm::MachineFunction::getTarget(), HandleVRSaveUpdate(), llvm::PPCRegisterInfo::hasBasePointer(), llvm::MachineModuleInfo::hasDebugInfo(), hasFP(), i, I, llvm::RegState::ImplicitKill, llvm::PPCSubtarget::isDarwinABI(), llvm::MachineFrameInfo::isFrameAddressTaken(), llvm::isInt< 16 >(), llvm::isInt< 32 >(), llvm::isPowerOf2_32(), llvm::PPCSubtarget::isPPC64(), llvm::PPCSubtarget::isSVR4ABI(), llvm::RegState::Kill, llvm_unreachable, llvm::Log2_32(), MRI, llvm::PPCFunctionInfo::mustSaveLR(), MustSaveLR(), llvm::Function::needsUnwindTableEntry(), OR, llvm::TargetOpcode::PROLOG_LABEL, replaceFPWithRealFP(), llvm::NVPTX::PTXCvtMode::RM, llvm::SmallVectorTemplateCommon< T, typename >::size(), and TII.
Referenced by PPCFrameLowering().
static unsigned llvm::PPCFrameLowering::getBasePointerSaveOffset (bool isPPC64, bool isDarwinABI) inline static
getBasePointerSaveOffset - Return the previous frame offset to save the base pointer.
Definition at line 99 of file PPCFrameLowering.h.
Referenced by emitEpilogue(), emitPrologue(), and processFunctionBeforeCalleeSavedScan().
const SpillSlot* llvm::PPCFrameLowering::getCalleeSavedSpillSlots (unsigned & NumEntries) const inline virtual
getCalleeSavedSpillSlots - This method returns a pointer to an array of pairs, that contains an entry for each callee saved register that must be spilled to a particular stack location if it is spilled.
Each entry in this array contains a <register,offset> pair, indicating the fixed offset from the incoming stack pointer that each register should be spilled at. If a register is not listed here, the code generator is allowed to spill it anywhere it chooses.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 144 of file PPCFrameLowering.h.
References llvm::array_lengthof(), llvm::PPCSubtarget::isDarwinABI(), llvm::PPCSubtarget::isPPC64(), and llvm::PPCSubtarget::isSVR4ABI().
static unsigned llvm::PPCFrameLowering::getFramePointerSaveOffset (bool isPPC64, bool isDarwinABI) inline static
getFramePointerSaveOffset - Return the previous frame offset to save the frame pointer.
Definition at line 84 of file PPCFrameLowering.h.
Referenced by emitEpilogue(), emitPrologue(), EmitTailCallStoreFPAndRetAddr(), isLocalCall(), and processFunctionBeforeCalleeSavedScan().
static unsigned llvm::PPCFrameLowering::getLinkageSize (bool isPPC64, bool isDarwinABI) inline static
getLinkageSize - Return the size of the PowerPC ABI linkage area.
Definition at line 109 of file PPCFrameLowering.h.
Referenced by CalculateParameterAndLinkageAreaSize(), CalculateStackSlotSize(), getMinCallFrameSize(), and isLocalCall().
static unsigned llvm::PPCFrameLowering::getMinCallArgumentsSize (bool isPPC64, bool isDarwinABI) inline static
getMinCallArgumentsSize - Return the size of the minium PowerPC ABI argument area.
Definition at line 119 of file PPCFrameLowering.h.
Referenced by getMinCallFrameSize().
static unsigned llvm::PPCFrameLowering::getMinCallFrameSize (bool isPPC64, bool isDarwinABI) inline static
getMinCallFrameSize - Return the minimum size a call frame can be using the PowerPC ABI.
Definition at line 136 of file PPCFrameLowering.h.
References getLinkageSize(), and getMinCallArgumentsSize().
Referenced by CalculateParameterAndLinkageAreaSize(), CalculateStackSlotSize(), and determineFrameLayout().
static unsigned llvm::PPCFrameLowering::getReturnSaveOffset (bool isPPC64, bool isDarwinABI) inline static
getReturnSaveOffset - Return the previous frame offset to save the return address.
Definition at line 75 of file PPCFrameLowering.h.
Referenced by emitEpilogue(), emitPrologue(), EmitTailCallStoreFPAndRetAddr(), llvm::PPCTargetLowering::isLegalAddressingMode(), and isLocalCall().
bool PPCFrameLowering::hasFP (const MachineFunction & MF) const virtual
hasFP - Return true if the specified function should have a dedicated frame pointer register. For most targets this is true only if the function has variable sized allocas or if frame pointer elimination is disabled.
Implements llvm::TargetFrameLowering.
Definition at line 268 of file PPCFrameLowering.cpp.
References llvm::MachineFunction::getFrameInfo(), llvm::MachineFrameInfo::getStackSize(), and needsFP().
Referenced by emitEpilogue(), emitPrologue(), and PPCFrameLowering().
bool PPCFrameLowering::needsFP (const MachineFunction & MF) const
Definition at line 279 of file PPCFrameLowering.cpp.
References llvm::TargetOptions::DisableFramePointerElim(), llvm::Function::getAttributes(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getTarget(), llvm::TargetOptions::GuaranteedTailCallOpt, llvm::AttributeSet::hasAttribute(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::Attribute::Naked, and llvm::TargetMachine::Options.
Referenced by llvm::PPCRegisterInfo::getReservedRegs(), hasFP(), PPCFrameLowering(), processFunctionBeforeCalleeSavedScan(), processFunctionBeforeFrameFinalized(), replaceFPWithRealFP(), and restoreCalleeSavedRegisters().
void PPCFrameLowering::processFunctionBeforeCalleeSavedScan (MachineFunction & MF, RegScavenger * RS = NULL) const virtual
processFunctionBeforeCalleeSavedScan - This method is called immediately before PrologEpilogInserter scans the physical registers used to determine what callee saved registers should be spilled. This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 889 of file PPCFrameLowering.cpp.
References llvm::MachineFrameInfo::CreateFixedObject(), llvm::PPCFunctionInfo::getBasePointerSaveIndex(), getBasePointerSaveOffset(), llvm::MachineFunction::getFrameInfo(), llvm::PPCFunctionInfo::getFramePointerSaveIndex(), getFramePointerSaveOffset(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getRegInfo(), llvm::TargetMachine::getRegisterInfo(), llvm::PPCFunctionInfo::getTailCallSPDelta(), llvm::MachineFunction::getTarget(), llvm::TargetOptions::GuaranteedTailCallOpt, llvm::PPCRegisterInfo::hasBasePointer(), llvm::PPCSubtarget::isDarwinABI(), llvm::MachineRegisterInfo::isPhysRegUsed(), llvm::PPCSubtarget::isPPC64(), MRI, MustSaveLR(), needsFP(), llvm::TargetMachine::Options, llvm::PPCFunctionInfo::setBasePointerSaveIndex(), llvm::PPCFunctionInfo::setCRSpillFrameIndex(), llvm::PPCFunctionInfo::setFramePointerSaveIndex(), llvm::PPCFunctionInfo::setMustSaveLR(), and llvm::MachineRegisterInfo::setPhysRegUnused().
Referenced by PPCFrameLowering().
void PPCFrameLowering::processFunctionBeforeFrameFinalized (MachineFunction & MF, RegScavenger * RS = NULL) const virtual
processFunctionBeforeFrameFinalized - This method is called immediately before the specified function's frame layout (MF.getFrameInfo()) is finalized. Once the frame is finalized, MO_FrameIndex operands are replaced with direct constants. This method is optional.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 944 of file PPCFrameLowering.cpp.
References addScavengingSpillSlot(), llvm::PPCFunctionInfo::getBasePointerSaveIndex(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), llvm::PPCFunctionInfo::getFramePointerSaveIndex(), llvm::MachineFunction::getInfo(), llvm::MachineFrameInfo::getObjectOffset(), llvm::TargetMachine::getRegisterInfo(), llvm::PPCFunctionInfo::getTailCallSPDelta(), llvm::MachineFunction::getTarget(), llvm::TargetOptions::GuaranteedTailCallOpt, llvm::PPCRegisterInfo::hasBasePointer(), i, llvm::PPCSubtarget::isPPC64(), llvm::PPCSubtarget::isSVR4ABI(), llvm_unreachable, needsFP(), llvm::TargetMachine::Options, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::MachineFrameInfo::setObjectOffset(), llvm::SmallVectorTemplateCommon< T >::size(), and spillsCR().
Referenced by PPCFrameLowering().
void PPCFrameLowering::replaceFPWithRealFP (MachineFunction & MF) const
Definition at line 294 of file PPCFrameLowering.cpp.
References llvm::MachineFunction::begin(), llvm::MachineFunction::end(), llvm::MachineOperand::getReg(), llvm::TargetMachine::getRegisterInfo(), llvm::MachineFunction::getTarget(), llvm::PPCRegisterInfo::hasBasePointer(), I, llvm::MachineOperand::isReg(), needsFP(), and llvm::MachineOperand::setReg().
Referenced by emitPrologue(), and PPCFrameLowering().
bool PPCFrameLowering::restoreCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const virtual
restoreCalleeSavedRegisters - Issues instruction(s) to restore all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of load instructions via loadRegToStackSlot(). Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1339 of file PPCFrameLowering.cpp.
References llvm::MachineBasicBlock::begin(), llvm::TargetMachine::getInstrInfo(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getTarget(), i, I, llvm::PPCSubtarget::isDarwinABI(), llvm::PPCSubtarget::isPPC64(), llvm::PPCSubtarget::isSVR4ABI(), llvm::PPCInstrInfo::loadRegFromStackSlot(), llvm::A64CC::MI, needsFP(), restoreCRs(), and TII.
Referenced by PPCFrameLowering().
bool PPCFrameLowering::spillCalleeSavedRegisters (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, const std::vector< CalleeSavedInfo > & CSI, const TargetRegisterInfo * TRI) const virtual
spillCalleeSavedRegisters - Issues instruction(s) to spill all callee saved registers and returns true if it isn't possible / profitable to do so by issuing a series of store instructions via storeRegToStackSlot(). Returns false otherwise.
Reimplemented from llvm::TargetFrameLowering.
Definition at line 1194 of file PPCFrameLowering.cpp.
References llvm::addFrameReference(), llvm::MachineBasicBlock::addLiveIn(), llvm::PPCFunctionInfo::addMustSaveCR(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineFunction::getInfo(), llvm::TargetMachine::getInstrInfo(), llvm::getKillRegState(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getTarget(), i, llvm::RegState::ImplicitKill, llvm::MachineBasicBlock::insert(), llvm::PPCSubtarget::isDarwinABI(), llvm::PPCSubtarget::isPPC64(), llvm::PPCSubtarget::isSVR4ABI(), llvm::PPCFunctionInfo::setSpillsCR(), llvm::PPCInstrInfo::storeRegToStackSlot(), and TII.
Referenced by PPCFrameLowering().
bool llvm::PPCFrameLowering::targetHandlesStackFrameRounding () const inline virtual
targetHandlesStackFrameRounding - Returns true if the target is responsible for rounding up the stack frame (probably at emitPrologue time).
Reimplemented from llvm::TargetFrameLowering.
Definition at line 71 of file PPCFrameLowering.h.
The documentation for this class was generated from the following files:
PPCFrameLowering.h
PPCFrameLowering.cpp