LLVM: llvm::HexagonTargetMachine Class Reference
LLVM API Documentation
llvm::HexagonTargetMachine Class Reference
#include <HexagonTargetMachine.h>
Public Member Functions
HexagonTargetMachine (const Target &T, StringRef TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
virtual const HexagonInstrInfo * getInstrInfo () const
virtual const HexagonSubtarget * getSubtargetImpl () const
virtual const HexagonRegisterInfo * getRegisterInfo () const
virtual const InstrItineraryData * getInstrItineraryData () const
virtual const HexagonTargetLowering * getTargetLowering () const
virtual const HexagonFrameLowering * getFrameLowering () const
virtual const HexagonSelectionDAGInfo * getSelectionDAGInfo () const
virtual const DataLayout * getDataLayout () const
virtual bool addPassesForOptimizations (PassManagerBase &PM)
virtual TargetPassConfig * createPassConfig (PassManagerBase &PM)
Public Member Functions inherited from llvm::LLVMTargetMachine
virtual void addAnalysisPasses (PassManagerBase &PM)
Register analysis passes for this target with a pass manager.
virtual bool addPassesToEmitFile (PassManagerBase &PM, formatted_raw_ostream &Out, CodeGenFileType FileType, bool DisableVerify=true, AnalysisID StartAfter=0, AnalysisID StopAfter=0)
virtual bool addPassesToEmitMachineCode (PassManagerBase &PM, JITCodeEmitter &MCE, bool DisableVerify=true)
virtual bool addPassesToEmitMC (PassManagerBase &PM, MCContext *&Ctx, raw_ostream &OS, bool DisableVerify=true)
virtual bool addCodeEmitter (PassManagerBase &, JITCodeEmitter &)
Public Member Functions inherited from llvm::TargetMachine
virtual ~TargetMachine ()
const Target & getTarget () const
const StringRef getTargetTriple () const
const StringRef getTargetCPU () const
const StringRef getTargetFeatureString () const
void resetTargetOptions (const MachineFunction *MF) const
Reset the target options based on the function's attributes.
const MCAsmInfo * getMCAsmInfo () const
template<typename STC >
const STC & getSubtarget () const
virtual const TargetIntrinsicInfo * getIntrinsicInfo () const
virtual TargetJITInfo * getJITInfo ()
bool hasMCRelaxAll () const
void setMCRelaxAll (bool Value)
bool hasMCSaveTempLabels () const
void setMCSaveTempLabels (bool Value)
bool hasMCNoExecStack () const
hasMCNoExecStack - Check whether an executable stack is not needed.
void setMCNoExecStack (bool Value)
setMCNoExecStack - Set whether an executabel stack is not needed.
bool hasMCUseLoc () const
hasMCUseLoc - Check whether we should use dwarf's .loc directive.
void setMCUseLoc (bool Value)
setMCUseLoc - Set whether all we should use dwarf's .loc directive.
bool hasMCUseCFI () const
hasMCUseCFI - Check whether we should use dwarf's .cfi_* directives.
void setMCUseCFI (bool Value)
setMCUseCFI - Set whether all we should use dwarf's .cfi_* directives.
bool hasMCUseDwarfDirectory () const
void setMCUseDwarfDirectory (bool Value)
Reloc::Model getRelocationModel () const
CodeModel::Model getCodeModel () const
TLSModel::Model getTLSModel (const GlobalValue *GV) const
CodeGenOpt::Level getOptLevel () const
void setOptLevel (CodeGenOpt::Level Level) const
Overrides the optimization level.
void setFastISel (bool Enable)
bool shouldPrintMachineCode () const
Static Public Member Functions
static unsigned getModuleMatchQuality (const Module &M)
Static Public Member Functions inherited from llvm::TargetMachine
static bool getAsmVerbosityDefault ()
static void setAsmVerbosityDefault (bool)
static bool getDataSections ()
static bool getFunctionSections ()
static void setDataSections (bool)
setDataSections - Set if the data are emit into separate sections.
static void setFunctionSections (bool)
Additional Inherited Members
Public Types inherited from llvm::TargetMachine
enum CodeGenFileType { CGFT_AssemblyFile, CGFT_ObjectFile, CGFT_Null }
Public Attributes inherited from llvm::TargetMachine
TargetOptions Options
Protected Member Functions inherited from llvm::LLVMTargetMachine
LLVMTargetMachine (const Target &T, StringRef TargetTriple, StringRef CPU, StringRef FS, TargetOptions Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
void initAsmInfo ()
Protected Member Functions inherited from llvm::TargetMachine
TargetMachine (const Target &T, StringRef TargetTriple, StringRef CPU, StringRef FS, const TargetOptions &Options)
Protected Attributes inherited from llvm::TargetMachine
const Target & TheTarget
TheTarget - The Target that this machine was created for.
std::string TargetTriple
std::string TargetCPU
std::string TargetFS
MCCodeGenInfo * CodeGenInfo
const MCAsmInfo * AsmInfo
unsigned MCRelaxAll: 1
unsigned MCNoExecStack: 1
unsigned MCSaveTempLabels: 1
unsigned MCUseLoc: 1
unsigned MCUseCFI: 1
unsigned MCUseDwarfDirectory: 1
Detailed Description
Definition at line 29 of file HexagonTargetMachine.h.
Constructor & Destructor Documentation
HexagonTargetMachine::HexagonTargetMachine (const Target & T, StringRef TT, StringRef CPU, StringRef FS, const TargetOptions & Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
HexagonTargetMachine ctor - Create an ILP32 architecture model.Hexagon_TODO: Do I need an aggregate alignment?
Definition at line 67 of file HexagonTargetMachine.cpp.
References llvm::LLVMTargetMachine::initAsmInfo(), and llvm::TargetMachine::setMCUseCFI().
Member Function Documentation
bool HexagonTargetMachine::addPassesForOptimizations (PassManagerBase & PM) virtual
Definition at line 87 of file HexagonTargetMachine.cpp.
References llvm::createConstantPropagationPass(), llvm::createDeadCodeEliminationPass(), llvm::createLoopSimplifyPass(), llvm::createLoopStrengthReducePass(), llvm::createLoopUnrollPass(), createVLIWMachineSched(), DisableHexagonMISched, llvm::TargetMachine::getOptLevel(), llvm::MachineSchedulerID, llvm::CodeGenOpt::None, and llvm::SystemZISD::TM.
Referenced by getDataLayout().
TargetPassConfig * HexagonTargetMachine::createPassConfig (PassManagerBase & PM) virtual
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
Targets may override this to extend TargetPassConfig.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 132 of file HexagonTargetMachine.cpp.
References llvm::createHexagonCFGOptimizer(), llvm::createHexagonCopyToCombine(), llvm::createHexagonExpandPredSpillCode(), llvm::createHexagonFixupHwLoops(), llvm::createHexagonHardwareLoops(), llvm::createHexagonISelDag(), llvm::createHexagonNewValueJump(), llvm::createHexagonPacketizer(), llvm::createHexagonPeephole(), llvm::createHexagonRemoveExtendArgs(), llvm::createHexagonSplitConst32AndConst64(), llvm::createHexagonSplitTFRCondSets(), DisableHardwareLoops, DisableHexagonCFGOpt, llvm::TargetLoweringBase::getObjFileLowering(), llvm::TargetMachine::getOptLevel(), getTargetLowering(), llvm::IfConverterID, llvm::HexagonTargetObjectFile::IsSmallDataEnabled(), llvm::CodeGenOpt::None, and llvm::SystemZISD::TM.
Referenced by getDataLayout().
virtual const DataLayout* llvm::HexagonTargetMachine::getDataLayout () const inline virtual
Reimplemented from llvm::TargetMachine.
Definition at line 71 of file HexagonTargetMachine.h.
References addPassesForOptimizations(), createPassConfig(), llvm::flag_aligned_memcpy, getModuleMatchQuality(), and M.
virtual const HexagonFrameLowering* llvm::HexagonTargetMachine::getFrameLowering () const inline virtual
Reimplemented from llvm::TargetMachine.
Definition at line 63 of file HexagonTargetMachine.h.
virtual const HexagonInstrInfo* llvm::HexagonTargetMachine::getInstrInfo () const inline virtual
Reimplemented from llvm::TargetMachine.
Definition at line 44 of file HexagonTargetMachine.h.
Referenced by llvm::HexagonMCInst::getUnits(), and OffsetFitsS11().
virtual const InstrItineraryData* llvm::HexagonTargetMachine::getInstrItineraryData () const inline virtual
getInstrItineraryData - Returns instruction itinerary data for the target or specific subtarget.
Reimplemented from llvm::TargetMachine.
Definition at line 54 of file HexagonTargetMachine.h.
Referenced by llvm::HexagonMCInst::getUnits().
static unsigned llvm::HexagonTargetMachine::getModuleMatchQuality (const Module & M) static
Referenced by getDataLayout().
virtual const HexagonRegisterInfo* llvm::HexagonTargetMachine::getRegisterInfo () const inline virtual
getRegisterInfo - If register information is available, return it. If not, return null. This is kept separate from RegInfo until RegInfo has details of graph coloring register allocation removed from it.
Reimplemented from llvm::TargetMachine.
Definition at line 50 of file HexagonTargetMachine.h.
References llvm::HexagonInstrInfo::getRegisterInfo().
Referenced by llvm::HexagonTargetLowering::HexagonTargetLowering(), llvm::HexagonTargetLowering::isFPImmLegal(), and OffsetFitsS11().
virtual const HexagonSelectionDAGInfo* llvm::HexagonTargetMachine::getSelectionDAGInfo () const inline virtual
Reimplemented from llvm::TargetMachine.
Definition at line 67 of file HexagonTargetMachine.h.
virtual const HexagonSubtarget* llvm::HexagonTargetMachine::getSubtargetImpl () const inline virtual
getSubtargetImpl - virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
Reimplemented from llvm::TargetMachine.
Definition at line 47 of file HexagonTargetMachine.h.
Referenced by llvm::HexagonTargetLowering::HexagonTargetLowering().
virtual const HexagonTargetLowering* llvm::HexagonTargetMachine::getTargetLowering () const inline virtual
Reimplemented from llvm::TargetMachine.
Definition at line 59 of file HexagonTargetMachine.h.
Referenced by createPassConfig().
The documentation for this class was generated from the following files:
HexagonTargetMachine.h
HexagonTargetMachine.cpp