LLVM: llvm::BasicBlock Class Reference
LLVM API Documentation
llvm::BasicBlock Class Reference
LLVM Basic Block Representation.
#include <BasicBlock.h>
Public Types
typedef iplist< Instruction > InstListType
typedef InstListType::iterator iterator
Instruction iterators...
typedef InstListType::const_iterator const_iterator
typedef InstListType::reverse_iterator reverse_iterator
typedef InstListType::const_reverse_iterator const_reverse_iterator
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal, BasicBlockVal, FunctionVal, GlobalAliasVal,
GlobalVariableVal, UndefValueVal, BlockAddressVal, ConstantExprVal,
ConstantAggregateZeroVal, ConstantDataArrayVal, ConstantDataVectorVal, ConstantIntVal,
ConstantFPVal, ConstantArrayVal, ConstantStructVal, ConstantVectorVal,
ConstantPointerNullVal, MDNodeVal, MDStringVal, InlineAsmVal,
PseudoSourceValueVal, FixedStackPseudoSourceValueVal, InstructionVal, ConstantFirstVal = FunctionVal,
ConstantLastVal = ConstantPointerNullVal
}
typedef value_use_iterator< User > use_iterator
typedef value_use_iterator< const User > const_use_iterator
Public Member Functions
LLVMContext & getContext () const
Get the context in which this basic block lives.
~BasicBlock ()
const Function * getParent () const
Return the enclosing method, or null if none.
Function * getParent ()
TerminatorInst * getTerminator ()
Returns the terminator instruction if the block is well formed or null if the block is not well formed.
const TerminatorInst * getTerminator () const
Instruction * getFirstNonPHI ()
Returns a pointer to the first instruction in this block that is not a PHINode instruction.
const Instruction * getFirstNonPHI () const
Instruction * getFirstNonPHIOrDbg ()
Returns a pointer to the first instruction in this block that is not a PHINode or a debug intrinsic.
const Instruction * getFirstNonPHIOrDbg () const
Instruction * getFirstNonPHIOrDbgOrLifetime ()
Returns a pointer to the first instruction in this block that is not a PHINode, a debug intrinsic, or a lifetime intrinsic.
const Instruction * getFirstNonPHIOrDbgOrLifetime () const
iterator getFirstInsertionPt ()
Returns an iterator to the first instruction in this block that is suitable for inserting a non-PHI instruction.
const_iterator getFirstInsertionPt () const
void removeFromParent ()
Unlink 'this' from the containing function, but do not delete it.
void eraseFromParent ()
Unlink 'this' from the containing function and delete it.
void moveBefore (BasicBlock *MovePos)
Unlink this basic block from its current function and insert it into the function that MovePos lives in, right before MovePos.
void moveAfter (BasicBlock *MovePos)
Unlink this basic block from its current function and insert it right after MovePos in the function MovePos lives in.
BasicBlock * getSinglePredecessor ()
Return this block if it has a single predecessor block. Otherwise return a null pointer.
const BasicBlock * getSinglePredecessor () const
BasicBlock * getUniquePredecessor ()
Return this block if it has a unique predecessor block. Otherwise return a null pointer.
const BasicBlock * getUniquePredecessor () const
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_t size () const
bool empty () const
const Instruction & front () const
Instruction & front ()
const Instruction & back () const
Instruction & back ()
const InstListType & getInstList () const
Return the underlying instruction list container.
InstListType & getInstList ()
ValueSymbolTable * getValueSymbolTable ()
Returns a pointer to the symbol table if one exists.
void dropAllReferences ()
Cause all subinstructions to "let go" of all the references that said subinstructions are maintaining.
void removePredecessor (BasicBlock *Pred, bool DontDeleteUselessPHIs=false)
Notify the BasicBlock that the predecessor Pred is no longer able to reach it.
BasicBlock * splitBasicBlock (iterator I, const Twine &BBName="")
Split the basic block into two basic blocks at the specified instruction.
bool hasAddressTaken () const
Returns true if there are any uses of this basic block other than direct branches, switches, etc. to it.
void replaceSuccessorsPhiUsesWith (BasicBlock *New)
Update all phi nodes in this basic block's successors to refer to basic block New instead of to it.
bool isLandingPad () const
Return true if this basic block is a landing pad.
LandingPadInst * getLandingPadInst ()
Return the landingpad instruction associated with the landing pad.
const LandingPadInst * getLandingPadInst () const
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
dump - Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O, AssemblyAnnotationWriter *AAW=0) const
Type * getType () const
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
void setName (const Twine &Name)
void takeName (Value *V)
void replaceAllUsesWith (Value *V)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
User * use_back ()
const User * use_back () const
bool hasOneUse () const
bool hasNUses (unsigned N) const
bool hasNUsesOrMore (unsigned N) const
bool isUsedInBasicBlock (const BasicBlock *BB) const
unsigned getNumUses () const
void addUse (Use &U)
unsigned getValueID () const
unsigned getRawSubclassOptionalData () const
void clearSubclassOptionalData ()
bool hasSameSubclassOptionalData (const Value *V) const
void intersectOptionalDataWith (const Value *V)
bool hasValueHandle () const
Value * stripPointerCasts ()
Strips off any unneeded pointer casts, all-zero GEPs and aliases from the specified value, returning the original uncasted value.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strips off any unneeded pointer casts and all-zero GEPs from the specified value, returning the original uncasted value.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strips off unneeded pointer casts and all-constant GEPs from the specified value, returning the original pointer value.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Strips like stripInBoundsConstantOffsets but also accumulates the constant offset stripped.
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strips off unneeded pointer casts and any in-bounds offsets from the specified value, returning the original pointer value.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer () const
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Public Member Functions inherited from llvm::ilist_node< BasicBlock >
BasicBlock * getPrevNode ()
Get the previous node, or 0 for the list head.
const BasicBlock * getPrevNode () const
Get the previous node, or 0 for the list head.
BasicBlock * getNextNode ()
Get the next node, or 0 for the list tail.
const BasicBlock * getNextNode () const
Get the next node, or 0 for the list tail.
Static Public Member Functions
static BasicBlock * Create (LLVMContext &Context, const Twine &Name="", Function *Parent=0, BasicBlock *InsertBefore=0)
Creates a new BasicBlock.
static iplist< Instruction > BasicBlock::* getSublistAccess (Instruction *)
Returns a pointer to a member of the instruction list.
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast.
Friends
class BlockAddress
class SymbolTableListTraits< BasicBlock, Function >
Additional Inherited Members
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
Protected Member Functions inherited from llvm::Value
virtual void printCustom (raw_ostream &O) const
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Member Functions inherited from llvm::ilist_node< BasicBlock >
ilist_node ()
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Detailed Description
LLVM Basic Block Representation.
This represents a single basic block in LLVM. A basic block is simply a container of instructions that execute sequentially. Basic blocks are Values because they are referenced by instructions such as branches and switch tables. The type of a BasicBlock is "Type::LabelTy" because the basic block represents a label to which a branch can jump.
A well formed basic block is formed of a list of non-terminating instructions followed by a single TerminatorInst instruction. TerminatorInst's may not occur in the middle of basic blocks, and must terminate the blocks. The BasicBlock class allows malformed basic blocks to occur because it may be useful in the intermediate stage of constructing or modifying a program. However, the verifier will ensure that basic blocks are "well formed".
Definition at line 72 of file BasicBlock.h.
Member Typedef Documentation
typedef InstListType::const_iterator llvm::BasicBlock::const_iterator
Definition at line 100 of file BasicBlock.h.
typedef InstListType::const_reverse_iterator llvm::BasicBlock::const_reverse_iterator
Definition at line 102 of file BasicBlock.h.
typedef iplist<Instruction> llvm::BasicBlock::InstListType
Definition at line 76 of file BasicBlock.h.
typedef InstListType::iterator llvm::BasicBlock::iterator
Instruction iterators...
Definition at line 99 of file BasicBlock.h.
typedef InstListType::reverse_iterator llvm::BasicBlock::reverse_iterator
Definition at line 101 of file BasicBlock.h.
Constructor & Destructor Documentation
BasicBlock::~BasicBlock ()
Definition at line 61 of file BasicBlock.cpp.
References llvm::LeakDetector::addGarbageObject(), llvm::iplist< NodeTy, Traits >::clear(), llvm::BlockAddress::destroyConstant(), dropAllReferences(), llvm::ConstantInt::get(), getContext(), llvm::Type::getInt32Ty(), llvm::ConstantExpr::getIntToPtr(), getParent(), llvm::Value::getType(), hasAddressTaken(), llvm::LeakDetector::removeGarbageObject(), llvm::Value::replaceAllUsesWith(), llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::setSymTabObject(), llvm::Value::use_back(), and llvm::Value::use_empty().
Member Function Documentation
const Instruction& llvm::BasicBlock::back () const inline
Definition at line 207 of file BasicBlock.h.
References llvm::iplist< NodeTy, Traits >::back().
Referenced by llvm::AliasAnalysis::canBasicBlockModify(), CheckForCanReleaseCFGHazard(), llvm::CloneAndPruneFunctionInto(), ComputePostOrders(), llvm::createObjCARCContractPass(), llvm::createObjCARCOptPass(), llvm::DeleteDeadBlock(), llvm::objcarc::FindDependencies(), FindPredecessorAutoreleaseWithSafePath(), getEdgeValueLocal(), llvm::BitcodeReader::ParseTriple(), and llvm::SparseSolver::Solve().
Instruction& llvm::BasicBlock::back () inline
Definition at line 208 of file BasicBlock.h.
References llvm::iplist< NodeTy, Traits >::back().
iterator llvm::BasicBlock::begin () inline
Instruction iterator methods
Definition at line 193 of file BasicBlock.h.
References llvm::iplist< NodeTy, Traits >::begin().
Referenced by llvm::AliasSetTracker::add(), AddPHINodeEntriesForMappedBlock(), AddPredecessorToBlock(), AddReachableCodeToWorklist(), AddressIsTaken(), llvm::CodeMetrics::analyzeBasicBlock(), areAllUsesIn(), BlockDominatesAnExit(), BlockIsSimpleEnoughToThreadThrough(), llvm::Interpreter::callFunction(), canIfConvertPHINodes(), CanPropagatePredecessorsForPHIs(), checkCSEInPredecessor(), CheckForCanReleaseCFGHazard(), llvm::CloneAndPruneFunctionInto(), llvm::CloneBasicBlock(), llvm::CloneFunction(), CloneLoop(), CloneLoopBlocks(), collectFailStats(), CommitValueTo(), ComputePostOrders(), ConvertToSInt(), llvm::createCodeGenPreparePass(), llvm::createEarlyCSEPass(), llvm::createLICMPass(), llvm::createLoopDeletionPass(), llvm::createLoopInstSimplifyPass(), llvm::createLoopSimplifyPass(), llvm::createObjCARCContractPass(), llvm::createObjCARCOptPass(), createPHIsForSplitLoopExit(), llvm::createPPCCTRLoopsVerify(), llvm::createPruneEHPass(), llvm::createSinkingPass(), cse(), cxxDtorIsEmpty(), llvm::DeleteDeadPHIs(), deleteIfDeadInstruction(), DeleteInstructionInBlock(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), llvm::DominatorTree::dominates(), dropAllReferences(), llvm::EliminateDuplicatePHINodes(), EvaluateExpression(), llvm::CodeExtractor::extractCodeRegion(), llvm::FastISel::FastEmitZExtFromI1(), llvm::FindAvailableLoadedValue(), llvm::objcarc::FindDependencies(), FindInitTrampolineFromBB(), llvm::CodeExtractor::findInputsOutputs(), FindLoopCounter(), FindPHIForConditionForwarding(), FindPHIToPartitionLoops(), llvm::SSAUpdaterTraits< SSAUpdater >::FindPredecessorBlocks(), FindUnconditionalPreds(), FirstNonDbg(), fixupFPReturnAndCall(), llvm::FoldBranchToCommonDest(), FoldCondBranchOnPHI(), llvm::FoldSingleEntryPHINodes(), FoldTwoEntryPHINode(), generateUnsignedDivisionCode(), genLoopLimit(), llvm::Loop::getCanonicalInductionVariable(), GetCaseResults(), llvm::MemoryDependenceAnalysis::getDependency(), getFirstNonPHI(), getFirstNonPHIOrDbg(), getFirstNonPHIOrDbgOrLifetime(), llvm::DenseMapInfo< ComparableFunction >::getHashValue(), llvm::GetIfCondition(), GetLocation(), getMaxWeightFor(), llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), llvm::SparseSolver::getOrInitValueState(), llvm::SCEVExpander::getOrInsertCanonicalInductionVariable(), llvm::MemoryDependenceAnalysis::getPointerDependencyFrom(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), HandleCallsInBlockInlinedThroughInvoke(), hasAddressTakenAndUsed(), HasNoDuplicateCall(), hasUsesOutsideLoop(), llvm::SCEVExpander::hoistIVInc(), HoistThenElseCodeToIf(), INITIALIZE_PASS(), INITIALIZE_PASS_BEGIN(), llvm::InlineFunction(), insertFastDiv(), InstructionDereferencesPointer(), isAtomic(), isBlockValidForExtraction(), isExistingPhi(), isExitBlock(), isFormingBranchFromSelectProfitable(), llvm::Loop::isLCSSAForm(), isLoopInvariant(), IsNonLocalValue(), isOnlyReachableViaThisEdge(), isOnlyUsedInEntryBlock(), isPossibleSelfRead(), isProfitableChain(), llvm::isSafeToLoadUnconditionally(), isSimpleLoadStore(), isTrivialLoopExitBlock(), isTrivialLoopExitBlockHelper(), isUnmovableInstruction(), llvm::Value::isUsedInBasicBlock(), isZero(), llvm::IVUsers::IVUsers(), IVUseShouldUsePostIncValue(), llvm::linkShadowStackGC(), LLVMGetFirstInstruction(), LLVMGetLastInstruction(), LLVMGetPreviousInstruction(), LowerStoreInst(), markAliveBlocks(), MarkBlocksLiveIn(), MarkIndicesSafe(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), mergeEmptyReturnBlocks(), NegateValue(), operator<<(), OptimizeCmpExpression(), llvm::SparseSolver::Print(), llvm::AssemblyWriter::printBasicBlock(), promoteSingleBlockAlloca(), PushLoopPHIs(), removePredecessor(), llvm::RemovePredecessorAndSimplify(), removeUndefIntroducingPredecessor(), llvm::SCEVExpander::replaceCongruentIVs(), replaceSuccessorsPhiUsesWith(), ReplaceUsesOfWith(), RewriteUsesOfClonedInstructions(), llvm::LoadAndStorePromoter::run(), llvm::StackProtector::runOnFunction(), shouldSpeculateInstrs(), SimplifyBranchOnICmpChain(), SimplifyCondBranchToCondBranch(), llvm::InstCombiner::SimplifyDivRemOfSelect(), llvm::SimplifyInstructionsInBlock(), llvm::simplifyLoopIVs(), SinkThenElseCodeToEnd(), llvm::SparseSolver::Solve(), SpeculativelyExecuteBB(), SplitAddRecs(), splitBasicBlock(), llvm::SplitBlockPredecessors(), llvm::SplitCriticalEdge(), llvm::SplitEdge(), SwitchToLookupTable(), tryToMakeAllocaBePromotable(), TryToShrinkGlobalToBoolean(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), TryToSimplifyUncondBranchWithICmpInIt(), TurnSwitchRangeIntoICmp(), llvm::UnrollLoop(), UpdatePHINodes(), llvm::InstVisitor< ObjectSizeOffsetVisitor, SizeOffsetType >::visit(), llvm::Interpreter::visitIndirectBrInst(), llvm::InstCombiner::visitPHINode(), and llvm::InstCombiner::visitStoreInst().
const_iterator llvm::BasicBlock::begin () const inline
Definition at line 194 of file BasicBlock.h.
References llvm::iplist< NodeTy, Traits >::begin().
static bool llvm::BasicBlock::classof (const Value * V) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 226 of file BasicBlock.h.
References llvm::Value::BasicBlockVal, llvm::Value::getValueID(), and I.
static BasicBlock* llvm::BasicBlock::Create (LLVMContext & Context, const Twine & Name = "", Function * Parent = 0, BasicBlock * InsertBefore = 0) inline static
Creates a new BasicBlock.
If the Parent parameter is specified, the basic block is automatically inserted at either the end of the function (if InsertBefore is 0), or before the specified basic block.
Definition at line 109 of file BasicBlock.h.
References llvm::ISD::BasicBlock.
Referenced by AddPHINodeEntriesForMappedBlock(), checkInterfaceFunction(), llvm::CloneBasicBlock(), llvm::CloneFunction(), convertMemSetToLoop(), convertTransferToLoop(), createCast(), llvm::createDwarfEHPass(), CreatePrologue(), llvm::CodeExtractor::extractCodeRegion(), FindPhiPredForUseInBlock(), FirstNonDbg(), FitWeights(), FoldCondBranchOnPHI(), FunctionNumber(), generateUnsignedDivisionCode(), getFunctionName(), INITIALIZE_PASS(), insertFastDiv(), isFormingBranchFromSelectProfitable(), LLVMAppendBasicBlockInContext(), LLVMInsertBasicBlockInContext(), MarkBlocksLiveIn(), operator<<(), llvm::BitcodeReader::ParseTriple(), PerformHeapAllocSRoA(), PlaceSplitBlockCarefully(), ReplaceUsesOfWith(), llvm::JIT::runFunction(), llvm::UnifyFunctionExitNodes::runOnFunction(), SimplifyCondBranchToCondBranch(), splitBasicBlock(), llvm::SplitBlockAndInsertIfThen(), llvm::SplitBlockPredecessors(), llvm::SplitCriticalEdge(), llvm::SplitLandingPadPredecessors(), SwitchToLookupTable(), TryToSimplifyUncondBranchWithICmpInIt(), and llvm::UnrollRuntimeLoopProlog().
void BasicBlock::dropAllReferences ()
Cause all subinstructions to "let go" of all the references that said subinstructions are maintaining.
This allows one to 'delete' a whole class at a time, even though there may be circular references... first all references are dropped, and all use counts go to zero. Then everything is delete'd for real. Note that no operations are valid on an object that has "dropped all references", except operator delete.
Definition at line 176 of file BasicBlock.cpp.
References begin(), end(), and I.
Referenced by INITIALIZE_PASS(), and ~BasicBlock().
bool llvm::BasicBlock::empty () const inline
Definition at line 204 of file BasicBlock.h.
References llvm::iplist< NodeTy, Traits >::empty().
Referenced by AddressIsTaken(), llvm::createSinkingPass(), llvm::DeleteDeadBlock(), llvm::BitcodeReader::ParseTriple(), and shouldSpeculateInstrs().
iterator llvm::BasicBlock::end () inline
Definition at line 195 of file BasicBlock.h.
References llvm::iplist< NodeTy, Traits >::end().
Referenced by llvm::AliasSetTracker::add(), AddPHINodeEntriesForMappedBlock(), AddReachableCodeToWorklist(), AddressIsTaken(), llvm::CodeMetrics::analyzeBasicBlock(), areAllUsesIn(), BlockDominatesAnExit(), canIfConvertPHINodes(), changeToUnreachable(), checkCSEInPredecessor(), CheckForCanReleaseCFGHazard(), llvm::CloneBasicBlock(), llvm::CloneFunction(), collectFailStats(), llvm::createEarlyCSEPass(), llvm::createLICMPass(), llvm::createLoopInstSimplifyPass(), llvm::createObjCARCContractPass(), llvm::createPPCCTRLoopsVerify(), llvm::createPruneEHPass(), llvm::createSinkingPass(), cse(), cxxDtorIsEmpty(), deleteIfDeadInstruction(), DeleteInstructionInBlock(), dropAllReferences(), llvm::objcarc::FindDependencies(), llvm::CodeExtractor::findInputsOutputs(), FindUnconditionalPreds(), FirstNonDbg(), fixupFPReturnAndCall(), FoldBlockIntoPredecessor(), llvm::FoldBranchToCommonDest(), GenerateARCBBTerminatorAnnotation(), GetCaseResults(), llvm::DenseMapInfo< ComparableFunction >::getHashValue(), getMaxWeightFor(), llvm::Region::getNameStr(), llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), llvm::MemoryDependenceAnalysis::getNonLocalPointerDependency(), HandleCallsInBlockInlinedThroughInvoke(), hasAddressTakenAndUsed(), HasNoDuplicateCall(), INITIALIZE_PASS(), insertFastDiv(), InstructionDereferencesPointer(), isAtomic(), isBlockValidForExtraction(), isFormingBranchFromSelectProfitable(), llvm::isInTailCallPosition(), llvm::Loop::isLCSSAForm(), isOnlyReachableViaThisEdge(), isPossibleSelfRead(), llvm::isPotentiallyReachable(), isSafeAndProfitableToSinkLoad(), isSimpleLoadStore(), isTrivialLoopExitBlock(), isTrivialLoopExitBlockHelper(), isUnmovableInstruction(), llvm::Value::isUsedInBasicBlock(), isZero(), LLVMGetFirstInstruction(), LLVMGetLastInstruction(), LLVMGetNextInstruction(), LLVMPositionBuilder(), LowerStoreInst(), markAliveBlocks(), MarkIndicesSafe(), llvm::MergeBlockIntoPredecessor(), passingValueIsAlwaysUndefined(), llvm::SparseSolver::Print(), llvm::AssemblyWriter::printBasicBlock(), replaceSuccessorsPhiUsesWith(), ReplaceUsesOfWith(), RewriteUsesOfClonedInstructions(), llvm::LoadAndStorePromoter::run(), llvm::StackProtector::runOnFunction(), llvm::IRBuilderBase::SetInsertPoint(), shouldSpeculateInstrs(), llvm::SimplifyInstructionsInBlock(), SinkThenElseCodeToEnd(), llvm::SparseSolver::Solve(), SpeculativelyExecuteBB(), splitBasicBlock(), tryToMakeAllocaBePromotable(), TryToSinkInstruction(), and llvm::InstVisitor< ObjectSizeOffsetVisitor, SizeOffsetType >::visit().
const_iterator llvm::BasicBlock::end () const inline
Definition at line 196 of file BasicBlock.h.
References llvm::iplist< NodeTy, Traits >::end().
void BasicBlock::eraseFromParent ()
Unlink 'this' from the containing function and delete it.
Definition at line 100 of file BasicBlock.cpp.
References llvm::iplist< NodeTy, Traits >::erase(), llvm::Function::getBasicBlockList(), and getParent().
Referenced by llvm::CloneAndPruneFunctionInto(), llvm::createCodeGenPreparePass(), llvm::createLoopSimplifyPass(), llvm::createPruneEHPass(), llvm::DeleteDeadBlock(), FoldBlockIntoPredecessor(), llvm::InlineFunction(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), mergeEmptyReturnBlocks(), OptimizeCmpExpression(), ReplaceUsesOfWith(), shouldSpeculateInstrs(), SimplifyBranchOnICmpChain(), and llvm::TryToSimplifyUncondBranchFromEmptyBlock().
const Instruction& llvm::BasicBlock::front () const inline
Definition at line 205 of file BasicBlock.h.
References llvm::iplist< NodeTy, Traits >::front().
Referenced by llvm::AliasAnalysis::canBasicBlockModify(), llvm::SSAUpdaterTraits< SSAUpdater >::CreateEmptyPHI(), CreatePrologue(), FindMostPopularDest(), FirstNonDbg(), llvm::FoldBranchToCommonDest(), llvm::LoopBase< BasicBlock, Loop >::getHeader(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), INITIALIZE_PASS(), isPossibleSelfRead(), MarkIndicesSafe(), llvm::MergeBlockIntoPredecessor(), mergeEmptyReturnBlocks(), promoteSingleBlockAlloca(), removePredecessor(), llvm::RemovePredecessorAndSimplify(), llvm::UnifyFunctionExitNodes::runOnFunction(), SimplifyBranchOnICmpChain(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), TryToSimplifyUncondBranchWithICmpInIt(), and llvm::InstCombiner::visitStoreInst().
Instruction& llvm::BasicBlock::front () inline
Definition at line 206 of file BasicBlock.h.
References llvm::iplist< NodeTy, Traits >::front().
LLVMContext & BasicBlock::getContext () const
Get the context in which this basic block lives.
Definition at line 33 of file BasicBlock.cpp.
References llvm::LeakDetector::addGarbageObject(), llvm::Value::BasicBlockVal, llvm::Function::getBasicBlockList(), llvm::Type::getContext(), llvm::Type::getLabelTy(), llvm::Value::getType(), llvm::iplist< NodeTy, Traits >::insert(), llvm::iplist< NodeTy, Traits >::push_back(), and llvm::Value::setName().
Referenced by AddPHINodeEntriesForMappedBlock(), llvm::CloneBasicBlock(), llvm::CloneFunction(), computeBytesPoppedByCallee(), llvm::ConstantFoldTerminator(), cse(), EliminateDeadSwitchCases(), llvm::EmitFWrite(), llvm::EmitMemChr(), llvm::EmitMemCmp(), llvm::EmitMemCpyChk(), llvm::EmitStrLen(), llvm::EmitStrNCmp(), llvm::EmitStrNLen(), llvm::CodeExtractor::extractCodeRegion(), llvm::FastISel::FastEmitZExtFromI1(), llvm::CodeExtractor::findInputsOutputs(), FindLIVLoopCondition(), FindMostPopularDest(), FitWeights(), llvm::SimplifyFortifiedLibCalls::fold(), FoldCondBranchOnPHI(), INITIALIZE_PASS(), isOnlyReachableViaThisEdge(), isTrivialLoopExitBlock(), PerformHeapAllocSRoA(), splitBasicBlock(), llvm::SplitBlockAndInsertIfThen(), llvm::SplitBlockPredecessors(), llvm::SplitLandingPadPredecessors(), TryToSimplifyUncondBranchWithICmpInIt(), llvm::UnreachableInst::UnreachableInst(), llvm::UnrollRuntimeLoopProlog(), ValuesOverlap(), and ~BasicBlock().
BasicBlock::iterator BasicBlock::getFirstInsertionPt ()
Returns an iterator to the first instruction in this block that is suitable for inserting a non-PHI instruction.
In particular, it skips all PHIs and LandingPad instructions.
Definition at line 170 of file BasicBlock.cpp.
References getFirstNonPHI().
Referenced by CheckForCanReleaseCFGHazard(), checkInterfaceFunction(), ConvertToSInt(), llvm::createLICMPass(), createPrivateNonConstGlobalForString(), llvm::DemoteRegToStack(), llvm::InstCombiner::DoOneIteration(), llvm::SCEVExpander::expandCodeFor(), FindScalarElement(), GenerateARCBBEntranceAnnotation(), genLoopLimit(), getGEPInductionOperand(), hasUsesOutsideLoop(), isFormingBranchFromSelectProfitable(), IsNonLocalValue(), MarkBlocksLiveIn(), OptimizeCmpExpression(), OptimizeNoopCopyExpression(), llvm::SCEVExpander::replaceCongruentIVs(), llvm::SplitLandingPadPredecessors(), TryToSinkInstruction(), llvm::ObjectSizeOffsetEvaluator::visitPHINode(), and llvm::InstCombiner::visitStoreInst().
const_iterator llvm::BasicBlock::getFirstInsertionPt () const inline
Definition at line 154 of file BasicBlock.h.
Instruction * BasicBlock::getFirstNonPHI ()
Returns a pointer to the first instruction in this block that is not a PHINode instruction.
When adding instructions to the beginning of the basic block, they should be added before the returned value, not before the first instruction, which might be PHI. Returns 0 is there's no non-PHI instruction.
Definition at line 130 of file BasicBlock.cpp.
References begin(), and i.
Referenced by collectFailStats(), createPHIsForSplitLoopExit(), createPrivateNonConstGlobalForString(), deleteIfDeadInstruction(), llvm::CodeExtractor::findInputsOutputs(), getFirstInsertionPt(), getGEPInductionOperand(), getJumpThreadDuplicationCost(), getLandingPadInst(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), llvm::InsertPreheaderForLoop(), isAtomic(), isLandingPad(), and SimplifyBranchOnICmpChain().
const Instruction* llvm::BasicBlock::getFirstNonPHI () const inline
Definition at line 131 of file BasicBlock.h.
Instruction * BasicBlock::getFirstNonPHIOrDbg ()
Returns a pointer to the first instruction in this block that is not a PHINode or a debug intrinsic.
Definition at line 140 of file BasicBlock.cpp.
References begin(), and i.
Referenced by llvm::createJumpThreadingPass(), FindPHIForConditionForwarding(), SimplifyBranchOnICmpChain(), SimplifyCondBranchToTwoReturns(), SwitchToLookupTable(), and llvm::InstCombiner::visitAllocaInst().
const Instruction* llvm::BasicBlock::getFirstNonPHIOrDbg () const inline
Definition at line 138 of file BasicBlock.h.
Instruction * BasicBlock::getFirstNonPHIOrDbgOrLifetime ()
Returns a pointer to the first instruction in this block that is not a PHINode, a debug intrinsic, or a lifetime intrinsic.
Definition at line 150 of file BasicBlock.cpp.
References begin(), llvm::dyn_cast(), llvm::IntrinsicInst::getIntrinsicID(), i, llvm::Intrinsic::lifetime_end, and llvm::Intrinsic::lifetime_start.
Referenced by SwitchToLookupTable().
const Instruction* llvm::BasicBlock::getFirstNonPHIOrDbgOrLifetime () const inline
Definition at line 145 of file BasicBlock.h.
const InstListType& llvm::BasicBlock::getInstList () const inline
Return the underlying instruction list container.
Currently you need to access the underlying instruction list container directly if you want to modify it.
Definition at line 214 of file BasicBlock.h.
Referenced by AddPHINodeEntriesForMappedBlock(), changeToUnreachable(), llvm::CloneAndPruneFunctionInto(), llvm::CloneBasicBlock(), llvm::CloneFunction(), CloneLoopBlocks(), llvm::BinaryOperator::Create(), createCallHelper(), llvm::createLICMPass(), createMalloc(), llvm::DeleteDeadBlock(), DeleteInstructionInBlock(), llvm::InstCombiner::DoOneIteration(), llvm::Instruction::eraseFromParent(), llvm::CodeExtractor::extractCodeRegion(), FindPhiPredForUseInBlock(), FirstNonDbg(), FoldBlockIntoPredecessor(), llvm::FoldBranchToCommonDest(), FoldCondBranchOnPHI(), llvm::FoldReturnIntoUncondBranch(), FoldTwoEntryPHINode(), FunctionNumber(), llvm::IRBuilderBase::getCurrentFunctionReturnType(), HandleCallsInBlockInlinedThroughInvoke(), HoistThenElseCodeToIf(), INITIALIZE_PASS(), llvm::InlineFunction(), llvm::Instruction::insertAfter(), llvm::Instruction::insertBefore(), insertFastDiv(), llvm::IRBuilderDefaultInserter< true >::InsertHelper(), llvm::InstCombiner::InsertNewInstBefore(), llvm::Instruction::Instruction(), isAlwaysFoldable(), LdStHasDebugValue(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), llvm::Instruction::moveBefore(), operator<<(), llvm::BitcodeReader::ParseTriple(), PlaceSplitBlockCarefully(), promoteSingleBlockAlloca(), llvm::Instruction::removeFromParent(), removePredecessor(), llvm::ReplaceInstWithInst(), ReplaceUsesOfWith(), llvm::UnifyFunctionExitNodes::runOnFunction(), shouldSpeculateInstrs(), SinkThenElseCodeToEnd(), SpeculativelyExecuteBB(), splitBasicBlock(), llvm::SplitLandingPadPredecessors(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), and llvm::UnrollLoop().
InstListType& llvm::BasicBlock::getInstList () inline
Definition at line 215 of file BasicBlock.h.
LandingPadInst * BasicBlock::getLandingPadInst ()
Return the landingpad instruction associated with the landing pad.
getLandingPadInst() - Return the landingpad instruction associated with the landing pad.
Definition at line 366 of file BasicBlock.cpp.
References llvm::dyn_cast(), and getFirstNonPHI().
Referenced by CloneLoop(), INITIALIZE_PASS(), llvm::InlineFunction(), isContiguous(), MarkBlocksLiveIn(), and llvm::SplitLandingPadPredecessors().
const LandingPadInst * BasicBlock::getLandingPadInst () const
Definition at line 369 of file BasicBlock.cpp.
References llvm::dyn_cast(), and getFirstNonPHI().
const Function* llvm::BasicBlock::getParent () const inline
Return the enclosing method, or null if none.
Definition at line 116 of file BasicBlock.h.
Referenced by AddPHINodeEntriesForMappedBlock(), llvm::CodeMetrics::analyzeBasicBlock(), canFoldIVIncExpr(), CanTRE(), changeToUnreachable(), checkInterfaceFunction(), llvm::CloneBasicBlock(), llvm::CloneFunction(), CloneLoop(), CloneLoopBlocks(), CollectBSwapParts(), llvm::ConstantFoldTerminator(), llvm::createArgumentPromotionPass(), llvm::createCodeGenPreparePass(), llvm::IRBuilderBase::CreateGlobalString(), llvm::createJumpThreadingPass(), llvm::IRBuilderBase::CreateLifetimeEnd(), llvm::IRBuilderBase::CreateLifetimeStart(), llvm::IRBuilderBase::CreateMemCpy(), llvm::IRBuilderBase::CreateMemMove(), llvm::IRBuilderBase::CreateMemSet(), llvm::createMergeFunctionsPass(), llvm::createPPCCTRLoopsVerify(), llvm::createPruneEHPass(), cse(), deleteIfDeadInstruction(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), llvm::DominatorTree::dominates(), llvm::EmitFPutC(), llvm::EmitFPutS(), llvm::EmitFWrite(), llvm::EmitMemChr(), llvm::EmitMemCmp(), llvm::EmitMemCpyChk(), llvm::EmitPutChar(), llvm::EmitPutS(), llvm::EmitStrChr(), llvm::EmitStrCpy(), llvm::EmitStrLen(), llvm::EmitStrNCmp(), llvm::EmitStrNCpy(), llvm::EmitStrNLen(), llvm::EmitUnaryFloatFnCall(), eraseFromParent(), llvm::CodeExtractor::extractCodeRegion(), llvm::CodeExtractor::findInputsOutputs(), FindPhiPredForUseInBlock(), FindPotentialTailCall(), FindUnconditionalPreds(), FirstNonDbg(), FitWeights(), FoldCondBranchOnPHI(), GenerateARCBBEntranceAnnotation(), GenerateARCBBTerminatorAnnotation(), generateUnsignedDivisionCode(), llvm::BlockAddress::get(), llvm::MMIAddrLabelMap::getAddrLabelSymbol(), getCommonReturnValue(), getComparePred(), llvm::IRBuilderBase::getCurrentFunctionReturnType(), llvm::MemoryDependenceAnalysis::getDependency(), llvm::Trace::getFunction(), getFunctionForValue(), llvm::ValueEnumerator::getGlobalBasicBlockID(), llvm::MemoryDependenceAnalysis::getLoadLoadClobberFullWidthSize(), GetLocation(), getMemSetPatternValue(), llvm::DOTGraphTraits< DomTreeNode * >::getNodeLabel(), llvm::DOTGraphTraits< RegionNode * >::getNodeLabel(), llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), llvm::MemoryDependenceAnalysis::getPointerDependencyFrom(), llvm::JIT::getPointerToBasicBlock(), llvm::SelectionDAGBuilder::getValueImpl(), getValueSymbolTable(), HandleByValArgument(), HandleInlinedInvoke(), hasAddressTakenAndUsed(), hasOutsideLoopUser(), INITIALIZE_PASS(), llvm::InlineFunction(), insertFastDiv(), InstructionDereferencesPointer(), llvm::isAllocaPromotable(), isAlwaysFoldable(), isContiguous(), isDynamicConstant(), llvm::SelectionDAGBuilder::isExportableFromCurrentBlock(), isFormingBranchFromSelectProfitable(), llvm::isInTailCallPosition(), IsNonLocalValue(), llvm::SCEVUnknown::isOffsetOf(), isOnlyReachableViaThisEdge(), llvm::isPotentiallyReachable(), llvm::AllocaInst::isStaticAlloca(), isTrivialLoopExitBlock(), isZero(), LLVMGetNextBasicBlock(), LLVMGetPreviousBasicBlock(), LLVMInsertBasicBlockInContext(), llvm::IntrinsicLowering::LowerToByteSwap(), MarkBlocksLiveIn(), moveAfter(), moveBefore(), NegateValue(), operator<<(), OptimizeCmpExpression(), PerformHeapAllocSRoA(), llvm::PHITransAddr::PHITranslateWithInsertion(), PlaceSplitBlockCarefully(), llvm::AssemblyWriter::printBasicBlock(), PrintOps(), ProcessUAddIdiom(), ProcessUGT_ADDCST_ADD(), promoteSingleBlockAlloca(), removeFromParent(), RemoveInstInputs(), removeUndefIntroducingPredecessor(), ReplaceCallWith(), replaceConstantExprOp(), ReplaceUsesOfWith(), rewriteSingleStoreAlloca(), SimplifyBranchOnICmpChain(), SimplifyCondBranchToCondBranch(), splitBasicBlock(), llvm::SplitBlockAndInsertIfThen(), llvm::SplitBlockPredecessors(), llvm::SplitCriticalEdge(), llvm::SplitLandingPadPredecessors(), SwitchToLookupTable(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), TryToSimplifyUncondBranchWithICmpInIt(), TryToSinkInstruction(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopProlog(), UpdateCallGraphAfterInlining(), llvm::MMIAddrLabelMap::UpdateForDeletedBlock(), useFuncSeen(), ValueDominatesPHI(), llvm::InstCombiner::visitAllocaInst(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitFPTrunc(), and ~BasicBlock().
Function* llvm::BasicBlock::getParent () inline
Definition at line 117 of file BasicBlock.h.
BasicBlock * BasicBlock::getSinglePredecessor ()
Return this block if it has a single predecessor block. Otherwise return a null pointer.
getSinglePredecessor - If this basic block has a single predecessor block, return the block, otherwise return a null pointer.
Definition at line 183 of file BasicBlock.cpp.
References llvm::pred_begin(), and llvm::pred_end().
Referenced by CanPropagatePredecessorsForPHIs(), llvm::CloneAndPruneFunctionInto(), llvm::createCodeGenPreparePass(), llvm::createEarlyCSEPass(), llvm::createLoopSimplifyPass(), llvm::createObjCARCContractPass(), createPrivateNonConstGlobalForString(), llvm::DeleteDeadBlock(), deleteIfDeadInstruction(), llvm::DemoteRegToStack(), llvm::DominatorTree::dominates(), FindPHIForConditionForwarding(), FoldBlockIntoPredecessor(), llvm::FoldBranchToCommonDest(), llvm::GetIfCondition(), hasAddressTakenAndUsed(), isLifetimeStart(), isOnlyReachableViaThisEdge(), llvm::MergeBasicBlockIntoOnlyPred(), removeUndefIntroducingPredecessor(), ReplaceUsesOfWith(), shouldSpeculateInstrs(), SolveQuadraticEquation(), llvm::SplitEdge(), SwitchToLookupTable(), tryToMoveFreeBeforeNullTest(), and TryToSimplifyUncondBranchWithICmpInIt().
const BasicBlock* llvm::BasicBlock::getSinglePredecessor () const inline
Definition at line 176 of file BasicBlock.h.
static iplist<Instruction> BasicBlock::* llvm::BasicBlock::getSublistAccess (Instruction *) inline static
Returns a pointer to a member of the instruction list.
Definition at line 218 of file BasicBlock.h.
TerminatorInst * BasicBlock::getTerminator ()
Returns the terminator instruction if the block is well formed or null if the block is not well formed.
Definition at line 120 of file BasicBlock.cpp.
References llvm::iplist< NodeTy, Traits >::back(), llvm::dyn_cast(), and llvm::iplist< NodeTy, Traits >::empty().
Referenced by AddPHINodeEntriesForMappedBlock(), AddReachableCodeToWorklist(), AddressIsTaken(), llvm::CodeMetrics::analyzeBasicBlock(), BlockIsSimpleEnoughToThreadThrough(), canExpandBackedgeTakenCount(), canIfConvertPHINodes(), checkInterfaceFunction(), llvm::CloneAndPruneFunctionInto(), llvm::CloneFunction(), llvm::CloneFunctionInto(), CloneLoop(), CloneLoopBlocks(), CommitValueTo(), ConnectProlog(), llvm::ConstantFoldTerminator(), convertMemSetToLoop(), convertTransferToLoop(), llvm::createCodeGenPreparePass(), llvm::createJumpThreadingPass(), llvm::createLICMPass(), llvm::createLoopDeletionPass(), llvm::createLoopSimplifyPass(), llvm::createObjCARCContractPass(), createPHIsForSplitLoopExit(), llvm::createPPCCTRLoopsVerify(), CreatePrologue(), llvm::createSinkingPass(), cse(), llvm::DeleteDeadBlock(), DeleteInstructionInBlock(), llvm::DemotePHIToStack(), DominatesMergePoint(), llvm::SCEVExpander::expandCodeFor(), llvm::FastISel::FastEmitZExtFromI1(), llvm::CodeExtractor::findInputsOutputs(), FindLoopCounter(), FindMostPopularDest(), FindPHIForConditionForwarding(), FindUnconditionalPreds(), FirstNonDbg(), FitWeights(), FoldBlockIntoPredecessor(), llvm::FoldBranchToCommonDest(), FoldCondBranchOnPHI(), FoldOperationIntoSelectOperand(), llvm::FoldReturnIntoUncondBranch(), FoldTwoEntryPHINode(), llvm::ScalarEvolution::forgetValue(), generateUnsignedDivisionCode(), genLoopLimit(), GetBestDestForJumpOnUndef(), llvm::DOTGraphTraits< const Function * >::getEdgeSourceLabel(), getEdgeValueLocal(), getGEPInductionOperand(), llvm::DenseMapInfo< ComparableFunction >::getHashValue(), llvm::GetIfCondition(), getInsertPointForUses(), llvm::Loop::getLoopID(), getLoopTest(), getMaxWeightFor(), getMemSetPatternValue(), llvm::GetSuccessorNumber(), hasAddressTakenAndUsed(), hasOutsideLoopUser(), llvm::SCEVExpander::hoistIVInc(), INITIALIZE_PASS(), llvm::InlineFunction(), llvm::DIBuilder::insertDeclare(), llvm::InsertPreheaderForLoop(), isAlwaysFoldable(), llvm::SparseSolver::isEdgeFeasible(), isFormingBranchFromSelectProfitable(), llvm::isInTailCallPosition(), isLifetimeStart(), llvm::ScalarEvolution::isLoopBackedgeGuardedByCond(), isLoopInvariant(), isOnlyReachableViaThisEdge(), isOnlyUsedInEntryBlock(), isPossibleSelfRead(), isSafeAndProfitableToSinkLoad(), isSafePHIToSpeculate(), isSimpleLoadStore(), llvm::BasicBlockEdge::isSingleEdge(), isTrivialLoopExitBlock(), llvm::Loop::makeLoopInvariant(), markAliveBlocks(), MarkBlocksLiveIn(), matchPair(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), mergeEmptyReturnBlocks(), OptimizeCmpExpression(), PerformHeapAllocSRoA(), llvm::PHITransAddr::PHITranslateWithInsertion(), PlaceSplitBlockCarefully(), removeUndefIntroducingPredecessor(), replaceConstantExprOp(), replaceSuccessorsPhiUsesWith(), ReplaceUsesOfWith(), llvm::UnifyFunctionExitNodes::runOnFunction(), llvm::IRBuilderBase::SetInsertPoint(), llvm::Loop::setLoopID(), shouldSpeculateInstrs(), SimplifyBranchOnICmpChain(), SimplifyCondBranchToCondBranch(), SimplifyCondBranchToTwoReturns(), SinkThenElseCodeToEnd(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), speculatePHINodeLoads(), SpeculativelyExecuteBB(), SplitAddRecs(), splitBasicBlock(), llvm::SplitBlockAndInsertIfThen(), llvm::SplitCriticalEdge(), SplitCriticalSideEffectEdges(), llvm::SplitEdge(), llvm::SplitLandingPadPredecessors(), llvm::succ_begin(), llvm::succ_end(), SwitchToLookupTable(), tryToMakeAllocaBePromotable(), tryToMoveFreeBeforeNullTest(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), TryToSimplifyUncondBranchWithICmpInIt(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopProlog(), ValuesOverlap(), llvm::InstCombiner::visitCallInst(), and llvm::InstCombiner::visitStoreInst().
const TerminatorInst * BasicBlock::getTerminator () const
Definition at line 125 of file BasicBlock.cpp.
References llvm::iplist< NodeTy, Traits >::back(), llvm::dyn_cast(), and llvm::iplist< NodeTy, Traits >::empty().
BasicBlock * BasicBlock::getUniquePredecessor ()
Return this block if it has a unique predecessor block. Otherwise return a null pointer.
Note that unique predecessor doesn't mean single edge, there can be multiple edges from the unique predecessor to this block (for example a switch statement with multiple cases having the same destination).
getUniquePredecessor - If this basic block has a unique predecessor block, return the block, otherwise return a null pointer. Note that unique predecessor doesn't mean single edge, there can be multiple edges from the unique predecessor to this block (for example a switch statement with multiple cases having the same destination).
Definition at line 196 of file BasicBlock.cpp.
References llvm::pred_begin(), and llvm::pred_end().
Referenced by isDynamicConstant(), isSafeToMove(), isZero(), and llvm::MergeBlockIntoPredecessor().
const BasicBlock* llvm::BasicBlock::getUniquePredecessor () const inline
Definition at line 186 of file BasicBlock.h.
ValueSymbolTable * BasicBlock::getValueSymbolTable ()
Returns a pointer to the symbol table if one exists.
Definition at line 27 of file BasicBlock.cpp.
References F(), and getParent().
bool llvm::BasicBlock::hasAddressTaken () const inline
Returns true if there are any uses of this basic block other than direct branches, switches, etc. to it.
Definition at line 268 of file BasicBlock.h.
References DEFINE_SIMPLE_CONVERSION_FUNCTIONS, and llvm::Value::setValueSubclassData().
Referenced by llvm::CloneFunction(), llvm::CloneFunctionInto(), llvm::createCodeGenPreparePass(), llvm::AsmPrinter::EmitFunctionBody(), llvm::MMIAddrLabelMap::getAddrLabelSymbol(), llvm::MMIAddrLabelMap::getAddrLabelSymbolToEmit(), hasAddressTakenAndUsed(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), OptimizeCmpExpression(), shouldSpeculateInstrs(), SwitchToLookupTable(), llvm::UnrollLoop(), and ~BasicBlock().
bool BasicBlock::isLandingPad () const
Return true if this basic block is a landing pad.
Being a ``landing pad'' means that the basic block is the destination of the 'unwind' edge of an invoke instruction.
isLandingPad - Return true if this basic block is a landing pad. I.e., it's the destination of the 'unwind' edge of an invoke instruction.
Definition at line 360 of file BasicBlock.cpp.
References getFirstNonPHI().
Referenced by CloneLoop(), ConnectProlog(), createPHIsForSplitLoopExit(), hasAddressTakenAndUsed(), INITIALIZE_PASS(), llvm::InsertPreheaderForLoop(), isBlockValidForExtraction(), isLifetimeStart(), isOnlyReachableViaThisEdge(), PlaceSplitBlockCarefully(), llvm::SplitCriticalEdge(), and llvm::SplitLandingPadPredecessors().
void BasicBlock::moveAfter (BasicBlock * MovePos)
Unlink this basic block from its current function and insert it right after MovePos in the function MovePos lives in.
moveAfter - Unlink this basic block from its current function and insert it into the function that MovePos lives in, right after MovePos.
Definition at line 113 of file BasicBlock.cpp.
References llvm::Function::getBasicBlockList(), getParent(), I, and llvm::iplist< NodeTy, Traits >::splice().
Referenced by AddPHINodeEntriesForMappedBlock(), CreatePrologue(), and PlaceSplitBlockCarefully().
void BasicBlock::moveBefore (BasicBlock * MovePos)
Unlink this basic block from its current function and insert it into the function that MovePos lives in, right before MovePos.
moveBefore - Unlink this basic block from its current function and insert it into the function that MovePos lives in, right before MovePos.
Definition at line 106 of file BasicBlock.cpp.
References llvm::Function::getBasicBlockList(), getParent(), and llvm::iplist< NodeTy, Traits >::splice().
Referenced by llvm::createCodeGenPreparePass(), hasAddressTakenAndUsed(), insertFastDiv(), and shouldSpeculateInstrs().
reverse_iterator llvm::BasicBlock::rbegin () inline
Definition at line 198 of file BasicBlock.h.
References llvm::iplist< NodeTy, Traits >::rbegin().
Referenced by FindPotentialTailCall(), isSafeToSpeculateStore(), and isSimpleLoadStore().
const_reverse_iterator llvm::BasicBlock::rbegin () const inline
Definition at line 199 of file BasicBlock.h.
References llvm::iplist< NodeTy, Traits >::rbegin().
void BasicBlock::removeFromParent ()
Unlink 'this' from the containing function, but do not delete it.
Definition at line 96 of file BasicBlock.cpp.
References llvm::Function::getBasicBlockList(), getParent(), and llvm::iplist< NodeTy, Traits >::remove().
void BasicBlock::removePredecessor (BasicBlock * Pred, bool DontDeleteUselessPHIs = false)
Notify the BasicBlock that the predecessor Pred is no longer able to reach it.
This is actually not used to update the Predecessor list, but is actually used to update the PHI nodes that reside in the block. Note that this should be called while the predecessor still refers to this block.
removePredecessor - This method is used to notify a BasicBlock that the specified Predecessor of the block is no longer able to reach it. This is actually not used to update the Predecessor list, but is actually used to update the PHI nodes that reside in the block. Note that this should be called while the predecessor still refers to this block.
Definition at line 216 of file BasicBlock.cpp.
References begin(), llvm::dyn_cast(), llvm::iplist< NodeTy, Traits >::empty(), llvm::Instruction::eraseFromParent(), front(), llvm::UndefValue::get(), llvm::PHINode::getIncomingBlock(), getInstList(), llvm::PHINode::getNumIncomingValues(), llvm::PHINode::hasConstantValue(), llvm::Value::hasNUsesOrMore(), llvm::iplist< NodeTy, Traits >::pop_front(), llvm::pred_begin(), llvm::pred_end(), llvm::PHINode::removeIncomingValue(), and llvm::Value::replaceAllUsesWith().
Referenced by AddPHINodeEntriesForMappedBlock(), AddressIsTaken(), changeToCall(), changeToUnreachable(), llvm::ConstantFoldTerminator(), llvm::createLoopSimplifyPass(), llvm::createPruneEHPass(), llvm::DeleteDeadBlock(), EliminateDeadSwitchCases(), FitWeights(), FoldCondBranchOnPHI(), llvm::FoldReturnIntoUncondBranch(), HandleInlinedInvoke(), hasAddressTakenAndUsed(), llvm::RemovePredecessorAndSimplify(), removeUndefIntroducingPredecessor(), SimplifyBranchOnICmpChain(), SimplifyCondBranchToTwoReturns(), SimplifyTerminatorOnSelect(), llvm::SplitCriticalEdge(), SwitchToLookupTable(), and ValuesOverlap().
reverse_iterator llvm::BasicBlock::rend () inline
Definition at line 200 of file BasicBlock.h.
References llvm::iplist< NodeTy, Traits >::rend().
Referenced by FindPotentialTailCall(), isSafeToSpeculateStore(), and isSimpleLoadStore().
const_reverse_iterator llvm::BasicBlock::rend () const inline
Definition at line 201 of file BasicBlock.h.
References llvm::iplist< NodeTy, Traits >::rend().
void BasicBlock::replaceSuccessorsPhiUsesWith (BasicBlock * New)
Update all phi nodes in this basic block's successors to refer to basic block New instead of to it.
Definition at line 337 of file BasicBlock.cpp.
References begin(), llvm::dyn_cast(), end(), llvm::PHINode::getBasicBlockIndex(), llvm::TerminatorInst::getNumSuccessors(), llvm::TerminatorInst::getSuccessor(), getTerminator(), i, llvm::ARM_PROC::IE, and llvm::PHINode::setIncomingBlock().
Referenced by shouldSpeculateInstrs().
size_t llvm::BasicBlock::size () const inline
Definition at line 203 of file BasicBlock.h.
References llvm::iplist< NodeTy, Traits >::size().
Referenced by deleteIfDeadInstruction(), llvm::FastISel::FastEmitBranch(), FitWeights(), llvm::BitcodeReader::ParseTriple(), SimplifyBranchOnICmpChain(), and tryToMoveFreeBeforeNullTest().
BasicBlock * BasicBlock::splitBasicBlock (iterator I, const Twine & BBName = "")
Split the basic block into two basic blocks at the specified instruction.
Note that all instructions BEFORE the specified iterator stay as part of the original basic block, an unconditional branch is added to the original BB, and the rest of the instructions in the BB are moved to the new BB, including the old terminator. The newly formed BasicBlock is returned. This function invalidates the specified iterator.
Note that this only works on well formed basic blocks (must have a terminator), and 'I' must not be the end of instruction list (which would cause a degenerate basic block to be formed, having a terminator inside of the basic block).
Also note that this doesn't preserve any passes. To split blocks while keeping loop information consistent, use the SplitBlock utility function.
splitBasicBlock - This splits a basic block into two at the specified instruction. Note that all instructions BEFORE the specified iterator stay as part of the original basic block, an unconditional branch is added to the new BB, and the rest of the instructions in the BB are moved to the new BB, including the old terminator. This invalidates the iterator.
Note that this only works on well formed basic blocks (must have a terminator), and 'I' must not be the end of instruction list (which would cause a degenerate basic block to be formed, having a terminator inside of the basic block).
Definition at line 298 of file BasicBlock.cpp.
References begin(), Create(), llvm::BranchInst::Create(), llvm::dyn_cast(), end(), llvm::iplist< NodeTy, Traits >::end(), llvm::PHINode::getBasicBlockIndex(), getContext(), getInstList(), getParent(), getTerminator(), I, llvm::next(), llvm::PHINode::setIncomingBlock(), llvm::iplist< NodeTy, Traits >::splice(), llvm::succ_begin(), and llvm::succ_end().
Referenced by convertMemSetToLoop(), convertTransferToLoop(), CreatePrologue(), llvm::CodeExtractor::findInputsOutputs(), generateUnsignedDivisionCode(), getGEPInductionOperand(), HandleCallsInBlockInlinedThroughInvoke(), INITIALIZE_PASS(), llvm::InlineFunction(), isFormingBranchFromSelectProfitable(), MarkBlocksLiveIn(), PerformHeapAllocSRoA(), llvm::NVPTXSplitBBatBar::runOnFunction(), SimplifyBranchOnICmpChain(), llvm::SplitBlock(), and llvm::SplitBlockAndInsertIfThen().
Friends And Related Function Documentation
friend class BlockAddress friend
Definition at line 74 of file BasicBlock.h.
friend class SymbolTableListTraits< BasicBlock, Function > friend
Definition at line 82 of file BasicBlock.h.
The documentation for this class was generated from the following files:
BasicBlock.h
BasicBlock.cpp