LLVM: llvm::NVPTXAllocaHoisting Class Reference
LLVM API Documentation
llvm::NVPTXAllocaHoisting Class Reference
#include <NVPTXAllocaHoisting.h>
Public Member Functions
NVPTXAllocaHoisting ()
void getAnalysisUsage (AnalysisUsage &AU) const
virtual const char * getPassName () const
virtual bool runOnFunction (Function &function)
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const
createPrinterPass - Get a function printer pass.
virtual void assignPassManager (PMStack &PMS, PassManagerType T)
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 1
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
Definition at line 28 of file NVPTXAllocaHoisting.h.
Constructor & Destructor Documentation
llvm::NVPTXAllocaHoisting::NVPTXAllocaHoisting () inline
Definition at line 31 of file NVPTXAllocaHoisting.h.
Referenced by llvm::createAllocaHoisting().
Member Function Documentation
void llvm::NVPTXAllocaHoisting::getAnalysisUsage (AnalysisUsage &) const inline virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job. If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 33 of file NVPTXAllocaHoisting.h.
References llvm::AnalysisUsage::addPreserved(), and llvm::AnalysisUsage::addRequired().
virtual const char* llvm::NVPTXAllocaHoisting::getPassName () const inline virtual
getPassName - Return a nice clean name for a pass. This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 38 of file NVPTXAllocaHoisting.h.
References llvm::createAllocaHoisting(), and runOnFunction().
bool llvm::NVPTXAllocaHoisting::runOnFunction (Function & F) virtual
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
Implements llvm::FunctionPass.
Definition at line 21 of file NVPTXAllocaHoisting.cpp.
References llvm::dyn_cast(), llvm::sys::path::end(), llvm::AllocaInst::getArraySize(), I, ID, llvm::Instruction::moveBefore(), and llvm::X.
Referenced by getPassName().
Member Data Documentation
char llvm::NVPTXAllocaHoisting::ID = 1 static
Definition at line 30 of file NVPTXAllocaHoisting.h.
Referenced by runOnFunction().
The documentation for this class was generated from the following files:
NVPTXAllocaHoisting.h
NVPTXAllocaHoisting.cpp