LLVM: llvm::ListInit Class Reference
LLVM API Documentation
llvm::ListInit Class Reference
#include <Record.h>
Public Types
typedef std::vector< Init * >::const_iterator const_iterator
Public Member Functions
void Profile (FoldingSetNodeID &ID) const
unsigned getSize () const
Init * getElement (unsigned i) const
Record * getElementAsRecord (unsigned i) const
virtual Init * convertInitListSlice (const std::vector< unsigned > &Elements) const
virtual Init * convertInitializerTo (RecTy *Ty) const
virtual Init * resolveReferences (Record &R, const RecordVal *RV) const
virtual std::string getAsString () const
getAsString - Convert this value to a string form.
ArrayRef< Init * > getValues () const
const_iterator begin () const
const_iterator end () const
size_t size () const
bool empty () const
virtual Init * resolveListElementReference (Record &R, const RecordVal *RV, unsigned Elt) const
virtual Init * getBit (unsigned Bit) const
Public Member Functions inherited from llvm::TypedInit
RecTy * getType () const
virtual Init * convertInitializerBitRange (const std::vector< unsigned > &Bits) const
virtual RecTy * getFieldType (const std::string &FieldName) const
Public Member Functions inherited from llvm::Init
InitKind getKind () const
virtual ~Init ()
virtual bool isComplete () const
void print (raw_ostream &OS) const
print - Print out this value.
virtual std::string getAsUnquotedString () const
void dump () const
virtual Init * getFieldInit (Record &R, const RecordVal *RV, const std::string &FieldName) const
virtual Init * getBitVar () const
virtual unsigned getBitNum () const
Public Member Functions inherited from llvm::FoldingSetImpl::Node
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static bool classof (const Init *I)
static ListInit * get (ArrayRef< Init * > Range, RecTy *EltTy)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind {
IK_BitInit, IK_BitsInit, IK_FirstTypedInit, IK_DagInit,
IK_DefInit, IK_FieldInit, IK_IntInit, IK_ListInit,
IK_FirstOpInit, IK_BinOpInit, IK_TernOpInit, IK_UnOpInit,
IK_LastOpInit, IK_StringInit, IK_VarInit, IK_VarListElementInit,
IK_LastTypedInit, IK_UnsetInit, IK_VarBitInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T)
Protected Member Functions inherited from llvm::Init
Init (InitKind K)
Detailed Description
ListInit - [AL, AH, CL] - Represent a list of defs
Definition at line 780 of file Record.h.
Member Typedef Documentation
typedef std::vector<Init*>::const_iterator llvm::ListInit::const_iterator
Definition at line 783 of file Record.h.
Member Function Documentation
const_iterator llvm::ListInit::begin () const inline
Definition at line 827 of file Record.h.
static bool llvm::ListInit::classof (const Init * I) inline static
Definition at line 794 of file Record.h.
References llvm::Init::getKind().
virtual Init* llvm::ListInit::convertInitializerTo (RecTy * Ty) const inline virtual
convertInitializerTo - This virtual function is a simple call-back function that should be overridden to call the appropriate RecTy::convertValue method.
Implements llvm::Init.
Definition at line 812 of file Record.h.
References llvm::RecTy::convertValue(), and llvm::RecTy::getAsString().
Init * ListInit::convertInitListSlice (const std::vector< unsigned > & Elements) const virtual
convertInitListSlice - This method is used to implement the list slice selection operator. Given an initializer, it selects the specified list elements, returning them as a new init of list type. If it is not legal to take a slice of this, return null.
Reimplemented from llvm::TypedInit.
Definition at line 650 of file Record.cpp.
References get(), llvm::Intrinsic::getType(), and i.
bool llvm::ListInit::empty () const inline
Definition at line 831 of file Record.h.
const_iterator llvm::ListInit::end () const inline
Definition at line 828 of file Record.h.
ListInit * ListInit::get (ArrayRef< Init * > Range, RecTy * EltTy) static
Definition at line 623 of file Record.cpp.
References I, and ProfileListInit().
Referenced by llvm::TypedInit::convertInitListSlice(), convertInitListSlice(), llvm::ListRecTy::convertValue(), llvm::UnOpInit::Fold(), ForeachHelper(), GetNewAnonymousName(), and resolveReferences().
std::string ListInit::getAsString () const virtual
getAsString - Convert this value to a string form.
Implements llvm::Init.
Definition at line 703 of file Record.cpp.
References i.
virtual Init* llvm::ListInit::getBit (unsigned Bit) const inline virtual
getBit - This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 839 of file Record.h.
References llvm_unreachable.
Init* llvm::ListInit::getElement (unsigned i) const inline
Definition at line 802 of file Record.h.
References i.
Referenced by llvm::ListRecTy::convertValue(), GetNewAnonymousName(), llvm::Record::getValueAsListOfDefs(), llvm::Record::getValueAsListOfInts(), llvm::Record::getValueAsListOfStrings(), and llvm::VarInit::resolveListElementReference().
Record * ListInit::getElementAsRecord (unsigned i) const
Definition at line 660 of file Record.cpp.
References llvm::dyn_cast(), i, and llvm::PrintFatalError().
unsigned llvm::ListInit::getSize () const inline
Definition at line 801 of file Record.h.
Referenced by llvm::ListRecTy::convertValue(), llvm::SubMultiClassReference::dump(), GetNewAnonymousName(), llvm::Record::getValueAsListOfDefs(), llvm::Record::getValueAsListOfInts(), llvm::Record::getValueAsListOfStrings(), and llvm::VarInit::resolveListElementReference().
ArrayRef<Init*> llvm::ListInit::getValues () const inline
Definition at line 825 of file Record.h.
void ListInit::Profile (FoldingSetNodeID & ID) const
Definition at line 641 of file Record.cpp.
References llvm::dyn_cast(), llvm::ListRecTy::getElementType(), llvm::Intrinsic::getType(), and ProfileListInit().
Init * ListInit::resolveListElementReference (Record & R, const RecordVal * RV, unsigned Elt) const virtual
resolveListElementReference - This method is used to implement VarListElementInit::resolveReferences. If the list element is resolvable now, we return the resolved value, otherwise we return null.
Implements llvm::TypedInit.
Definition at line 690 of file Record.cpp.
Referenced by llvm::SubMultiClassReference::dump().
Init * ListInit::resolveReferences (Record & R, const RecordVal * RV) const virtual
resolveReferences - This method is used by classes that refer to other variables which may not be defined at the time they expression is formed. If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 668 of file Record.cpp.
References get(), llvm::Intrinsic::getType(), i, and llvm::Init::resolveReferences().
size_t llvm::ListInit::size () const inline
Definition at line 830 of file Record.h.
The documentation for this class was generated from the following files:
Record.h
Record.cpp