LLVM: llvm::ImmutableIntervalMap< ValT >::Factory Class Reference
LLVM API Documentation
llvm::ImmutableIntervalMap< ValT >::Factory Class Reference
#include <ImmutableIntervalMap.h>
Public Member Functions
Factory (BumpPtrAllocator &Alloc)
ImmutableIntervalMap getEmptyMap ()
ImmutableIntervalMap add (ImmutableIntervalMap Old, key_type_ref K, data_type_ref D)
ImmutableIntervalMap remove (ImmutableIntervalMap Old, key_type_ref K)
data_type * lookup (ImmutableIntervalMap M, key_type_ref K)
Detailed Description
template<typename ValT>
class llvm::ImmutableIntervalMap< ValT >::Factory
Definition at line 210 of file ImmutableIntervalMap.h.
Constructor & Destructor Documentation
template<typename ValT > llvm::ImmutableIntervalMap< ValT >::Factory::Factory (BumpPtrAllocator & Alloc) inline
Definition at line 214 of file ImmutableIntervalMap.h.
Member Function Documentation
template<typename ValT > ImmutableIntervalMap llvm::ImmutableIntervalMap< ValT >::Factory::add (ImmutableIntervalMap Old, key_type_ref K, data_type_ref D) inline
Definition at line 220 of file ImmutableIntervalMap.h.
References llvm::ImutAVLFactory< ImutInfo >::add(), llvm::ImutAVLFactory< ImutInfo >::getCanonicalTree(), and llvm::ImmutableMap< KeyT, ValT, ValInfo >::Root.
template<typename ValT > ImmutableIntervalMap llvm::ImmutableIntervalMap< ValT >::Factory::getEmptyMap () inline
Definition at line 216 of file ImmutableIntervalMap.h.
References llvm::ImutAVLFactory< ImutInfo >::getEmptyTree().
template<typename ValT > data_type* llvm::ImmutableIntervalMap< ValT >::Factory::lookup (ImmutableIntervalMap M, key_type_ref K) inline
Definition at line 231 of file ImmutableIntervalMap.h.
References llvm::ImutIntervalAVLFactory< ImutInfo >::Find(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::getRoot(), llvm::ImutAVLTree< ImutInfo >::getValue(), and lookup().
template<typename ValT > ImmutableIntervalMap llvm::ImmutableIntervalMap< ValT >::Factory::remove (ImmutableIntervalMap Old, key_type_ref K) inline
Definition at line 226 of file ImmutableIntervalMap.h.
References llvm::ImutAVLFactory< ImutInfo >::getCanonicalTree(), and llvm::ImutAVLFactory< ImutInfo >::remove().
The documentation for this class was generated from the following file:
ImmutableIntervalMap.h