LLVM: llvm::PMStack Class Reference
LLVM API Documentation
llvm::PMStack Class Reference
#include <LegacyPassManagers.h>
Public Types
typedef std::vector< PMDataManager * >::const_reverse_iterator iterator
Public Member Functions
iterator begin () const
iterator end () const
void pop ()
PMDataManager * top () const
void push (PMDataManager *PM)
bool empty () const
void dump () const
Detailed Description
PMStack - This class implements a stack data structure of PMDataManager pointers.
Top level pass managers (see PassManager.cpp) maintain active Pass Managers using PMStack. Each Pass implements assignPassManager() to connect itself with appropriate manager. assignPassManager() walks PMStack to find suitable manager.
Definition at line 144 of file LegacyPassManagers.h.
Member Typedef Documentation
typedef std::vector<PMDataManager *>::const_reverse_iterator llvm::PMStack::iterator
Definition at line 146 of file LegacyPassManagers.h.
Member Function Documentation
iterator llvm::PMStack::begin () const inline
Definition at line 147 of file LegacyPassManagers.h.
References S.
Referenced by llvm::PMDataManager::populateInheritedAnalysis().
void PMStack::dump () const
Definition at line 1815 of file LegacyPassManager.cpp.
References llvm::dbgs(), I, and S.
bool llvm::PMStack::empty () const inline
Definition at line 153 of file LegacyPassManagers.h.
References llvm::dump(), and S.
Referenced by llvm::LoopPass::assignPassManager(), llvm::CallGraphSCCPass::assignPassManager(), llvm::RegionPass::assignPassManager(), llvm::ModulePass::assignPassManager(), llvm::FunctionPass::assignPassManager(), llvm::BasicBlockPass::assignPassManager(), llvm::LoopPass::preparePassManager(), and llvm::RegionPass::preparePassManager().
iterator llvm::PMStack::end () const inline
Definition at line 148 of file LegacyPassManagers.h.
References S.
Referenced by llvm::PMDataManager::populateInheritedAnalysis().
void PMStack::pop ()
Definition at line 1782 of file LegacyPassManager.cpp.
References llvm::PMDataManager::initializeAnalysisInfo(), and S.
Referenced by llvm::LoopPass::assignPassManager(), llvm::CallGraphSCCPass::assignPassManager(), llvm::RegionPass::assignPassManager(), llvm::ModulePass::assignPassManager(), llvm::FunctionPass::assignPassManager(), llvm::LoopPass::preparePassManager(), and llvm::RegionPass::preparePassManager().
void PMStack::push (PMDataManager * PM)
Definition at line 1791 of file LegacyPassManager.cpp.
References llvm::PMDataManager::getDepth(), llvm::PMDataManager::getPassManagerType(), llvm::PMT_FunctionPassManager, llvm::PMT_ModulePassManager, S, llvm::PMDataManager::setDepth(), and llvm::PMDataManager::setTopLevelManager().
Referenced by llvm::LoopPass::assignPassManager(), llvm::CallGraphSCCPass::assignPassManager(), llvm::RegionPass::assignPassManager(), llvm::FunctionPass::assignPassManager(), and llvm::BasicBlockPass::assignPassManager().
PMDataManager* llvm::PMStack::top () const inline
Definition at line 151 of file LegacyPassManagers.h.
References S.
Referenced by llvm::LoopPass::assignPassManager(), llvm::CallGraphSCCPass::assignPassManager(), llvm::RegionPass::assignPassManager(), llvm::ModulePass::assignPassManager(), llvm::FunctionPass::assignPassManager(), llvm::BasicBlockPass::assignPassManager(), llvm::LoopPass::preparePassManager(), and llvm::RegionPass::preparePassManager().
The documentation for this class was generated from the following files:
LegacyPassManagers.h
LegacyPassManager.cpp