LLVM: llvm::DebugRecVH Class Reference
LLVM API Documentation
llvm::DebugRecVH Class Reference
#include <LLVMContextImpl.h>
Public Member Functions
DebugRecVH (MDNode *n, LLVMContextImpl *ctx, int idx)
MDNode * get () const
virtual void deleted ()
virtual void allUsesReplacedWith (Value *VNew)
Public Member Functions inherited from llvm::CallbackVH
CallbackVH ()
CallbackVH (Value *P)
operator Value * () const
Public Member Functions inherited from llvm::ValueHandleBase
ValueHandleBase (HandleBaseKind Kind)
ValueHandleBase (HandleBaseKind Kind, Value *V)
ValueHandleBase (HandleBaseKind Kind, const ValueHandleBase &RHS)
~ValueHandleBase ()
Value * operator= (Value *RHS)
Value * operator= (const ValueHandleBase &RHS)
Value * operator-> () const
Value & operator* () const
Additional Inherited Members
Static Public Member Functions inherited from llvm::ValueHandleBase
static void ValueIsDeleted (Value *V)
static void ValueIsRAUWd (Value *Old, Value *New)
Protected Types inherited from llvm::ValueHandleBase
enum HandleBaseKind { Assert, Callback, Tracking, Weak }
Protected Member Functions inherited from llvm::CallbackVH
CallbackVH (const CallbackVH &RHS)
virtual ~CallbackVH ()
void setValPtr (Value *P)
Protected Member Functions inherited from llvm::ValueHandleBase
Value * getValPtr () const
void setValPtrInt (unsigned K)
unsigned getValPtrInt () const
Static Protected Member Functions inherited from llvm::ValueHandleBase
static bool isValid (Value *V)
Detailed Description
DebugRecVH - This is a CallbackVH used to keep the Scope -> index maps up to date as MDNodes mutate. This class is implemented in DebugLoc.cpp.
Definition at line 212 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
llvm::DebugRecVH::DebugRecVH (MDNode * n, LLVMContextImpl * ctx, int idx) inline
Definition at line 222 of file LLVMContextImpl.h.
Member Function Documentation
void DebugRecVH::allUsesReplacedWith (Value *) virtual
Called when this->getValPtr()->replaceAllUsesWith(new_value) is called, before any of the uses have actually been replaced. If WeakVH were implemented as a CallbackVH, it would use this method to call setValPtr(new_value). AssertingVH would do nothing in this method.
Reimplemented from llvm::CallbackVH.
Definition at line 256 of file DebugLoc.cpp.
References llvm::dyn_cast(), and llvm::MDNode::get().
void DebugRecVH::deleted () virtual
deleted - The MDNode this is pointing to got deleted, so this pointer needs to drop to null and we need remove our entry from the DenseMap.
Reimplemented from llvm::CallbackVH.
Definition at line 213 of file DebugLoc.cpp.
References llvm::MDNode::get().
MDNode* llvm::DebugRecVH::get () const inline
Definition at line 225 of file LLVMContextImpl.h.
The documentation for this class was generated from the following files:
LLVMContextImpl.h
DebugLoc.cpp