LLVM: llvm::GCOVBlock Class Reference
LLVM API Documentation
llvm::GCOVBlock Class Reference
GCOVBlock - Collects block information.
#include <GCOV.h>
Public Member Functions
GCOVBlock (GCOVFunction &P, uint32_t N)
~GCOVBlock ()
~GCOVBlock - Delete GCOVBlock and its content.
void addEdge (uint32_t N)
void addLine (uint32_t N)
void addCount (uint64_t N)
size_t getNumEdges ()
void dump ()
dump - Dump GCOVBlock content to dbgs() for debugging purposes.
void collectLineCounts (FileInfo &FI)
Detailed Description
GCOVBlock - Collects block information.
Definition at line 225 of file GCOV.h.
Constructor & Destructor Documentation
llvm::GCOVBlock::GCOVBlock (GCOVFunction & P, uint32_t N) inline
Definition at line 227 of file GCOV.h.
GCOVBlock::~GCOVBlock ()
~GCOVBlock - Delete GCOVBlock and its content.
Definition at line 243 of file GCOV.cpp.
Member Function Documentation
void llvm::GCOVBlock::addCount (uint64_t N) inline
Definition at line 232 of file GCOV.h.
References N.
Referenced by llvm::GCOVFunction::read().
void llvm::GCOVBlock::addEdge (uint32_t N) inline
Definition at line 230 of file GCOV.h.
Referenced by getFunctionName().
void llvm::GCOVBlock::addLine (uint32_t N) inline
Definition at line 231 of file GCOV.h.
Referenced by llvm::GCOVFunction::read().
void GCOVBlock::collectLineCounts (FileInfo & FI)
collectLineCounts - Collect line counts. This must be used after reading .gcno and .gcda files.
Definition at line 250 of file GCOV.cpp.
References llvm::FileInfo::addLineCount(), and I.
void GCOVBlock::dump ()
dump - Dump GCOVBlock content to dbgs() for debugging purposes.
Definition at line 257 of file GCOV.cpp.
References llvm::dbgs(), and I.
size_t llvm::GCOVBlock::getNumEdges () inline
Definition at line 233 of file GCOV.h.
References llvm::dump().
Referenced by llvm::GCOVFunction::read().
The documentation for this class was generated from the following files:
GCOV.h
GCOV.cpp