LLVM: llvm::MCAsmParserSemaCallback Class Reference
LLVM API Documentation
llvm::MCAsmParserSemaCallback Class Reference abstract
MCAsmParserSemaCallback - Generic Sema callback for assembly parser.
#include <MCAsmParser.h>
Classes
struct InlineAsmIdentifierInfo
Public Member Functions
virtual ~MCAsmParserSemaCallback ()
virtual void * LookupInlineAsmIdentifier (StringRef &LineBuf, InlineAsmIdentifierInfo &Info, bool IsUnevaluatedContext)=0
virtual bool LookupInlineAsmField (StringRef Base, StringRef Member, unsigned &Offset)=0
Detailed Description
MCAsmParserSemaCallback - Generic Sema callback for assembly parser.
Definition at line 34 of file MCAsmParser.h.
Constructor & Destructor Documentation
MCAsmParserSemaCallback::~MCAsmParserSemaCallback () virtual
Definition at line 50 of file AsmParser.cpp.
References llvm::ARM_PROC::A, B, llvm::SmallVectorImpl< T >::clear(), llvm::createCOFFAsmParser(), llvm::createDarwinAsmParser(), llvm::createELFAsmParser(), llvm::lltok::Error, llvm::MCAsmInfo::getAssemblerDialect(), i, I, LLVM_DELETED_FUNCTION, M, MII, N, llvm::None, P, llvm::SourceMgr::PrintMessage(), Register, llvm::NVPTX::PTXLdStInstCode::Signed, llvm::SmallVectorTemplateCommon< T >::size(), and llvm::SrcMgr.
Referenced by llvm::MCAsmParserSemaCallback::InlineAsmIdentifierInfo::clear().
Member Function Documentation
virtual bool llvm::MCAsmParserSemaCallback::LookupInlineAsmField (StringRef Base, StringRef Member, unsigned & Offset) pure virtual
Referenced by llvm::MCAsmParserSemaCallback::InlineAsmIdentifierInfo::clear().
virtual void* llvm::MCAsmParserSemaCallback::LookupInlineAsmIdentifier (StringRef & LineBuf, InlineAsmIdentifierInfo & Info, bool IsUnevaluatedContext) pure virtual
Referenced by llvm::MCAsmParserSemaCallback::InlineAsmIdentifierInfo::clear().
The documentation for this class was generated from the following files:
MCAsmParser.h
AsmParser.cpp