LLVM: llvm::ValueEnumerator Class Reference
LLVM API Documentation
llvm::ValueEnumerator Class Reference
#include <ValueEnumerator.h>
Public Types
typedef std::vector< Type * > TypeList
typedef std::vector< std::pair< const Value *, unsigned > > ValueList
Public Member Functions
ValueEnumerator (const Module *M)
ValueEnumerator - Enumerate module-level information.
void dump () const
void print (raw_ostream &OS, const ValueMapType &Map, const char *Name) const
unsigned getValueID (const Value *V) const
unsigned getTypeID (Type *T) const
unsigned getInstructionID (const Instruction *I) const
void setInstructionID (const Instruction *I)
unsigned getAttributeID (AttributeSet PAL) const
unsigned getAttributeGroupID (AttributeSet PAL) const
void getFunctionConstantRange (unsigned &Start, unsigned &End) const
const ValueList & getValues () const
const ValueList & getMDValues () const
const SmallVectorImpl< const MDNode * > & getFunctionLocalMDValues () const
const TypeList & getTypes () const
const std::vector< const BasicBlock * > & getBasicBlocks () const
const std::vector< AttributeSet > & getAttributes () const
const std::vector< AttributeSet > & getAttributeGroups () const
unsigned getGlobalBasicBlockID (const BasicBlock *BB) const
void incorporateFunction (const Function &F)
void purgeFunction ()
Detailed Description
Definition at line 37 of file ValueEnumerator.h.
Member Typedef Documentation
typedef std::vector<Type*> llvm::ValueEnumerator::TypeList
Definition at line 39 of file ValueEnumerator.h.
typedef std::vector<std::pair<const Value*, unsigned> > llvm::ValueEnumerator::ValueList
Definition at line 42 of file ValueEnumerator.h.
Constructor & Destructor Documentation
ValueEnumerator::ValueEnumerator (const Module * M)
ValueEnumerator - Enumerate module-level information.
Definition at line 32 of file ValueEnumerator.cpp.
References llvm::Module::alias_begin(), llvm::Module::alias_end(), BB, llvm::Module::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::Module::end(), F(), getAttributes(), llvm::Module::getValueSymbolTable(), llvm::Module::global_begin(), llvm::Module::global_end(), i, I, and llvm::SmallVectorTemplateCommon< T >::size().
Member Function Documentation
void ValueEnumerator::dump () const
Definition at line 139 of file ValueEnumerator.cpp.
References llvm::dbgs(), and print().
unsigned llvm::ValueEnumerator::getAttributeGroupID (AttributeSet PAL) const inline
Definition at line 112 of file ValueEnumerator.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::find(), and llvm::AttributeSet::isEmpty().
Referenced by WriteAttributeGroupTable(), and WriteAttributeTable().
const std::vector<AttributeSet>& llvm::ValueEnumerator::getAttributeGroups () const inline
Definition at line 138 of file ValueEnumerator.h.
References BB, F(), getGlobalBasicBlockID(), incorporateFunction(), M, N, purgeFunction(), and llvm::A64DB::ST.
Referenced by WriteAttributeGroupTable().
unsigned llvm::ValueEnumerator::getAttributeID (AttributeSet PAL) const inline
Definition at line 105 of file ValueEnumerator.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::find(), and llvm::AttributeSet::isEmpty().
Referenced by WriteInstruction(), and WriteModuleInfo().
const std::vector<AttributeSet>& llvm::ValueEnumerator::getAttributes () const inline
Definition at line 135 of file ValueEnumerator.h.
Referenced by ValueEnumerator(), and WriteAttributeTable().
const std::vector<const BasicBlock*>& llvm::ValueEnumerator::getBasicBlocks () const inline
Definition at line 132 of file ValueEnumerator.h.
Referenced by WriteFunction().
void llvm::ValueEnumerator::getFunctionConstantRange (unsigned & Start, unsigned & End) const inline
getFunctionConstantRange - Return the range of values that corresponds to function-local constants.
Definition at line 121 of file ValueEnumerator.h.
Referenced by WriteFunction().
const SmallVectorImpl<const MDNode *>& llvm::ValueEnumerator::getFunctionLocalMDValues () const inline
Definition at line 128 of file ValueEnumerator.h.
Referenced by WriteFunctionLocalMetadata().
unsigned ValueEnumerator::getGlobalBasicBlockID (const BasicBlock * BB) const
getGlobalBasicBlockID - This returns the function-specific ID for the specified basic block. This is relatively expensive information, so it should only be used by rare constructs such as address-of-label.
Definition at line 537 of file ValueEnumerator.cpp.
References BB, llvm::BasicBlock::getParent(), and IncorporateFunctionInfoGlobalBBIDs().
Referenced by getAttributeGroups(), and WriteConstants().
unsigned ValueEnumerator::getInstructionID (const Instruction * I) const
Definition at line 117 of file ValueEnumerator.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::find(), and I.
Referenced by getTypeID(), and WriteMetadataAttachment().
const ValueList& llvm::ValueEnumerator::getMDValues () const inline
Definition at line 127 of file ValueEnumerator.h.
Referenced by WriteModuleMetadata().
unsigned llvm::ValueEnumerator::getTypeID (Type * T) const inline
Definition at line 96 of file ValueEnumerator.h.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::find(), getInstructionID(), I, and setInstructionID().
Referenced by print(), PushValueAndType(), WriteConstants(), WriteInstruction(), WriteMDNode(), WriteModuleInfo(), and WriteTypeTable().
const TypeList& llvm::ValueEnumerator::getTypes () const inline
Definition at line 131 of file ValueEnumerator.h.
Referenced by WriteBlockInfo(), and WriteTypeTable().
unsigned ValueEnumerator::getValueID (const Value * V) const
Definition at line 127 of file ValueEnumerator.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::end(), llvm::ValueMap< KeyT, ValueT, Config >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::find(), llvm::ValueMap< KeyT, ValueT, Config >::find(), and I.
Referenced by pushValue(), PushValueAndType(), pushValueSigned(), WriteConstants(), WriteFunction(), WriteInstruction(), WriteMDNode(), WriteMetadataAttachment(), WriteModuleInfo(), WriteModuleMetadata(), and WriteValueSymbolTable().
const ValueList& llvm::ValueEnumerator::getValues () const inline
Definition at line 126 of file ValueEnumerator.h.
Referenced by WriteConstants(), and WriteModuleConstants().
void ValueEnumerator::incorporateFunction (const Function & F)
incorporateFunction/purgeFunction - If you'd like to deal with a function, use these two methods to get its data into the ValueEnumerator!
Definition at line 448 of file ValueEnumerator.cpp.
References llvm::Function::arg_begin(), llvm::Function::arg_end(), BB, llvm::Function::begin(), llvm::Function::end(), llvm::Function::getAttributes(), llvm::MDNode::getFunction(), i, I, llvm::MDNode::isFunctionLocal(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::ValueMap< KeyT, ValueT, Config >::size(), and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by getAttributeGroups(), WriteFunction(), and WriteFunctionUseList().
void ValueEnumerator::print (raw_ostream & OS, const ValueMapType & Map, const char * Name) const
Definition at line 146 of file ValueEnumerator.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::begin(), llvm::ValueSymbolTable::begin(), llvm::ValueMap< KeyT, ValueT, Config >::count(), llvm::Value::dump(), llvm::dyn_cast(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::end(), llvm::ValueSymbolTable::end(), llvm::Value::getContext(), llvm::MDNode::getFunction(), llvm::Value::getName(), llvm::MDNode::getNumOperands(), llvm::NamedMDNode::getNumOperands(), llvm::AttributeSet::getNumSlots(), llvm::MDNode::getOperand(), llvm::NamedMDNode::getOperand(), llvm::AttributeSet::getSlotAttributes(), llvm::Value::getType(), getTypeID(), llvm::Type::getVoidTy(), llvm::Value::hasName(), i, I, llvm::AttributeSet::isEmpty(), llvm::MDNode::isFunctionLocal(), isIntOrIntVectorValue(), llvm::Type::isVoidTy(), M, N, llvm::Module::named_metadata_begin(), llvm::Module::named_metadata_end(), P, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::size(), llvm::ValueMap< KeyT, ValueT, Config >::size(), llvm::Type::subtype_begin(), llvm::Type::subtype_end(), llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by dump().
void ValueEnumerator::purgeFunction ()
Remove purged values from the ValueMap.
Definition at line 512 of file ValueEnumerator.cpp.
References llvm::ValueMap< KeyT, ValueT, Config >::erase(), and i.
Referenced by getAttributeGroups(), WriteFunction(), and WriteFunctionUseList().
void ValueEnumerator::setInstructionID (const Instruction * I)
Definition at line 123 of file ValueEnumerator.cpp.
References I.
Referenced by getTypeID(), and WriteInstruction().
The documentation for this class was generated from the following files:
ValueEnumerator.h
ValueEnumerator.cpp