LLVM: llvm::sys::ThreadLocalImpl Class Reference
LLVM API Documentation
llvm::sys::ThreadLocalImpl Class Reference
#include <ThreadLocal.h>
Public Member Functions
ThreadLocalImpl ()
virtual ~ThreadLocalImpl ()
void setInstance (const void *d)
const void * getInstance ()
void removeInstance ()
Detailed Description
Definition at line 25 of file ThreadLocal.h.
Constructor & Destructor Documentation
llvm::ThreadLocalImpl::ThreadLocalImpl ()
Definition at line 52 of file ThreadLocal.cpp.
References data.
llvm::ThreadLocalImpl::~ThreadLocalImpl () virtual
Definition at line 60 of file ThreadLocal.cpp.
References data.
Member Function Documentation
const void * llvm::ThreadLocalImpl::getInstance ()
Definition at line 74 of file ThreadLocal.cpp.
References data.
Referenced by llvm::sys::ThreadLocal< T >::get().
void llvm::ThreadLocalImpl::removeInstance ()
Definition at line 79 of file ThreadLocal.cpp.
References setInstance().
Referenced by llvm::sys::ThreadLocal< T >::erase().
void llvm::ThreadLocalImpl::setInstance (const void * d)
Definition at line 67 of file ThreadLocal.cpp.
References data.
Referenced by removeInstance(), and llvm::sys::ThreadLocal< T >::set().
Member Data Documentation
ThreadLocalDataTy llvm::sys::ThreadLocalImpl::align_data
Definition at line 33 of file ThreadLocal.h.
char llvm::sys::ThreadLocalImpl::data[sizeof(ThreadLocalDataTy)]
Definition at line 32 of file ThreadLocal.h.
Referenced by getInstance(), setInstance(), ThreadLocalImpl(), and ~ThreadLocalImpl().
The documentation for this class was generated from the following files:
ThreadLocal.h
ThreadLocal.cpp