LLVM: llvm::User Class Reference
LLVM API Documentation
llvm::User Class Reference
#include <User.h>
Classes
class value_op_iterator
Public Types
typedef Use * op_iterator
typedef const Use * const_op_iterator
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal, BasicBlockVal, FunctionVal, GlobalAliasVal,
GlobalVariableVal, UndefValueVal, BlockAddressVal, ConstantExprVal,
ConstantAggregateZeroVal, ConstantDataArrayVal, ConstantDataVectorVal, ConstantIntVal,
ConstantFPVal, ConstantArrayVal, ConstantStructVal, ConstantVectorVal,
ConstantPointerNullVal, MDNodeVal, MDStringVal, InlineAsmVal,
PseudoSourceValueVal, FixedStackPseudoSourceValueVal, InstructionVal, ConstantFirstVal = FunctionVal,
ConstantLastVal = ConstantPointerNullVal
}
typedef value_use_iterator< User > use_iterator
typedef value_use_iterator< const User > const_use_iterator
Public Member Functions
~User ()
void operator delete (void *Usr)
operator delete - free memory allocated for User and Use objects
void operator delete (void *, unsigned)
placement delete - required by std, but never called.
void operator delete (void *, unsigned, bool)
placement delete - required by std, but never called.
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
void dropAllReferences ()
void replaceUsesOfWith (Value *From, Value *To)
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
dump - Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O, AssemblyAnnotationWriter *AAW=0) const
Type * getType () const
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
void setName (const Twine &Name)
void takeName (Value *V)
void replaceAllUsesWith (Value *V)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
User * use_back ()
const User * use_back () const
bool hasOneUse () const
bool hasNUses (unsigned N) const
bool hasNUsesOrMore (unsigned N) const
bool isUsedInBasicBlock (const BasicBlock *BB) const
unsigned getNumUses () const
void addUse (Use &U)
unsigned getValueID () const
unsigned getRawSubclassOptionalData () const
void clearSubclassOptionalData ()
bool hasSameSubclassOptionalData (const Value *V) const
void intersectOptionalDataWith (const Value *V)
bool hasValueHandle () const
Value * stripPointerCasts ()
Strips off any unneeded pointer casts, all-zero GEPs and aliases from the specified value, returning the original uncasted value.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strips off any unneeded pointer casts and all-zero GEPs from the specified value, returning the original uncasted value.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strips off unneeded pointer casts and all-constant GEPs from the specified value, returning the original pointer value.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Strips like stripInBoundsConstantOffsets but also accumulates the constant offset stripped.
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strips off unneeded pointer casts and any in-bounds offsets from the specified value, returning the original pointer value.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer () const
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Static Public Member Functions
static bool classof (const Value *V)
Protected Member Functions
void * operator new (size_t s, unsigned Us)
User (Type *ty, unsigned vty, Use *OpList, unsigned NumOps)
Use * allocHungoffUses (unsigned) const
void dropHungoffUses ()
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
virtual void printCustom (raw_ostream &O) const
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Static Protected Member Functions
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes
Use * OperandList
unsigned NumOperands
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Friends
template<unsigned >
struct HungoffOperandTraits
Additional Inherited Members
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
Detailed Description
Definition at line 33 of file User.h.
Member Typedef Documentation
typedef const Use* llvm::User::const_op_iterator
Definition at line 114 of file User.h.
typedef Use* llvm::User::op_iterator
Definition at line 113 of file User.h.
Constructor & Destructor Documentation
llvm::User::User (Type * ty, unsigned vty, Use * OpList, unsigned NumOps) inline protected
Definition at line 52 of file User.h.
References allocHungoffUses().
llvm::User::~User () inline
Definition at line 62 of file User.h.
References llvm::Use::zap().
Member Function Documentation
Use * llvm::User::allocHungoffUses (unsigned N) const protected
Definition at line 45 of file User.cpp.
References llvm::Use::initTags(), N, and size.
Referenced by llvm::CmpInst::isFalseWhenEqual(), llvm::SwitchInst::removeCase(), and User().
static bool llvm::User::classof (const Value * V) inline static
Definition at line 179 of file User.h.
void llvm::User::dropAllReferences () inline
Definition at line 168 of file User.h.
References i, op_begin(), op_end(), and replaceUsesOfWith().
Referenced by llvm::expandDivision(), llvm::expandDivisionUpTo32Bits(), llvm::expandRemainder(), and llvm::expandRemainderUpTo32Bits().
void llvm::User::dropHungoffUses () inline protected
Definition at line 55 of file User.h.
References llvm::Use::zap().
Referenced by llvm::IndirectBrInst::~IndirectBrInst(), and llvm::SwitchInst::~SwitchInst().
unsigned llvm::User::getNumOperands () const inline
Definition at line 108 of file User.h.
References NumOperands.
Referenced by AddPHINodeEntriesForMappedBlock(), llvm::MachineModuleInfo::AnalyzeModule(), areAllUsesIn(), llvm::SelectInst::areInvalidOperands(), llvm::PHINode::block_end(), CanEvaluateShuffled(), canTrapImpl(), CanTRE(), llvm::GetElementPtrInst::clone_impl(), llvm::CallInst::clone_impl(), llvm::ReturnInst::clone_impl(), llvm::BranchInst::clone_impl(), llvm::InvokeInst::clone_impl(), llvm::collectUsedGlobalVariables(), CommitValueTo(), llvm::ComputeMaskedBits(), llvm::constant_iterator::constant_iterator(), ConstantFold(), llvm::ConstantFoldLoadThroughGEPConstantExpr(), ConvertAtomicSynchScope(), llvm::CallInst::CreateFree(), llvm::createLoopVectorizePass(), llvm::createNVVMReflectPass(), createPrivateNonConstGlobalForString(), DeleteDeadInstruction(), deleteDeadInstruction(), emitGlobalConstantArray(), emitGlobalConstantStruct(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), llvm::InstCombiner::EraseInstFromFunction(), EvaluateConstantChrecAtConstant(), EvaluateExpression(), EvaluateGEPOffsetExpression(), evaluateICmpRelation(), EvaluateStoreInto(), ExposePointerBase(), llvm::FenceInst::FenceInst(), FindUsedValues(), findUsedValues(), FirstNonDbg(), llvm::InstCombiner::FoldCmpLoadFromIndexedGlobal(), llvm::InstCombiner::FoldGEPICmp(), FoldOperationIntoSelectOperand(), llvm::InstCombiner::FoldSelectOpOp(), llvm::Constant::getAggregateElement(), llvm::ConstantExpr::getAsInstruction(), llvm::PHINode::getBasicBlockIndex(), getCommonReturnValue(), getComparePred(), getGEPInductionOperand(), llvm::DenseMapInfo< ComparableFunction >::getHashValue(), llvm::SCEVExpander::getIVIncOperand(), llvm::InvokeInst::getLandingPadInst(), getLoopPhiForCounter(), getMergedGlobalExpr(), getNoopInput(), llvm::CallInst::getNumArgOperands(), llvm::InvokeInst::getNumArgOperands(), llvm::SwitchInst::getNumCases(), llvm::LandingPadInst::getNumClauses(), llvm::IndirectBrInst::getNumDestinations(), llvm::PHINode::getNumIncomingValues(), llvm::GEPOperator::getNumIndices(), llvm::GetElementPtrInst::getNumIndices(), llvm::SwitchInst::getNumSuccessors(), llvm::IndirectBrInst::getNumSuccessors(), GetOffsetFromIndex(), getOpenCLAlignment(), llvm::TargetTransformInfo::getReductionCost(), llvm::Constant::getRelocationInfo(), llvm::ReturnInst::getReturnValue(), llvm::ConstantVector::getSplatValue(), llvm::DenseMapInfo< CallValue >::getTombstoneKey(), llvm::ConstantKeyData< ConstantExpr >::getValType(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::ConstantExpr::getWithOperandReplaced(), llvm::ConstantExpr::getWithOperands(), llvm::GetElementPtrInst::hasAllConstantIndices(), llvm::GetElementPtrInst::hasAllZeroIndices(), llvm::PHINode::hasConstantValue(), llvm::GEPOperator::hasIndices(), llvm::GetElementPtrInst::hasIndices(), llvm::Loop::hasLoopInvariantOperands(), INITIALIZE_PASS(), llvm::BranchInst::isConditional(), isContiguous(), llvm::DenseMapInfo< Expression >::isEqual(), llvm::CmpInst::isFalseWhenEqual(), llvm::Instruction::isIdenticalToWhenDefined(), isLikelyComplexAddressComputation(), llvm::SCEVUnknown::isOffsetOf(), isOnlyReachableViaThisEdge(), IsPointerOffset(), isRunOfOnes(), IsSafeComputationToRemove(), isSafeSROAElementUse(), llvm::isSafeToSpeculativelyExecute(), llvm::Instruction::isSameOperationAs(), isSimpleEnoughValueToCommitHelper(), isSimpleLoadStore(), llvm::Constant::isThreadDependent(), llvm::BranchInst::isUnconditional(), IsUserOfGlobalSafeForSRA(), llvm::Loop::makeLoopInvariant(), llvm::MapValue(), MarkIndicesSafe(), mergeEmptyReturnBlocks(), llvm::HungoffOperandTraits< 2 >::op_end(), llvm::OptionalOperandTraits< GlobalVariable >::operands(), llvm::VariadicOperandTraits< CallInst, 1 >::operands(), llvm::HungoffOperandTraits< 2 >::operands(), llvm::constant_iterator::operator++(), OptimizeCmpExpression(), ParseGlobalCtors(), llvm::AssemblyWriter::printInstruction(), promoteSingleBlockAlloca(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), RemapInstruction(), llvm::SwitchInst::removeCase(), RemoveDeadConstant(), llvm::IndirectBrInst::removeDestination(), RemoveInstInputs(), replaceUsesOfWith(), ReplaceUsesOfWith(), llvm::Constant::replaceUsesOfWithOnConstant(), llvm::GlobalVariable::replaceUsesOfWithOnConstant(), llvm::ConstantArray::replaceUsesOfWithOnConstant(), llvm::ConstantStruct::replaceUsesOfWithOnConstant(), llvm::ConstantVector::replaceUsesOfWithOnConstant(), llvm::ConstantExpr::replaceUsesOfWithOnConstant(), llvm::returnTypeIsEligibleForTailCall(), llvm::ExecutionEngine::runStaticConstructorsDestructors(), SimplifyWithOpReplaced(), SinkThenElseCodeToEnd(), SRAGlobal(), llvm::UnreachableInst::UnreachableInst(), ValueIsOnlyUsedLocallyOrStoredToOneGlobal(), VerifySubExpr(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::Interpreter::visitReturnInst(), WriteConstants(), WriteInstruction(), and llvm::CallInst::~CallInst().
Value* llvm::User::getOperand (unsigned i) const inline
Definition at line 88 of file User.h.
References i.
Referenced by llvm::AliasSetTracker::add(), llvm::AddCatchInfo(), llvm::MachineBasicBlock::addLiveIn(), AddPHINodeEntriesForMappedBlock(), AddReachableCodeToWorklist(), AddressIsTaken(), llvm::MachineModuleInfo::AnalyzeModule(), areAllUsesIn(), llvm::AtomicCmpXchgInst::AtomicCmpXchgInst(), BreakUpSubtract(), buildMultiplyTree(), CanEvaluateSExtd(), CanEvaluateShifted(), CanEvaluateShuffled(), CanEvaluateTruncated(), CanEvaluateZExtd(), llvm::CannotBeNegativeZero(), CanPHITrans(), CanTRE(), CheapToScalarize(), CleanupPointerRootUsers(), ClearSubclassDataAfterReassociation(), llvm::AllocaInst::clone_impl(), llvm::LoadInst::clone_impl(), llvm::StoreInst::clone_impl(), llvm::AtomicCmpXchgInst::clone_impl(), llvm::AtomicRMWInst::clone_impl(), llvm::SelectInst::clone_impl(), llvm::VAArgInst::clone_impl(), llvm::ExtractElementInst::clone_impl(), llvm::InsertElementInst::clone_impl(), llvm::ShuffleVectorInst::clone_impl(), llvm::TruncInst::clone_impl(), llvm::ZExtInst::clone_impl(), llvm::SExtInst::clone_impl(), llvm::FPTruncInst::clone_impl(), llvm::FPExtInst::clone_impl(), llvm::UIToFPInst::clone_impl(), llvm::SIToFPInst::clone_impl(), llvm::FPToUIInst::clone_impl(), llvm::FPToSIInst::clone_impl(), llvm::IntToPtrInst::clone_impl(), llvm::PtrToIntInst::clone_impl(), llvm::BitCastInst::clone_impl(), llvm::AddrSpaceCastInst::clone_impl(), CollectBSwapParts(), CollectInsertionElements(), CollectShuffleElements(), CollectSingleShuffleElements(), llvm::collectUsedGlobalVariables(), CommitValueTo(), llvm::InstCombiner::commonCastTransforms(), llvm::InstCombiner::commonIDivTransforms(), llvm::InstCombiner::commonIRemTransforms(), llvm::InstCombiner::commonPointerCastTransforms(), llvm::InstCombiner::commonShiftTransforms(), computeBytesPoppedByCallee(), llvm::ComputeMaskedBits(), llvm::ComputeMultiple(), llvm::ComputeNumSignBits(), ConstantFold(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCompareInstOperands(), llvm::ConstantFoldCompareInstruction(), ConstantFoldGetElementPtrImpl(), llvm::ConstantFoldInstOperands(), llvm::ConstantFoldLoadFromConstPtr(), ConstantFoldLoadInst(), llvm::ConstantFoldLoadThroughGEPConstantExpr(), llvm::ConstantFoldSelectInstruction(), ConvertAtomicSynchScope(), llvm::ConvertDebugDeclareToDebugValue(), ConvertShiftToMul(), ConvertToSInt(), llvm::createCorrelatedValuePropagationPass(), llvm::createDwarfEHPass(), llvm::createEarlyCSEPass(), llvm::createLICMPass(), llvm::createLoopVectorizePass(), llvm::createNVVMReflectPass(), createPrivateNonConstGlobalForString(), createReplacementInstr(), cse(), decomposeBitTestICmp(), DecomposeGEPExpression(), DecomposeSimpleLinearExpr(), DeleteDeadInstruction(), deleteDeadInstruction(), deleteIfDeadInstruction(), DemandedBitsLHSMask(), detectLog2OfHalf(), llvm::InstCombiner::DoOneIteration(), dyn_castFoldableMul(), emitGlobalConstantArray(), emitGlobalConstantStruct(), emitGlobalConstantVector(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), EvaluateConstantChrecAtConstant(), EvaluateExpression(), EvaluateGEPOffsetExpression(), evaluateICmpRelation(), EvaluateStoreInto(), llvm::expandDivision(), llvm::expandDivisionUpTo32Bits(), llvm::expandRemainder(), llvm::expandRemainderUpTo32Bits(), ExposePointerBase(), ExtractConstantBytes(), ExtractEquivalentCondition(), FactorizeBinOp(), llvm::FastISel::FastEmitBranch(), llvm::FCmpInst::FCmpInst(), FindInitTrampoline(), FindInitTrampolineFromAlloca(), llvm::SelectionDAGBuilder::FindMergedConditions(), FindMostPopularDest(), FindPredecessorAutoreleaseWithSafePath(), FindScalarElement(), FindSingleUseMultiplyFactors(), FindUnconditionalPreds(), FindUsedValues(), findUsedValues(), FirstNonDbg(), llvm::InstCombiner::FoldAndOfFCmps(), llvm::InstCombiner::FoldAndOfICmps(), llvm::FoldBranchToCommonDest(), llvm::InstCombiner::FoldCmpLoadFromIndexedGlobal(), foldConstantCastPair(), llvm::InstCombiner::FoldFCmp_IntToFP_Cst(), llvm::InstCombiner::foldFMulConst(), llvm::InstCombiner::FoldGEPICmp(), llvm::InstCombiner::FoldICmpDivCst(), llvm::InstCombiner::FoldICmpShrCst(), foldLogOpOfMaskedICmpsHelper(), FoldOperationIntoSelectOperand(), llvm::InstCombiner::FoldOrOfFCmps(), llvm::InstCombiner::FoldOrOfICmps(), foldSelectICmpAnd(), foldSelectICmpAndOr(), foldSelectInst(), llvm::InstCombiner::FoldSelectOpOp(), llvm::InstCombiner::FoldShiftByConstant(), foldUDivShl(), llvm::ScalarEvolution::forgetValue(), GatherConstantCompares(), llvm::gep_type_begin(), llvm::IndirectBrInst::getAddress(), llvm::ExtractValueInst::getAggregateOperand(), llvm::InsertValueInst::getAggregateOperand(), llvm::GlobalAlias::getAliasedGlobal(), llvm::GlobalAlias::getAliasee(), llvm::CallInst::getArgOperand(), llvm::InvokeInst::getArgOperand(), llvm::AllocaInst::getArraySize(), getCommonReturnValue(), llvm::AtomicCmpXchgInst::getCompareOperand(), getComparePred(), llvm::SwitchInst::getCondition(), llvm::ExecutionEngine::getConstantValue(), llvm::SwitchInst::getDefaultDest(), getEdgeValueLocal(), getFCmpValue(), llvm::BinaryOperator::getFNegArgument(), getGEPInductionOperand(), llvm::DenseMapInfo< ComparableFunction >::getHashValue(), llvm::PHINode::getIncomingValue(), llvm::InsertValueInst::getInsertedValueOperand(), llvm::SCEVExpander::getIVIncOperand(), getKnownConstant(), getLoopPhiForCounter(), llvm::ShuffleVectorInst::getMask(), getMaxWeightFor(), getMergedGlobalExpr(), llvm::BinaryOperator::getNegArgument(), llvm::AtomicCmpXchgInst::getNewValOperand(), getNoopInput(), llvm::BinaryOperator::getNotArgument(), GetOffsetFromIndex(), getOpenCLAlignment(), llvm::LandingPadInst::getPersonalityFn(), llvm::LoadInst::getPointerOperand(), llvm::StoreInst::getPointerOperand(), llvm::GEPOperator::getPointerOperand(), llvm::AtomicCmpXchgInst::getPointerOperand(), llvm::AtomicRMWInst::getPointerOperand(), llvm::GetElementPtrInst::getPointerOperand(), llvm::VAArgInst::getPointerOperand(), llvm::PtrToIntInst::getPointerOperand(), llvm::TargetTransformInfo::getReductionCost(), GetRegistersForValue(), llvm::Constant::getRelocationInfo(), llvm::ReturnInst::getReturnValue(), GetShiftedValue(), getShuffleAndOtherOprd(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::ScalarEvolution::getSignedRange(), llvm::ConstantVector::getSplatValue(), llvm::CastInst::getSrcTy(), llvm::SwitchInst::getSuccessor(), llvm::IndirectBrInst::getSuccessor(), llvm::DenseMapInfo< SimpleValue >::getTombstoneKey(), llvm::DenseMapInfo< CallValue >::getTombstoneKey(), getTruncatedArgReg(), llvm::AtomicRMWInst::getValOperand(), llvm::ConstantKeyData< ConstantExpr >::getValType(), llvm::DbgValueInst::getValue(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::StoreInst::getValueOperand(), llvm::ConstantExpr::getWithOperandReplaced(), llvm::ConstantExpr::getWithOperands(), hasAddressTakenAndUsed(), llvm::GetElementPtrInst::hasAllConstantIndices(), llvm::GetElementPtrInst::hasAllZeroIndices(), llvm::Loop::hasLoopInvariantOperands(), hasOutsideLoopUser(), llvm::SCEVExpander::hoistIVInc(), llvm::BinaryOperator::init(), INITIALIZE_PASS(), llvm::InlineFunction(), insertFastDiv(), insertVector(), InstCombineLoadCast(), InstCombineStoreToCast(), InstructionDereferencesPointer(), llvm::isAllocaPromotable(), isAllocSiteRemovable(), isAlwaysFoldable(), llvm::AllocaInst::isArrayAllocation(), isCompatibleAggregate(), IsConstantOffsetFromGlobal(), isContiguous(), isEliminableCastPair(), isFMulOrFDivWithConstant(), isFormingBranchFromSelectProfitable(), isHighCostExpansion(), llvm::Instruction::isIdenticalToWhenDefined(), llvm::CastInst::isIntegerCast(), isInterestingMemoryAccess(), isLikelyComplexAddressComputation(), llvm::CastInst::isLosslessCast(), IsNonLocalValue(), llvm::CastInst::isNoopCast(), llvm::SCEVUnknown::isOffsetOf(), isOnlyReachableViaThisEdge(), IsPointerOffset(), isProfitableToFoldUnconditional(), isRunOfOnes(), isSafeAndProfitableToSinkLoad(), IsSafeComputationToRemove(), isSafeSROAElementUse(), isSafeToEliminateVarargsCast(), llvm::isSafeToSpeculativelyExecute(), isSameCompare(), llvm::Instruction::isSameOperationAs(), isSequentialInRange(), isSimpleEnoughValueToCommitHelper(), isSimpleLoadStore(), llvm::AllocaInst::isStaticAlloca(), llvm::Constant::isThreadDependent(), IsUserOfGlobalSafeForSRA(), isZero(), LdStHasDebugValue(), llvm::FastISel::leaveLocalValueArea(), LinearizeExprTree(), llvm::SelectionDAGBuilder::LowerCallOperands(), nvptx::LowerConstant(), lowerConstant(), llvm::IntrinsicLowering::LowerIntrinsicCall(), LowerNegateToMultiply(), llvm::Loop::makeLoopInvariant(), LTOModule::makeLTOModule(), llvm::MapValue(), MarkIndicesSafe(), llvm::PatternMatch::BinaryOp_match< LHS_t, RHS_t, Opcode >::match(), llvm::PatternMatch::BinOp2_match< LHS_t, RHS_t, Opc1, Opc2 >::match(), matchPairwiseReduction(), matchPairwiseReductionAtLevel(), MatchSelectPattern(), matchVectorSplittingReduction(), mergeEmptyReturnBlocks(), needsLFTR(), NegateValue(), llvm::constant_iterator::operator*(), llvm::operator<<(), OptimizeAwayTrappingUsesOfLoads(), OptimizeCmpExpression(), OptimizeIntegerToVectorInsertions(), OptimizeIntToFloatBitCast(), OptimizeNoopCopyExpression(), ParseGlobalCtors(), PerformHeapAllocSRoA(), llvm::PHITransAddr::PHITranslateWithInsertion(), llvm::PointerMayBeCaptured(), llvm::AssemblyWriter::printInstruction(), PrintOps(), ProcessUAddIdiom(), ProcessUGT_ADDCST_ADD(), PushDefUseChildren(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), RemapInstruction(), llvm::AliasSetTracker::remove(), RemoveDeadConstant(), RemoveInstInputs(), RemoveNestAttribute(), replaceUsesOfWith(), ReplaceUsesOfWith(), llvm::GlobalVariable::replaceUsesOfWithOnConstant(), llvm::ConstantArray::replaceUsesOfWithOnConstant(), llvm::ConstantStruct::replaceUsesOfWithOnConstant(), llvm::ConstantVector::replaceUsesOfWithOnConstant(), llvm::ConstantExpr::replaceUsesOfWithOnConstant(), llvm::returnTypeIsEligibleForTailCall(), reuseOrInsertFastDiv(), rewriteSingleStoreAlloca(), RightDistributesOverLeft(), llvm::NVPTXLowerAggrCopies::runOnFunction(), llvm::UnifyFunctionExitNodes::runOnFunction(), llvm::StackProtector::runOnFunction(), llvm::ExecutionEngine::runStaticConstructorsDestructors(), llvm::FastISel::SelectOperator(), llvm::LoadInst::setAlignment(), llvm::StoreInst::setAlignment(), ShouldBreakUpSubtract(), ShrinkDemandedConstant(), SimplifyAssociativeBinOp(), llvm::InstCombiner::SimplifyDivRemOfSelect(), SimplifyICmpInst(), llvm::SimplifyInstruction(), SimplifyWithOpReplaced(), SinkThenElseCodeToEnd(), AllocaSlices::SliceBuilder::SliceBuilder(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), SRAGlobal(), swapMayExposeCSEOpportunities(), SymbolicallyEvaluateGEP(), ThreadBinOpOverSelect(), TryToShrinkGlobalToBoolean(), TryToSimplifyUncondBranchWithICmpInIt(), llvm::SelectionDAGBuilder::UpdateSplitBlock(), ValueIsOnlyUsedLocallyOrStoredToOneGlobal(), VerifySubExpr(), llvm::InstCombiner::visitAdd(), llvm::Interpreter::visitAllocaInst(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitAShr(), llvm::Interpreter::visitAShr(), llvm::Interpreter::visitBinaryOperator(), llvm::InstCombiner::visitBitCast(), llvm::Interpreter::visitBitCastInst(), llvm::Interpreter::visitExtractElementInst(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitFAdd(), llvm::Interpreter::visitFCmpInst(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitFDiv(), llvm::InstCombiner::visitFMul(), llvm::Interpreter::visitFPExtInst(), llvm::InstCombiner::visitFPToSI(), llvm::Interpreter::visitFPToSIInst(), llvm::InstCombiner::visitFPToUI(), llvm::Interpreter::visitFPToUIInst(), llvm::InstCombiner::visitFPTrunc(), llvm::Interpreter::visitFPTruncInst(), llvm::InstCombiner::visitFRem(), llvm::InstCombiner::visitFSub(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::Interpreter::visitICmpInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithCastAndCast(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::Interpreter::visitInsertElementInst(), llvm::InstCombiner::visitInsertElementInst(), llvm::Interpreter::visitInsertValueInst(), llvm::InstCombiner::visitIntToPtr(), llvm::Interpreter::visitIntToPtrInst(), llvm::InstCombiner::visitLandingPadInst(), llvm::InstCombiner::visitLoadInst(), llvm::InstCombiner::visitLShr(), llvm::Interpreter::visitLShr(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitPtrToInt(), llvm::Interpreter::visitPtrToIntInst(), llvm::InstCombiner::visitSDiv(), llvm::Interpreter::visitSelectInst(), llvm::InstCombiner::visitSelectInst(), llvm::InstCombiner::visitSelectInstWithICmp(), llvm::InstCombiner::visitSExt(), llvm::Interpreter::visitSExtInst(), llvm::InstCombiner::visitShl(), llvm::Interpreter::visitShl(), llvm::Interpreter::visitShuffleVectorInst(), llvm::InstCombiner::visitShuffleVectorInst(), llvm::Interpreter::visitSIToFPInst(), llvm::InstCombiner::visitSRem(), llvm::Interpreter::visitStoreInst(), llvm::InstCombiner::visitStoreInst(), llvm::InstCombiner::visitSub(), llvm::InstCombiner::visitSwitchInst(), llvm::InstCombiner::visitTrunc(), llvm::Interpreter::visitTruncInst(), llvm::InstCombiner::visitUDiv(), llvm::Interpreter::visitUIToFPInst(), llvm::InstCombiner::visitURem(), llvm::Interpreter::visitVAArgInst(), llvm::InstCombiner::visitXor(), llvm::InstCombiner::visitZExt(), llvm::Interpreter::visitZExtInst(), WriteConstants(), WriteInstruction(), and X86ChooseCmpImmediateOpcode().
const Use& llvm::User::getOperandUse (unsigned i) const inline
Definition at line 99 of file User.h.
References i.
Referenced by ConstructSSAForLoadSet(), isContiguous(), isExitBlock(), isOnlyReachableViaThisEdge(), ShrinkDemandedConstant(), and llvm::InstCombiner::visitICmpInst().
Use& llvm::User::getOperandUse (unsigned i) inline
Definition at line 103 of file User.h.
References i.
template<int Idx> Use& llvm::User::Op () inline protected
Definition at line 81 of file User.h.
Referenced by canTrapImpl(), llvm::CallInst::getCalledFunction(), llvm::InvokeInst::getCalledFunction(), llvm::CallInst::getCalledValue(), llvm::InvokeInst::getCalledValue(), llvm::BranchInst::getCondition(), llvm::InvokeInst::getLandingPadInst(), llvm::InvokeInst::getNormalDest(), llvm::ConstantExpr::getOpcode(), llvm::BranchInst::getSuccessor(), llvm::InvokeInst::getUnwindDest(), llvm::ConstantExpr::getWithOperandReplaced(), llvm::CallInst::isInlineAsm(), llvm::BinaryOperator::operator new(), llvm::CmpInst::operator new(), llvm::ConstantExpr::replaceUsesOfWithOnConstant(), llvm::CallInst::setCalledFunction(), llvm::InvokeInst::setCalledFunction(), llvm::BranchInst::setCondition(), llvm::InvokeInst::setNormalDest(), llvm::BranchInst::setSuccessor(), llvm::InvokeInst::setSuccessor(), llvm::InvokeInst::setUnwindDest(), llvm::BranchInst::swapSuccessors(), llvm::UnreachableInst::UnreachableInst(), and llvm::ReturnInst::~ReturnInst().
template<int Idx> const Use& llvm::User::Op () const inline protected
Definition at line 84 of file User.h.
op_iterator llvm::User::op_begin () inline
Definition at line 116 of file User.h.
References OperandList.
Referenced by llvm::AddLandingPadInfo(), AddReachableCodeToWorklist(), areAllUsesIn(), llvm::SelectInst::areInvalidOperands(), llvm::PHINode::block_begin(), buildMultiplyTree(), canFoldIVIncExpr(), llvm::objcarc::CanUse(), changeToCall(), llvm::TypeFinder::clear(), llvm::ConstantArray::ConstantArray(), ConstantFoldConstantExpressionImpl(), llvm::ConstantFoldInstruction(), llvm::ConstantStruct::ConstantStruct(), llvm::ConstantVector::ConstantVector(), llvm::CallInst::CreateFree(), createPrivateNonConstGlobalForString(), createReplacementInstr(), DecomposeGEPExpression(), DeleteTriviallyDeadInstructions(), DominatesMergePoint(), dropAllReferences(), llvm::EliminateDuplicatePHINodes(), llvm::EmitGEPOffset(), llvm::InstCombiner::EraseInstFromFunction(), ExposePointerBase(), llvm::FenceInst::FenceInst(), llvm::FoldBranchToCommonDest(), FoldCondBranchOnPHI(), llvm::FoldReturnIntoUncondBranch(), llvm::gep_type_begin(), llvm::ConstantExpr::getAsInstruction(), getComparePred(), getConstantEvolvingPHIOperands(), llvm::PHINode::getIncomingBlock(), llvm::SCEVExpander::getIVIncOperand(), getNoopInput(), hasConcreteDefImpl(), hasMultipleUsesOf(), hasOutsideLoopUser(), hasUsesOutsideLoop(), llvm::GEPOperator::idx_begin(), llvm::GetElementPtrInst::idx_begin(), INITIALIZE_PASS(), insertVector(), isCompatibleAggregate(), llvm::DenseMapInfo< Expression >::isEqual(), llvm::ConstantExpr::isGEPWithNoNotionalOverIndexing(), isInterestingPointer(), isSequentialInRange(), llvm::FastISel::leaveLocalValueArea(), MarkIndicesSafe(), ParseGlobalCtors(), PushDefUseChildren(), llvm::RemapInstruction(), removeFinishedSplitUses(), RemoveNestAttribute(), llvm::BitcodeReaderValueList::ResolveConstantForwardRefs(), llvm::TypeFinder::run(), llvm::FindUsedTypes::runOnModule(), SimplifyBranchOnICmpChain(), llvm::SimplifyInstruction(), SpeculativelyExecuteBB(), tryToMakeAllocaBePromotable(), value_op_begin(), llvm::InstCombiner::visitGetElementPtrInst(), and llvm::CallInst::~CallInst().
const_op_iterator llvm::User::op_begin () const inline
Definition at line 117 of file User.h.
References OperandList.
op_iterator llvm::User::op_end () inline
Definition at line 118 of file User.h.
References NumOperands.
Referenced by llvm::AddLandingPadInfo(), AddReachableCodeToWorklist(), areAllUsesIn(), llvm::SelectInst::areInvalidOperands(), buildMultiplyTree(), canFoldIVIncExpr(), llvm::objcarc::CanUse(), changeToCall(), llvm::TypeFinder::clear(), ConstantFoldConstantExpressionImpl(), llvm::ConstantFoldInstruction(), llvm::CallInst::CreateFree(), createPrivateNonConstGlobalForString(), createReplacementInstr(), DecomposeGEPExpression(), DeleteTriviallyDeadInstructions(), DominatesMergePoint(), dropAllReferences(), llvm::EliminateDuplicatePHINodes(), llvm::EmitGEPOffset(), llvm::InstCombiner::EraseInstFromFunction(), ExposePointerBase(), llvm::FenceInst::FenceInst(), llvm::FoldBranchToCommonDest(), FoldCondBranchOnPHI(), llvm::FoldReturnIntoUncondBranch(), llvm::gep_type_end(), llvm::ConstantExpr::getAsInstruction(), getComparePred(), getConstantEvolvingPHIOperands(), llvm::SCEVExpander::getIVIncOperand(), getNoopInput(), hasConcreteDefImpl(), hasMultipleUsesOf(), hasOutsideLoopUser(), hasUsesOutsideLoop(), llvm::GEPOperator::idx_end(), llvm::GetElementPtrInst::idx_end(), INITIALIZE_PASS(), insertVector(), isCompatibleAggregate(), llvm::DenseMapInfo< Expression >::isEqual(), isInterestingPointer(), isSequentialInRange(), llvm::FastISel::leaveLocalValueArea(), MarkIndicesSafe(), ParseGlobalCtors(), PushDefUseChildren(), llvm::RemapInstruction(), removeFinishedSplitUses(), RemoveNestAttribute(), llvm::BitcodeReaderValueList::ResolveConstantForwardRefs(), llvm::TypeFinder::run(), llvm::FindUsedTypes::runOnModule(), SimplifyBranchOnICmpChain(), llvm::SimplifyInstruction(), SpeculativelyExecuteBB(), tryToMakeAllocaBePromotable(), value_op_end(), llvm::InstCombiner::visitGetElementPtrInst(), and llvm::CallInst::~CallInst().
const_op_iterator llvm::User::op_end () const inline
Definition at line 119 of file User.h.
References NumOperands.
void llvm::User::operator delete (void * Usr)
operator delete - free memory allocated for User and Use objects
Definition at line 74 of file User.cpp.
References NumOperands.
void llvm::User::operator delete (void * , unsigned) inline
placement delete - required by std, but never called.
Definition at line 68 of file User.h.
References llvm_unreachable.
void llvm::User::operator delete (void * , unsigned , bool) inline
placement delete - required by std, but never called.
Definition at line 72 of file User.h.
References llvm_unreachable.
void * llvm::User::operator new (size_t s, unsigned Us) protected
Definition at line 59 of file User.cpp.
References llvm::Use::initTags(), NumOperands, and OperandList.
template<int Idx, typename U > static Use& llvm::User::OpFrom (const U * that) inline static protected
Definition at line 76 of file User.h.
void llvm::User::replaceUsesOfWith (Value * From, Value * To)
replaceUsesOfWith - Replaces all references to the "From" definition with references to the "To" definition.
Definition at line 26 of file User.cpp.
References getNumOperands(), getOperand(), i, and setOperand().
Referenced by canFoldIVIncExpr(), llvm::createCorrelatedValuePropagationPass(), llvm::createLoopDeletionPass(), llvm::DemoteRegToStack(), dropAllReferences(), llvm::CodeExtractor::findInputsOutputs(), FindPhiPredForUseInBlock(), llvm::FoldBranchToCommonDest(), INITIALIZE_PASS(), isAlwaysFoldable(), IsNonLocalValue(), isZeroLengthArray(), OptimizeGlobalAddressOfMalloc(), ReplaceUsesOfMallocWithGlobal(), and ReplaceUsesOfWith().
void llvm::User::setOperand (unsigned i, Value * Val) inline
Definition at line 92 of file User.h.
References i.
Referenced by AddPHINodeEntriesForMappedBlock(), BreakUpSubtract(), buildMultiplyTree(), ClearSubclassDataAfterReassociation(), llvm::InstCombiner::commonIDivTransforms(), llvm::InstCombiner::commonIRemTransforms(), llvm::InstCombiner::commonPointerCastTransforms(), llvm::InstCombiner::commonShiftTransforms(), ConvertShiftToMul(), llvm::createLoopVectorizePass(), DeleteDeadInstruction(), deleteDeadInstruction(), deleteIfDeadInstruction(), FindMostPopularDest(), FirstNonDbg(), llvm::InstCombiner::FoldICmpDivCst(), llvm::InstCombiner::FoldICmpShrCst(), llvm::FoldReturnIntoUncondBranch(), llvm::InstCombiner::FoldShiftByConstant(), llvm::BlockAddress::get(), getFCmpValue(), getGEPInductionOperand(), GetShiftedValue(), INITIALIZE_PASS(), llvm::InlineFunction(), insertVector(), InstCombineStoreToCast(), isOnlyReachableViaThisEdge(), LinearizeExprTree(), LowerNegateToMultiply(), MarkBlocksLiveIn(), mergeEmptyReturnBlocks(), NegateValue(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), RemapInstruction(), replaceUsesOfWith(), llvm::GlobalVariable::replaceUsesOfWithOnConstant(), llvm::ConstantArray::replaceUsesOfWithOnConstant(), llvm::ConstantStruct::replaceUsesOfWithOnConstant(), llvm::BlockAddress::replaceUsesOfWithOnConstant(), llvm::IndirectBrInst::setAddress(), llvm::GlobalAlias::setAliasee(), llvm::CallInst::setArgOperand(), llvm::InvokeInst::setArgOperand(), llvm::SwitchInst::setCondition(), llvm::SwitchInst::setDefaultDest(), llvm::PHINode::setIncomingValue(), llvm::Function::setPrefixData(), llvm::SwitchInst::setSuccessor(), llvm::IndirectBrInst::setSuccessor(), llvm::SwitchInst::CaseIt::setValue(), ShrinkDemandedConstant(), llvm::InstCombiner::SimplifyDivRemOfSelect(), SinkThenElseCodeToEnd(), SpeculativelyExecuteBB(), TryToSimplifyUncondBranchWithICmpInIt(), llvm::InstCombiner::visitAllocaInst(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitLoadInst(), llvm::InstCombiner::visitSelectInst(), llvm::InstCombiner::visitSelectInstWithICmp(), llvm::InstCombiner::visitShuffleVectorInst(), llvm::InstCombiner::visitSRem(), llvm::InstCombiner::visitStoreInst(), and llvm::InstCombiner::visitXor().
value_op_iterator llvm::User::value_op_begin () inline
Definition at line 153 of file User.h.
References op_begin(), and llvm::User::value_op_iterator::value_op_iterator().
Referenced by createMinMaxOp(), and llvm::DenseMapInfo< SimpleValue >::getTombstoneKey().
value_op_iterator llvm::User::value_op_end () inline
Definition at line 156 of file User.h.
References op_end(), and llvm::User::value_op_iterator::value_op_iterator().
Referenced by createMinMaxOp(), and llvm::DenseMapInfo< SimpleValue >::getTombstoneKey().
Friends And Related Function Documentation
template<unsigned > friend struct HungoffOperandTraits friend
Definition at line 37 of file User.h.
Member Data Documentation
unsigned llvm::User::NumOperands protected
NumOperands - The number of values used by this User.
Definition at line 49 of file User.h.
Referenced by llvm::SwitchInst::addCase(), llvm::IndirectBrInst::addDestination(), llvm::PHINode::addIncoming(), llvm::FenceInst::FenceInst(), getNumOperands(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::CmpInst::isFalseWhenEqual(), op_end(), operator delete(), operator new(), llvm::SwitchInst::removeCase(), llvm::IndirectBrInst::removeDestination(), llvm::GlobalVariable::setInitializer(), and llvm::GlobalVariable::~GlobalVariable().
Use* llvm::User::OperandList protected
OperandList - This is a pointer to the array of Uses for this User. For nodes of fixed arity (e.g. a binary operator) this array will live prefixed to some derived class instance. For nodes of resizable variable arity (e.g. PHINodes, SwitchInst etc.), this memory will be dynamically allocated and should be destroyed by the classes' virtual dtor.
Definition at line 45 of file User.h.
Referenced by llvm::IndirectBrInst::addDestination(), llvm::FenceInst::FenceInst(), llvm::LandingPadInst::getClause(), llvm::ConstantExpr::getOpcodeName(), llvm::PHINode::hasConstantValue(), llvm::LandingPadInst::isCatch(), llvm::CmpInst::isFalseWhenEqual(), llvm::LandingPadInst::isFilter(), llvm::HungoffOperandTraits< 2 >::op_begin(), op_begin(), llvm::HungoffOperandTraits< 2 >::op_end(), operator new(), llvm::SwitchInst::removeCase(), llvm::IndirectBrInst::removeDestination(), llvm::ConstantArray::replaceUsesOfWithOnConstant(), and llvm::ConstantStruct::replaceUsesOfWithOnConstant().
The documentation for this class was generated from the following files:
User.h
User.cpp