LLVM: llvm::MCSectionData Class Reference
LLVM API Documentation
llvm::MCSectionData Class Reference
#include <MCAssembler.h>
Public Types
enum BundleLockStateType { NotBundleLocked, BundleLocked, BundleLockedAlignToEnd }
Express the state of bundle locked groups while emitting code.
typedef iplist< MCFragment > FragmentListType
typedef FragmentListType::const_iterator const_iterator
typedef FragmentListType::iterator iterator
typedef FragmentListType::const_reverse_iterator const_reverse_iterator
typedef FragmentListType::reverse_iterator reverse_iterator
Public Member Functions
MCSectionData ()
MCSectionData (const MCSection &Section, MCAssembler *A=0)
const MCSection & getSection () const
unsigned getAlignment () const
void setAlignment (unsigned Value)
bool hasInstructions () const
void setHasInstructions (bool Value)
unsigned getOrdinal () const
void setOrdinal (unsigned Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
Fragment Access
const FragmentListType & getFragmentList () const
FragmentListType & getFragmentList ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_t size () const
bool empty () const
iterator getSubsectionInsertionPoint (unsigned Subsection)
bool isBundleLocked () const
BundleLockStateType getBundleLockState () const
void setBundleLockState (BundleLockStateType NewState)
bool isBundleGroupBeforeFirstInst () const
void setBundleGroupBeforeFirstInst (bool IsFirst)
void dump ()
Public Member Functions inherited from llvm::ilist_node< MCSectionData >
MCSectionData * getPrevNode ()
Get the previous node, or 0 for the list head.
const MCSectionData * getPrevNode () const
Get the previous node, or 0 for the list head.
MCSectionData * getNextNode ()
Get the next node, or 0 for the list tail.
const MCSectionData * getNextNode () const
Get the next node, or 0 for the list tail.
Friends
class MCAsmLayout
Additional Inherited Members
Protected Member Functions inherited from llvm::ilist_node< MCSectionData >
ilist_node ()
Detailed Description
Definition at line 544 of file MCAssembler.h.
Member Typedef Documentation
typedef FragmentListType::const_iterator llvm::MCSectionData::const_iterator
Definition at line 553 of file MCAssembler.h.
typedef FragmentListType::const_reverse_iterator llvm::MCSectionData::const_reverse_iterator
Definition at line 556 of file MCAssembler.h.
typedef iplist<MCFragment> llvm::MCSectionData::FragmentListType
Definition at line 551 of file MCAssembler.h.
typedef FragmentListType::iterator llvm::MCSectionData::iterator
Definition at line 554 of file MCAssembler.h.
typedef FragmentListType::reverse_iterator llvm::MCSectionData::reverse_iterator
Definition at line 557 of file MCAssembler.h.
Member Enumeration Documentation
enum llvm::MCSectionData::BundleLockStateType
Express the state of bundle locked groups while emitting code.
Enumerator
NotBundleLocked
BundleLocked
BundleLockedAlignToEnd
Definition at line 560 of file MCAssembler.h.
Constructor & Destructor Documentation
MCSectionData::MCSectionData ()
Definition at line 233 of file MCAssembler.cpp.
MCSectionData::MCSectionData (const MCSection & Section, MCAssembler * A = 0)
Definition at line 235 of file MCAssembler.cpp.
References llvm::MCAssembler::getSectionList(), and llvm::iplist< NodeTy, Traits >::push_back().
Member Function Documentation
iterator llvm::MCSectionData::begin () inline
Definition at line 625 of file MCAssembler.h.
References llvm::iplist< NodeTy, Traits >::begin().
Referenced by compareBySuffix(), llvm::MCAssembler::Finish(), llvm::MCAsmLayout::invalidateFragmentsFrom(), and llvm::MCAssembler::writeSectionData().
const_iterator llvm::MCSectionData::begin () const inline
Definition at line 626 of file MCAssembler.h.
References llvm::iplist< NodeTy, Traits >::begin().
void MCSectionData::dump ()
Definition at line 1127 of file MCAssembler.cpp.
References llvm::MCAssembler::begin(), llvm::MCAssembler::end(), llvm::errs(), and it.
bool llvm::MCSectionData::empty () const inline
Definition at line 639 of file MCAssembler.h.
References llvm::iplist< NodeTy, Traits >::empty().
iterator llvm::MCSectionData::end () inline
Definition at line 628 of file MCAssembler.h.
References llvm::iplist< NodeTy, Traits >::end().
Referenced by compareBySuffix(), llvm::MCAssembler::Finish(), getSubsectionInsertionPoint(), and llvm::MCAssembler::writeSectionData().
const_iterator llvm::MCSectionData::end () const inline
Definition at line 629 of file MCAssembler.h.
References llvm::iplist< NodeTy, Traits >::end().
unsigned llvm::MCSectionData::getAlignment () const inline
Definition at line 607 of file MCAssembler.h.
Referenced by compareBySuffix(), llvm::MachObjectWriter::computeSectionAddresses(), llvm::MCELFStreamer::Flush(), llvm::MachObjectWriter::getPaddingSize(), write_uint32_le(), and llvm::MachObjectWriter::WriteSection().
BundleLockStateType llvm::MCSectionData::getBundleLockState () const inline
Definition at line 647 of file MCAssembler.h.
Referenced by llvm::MCELFStreamer::EmitIdent().
const FragmentListType& llvm::MCSectionData::getFragmentList () const inline
Definition at line 622 of file MCAssembler.h.
Referenced by llvm::MCAsmLayout::getSectionAddressSize(), getSubsectionInsertionPoint(), llvm::MCObjectStreamer::insert(), and llvm::MCFragment::MCFragment().
FragmentListType& llvm::MCSectionData::getFragmentList () inline
Definition at line 623 of file MCAssembler.h.
unsigned llvm::MCSectionData::getLayoutOrder () const inline
Definition at line 616 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::getPaddingSize().
unsigned llvm::MCSectionData::getOrdinal () const inline
Definition at line 613 of file MCAssembler.h.
Referenced by compareBySuffix(), getARMFixupKindMachOInfo(), getFixupKindLog2Size(), and getFixupOffset().
const MCSection& llvm::MCSectionData::getSection () const inline
Definition at line 605 of file MCAssembler.h.
References llvm::ARMBuildAttrs::Section.
Referenced by compareBySuffix(), llvm::MCAssembler::getAtom(), getFixupKindLog2Size(), llvm::MachObjectWriter::getPaddingSize(), llvm::MCAsmLayout::getSectionFileSize(), llvm::MCObjectWriter::IsSymbolRefDifferenceFullyResolvedImpl(), llvm::MachObjectWriter::IsSymbolRefDifferenceFullyResolvedImpl(), write_uint32_le(), llvm::MachObjectWriter::WriteObject(), llvm::MachObjectWriter::WriteSection(), and llvm::MCAssembler::writeSectionData().
MCSectionData::iterator MCSectionData::getSubsectionInsertionPoint (unsigned Subsection)
Definition at line 247 of file MCAssembler.cpp.
References end(), getFragmentList(), llvm::iplist< NodeTy, Traits >::insert(), llvm::A64CC::MI, and llvm::MCFragment::setParent().
Referenced by llvm::MCObjectStreamer::ChangeSection().
bool llvm::MCSectionData::hasInstructions () const inline
Definition at line 610 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::WriteSection().
bool llvm::MCSectionData::isBundleGroupBeforeFirstInst () const inline
Definition at line 655 of file MCAssembler.h.
Referenced by llvm::MCELFStreamer::EmitIdent().
bool llvm::MCSectionData::isBundleLocked () const inline
Definition at line 643 of file MCAssembler.h.
Referenced by llvm::MCELFStreamer::ChangeSection(), llvm::MCELFStreamer::EmitIdent(), and llvm::MCObjectStreamer::EmitInstruction().
reverse_iterator llvm::MCSectionData::rbegin () inline
Definition at line 631 of file MCAssembler.h.
References llvm::iplist< NodeTy, Traits >::rbegin().
const_reverse_iterator llvm::MCSectionData::rbegin () const inline
Definition at line 632 of file MCAssembler.h.
References llvm::iplist< NodeTy, Traits >::rbegin().
reverse_iterator llvm::MCSectionData::rend () inline
Definition at line 634 of file MCAssembler.h.
References llvm::iplist< NodeTy, Traits >::rend().
const_reverse_iterator llvm::MCSectionData::rend () const inline
Definition at line 635 of file MCAssembler.h.
References llvm::iplist< NodeTy, Traits >::rend().
void llvm::MCSectionData::setAlignment (unsigned Value) inline
Definition at line 608 of file MCAssembler.h.
Referenced by compareBySuffix(), llvm::MCObjectStreamer::EmitValueToAlignment(), and llvm::MCELFStreamer::Flush().
void llvm::MCSectionData::setBundleGroupBeforeFirstInst (bool IsFirst) inline
Definition at line 659 of file MCAssembler.h.
References llvm::MCFragment::dump().
Referenced by llvm::MCELFStreamer::EmitIdent().
void llvm::MCSectionData::setBundleLockState (BundleLockStateType NewState) inline
Definition at line 651 of file MCAssembler.h.
Referenced by llvm::MCELFStreamer::EmitIdent().
void llvm::MCSectionData::setHasInstructions (bool Value) inline
Definition at line 611 of file MCAssembler.h.
Referenced by llvm::MCObjectStreamer::EmitInstruction().
void llvm::MCSectionData::setLayoutOrder (unsigned Value) inline
Definition at line 617 of file MCAssembler.h.
Referenced by llvm::MCAssembler::Finish().
void llvm::MCSectionData::setOrdinal (unsigned Value) inline
Definition at line 614 of file MCAssembler.h.
size_t llvm::MCSectionData::size () const inline
Definition at line 637 of file MCAssembler.h.
References llvm::iplist< NodeTy, Traits >::size().
Friends And Related Function Documentation
friend class MCAsmLayout friend
Definition at line 545 of file MCAssembler.h.
The documentation for this class was generated from the following files:
MCAssembler.h
MCAssembler.cpp