LLVM: llvm::CoalescerPair Class Reference
LLVM API Documentation
llvm::CoalescerPair Class Reference
#include <RegisterCoalescer.h>
Public Member Functions
CoalescerPair (const TargetRegisterInfo &tri)
CoalescerPair (unsigned VirtReg, unsigned PhysReg, const TargetRegisterInfo &tri)
bool setRegisters (const MachineInstr *)
bool flip ()
bool isCoalescable (const MachineInstr *) const
bool isPhys () const
isPhys - Return true if DstReg is a physical register.
bool isPartial () const
bool isCrossClass () const
bool isFlipped () const
unsigned getDstReg () const
unsigned getSrcReg () const
getSrcReg - Return the virtual register that will be coalesced away.
unsigned getDstIdx () const
unsigned getSrcIdx () const
const TargetRegisterClass * getNewRC () const
getNewRC - Return the register class of the coalesced register.
Detailed Description
CoalescerPair - A helper class for register coalescers. When deciding if two registers can be coalesced, CoalescerPair can determine if a copy instruction would become an identity copy after coalescing.
Definition at line 28 of file RegisterCoalescer.h.
Constructor & Destructor Documentation
llvm::CoalescerPair::CoalescerPair (const TargetRegisterInfo & tri) inline
Definition at line 62 of file RegisterCoalescer.h.
llvm::CoalescerPair::CoalescerPair (unsigned VirtReg, unsigned PhysReg, const TargetRegisterInfo & tri) inline
Create a CoalescerPair representing a virtreg-to-physreg copy. No need to call setRegisters().
Definition at line 68 of file RegisterCoalescer.h.
References flip(), isCoalescable(), and setRegisters().
Member Function Documentation
bool CoalescerPair::flip ()
flip - Swap SrcReg and DstReg. Return false if swapping is impossible because DstReg is a physical register, or SubIdx is set.
Definition at line 341 of file RegisterCoalescer.cpp.
References llvm::TargetRegisterInfo::isPhysicalRegister(), and std::swap().
Referenced by CoalescerPair().
unsigned llvm::CoalescerPair::getDstIdx () const inline
getDstIdx - Return the subregister index that DstReg will be coalesced into, or 0.
Definition at line 109 of file RegisterCoalescer.h.
Referenced by isCoalescable().
unsigned llvm::CoalescerPair::getDstReg () const inline
getDstReg - Return the register (virtual or physical) that will remain after coalescing.
Definition at line 102 of file RegisterCoalescer.h.
Referenced by isCoalescable().
const TargetRegisterClass* llvm::CoalescerPair::getNewRC () const inline
getNewRC - Return the register class of the coalesced register.
Definition at line 116 of file RegisterCoalescer.h.
Referenced by isCoalescable().
unsigned llvm::CoalescerPair::getSrcIdx () const inline
getSrcIdx - Return the subregister index that SrcReg will be coalesced into, or 0.
Definition at line 113 of file RegisterCoalescer.h.
Referenced by isCoalescable().
unsigned llvm::CoalescerPair::getSrcReg () const inline
getSrcReg - Return the virtual register that will be coalesced away.
Definition at line 105 of file RegisterCoalescer.h.
Referenced by isCoalescable().
bool CoalescerPair::isCoalescable (const MachineInstr * MI) const
isCoalescable - Return true if MI is a copy instruction that will become an identity copy after coalescing.
Definition at line 350 of file RegisterCoalescer.cpp.
References llvm::MachineInstr::addOperand(), llvm::AnalysisUsage::addPreserved(), llvm::AnalysisUsage::addPreservedID(), llvm::AnalysisUsage::addRequired(), llvm::LiveRange::addSegment(), llvm::MachineInstr::allDefsAreDead(), llvm::LiveRange::begin(), llvm::TargetRegisterClass::contains(), llvm::LiveRange::containsOneValue(), llvm::MachineOperand::CreateReg(), llvm::SmallVectorTemplateCommon< T >::data(), llvm::dbgs(), DEBUG, llvm::tgtok::Def, llvm::VNInfo::def, llvm::LiveRangeEdit::eliminateDeadDefs(), llvm::SmallVectorBase::empty(), llvm::LiveRange::end(), llvm::LiveQueryResult::endPoint(), llvm::MachineBasicBlock::erase(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::findRegisterDefOperandIdx(), llvm::MachineInstr::findRegisterUseOperandIdx(), llvm::LiveRange::FindSegmentContaining(), llvm::SmallVectorTemplateCommon< T >::front(), llvm::MachineFunctionPass::getAnalysisUsage(), llvm::MachineInstr::getDesc(), getDstIdx(), getDstReg(), getNewRC(), llvm::MachineBasicBlock::getNumber(), llvm::MCInstrDesc::getNumDefs(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getNumOperands(), llvm::LiveRange::getNumValNums(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getParent(), llvm::SlotIndex::getPrevSlot(), llvm::MachineOperand::getReg(), llvm::MCRegisterInfo::getRegClass(), llvm::SlotIndex::getRegSlot(), llvm::LiveIntervals::getSlotIndexes(), getSrcIdx(), getSrcReg(), llvm::MachineOperand::getSubReg(), llvm::LiveRange::getVNInfoAt(), i, I, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::MachineBasicBlock::insert(), llvm::MachineInstr::isAsCheapAsAMove(), llvm::SlotIndex::isBlock(), isCoalescable(), llvm::MachineInstr::isCommutable(), llvm::MachineInstr::isCopy(), llvm::MachineInstr::isCopyLike(), llvm::SlotIndex::isDead(), llvm::MachineOperand::isDead(), llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isDef(), isFlipped(), llvm::MachineInstr::isFullCopy(), llvm::MachineOperand::isImplicit(), llvm::MachineInstr::isImplicitDef(), llvm::LiveQueryResult::isKill(), isMoveInstr(), isPartial(), llvm::VNInfo::isPHIDef(), isPhys(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::MachineOperand::isReg(), llvm::MachineInstr::isRegTiedToDefOperand(), llvm::MachineInstr::isRegTiedToUseOperand(), llvm::MachineInstr::isSafeToMove(), llvm::SlotIndex::isSameInstr(), llvm::MachineOperand::isUndef(), llvm::VNInfo::isUnused(), llvm::MachineOperandIteratorBase::isValid(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::LiveRange::join(), llvm::LiveRange::liveAt(), llvm_unreachable, llvm::MachineDominatorsID, llvm::LiveRange::MergeValueNumberInto(), llvm::A64CC::MI, MII, MRI, llvm::next(), llvm::LiveRange::overlaps(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::prior(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::LiveRange::Query(), llvm::MachineInstr::readsWritesVirtualRegister(), llvm::LiveInterval::reg, llvm::LiveRange::removeValNo(), llvm::MachineOperand::setIsDead(), llvm::MachineOperand::setIsKill(), llvm::MachineOperand::setIsUndef(), llvm::AnalysisUsage::setPreservesCFG(), llvm::MachineOperand::setReg(), llvm::MachineOperand::setSubReg(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::SmallVectorTemplateCommon< T, typename >::size(), size, llvm::MachineInstr::substituteRegister(), llvm::MachineOperand::substPhysReg(), llvm::MachineOperand::substVirtReg(), std::swap(), llvm::tie(), TII, llvm::LiveQueryResult::valueDefined(), and llvm::LiveQueryResult::valueIn().
Referenced by CoalescerPair(), isCoalescable(), and llvm::LiveRange::overlaps().
bool llvm::CoalescerPair::isCrossClass () const inline
isCrossClass - Return true if DstReg is virtual and NewRC is a smaller register class than DstReg's.
Definition at line 94 of file RegisterCoalescer.h.
bool llvm::CoalescerPair::isFlipped () const inline
isFlipped - Return true when getSrcReg is the register being defined by the original copy instruction.
Definition at line 98 of file RegisterCoalescer.h.
Referenced by isCoalescable().
bool llvm::CoalescerPair::isPartial () const inline
isPartial - Return true if the original copy instruction did not copy the full register, but was a subreg operation.
Definition at line 90 of file RegisterCoalescer.h.
Referenced by isCoalescable().
bool llvm::CoalescerPair::isPhys () const inline
isPhys - Return true if DstReg is a physical register.
Definition at line 86 of file RegisterCoalescer.h.
Referenced by isCoalescable().
bool CoalescerPair::setRegisters (const MachineInstr * MI)
setRegisters - set registers to match the copy instruction MI. Return false if MI is not a coalescable copy instruction.
Definition at line 252 of file RegisterCoalescer.cpp.
References llvm::TargetRegisterClass::contains(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), isMoveInstr(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::TargetRegisterInfo::isVirtualRegister(), MRI, and std::swap().
Referenced by CoalescerPair().
The documentation for this class was generated from the following files:
RegisterCoalescer.h
RegisterCoalescer.cpp