LLVM: llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT > Class Template Reference
LLVM API Documentation
llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT > Class Template Reference
#include <DenseMap.h>
Inherited by llvm::DenseMap< AnalysisID, llvm::IdentifyingPassPtr >, llvm::DenseMap< AnalysisID, llvm::Pass * >, llvm::DenseMap< ASTCallbackVH, AliasSet::PointerRec *, ASTCallbackVHDenseMapInfo >, llvm::DenseMap< AttributeSet, unsigned >, llvm::DenseMap< BasicBlock *, Region * >, llvm::DenseMap< BlkT *, BBInfo * >, llvm::DenseMap< BlockT *, BranchProbability >, llvm::DenseMap< BlockT *, LoopT * >, llvm::DenseMap< BlockT *, unsigned >, llvm::DenseMap< const BlockT *, llvm::BlockFrequency >, llvm::DenseMap< const Function *, GCFunctionInfo * >, llvm::DenseMap< const Function *, ReturnInst * >, llvm::DenseMap< const Function *, unsigned >, llvm::DenseMap< const Instruction *, unsigned >, llvm::DenseMap< const llvm::AllocaInst *, int >, llvm::DenseMap< const llvm::Argument *, int >, llvm::DenseMap< const llvm::BasicBlock *, llvm::BlockFrequency >, llvm::DenseMap< const llvm::BasicBlock *, llvm::MachineBasicBlock * >, llvm::DenseMap< const llvm::BasicBlock *, unsigned >, llvm::DenseMap< const llvm::Constant *, unsigned >, llvm::DenseMap< const llvm::DIE *, llvm::CompileUnit * >, llvm::DenseMap< const llvm::DIE *, unsigned >, llvm::DenseMap< const llvm::GlobalValue *, unsigned >, llvm::DenseMap< const llvm::Instruction *, llvm::SmallVector >, llvm::DenseMap< const llvm::Loop *, BackedgeTakenInfo >, llvm::DenseMap< const llvm::MachineBasicBlock *, llvm::BlockFrequency >, llvm::DenseMap< const llvm::MachineInstr *, llvm::MachineTraceMetrics::InstrCycles >, llvm::DenseMap< const llvm::MachineInstr *, llvm::MCSymbol * >, llvm::DenseMap< const llvm::MCSection *, llvm::MCLineSection * >, llvm::DenseMap< const llvm::MCSection *, llvm::MCSectionData * >, llvm::DenseMap< const llvm::MCSectionData *, llvm::MCFragment * >, llvm::DenseMap< const llvm::MCSectionData *, std::vector< MachO::any_relocation_info > >, llvm::DenseMap< const llvm::MCSectionData *, unsigned >, llvm::DenseMap< const llvm::MCSymbol *, llvm::MCSymbolData * >, llvm::DenseMap< const llvm::MCSymbol *, uint64_t >, llvm::DenseMap< const llvm::MCSymbol *, unsigned >, llvm::DenseMap< const llvm::MDNode *, llvm::CompileUnit * >, llvm::DenseMap< const llvm::MDNode *, llvm::DbgVariable * >, llvm::DenseMap< const llvm::MDNode *, llvm::DIE * >, llvm::DenseMap< const llvm::MDNode *, llvm::DIEEntry * >, llvm::DenseMap< const llvm::MDNode *, llvm::LexicalScope * >, llvm::DenseMap< const llvm::MDNode *, unsigned >, llvm::DenseMap< const llvm::object::Elf_Sym_Impl *, ELF::Elf64_Word >, llvm::DenseMap< const llvm::SCEV *, const llvm::Loop * >, llvm::DenseMap< const llvm::SCEV *, llvm::ConstantRange >, llvm::DenseMap< const llvm::SCEV *, llvm::SmallVector< std::pair< const llvm::BasicBlock *, BlockDisposition >, 2 > >, llvm::DenseMap< const llvm::SCEV *, llvm::SmallVector< std::pair< const llvm::Loop *, const llvm::SCEV * >, 2 > >, llvm::DenseMap< const llvm::SCEV *, llvm::SmallVector< std::pair< const llvm::Loop *, LoopDisposition >, 2 > >, llvm::DenseMap< const llvm::Value *, char, DenseMapInfo< const llvm::Value * > >, llvm::DenseMap< const llvm::Value *, DanglingDebugInfo >, llvm::DenseMap< const llvm::Value *, llvm::SDValue >, llvm::DenseMap< const llvm::Value *, unsigned >, llvm::DenseMap< const MachineInstr *, SlotIndex >, llvm::DenseMap< const MCExpr *, unsigned >, llvm::DenseMap< const MCSection *, SmallVector< SymbolCU, 8 > >, llvm::DenseMap< const MCSectionData *, uint64_t >, llvm::DenseMap< const MDNode *, SmallVector< const MachineInstr *, 4 > >, llvm::DenseMap< const MDString *, MDNode * >, llvm::DenseMap< const SDNode *, SmallVector< SDDbgValue *, 2 > >, llvm::DenseMap< const TargetRegisterClass *, VRegMap >, llvm::DenseMap< const Value *, unsigned >, llvm::DenseMap< const Value *, WeakEvalType >, llvm::DenseMap< ConstantArray *, char, MapInfo >, llvm::DenseMap< ConstantClass *, char, MapInfo >, llvm::DenseMap< ConstantStruct *, char, MapInfo >, llvm::DenseMap< ConstantVector *, char, MapInfo >, llvm::DenseMap< DenseMapAPFloatKeyInfo::KeyTy, ConstantFP *, DenseMapAPFloatKeyInfo >, llvm::DenseMap< DenseMapAPIntKeyInfo::KeyTy, ConstantInt *, DenseMapAPIntKeyInfo >, llvm::DenseMap< Edge, uint32_t >, llvm::DenseMap< Function *, FunctionAnalysisResultListT >, llvm::DenseMap< FunctionType *, bool, FunctionTypeKeyInfo >, llvm::DenseMap< Instruction *, MemDepResult >, llvm::DenseMap< Instruction *, PerInstNLInfo >, llvm::DenseMap< Instruction *, SmallPtrSet< Instruction *, 4 > >, llvm::DenseMap< Instruction *, SmallPtrSet< ValueIsLoadPair, 4 > >, llvm::DenseMap< K, llvm::ScopedHashTableVal *, KInfo >, llvm::DenseMap< LexicalScope *, SmallVector< DbgVariable *, 8 > >, llvm::DenseMap< llvm::AssertingVH< llvm::BasicBlock >, AddrLabelSymEntry >, llvm::DenseMap< llvm::AssertingVH< llvm::Function >, std::vector< llvm::MCSymbol * > >, llvm::DenseMap< llvm::AssertingVH< llvm::MDNode >, std::string >, llvm::DenseMap< llvm::AttributeSet, unsigned >, llvm::DenseMap< llvm::BasicBlock *, BranchProbability >, llvm::DenseMap< llvm::BasicBlock *, DomTreeNodeBase< llvm::BasicBlock > * >, llvm::DenseMap< llvm::BasicBlock *, llvm::BasicBlock * >, llvm::DenseMap< llvm::BasicBlock *, llvm::BasicBlock ** >, llvm::DenseMap< llvm::BasicBlock *, llvm::DominatorTreeBase::InfoRec >, llvm::DenseMap< llvm::BasicBlock *, llvm::Loop * >, llvm::DenseMap< llvm::BasicBlock *, unsigned >, llvm::DenseMap< llvm::DebugLoc, llvm::LexicalScope * >, llvm::DenseMap< llvm::DIE *, const llvm::MDNode * >, llvm::DenseMap< llvm::Function *, std::vector< BlockAddrRefTy > >, llvm::DenseMap< llvm::Function *, uint64_t >, llvm::DenseMap< llvm::Instruction *, std::vector< MDRef > >, llvm::DenseMap< llvm::Instruction *, unsigned >, llvm::DenseMap< llvm::MachineBasicBlock *, BranchProbability >, llvm::DenseMap< llvm::MachineBasicBlock *, DomTreeNodeBase< llvm::MachineBasicBlock > * >, llvm::DenseMap< llvm::MachineBasicBlock *, llvm::DominatorTreeBase::InfoRec >, llvm::DenseMap< llvm::MachineBasicBlock *, llvm::MachineBasicBlock * >, llvm::DenseMap< llvm::MachineBasicBlock *, llvm::MachineLoop * >, llvm::DenseMap< llvm::MachineBasicBlock *, llvm::SmallVector< unsigned, 4 > >, llvm::DenseMap< llvm::MachineBasicBlock *, unsigned >, llvm::DenseMap< llvm::MachineConstantPoolValue *, char, DenseMapInfo< llvm::MachineConstantPoolValue * > >, llvm::DenseMap< llvm::MachineInstr *, llvm::SUnit * >, llvm::DenseMap< llvm::MachineInstr *, unsigned >, llvm::DenseMap< llvm::MCSymbol *, llvm::SmallVector< unsigned, 4 > >, llvm::DenseMap< llvm::MCSymbol *, StubValueTy >, llvm::DenseMap< llvm::MCSymbol *, unsigned >, llvm::DenseMap< llvm::MCSymbol const *, char, DenseMapInfo< llvm::MCSymbol const * > >, llvm::DenseMap< llvm::MDNode *, int >, llvm::DenseMap< llvm::Pass *, llvm::AnalysisUsage * >, llvm::DenseMap< llvm::Pass *, llvm::Pass * >, llvm::DenseMap< llvm::Pass *, llvm::SmallPtrSet< llvm::Pass *, 8 > >, llvm::DenseMap< llvm::PHINode *, llvm::Constant * >, llvm::DenseMap< llvm::PointerType *, llvm::ConstantPointerNull * >, llvm::DenseMap< llvm::StructType *, unsigned >, llvm::DenseMap< llvm::Type *, char, DenseMapInfo< llvm::Type * > >, llvm::DenseMap< llvm::Type *, llvm::ConstantAggregateZero * >, llvm::DenseMap< llvm::Type *, llvm::PointerType * >, llvm::DenseMap< llvm::Type *, llvm::UndefValue * >, llvm::DenseMap< llvm::Value *, char, DenseMapInfo< llvm::Value * > >, llvm::DenseMap< llvm::Value *, LatticeVal >, llvm::DenseMap< Module *, ObjectImage * >, llvm::DenseMap< NodeT *, DomTreeNodeBase< NodeT > * >, llvm::DenseMap< NodeT *, llvm::DominatorTreeBase::InfoRec >, llvm::DenseMap< NodeT *, NodeT * >, llvm::DenseMap< NodeType *, unsigned >, llvm::DenseMap< SCEVCallbackVH, const SCEV *, DenseMapInfo< Value * > >, llvm::DenseMap< std::pair< llvm::Function *, llvm::BasicBlock * >, llvm::BlockAddress * >, llvm::DenseMap< std::pair< llvm::MDNode *, llvm::MDNode * >, int >, llvm::DenseMap< std::pair< llvm::Type *, uint64_t >, llvm::ArrayType * >, llvm::DenseMap< std::pair< llvm::Type *, unsigned >, llvm::PointerType * >, llvm::DenseMap< std::pair< llvm::Type *, unsigned >, llvm::VectorType * >, llvm::DenseMap< std::pair< unsigned, unsigned >, ValueForcePair >, llvm::DenseMap< std::pair< void *, Function * >, FunctionAnalysisResultListT::iterator >, llvm::DenseMap< StructType *, bool, AnonStructTypeKeyInfo >, llvm::DenseMap< Type *, unsigned >, llvm::DenseMap< uint32_t, char, DenseMapInfo< uint32_t > >, llvm::DenseMap< uint64_t, object::RelocationRef >, llvm::DenseMap< uint64_t, std::pair< uint8_t, int64_t > >, llvm::DenseMap< unsigned int, unsigned int >, llvm::DenseMap< unsigned, AllowedSet >, llvm::DenseMap< unsigned, float >, llvm::DenseMap< unsigned, int >, llvm::DenseMap< unsigned, intptr_t >, llvm::DenseMap< unsigned, llvm::IntegerType * >, llvm::DenseMap< unsigned, llvm::MCLabel * >, llvm::DenseMap< unsigned, llvm::MCSymbol * >, llvm::DenseMap< unsigned, llvm::PointerAlignElem >, llvm::DenseMap< unsigned, llvm::SmallVector >, llvm::DenseMap< unsigned, PBQP::Graph::NodeId >, llvm::DenseMap< unsigned, std::pair< unsigned, unsigned > >, llvm::DenseMap< unsigned, std::string >, llvm::DenseMap< unsigned, TreeTy * >, llvm::DenseMap< unsigned, unsigned >, llvm::DenseMap< UnsignPair, unsigned >, llvm::DenseMap< Value *, char, DenseMapInfo< Value * > >, llvm::DenseMap< Value *, ValueHandleBase * >, llvm::DenseMap< ValueIsLoadPair, NonLocalPointerInfo >, llvm::DenseMap< ValueMapCVH, const llvm::MipsCallEntry *, DenseMapInfo< ValueMapCVH > >, llvm::DenseMap< ValueMapCVH, SSPLayoutKind, DenseMapInfo< ValueMapCVH > >, llvm::DenseMap< ValueMapCVH, ValueT, DenseMapInfo< ValueMapCVH > >, llvm::DenseMap< ValueMapCVH, void *, DenseMapInfo< ValueMapCVH > >, llvm::DenseMap< ValuePairTy, bool >, llvm::DenseMap< ValueT, char, ValueInfoT >, llvm::DenseMap< void *, intptr_t >, llvm::DenseMap< void *, polymorphic_ptr< AnalysisPassConcept< Function > > >, llvm::DenseMap< void *, polymorphic_ptr< AnalysisPassConcept< Module > > >, and llvm::DenseMap< void *, polymorphic_ptr< AnalysisResultConcept< Module > > >.
Public Types
typedef KeyT key_type
typedef ValueT mapped_type
typedef BucketT value_type
typedef DenseMapIterator< KeyT, ValueT, KeyInfoT > iterator
typedef DenseMapIterator< KeyT, ValueT, KeyInfoT, true > const_iterator
Public Member Functions
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool LLVM_ATTRIBUTE_UNUSED_RESULT empty () const
unsigned size () const
void resize (size_t Size)
Grow the densemap so that it has at least Size buckets. Does not shrink.
void clear ()
bool count (const KeyT &Val) const
count - Return true if the specified key is in the map.
iterator find (const KeyT &Val)
const_iterator find (const KeyT &Val) const
template<class LookupKeyT >
iterator find_as (const LookupKeyT &Val)
template<class LookupKeyT >
const_iterator find_as (const LookupKeyT &Val) const
ValueT lookup (const KeyT &Val) const
std::pair< iterator, bool > insert (const std::pair< KeyT, ValueT > &KV)
template<typename InputIt >
void insert (InputIt I, InputIt E)
insert - Range insertion of pairs.
bool erase (const KeyT &Val)
void erase (iterator I)
value_type & FindAndConstruct (const KeyT &Key)
ValueT & operator[] (const KeyT &Key)
bool isPointerIntoBucketsArray (const void *Ptr) const
const void * getPointerIntoBucketsArray () const
size_t getMemorySize () const
Protected Types
typedef std::pair< KeyT, ValueT > BucketT
Protected Member Functions
DenseMapBase ()
void destroyAll ()
void initEmpty ()
void moveFromOldBuckets (BucketT *OldBucketsBegin, BucketT *OldBucketsEnd)
template<typename OtherBaseT >
void copyFrom (const DenseMapBase< OtherBaseT, KeyT, ValueT, KeyInfoT > &other)
void swap (DenseMapBase &RHS)
Static Protected Member Functions
static unsigned getHashValue (const KeyT &Val)
template<typename LookupKeyT >
static unsigned getHashValue (const LookupKeyT &Val)
static const KeyT getEmptyKey ()
static const KeyT getTombstoneKey ()
Detailed Description
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT>
class llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >
Definition at line 41 of file DenseMap.h.
Member Typedef Documentation
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> typedef std::pair<KeyT, ValueT> llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::BucketT protected
Definition at line 43 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> typedef DenseMapIterator<KeyT, ValueT, KeyInfoT, true> llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::const_iterator
Definition at line 52 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> typedef DenseMapIterator<KeyT, ValueT, KeyInfoT> llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::iterator
Definition at line 50 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> typedef KeyT llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::key_type
Definition at line 46 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> typedef ValueT llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::mapped_type
Definition at line 47 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> typedef BucketT llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::value_type
Definition at line 48 of file DenseMap.h.
Constructor & Destructor Documentation
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::DenseMapBase () inline protected
Definition at line 248 of file DenseMap.h.
Member Function Documentation
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::begin () inline
Definition at line 53 of file DenseMap.h.
Referenced by llvm::ValueMap< const BasicBlock *, void * >::begin(), llvm::DenseSet< llvm::Value * >::begin(), llvm::DwarfDebug::beginFunction(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::compare(), llvm::DwarfDebug::endFunction(), FindMostPopularDest(), llvm::ConstantAggrUniqueMap< ArrayType, ConstantArray >::freeConstants(), llvm::Value::getContext(), isLoadFromGOTOrConstantPool(), llvm::ConstantAggrUniqueMap< ArrayType, ConstantArray >::map_begin(), llvm::ValueEnumerator::print(), llvm::MemoryDependenceAnalysis::removeInstruction(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::reset(), llvm::MachineSSAUpdater::RewriteUse(), llvm::SelectionDAGISel::runOnMachineFunction(), shouldAddODRHash(), llvm::ScalarEvolution::verifyAnalysis(), and llvm::AsmPrinter::~AsmPrinter().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> const_iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::begin () const inline
Definition at line 60 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::clear () inline
Definition at line 78 of file DenseMap.h.
Referenced by llvm::VirtRegAuxInfo::calculateSpillWeightAndHint(), llvm::DenseSet< llvm::Value * >::clear(), llvm::objcarc::ProvenanceAnalysis::clear(), llvm::ValueMap< const BasicBlock *, void * >::clear(), llvm::SDDbgInfo::clear(), llvm::FunctionLoweringInfo::clear(), llvm::GCModuleInfo::clear(), llvm::DwarfDebug::endFunction(), llvm::BitcodeReader::FreeState(), llvm::MachineSSAUpdater::Initialize(), llvm::SSAUpdater::Initialize(), INITIALIZE_PASS(), llvm::isAllocaPromotable(), llvm::FastISel::LowerArguments(), regsAreCompatible(), llvm::MemoryDependenceAnalysis::releaseMemory(), llvm::SlotIndexes::releaseMemory(), llvm::LoopInfoBase< llvm::MachineBasicBlock, llvm::MachineLoop >::releaseMemory(), llvm::ScalarEvolution::releaseMemory(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::reset(), llvm::SplitEditor::reset(), and llvm::FastISel::startNewBlock().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> template<typename OtherBaseT > void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::copyFrom (const DenseMapBase< OtherBaseT, KeyT, ValueT, KeyInfoT > & other) inline protected
Definition at line 310 of file DenseMap.h.
Referenced by llvm::DenseMap< unsigned, unsigned >::DenseMap(), llvm::DenseMap< unsigned, unsigned >::operator=(), llvm::SmallDenseMap< llvm::SDValue, llvm::SDValue, 8 >::operator=(), and llvm::SmallDenseMap< llvm::SDValue, llvm::SDValue, 8 >::SmallDenseMap().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> bool llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::count (const KeyT & Val) const inline
count - Return true if the specified key is in the map.
Definition at line 103 of file DenseMap.h.
Referenced by llvm::DFAPacketizer::canReserveResources(), llvm::DenseSet< llvm::Value * >::count(), llvm::DFAPacketizer::DFAPacketizer(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::DwarfException::EmitExceptionTable(), llvm::Function::getIntrinsicID(), llvm::SlotIndexes::hasIndex(), llvm::MachineSSAUpdater::HasValueForBlock(), llvm::SSAUpdater::HasValueForBlock(), llvm::FunctionLoweringInfo::isExportedInst(), llvm::ARMBaseInstrInfo::isFpMLxInstruction(), llvm::PPCRegisterInfo::needsFrameBaseReg(), llvm::MemoryDependenceAnalysis::removeInstruction(), llvm::scc_iterator< GraphT, GT >::ReplaceNode(), llvm::DFAPacketizer::reserveResources(), selectIncomingValueForBlock(), and llvm::X86InstrInfo::X86InstrInfo().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::destroyAll () inline protected
Definition at line 250 of file DenseMap.h.
Referenced by llvm::DenseMap< unsigned, unsigned >::copyFrom(), llvm::SmallDenseMap< llvm::SDValue, llvm::SDValue, 8 >::copyFrom(), llvm::DenseMap< unsigned, unsigned >::operator=(), llvm::SmallDenseMap< llvm::SDValue, llvm::SDValue, 8 >::operator=(), llvm::DenseMap< unsigned, unsigned >::shrink_and_clear(), llvm::SmallDenseMap< llvm::SDValue, llvm::SDValue, 8 >::shrink_and_clear(), llvm::DenseMap< unsigned, unsigned >::~DenseMap(), and llvm::SmallDenseMap< llvm::SDValue, llvm::SDValue, 8 >::~SmallDenseMap().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> bool LLVM_ATTRIBUTE_UNUSED_RESULT llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::empty () const inline
Definition at line 67 of file DenseMap.h.
Referenced by llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT >, KeyT, ValueT, KeyInfoT >::begin(), llvm::DwarfDebug::beginFunction(), CompactSwizzlableVector(), llvm::DenseSet< llvm::Value * >::empty(), llvm::ValueMap< const BasicBlock *, void * >::empty(), llvm::MCObjectSymbolizer::findRelocationAt(), ReorganizeVector(), and llvm::SlotIndexes::runOnMachineFunction().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::end () inline
Definition at line 57 of file DenseMap.h.
Referenced by llvm::ValueMapCallbackVH< KeyT, ValueT, Config >::allUsesReplacedWith(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT >, KeyT, ValueT, KeyInfoT >::begin(), llvm::DwarfDebug::beginFunction(), llvm::bypassSlowDivision(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::compare(), llvm::ObjectSizeOffsetEvaluator::compute(), llvm::DwarfException::ComputeCallSiteTable(), llvm::SelectionDAGBuilder::CopyToExportRegsIfNeeded(), llvm::ValueMap< const BasicBlock *, void * >::count(), llvm::ValueMap< const BasicBlock *, void * >::end(), llvm::DenseSet< llvm::Value * >::end(), llvm::DwarfDebug::endFunction(), llvm::ValueMap< const BasicBlock *, void * >::erase(), llvm::DWARFFormValue::extractValue(), llvm::FastISel::FastEmitBranch(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT >, KeyT, ValueT, KeyInfoT >::find(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT >, KeyT, ValueT, KeyInfoT >::find_as(), llvm::MCObjectSymbolizer::findRelocationAt(), llvm::ConstantAggrUniqueMap< ArrayType, ConstantArray >::freeConstants(), llvm::FunctionType::get(), llvm::StructType::get(), llvm::ValueEnumerator::getAttributeGroupID(), llvm::ValueEnumerator::getAttributeID(), llvm::Value::getContext(), llvm::BranchProbabilityInfo::getEdgeWeight(), llvm::GCModuleInfo::getFunctionInfo(), llvm::SlotIndexes::getIndexAfter(), llvm::SlotIndexes::getIndexBefore(), llvm::ARMJITInfo::getIndirectSymAddr(), llvm::ValueEnumerator::getInstructionID(), llvm::SlotIndexes::getInstructionIndex(), getMappedReg(), llvm::X86InstrInfo::getOpcodeAfterMemoryUnfold(), llvm::ConstantAggrUniqueMap< ArrayType, ConstantArray >::getOrCreate(), llvm::ARMFunctionInfo::getOriginalCPIdx(), llvm::ARMJITInfo::getPCLabelAddr(), llvm::Function::getPrefixData(), llvm::RegionInfo::getRegionFor(), getRegsUsedByPHIs(), llvm::SDDbgInfo::getSDDbgValues(), llvm::MCRegisterInfo::getSEHRegNum(), llvm::R600InstrInfo::getSrcs(), getTruncatedArgReg(), llvm::ValueEnumerator::getTypeID(), llvm::SelectionDAGBuilder::getValue(), llvm::ValueEnumerator::getValueID(), llvm::SlotIndexes::insertMachineInstrInMaps(), llvm::FunctionLoweringInfo::InvalidatePHILiveOutRegInfo(), llvm::isAllocaPromotable(), llvm::AsmPrinter::isBlockOnlyReachableByFallthrough(), isLoadFromGOTOrConstantPool(), isOnlyUsedInEntryBlock(), llvm::ValueMap< const BasicBlock *, void * >::lookup(), llvm::FastISel::lookUpRegForValue(), llvm::FastISel::LowerArguments(), llvm::ConstantAggrUniqueMap< ArrayType, ConstantArray >::map_end(), llvm::DWARFDebugLoc::parse(), llvm::DWARFDebugLine::parseStatementTable(), llvm::ValueEnumerator::print(), llvm::FileInfo::print(), pushDepHeight(), llvm::PBQPRAProblem::recordVReg(), llvm::ConstantAggrUniqueMap< ArrayType, ConstantArray >::remove(), llvm::LoopInfoBase< llvm::MachineBasicBlock, llvm::MachineLoop >::removeBlock(), llvm::MemoryDependenceAnalysis::removeInstruction(), llvm::SlotIndexes::removeMachineInstrFromMaps(), llvm::SlotIndexes::repairIndexesInRange(), llvm::SlotIndexes::replaceMachineInstrInMaps(), replaceUndefValuesInPhi(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::reset(), llvm::DIRef< T >::resolve(), reuseOrInsertFastDiv(), llvm::MachineSSAUpdater::RewriteUse(), llvm::SelectionDAGISel::runOnMachineFunction(), selectIncomingValueForBlock(), shouldAddODRHash(), SortNonLocalDepInfoCache(), llvm::X86InstrInfo::unfoldMemoryOperand(), llvm::ScalarEvolution::verifyAnalysis(), and llvm::AsmPrinter::~AsmPrinter().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> const_iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::end () const inline
Definition at line 63 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> bool llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::erase (const KeyT & Val) inline
Definition at line 190 of file DenseMap.h.
Referenced by llvm::ValueMapCallbackVH< KeyT, ValueT, Config >::allUsesReplacedWith(), llvm::LoopInfoBase< llvm::MachineBasicBlock, llvm::MachineLoop >::changeLoopFor(), llvm::ObjectSizeOffsetEvaluator::compute(), llvm::ValueMapCallbackVH< KeyT, ValueT, Config >::deleted(), llvm::SCEVAddRecExpr::delinearize(), llvm::DenseSet< llvm::Value * >::erase(), llvm::ValueMap< const BasicBlock *, void * >::erase(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::eraseNode(), llvm::Value::getContext(), llvm::isAllocaPromotable(), pushDepHeight(), regsAreCompatible(), llvm::ConstantAggrUniqueMap< ArrayType, ConstantArray >::remove(), llvm::LoopInfoBase< llvm::MachineBasicBlock, llvm::MachineLoop >::removeBlock(), llvm::MemoryDependenceAnalysis::removeInstruction(), llvm::SlotIndexes::removeMachineInstrFromMaps(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::removeNode(), llvm::SlotIndexes::replaceMachineInstrInMaps(), llvm::scc_iterator< GraphT, GT >::ReplaceNode(), llvm::Value::setName(), llvm::Function::setPrefixData(), SortNonLocalDepInfoCache(), and llvm::Function::~Function().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::erase (iterator I) inline
Definition at line 201 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::find (const KeyT & Val) inline
Definition at line 108 of file DenseMap.h.
Referenced by llvm::ValueMapCallbackVH< KeyT, ValueT, Config >::allUsesReplacedWith(), llvm::DwarfDebug::beginFunction(), llvm::bypassSlowDivision(), CheckForLiveRegDef(), llvm::PMTopLevelManager::collectLastUses(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::compare(), llvm::ObjectSizeOffsetEvaluator::compute(), llvm::DwarfException::ComputeCallSiteTable(), llvm::SelectionDAGBuilder::CopyToExportRegsIfNeeded(), llvm::PPCRegisterInfo::eliminateFrameIndex(), llvm::DWARFFormValue::extractValue(), llvm::FastISel::FastEmitBranch(), llvm::DenseSet< llvm::Value * >::find(), llvm::MCObjectSymbolizer::findRelocationAt(), llvm::ConstantAggrUniqueMap< ArrayType, ConstantArray >::freeConstants(), llvm::ValueEnumerator::getAttributeGroupID(), llvm::ValueEnumerator::getAttributeID(), getComparePred(), llvm::BranchProbabilityInfo::getEdgeWeight(), llvm::GCModuleInfo::getFunctionInfo(), llvm::SlotIndexes::getIndexAfter(), llvm::SlotIndexes::getIndexBefore(), llvm::ARMJITInfo::getIndirectSymAddr(), llvm::ValueEnumerator::getInstructionID(), llvm::SlotIndexes::getInstructionIndex(), getMappedReg(), llvm::X86InstrInfo::getOpcodeAfterMemoryUnfold(), llvm::ARMFunctionInfo::getOriginalCPIdx(), llvm::ARMJITInfo::getPCLabelAddr(), llvm::Function::getPrefixData(), llvm::RegionInfo::getRegionFor(), getRegsUsedByPHIs(), llvm::SDDbgInfo::getSDDbgValues(), llvm::MCRegisterInfo::getSEHRegNum(), llvm::R600InstrInfo::getSrcs(), getTruncatedArgReg(), llvm::ValueEnumerator::getTypeID(), llvm::SelectionDAGBuilder::getValue(), llvm::ValueEnumerator::getValueID(), llvm::PMTopLevelManager::initializeAllAnalysisInfo(), llvm::SlotIndexes::insertMachineInstrInMaps(), llvm::FunctionLoweringInfo::InvalidatePHILiveOutRegInfo(), llvm::isAllocaPromotable(), llvm::AsmPrinter::isBlockOnlyReachableByFallthrough(), isLoadFromGOTOrConstantPool(), isOnlyUsedInEntryBlock(), llvm::FastISel::lookUpRegForValue(), llvm::FastISel::LowerArguments(), llvm::DWARFDebugLoc::parse(), llvm::DWARFDebugLine::parseStatementTable(), llvm::BitcodeReader::ParseTriple(), llvm::FileInfo::print(), promoteSingleBlockAlloca(), pushDepHeight(), llvm::PBQPRAProblem::recordVReg(), llvm::LoopInfoBase< llvm::MachineBasicBlock, llvm::MachineLoop >::removeBlock(), RemoveFromReverseMap(), llvm::MemoryDependenceAnalysis::removeInstruction(), llvm::SlotIndexes::removeMachineInstrFromMaps(), llvm::SlotIndexes::repairIndexesInRange(), llvm::SlotIndexes::replaceMachineInstrInMaps(), replaceUndefValuesInPhi(), llvm::DIRef< T >::resolve(), reuseOrInsertFastDiv(), llvm::SelectionDAGISel::runOnMachineFunction(), selectIncomingValueForBlock(), SortNonLocalDepInfoCache(), llvm::X86InstrInfo::unfoldMemoryOperand(), and UpdateCPSRUse().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> const_iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::find (const KeyT & Val) const inline
Definition at line 114 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> template<class LookupKeyT > iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::find_as (const LookupKeyT & Val) inline
Alternate version of find() which allows a different, and possibly less expensive, key type. The DenseMapInfo is responsible for supplying methods getHashValue(LookupKeyT) and isEqual(LookupKeyT, KeyT) for each key type used.
Definition at line 127 of file DenseMap.h.
Referenced by llvm::ValueMap< const BasicBlock *, void * >::count(), llvm::ValueMap< const BasicBlock *, void * >::erase(), llvm::ValueMap< const BasicBlock *, void * >::find(), llvm::ConstantAggrUniqueMap< ArrayType, ConstantArray >::find(), llvm::FunctionType::get(), llvm::StructType::get(), llvm::ConstantAggrUniqueMap< ArrayType, ConstantArray >::getOrCreate(), and llvm::ValueMap< const BasicBlock *, void * >::lookup().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> template<class LookupKeyT > const_iterator llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::find_as (const LookupKeyT & Val) const inline
Definition at line 134 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> value_type& llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::FindAndConstruct (const KeyT & Key) inline
Definition at line 209 of file DenseMap.h.
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), llvm::ValueMap< const BasicBlock *, void * >::FindAndConstruct(), and llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT >, KeyT, ValueT, KeyInfoT >::operator[]().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> static const KeyT llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::getEmptyKey () inline static protected
Definition at line 340 of file DenseMap.h.
Referenced by llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT >, KeyT, ValueT, KeyInfoT >::clear(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT >, KeyT, ValueT, KeyInfoT >::copyFrom(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT >, KeyT, ValueT, KeyInfoT >::destroyAll(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT >, KeyT, ValueT, KeyInfoT >::getTombstoneKey(), llvm::SmallDenseMap< llvm::SDValue, llvm::SDValue, 8 >::grow(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT >, KeyT, ValueT, KeyInfoT >::initEmpty(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT >, KeyT, ValueT, KeyInfoT >::moveFromOldBuckets(), and llvm::SmallDenseMap< llvm::SDValue, llvm::SDValue, 8 >::swap().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> static unsigned llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::getHashValue (const KeyT & Val) inline static protected
Definition at line 333 of file DenseMap.h.
Referenced by llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT >, KeyT, ValueT, KeyInfoT >::getTombstoneKey().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> template<typename LookupKeyT > static unsigned llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::getHashValue (const LookupKeyT & Val) inline static protected
Definition at line 337 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> size_t llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::getMemorySize () const inline
Return the approximate size (in bytes) of the actual map. This is just the raw memory used by DenseMap. If entries are pointers to objects, the size of the referenced objects are not included.
Definition at line 527 of file DenseMap.h.
Referenced by llvm::DenseSet< llvm::Value * >::getMemorySize().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> const void* llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::getPointerIntoBucketsArray () const inline
getPointerIntoBucketsArray() - Return an opaque pointer into the buckets array. In conjunction with the previous method, this can be used to determine whether an insertion caused the DenseMap to reallocate.
Definition at line 245 of file DenseMap.h.
Referenced by llvm::Value::getContext(), and llvm::ValueMap< const BasicBlock *, void * >::getPointerIntoBucketsArray().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> static const KeyT llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::getTombstoneKey () inline static protected
Definition at line 343 of file DenseMap.h.
Referenced by llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT >, KeyT, ValueT, KeyInfoT >::clear(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT >, KeyT, ValueT, KeyInfoT >::copyFrom(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT >, KeyT, ValueT, KeyInfoT >::destroyAll(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT >, KeyT, ValueT, KeyInfoT >::erase(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT >, KeyT, ValueT, KeyInfoT >::getTombstoneKey(), llvm::SmallDenseMap< llvm::SDValue, llvm::SDValue, 8 >::grow(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT >, KeyT, ValueT, KeyInfoT >::moveFromOldBuckets(), and llvm::SmallDenseMap< llvm::SDValue, llvm::SDValue, 8 >::swap().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::initEmpty () inline protected
Definition at line 267 of file DenseMap.h.
Referenced by llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT >, KeyT, ValueT, KeyInfoT >::moveFromOldBuckets().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> std::pair<iterator, bool> llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::insert (const std::pair< KeyT, ValueT > & KV) inline
Definition at line 153 of file DenseMap.h.
Referenced by llvm::ARMJITInfo::addIndirectSymAddr(), llvm::ARMJITInfo::addPCLabelAddr(), llvm::ARMBaseInstrInfo::ARMBaseInstrInfo(), llvm::DenseMap< unsigned, unsigned >::DenseMap(), llvm::SplitEditor::dump(), llvm::ScheduleDAGMI::dumpSchedule(), llvm::DWARFContextInMemory::DWARFContextInMemory(), gatherIncomingValuesToPhi(), llvm::generateDITypeIdentifierMap(), llvm::MemoryDependenceAnalysis::getNonLocalPointerDependency(), getOpenCLAlignment(), getRegsUsedByPHIs(), llvm::DenseSet< llvm::Value * >::insert(), llvm::ValueMap< const BasicBlock *, void * >::insert(), llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT >, KeyT, ValueT, KeyInfoT >::insert(), insertFastDiv(), llvm::SlotIndexes::insertMachineInstrInMaps(), llvm::AsmPrinter::isBlockOnlyReachableByFallthrough(), isLoadFromGOTOrConstantPool(), pushDepHeight(), llvm::ARMFunctionInfo::recordCPEClone(), regsAreCompatible(), llvm::objcarc::ProvenanceAnalysis::related(), llvm::MemoryDependenceAnalysis::removeInstruction(), llvm::SlotIndexes::replaceMachineInstrInMaps(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::SlotIndexes::runOnMachineFunction(), selectIncomingValueForBlock(), AllocaSlices::SliceBuilder::SliceBuilder(), llvm::SmallDenseMap< llvm::SDValue, llvm::SDValue, 8 >::SmallDenseMap(), and SortNonLocalDepInfoCache().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> template<typename InputIt > void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::insert (InputIt I, InputIt E) inline
insert - Range insertion of pairs.
Definition at line 184 of file DenseMap.h.
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> bool llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::isPointerIntoBucketsArray (const void * Ptr) const inline
isPointerIntoBucketsArray - Return true if the specified pointer points somewhere into the DenseMap's array of buckets (i.e. either to a key or value in the DenseMap).
Definition at line 238 of file DenseMap.h.
Referenced by llvm::Value::getContext(), and llvm::ValueMap< const BasicBlock *, void * >::isPointerIntoBucketsArray().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> ValueT llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::lookup (const KeyT & Val) const inline
lookup - Return the entry for the specified key, or a default constructed value if no such entry exists.
Definition at line 143 of file DenseMap.h.
Referenced by llvm::SSAUpdaterImpl< UpdaterT >::BuildBlockList(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::getIDom(), llvm::LoopInfoBase< llvm::MachineBasicBlock, llvm::MachineLoop >::getLoopFor(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::getNode(), llvm::MachObjectWriter::getSectionAddress(), INITIALIZE_PASS(), llvm::DwarfDebug::isSubprogramContext(), llvm::SplitEditor::overlapIntv(), and pushDepHeight().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::moveFromOldBuckets (BucketT * OldBucketsBegin, BucketT * OldBucketsEnd) inline protected
Definition at line 278 of file DenseMap.h.
Referenced by llvm::DenseMap< unsigned, unsigned >::grow(), and llvm::SmallDenseMap< llvm::SDValue, llvm::SDValue, 8 >::grow().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> ValueT& llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::operator[] (const KeyT & Key) inline
Definition at line 217 of file DenseMap.h.
Referenced by llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT >, KeyT, ValueT, KeyInfoT >::operator[]().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::resize (size_t Size) inline
Grow the densemap so that it has at least Size buckets. Does not shrink.
Definition at line 73 of file DenseMap.h.
Referenced by llvm::DenseSet< llvm::Value * >::resize(), and llvm::ValueMap< const BasicBlock *, void * >::resize().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> unsigned llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::size () const inline
Definition at line 70 of file DenseMap.h.
Referenced by llvm::DominatorTreeBase< llvm::MachineBasicBlock >::compare(), llvm::Value::getContext(), getOpenCLAlignment(), llvm::ValueEnumerator::print(), llvm::SmallDenseMap< llvm::SDValue, llvm::SDValue, 8 >::shrink_and_clear(), llvm::DenseSet< llvm::Value * >::size(), llvm::ValueMap< const BasicBlock *, void * >::size(), SortNonLocalDepInfoCache(), and llvm::ScalarEvolution::verifyAnalysis().
template<typename DerivedT, typename KeyT, typename ValueT, typename KeyInfoT> void llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::swap (DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT > & RHS) inline protected
Definition at line 328 of file DenseMap.h.
Referenced by llvm::DenseMap< unsigned, unsigned >::DenseMap(), llvm::DenseMap< unsigned, unsigned >::operator=(), llvm::SmallDenseMap< llvm::SDValue, llvm::SDValue, 8 >::operator=(), and llvm::SmallDenseMap< llvm::SDValue, llvm::SDValue, 8 >::SmallDenseMap().
The documentation for this class was generated from the following file:
DenseMap.h