LLVM: llvm::DebugInfoFinder Class Reference
LLVM API Documentation
llvm::DebugInfoFinder Class Reference
#include <DebugInfo.h>
Public Types
typedef SmallVectorImpl< MDNode * >::const_iterator iterator
Public Member Functions
DebugInfoFinder ()
void processModule (const Module &M)
processModule - Process entire module and collect debug info.
void processDeclare (const Module &M, const DbgDeclareInst *DDI)
processDeclare - Process DbgDeclareInst.
void processValue (const Module &M, const DbgValueInst *DVI)
Process DbgValueInst.
void processLocation (const Module &M, DILocation Loc)
processLocation - Process DILocation.
void reset ()
Clear all lists.
iterator compile_unit_begin () const
iterator compile_unit_end () const
iterator subprogram_begin () const
iterator subprogram_end () const
iterator global_variable_begin () const
iterator global_variable_end () const
iterator type_begin () const
iterator type_end () const
iterator scope_begin () const
iterator scope_end () const
unsigned compile_unit_count () const
unsigned global_variable_count () const
unsigned subprogram_count () const
unsigned type_count () const
unsigned scope_count () const
Detailed Description
DebugInfoFinder tries to list all debug info MDNodes used in a module. To list debug info MDNodes used by an instruction, DebugInfoFinder uses processDeclare, processValue and processLocation to handle DbgDeclareInst, DbgValueInst and DbgLoc attached to instructions. processModule will go through all DICompileUnits in llvm.dbg.cu and list debug info MDNodes used by the CUs.
Definition at line 771 of file DebugInfo.h.
Member Typedef Documentation
typedef SmallVectorImpl<MDNode *>::const_iterator llvm::DebugInfoFinder::iterator
Definition at line 819 of file DebugInfo.h.
Constructor & Destructor Documentation
llvm::DebugInfoFinder::DebugInfoFinder () inline
Definition at line 773 of file DebugInfo.h.
Member Function Documentation
iterator llvm::DebugInfoFinder::compile_unit_begin () const inline
Definition at line 820 of file DebugInfo.h.
Referenced by INITIALIZE_PASS(), isContiguous(), StripSymbolNames(), and useFuncSeen().
unsigned llvm::DebugInfoFinder::compile_unit_count () const inline
Definition at line 831 of file DebugInfo.h.
iterator llvm::DebugInfoFinder::compile_unit_end () const inline
Definition at line 821 of file DebugInfo.h.
Referenced by INITIALIZE_PASS(), isContiguous(), StripSymbolNames(), and useFuncSeen().
iterator llvm::DebugInfoFinder::global_variable_begin () const inline
Definition at line 824 of file DebugInfo.h.
Referenced by INITIALIZE_PASS(), and isContiguous().
unsigned llvm::DebugInfoFinder::global_variable_count () const inline
Definition at line 832 of file DebugInfo.h.
iterator llvm::DebugInfoFinder::global_variable_end () const inline
Definition at line 825 of file DebugInfo.h.
Referenced by INITIALIZE_PASS(), and isContiguous().
void DebugInfoFinder::processDeclare (const Module & M, const DbgDeclareInst * DDI)
processDeclare - Process DbgDeclareInst.
Definition at line 1097 of file DebugInfo.cpp.
References llvm::dyn_cast(), llvm::Intrinsic::getType(), llvm::DbgDeclareInst::getVariable(), llvm::DIDescriptor::isVariable(), and N.
Referenced by isContiguous().
void DebugInfoFinder::processLocation (const Module & M, DILocation Loc)
processLocation - Process DILocation.
Definition at line 1005 of file DebugInfo.cpp.
References llvm::X86II::DA, llvm::DIType::getContext(), llvm::DISubprogram::getContext(), llvm::DILexicalBlock::getContext(), llvm::DINameSpace::getContext(), llvm::DITemplateTypeParameter::getContext(), llvm::DITemplateValueParameter::getContext(), llvm::DILocation::getOrigLocation(), llvm::DILexicalBlockFile::getScope(), llvm::DILocation::getScope(), llvm::DISubprogram::getTemplateParams(), llvm::DISubprogram::getType(), llvm::DITemplateTypeParameter::getType(), llvm::DITemplateValueParameter::getType(), llvm::DICompositeType::getTypeArray(), llvm::DIDerivedType::getTypeDerivedFrom(), i, I, llvm::DIDescriptor::isCompileUnit(), llvm::DIDescriptor::isCompositeType(), llvm::DIDescriptor::isDerivedType(), llvm::DIDescriptor::isLexicalBlock(), llvm::DIDescriptor::isLexicalBlockFile(), llvm::DIDescriptor::isNameSpace(), llvm::DIDescriptor::isSubprogram(), llvm::DIDescriptor::isTemplateTypeParameter(), llvm::DIDescriptor::isTemplateValueParameter(), llvm::DIDescriptor::isType(), and llvm::DIRef< T >::resolve().
Referenced by isContiguous().
void DebugInfoFinder::processModule (const Module & M)
processModule - Process entire module and collect debug info.
processModule - Process entire module and collect debug info anchors.
Definition at line 966 of file DebugInfo.cpp.
References llvm::DINameSpace::getContext(), llvm::DIArray::getElement(), llvm::DIImportedEntity::getEntity(), llvm::Module::getNamedMetadata(), llvm::DIArray::getNumElements(), and i.
Referenced by INITIALIZE_PASS(), StripSymbolNames(), and useFuncSeen().
void DebugInfoFinder::processValue (const Module & M, const DbgValueInst * DVI)
Process DbgValueInst.
Definition at line 1114 of file DebugInfo.cpp.
References llvm::dyn_cast(), llvm::Intrinsic::getType(), llvm::DbgValueInst::getVariable(), llvm::DIDescriptor::isVariable(), and N.
Referenced by isContiguous().
void DebugInfoFinder::reset ()
Clear all lists.
Definition at line 946 of file DebugInfo.cpp.
References llvm::generateDITypeIdentifierMap(), llvm::Module::getNamedMetadata(), and M.
iterator llvm::DebugInfoFinder::scope_begin () const inline
Definition at line 828 of file DebugInfo.h.
Referenced by isContiguous().
unsigned llvm::DebugInfoFinder::scope_count () const inline
Definition at line 835 of file DebugInfo.h.
iterator llvm::DebugInfoFinder::scope_end () const inline
Definition at line 829 of file DebugInfo.h.
Referenced by isContiguous().
iterator llvm::DebugInfoFinder::subprogram_begin () const inline
Definition at line 822 of file DebugInfo.h.
Referenced by INITIALIZE_PASS(), isContiguous(), and useFuncSeen().
unsigned llvm::DebugInfoFinder::subprogram_count () const inline
Definition at line 833 of file DebugInfo.h.
iterator llvm::DebugInfoFinder::subprogram_end () const inline
Definition at line 823 of file DebugInfo.h.
Referenced by INITIALIZE_PASS(), isContiguous(), and useFuncSeen().
iterator llvm::DebugInfoFinder::type_begin () const inline
Definition at line 826 of file DebugInfo.h.
Referenced by INITIALIZE_PASS(), and isContiguous().
unsigned llvm::DebugInfoFinder::type_count () const inline
Definition at line 834 of file DebugInfo.h.
iterator llvm::DebugInfoFinder::type_end () const inline
Definition at line 827 of file DebugInfo.h.
Referenced by INITIALIZE_PASS(), and isContiguous().
The documentation for this class was generated from the following files:
DebugInfo.h
DebugInfo.cpp