LLVM: llvm::AMDGPUSubtarget Class Reference
LLVM API Documentation
llvm::AMDGPUSubtarget Class Reference
#include <AMDGPUSubtarget.h>
Public Types
enum Generation {
R600 = 0, R700, EVERGREEN, NORTHERN_ISLANDS,
SOUTHERN_ISLANDS, SEA_ISLANDS
}
Public Member Functions
AMDGPUSubtarget (StringRef TT, StringRef CPU, StringRef FS)
const InstrItineraryData & getInstrItineraryData () const
virtual void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
bool is64bit () const
bool hasVertexCache () const
short getTexVTXClauseSize () const
enum Generation getGeneration () const
bool hasHWFP64 () const
bool hasCaymanISA () const
bool IsIRStructurizerEnabled () const
bool isIfCvtEnabled () const
virtual bool enableMachineScheduler () const
bool isTargetELF () const
std::string getDataLayout () const
std::string getDeviceName () const
virtual size_t getDefaultSize (uint32_t dim) const
bool dumpCode () const
bool r600ALUEncoding () const
Detailed Description
Definition at line 29 of file AMDGPUSubtarget.h.
Member Enumeration Documentation
enum llvm::AMDGPUSubtarget::Generation
Enumerator
R600
R700
EVERGREEN
NORTHERN_ISLANDS
SOUTHERN_ISLANDS
SEA_ISLANDS
Definition at line 31 of file AMDGPUSubtarget.h.
Constructor & Destructor Documentation
AMDGPUSubtarget::AMDGPUSubtarget (StringRef TT, StringRef CPU, StringRef FS)
Definition at line 24 of file AMDGPUSubtarget.cpp.
References ParseSubtargetFeatures(), and R600.
Member Function Documentation
bool llvm::AMDGPUSubtarget::dumpCode () const inline
Definition at line 81 of file AMDGPUSubtarget.h.
Referenced by llvm::AMDGPUAsmPrinter::runOnMachineFunction().
virtual bool llvm::AMDGPUSubtarget::enableMachineScheduler () const inline virtual
Definition at line 72 of file AMDGPUSubtarget.h.
References getDataLayout(), getDefaultSize(), getDeviceName(), getGeneration(), isTargetELF(), and NORTHERN_ISLANDS.
std::string AMDGPUSubtarget::getDataLayout () const
Definition at line 91 of file AMDGPUSubtarget.cpp.
References hasHWFP64(), is64bit(), and SOUTHERN_ISLANDS.
Referenced by enableMachineScheduler().
size_t AMDGPUSubtarget::getDefaultSize (uint32_t dim) const virtual
Definition at line 82 of file AMDGPUSubtarget.cpp.
Referenced by enableMachineScheduler().
std::string AMDGPUSubtarget::getDeviceName () const
Definition at line 118 of file AMDGPUSubtarget.cpp.
Referenced by enableMachineScheduler().
enum AMDGPUSubtarget::Generation AMDGPUSubtarget::getGeneration () const
Definition at line 58 of file AMDGPUSubtarget.cpp.
Referenced by llvm::AMDGPUTargetMachine::addAnalysisPasses(), llvm::AMDGPUTargetMachine::AMDGPUTargetMachine(), llvm::R600InstrInfo::buildSlotOfVectorInstruction(), llvm::createAMDGPUISelDag(), llvm::AMDGPUAsmPrinter::EmitProgramInfoSI(), enableMachineScheduler(), getInstrItineraryData(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), and llvm::AMDGPUTargetMachine::~AMDGPUTargetMachine().
const InstrItineraryData& llvm::AMDGPUSubtarget::getInstrItineraryData () const inline
Definition at line 60 of file AMDGPUSubtarget.h.
References llvm::X86II::FS, getGeneration(), getTexVTXClauseSize(), hasCaymanISA(), hasHWFP64(), hasVertexCache(), is64bit(), isIfCvtEnabled(), IsIRStructurizerEnabled(), and ParseSubtargetFeatures().
short AMDGPUSubtarget::getTexVTXClauseSize () const
Definition at line 54 of file AMDGPUSubtarget.cpp.
Referenced by getInstrItineraryData(), and llvm::R600SchedStrategy::initialize().
bool AMDGPUSubtarget::hasCaymanISA () const
Definition at line 66 of file AMDGPUSubtarget.cpp.
Referenced by getInstrItineraryData(), and llvm::R600InstrInfo::isTransOnly().
bool AMDGPUSubtarget::hasHWFP64 () const
Definition at line 62 of file AMDGPUSubtarget.cpp.
Referenced by getDataLayout(), and getInstrItineraryData().
bool AMDGPUSubtarget::hasVertexCache () const
Definition at line 50 of file AMDGPUSubtarget.cpp.
Referenced by getInstrItineraryData(), llvm::R600InstrInfo::usesTextureCache(), and llvm::R600InstrInfo::usesVertexCache().
bool AMDGPUSubtarget::is64bit () const
Definition at line 46 of file AMDGPUSubtarget.cpp.
Referenced by getDataLayout(), and getInstrItineraryData().
bool AMDGPUSubtarget::isIfCvtEnabled () const
Definition at line 74 of file AMDGPUSubtarget.cpp.
Referenced by llvm::AMDGPUTargetMachine::addAnalysisPasses(), and getInstrItineraryData().
bool AMDGPUSubtarget::IsIRStructurizerEnabled () const
Definition at line 70 of file AMDGPUSubtarget.cpp.
Referenced by llvm::AMDGPUTargetMachine::addAnalysisPasses(), and getInstrItineraryData().
bool AMDGPUSubtarget::isTargetELF () const
Definition at line 78 of file AMDGPUSubtarget.cpp.
Referenced by enableMachineScheduler().
virtual void llvm::AMDGPUSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS) virtual
Referenced by AMDGPUSubtarget(), and getInstrItineraryData().
bool llvm::AMDGPUSubtarget::r600ALUEncoding () const inline
Definition at line 82 of file AMDGPUSubtarget.h.
The documentation for this class was generated from the following files:
AMDGPUSubtarget.h
AMDGPUSubtarget.cpp