LLVM: llvm::SystemZTargetMachine Class Reference
LLVM API Documentation
llvm::SystemZTargetMachine Class Reference
#include <SystemZTargetMachine.h>
Public Member Functions
SystemZTargetMachine (const Target &T, StringRef TT, StringRef CPU, StringRef FS, const TargetOptions &Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
virtual const TargetFrameLowering * getFrameLowering () const LLVM_OVERRIDE
virtual const SystemZInstrInfo * getInstrInfo () const LLVM_OVERRIDE
virtual const SystemZSubtarget * getSubtargetImpl () const LLVM_OVERRIDE
virtual const DataLayout * getDataLayout () const LLVM_OVERRIDE
virtual const SystemZRegisterInfo * getRegisterInfo () const LLVM_OVERRIDE
virtual const SystemZTargetLowering * getTargetLowering () const LLVM_OVERRIDE
virtual const TargetSelectionDAGInfo * getSelectionDAGInfo () const LLVM_OVERRIDE
virtual TargetPassConfig * createPassConfig (PassManagerBase &PM) LLVM_OVERRIDE
Public Member Functions inherited from llvm::LLVMTargetMachine
virtual void addAnalysisPasses (PassManagerBase &PM)
Register analysis passes for this target with a pass manager.
virtual bool addPassesToEmitFile (PassManagerBase &PM, formatted_raw_ostream &Out, CodeGenFileType FileType, bool DisableVerify=true, AnalysisID StartAfter=0, AnalysisID StopAfter=0)
virtual bool addPassesToEmitMachineCode (PassManagerBase &PM, JITCodeEmitter &MCE, bool DisableVerify=true)
virtual bool addPassesToEmitMC (PassManagerBase &PM, MCContext *&Ctx, raw_ostream &OS, bool DisableVerify=true)
virtual bool addCodeEmitter (PassManagerBase &, JITCodeEmitter &)
Public Member Functions inherited from llvm::TargetMachine
virtual ~TargetMachine ()
const Target & getTarget () const
const StringRef getTargetTriple () const
const StringRef getTargetCPU () const
const StringRef getTargetFeatureString () const
void resetTargetOptions (const MachineFunction *MF) const
Reset the target options based on the function's attributes.
const MCAsmInfo * getMCAsmInfo () const
template<typename STC >
const STC & getSubtarget () const
virtual const TargetIntrinsicInfo * getIntrinsicInfo () const
virtual TargetJITInfo * getJITInfo ()
virtual const InstrItineraryData * getInstrItineraryData () const
bool hasMCRelaxAll () const
void setMCRelaxAll (bool Value)
bool hasMCSaveTempLabels () const
void setMCSaveTempLabels (bool Value)
bool hasMCNoExecStack () const
hasMCNoExecStack - Check whether an executable stack is not needed.
void setMCNoExecStack (bool Value)
setMCNoExecStack - Set whether an executabel stack is not needed.
bool hasMCUseLoc () const
hasMCUseLoc - Check whether we should use dwarf's .loc directive.
void setMCUseLoc (bool Value)
setMCUseLoc - Set whether all we should use dwarf's .loc directive.
bool hasMCUseCFI () const
hasMCUseCFI - Check whether we should use dwarf's .cfi_* directives.
void setMCUseCFI (bool Value)
setMCUseCFI - Set whether all we should use dwarf's .cfi_* directives.
bool hasMCUseDwarfDirectory () const
void setMCUseDwarfDirectory (bool Value)
Reloc::Model getRelocationModel () const
CodeModel::Model getCodeModel () const
TLSModel::Model getTLSModel (const GlobalValue *GV) const
CodeGenOpt::Level getOptLevel () const
void setOptLevel (CodeGenOpt::Level Level) const
Overrides the optimization level.
void setFastISel (bool Enable)
bool shouldPrintMachineCode () const
Additional Inherited Members
Public Types inherited from llvm::TargetMachine
enum CodeGenFileType { CGFT_AssemblyFile, CGFT_ObjectFile, CGFT_Null }
Static Public Member Functions inherited from llvm::TargetMachine
static bool getAsmVerbosityDefault ()
static void setAsmVerbosityDefault (bool)
static bool getDataSections ()
static bool getFunctionSections ()
static void setDataSections (bool)
setDataSections - Set if the data are emit into separate sections.
static void setFunctionSections (bool)
Public Attributes inherited from llvm::TargetMachine
TargetOptions Options
Protected Member Functions inherited from llvm::LLVMTargetMachine
LLVMTargetMachine (const Target &T, StringRef TargetTriple, StringRef CPU, StringRef FS, TargetOptions Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
void initAsmInfo ()
Protected Member Functions inherited from llvm::TargetMachine
TargetMachine (const Target &T, StringRef TargetTriple, StringRef CPU, StringRef FS, const TargetOptions &Options)
Protected Attributes inherited from llvm::TargetMachine
const Target & TheTarget
TheTarget - The Target that this machine was created for.
std::string TargetTriple
std::string TargetCPU
std::string TargetFS
MCCodeGenInfo * CodeGenInfo
const MCAsmInfo * AsmInfo
unsigned MCRelaxAll: 1
unsigned MCNoExecStack: 1
unsigned MCSaveTempLabels: 1
unsigned MCUseLoc: 1
unsigned MCUseCFI: 1
unsigned MCUseDwarfDirectory: 1
Detailed Description
Definition at line 30 of file SystemZTargetMachine.h.
Constructor & Destructor Documentation
SystemZTargetMachine::SystemZTargetMachine (const Target & T, StringRef TT, StringRef CPU, StringRef FS, const TargetOptions & Options, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
Definition at line 22 of file SystemZTargetMachine.cpp.
References llvm::TargetPassConfig::addIRPasses(), llvm::createPartiallyInlineLibCallsPass(), llvm::createSystemZElimComparePass(), llvm::createSystemZISelDag(), llvm::createSystemZLongBranchPass(), llvm::createSystemZShortenInstPass(), llvm::TargetMachine::getOptLevel(), getSubtargetImpl(), llvm::IfConverterID, llvm::LLVMTargetMachine::initAsmInfo(), LLVM_OVERRIDE, llvm::CodeGenOpt::None, and llvm::SystemZISD::TM.
Member Function Documentation
TargetPassConfig * SystemZTargetMachine::createPassConfig (PassManagerBase & PM) virtual
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
createPassConfig - Create a pass configuration object to be used by addPassToEmitX methods for generating a pipeline of CodeGen passes.
Targets may override this to extend TargetPassConfig.
Reimplemented from llvm::LLVMTargetMachine.
Definition at line 106 of file SystemZTargetMachine.cpp.
Referenced by getSelectionDAGInfo().
virtual const DataLayout* llvm::SystemZTargetMachine::getDataLayout () const inline virtual
Reimplemented from llvm::TargetMachine.
Definition at line 54 of file SystemZTargetMachine.h.
virtual const TargetFrameLowering* llvm::SystemZTargetMachine::getFrameLowering () const inline virtual
Reimplemented from llvm::TargetMachine.
Definition at line 45 of file SystemZTargetMachine.h.
Referenced by llvm::SystemZTargetLowering::LowerFormalArguments().
virtual const SystemZInstrInfo* llvm::SystemZTargetMachine::getInstrInfo () const inline virtual
Reimplemented from llvm::TargetMachine.
Definition at line 48 of file SystemZTargetMachine.h.
Referenced by llvm::SystemZRegisterInfo::eliminateFrameIndex(), and forceReg().
virtual const SystemZRegisterInfo* llvm::SystemZTargetMachine::getRegisterInfo () const inline virtual
getRegisterInfo - If register information is available, return it. If not, return null. This is kept separate from RegInfo until RegInfo has details of graph coloring register allocation removed from it.
Reimplemented from llvm::TargetMachine.
Definition at line 57 of file SystemZTargetMachine.h.
References llvm::SystemZInstrInfo::getRegisterInfo().
Referenced by addSavedGPR(), and llvm::SystemZInstrInfo::optimizeCompareInstr().
virtual const TargetSelectionDAGInfo* llvm::SystemZTargetMachine::getSelectionDAGInfo () const inline virtual
Reimplemented from llvm::TargetMachine.
Definition at line 63 of file SystemZTargetMachine.h.
References createPassConfig(), and LLVM_OVERRIDE.
virtual const SystemZSubtarget* llvm::SystemZTargetMachine::getSubtargetImpl () const inline virtual
getSubtargetImpl - virtual method implemented by subclasses that returns a reference to that target's TargetSubtargetInfo-derived member variable.
Reimplemented from llvm::TargetMachine.
Definition at line 51 of file SystemZTargetMachine.h.
Referenced by forceReg(), llvm::SystemZInstrInfo::isPredicable(), llvm::SystemZInstrInfo::PredicateInstruction(), and SystemZTargetMachine().
virtual const SystemZTargetLowering* llvm::SystemZTargetMachine::getTargetLowering () const inline virtual
Reimplemented from llvm::TargetMachine.
Definition at line 60 of file SystemZTargetMachine.h.
The documentation for this class was generated from the following files:
SystemZTargetMachine.h
SystemZTargetMachine.cpp