LLVM: llvm::ObjectBuffer Class Reference
LLVM API Documentation
llvm::ObjectBuffer Class Reference
#include <ObjectBuffer.h>
Public Member Functions
ObjectBuffer ()
ObjectBuffer (MemoryBuffer *Buf)
virtual ~ObjectBuffer ()
MemoryBuffer * getMemBuffer () const
const char * getBufferStart () const
size_t getBufferSize () const
StringRef getBuffer () const
Protected Attributes
OwningPtr< MemoryBuffer > Buffer
Detailed Description
ObjectBuffer - This class acts as a container for the memory buffer used during generation and loading of executable objects using MCJIT and RuntimeDyld. The underlying memory for the object will be owned by the ObjectBuffer instance throughout its lifetime. The getMemBuffer() method provides a way to create a MemoryBuffer wrapper object instance to be owned by other classes (such as ObjectFile) as needed, but the MemoryBuffer instance returned does not own the actual memory it points to.
Definition at line 32 of file ObjectBuffer.h.
Constructor & Destructor Documentation
llvm::ObjectBuffer::ObjectBuffer () inline
Definition at line 35 of file ObjectBuffer.h.
llvm::ObjectBuffer::ObjectBuffer (MemoryBuffer * Buf) inline
Definition at line 36 of file ObjectBuffer.h.
virtual llvm::ObjectBuffer::~ObjectBuffer () inline virtual
Definition at line 37 of file ObjectBuffer.h.
Member Function Documentation
StringRef llvm::ObjectBuffer::getBuffer () const inline
Definition at line 48 of file ObjectBuffer.h.
References Buffer.
Referenced by llvm::RuntimeDyld::loadObject().
size_t llvm::ObjectBuffer::getBufferSize () const inline
Definition at line 47 of file ObjectBuffer.h.
References Buffer.
Referenced by __jit_debug_register_code(), llvm::RuntimeDyldELF::createObjectImage(), llvm::RuntimeDyldMachO::isCompatibleFormat(), and llvm::RuntimeDyldELF::isCompatibleFormat().
const char* llvm::ObjectBuffer::getBufferStart () const inline
Definition at line 46 of file ObjectBuffer.h.
References Buffer.
Referenced by __jit_debug_register_code(), llvm::RuntimeDyldELF::createObjectImage(), llvm::RuntimeDyldMachO::isCompatibleFormat(), llvm::RuntimeDyldELF::isCompatibleFormat(), and llvm::RuntimeDyldImpl::loadObject().
MemoryBuffer* llvm::ObjectBuffer::getMemBuffer () const inline
getMemBuffer - Like MemoryBuffer::getMemBuffer() this function returns a pointer to an object that is owned by the caller. However, the caller does not take ownership of the underlying memory.
Definition at line 42 of file ObjectBuffer.h.
References Buffer, and llvm::MemoryBuffer::getMemBuffer().
Referenced by llvm::RuntimeDyldELF::createObjectImage(), and llvm::MCJIT::emitObject().
Member Data Documentation
OwningPtr<MemoryBuffer> llvm::ObjectBuffer::Buffer protected
Definition at line 52 of file ObjectBuffer.h.
Referenced by llvm::ObjectBufferStream::flush(), getBuffer(), getBufferSize(), getBufferStart(), and getMemBuffer().
The documentation for this class was generated from the following files:
ObjectBuffer.h
ExecutionEngine.cpp