LLVM: llvm::MCELFObjectTargetWriter Class Reference
LLVM API Documentation
llvm::MCELFObjectTargetWriter Class Reference abstract
#include <MCELFObjectWriter.h>
Public Member Functions
virtual ~MCELFObjectTargetWriter ()
virtual unsigned GetRelocType (const MCValue &Target, const MCFixup &Fixup, bool IsPCRel, bool IsRelocWithSymbol, int64_t Addend) const =0
virtual const MCSymbol * ExplicitRelSym (const MCAssembler &Asm, const MCValue &Target, const MCFragment &F, const MCFixup &Fixup, bool IsPCRel) const
virtual const MCSymbol * undefinedExplicitRelSym (const MCValue &Target, const MCFixup &Fixup, bool IsPCRel) const
virtual void sortRelocs (const MCAssembler &Asm, std::vector< ELFRelocationEntry > &Relocs)
unsigned getRType (uint32_t Type) const
unsigned getRType2 (uint32_t Type) const
unsigned getRType3 (uint32_t Type) const
unsigned getRSsym (uint32_t Type) const
unsigned setRType (unsigned Value, unsigned Type) const
unsigned setRType2 (unsigned Value, unsigned Type) const
unsigned setRType3 (unsigned Value, unsigned Type) const
unsigned setRSsym (unsigned Value, unsigned Type) const
Accessors
uint8_t getOSABI () const
uint16_t getEMachine () const
bool hasRelocationAddend () const
bool is64Bit () const
bool isN64 () const
Static Public Member Functions
static uint8_t getOSABI (Triple::OSType OSType)
Protected Member Functions
MCELFObjectTargetWriter (bool Is64Bit_, uint8_t OSABI_, uint16_t EMachine_, bool HasRelocationAddend, bool IsN64=false)
Detailed Description
Definition at line 47 of file MCELFObjectWriter.h.
Constructor & Destructor Documentation
MCELFObjectTargetWriter::MCELFObjectTargetWriter (bool Is64Bit_, uint8_t OSABI_, uint16_t EMachine_, bool HasRelocationAddend, bool IsN64 = false) protected
Definition at line 17 of file MCELFObjectTargetWriter.cpp.
virtual llvm::MCELFObjectTargetWriter::~MCELFObjectTargetWriter () inline virtual
Definition at line 72 of file MCELFObjectWriter.h.
References llvm::HexStyle::Asm, F(), and llvm::ELFRelocationEntry::Fixup.
Member Function Documentation
const MCSymbol * MCELFObjectTargetWriter::ExplicitRelSym (const MCAssembler & Asm, const MCValue & Target, const MCFragment & F, const MCFixup & Fixup, bool IsPCRel) const virtual
Definition at line 27 of file MCELFObjectTargetWriter.cpp.
uint16_t llvm::MCELFObjectTargetWriter::getEMachine () const inline
Definition at line 92 of file MCELFObjectWriter.h.
static uint8_t llvm::MCELFObjectTargetWriter::getOSABI (Triple::OSType OSType) inline static
Definition at line 61 of file MCELFObjectWriter.h.
References llvm::ELF::ELFOSABI_FREEBSD, llvm::ELF::ELFOSABI_LINUX, llvm::ELF::ELFOSABI_NONE, llvm::Triple::FreeBSD, and llvm::Triple::Linux.
uint8_t llvm::MCELFObjectTargetWriter::getOSABI () const inline
Definition at line 91 of file MCELFObjectWriter.h.
Referenced by adjustFixupValue(), llvm::createARMAsmBackend(), llvm::createPPCAsmBackend(), llvm::createSystemZMCAsmBackend(), llvm::createX86_32AsmBackend(), and llvm::createX86_64AsmBackend().
virtual unsigned llvm::MCELFObjectTargetWriter::GetRelocType (const MCValue & Target, const MCFixup & Fixup, bool IsPCRel, bool IsRelocWithSymbol, int64_t Addend) const pure virtual
unsigned llvm::MCELFObjectTargetWriter::getRSsym (uint32_t Type) const inline
Definition at line 119 of file MCELFObjectWriter.h.
References R_SSYM_SHIFT.
unsigned llvm::MCELFObjectTargetWriter::getRType (uint32_t Type) const inline
Definition at line 110 of file MCELFObjectWriter.h.
References R_TYPE_SHIFT.
unsigned llvm::MCELFObjectTargetWriter::getRType2 (uint32_t Type) const inline
Definition at line 113 of file MCELFObjectWriter.h.
References R_TYPE2_SHIFT.
unsigned llvm::MCELFObjectTargetWriter::getRType3 (uint32_t Type) const inline
Definition at line 116 of file MCELFObjectWriter.h.
References R_TYPE3_SHIFT.
bool llvm::MCELFObjectTargetWriter::hasRelocationAddend () const inline
Definition at line 93 of file MCELFObjectWriter.h.
bool llvm::MCELFObjectTargetWriter::is64Bit () const inline
Definition at line 94 of file MCELFObjectWriter.h.
bool llvm::MCELFObjectTargetWriter::isN64 () const inline
Definition at line 95 of file MCELFObjectWriter.h.
unsigned llvm::MCELFObjectTargetWriter::setRSsym (unsigned Value, unsigned Type) const inline
Definition at line 133 of file MCELFObjectWriter.h.
References llvm::createELFObjectWriter(), R_SSYM_MASK, and R_SSYM_SHIFT.
unsigned llvm::MCELFObjectTargetWriter::setRType (unsigned Value, unsigned Type) const inline
Definition at line 124 of file MCELFObjectWriter.h.
References R_TYPE_MASK, and R_TYPE_SHIFT.
unsigned llvm::MCELFObjectTargetWriter::setRType2 (unsigned Value, unsigned Type) const inline
Definition at line 127 of file MCELFObjectWriter.h.
References R_TYPE2_MASK, and R_TYPE2_SHIFT.
unsigned llvm::MCELFObjectTargetWriter::setRType3 (unsigned Value, unsigned Type) const inline
Definition at line 130 of file MCELFObjectWriter.h.
References R_TYPE3_MASK, and R_TYPE3_SHIFT.
void MCELFObjectTargetWriter::sortRelocs (const MCAssembler & Asm, std::vector< ELFRelocationEntry > & Relocs) virtual
Definition at line 58 of file MCELFObjectTargetWriter.cpp.
References llvm::array_pod_sort(), and cmpRel().
const MCSymbol * MCELFObjectTargetWriter::undefinedExplicitRelSym (const MCValue & Target, const MCFixup & Fixup, bool IsPCRel) const virtual
Definition at line 35 of file MCELFObjectTargetWriter.cpp.
References llvm::MCSymbol::AliasedSymbol(), llvm::MCValue::getSymA(), llvm::MCSymbolRefExpr::getSymbol(), and llvm::ARMBuildAttrs::Symbol.
The documentation for this class was generated from the following files:
MCELFObjectWriter.h
MCELFObjectTargetWriter.cpp