LLVM: llvm::TypeFinder Class Reference
LLVM API Documentation
llvm::TypeFinder Class Reference
#include <TypeFinder.h>
Public Types
typedef std::vector< StructType * >::iterator iterator
typedef std::vector< StructType * >::const_iterator const_iterator
Public Member Functions
TypeFinder ()
void run (const Module &M, bool onlyNamed)
void clear ()
iterator begin ()
iterator end ()
const_iterator begin () const
const_iterator end () const
bool empty () const
size_t size () const
iterator erase (iterator I, iterator E)
StructType *& operator[] (unsigned Idx)
Detailed Description
TypeFinder - Walk over a module, identifying all of the types that are used by the module.
Definition at line 30 of file TypeFinder.h.
Member Typedef Documentation
typedef std::vector<StructType*>::const_iterator llvm::TypeFinder::const_iterator
Definition at line 46 of file TypeFinder.h.
typedef std::vector<StructType*>::iterator llvm::TypeFinder::iterator
Definition at line 45 of file TypeFinder.h.
Constructor & Destructor Documentation
llvm::TypeFinder::TypeFinder () inline
Definition at line 40 of file TypeFinder.h.
References clear(), M, and run().
Member Function Documentation
iterator llvm::TypeFinder::begin () inline
Definition at line 48 of file TypeFinder.h.
Referenced by isLessConstraining(), and llvm::Linker::Linker().
const_iterator llvm::TypeFinder::begin () const inline
Definition at line 51 of file TypeFinder.h.
void TypeFinder::clear ()
Definition at line 88 of file TypeFinder.cpp.
References llvm::SmallVectorBase::empty(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::Value::getType(), i, I, M, llvm::User::op_begin(), llvm::User::op_end(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::Type::subtype_rbegin(), and llvm::Type::subtype_rend().
Referenced by TypeFinder().
bool llvm::TypeFinder::empty () const inline
Definition at line 54 of file TypeFinder.h.
Referenced by llvm::AssemblyWriter::printTypeIdentities().
iterator llvm::TypeFinder::end () inline
Definition at line 49 of file TypeFinder.h.
Referenced by isLessConstraining(), and llvm::Linker::Linker().
const_iterator llvm::TypeFinder::end () const inline
Definition at line 52 of file TypeFinder.h.
iterator llvm::TypeFinder::erase (iterator I, iterator E) inline
Definition at line 56 of file TypeFinder.h.
StructType*& llvm::TypeFinder::operator[] (unsigned Idx) inline
Definition at line 58 of file TypeFinder.h.
void TypeFinder::run (const Module & M, bool onlyNamed)
Definition at line 23 of file TypeFinder.cpp.
References llvm::Module::alias_begin(), llvm::Module::alias_end(), BB, llvm::Module::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::Module::end(), llvm::Instruction::getAllMetadataOtherThanDebugLoc(), llvm::NamedMDNode::getNumOperands(), llvm::NamedMDNode::getOperand(), llvm::Value::getType(), llvm::Module::global_begin(), llvm::Module::global_end(), i, I, llvm::Module::named_metadata_begin(), llvm::Module::named_metadata_end(), llvm::User::op_begin(), llvm::User::op_end(), and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by isLessConstraining(), llvm::Linker::Linker(), StripTypeNames(), and TypeFinder().
size_t llvm::TypeFinder::size () const inline
Definition at line 55 of file TypeFinder.h.
Referenced by isLessConstraining(), llvm::AssemblyWriter::printTypeIdentities(), and StripTypeNames().
The documentation for this class was generated from the following files:
TypeFinder.h
TypeFinder.cpp