LLVM: llvm::object::RelocVisitor Class Reference
LLVM API Documentation
llvm::object::RelocVisitor Class Reference
Base class for object file relocation visitors.
#include <RelocVisitor.h>
Public Member Functions
RelocVisitor (StringRef FileFormat)
RelocToApply visit (uint32_t RelocType, RelocationRef R, uint64_t SecAddr=0, uint64_t Value=0)
bool error ()
Detailed Description
Base class for object file relocation visitors.
Definition at line 42 of file RelocVisitor.h.
Constructor & Destructor Documentation
llvm::object::RelocVisitor::RelocVisitor (StringRef FileFormat) inline explicit
Definition at line 44 of file RelocVisitor.h.
Member Function Documentation
bool llvm::object::RelocVisitor::error () inline
Definition at line 131 of file RelocVisitor.h.
References llvm::object::getELFRelocationAddend(), llvm::object::RelocationRef::getObjectFile(), llvm::object::RelocationRef::getOffset(), llvm::object::RelocationRef::getRawDataRefImpl(), llvm::object::ELFObjectFile< ELFT >::getRelocationAddend(), and llvm::object::RelocToApply::RelocToApply().
RelocToApply llvm::object::RelocVisitor::visit (uint32_t RelocType, RelocationRef R, uint64_t SecAddr = 0, uint64_t Value = 0) inline
Definition at line 50 of file RelocVisitor.h.
References llvm::ELF::R_386_32, llvm::ELF::R_386_NONE, llvm::ELF::R_386_PC32, llvm::ELF::R_390_32, llvm::ELF::R_390_64, llvm::ELF::R_AARCH64_ABS32, llvm::ELF::R_AARCH64_ABS64, llvm::ELF::R_MIPS_32, llvm::ELF::R_PPC64_ADDR32, llvm::ELF::R_PPC64_ADDR64, llvm::ELF::R_PPC_ADDR32, llvm::ELF::R_X86_64_32, llvm::ELF::R_X86_64_32S, llvm::ELF::R_X86_64_64, llvm::ELF::R_X86_64_NONE, llvm::ELF::R_X86_64_PC32, and llvm::object::RelocToApply::RelocToApply().
The documentation for this class was generated from the following file:
RelocVisitor.h