LLVM: llvm::object::MachOObjectFile Class Reference
LLVM API Documentation
llvm::object::MachOObjectFile Class Reference
#include <MachO.h>
Classes
struct LoadCommandInfo
Public Member Functions
MachOObjectFile (MemoryBuffer *Object, bool IsLittleEndian, bool Is64Bits, error_code &ec)
virtual error_code getSymbolNext (DataRefImpl Symb, SymbolRef &Res) const
virtual error_code getSymbolName (DataRefImpl Symb, StringRef &Res) const
virtual error_code getSymbolAddress (DataRefImpl Symb, uint64_t &Res) const
virtual error_code getSymbolFileOffset (DataRefImpl Symb, uint64_t &Res) const
virtual error_code getSymbolAlignment (DataRefImpl Symb, uint32_t &Res) const
virtual error_code getSymbolSize (DataRefImpl Symb, uint64_t &Res) const
virtual error_code getSymbolType (DataRefImpl Symb, SymbolRef::Type &Res) const
virtual error_code getSymbolFlags (DataRefImpl Symb, uint32_t &Res) const
virtual error_code getSymbolSection (DataRefImpl Symb, section_iterator &Res) const
virtual error_code getSymbolValue (DataRefImpl Symb, uint64_t &Val) const
virtual error_code getSectionNext (DataRefImpl Sec, SectionRef &Res) const
virtual error_code getSectionName (DataRefImpl Sec, StringRef &Res) const
virtual error_code getSectionAddress (DataRefImpl Sec, uint64_t &Res) const
virtual error_code getSectionSize (DataRefImpl Sec, uint64_t &Res) const
virtual error_code getSectionContents (DataRefImpl Sec, StringRef &Res) const
virtual error_code getSectionAlignment (DataRefImpl Sec, uint64_t &Res) const
virtual error_code isSectionText (DataRefImpl Sec, bool &Res) const
virtual error_code isSectionData (DataRefImpl Sec, bool &Res) const
virtual error_code isSectionBSS (DataRefImpl Sec, bool &Res) const
virtual error_code isSectionRequiredForExecution (DataRefImpl Sec, bool &Res) const
virtual error_code isSectionVirtual (DataRefImpl Sec, bool &Res) const
virtual error_code isSectionZeroInit (DataRefImpl Sec, bool &Res) const
virtual error_code isSectionReadOnlyData (DataRefImpl Sec, bool &Res) const
virtual error_code sectionContainsSymbol (DataRefImpl Sec, DataRefImpl Symb, bool &Result) const
virtual relocation_iterator section_rel_begin (DataRefImpl Sec) const
virtual relocation_iterator section_rel_end (DataRefImpl Sec) const
virtual error_code getRelocationNext (DataRefImpl Rel, RelocationRef &Res) const
virtual error_code getRelocationAddress (DataRefImpl Rel, uint64_t &Res) const
virtual error_code getRelocationOffset (DataRefImpl Rel, uint64_t &Res) const
virtual symbol_iterator getRelocationSymbol (DataRefImpl Rel) const
virtual error_code getRelocationType (DataRefImpl Rel, uint64_t &Res) const
virtual error_code getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > &Result) const
virtual error_code getRelocationValueString (DataRefImpl Rel, SmallVectorImpl< char > &Result) const
virtual error_code getRelocationHidden (DataRefImpl Rel, bool &Result) const
virtual error_code getLibraryNext (DataRefImpl LibData, LibraryRef &Res) const
virtual error_code getLibraryPath (DataRefImpl LibData, StringRef &Res) const
virtual symbol_iterator begin_symbols () const
virtual symbol_iterator end_symbols () const
virtual symbol_iterator begin_dynamic_symbols () const
virtual symbol_iterator end_dynamic_symbols () const
virtual section_iterator begin_sections () const
virtual section_iterator end_sections () const
virtual library_iterator begin_libraries_needed () const
virtual library_iterator end_libraries_needed () const
virtual uint8_t getBytesInAddress () const
The number of bytes used to represent an address in this object file format.
virtual StringRef getFileFormatName () const
virtual unsigned getArch () const
virtual StringRef getLoadName () const
relocation_iterator section_rel_begin (unsigned Index) const
relocation_iterator section_rel_end (unsigned Index) const
dice_iterator begin_dices () const
dice_iterator end_dices () const
StringRef getSectionFinalSegmentName (DataRefImpl Sec) const
ArrayRef< char > getSectionRawName (DataRefImpl Sec) const
ArrayRef< char > getSectionRawFinalSegmentName (DataRefImpl Sec) const
bool isRelocationScattered (const MachO::any_relocation_info &RE) const
unsigned getPlainRelocationSymbolNum (const MachO::any_relocation_info &RE) const
bool getPlainRelocationExternal (const MachO::any_relocation_info &RE) const
bool getScatteredRelocationScattered (const MachO::any_relocation_info &RE) const
uint32_t getScatteredRelocationValue (const MachO::any_relocation_info &RE) const
unsigned getAnyRelocationAddress (const MachO::any_relocation_info &RE) const
unsigned getAnyRelocationPCRel (const MachO::any_relocation_info &RE) const
unsigned getAnyRelocationLength (const MachO::any_relocation_info &RE) const
unsigned getAnyRelocationType (const MachO::any_relocation_info &RE) const
SectionRef getRelocationSection (const MachO::any_relocation_info &RE) const
LoadCommandInfo getFirstLoadCommandInfo () const
LoadCommandInfo getNextLoadCommandInfo (const LoadCommandInfo &L) const
MachO::section getSection (DataRefImpl DRI) const
MachO::section_64 getSection64 (DataRefImpl DRI) const
MachO::section getSection (const LoadCommandInfo &L, unsigned Index) const
MachO::section_64 getSection64 (const LoadCommandInfo &L, unsigned Index) const
MachO::nlist getSymbolTableEntry (DataRefImpl DRI) const
MachO::nlist_64 getSymbol64TableEntry (DataRefImpl DRI) const
MachO::linkedit_data_command getLinkeditDataLoadCommand (const LoadCommandInfo &L) const
MachO::segment_command getSegmentLoadCommand (const LoadCommandInfo &L) const
MachO::segment_command_64 getSegment64LoadCommand (const LoadCommandInfo &L) const
MachO::linker_options_command getLinkerOptionsLoadCommand (const LoadCommandInfo &L) const
MachO::any_relocation_info getRelocation (DataRefImpl Rel) const
MachO::data_in_code_entry getDice (DataRefImpl Rel) const
MachO::mach_header getHeader () const
MachO::mach_header_64 getHeader64 () const
uint32_t getIndirectSymbolTableEntry (const MachO::dysymtab_command &DLC, unsigned Index) const
MachO::data_in_code_entry getDataInCodeTableEntry (uint32_t DataOffset, unsigned Index) const
MachO::symtab_command getSymtabLoadCommand () const
MachO::dysymtab_command getDysymtabLoadCommand () const
MachO::linkedit_data_command getDataInCodeLoadCommand () const
StringRef getStringTableData () const
bool is64Bit () const
void ReadULEB128s (uint64_t Index, SmallVectorImpl< uint64_t > &Out) const
Public Member Functions inherited from llvm::object::Binary
virtual ~Binary ()
StringRef getData () const
StringRef getFileName () const
unsigned int getType () const
bool isObject () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isLittleEndian () const
Static Public Member Functions
static Triple::ArchType getArch (uint32_t CPUType)
static bool classof (const Binary *v)
Static Public Member Functions inherited from llvm::object::ObjectFile
static ObjectFile * createObjectFile (StringRef ObjectPath)
Create ObjectFile from path.
static ObjectFile * createObjectFile (MemoryBuffer *Object)
static bool classof (const Binary *v)
static ObjectFile * createCOFFObjectFile (MemoryBuffer *Object)
static ObjectFile * createELFObjectFile (MemoryBuffer *Object)
static ObjectFile * createMachOObjectFile (MemoryBuffer *Object)
Additional Inherited Members
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive, ID_MachOUniversalBinary, ID_StartObjects, ID_COFF,
ID_ELF32L, ID_ELF32B, ID_ELF64L, ID_ELF64B,
ID_MachO32L, ID_MachO32B, ID_MachO64L, ID_MachO64B,
ID_EndObjects
}
Protected Member Functions inherited from llvm::object::ObjectFile
ObjectFile (unsigned int Type, MemoryBuffer *source)
const uint8_t * base () const
virtual section_iterator getRelocatedSection (DataRefImpl Sec) const
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBuffer *Source)
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBuffer * Data
Detailed Description
Definition at line 52 of file Object/MachO.h.
Constructor & Destructor Documentation
llvm::object::MachOObjectFile::MachOObjectFile (MemoryBuffer * Object, bool IsLittleEndian, bool Is64Bits, error_code & ec)
Definition at line 422 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::C, llvm::MachO::load_command::cmd, getFirstLoadCommandInfo(), getHeader(), getNextLoadCommandInfo(), llvm::object::getSectionPtr(), llvm::object::getSegmentLoadCommandNumSections(), I, is64Bit(), llvm::SPII::Load, llvm::MachO::mach_header::ncmds, llvm::object::MachOObjectFile::LoadCommandInfo::Ptr, and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by llvm::object::ObjectFile::createMachOObjectFile().
Member Function Documentation
dice_iterator llvm::object::MachOObjectFile::begin_dices () const
Definition at line 1320 of file MachOObjectFile.cpp.
References llvm::MachO::linkedit_data_command::dataoff, getDataInCodeLoadCommand(), llvm::object::getPtr(), and llvm::object::DataRefImpl::p.
symbol_iterator llvm::object::MachOObjectFile::begin_dynamic_symbols () const virtual
Implements llvm::object::ObjectFile.
Definition at line 1215 of file MachOObjectFile.cpp.
References llvm::report_fatal_error().
library_iterator llvm::object::MachOObjectFile::begin_libraries_needed () const virtual
Implements llvm::object::ObjectFile.
Definition at line 1236 of file MachOObjectFile.cpp.
References llvm::report_fatal_error().
section_iterator llvm::object::MachOObjectFile::begin_sections () const virtual
Implements llvm::object::ObjectFile.
Definition at line 1225 of file MachOObjectFile.cpp.
References llvm::object::ObjectFile::SectionRef.
Referenced by llvm::MCMachOObjectDisassembler::MCMachOObjectDisassembler(), and llvm::object::printRelocationTargetName().
symbol_iterator llvm::object::MachOObjectFile::begin_symbols () const virtual
Implements llvm::object::ObjectFile.
Definition at line 1190 of file MachOObjectFile.cpp.
References llvm::object::getPtr(), getSymtabLoadCommand(), llvm::object::DataRefImpl::p, llvm::object::ObjectFile::SymbolRef, and llvm::MachO::symtab_command::symoff.
Referenced by getSymbolSize(), and llvm::object::printRelocationTargetName().
static bool llvm::object::MachOObjectFile::classof (const Binary * v) inline static
Definition at line 202 of file Object/MachO.h.
References llvm::object::Binary::isMachO().
dice_iterator llvm::object::MachOObjectFile::end_dices () const
Definition at line 1330 of file MachOObjectFile.cpp.
References llvm::MachO::linkedit_data_command::dataoff, llvm::MachO::linkedit_data_command::datasize, getDataInCodeLoadCommand(), llvm::object::getPtr(), and llvm::object::DataRefImpl::p.
symbol_iterator llvm::object::MachOObjectFile::end_dynamic_symbols () const virtual
Implements llvm::object::ObjectFile.
Definition at line 1220 of file MachOObjectFile.cpp.
References llvm::report_fatal_error().
library_iterator llvm::object::MachOObjectFile::end_libraries_needed () const virtual
Implements llvm::object::ObjectFile.
Definition at line 1241 of file MachOObjectFile.cpp.
References llvm::report_fatal_error().
section_iterator llvm::object::MachOObjectFile::end_sections () const virtual
Implements llvm::object::ObjectFile.
Definition at line 1230 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, llvm::object::ObjectFile::SectionRef, and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by getRelocationSection(), getSymbolSection(), llvm::MCMachOObjectDisassembler::MCMachOObjectDisassembler(), and llvm::object::printRelocationTargetName().
symbol_iterator llvm::object::MachOObjectFile::end_symbols () const virtual
Implements llvm::object::ObjectFile.
Definition at line 1200 of file MachOObjectFile.cpp.
References llvm::object::getPtr(), getSymtabLoadCommand(), is64Bit(), llvm::MachO::symtab_command::nsyms, llvm::object::DataRefImpl::p, llvm::object::ObjectFile::SymbolRef, and llvm::MachO::symtab_command::symoff.
Referenced by getRelocationSymbol(), getSymbolSize(), and llvm::object::printRelocationTargetName().
unsigned llvm::object::MachOObjectFile::getAnyRelocationAddress (const MachO::any_relocation_info & RE) const
Definition at line 1393 of file MachOObjectFile.cpp.
References llvm::object::getPlainRelocationAddress(), llvm::object::getScatteredRelocationAddress(), and isRelocationScattered().
Referenced by getRelocationOffset().
unsigned llvm::object::MachOObjectFile::getAnyRelocationLength (const MachO::any_relocation_info & RE) const
Definition at line 1407 of file MachOObjectFile.cpp.
References llvm::object::getPlainRelocationLength(), llvm::object::getScatteredRelocationLength(), and isRelocationScattered().
Referenced by getRelocationValueString(), and llvm::RuntimeDyldMachO::processRelocationRef().
unsigned llvm::object::MachOObjectFile::getAnyRelocationPCRel (const MachO::any_relocation_info & RE) const
Definition at line 1400 of file MachOObjectFile.cpp.
References llvm::object::getPlainRelocationPCRel(), llvm::object::getScatteredRelocationPCRel(), and isRelocationScattered().
Referenced by getRelocationValueString(), and llvm::RuntimeDyldMachO::processRelocationRef().
unsigned llvm::object::MachOObjectFile::getAnyRelocationType (const MachO::any_relocation_info & RE) const
Definition at line 1415 of file MachOObjectFile.cpp.
References llvm::object::getPlainRelocationType(), llvm::object::getScatteredRelocationType(), and isRelocationScattered().
Referenced by getRelocationType(), getRelocationValueString(), and llvm::RuntimeDyldMachO::processRelocationRef().
unsigned llvm::object::MachOObjectFile::getArch () const virtual
Implements llvm::object::ObjectFile.
Definition at line 1299 of file MachOObjectFile.cpp.
References llvm::object::getCPUType().
Referenced by llvm::object::MachOUniversalBinary::ObjectForArch::getAsObjectFile(), getRelocationHidden(), getRelocationTypeName(), and getRelocationValueString().
Triple::ArchType llvm::object::MachOObjectFile::getArch (uint32_t CPUType) static
Definition at line 1282 of file MachOObjectFile.cpp.
References llvm::Triple::arm, llvm::MachO::CPU_TYPE_ARM, llvm::MachO::CPU_TYPE_I386, llvm::MachO::CPU_TYPE_POWERPC, llvm::MachO::CPU_TYPE_POWERPC64, llvm::MachO::CPU_TYPE_X86_64, llvm::Triple::ppc, llvm::Triple::ppc64, llvm::Triple::UnknownArch, llvm::Triple::x86, and llvm::Triple::x86_64.
uint8_t llvm::object::MachOObjectFile::getBytesInAddress () const virtual
The number of bytes used to represent an address in this object file format.
Implements llvm::object::ObjectFile.
Definition at line 1246 of file MachOObjectFile.cpp.
References is64Bit().
MachO::linkedit_data_command llvm::object::MachOObjectFile::getDataInCodeLoadCommand () const
Definition at line 1547 of file MachOObjectFile.cpp.
References llvm::MachO::linkedit_data_command::cmd.
Referenced by begin_dices(), and end_dices().
MachO::data_in_code_entry llvm::object::MachOObjectFile::getDataInCodeTableEntry (uint32_t DataOffset, unsigned Index) const
Definition at line 1532 of file MachOObjectFile.cpp.
References llvm::object::getPtr().
MachO::data_in_code_entry llvm::object::MachOObjectFile::getDice (DataRefImpl Rel) const
Definition at line 1511 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::p, and P.
Referenced by llvm::object::DiceRef::getKind(), llvm::object::DiceRef::getLength(), and llvm::object::DiceRef::getOffset().
MachO::dysymtab_command llvm::object::MachOObjectFile::getDysymtabLoadCommand () const
Definition at line 1542 of file MachOObjectFile.cpp.
StringRef llvm::object::MachOObjectFile::getFileFormatName () const virtual
Implements llvm::object::ObjectFile.
Definition at line 1250 of file MachOObjectFile.cpp.
References llvm::MachO::CPU_TYPE_ARM, llvm::MachO::CPU_TYPE_I386, llvm::MachO::CPU_TYPE_POWERPC, llvm::MachO::CPU_TYPE_POWERPC64, llvm::MachO::CPU_TYPE_X86_64, llvm::object::getCPUType(), and is64Bit().
MachOObjectFile::LoadCommandInfo llvm::object::MachOObjectFile::getFirstLoadCommandInfo () const
Definition at line 1434 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::C, llvm::object::getPtr(), llvm::COFF::HeaderSize, is64Bit(), llvm::SPII::Load, and llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
Referenced by llvm::MCMachOObjectDisassembler::getEntrypoint(), and MachOObjectFile().
MachO::mach_header llvm::object::MachOObjectFile::getHeader () const
Definition at line 1516 of file MachOObjectFile.cpp.
References llvm::object::getPtr().
Referenced by llvm::object::getCPUType(), llvm::MCMachOObjectDisassembler::getEntrypoint(), and MachOObjectFile().
MachO::mach_header_64 llvm::object::MachOObjectFile::getHeader64 () const
Definition at line 1520 of file MachOObjectFile.cpp.
References llvm::object::getPtr().
uint32_t llvm::object::MachOObjectFile::getIndirectSymbolTableEntry (const MachO::dysymtab_command & DLC, unsigned Index) const
Definition at line 1524 of file MachOObjectFile.cpp.
References llvm::object::getPtr(), and llvm::MachO::dysymtab_command::indirectsymoff.
error_code llvm::object::MachOObjectFile::getLibraryNext (DataRefImpl LibData, LibraryRef & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 1180 of file MachOObjectFile.cpp.
References llvm::report_fatal_error().
error_code llvm::object::MachOObjectFile::getLibraryPath (DataRefImpl LibData, StringRef & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 1185 of file MachOObjectFile.cpp.
References llvm::report_fatal_error().
MachO::linkedit_data_command llvm::object::MachOObjectFile::getLinkeditDataLoadCommand (const LoadCommandInfo & L) const
Definition at line 1485 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
MachO::linker_options_command llvm::object::MachOObjectFile::getLinkerOptionsLoadCommand (const LoadCommandInfo & L) const
Definition at line 1500 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
StringRef llvm::object::MachOObjectFile::getLoadName () const virtual
For shared objects, returns the name which this object should be loaded from at runtime. This corresponds to DT_SONAME on ELF and LC_ID_DYLIB (install name) on MachO.
Implements llvm::object::ObjectFile.
Definition at line 1303 of file MachOObjectFile.cpp.
References llvm::report_fatal_error().
MachOObjectFile::LoadCommandInfo llvm::object::MachOObjectFile::getNextLoadCommandInfo (const LoadCommandInfo & L) const
Definition at line 1445 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::C, llvm::MachO::load_command::cmdsize, and llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
Referenced by llvm::MCMachOObjectDisassembler::getEntrypoint(), and MachOObjectFile().
bool llvm::object::MachOObjectFile::getPlainRelocationExternal (const MachO::any_relocation_info & RE) const
Definition at line 1376 of file MachOObjectFile.cpp.
References llvm::object::Binary::isLittleEndian(), and llvm::MachO::any_relocation_info::r_word1.
Referenced by getRelocationSection(), getRelocationSymbol(), llvm::object::printRelocationTargetName(), and llvm::RuntimeDyldMachO::processRelocationRef().
unsigned llvm::object::MachOObjectFile::getPlainRelocationSymbolNum (const MachO::any_relocation_info & RE) const
Definition at line 1369 of file MachOObjectFile.cpp.
References llvm::object::Binary::isLittleEndian(), and llvm::MachO::any_relocation_info::r_word1.
Referenced by getRelocationSection(), getRelocationSymbol(), and llvm::object::printRelocationTargetName().
MachO::any_relocation_info llvm::object::MachOObjectFile::getRelocation (DataRefImpl Rel) const
Definition at line 1505 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::p, and P.
Referenced by getRelocationOffset(), getRelocationSymbol(), getRelocationType(), getRelocationValueString(), and llvm::RuntimeDyldMachO::processRelocationRef().
error_code llvm::object::MachOObjectFile::getRelocationAddress (DataRefImpl Rel, uint64_t & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 847 of file MachOObjectFile.cpp.
References llvm::report_fatal_error().
error_code llvm::object::MachOObjectFile::getRelocationHidden (DataRefImpl Rel, bool & Result) const virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 1153 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::Triple::arm, llvm::object::DataRefImpl::d, llvm::MachO::GENERIC_RELOC_PAIR, getArch(), getRelocationType(), llvm::Triple::ppc, llvm::object::object_error::success, Type, llvm::Triple::x86, llvm::Triple::x86_64, llvm::MachO::X86_64_RELOC_SUBTRACTOR, and llvm::MachO::X86_64_RELOC_UNSIGNED.
error_code llvm::object::MachOObjectFile::getRelocationNext (DataRefImpl Rel, RelocationRef & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 837 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::p, P, llvm::object::ObjectFile::RelocationRef, and llvm::object::object_error::success.
error_code llvm::object::MachOObjectFile::getRelocationOffset (DataRefImpl Rel, uint64_t & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 851 of file MachOObjectFile.cpp.
References getAnyRelocationAddress(), getRelocation(), and llvm::object::object_error::success.
SectionRef llvm::object::MachOObjectFile::getRelocationSection (const MachO::any_relocation_info & RE) const
Definition at line 1423 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, end_sections(), getPlainRelocationExternal(), getPlainRelocationSymbolNum(), isRelocationScattered(), and llvm::object::ObjectFile::SectionRef.
Referenced by llvm::RuntimeDyldMachO::processRelocationRef().
symbol_iterator llvm::object::MachOObjectFile::getRelocationSymbol (DataRefImpl Rel) const virtual
Implements llvm::object::ObjectFile.
Definition at line 859 of file MachOObjectFile.cpp.
References end_symbols(), getPlainRelocationExternal(), getPlainRelocationSymbolNum(), llvm::object::getPtr(), getRelocation(), getSymtabLoadCommand(), is64Bit(), llvm::object::DataRefImpl::p, S, llvm::object::ObjectFile::SymbolRef, and llvm::MachO::symtab_command::symoff.
error_code llvm::object::MachOObjectFile::getRelocationType (DataRefImpl Rel, uint64_t & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 876 of file MachOObjectFile.cpp.
References getAnyRelocationType(), getRelocation(), and llvm::object::object_error::success.
Referenced by getRelocationHidden(), and getRelocationTypeName().
error_code llvm::object::MachOObjectFile::getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > & Result) const virtual
Implements llvm::object::ObjectFile.
Definition at line 884 of file MachOObjectFile.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::Triple::arm, llvm::StringRef::begin(), llvm::StringRef::end(), getArch(), getRelocationType(), llvm::Triple::ppc, llvm::object::object_error::success, llvm::Triple::UnknownArch, llvm::Triple::x86, and llvm::Triple::x86_64.
error_code llvm::object::MachOObjectFile::getRelocationValueString (DataRefImpl Rel, SmallVectorImpl< char > & Result) const virtual
Implements llvm::object::ObjectFile.
Definition at line 977 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::SmallVectorImpl< T >::append(), llvm::Triple::arm, llvm::MachO::ARM_RELOC_HALF, llvm::MachO::ARM_RELOC_HALF_SECTDIFF, llvm::MachO::ARM_RELOC_PAIR, llvm::object::DataRefImpl::d, llvm::raw_ostream::flush(), llvm::MachO::GENERIC_RELOC_LOCAL_SECTDIFF, llvm::MachO::GENERIC_RELOC_PAIR, llvm::MachO::GENERIC_RELOC_SECTDIFF, llvm::MachO::GENERIC_RELOC_TLV, getAnyRelocationLength(), getAnyRelocationPCRel(), getAnyRelocationType(), getArch(), getRelocation(), llvm::Triple::ppc, llvm::object::printRelocationTargetName(), llvm::report_fatal_error(), llvm::object::object_error::success, llvm::Triple::x86, llvm::Triple::x86_64, llvm::MachO::X86_64_RELOC_GOT, llvm::MachO::X86_64_RELOC_GOT_LOAD, llvm::MachO::X86_64_RELOC_SIGNED_1, llvm::MachO::X86_64_RELOC_SIGNED_2, llvm::MachO::X86_64_RELOC_SIGNED_4, llvm::MachO::X86_64_RELOC_SUBTRACTOR, llvm::MachO::X86_64_RELOC_TLV, and llvm::MachO::X86_64_RELOC_UNSIGNED.
bool llvm::object::MachOObjectFile::getScatteredRelocationScattered (const MachO::any_relocation_info & RE) const
Definition at line 1383 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word0.
uint32_t llvm::object::MachOObjectFile::getScatteredRelocationValue (const MachO::any_relocation_info & RE) const
Definition at line 1388 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word1.
MachO::section llvm::object::MachOObjectFile::getSection (DataRefImpl DRI) const
Definition at line 1452 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, and llvm::object::DataRefImpl::d.
Referenced by getSectionAddress(), getSectionAlignment(), getSectionContents(), llvm::object::getSectionFlags(), getSectionSize(), getSymbolFileOffset(), section_rel_begin(), and section_rel_end().
MachO::section llvm::object::MachOObjectFile::getSection (const LoadCommandInfo & L, unsigned Index) const
Definition at line 1460 of file MachOObjectFile.cpp.
References llvm::object::getSectionPtr().
MachO::section_64 llvm::object::MachOObjectFile::getSection64 (DataRefImpl DRI) const
Definition at line 1456 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, and llvm::object::DataRefImpl::d.
Referenced by getSectionAddress(), getSectionAlignment(), getSectionContents(), llvm::object::getSectionFlags(), getSectionSize(), getSymbolFileOffset(), section_rel_begin(), and section_rel_end().
MachO::section_64 llvm::object::MachOObjectFile::getSection64 (const LoadCommandInfo & L, unsigned Index) const
Definition at line 1466 of file MachOObjectFile.cpp.
References llvm::object::getSectionPtr().
error_code llvm::object::MachOObjectFile::getSectionAddress (DataRefImpl Sec, uint64_t & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 666 of file MachOObjectFile.cpp.
References llvm::MachO::section::addr, llvm::MachO::section_64::addr, getSection(), getSection64(), is64Bit(), and llvm::object::object_error::success.
Referenced by getSymbolSize(), and sectionContainsSymbol().
error_code llvm::object::MachOObjectFile::getSectionAlignment (DataRefImpl Sec, uint64_t & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 710 of file MachOObjectFile.cpp.
References Align, llvm::MachO::section::align, llvm::MachO::section_64::align, getSection(), getSection64(), is64Bit(), and llvm::object::object_error::success.
error_code llvm::object::MachOObjectFile::getSectionContents (DataRefImpl Sec, StringRef & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 691 of file MachOObjectFile.cpp.
References llvm::object::Binary::getData(), getSection(), getSection64(), is64Bit(), llvm::MachO::section::offset, llvm::MachO::section_64::offset, llvm::MachO::section::size, llvm::MachO::section_64::size, llvm::StringRef::substr(), and llvm::object::object_error::success.
StringRef llvm::object::MachOObjectFile::getSectionFinalSegmentName (DataRefImpl Sec) const
Definition at line 1342 of file MachOObjectFile.cpp.
References llvm::ArrayRef< T >::data(), getSectionRawFinalSegmentName(), and llvm::object::parseSegmentOrSectionName().
error_code llvm::object::MachOObjectFile::getSectionName (DataRefImpl Sec, StringRef & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 659 of file MachOObjectFile.cpp.
References llvm::ArrayRef< T >::data(), getSectionRawName(), llvm::object::parseSegmentOrSectionName(), and llvm::object::object_error::success.
error_code llvm::object::MachOObjectFile::getSectionNext (DataRefImpl Sec, SectionRef & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 651 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, llvm::object::ObjectFile::SectionRef, and llvm::object::object_error::success.
ArrayRef< char > llvm::object::MachOObjectFile::getSectionRawFinalSegmentName (DataRefImpl Sec) const
Definition at line 1355 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, and llvm::object::section_base::segname.
Referenced by getSectionFinalSegmentName().
ArrayRef< char > llvm::object::MachOObjectFile::getSectionRawName (DataRefImpl Sec) const
Definition at line 1348 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, and llvm::object::section_base::sectname.
Referenced by getSectionName().
error_code llvm::object::MachOObjectFile::getSectionSize (DataRefImpl Sec, uint64_t & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 678 of file MachOObjectFile.cpp.
References getSection(), getSection64(), is64Bit(), llvm::MachO::section::size, llvm::MachO::section_64::size, and llvm::object::object_error::success.
Referenced by getSymbolSize(), and sectionContainsSymbol().
MachO::segment_command_64 llvm::object::MachOObjectFile::getSegment64LoadCommand (const LoadCommandInfo & L) const
Definition at line 1495 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
Referenced by llvm::object::getSegmentLoadCommandNumSections().
MachO::segment_command llvm::object::MachOObjectFile::getSegmentLoadCommand (const LoadCommandInfo & L) const
Definition at line 1490 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
Referenced by llvm::object::getSegmentLoadCommandNumSections().
StringRef llvm::object::MachOObjectFile::getStringTableData () const
Definition at line 1560 of file MachOObjectFile.cpp.
References llvm::object::Binary::getData(), getSymtabLoadCommand(), S, llvm::MachO::symtab_command::stroff, llvm::MachO::symtab_command::strsize, and llvm::StringRef::substr().
Referenced by getSymbolName().
MachO::nlist_64 llvm::object::MachOObjectFile::getSymbol64TableEntry (DataRefImpl DRI) const
Definition at line 1479 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::p, and P.
Referenced by getSymbolAddress().
error_code llvm::object::MachOObjectFile::getSymbolAddress (DataRefImpl Symb, uint64_t & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 476 of file MachOObjectFile.cpp.
References getSymbol64TableEntry(), getSymbolTableEntry(), is64Bit(), llvm::MachO::nlist::n_value, llvm::MachO::nlist_64::n_value, and llvm::object::object_error::success.
Referenced by getSymbolFileOffset(), getSymbolFlags(), getSymbolSize(), and sectionContainsSymbol().
error_code llvm::object::MachOObjectFile::getSymbolAlignment (DataRefImpl Symb, uint32_t & Res) const virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 511 of file MachOObjectFile.cpp.
References llvm::MachO::GET_COMM_ALIGN(), getSymbolFlags(), llvm::object::getSymbolTableEntryBase(), llvm::object::nlist_base::n_desc, and llvm::object::object_error::success.
error_code llvm::object::MachOObjectFile::getSymbolFileOffset (DataRefImpl Symb, uint64_t & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 489 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::MachO::section::addr, llvm::MachO::section_64::addr, llvm::object::DataRefImpl::d, getSection(), getSection64(), getSymbolAddress(), llvm::object::getSymbolTableEntryBase(), is64Bit(), llvm::object::nlist_base::n_sect, llvm::MachO::section::offset, llvm::MachO::section_64::offset, and llvm::object::object_error::success.
error_code llvm::object::MachOObjectFile::getSymbolFlags (DataRefImpl Symb, uint32_t & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 594 of file MachOObjectFile.cpp.
References getSymbolAddress(), llvm::object::getSymbolTableEntryBase(), llvm::MachO::N_ABS, llvm::object::nlist_base::n_desc, llvm::MachO::N_EXT, llvm::MachO::N_STAB, llvm::object::nlist_base::n_type, llvm::MachO::N_TYPE, llvm::MachO::N_UNDF, llvm::MachO::N_WEAK_DEF, llvm::MachO::N_WEAK_REF, and llvm::object::object_error::success.
Referenced by getSymbolAlignment(), and getSymbolSize().
error_code llvm::object::MachOObjectFile::getSymbolName (DataRefImpl Symb, StringRef & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 467 of file MachOObjectFile.cpp.
References llvm::StringRef::data(), getStringTableData(), llvm::object::getSymbolTableEntryBase(), llvm::object::nlist_base::n_strx, and llvm::object::object_error::success.
error_code llvm::object::MachOObjectFile::getSymbolNext (DataRefImpl Symb, SymbolRef & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 457 of file MachOObjectFile.cpp.
References is64Bit(), llvm::object::DataRefImpl::p, llvm::object::object_error::success, and llvm::object::ObjectFile::SymbolRef.
error_code llvm::object::MachOObjectFile::getSymbolSection (DataRefImpl Symb, section_iterator & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 630 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, end_sections(), llvm::object::getSymbolTableEntryBase(), index, llvm::object::nlist_base::n_sect, llvm::object::ObjectFile::SectionRef, and llvm::object::object_error::success.
error_code llvm::object::MachOObjectFile::getSymbolSize (DataRefImpl Symb, uint64_t & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 524 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, begin_symbols(), llvm::object::DataRefImpl::d, end_symbols(), getSectionAddress(), getSectionSize(), getSymbolAddress(), getSymbolFlags(), llvm::object::getSymbolTableEntryBase(), I, llvm::object::nlist_base::n_sect, llvm::object::object_error::success, and llvm::object::UnknownAddressOrSize.
MachO::nlist llvm::object::MachOObjectFile::getSymbolTableEntry (DataRefImpl DRI) const
Definition at line 1473 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::p, and P.
Referenced by getSymbolAddress().
error_code llvm::object::MachOObjectFile::getSymbolType (DataRefImpl Symb, SymbolRef::Type & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 570 of file MachOObjectFile.cpp.
References llvm::object::getSymbolTableEntryBase(), llvm::MachO::N_SECT, llvm::MachO::N_STAB, llvm::object::nlist_base::n_type, llvm::MachO::N_TYPE, llvm::MachO::N_UNDF, llvm::object::SymbolRef::ST_Debug, llvm::object::SymbolRef::ST_Function, llvm::object::SymbolRef::ST_Other, llvm::object::SymbolRef::ST_Unknown, and llvm::object::object_error::success.
Referenced by sectionContainsSymbol().
error_code llvm::object::MachOObjectFile::getSymbolValue (DataRefImpl Symb, uint64_t & Val) const virtual
Implements llvm::object::ObjectFile.
Definition at line 646 of file MachOObjectFile.cpp.
References llvm::report_fatal_error().
MachO::symtab_command llvm::object::MachOObjectFile::getSymtabLoadCommand () const
Definition at line 1538 of file MachOObjectFile.cpp.
Referenced by begin_symbols(), end_symbols(), getRelocationSymbol(), and getStringTableData().
bool llvm::object::MachOObjectFile::is64Bit () const
Definition at line 1565 of file MachOObjectFile.cpp.
References llvm::object::Binary::getMachOType(), and llvm::object::Binary::getType().
Referenced by end_symbols(), getBytesInAddress(), getFileFormatName(), getFirstLoadCommandInfo(), getRelocationSymbol(), getSectionAddress(), getSectionAlignment(), getSectionContents(), llvm::object::getSectionFlags(), llvm::object::getSectionPtr(), getSectionSize(), llvm::object::getSegmentLoadCommandNumSections(), llvm::MCMachOObjectDisassembler::getStaticExitFunctions(), llvm::MCMachOObjectDisassembler::getStaticInitFunctions(), getSymbolAddress(), getSymbolFileOffset(), getSymbolNext(), MachOObjectFile(), section_rel_begin(), and section_rel_end().
bool llvm::object::MachOObjectFile::isRelocationScattered (const MachO::any_relocation_info & RE) const
Definition at line 1362 of file MachOObjectFile.cpp.
References llvm::MachO::CPU_TYPE_X86_64, llvm::object::getCPUType(), and llvm::object::getPlainRelocationAddress().
Referenced by getAnyRelocationAddress(), getAnyRelocationLength(), getAnyRelocationPCRel(), getAnyRelocationType(), getRelocationSection(), llvm::object::printRelocationTargetName(), and llvm::RuntimeDyldMachO::processRelocationRef().
error_code llvm::object::MachOObjectFile::isSectionBSS (DataRefImpl Sec, bool & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 737 of file MachOObjectFile.cpp.
References llvm::object::object_error::success.
error_code llvm::object::MachOObjectFile::isSectionData (DataRefImpl Sec, bool & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 731 of file MachOObjectFile.cpp.
References llvm::object::object_error::success.
error_code llvm::object::MachOObjectFile::isSectionReadOnlyData (DataRefImpl Sec, bool & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 767 of file MachOObjectFile.cpp.
References llvm::object::object_error::success.
error_code llvm::object::MachOObjectFile::isSectionRequiredForExecution (DataRefImpl Sec, bool & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 744 of file MachOObjectFile.cpp.
References llvm::object::object_error::success.
error_code llvm::object::MachOObjectFile::isSectionText (DataRefImpl Sec, bool & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 725 of file MachOObjectFile.cpp.
References llvm::object::getSectionFlags(), and llvm::object::object_error::success.
error_code llvm::object::MachOObjectFile::isSectionVirtual (DataRefImpl Sec, bool & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 751 of file MachOObjectFile.cpp.
References llvm::object::object_error::success.
error_code llvm::object::MachOObjectFile::isSectionZeroInit (DataRefImpl Sec, bool & Res) const virtual
Implements llvm::object::ObjectFile.
Definition at line 759 of file MachOObjectFile.cpp.
References llvm::object::getSectionFlags(), llvm::MachO::S_GB_ZEROFILL, llvm::MachO::S_ZEROFILL, and llvm::object::object_error::success.
void llvm::object::MachOObjectFile::ReadULEB128s (uint64_t Index, SmallVectorImpl< uint64_t > & Out) const
Definition at line 1570 of file MachOObjectFile.cpp.
References llvm::object::Binary::getData(), llvm::DataExtractor::getULEB128(), and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
relocation_iterator llvm::object::MachOObjectFile::section_rel_begin (DataRefImpl Sec) const virtual
Implements llvm::object::ObjectFile.
Definition at line 800 of file MachOObjectFile.cpp.
References llvm::object::getPtr(), getSection(), getSection64(), is64Bit(), llvm::object::DataRefImpl::p, llvm::object::ObjectFile::RelocationRef, llvm::MachO::section::reloff, llvm::MachO::section_64::reloff, and llvm::AArch64ISD::Ret.
Referenced by section_rel_begin().
relocation_iterator llvm::object::MachOObjectFile::section_rel_begin (unsigned Index) const
Definition at line 1308 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, and section_rel_begin().
relocation_iterator llvm::object::MachOObjectFile::section_rel_end (DataRefImpl Sec) const virtual
Implements llvm::object::ObjectFile.
Definition at line 816 of file MachOObjectFile.cpp.
References llvm::object::getPtr(), getSection(), getSection64(), is64Bit(), llvm::MachO::section::nreloc, llvm::MachO::section_64::nreloc, llvm::object::DataRefImpl::p, P, llvm::object::ObjectFile::RelocationRef, llvm::MachO::section::reloff, llvm::MachO::section_64::reloff, and llvm::AArch64ISD::Ret.
Referenced by section_rel_end().
relocation_iterator llvm::object::MachOObjectFile::section_rel_end (unsigned Index) const
Definition at line 1314 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::d, and section_rel_end().
error_code llvm::object::MachOObjectFile::sectionContainsSymbol (DataRefImpl Sec, DataRefImpl Symb, bool & Result) const virtual
Implements llvm::object::ObjectFile.
Definition at line 779 of file MachOObjectFile.cpp.
References getSectionAddress(), getSectionSize(), getSymbolAddress(), getSymbolType(), llvm::A64DB::ST, llvm::object::SymbolRef::ST_Unknown, and llvm::object::object_error::success.
The documentation for this class was generated from the following files:
Object/MachO.h
MachOObjectFile.cpp