LLVM: llvm::MachineRegisterInfo::Delegate Class Reference
LLVM API Documentation
llvm::MachineRegisterInfo::Delegate Class Reference abstract
#include <MachineRegisterInfo.h>
Public Member Functions
virtual void MRI_NoteNewVirtualRegister (unsigned Reg)=0
virtual ~Delegate ()
Detailed Description
Definition at line 32 of file MachineRegisterInfo.h.
Constructor & Destructor Documentation
virtual llvm::MachineRegisterInfo::Delegate::~Delegate () inline virtual
Definition at line 37 of file MachineRegisterInfo.h.
References llvm::MachineOperand::isReg(), llvm::TargetRegisterInfo::isVirtualRegister(), LLVM_DELETED_FUNCTION, llvm::MachineOperand::Reg, and llvm::MachineRegisterInfo::~MachineRegisterInfo().
Member Function Documentation
virtual void llvm::MachineRegisterInfo::Delegate::MRI_NoteNewVirtualRegister (unsigned Reg) pure virtual
Referenced by llvm::MachineRegisterInfo::createVirtualRegister().
The documentation for this class was generated from the following files:
MachineRegisterInfo.h
MachineRegisterInfo.cpp