LLVM: llvm::DagRecTy Class Reference
LLVM API Documentation
llvm::DagRecTy Class Reference
#include <Record.h>
Public Member Functions
virtual Init * convertValue (UnsetInit *UI)
virtual Init * convertValue (BitInit *BI)
virtual Init * convertValue (BitsInit *BI)
virtual Init * convertValue (IntInit *II)
virtual Init * convertValue (StringInit *SI)
virtual Init * convertValue (ListInit *LI)
virtual Init * convertValue (VarBitInit *VB)
virtual Init * convertValue (DefInit *DI)
virtual Init * convertValue (UnOpInit *BO)
virtual Init * convertValue (BinOpInit *BO)
virtual Init * convertValue (TernOpInit *BO)
virtual Init * convertValue (DagInit *CI)
virtual Init * convertValue (TypedInit *TI)
virtual Init * convertValue (VarInit *VI)
virtual Init * convertValue (FieldInit *FI)
virtual std::string getAsString () const
virtual bool typeIsConvertibleTo (const RecTy *RHS) const
Public Member Functions inherited from llvm::RecTy
RecTyKind getRecTyKind () const
RecTy (RecTyKind K)
virtual ~RecTy ()
void print (raw_ostream &OS) const
void dump () const
ListRecTy * getListTy ()
getListTy - Returns the type representing list<this>.
virtual bool baseClassOf (const RecTy *) const
Static Public Member Functions
static bool classof (const RecTy *RT)
static DagRecTy * get ()
Additional Inherited Members
Public Types inherited from llvm::RecTy
enum RecTyKind {
BitRecTyKind, BitsRecTyKind, IntRecTyKind, StringRecTyKind,
ListRecTyKind, DagRecTyKind, RecordRecTyKind
}
Subclass discriminator (for dyn_cast<> et al.)
Detailed Description
DagRecTy - 'dag' - Represent a dag fragment
Definition at line 332 of file Record.h.
Member Function Documentation
static bool llvm::DagRecTy::classof (const RecTy * RT) inline static
Definition at line 336 of file Record.h.
References llvm::RecTy::DagRecTyKind, and llvm::RecTy::getRecTyKind().
virtual Init* llvm::DagRecTy::convertValue (UnsetInit * UI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 342 of file Record.h.
virtual Init* llvm::DagRecTy::convertValue (BitInit * BI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 343 of file Record.h.
virtual Init* llvm::DagRecTy::convertValue (BitsInit * BI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 344 of file Record.h.
virtual Init* llvm::DagRecTy::convertValue (IntInit * II) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 345 of file Record.h.
virtual Init* llvm::DagRecTy::convertValue (StringInit * SI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 346 of file Record.h.
virtual Init* llvm::DagRecTy::convertValue (ListInit * LI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 347 of file Record.h.
virtual Init* llvm::DagRecTy::convertValue (VarBitInit * VB) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 348 of file Record.h.
virtual Init* llvm::DagRecTy::convertValue (DefInit * DI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 349 of file Record.h.
References llvm::RecTy::convertValue().
Init * DagRecTy::convertValue (UnOpInit * BO) virtual
Reimplemented from llvm::RecTy.
Definition at line 311 of file Record.cpp.
References llvm::UnOpInit::CAST, llvm::Init::convertInitializerTo(), llvm::UnOpInit::get(), llvm::UnOpInit::getOpcode(), and llvm::UnOpInit::getOperand().
Init * DagRecTy::convertValue (BinOpInit * BO) virtual
Reimplemented from llvm::RecTy.
Definition at line 322 of file Record.cpp.
References llvm::BinOpInit::CONCAT, llvm::Init::convertInitializerTo(), llvm::BinOpInit::get(), llvm::BinOpInit::getLHS(), llvm::BinOpInit::getOpcode(), and llvm::BinOpInit::getRHS().
virtual Init* llvm::DagRecTy::convertValue (TernOpInit * BO) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 352 of file Record.h.
References llvm::RecTy::convertValue().
virtual Init* llvm::DagRecTy::convertValue (DagInit * CI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 353 of file Record.h.
References llvm::RecTy::convertValue().
Init * DagRecTy::convertValue (TypedInit * TI) virtual
Reimplemented from llvm::RecTy.
Definition at line 305 of file Record.cpp.
References llvm::TypedInit::getType(), and llvm::RecTy::typeIsConvertibleTo().
virtual Init* llvm::DagRecTy::convertValue (VarInit * VI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 355 of file Record.h.
References llvm::RecTy::convertValue().
virtual Init* llvm::DagRecTy::convertValue (FieldInit * FI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 356 of file Record.h.
References llvm::RecTy::convertValue().
static DagRecTy* llvm::DagRecTy::get () inline static
Definition at line 340 of file Record.h.
Referenced by GetNewAnonymousName().
virtual std::string llvm::DagRecTy::getAsString () const inline virtual
Implements llvm::RecTy.
Definition at line 358 of file Record.h.
virtual bool llvm::DagRecTy::typeIsConvertibleTo (const RecTy * RHS) const inline virtual
typeIsConvertibleTo - Return true if all values of 'this' type can be converted to the specified type.
Implements llvm::RecTy.
Definition at line 360 of file Record.h.
References llvm::RecTy::baseClassOf().
The documentation for this class was generated from the following files:
Record.h
Record.cpp