LLVM: llvm::JITRegistrar Class Reference
LLVM API Documentation
llvm::JITRegistrar Class Reference abstract
Global access point for the JIT debugging interface.
#include <JITRegistrar.h>
Public Member Functions
JITRegistrar ()
Instantiates the JIT service.
virtual ~JITRegistrar ()
virtual void registerObject (const ObjectBuffer &Object)=0
virtual bool deregisterObject (const ObjectBuffer &Object)=0
Static Public Member Functions
static JITRegistrar & getGDBRegistrar ()
Returns a reference to a GDB JIT registrar singleton.
Detailed Description
Global access point for the JIT debugging interface.
Definition at line 18 of file JITRegistrar.h.
Constructor & Destructor Documentation
llvm::JITRegistrar::JITRegistrar () inline
Instantiates the JIT service.
Definition at line 22 of file JITRegistrar.h.
virtual llvm::JITRegistrar::~JITRegistrar () inline virtual
Unregisters each object that was previously registered and releases all internal resources.
Definition at line 26 of file JITRegistrar.h.
References deregisterObject(), getGDBRegistrar(), and registerObject().
Member Function Documentation
virtual bool llvm::JITRegistrar::deregisterObject (const ObjectBuffer & Object) pure virtual
Removes the internal registration of Object, and frees associated resources. Returns true if Object was previously registered.
Referenced by ~JITRegistrar().
JITRegistrar & llvm::JITRegistrar::getGDBRegistrar () static
Returns a reference to a GDB JIT registrar singleton.
Definition at line 200 of file GDBRegistrar.cpp.
Referenced by ~JITRegistrar().
virtual void llvm::JITRegistrar::registerObject (const ObjectBuffer & Object) pure virtual
Creates an entry in the JIT registry for the buffer Object, which must contain an object file in executable memory with any debug information for the debugger.
Referenced by ~JITRegistrar().
The documentation for this class was generated from the following files:
JITRegistrar.h
GDBRegistrar.cpp
RuntimeDyld.cpp