LLVM: llvm::SelectionDAGISel Class Reference
LLVM API Documentation
llvm::SelectionDAGISel Class Reference abstract
#include <SelectionDAGISel.h>
Public Types
enum BuiltinOpcodes {
OPC_Scope, OPC_RecordNode, OPC_RecordChild0, OPC_RecordChild1,
OPC_RecordChild2, OPC_RecordChild3, OPC_RecordChild4, OPC_RecordChild5,
OPC_RecordChild6, OPC_RecordChild7, OPC_RecordMemRef, OPC_CaptureGlueInput,
OPC_MoveChild, OPC_MoveParent, OPC_CheckSame, OPC_CheckChild0Same,
OPC_CheckChild1Same, OPC_CheckChild2Same, OPC_CheckChild3Same, OPC_CheckPatternPredicate,
OPC_CheckPredicate, OPC_CheckOpcode, OPC_SwitchOpcode, OPC_CheckType,
OPC_SwitchType, OPC_CheckChild0Type, OPC_CheckChild1Type, OPC_CheckChild2Type,
OPC_CheckChild3Type, OPC_CheckChild4Type, OPC_CheckChild5Type, OPC_CheckChild6Type,
OPC_CheckChild7Type, OPC_CheckInteger, OPC_CheckCondCode, OPC_CheckValueType,
OPC_CheckComplexPat, OPC_CheckAndImm, OPC_CheckOrImm, OPC_CheckFoldableChainNode,
OPC_EmitInteger, OPC_EmitRegister, OPC_EmitRegister2, OPC_EmitConvertToTarget,
OPC_EmitMergeInputChains, OPC_EmitMergeInputChains1_0, OPC_EmitMergeInputChains1_1, OPC_EmitCopyToReg,
OPC_EmitNodeXForm, OPC_EmitNode, OPC_MorphNodeTo, OPC_MarkGlueResults,
OPC_CompleteMatch
}
enum {
OPFL_None = 0, OPFL_Chain = 1, OPFL_GlueInput = 2, OPFL_GlueOutput = 4,
OPFL_MemRefs = 8, OPFL_Variadic0 = 1<<4, OPFL_Variadic1 = 2<<4, OPFL_Variadic2 = 3<<4,
OPFL_Variadic3 = 4<<4, OPFL_Variadic4 = 5<<4, OPFL_Variadic5 = 6<<4, OPFL_Variadic6 = 7<<4,
OPFL_VariadicInfo = OPFL_Variadic6
}
Public Member Functions
SelectionDAGISel (TargetMachine &tm, CodeGenOpt::Level OL=CodeGenOpt::Default)
virtual ~SelectionDAGISel ()
const TargetLowering * getTargetLowering () const
virtual void getAnalysisUsage (AnalysisUsage &AU) const
virtual bool runOnMachineFunction (MachineFunction &MF)
virtual void EmitFunctionEntryCode ()
virtual void PreprocessISelDAG ()
virtual void PostprocessISelDAG ()
virtual SDNode * Select (SDNode *N)=0
Select - Main hook targets implement to select a node.
virtual bool SelectInlineAsmMemoryOperand (const SDValue &Op, char ConstraintCode, std::vector< SDValue > &OutOps)
virtual bool IsProfitableToFold (SDValue N, SDNode *U, SDNode *Root) const
bool CheckAndMask (SDValue LHS, ConstantSDNode *RHS, int64_t DesiredMaskS) const
bool CheckOrMask (SDValue LHS, ConstantSDNode *RHS, int64_t DesiredMaskS) const
virtual bool CheckPatternPredicate (unsigned PredNo) const
virtual bool CheckNodePredicate (SDNode *N, unsigned PredNo) const
virtual bool CheckComplexPattern (SDNode *Root, SDNode *Parent, SDValue N, unsigned PatternNo, SmallVectorImpl< std::pair< SDValue, SDNode * > > &Result)
virtual SDValue RunSDNodeXForm (SDValue V, unsigned XFormNo)
SDNode * SelectCodeCommon (SDNode *NodeToMatch, const unsigned char *MatcherTable, unsigned TableSize)
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const
createPrinterPass - Get a function printer pass.
virtual void assignPassManager (PMStack &PMS, PassManagerType T)
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Member Functions
static bool IsLegalToFold (SDValue N, SDNode *U, SDNode *Root, CodeGenOpt::Level OptLevel, bool IgnoreChains=false)
static int getNumFixedFromVariadicInfo (unsigned Flags)
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Public Attributes
TargetMachine & TM
const TargetLibraryInfo * LibInfo
const TargetTransformInfo * TTI
FunctionLoweringInfo * FuncInfo
MachineFunction * MF
MachineRegisterInfo * RegInfo
SelectionDAG * CurDAG
SelectionDAGBuilder * SDB
AliasAnalysis * AA
GCFunctionInfo * GFI
CodeGenOpt::Level OptLevel
Static Public Attributes
static char ID = 0
Protected Member Functions
void ReplaceUses (SDValue F, SDValue T)
void ReplaceUses (const SDValue *F, const SDValue *T, unsigned Num)
void ReplaceUses (SDNode *F, SDNode *T)
void SelectInlineAsmMemoryOperands (std::vector< SDValue > &Ops)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
Protected Attributes
unsigned DAGSize
Detailed Description
SelectionDAGISel - This is the common base class used for SelectionDAG-based pattern-matching instruction selectors.
Definition at line 42 of file SelectionDAGISel.h.
Member Enumeration Documentation
anonymous enum
Enumerator
OPFL_None
OPFL_Chain
OPFL_GlueInput
OPFL_GlueOutput
OPFL_MemRefs
OPFL_Variadic0
OPFL_Variadic1
OPFL_Variadic2
OPFL_Variadic3
OPFL_Variadic4
OPFL_Variadic5
OPFL_Variadic6
OPFL_VariadicInfo
Definition at line 149 of file SelectionDAGISel.h.
enum llvm::SelectionDAGISel::BuiltinOpcodes
Enumerator
OPC_Scope
OPC_RecordNode
OPC_RecordChild0
OPC_RecordChild1
OPC_RecordChild2
OPC_RecordChild3
OPC_RecordChild4
OPC_RecordChild5
OPC_RecordChild6
OPC_RecordChild7
OPC_RecordMemRef
OPC_CaptureGlueInput
OPC_MoveChild
OPC_MoveParent
OPC_CheckSame
OPC_CheckChild0Same
OPC_CheckChild1Same
OPC_CheckChild2Same
OPC_CheckChild3Same
OPC_CheckPatternPredicate
OPC_CheckPredicate
OPC_CheckOpcode
OPC_SwitchOpcode
OPC_CheckType
OPC_SwitchType
OPC_CheckChild0Type
OPC_CheckChild1Type
OPC_CheckChild2Type
OPC_CheckChild3Type
OPC_CheckChild4Type
OPC_CheckChild5Type
OPC_CheckChild6Type
OPC_CheckChild7Type
OPC_CheckInteger
OPC_CheckCondCode
OPC_CheckValueType
OPC_CheckComplexPat
OPC_CheckAndImm
OPC_CheckOrImm
OPC_CheckFoldableChainNode
OPC_EmitInteger
OPC_EmitRegister
OPC_EmitRegister2
OPC_EmitConvertToTarget
OPC_EmitMergeInputChains
OPC_EmitMergeInputChains1_0
OPC_EmitMergeInputChains1_1
OPC_EmitCopyToReg
OPC_EmitNodeXForm
OPC_EmitNode
OPC_MorphNodeTo
OPC_MarkGlueResults
OPC_CompleteMatch
Definition at line 106 of file SelectionDAGISel.h.
Constructor & Destructor Documentation
SelectionDAGISel::SelectionDAGISel (TargetMachine & tm, CodeGenOpt::Level OL = CodeGenOpt::Default) explicit
Definition at line 317 of file SelectionDAGISel.cpp.
References llvm::PassRegistry::getPassRegistry(), llvm::initializeAliasAnalysisAnalysisGroup(), llvm::initializeBranchProbabilityInfoPass(), llvm::initializeGCModuleInfoPass(), and llvm::initializeTargetLibraryInfoPass().
SelectionDAGISel::~SelectionDAGISel () virtual
Definition at line 332 of file SelectionDAGISel.cpp.
References CurDAG, FuncInfo, and SDB.
Member Function Documentation
bool SelectionDAGISel::CheckAndMask (SDValue LHS, ConstantSDNode * RHS, int64_t DesiredMaskS) const
CheckAndMask - The isel is trying to match something like (and X, 255). If the dag combiner simplified the 255, we still want to match. RHS is the actual value in the DAG on the RHS of an AND, and DesiredMaskS is the value specified in the .td file (e.g. 255).
Definition at line 1559 of file SelectionDAGISel.cpp.
References CurDAG, llvm::ConstantSDNode::getAPIntValue(), llvm::SDValue::getValueSizeInBits(), llvm::APInt::intersects(), and llvm::SelectionDAG::MaskedValueIsZero().
Referenced by CheckAndImm(), and ReplaceUses().
virtual bool llvm::SelectionDAGISel::CheckComplexPattern (SDNode * Root, SDNode * Parent, SDValue N, unsigned PatternNo, SmallVectorImpl< std::pair< SDValue, SDNode * > > & Result) inline virtual
Definition at line 227 of file SelectionDAGISel.h.
References llvm_unreachable.
Referenced by SelectCodeCommon().
virtual bool llvm::SelectionDAGISel::CheckNodePredicate (SDNode * N, unsigned PredNo) const inline virtual
CheckNodePredicate - This function is generated by tblgen in the target. It runs node predicate number PredNo and returns true if it succeeds or false if it fails. The number is a private implementation detail to the code tblgen produces.
Definition at line 223 of file SelectionDAGISel.h.
References llvm_unreachable.
Referenced by CheckNodePredicate(), IsPredicateKnownToFail(), and SelectCodeCommon().
bool SelectionDAGISel::CheckOrMask (SDValue LHS, ConstantSDNode * RHS, int64_t DesiredMaskS) const
CheckOrMask - The isel is trying to match something like (or X, 255). If the dag combiner simplified the 255, we still want to match. RHS is the actual value in the DAG on the RHS of an OR, and DesiredMaskS is the value specified in the .td file (e.g. 255).
Definition at line 1588 of file SelectionDAGISel.cpp.
References llvm::SelectionDAG::ComputeMaskedBits(), CurDAG, llvm::ConstantSDNode::getAPIntValue(), llvm::SDValue::getValueSizeInBits(), llvm::APInt::intersects(), and SelectInlineAsmMemoryOperands().
Referenced by CheckOrImm(), and ReplaceUses().
virtual bool llvm::SelectionDAGISel::CheckPatternPredicate (unsigned PredNo) const inline virtual
CheckPatternPredicate - This function is generated by tblgen in the target. It runs the specified pattern predicate and returns true if it succeeds or false if it fails. The number is a private implementation detail to the code tblgen produces.
Definition at line 215 of file SelectionDAGISel.h.
References llvm_unreachable.
Referenced by CheckPatternPredicate(), IsPredicateKnownToFail(), and SelectCodeCommon().
virtual void llvm::SelectionDAGISel::EmitFunctionEntryCode () inline virtual
Definition at line 69 of file SelectionDAGISel.h.
void SelectionDAGISel::getAnalysisUsage (AnalysisUsage & AU) const virtual
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
For MachineFunctionPasses, calling AU.preservesCFG() indicates that the pass does not modify the MachineBasicBlock CFG.
Reimplemented from llvm::MachineFunctionPass.
Definition at line 338 of file SelectionDAGISel.cpp.
References llvm::AnalysisUsage::addPreserved(), llvm::AnalysisUsage::addRequired(), llvm::MachineFunctionPass::getAnalysisUsage(), llvm::CodeGenOpt::None, OptLevel, and UseMBPI.
Referenced by getTargetLowering().
static int llvm::SelectionDAGISel::getNumFixedFromVariadicInfo (unsigned Flags) inline static
getNumFixedFromVariadicInfo - Transform an EmitNode flags word into the number of fixed arity values that should be skipped when copying from the root.
Definition at line 169 of file SelectionDAGISel.h.
References OPFL_VariadicInfo.
Referenced by SelectCodeCommon().
const TargetLowering* llvm::SelectionDAGISel::getTargetLowering () const inline
Definition at line 61 of file SelectionDAGISel.h.
References getAnalysisUsage(), llvm::TargetMachine::getTargetLowering(), and runOnMachineFunction().
Referenced by collectFailStats(), llvm::createDefaultScheduler(), llvm::createHybridListDAGScheduler(), llvm::createILPListDAGScheduler(), llvm::MipsDAGToDAGISel::getGlobalBaseReg(), IsPredicateKnownToFail(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), runOnMachineFunction(), and SelectCodeCommon().
bool SelectionDAGISel::IsLegalToFold (SDValue N, SDNode * U, SDNode * Root, CodeGenOpt::Level OptLevel, bool IgnoreChains = false) static
IsLegalToFold - Returns true if the specific operand node N of U can be folded during instruction selection that starts at Root. FIXME: This is a static member function because the MSP430/X86 targets, which uses it during isel. This could become a proper member.
IsLegalToFold - Returns true if the specific operand node N of U can be folded during instruction selection that starts at Root.
Definition at line 1730 of file SelectionDAGISel.cpp.
References CurDAG, findGlueUse(), findNonImmUse(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumValues(), llvm::SDNode::getValueType(), llvm::MVT::Glue, llvm::TargetOpcode::IMPLICIT_DEF, llvm::ISD::INLINEASM, LLVM_ATTRIBUTE_ALWAYS_INLINE, N, llvm::CodeGenOpt::None, llvm::SDNode::op_begin(), llvm::SDNode::op_end(), llvm::MVT::Other, SelectInlineAsmMemoryOperands(), llvm::SelectionDAG::SelectNodeTo(), and llvm::SDNode::setNodeId().
Referenced by SelectCodeCommon(), and SelectInlineAsmMemoryOperand().
bool SelectionDAGISel::IsProfitableToFold (SDValue N, SDNode * U, SDNode * Root) const virtual
IsProfitableToFold - Returns true if it's profitable to fold the specific operand node N of U during instruction selection that starts at Root.
Definition at line 1722 of file SelectionDAGISel.cpp.
References llvm::SDValue::hasOneUse(), llvm::CodeGenOpt::None, and OptLevel.
Referenced by SelectCodeCommon(), and SelectInlineAsmMemoryOperand().
virtual void llvm::SelectionDAGISel::PostprocessISelDAG () inline virtual
PostprocessISelDAG() - This hook allows the target to hack on the graph right after selection.
Definition at line 77 of file SelectionDAGISel.h.
References N, and Select().
Referenced by runOnMachineFunction().
virtual void llvm::SelectionDAGISel::PreprocessISelDAG () inline virtual
PreprocessISelDAG - This hook allows targets to hack on the graph before instruction selection starts.
Definition at line 73 of file SelectionDAGISel.h.
Referenced by runOnMachineFunction().
void llvm::SelectionDAGISel::ReplaceUses (SDValue F, SDValue T) inline protected
ReplaceUses - replace all uses of the old node F with the use of the new node T.
Definition at line 181 of file SelectionDAGISel.h.
References llvm::SelectionDAG::ReplaceAllUsesOfValueWith().
Referenced by runOnMachineFunction().
void llvm::SelectionDAGISel::ReplaceUses (const SDValue * F, const SDValue * T, unsigned Num) inline protected
ReplaceUses - replace all uses of the old nodes F with the use of the new nodes T.
Definition at line 187 of file SelectionDAGISel.h.
References llvm::SelectionDAG::ReplaceAllUsesOfValuesWith().
void llvm::SelectionDAGISel::ReplaceUses (SDNode * F, SDNode * T) inline protected
ReplaceUses - replace all uses of the old node F with the use of the new node T.
Definition at line 193 of file SelectionDAGISel.h.
References CheckAndMask(), CheckOrMask(), llvm::SelectionDAG::ReplaceAllUsesWith(), and SelectInlineAsmMemoryOperands().
bool SelectionDAGISel::runOnMachineFunction (MachineFunction & MF) virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Reimplemented in llvm::MipsDAGToDAGISel.
Definition at line 387 of file SelectionDAGISel.cpp.
References AA, llvm::MachineModuleInfo::addLandingPad(), llvm::MachineBasicBlock::addLiveIn(), llvm::FunctionLoweringInfo::AddLiveOutRegInfo(), llvm::AfterLegalizeDAG, llvm::AfterLegalizeTypes, llvm::AfterLegalizeVectorOps, llvm::SelectionDAG::allnodes_begin(), llvm::FunctionLoweringInfo::ArgDbgValues, llvm::SelectionDAG::AssignTopologicalOrder(), llvm::BeforeLegalizeTypes, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::begin(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::FunctionLoweringInfo::BPI, llvm::BuildMI(), llvm::Function::callsFunctionThatReturnsTwice(), llvm::FunctionLoweringInfo::clear(), llvm::SelectionDAG::clear(), llvm::SelectionDAGBuilder::clear(), llvm::SelectionDAG::Combine(), llvm::SelectionDAG::ComputeMaskedBits(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::MachineRegisterInfo::constrainRegClass(), llvm::ISD::CopyToReg, CurDAG, DAGSize, llvm::SelectionDAG::DAGUpdateListener, llvm::TargetOpcode::DBG_VALUE, llvm::dbgs(), DEBUG, llvm::tgtok::Def, llvm::ISD::DELETED_NODE, llvm::NVPTXISD::Dummy, llvm::SelectionDAG::dump(), llvm::TargetOpcode::EH_LABEL, llvm::MachineRegisterInfo::EmitLiveInCopies(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::SmallVectorBase::empty(), llvm::TargetOptions::EnableFastISel, EnableFastISelAbort, EnableFastISelVerbose, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::end(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::FunctionLoweringInfo::ExceptionPointerVirtReg, llvm::FunctionLoweringInfo::ExceptionSelectorVirtReg, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::find(), llvm::MachineRegisterInfo::freezeReservedRegs(), FuncInfo, llvm::MCInstrInfo::get(), llvm::MachineBasicBlock::getBasicBlock(), llvm::SelectionDAGBuilder::getControlRoot(), llvm::SelectionDAGBuilder::getCurDebugLoc(), llvm::MachineInstr::getDebugLoc(), llvm::TargetLoweringBase::getExceptionPointerRegister(), llvm::TargetLoweringBase::getExceptionSelectorRegister(), llvm::MachineFunction::getFrameInfo(), llvm::TargetRegisterInfo::getFrameRegister(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getImm(), llvm::TargetMachine::getInstrInfo(), llvm::MachineFunction::getMMI(), llvm::MachineBasicBlock::getName(), llvm::Value::getName(), llvm::MachineFunction::getName(), llvm::SDValue::getNode(), llvm::MachineBasicBlock::getNumber(), llvm::MachineInstr::getNumOperands(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOpcode(), llvm::MachineInstr::getOperand(), llvm::SDNode::getOperand(), llvm::MachineInstr::getParent(), llvm::TargetLoweringBase::getPointerTy(), llvm::MachineOperand::getReg(), getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::TargetLoweringBase::getRegClassFor(), llvm::MachineFunction::getRegInfo(), llvm::TargetMachine::getRegisterInfo(), llvm::SelectionDAG::getRoot(), llvm::TargetMachine::getSubtarget(), getTargetLowering(), llvm::TargetMachine::getTargetLowering(), llvm::SDValue::getValueType(), llvm::MachineRegisterInfo::getVRegDef(), GFI, llvm::MachineFrameInfo::hasCalls(), llvm::Function::hasFnAttribute(), llvm::Function::hasGC(), llvm::MachineFunction::hasMSInlineAsm(), llvm::SelectionDAGBuilder::HasTailCall, i, I, llvm::ARM_PROC::IE, llvm::SelectionDAG::init(), llvm::SelectionDAGBuilder::init(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::insert(), llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::MachineBasicBlock::insert(), llvm::MachineBasicBlock::insertAfter(), llvm::FunctionLoweringInfo::InsertPt, llvm::MCInstrDesc::isCall(), llvm::MachineInstr::isCopy(), llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isFI(), llvm::MachineInstr::isIndirectDebugValue(), llvm::EVT::isInteger(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::MCInstrDesc::isReturn(), llvm::EVT::isVector(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::SelectionDAG::Legalize(), llvm::SelectionDAG::LegalizeTypes(), llvm::SelectionDAG::LegalizeVectors(), LibInfo, llvm::MachineRegisterInfo::livein_begin(), llvm::MachineRegisterInfo::livein_end(), llvm::SelectionDAGBuilder::LPadToCallSiteMap, llvm::FunctionLoweringInfo::MBB, MF, llvm::A64CC::MI, MRI, N, llvm::SelectionDAG::NewNodesMustHaveLegalTypes, llvm::next(), llvm::CodeGenOpt::None, llvm::Attribute::OptimizeNone, llvm::TargetMachine::Options, OptLevel, llvm::MVT::Other, llvm::SmallVectorImpl< T >::pop_back_val(), PostprocessISelDAG(), PreprocessISelDAG(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::FunctionLoweringInfo::RegFixups, RegInfo, llvm::SelectionDAG::RemoveDeadNode(), llvm::MachineRegisterInfo::replaceRegWith(), ReplaceUses(), llvm::TargetSubtargetInfo::resetSubtargetFeatures(), llvm::TargetMachine::resetTargetOptions(), llvm::ScheduleDAGSDNodes::Run(), Scheduler, SDB, Select(), llvm::FunctionLoweringInfo::set(), llvm::MachineModuleInfo::setCallSiteLandingPad(), llvm::MachineFunction::setExposesReturnsTwice(), llvm::MachineFrameInfo::setHasCalls(), llvm::MachineFunction::setHasMSInlineAsm(), llvm::SelectionDAG::setRoot(), SplitCriticalSideEffectEdges(), llvm::A64DB::ST, llvm::StringRef::str(), T, TII, llvm::TimePassesIsEnabled, TM, TTI, llvm::SelectionDAGBuilder::UpdateSplitBlock(), llvm::MachineRegisterInfo::use_begin(), llvm::SDNode::use_empty(), UseMBPI, ViewDAGCombine2, ViewDAGCombineLT, llvm::SelectionDAG::viewGraph(), llvm::ScheduleDAG::viewGraph(), ViewISelDAGs, ViewLegalizeDAGs, ViewLegalizeTypesDAGs, ViewSchedDAGs, ViewSUnitDAGs, llvm::TargetRegisterInfo::virtReg2Index(), and llvm::SelectionDAGBuilder::visit().
Referenced by getTargetLowering(), and llvm::MipsDAGToDAGISel::runOnMachineFunction().
virtual SDValue llvm::SelectionDAGISel::RunSDNodeXForm (SDValue V, unsigned XFormNo) inline virtual
Definition at line 233 of file SelectionDAGISel.h.
References F(), llvm_unreachable, and SelectCodeCommon().
Referenced by SelectCodeCommon().
virtual SDNode* llvm::SelectionDAGISel::Select (SDNode * N) pure virtual
Select - Main hook targets implement to select a node.
Referenced by PostprocessISelDAG(), and runOnMachineFunction().
SDNode * SelectionDAGISel::SelectCodeCommon (SDNode * NodeToMatch, const unsigned char * MatcherTable, unsigned TableSize)
Definition at line 2350 of file SelectionDAGISel.cpp.
References llvm::MachineFunction::allocateMemRefsArray(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::SmallVectorTemplateCommon< T >::back(), llvm::ISD::BasicBlock, llvm::SmallVectorTemplateCommon< T >::begin(), CheckAndImm(), CheckChildSame(), CheckChildType(), CheckComplexPattern(), CheckCondCode(), CheckInteger(), CheckNodePredicate(), CheckOpcode(), CheckOrImm(), CheckPatternPredicate(), CheckSame(), CheckType(), CheckValueType(), llvm::SmallVectorImpl< T >::clear(), llvm::ISD::Constant, llvm::ISD::ConstantFP, llvm::ISD::CopyFromReg, llvm::ISD::CopyToReg, CurDAG, llvm::SmallVectorTemplateCommon< T >::data(), llvm::dbgs(), DEBUG, llvm::ISD::DELETED_NODE, llvm::SDNode::dump(), llvm::ISD::EH_LABEL, llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::ISD::EntryToken, llvm::MCInstrInfo::get(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getEntryNode(), llvm::TargetMachine::getInstrInfo(), llvm::TargetMachine::getIntrinsicInfo(), llvm::SelectionDAG::getMachineNode(), llvm::Intrinsic::getName(), llvm::MachineFunction::getName(), llvm::SDValue::getNode(), getNumFixedFromVariadicInfo(), llvm::SDValue::getNumOperands(), llvm::SDNode::getNumOperands(), llvm::SDNode::getNumValues(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRegister(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), getTargetLowering(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), GetVBR(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, HandleMergeInputChains(), llvm::ISD::HANDLENODE, i, I, ID, llvm::ISD::INLINEASM, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::MVT::iPTR, IsLegalToFold(), llvm::SDNode::isMachineOpcode(), IsPredicateKnownToFail(), IsProfitableToFold(), llvm::ISD::LIFETIME_END, llvm::ISD::LIFETIME_START, llvm::MCInstrDesc::mayLoad(), llvm::MCInstrDesc::mayStore(), llvm::ISD::MDNODE_SDNODE, MF, llvm::Intrinsic::num_intrinsics, OPC_CaptureGlueInput, OPC_CheckAndImm, OPC_CheckChild0Same, OPC_CheckChild0Type, OPC_CheckChild1Same, OPC_CheckChild1Type, OPC_CheckChild2Same, OPC_CheckChild2Type, OPC_CheckChild3Same, OPC_CheckChild3Type, OPC_CheckChild4Type, OPC_CheckChild5Type, OPC_CheckChild6Type, OPC_CheckChild7Type, OPC_CheckComplexPat, OPC_CheckCondCode, OPC_CheckFoldableChainNode, OPC_CheckInteger, OPC_CheckOpcode, OPC_CheckOrImm, OPC_CheckPatternPredicate, OPC_CheckPredicate, OPC_CheckSame, OPC_CheckType, OPC_CheckValueType, OPC_CompleteMatch, OPC_EmitConvertToTarget, OPC_EmitCopyToReg, OPC_EmitInteger, OPC_EmitMergeInputChains, OPC_EmitMergeInputChains1_0, OPC_EmitMergeInputChains1_1, OPC_EmitNode, OPC_EmitNodeXForm, OPC_EmitRegister, OPC_EmitRegister2, OPC_MarkGlueResults, OPC_MorphNodeTo, OPC_MoveChild, OPC_MoveParent, OPC_RecordChild0, OPC_RecordChild1, OPC_RecordChild2, OPC_RecordChild3, OPC_RecordChild4, OPC_RecordChild5, OPC_RecordChild6, OPC_RecordChild7, OPC_RecordMemRef, OPC_RecordNode, OPC_Scope, OPC_SwitchOpcode, OPC_SwitchType, OPFL_Chain, OPFL_GlueInput, OPFL_GlueOutput, OPFL_MemRefs, OPFL_VariadicInfo, OptLevel, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::pop_back(), llvm::SDNode::printrFull(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::ISD::Register, llvm::ISD::RegisterMask, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::report_fatal_error(), llvm::SmallVectorImpl< T >::resize(), RunSDNodeXForm(), llvm::SDNode::setNodeId(), llvm::MVT::SimpleTy, llvm::SmallVectorTemplateCommon< T >::size(), llvm::raw_string_ostream::str(), llvm::ISD::TargetBlockAddress, llvm::ISD::TargetConstant, llvm::ISD::TargetConstantFP, llvm::ISD::TargetConstantPool, llvm::ISD::TargetExternalSymbol, llvm::ISD::TargetFrameIndex, llvm::ISD::TargetGlobalAddress, llvm::ISD::TargetGlobalTLSAddress, llvm::ISD::TargetJumpTable, TII, TM, llvm::ISD::TokenFactor, llvm::ISD::UNDEF, and llvm::SDNode::use_empty().
Referenced by IsPredicateKnownToFail(), and RunSDNodeXForm().
virtual bool llvm::SelectionDAGISel::SelectInlineAsmMemoryOperand (const SDValue & Op, char ConstraintCode, std::vector< SDValue > & OutOps) inline virtual
SelectInlineAsmMemoryOperand - Select the specified address as a target addressing mode, according to the specified constraint code. If this does not match or is not implemented, return true. The resultant operands (which will appear in the machine instruction) should be added to the OutOps vector.
Definition at line 87 of file SelectionDAGISel.h.
References IsLegalToFold(), and IsProfitableToFold().
Referenced by SelectInlineAsmMemoryOperands().
void SelectionDAGISel::SelectInlineAsmMemoryOperands (std::vector< SDValue > & Ops) protected
SelectInlineAsmMemoryOperands - Calls to this are automatically generated by tblgen. Others should not call it.
Definition at line 1622 of file SelectionDAGISel.cpp.
References CurDAG, llvm::InlineAsm::getFlagWord(), llvm::InlineAsm::getNumOperandRegisters(), llvm::SelectionDAG::getTargetConstant(), llvm::MVT::Glue, i, llvm::MVT::i32, llvm::InlineAsm::isMemKind(), llvm::report_fatal_error(), SelectInlineAsmMemoryOperand(), and std::swap().
Referenced by CheckOrMask(), IsLegalToFold(), and ReplaceUses().
Member Data Documentation
AliasAnalysis* llvm::SelectionDAGISel::AA
Definition at line 52 of file SelectionDAGISel.h.
Referenced by llvm::createVLIWDAGScheduler(), and runOnMachineFunction().
SelectionDAG* llvm::SelectionDAGISel::CurDAG
Definition at line 50 of file SelectionDAGISel.h.
Referenced by CheckAndMask(), CheckOrMask(), collectFailStats(), FindSplitPointForStackProtector(), llvm::MipsDAGToDAGISel::getGlobalBaseReg(), GetVBR(), HandleMergeInputChains(), IsLegalToFold(), runOnMachineFunction(), SelectCodeCommon(), SelectInlineAsmMemoryOperands(), and ~SelectionDAGISel().
unsigned llvm::SelectionDAGISel::DAGSize protected
DAGSize - Size of DAG being instruction selected.
Definition at line 177 of file SelectionDAGISel.h.
Referenced by runOnMachineFunction().
FunctionLoweringInfo* llvm::SelectionDAGISel::FuncInfo
Definition at line 47 of file SelectionDAGISel.h.
Referenced by collectFailStats(), FindSplitPointForStackProtector(), runOnMachineFunction(), and ~SelectionDAGISel().
GCFunctionInfo* llvm::SelectionDAGISel::GFI
Definition at line 53 of file SelectionDAGISel.h.
Referenced by runOnMachineFunction().
char SelectionDAGISel::ID = 0 static
Definition at line 55 of file SelectionDAGISel.h.
Referenced by initializePassOnce(), and SelectCodeCommon().
const TargetLibraryInfo* llvm::SelectionDAGISel::LibInfo
Definition at line 45 of file SelectionDAGISel.h.
Referenced by collectFailStats(), and runOnMachineFunction().
MachineFunction* llvm::SelectionDAGISel::MF
Definition at line 48 of file SelectionDAGISel.h.
Referenced by llvm::createBURRListDAGScheduler(), llvm::createDAGLinearizer(), llvm::createFastDAGScheduler(), llvm::createHybridListDAGScheduler(), llvm::createILPListDAGScheduler(), llvm::createSourceListDAGScheduler(), llvm::createVLIWDAGScheduler(), FindSplitPointForStackProtector(), llvm::MipsDAGToDAGISel::getGlobalBaseReg(), llvm::MipsDAGToDAGISel::getPassName(), llvm::Mips16DAGToDAGISel::Mips16DAGToDAGISel(), llvm::MipsSEDAGToDAGISel::MipsSEDAGToDAGISel(), llvm::OptLevelChanger::OptLevelChanger(), llvm::ResourcePriorityQueue::ResourcePriorityQueue(), runOnMachineFunction(), SelectCodeCommon(), and llvm::OptLevelChanger::~OptLevelChanger().
CodeGenOpt::Level llvm::SelectionDAGISel::OptLevel
Definition at line 54 of file SelectionDAGISel.h.
Referenced by collectFailStats(), FindSplitPointForStackProtector(), getAnalysisUsage(), IsProfitableToFold(), llvm::OptLevelChanger::OptLevelChanger(), runOnMachineFunction(), SelectCodeCommon(), and llvm::OptLevelChanger::~OptLevelChanger().
MachineRegisterInfo* llvm::SelectionDAGISel::RegInfo
Definition at line 49 of file SelectionDAGISel.h.
Referenced by runOnMachineFunction().
SelectionDAGBuilder* llvm::SelectionDAGISel::SDB
Definition at line 51 of file SelectionDAGISel.h.
Referenced by collectFailStats(), FindSplitPointForStackProtector(), runOnMachineFunction(), and ~SelectionDAGISel().
TargetMachine& llvm::SelectionDAGISel::TM
Definition at line 44 of file SelectionDAGISel.h.
Referenced by collectFailStats(), llvm::createBURRListDAGScheduler(), llvm::createDefaultScheduler(), llvm::createHybridListDAGScheduler(), llvm::createILPListDAGScheduler(), llvm::createSourceListDAGScheduler(), llvm::Mips16DAGToDAGISel::Mips16DAGToDAGISel(), llvm::MipsSEDAGToDAGISel::MipsSEDAGToDAGISel(), llvm::OptLevelChanger::OptLevelChanger(), runOnMachineFunction(), SelectCodeCommon(), and llvm::OptLevelChanger::~OptLevelChanger().
const TargetTransformInfo* llvm::SelectionDAGISel::TTI
Definition at line 46 of file SelectionDAGISel.h.
Referenced by runOnMachineFunction().
The documentation for this class was generated from the following files:
SelectionDAGISel.h
SelectionDAGBuilder.cpp
SelectionDAGISel.cpp