LLVM: llvm::DWARFDebugAbbrev Class Reference
LLVM API Documentation
llvm::DWARFDebugAbbrev Class Reference
#include <DWARFDebugAbbrev.h>
Public Types
typedef std::map< uint64_t, DWARFAbbreviationDeclarationSet > DWARFAbbreviationDeclarationCollMap
typedef DWARFAbbreviationDeclarationCollMap::iterator DWARFAbbreviationDeclarationCollMapIter
typedef DWARFAbbreviationDeclarationCollMap::const_iterator DWARFAbbreviationDeclarationCollMapConstIter
Public Member Functions
DWARFDebugAbbrev ()
const DWARFAbbreviationDeclarationSet * getAbbreviationDeclarationSet (uint64_t cu_abbr_offset) const
void dump (raw_ostream &OS) const
void parse (DataExtractor data)
Detailed Description
Definition at line 50 of file DWARFDebugAbbrev.h.
Member Typedef Documentation
typedef std::map<uint64_t, DWARFAbbreviationDeclarationSet> llvm::DWARFDebugAbbrev::DWARFAbbreviationDeclarationCollMap
Definition at line 53 of file DWARFDebugAbbrev.h.
typedef DWARFAbbreviationDeclarationCollMap::const_iterator llvm::DWARFDebugAbbrev::DWARFAbbreviationDeclarationCollMapConstIter
Definition at line 57 of file DWARFDebugAbbrev.h.
typedef DWARFAbbreviationDeclarationCollMap::iterator llvm::DWARFDebugAbbrev::DWARFAbbreviationDeclarationCollMapIter
Definition at line 55 of file DWARFDebugAbbrev.h.
Constructor & Destructor Documentation
DWARFDebugAbbrev::DWARFDebugAbbrev ()
Definition at line 58 of file DWARFDebugAbbrev.cpp.
Member Function Documentation
void DWARFDebugAbbrev::dump (raw_ostream & OS) const
Definition at line 78 of file DWARFDebugAbbrev.cpp.
References llvm::format().
const DWARFAbbreviationDeclarationSet * DWARFDebugAbbrev::getAbbreviationDeclarationSet (uint64_t cu_abbr_offset) const
Definition at line 92 of file DWARFDebugAbbrev.cpp.
References llvm::sys::path::end().
Referenced by llvm::DWARFUnit::extractImpl().
void DWARFDebugAbbrev::parse (DataExtractor data)
Definition at line 63 of file DWARFDebugAbbrev.cpp.
References llvm::DWARFAbbreviationDeclarationSet::extract(), and llvm::DataExtractor::isValidOffset().
The documentation for this class was generated from the following files:
DWARFDebugAbbrev.h
DWARFDebugAbbrev.cpp