LLVM: llvm::Instruction Class Reference
LLVM API Documentation
llvm::Instruction Class Reference abstract
#include <Instruction.h>
Public Types
enum OperationEquivalenceFlags { CompareIgnoringAlignment = 1<<0, CompareUsingScalarTypes = 1<<1 }
enum TermOps
enum BinaryOps
enum MemoryOps
enum CastOps
enum OtherOps
Public Types inherited from llvm::User
typedef Use * op_iterator
typedef const Use * const_op_iterator
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal, BasicBlockVal, FunctionVal, GlobalAliasVal,
GlobalVariableVal, UndefValueVal, BlockAddressVal, ConstantExprVal,
ConstantAggregateZeroVal, ConstantDataArrayVal, ConstantDataVectorVal, ConstantIntVal,
ConstantFPVal, ConstantArrayVal, ConstantStructVal, ConstantVectorVal,
ConstantPointerNullVal, MDNodeVal, MDStringVal, InlineAsmVal,
PseudoSourceValueVal, FixedStackPseudoSourceValueVal, InstructionVal, ConstantFirstVal = FunctionVal,
ConstantLastVal = ConstantPointerNullVal
}
typedef value_use_iterator< User > use_iterator
typedef value_use_iterator< const User > const_use_iterator
Public Member Functions
~Instruction ()
Instruction * use_back ()
const Instruction * use_back () const
const BasicBlock * getParent () const
BasicBlock * getParent ()
void removeFromParent ()
void eraseFromParent ()
void insertBefore (Instruction *InsertPos)
void insertAfter (Instruction *InsertPos)
void moveBefore (Instruction *MovePos)
unsigned getOpcode () const
getOpcode() returns a member of one of the enums like Instruction::Add.
const char * getOpcodeName () const
bool isTerminator () const
bool isBinaryOp () const
bool isShift ()
bool isCast () const
bool isLogicalShift () const
bool isArithmeticShift () const
isArithmeticShift - Return true if this is an arithmetic shift right.
bool hasMetadata () const
bool hasMetadataOtherThanDebugLoc () const
MDNode * getMetadata (unsigned KindID) const
MDNode * getMetadata (StringRef Kind) const
void getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
void getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode * > > &MDs) const
void setMetadata (unsigned KindID, MDNode *Node)
void setMetadata (StringRef Kind, MDNode *Node)
void setDebugLoc (const DebugLoc &Loc)
setDebugLoc - Set the debug location information for this instruction.
const DebugLoc & getDebugLoc () const
getDebugLoc - Return the debug location for this node as a DebugLoc.
void setHasUnsafeAlgebra (bool B)
void setHasNoNaNs (bool B)
void setHasNoInfs (bool B)
void setHasNoSignedZeros (bool B)
void setHasAllowReciprocal (bool B)
void setFastMathFlags (FastMathFlags FMF)
bool hasUnsafeAlgebra () const
Determine whether the unsafe-algebra flag is set.
bool hasNoNaNs () const
Determine whether the no-NaNs flag is set.
bool hasNoInfs () const
Determine whether the no-infs flag is set.
bool hasNoSignedZeros () const
Determine whether the no-signed-zeros flag is set.
bool hasAllowReciprocal () const
Determine whether the allow-reciprocal flag is set.
FastMathFlags getFastMathFlags () const
void copyFastMathFlags (const Instruction *I)
Copy I's fast-math flags.
bool isAssociative () const
bool isCommutative () const
bool isIdempotent () const
bool isNilpotent () const
bool mayWriteToMemory () const
bool mayReadFromMemory () const
bool mayReadOrWriteMemory () const
bool mayThrow () const
bool mayReturn () const
bool mayHaveSideEffects () const
Instruction * clone () const
bool isIdenticalTo (const Instruction *I) const
bool isIdenticalToWhenDefined (const Instruction *I) const
bool isSameOperationAs (const Instruction *I, unsigned flags=0) const
Determine if one instruction is the same operation as another.
bool isUsedOutsideOfBlock (const BasicBlock *BB) const
Public Member Functions inherited from llvm::User
~User ()
void operator delete (void *Usr)
operator delete - free memory allocated for User and Use objects
void operator delete (void *, unsigned)
placement delete - required by std, but never called.
void operator delete (void *, unsigned, bool)
placement delete - required by std, but never called.
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
void dropAllReferences ()
void replaceUsesOfWith (Value *From, Value *To)
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
dump - Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O, AssemblyAnnotationWriter *AAW=0) const
Type * getType () const
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
void setName (const Twine &Name)
void takeName (Value *V)
void replaceAllUsesWith (Value *V)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
User * use_back ()
const User * use_back () const
bool hasOneUse () const
bool hasNUses (unsigned N) const
bool hasNUsesOrMore (unsigned N) const
bool isUsedInBasicBlock (const BasicBlock *BB) const
unsigned getNumUses () const
void addUse (Use &U)
unsigned getValueID () const
unsigned getRawSubclassOptionalData () const
void clearSubclassOptionalData ()
bool hasSameSubclassOptionalData (const Value *V) const
void intersectOptionalDataWith (const Value *V)
bool hasValueHandle () const
Value * stripPointerCasts ()
Strips off any unneeded pointer casts, all-zero GEPs and aliases from the specified value, returning the original uncasted value.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strips off any unneeded pointer casts and all-zero GEPs from the specified value, returning the original uncasted value.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strips off unneeded pointer casts and all-constant GEPs from the specified value, returning the original pointer value.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Strips like stripInBoundsConstantOffsets but also accumulates the constant offset stripped.
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strips off unneeded pointer casts and any in-bounds offsets from the specified value, returning the original pointer value.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer () const
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Public Member Functions inherited from llvm::ilist_node< Instruction >
Instruction * getPrevNode ()
Get the previous node, or 0 for the list head.
const Instruction * getPrevNode () const
Get the previous node, or 0 for the list head.
Instruction * getNextNode ()
Get the next node, or 0 for the list tail.
const Instruction * getNextNode () const
Get the next node, or 0 for the list tail.
Static Public Member Functions
static const char * getOpcodeName (unsigned OpCode)
static bool isTerminator (unsigned OpCode)
static bool isBinaryOp (unsigned Opcode)
static bool isShift (unsigned Opcode)
Determine if the Opcode is one of the shift instructions.
static bool isCast (unsigned OpCode)
Determine if the OpCode is one of the CastInst instructions.
static bool isAssociative (unsigned op)
static bool isCommutative (unsigned op)
static bool isIdempotent (unsigned op)
static bool isNilpotent (unsigned op)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Protected Member Functions
void setInstructionSubclassData (unsigned short D)
unsigned getSubclassDataFromInstruction () const
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, Instruction *InsertBefore=0)
Instruction (Type *Ty, unsigned iType, Use *Ops, unsigned NumOps, BasicBlock *InsertAtEnd)
virtual Instruction * clone_impl () const =0
Protected Member Functions inherited from llvm::User
void * operator new (size_t s, unsigned Us)
User (Type *ty, unsigned vty, Use *OpList, unsigned NumOps)
Use * allocHungoffUses (unsigned) const
void dropHungoffUses ()
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
virtual void printCustom (raw_ostream &O) const
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Member Functions inherited from llvm::ilist_node< Instruction >
ilist_node ()
Friends
class SymbolTableListTraits< Instruction, BasicBlock >
Additional Inherited Members
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::User
Use * OperandList
unsigned NumOperands
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Detailed Description
Definition at line 31 of file Instruction.h.
Member Enumeration Documentation
enum llvm::Instruction::BinaryOps
Definition at line 387 of file Instruction.h.
enum llvm::Instruction::CastOps
Definition at line 401 of file Instruction.h.
enum llvm::Instruction::MemoryOps
Definition at line 394 of file Instruction.h.
enum llvm::Instruction::OperationEquivalenceFlags
When checking for operation equivalence (using isSameOperationAs) it is sometimes useful to ignore certain attributes.
Enumerator
CompareIgnoringAlignment
Check for equivalence ignoring load/store alignment.
CompareUsingScalarTypes
Check for equivalence treating a type and a vector of that type as equivalent.
Definition at line 347 of file Instruction.h.
enum llvm::Instruction::OtherOps
Definition at line 408 of file Instruction.h.
enum llvm::Instruction::TermOps
Definition at line 380 of file Instruction.h.
Constructor & Destructor Documentation
Instruction::~Instruction ()
Definition at line 51 of file Instruction.cpp.
References llvm::LeakDetector::addGarbageObject(), getParent(), P, and llvm::LeakDetector::removeGarbageObject().
Instruction::Instruction (Type * Ty, unsigned iType, Use * Ops, unsigned NumOps, Instruction * InsertBefore = 0) protected
Definition at line 24 of file Instruction.cpp.
References llvm::LeakDetector::addGarbageObject(), llvm::BasicBlock::getInstList(), getParent(), and llvm::iplist< NodeTy, Traits >::insert().
Instruction::Instruction (Type * Ty, unsigned iType, Use * Ops, unsigned NumOps, BasicBlock * InsertAtEnd) protected
Definition at line 38 of file Instruction.cpp.
References llvm::LeakDetector::addGarbageObject(), llvm::BasicBlock::getInstList(), and llvm::iplist< NodeTy, Traits >::push_back().
Member Function Documentation
static bool llvm::Instruction::classof (const Value * V) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 373 of file Instruction.h.
References llvm::Value::getValueID(), and llvm::Value::InstructionVal.
Instruction * Instruction::clone () const
clone() - Create a copy of 'this' instruction that is identical in all ways except the following:
The instruction has no parent
The instruction has no name
Definition at line 541 of file Instruction.cpp.
References clone_impl(), getAllMetadataOtherThanDebugLoc(), getDebugLoc(), hasMetadata(), i, setDebugLoc(), setMetadata(), llvm::SmallVectorTemplateCommon< T >::size(), and llvm::Value::SubclassOptionalData.
Referenced by llvm::CloneBasicBlock(), llvm::CloneFunction(), ConvertToSInt(), llvm::createLICMPass(), llvm::createLoopVectorizePass(), llvm::createObjCARCOptPass(), llvm::FoldBranchToCommonDest(), llvm::FoldReturnIntoUncondBranch(), getGEPInductionOperand(), HoistThenElseCodeToIf(), INITIALIZE_PASS(), isAlwaysFoldable(), isOnlyReachableViaThisEdge(), mayHaveSideEffects(), shouldSpeculateInstrs(), and llvm::SplitLandingPadPredecessors().
virtual Instruction* llvm::Instruction::clone_impl () const protected pure virtual
Implemented in llvm::AddrSpaceCastInst, llvm::BitCastInst, llvm::PtrToIntInst, llvm::IntToPtrInst, llvm::FPToSIInst, llvm::FPToUIInst, llvm::SIToFPInst, llvm::UIToFPInst, llvm::FPExtInst, llvm::FPTruncInst, llvm::SExtInst, llvm::ZExtInst, llvm::TruncInst, llvm::UnreachableInst, llvm::ResumeInst, llvm::InvokeInst, llvm::IndirectBrInst, llvm::SwitchInst, llvm::BranchInst, llvm::ReturnInst, llvm::LandingPadInst, llvm::PHINode, llvm::InsertValueInst, llvm::ExtractValueInst, llvm::ShuffleVectorInst, llvm::InsertElementInst, llvm::ExtractElementInst, llvm::VAArgInst, llvm::SelectInst, llvm::CallInst, llvm::FCmpInst, llvm::ICmpInst, llvm::GetElementPtrInst, llvm::AtomicRMWInst, llvm::AtomicCmpXchgInst, llvm::FenceInst, llvm::StoreInst, llvm::BinaryOperator, llvm::LoadInst, llvm::AllocaInst, and llvm::TerminatorInst.
Referenced by clone(), and getSubclassDataFromInstruction().
void Instruction::copyFastMathFlags (const Instruction * I)
Copy I's fast-math flags.
Definition at line 181 of file Instruction.cpp.
References getFastMathFlags(), and setFastMathFlags().
Referenced by getDebugLoc(), llvm::InstCombiner::visitFMul(), and llvm::InstCombiner::visitFSub().
void Instruction::eraseFromParent ()
eraseFromParent - This method unlinks 'this' from the containing basic block and deletes it.
Definition at line 72 of file Instruction.cpp.
References llvm::iplist< NodeTy, Traits >::erase(), llvm::BasicBlock::getInstList(), and getParent().
Referenced by AddPHINodeEntriesForMappedBlock(), AddReachableCodeToWorklist(), AddressIsTaken(), buildMultiplyTree(), BuildSubAggregate(), CanTRE(), changeToCall(), checkCSEInPredecessor(), CleanupPointerRootUsers(), llvm::CloneAndPruneFunctionInto(), CloneLoop(), CloneLoopBlocks(), ComputePostOrders(), ConnectProlog(), llvm::ConstantFoldTerminator(), ConvertToSInt(), llvm::createConstantPropagationPass(), llvm::createCorrelatedValuePropagationPass(), llvm::createDeadArgHackingPass(), llvm::createDwarfEHPass(), llvm::createEarlyCSEPass(), createFailOrdering(), llvm::createLICMPass(), llvm::createLoopSimplifyPass(), llvm::createObjCARCContractPass(), llvm::createObjCARCOptPass(), createPrivateNonConstGlobalForString(), CreatePrologue(), cse(), cxxDtorIsEmpty(), DeleteDeadInstruction(), deleteDeadInstruction(), DeleteInstructionInBlock(), DeleteTriviallyDeadInstructions(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), llvm::InstCombiner::DoOneIteration(), llvm::EliminateDuplicatePHINodes(), enqueueUsersInWorklist(), llvm::InstCombiner::EraseInstFromFunction(), llvm::objcarc::EraseInstruction(), EraseTerminatorInstAndDCECond(), llvm::expandDivision(), llvm::expandDivisionUpTo32Bits(), llvm::expandRemainder(), llvm::expandRemainderUpTo32Bits(), FindMostPopularDest(), FindPhiPredForUseInBlock(), FindPHIToPartitionLoops(), llvm::FoldReturnIntoUncondBranch(), FoldTwoEntryPHINode(), generateUnsignedDivisionCode(), getGEPInductionOperand(), getParent(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), hasAddressTakenAndUsed(), INITIALIZE_PASS(), InlineCallIfPossible(), llvm::InlineFunction(), insertFastDiv(), insertVector(), isAlwaysFoldable(), isFormingBranchFromSelectProfitable(), isLifetimeStart(), isOnlyReachableViaThisEdge(), isSimpleLoadStore(), LowerAtomicCmpXchgInst(), LowerAtomicRMWInst(), llvm::LowerDbgDeclare(), LowerFenceInst(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::IntrinsicLowering::LowerToByteSwap(), markAliveBlocks(), MarkBlocksLiveIn(), MarkIndicesSafe(), llvm::MergeBasicBlockIntoOnlyPred(), mergeEmptyReturnBlocks(), OptimizeCmpExpression(), OptimizeGlobalAddressOfMalloc(), OptimizeNoopCopyExpression(), PerformHeapAllocSRoA(), llvm::PHITransAddr::PHITranslateWithInsertion(), promoteSingleBlockAlloca(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), removeFinishedSplitUses(), removeLifetimeIntrinsicUsers(), llvm::BasicBlock::removePredecessor(), removeUndefIntroducingPredecessor(), llvm::LibCallSimplifier::replaceAllUsesWith(), replaceAndRecursivelySimplifyImpl(), llvm::replaceDbgDeclareForAlloca(), ReplaceUsesOfMallocWithGlobal(), ReplaceUsesOfWith(), reuseOrInsertFastDiv(), rewriteSingleStoreAlloca(), RewriteUsesOfLoadForHeapSRoA(), llvm::LoadAndStorePromoter::run(), llvm::NVPTXLowerAggrCopies::runOnFunction(), llvm::Inliner::runOnSCC(), shouldSpeculateInstrs(), SimplifyBranchOnICmpChain(), AllocaSlices::SliceBuilder::SliceBuilder(), speculatePHINodeLoads(), speculateSelectInstLoads(), llvm::SplitLandingPadPredecessors(), llvm::StripDebugInfo(), StripSymbolNames(), SwitchToLookupTable(), tryToMakeAllocaBePromotable(), TryToOptimizeStoreOfMallocToGlobal(), TryToShrinkGlobalToBoolean(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), TryToSimplifyUncondBranchWithICmpInIt(), TurnSwitchRangeIntoICmp(), llvm::UnrollLoop(), llvm::UpgradeIntrinsicCall(), and llvm::ObjectSizeOffsetEvaluator::visitPHINode().
void llvm::Instruction::getAllMetadata (SmallVectorImpl< std::pair< unsigned, MDNode * > > & MDs) const inline
getAllMetadata - Get all metadata attached to this Instruction. The first element of each pair returned is the KindID, the second element is the metadata value. This list is returned sorted by the KindID.
Definition at line 155 of file Instruction.h.
References hasMetadata().
Referenced by llvm::AssemblyWriter::printInstruction(), and llvm::RemapInstruction().
void llvm::Instruction::getAllMetadataOtherThanDebugLoc (SmallVectorImpl< std::pair< unsigned, MDNode * > > & MDs) const inline
getAllMetadataOtherThanDebugLoc - This does the same thing as getAllMetadata, except that it filters out the debug location.
Definition at line 162 of file Instruction.h.
References hasMetadataOtherThanDebugLoc(), and setMetadata().
Referenced by clone(), and llvm::TypeFinder::run().
const DebugLoc& llvm::Instruction::getDebugLoc () const inline
getDebugLoc - Return the debug location for this node as a DebugLoc.
Definition at line 178 of file Instruction.h.
References B, copyFastMathFlags(), getFastMathFlags(), hasAllowReciprocal(), hasNoInfs(), hasNoNaNs(), hasNoSignedZeros(), hasUnsafeAlgebra(), I, isAssociative(), setFastMathFlags(), setHasAllowReciprocal(), setHasNoInfs(), setHasNoNaNs(), setHasNoSignedZeros(), and setHasUnsafeAlgebra().
Referenced by AddPHINodeEntriesForMappedBlock(), BreakUpSubtract(), buildMultiplyTree(), canFoldIVIncExpr(), changeToCall(), changeToUnreachable(), checkInterfaceFunction(), clone(), llvm::ConvertDebugDeclareToDebugValue(), ConvertShiftToMul(), createAndInstr(), llvm::createDeadArgHackingPass(), llvm::createObjCARCContractPass(), createPrivateNonConstGlobalForString(), deleteIfDeadInstruction(), llvm::InstCombiner::DoOneIteration(), llvm::FastISel::FastEmitZExtFromI1(), FindInitTrampoline(), FirstNonDbg(), FitWeights(), fixupLineNumbers(), llvm::SelectionDAGBuilder::getCurDebugLoc(), llvm::SDLoc::getDebugLoc(), GetLoadValueForLoad(), getMemSetPatternValue(), getTruncatedArgReg(), hasAddressTakenAndUsed(), llvm::SCEVExpander::hoistIVInc(), llvm::InlineFunction(), llvm::InstCombiner::InsertNewInstWith(), llvm::InsertPreheaderForLoop(), llvm::IRBuilder< true, TargetFolder >::IRBuilder(), isLifetimeStart(), isOnlyReachableViaThisEdge(), isSafeAndProfitableToSinkLoad(), LowerNegateToMultiply(), llvm::SCEVExpander::replaceCongruentIVs(), llvm::FastISel::SelectInstruction(), llvm::FastISel::SelectOperator(), llvm::FunctionLoweringInfo::set(), llvm::IRBuilderBase::SetInsertPoint(), SimplifyBranchOnICmpChain(), SimplifyTerminatorOnSelect(), AllocaSlices::SliceBuilder::SliceBuilder(), llvm::SplitCriticalEdge(), TryToSimplifyUncondBranchWithICmpInIt(), llvm::InstCombiner::visitFDiv(), llvm::InstCombiner::visitStoreInst(), and llvm::InstCombiner::visitXor().
FastMathFlags Instruction::getFastMathFlags () const
Convenience function for getting all the fast-math flags, which must be an operator which supports these flags. See LangRef.html for the meaning of these flats.
Definition at line 175 of file Instruction.cpp.
Referenced by ClearSubclassDataAfterReassociation(), copyFastMathFlags(), getDebugLoc(), llvm::SimplifyInstruction(), llvm::InstCombiner::visitFAdd(), llvm::InstCombiner::visitFDiv(), llvm::InstCombiner::visitFMul(), and llvm::InstCombiner::visitFSub().
MDNode* llvm::Instruction::getMetadata (unsigned KindID) const inline
getMetadata - Get the metadata of given kind attached to this Instruction. If the metadata is not found then return null.
Definition at line 140 of file Instruction.h.
References hasMetadata().
Referenced by llvm::AliasSetTracker::add(), CheckForCanReleaseCFGHazard(), llvm::createBasicAliasAnalysisPass(), llvm::createFunctionAttrsPass(), llvm::createLICMPass(), llvm::LLVMContext::emitError(), ExtractBranchMetadata(), llvm::getAlign(), GetBranchWeights(), llvm::FPMathOperator::getFPAccuracy(), llvm::AliasAnalysis::getLocation(), llvm::AliasAnalysis::getLocationForDest(), llvm::AliasAnalysis::getLocationForSource(), llvm::Loop::getLoopID(), getMaxWeightFor(), llvm::AliasAnalysis::getModRefInfo(), llvm::MemoryDependenceAnalysis::getPointerDependencyFrom(), GetRegistersForValue(), hasAddressTakenAndUsed(), HasBranchWeights(), isContiguous(), isLifetimeStart(), isSequentialInRange(), isStructPathTBAA(), isVtableAccess(), MarkIndicesSafe(), patchReplacementInstruction(), reduceToSingleValueType(), llvm::AliasSetTracker::remove(), speculatePHINodeLoads(), speculateSelectInstLoads(), llvm::BranchInst::swapSuccessors(), tryToMakeAllocaBePromotable(), llvm::UpgradeInstWithTBAATag(), ValuesOverlap(), and llvm::InstCombiner::visitStoreInst().
MDNode* llvm::Instruction::getMetadata (StringRef Kind) const inline
getMetadata - Get the metadata of given kind attached to this Instruction. If the metadata is not found then return null.
Definition at line 147 of file Instruction.h.
References hasMetadata().
unsigned llvm::Instruction::getOpcode () const inline
getOpcode() returns a member of one of the enums like Instruction::Add.
Definition at line 83 of file Instruction.h.
References llvm::Value::getValueID(), and llvm::Value::InstructionVal.
Referenced by areAllUsesIn(), buildMultiplyTree(), BuildNew(), CanEvaluateSExtd(), CanEvaluateShifted(), CanEvaluateShuffled(), CanEvaluateTruncated(), CanEvaluateZExtd(), CanPHITrans(), CheapToScalarize(), llvm::OverflowingBinaryOperator::classof(), llvm::AllocaInst::classof(), llvm::UnaryInstruction::classof(), llvm::PossiblyExactOperator::classof(), llvm::LoadInst::classof(), llvm::ConcreteOperator< OverflowingBinaryOperator, Instruction::Mul >::classof(), llvm::StoreInst::classof(), llvm::FenceInst::classof(), llvm::AtomicCmpXchgInst::classof(), llvm::AtomicRMWInst::classof(), llvm::CmpInst::classof(), llvm::GetElementPtrInst::classof(), llvm::ICmpInst::classof(), llvm::FCmpInst::classof(), llvm::CallInst::classof(), llvm::SelectInst::classof(), llvm::VAArgInst::classof(), llvm::ExtractElementInst::classof(), llvm::InsertElementInst::classof(), llvm::ShuffleVectorInst::classof(), llvm::ExtractValueInst::classof(), llvm::InsertValueInst::classof(), llvm::PHINode::classof(), llvm::LandingPadInst::classof(), llvm::ReturnInst::classof(), llvm::BranchInst::classof(), llvm::SwitchInst::classof(), llvm::IndirectBrInst::classof(), llvm::InvokeInst::classof(), llvm::ResumeInst::classof(), llvm::UnreachableInst::classof(), llvm::TruncInst::classof(), llvm::ZExtInst::classof(), llvm::SExtInst::classof(), llvm::FPTruncInst::classof(), llvm::FPExtInst::classof(), llvm::UIToFPInst::classof(), llvm::SIToFPInst::classof(), llvm::FPToUIInst::classof(), llvm::FPToSIInst::classof(), llvm::IntToPtrInst::classof(), llvm::PtrToIntInst::classof(), llvm::BitCastInst::classof(), llvm::AddrSpaceCastInst::classof(), CollectBSwapParts(), collectFailStats(), CollectInsertionElements(), computeBytesPoppedByCallee(), ConstantFold(), llvm::ConstantFoldInstruction(), ConvertAtomicSynchScope(), ConvertToSInt(), llvm::createCorrelatedValuePropagationPass(), createMinMaxOp(), DecomposeSimpleLinearExpr(), deleteIfDeadInstruction(), detectLog2OfHalf(), determinePointerReadAttrs(), dyn_castFoldableMul(), EvaluateExpression(), llvm::SelectionDAGBuilder::FindMergedConditions(), llvm::InstCombiner::foldFMulConst(), FoldOperationIntoSelectOperand(), llvm::InstCombiner::FoldSelectOpOp(), GatherConstantCompares(), getComparePred(), getFCmpValue(), llvm::DenseMapInfo< ComparableFunction >::getHashValue(), llvm::SCEVExpander::getIVIncOperand(), getKnownConstant(), getLoopPhiForCounter(), llvm::AliasAnalysis::getModRefInfo(), llvm::BinaryOperator::getOpcode(), llvm::CastInst::getOpcode(), llvm::CmpInst::getOpcode(), llvm::SelectInst::getOpcode(), getOpcodeName(), GetSelectFoldableConstant(), GetSelectFoldableOperands(), GetShiftedValue(), llvm::DenseMapInfo< SimpleValue >::getTombstoneKey(), llvm::DenseMapInfo< CallValue >::getTombstoneKey(), hasAddressTakenAndUsed(), llvm::InlineFunction(), InstructionDereferencesPointer(), isAllocSiteRemovable(), isArithmeticShift(), isAssociative(), isBinaryOp(), isCast(), isCommutative(), llvm::DenseMapInfo< Expression >::isEqual(), isFMulOrFDivWithConstant(), isHighCostExpansion(), isIdempotent(), isIdenticalToWhenDefined(), isLikelyComplexAddressComputation(), isLogicalShift(), isNilpotent(), isRunOfOnes(), isSameOperationAs(), isShift(), isTerminator(), isUnmovableInstruction(), llvm::FastISel::LowerArguments(), matchVectorSplittingReduction(), mayReadFromMemory(), mayWriteToMemory(), OptimizeCmpExpression(), llvm::PHITransAddr::PHITranslateWithInsertion(), llvm::PointerMayBeCaptured(), PrintOps(), RemoveInstInputs(), llvm::FastISel::SelectInstruction(), shouldMergeGEPs(), ShrinkDemandedConstant(), SimplifyBranchOnICmpChain(), llvm::SimplifyInstruction(), SimplifyWithOpReplaced(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), ThreadBinOpOverSelect(), llvm::InstVisitor< ObjectSizeOffsetVisitor, SizeOffsetType >::visit(), llvm::SelectionDAGBuilder::visit(), llvm::Interpreter::visitAllocaInst(), llvm::InstCombiner::visitFMul(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitSwitchInst(), WriteInstruction(), and X86ChooseCmpImmediateOpcode().
const char* llvm::Instruction::getOpcodeName () const inline
Definition at line 85 of file Instruction.h.
References getOpcode(), and getOpcodeName().
Referenced by createPrivateNonConstGlobalForString(), llvm::ScalarEvolution::forgetValue(), getOpcodeName(), llvm::ConstantExpr::getOpcodeName(), isCast(), llvm::AssemblyWriter::printInstruction(), and PrintOps().
const char * Instruction::getOpcodeName (unsigned OpCode) static
Definition at line 186 of file Instruction.cpp.
References llvm::APIntOps::And(), llvm::Call, ExtractElement(), llvm::SPII::Load, llvm::APIntOps::Or(), llvm::TargetOpcode::PHI, llvm::AArch64ISD::Ret, llvm::MCID::Select, llvm::SPII::Store, and llvm::APIntOps::Xor().
const BasicBlock* llvm::Instruction::getParent () const inline
Definition at line 52 of file Instruction.h.
Referenced by AddPHINodeEntriesForMappedBlock(), AddressIsTaken(), llvm::IVUsers::AddUsersImpl(), areAllUsesIn(), BlockIsSimpleEnoughToThreadThrough(), BuildConstantFromSCEV(), canConstantEvolve(), canFoldIVIncExpr(), llvm::AliasAnalysis::canInstructionRangeModify(), CanSelectOperandBeMappingIntoPredBlock(), CanTRE(), changeToCall(), changeToUnreachable(), llvm::CloneAndPruneFunctionInto(), CollectBSwapParts(), computeBytesPoppedByCallee(), ComputePostOrders(), ComputeRange(), ConstructSSAForLoadSet(), llvm::Region::contains(), convertMemSetToLoop(), ConvertToSInt(), convertTransferToLoop(), llvm::createArgumentPromotionPass(), llvm::createCodeGenPreparePass(), llvm::createCorrelatedValuePropagationPass(), llvm::createDwarfEHPass(), createFree(), llvm::createLICMPass(), llvm::createLoopSimplifyPass(), createMalloc(), llvm::createMergeFunctionsPass(), llvm::createObjCARCContractPass(), llvm::createObjCARCOptPass(), createPrivateNonConstGlobalForString(), llvm::createSinkingPass(), cse(), DecomposeSimpleLinearExpr(), deleteIfDeadInstruction(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), llvm::DependenceAnalysis::depends(), llvm::DominatorTree::dominates(), DominatesMergePoint(), llvm::InstCombiner::DoOneIteration(), llvm::Value::DoPHITranslation(), EliminateDeadSwitchCases(), eraseFromParent(), EvaluateExpression(), llvm::SCEVExpander::expandCodeFor(), FindInitTrampolineFromBB(), llvm::SelectionDAGBuilder::FindMergedConditions(), FindMostPopularDest(), FindPhiPredForUseInBlock(), FindUnconditionalPreds(), FirstNonDbg(), FitWeights(), llvm::SimplifyFortifiedLibCalls::fold(), llvm::FoldBranchToCommonDest(), FoldCondBranchOnPHI(), FoldOperationIntoSelectOperand(), FoldTwoEntryPHINode(), llvm::ScalarEvolution::forgetValue(), GetCaseResults(), getCommonReturnValue(), getComparePred(), llvm::MemoryDependenceAnalysis::getDependency(), getInsertPointForUses(), getKnownConstant(), llvm::MemoryDependenceAnalysis::getLoadLoadClobberFullWidthSize(), GetLoadValueForLoad(), getLoopPhiForCounter(), GetMemInstValueForLoad(), getMemSetPatternValue(), llvm::AliasAnalysis::getModRefInfo(), llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), llvm::MemoryDependenceAnalysis::getNonLocalPointerDependency(), getPointerOperand(), llvm::DependenceAnalysis::getSplitIteration(), GetStoreValueForLoad(), getTruncatedArgReg(), llvm::SelectionDAGBuilder::getValueImpl(), HandleByValArgument(), HandleInlinedInvoke(), hasAddressTakenAndUsed(), HasSafePathToPredecessorCall(), llvm::SCEVExpander::hoistIVInc(), HoistThenElseCodeToIf(), InBlock(), INITIALIZE_PASS(), InlineCallIfPossible(), llvm::InlineFunction(), insertAfter(), insertBefore(), llvm::InstCombiner::InsertNewInstBefore(), Instruction(), llvm::isAllocaPromotable(), isContiguous(), isDynamicConstant(), llvm::SparseSolver::isEdgeFeasible(), llvm::DenseMapInfo< Expression >::isEqual(), isExitBlock(), isFormingBranchFromSelectProfitable(), llvm::isInTailCallPosition(), isInteresting(), isLifetimeStart(), isLoopInvariant(), IsNonLocalValue(), llvm::SCEVUnknown::isOffsetOf(), isOnlyReachableViaThisEdge(), llvm::isPotentiallyReachable(), isProfitableToFoldUnconditional(), llvm::DominatorTree::isReachableFromEntry(), isSafeAndProfitableToSinkLoad(), isSafePHIToSpeculate(), llvm::isSafeToLoadUnconditionally(), isSafeToMove(), llvm::AllocaInst::isStaticAlloca(), llvm::Value::isUsedInBasicBlock(), isUsedOutsideOfDefiningBlock(), isZero(), IVUseShouldUsePostIncValue(), LdStHasDebugValue(), LLVMGetNextInstruction(), LLVMGetPreviousInstruction(), LLVMPositionBuilderBefore(), llvm::FastISel::LowerArguments(), LowerAtomicCmpXchgInst(), LowerAtomicRMWInst(), LowerBSWAP(), LowerCTLZ(), LowerCTPOP(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::IntrinsicLowering::LowerToByteSwap(), MarkBlocksLiveIn(), MarkIndicesSafe(), MergeAliasResults(), moveBefore(), NegateValue(), operator<<(), llvm::operator<<(), OptimizeCmpExpression(), OptimizeNoopCopyExpression(), passingValueIsAlwaysUndefined(), PerformHeapAllocSRoA(), PickMostRelevantLoop(), PrintOps(), ProcessUAddIdiom(), ProcessUGT_ADDCST_ADD(), promoteSingleBlockAlloca(), PushDefUseChildren(), removeFromParent(), RemoveInstInputs(), replaceAndRecursivelySimplifyImpl(), ReplaceCallWith(), llvm::replaceDbgDeclareForAlloca(), llvm::ReplaceInstWithInst(), llvm::LoopInfo::replacementPreservesLCSSAForm(), ReplaceUsesOfWith(), rewriteSingleStoreAlloca(), llvm::SSAUpdater::RewriteUse(), llvm::SSAUpdater::RewriteUseAfterInsertions(), RewriteUsesOfClonedInstructions(), llvm::LoadAndStorePromoter::run(), llvm::NVPTXSplitBBatBar::runOnFunction(), SafeToMergeTerminators(), llvm::FastISel::SelectInstruction(), llvm::IRBuilderBase::SetInsertPoint(), SimplifyBranchOnICmpChain(), SimplifyCondBranchToCondBranch(), SimplifyCondBranchToTwoReturns(), llvm::InstCombiner::SimplifyDivRemOfSelect(), SimplifyTerminatorOnSelect(), llvm::simplifyUsersOfIV(), SinkThenElseCodeToEnd(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), llvm::SparseSolver::Solve(), SortNonLocalDepInfoCache(), SpeculativelyExecuteBB(), llvm::SplitBlockAndInsertIfThen(), llvm::SplitCriticalEdge(), SwitchToLookupTable(), llvm::FastISel::tryToFoldLoad(), tryToMoveFreeBeforeNullTest(), TryToSimplifyUncondBranchWithICmpInIt(), TryToSinkInstruction(), TurnSwitchRangeIntoICmp(), UpdateCallGraphAfterInlining(), llvm::UpgradeIntrinsicCall(), useFuncSeen(), ValueDominatesPHI(), ValuesOverlap(), llvm::SelectionDAGBuilder::visit(), llvm::InstCombiner::visitAllocaInst(), llvm::InstCombiner::visitCallInst(), llvm::Interpreter::visitCallSite(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitFPTrunc(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitLoadInst(), llvm::InstCombiner::visitPHINode(), llvm::InstCombiner::visitStoreInst(), X86ChooseCmpImmediateOpcode(), and ~Instruction().
BasicBlock* llvm::Instruction::getParent () inline
Definition at line 53 of file Instruction.h.
References eraseFromParent(), insertAfter(), insertBefore(), moveBefore(), and removeFromParent().
unsigned llvm::Instruction::getSubclassDataFromInstruction () const inline protected
Definition at line 441 of file Instruction.h.
References clone_impl().
Referenced by llvm::AllocaInst::getAlignment(), llvm::LoadInst::getAlignment(), llvm::StoreInst::getAlignment(), llvm::CallInst::getCallingConv(), llvm::InvokeInst::getCallingConv(), llvm::AtomicRMWInst::getOperation(), llvm::LoadInst::getOrdering(), llvm::StoreInst::getOrdering(), llvm::FenceInst::getOrdering(), llvm::AtomicCmpXchgInst::getOrdering(), llvm::AtomicRMWInst::getOrdering(), llvm::CmpInst::getPredicate(), llvm::LoadInst::getSynchScope(), llvm::StoreInst::getSynchScope(), llvm::FenceInst::getSynchScope(), llvm::AtomicCmpXchgInst::getSynchScope(), llvm::AtomicRMWInst::getSynchScope(), llvm::LandingPadInst::isCleanup(), llvm::CallInst::isTailCall(), llvm::LoadInst::isVolatile(), llvm::StoreInst::isVolatile(), llvm::AtomicCmpXchgInst::isVolatile(), llvm::AtomicRMWInst::isVolatile(), llvm::LoadInst::setAlignment(), llvm::StoreInst::setAlignment(), llvm::CallInst::setCallingConv(), llvm::LandingPadInst::setCleanup(), llvm::AtomicRMWInst::setOperation(), llvm::LoadInst::setOrdering(), llvm::StoreInst::setOrdering(), llvm::FenceInst::setOrdering(), llvm::AtomicCmpXchgInst::setOrdering(), llvm::AtomicRMWInst::setOrdering(), llvm::LoadInst::setSynchScope(), llvm::StoreInst::setSynchScope(), llvm::FenceInst::setSynchScope(), llvm::AtomicCmpXchgInst::setSynchScope(), llvm::AtomicRMWInst::setSynchScope(), llvm::CallInst::setTailCall(), llvm::LoadInst::setVolatile(), llvm::StoreInst::setVolatile(), llvm::AtomicCmpXchgInst::setVolatile(), and llvm::AtomicRMWInst::setVolatile().
bool Instruction::hasAllowReciprocal () const
Determine whether the allow-reciprocal flag is set.
Definition at line 167 of file Instruction.cpp.
Referenced by getDebugLoc(), and llvm::InstCombiner::visitFDiv().
bool llvm::Instruction::hasMetadata () const inline
hasMetadata() - Return true if this instruction has any metadata attached to it.
Definition at line 128 of file Instruction.h.
References llvm::DebugLoc::isUnknown().
Referenced by clone(), getAllMetadata(), and getMetadata().
bool llvm::Instruction::hasMetadataOtherThanDebugLoc () const inline
hasMetadataOtherThanDebugLoc - Return true if this instruction has metadata attached to it other than a debug location.
Definition at line 134 of file Instruction.h.
Referenced by getAllMetadataOtherThanDebugLoc().
bool Instruction::hasNoInfs () const
Determine whether the no-infs flag is set.
Definition at line 155 of file Instruction.cpp.
Referenced by getDebugLoc(), SimplifyFAddInst(), and llvm::InstCombiner::visitFMul().
bool Instruction::hasNoNaNs () const
Determine whether the no-NaNs flag is set.
Definition at line 149 of file Instruction.cpp.
Referenced by getDebugLoc(), SimplifyFAddInst(), and llvm::InstCombiner::visitFMul().
bool Instruction::hasNoSignedZeros () const
Determine whether the no-signed-zeros flag is set.
Definition at line 161 of file Instruction.cpp.
Referenced by getDebugLoc(), llvm::BinaryOperator::isFNeg(), llvm::InstCombiner::visitFAdd(), and llvm::InstCombiner::visitFMul().
bool Instruction::hasUnsafeAlgebra () const
Determine whether the unsafe-algebra flag is set.
Definition at line 143 of file Instruction.cpp.
Referenced by detectLog2OfHalf(), getDebugLoc(), isAssociative(), llvm::InstCombiner::visitFAdd(), llvm::InstCombiner::visitFDiv(), llvm::InstCombiner::visitFMul(), and llvm::InstCombiner::visitFSub().
void Instruction::insertAfter (Instruction * InsertPos)
insertAfter - Insert an unlinked instructions into a basic block immediately after the specified instruction.
Definition at line 84 of file Instruction.cpp.
References llvm::BasicBlock::getInstList(), getParent(), and llvm::iplist< NodeTy, Traits >::insertAfter().
Referenced by getParent(), INITIALIZE_PASS_BEGIN(), isFormingBranchFromSelectProfitable(), IsNonLocalValue(), and MarkBlocksLiveIn().
void Instruction::insertBefore (Instruction * InsertPos)
insertBefore - Insert an unlinked instructions into a basic block immediately before the specified instruction.
Definition at line 78 of file Instruction.cpp.
References llvm::BasicBlock::getInstList(), getParent(), and llvm::iplist< NodeTy, Traits >::insert().
Referenced by ConvertToSInt(), llvm::createObjCARCOptPass(), getParent(), INITIALIZE_PASS(), isFormingBranchFromSelectProfitable(), isOnlyReachableViaThisEdge(), shouldSpeculateInstrs(), llvm::UnrollRuntimeLoopProlog(), and llvm::InstCombiner::visitUDiv().
bool llvm::Instruction::isArithmeticShift () const inline
isArithmeticShift - Return true if this is an arithmetic shift right.
Definition at line 113 of file Instruction.h.
References getOpcode().
bool Instruction::isAssociative () const
isAssociative - Return true if the instruction is associative:
Associative operators satisfy: x op (y op z) === (x op y) op z
In LLVM, the Add, Mul, And, Or, and Xor operators are associative.
Definition at line 482 of file Instruction.cpp.
References getOpcode(), and hasUnsafeAlgebra().
Referenced by areAllUsesIn(), buildMultiplyTree(), ClearSubclassDataAfterReassociation(), llvm::ConstantFoldBinaryInstruction(), getCommonReturnValue(), getDebugLoc(), isSimpleLoadStore(), LinearizeExprTree(), SimplifyAssociativeBinOp(), and SimplifyBinOp().
bool Instruction::isAssociative (unsigned Opcode) static
isAssociative - Return true if the instruction is associative:
Associative operators satisfy: x op (y op z) === (x op y) op z
In LLVM, the Add, Mul, And, Or, and Xor operators are associative.
Definition at line 477 of file Instruction.cpp.
References llvm::APIntOps::And(), llvm::APIntOps::Or(), and llvm::APIntOps::Xor().
bool llvm::Instruction::isBinaryOp () const inline
Definition at line 87 of file Instruction.h.
References getOpcode(), and isBinaryOp().
Referenced by llvm::BinaryOperator::classof(), llvm::ConstantFoldInstOperands(), hasUsesOutsideLoop(), INITIALIZE_PASS(), and isBinaryOp().
static bool llvm::Instruction::isBinaryOp (unsigned Opcode) inline static
Definition at line 97 of file Instruction.h.
bool llvm::Instruction::isCast () const inline
Definition at line 89 of file Instruction.h.
References getOpcode(), getOpcodeName(), and isCast().
Referenced by llvm::CastInst::classof(), llvm::ConstantCreator< ConstantExpr, Type, ExprMapKeyType >::create(), foldConstantCastPair(), llvm::InstCombiner::FoldSelectOpOp(), llvm::ConstantExpr::getCast(), INITIALIZE_PASS(), isCast(), llvm::ConstantExpr::isCast(), isZero(), WriteConstants(), and WriteInstruction().
static bool llvm::Instruction::isCast (unsigned OpCode) inline static
Determine if the OpCode is one of the CastInst instructions.
Definition at line 118 of file Instruction.h.
bool llvm::Instruction::isCommutative () const inline
isCommutative - Return true if the instruction is commutative:
Commutative operators satisfy: (x op y) === (y op x)
In LLVM, these are the associative operators, plus SetEQ and SetNE, when applied to any type.
Definition at line 269 of file Instruction.h.
References getOpcode(), and isCommutative().
Referenced by areAllUsesIn(), ClearSubclassDataAfterReassociation(), llvm::ConstantFoldBinaryInstruction(), ExpandBinOp(), FactorizeBinOp(), llvm::InstCombiner::FoldSelectOpOp(), getCommonReturnValue(), llvm::CmpInst::getSwappedPredicate(), isCommutative(), llvm::DenseMapInfo< Expression >::isEqual(), isSimpleLoadStore(), LinearizeExprTree(), RightDistributesOverLeft(), SimplifyAssociativeBinOp(), llvm::BinaryOperator::swapOperands(), and ThreadBinOpOverSelect().
bool Instruction::isCommutative (unsigned op) static
isCommutative - Return true if the instruction is commutative:
Commutative operators satisfy: (x op y) === (y op x)
In LLVM, these are the associative operators, plus SetEQ and SetNE, when applied to any type.
Definition at line 503 of file Instruction.cpp.
References llvm::APIntOps::And(), llvm::APIntOps::Or(), and llvm::APIntOps::Xor().
bool llvm::Instruction::isIdempotent () const inline
isIdempotent - Return true if the instruction is idempotent:
Idempotent operators satisfy: x op x === x
In LLVM, the And and Or operators are idempotent.
Definition at line 278 of file Instruction.h.
References getOpcode(), and isIdempotent().
Referenced by IncorporateWeight(), and isIdempotent().
bool Instruction::isIdempotent (unsigned Opcode) static
isIdempotent - Return true if the instruction is idempotent:
Idempotent operators satisfy: x op x === x
In LLVM, the And and Or operators are idempotent.
Definition at line 524 of file Instruction.cpp.
References llvm::APIntOps::And(), and llvm::APIntOps::Or().
bool Instruction::isIdenticalTo (const Instruction * I) const
isIdenticalTo - Return true if the specified instruction is exactly identical to the current one. This means that all operands match and any extra information (e.g. load is volatile) agree.
Definition at line 264 of file Instruction.cpp.
References isIdenticalToWhenDefined(), and llvm::Value::SubclassOptionalData.
Referenced by checkCSEInPredecessor(), createMinMaxOp(), FoldOperationIntoSelectOperand(), llvm::DenseMapInfo< SimpleValue >::getTombstoneKey(), llvm::DenseMapInfo< CallValue >::getTombstoneKey(), and mayHaveSideEffects().
bool Instruction::isIdenticalToWhenDefined (const Instruction * I) const
isIdenticalToWhenDefined - This is like isIdenticalTo, except that it ignores the SubclassOptionalData flags, which specify conditions under which the instruction's result is undefined.
Definition at line 272 of file Instruction.cpp.
References llvm::Intrinsic::getAttributes(), llvm::PHINode::getIncomingBlock(), llvm::User::getNumOperands(), getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), i, and I.
Referenced by GetLocation(), HoistThenElseCodeToIf(), isIdenticalTo(), and mayHaveSideEffects().
bool llvm::Instruction::isLogicalShift () const inline
isLogicalShift - Return true if this is a logical shift left or a logical shift right.
Definition at line 108 of file Instruction.h.
References getOpcode().
Referenced by CollectBSwapParts(), and llvm::InstCombiner::FoldShiftByConstant().
bool llvm::Instruction::isNilpotent () const inline
isNilpotent - Return true if the instruction is nilpotent:
Nilpotent operators satisfy: x op x === Id,
where Id is the identity for the operator, i.e. a constant such that x op Id === x and Id op x === x for all x.
In LLVM, the Xor operator is nilpotent.
Definition at line 290 of file Instruction.h.
References getOpcode(), isNilpotent(), mayReadFromMemory(), and mayWriteToMemory().
Referenced by IncorporateWeight(), and isNilpotent().
bool Instruction::isNilpotent (unsigned Opcode) static
isNilpotent - Return true if the instruction is nilpotent:
Nilpotent operators satisfy: x op x === Id,
where Id is the identity for the operator, i.e. a constant such that x op Id === x and Id op x === x for all x.
In LLVM, the Xor operator is nilpotent.
Definition at line 537 of file Instruction.cpp.
References llvm::APIntOps::Xor().
bool Instruction::isSameOperationAs (const Instruction * I, unsigned flags = 0) const
Determine if one instruction is the same operation as another.
This function determines if the specified instruction executes the same operation as the current one. This means that the opcodes, type, operand types and any other factors affecting the operation must be the same. This is similar to isIdenticalTo except the operands themselves don't have to be identical.
Returns
true if the specified instruction is the same operation as the current one.
Definition at line 334 of file Instruction.cpp.
References CompareIgnoringAlignment, CompareUsingScalarTypes, llvm::Intrinsic::getAttributes(), llvm::User::getNumOperands(), getOpcode(), llvm::User::getOperand(), llvm::Type::getScalarType(), llvm::Value::getType(), i, and I.
Referenced by hasUsesOutsideLoop(), isSafeAndProfitableToSinkLoad(), isSimpleLoadStore(), SinkThenElseCodeToEnd(), and llvm::InstCombiner::visitStoreInst().
bool llvm::Instruction::isShift () inline
Definition at line 88 of file Instruction.h.
References getOpcode(), and isShift().
Referenced by llvm::InstCombiner::FoldShiftByConstant(), getFCmpValue(), isShift(), and llvm::InstCombiner::visitXor().
static bool llvm::Instruction::isShift (unsigned Opcode) inline static
Determine if the Opcode is one of the shift instructions.
Definition at line 102 of file Instruction.h.
bool llvm::Instruction::isTerminator () const inline
Definition at line 86 of file Instruction.h.
References getOpcode(), and isTerminator().
Referenced by llvm::TerminatorInst::classof(), llvm::createJumpThreadingPass(), isFormingBranchFromSelectProfitable(), isSimpleLoadStore(), isTerminator(), llvm::MemoryDependenceAnalysis::removeInstruction(), SimplifyBranchOnICmpChain(), and SimplifyCondBranchToTwoReturns().
static bool llvm::Instruction::isTerminator (unsigned OpCode) inline static
Definition at line 93 of file Instruction.h.
bool Instruction::isUsedOutsideOfBlock (const BasicBlock * BB) const
isUsedOutsideOfBlock - Return true if there are any uses of this instruction in blocks other than the specified block. Note that PHI nodes are considered to evaluate their operands in the corresponding predecessor block.
isUsedOutsideOfBlock - Return true if there are any uses of I outside of the specified block. Note that PHI nodes are considered to evaluate their operands in the corresponding predecessor block.
Definition at line 401 of file Instruction.cpp.
References BB, llvm::dyn_cast(), llvm::PHINode::getIncomingBlock(), llvm::Value::use_begin(), and llvm::Value::use_end().
bool llvm::Instruction::mayHaveSideEffects () const inline
mayHaveSideEffects - Return true if the instruction may have side effects.
Note that this does not consider malloc and alloca to have side effects because the newly allocated memory is completely invisible to instructions which don't used the returned value. For cases where this matters, isSafeToSpeculativelyExecute may be more appropriate.
Definition at line 324 of file Instruction.h.
References clone(), isIdenticalTo(), isIdenticalToWhenDefined(), mayReturn(), mayThrow(), and mayWriteToMemory().
Referenced by CanTRE(), ExposePointerBase(), InstructionWillNotHaveChain(), llvm::isInstructionTriviallyDead(), llvm::isInTailCallPosition(), isOnlyReachableViaThisEdge(), IsSafeComputationToRemove(), isSafePHIToSpeculate(), isSafeToSpeculateStore(), SinkThenElseCodeToEnd(), SpeculativelyExecuteBB(), and TryToSinkInstruction().
bool Instruction::mayReadFromMemory () const
mayReadFromMemory - Return true if this instruction may read memory.
Definition at line 421 of file Instruction.cpp.
References llvm::Call, getOpcode(), llvm::SPII::Load, and llvm::SPII::Store.
Referenced by llvm::createEarlyCSEPass(), llvm::createFunctionAttrsPass(), llvm::createMemDepPrinter(), llvm::DependenceAnalysis::depends(), GetLocation(), llvm::DependenceAnalysis::getSplitIteration(), hasConcreteDefImpl(), InstructionWillNotHaveChain(), llvm::isInTailCallPosition(), isNilpotent(), isOnlyReachableViaThisEdge(), isSimpleLoadStore(), llvm::Loop::makeLoopInvariant(), mayReadOrWriteMemory(), shouldSpeculateInstrs(), and TryToSinkInstruction().
bool llvm::Instruction::mayReadOrWriteMemory () const inline
mayReadOrWriteMemory - Return true if this instruction may read or write memory.
Definition at line 304 of file Instruction.h.
References mayReadFromMemory(), mayReturn(), mayThrow(), and mayWriteToMemory().
Referenced by llvm::AliasSetTracker::addUnknown(), llvm::AliasSet::aliasesUnknownInst(), llvm::AliasSetTracker::deleteValue(), llvm::AliasSetTracker::removeUnknown(), and SinkThenElseCodeToEnd().
bool Instruction::mayReturn () const
mayReturn - Return true if this is a function that may return. this is true for all normal instructions. The only exception is functions that are marked with the 'noreturn' attribute.
Definition at line 465 of file Instruction.cpp.
Referenced by mayHaveSideEffects(), and mayReadOrWriteMemory().
bool Instruction::mayThrow () const
mayThrow - Return true if this instruction may throw an exception.
Definition at line 459 of file Instruction.cpp.
Referenced by mayHaveSideEffects(), and mayReadOrWriteMemory().
bool Instruction::mayWriteToMemory () const
mayWriteToMemory - Return true if this instruction may modify memory.
Definition at line 441 of file Instruction.cpp.
References llvm::Call, getOpcode(), llvm::SPII::Load, and llvm::SPII::Store.
Referenced by CanTRE(), llvm::createEarlyCSEPass(), llvm::createFunctionAttrsPass(), llvm::createMemDepPrinter(), llvm::DependenceAnalysis::depends(), llvm::FindAvailableLoadedValue(), FindInitTrampolineFromBB(), GetLocation(), llvm::DependenceAnalysis::getSplitIteration(), isFoldedOrDeadInstruction(), isNilpotent(), isSafeToMove(), isSimpleLoadStore(), mayHaveSideEffects(), mayReadOrWriteMemory(), llvm::AliasSet::mergeSetIn(), and shouldSpeculateInstrs().
void Instruction::moveBefore (Instruction * MovePos)
moveBefore - Unlink this instruction from its current basic block and insert it into the basic block that MovePos lives in, right before MovePos.
Definition at line 91 of file Instruction.cpp.
References llvm::BasicBlock::getInstList(), getParent(), and llvm::iplist< NodeTy, Traits >::splice().
Referenced by llvm::createLICMPass(), genLoopLimit(), getParent(), llvm::SCEVExpander::hoistIVInc(), isAlwaysFoldable(), isCompatibleAggregate(), isSafeToMove(), LinearizeExprTree(), llvm::Loop::makeLoopInvariant(), MarkBlocksLiveIn(), NegateValue(), llvm::NVPTXAllocaHoisting::runOnFunction(), shouldSpeculateInstrs(), tryToMoveFreeBeforeNullTest(), TryToSinkInstruction(), llvm::InstCombiner::visitAllocaInst(), and llvm::InstCombiner::visitSelectInstWithICmp().
void Instruction::removeFromParent ()
removeFromParent - This method unlinks 'this' from the containing basic block, but does not delete it.
Definition at line 68 of file Instruction.cpp.
References llvm::BasicBlock::getInstList(), getParent(), and llvm::iplist< NodeTy, Traits >::remove().
Referenced by AddPHINodeEntriesForMappedBlock(), getParent(), isFormingBranchFromSelectProfitable(), IsNonLocalValue(), and SimplifyBranchOnICmpChain().
void llvm::Instruction::setDebugLoc (const DebugLoc & Loc) inline
setDebugLoc - Set the debug location information for this instruction.
Definition at line 175 of file Instruction.h.
Referenced by AddPHINodeEntriesForMappedBlock(), checkInterfaceFunction(), clone(), llvm::ConvertDebugDeclareToDebugValue(), ConvertShiftToMul(), createAndInstr(), llvm::createLICMPass(), llvm::createObjCARCContractPass(), createPrivateNonConstGlobalForString(), deleteIfDeadInstruction(), FirstNonDbg(), FitWeights(), getMemSetPatternValue(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), hasAddressTakenAndUsed(), llvm::SCEVExpander::hoistIVInc(), llvm::InlineFunction(), llvm::InstCombiner::InsertNewInstWith(), llvm::InsertPreheaderForLoop(), isLifetimeStart(), isOnlyReachableViaThisEdge(), isSafeAndProfitableToSinkLoad(), llvm::BitcodeReader::ParseTriple(), llvm::IRBuilderBase::SetInstDebugLocation(), shouldSpeculateInstrs(), AllocaSlices::SliceBuilder::SliceBuilder(), and llvm::InstCombiner::visitStoreInst().
void Instruction::setFastMathFlags (FastMathFlags FMF)
Convenience function for setting all the fast-math flags on this instruction, which must be an operator which supports these flags. See LangRef.html for the meaning of these flats.
Definition at line 137 of file Instruction.cpp.
Referenced by ClearSubclassDataAfterReassociation(), copyFastMathFlags(), llvm::IRBuilder< true, TargetFolder >::CreateUnreachable(), FunctionNumber(), getDebugLoc(), llvm::BitcodeReader::ParseTriple(), and llvm::InstCombiner::visitFDiv().
void Instruction::setHasAllowReciprocal (bool B)
Set or clear the allow-reciprocal flag on this instruction, which must be an operator which supports this flag. See LangRef.html for the meaning of this flag.
Definition at line 129 of file Instruction.cpp.
Referenced by getDebugLoc().
void Instruction::setHasNoInfs (bool B)
Set or clear the no-infs flag on this instruction, which must be an operator which supports this flag. See LangRef.html for the meaning of this flag.
Definition at line 113 of file Instruction.cpp.
Referenced by getDebugLoc().
void Instruction::setHasNoNaNs (bool B)
Set or clear the no-nans flag on this instruction, which must be an operator which supports this flag. See LangRef.html for the meaning of this flag.
Set or clear the NoNaNs flag on this instruction, which must be an operator which supports this flag. See LangRef.html for the meaning of this flag.
Definition at line 106 of file Instruction.cpp.
Referenced by getDebugLoc().
void Instruction::setHasNoSignedZeros (bool B)
Set or clear the no-signed-zeros flag on this instruction, which must be an operator which supports this flag. See LangRef.html for the meaning of this flag.
Definition at line 121 of file Instruction.cpp.
Referenced by getDebugLoc().
void Instruction::setHasUnsafeAlgebra (bool B)
Set or clear the unsafe-algebra flag on this instruction, which must be an operator which supports this flag. See LangRef.html for the meaning of this flag.
Definition at line 99 of file Instruction.cpp.
Referenced by getDebugLoc().
void llvm::Instruction::setInstructionSubclassData (unsigned short D) inline protected
Definition at line 436 of file Instruction.h.
Referenced by llvm::AllocaInst::classof(), llvm::LoadInst::classof(), llvm::StoreInst::classof(), llvm::FenceInst::classof(), llvm::AtomicCmpXchgInst::classof(), llvm::AtomicRMWInst::classof(), llvm::CallInst::classof(), llvm::InvokeInst::classof(), and llvm::CmpInst::setPredicate().
void Instruction::setMetadata (unsigned KindID, MDNode * Node)
setMetadata - Set the metadata of the specified kind to the specified node. This updates/replaces metadata if already present, or removes it if Node is null.
setMetadata - Set the metadata of of the specified kind to the specified node. This updates/replaces metadata if already present, or removes it if Node is null.
Definition at line 589 of file Metadata.cpp.
References llvm::array_pod_sort(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::Value::getContext(), llvm::DebugLoc::getFromDILocation(), i, I, llvm::LLVMContext::MD_dbg, llvm::LLVMContextImpl::MetadataStore, llvm::LLVMContext::pImpl, llvm::SmallVectorTemplateBase< T, isPodLike >::pop_back(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by AppendMDNodeToInstForPtr(), clone(), ComputePostOrders(), llvm::ConstantFoldTerminator(), llvm::createLICMPass(), llvm::IRBuilderBase::CreateMemCpy(), llvm::IRBuilderBase::CreateMemMove(), llvm::IRBuilderBase::CreateMemSet(), llvm::createObjCARCOptPass(), llvm::IRBuilder< true, TargetFolder >::CreateUnreachable(), EliminateDeadSwitchCases(), FitWeights(), llvm::FoldBranchToCommonDest(), getAllMetadataOtherThanDebugLoc(), isLifetimeStart(), MarkIndicesSafe(), llvm::BitcodeReader::ParseTriple(), reduceToSingleValueType(), llvm::RemapInstruction(), llvm::LLParser::Run(), llvm::Loop::setLoopID(), SimplifyCondBranchToCondBranch(), SimplifyTerminatorOnSelect(), speculatePHINodeLoads(), speculateSelectInstLoads(), llvm::SplitBlockAndInsertIfThen(), llvm::BranchInst::swapSuccessors(), tryToMakeAllocaBePromotable(), TryToSimplifyUncondBranchWithICmpInIt(), TurnSwitchRangeIntoICmp(), llvm::UpgradeInstWithTBAATag(), llvm::UpgradeIntrinsicCall(), ValuesOverlap(), and llvm::InstCombiner::visitStoreInst().
void Instruction::setMetadata (StringRef Kind, MDNode * Node)
Definition at line 577 of file Metadata.cpp.
References llvm::Value::getContext().
Instruction* llvm::Instruction::use_back () inline
use_back - Specialize the methods defined in Value, as we know that an instruction can only be used by other instructions.
Definition at line 49 of file Instruction.h.
References llvm::Value::use_begin().
Referenced by buildMultiplyTree(), ConvertToSInt(), DeadPHICycle(), llvm::DemoteRegToStack(), llvm::InstCombiner::DoOneIteration(), FindScalarElement(), getCommonReturnValue(), MarkBlocksLiveIn(), MarkIndicesSafe(), OptimizeGlobalAddressOfMalloc(), promoteSingleBlockAlloca(), ShouldBreakUpSubtract(), shouldMergeGEPs(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), llvm::FastISel::tryToFoldLoad(), tryToMakeAllocaBePromotable(), TryToSimplifyUncondBranchWithICmpInIt(), llvm::InstCombiner::visitInsertElementInst(), llvm::InstCombiner::visitPHINode(), llvm::InstCombiner::visitSExt(), and llvm::InstCombiner::visitZExt().
const Instruction* llvm::Instruction::use_back () const inline
Definition at line 50 of file Instruction.h.
References llvm::Value::use_begin().
Friends And Related Function Documentation
friend class SymbolTableListTraits< Instruction, BasicBlock > friend
Definition at line 429 of file Instruction.h.
The documentation for this class was generated from the following files:
Instruction.h
Instruction.cpp
Metadata.cpp