LLVM: llvm::yaml::ScalarNode Class Reference
LLVM API Documentation
llvm::yaml::ScalarNode Class Reference
A scalar node is an opaque datum that can be presented as a series of zero or more Unicode scalar values.
#include <YAMLParser.h>
Public Member Functions
ScalarNode (OwningPtr< Document > &D, StringRef Anchor, StringRef Tag, StringRef Val)
StringRef getRawValue () const
StringRef getValue (SmallVectorImpl< char > &Storage) const
Gets the value of this node as a StringRef.
Public Member Functions inherited from llvm::yaml::Node
Node (unsigned int Type, OwningPtr< Document > &, StringRef Anchor, StringRef Tag)
StringRef getAnchor () const
Get the value of the anchor attached to this node. If it does not have one, getAnchor().size() will be 0.
StringRef getRawTag () const
Get the tag as it was written in the document. This does not perform tag resolution.
std::string getVerbatimTag () const
Get the verbatium tag for a given Node. This performs tag resoluton and substitution.
SMRange getSourceRange () const
void setSourceRange (SMRange SR)
Token & peekNext ()
Token getNext ()
Node * parseBlockNode ()
BumpPtrAllocator & getAllocator ()
void setError (const Twine &Message, Token &Location) const
bool failed () const
virtual void skip ()
unsigned int getType () const
void * operator new (size_t Size, BumpPtrAllocator &Alloc, size_t Alignment=16) throw ()
void operator delete (void *Ptr, BumpPtrAllocator &Alloc, size_t) throw ()
Static Public Member Functions
static bool classof (const Node *N)
Additional Inherited Members
Public Types inherited from llvm::yaml::Node
enum NodeKind {
NK_Null, NK_Scalar, NK_KeyValue, NK_Mapping,
NK_Sequence, NK_Alias
}
Protected Member Functions inherited from llvm::yaml::Node
void operator delete (void *) throw ()
virtual ~Node ()
Protected Attributes inherited from llvm::yaml::Node
OwningPtr< Document > & Doc
SMRange SourceRange
Detailed Description
A scalar node is an opaque datum that can be presented as a series of zero or more Unicode scalar values.
Example: Adena
Definition at line 194 of file YAMLParser.h.
Constructor & Destructor Documentation
llvm::yaml::ScalarNode::ScalarNode (OwningPtr< Document > & D, StringRef Anchor, StringRef Tag, StringRef Val) inline
Definition at line 197 of file YAMLParser.h.
References llvm::StringRef::begin(), llvm::StringRef::end(), and llvm::SMLoc::getFromPointer().
Member Function Documentation
static bool llvm::yaml::ScalarNode::classof (const Node * N) inline static
Definition at line 217 of file YAMLParser.h.
References llvm::yaml::Node::getType().
Referenced by llvm::yaml::Input::classof().
StringRef llvm::yaml::ScalarNode::getRawValue () const inline
Definition at line 208 of file YAMLParser.h.
StringRef ScalarNode::getValue (SmallVectorImpl< char > & Storage) const
Gets the value of this node as a StringRef.
Parameters
Storage is used to store the content of the returned StringRef iff it requires any modification from how it appeared in the source. This happens with escaped characters and multi-line literals.
Definition at line 1683 of file YAMLParser.cpp.
References llvm::StringRef::begin(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::StringRef::empty(), encodeUTF8(), llvm::StringRef::end(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::StringRef::find(), llvm::StringRef::find_first_of(), llvm::StringRef::getAsInteger(), i, llvm::SmallVectorImpl< T >::insert(), llvm::StringRef::npos, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::yaml::Token::Range, llvm::SmallVectorImpl< T >::reserve(), llvm::yaml::Node::setError(), llvm::StringRef::size(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::StringRef::substr(), and T.
Referenced by llvm::yaml::Input::nextDocument().
The documentation for this class was generated from the following files:
YAMLParser.h
YAMLParser.cpp