LLVM: llvm::DWARFDebugArangeSet Class Reference
LLVM API Documentation
llvm::DWARFDebugArangeSet Class Reference
#include <DWARFDebugArangeSet.h>
Classes
struct Descriptor
struct Header
Public Member Functions
DWARFDebugArangeSet ()
void clear ()
bool extract (DataExtractor data, uint32_t *offset_ptr)
void dump (raw_ostream &OS) const
uint32_t getCompileUnitDIEOffset () const
uint32_t getNumDescriptors () const
const Descriptor * getDescriptor (uint32_t i) const
Detailed Description
Definition at line 20 of file DWARFDebugArangeSet.h.
Constructor & Destructor Documentation
llvm::DWARFDebugArangeSet::DWARFDebugArangeSet () inline
Definition at line 54 of file DWARFDebugArangeSet.h.
References clear(), dump(), and extract().
Member Function Documentation
void DWARFDebugArangeSet::clear ()
Definition at line 17 of file DWARFDebugArangeSet.cpp.
References llvm::Intrinsic::memset.
Referenced by DWARFDebugArangeSet(), and extract().
void DWARFDebugArangeSet::dump (raw_ostream & OS) const
Definition at line 90 of file DWARFDebugArangeSet.cpp.
References llvm::DWARFDebugArangeSet::Header::AddrSize, llvm::DWARFDebugArangeSet::Header::CuOffset, llvm::sys::path::end(), llvm::format(), llvm::DWARFDebugArangeSet::Header::Length, llvm::DWARFDebugArangeSet::Header::SegSize, and llvm::DWARFDebugArangeSet::Header::Version.
Referenced by llvm::DWARFContext::dump(), and DWARFDebugArangeSet().
bool DWARFDebugArangeSet::extract (DataExtractor data, uint32_t * offset_ptr)
Definition at line 24 of file DWARFDebugArangeSet.cpp.
References llvm::DWARFDebugArangeSet::Descriptor::Address, llvm::DWARFDebugArangeSet::Header::AddrSize, clear(), llvm::DWARFDebugArangeSet::Header::CuOffset, llvm::DataExtractor::getU16(), llvm::DataExtractor::getU32(), llvm::DataExtractor::getU8(), llvm::DataExtractor::getUnsigned(), llvm::DataExtractor::isValidOffset(), llvm::DataExtractor::isValidOffsetForDataOfSize(), llvm::DWARFDebugArangeSet::Header::Length, llvm::DWARFDebugArangeSet::Descriptor::Length, llvm::DWARFDebugArangeSet::Header::SegSize, and llvm::DWARFDebugArangeSet::Header::Version.
Referenced by DWARFDebugArangeSet().
uint32_t llvm::DWARFDebugArangeSet::getCompileUnitDIEOffset () const inline
Definition at line 59 of file DWARFDebugArangeSet.h.
References llvm::DWARFDebugArangeSet::Header::CuOffset.
const Descriptor* llvm::DWARFDebugArangeSet::getDescriptor (uint32_t i) const inline
Definition at line 61 of file DWARFDebugArangeSet.h.
uint32_t llvm::DWARFDebugArangeSet::getNumDescriptors () const inline
Definition at line 60 of file DWARFDebugArangeSet.h.
The documentation for this class was generated from the following files:
DWARFDebugArangeSet.h
DWARFDebugArangeSet.cpp