LLVM: llvm::ObjectImage Class Reference
LLVM API Documentation
llvm::ObjectImage Class Reference abstract
#include <ObjectImage.h>
Public Member Functions
ObjectImage (ObjectBuffer *Input)
virtual ~ObjectImage ()
virtual object::symbol_iterator begin_symbols () const =0
virtual object::symbol_iterator end_symbols () const =0
virtual object::section_iterator begin_sections () const =0
virtual object::section_iterator end_sections () const =0
virtual unsigned getArch () const =0
virtual void updateSectionAddress (const object::SectionRef &Sec, uint64_t Addr)=0
virtual void updateSymbolAddress (const object::SymbolRef &Sym, uint64_t Addr)=0
virtual StringRef getData () const =0
virtual object::ObjectFile * getObjectFile () const =0
virtual void registerWithDebugger ()=0
virtual void deregisterWithDebugger ()=0
Protected Attributes
OwningPtr< ObjectBuffer > Buffer
Detailed Description
ObjectImage - A container class that represents an ObjectFile that has been or is in the process of being loaded into memory for execution.
Definition at line 25 of file ObjectImage.h.
Constructor & Destructor Documentation
llvm::ObjectImage::ObjectImage (ObjectBuffer * Input) inline
Definition at line 34 of file ObjectImage.h.
virtual llvm::ObjectImage::~ObjectImage () inline virtual
Definition at line 35 of file ObjectImage.h.
References begin_sections(), begin_symbols(), deregisterWithDebugger(), end_sections(), end_symbols(), getArch(), getData(), getObjectFile(), registerWithDebugger(), updateSectionAddress(), and updateSymbolAddress().
Member Function Documentation
virtual object::section_iterator llvm::ObjectImage::begin_sections () const pure virtual
Implemented in llvm::ObjectImageCommon.
Referenced by llvm::RuntimeDyldImpl::loadObject(), ~ObjectImage(), and llvm::RuntimeDyldELF::~RuntimeDyldELF().
virtual object::symbol_iterator llvm::ObjectImage::begin_symbols () const pure virtual
Implemented in llvm::ObjectImageCommon.
Referenced by llvm::RuntimeDyldImpl::loadObject(), and ~ObjectImage().
virtual void llvm::ObjectImage::deregisterWithDebugger () pure virtual
Implemented in llvm::ObjectImageCommon.
Referenced by ~ObjectImage().
virtual object::section_iterator llvm::ObjectImage::end_sections () const pure virtual
Implemented in llvm::ObjectImageCommon.
Referenced by llvm::RuntimeDyldImpl::loadObject(), llvm::RuntimeDyldELF::processRelocationRef(), ~ObjectImage(), and llvm::RuntimeDyldELF::~RuntimeDyldELF().
virtual object::symbol_iterator llvm::ObjectImage::end_symbols () const pure virtual
Implemented in llvm::ObjectImageCommon.
Referenced by llvm::RuntimeDyldImpl::loadObject(), llvm::RuntimeDyldELF::processRelocationRef(), and ~ObjectImage().
virtual unsigned llvm::ObjectImage::getArch () const pure virtual
Implemented in llvm::ObjectImageCommon.
Referenced by llvm::RuntimeDyldImpl::loadObject(), and ~ObjectImage().
virtual StringRef llvm::ObjectImage::getData () const pure virtual
Implemented in llvm::ObjectImageCommon.
Referenced by ~ObjectImage().
virtual object::ObjectFile* llvm::ObjectImage::getObjectFile () const pure virtual
Implemented in llvm::ObjectImageCommon.
Referenced by llvm::RuntimeDyldImpl::emitSection(), llvm::RuntimeDyldImpl::loadObject(), llvm::RuntimeDyldMachO::processRelocationRef(), and ~ObjectImage().
virtual void llvm::ObjectImage::registerWithDebugger () pure virtual
Implemented in llvm::ObjectImageCommon.
Referenced by ~ObjectImage().
virtual void llvm::ObjectImage::updateSectionAddress (const object::SectionRef & Sec, uint64_t Addr) pure virtual
Implemented in llvm::ObjectImageCommon.
Referenced by llvm::RuntimeDyldImpl::emitSection(), and ~ObjectImage().
virtual void llvm::ObjectImage::updateSymbolAddress (const object::SymbolRef & Sym, uint64_t Addr) pure virtual
Implemented in llvm::ObjectImageCommon.
Referenced by llvm::RuntimeDyldImpl::emitCommonSymbols(), and ~ObjectImage().
Member Data Documentation
OwningPtr<ObjectBuffer> llvm::ObjectImage::Buffer protected
Definition at line 31 of file ObjectImage.h.
Referenced by llvm::ObjectImageCommon::ObjectImageCommon().
The documentation for this class was generated from the following files:
ObjectImage.h
RuntimeDyld.cpp