LLVM: llvm::BranchFolder Class Reference
LLVM API Documentation
llvm::BranchFolder Class Reference
#include <BranchFolding.h>
Public Member Functions
BranchFolder (bool defaultEnableTailMerge, bool CommonHoist)
bool OptimizeFunction (MachineFunction &MF, const TargetInstrInfo *tii, const TargetRegisterInfo *tri, MachineModuleInfo *mmi)
Detailed Description
Definition at line 24 of file BranchFolding.h.
Constructor & Destructor Documentation
BranchFolder::BranchFolder (bool defaultEnableTailMerge, bool CommonHoist) explicit
Definition at line 94 of file BranchFolding.cpp.
References llvm::MachineBasicBlock::begin(), llvm::cl::BOU_FALSE, llvm::cl::BOU_TRUE, llvm::cl::BOU_UNSET, llvm::SmallSet< T, N, C >::count(), llvm::dbgs(), DEBUG, llvm::SmallSet< T, N, C >::empty(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::erase(), llvm::MachineBasicBlock::erase(), FlagEnableTailMerge, llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), i, I, llvm::SmallSet< T, N, C >::insert(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUse(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::MachineBasicBlock::pred_empty(), llvm::MachineBasicBlock::removeSuccessor(), llvm::MachineBasicBlock::succ_empty(), llvm::MachineBasicBlock::succ_end(), and TII.
Member Function Documentation
bool BranchFolder::OptimizeFunction (MachineFunction & MF, const TargetInstrInfo * tii, const TargetRegisterInfo * tri, MachineModuleInfo * mmi)
OptimizeFunction - Perhaps branch folding, tail merging and other CFG optimizations on the given function.
Definition at line 174 of file BranchFolding.cpp.
References llvm::HexagonInstrInfo::AnalyzeBranch(), BB, llvm::MachineFunction::begin(), llvm::MachineBasicBlock::CorrectExtraCFGEdges(), llvm::SmallVectorBase::empty(), llvm::MachineFunction::end(), llvm::MachineOperand::getIndex(), llvm::MachineFunction::getJumpTableInfo(), llvm::MachineJumpTableInfo::getJumpTables(), llvm::MachineFunction::getRegInfo(), i, I, llvm::MachineRegisterInfo::invalidateLiveness(), llvm::MachineOperand::isJTI(), MRI, llvm::MachineJumpTableInfo::RemoveJumpTable(), TII, and llvm::MachineRegisterInfo::tracksLiveness().
Referenced by INITIALIZE_PASS().
The documentation for this class was generated from the following files:
BranchFolding.h
BranchFolding.cpp