LLVM: llvm::MipsTargetLowering Class Reference
LLVM API Documentation
llvm::MipsTargetLowering Class Reference abstract
#include <MipsISelLowering.h>
Classes
struct ByValArgInfo
ByValArgInfo - Byval argument information.
struct LTStr
class MipsCC
Public Member Functions
MipsTargetLowering (MipsTargetMachine &TM)
virtual MVT getScalarShiftAmountTy (EVT LHSTy) const
virtual void LowerOperationWrapper (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG) const
virtual SDValue LowerOperation (SDValue Op, SelectionDAG &DAG) const
LowerOperation - Provide custom lowering hooks for some operations.
virtual void ReplaceNodeResults (SDNode *N, SmallVectorImpl< SDValue > &Results, SelectionDAG &DAG) const
virtual const char * getTargetNodeName (unsigned Opcode) const
getTargetNodeName - This method returns the name of a target specific
EVT getSetCCResultType (LLVMContext &Context, EVT VT) const
getSetCCResultType - get the ISD::SETCC result ValueType
virtual SDValue PerformDAGCombine (SDNode *N, DAGCombinerInfo &DCI) const
virtual MachineBasicBlock * EmitInstrWithCustomInserter (MachineInstr *MI, MachineBasicBlock *MBB) const
Public Member Functions inherited from llvm::TargetLowering
TargetLowering (const TargetMachine &TM, const TargetLoweringObjectFile *TLOF)
NOTE: The constructor takes ownership of TLOF.
virtual bool getPreIndexedAddressParts (SDNode *, SDValue &, SDValue &, ISD::MemIndexedMode &, SelectionDAG &) const
virtual bool getPostIndexedAddressParts (SDNode *, SDNode *, SDValue &, SDValue &, ISD::MemIndexedMode &, SelectionDAG &) const
virtual const MCExpr * LowerCustomJumpTableEntry (const MachineJumpTableInfo *, const MachineBasicBlock *, unsigned, MCContext &) const
virtual SDValue getPICJumpTableRelocBase (SDValue Table, SelectionDAG &DAG) const
Returns relocation base for the given PIC jumptable.
virtual const MCExpr * getPICJumpTableRelocBaseExpr (const MachineFunction *MF, unsigned JTI, MCContext &Ctx) const
bool isInTailCallPosition (SelectionDAG &DAG, SDNode *Node, SDValue &Chain) const
void softenSetCCOperands (SelectionDAG &DAG, EVT VT, SDValue &NewLHS, SDValue &NewRHS, ISD::CondCode &CCCode, SDLoc DL) const
std::pair< SDValue, SDValue > makeLibCall (SelectionDAG &DAG, RTLIB::Libcall LC, EVT RetVT, const SDValue *Ops, unsigned NumOps, bool isSigned, SDLoc dl, bool doesNotReturn=false, bool isReturnValueUsed=true) const
Returns a pair of (return value, chain).
bool SimplifyDemandedBits (SDValue Op, const APInt &DemandedMask, APInt &KnownZero, APInt &KnownOne, TargetLoweringOpt &TLO, unsigned Depth=0) const
virtual void computeMaskedBitsForTargetNode (const SDValue Op, APInt &KnownZero, APInt &KnownOne, const SelectionDAG &DAG, unsigned Depth=0) const
virtual unsigned ComputeNumSignBitsForTargetNode (SDValue Op, unsigned Depth=0) const
SDValue SimplifySetCC (EVT VT, SDValue N0, SDValue N1, ISD::CondCode Cond, bool foldBooleans, DAGCombinerInfo &DCI, SDLoc dl) const
virtual bool isGAPlusOffset (SDNode *N, const GlobalValue *&GA, int64_t &Offset) const
virtual bool isTypeDesirableForOp (unsigned, EVT VT) const
virtual bool isDesirableToTransformToIntegerOp (unsigned, EVT) const
virtual bool IsDesirableToPromoteOp (SDValue, EVT &) const
std::pair< SDValue, SDValue > LowerCallTo (CallLoweringInfo &CLI) const
virtual void HandleByVal (CCState *, unsigned &, unsigned) const
Target-specific cleanup for formal ByVal parameters.
virtual bool isUsedByReturnOnly (SDNode *, SDValue &) const
virtual bool mayBeEmittedAsTailCall (CallInst *) const
virtual MVT getTypeForExtArgOrReturn (MVT VT, ISD::NodeType) const
virtual const uint16_t * getScratchRegisters (CallingConv::ID CC) const
virtual FastISel * createFastISel (FunctionLoweringInfo &, const TargetLibraryInfo *) const
virtual bool ExpandInlineAsm (CallInst *) const
virtual AsmOperandInfoVector ParseConstraints (ImmutableCallSite CS) const
virtual ConstraintWeight getMultipleConstraintMatchWeight (AsmOperandInfo &info, int maIndex) const
virtual void ComputeConstraintToUse (AsmOperandInfo &OpInfo, SDValue Op, SelectionDAG *DAG=0) const
virtual const char * LowerXConstraint (EVT ConstraintVT) const
SDValue BuildExactSDIV (SDValue Op1, SDValue Op2, SDLoc dl, SelectionDAG &DAG) const
Given an exact SDIV by a constant, create a multiplication with the multiplicative inverse of the constant.
SDValue BuildSDIV (SDNode *N, SelectionDAG &DAG, bool IsAfterLegalization, std::vector< SDNode * > *Created) const
Given an ISD::SDIV node expressing a divide by constant, return a DAG expression to select that will generate the same value by multiplying by a magic number. See: http://the.wall.riscom.net/books/proc/ppc/cwg/code2.html
SDValue BuildUDIV (SDNode *N, SelectionDAG &DAG, bool IsAfterLegalization, std::vector< SDNode * > *Created) const
Given an ISD::UDIV node expressing a divide by constant, return a DAG expression to select that will generate the same value by multiplying by a magic number. See: http://the.wall.riscom.net/books/proc/ppc/cwg/code2.html
virtual void AdjustInstrPostInstrSelection (MachineInstr *MI, SDNode *Node) const
Public Member Functions inherited from llvm::TargetLoweringBase
TargetLoweringBase (const TargetMachine &TM, const TargetLoweringObjectFile *TLOF)
NOTE: The constructor takes ownership of TLOF.
virtual ~TargetLoweringBase ()
const TargetMachine & getTargetMachine () const
const DataLayout * getDataLayout () const
const TargetLoweringObjectFile & getObjFileLowering () const
bool isBigEndian () const
bool isLittleEndian () const
virtual MVT getPointerTy (uint32_t=0) const
unsigned getPointerSizeInBits (uint32_t AS=0) const
unsigned getPointerTypeSizeInBits (Type *Ty) const
EVT getShiftAmountTy (EVT LHSTy) const
virtual MVT getVectorIdxTy () const
bool isSelectExpensive () const
Return true if the select operation is expensive for this target.
virtual bool isSelectSupported (SelectSupportKind) const
virtual bool shouldSplitVectorElementType (EVT) const
bool isIntDivCheap () const
bool isSlowDivBypassed () const
Returns true if target has indicated at least one type should be bypassed.
const DenseMap< unsigned int, unsigned int > & getBypassSlowDivWidths () const
bool isPow2DivCheap () const
Return true if pow2 div is cheaper than a chain of srl/add/sra.
bool isJumpExpensive () const
bool isPredictableSelectExpensive () const
virtual bool isLoadBitCastBeneficial (EVT, EVT) const
virtual MVT::SimpleValueType getCmpLibcallReturnType () const
BooleanContent getBooleanContents (bool isVec) const
Sched::Preference getSchedulingPreference () const
Return target scheduling preference.
virtual Sched::Preference getSchedulingPreference (SDNode *) const
virtual const TargetRegisterClass * getRegClassFor (MVT VT) const
virtual const TargetRegisterClass * getRepRegClassFor (MVT VT) const
virtual uint8_t getRepRegClassCostFor (MVT VT) const
bool isTypeLegal (EVT VT) const
const ValueTypeActionImpl & getValueTypeActions () const
LegalizeTypeAction getTypeAction (LLVMContext &Context, EVT VT) const
LegalizeTypeAction getTypeAction (MVT VT) const
EVT getTypeToTransformTo (LLVMContext &Context, EVT VT) const
EVT getTypeToExpandTo (LLVMContext &Context, EVT VT) const
unsigned getVectorTypeBreakdown (LLVMContext &Context, EVT VT, EVT &IntermediateVT, unsigned &NumIntermediates, MVT &RegisterVT) const
virtual bool getTgtMemIntrinsic (IntrinsicInfo &, const CallInst &, unsigned) const
virtual bool isShuffleMaskLegal (const SmallVectorImpl< int > &, EVT) const
virtual bool canOpTrap (unsigned Op, EVT VT) const
virtual bool isVectorClearMaskLegal (const SmallVectorImpl< int > &, EVT) const
LegalizeAction getOperationAction (unsigned Op, EVT VT) const
bool isOperationLegalOrCustom (unsigned Op, EVT VT) const
bool isOperationLegalOrPromote (unsigned Op, EVT VT) const
bool isOperationExpand (unsigned Op, EVT VT) const
bool isOperationLegal (unsigned Op, EVT VT) const
Return true if the specified operation is legal on this target.
LegalizeAction getLoadExtAction (unsigned ExtType, MVT VT) const
bool isLoadExtLegal (unsigned ExtType, EVT VT) const
Return true if the specified load with extension is legal on this target.
LegalizeAction getTruncStoreAction (MVT ValVT, MVT MemVT) const
bool isTruncStoreLegal (EVT ValVT, EVT MemVT) const
LegalizeAction getIndexedLoadAction (unsigned IdxMode, MVT VT) const
bool isIndexedLoadLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getIndexedStoreAction (unsigned IdxMode, MVT VT) const
bool isIndexedStoreLegal (unsigned IdxMode, EVT VT) const
Return true if the specified indexed load is legal on this target.
LegalizeAction getCondCodeAction (ISD::CondCode CC, MVT VT) const
bool isCondCodeLegal (ISD::CondCode CC, MVT VT) const
Return true if the specified condition code is legal on this target.
MVT getTypeToPromoteTo (unsigned Op, MVT VT) const
EVT getValueType (Type *Ty, bool AllowUnknown=false) const
MVT getSimpleValueType (Type *Ty, bool AllowUnknown=false) const
Return the MVT corresponding to this LLVM type. See getValueType.
virtual unsigned getByValTypeAlignment (Type *Ty) const
MVT getRegisterType (MVT VT) const
Return the type of registers that this ValueType will eventually require.
MVT getRegisterType (LLVMContext &Context, EVT VT) const
Return the type of registers that this ValueType will eventually require.
unsigned getNumRegisters (LLVMContext &Context, EVT VT) const
virtual bool ShouldShrinkFPConstant (EVT) const
bool hasTargetDAGCombine (ISD::NodeType NT) const
unsigned getMaxStoresPerMemset (bool OptSize) const
Get maximum # of store operations permitted for llvm.memset.
unsigned getMaxStoresPerMemcpy (bool OptSize) const
Get maximum # of store operations permitted for llvm.memcpy.
unsigned getMaxStoresPerMemmove (bool OptSize) const
Get maximum # of store operations permitted for llvm.memmove.
virtual bool allowsUnalignedMemoryAccesses (EVT, bool *=0) const
Determine if the target supports unaligned memory accesses.
virtual bool isSafeMemOpType (MVT) const
bool usesUnderscoreSetJmp () const
Determine if we should use _setjmp or setjmp to implement llvm.setjmp.
bool usesUnderscoreLongJmp () const
Determine if we should use _longjmp or longjmp to implement llvm.longjmp.
bool supportJumpTables () const
Return whether the target can generate code for jump tables.
int getMinimumJumpTableEntries () const
unsigned getStackPointerRegisterToSaveRestore () const
unsigned getExceptionPointerRegister () const
unsigned getExceptionSelectorRegister () const
unsigned getJumpBufSize () const
unsigned getJumpBufAlignment () const
unsigned getMinStackArgumentAlignment () const
Return the minimum stack alignment of an argument.
unsigned getMinFunctionAlignment () const
Return the minimum function alignment.
unsigned getPrefFunctionAlignment () const
Return the preferred function alignment.
unsigned getPrefLoopAlignment () const
Return the preferred loop alignment.
bool getInsertFencesForAtomic () const
virtual bool getStackCookieLocation (unsigned &, unsigned &) const
virtual unsigned getMaximalGlobalOffset () const
virtual bool isNoopAddrSpaceCast (unsigned SrcAS, unsigned DestAS) const
Returns true if a cast between SrcAS and DestAS is a noop.
virtual void resetOperationActions ()
Reset the operation actions based on target options.
virtual bool GetAddrModeArguments (IntrinsicInst *, SmallVectorImpl< Value * > &, Type *&) const
virtual int getScalingFactorCost (const AddrMode &AM, Type *Ty) const
Return the cost of the scaling factor used in the addressing mode represented by AM for this target, for a load/store of the specified type.
virtual bool isLegalICmpImmediate (int64_t) const
virtual bool isLegalAddImmediate (int64_t) const
virtual bool isTruncateFree (Type *, Type *) const
virtual bool allowTruncateForTailCall (Type *, Type *) const
virtual bool isTruncateFree (EVT, EVT) const
virtual bool isZExtFree (Type *, Type *) const
virtual bool isZExtFree (EVT, EVT) const
virtual bool hasPairedLoad (Type *, unsigned &) const
virtual bool hasPairedLoad (EVT, unsigned &) const
virtual bool isZExtFree (SDValue Val, EVT VT2) const
virtual bool isFNegFree (EVT VT) const
virtual bool isFAbsFree (EVT VT) const
virtual bool isFMAFasterThanFMulAndFAdd (EVT) const
virtual bool isNarrowingProfitable (EVT, EVT) const
void setLibcallName (RTLIB::Libcall Call, const char *Name)
Rename the default libcall routine name for the specified libcall.
const char * getLibcallName (RTLIB::Libcall Call) const
Get the libcall routine name for the specified libcall.
void setCmpLibcallCC (RTLIB::Libcall Call, ISD::CondCode CC)
ISD::CondCode getCmpLibcallCC (RTLIB::Libcall Call) const
void setLibcallCallingConv (RTLIB::Libcall Call, CallingConv::ID CC)
Set the CallingConv that should be used for the specified libcall.
CallingConv::ID getLibcallCallingConv (RTLIB::Libcall Call) const
Get the CallingConv that should be used for the specified libcall.
LegalizeKind getTypeConversion (LLVMContext &Context, EVT VT) const
int InstructionOpcodeToISD (unsigned Opcode) const
Get the ISD node that corresponds to the Instruction class opcode.
std::pair< unsigned, MVT > getTypeLegalizationCost (Type *Ty) const
Estimate the cost of type-legalization and the legalized type.
Static Public Member Functions
static const MipsTargetLowering * create (MipsTargetMachine &TM)
Static Public Member Functions inherited from llvm::TargetLoweringBase
static ISD::NodeType getExtendForContent (BooleanContent Content)
Protected Member Functions
SDValue getGlobalReg (SelectionDAG &DAG, EVT Ty) const
template<class NodeTy >
SDValue getAddrLocal (NodeTy *N, EVT Ty, SelectionDAG &DAG, bool HasMips64) const
template<class NodeTy >
SDValue getAddrGlobal (NodeTy *N, EVT Ty, SelectionDAG &DAG, unsigned Flag, SDValue Chain, const MachinePointerInfo &PtrInfo) const
template<class NodeTy >
SDValue getAddrGlobalLargeGOT (NodeTy *N, EVT Ty, SelectionDAG &DAG, unsigned HiFlag, unsigned LoFlag, SDValue Chain, const MachinePointerInfo &PtrInfo) const
template<class NodeTy >
SDValue getAddrNonPIC (NodeTy *N, EVT Ty, SelectionDAG &DAG) const
virtual void getOpndList (SmallVectorImpl< SDValue > &Ops, std::deque< std::pair< unsigned, SDValue > > &RegsToPass, bool IsPICCall, bool GlobalOrExternal, bool InternalLinkage, CallLoweringInfo &CLI, SDValue Callee, SDValue Chain) const
SDValue lowerLOAD (SDValue Op, SelectionDAG &DAG) const
SDValue lowerSTORE (SDValue Op, SelectionDAG &DAG) const
Protected Member Functions inherited from llvm::TargetLoweringBase
void initActions ()
Initialize all of the actions to default values.
void setBooleanContents (BooleanContent Ty)
void setBooleanVectorContents (BooleanContent Ty)
void setSchedulingPreference (Sched::Preference Pref)
Specify the target scheduling preference.
void setUseUnderscoreSetJmp (bool Val)
void setUseUnderscoreLongJmp (bool Val)
void setSupportJumpTables (bool Val)
Indicate whether the target can generate code for jump tables.
void setMinimumJumpTableEntries (int Val)
void setStackPointerRegisterToSaveRestore (unsigned R)
void setExceptionPointerRegister (unsigned R)
void setExceptionSelectorRegister (unsigned R)
void setSelectIsExpensive (bool isExpensive=true)
void setJumpIsExpensive (bool isExpensive=true)
void setIntDivIsCheap (bool isCheap=true)
void addBypassSlowDiv (unsigned int SlowBitWidth, unsigned int FastBitWidth)
Tells the code generator which bitwidths to bypass.
void setPow2DivIsCheap (bool isCheap=true)
void addRegisterClass (MVT VT, const TargetRegisterClass *RC)
void clearRegisterClasses ()
Remove all register classes.
void clearOperationActions ()
Remove all operation actions.
virtual std::pair< const TargetRegisterClass *, uint8_t > findRepresentativeClass (MVT VT) const
void computeRegisterProperties ()
void setOperationAction (unsigned Op, MVT VT, LegalizeAction Action)
void setLoadExtAction (unsigned ExtType, MVT VT, LegalizeAction Action)
void setTruncStoreAction (MVT ValVT, MVT MemVT, LegalizeAction Action)
void setIndexedLoadAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
void setIndexedStoreAction (unsigned IdxMode, MVT VT, LegalizeAction Action)
void setCondCodeAction (ISD::CondCode CC, MVT VT, LegalizeAction Action)
void AddPromotedToType (unsigned Opc, MVT OrigVT, MVT DestVT)
void setTargetDAGCombine (ISD::NodeType NT)
void setJumpBufSize (unsigned Size)
Set the target's required jmp_buf buffer size (in bytes); default is 200.
void setJumpBufAlignment (unsigned Align)
void setMinFunctionAlignment (unsigned Align)
Set the target's minimum function alignment (in log2(bytes))
void setPrefFunctionAlignment (unsigned Align)
void setPrefLoopAlignment (unsigned Align)
void setMinStackArgumentAlignment (unsigned Align)
Set the minimum stack alignment of an argument (in log2(bytes)).
void setInsertFencesForAtomic (bool fence)
bool isLegalRC (const TargetRegisterClass *RC) const
Protected Attributes
const MipsSubtarget * Subtarget
bool HasMips64
bool IsN64
bool IsO32
Protected Attributes inherited from llvm::TargetLoweringBase
unsigned MaxStoresPerMemset
Specify maximum number of store instructions per memset call.
unsigned MaxStoresPerMemsetOptSize
unsigned MaxStoresPerMemcpy
Specify maximum bytes of store instructions per memcpy call.
unsigned MaxStoresPerMemcpyOptSize
unsigned MaxStoresPerMemmove
Specify maximum bytes of store instructions per memmove call.
unsigned MaxStoresPerMemmoveOptSize
bool PredictableSelectIsExpensive
Additional Inherited Members
Public Types inherited from llvm::TargetLowering
enum ConstraintType {
C_Register, C_RegisterClass, C_Memory, C_Other,
C_Unknown
}
enum ConstraintWeight {
CW_Invalid = -1, CW_Okay = 0, CW_Good = 1, CW_Better = 2,
CW_Best = 3, CW_SpecificReg = CW_Okay, CW_Register = CW_Good, CW_Memory = CW_Better,
CW_Constant = CW_Best, CW_Default = CW_Okay
}
typedef std::vector< ArgListEntry > ArgListTy
typedef std::vector< AsmOperandInfo > AsmOperandInfoVector
Public Types inherited from llvm::TargetLoweringBase
enum LegalizeAction { Legal, Promote, Expand, Custom }
enum LegalizeTypeAction {
TypeLegal, TypePromoteInteger, TypeExpandInteger, TypeSoftenFloat,
TypeExpandFloat, TypeScalarizeVector, TypeSplitVector, TypeWidenVector
}
enum BooleanContent { UndefinedBooleanContent, ZeroOrOneBooleanContent, ZeroOrNegativeOneBooleanContent }
Enum that describes how the target represents true/false values.
enum SelectSupportKind { ScalarValSelect, ScalarCondVectorVal, VectorMaskSelect }
Enum that describes what type of support for selects the target has.
typedef std::pair< LegalizeTypeAction, EVT > LegalizeKind
Detailed Description
Definition at line 211 of file MipsISelLowering.h.
Constructor & Destructor Documentation
MipsTargetLowering::MipsTargetLowering (MipsTargetMachine & TM) explicit
Definition at line 205 of file MipsISelLowering.cpp.
References llvm::ISD::ADD, llvm::TargetLoweringBase::AddPromotedToType(), llvm::ISD::AND, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_STORE, llvm::ISD::BlockAddress, llvm::ISD::BR_CC, llvm::ISD::BR_JT, llvm::ISD::BRCOND, llvm::ISD::BSWAP, llvm::ISD::ConstantPool, llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::TargetLoweringBase::Custom, llvm::ISD::DYNAMIC_STACKALLOC, llvm::ISD::EH_RETURN, llvm::TargetLoweringBase::Expand, llvm::ISD::EXTLOAD, llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FABS, llvm::ISD::FCOPYSIGN, llvm::ISD::FCOS, llvm::ISD::FEXP, llvm::ISD::FLOG, llvm::ISD::FLOG10, llvm::ISD::FLOG2, llvm::ISD::FMA, llvm::ISD::FNEG, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FPOW, llvm::ISD::FPOWI, llvm::ISD::FREM, llvm::ISD::FSIN, llvm::ISD::FSINCOS, llvm::ISD::GlobalAddress, llvm::ISD::GlobalTLSAddress, llvm::MipsSubtarget::hasBitCount(), llvm::MipsSubtarget::hasMips32r2(), HasMips64, llvm::MipsSubtarget::hasMips64r2(), llvm::MipsSubtarget::hasSEInReg(), llvm::MipsSubtarget::hasSwap(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, IsN64, llvm::ISD::JumpTable, llvm::TargetLoweringBase::Legal, llvm::ISD::LOAD, llvm::TargetLoweringBase::MaxStoresPerMemcpy, llvm::TargetOptions::NoNaNsFPMath, llvm::TargetMachine::Options, llvm::ISD::OR, llvm::MVT::Other, llvm::TargetLoweringBase::Promote, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SDIV, llvm::ISD::SDIVREM, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::TargetLoweringBase::setBooleanContents(), llvm::TargetLoweringBase::setBooleanVectorContents(), llvm::ISD::SETCC, llvm::TargetLoweringBase::setExceptionPointerRegister(), llvm::TargetLoweringBase::setExceptionSelectorRegister(), llvm::TargetLoweringBase::setInsertFencesForAtomic(), llvm::TargetLoweringBase::setLoadExtAction(), llvm::TargetLoweringBase::setMinFunctionAlignment(), llvm::TargetLoweringBase::setOperationAction(), llvm::TargetLoweringBase::setStackPointerRegisterToSaveRestore(), llvm::TargetLoweringBase::setTargetDAGCombine(), llvm::TargetLoweringBase::setTruncStoreAction(), llvm::ISD::SEXTLOAD, llvm::ISD::SHL_PARTS, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SRA_PARTS, llvm::ISD::SREM, llvm::ISD::SRL_PARTS, llvm::ISD::STACKRESTORE, llvm::ISD::STACKSAVE, llvm::ISD::STORE, Subtarget, llvm::ISD::TRAP, llvm::ISD::UDIV, llvm::ISD::UDIVREM, llvm::ISD::UINT_TO_FP, llvm::ISD::UREM, llvm::ISD::VAARG, llvm::ISD::VACOPY, llvm::ISD::VAEND, llvm::ISD::VASTART, llvm::TargetLoweringBase::ZeroOrNegativeOneBooleanContent, llvm::TargetLoweringBase::ZeroOrOneBooleanContent, and llvm::ISD::ZEXTLOAD.
Referenced by getTargetNodeName().
Member Function Documentation
const MipsTargetLowering * MipsTargetLowering::create (MipsTargetMachine & TM) static
Definition at line 397 of file MipsISelLowering.cpp.
References llvm::createMips16TargetLowering(), llvm::createMipsSETargetLowering(), llvm::MipsTargetMachine::getSubtargetImpl(), and llvm::MipsSubtarget::inMips16Mode().
Referenced by llvm::MipsTargetMachine::setHelperClassesMips16(), and llvm::MipsTargetMachine::setHelperClassesMipsSE().
MachineBasicBlock * MipsTargetLowering::EmitInstrWithCustomInserter (MachineInstr * MI, MachineBasicBlock * MBB) const virtual
This method should be implemented by targets that mark instructions with the 'usesCustomInserter' flag. These instructions are special in various ways, which require special support to insert. The specified MachineInstr is created but not inserted into any basic blocks, and this method is called to expand it into a sequence of instructions, potentially also creating new basic blocks and control flow.
Reimplemented from llvm::TargetLowering.
Reimplemented in llvm::MipsSETargetLowering, and llvm::Mips16TargetLowering.
Definition at line 787 of file MipsISelLowering.cpp.
References llvm::ISD::ADD, llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), AND, BB, llvm::MachineBasicBlock::begin(), llvm::Mips::BRANCH_F, llvm::Mips::BRANCH_T, llvm::ISD::BRIND, llvm::BuildMI(), llvm::CallingConv::C, CC, createCMovFP(), createFPCmp(), llvm::MachineFunction::CreateMachineBasicBlock(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), expandPseudoDIV(), llvm::MipsISD::FPBrcond, llvm::MipsISD::FPCmp, llvm::TLSModel::GeneralDynamic, llvm::MCInstrInfo::get(), getAddrGlobal(), getAddrGlobalLargeGOT(), getAddrLocal(), getAddrNonPIC(), llvm::MachineBasicBlock::getBasicBlock(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::TargetLoweringBase::getDataLayout(), llvm::MachineInstr::getDebugLoc(), llvm::SelectionDAG::getEntryNode(), llvm::MachineJumpTableInfo::getEntrySize(), llvm::SelectionDAG::getExternalSymbol(), llvm::SelectionDAG::getExtLoad(), llvm::SelectionDAG::getFrameIndex(), llvm::GlobalAddressSDNode::getGlobal(), getGlobalReg(), llvm::MachinePointerInfo::getGOT(), llvm::MachineFunction::getInfo(), llvm::TargetMachine::getInstrInfo(), llvm::MVT::getIntegerVT(), llvm::EVT::getIntegerVT(), llvm::Type::getIntNTy(), llvm::MachinePointerInfo::getJumpTable(), llvm::MachineFunction::getJumpTableInfo(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getObjFileLowering(), llvm::SDValue::getOpcode(), llvm::MachineInstr::getOpcode(), llvm::SDValue::getOperand(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::TargetLowering::getPICJumpTableRelocBase(), llvm::TargetLoweringBase::getPointerTy(), llvm::MachineOperand::getReg(), llvm::TargetLoweringBase::getRegClassFor(), llvm::MachineFunction::getRegInfo(), llvm::SelectionDAG::getRegister(), getSetCCResultType(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::TargetLoweringBase::getTargetMachine(), llvm::TargetMachine::getTLSModel(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::MipsFunctionInfo::getVarArgsFrameIndex(), llvm::SelectionDAG::getVTList(), llvm::MipsISD::GPRel, HasMips64, llvm::MipsISD::Hi, llvm::HexagonISD::Hi, llvm::MVT::i32, llvm::TLSModel::InitialExec, llvm::MachineFunction::insert(), invertFPCondCodeUser(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), llvm::MipsSubtarget::isLittle(), IsN64, LargeGOT, llvm_unreachable, llvm::HexagonISD::Lo, llvm::MipsISD::Lo, llvm::TLSModel::LocalDynamic, llvm::TLSModel::LocalExec, llvm::TargetLowering::LowerCallTo(), llvm::A64CC::MI, llvm::MipsII::MO_DTPREL_HI, llvm::MipsII::MO_DTPREL_LO, llvm::MipsII::MO_GOT16, llvm::MipsII::MO_GOT_DISP, llvm::MipsII::MO_GOT_HI16, llvm::MipsII::MO_GOT_LO16, llvm::MipsII::MO_GOTTPREL, llvm::MipsII::MO_GPREL, llvm::MipsII::MO_TLSGD, llvm::MipsII::MO_TLSLDM, llvm::MipsII::MO_TPREL_HI, llvm::MipsII::MO_TPREL_LO, model, llvm::ISD::MUL, llvm::next(), llvm::TargetLowering::ArgListEntry::Node, OR, llvm::MVT::Other, llvm::Reloc::PIC_, llvm::AArch64ISD::Ret, llvm::PPCISD::SC, llvm::ISD::SELECT, llvm::ISD::SETCC, llvm::ISD::SEXTLOAD, llvm::MachineBasicBlock::splice(), llvm::ISD::SRA, Subtarget, llvm::MipsISD::ThreadPointer, TII, llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs(), llvm::TargetLowering::ArgListEntry::Ty, llvm::MipsISD::Wrapper, and XOR.
Referenced by llvm::Mips16TargetLowering::EmitInstrWithCustomInserter(), and llvm::MipsSETargetLowering::EmitInstrWithCustomInserter().
template<class NodeTy > SDValue llvm::MipsTargetLowering::getAddrGlobal (NodeTy * N, EVT Ty, SelectionDAG & DAG, unsigned Flag, SDValue Chain, const MachinePointerInfo & PtrInfo) const inline protected
Definition at line 278 of file MipsISelLowering.h.
References llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getNode(), and llvm::MipsISD::Wrapper.
Referenced by EmitInstrWithCustomInserter(), and getOpndList().
template<class NodeTy > SDValue llvm::MipsTargetLowering::getAddrGlobalLargeGOT (NodeTy * N, EVT Ty, SelectionDAG & DAG, unsigned HiFlag, unsigned LoFlag, SDValue Chain, const MachinePointerInfo & PtrInfo) const inline protected
Definition at line 292 of file MipsISelLowering.h.
References llvm::ISD::ADD, llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getNode(), llvm::MipsISD::Hi, and llvm::MipsISD::Wrapper.
Referenced by EmitInstrWithCustomInserter(), and getOpndList().
template<class NodeTy > SDValue llvm::MipsTargetLowering::getAddrLocal (NodeTy * N, EVT Ty, SelectionDAG & DAG, bool HasMips64) const inline protected
Definition at line 258 of file MipsISelLowering.h.
References llvm::ISD::ADD, llvm::SelectionDAG::getEntryNode(), llvm::MachinePointerInfo::getGOT(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getNode(), llvm::ARMCP::GOT, llvm::MipsISD::Lo, llvm::SPII::Load, llvm::MipsII::MO_ABS_LO, llvm::MipsII::MO_GOT, llvm::MipsII::MO_GOT_OFST, llvm::MipsII::MO_GOT_PAGE, and llvm::MipsISD::Wrapper.
Referenced by EmitInstrWithCustomInserter(), and getOpndList().
template<class NodeTy > SDValue llvm::MipsTargetLowering::getAddrNonPIC (NodeTy * N, EVT Ty, SelectionDAG & DAG) const inline protected
Definition at line 311 of file MipsISelLowering.h.
References llvm::ISD::ADD, llvm::SelectionDAG::getNode(), llvm::MipsISD::Hi, llvm::MipsISD::Lo, llvm::MipsII::MO_ABS_HI, and llvm::MipsII::MO_ABS_LO.
Referenced by EmitInstrWithCustomInserter().
SDValue MipsTargetLowering::getGlobalReg (SelectionDAG & DAG, EVT Ty) const protected
Definition at line 79 of file MipsISelLowering.cpp.
References llvm::ConstantPoolSDNode::getAlignment(), llvm::BlockAddressSDNode::getBlockAddress(), llvm::ConstantPoolSDNode::getConstVal(), llvm::GlobalAddressSDNode::getGlobal(), llvm::MipsFunctionInfo::getGlobalBaseReg(), llvm::JumpTableSDNode::getIndex(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::ConstantPoolSDNode::getOffset(), llvm::SelectionDAG::getRegister(), llvm::ExternalSymbolSDNode::getSymbol(), llvm::SelectionDAG::getTargetBlockAddress(), llvm::SelectionDAG::getTargetConstantPool(), llvm::SelectionDAG::getTargetExternalSymbol(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::SelectionDAG::getTargetJumpTable(), and N.
Referenced by EmitInstrWithCustomInserter(), and getOpndList().
void MipsTargetLowering::getOpndList (SmallVectorImpl< SDValue > & Ops, std::deque< std::pair< unsigned, SDValue > > & RegsToPass, bool IsPICCall, bool GlobalOrExternal, bool InternalLinkage, CallLoweringInfo & CLI, SDValue Callee, SDValue Chain) const protected virtual
This function fills Ops, which is the list of operands that will later be used when a function call node is created. It also generates copyToReg nodes to set up argument registers.
Definition at line 2247 of file MipsISelLowering.cpp.
References addLiveIn(), llvm::object::advance(), llvm::CCValAssign::AExt, llvm::MipsTargetLowering::MipsCC::analyzeCallOperands(), llvm::MipsTargetLowering::MipsCC::analyzeCallResult(), llvm::MipsTargetLowering::MipsCC::analyzeReturn(), llvm::ISD::ANY_EXTEND, llvm::Function::arg_begin(), llvm::TargetLowering::CallLoweringInfo::Args, llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::ISD::BITCAST, llvm::MipsISD::BuildPairF64, llvm::TargetLowering::C_Memory, llvm::TargetLowering::C_RegisterClass, llvm::TargetLowering::CallLoweringInfo::CallConv, llvm::TargetLowering::CallLoweringInfo::Callee, llvm::TargetLowering::AsmOperandInfo::CallOperandVal, llvm::MipsFunctionInfo::callPtrInfo(), llvm::TargetLowering::CallLoweringInfo::Chain, llvm::CCState::CheckReturn(), llvm::MachineFrameInfo::CreateFixedObject(), llvm::TargetLowering::CW_Constant, llvm::TargetLowering::CW_Default, llvm::TargetLowering::CW_Invalid, llvm::TargetLowering::CW_Memory, llvm::TargetLowering::CW_Register, llvm::TargetLowering::CW_SpecificReg, llvm::TargetLowering::CallLoweringInfo::DAG, llvm::TargetLowering::CallLoweringInfo::DL, llvm::SmallVectorBase::empty(), llvm::MipsISD::ExtractElementF64, F(), llvm::MVT::f32, llvm::MVT::f64, llvm::CCValAssign::Full, G, getAddrGlobal(), getAddrGlobalLargeGOT(), getAddrLocal(), getBitWidth(), llvm::ISD::ArgFlagsTy::getByValSize(), llvm::TargetRegisterInfo::getCallPreservedMask(), llvm::SelectionDAG::getCALLSEQ_END(), llvm::SelectionDAG::getCALLSEQ_START(), llvm::SelectionDAG::getConstant(), llvm::TargetLowering::getConstraintType(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getEntryNode(), llvm::MachinePointerInfo::getFixedStack(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::TargetMachine::getFrameLowering(), llvm::MachineFunction::getFunction(), getGlobalReg(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getMachineFunction(), llvm::MipsRegisterInfo::getMips16RetHelperMask(), getNextIntArgReg(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::TargetLoweringBase::getRegClassFor(), llvm::MachineFunction::getRegInfo(), llvm::SelectionDAG::getRegister(), llvm::TargetMachine::getRegisterInfo(), llvm::SelectionDAG::getRegisterMask(), llvm::TargetMachine::getRelocationModel(), llvm::Function::getReturnType(), llvm::TargetLowering::getSingleConstraintMatchWeight(), llvm::EVT::getSizeInBits(), llvm::MipsFunctionInfo::getSRetReturnReg(), llvm::TargetFrameLowering::getStackAlignment(), llvm::MachineFunction::getTarget(), llvm::SelectionDAG::getTargetExternalSymbol(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::TargetLoweringBase::getTargetMachine(), llvm::Value::getType(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::CCValAssign::getValVT(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::Function::hasFnAttribute(), llvm::GlobalValue::hasInternalLinkage(), HasMips64, llvm::MipsSubtarget::hasMSA(), llvm::Function::hasStructRetAttr(), llvm::HexagonISD::Hi, i, llvm::MVT::i32, llvm::MVT::i64, info, llvm::MipsSubtarget::inMips16HardFloat(), llvm::MipsISD::Ins, llvm::TargetLowering::CallLoweringInfo::Ins, llvm::ISD::ArgFlagsTy::isByVal(), llvm::Type::isFloatTy(), llvm::MipsSubtarget::isFP64bit(), llvm::Type::isIntegerTy(), llvm::MipsSubtarget::isLittle(), llvm::CCValAssign::isMemLoc(), IsN64, IsO32, llvm::CCValAssign::isRegLoc(), llvm::TargetLowering::CallLoweringInfo::IsTailCall, llvm::TargetLowering::CallLoweringInfo::IsVarArg, llvm::Type::isVectorTy(), llvm::MipsISD::JmpLink, LargeGOT, llvm_unreachable, llvm::HexagonISD::Lo, llvm::SPII::Load, llvm::MipsSubtarget::mipsSEUsesSoftFloat(), llvm::MipsII::MO_CALL_HI16, llvm::MipsII::MO_CALL_LO16, llvm::MipsII::MO_GOT_CALL, llvm::MipsII::MO_NO_FLAG, llvm::MVT::Other, llvm::TargetLowering::CallLoweringInfo::Outs, llvm::TargetLowering::CallLoweringInfo::OutVals, llvm::Reloc::PIC_, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::MipsISD::Ret, llvm::TargetLowering::CallLoweringInfo::RetTy, llvm::RoundUpToAlignment(), S, llvm::MipsFunctionInfo::setFormalArgInfo(), llvm::MipsFunctionInfo::setSRetReturnReg(), llvm::MipsFunctionInfo::setVarArgsFrameIndex(), llvm::CCValAssign::SExt, llvm::ISD::SIGN_EXTEND, llvm::SmallVectorTemplateCommon< T >::size(), Subtarget, std::swap(), llvm::MipsISD::TailCall, llvm::ISD::TokenFactor, llvm::ISD::TRUNCATE, type, llvm::ISD::ZERO_EXTEND, and llvm::CCValAssign::ZExt.
Referenced by llvm::MipsSETargetLowering::EmitInstrWithCustomInserter(), and getNextIntArgReg().
virtual MVT llvm::MipsTargetLowering::getScalarShiftAmountTy (EVT LHSTy) const inline virtual
Reimplemented from llvm::TargetLoweringBase.
Definition at line 217 of file MipsISelLowering.h.
References llvm::MVT::i32, llvm::A64CC::MI, and N.
Referenced by performMULCombine().
EVT MipsTargetLowering::getSetCCResultType (LLVMContext & Context, EVT VT) const virtual
getSetCCResultType - get the ISD::SETCC result ValueType
Reimplemented from llvm::TargetLoweringBase.
Definition at line 404 of file MipsISelLowering.cpp.
References llvm::EVT::changeVectorElementTypeToInteger(), llvm::MVT::i32, and llvm::EVT::isVector().
Referenced by EmitInstrWithCustomInserter().
const char * MipsTargetLowering::getTargetNodeName (unsigned Opcode) const virtual
getTargetNodeName - This method returns the name of a target specific
Reimplemented from llvm::TargetLowering.
Definition at line 115 of file MipsISelLowering.cpp.
References llvm::MipsISD::BuildPairF64, llvm::MipsISD::CMovFP_F, llvm::MipsISD::CMovFP_T, llvm::MipsISD::DivRem, llvm::MipsISD::DivRem16, llvm::MipsISD::DivRemU, llvm::MipsISD::DivRemU16, llvm::MipsISD::EH_RETURN, llvm::MipsISD::Ext, llvm::MipsISD::EXTP, llvm::MipsISD::EXTPDP, llvm::MipsISD::EXTR_R_W, llvm::MipsISD::EXTR_RS_W, llvm::MipsISD::EXTR_S_H, llvm::MipsISD::EXTR_W, llvm::MipsISD::ExtractElementF64, llvm::MipsISD::FPBrcond, llvm::MipsISD::FPCmp, llvm::MipsISD::GPRel, llvm::MipsISD::Hi, llvm::MipsISD::ILVEV, llvm::MipsISD::ILVL, llvm::MipsISD::ILVOD, llvm::MipsISD::ILVR, llvm::MipsISD::Ins, llvm::MipsISD::JmpLink, llvm::MipsISD::LDL, llvm::MipsISD::LDR, llvm::MipsISD::Lo, llvm::MipsISD::LWL, llvm::MipsISD::LWR, llvm::MipsISD::MAdd, llvm::MipsISD::MADD_DSP, llvm::MipsISD::MAddu, llvm::MipsISD::MADDU_DSP, llvm::MipsISD::MFHI, llvm::MipsISD::MFLO, MipsTargetLowering(), llvm::MipsISD::MSub, llvm::MipsISD::MSUB_DSP, llvm::MipsISD::MSubu, llvm::MipsISD::MSUBU_DSP, llvm::MipsISD::MTHLIP, llvm::MipsISD::MTLOHI, llvm::MipsISD::Mult, llvm::MipsISD::MULT, llvm::MipsISD::Multu, llvm::MipsISD::MULTU, llvm::MipsISD::PCKEV, llvm::MipsISD::PCKOD, llvm::MipsISD::Ret, llvm::MipsISD::SDL, llvm::MipsISD::SDR, llvm::MipsISD::SELECT_CC_DSP, llvm::MipsISD::SETCC_DSP, llvm::MipsISD::SHF, llvm::MipsISD::SHILO, llvm::MipsISD::SHLL_DSP, llvm::MipsISD::SHRA_DSP, llvm::MipsISD::SHRL_DSP, llvm::MipsISD::SWL, llvm::MipsISD::SWR, llvm::MipsISD::Sync, llvm::MipsISD::TailCall, llvm::MipsISD::ThreadPointer, llvm::MipsISD::TruncIntFP, llvm::MipsISD::VALL_NONZERO, llvm::MipsISD::VALL_ZERO, llvm::MipsISD::VANY_NONZERO, llvm::MipsISD::VANY_ZERO, llvm::MipsISD::VCEQ, llvm::MipsISD::VCLE_S, llvm::MipsISD::VCLE_U, llvm::MipsISD::VCLT_S, llvm::MipsISD::VCLT_U, llvm::MipsISD::VEXTRACT_SEXT_ELT, llvm::MipsISD::VEXTRACT_ZEXT_ELT, llvm::MipsISD::VNOR, llvm::MipsISD::VSHF, llvm::MipsISD::VSMAX, llvm::MipsISD::VSMIN, llvm::MipsISD::VUMAX, llvm::MipsISD::VUMIN, and llvm::MipsISD::Wrapper.
SDValue MipsTargetLowering::lowerLOAD (SDValue Op, SelectionDAG & DAG) const protected
Definition at line 1942 of file MipsISelLowering.cpp.
References createLoadLR(), llvm::ISD::EXTLOAD, llvm::MemSDNode::getAlignment(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::LoadSDNode::getExtensionType(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::MVT::i32, llvm::MVT::i64, llvm::MipsSubtarget::isLittle(), llvm::A64DB::LD, llvm::MipsISD::LDL, llvm::MipsISD::LDR, llvm::MipsISD::LWL, llvm::MipsISD::LWR, llvm::ISD::NON_EXTLOAD, llvm::ISD::SEXTLOAD, llvm::ISD::SHL, llvm::ISD::SRL, Subtarget, llvm::RegState::Undef, and llvm::ISD::ZEXTLOAD.
Referenced by llvm::MipsSETargetLowering::EmitInstrWithCustomInserter(), and LowerOperation().
SDValue MipsTargetLowering::LowerOperation (SDValue Op, SelectionDAG & DAG) const virtual
LowerOperation - Provide custom lowering hooks for some operations.
Reimplemented from llvm::TargetLowering.
Reimplemented in llvm::MipsSETargetLowering.
Definition at line 715 of file MipsISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::ATOMIC_FENCE, llvm::ISD::BlockAddress, llvm::ISD::BR_JT, llvm::ISD::BRCOND, llvm::ISD::ConstantPool, llvm::ISD::EH_RETURN, llvm::ISD::FABS, llvm::ISD::FCOPYSIGN, llvm::ISD::FP_TO_SINT, llvm::ISD::FRAMEADDR, llvm::SDValue::getOpcode(), llvm::ISD::GlobalAddress, llvm::ISD::GlobalTLSAddress, llvm::ISD::JumpTable, llvm::ISD::LOAD, lowerLOAD(), lowerSTORE(), llvm::ISD::RETURNADDR, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::ISD::SHL_PARTS, llvm::ISD::SRA_PARTS, llvm::ISD::SRL_PARTS, llvm::ISD::STORE, and llvm::ISD::VASTART.
Referenced by llvm::MipsSETargetLowering::LowerOperation(), LowerOperationWrapper(), and ReplaceNodeResults().
void MipsTargetLowering::LowerOperationWrapper (SDNode * N, SmallVectorImpl< SDValue > & Results, SelectionDAG & DAG) const virtual
This callback is invoked by the type legalizer to legalize nodes with an illegal operand type but legal result types. It replaces the LowerOperation callback in the type Legalizer. The reason we can not do away with LowerOperation entirely is that LegalizeDAG isn't yet ready to use this callback.
TODO: Consider merging with ReplaceNodeResults.
The target places new result values for the node in Results (their number and types must exactly match those of the original return values of the node), or leaves Results empty, which indicates that the node is not to be custom lowered after all. The default implementation calls LowerOperation.
Reimplemented from llvm::TargetLowering.
Definition at line 698 of file MipsISelLowering.cpp.
References llvm::SDNode::getNumValues(), llvm::SDValue::getValue(), I, LowerOperation(), and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by ReplaceNodeResults().
SDValue MipsTargetLowering::lowerSTORE (SDValue Op, SelectionDAG & DAG) const protected
Definition at line 2064 of file MipsISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::BITCAST, llvm::MachineFrameInfo::CreateFixedObject(), llvm::ISD::FRAME_TO_ARGS_OFFSET, llvm::ISD::FRAMEADDR, llvm::MemSDNode::getAlignment(), llvm::SelectionDAG::getConstant(), llvm::EVT::getFloatingPointVT(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::MVT::i32, llvm::MVT::i64, llvm::MipsSubtarget::isLittle(), lowerFP_TO_SINT_STORE(), lowerUnalignedIntStore(), Subtarget, and llvm::MipsISD::TruncIntFP.
Referenced by llvm::MipsSETargetLowering::EmitInstrWithCustomInserter(), and LowerOperation().
SDValue MipsTargetLowering::PerformDAGCombine (SDNode * N, DAGCombinerInfo & DCI) const virtual
This method will be invoked for all target nodes and for any target-independent nodes that the target has registered with invoke it for.
The semantics are as follows: Return Value: SDValue.Val == 0 - No change was made SDValue.Val == N - N was replaced, is dead, and is already handled. otherwise - N should be replaced by the returned Operand.
In addition, methods provided by DAGCombinerInfo may be used to perform more complex transformations.
Reimplemented from llvm::TargetLowering.
Reimplemented in llvm::MipsSETargetLowering.
Definition at line 674 of file MipsISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::TargetLowering::DAGCombinerInfo::DAG, llvm::SDNode::getOpcode(), llvm::ISD::OR, performADDCombine(), performANDCombine(), performDivRemCombine(), performORCombine(), performSELECTCombine(), llvm::ISD::SDIVREM, llvm::ISD::SELECT, Subtarget, and llvm::ISD::UDIVREM.
Referenced by llvm::MipsSETargetLowering::PerformDAGCombine().
void MipsTargetLowering::ReplaceNodeResults (SDNode * N, SmallVectorImpl< SDValue > & Results, SelectionDAG & DAG) const virtual
ReplaceNodeResults - Replace the results of node with an illegal result type with new values built out of custom code.
Reimplemented from llvm::TargetLowering.
Definition at line 708 of file MipsISelLowering.cpp.
References LowerOperation(), and LowerOperationWrapper().
Member Data Documentation
bool llvm::MipsTargetLowering::HasMips64 protected
Definition at line 431 of file MipsISelLowering.h.
Referenced by EmitInstrWithCustomInserter(), getOpndList(), llvm::MipsSETargetLowering::MipsSETargetLowering(), MipsTargetLowering(), and parsePhysicalReg().
bool llvm::MipsTargetLowering::IsN64 protected
Definition at line 431 of file MipsISelLowering.h.
Referenced by llvm::MipsSETargetLowering::EmitInstrWithCustomInserter(), EmitInstrWithCustomInserter(), getOpndList(), lowerFABS64(), MipsTargetLowering(), and parsePhysicalReg().
bool llvm::MipsTargetLowering::IsO32 protected
Definition at line 431 of file MipsISelLowering.h.
Referenced by getOpndList().
const MipsSubtarget* llvm::MipsTargetLowering::Subtarget protected
Definition at line 429 of file MipsISelLowering.h.
Referenced by llvm::MipsSETargetLowering::EmitInstrWithCustomInserter(), EmitInstrWithCustomInserter(), getOpndList(), llvm::MipsSETargetLowering::getRepRegClassFor(), isConstantOrUndefBUILD_VECTOR(), lowerFABS64(), lowerFCOPYSIGN64(), lowerLOAD(), lowerMSABitClearImm(), lowerSTORE(), lowerVECTOR_SHUFFLE_VSHF(), llvm::Mips16TargetLowering::Mips16TargetLowering(), llvm::MipsSETargetLowering::MipsSETargetLowering(), MipsTargetLowering(), originalTypeIsF128(), parsePhysicalReg(), llvm::MipsSETargetLowering::PerformDAGCombine(), and PerformDAGCombine().
The documentation for this class was generated from the following files:
MipsISelLowering.h
MipsISelLowering.cpp