LLVM: llvm::ARMAsmPrinter Class Reference
LLVM API Documentation
llvm::ARMAsmPrinter Class Reference
#include <ARMAsmPrinter.h>
Public Member Functions
ARMAsmPrinter (TargetMachine &TM, MCStreamer &Streamer)
virtual const char * getPassName () const LLVM_OVERRIDE
void printOperand (const MachineInstr *MI, int OpNum, raw_ostream &O, const char *Modifier=0)
virtual bool PrintAsmOperand (const MachineInstr *MI, unsigned OpNum, unsigned AsmVariant, const char *ExtraCode, raw_ostream &O) LLVM_OVERRIDE
virtual bool PrintAsmMemoryOperand (const MachineInstr *MI, unsigned OpNum, unsigned AsmVariant, const char *ExtraCode, raw_ostream &O) LLVM_OVERRIDE
void EmitJumpTable (const MachineInstr *MI)
void EmitJump2Table (const MachineInstr *MI)
virtual void EmitInstruction (const MachineInstr *MI) LLVM_OVERRIDE
EmitInstruction - Targets should implement this to emit instructions.
virtual bool runOnMachineFunction (MachineFunction &F) LLVM_OVERRIDE
virtual void EmitConstantPool () LLVM_OVERRIDE
virtual void EmitFunctionBodyEnd () LLVM_OVERRIDE
virtual void EmitFunctionEntryLabel () LLVM_OVERRIDE
virtual void EmitStartOfAsmFile (Module &M) LLVM_OVERRIDE
virtual void EmitEndOfAsmFile (Module &M) LLVM_OVERRIDE
virtual void EmitXXStructor (const Constant *CV) LLVM_OVERRIDE
bool lowerOperand (const MachineOperand &MO, MCOperand &MCOp)
virtual void EmitDwarfRegOp (const MachineLocation &MLoc, bool Indirect) const LLVM_OVERRIDE
EmitDwarfRegOp - Emit dwarf register operation.
virtual unsigned getISAEncoding () LLVM_OVERRIDE
virtual void EmitMachineConstantPoolValue (MachineConstantPoolValue *MCPV) LLVM_OVERRIDE
Public Member Functions inherited from llvm::AsmPrinter
virtual ~AsmPrinter ()
const DwarfDebug * getDwarfDebug () const
bool isVerbose () const
unsigned getFunctionNumber () const
const TargetLoweringObjectFile & getObjFileLowering () const
getObjFileLowering - Return information about object file lowering.
const DataLayout & getDataLayout () const
getDataLayout - Return information about data layout.
StringRef getTargetTriple () const
getTargetTriple - Return the target triple string.
const MCSection * getCurrentSection () const
getCurrentSection() - Return the current section we are emitting to.
MCSymbol * getSymbol (const GlobalValue *GV) const
void getAnalysisUsage (AnalysisUsage &AU) const
bool doInitialization (Module &M)
bool doFinalization (Module &M)
void SetupMachineFunction (MachineFunction &MF)
void EmitFunctionHeader ()
void EmitFunctionBody ()
void emitPrologLabel (const MachineInstr &MI)
CFIMoveType needsCFIMoves ()
bool needsSEHMoves ()
bool needsRelocationsForDwarfStringPool () const
void EmitJumpTableInfo ()
virtual void EmitGlobalVariable (const GlobalVariable *GV)
EmitGlobalVariable - Emit the specified global variable to the .s file.
bool EmitSpecialLLVMGlobal (const GlobalVariable *GV)
void EmitAlignment (unsigned NumBits, const GlobalValue *GV=0) const
void EmitBasicBlockStart (const MachineBasicBlock *MBB) const
void EmitGlobalConstant (const Constant *CV)
Print a general LLVM constant to the .s file.
virtual void EmitFunctionBodyStart ()
virtual bool isBlockOnlyReachableByFallthrough (const MachineBasicBlock *MBB) const
virtual void emitImplicitDef (const MachineInstr *MI) const
MCSymbol * GetTempSymbol (StringRef Name, unsigned ID) const
MCSymbol * GetTempSymbol (StringRef Name) const
MCSymbol * GetSymbolWithGlobalValueBase (const GlobalValue *GV, StringRef Suffix, bool ForcePrivate=true) const
MCSymbol * GetExternalSymbolSymbol (StringRef Sym) const
MCSymbol * GetCPISymbol (unsigned CPID) const
GetCPISymbol - Return the symbol for the specified constant pool entry.
MCSymbol * GetJTISymbol (unsigned JTID, bool isLinkerPrivate=false) const
GetJTISymbol - Return the symbol for the specified jump table entry.
MCSymbol * GetJTSetSymbol (unsigned UID, unsigned MBBID) const
MCSymbol * GetBlockAddressSymbol (const BlockAddress *BA) const
MCSymbol * GetBlockAddressSymbol (const BasicBlock *BB) const
void printOffset (int64_t Offset, raw_ostream &OS) const
printOffset - This is just convenient handler for printing offsets.
void EmitInt8 (int Value) const
void EmitInt16 (int Value) const
void EmitInt32 (int Value) const
void EmitLabelDifference (const MCSymbol *Hi, const MCSymbol *Lo, unsigned Size) const
void EmitLabelOffsetDifference (const MCSymbol *Hi, uint64_t Offset, const MCSymbol *Lo, unsigned Size) const
void EmitLabelPlusOffset (const MCSymbol *Label, uint64_t Offset, unsigned Size, bool IsSectionRelative=false) const
void EmitLabelReference (const MCSymbol *Label, unsigned Size, bool IsSectionRelative=false) const
void EmitSLEB128 (int64_t Value, const char *Desc=0) const
EmitSLEB128 - emit the specified signed leb128 value.
void EmitULEB128 (uint64_t Value, const char *Desc=0, unsigned PadTo=0) const
EmitULEB128 - emit the specified unsigned leb128 value.
void EmitCFAByte (unsigned Val) const
EmitCFAByte - Emit a .byte 42 directive for a DW_CFA_xxx value.
void EmitEncodingByte (unsigned Val, const char *Desc=0) const
unsigned GetSizeOfEncodedValue (unsigned Encoding) const
GetSizeOfEncodedValue - Return the size of the encoding in bytes.
void EmitTTypeReference (const GlobalValue *GV, unsigned Encoding) const
EmitReference - Emit reference to a ttype global with a specified encoding.
void EmitSectionOffset (const MCSymbol *Label, const MCSymbol *SectionLabel) const
void emitCFIInstruction (const MCCFIInstruction &Inst) const
Emit frame instruction to describe the layout of the frame.
virtual void PrintSpecial (const MachineInstr *MI, raw_ostream &OS, const char *Code) const
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const
createPrinterPass - Get a function printer pass.
virtual void assignPassManager (PMStack &PMS, PassManagerType T)
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Additional Inherited Members
Public Types inherited from llvm::AsmPrinter
enum CFIMoveType { CFI_M_None, CFI_M_EH, CFI_M_Debug }
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Public Attributes inherited from llvm::AsmPrinter
TargetMachine & TM
const MCAsmInfo * MAI
const MCInstrInfo * MII
MCContext & OutContext
MCStreamer & OutStreamer
const MachineFunction * MF
The current machine function.
MachineModuleInfo * MMI
MMI - This is a pointer to the current MachineModuleInfo.
Mangler * Mang
MCSymbol * CurrentFnSym
MCSymbol * CurrentFnSymForSize
Protected Member Functions inherited from llvm::AsmPrinter
AsmPrinter (TargetMachine &TM, MCStreamer &Streamer)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
Detailed Description
Definition at line 29 of file ARMAsmPrinter.h.
Constructor & Destructor Documentation
llvm::ARMAsmPrinter::ARMAsmPrinter (TargetMachine & TM, MCStreamer & Streamer) inline explicit
Definition at line 47 of file ARMAsmPrinter.h.
References llvm::TargetMachine::getSubtarget().
Member Function Documentation
virtual void llvm::ARMAsmPrinter::EmitConstantPool () inline virtual
EmitConstantPool - Print to the current output stream assembly representations of the constants in the constant pool MCP. This is used to print out constants which have been "spilled to memory" by the code generator.
Reimplemented from llvm::AsmPrinter.
Definition at line 71 of file ARMAsmPrinter.h.
References LLVM_OVERRIDE, and M.
void ARMAsmPrinter::EmitDwarfRegOp (const MachineLocation & MLoc, bool Indirect) const virtual
EmitDwarfRegOp - Emit dwarf register operation.
Reimplemented from llvm::AsmPrinter.
Definition at line 60 of file ARMAsmPrinter.cpp.
References llvm::MCStreamer::AddComment(), llvm::dwarf::DW_OP_bit_piece, llvm::dwarf::DW_OP_piece, llvm::dwarf::DW_OP_regx, llvm::AsmPrinter::EmitDwarfRegOp(), llvm::AsmPrinter::EmitInt8(), llvm::AsmPrinter::EmitULEB128(), llvm::MCRegisterInfo::getDwarfRegNum(), llvm::MachineLocation::getReg(), llvm::TargetMachine::getRegisterInfo(), llvm::MachineLocation::isReg(), llvm::AsmPrinter::OutStreamer, and llvm::AsmPrinter::TM.
void ARMAsmPrinter::EmitEndOfAsmFile (Module &) virtual
EmitEndOfAsmFile - This virtual method can be overridden by targets that want to emit something at the end of their file.
Reimplemented from llvm::AsmPrinter.
Definition at line 511 of file ARMAsmPrinter.cpp.
References llvm::MCStreamer::AddBlankLine(), llvm::MCSymbolRefExpr::Create(), llvm::AsmPrinter::EmitAlignment(), llvm::MCStreamer::EmitAssemblerFlag(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitSymbolAttribute(), llvm::MCStreamer::EmitValue(), llvm::MachineModuleInfoMachO::GetGVStubList(), llvm::MachineModuleInfoMachO::GetHiddenGVStubList(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getInt(), llvm::MCObjectFileInfo::getNonLazySymbolPointerSection(), llvm::MachineModuleInfo::getObjFileInfo(), llvm::AsmPrinter::getObjFileLowering(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer(), i, llvm::ARMSubtarget::isTargetDarwin(), llvm::MCAF_SubsectionsViaSymbols, llvm::MCSA_IndirectSymbol, llvm::AsmPrinter::MMI, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, and llvm::MCStreamer::SwitchSection().
void ARMAsmPrinter::EmitFunctionBodyEnd () virtual
EmitFunctionBodyEnd - Targets can override this to emit stuff after the last basic block in the function.
Reimplemented from llvm::AsmPrinter.
Definition at line 123 of file ARMAsmPrinter.cpp.
References llvm::MCStreamer::EmitDataRegion(), llvm::MCDR_DataRegionEnd, and llvm::AsmPrinter::OutStreamer.
void ARMAsmPrinter::EmitFunctionEntryLabel () virtual
EmitFunctionEntryLabel - Emit the label that is the entrypoint for the function. This can be overridden by targets as required to do custom stuff.
Reimplemented from llvm::AsmPrinter.
Definition at line 132 of file ARMAsmPrinter.cpp.
References llvm::AsmPrinter::CurrentFnSym, llvm::MCStreamer::EmitAssemblerFlag(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitThumbFunc(), llvm::ARMFunctionInfo::isThumbFunction(), llvm::MCAF_Code16, and llvm::AsmPrinter::OutStreamer.
void ARMAsmPrinter::EmitInstruction (const MachineInstr *) virtual
EmitInstruction - Targets should implement this to emit instructions.
CONSTPOOL_ENTRY - This instruction represents a floating constant pool in the function. The first operand is the ID# for this instruction, the second is the index into the MachineConstantPool that this is, the third is the size in bytes of this constant pool entry. The required alignment is specified on the basic block holding this MI.
Reimplemented from llvm::AsmPrinter.
Definition at line 1108 of file ARMAsmPrinter.cpp.
References llvm::MCStreamer::AddComment(), llvm::MCInstBuilder::addImm(), llvm::MCInst::addOperand(), llvm::MCInstBuilder::addReg(), llvm::ARMCC::AL, llvm::MachineConstantPoolEntry::ConstVal, llvm::convertAddSubFlagsOpcode(), llvm::MCConstantExpr::Create(), llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateAdd(), llvm::MCOperand::CreateExpr(), llvm::MCOperand::CreateImm(), llvm::ARMMCExpr::CreateLower16(), llvm::MCOperand::CreateReg(), llvm::MCBinaryExpr::CreateSub(), llvm::ARMMCExpr::CreateUpper16(), llvm::TargetOpcode::DBG_VALUE, llvm::AsmPrinter::EmitAlignment(), llvm::MCStreamer::EmitDataRegion(), llvm::AsmPrinter::EmitGlobalConstant(), llvm::MCStreamer::EmitInstruction(), llvm::MCStreamer::EmitIntValue(), EmitJump2Table(), EmitJumpTable(), llvm::MCStreamer::EmitLabel(), EmitMachineConstantPoolValue(), llvm::MachineInstr::FrameSetup, llvm::MachineConstantPool::getConstants(), llvm::AsmPrinter::GetCPISymbol(), llvm::MachineInstr::getFlag(), llvm::AsmPrinter::getFunctionNumber(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), getPICLabel(), llvm::MCAsmInfo::getPrivateGlobalPrefix(), llvm::MachineOperand::getReg(), llvm::AsmPrinter::getSymbol(), llvm::MachineOperand::getTargetFlags(), llvm::MachineConstantPoolEntry::isMachineConstantPoolEntry(), llvm::ARMSubtarget::isTargetDarwin(), llvm_unreachable, llvm::LowerARMMachineInstrToMCInst(), llvm::MachineConstantPoolEntry::MachineCPVal, llvm::AsmPrinter::MAI, llvm::MCDR_DataRegion, llvm::MCDR_DataRegionEnd, llvm::ARMII::MO_HI16_NONLAZY_PIC, llvm::ARMII::MO_LO16_NONLAZY_PIC, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, llvm::MCInst::setOpcode(), llvm::ISD::TRAP, and llvm::MachineConstantPoolEntry::Val.
void ARMAsmPrinter::EmitJump2Table (const MachineInstr * MI)
Definition at line 904 of file ARMAsmPrinter.cpp.
References llvm::ARMCC::AL, llvm::MachineConstantPoolEntry::ConstVal, llvm::MCConstantExpr::Create(), llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateDiv(), llvm::MCBinaryExpr::CreateSub(), llvm::MachineInstr::dump(), llvm::MCStreamer::EmitDataRegion(), llvm::MCStreamer::EmitInstruction(), llvm::MCStreamer::EmitLabel(), llvm::ARMTargetStreamer::emitPad(), llvm::ARMTargetStreamer::emitRegSave(), llvm::ARMTargetStreamer::emitSetFP(), llvm::MCStreamer::EmitValue(), EnableARMEHABI, llvm::MachineInstr::FrameSetup, llvm::MachineFunction::getConstantPool(), llvm::MachineConstantPool::getConstants(), llvm::MachineInstr::getFlag(), llvm::TargetRegisterInfo::getFrameRegister(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineFunction::getInfo(), llvm::MachineFunction::getJumpTableInfo(), llvm::MachineJumpTableInfo::getJumpTables(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::ARMFunctionInfo::getOriginalCPIdx(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::TargetMachine::getRegisterInfo(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineFunction::getTarget(), llvm::MCStreamer::getTargetStreamer(), i, llvm::MachineOperand::isImplicit(), llvm::MachineConstantPoolEntry::isMachineConstantPoolEntry(), llvm_unreachable, llvm::MachineInstr::mayStore(), llvm::MCDR_DataRegionEnd, llvm::MCDR_DataRegionJT16, llvm::MCDR_DataRegionJT8, llvm::AsmPrinter::MF, llvm::A64CC::MI, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::MachineConstantPoolEntry::Val.
Referenced by EmitInstruction().
void ARMAsmPrinter::EmitJumpTable (const MachineInstr * MI)
Definition at line 853 of file ARMAsmPrinter.cpp.
References llvm::MCConstantExpr::Create(), llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateAdd(), llvm::MCBinaryExpr::CreateSub(), llvm::MCStreamer::EmitDataRegion(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitValue(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineFunction::getJumpTableInfo(), llvm::MachineJumpTableInfo::getJumpTables(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::TargetMachine::getRelocationModel(), llvm::MachineBasicBlock::getSymbol(), i, llvm::ARMFunctionInfo::isThumbFunction(), llvm::MCDR_DataRegionEnd, llvm::MCDR_DataRegionJT32, llvm::AsmPrinter::MF, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, llvm::Reloc::PIC_, and llvm::AsmPrinter::TM.
Referenced by EmitInstruction().
void ARMAsmPrinter::EmitMachineConstantPoolValue (MachineConstantPoolValue * MCPV) virtual
EmitMachineConstantPoolValue - Print a machine constantpool value to the .s file.
Reimplemented from llvm::AsmPrinter.
Definition at line 797 of file ARMAsmPrinter.cpp.
References llvm::MCConstantExpr::Create(), llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateAdd(), llvm::MCBinaryExpr::CreateSub(), llvm::MCContext::CreateTempSymbol(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitValue(), llvm::AsmPrinter::GetBlockAddressSymbol(), llvm::TargetMachine::getDataLayout(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::AsmPrinter::getFunctionNumber(), llvm::ARMConstantPoolValue::getLabelId(), llvm::ARMConstantPoolValue::getModifier(), getModifierVariantKind(), llvm::MCContext::GetOrCreateSymbol(), llvm::ARMConstantPoolValue::getPCAdjustment(), getPICLabel(), llvm::MCAsmInfo::getPrivateGlobalPrefix(), llvm::AsmPrinter::getSymbol(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineConstantPoolValue::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::ARMConstantPoolValue::isBlockAddress(), llvm::ARMConstantPoolValue::isExtSymbol(), llvm::ARMConstantPoolValue::isGlobalValue(), llvm::ARMConstantPoolValue::isLSDA(), llvm::ARMConstantPoolValue::isMachineBasicBlock(), llvm::AsmPrinter::MAI, llvm::ARMConstantPoolValue::mustAddCurrentAddress(), llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, llvm::raw_svector_ostream::str(), and llvm::AsmPrinter::TM.
Referenced by EmitInstruction(), and getModifierVariantKind().
void ARMAsmPrinter::EmitStartOfAsmFile (Module &) virtual
EmitStartOfAsmFile - This virtual method can be overridden by targets that want to emit something at the start of their file.
Reimplemented from llvm::AsmPrinter.
Definition at line 449 of file ARMAsmPrinter.cpp.
References llvm::Module::begin(), llvm::Reloc::DynamicNoPIC, llvm::MCStreamer::EmitAssemblerFlag(), llvm::Module::end(), F(), llvm::MCObjectFileInfo::getConstTextCoalSection(), llvm::MCContext::getMachOSection(), llvm::AsmPrinter::getObjFileLowering(), llvm::TargetMachine::getRelocationModel(), llvm::SectionKind::getText(), llvm::MCObjectFileInfo::getTextCoalSection(), llvm::MCObjectFileInfo::getTextSection(), i, llvm::SetVector< T, Vector, Set >::insert(), llvm::ARMSubtarget::isTargetDarwin(), llvm::ARMSubtarget::isTargetELF(), llvm::AsmPrinter::Mang, llvm::MCAF_SyntaxUnified, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, llvm::Reloc::PIC_, llvm::MachO::S_REGULAR, llvm::MachO::S_SYMBOL_STUBS, llvm::TargetLoweringObjectFile::SectionForGlobal(), llvm::SetVector< T, Vector, Set >::size(), llvm::MCStreamer::SwitchSection(), and llvm::AsmPrinter::TM.
void ARMAsmPrinter::EmitXXStructor (const Constant * CV) virtual
EmitXXStructor - Targets can override this to change how global constants that are part of a C++ static/global constructor list are emitted.
Reimplemented from llvm::AsmPrinter.
Definition at line 141 of file ARMAsmPrinter.cpp.
References llvm::MCSymbolRefExpr::Create(), llvm::dyn_cast(), llvm::MCStreamer::EmitValue(), llvm::TargetMachine::getDataLayout(), llvm::AsmPrinter::getSymbol(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::ARMSubtarget::isTargetDarwin(), llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, llvm::Value::stripPointerCasts(), llvm::AsmPrinter::TM, llvm::MCSymbolRefExpr::VK_ARM_TARGET1, and llvm::MCSymbolRefExpr::VK_None.
virtual unsigned llvm::ARMAsmPrinter::getISAEncoding () inline virtual
getISAEncoding - Get the value for DW_AT_APPLE_isa. Zero if no isa encoding specified.
Reimplemented from llvm::AsmPrinter.
Definition at line 104 of file ARMAsmPrinter.h.
References llvm::ARM::DW_ISA_ARM_arm, llvm::ARM::DW_ISA_ARM_thumb, GetSymbolRef(), LLVM_OVERRIDE, and llvm::ARMBuildAttrs::Symbol.
virtual const char* llvm::ARMAsmPrinter::getPassName () const inline virtual
getPassName - Return a nice clean name for a pass. This usually implemented in terms of the name that is registered by one of the Registration templates, but can be overloaded directly.
Reimplemented from llvm::Pass.
Definition at line 52 of file ARMAsmPrinter.h.
References F(), LLVM_OVERRIDE, and llvm::A64CC::MI.
bool ARMAsmPrinter::lowerOperand (const MachineOperand & MO, MCOperand & MCOp)
Definition at line 66 of file ARMMCInstLower.cpp.
References llvm::APFloat::convert(), llvm::APFloat::convertToDouble(), llvm::MCSymbolRefExpr::Create(), llvm::MCOperand::CreateExpr(), llvm::MCOperand::CreateFPImm(), llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), llvm::MachineOperand::getBlockAddress(), llvm::AsmPrinter::GetBlockAddressSymbol(), llvm::AsmPrinter::GetCPISymbol(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::MachineOperand::getFPImm(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::AsmPrinter::GetJTISymbol(), llvm::MachineOperand::getMBB(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), llvm::AsmPrinter::getSymbol(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getSymbolName(), llvm::MachineOperand::getType(), llvm::ConstantFP::getValueAPF(), llvm::APFloat::IEEEdouble, llvm::MachineOperand::isImplicit(), llvm_unreachable, llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_FPImmediate, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_JumpTableIndex, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_Register, llvm::MachineOperand::MO_RegisterMask, llvm::AsmPrinter::OutContext, and llvm::APFloat::rmTowardZero.
Referenced by llvm::LowerARMMachineInstrToMCInst().
bool ARMAsmPrinter::PrintAsmMemoryOperand (const MachineInstr * MI, unsigned OpNo, unsigned AsmVariant, const char * ExtraCode, raw_ostream & OS) virtual
PrintAsmMemoryOperand - Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant as an address. Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
Reimplemented from llvm::AsmPrinter.
Definition at line 424 of file ARMAsmPrinter.cpp.
References llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::ARMInstPrinter::getRegisterName(), and llvm::MachineOperand::isReg().
bool ARMAsmPrinter::PrintAsmOperand (const MachineInstr * MI, unsigned OpNo, unsigned AsmVariant, const char * ExtraCode, raw_ostream & O) virtual
PrintAsmOperand - Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant. Targets should override this to format as appropriate. This method can return true if the operand is erroneous.
PrintAsmOperand - Print the specified operand of MI, an INLINEASM instruction, using the specified assembler variant. Targets should override this to format as appropriate.
Reimplemented from llvm::AsmPrinter.
Definition at line 249 of file ARMAsmPrinter.cpp.
References llvm::MachineOperand::getImm(), llvm::InlineAsm::getNumOperandRegisters(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::TargetMachine::getRegisterInfo(), llvm::ARMInstPrinter::getRegisterName(), llvm::MCRegisterInfo::getSubReg(), llvm::MachineFunction::getTarget(), llvm::InlineAsm::hasRegClassConstraint(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isReg(), llvm::InlineAsm::isUseOperandTiedToDef(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::AsmPrinter::MF, llvm::AsmPrinter::PrintAsmOperand(), and printOperand().
void ARMAsmPrinter::printOperand (const MachineInstr * MI, int OpNum, raw_ostream & O, const char * Modifier = 0)
Definition at line 167 of file ARMAsmPrinter.cpp.
References llvm::AsmPrinter::GetCPISymbol(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::AsmPrinter::getFunctionNumber(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::AsmPrinter::GetJTISymbol(), llvm::MachineOperand::getMBB(), llvm::MachineOperand::getOffset(), llvm::MachineInstr::getOperand(), llvm::MCContext::GetOrCreateSymbol(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MCAsmInfo::getPrivateGlobalPrefix(), llvm::MachineOperand::getReg(), llvm::TargetMachine::getRegisterInfo(), llvm::ARMInstPrinter::getRegisterName(), llvm::MachineOperand::getSubReg(), llvm::MCRegisterInfo::getSubReg(), llvm::AsmPrinter::getSymbol(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getSymbolName(), llvm::MachineFunction::getTarget(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::getType(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm_unreachable, llvm::AsmPrinter::MAI, llvm::AsmPrinter::MF, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::ARMII::MO_HI16, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_JumpTableIndex, llvm::ARMII::MO_LO16, llvm::MachineOperand::MO_MachineBasicBlock, llvm::ARMII::MO_PLT, llvm::MachineOperand::MO_Register, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::printOffset(), llvm::SmallString< InternalLen >::str(), and llvm::LibFunc::strcmp.
Referenced by PrintAsmOperand().
bool ARMAsmPrinter::runOnMachineFunction (MachineFunction & MF) virtual
runOnMachineFunction - This uses the EmitInstruction() method to print assembly for each instruction.
Reimplemented from llvm::AsmPrinter.
Definition at line 160 of file ARMAsmPrinter.cpp.
References llvm::MachineFunction::getConstantPool(), llvm::MachineFunction::getInfo(), and llvm::AsmPrinter::runOnMachineFunction().
The documentation for this class was generated from the following files:
ARMAsmPrinter.h
ARMAsmPrinter.cpp
ARMMCInstLower.cpp