LLVM: llvm::error_category Class Reference
LLVM API Documentation
llvm::error_category Class Reference abstract
#include <system_error.h>
Public Member Functions
virtual ~error_category ()
virtual const char * name () const =0
virtual error_condition default_error_condition (int _ev) const
virtual bool equivalent (int _code, const error_condition &_condition) const
virtual bool equivalent (const error_code &_code, int _condition) const
virtual std::string message (int _ev) const =0
bool operator== (const error_category &_rhs) const
bool operator!= (const error_category &_rhs) const
bool operator< (const error_category &_rhs) const
Friends
class _do_message
Detailed Description
Definition at line 627 of file system_error.h.
Constructor & Destructor Documentation
llvm::error_category::~error_category () virtual
Definition at line 26 of file system_error.cpp.
Member Function Documentation
error_condition llvm::error_category::default_error_condition (int _ev) const virtual
Reimplemented in llvm::_system_error_category.
Definition at line 30 of file system_error.cpp.
Referenced by llvm::error_code::default_error_condition(), and equivalent().
bool llvm::error_category::equivalent (int _code, const error_condition & _condition) const virtual
Definition at line 35 of file system_error.cpp.
References default_error_condition().
Referenced by llvm::operator==().
bool llvm::error_category::equivalent (const error_code & _code, int _condition) const virtual
Definition at line 40 of file system_error.cpp.
References llvm::error_code::category(), and llvm::error_code::value().
virtual std::string llvm::error_category::message (int _ev) const pure virtual
Implemented in llvm::_do_message, llvm::_system_error_category, and llvm::_generic_error_category.
virtual const char* llvm::error_category::name () const pure virtual
Implemented in llvm::_system_error_category, and llvm::_generic_error_category.
bool llvm::error_category::operator!= (const error_category & _rhs) const inline
Definition at line 646 of file system_error.h.
bool llvm::error_category::operator< (const error_category & _rhs) const inline
Definition at line 648 of file system_error.h.
bool llvm::error_category::operator== (const error_category & _rhs) const inline
Definition at line 644 of file system_error.h.
Friends And Related Function Documentation
friend class _do_message friend
Definition at line 650 of file system_error.h.
The documentation for this class was generated from the following files:
system_error.h
system_error.cpp