LLVM: llvm::RecordVal Class Reference
LLVM API Documentation
llvm::RecordVal Class Reference
#include <Record.h>
Public Member Functions
RecordVal (Init *N, RecTy *T, unsigned P)
RecordVal (const std::string &N, RecTy *T, unsigned P)
const std::string & getName () const
const Init * getNameInit () const
std::string getNameInitAsString () const
unsigned getPrefix () const
RecTy * getType () const
Init * getValue () const
bool setValue (Init *V)
void dump () const
void print (raw_ostream &OS, bool PrintSem=true) const
Detailed Description
Definition at line 1339 of file Record.h.
Constructor & Destructor Documentation
RecordVal::RecordVal (Init * N, RecTy * T, unsigned P)
Definition at line 1630 of file Record.cpp.
References llvm::RecTy::convertValue(), and llvm::UnsetInit::get().
RecordVal::RecordVal (const std::string & N, RecTy * T, unsigned P)
Definition at line 1636 of file Record.cpp.
References llvm::RecTy::convertValue(), and llvm::UnsetInit::get().
Member Function Documentation
void RecordVal::dump () const
Definition at line 1648 of file Record.cpp.
References llvm::errs().
const std::string & RecordVal::getName () const
Definition at line 1642 of file Record.cpp.
References llvm::dyn_cast(), and llvm::StringInit::getValue().
Referenced by llvm::SubMultiClassReference::dump(), llvm::Record::getValueAsBit(), llvm::Record::getValueAsBitOrUnset(), llvm::Record::getValueAsBitsInit(), llvm::Record::getValueAsDag(), llvm::Record::getValueAsDef(), llvm::Record::getValueAsInt(), llvm::Record::getValueAsListInit(), llvm::Record::getValueAsListOfDefs(), llvm::Record::getValueAsListOfInts(), llvm::Record::getValueAsListOfStrings(), llvm::Record::getValueAsString(), llvm::Record::getValueInit(), and llvm::operator<<().
const Init* llvm::RecordVal::getNameInit () const inline
Definition at line 1349 of file Record.h.
Referenced by llvm::Record::addValue(), llvm::SubMultiClassReference::dump(), llvm::VarInit::resolveListElementReference(), and llvm::Record::resolveReferencesTo().
std::string llvm::RecordVal::getNameInitAsString () const inline
Definition at line 1350 of file Record.h.
Referenced by llvm::operator<<(), print(), and llvm::Record::resolveReferencesTo().
unsigned llvm::RecordVal::getPrefix () const inline
Definition at line 1354 of file Record.h.
References llvm::cl::Prefix.
Referenced by llvm::operator<<(), and print().
RecTy* llvm::RecordVal::getType () const inline
Definition at line 1355 of file Record.h.
Referenced by llvm::SubMultiClassReference::dump(), llvm::UnOpInit::Fold(), GetNewAnonymousName(), print(), and llvm::QualifyName().
Init* llvm::RecordVal::getValue () const inline
Definition at line 1356 of file Record.h.
Referenced by llvm::SubMultiClassReference::dump(), llvm::VarInit::getFieldType(), GetNewAnonymousName(), llvm::Record::getValueAsBit(), llvm::Record::getValueAsBitOrUnset(), llvm::Record::getValueAsBitsInit(), llvm::Record::getValueAsDag(), llvm::Record::getValueAsDef(), llvm::Record::getValueAsInt(), llvm::Record::getValueAsListInit(), llvm::Record::getValueAsString(), llvm::Record::getValueInit(), print(), llvm::VarInit::resolveListElementReference(), and llvm::Record::resolveReferencesTo().
void RecordVal::print (raw_ostream & OS, bool PrintSem = true) const
Definition at line 1650 of file Record.cpp.
References llvm::dyn_cast(), llvm::StringRecTy::get(), getNameInitAsString(), getPrefix(), llvm::TypedInit::getType(), getType(), getValue(), and llvm::PrintFatalError().
Referenced by llvm::operator<<().
bool llvm::RecordVal::setValue (Init * V) inline
Definition at line 1358 of file Record.h.
References llvm::Init::convertInitializerTo(), llvm::RecTy::dump(), and llvm::RecTy::print().
Referenced by llvm::SubMultiClassReference::dump(), and llvm::Record::resolveReferencesTo().
The documentation for this class was generated from the following files:
Record.h
Record.cpp