LLVM: llvm::MCContext Class Reference
LLVM API Documentation
llvm::MCContext Class Reference
#include <MCContext.h>
Public Types
typedef StringMap< MCSymbol *, BumpPtrAllocator & > SymbolTable
Public Member Functions
MCContext (const MCAsmInfo *MAI, const MCRegisterInfo *MRI, const MCObjectFileInfo *MOFI, const SourceMgr *Mgr=0, bool DoAutoReset=true)
~MCContext ()
const SourceMgr * getSourceManager () const
const MCAsmInfo * getAsmInfo () const
const MCRegisterInfo * getRegisterInfo () const
const MCObjectFileInfo * getObjectFileInfo () const
void setAllowTemporaryLabels (bool Value)
char * getSecureLogFile ()
raw_ostream * getSecureLog ()
bool getSecureLogUsed ()
void setSecureLog (raw_ostream *Value)
void setSecureLogUsed (bool Value)
void * Allocate (unsigned Size, unsigned Align=8)
void Deallocate (void *Ptr)
LLVM_ATTRIBUTE_NORETURN void FatalError (SMLoc L, const Twine &Msg)
Module Lifetime Management
void reset ()
Symbol Management
MCSymbol * CreateTempSymbol ()
unsigned getUniqueSymbolID ()
MCSymbol * CreateDirectionalLocalSymbol (int64_t LocalLabelVal)
MCSymbol * GetDirectionalLocalSymbol (int64_t LocalLabelVal, int bORf)
MCSymbol * GetOrCreateSymbol (StringRef Name)
MCSymbol * GetOrCreateSymbol (const Twine &Name)
MCSymbol * LookupSymbol (StringRef Name) const
LookupSymbol - Get the symbol for Name, or null.
MCSymbol * LookupSymbol (const Twine &Name) const
const SymbolTable & getSymbols () const
Section Management
const MCSectionMachO * getMachOSection (StringRef Segment, StringRef Section, unsigned TypeAndAttributes, unsigned Reserved2, SectionKind K)
const MCSectionMachO * getMachOSection (StringRef Segment, StringRef Section, unsigned TypeAndAttributes, SectionKind K)
const MCSectionELF * getELFSection (StringRef Section, unsigned Type, unsigned Flags, SectionKind Kind)
const MCSectionELF * getELFSection (StringRef Section, unsigned Type, unsigned Flags, SectionKind Kind, unsigned EntrySize, StringRef Group)
const MCSectionELF * CreateELFGroupSection ()
const MCSectionCOFF * getCOFFSection (StringRef Section, unsigned Characteristics, SectionKind Kind, StringRef COMDATSymName, int Selection, const MCSectionCOFF *Assoc=0)
const MCSectionCOFF * getCOFFSection (StringRef Section, unsigned Characteristics, SectionKind Kind)
const MCSectionCOFF * getCOFFSection (StringRef Section)
Dwarf Management
StringRef getCompilationDir () const
Get the compilation directory for DW_AT_comp_dir This can be overridden by clients which want to control the reported compilation directory and have it be something other than the current working directory.
void setCompilationDir (StringRef S)
Set the compilation directory for DW_AT_comp_dir Override the default (CWD) compilation directory.
const std::string & getMainFileName () const
Get the main file name for use in error messages and debug info. This can be set to ensure we've got the correct file name after preprocessing or for -save-temps.
void setMainFileName (StringRef S)
Set the main file name and override the default.
unsigned GetDwarfFile (StringRef Directory, StringRef FileName, unsigned FileNumber, unsigned CUID)
GetDwarfFile - creates an entry in the dwarf file and directory tables.
bool isValidDwarfFileNumber (unsigned FileNumber, unsigned CUID=0)
bool hasDwarfFiles () const
const SmallVectorImpl< MCDwarfFile * > & getMCDwarfFiles (unsigned CUID=0)
const SmallVectorImpl< StringRef > & getMCDwarfDirs (unsigned CUID=0)
const DenseMap< const MCSection *, MCLineSection * > & getMCLineSections () const
const std::vector< const MCSection * > & getMCLineSectionOrder () const
void addMCLineSection (const MCSection *Sec, MCLineSection *Line)
unsigned getDwarfCompileUnitID ()
void setDwarfCompileUnitID (unsigned CUIndex)
const DenseMap< unsigned, MCSymbol * > & getMCLineTableSymbols () const
MCSymbol * getMCLineTableSymbol (unsigned ID) const
void setMCLineTableSymbol (MCSymbol *Sym, unsigned ID)
void setCurrentDwarfLoc (unsigned FileNum, unsigned Line, unsigned Column, unsigned Flags, unsigned Isa, unsigned Discriminator)
void ClearDwarfLocSeen ()
bool getDwarfLocSeen ()
const MCDwarfLoc & getCurrentDwarfLoc ()
bool getGenDwarfForAssembly ()
void setGenDwarfForAssembly (bool Value)
unsigned getGenDwarfFileNumber ()
unsigned nextGenDwarfFileNumber ()
const MCSection * getGenDwarfSection ()
void setGenDwarfSection (const MCSection *Sec)
MCSymbol * getGenDwarfSectionStartSym ()
void setGenDwarfSectionStartSym (MCSymbol *Sym)
MCSymbol * getGenDwarfSectionEndSym ()
void setGenDwarfSectionEndSym (MCSymbol *Sym)
const std::vector< const MCGenDwarfLabelEntry * > & getMCGenDwarfLabelEntries () const
void addMCGenDwarfLabelEntry (const MCGenDwarfLabelEntry *E)
void setDwarfDebugFlags (StringRef S)
StringRef getDwarfDebugFlags ()
void setDwarfDebugProducer (StringRef S)
StringRef getDwarfDebugProducer ()
Detailed Description
MCContext - Context object for machine code objects. This class owns all of the sections that it creates.
Definition at line 46 of file MCContext.h.
Member Typedef Documentation
typedef StringMap<MCSymbol*, BumpPtrAllocator&> llvm::MCContext::SymbolTable
Definition at line 50 of file MCContext.h.
Constructor & Destructor Documentation
MCContext::MCContext (const MCAsmInfo * MAI, const MCRegisterInfo * MRI, const MCObjectFileInfo * MOFI, const SourceMgr * Mgr = 0, bool DoAutoReset = true) explicit
Definition at line 39 of file MCContext.cpp.
References llvm::sys::fs::current_path(), llvm::MemoryBuffer::getBufferIdentifier(), llvm::LibFunc::getenv, llvm::SourceMgr::getMemoryBuffer(), and llvm::SourceMgr::getNumBuffers().
MCContext::~MCContext ()
Definition at line 67 of file MCContext.cpp.
References reset().
Member Function Documentation
void llvm::MCContext::addMCGenDwarfLabelEntry (const MCGenDwarfLabelEntry * E) inline
Definition at line 387 of file MCContext.h.
Referenced by llvm::MCGenDwarfLabelEntry::Make().
void llvm::MCContext::addMCLineSection (const MCSection * Sec, MCLineSection * Line) inline
Definition at line 325 of file MCContext.h.
Referenced by llvm::MCLineEntry::Make().
void* llvm::MCContext::Allocate (unsigned Size, unsigned Align = 8) inline
Definition at line 409 of file MCContext.h.
References Align, and llvm::BumpPtrAllocator::Allocate().
Referenced by GetDwarfFile().
void llvm::MCContext::ClearDwarfLocSeen () inline
Definition at line 364 of file MCContext.h.
Referenced by llvm::MCLineEntry::Make().
MCSymbol * MCContext::CreateDirectionalLocalSymbol (int64_t LocalLabelVal)
CreateDirectionalLocalSymbol - Create the definition of a directional local symbol for numbered label (used for "1:" definitions).
Definition at line 185 of file MCContext.cpp.
References GetOrCreateSymbol(), and llvm::MCAsmInfo::getPrivateGlobalPrefix().
Referenced by getUniqueSymbolID().
const MCSectionELF * MCContext::CreateELFGroupSection ()
Definition at line 275 of file MCContext.cpp.
References llvm::SectionKind::getReadOnly().
Referenced by compareBySuffix(), and getMachOSection().
MCSymbol * MCContext::CreateTempSymbol ()
CreateTempSymbol - Create and return a new assembler temporary symbol with a unique but unspecified name.
Definition at line 164 of file MCContext.cpp.
References llvm::MCLabel::getInstance(), llvm::MCAsmInfo::getPrivateGlobalPrefix(), and llvm::MCLabel::incInstance().
Referenced by llvm::MachineModuleInfo::addLandingPad(), llvm::DwarfDebug::beginInstruction(), llvm::MCGenDwarfInfo::Emit(), llvm::MCDwarfFrameEmitter::Emit(), llvm::DwarfUnits::emitAddresses(), llvm::MCDwarfFileTable::EmitCU(), EmitDwarfLineTable(), EmitEncodingByte(), llvm::AsmPrinter::EmitFunctionBody(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), llvm::X86AsmPrinter::EmitInstruction(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), llvm::EmitUnwindInfo(), llvm::MCObjectStreamer::EmitValueToOffset(), llvm::MCStreamer::EmitWin64EHAllocStack(), llvm::MCStreamer::EmitWin64EHEndChained(), llvm::MCStreamer::EmitWin64EHEndProc(), llvm::MCStreamer::EmitWin64EHEndProlog(), llvm::MCStreamer::EmitWin64EHPushFrame(), llvm::MCStreamer::EmitWin64EHPushReg(), llvm::MCStreamer::EmitWin64EHSaveReg(), llvm::MCStreamer::EmitWin64EHSaveXMM(), llvm::MCStreamer::EmitWin64EHSetFrame(), llvm::MCStreamer::EmitWin64EHStartChained(), llvm::MCStreamer::EmitWin64EHStartProc(), llvm::DwarfDebug::endInstruction(), llvm::MCStreamer::ForceExpAbs(), llvm::PatchPointOpers::getNextScratchIdx(), llvm::TargetLoweringObjectFile::getTTypeReference(), INITIALIZE_PASS(), llvm::linkErlangGC(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::MCLineEntry::Make(), llvm::MCGenDwarfLabelEntry::Make(), llvm::MCStreamer::RecordProcEnd(), llvm::MCStreamer::RecordProcStart(), setAllowTemporaryLabels(), and llvm::XCoreFrameLowering::spillCalleeSavedRegisters().
void llvm::MCContext::Deallocate (void * Ptr) inline
Definition at line 412 of file MCContext.h.
References FatalError(), and LLVM_ATTRIBUTE_NORETURN.
void MCContext::FatalError (SMLoc L, const Twine & Msg)
Definition at line 412 of file MCContext.cpp.
References llvm::SourceMgr::DK_Error, exit(), llvm::SourceMgr::PrintMessage(), llvm::report_fatal_error(), and llvm::sys::RunInterruptHandlers().
Referenced by Deallocate(), getARMFixupKindMachOInfo(), llvm::MCAssembler::getAtom(), getFixupKindLog2Size(), and getFixupOffset().
const MCAsmInfo* llvm::MCContext::getAsmInfo () const inline
Definition at line 175 of file MCContext.h.
Referenced by llvm::MCGenDwarfInfo::Emit(), llvm::MCDwarfFrameEmitter::Emit(), llvm::MCDwarfFileTable::EmitCU(), EmitDwarfLineTable(), EmitEncodingByte(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), llvm::MCStreamer::EmitIntValue(), EmitPersonality(), EmitSymbol(), llvm::MCStreamer::ForceExpAbs(), getDataAlignmentFactor(), getSizeForEncoding(), llvm::MachineBasicBlock::getSymbol(), llvm::MCStreamer::RecordProcStart(), and ScaleAddrDelta().
const MCSectionCOFF * MCContext::getCOFFSection (StringRef Section, unsigned Characteristics, SectionKind Kind, StringRef COMDATSymName, int Selection, const MCSectionCOFF * Assoc = 0)
Definition at line 283 of file MCContext.cpp.
References llvm::StringRef::empty(), GetOrCreateSymbol(), and P.
Referenced by getCOFFSection(), getMachOSection(), llvm::getWin64EHFuncTableSection(), llvm::getWin64EHTableSection(), getWin64EHTableSection(), and llvm::MCObjectFileInfo::InitMCObjectFileInfo().
const MCSectionCOFF * MCContext::getCOFFSection (StringRef Section, unsigned Characteristics, SectionKind Kind)
Definition at line 312 of file MCContext.cpp.
References getCOFFSection().
const MCSectionCOFF * MCContext::getCOFFSection (StringRef Section)
Definition at line 317 of file MCContext.cpp.
References P.
StringRef llvm::MCContext::getCompilationDir () const inline
Get the compilation directory for DW_AT_comp_dir This can be overridden by clients which want to control the reported compilation directory and have it be something other than the current working directory.
Definition at line 281 of file MCContext.h.
Referenced by EmitGenDwarfInfo().
const MCDwarfLoc& llvm::MCContext::getCurrentDwarfLoc () inline
Definition at line 367 of file MCContext.h.
Referenced by llvm::MCLineEntry::Make().
MCSymbol * MCContext::GetDirectionalLocalSymbol (int64_t LocalLabelVal, int bORf)
GetDirectionalLocalSymbol - Create and return a directional local symbol for numbered label (used for "1b" or 1f" references).
Definition at line 191 of file MCContext.cpp.
References GetOrCreateSymbol(), and llvm::MCAsmInfo::getPrivateGlobalPrefix().
Referenced by getUniqueSymbolID().
unsigned llvm::MCContext::getDwarfCompileUnitID () inline
Definition at line 329 of file MCContext.h.
Referenced by llvm::DwarfDebug::endFunction(), and llvm::MCLineEntry::Make().
StringRef llvm::MCContext::getDwarfDebugFlags () inline
Definition at line 392 of file MCContext.h.
Referenced by EmitGenDwarfAbbrev(), and EmitGenDwarfInfo().
StringRef llvm::MCContext::getDwarfDebugProducer () inline
Definition at line 395 of file MCContext.h.
Referenced by EmitGenDwarfInfo().
unsigned MCContext::GetDwarfFile (StringRef Directory, StringRef FileName, unsigned FileNumber, unsigned CUID)
GetDwarfFile - creates an entry in the dwarf file and directory tables.
GetDwarfFile - takes a file name an number to place in the dwarf file and directory tables. If the file number has already been allocated it is an error and zero is returned and the client reports the error, else the allocated file number is returned. The file numbers may be in any order.
Definition at line 337 of file MCContext.cpp.
References Allocate(), llvm::StringRef::data(), llvm::StringRef::empty(), llvm::ARMBuildAttrs::File, llvm::sys::path::filename(), llvm::Intrinsic::memcpy, llvm::sys::path::parent_path(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorImpl< T >::resize(), llvm::StringRef::size(), and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by llvm::MCStreamer::EmitDwarfFileDirective(), and setMainFileName().
bool llvm::MCContext::getDwarfLocSeen () inline
Definition at line 366 of file MCContext.h.
Referenced by llvm::MCLineEntry::Make().
const MCSectionELF * MCContext::getELFSection (StringRef Section, unsigned Type, unsigned Flags, SectionKind Kind)
Definition at line 243 of file MCContext.cpp.
Referenced by compareBySuffix(), llvm::MCELFStreamer::EmitCommonSymbol(), llvm::MCELFStreamer::EmitIdent(), getMachOSection(), llvm::SystemZMCAsmInfo::getNonexecutableStackSection(), llvm::X86ELFMCAsmInfo::getNonexecutableStackSection(), llvm::XCoreTargetObjectFile::Initialize(), llvm::HexagonTargetObjectFile::Initialize(), llvm::MipsTargetObjectFile::Initialize(), llvm::MCObjectFileInfo::InitMCObjectFileInfo(), llvm::linkErlangGCPrinter(), and llvm::AMDGPUAsmPrinter::runOnMachineFunction().
const MCSectionELF * MCContext::getELFSection (StringRef Section, unsigned Type, unsigned Flags, SectionKind Kind, unsigned EntrySize, StringRef Group)
Definition at line 249 of file MCContext.cpp.
References llvm::MCSectionELF::DetermineEntrySize(), llvm::StringRef::empty(), and GetOrCreateSymbol().
unsigned llvm::MCContext::getGenDwarfFileNumber () inline
Definition at line 371 of file MCContext.h.
Referenced by llvm::MCGenDwarfLabelEntry::Make().
bool llvm::MCContext::getGenDwarfForAssembly () inline
Definition at line 369 of file MCContext.h.
const MCSection* llvm::MCContext::getGenDwarfSection () inline
Definition at line 373 of file MCContext.h.
Referenced by EmitGenDwarfAranges(), and llvm::MCGenDwarfLabelEntry::Make().
MCSymbol* llvm::MCContext::getGenDwarfSectionEndSym () inline
Definition at line 379 of file MCContext.h.
Referenced by EmitGenDwarfInfo().
MCSymbol* llvm::MCContext::getGenDwarfSectionStartSym () inline
Definition at line 375 of file MCContext.h.
Referenced by EmitGenDwarfAranges(), and EmitGenDwarfInfo().
const MCSectionMachO * MCContext::getMachOSection (StringRef Segment, StringRef Section, unsigned TypeAndAttributes, unsigned Reserved2, SectionKind K)
getMachOSection - Return the MCSection for the specified mach-o section. This requires the operands to be valid.
Definition at line 214 of file MCContext.cpp.
References getELFSection(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::ARMBuildAttrs::Section, and llvm::SmallString< InternalLen >::str().
Referenced by llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::ARMAsmPrinter::EmitStartOfAsmFile(), getMachOSection(), getSymbols(), llvm::MCObjectFileInfo::InitMCObjectFileInfo(), and LookupSymbol().
const MCSectionMachO* llvm::MCContext::getMachOSection (StringRef Segment, StringRef Section, unsigned TypeAndAttributes, SectionKind K) inline
Definition at line 243 of file MCContext.h.
References Characteristics, CreateELFGroupSection(), getCOFFSection(), getELFSection(), and getMachOSection().
const std::string& llvm::MCContext::getMainFileName () const inline
Get the main file name for use in error messages and debug info. This can be set to ensure we've got the correct file name after preprocessing or for -save-temps.
Definition at line 290 of file MCContext.h.
const SmallVectorImpl<StringRef>& llvm::MCContext::getMCDwarfDirs (unsigned CUID = 0) inline
Definition at line 314 of file MCContext.h.
Referenced by llvm::MCDwarfFileTable::EmitCU(), and EmitGenDwarfInfo().
const SmallVectorImpl<MCDwarfFile *>& llvm::MCContext::getMCDwarfFiles (unsigned CUID = 0) inline
Definition at line 311 of file MCContext.h.
Referenced by llvm::MCDwarfFileTable::EmitCU(), and EmitGenDwarfInfo().
const std::vector<const MCGenDwarfLabelEntry *>& llvm::MCContext::getMCGenDwarfLabelEntries () const inline
Definition at line 384 of file MCContext.h.
Referenced by EmitGenDwarfInfo().
const std::vector<const MCSection *>& llvm::MCContext::getMCLineSectionOrder () const inline
Definition at line 322 of file MCContext.h.
Referenced by llvm::MCDwarfFileTable::EmitCU().
const DenseMap<const MCSection *, MCLineSection *>& llvm::MCContext::getMCLineSections () const inline
Definition at line 319 of file MCContext.h.
Referenced by llvm::MCDwarfFileTable::Emit(), llvm::MCGenDwarfInfo::Emit(), llvm::MCDwarfFileTable::EmitCU(), and llvm::MCLineEntry::Make().
MCSymbol* llvm::MCContext::getMCLineTableSymbol (unsigned ID) const inline
Definition at line 338 of file MCContext.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), and llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::find().
Referenced by llvm::MCDwarfFileTable::EmitCU().
const DenseMap<unsigned, MCSymbol *>& llvm::MCContext::getMCLineTableSymbols () const inline
Definition at line 335 of file MCContext.h.
Referenced by llvm::MCDwarfFileTable::Emit().
const MCObjectFileInfo* llvm::MCContext::getObjectFileInfo () const inline
Definition at line 179 of file MCContext.h.
Referenced by llvm::MCDwarfFileTable::Emit(), llvm::MCGenDwarfInfo::Emit(), llvm::MCDwarfFrameEmitter::Emit(), EmitDwarfLineTable(), EmitEncodingByte(), EmitGenDwarfAbbrev(), EmitGenDwarfAranges(), EmitGenDwarfInfo(), llvm::getWin64EHFuncTableSection(), llvm::getWin64EHTableSection(), getWin64EHTableSection(), and llvm::StackMaps::serializeToStackMapSection().
MCSymbol * MCContext::GetOrCreateSymbol (StringRef Name)
GetOrCreateSymbol - Lookup the symbol inside with the specified Name. If it exists, return it. If not, create a forward reference and return it.
Parameters
Name - The symbol name, which must be unique across all symbols.
Definition at line 117 of file MCContext.cpp.
References llvm::StringRef::empty(), llvm::StringMapEntry< ValueTy >::getKey(), llvm::StringMap< ValueTy, AllocatorTy >::GetOrCreateValue(), llvm::MCAsmInfo::getPrivateGlobalPrefix(), llvm::StringMapEntry< ValueTy >::getValue(), llvm::SmallVectorImpl< T >::resize(), llvm::StringMapEntry< ValueTy >::setValue(), llvm::StringRef::size(), and llvm::StringRef::startswith().
Referenced by CreateDirectionalLocalSymbol(), EmitCamlGlobal(), EmitEncodingByte(), llvm::X86AsmPrinter::EmitEndOfAsmFile(), llvm::DwarfException::EmitExceptionTable(), llvm::AsmPrinter::EmitGlobalVariable(), llvm::ARMAsmPrinter::EmitMachineConstantPoolValue(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), llvm::X86AsmPrinter::EmitStartOfAsmFile(), GetAnonSym(), getCOFFSection(), llvm::MSP430MCInstLower::GetConstantPoolIndexSymbol(), llvm::AsmPrinter::GetCPISymbol(), GetDirectionalLocalSymbol(), getELFSection(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::MachineFunction::getJTISymbol(), llvm::AsmPrinter::GetJTSetSymbol(), llvm::MSP430MCInstLower::GetJumpTableSymbol(), GetLazyPtr(), GetOrCreateSymbol(), getPICLabel(), llvm::TargetLoweringObjectFile::getSymbol(), llvm::MachineBasicBlock::getSymbol(), GetSymbolFromOperand(), llvm::AsmPrinter::GetSymbolWithGlobalValueBase(), llvm::AsmPrinter::GetTempSymbol(), getUniqueSymbolID(), LowerTlsAddr(), llvm::ARMAsmPrinter::printOperand(), llvm::X86AsmPrinter::printSymbolOperand(), llvm::StackMaps::serializeToStackMapSection(), llvm::MCExternalSymbolizer::tryAddingSymbolicOperand(), and llvm::MCObjectSymbolizer::tryAddingSymbolicOperand().
MCSymbol * MCContext::GetOrCreateSymbol (const Twine & Name)
Definition at line 158 of file MCContext.cpp.
References GetOrCreateSymbol(), llvm::SmallString< InternalLen >::str(), and llvm::Twine::toVector().
const MCRegisterInfo* llvm::MCContext::getRegisterInfo () const inline
Definition at line 177 of file MCContext.h.
Referenced by llvm::X86FrameLowering::emitCalleeSavedFrameMoves(), EmitEncodingByte(), llvm::Mips16FrameLowering::emitPrologue(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::XCoreFrameLowering::emitPrologue(), llvm::SparcFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::AArch64FrameLowering::emitPrologue(), llvm::SystemZFrameLowering::emitPrologue(), and llvm::StackMaps::serializeToStackMapSection().
raw_ostream* llvm::MCContext::getSecureLog () inline
Definition at line 400 of file MCContext.h.
char* llvm::MCContext::getSecureLogFile () inline
Definition at line 399 of file MCContext.h.
bool llvm::MCContext::getSecureLogUsed () inline
Definition at line 401 of file MCContext.h.
const SourceMgr* llvm::MCContext::getSourceManager () const inline
Definition at line 173 of file MCContext.h.
const SymbolTable& llvm::MCContext::getSymbols () const inline
getSymbols - Get a reference for the symbol table for clients that want to, for example, iterate over all symbols. 'const' because we still want any modifications to the table itself to use the MCContext APIs.
Definition at line 227 of file MCContext.h.
References getMachOSection(), and llvm::ARMBuildAttrs::Section.
unsigned llvm::MCContext::getUniqueSymbolID () inline
getUniqueSymbolID() - Return a unique identifier for use in constructing symbol names.
Definition at line 201 of file MCContext.h.
References CreateDirectionalLocalSymbol(), GetDirectionalLocalSymbol(), GetOrCreateSymbol(), and LookupSymbol().
bool llvm::MCContext::hasDwarfFiles () const inline
Definition at line 301 of file MCContext.h.
bool MCContext::isValidDwarfFileNumber (unsigned FileNumber, unsigned CUID = 0)
isValidDwarfFileNumber - takes a dwarf file number and returns true if it currently is assigned and false otherwise.
Definition at line 404 of file MCContext.cpp.
References llvm::SmallVectorTemplateCommon< T >::size().
Referenced by setMainFileName().
MCSymbol * MCContext::LookupSymbol (StringRef Name) const
LookupSymbol - Get the symbol for Name, or null.
Definition at line 199 of file MCContext.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::lookup().
Referenced by getUniqueSymbolID(), and LookupSymbol().
MCSymbol * MCContext::LookupSymbol (const Twine & Name) const
Definition at line 203 of file MCContext.cpp.
References getMachOSection(), LookupSymbol(), llvm::SmallString< InternalLen >::str(), and llvm::Twine::toVector().
unsigned llvm::MCContext::nextGenDwarfFileNumber () inline
Definition at line 372 of file MCContext.h.
void MCContext::reset ()
reset - return object to right after construction state to prepare to process a new module
Definition at line 83 of file MCContext.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::clear(), DWARF2_FLAG_IS_STMT, and llvm::BumpPtrAllocator::Reset().
Referenced by llvm::MachineModuleInfo::doFinalization(), setAllowTemporaryLabels(), and ~MCContext().
void llvm::MCContext::setAllowTemporaryLabels (bool Value) inline
Definition at line 181 of file MCContext.h.
References CreateTempSymbol(), and reset().
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile(), and llvm::LLVMTargetMachine::addPassesToEmitMC().
void llvm::MCContext::setCompilationDir (StringRef S) inline
Set the compilation directory for DW_AT_comp_dir Override the default (CWD) compilation directory.
Definition at line 285 of file MCContext.h.
References llvm::StringRef::str().
void llvm::MCContext::setCurrentDwarfLoc (unsigned FileNum, unsigned Line, unsigned Column, unsigned Flags, unsigned Isa, unsigned Discriminator) inline
setCurrentDwarfLoc - saves the information from the currently parsed dwarf .loc directive and sets DwarfLocSeen. When the next instruction is assembled an entry in the line number table with this information and the address of the instruction will be created.
Definition at line 353 of file MCContext.h.
References llvm::MCDwarfLoc::setColumn(), llvm::MCDwarfLoc::setDiscriminator(), llvm::MCDwarfLoc::setFileNum(), llvm::MCDwarfLoc::setFlags(), llvm::MCDwarfLoc::setIsa(), and llvm::MCDwarfLoc::setLine().
Referenced by llvm::MCStreamer::EmitDwarfLocDirective().
void llvm::MCContext::setDwarfCompileUnitID (unsigned CUIndex) inline
Definition at line 332 of file MCContext.h.
Referenced by llvm::DwarfDebug::beginFunction(), and llvm::DwarfDebug::endFunction().
void llvm::MCContext::setDwarfDebugFlags (StringRef S) inline
Definition at line 391 of file MCContext.h.
References S.
void llvm::MCContext::setDwarfDebugProducer (StringRef S) inline
Definition at line 394 of file MCContext.h.
References S.
void llvm::MCContext::setGenDwarfForAssembly (bool Value) inline
Definition at line 370 of file MCContext.h.
void llvm::MCContext::setGenDwarfSection (const MCSection * Sec) inline
Definition at line 374 of file MCContext.h.
void llvm::MCContext::setGenDwarfSectionEndSym (MCSymbol * Sym) inline
Definition at line 380 of file MCContext.h.
Referenced by EmitGenDwarfAranges().
void llvm::MCContext::setGenDwarfSectionStartSym (MCSymbol * Sym) inline
Definition at line 376 of file MCContext.h.
void llvm::MCContext::setMainFileName (StringRef S) inline
Set the main file name and override the default.
Definition at line 293 of file MCContext.h.
References GetDwarfFile(), isValidDwarfFileNumber(), and llvm::StringRef::str().
void llvm::MCContext::setMCLineTableSymbol (MCSymbol * Sym, unsigned ID) inline
Definition at line 345 of file MCContext.h.
Referenced by llvm::DwarfDebug::getOrCreateSourceID().
void llvm::MCContext::setSecureLog (raw_ostream * Value) inline
Definition at line 402 of file MCContext.h.
void llvm::MCContext::setSecureLogUsed (bool Value) inline
Definition at line 405 of file MCContext.h.
The documentation for this class was generated from the following files:
MCContext.h
MCContext.cpp