LLVM: llvm::GCMetadataPrinter Class Reference
LLVM API Documentation
llvm::GCMetadataPrinter Class Reference
#include <GCMetadataPrinter.h>
Public Types
typedef GCStrategy::list_type list_type
typedef GCStrategy::iterator iterator
Public Member Functions
GCStrategy & getStrategy ()
const Module & getModule () const
iterator begin ()
begin/end - Iterate over the collected function metadata.
iterator end ()
virtual void beginAssembly (AsmPrinter &AP)
beginAssembly/finishAssembly - Emit module metadata as assembly code.
virtual void finishAssembly (AsmPrinter &AP)
virtual ~GCMetadataPrinter ()
Protected Member Functions
GCMetadataPrinter ()
Friends
class AsmPrinter
Detailed Description
GCMetadataPrinter - Emits GC metadata as assembly code.
Definition at line 37 of file GCMetadataPrinter.h.
Member Typedef Documentation
typedef GCStrategy::iterator llvm::GCMetadataPrinter::iterator
Definition at line 40 of file GCMetadataPrinter.h.
typedef GCStrategy::list_type llvm::GCMetadataPrinter::list_type
Definition at line 39 of file GCMetadataPrinter.h.
Constructor & Destructor Documentation
GCMetadataPrinter::GCMetadataPrinter () protected
Definition at line 17 of file GCMetadataPrinter.cpp.
GCMetadataPrinter::~GCMetadataPrinter () virtual
Definition at line 19 of file GCMetadataPrinter.cpp.
Referenced by end().
Member Function Documentation
iterator llvm::GCMetadataPrinter::begin () inline
begin/end - Iterate over the collected function metadata.
Definition at line 61 of file GCMetadataPrinter.h.
References llvm::GCStrategy::begin().
void GCMetadataPrinter::beginAssembly (AsmPrinter & AP) virtual
beginAssembly/finishAssembly - Emit module metadata as assembly code.
Definition at line 21 of file GCMetadataPrinter.cpp.
Referenced by end().
iterator llvm::GCMetadataPrinter::end () inline
Definition at line 62 of file GCMetadataPrinter.h.
References beginAssembly(), llvm::GCStrategy::end(), finishAssembly(), and ~GCMetadataPrinter().
void GCMetadataPrinter::finishAssembly (AsmPrinter & AP) virtual
Definition at line 25 of file GCMetadataPrinter.cpp.
Referenced by end().
const Module& llvm::GCMetadataPrinter::getModule () const inline
Definition at line 58 of file GCMetadataPrinter.h.
References llvm::GCStrategy::getModule().
GCStrategy& llvm::GCMetadataPrinter::getStrategy () inline
Definition at line 57 of file GCMetadataPrinter.h.
References S.
Friends And Related Function Documentation
friend class AsmPrinter friend
Definition at line 45 of file GCMetadataPrinter.h.
The documentation for this class was generated from the following files:
GCMetadataPrinter.h
GCMetadataPrinter.cpp