LLVM: llvm::DWARFAbbreviationDeclarationSet Class Reference
LLVM API Documentation
llvm::DWARFAbbreviationDeclarationSet Class Reference
#include <DWARFDebugAbbrev.h>
Public Member Functions
DWARFAbbreviationDeclarationSet ()
DWARFAbbreviationDeclarationSet (uint32_t offset, uint32_t idxOffset)
void clear ()
uint32_t getOffset () const
void dump (raw_ostream &OS) const
bool extract (DataExtractor data, uint32_t *offset_ptr)
const DWARFAbbreviationDeclaration * getAbbreviationDeclaration (uint32_t abbrCode) const
Detailed Description
Definition at line 27 of file DWARFDebugAbbrev.h.
Constructor & Destructor Documentation
llvm::DWARFAbbreviationDeclarationSet::DWARFAbbreviationDeclarationSet () inline
Definition at line 32 of file DWARFDebugAbbrev.h.
llvm::DWARFAbbreviationDeclarationSet::DWARFAbbreviationDeclarationSet (uint32_t offset, uint32_t idxOffset) inline
Definition at line 35 of file DWARFDebugAbbrev.h.
Member Function Documentation
void llvm::DWARFAbbreviationDeclarationSet::clear () inline
Definition at line 38 of file DWARFDebugAbbrev.h.
Referenced by extract().
void DWARFAbbreviationDeclarationSet::dump (raw_ostream & OS) const
Definition at line 35 of file DWARFDebugAbbrev.cpp.
References i.
Referenced by getOffset().
bool DWARFAbbreviationDeclarationSet::extract (DataExtractor data, uint32_t * offset_ptr)
Definition at line 15 of file DWARFDebugAbbrev.cpp.
References clear(), llvm::DWARFAbbreviationDeclaration::extract(), and llvm::DWARFAbbreviationDeclaration::getCode().
Referenced by getOffset(), and llvm::DWARFDebugAbbrev::parse().
const DWARFAbbreviationDeclaration * DWARFAbbreviationDeclarationSet::getAbbreviationDeclaration (uint32_t abbrCode) const
Definition at line 41 of file DWARFDebugAbbrev.cpp.
References llvm::sys::path::end().
Referenced by llvm::DWARFDebugInfoEntryMinimal::extractFast(), and getOffset().
uint32_t llvm::DWARFAbbreviationDeclarationSet::getOffset () const inline
Definition at line 42 of file DWARFDebugAbbrev.h.
References dump(), extract(), and getAbbreviationDeclaration().
The documentation for this class was generated from the following files:
DWARFDebugAbbrev.h
DWARFDebugAbbrev.cpp