LLVM: llvm::BitsRecTy Class Reference
LLVM API Documentation
llvm::BitsRecTy Class Reference
#include <Record.h>
Public Member Functions
unsigned getNumBits () const
virtual Init * convertValue (UnsetInit *UI)
virtual Init * convertValue (BitInit *UI)
virtual Init * convertValue (BitsInit *BI)
virtual Init * convertValue (IntInit *II)
virtual Init * convertValue (StringInit *SI)
virtual Init * convertValue (ListInit *LI)
virtual Init * convertValue (VarBitInit *VB)
virtual Init * convertValue (DefInit *DI)
virtual Init * convertValue (DagInit *DI)
virtual Init * convertValue (UnOpInit *UI)
virtual Init * convertValue (BinOpInit *UI)
virtual Init * convertValue (TernOpInit *UI)
virtual Init * convertValue (TypedInit *TI)
virtual Init * convertValue (VarInit *VI)
virtual Init * convertValue (FieldInit *FI)
virtual std::string getAsString () const
virtual bool typeIsConvertibleTo (const RecTy *RHS) const
virtual bool baseClassOf (const RecTy *) const
Public Member Functions inherited from llvm::RecTy
RecTyKind getRecTyKind () const
RecTy (RecTyKind K)
virtual ~RecTy ()
void print (raw_ostream &OS) const
void dump () const
ListRecTy * getListTy ()
getListTy - Returns the type representing list<this>.
Static Public Member Functions
static bool classof (const RecTy *RT)
static BitsRecTy * get (unsigned Sz)
Additional Inherited Members
Public Types inherited from llvm::RecTy
enum RecTyKind {
BitRecTyKind, BitsRecTyKind, IntRecTyKind, StringRecTyKind,
ListRecTyKind, DagRecTyKind, RecordRecTyKind
}
Subclass discriminator (for dyn_cast<> et al.)
Detailed Description
BitsRecTy - 'bits<n>' - Represent a fixed number of bits
Definition at line 180 of file Record.h.
Member Function Documentation
bool BitsRecTy::baseClassOf (const RecTy * RHS) const virtual
Reimplemented from llvm::RecTy.
Definition at line 205 of file Record.cpp.
References llvm::RecTy::baseClassOf(), and llvm::RecTy::getRecTyKind().
static bool llvm::BitsRecTy::classof (const RecTy * RT) inline static
Definition at line 184 of file Record.h.
References llvm::RecTy::BitsRecTyKind, and llvm::RecTy::getRecTyKind().
Init * BitsRecTy::convertValue (UnsetInit * UI) virtual
Reimplemented from llvm::RecTy.
Definition at line 144 of file Record.cpp.
References llvm::UnsetInit::get(), llvm::BitsInit::get(), and i.
Init * BitsRecTy::convertValue (BitInit * UI) virtual
Reimplemented from llvm::RecTy.
Definition at line 153 of file Record.cpp.
References llvm::BitsInit::get().
Init * BitsRecTy::convertValue (BitsInit * BI) virtual
Reimplemented from llvm::RecTy.
Definition at line 183 of file Record.cpp.
References llvm::BitsInit::getNumBits().
Init * BitsRecTy::convertValue (IntInit * II) virtual
convertValue from Int initializer to bits type: Split the integer up into the appropriate bits.
Reimplemented from llvm::RecTy.
Definition at line 169 of file Record.cpp.
References canFitInBitfield(), llvm::BitInit::get(), llvm::BitsInit::get(), llvm::IntInit::getValue(), and i.
virtual Init* llvm::BitsRecTy::convertValue (StringInit * SI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 196 of file Record.h.
virtual Init* llvm::BitsRecTy::convertValue (ListInit * LI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 197 of file Record.h.
virtual Init* llvm::BitsRecTy::convertValue (VarBitInit * VB) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 198 of file Record.h.
virtual Init* llvm::BitsRecTy::convertValue (DefInit * DI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 199 of file Record.h.
virtual Init* llvm::BitsRecTy::convertValue (DagInit * DI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 200 of file Record.h.
virtual Init* llvm::BitsRecTy::convertValue (UnOpInit * UI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 201 of file Record.h.
References llvm::RecTy::convertValue().
virtual Init* llvm::BitsRecTy::convertValue (BinOpInit * UI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 202 of file Record.h.
References llvm::RecTy::convertValue().
virtual Init* llvm::BitsRecTy::convertValue (TernOpInit * UI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 203 of file Record.h.
References llvm::RecTy::convertValue().
Init * BitsRecTy::convertValue (TypedInit * TI) virtual
Reimplemented from llvm::RecTy.
Definition at line 190 of file Record.cpp.
References llvm::BitsInit::get(), llvm::VarBitInit::get(), llvm::TypedInit::getType(), i, and llvm::RecTy::typeIsConvertibleTo().
virtual Init* llvm::BitsRecTy::convertValue (VarInit * VI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 205 of file Record.h.
References llvm::RecTy::convertValue().
virtual Init* llvm::BitsRecTy::convertValue (FieldInit * FI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 206 of file Record.h.
References llvm::RecTy::convertValue(), and llvm::RecTy::getAsString().
BitsRecTy * BitsRecTy::get (unsigned Sz) static
Definition at line 130 of file Record.cpp.
Referenced by llvm::SubMultiClassReference::dump(), and GetNewAnonymousName().
std::string BitsRecTy::getAsString () const virtual
Implements llvm::RecTy.
Definition at line 140 of file Record.cpp.
References llvm::utostr().
unsigned llvm::BitsRecTy::getNumBits () const inline
Definition at line 190 of file Record.h.
References llvm::RecTy::convertValue().
Referenced by llvm::TypedInit::convertInitializerBitRange().
virtual bool llvm::BitsRecTy::typeIsConvertibleTo (const RecTy * RHS) const inline virtual
typeIsConvertibleTo - Return true if all values of 'this' type can be converted to the specified type.
Implements llvm::RecTy.
Definition at line 210 of file Record.h.
References llvm::RecTy::baseClassOf().
The documentation for this class was generated from the following files:
Record.h
Record.cpp