LLVM: llvm::MSP430InstrInfo Class Reference
LLVM API Documentation
llvm::MSP430InstrInfo Class Reference
#include <MSP430InstrInfo.h>
Public Member Functions
MSP430InstrInfo (MSP430TargetMachine &TM)
virtual const TargetRegisterInfo & getRegisterInfo () const
void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const
virtual void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const
virtual void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned DestReg, int FrameIdx, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const
unsigned GetInstSizeInBytes (const MachineInstr *MI) const
bool ReverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const
bool isUnpredicatedTerminator (const MachineInstr *MI) const
bool AnalyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify) const
unsigned RemoveBranch (MachineBasicBlock &MBB) const
unsigned InsertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, const SmallVectorImpl< MachineOperand > &Cond, DebugLoc DL) const
Detailed Description
Definition at line 43 of file MSP430InstrInfo.h.
Constructor & Destructor Documentation
MSP430InstrInfo::MSP430InstrInfo (MSP430TargetMachine & TM) explicit
Definition at line 33 of file MSP430InstrInfo.cpp.
Member Function Documentation
bool MSP430InstrInfo::AnalyzeBranch (MachineBasicBlock & MBB, MachineBasicBlock *& TBB, MachineBasicBlock *& FBB, SmallVectorImpl< MachineOperand > & Cond, bool AllowModify) const
Definition at line 172 of file MSP430InstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::SmallVectorImpl< T >::clear(), MSP430CC::COND_INVALID, llvm::MachineOperand::CreateImm(), llvm::SmallVectorBase::empty(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::eraseFromParent(), I, llvm::MachineBasicBlock::isLayoutSuccessor(), isUnpredicatedTerminator(), llvm::next(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), and llvm::SmallVectorTemplateCommon< T >::size().
void MSP430InstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const
Definition at line 91 of file MSP430InstrInfo.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::getKillRegState(), and llvm_unreachable.
unsigned MSP430InstrInfo::GetInstSizeInBytes (const MachineInstr * MI) const
GetInstSize - Return the number of bytes of code the specified instruction may be. This returns the maximum number of bytes.
Definition at line 295 of file MSP430InstrInfo.cpp.
References llvm::TargetOpcode::DBG_VALUE, llvm::TargetOpcode::EH_LABEL, llvm::MachineInstr::getDesc(), llvm::TargetInstrInfo::getInlineAsmLength(), llvm::TargetMachine::getInstrInfo(), llvm::TargetMachine::getMCAsmInfo(), llvm::MCInstrDesc::getOpcode(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getSymbolName(), llvm::MachineFunction::getTarget(), llvm::TargetOpcode::IMPLICIT_DEF, llvm::TargetOpcode::INLINEASM, llvm::TargetOpcode::KILL, llvm_unreachable, llvm::TargetOpcode::PROLOG_LABEL, llvm::MSP430II::Size2Bytes, llvm::MSP430II::Size4Bytes, llvm::MSP430II::Size6Bytes, llvm::MSP430II::SizeMask, llvm::MSP430II::SizeSpecial, TII, and llvm::MCInstrDesc::TSFlags.
Referenced by llvm::createMSP430BranchSelectionPass().
virtual const TargetRegisterInfo& llvm::MSP430InstrInfo::getRegisterInfo () const inline virtual
getRegisterInfo - TargetInstrInfo is a superset of MRegister info. As such, whenever a client has an instance of instruction info, it should always be able to get register info as well (through this method).
Definition at line 53 of file MSP430InstrInfo.h.
References llvm::ISD::FrameIndex, I, and llvm::A64CC::MI.
Referenced by llvm::MSP430TargetMachine::getRegisterInfo().
unsigned MSP430InstrInfo::InsertBranch (MachineBasicBlock & MBB, MachineBasicBlock * TBB, MachineBasicBlock * FBB, const SmallVectorImpl< MachineOperand > & Cond, DebugLoc DL) const
Definition at line 263 of file MSP430InstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::BuildMI(), llvm::SmallVectorBase::empty(), and llvm::SmallVectorTemplateCommon< T >::size().
bool MSP430InstrInfo::isUnpredicatedTerminator (const MachineInstr * MI) const
Definition at line 161 of file MSP430InstrInfo.cpp.
References llvm::MachineInstr::isBarrier(), llvm::MachineInstr::isBranch(), llvm::MachineInstr::isPredicable(), and llvm::MachineInstr::isTerminator().
Referenced by AnalyzeBranch().
void MSP430InstrInfo::loadRegFromStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, unsigned DestReg, int FrameIdx, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const virtual
Definition at line 65 of file MSP430InstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), llvm_unreachable, and llvm::MachineMemOperand::MOLoad.
unsigned MSP430InstrInfo::RemoveBranch (MachineBasicBlock & MBB) const
Definition at line 107 of file MSP430InstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), I, and ReverseBranchCondition().
bool MSP430InstrInfo::ReverseBranchCondition (SmallVectorImpl< MachineOperand > & Cond) const
Definition at line 130 of file MSP430InstrInfo.cpp.
References CC, MSP430CC::COND_E, MSP430CC::COND_GE, MSP430CC::COND_HS, MSP430CC::COND_L, MSP430CC::COND_LO, MSP430CC::COND_NE, llvm_unreachable, and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by llvm::createMSP430BranchSelectionPass(), and RemoveBranch().
void MSP430InstrInfo::storeRegToStackSlot (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI) const virtual
Definition at line 37 of file MSP430InstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::getKillRegState(), llvm::MachineFunction::getMachineMemOperand(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineBasicBlock::getParent(), llvm_unreachable, and llvm::MachineMemOperand::MOStore.
The documentation for this class was generated from the following files:
MSP430InstrInfo.h
MSP430InstrInfo.cpp