LLVM: llvm::VirtRegAuxInfo Class Reference
LLVM API Documentation
llvm::VirtRegAuxInfo Class Reference
Calculate auxiliary information for a virtual register such as its spill weight and allocation hint.
#include <CalcSpillWeights.h>
Public Types
typedef float(* NormalizingFn) (float, unsigned)
Public Member Functions
VirtRegAuxInfo (MachineFunction &mf, LiveIntervals &lis, const MachineLoopInfo &loops, const MachineBlockFrequencyInfo &mbfi, NormalizingFn norm=normalizeSpillWeight)
void calculateSpillWeightAndHint (LiveInterval &li)
(re)compute li's spill weight and allocation hint.
Detailed Description
Calculate auxiliary information for a virtual register such as its spill weight and allocation hint.
Definition at line 45 of file CalcSpillWeights.h.
Member Typedef Documentation
typedef float(* llvm::VirtRegAuxInfo::NormalizingFn) (float, unsigned)
Definition at line 47 of file CalcSpillWeights.h.
Constructor & Destructor Documentation
llvm::VirtRegAuxInfo::VirtRegAuxInfo (MachineFunction & mf, LiveIntervals & lis, const MachineLoopInfo & loops, const MachineBlockFrequencyInfo & mbfi, NormalizingFn norm = normalizeSpillWeight) inline
Definition at line 58 of file CalcSpillWeights.h.
References calculateSpillWeightAndHint(), llvm::calculateSpillWeightsAndHints(), norm(), and llvm::normalizeSpillWeight().
Member Function Documentation
void VirtRegAuxInfo::calculateSpillWeightAndHint (LiveInterval & li)
(re)compute li's spill weight and allocation hint.
Definition at line 96 of file CalcSpillWeights.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::clear(), copyHint(), llvm::MachineBlockFrequencyInfo::getBlockFreq(), llvm::TargetMachine::getInstrInfo(), llvm::MachineLoopInfo::getLoopFor(), llvm::MachineInstr::getParent(), llvm::MachineRegisterInfo::getRegAllocationHint(), llvm::MachineFunction::getRegInfo(), llvm::TargetMachine::getRegisterInfo(), llvm::LiveInterval::getSize(), llvm::LiveIntervals::getSlotIndexes(), llvm::LiveIntervals::getSpillWeight(), llvm::MachineFunction::getTarget(), I, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::MachineRegisterInfo::isAllocatable(), llvm::MachineInstr::isCopy(), llvm::MachineInstr::isDebugValue(), llvm::MachineInstr::isIdentityCopy(), llvm::MachineInstr::isImplicitDef(), llvm::LiveIntervals::isLiveOutOfMBB(), llvm::LoopBase< BlockT, LoopT >::isLoopExiting(), llvm::TargetRegisterInfo::isPhysicalRegister(), isRematerializable(), llvm::LiveInterval::isSpillable(), llvm::LiveRange::isZeroLength(), loop, llvm::LiveInterval::markNotSpillable(), llvm::MachineInstr::readsWritesVirtualRegister(), llvm::LiveInterval::reg, llvm::MachineRegisterInfo::reg_begin(), llvm::MachineRegisterInfo::setRegAllocationHint(), llvm::tie(), and llvm::LiveInterval::weight.
Referenced by llvm::LiveRangeEdit::calculateRegClassAndHint(), llvm::calculateSpillWeightsAndHints(), and VirtRegAuxInfo().
The documentation for this class was generated from the following files:
CalcSpillWeights.h
CalcSpillWeights.cpp