LLVM: llvm::AssemblyAnnotationWriter Class Reference
LLVM API Documentation
llvm::AssemblyAnnotationWriter Class Reference
#include <AssemblyAnnotationWriter.h>
Public Member Functions
virtual ~AssemblyAnnotationWriter ()
virtual void emitFunctionAnnot (const Function *, formatted_raw_ostream &)
virtual void emitBasicBlockStartAnnot (const BasicBlock *, formatted_raw_ostream &)
virtual void emitBasicBlockEndAnnot (const BasicBlock *, formatted_raw_ostream &)
virtual void emitInstructionAnnot (const Instruction *, formatted_raw_ostream &)
virtual void printInfoComment (const Value &, formatted_raw_ostream &)
Detailed Description
Definition at line 28 of file AssemblyAnnotationWriter.h.
Constructor & Destructor Documentation
AssemblyAnnotationWriter::~AssemblyAnnotationWriter () virtual
Definition at line 49 of file AsmWriter.cpp.
Member Function Documentation
virtual void llvm::AssemblyAnnotationWriter::emitBasicBlockEndAnnot (const BasicBlock * , formatted_raw_ostream &) inline virtual
emitBasicBlockEndAnnot - This may be implemented to emit a string right after the basic block.
Definition at line 47 of file AssemblyAnnotationWriter.h.
Referenced by llvm::AssemblyWriter::printBasicBlock().
virtual void llvm::AssemblyAnnotationWriter::emitBasicBlockStartAnnot (const BasicBlock * , formatted_raw_ostream &) inline virtual
emitBasicBlockStartAnnot - This may be implemented to emit a string right after the basic block label, but before the first instruction in the block.
Definition at line 41 of file AssemblyAnnotationWriter.h.
Referenced by llvm::AssemblyWriter::printBasicBlock().
virtual void llvm::AssemblyAnnotationWriter::emitFunctionAnnot (const Function * , formatted_raw_ostream &) inline virtual
emitFunctionAnnot - This may be implemented to emit a string right before the start of a function.
Definition at line 35 of file AssemblyAnnotationWriter.h.
Referenced by llvm::AssemblyWriter::printFunction().
virtual void llvm::AssemblyAnnotationWriter::emitInstructionAnnot (const Instruction * , formatted_raw_ostream &) inline virtual
emitInstructionAnnot - This may be implemented to emit a string right before an instruction is emitted.
Definition at line 53 of file AssemblyAnnotationWriter.h.
Referenced by llvm::AssemblyWriter::printInstruction().
virtual void llvm::AssemblyAnnotationWriter::printInfoComment (const Value & , formatted_raw_ostream &) inline virtual
printInfoComment - This may be implemented to emit a comment to the right of an instruction or global value.
Definition at line 58 of file AssemblyAnnotationWriter.h.
Referenced by llvm::AssemblyWriter::printInstructionLine().
The documentation for this class was generated from the following files:
AssemblyAnnotationWriter.h
AsmWriter.cpp