LLVM: llvm::BranchProbability Class Reference
LLVM API Documentation
llvm::BranchProbability Class Reference
#include <BranchProbability.h>
Public Member Functions
BranchProbability (uint32_t n, uint32_t d)
uint32_t getNumerator () const
uint32_t getDenominator () const
BranchProbability getCompl () const
void print (raw_ostream &OS) const
void dump () const
bool operator== (BranchProbability RHS) const
bool operator!= (BranchProbability RHS) const
bool operator< (BranchProbability RHS) const
bool operator> (BranchProbability RHS) const
bool operator<= (BranchProbability RHS) const
bool operator>= (BranchProbability RHS) const
Static Public Member Functions
static BranchProbability getZero ()
static BranchProbability getOne ()
Detailed Description
Definition at line 25 of file BranchProbability.h.
Constructor & Destructor Documentation
llvm::BranchProbability::BranchProbability (uint32_t n, uint32_t d) inline
Definition at line 33 of file BranchProbability.h.
Referenced by getCompl(), getOne(), and getZero().
Member Function Documentation
void BranchProbability::dump () const
Definition at line 25 of file BranchProbability.cpp.
References llvm::dbgs().
Referenced by getCompl().
BranchProbability llvm::BranchProbability::getCompl () const inline
Definition at line 45 of file BranchProbability.h.
References BranchProbability(), dump(), and print().
Referenced by getBlockNum(), and getNextBlock().
uint32_t llvm::BranchProbability::getDenominator () const inline
Definition at line 42 of file BranchProbability.h.
Referenced by llvm::ARMBaseInstrInfo::isProfitableToIfCvt(), llvm::BlockFrequency::operator*=(), llvm::BlockFrequency::operator/=(), and llvm::BlockFrequency::scale().
uint32_t llvm::BranchProbability::getNumerator () const inline
Definition at line 41 of file BranchProbability.h.
Referenced by llvm::ARMBaseInstrInfo::isProfitableToIfCvt(), llvm::BlockFrequency::operator*=(), llvm::BlockFrequency::operator/=(), and llvm::BlockFrequency::scale().
static BranchProbability llvm::BranchProbability::getOne () inline static
Definition at line 39 of file BranchProbability.h.
References BranchProbability().
static BranchProbability llvm::BranchProbability::getZero () inline static
Definition at line 38 of file BranchProbability.h.
References BranchProbability().
bool llvm::BranchProbability::operator!= (BranchProbability RHS) const inline
Definition at line 56 of file BranchProbability.h.
bool llvm::BranchProbability::operator< (BranchProbability RHS) const inline
Definition at line 59 of file BranchProbability.h.
bool llvm::BranchProbability::operator<= (BranchProbability RHS) const inline
Definition at line 65 of file BranchProbability.h.
bool llvm::BranchProbability::operator== (BranchProbability RHS) const inline
Definition at line 53 of file BranchProbability.h.
bool llvm::BranchProbability::operator> (BranchProbability RHS) const inline
Definition at line 62 of file BranchProbability.h.
bool llvm::BranchProbability::operator>= (BranchProbability RHS) const inline
Definition at line 68 of file BranchProbability.h.
References llvm::operator<<().
void BranchProbability::print (raw_ostream & OS) const
Definition at line 21 of file BranchProbability.cpp.
References llvm::format().
Referenced by getCompl(), and llvm::operator<<().
The documentation for this class was generated from the following files:
BranchProbability.h
BranchProbability.cpp