LLVM: llvm::DwarfDebug Class Reference
LLVM API Documentation
llvm::DwarfDebug Class Reference
Collects and handles dwarf debug information.
#include <DwarfDebug.h>
Public Member Functions
DwarfDebug (AsmPrinter *A, Module *M)
void insertDIE (const MDNode *TypeMD, DIE *Die)
DIE * getDIE (const MDNode *TypeMD)
void beginModule ()
Emit all Dwarf sections that should come prior to the content.
void endModule ()
Emit all Dwarf sections that should come after the content.
void beginFunction (const MachineFunction *MF)
Gather pre-function debug information.
void endFunction (const MachineFunction *MF)
Gather and emit post-function debug information.
void beginInstruction (const MachineInstr *MI)
Process beginning of an instruction.
void endInstruction (const MachineInstr *MI)
Process end of an instruction.
void addTypeUnitType (DIE *Die)
Add a DIE to the set of types that we're going to pull into type units.
void addArangeLabel (SymbolCU SCU)
Add a label so that arange data can be generated for it.
void setSymbolSize (const MCSymbol *Sym, uint64_t Size)
For symbols that have a size designated (e.g. common symbols), this tracks that size.
unsigned getOrCreateSourceID (StringRef DirName, StringRef FullName, unsigned CUID)
Look up the source id with the given directory and source file names. If none currently exists, create a new id and insert it in the SourceIds map.
void emitDIE (DIE *Die, ArrayRef< DIEAbbrev * > Abbrevs)
Recursively Emits a debug information entry.
bool useDwarfAccelTables ()
Returns whether or not to emit tables that dwarf consumers can use to accelerate lookup.
bool useSplitDwarf ()
Returns whether or not to change the current debug info for the split dwarf proposal support.
unsigned getDwarfVersion () const
Returns the Dwarf Version.
template<typename T >
T resolve (DIRef< T > Ref) const
Find the MDNode for the given reference.
bool isSubprogramContext (const MDNode *Context)
Detailed Description
Collects and handles dwarf debug information.
Definition at line 313 of file DwarfDebug.h.
Constructor & Destructor Documentation
DwarfDebug::DwarfDebug (AsmPrinter * A, Module * M)
Definition at line 181 of file DwarfDebug.cpp.
References beginModule(), llvm::Reloc::Default, getDwarfVersionFromModule(), llvm::MachineModuleInfo::getModule(), llvm::AsmPrinter::getTargetTriple(), T, and llvm::TimePassesIsEnabled.
Member Function Documentation
void llvm::DwarfDebug::addArangeLabel (SymbolCU SCU) inline
Add a label so that arange data can be generated for it.
Definition at line 701 of file DwarfDebug.h.
Referenced by llvm::CompileUnit::addLabelAddress(), and llvm::CompileUnit::addOpAddress().
void llvm::DwarfDebug::addTypeUnitType (DIE * Die) inline
Add a DIE to the set of types that we're going to pull into type units.
Definition at line 698 of file DwarfDebug.h.
Referenced by shouldCreateTypeUnit().
void DwarfDebug::beginFunction (const MachineFunction * MF)
Gather pre-function debug information.
Definition at line 1592 of file DwarfDebug.cpp.
References llvm::SmallVectorTemplateCommon< T >::back(), llvm::MachineFunction::back(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::begin(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::MachineFunction::begin(), llvm::dbgs(), DEBUG, DWARF2_FLAG_IS_STMT, llvm::MCStreamer::EmitLabel(), llvm::SmallVectorBase::empty(), llvm::LexicalScopes::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::end(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::find(), llvm::MachineInstr::FrameSetup, llvm::DIVariable::getArgNumber(), llvm::DebugLoc::getCol(), llvm::Function::getContext(), llvm::MCStreamer::getContext(), llvm::DIVariable::getContext(), llvm::LexicalScopes::getCurrentFunctionScope(), llvm::MachineInstr::getDebugLoc(), llvm::getDISubprogram(), llvm::MachineInstr::getFlag(), getFnDebugLoc(), llvm::MachineFunction::getFunction(), llvm::AsmPrinter::getFunctionNumber(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::DebugLoc::getLine(), llvm::MachineInstr::getNumOperands(), llvm::MCRegisterInfo::getNumRegs(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::TargetMachine::getRegisterInfo(), llvm::DebugLoc::getScope(), llvm::LexicalScope::getScopeNode(), llvm::DIDescriptor::getTag(), llvm::AsmPrinter::GetTempSymbol(), llvm::CompileUnit::getUniqueID(), llvm::DbgVariable::getVariable(), llvm::MachineModuleInfo::hasDebugInfo(), llvm::TargetMachine::hasMCUseLoc(), llvm::MCStreamer::hasRawTextSupport(), i, I, llvm::ARM_PROC::IE, llvm::LexicalScopes::initialize(), llvm::SmallVectorImpl< T >::insert(), isDbgValueInDefinedReg(), llvm::MachineInstr::isDebugValue(), llvm::MachineInstr::isIdenticalTo(), llvm::MachineInstr::isLabel(), llvm::DebugLoc::isUnknown(), llvm::MCRegAliasIterator::isValid(), llvm::DIDescriptor::isVariable(), llvm::A64CC::LS, llvm::A64CC::MI, llvm::next(), llvm::MachineInstr::operands_begin(), llvm::MachineInstr::operands_end(), llvm::AsmPrinter::OutStreamer, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::pop_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::MCContext::setDwarfCompileUnitID(), llvm::SmallVectorTemplateCommon< T >::size(), and llvm::AsmPrinter::TM.
Referenced by llvm::AsmPrinter::EmitFunctionHeader().
void DwarfDebug::beginInstruction (const MachineInstr * MI)
Process beginning of an instruction.
Definition at line 1467 of file DwarfDebug.cpp.
References llvm::MCContext::CreateTempSymbol(), DWARF2_FLAG_IS_STMT, DWARF2_FLAG_PROLOGUE_END, llvm::MCStreamer::EmitLabel(), llvm::DebugLoc::getCol(), llvm::Function::getContext(), llvm::MachineModuleInfo::getContext(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFunction(), llvm::DebugLoc::getLine(), llvm::DebugLoc::getScope(), I, llvm::MachineInstr::isDebugValue(), llvm::DebugLoc::isUnknown(), llvm::AsmPrinter::MF, llvm::AsmPrinter::OutStreamer, and UnknownLocations.
Referenced by llvm::AsmPrinter::EmitFunctionBody().
void DwarfDebug::beginModule ()
Emit all Dwarf sections that should come prior to the content.
Definition at line 896 of file DwarfDebug.cpp.
References llvm::DIE::addChild(), llvm::CompileUnit::addUInt(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::CompileUnit::constructVariableDIE(), DisableDebugInfoPrinting, llvm::dwarf::DW_INL_inlined, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::generateDITypeIdentifierMap(), llvm::CompileUnit::getDIE(), llvm::DIArray::getElement(), llvm::MachineModuleInfo::getModule(), llvm::Module::getNamedMetadata(), llvm::DIArray::getNumElements(), llvm::NamedMDNode::getNumOperands(), llvm::AsmPrinter::getObjFileLowering(), llvm::NamedMDNode::getOperand(), llvm::MCObjectFileInfo::getTextSection(), llvm::DISubprogram::getVariables(), i, llvm::DISubprogram::isDefinition(), llvm::DIDescriptor::isSubprogram(), M, llvm::None, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::MachineModuleInfo::setDebugInfoAvailability().
Referenced by DwarfDebug().
void DwarfDebug::emitDIE (DIE * Die, ArrayRef< DIEAbbrev * > Abbrevs)
Recursively Emits a debug information entry.
Definition at line 2041 of file DwarfDebug.cpp.
References llvm::dwarf::AccessibilityString(), llvm::MCStreamer::AddComment(), llvm::dwarf::AttributeString(), llvm::MCAsmInfo::doesDwarfUseRelocationsAcrossSections(), llvm::dwarf::DW_CHILDREN_yes, llvm::AsmPrinter::EmitInt32(), llvm::AsmPrinter::EmitInt8(), llvm::AsmPrinter::EmitLabelDifference(), llvm::AsmPrinter::EmitLabelOffsetDifference(), llvm::AsmPrinter::EmitLabelPlusOffset(), llvm::AsmPrinter::EmitSectionOffset(), llvm::AsmPrinter::EmitULEB128(), llvm::DIE::getAbbrevNumber(), llvm::DIE::getChildren(), llvm::DIEAbbrev::getChildrenFlag(), llvm::DIE::getCompileUnit(), llvm::DIEAbbrev::getData(), llvm::CompileUnit::getDebugInfoOffset(), llvm::DIEEntry::getEntry(), llvm::DIE::getOffset(), llvm::DIEEntry::getRefAddrSize(), llvm::DIE::getSize(), llvm::DIEAbbrev::getTag(), llvm::DIEInteger::getValue(), llvm::DIE::getValues(), i, llvm::AsmPrinter::isVerbose(), j(), M, llvm::AsmPrinter::MAI, N, llvm::AsmPrinter::OutStreamer, llvm::SmallVectorTemplateCommon< T >::size(), llvm::dwarf::TagString(), useSplitDwarf(), and llvm::Twine::utohexstr().
Referenced by llvm::DwarfUnits::emitUnits().
void DwarfDebug::endFunction (const MachineFunction * MF)
Gather and emit post-function debug information.
Definition at line 1819 of file DwarfDebug.cpp.
References llvm::CompileUnit::addFlag(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::begin(), llvm::cleanseInlinedVariable(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::clear(), llvm::X86II::DB, llvm::DeleteContainerPointers(), llvm::TargetOptions::DisableFramePointerElim(), llvm::MCStreamer::EmitDwarfLocDirective(), llvm::MCStreamer::EmitLabel(), llvm::LexicalScopes::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::end(), F(), llvm::LexicalScopes::findAbstractScope(), llvm::LexicalScopes::getAbstractScopesList(), llvm::MCStreamer::getContext(), llvm::DIVariable::getContext(), llvm::LexicalScopes::getCurrentFunctionScope(), llvm::DIScope::getDirectory(), llvm::MCContext::getDwarfCompileUnitID(), llvm::DIArray::getElement(), llvm::DIScope::getFilename(), llvm::AsmPrinter::getFunctionNumber(), llvm::DIArray::getNumElements(), getOrCreateSourceID(), llvm::LexicalScope::getScopeNode(), llvm::MachineFunction::getTarget(), llvm::AsmPrinter::GetTempSymbol(), llvm::DISubprogram::getVariables(), llvm::MachineModuleInfo::hasDebugInfo(), i, I, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::DIDescriptor::isCompileUnit(), llvm::DIDescriptor::isFile(), llvm::DIDescriptor::isLexicalBlock(), llvm::DIDescriptor::isLexicalBlockFile(), llvm::DIDescriptor::isSubprogram(), llvm::DIDescriptor::isVariable(), llvm_unreachable, llvm::TargetMachine::Options, llvm::AsmPrinter::OutStreamer, S, llvm::MCContext::setDwarfCompileUnitID(), and llvm::ArrayRef< T >::size().
Referenced by llvm::AsmPrinter::EmitFunctionBody().
void DwarfDebug::endInstruction (const MachineInstr * MI)
Process end of an instruction.
Definition at line 1509 of file DwarfDebug.cpp.
References llvm::SmallVectorTemplateCommon< T >::begin(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::MCContext::CreateTempSymbol(), llvm::MCStreamer::EmitLabel(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::LexicalScope::getChildren(), llvm::MachineModuleInfo::getContext(), llvm::LexicalScopes::getCurrentFunctionScope(), llvm::LexicalScope::getRanges(), I, llvm::LexicalScope::isAbstractScope(), llvm::MachineInstr::isDebugValue(), llvm::AsmPrinter::OutStreamer, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), and S.
Referenced by llvm::AsmPrinter::EmitFunctionBody().
void DwarfDebug::endModule ()
Emit all Dwarf sections that should come after the content.
Definition at line 1147 of file DwarfDebug.cpp.
References llvm::Function::arg_size(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::cleanseInlinedVariable(), llvm::DwarfUnits::emitAddresses(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::LexicalScopes::findAbstractScope(), llvm::LexicalScopes::findLexicalScope(), for, GenerateGnuPubSections, llvm::DIVariable::getArgNumber(), llvm::DIVariable::getContext(), llvm::MCObjectFileInfo::getDwarfAddrSection(), llvm::MachineFunction::getFunction(), llvm::AsmPrinter::getObjFileLowering(), llvm::DebugLoc::getScope(), llvm::DIDescriptor::getTag(), llvm::DbgVariable::getVariable(), llvm::MachineModuleInfo::getVariableDbgInfo(), I, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::LexicalScopes::isCurrentFunctionScope(), llvm::DbgVariable::setFrameIndex(), useDwarfAccelTables(), and useSplitDwarf().
Referenced by llvm::AsmPrinter::doFinalization().
DIE* llvm::DwarfDebug::getDIE (const MDNode * TypeMD) inline
Definition at line 673 of file DwarfDebug.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::lookup().
Referenced by llvm::CompileUnit::getDIE().
unsigned llvm::DwarfDebug::getDwarfVersion () const inline
Returns the Dwarf Version.
Definition at line 727 of file DwarfDebug.h.
Referenced by llvm::CompileUnit::addFlag(), llvm::CompileUnit::constructVariableDIE(), llvm::CompileUnit::emitHeader(), and llvm::DIEEntry::getRefAddrSize().
unsigned DwarfDebug::getOrCreateSourceID (StringRef DirName, StringRef FullName, unsigned CUID)
Look up the source id with the given directory and source file names. If none currently exists, create a new id and insert it in the SourceIds map.
Definition at line 677 of file DwarfDebug.cpp.
References llvm::DIE::addChild(), llvm::CompileUnit::addDelta(), llvm::CompileUnit::addDIEEntry(), llvm::CompileUnit::addFlag(), llvm::CompileUnit::addGlobalName(), llvm::CompileUnit::addLabel(), llvm::CompileUnit::addLabelAddress(), llvm::CompileUnit::addString(), llvm::CompileUnit::addUInt(), llvm::DwarfUnits::addUnit(), llvm::MCAsmInfo::doesDwarfUseRelocationsAcrossSections(), llvm::MCStreamer::EmitDwarfFileDirective(), llvm::StringRef::empty(), GenerateGnuPubSections, llvm::MCStreamer::getContext(), llvm::DISubprogram::getContext(), llvm::DIImportedEntity::getContext(), llvm::CompileUnit::getDIE(), llvm::DIScope::getDirectory(), llvm::DIImportedEntity::getEntity(), llvm::DIScope::getFilename(), llvm::DICompileUnit::getFlags(), llvm::DICompileUnit::getLanguage(), llvm::DIImportedEntity::getLineNumber(), llvm::DISubprogram::getName(), llvm::DIImportedEntity::getName(), llvm::CompileUnit::getOrCreateContextDIE(), llvm::CompileUnit::getOrCreateNameSpace(), llvm::CompileUnit::getOrCreateSubprogramDIE(), llvm::CompileUnit::getOrCreateTypeDIE(), llvm::DICompileUnit::getProducer(), llvm::DICompileUnit::getRunTimeVersion(), llvm::DIDescriptor::getTag(), llvm::AsmPrinter::GetTempSymbol(), llvm::CompileUnit::getUniqueID(), llvm::StringMapEntry< ValueTy >::getValue(), llvm::TargetMachine::hasMCUseLoc(), llvm::MCStreamer::hasRawTextSupport(), llvm::CompileUnit::insertDIE(), llvm::DISubprogram::isDefinition(), llvm::DIDescriptor::isNameSpace(), llvm::DICompileUnit::isOptimized(), llvm::DIDescriptor::isSubprogram(), llvm::DIDescriptor::isType(), llvm::AsmPrinter::MAI, N, llvm::None, llvm::AsmPrinter::OutStreamer, resolve(), llvm::MCContext::setMCLineTableSymbol(), llvm::AsmPrinter::TM, useSplitDwarf(), llvm::utostr(), and llvm::DIImportedEntity::Verify().
Referenced by llvm::CompileUnit::addSourceLine(), endFunction(), and isSubprogramContext().
void llvm::DwarfDebug::insertDIE (const MDNode * TypeMD, DIE * Die) inline
Definition at line 670 of file DwarfDebug.h.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::insert().
Referenced by llvm::CompileUnit::insertDIE().
bool DwarfDebug::isSubprogramContext (const MDNode * Context)
isSubprogramContext - Return true if Context is either a subprogram or another context nested inside a subprogram.
Definition at line 355 of file DwarfDebug.cpp.
References llvm::CompileUnit::addAddress(), llvm::DIE::addChild(), llvm::CompileUnit::addDIEEntry(), llvm::CompileUnit::addFlag(), llvm::CompileUnit::addLabelAddress(), llvm::CompileUnit::addPubTypes(), addSubprogramNames(), llvm::CompileUnit::addType(), llvm::CompileUnit::addUInt(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::CompileUnit::constructVariableDIE(), llvm::CompileUnit::createAndAddDIE(), llvm::dbgs(), DEBUG, llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::LexicalScope::getChildren(), llvm::DISubprogram::getContext(), llvm::CompileUnit::getCUDie(), llvm::AsmPrinter::getDataLayout(), llvm::CompileUnit::getDIE(), llvm::getDISubprogram(), llvm::DIArray::getElement(), llvm::TargetRegisterInfo::getFrameRegister(), llvm::DISubprogram::getFunctionDeclaration(), llvm::AsmPrinter::getFunctionNumber(), llvm::LexicalScope::getInlinedAt(), llvm::DIArray::getNumElements(), getOrCreateSourceID(), llvm::DataLayout::getPointerSize(), llvm::LexicalScope::getRanges(), llvm::TargetMachine::getRegisterInfo(), llvm::LexicalScope::getScopeNode(), llvm::DIDescriptor::getTag(), llvm::AsmPrinter::GetTempSymbol(), llvm::DISubprogram::getType(), llvm::DICompositeType::getTypeArray(), llvm::CompileUnit::getUniqueID(), i, I, llvm::LexicalScope::isAbstractScope(), llvm::DIDescriptor::isCompileUnit(), llvm::LexicalScopes::isCurrentFunctionScope(), llvm::MCSymbol::isDefined(), llvm::DISubprogram::isDefinition(), llvm::DIDescriptor::isFile(), llvm::DIDescriptor::isSubprogram(), llvm::DIDescriptor::isType(), j(), llvm_unreachable, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::lookup(), M, llvm::AsmPrinter::MF, N, llvm::None, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), resolve(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::SmallVectorTemplateCommon< T >::size(), and llvm::AsmPrinter::TM.
Referenced by llvm::CompileUnit::createGlobalVariableDIE().
template<typename T > T llvm::DwarfDebug::resolve (DIRef< T > Ref) const inline
Find the MDNode for the given reference.
Definition at line 730 of file DwarfDebug.h.
References llvm::DIRef< T >::resolve().
Referenced by getBaseTypeSize(), llvm::CompileUnit::getHeaderSize(), getOrCreateSourceID(), isSubprogramContext(), isTypeSigned(), isTypeUnitScoped(), and isUnsignedDIType().
void llvm::DwarfDebug::setSymbolSize (const MCSymbol * Sym, uint64_t Size) inline
For symbols that have a size designated (e.g. common symbols), this tracks that size.
Definition at line 705 of file DwarfDebug.h.
Referenced by llvm::AsmPrinter::EmitGlobalVariable().
bool llvm::DwarfDebug::useDwarfAccelTables () inline
Returns whether or not to emit tables that dwarf consumers can use to accelerate lookup.
Definition at line 720 of file DwarfDebug.h.
Referenced by endModule().
bool llvm::DwarfDebug::useSplitDwarf () inline
Returns whether or not to change the current debug info for the split dwarf proposal support.
Definition at line 724 of file DwarfDebug.h.
Referenced by llvm::CompileUnit::addLabelAddress(), llvm::CompileUnit::addOpAddress(), llvm::CompileUnit::addString(), llvm::DwarfUnits::computeSizeAndOffsets(), llvm::CompileUnit::createGlobalVariableDIE(), llvm::DwarfUnits::emitAddresses(), emitDIE(), llvm::DwarfUnits::emitUnits(), endModule(), getOrCreateSourceID(), and shouldAddODRHash().
The documentation for this class was generated from the following files:
DwarfDebug.h
DwarfDebug.cpp