LLVM: llvm::SmallSet< T, N, C > Class Template Reference
LLVM API Documentation
llvm::SmallSet< T, N, C > Class Template Reference
#include <SmallSet.h>
Public Member Functions
SmallSet ()
bool empty () const
unsigned size () const
bool count (const T &V) const
count - Return true if the element is in the set.
bool insert (const T &V)
template<typename IterT >
void insert (IterT I, IterT E)
bool erase (const T &V)
void clear ()
Detailed Description
template<typename T, unsigned N, typename C = std::less<T>>
class llvm::SmallSet< T, N, C >
SmallSet - This maintains a set of unique values, optimizing for the case when the set is small (less than N). In this case, the set can be maintained with no mallocs. If the set gets large, we expand to using an std::set to maintain reasonable lookup times.
Note that this set does not provide a way to iterate over members in the set.
Definition at line 31 of file SmallSet.h.
Constructor & Destructor Documentation
template<typename T, unsigned N, typename C = std::less<T>> llvm::SmallSet< T, N, C >::SmallSet () inline
Definition at line 40 of file SmallSet.h.
Member Function Documentation
template<typename T, unsigned N, typename C = std::less<T>> void llvm::SmallSet< T, N, C >::clear () inline
Definition at line 97 of file SmallSet.h.
Referenced by checkInterfaceFunction(), CollectSubexprs(), getCopyOrBitcastDefUseIdx(), InstructionStoresToFI(), and isCopy().
template<typename T, unsigned N, typename C = std::less<T>> bool llvm::SmallSet< T, N, C >::count (const T & V) const inline
count - Return true if the element is in the set.
Definition at line 48 of file SmallSet.h.
Referenced by llvm::LiveVariables::addNewBlock(), AdjustStackOffset(), AntiDepEdges(), areAllUsesIn(), llvm::BranchFolder::BranchFolder(), llvm::ARMBaseInstrInfo::canCauseFpMLxStall(), llvm::ARMBaseInstrInfo::copyPhysReg(), llvm::createHexagonHardwareLoops(), llvm::createSparcDelaySlotFillerPass(), llvm::finalizeBundle(), findDeadCallerSavedReg(), findHoistingInsertPosAndDeps(), getCopyOrBitcastDefUseIdx(), llvm::LiveVariables::HandleVirtRegDef(), INITIALIZE_PASS(), InstructionStoresToFI(), isCopy(), isHighLatencyCPSR(), isi32Store(), IsSafeAndProfitableToMove(), isVtableAccess(), MaySpeculate(), regsAreCompatible(), RemoveKills(), llvm::LiveVariables::runOnMachineFunction(), llvm::MachineBasicBlock::SplitCriticalEdge(), and verifyCTRBranch().
template<typename T, unsigned N, typename C = std::less<T>> bool llvm::SmallSet< T, N, C >::empty () const inline
Definition at line 42 of file SmallSet.h.
Referenced by llvm::BranchFolder::BranchFolder(), llvm::createHexagonHardwareLoops(), and findHoistingInsertPosAndDeps().
template<typename T, unsigned N, typename C = std::less<T>> bool llvm::SmallSet< T, N, C >::erase (const T & V) inline
Definition at line 86 of file SmallSet.h.
Referenced by areAllUsesIn(), llvm::finalizeBundle(), findHoistingInsertPosAndDeps(), llvm::LiveVariables::HandleVirtRegDef(), llvm::SetVector< llvm::BasicBlock * >::operator!=(), and regsAreCompatible().
template<typename T, unsigned N, typename C = std::less<T>> bool llvm::SmallSet< T, N, C >::insert (const T & V) inline
insert - Insert an element into the set if it isn't already there. Returns true if the element is inserted (it was not in the set before).
Definition at line 59 of file SmallSet.h.
Referenced by llvm::LiveVariables::addNewBlock(), AdjustStackOffset(), AntiDepEdges(), areAllUsesIn(), llvm::ARMBaseInstrInfo::ARMBaseInstrInfo(), llvm::BranchFolder::BranchFolder(), buildFromShuffleMostly(), CheckForLiveRegDef(), CheckForLiveRegDefMasked(), checkInterfaceFunction(), CollectSubexprs(), ComputeRange(), concatenateMemOperands(), llvm::ARMBaseInstrInfo::copyPhysReg(), llvm::createHexagonHardwareLoops(), llvm::createSparcDelaySlotFillerPass(), determinePointerReadAttrs(), llvm::finalizeBundle(), findConsecutiveLoad(), findDeadCallerSavedReg(), findHoistingInsertPosAndDeps(), llvm::R600InstrInfo::fitsConstReadLimitations(), getCopyOrBitcastDefUseIdx(), llvm::DenseMapInfo< ComparableFunction >::getHashValue(), getNodeRegMask(), llvm::LiveVariables::HandleVirtRegDef(), llvm::SCEVExpander::hoistIVInc(), INITIALIZE_PASS(), llvm::SmallSet< llvm::BasicBlock *, 16 >::insert(), InstructionStoresToFI(), isHighLatencyCPSR(), isi32Store(), isOperandKill(), isPotentiallyReachableInner(), IsSafeAndProfitableToMove(), isVtableAccess(), llvm::PointerMayBeCaptured(), ProcessSourceNode(), regsAreCompatible(), RemoveKills(), llvm::LiveVariables::runOnMachineFunction(), llvm::MachineBasicBlock::SplitCriticalEdge(), TrackDefUses(), llvm::SelectionDAGBuilder::UpdateSplitBlock(), and verifyCTRBranch().
template<typename T, unsigned N, typename C = std::less<T>> template<typename IterT > void llvm::SmallSet< T, N, C >::insert (IterT I, IterT E) inline
Definition at line 81 of file SmallSet.h.
template<typename T, unsigned N, typename C = std::less<T>> unsigned llvm::SmallSet< T, N, C >::size () const inline
Definition at line 43 of file SmallSet.h.
Referenced by areAllUsesIn(), buildFromShuffleMostly(), ComputeRange(), llvm::R600InstrInfo::fitsConstReadLimitations(), and IsSafeAndProfitableToMove().
The documentation for this class was generated from the following file:
SmallSet.h