LLVM: llvm::MachineLoopInfo Class Reference
LLVM API Documentation
llvm::MachineLoopInfo Class Reference
#include <MachineLoopInfo.h>
Public Types
typedef LoopInfoBase< MachineBasicBlock, MachineLoop >::iterator iterator
Public Member Functions
MachineLoopInfo ()
LoopInfoBase< MachineBasicBlock, MachineLoop > & getBase ()
iterator begin () const
iterator end () const
bool empty () const
MachineLoop * getLoopFor (const MachineBasicBlock *BB) const
const MachineLoop * operator[] (const MachineBasicBlock *BB) const
unsigned getLoopDepth (const MachineBasicBlock *BB) const
bool isLoopHeader (MachineBasicBlock *BB) const
virtual bool runOnMachineFunction (MachineFunction &F)
virtual void releaseMemory ()
virtual void getAnalysisUsage (AnalysisUsage &AU) const
MachineLoop * removeLoop (iterator I)
void changeLoopFor (MachineBasicBlock *BB, MachineLoop *L)
void changeTopLevelLoop (MachineLoop *OldLoop, MachineLoop *NewLoop)
void addTopLevelLoop (MachineLoop *New)
void removeBlock (MachineBasicBlock *BB)
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const
createPrinterPass - Get a function printer pass.
virtual void assignPassManager (PMStack &PMS, PassManagerType T)
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Friends
class LoopBase< MachineBasicBlock, MachineLoop >
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
Detailed Description
Definition at line 72 of file MachineLoopInfo.h.
Member Typedef Documentation
typedef LoopInfoBase<MachineBasicBlock, MachineLoop>::iterator llvm::MachineLoopInfo::iterator
iterator/begin/end - The interface to the top-level loops in the current function.
Definition at line 91 of file MachineLoopInfo.h.
Constructor & Destructor Documentation
llvm::MachineLoopInfo::MachineLoopInfo () inline
Definition at line 82 of file MachineLoopInfo.h.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeMachineLoopInfoPass().
Member Function Documentation
void llvm::MachineLoopInfo::addTopLevelLoop (MachineLoop * New) inline
addTopLevelLoop - This adds the specified loop to the collection of top-level loops.
Definition at line 148 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::addTopLevelLoop().
iterator llvm::MachineLoopInfo::begin () const inline
Definition at line 92 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::begin().
Referenced by llvm::createHexagonHardwareLoops(), and LoopIsOuterMostWithPredecessor().
void llvm::MachineLoopInfo::changeLoopFor (MachineBasicBlock * BB, MachineLoop * L) inline
changeLoopFor - Change the top-level loop that contains BB to the specified loop. This should be used by transformations that restructure the loop hierarchy tree.
Definition at line 136 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::changeLoopFor().
void llvm::MachineLoopInfo::changeTopLevelLoop (MachineLoop * OldLoop, MachineLoop * NewLoop) inline
changeTopLevelLoop - Replace the specified loop in the top-level loops list with the indicated loop.
Definition at line 142 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::changeTopLevelLoop().
bool llvm::MachineLoopInfo::empty () const inline
Definition at line 94 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::empty().
iterator llvm::MachineLoopInfo::end () const inline
Definition at line 93 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::end().
Referenced by llvm::createHexagonHardwareLoops(), and LoopIsOuterMostWithPredecessor().
void MachineLoopInfo::getAnalysisUsage (AnalysisUsage & AU) const virtual
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
For MachineFunctionPasses, calling AU.preservesCFG() indicates that the pass does not modify the MachineBasicBlock CFG.
Reimplemented from llvm::MachineFunctionPass.
Definition at line 43 of file MachineLoopInfo.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::MachineFunctionPass::getAnalysisUsage(), and llvm::AnalysisUsage::setPreservesAll().
LoopInfoBase<MachineBasicBlock, MachineLoop>& llvm::MachineLoopInfo::getBase () inline
Definition at line 86 of file MachineLoopInfo.h.
unsigned llvm::MachineLoopInfo::getLoopDepth (const MachineBasicBlock * BB) const inline
getLoopDepth - Return the loop nesting level of the specified block...
Definition at line 111 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::getLoopDepth().
Referenced by operator<<(), and llvm::VLIWMachineScheduler::schedule().
MachineLoop* llvm::MachineLoopInfo::getLoopFor (const MachineBasicBlock * BB) const inline
getLoopFor - Return the inner most loop that BB lives in. If a basic block is in no loop (for example the entry node), null is returned.
Definition at line 99 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor().
Referenced by llvm::VirtRegAuxInfo::calculateSpillWeightAndHint(), emitBasicBlockLoopComments(), llvm::MachineTraceMetrics::Ensemble::getLoopFor(), InstructionStoresToFI(), and isSourceDefinedByImplicitDef().
bool llvm::MachineLoopInfo::isLoopHeader (MachineBasicBlock * BB) const inline
Definition at line 116 of file MachineLoopInfo.h.
References F(), and llvm::LoopInfoBase< BlockT, LoopT >::isLoopHeader().
Referenced by isPostDominatedBy().
const MachineLoop* llvm::MachineLoopInfo::operator[] (const MachineBasicBlock * BB) const inline
operator[] - same as getLoopFor...
Definition at line 105 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::getLoopFor().
virtual void llvm::MachineLoopInfo::releaseMemory () inline virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed. The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 124 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::releaseMemory().
void llvm::MachineLoopInfo::removeBlock (MachineBasicBlock * BB) inline
removeBlock - This method completely removes BB from all data structures, including all of the Loop objects it is nested in and our mapping from MachineBasicBlocks to loops.
Definition at line 155 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::removeBlock().
MachineLoop* llvm::MachineLoopInfo::removeLoop (iterator I) inline
removeLoop - This removes the specified top-level loop from this loop info object. The loop is not deleted, as it will presumably be inserted into another loop.
Definition at line 131 of file MachineLoopInfo.h.
References llvm::LoopInfoBase< BlockT, LoopT >::removeLoop().
bool MachineLoopInfo::runOnMachineFunction (MachineFunction & F) virtual
runOnFunction - Calculate the natural loop information.
Implements llvm::MachineFunctionPass.
Definition at line 37 of file MachineLoopInfo.cpp.
Friends And Related Function Documentation
friend class LoopBase< MachineBasicBlock, MachineLoop > friend
Definition at line 74 of file MachineLoopInfo.h.
Member Data Documentation
char MachineLoopInfo::ID = 0 static
Definition at line 80 of file MachineLoopInfo.h.
The documentation for this class was generated from the following files:
MachineLoopInfo.h
MachineLoopInfo.cpp