LLVM: llvm::ConstantVector Class Reference
LLVM API Documentation
llvm::ConstantVector Class Reference
#include <Constants.h>
Public Member Functions
DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Constant)
Transparently provide more efficient getOperand methods.
VectorType * getType () const
Constant * getSplatValue () const
virtual void destroyConstant ()
virtual void replaceUsesOfWithOnConstant (Value *From, Value *To, Use *U)
Public Member Functions inherited from llvm::Constant
bool isNullValue () const
bool isAllOnesValue () const
bool isNegativeZeroValue () const
bool isZeroValue () const
Return true if the value is negative zero or null value.
bool canTrap () const
bool isThreadDependent () const
isThreadDependent - Return true if the value can vary between threads.
bool isConstantUsed () const
PossibleRelocationsTy getRelocationInfo () const
Constant * getAggregateElement (unsigned Elt) const
Constant * getAggregateElement (Constant *Elt) const
Constant * getSplatValue () const
const APInt & getUniqueInteger () const
void removeDeadConstantUsers () const
Public Member Functions inherited from llvm::User
~User ()
void operator delete (void *Usr)
operator delete - free memory allocated for User and Use objects
void operator delete (void *, unsigned)
placement delete - required by std, but never called.
void operator delete (void *, unsigned, bool)
placement delete - required by std, but never called.
Value * getOperand (unsigned i) const
void setOperand (unsigned i, Value *Val)
const Use & getOperandUse (unsigned i) const
Use & getOperandUse (unsigned i)
unsigned getNumOperands () const
op_iterator op_begin ()
const_op_iterator op_begin () const
op_iterator op_end ()
const_op_iterator op_end () const
value_op_iterator value_op_begin ()
value_op_iterator value_op_end ()
void dropAllReferences ()
void replaceUsesOfWith (Value *From, Value *To)
Public Member Functions inherited from llvm::Value
virtual ~Value ()
void dump () const
dump - Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O, AssemblyAnnotationWriter *AAW=0) const
Type * getType () const
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
void setName (const Twine &Name)
void takeName (Value *V)
void replaceAllUsesWith (Value *V)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
User * use_back ()
const User * use_back () const
bool hasOneUse () const
bool hasNUses (unsigned N) const
bool hasNUsesOrMore (unsigned N) const
bool isUsedInBasicBlock (const BasicBlock *BB) const
unsigned getNumUses () const
void addUse (Use &U)
unsigned getValueID () const
unsigned getRawSubclassOptionalData () const
void clearSubclassOptionalData ()
bool hasSameSubclassOptionalData (const Value *V) const
void intersectOptionalDataWith (const Value *V)
bool hasValueHandle () const
Value * stripPointerCasts ()
Strips off any unneeded pointer casts, all-zero GEPs and aliases from the specified value, returning the original uncasted value.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strips off any unneeded pointer casts and all-zero GEPs from the specified value, returning the original uncasted value.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strips off unneeded pointer casts and all-constant GEPs from the specified value, returning the original pointer value.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Strips like stripInBoundsConstantOffsets but also accumulates the constant offset stripped.
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strips off unneeded pointer casts and any in-bounds offsets from the specified value, returning the original pointer value.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer () const
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Static Public Member Functions
static Constant * get (ArrayRef< Constant * > V)
static Constant * getSplat (unsigned NumElts, Constant *Elt)
static bool classof (const Value *V)
Methods for support type inquiry through isa, cast, and dyn_cast:
Static Public Member Functions inherited from llvm::Constant
static bool classof (const Value *V)
static Constant * getNullValue (Type *Ty)
static Constant * getAllOnesValue (Type *Ty)
Get the all ones value.
static Constant * getIntegerValue (Type *Ty, const APInt &V)
Static Public Member Functions inherited from llvm::User
static bool classof (const Value *V)
Protected Member Functions
ConstantVector (VectorType *T, ArrayRef< Constant * > Val)
Protected Member Functions inherited from llvm::Constant
Constant (Type *ty, ValueTy vty, Use *Ops, unsigned NumOps)
void destroyConstantImpl ()
Protected Member Functions inherited from llvm::User
void * operator new (size_t s, unsigned Us)
User (Type *ty, unsigned vty, Use *OpList, unsigned NumOps)
Use * allocHungoffUses (unsigned) const
void dropHungoffUses ()
template<int Idx>
Use & Op ()
template<int Idx>
const Use & Op () const
Protected Member Functions inherited from llvm::Value
virtual void printCustom (raw_ostream &O) const
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Friends
struct ConstantArrayCreator< ConstantVector, VectorType >
Additional Inherited Members
Public Types inherited from llvm::Constant
enum PossibleRelocationsTy { NoRelocation = 0, LocalRelocation = 1, GlobalRelocations = 2 }
Public Types inherited from llvm::User
typedef Use * op_iterator
typedef const Use * const_op_iterator
Public Types inherited from llvm::Value
enum ValueTy {
ArgumentVal, BasicBlockVal, FunctionVal, GlobalAliasVal,
GlobalVariableVal, UndefValueVal, BlockAddressVal, ConstantExprVal,
ConstantAggregateZeroVal, ConstantDataArrayVal, ConstantDataVectorVal, ConstantIntVal,
ConstantFPVal, ConstantArrayVal, ConstantStructVal, ConstantVectorVal,
ConstantPointerNullVal, MDNodeVal, MDStringVal, InlineAsmVal,
PseudoSourceValueVal, FixedStackPseudoSourceValueVal, InstructionVal, ConstantFirstVal = FunctionVal,
ConstantLastVal = ConstantPointerNullVal
}
typedef value_use_iterator< User > use_iterator
typedef value_use_iterator< const User > const_use_iterator
Static Public Attributes inherited from llvm::Value
static const unsigned MaximumAlignment = 1u << 29
Static Protected Member Functions inherited from llvm::User
template<int Idx, typename U >
static Use & OpFrom (const U *that)
Protected Attributes inherited from llvm::User
Use * OperandList
unsigned NumOperands
Protected Attributes inherited from llvm::Value
unsigned char SubclassOptionalData: 7
Detailed Description
ConstantVector - Constant Vector Declarations
Definition at line 437 of file Constants.h.
Constructor & Destructor Documentation
ConstantVector::ConstantVector (VectorType * T, ArrayRef< Constant * > Val) protected
Definition at line 912 of file Constants.cpp.
References llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::SequentialType::getElementType(), getType(), i, llvm::User::op_begin(), and llvm::ArrayRef< T >::size().
Member Function Documentation
static bool llvm::ConstantVector::classof (const Value * V) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 468 of file Constants.h.
References llvm::Value::ConstantVectorVal, and llvm::Value::getValueID().
llvm::ConstantVector::DECLARE_TRANSPARENT_OPERAND_ACCESSORS (Constant)
Transparently provide more efficient getOperand methods.
void ConstantVector::destroyConstant () virtual
destroyConstant - Called if some element of this constant is no longer valid. At this point only other constants may be on the use_list for this constant. Any constants on our Use list must also be destroy'd. The implementation must be sure to remove the constant from the list of available cached constants. Implementations should call destroyConstantImpl as the last thing they do, to destroy all users and delete this.
Reimplemented from llvm::Constant.
Definition at line 1269 of file Constants.cpp.
References llvm::Constant::destroyConstantImpl(), llvm::Type::getContext(), getType(), llvm::LLVMContext::pImpl, llvm::ConstantAggrUniqueMap< TypeClass, ConstantClass >::remove(), and llvm::LLVMContextImpl::VectorConstants.
Referenced by llvm::ConstantArray::replaceUsesOfWithOnConstant(), llvm::ConstantStruct::replaceUsesOfWithOnConstant(), replaceUsesOfWithOnConstant(), llvm::BlockAddress::replaceUsesOfWithOnConstant(), and llvm::ConstantExpr::replaceUsesOfWithOnConstant().
Constant * ConstantVector::get (ArrayRef< Constant * > V) static
Definition at line 923 of file Constants.cpp.
References llvm::ArrayRef< T >::empty(), llvm::ArrayRef< T >::front(), llvm::ConstantAggregateZero::get(), llvm::VectorType::get(), llvm::ConstantDataVector::get(), llvm::UndefValue::get(), llvm::Value::getContext(), llvm::Value::getType(), i, llvm::ConstantDataSequential::isElementTypeCompatible(), llvm::Constant::isNullValue(), isZero(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::ArrayRef< T >::size(), llvm::SmallVectorTemplateCommon< T >::size(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by BitCastConstantVector(), llvm::X86TargetLowering::BuildFILD(), BuildNew(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldInsertElementInstruction(), llvm::ConstantFoldInsertValueInstruction(), llvm::ConstantFoldSelectInstruction(), llvm::ConstantFoldShuffleVectorInstruction(), cse(), EvaluateStoreInto(), ExpandUnalignedLoad(), extractVector(), FoldBitCast(), FunctionNumber(), getGEPInductionOperand(), getLogBase2Vector(), insertVector(), LLVMConstVector(), LowerFP_EXTEND(), llvm::MapValue(), ReadWideAPInt(), llvm::BitcodeReaderValueList::ResolveConstantForwardRefs(), ShrinkDemandedConstant(), llvm::UpgradeIntrinsicCall(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitInsertElementInst(), llvm::InstCombiner::visitShuffleVectorInst(), and llvm::InstCombiner::visitSRem().
Constant * ConstantVector::getSplat (unsigned NumElts, Constant * Elt) static
getSplat - Return a ConstantVector with the specified constant in each element.
Definition at line 1021 of file Constants.cpp.
References llvm::ConstantDataVector::getSplat(), llvm::Value::getType(), and llvm::ConstantDataSequential::isElementTypeCompatible().
Referenced by cse(), llvm::ConstantInt::get(), llvm::ConstantFP::get(), llvm::Constant::getAllOnesValue(), llvm::ConstantInt::getFalse(), llvm::Constant::getIntegerValue(), llvm::ConstantDataVector::getSplat(), llvm::ConstantInt::getTrue(), llvm::ConstantFP::getZeroValueForNegation(), isCompatibleAggregate(), LowerFP_EXTEND(), and stripAndComputeConstantOffsets().
Constant * ConstantVector::getSplatValue () const
getSplatValue - If this is a splat constant, meaning that all of the elements have the same value, return that value. Otherwise return NULL.
getSplatValue - If this is a splat constant, where all of the elements have the same value, return that value. Otherwise return null.
Definition at line 1289 of file Constants.cpp.
References llvm::User::getNumOperands(), llvm::User::getOperand(), and I.
Referenced by getOperandInfo(), and llvm::Constant::getUniqueInteger().
VectorType* llvm::ConstantVector::getType () const inline
getType - Specialize the getType() method to always return a VectorType, which reduces the amount of casting needed in parts of the compiler.
Definition at line 456 of file Constants.h.
References llvm::Constant::destroyConstant(), llvm::Constant::getSplatValue(), llvm::Value::getType(), and llvm::Constant::replaceUsesOfWithOnConstant().
Referenced by ConstantVector(), llvm::ConstantAggregateZero::destroyConstant(), llvm::ConstantArray::destroyConstant(), llvm::ConstantStruct::destroyConstant(), destroyConstant(), llvm::ConstantPointerNull::destroyConstant(), llvm::ConstantDataSequential::destroyConstant(), llvm::ConstantExpr::destroyConstant(), llvm::UndefValue::destroyConstant(), emitGlobalConstantVector(), llvm::ConstantExpr::getAsInstruction(), llvm::ConstantDataSequential::getElementType(), llvm::ConstantExpr::getGetElementPtr(), llvm::ConstantDataSequential::getNumElements(), llvm::Constant::getSplatValue(), llvm::ConstantExpr::getWithOperands(), llvm::ConstantDataSequential::isString(), llvm::ConstantArray::replaceUsesOfWithOnConstant(), and llvm::ConstantStruct::replaceUsesOfWithOnConstant().
void ConstantVector::replaceUsesOfWithOnConstant (Value * , Value * , Use *) virtual
replaceUsesOfWithOnConstant - This method is a special form of User::replaceUsesOfWith (which does not work on constants) that does work on constants. Basically this method goes through the trouble of building a new constant that is equivalent to the current one, with all uses of From replaced with uses of To. After this construction is completed, all of the users of 'this' are replaced to use the new constant, and then 'this' is deleted. In general, you should not call this method, instead, use Value::replaceAllUsesWith, which automatically dispatches to this method as needed.
Reimplemented from llvm::Constant.
Definition at line 2721 of file Constants.cpp.
References destroyConstant(), llvm::User::getNumOperands(), llvm::User::getOperand(), i, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::Value::replaceAllUsesWith(), and llvm::SmallVectorImpl< T >::reserve().
Friends And Related Function Documentation
friend struct ConstantArrayCreator< ConstantVector, VectorType > friend
Definition at line 438 of file Constants.h.
The documentation for this class was generated from the following files:
Constants.h
Constants.cpp