LLVM: llvm::LoadAndStorePromoter Class Reference
LLVM API Documentation
llvm::LoadAndStorePromoter Class Reference
Helper class for promoting a collection of loads and stores into SSA Form using the SSAUpdater.
#include <SSAUpdater.h>
Public Member Functions
LoadAndStorePromoter (const SmallVectorImpl< Instruction * > &Insts, SSAUpdater &S, StringRef Name=StringRef())
virtual ~LoadAndStorePromoter ()
void run (const SmallVectorImpl< Instruction * > &Insts) const
This does the promotion.
virtual bool isInstInList (Instruction *I, const SmallVectorImpl< Instruction * > &Insts) const
Return true if the specified instruction is in the Inst list.
virtual void doExtraRewritesBeforeFinalDeletion () const
This hook is invoked after all the stores are found and inserted as available values.
virtual void replaceLoadWithValue (LoadInst *LI, Value *V) const
Clients can choose to implement this to get notified right before a load is RAUW'd another value.
virtual void instructionDeleted (Instruction *I) const
Called before each instruction is deleted.
virtual void updateDebugInfo (Instruction *I) const
Called to update debug info associated with the instruction.
Protected Attributes
SSAUpdater & SSA
Detailed Description
Helper class for promoting a collection of loads and stores into SSA Form using the SSAUpdater.
This handles complexities that SSAUpdater doesn't, such as multiple loads and stores in one block.
Clients of this class are expected to subclass this and implement the virtual methods.
Definition at line 133 of file SSAUpdater.h.
Constructor & Destructor Documentation
LoadAndStorePromoter::LoadAndStorePromoter (const SmallVectorImpl< Instruction * > & Insts, SSAUpdater & S, StringRef Name = StringRef())
Definition at line 325 of file SSAUpdater.cpp.
References llvm::SmallVectorBase::empty(), llvm::StringRef::empty(), llvm::Value::getName(), llvm::Value::getType(), llvm::SSAUpdater::Initialize(), run(), and SSA.
Referenced by llvm::SSAUpdaterTraits< SSAUpdater >::GetPHIValue().
virtual llvm::LoadAndStorePromoter::~LoadAndStorePromoter () inline virtual
Definition at line 139 of file SSAUpdater.h.
References I.
Member Function Documentation
virtual void llvm::LoadAndStorePromoter::doExtraRewritesBeforeFinalDeletion () const inline virtual
This hook is invoked after all the stores are found and inserted as available values.
Definition at line 158 of file SSAUpdater.h.
Referenced by run().
virtual void llvm::LoadAndStorePromoter::instructionDeleted (Instruction * I) const inline virtual
Called before each instruction is deleted.
Definition at line 167 of file SSAUpdater.h.
Referenced by run().
bool LoadAndStorePromoter::isInstInList (Instruction * I, const SmallVectorImpl< Instruction * > & Insts) const virtual
Return true if the specified instruction is in the Inst list.
The Insts list is the one passed into the constructor. Clients should implement this with a more efficient version if possible.
Definition at line 488 of file SSAUpdater.cpp.
References llvm::SmallVectorTemplateCommon< T >::begin(), llvm::SmallVectorTemplateCommon< T >::end(), and I.
Referenced by run().
virtual void llvm::LoadAndStorePromoter::replaceLoadWithValue (LoadInst * LI, Value * V) const inline virtual
Clients can choose to implement this to get notified right before a load is RAUW'd another value.
Definition at line 163 of file SSAUpdater.h.
Referenced by run().
void LoadAndStorePromoter::run (const SmallVectorImpl< Instruction * > & Insts) const
This does the promotion.
Insts is a list of loads and stores to promote, and Name is the basename for the PHIs to insert. After this is complete, the loads and stores are removed from the code.
Definition at line 342 of file SSAUpdater.cpp.
References llvm::SSAUpdater::AddAvailableValue(), BB, llvm::BasicBlock::begin(), llvm::TinyPtrVector< EltTy >::clear(), doExtraRewritesBeforeFinalDeletion(), llvm::TinyPtrVector< EltTy >::empty(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), llvm::BasicBlock::end(), llvm::Instruction::eraseFromParent(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::find(), llvm::UndefValue::get(), llvm::Instruction::getParent(), llvm::Value::getType(), llvm::SSAUpdater::GetValueInMiddleOfBlock(), i, instructionDeleted(), isInstInList(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::Value::replaceAllUsesWith(), replaceLoadWithValue(), llvm::TinyPtrVector< EltTy >::size(), llvm::SmallVectorTemplateCommon< T >::size(), SSA, updateDebugInfo(), and llvm::Value::use_empty().
Referenced by LoadAndStorePromoter(), and AllocaSlices::SliceBuilder::SliceBuilder().
virtual void llvm::LoadAndStorePromoter::updateDebugInfo (Instruction * I) const inline virtual
Called to update debug info associated with the instruction.
Definition at line 171 of file SSAUpdater.h.
Referenced by run().
Member Data Documentation
SSAUpdater& llvm::LoadAndStorePromoter::SSA protected
Definition at line 135 of file SSAUpdater.h.
Referenced by LoadAndStorePromoter(), and run().
The documentation for this class was generated from the following files:
SSAUpdater.h
SSAUpdater.cpp