LLVM: llvm::AttributeImpl Class Reference
LLVM API Documentation
llvm::AttributeImpl Class Reference
#include <AttributeImpl.h>
Public Member Functions
virtual ~AttributeImpl ()
bool isEnumAttribute () const
bool isAlignAttribute () const
bool isStringAttribute () const
bool hasAttribute (Attribute::AttrKind A) const
bool hasAttribute (StringRef Kind) const
Attribute::AttrKind getKindAsEnum () const
uint64_t getValueAsInt () const
StringRef getKindAsString () const
StringRef getValueAsString () const
bool operator< (const AttributeImpl &AI) const
Used when sorting the attributes.
void Profile (FoldingSetNodeID &ID) const
Public Member Functions inherited from llvm::FoldingSetImpl::Node
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static void Profile (FoldingSetNodeID &ID, Attribute::AttrKind Kind, uint64_t Val)
static void Profile (FoldingSetNodeID &ID, StringRef Kind, StringRef Values)
static uint64_t getAttrMask (Attribute::AttrKind Val)
Protected Types
enum AttrEntryKind { EnumAttrEntry, AlignAttrEntry, StringAttrEntry }
Protected Member Functions
AttributeImpl (AttrEntryKind KindID)
Detailed Description
Definition at line 32 of file AttributeImpl.h.
Member Enumeration Documentation
enum llvm::AttributeImpl::AttrEntryKind protected
Enumerator
EnumAttrEntry
AlignAttrEntry
StringAttrEntry
Definition at line 40 of file AttributeImpl.h.
Constructor & Destructor Documentation
llvm::AttributeImpl::AttributeImpl (AttrEntryKind KindID) inline protected
Definition at line 46 of file AttributeImpl.h.
References ~AttributeImpl().
AttributeImpl::~AttributeImpl () virtual
Definition at line 290 of file Attributes.cpp.
Referenced by AttributeImpl().
Member Function Documentation
uint64_t AttributeImpl::getAttrMask (Attribute::AttrKind Val) static
Definition at line 347 of file Attributes.cpp.
References llvm::Attribute::Alignment, llvm::Attribute::AlwaysInline, llvm::Attribute::Builtin, llvm::Attribute::ByVal, llvm::Attribute::Cold, llvm::Attribute::EndAttrKinds, llvm::Attribute::InlineHint, llvm::Attribute::InReg, llvm_unreachable, llvm::Attribute::MinSize, llvm::Attribute::Naked, llvm::Attribute::Nest, llvm::Attribute::NoAlias, llvm::Attribute::NoBuiltin, llvm::Attribute::NoCapture, llvm::Attribute::NoDuplicate, llvm::Attribute::NoImplicitFloat, llvm::Attribute::NoInline, llvm::Attribute::None, llvm::Attribute::NonLazyBind, llvm::Attribute::NoRedZone, llvm::Attribute::NoReturn, llvm::Attribute::NoUnwind, llvm::Attribute::OptimizeForSize, llvm::Attribute::OptimizeNone, llvm::Attribute::ReadNone, llvm::Attribute::ReadOnly, llvm::Attribute::Returned, llvm::Attribute::ReturnsTwice, llvm::Attribute::SanitizeAddress, llvm::Attribute::SanitizeMemory, llvm::Attribute::SanitizeThread, llvm::Attribute::SExt, llvm::Attribute::StackAlignment, llvm::Attribute::StackProtect, llvm::Attribute::StackProtectReq, llvm::Attribute::StackProtectStrong, llvm::Attribute::StructRet, llvm::Attribute::UWTable, and llvm::Attribute::ZExt.
Referenced by llvm::AttrBuilder::addRawValue(), Profile(), and llvm::AttributeSetImpl::Raw().
Attribute::AttrKind AttributeImpl::getKindAsEnum () const
Definition at line 305 of file Attributes.cpp.
References llvm::Attribute::isAlignAttribute(), and llvm::Attribute::isEnumAttribute().
Referenced by llvm::Attribute::getKindAsEnum(), isStringAttribute(), operator<(), and Profile().
StringRef AttributeImpl::getKindAsString () const
Definition at line 315 of file Attributes.cpp.
References llvm::Attribute::isStringAttribute().
Referenced by llvm::Attribute::getKindAsString(), isStringAttribute(), operator<(), and Profile().
uint64_t AttributeImpl::getValueAsInt () const
Definition at line 310 of file Attributes.cpp.
References llvm::Attribute::getAlignment(), and llvm::Attribute::isAlignAttribute().
Referenced by llvm::Attribute::getAlignment(), llvm::Attribute::getStackAlignment(), llvm::Attribute::getValueAsInt(), isStringAttribute(), operator<(), and Profile().
StringRef AttributeImpl::getValueAsString () const
Definition at line 320 of file Attributes.cpp.
References llvm::Attribute::isStringAttribute().
Referenced by llvm::Attribute::getAsString(), llvm::Attribute::getValueAsString(), isStringAttribute(), operator<(), and Profile().
bool AttributeImpl::hasAttribute (Attribute::AttrKind A) const
Definition at line 295 of file Attributes.cpp.
References llvm::ARM_PROC::A, llvm::Attribute::getKindAsEnum(), and llvm::Attribute::isStringAttribute().
Referenced by llvm::Attribute::hasAttribute(), and isStringAttribute().
bool AttributeImpl::hasAttribute (StringRef Kind) const
Definition at line 300 of file Attributes.cpp.
References llvm::Attribute::getKindAsString(), and llvm::Attribute::isStringAttribute().
bool llvm::AttributeImpl::isAlignAttribute () const inline
Definition at line 52 of file AttributeImpl.h.
References AlignAttrEntry.
Referenced by llvm::Attribute::isAlignAttribute(), operator<(), and Profile().
bool llvm::AttributeImpl::isEnumAttribute () const inline
Definition at line 51 of file AttributeImpl.h.
References EnumAttrEntry.
Referenced by llvm::Attribute::isEnumAttribute(), operator<(), and Profile().
bool llvm::AttributeImpl::isStringAttribute () const inline
Definition at line 53 of file AttributeImpl.h.
References llvm::ARM_PROC::A, getKindAsEnum(), getKindAsString(), getValueAsInt(), getValueAsString(), hasAttribute(), operator<(), and StringAttrEntry.
Referenced by llvm::Attribute::isStringAttribute(), and operator<().
bool AttributeImpl::operator< (const AttributeImpl & AI) const
Used when sorting the attributes.
Definition at line 325 of file Attributes.cpp.
References getKindAsEnum(), llvm::Attribute::getKindAsEnum(), getKindAsString(), llvm::Attribute::getKindAsString(), getValueAsInt(), llvm::Attribute::getValueAsInt(), getValueAsString(), llvm::Attribute::getValueAsString(), isAlignAttribute(), llvm::Attribute::isAlignAttribute(), isEnumAttribute(), llvm::Attribute::isEnumAttribute(), and isStringAttribute().
Referenced by isStringAttribute().
void llvm::AttributeImpl::Profile (FoldingSetNodeID & ID) const inline
Definition at line 67 of file AttributeImpl.h.
References getKindAsEnum(), getKindAsString(), getValueAsInt(), getValueAsString(), isAlignAttribute(), and isEnumAttribute().
Referenced by llvm::AttributeSetNode::Profile(), and llvm::AttributeSetImpl::Profile().
static void llvm::AttributeImpl::Profile (FoldingSetNodeID & ID, Attribute::AttrKind Kind, uint64_t Val) inline static
Definition at line 75 of file AttributeImpl.h.
References llvm::FoldingSetNodeID::AddInteger().
static void llvm::AttributeImpl::Profile (FoldingSetNodeID & ID, StringRef Kind, StringRef Values) inline static
Definition at line 80 of file AttributeImpl.h.
References llvm::FoldingSetNodeID::AddString(), llvm::StringRef::empty(), and getAttrMask().
The documentation for this class was generated from the following files:
AttributeImpl.h
Attributes.cpp