LLVM: llvm::MCWin64EHUnwindEmitter Class Reference
LLVM API Documentation
llvm::MCWin64EHUnwindEmitter Class Reference
#include <MCWin64EH.h>
Static Public Member Functions
static StringRef GetSectionSuffix (const MCSymbol *func)
static void Emit (MCStreamer &streamer)
static void EmitUnwindInfo (MCStreamer &streamer, MCWin64EHUnwindInfo *info)
Detailed Description
Definition at line 82 of file MCWin64EH.h.
Member Function Documentation
void llvm::MCWin64EHUnwindEmitter::Emit (MCStreamer & streamer) static
Definition at line 277 of file MCWin64EH.cpp.
References llvm::EmitRuntimeFunction(), llvm::EmitUnwindInfo(), llvm::MCWin64EHUnwindInfo::Function, llvm::MCStreamer::getContext(), llvm::MCStreamer::getNumW64UnwindInfos(), GetSectionSuffix(), llvm::MCStreamer::getW64UnwindInfo(), llvm::getWin64EHFuncTableSection(), llvm::getWin64EHTableSection(), i, info, and llvm::MCStreamer::SwitchSection().
Referenced by llvm::MCStreamer::EmitW64Tables().
void llvm::MCWin64EHUnwindEmitter::EmitUnwindInfo (MCStreamer & streamer, MCWin64EHUnwindInfo * info) static
Definition at line 265 of file MCWin64EH.cpp.
References llvm::EmitUnwindInfo(), llvm::MCWin64EHUnwindInfo::Function, llvm::MCStreamer::getContext(), GetSectionSuffix(), llvm::getWin64EHTableSection(), and llvm::MCStreamer::SwitchSection().
StringRef llvm::MCWin64EHUnwindEmitter::GetSectionSuffix (const MCSymbol * func) static
Definition at line 225 of file MCWin64EH.cpp.
References llvm::StringRef::find(), llvm::MCSymbol::getSection(), llvm::MCSectionCOFF::getSectionName(), llvm::MCSymbol::isInSection(), llvm::StringRef::npos, and llvm::StringRef::substr().
Referenced by Emit(), EmitUnwindInfo(), and getWin64EHTableSection().
The documentation for this class was generated from the following files:
MCWin64EH.h
MCWin64EH.cpp