LLVM: llvm::HexagonMCInst Class Reference
LLVM API Documentation
llvm::HexagonMCInst Class Reference
#include <HexagonMCInst.h>
Public Member Functions
HexagonMCInst ()
HexagonMCInst (const MCInstrDesc &mcid)
bool isPacketStart () const
bool isPacketEnd () const
void setPacketStart (bool Y)
void setPacketEnd (bool Y)
void resetPacket ()
unsigned getUnits (const HexagonTargetMachine *TM) const
unsigned getType () const
void setDesc (const MCInstrDesc &mcid)
const MCInstrDesc & getDesc (void) const
bool isCanon () const
bool isPrefix () const
bool isSolo () const
bool isConstExtended () const
unsigned short getCExtOpNum (void) const
bool isNewValue () const
bool hasNewValue () const
const MCOperand & getNewValue () const
unsigned getBitCount (void) const
Public Member Functions inherited from llvm::MCInst
MCInst ()
void setOpcode (unsigned Op)
unsigned getOpcode () const
void setLoc (SMLoc loc)
SMLoc getLoc () const
const MCOperand & getOperand (unsigned i) const
MCOperand & getOperand (unsigned i)
unsigned getNumOperands () const
void addOperand (const MCOperand &Op)
void clear ()
size_t size ()
iterator begin ()
iterator end ()
iterator insert (iterator I, const MCOperand &Op)
void print (raw_ostream &OS, const MCAsmInfo *MAI) const
void dump () const
void dump_pretty (raw_ostream &OS, const MCAsmInfo *MAI=0, const MCInstPrinter *Printer=0, StringRef Separator=" ") const
Dump the MCInst as prettily as possible using the additional MC structures, if given. Operators are separated by the Separator string.
Additional Inherited Members
Public Types inherited from llvm::MCInst
typedef SmallVectorImpl< MCOperand >::iterator iterator
Detailed Description
Definition at line 23 of file HexagonMCInst.h.
Constructor & Destructor Documentation
llvm::HexagonMCInst::HexagonMCInst () inline explicit
Definition at line 33 of file HexagonMCInst.h.
llvm::HexagonMCInst::HexagonMCInst (const MCInstrDesc & mcid) inline
Definition at line 35 of file HexagonMCInst.h.
Member Function Documentation
unsigned HexagonMCInst::getBitCount (void) const
Definition at line 129 of file HexagonMCInst.cpp.
References llvm::HexagonII::ExtentBitsMask, llvm::HexagonII::ExtentBitsPos, F(), and llvm::MCInstrDesc::TSFlags.
Referenced by getDesc().
unsigned short HexagonMCInst::getCExtOpNum (void) const
Definition at line 135 of file HexagonMCInst.cpp.
References llvm::HexagonII::ExtendableOpMask, llvm::HexagonII::ExtendableOpPos, llvm::HexagonII::ExtentBitsMask, llvm::HexagonII::ExtentBitsPos, llvm::HexagonII::ExtentSignedMask, llvm::HexagonII::ExtentSignedPos, F(), and llvm::MCInstrDesc::TSFlags.
Referenced by getDesc(), and isConstExtended().
const MCInstrDesc& llvm::HexagonMCInst::getDesc (void) const inline
Definition at line 51 of file HexagonMCInst.h.
References getBitCount(), getCExtOpNum(), getNewValue(), hasNewValue(), isCanon(), isConstExtended(), isNewValue(), isPrefix(), and isSolo().
const MCOperand & HexagonMCInst::getNewValue () const
Definition at line 69 of file HexagonMCInst.cpp.
References F(), llvm::MCInst::getOperand(), hasNewValue(), isNewValue(), llvm::MCOperand::isReg(), llvm::HexagonII::NewValueOpMask, llvm::HexagonII::NewValueOpPos, and llvm::MCInstrDesc::TSFlags.
Referenced by getDesc().
unsigned HexagonMCInst::getType () const
Definition at line 32 of file HexagonMCInst.cpp.
References F(), llvm::MCInstrDesc::TSFlags, llvm::HexagonII::TypeMask, and llvm::HexagonII::TypePos.
Referenced by isCanon(), isPrefix(), and resetPacket().
unsigned HexagonMCInst::getUnits (const HexagonTargetMachine * TM) const
Definition at line 22 of file HexagonMCInst.cpp.
References llvm::InstrItineraryData::beginStage(), llvm::HexagonTargetMachine::getInstrInfo(), llvm::HexagonTargetMachine::getInstrItineraryData(), llvm::InstrStage::getUnits(), and this.
Referenced by resetPacket().
bool HexagonMCInst::hasNewValue () const
Definition at line 63 of file HexagonMCInst.cpp.
References F(), llvm::HexagonII::hasNewValueMask, llvm::HexagonII::hasNewValuePos, and llvm::MCInstrDesc::TSFlags.
Referenced by getDesc(), and getNewValue().
bool HexagonMCInst::isCanon () const
Definition at line 39 of file HexagonMCInst.cpp.
References getType(), isPrefix(), llvm::MCInstrDesc::isPseudo(), and llvm::HexagonII::TypeENDLOOP.
Referenced by getDesc().
bool HexagonMCInst::isConstExtended (void) const
Definition at line 87 of file HexagonMCInst.cpp.
References llvm::HexagonII::ExtendableMask, llvm::HexagonII::ExtendablePos, llvm::HexagonII::ExtendedMask, llvm::HexagonII::ExtendedPos, F(), getCExtOpNum(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), and llvm::MCInstrDesc::TSFlags.
Referenced by getDesc(), and llvm::HexagonInstPrinter::printExtOperand().
bool HexagonMCInst::isNewValue () const
Definition at line 57 of file HexagonMCInst.cpp.
References F(), llvm::HexagonII::NewValueMask, llvm::HexagonII::NewValuePos, and llvm::MCInstrDesc::TSFlags.
Referenced by getDesc(), and getNewValue().
bool llvm::HexagonMCInst::isPacketEnd () const inline
Definition at line 39 of file HexagonMCInst.h.
Referenced by llvm::HexagonInstPrinter::printInst().
bool llvm::HexagonMCInst::isPacketStart () const inline
Definition at line 38 of file HexagonMCInst.h.
Referenced by llvm::HexagonInstPrinter::printInst().
bool HexagonMCInst::isPrefix () const
Definition at line 46 of file HexagonMCInst.cpp.
References getType(), and llvm::HexagonII::TypePREFIX.
Referenced by getDesc(), and isCanon().
bool HexagonMCInst::isSolo () const
Definition at line 51 of file HexagonMCInst.cpp.
References F(), llvm::HexagonII::SoloMask, llvm::HexagonII::SoloPos, and llvm::MCInstrDesc::TSFlags.
Referenced by getDesc().
void llvm::HexagonMCInst::resetPacket () inline
Definition at line 42 of file HexagonMCInst.h.
References getType(), getUnits(), setPacketEnd(), setPacketStart(), and llvm::SystemZISD::TM.
void llvm::HexagonMCInst::setDesc (const MCInstrDesc & mcid) inline
Definition at line 50 of file HexagonMCInst.h.
Referenced by llvm::HexagonLowerToMC().
void llvm::HexagonMCInst::setPacketEnd (bool Y) inline
Definition at line 41 of file HexagonMCInst.h.
References Y.
Referenced by llvm::HexagonAsmPrinter::EmitInstruction(), and resetPacket().
void llvm::HexagonMCInst::setPacketStart (bool Y) inline
Definition at line 40 of file HexagonMCInst.h.
References Y.
Referenced by llvm::HexagonAsmPrinter::EmitInstruction(), llvm::HexagonInstPrinter::printInst(), and resetPacket().
The documentation for this class was generated from the following files:
HexagonMCInst.h
HexagonMCInst.cpp