LLVM: llvm::MachineInstrBuilder Class Reference
LLVM API Documentation
llvm::MachineInstrBuilder Class Reference
#include <MachineInstrBuilder.h>
Public Member Functions
MachineInstrBuilder ()
MachineInstrBuilder (MachineFunction &F, MachineInstr *I)
operator MachineInstr * () const
MachineInstr * operator-> () const
operator MachineBasicBlock::iterator () const
const MachineInstrBuilder & addReg (unsigned RegNo, unsigned flags=0, unsigned SubReg=0) const
const MachineInstrBuilder & addImm (int64_t Val) const
const MachineInstrBuilder & addCImm (const ConstantInt *Val) const
const MachineInstrBuilder & addFPImm (const ConstantFP *Val) const
const MachineInstrBuilder & addMBB (MachineBasicBlock *MBB, unsigned char TargetFlags=0) const
const MachineInstrBuilder & addFrameIndex (int Idx) const
const MachineInstrBuilder & addConstantPoolIndex (unsigned Idx, int Offset=0, unsigned char TargetFlags=0) const
const MachineInstrBuilder & addTargetIndex (unsigned Idx, int64_t Offset=0, unsigned char TargetFlags=0) const
const MachineInstrBuilder & addJumpTableIndex (unsigned Idx, unsigned char TargetFlags=0) const
const MachineInstrBuilder & addGlobalAddress (const GlobalValue *GV, int64_t Offset=0, unsigned char TargetFlags=0) const
const MachineInstrBuilder & addExternalSymbol (const char *FnName, unsigned char TargetFlags=0) const
const MachineInstrBuilder & addBlockAddress (const BlockAddress *BA, int64_t Offset=0, unsigned char TargetFlags=0) const
const MachineInstrBuilder & addRegMask (const uint32_t *Mask) const
const MachineInstrBuilder & addMemOperand (MachineMemOperand *MMO) const
const MachineInstrBuilder & setMemRefs (MachineInstr::mmo_iterator b, MachineInstr::mmo_iterator e) const
const MachineInstrBuilder & addOperand (const MachineOperand &MO) const
const MachineInstrBuilder & addMetadata (const MDNode *MD) const
const MachineInstrBuilder & addSym (MCSymbol *Sym) const
const MachineInstrBuilder & setMIFlags (unsigned Flags) const
const MachineInstrBuilder & setMIFlag (MachineInstr::MIFlag Flag) const
const MachineInstrBuilder & addDisp (const MachineOperand &Disp, int64_t off, unsigned char TargetFlags=0) const
const MachineInstrBuilder & copyImplicitOps (const MachineInstr *OtherMI)
Copy all the implicit operands from OtherMI onto this one.
Detailed Description
Definition at line 45 of file MachineInstrBuilder.h.
Constructor & Destructor Documentation
llvm::MachineInstrBuilder::MachineInstrBuilder () inline
Definition at line 49 of file MachineInstrBuilder.h.
llvm::MachineInstrBuilder::MachineInstrBuilder (MachineFunction & F, MachineInstr * I) inline
Create a MachineInstrBuilder for manipulating an existing instruction. F must be the machine function that was used to allocate I.
Definition at line 53 of file MachineInstrBuilder.h.
Member Function Documentation
const MachineInstrBuilder& llvm::MachineInstrBuilder::addBlockAddress (const BlockAddress * BA, int64_t Offset = 0, unsigned char TargetFlags = 0) const inline
Definition at line 142 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateBA().
Referenced by countOperands().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addCImm (const ConstantInt * Val) const inline
Definition at line 88 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateCImm().
Referenced by llvm::InstrEmitter::EmitDbgValue(), and llvm::FastISel::leaveLocalValueArea().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addConstantPoolIndex (unsigned Idx, int Offset = 0, unsigned char TargetFlags = 0) const inline
Definition at line 109 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateCPI().
Referenced by llvm::addConstantPoolReference(), countOperands(), llvm::createARMConstantIslandPass(), llvm::createMipsConstantIslandPass(), emitPostSt(), getComparePred(), getUnconditionalBrDisp(), llvm::ARMBaseInstrInfo::reMaterialize(), and llvm::ARMTargetLowering::ReplaceNodeResults().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addDisp (const MachineOperand & Disp, int64_t off, unsigned char TargetFlags = 0) const inline
Definition at line 192 of file MachineInstrBuilder.h.
References llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getOffset(), llvm::MachineOperand::getTargetFlags(), llvm::MachineOperand::getType(), llvm_unreachable, llvm::MachineOperand::MO_GlobalAddress, and llvm::MachineOperand::MO_Immediate.
Referenced by checkAndUpdateEFLAGSKill(), EmitMonitor(), and getPseudoCMOVOpc().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addExternalSymbol (const char * FnName, unsigned char TargetFlags = 0) const inline
Definition at line 136 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateES().
Referenced by computeBytesPoppedByCallee(), countOperands(), llvm::InstrEmitter::EmitDbgValue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitEpilogue(), emitGPDisp(), getComparePred(), and llvm::X86InstrInfo::hasHighOperandLatency().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addFPImm (const ConstantFP * Val) const inline
Definition at line 93 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateFPImm().
Referenced by countOperands(), llvm::InstrEmitter::EmitDbgValue(), llvm::FastISel::FastEmitInst_rf(), and llvm::FastISel::leaveLocalValueArea().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addFrameIndex (int Idx) const inline
Definition at line 104 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateFI().
Referenced by llvm::addFrameReference(), llvm::addFullAddress(), countOperands(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::AArch64FrameLowering::emitFrameMemOps(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), getComparePred(), llvm::Mips16InstrInfo::loadRegFromStack(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), llvm::ARMTargetLowering::ReplaceNodeResults(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), and llvm::ARMBaseInstrInfo::storeRegToStackSlot().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addGlobalAddress (const GlobalValue * GV, int64_t Offset = 0, unsigned char TargetFlags = 0) const inline
Definition at line 129 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateGA().
Referenced by llvm::addFullAddress(), checkAndUpdateEFLAGSKill(), computeBytesPoppedByCallee(), countOperands(), llvm::ARMFrameLowering::emitEpilogue(), llvm::X86FrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitEpilogue(), getComparePred(), GetDSubRegs(), and isUnsafeToMoveAcross().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addImm (int64_t Val) const inline
addImm - Add a new immediate operand.
Definition at line 83 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateImm().
Referenced by llvm::addConstantPoolReference(), llvm::AddDefaultPred(), llvm::addDirectMem(), llvm::addFrameReference(), llvm::addFullAddress(), llvm::addOffset(), llvm::addRegReg(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::MipsSEInstrInfo::adjustStackPtr(), llvm::MipsInstrInfo::AnalyzeBranch(), llvm::Mips16InstrInfo::basicLoadImmediate(), llvm::ARMBaseInstrInfo::breakPartialRegDependency(), llvm::Mips16InstrInfo::BuildAddiuSpImm(), llvm::R600InstrInfo::buildDefaultInstruction(), llvm::SIInstrInfo::buildIndirectRead(), llvm::SIInstrInfo::buildIndirectWrite(), llvm::BuildMI(), checkAndUpdateEFLAGSKill(), llvm::X86InstrInfo::classifyLEAReg(), CompareMBBNumbers(), computeBytesPoppedByCallee(), concatenateMemOperands(), llvm::ARMBaseInstrInfo::convertToThreeAddress(), llvm::SystemZInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::AArch64InstrInfo::copyPhysReg(), llvm::MipsSEInstrInfo::copyPhysReg(), llvm::XCoreInstrInfo::copyPhysReg(), llvm::HexagonInstrInfo::copyPhysReg(), countOperands(), llvm::createARMConstantIslandPass(), llvm::createHexagonHardwareLoops(), llvm::createMipsConstantIslandPass(), llvm::createSILowerControlFlowPass(), llvm::createSystemZLongBranchPass(), dumpMachineInstrRangeWithSlotIndex(), llvm::MSP430FrameLowering::eliminateCallFramePseudoInstr(), llvm::PPCFrameLowering::eliminateCallFramePseudoInstr(), llvm::X86FrameLowering::eliminateCallFramePseudoInstr(), llvm::MSP430RegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), llvm::PPCRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), llvm::emitARMRegPlusImmediate(), llvm::AArch64TargetLowering::emitAtomicBinary(), llvm::AArch64TargetLowering::emitAtomicBinaryMinMax(), llvm::AArch64TargetLowering::emitAtomicCmpSwap(), llvm::InstrEmitter::EmitDbgValue(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::MSP430FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::AArch64FrameLowering::emitFrameMemOps(), emitIncrement(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::SparcTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::Thumb2RegisterInfo::emitLoadConstPool(), llvm::Thumb1RegisterInfo::emitLoadConstPool(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), EmitMonitor(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), emitPostLd(), emitPostSt(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::MSP430FrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::emitRegUpdate(), llvm::MSP430TargetLowering::EmitShiftInstr(), emitSPUpdate(), llvm::emitT2RegPlusImmediate(), emitThumbConstant(), llvm::emitThumbRegPlusImmediate(), emitThumbRegPlusImmInReg(), expandPseudoDIV(), llvm::FastISel::FastEmitInst_i(), llvm::FastISel::FastEmitInst_ii(), llvm::FastISel::FastEmitInst_ri(), llvm::FastISel::FastEmitInst_rii(), llvm::FastISel::FastEmitInst_rri(), llvm::FastISel::FastEmitInst_rrii(), findInsertLocation(), llvm::ARMBaseInstrInfo::FoldImmediate(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), forceReg(), getComparePred(), GetDSubRegs(), llvm::ARMFrameLowering::getFrameIndexOffset(), getNonDebugInstr(), getPostIndexedLoadStoreOpcode(), getPseudoCMOVOpc(), getTruncatedArgReg(), getUnconditionalBrDisp(), llvm::ARMInstrInfo::getUnindexedOpcode(), HandleVRSaveUpdate(), INITIALIZE_PASS(), llvm::ARMBaseInstrInfo::InsertBranch(), llvm::SparcInstrInfo::InsertBranch(), llvm::MSP430InstrInfo::InsertBranch(), llvm::PPCInstrInfo::InsertBranch(), llvm::SystemZInstrInfo::InsertBranch(), InsertLDR_STR(), isCopy(), isFpMulInstruction(), isi32Store(), isMSALoadOrStore(), isUnsafeToMoveAcross(), llvm::FastISel::leaveLocalValueArea(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::Mips16InstrInfo::loadImmediate(), llvm::SystemZInstrInfo::loadImmediate(), llvm::Mips16InstrInfo::loadRegFromStack(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::XCoreInstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::PPCRegisterInfo::lowerCRRestore(), llvm::PPCRegisterInfo::lowerCRSpilling(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), lowerVECTOR_SHUFFLE_VSHF(), llvm::Mips16InstrInfo::makeFrame(), MakeM0Inst(), llvm::PPCRegisterInfo::materializeFrameBaseRegister(), Mips16WhichOp8uOr16simm(), llvm::ARMBaseInstrInfo::optimizeSelect(), llvm::SystemZInstrInfo::PredicateInstruction(), llvm::ARMBaseInstrInfo::reMaterialize(), replaceFI(), llvm::ARMTargetLowering::ReplaceNodeResults(), llvm::SystemZFrameLowering::restoreCalleeSavedRegisters(), llvm::Mips16InstrInfo::restoreFrame(), llvm::ARMBaseInstrInfo::setExecutionDomain(), llvm::SystemZFrameLowering::spillCalleeSavedRegisters(), llvm::Mips16InstrInfo::storeRegToStack(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), storeToStack(), llvm::SystemZInstrInfo::SystemZInstrInfo(), VerifyLowRegs(), and X86ChooseCmpImmediateOpcode().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addJumpTableIndex (unsigned Idx, unsigned char TargetFlags = 0) const inline
Definition at line 123 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateJTI().
Referenced by countOperands(), and llvm::ARMTargetLowering::ReplaceNodeResults().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addMBB (MachineBasicBlock * MBB, unsigned char TargetFlags = 0) const inline
Definition at line 98 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateMBB().
Referenced by llvm::SSAUpdaterTraits< MachineSSAUpdater >::AddPHIOperand(), llvm::MipsInstrInfo::AnalyzeBranch(), llvm::SparcInstrInfo::AnalyzeBranch(), llvm::X86InstrInfo::AnalyzeBranch(), checkAndUpdateEFLAGSKill(), countOperands(), llvm::AArch64TargetLowering::emitAtomicBinary(), llvm::PPCTargetLowering::EmitAtomicBinary(), llvm::AArch64TargetLowering::emitAtomicBinaryMinMax(), llvm::AArch64TargetLowering::emitAtomicCmpSwap(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::AArch64TargetLowering::EmitF128CSEL(), llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), EmitMonitor(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), emitPostSt(), llvm::MSP430TargetLowering::EmitShiftInstr(), FindSplitPointForStackProtector(), forceReg(), getComparePred(), getNewValueJumpOpcode(), getNonDebugInstr(), getPseudoCMOVOpc(), getUnconditionalBrDisp(), llvm::MachineSSAUpdater::GetValueInMiddleOfBlock(), llvm::MipsInstrInfo::InsertBranch(), llvm::XCoreInstrInfo::InsertBranch(), llvm::AArch64InstrInfo::InsertBranch(), llvm::ARMBaseInstrInfo::InsertBranch(), llvm::HexagonInstrInfo::InsertBranch(), llvm::NVPTXInstrInfo::InsertBranch(), llvm::SparcInstrInfo::InsertBranch(), llvm::MSP430InstrInfo::InsertBranch(), llvm::PPCInstrInfo::InsertBranch(), llvm::SystemZInstrInfo::InsertBranch(), llvm::R600InstrInfo::InsertBranch(), llvm::X86InstrInfo::InsertBranch(), and lowerVECTOR_SHUFFLE_VSHF().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addMemOperand (MachineMemOperand * MMO) const inline
Definition at line 154 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addMemOperand().
Referenced by llvm::addFrameReference(), llvm::AArch64FrameLowering::emitFrameMemOps(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), getComparePred(), getPseudoCMOVOpc(), llvm::Mips16InstrInfo::loadRegFromStack(), llvm::MipsSEInstrInfo::loadRegFromStack(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::HexagonInstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::ARMTargetLowering::ReplaceNodeResults(), llvm::Mips16InstrInfo::storeRegToStack(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), and llvm::ARMBaseInstrInfo::storeRegToStackSlot().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addMetadata (const MDNode * MD) const inline
Definition at line 171 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateMetadata().
Referenced by llvm::BuildMI(), dumpMachineInstrRangeWithSlotIndex(), llvm::InstrEmitter::EmitDbgValue(), findInsertLocation(), getTruncatedArgReg(), llvm::FastISel::leaveLocalValueArea(), and X86ChooseCmpImmediateOpcode().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addOperand (const MachineOperand & MO) const inline
Definition at line 166 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand().
Referenced by BBHasFallthrough(), llvm::SIInstrInfo::buildIndirectRead(), llvm::SIInstrInfo::buildIndirectWrite(), checkAndUpdateEFLAGSKill(), llvm::X86InstrInfo::classifyLEAReg(), llvm::SystemZInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::createMSP430BranchSelectionPass(), llvm::createSILowerControlFlowPass(), llvm::createSystemZLongBranchPass(), llvm::X86FrameLowering::emitEpilogue(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), EmitMonitor(), EmitPCMPSTRI(), EmitPCMPSTRM(), llvm::AArch64InstrInfo::expandPostRAPseudo(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), foldPatchpoint(), forceReg(), FuseInst(), FuseTwoAddrInst(), llvm::MipsInstrInfo::genInstrWithNewOpc(), GetDSubRegs(), getPseudoCMOVOpc(), getUpdatingLSMultipleOpcode(), llvm::AArch64InstrInfo::InsertBranch(), isCompareZero(), llvm::SIInstrInfo::legalizeOperands(), llvm::SIInstrInfo::legalizeOpWithMove(), llvm::X86InstrInfo::loadRegFromAddr(), MakeM0Inst(), llvm::ARMBaseInstrInfo::optimizeSelect(), regsAreCompatible(), llvm::X86InstrInfo::reMaterialize(), llvm::X86InstrInfo::storeRegToAddr(), llvm::tryFoldSPUpdateIntoPushPop(), llvm::X86InstrInfo::unfoldMemoryOperand(), and VerifyLowRegs().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addReg (unsigned RegNo, unsigned flags = 0, unsigned SubReg = 0) const inline
addReg - Add a new virtual register operand...
Definition at line 64 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), llvm::MachineOperand::CreateReg(), llvm::RegState::Dead, llvm::RegState::Debug, llvm::RegState::Define, llvm::RegState::EarlyClobber, llvm::RegState::Implicit, llvm::RegState::InternalRead, llvm::RegState::Kill, and llvm::RegState::Undef.
Referenced by llvm::addConstantPoolReference(), llvm::AddDefaultCC(), llvm::AddDefaultPred(), llvm::AddDefaultT1CC(), llvm::addDirectMem(), llvm::ARMBaseInstrInfo::AddDReg(), llvm::addFrameReference(), llvm::addFullAddress(), llvm::AddNoT1CC(), llvm::addOffset(), llvm::addRegOffset(), llvm::addRegReg(), addSavedGPR(), llvm::X86FrameLowering::adjustForSegmentedStacks(), llvm::MipsSEInstrInfo::adjustStackPtr(), llvm::MipsInstrInfo::AnalyzeBranch(), llvm::X86InstrInfo::breakPartialRegDependency(), llvm::R600InstrInfo::buildDefaultInstruction(), llvm::SIInstrInfo::buildIndirectRead(), llvm::R600InstrInfo::buildIndirectRead(), llvm::SIInstrInfo::buildIndirectWrite(), llvm::R600InstrInfo::buildIndirectWrite(), llvm::BuildMI(), llvm::SIInstrInfo::buildMovInstr(), checkAndUpdateEFLAGSKill(), llvm::X86InstrInfo::classifyLEAReg(), CompareMBBNumbers(), computeBytesPoppedByCallee(), concatenateMemOperands(), llvm::ARMBaseInstrInfo::convertToThreeAddress(), llvm::SystemZInstrInfo::convertToThreeAddress(), llvm::X86InstrInfo::convertToThreeAddress(), llvm::AArch64InstrInfo::copyPhysReg(), llvm::SIInstrInfo::copyPhysReg(), llvm::Mips16InstrInfo::copyPhysReg(), llvm::MipsSEInstrInfo::copyPhysReg(), llvm::NVPTXInstrInfo::copyPhysReg(), llvm::MSP430InstrInfo::copyPhysReg(), llvm::XCoreInstrInfo::copyPhysReg(), llvm::HexagonInstrInfo::copyPhysReg(), llvm::SparcInstrInfo::copyPhysReg(), llvm::ARMBaseInstrInfo::copyPhysReg(), llvm::PPCInstrInfo::copyPhysReg(), llvm::SystemZInstrInfo::copyPhysReg(), llvm::X86InstrInfo::copyPhysReg(), countOperands(), llvm::createHexagonHardwareLoops(), llvm::createSILowerControlFlowPass(), llvm::PPCFrameLowering::eliminateCallFramePseudoInstr(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::XCoreRegisterInfo::eliminateFrameIndex(), llvm::HexagonRegisterInfo::eliminateFrameIndex(), llvm::SystemZRegisterInfo::eliminateFrameIndex(), emitAlignedDPRCS2Restores(), emitAlignedDPRCS2Spills(), llvm::emitARMRegPlusImmediate(), llvm::AArch64TargetLowering::emitAtomicBinary(), llvm::PPCTargetLowering::EmitAtomicBinary(), llvm::AArch64TargetLowering::emitAtomicBinaryMinMax(), llvm::AArch64TargetLowering::emitAtomicCmpSwap(), llvm::InstrEmitter::EmitDbgValue(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), llvm::MipsSEFrameLowering::emitEpilogue(), llvm::HexagonFrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitEpilogue(), llvm::Thumb1FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::emitEpilogue(), llvm::PPCFrameLowering::emitEpilogue(), llvm::AArch64FrameLowering::emitEpilogue(), llvm::R600TargetLowering::EmitInstrWithCustomInserter(), llvm::SITargetLowering::EmitInstrWithCustomInserter(), llvm::SparcTargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::Thumb2RegisterInfo::emitLoadConstPool(), llvm::Thumb1RegisterInfo::emitLoadConstPool(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), EmitMonitor(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), emitPostLd(), emitPostSt(), llvm::MipsSEFrameLowering::emitPrologue(), llvm::ARMFrameLowering::emitPrologue(), llvm::PPCFrameLowering::emitPrologue(), llvm::X86FrameLowering::emitPrologue(), llvm::emitRegUpdate(), llvm::MSP430TargetLowering::EmitShiftInstr(), llvm::emitT2RegPlusImmediate(), llvm::emitThumbRegPlusImmediate(), emitThumbRegPlusImmInReg(), Expand2AddrUndef(), expandPseudoDIV(), llvm::FastISel::FastEmitInst_r(), llvm::FastISel::FastEmitInst_rf(), llvm::FastISel::FastEmitInst_ri(), llvm::FastISel::FastEmitInst_rii(), llvm::FastISel::FastEmitInst_rr(), llvm::FastISel::FastEmitInst_rri(), llvm::FastISel::FastEmitInst_rrii(), llvm::FastISel::FastEmitInst_rrr(), llvm::finalizeBundle(), FindSplitPointForStackProtector(), llvm::ARMBaseInstrInfo::FoldImmediate(), llvm::SystemZInstrInfo::foldMemoryOperandImpl(), forceReg(), getComparePred(), GetDSubRegs(), llvm::ARMFrameLowering::getFrameIndexOffset(), getNonDebugInstr(), getPostIndexedLoadStoreOpcode(), getPseudoCMOVOpc(), getUnconditionalBrDisp(), getUpdatingLSMultipleOpcode(), llvm::MachineSSAUpdater::GetValueInMiddleOfBlock(), INITIALIZE_PASS(), llvm::XCoreInstrInfo::InsertBranch(), llvm::ARMBaseInstrInfo::InsertBranch(), llvm::HexagonInstrInfo::InsertBranch(), llvm::NVPTXInstrInfo::InsertBranch(), llvm::PPCInstrInfo::InsertBranch(), llvm::R600InstrInfo::InsertBranch(), InsertLDR_STR(), llvm::PPCInstrInfo::insertSelect(), llvm::X86InstrInfo::insertSelect(), isCompareZero(), isFpMulInstruction(), isi32Store(), isMSALoadOrStore(), isUnsafeToMoveAcross(), llvm::FastISel::leaveLocalValueArea(), llvm::MipsSEInstrInfo::loadImmediate(), llvm::Mips16InstrInfo::loadImmediate(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::PPCRegisterInfo::lowerDynamicAlloc(), lowerVECTOR_SHUFFLE_VSHF(), llvm::Mips16InstrInfo::makeFrame(), Mips16WhichOp8uOr16simm(), llvm::PPCInstrInfo::optimizeCompareInstr(), llvm::SystemZInstrInfo::PredicateInstruction(), llvm::R600InstrInfo::PredicateInstruction(), replaceFI(), llvm::ARMTargetLowering::ReplaceNodeResults(), llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters(), llvm::SystemZFrameLowering::restoreCalleeSavedRegisters(), llvm::Mips16InstrInfo::restoreFrame(), resultTests(), llvm::Thumb1RegisterInfo::saveScavengerRegister(), llvm::ARMBaseInstrInfo::setExecutionDomain(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), llvm::SystemZFrameLowering::spillCalleeSavedRegisters(), llvm::PPCFrameLowering::spillCalleeSavedRegisters(), llvm::X86InstrInfo::storeRegToAddr(), llvm::Mips16InstrInfo::storeRegToStack(), llvm::MipsSEInstrInfo::storeRegToStack(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::XCoreInstrInfo::storeRegToStackSlot(), llvm::HexagonInstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::X86InstrInfo::storeRegToStackSlot(), llvm::SystemZInstrInfo::SystemZInstrInfo(), llvm::X86InstrInfo::unfoldMemoryOperand(), UpdatePredRedefs(), VerifyLowRegs(), and X86ChooseCmpImmediateOpcode().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addRegMask (const uint32_t * Mask) const inline
Definition at line 149 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateRegMask().
Referenced by checkAndUpdateEFLAGSKill(), computeBytesPoppedByCallee(), countOperands(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), getComparePred(), and llvm::ARMTargetLowering::ReplaceNodeResults().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addSym (MCSymbol * Sym) const inline
Definition at line 176 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateMCSymbol().
const MachineInstrBuilder& llvm::MachineInstrBuilder::addTargetIndex (unsigned Idx, int64_t Offset = 0, unsigned char TargetFlags = 0) const inline
Definition at line 116 of file MachineInstrBuilder.h.
References llvm::MachineInstr::addOperand(), and llvm::MachineOperand::CreateTargetIndex().
Referenced by countOperands().
const MachineInstrBuilder& llvm::MachineInstrBuilder::copyImplicitOps (const MachineInstr * OtherMI) inline
Copy all the implicit operands from OtherMI onto this one.
Definition at line 214 of file MachineInstrBuilder.h.
References llvm::MachineInstr::copyImplicitOps().
Referenced by llvm::Thumb1FrameLowering::emitEpilogue(), llvm::ARMFrameLowering::getFrameIndexOffset(), and llvm::Thumb1FrameLowering::restoreCalleeSavedRegisters().
llvm::MachineInstrBuilder::operator MachineBasicBlock::iterator () const inline
Definition at line 59 of file MachineInstrBuilder.h.
References llvm::A64CC::MI.
llvm::MachineInstrBuilder::operator MachineInstr * () const inline
Allow automatic conversion to the machine instruction we are working on.
Definition at line 57 of file MachineInstrBuilder.h.
References llvm::A64CC::MI.
MachineInstr* llvm::MachineInstrBuilder::operator-> () const inline
Definition at line 58 of file MachineInstrBuilder.h.
References llvm::A64CC::MI.
const MachineInstrBuilder& llvm::MachineInstrBuilder::setMemRefs (MachineInstr::mmo_iterator b, MachineInstr::mmo_iterator e) const inline
Definition at line 159 of file MachineInstrBuilder.h.
References llvm::MachineInstr::setMemRefs().
Referenced by checkAndUpdateEFLAGSKill(), llvm::PPCTargetLowering::emitEHSjLjLongJmp(), llvm::PPCTargetLowering::emitEHSjLjSetJmp(), EmitMonitor(), llvm::MipsInstrInfo::genInstrWithNewOpc(), GetDSubRegs(), getPseudoCMOVOpc(), llvm::X86InstrInfo::loadRegFromAddr(), and llvm::X86InstrInfo::storeRegToAddr().
const MachineInstrBuilder& llvm::MachineInstrBuilder::setMIFlag (MachineInstr::MIFlag Flag) const inline
Definition at line 186 of file MachineInstrBuilder.h.
References llvm::MachineInstr::setFlag().
Referenced by llvm::X86FrameLowering::emitPrologue(), llvm::emitRegUpdate(), and llvm::X86FrameLowering::spillCalleeSavedRegisters().
const MachineInstrBuilder& llvm::MachineInstrBuilder::setMIFlags (unsigned Flags) const inline
Definition at line 181 of file MachineInstrBuilder.h.
References llvm::MachineInstr::setFlags().
Referenced by llvm::emitARMRegPlusImmediate(), llvm::AArch64FrameLowering::emitFrameMemOps(), llvm::Thumb2RegisterInfo::emitLoadConstPool(), llvm::Thumb1RegisterInfo::emitLoadConstPool(), llvm::ARMBaseRegisterInfo::emitLoadConstPool(), llvm::Thumb1FrameLowering::emitPrologue(), llvm::emitRegUpdate(), llvm::emitT2RegPlusImmediate(), llvm::emitThumbRegPlusImmediate(), emitThumbRegPlusImmInReg(), llvm::ARMFrameLowering::getFrameIndexOffset(), llvm::Thumb1FrameLowering::spillCalleeSavedRegisters(), and VerifyLowRegs().
The documentation for this class was generated from the following file:
MachineInstrBuilder.h