LLVM: llvm::MCBasicBlock Class Reference
LLVM API Documentation
llvm::MCBasicBlock Class Reference
Basic block containing a sequence of disassembled instructions. The basic block is backed by an MCTextAtom, which holds the instructions, and the address range it covers. Create a basic block using MCFunction::createBlock.
#include <MCFunction.h>
Public Member Functions
const MCTextAtom * getInsts () const
Get the backing MCTextAtom, containing the instruction sequence.
Get the owning MCFunction.
const MCFunction * getParent () const
MCFunction * getParent ()
Friends
class MCFunction
typedef BasicBlockListTy::const_iterator succ_const_iterator
typedef BasicBlockListTy::const_iterator pred_const_iterator
succ_const_iterator succ_begin () const
succ_const_iterator succ_end () const
pred_const_iterator pred_begin () const
pred_const_iterator pred_end () const
void addSuccessor (const MCBasicBlock *MCBB)
bool isSuccessor (const MCBasicBlock *MCBB) const
void addPredecessor (const MCBasicBlock *MCBB)
bool isPredecessor (const MCBasicBlock *MCBB) const
void splitBasicBlock (MCBasicBlock *SplitBB)
Split block, mirrorring NewAtom = Insts->split(..). This moves all successors to SplitBB, and adds a fallthrough to it. SplitBB The result of splitting Insts, a basic block directly following this basic block.
Detailed Description
Basic block containing a sequence of disassembled instructions. The basic block is backed by an MCTextAtom, which holds the instructions, and the address range it covers. Create a basic block using MCFunction::createBlock.
Definition at line 33 of file MCFunction.h.
Member Typedef Documentation
typedef BasicBlockListTy::const_iterator llvm::MCBasicBlock::pred_const_iterator
Definition at line 64 of file MCFunction.h.
typedef BasicBlockListTy::const_iterator llvm::MCBasicBlock::succ_const_iterator
MC CFG access: Predecessors/Successors.
Definition at line 60 of file MCFunction.h.
Member Function Documentation
void MCBasicBlock::addPredecessor (const MCBasicBlock * MCBB)
Definition at line 62 of file MCFunction.cpp.
Referenced by llvm::yaml::ScalarTraits< MCModuleYAML::OpcodeEnum >::input(), pred_end(), RemoveDupsFromAddressVector(), and splitBasicBlock().
void MCBasicBlock::addSuccessor (const MCBasicBlock * MCBB)
Definition at line 52 of file MCFunction.cpp.
Referenced by llvm::yaml::ScalarTraits< MCModuleYAML::OpcodeEnum >::input(), pred_end(), and RemoveDupsFromAddressVector().
const MCTextAtom* llvm::MCBasicBlock::getInsts () const inline
Get the backing MCTextAtom, containing the instruction sequence.
Definition at line 50 of file MCFunction.h.
Referenced by CompBBToAtom(), and llvm::yaml::ScalarTraits< MCModuleYAML::OpcodeEnum >::input().
const MCFunction* llvm::MCBasicBlock::getParent () const inline
Definition at line 54 of file MCFunction.h.
Referenced by CompBBToAtom().
MCFunction* llvm::MCBasicBlock::getParent () inline
Definition at line 55 of file MCFunction.h.
bool MCBasicBlock::isPredecessor (const MCBasicBlock * MCBB) const
Definition at line 67 of file MCFunction.cpp.
Referenced by pred_end().
bool MCBasicBlock::isSuccessor (const MCBasicBlock * MCBB) const
Definition at line 57 of file MCFunction.cpp.
Referenced by pred_end().
pred_const_iterator llvm::MCBasicBlock::pred_begin () const inline
Definition at line 65 of file MCFunction.h.
Referenced by llvm::yaml::ScalarTraits< MCModuleYAML::OpcodeEnum >::input().
pred_const_iterator llvm::MCBasicBlock::pred_end () const inline
Definition at line 66 of file MCFunction.h.
References addPredecessor(), addSuccessor(), isPredecessor(), isSuccessor(), and splitBasicBlock().
Referenced by llvm::yaml::ScalarTraits< MCModuleYAML::OpcodeEnum >::input().
void MCBasicBlock::splitBasicBlock (MCBasicBlock * SplitBB)
Split block, mirrorring NewAtom = Insts->split(..). This moves all successors to SplitBB, and adds a fallthrough to it. SplitBB The result of splitting Insts, a basic block directly following this basic block.
Definition at line 72 of file MCFunction.cpp.
References addPredecessor(), llvm::MCAtom::getBeginAddr(), and llvm::MCAtom::getEndAddr().
Referenced by CompBBToAtom(), and pred_end().
succ_const_iterator llvm::MCBasicBlock::succ_begin () const inline
Definition at line 61 of file MCFunction.h.
Referenced by llvm::yaml::ScalarTraits< MCModuleYAML::OpcodeEnum >::input().
succ_const_iterator llvm::MCBasicBlock::succ_end () const inline
Definition at line 62 of file MCFunction.h.
Referenced by llvm::yaml::ScalarTraits< MCModuleYAML::OpcodeEnum >::input().
Friends And Related Function Documentation
friend class MCFunction friend
Definition at line 38 of file MCFunction.h.
The documentation for this class was generated from the following files:
MCFunction.h
MCFunction.cpp