LLVM: llvm::SCEVConstant Class Reference
LLVM API Documentation
llvm::SCEVConstant Class Reference
#include <ScalarEvolutionExpressions.h>
Public Member Functions
ConstantInt * getValue () const
Type * getType () const
Public Member Functions inherited from llvm::SCEV
SCEV (const FoldingSetNodeIDRef ID, unsigned SCEVTy)
unsigned getSCEVType () const
Type * getType () const
bool isZero () const
bool isOne () const
bool isAllOnesValue () const
bool isNonConstantNegative () const
void print (raw_ostream &OS) const
void dump () const
Public Member Functions inherited from llvm::FoldingSetImpl::Node
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Static Public Member Functions
static bool classof (const SCEV *S)
Methods for support type inquiry through isa, cast, and dyn_cast:
Friends
class ScalarEvolution
Additional Inherited Members
Public Types inherited from llvm::SCEV
enum NoWrapFlags {
FlagAnyWrap = 0, FlagNW = (1 << 0), FlagNUW = (1 << 1), FlagNSW = (1 << 2),
NoWrapMask = (1 << 3) -1
}
Protected Attributes inherited from llvm::SCEV
unsigned short SubclassData
Detailed Description
SCEVConstant - This class represents a constant integer value.
Definition at line 37 of file ScalarEvolutionExpressions.h.
Member Function Documentation
static bool llvm::SCEVConstant::classof (const SCEV * S) inline static
Methods for support type inquiry through isa, cast, and dyn_cast:
Definition at line 49 of file ScalarEvolutionExpressions.h.
References llvm::SCEV::getSCEVType(), and llvm::scConstant.
Type* llvm::SCEVConstant::getType () const inline
Definition at line 46 of file ScalarEvolutionExpressions.h.
References llvm::ConstantInt::getType().
Referenced by CollectSubexprs().
ConstantInt* llvm::SCEVConstant::getValue () const inline
Definition at line 44 of file ScalarEvolutionExpressions.h.
Referenced by areAllUsesIn(), canFoldIVIncExpr(), CollectSubexprs(), deleteIfDeadInstruction(), FactorOutConstant(), gcd(), getConstantPart(), getExactSDiv(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), getPointerOperand(), llvm::ScalarEvolution::getSmallConstantTripCount(), llvm::ScalarEvolution::getSmallConstantTripMultiple(), isLikelyComplexAddressComputation(), llvm::SCEV::isNonConstantNegative(), llvm::SCEVUnknown::isOffsetOf(), isRemainderZero(), llvm::FullDependence::isSplitable(), isStridedPtr(), minAPInt(), llvm::SCEVExpander::replaceCongruentIVs(), sdiv(), llvm::SCEVExpander::setChainedPhi(), SolveQuadraticEquation(), and srem().
Friends And Related Function Documentation
friend class ScalarEvolution friend
Definition at line 38 of file ScalarEvolutionExpressions.h.
The documentation for this class was generated from the following file:
ScalarEvolutionExpressions.h