LLVM: llvm::DWARFAbbreviationDeclaration Class Reference
LLVM API Documentation
llvm::DWARFAbbreviationDeclaration Class Reference
#include <DWARFAbbreviationDeclaration.h>
Public Member Functions
DWARFAbbreviationDeclaration ()
uint32_t getCode () const
uint32_t getTag () const
bool hasChildren () const
uint32_t getNumAttributes () const
uint16_t getAttrByIndex (uint32_t idx) const
uint16_t getFormByIndex (uint32_t idx) const
uint32_t findAttributeIndex (uint16_t attr) const
bool extract (DataExtractor Data, uint32_t *OffsetPtr)
void dump (raw_ostream &OS) const
Detailed Description
Definition at line 20 of file DWARFAbbreviationDeclaration.h.
Constructor & Destructor Documentation
DWARFAbbreviationDeclaration::DWARFAbbreviationDeclaration ()
Definition at line 24 of file DWARFAbbreviationDeclaration.cpp.
Member Function Documentation
void DWARFAbbreviationDeclaration::dump (raw_ostream & OS) const
Definition at line 64 of file DWARFAbbreviationDeclaration.cpp.
References llvm::dwarf::AttributeString(), llvm::format(), llvm::dwarf::FormEncodingString(), i, and llvm::dwarf::TagString().
Referenced by getFormByIndex().
bool DWARFAbbreviationDeclaration::extract (DataExtractor Data, uint32_t * OffsetPtr)
Definition at line 29 of file DWARFAbbreviationDeclaration.cpp.
References llvm::tgtok::Code, llvm::dwarf::DW_CHILDREN_yes, llvm::DataExtractor::getU8(), and llvm::DataExtractor::getULEB128().
Referenced by llvm::DWARFAbbreviationDeclarationSet::extract(), and getFormByIndex().
uint32_t DWARFAbbreviationDeclaration::findAttributeIndex (uint16_t attr) const
Definition at line 91 of file DWARFAbbreviationDeclaration.cpp.
References i.
Referenced by getFormByIndex().
uint16_t llvm::DWARFAbbreviationDeclaration::getAttrByIndex (uint32_t idx) const inline
Definition at line 38 of file DWARFAbbreviationDeclaration.h.
References llvm::SmallVectorTemplateCommon< T, typename >::size().
uint32_t llvm::DWARFAbbreviationDeclaration::getCode () const inline
Definition at line 34 of file DWARFAbbreviationDeclaration.h.
Referenced by llvm::DWARFAbbreviationDeclarationSet::extract().
uint16_t llvm::DWARFAbbreviationDeclaration::getFormByIndex (uint32_t idx) const inline
Definition at line 41 of file DWARFAbbreviationDeclaration.h.
References dump(), extract(), findAttributeIndex(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
uint32_t llvm::DWARFAbbreviationDeclaration::getNumAttributes () const inline
Definition at line 37 of file DWARFAbbreviationDeclaration.h.
References llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::DWARFDebugInfoEntryMinimal::getNumAttributes().
uint32_t llvm::DWARFAbbreviationDeclaration::getTag () const inline
Definition at line 35 of file DWARFAbbreviationDeclaration.h.
Referenced by llvm::DWARFDebugInfoEntryMinimal::getTag().
bool llvm::DWARFAbbreviationDeclaration::hasChildren () const inline
Definition at line 36 of file DWARFAbbreviationDeclaration.h.
Referenced by llvm::DWARFUnit::getDWOId(), and llvm::DWARFDebugInfoEntryMinimal::hasChildren().
The documentation for this class was generated from the following files:
DWARFAbbreviationDeclaration.h
DWARFAbbreviationDeclaration.cpp