LLVM: llvm::ArrayType Class Reference
LLVM API Documentation
llvm::ArrayType Class Reference
#include <DerivedTypes.h>
Public Member Functions
uint64_t getNumElements () const
Public Member Functions inherited from llvm::SequentialType
Type * getElementType () const
Public Member Functions inherited from llvm::CompositeType
Type * getTypeAtIndex (const Value *V)
Type * getTypeAtIndex (unsigned Idx)
bool indexValid (const Value *V) const
bool indexValid (unsigned Idx) const
Public Member Functions inherited from llvm::Type
void print (raw_ostream &O) const
void dump () const
LLVMContext & getContext () const
getContext - Return the LLVMContext in which this type was uniqued.
TypeID getTypeID () const
bool isVoidTy () const
isVoidTy - Return true if this is 'void'.
bool isHalfTy () const
isHalfTy - Return true if this is 'half', a 16-bit IEEE fp type.
bool isFloatTy () const
isFloatTy - Return true if this is 'float', a 32-bit IEEE fp type.
bool isDoubleTy () const
isDoubleTy - Return true if this is 'double', a 64-bit IEEE fp type.
bool isX86_FP80Ty () const
isX86_FP80Ty - Return true if this is x86 long double.
bool isFP128Ty () const
isFP128Ty - Return true if this is 'fp128'.
bool isPPC_FP128Ty () const
isPPC_FP128Ty - Return true if this is powerpc long double.
bool isFloatingPointTy () const
const fltSemantics & getFltSemantics () const
bool isX86_MMXTy () const
isX86_MMXTy - Return true if this is X86 MMX.
bool isFPOrFPVectorTy () const
bool isLabelTy () const
isLabelTy - Return true if this is 'label'.
bool isMetadataTy () const
isMetadataTy - Return true if this is 'metadata'.
bool isIntegerTy () const
bool isIntegerTy (unsigned Bitwidth) const
isIntegerTy - Return true if this is an IntegerType of the given width.
bool isIntOrIntVectorTy () const
bool isFunctionTy () const
bool isStructTy () const
bool isArrayTy () const
bool isPointerTy () const
bool isPtrOrPtrVectorTy () const
bool isVectorTy () const
bool canLosslesslyBitCastTo (Type *Ty) const
Determine if this type could be losslessly bitcast to Ty.
bool isEmptyTy () const
bool isPrimitiveType () const
bool isDerivedType () const
bool isFirstClassType () const
bool isSingleValueType () const
bool isAggregateType () const
bool isSized () const
unsigned getPrimitiveSizeInBits () const
unsigned getScalarSizeInBits ()
int getFPMantissaWidth () const
const Type * getScalarType () const
Type * getScalarType ()
subtype_iterator subtype_begin () const
subtype_iterator subtype_end () const
subtype_reverse_iterator subtype_rbegin () const
subtype_reverse_iterator subtype_rend () const
Type * getContainedType (unsigned i) const
unsigned getNumContainedTypes () const
unsigned getIntegerBitWidth () const
Type * getFunctionParamType (unsigned i) const
unsigned getFunctionNumParams () const
bool isFunctionVarArg () const
StringRef getStructName () const
unsigned getStructNumElements () const
Type * getStructElementType (unsigned N) const
Type * getSequentialElementType () const
uint64_t getArrayNumElements () const
Type * getArrayElementType () const
unsigned getVectorNumElements () const
Type * getVectorElementType () const
Type * getPointerElementType () const
unsigned getPointerAddressSpace () const
Get the address space of this pointer or pointer vector type.
PointerType * getPointerTo (unsigned AddrSpace=0)
Static Public Member Functions
static ArrayType * get (Type *ElementType, uint64_t NumElements)
static bool isValidElementType (Type *ElemTy)
static bool classof (const Type *T)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::SequentialType
static bool classof (const Type *T)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::CompositeType
static bool classof (const Type *T)
Methods for support type inquiry through isa, cast, and dyn_cast.
Static Public Member Functions inherited from llvm::Type
static Type * getPrimitiveType (LLVMContext &C, TypeID IDNumber)
getPrimitiveType - Return a type based on an identifier.
static Type * getVoidTy (LLVMContext &C)
static Type * getLabelTy (LLVMContext &C)
static Type * getHalfTy (LLVMContext &C)
static Type * getFloatTy (LLVMContext &C)
static Type * getDoubleTy (LLVMContext &C)
static Type * getMetadataTy (LLVMContext &C)
static Type * getX86_FP80Ty (LLVMContext &C)
static Type * getFP128Ty (LLVMContext &C)
static Type * getPPC_FP128Ty (LLVMContext &C)
static Type * getX86_MMXTy (LLVMContext &C)
static IntegerType * getIntNTy (LLVMContext &C, unsigned N)
static IntegerType * getInt1Ty (LLVMContext &C)
static IntegerType * getInt8Ty (LLVMContext &C)
static IntegerType * getInt16Ty (LLVMContext &C)
static IntegerType * getInt32Ty (LLVMContext &C)
static IntegerType * getInt64Ty (LLVMContext &C)
static PointerType * getHalfPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getFloatPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getDoublePtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getX86_FP80PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getFP128PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getPPC_FP128PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getX86_MMXPtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getIntNPtrTy (LLVMContext &C, unsigned N, unsigned AS=0)
static PointerType * getInt1PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt8PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt16PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt32PtrTy (LLVMContext &C, unsigned AS=0)
static PointerType * getInt64PtrTy (LLVMContext &C, unsigned AS=0)
Additional Inherited Members
Public Types inherited from llvm::Type
enum TypeID {
VoidTyID = 0, HalfTyID, FloatTyID, DoubleTyID,
X86_FP80TyID, FP128TyID, PPC_FP128TyID, LabelTyID,
MetadataTyID, X86_MMXTyID, IntegerTyID, FunctionTyID,
StructTyID, ArrayTyID, PointerTyID, VectorTyID,
NumTypeIDs, LastPrimitiveTyID = X86_MMXTyID, FirstDerivedTyID = IntegerTyID
}
typedef Type *const * subtype_iterator
typedef std::reverse_iterator< subtype_iterator > subtype_reverse_iterator
Protected Member Functions inherited from llvm::SequentialType
SequentialType (TypeID TID, Type *ElType)
Protected Member Functions inherited from llvm::CompositeType
CompositeType (LLVMContext &C, TypeID tid)
Protected Member Functions inherited from llvm::Type
Type (LLVMContext &C, TypeID tid)
~Type ()
void setTypeID (TypeID ID)
unsigned getSubclassData () const
void setSubclassData (unsigned val)
Protected Attributes inherited from llvm::Type
unsigned NumContainedTys
Type *const * ContainedTys
Detailed Description
ArrayType - Class to represent array types.
Definition at line 332 of file DerivedTypes.h.
Member Function Documentation
static bool llvm::ArrayType::classof (const Type * T) inline static
Methods for support type inquiry through isa, cast, and dyn_cast.
Definition at line 351 of file DerivedTypes.h.
References llvm::Type::ArrayTyID, and llvm::Type::getTypeID().
ArrayType * ArrayType::get (Type * ElementType, uint64_t NumElements) static
ArrayType::get - This static method is the primary way to construct an ArrayType
Definition at line 679 of file Type.cpp.
References llvm::LLVMContextImpl::ArrayTypes, llvm::Type::getContext(), llvm::LLVMContext::pImpl, and llvm::LLVMContextImpl::TypeAllocator.
Referenced by accumulateAndSortLibcalls(), appendToGlobalArray(), checkInterfaceFunction(), createLoweredType(), createPrivateNonConstGlobalForString(), llvm::createSjLjEHPreparePass(), FunctionNumber(), llvm::TypeBuilder< T[N], cross >::get(), llvm::TypeBuilder< T[], cross >::get(), llvm::ConstantDataArray::get(), GetAttrFromCode(), GetCaseResults(), getFunctionName(), getMemSetPatternValue(), getTypePartition(), INITIALIZE_PASS(), InstallGlobalCtors(), isLessConstraining(), llvm::linkShadowStackGC(), LLVMArrayType(), LLVMConstArray(), OptimizeGlobalAddressOfMalloc(), partitionShuffleOfConcats(), setUsedInitializer(), StackMallocSizeClass(), llvm::InstCombiner::visitAllocaInst(), and llvm::InstCombiner::visitLandingPadInst().
uint64_t llvm::ArrayType::getNumElements () const inline
Definition at line 348 of file DerivedTypes.h.
Referenced by llvm::ConstantArray::ConstantArray(), ftostr(), llvm::DenseMapInfo< ComparableFunction >::getHashValue(), llvm::DataLayout::getTypeSizeInBits(), isDereferenceablePointer(), llvm::Type::isEmptyTy(), isLessConstraining(), isZeroLengthArray(), llvm::TypePrinting::print(), tryToMakeAllocaBePromotable(), llvm::InstCombiner::visitLandingPadInst(), and WriteTypeTable().
bool ArrayType::isValidElementType (Type * ElemTy) static
isValidElementType - Return true if the specified type is valid as a element type.
Definition at line 692 of file Type.cpp.
References llvm::Type::isFunctionTy(), llvm::Type::isLabelTy(), llvm::Type::isMetadataTy(), llvm::Type::isVoidTy(), and llvm::Type::VectorTyID.
The documentation for this class was generated from the following files:
DerivedTypes.h
Type.cpp