LLVM: llvm::MCCompactEncodedInstFragment Class Reference
LLVM API Documentation
llvm::MCCompactEncodedInstFragment Class Reference
#include <MCAssembler.h>
Public Member Functions
MCCompactEncodedInstFragment (MCSectionData *SD=0)
virtual bool hasInstructions () const
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
virtual SmallVectorImpl< char > & getContents ()
virtual const SmallVectorImpl< char > & getContents () const
virtual bool alignToBundleEnd () const
Should this fragment be placed at the end of an aligned bundle?
virtual void setAlignToBundleEnd (bool V)
Public Member Functions inherited from llvm::MCEncodedFragment
MCEncodedFragment (MCFragment::FragmentType FType, MCSectionData *SD=0)
virtual ~MCEncodedFragment ()
virtual uint8_t getBundlePadding () const
Get the padding size that must be inserted before this fragment. Used for bundling. By default, no padding is inserted. Note that padding size is restricted to 8 bits. This is an optimization to reduce the amount of space used for each fragment. In practice, larger padding should never be required.
virtual void setBundlePadding (uint8_t N)
Set the padding size for this fragment. By default it's a no-op, and only some fragments have a meaningful implementation.
Public Member Functions inherited from llvm::MCFragment
MCFragment ()
virtual ~MCFragment ()
FragmentType getKind () const
MCSectionData * getParent () const
void setParent (MCSectionData *Value)
MCSymbolData * getAtom () const
void setAtom (MCSymbolData *Value)
unsigned getLayoutOrder () const
void setLayoutOrder (unsigned Value)
void dump ()
Public Member Functions inherited from llvm::ilist_node< MCFragment >
MCFragment * getPrevNode ()
Get the previous node, or 0 for the list head.
const MCFragment * getPrevNode () const
Get the previous node, or 0 for the list head.
MCFragment * getNextNode ()
Get the next node, or 0 for the list tail.
const MCFragment * getNextNode () const
Get the next node, or 0 for the list tail.
Static Public Member Functions
static bool classof (const MCFragment *F)
Static Public Member Functions inherited from llvm::MCEncodedFragment
static bool classof (const MCFragment *F)
Additional Inherited Members
Public Types inherited from llvm::MCFragment
enum FragmentType {
FT_Align, FT_Data, FT_CompactEncodedInst, FT_Fill,
FT_Relaxable, FT_Org, FT_Dwarf, FT_DwarfFrame,
FT_LEB
}
Protected Member Functions inherited from llvm::MCFragment
MCFragment (FragmentType _Kind, MCSectionData *_Parent=0)
Protected Member Functions inherited from llvm::ilist_node< MCFragment >
ilist_node ()
Detailed Description
This is a compact (memory-size-wise) fragment for holding an encoded instruction (non-relaxable) that has no fixups registered. When applicable, it can be used instead of MCDataFragment and lead to lower memory consumption.
Definition at line 254 of file MCAssembler.h.
Constructor & Destructor Documentation
llvm::MCCompactEncodedInstFragment::MCCompactEncodedInstFragment (MCSectionData * SD = 0) inline
Definition at line 262 of file MCAssembler.h.
Member Function Documentation
virtual bool llvm::MCCompactEncodedInstFragment::alignToBundleEnd () const inline virtual
Should this fragment be placed at the end of an aligned bundle?
Reimplemented from llvm::MCFragment.
Definition at line 274 of file MCAssembler.h.
static bool llvm::MCCompactEncodedInstFragment::classof (const MCFragment * F) inline static
Definition at line 277 of file MCAssembler.h.
References llvm::MCFragment::FT_CompactEncodedInst, and llvm::MCFragment::getKind().
virtual SmallVectorImpl<char>& llvm::MCCompactEncodedInstFragment::getContents () inline virtual
Implements llvm::MCEncodedFragment.
Definition at line 271 of file MCAssembler.h.
Referenced by llvm::MCFragment::dump(), and llvm::MCELFStreamer::EmitIdent().
virtual const SmallVectorImpl<char>& llvm::MCCompactEncodedInstFragment::getContents () const inline virtual
Implements llvm::MCEncodedFragment.
Definition at line 272 of file MCAssembler.h.
virtual bool llvm::MCCompactEncodedInstFragment::hasInstructions () const inline virtual
Does this fragment have instructions emitted into it? By default this is false, but specific fragment types may set it to true.
Reimplemented from llvm::MCFragment.
Definition at line 267 of file MCAssembler.h.
virtual void llvm::MCCompactEncodedInstFragment::setAlignToBundleEnd (bool V) inline virtual
Reimplemented from llvm::MCFragment.
Definition at line 275 of file MCAssembler.h.
The documentation for this class was generated from the following files:
MCAssembler.h
MCAssembler.cpp