LLVM: llvm::FoldingSetImpl::Node Class Reference
LLVM API Documentation
llvm::FoldingSetImpl::Node Class Reference
#include <FoldingSet.h>
Public Member Functions
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Detailed Description
Node - This class is used to maintain the singly linked bucket list in a folding set.
Definition at line 133 of file FoldingSet.h.
Constructor & Destructor Documentation
llvm::FoldingSetImpl::Node::Node () inline
Definition at line 140 of file FoldingSet.h.
Referenced by llvm::SDDbgInfo::add().
Member Function Documentation
void* llvm::FoldingSetImpl::Node::getNextInBucket () const inline
Definition at line 143 of file FoldingSet.h.
Referenced by llvm::FoldingSetBucketIteratorImpl::advance(), llvm::FoldingSetImpl::InsertNode(), and llvm::FoldingSetImpl::RemoveNode().
void llvm::FoldingSetImpl::Node::SetNextInBucket (void * N) inline
Definition at line 144 of file FoldingSet.h.
References llvm::FoldingSetImpl::clear(), llvm::FoldingSetImpl::FindNodeOrInsertPos(), llvm::FoldingSetImpl::GetOrInsertNode(), llvm::FoldingSetImpl::InsertNode(), N, and llvm::FoldingSetImpl::RemoveNode().
Referenced by llvm::FoldingSetImpl::InsertNode(), and llvm::FoldingSetImpl::RemoveNode().
The documentation for this class was generated from the following file:
FoldingSet.h