LLVM: llvm::MMIAddrLabelMap Class Reference
LLVM API Documentation
llvm::MMIAddrLabelMap Class Reference
Public Member Functions
MMIAddrLabelMap (MCContext &context)
~MMIAddrLabelMap ()
MCSymbol * getAddrLabelSymbol (BasicBlock *BB)
std::vector< MCSymbol * > getAddrLabelSymbolToEmit (BasicBlock *BB)
void takeDeletedSymbolsForFunction (Function *F, std::vector< MCSymbol * > &Result)
void UpdateForDeletedBlock (BasicBlock *BB)
void UpdateForRAUWBlock (BasicBlock *Old, BasicBlock *New)
Detailed Description
Definition at line 52 of file MachineModuleInfo.cpp.
Constructor & Destructor Documentation
llvm::MMIAddrLabelMap::MMIAddrLabelMap (MCContext & context) inline
Definition at line 77 of file MachineModuleInfo.cpp.
llvm::MMIAddrLabelMap::~MMIAddrLabelMap () inline
Definition at line 78 of file MachineModuleInfo.cpp.
References BB, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::begin(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::empty(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), F(), and I.
Member Function Documentation
MCSymbol * MMIAddrLabelMap::getAddrLabelSymbol (BasicBlock * BB)
Definition at line 100 of file MachineModuleInfo.cpp.
References BB, llvm::BasicBlock::getParent(), and llvm::BasicBlock::hasAddressTaken().
Referenced by llvm::MachineModuleInfo::getAddrLabelSymbol().
std::vector< MCSymbol * > MMIAddrLabelMap::getAddrLabelSymbolToEmit (BasicBlock * BB)
Definition at line 125 of file MachineModuleInfo.cpp.
References BB, llvm::BasicBlock::hasAddressTaken(), and takeDeletedSymbolsForFunction().
Referenced by llvm::MachineModuleInfo::getAddrLabelSymbolToEmit().
void MMIAddrLabelMap::takeDeletedSymbolsForFunction (Function * F, std::vector< MCSymbol * > & Result)
takeDeletedSymbolsForFunction - If we have any deleted symbols for F, return them.
Definition at line 146 of file MachineModuleInfo.cpp.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), I, and std::swap().
Referenced by getAddrLabelSymbolToEmit().
void MMIAddrLabelMap::UpdateForDeletedBlock (BasicBlock * BB)
Definition at line 159 of file MachineModuleInfo.cpp.
References BB, llvm::BasicBlock::getParent(), i, and llvm::MCSymbol::isDefined().
void MMIAddrLabelMap::UpdateForRAUWBlock (BasicBlock * Old, BasicBlock * New)
Definition at line 201 of file MachineModuleInfo.cpp.
The documentation for this class was generated from the following file:
MachineModuleInfo.cpp