LLVM: llvm::DIEAbbrevData Class Reference
LLVM API Documentation
llvm::DIEAbbrevData Class Reference
#include <DIE.h>
Public Member Functions
DIEAbbrevData (dwarf::Attribute A, dwarf::Form F)
dwarf::Attribute getAttribute () const
dwarf::Form getForm () const
void Profile (FoldingSetNodeID &ID) const
Detailed Description
DIEAbbrevData - Dwarf abbreviation data, describes one attribute of a Dwarf abbreviation.
Definition at line 33 of file DIE.h.
Constructor & Destructor Documentation
llvm::DIEAbbrevData::DIEAbbrevData (dwarf::Attribute A, dwarf::Form F) inline
Definition at line 42 of file DIE.h.
Referenced by llvm::DIEAbbrev::AddAttribute().
Member Function Documentation
dwarf::Attribute llvm::DIEAbbrevData::getAttribute () const inline
Definition at line 45 of file DIE.h.
Referenced by llvm::DIEAbbrev::Emit(), getDIEStringAttr(), llvm::DIEAbbrev::print(), and llvm::DIE::print().
dwarf::Form llvm::DIEAbbrevData::getForm () const inline
Definition at line 46 of file DIE.h.
References Profile().
Referenced by llvm::DIEBlock::ComputeSize(), llvm::DIEAbbrev::Emit(), llvm::DIEBlock::EmitValue(), getDIEStringAttr(), llvm::DIEAbbrev::print(), and llvm::DIE::print().
void DIEAbbrevData::Profile (FoldingSetNodeID & ID) const
Profile - Used to gather unique data for the abbreviation folding set.
Definition at line 36 of file DIE.cpp.
References llvm::FoldingSetNodeID::AddInteger().
Referenced by llvm::DIEAbbrev::AddAttribute(), getForm(), and llvm::DIEAbbrev::Profile().
The documentation for this class was generated from the following files:
DIE.h
DIE.cpp