LLVM: llvm::StringRecTy Class Reference
LLVM API Documentation
llvm::StringRecTy Class Reference
#include <Record.h>
Public Member Functions
virtual Init * convertValue (UnsetInit *UI)
virtual Init * convertValue (BitInit *BI)
virtual Init * convertValue (BitsInit *BI)
virtual Init * convertValue (IntInit *II)
virtual Init * convertValue (StringInit *SI)
virtual Init * convertValue (ListInit *LI)
virtual Init * convertValue (UnOpInit *BO)
virtual Init * convertValue (BinOpInit *BO)
virtual Init * convertValue (TernOpInit *BO)
virtual Init * convertValue (VarBitInit *VB)
virtual Init * convertValue (DefInit *DI)
virtual Init * convertValue (DagInit *DI)
virtual Init * convertValue (TypedInit *TI)
virtual Init * convertValue (VarInit *VI)
virtual Init * convertValue (FieldInit *FI)
virtual std::string getAsString () const
virtual bool typeIsConvertibleTo (const RecTy *RHS) const
Public Member Functions inherited from llvm::RecTy
RecTyKind getRecTyKind () const
RecTy (RecTyKind K)
virtual ~RecTy ()
void print (raw_ostream &OS) const
void dump () const
ListRecTy * getListTy ()
getListTy - Returns the type representing list<this>.
virtual bool baseClassOf (const RecTy *) const
Static Public Member Functions
static bool classof (const RecTy *RT)
static StringRecTy * get ()
Additional Inherited Members
Public Types inherited from llvm::RecTy
enum RecTyKind {
BitRecTyKind, BitsRecTyKind, IntRecTyKind, StringRecTyKind,
ListRecTyKind, DagRecTyKind, RecordRecTyKind
}
Subclass discriminator (for dyn_cast<> et al.)
Detailed Description
StringRecTy - 'string' - Represent an string value
Definition at line 256 of file Record.h.
Member Function Documentation
static bool llvm::StringRecTy::classof (const RecTy * RT) inline static
Definition at line 260 of file Record.h.
References llvm::RecTy::getRecTyKind(), and llvm::RecTy::StringRecTyKind.
virtual Init* llvm::StringRecTy::convertValue (UnsetInit * UI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 266 of file Record.h.
virtual Init* llvm::StringRecTy::convertValue (BitInit * BI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 267 of file Record.h.
virtual Init* llvm::StringRecTy::convertValue (BitsInit * BI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 268 of file Record.h.
virtual Init* llvm::StringRecTy::convertValue (IntInit * II) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 269 of file Record.h.
virtual Init* llvm::StringRecTy::convertValue (StringInit * SI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 270 of file Record.h.
virtual Init* llvm::StringRecTy::convertValue (ListInit * LI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 271 of file Record.h.
References llvm::RecTy::convertValue().
Init * StringRecTy::convertValue (UnOpInit * BO) virtual
Reimplemented from llvm::RecTy.
Definition at line 238 of file Record.cpp.
References llvm::UnOpInit::CAST, llvm::Init::convertInitializerTo(), convertValue(), llvm::UnOpInit::get(), llvm::UnOpInit::getOpcode(), and llvm::UnOpInit::getOperand().
Init * StringRecTy::convertValue (BinOpInit * BO) virtual
Reimplemented from llvm::RecTy.
Definition at line 250 of file Record.cpp.
References llvm::Init::convertInitializerTo(), convertValue(), llvm::BinOpInit::get(), llvm::BinOpInit::getLHS(), llvm::BinOpInit::getOpcode(), llvm::BinOpInit::getRHS(), and llvm::BinOpInit::STRCONCAT.
virtual Init* llvm::StringRecTy::convertValue (TernOpInit * BO) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 274 of file Record.h.
References llvm::RecTy::convertValue().
virtual Init* llvm::StringRecTy::convertValue (VarBitInit * VB) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 276 of file Record.h.
virtual Init* llvm::StringRecTy::convertValue (DefInit * DI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 277 of file Record.h.
virtual Init* llvm::StringRecTy::convertValue (DagInit * DI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 278 of file Record.h.
References llvm::RecTy::convertValue().
Init * StringRecTy::convertValue (TypedInit * TI) virtual
Reimplemented from llvm::RecTy.
Definition at line 264 of file Record.cpp.
References llvm::TypedInit::getType().
virtual Init* llvm::StringRecTy::convertValue (VarInit * VI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 280 of file Record.h.
References llvm::RecTy::convertValue().
virtual Init* llvm::StringRecTy::convertValue (FieldInit * FI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 281 of file Record.h.
References llvm::RecTy::convertValue().
static StringRecTy* llvm::StringRecTy::get () inline static
Definition at line 264 of file Record.h.
Referenced by GetNewAnonymousName(), and llvm::RecordVal::print().
virtual std::string llvm::StringRecTy::getAsString () const inline virtual
Implements llvm::RecTy.
Definition at line 283 of file Record.h.
virtual bool llvm::StringRecTy::typeIsConvertibleTo (const RecTy * RHS) const inline virtual
typeIsConvertibleTo - Return true if all values of 'this' type can be converted to the specified type.
Implements llvm::RecTy.
Definition at line 285 of file Record.h.
References llvm::RecTy::baseClassOf().
The documentation for this class was generated from the following files:
Record.h
Record.cpp