LLVM: llvm::AsmToken Class Reference
LLVM API Documentation
llvm::AsmToken Class Reference
AsmToken - Target independent representation for an assembler token.
#include <MCAsmLexer.h>
Public Types
enum TokenKind {
Eof, Error, Identifier, String,
Integer, Real, EndOfStatement, Colon,
Space, Plus, Minus, Tilde,
Slash, BackSlash, LParen, RParen,
LBrac, RBrac, LCurly, RCurly,
Star, Dot, Comma, Dollar,
Equal, EqualEqual, Pipe, PipePipe,
Caret, Amp, AmpAmp, Exclaim,
ExclaimEqual, Percent, Hash, Less,
LessEqual, LessLess, LessGreater, Greater,
GreaterEqual, GreaterGreater, At
}
Public Member Functions
AsmToken ()
AsmToken (TokenKind _Kind, StringRef _Str, int64_t _IntVal=0)
TokenKind getKind () const
bool is (TokenKind K) const
bool isNot (TokenKind K) const
SMLoc getLoc () const
SMLoc getEndLoc () const
StringRef getStringContents () const
getStringContents - Get the contents of a string token (without quotes).
StringRef getIdentifier () const
StringRef getString () const
int64_t getIntVal () const
Detailed Description
AsmToken - Target independent representation for an assembler token.
Definition at line 21 of file MCAsmLexer.h.
Member Enumeration Documentation
enum llvm::AsmToken::TokenKind
Enumerator
Eof
Error
Identifier
String
Integer
Real
EndOfStatement
Colon
Space
Plus
Minus
Tilde
Slash
BackSlash
LParen
RParen
LBrac
RBrac
LCurly
RCurly
Star
Dot
Comma
Dollar
Equal
EqualEqual
Pipe
PipePipe
Caret
Amp
AmpAmp
Exclaim
ExclaimEqual
Percent
Hash
Less
LessEqual
LessLess
LessGreater
Greater
GreaterEqual
GreaterGreater
At
Definition at line 23 of file MCAsmLexer.h.
Constructor & Destructor Documentation
llvm::AsmToken::AsmToken () inline
Definition at line 63 of file MCAsmLexer.h.
llvm::AsmToken::AsmToken (TokenKind _Kind, StringRef _Str, int64_t _IntVal = 0) inline
Definition at line 64 of file MCAsmLexer.h.
Member Function Documentation
SMLoc AsmToken::getEndLoc () const
Definition at line 30 of file MCAsmLexer.cpp.
References llvm::SMLoc::getFromPointer().
Referenced by getDRegFromQReg(), getInstDesc(), isImmSExti64i32Value(), isNot(), and RewriteIntelBracExpression().
StringRef llvm::AsmToken::getIdentifier () const inline
getIdentifier - Get the identifier string for the current token, which should be an identifier or a string. This gets the portion of the string which should be used as the identifier, e.g., it does not include the quotes on strings.
Definition at line 84 of file MCAsmLexer.h.
References getString(), getStringContents(), and Identifier.
Referenced by convert64i32to64ri8(), getInstDesc(), getRealVLDOpcode(), and isValidEncoding().
int64_t llvm::AsmToken::getIntVal () const inline
Definition at line 100 of file MCAsmLexer.h.
References Integer.
Referenced by getDRegFromQReg(), getInstDesc(), isImmSExti64i32Value(), and RewriteIntelBracExpression().
TokenKind llvm::AsmToken::getKind () const inline
Definition at line 67 of file MCAsmLexer.h.
Referenced by getInstDesc(), and llvm::MCAsmLexer::getKind().
SMLoc AsmToken::getLoc () const
Definition at line 26 of file MCAsmLexer.cpp.
References llvm::SMLoc::getFromPointer().
Referenced by convert64i32to64ri8(), getBinOpPrecedence(), getDRegFromQReg(), getInstDesc(), getRealVLDOpcode(), isImmSExti64i32Value(), isNot(), isValidEncoding(), llvm::MCAsmLexer::Lex(), and RewriteIntelBracExpression().
StringRef llvm::AsmToken::getString () const inline
getString - Get the string for the current token, this includes all characters (for example, the quotes on strings) in the token.
The returned StringRef points into the source manager's memory buffer, and is safe to store across calls to Lex().
Definition at line 95 of file MCAsmLexer.h.
Referenced by convert64i32to64ri8(), getDRegFromQReg(), getIdentifier(), getInstDesc(), getRealVLDOpcode(), isImmSExti64i32Value(), MatchCoprocessorOperandName(), and RewriteIntelBracExpression().
StringRef llvm::AsmToken::getStringContents () const inline
getStringContents - Get the contents of a string token (without quotes).
Definition at line 75 of file MCAsmLexer.h.
References llvm::StringRef::size(), llvm::StringRef::slice(), and String.
Referenced by getIdentifier().
bool llvm::AsmToken::is (TokenKind K) const inline
Definition at line 68 of file MCAsmLexer.h.
Referenced by getDRegFromQReg(), getInstDesc(), llvm::MCAsmLexer::is(), isImmSExti64i32Value(), MatchCoprocessorOperandName(), and RewriteIntelBracExpression().
bool llvm::AsmToken::isNot (TokenKind K) const inline
Definition at line 69 of file MCAsmLexer.h.
References getEndLoc(), and getLoc().
Referenced by getDRegFromQReg(), getInstDesc(), getRealVLDOpcode(), isImmSExti64i32Value(), llvm::MCAsmLexer::isNot(), MatchCoprocessorOperandName(), and RewriteIntelBracExpression().
The documentation for this class was generated from the following files:
MCAsmLexer.h
MCAsmLexer.cpp