LLVM: llvm::PBQPBuilder Class Reference
LLVM API Documentation
llvm::PBQPBuilder Class Reference
#include <RegAllocPBQP.h>
Public Types
typedef std::set< unsigned > RegSet
Public Member Functions
PBQPBuilder ()
Default constructor.
virtual ~PBQPBuilder ()
Clean up a PBQPBuilder.
virtual PBQPRAProblem * build (MachineFunction *mf, const LiveIntervals *lis, const MachineBlockFrequencyInfo *mbfi, const RegSet &vregs)
Detailed Description
Builds PBQP instances to represent register allocation problems. Includes spill, interference and coalescing costs by default. You can extend this class to support additional constraints for your architecture.
Definition at line 110 of file RegAllocPBQP.h.
Member Typedef Documentation
typedef std::set<unsigned> llvm::PBQPBuilder::RegSet
Definition at line 116 of file RegAllocPBQP.h.
Constructor & Destructor Documentation
llvm::PBQPBuilder::PBQPBuilder () inline
Default constructor.
Definition at line 119 of file RegAllocPBQP.h.
virtual llvm::PBQPBuilder::~PBQPBuilder () inline virtual
Clean up a PBQPBuilder.
Definition at line 122 of file RegAllocPBQP.h.
Member Function Documentation
PBQPRAProblem * PBQPBuilder::build (MachineFunction * mf, const LiveIntervals * lis, const MachineBlockFrequencyInfo * mbfi, const RegSet & vregs) virtual
Build a PBQP instance to represent the register allocation problem for the given MachineFunction.
Reimplemented in llvm::PBQPBuilderWithCoalescing.
Definition at line 189 of file RegAllocPBQP.cpp.
References PBQP::Graph::addEdge(), PBQP::Graph::addNode(), llvm::LiveIntervals::checkRegMaskInterference(), llvm::MachineRegisterInfo::def_empty(), llvm::BitVector::empty(), llvm::LiveRange::empty(), g, llvm::PBQPRAProblem::getAllowedSet(), PBQP::Matrix::getCols(), PBQP::Graph::getEdgeCosts(), llvm::PBQPRAProblem::getGraph(), llvm::LiveIntervals::getInterval(), PBQP::Graph::getNodeCosts(), llvm::PBQPRAProblem::getNodeForVReg(), llvm::MCRegisterInfo::getNumRegs(), llvm::TargetRegisterClass::getRawAllocationOrder(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::TargetMachine::getRegisterInfo(), llvm::LiveIntervals::getRegUnit(), PBQP::Matrix::getRows(), llvm::MachineFunction::getTarget(), i, llvm::MachineRegisterInfo::isReserved(), llvm::MCRegisterInfo::DiffListIterator::isValid(), j(), Matrix, llvm::next(), node, llvm::LiveRange::overlaps(), p, llvm::PBQPRAProblem::recordVReg(), llvm::TargetRegisterInfo::regsOverlap(), llvm::MachineRegisterInfo::setPhysRegUsed(), llvm::ArrayRef< T >::size(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::OwningPtr< T >::take(), llvm::BitVector::test(), and llvm::LiveInterval::weight.
Referenced by llvm::PBQPBuilderWithCoalescing::build().
The documentation for this class was generated from the following files:
RegAllocPBQP.h
RegAllocPBQP.cpp