LLVM: llvm::object::RelocationRef Class Reference
LLVM API Documentation
llvm::object::RelocationRef Class Reference
#include <ObjectFile.h>
Public Member Functions
RelocationRef ()
RelocationRef (DataRefImpl RelocationP, const ObjectFile *Owner)
RelocationRef.
bool operator== (const RelocationRef &Other) const
error_code getNext (RelocationRef &Result) const
error_code getAddress (uint64_t &Result) const
error_code getOffset (uint64_t &Result) const
symbol_iterator getSymbol () const
error_code getType (uint64_t &Result) const
error_code getHidden (bool &Result) const
Indicates whether this relocation should hidden when listing relocations, usually because it is the trailing part of a multipart relocation that will be printed as part of the leading relocation.
error_code getTypeName (SmallVectorImpl< char > &Result) const
Get a string that represents the type of this relocation.
error_code getValueString (SmallVectorImpl< char > &Result) const
Get a string that represents the calculation of the value of this relocation.
DataRefImpl getRawDataRefImpl () const
const ObjectFile * getObjectFile () const
Detailed Description
RelocationRef - This is a value type class that represents a single relocation in the list of relocations in the object file.
Definition at line 92 of file ObjectFile.h.
Constructor & Destructor Documentation
llvm::object::RelocationRef::RelocationRef () inline
Definition at line 97 of file ObjectFile.h.
References llvm::Intrinsic::getType(), and llvm::object::operator==().
llvm::object::RelocationRef::RelocationRef (DataRefImpl RelocationP, const ObjectFile * Owner) inline
RelocationRef.
Definition at line 538 of file ObjectFile.h.
Member Function Documentation
error_code llvm::object::RelocationRef::getAddress (uint64_t & Result) const inline
Definition at line 551 of file ObjectFile.h.
References llvm::object::ObjectFile::getRelocationAddress().
error_code llvm::object::RelocationRef::getHidden (bool & Result) const inline
Indicates whether this relocation should hidden when listing relocations, usually because it is the trailing part of a multipart relocation that will be printed as part of the leading relocation.
Definition at line 577 of file ObjectFile.h.
References llvm::object::ObjectFile::getRelocationHidden().
error_code llvm::object::RelocationRef::getNext (RelocationRef & Result) const inline
Definition at line 547 of file ObjectFile.h.
References llvm::object::ObjectFile::getRelocationNext().
const ObjectFile * llvm::object::RelocationRef::getObjectFile () const inline
Definition at line 585 of file ObjectFile.h.
Referenced by llvm::object::RelocVisitor::error(), and llvm::object::getELFRelocationAddend().
error_code llvm::object::RelocationRef::getOffset (uint64_t & Result) const inline
Definition at line 555 of file ObjectFile.h.
References llvm::object::ObjectFile::getRelocationOffset().
Referenced by llvm::object::RelocVisitor::error(), llvm::RuntimeDyldMachO::processRelocationRef(), and llvm::RuntimeDyldELF::processRelocationRef().
DataRefImpl llvm::object::RelocationRef::getRawDataRefImpl () const inline
Definition at line 581 of file ObjectFile.h.
Referenced by llvm::object::RelocVisitor::error(), llvm::object::getELFRelocationAddend(), and llvm::RuntimeDyldMachO::processRelocationRef().
symbol_iterator llvm::object::RelocationRef::getSymbol () const inline
Definition at line 559 of file ObjectFile.h.
References llvm::object::ObjectFile::getRelocationSymbol().
Referenced by llvm::RuntimeDyldMachO::processRelocationRef(), and llvm::RuntimeDyldELF::processRelocationRef().
error_code llvm::object::RelocationRef::getType (uint64_t & Result) const inline
Definition at line 563 of file ObjectFile.h.
References llvm::object::ObjectFile::getRelocationType().
Referenced by llvm::RuntimeDyldELF::processRelocationRef().
error_code llvm::object::RelocationRef::getTypeName (SmallVectorImpl< char > & Result) const inline
Get a string that represents the type of this relocation.
This is for display purposes only.
Definition at line 567 of file ObjectFile.h.
References llvm::object::ObjectFile::getRelocationTypeName().
error_code llvm::object::RelocationRef::getValueString (SmallVectorImpl< char > & Result) const inline
Get a string that represents the calculation of the value of this relocation.
This is for display purposes only.
Definition at line 572 of file ObjectFile.h.
References llvm::object::ObjectFile::getRelocationValueString().
bool llvm::object::RelocationRef::operator== (const RelocationRef & Other) const inline
Definition at line 543 of file ObjectFile.h.
The documentation for this class was generated from the following file:
ObjectFile.h