LLVM: llvm::Win64Exception Class Reference
LLVM API Documentation
llvm::Win64Exception Class Reference
#include <DwarfException.h>
Public Member Functions
Win64Exception (AsmPrinter *A)
virtual ~Win64Exception ()
virtual void EndModule ()
virtual void BeginFunction (const MachineFunction *MF)
virtual void EndFunction ()
EndFunction - Gather and emit post-function exception information.
Public Member Functions inherited from llvm::DwarfException
DwarfException (AsmPrinter *A)
virtual ~DwarfException ()
Additional Inherited Members
Protected Types inherited from llvm::DwarfException
typedef DenseMap< MCSymbol *, PadRange > RangeMapType
Protected Member Functions inherited from llvm::DwarfException
unsigned ComputeActionsTable (const SmallVectorImpl< const LandingPadInfo * > &LPs, SmallVectorImpl< ActionEntry > &Actions, SmallVectorImpl< unsigned > &FirstActions)
bool CallToNoUnwindFunction (const MachineInstr *MI)
void ComputeCallSiteTable (SmallVectorImpl< CallSiteEntry > &CallSites, const RangeMapType &PadMap, const SmallVectorImpl< const LandingPadInfo * > &LPs, const SmallVectorImpl< unsigned > &FirstActions)
void EmitExceptionTable ()
virtual void EmitTypeInfos (unsigned TTypeEncoding)
Static Protected Member Functions inherited from llvm::DwarfException
static unsigned SharedTypeIds (const LandingPadInfo *L, const LandingPadInfo *R)
SharedTypeIds - How many leading type ids two landing pads have in common.
static bool PadLT (const LandingPadInfo *L, const LandingPadInfo *R)
PadLT - Order landing pads lexicographically by type id.
Protected Attributes inherited from llvm::DwarfException
AsmPrinter * Asm
Asm - Target of Dwarf emission.
MachineModuleInfo * MMI
MMI - Collected machine module information.
Detailed Description
Definition at line 202 of file DwarfException.h.
Constructor & Destructor Documentation
Win64Exception::Win64Exception (AsmPrinter * A)
Definition at line 40 of file Win64Exception.cpp.
Win64Exception::~Win64Exception () virtual
Definition at line 45 of file Win64Exception.cpp.
Member Function Documentation
void Win64Exception::BeginFunction (const MachineFunction * MF) virtual
BeginFunction - Gather pre-function exception information. Assumes being emitted immediately after the function entry point.
BeginFunction - Gather pre-function exception information. Assumes it's being emitted immediately after the function entry point.
Reimplemented from llvm::DwarfException.
Definition at line 54 of file Win64Exception.cpp.
References llvm::DwarfException::Asm, llvm::AsmPrinter::CurrentFnSym, llvm::dwarf::DW_EH_PE_omit, llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitWin64EHHandler(), llvm::MCStreamer::EmitWin64EHStartProc(), llvm::AsmPrinter::GetExternalSymbolSymbol(), llvm::AsmPrinter::getFunctionNumber(), llvm::MachineModuleInfo::getLandingPads(), llvm::MCObjectFileInfo::getLSDAEncoding(), llvm::AsmPrinter::getObjFileLowering(), llvm::MachineModuleInfo::getPersonalities(), llvm::MCObjectFileInfo::getPersonalityEncoding(), llvm::MachineModuleInfo::getPersonalityIndex(), llvm::AsmPrinter::GetTempSymbol(), llvm::DwarfException::MMI, llvm::AsmPrinter::needsSEHMoves(), and llvm::AsmPrinter::OutStreamer.
void Win64Exception::EndFunction () virtual
EndFunction - Gather and emit post-function exception information.
EndFunction - Gather and emit post-function exception information.
Reimplemented from llvm::DwarfException.
Definition at line 91 of file Win64Exception.cpp.
References llvm::DwarfException::Asm, llvm::MCSymbolRefExpr::Create(), llvm::DwarfException::EmitExceptionTable(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitValue(), llvm::MCStreamer::EmitWin64EHEndProc(), llvm::MCStreamer::EmitWin64EHHandlerData(), llvm::TargetLoweringObjectFile::getCFIPersonalitySymbol(), llvm::AsmPrinter::getFunctionNumber(), llvm::AsmPrinter::getObjFileLowering(), llvm::MachineModuleInfo::getPersonalities(), llvm::MachineModuleInfo::getPersonalityIndex(), llvm::AsmPrinter::GetTempSymbol(), llvm::AsmPrinter::Mang, llvm::DwarfException::MMI, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, llvm::MCStreamer::PopSection(), llvm::MCStreamer::PushSection(), and llvm::MachineModuleInfo::TidyLandingPads().
void Win64Exception::EndModule () virtual
EndModule - Emit all exception information that should come after the content.
Reimplemented from llvm::DwarfException.
Definition at line 49 of file Win64Exception.cpp.
The documentation for this class was generated from the following files:
DwarfException.h
Win64Exception.cpp