LLVM: llvm::BitCodeAbbrev Class Reference
LLVM API Documentation
llvm::BitCodeAbbrev Class Reference
#include <BitCodes.h>
Public Member Functions
BitCodeAbbrev ()
void addRef ()
void dropRef ()
unsigned getNumOperandInfos () const
const BitCodeAbbrevOp & getOperandInfo (unsigned N) const
void Add (const BitCodeAbbrevOp &OpInfo)
Detailed Description
BitCodeAbbrev - This class represents an abbreviation record. An abbreviation allows a complex record that has redundancy to be stored in a specialized format instead of the fully-general, fully-vbr, format.
Definition at line 164 of file BitCodes.h.
Constructor & Destructor Documentation
llvm::BitCodeAbbrev::BitCodeAbbrev () inline
Definition at line 169 of file BitCodes.h.
Member Function Documentation
void llvm::BitCodeAbbrev::Add (const BitCodeAbbrevOp & OpInfo) inline
Definition at line 181 of file BitCodes.h.
References llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by llvm::BitstreamCursor::ReadAbbrevRecord(), WriteBlockInfo(), WriteConstants(), WriteModuleInfo(), and WriteModuleMetadata().
void llvm::BitCodeAbbrev::addRef () inline
Definition at line 171 of file BitCodes.h.
void llvm::BitCodeAbbrev::dropRef () inline
Definition at line 172 of file BitCodes.h.
unsigned llvm::BitCodeAbbrev::getNumOperandInfos () const inline
Definition at line 174 of file BitCodes.h.
References llvm::SmallVectorTemplateCommon< T >::size().
Referenced by llvm::BitstreamWriter::EmitRecordWithArray(), llvm::BitstreamCursor::readRecord(), and llvm::BitstreamCursor::skipRecord().
const BitCodeAbbrevOp& llvm::BitCodeAbbrev::getOperandInfo (unsigned N) const inline
Definition at line 177 of file BitCodes.h.
References N.
Referenced by llvm::BitstreamWriter::EmitRecordWithArray(), llvm::BitstreamCursor::readRecord(), and llvm::BitstreamCursor::skipRecord().
The documentation for this class was generated from the following file:
BitCodes.h