LLVM: llvm::mapped_iterator< RootIt, UnaryFunc > Class Template Reference
LLVM API Documentation
llvm::mapped_iterator< RootIt, UnaryFunc > Class Template Reference
#include <STLExtras.h>
Public Types
typedef std::iterator_traits< RootIt >::iterator_category iterator_category
typedef std::iterator_traits< RootIt >::difference_type difference_type
typedef UnaryFunc::result_type value_type
typedef void pointer
typedef void reference
typedef RootIt iterator_type
typedef mapped_iterator< RootIt, UnaryFunc > _Self
Public Member Functions
const RootIt & getCurrent () const
const UnaryFunc & getFunc () const
mapped_iterator (const RootIt &I, UnaryFunc F)
mapped_iterator (const mapped_iterator &It)
value_type operator* () const
_Self & operator++ ()
_Self & operator-- ()
_Self operator++ (int)
_Self operator-- (int)
_Self operator+ (difference_type n) const
_Self & operator+= (difference_type n)
_Self operator- (difference_type n) const
_Self & operator-= (difference_type n)
reference operator[] (difference_type n) const
bool operator!= (const _Self &X) const
bool operator== (const _Self &X) const
bool operator< (const _Self &X) const
difference_type operator- (const _Self &X) const
Detailed Description
template<class RootIt, class UnaryFunc>
class llvm::mapped_iterator< RootIt, UnaryFunc >
Definition at line 76 of file STLExtras.h.
Member Typedef Documentation
template<class RootIt, class UnaryFunc> typedef mapped_iterator<RootIt, UnaryFunc> llvm::mapped_iterator< RootIt, UnaryFunc >::_Self
Definition at line 91 of file STLExtras.h.
template<class RootIt, class UnaryFunc> typedef std::iterator_traits<RootIt>::difference_type llvm::mapped_iterator< RootIt, UnaryFunc >::difference_type
Definition at line 83 of file STLExtras.h.
template<class RootIt, class UnaryFunc> typedef std::iterator_traits<RootIt>::iterator_category llvm::mapped_iterator< RootIt, UnaryFunc >::iterator_category
Definition at line 81 of file STLExtras.h.
template<class RootIt, class UnaryFunc> typedef RootIt llvm::mapped_iterator< RootIt, UnaryFunc >::iterator_type
Definition at line 90 of file STLExtras.h.
template<class RootIt, class UnaryFunc> typedef void llvm::mapped_iterator< RootIt, UnaryFunc >::pointer
Definition at line 86 of file STLExtras.h.
template<class RootIt, class UnaryFunc> typedef void llvm::mapped_iterator< RootIt, UnaryFunc >::reference
Definition at line 88 of file STLExtras.h.
template<class RootIt, class UnaryFunc> typedef UnaryFunc::result_type llvm::mapped_iterator< RootIt, UnaryFunc >::value_type
Definition at line 84 of file STLExtras.h.
Constructor & Destructor Documentation
template<class RootIt, class UnaryFunc> llvm::mapped_iterator< RootIt, UnaryFunc >::mapped_iterator (const RootIt & I, UnaryFunc F) inline explicit
Definition at line 96 of file STLExtras.h.
template<class RootIt, class UnaryFunc> llvm::mapped_iterator< RootIt, UnaryFunc >::mapped_iterator (const mapped_iterator< RootIt, UnaryFunc > & It) inline
Definition at line 98 of file STLExtras.h.
Member Function Documentation
template<class RootIt, class UnaryFunc> const RootIt& llvm::mapped_iterator< RootIt, UnaryFunc >::getCurrent () const inline
Definition at line 93 of file STLExtras.h.
Referenced by llvm::operator+().
template<class RootIt, class UnaryFunc> const UnaryFunc& llvm::mapped_iterator< RootIt, UnaryFunc >::getFunc () const inline
Definition at line 94 of file STLExtras.h.
Referenced by llvm::operator+().
template<class RootIt, class UnaryFunc> bool llvm::mapped_iterator< RootIt, UnaryFunc >::operator!= (const _Self & X) const inline
Definition at line 119 of file STLExtras.h.
References llvm::operator==().
template<class RootIt, class UnaryFunc> value_type llvm::mapped_iterator< RootIt, UnaryFunc >::operator* () const inline
Definition at line 101 of file STLExtras.h.
template<class RootIt, class UnaryFunc> _Self llvm::mapped_iterator< RootIt, UnaryFunc >::operator+ (difference_type n) const inline
Definition at line 109 of file STLExtras.h.
template<class RootIt, class UnaryFunc> _Self& llvm::mapped_iterator< RootIt, UnaryFunc >::operator++ () inline
Definition at line 105 of file STLExtras.h.
template<class RootIt, class UnaryFunc> _Self llvm::mapped_iterator< RootIt, UnaryFunc >::operator++ (int) inline
Definition at line 107 of file STLExtras.h.
template<class RootIt, class UnaryFunc> _Self& llvm::mapped_iterator< RootIt, UnaryFunc >::operator+= (difference_type n) inline
Definition at line 112 of file STLExtras.h.
References n.
template<class RootIt, class UnaryFunc> _Self llvm::mapped_iterator< RootIt, UnaryFunc >::operator- (difference_type n) const inline
Definition at line 113 of file STLExtras.h.
template<class RootIt, class UnaryFunc> difference_type llvm::mapped_iterator< RootIt, UnaryFunc >::operator- (const _Self & X) const inline
Definition at line 123 of file STLExtras.h.
template<class RootIt, class UnaryFunc> _Self& llvm::mapped_iterator< RootIt, UnaryFunc >::operator-- () inline
Definition at line 106 of file STLExtras.h.
template<class RootIt, class UnaryFunc> _Self llvm::mapped_iterator< RootIt, UnaryFunc >::operator-- (int) inline
Definition at line 108 of file STLExtras.h.
template<class RootIt, class UnaryFunc> _Self& llvm::mapped_iterator< RootIt, UnaryFunc >::operator-= (difference_type n) inline
Definition at line 116 of file STLExtras.h.
References n.
template<class RootIt, class UnaryFunc> bool llvm::mapped_iterator< RootIt, UnaryFunc >::operator< (const _Self & X) const inline
Definition at line 121 of file STLExtras.h.
template<class RootIt, class UnaryFunc> bool llvm::mapped_iterator< RootIt, UnaryFunc >::operator== (const _Self & X) const inline
Definition at line 120 of file STLExtras.h.
template<class RootIt, class UnaryFunc> reference llvm::mapped_iterator< RootIt, UnaryFunc >::operator[] (difference_type n) const inline
Definition at line 117 of file STLExtras.h.
References n.
The documentation for this class was generated from the following file:
STLExtras.h