LLVM: llvm::MCWinCOFFObjectTargetWriter Class Reference
LLVM API Documentation
llvm::MCWinCOFFObjectTargetWriter Class Reference abstract
#include <MCWinCOFFObjectWriter.h>
Public Member Functions
virtual ~MCWinCOFFObjectTargetWriter ()
unsigned getMachine () const
virtual unsigned getRelocType (const MCValue &Target, const MCFixup &Fixup, bool IsCrossSection) const =0
Protected Member Functions
MCWinCOFFObjectTargetWriter (unsigned Machine_)
Detailed Description
Definition at line 19 of file MCWinCOFFObjectWriter.h.
Constructor & Destructor Documentation
MCWinCOFFObjectTargetWriter::MCWinCOFFObjectTargetWriter (unsigned Machine_) protected
Definition at line 914 of file WinCOFFObjectWriter.cpp.
virtual llvm::MCWinCOFFObjectTargetWriter::~MCWinCOFFObjectTargetWriter () inline virtual
Definition at line 27 of file MCWinCOFFObjectWriter.h.
Member Function Documentation
unsigned llvm::MCWinCOFFObjectTargetWriter::getMachine () const inline
Definition at line 29 of file MCWinCOFFObjectWriter.h.
References llvm::createWinCOFFObjectWriter(), and getRelocType().
virtual unsigned llvm::MCWinCOFFObjectTargetWriter::getRelocType (const MCValue & Target, const MCFixup & Fixup, bool IsCrossSection) const pure virtual
Referenced by getMachine().
The documentation for this class was generated from the following files:
MCWinCOFFObjectWriter.h
WinCOFFObjectWriter.cpp