LLVM: llvm::cl::StringSaver Class Reference
LLVM API Documentation
llvm::cl::StringSaver Class Reference abstract
Saves strings in the inheritor's stable storage and returns a stable raw character pointer.
#include <CommandLine.h>
Public Member Functions
virtual const char * SaveString (const char *Str)=0
virtual ~StringSaver ()
Detailed Description
Saves strings in the inheritor's stable storage and returns a stable raw character pointer.
Definition at line 1757 of file CommandLine.h.
Constructor & Destructor Documentation
virtual llvm::cl::StringSaver::~StringSaver () inline virtual
Definition at line 1761 of file CommandLine.h.
References llvm::Sched::Source, llvm::cl::TokenizeGNUCommandLine(), and llvm::cl::TokenizeWindowsCommandLine().
Member Function Documentation
virtual const char* llvm::cl::StringSaver::SaveString (const char * Str) pure virtual
Referenced by llvm::cl::TokenizeGNUCommandLine(), and llvm::cl::TokenizeWindowsCommandLine().
The documentation for this class was generated from the following files:
CommandLine.h
CommandLine.cpp