LLVM: llvm::MCFunction Class Reference
LLVM API Documentation
llvm::MCFunction Class Reference
Represents a function in machine code, containing MCBasicBlocks. MCFunctions are created by MCModule.
#include <MCFunction.h>
Public Member Functions
MCBasicBlock & createBlock (const MCTextAtom &Insts)
Create an MCBasicBlock backed by Insts and add it to this function.
StringRef getName () const
Get the owning MC Module.
const MCModule * getParent () const
MCModule * getParent ()
Friends
class MCModule
Access to the function's basic blocks. No ordering is enforced,
Get the entry point basic block.
except that the first block is the entry block.
typedef BasicBlockListTy::const_iterator const_iterator
typedef BasicBlockListTy::iterator iterator
const MCBasicBlock * getEntryBlock () const
MCBasicBlock * getEntryBlock ()
bool empty () const
const_iterator begin () const
iterator begin ()
const_iterator end () const
iterator end ()
const MCBasicBlock * front () const
MCBasicBlock * front ()
const MCBasicBlock * back () const
MCBasicBlock * back ()
const MCBasicBlock * find (uint64_t StartAddr) const
Find the basic block, if any, that starts at StartAddr.
MCBasicBlock * find (uint64_t StartAddr)
Detailed Description
Represents a function in machine code, containing MCBasicBlocks. MCFunctions are created by MCModule.
Definition at line 85 of file MCFunction.h.
Member Typedef Documentation
typedef BasicBlockListTy::const_iterator llvm::MCFunction::const_iterator
Definition at line 122 of file MCFunction.h.
typedef BasicBlockListTy:: iterator llvm::MCFunction::iterator
Definition at line 123 of file MCFunction.h.
Member Function Documentation
const MCBasicBlock* llvm::MCFunction::back () const inline
Definition at line 131 of file MCFunction.h.
MCBasicBlock* llvm::MCFunction::back () inline
Definition at line 132 of file MCFunction.h.
const_iterator llvm::MCFunction::begin () const inline
Definition at line 124 of file MCFunction.h.
Referenced by llvm::yaml::ScalarTraits< MCModuleYAML::OpcodeEnum >::input().
iterator llvm::MCFunction::begin () inline
Definition at line 125 of file MCFunction.h.
MCBasicBlock & MCFunction::createBlock (const MCTextAtom & Insts)
Create an MCBasicBlock backed by Insts and add it to this function.
Parameters
Insts Sequence of straight-line code backing the basic block.
Returns
The newly created basic block.
Definition at line 28 of file MCFunction.cpp.
Referenced by CompBBToAtom(), llvm::yaml::ScalarTraits< MCModuleYAML::OpcodeEnum >::input(), and RemoveDupsFromAddressVector().
bool llvm::MCFunction::empty () const inline
Definition at line 120 of file MCFunction.h.
const_iterator llvm::MCFunction::end () const inline
Definition at line 126 of file MCFunction.h.
Referenced by llvm::yaml::ScalarTraits< MCModuleYAML::OpcodeEnum >::input().
iterator llvm::MCFunction::end () inline
Definition at line 127 of file MCFunction.h.
const MCBasicBlock * MCFunction::find (uint64_t StartAddr) const
Find the basic block, if any, that starts at StartAddr.
Definition at line 41 of file MCFunction.cpp.
References llvm::GlobalValue::getParent(), and getParent().
Referenced by llvm::yaml::ScalarTraits< MCModuleYAML::OpcodeEnum >::input(), and RemoveDupsFromAddressVector().
MCBasicBlock * MCFunction::find (uint64_t StartAddr)
Definition at line 34 of file MCFunction.cpp.
References llvm::sys::path::begin(), llvm::sys::path::end(), and I.
const MCBasicBlock* llvm::MCFunction::front () const inline
Definition at line 129 of file MCFunction.h.
MCBasicBlock* llvm::MCFunction::front () inline
Definition at line 130 of file MCFunction.h.
const MCBasicBlock* llvm::MCFunction::getEntryBlock () const inline
Definition at line 117 of file MCFunction.h.
MCBasicBlock* llvm::MCFunction::getEntryBlock () inline
Definition at line 118 of file MCFunction.h.
StringRef llvm::MCFunction::getName () const inline
Definition at line 105 of file MCFunction.h.
Referenced by llvm::yaml::ScalarTraits< MCModuleYAML::OpcodeEnum >::input().
const MCModule* llvm::MCFunction::getParent () const inline
Definition at line 109 of file MCFunction.h.
MCModule* llvm::MCFunction::getParent () inline
Definition at line 110 of file MCFunction.h.
Friends And Related Function Documentation
friend class MCModule friend
Definition at line 95 of file MCFunction.h.
The documentation for this class was generated from the following files:
MCFunction.h
MCFunction.cpp