LLVM: llvm::DWARFDebugFrame Class Reference
LLVM API Documentation
llvm::DWARFDebugFrame Class Reference
A parsed .debug_frame section.
#include <DWARFDebugFrame.h>
Public Member Functions
DWARFDebugFrame ()
~DWARFDebugFrame ()
void dump (raw_ostream &OS) const
Dump the section data into the given stream.
void parse (DataExtractor Data)
Parse the section from raw data. data is assumed to be pointing to the beginning of the section.
Detailed Description
A parsed .debug_frame section.
Definition at line 25 of file DWARFDebugFrame.h.
Constructor & Destructor Documentation
DWARFDebugFrame::DWARFDebugFrame ()
Definition at line 286 of file DWARFDebugFrame.cpp.
DWARFDebugFrame::~DWARFDebugFrame ()
Definition at line 290 of file DWARFDebugFrame.cpp.
References I.
Member Function Documentation
void DWARFDebugFrame::dump (raw_ostream & OS) const
Dump the section data into the given stream.
Definition at line 381 of file DWARFDebugFrame.cpp.
References llvm::FrameEntry::dumpHeader(), llvm::FrameEntry::dumpInstructions(), and I.
void DWARFDebugFrame::parse (DataExtractor Data)
Parse the section from raw data. data is assumed to be pointing to the beginning of the section.
Definition at line 309 of file DWARFDebugFrame.cpp.
References llvm::dwarf::DW64_CIE_ID, llvm::dwarf::DW_CIE_ID, llvm::format(), llvm::DataExtractor::getAddress(), llvm::DataExtractor::getCStr(), llvm::FrameEntry::getOffset(), llvm::DataExtractor::getSLEB128(), llvm::DataExtractor::getU32(), llvm::DataExtractor::getU64(), llvm::DataExtractor::getU8(), llvm::DataExtractor::getULEB128(), llvm::DataExtractor::getUnsigned(), llvm::tgtok::Id, llvm::DataExtractor::isValidOffset(), llvm::FrameEntry::parseInstructions(), and llvm::report_fatal_error().
The documentation for this class was generated from the following files:
DWARFDebugFrame.h
DWARFDebugFrame.cpp