LLVM: llvm::MachineSchedStrategy Class Reference
LLVM API Documentation
llvm::MachineSchedStrategy Class Reference abstract
#include <MachineScheduler.h>
Public Member Functions
virtual ~MachineSchedStrategy ()
virtual void initPolicy (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned NumRegionInstrs)
Optionally override the per-region scheduling policy.
virtual bool shouldTrackPressure () const
virtual void initialize (ScheduleDAGMI *DAG)=0
Initialize the strategy after building the DAG for a new region.
virtual void registerRoots ()
virtual SUnit * pickNode (bool &IsTopNode)=0
virtual void scheduleTree (unsigned SubtreeID)
Scheduler callback to notify that a new subtree is scheduled.
virtual void schedNode (SUnit *SU, bool IsTopNode)=0
virtual void releaseTopNode (SUnit *SU)=0
virtual void releaseBottomNode (SUnit *SU)=0
Detailed Description
MachineSchedStrategy - Interface to the scheduling algorithm used by ScheduleDAGMI.
Initialization sequence: initPolicy -> shouldTrackPressure -> initialize(DAG) -> registerRoots
Definition at line 166 of file MachineScheduler.h.
Constructor & Destructor Documentation
virtual llvm::MachineSchedStrategy::~MachineSchedStrategy () inline virtual
Definition at line 169 of file MachineScheduler.h.
Member Function Documentation
virtual void llvm::MachineSchedStrategy::initialize (ScheduleDAGMI * DAG) pure virtual
Initialize the strategy after building the DAG for a new region.
Implemented in llvm::ConvergingVLIWScheduler, and llvm::R600SchedStrategy.
Referenced by llvm::VLIWMachineScheduler::schedule().
virtual void llvm::MachineSchedStrategy::initPolicy (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned NumRegionInstrs) inline virtual
Optionally override the per-region scheduling policy.
Definition at line 172 of file MachineScheduler.h.
virtual SUnit* llvm::MachineSchedStrategy::pickNode (bool & IsTopNode) pure virtual
Pick the next node to schedule, or return NULL. Set IsTopNode to true to schedule the node at the top of the unscheduled region. Otherwise it will be scheduled at the bottom.
Implemented in llvm::ConvergingVLIWScheduler, and llvm::R600SchedStrategy.
Referenced by llvm::VLIWMachineScheduler::schedule().
virtual void llvm::MachineSchedStrategy::registerRoots () inline virtual
Notify this strategy that all roots have been released (including those that depend on EntrySU or ExitSU).
Definition at line 185 of file MachineScheduler.h.
virtual void llvm::MachineSchedStrategy::releaseBottomNode (SUnit * SU) pure virtual
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
Implemented in llvm::ConvergingVLIWScheduler, and llvm::R600SchedStrategy.
virtual void llvm::MachineSchedStrategy::releaseTopNode (SUnit * SU) pure virtual
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
Implemented in llvm::ConvergingVLIWScheduler, and llvm::R600SchedStrategy.
virtual void llvm::MachineSchedStrategy::schedNode (SUnit * SU, bool IsTopNode) pure virtual
Notify MachineSchedStrategy that ScheduleDAGMI has scheduled an instruction and updated scheduled/remaining flags in the DAG nodes.
Implemented in llvm::ConvergingVLIWScheduler, and llvm::R600SchedStrategy.
virtual void llvm::MachineSchedStrategy::scheduleTree (unsigned SubtreeID) inline virtual
Scheduler callback to notify that a new subtree is scheduled.
Definition at line 193 of file MachineScheduler.h.
virtual bool llvm::MachineSchedStrategy::shouldTrackPressure () const inline virtual
Check if pressure tracking is needed before building the DAG and initializing this strategy. Called after initPolicy.
Definition at line 178 of file MachineScheduler.h.
References initialize().
The documentation for this class was generated from the following files:
MachineScheduler.h
MachineScheduler.cpp