LLVM: llvm::TargetRegistry::iterator Class Reference
LLVM API Documentation
llvm::TargetRegistry::iterator Class Reference
#include <TargetRegistry.h>
Public Member Functions
iterator (const iterator &I)
iterator ()
bool operator== (const iterator &x) const
bool operator!= (const iterator &x) const
iterator & operator++ ()
iterator operator++ (int)
const Target & operator* () const
const Target * operator-> () const
Friends
struct TargetRegistry
Detailed Description
Definition at line 488 of file TargetRegistry.h.
Constructor & Destructor Documentation
llvm::TargetRegistry::iterator::iterator (const iterator & I) inline
Definition at line 493 of file TargetRegistry.h.
llvm::TargetRegistry::iterator::iterator () inline
Definition at line 494 of file TargetRegistry.h.
Member Function Documentation
bool llvm::TargetRegistry::iterator::operator!= (const iterator & x) const inline
Definition at line 499 of file TargetRegistry.h.
References llvm::operator==().
const Target& llvm::TargetRegistry::iterator::operator* () const inline
Definition at line 515 of file TargetRegistry.h.
iterator& llvm::TargetRegistry::iterator::operator++ () inline
Definition at line 504 of file TargetRegistry.h.
References llvm::Target::getNext().
iterator llvm::TargetRegistry::iterator::operator++ (int) inline
Definition at line 509 of file TargetRegistry.h.
const Target* llvm::TargetRegistry::iterator::operator-> () const inline
Definition at line 520 of file TargetRegistry.h.
References llvm::sys::path::begin().
bool llvm::TargetRegistry::iterator::operator== (const iterator & x) const inline
Definition at line 496 of file TargetRegistry.h.
Friends And Related Function Documentation
friend struct TargetRegistry friend
Definition at line 491 of file TargetRegistry.h.
The documentation for this class was generated from the following file:
TargetRegistry.h