LLVM: llvm::MCCodeEmitter Class Reference
LLVM API Documentation
llvm::MCCodeEmitter Class Reference abstract
MCCodeEmitter - Generic instruction encoding interface.
#include <MCCodeEmitter.h>
Public Member Functions
virtual ~MCCodeEmitter ()
virtual void reset ()
Lifetime management.
virtual void EncodeInstruction (const MCInst &Inst, raw_ostream &OS, SmallVectorImpl< MCFixup > &Fixups) const =0
Protected Member Functions
MCCodeEmitter ()
Detailed Description
MCCodeEmitter - Generic instruction encoding interface.
Definition at line 22 of file MCCodeEmitter.h.
Constructor & Destructor Documentation
MCCodeEmitter::MCCodeEmitter () protected
Definition at line 14 of file MCCodeEmitter.cpp.
MCCodeEmitter::~MCCodeEmitter () virtual
Definition at line 17 of file MCCodeEmitter.cpp.
Member Function Documentation
virtual void llvm::MCCodeEmitter::EncodeInstruction (const MCInst & Inst, raw_ostream & OS, SmallVectorImpl< MCFixup > & Fixups) const pure virtual
EncodeInstruction - Encode the given Inst to bytes on the output stream OS.
Referenced by llvm::MCELFStreamer::EmitIdent(), llvm::AMDGPUAsmPrinter::EmitInstruction(), llvm::MCObjectStreamer::EmitInstToFragment(), llvm::MCAssembler::Finish(), getWin64EHTableSection(), and reset().
virtual void llvm::MCCodeEmitter::reset () inline virtual
Lifetime management.
Definition at line 33 of file MCCodeEmitter.h.
References EncodeInstruction().
Referenced by llvm::MCAssembler::reset().
The documentation for this class was generated from the following files:
MCCodeEmitter.h
MCCodeEmitter.cpp