LLVM: llvm::TimeRecord Class Reference
LLVM API Documentation
llvm::TimeRecord Class Reference
#include <Timer.h>
Public Member Functions
TimeRecord ()
double getProcessTime () const
double getUserTime () const
double getSystemTime () const
double getWallTime () const
ssize_t getMemUsed () const
bool operator< (const TimeRecord &T) const
void operator+= (const TimeRecord &RHS)
void operator-= (const TimeRecord &RHS)
void print (const TimeRecord &Total, raw_ostream &OS) const
Static Public Member Functions
static TimeRecord getCurrentTime (bool Start=true)
Detailed Description
Definition at line 27 of file Timer.h.
Constructor & Destructor Documentation
llvm::TimeRecord::TimeRecord () inline
Definition at line 33 of file Timer.h.
References getCurrentTime().
Member Function Documentation
TimeRecord TimeRecord::getCurrentTime (bool Start = true) static
getCurrentTime - Get the current time and memory usage. If Start is true we get the memory usage before the time, otherwise we get time before memory usage. This matters if the time to get the memory usage is significant and shouldn't be counted as part of a duration.
Definition at line 129 of file Timer.cpp.
References getMemUsage(), llvm::sys::Process::GetTimeUsage(), llvm::sys::TimeValue::microseconds(), and llvm::sys::TimeValue::seconds().
Referenced by llvm::Timer::startTimer(), llvm::Timer::stopTimer(), and TimeRecord().
ssize_t llvm::TimeRecord::getMemUsed () const inline
Definition at line 45 of file Timer.h.
Referenced by print().
double llvm::TimeRecord::getProcessTime () const inline
Definition at line 41 of file Timer.h.
Referenced by print().
double llvm::TimeRecord::getSystemTime () const inline
Definition at line 43 of file Timer.h.
Referenced by print().
double llvm::TimeRecord::getUserTime () const inline
Definition at line 42 of file Timer.h.
Referenced by print().
double llvm::TimeRecord::getWallTime () const inline
Definition at line 44 of file Timer.h.
Referenced by print().
void llvm::TimeRecord::operator+= (const TimeRecord & RHS) inline
Definition at line 54 of file Timer.h.
void llvm::TimeRecord::operator-= (const TimeRecord & RHS) inline
Definition at line 60 of file Timer.h.
References print().
bool llvm::TimeRecord::operator< (const TimeRecord & T) const inline
Definition at line 49 of file Timer.h.
void TimeRecord::print (const TimeRecord & Total, raw_ostream & OS) const
print - Print the current timer to standard error, and reset the "Started" flag.
Definition at line 175 of file Timer.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::begin(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::format(), getMemUsed(), getProcessTime(), getSystemTime(), getUserTime(), getWallTime(), I, llvm::Timer::init(), llvm::Timer::isInitialized(), printVal(), T, and llvm::Timer::TimerGroup.
Referenced by operator-=(), and llvm::TimerGroup::setName().
The documentation for this class was generated from the following files:
Timer.h
Timer.cpp