LLVM: llvm::object::ELFObjectFile< ELFT > Class Template Reference
LLVM API Documentation
llvm::object::ELFObjectFile< ELFT > Class Template Reference
#include <ELFObjectFile.h>
Public Types
typedef ELFFile< ELFT >::uintX_t uintX_t
typedef ELFFile< ELFT >::Elf_Sym Elf_Sym
typedef ELFFile< ELFT >::Elf_Shdr Elf_Shdr
typedef ELFFile< ELFT >::Elf_Rel Elf_Rel
typedef ELFFile< ELFT >::Elf_Rela Elf_Rela
typedef ELFFile< ELFT >::Elf_Dyn Elf_Dyn
typedef ELFFile< ELFT >::Elf_Sym_Iter Elf_Sym_Iter
typedef ELFFile< ELFT >::Elf_Shdr_Iter Elf_Shdr_Iter
typedef ELFFile< ELFT >::Elf_Dyn_Iter Elf_Dyn_Iter
Public Member Functions
ELFObjectFile (MemoryBuffer *Object, error_code &ec)
const Elf_Sym * getSymbol (DataRefImpl Symb) const
virtual symbol_iterator begin_symbols () const
virtual symbol_iterator end_symbols () const
virtual symbol_iterator begin_dynamic_symbols () const
virtual symbol_iterator end_dynamic_symbols () const
virtual section_iterator begin_sections () const
virtual section_iterator end_sections () const
virtual library_iterator begin_libraries_needed () const
virtual library_iterator end_libraries_needed () const
error_code getRelocationAddend (DataRefImpl Rel, int64_t &Res) const
error_code getSymbolVersion (SymbolRef Symb, StringRef &Version, bool &IsDefault) const
virtual uint8_t getBytesInAddress () const
The number of bytes used to represent an address in this object file format.
virtual StringRef getFileFormatName () const
virtual StringRef getObjectType () const
virtual unsigned getArch () const
virtual StringRef getLoadName () const
const ELFFile< ELFT > * getELFFile () const
bool isDyldType () const
Public Member Functions inherited from llvm::object::Binary
virtual ~Binary ()
StringRef getData () const
StringRef getFileName () const
unsigned int getType () const
bool isObject () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isLittleEndian () const
Static Public Member Functions
static bool classof (const Binary *v)
Static Public Member Functions inherited from llvm::object::ObjectFile
static ObjectFile * createObjectFile (StringRef ObjectPath)
Create ObjectFile from path.
static ObjectFile * createObjectFile (MemoryBuffer *Object)
static bool classof (const Binary *v)
static ObjectFile * createCOFFObjectFile (MemoryBuffer *Object)
static ObjectFile * createELFObjectFile (MemoryBuffer *Object)
static ObjectFile * createMachOObjectFile (MemoryBuffer *Object)
Protected Member Functions
virtual error_code getSymbolNext (DataRefImpl Symb, SymbolRef &Res) const
virtual error_code getSymbolName (DataRefImpl Symb, StringRef &Res) const
virtual error_code getSymbolFileOffset (DataRefImpl Symb, uint64_t &Res) const
virtual error_code getSymbolAddress (DataRefImpl Symb, uint64_t &Res) const
virtual error_code getSymbolAlignment (DataRefImpl Symb, uint32_t &Res) const
virtual error_code getSymbolSize (DataRefImpl Symb, uint64_t &Res) const
virtual error_code getSymbolFlags (DataRefImpl Symb, uint32_t &Res) const
virtual error_code getSymbolType (DataRefImpl Symb, SymbolRef::Type &Res) const
virtual error_code getSymbolSection (DataRefImpl Symb, section_iterator &Res) const
virtual error_code getSymbolValue (DataRefImpl Symb, uint64_t &Val) const
virtual error_code getLibraryNext (DataRefImpl Data, LibraryRef &Result) const
virtual error_code getLibraryPath (DataRefImpl Data, StringRef &Res) const
virtual error_code getSectionNext (DataRefImpl Sec, SectionRef &Res) const
virtual error_code getSectionName (DataRefImpl Sec, StringRef &Res) const
virtual error_code getSectionAddress (DataRefImpl Sec, uint64_t &Res) const
virtual error_code getSectionSize (DataRefImpl Sec, uint64_t &Res) const
virtual error_code getSectionContents (DataRefImpl Sec, StringRef &Res) const
virtual error_code getSectionAlignment (DataRefImpl Sec, uint64_t &Res) const
virtual error_code isSectionText (DataRefImpl Sec, bool &Res) const
virtual error_code isSectionData (DataRefImpl Sec, bool &Res) const
virtual error_code isSectionBSS (DataRefImpl Sec, bool &Res) const
virtual error_code isSectionRequiredForExecution (DataRefImpl Sec, bool &Res) const
virtual error_code isSectionVirtual (DataRefImpl Sec, bool &Res) const
virtual error_code isSectionZeroInit (DataRefImpl Sec, bool &Res) const
virtual error_code isSectionReadOnlyData (DataRefImpl Sec, bool &Res) const
virtual error_code sectionContainsSymbol (DataRefImpl Sec, DataRefImpl Symb, bool &Result) const
virtual relocation_iterator section_rel_begin (DataRefImpl Sec) const
virtual relocation_iterator section_rel_end (DataRefImpl Sec) const
virtual section_iterator getRelocatedSection (DataRefImpl Sec) const
virtual error_code getRelocationNext (DataRefImpl Rel, RelocationRef &Res) const
virtual error_code getRelocationAddress (DataRefImpl Rel, uint64_t &Res) const
virtual error_code getRelocationOffset (DataRefImpl Rel, uint64_t &Res) const
virtual symbol_iterator getRelocationSymbol (DataRefImpl Rel) const
virtual error_code getRelocationType (DataRefImpl Rel, uint64_t &Res) const
virtual error_code getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > &Result) const
virtual error_code getRelocationValueString (DataRefImpl Rel, SmallVectorImpl< char > &Result) const
uint64_t getROffset (DataRefImpl Rel) const
StringRef getRelocationTypeName (uint32_t Type) const
const Elf_Shdr * getRelSection (DataRefImpl Rel) const
Get the relocation section that contains Rel.
const Elf_Rel * getRel (DataRefImpl Rel) const
const Elf_Rela * getRela (DataRefImpl Rela) const
Elf_Sym_Iter toELFSymIter (DataRefImpl Symb) const
DataRefImpl toDRI (Elf_Sym_Iter Symb) const
Elf_Shdr_Iter toELFShdrIter (DataRefImpl Sec) const
DataRefImpl toDRI (Elf_Shdr_Iter Sec) const
DataRefImpl toDRI (const Elf_Shdr *Sec) const
Elf_Dyn_Iter toELFDynIter (DataRefImpl Dyn) const
DataRefImpl toDRI (Elf_Dyn_Iter Dyn) const
Protected Member Functions inherited from llvm::object::ObjectFile
ObjectFile (unsigned int Type, MemoryBuffer *source)
const uint8_t * base () const
virtual error_code getRelocationHidden (DataRefImpl Rel, bool &Result) const
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBuffer *Source)
Protected Attributes
ELFFile< ELFT > EF
bool isDyldELFObject
Protected Attributes inherited from llvm::object::Binary
MemoryBuffer * Data
Additional Inherited Members
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive, ID_MachOUniversalBinary, ID_StartObjects, ID_COFF,
ID_ELF32L, ID_ELF32B, ID_ELF64L, ID_ELF64B,
ID_MachO32L, ID_MachO32B, ID_MachO64L, ID_MachO64B,
ID_EndObjects
}
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Detailed Description
template<class ELFT>
class llvm::object::ELFObjectFile< ELFT >
Definition at line 39 of file ELFObjectFile.h.
Member Typedef Documentation
template<class ELFT> typedef ELFFile<ELFT>::Elf_Dyn llvm::object::ELFObjectFile< ELFT >::Elf_Dyn
Definition at line 49 of file ELFObjectFile.h.
template<class ELFT> typedef ELFFile<ELFT>::Elf_Dyn_Iter llvm::object::ELFObjectFile< ELFT >::Elf_Dyn_Iter
Definition at line 53 of file ELFObjectFile.h.
template<class ELFT> typedef ELFFile<ELFT>::Elf_Rel llvm::object::ELFObjectFile< ELFT >::Elf_Rel
Definition at line 47 of file ELFObjectFile.h.
template<class ELFT> typedef ELFFile<ELFT>::Elf_Rela llvm::object::ELFObjectFile< ELFT >::Elf_Rela
Definition at line 48 of file ELFObjectFile.h.
template<class ELFT> typedef ELFFile<ELFT>::Elf_Shdr llvm::object::ELFObjectFile< ELFT >::Elf_Shdr
Definition at line 46 of file ELFObjectFile.h.
template<class ELFT> typedef ELFFile<ELFT>::Elf_Shdr_Iter llvm::object::ELFObjectFile< ELFT >::Elf_Shdr_Iter
Definition at line 52 of file ELFObjectFile.h.
template<class ELFT> typedef ELFFile<ELFT>::Elf_Sym llvm::object::ELFObjectFile< ELFT >::Elf_Sym
Definition at line 45 of file ELFObjectFile.h.
template<class ELFT> typedef ELFFile<ELFT>::Elf_Sym_Iter llvm::object::ELFObjectFile< ELFT >::Elf_Sym_Iter
Definition at line 51 of file ELFObjectFile.h.
template<class ELFT> typedef ELFFile<ELFT>::uintX_t llvm::object::ELFObjectFile< ELFT >::uintX_t
Definition at line 43 of file ELFObjectFile.h.
Constructor & Destructor Documentation
template<class ELFT > llvm::object::ELFObjectFile< ELFT >::ELFObjectFile (MemoryBuffer * Object, error_code & ec)
Definition at line 815 of file ELFObjectFile.h.
Member Function Documentation
template<class ELFT > symbol_iterator llvm::object::ELFObjectFile< ELFT >::begin_dynamic_symbols () const virtual
Implements llvm::object::ObjectFile.
Definition at line 833 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, llvm::object::ObjectFile::SymbolRef, and llvm::object::ELFObjectFile< ELFT >::toDRI().
template<class ELFT > library_iterator llvm::object::ELFObjectFile< ELFT >::begin_libraries_needed () const virtual
Implements llvm::object::ObjectFile.
Definition at line 866 of file ELFObjectFile.h.
References llvm::X86II::DE, llvm::ELF::DT_SONAME, llvm::object::ELFObjectFile< ELFT >::EF, llvm::object::ObjectFile::LibraryRef, and llvm::object::ELFObjectFile< ELFT >::toDRI().
template<class ELFT > section_iterator llvm::object::ELFObjectFile< ELFT >::begin_sections () const virtual
Implements llvm::object::ObjectFile.
Definition at line 843 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, llvm::object::ObjectFile::SectionRef, and llvm::object::ELFObjectFile< ELFT >::toDRI().
template<class ELFT > symbol_iterator llvm::object::ELFObjectFile< ELFT >::begin_symbols () const virtual
Implements llvm::object::ObjectFile.
Definition at line 823 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, llvm::object::ObjectFile::SymbolRef, and llvm::object::ELFObjectFile< ELFT >::toDRI().
template<class ELFT> static bool llvm::object::ELFObjectFile< ELFT >::classof (const Binary * v) inline static
Definition at line 197 of file ELFObjectFile.h.
References llvm::object::Binary::getELFType(), llvm::object::Binary::getType(), and llvm::support::little.
template<class ELFT > symbol_iterator llvm::object::ELFObjectFile< ELFT >::end_dynamic_symbols () const virtual
Implements llvm::object::ObjectFile.
Definition at line 838 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, llvm::object::ObjectFile::SymbolRef, and llvm::object::ELFObjectFile< ELFT >::toDRI().
template<class ELFT > library_iterator llvm::object::ELFObjectFile< ELFT >::end_libraries_needed () const virtual
Implements llvm::object::ObjectFile.
Definition at line 899 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, llvm::object::ObjectFile::LibraryRef, and llvm::object::ELFObjectFile< ELFT >::toDRI().
template<class ELFT > section_iterator llvm::object::ELFObjectFile< ELFT >::end_sections () const virtual
Implements llvm::object::ObjectFile.
Definition at line 848 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, llvm::object::ObjectFile::SectionRef, and llvm::object::ELFObjectFile< ELFT >::toDRI().
Referenced by llvm::object::ELFObjectFile< ELFT >::getRelocatedSection(), and llvm::object::ELFObjectFile< ELFT >::getSymbolSection().
template<class ELFT > symbol_iterator llvm::object::ELFObjectFile< ELFT >::end_symbols () const virtual
Implements llvm::object::ObjectFile.
Definition at line 828 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, llvm::object::ObjectFile::SymbolRef, and llvm::object::ELFObjectFile< ELFT >::toDRI().
Referenced by llvm::object::ELFObjectFile< ELFT >::getRelocationSymbol().
template<class ELFT > unsigned llvm::object::ELFObjectFile< ELFT >::getArch () const virtual
Implements llvm::object::ObjectFile.
Definition at line 950 of file ELFObjectFile.h.
References llvm::Triple::aarch64, llvm::Triple::arm, llvm::object::ELFObjectFile< ELFT >::EF, llvm::ELF::EM_386, llvm::ELF::EM_AARCH64, llvm::ELF::EM_ARM, llvm::ELF::EM_HEXAGON, llvm::ELF::EM_MIPS, llvm::ELF::EM_PPC64, llvm::ELF::EM_S390, llvm::ELF::EM_X86_64, llvm::Triple::hexagon, llvm::support::little, llvm::Triple::mips, llvm::Triple::mipsel, llvm::Triple::ppc64, llvm::Triple::ppc64le, llvm::Triple::systemz, llvm::Triple::UnknownArch, llvm::Triple::x86, and llvm::Triple::x86_64.
Referenced by llvm::object::ELFObjectFile< ELFT >::getObjectType().
template<class ELFT > uint8_t llvm::object::ELFObjectFile< ELFT >::getBytesInAddress () const virtual
The number of bytes used to represent an address in this object file format.
Implements llvm::object::ObjectFile.
Definition at line 904 of file ELFObjectFile.h.
template<class ELFT> const ELFFile<ELFT>* llvm::object::ELFObjectFile< ELFT >::getELFFile () const inline
Definition at line 194 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF.
Referenced by llvm::MCObjectSymbolizer::findRelocationAt().
template<class ELFT > StringRef llvm::object::ELFObjectFile< ELFT >::getFileFormatName () const virtual
Implements llvm::object::ObjectFile.
Definition at line 909 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, llvm::ELF::EI_CLASS, llvm::ELF::ELFCLASS32, llvm::ELF::ELFCLASS64, llvm::ELF::EM_386, llvm::ELF::EM_AARCH64, llvm::ELF::EM_ARM, llvm::ELF::EM_HEXAGON, llvm::ELF::EM_MIPS, llvm::ELF::EM_PPC, llvm::ELF::EM_PPC64, llvm::ELF::EM_S390, llvm::ELF::EM_X86_64, and llvm::report_fatal_error().
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getLibraryNext (DataRefImpl Data, LibraryRef & Result) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 877 of file ELFObjectFile.h.
References llvm::X86II::DE, llvm::ELF::DT_NEEDED, llvm::object::ELFObjectFile< ELFT >::EF, llvm::object::ObjectFile::LibraryRef, llvm::object::object_error::success, llvm::object::ELFObjectFile< ELFT >::toDRI(), and llvm::object::ELFObjectFile< ELFT >::toELFDynIter().
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getLibraryPath (DataRefImpl Data, StringRef & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 892 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, llvm::object::object_error::success, and llvm::object::ELFObjectFile< ELFT >::toELFDynIter().
template<class ELFT > StringRef llvm::object::ELFObjectFile< ELFT >::getLoadName () const virtual
For shared objects, returns the name which this object should be loaded from at runtime. This corresponds to DT_SONAME on ELF and LC_ID_DYLIB (install name) on MachO.
Implements llvm::object::ObjectFile.
Definition at line 853 of file ELFObjectFile.h.
References llvm::X86II::DE, llvm::ELF::DT_SONAME, and llvm::object::ELFObjectFile< ELFT >::EF.
Referenced by llvm::object::ELFObjectFile< ELFT >::getObjectType().
template<class ELFT> virtual StringRef llvm::object::ELFObjectFile< ELFT >::getObjectType () const inline virtual
Definition at line 190 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::getArch(), and llvm::object::ELFObjectFile< ELFT >::getLoadName().
template<class ELFT > const ELFObjectFile< ELFT >::Elf_Rel * llvm::object::ELFObjectFile< ELFT >::getRel (DataRefImpl Rel) const protected
Definition at line 804 of file ELFObjectFile.h.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::b, llvm::object::DataRefImpl::d, and llvm::object::ELFObjectFile< ELFT >::EF.
Referenced by llvm::object::ELFObjectFile< ELFT >::getRelocationSymbol(), llvm::object::ELFObjectFile< ELFT >::getRelocationType(), llvm::object::ELFObjectFile< ELFT >::getRelocationTypeName(), llvm::object::ELFObjectFile< ELFT >::getRelocationValueString(), llvm::object::ELFObjectFile< ELFT >::getRelSection(), and llvm::object::ELFObjectFile< ELFT >::getROffset().
template<class ELFT > const ELFObjectFile< ELFT >::Elf_Rela * llvm::object::ELFObjectFile< ELFT >::getRela (DataRefImpl Rela) const protected
Definition at line 810 of file ELFObjectFile.h.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::b, llvm::object::DataRefImpl::d, and llvm::object::ELFObjectFile< ELFT >::EF.
Referenced by llvm::object::ELFObjectFile< ELFT >::getRelocationAddend(), llvm::object::ELFObjectFile< ELFT >::getRelocationSymbol(), llvm::object::ELFObjectFile< ELFT >::getRelocationType(), llvm::object::ELFObjectFile< ELFT >::getRelocationTypeName(), llvm::object::ELFObjectFile< ELFT >::getRelocationValueString(), llvm::object::ELFObjectFile< ELFT >::getRelSection(), and llvm::object::ELFObjectFile< ELFT >::getROffset().
template<class ELFT > section_iterator llvm::object::ELFObjectFile< ELFT >::getRelocatedSection (DataRefImpl Sec) const protected virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 567 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, llvm::object::ELFObjectFile< ELFT >::end_sections(), llvm::ELF::ET_REL, llvm::object::ObjectFile::SectionRef, llvm::object::ELFObjectFile< ELFT >::toDRI(), and llvm::object::ELFObjectFile< ELFT >::toELFShdrIter().
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getRelocationAddend (DataRefImpl Rel, int64_t & Res) const
Definition at line 700 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::getRela(), llvm::object::ELFObjectFile< ELFT >::getRelSection(), llvm::report_fatal_error(), and llvm::object::object_error::success.
Referenced by llvm::object::RelocVisitor::error().
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getRelocationAddress (DataRefImpl Rel, uint64_t & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 627 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::getROffset(), and llvm::object::object_error::success.
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getRelocationNext (DataRefImpl Rel, RelocationRef & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 582 of file ELFObjectFile.h.
References llvm::object::DataRefImpl::b, llvm::object::DataRefImpl::d, llvm::object::ObjectFile::RelocationRef, and llvm::object::object_error::success.
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getRelocationOffset (DataRefImpl Rel, uint64_t & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 634 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::getROffset(), and llvm::object::object_error::success.
template<class ELFT > symbol_iterator llvm::object::ELFObjectFile< ELFT >::getRelocationSymbol (DataRefImpl Rel) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 591 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, llvm::object::ELFObjectFile< ELFT >::end_symbols(), llvm::object::ELFObjectFile< ELFT >::getRel(), llvm::object::ELFObjectFile< ELFT >::getRela(), llvm::object::ELFObjectFile< ELFT >::getRelSection(), llvm::report_fatal_error(), llvm::object::ObjectFile::SymbolRef, and llvm::object::ELFObjectFile< ELFT >::toDRI().
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getRelocationType (DataRefImpl Rel, uint64_t & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 654 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, llvm::object::ELFObjectFile< ELFT >::getRel(), llvm::object::ELFObjectFile< ELFT >::getRela(), llvm::object::ELFObjectFile< ELFT >::getRelSection(), llvm::report_fatal_error(), and llvm::object::object_error::success.
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > & Result) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 678 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, llvm::object::ELFObjectFile< ELFT >::getRel(), llvm::object::ELFObjectFile< ELFT >::getRela(), llvm::object::ELFObjectFile< ELFT >::getRelSection(), llvm::object::object_error::parse_failed, llvm::object::object_error::success, and type.
template<class ELFT > StringRef llvm::object::ELFObjectFile< ELFT >::getRelocationTypeName (uint32_t Type) const protected
Definition at line 673 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, llvm::object::getELFRelocationTypeName(), and Type.
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getRelocationValueString (DataRefImpl Rel, SmallVectorImpl< char > & Result) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 718 of file ELFObjectFile.h.
References llvm::SmallVectorImpl< T >::append(), llvm::StringRef::begin(), llvm::object::ELFObjectFile< ELFT >::EF, llvm::ELF::EM_AARCH64, llvm::ELF::EM_ARM, llvm::ELF::EM_HEXAGON, llvm::ELF::EM_X86_64, llvm::SmallVectorBase::empty(), llvm::StringRef::end(), llvm::raw_ostream::flush(), llvm::object::ELFObjectFile< ELFT >::getRel(), llvm::object::ELFObjectFile< ELFT >::getRela(), llvm::object::ELFObjectFile< ELFT >::getRelSection(), llvm::object::object_error::parse_failed, llvm::ELF::R_X86_64_16, llvm::ELF::R_X86_64_32, llvm::ELF::R_X86_64_32S, llvm::ELF::R_X86_64_64, llvm::ELF::R_X86_64_8, llvm::ELF::R_X86_64_PC16, llvm::ELF::R_X86_64_PC32, llvm::ELF::R_X86_64_PC8, llvm::object::object_error::success, and type.
template<class ELFT> const Elf_Shdr* llvm::object::ELFObjectFile< ELFT >::getRelSection (DataRefImpl Rel) const inline protected
Get the relocation section that contains Rel.
Definition at line 110 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::getRel(), and llvm::object::ELFObjectFile< ELFT >::getRela().
Referenced by llvm::object::ELFObjectFile< ELFT >::getRelocationAddend(), llvm::object::ELFObjectFile< ELFT >::getRelocationSymbol(), llvm::object::ELFObjectFile< ELFT >::getRelocationType(), llvm::object::ELFObjectFile< ELFT >::getRelocationTypeName(), llvm::object::ELFObjectFile< ELFT >::getRelocationValueString(), and llvm::object::ELFObjectFile< ELFT >::getROffset().
template<class ELFT > uint64_t llvm::object::ELFObjectFile< ELFT >::getROffset (DataRefImpl Rel) const protected
Definition at line 641 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::getRel(), llvm::object::ELFObjectFile< ELFT >::getRela(), llvm::object::ELFObjectFile< ELFT >::getRelSection(), and llvm::report_fatal_error().
Referenced by llvm::object::ELFObjectFile< ELFT >::getRelocationAddress(), and llvm::object::ELFObjectFile< ELFT >::getRelocationOffset().
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getSectionAddress (DataRefImpl Sec, uint64_t & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 444 of file ELFObjectFile.h.
References llvm::object::object_error::success, and llvm::object::ELFObjectFile< ELFT >::toELFShdrIter().
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getSectionAlignment (DataRefImpl Sec, uint64_t & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 466 of file ELFObjectFile.h.
References llvm::object::object_error::success, and llvm::object::ELFObjectFile< ELFT >::toELFShdrIter().
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getSectionContents (DataRefImpl Sec, StringRef & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 458 of file ELFObjectFile.h.
References llvm::object::ObjectFile::base(), llvm::object::object_error::success, and llvm::object::ELFObjectFile< ELFT >::toELFShdrIter().
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getSectionName (DataRefImpl Sec, StringRef & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 434 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, llvm::object::object_error::success, and llvm::object::ELFObjectFile< ELFT >::toELFShdrIter().
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getSectionNext (DataRefImpl Sec, SectionRef & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 427 of file ELFObjectFile.h.
References llvm::object::ObjectFile::SectionRef, llvm::object::object_error::success, llvm::object::ELFObjectFile< ELFT >::toDRI(), and llvm::object::ELFObjectFile< ELFT >::toELFShdrIter().
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getSectionSize (DataRefImpl Sec, uint64_t & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 451 of file ELFObjectFile.h.
References llvm::object::object_error::success, and llvm::object::ELFObjectFile< ELFT >::toELFShdrIter().
template<class ELFT > const ELFFile< ELFT >::Elf_Sym * llvm::object::ELFObjectFile< ELFT >::getSymbol (DataRefImpl Symb) const
Definition at line 798 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::toELFSymIter().
Referenced by llvm::object::ELFObjectFile< ELFT >::getSymbolAddress(), llvm::object::ELFObjectFile< ELFT >::getSymbolFileOffset(), llvm::object::ELFObjectFile< ELFT >::getSymbolFlags(), llvm::object::ELFObjectFile< ELFT >::getSymbolSection(), llvm::object::ELFObjectFile< ELFT >::getSymbolType(), llvm::object::ELFObjectFile< ELFT >::getSymbolValue(), and llvm::object::ELFObjectFile< ELFT >::getSymbolVersion().
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getSymbolAddress (DataRefImpl Symb, uint64_t & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 275 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, llvm::ELF::EM_ARM, llvm::ELF::ET_DYN, llvm::ELF::ET_EXEC, llvm::object::ELFObjectFile< ELFT >::getSymbol(), llvm::object::Elf_Sym_Impl< ELFT >::getType(), llvm::ELF::SHN_ABS, llvm::ELF::SHN_COMMON, llvm::ELF::SHN_UNDEF, llvm::ELF::STT_FUNC, llvm::ELF::STT_NOTYPE, llvm::ELF::STT_OBJECT, llvm::ELF::STT_SECTION, llvm::object::object_error::success, and llvm::object::UnknownAddressOrSize.
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getSymbolAlignment (DataRefImpl Symb, uint32_t & Res) const protected virtual
Reimplemented from llvm::object::ObjectFile.
Definition at line 323 of file ELFObjectFile.h.
References llvm::ELF::SHN_COMMON, llvm::object::object_error::success, and llvm::object::ELFObjectFile< ELFT >::toELFSymIter().
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getSymbolFileOffset (DataRefImpl Symb, uint64_t & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 242 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, llvm::object::ELFObjectFile< ELFT >::getSymbol(), llvm::object::Elf_Sym_Impl< ELFT >::getType(), llvm::ELF::SHN_ABS, llvm::ELF::SHN_COMMON, llvm::ELF::SHN_UNDEF, llvm::ELF::STT_FUNC, llvm::ELF::STT_NOTYPE, llvm::ELF::STT_OBJECT, llvm::ELF::STT_SECTION, llvm::object::object_error::success, and llvm::object::UnknownAddressOrSize.
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getSymbolFlags (DataRefImpl Symb, uint32_t & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 371 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, llvm::object::Elf_Sym_Impl< ELFT >::getBinding(), llvm::object::ELFObjectFile< ELFT >::getSymbol(), llvm::object::Elf_Sym_Impl< ELFT >::getType(), llvm::ELF::SHN_ABS, llvm::ELF::SHN_COMMON, llvm::ELF::SHN_UNDEF, llvm::ELF::STB_LOCAL, llvm::ELF::STB_WEAK, llvm::ELF::STT_COMMON, llvm::ELF::STT_FILE, llvm::ELF::STT_SECTION, llvm::ELF::STT_TLS, and llvm::object::object_error::success.
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getSymbolName (DataRefImpl Symb, StringRef & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 218 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, llvm::object::object_error::success, and llvm::object::ELFObjectFile< ELFT >::toELFSymIter().
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getSymbolNext (DataRefImpl Symb, SymbolRef & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 211 of file ELFObjectFile.h.
References llvm::object::object_error::success, llvm::object::ObjectFile::SymbolRef, llvm::object::ELFObjectFile< ELFT >::toDRI(), and llvm::object::ELFObjectFile< ELFT >::toELFSymIter().
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getSymbolSection (DataRefImpl Symb, section_iterator & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 404 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, llvm::object::ELFObjectFile< ELFT >::end_sections(), llvm::object::ELFObjectFile< ELFT >::getSymbol(), llvm::object::DataRefImpl::p, llvm::object::ObjectFile::SectionRef, and llvm::object::object_error::success.
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getSymbolSize (DataRefImpl Symb, uint64_t & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 334 of file ELFObjectFile.h.
References llvm::object::object_error::success, and llvm::object::ELFObjectFile< ELFT >::toELFSymIter().
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getSymbolType (DataRefImpl Symb, SymbolRef::Type & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 341 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::getSymbol(), llvm::object::Elf_Sym_Impl< ELFT >::getType(), llvm::object::SymbolRef::ST_Data, llvm::object::SymbolRef::ST_Debug, llvm::object::SymbolRef::ST_File, llvm::object::SymbolRef::ST_Function, llvm::object::SymbolRef::ST_Other, llvm::object::SymbolRef::ST_Unknown, llvm::ELF::STT_COMMON, llvm::ELF::STT_FILE, llvm::ELF::STT_FUNC, llvm::ELF::STT_NOTYPE, llvm::ELF::STT_OBJECT, llvm::ELF::STT_SECTION, llvm::ELF::STT_TLS, and llvm::object::object_error::success.
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getSymbolValue (DataRefImpl Symb, uint64_t & Val) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 419 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::getSymbol(), and llvm::object::object_error::success.
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::getSymbolVersion (SymbolRef Symb, StringRef & Version, bool & IsDefault) const
Definition at line 228 of file ELFObjectFile.h.
References llvm::object::DataRefImpl::b, llvm::object::DataRefImpl::d, llvm::object::ELFObjectFile< ELFT >::EF, llvm::object::SymbolRef::getRawDataRefImpl(), llvm::object::ELFObjectFile< ELFT >::getSymbol(), and llvm::object::object_error::success.
template<class ELFT> bool llvm::object::ELFObjectFile< ELFT >::isDyldType () const inline
Definition at line 196 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::isDyldELFObject.
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::isSectionBSS (DataRefImpl Sec, bool & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 489 of file ELFObjectFile.h.
References llvm::object::object_error::success, and llvm::object::ELFObjectFile< ELFT >::toELFShdrIter().
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::isSectionData (DataRefImpl Sec, bool & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 480 of file ELFObjectFile.h.
References llvm::object::object_error::success, and llvm::object::ELFObjectFile< ELFT >::toELFShdrIter().
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::isSectionReadOnlyData (DataRefImpl Sec, bool & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 520 of file ELFObjectFile.h.
References llvm::object::object_error::success, and llvm::object::ELFObjectFile< ELFT >::toELFShdrIter().
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::isSectionRequiredForExecution (DataRefImpl Sec, bool & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 499 of file ELFObjectFile.h.
References llvm::object::object_error::success, and llvm::object::ELFObjectFile< ELFT >::toELFShdrIter().
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::isSectionText (DataRefImpl Sec, bool & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 473 of file ELFObjectFile.h.
References llvm::object::object_error::success, and llvm::object::ELFObjectFile< ELFT >::toELFShdrIter().
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::isSectionVirtual (DataRefImpl Sec, bool & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 506 of file ELFObjectFile.h.
References llvm::object::object_error::success, and llvm::object::ELFObjectFile< ELFT >::toELFShdrIter().
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::isSectionZeroInit (DataRefImpl Sec, bool & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 513 of file ELFObjectFile.h.
References llvm::object::object_error::success, and llvm::object::ELFObjectFile< ELFT >::toELFShdrIter().
template<class ELFT > relocation_iterator llvm::object::ELFObjectFile< ELFT >::section_rel_begin (DataRefImpl Sec) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 542 of file ELFObjectFile.h.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::b, llvm::object::DataRefImpl::d, llvm::object::ELFObjectFile< ELFT >::EF, llvm::object::DataRefImpl::p, and llvm::object::ObjectFile::RelocationRef.
template<class ELFT > relocation_iterator llvm::object::ELFObjectFile< ELFT >::section_rel_end (DataRefImpl Sec) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 552 of file ELFObjectFile.h.
References llvm::object::DataRefImpl::a, llvm::object::DataRefImpl::b, llvm::object::DataRefImpl::d, llvm::object::ELFObjectFile< ELFT >::EF, llvm::object::DataRefImpl::p, llvm::object::ObjectFile::RelocationRef, and S.
template<class ELFT > error_code llvm::object::ELFObjectFile< ELFT >::sectionContainsSymbol (DataRefImpl Sec, DataRefImpl Symb, bool & Result) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 528 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, llvm::ELF::SHN_HIRESERVE, llvm::ELF::SHN_LORESERVE, llvm::object::object_error::success, llvm::object::ELFObjectFile< ELFT >::toELFShdrIter(), and llvm::object::ELFObjectFile< ELFT >::toELFSymIter().
template<class ELFT> DataRefImpl llvm::object::ELFObjectFile< ELFT >::toDRI (Elf_Sym_Iter Symb) const inline protected
Definition at line 127 of file ELFObjectFile.h.
References llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::get(), llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::isDynamic(), and llvm::object::DataRefImpl::p.
Referenced by llvm::object::ELFObjectFile< ELFT >::begin_dynamic_symbols(), llvm::object::ELFObjectFile< ELFT >::begin_libraries_needed(), llvm::object::ELFObjectFile< ELFT >::begin_sections(), llvm::object::ELFObjectFile< ELFT >::begin_symbols(), llvm::object::ELFObjectFile< ELFT >::end_dynamic_symbols(), llvm::object::ELFObjectFile< ELFT >::end_libraries_needed(), llvm::object::ELFObjectFile< ELFT >::end_sections(), llvm::object::ELFObjectFile< ELFT >::end_symbols(), llvm::object::ELFObjectFile< ELFT >::getLibraryNext(), llvm::object::ELFObjectFile< ELFT >::getRelocatedSection(), llvm::object::ELFObjectFile< ELFT >::getRelocationSymbol(), llvm::object::ELFObjectFile< ELFT >::getSectionNext(), and llvm::object::ELFObjectFile< ELFT >::getSymbolNext().
template<class ELFT> DataRefImpl llvm::object::ELFObjectFile< ELFT >::toDRI (Elf_Shdr_Iter Sec) const inline protected
Definition at line 139 of file ELFObjectFile.h.
References llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT >::get(), and llvm::object::DataRefImpl::p.
template<class ELFT> DataRefImpl llvm::object::ELFObjectFile< ELFT >::toDRI (const Elf_Shdr * Sec) const inline protected
Definition at line 145 of file ELFObjectFile.h.
References llvm::object::DataRefImpl::p.
template<class ELFT> DataRefImpl llvm::object::ELFObjectFile< ELFT >::toDRI (Elf_Dyn_Iter Dyn) const inline protected
Definition at line 156 of file ELFObjectFile.h.
References llvm::object::ELFFile< ELFT >::ELFEntityIterator< EntT >::get(), and llvm::object::DataRefImpl::p.
template<class ELFT> Elf_Dyn_Iter llvm::object::ELFObjectFile< ELFT >::toELFDynIter (DataRefImpl Dyn) const inline protected
Definition at line 151 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, and llvm::object::DataRefImpl::p.
Referenced by llvm::object::ELFObjectFile< ELFT >::getLibraryNext(), and llvm::object::ELFObjectFile< ELFT >::getLibraryPath().
template<class ELFT> Elf_Shdr_Iter llvm::object::ELFObjectFile< ELFT >::toELFShdrIter (DataRefImpl Sec) const inline protected
Definition at line 134 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, and llvm::object::DataRefImpl::p.
Referenced by llvm::object::ELFObjectFile< ELFT >::getRelocatedSection(), llvm::object::ELFObjectFile< ELFT >::getSectionAddress(), llvm::object::ELFObjectFile< ELFT >::getSectionAlignment(), llvm::object::ELFObjectFile< ELFT >::getSectionContents(), llvm::object::ELFObjectFile< ELFT >::getSectionName(), llvm::object::ELFObjectFile< ELFT >::getSectionNext(), llvm::object::ELFObjectFile< ELFT >::getSectionSize(), llvm::object::ELFObjectFile< ELFT >::isSectionBSS(), llvm::object::ELFObjectFile< ELFT >::isSectionData(), llvm::object::ELFObjectFile< ELFT >::isSectionReadOnlyData(), llvm::object::ELFObjectFile< ELFT >::isSectionRequiredForExecution(), llvm::object::ELFObjectFile< ELFT >::isSectionText(), llvm::object::ELFObjectFile< ELFT >::isSectionVirtual(), llvm::object::ELFObjectFile< ELFT >::isSectionZeroInit(), and llvm::object::ELFObjectFile< ELFT >::sectionContainsSymbol().
template<class ELFT> Elf_Sym_Iter llvm::object::ELFObjectFile< ELFT >::toELFSymIter (DataRefImpl Symb) const inline protected
Definition at line 117 of file ELFObjectFile.h.
References llvm::object::ELFObjectFile< ELFT >::EF, and llvm::object::DataRefImpl::p.
Referenced by llvm::object::ELFObjectFile< ELFT >::getSymbol(), llvm::object::ELFObjectFile< ELFT >::getSymbolAlignment(), llvm::object::ELFObjectFile< ELFT >::getSymbolName(), llvm::object::ELFObjectFile< ELFT >::getSymbolNext(), llvm::object::ELFObjectFile< ELFT >::getSymbolSize(), and llvm::object::ELFObjectFile< ELFT >::sectionContainsSymbol().
Member Data Documentation
template<class ELFT> ELFFile<ELFT> llvm::object::ELFObjectFile< ELFT >::EF protected
Definition at line 56 of file ELFObjectFile.h.
Referenced by llvm::object::ELFObjectFile< ELFT >::begin_dynamic_symbols(), llvm::object::ELFObjectFile< ELFT >::begin_libraries_needed(), llvm::object::ELFObjectFile< ELFT >::begin_sections(), llvm::object::ELFObjectFile< ELFT >::begin_symbols(), llvm::object::ELFObjectFile< ELFT >::end_dynamic_symbols(), llvm::object::ELFObjectFile< ELFT >::end_libraries_needed(), llvm::object::ELFObjectFile< ELFT >::end_sections(), llvm::object::ELFObjectFile< ELFT >::end_symbols(), llvm::object::ELFObjectFile< ELFT >::getArch(), llvm::object::ELFObjectFile< ELFT >::getELFFile(), llvm::object::ELFObjectFile< ELFT >::getFileFormatName(), llvm::object::ELFObjectFile< ELFT >::getLibraryNext(), llvm::object::ELFObjectFile< ELFT >::getLibraryPath(), llvm::object::ELFObjectFile< ELFT >::getLoadName(), llvm::object::ELFObjectFile< ELFT >::getRel(), llvm::object::ELFObjectFile< ELFT >::getRela(), llvm::object::ELFObjectFile< ELFT >::getRelocatedSection(), llvm::object::ELFObjectFile< ELFT >::getRelocationSymbol(), llvm::object::ELFObjectFile< ELFT >::getRelocationType(), llvm::object::ELFObjectFile< ELFT >::getRelocationTypeName(), llvm::object::ELFObjectFile< ELFT >::getRelocationValueString(), llvm::object::ELFObjectFile< ELFT >::getSectionName(), llvm::object::ELFObjectFile< ELFT >::getSymbolAddress(), llvm::object::ELFObjectFile< ELFT >::getSymbolFileOffset(), llvm::object::ELFObjectFile< ELFT >::getSymbolFlags(), llvm::object::ELFObjectFile< ELFT >::getSymbolName(), llvm::object::ELFObjectFile< ELFT >::getSymbolSection(), llvm::object::ELFObjectFile< ELFT >::getSymbolVersion(), llvm::object::ELFObjectFile< ELFT >::section_rel_begin(), llvm::object::ELFObjectFile< ELFT >::section_rel_end(), llvm::object::ELFObjectFile< ELFT >::sectionContainsSymbol(), llvm::object::ELFObjectFile< ELFT >::toELFDynIter(), llvm::object::ELFObjectFile< ELFT >::toELFShdrIter(), and llvm::object::ELFObjectFile< ELFT >::toELFSymIter().
template<class ELFT> bool llvm::object::ELFObjectFile< ELFT >::isDyldELFObject protected
Definition at line 165 of file ELFObjectFile.h.
Referenced by llvm::object::ELFObjectFile< ELFT >::isDyldType().
The documentation for this class was generated from the following file:
ELFObjectFile.h