LLVM: llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_iterator Class Reference
LLVM API Documentation
llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_iterator Class Reference
Iterator for PHI operands.
Public Member Functions
PHI_iterator (MachineInstr *P)
PHI_iterator (MachineInstr *P, bool)
PHI_iterator & operator++ ()
bool operator== (const PHI_iterator &x) const
bool operator!= (const PHI_iterator &x) const
unsigned getIncomingValue ()
MachineBasicBlock * getIncomingBlock ()
Detailed Description
template<>
class llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_iterator
Iterator for PHI operands.
Definition at line 258 of file MachineSSAUpdater.cpp.
Constructor & Destructor Documentation
llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_iterator::PHI_iterator (MachineInstr * P) inline explicit
Definition at line 264 of file MachineSSAUpdater.cpp.
llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_iterator::PHI_iterator (MachineInstr * P, bool) inline
Definition at line 266 of file MachineSSAUpdater.cpp.
Member Function Documentation
MachineBasicBlock* llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_iterator::getIncomingBlock () inline
Definition at line 273 of file MachineSSAUpdater.cpp.
References llvm::MachineOperand::getMBB(), and llvm::MachineInstr::getOperand().
unsigned llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_iterator::getIncomingValue () inline
Definition at line 272 of file MachineSSAUpdater.cpp.
References llvm::MachineInstr::getOperand(), and llvm::MachineOperand::getReg().
bool llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_iterator::operator!= (const PHI_iterator & x) const inline
Definition at line 271 of file MachineSSAUpdater.cpp.
References llvm::operator==().
PHI_iterator& llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_iterator::operator++ () inline
Definition at line 269 of file MachineSSAUpdater.cpp.
bool llvm::SSAUpdaterTraits< MachineSSAUpdater >::PHI_iterator::operator== (const PHI_iterator & x) const inline
Definition at line 270 of file MachineSSAUpdater.cpp.
The documentation for this class was generated from the following file:
MachineSSAUpdater.cpp