LLVM: llvm::iplist< NodeTy, Traits > Class Template Reference
LLVM API Documentation
llvm::iplist< NodeTy, Traits > Class Template Reference
#include <ilist.h>
Public Types
typedef NodeTy * pointer
typedef const NodeTy * const_pointer
typedef NodeTy & reference
typedef const NodeTy & const_reference
typedef NodeTy value_type
typedef ilist_iterator< NodeTy > iterator
typedef ilist_iterator< const NodeTy > const_iterator
typedef size_t size_type
typedef ptrdiff_t difference_type
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
typedef std::reverse_iterator< iterator > reverse_iterator
Public Member Functions
iplist ()
~iplist ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type max_size () const
bool LLVM_ATTRIBUTE_UNUSED_RESULT empty () const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
void swap (iplist &RHS)
iterator insert (iterator where, NodeTy *New)
iterator insertAfter (iterator where, NodeTy *New)
NodeTy * remove (iterator &IT)
NodeTy * remove (const iterator &IT)
iterator erase (iterator where)
void clearAndLeakNodesUnsafely ()
size_type LLVM_ATTRIBUTE_UNUSED_RESULT size () const
iterator erase (iterator first, iterator last)
void clear ()
void push_front (NodeTy *val)
void push_back (NodeTy *val)
void pop_front ()
void pop_back ()
template<class InIt >
void insert (iterator where, InIt first, InIt last)
void splice (iterator where, iplist &L2)
void splice (iterator where, iplist &L2, iterator first)
void splice (iterator where, iplist &L2, iterator first, iterator last)
void erase (const NodeTy &val)
template<class Pr1 >
void erase_if (Pr1 pred)
template<class Pr2 >
void unique (Pr2 pred)
void unique ()
template<class Pr3 >
void merge (iplist &right, Pr3 pred)
void merge (iplist &right)
template<class Pr3 >
void sort (Pr3 pred)
void sort ()
Detailed Description
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>>
class llvm::iplist< NodeTy, Traits >
iplist - The subset of list functionality that can safely be used on nodes of polymorphic types, i.e. a heterogeneous list with a common base class that holds the next/prev pointers. The only state of the list itself is a single pointer to the head of the list.
This list can be in one of three interesting states:
The list may be completely unconstructed. In this case, the head pointer is null. When in this form, any query for an iterator (e.g. begin() or end()) causes the list to transparently change to state #2.
The list may be empty, but contain a sentinel for the end iterator. This sentinel is created by the Traits::createSentinel method and is a link in the list. When the list is empty, the pointer in the iplist points to the sentinel. Once the sentinel is constructed, it is not destroyed until the list is.
The list may contain actual objects in it, which are stored as a doubly linked list of nodes. One invariant of the list is that the predecessor of the first node in the list always points to the last node in the list, and the successor pointer for the sentinel (which always stays at the end of the list) is always null.
Definition at line 49 of file ilist.h.
Member Typedef Documentation
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> typedef ilist_iterator<const NodeTy> llvm::iplist< NodeTy, Traits >::const_iterator
Definition at line 345 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> typedef const NodeTy* llvm::iplist< NodeTy, Traits >::const_pointer
Definition at line 340 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> typedef const NodeTy& llvm::iplist< NodeTy, Traits >::const_reference
Definition at line 342 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> typedef std::reverse_iterator<const_iterator> llvm::iplist< NodeTy, Traits >::const_reverse_iterator
Definition at line 348 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> typedef ptrdiff_t llvm::iplist< NodeTy, Traits >::difference_type
Definition at line 347 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> typedef ilist_iterator<NodeTy> llvm::iplist< NodeTy, Traits >::iterator
Definition at line 344 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> typedef NodeTy* llvm::iplist< NodeTy, Traits >::pointer
Definition at line 339 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> typedef NodeTy& llvm::iplist< NodeTy, Traits >::reference
Definition at line 341 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> typedef std::reverse_iterator<iterator> llvm::iplist< NodeTy, Traits >::reverse_iterator
Definition at line 349 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> typedef size_t llvm::iplist< NodeTy, Traits >::size_type
Definition at line 346 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> typedef NodeTy llvm::iplist< NodeTy, Traits >::value_type
Definition at line 343 of file ilist.h.
Constructor & Destructor Documentation
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> llvm::iplist< NodeTy, Traits >::iplist () inline
Definition at line 351 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> llvm::iplist< NodeTy, Traits >::~iplist () inline
Definition at line 352 of file ilist.h.
Member Function Documentation
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> reference llvm::iplist< NodeTy, Traits >::back () inline
Definition at line 398 of file ilist.h.
Referenced by llvm::BasicBlock::back(), llvm::MachineBasicBlock::back(), llvm::MachineFunction::back(), llvm::Function::back(), llvm::SlotIndexes::getLastIndex(), llvm::MCAsmLayout::getSectionAddressSize(), llvm::BasicBlock::getTerminator(), INITIALIZE_PASS(), insertFastDiv(), llvm::SlotIndexes::insertMBBInMaps(), is_ns_word_char(), llvm::SlotIndexes::runOnMachineFunction(), and wasEscaped().
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> const_reference llvm::iplist< NodeTy, Traits >::back () const inline
Definition at line 402 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> iterator llvm::iplist< NodeTy, Traits >::begin () inline
Definition at line 359 of file ilist.h.
Referenced by llvm::Module::alias_begin(), llvm::Recycler< llvm::MachineInstr >::Allocate(), llvm::Function::arg_begin(), llvm::BasicBlock::begin(), llvm::MachineFunction::begin(), llvm::Function::begin(), llvm::Module::begin(), llvm::MCSectionData::begin(), llvm::Recycler< llvm::MachineInstr >::clear(), ConvertAtomicSynchScope(), llvm::SparseBitVector< ElementSize >::count(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::SlotIndexes::dump(), llvm::SparseBitVector< ElementSize >::find_first(), llvm::Module::global_begin(), llvm::ilist< SparseBitVectorElement< ElementSize > >::ilist(), llvm::MachineBasicBlock::instr_begin(), llvm::SparseBitVector< ElementSize >::intersects(), llvm::SparseBitVector< ElementSize >::intersectWithComplement(), is_ns_word_char(), LdStHasDebugValue(), llvm::iplist< Argument >::merge(), llvm::Module::named_metadata_begin(), llvm::SparseBitVector< ElementSize >::operator&=(), llvm::SparseBitVector< ElementSize >::operator=(), llvm::SparseBitVector< ElementSize >::operator==(), llvm::SparseBitVector< ElementSize >::operator|=(), llvm::SlotIndexes::renumberIndexes(), llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::setSymTabObject(), llvm::SparseBitVector< ElementSize >::SparseBitVector(), and llvm::iplist< Argument >::splice().
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> const_iterator llvm::iplist< NodeTy, Traits >::begin () const inline
Definition at line 363 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> void llvm::iplist< NodeTy, Traits >::clear () inline
Definition at line 550 of file ilist.h.
Referenced by llvm::SparseBitVector< ElementSize >::clear(), llvm::MachineBasicBlock::clear(), llvm::SparseBitVector< ElementSize >::intersectWithComplement(), llvm::SparseBitVector< ElementSize >::operator=(), llvm::yaml::Scanner::peekNext(), llvm::SlotIndexes::releaseMemory(), llvm::BasicBlock::~BasicBlock(), and llvm::Module::~Module().
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> void llvm::iplist< NodeTy, Traits >::clearAndLeakNodesUnsafely () inline
Remove all nodes from the list like clear(), but do not call removeNodeFromList() or deleteNode().
This should only be used immediately before freeing nodes in bulk to avoid traversing the list and bringing all the nodes into cache.
Definition at line 475 of file ilist.h.
Referenced by llvm::Recycler< llvm::MachineInstr >::clear().
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> bool LLVM_ATTRIBUTE_UNUSED_RESULT llvm::iplist< NodeTy, Traits >::empty () const inline
Definition at line 385 of file ilist.h.
Referenced by llvm::Module::alias_empty(), llvm::Recycler< llvm::MachineInstr >::Allocate(), llvm::Recycler< llvm::MachineInstr >::clear(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::BasicBlock::empty(), llvm::MachineBasicBlock::empty(), llvm::MachineFunction::empty(), llvm::Function::empty(), llvm::Module::empty(), llvm::MCSectionData::empty(), llvm::SparseBitVector< ElementSize >::empty(), llvm::SparseBitVector< ElementSize >::find_first(), llvm::yaml::Scanner::getNext(), llvm::BasicBlock::getTerminator(), llvm::Module::global_empty(), llvm::SparseBitVector< ElementSize >::intersects(), llvm::SparseBitVector< ElementSize >::intersectWithComplement(), llvm::Module::named_metadata_empty(), llvm::SparseBitVector< ElementSize >::operator&=(), llvm::SparseBitVector< ElementSize >::operator|=(), llvm::yaml::Scanner::peekNext(), llvm::BasicBlock::removePredecessor(), llvm::SparseBitVector< ElementSize >::reset(), llvm::SlotIndexes::runOnMachineFunction(), llvm::SparseBitVector< ElementSize >::set(), llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::setSymTabObject(), llvm::iplist< Argument >::splice(), llvm::SparseBitVector< ElementSize >::test(), and llvm::Recycler< llvm::MachineInstr >::~Recycler().
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> iterator llvm::iplist< NodeTy, Traits >::end () inline
Definition at line 367 of file ilist.h.
Referenced by llvm::Module::alias_end(), llvm::Function::arg_end(), ConvertAtomicSynchScope(), llvm::SparseBitVector< ElementSize >::count(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::SlotIndexes::dump(), llvm::BasicBlock::end(), llvm::MachineFunction::end(), llvm::Function::end(), llvm::Module::end(), llvm::MCSectionData::end(), llvm::SlotIndexes::getNextNonNullIndex(), llvm::Module::global_end(), llvm::ilist< SparseBitVectorElement< ElementSize > >::ilist(), llvm::MachineBasicBlock::instr_end(), llvm::SparseBitVector< ElementSize >::intersects(), llvm::SparseBitVector< ElementSize >::intersectWithComplement(), is_ns_word_char(), llvm::iplist< Argument >::merge(), llvm::Module::named_metadata_end(), llvm::SparseBitVector< ElementSize >::operator&=(), llvm::SparseBitVector< ElementSize >::operator=(), llvm::SparseBitVector< ElementSize >::operator==(), llvm::SparseBitVector< ElementSize >::operator|=(), llvm::SlotIndexes::renumberIndexes(), llvm::SparseBitVector< ElementSize >::reset(), llvm::SparseBitVector< ElementSize >::set(), llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::setSymTabObject(), llvm::SparseBitVector< ElementSize >::SparseBitVector(), llvm::iplist< Argument >::splice(), llvm::BasicBlock::splitBasicBlock(), and llvm::SparseBitVector< ElementSize >::test().
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> const_iterator llvm::iplist< NodeTy, Traits >::end () const inline
Definition at line 371 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> iterator llvm::iplist< NodeTy, Traits >::erase (iterator where) inline
Definition at line 465 of file ilist.h.
Referenced by AddressIsTaken(), changeToUnreachable(), CloneLoopBlocks(), DeleteInstructionInBlock(), llvm::MachineFunction::erase(), llvm::MachineBasicBlock::erase(), llvm::GlobalAlias::eraseFromParent(), llvm::Instruction::eraseFromParent(), llvm::BasicBlock::eraseFromParent(), llvm::GlobalVariable::eraseFromParent(), llvm::SlotIndexes::eraseIndex(), llvm::Module::eraseNamedMetadata(), FirstNonDbg(), hasUsesToReplace(), INITIALIZE_PASS(), llvm::InlineFunction(), llvm::SparseBitVector< ElementSize >::intersectWithComplement(), llvm::SparseBitVector< ElementSize >::operator&=(), operator<<(), PlaceSplitBlockCarefully(), promoteSingleBlockAlloca(), llvm::removeUnreachableBlocks(), llvm::ReplaceInstWithValue(), llvm::SparseBitVector< ElementSize >::reset(), SRAGlobal(), llvm::UnrollLoop(), and llvm::MachineFunction::~MachineFunction().
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> iterator llvm::iplist< NodeTy, Traits >::erase (iterator first, iterator last) inline
Definition at line 544 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> void llvm::iplist< NodeTy, Traits >::erase (const NodeTy & val) inline
Definition at line 592 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> template<class Pr1 > void llvm::iplist< NodeTy, Traits >::erase_if (Pr1 pred) inline
Definition at line 599 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> reference llvm::iplist< NodeTy, Traits >::front () inline
Definition at line 390 of file ilist.h.
Referenced by llvm::BasicBlock::front(), llvm::MachineBasicBlock::front(), llvm::MachineFunction::front(), llvm::Function::front(), llvm::SlotIndexes::getZeroIndex(), INITIALIZE_PASS(), and llvm::yaml::Scanner::peekNext().
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> const_reference llvm::iplist< NodeTy, Traits >::front () const inline
Definition at line 394 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> iterator llvm::iplist< NodeTy, Traits >::insert (iterator where, NodeTy * New) inline
Definition at line 412 of file ilist.h.
Referenced by AddPHINodeEntriesForMappedBlock(), createCallHelper(), llvm::createDeadArgHackingPass(), llvm::createLICMPass(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::InstCombiner::DoOneIteration(), llvm::FoldBranchToCommonDest(), FoldCondBranchOnPHI(), llvm::FoldReturnIntoUncondBranch(), llvm::BasicBlock::getContext(), llvm::IRBuilderBase::getCurrentFunctionReturnType(), llvm::MCSectionData::getSubsectionInsertionPoint(), llvm::GlobalVariable::GlobalVariable(), HoistThenElseCodeToIf(), llvm::MCObjectStreamer::insert(), llvm::Instruction::insertBefore(), llvm::IRBuilderDefaultInserter< true >::InsertHelper(), llvm::InstCombiner::InsertNewInstBefore(), InstallGlobalCtors(), llvm::Instruction::Instruction(), isAlwaysFoldable(), MarkIndicesSafe(), NumRetVals(), operator<<(), OptimizeGlobalAddressOfMalloc(), llvm::ReplaceInstWithInst(), llvm::SplitCriticalEdge(), llvm::SplitLandingPadPredecessors(), SRAGlobal(), and TryToShrinkGlobalToBoolean().
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> template<class InIt > void llvm::iplist< NodeTy, Traits >::insert (iterator where, InIt first, InIt last) inline
Definition at line 565 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> iterator llvm::iplist< NodeTy, Traits >::insertAfter (iterator where, NodeTy * New) inline
Definition at line 428 of file ilist.h.
Referenced by llvm::Instruction::insertAfter(), llvm::MachineBasicBlock::insertAfter(), and llvm::SlotIndexes::insertMBBInMaps().
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> size_type llvm::iplist< NodeTy, Traits >::max_size () const inline
Definition at line 384 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> template<class Pr3 > void llvm::iplist< NodeTy, Traits >::merge (iplist< NodeTy, Traits > & right, Pr3 pred) inline
Definition at line 619 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> void llvm::iplist< NodeTy, Traits >::merge (iplist< NodeTy, Traits > & right) inline
Definition at line 632 of file ilist.h.
Referenced by llvm::iplist< Argument >::merge().
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> void llvm::iplist< NodeTy, Traits >::pop_back () inline
Definition at line 559 of file ilist.h.
Referenced by llvm::DeleteDeadBlock(), FoldBlockIntoPredecessor(), HandleCallsInBlockInlinedThroughInvoke(), llvm::InlineFunction(), llvm::MergeBlockIntoPredecessor(), llvm::MachineBasicBlock::pop_back(), and llvm::UnifyFunctionExitNodes::runOnFunction().
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> void llvm::iplist< NodeTy, Traits >::pop_front () inline
Definition at line 555 of file ilist.h.
Referenced by llvm::yaml::Scanner::getNext(), HandleCallsInBlockInlinedThroughInvoke(), INITIALIZE_PASS(), llvm::MachineBasicBlock::pop_front(), and llvm::BasicBlock::removePredecessor().
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> void llvm::iplist< NodeTy, Traits >::push_back (NodeTy * val) inline
Definition at line 554 of file ilist.h.
Referenced by AddPHINodeEntriesForMappedBlock(), llvm::Argument::Argument(), checkInterfaceFunction(), llvm::CloneAndPruneFunctionInto(), llvm::CloneBasicBlock(), llvm::CloneFunction(), llvm::BinaryOperator::Create(), createMalloc(), llvm::Function::eraseFromParent(), llvm::CodeExtractor::extractCodeRegion(), llvm::CodeExtractor::findInputsOutputs(), FindPhiPredForUseInBlock(), llvm::FoldReturnIntoUncondBranch(), FunctionNumber(), llvm::BasicBlock::getContext(), llvm::Module::getOrInsertFunction(), llvm::GlobalAlias::GlobalAlias(), llvm::GlobalVariable::GlobalVariable(), INITIALIZE_PASS(), llvm::Instruction::Instruction(), llvm::MCFragment::MCFragment(), llvm::MCSectionData::MCSectionData(), llvm::MCSymbolData::MCSymbolData(), operator<<(), llvm::BitcodeReader::ParseTriple(), llvm::LLParser::Run(), llvm::UnifyFunctionExitNodes::runOnFunction(), and llvm::UnrollLoop().
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> void llvm::iplist< NodeTy, Traits >::push_front (NodeTy * val) inline
Definition at line 553 of file ilist.h.
Referenced by llvm::Recycler< llvm::MachineInstr >::Deallocate().
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> reverse_iterator llvm::iplist< NodeTy, Traits >::rbegin () inline
Definition at line 377 of file ilist.h.
Referenced by llvm::MachineBasicBlock::instr_rbegin(), OptimizeCmpExpression(), llvm::BasicBlock::rbegin(), llvm::MachineFunction::rbegin(), llvm::MCSectionData::rbegin(), and SinkThenElseCodeToEnd().
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> const_reverse_iterator llvm::iplist< NodeTy, Traits >::rbegin () const inline
Definition at line 378 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> NodeTy* llvm::iplist< NodeTy, Traits >::remove (iterator & IT) inline
Definition at line 435 of file ilist.h.
Referenced by llvm::Recycler< llvm::MachineInstr >::Allocate(), llvm::Recycler< llvm::MachineInstr >::clear(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::SlotIndexes::eraseIndex(), FindPhiPredForUseInBlock(), llvm::MachineFunction::remove(), llvm::MachineBasicBlock::remove(), llvm::GlobalAlias::removeFromParent(), llvm::Instruction::removeFromParent(), llvm::BasicBlock::removeFromParent(), llvm::GlobalVariable::removeFromParent(), and llvm::CallGraph::removeFunctionFromModule().
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> NodeTy* llvm::iplist< NodeTy, Traits >::remove (const iterator & IT) inline
Definition at line 459 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> reverse_iterator llvm::iplist< NodeTy, Traits >::rend () inline
Definition at line 379 of file ilist.h.
Referenced by llvm::MachineBasicBlock::instr_rend(), OptimizeCmpExpression(), llvm::BasicBlock::rend(), llvm::MachineFunction::rend(), llvm::MCSectionData::rend(), and SinkThenElseCodeToEnd().
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> const_reverse_iterator llvm::iplist< NodeTy, Traits >::rend () const inline
Definition at line 380 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> size_type LLVM_ATTRIBUTE_UNUSED_RESULT llvm::iplist< NodeTy, Traits >::size () const inline
Definition at line 539 of file ilist.h.
Referenced by llvm::Module::alias_size(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::NVPTXAsmPrinter::doInitialization(), INITIALIZE_PASS(), llvm::Module::named_metadata_size(), llvm::Recycler< llvm::MachineInstr >::PrintStats(), llvm::BasicBlock::size(), llvm::MachineBasicBlock::size(), llvm::MachineFunction::size(), llvm::Function::size(), llvm::Module::size(), and llvm::MCSectionData::size().
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> template<class Pr3 > void llvm::iplist< NodeTy, Traits >::sort (Pr3 pred)
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> void llvm::iplist< NodeTy, Traits >::sort () inline
Definition at line 635 of file ilist.h.
Referenced by llvm::iplist< Argument >::sort().
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> void llvm::iplist< NodeTy, Traits >::splice (iterator where, iplist< NodeTy, Traits > & L2) inline
Definition at line 570 of file ilist.h.
Referenced by CloneLoop(), llvm::createDeadArgHackingPass(), FoldBlockIntoPredecessor(), FoldTwoEntryPHINode(), FunctionNumber(), getArrayElements(), HoistThenElseCodeToIf(), INITIALIZE_PASS(), llvm::InlineFunction(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), llvm::BasicBlock::moveAfter(), llvm::Instruction::moveBefore(), llvm::BasicBlock::moveBefore(), NumRetVals(), PlaceSplitBlockCarefully(), ReplaceUsesOfWith(), llvm::LLParser::Run(), shouldSpeculateInstrs(), SinkThenElseCodeToEnd(), SpeculativelyExecuteBB(), llvm::MachineFunction::splice(), llvm::MachineBasicBlock::splice(), llvm::BasicBlock::splitBasicBlock(), and llvm::UnrollRuntimeLoopProlog().
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> void llvm::iplist< NodeTy, Traits >::splice (iterator where, iplist< NodeTy, Traits > & L2, iterator first) inline
Definition at line 574 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> void llvm::iplist< NodeTy, Traits >::splice (iterator where, iplist< NodeTy, Traits > & L2, iterator first, iterator last) inline
Definition at line 579 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> void llvm::iplist< NodeTy, Traits >::swap (iplist< NodeTy, Traits > & RHS) inline
Definition at line 407 of file ilist.h.
Referenced by std::swap().
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> template<class Pr2 > void llvm::iplist< NodeTy, Traits >::unique (Pr2 pred) inline
Definition at line 607 of file ilist.h.
template<typename NodeTy, typename Traits = ilist_traits<NodeTy>> void llvm::iplist< NodeTy, Traits >::unique () inline
Definition at line 617 of file ilist.h.
Referenced by llvm::iplist< Argument >::unique().
The documentation for this class was generated from the following file:
ilist.h