LLVM: llvm::MemDepResult Class Reference
LLVM API Documentation
llvm::MemDepResult Class Reference
#include <MemoryDependenceAnalysis.h>
Public Member Functions
MemDepResult ()
bool isClobber () const
bool isDef () const
bool isNonLocal () const
bool isNonFuncLocal () const
bool isUnknown () const
Instruction * getInst () const
bool operator== (const MemDepResult &M) const
bool operator!= (const MemDepResult &M) const
bool operator< (const MemDepResult &M) const
bool operator> (const MemDepResult &M) const
Static Public Member Functions
static MemDepResult getDef (Instruction *Inst)
static MemDepResult getClobber (Instruction *Inst)
static MemDepResult getNonLocal ()
static MemDepResult getNonFuncLocal ()
static MemDepResult getUnknown ()
Friends
class MemoryDependenceAnalysis
Detailed Description
MemDepResult - A memory dependence query can return one of three different answers, described below.
Definition at line 40 of file MemoryDependenceAnalysis.h.
Constructor & Destructor Documentation
llvm::MemDepResult::MemDepResult () inline
Definition at line 101 of file MemoryDependenceAnalysis.h.
Referenced by getClobber(), getDef(), getNonFuncLocal(), getNonLocal(), and getUnknown().
Member Function Documentation
static MemDepResult llvm::MemDepResult::getClobber (Instruction * Inst) inline static
Definition at line 109 of file MemoryDependenceAnalysis.h.
References MemDepResult().
Referenced by GetLocation(), and llvm::MemoryDependenceAnalysis::getPointerDependencyFrom().
static MemDepResult llvm::MemDepResult::getDef (Instruction * Inst) inline static
get methods: These are static ctor methods for creating various MemDepResult kinds.
Definition at line 105 of file MemoryDependenceAnalysis.h.
References MemDepResult().
Referenced by GetLocation(), and llvm::MemoryDependenceAnalysis::getPointerDependencyFrom().
Instruction* llvm::MemDepResult::getInst () const inline
getInst() - If this is a normal dependency, return the instruction that is depended on. Otherwise, return null.
Definition at line 158 of file MemoryDependenceAnalysis.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getInt(), and llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer().
Referenced by FindUnconditionalPreds(), llvm::MemoryDependenceAnalysis::getDependency(), llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), llvm::MemoryDependenceAnalysis::getNonLocalPointerDependency(), llvm::DenseMapInfo< Expression >::isEqual(), isLifetimeStart(), isPossibleSelfRead(), patchAndReplaceAllUsesWith(), and llvm::MemoryDependenceAnalysis::removeInstruction().
static MemDepResult llvm::MemDepResult::getNonFuncLocal () inline static
Definition at line 117 of file MemoryDependenceAnalysis.h.
References MemDepResult().
Referenced by llvm::MemoryDependenceAnalysis::getDependency(), GetLocation(), llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), and llvm::MemoryDependenceAnalysis::getPointerDependencyFrom().
static MemDepResult llvm::MemDepResult::getNonLocal () inline static
Definition at line 113 of file MemoryDependenceAnalysis.h.
References MemDepResult().
Referenced by llvm::MemoryDependenceAnalysis::getDependency(), GetLocation(), llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), and llvm::MemoryDependenceAnalysis::getPointerDependencyFrom().
static MemDepResult llvm::MemDepResult::getUnknown () inline static
Definition at line 121 of file MemoryDependenceAnalysis.h.
References MemDepResult().
Referenced by llvm::MemoryDependenceAnalysis::getDependency(), GetLocation(), llvm::MemoryDependenceAnalysis::getNonLocalPointerDependency(), llvm::MemoryDependenceAnalysis::getPointerDependencyFrom(), and SortNonLocalDepInfoCache().
bool llvm::MemDepResult::isClobber () const inline
isClobber - Return true if this MemDepResult represents a query that is an instruction clobber dependency.
Definition at line 128 of file MemoryDependenceAnalysis.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getInt().
Referenced by FindUnconditionalPreds(), llvm::MemoryDependenceAnalysis::getNonLocalPointerDependency(), isLifetimeStart(), isPossibleSelfRead(), and patchAndReplaceAllUsesWith().
bool llvm::MemDepResult::isDef () const inline
isDef - Return true if this MemDepResult represents a query that is an instruction definition dependency.
Definition at line 132 of file MemoryDependenceAnalysis.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getInt().
Referenced by FindUnconditionalPreds(), llvm::MemoryDependenceAnalysis::getNonLocalPointerDependency(), llvm::DenseMapInfo< Expression >::isEqual(), isLifetimeStart(), isPossibleSelfRead(), and patchAndReplaceAllUsesWith().
bool llvm::MemDepResult::isNonFuncLocal () const inline
isNonFuncLocal - Return true if this MemDepResult represents a query that is transparent to the start of the function.
Definition at line 144 of file MemoryDependenceAnalysis.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getInt(), and llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer().
bool llvm::MemDepResult::isNonLocal () const inline
isNonLocal - Return true if this MemDepResult represents a query that is transparent to the start of the block, but where a non-local hasn't been done.
Definition at line 137 of file MemoryDependenceAnalysis.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getInt(), and llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer().
Referenced by llvm::createMemDepPrinter(), FindUnconditionalPreds(), llvm::DenseMapInfo< Expression >::isEqual(), patchAndReplaceAllUsesWith(), and SortNonLocalDepInfoCache().
bool llvm::MemDepResult::isUnknown () const inline
isUnknown - Return true if this MemDepResult represents a query which cannot and/or will not be computed.
Definition at line 151 of file MemoryDependenceAnalysis.h.
References llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getInt(), and llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer().
bool llvm::MemDepResult::operator!= (const MemDepResult & M) const inline
Definition at line 164 of file MemoryDependenceAnalysis.h.
bool llvm::MemDepResult::operator< (const MemDepResult & M) const inline
Definition at line 165 of file MemoryDependenceAnalysis.h.
bool llvm::MemDepResult::operator== (const MemDepResult & M) const inline
Definition at line 163 of file MemoryDependenceAnalysis.h.
bool llvm::MemDepResult::operator> (const MemDepResult & M) const inline
Definition at line 166 of file MemoryDependenceAnalysis.h.
Friends And Related Function Documentation
friend class MemoryDependenceAnalysis friend
Definition at line 168 of file MemoryDependenceAnalysis.h.
The documentation for this class was generated from the following file:
MemoryDependenceAnalysis.h