LLVM: llvm::LSBaseSDNode Class Reference
LLVM API Documentation
llvm::LSBaseSDNode Class Reference
#include <SelectionDAGNodes.h>
Public Member Functions
LSBaseSDNode (ISD::NodeType NodeTy, unsigned Order, DebugLoc dl, SDValue *Operands, unsigned numOperands, SDVTList VTs, ISD::MemIndexedMode AM, EVT MemVT, MachineMemOperand *MMO)
const SDValue & getOffset () const
ISD::MemIndexedMode getAddressingMode () const
bool isIndexed () const
isIndexed - Return true if this is a pre/post inc/dec load/store.
bool isUnindexed () const
isUnindexed - Return true if this is NOT a pre/post inc/dec load/store.
Public Member Functions inherited from llvm::MemSDNode
MemSDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTs, EVT MemoryVT, MachineMemOperand *MMO)
MemSDNode (unsigned Opc, unsigned Order, DebugLoc dl, SDVTList VTs, const SDValue *Ops, unsigned NumOps, EVT MemoryVT, MachineMemOperand *MMO)
bool readMem () const
bool writeMem () const
unsigned getOriginalAlignment () const
Returns alignment and volatility of the memory access.
unsigned getAlignment () const
unsigned getRawSubclassData () const
bool isVolatile () const
bool isNonTemporal () const
bool isInvariant () const
AtomicOrdering getOrdering () const
SynchronizationScope getSynchScope () const
const Value * getSrcValue () const
Returns the SrcValue and offset that describes the location of the access.
int64_t getSrcValueOffset () const
const MDNode * getTBAAInfo () const
Returns the TBAAInfo that describes the dereference.
const MDNode * getRanges () const
Returns the Ranges that describes the dereference.
EVT getMemoryVT () const
getMemoryVT - Return the type of the in-memory value.
MachineMemOperand * getMemOperand () const
const MachinePointerInfo & getPointerInfo () const
unsigned getAddressSpace () const
getAddressSpace - Return the address space for the associated pointer
void refineAlignment (const MachineMemOperand *NewMMO)
const SDValue & getChain () const
const SDValue & getBasePtr () const
Public Member Functions inherited from llvm::SDNode
unsigned getOpcode () const
bool isTargetOpcode () const
bool isTargetMemoryOpcode () const
bool isMachineOpcode () const
unsigned getMachineOpcode () const
bool getHasDebugValue () const
getHasDebugValue - get this bit.
void setHasDebugValue (bool b)
setHasDebugValue - set this bit.
bool use_empty () const
bool hasOneUse () const
size_t use_size () const
int getNodeId () const
void setNodeId (int Id)
setNodeId - Set unique node id.
unsigned getIROrder () const
void setIROrder (unsigned Order)
const DebugLoc getDebugLoc () const
getDebugLoc - Return the source location info.
void setDebugLoc (const DebugLoc dl)
use_iterator use_begin () const
bool hasNUsesOfValue (unsigned NUses, unsigned Value) const
bool hasAnyUseOfValue (unsigned Value) const
bool isOnlyUserOf (SDNode *N) const
bool isOperandOf (SDNode *N) const
bool isPredecessorOf (const SDNode *N) const
bool hasPredecessor (const SDNode *N) const
bool hasPredecessorHelper (const SDNode *N, SmallPtrSet< const SDNode *, 32 > &Visited, SmallVectorImpl< const SDNode * > &Worklist) const
unsigned getNumOperands () const
uint64_t getConstantOperandVal (unsigned Num) const
const SDValue & getOperand (unsigned Num) const
op_iterator op_begin () const
op_iterator op_end () const
SDVTList getVTList () const
SDNode * getGluedNode () const
const SDNode * getGluedMachineNode () const
SDNode * getGluedUser () const
unsigned getNumValues () const
EVT getValueType (unsigned ResNo) const
MVT getSimpleValueType (unsigned ResNo) const
unsigned getValueSizeInBits (unsigned ResNo) const
value_iterator value_begin () const
value_iterator value_end () const
std::string getOperationName (const SelectionDAG *G=0) const
void print_types (raw_ostream &OS, const SelectionDAG *G) const
void print_details (raw_ostream &OS, const SelectionDAG *G) const
void print (raw_ostream &OS, const SelectionDAG *G=0) const
void printr (raw_ostream &OS, const SelectionDAG *G=0) const
void printrFull (raw_ostream &O, const SelectionDAG *G=0) const
void printrWithDepth (raw_ostream &O, const SelectionDAG *G=0, unsigned depth=100) const
void dump () const
dump - Dump this node, for debugging.
void dumpr () const
dumpr - Dump (recursively) this node and its use-def subgraph.
void dump (const SelectionDAG *G) const
void dumpr (const SelectionDAG *G) const
void dumprFull (const SelectionDAG *G=0) const
void dumprWithDepth (const SelectionDAG *G=0, unsigned depth=100) const
void Profile (FoldingSetNodeID &ID) const
void addUse (SDUse &U)
Public Member Functions inherited from llvm::FoldingSetImpl::Node
Node ()
void * getNextInBucket () const
void SetNextInBucket (void *N)
Public Member Functions inherited from llvm::ilist_node< SDNode >
SDNode * getPrevNode ()
Get the previous node, or 0 for the list head.
const SDNode * getPrevNode () const
Get the previous node, or 0 for the list head.
SDNode * getNextNode ()
Get the next node, or 0 for the list tail.
const SDNode * getNextNode () const
Get the next node, or 0 for the list tail.
Static Public Member Functions
static bool classof (const SDNode *N)
Static Public Member Functions inherited from llvm::MemSDNode
static bool classof (const SDNode *N)
Static Public Member Functions inherited from llvm::SDNode
static use_iterator use_end ()
static const char * getIndexedModeName (ISD::MemIndexedMode AM)
Additional Inherited Members
Public Types inherited from llvm::SDNode
typedef SDUse * op_iterator
typedef const EVT * value_iterator
Protected Member Functions inherited from llvm::SDNode
SDNode (unsigned Opc, unsigned Order, const DebugLoc dl, SDVTList VTs, const SDValue *Ops, unsigned NumOps)
SDNode (unsigned Opc, unsigned Order, const DebugLoc dl, SDVTList VTs)
void InitOperands (SDUse *Ops, const SDValue &Op0)
InitOperands - Initialize the operands list of this with 1 operand.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1)
InitOperands - Initialize the operands list of this with 2 operands.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1, const SDValue &Op2)
InitOperands - Initialize the operands list of this with 3 operands.
void InitOperands (SDUse *Ops, const SDValue &Op0, const SDValue &Op1, const SDValue &Op2, const SDValue &Op3)
InitOperands - Initialize the operands list of this with 4 operands.
void InitOperands (SDUse *Ops, const SDValue *Vals, unsigned N)
InitOperands - Initialize the operands list of this with N operands.
void DropOperands ()
Protected Member Functions inherited from llvm::ilist_node< SDNode >
ilist_node ()
Static Protected Member Functions inherited from llvm::SDNode
static SDVTList getSDVTList (EVT VT)
Protected Attributes inherited from llvm::MemSDNode
MachineMemOperand * MMO
MMO - Memory reference information.
Protected Attributes inherited from llvm::SDNode
uint16_t SubclassData: 14
Detailed Description
LSBaseSDNode - Base class for LoadSDNode and StoreSDNode
Definition at line 1675 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
llvm::LSBaseSDNode::LSBaseSDNode (ISD::NodeType NodeTy, unsigned Order, DebugLoc dl, SDValue * Operands, unsigned numOperands, SDVTList VTs, ISD::MemIndexedMode AM, EVT MemVT, MachineMemOperand * MMO) inline
Definition at line 1684 of file SelectionDAGNodes.h.
References llvm::ISD::UNDEF.
Member Function Documentation
static bool llvm::LSBaseSDNode::classof (const SDNode * N) inline static
Definition at line 1712 of file SelectionDAGNodes.h.
References llvm::SDNode::getOpcode(), llvm::ISD::LOAD, and llvm::ISD::STORE.
ISD::MemIndexedMode llvm::LSBaseSDNode::getAddressingMode () const inline
getAddressingMode - Return the addressing mode for this load or store: unindexed, pre-inc, pre-dec, post-inc, or post-dec.
Definition at line 1702 of file SelectionDAGNodes.h.
Referenced by ExpandUnalignedLoad(), ExpandUnalignedStore(), getAL(), GetFPLibCall(), getVCmpEQInst(), isCalleeLoad(), isConstantSplatVector(), llvm::ISD::isNormalLoad(), llvm::ISD::isNormalStore(), isScaledConstantInRange(), isValidIndexedLoad(), and OffsetFitsS11().
const SDValue& llvm::LSBaseSDNode::getOffset () const inline
Definition at line 1696 of file SelectionDAGNodes.h.
References llvm::ISD::LOAD.
bool llvm::LSBaseSDNode::isIndexed () const inline
isIndexed - Return true if this is a pre/post inc/dec load/store.
Definition at line 1707 of file SelectionDAGNodes.h.
References llvm::ISD::UNINDEXED.
Referenced by llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), getCodeAddrSpace(), ConsecutiveMemoryChainSorter::operator()(), and llvm::R600TargetLowering::ReplaceNodeResults().
bool llvm::LSBaseSDNode::isUnindexed () const inline
isUnindexed - Return true if this is NOT a pre/post inc/dec load/store.
Definition at line 1710 of file SelectionDAGNodes.h.
References llvm::ISD::UNINDEXED.
Referenced by canFoldInAddressingMode(), isConstantSplatVector(), ConsecutiveMemoryChainSorter::operator()(), and llvm::TargetLowering::SimplifySetCC().
The documentation for this class was generated from the following file:
SelectionDAGNodes.h