LLVM: llvm::DominatorBase< NodeT > Class Template Reference
LLVM API Documentation
llvm::DominatorBase< NodeT > Class Template Reference
#include <Dominators.h>
Public Member Functions
const std::vector< NodeT * > & getRoots () const
bool isPostDominator () const
Protected Member Functions
DominatorBase (bool isPostDom)
Protected Attributes
std::vector< NodeT * > Roots
const bool IsPostDominators
Detailed Description
template<class NodeT>
class llvm::DominatorBase< NodeT >
DominatorBase - Base class that other, more interesting dominator analyses inherit from.
Definition at line 37 of file Dominators.h.
Constructor & Destructor Documentation
template<class NodeT> llvm::DominatorBase< NodeT >::DominatorBase (bool isPostDom) inline explicit protected
Definition at line 41 of file Dominators.h.
Member Function Documentation
template<class NodeT> const std::vector<NodeT*>& llvm::DominatorBase< NodeT >::getRoots () const inline
getRoots - Return the root blocks of the current CFG. This may include multiple blocks if we are computing post dominators. For forward dominators, this will always be a single block (the entry node).
Definition at line 49 of file Dominators.h.
Referenced by llvm::MachinePostDominatorTree::getRoots(), llvm::PostDominatorTree::getRoots(), llvm::MachineDominatorTree::getRoots(), and llvm::DominatorTree::getRoots().
template<class NodeT> bool llvm::DominatorBase< NodeT >::isPostDominator () const inline
isPostDominator - Returns true if analysis based of postdoms
Definition at line 53 of file Dominators.h.
Referenced by llvm::DominatorTreeBase< llvm::MachineBasicBlock >::findNearestCommonDominator(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::isReachableFromEntry(), and llvm::DominatorTreeBase< llvm::MachineBasicBlock >::print().
Member Data Documentation
template<class NodeT> const bool llvm::DominatorBase< NodeT >::IsPostDominators protected
Definition at line 40 of file Dominators.h.
Referenced by llvm::DominatorBase< llvm::MachineBasicBlock >::isPostDominator(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::recalculate(), and llvm::DominatorTreeBase< llvm::MachineBasicBlock >::splitBlock().
template<class NodeT> std::vector<NodeT*> llvm::DominatorBase< NodeT >::Roots protected
Definition at line 39 of file Dominators.h.
Referenced by llvm::DominatorTreeBase< llvm::MachineBasicBlock >::addRoot(), llvm::DFSPass(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::getRoot(), llvm::DominatorBase< llvm::MachineBasicBlock >::getRoots(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::recalculate(), and llvm::DominatorTreeBase< llvm::MachineBasicBlock >::reset().
The documentation for this class was generated from the following file:
Dominators.h