LLVM: llvm::MCWin64EHInstruction Class Reference
LLVM API Documentation
llvm::MCWin64EHInstruction Class Reference
#include <MCWin64EH.h>
Public Types
typedef Win64EH::UnwindOpcodes OpType
Public Member Functions
MCWin64EHInstruction (OpType Op, MCSymbol *L, unsigned Reg)
MCWin64EHInstruction (MCSymbol *L, unsigned Size)
MCWin64EHInstruction (OpType Op, MCSymbol *L, unsigned Reg, unsigned Off)
MCWin64EHInstruction (OpType Op, MCSymbol *L, bool Code)
OpType getOperation () const
MCSymbol * getLabel () const
unsigned getOffset () const
unsigned getSize () const
unsigned getRegister () const
bool isPushCodeFrame () const
Detailed Description
Definition at line 27 of file MCWin64EH.h.
Member Typedef Documentation
typedef Win64EH::UnwindOpcodes llvm::MCWin64EHInstruction::OpType
Definition at line 29 of file MCWin64EH.h.
Constructor & Destructor Documentation
llvm::MCWin64EHInstruction::MCWin64EHInstruction (OpType Op, MCSymbol * L, unsigned Reg) inline
Definition at line 36 of file MCWin64EH.h.
References llvm::Win64EH::UOP_PushNonVol.
llvm::MCWin64EHInstruction::MCWin64EHInstruction (MCSymbol * L, unsigned Size) inline
Definition at line 40 of file MCWin64EH.h.
llvm::MCWin64EHInstruction::MCWin64EHInstruction (OpType Op, MCSymbol * L, unsigned Reg, unsigned Off) inline
Definition at line 43 of file MCWin64EH.h.
References llvm::Win64EH::UOP_SaveNonVol, llvm::Win64EH::UOP_SaveNonVolBig, llvm::Win64EH::UOP_SaveXMM128, llvm::Win64EH::UOP_SaveXMM128Big, and llvm::Win64EH::UOP_SetFPReg.
llvm::MCWin64EHInstruction::MCWin64EHInstruction (OpType Op, MCSymbol * L, bool Code) inline
Definition at line 51 of file MCWin64EH.h.
References llvm::Win64EH::UOP_PushMachFrame.
Member Function Documentation
MCSymbol* llvm::MCWin64EHInstruction::getLabel () const inline
Definition at line 56 of file MCWin64EH.h.
Referenced by llvm::EmitUnwindCode().
unsigned llvm::MCWin64EHInstruction::getOffset () const inline
Definition at line 57 of file MCWin64EH.h.
Referenced by llvm::EmitUnwindCode(), and llvm::EmitUnwindInfo().
OpType llvm::MCWin64EHInstruction::getOperation () const inline
Definition at line 55 of file MCWin64EH.h.
Referenced by llvm::EmitUnwindCode(), and llvm::EmitUnwindInfo().
unsigned llvm::MCWin64EHInstruction::getRegister () const inline
Definition at line 59 of file MCWin64EH.h.
Referenced by llvm::EmitUnwindCode(), and llvm::EmitUnwindInfo().
unsigned llvm::MCWin64EHInstruction::getSize () const inline
Definition at line 58 of file MCWin64EH.h.
Referenced by llvm::EmitUnwindCode().
bool llvm::MCWin64EHInstruction::isPushCodeFrame () const inline
Definition at line 60 of file MCWin64EH.h.
Referenced by llvm::EmitUnwindCode().
The documentation for this class was generated from the following file:
MCWin64EH.h