LLVM: llvm::NonLocalDepEntry Class Reference
LLVM API Documentation
llvm::NonLocalDepEntry Class Reference
#include <MemoryDependenceAnalysis.h>
Public Member Functions
NonLocalDepEntry (BasicBlock *bb, MemDepResult result)
NonLocalDepEntry (BasicBlock *bb)
BasicBlock * getBB () const
void setResult (const MemDepResult &R)
const MemDepResult & getResult () const
bool operator< (const NonLocalDepEntry &RHS) const
Detailed Description
NonLocalDepEntry - This is an entry in the NonLocalDepInfo cache. For each BasicBlock (the BB entry) it keeps a MemDepResult.
Definition at line 190 of file MemoryDependenceAnalysis.h.
Constructor & Destructor Documentation
llvm::NonLocalDepEntry::NonLocalDepEntry (BasicBlock * bb, MemDepResult result) inline
Definition at line 194 of file MemoryDependenceAnalysis.h.
llvm::NonLocalDepEntry::NonLocalDepEntry (BasicBlock * bb) inline
Definition at line 198 of file MemoryDependenceAnalysis.h.
Member Function Documentation
BasicBlock* llvm::NonLocalDepEntry::getBB () const inline
Definition at line 201 of file MemoryDependenceAnalysis.h.
References BB.
Referenced by llvm::NonLocalDepResult::getBB(), and llvm::DenseMapInfo< Expression >::isEqual().
const MemDepResult& llvm::NonLocalDepEntry::getResult () const inline
Definition at line 205 of file MemoryDependenceAnalysis.h.
Referenced by llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), llvm::MemoryDependenceAnalysis::getNonLocalPointerDependency(), llvm::NonLocalDepResult::getResult(), and llvm::DenseMapInfo< Expression >::isEqual().
bool llvm::NonLocalDepEntry::operator< (const NonLocalDepEntry & RHS) const inline
Definition at line 207 of file MemoryDependenceAnalysis.h.
void llvm::NonLocalDepEntry::setResult (const MemDepResult & R) inline
Definition at line 203 of file MemoryDependenceAnalysis.h.
Referenced by llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), llvm::MemoryDependenceAnalysis::getNonLocalPointerDependency(), and llvm::NonLocalDepResult::setResult().
The documentation for this class was generated from the following file:
MemoryDependenceAnalysis.h