LLVM: llvm::VarInit Class Reference
LLVM API Documentation
llvm::VarInit Class Reference
#include <Record.h>
Public Member Functions
virtual Init * convertInitializerTo (RecTy *Ty) const
const std::string & getName () const
Init * getNameInit () const
std::string getNameInitAsString () const
virtual Init * resolveListElementReference (Record &R, const RecordVal *RV, unsigned Elt) const
virtual RecTy * getFieldType (const std::string &FieldName) const
virtual Init * getFieldInit (Record &R, const RecordVal *RV, const std::string &FieldName) const
virtual Init * resolveReferences (Record &R, const RecordVal *RV) const
virtual Init * getBit (unsigned Bit) const
virtual std::string getAsString () const
getAsString - Convert this value to a string form.
Public Member Functions inherited from llvm::TypedInit
RecTy * getType () const
virtual Init * convertInitializerBitRange (const std::vector< unsigned > &Bits) const
virtual Init * convertInitListSlice (const std::vector< unsigned > &Elements) const
Public Member Functions inherited from llvm::Init
InitKind getKind () const
virtual ~Init ()
virtual bool isComplete () const
void print (raw_ostream &OS) const
print - Print out this value.
virtual std::string getAsUnquotedString () const
void dump () const
virtual Init * getBitVar () const
virtual unsigned getBitNum () const
Static Public Member Functions
static bool classof (const Init *I)
static VarInit * get (const std::string &VN, RecTy *T)
static VarInit * get (Init *VN, RecTy *T)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind {
IK_BitInit, IK_BitsInit, IK_FirstTypedInit, IK_DagInit,
IK_DefInit, IK_FieldInit, IK_IntInit, IK_ListInit,
IK_FirstOpInit, IK_BinOpInit, IK_TernOpInit, IK_UnOpInit,
IK_LastOpInit, IK_StringInit, IK_VarInit, IK_VarListElementInit,
IK_LastTypedInit, IK_UnsetInit, IK_VarBitInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T)
Protected Member Functions inherited from llvm::Init
Init (InitKind K)
Detailed Description
VarInit - 'Opcode' - Represent a reference to an entire variable object.
Definition at line 1042 of file Record.h.
Member Function Documentation
static bool llvm::VarInit::classof (const Init * I) inline static
Definition at line 1054 of file Record.h.
References llvm::Init::getKind(), and T.
virtual Init* llvm::VarInit::convertInitializerTo (RecTy * Ty) const inline virtual
convertInitializerTo - This virtual function is a simple call-back function that should be overridden to call the appropriate RecTy::convertValue method.
Implements llvm::Init.
Definition at line 1060 of file Record.h.
References llvm::RecTy::convertValue(), and llvm::Intrinsic::getName().
VarInit * VarInit::get (const std::string & VN, RecTy * T) static
Definition at line 1304 of file Record.cpp.
References llvm::StringInit::get().
Referenced by llvm::UnOpInit::Fold(), llvm::TernOpInit::Fold(), and GetNewAnonymousName().
VarInit * VarInit::get (Init * VN, RecTy * T) static
Definition at line 1309 of file Record.cpp.
References I.
virtual std::string llvm::VarInit::getAsString () const inline virtual
getAsString - Convert this value to a string form.
Implements llvm::Init.
Definition at line 1086 of file Record.h.
References llvm::Intrinsic::getName().
Init * VarInit::getBit (unsigned Bit) const virtual
getBit - This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 1326 of file Record.cpp.
References llvm::BitRecTy::get(), llvm::VarBitInit::get(), and llvm::Intrinsic::getType().
Init * VarInit::getFieldInit (Record & R, const RecordVal * RV, const std::string & FieldName) const virtual
getFieldInit - This method complements getFieldType to return the initializer for the specified field. If getFieldType returns non-null this method should return non-null, otherwise it returns null.
Reimplemented from llvm::Init.
Definition at line 1366 of file Record.cpp.
References llvm::Init::getFieldInit(), llvm::Intrinsic::getType(), llvm::Record::getValue(), I, and llvm::tgtok::VarName.
RecTy * VarInit::getFieldType (const std::string & FieldName) const virtual
getFieldType - This method is used to implement the FieldInit class. Implementors of this method should return the type of the named field if they are of record type.
Reimplemented from llvm::TypedInit.
Definition at line 1359 of file Record.cpp.
References llvm::Intrinsic::getType(), and llvm::RecordVal::getValue().
const std::string & VarInit::getName () const
Definition at line 1320 of file Record.cpp.
References llvm::dyn_cast(), and llvm::StringInit::getValue().
Referenced by llvm::SubMultiClassReference::dump(), and GetNewAnonymousName().
Init* llvm::VarInit::getNameInit () const inline
Definition at line 1065 of file Record.h.
References llvm::tgtok::VarName.
std::string llvm::VarInit::getNameInitAsString () const inline
Definition at line 1066 of file Record.h.
References llvm::tgtok::Bit.
Init * VarInit::resolveListElementReference (Record & R, const RecordVal * RV, unsigned Elt) const virtual
resolveListElementReference - This method is used to implement VarListElementInit::resolveReferences. If the list element is resolvable now, we return the resolved value, otherwise we return null.
Implements llvm::TypedInit.
Definition at line 1332 of file Record.cpp.
References llvm::dyn_cast(), llvm::VarListElementInit::get(), llvm::ListInit::getElement(), llvm::RecordVal::getNameInit(), llvm::ListInit::getSize(), llvm::RecordVal::getValue(), llvm::Record::getValue(), and llvm::Record::isTemplateArg().
Init * VarInit::resolveReferences (Record & R, const RecordVal * RV) const virtual
resolveReferences - This method is used by classes that refer to other variables which may not be defined at the time they expression is formed. If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
resolveReferences - This method is used by classes that refer to other variables which may not be defined at the time the expression is formed. If a value is set for the variable later, this method will be called on users of the value to allow the value to propagate out.
Reimplemented from llvm::Init.
Definition at line 1387 of file Record.cpp.
References llvm::Record::getValue(), and llvm::tgtok::VarName.
The documentation for this class was generated from the following files:
Record.h
Record.cpp