LLVM: llvm::ListRecTy Class Reference
LLVM API Documentation
llvm::ListRecTy Class Reference
#include <Record.h>
Public Member Functions
RecTy * getElementType () const
virtual Init * convertValue (UnsetInit *UI)
virtual Init * convertValue (BitInit *BI)
virtual Init * convertValue (BitsInit *BI)
virtual Init * convertValue (IntInit *II)
virtual Init * convertValue (StringInit *SI)
virtual Init * convertValue (ListInit *LI)
virtual Init * convertValue (VarBitInit *VB)
virtual Init * convertValue (DefInit *DI)
virtual Init * convertValue (DagInit *DI)
virtual Init * convertValue (UnOpInit *UI)
virtual Init * convertValue (BinOpInit *UI)
virtual Init * convertValue (TernOpInit *UI)
virtual Init * convertValue (TypedInit *TI)
virtual Init * convertValue (VarInit *VI)
virtual Init * convertValue (FieldInit *FI)
virtual std::string getAsString () const
virtual bool typeIsConvertibleTo (const RecTy *RHS) const
virtual bool baseClassOf (const RecTy *) const
Public Member Functions inherited from llvm::RecTy
RecTyKind getRecTyKind () const
RecTy (RecTyKind K)
virtual ~RecTy ()
void print (raw_ostream &OS) const
void dump () const
ListRecTy * getListTy ()
getListTy - Returns the type representing list<this>.
Static Public Member Functions
static bool classof (const RecTy *RT)
static ListRecTy * get (RecTy *T)
Friends
ListRecTy * RecTy::getListTy ()
Additional Inherited Members
Public Types inherited from llvm::RecTy
enum RecTyKind {
BitRecTyKind, BitsRecTyKind, IntRecTyKind, StringRecTyKind,
ListRecTyKind, DagRecTyKind, RecordRecTyKind
}
Subclass discriminator (for dyn_cast<> et al.)
Detailed Description
ListRecTy - 'list<Ty>' - Represent a list of values, all of which must be of the specified type.
Definition at line 293 of file Record.h.
Member Function Documentation
bool ListRecTy::baseClassOf (const RecTy * RHS) const virtual
Reimplemented from llvm::RecTy.
Definition at line 299 of file Record.cpp.
static bool llvm::ListRecTy::classof (const RecTy * RT) inline static
Definition at line 298 of file Record.h.
References llvm::RecTy::getRecTyKind(), and llvm::RecTy::ListRecTyKind.
virtual Init* llvm::ListRecTy::convertValue (UnsetInit * UI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 305 of file Record.h.
virtual Init* llvm::ListRecTy::convertValue (BitInit * BI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 306 of file Record.h.
virtual Init* llvm::ListRecTy::convertValue (BitsInit * BI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 307 of file Record.h.
virtual Init* llvm::ListRecTy::convertValue (IntInit * II) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 308 of file Record.h.
virtual Init* llvm::ListRecTy::convertValue (StringInit * SI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 309 of file Record.h.
References llvm::RecTy::convertValue().
Init * ListRecTy::convertValue (ListInit * LI) virtual
Reimplemented from llvm::RecTy.
Definition at line 274 of file Record.cpp.
References llvm::Init::convertInitializerTo(), llvm::ListInit::get(), llvm::ListInit::getElement(), llvm::ListInit::getSize(), llvm::TypedInit::getType(), and i.
virtual Init* llvm::ListRecTy::convertValue (VarBitInit * VB) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 311 of file Record.h.
virtual Init* llvm::ListRecTy::convertValue (DefInit * DI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 312 of file Record.h.
virtual Init* llvm::ListRecTy::convertValue (DagInit * DI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 313 of file Record.h.
virtual Init* llvm::ListRecTy::convertValue (UnOpInit * UI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 314 of file Record.h.
References llvm::RecTy::convertValue().
virtual Init* llvm::ListRecTy::convertValue (BinOpInit * UI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 315 of file Record.h.
References llvm::RecTy::convertValue().
virtual Init* llvm::ListRecTy::convertValue (TernOpInit * UI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 316 of file Record.h.
References llvm::RecTy::convertValue().
Init * ListRecTy::convertValue (TypedInit * TI) virtual
Reimplemented from llvm::RecTy.
Definition at line 291 of file Record.cpp.
References llvm::TypedInit::getType().
virtual Init* llvm::ListRecTy::convertValue (VarInit * VI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 318 of file Record.h.
References llvm::RecTy::convertValue().
virtual Init* llvm::ListRecTy::convertValue (FieldInit * FI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 319 of file Record.h.
References llvm::RecTy::convertValue(), and llvm::RecTy::getAsString().
static ListRecTy* llvm::ListRecTy::get (RecTy * T) inline static
Definition at line 302 of file Record.h.
References llvm::RecTy::getListTy().
Referenced by GetNewAnonymousName().
std::string ListRecTy::getAsString () const virtual
Implements llvm::RecTy.
Definition at line 270 of file Record.cpp.
RecTy* llvm::ListRecTy::getElementType () const inline
Definition at line 303 of file Record.h.
Referenced by GetNewAnonymousName(), and llvm::ListInit::Profile().
virtual bool llvm::ListRecTy::typeIsConvertibleTo (const RecTy * RHS) const inline virtual
typeIsConvertibleTo - Return true if all values of 'this' type can be converted to the specified type.
Implements llvm::RecTy.
Definition at line 323 of file Record.h.
References llvm::RecTy::baseClassOf().
Friends And Related Function Documentation
ListRecTy* RecTy::getListTy () friend
The documentation for this class was generated from the following files:
Record.h
Record.cpp