LLVM: llvm::DILineInfo Class Reference
LLVM API Documentation
llvm::DILineInfo Class Reference
DILineInfo - a format-neutral container for source line information.
#include <DIContext.h>
Public Member Functions
DILineInfo ()
DILineInfo (StringRef fileName, StringRef functionName, uint32_t line, uint32_t column)
const char * getFileName ()
const char * getFunctionName ()
uint32_t getLine () const
uint32_t getColumn () const
bool operator== (const DILineInfo &RHS) const
bool operator!= (const DILineInfo &RHS) const
Detailed Description
DILineInfo - a format-neutral container for source line information.
Definition at line 32 of file DIContext.h.
Constructor & Destructor Documentation
llvm::DILineInfo::DILineInfo () inline
Definition at line 38 of file DIContext.h.
llvm::DILineInfo::DILineInfo (StringRef fileName, StringRef functionName, uint32_t line, uint32_t column) inline
Definition at line 41 of file DIContext.h.
Member Function Documentation
uint32_t llvm::DILineInfo::getColumn () const inline
Definition at line 49 of file DIContext.h.
const char* llvm::DILineInfo::getFileName () inline
Definition at line 46 of file DIContext.h.
References llvm::SmallString< InternalLen >::c_str().
const char* llvm::DILineInfo::getFunctionName () inline
Definition at line 47 of file DIContext.h.
References llvm::SmallString< InternalLen >::c_str().
uint32_t llvm::DILineInfo::getLine () const inline
Definition at line 48 of file DIContext.h.
bool llvm::DILineInfo::operator!= (const DILineInfo & RHS) const inline
Definition at line 56 of file DIContext.h.
bool llvm::DILineInfo::operator== (const DILineInfo & RHS) const inline
Definition at line 51 of file DIContext.h.
References llvm::SmallString< InternalLen >::equals().
The documentation for this class was generated from the following file:
DIContext.h