LLVM: llvm::SDUse Class Reference
LLVM API Documentation
llvm::SDUse Class Reference
#include <SelectionDAGNodes.h>
Public Member Functions
SDUse ()
operator const SDValue & () const
Normally SDUse will just implicitly convert to an SDValue that it holds.
const SDValue & get () const
SDNode * getUser ()
getUser - This returns the SDNode that contains this Use.
SDUse * getNext () const
getNext - Get the next SDUse in the use list.
SDNode * getNode () const
getNode - Convenience function for get().getNode().
unsigned getResNo () const
getResNo - Convenience function for get().getResNo().
EVT getValueType () const
getValueType - Convenience function for get().getValueType().
bool operator== (const SDValue &V) const
operator== - Convenience function for get().operator==
bool operator!= (const SDValue &V) const
operator!= - Convenience function for get().operator!=
bool operator< (const SDValue &V) const
operator< - Convenience function for get().operator<
Friends
class SelectionDAG
class SDNode
Detailed Description
SDUse - Represents a use of a SDNode. This class holds an SDValue, which records the SDNode being used and the result number, a pointer to the SDNode using the value, and Next and Prev pointers, which link together all the uses of an SDNode.
Definition at line 215 of file SelectionDAGNodes.h.
Constructor & Destructor Documentation
llvm::SDUse::SDUse () inline
Definition at line 228 of file SelectionDAGNodes.h.
Member Function Documentation
const SDValue& llvm::SDUse::get () const inline
If implicit conversion to SDValue doesn't work, the get() method returns the SDValue.
Definition at line 235 of file SelectionDAGNodes.h.
SDUse* llvm::SDUse::getNext () const inline
getNext - Get the next SDUse in the use list.
Definition at line 241 of file SelectionDAGNodes.h.
Referenced by llvm::SDNode::use_iterator::operator++().
SDNode* llvm::SDUse::getNode () const inline
getNode - Convenience function for get().getNode().
Definition at line 244 of file SelectionDAGNodes.h.
References llvm::SDValue::getNode().
Referenced by AddNodeIDOperands(), llvm::simplify_type< SDUse >::getSimplifiedValue(), llvm::SDNode::isOperandOf(), llvm::SelectionDAG::MorphNodeTo(), and llvm::SelectionDAG::RemoveDeadNodes().
unsigned llvm::SDUse::getResNo () const inline
getResNo - Convenience function for get().getResNo().
Definition at line 246 of file SelectionDAGNodes.h.
References llvm::SDValue::getResNo().
Referenced by AddNodeIDOperands(), ExtendUsesToFormExtLoad(), findGlueUse(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::SelectionDAG::ReplaceAllUsesOfValuesWith(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), and llvm::SelectionDAG::ReplaceAllUsesWith().
SDNode* llvm::SDUse::getUser () inline
getUser - This returns the SDNode that contains this Use.
Definition at line 238 of file SelectionDAGNodes.h.
Referenced by ExtendUsesToFormExtLoad(), findGlueUse(), llvm::SDNode::use_iterator::getOperandNo(), and llvm::SDNode::use_iterator::operator*().
EVT llvm::SDUse::getValueType () const inline
getValueType - Convenience function for get().getValueType().
Definition at line 248 of file SelectionDAGNodes.h.
References llvm::SDValue::getValueType().
llvm::SDUse::operator const SDValue & () const inline
Normally SDUse will just implicitly convert to an SDValue that it holds.
Definition at line 231 of file SelectionDAGNodes.h.
bool llvm::SDUse::operator!= (const SDValue & V) const inline
operator!= - Convenience function for get().operator!=
Definition at line 256 of file SelectionDAGNodes.h.
bool llvm::SDUse::operator< (const SDValue & V) const inline
operator< - Convenience function for get().operator<
Definition at line 261 of file SelectionDAGNodes.h.
bool llvm::SDUse::operator== (const SDValue & V) const inline
operator== - Convenience function for get().operator==
Definition at line 251 of file SelectionDAGNodes.h.
Friends And Related Function Documentation
friend class SDNode friend
Definition at line 267 of file SelectionDAGNodes.h.
friend class SelectionDAG friend
Definition at line 266 of file SelectionDAGNodes.h.
The documentation for this class was generated from the following file:
SelectionDAGNodes.h