LLVM: llvm::object::content_iterator< content_type > Class Template Reference
LLVM API Documentation
llvm::object::content_iterator< content_type > Class Template Reference
#include <ObjectFile.h>
Public Member Functions
content_iterator (content_type symb)
const content_type * operator-> () const
const content_type & operator* () const
bool operator== (const content_iterator &other) const
bool operator!= (const content_iterator &other) const
content_iterator & increment (error_code &err)
Detailed Description
template<class content_type>
class llvm::object::content_iterator< content_type >
Definition at line 43 of file ObjectFile.h.
Constructor & Destructor Documentation
template<class content_type > llvm::object::content_iterator< content_type >::content_iterator (content_type symb) inline
Definition at line 46 of file ObjectFile.h.
Member Function Documentation
template<class content_type > content_iterator& llvm::object::content_iterator< content_type >::increment (error_code & err) inline
Definition at line 65 of file ObjectFile.h.
References llvm::next().
Referenced by llvm::MCObjectDisassembler::buildModule(), llvm::RuntimeDyldImpl::emitSection(), llvm::MCObjectSymbolizer::findRelocationAt(), llvm::MCObjectDisassembler::getEntrypoint(), llvm::RuntimeDyldImpl::loadObject(), llvm::MCMachOObjectDisassembler::MCMachOObjectDisassembler(), llvm::object::printRelocationTargetName(), RemoveDupsFromAddressVector(), llvm::MCObjectSymbolizer::tryAddingSymbolicOperand(), and llvm::RuntimeDyldELF::~RuntimeDyldELF().
template<class content_type > bool llvm::object::content_iterator< content_type >::operator!= (const content_iterator< content_type > & other) const inline
Definition at line 61 of file ObjectFile.h.
template<class content_type > const content_type& llvm::object::content_iterator< content_type >::operator* () const inline
Definition at line 53 of file ObjectFile.h.
template<class content_type > const content_type* llvm::object::content_iterator< content_type >::operator-> () const inline
Definition at line 49 of file ObjectFile.h.
template<class content_type > bool llvm::object::content_iterator< content_type >::operator== (const content_iterator< content_type > & other) const inline
Definition at line 57 of file ObjectFile.h.
The documentation for this class was generated from the following file:
ObjectFile.h