LLVM: llvm::DefInit Class Reference
LLVM API Documentation
llvm::DefInit Class Reference
#include <Record.h>
Public Member Functions
virtual Init * convertInitializerTo (RecTy *Ty) const
Record * getDef () const
virtual RecTy * getFieldType (const std::string &FieldName) const
virtual Init * getFieldInit (Record &R, const RecordVal *RV, const std::string &FieldName) const
virtual std::string getAsString () const
getAsString - Convert this value to a string form.
virtual Init * getBit (unsigned Bit) const
virtual Init * resolveListElementReference (Record &R, const RecordVal *RV, unsigned Elt) const
Public Member Functions inherited from llvm::TypedInit
RecTy * getType () const
virtual Init * convertInitializerBitRange (const std::vector< unsigned > &Bits) const
virtual Init * convertInitListSlice (const std::vector< unsigned > &Elements) const
Public Member Functions inherited from llvm::Init
InitKind getKind () const
virtual ~Init ()
virtual bool isComplete () const
void print (raw_ostream &OS) const
print - Print out this value.
virtual std::string getAsUnquotedString () const
void dump () const
virtual Init * resolveReferences (Record &R, const RecordVal *RV) const
virtual Init * getBitVar () const
virtual unsigned getBitNum () const
Static Public Member Functions
static bool classof (const Init *I)
static DefInit * get (Record *)
Static Public Member Functions inherited from llvm::TypedInit
static bool classof (const Init *I)
Friends
class Record
Additional Inherited Members
Protected Types inherited from llvm::Init
enum InitKind {
IK_BitInit, IK_BitsInit, IK_FirstTypedInit, IK_DagInit,
IK_DefInit, IK_FieldInit, IK_IntInit, IK_ListInit,
IK_FirstOpInit, IK_BinOpInit, IK_TernOpInit, IK_UnOpInit,
IK_LastOpInit, IK_StringInit, IK_VarInit, IK_VarListElementInit,
IK_LastTypedInit, IK_UnsetInit, IK_VarBitInit
}
Discriminator enum (for isa<>, dyn_cast<>, et al.)
Protected Member Functions inherited from llvm::TypedInit
TypedInit (InitKind K, RecTy *T)
Protected Member Functions inherited from llvm::Init
Init (InitKind K)
Detailed Description
DefInit - AL - Represent a reference to a 'def' in the description
Definition at line 1174 of file Record.h.
Member Function Documentation
static bool llvm::DefInit::classof (const Init * I) inline static
Definition at line 1184 of file Record.h.
References llvm::Init::getKind().
virtual Init* llvm::DefInit::convertInitializerTo (RecTy * Ty) const inline virtual
convertInitializerTo - This virtual function is a simple call-back function that should be overridden to call the appropriate RecTy::convertValue method.
Implements llvm::Init.
Definition at line 1189 of file Record.h.
References llvm::RecTy::convertValue().
DefInit * DefInit::get (Record * R) static
Definition at line 1468 of file Record.cpp.
References llvm::Record::getDefInit().
Referenced by llvm::UnOpInit::Fold(), llvm::TernOpInit::Fold(), and GetNewAnonymousName().
std::string DefInit::getAsString () const virtual
getAsString - Convert this value to a string form.
Implements llvm::Init.
Definition at line 1484 of file Record.cpp.
References llvm::tgtok::Def.
Referenced by llvm::TernOpInit::Fold().
virtual Init* llvm::DefInit::getBit (unsigned Bit) const inline virtual
getBit - This method is used to return the initializer for the specified bit.
Implements llvm::Init.
Definition at line 1203 of file Record.h.
References llvm_unreachable.
Record* llvm::DefInit::getDef () const inline
Definition at line 1193 of file Record.h.
References llvm::tgtok::Def, and llvm::RecTy::getAsString().
Referenced by llvm::RecordRecTy::convertValue(), and llvm::BinOpInit::Fold().
Init * DefInit::getFieldInit (Record & R, const RecordVal * RV, const std::string & FieldName) const virtual
getFieldInit - This method complements getFieldType to return the initializer for the specified field. If getFieldType returns non-null this method should return non-null, otherwise it returns null.
Reimplemented from llvm::Init.
Definition at line 1478 of file Record.cpp.
References llvm::tgtok::Def.
RecTy * DefInit::getFieldType (const std::string & FieldName) const virtual
getFieldType - This method is used to implement the FieldInit class. Implementors of this method should return the type of the named field if they are of record type.
Reimplemented from llvm::TypedInit.
Definition at line 1472 of file Record.cpp.
References llvm::tgtok::Def.
virtual Init* llvm::DefInit::resolveListElementReference (Record & R, const RecordVal * RV, unsigned Elt) const inline virtual
resolveListElementReference - This method is used to implement VarListElementInit::resolveReferences. If the list element is resolvable now, we return the resolved value, otherwise we return null.
Implements llvm::TypedInit.
Definition at line 1210 of file Record.h.
References llvm_unreachable.
Friends And Related Function Documentation
friend class Record friend
Definition at line 1178 of file Record.h.
The documentation for this class was generated from the following files:
Record.h
Record.cpp