LLVM: llvm::Value Class Reference
LLVM API Documentation
llvm::Value Class Reference
LLVM Value Representation.
#include <Value.h>
Public Types
enum ValueTy {
ArgumentVal, BasicBlockVal, FunctionVal, GlobalAliasVal,
GlobalVariableVal, UndefValueVal, BlockAddressVal, ConstantExprVal,
ConstantAggregateZeroVal, ConstantDataArrayVal, ConstantDataVectorVal, ConstantIntVal,
ConstantFPVal, ConstantArrayVal, ConstantStructVal, ConstantVectorVal,
ConstantPointerNullVal, MDNodeVal, MDStringVal, InlineAsmVal,
PseudoSourceValueVal, FixedStackPseudoSourceValueVal, InstructionVal, ConstantFirstVal = FunctionVal,
ConstantLastVal = ConstantPointerNullVal
}
typedef value_use_iterator< User > use_iterator
typedef value_use_iterator< const User > const_use_iterator
Public Member Functions
virtual ~Value ()
void dump () const
dump - Support for debugging, callable in GDB: V->dump()
void print (raw_ostream &O, AssemblyAnnotationWriter *AAW=0) const
Type * getType () const
LLVMContext & getContext () const
All values hold a context through their type.
bool hasName () const
ValueName * getValueName () const
void setValueName (ValueName *VN)
StringRef getName () const
void setName (const Twine &Name)
void takeName (Value *V)
void replaceAllUsesWith (Value *V)
bool use_empty () const
use_iterator use_begin ()
const_use_iterator use_begin () const
use_iterator use_end ()
const_use_iterator use_end () const
User * use_back ()
const User * use_back () const
bool hasOneUse () const
bool hasNUses (unsigned N) const
bool hasNUsesOrMore (unsigned N) const
bool isUsedInBasicBlock (const BasicBlock *BB) const
unsigned getNumUses () const
void addUse (Use &U)
unsigned getValueID () const
unsigned getRawSubclassOptionalData () const
void clearSubclassOptionalData ()
bool hasSameSubclassOptionalData (const Value *V) const
void intersectOptionalDataWith (const Value *V)
bool hasValueHandle () const
Value * stripPointerCasts ()
Strips off any unneeded pointer casts, all-zero GEPs and aliases from the specified value, returning the original uncasted value.
const Value * stripPointerCasts () const
Value * stripPointerCastsNoFollowAliases ()
Strips off any unneeded pointer casts and all-zero GEPs from the specified value, returning the original uncasted value.
const Value * stripPointerCastsNoFollowAliases () const
Value * stripInBoundsConstantOffsets ()
Strips off unneeded pointer casts and all-constant GEPs from the specified value, returning the original pointer value.
const Value * stripInBoundsConstantOffsets () const
Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset)
Strips like stripInBoundsConstantOffsets but also accumulates the constant offset stripped.
const Value * stripAndAccumulateInBoundsConstantOffsets (const DataLayout &DL, APInt &Offset) const
Value * stripInBoundsOffsets ()
Strips off unneeded pointer casts and any in-bounds offsets from the specified value, returning the original pointer value.
const Value * stripInBoundsOffsets () const
bool isDereferenceablePointer () const
Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB)
const Value * DoPHITranslation (const BasicBlock *CurBB, const BasicBlock *PredBB) const
void mutateType (Type *Ty)
Static Public Attributes
static const unsigned MaximumAlignment = 1u << 29
Protected Member Functions
virtual void printCustom (raw_ostream &O) const
Value (Type *Ty, unsigned scid)
unsigned short getSubclassDataFromValue () const
void setValueSubclassData (unsigned short D)
Protected Attributes
unsigned char SubclassOptionalData: 7
Friends
class ValueSymbolTable
class ValueHandleBase
Detailed Description
LLVM Value Representation.
This is a very important LLVM class. It is the base class of all values computed by a program that may be used as operands to other values. Value is the super class of other important classes such as Instruction and Function. All Values have a Type. Type is not a subclass of Value. Some values can have a name and they belong to some Module. Setting the name on the Value automatically updates the module's symbol table.
Every value has a "use list" that keeps track of which other Values are using this Value. A Value can also have an arbitrary number of ValueHandle objects that watch it and listen to RAUW and Destroy events. See llvm/Support/ValueHandle.h for details.
Definition at line 66 of file Value.h.
Member Typedef Documentation
typedef value_use_iterator<const User> llvm::Value::const_use_iterator
Definition at line 147 of file Value.h.
typedef value_use_iterator<User> llvm::Value::use_iterator
Definition at line 146 of file Value.h.
Member Enumeration Documentation
enum llvm::Value::ValueTy
An enumeration for keeping track of the concrete subclass of Value that is actually instantiated. Values of this enumeration are kept in the Value classes SubclassID field. They are used for concrete type identification.
Enumerator
ArgumentVal
BasicBlockVal
FunctionVal
GlobalAliasVal
GlobalVariableVal
UndefValueVal
BlockAddressVal
ConstantExprVal
ConstantAggregateZeroVal
ConstantDataArrayVal
ConstantDataVectorVal
ConstantIntVal
ConstantFPVal
ConstantArrayVal
ConstantStructVal
ConstantVectorVal
ConstantPointerNullVal
MDNodeVal
MDStringVal
InlineAsmVal
PseudoSourceValueVal
FixedStackPseudoSourceValueVal
InstructionVal
ConstantFirstVal
ConstantLastVal
Definition at line 191 of file Value.h.
Constructor & Destructor Documentation
Value::Value (Type * Ty, unsigned scid) protected
Definition at line 44 of file Value.cpp.
References BasicBlockVal, llvm::Call, ConstantLastVal, llvm::Type::isFirstClassType(), llvm::Type::isStructTy(), and llvm::Type::isVoidTy().
Referenced by ValuesOverlap().
Value::~Value () virtual
Definition at line 60 of file Value.cpp.
References llvm::dbgs(), llvm::StringMapEntry< ValueTy >::Destroy(), getName(), I, MDStringVal, llvm::LeakDetector::removeGarbageObject(), use_begin(), use_empty(), use_end(), and llvm::ValueHandleBase::ValueIsDeleted().
Member Function Documentation
void llvm::Value::addUse (Use & U) inline
addUse - This method should only be used by the Use class.
Definition at line 185 of file Value.h.
Referenced by llvm::Use::set(), and llvm::Use::swap().
void llvm::Value::clearSubclassOptionalData () inline
clearSubclassOptionalData - Clear the optional flags contained in this value.
Definition at line 246 of file Value.h.
References SubclassOptionalData.
Referenced by ClearSubclassDataAfterReassociation(), and LinearizeExprTree().
Value * Value::DoPHITranslation (const BasicBlock * CurBB, const BasicBlock * PredBB)
DoPHITranslation - If this value is a PHI node with CurBB as its parent, return the value in the PHI node corresponding to PredBB. If not, return ourself. This is useful if you want to know the value something has in a predecessor block.
Definition at line 509 of file Value.cpp.
References llvm::dyn_cast(), llvm::PHINode::getIncomingValueForBlock(), and llvm::Instruction::getParent().
Referenced by DoPHITranslation(), FoldOperationIntoSelectOperand(), getKnownConstant(), and stripInBoundsOffsets().
const Value* llvm::Value::DoPHITranslation (const BasicBlock * CurBB, const BasicBlock * PredBB) const inline
Definition at line 328 of file Value.h.
References DoPHITranslation().
void Value::dump () const
dump - Support for debugging, callable in GDB: V->dump()
Definition at line 2212 of file AsmWriter.cpp.
References llvm::dbgs().
Referenced by checkInterfaceFunction(), collectFailStats(), llvm::createGVNPass(), llvm::LexicalScope::dump(), llvm::dumpBlock(), llvm::dumpInst(), llvm::NamedMDNode::getParent(), getTruncatedArgReg(), llvm::ExecutionEngine::InitializeMemory(), llvm::ValueEnumerator::print(), and WriteConstants().
LLVMContext & Value::getContext () const
All values hold a context through their type.
Definition at line 517 of file Value.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::begin(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::erase(), llvm::Type::getContext(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::getPointerIntoBucketsArray(), I, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::isPointerIntoBucketsArray(), llvm::tgtok::List, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::size(), and llvm::LLVMContextImpl::ValueHandles.
Referenced by llvm::Function::addAttribute(), llvm::Function::addAttributes(), AddOne(), AddWithOverflow(), AppendMDNodeToInstForPtr(), llvm::SelectInst::areInvalidOperands(), BitCastConstantVector(), CanShareConstantPoolEntry(), changeToUnreachable(), clearGarbage(), llvm::FenceInst::clone_impl(), llvm::UnreachableInst::clone_impl(), CloneLoop(), CollectInsertionElements(), CollectShuffleElements(), CollectSingleShuffleElements(), computeBytesPoppedByCallee(), llvm::ComputeMultiple(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCompareInstruction(), llvm::ConstantFoldInsertElementInstruction(), llvm::ConstantFoldLoadFromConstPtr(), llvm::ConstantFoldShuffleVectorInstruction(), ConvertToSInt(), llvm::SelectionDAGBuilder::CopyValueToVirtualRegister(), llvm::ARMConstantPoolConstant::Create(), llvm::createCorrelatedValuePropagationPass(), llvm::createObjCARCContractPass(), llvm::createObjCARCOptPass(), CreatePrologue(), llvm::createSjLjEHPreparePass(), decomposeBitTestICmp(), llvm::MDNode::deleteTemporary(), llvm::ConstantAggregateZero::destroyConstant(), llvm::ConstantPointerNull::destroyConstant(), llvm::ConstantDataSequential::destroyConstant(), llvm::UndefValue::destroyConstant(), determinePointerReadAttrs(), llvm::Function::eraseFromParent(), ExtractConstantBytes(), llvm::FastISel::FastEmitBranch(), llvm::FindAllocaDbgDeclare(), FindInitTrampoline(), FitsInFPType(), FoldBitCast(), llvm::FoldBranchToCommonDest(), llvm::InstCombiner::FoldCmpLoadFromIndexedGlobal(), llvm::InstCombiner::FoldICmpAddOpCst(), FoldReinterpretLoadFromConstPtr(), llvm::InstCombiner::FoldShiftByConstant(), ftostr(), GatherConstantCompares(), genLoopLimit(), llvm::DebugLoc::get(), llvm::ConstantArray::get(), llvm::ConstantVector::get(), llvm::ConstantExpr::get(), llvm::DebugLoc::getAsMDNode(), getComparePred(), llvm::LazyValueInfo::getConstant(), llvm::LazyValueInfo::getConstantOnEdge(), getEdgeValueLocal(), llvm::ConstantDataSequential::getElementAsConstant(), llvm::ConstantExpr::getExtractElement(), llvm::ConstantExpr::getExtractValue(), llvm::ConstantExpr::getFCmp(), getFCmpValue(), getGEPInductionOperand(), llvm::ConstantExpr::getGetElementPtr(), llvm::ConstantExpr::getICmp(), llvm::ConstantExpr::getInsertElement(), llvm::ConstantExpr::getInsertValue(), llvm::Function::getIntrinsicID(), getKnownConstant(), llvm::InvokeInst::getLandingPadInst(), getMemCmpLoad(), llvm::MDNode::getMostGenericRange(), llvm::MDNode::getMostGenericTBAA(), llvm::getObjectSize(), getOpenCLAlignment(), llvm::Function::getPrefixData(), llvm::FastISel::getRegForValue(), llvm::ConstantExpr::getSelect(), GetShiftedValue(), llvm::ConstantDataVector::getSplat(), getType(), llvm::ConstantStruct::getTypeForElements(), HandleByValArgument(), IdxCompare(), llvm::InlineFunction(), llvm::DIBuilder::insertDbgValueIntrinsic(), llvm::DIBuilder::insertDeclare(), insertVector(), InstallGlobalCtors(), InstCombineStoreToCast(), llvm::isAllocaPromotable(), llvm::isBytewiseValue(), isCompatibleAggregate(), llvm::CmpInst::isFalseWhenEqual(), isFormingBranchFromSelectProfitable(), isZero(), llvm::FastISel::leaveLocalValueArea(), LLVMAddAttribute(), LLVMRemoveAttribute(), LLVMSetParamAlignment(), LookThroughFPExtensions(), nvptx::LowerConstant(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::MapValue(), MarkIndicesSafe(), llvm::MergeBasicBlockIntoOnlyPred(), operator<<(), OptimizeGlobalAddressOfMalloc(), OptimizeNoopCopyExpression(), OptimizeVectorResize(), PerformHeapAllocSRoA(), llvm::ValueEnumerator::print(), ProcessUGT_ADDCST_ADD(), ReadDataFromGlobal(), reduceToSingleValueType(), llvm::Function::removeAttributes(), llvm::SwitchInst::removeCase(), llvm::replaceDbgDeclareForAlloca(), ReplaceFPIntrinsicWithCall(), ReplaceUsesOfWith(), llvm::ConstantStruct::replaceUsesOfWithOnConstant(), llvm::BlockAddress::replaceUsesOfWithOnConstant(), llvm::Instruction::setMetadata(), setName(), llvm::Function::setPrefixData(), setUsedInitializer(), ShrinkDemandedConstant(), SimplifyBranchOnICmpChain(), SimplifyCondBranchToCondBranch(), SimplifyICmpInst(), SimplifyTerminatorOnSelect(), AllocaSlices::SliceBuilder::SliceBuilder(), llvm::SplitCriticalEdge(), SRAGlobal(), stripAndComputeConstantOffsets(), SubOne(), SubWithOverflow(), SwitchToLookupTable(), TryToShrinkGlobalToBoolean(), TryToSimplifyUncondBranchWithICmpInIt(), TurnSwitchRangeIntoICmp(), llvm::UnreachableInst::UnreachableInst(), llvm::UpgradeBitCastExpr(), llvm::UpgradeBitCastInst(), llvm::UpgradeInstWithTBAATag(), llvm::UpgradeIntrinsicCall(), llvm::ValueHandleBase::ValueIsDeleted(), llvm::ValueHandleBase::ValueIsRAUWd(), llvm::InstCombiner::visitAllocaInst(), llvm::InstCombiner::visitBitCast(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitFree(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitIntToPtr(), llvm::InstCombiner::visitPtrToInt(), llvm::Interpreter::visitReturnInst(), llvm::InstCombiner::visitShuffleVectorInst(), llvm::InstCombiner::visitTrunc(), WriteMDNode(), X86ChooseCmpImmediateOpcode(), llvm::Function::~Function(), and llvm::ReturnInst::~ReturnInst().
StringRef Value::getName () const
getName() - Return a constant reference to the value's name. This is cheap and guaranteed to return the same reference as long as the value is not modified.
Definition at line 167 of file Value.cpp.
References llvm::StringMapEntry< ValueTy >::getKey().
Referenced by llvm::ExecutionEngine::addGlobalMapping(), AddPHINodeEntriesForMappedBlock(), AddressIsTaken(), llvm::X86FrameLowering::adjustForHiPEPrologue(), assureFPCallStub(), llvm::MDString::begin(), llvm::PBQPBuilderWithCoalescing::build(), llvm::Interpreter::callExternalFunction(), llvm::CallGraph::CallGraph(), canBeHidden(), llvm::canConstantFoldCallTo(), CanPropagatePredecessorsForPHIs(), checkInterfaceFunction(), llvm::CloneBasicBlock(), llvm::CloneFunction(), CloneLoop(), CommitValueTo(), llvm::InstCombiner::commonShiftTransforms(), LTOCodeGenerator::compile(), ConnectProlog(), llvm::ConstantFoldCall(), ConstructSSAForLoadSet(), ConvertAtomicSynchScope(), ConvertToSInt(), copyGVAttributes(), llvm::createArgumentPromotionPass(), llvm::createBasicAliasAnalysisPass(), createCast(), createFPFnStub(), llvm::createJumpThreadingPass(), llvm::createLICMPass(), llvm::createLoopSimplifyPass(), llvm::createLoopVectorizePass(), llvm::createPPCCTRLoopsVerify(), createPrivateNonConstGlobalForString(), CreatePrologue(), createReplacementInstr(), deleteIfDeadInstruction(), DeleteInstructionInBlock(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), DescKind(), llvm::DISubprogram::describes(), determinePointerReadAttrs(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::InstCombiner::DoOneIteration(), llvm::dumpBlock(), EmitCamlGlobal(), llvm::ARMJITInfo::emitFunctionStub(), llvm::EmitGEPOffset(), llvm::ExecutionEngine::emitGlobals(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), llvm::MDString::end(), enqueueUsersInWorklist(), EvaluateStaticConstructor(), llvm::ExtractTypeInfo(), llvm::CodeExtractor::findInputsOutputs(), FindMostPopularDest(), FindPhiPredForUseInBlock(), FindPredecessorAutoreleaseWithSafePath(), FindScalarElement(), FirstNonDbg(), fixupSubprogramName(), llvm::SimplifyFortifiedLibCalls::fold(), llvm::InstCombiner::FoldAndOfICmps(), FoldBlockIntoPredecessor(), llvm::FoldBranchToCommonDest(), FoldCondBranchOnPHI(), llvm::InstCombiner::FoldICmpShrCst(), FoldOperationIntoSelectOperand(), llvm::InstCombiner::FoldOrOfICmps(), llvm::InstCombiner::FoldSelectOpOp(), llvm::InstCombiner::FoldShiftByConstant(), FoldTwoEntryPHINode(), forceRenaming(), ftostr(), FunctionNumber(), GenerateARCAnnotation(), GenerateARCBBEntranceAnnotation(), GenerateARCBBTerminatorAnnotation(), getAllocationData(), llvm::DOTGraphTraits< const Function * >::getCompleteNodeLabel(), llvm::Intrinsic::getDeclaration(), getEdgeValueLocal(), llvm::TargetLoweringObjectFileMachO::getExplicitSectionGlobal(), getFCmpValue(), llvm::MachineBasicBlock::getFullName(), llvm::objcarc::GetFunctionClass(), llvm::LibCallInfo::getFunctionInfo(), getFunctionName(), getGEPInductionOperand(), llvm::DOTGraphTraits< const Function * >::getGraphName(), llvm::DOTGraphTraits< BlockFrequencyInfo * >::getGraphName(), llvm::InlineCostAnalysis::getInlineCost(), llvm::getInst(), getIntrinsicIDForCall(), llvm::MDString::getLength(), llvm::MachineFunction::getName(), llvm::Region::getNameStr(), llvm::Mangler::getNameWithPrefix(), llvm::DOTGraphTraits< BlockFrequencyInfo * >::getNodeLabel(), llvm::JIT::getOrEmitGlobalVariable(), llvm::SparseSolver::getOrInitValueState(), llvm::NamedMDNode::getParent(), getPointerOperand(), llvm::JIT::getPointerToFunction(), llvm::MCJIT::getPointerToFunction(), llvm::TargetTransformInfo::getReductionCost(), llvm::getSamplerName(), llvm::DOTGraphTraits< const Function * >::getSimpleNodeLabel(), llvm::MDString::getString(), llvm::getSurfaceName(), llvm::getTextureName(), getTypePartition(), GlobalWasGeneratedByAsan(), HandleByValArgument(), HandleCallsInBlockInlinedThroughInvoke(), hasAddressTakenAndUsed(), hasMemoryWrite(), HoistThenElseCodeToIf(), INITIALIZE_PASS(), llvm::InlineFunction(), llvm::InsertPreheaderForLoop(), insertVector(), InstCombineLoadCast(), InstCombineStoreToCast(), InstructionDereferencesPointer(), isAlwaysFoldable(), isCompatibleAggregate(), isContiguous(), isExitBlock(), llvm::isFreeCall(), llvm::SpecialCaseList::isIn(), isInterestingPointer(), isIntrinsicInline(), isLessConstraining(), isLifetimeStart(), isLoopInvariant(), isNonGhostDeclaration(), isOnlyReachableViaThisEdge(), isSafeAndProfitableToSinkLoad(), llvm::linkShadowStackGC(), llvm::LoadAndStorePromoter::LoadAndStorePromoter(), lookupFunction(), llvm::LibCallSimplifierImpl::lookupOptimization(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::IntrinsicLowering::LowerToByteSwap(), MarkBlocksLiveIn(), MarkIndicesSafe(), llvm::MipsCallEntry::mayAlias(), NegateValue(), NumRetVals(), operator<<(), llvm::operator<<(), OptimizeGlobalAddressOfMalloc(), llvm::OptLevelChanger::OptLevelChanger(), PerformHeapAllocSRoA(), llvm::PHITransAddr::PHITranslateWithInsertion(), PlaceSplitBlockCarefully(), llvm::ValueEnumerator::print(), llvm::Trace::print(), llvm::SparseSolver::Print(), llvm::CallGraph::print(), llvm::CallGraphNode::print(), llvm::AssemblyWriter::printBasicBlock(), llvm::BranchProbabilityInfo::printEdgeProbability(), PrintLLVMName(), ProcessUGT_ADDCST_ADD(), RecognizePersonality(), ReplaceCallWith(), ReplaceUsesOfMallocWithGlobal(), ReplaceUsesOfWith(), RewriteHeapSROALoadUser(), RewriteUsesOfClonedInstructions(), RightDistributesOverLeft(), llvm::LLParser::Run(), llvm::DOTGraphTraitsViewer< Analysis, Simple >::runOnFunction(), llvm::DOTGraphTraitsPrinter< Analysis, Simple >::runOnFunction(), llvm::LPPassManager::runOnFunction(), llvm::RGPassManager::runOnFunction(), llvm::FPPassManager::runOnFunction(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::MipsOs16::runOnModule(), llvm::Inliner::runOnSCC(), llvm::VLIWMachineScheduler::schedule(), llvm::FastISel::SelectInstruction(), llvm::BranchProbabilityInfo::setEdgeWeight(), setName(), setValueName(), shouldInternalize(), shouldSpeculateInstrs(), ShrinkDemandedConstant(), SimplifyCondBranchToCondBranch(), SinkThenElseCodeToEnd(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), speculatePHINodeLoads(), speculateSelectInstLoads(), SpeculativelyExecuteBB(), llvm::SplitBlock(), llvm::SplitBlockPredecessors(), llvm::SplitCriticalEdge(), llvm::SplitLandingPadPredecessors(), SRAGlobal(), StackMallocSizeClass(), StripSymtab(), tryToMakeAllocaBePromotable(), TryToOptimizeStoreOfMallocToGlobal(), TryToShrinkGlobalToBoolean(), TurnSwitchRangeIntoICmp(), llvm::UnrollLoop(), UpdatePHINodes(), llvm::UpgradeIntrinsicCall(), UpgradeIntrinsicFunction1(), UpgradeSSE41Function(), usedInGlobalVarDef(), llvm::ValueHandleBase::ValueIsDeleted(), llvm::ValueHandleBase::ValueIsRAUWd(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAllocaInst(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitFPTrunc(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithCastAndCast(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitSDiv(), llvm::InstCombiner::visitSelectInst(), llvm::InstCombiner::visitSExt(), llvm::InstCombiner::visitSRem(), llvm::InstCombiner::visitTrunc(), llvm::InstCombiner::visitXor(), llvm::InstCombiner::visitZExt(), llvm::OptLevelChanger::~OptLevelChanger(), ~Value(), and llvm::ValueSymbolTable::~ValueSymbolTable().
unsigned Value::getNumUses () const
getNumUses - This method computes the number of uses of this Value. This is a linear time operation. Use hasOneUse, hasNUses, or hasNUsesOrMore to check for specific values.
getNumUses - This method computes the number of uses of this Value. This is a linear time operation. Use hasOneUse or hasNUses to check for specific values.
Definition at line 139 of file Value.cpp.
References use_begin(), and use_end().
Referenced by llvm::createDwarfEHPass(), hasOneUse(), IsNonLocalValue(), isSimpleLoadStore(), and MarkBlocksLiveIn().
unsigned llvm::Value::getRawSubclassOptionalData () const inline
getRawSubclassOptionalData - Return the raw optional flags value contained in this value. This should only be used when testing two Values for equivalence.
Definition at line 240 of file Value.h.
References SubclassOptionalData.
Referenced by llvm::ConstantKeyData< ConstantExpr >::getValType().
unsigned short llvm::Value::getSubclassDataFromValue () const inline protected
Definition at line 347 of file Value.h.
Referenced by llvm::MDNode::classof(), llvm::MDNode::deleteTemporary(), llvm::MDNode::getFunction(), llvm::ConstantExpr::getOpcode(), llvm::MDNode::getTemporary(), llvm::MDNode::isFunctionLocal(), llvm::MDNode::Profile(), llvm::MDNode::replaceOperandWith(), llvm::Function::setPrefixData(), and llvm::Function::~Function().
Type* llvm::Value::getType () const inline
All values are typed, get the type of this value.
Definition at line 111 of file Value.h.
References getContext().
Referenced by llvm::GetElementPtrInst::accumulateConstantOffset(), llvm::AliasSetTracker::add(), llvm::SSAUpdater::AddAvailableValue(), llvm::PHINode::addIncoming(), AddOne(), AddressIsTaken(), llvm::IVUsers::AddUsersImpl(), AddWithOverflow(), AnalyzeLoadFromClobberingLoad(), AnalyzeLoadFromClobberingStore(), areAllUsesIn(), llvm::SelectInst::areInvalidOperands(), llvm::AtomicCmpXchgInst::AtomicCmpXchgInst(), BitCastConstantVector(), BreakUpSubtract(), BuildConstantFromSCEV(), buildMultiplyTree(), BuildNew(), BuildSubAggregate(), CanCoerceMustAliasedValueToLoad(), CanEvaluateSExtd(), CanEvaluateShifted(), CanEvaluateTruncated(), CanEvaluateZExtd(), llvm::FastISel::canFoldAddIntoGEP(), canFoldIVIncExpr(), CanShareConstantPoolEntry(), canTrapImpl(), llvm::CastInst::castIsValid(), CheapToScalarize(), checkBinaryFloatSignature(), checkInterfaceFunction(), checkUnaryFloatSignature(), llvm::FPMathOperator::classof(), llvm::ExtractValueInst::classof(), llvm::TypeFinder::clear(), llvm::VAArgInst::clone_impl(), llvm::TruncInst::clone_impl(), llvm::ZExtInst::clone_impl(), llvm::SExtInst::clone_impl(), llvm::FPTruncInst::clone_impl(), llvm::FPExtInst::clone_impl(), llvm::UIToFPInst::clone_impl(), llvm::SIToFPInst::clone_impl(), llvm::FPToUIInst::clone_impl(), llvm::FPToSIInst::clone_impl(), llvm::IntToPtrInst::clone_impl(), llvm::PtrToIntInst::clone_impl(), llvm::BitCastInst::clone_impl(), llvm::AddrSpaceCastInst::clone_impl(), llvm::CloneAndPruneFunctionInto(), CloneLoop(), CoerceAvailableValueToLoadType(), CollectBSwapParts(), collectFailStats(), CollectInsertionElements(), CollectShuffleElements(), CollectSingleShuffleElements(), CommitValueTo(), llvm::InstCombiner::commonCastTransforms(), llvm::InstCombiner::commonIDivTransforms(), llvm::InstCombiner::commonPointerCastTransforms(), llvm::InstCombiner::commonShiftTransforms(), computeBytesPoppedByCallee(), llvm::ComputeMaskedBits(), llvm::ComputeMultiple(), llvm::ComputeNumSignBits(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), computePointerICmp(), ComputePostOrders(), llvm::ComputeSignBit(), llvm::ComputeUsesVAFloatArgument(), ConnectProlog(), ConstantFold(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCastInstruction(), llvm::ConstantFoldCompareInstOperands(), llvm::ConstantFoldCompareInstruction(), ConstantFoldConstantExpressionImpl(), llvm::ConstantFoldExtractElementInstruction(), ConstantFoldGetElementPtrImpl(), llvm::ConstantFoldInsertElementInstruction(), llvm::ConstantFoldInsertValueInstruction(), llvm::ConstantFoldInstOperands(), llvm::ConstantFoldInstruction(), llvm::ConstantFoldLoadFromConstPtr(), llvm::ConstantFoldSelectInstruction(), llvm::ConstantFoldShuffleVectorInstruction(), ConstructSSAForLoadSet(), ConvertAtomicSynchScope(), convertMemSetToLoop(), ConvertShiftToMul(), ConvertToSInt(), convertTransferToLoop(), convertValue(), llvm::SelectionDAGBuilder::CopyToExportRegsIfNeeded(), llvm::SelectionDAGBuilder::CopyValueToVirtualRegister(), llvm::BinaryOperator::Create(), llvm::createAMDGPUISelDag(), llvm::IRBuilder< true, TargetFolder >::CreateAnd(), createAndInstr(), llvm::createArgumentPromotionPass(), llvm::IRBuilder< true, TargetFolder >::CreateAShr(), llvm::createBasicAliasAnalysisPass(), llvm::TargetFolder::CreateCast(), createCast(), llvm::IRBuilder< true, TargetFolder >::CreateCast(), llvm::createCorrelatedValuePropagationPass(), llvm::createDeadArgHackingPass(), createFailOrdering(), llvm::BinaryOperator::CreateFNeg(), llvm::TargetFolder::CreateFPCast(), llvm::CastInst::CreateFPCast(), llvm::IRBuilder< true, TargetFolder >::CreateFPCast(), createFree(), llvm::CallInst::CreateFree(), llvm::createFunctionAttrsPass(), llvm::createGlobalsModRefPass(), llvm::IRBuilderBase::CreateGlobalString(), llvm::CompileUnit::createGlobalVariableDIE(), llvm::createIndVarSimplifyPass(), llvm::TargetFolder::CreateIntCast(), llvm::IRBuilder< true, TargetFolder >::CreateIntCast(), llvm::CastInst::CreateIntegerCast(), llvm::IRBuilder< true, TargetFolder >::CreateIsNotNull(), llvm::IRBuilder< true, TargetFolder >::CreateIsNull(), llvm::createLICMPass(), llvm::IRBuilderBase::CreateLifetimeEnd(), llvm::IRBuilderBase::CreateLifetimeStart(), llvm::createLoopSimplifyPass(), llvm::createLoopVectorizePass(), llvm::IRBuilder< true, TargetFolder >::CreateLShr(), createMalloc(), llvm::IRBuilderBase::CreateMemCpy(), llvm::IRBuilderBase::CreateMemMove(), llvm::IRBuilderBase::CreateMemSet(), llvm::BinaryOperator::CreateNeg(), llvm::BinaryOperator::CreateNot(), llvm::BinaryOperator::CreateNSWNeg(), llvm::BinaryOperator::CreateNUWNeg(), llvm::createNVVMReflectPass(), llvm::createObjCARCContractPass(), llvm::createObjCARCOptPass(), llvm::IRBuilder< true, TargetFolder >::CreateOr(), createPHIsForSplitLoopExit(), llvm::TargetFolder::CreatePointerCast(), llvm::CastInst::CreatePointerCast(), llvm::IRBuilder< true, TargetFolder >::CreatePointerCast(), createPrivateGlobalForString(), createPrivateNonConstGlobalForString(), llvm::IRBuilder< true, TargetFolder >::CreatePtrDiff(), createReplacementInstr(), llvm::TargetFolder::CreateSExtOrBitCast(), llvm::CastInst::CreateSExtOrBitCast(), llvm::IRBuilder< true, TargetFolder >::CreateSExtOrBitCast(), llvm::IRBuilder< true, TargetFolder >::CreateSExtOrTrunc(), llvm::IRBuilder< true, TargetFolder >::CreateShl(), llvm::TargetFolder::CreateTruncOrBitCast(), llvm::CastInst::CreateTruncOrBitCast(), llvm::IRBuilder< true, TargetFolder >::CreateTruncOrBitCast(), llvm::IRBuilder< true, TargetFolder >::CreateVectorSplat(), llvm::IRBuilder< true, TargetFolder >::CreateXor(), llvm::TargetFolder::CreateZExtOrBitCast(), llvm::CastInst::CreateZExtOrBitCast(), llvm::IRBuilder< true, TargetFolder >::CreateZExtOrBitCast(), llvm::IRBuilder< true, TargetFolder >::CreateZExtOrTrunc(), cse(), CvtFDivConstToReciprocal(), cxxDtorIsEmpty(), DecomposeGEPExpression(), DecomposeSimpleLinearExpr(), llvm::DeleteDeadBlock(), deleteIfDeadInstruction(), DeleteInstructionInBlock(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), llvm::InstCombiner::DoOneIteration(), dyn_castFoldableMul(), EliminateDeadSwitchCases(), emitDebugValueComment(), llvm::EmitFPutC(), llvm::EmitFPutS(), llvm::EmitFWrite(), llvm::EmitGEPOffset(), llvm::AsmPrinter::EmitGlobalConstant(), emitGlobalConstantFP(), emitGlobalConstantImpl(), emitGlobalConstantStruct(), llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc(), llvm::EmitStrNCpy(), llvm::EmitUnaryFloatFnCall(), llvm::ARMAsmPrinter::EmitXXStructor(), EraseTerminatorInstAndDCECond(), EvaluateExpression(), evaluateFCmpRelation(), EvaluateGEPOffsetExpression(), evaluateICmpRelation(), EvaluateStoreInto(), llvm::expandDivision(), llvm::expandDivisionUpTo32Bits(), llvm::ARMTargetLowering::ExpandInlineAsm(), llvm::X86TargetLowering::ExpandInlineAsm(), llvm::expandRemainderUpTo32Bits(), ExtractConstantBytes(), extractInteger(), extractVector(), llvm::FastISel::FastEmitBranch(), llvm::FastISel::FastEmitZExtFromI1(), llvm::FindAvailableLoadedValue(), FindInitTrampoline(), llvm::CodeExtractor::findInputsOutputs(), llvm::FindInsertedValue(), FindLIVLoopCondition(), FindLoopCounter(), FindMostPopularDest(), FindPhiPredForUseInBlock(), FindScalarElement(), FirstNonDbg(), FitWeights(), fixupFPReturnAndCall(), llvm::InstCombiner::FoldAndOfFCmps(), llvm::InstCombiner::FoldAndOfICmps(), FoldBitCast(), llvm::InstCombiner::FoldCmpLoadFromIndexedGlobal(), foldConstantCastPair(), llvm::InstCombiner::FoldFCmp_IntToFP_Cst(), llvm::InstCombiner::FoldGEPICmp(), llvm::InstCombiner::FoldICmpAddOpCst(), llvm::InstCombiner::FoldICmpShrCst(), foldLogOpOfMaskedICmps(), foldLogOpOfMaskedICmpsHelper(), FoldOperationIntoSelectOperand(), llvm::InstCombiner::FoldOrOfFCmps(), FoldReinterpretLoadFromConstPtr(), foldSelectICmpAnd(), foldSelectICmpAndOr(), llvm::InstCombiner::FoldSelectOpOp(), llvm::InstCombiner::FoldShiftByConstant(), FoldTwoEntryPHINode(), foldUDivNegCst(), foldUDivPow2Cst(), foldUDivShl(), llvm::ScalarEvolution::forgetValue(), ftostr(), FunctionNumber(), genLoopLimit(), llvm::gep_type_begin(), llvm::ConstantArray::get(), llvm::ConstantVector::get(), llvm::ConstantExpr::get(), getAccessType(), getAdjustedPtr(), llvm::Constant::getAggregateElement(), getAISize(), llvm::MemIntrinsic::getAlignmentType(), getArrayElements(), llvm::ConstantExpr::getBitCast(), GetCaseResults(), llvm::CastInst::getCastOpcode(), getCodeAddrSpace(), llvm::ConstantExpr::getCompare(), getComparePred(), GetCompareTy(), GetConstantInt(), llvm::SelectionDAG::getConstantPool(), GetConstantPoolSizeInBytes(), llvm::ExecutionEngine::getConstantValue(), llvm::BasicBlock::getContext(), llvm::Function::getContext(), llvm::IRBuilderBase::getCurrentFunctionReturnType(), llvm::Intrinsic::getDeclaration(), llvm::CastInst::getDestTy(), getEdgeValueLocal(), llvm::ConstantAggregateZero::getElementValue(), llvm::UndefValue::getElementValue(), llvm::ConstantExpr::getExtractElement(), llvm::ConstantExpr::getExtractValue(), llvm::ConstantExpr::getFCmp(), llvm::ConstantExpr::getFNeg(), llvm::ConstantExpr::getFPCast(), llvm::ConstantExpr::getFPExtend(), llvm::ConstantExpr::getFPToSI(), llvm::ConstantExpr::getFPToUI(), llvm::ConstantExpr::getFPTrunc(), llvm::objcarc::GetFunctionClass(), llvm::Function::getFunctionType(), getGEPInductionOperand(), llvm::GetElementPtrInst::getGEPReturnType(), llvm::ConstantExpr::getGetElementPtr(), llvm::DenseMapInfo< ComparableFunction >::getHashValue(), llvm::ConstantExpr::getICmp(), llvm::getICmpValue(), llvm::ConstantExpr::getInsertElement(), llvm::ConstantExpr::getInsertValue(), llvm::ConstantExpr::getIntegerCast(), llvm::ConstantExpr::getIntToPtr(), llvm::SCEVExpander::getIVIncOperand(), llvm::TargetLoweringObjectFile::getKindForGlobal(), getKnownConstant(), GetLinearExpression(), llvm::MemoryDependenceAnalysis::getLoadLoadClobberFullWidthSize(), GetLoadValueForLoad(), llvm::AliasAnalysis::getLocation(), getLogBase2Vector(), llvm::getMallocType(), getMaxWeightFor(), getMemCmpLoad(), GetMemInstValueForLoad(), getMemSetPatternValue(), getMergedGlobalExpr(), llvm::AliasAnalysis::getModRefInfo(), getNaturalGEPWithOffset(), llvm::ConstantExpr::getNeg(), llvm::MemoryDependenceAnalysis::getNonLocalPointerDependency(), getNoopInput(), llvm::ConstantExpr::getNot(), getOne(), getOpenCLAlignment(), llvm::MipsTargetLowering::getOpndList(), llvm::getOrEnforceKnownAlignment(), llvm::Argument::getParamAlignment(), llvm::GetPointerBaseWithConstantOffset(), llvm::ConstantExpr::getPointerBitCastOrAddrSpaceCast(), llvm::ConstantExpr::getPointerCast(), llvm::ConstantExpr::getPtrToInt(), llvm::TargetTransformInfo::getReductionCost(), llvm::FastISel::getRegForGEPIndex(), llvm::FastISel::getRegForValue(), GetRegistersForValue(), llvm::ScalarEvolution::getSCEV(), llvm::ConstantExpr::getSelect(), GetSelectFoldableConstant(), llvm::ConstantAggregateZero::getSequentialElement(), llvm::UndefValue::getSequentialElement(), llvm::ConstantExpr::getSExt(), llvm::ConstantExpr::getSExtOrBitCast(), GetShiftedValue(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::ConstantExpr::getShuffleVector(), llvm::ScalarEvolution::getSignedRange(), llvm::SystemZTargetLowering::getSingleConstraintMatchWeight(), llvm::ARMTargetLowering::getSingleConstraintMatchWeight(), llvm::PPCTargetLowering::getSingleConstraintMatchWeight(), llvm::X86TargetLowering::getSingleConstraintMatchWeight(), llvm::TargetLowering::getSingleConstraintMatchWeight(), llvm::ConstantExpr::getSIToFP(), llvm::ConstantVector::getSplat(), llvm::ConstantDataVector::getSplat(), llvm::CastInst::getSrcTy(), llvm::SelectionDAG::getSrcValue(), GetStoreValueForLoad(), llvm::GetStringLength(), llvm::ConstantAggregateZero::getStructElement(), llvm::UndefValue::getStructElement(), llvm::NVPTXTargetLowering::getTgtMemIntrinsic(), llvm::AArch64TargetLowering::getTgtMemIntrinsic(), llvm::ARMTargetLowering::getTgtMemIntrinsic(), llvm::DenseMapInfo< SimpleValue >::getTombstoneKey(), llvm::DenseMapInfo< CallValue >::getTombstoneKey(), llvm::ConstantExpr::getTrunc(), getTruncatedArgReg(), llvm::ConstantExpr::getTruncOrBitCast(), llvm::InlineAsm::getType(), llvm::AllocaInst::getType(), llvm::GlobalValue::getType(), llvm::ConstantInt::getType(), llvm::ConstantArray::getType(), llvm::ConstantStruct::getType(), llvm::ConstantVector::getType(), llvm::ConstantPointerNull::getType(), llvm::ConstantDataSequential::getType(), llvm::ConstantDataArray::getType(), llvm::ConstantDataVector::getType(), llvm::GetElementPtrInst::getType(), llvm::InsertElementInst::getType(), llvm::ShuffleVectorInst::getType(), llvm::ConstantExpr::getUIToFP(), llvm::GetUnderlyingObject(), getUnderlyingObjectFromInt(), getUnderlyingObjects(), llvm::SelectionDAGBuilder::getValue(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::ConstantExpr::getWithOperandReplaced(), llvm::ConstantExpr::getZExt(), llvm::ConstantExpr::getZExtOrBitCast(), llvm::GlobalAlias::GlobalAlias(), llvm::GlobalVariable::GlobalVariable(), GlobalWasGeneratedByAsan(), HandleByValArgument(), hasAddressTakenAndUsed(), llvm::Argument::hasByValAttr(), hasComputableBounds(), llvm::PHINode::hasConstantValue(), llvm::Argument::hasNestAttr(), llvm::Argument::hasNoAliasAttr(), llvm::Argument::hasNoCaptureAttr(), llvm::Argument::hasStructRetAttr(), llvm::SCEVExpander::hoistIVInc(), HoistThenElseCodeToIf(), IdxCompare(), llvm::CompositeType::indexValid(), llvm::BinaryOperator::init(), INITIALIZE_PASS(), llvm::ExecutionEngine::InitializeMemory(), llvm::FunctionLoweringInfo::InitializeRegForValue(), llvm::InlineFunction(), insertFastDiv(), InsertFenceForAtomic(), insertInteger(), insertVector(), InstallGlobalCtors(), InstCombineLoadCast(), InstCombineStoreToCast(), InstructionDereferencesPointer(), llvm::MemoryDependenceAnalysis::invalidateCachedPointerInfo(), isAlwaysFoldable(), isAtomic(), llvm::isBytewiseValue(), llvm::LandingPadInst::isCatch(), isCompatibleAggregate(), isCompatibleIVType(), IsConstantOffsetFromGlobal(), isContiguous(), isEliminableCastPair(), llvm::DenseMapInfo< Expression >::isEqual(), isExistingPhi(), isExitBlock(), llvm::CmpInst::isFalseWhenEqual(), llvm::LandingPadInst::isFilter(), isFormingBranchFromSelectProfitable(), isGEPKnownNonNull(), isHighCostExpansion(), llvm::Instruction::isIdenticalToWhenDefined(), llvm::isImageOrSamplerVal(), llvm::CastInst::isIntegerCast(), isInterestingMemoryAccess(), isInterestingPointer(), llvm::isKnownNonZero(), llvm::isKnownToBeAPowerOfTwo(), isLifetimeStart(), isLikelyComplexAddressComputation(), isLoopInvariant(), llvm::CastInst::isLosslessCast(), llvm::Constant::isNegativeZeroValue(), IsNonLocalValue(), llvm::CastInst::isNoopCast(), IsNullTerminatedString(), llvm::SCEVUnknown::isOffsetOf(), isOnlyReachableViaThisEdge(), isOnlyUsedInEntryBlock(), isOverwrite(), IsPointerOffset(), isPossibleSelfRead(), llvm::objcarc::IsPotentialRetainableObjPtr(), isProfitableChain(), isRepeatedByteSequence(), isRunOfOnes(), isSafeAndProfitableToSinkLoad(), isSafeToEliminateVarargsCast(), llvm::isSafeToLoadUnconditionally(), llvm::isSafeToSpeculativelyExecute(), llvm::Instruction::isSameOperationAs(), isSequentialInRange(), isSimpleEnoughPointerToCommit(), isSimpleEnoughValueToCommitHelper(), isSimpleIVUser(), isSimpleLoadStore(), isStridedPtr(), llvm::ExtractElementInst::isValidOperands(), llvm::InsertElementInst::isValidOperands(), llvm::ShuffleVectorInst::isValidOperands(), isZero(), llvm::FastISel::leaveLocalValueArea(), LinearizeExprTree(), llvm::linkShadowStackGC(), llvm::LoadAndStorePromoter::LoadAndStorePromoter(), LowerBSWAP(), llvm::SelectionDAGBuilder::LowerCallOperands(), llvm::SelectionDAGBuilder::LowerCallTo(), nvptx::LowerConstant(), lowerConstant(), LowerCTLZ(), LowerCTPOP(), llvm::IntrinsicLowering::LowerIntrinsicCall(), LowerNegateToMultiply(), llvm::IntrinsicLowering::LowerToByteSwap(), llvm::MapValue(), MarkBlocksLiveIn(), MarkIndicesSafe(), matchPairwiseReduction(), matchPairwiseReductionAtLevel(), MatchSelectFromAndOr(), matchVectorSplittingReduction(), MergeAliasResults(), llvm::MergeBasicBlockIntoOnlyPred(), mergeEmptyReturnBlocks(), llvm::operator<<(), OptimizeAndOrXor(), OptimizeAwayTrappingUsesOfValue(), OptimizeCmpExpression(), OptimizeGlobalAddressOfMalloc(), OptimizeIntegerToVectorInsertions(), OptimizeIntToFloatBitCast(), OptimizeNoopCopyExpression(), OptimizeOnceStoredGlobal(), OptimizeVectorResize(), llvm::TargetLowering::ParseConstraints(), llvm::BitcodeReader::ParseTriple(), partitionShuffleOfConcats(), patchAndReplaceAllUsesWith(), PerformHeapAllocSRoA(), PHIsEqualValue(), llvm::PHITransAddr::PHITranslateWithInsertion(), PlaceSplitBlockCarefully(), llvm::PointerMayBeCaptured(), PoisonShadowPartialRightRedzone(), llvm::ValueEnumerator::print(), llvm::ARMConstantPoolValue::print(), llvm::AssemblyWriter::printArgument(), llvm::AssemblyWriter::printInstruction(), PrintOps(), ProcessUAddIdiom(), ProcessUGT_ADDCST_ADD(), llvm::MDNode::Profile(), promoteSingleBlockAlloca(), PushDefUseChildren(), PushValueAndType(), ReadDataFromGlobal(), reduceToSingleValueType(), llvm::RemapInstruction(), llvm::AliasSetTracker::remove(), llvm::SwitchInst::removeCase(), RemoveDeadConstant(), removeFinishedSplitUses(), llvm::MemoryDependenceAnalysis::removeInstruction(), removeLifetimeIntrinsicUsers(), replaceAllUsesWith(), llvm::SCEVExpander::replaceCongruentIVs(), ReplaceFPIntrinsicWithCall(), llvm::InstCombiner::ReplaceInstUsesWith(), llvm::MDNode::replaceOperandWith(), ReplaceUsesOfWith(), llvm::returnTypeIsEligibleForTailCall(), RewriteHeapSROALoadUser(), rewriteSingleStoreAlloca(), RewriteUsesOfClonedInstructions(), llvm::TypeFinder::run(), llvm::LLParser::Run(), llvm::Interpreter::run(), llvm::LoadAndStorePromoter::run(), llvm::JIT::runFunction(), llvm::NVPTXLowerAggrCopies::runOnFunction(), llvm::FindUsedTypes::runOnModule(), llvm::FastISel::SelectOperator(), llvm::FunctionLoweringInfo::set(), llvm::GlobalAlias::setAliasee(), llvm::LoadInst::setAlignment(), llvm::StoreInst::setAlignment(), llvm::MemIntrinsic::setDest(), llvm::GlobalVariable::setInitializer(), llvm::MemIntrinsic::setLength(), setName(), llvm::MemTransferInst::setSource(), llvm::MemSetInst::setValue(), shorter_filter(), shouldMergeGEPs(), ShrinkDemandedConstant(), SimplifyAddInst(), SimplifyAndInst(), SimplifyAShrInst(), SimplifyBinOp(), SimplifyBranchOnICmpChain(), SimplifyCall(), SimplifyDiv(), SimplifyFAddInst(), SimplifyFSubInst(), SimplifyICmpInst(), SimplifyInsertValueInst(), llvm::SimplifyInstruction(), SimplifyLShrInst(), SimplifyMulInst(), SimplifyOrInst(), SimplifyPHINode(), SimplifyRem(), SimplifyShift(), SimplifyShlInst(), SimplifySubInst(), SimplifyWithOpReplaced(), SimplifyXorInst(), SinkThenElseCodeToEnd(), AllocaSlices::SliceBuilder::SliceBuilder(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), speculatePHINodeLoads(), SplitAddRecs(), llvm::SplitLandingPadPredecessors(), stripAndAccumulateInBoundsConstantOffsets(), stripAndComputeConstantOffsets(), StripPtrCastKeepAS(), SubOne(), SubWithOverflow(), swapMayExposeCSEOpportunities(), SwitchToLookupTable(), SymbolicallyEvaluateBinop(), SymbolicallyEvaluateGEP(), ThreadCmpOverSelect(), tryToMakeAllocaBePromotable(), TryToOptimizeStoreOfMallocToGlobal(), TryToShrinkGlobalToBoolean(), TurnSwitchRangeIntoICmp(), underlyingObjectsAlias(), llvm::UnreachableInst::UnreachableInst(), llvm::UnrollRuntimeLoopProlog(), UpdatePHINodes(), llvm::SelectionDAGBuilder::UpdateSplitBlock(), llvm::UpgradeBitCastExpr(), llvm::UpgradeBitCastInst(), llvm::UpgradeIntrinsicCall(), llvm::ValueHandleBase::ValueIsDeleted(), llvm::ValueHandleBase::ValueIsRAUWd(), llvm::InstCombiner::visitAdd(), llvm::Interpreter::visitAllocaInst(), llvm::InstCombiner::visitAllocaInst(), llvm::InstCombiner::visitAllocSite(), llvm::InstCombiner::visitAnd(), llvm::ObjectSizeOffsetVisitor::visitArgument(), llvm::InstCombiner::visitAShr(), llvm::Interpreter::visitAShr(), llvm::Interpreter::visitBinaryOperator(), llvm::InstCombiner::visitBitCast(), llvm::Interpreter::visitBitCastInst(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::InstCombiner::visitCallInst(), llvm::Interpreter::visitExtractElementInst(), llvm::InstCombiner::visitExtractElementInst(), llvm::Interpreter::visitExtractValueInst(), llvm::InstCombiner::visitFAdd(), llvm::Interpreter::visitFCmpInst(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitFMul(), llvm::Interpreter::visitFPExtInst(), llvm::InstCombiner::visitFPToSI(), llvm::Interpreter::visitFPToSIInst(), llvm::InstCombiner::visitFPToUI(), llvm::Interpreter::visitFPToUIInst(), llvm::InstCombiner::visitFPTrunc(), llvm::Interpreter::visitFPTruncInst(), llvm::InstCombiner::visitFSub(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::Interpreter::visitICmpInst(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithCastAndCast(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitInsertElementInst(), llvm::Interpreter::visitInsertValueInst(), llvm::InstCombiner::visitIntToPtr(), llvm::Interpreter::visitIntToPtrInst(), llvm::InstCombiner::visitLandingPadInst(), llvm::Interpreter::visitLoadInst(), llvm::InstCombiner::visitLoadInst(), llvm::InstCombiner::visitLShr(), llvm::Interpreter::visitLShr(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitPHINode(), llvm::PtrUseVisitor< SliceBuilder >::visitPtr(), llvm::InstCombiner::visitPtrToInt(), llvm::Interpreter::visitPtrToIntInst(), llvm::Interpreter::visitReturnInst(), llvm::InstCombiner::visitSDiv(), llvm::Interpreter::visitSelectInst(), llvm::InstCombiner::visitSelectInst(), llvm::InstCombiner::visitSelectInstWithICmp(), llvm::InstCombiner::visitSExt(), llvm::Interpreter::visitSExtInst(), llvm::Interpreter::visitShl(), llvm::InstCombiner::visitShuffleVectorInst(), llvm::Interpreter::visitSIToFPInst(), llvm::SelectionDAGBuilder::visitSPDescriptorParent(), llvm::InstCombiner::visitSRem(), llvm::Interpreter::visitStoreInst(), llvm::InstCombiner::visitStoreInst(), llvm::InstCombiner::visitSub(), llvm::Interpreter::visitSwitchInst(), llvm::InstCombiner::visitTrunc(), llvm::Interpreter::visitTruncInst(), llvm::InstCombiner::visitUDiv(), llvm::Interpreter::visitUIToFPInst(), llvm::InstCombiner::visitURem(), llvm::Interpreter::visitVAArgInst(), llvm::InstCombiner::visitXor(), llvm::InstCombiner::visitZExt(), llvm::Interpreter::visitZExtInst(), width_descending(), llvm::WriteAsOperand(), llvm::WriteConstantInternal(), WriteConstants(), WriteInstruction(), WriteMDNode(), llvm::AssemblyWriter::writeOperand(), llvm::AssemblyWriter::writeParamOperand(), X86ChooseCmpImmediateOpcode(), llvm::BasicBlock::~BasicBlock(), and llvm::CallInst::~CallInst().
unsigned llvm::Value::getValueID () const inline
getValueID - Return an ID for the concrete type of this object. This is used to implement the classof checks. This should not be used for any other purpose, as the values may change as LLVM evolves. Also, note that for instructions, the Instruction's opcode is added to InstructionVal. So this means three things:
there is no value with code InstructionVal (no opcode==0).
there are more possible values for the value type than in ValueTy enum.
the InstructionVal enumerator must be the highest valued enumerator in
the ValueTy enum.
Definition at line 233 of file Value.h.
Referenced by llvm::PseudoSourceValue::classof(), llvm::MDString::classof(), llvm::GlobalAlias::classof(), llvm::FixedStackPseudoSourceValue::classof(), llvm::Argument::classof(), llvm::Constant::classof(), llvm::MDNode::classof(), llvm::InlineAsm::classof(), llvm::GlobalVariable::classof(), llvm::ConstantInt::classof(), llvm::BasicBlock::classof(), llvm::ConstantFP::classof(), llvm::GlobalValue::classof(), llvm::ConstantAggregateZero::classof(), llvm::ConstantArray::classof(), llvm::Instruction::classof(), llvm::ConstantStruct::classof(), llvm::Function::classof(), llvm::ConstantVector::classof(), llvm::ConstantPointerNull::classof(), llvm::ConstantDataSequential::classof(), llvm::ConstantDataArray::classof(), llvm::ConstantDataVector::classof(), llvm::BlockAddress::classof(), llvm::ConstantExpr::classof(), llvm::UndefValue::classof(), llvm::isa_impl< Constant, Value >::doit(), llvm::isa_impl< Argument, Value >::doit(), llvm::isa_impl< InlineAsm, Value >::doit(), llvm::isa_impl< Instruction, Value >::doit(), llvm::isa_impl< BasicBlock, Value >::doit(), llvm::isa_impl< Function, Value >::doit(), llvm::isa_impl< GlobalVariable, Value >::doit(), llvm::isa_impl< GlobalAlias, Value >::doit(), llvm::isa_impl< MDNode, Value >::doit(), llvm::DenseMapInfo< ComparableFunction >::getHashValue(), llvm::Instruction::getOpcode(), and llvm::WriteAsOperandInternal().
ValueName* llvm::Value::getValueName () const inline
Definition at line 118 of file Value.h.
Referenced by llvm::TargetIntrinsicInfo::getIntrinsicID(), llvm::Function::getIntrinsicID(), and llvm::Function::~Function().
bool llvm::Value::hasName () const inline
Definition at line 117 of file Value.h.
References MDStringVal.
Referenced by llvm::canConstantFoldCallTo(), llvm::CloneBasicBlock(), llvm::CloneFunction(), llvm::ConstantFoldCall(), llvm::createPPCCTRLoopsVerify(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::ExecutionEngine::emitGlobals(), FoldBlockIntoPredecessor(), ftostr(), FunctionNumber(), llvm::Mangler::getNameWithPrefix(), llvm::TargetTransformInfo::getReductionCost(), llvm::getSamplerName(), llvm::getSurfaceName(), llvm::getTextureName(), isContiguous(), llvm::MergeBlockIntoPredecessor(), llvm::ValueEnumerator::print(), llvm::SparseSolver::Print(), llvm::AssemblyWriter::printAlias(), llvm::AssemblyWriter::printArgument(), llvm::AssemblyWriter::printBasicBlock(), llvm::AssemblyWriter::printInstruction(), RemoveNestAttribute(), llvm::ReplaceInstWithValue(), llvm::FastISel::SelectInstruction(), setName(), takeName(), llvm::WriteAsOperand(), and llvm::ValueSymbolTable::~ValueSymbolTable().
bool Value::hasNUses (unsigned N) const
hasNUses - Return true if this Value has exactly N users.
Definition at line 92 of file Value.cpp.
References N, use_begin(), and use_end().
Referenced by FindScalarElement(), hasOneUse(), and WriteUseList().
bool Value::hasNUsesOrMore (unsigned N) const
hasNUsesOrMore - Return true if this value has N users or more. This is logically equivalent to getNumUses() >= N.
Definition at line 103 of file Value.cpp.
References N, use_begin(), and use_end().
Referenced by hasMoreThanOneUseOtherThanLLVMUsed(), hasOneUse(), llvm::BasicBlock::removePredecessor(), replaceConstantExprOp(), and SRAGlobal().
bool llvm::Value::hasOneUse () const inline
hasOneUse - Return true if there is exactly one user of this value. This is specialized because it is a common request and does not require traversing the whole use list.
Definition at line 161 of file Value.h.
References BB, getNumUses(), hasNUses(), hasNUsesOrMore(), I, isUsedInBasicBlock(), N, use_begin(), and use_end().
Referenced by AddPHINodeEntriesForMappedBlock(), areAllUsesIn(), buildMultiplyTree(), CanEvaluateSExtd(), CanEvaluateShifted(), CanEvaluateShuffled(), CanEvaluateTruncated(), CanEvaluateZExtd(), CheapToScalarize(), ClearSubclassDataAfterReassociation(), collectFailStats(), CollectInsertionElements(), computeBytesPoppedByCallee(), ConvertToSInt(), DeadPHICycle(), DecomposeSimpleLinearExpr(), detectLog2OfHalf(), llvm::InstCombiner::DoOneIteration(), dyn_castFoldableMul(), FindInitTrampolineFromAlloca(), llvm::SelectionDAGBuilder::FindMergedConditions(), FindScalarElement(), FindSingleUseIdentifiedObject(), llvm::InstCombiner::FoldAndOfICmps(), llvm::FoldBranchToCommonDest(), FoldCondBranchOnPHI(), llvm::InstCombiner::foldFMulConst(), llvm::InstCombiner::FoldGEPICmp(), llvm::InstCombiner::FoldICmpShrCst(), FoldOperationIntoSelectOperand(), llvm::InstCombiner::FoldOrOfICmps(), llvm::InstCombiner::FoldShiftByConstant(), getCommonReturnValue(), getComparePred(), getFCmpValue(), hasUseOtherThanLLVMUsed(), hasUsesOutsideLoop(), isAlwaysFoldable(), isFormingBranchFromSelectProfitable(), IsNonLocalValue(), isOnlyReachableViaThisEdge(), isReassociableOp(), isSafeAndProfitableToSinkLoad(), IsSafeComputationToRemove(), LinearizeExprTree(), llvm::FastISel::LowerArguments(), MarkBlocksLiveIn(), OptimizeCmpExpression(), ProcessUGT_ADDCST_ADD(), RightDistributesOverLeft(), ShouldBreakUpSubtract(), shouldMergeGEPs(), ShrinkDemandedConstant(), llvm::InstCombiner::SimplifyDivRemOfSelect(), simplifyValueKnownNonZero(), SinkThenElseCodeToEnd(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), llvm::FastISel::tryToFoldLoad(), TryToSimplifyUncondBranchWithICmpInIt(), TryToSinkInstruction(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitAnd(), llvm::InstCombiner::visitBranchInst(), llvm::InstCombiner::visitExtractElementInst(), llvm::InstCombiner::visitFDiv(), llvm::InstCombiner::visitFMul(), llvm::InstCombiner::visitFPTrunc(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitInsertElementInst(), llvm::InstCombiner::visitLoadInst(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitPHINode(), llvm::InstCombiner::visitSelectInstWithICmp(), llvm::InstCombiner::visitSExt(), llvm::InstCombiner::visitStoreInst(), llvm::InstCombiner::visitTrunc(), llvm::InstCombiner::visitXor(), llvm::InstCombiner::visitZExt(), and X86ChooseCmpImmediateOpcode().
bool llvm::Value::hasSameSubclassOptionalData (const Value * V) const inline
hasSameSubclassOptionalData - Test whether the optional flags contained in this value are equal to the optional flags in the given value.
Definition at line 252 of file Value.h.
References SubclassOptionalData.
Referenced by llvm::DenseMapInfo< ComparableFunction >::getHashValue().
bool llvm::Value::hasValueHandle () const inline
hasValueHandle - Return true if there is a value handle associated with this value.
Definition at line 264 of file Value.h.
References stripPointerCasts().
void llvm::Value::intersectOptionalDataWith (const Value * V) inline
intersectOptionalDataWith - Clear any optional flags in this value that are not also set in the given value.
Definition at line 258 of file Value.h.
References SubclassOptionalData.
Referenced by HoistThenElseCodeToIf(), and SinkThenElseCodeToEnd().
bool Value::isDereferenceablePointer () const
isDereferenceablePointer - Test if this value is always a pointer to allocated and suitably aligned memory for a simple load or store.
Definition at line 500 of file Value.cpp.
References isDereferenceablePointer().
Referenced by AllCallersPassInValidPointerForArgument(), isDereferenceablePointer(), isSafePHIToSpeculate(), isSafeSelectToSpeculate(), llvm::isSafeToSpeculativelyExecute(), and stripInBoundsOffsets().
bool Value::isUsedInBasicBlock (const BasicBlock * BB) const
isUsedInBasicBlock - Return true if this value is used in the specified basic block.
Definition at line 114 of file Value.cpp.
References BB, llvm::BasicBlock::begin(), llvm::dyn_cast(), llvm::BasicBlock::end(), llvm::Instruction::getParent(), use_begin(), and use_end().
Referenced by hasOneUse(), and OptimizeCmpExpression().
void llvm::Value::mutateType (Type * Ty) inline
mutateType - Mutate the type of this Value to be of the specified type. Note that this is an extremely dangerous operation which can create completely invalid IR very easily. It is strongly recommended that you recreate IR objects with the right types instead of mutating them in place.
Definition at line 342 of file Value.h.
Referenced by llvm::RemapInstruction().
void Value::print (raw_ostream & O, AssemblyAnnotationWriter * AAW = 0) const
print - Implement operator<< on Value.
Definition at line 2162 of file AsmWriter.cpp.
References BB, F(), llvm::MDNode::getFunction(), getModuleFromVal(), llvm::GlobalValue::getParent(), llvm::TypePrinting::print(), llvm::AssemblyWriter::printGlobal(), llvm::AssemblyWriter::printInstruction(), llvm::AssemblyWriter::printMDNodeBody(), llvm::WriteAsOperand(), and llvm::WriteConstantInternal().
Referenced by llvm::createMemDepPrinter(), llvm::InstCombiner::DoOneIteration(), llvm::NamedMDNode::getParent(), llvm::operator<<(), llvm::AliasSetTracker::print(), and llvm::WriteAsOperandInternal().
void Value::printCustom (raw_ostream & O) const protected virtual
printCustom - Value subclasses can override this to implement custom printing behavior.
Reimplemented in llvm::FixedStackPseudoSourceValue.
Definition at line 2207 of file AsmWriter.cpp.
References llvm_unreachable.
void Value::replaceAllUsesWith (Value * V)
replaceAllUsesWith - Go through the uses list for this definition and make each use point to "V" instead of "this". After this completes, 'this's use list is guaranteed to be empty.
Definition at line 303 of file Value.cpp.
References BB, getType(), llvm::Use::getUser(), llvm::Use::set(), use_empty(), and llvm::ValueHandleBase::ValueIsRAUWd().
Referenced by AddReachableCodeToWorklist(), AddressIsTaken(), BreakUpSubtract(), buildMultiplyTree(), CanTRE(), changeToCall(), checkCSEInPredecessor(), checkInterfaceFunction(), llvm::CloneAndPruneFunctionInto(), CloneLoop(), CommitValueTo(), ComputePostOrders(), ConvertShiftToMul(), ConvertToSInt(), createCast(), llvm::createCodeGenPreparePass(), llvm::createConstantPropagationPass(), llvm::createCorrelatedValuePropagationPass(), llvm::createDeadArgHackingPass(), llvm::createEarlyCSEPass(), llvm::createLICMPass(), llvm::createLoopInstSimplifyPass(), llvm::createLoopSimplifyPass(), llvm::createNVVMReflectPass(), llvm::createObjCARCContractPass(), llvm::createObjCARCOptPass(), cse(), cxxDtorIsEmpty(), llvm::DeleteDeadBlock(), deleteIfDeadInstruction(), DeleteInstructionInBlock(), llvm::DemotePHIToStack(), llvm::InstCombiner::DoOneIteration(), llvm::EliminateDuplicatePHINodes(), llvm::objcarc::EraseInstruction(), llvm::expandDivision(), llvm::expandDivisionUpTo32Bits(), llvm::expandRemainder(), llvm::expandRemainderUpTo32Bits(), FindMostPopularDest(), FindPHIToPartitionLoops(), FirstNonDbg(), FoldBlockIntoPredecessor(), FoldTwoEntryPHINode(), GetLoadValueForLoad(), HandleCallsInBlockInlinedThroughInvoke(), hasAddressTakenAndUsed(), HoistThenElseCodeToIf(), INITIALIZE_PASS(), INITIALIZE_PASS_BEGIN(), InlineCallIfPossible(), llvm::InlineFunction(), insertFastDiv(), insertVector(), InstallGlobalCtors(), isAlwaysFoldable(), isCompatibleAggregate(), isFormingBranchFromSelectProfitable(), isLessConstraining(), isLifetimeStart(), isOnlyReachableViaThisEdge(), llvm::linkShadowStackGC(), LowerAtomicCmpXchgInst(), LowerAtomicRMWInst(), llvm::IntrinsicLowering::LowerIntrinsicCall(), LowerNegateToMultiply(), llvm::IntrinsicLowering::LowerToByteSwap(), llvm::MapValue(), MarkBlocksLiveIn(), MarkIndicesSafe(), llvm::MergeBasicBlockIntoOnlyPred(), llvm::MergeBlockIntoPredecessor(), mergeEmptyReturnBlocks(), OptimizeGlobalAddressOfMalloc(), llvm::BitcodeReader::ParseTriple(), patchAndReplaceAllUsesWith(), llvm::MDNode::Profile(), promoteSingleBlockAlloca(), removeFinishedSplitUses(), llvm::BasicBlock::removePredecessor(), llvm::LibCallSimplifier::replaceAllUsesWith(), llvm::DIType::replaceAllUsesWith(), replaceAndRecursivelySimplifyImpl(), ReplaceCallWith(), llvm::SCEVExpander::replaceCongruentIVs(), llvm::InstCombiner::ReplaceInstUsesWith(), llvm::ReplaceInstWithValue(), ReplaceUsesOfWith(), llvm::ConstantArray::replaceUsesOfWithOnConstant(), llvm::ConstantStruct::replaceUsesOfWithOnConstant(), llvm::ConstantVector::replaceUsesOfWithOnConstant(), llvm::BlockAddress::replaceUsesOfWithOnConstant(), llvm::ConstantExpr::replaceUsesOfWithOnConstant(), llvm::BitcodeReaderValueList::ResolveConstantForwardRefs(), RewriteHeapSROALoadUser(), rewriteSingleStoreAlloca(), llvm::LLParser::Run(), llvm::LoadAndStorePromoter::run(), setValueName(), SimplifyBranchOnICmpChain(), speculatePHINodeLoads(), speculateSelectInstLoads(), llvm::SplitLandingPadPredecessors(), SRAGlobal(), StackMallocSizeClass(), tryToMakeAllocaBePromotable(), TryToOptimizeStoreOfMallocToGlobal(), TryToShrinkGlobalToBoolean(), llvm::TryToSimplifyUncondBranchFromEmptyBlock(), TryToSimplifyUncondBranchWithICmpInIt(), llvm::UnrollLoop(), llvm::UpgradeIntrinsicCall(), llvm::ObjectSizeOffsetEvaluator::visitPHINode(), and llvm::BasicBlock::~BasicBlock().
void Value::setName (const Twine & Name)
setName() - Change the name of the value, choosing a new unique name if the provided name is taken.
Parameters
Name The new name; or "" if the value's name should be removed.
Definition at line 175 of file Value.cpp.
References llvm::StringRef::begin(), llvm::StringMapEntry< ValueTy >::Create(), llvm::StringMapEntry< ValueTy >::Destroy(), llvm::StringRef::empty(), llvm::StringRef::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::erase(), F(), getContext(), getName(), getSymTab(), getType(), hasName(), llvm::LLVMContextImpl::IntrinsicIDCache, llvm::Twine::isTriviallyEmpty(), MDStringVal, llvm::LLVMContext::pImpl, llvm::StringMapEntry< ValueTy >::setValue(), llvm::A64DB::ST, and llvm::Twine::toStringRef().
Referenced by llvm::GetElementPtrInst::accumulateConstantOffset(), AddPHINodeEntriesForMappedBlock(), llvm::AllocaInst::AllocaInst(), llvm::Argument::Argument(), llvm::BinaryOperator::BinaryOperator(), llvm::CastInst::CastInst(), checkInterfaceFunction(), llvm::CloneBasicBlock(), llvm::CloneFunction(), llvm::CmpInst::CmpInst(), llvm::IRBuilderBase::CreateGlobalString(), llvm::createLICMPass(), llvm::createLoopVectorizePass(), createPrivateNonConstGlobalForString(), llvm::FenceInst::FenceInst(), FindInitTrampoline(), FirstNonDbg(), FoldBlockIntoPredecessor(), llvm::FoldBranchToCommonDest(), FoldCondBranchOnPHI(), forceRenaming(), FunctionNumber(), generateUnsignedDivisionCode(), GetAttrFromCode(), llvm::BasicBlock::getContext(), getFunctionName(), getGEPInductionOperand(), llvm::Module::getOrInsertFunction(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::GlobalValue::GlobalValue(), INITIALIZE_PASS(), llvm::IRBuilderDefaultInserter< true >::InsertHelper(), isAlwaysFoldable(), isOnlyReachableViaThisEdge(), llvm::ExtractElementInst::isValidOperands(), llvm::LoadInst::LoadInst(), llvm::IntrinsicLowering::LowerIntrinsicCall(), MarkIndicesSafe(), NegateValue(), ReplaceCallWith(), setValueName(), shouldSpeculateInstrs(), llvm::ShuffleVectorInst::ShuffleVectorInst(), llvm::SplitLandingPadPredecessors(), StripSymtab(), takeName(), llvm::UpgradeIntrinsicCall(), UpgradeIntrinsicFunction1(), UpgradeSSE41Function(), and llvm::VAArgInst::VAArgInst().
void llvm::Value::setValueName (ValueName * VN) inline
Definition at line 119 of file Value.h.
References getName(), replaceAllUsesWith(), setName(), and takeName().
Referenced by llvm::MDString::get().
void llvm::Value::setValueSubclassData (unsigned short D) inline protected
Definition at line 348 of file Value.h.
Referenced by llvm::MDNode::classof(), llvm::Function::classof(), llvm::ConstantExpr::classof(), llvm::ConstantExpr::ConstantExpr(), llvm::Function::eraseFromParent(), llvm::MDNode::getFunction(), llvm::BasicBlock::hasAddressTaken(), llvm::CmpInst::makeCmpResultType(), llvm::MDNode::Profile(), llvm::MDNode::replaceOperandWith(), llvm::Function::setPrefixData(), and llvm::Function::~Function().
Value * Value::stripAndAccumulateInBoundsConstantOffsets (const DataLayout & DL, APInt & Offset)
Strips like stripInBoundsConstantOffsets but also accumulates the constant offset stripped.
Stores the resulting constant offset stripped into the APInt provided. The provided APInt will be extended or truncated as needed to be the correct bitwidth for an offset of this pointer type.
If this is called on a non-pointer value, it returns 'this'.
Definition at line 397 of file Value.cpp.
References llvm::APInt::getBitWidth(), llvm::Operator::getOpcode(), llvm::DataLayout::getPointerSizeInBits(), getType(), llvm::SmallPtrSet< PtrType, SmallSize >::insert(), and llvm::Type::isPointerTy().
Referenced by stripAndAccumulateInBoundsConstantOffsets(), and stripInBoundsConstantOffsets().
const Value* llvm::Value::stripAndAccumulateInBoundsConstantOffsets (const DataLayout & DL, APInt & Offset) const inline
Definition at line 303 of file Value.h.
References stripAndAccumulateInBoundsConstantOffsets(), and stripInBoundsOffsets().
Value * Value::stripInBoundsConstantOffsets ()
Strips off unneeded pointer casts and all-constant GEPs from the specified value, returning the original pointer value.
If this is called on a non-pointer value, it returns 'this'.
Definition at line 393 of file Value.cpp.
Referenced by stripInBoundsConstantOffsets(), and stripPointerCastsNoFollowAliases().
const Value* llvm::Value::stripInBoundsConstantOffsets () const inline
Definition at line 289 of file Value.h.
References stripAndAccumulateInBoundsConstantOffsets(), and stripInBoundsConstantOffsets().
Value * Value::stripInBoundsOffsets ()
Strips off unneeded pointer casts and any in-bounds offsets from the specified value, returning the original pointer value.
If this is called on a non-pointer value, it returns 'this'.
Definition at line 433 of file Value.cpp.
Referenced by insertVector(), stripAndAccumulateInBoundsConstantOffsets(), and stripInBoundsOffsets().
const Value* llvm::Value::stripInBoundsOffsets () const inline
Definition at line 314 of file Value.h.
References DoPHITranslation(), isDereferenceablePointer(), and stripInBoundsOffsets().
Value * Value::stripPointerCasts ()
Strips off any unneeded pointer casts, all-zero GEPs and aliases from the specified value, returning the original uncasted value.
If this is called on a non-pointer value, it returns 'this'.
Definition at line 385 of file Value.cpp.
Referenced by llvm::AddLandingPadInfo(), llvm::MachineModuleInfo::AnalyzeModule(), CommitValueTo(), llvm::ObjectSizeOffsetVisitor::compute(), llvm::ObjectSizeOffsetEvaluator::compute(), computePointerICmp(), cxxDtorIsEmpty(), llvm::EmitFPutS(), llvm::EmitFWrite(), llvm::EmitMemChr(), llvm::EmitMemCmp(), llvm::EmitMemCpyChk(), llvm::EmitPutChar(), llvm::AsmPrinter::EmitSpecialLLVMGlobal(), llvm::EmitStrChr(), llvm::EmitStrCpy(), llvm::EmitStrLen(), llvm::EmitStrNCmp(), llvm::EmitStrNCpy(), llvm::EmitStrNLen(), llvm::EmitUnaryFloatFnCall(), llvm::ARMAsmPrinter::EmitXXStructor(), enforceKnownAlignment(), llvm::ExtractTypeInfo(), FindInitTrampoline(), FindInitTrampolineFromAlloca(), findUsedValues(), llvm::InstCombiner::FoldGEPICmp(), getCalledFunction(), llvm::getConstantStringInfo(), llvm::MemIntrinsic::getDest(), getKnownConstant(), getOpenCLAlignment(), llvm::MemTransferInst::getSource(), GetStringLengthH(), getTruncatedArgReg(), hasAddressTakenAndUsed(), hasNoAliasAttr(), hasUsesToReplace(), hasValueHandle(), INITIALIZE_PASS(), isCompatibleAggregate(), isContiguous(), isOverwrite(), IsPointerOffset(), isZero(), MergeAliasResults(), OptimizeOnceStoredGlobal(), RecognizePersonality(), reduceToSingleValueType(), llvm::BlockAddress::replaceUsesOfWithOnConstant(), llvm::skipPointerTransfer(), stripPointerCasts(), llvm::objcarc::StripPointerCastsAndObjCCalls(), llvm::InstCombiner::visitGetElementPtrInst(), and llvm::InstCombiner::visitLandingPadInst().
const Value* llvm::Value::stripPointerCasts () const inline
Definition at line 271 of file Value.h.
References stripPointerCasts(), and stripPointerCastsNoFollowAliases().
Value * Value::stripPointerCastsNoFollowAliases ()
Strips off any unneeded pointer casts and all-zero GEPs from the specified value, returning the original uncasted value.
If this is called on a non-pointer value, it returns 'this'.
Definition at line 389 of file Value.cpp.
Referenced by llvm::collectUsedGlobalVariables(), FindUsedValues(), stripPointerCasts(), and stripPointerCastsNoFollowAliases().
const Value* llvm::Value::stripPointerCastsNoFollowAliases () const inline
Definition at line 280 of file Value.h.
References stripInBoundsConstantOffsets(), and stripPointerCastsNoFollowAliases().
void Value::takeName (Value * V)
takeName - transfer the name from V to this value, setting V's name to empty. It is an error to call V->takeName(V).
Definition at line 239 of file Value.cpp.
References llvm::StringMapEntry< ValueTy >::Destroy(), getSymTab(), hasName(), MDStringVal, setName(), llvm::StringMapEntry< ValueTy >::setValue(), and llvm::A64DB::ST.
Referenced by checkInterfaceFunction(), ClearSubclassDataAfterReassociation(), llvm::InstCombiner::commonPointerCastTransforms(), ConvertShiftToMul(), ConvertToSInt(), createCast(), llvm::createDeadArgHackingPass(), DecomposeSimpleLinearExpr(), FindInitTrampoline(), FirstNonDbg(), llvm::FoldBranchToCommonDest(), FoldOperationIntoSelectOperand(), llvm::InstCombiner::FoldSelectIntoOp(), llvm::InstCombiner::FoldShiftByConstant(), FoldTwoEntryPHINode(), forceRenaming(), getFCmpValue(), GetLoadValueForLoad(), GetShiftedValue(), hasAddressTakenAndUsed(), hasUsesToReplace(), HoistThenElseCodeToIf(), INITIALIZE_PASS(), INITIALIZE_PASS_BEGIN(), InstallGlobalCtors(), isCompatibleAggregate(), isFormingBranchFromSelectProfitable(), isLifetimeStart(), isZeroLengthArray(), llvm::linkShadowStackGC(), MarkIndicesSafe(), llvm::MergeBlockIntoPredecessor(), NumRetVals(), llvm::ReplaceInstWithValue(), RightDistributesOverLeft(), setUsedInitializer(), setValueName(), ShrinkDemandedConstant(), tryToMakeAllocaBePromotable(), TryToShrinkGlobalToBoolean(), llvm::InstCombiner::visitCallInst(), llvm::InstCombiner::visitFMul(), llvm::InstCombiner::visitGetElementPtrInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitTrunc(), and llvm::InstCombiner::visitXor().
User* llvm::Value::use_back () inline
Definition at line 154 of file Value.h.
References use_begin().
Referenced by AddressIsTaken(), llvm::Constant::destroyConstantImpl(), MarkIndicesSafe(), NumRetVals(), OptimizeGlobalAddressOfMalloc(), removeDeadUsersOfConstant(), SRAGlobal(), StripSymbolNames(), TryToShrinkGlobalToBoolean(), and llvm::BasicBlock::~BasicBlock().
const User* llvm::Value::use_back () const inline
Definition at line 155 of file Value.h.
References use_begin().
use_iterator llvm::Value::use_begin () inline
Definition at line 150 of file Value.h.
Referenced by AddressIsTaken(), llvm::IVUsers::AddUsersImpl(), llvm::InstCombineWorklist::AddUsersToWorkList(), AllCallersPassInValidPointerForArgument(), AllGlobalLoadUsesSimpleEnoughForHeapSRA(), AllUsesOfLoadedValueWillTrapIfNull(), AllUsesOfValueWillTrapIfNull(), AlmostDeadIV(), analyzeGlobalAux(), areAllUsesEqual(), areAllUsesIn(), canFoldIVIncExpr(), ChangeCalleesToFastCall(), llvm::GraphTraits< const Value * >::child_begin(), llvm::GraphTraits< Value * >::child_begin(), CleanupConstantGlobalUsers(), CleanupPointerRootUsers(), ConstantPropUsersOf(), ConvertToSInt(), llvm::createArgumentPromotionPass(), createCast(), llvm::createConstantPropagationPass(), llvm::createDeadArgHackingPass(), llvm::createGlobalsModRefPass(), llvm::createLICMPass(), llvm::createLoopInstSimplifyPass(), llvm::createMergeFunctionsPass(), llvm::createObjCARCContractPass(), llvm::createObjCARCOptPass(), llvm::createSinkingPass(), cxxDtorIsEmpty(), deleteIfDeadInstruction(), llvm::SCEVAddRecExpr::delinearize(), determinePointerReadAttrs(), llvm::InstCombiner::DoOneIteration(), llvm::detail::PtrUseVisitorBase::enqueueUsers(), enqueueUsersInWorklist(), FindInitTrampolineFromAlloca(), llvm::CodeExtractor::findInputsOutputs(), FindPhiPredForUseInBlock(), FindScalarElement(), FindSingleUseIdentifiedObject(), llvm::FoldBranchToCommonDest(), FoldOperationIntoSelectOperand(), llvm::Inliner::getInlineThreshold(), llvm::getMallocType(), getNumUses(), GlobalUsersSafeToSRA(), llvm::Function::hasAddressTaken(), hasLifetimeMarkers(), hasNUses(), hasNUsesOrMore(), hasOneUse(), hasOutsideLoopUser(), hasUsesOutsideLoop(), INITIALIZE_PASS(), insertVector(), llvm::isAllocaPromotable(), isAllocSiteRemovable(), isCompatibleAggregate(), llvm::Constant::isConstantUsed(), isContiguous(), llvm::Function::isDefTriviallyDead(), isExitBlock(), isHighCostExpansion(), isLoopInvariant(), IsNonLocalValue(), isOnlyCopiedFromConstantGlobal(), isOnlyUsedInEntryBlock(), IsOnlyUsedInZeroEqualityComparison(), isProfitableChain(), isSafePHIToSpeculate(), isSafeSelectToSpeculate(), isSafeSROAElementUse(), llvm::isSafeToDestroyConstant(), isSimpleLoadStore(), IsStoredObjCPointer(), isUsedByLifetimeMarker(), isUsedInBasicBlock(), llvm::Instruction::isUsedOutsideOfBlock(), isUsedOutsideOfDefiningBlock(), IsUserOfGlobalSafeForSRA(), isZeroLengthArray(), LinearizeExprTree(), LLVMGetFirstUse(), LoadUsesSimpleEnoughForHeapSRA(), llvm::FastISel::LowerArguments(), llvm::LowerDbgDeclare(), MarkBlocksLiveIn(), MarkIndicesSafe(), NegateValue(), NumRetVals(), OnlyUsedBy(), llvm::onlyUsedByLifetimeMarkers(), OptimizeAwayTrappingUsesOfLoads(), OptimizeAwayTrappingUsesOfValue(), OptimizeCmpExpression(), OptimizeGlobalAddressOfMalloc(), OptimizeNoopCopyExpression(), passingValueIsAlwaysUndefined(), patchAndReplaceAllUsesWith(), PerformHeapAllocSRoA(), llvm::PointerMayBeCaptured(), llvm::ValueEnumerator::print(), ProcessUGT_ADDCST_ADD(), promoteSingleBlockAlloca(), PushDefUseChildren(), pushIVUsers(), llvm::Constant::removeDeadConstantUsers(), RemoveInstInputs(), removeLifetimeIntrinsicUsers(), RemoveNestAttribute(), replaceAndRecursivelySimplifyImpl(), replaceConstantExprOp(), ReplaceUsesOfMallocWithGlobal(), ReplaceUsesOfWith(), RewriteHeapSROALoadUser(), rewriteNonInstructionUses(), rewriteSingleStoreAlloca(), RewriteUsesOfClonedInstructions(), RewriteUsesOfLoadForHeapSRoA(), llvm::NVPTXLowerAggrCopies::runOnFunction(), llvm::StackProtector::runOnFunction(), AllocaSlices::SliceBuilder::SliceBuilder(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), llvm::SparseSolver::Solve(), speculatePHINodeLoads(), speculateSelectInstLoads(), swapMayExposeCSEOpportunities(), tryToMakeAllocaBePromotable(), TryToShrinkGlobalToBoolean(), llvm::UpgradeCallsToIntrinsic(), llvm::Instruction::use_back(), use_back(), usedInGlobalVarDef(), usedInOneFunc(), useFuncSeen(), ValueIsOnlyUsedLocallyOrStoredToOneGlobal(), llvm::InstCombiner::visitICmpInst(), WriteUseList(), and ~Value().
const_use_iterator llvm::Value::use_begin () const inline
Definition at line 151 of file Value.h.
bool llvm::Value::use_empty () const inline
Definition at line 149 of file Value.h.
Referenced by AddReachableCodeToWorklist(), AddressIsTaken(), areAllUsesIn(), collectFailStats(), CommitValueTo(), computeBytesPoppedByCallee(), ComputePostOrders(), ConvertToSInt(), llvm::SelectionDAGBuilder::CopyToExportRegsIfNeeded(), createCast(), llvm::createConstantPropagationPass(), llvm::createDeadArgHackingPass(), llvm::createEarlyCSEPass(), llvm::createLICMPass(), llvm::createLoopInstSimplifyPass(), llvm::createObjCARCContractPass(), llvm::createObjCARCOptPass(), DeadPHICycle(), llvm::DeleteDeadBlock(), DeleteDeadInstruction(), deleteDeadInstruction(), DeleteInstructionInBlock(), llvm::MDNode::deleteTemporary(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), llvm::Constant::destroyConstantImpl(), llvm::AsmPrinter::doFinalization(), llvm::NVPTXAsmPrinter::doFinalization(), llvm::InstCombiner::DoOneIteration(), llvm::InstCombiner::EraseInstFromFunction(), llvm::objcarc::EraseInstruction(), llvm::FastISel::FastEmitZExtFromI1(), FindInitTrampoline(), FindSingleUseIdentifiedObject(), getAdjustedPtr(), getTruncatedArgReg(), hasAddressTakenAndUsed(), hasUseOtherThanLLVMUsed(), INITIALIZE_PASS(), llvm::InlineFunction(), InstallGlobalCtors(), isAlwaysFoldable(), IsBetterCannonical(), llvm::isInstructionTriviallyDead(), IsNonLocalValue(), isOnlyUsedInEntryBlock(), isSafeToEliminateVarargsCast(), isUsedOutsideOfDefiningBlock(), llvm::FastISel::leaveLocalValueArea(), LinearizeExprTree(), llvm::SelectionDAGBuilder::LowerCallOperands(), llvm::IntrinsicLowering::LowerIntrinsicCall(), MarkBlocksLiveIn(), MarkIndicesSafe(), NumRetVals(), OptimizeAwayTrappingUsesOfLoads(), OptimizeCmpExpression(), OptimizeGlobalAddressOfMalloc(), OptimizeNoopCopyExpression(), passingValueIsAlwaysUndefined(), patchAndReplaceAllUsesWith(), llvm::AssemblyWriter::printBasicBlock(), promoteSingleBlockAlloca(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), RemoveDeadConstant(), removeDeadUsersOfConstant(), removeFinishedSplitUses(), replaceAllUsesWith(), ReplaceCallWith(), ReplaceUsesOfMallocWithGlobal(), RewriteUsesOfClonedInstructions(), RewriteUsesOfLoadForHeapSRoA(), llvm::LoadAndStorePromoter::run(), llvm::Inliner::runOnSCC(), llvm::FunctionLoweringInfo::set(), llvm::InstCombiner::SimplifyDivRemOfSelect(), AllocaSlices::SliceBuilder::SliceBuilder(), speculatePHINodeLoads(), speculateSelectInstLoads(), SRAGlobal(), StripSymbolNames(), tryToMakeAllocaBePromotable(), TryToShrinkGlobalToBoolean(), useFuncSeen(), llvm::PtrUseVisitor< SliceBuilder >::visitGetElementPtrInst(), WriteUseList(), llvm::BasicBlock::~BasicBlock(), and ~Value().
use_iterator llvm::Value::use_end () inline
Definition at line 152 of file Value.h.
Referenced by AddressIsTaken(), llvm::IVUsers::AddUsersImpl(), llvm::InstCombineWorklist::AddUsersToWorkList(), AllCallersPassInValidPointerForArgument(), AllGlobalLoadUsesSimpleEnoughForHeapSRA(), AllUsesOfLoadedValueWillTrapIfNull(), AllUsesOfValueWillTrapIfNull(), AlmostDeadIV(), analyzeGlobalAux(), areAllUsesEqual(), areAllUsesIn(), canFoldIVIncExpr(), ChangeCalleesToFastCall(), llvm::GraphTraits< const Value * >::child_end(), llvm::GraphTraits< Value * >::child_end(), CleanupConstantGlobalUsers(), CleanupPointerRootUsers(), ConstantPropUsersOf(), ConvertToSInt(), llvm::createArgumentPromotionPass(), createCast(), llvm::createConstantPropagationPass(), llvm::createDeadArgHackingPass(), llvm::createGlobalsModRefPass(), llvm::createLICMPass(), llvm::createLoopInstSimplifyPass(), llvm::createMergeFunctionsPass(), llvm::createObjCARCContractPass(), llvm::createObjCARCOptPass(), llvm::createSinkingPass(), cxxDtorIsEmpty(), deleteIfDeadInstruction(), llvm::SCEVAddRecExpr::delinearize(), determinePointerReadAttrs(), llvm::detail::PtrUseVisitorBase::enqueueUsers(), enqueueUsersInWorklist(), FindInitTrampolineFromAlloca(), llvm::CodeExtractor::findInputsOutputs(), FindPhiPredForUseInBlock(), FindSingleUseIdentifiedObject(), FoldOperationIntoSelectOperand(), llvm::Inliner::getInlineThreshold(), llvm::getMallocType(), getNumUses(), GlobalUsersSafeToSRA(), llvm::Function::hasAddressTaken(), hasLifetimeMarkers(), hasNUses(), hasNUsesOrMore(), hasOneUse(), hasOutsideLoopUser(), hasUsesOutsideLoop(), INITIALIZE_PASS(), insertVector(), llvm::isAllocaPromotable(), isAllocSiteRemovable(), isCompatibleAggregate(), llvm::Constant::isConstantUsed(), isContiguous(), llvm::Function::isDefTriviallyDead(), isExitBlock(), isHighCostExpansion(), isLoopInvariant(), IsNonLocalValue(), isOnlyCopiedFromConstantGlobal(), isOnlyUsedInEntryBlock(), IsOnlyUsedInZeroEqualityComparison(), isProfitableChain(), isSafePHIToSpeculate(), isSafeSelectToSpeculate(), isSafeSROAElementUse(), llvm::isSafeToDestroyConstant(), isSimpleLoadStore(), IsStoredObjCPointer(), isUsedByLifetimeMarker(), isUsedInBasicBlock(), llvm::Instruction::isUsedOutsideOfBlock(), isUsedOutsideOfDefiningBlock(), IsUserOfGlobalSafeForSRA(), isZeroLengthArray(), LLVMGetFirstUse(), LoadUsesSimpleEnoughForHeapSRA(), llvm::LowerDbgDeclare(), MarkBlocksLiveIn(), MarkIndicesSafe(), NegateValue(), NumRetVals(), OnlyUsedBy(), llvm::onlyUsedByLifetimeMarkers(), OptimizeAwayTrappingUsesOfLoads(), OptimizeAwayTrappingUsesOfValue(), OptimizeCmpExpression(), OptimizeNoopCopyExpression(), patchAndReplaceAllUsesWith(), PerformHeapAllocSRoA(), llvm::PointerMayBeCaptured(), llvm::ValueEnumerator::print(), ProcessUGT_ADDCST_ADD(), promoteSingleBlockAlloca(), PushDefUseChildren(), pushIVUsers(), llvm::Constant::removeDeadConstantUsers(), RemoveInstInputs(), removeLifetimeIntrinsicUsers(), RemoveNestAttribute(), replaceAndRecursivelySimplifyImpl(), replaceConstantExprOp(), ReplaceUsesOfWith(), RewriteHeapSROALoadUser(), rewriteNonInstructionUses(), rewriteSingleStoreAlloca(), RewriteUsesOfClonedInstructions(), RewriteUsesOfLoadForHeapSRoA(), llvm::StackProtector::runOnFunction(), AllocaSlices::SliceBuilder::SliceBuilder(), llvm::InstCombiner::SliceUpIllegalIntegerPHI(), llvm::SparseSolver::Solve(), swapMayExposeCSEOpportunities(), tryToMakeAllocaBePromotable(), TryToShrinkGlobalToBoolean(), llvm::UpgradeCallsToIntrinsic(), usedInGlobalVarDef(), usedInOneFunc(), useFuncSeen(), ValueIsOnlyUsedLocallyOrStoredToOneGlobal(), WriteUseList(), and ~Value().
const_use_iterator llvm::Value::use_end () const inline
Definition at line 153 of file Value.h.
Friends And Related Function Documentation
friend class ValueHandleBase friend
Definition at line 86 of file Value.h.
friend class ValueSymbolTable friend
Definition at line 85 of file Value.h.
Referenced by llvm::Function::eraseFromParent().
Member Data Documentation
const unsigned llvm::Value::MaximumAlignment = 1u << 29 static
MaximumAlignment - This is the greatest alignment value supported by load, store, and alloca instructions, and global values.
Definition at line 335 of file Value.h.
Referenced by llvm::getOrEnforceKnownAlignment().
unsigned char llvm::Value::SubclassOptionalData protected
SubclassOptionalData - This member is similar to SubclassData, however it is for holding information which may be used to aid optimization, but which may be cleared to zero without affecting conservative interpretation.
Definition at line 74 of file Value.h.
Referenced by llvm::SelectInst::areInvalidOperands(), llvm::BinaryConstantExpr::BinaryConstantExpr(), clearSubclassOptionalData(), llvm::Instruction::clone(), llvm::GetElementPtrConstantExpr::Create(), llvm::CallInst::CreateFree(), llvm::FenceInst::FenceInst(), llvm::ConstantExpr::getAsInstruction(), llvm::FPMathOperator::getFastMathFlags(), llvm::InvokeInst::getLandingPadInst(), getRawSubclassOptionalData(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::ConstantExpr::getWithOperands(), llvm::FPMathOperator::hasAllowReciprocal(), llvm::FPMathOperator::hasNoInfs(), llvm::FPMathOperator::hasNoNaNs(), llvm::OverflowingBinaryOperator::hasNoSignedWrap(), llvm::FPMathOperator::hasNoSignedZeros(), llvm::OverflowingBinaryOperator::hasNoUnsignedWrap(), hasSameSubclassOptionalData(), llvm::FPMathOperator::hasUnsafeAlgebra(), intersectOptionalDataWith(), llvm::PossiblyExactOperator::isExact(), llvm::CmpInst::isFalseWhenEqual(), llvm::Instruction::isIdenticalTo(), llvm::GEPOperator::isInBounds(), llvm::SwitchInst::removeCase(), llvm::UnreachableInst::UnreachableInst(), and llvm::CallInst::~CallInst().
The documentation for this class was generated from the following files:
Value.h
AsmWriter.cpp
Value.cpp