LLVM: llvm::CCValAssign Class Reference
LLVM API Documentation
llvm::CCValAssign Class Reference
CCValAssign - Represent assignment of one arg/retval to a location.
#include <CallingConvLower.h>
Public Types
enum LocInfo {
Full, SExt, ZExt, AExt,
BCvt, VExt, Indirect
}
Public Member Functions
unsigned getValNo () const
MVT getValVT () const
bool isRegLoc () const
bool isMemLoc () const
bool needsCustom () const
unsigned getLocReg () const
unsigned getLocMemOffset () const
MVT getLocVT () const
LocInfo getLocInfo () const
bool isExtInLoc () const
Static Public Member Functions
static CCValAssign getReg (unsigned ValNo, MVT ValVT, unsigned RegNo, MVT LocVT, LocInfo HTP)
static CCValAssign getCustomReg (unsigned ValNo, MVT ValVT, unsigned RegNo, MVT LocVT, LocInfo HTP)
static CCValAssign getMem (unsigned ValNo, MVT ValVT, unsigned Offset, MVT LocVT, LocInfo HTP)
static CCValAssign getCustomMem (unsigned ValNo, MVT ValVT, unsigned Offset, MVT LocVT, LocInfo HTP)
Detailed Description
CCValAssign - Represent assignment of one arg/retval to a location.
Definition at line 31 of file CallingConvLower.h.
Member Enumeration Documentation
enum llvm::CCValAssign::LocInfo
Enumerator
Full
SExt
ZExt
AExt
BCvt
VExt
Indirect
Definition at line 33 of file CallingConvLower.h.
Member Function Documentation
static CCValAssign llvm::CCValAssign::getCustomMem (unsigned ValNo, MVT ValVT, unsigned Offset, MVT LocVT, LocInfo HTP) inline static
Definition at line 105 of file CallingConvLower.h.
References getMem(), and llvm::AArch64ISD::Ret.
Referenced by CC_Sparc_Assign_f64(), CC_Sparc_Assign_SRet(), llvm::f64AssignAAPCS(), and llvm::f64AssignAPCS().
static CCValAssign llvm::CCValAssign::getCustomReg (unsigned ValNo, MVT ValVT, unsigned RegNo, MVT LocVT, LocInfo HTP) inline static
Definition at line 82 of file CallingConvLower.h.
References getReg(), and llvm::AArch64ISD::Ret.
Referenced by CC_Sparc64_Half(), CC_Sparc_Assign_f64(), llvm::f64AssignAAPCS(), llvm::f64AssignAPCS(), and llvm::f64RetAssign().
LocInfo llvm::CCValAssign::getLocInfo () const inline
Definition at line 126 of file CallingConvLower.h.
Referenced by AnalyzeReturnValues(), canUseSiblingCall(), computeBytesPoppedByCallee(), convertLocVTToValVT(), convertValVTToLocVT(), EmitTailCallStoreRetAddr(), fixupVariableFloatArgs(), FPCCToARMCC(), FuncIsMadeTailCallSafe(), getComparePred(), llvm::MipsTargetLowering::getOpndList(), isADDADDMUL(), isLocalCall(), llvm::X86TargetLowering::isNoopAddrSpaceCast(), llvm::HexagonTargetLowering::LowerCall(), llvm::AArch64TargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::AArch64TargetLowering::LowerCallResult(), llvm::AArch64TargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerInterruptReturn(), llvm::AArch64TargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_64(), LowerVASTART(), and MatchingStackOffset().
unsigned llvm::CCValAssign::getLocMemOffset () const inline
Definition at line 123 of file CallingConvLower.h.
References isMemLoc().
Referenced by AnalyzeReturnValues(), CalculateStackSlotSize(), computeBytesPoppedByCallee(), EmitTailCallStoreRetAddr(), FPCCToARMCC(), FuncIsMadeTailCallSafe(), getComparePred(), llvm::MipsTargetLowering::getOpndList(), isADDADDMUL(), isLocalCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::AArch64TargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::AArch64TargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerVASTART(), and MatchingStackOffset().
unsigned llvm::CCValAssign::getLocReg () const inline
Definition at line 122 of file CallingConvLower.h.
References isRegLoc().
Referenced by AnalyzeReturnValues(), CalculateStackSlotSize(), canUseSiblingCall(), computeBytesPoppedByCallee(), EmitTailCallStoreRetAddr(), fixupVariableFloatArgs(), FPCCToARMCC(), FuncIsMadeTailCallSafe(), getComparePred(), llvm::MipsTargetLowering::getOpndList(), isADDADDMUL(), isLocalCall(), llvm::X86TargetLowering::isNoopAddrSpaceCast(), llvm::HexagonTargetLowering::LowerCall(), llvm::AArch64TargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::AArch64TargetLowering::LowerCallResult(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::AArch64TargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerInterruptReturn(), llvm::HexagonTargetLowering::LowerReturn(), llvm::AArch64TargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), LowerVASTART(), and MatchingStackOffset().
MVT llvm::CCValAssign::getLocVT () const inline
Definition at line 124 of file CallingConvLower.h.
Referenced by AnalyzeReturnValues(), CalculateStackSlotSize(), computeBytesPoppedByCallee(), convertLocVTToValVT(), convertValVTToLocVT(), EmitTailCallStoreRetAddr(), fixupVariableFloatArgs(), FPCCToARMCC(), FuncIsMadeTailCallSafe(), getComparePred(), llvm::MipsTargetLowering::getOpndList(), isADDADDMUL(), isLocalCall(), llvm::X86TargetLowering::isNoopAddrSpaceCast(), llvm::HexagonTargetLowering::LowerCall(), llvm::AArch64TargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::AArch64TargetLowering::LowerCallResult(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::AArch64TargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerInterruptReturn(), llvm::HexagonTargetLowering::LowerReturn(), llvm::AArch64TargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), LowerVASTART(), and MatchingStackOffset().
static CCValAssign llvm::CCValAssign::getMem (unsigned ValNo, MVT ValVT, unsigned Offset, MVT LocVT, LocInfo HTP) inline static
Definition at line 91 of file CallingConvLower.h.
References llvm::AArch64ISD::Ret.
Referenced by allocateStack(), llvm::MipsTargetLowering::MipsCC::analyzeReturn(), CC_Hexagon(), CC_Hexagon32(), CC_Hexagon64(), CC_Hexagon_VarArg(), CC_MipsO32(), CC_Sparc64_Full(), CC_Sparc64_Half(), fixupVariableFloatArgs(), getCustomMem(), llvm::Hexagon_CCState::HandleByVal(), llvm::CCState::HandleByVal(), RetCC_Hexagon32(), and RetCC_Hexagon64().
static CCValAssign llvm::CCValAssign::getReg (unsigned ValNo, MVT ValVT, unsigned RegNo, MVT LocVT, LocInfo HTP) inline static
Definition at line 68 of file CallingConvLower.h.
References llvm::AArch64ISD::Ret.
Referenced by AnalyzeArguments(), llvm::Hexagon_CCState::AnalyzeReturn(), CC_Hexagon32(), CC_Hexagon64(), CC_MipsO32(), CC_Sparc64_Full(), CC_Sparc64_Half(), fixupVariableFloatArgs(), getCustomReg(), RetCC_Hexagon32(), and RetCC_Hexagon64().
unsigned llvm::CCValAssign::getValNo () const inline
Definition at line 114 of file CallingConvLower.h.
Referenced by computeBytesPoppedByCallee(), fixupVariableFloatArgs(), FuncIsMadeTailCallSafe(), getComparePred(), isLocalCall(), and LowerVASTART().
MVT llvm::CCValAssign::getValVT () const inline
Definition at line 115 of file CallingConvLower.h.
Referenced by AnalyzeReturnValues(), CalculateStackSlotSize(), convertLocVTToValVT(), EmitTailCallStoreRetAddr(), fixupVariableFloatArgs(), FPCCToARMCC(), FuncIsMadeTailCallSafe(), getComparePred(), llvm::MipsTargetLowering::getOpndList(), isLocalCall(), llvm::X86TargetLowering::isNoopAddrSpaceCast(), llvm::AArch64TargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_64(), llvm::AArch64TargetLowering::LowerCallResult(), llvm::AArch64TargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), llvm::SparcTargetLowering::LowerReturn_64(), and LowerVASTART().
bool llvm::CCValAssign::isExtInLoc () const inline
Definition at line 127 of file CallingConvLower.h.
References AExt, SExt, and ZExt.
Referenced by convertLocVTToValVT(), FuncIsMadeTailCallSafe(), llvm::SparcTargetLowering::LowerCall_64(), and llvm::SparcTargetLowering::LowerFormalArguments_64().
bool llvm::CCValAssign::isMemLoc () const inline
Definition at line 118 of file CallingConvLower.h.
Referenced by AnalyzeReturnValues(), CalculateStackSlotSize(), EmitTailCallStoreRetAddr(), FPCCToARMCC(), FuncIsMadeTailCallSafe(), getComparePred(), getLocMemOffset(), llvm::MipsTargetLowering::getOpndList(), isADDADDMUL(), isLocalCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::AArch64TargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::AArch64TargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), and LowerVASTART().
bool llvm::CCValAssign::isRegLoc () const inline
Definition at line 117 of file CallingConvLower.h.
Referenced by AnalyzeReturnValues(), CalculateStackSlotSize(), canUseSiblingCall(), computeBytesPoppedByCallee(), EmitTailCallStoreRetAddr(), fixupVariableFloatArgs(), FPCCToARMCC(), FuncIsMadeTailCallSafe(), getComparePred(), getLocReg(), llvm::MipsTargetLowering::getOpndList(), isADDADDMUL(), isLocalCall(), llvm::X86TargetLowering::isNoopAddrSpaceCast(), llvm::HexagonTargetLowering::LowerCall(), llvm::AArch64TargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::AArch64TargetLowering::LowerCallResult(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::AArch64TargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerInterruptReturn(), llvm::AArch64TargetLowering::LowerReturn(), llvm::SystemZTargetLowering::LowerReturn(), llvm::SparcTargetLowering::LowerReturn_32(), llvm::SparcTargetLowering::LowerReturn_64(), LowerVASTART(), and MatchingStackOffset().
bool llvm::CCValAssign::needsCustom () const inline
Definition at line 120 of file CallingConvLower.h.
Referenced by FPCCToARMCC(), getComparePred(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SparcTargetLowering::LowerCall_64(), llvm::SparcTargetLowering::LowerFormalArguments_32(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerInterruptReturn(), llvm::SparcTargetLowering::LowerReturn_64(), LowerVASTART(), and MatchingStackOffset().
The documentation for this class was generated from the following file:
CallingConvLower.h