LLVM: llvm::CodeExtractor Class Reference
LLVM API Documentation
llvm::CodeExtractor Class Reference
Utility class for extracting code into a new function.
#include <CodeExtractor.h>
Public Member Functions
CodeExtractor (BasicBlock *BB, bool AggregateArgs=false)
Create a code extractor for a single basic block.
CodeExtractor (ArrayRef< BasicBlock * > BBs, DominatorTree *DT=0, bool AggregateArgs=false)
Create a code extractor for a sequence of blocks.
CodeExtractor (DominatorTree &DT, Loop &L, bool AggregateArgs=false)
Create a code extractor for a loop body.
CodeExtractor (DominatorTree &DT, const RegionNode &RN, bool AggregateArgs=false)
Create a code extractor for a region node.
Function * extractCodeRegion ()
Perform the extraction, returning the new function.
bool isEligible () const
Test whether this code extractor is eligible.
void findInputsOutputs (ValueSet &Inputs, ValueSet &Outputs) const
Compute the set of input values and output values for the code.
Detailed Description
Utility class for extracting code into a new function.
This utility provides a simple interface for extracting some sequence of code into its own function, replacing it with a call to that function. It also provides various methods to query about the nature and result of such a transformation.
The rough algorithm used is: 1) Find both the inputs and outputs for the extracted region. 2) Pass the inputs as arguments, remapping them within the extracted function to arguments. 3) Add allocas for any scalar outputs, adding all of the outputs' allocas as arguments, and inserting stores to the arguments for any scalars.
Definition at line 44 of file CodeExtractor.h.
Constructor & Destructor Documentation
CodeExtractor::CodeExtractor (BasicBlock * BB, bool AggregateArgs = false)
Create a code extractor for a single basic block.
In this formation, we don't require a dominator tree. The given basic block is set up for extraction.
Definition at line 120 of file CodeExtractor.cpp.
CodeExtractor::CodeExtractor (ArrayRef< BasicBlock * > BBs, DominatorTree * DT = 0, bool AggregateArgs = false)
Create a code extractor for a sequence of blocks.
Given a sequence of basic blocks where the first block in the sequence dominates the rest, prepare a code extractor object for pulling this sequence out into its new function. When a DominatorTree is also given, extra checking and transformations are enabled.
Definition at line 124 of file CodeExtractor.cpp.
CodeExtractor::CodeExtractor (DominatorTree & DT, Loop & L, bool AggregateArgs = false)
Create a code extractor for a loop body.
Behaves just like the generic code sequence constructor, but uses the block sequence of the loop.
Definition at line 129 of file CodeExtractor.cpp.
CodeExtractor::CodeExtractor (DominatorTree & DT, const RegionNode & RN, bool AggregateArgs = false)
Create a code extractor for a region node.
Behaves just like the generic code sequence constructor, but uses the block sequence of the region node passed in.
Definition at line 133 of file CodeExtractor.cpp.
Member Function Documentation
Function * CodeExtractor::extractCodeRegion ()
Perform the extraction, returning the new function.
Returns zero when called on a CodeExtractor instance where isEligible returns false.
Definition at line 688 of file CodeExtractor.cpp.
References llvm::sys::path::begin(), llvm::BasicBlock::begin(), llvm::BasicBlock::Create(), llvm::BranchInst::Create(), DEBUG, findInputsOutputs(), llvm::BasicBlock::getContext(), llvm::PHINode::getIncomingBlock(), llvm::BasicBlock::getInstList(), llvm::PHINode::getNumIncomingValues(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), i, I, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), isEligible(), llvm::iplist< NodeTy, Traits >::push_back(), llvm::PHINode::removeIncomingValue(), llvm::report_fatal_error(), llvm::PHINode::setIncomingBlock(), llvm::SmallPtrSetImpl::size(), llvm::succ_begin(), llvm::succ_end(), and llvm::verifyFunction().
Referenced by INITIALIZE_PASS().
void CodeExtractor::findInputsOutputs (ValueSet & Inputs, ValueSet & Outputs) const
Compute the set of input values and output values for the code.
These can be used either when performing the extraction or to evaluate the expected size of a call to the extracted function. Note that this work cannot be cached between the two as once we decide to extract a code sequence, that sequence is modified, including changing these sets, before extraction occurs. These modifications won't have any significant impact on the cost however.
Definition at line 158 of file CodeExtractor.cpp.
References llvm::PHINode::addIncoming(), llvm::DominatorTree::addNewBlock(), llvm::Function::arg_begin(), BB, llvm::SetVector< T, Vector, Set >::begin(), llvm::DomTreeNodeBase< NodeT >::begin(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::BasicBlock::begin(), llvm::Function::begin(), llvm::DominatorTree::changeImmediateDominator(), llvm::Function::Create(), llvm::GetElementPtrInst::Create(), llvm::PHINode::Create(), llvm::dbgs(), llvm::X86II::DE, DEBUG, definedInCaller(), definedInRegion(), llvm::Function::doesNotThrow(), llvm::dyn_cast(), llvm::DomTreeNodeBase< NodeT >::end(), llvm::SetVector< T, Vector, Set >::end(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::BasicBlock::end(), llvm::ConstantInt::get(), llvm::FunctionType::get(), llvm::StructType::get(), llvm::Function::getBasicBlockList(), llvm::BasicBlock::getContext(), llvm::Module::getContext(), llvm::Function::getEntryBlock(), llvm::BasicBlock::getFirstNonPHI(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::Type::getInt16Ty(), llvm::Type::getInt1Ty(), llvm::Type::getInt32Ty(), llvm::Intrinsic::getName(), llvm::Value::getName(), llvm::DominatorTree::getNode(), llvm::Constant::getNullValue(), llvm::PHINode::getNumIncomingValues(), llvm::BasicBlock::getParent(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::PointerType::getUnqual(), llvm::Type::getVoidTy(), i, I, llvm::ARM_PROC::IE, llvm::SetVector< T, Vector, Set >::insert(), llvm::GlobalValue::InternalLinkage, M, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::iplist< NodeTy, Traits >::push_back(), llvm::PHINode::removeIncomingValue(), llvm::User::replaceUsesOfWith(), llvm::Function::setDoesNotThrow(), llvm::SetVector< T, Vector, Set >::size(), llvm::BasicBlock::splitBasicBlock(), llvm::DominatorTree::splitBlock(), use, llvm::Value::use_begin(), llvm::Value::use_end(), and Users.
Referenced by extractCodeRegion(), and isEligible().
bool llvm::CodeExtractor::isEligible () const inline
Test whether this code extractor is eligible.
Based on the blocks used when constructing the code extractor, determine whether it is eligible for extraction.
Definition at line 95 of file CodeExtractor.h.
References llvm::SetVector< T, Vector, Set >::empty(), findInputsOutputs(), and M.
Referenced by extractCodeRegion().
The documentation for this class was generated from the following files:
CodeExtractor.h
CodeExtractor.cpp