LLVM: llvm::HexagonSelectionDAGInfo Class Reference
LLVM API Documentation
llvm::HexagonSelectionDAGInfo Class Reference
#include <HexagonSelectionDAGInfo.h>
Public Member Functions
HexagonSelectionDAGInfo (const HexagonTargetMachine &TM)
~HexagonSelectionDAGInfo ()
virtual SDValue EmitTargetCodeForMemcpy (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Dst, SDValue Src, SDValue Size, unsigned Align, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const
Public Member Functions inherited from llvm::TargetSelectionDAGInfo
TargetSelectionDAGInfo (const TargetMachine &TM)
virtual ~TargetSelectionDAGInfo ()
virtual SDValue EmitTargetCodeForMemmove (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const
virtual SDValue EmitTargetCodeForMemset (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, MachinePointerInfo DstPtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForMemcmp (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForMemchr (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Src, SDValue Char, SDValue Length, MachinePointerInfo SrcPtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrcpy (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Dest, SDValue Src, MachinePointerInfo DestPtrInfo, MachinePointerInfo SrcPtrInfo, bool isStpcpy) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrcmp (SelectionDAG &DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, MachinePointerInfo Op1PtrInfo, MachinePointerInfo Op2PtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrlen (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Src, MachinePointerInfo SrcPtrInfo) const
virtual std::pair< SDValue, SDValue > EmitTargetCodeForStrnlen (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Src, SDValue MaxLength, MachinePointerInfo SrcPtrInfo) const
Additional Inherited Members
Protected Member Functions inherited from llvm::TargetSelectionDAGInfo
const DataLayout * getDataLayout () const
Detailed Description
Definition at line 23 of file HexagonSelectionDAGInfo.h.
Constructor & Destructor Documentation
HexagonSelectionDAGInfo::HexagonSelectionDAGInfo (const HexagonTargetMachine & TM) explicit
Definition at line 20 of file HexagonSelectionDAGInfo.cpp.
HexagonSelectionDAGInfo::~HexagonSelectionDAGInfo ()
Definition at line 25 of file HexagonSelectionDAGInfo.cpp.
References EmitTargetCodeForMemcpy().
Member Function Documentation
SDValue HexagonSelectionDAGInfo::EmitTargetCodeForMemcpy (SelectionDAG & DAG, SDLoc dl, SDValue Chain, SDValue Op1, SDValue Op2, SDValue Op3, unsigned Align, bool isVolatile, bool AlwaysInline, MachinePointerInfo DstPtrInfo, MachinePointerInfo SrcPtrInfo) const virtual
EmitTargetCodeForMemcpy - Emit target-specific code that performs a memcpy. This can be used by targets to provide code sequences for cases that don't fit the target's parameters for simple loads/stores and can be more efficient than using a library call. This function can return a null SDValue if the target declines to use custom code and a different lowering strategy should be used.
If AlwaysInline is true, the size is constant and the target should not emit any calls and is strongly encouraged to attempt to emit inline code even if it is beyond the usual threshold because this intrinsic is being expanded in a place where calls are not feasible (e.g. within the prologue for another call). If the target chooses to decline an AlwaysInline request here, legalize will resort to using simple loads and stores.
Reimplemented from llvm::TargetSelectionDAGInfo.
Definition at line 30 of file HexagonSelectionDAGInfo.cpp.
References llvm::dyn_cast(), llvm::flag_aligned_memcpy, llvm::ConstantSDNode::getZExtValue(), and x3.
Referenced by ~HexagonSelectionDAGInfo().
The documentation for this class was generated from the following files:
HexagonSelectionDAGInfo.h
HexagonSelectionDAGInfo.cpp