LLVM: llvm::OwningPtr< T > Class Template Reference
LLVM API Documentation
llvm::OwningPtr< T > Class Template Reference
#include <OwningPtr.h>
Public Member Functions
OwningPtr (T *P=0)
~OwningPtr ()
void reset (T *P=0)
T * take ()
T & operator* () const
T * operator-> () const
T * get () const
LLVM_EXPLICIT operator bool () const
bool operator! () const
bool isValid () const
void swap (OwningPtr &RHS)
Detailed Description
template<class T>
class llvm::OwningPtr< T >
OwningPtr smart pointer - OwningPtr mimics a built-in pointer except that it guarantees deletion of the object pointed to, either on destruction of the OwningPtr or via an explicit reset(). Once created, ownership of the pointee object can be taken away from OwningPtr by using the take method.
Definition at line 28 of file OwningPtr.h.
Constructor & Destructor Documentation
template<class T> llvm::OwningPtr< T >::OwningPtr (T * P = 0) inline explicit
Definition at line 33 of file OwningPtr.h.
template<class T> llvm::OwningPtr< T >::~OwningPtr () inline
Definition at line 44 of file OwningPtr.h.
Member Function Documentation
template<class T> T* llvm::OwningPtr< T >::get () const inline
Definition at line 72 of file OwningPtr.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitMC(), llvm::DWARFUnit::buildAddressRangeTable(), canBeHidden(), llvm::FileOutputBuffer::create(), llvm::SpecialCaseList::create(), llvm::MCJIT::generateCodeForModule(), llvm::LLVMDisasmContext::getAsmInfo(), llvm::CompileUnit::getCUDie(), llvm::LLVMDisasmContext::getDisAsm(), llvm::DWARFUnit::getDWOId(), llvm::MipsTargetMachine::getFrameLowering(), llvm::ThumbTargetMachine::getFrameLowering(), llvm::DWARFUnit::getInlinedChainForAddress(), llvm::AMDGPUTargetMachine::getInstrInfo(), llvm::MipsTargetMachine::getInstrInfo(), llvm::LLVMDisasmContext::getInstrInfo(), llvm::ThumbTargetMachine::getInstrInfo(), llvm::LLVMDisasmContext::getIP(), LTOModule::getLLVVMModule(), llvm::Module::getMaterializer(), llvm::LLVMDisasmContext::getRegisterInfo(), llvm::LLVMDisasmContext::getSubtargetInfo(), llvm::AMDGPUTargetMachine::getTargetLowering(), llvm::MipsTargetMachine::getTargetLowering(), getWin64EHTableSection(), llvm::ParseAssembly(), llvm::DebugIR::runOnModule(), and llvm::yaml::Input::setCurrentDocument().
template<class T> bool llvm::OwningPtr< T >::isValid () const inline
Definition at line 75 of file OwningPtr.h.
template<class T> LLVM_EXPLICIT llvm::OwningPtr< T >::operator bool () const inline
Definition at line 73 of file OwningPtr.h.
template<class T> bool llvm::OwningPtr< T >::operator! () const inline
Definition at line 74 of file OwningPtr.h.
template<class T> T& llvm::OwningPtr< T >::operator* () const inline
Definition at line 66 of file OwningPtr.h.
template<class T> T* llvm::OwningPtr< T >::operator-> () const inline
Definition at line 71 of file OwningPtr.h.
template<class T> void llvm::OwningPtr< T >::reset (T * P = 0) inline
reset - Change the current pointee to the specified pointer. Note that calling this with any pointer (including a null pointer) deletes the current pointer.
Definition at line 51 of file OwningPtr.h.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitMC(), llvm::BitstreamReader::BitstreamReader(), llvm::DWARFUnit::buildAddressRangeTable(), llvm::DWARFUnit::clear(), llvm::zlib::compress(), llvm::FileOutputBuffer::create(), llvm::createDefaultPBQPRegisterAllocator(), llvm::createGreedyRegisterAllocator(), llvm::object::ObjectFile::createMachOObjectFile(), llvm::createMipsDelaySlotFillerPass(), llvm::MCJIT::generateCodeForModule(), llvm::object::MachOUniversalBinary::ObjectForArch::getAsObjectFile(), llvm::DWARFUnit::getDWOId(), llvm::object::Archive::Child::getMemoryBuffer(), getMemoryBufferForStream(), getOpenFileImpl(), llvm::BitstreamReader::init(), llvm::LLVMDisasmContext::LLVMDisasmContext(), llvm::OwningArrayPtr< unsigned >::OwningArrayPtr(), llvm::OwningPtr< const llvm::llvm::MCDisassembler >::OwningPtr(), llvm::yaml::Input::setCurrentDocument(), llvm::LLVMDisasmContext::setIP(), llvm::zlib::uncompress(), and llvm::yaml2mcmodule().
template<class T> void llvm::OwningPtr< T >::swap (OwningPtr< T > & RHS) inline
Definition at line 77 of file OwningPtr.h.
Referenced by llvm::object::createBinary(), llvm::object::Archive::Child::getAsBinary(), getOpenFileImpl(), and llvm::swap().
template<class T> T* llvm::OwningPtr< T >::take () inline
take - Reset the owning pointer to null and return its pointer. This does not delete the pointer before returning it.
Definition at line 60 of file OwningPtr.h.
Referenced by llvm::SourceMgr::AddIncludeFile(), llvm::LLVMTargetMachine::addPassesToEmitMC(), llvm::PBQPBuilder::build(), llvm::PBQPBuilderWithCoalescing::build(), LTOCodeGenerator::compile(), llvm::FileOutputBuffer::create(), llvm::SpecialCaseList::create(), llvm::EngineBuilder::create(), llvm::object::createBinary(), llvm::object::ObjectFile::createMachOObjectFile(), llvm::object::ObjectFile::createObjectFile(), llvm::DWARFContextInMemory::DWARFContextInMemory(), llvm::MCJIT::emitObject(), llvm::MCJIT::generateCodeForModule(), llvm::object::Archive::Child::getAsBinary(), llvm::getLazyIRFileModule(), llvm::DWARFContext::getLineTableForCompileUnit(), LTOModule::isBitcodeFileForTarget(), LLVMCreateMemoryBufferWithContentsOfFile(), LLVMCreateMemoryBufferWithSTDIN(), llvm::RuntimeDyldImpl::loadObject(), LTOModule::makeLTOModule(), llvm::ParseAssembly(), llvm::ParseAssemblyFile(), llvm::ParseIRFile(), llvm::MCObjectDisassembler::setFallbackRegion(), llvm::MCDisassembler::setSymbolizer(), and llvm::TableGenMain().
The documentation for this class was generated from the following file:
OwningPtr.h