LLVM: llvm::DotDebugLocEntry Class Reference
LLVM API Documentation
llvm::DotDebugLocEntry Class Reference
This struct describes location entries emitted in the .debug_loc section.
#include <DwarfDebug.h>
Public Member Functions
DotDebugLocEntry ()
DotDebugLocEntry (const MCSymbol *B, const MCSymbol *E, MachineLocation &L, const MDNode *V)
DotDebugLocEntry (const MCSymbol *B, const MCSymbol *E, int64_t i)
DotDebugLocEntry (const MCSymbol *B, const MCSymbol *E, const ConstantFP *FPtr)
DotDebugLocEntry (const MCSymbol *B, const MCSymbol *E, const ConstantInt *IPtr)
bool isEmpty ()
Empty entries are also used as a trigger to emit temp label. Such labels are referenced is used to find debug_loc offset for a given DIE.
bool isMerged ()
void Merge (DotDebugLocEntry *Next)
bool isLocation () const
bool isInt () const
bool isConstantFP () const
bool isConstantInt () const
int64_t getInt () const
const ConstantFP * getConstantFP () const
const ConstantInt * getConstantInt () const
const MDNode * getVariable () const
const MCSymbol * getBeginSym () const
const MCSymbol * getEndSym () const
MachineLocation getLoc () const
Detailed Description
This struct describes location entries emitted in the .debug_loc section.
Definition at line 65 of file DwarfDebug.h.
Constructor & Destructor Documentation
llvm::DotDebugLocEntry::DotDebugLocEntry () inline
Definition at line 95 of file DwarfDebug.h.
llvm::DotDebugLocEntry::DotDebugLocEntry (const MCSymbol * B, const MCSymbol * E, MachineLocation & L, const MDNode * V) inline
Definition at line 98 of file DwarfDebug.h.
llvm::DotDebugLocEntry::DotDebugLocEntry (const MCSymbol * B, const MCSymbol * E, int64_t i) inline
Definition at line 104 of file DwarfDebug.h.
References i.
llvm::DotDebugLocEntry::DotDebugLocEntry (const MCSymbol * B, const MCSymbol * E, const ConstantFP * FPtr) inline
Definition at line 109 of file DwarfDebug.h.
llvm::DotDebugLocEntry::DotDebugLocEntry (const MCSymbol * B, const MCSymbol * E, const ConstantInt * IPtr) inline
Definition at line 114 of file DwarfDebug.h.
Member Function Documentation
const MCSymbol* llvm::DotDebugLocEntry::getBeginSym () const inline
Definition at line 139 of file DwarfDebug.h.
Referenced by llvm::DwarfUnits::emitAddresses().
const ConstantFP* llvm::DotDebugLocEntry::getConstantFP () const inline
Definition at line 136 of file DwarfDebug.h.
const ConstantInt* llvm::DotDebugLocEntry::getConstantInt () const inline
Definition at line 137 of file DwarfDebug.h.
const MCSymbol* llvm::DotDebugLocEntry::getEndSym () const inline
Definition at line 140 of file DwarfDebug.h.
Referenced by llvm::DwarfUnits::emitAddresses().
int64_t llvm::DotDebugLocEntry::getInt () const inline
Definition at line 135 of file DwarfDebug.h.
Referenced by llvm::DwarfUnits::emitAddresses().
MachineLocation llvm::DotDebugLocEntry::getLoc () const inline
Definition at line 141 of file DwarfDebug.h.
Referenced by llvm::DwarfUnits::emitAddresses().
const MDNode* llvm::DotDebugLocEntry::getVariable () const inline
Definition at line 138 of file DwarfDebug.h.
Referenced by llvm::DwarfUnits::emitAddresses().
bool llvm::DotDebugLocEntry::isConstantFP () const inline
Definition at line 133 of file DwarfDebug.h.
bool llvm::DotDebugLocEntry::isConstantInt () const inline
Definition at line 134 of file DwarfDebug.h.
bool llvm::DotDebugLocEntry::isEmpty () inline
Empty entries are also used as a trigger to emit temp label. Such labels are referenced is used to find debug_loc offset for a given DIE.
Definition at line 123 of file DwarfDebug.h.
Referenced by llvm::DwarfUnits::emitAddresses().
bool llvm::DotDebugLocEntry::isInt () const inline
Definition at line 132 of file DwarfDebug.h.
Referenced by llvm::DwarfUnits::emitAddresses().
bool llvm::DotDebugLocEntry::isLocation () const inline
Definition at line 131 of file DwarfDebug.h.
Referenced by llvm::DwarfUnits::emitAddresses().
bool llvm::DotDebugLocEntry::isMerged () inline
Definition at line 124 of file DwarfDebug.h.
Referenced by llvm::DwarfUnits::emitAddresses().
void llvm::DotDebugLocEntry::Merge (DotDebugLocEntry * Next) inline
Definition at line 125 of file DwarfDebug.h.
Referenced by llvm::DwarfUnits::emitAddresses().
Member Data Documentation
const ConstantFP* llvm::DotDebugLocEntry::CFP
Definition at line 81 of file DwarfDebug.h.
const ConstantInt* llvm::DotDebugLocEntry::CIP
Definition at line 82 of file DwarfDebug.h.
int64_t llvm::DotDebugLocEntry::Int
Definition at line 80 of file DwarfDebug.h.
The documentation for this class was generated from the following file:
DwarfDebug.h