LLVM: llvm::DIDescriptor Class Reference
LLVM API Documentation
llvm::DIDescriptor Class Reference
#include <DebugInfo.h>
Public Types
enum {
FlagPrivate = 1 << 0, FlagProtected = 1 << 1, FlagFwdDecl = 1 << 2, FlagAppleBlock = 1 << 3,
FlagBlockByrefStruct = 1 << 4, FlagVirtual = 1 << 5, FlagArtificial = 1 << 6, FlagExplicit = 1 << 7,
FlagPrototyped = 1 << 8, FlagObjcClassComplete = 1 << 9, FlagObjectPointer = 1 << 10, FlagVector = 1 << 11,
FlagStaticMember = 1 << 12, FlagIndirectVariable = 1 << 13
}
Public Member Functions
DIDescriptor (const MDNode *N=0)
bool Verify () const
operator MDNode * () const
MDNode * operator-> () const
LLVM_EXPLICIT operator bool () const
bool operator== (DIDescriptor Other) const
bool operator!= (DIDescriptor Other) const
uint16_t getTag () const
bool isDerivedType () const
isDerivedType - Return true if the specified tag is legal for DIDerivedType.
bool isCompositeType () const
bool isBasicType () const
bool isVariable () const
isVariable - Return true if the specified tag is legal for DIVariable.
bool isSubprogram () const
bool isGlobalVariable () const
bool isScope () const
bool isFile () const
isFile - Return true if the specified tag is DW_TAG_file_type.
bool isCompileUnit () const
isCompileUnit - Return true if the specified tag is DW_TAG_compile_unit.
bool isNameSpace () const
isNameSpace - Return true if the specified tag is DW_TAG_namespace.
bool isLexicalBlockFile () const
bool isLexicalBlock () const
isLexicalBlock - Return true if the specified tag is DW_TAG_lexical_block.
bool isSubrange () const
isSubrange - Return true if the specified tag is DW_TAG_subrange_type.
bool isEnumerator () const
isEnumerator - Return true if the specified tag is DW_TAG_enumerator.
bool isType () const
isType - Return true if the specified tag is legal for DIType.
bool isUnspecifiedParameter () const
bool isTemplateTypeParameter () const
bool isTemplateValueParameter () const
bool isObjCProperty () const
isObjCProperty - Return true if the specified tag is DW_TAG_APPLE_property.
bool isImportedEntity () const
Return true if the specified tag is DW_TAG_imported_module or DW_TAG_imported_declaration.
void print (raw_ostream &OS) const
print - print descriptor.
void dump () const
dump - print descriptor to dbgs() with a newline.
Protected Member Functions
StringRef getStringField (unsigned Elt) const
unsigned getUnsignedField (unsigned Elt) const
uint64_t getUInt64Field (unsigned Elt) const
int64_t getInt64Field (unsigned Elt) const
DIDescriptor getDescriptorField (unsigned Elt) const
template<typename DescTy >
DescTy getFieldAs (unsigned Elt) const
GlobalVariable * getGlobalVariableField (unsigned Elt) const
Constant * getConstantField (unsigned Elt) const
Function * getFunctionField (unsigned Elt) const
void replaceFunctionField (unsigned Elt, Function *F)
template<>
DIScopeRef getFieldAs (unsigned Elt) const
Specialize getFieldAs to handle fields that are references to DIScopes.
template<>
DITypeRef getFieldAs (unsigned Elt) const
Specialize getFieldAs to handle fields that are references to DITypes.
template<>
DIScopeRef getFieldAs (unsigned Elt) const
Specialize getFieldAs to handle fields that are references to DIScopes.
template<>
DITypeRef getFieldAs (unsigned Elt) const
Specialize getFieldAs to handle fields that are references to DITypes.
Protected Attributes
const MDNode * DbgNode
Friends
template<typename T >
class DIRef
Detailed Description
DIDescriptor - A thin wraper around MDNode to access encoded debug info. This should not be stored in a container, because the underlying MDNode may change in certain situations.
Definition at line 60 of file DebugInfo.h.
Member Enumeration Documentation
anonymous enum
Enumerator
FlagPrivate
FlagProtected
FlagFwdDecl
FlagAppleBlock
FlagBlockByrefStruct
FlagVirtual
FlagArtificial
FlagExplicit
FlagPrototyped
FlagObjcClassComplete
FlagObjectPointer
FlagVector
FlagStaticMember
FlagIndirectVariable
Definition at line 66 of file DebugInfo.h.
Constructor & Destructor Documentation
llvm::DIDescriptor::DIDescriptor (const MDNode * N = 0) inline explicit
Definition at line 104 of file DebugInfo.h.
References Verify().
Referenced by llvm::DIRef< T >::resolve().
Member Function Documentation
void DIDescriptor::dump () const
dump - print descriptor to dbgs() with a newline.
dump - Print descriptor to dbgs() with a newline.
Definition at line 1195 of file DebugInfo.cpp.
References llvm::dbgs().
Referenced by getTag().
Constant * DIDescriptor::getConstantField (unsigned Elt) const protected
Definition at line 111 of file DebugInfo.cpp.
Referenced by llvm::DIDerivedType::getConstant(), llvm::DIGlobalVariable::getConstant(), and getFieldAs().
DIDescriptor DIDescriptor::getDescriptorField (unsigned Elt) const protected
Definition at line 97 of file DebugInfo.cpp.
References llvm::tgtok::Field, and getNodeField().
Referenced by llvm::DIArray::getElement(), getFieldAs(), and getUnsignedField().
template<typename DescTy > DescTy llvm::DIDescriptor::getFieldAs (unsigned Elt) const inline protected
Definition at line 94 of file DebugInfo.h.
References F(), getConstantField(), getDescriptorField(), getFunctionField(), getGlobalVariableField(), and replaceFunctionField().
Referenced by llvm::DIScope::DIScope().
template<> DIScopeRef llvm::DIDescriptor::getFieldAs (unsigned Elt) const protected
Specialize getFieldAs to handle fields that are references to DIScopes.
template<> DITypeRef llvm::DIDescriptor::getFieldAs (unsigned Elt) const protected
Specialize getFieldAs to handle fields that are references to DITypes.
template<> DIScopeRef llvm::DIDescriptor::getFieldAs (unsigned Elt) const protected
Specialize getFieldAs to handle fields that are references to DIScopes.
Definition at line 1422 of file DebugInfo.cpp.
References getField().
template<> DITypeRef llvm::DIDescriptor::getFieldAs (unsigned Elt) const protected
Specialize getFieldAs to handle fields that are references to DITypes.
Definition at line 1426 of file DebugInfo.cpp.
References getField().
Function * DIDescriptor::getFunctionField (unsigned Elt) const protected
Definition at line 120 of file DebugInfo.cpp.
Referenced by getFieldAs(), and llvm::DISubprogram::getFunction().
GlobalVariable * DIDescriptor::getGlobalVariableField (unsigned Elt) const protected
Definition at line 102 of file DebugInfo.cpp.
Referenced by getFieldAs(), and llvm::DIGlobalVariable::getGlobal().
int64_t DIDescriptor::getInt64Field (unsigned Elt) const protected
Definition at line 85 of file DebugInfo.cpp.
Referenced by llvm::DISubrange::getCount(), llvm::DIEnumerator::getEnumValue(), llvm::DISubrange::getLo(), and getUnsignedField().
StringRef DIDescriptor::getStringField (unsigned Elt) const protected
Definition at line 69 of file DebugInfo.cpp.
References getStringField().
Referenced by llvm::DISubprogram::getDisplayName(), llvm::DIGlobalVariable::getDisplayName(), llvm::DICompileUnit::getFlags(), llvm::DISubprogram::getLinkageName(), llvm::DIGlobalVariable::getLinkageName(), llvm::DIEnumerator::getName(), llvm::DIType::getName(), llvm::DISubprogram::getName(), llvm::DINameSpace::getName(), llvm::DITemplateTypeParameter::getName(), llvm::DITemplateValueParameter::getName(), llvm::DIGlobalVariable::getName(), llvm::DIVariable::getName(), llvm::DIImportedEntity::getName(), llvm::DIObjCProperty::getObjCPropertyGetterName(), llvm::DIObjCProperty::getObjCPropertyName(), llvm::DIObjCProperty::getObjCPropertySetterName(), llvm::DICompileUnit::getProducer(), and llvm::DICompileUnit::getSplitDebugFilename().
uint16_t llvm::DIDescriptor::getTag () const inline
Definition at line 121 of file DebugInfo.h.
References dump(), getUnsignedField(), isBasicType(), isCompileUnit(), isCompositeType(), isDerivedType(), isEnumerator(), isFile(), isGlobalVariable(), isImportedEntity(), isLexicalBlock(), isLexicalBlockFile(), isNameSpace(), isObjCProperty(), isScope(), isSubprogram(), isSubrange(), isTemplateTypeParameter(), isTemplateValueParameter(), isType(), isUnspecifiedParameter(), isVariable(), and print().
Referenced by llvm::CompileUnit::addBlockByrefAddress(), llvm::CompileUnit::addPubTypes(), llvm::DwarfDebug::beginFunction(), llvm::CompileUnit::constructVariableDIE(), llvm::DIBuilder::createFunction(), llvm::CompileUnit::createGlobalVariableDIE(), llvm::DIBuilder::createMethod(), llvm::DwarfDebug::endModule(), getBaseTypeSize(), llvm::DIDerivedType::getClassType(), llvm::DIDerivedType::getConstant(), getDebugLocEntry(), llvm::DwarfDebug::getOrCreateSourceID(), llvm::CompileUnit::getOrCreateSubprogramDIE(), llvm::CompileUnit::getOrCreateTypeDIE(), llvm::DbgVariable::getTag(), getTruncatedArgReg(), llvm::DbgVariable::getType(), llvm::DwarfDebug::isSubprogramContext(), shouldCreateTypeUnit(), and llvm::WriteMDNodeComment().
uint64_t DIDescriptor::getUInt64Field (unsigned Elt) const protected
Definition at line 73 of file DebugInfo.cpp.
Referenced by llvm::DIVariable::getAddrElement(), llvm::DIType::getAlignInBits(), llvm::DIType::getOffsetInBits(), llvm::DIType::getSizeInBits(), and getUnsignedField().
unsigned llvm::DIDescriptor::getUnsignedField (unsigned Elt) const inline protected
Definition at line 87 of file DebugInfo.h.
References getDescriptorField(), getInt64Field(), and getUInt64Field().
Referenced by llvm::DIVariable::getArgNumber(), llvm::DILexicalBlock::getColumnNumber(), llvm::DITemplateTypeParameter::getColumnNumber(), llvm::DITemplateValueParameter::getColumnNumber(), llvm::DILocation::getColumnNumber(), llvm::DIBasicType::getEncoding(), llvm::DIType::getFlags(), llvm::DISubprogram::getFlags(), llvm::DICompileUnit::getLanguage(), llvm::DIType::getLineNumber(), llvm::DISubprogram::getLineNumber(), llvm::DILexicalBlock::getLineNumber(), llvm::DINameSpace::getLineNumber(), llvm::DITemplateTypeParameter::getLineNumber(), llvm::DITemplateValueParameter::getLineNumber(), llvm::DIGlobalVariable::getLineNumber(), llvm::DIVariable::getLineNumber(), llvm::DILocation::getLineNumber(), llvm::DIObjCProperty::getLineNumber(), llvm::DIImportedEntity::getLineNumber(), llvm::DICompositeType::getRunTimeLang(), llvm::DICompileUnit::getRunTimeVersion(), llvm::DISubprogram::getScopeLineNumber(), getTag(), llvm::DISubprogram::getVirtualIndex(), llvm::DISubprogram::getVirtuality(), llvm::DISubprogram::isArtificial(), llvm::DIVariable::isArtificial(), llvm::DIObjCProperty::isAssignObjCProperty(), llvm::DIObjCProperty::isCopyObjCProperty(), llvm::DISubprogram::isDefinition(), llvm::DIGlobalVariable::isDefinition(), llvm::DISubprogram::isExplicit(), llvm::DIVariable::isIndirect(), llvm::DISubprogram::isLocalToUnit(), llvm::DIGlobalVariable::isLocalToUnit(), llvm::DIObjCProperty::isNonAtomicObjCProperty(), llvm::DIVariable::isObjectPointer(), llvm::DICompileUnit::isOptimized(), llvm::DISubprogram::isPrivate(), llvm::DISubprogram::isProtected(), llvm::DISubprogram::isPrototyped(), llvm::DIObjCProperty::isReadOnlyObjCProperty(), llvm::DIObjCProperty::isReadWriteObjCProperty(), and llvm::DIObjCProperty::isRetainObjCProperty().
bool DIDescriptor::isBasicType () const
isBasicType - Return true if the specified tag is legal for DIBasicType.
Definition at line 152 of file DebugInfo.cpp.
Referenced by llvm::CompileUnit::getOrCreateTypeDIE(), getTag(), isTypeSigned(), and isUnsignedDIType().
bool DIDescriptor::isCompileUnit () const
isCompileUnit - Return true if the specified tag is DW_TAG_compile_unit.
Definition at line 275 of file DebugInfo.cpp.
Referenced by llvm::CompileUnit::addGlobalType(), llvm::CompileUnit::createGlobalVariableDIE(), llvm::DwarfDebug::endFunction(), llvm::CompileUnit::getParentContextString(), getTag(), llvm::DwarfDebug::isSubprogramContext(), and llvm::DebugInfoFinder::processLocation().
bool DIDescriptor::isCompositeType () const
isCompositeType - Return true if the specified tag is legal for DICompositeType.
Definition at line 189 of file DebugInfo.cpp.
Referenced by llvm::DIBuilder::createClassType(), llvm::DIBuilder::createForwardDecl(), llvm::DIBuilder::createStructType(), llvm::getDICompositeType(), llvm::CompileUnit::getOrCreateTypeDIE(), getTag(), and llvm::DebugInfoFinder::processLocation().
bool DIDescriptor::isDerivedType () const
isDerivedType - Return true if the specified tag is legal for DIDerivedType.
Definition at line 165 of file DebugInfo.cpp.
Referenced by getBaseTypeSize(), llvm::getDICompositeType(), llvm::CompileUnit::getOrCreateTypeDIE(), getTag(), isTypeSigned(), isUnsignedDIType(), llvm::DebugInfoFinder::processLocation(), and shouldCreateTypeUnit().
bool DIDescriptor::isEnumerator () const
isEnumerator - Return true if the specified tag is DW_TAG_enumerator.
Definition at line 308 of file DebugInfo.cpp.
Referenced by getTag().
bool DIDescriptor::isFile () const
isFile - Return true if the specified tag is DW_TAG_file_type.
Definition at line 280 of file DebugInfo.cpp.
Referenced by llvm::CompileUnit::addGlobalType(), llvm::CompileUnit::createGlobalVariableDIE(), llvm::DwarfDebug::endFunction(), llvm::CompileUnit::getOrCreateContextDIE(), getTag(), and llvm::DwarfDebug::isSubprogramContext().
bool DIDescriptor::isGlobalVariable () const
isGlobalVariable - Return true if the specified tag is legal for DIGlobalVariable.
Definition at line 231 of file DebugInfo.cpp.
Referenced by llvm::CompileUnit::addSourceLine(), llvm::CompileUnit::createGlobalVariableDIE(), and getTag().
bool DIDescriptor::isImportedEntity () const
Return true if the specified tag is DW_TAG_imported_module or DW_TAG_imported_declaration.
Definition at line 319 of file DebugInfo.cpp.
Referenced by getTag().
bool DIDescriptor::isLexicalBlock () const
isLexicalBlock - Return true if the specified tag is DW_TAG_lexical_block.
Definition at line 297 of file DebugInfo.cpp.
Referenced by llvm::DwarfDebug::endFunction(), llvm::LexicalScopes::findLexicalScope(), llvm::getDISubprogram(), getTag(), and llvm::DebugInfoFinder::processLocation().
bool DIDescriptor::isLexicalBlockFile () const
isLexicalBlockFile - Return true if the specified descriptor is a lexical block with an extra file.
Definition at line 291 of file DebugInfo.cpp.
Referenced by llvm::DwarfDebug::endFunction(), llvm::LexicalScopes::findLexicalScope(), llvm::getDISubprogram(), getTag(), and llvm::DebugInfoFinder::processLocation().
bool DIDescriptor::isNameSpace () const
isNameSpace - Return true if the specified tag is DW_TAG_namespace.
Definition at line 285 of file DebugInfo.cpp.
Referenced by llvm::CompileUnit::addGlobalType(), llvm::CompileUnit::getOrCreateContextDIE(), llvm::DwarfDebug::getOrCreateSourceID(), getTag(), and llvm::DebugInfoFinder::processLocation().
bool DIDescriptor::isObjCProperty () const
isObjCProperty - Return true if the specified tag is DW_TAG_APPLE_property.
Definition at line 313 of file DebugInfo.cpp.
Referenced by llvm::CompileUnit::addSourceLine(), getTag(), and shouldCreateTypeUnit().
bool DIDescriptor::isScope () const
isScope - Return true if the specified tag is one of the scope related tag.
Definition at line 244 of file DebugInfo.cpp.
References llvm::dwarf::isType().
Referenced by llvm::DIBuilder::createClassType(), llvm::DIBuilder::createLocalVariable(), getTag(), isScopeRef(), and printDebugLoc().
bool DIDescriptor::isSubprogram () const
isSubprogram - Return true if the specified tag is legal for DISubprogram.
Definition at line 225 of file DebugInfo.cpp.
Referenced by llvm::CompileUnit::addSourceLine(), llvm::DwarfDebug::beginModule(), llvm::DIBuilder::createFunction(), llvm::DIBuilder::createMethod(), emitDebugValueComment(), llvm::DwarfDebug::endFunction(), llvm::DILexicalBlockFile::getContext(), llvm::getDISubprogram(), getFnDebugLoc(), llvm::CompileUnit::getOrCreateContextDIE(), llvm::DwarfDebug::getOrCreateSourceID(), llvm::CompileUnit::getOrCreateSubprogramDIE(), getTag(), isShareableAcrossCUs(), llvm::DwarfDebug::isSubprogramContext(), isTypeUnitScoped(), llvm::DebugInfoFinder::processLocation(), and shouldCreateTypeUnit().
bool DIDescriptor::isSubrange () const
isSubrange - Return true if the specified tag is DW_TAG_subrange_type.
Definition at line 303 of file DebugInfo.cpp.
Referenced by getTag().
bool DIDescriptor::isTemplateTypeParameter () const
isTemplateTypeParameter - Return true if the specified tag is DW_TAG_template_type_parameter.
Definition at line 262 of file DebugInfo.cpp.
Referenced by llvm::CompileUnit::addTemplateParams(), getTag(), and llvm::DebugInfoFinder::processLocation().
bool DIDescriptor::isTemplateValueParameter () const
isTemplateValueParameter - Return true if the specified tag is DW_TAG_template_value_parameter.
Definition at line 268 of file DebugInfo.cpp.
Referenced by llvm::CompileUnit::addTemplateParams(), getTag(), and llvm::DebugInfoFinder::processLocation().
bool DIDescriptor::isType () const
isType - Return true if the specified tag is legal for DIType.
Definition at line 219 of file DebugInfo.cpp.
Referenced by llvm::CompileUnit::addSourceLine(), llvm::DIBuilder::createClassType(), llvm::DIBuilder::createFriend(), llvm::DIBuilder::createInheritance(), llvm::DIBuilder::createLocalVariable(), llvm::DIBuilder::createReferenceType(), llvm::DIBuilder::createTypedef(), llvm::CompileUnit::getOrCreateContextDIE(), llvm::DwarfDebug::getOrCreateSourceID(), llvm::CompileUnit::getOrCreateTypeDIE(), getTag(), isShareableAcrossCUs(), llvm::DwarfDebug::isSubprogramContext(), isTypeRef(), llvm::DIType::isValid(), and llvm::DebugInfoFinder::processLocation().
bool DIDescriptor::isUnspecifiedParameter () const
isUnspecifiedParmeter - Return true if the specified tag is DW_TAG_unspecified_parameters.
Definition at line 238 of file DebugInfo.cpp.
Referenced by getTag(), and shouldCreateTypeUnit().
bool DIDescriptor::isVariable () const
isVariable - Return true if the specified tag is legal for DIVariable.
Definition at line 206 of file DebugInfo.cpp.
Referenced by llvm::CompileUnit::addSourceLine(), llvm::DwarfDebug::beginFunction(), llvm::DIBuilder::createLocalVariable(), llvm::DwarfDebug::endFunction(), getDebugLocEntry(), llvm::DbgVariable::getNumAddrElements(), getTag(), getTruncatedArgReg(), llvm::DIBuilder::insertDbgValueIntrinsic(), llvm::DIBuilder::insertDeclare(), llvm::DbgVariable::isBlockByrefVariable(), llvm::DebugInfoFinder::processDeclare(), llvm::DebugInfoFinder::processValue(), and llvm::DbgVariable::variableHasComplexAddress().
LLVM_EXPLICIT llvm::DIDescriptor::operator bool () const inline
Definition at line 116 of file DebugInfo.h.
llvm::DIDescriptor::operator MDNode * () const inline
Definition at line 108 of file DebugInfo.h.
References DbgNode.
bool llvm::DIDescriptor::operator!= (DIDescriptor Other) const inline
Definition at line 119 of file DebugInfo.h.
References operator==().
MDNode* llvm::DIDescriptor::operator-> () const inline
Definition at line 109 of file DebugInfo.h.
References DbgNode.
bool llvm::DIDescriptor::operator== (DIDescriptor Other) const inline
Definition at line 118 of file DebugInfo.h.
References DbgNode.
Referenced by operator!=().
void DIDescriptor::print (raw_ostream & OS) const
print - print descriptor.
print - Print descriptor.
Definition at line 1201 of file DebugInfo.cpp.
References llvm::DIScope::printInternal(), llvm::DIType::printInternal(), and llvm::dwarf::TagString().
Referenced by getTag(), INITIALIZE_PASS(), and llvm::WriteMDNodeComment().
void DIDescriptor::replaceFunctionField (unsigned Elt, Function * F) protected
Definition at line 129 of file DebugInfo.cpp.
References llvm::MDNode::replaceOperandWith().
Referenced by getFieldAs(), and llvm::DISubprogram::replaceFunction().
bool DIDescriptor::Verify () const
Definition at line 37 of file DebugInfo.cpp.
References llvm::DISubrange::Verify(), llvm::DIEnumerator::Verify(), llvm::DIBasicType::Verify(), llvm::DIDerivedType::Verify(), llvm::DICompositeType::Verify(), llvm::DIFile::Verify(), llvm::DICompileUnit::Verify(), llvm::DISubprogram::Verify(), llvm::DILexicalBlock::Verify(), llvm::DILexicalBlockFile::Verify(), llvm::DINameSpace::Verify(), llvm::DITemplateTypeParameter::Verify(), llvm::DITemplateValueParameter::Verify(), llvm::DIGlobalVariable::Verify(), llvm::DIVariable::Verify(), llvm::DIObjCProperty::Verify(), and llvm::DIImportedEntity::Verify().
Referenced by DIDescriptor(), llvm::DIFile::DIFile(), llvm::DIType::DIType(), llvm::DILexicalBlock::getColumnNumber(), llvm::DITemplateTypeParameter::getColumnNumber(), llvm::DITemplateValueParameter::getColumnNumber(), llvm::DIDerivedType::getConstant(), llvm::DISubrange::getCount(), llvm::DILocation::getDirectory(), llvm::DIBasicType::getEncoding(), llvm::DIEnumerator::getEnumValue(), llvm::DINameSpace::getLineNumber(), llvm::DIImportedEntity::getName(), llvm::DILexicalBlockFile::getScope(), llvm::DICompileUnit::getSplitDebugFilename(), llvm::DIGlobalVariable::getStaticDataMemberDeclaration(), llvm::DICompositeType::getTemplateParams(), llvm::DIObjCProperty::getType(), isContiguous(), llvm::DIVariable::isIndirect(), llvm::DISubprogram::isPrototyped(), and llvm::WriteMDNodeComment().
Friends And Related Function Documentation
template<typename T > friend class DIRef friend
Definition at line 63 of file DebugInfo.h.
Referenced by llvm::DIScope::DIScope().
Member Data Documentation
const MDNode* llvm::DIDescriptor::DbgNode protected
Definition at line 84 of file DebugInfo.h.
Referenced by llvm::DIType::isValid(), operator MDNode *(), operator->(), and operator==().
The documentation for this class was generated from the following files:
DebugInfo.h
DebugInfo.cpp