LLVM: llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy > Class Template Reference
LLVM API Documentation
llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy > Class Template Reference
#include <CallSite.h>
Public Types
typedef IterTy arg_iterator
Public Member Functions
CallSiteBase ()
CallSiteBase (CallTy *CI)
CallSiteBase (InvokeTy *II)
CallSiteBase (ValTy *II)
bool isCall () const
bool isInvoke () const
InstrTy * getInstruction () const
InstrTy * operator-> () const
LLVM_EXPLICIT operator bool () const
ValTy * getCalledValue () const
FunTy * getCalledFunction () const
void setCalledFunction (Value *V)
bool isCallee (value_use_iterator< UserTy > UI) const
ValTy * getArgument (unsigned ArgNo) const
void setArgument (unsigned ArgNo, Value *newVal)
unsigned getArgumentNo (value_use_iterator< UserTy > I) const
IterTy arg_begin () const
IterTy arg_end () const
bool arg_empty () const
unsigned arg_size () const
Type * getType () const
FunTy * getCaller () const
CallingConv::ID getCallingConv () const
void setCallingConv (CallingConv::ID CC)
const AttributeSet & getAttributes () const
void setAttributes (const AttributeSet &PAL)
bool hasFnAttr (Attribute::AttrKind A) const
Return true if this function has the given attribute.
bool paramHasAttr (unsigned i, Attribute::AttrKind A) const
Return true if the call or the callee has the given attribute.
uint16_t getParamAlignment (uint16_t i) const
Extract the alignment for a call or parameter (0=unknown).
bool isNoBuiltin () const
Return true if the call should not be treated as a call to a builtin.
bool isNoInline () const
Return true if the call should not be inlined.
void setIsNoInline (bool Value=true)
bool doesNotAccessMemory () const
Determine if the call does not access memory.
void setDoesNotAccessMemory ()
bool onlyReadsMemory () const
Determine if the call does not access or only reads memory.
void setOnlyReadsMemory ()
bool doesNotReturn () const
Determine if the call cannot return.
void setDoesNotReturn ()
bool doesNotThrow () const
Determine if the call cannot unwind.
void setDoesNotThrow ()
bool doesNotCapture (unsigned ArgNo) const
Determine whether this argument is not captured.
bool isByValArgument (unsigned ArgNo) const
Determine whether this argument is passed by value.
bool doesNotAccessMemory (unsigned ArgNo) const
bool onlyReadsMemory (unsigned ArgNo) const
bool hasArgument (const Value *Arg) const
Static Protected Member Functions
static CallSiteBase get (ValTy *V)
Protected Attributes
PointerIntPair< InstrTy *, 1, bool > I
Detailed Description
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator>
class llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >
Definition at line 46 of file CallSite.h.
Member Typedef Documentation
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> typedef IterTy llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_iterator
arg_iterator - The type of iterator to use when looping over actual arguments at this call site.
Definition at line 133 of file CallSite.h.
Constructor & Destructor Documentation
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::CallSiteBase () inline
Definition at line 50 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::get().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::CallSiteBase (CallTy * CI) inline
Definition at line 51 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::CallSiteBase (InvokeTy * II) inline
Definition at line 52 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::CallSiteBase (ValTy * II) inline
Definition at line 53 of file CallSite.h.
Member Function Documentation
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> IterTy llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_begin () const inline
arg_begin/arg_end - Return iterators corresponding to the actual argument list for a call site.
Definition at line 137 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::arg_empty(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::arg_size(), llvm::AliasAnalysis::callCapturesBefore(), llvm::objcarc::CanAlterRefCount(), CommitValueTo(), computeBytesPoppedByCallee(), llvm::createBasicAliasAnalysisPass(), llvm::createDeadArgHackingPass(), llvm::createFunctionAttrsPass(), createPrivateNonConstGlobalForString(), determinePointerReadAttrs(), FindInitTrampoline(), FirstNonDbg(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getArgument(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getArgumentNo(), llvm::objcarc::GetCallSiteClass(), getComparePred(), llvm::AliasAnalysis::getModRefInfo(), HandleCallsInBlockInlinedThroughInvoke(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::hasArgument(), INITIALIZE_PASS(), llvm::InlineFunction(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::PointerMayBeCaptured(), ReplaceFPIntrinsicWithCall(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::setArgument(), llvm::SimplifyInstruction(), and llvm::Interpreter::visitCallSite().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_empty () const inline
Definition at line 144 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> IterTy llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_end () const inline
Definition at line 143 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::arg_empty(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::arg_size(), llvm::AliasAnalysis::callCapturesBefore(), llvm::objcarc::CanAlterRefCount(), CommitValueTo(), computeBytesPoppedByCallee(), llvm::createBasicAliasAnalysisPass(), llvm::createFunctionAttrsPass(), createPrivateNonConstGlobalForString(), determinePointerReadAttrs(), FindInitTrampoline(), FirstNonDbg(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getArgument(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getArgumentNo(), llvm::objcarc::GetCallSiteClass(), getComparePred(), llvm::AliasAnalysis::getModRefInfo(), HandleCallsInBlockInlinedThroughInvoke(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::hasArgument(), INITIALIZE_PASS(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::IntrinsicLowering::LowerIntrinsicCall(), llvm::PointerMayBeCaptured(), ReplaceFPIntrinsicWithCall(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::setArgument(), llvm::SimplifyInstruction(), and llvm::Interpreter::visitCallSite().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> unsigned llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_size () const inline
Definition at line 145 of file CallSite.h.
Referenced by computeBytesPoppedByCallee(), FindInitTrampoline(), getComparePred(), INITIALIZE_PASS(), llvm::InlineFunction(), llvm::SelectionDAGBuilder::LowerCallTo(), OptimizeAwayTrappingUsesOfValue(), and llvm::Interpreter::visitCallSite().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::doesNotAccessMemory () const inline
Determine if the call does not access memory.
Definition at line 216 of file CallSite.h.
Referenced by llvm::AliasAnalysis::callCapturesBefore(), llvm::createBasicAliasAnalysisPass(), determinePointerReadAttrs(), and llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::doesNotAccessMemory().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::doesNotAccessMemory (unsigned ArgNo) const inline
Definition at line 260 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::doesNotCapture (unsigned ArgNo) const inline
Determine whether this argument is not captured.
Definition at line 251 of file CallSite.h.
Referenced by llvm::AliasAnalysis::callCapturesBefore(), llvm::createBasicAliasAnalysisPass(), and llvm::PointerMayBeCaptured().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::doesNotReturn () const inline
Determine if the call cannot return.
Definition at line 232 of file CallSite.h.
Referenced by checkInterfaceFunction(), and llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::doesNotReturn().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::doesNotThrow () const inline
Determine if the call cannot unwind.
Definition at line 240 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::doesNotThrow(), FindInitTrampoline(), llvm::InlineFunction(), and llvm::PointerMayBeCaptured().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> static CallSiteBase llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::get (ValTy * V) inline static protected
CallSiteBase::get - This static method is sort of like a constructor. It will create an appropriate call site for a Call or Invoke instruction, but it can also create a null initialized CallSiteBase object for something which is NOT a call site.
Definition at line 60 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> ValTy* llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getArgument (unsigned ArgNo) const inline
Definition at line 111 of file CallSite.h.
Referenced by AllCallersPassInValidPointerForArgument(), llvm::createBasicAliasAnalysisPass(), llvm::createDeadArgHackingPass(), GetRegistersForValue(), getStoredPointerOperand(), INITIALIZE_PASS(), llvm::PatternMatch::Argument_match< Opnd_t >::match(), OptimizeAwayTrappingUsesOfValue(), llvm::TargetLowering::ParseConstraints(), llvm::ObjectSizeOffsetVisitor::visitCallSite(), and llvm::ObjectSizeOffsetEvaluator::visitCallSite().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> unsigned llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getArgumentNo (value_use_iterator< UserTy > I) const inline
Given a value use iterator, returns the argument that corresponds to it. Iterator must actually correspond to an argument.
Definition at line 124 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> const AttributeSet& llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getAttributes () const inline
getAttributes/setAttributes - get or set the parameter attributes of the call.
Definition at line 179 of file CallSite.h.
Referenced by computeBytesPoppedByCallee(), llvm::createDeadArgHackingPass(), FindInitTrampoline(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getAttributes(), INITIALIZE_PASS(), LLVMAddInstrAttribute(), LLVMRemoveInstrAttribute(), LLVMSetInstrParamAlignment(), llvm::SelectionDAGBuilder::LowerCallTo(), OptimizeCmpExpression(), and RemoveNestAttribute().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> FunTy* llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledFunction () const inline
getCalledFunction - Return the function being called if this is a direct call, otherwise return null (if it's an indirect call).
Definition at line 93 of file CallSite.h.
Referenced by llvm::CallGraphNode::addCalledFunction(), llvm::CodeMetrics::analyzeBasicBlock(), llvm::CallGraph::CallGraph(), llvm::createAlwaysInlinerPass(), llvm::createBasicAliasAnalysisPass(), llvm::createFunctionAttrsPass(), llvm::createGlobalsModRefPass(), createPrivateNonConstGlobalForString(), determinePointerReadAttrs(), getCalledFunction(), llvm::InlineCostAnalysis::getInlineCost(), llvm::Inliner::getInlineThreshold(), llvm::AliasAnalysis::getModRefBehavior(), llvm::LibCallAliasAnalysis::getModRefInfo(), llvm::NVPTXTargetLowering::getPrototype(), INITIALIZE_PASS(), InlineCallIfPossible(), llvm::InlineFunction(), llvm::InlineCostAnalysis::isInlineViable(), llvm::Inliner::runOnSCC(), UpdateCallGraphAfterInlining(), and llvm::Interpreter::visitCallSite().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> ValTy* llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledValue () const inline
getCalledValue - Return the pointer to function that is being called.
Definition at line 85 of file CallSite.h.
Referenced by llvm::CodeMetrics::analyzeBasicBlock(), CommitValueTo(), computeBytesPoppedByCallee(), createPrivateNonConstGlobalForString(), FindInitTrampoline(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getCalledFunction(), getComparePred(), GetRegistersForValue(), INITIALIZE_PASS(), llvm::SelectionDAGBuilder::LowerCallTo(), OptimizeAwayTrappingUsesOfValue(), llvm::TargetLowering::ParseConstraints(), llvm::SimplifyInstruction(), and llvm::Interpreter::visitCallSite().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> FunTy* llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCaller () const inline
getCaller - Return the caller function for this call site
Definition at line 153 of file CallSite.h.
Referenced by llvm::InlineCostAnalysis::getInlineCost(), llvm::Inliner::getInlineThreshold(), InlineCallIfPossible(), and llvm::Inliner::runOnSCC().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> CallingConv::ID llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCallingConv () const inline
getCallingConv/setCallingConv - get or set the calling convention of the call.
Definition at line 170 of file CallSite.h.
Referenced by computeBytesPoppedByCallee(), llvm::createDeadArgHackingPass(), FindInitTrampoline(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getCallingConv(), getComparePred(), INITIALIZE_PASS(), IsCCallConvention(), and llvm::SelectionDAGBuilder::LowerCallTo().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> InstrTy* llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getInstruction () const inline
Definition at line 79 of file CallSite.h.
Referenced by llvm::CallGraphNode::addCalledFunction(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::arg_begin(), llvm::AliasAnalysis::callCapturesBefore(), checkInterfaceFunction(), CommitValueTo(), computeBytesPoppedByCallee(), llvm::createArgumentPromotionPass(), llvm::createBasicAliasAnalysisPass(), llvm::createDeadArgHackingPass(), llvm::createMergeFunctionsPass(), llvm::createObjCARCContractPass(), llvm::createObjCARCOptPass(), createPrivateNonConstGlobalForString(), llvm::Interpreter::exitCalled(), FindInitTrampoline(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getArgumentNo(), getCalledFunction(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getCalledValue(), llvm::Inliner::getInlineThreshold(), GetLocation(), llvm::AliasAnalysis::getModRefInfo(), llvm::MemoryDependenceAnalysis::getNonLocalCallDependency(), llvm::NVPTXTargetLowering::getPrototype(), GetRegistersForValue(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::hasArgument(), INITIALIZE_AG_PASS(), INITIALIZE_PASS(), llvm::InlineFunction(), llvm::InlineCostAnalysis::isInlineViable(), llvm::isInTailCallPosition(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::isInvoke(), isStructPathTBAA(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::TargetLowering::LowerCallTo(), NumRetVals(), llvm::CallSite::operator<(), PrintModRefResults(), llvm::CallGraphNode::removeCallEdgeFor(), llvm::CallGraphNode::replaceCallEdge(), llvm::Inliner::runOnSCC(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::setArgument(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::setCalledFunction(), UpdateCallGraphAfterInlining(), llvm::Interpreter::visitCallSite(), llvm::ObjectSizeOffsetVisitor::visitCallSite(), llvm::InstVisitor< ObjectSizeOffsetVisitor, SizeOffsetType >::visitCallSite(), llvm::ObjectSizeOffsetEvaluator::visitCallSite(), and llvm::PtrUseVisitor< SliceBuilder >::visitCallSite().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> uint16_t llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getParamAlignment (uint16_t i) const inline
Extract the alignment for a call or parameter (0=unknown).
Definition at line 197 of file CallSite.h.
Referenced by computeBytesPoppedByCallee(), createPrivateNonConstGlobalForString(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::getParamAlignment(), and llvm::TargetLowering::ArgListEntry::setAttributes().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> Type* llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getType () const inline
getType - Return the type of the instruction that generated this call site
Definition at line 149 of file CallSite.h.
Referenced by llvm::Interpreter::exitCalled(), GetRegistersForValue(), INITIALIZE_PASS(), and llvm::TargetLowering::ParseConstraints().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::hasArgument (const Value * Arg) const inline
hasArgument - Returns true if this CallSite passes the given Value* as an argument to the called function.
Definition at line 271 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::hasFnAttr (Attribute::AttrKind A) const inline
Return true if this function has the given attribute.
Definition at line 187 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::hasFnAttr(), hasNoAliasAttr(), and hasReturnsTwiceAttr().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isByValArgument (unsigned ArgNo) const inline
Determine whether this argument is passed by value.
Definition at line 256 of file CallSite.h.
Referenced by llvm::AliasAnalysis::callCapturesBefore(), llvm::createBasicAliasAnalysisPass(), llvm::InlineFunction(), and isSafeToEliminateVarargsCast().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isCall () const inline
isCall - true if a CallInst is enclosed. Note that !isCall() does not mean it is an InvokeInst enclosed, it also could signify a NULL Instruction pointer.
Definition at line 73 of file CallSite.h.
Referenced by createPrivateNonConstGlobalForString(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::hasArgument(), llvm::InlineCostAnalysis::isInlineViable(), llvm::PatternMatch::Argument_match< Opnd_t >::match(), and llvm::InstVisitor< ObjectSizeOffsetVisitor, SizeOffsetType >::visitCallSite().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isCallee (value_use_iterator< UserTy > UI) const inline
isCallee - Determine whether the passed iterator points to the callee operand's Use.
Definition at line 107 of file CallSite.h.
Referenced by AddressIsTaken(), llvm::createArgumentPromotionPass(), llvm::createDeadArgHackingPass(), llvm::createMergeFunctionsPass(), INITIALIZE_PASS(), and NumRetVals().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isInvoke () const inline
isInvoke - true if a InvokeInst is enclosed.
Definition at line 77 of file CallSite.h.
Referenced by createPrivateNonConstGlobalForString(), and llvm::InstVisitor< ObjectSizeOffsetVisitor, SizeOffsetType >::visitCallSite().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isNoBuiltin () const inline
Return true if the call should not be treated as a call to a builtin.
Definition at line 203 of file CallSite.h.
Referenced by getCalledFunction(), and llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::isNoBuiltin().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isNoInline () const inline
Return true if the call should not be inlined.
Definition at line 208 of file CallSite.h.
Referenced by llvm::CodeMetrics::analyzeBasicBlock(), llvm::InlineCostAnalysis::getInlineCost(), and llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::isNoInline().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::onlyReadsMemory () const inline
Determine if the call does not access or only reads memory.
Definition at line 224 of file CallSite.h.
Referenced by llvm::AliasAnalysis::callCapturesBefore(), llvm::createBasicAliasAnalysisPass(), determinePointerReadAttrs(), llvm::objcarc::GetCallSiteClass(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::onlyReadsMemory(), and llvm::PointerMayBeCaptured().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::onlyReadsMemory (unsigned ArgNo) const inline
Definition at line 264 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> LLVM_EXPLICIT llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::operator bool () const inline
Definition at line 81 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> InstrTy* llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::operator-> () const inline
Definition at line 80 of file CallSite.h.
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> bool llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::paramHasAttr (unsigned i, Attribute::AttrKind A) const inline
Return true if the call or the callee has the given attribute.
Definition at line 192 of file CallSite.h.
Referenced by computeBytesPoppedByCallee(), createPrivateNonConstGlobalForString(), determinePointerReadAttrs(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::doesNotAccessMemory(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::doesNotCapture(), getComparePred(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::isByValArgument(), llvm::isNoAliasCall(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::onlyReadsMemory(), llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::paramHasAttr(), and llvm::TargetLowering::ArgListEntry::setAttributes().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> void llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setArgument (unsigned ArgNo, Value * newVal) inline
Definition at line 116 of file CallSite.h.
Referenced by llvm::createDeadArgHackingPass(), and OptimizeAwayTrappingUsesOfValue().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> void llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setAttributes (const AttributeSet & PAL) inline
Definition at line 182 of file CallSite.h.
Referenced by INITIALIZE_PASS(), LLVMAddInstrAttribute(), LLVMRemoveInstrAttribute(), LLVMSetInstrParamAlignment(), RemoveNestAttribute(), and llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::setAttributes().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> void llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setCalledFunction (Value * V) inline
setCalledFunction - Set the callee to the specified value.
Definition at line 99 of file CallSite.h.
Referenced by createPrivateNonConstGlobalForString(), FindInitTrampoline(), INITIALIZE_PASS(), and OptimizeAwayTrappingUsesOfValue().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> void llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setCallingConv (CallingConv::ID CC) inline
Definition at line 173 of file CallSite.h.
Referenced by ChangeCalleesToFastCall(), INITIALIZE_PASS(), and llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::setCallingConv().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> void llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setDoesNotAccessMemory () inline
Definition at line 219 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::setDoesNotAccessMemory().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> void llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setDoesNotReturn () inline
Definition at line 235 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::setDoesNotReturn().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> void llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setDoesNotThrow () inline
Definition at line 243 of file CallSite.h.
Referenced by FindInitTrampoline(), and llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::setDoesNotThrow().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> void llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setIsNoInline (bool Value = true) inline
Definition at line 211 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::setIsNoInline().
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> void llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setOnlyReadsMemory () inline
Definition at line 227 of file CallSite.h.
Referenced by llvm::CallSiteBase< Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator >::setOnlyReadsMemory().
Member Data Documentation
template<typename FunTy = const Function, typename ValTy = const Value, typename UserTy = const User, typename InstrTy = const Instruction, typename CallTy = const CallInst, typename InvokeTy = const InvokeInst, typename IterTy = User::const_op_iterator> PointerIntPair<InstrTy*, 1, bool> llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::I protected
Definition at line 48 of file CallSite.h.
Referenced by llvm::CallSite::operator!=(), and llvm::CallSite::operator==().
The documentation for this class was generated from the following file:
CallSite.h