LLVM: llvm::LiveRegMatrix Class Reference
LLVM API Documentation
llvm::LiveRegMatrix Class Reference
#include <LiveRegMatrix.h>
Public Types
enum InterferenceKind { IK_Free = 0, IK_VirtReg, IK_RegUnit, IK_RegMask }
Public Member Functions
LiveRegMatrix ()
void invalidateVirtRegs ()
InterferenceKind checkInterference (LiveInterval &VirtReg, unsigned PhysReg)
void assign (LiveInterval &VirtReg, unsigned PhysReg)
void unassign (LiveInterval &VirtReg)
bool checkRegMaskInterference (LiveInterval &VirtReg, unsigned PhysReg=0)
bool checkRegUnitInterference (LiveInterval &VirtReg, unsigned PhysReg)
LiveIntervalUnion::Query & query (LiveInterval &VirtReg, unsigned RegUnit)
LiveIntervalUnion * getLiveUnions ()
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const
createPrinterPass - Get a function printer pass.
virtual void assignPassManager (PMStack &PMS, PassManagerType T)
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
Detailed Description
Definition at line 40 of file LiveRegMatrix.h.
Member Enumeration Documentation
enum llvm::LiveRegMatrix::InterferenceKind
Enumerator
IK_Free
No interference, go ahead and assign.
IK_VirtReg
Virtual register interference. There are interfering virtual registers assigned to PhysReg or its aliases. This interference could be resolved by unassigning those other virtual registers.
IK_RegUnit
Register unit interference. A fixed live range is in the way, typically argument registers for a call. This can't be resolved by unassigning other virtual registers.
IK_RegMask
RegMask interference. The live range is crossing an instruction with a regmask operand that doesn't preserve PhysReg. This typically means VirtReg is live across a call, and PhysReg isn't call-preserved.
Definition at line 82 of file LiveRegMatrix.h.
Constructor & Destructor Documentation
Live Register false LiveRegMatrix::LiveRegMatrix ()
Definition at line 39 of file LiveRegMatrix.cpp.
References llvm::AnalysisUsage::addRequiredTransitive(), llvm::LiveIntervalUnion::Array::clear(), llvm::MachineFunctionPass::getAnalysisUsage(), llvm::MCRegisterInfo::getNumRegUnits(), llvm::MachineFunction::getRegInfo(), llvm::TargetMachine::getRegisterInfo(), llvm::MachineFunction::getTarget(), i, llvm::LiveIntervalUnion::Array::init(), invalidateVirtRegs(), llvm::AnalysisUsage::setPreservesAll(), and llvm::LiveIntervalUnion::Array::size().
Member Function Documentation
void LiveRegMatrix::assign (LiveInterval & VirtReg, unsigned PhysReg)
Assign VirtReg to PhysReg. This will mark VirtReg's live range as occupied in the LiveRegMatrix and update VirtRegMap. The live range is expected to be available in PhysReg.
Definition at line 72 of file LiveRegMatrix.cpp.
References llvm::VirtRegMap::assignVirt2Phys(), llvm::dbgs(), DEBUG, llvm::VirtRegMap::hasPhys(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::LiveInterval::reg, and llvm::MachineRegisterInfo::setPhysRegUsed().
Referenced by llvm::RegAllocBase::allocatePhysRegs().
LiveRegMatrix::InterferenceKind LiveRegMatrix::checkInterference (LiveInterval & VirtReg, unsigned PhysReg)
Check for interference before assigning VirtReg to PhysReg. If this function returns IK_Free, it is legal to assign(VirtReg, PhysReg). When there is more than one kind of interference, the InterferenceKind with the highest enum value is returned.
Definition at line 138 of file LiveRegMatrix.cpp.
References llvm::LiveIntervalUnion::Query::checkInterference(), checkRegMaskInterference(), checkRegUnitInterference(), llvm::LiveRange::empty(), IK_Free, IK_RegMask, IK_RegUnit, IK_VirtReg, llvm::MCRegisterInfo::DiffListIterator::isValid(), and query().
bool LiveRegMatrix::checkRegMaskInterference (LiveInterval & VirtReg, unsigned PhysReg = 0)
Check for regmask interference only. Return true if VirtReg crosses a regmask operand that clobbers PhysReg. If PhysReg is null, check if VirtReg crosses any regmask operands.
Definition at line 99 of file LiveRegMatrix.cpp.
References llvm::LiveIntervals::checkRegMaskInterference(), llvm::BitVector::clear(), llvm::BitVector::empty(), llvm::LiveInterval::reg, and llvm::BitVector::test().
Referenced by checkInterference().
bool LiveRegMatrix::checkRegUnitInterference (LiveInterval & VirtReg, unsigned PhysReg)
Check for regunit interference only. Return true if VirtReg overlaps a fixed assignment of one of PhysRegs's register units.
Definition at line 117 of file LiveRegMatrix.cpp.
References llvm::LiveRange::empty(), llvm::LiveIntervals::getRegUnit(), llvm::LiveIntervals::getSlotIndexes(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::LiveRange::overlaps(), and llvm::LiveInterval::reg.
Referenced by checkInterference().
LiveIntervalUnion* llvm::LiveRegMatrix::getLiveUnions () inline
Directly access the live interval unions per regunit. This returns an array indexed by the regunit number.
Definition at line 143 of file LiveRegMatrix.h.
void llvm::LiveRegMatrix::invalidateVirtRegs () inline
Invalidate cached interference queries after modifying virtual register live ranges. Interference checks may return stale information unless caches are invalidated.
Definition at line 80 of file LiveRegMatrix.h.
Referenced by llvm::RegAllocBase::allocatePhysRegs(), and LiveRegMatrix().
LiveIntervalUnion::Query & LiveRegMatrix::query (LiveInterval & VirtReg, unsigned RegUnit)
Query a line of the assigned virtual register matrix directly. Use MCRegUnitIterator to enumerate all regunits in the desired PhysReg. This returns a reference to an internal Query data structure that is only valid until the next query() call.
Definition at line 130 of file LiveRegMatrix.cpp.
References llvm::LiveIntervalUnion::Query::init().
Referenced by checkInterference().
void LiveRegMatrix::unassign (LiveInterval & VirtReg)
Unassign VirtReg from its PhysReg. Assuming that VirtReg was previously assigned to a PhysReg, this undoes the assignment and updates VirtRegMap accordingly.
Definition at line 86 of file LiveRegMatrix.cpp.
References llvm::VirtRegMap::clearVirt(), llvm::dbgs(), DEBUG, llvm::VirtRegMap::getPhys(), llvm::MCRegisterInfo::DiffListIterator::isValid(), and llvm::LiveInterval::reg.
Member Data Documentation
char LiveRegMatrix::ID = 0 static
Definition at line 66 of file LiveRegMatrix.h.
The documentation for this class was generated from the following files:
LiveRegMatrix.h
LiveRegMatrix.cpp