LLVM: llvm::object::COFFObjectFile Class Reference
LLVM API Documentation
llvm::object::COFFObjectFile Class Reference
#include <COFF.h>
Public Member Functions
COFFObjectFile (MemoryBuffer *Object, error_code &ec)
virtual symbol_iterator begin_symbols () const
virtual symbol_iterator end_symbols () const
virtual symbol_iterator begin_dynamic_symbols () const
virtual symbol_iterator end_dynamic_symbols () const
virtual library_iterator begin_libraries_needed () const
virtual library_iterator end_libraries_needed () const
virtual section_iterator begin_sections () const
virtual section_iterator end_sections () const
const coff_section * getCOFFSection (section_iterator &It) const
const coff_symbol * getCOFFSymbol (symbol_iterator &It) const
const coff_relocation * getCOFFRelocation (relocation_iterator &It) const
virtual uint8_t getBytesInAddress () const
The number of bytes used to represent an address in this object file format.
virtual StringRef getFileFormatName () const
virtual unsigned getArch () const
virtual StringRef getLoadName () const
import_directory_iterator import_directory_begin () const
import_directory_iterator import_directory_end () const
error_code getHeader (const coff_file_header *&Res) const
error_code getCOFFHeader (const coff_file_header *&Res) const
error_code getPE32Header (const pe32_header *&Res) const
error_code getDataDirectory (uint32_t index, const data_directory *&Res) const
error_code getSection (int32_t index, const coff_section *&Res) const
error_code getSymbol (uint32_t index, const coff_symbol *&Res) const
template<typename T >
error_code getAuxSymbol (uint32_t index, const T *&Res) const
error_code getSymbolName (const coff_symbol *symbol, StringRef &Res) const
ArrayRef< uint8_t > getSymbolAuxData (const coff_symbol *symbol) const
error_code getSectionName (const coff_section *Sec, StringRef &Res) const
error_code getSectionContents (const coff_section *Sec, ArrayRef< uint8_t > &Res) const
error_code getRvaPtr (uint32_t Rva, uintptr_t &Res) const
error_code getHintName (uint32_t Rva, uint16_t &Hint, StringRef &Name) const
Public Member Functions inherited from llvm::object::Binary
virtual ~Binary ()
StringRef getData () const
StringRef getFileName () const
unsigned int getType () const
bool isObject () const
bool isArchive () const
bool isMachOUniversalBinary () const
bool isELF () const
bool isMachO () const
bool isCOFF () const
bool isLittleEndian () const
Static Public Member Functions
static bool classof (const Binary *v)
Static Public Member Functions inherited from llvm::object::ObjectFile
static ObjectFile * createObjectFile (StringRef ObjectPath)
Create ObjectFile from path.
static ObjectFile * createObjectFile (MemoryBuffer *Object)
static bool classof (const Binary *v)
static ObjectFile * createCOFFObjectFile (MemoryBuffer *Object)
static ObjectFile * createELFObjectFile (MemoryBuffer *Object)
static ObjectFile * createMachOObjectFile (MemoryBuffer *Object)
Protected Member Functions
virtual error_code getSymbolNext (DataRefImpl Symb, SymbolRef &Res) const
virtual error_code getSymbolName (DataRefImpl Symb, StringRef &Res) const
virtual error_code getSymbolFileOffset (DataRefImpl Symb, uint64_t &Res) const
virtual error_code getSymbolAddress (DataRefImpl Symb, uint64_t &Res) const
virtual error_code getSymbolSize (DataRefImpl Symb, uint64_t &Res) const
virtual error_code getSymbolFlags (DataRefImpl Symb, uint32_t &Res) const
virtual error_code getSymbolType (DataRefImpl Symb, SymbolRef::Type &Res) const
virtual error_code getSymbolSection (DataRefImpl Symb, section_iterator &Res) const
virtual error_code getSymbolValue (DataRefImpl Symb, uint64_t &Val) const
virtual error_code getSectionNext (DataRefImpl Sec, SectionRef &Res) const
virtual error_code getSectionName (DataRefImpl Sec, StringRef &Res) const
virtual error_code getSectionAddress (DataRefImpl Sec, uint64_t &Res) const
virtual error_code getSectionSize (DataRefImpl Sec, uint64_t &Res) const
virtual error_code getSectionContents (DataRefImpl Sec, StringRef &Res) const
virtual error_code getSectionAlignment (DataRefImpl Sec, uint64_t &Res) const
virtual error_code isSectionText (DataRefImpl Sec, bool &Res) const
virtual error_code isSectionData (DataRefImpl Sec, bool &Res) const
virtual error_code isSectionBSS (DataRefImpl Sec, bool &Res) const
virtual error_code isSectionVirtual (DataRefImpl Sec, bool &Res) const
virtual error_code isSectionZeroInit (DataRefImpl Sec, bool &Res) const
virtual error_code isSectionReadOnlyData (DataRefImpl Sec, bool &Res) const
virtual error_code isSectionRequiredForExecution (DataRefImpl Sec, bool &Res) const
virtual error_code sectionContainsSymbol (DataRefImpl Sec, DataRefImpl Symb, bool &Result) const
virtual relocation_iterator section_rel_begin (DataRefImpl Sec) const
virtual relocation_iterator section_rel_end (DataRefImpl Sec) const
virtual error_code getRelocationNext (DataRefImpl Rel, RelocationRef &Res) const
virtual error_code getRelocationAddress (DataRefImpl Rel, uint64_t &Res) const
virtual error_code getRelocationOffset (DataRefImpl Rel, uint64_t &Res) const
virtual symbol_iterator getRelocationSymbol (DataRefImpl Rel) const
virtual error_code getRelocationType (DataRefImpl Rel, uint64_t &Res) const
virtual error_code getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > &Result) const
virtual error_code getRelocationValueString (DataRefImpl Rel, SmallVectorImpl< char > &Result) const
virtual error_code getLibraryNext (DataRefImpl LibData, LibraryRef &Result) const
virtual error_code getLibraryPath (DataRefImpl LibData, StringRef &Result) const
Protected Member Functions inherited from llvm::object::ObjectFile
ObjectFile (unsigned int Type, MemoryBuffer *source)
const uint8_t * base () const
virtual error_code getSymbolAlignment (DataRefImpl Symb, uint32_t &Res) const
virtual section_iterator getRelocatedSection (DataRefImpl Sec) const
virtual error_code getRelocationHidden (DataRefImpl Rel, bool &Result) const
Protected Member Functions inherited from llvm::object::Binary
Binary (unsigned int Type, MemoryBuffer *Source)
Friends
class ImportDirectoryEntryRef
Additional Inherited Members
Protected Types inherited from llvm::object::Binary
enum {
ID_Archive, ID_MachOUniversalBinary, ID_StartObjects, ID_COFF,
ID_ELF32L, ID_ELF32B, ID_ELF64L, ID_ELF64B,
ID_MachO32L, ID_MachO32B, ID_MachO64L, ID_MachO64B,
ID_EndObjects
}
Static Protected Member Functions inherited from llvm::object::Binary
static unsigned int getELFType (bool isLE, bool is64Bits)
static unsigned int getMachOType (bool isLE, bool is64Bits)
Protected Attributes inherited from llvm::object::Binary
MemoryBuffer * Data
Detailed Description
Definition at line 223 of file Object/COFF.h.
Constructor & Destructor Documentation
COFFObjectFile::COFFObjectFile (MemoryBuffer * Object, error_code & ec)
Definition at line 453 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), llvm::object::Binary::Data, if(), llvm::object::coff_file_header::isImportLibrary(), llvm::object::pe32_header::Magic, llvm::LibFunc::memcmp, llvm::object::pe32_header::NumberOfRvaAndSize, llvm::object::coff_file_header::NumberOfSections, llvm::object::object_error::parse_failed, llvm::object::coff_file_header::PointerToSymbolTable, llvm::object::coff_file_header::SizeOfOptionalHeader, and llvm::object::object_error::success.
Referenced by llvm::object::ObjectFile::createCOFFObjectFile().
Member Function Documentation
symbol_iterator COFFObjectFile::begin_dynamic_symbols () const virtual
Implements llvm::object::ObjectFile.
Definition at line 540 of file COFFObjectFile.cpp.
References llvm::report_fatal_error().
library_iterator COFFObjectFile::begin_libraries_needed () const virtual
Implements llvm::object::ObjectFile.
Definition at line 550 of file COFFObjectFile.cpp.
References llvm::report_fatal_error().
section_iterator COFFObjectFile::begin_sections () const virtual
Implements llvm::object::ObjectFile.
Definition at line 582 of file COFFObjectFile.cpp.
References llvm::object::DataRefImpl::p, ret(), and llvm::object::ObjectFile::SectionRef.
Referenced by getRvaPtr().
symbol_iterator COFFObjectFile::begin_symbols () const virtual
Implements llvm::object::ObjectFile.
Definition at line 527 of file COFFObjectFile.cpp.
References llvm::object::DataRefImpl::p, ret(), and llvm::object::ObjectFile::SymbolRef.
static bool llvm::object::COFFObjectFile::classof (const Binary * v) inline static
Definition at line 341 of file Object/COFF.h.
References llvm::object::Binary::isCOFF().
symbol_iterator COFFObjectFile::end_dynamic_symbols () const virtual
Implements llvm::object::ObjectFile.
Definition at line 545 of file COFFObjectFile.cpp.
References llvm::report_fatal_error().
library_iterator COFFObjectFile::end_libraries_needed () const virtual
Implements llvm::object::ObjectFile.
Definition at line 555 of file COFFObjectFile.cpp.
References llvm::report_fatal_error().
section_iterator COFFObjectFile::end_sections () const virtual
Implements llvm::object::ObjectFile.
Definition at line 588 of file COFFObjectFile.cpp.
References llvm::object::coff_file_header::isImportLibrary(), llvm::object::coff_file_header::NumberOfSections, llvm::object::DataRefImpl::p, ret(), and llvm::object::ObjectFile::SectionRef.
Referenced by getRvaPtr(), and getSymbolSection().
symbol_iterator COFFObjectFile::end_symbols () const virtual
Implements llvm::object::ObjectFile.
Definition at line 533 of file COFFObjectFile.cpp.
References llvm::object::DataRefImpl::p, ret(), and llvm::object::ObjectFile::SymbolRef.
unsigned COFFObjectFile::getArch () const virtual
Implements llvm::object::ObjectFile.
Definition at line 611 of file COFFObjectFile.cpp.
References llvm::COFF::IMAGE_FILE_MACHINE_AMD64, llvm::COFF::IMAGE_FILE_MACHINE_I386, llvm::object::coff_file_header::Machine, llvm::Triple::UnknownArch, llvm::Triple::x86, and llvm::Triple::x86_64.
Referenced by getBytesInAddress().
template<typename T > error_code llvm::object::COFFObjectFile::getAuxSymbol (uint32_t index, const T *& Res) const inline
Definition at line 325 of file Object/COFF.h.
References s.
uint8_t COFFObjectFile::getBytesInAddress () const virtual
The number of bytes used to represent an address in this object file format.
Implements llvm::object::ObjectFile.
Definition at line 596 of file COFFObjectFile.cpp.
References getArch(), and llvm::Triple::x86_64.
error_code COFFObjectFile::getCOFFHeader (const coff_file_header *& Res) const
Definition at line 628 of file COFFObjectFile.cpp.
References llvm::object::object_error::success.
Referenced by getHeader().
const coff_relocation * COFFObjectFile::getCOFFRelocation (relocation_iterator & It) const
Definition at line 800 of file COFFObjectFile.cpp.
const coff_section * COFFObjectFile::getCOFFSection (section_iterator & It) const
Definition at line 792 of file COFFObjectFile.cpp.
Referenced by getRvaPtr().
const coff_symbol * COFFObjectFile::getCOFFSymbol (symbol_iterator & It) const
Definition at line 796 of file COFFObjectFile.cpp.
error_code COFFObjectFile::getDataDirectory (uint32_t index, const data_directory *& Res) const
Definition at line 638 of file COFFObjectFile.cpp.
References index, llvm::object::pe32_header::NumberOfRvaAndSize, llvm::object::object_error::parse_failed, and llvm::object::object_error::success.
Referenced by getHintName().
StringRef COFFObjectFile::getFileFormatName () const virtual
Implements llvm::object::ObjectFile.
Definition at line 600 of file COFFObjectFile.cpp.
References llvm::COFF::IMAGE_FILE_MACHINE_AMD64, llvm::COFF::IMAGE_FILE_MACHINE_I386, and llvm::object::coff_file_header::Machine.
error_code COFFObjectFile::getHeader (const coff_file_header *& Res) const
Definition at line 624 of file COFFObjectFile.cpp.
References getCOFFHeader().
error_code COFFObjectFile::getHintName (uint32_t Rva, uint16_t & Hint, StringRef & Name) const
Definition at line 415 of file COFFObjectFile.cpp.
References getDataDirectory(), getRvaPtr(), llvm::COFF::IMPORT_TABLE, llvm::object::object_error::parse_failed, llvm::object::data_directory::RelativeVirtualAddress, llvm::object::data_directory::Size, and llvm::object::object_error::success.
Referenced by getRvaPtr().
error_code COFFObjectFile::getLibraryNext (DataRefImpl LibData, LibraryRef & Result) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 875 of file COFFObjectFile.cpp.
References llvm::report_fatal_error().
error_code COFFObjectFile::getLibraryPath (DataRefImpl LibData, StringRef & Result) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 880 of file COFFObjectFile.cpp.
References llvm::object::ImportDirectoryEntryRef::operator==(), and llvm::report_fatal_error().
StringRef COFFObjectFile::getLoadName () const virtual
For shared objects, returns the name which this object should be loaded from at runtime. This corresponds to DT_SONAME on ELF and LC_ID_DYLIB (install name) on MachO.
Implements llvm::object::ObjectFile.
Definition at line 560 of file COFFObjectFile.cpp.
error_code COFFObjectFile::getPE32Header (const pe32_header *& Res) const
Definition at line 633 of file COFFObjectFile.cpp.
References llvm::object::object_error::success.
error_code COFFObjectFile::getRelocationAddress (DataRefImpl Rel, uint64_t & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 770 of file COFFObjectFile.cpp.
References llvm::report_fatal_error().
error_code COFFObjectFile::getRelocationNext (DataRefImpl Rel, RelocationRef & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 763 of file COFFObjectFile.cpp.
References llvm::object::DataRefImpl::p, llvm::object::ObjectFile::RelocationRef, and llvm::object::object_error::success.
error_code COFFObjectFile::getRelocationOffset (DataRefImpl Rel, uint64_t & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 774 of file COFFObjectFile.cpp.
References llvm::object::object_error::success, and llvm::object::coff_relocation::VirtualAddress.
symbol_iterator COFFObjectFile::getRelocationSymbol (DataRefImpl Rel) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 779 of file COFFObjectFile.cpp.
References llvm::object::DataRefImpl::p, llvm::object::ObjectFile::SymbolRef, and llvm::object::coff_relocation::SymbolTableIndex.
error_code COFFObjectFile::getRelocationType (DataRefImpl Rel, uint64_t & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 785 of file COFFObjectFile.cpp.
References llvm::object::object_error::success, and llvm::object::coff_relocation::Type.
error_code COFFObjectFile::getRelocationTypeName (DataRefImpl Rel, SmallVectorImpl< char > & Result) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 808 of file COFFObjectFile.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::StringRef::begin(), llvm::StringRef::end(), llvm::COFF::IMAGE_FILE_MACHINE_AMD64, llvm::COFF::IMAGE_FILE_MACHINE_I386, llvm::COFF::IMAGE_REL_AMD64_ABSOLUTE, llvm::COFF::IMAGE_REL_AMD64_ADDR32, llvm::COFF::IMAGE_REL_AMD64_ADDR32NB, llvm::COFF::IMAGE_REL_AMD64_ADDR64, llvm::COFF::IMAGE_REL_AMD64_PAIR, llvm::COFF::IMAGE_REL_AMD64_REL32, llvm::COFF::IMAGE_REL_AMD64_REL32_1, llvm::COFF::IMAGE_REL_AMD64_REL32_2, llvm::COFF::IMAGE_REL_AMD64_REL32_3, llvm::COFF::IMAGE_REL_AMD64_REL32_4, llvm::COFF::IMAGE_REL_AMD64_REL32_5, llvm::COFF::IMAGE_REL_AMD64_SECREL, llvm::COFF::IMAGE_REL_AMD64_SECREL7, llvm::COFF::IMAGE_REL_AMD64_SECTION, llvm::COFF::IMAGE_REL_AMD64_SREL32, llvm::COFF::IMAGE_REL_AMD64_SSPAN32, llvm::COFF::IMAGE_REL_AMD64_TOKEN, llvm::COFF::IMAGE_REL_I386_ABSOLUTE, llvm::COFF::IMAGE_REL_I386_DIR16, llvm::COFF::IMAGE_REL_I386_DIR32, llvm::COFF::IMAGE_REL_I386_DIR32NB, llvm::COFF::IMAGE_REL_I386_REL16, llvm::COFF::IMAGE_REL_I386_REL32, llvm::COFF::IMAGE_REL_I386_SECREL, llvm::COFF::IMAGE_REL_I386_SECREL7, llvm::COFF::IMAGE_REL_I386_SECTION, llvm::COFF::IMAGE_REL_I386_SEG12, llvm::COFF::IMAGE_REL_I386_TOKEN, LLVM_COFF_SWITCH_RELOC_TYPE_NAME, llvm::object::coff_file_header::Machine, llvm::object::object_error::success, and llvm::object::coff_relocation::Type.
error_code COFFObjectFile::getRelocationValueString (DataRefImpl Rel, SmallVectorImpl< char > & Result) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 862 of file COFFObjectFile.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::StringRef::begin(), llvm::StringRef::end(), getSymbol(), getSymbolName(), llvm::object::DataRefImpl::p, llvm::object::object_error::success, and llvm::object::coff_relocation::SymbolTableIndex.
error_code COFFObjectFile::getRvaPtr (uint32_t Rva, uintptr_t & Res) const
Definition at line 394 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), begin_sections(), end_sections(), getCOFFSection(), getHintName(), i, llvm::object::object_error::parse_failed, llvm::object::coff_section::PointerToRawData, llvm::ARMBuildAttrs::Section, llvm::object::object_error::success, llvm::object::coff_section::VirtualAddress, and llvm::object::coff_section::VirtualSize.
Referenced by getHintName().
error_code COFFObjectFile::getSection (int32_t index, const coff_section *& Res) const
Definition at line 647 of file COFFObjectFile.cpp.
References llvm::COFF::IMAGE_SYM_ABSOLUTE, llvm::COFF::IMAGE_SYM_DEBUG, llvm::COFF::IMAGE_SYM_UNDEFINED, llvm::object::object_error::parse_failed, llvm::object::object_error::success, and llvm::object::object_error::unexpected_eof.
Referenced by getSymbolAddress(), getSymbolFileOffset(), getSymbolSection(), getSymbolSize(), getSymbolType(), and sectionContainsSymbol().
error_code COFFObjectFile::getSectionAddress (DataRefImpl Sec, uint64_t & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 245 of file COFFObjectFile.cpp.
References llvm::object::object_error::success, and llvm::object::coff_section::VirtualAddress.
error_code COFFObjectFile::getSectionAlignment (DataRefImpl Sec, uint64_t & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 268 of file COFFObjectFile.cpp.
References llvm::object::coff_section::Characteristics, llvm::object::object_error::parse_failed, and llvm::object::object_error::success.
virtual error_code llvm::object::COFFObjectFile::getSectionContents (DataRefImpl Sec, StringRef & Res) const protected virtual
Implements llvm::object::ObjectFile.
Referenced by getSectionSize(), and getSymbolAuxData().
error_code llvm::object::COFFObjectFile::getSectionContents (const coff_section * Sec, ArrayRef< uint8_t > & Res) const
virtual error_code llvm::object::COFFObjectFile::getSectionName (DataRefImpl Sec, StringRef & Res) const protected virtual
Implements llvm::object::ObjectFile.
Referenced by getSectionNext(), and getSymbolAuxData().
error_code llvm::object::COFFObjectFile::getSectionName (const coff_section * Sec, StringRef & Res) const
error_code COFFObjectFile::getSectionNext (DataRefImpl Sec, SectionRef & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 230 of file COFFObjectFile.cpp.
References getSectionName(), llvm::object::DataRefImpl::p, llvm::object::ObjectFile::SectionRef, and llvm::object::object_error::success.
error_code COFFObjectFile::getSectionSize (DataRefImpl Sec, uint64_t & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 252 of file COFFObjectFile.cpp.
References llvm::ArrayRef< T >::data(), getSectionContents(), llvm::ArrayRef< T >::size(), llvm::object::coff_section::SizeOfRawData, and llvm::object::object_error::success.
error_code COFFObjectFile::getSymbol (uint32_t index, const coff_symbol *& Res) const
Definition at line 673 of file COFFObjectFile.cpp.
References getSymbolName(), index, llvm::object::coff_symbol::Name, llvm::object::coff_symbol::StringTableOffset::Offset, llvm::object::coff_symbol::Offset, llvm::object::object_error::parse_failed, llvm::object::coff_symbol::ShortName, llvm::object::object_error::success, and llvm::object::coff_symbol::StringTableOffset::Zeroes.
Referenced by getRelocationValueString().
error_code COFFObjectFile::getSymbolAddress (DataRefImpl Symb, uint64_t & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 125 of file COFFObjectFile.cpp.
References getSection(), llvm::COFF::IMAGE_SYM_UNDEFINED, llvm::ARMBuildAttrs::Section, llvm::object::coff_symbol::SectionNumber, llvm::object::object_error::success, llvm::object::UnknownAddressOrSize, llvm::object::coff_symbol::Value, and llvm::object::coff_section::VirtualAddress.
ArrayRef< uint8_t > COFFObjectFile::getSymbolAuxData (const coff_symbol * symbol) const
Definition at line 701 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), llvm::object::Binary::Data, llvm::StringRef::getAsInteger(), llvm::MemoryBuffer::getBufferEnd(), getSectionContents(), getSectionName(), llvm::object::coff_section::Name, llvm::object::coff_symbol::NumberOfAuxSymbols, llvm::object::coff_file_header::NumberOfSymbols, llvm::object::DataRefImpl::p, llvm::object::object_error::parse_failed, llvm::object::coff_section::PointerToRawData, llvm::object::coff_file_header::PointerToSymbolTable, llvm::report_fatal_error(), llvm::object::coff_section::SizeOfRawData, llvm::StringRef::substr(), and llvm::object::object_error::success.
error_code COFFObjectFile::getSymbolFileOffset (DataRefImpl Symb, uint64_t & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 109 of file COFFObjectFile.cpp.
References getSection(), llvm::COFF::IMAGE_SYM_UNDEFINED, llvm::object::coff_section::PointerToRawData, llvm::ARMBuildAttrs::Section, llvm::object::coff_symbol::SectionNumber, llvm::object::object_error::success, llvm::object::UnknownAddressOrSize, and llvm::object::coff_symbol::Value.
error_code COFFObjectFile::getSymbolFlags (DataRefImpl Symb, uint32_t & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 167 of file COFFObjectFile.cpp.
References llvm::COFF::IMAGE_SYM_ABSOLUTE, llvm::COFF::IMAGE_SYM_CLASS_EXTERNAL, llvm::COFF::IMAGE_SYM_CLASS_WEAK_EXTERNAL, llvm::COFF::IMAGE_SYM_UNDEFINED, llvm::object::coff_symbol::SectionNumber, llvm::object::coff_symbol::StorageClass, and llvm::object::object_error::success.
virtual error_code llvm::object::COFFObjectFile::getSymbolName (DataRefImpl Symb, StringRef & Res) const protected virtual
Implements llvm::object::ObjectFile.
Referenced by getRelocationValueString(), getSymbol(), and getSymbolNext().
error_code llvm::object::COFFObjectFile::getSymbolName (const coff_symbol * symbol, StringRef & Res) const
error_code COFFObjectFile::getSymbolNext (DataRefImpl Symb, SymbolRef & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 94 of file COFFObjectFile.cpp.
References getSymbolName(), llvm::object::coff_symbol::NumberOfAuxSymbols, llvm::object::DataRefImpl::p, llvm::object::object_error::success, and llvm::object::ObjectFile::SymbolRef.
error_code COFFObjectFile::getSymbolSection (DataRefImpl Symb, section_iterator & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 210 of file COFFObjectFile.cpp.
References end_sections(), getSection(), llvm::COFF::IMAGE_SYM_UNDEFINED, llvm::object::DataRefImpl::p, llvm::object::coff_symbol::SectionNumber, llvm::object::ObjectFile::SectionRef, and llvm::object::object_error::success.
error_code COFFObjectFile::getSymbolSize (DataRefImpl Symb, uint64_t & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 191 of file COFFObjectFile.cpp.
References getSection(), llvm::COFF::IMAGE_SYM_UNDEFINED, llvm::ARMBuildAttrs::Section, llvm::object::coff_symbol::SectionNumber, llvm::object::coff_section::SizeOfRawData, llvm::object::object_error::success, llvm::object::UnknownAddressOrSize, and llvm::object::coff_symbol::Value.
error_code COFFObjectFile::getSymbolType (DataRefImpl Symb, SymbolRef::Type & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 141 of file COFFObjectFile.cpp.
References Characteristics, llvm::object::coff_section::Characteristics, llvm::object::coff_symbol::getComplexType(), getSection(), llvm::COFF::IMAGE_SYM_CLASS_EXTERNAL, llvm::COFF::IMAGE_SYM_DTYPE_FUNCTION, llvm::COFF::IMAGE_SYM_UNDEFINED, llvm::ARMBuildAttrs::Section, llvm::object::coff_symbol::SectionNumber, llvm::object::SymbolRef::ST_Data, llvm::object::SymbolRef::ST_Function, llvm::object::SymbolRef::ST_Other, llvm::object::SymbolRef::ST_Unknown, llvm::object::coff_symbol::StorageClass, and llvm::object::object_error::success.
error_code COFFObjectFile::getSymbolValue (DataRefImpl Symb, uint64_t & Val) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 225 of file COFFObjectFile.cpp.
References llvm::report_fatal_error().
import_directory_iterator COFFObjectFile::import_directory_begin () const
Definition at line 565 of file COFFObjectFile.cpp.
References ImportDirectoryEntryRef, and llvm::object::DataRefImpl::p.
import_directory_iterator COFFObjectFile::import_directory_end () const
Definition at line 571 of file COFFObjectFile.cpp.
References ImportDirectoryEntryRef, and llvm::object::DataRefImpl::p.
error_code COFFObjectFile::isSectionBSS (DataRefImpl Sec, bool & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 291 of file COFFObjectFile.cpp.
References llvm::object::coff_section::Characteristics, and llvm::object::object_error::success.
error_code COFFObjectFile::isSectionData (DataRefImpl Sec, bool & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 284 of file COFFObjectFile.cpp.
References llvm::object::coff_section::Characteristics, and llvm::object::object_error::success.
error_code COFFObjectFile::isSectionReadOnlyData (DataRefImpl Sec, bool & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 319 of file COFFObjectFile.cpp.
References llvm::object::object_error::success.
error_code COFFObjectFile::isSectionRequiredForExecution (DataRefImpl Sec, bool & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 298 of file COFFObjectFile.cpp.
References llvm::object::object_error::success.
error_code COFFObjectFile::isSectionText (DataRefImpl Sec, bool & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 277 of file COFFObjectFile.cpp.
References llvm::object::coff_section::Characteristics, and llvm::object::object_error::success.
error_code COFFObjectFile::isSectionVirtual (DataRefImpl Sec, bool & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 305 of file COFFObjectFile.cpp.
References llvm::object::coff_section::Characteristics, and llvm::object::object_error::success.
error_code COFFObjectFile::isSectionZeroInit (DataRefImpl Sec, bool & Res) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 312 of file COFFObjectFile.cpp.
References llvm::object::object_error::success.
relocation_iterator COFFObjectFile::section_rel_begin (DataRefImpl Sec) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 340 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), llvm::object::coff_section::NumberOfRelocations, llvm::object::DataRefImpl::p, llvm::object::coff_section::PointerToRelocations, llvm::object::ObjectFile::RelocationRef, and ret().
relocation_iterator COFFObjectFile::section_rel_end (DataRefImpl Sec) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 351 of file COFFObjectFile.cpp.
References llvm::object::ObjectFile::base(), llvm::object::Binary::Data, llvm::object::coff_section::NumberOfRelocations, llvm::object::coff_file_header::NumberOfSymbols, llvm::object::DataRefImpl::p, llvm::object::object_error::parse_failed, llvm::object::coff_section::PointerToRelocations, llvm::object::coff_file_header::PointerToSymbolTable, llvm::object::ObjectFile::RelocationRef, ret(), and llvm::object::object_error::success.
error_code COFFObjectFile::sectionContainsSymbol (DataRefImpl Sec, DataRefImpl Symb, bool & Result) const protected virtual
Implements llvm::object::ObjectFile.
Definition at line 326 of file COFFObjectFile.cpp.
References getSection(), llvm::object::coff_symbol::SectionNumber, and llvm::object::object_error::success.
Friends And Related Function Documentation
friend class ImportDirectoryEntryRef friend
Definition at line 225 of file Object/COFF.h.
Referenced by llvm::object::ImportDirectoryEntryRef::getNext(), import_directory_begin(), and import_directory_end().
The documentation for this class was generated from the following files:
Object/COFF.h
COFFObjectFile.cpp