LLVM: llvm::User::value_op_iterator Class Reference
LLVM API Documentation
llvm::User::value_op_iterator Class Reference
#include <User.h>
Public Member Functions
value_op_iterator (Use *U)
bool operator== (const value_op_iterator &x) const
bool operator!= (const value_op_iterator &x) const
value_op_iterator & operator++ ()
Iterator traversal: forward iteration only.
value_op_iterator operator++ (int)
Value * operator* () const
Retrieve a pointer to the current Value.
Value * operator-> () const
Detailed Description
Convenience iterator for directly iterating over the Values in the OperandList
Definition at line 123 of file User.h.
Constructor & Destructor Documentation
llvm::User::value_op_iterator::value_op_iterator (Use * U) inline explicit
Definition at line 127 of file User.h.
Referenced by llvm::User::value_op_begin(), and llvm::User::value_op_end().
Member Function Documentation
bool llvm::User::value_op_iterator::operator!= (const value_op_iterator & x) const inline
Definition at line 132 of file User.h.
References operator==().
Value* llvm::User::value_op_iterator::operator* () const inline
Retrieve a pointer to the current Value.
Definition at line 146 of file User.h.
Referenced by operator->().
value_op_iterator& llvm::User::value_op_iterator::operator++ () inline
Iterator traversal: forward iteration only.
Definition at line 137 of file User.h.
value_op_iterator llvm::User::value_op_iterator::operator++ (int) inline
Definition at line 141 of file User.h.
Value* llvm::User::value_op_iterator::operator-> () const inline
Definition at line 150 of file User.h.
References operator*().
bool llvm::User::value_op_iterator::operator== (const value_op_iterator & x) const inline
Definition at line 129 of file User.h.
Referenced by operator!=().
The documentation for this class was generated from the following file:
User.h