LLVM: llvm::po_iterator_storage< SetType, External > Class Template Reference
LLVM API Documentation
llvm::po_iterator_storage< SetType, External > Class Template Reference
Default po_iterator_storage implementation with an internal set object.
#include <PostOrderIterator.h>
Public Member Functions
template<typename NodeType >
bool insertEdge (NodeType *From, NodeType *To)
template<typename NodeType >
void finishPostorder (NodeType *BB)
Detailed Description
template<class SetType, bool External>
class llvm::po_iterator_storage< SetType, External >
Default po_iterator_storage implementation with an internal set object.
Definition at line 54 of file PostOrderIterator.h.
Member Function Documentation
template<class SetType, bool External> template<typename NodeType > void llvm::po_iterator_storage< SetType, External >::finishPostorder (NodeType * BB) inline
Definition at line 65 of file PostOrderIterator.h.
Referenced by llvm::po_iterator_storage< LoopBlocksTraversal, true >::insertEdge(), and llvm::po_iterator< T, SetType, true >::operator++().
template<class SetType, bool External> template<typename NodeType > bool llvm::po_iterator_storage< SetType, External >::insertEdge (NodeType * From, NodeType * To) inline
Definition at line 59 of file PostOrderIterator.h.
Referenced by llvm::LoopBlocksTraversal::finishPostorder().
The documentation for this class was generated from the following file:
PostOrderIterator.h