LLVM: llvm::ObjectImageCommon Class Reference
LLVM API Documentation
llvm::ObjectImageCommon Class Reference
#include <ObjectImageCommon.h>
Public Member Functions
ObjectImageCommon (ObjectBuffer *Input)
virtual ~ObjectImageCommon ()
virtual object::symbol_iterator begin_symbols () const
virtual object::symbol_iterator end_symbols () const
virtual object::section_iterator begin_sections () const
virtual object::section_iterator end_sections () const
virtual unsigned getArch () const
virtual StringRef getData () const
virtual object::ObjectFile * getObjectFile () const
virtual void updateSectionAddress (const object::SectionRef &Sec, uint64_t Addr)
virtual void updateSymbolAddress (const object::SymbolRef &Sym, uint64_t Addr)
virtual void registerWithDebugger ()
virtual void deregisterWithDebugger ()
Public Member Functions inherited from llvm::ObjectImage
ObjectImage (ObjectBuffer *Input)
virtual ~ObjectImage ()
Protected Member Functions
ObjectImageCommon (ObjectBuffer *Input, object::ObjectFile *Obj)
Protected Attributes
object::ObjectFile * ObjFile
Protected Attributes inherited from llvm::ObjectImage
OwningPtr< ObjectBuffer > Buffer
Detailed Description
Definition at line 23 of file ObjectImageCommon.h.
Constructor & Destructor Documentation
llvm::ObjectImageCommon::ObjectImageCommon (ObjectBuffer * Input, object::ObjectFile * Obj) inline protected
Definition at line 33 of file ObjectImageCommon.h.
llvm::ObjectImageCommon::ObjectImageCommon (ObjectBuffer * Input) inline
Definition at line 40 of file ObjectImageCommon.h.
References llvm::ObjectImage::Buffer, and llvm::object::ObjectFile::createObjectFile().
virtual llvm::ObjectImageCommon::~ObjectImageCommon () inline virtual
Definition at line 45 of file ObjectImageCommon.h.
References ObjFile.
Member Function Documentation
virtual object::section_iterator llvm::ObjectImageCommon::begin_sections () const inline virtual
Implements llvm::ObjectImage.
Definition at line 52 of file ObjectImageCommon.h.
References llvm::object::ObjectFile::begin_sections().
virtual object::symbol_iterator llvm::ObjectImageCommon::begin_symbols () const inline virtual
Implements llvm::ObjectImage.
Definition at line 47 of file ObjectImageCommon.h.
References llvm::object::ObjectFile::begin_symbols().
virtual void llvm::ObjectImageCommon::deregisterWithDebugger () inline virtual
Implements llvm::ObjectImage.
Definition at line 73 of file ObjectImageCommon.h.
virtual object::section_iterator llvm::ObjectImageCommon::end_sections () const inline virtual
Implements llvm::ObjectImage.
Definition at line 54 of file ObjectImageCommon.h.
References llvm::object::ObjectFile::end_sections().
virtual object::symbol_iterator llvm::ObjectImageCommon::end_symbols () const inline virtual
Implements llvm::ObjectImage.
Definition at line 49 of file ObjectImageCommon.h.
References llvm::object::ObjectFile::end_symbols().
virtual unsigned llvm::ObjectImageCommon::getArch () const inline virtual
Implements llvm::ObjectImage.
Definition at line 57 of file ObjectImageCommon.h.
References llvm::object::ObjectFile::getArch().
virtual StringRef llvm::ObjectImageCommon::getData () const inline virtual
Implements llvm::ObjectImage.
Definition at line 60 of file ObjectImageCommon.h.
References llvm::object::Binary::getData().
virtual object::ObjectFile* llvm::ObjectImageCommon::getObjectFile () const inline virtual
Implements llvm::ObjectImage.
Definition at line 62 of file ObjectImageCommon.h.
References ObjFile.
virtual void llvm::ObjectImageCommon::registerWithDebugger () inline virtual
Implements llvm::ObjectImage.
Definition at line 72 of file ObjectImageCommon.h.
virtual void llvm::ObjectImageCommon::updateSectionAddress (const object::SectionRef & Sec, uint64_t Addr) inline virtual
Implements llvm::ObjectImage.
Definition at line 66 of file ObjectImageCommon.h.
virtual void llvm::ObjectImageCommon::updateSymbolAddress (const object::SymbolRef & Sym, uint64_t Addr) inline virtual
Implements llvm::ObjectImage.
Definition at line 68 of file ObjectImageCommon.h.
Member Data Documentation
object::ObjectFile* llvm::ObjectImageCommon::ObjFile protected
Definition at line 29 of file ObjectImageCommon.h.
Referenced by getObjectFile(), and ~ObjectImageCommon().
The documentation for this class was generated from the following files:
ObjectImageCommon.h
RuntimeDyld.cpp