LLVM: llvm::SlabAllocator Class Reference
LLVM API Documentation
llvm::SlabAllocator Class Reference abstract
#include <Allocator.h>
Public Member Functions
virtual ~SlabAllocator ()
virtual MemSlab * Allocate (size_t Size)=0
virtual void Deallocate (MemSlab *Slab)=0
Detailed Description
SlabAllocator - This class can be used to parameterize the underlying allocation strategy for the bump allocator. In particular, this is used by the JIT to allocate contiguous swathes of executable memory. The interface uses MemSlab's instead of void *'s so that the allocator doesn't have to remember the size of the pointer it allocated.
Definition at line 64 of file Allocator.h.
Constructor & Destructor Documentation
llvm::SlabAllocator::~SlabAllocator () virtual
Definition at line 174 of file Allocator.cpp.
Member Function Documentation
virtual MemSlab* llvm::SlabAllocator::Allocate (size_t Size) pure virtual
Implemented in llvm::MallocSlabAllocator.
Referenced by llvm::MallocSlabAllocator::Allocate(), llvm::BumpPtrAllocator::Allocate(), and llvm::BumpPtrAllocator::~BumpPtrAllocator().
virtual void llvm::SlabAllocator::Deallocate (MemSlab * Slab) pure virtual
Implemented in llvm::MallocSlabAllocator.
Referenced by llvm::MallocSlabAllocator::Deallocate(), and llvm::BumpPtrAllocator::~BumpPtrAllocator().
The documentation for this class was generated from the following files:
Allocator.h
Allocator.cpp