LLVM: llvm::ARMConstantPoolValue Class Reference
LLVM API Documentation
llvm::ARMConstantPoolValue Class Reference
#include <ARMConstantPoolValue.h>
Public Member Functions
virtual ~ARMConstantPoolValue ()
ARMCP::ARMCPModifier getModifier () const
const char * getModifierText () const
bool hasModifier () const
bool mustAddCurrentAddress () const
unsigned getLabelId () const
unsigned char getPCAdjustment () const
bool isGlobalValue () const
bool isExtSymbol () const
bool isBlockAddress () const
bool isLSDA () const
bool isMachineBasicBlock () const
virtual unsigned getRelocationInfo () const
virtual int getExistingMachineCPValue (MachineConstantPool *CP, unsigned Alignment)
virtual void addSelectionDAGCSEId (FoldingSetNodeID &ID)
virtual bool hasSameValue (ARMConstantPoolValue *ACPV)
bool equals (const ARMConstantPoolValue *A) const
virtual void print (raw_ostream &O) const
print - Implement operator<<
void print (raw_ostream *O) const
void dump () const
Public Member Functions inherited from llvm::MachineConstantPoolValue
MachineConstantPoolValue (Type *ty)
virtual ~MachineConstantPoolValue ()
Type * getType () const
Protected Member Functions
ARMConstantPoolValue (Type *Ty, unsigned id, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress)
ARMConstantPoolValue (LLVMContext &C, unsigned id, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress)
template<typename Derived >
int getExistingMachineCPValueImpl (MachineConstantPool *CP, unsigned Alignment)
Detailed Description
ARMConstantPoolValue - ARM specific constantpool value. This is used to represent PC-relative displacement between the address of the load instruction and the constant being loaded, i.e. (&GV-(LPIC+8)).
Definition at line 52 of file ARMConstantPoolValue.h.
Constructor & Destructor Documentation
ARMConstantPoolValue::ARMConstantPoolValue (Type * Ty, unsigned id, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress) protected
Definition at line 29 of file ARMConstantPoolValue.cpp.
Referenced by print(), llvm::ARMConstantPoolConstant::print(), and llvm::ARMConstantPoolSymbol::print().
ARMConstantPoolValue::ARMConstantPoolValue (LLVMContext & C, unsigned id, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress) protected
Definition at line 38 of file ARMConstantPoolValue.cpp.
ARMConstantPoolValue::~ARMConstantPoolValue () virtual
Definition at line 47 of file ARMConstantPoolValue.cpp.
Member Function Documentation
void ARMConstantPoolValue::addSelectionDAGCSEId (FoldingSetNodeID & ID) virtual
Implements llvm::MachineConstantPoolValue.
Reimplemented in llvm::ARMConstantPoolMBB, llvm::ARMConstantPoolSymbol, and llvm::ARMConstantPoolConstant.
Definition at line 69 of file ARMConstantPoolValue.cpp.
References llvm::FoldingSetNodeID::AddInteger().
Referenced by llvm::ARMConstantPoolConstant::addSelectionDAGCSEId(), llvm::ARMConstantPoolSymbol::addSelectionDAGCSEId(), and llvm::ARMConstantPoolMBB::addSelectionDAGCSEId().
void ARMConstantPoolValue::dump () const
Definition at line 89 of file ARMConstantPoolValue.cpp.
References llvm::errs().
bool llvm::ARMConstantPoolValue::equals (const ARMConstantPoolValue * A) const inline
Definition at line 117 of file ARMConstantPoolValue.h.
Referenced by llvm::ARMConstantPoolConstant::equals(), llvm::ARMConstantPoolSymbol::equals(), and llvm::ARMConstantPoolMBB::equals().
int ARMConstantPoolValue::getExistingMachineCPValue (MachineConstantPool * CP, unsigned Alignment) virtual
Implements llvm::MachineConstantPoolValue.
Reimplemented in llvm::ARMConstantPoolMBB, llvm::ARMConstantPoolSymbol, and llvm::ARMConstantPoolConstant.
Definition at line 63 of file ARMConstantPoolValue.cpp.
References llvm_unreachable.
template<typename Derived > int llvm::ARMConstantPoolValue::getExistingMachineCPValueImpl (MachineConstantPool * CP, unsigned Alignment) inline protected
Definition at line 70 of file ARMConstantPoolValue.h.
References llvm::MachineConstantPool::getConstants(), i, and if().
unsigned llvm::ARMConstantPoolValue::getLabelId () const inline
Definition at line 97 of file ARMConstantPoolValue.h.
Referenced by llvm::ARMJITInfo::emitFunctionStub(), and llvm::ARMAsmPrinter::EmitMachineConstantPoolValue().
ARMCP::ARMCPModifier llvm::ARMConstantPoolValue::getModifier () const inline
Definition at line 91 of file ARMConstantPoolValue.h.
Referenced by llvm::ARMAsmPrinter::EmitMachineConstantPoolValue().
const char * ARMConstantPoolValue::getModifierText () const
Definition at line 49 of file ARMConstantPoolValue.cpp.
References llvm::ARMCP::GOT, llvm::ARMCP::GOTOFF, llvm::ARMCP::GOTTPOFF, llvm_unreachable, llvm::ARMCP::no_modifier, llvm::ARMCP::TLSGD, and llvm::ARMCP::TPOFF.
Referenced by print().
unsigned char llvm::ARMConstantPoolValue::getPCAdjustment () const inline
Definition at line 98 of file ARMConstantPoolValue.h.
Referenced by llvm::ARMJITInfo::emitFunctionStub(), and llvm::ARMAsmPrinter::EmitMachineConstantPoolValue().
virtual unsigned llvm::ARMConstantPoolValue::getRelocationInfo () const inline virtual
getRelocationInfo - This method classifies the entry according to whether or not it may generate a relocation entry. This must be conservative, so if it might codegen to a relocatable entry, it should say so. The return values are the same as Constant::getRelocationInfo().
Implements llvm::MachineConstantPoolValue.
Definition at line 106 of file ARMConstantPoolValue.h.
bool llvm::ARMConstantPoolValue::hasModifier () const inline
Definition at line 93 of file ARMConstantPoolValue.h.
References llvm::ARMCP::no_modifier.
Referenced by llvm::ARMJITInfo::emitFunctionStub().
bool ARMConstantPoolValue::hasSameValue (ARMConstantPoolValue * ACPV) virtual
hasSameValue - Return true if this ARM constpool value can share the same constantpool entry as another ARM constpool value.
Reimplemented in llvm::ARMConstantPoolMBB, llvm::ARMConstantPoolSymbol, and llvm::ARMConstantPoolConstant.
Definition at line 75 of file ARMConstantPoolValue.cpp.
References llvm::ARMCP::CPExtSymbol, and llvm::ARMCP::CPValue.
Referenced by llvm::ARMConstantPoolConstant::hasSameValue(), llvm::ARMConstantPoolSymbol::hasSameValue(), llvm::ARMConstantPoolMBB::hasSameValue(), and llvm::ARMBaseInstrInfo::produceSameValue().
bool llvm::ARMConstantPoolValue::isBlockAddress () const inline
Definition at line 102 of file ARMConstantPoolValue.h.
References llvm::ARMCP::CPBlockAddress.
Referenced by llvm::ARMConstantPoolConstant::classof(), and llvm::ARMAsmPrinter::EmitMachineConstantPoolValue().
bool llvm::ARMConstantPoolValue::isExtSymbol () const inline
Definition at line 101 of file ARMConstantPoolValue.h.
References llvm::ARMCP::CPExtSymbol.
Referenced by llvm::ARMConstantPoolSymbol::classof(), and llvm::ARMAsmPrinter::EmitMachineConstantPoolValue().
bool llvm::ARMConstantPoolValue::isGlobalValue () const inline
Definition at line 100 of file ARMConstantPoolValue.h.
References llvm::ARMCP::CPValue.
Referenced by llvm::ARMConstantPoolConstant::classof(), llvm::createARMJITCodeEmitterPass(), and llvm::ARMAsmPrinter::EmitMachineConstantPoolValue().
bool llvm::ARMConstantPoolValue::isLSDA () const inline
Definition at line 103 of file ARMConstantPoolValue.h.
References llvm::ARMCP::CPLSDA.
Referenced by llvm::ARMConstantPoolConstant::classof(), and llvm::ARMAsmPrinter::EmitMachineConstantPoolValue().
bool llvm::ARMConstantPoolValue::isMachineBasicBlock () const inline
Definition at line 104 of file ARMConstantPoolValue.h.
References llvm::ARMCP::CPMachineBasicBlock.
Referenced by llvm::ARMConstantPoolMBB::classof(), and llvm::ARMAsmPrinter::EmitMachineConstantPoolValue().
bool llvm::ARMConstantPoolValue::mustAddCurrentAddress () const inline
Definition at line 95 of file ARMConstantPoolValue.h.
Referenced by llvm::ARMJITInfo::emitFunctionStub(), and llvm::ARMAsmPrinter::EmitMachineConstantPoolValue().
void ARMConstantPoolValue::print (raw_ostream & O) const virtual
print - Implement operator<<
Implements llvm::MachineConstantPoolValue.
Reimplemented in llvm::ARMConstantPoolMBB, llvm::ARMConstantPoolSymbol, and llvm::ARMConstantPoolConstant.
Definition at line 93 of file ARMConstantPoolValue.cpp.
References ARMConstantPoolValue(), getModifierText(), and llvm::Value::getType().
Referenced by llvm::operator<<(), llvm::ARMConstantPoolConstant::print(), llvm::ARMConstantPoolSymbol::print(), and llvm::ARMConstantPoolMBB::print().
void llvm::ARMConstantPoolValue::print (raw_ostream * O) const inline
Definition at line 124 of file ARMConstantPoolValue.h.
References llvm::dump(), and print().
Referenced by print().
The documentation for this class was generated from the following files:
ARMConstantPoolValue.h
ARMConstantPoolValue.cpp