LLVM: llvm::DILineInfoSpecifier Class Reference
LLVM API Documentation
llvm::DILineInfoSpecifier Class Reference
#include <DIContext.h>
Public Types
enum Specification { FileLineInfo = 1 << 0, AbsoluteFilePath = 1 << 1, FunctionName = 1 << 2 }
Public Member Functions
DILineInfoSpecifier (uint32_t flags=FileLineInfo)
bool needs (Specification spec) const
Detailed Description
DILineInfoSpecifier - controls which fields of DILineInfo container should be filled with data.
Definition at line 82 of file DIContext.h.
Member Enumeration Documentation
enum llvm::DILineInfoSpecifier::Specification
Enumerator
FileLineInfo
AbsoluteFilePath
FunctionName
Definition at line 85 of file DIContext.h.
Constructor & Destructor Documentation
llvm::DILineInfoSpecifier::DILineInfoSpecifier (uint32_t flags = FileLineInfo) inline
Definition at line 91 of file DIContext.h.
Member Function Documentation
bool llvm::DILineInfoSpecifier::needs (Specification spec) const inline
Definition at line 92 of file DIContext.h.
Referenced by llvm::DWARFContext::getInliningInfoForAddress(), llvm::DWARFContext::getLineInfoForAddress(), and llvm::DWARFContext::getLineInfoForAddressRange().
The documentation for this class was generated from the following file:
DIContext.h