LLVM: llvm::RuntimeDyldMachO Class Reference
LLVM API Documentation
llvm::RuntimeDyldMachO Class Reference
#include <RuntimeDyldMachO.h>
Public Member Functions
RuntimeDyldMachO (RTDyldMemoryManager *mm)
virtual void resolveRelocation (const RelocationEntry &RE, uint64_t Value)
A object file specific relocation resolver.
virtual void processRelocationRef (unsigned SectionID, RelocationRef RelI, ObjectImage &Obj, ObjSectionToIDMap &ObjSectionToID, const SymbolTableMap &Symbols, StubMap &Stubs)
Parses the object file relocation and stores it to Relocations or SymbolRelocations (this depends on the object file type).
virtual bool isCompatibleFormat (const ObjectBuffer *Buffer) const
virtual void registerEHFrames ()
virtual void finalizeLoad (ObjSectionToIDMap &SectionMap)
Public Member Functions inherited from llvm::RuntimeDyldImpl
RuntimeDyldImpl (RTDyldMemoryManager *mm)
virtual ~RuntimeDyldImpl ()
ObjectImage * loadObject (ObjectBuffer *InputBuffer)
void * getSymbolAddress (StringRef Name)
uint64_t getSymbolLoadAddress (StringRef Name)
void resolveRelocations ()
void reassignSectionAddress (unsigned SectionID, uint64_t Addr)
void mapSectionAddress (const void *LocalAddress, uint64_t TargetAddress)
bool hasError ()
void clearError ()
StringRef getErrorString ()
virtual void deregisterEHFrames ()
Additional Inherited Members
Protected Types inherited from llvm::RuntimeDyldImpl
typedef SmallVector< SectionEntry, 64 > SectionList
typedef unsigned SID
typedef std::map< SectionRef, unsigned > ObjSectionToIDMap
typedef std::pair< unsigned, uintptr_t > SymbolLoc
typedef StringMap< SymbolLoc > SymbolTableMap
typedef std::pair< unsigned, unsigned > CommonSymbolInfo
typedef std::map< SymbolRef, CommonSymbolInfo > CommonSymbolMap
typedef SmallVector< RelocationEntry, 64 > RelocationList
typedef std::map< RelocationValueRef, uintptr_t > StubMap
Protected Member Functions inherited from llvm::RuntimeDyldImpl
bool Error (const Twine &Msg)
uint64_t getSectionLoadAddress (unsigned SectionID)
uint8_t * getSectionAddress (unsigned SectionID)
void writeInt16BE (uint8_t *Addr, uint16_t Value)
void writeInt32BE (uint8_t *Addr, uint32_t Value)
void writeInt64BE (uint8_t *Addr, uint64_t Value)
void emitCommonSymbols (ObjectImage &Obj, const CommonSymbolMap &CommonSymbols, uint64_t TotalSize, SymbolTableMap &SymbolTable)
Given the common symbols discovered in the object file, emit a new section for them and update the symbol mappings in the object and symbol table.
unsigned emitSection (ObjectImage &Obj, const SectionRef &Section, bool IsCode)
Emits section data from the object file to the MemoryManager.
unsigned findOrEmitSection (ObjectImage &Obj, const SectionRef &Section, bool IsCode, ObjSectionToIDMap &LocalSections)
Find Section in LocalSections. If the secton is not found - emit it and store in LocalSections.
void addRelocationForSection (const RelocationEntry &RE, unsigned SectionID)
void addRelocationForSymbol (const RelocationEntry &RE, StringRef SymbolName)
uint8_t * createStubFunction (uint8_t *Addr)
Emits long jump instruction to Addr.
void resolveRelocationList (const RelocationList &Relocs, uint64_t Value)
Resolves relocations from Relocs list with address from Value.
void resolveExternalSymbols ()
Resolve relocations to external symbols.
virtual void updateGOTEntries (StringRef Name, uint64_t Addr)
Update GOT entries for external symbols.
virtual ObjectImage * createObjectImage (ObjectBuffer *InputBuffer)
Protected Attributes inherited from llvm::RuntimeDyldImpl
RTDyldMemoryManager * MemMgr
SectionList Sections
SymbolTableMap GlobalSymbolTable
DenseMap< unsigned, RelocationList > Relocations
StringMap< RelocationList > ExternalSymbolRelocations
Triple::ArchType Arch
bool IsTargetLittleEndian
sys::Mutex lock
bool HasError
std::string ErrorStr
Detailed Description
Definition at line 27 of file RuntimeDyldMachO.h.
Constructor & Destructor Documentation
llvm::RuntimeDyldMachO::RuntimeDyldMachO (RTDyldMemoryManager * mm) inline
Definition at line 87 of file RuntimeDyldMachO.h.
Member Function Documentation
void llvm::RuntimeDyldMachO::finalizeLoad (ObjSectionToIDMap & SectionMap) virtual
Reimplemented from llvm::RuntimeDyldImpl.
Definition at line 91 of file RuntimeDyldMachO.cpp.
References llvm::object::SectionRef::getName(), i, RTDYLD_INVALID_SECTION_ID, and llvm::ARMBuildAttrs::Section.
bool llvm::RuntimeDyldMachO::isCompatibleFormat (const ObjectBuffer * Buffer) const virtual
Implements llvm::RuntimeDyldImpl.
Definition at line 446 of file RuntimeDyldMachO.cpp.
References llvm::ObjectBuffer::getBufferSize(), llvm::ObjectBuffer::getBufferStart(), and Magic.
void llvm::RuntimeDyldMachO::processRelocationRef (unsigned SectionID, RelocationRef RelI, ObjectImage & Obj, ObjSectionToIDMap & ObjSectionToID, const SymbolTableMap & Symbols, StubMap & Stubs) virtual
Parses the object file relocation and stores it to Relocations or SymbolRelocations (this depends on the object file type).
Implements llvm::RuntimeDyldImpl.
Definition at line 324 of file RuntimeDyldMachO.cpp.
References llvm::RelocationValueRef::Addend, llvm::SectionEntry::Address, llvm::Triple::arm, llvm::MachO::ARM_RELOC_BR24, llvm::StringRef::data(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::StringMap< ValueTy, AllocatorTy >::find(), llvm::MachO::GENERIC_RELOC_VANILLA, llvm::object::SectionRef::getAddress(), llvm::object::MachOObjectFile::getAnyRelocationLength(), llvm::object::MachOObjectFile::getAnyRelocationPCRel(), llvm::object::MachOObjectFile::getAnyRelocationType(), llvm::ObjectImage::getObjectFile(), llvm::object::RelocationRef::getOffset(), llvm::object::MachOObjectFile::getPlainRelocationExternal(), llvm::object::RelocationRef::getRawDataRefImpl(), llvm::object::MachOObjectFile::getRelocation(), llvm::object::MachOObjectFile::getRelocationSection(), llvm::object::RelocationRef::getSymbol(), i, llvm::object::MachOObjectFile::isRelocationScattered(), llvm::Intrinsic::memcpy, llvm::StringMapEntry< ValueTy >::second, llvm::RelocationValueRef::SectionID, llvm::SectionEntry::StubOffset, llvm::ARMBuildAttrs::Symbol, llvm::RelocationValueRef::SymbolName, llvm::Triple::x86_64, llvm::MachO::X86_64_RELOC_GOT, llvm::MachO::X86_64_RELOC_GOT_LOAD, and llvm::MachO::X86_64_RELOC_UNSIGNED.
void llvm::RuntimeDyldMachO::registerEHFrames () virtual
Reimplemented from llvm::RuntimeDyldImpl.
Definition at line 58 of file RuntimeDyldMachO.cpp.
References llvm::SectionEntry::Address, llvm::computeDelta(), i, llvm::SectionEntry::LoadAddress, P, llvm::processFDE(), RTDYLD_INVALID_SECTION_ID, and llvm::SectionEntry::Size.
void llvm::RuntimeDyldMachO::resolveRelocation (const RelocationEntry & RE, uint64_t Value) virtual
A object file specific relocation resolver.
Parameters
RE The relocation to be resolved
Value Target symbol address to apply the relocation action
Implements llvm::RuntimeDyldImpl.
Definition at line 132 of file RuntimeDyldMachO.cpp.
References llvm::RelocationEntry::Addend, llvm::SectionEntry::Address, llvm::Triple::arm, llvm::MachO::ARM_RELOC_BR24, llvm::MachO::ARM_RELOC_HALF, llvm::MachO::ARM_RELOC_HALF_SECTDIFF, llvm::MachO::ARM_RELOC_LOCAL_SECTDIFF, llvm::MachO::ARM_RELOC_PAIR, llvm::MachO::ARM_RELOC_PB_LA_PTR, llvm::MachO::ARM_RELOC_SECTDIFF, llvm::MachO::ARM_RELOC_VANILLA, llvm::MachO::ARM_THUMB_32BIT_BRANCH, llvm::MachO::ARM_THUMB_RELOC_BR22, llvm::dbgs(), DEBUG, llvm::lltok::Error, llvm::format(), llvm::MachO::GENERIC_RELOC_LOCAL_SECTDIFF, llvm::MachO::GENERIC_RELOC_PB_LA_PTR, llvm::MachO::GENERIC_RELOC_SECTDIFF, llvm::MachO::GENERIC_RELOC_VANILLA, i, llvm::RelocationEntry::IsPCRel, llvm_unreachable, llvm::SectionEntry::LoadAddress, llvm::RelocationEntry::Offset, p, llvm::RelocationEntry::RelType, llvm::ARMBuildAttrs::Section, llvm::RelocationEntry::SectionID, llvm::RelocationEntry::Size, llvm::Triple::thumb, Type, llvm::Triple::x86, llvm::Triple::x86_64, llvm::MachO::X86_64_RELOC_BRANCH, llvm::MachO::X86_64_RELOC_GOT, llvm::MachO::X86_64_RELOC_GOT_LOAD, llvm::MachO::X86_64_RELOC_SIGNED, llvm::MachO::X86_64_RELOC_SIGNED_1, llvm::MachO::X86_64_RELOC_SIGNED_2, llvm::MachO::X86_64_RELOC_SIGNED_4, llvm::MachO::X86_64_RELOC_SUBTRACTOR, llvm::MachO::X86_64_RELOC_TLV, and llvm::MachO::X86_64_RELOC_UNSIGNED.
The documentation for this class was generated from the following files:
RuntimeDyldMachO.h
RuntimeDyldMachO.cpp