LLVM: llvm::sys::fs::directory_iterator Class Reference
LLVM API Documentation
llvm::sys::fs::directory_iterator Class Reference
#include <FileSystem.h>
Public Member Functions
directory_iterator (const Twine &path, error_code &ec)
directory_iterator (const directory_entry &de, error_code &ec)
directory_iterator ()
Construct end iterator.
directory_iterator & increment (error_code &ec)
const directory_entry & operator* () const
const directory_entry * operator-> () const
bool operator== (const directory_iterator &RHS) const
bool operator!= (const directory_iterator &RHS) const
Detailed Description
directory_iterator - Iterates through the entries in path. There is no operator++ because we need an error_code. If it's really needed we can make it call report_fatal_error on error.
Definition at line 846 of file FileSystem.h.
Constructor & Destructor Documentation
llvm::sys::fs::directory_iterator::directory_iterator (const Twine & path, error_code & ec) inline explicit
Definition at line 850 of file FileSystem.h.
References llvm::sys::fs::detail::directory_iterator_construct(), and llvm::Twine::toStringRef().
llvm::sys::fs::directory_iterator::directory_iterator (const directory_entry & de, error_code & ec) inline explicit
Definition at line 857 of file FileSystem.h.
References llvm::sys::fs::detail::directory_iterator_construct(), and llvm::sys::fs::directory_entry::path().
llvm::sys::fs::directory_iterator::directory_iterator () inline
Construct end iterator.
Definition at line 863 of file FileSystem.h.
Member Function Documentation
directory_iterator& llvm::sys::fs::directory_iterator::increment (error_code & ec) inline
Definition at line 866 of file FileSystem.h.
References llvm::sys::fs::detail::directory_iterator_increment().
Referenced by llvm::sys::fs::identify_magic().
bool llvm::sys::fs::directory_iterator::operator!= (const directory_iterator & RHS) const inline
Definition at line 884 of file FileSystem.h.
const directory_entry& llvm::sys::fs::directory_iterator::operator* () const inline
Definition at line 871 of file FileSystem.h.
const directory_entry* llvm::sys::fs::directory_iterator::operator-> () const inline
Definition at line 872 of file FileSystem.h.
bool llvm::sys::fs::directory_iterator::operator== (const directory_iterator & RHS) const inline
Definition at line 874 of file FileSystem.h.
The documentation for this class was generated from the following file:
FileSystem.h