LLVM: llvm::IntRecTy Class Reference
LLVM API Documentation
llvm::IntRecTy Class Reference
#include <Record.h>
Public Member Functions
virtual Init * convertValue (UnsetInit *UI)
virtual Init * convertValue (BitInit *BI)
virtual Init * convertValue (BitsInit *BI)
virtual Init * convertValue (IntInit *II)
virtual Init * convertValue (StringInit *SI)
virtual Init * convertValue (ListInit *LI)
virtual Init * convertValue (VarBitInit *VB)
virtual Init * convertValue (DefInit *DI)
virtual Init * convertValue (DagInit *DI)
virtual Init * convertValue (UnOpInit *UI)
virtual Init * convertValue (BinOpInit *UI)
virtual Init * convertValue (TernOpInit *UI)
virtual Init * convertValue (TypedInit *TI)
virtual Init * convertValue (VarInit *VI)
virtual Init * convertValue (FieldInit *FI)
virtual std::string getAsString () const
virtual bool typeIsConvertibleTo (const RecTy *RHS) const
virtual bool baseClassOf (const RecTy *) const
Public Member Functions inherited from llvm::RecTy
RecTyKind getRecTyKind () const
RecTy (RecTyKind K)
virtual ~RecTy ()
void print (raw_ostream &OS) const
void dump () const
ListRecTy * getListTy ()
getListTy - Returns the type representing list<this>.
Static Public Member Functions
static bool classof (const RecTy *RT)
static IntRecTy * get ()
Additional Inherited Members
Public Types inherited from llvm::RecTy
enum RecTyKind {
BitRecTyKind, BitsRecTyKind, IntRecTyKind, StringRecTyKind,
ListRecTyKind, DagRecTyKind, RecordRecTyKind
}
Subclass discriminator (for dyn_cast<> et al.)
Detailed Description
IntRecTy - 'int' - Represent an integer value of no particular size
Definition at line 219 of file Record.h.
Member Function Documentation
bool IntRecTy::baseClassOf (const RecTy * RHS) const virtual
Reimplemented from llvm::RecTy.
Definition at line 233 of file Record.cpp.
References llvm::RecTy::getRecTyKind().
static bool llvm::IntRecTy::classof (const RecTy * RT) inline static
Definition at line 223 of file Record.h.
References llvm::RecTy::getRecTyKind(), and llvm::RecTy::IntRecTyKind.
virtual Init* llvm::IntRecTy::convertValue (UnsetInit * UI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 229 of file Record.h.
References llvm::RecTy::convertValue().
Init * IntRecTy::convertValue (BitInit * BI) virtual
Reimplemented from llvm::RecTy.
Definition at line 212 of file Record.cpp.
References llvm::IntInit::get(), and llvm::BitInit::getValue().
Init * IntRecTy::convertValue (BitsInit * BI) virtual
Reimplemented from llvm::RecTy.
Definition at line 216 of file Record.cpp.
References llvm::tgtok::Bit, llvm::IntInit::get(), llvm::BitsInit::getBit(), llvm::BitsInit::getNumBits(), and i.
virtual Init* llvm::IntRecTy::convertValue (IntInit * II) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 232 of file Record.h.
virtual Init* llvm::IntRecTy::convertValue (StringInit * SI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 233 of file Record.h.
virtual Init* llvm::IntRecTy::convertValue (ListInit * LI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 234 of file Record.h.
virtual Init* llvm::IntRecTy::convertValue (VarBitInit * VB) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 235 of file Record.h.
virtual Init* llvm::IntRecTy::convertValue (DefInit * DI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 236 of file Record.h.
virtual Init* llvm::IntRecTy::convertValue (DagInit * DI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 237 of file Record.h.
virtual Init* llvm::IntRecTy::convertValue (UnOpInit * UI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 238 of file Record.h.
References llvm::RecTy::convertValue().
virtual Init* llvm::IntRecTy::convertValue (BinOpInit * UI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 239 of file Record.h.
References llvm::RecTy::convertValue().
virtual Init* llvm::IntRecTy::convertValue (TernOpInit * UI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 240 of file Record.h.
References llvm::RecTy::convertValue().
Init * IntRecTy::convertValue (TypedInit * TI) virtual
Reimplemented from llvm::RecTy.
Definition at line 227 of file Record.cpp.
References llvm::TypedInit::getType(), and llvm::RecTy::typeIsConvertibleTo().
virtual Init* llvm::IntRecTy::convertValue (VarInit * VI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 242 of file Record.h.
References llvm::RecTy::convertValue().
virtual Init* llvm::IntRecTy::convertValue (FieldInit * FI) inline virtual
Reimplemented from llvm::RecTy.
Definition at line 243 of file Record.h.
References llvm::RecTy::convertValue().
static IntRecTy* llvm::IntRecTy::get () inline static
Definition at line 227 of file Record.h.
Referenced by llvm::BinOpInit::Fold(), llvm::TernOpInit::Fold(), GetNewAnonymousName(), and llvm::TernOpInit::resolveReferences().
virtual std::string llvm::IntRecTy::getAsString () const inline virtual
Implements llvm::RecTy.
Definition at line 245 of file Record.h.
virtual bool llvm::IntRecTy::typeIsConvertibleTo (const RecTy * RHS) const inline virtual
typeIsConvertibleTo - Return true if all values of 'this' type can be converted to the specified type.
Implements llvm::RecTy.
Definition at line 247 of file Record.h.
References llvm::RecTy::baseClassOf().
The documentation for this class was generated from the following files:
Record.h
Record.cpp