LLVM: llvm::IntervalMapImpl::Path Class Reference
LLVM API Documentation
llvm::IntervalMapImpl::Path Class Reference
#include <IntervalMap.h>
Public Member Functions
template<typename NodeT >
NodeT & node (unsigned Level) const
unsigned size (unsigned Level) const
unsigned offset (unsigned Level) const
unsigned & offset (unsigned Level)
template<typename NodeT >
NodeT & leaf () const
unsigned leafSize () const
unsigned leafOffset () const
unsigned & leafOffset ()
bool valid () const
valid - Return true if path is at a valid node, not at end().
unsigned height () const
NodeRef & subtree (unsigned Level) const
void reset (unsigned Level)
void push (NodeRef Node, unsigned Offset)
void pop ()
pop - Remove the last path entry.
void setSize (unsigned Level, unsigned Size)
void setRoot (void *Node, unsigned Size, unsigned Offset)
void replaceRoot (void *Root, unsigned Size, IdxPair Offsets)
NodeRef getLeftSibling (unsigned Level) const
void moveLeft (unsigned Level)
void fillLeft (unsigned Height)
NodeRef getRightSibling (unsigned Level) const
void moveRight (unsigned Level)
bool atBegin () const
atBegin - Return true if path is at begin().
bool atLastEntry (unsigned Level) const
void legalizeForInsert (unsigned Level)
Detailed Description
Definition at line 767 of file IntervalMap.h.
Member Function Documentation
bool llvm::IntervalMapImpl::Path::atBegin () const inline
atBegin - Return true if path is at begin().
Definition at line 894 of file IntervalMap.h.
References i, and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::atBegin(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase().
bool llvm::IntervalMapImpl::Path::atLastEntry (unsigned Level) const inline
atLastEntry - Return true if the path is at the last entry of the node at Level.
Parameters
Level Node to examine.
Definition at line 904 of file IntervalMap.h.
References llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by getRightSibling(), moveRight(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::operator--(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setValue().
void llvm::IntervalMapImpl::Path::fillLeft (unsigned Height) inline
fillLeft - Grow path to Height by taking leftmost branches.
Parameters
Height The target height.
Definition at line 878 of file IntervalMap.h.
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::goToBegin().
NodeRef llvm::IntervalMapImpl::Path::getLeftSibling (unsigned Level) const
getLeftSibling - Get the left sibling node at Level, or a null NodeRef.
Parameters
Level Get the sibling to node(Level).
Returns
Left sibling, or NodeRef().
Definition at line 25 of file IntervalMap.cpp.
References l, offset(), llvm::IntervalMapImpl::NodeRef::size(), and llvm::IntervalMapImpl::NodeRef::subtree().
NodeRef llvm::IntervalMapImpl::Path::getRightSibling (unsigned Level) const
getLeftSibling - Get the left sibling node at Level, or a null NodeRef.
Parameters
Level Get the sinbling to node(Level).
Returns
Left sibling, or NodeRef().
Definition at line 75 of file IntervalMap.cpp.
References atLastEntry(), l, offset(), and llvm::IntervalMapImpl::NodeRef::subtree().
unsigned llvm::IntervalMapImpl::Path::height () const inline
height - Return the height of the tree corresponding to this path. This matches map->height in a full path.
Definition at line 813 of file IntervalMap.h.
References llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by moveLeft().
template<typename NodeT > NodeT& llvm::IntervalMapImpl::Path::leaf () const inline
Definition at line 799 of file IntervalMap.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeStart(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeStop(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeValue().
unsigned llvm::IntervalMapImpl::Path::leafOffset () const inline
Definition at line 803 of file IntervalMap.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::advanceTo(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::insert(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator++(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator--(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator==(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeStart(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeStop(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::unsafeValue().
unsigned& llvm::IntervalMapImpl::Path::leafOffset () inline
Definition at line 804 of file IntervalMap.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back().
unsigned llvm::IntervalMapImpl::Path::leafSize () const inline
Definition at line 802 of file IntervalMap.h.
References llvm::SmallVectorTemplateCommon< T, typename >::back().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator++().
void llvm::IntervalMapImpl::Path::legalizeForInsert (unsigned Level) inline
legalizeForInsert - Prepare the path for an insertion at Level. When the path is at end(), node(Level) may not be a legal node. legalizeForInsert ensures that node(Level) is real by moving back to the last node at Level, and setting offset(Level) to size(Level) if required.
Parameters
Level The level where an insertion is about to take place.
Definition at line 913 of file IntervalMap.h.
References N.
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setValue().
void llvm::IntervalMapImpl::Path::moveLeft (unsigned Level)
moveLeft - Move path to the left sibling at Level. Leave nodes below Level unaltered.
Parameters
Level Move node(Level).
Definition at line 48 of file IntervalMap.cpp.
References height(), l, offset(), llvm::SmallVectorImpl< T >::resize(), llvm::IntervalMapImpl::NodeRef::size(), llvm::IntervalMapImpl::NodeRef::subtree(), subtree(), and valid().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator--().
void llvm::IntervalMapImpl::Path::moveRight (unsigned Level)
moveRight - Move path to the left sibling at Level. Leave nodes below Level unaltered.
Parameters
Level Move node(Level).
Definition at line 98 of file IntervalMap.cpp.
References atLastEntry(), l, offset(), size(), llvm::IntervalMapImpl::NodeRef::subtree(), and subtree().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::operator++().
template<typename NodeT > NodeT& llvm::IntervalMapImpl::Path::node (unsigned Level) const inline
Definition at line 791 of file IntervalMap.h.
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::operator--(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setValue().
unsigned llvm::IntervalMapImpl::Path::offset (unsigned Level) const inline
Definition at line 795 of file IntervalMap.h.
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), getLeftSibling(), getRightSibling(), moveLeft(), moveRight(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::operator--(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setValue().
unsigned& llvm::IntervalMapImpl::Path::offset (unsigned Level) inline
Definition at line 796 of file IntervalMap.h.
void llvm::IntervalMapImpl::Path::pop () inline
pop - Remove the last path entry.
Definition at line 836 of file IntervalMap.h.
References llvm::SmallVectorTemplateBase< T, isPodLike >::pop_back().
void llvm::IntervalMapImpl::Path::push (NodeRef Node, unsigned Offset) inline
push - Add entry to path.
Parameters
Node Node to add, should be subtree(path.size()-1).
Offset Offset into Node.
Definition at line 831 of file IntervalMap.h.
References llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
void llvm::IntervalMapImpl::Path::replaceRoot (void * Root, unsigned Size, IdxPair Offsets)
replaceRoot - Replace the current root node with two new entries after the tree height has increased.
Parameters
Root The new root node.
Size Number of entries in the new root.
Offsets Offsets into the root and first branch nodes.
Definition at line 19 of file IntervalMap.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::front(), llvm::SmallVectorImpl< T >::insert(), and subtree().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::insert(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setValue().
void llvm::IntervalMapImpl::Path::reset (unsigned Level) inline
reset - Reset cached information about node(Level) from subtree(Level -1).
Parameters
Level 1..height. THe node to update after parent node changed.
Definition at line 824 of file IntervalMap.h.
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setValue().
void llvm::IntervalMapImpl::Path::setRoot (void * Node, unsigned Size, unsigned Offset) inline
setRoot - Clear the path and set a new root node.
Parameters
Node New root node.
Size New root size.
Offset Offset into root node.
Definition at line 854 of file IntervalMap.h.
References llvm::SmallVectorImpl< T >::clear(), and llvm::SmallVectorTemplateBase< T, isPodLike >::push_back().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::setRoot().
void llvm::IntervalMapImpl::Path::setSize (unsigned Level, unsigned Size) inline
setSize - Set the size of a node both in the path and in the tree.
Parameters
Level 0..height. Note that setting the root size won't change map->rootSize.
Size New node size.
Definition at line 844 of file IntervalMap.h.
References llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::insert(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setValue().
unsigned llvm::IntervalMapImpl::Path::size (unsigned Level) const inline
Definition at line 794 of file IntervalMap.h.
References llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), moveRight(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setValue().
NodeRef& llvm::IntervalMapImpl::Path::subtree (unsigned Level) const inline
subtree - Get the subtree referenced from Level. When the path is consistent, node(Level + 1) == subtree(Level).
Parameters
Level 0..height-1. The leaves have no subtrees.
Definition at line 818 of file IntervalMap.h.
Referenced by moveLeft(), moveRight(), and replaceRoot().
bool llvm::IntervalMapImpl::Path::valid () const inline
valid - Return true if path is at a valid node, not at end().
Definition at line 807 of file IntervalMap.h.
References llvm::SmallVectorBase::empty(), and llvm::SmallVectorTemplateCommon< T, typename >::front().
Referenced by llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), moveLeft(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::valid().
The documentation for this class was generated from the following files:
IntervalMap.h
IntervalMap.cpp