LLVM: llvm::ConvergingVLIWScheduler Class Reference
LLVM API Documentation
llvm::ConvergingVLIWScheduler Class Reference
#include <HexagonMachineScheduler.h>
Public Types
enum { TopQID = 1, BotQID = 2, LogMaxQID = 2 }
SUnit::NodeQueueId: 0 (none), 1 (top), 2 (bot), 3 (both)
Public Member Functions
ConvergingVLIWScheduler ()
virtual void initialize (ScheduleDAGMI *dag)
Initialize the strategy after building the DAG for a new region.
virtual SUnit * pickNode (bool &IsTopNode)
Pick the best node to balance the schedule. Implements MachineSchedStrategy.
virtual void schedNode (SUnit *SU, bool IsTopNode)
virtual void releaseTopNode (SUnit *SU)
virtual void releaseBottomNode (SUnit *SU)
unsigned ReportPackets ()
Public Member Functions inherited from llvm::MachineSchedStrategy
virtual ~MachineSchedStrategy ()
virtual void initPolicy (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned NumRegionInstrs)
Optionally override the per-region scheduling policy.
virtual bool shouldTrackPressure () const
virtual void registerRoots ()
virtual void scheduleTree (unsigned SubtreeID)
Scheduler callback to notify that a new subtree is scheduled.
Protected Member Functions
SUnit * pickNodeBidrectional (bool &IsTopNode)
Pick the best candidate node from either the top or bottom queue.
int SchedulingCost (ReadyQueue &Q, SUnit *SU, SchedCandidate &Candidate, RegPressureDelta &Delta, bool verbose)
CandResult pickNodeFromQueue (ReadyQueue &Q, const RegPressureTracker &RPTracker, SchedCandidate &Candidate)
void traceCandidate (const char *Label, const ReadyQueue &Q, SUnit *SU, PressureChange P=PressureChange())
Detailed Description
ConvergingVLIWScheduler shrinks the unscheduled zone using heuristics to balance the schedule.
Definition at line 109 of file HexagonMachineScheduler.h.
Member Enumeration Documentation
anonymous enum
SUnit::NodeQueueId: 0 (none), 1 (top), 2 (bot), 3 (both)
Enumerator
TopQID
BotQID
LogMaxQID
Definition at line 200 of file HexagonMachineScheduler.h.
Constructor & Destructor Documentation
llvm::ConvergingVLIWScheduler::ConvergingVLIWScheduler () inline
Definition at line 206 of file HexagonMachineScheduler.h.
References initialize().
Member Function Documentation
void ConvergingVLIWScheduler::initialize (ScheduleDAGMI * DAG) virtual
Initialize the strategy after building the DAG for a new region.
Implements llvm::MachineSchedStrategy.
Definition at line 195 of file HexagonMachineScheduler.cpp.
References llvm::TargetInstrInfo::CreateTargetMIHazardRecognizer(), llvm::ForceBottomUp, llvm::ForceTopDown, llvm::TargetMachine::getInstrInfo(), llvm::TargetMachine::getTarget(), llvm::TargetSchedModel::init(), llvm::ScheduleDAGInstrs::SchedModel, and llvm::ScheduleDAG::TM.
SUnit * ConvergingVLIWScheduler::pickNode (bool & IsTopNode) virtual
Pick the best node to balance the schedule. Implements MachineSchedStrategy.
Implements llvm::MachineSchedStrategy.
Definition at line 635 of file HexagonMachineScheduler.cpp.
References llvm::dbgs(), DEBUG, llvm::SUnit::dump(), llvm::ForceBottomUp, llvm::ForceTopDown, llvm::SUnit::isBottomReady(), and llvm::SUnit::isTopReady().
SUnit * ConvergingVLIWScheduler::pickNodeBidrectional (bool & IsTopNode) protected
Pick the best candidate node from either the top or bottom queue.
Definition at line 577 of file HexagonMachineScheduler.cpp.
ConvergingVLIWScheduler::CandResult ConvergingVLIWScheduler::pickNodeFromQueue (ReadyQueue & Q, const RegPressureTracker & RPTracker, SchedCandidate & Candidate) protected
Pick the best candidate from the top queue.
TODO: getMaxPressureDelta results can be mostly cached for each SUnit during DAG building. To adjust for the current scheduling location we need to maintain the number of vreg uses remaining to be top-scheduled.
Definition at line 532 of file HexagonMachineScheduler.cpp.
References llvm::ReadyQueue::begin(), DEBUG, llvm::ReadyQueue::dump(), llvm::ReadyQueue::end(), I, and llvm::ScheduleDAGMI::RPTracker.
Referenced by SchedulingCost().
void ConvergingVLIWScheduler::releaseBottomNode (SUnit * SU) virtual
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
Implements llvm::MachineSchedStrategy.
Definition at line 237 of file HexagonMachineScheduler.cpp.
References llvm::SUnit::BotReadyCycle, llvm::dbgs(), DEBUG, llvm::SUnit::getInstr(), llvm::TargetSchedModel::getIssueWidth(), llvm::TargetSchedModel::getNumMicroOps(), i, I, llvm::SUnit::isCall, llvm::SUnit::isScheduled, llvm::ScheduleHazardRecognizer::NoHazard, llvm::ScheduleDAGInstrs::SchedModel, llvm::SUnit::Succs, and llvm::SUnit::TopReadyCycle.
void ConvergingVLIWScheduler::releaseTopNode (SUnit * SU) virtual
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
Implements llvm::MachineSchedStrategy.
Definition at line 220 of file HexagonMachineScheduler.cpp.
References I, llvm::SUnit::isScheduled, llvm::SUnit::Preds, and llvm::SUnit::TopReadyCycle.
unsigned llvm::ConvergingVLIWScheduler::ReportPackets () inline
Definition at line 219 of file HexagonMachineScheduler.h.
References P.
void ConvergingVLIWScheduler::schedNode (SUnit * SU, bool IsTopNode) virtual
Update the scheduler's state after scheduling a node. This is the same node that was just returned by pickNode(). However, VLIWMachineScheduler needs to update it's state based on the current cycle before MachineSchedStrategy does.
Implements llvm::MachineSchedStrategy.
Definition at line 683 of file HexagonMachineScheduler.cpp.
References llvm::SUnit::BotReadyCycle, and llvm::SUnit::TopReadyCycle.
int ConvergingVLIWScheduler::SchedulingCost (ReadyQueue & Q, SUnit * SU, SchedCandidate & Candidate, RegPressureDelta & Delta, bool verbose) protected
Single point to compute overall scheduling cost. TODO: More heuristics will be used soon.
Definition at line 466 of file HexagonMachineScheduler.cpp.
References llvm::RegPressureDelta::CriticalMax, llvm::dbgs(), DEBUG, llvm::RegPressureDelta::Excess, FactorOne, llvm::SUnit::getDepth(), llvm::SUnit::getHeight(), llvm::ReadyQueue::getID(), getSingleUnscheduledPred(), getSingleUnscheduledSucc(), llvm::PressureChange::getUnitInc(), I, llvm::SUnit::isScheduled, llvm::SUnit::isScheduleHigh, pickNodeFromQueue(), llvm::SUnit::Preds, PriorityOne, PriorityTwo, ScaleTwo, and llvm::SUnit::Succs.
void ConvergingVLIWScheduler::traceCandidate (const char * Label, const ReadyQueue & Q, SUnit * SU, PressureChange P = PressureChange()) protected
Definition at line 408 of file HexagonMachineScheduler.cpp.
References llvm::dbgs(), llvm::SUnit::dump(), llvm::ReadyQueue::getName(), llvm::PressureChange::getPSet(), llvm::PressureChange::getUnitInc(), and llvm::PressureChange::isValid().
The documentation for this class was generated from the following files:
HexagonMachineScheduler.h
HexagonMachineScheduler.cpp