LLVM: llvm::DITemplateTypeParameter Class Reference
LLVM API Documentation
llvm::DITemplateTypeParameter Class Reference
DITemplateTypeParameter - This is a wrapper for template type parameter.
#include <DebugInfo.h>
Public Member Functions
DITemplateTypeParameter (const MDNode *N=0)
DIScopeRef getContext () const
StringRef getName () const
DITypeRef getType () const
StringRef getFilename () const
StringRef getDirectory () const
unsigned getLineNumber () const
unsigned getColumnNumber () const
bool Verify () const
Verify that the template type parameter descriptor is well formed.
Public Member Functions inherited from llvm::DIDescriptor
DIDescriptor (const MDNode *N=0)
bool Verify () const
operator MDNode * () const
MDNode * operator-> () const
LLVM_EXPLICIT operator bool () const
bool operator== (DIDescriptor Other) const
bool operator!= (DIDescriptor Other) const
uint16_t getTag () const
bool isDerivedType () const
isDerivedType - Return true if the specified tag is legal for DIDerivedType.
bool isCompositeType () const
bool isBasicType () const
bool isVariable () const
isVariable - Return true if the specified tag is legal for DIVariable.
bool isSubprogram () const
bool isGlobalVariable () const
bool isScope () const
bool isFile () const
isFile - Return true if the specified tag is DW_TAG_file_type.
bool isCompileUnit () const
isCompileUnit - Return true if the specified tag is DW_TAG_compile_unit.
bool isNameSpace () const
isNameSpace - Return true if the specified tag is DW_TAG_namespace.
bool isLexicalBlockFile () const
bool isLexicalBlock () const
isLexicalBlock - Return true if the specified tag is DW_TAG_lexical_block.
bool isSubrange () const
isSubrange - Return true if the specified tag is DW_TAG_subrange_type.
bool isEnumerator () const
isEnumerator - Return true if the specified tag is DW_TAG_enumerator.
bool isType () const
isType - Return true if the specified tag is legal for DIType.
bool isUnspecifiedParameter () const
bool isTemplateTypeParameter () const
bool isTemplateValueParameter () const
bool isObjCProperty () const
isObjCProperty - Return true if the specified tag is DW_TAG_APPLE_property.
bool isImportedEntity () const
Return true if the specified tag is DW_TAG_imported_module or DW_TAG_imported_declaration.
void print (raw_ostream &OS) const
print - print descriptor.
void dump () const
dump - print descriptor to dbgs() with a newline.
Additional Inherited Members
Public Types inherited from llvm::DIDescriptor
enum {
FlagPrivate = 1 << 0, FlagProtected = 1 << 1, FlagFwdDecl = 1 << 2, FlagAppleBlock = 1 << 3,
FlagBlockByrefStruct = 1 << 4, FlagVirtual = 1 << 5, FlagArtificial = 1 << 6, FlagExplicit = 1 << 7,
FlagPrototyped = 1 << 8, FlagObjcClassComplete = 1 << 9, FlagObjectPointer = 1 << 10, FlagVector = 1 << 11,
FlagStaticMember = 1 << 12, FlagIndirectVariable = 1 << 13
}
Protected Member Functions inherited from llvm::DIDescriptor
StringRef getStringField (unsigned Elt) const
unsigned getUnsignedField (unsigned Elt) const
uint64_t getUInt64Field (unsigned Elt) const
int64_t getInt64Field (unsigned Elt) const
DIDescriptor getDescriptorField (unsigned Elt) const
template<typename DescTy >
DescTy getFieldAs (unsigned Elt) const
GlobalVariable * getGlobalVariableField (unsigned Elt) const
Constant * getConstantField (unsigned Elt) const
Function * getFunctionField (unsigned Elt) const
void replaceFunctionField (unsigned Elt, Function *F)
template<>
DIScopeRef getFieldAs (unsigned Elt) const
Specialize getFieldAs to handle fields that are references to DIScopes.
template<>
DITypeRef getFieldAs (unsigned Elt) const
Specialize getFieldAs to handle fields that are references to DITypes.
template<>
DIScopeRef getFieldAs (unsigned Elt) const
Specialize getFieldAs to handle fields that are references to DIScopes.
template<>
DITypeRef getFieldAs (unsigned Elt) const
Specialize getFieldAs to handle fields that are references to DITypes.
Protected Attributes inherited from llvm::DIDescriptor
const MDNode * DbgNode
Detailed Description
DITemplateTypeParameter - This is a wrapper for template type parameter.
Definition at line 537 of file DebugInfo.h.
Constructor & Destructor Documentation
llvm::DITemplateTypeParameter::DITemplateTypeParameter (const MDNode * N = 0) inline explicit
Definition at line 539 of file DebugInfo.h.
Member Function Documentation
unsigned llvm::DITemplateTypeParameter::getColumnNumber () const inline
Definition at line 549 of file DebugInfo.h.
References llvm::DIDescriptor::getUnsignedField(), and llvm::DIDescriptor::Verify().
DIScopeRef llvm::DITemplateTypeParameter::getContext () const inline
Definition at line 541 of file DebugInfo.h.
Referenced by llvm::DebugInfoFinder::processLocation().
StringRef llvm::DITemplateTypeParameter::getDirectory () const inline
Definition at line 545 of file DebugInfo.h.
StringRef llvm::DITemplateTypeParameter::getFilename () const inline
Definition at line 544 of file DebugInfo.h.
References getFilename().
Referenced by getFilename().
unsigned llvm::DITemplateTypeParameter::getLineNumber () const inline
Definition at line 548 of file DebugInfo.h.
References llvm::DIDescriptor::getUnsignedField().
StringRef llvm::DITemplateTypeParameter::getName () const inline
Definition at line 542 of file DebugInfo.h.
References llvm::DIDescriptor::getStringField().
Referenced by shouldCreateTypeUnit().
DITypeRef llvm::DITemplateTypeParameter::getType () const inline
Definition at line 543 of file DebugInfo.h.
Referenced by llvm::DebugInfoFinder::processLocation(), and shouldCreateTypeUnit().
bool DITemplateTypeParameter::Verify () const
Verify that the template type parameter descriptor is well formed.
Definition at line 603 of file DebugInfo.cpp.
Referenced by llvm::DIDescriptor::Verify().
The documentation for this class was generated from the following files:
DebugInfo.h
DebugInfo.cpp