LLVM: llvm::FunctionPass Class Reference
LLVM API Documentation
llvm::FunctionPass Class Reference abstract
#include <Pass.h>
Public Member Functions
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const
createPrinterPass - Get a function printer pass.
virtual bool runOnFunction (Function &F)=0
virtual void assignPassManager (PMStack &PMS, PassManagerType T)
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void getAnalysisUsage (AnalysisUsage &) const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
FunctionPass class - This class is used to implement most global optimizations. Optimizations should subclass this class if they meet the following constraints:
Optimizations are organized globally, i.e., a function at a time
Optimizing a function does not cause the addition or removal of any functions in the module
Definition at line 293 of file Pass.h.
Constructor & Destructor Documentation
llvm::FunctionPass::FunctionPass (char & pid) inline explicit
Definition at line 295 of file Pass.h.
References llvm::Pass::assignPassManager(), llvm::Pass::createPrinterPass(), F(), and llvm::Pass::getPotentialPassManagerType().
Member Function Documentation
void FunctionPass::assignPassManager (PMStack & PMS, PassManagerType PreferredType) virtual
Find appropriate Function Pass Manager or Call Graph Pass Manager in the PM Stack and add self into that manager.
Reimplemented from llvm::Pass.
Definition at line 1844 of file LegacyPassManager.cpp.
References llvm::PMDataManager::add(), llvm::PMTopLevelManager::addIndirectPassManager(), llvm::ModulePass::assignPassManager(), llvm::PMStack::empty(), llvm::PMDataManager::getPassManagerType(), llvm::PMT_FunctionPassManager, llvm::PMStack::pop(), llvm::PMDataManager::populateInheritedAnalysis(), llvm::PMStack::push(), and llvm::PMStack::top().
Pass * FunctionPass::createPrinterPass (raw_ostream & O, const std::string & Banner) const virtual
createPrinterPass - Get a function printer pass.
Implements llvm::Pass.
Definition at line 131 of file Pass.cpp.
References llvm::createPrintFunctionPass().
PassManagerType FunctionPass::getPotentialPassManagerType () const virtual
Return what kind of Pass Manager can manage this pass.
Reimplemented from llvm::Pass.
Definition at line 136 of file Pass.cpp.
References llvm::PMT_FunctionPassManager.
virtual bool llvm::FunctionPass::runOnFunction (Function & F) pure virtual
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
Implemented in llvm::DependenceAnalysis, llvm::ScalarEvolution, llvm::DominatorTree, llvm::RegionInfo, llvm::LoopInfo, llvm::MemoryDependenceAnalysis, llvm::DominanceFrontier, llvm::StackProtector, llvm::RGPassManager, llvm::InstCombiner, llvm::LPPassManager, llvm::LazyValueInfo, llvm::IntervalPartition, llvm::DOTGraphTraitsPrinter< Analysis, Simple >, llvm::LibCallAliasAnalysis, llvm::BranchProbabilityInfo, llvm::UnifyFunctionExitNodes, llvm::BlockFrequencyInfo, llvm::NVPTXAllocaHoisting, llvm::PostDominatorTree, llvm::NVPTXLowerAggrCopies, llvm::NVPTXSplitBBatBar, and llvm::DOTGraphTraitsViewer< Analysis, Simple >.
Referenced by llvm::FPPassManager::runOnFunction().
The documentation for this class was generated from the following files:
Pass.h
LegacyPassManager.cpp
Pass.cpp