LLVM: llvm::MCDwarfFile Class Reference
LLVM API Documentation
llvm::MCDwarfFile Class Reference
#include <MCDwarf.h>
Public Member Functions
StringRef getName () const
getName - Get the base name of this MCDwarfFile.
unsigned getDirIndex () const
getDirIndex - Get the dirIndex of this MCDwarfFile.
void print (raw_ostream &OS) const
print - Print the value to the stream OS.
void dump () const
dump - Print the value to stderr.
Friends
class MCContext
Detailed Description
MCDwarfFile - Instances of this class represent the name of the dwarf .file directive and its associated dwarf file number in the MC file, and MCDwarfFile's are created and unique'd by the MCContext class where the file number for each is its index into the vector of DwarfFiles (note index 0 is not used and not a valid dwarf file number).
Definition at line 39 of file MCDwarf.h.
Member Function Documentation
void MCDwarfFile::dump () const
dump - Print the value to stderr.
Definition at line 445 of file MCDwarf.cpp.
References llvm::dbgs().
Referenced by getDirIndex().
unsigned llvm::MCDwarfFile::getDirIndex () const inline
getDirIndex - Get the dirIndex of this MCDwarfFile.
Definition at line 60 of file MCDwarf.h.
References dump(), and print().
StringRef llvm::MCDwarfFile::getName () const inline
getName - Get the base name of this MCDwarfFile.
Definition at line 57 of file MCDwarf.h.
void MCDwarfFile::print (raw_ostream & OS) const
print - Print the value to the stream OS.
Definition at line 440 of file MCDwarf.cpp.
References llvm::Intrinsic::getName().
Referenced by getDirIndex(), and llvm::operator<<().
Friends And Related Function Documentation
friend class MCContext friend
Definition at line 48 of file MCDwarf.h.
The documentation for this class was generated from the following files:
MCDwarf.h
MCDwarf.cpp