LLVM: llvm::MCSymbolData Class Reference
LLVM API Documentation
llvm::MCSymbolData Class Reference
#include <MCAssembler.h>
Public Member Functions
MCSymbolData ()
MCSymbolData (const MCSymbol &_Symbol, MCFragment *_Fragment, uint64_t _Offset, MCAssembler *A=0)
void dump ()
Accessors
const MCSymbol & getSymbol () const
MCFragment * getFragment () const
void setFragment (MCFragment *Value)
uint64_t getOffset () const
void setOffset (uint64_t Value)
Symbol Attributes
bool isExternal () const
void setExternal (bool Value)
bool isPrivateExtern () const
void setPrivateExtern (bool Value)
bool isCommon () const
isCommon - Is this a 'common' symbol.
void setCommon (uint64_t Size, unsigned Align)
uint64_t getCommonSize () const
getCommonSize - Return the size of a 'common' symbol.
void setSize (const MCExpr *SS)
const MCExpr * getSize () const
unsigned getCommonAlignment () const
getCommonAlignment - Return the alignment of a 'common' symbol.
uint32_t getFlags () const
getFlags - Get the (implementation defined) symbol flags.
void setFlags (uint32_t Value)
setFlags - Set the (implementation defined) symbol flags.
void modifyFlags (uint32_t Value, uint32_t Mask)
modifyFlags - Modify the flags via a mask
uint64_t getIndex () const
getIndex - Get the (implementation defined) index.
void setIndex (uint64_t Value)
setIndex - Set the (implementation defined) index.
Public Member Functions inherited from llvm::ilist_node< MCSymbolData >
MCSymbolData * getPrevNode ()
Get the previous node, or 0 for the list head.
const MCSymbolData * getPrevNode () const
Get the previous node, or 0 for the list head.
MCSymbolData * getNextNode ()
Get the next node, or 0 for the list tail.
const MCSymbolData * getNextNode () const
Get the next node, or 0 for the list tail.
Public Attributes
const MCSymbol * Symbol
MCFragment * Fragment
Fragment - The fragment this symbol's value is relative to, if any.
uint64_t Offset
unsigned IsExternal: 1
unsigned IsPrivateExtern: 1
IsPrivateExtern - True if this symbol is private extern.
uint64_t CommonSize
CommonSize - The size of the symbol, if it is 'common', or 0.
const MCExpr * SymbolSize
unsigned CommonAlign
CommonAlign - The alignment of the symbol, if it is 'common'.
uint32_t Flags
uint64_t Index
Index - Index field, for use by the object file implementation.
Additional Inherited Members
Protected Member Functions inherited from llvm::ilist_node< MCSymbolData >
ilist_node ()
Detailed Description
Definition at line 669 of file MCAssembler.h.
Constructor & Destructor Documentation
MCSymbolData::MCSymbolData ()
Definition at line 278 of file MCAssembler.cpp.
MCSymbolData::MCSymbolData (const MCSymbol & _Symbol, MCFragment * _Fragment, uint64_t _Offset, MCAssembler * A = 0)
Definition at line 280 of file MCAssembler.cpp.
References llvm::MCAssembler::getSymbolList(), and llvm::iplist< NodeTy, Traits >::push_back().
Member Function Documentation
void MCSymbolData::dump ()
Definition at line 1140 of file MCAssembler.cpp.
References llvm::errs().
unsigned llvm::MCSymbolData::getCommonAlignment () const inline
getCommonAlignment - Return the alignment of a 'common' symbol.
Definition at line 764 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::WriteNlist().
uint64_t llvm::MCSymbolData::getCommonSize () const inline
getCommonSize - Return the size of a 'common' symbol.
Definition at line 749 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::WriteNlist().
uint32_t llvm::MCSymbolData::getFlags () const inline
getFlags - Get the (implementation defined) symbol flags.
Definition at line 770 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::BindIndirectSymbols(), compareBySuffix(), llvm::MachObjectWriter::doesSymbolRequireExternRelocation(), llvm::MCELFStreamer::EmitWeakReference(), getARMFixupKindMachOInfo(), llvm::MCELF::GetBinding(), GetFPUName(), llvm::MCELF::getOther(), llvm::MCELF::GetType(), llvm::MCELF::GetVisibility(), llvm::MCELF::SetBinding(), llvm::MCELF::setOther(), llvm::MCELF::SetType(), llvm::MCELF::SetVisibility(), write_uint32_le(), and llvm::MachObjectWriter::WriteNlist().
MCFragment* llvm::MCSymbolData::getFragment () const inline
Definition at line 720 of file MCAssembler.h.
Referenced by llvm::MCObjectStreamer::EmitLabel(), getARMFixupKindMachOInfo(), llvm::MCAssembler::getAtom(), getFixupKindLog2Size(), getFixupOffset(), llvm::MachObjectWriter::getSymbolAddress(), llvm::MCAsmLayout::getSymbolOffset(), llvm::MCObjectWriter::IsSymbolRefDifferenceFullyResolved(), and llvm::MachObjectWriter::IsSymbolRefDifferenceFullyResolvedImpl().
uint64_t llvm::MCSymbolData::getIndex () const inline
getIndex - Get the (implementation defined) index.
Definition at line 781 of file MCAssembler.h.
Referenced by getARMFixupKindMachOInfo(), getFixupKindLog2Size(), getFixupOffset(), and llvm::MachObjectWriter::WriteObject().
uint64_t llvm::MCSymbolData::getOffset () const inline
Definition at line 723 of file MCAssembler.h.
Referenced by llvm::MCAsmLayout::getSymbolOffset().
const MCExpr* llvm::MCSymbolData::getSize () const inline
Definition at line 758 of file MCAssembler.h.
References llvm::COFF::SymbolSize.
const MCSymbol& llvm::MCSymbolData::getSymbol () const inline
Definition at line 718 of file MCAssembler.h.
References llvm::ARMBuildAttrs::Symbol.
Referenced by llvm::MCELFStreamer::Flush(), getARMFixupKindMachOInfo(), llvm::MCAssembler::getAtom(), getFixupKindLog2Size(), getFixupOffset(), llvm::MachObjectWriter::getSymbolAddress(), llvm::MCAsmLayout::getSymbolOffset(), llvm::MCObjectWriter::IsSymbolRefDifferenceFullyResolvedImpl(), llvm::MachObjectWriter::IsSymbolRefDifferenceFullyResolvedImpl(), llvm::MachObjectWriter::markAbsoluteVariableSymbols(), write_uint32_le(), and llvm::MachObjectWriter::WriteNlist().
bool llvm::MCSymbolData::isCommon () const inline
isCommon - Is this a 'common' symbol.
Definition at line 737 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::WriteNlist().
bool llvm::MCSymbolData::isExternal () const inline
Definition at line 730 of file MCAssembler.h.
Referenced by getFixupKindLog2Size(), NeedsMatchingLo(), write_uint32_le(), llvm::MachObjectWriter::WriteNlist(), and llvm::MachObjectWriter::WriteObject().
bool llvm::MCSymbolData::isPrivateExtern () const inline
Definition at line 733 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::WriteNlist().
void llvm::MCSymbolData::modifyFlags (uint32_t Value, uint32_t Mask) inline
modifyFlags - Modify the flags via a mask
Definition at line 776 of file MCAssembler.h.
void llvm::MCSymbolData::setCommon (uint64_t Size, unsigned Align) inline
setCommon - Mark this symbol as being 'common'.
Parameters
Size - The size of the symbol.
Align - The alignment of the symbol.
Definition at line 743 of file MCAssembler.h.
References Align.
Referenced by llvm::MCELFStreamer::EmitCommonSymbol().
void llvm::MCSymbolData::setExternal (bool Value) inline
Definition at line 731 of file MCAssembler.h.
Referenced by llvm::MCELFStreamer::EmitCommonSymbol(), llvm::MCELFStreamer::EmitLocalCommonSymbol(), llvm::MCELFStreamer::EmitSymbolAttribute(), and GetFPUName().
void llvm::MCSymbolData::setFlags (uint32_t Value) inline
setFlags - Set the (implementation defined) symbol flags.
Definition at line 773 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::BindIndirectSymbols(), llvm::MCELFStreamer::EmitWeakReference(), GetFPUName(), llvm::MCELF::SetBinding(), llvm::MCELF::setOther(), llvm::MCELF::SetType(), and llvm::MCELF::SetVisibility().
void llvm::MCSymbolData::setFragment (MCFragment * Value) inline
Definition at line 721 of file MCAssembler.h.
Referenced by llvm::MCObjectStreamer::EmitLabel(), and llvm::MCELFStreamer::Flush().
void llvm::MCSymbolData::setIndex (uint64_t Value) inline
setIndex - Set the (implementation defined) index.
Definition at line 784 of file MCAssembler.h.
References llvm::MCFragment::dump().
void llvm::MCSymbolData::setOffset (uint64_t Value) inline
Definition at line 724 of file MCAssembler.h.
Referenced by llvm::MCObjectStreamer::EmitLabel().
void llvm::MCSymbolData::setPrivateExtern (bool Value) inline
Definition at line 734 of file MCAssembler.h.
void llvm::MCSymbolData::setSize (const MCExpr * SS) inline
Definition at line 754 of file MCAssembler.h.
Referenced by llvm::MCELFStreamer::EmitCommonSymbol(), and llvm::MCELFStreamer::EmitELFSize().
Member Data Documentation
unsigned llvm::MCSymbolData::CommonAlign
CommonAlign - The alignment of the symbol, if it is 'common'.
Definition at line 700 of file MCAssembler.h.
uint64_t llvm::MCSymbolData::CommonSize
CommonSize - The size of the symbol, if it is 'common', or 0.
Definition at line 691 of file MCAssembler.h.
uint32_t llvm::MCSymbolData::Flags
Flags - The Flags field is used by object file implementations to store additional per symbol information which is not easily classified.
Definition at line 704 of file MCAssembler.h.
MCFragment* llvm::MCSymbolData::Fragment
Fragment - The fragment this symbol's value is relative to, if any.
Definition at line 674 of file MCAssembler.h.
Referenced by write_uint32_le().
uint64_t llvm::MCSymbolData::Index
Index - Index field, for use by the object file implementation.
Definition at line 707 of file MCAssembler.h.
unsigned llvm::MCSymbolData::IsExternal
IsExternal - True if this symbol is visible outside this translation unit.
Definition at line 682 of file MCAssembler.h.
unsigned llvm::MCSymbolData::IsPrivateExtern
IsPrivateExtern - True if this symbol is private extern.
Definition at line 685 of file MCAssembler.h.
uint64_t llvm::MCSymbolData::Offset
Offset - The offset to apply to the fragment address to form this symbol's value.
Definition at line 678 of file MCAssembler.h.
Referenced by write_uint32_le().
const MCSymbol* llvm::MCSymbolData::Symbol
Definition at line 671 of file MCAssembler.h.
Referenced by llvm::MachObjectWriter::doesSymbolRequireExternRelocation(), getARMFixupKindMachOInfo(), getFixupKindLog2Size(), and getFixupOffset().
const MCExpr* llvm::MCSymbolData::SymbolSize
SymbolSize - An expression describing how to calculate the size of a symbol. If a symbol has no size this field will be NULL.
Definition at line 695 of file MCAssembler.h.
The documentation for this class was generated from the following files:
MCAssembler.h
MCAssembler.cpp