LLVM: llvm::BasicBlockEdge Class Reference
LLVM API Documentation
llvm::BasicBlockEdge Class Reference
#include <Dominators.h>
Public Member Functions
BasicBlockEdge (const BasicBlock *Start_, const BasicBlock *End_)
const BasicBlock * getStart () const
const BasicBlock * getEnd () const
bool isSingleEdge () const
Detailed Description
Definition at line 721 of file Dominators.h.
Constructor & Destructor Documentation
llvm::BasicBlockEdge::BasicBlockEdge (const BasicBlock * Start_, const BasicBlock * End_) inline
Definition at line 725 of file Dominators.h.
Member Function Documentation
const BasicBlock* llvm::BasicBlockEdge::getEnd () const inline
Definition at line 730 of file Dominators.h.
Referenced by llvm::DominatorTree::dominates(), and isOnlyReachableViaThisEdge().
const BasicBlock* llvm::BasicBlockEdge::getStart () const inline
Definition at line 727 of file Dominators.h.
Referenced by llvm::DominatorTree::dominates(), and isOnlyReachableViaThisEdge().
bool BasicBlockEdge::isSingleEdge () const
Definition at line 42 of file Dominators.cpp.
References llvm::TerminatorInst::getNumSuccessors(), llvm::TerminatorInst::getSuccessor(), llvm::BasicBlock::getTerminator(), i, llvm::DominatorTree::ID, n, and llvm::TEMPLATE_INSTANTIATION().
Referenced by llvm::DominatorTree::dominates().
The documentation for this class was generated from the following files:
Dominators.h
Dominators.cpp