LLVM: llvm::R600SchedStrategy Class Reference
LLVM API Documentation
llvm::R600SchedStrategy Class Reference
#include <R600MachineScheduler.h>
Public Member Functions
R600SchedStrategy ()
virtual ~R600SchedStrategy ()
virtual void initialize (ScheduleDAGMI *dag)
Initialize the strategy after building the DAG for a new region.
virtual SUnit * pickNode (bool &IsTopNode)
virtual void schedNode (SUnit *SU, bool IsTopNode)
virtual void releaseTopNode (SUnit *SU)
virtual void releaseBottomNode (SUnit *SU)
Public Member Functions inherited from llvm::MachineSchedStrategy
virtual ~MachineSchedStrategy ()
virtual void initPolicy (MachineBasicBlock::iterator Begin, MachineBasicBlock::iterator End, unsigned NumRegionInstrs)
Optionally override the per-region scheduling policy.
virtual bool shouldTrackPressure () const
virtual void registerRoots ()
virtual void scheduleTree (unsigned SubtreeID)
Scheduler callback to notify that a new subtree is scheduled.
Detailed Description
Definition at line 27 of file R600MachineScheduler.h.
Constructor & Destructor Documentation
llvm::R600SchedStrategy::R600SchedStrategy () inline
Definition at line 70 of file R600MachineScheduler.h.
virtual llvm::R600SchedStrategy::~R600SchedStrategy () inline virtual
Definition at line 74 of file R600MachineScheduler.h.
References initialize(), llvm::A64CC::MI, pickNode(), releaseBottomNode(), releaseTopNode(), and schedNode().
Member Function Documentation
void R600SchedStrategy::initialize (ScheduleDAGMI * DAG) virtual
Initialize the strategy after building the DAG for a new region.
Implements llvm::MachineSchedStrategy.
Definition at line 26 of file R600MachineScheduler.cpp.
References llvm::R600InstrInfo::getMaxAlusPerClause(), llvm::TargetMachine::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::AMDGPUSubtarget::getTexVTXClauseSize(), llvm::ScheduleDAG::MF, llvm::ScheduleDAG::MRI, llvm::A64DB::ST, llvm::ScheduleDAG::TII, llvm::ScheduleDAG::TM, and llvm::ScheduleDAG::TRI.
Referenced by ~R600SchedStrategy().
SUnit * R600SchedStrategy::pickNode (bool & IsTopNode) virtual
Pick the next node to schedule, or return NULL. Set IsTopNode to true to schedule the node at the top of the unscheduled region. Otherwise it will be scheduled at the bottom.
Implements llvm::MachineSchedStrategy.
Definition at line 58 of file R600MachineScheduler.cpp.
References llvm::dbgs(), DEBUG, llvm::SUnit::dump(), getWFCountLimitedByGPR(), i, llvm::SUnit::isScheduled, S, size, and llvm::ScheduleDAG::SUnits.
Referenced by ~R600SchedStrategy().
void R600SchedStrategy::releaseBottomNode (SUnit * SU) virtual
When all successor dependencies have been resolved, free this node for bottom-up scheduling.
Implements llvm::MachineSchedStrategy.
Definition at line 193 of file R600MachineScheduler.cpp.
References base, llvm::MachineRegisterInfo::constrainRegClass(), llvm::TargetRegisterClass::contains(), llvm::TargetOpcode::COPY, llvm::dbgs(), DEBUG, llvm::SUnit::dump(), llvm::R600InstrInfo::fitsConstReadLimitations(), llvm::SUnit::getInstr(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::R600InstrInfo::getOperandIdx(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineOperand::getSubReg(), i, llvm::R600InstrInfo::isALUInstr(), llvm::R600InstrInfo::isCubeOp(), llvm::MachineOperand::isDef(), llvm::R600InstrInfo::isLDSInstr(), isPhysicalRegCopy(), llvm::R600InstrInfo::isReductionOp(), llvm::MachineOperand::isReg(), llvm::R600InstrInfo::isTransOnly(), llvm::MachineOperand::isUndef(), llvm::R600InstrInfo::isVector(), llvm::R600InstrInfo::isVectorOnly(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::A64CC::MI, llvm::MachineInstr::operands_begin(), llvm::MachineInstr::operands_end(), llvm::R600InstrInfo::readsLDSSrcReg(), llvm::R600InstrInfo::usesTextureCache(), and llvm::R600InstrInfo::usesVertexCache().
Referenced by ~R600SchedStrategy().
void R600SchedStrategy::releaseTopNode (SUnit * SU) virtual
When all predecessor dependencies have been resolved, free this node for top-down scheduling.
Implements llvm::MachineSchedStrategy.
Definition at line 189 of file R600MachineScheduler.cpp.
References llvm::dbgs(), DEBUG, and llvm::SUnit::dump().
Referenced by ~R600SchedStrategy().
void R600SchedStrategy::schedNode (SUnit * SU, bool IsTopNode) virtual
Notify MachineSchedStrategy that ScheduleDAGMI has scheduled an instruction and updated scheduled/remaining flags in the DAG nodes.
Implements llvm::MachineSchedStrategy.
Definition at line 141 of file R600MachineScheduler.cpp.
References llvm::dbgs(), DEBUG, llvm::SUnit::getInstr(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isReg(), llvm::MachineInstr::operands_begin(), and llvm::MachineInstr::operands_end().
Referenced by ~R600SchedStrategy().
The documentation for this class was generated from the following files:
R600MachineScheduler.h
R600MachineScheduler.cpp