LLVM: llvm::LiveDebugVariables Class Reference
LLVM API Documentation
llvm::LiveDebugVariables Class Reference
#include <LiveDebugVariables.h>
Public Member Functions
LiveDebugVariables ()
~LiveDebugVariables ()
void renameRegister (unsigned OldReg, unsigned NewReg, unsigned SubIdx)
void splitRegister (unsigned OldReg, ArrayRef< unsigned > NewRegs, LiveIntervals &LIS)
void emitDebugValues (VirtRegMap *VRM)
void dump ()
dump - Print data structures to dbgs().
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const
createPrinterPass - Get a function printer pass.
virtual void assignPassManager (PMStack &PMS, PassManagerType T)
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
Detailed Description
Definition at line 33 of file LiveDebugVariables.h.
Constructor & Destructor Documentation
LiveDebugVariables::LiveDebugVariables ()
Definition at line 67 of file LiveDebugVariables.cpp.
References llvm::PassRegistry::getPassRegistry(), and llvm::initializeLiveDebugVariablesPass().
LiveDebugVariables::~LiveDebugVariables ()
Definition at line 725 of file LiveDebugVariables.cpp.
References llvm::LiveRange::advanceTo(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::advanceTo(), llvm::LiveRange::begin(), llvm::LiveRange::beginIndex(), llvm::MachineOperand::CreateReg(), llvm::dbgs(), DEBUG, llvm::LiveRange::empty(), llvm::LiveRange::end(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::erase(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::find(), llvm::LiveIntervals::getInterval(), llvm::MachineOperand::getReg(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::goToBegin(), i, llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::insert(), llvm::MachineOperand::isReg(), llvm::Pass::print(), llvm::LiveInterval::reg, llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::setMap(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setStartUnchecked(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setStopUnchecked(), llvm::MachineOperand::setSubReg(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setValue(), llvm::IntervalMap< KeyT, ValT, N, Traits >::iterator::setValueUnchecked(), llvm::ArrayRef< T >::size(), splitRegister(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::start(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::stop(), llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::valid(), and llvm::IntervalMap< KeyT, ValT, N, Traits >::const_iterator::value().
Member Function Documentation
void LiveDebugVariables::dump ()
dump - Print data structures to dbgs().
Definition at line 993 of file LiveDebugVariables.cpp.
References llvm::dbgs(), and llvm::Pass::print().
void LiveDebugVariables::emitDebugValues (VirtRegMap * VRM)
emitDebugValues - Emit new DBG_VALUE instructions reflecting the changes that happened during register allocation.
Parameters
VRM Rename virtual registers according to map.
Definition at line 986 of file LiveDebugVariables.cpp.
void llvm::LiveDebugVariables::renameRegister (unsigned OldReg, unsigned NewReg, unsigned SubIdx)
renameRegister - Move any user variables in OldReg to NewReg:SubIdx.
Parameters
OldReg Old virtual register that is going away.
NewReg New register holding the user variables.
SubIdx If NewReg is a virtual register, SubIdx may indicate a sub- register.
void LiveDebugVariables::splitRegister (unsigned OldReg, ArrayRef< unsigned > NewRegs, LiveIntervals & LIS)
splitRegister - Move any user variables in OldReg to the live ranges in NewRegs where they are live. Mark the values as unavailable where no new register is live.
Definition at line 864 of file LiveDebugVariables.cpp.
References llvm::MachineOperand::CreateFI(), llvm::VirtRegMap::getPhys(), llvm::MachineOperand::getReg(), llvm::VirtRegMap::getStackSlot(), i, llvm::VirtRegMap::isAssignedReg(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::MachineOperand::isReg(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::VirtRegMap::NO_STACK_SLOT, llvm::MachineOperand::setReg(), llvm::MachineOperand::setSubReg(), and llvm::MachineOperand::substPhysReg().
Referenced by llvm::createGreedyRegisterAllocator(), and ~LiveDebugVariables().
Member Data Documentation
char LiveDebugVariables::ID = 0 static
Definition at line 36 of file LiveDebugVariables.h.
The documentation for this class was generated from the following files:
LiveDebugVariables.h
LiveDebugVariables.cpp