LLVM: llvm::IVVisitor Class Reference
LLVM API Documentation
llvm::IVVisitor Class Reference abstract
#include <SimplifyIndVar.h>
Public Member Functions
virtual ~IVVisitor ()
virtual void visitCast (CastInst *Cast)=0
Detailed Description
Interface for visiting interesting IV users that are recognized but not simplified by this utility.
Definition at line 33 of file SimplifyIndVar.h.
Constructor & Destructor Documentation
virtual llvm::IVVisitor::~IVVisitor () inline virtual
Definition at line 36 of file SimplifyIndVar.h.
References llvm::RegState::Dead, llvm::simplifyLoopIVs(), llvm::simplifyUsersOfIV(), and visitCast().
Member Function Documentation
virtual void llvm::IVVisitor::visitCast (CastInst * Cast) pure virtual
Referenced by isSimpleIVUser(), and ~IVVisitor().
The documentation for this class was generated from the following files:
SimplifyIndVar.h
SimplifyIndVar.cpp