LLVM: llvm::SectionKind Class Reference
LLVM API Documentation
llvm::SectionKind Class Reference
#include <SectionKind.h>
Public Member Functions
bool isMetadata () const
bool isText () const
bool isReadOnly () const
bool isMergeableCString () const
bool isMergeable1ByteCString () const
bool isMergeable2ByteCString () const
bool isMergeable4ByteCString () const
bool isMergeableConst () const
bool isMergeableConst4 () const
bool isMergeableConst8 () const
bool isMergeableConst16 () const
bool isWriteable () const
bool isThreadLocal () const
bool isThreadBSS () const
bool isThreadData () const
bool isGlobalWriteableData () const
bool isBSS () const
bool isBSSLocal () const
bool isBSSExtern () const
bool isCommon () const
bool isDataRel () const
bool isDataRelLocal () const
bool isDataNoRel () const
bool isReadOnlyWithRel () const
bool isReadOnlyWithRelLocal () const
Static Public Member Functions
static SectionKind getMetadata ()
static SectionKind getText ()
static SectionKind getReadOnly ()
static SectionKind getMergeable1ByteCString ()
static SectionKind getMergeable2ByteCString ()
static SectionKind getMergeable4ByteCString ()
static SectionKind getMergeableConst ()
static SectionKind getMergeableConst4 ()
static SectionKind getMergeableConst8 ()
static SectionKind getMergeableConst16 ()
static SectionKind getThreadBSS ()
static SectionKind getThreadData ()
static SectionKind getBSS ()
static SectionKind getBSSLocal ()
static SectionKind getBSSExtern ()
static SectionKind getCommon ()
static SectionKind getDataRel ()
static SectionKind getDataRelLocal ()
static SectionKind getDataNoRel ()
static SectionKind getReadOnlyWithRel ()
static SectionKind getReadOnlyWithRelLocal ()
Detailed Description
SectionKind - This is a simple POD value that classifies the properties of a section. A section is classified into the deepest possible classification, and then the target maps them onto their sections based on what capabilities they have.
The comments below describe these as if they were an inheritance hierarchy in order to explain the predicates below.
Definition at line 28 of file SectionKind.h.
Member Function Documentation
static SectionKind llvm::SectionKind::getBSS () inline static
Definition at line 225 of file SectionKind.h.
Referenced by llvm::MCELFStreamer::EmitCommonSymbol(), getELFKindForNamedSection(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::XCoreTargetObjectFile::Initialize(), llvm::HexagonTargetObjectFile::Initialize(), llvm::MipsTargetObjectFile::Initialize(), and llvm::NVPTXTargetObjectFile::Initialize().
static SectionKind llvm::SectionKind::getBSSExtern () inline static
Definition at line 227 of file SectionKind.h.
Referenced by llvm::TargetLoweringObjectFile::getKindForGlobal().
static SectionKind llvm::SectionKind::getBSSLocal () inline static
Definition at line 226 of file SectionKind.h.
Referenced by llvm::TargetLoweringObjectFile::getKindForGlobal().
static SectionKind llvm::SectionKind::getCommon () inline static
Definition at line 228 of file SectionKind.h.
Referenced by llvm::TargetLoweringObjectFile::getKindForGlobal().
static SectionKind llvm::SectionKind::getDataNoRel () inline static
Definition at line 231 of file SectionKind.h.
Referenced by llvm::TargetLoweringObjectFileMachO::emitModuleFlags(), and llvm::TargetLoweringObjectFile::getKindForGlobal().
static SectionKind llvm::SectionKind::getDataRel () inline static
Definition at line 229 of file SectionKind.h.
Referenced by computeSectionKind(), llvm::TargetLoweringObjectFileELF::emitPersonalityValue(), GetFPUName(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::TargetLoweringObjectFileELF::getStaticCtorSection(), llvm::TargetLoweringObjectFileELF::getStaticDtorSection(), llvm::getWin64EHFuncTableSection(), llvm::getWin64EHTableSection(), getWin64EHTableSection(), llvm::XCoreTargetObjectFile::Initialize(), llvm::HexagonTargetObjectFile::Initialize(), llvm::MipsTargetObjectFile::Initialize(), llvm::NVPTXTargetObjectFile::Initialize(), llvm::TargetLoweringObjectFileELF::InitializeELF(), llvm::MCObjectFileInfo::InitMCObjectFileInfo(), and llvm::linkErlangGCPrinter().
static SectionKind llvm::SectionKind::getDataRelLocal () inline static
Definition at line 230 of file SectionKind.h.
Referenced by llvm::TargetLoweringObjectFile::getKindForGlobal().
static SectionKind llvm::SectionKind::getMergeable1ByteCString () inline static
Definition at line 210 of file SectionKind.h.
Referenced by llvm::TargetLoweringObjectFile::getKindForGlobal().
static SectionKind llvm::SectionKind::getMergeable2ByteCString () inline static
Definition at line 213 of file SectionKind.h.
Referenced by llvm::TargetLoweringObjectFile::getKindForGlobal().
static SectionKind llvm::SectionKind::getMergeable4ByteCString () inline static
Definition at line 216 of file SectionKind.h.
Referenced by llvm::TargetLoweringObjectFile::getKindForGlobal().
static SectionKind llvm::SectionKind::getMergeableConst () inline static
Definition at line 219 of file SectionKind.h.
Referenced by llvm::AsmPrinter::EmitConstantPool(), and llvm::TargetLoweringObjectFile::getKindForGlobal().
static SectionKind llvm::SectionKind::getMergeableConst16 () inline static
Definition at line 222 of file SectionKind.h.
Referenced by llvm::AsmPrinter::EmitConstantPool(), llvm::TargetLoweringObjectFile::getKindForGlobal(), and llvm::XCoreTargetObjectFile::Initialize().
static SectionKind llvm::SectionKind::getMergeableConst4 () inline static
Definition at line 220 of file SectionKind.h.
Referenced by llvm::AsmPrinter::EmitConstantPool(), llvm::TargetLoweringObjectFile::getKindForGlobal(), and llvm::XCoreTargetObjectFile::Initialize().
static SectionKind llvm::SectionKind::getMergeableConst8 () inline static
Definition at line 221 of file SectionKind.h.
Referenced by llvm::AsmPrinter::EmitConstantPool(), llvm::TargetLoweringObjectFile::getKindForGlobal(), and llvm::XCoreTargetObjectFile::Initialize().
static SectionKind llvm::SectionKind::getMetadata () inline static
Definition at line 207 of file SectionKind.h.
Referenced by llvm::X86AsmPrinter::EmitEndOfAsmFile(), GetFPUName(), llvm::SystemZMCAsmInfo::getNonexecutableStackSection(), llvm::X86ELFMCAsmInfo::getNonexecutableStackSection(), llvm::MipsTargetObjectFile::Initialize(), llvm::ARMElfTargetObjectFile::Initialize(), and llvm::NVPTXTargetObjectFile::Initialize().
static SectionKind llvm::SectionKind::getReadOnly () inline static
Definition at line 209 of file SectionKind.h.
Referenced by compareBySuffix(), computeSectionKind(), llvm::MCContext::CreateELFGroupSection(), llvm::MCELFStreamer::EmitIdent(), llvm::AsmPrinter::EmitJumpTableInfo(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::NVPTXTargetObjectFile::Initialize(), llvm::MCObjectFileInfo::InitMCObjectFileInfo(), parseSectionFlags(), llvm::AMDGPUAsmPrinter::runOnMachineFunction(), and stripRegisterPrefix().
static SectionKind llvm::SectionKind::getReadOnlyWithRel () inline static
Definition at line 232 of file SectionKind.h.
Referenced by llvm::AsmPrinter::EmitConstantPool(), llvm::TargetLoweringObjectFile::getKindForGlobal(), and llvm::XCoreTargetObjectFile::Initialize().
static SectionKind llvm::SectionKind::getReadOnlyWithRelLocal () inline static
Definition at line 233 of file SectionKind.h.
Referenced by llvm::AsmPrinter::EmitConstantPool(), and llvm::TargetLoweringObjectFile::getKindForGlobal().
static SectionKind llvm::SectionKind::getText () inline static
Definition at line 208 of file SectionKind.h.
Referenced by compareBySuffix(), computeSectionKind(), llvm::ARMAsmPrinter::EmitStartOfAsmFile(), GetAnonSym(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::NVPTXTargetObjectFile::Initialize(), and stripRegisterPrefix().
static SectionKind llvm::SectionKind::getThreadBSS () inline static
Definition at line 223 of file SectionKind.h.
Referenced by getELFKindForNamedSection(), and llvm::TargetLoweringObjectFile::getKindForGlobal().
static SectionKind llvm::SectionKind::getThreadData () inline static
Definition at line 224 of file SectionKind.h.
Referenced by computeSectionKind(), getELFKindForNamedSection(), and llvm::TargetLoweringObjectFile::getKindForGlobal().
bool llvm::SectionKind::isBSS () const inline
Definition at line 176 of file SectionKind.h.
Referenced by getCOFFSectionFlags(), getCOFFSectionPrefixForUniqueGlobal(), getELFSectionType(), getSectionPrefixForGlobal(), llvm::HexagonTargetObjectFile::IsGlobalInSmallSection(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), isGlobalWriteableData(), llvm::MipsTargetObjectFile::SelectSectionForGlobal(), llvm::HexagonTargetObjectFile::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFile::SelectSectionForGlobal().
bool llvm::SectionKind::isBSSExtern () const inline
Definition at line 178 of file SectionKind.h.
Referenced by llvm::AsmPrinter::EmitGlobalVariable(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
bool llvm::SectionKind::isBSSLocal () const inline
Definition at line 177 of file SectionKind.h.
Referenced by llvm::AsmPrinter::EmitGlobalVariable(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
bool llvm::SectionKind::isCommon () const inline
Definition at line 180 of file SectionKind.h.
Referenced by llvm::AsmPrinter::EmitGlobalVariable(), llvm::HexagonTargetObjectFile::IsGlobalInSmallSection(), isGlobalWriteableData(), and llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal().
bool llvm::SectionKind::isDataNoRel () const inline
Definition at line 190 of file SectionKind.h.
Referenced by getSectionPrefixForGlobal(), llvm::HexagonTargetObjectFile::IsGlobalInSmallSection(), llvm::HexagonTargetObjectFile::SelectSectionForGlobal(), llvm::MipsTargetObjectFile::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal().
bool llvm::SectionKind::isDataRel () const inline
Definition at line 182 of file SectionKind.h.
Referenced by llvm::TargetLoweringObjectFileMachO::getSectionForConstant(), getSectionPrefixForGlobal(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), isGlobalWriteableData(), and llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal().
bool llvm::SectionKind::isDataRelLocal () const inline
Definition at line 186 of file SectionKind.h.
Referenced by getSectionPrefixForGlobal(), and llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal().
bool llvm::SectionKind::isGlobalWriteableData () const inline
Definition at line 172 of file SectionKind.h.
References isBSS(), isCommon(), isDataRel(), and isReadOnlyWithRel().
Referenced by isWriteable().
bool llvm::SectionKind::isMergeable1ByteCString () const inline
Definition at line 149 of file SectionKind.h.
Referenced by llvm::MCSectionELF::DetermineEntrySize(), llvm::MipsTargetObjectFile::IsGlobalInSmallSection(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
bool llvm::SectionKind::isMergeable2ByteCString () const inline
Definition at line 150 of file SectionKind.h.
Referenced by llvm::MCSectionELF::DetermineEntrySize(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
bool llvm::SectionKind::isMergeable4ByteCString () const inline
Definition at line 151 of file SectionKind.h.
Referenced by llvm::MCSectionELF::DetermineEntrySize(), and llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal().
bool llvm::SectionKind::isMergeableConst () const inline
Definition at line 153 of file SectionKind.h.
Referenced by isReadOnly(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
bool llvm::SectionKind::isMergeableConst16 () const inline
Definition at line 159 of file SectionKind.h.
Referenced by llvm::MCSectionELF::DetermineEntrySize(), getELFSectionFlags(), llvm::TargetLoweringObjectFileELF::getSectionForConstant(), llvm::TargetLoweringObjectFileMachO::getSectionForConstant(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
bool llvm::SectionKind::isMergeableConst4 () const inline
Definition at line 157 of file SectionKind.h.
Referenced by llvm::MCSectionELF::DetermineEntrySize(), getELFSectionFlags(), llvm::TargetLoweringObjectFileELF::getSectionForConstant(), llvm::TargetLoweringObjectFileMachO::getSectionForConstant(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
bool llvm::SectionKind::isMergeableConst8 () const inline
Definition at line 158 of file SectionKind.h.
Referenced by llvm::MCSectionELF::DetermineEntrySize(), getELFSectionFlags(), llvm::TargetLoweringObjectFileELF::getSectionForConstant(), llvm::TargetLoweringObjectFileMachO::getSectionForConstant(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
bool llvm::SectionKind::isMergeableCString () const inline
Definition at line 145 of file SectionKind.h.
Referenced by getELFSectionFlags(), and isReadOnly().
bool llvm::SectionKind::isMetadata () const inline
Definition at line 137 of file SectionKind.h.
Referenced by getCOFFSectionFlags(), getELFSectionFlags(), and shouldAddODRHash().
bool llvm::SectionKind::isReadOnly () const inline
Definition at line 140 of file SectionKind.h.
References isMergeableConst(), and isMergeableCString().
Referenced by getCOFFSectionFlags(), llvm::TargetLoweringObjectFileELF::getSectionForConstant(), llvm::TargetLoweringObjectFile::getSectionForConstant(), getSectionPrefixForGlobal(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFile::SelectSectionForGlobal().
bool llvm::SectionKind::isReadOnlyWithRel () const inline
Definition at line 192 of file SectionKind.h.
Referenced by llvm::TargetLoweringObjectFileELF::getSectionForConstant(), llvm::TargetLoweringObjectFileMachO::getSectionForConstant(), getSectionPrefixForGlobal(), isGlobalWriteableData(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
bool llvm::SectionKind::isReadOnlyWithRelLocal () const inline
Definition at line 196 of file SectionKind.h.
Referenced by llvm::TargetLoweringObjectFileELF::getSectionForConstant(), getSectionPrefixForGlobal(), and llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal().
bool llvm::SectionKind::isText () const inline
Definition at line 138 of file SectionKind.h.
Referenced by llvm::AsmPrinter::EmitAlignment(), getCOFFSectionFlags(), getCOFFSectionPrefixForUniqueGlobal(), getELFSectionFlags(), getSectionPrefixForGlobal(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), llvm::TargetLoweringObjectFile::SelectSectionForGlobal(), and llvm::MCSectionCOFF::UseCodeAlign().
bool llvm::SectionKind::isThreadBSS () const inline
Definition at line 169 of file SectionKind.h.
Referenced by llvm::AsmPrinter::EmitGlobalVariable(), getELFSectionType(), getSectionPrefixForGlobal(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
bool llvm::SectionKind::isThreadData () const inline
Definition at line 170 of file SectionKind.h.
Referenced by llvm::AsmPrinter::EmitGlobalVariable(), getSectionPrefixForGlobal(), llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFileMachO::SelectSectionForGlobal().
bool llvm::SectionKind::isThreadLocal () const inline
Definition at line 165 of file SectionKind.h.
Referenced by llvm::AsmPrinter::EmitGlobalVariable(), getCOFFSectionFlags(), getCOFFSectionPrefixForUniqueGlobal(), getELFSectionFlags(), isWriteable(), llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal(), and llvm::TargetLoweringObjectFile::SelectSectionForGlobal().
bool llvm::SectionKind::isWriteable () const inline
Definition at line 161 of file SectionKind.h.
References isGlobalWriteableData(), and isThreadLocal().
Referenced by getCOFFSectionFlags(), getCOFFSectionPrefixForUniqueGlobal(), and getELFSectionFlags().
The documentation for this class was generated from the following file:
SectionKind.h