LLVM: llvm::MipsSEInstrInfo Class Reference
LLVM API Documentation
llvm::MipsSEInstrInfo Class Reference
#include <MipsSEInstrInfo.h>
Public Member Functions
MipsSEInstrInfo (MipsTargetMachine &TM)
virtual const MipsRegisterInfo & getRegisterInfo () const
virtual unsigned isLoadFromStackSlot (const MachineInstr *MI, int &FrameIndex) const
virtual unsigned isStoreToStackSlot (const MachineInstr *MI, int &FrameIndex) const
virtual void copyPhysReg (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const
virtual void storeRegToStack (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI, int64_t Offset) const
virtual void loadRegFromStack (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI, unsigned DestReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI, int64_t Offset) const
virtual bool expandPostRAPseudo (MachineBasicBlock::iterator MI) const
virtual unsigned getOppositeBranchOpc (unsigned Opc) const
void adjustStackPtr (unsigned SP, int64_t Amount, MachineBasicBlock &MBB, MachineBasicBlock::iterator I) const
Adjust SP by Amount bytes.
unsigned loadImmediate (int64_t Imm, MachineBasicBlock &MBB, MachineBasicBlock::iterator II, DebugLoc DL, unsigned *NewImm) const
Public Member Functions inherited from llvm::MipsInstrInfo
MipsInstrInfo (MipsTargetMachine &TM, unsigned UncondBrOpc)
virtual bool AnalyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify) const
Branch Analysis.
virtual unsigned RemoveBranch (MachineBasicBlock &MBB) const
virtual unsigned InsertBranch (MachineBasicBlock &MBB, MachineBasicBlock *TBB, MachineBasicBlock *FBB, const SmallVectorImpl< MachineOperand > &Cond, DebugLoc DL) const
virtual bool ReverseBranchCondition (SmallVectorImpl< MachineOperand > &Cond) const
BranchType AnalyzeBranch (MachineBasicBlock &MBB, MachineBasicBlock *&TBB, MachineBasicBlock *&FBB, SmallVectorImpl< MachineOperand > &Cond, bool AllowModify, SmallVectorImpl< MachineInstr * > &BranchInstrs) const
virtual void insertNoop (MachineBasicBlock &MBB, MachineBasicBlock::iterator MI) const
Insert nop instruction when hazard condition is found.
unsigned GetInstSizeInBytes (const MachineInstr *MI) const
Return the number of bytes of code the specified instruction may be.
virtual void storeRegToStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const
virtual void loadRegFromStackSlot (MachineBasicBlock &MBB, MachineBasicBlock::iterator MBBI, unsigned DestReg, int FrameIndex, const TargetRegisterClass *RC, const TargetRegisterInfo *TRI) const
MachineInstrBuilder genInstrWithNewOpc (unsigned NewOpc, MachineBasicBlock::iterator I) const
Additional Inherited Members
Public Types inherited from llvm::MipsInstrInfo
enum BranchType {
BT_None, BT_NoBranch, BT_Uncond, BT_Cond,
BT_CondUncond, BT_Indirect
}
Static Public Member Functions inherited from llvm::MipsInstrInfo
static const MipsInstrInfo * create (MipsTargetMachine &TM)
Protected Member Functions inherited from llvm::MipsInstrInfo
bool isZeroImm (const MachineOperand &op) const
MachineMemOperand * GetMemOperand (MachineBasicBlock &MBB, int FI, unsigned Flag) const
Protected Attributes inherited from llvm::MipsInstrInfo
MipsTargetMachine & TM
unsigned UncondBrOpc
Detailed Description
Definition at line 22 of file MipsSEInstrInfo.h.
Constructor & Destructor Documentation
MipsSEInstrInfo::MipsSEInstrInfo (MipsTargetMachine & TM) explicit
Definition at line 27 of file MipsSEInstrInfo.cpp.
Referenced by llvm::createMipsSEInstrInfo().
Member Function Documentation
void MipsSEInstrInfo::adjustStackPtr (unsigned SP, int64_t Amount, MachineBasicBlock & MBB, MachineBasicBlock::iterator I) const
Adjust SP by Amount bytes.
Definition at line 350 of file MipsSEInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::TargetMachine::getSubtarget(), llvm::MipsSubtarget::isABI_N64(), llvm::isInt< 16 >(), llvm::RegState::Kill, loadImmediate(), and llvm::MipsInstrInfo::TM.
Referenced by llvm::MipsSEFrameLowering::eliminateCallFramePseudoInstr().
void MipsSEInstrInfo::copyPhysReg (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, DebugLoc DL, unsigned DestReg, unsigned SrcReg, bool KillSrc) const virtual
Definition at line 82 of file MipsSEInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::RegState::Define, llvm::getKillRegState(), llvm::RegState::Implicit, llvm::RegState::ImplicitDefine, llvm::MipsISD::MFHI, llvm::MipsISD::MFLO, and storeRegToStack().
bool MipsSEInstrInfo::expandPostRAPseudo (MachineBasicBlock::iterator MI) const virtual
Definition at line 260 of file MipsSEInstrInfo.cpp.
References llvm::MipsISD::BuildPairF64, llvm::MachineBasicBlock::erase(), llvm::MipsISD::ExtractElementF64, llvm::MachineBasicBlock::getParent(), llvm::MipsISD::MFHI, and llvm::MipsISD::MFLO.
unsigned MipsSEInstrInfo::getOppositeBranchOpc (unsigned Opc) const virtual
getOppositeBranchOpc - Return the inverse of the specified opcode, e.g. turning BEQ to BNE.
Implements llvm::MipsInstrInfo.
Definition at line 329 of file MipsSEInstrInfo.cpp.
References llvm_unreachable.
const MipsRegisterInfo & MipsSEInstrInfo::getRegisterInfo () const virtual
getRegisterInfo - TargetInstrInfo is a superset of MRegister info. As such, whenever a client has an instance of instruction info, it should always be able to get register info as well (through this method).
Implements llvm::MipsInstrInfo.
Definition at line 33 of file MipsSEInstrInfo.cpp.
References isLoadFromStackSlot().
Referenced by loadImmediate().
unsigned MipsSEInstrInfo::isLoadFromStackSlot (const MachineInstr * MI, int & FrameIndex) const virtual
isLoadFromStackSlot - If the specified machine instruction is a direct load from a stack slot, return the virtual or physical register number of the destination along with the FrameIndex of the loaded stack slot. If not, return 0. This predicate must return 0 if the instruction has any side effects other than loading from the stack slot.
Definition at line 43 of file MipsSEInstrInfo.cpp.
References llvm::MachineOperand::getIndex(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isFI(), llvm::MachineOperand::isImm(), isStoreToStackSlot(), llvm::MipsInstrInfo::isZeroImm(), and llvm::A64DB::LD.
Referenced by getRegisterInfo().
unsigned MipsSEInstrInfo::isStoreToStackSlot (const MachineInstr * MI, int & FrameIndex) const virtual
isStoreToStackSlot - If the specified machine instruction is a direct store to a stack slot, return the virtual or physical register number of the source reg along with the FrameIndex of the loaded stack slot. If not, return 0. This predicate must return 0 if the instruction has any side effects other than storing to the stack slot.
Definition at line 66 of file MipsSEInstrInfo.cpp.
References llvm::MachineOperand::getIndex(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isFI(), llvm::MachineOperand::isImm(), and llvm::MipsInstrInfo::isZeroImm().
Referenced by isLoadFromStackSlot().
unsigned MipsSEInstrInfo::loadImmediate (int64_t Imm, MachineBasicBlock & MBB, MachineBasicBlock::iterator II, DebugLoc DL, unsigned * NewImm) const
Emit a series of instructions to load an immediate. If NewImm is a non-NULL parameter, the last instruction is not emitted, but instead its immediate operand is returned in NewImm.
This function generates the sequence of instructions needed to get the result of adding register REG and immediate IMM.
Definition at line 369 of file MipsSEInstrInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::MipsAnalyzeImmediate::Analyze(), B, llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::BuildMI(), llvm::RegState::Define, llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::MipsTargetMachine::getInstrInfo(), llvm::getKillRegState(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), getRegisterInfo(), llvm::TargetMachine::getRelocationModel(), llvm::MCRegisterInfo::getSubReg(), llvm::TargetMachine::getSubtarget(), I, llvm::MipsSubtarget::isABI_N64(), llvm::MachineOperand::isKill(), llvm::RegState::Kill, N, llvm::MCInstrDesc::NumOperands, llvm::Reloc::PIC_, llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::tie(), and llvm::MipsInstrInfo::TM.
Referenced by adjustStackPtr(), and isMSALoadOrStore().
void MipsSEInstrInfo::loadRegFromStack (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, unsigned DestReg, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI, int64_t Offset) const virtual
Implements llvm::MipsInstrInfo.
Definition at line 220 of file MipsSEInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::MipsInstrInfo::GetMemOperand(), llvm::TargetRegisterClass::hasType(), llvm::A64DB::LD, llvm::MachineMemOperand::MOLoad, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4i32, llvm::MVT::v8f16, and llvm::MVT::v8i16.
Referenced by storeRegToStack().
void MipsSEInstrInfo::storeRegToStack (MachineBasicBlock & MBB, MachineBasicBlock::iterator MI, unsigned SrcReg, bool isKill, int FrameIndex, const TargetRegisterClass * RC, const TargetRegisterInfo * TRI, int64_t Offset) const virtual
Implements llvm::MipsInstrInfo.
Definition at line 177 of file MipsSEInstrInfo.cpp.
References llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::getKillRegState(), llvm::MipsInstrInfo::GetMemOperand(), llvm::TargetRegisterClass::hasType(), loadRegFromStack(), llvm::MachineMemOperand::MOStore, llvm::MVT::v16i8, llvm::MVT::v2f64, llvm::MVT::v2i64, llvm::MVT::v4f32, llvm::MVT::v4i32, llvm::MVT::v8f16, and llvm::MVT::v8i16.
Referenced by copyPhysReg().
The documentation for this class was generated from the following files:
MipsSEInstrInfo.h
MipsSEInstrInfo.cpp