LLVM: llvm::MCGenDwarfLabelEntry Class Reference
LLVM API Documentation
llvm::MCGenDwarfLabelEntry Class Reference
#include <MCDwarf.h>
Public Member Functions
MCGenDwarfLabelEntry (StringRef name, unsigned fileNumber, unsigned lineNumber, MCSymbol *label)
StringRef getName () const
unsigned getFileNumber () const
unsigned getLineNumber () const
MCSymbol * getLabel () const
Static Public Member Functions
static void Make (MCSymbol *Symbol, MCStreamer *MCOS, SourceMgr &SrcMgr, SMLoc &Loc)
Detailed Description
Definition at line 250 of file MCDwarf.h.
Constructor & Destructor Documentation
llvm::MCGenDwarfLabelEntry::MCGenDwarfLabelEntry (StringRef name, unsigned fileNumber, unsigned lineNumber, MCSymbol * label) inline
Definition at line 262 of file MCDwarf.h.
Member Function Documentation
unsigned llvm::MCGenDwarfLabelEntry::getFileNumber () const inline
Definition at line 268 of file MCDwarf.h.
Referenced by EmitGenDwarfInfo().
MCSymbol* llvm::MCGenDwarfLabelEntry::getLabel () const inline
Definition at line 270 of file MCDwarf.h.
References llvm::SrcMgr, and llvm::ARMBuildAttrs::Symbol.
Referenced by EmitGenDwarfInfo().
unsigned llvm::MCGenDwarfLabelEntry::getLineNumber () const inline
Definition at line 269 of file MCDwarf.h.
Referenced by EmitGenDwarfInfo().
StringRef llvm::MCGenDwarfLabelEntry::getName () const inline
Definition at line 267 of file MCDwarf.h.
Referenced by EmitGenDwarfInfo().
void MCGenDwarfLabelEntry::Make (MCSymbol * Symbol, MCStreamer * MCOS, SourceMgr & SrcMgr, SMLoc & Loc) static
Definition at line 771 of file MCDwarf.cpp.
References llvm::MCContext::addMCGenDwarfLabelEntry(), llvm::MCContext::CreateTempSymbol(), llvm::MCStreamer::EmitLabel(), llvm::SourceMgr::FindBufferContainingLoc(), llvm::SourceMgr::FindLineNumber(), llvm::MCStreamer::getContext(), llvm::MCStreamer::getCurrentSection(), llvm::MCContext::getGenDwarfFileNumber(), llvm::MCContext::getGenDwarfSection(), llvm::MCSymbol::getName(), llvm::MCSymbol::isTemporary(), llvm::StringRef::size(), llvm::StringRef::startswith(), and llvm::StringRef::substr().
Referenced by getBinOpPrecedence().
The documentation for this class was generated from the following files:
MCDwarf.h
MCDwarf.cpp