LLVM: llvm::error_code Class Reference
LLVM API Documentation
llvm::error_code Class Reference
#include <system_error.h>
Public Types
typedef void(* unspecified_bool_type) ()
Public Member Functions
error_code ()
error_code (int _val, const error_category &_cat)
template<class E >
error_code (E _e, typename enable_if_c< is_error_code_enum< E >::value >::type *=0)
void assign (int _val, const error_category &_cat)
template<class E >
enable_if_c< is_error_code_enum< E >::value, error_code & >::type operator= (E _e)
void clear ()
int value () const
const error_category & category () const
error_condition default_error_condition () const
std::string message () const
operator unspecified_bool_type () const
Static Public Member Functions
static error_code success ()
static void unspecified_bool_true ()
Detailed Description
Definition at line 726 of file system_error.h.
Member Typedef Documentation
typedef void(* llvm::error_code::unspecified_bool_type) ()
Definition at line 774 of file system_error.h.
Constructor & Destructor Documentation
llvm::error_code::error_code () inline
Definition at line 730 of file system_error.h.
llvm::error_code::error_code (int _val, const error_category & _cat) inline
Definition at line 736 of file system_error.h.
template<class E > llvm::error_code::error_code (E _e, typename enable_if_c< is_error_code_enum< E >::value >::type * = 0) inline
Definition at line 740 of file system_error.h.
References llvm::make_error_code().
Member Function Documentation
void llvm::error_code::assign (int _val, const error_category & _cat) inline
Definition at line 746 of file system_error.h.
const error_category& llvm::error_code::category () const inline
Definition at line 767 of file system_error.h.
Referenced by llvm::error_category::equivalent(), llvm::operator<(), and llvm::operator==().
void llvm::error_code::clear () inline
Definition at line 760 of file system_error.h.
References llvm::system_category().
Referenced by llvm::BitcodeReader::ParseTriple().
error_condition llvm::error_code::default_error_condition () const inline
Definition at line 769 of file system_error.h.
References llvm::error_category::default_error_condition(), and message().
std::string llvm::error_code::message () const
Definition at line 118 of file system_error.cpp.
Referenced by LTOCodeGenerator::compile_to_file(), llvm::createGraphFilename(), llvm::SectionMemoryManager::finalizeMemory(), LLVMCreateMemoryBufferWithContentsOfFile(), LLVMCreateMemoryBufferWithSTDIN(), LLVMMoveToNextRelocation(), LLVMMoveToNextSection(), LLVMMoveToNextSymbol(), llvm::Module::Materialize(), llvm::Module::MaterializeAll(), llvm::object::printRelocationTargetName(), and llvm::raw_fd_ostream::raw_fd_ostream().
llvm::error_code::operator unspecified_bool_type () const inline
Definition at line 777 of file system_error.h.
template<class E > enable_if_c< is_error_code_enum<E>::value, error_code& >::type llvm::error_code::operator= (E _e) inline
Definition at line 757 of file system_error.h.
References llvm::make_error_code().
static error_code llvm::error_code::success () inline static
Definition at line 732 of file system_error.h.
Referenced by llvm::FileOutputBuffer::create(), decodeLLVMAttributesForBitcode(), llvm::BitcodeReader::decodeSignRotatedValue(), llvm::object::ELFFile< ELFT >::ELFFile(), llvm::sys::fs::file_size(), llvm::SectionMemoryManager::finalizeMemory(), GetAttrFromCode(), llvm::object::Archive::Child::getMemoryBuffer(), getMemoryBufferForStream(), getOpenFileImpl(), llvm::sys::fs::getUniqueID(), llvm::sys::fs::has_magic(), llvm::sys::fs::identify_magic(), llvm::sys::fs::is_directory(), llvm::sys::fs::is_regular_file(), llvm::sys::fs::is_symlink(), llvm::sys::fs::make_absolute(), llvm::BitcodeReader::Materialize(), llvm::BitcodeReader::MaterializeModule(), llvm::ErrorOr< T >::operator llvm::error_code(), llvm::BitcodeReader::ParseBitcodeInto(), llvm::BitcodeReader::ParseTriple(), ReadWideAPInt(), and llvm::DataStreamer::~DataStreamer().
static void llvm::error_code::unspecified_bool_true () inline static
Definition at line 775 of file system_error.h.
int llvm::error_code::value () const inline
Definition at line 765 of file system_error.h.
Referenced by llvm::error_category::equivalent(), llvm::operator<(), and llvm::operator==().
The documentation for this class was generated from the following files:
system_error.h
system_error.cpp