LLVM: llvm::PEI Class Reference
LLVM API Documentation
llvm::PEI Class Reference
#include <PrologEpilogInserter.h>
Public Member Functions
PEI ()
virtual void getAnalysisUsage (AnalysisUsage &AU) const
bool runOnMachineFunction (MachineFunction &Fn)
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const
createPrinterPass - Get a function printer pass.
virtual void assignPassManager (PMStack &PMS, PassManagerType T)
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
virtual void print (raw_ostream &O, const Module *M) const
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
Detailed Description
Definition at line 33 of file PrologEpilogInserter.h.
Constructor & Destructor Documentation
llvm::PEI::PEI () inline
Definition at line 36 of file PrologEpilogInserter.h.
References BB, getAnalysisUsage(), llvm::PassRegistry::getPassRegistry(), llvm::initializePEIPass(), and runOnMachineFunction().
Member Function Documentation
void PEI::getAnalysisUsage (AnalysisUsage & AU) const virtual
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
For MachineFunctionPasses, calling AU.preservesCFG() indicates that the pass does not modify the MachineBasicBlock CFG.
Reimplemented from llvm::MachineFunctionPass.
Definition at line 66 of file PrologEpilogInserter.cpp.
References llvm::MachineBasicBlock::back(), llvm::MachineFunction::begin(), llvm::MachineBasicBlock::empty(), llvm::MachineFunction::end(), llvm::MachineFunctionPass::getAnalysisUsage(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), and llvm::MachineInstr::isReturn().
Referenced by PEI().
bool PEI::runOnMachineFunction (MachineFunction & Fn) virtual
runOnMachineFunction - Insert prolog/epilog code and replace abstract frame indexes with appropriate references.
Implements llvm::MachineFunctionPass.
Definition at line 101 of file PrologEpilogInserter.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::MachineFrameInfo::adjustsStack(), Align, BB, llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::MachineModuleInfo::callsUnwindInit(), llvm::TargetFrameLowering::canSimplifyCallFramePseudos(), llvm::MachineRegisterInfo::clearVirtRegs(), llvm::MachineFrameInfo::CreateFixedObject(), llvm::MachineFrameInfo::CreateStackObject(), llvm::TargetFrameLowering::eliminateCallFramePseudoInstr(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::errs(), F(), llvm::TargetRegisterClass::getAlignment(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::TargetRegisterInfo::getCalleeSavedRegs(), llvm::TargetFrameLowering::getCalleeSavedSpillSlots(), llvm::TargetInstrInfo::getCallFrameDestroyOpcode(), llvm::TargetInstrInfo::getCallFrameSetupOpcode(), llvm::MachineFunction::getFrameInfo(), llvm::TargetMachine::getFrameLowering(), llvm::MachineFunction::getFunction(), llvm::TargetMachine::getInstrInfo(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::MachineFunction::getMMI(), llvm::MachineFunction::getName(), llvm::MachineRegisterInfo::getNumVirtRegs(), getReg(), llvm::MachineFunction::getRegInfo(), llvm::TargetMachine::getRegisterInfo(), llvm::TargetRegisterClass::getSize(), llvm::TargetFrameLowering::getStackAlignment(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getTarget(), llvm::Function::hasFnAttribute(), llvm::TargetRegisterInfo::hasReservedSpillSlot(), i, I, llvm::MachineRegisterInfo::isPhysRegUsed(), llvm::TargetInstrInfo::loadRegFromStackSlot(), llvm::Attribute::Naked, llvm::TargetFrameLowering::SpillSlot::Offset, llvm::TargetFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::TargetFrameLowering::processFunctionBeforeFrameFinalized(), llvm::TargetFrameLowering::SpillSlot::Reg, llvm::TargetRegisterInfo::requiresFrameIndexScavenging(), llvm::TargetRegisterInfo::requiresRegisterScavenging(), llvm::TargetFrameLowering::restoreCalleeSavedRegisters(), llvm::MachineFrameInfo::setAdjustsStack(), llvm::MachineFrameInfo::setCalleeSavedInfo(), llvm::MachineFrameInfo::setCalleeSavedInfoValid(), llvm::MachineFrameInfo::setMaxCallFrameSize(), llvm::TargetFrameLowering::spillCalleeSavedRegisters(), llvm::TargetInstrInfo::storeRegToStackSlot(), TII, and WarnStackSize.
Referenced by PEI().
Member Data Documentation
char PEI::ID = 0 static
Definition at line 35 of file PrologEpilogInserter.h.
The documentation for this class was generated from the following files:
PrologEpilogInserter.h
PrologEpilogInserter.cpp