LLVM: llvm::ARMConstantPoolSymbol Class Reference
LLVM API Documentation
llvm::ARMConstantPoolSymbol Class Reference
#include <ARMConstantPoolValue.h>
Public Member Functions
const char * getSymbol () const
virtual int getExistingMachineCPValue (MachineConstantPool *CP, unsigned Alignment)
virtual void addSelectionDAGCSEId (FoldingSetNodeID &ID)
virtual bool hasSameValue (ARMConstantPoolValue *ACPV)
virtual void print (raw_ostream &O) const
print - Implement operator<<
bool equals (const ARMConstantPoolSymbol *A) const
Public Member Functions inherited from llvm::ARMConstantPoolValue
virtual ~ARMConstantPoolValue ()
ARMCP::ARMCPModifier getModifier () const
const char * getModifierText () const
bool hasModifier () const
bool mustAddCurrentAddress () const
unsigned getLabelId () const
unsigned char getPCAdjustment () const
bool isGlobalValue () const
bool isExtSymbol () const
bool isBlockAddress () const
bool isLSDA () const
bool isMachineBasicBlock () const
virtual unsigned getRelocationInfo () const
bool equals (const ARMConstantPoolValue *A) const
void print (raw_ostream *O) const
void dump () const
Public Member Functions inherited from llvm::MachineConstantPoolValue
MachineConstantPoolValue (Type *ty)
virtual ~MachineConstantPoolValue ()
Type * getType () const
Static Public Member Functions
static ARMConstantPoolSymbol * Create (LLVMContext &C, const char *s, unsigned ID, unsigned char PCAdj)
static bool classof (const ARMConstantPoolValue *ACPV)
Additional Inherited Members
Protected Member Functions inherited from llvm::ARMConstantPoolValue
ARMConstantPoolValue (Type *Ty, unsigned id, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress)
ARMConstantPoolValue (LLVMContext &C, unsigned id, ARMCP::ARMCPKind Kind, unsigned char PCAdj, ARMCP::ARMCPModifier Modifier, bool AddCurrentAddress)
template<typename Derived >
int getExistingMachineCPValueImpl (MachineConstantPool *CP, unsigned Alignment)
Detailed Description
ARMConstantPoolSymbol - ARM-specific constantpool values for external symbols.
Definition at line 188 of file ARMConstantPoolValue.h.
Member Function Documentation
void ARMConstantPoolSymbol::addSelectionDAGCSEId (FoldingSetNodeID & ID) virtual
Reimplemented from llvm::ARMConstantPoolValue.
Definition at line 213 of file ARMConstantPoolValue.cpp.
References llvm::ARMConstantPoolValue::addSelectionDAGCSEId(), llvm::FoldingSetNodeID::AddString(), and S.
static bool llvm::ARMConstantPoolSymbol::classof (const ARMConstantPoolValue * ACPV) inline static
Definition at line 212 of file ARMConstantPoolValue.h.
References llvm::ARMConstantPoolValue::isExtSymbol().
ARMConstantPoolSymbol * ARMConstantPoolSymbol::Create (LLVMContext & C, const char * s, unsigned ID, unsigned char PCAdj) static
Definition at line 198 of file ARMConstantPoolValue.cpp.
References llvm::ARMCP::no_modifier.
Referenced by FPCCToARMCC(), llvm::ARMTargetLowering::getJumpTableEncoding(), and llvm::ARMInstrInfo::getUnindexedOpcode().
bool llvm::ARMConstantPoolSymbol::equals (const ARMConstantPoolSymbol * A) const inline
Definition at line 216 of file ARMConstantPoolValue.h.
References llvm::ARMConstantPoolValue::equals().
int ARMConstantPoolSymbol::getExistingMachineCPValue (MachineConstantPool * CP, unsigned Alignment) virtual
Reimplemented from llvm::ARMConstantPoolValue.
Definition at line 203 of file ARMConstantPoolValue.cpp.
const char* llvm::ARMConstantPoolSymbol::getSymbol () const inline
Definition at line 199 of file ARMConstantPoolValue.h.
bool ARMConstantPoolSymbol::hasSameValue (ARMConstantPoolValue * ACPV) virtual
hasSameValue - Return true if this ARM constpool value can share the same constantpool entry as another ARM constpool value.
Reimplemented from llvm::ARMConstantPoolValue.
Definition at line 208 of file ARMConstantPoolValue.cpp.
References llvm::dyn_cast(), llvm::ARMConstantPoolValue::hasSameValue(), and S.
void ARMConstantPoolSymbol::print (raw_ostream & O) const virtual
print - Implement operator<<
Reimplemented from llvm::ARMConstantPoolValue.
Definition at line 218 of file ARMConstantPoolValue.cpp.
References llvm::ARMConstantPoolValue::ARMConstantPoolValue(), llvm::ARMCP::CPMachineBasicBlock, llvm::ARMConstantPoolValue::print(), and S.
The documentation for this class was generated from the following files:
ARMConstantPoolValue.h
ARMConstantPoolValue.cpp