LLVM: llvm::MCMachOObjectDisassembler Class Reference
LLVM API Documentation
llvm::MCMachOObjectDisassembler Class Reference
#include <MCObjectDisassembler.h>
Public Member Functions
MCMachOObjectDisassembler (const object::MachOObjectFile &MOOF, const MCDisassembler &Dis, const MCInstrAnalysis &MIA, uint64_t VMAddrSlide, uint64_t HeaderLoadAddress)
Construct a Mach-O specific object disassembler.
Public Member Functions inherited from llvm::MCObjectDisassembler
MCObjectDisassembler (const object::ObjectFile &Obj, const MCDisassembler &Dis, const MCInstrAnalysis &MIA)
virtual ~MCObjectDisassembler ()
MCModule * buildModule (bool withCFG=false)
Build an MCModule, creating atoms and optionally functions.
MCModule * buildEmptyModule ()
MCFunction * createFunction (MCModule *Module, uint64_t BeginAddr, AddressSetTy &CallTargets, AddressSetTy &TailCallTargets)
void setFallbackRegion (OwningPtr< MemoryObject > &Region)
Set the region on which to fallback if disassembly was requested somewhere not accessible in the object file. This is used for dynamic disassembly (see RawMemoryObject).
void setSymbolizer (MCObjectSymbolizer *ObjectSymbolizer)
Set the symbolizer to use to get information on external functions. Note that this isn't used to do instruction-level symbolization (that is, plugged into MCDisassembler), but to symbolize function call targets.
Protected Member Functions
uint64_t getEffectiveLoadAddr (uint64_t Addr) LLVM_OVERRIDE
uint64_t getOriginalLoadAddr (uint64_t EffectiveAddr) LLVM_OVERRIDE
Compute the original load address, as specified in the objectfile. This is the inverse of getEffectiveLoadAddr.
uint64_t getEntrypoint () LLVM_OVERRIDE
Get the effective address of the entrypoint, or 0 if there is none.
ArrayRef< uint64_t > getStaticInitFunctions () LLVM_OVERRIDE
ArrayRef< uint64_t > getStaticExitFunctions () LLVM_OVERRIDE
Protected Member Functions inherited from llvm::MCObjectDisassembler
MemoryObject * getRegionFor (uint64_t Addr)
Return a memory region suitable for reading starting at Addr. In most cases, this returns a StringRefMemoryObject backed by the containing section. When no section was found, this returns the FallbackRegion, if it is suitable. If it is not, or if there is no fallback region, this returns 0.
Additional Inherited Members
Public Types inherited from llvm::MCObjectDisassembler
typedef std::vector< uint64_t > AddressSetTy
Protected Attributes inherited from llvm::MCObjectDisassembler
const object::ObjectFile & Obj
const MCDisassembler & Dis
const MCInstrAnalysis & MIA
MCObjectSymbolizer * MOS
OwningPtr< MemoryObject > FallbackRegion
The fallback memory region, outside the object file.
Detailed Description
Definition at line 143 of file MCObjectDisassembler.h.
Constructor & Destructor Documentation
MCMachOObjectDisassembler::MCMachOObjectDisassembler (const object::MachOObjectFile & MOOF, const MCDisassembler & Dis, const MCInstrAnalysis & MIA, uint64_t VMAddrSlide, uint64_t HeaderLoadAddress)
Construct a Mach-O specific object disassembler.
Parameters
VMAddrSlide The virtual address slide applied by dyld.
HeaderLoadAddress The load address of the mach_header for this object.
Definition at line 502 of file MCObjectDisassembler.cpp.
References llvm::object::MachOObjectFile::begin_sections(), llvm::dbgs(), DEBUG, llvm::object::MachOObjectFile::end_sections(), and llvm::object::content_iterator< content_type >::increment().
Member Function Documentation
uint64_t MCMachOObjectDisassembler::getEffectiveLoadAddr (uint64_t Addr) protected virtual
Reimplemented from llvm::MCObjectDisassembler.
Definition at line 528 of file MCObjectDisassembler.cpp.
uint64_t MCMachOObjectDisassembler::getEntrypoint () protected virtual
Get the effective address of the entrypoint, or 0 if there is none.
Reimplemented from llvm::MCObjectDisassembler.
Definition at line 537 of file MCObjectDisassembler.cpp.
References llvm::object::MachOObjectFile::LoadCommandInfo::C, llvm::MachO::load_command::cmd, llvm::MCObjectDisassembler::getEntrypoint(), llvm::object::MachOObjectFile::getFirstLoadCommandInfo(), llvm::object::MachOObjectFile::getHeader(), llvm::object::MachOObjectFile::getNextLoadCommandInfo(), I, llvm::SPII::Load, llvm::MachO::mach_header::ncmds, and llvm::object::MachOObjectFile::LoadCommandInfo::Ptr.
uint64_t MCMachOObjectDisassembler::getOriginalLoadAddr (uint64_t EffectiveAddr) protected virtual
Compute the original load address, as specified in the objectfile. This is the inverse of getEffectiveLoadAddr.
Reimplemented from llvm::MCObjectDisassembler.
Definition at line 533 of file MCObjectDisassembler.cpp.
ArrayRef< uint64_t > MCMachOObjectDisassembler::getStaticExitFunctions () protected virtual
Reimplemented from llvm::MCObjectDisassembler.
Definition at line 576 of file MCObjectDisassembler.cpp.
References llvm::StringRef::data(), llvm::object::MachOObjectFile::is64Bit(), and llvm::StringRef::size().
ArrayRef< uint64_t > MCMachOObjectDisassembler::getStaticInitFunctions () protected virtual
Reimplemented from llvm::MCObjectDisassembler.
Definition at line 566 of file MCObjectDisassembler.cpp.
References llvm::StringRef::data(), llvm::object::MachOObjectFile::is64Bit(), and llvm::StringRef::size().
The documentation for this class was generated from the following files:
MCObjectDisassembler.h
MCObjectDisassembler.cpp