LLVM: llvm::SystemZSubtarget Class Reference
LLVM API Documentation
llvm::SystemZSubtarget Class Reference
#include <SystemZSubtarget.h>
Public Member Functions
SystemZSubtarget (const std::string &TT, const std::string &CPU, const std::string &FS)
virtual bool useAA () const LLVM_OVERRIDE
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
bool hasDistinctOps () const
bool hasLoadStoreOnCond () const
bool hasHighWord () const
bool hasFPExtension () const
bool isPC32DBLSymbol (const GlobalValue *GV, Reloc::Model RM, CodeModel::Model CM) const
bool isTargetELF () const
Protected Attributes
bool HasDistinctOps
bool HasLoadStoreOnCond
bool HasHighWord
bool HasFPExtension
Detailed Description
Definition at line 28 of file SystemZSubtarget.h.
Constructor & Destructor Documentation
SystemZSubtarget::SystemZSubtarget (const std::string & TT, const std::string & CPU, const std::string & FS)
Definition at line 24 of file SystemZSubtarget.cpp.
References llvm::sys::getHostCPUName(), and ParseSubtargetFeatures().
Member Function Documentation
bool llvm::SystemZSubtarget::hasDistinctOps () const inline
Definition at line 50 of file SystemZSubtarget.h.
References HasDistinctOps.
bool llvm::SystemZSubtarget::hasFPExtension () const inline
Definition at line 59 of file SystemZSubtarget.h.
References HasFPExtension, isPC32DBLSymbol(), and llvm::NVPTX::PTXCvtMode::RM.
Referenced by llvm::SystemZTargetLowering::SystemZTargetLowering().
bool llvm::SystemZSubtarget::hasHighWord () const inline
Definition at line 56 of file SystemZSubtarget.h.
References HasHighWord.
Referenced by lowerGR128Binary(), maskMatters(), and llvm::SystemZTargetLowering::SystemZTargetLowering().
bool llvm::SystemZSubtarget::hasLoadStoreOnCond () const inline
Definition at line 53 of file SystemZSubtarget.h.
References HasLoadStoreOnCond.
Referenced by forceReg(), llvm::SystemZInstrInfo::isPredicable(), and llvm::SystemZInstrInfo::PredicateInstruction().
bool SystemZSubtarget::isPC32DBLSymbol (const GlobalValue * GV, Reloc::Model RM, CodeModel::Model CM) const
Definition at line 51 of file SystemZSubtarget.cpp.
References bindsLocally(), llvm::GlobalValue::getAlignment(), and llvm::CodeModel::Small.
Referenced by hasFPExtension(), and lowerGR128Binary().
bool llvm::SystemZSubtarget::isTargetELF () const inline
Definition at line 66 of file SystemZSubtarget.h.
References llvm::Triple::isOSBinFormatELF().
Referenced by llvm::SystemZAsmPrinter::EmitEndOfAsmFile().
void llvm::SystemZSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
Referenced by SystemZSubtarget(), and useAA().
virtual bool llvm::SystemZSubtarget::useAA () const inline virtual
Definition at line 44 of file SystemZSubtarget.h.
References llvm::X86II::FS, and ParseSubtargetFeatures().
Member Data Documentation
bool llvm::SystemZSubtarget::HasDistinctOps protected
Definition at line 31 of file SystemZSubtarget.h.
Referenced by hasDistinctOps().
bool llvm::SystemZSubtarget::HasFPExtension protected
Definition at line 34 of file SystemZSubtarget.h.
Referenced by hasFPExtension().
bool llvm::SystemZSubtarget::HasHighWord protected
Definition at line 33 of file SystemZSubtarget.h.
Referenced by hasHighWord().
bool llvm::SystemZSubtarget::HasLoadStoreOnCond protected
Definition at line 32 of file SystemZSubtarget.h.
Referenced by hasLoadStoreOnCond().
The documentation for this class was generated from the following files:
SystemZSubtarget.h
SystemZSubtarget.cpp