LLVM: llvm::sys::SmartMutex< mt_only > Class Template Reference
LLVM API Documentation
llvm::sys::SmartMutex< mt_only > Class Template Reference
#include <Mutex.h>
Public Member Functions
SmartMutex (bool rec=true)
bool acquire ()
bool release ()
bool tryacquire ()
Public Member Functions inherited from llvm::sys::MutexImpl
MutexImpl (bool recursive=true)
Default Constructor.
~MutexImpl ()
Destructor.
bool acquire ()
Unconditionally acquire the lock.
bool release ()
Unconditionally release the lock.
bool tryacquire ()
Try to acquire the lock.
Detailed Description
template<bool mt_only>
class llvm::sys::SmartMutex< mt_only >
SmartMutex - A mutex with a compile time constant parameter that indicates whether this mutex should become a no-op when we're not running in multithreaded mode.
Definition at line 89 of file Mutex.h.
Constructor & Destructor Documentation
template<bool mt_only> llvm::sys::SmartMutex< mt_only >::SmartMutex (bool rec = true) inline explicit
Definition at line 93 of file Mutex.h.
Member Function Documentation
template<bool mt_only> bool llvm::sys::SmartMutex< mt_only >::acquire () inline
Definition at line 96 of file Mutex.h.
Referenced by llvm::ValueMapCallbackVH< KeyT, ValueT, Config >::allUsesReplacedWith(), llvm::Interpreter::callExternalFunction(), llvm::ValueMapCallbackVH< KeyT, ValueT, Config >::deleted(), llvm::llvm_acquire_global_lock(), llvm::MutexGuard::MutexGuard(), and llvm::sys::SmartScopedLock< mt_only >::SmartScopedLock().
template<bool mt_only> bool llvm::sys::SmartMutex< mt_only >::release () inline
Definition at line 109 of file Mutex.h.
Referenced by llvm::ValueMapCallbackVH< KeyT, ValueT, Config >::allUsesReplacedWith(), llvm::Interpreter::callExternalFunction(), llvm::ValueMapCallbackVH< KeyT, ValueT, Config >::deleted(), llvm::llvm_release_global_lock(), llvm::MutexGuard::~MutexGuard(), and llvm::sys::SmartScopedLock< mt_only >::~SmartScopedLock().
template<bool mt_only> bool llvm::sys::SmartMutex< mt_only >::tryacquire () inline
Definition at line 123 of file Mutex.h.
The documentation for this class was generated from the following file:
Mutex.h