LLVM: llvm::DWARFDebugRangeList Class Reference
LLVM API Documentation
llvm::DWARFDebugRangeList Class Reference
#include <DWARFDebugRangeList.h>
Classes
struct RangeListEntry
Public Member Functions
DWARFDebugRangeList ()
void clear ()
void dump (raw_ostream &OS) const
bool extract (DataExtractor data, uint32_t *offset_ptr)
bool containsAddress (uint64_t BaseAddress, uint64_t Address) const
Detailed Description
Definition at line 20 of file DWARFDebugRangeList.h.
Constructor & Destructor Documentation
llvm::DWARFDebugRangeList::DWARFDebugRangeList () inline
Definition at line 66 of file DWARFDebugRangeList.h.
References clear(), llvm::DWARFDebugRangeList::RangeListEntry::containsAddress(), dump(), and extract().
Member Function Documentation
void DWARFDebugRangeList::clear ()
Definition at line 16 of file DWARFDebugRangeList.cpp.
Referenced by DWARFDebugRangeList(), and extract().
bool DWARFDebugRangeList::containsAddress (uint64_t BaseAddress, uint64_t Address) const
containsAddress - Returns true if range list contains the given address. Has to be passed base address of the compile unit that references this range list.
Definition at line 58 of file DWARFDebugRangeList.cpp.
References i, and n.
Referenced by llvm::DWARFDebugInfoEntryMinimal::addressRangeContainsAddress().
void DWARFDebugRangeList::dump (raw_ostream & OS) const
Definition at line 47 of file DWARFDebugRangeList.cpp.
References llvm::format(), i, and n.
Referenced by llvm::DWARFContext::dump(), and DWARFDebugRangeList().
bool DWARFDebugRangeList::extract (DataExtractor data, uint32_t * offset_ptr)
Definition at line 22 of file DWARFDebugRangeList.cpp.
References clear(), llvm::DWARFDebugRangeList::RangeListEntry::EndAddress, llvm::DataExtractor::getAddress(), llvm::DataExtractor::getAddressSize(), llvm::DWARFDebugRangeList::RangeListEntry::isEndOfListEntry(), llvm::DataExtractor::isValidOffset(), and llvm::DWARFDebugRangeList::RangeListEntry::StartAddress.
Referenced by llvm::DWARFContext::dump(), DWARFDebugRangeList(), and llvm::DWARFUnit::extractRangeList().
The documentation for this class was generated from the following files:
DWARFDebugRangeList.h
DWARFDebugRangeList.cpp