LLVM: llvm::SparcSubtarget Class Reference
LLVM API Documentation
llvm::SparcSubtarget Class Reference
#include <SparcSubtarget.h>
Public Member Functions
SparcSubtarget (const std::string &TT, const std::string &CPU, const std::string &FS, bool is64bit)
bool isV9 () const
bool isVIS () const
bool useDeprecatedV8Instructions () const
bool hasHardQuad () const
void ParseSubtargetFeatures (StringRef CPU, StringRef FS)
bool is64Bit () const
std::string getDataLayout () const
int64_t getStackPointerBias () const
int getAdjustedFrameSize (int stackSize) const
Detailed Description
Definition at line 26 of file SparcSubtarget.h.
Constructor & Destructor Documentation
SparcSubtarget::SparcSubtarget (const std::string & TT, const std::string & CPU, const std::string & FS, bool is64bit)
Definition at line 27 of file SparcSubtarget.cpp.
References ParseSubtargetFeatures().
Member Function Documentation
int SparcSubtarget::getAdjustedFrameSize (int stackSize) const
Given a actual stack size as determined by FrameInfo, this function returns adjusted framesize which includes space for register window spills and arguments.
Definition at line 51 of file SparcSubtarget.cpp.
References is64Bit(), and llvm::RoundUpToAlignment().
Referenced by llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::SparcFrameLowering::emitEpilogue(), llvm::SparcFrameLowering::emitPrologue(), and getStackPointerBias().
std::string llvm::SparcSubtarget::getDataLayout () const inline
Definition at line 48 of file SparcSubtarget.h.
References is64Bit(), and p.
int64_t llvm::SparcSubtarget::getStackPointerBias () const inline
The 64-bit ABI uses biased stack and frame pointers, so the stack frame of the current function is the area from [sp+BIAS] to [fp+BIAS].
Definition at line 60 of file SparcSubtarget.h.
References getAdjustedFrameSize(), and is64Bit().
Referenced by llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::SparcTargetLowering::LowerCall_64(), LowerDYNAMIC_STACKALLOC(), and llvm::SparcTargetLowering::LowerFormalArguments_64().
bool llvm::SparcSubtarget::hasHardQuad () const inline
Definition at line 41 of file SparcSubtarget.h.
References ParseSubtargetFeatures().
Referenced by llvm::SparcInstrInfo::copyPhysReg(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::SparcTargetLowering::LowerOperation(), and llvm::SparcTargetLowering::SparcTargetLowering().
bool llvm::SparcSubtarget::is64Bit () const inline
Definition at line 47 of file SparcSubtarget.h.
Referenced by getAdjustedFrameSize(), getDataLayout(), llvm::SparcRegisterInfo::getPointerRegClass(), llvm::SparcRegisterInfo::getReservedRegs(), getStackPointerBias(), llvm::SparcTargetLowering::LowerCall(), LowerDYNAMIC_STACKALLOC(), llvm::SparcTargetLowering::LowerF128Compare(), llvm::SparcTargetLowering::LowerF128Op(), llvm::SparcTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerOperation(), llvm::SparcTargetLowering::LowerReturn(), and llvm::SparcTargetLowering::SparcTargetLowering().
bool llvm::SparcSubtarget::isV9 () const inline
Definition at line 38 of file SparcSubtarget.h.
Referenced by llvm::SparcInstrInfo::copyPhysReg(), llvm::createSparcDelaySlotFillerPass(), llvm::SparcRegisterInfo::eliminateFrameIndex(), llvm::SparcRegisterInfo::getReservedRegs(), llvm::SparcTargetLowering::LowerOperation(), and llvm::SparcTargetLowering::SparcTargetLowering().
bool llvm::SparcSubtarget::isVIS () const inline
Definition at line 39 of file SparcSubtarget.h.
void llvm::SparcSubtarget::ParseSubtargetFeatures (StringRef CPU, StringRef FS)
ParseSubtargetFeatures - Parses features string setting specified subtarget options. Definition of function is auto generated by tblgen.
Referenced by hasHardQuad(), and SparcSubtarget().
bool llvm::SparcSubtarget::useDeprecatedV8Instructions () const inline
Definition at line 40 of file SparcSubtarget.h.
The documentation for this class was generated from the following files:
SparcSubtarget.h
SparcSubtarget.cpp