LLVM: CodeGenPrepare.cpp File Reference
LLVM API Documentation
CodeGenPrepare.cpp File Reference
#include "llvm/Transforms/Scalar.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/ValueMap.h"
#include "llvm/Analysis/DominatorInternals.h"
#include "llvm/Analysis/Dominators.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Assembly/Writer.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/Pass.h"
#include "llvm/Support/CallSite.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/GetElementPtrTypeIterator.h"
#include "llvm/Support/PatternMatch.h"
#include "llvm/Support/ValueHandle.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetLibraryInfo.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/BuildLibCalls.h"
#include "llvm/Transforms/Utils/BypassSlowDivision.h"
#include "llvm/Transforms/Utils/Local.h"
Macros
#define DEBUG_TYPE "codegenprepare"
Functions
STATISTIC (NumBlocksElim,"Number of blocks eliminated")
STATISTIC (NumPHIsElim,"Number of trivial PHIs eliminated")
STATISTIC (NumGEPsElim,"Number of GEPs converted to casts")
STATISTIC (NumCmpUses,"Number of uses of Cmp expressions replaced with uses of ""sunken Cmps")
STATISTIC (NumCastUses,"Number of uses of Cast expressions replaced with uses ""of sunken Casts")
STATISTIC (NumMemoryInsts,"Number of memory instructions whose address ""computations were sunk")
STATISTIC (NumExtsMoved,"Number of [s|z]ext instructions combined with loads")
STATISTIC (NumExtUses,"Number of uses of [s|z]ext instructions optimized")
STATISTIC (NumRetsDup,"Number of return instructions duplicated")
STATISTIC (NumDbgValueMoved,"Number of debug value instructions moved")
STATISTIC (NumSelectsExpanded,"Number of selects turned into branches")
INITIALIZE_PASS_BEGIN (CodeGenPrepare,"codegenprepare","Optimize for code generation", false, false) INITIALIZE_PASS_END(CodeGenPrepare
static bool OptimizeNoopCopyExpression (CastInst *CI, const TargetLowering &TLI)
static bool OptimizeCmpExpression (CmpInst *CI)
static bool IsNonLocalValue (Value *V, BasicBlock *BB)
static bool isFormingBranchFromSelectProfitable (SelectInst *SI)
Variables
static cl::opt< bool > DisableBranchOpts ("disable-cgp-branch-opts", cl::Hidden, cl::init(false), cl::desc("Disable branch optimizations in CodeGenPrepare"))
static cl::opt< bool > DisableSelectToBranch ("disable-cgp-select2branch", cl::Hidden, cl::init(false), cl::desc("Disable select to branch conversion."))
codegenprepare
Optimize for code generation
Optimize for code false
Macro Definition Documentation
#define DEBUG_TYPE "codegenprepare"
Definition at line 16 of file CodeGenPrepare.cpp.
Function Documentation
INITIALIZE_PASS_BEGIN (CodeGenPrepare , "codegenprepare" , "Optimize for code generation" , false , false)
static bool isFormingBranchFromSelectProfitable (SelectInst * SI) static
isFormingBranchFromSelectProfitable - Returns true if a SelectInst should be turned into an explicit branch.
Definition at line 1797 of file CodeGenPrepare.cpp.
References llvm::BasicBlock::begin(), llvm::Function::begin(), llvm::BasicBlock::Create(), llvm::PHINode::Create(), llvm::BranchInst::Create(), llvm::dbgs(), DEBUG, DisableSelectToBranch, llvm::dyn_cast(), llvm::BasicBlock::end(), llvm::Function::end(), llvm::Instruction::eraseFromParent(), llvm::SelectInst::getCondition(), llvm::Value::getContext(), llvm::SelectInst::getFalseValue(), llvm::BasicBlock::getFirstInsertionPt(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::BasicBlock::getTerminator(), llvm::SelectInst::getTrueValue(), llvm::Value::getType(), llvm::DbgValueInst::getValue(), llvm::Value::hasOneUse(), I, llvm::Instruction::insertAfter(), llvm::Instruction::insertBefore(), llvm::Type::isIntegerTy(), llvm::Instruction::isTerminator(), llvm::Type::isVectorTy(), NC, OptimizeCmpExpression(), OptimizeNoopCopyExpression(), P, llvm::Instruction::removeFromParent(), llvm::Value::replaceAllUsesWith(), llvm::TargetLoweringBase::ScalarCondVectorVal, llvm::TargetLoweringBase::ScalarValSelect, llvm::SimplifyInstruction(), llvm::BasicBlock::splitBasicBlock(), llvm::Value::takeName(), and llvm::TargetLoweringBase::VectorMaskSelect.
static bool IsNonLocalValue (Value * V, BasicBlock * BB) static
IsNonLocalValue - Return true if the specified values are defined in a different basic block than BB.
Definition at line 1442 of file CodeGenPrepare.cpp.
References llvm::SmallVectorTemplateCommon< T >::back(), BB, llvm::BasicBlock::begin(), llvm::TargetLowering::C_Memory, llvm::TargetLowering::AsmOperandInfo::ConstraintType, llvm::IRBuilder< preserveNames, T, Inserter >::CreateAdd(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateBitCast(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateIntCast(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateIntToPtr(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateMul(), llvm::IRBuilder< preserveNames, T, Inserter >::CreatePtrToInt(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateSExt(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateTrunc(), llvm::dbgs(), DEBUG, llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::ConstantInt::get(), llvm::CallInst::getArgOperand(), getBitWidth(), llvm::BasicBlock::getFirstInsertionPt(), llvm::Constant::getNullValue(), llvm::Value::getNumUses(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), getParent(), llvm::Value::getType(), llvm::Value::hasOneUse(), i, I, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::Instruction::insertAfter(), llvm::InlineAsm::ConstraintInfo::isIndirect, llvm::InlineAsm::isInput, llvm::Type::isPointerTy(), P, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::pop_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), llvm::Instruction::removeFromParent(), llvm::User::replaceUsesOfWith(), llvm::ISD::SEXTLOAD, llvm::SmallVectorTemplateCommon< T >::size(), llvm::InlineAsm::ConstraintInfo::Type, llvm::Value::use_begin(), llvm::Value::use_empty(), llvm::Value::use_end(), and llvm::ISD::ZEXTLOAD.
static bool OptimizeCmpExpression (CmpInst * CI) static
OptimizeCmpExpression - sink the given CmpInst into user blocks to reduce the number of virtual registers that must be created and coalesced. This is a clear win except on targets with multiple condition code registers (PowerPC), where it might lose; some adjustment may be wanted there.
Return true if any changes are made.
InsertedCmp - Only insert a cmp in each block once.
Definition at line 536 of file CodeGenPrepare.cpp.
References BB, llvm::SmallVectorTemplateCommon< T >::begin(), llvm::BasicBlock::begin(), llvm::TargetLowering::C_Memory, llvm::TargetLowering::AsmOperandInfo::CallOperandVal, llvm::SmallVectorImpl< T >::clear(), llvm::TargetLowering::ComputeConstraintToUse(), llvm::TargetLowering::AsmOperandInfo::ConstraintType, llvm::CmpInst::Create(), llvm::dbgs(), llvm::dump(), llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::Instruction::eraseFromParent(), llvm::BasicBlock::eraseFromParent(), llvm::FoldReturnIntoUncondBranch(), llvm::gep_type_begin(), llvm::ConstantInt::get(), llvm::CallInst::getArgOperand(), llvm::Function::getAttributes(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getAttributes(), llvm::CallInst::getCalledFunction(), llvm::CallInst::getCalledValue(), llvm::StructLayout::getElementOffset(), llvm::BasicBlock::getFirstInsertionPt(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::generic_gep_type_iterator< ItTy >::getIndexedType(), llvm::IntrinsicInst::getIntrinsicID(), llvm::PHINode::getNumIncomingValues(), llvm::User::getNumOperands(), llvm::Instruction::getOpcode(), llvm::CmpInst::getOpcode(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::Type::getPointerAddressSpace(), llvm::Type::getPointerElementType(), llvm::CmpInst::getPredicate(), llvm::ReturnInst::getReturnValue(), llvm::ConstantInt::getSExtValue(), llvm::DataLayout::getStructLayout(), llvm::BranchInst::getSuccessor(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::BasicBlock::hasAddressTaken(), llvm::AttributeSet::hasAttribute(), llvm::Value::hasOneUse(), i, I, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::InlineAsm::ConstraintInfo::isIndirect, llvm::Type::isIntegerTy(), llvm::Type::isPointerTy(), llvm::BranchInst::isUnconditional(), llvm::Value::isUsedInBasicBlock(), llvm::PatternMatch::m_Add(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::A64CC::MI, llvm::Attribute::NoAlias, llvm::Intrinsic::objectsize, llvm::operator<<(), llvm::operator==(), llvm::TargetLowering::ParseConstraints(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::pred_begin(), llvm::pred_end(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::iplist< NodeTy, Traits >::rbegin(), llvm::iplist< NodeTy, Traits >::rend(), llvm::replaceAndRecursivelySimplify(), llvm::Attribute::SExt, llvm::SmallVectorTemplateCommon< T >::size(), llvm::Value::use_begin(), llvm::Value::use_empty(), llvm::Value::use_end(), llvm::WriteAsOperand(), and llvm::Attribute::ZExt.
Referenced by isFormingBranchFromSelectProfitable().
static bool OptimizeNoopCopyExpression (CastInst * CI, const TargetLowering & TLI) static
OptimizeNoopCopyExpression - If the specified cast instruction is a noop copy (e.g. it's casting from one pointer type to another, i32->i8 on PPC), sink it into user blocks to reduce the number of virtual registers that must be created and coalesced.
Return true if any changes are made.
InsertedCasts - Only insert a cast in each block once.
Definition at line 454 of file CodeGenPrepare.cpp.
References llvm::EVT::bitsLT(), llvm::CastInst::Create(), llvm::Instruction::eraseFromParent(), llvm::Value::getContext(), llvm::BasicBlock::getFirstInsertionPt(), llvm::CastInst::getOpcode(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::Value::getType(), llvm::TargetLoweringBase::getTypeAction(), llvm::TargetLoweringBase::getTypeToTransformTo(), llvm::TargetLoweringBase::getValueType(), llvm::EVT::isInteger(), llvm::TargetLoweringBase::TypePromoteInteger, llvm::Value::use_begin(), llvm::Value::use_empty(), and llvm::Value::use_end().
Referenced by isFormingBranchFromSelectProfitable().
STATISTIC (NumBlocksElim , "Number of blocks eliminated")
STATISTIC (NumPHIsElim , "Number of trivial PHIs eliminated")
STATISTIC (NumGEPsElim , "Number of GEPs converted to casts")
STATISTIC (NumCmpUses , "Number of uses of Cmp expressions replaced with uses of ""sunken Cmps")
STATISTIC (NumCastUses , "Number of uses of Cast expressions replaced with uses ""of sunken Casts")
STATISTIC (NumMemoryInsts , "Number of memory instructions whose address ""computations were sunk")
STATISTIC (NumExtsMoved , "Number of ext instructions combined with loads" [s|z])
STATISTIC (NumExtUses , "Number of uses of ext instructions optimized" [s|z])
STATISTIC (NumRetsDup , "Number of return instructions duplicated")
STATISTIC (NumDbgValueMoved , "Number of debug value instructions moved")
STATISTIC (NumSelectsExpanded , "Number of selects turned into branches")
Variable Documentation
codegenprepare
Definition at line 137 of file CodeGenPrepare.cpp.
cl::opt<bool> DisableBranchOpts("disable-cgp-branch-opts", cl::Hidden, cl::init(false), cl::desc("Disable branch optimizations in CodeGenPrepare")) static
Referenced by llvm::createCodeGenPreparePass().
cl::opt<bool> DisableSelectToBranch("disable-cgp-select2branch", cl::Hidden, cl::init(false), cl::desc("Disable select to branch conversion.")) static
Referenced by isFormingBranchFromSelectProfitable().
Optimize for code false
Definition at line 137 of file CodeGenPrepare.cpp.
Optimize for code generation
Definition at line 137 of file CodeGenPrepare.cpp.
Referenced by llvm::DenseMapInfo< CallValue >::getTombstoneKey().