LLVM: COFFAsmParser.cpp File Reference
LLVM API Documentation
COFFAsmParser.cpp File Reference
#include "llvm/MC/MCParser/MCAsmParserExtension.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Twine.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCParser/MCAsmLexer.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSectionCOFF.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCTargetAsmParser.h"
#include "llvm/Support/COFF.h"
Namespaces
llvm
List of target independent CodeGen pass IDs.
Functions
static SectionKind computeSectionKind (unsigned Flags)
MCAsmParserExtension * llvm::createCOFFAsmParser ()
Function Documentation
static SectionKind computeSectionKind (unsigned Flags) static
Definition at line 146 of file COFFAsmParser.cpp.
References llvm::AsmToken::At, llvm::StringSwitch< T, R >::Case(), Characteristics, llvm::tgtok::Code, llvm::AsmToken::Comma, llvm::StringSwitch< T, R >::Default(), llvm::AsmToken::EndOfStatement, llvm::lltok::Error, llvm::MCSectionCOFF::getCharacteristics(), llvm::SectionKind::getDataRel(), llvm::SectionKind::getReadOnly(), llvm::MCSectionCOFF::getSectionName(), llvm::MCRegisterInfo::getSEHRegNum(), llvm::MCSectionCOFF::getSelection(), llvm::SectionKind::getText(), i, llvm::AsmToken::Identifier, llvm::COFF::IMAGE_COMDAT_SELECT_ANY, llvm::COFF::IMAGE_COMDAT_SELECT_ASSOCIATIVE, llvm::COFF::IMAGE_COMDAT_SELECT_EXACT_MATCH, llvm::COFF::IMAGE_COMDAT_SELECT_LARGEST, llvm::COFF::IMAGE_COMDAT_SELECT_NEWEST, llvm::COFF::IMAGE_COMDAT_SELECT_NODUPLICATES, llvm::COFF::IMAGE_COMDAT_SELECT_SAME_SIZE, is, llvm::SPII::Load, llvm::MCSA_Invalid, llvm::MCSA_Weak, MRI, n, llvm::None, llvm::AsmToken::Percent, llvm::ARMBuildAttrs::Section, llvm::MCSectionCOFF::setSelection(), llvm::StringRef::size(), llvm::AsmToken::String, llvm::ARMBuildAttrs::Symbol, and Type.