LLVM: COFFObjectFile.cpp File Reference
LLVM API Documentation
COFFObjectFile.cpp File Reference
#include "llvm/Object/COFF.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Triple.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <cctype>
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define LLVM_COFF_SWITCH_RELOC_TYPE_NAME(enum) case COFF::enum: res = #enum; break;
Functions
static const import_directory_table_entry * toImportEntry (DataRefImpl Imp)
Macro Definition Documentation
#define LLVM_COFF_SWITCH_RELOC_TYPE_NAME (enum) case COFF::enum: res = #enum; break;
Definition at line 805 of file COFFObjectFile.cpp.
Referenced by llvm::object::COFFObjectFile::getRelocationTypeName().
Function Documentation
static const import_directory_table_entry* toImportEntry (DataRefImpl Imp) static
Definition at line 890 of file COFFObjectFile.cpp.
References llvm::object::DataRefImpl::p.
Referenced by llvm::object::ImportDirectoryEntryRef::getImportLookupEntry(), llvm::object::ImportDirectoryEntryRef::getImportTableEntry(), llvm::object::ImportDirectoryEntryRef::getName(), and llvm::object::ImportDirectoryEntryRef::getNext().