LLVM: Compression.cpp File Reference
LLVM API Documentation
Compression.cpp File Reference
#include "llvm/Support/Compression.h"
#include "llvm/ADT/OwningPtr.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Config/config.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MemoryBuffer.h"
#include <zlib.h>
Functions
static int encodeZlibCompressionLevel (zlib::CompressionLevel Level)
static zlib::Status encodeZlibReturnValue (int ReturnValue)
Function Documentation
static int encodeZlibCompressionLevel (zlib::CompressionLevel Level) static
Definition at line 28 of file Compression.cpp.
References llvm::zlib::BestSizeCompression, llvm::zlib::BestSpeedCompression, llvm::zlib::DefaultCompression, llvm_unreachable, and llvm::zlib::NoCompression.
Referenced by llvm::zlib::compress().
static zlib::Status encodeZlibReturnValue (int ReturnValue) static
Definition at line 38 of file Compression.cpp.
References llvm_unreachable, llvm::zlib::StatusBufferTooShort, llvm::zlib::StatusInvalidArg, llvm::zlib::StatusInvalidData, llvm::zlib::StatusOK, and llvm::zlib::StatusOutOfMemory.
Referenced by llvm::zlib::compress(), and llvm::zlib::uncompress().