LLVM: ConstantMerge.cpp File Reference
LLVM API Documentation
ConstantMerge.cpp File Reference
#include "llvm/Transforms/IPO.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/PointerIntPair.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/Pass.h"
Macros
#define DEBUG_TYPE "constmerge"
Functions
STATISTIC (NumMerged,"Number of global constants merged")
INITIALIZE_PASS (ConstantMerge,"constmerge","Merge Duplicate Global Constants", false, false) ModulePass *llvm
static void FindUsedValues (GlobalVariable *LLVMUsed, SmallPtrSet< const GlobalValue *, 8 > &UsedValues)
Find values that are marked as llvm.used.
static bool IsBetterCannonical (const GlobalVariable &A, const GlobalVariable &B)
Macro Definition Documentation
#define DEBUG_TYPE "constmerge"
Definition at line 20 of file ConstantMerge.cpp.
Function Documentation
static void FindUsedValues (GlobalVariable * LLVMUsed, SmallPtrSet< const GlobalValue *, 8 > & UsedValues) static
Find values that are marked as llvm.used.
Definition at line 67 of file ConstantMerge.cpp.
References llvm::GlobalVariable::getInitializer(), llvm::User::getNumOperands(), llvm::User::getOperand(), i, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), and llvm::Value::stripPointerCastsNoFollowAliases().
Referenced by IsBetterCannonical().
INITIALIZE_PASS (ConstantMerge , "constmerge" , "Merge Duplicate Global Constants" , false , false)
Definition at line 59 of file ConstantMerge.cpp.
static bool IsBetterCannonical (const GlobalVariable & A, const GlobalVariable & B) static
Definition at line 80 of file ConstantMerge.cpp.
References Align, llvm::SmallVectorImpl< T >::clear(), llvm::SmallVectorBase::empty(), llvm::GlobalVariable::eraseFromParent(), FindUsedValues(), llvm::PointerType::getAddressSpace(), llvm::GlobalValue::getAlignment(), llvm::Module::getGlobalVariable(), llvm::GlobalVariable::getInitializer(), llvm::GlobalValue::getType(), llvm::Module::global_begin(), llvm::Module::global_end(), llvm::GlobalVariable::hasDefinitiveInitializer(), llvm::GlobalValue::hasLocalLinkage(), llvm::GlobalValue::hasSection(), llvm::GlobalValue::hasUnnamedAddr(), i, llvm::GlobalVariable::isConstant(), llvm::GlobalValue::isWeakForLinker(), M, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::Constant::removeDeadConstantUsers(), llvm::GlobalValue::setUnnamedAddr(), llvm::SmallVectorTemplateCommon< T >::size(), and llvm::Value::use_empty().
STATISTIC (NumMerged , "Number of global constants merged")