LLVM: CostModel.cpp File Reference
LLVM API Documentation
CostModel.cpp File Reference
#include "llvm/ADT/STLExtras.h"
#include "llvm/Analysis/Passes.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Value.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define CM_NAME "cost-model"
#define DEBUG_TYPE CM_NAME
Functions
static bool isReverseVectorMask (SmallVectorImpl< int > &Mask)
static TargetTransformInfo::OperandValueKind getOperandInfo (Value *V)
static bool matchMask (SmallVectorImpl< int > &M1, SmallVectorImpl< int > &M2)
static bool matchPairwiseShuffleMask (ShuffleVectorInst *SI, bool IsLeft, unsigned Level)
static bool matchPairwiseReductionAtLevel (const BinaryOperator *BinOp, unsigned Level, unsigned NumLevels)
static bool matchPairwiseReduction (const ExtractElementInst *ReduxRoot, unsigned &Opcode, Type *&Ty)
static std::pair< Value *, ShuffleVectorInst * > getShuffleAndOtherOprd (BinaryOperator *B)
static bool matchVectorSplittingReduction (const ExtractElementInst *ReduxRoot, unsigned &Opcode, Type *&Ty)
Variables
static cl::opt< bool > EnableReduxCost ("costmodel-reduxcost", cl::init(false), cl::Hidden, cl::desc("Recognize reduction patterns."))
static const char cm_name [] = "Cost Model Analysis"
Macro Definition Documentation
#define CM_NAME "cost-model"
Definition at line 20 of file CostModel.cpp.
#define DEBUG_TYPE CM_NAME
Definition at line 21 of file CostModel.cpp.
Function Documentation
static TargetTransformInfo::OperandValueKind getOperandInfo (Value * V) static
Definition at line 97 of file CostModel.cpp.
References llvm::ConstantVector::getSplatValue(), llvm::ConstantDataVector::getSplatValue(), llvm::TargetTransformInfo::OK_AnyValue, and llvm::TargetTransformInfo::OK_UniformConstantValue.
Referenced by matchVectorSplittingReduction().
static std::pair<Value *, ShuffleVectorInst *> getShuffleAndOtherOprd (BinaryOperator * B) static
Definition at line 279 of file CostModel.cpp.
References llvm::dyn_cast(), llvm::User::getOperand(), and S.
Referenced by matchVectorSplittingReduction().
static bool isReverseVectorMask (SmallVectorImpl< int > & Mask) static
Definition at line 90 of file CostModel.cpp.
References i, and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by matchVectorSplittingReduction().
static bool matchMask (SmallVectorImpl< int > & M1, SmallVectorImpl< int > & M2) static
Definition at line 114 of file CostModel.cpp.
References i, and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by matchPairwiseShuffleMask(), and matchVectorSplittingReduction().
static bool matchPairwiseReduction (const ExtractElementInst * ReduxRoot, unsigned & Opcode, Type *& Ty) static
Definition at line 229 of file CostModel.cpp.
References llvm::dyn_cast(), EnableReduxCost, llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::ConstantInt::getZExtValue(), llvm::isPowerOf2_32(), llvm::Log2_32(), and matchPairwiseReductionAtLevel().
Referenced by matchVectorSplittingReduction().
static bool matchPairwiseReductionAtLevel (const BinaryOperator * BinOp, unsigned Level, unsigned NumLevels) static
Definition at line 148 of file CostModel.cpp.
References llvm::dyn_cast(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm::Type::isVectorTy(), llvm::A64CC::LS, and matchPairwiseShuffleMask().
Referenced by matchPairwiseReduction().
static bool matchPairwiseShuffleMask (ShuffleVectorInst * SI, bool IsLeft, unsigned Level) static
Definition at line 125 of file CostModel.cpp.
References llvm::ShuffleVectorInst::getShuffleMask(), llvm::ShuffleVectorInst::getType(), llvm::Type::getVectorNumElements(), i, matchMask(), and val.
Referenced by matchPairwiseReductionAtLevel().
static bool matchVectorSplittingReduction (const ExtractElementInst * ReduxRoot, unsigned & Opcode, Type *& Ty) static
Definition at line 292 of file CostModel.cpp.
References llvm::APIntOps::And(), B, llvm::Function::begin(), llvm::Call, llvm::dyn_cast(), EnableReduxCost, llvm::SmallVectorTemplateCommon< T >::end(), llvm::Function::end(), ExtractElement(), llvm::LoadInst::getAlignment(), llvm::StoreInst::getAlignment(), llvm::SelectInst::getCondition(), llvm::Instruction::getOpcode(), llvm::BinaryOperator::getOpcode(), llvm::User::getOperand(), getOperandInfo(), llvm::LoadInst::getPointerAddressSpace(), llvm::StoreInst::getPointerAddressSpace(), llvm::Type::getPointerElementType(), getShuffleAndOtherOprd(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::Value::getType(), llvm::InsertElementInst::getType(), llvm::StoreInst::getValueOperand(), llvm::Type::getVectorNumElements(), llvm::ConstantInt::getZExtValue(), I, llvm::ARM_PROC::IE, llvm::isPowerOf2_32(), isReverseVectorMask(), it, j(), llvm::SPII::Load, matchMask(), matchPairwiseReduction(), llvm::APIntOps::Or(), llvm::TargetOpcode::PHI, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::AArch64ISD::Ret, llvm::MCID::Select, llvm::SmallVectorTemplateCommon< T >::size(), llvm::TargetTransformInfo::SK_Reverse, llvm::SPII::Store, llvm::tie(), and llvm::APIntOps::Xor().
Variable Documentation
const char cm_name[] = "Cost Model Analysis" static
Definition at line 69 of file CostModel.cpp.
cl::opt<bool> EnableReduxCost("costmodel-reduxcost", cl::init(false), cl::Hidden, cl::desc("Recognize reduction patterns.")) static
Referenced by matchPairwiseReduction(), and matchVectorSplittingReduction().