LLVM: CPPBackend.cpp File Reference
LLVM API Documentation
CPPBackend.cpp File Reference
#include "CPPTargetMachine.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Config/config.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Pass.h"
#include "llvm/PassManager.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/TargetRegistry.h"
#include <algorithm>
#include <cctype>
#include <cstdio>
#include <map>
#include <set>
Macros
#define HANDLE_ATTR(X)
Enumerations
enum WhatToGenerate {
GenProgram, GenModule, GenContents, GenFunction,
GenFunctions, GenInline, GenVariable, GenType
}
Functions
void LLVMInitializeCppBackendTarget ()
static void sanitize (std::string &str)
static std::string getTypePrefix (Type *Ty)
static std::string ftostr (const APFloat &V)
static StringRef ConvertAtomicOrdering (AtomicOrdering Ordering)
static StringRef ConvertAtomicSynchScope (SynchronizationScope SynchScope)
Variables
static cl::opt< std::string > FuncName ("cppfname", cl::desc("Specify the name of the generated function"), cl::value_desc("function name"))
static cl::opt< WhatToGenerate > GenerationType ("cppgen", cl::Optional, cl::desc("Choose what kind of output to generate"), cl::init(GenProgram), cl::values(clEnumValN(GenProgram,"program","Generate a complete program"), clEnumValN(GenModule,"module","Generate a module definition"), clEnumValN(GenContents,"contents","Generate contents of a module"), clEnumValN(GenFunction,"function","Generate a function definition"), clEnumValN(GenFunctions,"functions","Generate all function definitions"), clEnumValN(GenInline,"inline","Generate an inline function"), clEnumValN(GenVariable,"variable","Generate a variable definition"), clEnumValN(GenType,"type","Generate a type definition"), clEnumValEnd))
static cl::opt< std::string > NameToGenerate ("cppfor", cl::Optional, cl::desc("Specify the name of the thing to generate"), cl::init("!bad!"))
Macro Definition Documentation
#define HANDLE_ATTR (X)
Value:
if (attrs.contains(Attribute::X)) {                               \
        Out << "B.addAttribute(Attribute::" #X ");"; nl(Out);           \
        attrs.removeAttribute(Attribute::X);                            \
      }
Referenced by ftostr().
Enumeration Type Documentation
enum WhatToGenerate
Enumerator
GenProgram
GenModule
GenContents
GenFunction
GenFunctions
GenInline
GenVariable
GenType
Definition at line 46 of file CPPBackend.cpp.
Function Documentation
static StringRef ConvertAtomicOrdering (AtomicOrdering Ordering) static
Definition at line 1073 of file CPPBackend.cpp.
References llvm::Acquire, llvm::AcquireRelease, llvm_unreachable, llvm::Monotonic, llvm::NotAtomic, llvm::Release, llvm::SequentiallyConsistent, and llvm::Unordered.
Referenced by ConvertAtomicSynchScope().
static StringRef ConvertAtomicSynchScope (SynchronizationScope SynchScope) static
Definition at line 1086 of file CPPBackend.cpp.
References llvm::AtomicRMWInst::Add, llvm::AtomicRMWInst::And, llvm::APIntOps::And(), llvm::Function::arg_begin(), llvm::Function::arg_empty(), llvm::Function::arg_end(), llvm::AtomicRMWInst::BAD_BINOP, BB, llvm::SmallPtrSet< PtrType, SmallSize >::begin(), llvm::iplist< NodeTy, Traits >::begin(), llvm::Function::begin(), llvm::Call, call(), llvm::SwitchInst::case_begin(), llvm::SwitchInst::case_end(), ConvertAtomicOrdering(), llvm::CrossThread, llvm::GlobalValue::DefaultVisibility, llvm::SmallPtrSet< PtrType, SmallSize >::end(), llvm::iplist< NodeTy, Traits >::end(), llvm::Function::end(), ExtractElement(), F(), llvm::CmpInst::FCMP_FALSE, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_TRUE, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, FuncName, GenContents, GenerationType, GenFunction, GenFunctions, GenInline, GenModule, GenProgram, GenType, GenVariable, llvm::GlobalValue::getAlignment(), llvm::AllocaInst::getAlignment(), llvm::LoadInst::getAlignment(), llvm::StoreInst::getAlignment(), llvm::AllocaInst::getAllocatedType(), llvm::InvokeInst::getArgOperand(), llvm::Function::getAttributes(), llvm::CallInst::getAttributes(), llvm::InvokeInst::getAttributes(), llvm::CallInst::getCalledValue(), llvm::InvokeInst::getCalledValue(), llvm::Function::getCallingConv(), llvm::CallInst::getCallingConv(), llvm::InvokeInst::getCallingConv(), llvm::SwitchInst::getCondition(), llvm::SwitchInst::getDefaultDest(), llvm::Function::getFunctionType(), llvm::Function::getGC(), llvm::PHINode::getIncomingBlock(), llvm::GlobalValue::getLinkage(), llvm::Module::getModuleIdentifier(), llvm::Value::getName(), llvm::InvokeInst::getNormalDest(), llvm::CallInst::getNumArgOperands(), llvm::InvokeInst::getNumArgOperands(), llvm::SwitchInst::getNumCases(), llvm::LandingPadInst::getNumClauses(), llvm::IndirectBrInst::getNumDestinations(), llvm::PHINode::getNumIncomingValues(), llvm::ExtractValueInst::getNumIndices(), llvm::InsertValueInst::getNumIndices(), llvm::User::getNumOperands(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::PHINode::getOperandNumForIncomingValue(), llvm::AtomicRMWInst::getOperation(), llvm::LoadInst::getOrdering(), llvm::StoreInst::getOrdering(), llvm::FenceInst::getOrdering(), llvm::AtomicCmpXchgInst::getOrdering(), llvm::AtomicRMWInst::getOrdering(), llvm::Function::getReturnType(), llvm::ReturnInst::getReturnValue(), llvm::GlobalValue::getSection(), llvm::LoadInst::getSynchScope(), llvm::StoreInst::getSynchScope(), llvm::FenceInst::getSynchScope(), llvm::AtomicCmpXchgInst::getSynchScope(), llvm::AtomicRMWInst::getSynchScope(), llvm::Value::getType(), llvm::InvokeInst::getUnwindDest(), llvm::GlobalValue::getVisibility(), llvm::Function::hasGC(), llvm::GlobalValue::hasSection(), i, I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::ExtractValueInst::idx_begin(), llvm::InsertValueInst::idx_begin(), llvm::ARM_PROC::IE, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::AllocaInst::isArrayAllocation(), llvm::LoadInst::isAtomic(), llvm::StoreInst::isAtomic(), llvm::LandingPadInst::isCleanup(), llvm::GlobalValue::isDeclaration(), llvm::CallInst::isTailCall(), llvm::LoadInst::isVolatile(), llvm::StoreInst::isVolatile(), j(), llvm_unreachable, llvm::SPII::Load, load, M, llvm::AtomicRMWInst::Max, llvm::AtomicRMWInst::Min, NameToGenerate, llvm::AtomicRMWInst::Nand, llvm::AtomicRMWInst::Or, llvm::APIntOps::Or(), llvm::TargetOpcode::PHI, llvm::AArch64ISD::Ret, ret(), llvm::MCID::Select, llvm::SingleThread, llvm::SPII::Store, store, llvm::AtomicRMWInst::Sub, llvm::AtomicRMWInst::UMax, llvm::AtomicRMWInst::UMin, llvm::AtomicRMWInst::Xchg, llvm::AtomicRMWInst::Xor, and llvm::APIntOps::Xor().
static std::string ftostr (const APFloat & V) inline static
Definition at line 201 of file CPPBackend.cpp.
References llvm::APIntOps::And(), llvm::lltok::APFloat, llvm::GlobalValue::AppendingLinkage, llvm::Type::ArrayTyID, llvm::LibFunc::atof, llvm::GlobalValue::AvailableExternallyLinkage, llvm::StringRef::back(), BB, llvm::APFloat::bitcastToAPInt(), llvm::APFloat::bitwiseIsEqual(), llvm::CallingConv::C, llvm::CallingConv::Cold, llvm::GlobalValue::CommonLinkage, llvm::APFloat::convert(), llvm::APFloat::convertToDouble(), llvm::APFloat::convertToFloat(), llvm::GlobalValue::DefaultVisibility, llvm::GlobalValue::DLLExportLinkage, llvm::GlobalValue::DLLImportLinkage, double, llvm::Type::DoubleTyID, llvm::StringRef::drop_back(), llvm::StructType::element_begin(), llvm::StructType::element_end(), llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::ExternalWeakLinkage, ExtractElement(), F(), llvm::CallingConv::Fast, llvm::CmpInst::FCMP_FALSE, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_TRUE, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, llvm::ValueMapIterator< DenseMapT, KeyT >::ValueTypeProxy::first, llvm::CallingConv::FirstTargetCC, llvm::Type::FloatTyID, llvm::Type::FunctionTyID, llvm::GlobalVariable::GeneralDynamicTLSModel, llvm::PointerType::getAddressSpace(), llvm::GlobalValue::getAlignment(), getBitWidth(), llvm::Value::getContext(), llvm::Type::getDoubleTy(), llvm::SequentialType::getElementType(), llvm::Type::getFloatTy(), llvm::GlobalVariable::getInitializer(), llvm::GlobalValue::getLinkage(), llvm::Value::getName(), llvm::StructType::getName(), llvm::ArrayType::getNumElements(), llvm::VectorType::getNumElements(), llvm::AttributeSet::getNumSlots(), llvm::FunctionType::getReturnType(), llvm::GlobalValue::getSection(), llvm::APFloat::getSemantics(), llvm::AttributeSet::getSlotAttributes(), llvm::AttributeSet::getSlotIndex(), llvm::GlobalVariable::getThreadLocalMode(), llvm::GlobalValue::getType(), llvm::Value::getType(), llvm::Type::getTypeID(), getTypePrefix(), llvm::ConstantFP::getValueAPF(), llvm::GlobalValue::getVisibility(), llvm::APInt::getZExtValue(), HANDLE_ATTR, llvm::GlobalVariable::hasInitializer(), llvm::Value::hasName(), llvm::GlobalValue::hasSection(), llvm::GlobalValue::HiddenVisibility, i, I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::APFloat::IEEEdouble, llvm::APFloat::IEEEsingle, if(), index, llvm::GlobalVariable::InitialExecTLSModel, llvm::Type::IntegerTyID, llvm::GlobalValue::InternalLinkage, llvm::GlobalVariable::isConstant(), llvm::AttributeSet::isEmpty(), llvm::ConstantFP::isExactlyValue(), llvm::Type::isIntegerTy(), llvm::StructType::isLiteral(), llvm::StructType::isPacked(), llvm::Type::isPrimitiveType(), llvm::GlobalVariable::isThreadLocal(), llvm::FunctionType::isVarArg(), llvm::Type::LabelTyID, llvm::GlobalValue::LinkerPrivateLinkage, llvm::GlobalValue::LinkerPrivateWeakLinkage, llvm::GlobalValue::LinkOnceAnyLinkage, llvm::GlobalValue::LinkOnceODRLinkage, llvm_unreachable, llvm::GlobalVariable::LocalDynamicTLSModel, llvm::GlobalVariable::LocalExecTLSModel, llvm::A64CC::LT, M, N, llvm::GlobalVariable::NotThreadLocal, llvm::APIntOps::Or(), llvm::FunctionType::param_begin(), llvm::FunctionType::param_end(), llvm::Type::PointerTyID, llvm::GlobalValue::PrivateLinkage, llvm::GlobalValue::ProtectedVisibility, result, llvm::APFloat::rmNearestTiesToEven, sanitize(), llvm::ValueMapIterator< DenseMapT, KeyT >::ValueTypeProxy::second, llvm::MCID::Select, llvm::LibFunc::sprintf, llvm::A64DB::ST, llvm::Attribute::StackAlignment, llvm::LibFunc::strncmp, llvm::Type::StructTyID, llvm::tgtok::StrVal, TLM, llvm::utohexstr(), llvm::utostr(), val, llvm::Type::VectorTyID, llvm::Type::VoidTyID, llvm::GlobalValue::WeakAnyLinkage, llvm::GlobalValue::WeakODRLinkage, llvm::Type::X86_FP80TyID, llvm::Type::X86_MMXTyID, and llvm::APIntOps::Xor().
static std::string getTypePrefix (Type * Ty) static
Definition at line 180 of file CPPBackend.cpp.
References llvm::Type::ArrayTyID, llvm::Type::DoubleTyID, llvm::Type::FloatTyID, llvm::Type::FunctionTyID, getBitWidth(), llvm::Type::getTypeID(), llvm::Type::IntegerTyID, llvm::Type::LabelTyID, llvm::Type::PointerTyID, llvm::report_fatal_error(), llvm::Type::StructTyID, llvm::utostr(), llvm::Type::VectorTyID, and llvm::Type::VoidTyID.
Referenced by ftostr().
void LLVMInitializeCppBackendTarget ()
Definition at line 77 of file CPPBackend.cpp.
References F(), I, llvm::raw_ostream::indent(), llvm::A64CC::LT, M, llvm::TheCppBackendTarget, TLM, val, and llvm::X.
static void sanitize (std::string & str) inline static
Definition at line 174 of file CPPBackend.cpp.
References i.
Referenced by ftostr().
Variable Documentation
cl::opt<std::string> FuncName("cppfname", cl::desc("Specify the name of the generated function"), cl::value_desc("function name")) static
Referenced by ConvertAtomicSynchScope(), llvm::LibCallSimplifierImpl::hasFloatVersion(), and INITIALIZE_PASS().
cl::opt<WhatToGenerate> GenerationType("cppgen", cl::Optional, cl::desc("Choose what kind of output to generate"), cl::init(GenProgram), cl::values(clEnumValN(GenProgram,"program","Generate a complete program"),clEnumValN(GenModule,"module","Generate a module definition"),clEnumValN(GenContents,"contents","Generate contents of a module"),clEnumValN(GenFunction,"function","Generate a function definition"),clEnumValN(GenFunctions,"functions","Generate all function definitions"),clEnumValN(GenInline,"inline","Generate an inline function"),clEnumValN(GenVariable,"variable","Generate a variable definition"),clEnumValN(GenType,"type","Generate a type definition"),clEnumValEnd)) static
Referenced by ConvertAtomicSynchScope().
cl::opt<std::string> NameToGenerate("cppfor", cl::Optional, cl::desc("Specify the name of the thing to generate"), cl::init("!bad!")) static
Referenced by ConvertAtomicSynchScope().