LLVM: CppBackendTargetInfo.cpp File Reference
LLVM API Documentation
CppBackendTargetInfo.cpp File Reference
#include "CPPTargetMachine.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/TargetRegistry.h"
Functions
static unsigned CppBackend_TripleMatchQuality (const std::string &TT)
void LLVMInitializeCppBackendTargetInfo ()
void LLVMInitializeCppBackendTargetMC ()
Function Documentation
static unsigned CppBackend_TripleMatchQuality (const std::string & TT) static
Definition at line 17 of file CppBackendTargetInfo.cpp.
Referenced by LLVMInitializeCppBackendTargetInfo().
void LLVMInitializeCppBackendTargetInfo ()
Definition at line 22 of file CppBackendTargetInfo.cpp.
References CppBackend_TripleMatchQuality(), llvm::TargetRegistry::RegisterTarget(), and llvm::TheCppBackendTarget.
void LLVMInitializeCppBackendTargetMC ()
Definition at line 28 of file CppBackendTargetInfo.cpp.