LLVM: DAGCombiner.cpp File Reference
LLVM API Documentation
DAGCombiner.cpp File Reference
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include "llvm/Target/TargetSubtargetInfo.h"
#include <algorithm>
Classes
struct LoadedSliceSorter
Sorts LoadedSlice according to their offset.
struct BaseIndexOffset
struct MemOpLink
struct ConsecutiveMemoryChainSorter
Sorts store nodes in a link according to their offset from a shared.
Macros
#define DEBUG_TYPE "dagcombine"
Functions
STATISTIC (NodesCombined,"Number of dag nodes combined")
STATISTIC (PreIndexedNodes,"Number of pre-indexed nodes created")
STATISTIC (PostIndexedNodes,"Number of post-indexed nodes created")
STATISTIC (OpsNarrowed,"Number of load/op/store narrowed")
STATISTIC (LdStFP2Int,"Number of fp load/store pairs transformed to int")
STATISTIC (SlicedLoads,"Number of load sliced")
static char isNegatibleForFree (SDValue Op, bool LegalOperations, const TargetLowering &TLI, const TargetOptions *Options, unsigned Depth=0)
static SDValue GetNegatedExpression (SDValue Op, SelectionDAG &DAG, bool LegalOperations, unsigned Depth=0)
static bool isSetCCEquivalent (SDValue N, SDValue &LHS, SDValue &RHS, SDValue &CC)
static bool isOneUseSetCC (SDValue N)
static SDValue getInputChainForNode (SDNode *N)
static SDValue combineShlAddConstant (SDLoc DL, SDValue N0, SDValue N1, SelectionDAG &DAG)
static SDValue tryFoldToZero (SDLoc DL, const TargetLowering &TLI, EVT VT, SelectionDAG &DAG, bool LegalOperations, bool LegalTypes)
static bool isConstantSplatVector (SDNode *N, APInt &SplatValue)
static bool isBSwapHWordElement (SDValue N, SmallVectorImpl< SDNode * > &Parts)
static bool MatchRotateHalf (SDValue Op, SDValue &Shift, SDValue &Mask)
MatchRotateHalf - Match "(X shl/srl V1) & V2" where V2 may not be present.
static std::pair< SDValue, SDValue > SplitVSETCC (const SDNode *N, SelectionDAG &DAG)
static bool ExtendUsesToFormExtLoad (SDNode *N, SDValue N0, unsigned ExtOpc, SmallVectorImpl< SDNode * > &ExtendNodes, const TargetLowering &TLI)
static bool isTruncateOf (SelectionDAG &DAG, SDValue N, SDValue &Op, APInt &KnownZero)
static SDNode * getBuildPairElt (SDNode *N, unsigned i)
static bool canFoldInAddressingMode (SDNode *N, SDNode *Use, SelectionDAG &DAG, const TargetLowering &TLI)
static bool areUsedBitsDense (const APInt &UsedBits)
Check that all bits set in UsedBits form a dense region, i.e., UsedBits looks like 0..0 1..1 0..0.
static bool areSlicesNextToEachOther (const LoadedSlice &First, const LoadedSlice &Second)
Check whether or not First and Second are next to each other in memory. This means that there is no hole between the bits loaded by First and the bits loaded by Second.
static void adjustCostForPairing (SmallVectorImpl< LoadedSlice > &LoadedSlices, LoadedSlice::Cost &GlobalLSCost)
Adjust the GlobalLSCost according to the target paring capabilities and the layout of the slices.
static bool isSlicingProfitable (SmallVectorImpl< LoadedSlice > &LoadedSlices, const APInt &UsedBits, bool ForCodeSize)
Check the profitability of all involved LoadedSlice. Currently, it is considered profitable if there is exactly two involved slices (1) which are (2) next to each other in memory, and whose cost (.
static std::pair< unsigned, unsigned > CheckForMaskedLoad (SDValue V, SDValue Ptr, SDValue Chain)
static SDNode * ShrinkLoadReplaceStoreWithStore (const std::pair< unsigned, unsigned > &MaskInfo, SDValue IVal, StoreSDNode *St, DAGCombiner *DC)
static SDValue partitionShuffleOfConcats (SDNode *N, SelectionDAG &DAG)
static bool FindBaseOffset (SDValue Ptr, SDValue &Base, int64_t &Offset, const GlobalValue *&GV, const void *&CV)
FindBaseOffset - Return true if base is a frame index, which is known not.
Macro Definition Documentation
#define DEBUG_TYPE "dagcombine"
Definition at line 19 of file DAGCombiner.cpp.
Function Documentation
static void adjustCostForPairing (SmallVectorImpl< LoadedSlice > & LoadedSlices, LoadedSlice::Cost & GlobalLSCost) static
Adjust the GlobalLSCost according to the target paring capabilities and the layout of the slices.
Precondition
GlobalLSCost should account for at least as many loads as there is in the slices in LoadedSlices.
Definition at line 7933 of file DAGCombiner.cpp.
References areSlicesNextToEachOther(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::SmallVectorTemplateCommon< T >::end(), First, and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by isSlicingProfitable().
static bool areSlicesNextToEachOther (const LoadedSlice & First, const LoadedSlice & Second) static
Check whether or not First and Second are next to each other in memory. This means that there is no hole between the bits loaded by First and the bits loaded by Second.
Definition at line 7918 of file DAGCombiner.cpp.
References areUsedBitsDense().
Referenced by adjustCostForPairing().
static bool areUsedBitsDense (const APInt & UsedBits) static
Check that all bits set in UsedBits form a dense region, i.e., UsedBits looks like 0..0 1..1 0..0.
Definition at line 7901 of file DAGCombiner.cpp.
References llvm::APInt::countLeadingZeros(), llvm::APInt::countTrailingZeros(), llvm::APInt::getActiveBits(), llvm::APInt::isAllOnesValue(), llvm::APInt::lshr(), and llvm::APInt::trunc().
Referenced by areSlicesNextToEachOther(), and isSlicingProfitable().
static bool canFoldInAddressingMode (SDNode * N, SDNode * Use, SelectionDAG & DAG, const TargetLowering & TLI) static
canFoldInAddressingMode - Return true if 'Use' is a load or a store that uses N as its base pointer and that N may be folded in the load / store addressing mode.
Definition at line 7055 of file DAGCombiner.cpp.
References llvm::ISD::ADD, llvm::AfterLegalizeDAG, Align, llvm::ISD::BITCAST, llvm::SmallVectorImpl< T >::clear(), llvm::dbgs(), DEBUG, llvm::SelectionDAG::DeleteNode(), llvm::SDNode::dump(), llvm::dyn_cast(), llvm::DataLayout::getABITypeAlignment(), llvm::MemSDNode::getAlignment(), llvm::MachineMemOperand::getBaseAlignment(), llvm::LoadSDNode::getBasePtr(), llvm::StoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::TargetRegisterInfo::getCommonSubClass(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::TargetLoweringBase::getDataLayout(), llvm::LoadSDNode::getExtensionType(), llvm::SelectionDAG::getExtLoad(), llvm::SelectionDAG::getIndexedLoad(), llvm::SelectionDAG::getIndexedStore(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getLoad(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::LoadSDNode::getOffset(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::MemSDNode::getPointerInfo(), llvm::TargetLowering::getPostIndexedAddressParts(), llvm::TargetLowering::getPreIndexedAddressParts(), llvm::TargetLoweringBase::getRegClassFor(), llvm::TargetMachine::getRegisterInfo(), llvm::ConstantSDNode::getSExtValue(), llvm::EVT::getSimpleVT(), llvm::TargetMachine::getSubtarget(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::TargetLoweringBase::getTargetMachine(), llvm::MemSDNode::getTBAAInfo(), llvm::EVT::getTypeForEVT(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::StoreSDNode::getValue(), llvm::SDNode::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::MachinePointerInfo::getWithOffset(), llvm::SDNode::hasAnyUseOfValue(), llvm::SDNode::hasOneUse(), llvm::SDNode::hasPredecessorHelper(), i, I, llvm::SelectionDAG::InferPtrAlignment(), llvm::DataLayout::isBigEndian(), llvm::EVT::isExtended(), llvm::TargetLoweringBase::isIndexedLoadLegal(), llvm::TargetLoweringBase::isIndexedStoreLegal(), llvm::MemSDNode::isInvariant(), llvm::TargetLoweringBase::isLegalAddImmediate(), llvm::TargetLoweringBase::isLegalAddressingMode(), llvm::ISD::isNON_TRUNCStore(), llvm::MemSDNode::isNonTemporal(), llvm::ISD::isNormalLoad(), llvm::TargetLoweringBase::isOperationLegal(), llvm::SDNode::isPredecessorOf(), llvm::TargetLoweringBase::isTruncateFree(), llvm::TargetLoweringBase::isTypeLegal(), llvm::LSBaseSDNode::isUnindexed(), llvm::MemSDNode::isVolatile(), llvm::A64DB::LD, llvm::ISD::LOAD, llvm::A64CC::LS, llvm::MinAlign(), N, llvm::ISD::NON_EXTLOAD, llvm::CodeGenOpt::None, llvm::operator!=(), llvm::operator+=(), llvm::operator<(), llvm::operator<=(), llvm::operator==(), llvm::operator>(), llvm::operator>=(), llvm::MVT::Other, llvm::ISD::POST_DEC, llvm::ISD::POST_INC, llvm::ISD::PRE_DEC, llvm::ISD::PRE_INC, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::APInt::setAllBits(), Shift, llvm::SmallVectorTemplateCommon< T >::size(), llvm::A64DB::ST, llvm::ISD::SUB, std::swap(), llvm::ISD::TokenFactor, llvm::RegState::Undef, llvm::ISD::UNDEF, llvm::ISD::UNINDEXED, llvm::MVT::Untyped, llvm::SDNode::use_begin(), llvm::SDNode::use_empty(), llvm::SDNode::use_end(), and llvm::ISD::ZERO_EXTEND.
static std::pair<unsigned, unsigned> CheckForMaskedLoad (SDValue V, SDValue Ptr, SDValue Chain) static
CheckForMaskedLoad - Check to see if V is (and load (ptr), imm), where the load is having specific bytes cleared out. If so, return the byte size being masked out and the shift amount.
Definition at line 8136 of file DAGCombiner.cpp.
References llvm::ISD::AND, llvm::countLeadingZeros(), llvm::CountTrailingOnes_64(), llvm::countTrailingZeros(), llvm::LoadSDNode::getBasePtr(), llvm::SDValue::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), i, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::isNormalLoad(), llvm::A64DB::LD, and llvm::ISD::TokenFactor.
Referenced by ShrinkLoadReplaceStoreWithStore().
static SDValue combineShlAddConstant (SDLoc DL, SDValue N0, SDValue N1, SelectionDAG & DAG) static
Definition at line 1380 of file DAGCombiner.cpp.
References llvm::ISD::ADD, llvm::ISD::ADDC, llvm::ISD::ADDE, llvm::ISD::AND, llvm::ISD::CARRY_FALSE, llvm::SelectionDAG::ComputeMaskedBits(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::dyn_cast(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::ConstantSDNode::getAPIntValue(), llvm::APInt::getBoolValue(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getGlobalAddress(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getVTList(), llvm::ISD::GlobalAddress, llvm::MVT::Glue, llvm::SDNode::hasAnyUseOfValue(), llvm::SDNode::hasOneUse(), llvm::MVT::i1, llvm::ISD::isBuildVectorAllZeros(), llvm::TargetLowering::isOffsetFoldingLegal(), llvm::ConstantSDNode::isOne(), llvm::TargetLoweringBase::isOperationLegal(), llvm::ISD::OR, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::ISD::SUB, llvm::ISD::UNDEF, and llvm::ISD::ZERO_EXTEND.
static bool ExtendUsesToFormExtLoad (SDNode * N, SDValue N0, unsigned ExtOpc, SmallVectorImpl< SDNode * > & ExtendNodes, const TargetLowering & TLI) static
Definition at line 4409 of file DAGCombiner.cpp.
References llvm::ISD::AND, llvm::APIntOps::And(), llvm::ISD::ANY_EXTEND, CC, llvm::EVT::changeVectorElementTypeToInteger(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::ISD::Constant, llvm::ISD::CopyToReg, llvm::APInt::getAllOnesValue(), llvm::LoadSDNode::getBasePtr(), llvm::TargetLoweringBase::getBooleanContents(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::LoadSDNode::getExtensionType(), llvm::SelectionDAG::getExtLoad(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getResNo(), llvm::SDUse::getResNo(), llvm::EVT::getScalarType(), llvm::SelectionDAG::getSelect(), llvm::SelectionDAG::getSetCC(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::EVT::getSizeInBits(), llvm::SDUse::getUser(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::SDNode::getValueType(), llvm::SDValue::hasOneUse(), i, llvm::ISD::isEXTLoad(), llvm::TargetLoweringBase::isLoadExtLegal(), llvm::ISD::isNON_EXTLoad(), llvm::TargetLoweringBase::isOperationLegal(), llvm::ISD::isSEXTLoad(), llvm::ISD::isSignedIntSetCC(), llvm::TargetLoweringBase::isTruncateFree(), llvm::ISD::isUNINDEXEDLoad(), llvm::EVT::isVector(), llvm::MemSDNode::isVolatile(), j(), llvm::ISD::OR, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::ISD::SETCC, llvm::APInt::sext(), llvm::ISD::SEXTLOAD, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::SelectionDAG::SignBitIsZero(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::ISD::TRUNCATE, llvm::SDNode::use_begin(), llvm::SDNode::use_end(), llvm::ISD::XOR, llvm::ISD::ZERO_EXTEND, llvm::TargetLoweringBase::ZeroOrNegativeOneBooleanContent, and llvm::ISD::ZEXTLOAD.
Referenced by isTruncateOf().
static bool FindBaseOffset (SDValue Ptr, SDValue & Base, int64_t & Offset, const GlobalValue *& GV, const void *& CV) static
FindBaseOffset - Return true if base is a frame index, which is known not.
Definition at line 10768 of file DAGCombiner.cpp.
References llvm::ISD::ADD, llvm::AliasAnalysis::alias(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::SmallVectorImpl< T >::clear(), llvm::SmallVectorBase::empty(), llvm::ISD::EntryToken, G, llvm::MemSDNode::getBasePtr(), llvm::SelectionDAG::getEntryNode(), llvm::MachineFunction::getFrameInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::MachineFrameInfo::getObjectOffset(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::MemSDNode::getOriginalAlignment(), llvm::EVT::getSizeInBits(), llvm::MemSDNode::getSrcValue(), llvm::MemSDNode::getSrcValueOffset(), llvm::TargetMachine::getSubtarget(), llvm::TargetLoweringBase::getTargetMachine(), llvm::MemSDNode::getTBAAInfo(), llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::MemSDNode::isVolatile(), llvm::ISD::LOAD, llvm::A64CC::LS, n, N, llvm::AliasAnalysis::NoAlias, llvm::X86II::OpSize, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::pop_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::ISD::STORE, and llvm::ISD::TokenFactor.
static SDNode* getBuildPairElt (SDNode * N, unsigned i) static
Definition at line 5642 of file DAGCombiner.cpp.
References llvm::AfterLegalizeDAG, Align, llvm::TargetOptions::AllowFPOpFusion, llvm::ISD::AND, llvm::SmallVectorTemplateCommon< T >::back(), llvm::ISD::BITCAST, llvm::ISD::BR_CC, llvm::ISD::BRCOND, llvm::ISD::BUILD_PAIR, llvm::ISD::BUILD_VECTOR, CC, llvm::ISD::Constant, llvm::ISD::ConstantFP, llvm::dbgs(), DEBUG, llvm::SelectionDAG::DeleteNode(), llvm::APFloat::divide(), llvm::SDNode::dump(), llvm::dyn_cast(), llvm::ISD::EXTLOAD, f(), llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FABS, llvm::ISD::FADD, llvm::FPOpFusion::Fast, llvm::ISD::FCEIL, llvm::ISD::FCOPYSIGN, llvm::ISD::FDIV, llvm::ISD::FFLOOR, llvm::ISD::FMA, llvm::ISD::FMUL, llvm::ISD::FNEG, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FREM, llvm::ISD::FSUB, llvm::ISD::FTRUNC, llvm::CondCodeSDNode::get(), llvm::MemSDNode::getAlignment(), llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::ConstantFPSDNode::getConstantFPValue(), llvm::SDNode::getConstantOperandVal(), llvm::SelectionDAG::getContext(), llvm::TargetLoweringBase::getDataLayout(), llvm::SelectionDAG::getExtLoad(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::MemSDNode::getMemOperand(), GetNegatedExpression(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDNode::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MemSDNode::getPointerInfo(), llvm::SDValue::getResNo(), llvm::APFloat::getSemantics(), llvm::SelectionDAG::getSetCC(), llvm::APInt::getSignBit(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTarget(), llvm::TargetMachine::getTargetLowering(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::MemSDNode::getTBAAInfo(), llvm::EVT::getTypeForEVT(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::ConstantFPSDNode::getValueAPF(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::SDValue::hasOneUse(), llvm::SDNode::hasOneUse(), i, llvm::MVT::i1, llvm::tgtok::In, llvm::tgtok::Int, llvm::TargetLoweringBase::isBigEndian(), llvm::ISD::isBuildVectorAllZeros(), llvm::SelectionDAG::isConsecutiveLoad(), llvm::ConstantFPSDNode::isExactlyValue(), llvm::TargetLoweringBase::isFAbsFree(), llvm::EVT::isFloatingPoint(), llvm::TargetLoweringBase::isFMAFasterThanFMulAndFAdd(), llvm::TargetLoweringBase::isFNegFree(), llvm::TargetLoweringBase::isFPImmLegal(), llvm::EVT::isInteger(), llvm::MemSDNode::isInvariant(), llvm::TargetLoweringBase::isLittleEndian(), llvm::TargetLoweringBase::isLoadBitCastBeneficial(), llvm::TargetLoweringBase::isLoadExtLegal(), isNegatibleForFree(), llvm::APFloat::isNegative(), llvm::ISD::isNON_EXTLoad(), llvm::MemSDNode::isNonTemporal(), llvm::ISD::isNormalLoad(), llvm::TargetLoweringBase::isOperationLegal(), llvm::TargetLoweringBase::isOperationLegalOrCustom(), llvm::APInt::isPowerOf2(), llvm::ISD::isScalarToVector(), llvm::EVT::isVector(), llvm::MemSDNode::isVolatile(), llvm::APFloat::isZero(), llvm::ConstantFPSDNode::isZero(), j(), llvm::SPII::Load, llvm::ISD::LOAD, llvm::APInt::logBase2(), llvm::APInt::lshr(), llvm::ISD::MERGE_VALUES, N, llvm::APFloat::opInexact, llvm::APFloat::opOK, llvm::TargetMachine::Options, llvm::ISD::OR, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::APFloat::rmNearestTiesToEven, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::ISD::SETEQ, llvm::ISD::SETNE, llvm::ISD::SIGN_EXTEND, llvm::SelectionDAG::SignBitIsZero(), llvm::ISD::SINT_TO_FP, llvm::SmallVectorTemplateCommon< T >::size(), llvm::ISD::SRL, llvm::APInt::trunc(), llvm::ISD::TRUNCATE, llvm::ISD::UINT_TO_FP, llvm::ISD::UNDEF, llvm::TargetOptions::UnsafeFPMath, llvm::SDNode::use_begin(), llvm::X, llvm::ISD::XOR, llvm::ISD::ZERO_EXTEND, llvm::APInt::zext(), and llvm::APInt::zextOrTrunc().
static SDValue getInputChainForNode (SDNode * N) static
getInputChainForNode - Given a node, return its input chain if it has one, otherwise return a null sd operand.
Definition at line 1271 of file DAGCombiner.cpp.
References llvm::SmallVectorTemplateCommon< T >::begin(), llvm::SelectionDAG::DeleteNode(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::ISD::EntryToken, llvm::SelectionDAG::getEntryNode(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDValue::hasOneUse(), i, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::ISD::TokenFactor, and llvm::SDNode::use_empty().
static SDValue GetNegatedExpression (SDValue Op, SelectionDAG & DAG, bool LegalOperations, unsigned Depth = 0) static
GetNegatedExpression - If isNegatibleForFree returns true, this function returns the newly negated expression.
Definition at line 491 of file DAGCombiner.cpp.
References llvm::APFloat::changeSign(), llvm::ISD::ConstantFP, llvm::ISD::FADD, llvm::ISD::FDIV, llvm::ISD::FMUL, llvm::ISD::FNEG, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FSIN, llvm::ISD::FSUB, llvm::SelectionDAG::getConstantFP(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getTarget(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::SDValue::hasOneUse(), llvm::TargetOptions::HonorSignDependentRoundingFPMath(), isNegatibleForFree(), llvm_unreachable, llvm::TargetMachine::Options, and llvm::TargetOptions::UnsafeFPMath.
Referenced by getBuildPairElt().
static bool isBSwapHWordElement (SDValue N, SmallVectorImpl< SDNode * > & Parts) static
isBSwapHWordElement - Return true if the specified node is an element that makes up a 32-bit packed halfword byteswap. i.e. ((x&0xff)<<8)|((x&0xff00)>>8)|((x&0x00ff0000)<<8)|((x&0xff000000)>>8)
Definition at line 2990 of file DAGCombiner.cpp.
References llvm::ISD::AND, llvm::ISD::BSWAP, C1, llvm::ISD::Constant, llvm::dyn_cast(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::APInt::getAllOnesValue(), llvm::ConstantSDNode::getAPIntValue(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getSetCC(), llvm::ISD::getSetCCOrOperation(), llvm::ISD::getSetCCSwappedOperands(), llvm::SDValue::getSimpleValueType(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::ConstantSDNode::getZExtValue(), llvm::SDNode::hasOneUse(), llvm::MVT::i32, llvm::ISD::isBuildVectorAllOnes(), llvm::ISD::isBuildVectorAllZeros(), llvm::TargetLoweringBase::isCondCodeLegal(), llvm::EVT::isInteger(), llvm::TargetLoweringBase::isOperationLegal(), llvm::TargetLoweringBase::isOperationLegalOrCustom(), isSetCCEquivalent(), llvm::EVT::isVector(), llvm::SelectionDAG::MaskedValueIsZero(), llvm::ISD::OR, llvm::A64SE::ROR, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SETCC, llvm::ISD::SETCC_INVALID, llvm::ISD::SETGT, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SHL, llvm::ISD::SRL, std::swap(), llvm::ISD::UNDEF, and llvm::X.
static bool isConstantSplatVector (SDNode * N, APInt & SplatValue) static
isConstantSplatVector - Returns true if N is a BUILD_VECTOR node whose elements are all the same constant or undefined.
Definition at line 1783 of file DAGCombiner.cpp.
References llvm::ISD::ADD, ADD, llvm::ISD::ADDC, llvm::AfterLegalizeDAG, llvm::AfterLegalizeTypes, llvm::ISD::AND, llvm::ISD::ANY_EXTEND, B, llvm::ISD::BITCAST, llvm::ISD::BSWAP, llvm::dyn_cast(), llvm::ISD::EXTLOAD, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::FoldConstantArithmetic(), llvm::LSBaseSDNode::getAddressingMode(), llvm::MemSDNode::getAlignment(), llvm::APInt::getAllOnesValue(), llvm::ConstantSDNode::getAPIntValue(), llvm::LoadSDNode::getBasePtr(), llvm::APInt::getBitWidth(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::LoadSDNode::getExtensionType(), llvm::SelectionDAG::getExtLoad(), llvm::APInt::getHighBitsSet(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getLoad(), llvm::ShuffleVectorSDNode::getMask(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::APInt::getNullValue(), llvm::SDNode::getNumOperands(), llvm::SDNode::getNumValues(), llvm::LoadSDNode::getOffset(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MemSDNode::getPointerInfo(), llvm::EVT::getScalarType(), llvm::SelectionDAG::getSetCC(), llvm::ISD::getSetCCAndOperation(), llvm::ISD::getSetCCSwappedOperands(), llvm::APInt::getSExtValue(), llvm::SDValue::getSimpleValueType(), llvm::EVT::getSimpleVT(), llvm::MVT::getSizeInBits(), llvm::EVT::getSizeInBits(), llvm::EVT::getStoreSize(), llvm::MemSDNode::getTBAAInfo(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::SDNode::getVTList(), llvm::ConstantSDNode::getZExtValue(), llvm::SDNode::hasAnyUseOfValue(), llvm::SDValue::hasOneUse(), llvm::SDNode::hasOneUse(), llvm::HexagonISD::Hi, i, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::APInt::isAllOnesValue(), llvm::TargetLoweringBase::isBigEndian(), llvm::ISD::isBuildVectorAllOnes(), llvm::ISD::isBuildVectorAllZeros(), llvm::TargetLoweringBase::isCondCodeLegal(), llvm::BuildVectorSDNode::isConstantSplat(), llvm::ISD::isEXTLoad(), llvm::TargetLoweringBase::isIntDivCheap(), llvm::EVT::isInteger(), llvm::TargetLoweringBase::isLegalAddImmediate(), llvm::TargetLoweringBase::isLoadExtLegal(), llvm::APIntOps::isMask(), llvm::MemSDNode::isNonTemporal(), llvm::ConstantSDNode::isNullValue(), llvm::TargetLoweringBase::isOperationLegal(), llvm::TargetLoweringBase::isPow2DivCheap(), llvm::APInt::isPowerOf2(), llvm::EVT::isRound(), isSetCCEquivalent(), llvm::ISD::isSEXTLoad(), llvm::EVT::isSimple(), llvm::TargetLoweringBase::isTruncateFree(), llvm::TargetLowering::isTypeDesirableForOp(), llvm::TargetLoweringBase::isTypeLegal(), llvm::LSBaseSDNode::isUnindexed(), llvm::ISD::isUNINDEXEDLoad(), llvm::EVT::isVector(), llvm::MemSDNode::isVolatile(), llvm::TargetLoweringBase::isZExtFree(), llvm::HexagonISD::Lo, llvm::SPII::Load, llvm::ISD::LOAD, llvm::APInt::logBase2(), llvm::APIntOps::logBase2(), llvm::APInt::lshr(), llvm::SelectionDAG::MaskedValueIsZero(), llvm::MinAlign(), llvm::ISD::MUL, llvm::ISD::MULHS, llvm::ISD::MULHU, n, N, llvm::ISD::NON_EXTLOAD, llvm::SDNode::op_begin(), llvm::ISD::OR, llvm::ISD::SADDO, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SDIV, llvm::ISD::SETCC, llvm::ISD::SETCC_INVALID, llvm::ISD::SETEQ, llvm::ISD::SETGT, llvm::ISD::SETNE, llvm::ISD::SETUGE, llvm::ISD::SEXTLOAD, llvm::ISD::SHL, llvm::APInt::shl(), llvm::ISD::SIGN_EXTEND, llvm::SelectionDAG::SignBitIsZero(), llvm::ISD::SRA, llvm::ISD::SREM, llvm::ISD::SRL, llvm::ISD::SUB, std::swap(), llvm::APInt::trunc(), llvm::ISD::TRUNCATE, llvm::ISD::UADDO, llvm::ISD::UDIV, llvm::ISD::UNDEF, llvm::ISD::UREM, llvm::ISD::VECTOR_SHUFFLE, Y, llvm::ISD::ZERO_EXTEND, llvm::ISD::ZEXTLOAD, and llvm::APInt::zextOrTrunc().
static char isNegatibleForFree (SDValue Op, bool LegalOperations, const TargetLowering & TLI, const TargetOptions * Options, unsigned Depth = 0) static
isNegatibleForFree - Return 1 if we can compute the negated form of the specified expression for the same cost as the expression itself, or 2 if we can compute the negated form more cheaply than the expression itself.
Definition at line 427 of file DAGCombiner.cpp.
References llvm::ISD::ConstantFP, llvm::ISD::FADD, llvm::ISD::FDIV, llvm::ISD::FMUL, llvm::ISD::FNEG, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FSIN, llvm::ISD::FSUB, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), llvm::SDValue::hasOneUse(), llvm::TargetLoweringBase::isOperationLegalOrCustom(), and llvm::TargetOptions::UnsafeFPMath.
Referenced by getBuildPairElt(), and GetNegatedExpression().
static bool isOneUseSetCC (SDValue N) static
Definition at line 599 of file DAGCombiner.cpp.
References llvm::ISD::ADD, llvm::ISD::ADDC, llvm::ISD::ADDE, llvm::AfterLegalizeTypes, llvm::AfterLegalizeVectorOps, llvm::SelectionDAG::allnodes_begin(), llvm::SelectionDAG::allnodes_end(), llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::ISD::BITCAST, llvm::ISD::BR_CC, llvm::ISD::BRCOND, llvm::ISD::BUILD_PAIR, llvm::ISD::BUILD_VECTOR, llvm::ISD::BUILTIN_OP_END, llvm::ISD::CONCAT_VECTORS, llvm::ISD::Constant, llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::dbgs(), DEBUG, llvm::ISD::DELETED_NODE, llvm::SelectionDAG::DeleteNode(), llvm::NVPTXISD::Dummy, llvm::SDNode::dump(), llvm::SmallPtrSetImpl::empty(), llvm::SmallPtrSet< PtrType, SmallSize >::erase(), llvm::ISD::EXTLOAD, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FCEIL, llvm::ISD::FCOPYSIGN, llvm::ISD::FDIV, llvm::ISD::FFLOOR, llvm::ISD::FMA, llvm::ISD::FMUL, llvm::ISD::FNEG, llvm::SelectionDAG::FoldConstantArithmetic(), llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_ROUND_INREG, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FREM, llvm::ISD::FSUB, llvm::ISD::FTRUNC, llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::LoadSDNode::getExtensionType(), llvm::SelectionDAG::getExtLoad(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNodeIfExists(), llvm::SDNode::getNumOperands(), llvm::SDNode::getNumValues(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getRoot(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::SDNode::getValueType(), llvm::SDNode::getVTList(), llvm::SelectionDAG::getZeroExtendInReg(), llvm::SDValue::hasOneUse(), llvm::SDNode::hasOneUse(), llvm::TargetLoweringBase::hasTargetDAGCombine(), i, I, llvm::ISD::INSERT_VECTOR_ELT, llvm::EVT::isByteSized(), llvm::SelectionDAG::isCommutativeBinOp(), llvm::TargetLowering::IsDesirableToPromoteOp(), llvm::EVT::isInteger(), llvm::TargetLoweringBase::isLoadExtLegal(), llvm::ISD::isNON_EXTLoad(), llvm::TargetLoweringBase::isOperationLegal(), isSetCCEquivalent(), llvm::TargetLowering::isTypeDesirableForOp(), llvm::EVT::isVector(), llvm::A64DB::LD, llvm::SPII::Load, llvm::ISD::LOAD, llvm::ISD::MERGE_VALUES, llvm::ISD::MUL, llvm::ISD::MULHS, llvm::ISD::MULHU, N, llvm::TargetLowering::TargetLoweringOpt::New, llvm::TargetLowering::TargetLoweringOpt::Old, llvm::ISD::OR, llvm::TargetLowering::PerformDAGCombine(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SelectionDAG::RemoveDeadNodes(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::ISD::SDIV, llvm::ISD::SDIVREM, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::SelectionDAG::setRoot(), llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::TargetLowering::SimplifyDemandedBits(), llvm::ISD::SINT_TO_FP, llvm::ISD::SMUL_LOHI, llvm::ISD::SMULO, llvm::ISD::SRA, llvm::ISD::SREM, llvm::ISD::SRL, llvm::ISD::STORE, llvm::ISD::SUB, llvm::ISD::SUBC, llvm::ISD::SUBE, llvm::ISD::TokenFactor, llvm::SelectionDAG::TransferDbgValues(), llvm::ISD::TRUNCATE, llvm::ISD::UDIV, llvm::ISD::UDIVREM, llvm::ISD::UINT_TO_FP, llvm::ISD::UMUL_LOHI, llvm::ISD::UMULO, llvm::ISD::UREM, llvm::SDNode::use_empty(), llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::VSELECT, llvm::ISD::XOR, llvm::ISD::ZERO_EXTEND, and llvm::ISD::ZEXTLOAD.
Referenced by MatchRotateHalf().
static bool isSetCCEquivalent (SDValue N, SDValue & LHS, SDValue & RHS, SDValue & CC) static
Definition at line 575 of file DAGCombiner.cpp.
References llvm::ISD::Constant, llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::ISD::SELECT_CC, and llvm::ISD::SETCC.
Referenced by isBSwapHWordElement(), isConstantSplatVector(), isOneUseSetCC(), and MatchRotateHalf().
static bool isSlicingProfitable (SmallVectorImpl< LoadedSlice > & LoadedSlices, const APInt & UsedBits, bool ForCodeSize) static
Check the profitability of all involved LoadedSlice. Currently, it is considered profitable if there is exactly two involved slices (1) which are (2) next to each other in memory, and whose cost (.
See also
LoadedSlice::Cost) is smaller than the original load (3).
Note: The order of the elements in LoadedSlices may be modified, but not the elements themselves.
FIXME: When the cost model will be mature enough, we can relax constraints (1) and (2).
Definition at line 7997 of file DAGCombiner.cpp.
References adjustCostForPairing(), llvm::AfterLegalizeDAG, areUsedBitsDense(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValue(), llvm::SDNode::getValueSizeInBits(), llvm::SDNode::getValueType(), llvm::SDNode::hasOneUse(), llvm::EVT::isInteger(), llvm::ISD::isNormalLoad(), llvm::isPowerOf2_32(), llvm::MemSDNode::isVolatile(), llvm::A64DB::LD, llvm::ISD::LOAD, llvm::A64CC::LS, N, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), Shift, llvm::SmallVectorTemplateCommon< T >::size(), llvm::ISD::SRL, llvm::ISD::TokenFactor, llvm::ISD::TRUNCATE, llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
static bool isTruncateOf (SelectionDAG & DAG, SDValue N, SDValue & Op, APInt & KnownZero) static
Definition at line 4707 of file DAGCombiner.cpp.
References llvm::ISD::ADD, llvm::AfterLegalizeVectorOps, llvm::ISD::AND, llvm::APIntOps::And(), llvm::ISD::ANY_EXTEND, llvm::ISD::BITCAST, llvm::EVT::bitsGT(), llvm::EVT::bitsLT(), llvm::ISD::BUILD_VECTOR, llvm::SelectionDAG::ComputeMaskedBits(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::ISD::CONCAT_VECTORS, llvm::ISD::Constant, llvm::dyn_cast(), ExtendUsesToFormExtLoad(), llvm::ISD::EXTLOAD, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MemSDNode::getAlignment(), llvm::ConstantSDNode::getAPIntValue(), llvm::LoadSDNode::getBasePtr(), llvm::APInt::getBitsSet(), llvm::APInt::getBitWidth(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::LoadSDNode::getExtensionType(), llvm::SelectionDAG::getExtLoad(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getLoad(), llvm::APInt::getLowBitsSet(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDNode::getNumValues(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MemSDNode::getPointerInfo(), llvm::EVT::getScalarType(), llvm::SelectionDAG::getSetCC(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::EVT::getSizeInBits(), llvm::EVT::getStoreSizeInBits(), llvm::MemSDNode::getTBAAInfo(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::TargetLoweringBase::getVectorIdxTy(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::MachinePointerInfo::getWithOffset(), llvm::SelectionDAG::getZeroExtendInReg(), llvm::ConstantSDNode::getZExtValue(), llvm::SDValue::hasOneUse(), llvm::SDNode::hasOneUse(), i, llvm::MVT::i1, llvm::MVT::i32, llvm::TargetLoweringBase::isBigEndian(), llvm::EVT::isExtended(), llvm::ISD::isEXTLoad(), llvm::MemSDNode::isInvariant(), llvm::TargetLoweringBase::isLittleEndian(), llvm::TargetLoweringBase::isLoadExtLegal(), llvm::TargetLoweringBase::isNarrowingProfitable(), llvm::ISD::isNON_EXTLoad(), llvm::MemSDNode::isNonTemporal(), llvm::TargetLoweringBase::isOperationLegal(), llvm::EVT::isRound(), llvm::TargetLoweringBase::isTruncateFree(), llvm::TargetLowering::isTypeDesirableForOp(), llvm::isUIntN(), llvm::ISD::isUNINDEXEDLoad(), llvm::EVT::isVector(), llvm::MemSDNode::isVolatile(), llvm::TargetLoweringBase::isZExtFree(), llvm::ISD::isZEXTLoad(), llvm::SPII::Load, llvm::ISD::LOAD, llvm::SelectionDAG::MaskedValueIsZero(), llvm::MinAlign(), llvm::ISD::NON_EXTLOAD, llvm::A64CC::NV, llvm::ISD::OR, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ISD::SETCC, llvm::ISD::SETNE, llvm::ISD::SEXTLOAD, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::SmallVectorTemplateCommon< T >::size(), llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::TRUNCATE, llvm::ISD::UNDEF, llvm::MVT::Untyped, llvm::X, llvm::ISD::XOR, llvm::ISD::ZERO_EXTEND, llvm::APInt::zext(), and llvm::ISD::ZEXTLOAD.
static bool MatchRotateHalf (SDValue Op, SDValue & Shift, SDValue & Mask) static
MatchRotateHalf - Match "(X shl/srl V1) & V2" where V2 may not be present.
Definition at line 3287 of file DAGCombiner.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::ISD::BRCOND, C1, c2(), CC, llvm::SelectionDAG::ComputeMaskedBits(), llvm::ISD::Constant, llvm::APInt::countTrailingZeros(), llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::dyn_cast(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::APInt::getAllOnesValue(), llvm::ConstantSDNode::getAPIntValue(), llvm::TargetLoweringBase::getBooleanContents(), llvm::APInt::getBoolValue(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::APInt::getHighBitsSet(), llvm::EVT::getIntegerVT(), llvm::APInt::getLowBitsSet(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNOT(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarType(), llvm::SelectionDAG::getSelectCC(), llvm::SelectionDAG::getSetCC(), llvm::ISD::getSetCCInverse(), llvm::SDValue::getSimpleValueType(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::ConstantSDNode::getZExtValue(), llvm::SDValue::hasOneUse(), llvm::SDNode::hasOneUse(), llvm::MVT::i1, llvm::ConstantSDNode::isAllOnesValue(), llvm::ISD::isBuildVectorAllZeros(), llvm::TargetLoweringBase::isCondCodeLegal(), llvm::isInt(), llvm::EVT::isInteger(), llvm::APInt::isNegative(), llvm::ConstantSDNode::isNullValue(), isOneUseSetCC(), llvm::TargetLoweringBase::isOperationLegal(), llvm::TargetLoweringBase::isOperationLegalOrCustom(), isSetCCEquivalent(), llvm::TargetLoweringBase::isTruncateFree(), llvm::TargetLowering::isTypeDesirableForOp(), llvm::TargetLoweringBase::isTypeLegal(), llvm_unreachable, llvm::Log2_32(), llvm::APInt::lshr(), llvm::APIntOps::lshr(), llvm::SelectionDAG::MaskedValueIsZero(), llvm::ISD::OR, llvm::MVT::Other, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SELECT_CC, llvm::ISD::SETCC, Shift, llvm::ISD::SHL, llvm::APInt::shl(), llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::SelectionDAG::SignBitIsZero(), llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::SUB, llvm::ISD::SUBC, Sum, std::swap(), llvm::APInt::trunc(), llvm::ISD::TRUNCATE, tryFoldToZero(), llvm::ISD::UNDEF, llvm::SDNode::use_begin(), llvm::X, llvm::ISD::XOR, llvm::ISD::ZERO_EXTEND, and llvm::TargetLoweringBase::ZeroOrOneBooleanContent.
static SDValue partitionShuffleOfConcats (SDNode * N, SelectionDAG & DAG) static
Definition at line 9946 of file DAGCombiner.cpp.
References llvm::ISD::ADD, llvm::AfterLegalizeDAG, llvm::AfterLegalizeVectorOps, llvm::ISD::AND, llvm::ISD::BITCAST, llvm::EVT::bitsGE(), llvm::EVT::bitsGT(), llvm::EVT::bitsLT(), llvm::ISD::BUILD_VECTOR, llvm::TargetLowering::BuildSDIV(), llvm::TargetLowering::BuildUDIV(), CC, llvm::ISD::CONCAT_VECTORS, llvm::ISD::Constant, llvm::ISD::ConstantFP, llvm::APInt::countLeadingZeros(), llvm::APInt::countPopulation(), llvm::ISD::CTLZ, llvm::dyn_cast(), llvm::ISD::EXTLOAD, llvm::ISD::FABS, llvm::ISD::FDIV, llvm::ISD::FNEG, llvm::ArrayType::get(), llvm::ConstantArray::get(), llvm::MachinePointerInfo::getAddrSpace(), llvm::MemSDNode::getAlignment(), llvm::ConstantSDNode::getAPIntValue(), llvm::LoadSDNode::getBasePtr(), llvm::APInt::getBitWidth(), llvm::TargetLoweringBase::getBooleanContents(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::MachinePointerInfo::getConstantPool(), llvm::SelectionDAG::getConstantPool(), llvm::TargetLoweringBase::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::LoadSDNode::getExtensionType(), llvm::SelectionDAG::getExtLoad(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNOT(), llvm::SDValue::getNumOperands(), llvm::SDNode::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getOperationAction(), llvm::MemSDNode::getPointerInfo(), llvm::TargetLoweringBase::getPointerTy(), llvm::DataLayout::getPrefTypeAlignment(), llvm::SelectionDAG::getSelect(), llvm::SelectionDAG::getSetCC(), llvm::EVT::getSizeInBits(), llvm::ShuffleVectorSDNode::getSplatIndex(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::SelectionDAG::getZeroExtendInReg(), llvm::SDNode::hasAnyUseOfValue(), llvm::SDValue::hasOneUse(), i, I, llvm::MVT::i1, int, llvm::ConstantSDNode::isAllOnesValue(), llvm::EVT::isInteger(), llvm::MemSDNode::isInvariant(), llvm::MemSDNode::isNonTemporal(), llvm::ConstantSDNode::isNullValue(), llvm::ConstantSDNode::isOne(), llvm::TargetLoweringBase::isOperationLegal(), llvm::TargetLoweringBase::isOperationLegalOrCustom(), llvm::SDNode::isPredecessorOf(), llvm::ShuffleVectorSDNode::isSplat(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), llvm::TargetLoweringBase::isVectorClearMaskLegal(), llvm::MemSDNode::isVolatile(), llvm::TargetLoweringBase::Legal, llvm::SPII::Load, llvm::ISD::LOAD, llvm::Log2_32(), N, llvm::ISD::NON_EXTLOAD, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), S, llvm::ISD::SDIV, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, Shift, llvm::ISD::SHL, llvm::TargetLowering::SimplifySetCC(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::SUB, llvm::ISD::TRUNCATE, llvm::ISD::UDIV, llvm::ISD::UNDEF, llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::XOR, llvm::ISD::ZERO_EXTEND, and llvm::TargetLoweringBase::ZeroOrOneBooleanContent.
static SDNode* ShrinkLoadReplaceStoreWithStore (const std::pair< unsigned, unsigned > & MaskInfo, SDValue IVal, StoreSDNode * St, DAGCombiner * DC) static
ShrinkLoadReplaceStoreWithStore - Check to see if IVal is something that provides a value as specified by MaskInfo. If so, replace the specified store with a narrower store of truncated IVal.
Definition at line 8211 of file DAGCombiner.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, CheckForMaskedLoad(), llvm::ISD::Constant, llvm::APInt::countLeadingZeros(), llvm::APInt::countTrailingZeros(), llvm::DataLayout::getABITypeAlignment(), llvm::MachinePointerInfo::getAddrSpace(), llvm::MemSDNode::getAlignment(), llvm::APInt::getAllOnesValue(), llvm::LoadSDNode::getBasePtr(), llvm::StoreSDNode::getBasePtr(), llvm::APInt::getBitsSet(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::TargetLoweringBase::getDataLayout(), llvm::MVT::getIntegerVT(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getLoad(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::MemSDNode::getPointerInfo(), llvm::SelectionDAG::getStore(), llvm::EVT::getStoreSize(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::MemSDNode::getTBAAInfo(), llvm::EVT::getTypeForEVT(), llvm::SDValue::getValue(), llvm::StoreSDNode::getValue(), llvm::SDValue::getValueSizeInBits(), llvm::SDValue::getValueType(), llvm::MachinePointerInfo::getWithOffset(), llvm::SDValue::hasOneUse(), llvm::APInt::isAllOnesValue(), llvm::TargetLoweringBase::isBigEndian(), llvm::TargetLowering::isDesirableToTransformToIntegerOp(), llvm::MemSDNode::isInvariant(), llvm::TargetLoweringBase::isLittleEndian(), llvm::TargetLoweringBase::isNarrowingProfitable(), llvm::MemSDNode::isNonTemporal(), llvm::ISD::isNormalLoad(), llvm::ISD::isNormalStore(), llvm::TargetLoweringBase::isOperationLegal(), llvm::TargetLoweringBase::isOperationLegalOrCustom(), llvm::StoreSDNode::isTruncatingStore(), llvm::EVT::isVector(), llvm::MemSDNode::isVolatile(), llvm::A64DB::LD, llvm::ISD::LOAD, llvm::APIntOps::lshr(), llvm::SelectionDAG::MaskedValueIsZero(), llvm::MinAlign(), N, llvm::NextPowerOf2(), llvm::ISD::OR, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ISD::SRL, llvm::A64DB::ST, llvm::ISD::STORE, llvm::APInt::trunc(), llvm::ISD::TRUNCATE, and llvm::ISD::XOR.
static std::pair<SDValue, SDValue> SplitVSETCC (const SDNode * N, SelectionDAG & DAG) static
Definition at line 4275 of file DAGCombiner.cpp.
References llvm::ISD::ADD, CC, llvm::ISD::CONCAT_VECTORS, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::GetSplitDestVTs(), llvm::TargetLoweringBase::getTypeAction(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::HexagonISD::Hi, llvm::ISD::isBuildVectorAllOnes(), llvm::ISD::isBuildVectorAllZeros(), llvm::HexagonISD::Lo, llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, Shift, llvm::SelectionDAG::SplitVectorOperand(), llvm::ISD::SRA, llvm::ISD::SUB, llvm::tie(), llvm::TargetLoweringBase::TypeSplitVector, and llvm::ISD::XOR.
STATISTIC (NodesCombined , "Number of dag nodes combined")
STATISTIC (PreIndexedNodes , "Number of pre-indexed nodes created")
STATISTIC (PostIndexedNodes , "Number of post-indexed nodes created")
STATISTIC (OpsNarrowed , "Number of load/op/store narrowed")
STATISTIC (LdStFP2Int , "Number of fp load/store pairs transformed to int")
STATISTIC (SlicedLoads , "Number of load sliced")
static SDValue tryFoldToZero (SDLoc DL, const TargetLowering & TLI, EVT VT, SelectionDAG & DAG, bool LegalOperations, bool LegalTypes) static
Definition at line 1633 of file DAGCombiner.cpp.
References llvm::ISD::ADD, llvm::ISD::BUILD_VECTOR, llvm::ISD::CARRY_FALSE, llvm::dyn_cast(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::ConstantSDNode::getAPIntValue(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getGlobalAddress(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getVTList(), llvm::ISD::GlobalAddress, llvm::MVT::Glue, llvm::SDNode::hasAnyUseOfValue(), llvm::ConstantSDNode::isAllOnesValue(), llvm::ISD::isBuildVectorAllZeros(), llvm::TargetLowering::isOffsetFoldingLegal(), llvm::TargetLoweringBase::isOperationLegal(), llvm::EVT::isVector(), llvm::ISD::SUB, llvm::ISD::SUBC, llvm::ISD::UNDEF, and llvm::ISD::XOR.
Referenced by MatchRotateHalf().