LLVM: DataLayout.cpp File Reference
LLVM API Documentation
DataLayout.cpp File Reference
#include "llvm/IR/DataLayout.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/GetElementPtrTypeIterator.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/Mutex.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cstdlib>
Functions
static std::pair< StringRef, StringRef > split (StringRef Str, char Separator)
Checked version of split, to ensure mandatory subparts.
static unsigned getInt (StringRef R)
Get an unsinged integer, including error checks.
static unsigned inBytes (unsigned Bits)
Convert bits into bytes. Assert if not a byte width multiple.
Function Documentation
static unsigned getInt (StringRef R) static
Get an unsinged integer, including error checks.
Definition at line 189 of file DataLayout.cpp.
References llvm::StringRef::getAsInteger().
Referenced by llvm::object::ELFFile< ELFT >::Elf_Sym_Iter::getEntSize(), and inBytes().
static unsigned inBytes (unsigned Bits) static
Convert bits into bytes. Assert if not a byte width multiple.
Definition at line 197 of file DataLayout.cpp.
References llvm::AGGREGATE_ALIGN, llvm::StringRef::empty(), llvm::FLOAT_ALIGN, llvm::StringRef::front(), getInt(), llvm::INTEGER_ALIGN, llvm_unreachable, Split(), split(), llvm::STACK_ALIGN, llvm::StringRef::substr(), and llvm::VECTOR_ALIGN.
static std::pair<StringRef, StringRef> split (StringRef Str, char Separator) static
Checked version of split, to ensure mandatory subparts.
Definition at line 180 of file DataLayout.cpp.
References llvm::StringRef::empty(), Split(), and llvm::StringRef::split().
Referenced by inBytes().