LLVM: DCE.cpp File Reference
LLVM API Documentation
DCE.cpp File Reference
#include "llvm/Transforms/Scalar.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/IR/Instruction.h"
#include "llvm/Pass.h"
#include "llvm/Support/InstIterator.h"
#include "llvm/Target/TargetLibraryInfo.h"
#include "llvm/Transforms/Utils/Local.h"
Macros
#define DEBUG_TYPE "dce"
Functions
STATISTIC (DIEEliminated,"Number of insts removed by DIE pass")
STATISTIC (DCEEliminated,"Number of insts removed")
INITIALIZE_PASS (DeadInstElimination,"die","Dead Instruction Elimination", false, false) Pass *llvm
Macro Definition Documentation
#define DEBUG_TYPE "dce"
Definition at line 19 of file DCE.cpp.
Function Documentation
INITIALIZE_PASS (DeadInstElimination , "die" , "Dead Instruction Elimination" , false , false)
Definition at line 62 of file DCE.cpp.
References llvm::Instruction::eraseFromParent(), F(), llvm::PassRegistry::getPassRegistry(), i, I, llvm::initializeDCEPass(), llvm::inst_begin(), llvm::inst_end(), llvm::isInstructionTriviallyDead(), llvm::User::op_begin(), llvm::User::op_end(), llvm::LibFunc::remove, and llvm::AnalysisUsage::setPreservesCFG().
STATISTIC (DIEEliminated , "Number of insts removed by DIE pass")
STATISTIC (DCEEliminated , "Number of insts removed")