LLVM: DeadMachineInstructionElim.cpp File Reference
LLVM API Documentation
DeadMachineInstructionElim.cpp File Reference
#include "llvm/CodeGen/Passes.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetMachine.h"
Macros
#define DEBUG_TYPE "codegen-dce"
Functions
STATISTIC (NumDeletes,"Number of dead instructions deleted")
INITIALIZE_PASS (DeadMachineInstructionElim,"dead-mi-elimination","Remove dead machine instructions", false, false) bool DeadMachineInstructionElim
Macro Definition Documentation
#define DEBUG_TYPE "codegen-dce"
Definition at line 14 of file DeadMachineInstructionElim.cpp.
Function Documentation
INITIALIZE_PASS (DeadMachineInstructionElim , "dead-mi-elimination" , "Remove dead machine instructions" , false , false)
Definition at line 50 of file DeadMachineInstructionElim.cpp.
References llvm::dbgs(), DEBUG, llvm::MachineInstr::eraseFromParent(), llvm::TargetMachine::getInstrInfo(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::TargetMachine::getRegisterInfo(), llvm::MachineOperand::getRegMask(), llvm::MachineFunction::getTarget(), i, I, llvm::MachineOperand::isDebug(), llvm::MachineOperand::isDef(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRegMask(), llvm::MachineOperand::isUse(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::MCRegAliasIterator::isValid(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::A64CC::MI, MII, MRI, llvm::next(), llvm::MachineBasicBlock::rbegin(), llvm::MachineFunction::rbegin(), llvm::MachineBasicBlock::rend(), llvm::MachineFunction::rend(), S, llvm::MachineOperand::setReg(), llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_end(), and TII.
STATISTIC (NumDeletes , "Number of dead instructions deleted")