LLVM: DeadArgumentElimination.cpp File Reference
LLVM API Documentation
DeadArgumentElimination.cpp File Reference
#include "llvm/Transforms/IPO.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/DIBuilder.h"
#include "llvm/DebugInfo.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include "llvm/Support/CallSite.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <map>
#include <set>
Macros
#define DEBUG_TYPE "deadargelim"
Functions
STATISTIC (NumArgumentsEliminated,"Number of unread args removed")
STATISTIC (NumRetValsEliminated,"Number of unused return values removed")
STATISTIC (NumArgumentsReplacedWithUndef,"Number of unread args replaced with undef")
INITIALIZE_PASS (DAH,"deadarghaX0r","Dead Argument Hacking (BUGPOINT USE ONLY; DO NOT USE)", false, false) ModulePass *llvm
static unsigned NumRetVals (const Function *F)
Macro Definition Documentation
#define DEBUG_TYPE "deadargelim"
Definition at line 20 of file DeadArgumentElimination.cpp.
Function Documentation
INITIALIZE_PASS (DAH , "deadarghaX0r" , "Dead Argument Hacking (BUGPOINT USE ONLY; DO NOT USE)" , false , false)
createDeadArgEliminationPass - This pass removes arguments from functions which are not used by the body of the function.
Definition at line 186 of file DeadArgumentElimination.cpp.
static unsigned NumRetVals (const Function * F) static
Convenience function that returns the number of return values. It returns 0 for void functions and 1 for functions not returning a struct. It returns the number of struct elements for functions returning a struct.
Definition at line 413 of file DeadArgumentElimination.cpp.
References llvm::Function::arg_begin(), llvm::Function::arg_end(), llvm::Function::arg_size(), B, BB, llvm::Function::begin(), llvm::Module::begin(), llvm::Call, llvm::SmallVectorImpl< T >::clear(), llvm::AttrBuilder::contains(), llvm::Function::copyAttributesFrom(), llvm::Function::Create(), llvm::CallInst::Create(), llvm::ExtractValueInst::Create(), llvm::InsertValueInst::Create(), llvm::ReturnInst::Create(), llvm::InvokeInst::Create(), llvm::dbgs(), DEBUG, llvm::dyn_cast(), llvm::Function::end(), llvm::Module::end(), llvm::Function::eraseFromParent(), llvm::MipsISD::Ext, llvm::FunctionType::get(), llvm::StructType::get(), llvm::UndefValue::get(), llvm::InsertValueInst::getAggregateOperandIndex(), llvm::Function::getAttributes(), llvm::Function::getBasicBlockList(), llvm::Type::getContext(), llvm::Function::getContext(), llvm::StructType::getElementType(), llvm::AttributeSet::getFnAttributes(), llvm::Module::getFunctionList(), llvm::Function::getFunctionType(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getInstruction(), llvm::GlobalValue::getLinkage(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::FunctionType::getNumParams(), llvm::value_use_iterator< UserTy >::getOperandNo(), llvm::GlobalValue::getParent(), llvm::AttributeSet::getRetAttributes(), llvm::FunctionType::getReturnType(), llvm::Function::getReturnType(), llvm::Type::getVoidTy(), llvm::AttributeSet::hasAttributes(), llvm::ExtractValueInst::hasIndices(), llvm::GlobalValue::hasLocalLinkage(), i, I, llvm::ExtractValueInst::idx_begin(), llvm::iplist< NodeTy, Traits >::insert(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isCallee(), llvm::Function::isIntrinsic(), llvm::StructType::isPacked(), llvm::FunctionType::isVarArg(), llvm::Type::isVoidTy(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::AttrBuilder::removeAttribute(), llvm::AArch64ISD::Ret, llvm::Attribute::Returned, llvm::Function::setAttributes(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::iplist< NodeTy, Traits >::splice(), llvm::Value::takeName(), llvm::AttributeFuncs::typeIncompatible(), llvm::Value::use_back(), llvm::Value::use_begin(), llvm::Value::use_empty(), and llvm::Value::use_end().
STATISTIC (NumArgumentsEliminated , "Number of unread args removed")
STATISTIC (NumRetValsEliminated , "Number of unused return values removed")
STATISTIC (NumArgumentsReplacedWithUndef , "Number of unread args replaced with undef")