LLVM: Debug.cpp File Reference
LLVM API Documentation
Debug.cpp File Reference
#include "llvm/Support/Debug.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Signals.h"
#include "llvm/Support/circular_raw_ostream.h"
Functions
static void debug_user_sig_handler (void *Cookie)
Variables
static cl::opt< bool, true > Debug ("debug", cl::desc("Enable debug output"), cl::Hidden, cl::location(DebugFlag))
static cl::opt< unsigned > DebugBufferSize ("debug-buffer-size", cl::desc("Buffer the last N characters of debug output ""until program termination. ""[default 0 -- immediate print-out]"), cl::Hidden, cl::init(0))
static std::string CurrentDebugType
static DebugOnlyOpt DebugOnlyOptLoc
static cl::opt< DebugOnlyOpt, true, cl::parser< std::string > > DebugOnly ("debug-only", cl::desc("Enable a specific type of debug output"), cl::Hidden, cl::value_desc("debug string"), cl::location(DebugOnlyOptLoc), cl::ValueRequired)
Function Documentation
static void debug_user_sig_handler (void * Cookie) static
Definition at line 74 of file Debug.cpp.
References llvm::dbgs(), and llvm::circular_raw_ostream::flushBufferWithBanner().
Referenced by llvm::dbgs().
Variable Documentation
std::string CurrentDebugType static
Definition at line 53 of file Debug.cpp.
Referenced by llvm::isCurrentDebugType().
cl::opt<bool, true> Debug("debug", cl::desc("Enable debug output"), cl::Hidden, cl::location(DebugFlag)) static
Referenced by llvm::MCStreamer::EmitCFISections(), llvm::MCStreamer::EmitDwarfAdvanceFrameAddr(), isUsedIn(), and PrintQuotedString().
cl::opt<unsigned> DebugBufferSize("debug-buffer-size", cl::desc("Buffer the last N characters of debug output ""until program termination. ""[default 0 -- immediate print-out]"), cl::Hidden, cl::init(0)) static
Referenced by llvm::dbgs().
cl::opt<DebugOnlyOpt, true, cl::parser<std::string> > DebugOnly("debug-only", cl::desc("Enable a specific type of debug output"), cl::Hidden, cl::value_desc("debug string"), cl::location(DebugOnlyOptLoc), cl::ValueRequired) static
DebugOnlyOpt DebugOnlyOptLoc static
Definition at line 66 of file Debug.cpp.