LLVM: DependenceAnalysis.cpp File Reference
LLVM API Documentation
DependenceAnalysis.cpp File Reference
#include "llvm/Analysis/DependenceAnalysis.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/Operator.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/InstIterator.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "da"
Functions
STATISTIC (TotalArrayPairs,"Array pairs tested")
STATISTIC (SeparableSubscriptPairs,"Separable subscript pairs")
STATISTIC (CoupledSubscriptPairs,"Coupled subscript pairs")
STATISTIC (NonlinearSubscriptPairs,"Nonlinear subscript pairs")
STATISTIC (ZIVapplications,"ZIV applications")
STATISTIC (ZIVindependence,"ZIV independence")
STATISTIC (StrongSIVapplications,"Strong SIV applications")
STATISTIC (StrongSIVsuccesses,"Strong SIV successes")
STATISTIC (StrongSIVindependence,"Strong SIV independence")
STATISTIC (WeakCrossingSIVapplications,"Weak-Crossing SIV applications")
STATISTIC (WeakCrossingSIVsuccesses,"Weak-Crossing SIV successes")
STATISTIC (WeakCrossingSIVindependence,"Weak-Crossing SIV independence")
STATISTIC (ExactSIVapplications,"Exact SIV applications")
STATISTIC (ExactSIVsuccesses,"Exact SIV successes")
STATISTIC (ExactSIVindependence,"Exact SIV independence")
STATISTIC (WeakZeroSIVapplications,"Weak-Zero SIV applications")
STATISTIC (WeakZeroSIVsuccesses,"Weak-Zero SIV successes")
STATISTIC (WeakZeroSIVindependence,"Weak-Zero SIV independence")
STATISTIC (ExactRDIVapplications,"Exact RDIV applications")
STATISTIC (ExactRDIVindependence,"Exact RDIV independence")
STATISTIC (SymbolicRDIVapplications,"Symbolic RDIV applications")
STATISTIC (SymbolicRDIVindependence,"Symbolic RDIV independence")
STATISTIC (DeltaApplications,"Delta applications")
STATISTIC (DeltaSuccesses,"Delta successes")
STATISTIC (DeltaIndependence,"Delta independence")
STATISTIC (DeltaPropagations,"Delta propagations")
STATISTIC (GCDapplications,"GCD applications")
STATISTIC (GCDsuccesses,"GCD successes")
STATISTIC (GCDindependence,"GCD independence")
STATISTIC (BanerjeeApplications,"Banerjee applications")
STATISTIC (BanerjeeIndependence,"Banerjee independence")
STATISTIC (BanerjeeSuccesses,"Banerjee successes")
INITIALIZE_PASS_BEGIN (DependenceAnalysis,"da","Dependence Analysis", true, true) INITIALIZE_PASS_END(DependenceAnalysis
static void dumpExampleDependence (raw_ostream &OS, Function *F, DependenceAnalysis *DA)
static AliasAnalysis::AliasResult underlyingObjectsAlias (AliasAnalysis *AA, const Value *A, const Value *B)
static bool isLoadOrStore (const Instruction *I)
static Value * getPointerOperand (Instruction *I)
static bool findGCD (unsigned Bits, APInt AM, APInt BM, APInt Delta, APInt &G, APInt &X, APInt &Y)
static APInt floorOfQuotient (APInt A, APInt B)
static APInt ceilingOfQuotient (APInt A, APInt B)
static APInt maxAPInt (APInt A, APInt B)
static APInt minAPInt (APInt A, APInt B)
static bool isRemainderZero (const SCEVConstant *Dividend, const SCEVConstant *Divisor)
static const SCEVConstant * getConstantPart (const SCEVMulExpr *Product)
static void dumpSmallBitVector (SmallBitVector &BV)
Variables
static cl::opt< bool > Delinearize ("da-delinearize", cl::init(false), cl::Hidden, cl::ZeroOrMore, cl::desc("Try to delinearize array references."))
da
Dependence Analysis
Dependence true
Macro Definition Documentation
#define DEBUG_TYPE "da"
Definition at line 54 of file DependenceAnalysis.cpp.
Function Documentation
static APInt ceilingOfQuotient (APInt A, APInt B) static
Definition at line 1328 of file DependenceAnalysis.cpp.
References llvm::ARM_PROC::A, llvm::APInt::sdivrem(), llvm::APInt::sgt(), and llvm::APInt::slt().
Referenced by isRemainderZero(), and minAPInt().
static void dumpExampleDependence (raw_ostream & OS, Function * F, DependenceAnalysis * DA) static
Definition at line 157 of file DependenceAnalysis.cpp.
References llvm::DependenceAnalysis::depends(), llvm::DependenceAnalysis::getSplitIteration(), llvm::inst_begin(), and llvm::inst_end().
Referenced by llvm::DependenceAnalysis::print().
static void dumpSmallBitVector (SmallBitVector & BV) static
Definition at line 3233 of file DependenceAnalysis.cpp.
References llvm::dbgs(), llvm::SmallBitVector::find_first(), and llvm::SmallBitVector::find_next().
Referenced by llvm::DependenceAnalysis::depends().
static bool findGCD (unsigned Bits, APInt AM, APInt BM, APInt Delta, APInt & G, APInt & X, APInt & Y) static
Definition at line 1281 of file DependenceAnalysis.cpp.
References llvm::APInt::abs(), llvm::dbgs(), DEBUG, llvm::APInt::sdiv(), llvm::APInt::sdivrem(), llvm::APInt::slt(), and llvm::APInt::srem().
Referenced by llvm::SCEVAddRecExpr::delinearize(), isRemainderZero(), minAPInt(), and sdiv().
static APInt floorOfQuotient (APInt A, APInt B) static
Definition at line 1313 of file DependenceAnalysis.cpp.
References llvm::ARM_PROC::A, llvm::APInt::sdivrem(), llvm::APInt::sgt(), and llvm::APInt::slt().
Referenced by isRemainderZero(), and minAPInt().
static const SCEVConstant* getConstantPart (const SCEVMulExpr * Product) static
Definition at line 2192 of file DependenceAnalysis.cpp.
References llvm::ARM_PROC::A, llvm::APInt::abs(), llvm::Dependence::DVEntry::ALL, B, llvm::ISD::Constant, llvm::dbgs(), DEBUG, llvm::SCEVAddRecExpr::delinearize(), llvm::Dependence::DVEntry::Direction, llvm::Dependence::DVEntry::Distance, llvm::Dependence::dump(), llvm::dyn_cast(), llvm::Dependence::DVEntry::EQ, llvm::errs(), llvm::SmallBitVector::find_first(), llvm::SmallBitVector::find_next(), llvm::SCEV::FlagAnyWrap, llvm::SCEVAddRecExpr::getLoop(), llvm::SCEVNAryExpr::getNoWrapFlags(), llvm::APInt::getNullValue(), llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVNAryExpr::getOperand(), llvm::SCEVAddRecExpr::getStart(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::SCEV::getType(), llvm::SCEVConstant::getValue(), llvm::ConstantInt::getValue(), llvm::APIntOps::GreatestCommonDivisor(), llvm::Dependence::DVEntry::GT, i, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::SCEVAddRecExpr::isAffine(), llvm::SCEV::isZero(), isZero(), llvm_unreachable, llvm::Dependence::DVEntry::LT, llvm::Dependence::DVEntry::NONE, llvm::SmallVectorImpl< T >::resize(), llvm::Dependence::DVEntry::Scalar, llvm::APInt::sdiv(), llvm::SmallVectorTemplateCommon< T >::size(), size, llvm::APInt::srem(), and Sum.
static Value* getPointerOperand (Instruction * I) static
Definition at line 655 of file DependenceAnalysis.cpp.
References llvm::SmallBitVector::count(), llvm::dbgs(), DEBUG, llvm::Dependence::DVEntry::Direction, llvm::Dependence::DVEntry::Distance, llvm::dyn_cast(), llvm::Dependence::DVEntry::EQ, llvm::APInt::getBitWidth(), llvm::SCEVAddRecExpr::getLoop(), llvm::LoopBase< BlockT, LoopT >::getLoopDepth(), llvm::SCEVCastExpr::getOperand(), llvm::Instruction::getParent(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::SCEVAddRecExpr::getStart(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::SCEVCastExpr::getType(), llvm::SCEV::getType(), llvm::SCEVConstant::getValue(), llvm::ConstantInt::getValue(), llvm::Dependence::DVEntry::GT, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, if(), isLoopInvariant(), llvm::SCEV::isOne(), llvm::SCEV::isZero(), llvm_unreachable, Loops, llvm::Dependence::DVEntry::LT, N, llvm::Dependence::DVEntry::NONE, llvm::APInt::sdivrem(), llvm::SmallBitVector::set(), llvm::APInt::sgt(), llvm::APInt::slt(), llvm::Dependence::DVEntry::Splitable, llvm::APInt::srem(), llvm::X, and Y.
Referenced by llvm::DependenceAnalysis::depends(), and llvm::DependenceAnalysis::getSplitIteration().
INITIALIZE_PASS_BEGIN (DependenceAnalysis , "da" , "Dependence Analysis" , true , true)
static bool isLoadOrStore (const Instruction * I) static
Definition at line 645 of file DependenceAnalysis.cpp.
Referenced by llvm::DependenceAnalysis::depends(), and llvm::DependenceAnalysis::getSplitIteration().
static bool isRemainderZero (const SCEVConstant * Dividend, const SCEVConstant * Divisor) static
Definition at line 1542 of file DependenceAnalysis.cpp.
References llvm::tgtok::Bits, C1, ceilingOfQuotient(), llvm::dbgs(), DEBUG, llvm::Dependence::DVEntry::Direction, llvm::dyn_cast(), findGCD(), floorOfQuotient(), G, llvm::Dependence::DVEntry::GE, llvm::APInt::getBitWidth(), llvm::SCEVAddRecExpr::getLoop(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::SCEVAddRecExpr::getStart(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::SCEV::getType(), llvm::SCEVConstant::getValue(), llvm::ConstantInt::getValue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::Dependence::DVEntry::LE, llvm_unreachable, maxAPInt(), minAPInt(), llvm::Dependence::DVEntry::PeelFirst, llvm::Dependence::DVEntry::PeelLast, llvm::APInt::sdiv(), llvm::APInt::sgt(), llvm::APInt::srem(), llvm::X, and Y.
static APInt maxAPInt (APInt A, APInt B) static
Definition at line 1343 of file DependenceAnalysis.cpp.
References B, and llvm::APInt::sgt().
Referenced by isRemainderZero(), and minAPInt().
static APInt minAPInt (APInt A, APInt B) static
Definition at line 1349 of file DependenceAnalysis.cpp.
References B, llvm::tgtok::Bits, ceilingOfQuotient(), llvm::dbgs(), DEBUG, llvm::Dependence::DVEntry::Direction, llvm::dyn_cast(), llvm::Dependence::DVEntry::EQ, findGCD(), floorOfQuotient(), G, llvm::APInt::getBitWidth(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::SCEV::getType(), llvm::SCEVConstant::getValue(), llvm::ConstantInt::getValue(), llvm::Dependence::DVEntry::GT, llvm::Dependence::DVEntry::LT, maxAPInt(), llvm::Dependence::DVEntry::NONE, llvm::APInt::sdiv(), llvm::APInt::sgt(), llvm::APInt::sle(), llvm::APInt::slt(), llvm::X, and Y.
Referenced by isRemainderZero().
STATISTIC (TotalArrayPairs , "Array pairs tested")
STATISTIC (SeparableSubscriptPairs , "Separable subscript pairs")
STATISTIC (CoupledSubscriptPairs , "Coupled subscript pairs")
STATISTIC (NonlinearSubscriptPairs , "Nonlinear subscript pairs")
STATISTIC (ZIVapplications , "ZIV applications")
STATISTIC (ZIVindependence , "ZIV independence")
STATISTIC (StrongSIVapplications , "Strong SIV applications")
STATISTIC (StrongSIVsuccesses , "Strong SIV successes")
STATISTIC (StrongSIVindependence , "Strong SIV independence")
STATISTIC (WeakCrossingSIVapplications , "Weak-Crossing SIV applications")
STATISTIC (WeakCrossingSIVsuccesses , "Weak-Crossing SIV successes")
STATISTIC (WeakCrossingSIVindependence , "Weak-Crossing SIV independence")
STATISTIC (ExactSIVapplications , "Exact SIV applications")
STATISTIC (ExactSIVsuccesses , "Exact SIV successes")
STATISTIC (ExactSIVindependence , "Exact SIV independence")
STATISTIC (WeakZeroSIVapplications , "Weak-Zero SIV applications")
STATISTIC (WeakZeroSIVsuccesses , "Weak-Zero SIV successes")
STATISTIC (WeakZeroSIVindependence , "Weak-Zero SIV independence")
STATISTIC (ExactRDIVapplications , "Exact RDIV applications")
STATISTIC (ExactRDIVindependence , "Exact RDIV independence")
STATISTIC (SymbolicRDIVapplications , "Symbolic RDIV applications")
STATISTIC (SymbolicRDIVindependence , "Symbolic RDIV independence")
STATISTIC (DeltaApplications , "Delta applications")
STATISTIC (DeltaSuccesses , "Delta successes")
STATISTIC (DeltaIndependence , "Delta independence")
STATISTIC (DeltaPropagations , "Delta propagations")
STATISTIC (GCDapplications , "GCD applications")
STATISTIC (GCDsuccesses , "GCD successes")
STATISTIC (GCDindependence , "GCD independence")
STATISTIC (BanerjeeApplications , "Banerjee applications")
STATISTIC (BanerjeeIndependence , "Banerjee independence")
STATISTIC (BanerjeeSuccesses , "Banerjee successes")
static AliasAnalysis::AliasResult underlyingObjectsAlias (AliasAnalysis * AA, const Value * A, const Value * B) static
Definition at line 632 of file DependenceAnalysis.cpp.
References llvm::AliasAnalysis::alias(), llvm::Value::getType(), llvm::AliasAnalysis::getTypeStoreSize(), and llvm::GetUnderlyingObject().
Referenced by llvm::DependenceAnalysis::depends(), and llvm::DependenceAnalysis::getSplitIteration().
Variable Documentation
Dependence Analysis
Definition at line 120 of file DependenceAnalysis.cpp.
da
Definition at line 120 of file DependenceAnalysis.cpp.
cl::opt<bool> Delinearize("da-delinearize", cl::init(false), cl::Hidden, cl::ZeroOrMore, cl::desc("Try to delinearize array references.")) static
Referenced by llvm::DependenceAnalysis::depends(), and llvm::DependenceAnalysis::getSplitIteration().
Dependence true
Definition at line 120 of file DependenceAnalysis.cpp.