LLVM: DIBuilder.cpp File Reference
LLVM API Documentation
DIBuilder.cpp File Reference
#include "llvm/DIBuilder.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/DebugInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Dwarf.h"
Functions
static Constant * GetTagConstant (LLVMContext &VMContext, unsigned Tag)
static MDNode * getNonCompileUnitScope (MDNode *N)
static MDNode * createFilePathPair (LLVMContext &VMContext, StringRef Filename, StringRef Directory)
static DIImportedEntity createImportedModule (LLVMContext &C, DIScope Context, DIDescriptor NS, unsigned Line, StringRef Name, SmallVectorImpl< Value * > &AllImportedModules)
Function Documentation
static MDNode* createFilePathPair (LLVMContext & VMContext, StringRef Filename, StringRef Directory) static
Definition at line 84 of file DIBuilder.cpp.
References llvm::StringRef::empty(), llvm::MDString::get(), and llvm::MDNode::get().
Referenced by llvm::DIBuilder::createCompileUnit(), and llvm::DIBuilder::createFile().
static DIImportedEntity createImportedModule (LLVMContext & C, DIScope Context, DIDescriptor NS, unsigned Line, StringRef Name, SmallVectorImpl< Value * > & AllImportedModules) static
Definition at line 143 of file DIBuilder.cpp.
References llvm::StringRef::empty(), llvm::MDString::get(), llvm::ConstantInt::get(), llvm::MDNode::get(), llvm::Type::getInt32Ty(), GetTagConstant(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), and llvm::DIImportedEntity::Verify().
Referenced by llvm::DIBuilder::createImportedModule().
static MDNode* getNonCompileUnitScope (MDNode * N) static
getNonCompileUnitScope - If N is compile unit return NULL otherwise return N.
Definition at line 78 of file DIBuilder.cpp.
References N.
Referenced by llvm::DIBuilder::createClassType(), llvm::DIBuilder::createComplexVariable(), llvm::DIBuilder::createEnumerationType(), llvm::DIBuilder::createForwardDecl(), llvm::DIBuilder::createFunction(), llvm::DIBuilder::createLexicalBlock(), llvm::DIBuilder::createLocalVariable(), llvm::DIBuilder::createMemberType(), llvm::DIBuilder::createMethod(), llvm::DIBuilder::createNameSpace(), llvm::DIBuilder::createObjCIVar(), llvm::DIBuilder::createStaticMemberType(), llvm::DIBuilder::createStaticVariable(), llvm::DIBuilder::createStructType(), llvm::DIBuilder::createTemplateTypeParameter(), llvm::DIBuilder::createTypedef(), and llvm::DIBuilder::createUnionType().
static Constant* GetTagConstant (LLVMContext & VMContext, unsigned Tag) static
Definition at line 26 of file DIBuilder.cpp.
References llvm::ConstantInt::get(), and llvm::Type::getInt32Ty().
Referenced by llvm::DIBuilder::createArrayType(), llvm::DIBuilder::createBasicType(), llvm::DIBuilder::createClassType(), llvm::DIBuilder::createCompileUnit(), llvm::DIBuilder::createComplexVariable(), llvm::DIBuilder::createEnumerationType(), llvm::DIBuilder::createEnumerator(), llvm::DIBuilder::createFile(), llvm::DIBuilder::createForwardDecl(), llvm::DIBuilder::createFriend(), llvm::DIBuilder::createFunction(), llvm::DIBuilder::createGlobalVariable(), llvm::DIBuilder::createImportedDeclaration(), createImportedModule(), llvm::DIBuilder::createInheritance(), llvm::DIBuilder::createLexicalBlock(), llvm::DIBuilder::createLexicalBlockFile(), llvm::DIBuilder::createLocalVariable(), llvm::DIBuilder::createMemberPointerType(), llvm::DIBuilder::createMemberType(), llvm::DIBuilder::createMethod(), llvm::DIBuilder::createNameSpace(), llvm::DIBuilder::createObjCIVar(), llvm::DIBuilder::createObjCProperty(), llvm::DIBuilder::createPointerType(), llvm::DIBuilder::createQualifiedType(), llvm::DIBuilder::createReferenceType(), llvm::DIBuilder::createStaticMemberType(), llvm::DIBuilder::createStaticVariable(), llvm::DIBuilder::createStructType(), llvm::DIBuilder::createSubroutineType(), llvm::DIBuilder::createTemplateTypeParameter(), llvm::DIBuilder::createTypedef(), llvm::DIBuilder::createUnionType(), llvm::DIBuilder::createUnspecifiedParameter(), llvm::DIBuilder::createUnspecifiedType(), llvm::DIBuilder::createVectorType(), and llvm::DIBuilder::getOrCreateSubrange().