LLVM: DIEHash.cpp File Reference
LLVM API Documentation
DIEHash.cpp File Reference
#include "DIEHash.h"
#include "DIE.h"
#include "DwarfCompileUnit.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Dwarf.h"
#include "llvm/Support/Endian.h"
#include "llvm/Support/MD5.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "dwarfdebug"
#define COLLECT_ATTR(NAME)
#define ADD_ATTR(ATTR)
Functions
static StringRef getDIEStringAttr (const DIE &Die, uint16_t Attr)
Grabs the string in whichever attribute is passed in and returns a reference to it.
Macro Definition Documentation
#define ADD_ATTR (ATTR)
Value:
{                                                                            \
    if (ATTR.Val != 0)                                                         \
      hashAttribute(ATTR, Tag);                                                \
  }
Referenced by getDIEStringAttr().
#define COLLECT_ATTR (NAME)
Value:
case dwarf::NAME:                                                            \
    Attrs.NAME.Val = Values[i];                                                \
    Attrs.NAME.Desc = &Abbrevs.getData()[i];                                   \
    break
Referenced by getDIEStringAttr().
#define DEBUG_TYPE "dwarfdebug"
Definition at line 14 of file DIEHash.cpp.
Function Documentation
static StringRef getDIEStringAttr (const DIE & Die, uint16_t Attr) static
Grabs the string in whichever attribute is passed in and returns a reference to it.
Definition at line 32 of file DIEHash.cpp.
References ADD_ATTR, llvm::dwarf::AttributeString(), COLLECT_ATTR, llvm::dbgs(), DEBUG, llvm::StringRef::empty(), llvm::DIE::getAbbrev(), llvm::DIEAbbrevData::getAttribute(), llvm::DIE::getChildren(), llvm::DIEAbbrev::getData(), llvm::DIEAbbrevData::getForm(), llvm::DIE::getParent(), llvm::DIEString::getString(), llvm::DIE::getTag(), llvm::DIE::getValues(), i, I, llvm::dwarf::isType(), llvm_unreachable, llvm::makeArrayRef(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateCommon< T >::rbegin(), llvm::SmallVectorTemplateCommon< T >::rend(), S, llvm::SmallVectorTemplateCommon< T >::size(), and llvm::MD5::update().
Referenced by llvm::DIEHash::computeDIEODRSignature().