LLVM: DWARFContext.cpp File Reference
LLVM API Documentation
DWARFContext.cpp File Reference
#include "DWARFContext.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Support/Compression.h"
#include "llvm/Support/Dwarf.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
Typedefs
typedef DWARFDebugLine::LineTable DWARFLineTable
Functions
static void dumpPubSection (raw_ostream &OS, StringRef Name, StringRef Data, bool LittleEndian, bool GnuStyle)
static bool getFileNameForCompileUnit (DWARFCompileUnit *CU, const DWARFLineTable *LineTable, uint64_t FileIndex, bool NeedsAbsoluteFilePath, std::string &FileName)
static bool getFileLineInfoForCompileUnit (DWARFCompileUnit *CU, const DWARFLineTable *LineTable, uint64_t Address, bool NeedsAbsoluteFilePath, std::string &FileName, uint32_t &Line, uint32_t &Column)
static bool consumeCompressedDebugSectionHeader (StringRef &data, uint64_t &OriginalSize)
Typedef Documentation
typedef DWARFDebugLine::LineTable DWARFLineTable
Definition at line 24 of file DWARFContext.cpp.
Function Documentation
static bool consumeCompressedDebugSectionHeader (StringRef & data, uint64_t & OriginalSize) static
Definition at line 559 of file DWARFContext.cpp.
References llvm::DataExtractor::getU64(), llvm::StringRef::startswith(), and llvm::StringRef::substr().
Referenced by llvm::DWARFContextInMemory::DWARFContextInMemory().
static void dumpPubSection (raw_ostream & OS, StringRef Name, StringRef Data, bool LittleEndian, bool GnuStyle) static
Definition at line 32 of file DWARFContext.cpp.
References llvm::format(), llvm::dwarf::GDBIndexEntryKindString(), llvm::dwarf::GDBIndexEntryLinkageString(), llvm::DataExtractor::getCStr(), llvm::DataExtractor::getU16(), llvm::DataExtractor::getU32(), llvm::DataExtractor::getU8(), and llvm::StringRef::size().
Referenced by llvm::DWARFContext::dump().
static bool getFileLineInfoForCompileUnit (DWARFCompileUnit * CU, const DWARFLineTable * LineTable, uint64_t Address, bool NeedsAbsoluteFilePath, std::string & FileName, uint32_t & Line, uint32_t & Column) static
Definition at line 393 of file DWARFContext.cpp.
References llvm::DWARFDebugLine::Row::Column, llvm::DWARFDebugLine::Row::File, getFileNameForCompileUnit(), llvm::DWARFDebugLine::Row::Line, llvm::DWARFDebugLine::LineTable::lookupAddress(), and llvm::DWARFDebugLine::LineTable::Rows.
Referenced by llvm::DWARFContext::getInliningInfoForAddress(), and llvm::DWARFContext::getLineInfoForAddress().
static bool getFileNameForCompileUnit (DWARFCompileUnit * CU, const DWARFLineTable * LineTable, uint64_t FileIndex, bool NeedsAbsoluteFilePath, std::string & FileName) static
Definition at line 371 of file DWARFContext.cpp.
References llvm::sys::path::append(), llvm::DWARFUnit::getCompilationDir(), llvm::DWARFDebugLine::LineTable::getFileNameByIndex(), llvm::sys::path::is_relative(), and llvm::SmallString< InternalLen >::str().
Referenced by getFileLineInfoForCompileUnit(), llvm::DWARFContext::getInliningInfoForAddress(), and llvm::DWARFContext::getLineInfoForAddressRange().