LLVM: DwarfCompileUnit.cpp File Reference
LLVM API Documentation
DwarfCompileUnit.cpp File Reference
#include "DwarfCompileUnit.h"
#include "DwarfAccelTable.h"
#include "DwarfDebug.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/DIBuilder.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Instructions.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/Target/Mangler.h"
#include "llvm/Target/TargetFrameLowering.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetRegisterInfo.h"
Macros
#define DEBUG_TYPE "dwarfdebug"
Functions
static bool isShareableAcrossCUs (DIDescriptor D)
Check whether the DIE for this MDNode can be shared across CUs.
static bool isTypeSigned (DwarfDebug *DD, DIType Ty, int *SizeInBits)
isTypeSigned - Return true if the type is signed.
static bool isUnsignedDIType (DwarfDebug *DD, DIType Ty)
Return true if type encoding is unsigned.
static uint64_t getBaseTypeSize (DwarfDebug *DD, DIDerivedType Ty)
If this type is derived from a base type then return base type size.
static bool isTypeUnitScoped (DIType Ty, const DwarfDebug *DD)
static bool shouldCreateTypeUnit (DICompositeType CTy, const DwarfDebug *DD)
Return true if the type should be split out into a type unit.
static const ConstantExpr * getMergedGlobalExpr (const Value *V)
Macro Definition Documentation
#define DEBUG_TYPE "dwarfdebug"
Definition at line 14 of file DwarfCompileUnit.cpp.
Function Documentation
static uint64_t getBaseTypeSize (DwarfDebug * DD, DIDerivedType Ty) static
If this type is derived from a base type then return base type size.
Definition at line 691 of file DwarfCompileUnit.cpp.
References llvm::DIType::getSizeInBits(), llvm::DIDescriptor::getTag(), llvm::DIDerivedType::getTypeDerivedFrom(), llvm::DIDescriptor::isDerivedType(), llvm::DIType::isValid(), and llvm::DwarfDebug::resolve().
Referenced by llvm::CompileUnit::constructVariableDIE().
static const ConstantExpr* getMergedGlobalExpr (const Value * V) static
Definition at line 1484 of file DwarfCompileUnit.cpp.
References llvm::User::getNumOperands(), llvm::ConstantExpr::getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), and llvm::ConstantInt::isZero().
Referenced by llvm::CompileUnit::createGlobalVariableDIE().
static bool isShareableAcrossCUs (DIDescriptor D) static
Check whether the DIE for this MDNode can be shared across CUs.
Definition at line 102 of file DwarfCompileUnit.cpp.
References llvm::DISubprogram::isDefinition(), llvm::DIDescriptor::isSubprogram(), and llvm::DIDescriptor::isType().
Referenced by llvm::CompileUnit::getDIE(), and llvm::CompileUnit::insertDIE().
static bool isTypeSigned (DwarfDebug * DD, DIType Ty, int * SizeInBits) static
isTypeSigned - Return true if the type is signed.
Definition at line 660 of file DwarfCompileUnit.cpp.
References llvm::dwarf::DW_ATE_signed, llvm::dwarf::DW_ATE_signed_char, llvm::DIBasicType::getEncoding(), llvm::DIType::getSizeInBits(), llvm::DIDescriptor::isBasicType(), llvm::DIDescriptor::isDerivedType(), and llvm::DwarfDebug::resolve().
Referenced by llvm::CompileUnit::addConstantValue().
static bool isTypeUnitScoped (DIType Ty, const DwarfDebug * DD) static
Return true if the type is appropriately scoped to be contained inside its own type unit.
Definition at line 1099 of file DwarfCompileUnit.cpp.
References llvm::DIScope::getContext(), llvm::DIType::getContext(), llvm::DIDescriptor::isSubprogram(), and llvm::DwarfDebug::resolve().
Referenced by shouldCreateTypeUnit().
static bool isUnsignedDIType (DwarfDebug * DD, DIType Ty) static
Return true if type encoding is unsigned.
Definition at line 674 of file DwarfCompileUnit.cpp.
References llvm::dwarf::DW_ATE_boolean, llvm::dwarf::DW_ATE_unsigned, llvm::dwarf::DW_ATE_unsigned_char, llvm::DIBasicType::getEncoding(), llvm::DIDerivedType::getTypeDerivedFrom(), llvm::DIDescriptor::isBasicType(), llvm::DIDescriptor::isDerivedType(), and llvm::DwarfDebug::resolve().
Referenced by llvm::CompileUnit::constructVariableDIE(), llvm::CompileUnit::createGlobalVariableDIE(), and shouldCreateTypeUnit().
static bool shouldCreateTypeUnit (DICompositeType CTy, const DwarfDebug * DD) static
Return true if the type should be split out into a type unit.
Definition at line 1111 of file DwarfCompileUnit.cpp.
References llvm::ARM_PROC::A, llvm::CompileUnit::addBlock(), llvm::CompileUnit::addConstantValue(), llvm::CompileUnit::addDIEEntry(), llvm::CompileUnit::addFlag(), llvm::CompileUnit::addOpAddress(), llvm::CompileUnit::addSourceLine(), llvm::CompileUnit::addString(), llvm::CompileUnit::addTemplateParams(), llvm::CompileUnit::addType(), llvm::DwarfDebug::addTypeUnitType(), llvm::CompileUnit::addUInt(), llvm::CompileUnit::createAndAddDIE(), llvm::dwarf::DW_ACCESS_private, llvm::dwarf::DW_ACCESS_protected, llvm::dwarf::DW_ACCESS_public, llvm::dwarf::DW_APPLE_PROPERTY_assign, llvm::dwarf::DW_APPLE_PROPERTY_copy, llvm::dwarf::DW_APPLE_PROPERTY_nonatomic, llvm::dwarf::DW_APPLE_PROPERTY_readonly, llvm::dwarf::DW_APPLE_PROPERTY_readwrite, llvm::dwarf::DW_APPLE_PROPERTY_retain, llvm::dwarf::DW_LANG_C89, llvm::dwarf::DW_LANG_C99, llvm::dwarf::DW_LANG_ObjC, llvm::dwarf::DW_OP_stack_value, llvm::StringRef::empty(), llvm::DICompositeType::getContainingType(), llvm::DIArray::getElement(), llvm::CompileUnit::getLanguage(), llvm::DIType::getName(), llvm::DITemplateTypeParameter::getName(), llvm::DITemplateValueParameter::getName(), llvm::DIArray::getNumElements(), llvm::DIObjCProperty::getObjCPropertyGetterName(), llvm::DIObjCProperty::getObjCPropertyName(), llvm::DIObjCProperty::getObjCPropertySetterName(), llvm::CompileUnit::getOrCreateSubprogramDIE(), llvm::CompileUnit::getOrCreateTypeDIE(), llvm::DICompositeType::getRunTimeLang(), llvm::DIType::getSizeInBits(), llvm::AsmPrinter::getSymbol(), llvm::DIDescriptor::getTag(), llvm::DIE::getTag(), llvm::DICompositeType::getTemplateParams(), llvm::DITemplateTypeParameter::getType(), llvm::DITemplateValueParameter::getType(), llvm::DIObjCProperty::getType(), llvm::DICompositeType::getTypeArray(), llvm::DIDerivedType::getTypeDerivedFrom(), llvm::DITemplateValueParameter::getValue(), i, llvm::DIType::isAppleBlockExtension(), llvm::DIObjCProperty::isAssignObjCProperty(), llvm::DIObjCProperty::isCopyObjCProperty(), llvm::DIDescriptor::isDerivedType(), llvm::DISubprogram::isExplicit(), llvm::DIType::isForwardDecl(), llvm::DIObjCProperty::isNonAtomicObjCProperty(), llvm::DIType::isObjcClassComplete(), llvm::DIDescriptor::isObjCProperty(), llvm::DISubprogram::isPrivate(), llvm::DISubprogram::isProtected(), llvm::DIObjCProperty::isReadOnlyObjCProperty(), llvm::DIObjCProperty::isReadWriteObjCProperty(), llvm::DIObjCProperty::isRetainObjCProperty(), llvm::DIType::isStaticMember(), llvm::DIDescriptor::isSubprogram(), isTypeUnitScoped(), isUnsignedDIType(), llvm::DIDescriptor::isUnspecifiedParameter(), N, and llvm::None.