LLVM: EarlyIfConversion.cpp File Reference
LLVM API Documentation
EarlyIfConversion.cpp File Reference
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SparseSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineBranchProbabilityInfo.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/MachineTraceMetrics.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include "llvm/Target/TargetSubtargetInfo.h"
Macros
#define DEBUG_TYPE "early-ifcvt"
Functions
STATISTIC (NumDiamondsSeen,"Number of diamonds")
STATISTIC (NumDiamondsConv,"Number of diamonds converted")
STATISTIC (NumTrianglesSeen,"Number of triangles")
STATISTIC (NumTrianglesConv,"Number of triangles converted")
INITIALIZE_PASS_BEGIN (EarlyIfConverter,"early-ifcvt","Early If Converter", false, false) INITIALIZE_PASS_END(EarlyIfConverter
static unsigned adjCycles (unsigned Cyc, int Delta)
Variables
static cl::opt< unsigned > BlockInstrLimit ("early-ifcvt-limit", cl::init(30), cl::Hidden, cl::desc("Maximum number of instructions per speculated block."))
static cl::opt< bool > Stress ("stress-early-ifcvt", cl::Hidden, cl::desc("Turn all knobs to 11"))
early ifcvt
early Early If Converter
early Early If false
Macro Definition Documentation
#define DEBUG_TYPE "early-ifcvt"
Definition at line 19 of file EarlyIfConversion.cpp.
Function Documentation
static unsigned adjCycles (unsigned Cyc, int Delta) static
Definition at line 666 of file EarlyIfConversion.cpp.
References llvm::dbgs(), DEBUG, llvm::MachineTraceMetrics::InstrCycles::Depth, llvm::MachineTraceMetrics::Trace::getCriticalPath(), llvm::MachineTraceMetrics::Trace::getInstrCycles(), llvm::TargetMachine::getInstrInfo(), llvm::MachineTraceMetrics::Trace::getInstrSlack(), llvm::MachineFunction::getName(), llvm::MachineTraceMetrics::Trace::getPHIDepth(), llvm::MachineFunction::getRegInfo(), llvm::TargetMachine::getRegisterInfo(), llvm::MachineTraceMetrics::Trace::getResourceLength(), llvm::TargetMachine::getSubtarget(), llvm::MachineFunction::getTarget(), i, I, Loops, MaxDepth, llvm::po_begin(), llvm::po_end(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), Stress, and llvm::MachineTraceMetrics::TS_MinInstrCount.
INITIALIZE_PASS_BEGIN (EarlyIfConverter , "early-ifcvt" , "Early If Converter" , false , false)
STATISTIC (NumDiamondsSeen , "Number of diamonds")
STATISTIC (NumDiamondsConv , "Number of diamonds converted")
STATISTIC (NumTrianglesSeen , "Number of triangles")
STATISTIC (NumTrianglesConv , "Number of triangles converted")
Variable Documentation
cl::opt<unsigned> BlockInstrLimit("early-ifcvt-limit", cl::init(30), cl::Hidden, cl::desc("Maximum number of instructions per speculated block.")) static
early Early If Converter
Definition at line 615 of file EarlyIfConversion.cpp.
early Early If false
Definition at line 615 of file EarlyIfConversion.cpp.
early ifcvt
Definition at line 615 of file EarlyIfConversion.cpp.
cl::opt<bool> Stress("stress-early-ifcvt", cl::Hidden, cl::desc("Turn all knobs to 11")) static
Referenced by adjCycles().