LLVM: EarlyCSE.cpp File Reference
LLVM API Documentation
EarlyCSE.cpp File Reference
#include "llvm/Transforms/Scalar.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/ScopedHashTable.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/Dominators.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Instructions.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/RecyclingAllocator.h"
#include "llvm/Target/TargetLibraryInfo.h"
#include "llvm/Transforms/Utils/Local.h"
#include <deque>
Classes
struct llvm::DenseMapInfo< SimpleValue >
struct llvm::DenseMapInfo< CallValue >
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "early-cse"
Functions
STATISTIC (NumSimplify,"Number of instructions simplified or DCE'd")
STATISTIC (NumCSE,"Number of instructions CSE'd")
STATISTIC (NumCSELoad,"Number of load instructions CSE'd")
STATISTIC (NumCSECall,"Number of call instructions CSE'd")
STATISTIC (NumDSE,"Number of trivial dead stores removed")
static unsigned getHash (const void *V)
Macro Definition Documentation
#define DEBUG_TYPE "early-cse"
Definition at line 15 of file EarlyCSE.cpp.
Function Documentation
static unsigned getHash (const void * V) static
Definition at line 38 of file EarlyCSE.cpp.
References I.
Referenced by FixTail(), llvm::DenseMapInfo< CallValue >::getTombstoneKey(), and profileFunction().
STATISTIC (NumSimplify , "Number of instructions simplified or DCE'd")
STATISTIC (NumCSE , "Number of instructions CSE'd")
STATISTIC (NumCSELoad , "Number of load instructions CSE'd")
STATISTIC (NumCSECall , "Number of call instructions CSE'd")
STATISTIC (NumDSE , "Number of trivial dead stores removed")