LLVM: ELFObjectWriter.cpp File Reference
LLVM API Documentation
ELFObjectWriter.cpp File Reference
#include "llvm/MC/MCELFObjectWriter.h"
#include "llvm/ADT/OwningPtr.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAsmLayout.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCELF.h"
#include "llvm/MC/MCELFSymbolFlags.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixupKindInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ELF.h"
#include "llvm/Support/ErrorHandling.h"
#include <vector>
Macros
#define DEBUG_TYPE "reloc-info"
Functions
static int compareBySuffix (const MCSectionELF *const *a, const MCSectionELF *const *b)
Macro Definition Documentation
#define DEBUG_TYPE "reloc-info"
Definition at line 38 of file ELFObjectWriter.cpp.
Function Documentation
static int compareBySuffix (const MCSectionELF *const * a, const MCSectionELF *const * b) static
Definition at line 1125 of file ELFObjectWriter.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::array_pod_sort(), llvm::StringRef::begin(), llvm::MCSectionData::begin(), llvm::MCAssembler::begin(), llvm::MCContext::CreateELFGroupSection(), llvm::ELF_STB_Weak, llvm::ELF::EM_ARM, llvm::StringRef::end(), llvm::MCSectionData::end(), llvm::MCAssembler::end(), llvm::StringRef::endswith(), F(), llvm::MCFragment::FT_Data, llvm::MCSectionData::getAlignment(), llvm::MCDataFragment::getContents(), llvm::MCAssembler::getContext(), llvm::MCContext::getELFSection(), llvm::MCSectionELF::getFlags(), llvm::MCSymbolData::getFlags(), llvm::MCSectionELF::getGroup(), llvm::MCFragment::getKind(), llvm::MCSymbol::getName(), llvm::MCAssembler::getNoExecStack(), llvm::MCAssembler::getOrCreateSectionData(), llvm::MCAssembler::getOrCreateSymbolData(), llvm::MCSectionData::getOrdinal(), llvm::SectionKind::getReadOnly(), llvm::MCSectionData::getSection(), llvm::MCAsmLayout::getSectionAddressSize(), llvm::MCAsmLayout::getSectionFileSize(), llvm::MCSectionELF::getSectionName(), llvm::SectionKind::getText(), llvm::MCSectionELF::getType(), llvm::COFF::HeaderSize, i, I, llvm::MCObjectWriter::IsSymbolRefDifferenceFullyResolvedImpl(), llvm::MCSection::isVirtualSection(), it, llvm::OffsetToAlignment(), p, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::AArch64ISD::Ret, llvm::RoundUpToAlignment(), llvm::ARMBuildAttrs::Section, llvm::MCSectionData::setAlignment(), llvm::ELF::SHN_LORESERVE, llvm::StringRef::size(), llvm::MCAssembler::size(), llvm::StringRef::substr(), llvm::ELF::SYMENTRY_SIZE32, llvm::ELF::SYMENTRY_SIZE64, and llvm::MCAssembler::writeSectionData().