LLVM: ExpandPostRAPseudos.cpp File Reference
LLVM API Documentation
ExpandPostRAPseudos.cpp File Reference
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetRegisterInfo.h"
Macros
#define DEBUG_TYPE "postrapseudos"
Functions
INITIALIZE_PASS (ExpandPostRA,"postrapseudos","Post-RA pseudo instruction expansion pass", false, false) void ExpandPostRA
Macro Definition Documentation
#define DEBUG_TYPE "postrapseudos"
Definition at line 15 of file ExpandPostRAPseudos.cpp.
Function Documentation
INITIALIZE_PASS (ExpandPostRA , "postrapseudos" , "Post-RA pseudo instruction expansion pass" , false , false)
TransferImplicitDefs - MI is a pseudo-instruction, and the lowered replacement instructions immediately precede it. Copy any implicit-def operands from MI to the replacement instruction.
Definition at line 59 of file ExpandPostRAPseudos.cpp.
References llvm::MachineInstr::allDefsAreDead(), llvm::MachineFunction::begin(), llvm::TargetOpcode::COPY, llvm::HexagonInstrInfo::copyPhysReg(), llvm::MachineOperand::CreateReg(), llvm::TargetOpcode::DBG_VALUE, llvm::dbgs(), DEBUG, llvm::MachineFunction::end(), llvm::MachineBasicBlock::erase(), llvm::MachineInstr::eraseFromParent(), llvm::TargetOpcode::EXTRACT_SUBREG, llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::TargetMachine::getInstrInfo(), llvm::MachineFunction::getName(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::TargetMachine::getRegisterInfo(), llvm::MachineOperand::getSubReg(), llvm::MachineFunction::getTarget(), i, llvm::TargetOpcode::INSERT_SUBREG, llvm::MachineOperand::isDef(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isKill(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::MachineInstr::isPseudo(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUndef(), llvm::MachineOperand::isUse(), llvm::TargetOpcode::KILL, llvm_unreachable, llvm::A64CC::MI, llvm::MachineInstr::RemoveOperand(), llvm::MachineInstr::setDesc(), llvm::TargetOpcode::SUBREG_TO_REG, and TII.