LLVM: ExternalFunctions.cpp File Reference
LLVM API Documentation
ExternalFunctions.cpp File Reference
#include "Interpreter.h"
#include "llvm/Config/config.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/DynamicLibrary.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/Mutex.h"
#include <cmath>
#include <csignal>
#include <cstdio>
#include <cstring>
#include <map>
Typedefs
typedef GenericValue(* ExFunc) (FunctionType *, const std::vector< GenericValue > &)
Functions
static char getTypeID (Type *Ty)
static ExFunc lookupFunction (const Function *F)
static GenericValue lle_X_atexit (FunctionType *FT, const std::vector< GenericValue > &Args)
static GenericValue lle_X_exit (FunctionType *FT, const std::vector< GenericValue > &Args)
static GenericValue lle_X_abort (FunctionType *FT, const std::vector< GenericValue > &Args)
static GenericValue lle_X_sprintf (FunctionType *FT, const std::vector< GenericValue > &Args)
static GenericValue lle_X_printf (FunctionType *FT, const std::vector< GenericValue > &Args)
static GenericValue lle_X_sscanf (FunctionType *FT, const std::vector< GenericValue > &args)
static GenericValue lle_X_scanf (FunctionType *FT, const std::vector< GenericValue > &args)
static GenericValue lle_X_fprintf (FunctionType *FT, const std::vector< GenericValue > &Args)
static GenericValue lle_X_memset (FunctionType *FT, const std::vector< GenericValue > &Args)
static GenericValue lle_X_memcpy (FunctionType *FT, const std::vector< GenericValue > &Args)
Variables
static ManagedStatic< sys::Mutex > FunctionsLock
static ManagedStatic< std::map< const Function *, ExFunc > > ExportedFunctions
static std::map< std::string, ExFunc > FuncNames
static Interpreter * TheInterpreter
Typedef Documentation
typedef GenericValue(* ExFunc) (FunctionType *, const std::vector< GenericValue > &)
Definition at line 51 of file ExternalFunctions.cpp.
Function Documentation
static char getTypeID (Type * Ty) static
Definition at line 63 of file ExternalFunctions.cpp.
References llvm::Type::ArrayTyID, llvm::Type::DoubleTyID, llvm::Type::FloatTyID, llvm::Type::FunctionTyID, llvm::Type::getTypeID(), llvm::Type::IntegerTyID, llvm::Type::PointerTyID, llvm::Type::StructTyID, and llvm::Type::VoidTyID.
Referenced by llvm::ConstantDataSequential::getElementAsAPFloat(), LLVMCreateGenericValueOfFloat(), LLVMGenericValueToFloat(), LLVMGetTypeKind(), and lookupFunction().
static GenericValue lle_X_abort (FunctionType * FT, const std::vector< GenericValue > & Args) static
Definition at line 321 of file ExternalFunctions.cpp.
Referenced by lle_X_memcpy().
static GenericValue lle_X_atexit (FunctionType * FT, const std::vector< GenericValue > & Args) static
Definition at line 302 of file ExternalFunctions.cpp.
References llvm::Interpreter::addAtExitHandler(), llvm::GVTOP(), and llvm::GenericValue::IntVal.
Referenced by lle_X_memcpy().
static GenericValue lle_X_exit (FunctionType * FT, const std::vector< GenericValue > & Args) static
Definition at line 313 of file ExternalFunctions.cpp.
References llvm::Interpreter::exitCalled().
Referenced by lle_X_memcpy().
static GenericValue lle_X_fprintf (FunctionType * FT, const std::vector< GenericValue > & Args) static
Definition at line 461 of file ExternalFunctions.cpp.
References llvm::LibFunc::fputs, llvm::GVTOP(), lle_X_sprintf(), and llvm::PTOGV().
Referenced by lle_X_memcpy().
static GenericValue lle_X_memcpy (FunctionType * FT, const std::vector< GenericValue > & Args) static
Definition at line 486 of file ExternalFunctions.cpp.
References FuncNames, llvm::GVTOP(), llvm::GenericValue::IntVal, llvm::tgtok::IntVal, lle_X_abort(), lle_X_atexit(), lle_X_exit(), lle_X_fprintf(), lle_X_memset(), lle_X_printf(), lle_X_scanf(), lle_X_sprintf(), lle_X_sscanf(), and llvm::Intrinsic::memcpy.
static GenericValue lle_X_memset (FunctionType * FT, const std::vector< GenericValue > & Args) static
Definition at line 474 of file ExternalFunctions.cpp.
References llvm::GVTOP(), int, llvm::GenericValue::IntVal, llvm::tgtok::IntVal, llvm::Intrinsic::memset, and val.
Referenced by lle_X_memcpy().
static GenericValue lle_X_printf (FunctionType * FT, const std::vector< GenericValue > & Args) static
Definition at line 415 of file ExternalFunctions.cpp.
References lle_X_sprintf(), llvm::outs(), and llvm::PTOGV().
Referenced by lle_X_memcpy().
static GenericValue lle_X_scanf (FunctionType * FT, const std::vector< GenericValue > & args) static
Definition at line 444 of file ExternalFunctions.cpp.
References llvm::GVTOP(), i, llvm::GenericValue::IntVal, and llvm::LibFunc::scanf.
Referenced by lle_X_memcpy().
static GenericValue lle_X_sprintf (FunctionType * FT, const std::vector< GenericValue > & Args) static
Definition at line 332 of file ExternalFunctions.cpp.
References llvm::errs(), llvm::ExecutionEngine::getDataLayout(), llvm::DataLayout::getPointerSizeInBits(), llvm::GVTOP(), llvm::GenericValue::IntVal, llvm::tgtok::IntVal, llvm::Intrinsic::memcpy, llvm::LibFunc::sprintf, and llvm::LibFunc::strlen.
Referenced by lle_X_fprintf(), lle_X_memcpy(), and lle_X_printf().
static GenericValue lle_X_sscanf (FunctionType * FT, const std::vector< GenericValue > & args) static
Definition at line 428 of file ExternalFunctions.cpp.
References llvm::GVTOP(), i, llvm::GenericValue::IntVal, and llvm::LibFunc::sscanf.
Referenced by lle_X_memcpy().
static ExFunc lookupFunction (const Function * F) static
Definition at line 90 of file ExternalFunctions.cpp.
References llvm::ARM_PROC::A, llvm::Function::arg_begin(), llvm::Function::arg_end(), llvm::Function::arg_size(), llvm::SmallVectorTemplateCommon< T >::data(), llvm::Type::DoubleTyID, llvm::GenericValue::DoubleVal, F(), llvm::Type::FloatTyID, llvm::GenericValue::FloatVal, FuncNames, llvm::Type::getContainedType(), llvm::Function::getFunctionType(), llvm::Value::getName(), llvm::Type::getNumContainedTypes(), llvm::FunctionType::getParamType(), llvm::FunctionType::getReturnType(), getTypeID(), llvm::Type::getTypeID(), llvm::DataLayout::getTypeStoreSize(), llvm::APInt::getZExtValue(), llvm::GVTOP(), i, llvm::Type::IntegerTyID, llvm::GenericValue::IntVal, llvm::Function::isVarArg(), llvm::Type::PointerTyID, llvm::GenericValue::PointerVal, llvm::report_fatal_error(), llvm::SmallVectorImpl< T >::resize(), ret(), llvm::sys::DynamicLibrary::SearchForAddressOfSymbol(), llvm::StringRef::str(), values, and llvm::Type::VoidTyID.
Referenced by llvm::Interpreter::callExternalFunction().
Variable Documentation
ManagedStatic<std::map<const Function *, ExFunc> > ExportedFunctions static
Definition at line 53 of file ExternalFunctions.cpp.
std::map<std::string, ExFunc> FuncNames static
Definition at line 54 of file ExternalFunctions.cpp.
Referenced by lle_X_memcpy(), and lookupFunction().
ManagedStatic<sys::Mutex> FunctionsLock static
Definition at line 49 of file ExternalFunctions.cpp.
Interpreter* TheInterpreter static
Definition at line 61 of file ExternalFunctions.cpp.