LLVM: ExtractGV.cpp File Reference
LLVM API Documentation
ExtractGV.cpp File Reference
#include "llvm/Transforms/IPO.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include <algorithm>
Functions
static void makeVisible (GlobalValue &GV, bool Delete)
Function Documentation
static void makeVisible (GlobalValue & GV, bool Delete) static
Make sure GV is visible from both modules. Delete is true if it is being deleted from this module. This also makes sure GV cannot be dropped so that references from the split module remain valid.
Definition at line 28 of file ExtractGV.cpp.
References llvm::Module::alias_begin(), llvm::Module::alias_end(), llvm::Module::begin(), llvm::SetVector< T, Vector, Set >::count(), llvm::Function::Create(), llvm::Module::end(), llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::getLinkage(), llvm::Module::global_begin(), llvm::Module::global_end(), llvm::GlobalValue::hasLinkOnceLinkage(), llvm::GlobalValue::hasLocalLinkage(), llvm::GlobalValue::HiddenVisibility, I, llvm::GlobalValue::isDiscardableIfUnused(), llvm::GlobalValue::LinkOnceAnyLinkage, llvm::GlobalValue::LinkOnceODRLinkage, llvm_unreachable, M, llvm::GlobalValue::setLinkage(), llvm::Module::setModuleInlineAsm(), llvm::GlobalValue::setVisibility(), llvm::GlobalValue::WeakAnyLinkage, and llvm::GlobalValue::WeakODRLinkage.