LLVM: FlattenCFGPass.cpp File Reference
LLVM API Documentation
FlattenCFGPass.cpp File Reference
#include "llvm/Transforms/Scalar.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Pass.h"
#include "llvm/Support/CFG.h"
#include "llvm/Transforms/Utils/Local.h"
Macros
#define DEBUG_TYPE "flattencfg"
Functions
INITIALIZE_PASS_BEGIN (FlattenCFGPass,"flattencfg","Flatten the CFG", false, false) INITIALIZE_PASS_END(FlattenCFGPass
static bool iterativelyFlattenCFG (Function &F, AliasAnalysis *AA)
Variables
flattencfg
Flatten the CFG
Flatten the false
Macro Definition Documentation
#define DEBUG_TYPE "flattencfg"
Definition at line 14 of file FlattenCFGPass.cpp.
Function Documentation
INITIALIZE_PASS_BEGIN (FlattenCFGPass , "flattencfg" , "Flatten the CFG" , false , false)
static bool iterativelyFlattenCFG (Function & F, AliasAnalysis * AA) static
iterativelyFlattenCFG - Call FlattenCFG on all the blocks in the function, iterating until no more changes are made.
Definition at line 52 of file FlattenCFGPass.cpp.
References llvm::Function::begin(), llvm::Function::end(), F(), llvm::FlattenCFG(), and llvm::removeUnreachableBlocks().
Variable Documentation
Flatten the CFG
Definition at line 44 of file FlattenCFGPass.cpp.
Flatten the false
Definition at line 44 of file FlattenCFGPass.cpp.
flattencfg
Definition at line 44 of file FlattenCFGPass.cpp.