LLVM: FunctionAttrs.cpp File Reference
LLVM API Documentation
FunctionAttrs.cpp File Reference
#include "llvm/Transforms/IPO.h"
#include "llvm/ADT/SCCIterator.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/CallGraph.h"
#include "llvm/Analysis/CallGraphSCCPass.h"
#include "llvm/Analysis/CaptureTracking.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/Support/InstIterator.h"
#include "llvm/Target/TargetLibraryInfo.h"
Classes
struct llvm::GraphTraits< ArgumentGraphNode * >
struct llvm::GraphTraits< ArgumentGraph * >
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "functionattrs"
Functions
STATISTIC (NumReadNone,"Number of functions marked readnone")
STATISTIC (NumReadOnly,"Number of functions marked readonly")
STATISTIC (NumNoCapture,"Number of arguments marked nocapture")
STATISTIC (NumReadNoneArg,"Number of arguments marked readnone")
STATISTIC (NumReadOnlyArg,"Number of arguments marked readonly")
STATISTIC (NumNoAlias,"Number of function returns marked noalias")
STATISTIC (NumAnnotated,"Number of attributes added to library functions")
INITIALIZE_PASS_BEGIN (FunctionAttrs,"functionattrs","Deduce function attributes", false, false) INITIALIZE_PASS_END(FunctionAttrs
static Attribute::AttrKind determinePointerReadAttrs (Argument *A, const SmallPtrSet< Argument *, 8 > &SCCNodes)
Variables
functionattrs
Deduce function attributes
Deduce function false
Macro Definition Documentation
#define DEBUG_TYPE "functionattrs"
Definition at line 21 of file FunctionAttrs.cpp.
Function Documentation
static Attribute::AttrKind determinePointerReadAttrs (Argument * A, const SmallPtrSet< Argument *, 8 > & SCCNodes) static
Definition at line 410 of file FunctionAttrs.cpp.
References llvm::ARM_PROC::A, llvm::LibFunc::access, llvm::Argument::addAttr(), llvm::AttrBuilder::addAttribute(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_begin(), llvm::Function::arg_begin(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_end(), llvm::Function::arg_end(), llvm::LibFunc::atof, llvm::LibFunc::atoi, llvm::LibFunc::atol, llvm::LibFunc::atoll, B, llvm::LibFunc::bcmp, llvm::LibFunc::bcopy, llvm::CallGraphSCC::begin(), llvm::Function::begin(), llvm::LibFunc::bzero, llvm::Call, llvm::LibFunc::calloc, llvm::LibFunc::chmod, llvm::LibFunc::chown, llvm::LibFunc::clearerr, llvm::LibFunc::closedir, llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::LibFunc::ctermid, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::doesNotAccessMemory(), llvm::Function::doesNotAlias(), llvm::Function::doesNotThrow(), llvm::LibFunc::dunder_isoc99_scanf, llvm::LibFunc::dunder_isoc99_sscanf, llvm::LibFunc::dunder_strdup, llvm::LibFunc::dunder_strndup, llvm::LibFunc::dunder_strtok_r, llvm::SmallVectorBase::empty(), llvm::CallGraphSCC::end(), llvm::Function::end(), llvm::LibFunc::fclose, llvm::LibFunc::fdopen, llvm::LibFunc::feof, llvm::LibFunc::ferror, llvm::LibFunc::fflush, llvm::LibFunc::fgetc, llvm::LibFunc::fgetpos, llvm::LibFunc::fgets, llvm::LibFunc::fileno, llvm::LibFunc::flockfile, llvm::LibFunc::fopen, llvm::LibFunc::fopen64, llvm::LibFunc::fprintf, llvm::LibFunc::fputc, llvm::LibFunc::fputs, llvm::LibFunc::fread, llvm::LibFunc::free, llvm::LibFunc::frexp, llvm::LibFunc::frexpf, llvm::LibFunc::frexpl, llvm::LibFunc::fscanf, llvm::LibFunc::fseek, llvm::LibFunc::fseeko, llvm::LibFunc::fseeko64, llvm::LibFunc::fsetpos, llvm::LibFunc::fstat, llvm::LibFunc::fstat64, llvm::LibFunc::fstatvfs, llvm::LibFunc::fstatvfs64, llvm::LibFunc::ftell, llvm::LibFunc::ftello, llvm::LibFunc::ftello64, llvm::LibFunc::ftrylockfile, llvm::LibFunc::funlockfile, llvm::LibFunc::fwrite, get, llvm::Argument::getArgNo(), llvm::LibFunc::getc, llvm::LibFunc::getc_unlocked, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledFunction(), llvm::LibFunc::getchar, llvm::Value::getContext(), llvm::Function::getContext(), llvm::LibFunc::getenv, llvm::SelectInst::getFalseValue(), llvm::Function::getFunctionType(), llvm::PHINode::getIncomingValue(), llvm::LibFunc::getitimer, llvm::LibFunc::getlogin_r, llvm::Value::getName(), llvm::PHINode::getNumIncomingValues(), llvm::FunctionType::getNumParams(), llvm::Instruction::getOpcode(), llvm::FunctionType::getParamType(), llvm::LibFunc::getpwnam, llvm::FunctionType::getReturnType(), llvm::Function::getReturnType(), llvm::LibFunc::gets, llvm::LibFunc::gettimeofday, llvm::SelectInst::getTrueValue(), llvm::Argument::hasNoCaptureAttr(), llvm::LibFunc::htonl, llvm::LibFunc::htons, i, I, llvm::SmallSet< T, N, C >::insert(), llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::insert(), llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::GlobalValue::isDeclaration(), llvm::Type::isIntegerTy(), llvm::Type::isPointerTy(), llvm::Function::isVarArg(), llvm::Type::isVoidTy(), llvm::LibFunc::lchown, llvm::SPII::Load, llvm::LibFunc::lstat, llvm::LibFunc::lstat64, llvm::LibFunc::malloc, llvm::GlobalValue::mayBeOverridden(), llvm::LibFunc::memalign, llvm::LibFunc::memccpy, llvm::LibFunc::memchr, llvm::LibFunc::memcmp, llvm::LibFunc::memcpy, llvm::LibFunc::memmove, llvm::LibFunc::memrchr, llvm::LibFunc::mkdir, llvm::LibFunc::mktime, llvm::LibFunc::modf, llvm::LibFunc::modff, llvm::LibFunc::modfl, N, llvm::Attribute::NoAlias, llvm::Attribute::NoCapture, llvm::Attribute::None, llvm::LibFunc::ntohl, llvm::LibFunc::ntohs, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::onlyReadsMemory(), llvm::Function::onlyReadsMemory(), llvm::LibFunc::open, llvm::LibFunc::open64, llvm::LibFunc::opendir, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::paramHasAttr(), llvm::LibFunc::pclose, llvm::LibFunc::perror, llvm::TargetOpcode::PHI, llvm::PointerMayBeCaptured(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::LibFunc::popen, llvm::LibFunc::pread, llvm::LibFunc::printf, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::LibFunc::putc, llvm::LibFunc::putchar, llvm::LibFunc::puts, llvm::LibFunc::pwrite, llvm::LibFunc::qsort, llvm::LibFunc::read, llvm::LibFunc::readlink, llvm::Attribute::ReadNone, llvm::Attribute::ReadOnly, llvm::LibFunc::realloc, llvm::LibFunc::realpath, llvm::LibFunc::remove, llvm::LibFunc::rename, llvm::AArch64ISD::Ret, llvm::LibFunc::rewind, llvm::LibFunc::rmdir, llvm::LibFunc::scanf, llvm::scc_begin(), llvm::scc_end(), llvm::MCID::Select, llvm::LibFunc::setbuf, llvm::Function::setDoesNotAlias(), llvm::LibFunc::setitimer, llvm::LibFunc::setvbuf, llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::size(), llvm::LibFunc::snprintf, llvm::LibFunc::sprintf, llvm::LibFunc::sscanf, llvm::LibFunc::stat, llvm::LibFunc::stat64, llvm::LibFunc::statvfs, llvm::LibFunc::statvfs64, llvm::LibFunc::stpcpy, llvm::LibFunc::stpncpy, llvm::LibFunc::strcasecmp, llvm::LibFunc::strcat, llvm::LibFunc::strchr, llvm::LibFunc::strcmp, llvm::LibFunc::strcoll, llvm::LibFunc::strcpy, llvm::LibFunc::strcspn, llvm::LibFunc::strdup, llvm::LibFunc::strlen, llvm::LibFunc::strncasecmp, llvm::LibFunc::strncat, llvm::LibFunc::strncmp, llvm::LibFunc::strncpy, llvm::LibFunc::strndup, llvm::LibFunc::strpbrk, llvm::LibFunc::strrchr, llvm::LibFunc::strspn, llvm::LibFunc::strstr, llvm::LibFunc::strtod, llvm::LibFunc::strtof, llvm::LibFunc::strtok, llvm::LibFunc::strtok_r, llvm::LibFunc::strtol, llvm::LibFunc::strtold, llvm::LibFunc::strtoll, llvm::LibFunc::strtoul, llvm::LibFunc::strtoull, llvm::LibFunc::strxfrm, llvm::LibFunc::system, llvm::LibFunc::times, llvm::LibFunc::tmpfile, llvm::LibFunc::tmpfile64, llvm::LibFunc::uname, llvm::LibFunc::under_IO_getc, llvm::LibFunc::under_IO_putc, llvm::LibFunc::ungetc, llvm::LibFunc::unlink, llvm::LibFunc::unsetenv, llvm::Value::use_begin(), llvm::Value::use_end(), llvm::LibFunc::utime, llvm::LibFunc::utimes, llvm::LibFunc::valloc, llvm::LibFunc::vfprintf, llvm::LibFunc::vfscanf, llvm::LibFunc::vprintf, llvm::LibFunc::vscanf, llvm::LibFunc::vsnprintf, llvm::LibFunc::vsprintf, llvm::LibFunc::vsscanf, and llvm::LibFunc::write.
INITIALIZE_PASS_BEGIN (FunctionAttrs , "functionattrs" , "Deduce function attributes" , false , false)
STATISTIC (NumReadNone , "Number of functions marked readnone")
STATISTIC (NumReadOnly , "Number of functions marked readonly")
STATISTIC (NumNoCapture , "Number of arguments marked nocapture")
STATISTIC (NumReadNoneArg , "Number of arguments marked readnone")
STATISTIC (NumReadOnlyArg , "Number of arguments marked readonly")
STATISTIC (NumNoAlias , "Number of function returns marked noalias")
STATISTIC (NumAnnotated , "Number of attributes added to library functions")
Variable Documentation
Deduce function attributes
Definition at line 142 of file FunctionAttrs.cpp.
Referenced by llvm::LLLexer::getFilename(), and LTOModule::getSymbolAttributes().
Deduce function false
Definition at line 142 of file FunctionAttrs.cpp.
functionattrs
Definition at line 142 of file FunctionAttrs.cpp.