LLVM: FunctionLoweringInfo.cpp File Reference
LLVM API Documentation
FunctionLoweringInfo.cpp File Reference
#include "llvm/CodeGen/FunctionLoweringInfo.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/DebugInfo.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "function-lowering-info"
Functions
static bool isUsedOutsideOfDefiningBlock (const Instruction *I)
Macro Definition Documentation
#define DEBUG_TYPE "function-lowering-info"
Definition at line 15 of file FunctionLoweringInfo.cpp.
Function Documentation
static bool isUsedOutsideOfDefiningBlock (const Instruction * I) static
isUsedOutsideOfDefiningBlock - Return true if this instruction is used by PHI nodes or outside of the basic block that defines it, or used by a switch or atomic instruction, which may expand to multiple basic blocks.
Definition at line 45 of file FunctionLoweringInfo.cpp.
References BB, llvm::Instruction::getParent(), llvm::Value::use_begin(), llvm::Value::use_empty(), and llvm::Value::use_end().
Referenced by llvm::FunctionLoweringInfo::set().