LLVM: GCMetadata.cpp File Reference
LLVM API Documentation
GCMetadata.cpp File Reference
#include "llvm/CodeGen/GCMetadata.h"
#include "llvm/CodeGen/GCStrategy.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/Function.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
Functions
INITIALIZE_PASS (GCModuleInfo,"collector-metadata","Create Garbage Collector Module Metadata", false, false) GCFunctionInfo
static const char * DescKind (GC::PointKind Kind)
Function Documentation
static const char* DescKind (GC::PointKind Kind) static
Definition at line 132 of file GCMetadata.cpp.
References llvm::GCFunctionInfo::begin(), llvm::GCModuleInfo::clear(), llvm::GCFunctionInfo::end(), F(), llvm::GCFunctionInfo::getFunction(), llvm::GCModuleInfo::getFunctionInfo(), llvm::Value::getName(), llvm::Function::hasGC(), llvm::GCFunctionInfo::live_begin(), llvm::GCFunctionInfo::live_end(), llvm_unreachable, llvm::GC::Loop, llvm::GC::PostCall, llvm::GC::PreCall, llvm::GC::Return, llvm::GCFunctionInfo::roots_begin(), and llvm::GCFunctionInfo::roots_end().
INITIALIZE_PASS (GCModuleInfo , "collector-metadata" , "Create Garbage Collector Module Metadata" , false , false)
Definition at line 45 of file GCMetadata.cpp.