LLVM: GCOVProfiling.cpp File Reference
LLVM API Documentation
GCOVProfiling.cpp File Reference
#include "llvm/Transforms/Instrumentation.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/UniqueVector.h"
#include "llvm/DebugInfo.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/DebugLoc.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/InstIterator.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/ModuleUtils.h"
#include <algorithm>
#include <string>
#include <utility>
Macros
#define DEBUG_TYPE "insert-gcov-profiling"
Functions
INITIALIZE_PASS (GCOVProfiler,"insert-gcov-profiling","Insert instrumentation for GCOV profiling", false, false) ModulePass *llvm
static std::string getFunctionName (DISubprogram SP)
Variables
static cl::opt< std::string > DefaultGCOVVersion ("default-gcov-version", cl::init("402*"), cl::Hidden, cl::ValueRequired)
Macro Definition Documentation
#define DEBUG_TYPE "insert-gcov-profiling"
Definition at line 17 of file GCOVProfiling.cpp.
Function Documentation
static std::string getFunctionName (DISubprogram SP) static
Definition at line 148 of file GCOVProfiling.cpp.
References llvm::GCOVBlock::addEdge(), llvm::Function::addFnAttr(), llvm::sys::path::append(), llvm::appendToGlobalCtors(), llvm::Function::arg_begin(), BB, llvm::SmallVectorTemplateCommon< T >::begin(), llvm::Function::begin(), llvm::c_str(), llvm::raw_fd_ostream::close(), llvm::BasicBlock::Create(), llvm::Function::Create(), llvm::BranchInst::Create(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateAdd(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateBr(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateCall(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateCall2(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateCall3(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateCondBr(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateConstGEP2_64(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateConstInBoundsGEP2_64(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateGEP(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateGlobalStringPtr(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmpEQ(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateInBoundsGEP(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateLoad(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateRet(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateRetVoid(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateSelect(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateStore(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateZExt(), llvm::sys::fs::current_path(), llvm::StringRef::data(), llvm::dbgs(), DEBUG, llvm::DeleteContainerSeconds(), llvm::dyn_cast(), llvm::UniqueVector< T >::empty(), llvm::StringRef::empty(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::Function::end(), F(), llvm::sys::fs::F_Binary, llvm::sys::path::filename(), llvm::ConstantInt::get(), llvm::FunctionType::get(), llvm::ArrayType::get(), llvm::ConstantArray::get(), llvm::PointerType::get(), llvm::Module::getContext(), llvm::getDISubprogram(), llvm::DIArray::getElement(), llvm::SequentialType::getElementType(), llvm::DIScope::getFilename(), llvm::Module::getFunction(), llvm::DISubprogram::getFunction(), llvm::Module::getGlobalVariable(), llvm::IRBuilderBase::getInt32(), llvm::Type::getInt32Ty(), llvm::IRBuilderBase::getInt64(), llvm::Type::getInt64PtrTy(), llvm::IRBuilderBase::getInt64Ty(), llvm::Type::getInt64Ty(), llvm::IRBuilderBase::getInt8(), llvm::IRBuilderBase::getInt8PtrTy(), llvm::Type::getInt8PtrTy(), llvm::Type::getInt8Ty(), llvm::StringMapEntry< ValueTy >::getKey(), llvm::DebugLoc::getLine(), llvm::DISubprogram::getLineNumber(), llvm::DISubprogram::getLinkageName(), llvm::Value::getName(), llvm::DISubprogram::getName(), llvm::Module::getNamedMetadata(), llvm::Constant::getNullValue(), llvm::DIArray::getNumElements(), llvm::MDNode::getNumOperands(), llvm::NamedMDNode::getNumOperands(), llvm::TerminatorInst::getNumSuccessors(), llvm::MDNode::getOperand(), llvm::NamedMDNode::getOperand(), llvm::Module::getOrInsertFunction(), llvm::Type::getPointerTo(), llvm::Function::getReturnType(), llvm::DebugLoc::getScope(), llvm::MDString::getString(), llvm::DICompileUnit::getSubprograms(), llvm::TerminatorInst::getSuccessor(), llvm::GlobalValue::getType(), llvm::IRBuilderBase::getVoidTy(), llvm::Type::getVoidTy(), i, I, llvm::UniqueVector< T >::idFor(), llvm::ARM_PROC::IE, llvm::UniqueVector< T >::insert(), llvm::GlobalValue::InternalLinkage, llvm::Type::isIntegerTy(), llvm::DebugLoc::isUnknown(), j(), M, N, llvm::next(), llvm::Attribute::NoInline, llvm::Attribute::NoRedZone, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::sys::path::replace_extension(), llvm::report_fatal_error(), s, llvm::IRBuilderBase::SetInsertPoint(), llvm::GlobalValue::setLinkage(), llvm::Value::setName(), llvm::GlobalValue::setUnnamedAddr(), llvm::UniqueVector< T >::size(), llvm::StringRef::size(), llvm::StringRef::str(), llvm::SmallString< InternalLen >::str(), llvm::GCOVOptions::UseCfgChecksum, llvm::raw_ostream::write(), and llvm::LibFunc::write.
INITIALIZE_PASS (GCOVProfiler , "insert-gcov-profiling" , "Insert instrumentation for GCOV profiling" , false , false)
Definition at line 141 of file GCOVProfiling.cpp.
Variable Documentation
cl::opt<std::string> DefaultGCOVVersion("default-gcov-version", cl::init("402*"), cl::Hidden, cl::ValueRequired) static
Referenced by llvm::GCOVOptions::getDefault().