LLVM: GCStrategy.cpp File Reference
LLVM API Documentation
GCStrategy.cpp File Reference
#include "llvm/CodeGen/GCStrategy.h"
#include "llvm/Analysis/DominatorInternals.h"
#include "llvm/Analysis/Dominators.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetFrameLowering.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetRegisterInfo.h"
Functions
INITIALIZE_PASS_BEGIN (LowerIntrinsics,"gc-lowering","GC Lowering", false, false) FunctionPass *llvm
INITIALIZE_PASS (GCMachineCodeAnalysis,"gc-analysis","Analyze Machine Code For Garbage Collection", false, false) GCMachineCodeAnalysis
Function Documentation
INITIALIZE_PASS (GCMachineCodeAnalysis , "gc-analysis" , "Analyze Machine Code For Garbage Collection" , false , false)
Definition at line 340 of file GCStrategy.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::MachineFunction::begin(), llvm::BuildMI(), llvm::MCContext::CreateTempSymbol(), llvm::MachineFunction::end(), llvm::TargetOpcode::GC_LABEL, llvm::MachineFunctionPass::getAnalysisUsage(), llvm::MachineFunction::getContext(), llvm::TargetFrameLowering::getFrameIndexOffset(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::MachineBasicBlock::getParent(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getTarget(), llvm::Function::hasGC(), llvm::MachineFrameInfo::isDeadObjectIndex(), llvm::A64CC::MI, llvm::GC::PostCall, llvm::GC::PreCall, llvm::AnalysisUsage::setPreservesAll(), TII, and llvm::SystemZISD::TM.
INITIALIZE_PASS_BEGIN (LowerIntrinsics , "gc-lowering" , "GC Lowering" , false , false)
Definition at line 134 of file GCStrategy.cpp.
References llvm::AnalysisUsage::addPreserved(), llvm::AnalysisUsage::addRequired(), BB, llvm::SmallVectorTemplateCommon< T >::begin(), llvm::GCModuleInfo::begin(), llvm::BasicBlock::begin(), llvm::Function::begin(), llvm::Module::begin(), llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::GCStrategy::customReadBarrier(), llvm::GCStrategy::customRoots(), llvm::GCStrategy::customWriteBarrier(), llvm::GCModuleInfo::end(), llvm::Function::end(), llvm::Module::end(), F(), llvm::Intrinsic::gcread, llvm::Intrinsic::gcroot, llvm::Intrinsic::gcwrite, llvm::ConstantPointerNull::get(), llvm::Pass::getAnalysisUsage(), llvm::Function::getEntryBlock(), llvm::GCModuleInfo::getFunctionInfo(), llvm::Function::getIntrinsicID(), llvm::PassRegistry::getPassRegistry(), llvm::GCFunctionInfo::getStrategy(), llvm::Function::hasGC(), I, llvm::initializeLowerIntrinsicsPass(), llvm::GCStrategy::initializeRoots(), llvm::GCStrategy::InitRoots, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::Instruction::insertAfter(), llvm::A64CC::MI, llvm::GCStrategy::performCustomLowering(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::Value::replaceAllUsesWith(), S, llvm::SmallVectorTemplateCommon< T >::size(), and llvm::Value::takeName().