LLVM: GDBRegistrar.cpp File Reference
LLVM API Documentation
GDBRegistrar.cpp File Reference
#include "JITRegistrar.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Mutex.h"
#include "llvm/Support/MutexGuard.h"
Classes
struct jit_code_entry
struct jit_descriptor
Namespaces
llvm
List of target independent CodeGen pass IDs.
Enumerations
enum jit_actions_t { JIT_NOACTION = 0, JIT_REGISTER_FN, JIT_UNREGISTER_FN }
Functions
LLVM_ATTRIBUTE_NOINLINE void __jit_debug_register_code ()
Variables
struct jit_descriptor __jit_debug_descriptor = { 1, 0, 0, 0 }
Enumeration Type Documentation
enum jit_actions_t
Enumerator
JIT_NOACTION
JIT_REGISTER_FN
JIT_UNREGISTER_FN
Definition at line 22 of file GDBRegistrar.cpp.
Function Documentation
LLVM_ATTRIBUTE_NOINLINE void __jit_debug_register_code ()
Definition at line 50 of file GDBRegistrar.cpp.
References __jit_debug_descriptor, jit_descriptor::action_flag, jit_descriptor::first_entry, llvm::ObjectBuffer::getBufferSize(), llvm::ObjectBuffer::getBufferStart(), I, JIT_REGISTER_FN, JIT_UNREGISTER_FN, jit_code_entry::next_entry, jit_code_entry::prev_entry, jit_descriptor::relevant_entry, and llvm::report_fatal_error().
Variable Documentation
struct jit_descriptor __jit_debug_descriptor = { 1, 0, 0, 0 }
Definition at line 47 of file GDBRegistrar.cpp.
Referenced by __jit_debug_register_code().