LLVM: GlobalOpt.cpp File Reference
LLVM API Documentation
GlobalOpt.cpp File Reference
#include "llvm/Transforms/IPO.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/MemoryBuiltins.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/Pass.h"
#include "llvm/Support/CallSite.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/GetElementPtrTypeIterator.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Support/ValueHandle.h"
#include "llvm/Target/TargetLibraryInfo.h"
#include "llvm/Transforms/Utils/GlobalStatus.h"
#include "llvm/Transforms/Utils/ModuleUtils.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "globalopt"
Functions
STATISTIC (NumMarked,"Number of globals marked constant")
STATISTIC (NumUnnamed,"Number of globals marked unnamed_addr")
STATISTIC (NumSRA,"Number of aggregate globals broken into scalars")
STATISTIC (NumHeapSRA,"Number of heap objects SRA'd")
STATISTIC (NumSubstitute,"Number of globals with initializers stored into them")
STATISTIC (NumDeleted,"Number of globals deleted")
STATISTIC (NumFnDeleted,"Number of functions deleted")
STATISTIC (NumGlobUses,"Number of global uses devirtualized")
STATISTIC (NumLocalized,"Number of globals localized")
STATISTIC (NumShrunkToBool,"Number of global vars shrunk to booleans")
STATISTIC (NumFastCallFns,"Number of functions converted to fastcc")
STATISTIC (NumCtorsEvaluated,"Number of static ctors evaluated")
STATISTIC (NumNestRemoved,"Number of nest attributes removed")
STATISTIC (NumAliasesResolved,"Number of global aliases resolved")
STATISTIC (NumAliasesRemoved,"Number of global aliases eliminated")
STATISTIC (NumCXXDtorsRemoved,"Number of global C++ destructors removed")
INITIALIZE_PASS_BEGIN (GlobalOpt,"globalopt","Global Variable Optimizer", false, false) INITIALIZE_PASS_END(GlobalOpt
static bool isLeakCheckerRoot (GlobalVariable *GV)
static bool IsSafeComputationToRemove (Value *V, const TargetLibraryInfo *TLI)
static bool CleanupPointerRootUsers (GlobalVariable *GV, const TargetLibraryInfo *TLI)
static bool CleanupConstantGlobalUsers (Value *V, Constant *Init, DataLayout *TD, TargetLibraryInfo *TLI)
static bool isSafeSROAElementUse (Value *V)
static bool IsUserOfGlobalSafeForSRA (User *U, GlobalValue *GV)
static bool GlobalUsersSafeToSRA (GlobalValue *GV)
static GlobalVariable * SRAGlobal (GlobalVariable *GV, const DataLayout &TD)
static bool AllUsesOfValueWillTrapIfNull (const Value *V, SmallPtrSet< const PHINode *, 8 > &PHIs)
static bool AllUsesOfLoadedValueWillTrapIfNull (const GlobalVariable *GV)
static bool OptimizeAwayTrappingUsesOfValue (Value *V, Constant *NewV)
static bool OptimizeAwayTrappingUsesOfLoads (GlobalVariable *GV, Constant *LV, DataLayout *TD, TargetLibraryInfo *TLI)
static void ConstantPropUsersOf (Value *V, DataLayout *TD, TargetLibraryInfo *TLI)
static GlobalVariable * OptimizeGlobalAddressOfMalloc (GlobalVariable *GV, CallInst *CI, Type *AllocTy, ConstantInt *NElements, DataLayout *TD, TargetLibraryInfo *TLI)
static bool ValueIsOnlyUsedLocallyOrStoredToOneGlobal (const Instruction *V, const GlobalVariable *GV, SmallPtrSet< const PHINode *, 8 > &PHIs)
static void ReplaceUsesOfMallocWithGlobal (Instruction *Alloc, GlobalVariable *GV)
static bool LoadUsesSimpleEnoughForHeapSRA (const Value *V, SmallPtrSet< const PHINode *, 32 > &LoadUsingPHIs, SmallPtrSet< const PHINode *, 32 > &LoadUsingPHIsPerLoad)
static bool AllGlobalLoadUsesSimpleEnoughForHeapSRA (const GlobalVariable *GV, Instruction *StoredVal)
static Value * GetHeapSROAValue (Value *V, unsigned FieldNo, DenseMap< Value *, std::vector< Value * > > &InsertedScalarizedValues, std::vector< std::pair< PHINode *, unsigned > > &PHIsToRewrite)
static void RewriteHeapSROALoadUser (Instruction *LoadUser, DenseMap< Value *, std::vector< Value * > > &InsertedScalarizedValues, std::vector< std::pair< PHINode *, unsigned > > &PHIsToRewrite)
static void RewriteUsesOfLoadForHeapSRoA (LoadInst *Load, DenseMap< Value *, std::vector< Value * > > &InsertedScalarizedValues, std::vector< std::pair< PHINode *, unsigned > > &PHIsToRewrite)
static GlobalVariable * PerformHeapAllocSRoA (GlobalVariable *GV, CallInst *CI, Value *NElems, DataLayout *TD, const TargetLibraryInfo *TLI)
static bool TryToOptimizeStoreOfMallocToGlobal (GlobalVariable *GV, CallInst *CI, Type *AllocTy, AtomicOrdering Ordering, Module::global_iterator &GVI, DataLayout *TD, TargetLibraryInfo *TLI)
static bool OptimizeOnceStoredGlobal (GlobalVariable *GV, Value *StoredOnceVal, AtomicOrdering Ordering, Module::global_iterator &GVI, DataLayout *TD, TargetLibraryInfo *TLI)
static bool TryToShrinkGlobalToBoolean (GlobalVariable *GV, Constant *OtherVal)
static void ChangeCalleesToFastCall (Function *F)
static AttributeSet StripNest (LLVMContext &C, const AttributeSet &Attrs)
static void RemoveNestAttribute (Function *F)
static std::vector< Function * > ParseGlobalCtors (GlobalVariable *GV)
static GlobalVariable * InstallGlobalCtors (GlobalVariable *GCL, const std::vector< Function * > &Ctors)
static bool isSimpleEnoughValueToCommit (Constant *C, SmallPtrSet< Constant *, 8 > &SimpleConstants, const DataLayout *TD)
static bool isSimpleEnoughValueToCommitHelper (Constant *C, SmallPtrSet< Constant *, 8 > &SimpleConstants, const DataLayout *TD)
static bool isSimpleEnoughPointerToCommit (Constant *C)
static Constant * EvaluateStoreInto (Constant *Init, Constant *Val, ConstantExpr *Addr, unsigned OpNo)
static void CommitValueTo (Constant *Val, Constant *Addr)
static bool EvaluateStaticConstructor (Function *F, const DataLayout *TD, const TargetLibraryInfo *TLI)
static int compareNames (Constant *const *A, Constant *const *B)
static void setUsedInitializer (GlobalVariable &V, SmallPtrSet< GlobalValue *, 8 > Init)
static bool hasUseOtherThanLLVMUsed (GlobalAlias &GA, const LLVMUsed &U)
static bool hasMoreThanOneUseOtherThanLLVMUsed (GlobalValue &V, const LLVMUsed &U)
static bool mayHaveOtherReferences (GlobalAlias &GA, const LLVMUsed &U)
static bool hasUsesToReplace (GlobalAlias &GA, LLVMUsed &U, bool &RenameTarget)
static Function * FindCXAAtExit (Module &M, TargetLibraryInfo *TLI)
static bool cxxDtorIsEmpty (const Function &Fn, SmallPtrSet< const Function *, 8 > &CalledFunctions)
Variables
globalopt
Global Variable Optimizer
Global Variable false
Macro Definition Documentation
#define DEBUG_TYPE "globalopt"
Definition at line 16 of file GlobalOpt.cpp.
Function Documentation
static bool AllGlobalLoadUsesSimpleEnoughForHeapSRA (const GlobalVariable * GV, Instruction * StoredVal) static
AllGlobalLoadUsesSimpleEnoughForHeapSRA - If all users of values loaded from GV are simple enough to perform HeapSRA, return true.
Definition at line 1107 of file GlobalOpt.cpp.
References llvm::SmallPtrSet< PtrType, SmallSize >::begin(), llvm::SmallPtrSetImpl::clear(), llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::SmallPtrSet< PtrType, SmallSize >::end(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getNumIncomingValues(), I, LoadUsesSimpleEnoughForHeapSRA(), llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by TryToOptimizeStoreOfMallocToGlobal().
static bool AllUsesOfLoadedValueWillTrapIfNull (const GlobalVariable * GV) static
AllUsesOfLoadedValueWillTrapIfNull - Return true if all uses of any loads from GV will trap if the loaded value is null. Note that this also permits comparisons of the loaded value against null, as a special case.
Definition at line 657 of file GlobalOpt.cpp.
References AllUsesOfValueWillTrapIfNull(), llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by TryToOptimizeStoreOfMallocToGlobal().
static bool AllUsesOfValueWillTrapIfNull (const Value * V, SmallPtrSet< const PHINode *, 8 > & PHIs) static
AllUsesOfValueWillTrapIfNull - Return true if all users of the specified value will trap if the value is dynamically null. PHIs keeps track of any phi nodes we've seen to avoid reprocessing them.
Definition at line 611 of file GlobalOpt.cpp.
References llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by AllUsesOfLoadedValueWillTrapIfNull().
static void ChangeCalleesToFastCall (Function * F) static
ChangeCalleesToFastCall - Walk all of the direct calls of the specified function, changing them to FastCC.
Definition at line 1868 of file GlobalOpt.cpp.
References llvm::CallingConv::Fast, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setCallingConv(), llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by RemoveNestAttribute().
static bool CleanupConstantGlobalUsers (Value * V, Constant * Init, DataLayout * TD, TargetLibraryInfo * TLI) static
CleanupConstantGlobalUsers - We just marked GV constant. Loop over all users of the global, cleaning up the obvious ones. This is largely just a quick scan over the use list to clean up the easy and obvious cruft. This returns true if it made a change.
Definition at line 268 of file GlobalOpt.cpp.
References llvm::ConstantFoldInstruction(), llvm::ConstantFoldLoadThroughGEPConstantExpr(), llvm::Constant::getNullValue(), llvm::ConstantExpr::getOpcode(), llvm::isSafeToDestroyConstant(), llvm::A64CC::MI, llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by OptimizeAwayTrappingUsesOfLoads(), and TryToShrinkGlobalToBoolean().
static bool CleanupPointerRootUsers (GlobalVariable * GV, const TargetLibraryInfo * TLI) static
CleanupPointerRootUsers - This GV is a pointer root. Loop over all users of the global and clean up any that obviously don't assign the global a value that isn't dynamically allocated.
Definition at line 181 of file GlobalOpt.cpp.
References llvm::SmallVectorImpl< T >::clear(), llvm::RegState::Dead, llvm::dyn_cast(), llvm::Instruction::eraseFromParent(), llvm::GlobalVariable::eraseFromParent(), llvm::User::getOperand(), i, I, llvm::isAllocationFn(), llvm::GlobalVariable::isConstant(), IsSafeComputationToRemove(), llvm::isSafeToDestroyConstant(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by OptimizeAwayTrappingUsesOfLoads(), and TryToShrinkGlobalToBoolean().
static void CommitValueTo (Constant * Val, Constant * Addr) static
CommitValueTo - We have decided that Addr (which satisfies the predicate isSimpleEnoughPointerToCommit) should get Val as its value. Make it happen.
Definition at line 2251 of file GlobalOpt.cpp.
References llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_begin(), llvm::Function::arg_begin(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_end(), llvm::Function::arg_end(), llvm::BasicBlock::begin(), llvm::Function::begin(), llvm::Type::canLosslesslyBitCastTo(), llvm::ConstantFoldCall(), llvm::ConstantFoldConstantExpression(), llvm::ConstantFoldLoadThroughGEPConstantExpr(), llvm::dbgs(), DEBUG, llvm::DeleteContainerPointers(), llvm::dyn_cast(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), EvaluateStoreInto(), Evaluator, F(), llvm::IntegerType::get(), llvm::ConstantInt::get(), llvm::ConstantExpr::get(), llvm::UndefValue::get(), llvm::ConstantExpr::getBitCast(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledValue(), llvm::ConstantExpr::getCast(), llvm::ConstantExpr::getCompare(), llvm::Type::getContext(), llvm::Function::getFunctionType(), llvm::ConstantExpr::getGetElementPtr(), llvm::PHINode::getIncomingValueForBlock(), llvm::GlobalVariable::getInitializer(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getInstruction(), llvm::APInt::getLimitedValue(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::ConstantExpr::getSelect(), llvm::BasicBlock::getTerminator(), llvm::GlobalValue::getType(), llvm::Value::getType(), llvm::DataLayout::getTypeStoreSize(), llvm::ConstantInt::getValue(), llvm::ConstantInt::getZExtValue(), llvm::GlobalVariable::hasDefinitiveInitializer(), llvm::GlobalVariable::hasInitializer(), i, I, if(), llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::GlobalValue::InternalLinkage, llvm::Intrinsic::invariant_start, llvm::Constant::isAllOnesValue(), llvm::GlobalValue::isDeclaration(), isSimpleEnoughPointerToCommit(), isSimpleEnoughValueToCommit(), llvm::FunctionType::isVarArg(), llvm::Intrinsic::lifetime_end, llvm::Intrinsic::lifetime_start, llvm::GlobalValue::mayBeOverridden(), P, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::GlobalVariable::setInitializer(), llvm::Value::stripPointerCasts(), and llvm::Value::use_empty().
Referenced by EvaluateStaticConstructor().
static int compareNames (Constant *const * A, Constant *const * B) static
Definition at line 2848 of file GlobalOpt.cpp.
Referenced by setUsedInitializer().
static void ConstantPropUsersOf (Value * V, DataLayout * TD, TargetLibraryInfo * TLI) static
ConstantPropUsersOf - Walk the use list of V, constant folding all of the instructions that are foldable.
Definition at line 808 of file GlobalOpt.cpp.
References llvm::ConstantFoldInstruction(), I, llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by OptimizeGlobalAddressOfMalloc().
static bool cxxDtorIsEmpty (const Function & Fn, SmallPtrSet< const Function *, 8 > & CalledFunctions) static
cxxDtorIsEmpty - Returns whether the given function is an empty C++ destructor and can therefore be eliminated. Note that we assume that other optimization passes have already simplified the code so we only look for a function with a single basic block, where the only allowed instructions are 'ret', 'call' to an empty C++ dtor and other side-effect free instructions.
Definition at line 3068 of file GlobalOpt.cpp.
References llvm::BasicBlock::begin(), llvm::Function::begin(), llvm::dyn_cast(), llvm::BasicBlock::end(), llvm::Function::end(), llvm::Instruction::eraseFromParent(), FindCXAAtExit(), llvm::CallInst::getArgOperand(), llvm::Function::getEntryBlock(), llvm::Constant::getNullValue(), llvm::Value::getType(), I, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::GlobalValue::isDeclaration(), llvm::Value::replaceAllUsesWith(), llvm::Value::stripPointerCasts(), llvm::Value::use_begin(), and llvm::Value::use_end().
static bool EvaluateStaticConstructor (Function * F, const DataLayout * TD, const TargetLibraryInfo * TLI) static
EvaluateStaticConstructor - Evaluate static constructors in the function, if we can. Return true if we can, false otherwise.
Definition at line 2782 of file GlobalOpt.cpp.
References CommitValueTo(), llvm::dbgs(), DEBUG, llvm::Function::empty(), llvm::Eval(), Evaluator, llvm::Value::getName(), i, I, InstallGlobalCtors(), and ParseGlobalCtors().
static Constant* EvaluateStoreInto (Constant * Init, Constant * Val, ConstantExpr * Addr, unsigned OpNo) static
EvaluateStoreInto - Evaluate a piece of a constantexpr store into a global initializer. This returns 'Init' modified to reflect 'Val' stored into it. At this point, the GEP operands of Addr [0, OpNo) have been stepped into.
Definition at line 2203 of file GlobalOpt.cpp.
References llvm::ConstantArray::get(), llvm::ConstantStruct::get(), llvm::ConstantVector::get(), llvm::Constant::getAggregateElement(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Value::getType(), llvm::Type::getVectorNumElements(), llvm::ConstantInt::getZExtValue(), i, llvm::Type::isArrayTy(), and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by CommitValueTo().
static Function* FindCXAAtExit (Module & M, TargetLibraryInfo * TLI) static
Definition at line 3039 of file GlobalOpt.cpp.
References llvm::LibFunc::cxa_atexit, llvm::Module::getFunction(), llvm::Function::getFunctionType(), llvm::TargetLibraryInfo::getName(), llvm::FunctionType::getNumParams(), llvm::FunctionType::getParamType(), llvm::FunctionType::getReturnType(), llvm::TargetLibraryInfo::has(), llvm::Type::isIntegerTy(), and llvm::Type::isPointerTy().
Referenced by cxxDtorIsEmpty().
static Value* GetHeapSROAValue (Value * V, unsigned FieldNo, DenseMap< Value *, std::vector< Value * > > & InsertedScalarizedValues, std::vector< std::pair< PHINode *, unsigned > > & PHIsToRewrite) static
Definition at line 1156 of file GlobalOpt.cpp.
References llvm::PHINode::Create(), llvm::StructType::getElementType(), llvm::PointerType::getUnqual(), llvm_unreachable, and llvm::A64DB::ST.
Referenced by PerformHeapAllocSRoA(), and RewriteHeapSROALoadUser().
static bool GlobalUsersSafeToSRA (GlobalValue * GV) static
GlobalUsersSafeToSRA - Look at all uses of the global and decide whether it is safe for us to perform this transformation.
Definition at line 454 of file GlobalOpt.cpp.
References IsUserOfGlobalSafeForSRA(), llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by SRAGlobal().
static bool hasMoreThanOneUseOtherThanLLVMUsed (GlobalValue & V, const LLVMUsed & U) static
Definition at line 2933 of file GlobalOpt.cpp.
References llvm::Value::hasNUsesOrMore(), and N.
Referenced by hasUsesToReplace().
static bool hasUseOtherThanLLVMUsed (GlobalAlias & GA, const LLVMUsed & U) static
Definition at line 2917 of file GlobalOpt.cpp.
References llvm::Value::hasOneUse(), and llvm::Value::use_empty().
Referenced by hasUsesToReplace().
static bool hasUsesToReplace (GlobalAlias & GA, LLVMUsed & U, bool & RenameTarget) static
Definition at line 2951 of file GlobalOpt.cpp.
References llvm::Module::alias_begin(), llvm::Module::alias_end(), llvm::iplist< NodeTy, Traits >::erase(), llvm::GlobalAlias::getAliasee(), llvm::Module::getAliasList(), llvm::GlobalValue::hasLocalLinkage(), hasMoreThanOneUseOtherThanLLVMUsed(), hasUseOtherThanLLVMUsed(), I, llvm::GlobalValue::InternalLinkage, mayHaveOtherReferences(), llvm::Constant::removeDeadConstantUsers(), llvm::AArch64ISD::Ret, llvm::GlobalValue::setLinkage(), llvm::Value::stripPointerCasts(), and llvm::Value::takeName().
INITIALIZE_PASS_BEGIN (GlobalOpt , "globalopt" , "Global Variable Optimizer" , false , false)
static GlobalVariable* InstallGlobalCtors (GlobalVariable * GCL, const std::vector< Function * > & Ctors) static
InstallGlobalCtors - Given a specified llvm.global_ctors list, install the specified array, returning the new global to use.
Definition at line 2010 of file GlobalOpt.cpp.
References llvm::GlobalVariable::eraseFromParent(), llvm::ConstantInt::get(), llvm::FunctionType::get(), llvm::ArrayType::get(), llvm::ConstantArray::get(), llvm::ConstantStruct::get(), llvm::Type::getArrayElementType(), llvm::ConstantExpr::getBitCast(), llvm::Value::getContext(), llvm::SequentialType::getElementType(), llvm::Module::getGlobalList(), llvm::GlobalVariable::getInitializer(), llvm::Type::getInt32Ty(), llvm::GlobalValue::getLinkage(), llvm::Constant::getNullValue(), llvm::GlobalValue::getParent(), llvm::GlobalVariable::getThreadLocalMode(), llvm::GlobalValue::getType(), llvm::Value::getType(), llvm::PointerType::getUnqual(), llvm::Type::getVoidTy(), i, llvm::iplist< NodeTy, Traits >::insert(), llvm::GlobalVariable::isConstant(), isSimpleEnoughValueToCommit(), llvm::Value::replaceAllUsesWith(), llvm::GlobalVariable::setInitializer(), llvm::Value::takeName(), and llvm::Value::use_empty().
Referenced by EvaluateStaticConstructor().
static bool isLeakCheckerRoot (GlobalVariable * GV) static
isLeakCheckerRoot - Is this global variable possibly used by a leak checker as a root? If so, we might not really want to eliminate the stores to it.
Definition at line 103 of file GlobalOpt.cpp.
References llvm::Type::ArrayTyID, llvm::StructType::element_begin(), llvm::StructType::element_end(), llvm::SmallVectorBase::empty(), llvm::SequentialType::getElementType(), llvm::GlobalValue::getType(), llvm::Type::getTypeID(), llvm::GlobalValue::hasPrivateLinkage(), I, llvm::StructType::isOpaque(), llvm::Type::PointerTyID, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::Type::StructTyID, and llvm::Type::VectorTyID.
Referenced by OptimizeAwayTrappingUsesOfLoads(), and TryToShrinkGlobalToBoolean().
static bool IsSafeComputationToRemove (Value * V, const TargetLibraryInfo * TLI) static
Given a value that is stored to a global but never read, determine whether it's safe to remove the store and the chain of computation that feeds the store.
Definition at line 151 of file GlobalOpt.cpp.
References llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Value::hasOneUse(), I, llvm::isAllocationFn(), and llvm::Instruction::mayHaveSideEffects().
Referenced by CleanupPointerRootUsers().
static bool isSafeSROAElementUse (Value * V) static
isSafeSROAElementUse - Return true if the specified instruction is a safe user of a derived expression from a global that we want to SROA.
Definition at line 354 of file GlobalOpt.cpp.
References llvm::dyn_cast(), llvm::User::getNumOperands(), llvm::User::getOperand(), I, llvm::isSafeToDestroyConstant(), llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by IsUserOfGlobalSafeForSRA().
static bool isSimpleEnoughPointerToCommit (Constant * C) static
isSimpleEnoughPointerToCommit - Return true if this constant is simple enough for us to understand. In particular, if it is a cast to anything other than from one pointer type to another pointer type, we punt. We basically just support direct accesses to globals and GEP's of globals. This should be kept up to date with CommitValueTo.
Definition at line 2153 of file GlobalOpt.cpp.
References llvm::ConstantFoldLoadThroughGEPConstantExpr(), llvm::dyn_cast(), llvm::GlobalVariable::getInitializer(), llvm::Value::getType(), llvm::GlobalVariable::hasUniqueInitializer(), llvm::ConstantInt::isZero(), and llvm::next().
Referenced by CommitValueTo().
static bool isSimpleEnoughValueToCommit (Constant * C, SmallPtrSet< Constant *, 8 > & SimpleConstants, const DataLayout * TD) inline static
Definition at line 2138 of file GlobalOpt.cpp.
References llvm::SmallPtrSet< PtrType, SmallSize >::insert(), and isSimpleEnoughValueToCommitHelper().
Referenced by CommitValueTo(), InstallGlobalCtors(), and isSimpleEnoughValueToCommitHelper().
static bool isSimpleEnoughValueToCommitHelper (Constant * C, SmallPtrSet< Constant *, 8 > & SimpleConstants, const DataLayout * TD) static
isSimpleEnoughValueToCommit - Return true if the specified constant can be handled by the code generator. We don't want to generate something like: void *X = &X/42; because the code generator doesn't have a relocation that can handle that.
This function should be called if C was not found (but just got inserted) in SimpleConstants to avoid having to rescan the same constants all the time.
Definition at line 2083 of file GlobalOpt.cpp.
References llvm::User::getNumOperands(), llvm::ConstantExpr::getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm::DataLayout::getTypeSizeInBits(), i, and isSimpleEnoughValueToCommit().
Referenced by isSimpleEnoughValueToCommit().
static bool IsUserOfGlobalSafeForSRA (User * U, GlobalValue * GV) static
IsUserOfGlobalSafeForSRA - U is a direct user of the specified global value. Look at it and its uses and decide whether it is safe to SROA this global.
Definition at line 388 of file GlobalOpt.cpp.
References llvm::dyn_cast(), llvm::gep_type_begin(), llvm::gep_type_end(), llvm::User::getNumOperands(), llvm::generic_gep_type_iterator< ItTy >::getOperand(), llvm::User::getOperand(), llvm::ConstantInt::getZExtValue(), I, isSafeSROAElementUse(), llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by GlobalUsersSafeToSRA().
static bool LoadUsesSimpleEnoughForHeapSRA (const Value * V, SmallPtrSet< const PHINode *, 32 > & LoadUsingPHIs, SmallPtrSet< const PHINode *, 32 > & LoadUsingPHIsPerLoad) static
LoadUsesSimpleEnoughForHeapSRA - Verify that all uses of V (a load, or a phi of a load) are simple enough to perform heap SRA on. This permits GEP's that index through the array and struct field, icmps of null, and PHIs.
Definition at line 1054 of file GlobalOpt.cpp.
References llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by AllGlobalLoadUsesSimpleEnoughForHeapSRA().
static bool mayHaveOtherReferences (GlobalAlias & GA, const LLVMUsed & U) static
Definition at line 2944 of file GlobalOpt.cpp.
References llvm::GlobalValue::hasLocalLinkage().
Referenced by hasUsesToReplace().
static bool OptimizeAwayTrappingUsesOfLoads (GlobalVariable * GV, Constant * LV, DataLayout * TD, TargetLibraryInfo * TLI) static
OptimizeAwayTrappingUsesOfLoads - The specified global has only one non-null value stored into it. If there are uses of the loaded value that would trap if the loaded value is dynamically null, then we know that they cannot be reachable with a null optimize away the load.
Definition at line 744 of file GlobalOpt.cpp.
References CleanupConstantGlobalUsers(), CleanupPointerRootUsers(), llvm::dbgs(), DEBUG, llvm::GlobalVariable::eraseFromParent(), llvm::User::getOperand(), isLeakCheckerRoot(), OptimizeAwayTrappingUsesOfValue(), llvm::Value::use_begin(), llvm::Value::use_empty(), and llvm::Value::use_end().
Referenced by OptimizeOnceStoredGlobal().
static bool OptimizeAwayTrappingUsesOfValue (Value * V, Constant * NewV) static
Definition at line 677 of file GlobalOpt.cpp.
References llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_size(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getArgument(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledValue(), llvm::ConstantExpr::getCast(), llvm::ConstantExpr::getGetElementPtr(), llvm::Value::getType(), i, I, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorImpl< T >::reserve(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setArgument(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setCalledFunction(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by OptimizeAwayTrappingUsesOfLoads().
static GlobalVariable* OptimizeGlobalAddressOfMalloc (GlobalVariable * GV, CallInst * CI, Type * AllocTy, ConstantInt * NElements, DataLayout * TD, TargetLibraryInfo * TLI) static
OptimizeGlobalAddressOfMalloc - This function takes the specified global variable, and transforms the program as if it always contained the result of the specified malloc. Because it is always the result of the specified malloc, there is no reason to actually DO the malloc. Instead, turn the malloc into a global, and any loads of GV as uses of the new global.
Definition at line 828 of file GlobalOpt.cpp.
References ConstantPropUsersOf(), llvm::BinaryOperator::CreateNot(), DEBUG, llvm::Instruction::eraseFromParent(), llvm::GlobalVariable::eraseFromParent(), llvm::errs(), llvm::ArrayType::get(), llvm::UndefValue::get(), llvm::ConstantExpr::getBitCast(), llvm::Value::getContext(), llvm::SequentialType::getElementType(), llvm::ConstantInt::getFalse(), llvm::Module::getGlobalList(), llvm::Type::getInt1Ty(), llvm::Value::getName(), llvm::LoadInst::getOrdering(), llvm::GlobalValue::getParent(), llvm::CmpInst::getPredicate(), llvm::LoadInst::getSynchScope(), llvm::GlobalVariable::getThreadLocalMode(), llvm::ConstantInt::getTrue(), llvm::GlobalValue::getType(), llvm::Value::getType(), llvm::value_use_iterator< UserTy >::getUse(), llvm::Use::getUser(), llvm::ConstantInt::getZExtValue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::iplist< NodeTy, Traits >::insert(), llvm::GlobalValue::InternalLinkage, llvm::LoadInst::isUnordered(), llvm_unreachable, llvm::Value::replaceAllUsesWith(), llvm::User::replaceUsesOfWith(), llvm::Instruction::use_back(), llvm::Value::use_back(), llvm::Value::use_begin(), and llvm::Value::use_empty().
Referenced by TryToOptimizeStoreOfMallocToGlobal().
static bool OptimizeOnceStoredGlobal (GlobalVariable * GV, Value * StoredOnceVal, AtomicOrdering Ordering, Module::global_iterator & GVI, DataLayout * TD, TargetLibraryInfo * TLI) static
Definition at line 1568 of file GlobalOpt.cpp.
References llvm::extractMallocCall(), llvm::ConstantExpr::getBitCast(), llvm::GlobalVariable::getInitializer(), llvm::getMallocAllocatedType(), llvm::Value::getType(), llvm::Constant::isNullValue(), llvm::Type::isPointerTy(), OptimizeAwayTrappingUsesOfLoads(), llvm::Value::stripPointerCasts(), and TryToOptimizeStoreOfMallocToGlobal().
Referenced by TryToShrinkGlobalToBoolean().
static std::vector<Function*> ParseGlobalCtors (GlobalVariable * GV) static
ParseGlobalCtors - Given a llvm.global_ctors list that we can understand, return a list of the functions and null terminator as a vector.
Definition at line 1995 of file GlobalOpt.cpp.
References llvm::GlobalVariable::getInitializer(), llvm::User::getNumOperands(), llvm::User::getOperand(), i, llvm::Constant::isNullValue(), llvm::User::op_begin(), and llvm::User::op_end().
Referenced by EvaluateStaticConstructor().
static GlobalVariable* PerformHeapAllocSRoA (GlobalVariable * GV, CallInst * CI, Value * NElems, DataLayout * TD, const TargetLibraryInfo * TLI) static
PerformHeapAllocSRoA - CI is an allocation of an array of structures. Break it up into multiple allocations of arrays of the fields.
InsertedScalarizedLoads - As we process loads, if we can't immediately update all uses of the load, keep track of what scalarized loads are inserted for a given load.
Definition at line 1279 of file GlobalOpt.cpp.
References llvm::PHINode::addIncoming(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::begin(), llvm::BasicBlock::Create(), llvm::BranchInst::Create(), llvm::CallInst::CreateFree(), llvm::CallInst::CreateMalloc(), llvm::dbgs(), DEBUG, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), llvm::Instruction::eraseFromParent(), llvm::GlobalVariable::eraseFromParent(), llvm::ConstantInt::get(), llvm::CallInst::getArgOperand(), llvm::BasicBlock::getContext(), llvm::Value::getContext(), llvm::StructType::getElementType(), llvm::SequentialType::getElementType(), GetHeapSROAValue(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::DataLayout::getIntPtrType(), llvm::getMallocAllocatedType(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::StructType::getNumElements(), llvm::PHINode::getNumIncomingValues(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::StructLayout::getSizeInBytes(), llvm::DataLayout::getStructLayout(), llvm::BasicBlock::getTerminator(), llvm::GlobalVariable::getThreadLocalMode(), llvm::Intrinsic::getType(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::PointerType::getUnqual(), i, I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SLT, llvm::GlobalValue::InternalLinkage, ReplaceUsesOfMallocWithGlobal(), RewriteUsesOfLoadForHeapSRoA(), llvm::BasicBlock::splitBasicBlock(), llvm::A64DB::ST, llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by TryToOptimizeStoreOfMallocToGlobal().
static void RemoveNestAttribute (Function * F) static
Definition at line 1890 of file GlobalOpt.cpp.
References llvm::Module::begin(), llvm::CallingConv::C, ChangeCalleesToFastCall(), llvm::ConstantFoldConstantExpression(), llvm::Module::end(), llvm::Function::eraseFromParent(), F(), llvm::CallingConv::Fast, llvm::Function::getAttributes(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getAttributes(), llvm::Function::getCallingConv(), llvm::Function::getContext(), llvm::Module::getGlobalVariable(), llvm::GlobalVariable::getInitializer(), llvm::User::getOperand(), llvm::ConstantInt::getZExtValue(), llvm::Module::global_begin(), llvm::Module::global_end(), llvm::Function::hasAddressTaken(), llvm::AttributeSet::hasAttrSomewhere(), llvm::GlobalVariable::hasInitializer(), llvm::GlobalValue::hasLocalLinkage(), llvm::Value::hasName(), llvm::GlobalVariable::hasUniqueInitializer(), i, llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::isDeclaration(), llvm::Function::isDefTriviallyDead(), llvm::Function::isVarArg(), M, llvm::Attribute::Nest, llvm::User::op_begin(), llvm::User::op_end(), llvm::Constant::removeDeadConstantUsers(), llvm::Function::setAttributes(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setAttributes(), llvm::Function::setCallingConv(), llvm::GlobalVariable::setInitializer(), llvm::GlobalValue::setLinkage(), StripNest(), llvm::Value::use_begin(), and llvm::Value::use_end().
static void ReplaceUsesOfMallocWithGlobal (Instruction * Alloc, GlobalVariable * GV) static
ReplaceUsesOfMallocWithGlobal - The Alloc pointer is stored into GV somewhere. Transform all uses of the allocation into loads from the global and uses of the resultant pointer. Further, delete the store into GV. This assumes that these value pass the 'ValueIsOnlyUsedLocallyOrStoredToOneGlobal' predicate.
Definition at line 1011 of file GlobalOpt.cpp.
References llvm::Instruction::eraseFromParent(), llvm::Value::getName(), llvm::User::replaceUsesOfWith(), llvm::Value::use_begin(), and llvm::Value::use_empty().
Referenced by PerformHeapAllocSRoA().
static void RewriteHeapSROALoadUser (Instruction * LoadUser, DenseMap< Value *, std::vector< Value * > > & InsertedScalarizedValues, std::vector< std::pair< PHINode *, unsigned > > & PHIsToRewrite) static
RewriteHeapSROALoadUser - Given a load instruction and a value derived from the load, rewrite the derived value to use the HeapSRoA'd load.
Definition at line 1198 of file GlobalOpt.cpp.
References llvm::GetElementPtrInst::Create(), GetHeapSROAValue(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by RewriteUsesOfLoadForHeapSRoA().
static void RewriteUsesOfLoadForHeapSRoA (LoadInst * Load, DenseMap< Value *, std::vector< Value * > > & InsertedScalarizedValues, std::vector< std::pair< PHINode *, unsigned > > & PHIsToRewrite) static
RewriteUsesOfLoadForHeapSRoA - We are performing Heap SRoA on a global. Ptr is a value loaded from the global. Eliminate all uses of Ptr, making them use FieldGlobals instead. All uses of loaded values satisfy AllGlobalLoadUsesSimpleEnoughForHeapSRA.
Definition at line 1262 of file GlobalOpt.cpp.
References llvm::Instruction::eraseFromParent(), RewriteHeapSROALoadUser(), llvm::Value::use_begin(), llvm::Value::use_empty(), and llvm::Value::use_end().
Referenced by PerformHeapAllocSRoA().
static void setUsedInitializer (GlobalVariable & V, SmallPtrSet< GlobalValue *, 8 > Init) static
Definition at line 2852 of file GlobalOpt.cpp.
References llvm::GlobalValue::AppendingLinkage, llvm::array_pod_sort(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::SmallPtrSet< PtrType, SmallSize >::begin(), llvm::collectUsedGlobalVariables(), compareNames(), llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::SmallPtrSetImpl::empty(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::SmallPtrSet< PtrType, SmallSize >::end(), llvm::SmallPtrSet< PtrType, SmallSize >::erase(), llvm::GlobalVariable::eraseFromParent(), llvm::ArrayType::get(), llvm::ConstantArray::get(), llvm::ConstantExpr::getBitCast(), llvm::Value::getContext(), llvm::Type::getInt8PtrTy(), llvm::GlobalValue::getParent(), I, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::A64CC::NV, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::GlobalVariable::removeFromParent(), llvm::GlobalValue::setSection(), llvm::SmallVectorTemplateCommon< T >::size(), and llvm::Value::takeName().
static GlobalVariable* SRAGlobal (GlobalVariable * GV, const DataLayout & TD) static
SRAGlobal - Perform scalar replacement of aggregates on the specified global variable. This opens the door for other optimizations by exposing the behavior of the program in a more fine-grained way. We have determined that this transformation is safe already. We return the first global variable we insert so that the caller can reprocess it.
Definition at line 469 of file GlobalOpt.cpp.
References llvm::GetElementPtrInst::Create(), llvm::dbgs(), DEBUG, llvm::iplist< NodeTy, Traits >::erase(), llvm::DataLayout::getABITypeAlignment(), llvm::PointerType::getAddressSpace(), llvm::GlobalValue::getAlignment(), llvm::Value::getContext(), llvm::StructLayout::getElementOffset(), llvm::ConstantExpr::getGetElementPtr(), llvm::Module::getGlobalList(), llvm::GlobalVariable::getInitializer(), llvm::Type::getInt32Ty(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::GlobalValue::getParent(), llvm::DataLayout::getStructLayout(), llvm::GlobalVariable::getThreadLocalMode(), llvm::GlobalValue::getType(), llvm::DataLayout::getTypeAllocSize(), GlobalUsersSafeToSRA(), llvm::GlobalValue::hasLocalLinkage(), llvm::Value::hasNUsesOrMore(), i, llvm::tgtok::In, llvm::iplist< NodeTy, Traits >::insert(), llvm::GlobalValue::InternalLinkage, llvm::GlobalVariable::isConstant(), llvm::MinAlign(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::GlobalValue::setAlignment(), llvm::Value::use_back(), and llvm::Value::use_empty().
Referenced by TryToShrinkGlobalToBoolean().
STATISTIC (NumMarked , "Number of globals marked constant")
STATISTIC (NumUnnamed , "Number of globals marked unnamed_addr")
STATISTIC (NumSRA , "Number of aggregate globals broken into scalars")
STATISTIC (NumHeapSRA , "Number of heap objects SRA'd")
STATISTIC (NumSubstitute , "Number of globals with initializers stored into them")
STATISTIC (NumDeleted , "Number of globals deleted")
STATISTIC (NumFnDeleted , "Number of functions deleted")
STATISTIC (NumGlobUses , "Number of global uses devirtualized")
STATISTIC (NumLocalized , "Number of globals localized")
STATISTIC (NumShrunkToBool , "Number of global vars shrunk to booleans")
STATISTIC (NumFastCallFns , "Number of functions converted to fastcc")
STATISTIC (NumCtorsEvaluated , "Number of static ctors evaluated")
STATISTIC (NumNestRemoved , "Number of nest attributes removed")
STATISTIC (NumAliasesResolved , "Number of global aliases resolved")
STATISTIC (NumAliasesRemoved , "Number of global aliases eliminated")
STATISTIC (NumCXXDtorsRemoved , "Number of global C++ destructors removed")
static AttributeSet StripNest (LLVMContext & C, const AttributeSet & Attrs) static
Definition at line 1877 of file GlobalOpt.cpp.
References llvm::AttributeSet::getNumSlots(), llvm::AttributeSet::getSlotAttributes(), llvm::AttributeSet::getSlotIndex(), llvm::AttributeSet::hasAttribute(), i, llvm::Attribute::Nest, and llvm::AttributeSet::removeAttribute().
Referenced by RemoveNestAttribute().
static bool TryToOptimizeStoreOfMallocToGlobal (GlobalVariable * GV, CallInst * CI, Type * AllocTy, AtomicOrdering Ordering, Module::global_iterator & GVI, DataLayout * TD, TargetLibraryInfo * TLI) static
TryToOptimizeStoreOfMallocToGlobal - This function is called when we see a pointer global variable with a single value stored it that is a malloc or cast of malloc.
Definition at line 1467 of file GlobalOpt.cpp.
References AllGlobalLoadUsesSimpleEnoughForHeapSRA(), AllUsesOfLoadedValueWillTrapIfNull(), llvm::CallInst::CreateMalloc(), llvm::dyn_cast(), llvm::Instruction::eraseFromParent(), llvm::ConstantInt::get(), llvm::CallInst::getArgOperand(), llvm::DataLayout::getIntPtrType(), llvm::getMallocAllocatedType(), llvm::getMallocArraySize(), llvm::Value::getName(), llvm::StructType::getNumElements(), llvm::StructLayout::getSizeInBytes(), llvm::DataLayout::getStructLayout(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::Type::isSized(), llvm::NotAtomic, OptimizeGlobalAddressOfMalloc(), PerformHeapAllocSRoA(), llvm::Value::replaceAllUsesWith(), and ValueIsOnlyUsedLocallyOrStoredToOneGlobal().
Referenced by OptimizeOnceStoredGlobal().
static bool TryToShrinkGlobalToBoolean (GlobalVariable * GV, Constant * OtherVal) static
TryToShrinkGlobalToBoolean - At this point, we have learned that the only two values ever stored into GV are its initializer and OtherVal. See if we can shrink the global into a boolean and select between the two values whenever it is used. This exposes the values to other scalar optimizations.
Definition at line 1604 of file GlobalOpt.cpp.
References llvm::GlobalStatus::AccessingFunction, llvm::GlobalStatus::analyzeGlobal(), llvm::BasicBlock::begin(), CleanupConstantGlobalUsers(), CleanupPointerRootUsers(), llvm::SelectInst::Create(), llvm::dbgs(), DEBUG, llvm::Instruction::eraseFromParent(), llvm::GlobalVariable::eraseFromParent(), llvm::ConstantInt::get(), llvm::PointerType::getAddressSpace(), llvm::Value::getContext(), llvm::SequentialType::getElementType(), llvm::Function::getEntryBlock(), llvm::ConstantInt::getFalse(), llvm::Module::getGlobalList(), llvm::GlobalVariable::getInitializer(), llvm::Type::getInt1Ty(), llvm::Value::getName(), llvm::User::getOperand(), llvm::LoadInst::getOrdering(), llvm::GlobalValue::getParent(), llvm::LoadInst::getSynchScope(), llvm::GlobalVariable::getThreadLocalMode(), llvm::GlobalValue::getType(), llvm::Value::getType(), llvm::X86II::GS, llvm::GlobalValue::hasExternalLinkage(), llvm::GlobalVariable::hasInitializer(), llvm::GlobalValue::hasLocalLinkage(), llvm::GlobalStatus::HasMultipleAccessingFunctions, llvm::GlobalStatus::HasNonInstructionUser, llvm::GlobalValue::hasUnnamedAddr(), I, llvm::GlobalStatus::InitializerStored, llvm::iplist< NodeTy, Traits >::insert(), llvm::GlobalValue::InternalLinkage, llvm::GlobalStatus::IsCompared, llvm::GlobalVariable::isConstant(), llvm::GlobalValue::isDiscardableIfUnused(), llvm::Type::isFloatingPointTy(), isLeakCheckerRoot(), llvm::GlobalStatus::IsLoaded, llvm::Constant::isNullValue(), llvm::Type::isPointerTy(), llvm::Type::isSingleValueType(), llvm::Type::isVectorTy(), llvm::NotAtomic, OptimizeOnceStoredGlobal(), llvm::GlobalStatus::Ordering, llvm::Constant::removeDeadConstantUsers(), llvm::Value::replaceAllUsesWith(), llvm::GlobalVariable::setConstant(), llvm::GlobalVariable::setInitializer(), llvm::GlobalValue::setUnnamedAddr(), SRAGlobal(), llvm::GlobalStatus::StoredOnce, llvm::GlobalStatus::StoredOnceValue, llvm::Value::takeName(), llvm::Value::use_back(), llvm::Value::use_begin(), llvm::Value::use_empty(), and llvm::Value::use_end().
static bool ValueIsOnlyUsedLocallyOrStoredToOneGlobal (const Instruction * V, const GlobalVariable * GV, SmallPtrSet< const PHINode *, 8 > & PHIs) static
ValueIsOnlyUsedLocallyOrStoredToOneGlobal - Scan the use-list of V checking to make sure that there are no complex uses of V. We permit simple things like dereferencing the pointer, but not storing through the address, unless it is to the specified global.
Definition at line 962 of file GlobalOpt.cpp.
References llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by TryToOptimizeStoreOfMallocToGlobal().
Variable Documentation
Global Variable false
Definition at line 96 of file GlobalOpt.cpp.
globalopt
Definition at line 96 of file GlobalOpt.cpp.
Global Variable Optimizer
Definition at line 96 of file GlobalOpt.cpp.