LLVM: GlobalMerge.cpp File Reference
LLVM API Documentation
GlobalMerge.cpp File Reference
#include "llvm/Transforms/Scalar.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
Macros
#define DEBUG_TYPE "global-merge"
Functions
STATISTIC (NumMerged,"Number of globals merged")
INITIALIZE_PASS (GlobalMerge,"global-merge","Global Merge", false, false) bool GlobalMerge
Variables
static cl::opt< bool > EnableGlobalMergeOnConst ("global-merge-on-const", cl::Hidden, cl::desc("Enable global merge pass on constants"), cl::init(false))
Macro Definition Documentation
#define DEBUG_TYPE "global-merge"
Definition at line 54 of file GlobalMerge.cpp.
Function Documentation
INITIALIZE_PASS (GlobalMerge , "global-merge" , "Global Merge" , false , false)
Definition at line 139 of file GlobalMerge.cpp.
References llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::begin(), llvm::Module::begin(), llvm::SmallPtrSetImpl::clear(), llvm::collectUsedGlobalVariables(), llvm::dyn_cast(), EnableGlobalMergeOnConst, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), llvm::Module::end(), F(), G, llvm::ConstantInt::get(), llvm::StructType::get(), llvm::ConstantStruct::get(), llvm::DataLayout::getABITypeAlignment(), llvm::PointerType::getAddressSpace(), llvm::LandingPadInst::getClause(), llvm::TargetLoweringBase::getDataLayout(), llvm::Module::getGlobalVariable(), llvm::ConstantExpr::getInBoundsGetElementPtr(), llvm::GlobalVariable::getInitializer(), llvm::Type::getInt32Ty(), llvm::TargetLoweringObjectFile::getKindForGlobal(), llvm::BasicBlock::getLandingPadInst(), llvm::TargetLoweringBase::getMaximalGlobalOffset(), llvm::LandingPadInst::getNumClauses(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::DataLayout::getPreferredAlignment(), llvm::TargetMachine::getTargetLowering(), llvm::TargetLoweringBase::getTargetMachine(), llvm::DataLayout::getTypeAllocSize(), llvm::InvokeInst::getUnwindDest(), llvm::Module::global_begin(), llvm::Module::global_end(), llvm::GlobalVariable::hasInitializer(), i, I, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::GlobalValue::InternalLinkage, j(), M, llvm::GlobalVariable::NotThreadLocal, and llvm::Value::stripPointerCasts().
STATISTIC (NumMerged , "Number of globals merged")
Variable Documentation
cl::opt<bool> EnableGlobalMergeOnConst("global-merge-on-const", cl::Hidden, cl::desc("Enable global merge pass on constants"), cl::init(false)) static
Referenced by INITIALIZE_PASS().