LLVM: GlobalDCE.cpp File Reference
LLVM API Documentation
GlobalDCE.cpp File Reference
#include "llvm/Transforms/IPO.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
Macros
#define DEBUG_TYPE "globaldce"
Functions
STATISTIC (NumAliases,"Number of global aliases removed")
STATISTIC (NumFunctions,"Number of functions removed")
STATISTIC (NumVariables,"Number of global variables removed")
INITIALIZE_PASS (GlobalDCE,"globaldce","Dead Global Elimination", false, false) ModulePass *llvm
Macro Definition Documentation
#define DEBUG_TYPE "globaldce"
Definition at line 18 of file GlobalDCE.cpp.
Function Documentation
INITIALIZE_PASS (GlobalDCE , "globaldce" , "Dead Global Elimination" , false , false)
Definition at line 57 of file GlobalDCE.cpp.
References llvm::Module::alias_begin(), llvm::Module::alias_end(), BB, llvm::Function::begin(), llvm::Module::begin(), llvm::dyn_cast(), llvm::Function::end(), llvm::Module::end(), llvm::iplist< NodeTy, Traits >::erase(), F(), G, llvm::Module::getAliasList(), llvm::Module::getFunctionList(), llvm::Module::getGlobalList(), llvm::Function::getPrefixData(), llvm::Module::global_begin(), llvm::Module::global_end(), llvm::Function::hasPrefixData(), i, I, M, llvm::User::op_begin(), llvm::User::op_end(), llvm::Constant::removeDeadConstantUsers(), and llvm::Value::use_empty().
STATISTIC (NumAliases , "Number of global aliases removed")
STATISTIC (NumFunctions , "Number of functions removed")
STATISTIC (NumVariables , "Number of global variables removed")