LLVM: GraphWriter.cpp File Reference
LLVM API Documentation
GraphWriter.cpp File Reference
#include "llvm/Support/GraphWriter.h"
#include "llvm/Config/config.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/Program.h"
Functions
static bool LLVM_ATTRIBUTE_UNUSED ExecGraphViewer (StringRef ExecPath, std::vector< const char * > &args, StringRef Filename, bool wait, std::string &ErrMsg)
Variables
static cl::opt< bool > ViewBackground ("view-background", cl::Hidden, cl::desc("Execute graph viewer in the background. Creates tmp file litter."))
Function Documentation
static bool LLVM_ATTRIBUTE_UNUSED ExecGraphViewer (StringRef ExecPath, std::vector< const char * > & args, StringRef Filename, bool wait, std::string & ErrMsg) static
Definition at line 83 of file GraphWriter.cpp.
References llvm::errs(), llvm::sys::ExecuteAndWait(), llvm::sys::ExecuteNoWait(), llvm::sys::fs::remove(), and llvm::StringRef::str().
Referenced by llvm::DisplayGraph().
Variable Documentation
cl::opt<bool> ViewBackground("view-background", cl::Hidden, cl::desc("Execute graph viewer in the background. Creates tmp file litter.")) static
Referenced by llvm::DisplayGraph().