LLVM: HexagonVLIWPacketizer.cpp File Reference
LLVM API Documentation
HexagonVLIWPacketizer.cpp File Reference
#include "llvm/CodeGen/DFAPacketizer.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/ScheduleDAG.h"
#include "llvm/CodeGen/ScheduleDAGInstrs.h"
#include "llvm/CodeGen/LatencyPriorityQueue.h"
#include "llvm/CodeGen/SchedulerRegistry.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/MachineFunctionAnalysis.h"
#include "llvm/CodeGen/ScheduleHazardRecognizer.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/MC/MCInstrItineraries.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "Hexagon.h"
#include "HexagonTargetMachine.h"
#include "HexagonRegisterInfo.h"
#include "HexagonSubtarget.h"
#include "HexagonMachineFunctionInfo.h"
#include <map>
#include <vector>
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "packets"
Enumerations
enum PredicateKind { PK_False, PK_True, PK_Unknown }
Functions
void llvm::initializeHexagonPacketizerPass (PassRegistry &)
INITIALIZE_PASS_BEGIN (HexagonPacketizer,"packets","Hexagon Packetizer", false, false) INITIALIZE_PASS_END(HexagonPacketizer
static bool IsIndirectCall (MachineInstr *MI)
static bool IsRegDependence (const SDep::Kind DepType)
static bool IsDirectJump (MachineInstr *MI)
static bool IsSchedBarrier (MachineInstr *MI)
static bool IsControlFlow (MachineInstr *MI)
static bool IsLoopN (MachineInstr *MI)
static bool DoesModifyCalleeSavedReg (MachineInstr *MI, const TargetRegisterInfo *TRI)
static PredicateKind getPredicateSense (MachineInstr *MI, const HexagonInstrInfo *QII)
static MachineOperand & GetPostIncrementOperand (MachineInstr *MI, const HexagonInstrInfo *QII)
static MachineOperand & GetStoreValueOperand (MachineInstr *MI)
static unsigned getPredicatedRegister (MachineInstr *MI, const HexagonInstrInfo *QII)
Gets the predicate register of a predicated instruction.
Variables
static cl::opt< bool > PacketizeVolatiles ("hexagon-packetize-volatiles", cl::ZeroOrMore, cl::Hidden, cl::init(true), cl::desc("Allow non-solo packetization of volatile memory references"))
packets
Hexagon Packetizer
Hexagon false
Macro Definition Documentation
#define DEBUG_TYPE "packets"
Definition at line 19 of file HexagonVLIWPacketizer.cpp.
Enumeration Type Documentation
enum PredicateKind
Enumerator
PK_False
PK_True
PK_Unknown
Definition at line 455 of file HexagonVLIWPacketizer.cpp.
Function Documentation
static bool DoesModifyCalleeSavedReg (MachineInstr * MI, const TargetRegisterInfo * TRI) static
DoesModifyCalleeSavedReg - Returns true if the instruction modifies a callee-saved register.
Definition at line 392 of file HexagonVLIWPacketizer.cpp.
References llvm::SDep::Data, llvm::TargetRegisterInfo::getCalleeSavedRegs(), llvm::MachineInstr::getDesc(), llvm::HexagonInstrInfo::GetDotNewOp(), llvm::HexagonInstrInfo::GetDotNewPredOp(), llvm::HexagonInstrInfo::GetDotOldOp(), llvm::MachineInstr::getOpcode(), llvm::HexagonInstrInfo::isConditionalALU32(), llvm::MCInstrDesc::isConditionalBranch(), llvm::HexagonInstrInfo::isConditionalLoad(), llvm::HexagonInstrInfo::isConditionalStore(), llvm::HexagonInstrInfo::isConditionalTransfer(), llvm::HexagonInstrInfo::mayBeNewStore(), MII, llvm::MachineInstr::modifiesRegister(), llvm::MachineInstr::setDesc(), and TII.
Referenced by getPredicatedRegister().
static MachineOperand& GetPostIncrementOperand (MachineInstr * MI, const HexagonInstrInfo * QII) static
Definition at line 474 of file HexagonVLIWPacketizer.cpp.
References llvm::MachineInstr::getDesc(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isDef(), llvm::HexagonInstrInfo::isPostIncrement(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUse(), llvm_unreachable, llvm::MCInstrDesc::mayLoad(), and llvm::MCInstrDesc::mayStore().
Referenced by GetStoreValueOperand().
static unsigned getPredicatedRegister (MachineInstr * MI, const HexagonInstrInfo * QII) static
Gets the predicate register of a predicated instruction.
We use the following rule: The first predicate register that is a use is the predicate register of a predicated instruction.
Definition at line 841 of file HexagonVLIWPacketizer.cpp.
References llvm::SDep::Anti, llvm::SDep::Data, llvm::MachineInstr::definesRegister(), DoesModifyCalleeSavedReg(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::SUnit::getInstr(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), getPredicateSense(), llvm::MachineOperand::getReg(), llvm::MCInstrDesc::getSchedClass(), llvm::HexagonRegisterInfo::getStackRegister(), llvm::InstrStage::getUnits(), llvm::MachineInstr::hasOrderedMemoryRef(), llvm::HexagonSubtarget::hasV4TOps(), HEXAGON_LRFP_SIZE, i, I, llvm::ISD::INLINEASM, llvm::MCInstrDesc::isBarrier(), llvm::MCInstrDesc::isBranch(), llvm::MCInstrDesc::isCall(), llvm::MCInstrDesc::isConditionalBranch(), llvm::HexagonInstrInfo::isConstExtended(), IsControlFlow(), llvm::HexagonInstrInfo::isDeallocRet(), llvm::MachineInstr::isDebugValue(), IsDirectJump(), llvm::HexagonInstrInfo::isDotNewInst(), llvm::MachineInstr::isEHLabel(), llvm::HexagonInstrInfo::isExtended(), llvm::MachineInstr::isInlineAsm(), IsLoopN(), llvm::HexagonInstrInfo::isMemOp(), llvm::HexagonInstrInfo::isNewValueInst(), llvm::HexagonInstrInfo::isNewValueJump(), llvm::HexagonInstrInfo::isPredicated(), llvm::MachineOperand::isReg(), IsRegDependence(), llvm::MCInstrDesc::isReturn(), llvm::HexagonInstrInfo::isSaveCalleeSavedRegsCall(), IsSchedBarrier(), llvm::SUnit::isSucc(), llvm::MachineOperand::isUse(), llvm::HexagonInstrInfo::isValidOffset(), llvm_unreachable, llvm::MCInstrDesc::mayStore(), llvm::A64CC::MI, MII, llvm::MachineInstr::modifiesRegister(), llvm::MachineInstr::operands_begin(), llvm::MachineInstr::operands_end(), llvm::SDep::Order, llvm::SDep::Output, PK_Unknown, llvm::MachineOperand::setImm(), llvm::HexagonRegisterInfo::Subtarget, llvm::SUnit::Succs, TII, and llvm::SystemZISD::TM.
static PredicateKind getPredicateSense (MachineInstr * MI, const HexagonInstrInfo * QII) static
Returns true if an instruction is predicated on p0 and false if it's predicated on !p0.
Definition at line 463 of file HexagonVLIWPacketizer.cpp.
References llvm::HexagonInstrInfo::isPredicated(), llvm::HexagonInstrInfo::isPredicatedTrue(), PK_False, PK_True, and PK_Unknown.
Referenced by getPredicatedRegister(), and GetStoreValueOperand().
static MachineOperand& GetStoreValueOperand (MachineInstr * MI) static
Definition at line 514 of file HexagonVLIWPacketizer.cpp.
References llvm::SDep::Anti, llvm::MachineFunction::CreateMachineInstr(), llvm::MachineFunction::DeleteMachineInstr(), llvm::MachineInstr::getDesc(), llvm::HexagonInstrInfo::GetDotNewOp(), llvm::SUnit::getInstr(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), GetPostIncrementOperand(), getPredicateSense(), llvm::MachineOperand::getReg(), llvm::HexagonSubtarget::hasV4TOps(), i, llvm::MachineOperand::isDef(), llvm::HexagonInstrInfo::isDotNewInst(), llvm::MachineOperand::isImplicit(), llvm::HexagonInstrInfo::isPostIncrement(), llvm::HexagonInstrInfo::isPredicated(), llvm::MachineOperand::isReg(), llvm::SUnit::isSucc(), llvm::HexagonInstrInfo::mayBeNewStore(), llvm::MCInstrDesc::mayLoad(), llvm::MCInstrDesc::mayStore(), llvm::A64CC::MI, llvm::MachineInstr::modifiesRegister(), llvm::HexagonRegisterInfo::Subtarget, llvm::SUnit::Succs, TII, and llvm::SystemZISD::TM.
INITIALIZE_PASS_BEGIN (HexagonPacketizer , "packets" , "Hexagon Packetizer" , false , false)
static bool IsControlFlow (MachineInstr * MI) static
Definition at line 381 of file HexagonVLIWPacketizer.cpp.
References llvm::MachineInstr::getDesc(), llvm::MCInstrDesc::isCall(), and llvm::MCInstrDesc::isTerminator().
Referenced by getPredicatedRegister().
static bool IsDirectJump (MachineInstr * MI) static
Definition at line 369 of file HexagonVLIWPacketizer.cpp.
References llvm::MachineInstr::getOpcode().
Referenced by getPredicatedRegister().
static bool IsIndirectCall (MachineInstr * MI) static
Definition at line 267 of file HexagonVLIWPacketizer.cpp.
References llvm::MachineFunction::CreateMachineInstr(), llvm::SDep::Data, llvm::MachineFunction::DeleteMachineInstr(), llvm::MachineInstr::getDebugLoc(), llvm::HexagonRegisterInfo::getFrameRegister(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::HexagonRegisterInfo::getRARegister(), llvm::MachineOperand::getReg(), llvm::HexagonRegisterInfo::getStackRegister(), llvm::HexagonInstrInfo::isConstExtended(), llvm::HexagonInstrInfo::isDeallocRet(), llvm::HexagonInstrInfo::isExtended(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUse(), llvm_unreachable, llvm::A64CC::MI, TII, and llvm::SystemZISD::TM.
static bool IsLoopN (MachineInstr * MI) static
Definition at line 385 of file HexagonVLIWPacketizer.cpp.
References llvm::MachineInstr::getOpcode().
Referenced by getPredicatedRegister().
static bool IsRegDependence (const SDep::Kind DepType) static
Definition at line 364 of file HexagonVLIWPacketizer.cpp.
References llvm::SDep::Anti, llvm::SDep::Data, and llvm::SDep::Output.
Referenced by getPredicatedRegister().
static bool IsSchedBarrier (MachineInstr * MI) static
Definition at line 373 of file HexagonVLIWPacketizer.cpp.
References llvm::HexagonISD::BARRIER, and llvm::MachineInstr::getOpcode().
Referenced by getPredicatedRegister().
Variable Documentation
Hexagon false
Definition at line 180 of file HexagonVLIWPacketizer.cpp.
Hexagon Packetizer
Definition at line 180 of file HexagonVLIWPacketizer.cpp.
cl::opt<bool> PacketizeVolatiles("hexagon-packetize-volatiles", cl::ZeroOrMore, cl::Hidden, cl::init(true), cl::desc("Allow non-solo packetization of volatile memory references")) static
packets
Definition at line 180 of file HexagonVLIWPacketizer.cpp.