LLVM: HexagonMCInstLower.cpp File Reference
LLVM API Documentation
HexagonMCInstLower.cpp File Reference
#include "Hexagon.h"
#include "HexagonAsmPrinter.h"
#include "HexagonMachineFunctionInfo.h"
#include "MCTargetDesc/HexagonMCInst.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/IR/Constants.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/Target/Mangler.h"
Functions
static MCOperand GetSymbolRef (const MachineOperand &MO, const MCSymbol *Symbol, HexagonAsmPrinter &Printer)
Function Documentation
static MCOperand GetSymbolRef (const MachineOperand & MO, const MCSymbol * Symbol, HexagonAsmPrinter & Printer) static
Definition at line 27 of file HexagonMCInstLower.cpp.
References llvm::MCConstantExpr::Create(), llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateAdd(), llvm::MCOperand::CreateExpr(), llvm::MachineOperand::getOffset(), llvm::MachineOperand::isJTI(), llvm::AsmPrinter::OutContext, and llvm::MCSymbolRefExpr::VK_None.
Referenced by llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc(), llvm::ARMAsmPrinter::getISAEncoding(), and llvm::HexagonLowerToMC().