LLVM: HexagonNewValueJump.cpp File Reference
LLVM API Documentation
HexagonNewValueJump.cpp File Reference
#include "llvm/PassSupport.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/ScheduleDAGInstrs.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/LiveVariables.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/MachineFunctionAnalysis.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include "Hexagon.h"
#include "HexagonTargetMachine.h"
#include "HexagonRegisterInfo.h"
#include "HexagonSubtarget.h"
#include "HexagonInstrInfo.h"
#include "HexagonMachineFunctionInfo.h"
#include <map>
#include "llvm/Support/CommandLine.h"
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "hexagon-nvj"
Functions
STATISTIC (NumNVJGenerated,"Number of New Value Jump Instructions created")
void llvm::initializeHexagonNewValueJumpPass (PassRegistry &)
INITIALIZE_PASS_BEGIN (HexagonNewValueJump,"hexagon-nvj","Hexagon NewValueJump", false, false) INITIALIZE_PASS_END(HexagonNewValueJump
hexagon Hexagon static false bool canBeFeederToNewValueJump (const HexagonInstrInfo *QII, const TargetRegisterInfo *TRI, MachineBasicBlock::iterator II, MachineBasicBlock::iterator end, MachineBasicBlock::iterator skip, MachineFunction &MF)
static bool commonChecksToProhibitNewValueJump (bool afterRA, MachineBasicBlock::iterator MII)
static bool canCompareBeNewValueJump (const HexagonInstrInfo *QII, const TargetRegisterInfo *TRI, MachineBasicBlock::iterator II, unsigned pReg, bool secondReg, bool optLocation, MachineBasicBlock::iterator end, MachineFunction &MF)
static unsigned getNewValueJumpOpcode (MachineInstr *MI, int reg, bool secondRegNewified, MachineBasicBlock *jmpTarget, const MachineBranchProbabilityInfo *MBPI)
Variables
static cl::opt< int > DbgNVJCount ("nvj-count", cl::init(-1), cl::Hidden, cl::desc("Maximum number of predicated jumps to be converted to New Value Jump"))
static cl::opt< bool > DisableNewValueJumps ("disable-nvjump", cl::Hidden, cl::ZeroOrMore, cl::init(false), cl::desc("Disable New Value Jumps"))
hexagon nvj
hexagon Hexagon NewValueJump
hexagon Hexagon false
Macro Definition Documentation
#define DEBUG_TYPE "hexagon-nvj"
Definition at line 24 of file HexagonNewValueJump.cpp.
Function Documentation
hexagon Hexagon static false bool canBeFeederToNewValueJump (const HexagonInstrInfo * QII, const TargetRegisterInfo * TRI, MachineBasicBlock::iterator II, MachineBasicBlock::iterator end, MachineBasicBlock::iterator skip, MachineFunction & MF) static
Definition at line 109 of file HexagonNewValueJump.cpp.
References llvm::sys::path::end(), i, and llvm::TargetOpcode::KILL.
Referenced by getNewValueJumpOpcode().
static bool canCompareBeNewValueJump (const HexagonInstrInfo * QII, const TargetRegisterInfo * TRI, MachineBasicBlock::iterator II, unsigned pReg, bool secondReg, bool optLocation, MachineBasicBlock::iterator end, MachineFunction & MF) static
Definition at line 215 of file HexagonNewValueJump.cpp.
References commonChecksToProhibitNewValueJump(), llvm::TargetOpcode::COPY, llvm::sys::path::end(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::MachineRegisterInfo::getVRegDef(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::A64CC::MI, and MRI.
Referenced by getNewValueJumpOpcode().
static bool commonChecksToProhibitNewValueJump (bool afterRA, MachineBasicBlock::iterator MII) static
Definition at line 172 of file HexagonNewValueJump.cpp.
References llvm::TargetOpcode::COPY, llvm::TargetOpcode::KILL, and llvm::TargetOpcode::PHI.
Referenced by canCompareBeNewValueJump(), and getNewValueJumpOpcode().
static unsigned getNewValueJumpOpcode (MachineInstr * MI, int reg, bool secondRegNewified, MachineBasicBlock * jmpTarget, const MachineBranchProbabilityInfo * MBPI) static
Definition at line 289 of file HexagonNewValueJump.cpp.
References llvm::MachineInstrBuilder::addMBB(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::BuildMI(), canBeFeederToNewValueJump(), canCompareBeNewValueJump(), commonChecksToProhibitNewValueJump(), DbgNVJCount, llvm::dbgs(), DEBUG, DisableNewValueJumps, llvm::MachineBasicBlock::dump(), llvm::MachineInstr::dump(), llvm::sys::path::end(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::MachineInstr::eraseFromParent(), llvm::DebugLoc::get(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getDesc(), llvm::MachineBranchProbabilityInfo::getEdgeProbability(), llvm::MachineOperand::getImm(), llvm::TargetMachine::getInstrInfo(), llvm::getKillRegState(), llvm::MachineOperand::getMBB(), llvm::MachineFunction::getName(), llvm::MachineBasicBlock::getNumber(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::TargetMachine::getRegisterInfo(), llvm::MachineFunction::getTarget(), i, llvm::MCInstrDesc::isCompare(), llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isKill(), llvm::MachineBasicBlock::isLiveIn(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUse(), j(), llvm_unreachable, llvm::A64CC::MI, MII, llvm::MachineOperand::setIsKill(), llvm::MachineBasicBlock::splice(), llvm::MachineBasicBlock::succ_begin(), and llvm::MachineBasicBlock::succ_end().
INITIALIZE_PASS_BEGIN (HexagonNewValueJump , "hexagon-nvj" , "Hexagon NewValueJump" , false , false)
STATISTIC (NumNVJGenerated , "Number of New Value Jump Instructions created")
Variable Documentation
cl::opt<int> DbgNVJCount("nvj-count", cl::init(-1), cl::Hidden, cl::desc("Maximum number of predicated jumps to be converted to New Value Jump")) static
Referenced by getNewValueJumpOpcode().
cl::opt<bool> DisableNewValueJumps("disable-nvjump", cl::Hidden, cl::ZeroOrMore, cl::init(false), cl::desc("Disable New Value Jumps")) static
Referenced by getNewValueJumpOpcode().
hexagon Hexagon false
Definition at line 103 of file HexagonNewValueJump.cpp.
hexagon Hexagon NewValueJump
Definition at line 103 of file HexagonNewValueJump.cpp.
hexagon nvj
Definition at line 103 of file HexagonNewValueJump.cpp.