LLVM: HexagonFixupHwLoops.cpp File Reference
LLVM API Documentation
HexagonFixupHwLoops.cpp File Reference
#include "llvm/ADT/DenseMap.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/PassSupport.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "Hexagon.h"
#include "HexagonTargetMachine.h"
Namespaces
llvm
List of target independent CodeGen pass IDs.
Functions
void llvm::initializeHexagonFixupHwLoopsPass (PassRegistry &)
INITIALIZE_PASS (HexagonFixupHwLoops,"hwloopsfixup","Hexagon Hardware Loops Fixup", false, false) FunctionPass *llvm
static bool isHardwareLoop (const MachineInstr *MI)
Returns true if the instruction is a hardware loop instruction.
Function Documentation
INITIALIZE_PASS (HexagonFixupHwLoops , "hwloopsfixup" , "Hexagon Hardware Loops Fixup" , false , false)
Definition at line 72 of file HexagonFixupHwLoops.cpp.
static bool isHardwareLoop (const MachineInstr * MI) static
Returns true if the instruction is a hardware loop instruction.
Definition at line 81 of file HexagonFixupHwLoops.cpp.
References llvm::MachineFunction::begin(), llvm::BuildMI(), llvm::MachineFunction::end(), llvm::RegScavenger::enterBasicBlock(), llvm::RegScavenger::forward(), llvm::MCInstrInfo::get(), llvm::TargetMachine::getInstrInfo(), llvm::MachineInstr::getOpcode(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getTarget(), LC0, MII, llvm::RegScavenger::scavengeRegister(), and TII.