LLVM: HexagonPeephole.cpp File Reference
LLVM API Documentation
HexagonPeephole.cpp File Reference
#include "Hexagon.h"
#include "HexagonTargetMachine.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/Constants.h"
#include "llvm/PassSupport.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include <algorithm>
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "hexagon-peephole"
Functions
void llvm::initializeHexagonPeepholePass (PassRegistry &)
INITIALIZE_PASS (HexagonPeephole,"hexagon-peephole","Hexagon Peephole", false, false) bool HexagonPeephole
Variables
static cl::opt< bool > DisableHexagonPeephole ("disable-hexagon-peephole", cl::Hidden, cl::ZeroOrMore, cl::init(false), cl::desc("Disable Peephole Optimization"))
static cl::opt< bool > DisablePNotP ("disable-hexagon-pnotp", cl::Hidden, cl::ZeroOrMore, cl::init(false), cl::desc("Disable Optimization of PNotP"))
static cl::opt< bool > DisableOptSZExt ("disable-hexagon-optszext", cl::Hidden, cl::ZeroOrMore, cl::init(false), cl::desc("Disable Optimization of Sign/Zero Extends"))
static cl::opt< bool > DisableOptExtTo64 ("disable-hexagon-opt-ext-to-64", cl::Hidden, cl::ZeroOrMore, cl::init(false), cl::desc("Disable Optimization of extensions to i64."))
Macro Definition Documentation
#define DEBUG_TYPE "hexagon-peephole"
Definition at line 38 of file HexagonPeephole.cpp.
Function Documentation
INITIALIZE_PASS (HexagonPeephole , "hexagon-peephole" , "Hexagon Peephole" , false , false)
Definition at line 109 of file HexagonPeephole.cpp.
References llvm::MachineInstr::addOperand(), llvm::MachineBasicBlock::begin(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::clear(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::clear(), llvm::MachineOperand::CreateReg(), DisableHexagonPeephole, DisableOptExtTo64, DisableOptSZExt, DisablePNotP, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), llvm::MachineBasicBlock::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::find(), llvm::TargetRegisterClass::getID(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MCRegisterInfo::getRegClass(), llvm::MachineOperand::getSubReg(), llvm::MachineOperand::getType(), llvm::MachineInstr::isCopy(), llvm::MachineOperand::isDead(), llvm::MachineOperand::isDebug(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isKill(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUndef(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm_unreachable, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::lookup(), llvm::A64CC::MI, MII, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_Register, MRI, llvm::MachineInstr::RemoveOperand(), llvm::MachineInstr::setDesc(), llvm::MachineOperand::setImm(), llvm::MachineOperand::setReg(), and llvm::A64SE::SXTW.
Variable Documentation
cl::opt<bool> DisableHexagonPeephole("disable-hexagon-peephole", cl::Hidden, cl::ZeroOrMore, cl::init(false), cl::desc("Disable Peephole Optimization")) static
Referenced by INITIALIZE_PASS().
cl::opt<bool> DisableOptExtTo64("disable-hexagon-opt-ext-to-64", cl::Hidden, cl::ZeroOrMore, cl::init(false), cl::desc("Disable Optimization of extensions to i64.")) static
Referenced by INITIALIZE_PASS().
cl::opt<bool> DisableOptSZExt("disable-hexagon-optszext", cl::Hidden, cl::ZeroOrMore, cl::init(false), cl::desc("Disable Optimization of Sign/Zero Extends")) static
Referenced by INITIALIZE_PASS().
cl::opt<bool> DisablePNotP("disable-hexagon-pnotp", cl::Hidden, cl::ZeroOrMore, cl::init(false), cl::desc("Disable Optimization of PNotP")) static
Referenced by INITIALIZE_PASS().