LLVM: HexagonVarargsCallingConvention.h File Reference
LLVM API Documentation
HexagonVarargsCallingConvention.h File Reference
Functions
static bool RetCC_Hexagon32_VarArgs (unsigned ValNo, EVT ValVT, EVT LocVT, CCValAssign::LocInfo LocInfo, ISD::ArgFlagsTy ArgFlags, Hexagon_CCState &State, int NonVarArgsParams, int CurrentParam, bool ForceMem)
static bool CC_Hexagon32_VarArgs (unsigned ValNo, EVT ValVT, EVT LocVT, CCValAssign::LocInfo LocInfo, ISD::ArgFlagsTy ArgFlags, Hexagon_CCState &State, int NonVarArgsParams, int CurrentParam, bool ForceMem)
Function Documentation
static bool CC_Hexagon32_VarArgs (unsigned ValNo, EVT ValVT, EVT LocVT, CCValAssign::LocInfo LocInfo, ISD::ArgFlagsTy ArgFlags, Hexagon_CCState & State, int NonVarArgsParams, int CurrentParam, bool ForceMem) static
Definition at line 29 of file HexagonVarargsCallingConvention.h.
References f32(), getReg(), i16, i32, i64, i8, R2, R4, and Type.
static bool RetCC_Hexagon32_VarArgs (unsigned ValNo, EVT ValVT, EVT LocVT, CCValAssign::LocInfo LocInfo, ISD::ArgFlagsTy ArgFlags, Hexagon_CCState & State, int NonVarArgsParams, int CurrentParam, bool ForceMem) static
Definition at line 98 of file HexagonVarargsCallingConvention.h.
References f32(), getReg(), i32, i64, R2, R4, and Type.