LLVM: HexagonISelDAGToDAG.cpp File Reference
LLVM API Documentation
HexagonISelDAGToDAG.cpp File Reference
#include "Hexagon.h"
#include "HexagonISelLowering.h"
#include "HexagonTargetMachine.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "HexagonGenDAGISel.inc"
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "hexagon-isel"
Functions
void llvm::initializeHexagonDAGToDAGISelPass (PassRegistry &)
static void initializePassOnce (PassRegistry &Registry)
static bool IsS11_0_Offset (SDNode *S)
static bool IsS11_1_Offset (SDNode *S)
static bool IsS11_2_Offset (SDNode *S)
static bool IsS11_3_Offset (SDNode *S)
static bool IsU6_0_Offset (SDNode *S)
static bool IsU6_1_Offset (SDNode *S)
static bool IsU6_2_Offset (SDNode *S)
static unsigned doesIntrinsicReturnPredicate (unsigned ID)
static unsigned doesIntrinsicContainPredicate (unsigned ID)
static bool OffsetFitsS11 (EVT MemType, int64_t Offset)
Variables
static cl::opt< unsigned > MaxNumOfUsesForConstExtenders ("ga-max-num-uses-for-constant-extenders", cl::Hidden, cl::init(2), cl::desc("Maximum number of uses of a global address such that we still us a""constant extended instruction"))
Macro Definition Documentation
#define DEBUG_TYPE "hexagon-isel"
Definition at line 14 of file HexagonISelDAGToDAG.cpp.
Function Documentation
static unsigned doesIntrinsicContainPredicate (unsigned ID) static
Definition at line 316 of file HexagonISelDAGToDAG.cpp.
References llvm::Intrinsic::hexagon_C2_all8, llvm::Intrinsic::hexagon_C2_and, llvm::Intrinsic::hexagon_C2_any8, llvm::Intrinsic::hexagon_C2_mask, llvm::Intrinsic::hexagon_C2_mux, llvm::Intrinsic::hexagon_C2_muxii, llvm::Intrinsic::hexagon_C2_muxir, llvm::Intrinsic::hexagon_C2_muxri, llvm::Intrinsic::hexagon_C2_not, llvm::Intrinsic::hexagon_C2_or, llvm::Intrinsic::hexagon_C2_tfrpr, llvm::Intrinsic::hexagon_C2_vitpack, llvm::Intrinsic::hexagon_C2_vmux, llvm::Intrinsic::hexagon_C2_xor, llvm::Intrinsic::hexagon_S2_valignrb, and llvm::Intrinsic::hexagon_S2_vsplicerb.
Referenced by OffsetFitsS11().
static unsigned doesIntrinsicReturnPredicate (unsigned ID) static
Definition at line 269 of file HexagonISelDAGToDAG.cpp.
References llvm::Intrinsic::hexagon_A2_vcmpbeq, llvm::Intrinsic::hexagon_A2_vcmpbgtu, llvm::Intrinsic::hexagon_A2_vcmpheq, llvm::Intrinsic::hexagon_A2_vcmphgt, llvm::Intrinsic::hexagon_A2_vcmphgtu, llvm::Intrinsic::hexagon_A2_vcmpweq, llvm::Intrinsic::hexagon_A2_vcmpwgt, llvm::Intrinsic::hexagon_A2_vcmpwgtu, llvm::Intrinsic::hexagon_C2_all8, llvm::Intrinsic::hexagon_C2_and, llvm::Intrinsic::hexagon_C2_andn, llvm::Intrinsic::hexagon_C2_any8, llvm::Intrinsic::hexagon_C2_bitsclr, llvm::Intrinsic::hexagon_C2_bitsclri, llvm::Intrinsic::hexagon_C2_bitsset, llvm::Intrinsic::hexagon_C2_cmpeq, llvm::Intrinsic::hexagon_C2_cmpeqi, llvm::Intrinsic::hexagon_C2_cmpeqp, llvm::Intrinsic::hexagon_C2_cmpgei, llvm::Intrinsic::hexagon_C2_cmpgeui, llvm::Intrinsic::hexagon_C2_cmpgt, llvm::Intrinsic::hexagon_C2_cmpgti, llvm::Intrinsic::hexagon_C2_cmpgtp, llvm::Intrinsic::hexagon_C2_cmpgtu, llvm::Intrinsic::hexagon_C2_cmpgtui, llvm::Intrinsic::hexagon_C2_cmpgtup, llvm::Intrinsic::hexagon_C2_cmplt, llvm::Intrinsic::hexagon_C2_cmpltu, llvm::Intrinsic::hexagon_C2_not, llvm::Intrinsic::hexagon_C2_or, llvm::Intrinsic::hexagon_C2_orn, llvm::Intrinsic::hexagon_C2_pxfer_map, llvm::Intrinsic::hexagon_C2_tfrrp, llvm::Intrinsic::hexagon_C2_xor, llvm::Intrinsic::hexagon_S2_tstbit_i, and llvm::Intrinsic::hexagon_S2_tstbit_r.
Referenced by OffsetFitsS11().
static void initializePassOnce (PassRegistry & Registry) static
Definition at line 186 of file HexagonISelDAGToDAG.cpp.
References llvm::SelectionDAGISel::ID, and llvm::PassRegistry::registerPass().
Referenced by llvm::initializeHexagonDAGToDAGISelPass().
static bool IsS11_0_Offset (SDNode * S) static
Definition at line 198 of file HexagonISelDAGToDAG.cpp.
References llvm::ConstantSDNode::getSExtValue(), N, and S.
Referenced by OffsetFitsS11().
static bool IsS11_1_Offset (SDNode * S) static
Definition at line 208 of file HexagonISelDAGToDAG.cpp.
References llvm::ConstantSDNode::getSExtValue(), N, and S.
Referenced by OffsetFitsS11().
static bool IsS11_2_Offset (SDNode * S) static
Definition at line 218 of file HexagonISelDAGToDAG.cpp.
References llvm::ConstantSDNode::getSExtValue(), N, and S.
Referenced by OffsetFitsS11().
static bool IsS11_3_Offset (SDNode * S) static
Definition at line 228 of file HexagonISelDAGToDAG.cpp.
References llvm::ConstantSDNode::getSExtValue(), N, and S.
Referenced by OffsetFitsS11().
static bool IsU6_0_Offset (SDNode * S) static
Definition at line 238 of file HexagonISelDAGToDAG.cpp.
References llvm::ConstantSDNode::getSExtValue(), N, and S.
Referenced by OffsetFitsS11().
static bool IsU6_1_Offset (SDNode * S) static
Definition at line 248 of file HexagonISelDAGToDAG.cpp.
References llvm::ConstantSDNode::getSExtValue(), N, and S.
Referenced by OffsetFitsS11().
static bool IsU6_2_Offset (SDNode * S) static
Definition at line 258 of file HexagonISelDAGToDAG.cpp.
References llvm::ConstantSDNode::getSExtValue(), N, and S.
Referenced by OffsetFitsS11().
static bool OffsetFitsS11 (EVT MemType, int64_t Offset) static
Definition at line 364 of file HexagonISelDAGToDAG.cpp.
References llvm::ISD::ADD, llvm::CodeGenOpt::Aggressive, llvm::HexagonISD::CONST32, llvm::HexagonISD::CONST32_GP, llvm::ISD::Constant, llvm::ISD::ConstantFP, doesIntrinsicContainPredicate(), doesIntrinsicReturnPredicate(), llvm::dyn_cast(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), llvm::MVT::f32, llvm::MVT::f64, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::find(), llvm::ISD::FrameIndex, llvm::LSBaseSDNode::getAddressingMode(), llvm::LoadSDNode::getBasePtr(), llvm::StoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::LoadSDNode::getExtensionType(), llvm::GlobalAddressSDNode::getGlobal(), llvm::HexagonTargetMachine::getInstrInfo(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SDNode::getNumOperands(), llvm::LoadSDNode::getOffset(), llvm::StoreSDNode::getOffset(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::TargetMachine::getOptLevel(), llvm::HexagonTargetMachine::getRegisterInfo(), llvm::SDValue::getResNo(), llvm::ConstantSDNode::getSExtValue(), llvm::StoreSDNode::getValue(), llvm::ConstantFPSDNode::getValueAPF(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SDNode::hasOneUse(), i, I, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::SDNode::isMachineOpcode(), llvm::ISD::isNormalLoad(), IsS11_0_Offset(), IsS11_1_Offset(), IsS11_2_Offset(), IsS11_3_Offset(), llvm::StoreSDNode::isTruncatingStore(), IsU6_0_Offset(), IsU6_1_Offset(), IsU6_2_Offset(), llvm::HexagonInstrInfo::isValidAutoIncImm(), llvm::A64DB::LD, llvm_unreachable, llvm::ISD::LOAD, MaxNumOfUsesForConstExtenders, llvm::ISD::MUL, N, R600_InstFlag::OP1, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), R2, result, llvm::MCID::Select, llvm::ISD::SELECT, llvm::ISD::SETCC, llvm::ISD::SETGT, llvm::ISD::SETLT, llvm::SDNode::setNodeId(), llvm::ISD::SEXTLOAD, Shift, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::ISD::SRA, llvm::ISD::SRL, llvm::A64DB::ST, llvm::ISD::STORE, llvm::ISD::SUB, llvm::A64SE::SXTH, llvm::A64SE::SXTW, llvm::ISD::TargetExternalSymbol, llvm::ISD::TargetGlobalAddress, TII, llvm::ISD::TRUNCATE, llvm::ISD::UNINDEXED, llvm::SDNode::use_begin(), llvm::SDNode::use_end(), llvm::ISD::ZERO_EXTEND, and llvm::ISD::ZEXTLOAD.
Variable Documentation
cl::opt<unsigned> MaxNumOfUsesForConstExtenders("ga-max-num-uses-for-constant-extenders", cl::Hidden, cl::init(2), cl::desc("Maximum number of uses of a global address such that we still us a""constant extended instruction")) static
Referenced by OffsetFitsS11().