LLVM: HexagonTargetMachine.cpp File Reference
LLVM API Documentation
HexagonTargetMachine.cpp File Reference
#include "HexagonTargetMachine.h"
#include "Hexagon.h"
#include "HexagonISelLowering.h"
#include "HexagonMachineScheduler.h"
#include "HexagonTargetObjectFile.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/Module.h"
#include "llvm/PassManager.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Transforms/IPO/PassManagerBuilder.h"
#include "llvm/Transforms/Scalar.h"
Functions
void LLVMInitializeHexagonTarget ()
static ScheduleDAGInstrs * createVLIWMachineSched (MachineSchedContext *C)
Variables
static cl::opt< bool > DisableHardwareLoops ("disable-hexagon-hwloops", cl::Hidden, cl::desc("Disable Hardware Loops for Hexagon target"))
static cl::opt< bool > DisableHexagonMISched ("disable-hexagon-misched", cl::Hidden, cl::ZeroOrMore, cl::init(false), cl::desc("Disable Hexagon MI Scheduling"))
static cl::opt< bool > DisableHexagonCFGOpt ("disable-hexagon-cfgopt", cl::Hidden, cl::ZeroOrMore, cl::init(false), cl::desc("Disable Hexagon CFG Optimization"))
int HexagonTargetMachineModule = 0
static MachineSchedRegistry SchedCustomRegistry ("hexagon","Run Hexagon's custom scheduler", createVLIWMachineSched)
Function Documentation
static ScheduleDAGInstrs* createVLIWMachineSched (MachineSchedContext * C) static
Definition at line 54 of file HexagonTargetMachine.cpp.
References SchedCustomRegistry.
Referenced by llvm::HexagonTargetMachine::addPassesForOptimizations().
void LLVMInitializeHexagonTarget ()
Definition at line 49 of file HexagonTargetMachine.cpp.
References llvm::TheHexagonTarget, and llvm::X.
Variable Documentation
cl:: opt<bool> DisableHardwareLoops("disable-hexagon-hwloops", cl::Hidden, cl::desc("Disable Hardware Loops for Hexagon target")) static
Referenced by llvm::HexagonTargetMachine::createPassConfig().
cl::opt<bool> DisableHexagonCFGOpt("disable-hexagon-cfgopt", cl::Hidden, cl::ZeroOrMore, cl::init(false), cl::desc("Disable Hexagon CFG Optimization")) static
Referenced by llvm::HexagonTargetMachine::createPassConfig().
cl::opt<bool> DisableHexagonMISched("disable-hexagon-misched", cl::Hidden, cl::ZeroOrMore, cl::init(false), cl::desc("Disable Hexagon MI Scheduling")) static
Referenced by llvm::HexagonTargetMachine::addPassesForOptimizations().
int HexagonTargetMachineModule = 0
HexagonTargetMachineModule - Note that this is used on hosts that cannot link in a library unless there are references into the library. In particular, it seems that it is not possible to get things to work on Win32 without this. Though it is unused, do not remove it.
Definition at line 46 of file HexagonTargetMachine.cpp.
MachineSchedRegistry SchedCustomRegistry("hexagon","Run Hexagon's custom scheduler", createVLIWMachineSched) static
Referenced by createVLIWMachineSched().