LLVM: IfConversion.cpp File Reference
LLVM API Documentation
IfConversion.cpp File Reference
#include "llvm/CodeGen/Passes.h"
#include "BranchFolding.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineBranchProbabilityInfo.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetSchedule.h"
#include "llvm/CodeGen/LiveRegUnits.h"
#include "llvm/MC/MCInstrItineraries.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include "llvm/Target/TargetSubtargetInfo.h"
Macros
#define DEBUG_TYPE "ifcvt"
Functions
STATISTIC (NumSimple,"Number of simple if-conversions performed")
STATISTIC (NumSimpleFalse,"Number of simple (F) if-conversions performed")
STATISTIC (NumTriangle,"Number of triangle if-conversions performed")
STATISTIC (NumTriangleRev,"Number of triangle (R) if-conversions performed")
STATISTIC (NumTriangleFalse,"Number of triangle (F) if-conversions performed")
STATISTIC (NumTriangleFRev,"Number of triangle (F/R) if-conversions performed")
STATISTIC (NumDiamonds,"Number of diamond if-conversions performed")
STATISTIC (NumIfConvBBs,"Number of if-converted blocks")
STATISTIC (NumDupBBs,"Number of duplicated blocks")
STATISTIC (NumUnpred,"Number of true blocks of diamonds unpredicated")
static MachineBasicBlock * findFalseBlock (MachineBasicBlock *BB, MachineBasicBlock *TrueBB)
static MachineBasicBlock * getNextBlock (MachineBasicBlock *BB)
static bool canFallThroughTo (MachineBasicBlock *BB, MachineBasicBlock *ToBB)
static void InsertUncondBranch (MachineBasicBlock *BB, MachineBasicBlock *ToBB, const TargetInstrInfo *TII)
static void UpdatePredRedefs (MachineInstr *MI, LiveRegUnits &Redefs, const TargetRegisterInfo *TRI)
static void RemoveKills (MachineInstr &MI, const LiveRegUnits &DontKill, const MCRegisterInfo &MCRI)
static void RemoveKills (MachineBasicBlock::iterator I, MachineBasicBlock::iterator E, const LiveRegUnits &DontKill, const MCRegisterInfo &MCRI)
static bool MaySpeculate (const MachineInstr *MI, SmallSet< unsigned, 4 > &LaterRedefs, const TargetInstrInfo *TII)
Variables
static cl::opt< int > IfCvtFnStart ("ifcvt-fn-start", cl::init(-1), cl::Hidden)
static cl::opt< int > IfCvtFnStop ("ifcvt-fn-stop", cl::init(-1), cl::Hidden)
static cl::opt< int > IfCvtLimit ("ifcvt-limit", cl::init(-1), cl::Hidden)
static cl::opt< bool > DisableSimple ("disable-ifcvt-simple", cl::init(false), cl::Hidden)
static cl::opt< bool > DisableSimpleF ("disable-ifcvt-simple-false", cl::init(false), cl::Hidden)
static cl::opt< bool > DisableTriangle ("disable-ifcvt-triangle", cl::init(false), cl::Hidden)
static cl::opt< bool > DisableTriangleR ("disable-ifcvt-triangle-rev", cl::init(false), cl::Hidden)
static cl::opt< bool > DisableTriangleF ("disable-ifcvt-triangle-false", cl::init(false), cl::Hidden)
static cl::opt< bool > DisableTriangleFR ("disable-ifcvt-triangle-false-rev", cl::init(false), cl::Hidden)
static cl::opt< bool > DisableDiamond ("disable-ifcvt-diamond", cl::init(false), cl::Hidden)
static cl::opt< bool > IfCvtBranchFold ("ifcvt-branch-fold", cl::init(true), cl::Hidden)
Macro Definition Documentation
#define DEBUG_TYPE "ifcvt"
Definition at line 14 of file IfConversion.cpp.
Function Documentation
static bool canFallThroughTo (MachineBasicBlock * BB, MachineBasicBlock * ToBB) static
canFallThroughTo - Returns true either if ToBB is the next block after BB or that all the intervening blocks are empty (given BB can fall through to its next block).
Definition at line 922 of file IfConversion.cpp.
References BB, llvm::MachineFunction::end(), llvm::MachineBasicBlock::getParent(), I, llvm::next(), llvm::MachineBasicBlock::pred_begin(), and llvm::MachineBasicBlock::pred_end().
Referenced by RemoveKills().
static MachineBasicBlock* findFalseBlock (MachineBasicBlock * BB, MachineBasicBlock * TrueBB) static
findFalseBlock - BB has a fallthrough. Find its 'false' successor given its 'true' successor.
Definition at line 433 of file IfConversion.cpp.
References llvm::TargetInstrInfo::InsertBranch(), llvm::TargetInstrInfo::RemoveBranch(), llvm::TargetInstrInfo::ReverseBranchCondition(), llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_end(), and std::swap().
Referenced by getNextBlock().
static MachineBasicBlock* getNextBlock (MachineBasicBlock * BB) inline static
getNextBlock - Returns the next block in the function blocks ordering. If it is the end, returns NULL.
Definition at line 459 of file IfConversion.cpp.
References llvm::TargetInstrInfo::AnalyzeBranch(), BB, llvm::SmallVectorTemplateCommon< T >::begin(), llvm::MachineFunction::begin(), llvm::TargetSchedModel::computeInstrLatency(), llvm::TargetInstrInfo::DefinesPredicate(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::MachineFunction::end(), findFalseBlock(), llvm::BranchProbability::getCompl(), llvm::MachineBranchProbabilityInfo::getEdgeProbability(), llvm::MachineBasicBlock::getNumber(), llvm::MachineBasicBlock::getParent(), llvm::TargetInstrInfo::getPredicationCost(), I, if(), llvm::TargetInstrInfo::isPredicable(), llvm::TargetInstrInfo::isPredicated(), llvm::TargetInstrInfo::isProfitableToDupForIfCvt(), llvm::TargetInstrInfo::ReverseBranchCondition(), and llvm::TargetInstrInfo::SubsumesPredicate().
Referenced by MaySpeculate().
static void InsertUncondBranch (MachineBasicBlock * BB, MachineBasicBlock * ToBB, const TargetInstrInfo * TII) static
InsertUncondBranch - Inserts an unconditional branch from BB to ToBB.
Definition at line 953 of file IfConversion.cpp.
References llvm::TargetInstrInfo::AnalyzeBranch(), llvm::SmallVectorBase::empty(), and llvm::TargetInstrInfo::InsertBranch().
Referenced by RemoveKills().
static bool MaySpeculate (const MachineInstr * MI, SmallSet< unsigned, 4 > & LaterRedefs, const TargetInstrInfo * TII) static
Definition at line 1458 of file IfConversion.cpp.
References llvm::SmallVectorTemplateCommon< T >::begin(), llvm::MachineFunction::CloneMachineInstr(), llvm::TargetSchedModel::computeInstrLatency(), llvm::SmallSet< T, N, C >::count(), llvm::dbgs(), llvm::LiveRegUnits::empty(), llvm::SmallVectorTemplateCommon< T >::end(), getNextBlock(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::TargetInstrInfo::getPredicationCost(), llvm::MachineOperand::getReg(), i, I, llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isDef(), llvm::TargetInstrInfo::isPredicated(), llvm::MachineOperand::isReg(), llvm::MachineInstr::isSafeToMove(), llvm_unreachable, llvm::A64CC::MI, llvm::TargetInstrInfo::PredicateInstruction(), RemoveKills(), and UpdatePredRedefs().
static void RemoveKills (MachineInstr & MI, const LiveRegUnits & DontKill, const MCRegisterInfo & MCRI) static
Remove kill flags from operands with a registers in the DontKill set.
Definition at line 999 of file IfConversion.cpp.
References llvm::LiveRegUnits::contains(), and llvm::MachineOperandIteratorBase::isValid().
Referenced by MaySpeculate(), and RemoveKills().
static void RemoveKills (MachineBasicBlock::iterator I, MachineBasicBlock::iterator E, const LiveRegUnits & DontKill, const MCRegisterInfo & MCRI) static
Walks a range of machine instructions and removes kill flags for registers in the DontKill set.
Definition at line 1013 of file IfConversion.cpp.
References llvm::LiveRegUnits::addLiveIns(), canFallThroughTo(), llvm::LiveRegUnits::clear(), llvm::SmallSet< T, N, C >::count(), llvm::MachineBasicBlock::getNumber(), llvm::MachineOperand::getReg(), i, I, llvm::LiveRegUnits::init(), llvm::SmallSet< T, N, C >::insert(), llvm::TargetInstrInfo::InsertBranch(), InsertUncondBranch(), llvm::MachineOperand::isDef(), llvm::TargetInstrInfo::isProfitableToUnpredicate(), llvm::MachineOperand::isReg(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm_unreachable, llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_size(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::TargetInstrInfo::RemoveBranch(), RemoveKills(), llvm::TargetInstrInfo::ReverseBranchCondition(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::LiveRegUnits::stepBackward(), llvm::LiveRegUnits::stepForward(), and std::swap().
STATISTIC (NumSimple , "Number of simple if-conversions performed")
STATISTIC (NumSimpleFalse , "Number of simple (F) if-conversions performed")
STATISTIC (NumTriangle , "Number of triangle if-conversions performed")
STATISTIC (NumTriangleRev , "Number of triangle (R) if-conversions performed")
STATISTIC (NumTriangleFalse , "Number of triangle (F) if-conversions performed")
STATISTIC (NumTriangleFRev , "Number of triangle (F/R) if-conversions performed")
STATISTIC (NumDiamonds , "Number of diamond if-conversions performed")
STATISTIC (NumIfConvBBs , "Number of if-converted blocks")
STATISTIC (NumDupBBs , "Number of duplicated blocks")
STATISTIC (NumUnpred , "Number of true blocks of diamonds unpredicated")
static void UpdatePredRedefs (MachineInstr * MI, LiveRegUnits & Redefs, const TargetRegisterInfo * TRI) static
Behaves like LiveRegUnits::StepForward() but also adds implicit uses to all values defined in MI which are not live/used by MI.
Definition at line 971 of file IfConversion.cpp.
References llvm::LiveRegUnits::addReg(), llvm::MachineInstrBuilder::addReg(), llvm::LiveRegUnits::contains(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getParent(), llvm::RegState::Implicit, llvm::MachineOperandIteratorBase::isValid(), llvm::A64CC::MI, llvm::LiveRegUnits::removeReg(), and llvm::RegState::Undef.
Referenced by MaySpeculate().
Variable Documentation
cl::opt<bool> DisableDiamond("disable-ifcvt-diamond", cl::init(false), cl::Hidden) static
cl::opt<bool> DisableSimple("disable-ifcvt-simple", cl::init(false), cl::Hidden) static
cl::opt<bool> DisableSimpleF("disable-ifcvt-simple-false", cl::init(false), cl::Hidden) static
cl::opt<bool> DisableTriangle("disable-ifcvt-triangle", cl::init(false), cl::Hidden) static
cl::opt<bool> DisableTriangleF("disable-ifcvt-triangle-false", cl::init(false), cl::Hidden) static
cl::opt<bool> DisableTriangleFR("disable-ifcvt-triangle-false-rev", cl::init(false), cl::Hidden) static
cl::opt<bool> DisableTriangleR("disable-ifcvt-triangle-rev", cl::init(false), cl::Hidden) static
cl::opt<bool> IfCvtBranchFold("ifcvt-branch-fold", cl::init(true), cl::Hidden) static
cl::opt<int> IfCvtFnStart("ifcvt-fn-start", cl::init(-1), cl::Hidden) static
cl::opt<int> IfCvtFnStop("ifcvt-fn-stop", cl::init(-1), cl::Hidden) static
cl::opt<int> IfCvtLimit("ifcvt-limit", cl::init(-1), cl::Hidden) static