LLVM: InlineSpiller.cpp File Reference
LLVM API Documentation
InlineSpiller.cpp File Reference
#include "Spiller.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/TinyPtrVector.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/CodeGen/LiveIntervalAnalysis.h"
#include "llvm/CodeGen/LiveRangeEdit.h"
#include "llvm/CodeGen/LiveStackAnalysis.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineBlockFrequencyInfo.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineInstrBundle.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/VirtRegMap.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetMachine.h"
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "regalloc"
Functions
STATISTIC (NumSpilledRanges,"Number of spilled live ranges")
STATISTIC (NumSnippets,"Number of spilled snippets")
STATISTIC (NumSpills,"Number of spills inserted")
STATISTIC (NumSpillsRemoved,"Number of spills removed")
STATISTIC (NumReloads,"Number of reloads inserted")
STATISTIC (NumReloadsRemoved,"Number of reloads removed")
STATISTIC (NumFolded,"Number of folded stack accesses")
STATISTIC (NumFoldedLoads,"Number of folded loads")
STATISTIC (NumRemats,"Number of rematerialized defs for spilling")
STATISTIC (NumOmitReloadSpill,"Number of omitted spills of reloads")
STATISTIC (NumHoists,"Number of hoisted spills")
Spiller * llvm::createInlineSpiller (MachineFunctionPass &pass, MachineFunction &mf, VirtRegMap &vrm)
static unsigned isFullCopyOf (const MachineInstr *MI, unsigned Reg)
static raw_ostream & operator<< (raw_ostream &OS, const InlineSpiller::SibValueInfo &SVI)
static void dumpMachineInstrRangeWithSlotIndex (MachineBasicBlock::iterator B, MachineBasicBlock::iterator E, LiveIntervals const &LIS, const char *const header, unsigned VReg=0)
Variables
static cl::opt< bool > DisableHoisting ("disable-spill-hoist", cl::Hidden, cl::desc("Disable inline spill hoisting"))
Macro Definition Documentation
#define DEBUG_TYPE "regalloc"
Definition at line 15 of file InlineSpiller.cpp.
Function Documentation
static void dumpMachineInstrRangeWithSlotIndex (MachineBasicBlock::iterator B, MachineBasicBlock::iterator E, LiveIntervals const & LIS, const char *const header, unsigned VReg = 0) static
Definition at line 1009 of file InlineSpiller.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMetadata(), llvm::MachineOperandIteratorBase::analyzePhysReg(), llvm::MachineOperandIteratorBase::analyzeVirtReg(), llvm::VirtRegMap::assignVirt2StackSlot(), llvm::MachineInstrSpan::begin(), llvm::BuildMI(), llvm::LiveRangeEdit::calculateRegClassAndHint(), llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::LiveRangeEdit::createFrom(), llvm::TargetOpcode::DBG_VALUE, llvm::dbgs(), DEBUG, llvm::VNInfo::def, llvm::LiveRangeEdit::eliminateDeadDefs(), llvm::SmallVectorBase::empty(), llvm::MachineInstrSpan::empty(), llvm::MachineInstrSpan::end(), llvm::MachineBasicBlock::erase(), llvm::MachineInstr::eraseFromParent(), llvm::LiveRangeEdit::eraseVirtReg(), llvm::TargetInstrInfo::foldMemoryOperand(), llvm::MCInstrInfo::get(), llvm::LiveIntervals::getCachedRegUnit(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::LiveIntervals::getInstructionIndex(), llvm::LiveStacks::getInterval(), llvm::LiveIntervals::getInterval(), llvm::MachineOperand::getMetadata(), llvm::Intrinsic::getName(), llvm::LiveRange::getNextValue(), llvm::MachineInstr::getNumOperands(), llvm::LiveRange::getNumValNums(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::LiveStacks::getOrCreateInterval(), llvm::VirtRegMap::getOriginal(), llvm::MachineInstr::getParent(), llvm::LiveRangeEdit::getParent(), llvm::MachineBasicBlock::getParent(), llvm::LiveRangeEdit::getReg(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::SlotIndex::getRegSlot(), llvm::VirtRegMap::getStackSlot(), llvm::MachineOperand::getSubReg(), llvm::LiveRange::getValNumInfo(), llvm::LiveStacks::getVNInfoAllocator(), llvm::LiveRange::getVNInfoAt(), i, I, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::LiveIntervals::InsertMachineInstrInMaps(), llvm::LiveIntervals::InsertMachineInstrRangeInMaps(), llvm::MachineInstr::isBundled(), llvm::MachineInstr::isCopy(), llvm::MachineOperand::isDead(), llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isEarlyClobber(), isFullCopyOf(), llvm::MachineOperand::isImplicit(), llvm::MachineInstr::isIndirectDebugValue(), llvm::MachineOperand::isReg(), llvm::MachineInstr::isRegTiedToDefOperand(), llvm::MachineRegisterInfo::isReserved(), llvm::SlotIndex::isSameInstr(), llvm::LiveInterval::isSpillable(), llvm::TargetRegisterInfo::isStackSlot(), llvm::MachineOperand::isUse(), llvm::MachineOperandIteratorBase::isValid(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::TargetInstrInfo::loadRegFromStackSlot(), llvm::LiveRange::MergeSegmentsInAsValue(), llvm::A64CC::MI, MII, llvm::next(), llvm::VirtRegMap::NO_STACK_SLOT, llvm::TargetOpcode::PATCHPOINT, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::MachineRegisterInfo::reg_begin(), llvm::LiveIntervals::RemoveMachineInstrFromMaps(), llvm::MachineInstr::RemoveOperand(), llvm::LiveIntervals::ReplaceMachineInstrInMaps(), llvm::MachineOperand::setIsDead(), llvm::MachineOperand::setIsKill(), llvm::MachineOperand::setReg(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::SmallVectorTemplateCommon< T, typename >::size(), spill, llvm::TargetOpcode::STACKMAP, and llvm::TargetInstrInfo::storeRegToStackSlot().
static unsigned isFullCopyOf (const MachineInstr * MI, unsigned Reg) static
isFullCopyOf - If MI is a COPY to or from Reg, return the other register, otherwise return 0.
Definition at line 212 of file InlineSpiller.cpp.
References llvm::SmallVectorImpl< T >::assign(), llvm::SmallPtrSetImpl::clear(), llvm::dbgs(), DEBUG, llvm::LiveIntervals::getInterval(), llvm::LiveRange::getNumValNums(), llvm::MachineInstr::getOperand(), llvm::VirtRegMap::getOriginal(), llvm::LiveRangeEdit::getReg(), llvm::MachineOperand::getReg(), llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::LiveIntervals::intervalIsInOneMBB(), llvm::MachineInstr::isFullCopy(), llvm::TargetInstrInfo::isLoadFromStackSlot(), llvm::TargetInstrInfo::isStoreToStackSlot(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::A64CC::MI, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::LiveInterval::reg, llvm::MachineRegisterInfo::reg_begin(), and llvm::MachineRegisterInfo::reg_nodbg_begin().
Referenced by dumpMachineInstrRangeWithSlotIndex(), and operator<<().
static raw_ostream& operator<< (raw_ostream & OS, const InlineSpiller::SibValueInfo & SVI) static
Definition at line 316 of file InlineSpiller.cpp.
References llvm::MachineInstr::addRegisterDead(), llvm::MachineInstr::allDefsAreDead(), llvm::MachineOperandIteratorBase::analyzeVirtReg(), llvm::LiveRangeEdit::anyRematerializable(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::TinyPtrVector< EltTy >::begin(), llvm::MachineBasicBlock::begin(), llvm::MachineInstr::canFoldAsLoad(), llvm::LiveRangeEdit::canRematerializeAt(), llvm::LiveRangeEdit::checkRematerializable(), llvm::SmallPtrSetImpl::clear(), llvm::LiveRange::containsOneValue(), llvm::LiveRange::containsValue(), llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::LiveRangeEdit::createFrom(), llvm::dbgs(), DEBUG, llvm::VNInfo::def, DisableHoisting, llvm::MachineDominatorTree::dominates(), llvm::LiveRangeEdit::eliminateDeadDefs(), llvm::SmallVectorBase::empty(), llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::empty(), llvm::LiveRange::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::TinyPtrVector< EltTy >::end(), llvm::SmallVectorImpl< T >::erase(), llvm::MachineInstr::eraseFromParent(), llvm::LiveRangeEdit::eraseVirtReg(), llvm::MCInstrInfo::get(), llvm::SlotIndex::getBaseIndex(), llvm::LiveIntervals::getInstructionFromIndex(), llvm::LiveIntervals::getInstructionIndex(), llvm::LiveIntervals::getInterval(), llvm::MachineLoopInfo::getLoopDepth(), llvm::LiveIntervals::getMBBEndIdx(), llvm::LiveIntervals::getMBBFromIndex(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::LiveRangeEdit::getReg(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::SlotIndex::getRegSlot(), llvm::LiveRange::getValNumInfo(), llvm::LiveRange::getVNInfoAt(), llvm::LiveRange::getVNInfoBefore(), llvm::LiveIntervals::hasInterval(), i, I, llvm::VNInfo::id, if(), llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::insert(), llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::LiveIntervals::InsertMachineInstrInMaps(), llvm::MachineInstr::isCopy(), isFullCopyOf(), llvm::LiveQueryResult::isKill(), llvm::TargetInstrInfo::isLoadFromStackSlot(), llvm::VNInfo::isPHIDef(), llvm::MachineOperand::isReg(), llvm::TargetInstrInfo::isStoreToStackSlot(), llvm::VNInfo::isUnused(), llvm::MachineOperand::isUse(), llvm::TargetOpcode::KILL, llvm::LiveRangeEdit::markRematerialized(), llvm::MachineInstr::mayStore(), llvm::LiveRange::MergeValueInAsValue(), llvm::A64CC::MI, MII, llvm::LiveRangeEdit::Remat::OrigMI, llvm::LiveRangeEdit::Remat::ParentVNI, llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::pop_back_val(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_end(), llvm::TinyPtrVector< EltTy >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::LiveRange::Query(), llvm::LiveInterval::reg, llvm::LiveRangeEdit::rematerializeAt(), llvm::LiveIntervals::RemoveMachineInstrFromMaps(), llvm::NVPTX::PTXCvtMode::RM, llvm::MachineInstr::setDesc(), llvm::MachineOperand::setIsKill(), llvm::MachineOperand::setIsUndef(), llvm::MachineOperand::setReg(), llvm::TinyPtrVector< EltTy >::size(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::MachineBasicBlock::SkipPHIsAndLabels(), llvm::TargetInstrInfo::storeRegToStackSlot(), llvm::tie(), llvm::MachineRegisterInfo::use_nodbg_begin(), llvm::LiveQueryResult::valueIn(), llvm::LiveRange::vni_begin(), and llvm::LiveRange::vni_end().
STATISTIC (NumSpilledRanges , "Number of spilled live ranges")
STATISTIC (NumSnippets , "Number of spilled snippets")
STATISTIC (NumSpills , "Number of spills inserted")
STATISTIC (NumSpillsRemoved , "Number of spills removed")
STATISTIC (NumReloads , "Number of reloads inserted")
STATISTIC (NumReloadsRemoved , "Number of reloads removed")
STATISTIC (NumFolded , "Number of folded stack accesses")
STATISTIC (NumFoldedLoads , "Number of folded loads")
STATISTIC (NumRemats , "Number of rematerialized defs for spilling")
STATISTIC (NumOmitReloadSpill , "Number of omitted spills of reloads")
STATISTIC (NumHoists , "Number of hoisted spills")
Variable Documentation
cl::opt<bool> DisableHoisting("disable-spill-hoist", cl::Hidden, cl::desc("Disable inline spill hoisting")) static
Referenced by operator<<().