LLVM: InstrEmitter.cpp File Reference
LLVM API Documentation
InstrEmitter.cpp File Reference
#include "InstrEmitter.h"
#include "SDNodeDbgValue.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/StackMaps.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetMachine.h"
Macros
#define DEBUG_TYPE "instr-emitter"
Functions
static unsigned countOperands (SDNode *Node, unsigned NumExpUses, unsigned &NumImpUses)
Variables
const unsigned MinRCSize = 4
Macro Definition Documentation
#define DEBUG_TYPE "instr-emitter"
Definition at line 16 of file InstrEmitter.cpp.
Function Documentation
static unsigned countOperands (SDNode * Node, unsigned NumExpUses, unsigned & NumImpUses) static
countOperands - The inputs to target nodes have any actual inputs first, followed by an optional chain operand, then an optional glue operand. Compute the number of actual operands that will go into the resulting MachineInstr.
Also count physreg RegisterSDNode and RegisterMaskSDNode operands preceding the chain and glue. These operands may be implicit on the machine instr.
Definition at line 59 of file InstrEmitter.cpp.
References llvm::MachineInstrBuilder::addBlockAddress(), llvm::MachineInstrBuilder::addConstantPoolIndex(), llvm::MachineInstrBuilder::addExternalSymbol(), llvm::MachineInstrBuilder::addFPImm(), llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addGlobalAddress(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addJumpTableIndex(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineInstrBuilder::addRegMask(), llvm::MachineInstrBuilder::addTargetIndex(), Align, llvm::BuildMI(), llvm::MachineRegisterInfo::clearKillFlags(), llvm::MachineRegisterInfo::constrainRegClass(), llvm::TargetOpcode::COPY, llvm::ISD::CopyFromReg, llvm::ISD::CopyToReg, llvm::InstrEmitter::CountResults(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::RegState::Define, llvm::dyn_cast(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::erase(), llvm::TargetOpcode::EXTRACT_SUBREG, F(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::find(), llvm::MCInstrInfo::get(), llvm::TargetRegisterInfo::getAllocatableClass(), llvm::TargetRegisterInfo::getCommonSubClass(), llvm::MachineFunction::getConstantPool(), llvm::MachineConstantPool::getConstantPoolIndex(), llvm::TargetRegisterClass::getCopyCost(), llvm::TargetMachine::getDataLayout(), llvm::SDValue::getDebugLoc(), llvm::SDNode::getDebugLoc(), llvm::getDebugRegState(), llvm::getDefRegState(), llvm::MachineInstr::getDesc(), llvm::getImplRegState(), llvm::getKillRegState(), llvm::SDValue::getMachineOpcode(), llvm::SDNode::getMachineOpcode(), llvm::TargetRegisterInfo::getMatchingSuperRegClass(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::SDValue::getNode(), llvm::MCInstrDesc::getNumDefs(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getNumOperands(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOpcode(), llvm::MachineInstr::getOperand(), llvm::SDNode::getOperand(), llvm::MCInstrDesc::getOperandConstraint(), llvm::DataLayout::getPrefTypeAlignment(), getReg(), llvm::RegisterSDNode::getReg(), llvm::TargetInstrInfo::getRegClass(), llvm::MachineRegisterInfo::getRegClass(), llvm::TargetRegisterInfo::getRegClass(), llvm::TargetLoweringBase::getRegClassFor(), llvm::SDValue::getResNo(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::TargetRegisterInfo::getSubClassWithSubReg(), llvm::DataLayout::getTypeAllocSize(), llvm::SDValue::getValueType(), llvm::MachineRegisterInfo::getVRegDef(), llvm::ConstantSDNode::getZExtValue(), llvm::MVT::Glue, llvm::SDValue::hasOneUse(), llvm::SDNode::hasOneUse(), llvm::TargetRegisterClass::hasSubClassEq(), llvm::TargetRegisterClass::hasType(), i, I, llvm::TargetOpcode::IMPLICIT_DEF, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::insert(), llvm::MachineBasicBlock::insert(), llvm::TargetOpcode::INSERT_SUBREG, llvm::TargetInstrInfo::isCoalescableExtInstr(), llvm::MachineOperand::isImplicit(), llvm::SDValue::isMachineOpcode(), llvm::SDNode::isMachineOpcode(), llvm::MCOperandInfo::isOptionalDef(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::MachineOperand::isReg(), llvm::TargetLoweringBase::isTypeLegal(), llvm::MCInstrDesc::isVariadic(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm_unreachable, MinRCSize, N, llvm::MCInstrDesc::OpInfo, llvm::MVT::Other, llvm::TargetOpcode::REG_SEQUENCE, llvm::NVPTX::PTXCvtMode::RM, llvm::NVPTX::PTXCvtMode::RN, llvm::MachineRegisterInfo::setRegClass(), llvm::TargetOpcode::SUBREG_TO_REG, llvm::MCOI::TIED_TO, llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
Referenced by llvm::InstrEmitter::EmitDbgValue().
Variable Documentation
const unsigned MinRCSize = 4
MinRCSize - Smallest register class we allow when constraining virtual registers. If satisfying all register class constraints would require using a smaller register class, emit a COPY to a new virtual register instead.
Definition at line 38 of file InstrEmitter.cpp.
Referenced by countOperands().