LLVM: InstCombineCalls.cpp File Reference
LLVM API Documentation
InstCombineCalls.cpp File Reference
#include "InstCombine.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/MemoryBuiltins.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/Support/CallSite.h"
#include "llvm/Support/PatternMatch.h"
#include "llvm/Transforms/Utils/BuildLibCalls.h"
#include "llvm/Transforms/Utils/Local.h"
Functions
STATISTIC (NumSimplified,"Number of library calls simplified")
static Type * getPromotedType (Type *Ty)
static Type * reduceToSingleValueType (Type *T)
static bool isSafeToEliminateVarargsCast (const CallSite CS, const CastInst *const CI, const DataLayout *const TD, const int ix)
static IntrinsicInst * FindInitTrampolineFromAlloca (Value *TrampMem)
static IntrinsicInst * FindInitTrampolineFromBB (IntrinsicInst *AdjustTramp, Value *TrampMem)
static IntrinsicInst * FindInitTrampoline (Value *Callee)
Function Documentation
static IntrinsicInst* FindInitTrampoline (Value * Callee) static
Definition at line 862 of file InstCombineCalls.cpp.
References llvm::Intrinsic::adjust_trampoline, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_begin(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_end(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_size(), B, llvm::Attribute::ByVal, llvm::CastInst::Create(), llvm::CallInst::Create(), llvm::InvokeInst::Create(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::doesNotThrow(), llvm::dyn_cast(), FindInitTrampolineFromAlloca(), FindInitTrampolineFromBB(), llvm::FunctionType::get(), llvm::UndefValue::get(), llvm::CallInst::getArgOperand(), llvm::Function::getAttributes(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getAttributes(), llvm::ConstantExpr::getBitCast(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledValue(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCallingConv(), llvm::CallInst::getCallingConv(), llvm::CastInst::getCastOpcode(), llvm::Value::getContext(), llvm::Type::getContext(), llvm::Function::getContext(), llvm::Instruction::getDebugLoc(), llvm::SequentialType::getElementType(), llvm::AttributeSet::getFnAttributes(), llvm::Function::getFunctionType(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getInstruction(), llvm::Type::getInt1PtrTy(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Constant::getNullValue(), llvm::FunctionType::getNumParams(), llvm::AttributeSet::getNumSlots(), llvm::User::getOperand(), llvm::AttributeSet::getParamAttributes(), llvm::FunctionType::getParamType(), llvm::Type::getPointerElementType(), getPromotedType(), llvm::FunctionType::getReturnType(), llvm::AttributeSet::getSlotAttributes(), llvm::AttributeSet::getSlotIndex(), llvm::ConstantInt::getTrue(), llvm::GlobalValue::getType(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::PointerType::getUnqual(), llvm::AttributeSet::hasAttribute(), llvm::AttributeSet::hasAttributes(), llvm::AttrBuilder::hasAttributes(), i, I, llvm::isAllocLikeFn(), llvm::CastInst::isBitCastable(), llvm::GlobalValue::isDeclaration(), llvm::AttributeSet::isEmpty(), isSafeToEliminateVarargsCast(), llvm::Type::isSized(), llvm::Type::isStructTy(), llvm::CallInst::isTailCall(), llvm::FunctionType::isVarArg(), llvm::Type::isVoidTy(), IT, NC, llvm::Attribute::Nest, llvm::A64CC::NV, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorImpl< T >::reserve(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setCalledFunction(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setDoesNotThrow(), llvm::Value::setName(), llvm::Value::stripPointerCasts(), llvm::Attribute::StructRet, llvm::Value::takeName(), llvm::AttributeFuncs::typeIncompatible(), and llvm::Value::use_empty().
static IntrinsicInst* FindInitTrampolineFromAlloca (Value * TrampMem) static
Definition at line 801 of file InstCombineCalls.cpp.
References llvm::Intrinsic::adjust_trampoline, llvm::dyn_cast(), llvm::IntrinsicInst::getIntrinsicID(), llvm::User::getOperand(), llvm::Value::hasOneUse(), I, llvm::Intrinsic::init_trampoline, llvm::Value::stripPointerCasts(), llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by FindInitTrampoline().
static IntrinsicInst* FindInitTrampolineFromBB (IntrinsicInst * AdjustTramp, Value * TrampMem) static
Definition at line 841 of file InstCombineCalls.cpp.
References llvm::BasicBlock::begin(), llvm::Instruction::getParent(), I, llvm::Intrinsic::init_trampoline, and llvm::Instruction::mayWriteToMemory().
Referenced by FindInitTrampoline().
static Type* getPromotedType (Type * Ty) static
getPromotedType - Return the specified type promoted as it would be to pass though a va_arg area.
Definition at line 29 of file InstCombineCalls.cpp.
References llvm::Type::getContext(), and llvm::Type::getInt32Ty().
Referenced by FindInitTrampoline().
static bool isSafeToEliminateVarargsCast (const CallSite CS, const CastInst *const CI, const DataLayout *const TD, const int ix) static
isSafeToEliminateVarargsCast - If this cast does not affect the value passed through the varargs area, we can eliminate the use of the cast.
Definition at line 763 of file InstCombineCalls.cpp.
References llvm::CallInst::getCalledFunction(), llvm::User::getOperand(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isByValArgument(), llvm::CastInst::isLosslessCast(), llvm::Type::isSized(), and llvm::Value::use_empty().
Referenced by FindInitTrampoline().
static Type* reduceToSingleValueType (Type * T) static
reduceToSingleValueType - Given an aggregate type which ultimately holds a single scalar element, like {{{type}}} or [1 x type], return type.
Definition at line 39 of file InstCombineCalls.cpp.
References llvm::dyn_cast(), llvm::IntegerType::get(), llvm::ConstantInt::get(), llvm::PointerType::get(), llvm::MemIntrinsic::getAlignment(), llvm::MemIntrinsic::getAlignmentType(), llvm::CallInst::getArgOperand(), llvm::Value::getContext(), llvm::MemIntrinsic::getDest(), llvm::getKnownAlignment(), llvm::MemIntrinsic::getLength(), llvm::ConstantInt::getLimitedValue(), llvm::Instruction::getMetadata(), llvm::Constant::getNullValue(), llvm::Value::getType(), llvm::ConstantInt::getType(), llvm::MemSetInst::getValue(), llvm::Type::isIntegerTy(), llvm::isPowerOf2_32(), llvm::Type::isSingleValueType(), llvm::Type::isSized(), llvm::MemIntrinsic::isVolatile(), M, llvm::LLVMContext::MD_tbaa, llvm::LLVMContext::MD_tbaa_struct, llvm::A64CC::MI, llvm::MinAlign(), S, llvm::MemIntrinsic::setAlignment(), llvm::LoadInst::setAlignment(), llvm::StoreInst::setAlignment(), llvm::CallInst::setArgOperand(), llvm::MemIntrinsic::setLength(), llvm::Instruction::setMetadata(), llvm::Value::stripPointerCasts(), and T.
STATISTIC (NumSimplified , "Number of library calls simplified")