LLVM: InstCombineAddSub.cpp File Reference
LLVM API Documentation
InstCombineAddSub.cpp File Reference
#include "InstCombine.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/Support/GetElementPtrTypeIterator.h"
#include "llvm/Support/PatternMatch.h"
Functions
static Constant * AddOne (Constant *C)
AddOne - Add one to a ConstantInt.
static Constant * SubOne (ConstantInt *C)
SubOne - Subtract one from a ConstantInt.
static Value * dyn_castFoldableMul (Value *V, ConstantInt *&CST)
Function Documentation
static Constant* AddOne (Constant * C) static
AddOne - Add one to a ConstantInt.
Definition at line 849 of file InstCombineAddSub.cpp.
References llvm::ConstantInt::get(), llvm::ConstantExpr::getAdd(), and llvm::Value::getType().
Referenced by llvm::ScalarEvolution::getAddExpr(), llvm::InstCombiner::visitAdd(), and llvm::InstCombiner::visitSub().
static Value* dyn_castFoldableMul (Value * V, ConstantInt *& CST) inline static
Definition at line 864 of file InstCombineAddSub.cpp.
References llvm::ComputeNumSignBits(), llvm::dyn_cast(), llvm::ConstantInt::get(), getBitWidth(), llvm::Type::getContext(), llvm::ConstantInt::getLimitedValue(), llvm::APInt::getOneBitSet(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm::Value::hasOneUse(), and llvm::Type::isIntegerTy().
Referenced by llvm::InstCombiner::visitAdd(), and llvm::InstCombiner::visitSub().
static Constant* SubOne (ConstantInt * C) static
SubOne - Subtract one from a ConstantInt.
Definition at line 854 of file InstCombineAddSub.cpp.
References llvm::ConstantInt::get(), llvm::Value::getContext(), and llvm::ConstantInt::getValue().
Referenced by llvm::InstCombiner::visitAdd(), and llvm::InstCombiner::visitSub().