LLVM: InstCombineSimplifyDemanded.cpp File Reference
LLVM API Documentation
InstCombineSimplifyDemanded.cpp File Reference
#include "InstCombine.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/Support/PatternMatch.h"
Functions
static bool ShrinkDemandedConstant (Instruction *I, unsigned OpNo, APInt Demanded)
Function Documentation
static bool ShrinkDemandedConstant (Instruction * I, unsigned OpNo, APInt Demanded) static
ShrinkDemandedConstant - Check to see if the specified operand of the specified instruction is a constant integer. If so, check to see if there are any bits set in the constant that are not demanded. If so, shrink the constant and return true.
Definition at line 28 of file InstCombineSimplifyDemanded.cpp.
References llvm::APInt::abs(), llvm::APIntOps::And(), llvm::APInt::ashr(), llvm::Intrinsic::bswap, C1, llvm::Call, llvm::APInt::clearAllBits(), llvm::APInt::clearBit(), llvm::ComputeMaskedBits(), llvm::APInt::countLeadingZeros(), llvm::APInt::countTrailingZeros(), llvm::ExtractElementInst::Create(), llvm::InsertElementInst::Create(), llvm::dyn_cast(), llvm::ConstantInt::get(), llvm::Use::get(), llvm::ConstantVector::get(), llvm::UndefValue::get(), llvm::Constant::getAggregateElement(), llvm::APInt::getAllOnesValue(), llvm::CallInst::getArgOperand(), llvm::APInt::getBitsSet(), llvm::APInt::getBitWidth(), llvm::Value::getContext(), llvm::APInt::getHighBitsSet(), llvm::Type::getInt32Ty(), llvm::Type::getIntegerBitWidth(), llvm::Constant::getIntegerValue(), llvm::IntrinsicInst::getIntrinsicID(), llvm::APInt::getLowBitsSet(), llvm::ShuffleVectorInst::getMaskValue(), llvm::Value::getName(), llvm::Constant::getNullValue(), llvm::VectorType::getNumElements(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::User::getOperandUse(), llvm::Type::getScalarSizeInBits(), llvm::Type::getScalarType(), llvm::APInt::getSignBit(), llvm::Value::getType(), llvm::ConstantInt::getType(), llvm::ConstantInt::getValue(), llvm::ConstantInt::getZExtValue(), llvm::APInt::getZExtValue(), llvm::BinaryOperator::hasNoSignedWrap(), llvm::BinaryOperator::hasNoUnsignedWrap(), llvm::Value::hasOneUse(), i, I, llvm::APInt::isAllOnesValue(), llvm::Type::isIntOrIntVectorTy(), llvm::APInt::isNegative(), llvm::Type::isPointerTy(), llvm::APInt::isPowerOf2(), llvm::APInt::isSignBit(), llvm::Type::isVectorTy(), llvm_unreachable, llvm::APInt::lshr(), llvm::APIntOps::lshr(), llvm::PatternMatch::m_ConstantInt(), llvm::PatternMatch::m_Shr(), llvm::PatternMatch::m_Value(), llvm::PatternMatch::match(), llvm::APIntOps::Or(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::MCID::Select, llvm::CallInst::setArgOperand(), llvm::APInt::setBit(), llvm::BinaryOperator::setHasNoSignedWrap(), llvm::BinaryOperator::setIsExact(), llvm::User::setOperand(), llvm::APInt::shl(), llvm::Value::takeName(), llvm::APInt::trunc(), llvm::APInt::uge(), llvm::APInt::ult(), llvm::RegState::Undef, llvm::Intrinsic::x86_sse2_max_sd, llvm::Intrinsic::x86_sse2_min_sd, llvm::Intrinsic::x86_sse2_mul_sd, llvm::Intrinsic::x86_sse2_sub_sd, llvm::Intrinsic::x86_sse42_crc32_64_64, llvm::Intrinsic::x86_sse_max_ss, llvm::Intrinsic::x86_sse_min_ss, llvm::Intrinsic::x86_sse_mul_ss, llvm::Intrinsic::x86_sse_sub_ss, llvm::APIntOps::Xor(), llvm::APInt::zext(), and llvm::APInt::zextOrTrunc().
Referenced by llvm::TargetLowering::TargetLoweringOpt::CombineTo().