LLVM: Internalize.cpp File Reference
LLVM API Documentation
Internalize.cpp File Reference
#include "llvm/Transforms/IPO.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/CallGraph.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/GlobalStatus.h"
#include "llvm/Transforms/Utils/ModuleUtils.h"
#include <fstream>
#include <set>
Macros
#define DEBUG_TYPE "internalize"
Functions
STATISTIC (NumAliases,"Number of aliases internalized")
STATISTIC (NumFunctions,"Number of functions internalized")
STATISTIC (NumGlobals,"Number of global vars internalized")
INITIALIZE_PASS (InternalizePass,"internalize","Internalize Global Symbols", false, false) InternalizePass
static bool shouldInternalize (const GlobalValue &GV, const std::set< std::string > &ExternalNames)
Variables
static cl::opt< std::string > APIFile ("internalize-public-api-file", cl::value_desc("filename"), cl::desc("A file containing list of symbol names to preserve"))
static cl::list< std::string > APIList ("internalize-public-api-list", cl::value_desc("list"), cl::desc("A list of symbol names to preserve"), cl::CommaSeparated)
Macro Definition Documentation
#define DEBUG_TYPE "internalize"
Definition at line 22 of file Internalize.cpp.
Function Documentation
INITIALIZE_PASS (InternalizePass , "internalize" , "Internalize Global Symbols" , false , false)
Definition at line 72 of file Internalize.cpp.
References APIFile, APIList, llvm::ArrayRef< T >::begin(), llvm::ArrayRef< T >::end(), llvm::errs(), llvm::PassRegistry::getPassRegistry(), llvm::tgtok::In, llvm::initializeInternalizePassPass(), and llvm::ARMBuildAttrs::Symbol.
static bool shouldInternalize (const GlobalValue & GV, const std::set< std::string > & ExternalNames) static
Definition at line 108 of file Internalize.cpp.
References llvm::Module::alias_begin(), llvm::Module::alias_end(), llvm::SmallPtrSet< PtrType, SmallSize >::begin(), llvm::Module::begin(), llvm::collectUsedGlobalVariables(), llvm::dbgs(), DEBUG, llvm::SmallPtrSet< PtrType, SmallSize >::end(), llvm::Module::end(), llvm::CallGraph::getExternalCallingNode(), llvm::Value::getName(), llvm::Module::global_begin(), llvm::Module::global_end(), llvm::GlobalValue::hasAvailableExternallyLinkage(), llvm::GlobalValue::hasLocalLinkage(), I, llvm::GlobalValue::InternalLinkage, llvm::GlobalValue::isDeclaration(), and M.
STATISTIC (NumAliases , "Number of aliases internalized")
STATISTIC (NumFunctions , "Number of functions internalized")
STATISTIC (NumGlobals , "Number of global vars internalized")
Variable Documentation
cl::opt<std::string> APIFile("internalize-public-api-file", cl::value_desc("filename"), cl::desc("A file containing list of symbol names to preserve")) static
Referenced by INITIALIZE_PASS().
cl::list<std::string> APIList("internalize-public-api-list", cl::value_desc("list"), cl::desc("A list of symbol names to preserve"), cl::CommaSeparated) static
Referenced by INITIALIZE_PASS().