LLVM: IPConstantPropagation.cpp File Reference
LLVM API Documentation
IPConstantPropagation.cpp File Reference
#include "llvm/Transforms/IPO.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include "llvm/Support/CallSite.h"
Macros
#define DEBUG_TYPE "ipconstprop"
Functions
STATISTIC (NumArgumentsProped,"Number of args turned into constants")
STATISTIC (NumReturnValProped,"Number of return values turned into constants")
INITIALIZE_PASS (IPCP,"ipconstprop","Interprocedural constant propagation", false, false) ModulePass *llvm
Macro Definition Documentation
#define DEBUG_TYPE "ipconstprop"
Definition at line 18 of file IPConstantPropagation.cpp.
Function Documentation
INITIALIZE_PASS (IPCP , "ipconstprop" , "Interprocedural constant propagation" , false , false)
Definition at line 50 of file IPConstantPropagation.cpp.
References llvm::ARM_PROC::A, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_begin(), llvm::Function::arg_begin(), llvm::Function::arg_empty(), llvm::Function::arg_size(), BB, llvm::Function::begin(), llvm::Module::begin(), llvm::Call, llvm::dyn_cast(), llvm::Function::end(), llvm::Module::end(), llvm::Instruction::eraseFromParent(), F(), llvm::FindInsertedValue(), llvm::UndefValue::get(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getArgument(), llvm::StructType::getElementType(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getInstruction(), llvm::StructType::getNumElements(), llvm::Function::getReturnType(), i, I, index, llvm::MipsISD::Ins, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isCallee(), llvm::Type::isVoidTy(), M, llvm::GlobalValue::mayBeOverridden(), llvm::Function::onlyReadsMemory(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::SmallVectorImpl< T >::resize(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::Value::use_begin(), llvm::Value::use_empty(), and llvm::Value::use_end().
STATISTIC (NumArgumentsProped , "Number of args turned into constants")
STATISTIC (NumReturnValProped , "Number of return values turned into constants")