LLVM: JIT.cpp File Reference
LLVM API Documentation
JIT.cpp File Reference
#include "JIT.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/CodeGen/JITCodeEmitter.h"
#include "llvm/CodeGen/MachineCodeInfo.h"
#include "llvm/Config/config.h"
#include "llvm/ExecutionEngine/GenericValue.h"
#include "llvm/ExecutionEngine/JITEventListener.h"
#include "llvm/ExecutionEngine/JITMemoryManager.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Instructions.h"
#include "llvm/Support/Dwarf.h"
#include "llvm/Support/DynamicLibrary.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/MutexGuard.h"
#include "llvm/Target/TargetJITInfo.h"
#include "llvm/Target/TargetMachine.h"
Functions
void LLVMLinkInJIT ()
void * getPointerToNamedFunction (const char *Name)
Function Documentation
void* getPointerToNamedFunction (const char * Name)
Definition at line 131 of file JIT.cpp.
References llvm::JITMemoryManager::CreateDefaultMemManager(), M, llvm::report_fatal_error(), and llvm::SystemZISD::TM.
Referenced by llvm::JIT::create(), llvm::JIT::createJIT(), llvm::ExecutionEngine::getDataLayout(), llvm::JIT::getPointerToFunction(), llvm::MCJIT::getPointerToFunction(), and jit_noop().