LLVM: JITEmitter.cpp File Reference
LLVM API Documentation
JITEmitter.cpp File Reference
#include "JIT.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/OwningPtr.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/ValueMap.h"
#include "llvm/CodeGen/JITCodeEmitter.h"
#include "llvm/CodeGen/MachineCodeInfo.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRelocation.h"
#include "llvm/DebugInfo.h"
#include "llvm/ExecutionEngine/GenericValue.h"
#include "llvm/ExecutionEngine/JITEventListener.h"
#include "llvm/ExecutionEngine/JITMemoryManager.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Disassembler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/Memory.h"
#include "llvm/Support/MutexGuard.h"
#include "llvm/Support/ValueHandle.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetJITInfo.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include <algorithm>
#include <iomanip>
Macros
#define DEBUG_TYPE "jit"
Functions
STATISTIC (NumBytes,"Number of bytes of machine code compiled")
STATISTIC (NumRelos,"Number of relocations applied")
STATISTIC (NumRetries,"Number of retries with more memory")
static bool isNonGhostDeclaration (const Function *F)
static unsigned GetConstantPoolSizeInBytes (MachineConstantPool *MCP, const DataLayout *TD)
Macro Definition Documentation
#define DEBUG_TYPE "jit"
Definition at line 15 of file JITEmitter.cpp.
Function Documentation
static unsigned GetConstantPoolSizeInBytes (MachineConstantPool * MCP, const DataLayout * TD) static
Definition at line 749 of file JITEmitter.cpp.
References Align, llvm::JITCodeEmitter::allocateSpace(), llvm::MachineFunction::begin(), llvm::ISD::ConstantPool, llvm::MachineConstantPoolEntry::ConstVal, llvm::dbgs(), DEBUG, llvm::sys::disassembleBuffer(), llvm::MachineJumpTableInfo::EK_BlockAddress, llvm::MachineJumpTableInfo::EK_Custom32, llvm::MachineJumpTableInfo::EK_GPRel32BlockAddress, llvm::MachineJumpTableInfo::EK_GPRel64BlockAddress, llvm::MachineJumpTableInfo::EK_Inline, llvm::MachineJumpTableInfo::EK_LabelDifference32, llvm::MachineFunction::end(), F(), llvm::GlobalValue::getAlignment(), llvm::MachineConstantPoolEntry::getAlignment(), llvm::MachineRelocation::getBasicBlock(), llvm::MachineFunction::getConstantPool(), llvm::MachineConstantPool::getConstantPoolAlignment(), llvm::MachineRelocation::getConstantPoolIndex(), llvm::MachineConstantPool::getConstants(), llvm::MachineJumpTableInfo::getEntryAlignment(), llvm::MachineJumpTableInfo::getEntryKind(), llvm::MachineJumpTableInfo::getEntrySize(), llvm::MachineRelocation::getExternalSymbol(), llvm::MachineFunction::getFunction(), llvm::MachineRelocation::getGlobalValue(), llvm::MachineRelocation::getJumpTableIndex(), llvm::MachineFunction::getJumpTableInfo(), llvm::MachineJumpTableInfo::getJumpTables(), llvm::MachineRelocation::getMachineCodeOffset(), llvm::MachineFunction::getName(), llvm::MachineConstantPoolEntry::getType(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::sys::hasDisassembler(), i, llvm::sys::Memory::InvalidateInstructionCache(), llvm::MachineRelocation::isBasicBlock(), llvm::MachineRelocation::isConstantPoolIndex(), llvm::MachineRelocation::isExternalSymbol(), llvm::MachineRelocation::isGlobalValue(), llvm::MachineRelocation::isGOTRelative(), llvm::MachineRelocation::isIndirectSymbol(), llvm::MachineRelocation::isJumpTableIndex(), llvm::MachineConstantPoolEntry::isMachineConstantPoolEntry(), j(), llvm::ISD::JumpTable, llvm::MachineRelocation::letTargetResolve(), llvm_unreachable, llvm::MachineRelocation::mayNeedFarStub(), llvm::Intrinsic::memcpy, llvm::report_fatal_error(), llvm::ValueMapIterator< DenseMapT, KeyT >::ValueTypeProxy::second, llvm::MachineRelocation::setGOTIndex(), llvm::MachineRelocation::setResultPointer(), llvm::StringRef::size(), size, llvm::Function::size(), llvm::MachineConstantPoolEntry::Val, and llvm::raw_ostream::write_hex().
static bool isNonGhostDeclaration (const Function * F) static
Definition at line 63 of file JITEmitter.cpp.
References llvm::JIT::addPointerToBasicBlock(), llvm::JITEvent_EmittedFunctionDetails::LineStart::Address, llvm::TargetJITInfo::StubLayout::Alignment, llvm::JITMemoryManager::AllocateGOT(), llvm::tgtok::Code, llvm::ISD::ConstantPool, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::count(), llvm::JITMemoryManager::CreateDefaultMemManager(), llvm::dbgs(), DEBUG, F(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::find(), llvm::MachineBasicBlock::getBasicBlock(), llvm::JIT::getJITInfo(), llvm::TargetJITInfo::getLazyResolverFunction(), llvm::Value::getName(), llvm::MachineBasicBlock::getNumber(), llvm::DebugLoc::getScope(), llvm::MachineBasicBlock::hasAddressTaken(), llvm::GlobalValue::hasAvailableExternallyLinkage(), llvm::MutexGuard::holds(), I, llvm::GlobalValue::isDeclaration(), llvm::GlobalValue::isMaterializable(), llvm::DebugLoc::isUnknown(), llvm::ISD::JumpTable, llvm_unreachable, llvm::JITEvent_EmittedFunctionDetails::LineStart::Loc, Lock, llvm::ExecutionEngine::lock, llvm::TargetJITInfo::needsGOT(), llvm::report_fatal_error(), llvm::TargetJITInfo::StubLayout::Size, and llvm::SystemZISD::TM.
STATISTIC (NumBytes , "Number of bytes of machine code compiled")
STATISTIC (NumRelos , "Number of relocations applied")
STATISTIC (NumRetries , "Number of retries with more memory")