LLVM: JITMemoryManager.cpp File Reference
LLVM API Documentation
JITMemoryManager.cpp File Reference
#include "llvm/ExecutionEngine/JITMemoryManager.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Config/config.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/DynamicLibrary.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Memory.h"
#include "llvm/Support/raw_ostream.h"
#include <cassert>
#include <climits>
#include <cstring>
#include <vector>
Macros
#define DEBUG_TYPE "jit"
Functions
STATISTIC (NumSlabs,"Number of slabs of memory allocated by the JIT")
static void runAtExitHandlers ()
static void jit_exit (int Status)
static int jit_atexit (void(*Fn)())
static int jit_noop ()
Variables
static std::vector< void(*)()> AtExitHandlers
Macro Definition Documentation
#define DEBUG_TYPE "jit"
Definition at line 14 of file JITMemoryManager.cpp.
Function Documentation
static int jit_atexit (void(*)() Fn) static
Definition at line 830 of file JITMemoryManager.cpp.
References AtExitHandlers.
Referenced by jit_noop().
static void jit_exit (int Status) static
Definition at line 824 of file JITMemoryManager.cpp.
References exit(), and runAtExitHandlers().
Referenced by jit_noop().
static int jit_noop () static
Definition at line 835 of file JITMemoryManager.cpp.
References llvm::RTDyldMemoryManager::getPointerToNamedFunction(), getPointerToNamedFunction(), jit_atexit(), jit_exit(), llvm::jit_noop(), llvm::LibFunc::memcmp, llvm::cl::Prefix, llvm::report_fatal_error(), and llvm::sys::DynamicLibrary::SearchForAddressOfSymbol().
static void runAtExitHandlers () static
runAtExitHandlers - Run any functions registered by the program's calls to atexit(3), which we intercept and store in AtExitHandlers.
Definition at line 780 of file JITMemoryManager.cpp.
References llvm::sys::DynamicLibrary::AddSymbol(), AtExitHandlers, llvm::LibFunc::fstat, llvm::LibFunc::fstat64, llvm::LibFunc::lstat, llvm::LibFunc::lstat64, llvm::LibFunc::open64, llvm::LibFunc::stat, and llvm::LibFunc::stat64.
Referenced by jit_exit().
STATISTIC (NumSlabs , "Number of slabs of memory allocated by the JIT")
Variable Documentation
std::vector<void (*)()> AtExitHandlers static
Definition at line 774 of file JITMemoryManager.cpp.
Referenced by jit_atexit(), and runAtExitHandlers().