LLVM: JumpThreading.cpp File Reference
LLVM API Documentation
JumpThreading.cpp File Reference
#include "llvm/Transforms/Scalar.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/CFG.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/LazyValueInfo.h"
#include "llvm/Analysis/Loads.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ValueHandle.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetLibraryInfo.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/SSAUpdater.h"
Macros
#define DEBUG_TYPE "jump-threading"
Enumerations
enum ConstantPreference
Functions
STATISTIC (NumThreads,"Number of jumps threaded")
STATISTIC (NumFolds,"Number of terminators folded")
STATISTIC (NumDupes,"Number of branch blocks duplicated to eliminate phi")
INITIALIZE_PASS_BEGIN (JumpThreading,"jump-threading","Jump Threading", false, false) INITIALIZE_PASS_END(JumpThreading
static unsigned getJumpThreadDuplicationCost (const BasicBlock *BB, unsigned Threshold)
static Constant * getKnownConstant (Value *Val, ConstantPreference Preference)
static unsigned GetBestDestForJumpOnUndef (BasicBlock *BB)
static bool hasAddressTakenAndUsed (BasicBlock *BB)
static BasicBlock * FindMostPopularDest (BasicBlock *BB, const SmallVectorImpl< std::pair< BasicBlock *, BasicBlock * > > &PredToDestList)
static void AddPHINodeEntriesForMappedBlock (BasicBlock *PHIBB, BasicBlock *OldPred, BasicBlock *NewPred, DenseMap< Instruction *, Value * > &ValueMap)
Variables
static cl::opt< unsigned > Threshold ("jump-threading-threshold", cl::desc("Max block size to duplicate for jump threading"), cl::init(6), cl::Hidden)
jump threading
jump Jump Threading
jump Jump false
Macro Definition Documentation
#define DEBUG_TYPE "jump-threading"
Definition at line 14 of file JumpThreading.cpp.
Enumeration Type Documentation
enum ConstantPreference
Definition at line 57 of file JumpThreading.cpp.
Function Documentation
static void AddPHINodeEntriesForMappedBlock (BasicBlock * PHIBB, BasicBlock * OldPred, BasicBlock * NewPred, DenseMap< Instruction *, Value * > & ValueMap) static
AddPHINodeEntriesForMappedBlock - We're adding 'NewPred' as a new predecessor to the PHIBB block. If it has PHI nodes, add entries for NewPred using the entries from OldPred (suitably mapped).
Definition at line 1317 of file JumpThreading.cpp.
References llvm::SSAUpdater::AddAvailableValue(), llvm::PHINode::addIncoming(), BB, llvm::BasicBlock::begin(), llvm::BasicBlock::Create(), llvm::BranchInst::Create(), llvm::dbgs(), DEBUG, llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), llvm::BasicBlock::end(), llvm::Instruction::eraseFromParent(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::find(), llvm::SelectInst::getCondition(), llvm::BasicBlock::getContext(), llvm::Instruction::getDebugLoc(), llvm::SelectInst::getFalseValue(), llvm::PHINode::getIncomingValueForBlock(), llvm::BasicBlock::getInstList(), getJumpThreadDuplicationCost(), llvm::Value::getName(), llvm::User::getNumOperands(), llvm::TerminatorInst::getNumSuccessors(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::CmpInst::getPredicate(), llvm::TerminatorInst::getSuccessor(), llvm::BranchInst::getSuccessor(), llvm::BasicBlock::getTerminator(), llvm::SelectInst::getTrueValue(), llvm::Value::hasOneUse(), i, I, llvm::SSAUpdater::Initialize(), llvm::iplist< NodeTy, Traits >::insert(), llvm::BranchInst::isConditional(), llvm::BranchInst::isUnconditional(), llvm::BasicBlock::moveAfter(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::iplist< NodeTy, Traits >::push_back(), llvm::Instruction::removeFromParent(), llvm::BasicBlock::removePredecessor(), llvm::SSAUpdater::RewriteUse(), llvm::Instruction::setDebugLoc(), llvm::Value::setName(), llvm::User::setOperand(), llvm::TerminatorInst::setSuccessor(), llvm::SimplifyInstruction(), llvm::SimplifyInstructionsInBlock(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::SplitBlockPredecessors(), llvm::SplitEdge(), Threshold, and llvm::LazyValueInfo::Unknown.
static BasicBlock* FindMostPopularDest (BasicBlock * BB, const SmallVectorImpl< std::pair< BasicBlock *, BasicBlock * > > & PredToDestList) static
FindMostPopularDest - The specified list contains multiple possible threadable destinations. Pick the one that occurs the most frequently in the list.
Definition at line 1015 of file JumpThreading.cpp.
References BB, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::begin(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::dbgs(), DEBUG, llvm::SmallVectorBase::empty(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::Instruction::eraseFromParent(), llvm::BasicBlock::front(), llvm::UndefValue::get(), GetBestDestForJumpOnUndef(), llvm::BasicBlock::getContext(), llvm::ConstantInt::getFalse(), llvm::PHINode::getIncomingBlock(), llvm::Value::getName(), llvm::PHINode::getNumIncomingValues(), llvm::TerminatorInst::getNumSuccessors(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::TerminatorInst::getSuccessor(), llvm::BasicBlock::getTerminator(), llvm::ConstantInt::getTrue(), llvm::Value::getType(), i, llvm::ConstantInt::isZero(), isZero(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::SmallVectorImpl< T >::resize(), llvm::User::setOperand(), and llvm::SmallVectorTemplateCommon< T >::size().
static unsigned GetBestDestForJumpOnUndef (BasicBlock * BB) static
GetBestDestForBranchOnUndef - If we determine that the specified block ends in an undefined jump, decide which block is best to revector to.
Since we can pick an arbitrary destination, we pick the successor with the fewest predecessors. This should reduce the in-degree of the others.
Definition at line 610 of file JumpThreading.cpp.
References llvm::TerminatorInst::getNumSuccessors(), llvm::TerminatorInst::getSuccessor(), llvm::BasicBlock::getTerminator(), i, llvm::pred_begin(), and llvm::pred_end().
Referenced by FindMostPopularDest(), and hasAddressTakenAndUsed().
static unsigned getJumpThreadDuplicationCost (const BasicBlock * BB, unsigned Threshold) static
getJumpThreadDuplicationCost - Return the cost of duplicating this block to thread across it. Stop scanning the block when passing the threshold.
Ignore PHI nodes, these will be flattened when duplication happens.
Definition at line 222 of file JumpThreading.cpp.
References llvm::FindFunctionBackedges(), llvm::BasicBlock::getFirstNonPHI(), i, I, llvm::Attribute::NoDuplicate, and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by AddPHINodeEntriesForMappedBlock().
static Constant* getKnownConstant (Value * Val, ConstantPreference Preference) static
getKnownConstant - Helper method to determine if we can thread over a terminator with the given value as its condition, and if so what value to use for that. What kind of value this is depends on whether we want an integer or a block address, but an undef is always accepted. Returns null if Val is null or not an appropriate constant.
Definition at line 305 of file JumpThreading.cpp.
References llvm::APIntOps::And(), BB, llvm::Value::DoPHITranslation(), llvm::dyn_cast(), llvm::ConstantInt::get(), llvm::ConstantExpr::get(), llvm::ConstantExpr::getCompare(), llvm::Value::getContext(), llvm::ConstantInt::getFalse(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::Type::getInt1Ty(), llvm::ConstantExpr::getNot(), llvm::PHINode::getNumIncomingValues(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Instruction::getParent(), getParent(), llvm::Type::getPrimitiveSizeInBits(), llvm::ConstantInt::getTrue(), llvm::Value::getType(), i, I, llvm::APIntOps::Or(), P, llvm::pred_begin(), llvm::pred_end(), llvm::SimplifyCmpInst(), llvm::Value::stripPointerCasts(), llvm::LazyValueInfo::Unknown, and llvm::APIntOps::Xor().
Referenced by hasAddressTakenAndUsed().
static bool hasAddressTakenAndUsed (BasicBlock * BB) static
Definition at line 628 of file JumpThreading.cpp.
References llvm::PHINode::addIncoming(), llvm::array_pod_sort(), BB, llvm::BasicBlock::begin(), llvm::ConstantFoldInstruction(), llvm::ConstantFoldTerminator(), llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::PHINode::Create(), llvm::BranchInst::Create(), llvm::dbgs(), DEBUG, llvm::dyn_cast(), llvm::BasicBlock::end(), llvm::Instruction::eraseFromParent(), llvm::FindAvailableLoadedValue(), llvm::BlockAddress::get(), llvm::UndefValue::get(), llvm::LoadInst::getAlignment(), GetBestDestForJumpOnUndef(), llvm::Instruction::getDebugLoc(), llvm::Function::getEntryBlock(), getKnownConstant(), llvm::Instruction::getMetadata(), llvm::Value::getName(), llvm::TerminatorInst::getNumSuccessors(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), getParent(), llvm::BasicBlock::getSinglePredecessor(), llvm::TerminatorInst::getSuccessor(), llvm::BranchInst::getSuccessor(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::BasicBlock::hasAddressTaken(), i, I, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::BranchInst::isConditional(), llvm::BasicBlock::isLandingPad(), llvm::LoadInst::isSimple(), llvm::LLVMContext::MD_tbaa, llvm::MergeBasicBlockIntoOnlyPred(), llvm::BasicBlock::moveBefore(), P, llvm::pred_begin(), llvm::pred_end(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::Constant::removeDeadConstantUsers(), llvm::BasicBlock::removePredecessor(), llvm::Value::replaceAllUsesWith(), llvm::AArch64ISD::Ret, llvm::Instruction::setDebugLoc(), llvm::SmallPtrSetImpl::size(), llvm::SplitBlockPredecessors(), llvm::Value::stripPointerCasts(), llvm::Value::takeName(), llvm::MCID::Terminator, llvm::LazyValueInfo::True, llvm::LazyValueInfo::Unknown, llvm::Value::use_empty(), and llvm::APIntOps::Xor().
INITIALIZE_PASS_BEGIN (JumpThreading , "jump-threading" , "Jump Threading" , false , false)
STATISTIC (NumThreads , "Number of jumps threaded")
STATISTIC (NumFolds , "Number of terminators folded")
STATISTIC (NumDupes , "Number of branch blocks duplicated to eliminate phi")
Variable Documentation
jump Jump false
Definition at line 142 of file JumpThreading.cpp.
jump threading
Definition at line 142 of file JumpThreading.cpp.
jump Jump Threading
Definition at line 142 of file JumpThreading.cpp.
cl::opt<unsigned> Threshold("jump-threading-threshold", cl::desc("Max block size to duplicate for jump threading"), cl::init(6), cl::Hidden) static
Referenced by AddPHINodeEntriesForMappedBlock().