LLVM: LegalizeDAG.cpp File Reference
LLVM API Documentation
LegalizeDAG.cpp File Reference
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Triple.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/DebugInfo.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetFrameLowering.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetMachine.h"
Functions
static void ExpandUnalignedStore (StoreSDNode *ST, SelectionDAG &DAG, const TargetLowering &TLI, SelectionDAGLegalize *DAGLegalize)
ExpandUnalignedStore - Expands an unaligned store to 2 half-size stores.
static void ExpandUnalignedLoad (LoadSDNode *LD, SelectionDAG &DAG, const TargetLowering &TLI, SDValue &ValResult, SDValue &ChainResult)
ExpandUnalignedLoad - Expands an unaligned load to 2 half-size loads.
static bool isDivRemLibcallAvailable (SDNode *Node, bool isSigned, const TargetLowering &TLI)
isDivRemLibcallAvailable - Return true if divmod libcall is available.
static bool useDivRem (SDNode *Node, bool isSigned, bool isDIV)
static bool isSinCosLibcallAvailable (SDNode *Node, const TargetLowering &TLI)
isSinCosLibcallAvailable - Return true if sincos libcall is available.
static bool canCombineSinCosLibcall (SDNode *Node, const TargetLowering &TLI, const TargetMachine &TM)
static bool useSinCos (SDNode *Node)
Function Documentation
static bool canCombineSinCosLibcall (SDNode * Node, const TargetLowering & TLI, const TargetMachine & TM) static
canCombineSinCosLibcall - Return true if sincos libcall is available and can be used to combine sin and cos.
Definition at line 2149 of file LegalizeDAG.cpp.
References llvm::TargetMachine::getTargetTriple(), llvm::Triple::GNU, isSinCosLibcallAvailable(), llvm::TargetMachine::Options, and llvm::TargetOptions::UnsafeFPMath.
Referenced by useSinCos().
static void ExpandUnalignedLoad (LoadSDNode * LD, SelectionDAG & DAG, const TargetLowering & TLI, SDValue & ValResult, SDValue & ChainResult) static
ExpandUnalignedLoad - Expands an unaligned load to 2 half-size loads.
Definition at line 430 of file LegalizeDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::ADJUST_TRAMPOLINE, Align, llvm::TargetLoweringBase::allowsUnalignedMemoryAccesses(), llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::ISD::AssertZext, llvm::ISD::ATOMIC_STORE, llvm::ISD::BITCAST, llvm::APFloat::bitcastToAPInt(), llvm::EVT::bitsGE(), llvm::EVT::bitsGT(), llvm::EVT::bitsLT(), llvm::ISD::BR_CC, llvm::ISD::BUILTIN_OP_END, llvm::ISD::CALLSEQ_END, llvm::ISD::CALLSEQ_START, CC, llvm::SelectionDAG::CreateStackTemporary(), llvm::TargetLoweringBase::Custom, llvm::SmallVectorTemplateCommon< T >::data(), llvm::dbgs(), llvm::ISD::DEBUGTRAP, llvm::SDNode::dump(), llvm::ISD::EH_RETURN, llvm::ISD::EH_SJLJ_LONGJMP, llvm::ISD::EH_SJLJ_SETJMP, llvm::SmallVectorBase::empty(), llvm::TargetLoweringBase::Expand, ExpandUnalignedStore(), llvm::ISD::EXTLOAD, llvm::ISD::EXTRACT_ELEMENT, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, llvm::ISD::FABS, llvm::ISD::FLT_ROUNDS_, llvm::ISD::FNEG, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND_INREG, llvm::ISD::FPOWI, llvm::ISD::FRAME_TO_ARGS_OFFSET, llvm::ISD::FRAMEADDR, llvm::ConstantInt::get(), llvm::ConstantVector::get(), llvm::UndefValue::get(), llvm::DataLayout::getABITypeAlignment(), llvm::LSBaseSDNode::getAddressingMode(), llvm::MemSDNode::getAlignment(), llvm::LoadSDNode::getBasePtr(), llvm::StoreSDNode::getBasePtr(), llvm::SelectionDAG::getCALLSEQ_END(), llvm::SelectionDAG::getCALLSEQ_START(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getCondCode(), llvm::TargetLoweringBase::getCondCodeAction(), llvm::SelectionDAG::getConstant(), llvm::MachinePointerInfo::getConstantPool(), llvm::SelectionDAG::getConstantPool(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::TargetLoweringBase::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::LoadSDNode::getExtensionType(), llvm::SelectionDAG::getExternalSymbol(), llvm::SelectionDAG::getExtLoad(), llvm::MachinePointerInfo::getFixedStack(), llvm::TargetMachine::getFrameLowering(), llvm::FrameIndexSDNode::getIndex(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getIntPtrConstant(), llvm::TargetLoweringBase::getLibcallCallingConv(), llvm::TargetLoweringBase::getLibcallName(), llvm::SelectionDAG::getLoad(), llvm::TargetLoweringBase::getLoadExtAction(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getNumValues(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getOperationAction(), llvm::MemSDNode::getPointerInfo(), llvm::TargetLoweringBase::getPointerTy(), llvm::DataLayout::getPrefTypeAlignment(), llvm::TargetLoweringBase::getRegisterType(), llvm::SDValue::getResNo(), llvm::EVT::getScalarType(), llvm::SelectionDAG::getSelect(), llvm::SelectionDAG::getSetCC(), llvm::ISD::getSetCCSwappedOperands(), llvm::SelectionDAG::getShiftAmountOperand(), llvm::TargetLoweringBase::getShiftAmountTy(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::EVT::getSimpleVT(), llvm::MVT::getSizeInBits(), llvm::EVT::getSizeInBits(), llvm::TargetFrameLowering::getStackAlignment(), llvm::TargetLoweringBase::getStackPointerRegisterToSaveRestore(), llvm::SelectionDAG::getStore(), llvm::EVT::getStoreSizeInBits(), llvm::MemSDNode::getTBAAInfo(), llvm::SelectionDAG::getTruncStore(), llvm::TargetLoweringBase::getTruncStoreAction(), llvm::TargetLoweringBase::getTypeAction(), llvm::EVT::getTypeForEVT(), llvm::TargetLoweringBase::getTypeToPromoteTo(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::HandleSDNode::getValue(), llvm::StoreSDNode::getValue(), llvm::ConstantFPSDNode::getValueAPF(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::SDNode::getVTList(), llvm::MachinePointerInfo::getWithOffset(), llvm::SelectionDAG::getZeroExtendInReg(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::ConstantInt::getZExtValue(), llvm::HexagonISD::Hi, i, llvm::MVT::i1, llvm::MVT::i128, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::ISD::INIT_TRAMPOLINE, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::tgtok::IntVal, llvm::TargetLoweringBase::isBigEndian(), llvm::EVT::isByteSized(), llvm::TargetLoweringBase::isCondCodeLegal(), llvm::EVT::isFloatingPoint(), llvm::TargetLowering::isInTailCallPosition(), llvm::MVT::isInteger(), llvm::EVT::isInteger(), llvm::MemSDNode::isInvariant(), llvm::TargetLoweringBase::isLittleEndian(), llvm::TargetLoweringBase::isLoadExtLegal(), llvm::MemSDNode::isNonTemporal(), llvm::TargetLowering::ArgListEntry::isSExt, llvm::TargetLoweringBase::isShuffleMaskLegal(), llvm::StoreSDNode::isTruncatingStore(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), llvm::MemSDNode::isVolatile(), llvm::TargetLowering::ArgListEntry::isZExt, llvm::A64DB::LD, llvm::TargetLoweringBase::Legal, llvm_unreachable, llvm::HexagonISD::Lo, llvm::SPII::Load, llvm::ISD::LOAD, llvm::Log2_32(), llvm::TargetLowering::LowerCallTo(), llvm::TargetLowering::LowerOperation(), llvm::APInt::lshr(), llvm::ISD::MERGE_VALUES, llvm::MinAlign(), llvm::ISD::MUL, llvm::TargetLowering::ArgListEntry::Node, llvm::ISD::NON_EXTLOAD, llvm::ISD::OR, llvm::MVT::Other, llvm::MVT::ppcf128, llvm::TargetLoweringBase::Promote, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::ISD::RETURNADDR, llvm::ISD::ROTL, llvm::ISD::ROTR, llvm::ISD::SADDO, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::ISD::SETCC_INVALID, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, llvm::ISD::SETUO, llvm::ISD::SEXTLOAD, llvm::ISD::SHL, llvm::ISD::SHL_PARTS, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::MVT::SimpleTy, llvm::ISD::SINT_TO_FP, llvm::SmallVectorTemplateCommon< T >::size(), llvm::ISD::SMULO, llvm::ISD::SRA, llvm::ISD::SRA_PARTS, llvm::ISD::SRL, llvm::ISD::SRL_PARTS, llvm::ISD::SSUBO, llvm::A64DB::ST, llvm::ISD::STACKSAVE, llvm::SPII::Store, llvm::ISD::STORE, llvm::ISD::SUB, std::swap(), llvm::ISD::TargetConstant, llvm::ISD::TokenFactor, llvm::SelectionDAG::TransferDbgValues(), llvm::ISD::TRAP, llvm::APInt::trunc(), llvm::ISD::TRUNCATE, llvm::TargetLowering::ArgListEntry::Ty, llvm::TargetLoweringBase::TypeLegal, llvm::ISD::UADDO, llvm::ISD::UINT_TO_FP, llvm::ISD::UMULO, llvm::ISD::UNDEF, llvm::ISD::UNINDEXED, llvm::SelectionDAG::UpdateNodeOperands(), llvm::ISD::USUBO, llvm::ISD::VAARG, llvm::ISD::ZERO_EXTEND, and llvm::ISD::ZEXTLOAD.
static void ExpandUnalignedStore (StoreSDNode * ST, SelectionDAG & DAG, const TargetLowering & TLI, SelectionDAGLegalize * DAGLegalize) static
ExpandUnalignedStore - Expands an unaligned store to 2 half-size stores.
Definition at line 304 of file LegalizeDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::BITCAST, llvm::SelectionDAG::CreateStackTemporary(), llvm::ISD::EXTLOAD, llvm::LSBaseSDNode::getAddressingMode(), llvm::MemSDNode::getAddressSpace(), llvm::MemSDNode::getAlignment(), llvm::StoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getExtLoad(), llvm::EVT::getHalfSizedIntegerVT(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getLoad(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getNode(), llvm::MemSDNode::getPointerInfo(), llvm::TargetLoweringBase::getPointerTy(), llvm::TargetLoweringBase::getRegisterType(), llvm::TargetLoweringBase::getShiftAmountTy(), llvm::MVT::getSizeInBits(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getStore(), llvm::MemSDNode::getTBAAInfo(), llvm::SelectionDAG::getTruncStore(), llvm::SDValue::getValue(), llvm::StoreSDNode::getValue(), llvm::SDValue::getValueType(), llvm::MachinePointerInfo::getWithOffset(), llvm::HexagonISD::Hi, i, llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::TargetLoweringBase::isLittleEndian(), llvm::MemSDNode::isNonTemporal(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), llvm::MemSDNode::isVolatile(), llvm::HexagonISD::Lo, llvm::SPII::Load, llvm::MinAlign(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::ISD::SRL, llvm::SPII::Store, llvm::ISD::TokenFactor, and llvm::ISD::UNINDEXED.
Referenced by ExpandUnalignedLoad().
static bool isDivRemLibcallAvailable (SDNode * Node, bool isSigned, const TargetLowering & TLI) static
isDivRemLibcallAvailable - Return true if divmod libcall is available.
Definition at line 2029 of file LegalizeDAG.cpp.
References llvm::TargetLoweringBase::getLibcallName(), llvm::SDNode::getSimpleValueType(), llvm::MVT::i128, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm_unreachable, llvm::RTLIB::SDIVREM_I128, llvm::RTLIB::SDIVREM_I16, llvm::RTLIB::SDIVREM_I32, llvm::RTLIB::SDIVREM_I64, llvm::RTLIB::SDIVREM_I8, llvm::MVT::SimpleTy, llvm::RTLIB::UDIVREM_I128, llvm::RTLIB::UDIVREM_I16, llvm::RTLIB::UDIVREM_I32, llvm::RTLIB::UDIVREM_I64, and llvm::RTLIB::UDIVREM_I8.
Referenced by useSinCos().
static bool isSinCosLibcallAvailable (SDNode * Node, const TargetLowering & TLI) static
isSinCosLibcallAvailable - Return true if sincos libcall is available.
Definition at line 2134 of file LegalizeDAG.cpp.
References llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, llvm::TargetLoweringBase::getLibcallName(), llvm::SDNode::getSimpleValueType(), llvm_unreachable, llvm::MVT::ppcf128, llvm::MVT::SimpleTy, llvm::RTLIB::SINCOS_F128, llvm::RTLIB::SINCOS_F32, llvm::RTLIB::SINCOS_F64, llvm::RTLIB::SINCOS_F80, and llvm::RTLIB::SINCOS_PPCF128.
Referenced by canCombineSinCosLibcall().
static bool useDivRem (SDNode * Node, bool isSigned, bool isDIV) static
useDivRem - Only issue divrem libcall if both quotient and remainder are needed.
Definition at line 2046 of file LegalizeDAG.cpp.
References llvm::SelectionDAG::CreateStackTemporary(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getExternalSymbol(), llvm::TargetLoweringBase::getLibcallCallingConv(), llvm::TargetLoweringBase::getLibcallName(), llvm::SDValue::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::Type::getPointerTo(), llvm::TargetLoweringBase::getPointerTy(), llvm::SDNode::getSimpleValueType(), llvm::EVT::getTypeForEVT(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), i, llvm::MVT::i128, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::TargetLowering::ArgListEntry::isSExt, llvm::TargetLowering::ArgListEntry::isZExt, llvm_unreachable, llvm::TargetLowering::LowerCallTo(), llvm::TargetLowering::ArgListEntry::Node, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::ISD::SDIV, llvm::ISD::SDIVREM, llvm::RTLIB::SDIVREM_I128, llvm::RTLIB::SDIVREM_I16, llvm::RTLIB::SDIVREM_I32, llvm::RTLIB::SDIVREM_I64, llvm::RTLIB::SDIVREM_I8, llvm::MVT::SimpleTy, llvm::ISD::SREM, llvm::TargetLowering::ArgListEntry::Ty, llvm::ISD::UDIV, llvm::ISD::UDIVREM, llvm::RTLIB::UDIVREM_I128, llvm::RTLIB::UDIVREM_I16, llvm::RTLIB::UDIVREM_I32, llvm::RTLIB::UDIVREM_I64, llvm::RTLIB::UDIVREM_I8, llvm::ISD::UREM, llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
Referenced by useSinCos().
static bool useSinCos (SDNode * Node) static
useSinCos - Only issue sincos libcall if both sin and cos are needed.
Definition at line 2163 of file LegalizeDAG.cpp.
References llvm::ISD::ADD, Align, llvm::ISD::AND, llvm::APIntOps::And(), llvm::ISD::ANY_EXTEND, llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_FENCE, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_XOR, llvm::ISD::ATOMIC_STORE, llvm::ISD::ATOMIC_SWAP, llvm::ISD::BITCAST, llvm::EVT::bitsEq(), llvm::EVT::bitsGT(), llvm::EVT::bitsLT(), llvm::BitsToDouble(), llvm::ISD::BR_CC, llvm::ISD::BR_JT, llvm::ISD::BRCOND, llvm::ISD::BRIND, llvm::ISD::BSWAP, llvm::ISD::BUILD_PAIR, llvm::ISD::BUILD_VECTOR, llvm::CallingConv::C, canCombineSinCosLibcall(), CC, llvm::RTLIB::CEIL_F128, llvm::RTLIB::CEIL_F32, llvm::RTLIB::CEIL_F64, llvm::RTLIB::CEIL_F80, llvm::RTLIB::CEIL_PPCF128, llvm::ISD::CONCAT_VECTORS, llvm::ISD::ConstantFP, llvm::ISD::ConstantPool, llvm::APFloat::convertFromAPInt(), llvm::RTLIB::COS_F128, llvm::RTLIB::COS_F32, llvm::RTLIB::COS_F64, llvm::RTLIB::COS_F80, llvm::RTLIB::COS_PPCF128, llvm::SelectionDAG::CreateStackTemporary(), llvm::ISD::CTLZ, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::ISD::CTTZ, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::SmallVectorTemplateCommon< T >::data(), llvm::SelectionDAG::DeleteNode(), llvm::RTLIB::DIV_F128, llvm::RTLIB::DIV_F32, llvm::RTLIB::DIV_F64, llvm::RTLIB::DIV_F80, llvm::RTLIB::DIV_PPCF128, llvm::ISD::DYNAMIC_STACKALLOC, llvm::ISD::EH_LABEL, llvm::ISD::EH_RETURN, llvm::ISD::EH_SJLJ_LONGJMP, llvm::ISD::EH_SJLJ_SETJMP, llvm::SmallVectorBase::empty(), llvm::SelectionDAG::EVTToAPFloatSemantics(), llvm::RTLIB::EXP2_F128, llvm::RTLIB::EXP2_F32, llvm::RTLIB::EXP2_F64, llvm::RTLIB::EXP2_F80, llvm::RTLIB::EXP2_PPCF128, llvm::RTLIB::EXP_F128, llvm::RTLIB::EXP_F32, llvm::RTLIB::EXP_F64, llvm::RTLIB::EXP_F80, llvm::RTLIB::EXP_PPCF128, llvm::ISD::ExternalSymbol, llvm::ISD::EXTLOAD, llvm::ISD::EXTRACT_ELEMENT, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f128, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, llvm::ISD::FABS, llvm::ISD::FADD, llvm::CallingConv::Fast, llvm::ISD::FCEIL, llvm::ISD::FCOPYSIGN, llvm::ISD::FCOS, llvm::ISD::FDIV, llvm::ISD::FEXP, llvm::ISD::FEXP2, llvm::ISD::FFLOOR, llvm::ISD::FLOG, llvm::ISD::FLOG10, llvm::ISD::FLOG2, llvm::RTLIB::FLOOR_F128, llvm::RTLIB::FLOOR_F32, llvm::RTLIB::FLOOR_F64, llvm::RTLIB::FLOOR_F80, llvm::RTLIB::FLOOR_PPCF128, llvm::ISD::FLT_ROUNDS_, llvm::ISD::FMA, llvm::RTLIB::FMA_F128, llvm::RTLIB::FMA_F32, llvm::RTLIB::FMA_F64, llvm::RTLIB::FMA_F80, llvm::RTLIB::FMA_PPCF128, llvm::ISD::FMUL, llvm::ISD::FNEARBYINT, llvm::ISD::FNEG, llvm::ISD::FP16_TO_FP32, llvm::ISD::FP32_TO_FP16, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::ISD::FP_ROUND_INREG, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::RTLIB::FPEXT_F16_F32, llvm::ISD::FPOW, llvm::ISD::FPOWI, llvm::RTLIB::FPROUND_F32_F16, llvm::ISD::FRAME_TO_ARGS_OFFSET, llvm::ISD::FRAMEADDR, llvm::ISD::FREM, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::ISD::FSIN, llvm::ISD::FSINCOS, llvm::ISD::FSQRT, llvm::ISD::FSUB, llvm::ISD::FTRUNC, llvm::ConstantInt::get(), llvm::APInt::getAllOnesValue(), llvm::SelectionDAG::getAtomic(), llvm::TargetLoweringBase::getBooleanContents(), llvm::SelectionDAG::getCondCode(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), llvm::SDNode::getConstantOperandVal(), llvm::MachinePointerInfo::getConstantPool(), llvm::SelectionDAG::getConstantPool(), llvm::SelectionDAG::getContext(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::TargetLoweringBase::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::MachineJumpTableInfo::getEntrySize(), llvm::SelectionDAG::getExternalSymbol(), llvm::SelectionDAG::getExtLoad(), llvm::Type::getInt64Ty(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getIntPtrConstant(), llvm::MachinePointerInfo::getJumpTable(), llvm::MachineFunction::getJumpTableInfo(), llvm::TargetLoweringBase::getLibcallCallingConv(), llvm::TargetLoweringBase::getLibcallName(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::TargetLoweringBase::getMinStackArgumentAlignment(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNOT(), llvm::APInt::getNullValue(), llvm::SDNode::getNumValues(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::TargetLowering::getPICJumpTableRelocBase(), llvm::Type::getPointerTo(), llvm::TargetLoweringBase::getPointerTy(), llvm::TargetMachine::getRelocationModel(), llvm::EVT::getScalarType(), llvm::SelectionDAG::getSelect(), llvm::SelectionDAG::getSelectCC(), llvm::SelectionDAG::getSetCC(), llvm::ISD::getSetCCInverse(), llvm::ISD::getSetCCSwappedOperands(), llvm::TargetLoweringBase::getShiftAmountTy(), llvm::APInt::getSignBit(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::EVT::getSimpleVT(), llvm::MVT::getSizeInBits(), llvm::EVT::getSizeInBits(), llvm::APInt::getSplat(), llvm::TargetLoweringBase::getStackPointerRegisterToSaveRestore(), llvm::SelectionDAG::getStore(), llvm::EVT::getTypeForEVT(), llvm::TargetLoweringBase::getTypeToPromoteTo(), llvm::TargetLoweringBase::getTypeToTransformTo(), llvm::SelectionDAG::getUNDEF(), llvm::SelectionDAG::getVAArg(), llvm::SDValue::getValue(), llvm::HandleSDNode::getValue(), llvm::ConstantFPSDNode::getValueAPF(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::TargetLoweringBase::getVectorIdxTy(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), llvm::Type::getVoidTy(), llvm::SelectionDAG::getVTList(), llvm::SelectionDAG::getZeroExtendInReg(), llvm::ISD::GLOBAL_OFFSET_TABLE, llvm::ISD::GlobalAddress, llvm::ISD::GlobalTLSAddress, llvm::HexagonISD::Hi, i, llvm::MVT::i128, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INSERT_VECTOR_ELT, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::TargetLoweringBase::isCondCodeLegal(), isDivRemLibcallAvailable(), llvm::EVT::isFloatingPoint(), llvm::TargetLoweringBase::isFPImmLegal(), llvm::MVT::isInteger(), llvm::EVT::isInteger(), llvm::TargetLoweringBase::isLittleEndian(), llvm::TargetLoweringBase::isOperationLegalOrCustom(), llvm::TargetLowering::ArgListEntry::isSExt, llvm::ISD::isSignedIntSetCC(), llvm::TargetLoweringBase::isTypeLegal(), llvm::MVT::isVector(), llvm::EVT::isVector(), llvm::TargetLowering::ArgListEntry::isZExt, llvm::ISD::JumpTable, llvm::A64DB::LD, llvm_unreachable, llvm::HexagonISD::Lo, llvm::SPII::Load, llvm::RTLIB::LOG10_F128, llvm::RTLIB::LOG10_F32, llvm::RTLIB::LOG10_F64, llvm::RTLIB::LOG10_F80, llvm::RTLIB::LOG10_PPCF128, llvm::RTLIB::LOG2_F128, llvm::RTLIB::LOG2_F32, llvm::RTLIB::LOG2_F64, llvm::RTLIB::LOG2_F80, llvm::RTLIB::LOG2_PPCF128, llvm::RTLIB::LOG_F128, llvm::RTLIB::LOG_F32, llvm::RTLIB::LOG_F64, llvm::RTLIB::LOG_F80, llvm::RTLIB::LOG_PPCF128, llvm::TargetLowering::LowerCallTo(), llvm::ISD::MERGE_VALUES, llvm::ISD::MUL, llvm::RTLIB::MUL_I128, llvm::RTLIB::MUL_I16, llvm::RTLIB::MUL_I32, llvm::RTLIB::MUL_I64, llvm::RTLIB::MUL_I8, llvm::ISD::MULHS, llvm::ISD::MULHU, llvm::RTLIB::NEARBYINT_F128, llvm::RTLIB::NEARBYINT_F32, llvm::RTLIB::NEARBYINT_F64, llvm::RTLIB::NEARBYINT_F80, llvm::RTLIB::NEARBYINT_PPCF128, llvm::TargetLowering::ArgListEntry::Node, llvm::ISD::OR, llvm::APIntOps::Or(), llvm::MVT::Other, llvm::Reloc::PIC_, llvm::RTLIB::POW_F128, llvm::RTLIB::POW_F32, llvm::RTLIB::POW_F64, llvm::RTLIB::POW_F80, llvm::RTLIB::POW_PPCF128, llvm::RTLIB::POWI_F128, llvm::RTLIB::POWI_F32, llvm::RTLIB::POWI_F64, llvm::RTLIB::POWI_F80, llvm::RTLIB::POWI_PPCF128, llvm::MVT::ppcf128, llvm::ISD::PREFETCH, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::RTLIB::REM_F128, llvm::RTLIB::REM_F32, llvm::RTLIB::REM_F64, llvm::RTLIB::REM_F80, llvm::RTLIB::REM_PPCF128, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::AArch64ISD::Ret, llvm::ISD::RETURNADDR, llvm::RTLIB::RINT_F128, llvm::RTLIB::RINT_F32, llvm::RTLIB::RINT_F64, llvm::RTLIB::RINT_F80, llvm::RTLIB::RINT_PPCF128, llvm::APFloat::rmNearestTiesToEven, llvm::RTLIB::ROUND_F128, llvm::RTLIB::ROUND_F32, llvm::RTLIB::ROUND_F64, llvm::RTLIB::ROUND_F80, llvm::RTLIB::ROUND_PPCF128, llvm::ISD::SADDO, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SDIV, llvm::RTLIB::SDIV_I128, llvm::RTLIB::SDIV_I16, llvm::RTLIB::SDIV_I32, llvm::RTLIB::SDIV_I64, llvm::RTLIB::SDIV_I8, llvm::ISD::SDIVREM, llvm::ISD::SELECT, llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULT, llvm::ISD::SEXTLOAD, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::ISD::SIGN_EXTEND_INREG, llvm::MVT::SimpleTy, llvm::RTLIB::SIN_F128, llvm::RTLIB::SIN_F32, llvm::RTLIB::SIN_F64, llvm::RTLIB::SIN_F80, llvm::RTLIB::SIN_PPCF128, llvm::RTLIB::SINCOS_F128, llvm::RTLIB::SINCOS_F32, llvm::RTLIB::SINCOS_F64, llvm::RTLIB::SINCOS_F80, llvm::RTLIB::SINCOS_PPCF128, llvm::ISD::SINT_TO_FP, llvm::SmallVectorTemplateCommon< T >::size(), llvm::ISD::SMUL_LOHI, llvm::ISD::SMULO, llvm::RTLIB::SQRT_F128, llvm::RTLIB::SQRT_F32, llvm::RTLIB::SQRT_F64, llvm::RTLIB::SQRT_F80, llvm::RTLIB::SQRT_PPCF128, llvm::ISD::SRA, llvm::ISD::SREM, llvm::RTLIB::SREM_I128, llvm::RTLIB::SREM_I16, llvm::RTLIB::SREM_I32, llvm::RTLIB::SREM_I64, llvm::RTLIB::SREM_I8, llvm::ISD::SRL, llvm::ISD::SSUBO, llvm::ISD::STACKRESTORE, llvm::ISD::STACKSAVE, llvm::ISD::SUB, Sum, std::swap(), llvm::RTLIB::SYNC_FETCH_AND_ADD_1, llvm::RTLIB::SYNC_FETCH_AND_ADD_16, llvm::RTLIB::SYNC_FETCH_AND_ADD_2, llvm::RTLIB::SYNC_FETCH_AND_ADD_4, llvm::RTLIB::SYNC_FETCH_AND_ADD_8, llvm::RTLIB::SYNC_FETCH_AND_AND_1, llvm::RTLIB::SYNC_FETCH_AND_AND_16, llvm::RTLIB::SYNC_FETCH_AND_AND_2, llvm::RTLIB::SYNC_FETCH_AND_AND_4, llvm::RTLIB::SYNC_FETCH_AND_AND_8, llvm::RTLIB::SYNC_FETCH_AND_MAX_1, llvm::RTLIB::SYNC_FETCH_AND_MAX_16, llvm::RTLIB::SYNC_FETCH_AND_MAX_2, llvm::RTLIB::SYNC_FETCH_AND_MAX_4, llvm::RTLIB::SYNC_FETCH_AND_MAX_8, llvm::RTLIB::SYNC_FETCH_AND_MIN_1, llvm::RTLIB::SYNC_FETCH_AND_MIN_16, llvm::RTLIB::SYNC_FETCH_AND_MIN_2, llvm::RTLIB::SYNC_FETCH_AND_MIN_4, llvm::RTLIB::SYNC_FETCH_AND_MIN_8, llvm::RTLIB::SYNC_FETCH_AND_NAND_1, llvm::RTLIB::SYNC_FETCH_AND_NAND_16, llvm::RTLIB::SYNC_FETCH_AND_NAND_2, llvm::RTLIB::SYNC_FETCH_AND_NAND_4, llvm::RTLIB::SYNC_FETCH_AND_NAND_8, llvm::RTLIB::SYNC_FETCH_AND_OR_1, llvm::RTLIB::SYNC_FETCH_AND_OR_16, llvm::RTLIB::SYNC_FETCH_AND_OR_2, llvm::RTLIB::SYNC_FETCH_AND_OR_4, llvm::RTLIB::SYNC_FETCH_AND_OR_8, llvm::RTLIB::SYNC_FETCH_AND_SUB_1, llvm::RTLIB::SYNC_FETCH_AND_SUB_16, llvm::RTLIB::SYNC_FETCH_AND_SUB_2, llvm::RTLIB::SYNC_FETCH_AND_SUB_4, llvm::RTLIB::SYNC_FETCH_AND_SUB_8, llvm::RTLIB::SYNC_FETCH_AND_UMAX_1, llvm::RTLIB::SYNC_FETCH_AND_UMAX_16, llvm::RTLIB::SYNC_FETCH_AND_UMAX_2, llvm::RTLIB::SYNC_FETCH_AND_UMAX_4, llvm::RTLIB::SYNC_FETCH_AND_UMAX_8, llvm::RTLIB::SYNC_FETCH_AND_UMIN_1, llvm::RTLIB::SYNC_FETCH_AND_UMIN_16, llvm::RTLIB::SYNC_FETCH_AND_UMIN_2, llvm::RTLIB::SYNC_FETCH_AND_UMIN_4, llvm::RTLIB::SYNC_FETCH_AND_UMIN_8, llvm::RTLIB::SYNC_FETCH_AND_XOR_1, llvm::RTLIB::SYNC_FETCH_AND_XOR_16, llvm::RTLIB::SYNC_FETCH_AND_XOR_2, llvm::RTLIB::SYNC_FETCH_AND_XOR_4, llvm::RTLIB::SYNC_FETCH_AND_XOR_8, llvm::RTLIB::SYNC_LOCK_TEST_AND_SET_1, llvm::RTLIB::SYNC_LOCK_TEST_AND_SET_16, llvm::RTLIB::SYNC_LOCK_TEST_AND_SET_2, llvm::RTLIB::SYNC_LOCK_TEST_AND_SET_4, llvm::RTLIB::SYNC_LOCK_TEST_AND_SET_8, llvm::RTLIB::SYNC_VAL_COMPARE_AND_SWAP_1, llvm::RTLIB::SYNC_VAL_COMPARE_AND_SWAP_16, llvm::RTLIB::SYNC_VAL_COMPARE_AND_SWAP_2, llvm::RTLIB::SYNC_VAL_COMPARE_AND_SWAP_4, llvm::RTLIB::SYNC_VAL_COMPARE_AND_SWAP_8, llvm::ISD::TRAP, llvm::RTLIB::TRUNC_F128, llvm::RTLIB::TRUNC_F32, llvm::RTLIB::TRUNC_F64, llvm::RTLIB::TRUNC_F80, llvm::RTLIB::TRUNC_PPCF128, llvm::ISD::TRUNCATE, llvm::TargetLowering::ArgListEntry::Ty, llvm::ISD::UADDO, llvm::ISD::UDIV, llvm::RTLIB::UDIV_I128, llvm::RTLIB::UDIV_I16, llvm::RTLIB::UDIV_I32, llvm::RTLIB::UDIV_I64, llvm::RTLIB::UDIV_I8, llvm::ISD::UDIVREM, llvm::ISD::UINT_TO_FP, llvm::ISD::UMUL_LOHI, llvm::ISD::UMULO, llvm::ISD::UNDEF, llvm::TargetLoweringBase::UndefinedBooleanContent, llvm::RTLIB::UNKNOWN_LIBCALL, llvm::ISD::UREM, llvm::RTLIB::UREM_I128, llvm::RTLIB::UREM_I16, llvm::RTLIB::UREM_I32, llvm::RTLIB::UREM_I64, llvm::RTLIB::UREM_I8, llvm::SDNode::use_begin(), llvm::SDNode::use_end(), useDivRem(), llvm::ISD::USUBO, llvm::ISD::VAARG, llvm::ISD::VACOPY, llvm::ISD::VAEND, llvm::ISD::VECTOR_SHUFFLE, llvm::A64CC::VS, llvm::ISD::XOR, llvm::ISD::ZERO_EXTEND, llvm::TargetLoweringBase::ZeroOrNegativeOneBooleanContent, and llvm::TargetLoweringBase::ZeroOrOneBooleanContent.