LLVM: CMakeLists.txt File Reference
LLVM API Documentation
CMakeLists.txt File Reference
Functions
if (FFI_INCLUDE_PATH) include_directories($
endif () add_llvm_library(LLVMInterpreter Execution.cpp ExternalFunctions.cpp Interpreter.cpp) if(LLVM_ENABLE_FFI) target_link_libraries(LLVMInterpreter $
Function Documentation
endif ()
Definition at line 7 of file lib/ExecutionEngine/Interpreter/CMakeLists.txt.
Referenced by add_subdirectory(), llvm::InstrEmitter::EmitDbgValue(), and llvm::raw_fd_ostream::~raw_fd_ostream().
if (FFI_INCLUDE_PATH)
Definition at line 5 of file lib/ExecutionEngine/Interpreter/CMakeLists.txt.