LLVM: CMakeLists.txt File Reference
LLVM API Documentation
CMakeLists.txt File Reference
Functions
add_llvm_library (LLVMTarget Mangler.cpp Target.cpp TargetIntrinsicInfo.cpp TargetJITInfo.cpp TargetLibraryInfo.cpp TargetLoweringObjectFile.cpp TargetMachine.cpp TargetMachineC.cpp TargetSubtargetInfo.cpp) foreach(t $
message (STATUS"Targeting ${t}") add_subdirectory($
Function Documentation
add_llvm_library (LLVMTarget Mangler.cpp Target.cpp TargetIntrinsicInfo.cpp TargetJITInfo.cpp TargetLibraryInfo.cpp TargetLoweringObjectFile.cpp TargetMachine.cpp TargetMachineC.cpp TargetSubtargetInfo. cpp)
Definition at line 1 of file lib/Target/CMakeLists.txt.
message (STATUS"Targeting ${t}")
Definition at line 14 of file lib/Target/CMakeLists.txt.
References t.
Referenced by llvm::error_condition::category(), llvm::yaml::Input::classof(), llvm::yaml::Output::classof(), llvm::error_code::default_error_condition(), llvm::BitcodeReader::MaterializeModule(), and llvm::yaml::Input::nextDocument().