LLVM: LinkModules.cpp File Reference
LLVM API Documentation
LinkModules.cpp File Reference
#include "llvm/Linker.h"
#include "llvm-c/Linker.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/TypeFinder.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/Cloning.h"
#include <cctype>
Functions
static void forceRenaming (GlobalValue *GV, StringRef Name)
static void copyGVAttributes (GlobalValue *DestGV, const GlobalValue *SrcGV)
static bool isLessConstraining (GlobalValue::VisibilityTypes a, GlobalValue::VisibilityTypes b)
static void getArrayElements (Constant *C, SmallVectorImpl< Constant * > &Dest)
LLVMBool LLVMLinkModules (LLVMModuleRef Dest, LLVMModuleRef Src, LLVMLinkerMode Mode, char **OutMessages)
Function Documentation
static void copyGVAttributes (GlobalValue * DestGV, const GlobalValue * SrcGV) static
copyGVAttributes - copy additional attributes (those not needed to construct a GlobalValue) from the SrcGV to the DestGV.
Definition at line 491 of file LinkModules.cpp.
References llvm::GlobalValue::copyAttributesFrom(), forceRenaming(), llvm::GlobalValue::getAlignment(), llvm::Value::getName(), and llvm::GlobalValue::setAlignment().
Referenced by isLessConstraining().
static void forceRenaming (GlobalValue * GV, StringRef Name) static
forceRenaming - The LLVM SymbolTable class autorenames globals that conflict in the symbol table. This is good for all clients except for us. Go through the trouble to force this back.
Definition at line 471 of file LinkModules.cpp.
References llvm::Value::getName(), llvm::Module::getNamedValue(), llvm::GlobalValue::getParent(), llvm::GlobalValue::hasLocalLinkage(), M, llvm::Value::setName(), and llvm::Value::takeName().
Referenced by copyGVAttributes().
static void getArrayElements (Constant * C, SmallVectorImpl< Constant * > & Dest) static
Definition at line 928 of file LinkModules.cpp.
References llvm::NamedMDNode::addOperand(), llvm::Module::alias_begin(), llvm::Module::alias_end(), llvm::Module::Append, llvm::Module::AppendUnique, llvm::Function::arg_begin(), llvm::Function::arg_end(), BB, llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::begin(), llvm::Function::begin(), llvm::Module::begin(), llvm::CloneFunctionInto(), llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::X86II::DA, llvm::GlobalValue::Dematerialize(), llvm::Linker::DestroySource, llvm::X86II::DF, llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::end(), llvm::Function::end(), llvm::Module::end(), llvm::ValueMap< KeyT, ValueT, Config >::erase(), llvm::Module::Error, llvm::errs(), llvm::MDNode::get(), llvm::ConstantArray::get(), llvm::Constant::getAggregateElement(), llvm::Function::getBasicBlockList(), llvm::Module::getContext(), llvm::Module::getDataLayout(), llvm::Module::getModuleFlagsMetadata(), llvm::Module::getModuleIdentifier(), llvm::Module::getModuleInlineAsm(), llvm::MDNode::getNumOperands(), llvm::NamedMDNode::getNumOperands(), llvm::MDNode::getOperand(), llvm::NamedMDNode::getOperand(), llvm::Module::getOrInsertModuleFlagsMetadata(), llvm::Module::getOrInsertNamedMetadata(), llvm::Function::getPrefixData(), llvm::MDString::getString(), llvm::Module::getTargetTriple(), llvm::Value::getType(), llvm::ConstantInt::getZExtValue(), llvm::Module::global_begin(), llvm::Module::global_end(), llvm::Function::hasPrefixData(), i, I, llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::insert(), llvm::GlobalValue::isDeclaration(), llvm::GlobalValue::isMaterializable(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::lookup(), llvm::MapValue(), llvm::GlobalValue::Materialize(), llvm::Module::named_metadata_begin(), llvm::Module::named_metadata_end(), llvm::Module::Override, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::RemapInstruction(), llvm::Module::Require, llvm::RF_IgnoreMissingEntries, llvm::RF_None, llvm::GlobalAlias::setAliasee(), llvm::Module::setDataLayout(), llvm::GlobalVariable::setInitializer(), llvm::Module::setModuleInlineAsm(), llvm::Function::setPrefixData(), llvm::Module::setTargetTriple(), llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::size(), llvm::iplist< NodeTy, Traits >::splice(), and llvm::Module::Warning.
static bool isLessConstraining (GlobalValue::VisibilityTypes a, GlobalValue::VisibilityTypes b) static
Definition at line 500 of file LinkModules.cpp.
References llvm::StringRef::back(), llvm::TypeFinder::begin(), llvm::Module::begin(), copyGVAttributes(), llvm::Function::Create(), llvm::X86II::DF, llvm::dyn_cast(), llvm::TypeFinder::end(), llvm::Module::end(), llvm::GlobalVariable::eraseFromParent(), llvm::GlobalValue::eraseFromParent(), llvm::GlobalValue::ExternalLinkage, llvm::ArrayType::get(), llvm::PointerType::getAddressSpace(), llvm::GlobalValue::getAlignment(), llvm::ConstantExpr::getBitCast(), llvm::SequentialType::getElementType(), llvm::Function::getFunctionType(), llvm::GlobalVariable::getInitializer(), llvm::GlobalValue::getLinkage(), llvm::Value::getName(), llvm::StructType::getName(), llvm::ArrayType::getNumElements(), llvm::GlobalValue::getParent(), llvm::GlobalValue::getSection(), llvm::GlobalVariable::getThreadLocalMode(), llvm::GlobalValue::getType(), llvm::Module::getTypeByName(), llvm::GlobalValue::getVisibility(), llvm::Module::global_begin(), llvm::Module::global_end(), llvm::GlobalValue::hasAppendingLinkage(), llvm::GlobalValue::hasAvailableExternallyLinkage(), llvm::GlobalValue::hasCommonLinkage(), llvm::GlobalValue::hasDLLExportLinkage(), llvm::GlobalValue::hasDLLImportLinkage(), llvm::GlobalValue::hasExternalLinkage(), llvm::GlobalValue::hasExternalWeakLinkage(), llvm::GlobalValue::hasLinkOnceLinkage(), llvm::GlobalValue::hasLocalLinkage(), llvm::StructType::hasName(), llvm::GlobalValue::hasUnnamedAddr(), llvm::GlobalValue::hasWeakLinkage(), llvm::GlobalValue::HiddenVisibility, i, I, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::GlobalValue::InternalLinkage, llvm::GlobalVariable::isConstant(), llvm::GlobalValue::isDeclaration(), llvm::LibFunc::isdigit, llvm::GlobalValue::isMaterializable(), llvm::GlobalValue::isWeakForLinker(), llvm::A64CC::LT, llvm::StringRef::npos, llvm::A64CC::NV, llvm::GlobalValue::ProtectedVisibility, llvm::Value::replaceAllUsesWith(), llvm::StringRef::rfind(), llvm::TypeFinder::run(), llvm::GlobalValue::setLinkage(), llvm::GlobalValue::setUnnamedAddr(), llvm::GlobalValue::setVisibility(), llvm::TypeFinder::size(), llvm::A64DB::ST, and llvm::StringRef::substr().
LLVMBool LLVMLinkModules (LLVMModuleRef Dest, LLVMModuleRef Src, LLVMLinkerMode Mode, char ** OutMessages)
Definition at line 1389 of file LinkModules.cpp.
References llvm::Linker::LinkModules(), llvm::LibFunc::strdup, and llvm::unwrap().