LLVM: LiveRegUnits.cpp File Reference
LLVM API Documentation
LiveRegUnits.cpp File Reference
#include "llvm/CodeGen/LiveRegUnits.h"
#include "llvm/CodeGen/MachineInstrBundle.h"
Functions
static bool operClobbersUnit (const MachineOperand *MO, unsigned Unit, const MCRegisterInfo *MCRI)
Function Documentation
static bool operClobbersUnit (const MachineOperand * MO, unsigned Unit, const MCRegisterInfo * MCRI) static
Return true if the given MachineOperand clobbers the given register unit. A register unit is only clobbered if all its super-registers are clobbered.
Definition at line 22 of file LiveRegUnits.cpp.
References llvm::MachineOperand::clobbersPhysReg(), llvm::MCRegisterInfo::DiffListIterator::isValid(), and llvm::MCRegUnitRootIterator::isValid().
Referenced by llvm::LiveRegUnits::removeRegsInMask().