LLVM: LLParser.cpp File Reference
LLVM API Documentation
LLParser.cpp File Reference
#include "LLParser.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/AutoUpgrade.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/ValueSymbolTable.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
Functions
static std::string getTypeString (Type *T)
* if (!EatIfPresent(lltok::kw_thread_local)) return false
if (Lex.getKind()==lltok::lparen)
* if (!EatIfPresent(lltok::kw_addrspace)) return false
F (f)
FunctionNumber (functionNumber)
Variables
TLM = GlobalVariable::GeneralDynamicTLSModel
return false
Function Documentation
F (f)
Referenced by accumulateAndSortLibcalls(), llvm::SourceMgr::AddNewSourceBuffer(), AddressIsTaken(), llvm::MachineOperand::addTargetFlag(), llvm::X86FrameLowering::adjustForHiPEPrologue(), llvm::CodeMetrics::analyzeBasicBlock(), analyzeGlobalAux(), llvm::SITargetLowering::analyzeImmediate(), llvm::MachineModuleInfo::AnalyzeModule(), appendToGlobalArray(), llvm::ARMJITInfo::ARMJITInfo(), assertLocalFunction(), llvm::BitsToFloat(), llvm::APInt::bitsToFloat(), llvm::BranchProbabilityInfo::BranchProbabilityInfo(), llvm::Interpreter::callFunction(), llvm::CallGraph::CallGraph(), llvm::DwarfException::CallToNoUnwindFunction(), CanConstantFold(), canFoldIVIncExpr(), llvm::objcarc::CanInterruptRV(), llvm::CannotBeNegativeZero(), CanTRE(), checkAndUpdateEFLAGSKill(), checkInterfaceFunction(), llvm::Region::clearNodeCache(), llvm::CloneBasicBlock(), llvm::ClonedCodeInfo::ClonedCodeInfo(), CloneLoop(), CloneLoopBlocks(), llvm::CloneModule(), CollectBSwapParts(), CollectSubexprs(), CommitValueTo(), llvm::DominatorTree::compare(), compareBySuffix(), llvm::MCAssembler::computeFragmentSize(), llvm::ComputeLinearIndex(), llvm::ConstantFoldInstOperands(), ConvertAtomicSynchScope(), countOperands(), llvm::JIT::create(), llvm::createArgumentPromotionPass(), llvm::createARMJITCodeEmitterPass(), llvm::createBasicAliasAnalysisPass(), llvm::createCodeGenPreparePass(), llvm::createConstantPropagationPass(), llvm::createCorrelatedValuePropagationPass(), llvm::createCostModelAnalysisPass(), llvm::createEarlyCSEPass(), createFree(), llvm::CallInst::CreateFree(), llvm::DIBuilder::createGlobalVariable(), llvm::createHexagonHardwareLoops(), llvm::JIT::createJIT(), llvm::createJumpThreadingPass(), createMalloc(), llvm::createMemDepPrinter(), llvm::createMergeFunctionsPass(), llvm::createNVPTXISelDag(), llvm::createObjCARCContractPass(), llvm::createObjCARCOptPass(), llvm::createPPCCTRLoopsVerify(), llvm::legacy::FunctionPassManagerImpl::createPrinterPass(), createPrivateNonConstGlobalForString(), llvm::createPruneEHPass(), llvm::createScalarEvolutionAliasAnalysisPass(), llvm::createSingleLoopExtractorPass(), llvm::createSinkingPass(), llvm::DIBuilder::createStaticVariable(), llvm::createSystemZLongBranchPass(), llvm::createSystemZShortenInstPass(), cse(), DeleteTriviallyDeadInstructions(), llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), DescKind(), llvm::AsmPrinter::doFinalization(), llvm::AliasSetTracker::dump(), llvm::dumpBlock(), llvm::dumpParent(), llvm::PPCTargetLowering::EmitAtomicBinary(), llvm::InstrEmitter::EmitDbgValue(), llvm::EmitFPutC(), llvm::EmitFPutS(), llvm::AsmPrinter::EmitFunctionBody(), llvm::AsmPrinter::EmitFunctionHeader(), llvm::ARMJITInfo::emitFunctionStub(), llvm::EmitFWrite(), llvm::EmitGEPOffset(), emitGlobalConstantDataSequential(), emitGPDisp(), llvm::MCELFStreamer::EmitIdent(), llvm::SparcTargetLowering::EmitInstrWithCustomInserter(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), llvm::MSP430TargetLowering::EmitInstrWithCustomInserter(), llvm::ARMTargetLowering::EmitInstrWithCustomInserter(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::X86TargetLowering::EmitInstrWithCustomInserter(), llvm::AsmPrinter::EmitJumpTableInfo(), llvm::MCObjectStreamer::EmitLabel(), llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc(), llvm::EmitMemChr(), llvm::EmitMemCmp(), llvm::EmitMemCpyChk(), EmitMonitor(), llvm::PPCTargetLowering::EmitPartwordAtomicBinary(), llvm::EmitPutChar(), llvm::EmitPutS(), llvm::MSP430TargetLowering::EmitShiftInstr(), llvm::ARMAsmPrinter::EmitStartOfAsmFile(), llvm::EmitStrChr(), llvm::EmitStrCpy(), llvm::EmitStrLen(), llvm::EmitStrNCmp(), llvm::EmitStrNCpy(), llvm::EmitStrNLen(), llvm::EmitUnaryFloatFnCall(), llvm::GCStrategy::end(), llvm::GCModuleInfo::end(), llvm::DwarfDebug::endFunction(), enqueueUsersInWorklist(), ExpandPowI(), Find(), findDeadCallerSavedReg(), llvm::ExecutionEngine::FindFunctionNamed(), llvm::MCJIT::FindFunctionNamed(), llvm::AnalysisResolver::findImplPass(), FindLIVLoopCondition(), llvm::MCJIT::findModuleForSymbol(), FirstNonDbg(), FitsInFPType(), llvm::FloatToBits(), llvm::APInt::floatToBits(), llvm::MCELFStreamer::Flush(), llvm::InstCombiner::foldFMulConst(), llvm::FPPassManager::FPPassManager(), ftostr(), FunctionNumber(), llvm::FunctionPass::FunctionPass(), generateUnsignedDivisionCode(), llvm::BlockAddress::get(), llvm::HexagonInstrInfo::getAddrMode(), llvm::Pass::getAnalysis(), llvm::NVPTXSplitBBatBar::getAnalysisUsage(), llvm::NVPTXLowerAggrCopies::getAnalysisUsage(), llvm::Argument::getArgNo(), llvm::MCAsmLayout::getAssembler(), llvm::ValueEnumerator::getAttributeGroups(), llvm::HexagonMCInst::getBitCount(), getBlockNum(), llvm::MSP430RegisterInfo::getCalleeSavedRegs(), llvm::ARMBaseRegisterInfo::getCalleeSavedRegs(), llvm::HexagonMCInst::getCExtOpNum(), llvm::HexagonInstrInfo::getCExtOpNum(), getComparePred(), GetConstantPoolSizeInBytes(), llvm::ExecutionEngine::getConstantValue(), llvm::legacy::FunctionPassManagerImpl::getContainedManager(), llvm::LLParser::getContext(), llvm::ScalarEvolution::getCouldNotCompute(), llvm::ExecutionEngine::getDataLayout(), llvm::GCOVOptions::getDefault(), llvm::DIDescriptor::getFieldAs(), llvm::Interpreter::getFirstVarArg(), llvm::ARM_AM::getFPImmFloat(), llvm::GCFunctionInfo::getFunction(), llvm::MDNode::getFunction(), llvm::CallGraphNode::getFunction(), llvm::GCModuleInfo::getFunctionInfo(), getFunctionName(), llvm::DenseMapInfo< ComparableFunction >::getHashValue(), llvm::getInst(), llvm::objcarc::GetInstructionClass(), getIntrinsicIDForCall(), llvm::SparcJITInfo::getLazyResolverFunction(), llvm::MipsJITInfo::getLazyResolverFunction(), llvm::X86JITInfo::getLazyResolverFunction(), llvm::ARMJITInfo::getLazyResolverFunction(), llvm::HexagonInstrInfo::getMaxValue(), getMemCmpLoad(), llvm::HexagonInstrInfo::getMinValue(), llvm::AliasAnalysis::getModRefBehavior(), llvm::LibCallAliasAnalysis::getModRefInfo(), llvm::TargetLibraryInfo::getName(), llvm::Mangler::getNameWithPrefix(), llvm::HexagonMCInst::getNewValue(), llvm::MipsTargetLowering::getOpndList(), llvm::ARMTargetLowering::getOptimalMemOpType(), llvm::X86TargetLowering::getOptimalMemOpType(), llvm::MCObjectStreamer::getOrCreateDataFragment(), llvm::LiveStacks::getOrCreateInterval(), llvm::CallGraph::getOrInsertFunction(), llvm::Module::getOrInsertFunction(), llvm::getParentFunction(), llvm::MachineFunctionAnalysis::getPassName(), llvm::ARMAsmPrinter::getPassName(), getPLTReloc(), llvm::X86RegisterInfo::getPointerRegClass(), llvm::ExecutionEngine::getPointerToGlobal(), llvm::TargetTransformInfo::getReductionCost(), llvm::Pass::getResolver(), llvm::MachineDominatorTree::getRootNode(), llvm::X86AsmPrinter::getSubtarget(), llvm::DenseMapInfo< CallValue >::getTombstoneKey(), llvm::ImmutableMap< KeyT, ValT, ValInfo >::Factory::getTreeFactory(), llvm::ImmutableSet< ValT, ValInfo >::Factory::getTreeFactory(), getTruncatedArgReg(), llvm::HexagonMCInst::getType(), llvm::UnifyFunctionExitNodes::getUnreachableBlock(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::BasicBlock::getValueSymbolTable(), getWin64EHTableSection(), HasNestArgument(), llvm::HexagonMCInst::hasNewValue(), hasOutsideLoopUser(), llvm::ARM_PROC::IFlagsToString(), initialize(), INITIALIZE_AG_PASS(), INITIALIZE_PASS(), INITIALIZE_PASS_BEGIN(), llvm::yaml::ScalarTraits< MCModuleYAML::OpcodeEnum >::input(), llvm::InstCombiner::InstCombiner(), llvm::IntervalPartition::IntervalPartition(), llvm::AnalysisManager::invalidate(), llvm::AnalysisManager::invalidateAll(), isAtomic(), isBlockValidForExtraction(), isCompareZero(), llvm::HexagonMCInst::isConstExtended(), llvm::HexagonInstrInfo::isConstExtended(), llvm::GlobalValue::isDeclaration(), llvm::DenseMapInfo< Expression >::isEqual(), llvm::HexagonInstrInfo::isExtendable(), llvm::HexagonInstrInfo::isExtended(), llvm::TargetLowering::isInTailCallPosition(), isInterestingPointer(), llvm::MachineLoopInfo::isLoopHeader(), llvm::LoopInfo::isLoopHeader(), llvm::JITMemoryManager::isManagingGOT(), llvm::HexagonMCInst::isNewValue(), llvm::HexagonInstrInfo::isNewValue(), llvm::HexagonInstrInfo::isNewValueStore(), isNonGhostDeclaration(), isOnlyReachableViaThisEdge(), isOnlyUsedInEntryBlock(), llvm::HexagonInstrInfo::isOperandExtended(), IsPointerOffset(), llvm::HexagonInstrInfo::isPredicated(), llvm::HexagonInstrInfo::isPredicatedNew(), llvm::HexagonInstrInfo::isPredicatedTrue(), llvm::DISubprogram::isPrototyped(), llvm::HexagonMCInst::isSolo(), isStructPathTBAA(), isTrivialLoopExitBlock(), isUnmovableInstruction(), isXor1OfSetCC(), iterativelyFlattenCFG(), iterativelySimplifyCFG(), llvm::MCAsmLayout::layoutFragment(), llvm::FastISel::leaveLocalValueArea(), llvm::LibCallInfo::LibCallInfo(), llvm::linkShadowStackGC(), LLVMFindFunction(), LLVMGetGC(), LLVMGetIntrinsicID(), LLVMInitializeCppBackendTarget(), LLVMSetGC(), LLVMViewFunctionCFG(), LLVMViewFunctionCFGOnly(), lookupFunction(), llvm::NVPTXTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerFormalArguments(), LowerInterruptReturn(), llvm::NVPTXTargetLowering::LowerReturn(), lowerVECTOR_SHUFFLE_VSHF(), llvm::PatternMatch::m_Br(), llvm::MachineFunctionPass::MachineFunctionPass(), llvm::map_iterator(), llvm::MapValue(), MarkBlocksLiveIn(), MarkIndicesSafe(), llvm::BitcodeReader::materializeForwardReferencedFunctions(), llvm::BitcodeReader::MaterializeModule(), llvm::HexagonInstrInfo::mayBeNewStore(), llvm::MCAsmLayout::MCAsmLayout(), llvm::MipsJITInfo::MipsJITInfo(), llvm::PPCRegisterInfo::needsStackRealignment(), llvm::X86RegisterInfo::needsStackRealignment(), llvm::ARMBaseRegisterInfo::needsStackRealignment(), notDifferentParent(), llvm::objcarc::ObjCARCAliasAnalysis::ObjCARCAliasAnalysis(), llvm::operator<<(), originalTypeIsF128(), llvm::CallInst::paramHasAttr(), llvm::InvokeInst::paramHasAttr(), llvm::ParseAssemblyString(), llvm::BitcodeReader::ParseTriple(), PerformSTORECombine(), PlaceSplitBlockCarefully(), llvm::PMDataManager::PMDataManager(), llvm::PostDominatorTree::PostDominatorTree(), llvm::PPCJITInfo::PPCJITInfo(), llvm::Value::print(), llvm::Trace::print(), llvm::PassManagerPrettyStackEntry::print(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::print(), llvm::DependenceAnalysis::print(), PrintOps(), ProcessUAddIdiom(), ProcessUGT_ADDCST_ADD(), llvm::MDNode::Profile(), promoteSingleBlockAlloca(), llvm::GCOVFunction::read(), llvm::DominatorTreeBase< llvm::MachineBasicBlock >::recalculate(), RecognizePersonality(), llvm::Interpreter::Register(), llvm::CallInst::removeAttribute(), llvm::Inliner::removeDeadFunctions(), llvm::CallGraph::removeFunctionFromModule(), RemoveNestAttribute(), llvm::ARMTargetLowering::ReplaceNodeResults(), llvm::TargetMachine::resetTargetOptions(), llvm::LLParser::Run(), llvm::JIT::runJITOnFunction(), llvm::NVPTXLowerAggrCopies::runOnFunction(), llvm::UnifyFunctionExitNodes::runOnFunction(), llvm::BranchProbabilityInfo::runOnFunction(), llvm::DependenceAnalysis::runOnFunction(), llvm::PEI::runOnMachineFunction(), llvm::Mips16HardFloat::runOnModule(), llvm::MipsOs16::runOnModule(), llvm::FindUsedTypes::runOnModule(), llvm::Inliner::runOnSCC(), llvm::SelectionDAGISel::RunSDNodeXForm(), llvm::MCJIT::runStaticConstructorsDestructors(), llvm::ExecutionEngine::runStaticConstructorsDestructors(), llvm::FastISel::SelectInstruction(), llvm::TargetLibraryInfo::setAvailableWithName(), llvm::BitcodeReader::setBufferOwned(), llvm::MachineModuleInfo::setCompactUnwindEncoding(), llvm::Value::setName(), llvm::MachineOperand::setTargetFlags(), SimplifyCall(), AllocaSlices::SliceBuilder::SliceBuilder(), llvm::SparcJITInfo::SparcJITInfo(), StripSymbolNames(), llvm::TableGenMain(), llvm::UnrollRuntimeLoopProlog(), UpdateCallGraphAfterInlining(), llvm::UpgradeIntrinsicCall(), UpgradeIntrinsicFunction1(), useFuncSeen(), llvm::ValueEnumerator::ValueEnumerator(), llvm::DominatorTree::verifyAnalysis(), llvm::InstCombiner::visitAllocSite(), llvm::Interpreter::visitCallSite(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitFDiv(), llvm::InstVisitor< ObjectSizeOffsetVisitor, SizeOffsetType >::visitInstruction(), WriteConstants(), writeFragment(), writeFragmentContents(), WriteFunctionLocalMetadata(), WriteModule(), WriteModuleInfo(), llvm::JITCodeEmitter::~JITCodeEmitter(), llvm::JITMemoryManager::~JITMemoryManager(), llvm::MachineCodeEmitter::~MachineCodeEmitter(), llvm::MachineFunctionAnalysis::~MachineFunctionAnalysis(), llvm::MCELFObjectTargetWriter::~MCELFObjectTargetWriter(), llvm::MMIAddrLabelMap::~MMIAddrLabelMap(), and llvm::SparseSolver::~SparseSolver().
FunctionNumber (functionNumber)
Definition at line 1966 of file LLParser.cpp.
References llvm::Acquire, llvm::AcquireRelease, llvm::AtomicRMWInst::Add, llvm::SwitchInst::addCase(), llvm::LandingPadInst::addClause(), llvm::IndirectBrInst::addDestination(), llvm::PHINode::addIncoming(), llvm::Attribute::Alignment, llvm::AtomicRMWInst::And, llvm::FastMathFlags::any(), llvm::lltok::APFloat, llvm::ValID::APFloatVal, llvm::GlobalValue::AppendingLinkage, llvm::lltok::APSInt, llvm::ValID::APSIntVal, llvm::SelectInst::areInvalidOperands(), llvm::Function::arg_begin(), llvm::GlobalValue::AvailableExternallyLinkage, B, BB, llvm::SmallVectorTemplateCommon< T >::begin(), llvm::Attribute::Builtin, llvm::CastInst::castIsValid(), llvm::LandingPadInst::Catch, CC, llvm::lltok::comma, llvm::GlobalValue::CommonLinkage, llvm::ISD::Constant, llvm::ValID::ConstantStructElts, llvm::ValID::ConstantVal, llvm::AttrBuilder::contains(), llvm::APFloat::convert(), llvm::BasicBlock::Create(), llvm::Function::Create(), llvm::BinaryOperator::Create(), llvm::CastInst::Create(), llvm::GetElementPtrInst::Create(), llvm::CallInst::Create(), llvm::SelectInst::Create(), llvm::ExtractElementInst::Create(), llvm::InsertElementInst::Create(), llvm::ExtractValueInst::Create(), llvm::InsertValueInst::Create(), llvm::PHINode::Create(), llvm::LandingPadInst::Create(), llvm::ReturnInst::Create(), llvm::BranchInst::Create(), llvm::SwitchInst::Create(), llvm::IndirectBrInst::Create(), llvm::InvokeInst::Create(), llvm::ResumeInst::Create(), llvm::CrossThread, llvm::SmallVectorTemplateCommon< T >::data(), llvm::GlobalValue::DLLExportLinkage, llvm::GlobalValue::DLLImportLinkage, llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::Module::end(), llvm::lltok::Eof, llvm::lltok::equal, llvm::lltok::exclaim, llvm::GlobalValue::ExternalLinkage, llvm::GlobalValue::ExternalWeakLinkage, llvm::APSInt::extOrTrunc(), ExtractElement(), F(), llvm::CmpInst::FCMP_FALSE, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_TRUE, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, llvm::LandingPadInst::Filter, llvm::InlineAsm::get(), llvm::ConstantInt::get(), llvm::FunctionType::get(), llvm::MDNode::get(), llvm::ConstantFP::get(), llvm::ArrayType::get(), llvm::ConstantArray::get(), llvm::ConstantStruct::get(), llvm::ConstantVector::get(), llvm::ConstantPointerNull::get(), llvm::ConstantExpr::get(), llvm::UndefValue::get(), llvm::AttrBuilder::getAlignment(), llvm::LLLexer::getAPFloatVal(), llvm::LLLexer::getAPSIntVal(), llvm::ConstantExpr::getCast(), llvm::Type::getContext(), llvm::SequentialType::getElementType(), llvm::ConstantExpr::getExtractElement(), llvm::ConstantExpr::getExtractValue(), llvm::ConstantInt::getFalse(), llvm::ConstantExpr::getFCmp(), llvm::Module::getFunction(), llvm::Module::getFunctionList(), llvm::ConstantExpr::getGetElementPtr(), llvm::ConstantExpr::getICmp(), llvm::GetElementPtrInst::getIndexedType(), llvm::ExtractValueInst::getIndexedType(), llvm::ConstantExpr::getInsertElement(), llvm::ConstantExpr::getInsertValue(), llvm::BasicBlock::getInstList(), llvm::Type::getInt1Ty(), llvm::Type::getInt8Ty(), llvm::LLLexer::getKind(), llvm::Type::getLabelTy(), llvm::LLLexer::getLoc(), llvm::Value::getName(), llvm::Module::getNamedValue(), llvm::Constant::getNullValue(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarType(), llvm::ConstantExpr::getSelect(), llvm::APFloat::getSemantics(), llvm::ConstantExpr::getShuffleVector(), llvm::ConstantDataArray::getString(), llvm::LLLexer::getStrVal(), llvm::ConstantInt::getTrue(), llvm::Intrinsic::getType(), llvm::GlobalValue::getType(), llvm::Value::getType(), getTypeString(), llvm::LLLexer::getUIntVal(), llvm::PointerType::getUnqual(), llvm::lltok::GlobalID, llvm::lltok::GlobalVar, llvm::lltok::greater, llvm::AttrBuilder::hasAlignmentAttr(), llvm::AttributeSet::hasAttribute(), llvm::AttrBuilder::hasAttributes(), llvm::Value::hasName(), i, I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::APFloat::IEEEdouble, llvm::APFloat::IEEEhalf, llvm::APFloat::IEEEsingle, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::GlobalValue::InternalLinkage, llvm::Type::isAggregateType(), llvm::Type::isArrayTy(), isAtomic(), llvm::PossiblyExactOperator::IsExact, llvm::Type::isFirstClassType(), llvm::Type::isFloatingPointTy(), llvm::Type::isFloatTy(), llvm::Type::isFPOrFPVectorTy(), llvm::Type::isFunctionTy(), llvm::Type::isHalfTy(), llvm::Type::isIntegerTy(), llvm::Type::isIntOrIntVectorTy(), llvm::Type::isLabelTy(), llvm::Type::isMetadataTy(), llvm::Type::isPointerTy(), llvm::Type::isSized(), llvm::ExtractElementInst::isValidOperands(), llvm::InsertElementInst::isValidOperands(), llvm::ShuffleVectorInst::isValidOperands(), llvm::FunctionType::isValidReturnType(), llvm::ConstantFP::isValueValidForType(), llvm::FunctionType::isVarArg(), llvm::Type::isVectorTy(), llvm::Type::isVoidTy(), llvm::ValID::Kind, llvm::lltok::kw_add, llvm::lltok::kw_addrspacecast, llvm::lltok::kw_align, llvm::lltok::kw_alignstack, llvm::lltok::kw_alloca, llvm::lltok::kw_and, llvm::lltok::kw_ashr, llvm::lltok::kw_asm, llvm::lltok::kw_atomic, llvm::lltok::kw_atomicrmw, llvm::lltok::kw_bitcast, llvm::lltok::kw_blockaddress, llvm::lltok::kw_br, llvm::lltok::kw_c, llvm::lltok::kw_call, llvm::lltok::kw_catch, llvm::lltok::kw_cleanup, llvm::lltok::kw_cmpxchg, llvm::lltok::kw_eq, llvm::lltok::kw_exact, llvm::lltok::kw_extractelement, llvm::lltok::kw_extractvalue, llvm::lltok::kw_fadd, llvm::lltok::kw_false, llvm::lltok::kw_fcmp, llvm::lltok::kw_fdiv, llvm::lltok::kw_fence, llvm::lltok::kw_filter, llvm::lltok::kw_fmul, llvm::lltok::kw_fpext, llvm::lltok::kw_fptosi, llvm::lltok::kw_fptoui, llvm::lltok::kw_fptrunc, llvm::lltok::kw_frem, llvm::lltok::kw_fsub, llvm::lltok::kw_gc, llvm::lltok::kw_getelementptr, llvm::lltok::kw_icmp, llvm::lltok::kw_inbounds, llvm::lltok::kw_indirectbr, llvm::lltok::kw_insertelement, llvm::lltok::kw_insertvalue, llvm::lltok::kw_inteldialect, llvm::lltok::kw_inttoptr, llvm::lltok::kw_invoke, llvm::lltok::kw_landingpad, llvm::lltok::kw_load, llvm::lltok::kw_lshr, llvm::lltok::kw_max, llvm::lltok::kw_min, llvm::lltok::kw_mul, llvm::lltok::kw_nand, llvm::lltok::kw_ne, llvm::lltok::kw_nsw, llvm::lltok::kw_null, llvm::lltok::kw_nuw, llvm::lltok::kw_oeq, llvm::lltok::kw_oge, llvm::lltok::kw_ogt, llvm::lltok::kw_ole, llvm::lltok::kw_olt, llvm::lltok::kw_one, llvm::lltok::kw_or, llvm::lltok::kw_ord, llvm::lltok::kw_personality, llvm::lltok::kw_phi, llvm::lltok::kw_prefix, llvm::lltok::kw_ptrtoint, llvm::lltok::kw_resume, llvm::lltok::kw_ret, llvm::lltok::kw_sdiv, llvm::lltok::kw_section, llvm::lltok::kw_select, llvm::lltok::kw_sext, llvm::lltok::kw_sge, llvm::lltok::kw_sgt, llvm::lltok::kw_shl, llvm::lltok::kw_shufflevector, llvm::lltok::kw_sideeffect, llvm::lltok::kw_sitofp, llvm::lltok::kw_sle, llvm::lltok::kw_slt, llvm::lltok::kw_srem, llvm::lltok::kw_store, llvm::lltok::kw_sub, llvm::lltok::kw_switch, llvm::lltok::kw_tail, llvm::lltok::kw_to, llvm::lltok::kw_true, llvm::lltok::kw_trunc, llvm::lltok::kw_udiv, llvm::lltok::kw_ueq, llvm::lltok::kw_uge, llvm::lltok::kw_ugt, llvm::lltok::kw_uitofp, llvm::lltok::kw_ule, llvm::lltok::kw_ult, llvm::lltok::kw_umax, llvm::lltok::kw_umin, llvm::lltok::kw_undef, llvm::lltok::kw_une, llvm::lltok::kw_unnamed_addr, llvm::lltok::kw_uno, llvm::lltok::kw_unreachable, llvm::lltok::kw_unwind, llvm::lltok::kw_urem, llvm::lltok::kw_va_arg, llvm::lltok::kw_volatile, llvm::lltok::kw_xchg, llvm::lltok::kw_xor, llvm::lltok::kw_zeroinitializer, llvm::lltok::kw_zext, llvm::lltok::LabelStr, llvm::lltok::lbrace, llvm::lltok::less, llvm::LLLexer::Lex(), llvm::GlobalValue::LinkerPrivateLinkage, llvm::GlobalValue::LinkerPrivateWeakLinkage, llvm::GlobalValue::LinkOnceAnyLinkage, llvm::GlobalValue::LinkOnceODRLinkage, llvm_unreachable, llvm::ValID::Loc, llvm::lltok::LocalVar, llvm::lltok::LocalVarID, llvm::lltok::lparen, llvm::lltok::lsquare, llvm::makeArrayRef(), llvm::AtomicRMWInst::Max, llvm::ValID::MDNodeVal, llvm::ValID::MDStringVal, llvm::Intrinsic::memcpy, llvm::lltok::MetadataVar, llvm::AtomicRMWInst::Min, llvm::Monotonic, llvm::AtomicRMWInst::Nand, llvm::OverflowingBinaryOperator::NoSignedWrap, llvm::NotAtomic, llvm::OverflowingBinaryOperator::NoUnsignedWrap, llvm::AtomicRMWInst::Or, P, llvm::FunctionType::param_begin(), llvm::FunctionType::param_end(), llvm::cl::Prefix, llvm::GlobalValue::PrivateLinkage, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::iplist< NodeTy, Traits >::push_back(), llvm::lltok::rbrace, llvm::Release, llvm::AttrBuilder::removeAttribute(), llvm::APFloat::rmNearestTiesToEven, llvm::lltok::rparen, llvm::lltok::rsquare, llvm::ARMBuildAttrs::Section, llvm::MCID::Select, llvm::GlobalValue::setAlignment(), llvm::Function::setAttributes(), llvm::CallInst::setAttributes(), llvm::InvokeInst::setAttributes(), llvm::Function::setCallingConv(), llvm::CallInst::setCallingConv(), llvm::InvokeInst::setCallingConv(), llvm::LandingPadInst::setCleanup(), llvm::Instruction::setFastMathFlags(), llvm::Function::setGC(), llvm::GlobalValue::setLinkage(), llvm::Value::setName(), llvm::Function::setPrefixData(), llvm::GlobalValue::setSection(), llvm::CallInst::setTailCall(), llvm::GlobalValue::setUnnamedAddr(), llvm::GlobalValue::setVisibility(), llvm::AtomicCmpXchgInst::setVolatile(), llvm::AtomicRMWInst::setVolatile(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::iplist< NodeTy, Traits >::splice(), llvm::A64DB::ST, llvm::lltok::StringConstant, llvm::Attribute::StructRet, llvm::ValID::StrVal, llvm::ValID::StrVal2, llvm::AtomicRMWInst::Sub, llvm::ValID::t_APFloat, llvm::ValID::t_APSInt, llvm::ValID::t_Constant, llvm::ValID::t_ConstantStruct, llvm::ValID::t_EmptyArray, llvm::ValID::t_GlobalID, llvm::ValID::t_GlobalName, llvm::ValID::t_InlineAsm, llvm::ValID::t_LocalID, llvm::ValID::t_LocalName, llvm::ValID::t_MDNode, llvm::ValID::t_MDString, llvm::ValID::t_Null, llvm::ValID::t_PackedConstantStruct, llvm::ValID::t_Undef, llvm::ValID::t_Zero, llvm::ValID::UIntVal, llvm::AtomicRMWInst::UMax, llvm::AtomicRMWInst::UMin, llvm::Unordered, llvm::InlineAsm::Verify(), llvm::GlobalValue::WeakAnyLinkage, llvm::GlobalValue::WeakODRLinkage, llvm::AtomicRMWInst::Xchg, and llvm::AtomicRMWInst::Xor.
Referenced by llvm::LLParser::getContext(), llvm::MachineFunction::getFunctionNumber(), and PrintParentLoopComment().
static std::string getTypeString (Type * T) static
Definition at line 30 of file LLParser.cpp.
References llvm::raw_string_ostream::str(), and T.
Referenced by FunctionNumber(), and llvm::LLParser::Run().
* if (! EatIfPresentlltok::kw_thread_local)
ParseOptionalThreadLocal := /*empty
Referenced by llvm::TargetPassConfig::addMachinePasses(), allocset(), analyzeGlobalAux(), llvm::MachineOperandIteratorBase::analyzePhysReg(), llvm::MachineOperandIteratorBase::analyzeVirtReg(), BBHasFallthrough(), llvm::object::COFFObjectFile::COFFObjectFile(), CollectSubexprs(), CommitValueTo(), llvm::RegisterClassInfo::computePSetLimit(), llvm::createGreedyRegisterAllocator(), llvm::TargetInstrInfo::defaultDefLatency(), DeleteTriviallyDeadInstructions(), EvaluateExpression(), llvm::FastISel::FastEmitBranch(), llvm::PMDataManager::findAnalysisPass(), ftostr(), llvm::ARMConstantPoolValue::getExistingMachineCPValueImpl(), getNextBlock(), llvm::ConstantUniqueMap< llvm::InlineAsmKeyType, const llvm::InlineAsmKeyType &, llvm::PointerType, llvm::InlineAsm >::getOrCreate(), llvm::ConstantAggrUniqueMap< ArrayType, ConstantArray >::getOrCreate(), llvm::SparseSolver::getOrInitValueState(), getPointerOperand(), getRealVLDOpcode(), llvm::X86TargetLowering::getRegForInlineAsmConstraint(), llvm::MachineTraceMetrics::getResources(), llvm::ScalarEvolution::getSignedRange(), llvm::DataLayout::getStringRepresentation(), llvm::ScalarEvolution::getUnsignedRange(), llvm::InterferenceCache::init(), llvm::DenseMapInfo< Expression >::isEqual(), isSimpleLoadStore(), KnuthDiv(), llvm::MapValue(), operator<<(), llvm::DWARFDebugLoc::parse(), patchAndReplaceAllUsesWith(), llvm::RuntimeDyldELF::processRelocationRef(), StackMallocSizeClass(), llvm::ExecutionEngine::StoreValueToMemory(), translateImmediate(), llvm::ConstantRange::unionWith(), and write_uint32_le().
if (Lex. getKind() = = lltok::lparen)
Definition at line 1120 of file LLParser.cpp.
References llvm::LLLexer::Lex(), and llvm::lltok::rparen.
* if (! EatIfPresentlltok::kw_addrspace)
ParseOptionalAddrSpace := /*empty
Variable Documentation
return false
Definition at line 1125 of file LLParser.cpp.
TLM = GlobalVariable::GeneralDynamicTLSModel
Definition at line 1119 of file LLParser.cpp.
Referenced by ftostr(), llvm::LLParser::getContext(), LLVMInitializeCppBackendTarget(), ReadWideAPInt(), and llvm::LLParser::Run().