LLVM: LLVMContext.cpp File Reference
LLVM API Documentation
LLVMContext.cpp File Reference
#include "llvm/IR/LLVMContext.h"
#include "LLVMContextImpl.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/Metadata.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/SourceMgr.h"
#include <cctype>
Functions
static bool isValidName (StringRef MDName)
isValidName - Return true if Name is a valid custom metadata handler name.
Variables
static ManagedStatic< LLVMContext > GlobalContext
Function Documentation
static bool isValidName (StringRef MDName) static
isValidName - Return true if Name is a valid custom metadata handler name.
Definition at line 134 of file LLVMContext.cpp.
References llvm::StringRef::begin(), llvm::StringRef::empty(), llvm::StringRef::end(), and I.
Referenced by llvm::LLVMContext::getMDKindID().
Variable Documentation
ManagedStatic<LLVMContext> GlobalContext static
Definition at line 25 of file LLVMContext.cpp.
Referenced by llvm::getGlobalContext().