LLVM: LLVMTargetMachine.cpp File Reference
LLVM API Documentation
LLVMTargetMachine.cpp File Reference
#include "llvm/Target/TargetMachine.h"
#include "llvm/ADT/OwningPtr.h"
#include "llvm/Assembly/PrintModulePass.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/MachineFunctionAnalysis.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/PassManager.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include "llvm/Target/TargetSubtargetInfo.h"
#include "llvm/Transforms/Scalar.h"
Functions
static bool getVerboseAsm ()
static MCContext * addPassesToGenerateCode (LLVMTargetMachine *TM, PassManagerBase &PM, bool DisableVerify, AnalysisID StartAfter, AnalysisID StopAfter)
addPassesToX helper drives creation and initialization of TargetPassConfig.
Variables
static cl::opt< cl::boolOrDefault > EnableFastISelOption ("fast-isel", cl::Hidden, cl::desc("Enable the \"fast\" instruction selector"))
static cl::opt< bool > ShowMCEncoding ("show-mc-encoding", cl::Hidden, cl::desc("Show encoding in .s output"))
static cl::opt< bool > ShowMCInst ("show-mc-inst", cl::Hidden, cl::desc("Show instruction structure in .s output"))
static cl::opt< cl::boolOrDefault > AsmVerbose ("asm-verbose", cl::desc("Add comments to directives."), cl::init(cl::BOU_UNSET))
Function Documentation
static MCContext* addPassesToGenerateCode (LLVMTargetMachine * TM, PassManagerBase & PM, bool DisableVerify, AnalysisID StartAfter, AnalysisID StopAfter) static
addPassesToX helper drives creation and initialization of TargetPassConfig.
Definition at line 90 of file LLVMTargetMachine.cpp.
References llvm::TargetPassConfig::addCodeGenPrepare(), llvm::TargetPassConfig::addInstSelector(), llvm::TargetPassConfig::addIRPasses(), llvm::TargetPassConfig::addISelPrepare(), llvm::TargetPassConfig::addMachinePasses(), llvm::TargetPassConfig::addPassesToHandleExceptions(), llvm::cl::BOU_FALSE, llvm::cl::BOU_TRUE, llvm::LLVMTargetMachine::createPassConfig(), EnableFastISelOption, llvm::MachineModuleInfo::getContext(), llvm::TargetMachine::getMCAsmInfo(), llvm::TargetLoweringBase::getObjFileLowering(), llvm::TargetMachine::getOptLevel(), llvm::TargetMachine::getRegisterInfo(), llvm::TargetMachine::getTargetLowering(), llvm::CodeGenOpt::None, llvm::TargetPassConfig::setDisableVerify(), llvm::TargetMachine::setFastISel(), llvm::TargetPassConfig::setInitialized(), and llvm::TargetPassConfig::setStartStopPasses().
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile(), llvm::LLVMTargetMachine::addPassesToEmitMachineCode(), and llvm::LLVMTargetMachine::addPassesToEmitMC().
static bool getVerboseAsm () static
Definition at line 56 of file LLVMTargetMachine.cpp.
References AsmVerbose, llvm::cl::BOU_FALSE, llvm::cl::BOU_TRUE, llvm::cl::BOU_UNSET, llvm::TargetMachine::getAsmVerbosityDefault(), and llvm_unreachable.
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile().
Variable Documentation
cl::opt<cl::boolOrDefault> AsmVerbose("asm-verbose", cl::desc("Add comments to directives."), cl::init(cl::BOU_UNSET)) static
Referenced by getVerboseAsm().
cl::opt<cl::boolOrDefault> EnableFastISelOption("fast-isel", cl::Hidden, cl::desc("Enable the \"fast\" instruction selector")) static
Referenced by addPassesToGenerateCode().
cl::opt<bool> ShowMCEncoding("show-mc-encoding", cl::Hidden, cl::desc("Show encoding in .s output")) static
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile().
cl::opt<bool> ShowMCInst("show-mc-inst", cl::Hidden, cl::desc("Show instruction structure in .s output")) static
Referenced by llvm::LLVMTargetMachine::addPassesToEmitFile().