LLVM: LocalStackSlotAllocation.cpp File Reference
LLVM API Documentation
LocalStackSlotAllocation.cpp File Reference
#include "llvm/CodeGen/Passes.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetFrameLowering.h"
#include "llvm/Target/TargetRegisterInfo.h"
Macros
#define DEBUG_TYPE "localstackalloc"
Functions
STATISTIC (NumAllocations,"Number of frame indices allocated into local block")
STATISTIC (NumBaseRegisters,"Number of virtual frame base registers allocated")
STATISTIC (NumReplacements,"Number of frame indices references replaced")
INITIALIZE_PASS (LocalStackSlotPass,"localstackalloc","Local Stack Slot Allocation", false, false) bool LocalStackSlotPass
static bool lookupCandidateBaseReg (int64_t BaseOffset, int64_t FrameSizeAdjust, int64_t LocalFrameOffset, const MachineInstr *MI, const TargetRegisterInfo *TRI)
Macro Definition Documentation
#define DEBUG_TYPE "localstackalloc"
Definition at line 17 of file LocalStackSlotAllocation.cpp.
Function Documentation
INITIALIZE_PASS (LocalStackSlotPass , "localstackalloc" , "Local Stack Slot Allocation" , false , false)
Definition at line 84 of file LocalStackSlotAllocation.cpp.
References AdjustStackOffset(), Align, llvm::SmallSet< T, N, C >::count(), llvm::dbgs(), DEBUG, llvm::MachineFunction::getFrameInfo(), llvm::TargetMachine::getFrameLowering(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectIndexEnd(), llvm::MachineFrameInfo::getObjectSize(), llvm::TargetFrameLowering::getStackGrowthDirection(), llvm::MachineFrameInfo::getStackProtectorIndex(), llvm::MachineFunction::getTarget(), i, llvm::SmallSet< T, N, C >::insert(), int, llvm::MachineFrameInfo::isDeadObjectIndex(), llvm::MachineFrameInfo::mapLocalFrameObject(), llvm::MachineFrameInfo::MayNeedStackProtector(), llvm::TargetRegisterInfo::requiresVirtualBaseRegisters(), llvm::MachineFrameInfo::setLocalFrameMaxAlign(), llvm::MachineFrameInfo::setLocalFrameSize(), llvm::MachineFrameInfo::setUseLocalStackAllocationBlock(), and llvm::TargetFrameLowering::StackGrowsDown.
static bool lookupCandidateBaseReg (int64_t BaseOffset, int64_t FrameSizeAdjust, int64_t LocalFrameOffset, const MachineInstr * MI, const TargetRegisterInfo * TRI) inline static
Definition at line 200 of file LocalStackSlotAllocation.cpp.
References llvm::array_pod_sort(), BB, llvm::SmallVectorTemplateCommon< T >::begin(), llvm::MachineFunction::begin(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::dbgs(), DEBUG, llvm::SmallVectorTemplateCommon< T >::end(), llvm::MachineFunction::end(), f(), llvm::TargetRegisterInfo::getFrameIndexInstrOffset(), llvm::MachineFunction::getFrameInfo(), llvm::TargetMachine::getFrameLowering(), llvm::MachineOperand::getIndex(), llvm::MachineFrameInfo::getLocalFrameSize(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::TargetRegisterInfo::getPointerRegClass(), llvm::MachineFunction::getRegInfo(), llvm::TargetMachine::getRegisterInfo(), llvm::TargetFrameLowering::getStackGrowthDirection(), llvm::MachineFunction::getTarget(), i, I, llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isFI(), llvm::TargetRegisterInfo::isFrameOffsetLegal(), llvm::MachineFrameInfo::isObjectPreAllocated(), llvm::TargetRegisterInfo::materializeFrameBaseRegister(), llvm::A64CC::MI, llvm::TargetRegisterInfo::needsFrameBaseReg(), llvm::TargetRegisterInfo::resolveFrameIndex(), llvm::SmallVectorTemplateCommon< T >::size(), and llvm::TargetFrameLowering::StackGrowsDown.
STATISTIC (NumAllocations , "Number of frame indices allocated into local block")
STATISTIC (NumBaseRegisters , "Number of virtual frame base registers allocated")
STATISTIC (NumReplacements , "Number of frame indices references replaced")