LLVM: LoopExtractor.cpp File Reference
LLVM API Documentation
LoopExtractor.cpp File Reference
#include "llvm/Transforms/IPO.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/Dominators.h"
#include "llvm/Analysis/LoopPass.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/CodeExtractor.h"
#include <fstream>
#include <set>
Classes
struct false::SingleLoopExtractor
SingleLoopExtractor - For bugpoint.
Namespaces
false
Macros
#define DEBUG_TYPE "loop-extract"
Functions
STATISTIC (NumExtracted,"Number of loops extracted")
INITIALIZE_PASS_BEGIN (LoopExtractor,"loop-extract","Extract loops into new functions", false, false) INITIALIZE_PASS_END(LoopExtractor
INITIALIZE_PASS (SingleLoopExtractor,"loop-extract-single","Extract at most one loop into a new function", false, false) Pass *llvm
INITIALIZE_PASS (BlockExtractorPass,"extract-blocks","Extract Basic Blocks From Module (for bugpoint use)", false, false) ModulePass *llvm
Variables
loop extract
loop Extract loops into new functions
loop Extract loops into new false
static cl::opt< std::string > BlockFile ("extract-blocks-file", cl::value_desc("filename"), cl::desc("A file containing list of basic blocks to not extract"), cl::Hidden)
Macro Definition Documentation
#define DEBUG_TYPE "loop-extract"
Definition at line 17 of file LoopExtractor.cpp.
Function Documentation
INITIALIZE_PASS (SingleLoopExtractor , "loop-extract-single" , "Extract at most one loop into a new function" , false , false)
Definition at line 73 of file LoopExtractor.cpp.
References llvm::LPPassManager::deleteLoopFromQueue(), llvm::CodeExtractor::extractCodeRegion(), llvm::Function::getEntryBlock(), llvm::LoopBase< BlockT, LoopT >::getExitBlocks(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::BasicBlock::getParent(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::TerminatorInst::getSuccessor(), llvm::BasicBlock::getTerminator(), i, llvm::Loop::isLoopSimplifyForm(), and llvm::SmallVectorTemplateCommon< T >::size().
INITIALIZE_PASS (BlockExtractorPass , "extract-blocks" , "Extract Basic Blocks From Module (for bugpoint use)" , false , false)
Definition at line 185 of file LoopExtractor.cpp.
References llvm::object::advance(), BB, llvm::Function::begin(), llvm::Module::begin(), llvm::dyn_cast(), llvm::Function::empty(), llvm::Function::end(), llvm::Module::end(), llvm::errs(), llvm::CodeExtractor::extractCodeRegion(), F(), FuncName, llvm::Module::getFunction(), llvm::Function::getFunctionType(), llvm::Value::getName(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::BasicBlock::getTerminator(), llvm::InvokeInst::getUnwindDest(), i, I, llvm::tgtok::In, llvm::BasicBlock::isLandingPad(), M, llvm::pred_begin(), llvm::pred_end(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), Split(), and llvm::SplitLandingPadPredecessors().
INITIALIZE_PASS_BEGIN (LoopExtractor , "loop-extract" , "Extract loops into new functions" , false , false)
STATISTIC (NumExtracted , "Number of loops extracted")
Variable Documentation
cl::opt<std::string> BlockFile("extract-blocks-file", cl::value_desc("filename"), cl::desc("A file containing list of basic blocks to not extract"), cl::Hidden) static
Referenced by llvm::createSingleLoopExtractorPass().
loop extract
Definition at line 61 of file LoopExtractor.cpp.
Referenced by llvm::DWARFContext::dump(), and llvm::DWARFUnit::getRelocMap().
loop Extract loops into new false
Definition at line 61 of file LoopExtractor.cpp.
loop Extract loops into new functions
Definition at line 61 of file LoopExtractor.cpp.