LLVM: LoopVectorize.cpp File Reference
LLVM API Documentation
LoopVectorize.cpp File Reference
#include "llvm/Transforms/Vectorize.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/EquivalenceClasses.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/Dominators.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/LoopIterator.h"
#include "llvm/Analysis/LoopPass.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/ScalarEvolutionExpander.h"
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/Analysis/Verifier.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/IR/Value.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/PatternMatch.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Support/ValueHandle.h"
#include "llvm/Target/TargetLibraryInfo.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Local.h"
#include <algorithm>
#include <map>
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define LV_NAME "loop-vectorize"
#define DEBUG_TYPE LV_NAME
Functions
static unsigned getGEPInductionOperand (DataLayout *DL, const GetElementPtrInst *Gep)
Find the operand of the GEP that should be checked for consecutive stores. This ignores trailing indices that have no effect on the final pointer.
static Intrinsic::ID checkUnaryFloatSignature (const CallInst &I, Intrinsic::ID ValidIntrinsicID)
static Intrinsic::ID checkBinaryFloatSignature (const CallInst &I, Intrinsic::ID ValidIntrinsicID)
static Intrinsic::ID getIntrinsicIDForCall (CallInst *CI, const TargetLibraryInfo *TLI)
static unsigned getReductionBinOp (LoopVectorizationLegality::ReductionKind Kind)
This function translates the reduction kind to an LLVM binary operator.
Value * createMinMaxOp (IRBuilder<> &Builder, LoopVectorizationLegality::MinMaxReductionKind RK, Value *Left, Value *Right)
static void cse (BasicBlock *BB)
Perform cse of induction variable instructions.
static bool canIfConvertPHINodes (BasicBlock *BB)
Check whether it is safe to if-convert this phi node.
static Type * convertPointerToIntegerType (DataLayout &DL, Type *Ty)
static Type * getWiderType (DataLayout &DL, Type *Ty0, Type *Ty1)
static bool hasOutsideLoopUser (const Loop *TheLoop, Instruction *Inst, SmallPtrSet< Value *, 4 > &Reductions)
Check that the instruction has outside loop users and is not an identified reduction variable.
static bool hasComputableBounds (ScalarEvolution *SE, Value *Ptr)
Check whether a pointer can participate in a runtime bounds check.
static int isStridedPtr (ScalarEvolution *SE, DataLayout *DL, Value *Ptr, const Loop *Lp)
Check the stride of the pointer and ensure that it does not wrap in the address space.
static bool isFunctionScopeIdentifiedObject (Value *Ptr)
static bool isInBoundsGep (Value *Ptr)
static bool hasMultipleUsesOf (Instruction *I, SmallPtrSet< Instruction *, 8 > &Insts)
static bool areAllUsesIn (Instruction *I, SmallPtrSet< Instruction *, 8 > &Set)
static bool isLikelyComplexAddressComputation (Value *Ptr, LoopVectorizationLegality *Legal, ScalarEvolution *SE, const Loop *TheLoop)
Check whether the address computation for a non-consecutive memory access looks like an unlikely candidate for being merged into the indexing mode.
Pass * llvm::createLoopVectorizePass (bool NoUnrolling=false)
Variables
static cl::opt< unsigned > VectorizationFactor ("force-vector-width", cl::init(0), cl::Hidden, cl::desc("Sets the SIMD width. Zero is autoselect."))
static cl::opt< unsigned > VectorizationUnroll ("force-vector-unroll", cl::init(0), cl::Hidden, cl::desc("Sets the vectorization unroll count. ""Zero is autoselect."))
static cl::opt< bool > EnableIfConversion ("enable-if-conversion", cl::init(true), cl::Hidden, cl::desc("Enable if-conversion during vectorization."))
static cl::opt< unsigned > TinyTripCountVectorThreshold ("vectorizer-min-trip-count", cl::init(16), cl::Hidden, cl::desc("Don't vectorize loops with a constant ""trip count that is smaller than this ""value."))
We don't vectorize loops with a known constant trip count below this number.
static const unsigned TinyTripCountUnrollThreshold = 128
We don't unroll loops with a known constant trip count below this number.
static const unsigned RuntimeMemoryCheckThreshold = 8
static const unsigned MaxVectorWidth = 64
Maximum simd width.
static const unsigned MaxUnrollFactor = 16
Maximum vectorization unroll count.
static const unsigned SmallLoopCost = 20
The cost of a loop that is considered 'small' by the unroller.
static const char lv_name [] = "Loop Vectorization"
Macro Definition Documentation
#define DEBUG_TYPE LV_NAME
Definition at line 46 of file LoopVectorize.cpp.
#define LV_NAME "loop-vectorize"
Definition at line 45 of file LoopVectorize.cpp.
Function Documentation
static bool areAllUsesIn (Instruction * I, SmallPtrSet< Instruction *, 8 > & Set) static
Definition at line 4059 of file LoopVectorize.cpp.
References llvm::APIntOps::And(), llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorTemplateCommon< T >::back(), bb, be, llvm::SmallVectorTemplateCommon< T >::begin(), llvm::BasicBlock::begin(), llvm::IntervalMap< KeyT, ValT, N, Traits >::begin(), llvm::LoopBlocksDFS::beginRPO(), llvm::LoopBase< BlockT, LoopT >::block_begin(), llvm::LoopBase< BlockT, LoopT >::block_end(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::SmallSet< T, N, C >::count(), llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::dbgs(), DEBUG, llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::BasicBlock::end(), llvm::IntervalMap< KeyT, ValT, N, Traits >::end(), llvm::LoopBlocksDFS::endRPO(), llvm::ConstantInt::equalsInt(), llvm::SmallSet< T, N, C >::erase(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::PHINode::getIncomingValueForBlock(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::LoopBase< BlockT, LoopT >::getNumBlocks(), llvm::PHINode::getNumIncomingValues(), llvm::User::getNumOperands(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::Type::getPointerElementType(), llvm::LoadInst::getPointerOperand(), llvm::Type::getScalarType(), llvm::ScalarEvolution::getSCEV(), llvm::ScalarEvolution::getSmallConstantTripCount(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::DataLayout::getTypeSizeInBits(), llvm::SCEVConstant::getValue(), hasMultipleUsesOf(), llvm::Value::hasOneUse(), i, I, llvm::SmallSet< T, N, C >::insert(), llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::SCEV::isAllOnesValue(), llvm::Instruction::isAssociative(), llvm::Instruction::isCommutative(), llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), llvm::SCEV::isOne(), llvm::Type::isPointerTy(), llvm::isPowerOf2_32(), it, j(), llvm::tgtok::List, llvm::PatternMatch::m_OrdFMax(), llvm::PatternMatch::m_OrdFMin(), llvm::PatternMatch::m_SMax(), llvm::PatternMatch::m_SMin(), llvm::PatternMatch::m_UMax(), llvm::PatternMatch::m_UMin(), llvm::PatternMatch::m_UnordFMax(), llvm::PatternMatch::m_UnordFMin(), llvm::PatternMatch::m_Value(), llvm::User::op_begin(), llvm::User::op_end(), llvm::APIntOps::Or(), llvm::LoopBlocksDFS::perform(), llvm::TargetOpcode::PHI, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::pop_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::MCID::Select, llvm::SmallSet< T, N, C >::size(), llvm::SmallPtrSetImpl::size(), SmallLoopCost, llvm::A64DB::ST, llvm::Value::use_begin(), llvm::Value::use_empty(), llvm::Value::use_end(), VectorizationFactor, and llvm::APIntOps::Xor().
static bool canIfConvertPHINodes (BasicBlock * BB) static
Check whether it is safe to if-convert this phi node.
Phi nodes with constant expressions that can trap are not safe to if convert.
Definition at line 2788 of file LoopVectorize.cpp.
References llvm::BasicBlock::begin(), llvm::dbgs(), DEBUG, llvm::dyn_cast(), EnableIfConversion, llvm::BasicBlock::end(), llvm::ScalarEvolution::getBackedgeTakenCount(), llvm::ScalarEvolution::getCouldNotCompute(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getNumIncomingValues(), llvm::ScalarEvolution::getSmallConstantTripCount(), llvm::BasicBlock::getTerminator(), I, p, and TinyTripCountVectorThreshold.
static Intrinsic::ID checkBinaryFloatSignature (const CallInst & I, Intrinsic::ID ValidIntrinsicID) static
Definition at line 1873 of file LoopVectorize.cpp.
References llvm::CallInst::getArgOperand(), llvm::CallInst::getNumArgOperands(), llvm::Value::getType(), llvm::Type::isFloatingPointTy(), llvm::Intrinsic::not_intrinsic, and llvm::CallInst::onlyReadsMemory().
Referenced by getIntrinsicIDForCall().
static Intrinsic::ID checkUnaryFloatSignature (const CallInst & I, Intrinsic::ID ValidIntrinsicID) static
Definition at line 1862 of file LoopVectorize.cpp.
References llvm::CallInst::getArgOperand(), llvm::CallInst::getNumArgOperands(), llvm::Value::getType(), llvm::Type::isFloatingPointTy(), llvm::Intrinsic::not_intrinsic, and llvm::CallInst::onlyReadsMemory().
Referenced by getIntrinsicIDForCall().
static Type* convertPointerToIntegerType (DataLayout & DL, Type * Ty) static
Definition at line 2919 of file LoopVectorize.cpp.
References llvm::Type::getContext(), llvm::Type::getInt32Ty(), llvm::DataLayout::getIntPtrType(), llvm::Type::getScalarSizeInBits(), and llvm::Type::isPointerTy().
Referenced by getWiderType(), and hasOutsideLoopUser().
Value* createMinMaxOp (IRBuilder<> & Builder, LoopVectorizationLegality::MinMaxReductionKind RK, Value * Left, Value * Right)
Definition at line 2031 of file LoopVectorize.cpp.
References llvm::IRBuilder< preserveNames, T, Inserter >::CreateFCmp(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmp(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateSelect(), llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLT, llvm::Instruction::getOpcode(), llvm::hash_combine(), llvm::hash_combine_range(), I, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULT, llvm::Instruction::isIdenticalTo(), llvm_unreachable, P, llvm::MCID::Select, llvm::User::value_op_begin(), and llvm::User::value_op_end().
Referenced by cse().
static void cse (BasicBlock * BB) static
Perform cse of induction variable instructions.
Definition at line 2097 of file LoopVectorize.cpp.
References llvm::ARM_PROC::A, llvm::PHINode::addIncoming(), llvm::APIntOps::And(), B, BB, bb, be, llvm::BasicBlock::begin(), llvm::LoopBlocksDFS::beginRPO(), llvm::Call, llvm::PHINode::Create(), createMinMaxOp(), DEBUG, llvm::dyn_cast(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::BasicBlock::end(), llvm::LoopBlocksDFS::endRPO(), llvm::Instruction::eraseFromParent(), F(), llvm::ScalarEvolution::forgetLoop(), llvm::ConstantInt::get(), llvm::VectorType::get(), llvm::ConstantVector::get(), llvm::UndefValue::get(), llvm::CallInst::getArgOperand(), llvm::BranchInst::getCondition(), llvm::BasicBlock::getContext(), llvm::Intrinsic::getDeclaration(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getIncomingValueForBlock(), llvm::Type::getInt1Ty(), getIntrinsicIDForCall(), llvm::CallInst::getNumArgOperands(), llvm::PHINode::getNumIncomingValues(), llvm::BinaryOperator::getOpcode(), llvm::CastInst::getOpcode(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::CmpInst::getPredicate(), getReductionBinOp(), llvm::Type::getScalarType(), llvm::ScalarEvolution::getSCEV(), llvm::ConstantVector::getSplat(), llvm::BranchInst::getSuccessor(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::BinaryOperator::hasNoSignedWrap(), llvm::BinaryOperator::hasNoUnsignedWrap(), i, I, llvm::tgtok::In, llvm::BranchInst::isConditional(), llvm::BinaryOperator::isExact(), llvm::ScalarEvolution::isLoopInvariant(), llvm::Type::isPointerTy(), llvm::isPowerOf2_32(), it, j(), llvm::Intrinsic::lifetime_end, llvm::Intrinsic::lifetime_start, llvm_unreachable, llvm::SPII::Load, llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT >, KeyT, ValueT, KeyInfoT >::lookup(), M, llvm::APIntOps::Or(), P, llvm::LoopBlocksDFS::perform(), llvm::TargetOpcode::PHI, llvm::pred_begin(), llvm::pred_end(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::MCID::Select, llvm::BinaryOperator::setHasNoSignedWrap(), llvm::BinaryOperator::setHasNoUnsignedWrap(), llvm::BinaryOperator::setIsExact(), llvm::SPII::Store, and llvm::APIntOps::Xor().
static unsigned getGEPInductionOperand (DataLayout * DL, const GetElementPtrInst * Gep) static
Find the operand of the GEP that should be checked for consecutive stores. This ignores trailing indices that have no effect on the final pointer.
Definition at line 1073 of file LoopVectorize.cpp.
References llvm::LoopBase< BlockT, LoopT >::addBasicBlockToLoop(), llvm::LoopBase< BlockT, LoopT >::addChildLoop(), llvm::PHINode::addIncoming(), llvm::object::advance(), B, llvm::MapVector< KeyT, ValueT, MapType, VectorType >::begin(), Check(), llvm::Instruction::clone(), llvm::CmpInst::Create(), llvm::PHINode::Create(), llvm::BranchInst::Create(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateAnd(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateBitCast(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmpULE(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateOr(), llvm::dbgs(), DEBUG, llvm::dyn_cast(), llvm::MapVector< KeyT, ValueT, MapType, VectorType >::end(), llvm::Instruction::eraseFromParent(), llvm::SCEVExpander::expandCodeFor(), llvm::gep_type_begin(), llvm::ConstantInt::get(), llvm::ConstantFP::get(), llvm::VectorType::get(), llvm::ConstantVector::get(), llvm::UndefValue::get(), llvm::ScalarEvolution::getAddExpr(), llvm::LoadInst::getAlignment(), llvm::ScalarEvolution::getBackedgeTakenCount(), llvm::PHINode::getBasicBlockIndex(), llvm::ScalarEvolution::getConstant(), llvm::Value::getContext(), llvm::ScalarEvolution::getCouldNotCompute(), llvm::SequentialType::getElementType(), llvm::BasicBlock::getFirstInsertionPt(), llvm::BasicBlock::getFirstNonPHI(), llvm::Type::getInt8PtrTy(), llvm::Value::getName(), llvm::ScalarEvolution::getNoopOrZeroExtend(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::Type::getPointerAddressSpace(), llvm::Type::getPointerElementType(), llvm::LoadInst::getPointerOperand(), llvm::GetElementPtrInst::getPointerOperand(), llvm::Type::getPointerTo(), llvm::Type::getPrimitiveSizeInBits(), llvm::Type::getScalarType(), llvm::ScalarEvolution::getSCEV(), llvm::BasicBlock::getTerminator(), llvm::ConstantInt::getTrue(), llvm::ScalarEvolution::getTruncateOrNoop(), llvm::Intrinsic::getType(), llvm::SCEV::getType(), llvm::Value::getType(), llvm::GetElementPtrInst::getType(), llvm::DataLayout::getTypeAllocSize(), i, I, llvm::CmpInst::ICMP_EQ, llvm::IRBuilder< preserveNames, T, Inserter >::Insert(), llvm::Type::isAggregateType(), llvm::SCEV::isAllOnesValue(), llvm::Type::isIntegerTy(), llvm::ScalarEvolution::isLoopInvariant(), llvm::SCEV::isOne(), llvm::Type::isPointerTy(), llvm::Type::isVectorTy(), llvm::Type::isVoidTy(), j(), llvm::tgtok::List, llvm_unreachable, llvm::GC::Loop, llvm::PatternMatch::m_Zero(), llvm::PatternMatch::match(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::PHINode::setIncomingValue(), llvm::Value::setName(), llvm::User::setOperand(), and llvm::BasicBlock::splitBasicBlock().
static Intrinsic::ID getIntrinsicIDForCall (CallInst * CI, const TargetLibraryInfo * TLI) static
Definition at line 1888 of file LoopVectorize.cpp.
References llvm::LibFunc::ceil, llvm::Intrinsic::ceil, llvm::LibFunc::ceilf, llvm::LibFunc::ceill, checkBinaryFloatSignature(), checkUnaryFloatSignature(), llvm::LibFunc::copysign, llvm::Intrinsic::copysign, llvm::LibFunc::copysignf, llvm::LibFunc::copysignl, llvm::LibFunc::cos, llvm::Intrinsic::cos, llvm::LibFunc::cosf, llvm::LibFunc::cosl, llvm::LibFunc::exp, llvm::Intrinsic::exp, llvm::LibFunc::exp2, llvm::Intrinsic::exp2, llvm::LibFunc::exp2f, llvm::LibFunc::exp2l, llvm::LibFunc::expf, llvm::LibFunc::expl, F(), llvm::LibFunc::fabs, llvm::Intrinsic::fabs, llvm::LibFunc::fabsf, llvm::LibFunc::fabsl, llvm::LibFunc::floor, llvm::Intrinsic::floor, llvm::LibFunc::floorf, llvm::LibFunc::floorl, llvm::Intrinsic::fma, llvm::Intrinsic::fmuladd, llvm::CallInst::getCalledFunction(), llvm::TargetLibraryInfo::getLibFunc(), llvm::Value::getName(), llvm::GlobalValue::hasLocalLinkage(), llvm::Intrinsic::lifetime_end, llvm::Intrinsic::lifetime_start, llvm::LibFunc::log, llvm::Intrinsic::log, llvm::LibFunc::log10, llvm::Intrinsic::log10, llvm::LibFunc::log10f, llvm::LibFunc::log10l, llvm::LibFunc::log2, llvm::Intrinsic::log2, llvm::LibFunc::log2f, llvm::LibFunc::log2l, llvm::LibFunc::logf, llvm::LibFunc::logl, llvm::LibFunc::nearbyint, llvm::Intrinsic::nearbyint, llvm::LibFunc::nearbyintf, llvm::LibFunc::nearbyintl, llvm::Intrinsic::not_intrinsic, llvm::LibFunc::pow, llvm::Intrinsic::pow, llvm::LibFunc::powf, llvm::LibFunc::powl, llvm::LibFunc::rint, llvm::Intrinsic::rint, llvm::LibFunc::rintf, llvm::LibFunc::rintl, llvm::LibFunc::round, llvm::Intrinsic::round, llvm::LibFunc::roundf, llvm::LibFunc::roundl, llvm::LibFunc::sin, llvm::Intrinsic::sin, llvm::LibFunc::sinf, llvm::LibFunc::sinl, llvm::Intrinsic::sqrt, llvm::LibFunc::trunc, llvm::Intrinsic::trunc, llvm::LibFunc::truncf, and llvm::LibFunc::truncl.
Referenced by cse(), hasOutsideLoopUser(), isLikelyComplexAddressComputation(), and isStridedPtr().
static unsigned getReductionBinOp (LoopVectorizationLegality::ReductionKind Kind) static
This function translates the reduction kind to an LLVM binary operator.
Definition at line 2006 of file LoopVectorize.cpp.
References llvm::APIntOps::And(), llvm_unreachable, llvm::APIntOps::Or(), and llvm::APIntOps::Xor().
Referenced by cse().
static Type* getWiderType (DataLayout & DL, Type * Ty0, Type * Ty1) static
Definition at line 2931 of file LoopVectorize.cpp.
References convertPointerToIntegerType(), and llvm::Type::getScalarSizeInBits().
Referenced by hasOutsideLoopUser().
static bool hasComputableBounds (ScalarEvolution * SE, Value * Ptr) static
Check whether a pointer can participate in a runtime bounds check.
Definition at line 3241 of file LoopVectorize.cpp.
References llvm::dbgs(), DEBUG, llvm::dyn_cast(), llvm::Type::getPointerAddressSpace(), llvm::ScalarEvolution::getSCEV(), llvm::Value::getType(), i, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::insert(), llvm::SCEVAddRecExpr::isAffine(), isStridedPtr(), and j().
static bool hasMultipleUsesOf (Instruction * I, SmallPtrSet< Instruction *, 8 > & Insts) static
Definition at line 4046 of file LoopVectorize.cpp.
References llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::User::op_begin(), and llvm::User::op_end().
Referenced by areAllUsesIn().
static bool hasOutsideLoopUser (const Loop * TheLoop, Instruction * Inst, SmallPtrSet< Value *, 4 > & Reductions) static
Check that the instruction has outside loop users and is not an identified reduction variable.
Definition at line 2941 of file LoopVectorize.cpp.
References bb, be, llvm::LoopBase< BlockT, LoopT >::contains(), convertPointerToIntegerType(), llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::X86II::DA, llvm::dbgs(), DEBUG, llvm::dyn_cast(), F(), llvm::AttributeSet::getAttribute(), llvm::Function::getAttributes(), getIntrinsicIDForCall(), llvm::User::getOperand(), llvm::BasicBlock::getParent(), llvm::BasicBlock::getTerminator(), llvm::Attribute::getValueAsString(), getWiderType(), llvm::Function::hasFnAttribute(), I, llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), llvm::Type::isPointerTy(), llvm::VectorType::isValidElementType(), it, llvm::User::op_begin(), llvm::User::op_end(), llvm::A64DB::ST, llvm::Value::use_begin(), and llvm::Value::use_end().
static bool isFunctionScopeIdentifiedObject (Value * Ptr) static
Definition at line 3346 of file LoopVectorize.cpp.
References llvm::ARM_PROC::A, B, llvm::dbgs(), DEBUG, llvm::LoadInst::getPointerOperand(), llvm::StoreInst::getPointerOperand(), llvm::GetUnderlyingObjects(), llvm::isIdentifiedObject(), llvm::isNoAliasArgument(), llvm::isNoAliasCall(), and S.
static bool isInBoundsGep (Value * Ptr) static
Definition at line 3550 of file LoopVectorize.cpp.
Referenced by isStridedPtr().
static bool isLikelyComplexAddressComputation (Value * Ptr, LoopVectorizationLegality * Legal, ScalarEvolution * SE, const Loop * TheLoop) static
Check whether the address computation for a non-consecutive memory access looks like an unlikely candidate for being merged into the indexing mode.
We look for a GEP which has one index that is an induction variable and all other indices are loop invariant. If the stride of this access is also within a small bound we decide that this address computation can likely be merged into the addressing mode. In all other cases, we identify the address computation as complex.
Definition at line 4803 of file LoopVectorize.cpp.
References llvm::APIntOps::And(), llvm::Call, llvm::dyn_cast(), ExtractElement(), llvm::VectorType::get(), llvm::StoreInst::getAlignment(), llvm::CallInst::getArgOperand(), llvm::APInt::getBitWidth(), llvm::SelectInst::getCondition(), getIntrinsicIDForCall(), llvm::CallInst::getNumArgOperands(), llvm::User::getNumOperands(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::StoreInst::getPointerAddressSpace(), llvm::StoreInst::getPointerOperand(), llvm::ScalarEvolution::getSCEV(), llvm::APInt::getSExtValue(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::DataLayout::getTypeStoreSize(), llvm::SCEVConstant::getValue(), llvm::ConstantInt::getValue(), llvm::StoreInst::getValueOperand(), i, I, llvm::ScalarEvolution::isLoopInvariant(), llvm::Type::isVoidTy(), llvm::SPII::Load, llvm::TargetTransformInfo::OK_AnyValue, llvm::TargetTransformInfo::OK_UniformConstantValue, llvm::APIntOps::Or(), llvm::TargetOpcode::PHI, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::NVPTX::PTXLdStInstCode::Scalar, llvm::MCID::Select, llvm::TargetTransformInfo::SK_Reverse, llvm::SPII::Store, and llvm::APIntOps::Xor().
static int isStridedPtr (ScalarEvolution * SE, DataLayout * DL, Value * Ptr, const Loop * Lp) static
Check the stride of the pointer and ensure that it does not wrap in the address space.
Check whether the access through Ptr has a constant stride.
Definition at line 3557 of file LoopVectorize.cpp.
References llvm::ARM_PROC::A, llvm::APInt::abs(), B, bb, be, llvm::sys::path::begin(), llvm::LoopBase< BlockT, LoopT >::block_begin(), llvm::LoopBase< BlockT, LoopT >::block_end(), llvm::Call, llvm::SmallPtrSetImpl::clear(), llvm::dbgs(), DEBUG, llvm::dyn_cast(), llvm::sys::path::end(), llvm::EquivalenceClasses< ElemTy >::findValue(), llvm::APInt::getBitWidth(), getIntrinsicIDForCall(), llvm::EquivalenceClasses< ElemTy >::getLeaderValue(), llvm::SCEVAddRecExpr::getLoop(), llvm::ScalarEvolution::getMinusSCEV(), llvm::SCEVNAryExpr::getNoWrapFlags(), llvm::Type::getPointerElementType(), llvm::LoadInst::getPointerOperand(), llvm::StoreInst::getPointerOperand(), llvm::ScalarEvolution::getSCEV(), llvm::APInt::getSExtValue(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::SCEVConstant::getValue(), llvm::ConstantInt::getValue(), llvm::APInt::getZExtValue(), I, llvm::ARM_PROC::IE, llvm::Loop::isAnnotatedParallel(), isInBoundsGep(), llvm::APInt::isNegative(), llvm::Type::isPointerTy(), llvm::LoadInst::isSimple(), llvm::StoreInst::isSimple(), llvm::APInt::isStrictlyPositive(), it, llvm::A64DB::LD, llvm::EquivalenceClasses< ElemTy >::member_begin(), llvm::EquivalenceClasses< ElemTy >::member_end(), llvm::next(), llvm::SCEV::NoWrapMask, llvm::cl::Sink, llvm::A64DB::ST, std::swap(), VectorizationFactor, and VectorizationUnroll.
Referenced by hasComputableBounds().
Variable Documentation
cl::opt<bool> EnableIfConversion("enable-if-conversion", cl::init(true), cl::Hidden, cl::desc("Enable if-conversion during vectorization.")) static
Referenced by canIfConvertPHINodes().
const char lv_name[] = "Loop Vectorization" static
Definition at line 5038 of file LoopVectorize.cpp.
const unsigned MaxUnrollFactor = 16 static
Maximum vectorization unroll count.
Definition at line 128 of file LoopVectorize.cpp.
const unsigned MaxVectorWidth = 64 static
Maximum simd width.
Definition at line 125 of file LoopVectorize.cpp.
const unsigned RuntimeMemoryCheckThreshold = 8 static
When performing memory disambiguation checks at runtime do not make more than this number of comparisons.
Definition at line 122 of file LoopVectorize.cpp.
const unsigned SmallLoopCost = 20 static
The cost of a loop that is considered 'small' by the unroller.
Definition at line 131 of file LoopVectorize.cpp.
Referenced by areAllUsesIn().
const unsigned TinyTripCountUnrollThreshold = 128 static
We don't unroll loops with a known constant trip count below this number.
Definition at line 118 of file LoopVectorize.cpp.
cl::opt<unsigned> TinyTripCountVectorThreshold("vectorizer-min-trip-count", cl::init(16), cl::Hidden, cl::desc("Don't vectorize loops with a constant ""trip count that is smaller than this ""value.")) static
We don't vectorize loops with a known constant trip count below this number.
Referenced by canIfConvertPHINodes().
cl::opt<unsigned> VectorizationFactor("force-vector-width", cl::init(0), cl::Hidden, cl::desc("Sets the SIMD width. Zero is autoselect.")) static
Referenced by areAllUsesIn(), and isStridedPtr().
cl::opt<unsigned> VectorizationUnroll("force-vector-unroll", cl::init(0), cl::Hidden, cl::desc("Sets the vectorization unroll count. ""Zero is autoselect.")) static
Referenced by isStridedPtr().