LLVM: LoopSimplify.cpp File Reference
LLVM API Documentation
LoopSimplify.cpp File Reference
#include "llvm/Transforms/Scalar.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/SetOperations.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/DependenceAnalysis.h"
#include "llvm/Analysis/Dominators.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/LoopPass.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/CFG.h"
#include "llvm/Support/Debug.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/LoopUtils.h"
Macros
#define DEBUG_TYPE "loop-simplify"
Functions
STATISTIC (NumInserted,"Number of pre-header or exit blocks inserted")
STATISTIC (NumNested,"Number of nested loops split out")
static void PlaceSplitBlockCarefully (BasicBlock *NewBB, SmallVectorImpl< BasicBlock * > &SplitPreds, Loop *L)
INITIALIZE_PASS_BEGIN (LoopSimplify,"loop-simplify","Canonicalize natural loops", true, false) INITIALIZE_PASS_END(LoopSimplify
static void AddBlockAndPredsToSet (BasicBlock *InputBB, BasicBlock *StopBlock, std::set< BasicBlock * > &Blocks)
static PHINode * FindPHIToPartitionLoops (Loop *L, DominatorTree *DT, AliasAnalysis *AA, LoopInfo *LI)
Variables
loop simplify
loop Canonicalize natural loops
loop Canonicalize natural true
Macro Definition Documentation
#define DEBUG_TYPE "loop-simplify"
Definition at line 40 of file LoopSimplify.cpp.
Function Documentation
static void AddBlockAndPredsToSet (BasicBlock * InputBB, BasicBlock * StopBlock, std::set< BasicBlock * > & Blocks) static
AddBlockAndPredsToSet - Add the specified block, and all of its predecessors, to the specified set, if it's not already in there. Stop predecessor traversal when we reach StopBlock.
Definition at line 451 of file LoopSimplify.cpp.
References BB, I, llvm::pred_begin(), and llvm::pred_end().
Referenced by PlaceSplitBlockCarefully().
static PHINode* FindPHIToPartitionLoops (Loop * L, DominatorTree * DT, AliasAnalysis * AA, LoopInfo * LI) static
FindPHIToPartitionLoops - The first part of loop-nestification is to find a PHI node that tells us how to partition the loops.
Definition at line 469 of file LoopSimplify.cpp.
References llvm::BasicBlock::begin(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::AliasAnalysis::deleteValue(), llvm::Instruction::eraseFromParent(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getNumIncomingValues(), i, I, llvm::Value::replaceAllUsesWith(), and llvm::SimplifyInstruction().
Referenced by PlaceSplitBlockCarefully().
INITIALIZE_PASS_BEGIN (LoopSimplify , "loop-simplify" , "Canonicalize natural loops" , true , false)
void PlaceSplitBlockCarefully (BasicBlock * NewBB, SmallVectorImpl< BasicBlock * > & SplitPreds, Loop * L) static
Definition at line 495 of file LoopSimplify.cpp.
References llvm::LoopBase< BlockT, LoopT >::addBasicBlockToLoop(), AddBlockAndPredsToSet(), llvm::LoopBase< BlockT, LoopT >::addBlockEntry(), llvm::LoopBase< BlockT, LoopT >::addChildLoop(), llvm::PHINode::addIncoming(), BB, llvm::LoopBase< BlockT, LoopT >::block_begin(), llvm::LoopBase< BlockT, LoopT >::block_end(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::BasicBlock::Create(), llvm::PHINode::Create(), llvm::BranchInst::Create(), llvm::dbgs(), DEBUG, llvm::Function::end(), llvm::iplist< NodeTy, Traits >::erase(), F(), FindPHIToPartitionLoops(), llvm::Function::getBasicBlockList(), llvm::LoopBase< BlockT, LoopT >::getBlocks(), llvm::LoopBase< BlockT, LoopT >::getExitingBlocks(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::BasicBlock::getInstList(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::Value::getName(), llvm::LoopBase< BlockT, LoopT >::getNumBackEdges(), llvm::PHINode::getNumIncomingValues(), llvm::TerminatorInst::getNumSuccessors(), llvm::BasicBlock::getParent(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::LoopBase< BlockT, LoopT >::getSubLoops(), llvm::TerminatorInst::getSuccessor(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::Loop::hasDedicatedExits(), i, I, llvm::LPPassManager::insertLoopIntoQueue(), llvm::BasicBlock::isLandingPad(), llvm::GC::Loop, llvm::BasicBlock::moveAfter(), llvm::LoopBase< BlockT, LoopT >::moveToHeader(), P, llvm::pred_begin(), llvm::pred_end(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::LoopBase< BlockT, LoopT >::removeBlockFromLoop(), llvm::LoopBase< BlockT, LoopT >::removeChildLoop(), llvm::PHINode::removeIncomingValue(), llvm::PHINode::setIncomingBlock(), llvm::PHINode::setIncomingValue(), llvm::TerminatorInst::setSuccessor(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::iplist< NodeTy, Traits >::splice(), and llvm::SplitBlockPredecessors().
Referenced by llvm::InsertPreheaderForLoop().
STATISTIC (NumInserted , "Number of pre-header or exit blocks inserted")
STATISTIC (NumNested , "Number of nested loops split out")
Variable Documentation
loop Canonicalize natural loops
Definition at line 119 of file LoopSimplify.cpp.
loop simplify
Definition at line 119 of file LoopSimplify.cpp.
Referenced by PBQP::HeuristicSolverImpl< PBQP::Heuristics::Briggs >::recordRN().
loop Canonicalize natural true
Definition at line 119 of file LoopSimplify.cpp.