LLVM: LoopRerollPass.cpp File Reference
LLVM API Documentation
LoopRerollPass.cpp File Reference
#include "llvm/Transforms/Scalar.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/AliasSetTracker.h"
#include "llvm/Analysis/LoopPass.h"
#include "llvm/Analysis/ScalarEvolution.h"
#include "llvm/Analysis/ScalarEvolutionExpander.h"
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetLibraryInfo.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/LoopUtils.h"
Macros
#define DEBUG_TYPE "loop-reroll"
Functions
STATISTIC (NumRerolledLoops,"Number of rerolled loops")
static bool hasUsesOutsideLoop (Instruction *I, Loop *L)
static bool isSimpleLoadStore (Instruction *I)
Variables
static cl::opt< unsigned > MaxInc ("max-reroll-increment", cl::init(2048), cl::Hidden, cl::desc("The maximum increment for loop rerolling"))
Macro Definition Documentation
#define DEBUG_TYPE "loop-reroll"
Definition at line 14 of file LoopRerollPass.cpp.
Function Documentation
static bool hasUsesOutsideLoop (Instruction * I, Loop * L) static
Definition at line 355 of file LoopRerollPass.cpp.
References llvm::ARM_AM::add, llvm::BasicBlock::begin(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::dbgs(), DEBUG, llvm::BasicBlock::getFirstInsertionPt(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::ScalarEvolution::getSCEV(), llvm::Value::hasOneUse(), I, llvm::ARM_PROC::IE, llvm::DenseSet< ValueT, ValueInfoT >::insert(), Instructions, llvm::Instruction::isBinaryOp(), llvm::Instruction::isSameOperationAs(), MaxInc, llvm::User::op_begin(), llvm::User::op_end(), llvm::Value::use_begin(), llvm::Value::use_end(), and Users.
Referenced by isSimpleLoadStore().
static bool isSimpleLoadStore (Instruction * I) static
Definition at line 523 of file LoopRerollPass.cpp.
References llvm::AliasSetTracker::add(), llvm::sys::path::begin(), llvm::DenseSet< ValueT, ValueInfoT >::begin(), llvm::BasicBlock::begin(), llvm::AliasSetTracker::begin(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::DenseSet< ValueT, ValueInfoT >::count(), llvm::dbgs(), DEBUG, llvm::DeleteDeadPHIs(), llvm::dyn_cast(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), llvm::sys::path::const_iterator::end, llvm::sys::path::end(), llvm::DenseSet< ValueT, ValueInfoT >::end(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::BasicBlock::end(), llvm::AliasSetTracker::end(), llvm::Instruction::eraseFromParent(), llvm::SCEVAddRecExpr::evaluateAtIteration(), llvm::SCEVExpander::expandCodeFor(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::find(), llvm::SCEV::FlagAnyWrap, llvm::ScalarEvolution::getAddRecExpr(), llvm::ScalarEvolution::getConstant(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::PHINode::getIncomingValueForBlock(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::ScalarEvolution::getMinusSCEV(), llvm::ScalarEvolution::getMulExpr(), llvm::LoopBase< BlockT, LoopT >::getNumBlocks(), llvm::User::getNumOperands(), llvm::Value::getNumUses(), llvm::User::getOperand(), llvm::SCEVNAryExpr::getOperand(), llvm::SCEVAddRecExpr::getPostIncExpr(), llvm::ScalarEvolution::getSCEV(), llvm::SCEVAddRecExpr::getStart(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::BasicBlock::getTerminator(), llvm::SCEV::getType(), llvm::Value::getType(), llvm::SCEVNAryExpr::getType(), llvm::ConstantInt::getValue(), llvm::ConstantInt::getZExtValue(), H, hasUsesOutsideLoop(), i, I, llvm::CmpInst::ICMP_EQ, llvm::ARM_PROC::IE, if(), llvm::DenseSet< ValueT, ValueInfoT >::insert(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::insert(), llvm::InsertPreheaderForLoop(), llvm::SCEVAddRecExpr::isAffine(), llvm::Instruction::isAssociative(), llvm::Instruction::isCommutative(), llvm::isSafeToSpeculativelyExecute(), llvm::Instruction::isSameOperationAs(), llvm::ScalarEvolution::isSCEVable(), llvm::Instruction::isTerminator(), j(), MaxInc, llvm::Instruction::mayReadFromMemory(), llvm::Instruction::mayWriteToMemory(), llvm::A64CC::MI, llvm::next(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::BasicBlock::rbegin(), llvm::BasicBlock::rend(), llvm::SimplifyInstructionsInBlock(), llvm::DenseSet< ValueT, ValueInfoT >::size(), size, std::swap(), llvm::ConstantInt::uge(), llvm::Value::use_begin(), llvm::Value::use_end(), and Users.
STATISTIC (NumRerolledLoops , "Number of rerolled loops")
Variable Documentation
cl::opt<unsigned> MaxInc("max-reroll-increment", cl::init(2048), cl::Hidden, cl::desc("The maximum increment for loop rerolling")) static
Referenced by hasUsesOutsideLoop(), and isSimpleLoadStore().