LLVM: LowerInvoke.cpp File Reference
LLVM API Documentation
LowerInvoke.cpp File Reference
#include "llvm/Transforms/Scalar.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Local.h"
#include <csetjmp>
#include <set>
Macros
#define DEBUG_TYPE "lowerinvoke"
Functions
STATISTIC (NumInvokes,"Number of invokes replaced")
STATISTIC (NumSpilled,"Number of registers live across unwind edges")
static void MarkBlocksLiveIn (BasicBlock *BB, std::set< BasicBlock * > &LiveBBs)
Variables
static cl::opt< bool > ExpensiveEHSupport ("enable-correct-eh-support", cl::desc("Make the -lowerinvoke pass insert expensive, but correct, EH code"))
Macro Definition Documentation
#define DEBUG_TYPE "lowerinvoke"
Definition at line 37 of file LowerInvoke.cpp.
Function Documentation
static void MarkBlocksLiveIn (BasicBlock * BB, std::set< BasicBlock * > & LiveBBs) static
MarkBlocksLiveIn - Insert BB and all of its predescessors into LiveBBs until we reach blocks we've already seen.
Definition at line 255 of file LowerInvoke.cpp.
References Align, llvm::Function::arg_begin(), llvm::Function::arg_end(), llvm::SmallVectorTemplateCommon< T >::back(), BB, llvm::BasicBlock::begin(), llvm::Function::begin(), llvm::BasicBlock::Create(), llvm::GetElementPtrInst::Create(), llvm::CallInst::Create(), llvm::ExtractValueInst::Create(), llvm::InsertValueInst::Create(), llvm::BranchInst::Create(), llvm::SwitchInst::Create(), llvm::DemoteRegToStack(), llvm::SmallVectorBase::empty(), llvm::Function::end(), llvm::Instruction::eraseFromParent(), F(), llvm::ConstantInt::get(), llvm::Function::getContext(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::Type::getInt32Ty(), llvm::Type::getInt8PtrTy(), llvm::TargetLoweringBase::getJumpBufAlignment(), llvm::InvokeInst::getNormalDest(), llvm::Constant::getNullValue(), llvm::PHINode::getNumIncomingValues(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), getParent(), llvm::TargetMachine::getTargetLowering(), llvm::BasicBlock::getTerminator(), llvm::InvokeInst::getUnwindDest(), llvm::Value::hasOneUse(), i, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::Instruction::insertAfter(), NC, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::pop_back(), llvm::pred_begin(), llvm::pred_end(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::User::setOperand(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::BasicBlock::splitBasicBlock(), llvm::SplitCriticalEdge(), llvm::Instruction::use_back(), llvm::Value::use_begin(), llvm::Value::use_empty(), llvm::Value::use_end(), and Users.
STATISTIC (NumInvokes , "Number of invokes replaced")
STATISTIC (NumSpilled , "Number of registers live across unwind edges")
Variable Documentation
cl::opt<bool> ExpensiveEHSupport("enable-correct-eh-support", cl::desc("Make the -lowerinvoke pass insert expensive, but correct, EH code")) static