LLVM: LowerSwitch.cpp File Reference
LLVM API Documentation
LowerSwitch.cpp File Reference
#include "llvm/Transforms/Scalar.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/Pass.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/UnifyFunctionExitNodes.h"
#include <algorithm>
Functions
static raw_ostream & operator<< (raw_ostream &O, const LowerSwitch::CaseVector &C) LLVM_ATTRIBUTE_USED
Function Documentation
static raw_ostream & operator<< (raw_ostream & O, const LowerSwitch::CaseVector & C) static
Definition at line 114 of file LowerSwitch.cpp.
References B, llvm::BasicBlock::begin(), llvm::SwitchInst::case_begin(), llvm::SwitchInst::case_end(), llvm::BasicBlock::Create(), llvm::BranchInst::Create(), llvm::dbgs(), DEBUG, llvm::Reloc::Default, llvm::iplist< NodeTy, Traits >::erase(), llvm::ConstantExpr::getAdd(), llvm::PHINode::getBasicBlockIndex(), llvm::Function::getBasicBlockList(), llvm::SwitchInst::getCondition(), llvm::Value::getContext(), llvm::SwitchInst::getDefaultDest(), llvm::BasicBlock::getInstList(), llvm::Value::getName(), llvm::ConstantExpr::getNeg(), llvm::SwitchInst::getNumCases(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), i, I, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_ULE, llvm::iplist< NodeTy, Traits >::insert(), j(), llvm::next(), llvm::iplist< NodeTy, Traits >::push_back(), llvm::PHINode::removeIncomingValue(), and llvm::PHINode::setIncomingBlock().