LLVM: LTOCodeGenerator.cpp File Reference
LLVM API Documentation
LTOCodeGenerator.cpp File Reference
#include "llvm/LTO/LTOCodeGenerator.h"
#include "llvm/LTO/LTOModule.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Analysis/Passes.h"
#include "llvm/Analysis/Verifier.h"
#include "llvm/Bitcode/ReaderWriter.h"
#include "llvm/CodeGen/RuntimeLibcalls.h"
#include "llvm/Config/config.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/InitializePasses.h"
#include "llvm/Linker.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/SubtargetFeature.h"
#include "llvm/PassManager.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Signals.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/TargetSelect.h"
#include "llvm/Support/ToolOutputFile.h"
#include "llvm/Support/system_error.h"
#include "llvm/Target/TargetLibraryInfo.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include "llvm/Target/Mangler.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/IPO/PassManagerBuilder.h"
#include "llvm/Transforms/ObjCARC.h"
Functions
static void findUsedValues (GlobalVariable *LLVMUsed, SmallPtrSet< GlobalValue *, 8 > &UsedValues)
static void accumulateAndSortLibcalls (std::vector< StringRef > &Libcalls, const TargetLibraryInfo &TLI, const TargetLowering *Lowering)
Function Documentation
static void accumulateAndSortLibcalls (std::vector< StringRef > & Libcalls, const TargetLibraryInfo & TLI, const TargetLowering * Lowering) static
Definition at line 353 of file LTOCodeGenerator.cpp.
References llvm::TargetMachine::addAnalysisPasses(), llvm::TargetMachine::addPassesToEmitFile(), llvm::Module::alias_begin(), llvm::Module::alias_end(), llvm::GlobalValue::AppendingLinkage, llvm::array_pod_sort(), llvm::SmallPtrSet< PtrType, SmallSize >::begin(), llvm::Module::begin(), c, llvm::createInternalizePass(), llvm::createObjCARCContractPass(), llvm::createVerifierPass(), llvm::SmallPtrSetImpl::empty(), llvm::SmallPtrSet< PtrType, SmallSize >::end(), llvm::Module::end(), llvm::GlobalVariable::eraseFromParent(), f(), F(), findUsedValues(), llvm::ArrayType::get(), llvm::ConstantArray::get(), llvm::TargetMachine::getDataLayout(), llvm::Module::getGlobalVariable(), llvm::Type::getInt8PtrTy(), llvm::TargetLoweringBase::getLibcallName(), llvm::Linker::getModule(), llvm::TargetLibraryInfo::getName(), llvm::TargetMachine::getTargetLowering(), llvm::TargetMachine::getTargetTriple(), llvm::Module::global_begin(), llvm::Module::global_end(), llvm::TargetLibraryInfo::has(), i, I, llvm::LibFunc::NumLibFuncs, llvm::PassManagerBuilder::populateLTOPassManager(), and llvm::RTLIB::UNKNOWN_LIBCALL.
static void findUsedValues (GlobalVariable * LLVMUsed, SmallPtrSet< GlobalValue *, 8 > & UsedValues) static
Definition at line 342 of file LTOCodeGenerator.cpp.
References llvm::GlobalVariable::getInitializer(), llvm::User::getNumOperands(), llvm::User::getOperand(), i, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), and llvm::Value::stripPointerCasts().
Referenced by accumulateAndSortLibcalls().