LLVM: LTOModule.cpp File Reference
LLVM API Documentation
LTOModule.cpp File Reference
#include "llvm/LTO/LTOModule.h"
#include "llvm/ADT/OwningPtr.h"
#include "llvm/ADT/Triple.h"
#include "llvm/Bitcode/ReaderWriter.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCParser/MCAsmParser.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCTargetAsmParser.h"
#include "llvm/MC/SubtargetFeature.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/FileSystem.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/TargetSelect.h"
#include "llvm/Support/system_error.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include "llvm/Transforms/Utils/GlobalStatus.h"
Functions
static bool canBeHidden (const GlobalValue *GV)
static bool isDeclaration (const GlobalValue &V)
isDeclaration - Return 'true' if the global value is a declaration.
Function Documentation
static bool canBeHidden (const GlobalValue * GV) static
Definition at line 339 of file LTOModule.cpp.
References llvm::SourceMgr::AddNewSourceBuffer(), align, llvm::sys::path::begin(), llvm::StringMap< ValueTy, AllocatorTy >::begin(), llvm::LCOMM::ByteAlignment, llvm::ISD::Constant, llvm::countTrailingZeros(), llvm::createMCAsmParser(), llvm::Target::createMCAsmParser(), llvm::Target::createMCInstrInfo(), llvm::Target::createMCSubtargetInfo(), llvm::StringRef::data(), llvm::dyn_cast(), llvm::sys::path::end(), llvm::StringMap< ValueTy, AllocatorTy >::end(), llvm::OwningPtr< T >::get(), llvm::GlobalValue::getAlignment(), llvm::MCOperand::getExpr(), llvm::MCExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::GlobalValue::getLinkage(), llvm::MCSymbol::getName(), llvm::Value::getName(), llvm::Target::getName(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOperand(), llvm::StringMap< ValueTy, AllocatorTy >::GetOrCreateValue(), llvm::MCBinaryExpr::getRHS(), llvm::X86II::GS, llvm::GlobalValue::hasCommonLinkage(), llvm::GlobalValue::hasExternalLinkage(), llvm::GlobalValue::hasExternalWeakLinkage(), llvm::GlobalValue::hasHiddenVisibility(), llvm::GlobalValue::hasLinkerPrivateWeakLinkage(), llvm::GlobalValue::hasLinkOnceLinkage(), llvm::GlobalValue::hasProtectedVisibility(), llvm::GlobalValue::hasUnnamedAddr(), llvm::GlobalValue::hasWeakLinkage(), i, info, llvm::GlobalStatus::IsCompared, llvm::GlobalVariable::isConstant(), llvm::MCOperand::isExpr(), LTO_SYMBOL_DEFINITION_REGULAR, LTO_SYMBOL_DEFINITION_TENTATIVE, LTO_SYMBOL_DEFINITION_UNDEFINED, LTO_SYMBOL_DEFINITION_WEAK, LTO_SYMBOL_DEFINITION_WEAKUNDEF, LTO_SYMBOL_PERMISSIONS_CODE, LTO_SYMBOL_PERMISSIONS_DATA, LTO_SYMBOL_PERMISSIONS_RODATA, LTO_SYMBOL_SCOPE_DEFAULT, LTO_SYMBOL_SCOPE_DEFAULT_CAN_BE_HIDDEN, LTO_SYMBOL_SCOPE_HIDDEN, LTO_SYMBOL_SCOPE_INTERNAL, LTO_SYMBOL_SCOPE_MASK, LTO_SYMBOL_SCOPE_PROTECTED, llvm::MCSA_Global, llvm::MCAsmParser::Run(), S, llvm::ARMBuildAttrs::Section, llvm::MCSymbol::setSection(), llvm::MCAsmParser::setTargetParser(), llvm::StringRef::size(), llvm::SrcMgr, llvm::StringRef::startswith(), StorageClass, and llvm::ARMBuildAttrs::Symbol.
static bool isDeclaration (const GlobalValue & V) static
isDeclaration - Return 'true' if the global value is a declaration.
Definition at line 739 of file LTOModule.cpp.
References llvm::StringMap< ValueTy, AllocatorTy >::begin(), llvm::Function::begin(), f(), llvm::GlobalValue::hasAvailableExternallyLinkage(), info, llvm::GlobalValue::isDeclaration(), and llvm::GlobalValue::isMaterializable().
Referenced by llvm::TargetMachine::getTLSModel(), and LLVMIsDeclaration().