LLVM: MachineVerifier.cpp File Reference
LLVM API Documentation
MachineVerifier.cpp File Reference
#include "llvm/CodeGen/Passes.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/SetOperations.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/LiveIntervalAnalysis.h"
#include "llvm/CodeGen/LiveStackAnalysis.h"
#include "llvm/CodeGen/LiveVariables.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBundle.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/Instructions.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetRegisterInfo.h"
Functions
INITIALIZE_PASS (MachineVerifierPass,"machineverifier","Verify generated machine code", false, false) FunctionPass *llvm
static bool matchPair (MachineBasicBlock::const_succ_iterator i, const MachineBasicBlock *a, const MachineBasicBlock *b)
Function Documentation
INITIALIZE_PASS (MachineVerifierPass , "machineverifier" , "Verify generated machine code" , false , false)
Definition at line 263 of file MachineVerifier.cpp.
static bool matchPair (MachineBasicBlock::const_succ_iterator i, const MachineBasicBlock * a, const MachineBasicBlock * b) static
Definition at line 492 of file MachineVerifier.cpp.
References llvm::LiveVariables::VarInfo::AliveBlocks, llvm::TargetInstrInfo::AnalyzeBranch(), b, llvm::MachineBasicBlock::back(), BB, llvm::LiveRange::begin(), llvm::MachineBasicBlock::begin(), llvm::SmallPtrSet< PtrType, SmallSize >::begin(), llvm::MachineFunction::begin(), llvm::ConnectedVNInfoEqClasses::Classify(), llvm::SmallPtrSetImpl::clear(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::clear(), llvm::BitVector::clear(), llvm::MachineOperand::clobbersPhysReg(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::count(), llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::StringRef::data(), llvm::VNInfo::def, llvm::MachineRegisterInfo::def_begin(), llvm::MachineRegisterInfo::def_empty(), llvm::MachineRegisterInfo::def_end(), llvm::df_ext_begin(), llvm::df_ext_end(), llvm::SmallVectorBase::empty(), llvm::SmallPtrSetImpl::empty(), llvm::MachineBasicBlock::empty(), llvm::MachineFunction::empty(), llvm::LiveRange::Segment::end, llvm::LiveRange::end(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::SmallPtrSet< PtrType, SmallSize >::erase(), llvm::BitVector::find_first(), llvm::BitVector::find_next(), llvm::MachineInstr::findTiedOperandIdx(), llvm::MachineFunction::front(), llvm::MachineBasicBlock::getBasicBlock(), llvm::getBundleStart(), llvm::TargetInstrInfo::getCallFrameDestroyOpcode(), llvm::TargetInstrInfo::getCallFrameSetupOpcode(), llvm::SlotIndex::getDeadSlot(), llvm::MachineInstr::getDesc(), llvm::ConnectedVNInfoEqClasses::getEqClass(), llvm::MCAsmInfo::getExceptionHandlingType(), llvm::MachineFunction::getFrameInfo(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::TargetRegisterInfo::getLargestLegalSuperClass(), llvm::TargetRegisterInfo::getMatchingSuperRegClass(), llvm::MachineOperand::getMBB(), llvm::TargetMachine::getMCAsmInfo(), llvm::TargetRegisterClass::getName(), llvm::MCRegisterInfo::getName(), llvm::MachineBasicBlock::getNumber(), llvm::MachineFunction::getNumBlockIDs(), llvm::MCInstrDesc::getNumDefs(), llvm::InlineAsm::getNumOperandRegisters(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getNumOperands(), llvm::MCRegisterInfo::getNumRegUnits(), llvm::LiveRange::getNumValNums(), llvm::MachineRegisterInfo::getNumVirtRegs(), llvm::MachineInstr::getOperand(), llvm::MCInstrDesc::getOperandConstraint(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getParent(), llvm::SlotIndex::getPrevSlot(), llvm::MachineFrameInfo::getPristineRegs(), llvm::MachineOperand::getReg(), llvm::TargetInstrInfo::getRegClass(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineOperand::getRegMask(), llvm::SlotIndex::getRegSlot(), llvm::TargetRegisterInfo::getSubClassWithSubReg(), llvm::MachineOperand::getSubReg(), llvm::BasicBlock::getTerminator(), llvm::MachineOperand::getType(), llvm::LiveRange::getValNumInfo(), llvm::LiveRange::getVNInfoAt(), llvm::LiveRange::getVNInfoBefore(), llvm::MachineRegisterInfo::getVRegDef(), llvm::TargetRegisterInfo::hasRegUnit(), llvm::TargetRegisterClass::hasSuperClassEq(), i, I, llvm::VNInfo::id, llvm::TargetRegisterInfo::index2VirtReg(), llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::SlotIndex::isBlock(), llvm::SlotIndex::isDead(), llvm::MachineOperand::isDead(), llvm::LiveQueryResult::isDeadDef(), llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isDef(), llvm::SlotIndex::isEarlyClobber(), llvm::MachineOperand::isEarlyClobber(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isImplicit(), llvm::MachineInstr::isInlineAsm(), llvm::MachineInstr::isInsideBundle(), llvm::LiveQueryResult::isKill(), llvm::MachineOperand::isKill(), llvm::MachineBasicBlock::isLandingPad(), llvm::MachineOperand::isMetadata(), llvm::MCOperandInfo::isOptionalDef(), llvm::MachineInstr::isPHI(), llvm::VNInfo::isPHIDef(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::TargetInstrInfo::isPredicated(), llvm::MachineOperand::isReg(), llvm::SlotIndex::isRegister(), llvm::MachineInstr::isRegTiedToDefOperand(), llvm::MachineInstr::isReturn(), llvm::SlotIndex::isSameInstr(), llvm::MachineRegisterInfo::isSSA(), llvm::MachineBasicBlock::isSuccessor(), llvm::MachineOperand::isSymbol(), llvm::MachineInstr::isTerminator(), llvm::MachineOperand::isTied(), llvm::VNInfo::isUnused(), llvm::MachineOperand::isUse(), llvm::MachineOperandIteratorBase::isValid(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::MachineInstr::isVariadic(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::LiveVariables::VarInfo::Kills, llvm::A64CC::LE, llvm::LiveRange::liveAt(), llvm::MachineBasicBlock::livein_begin(), llvm::MachineBasicBlock::livein_end(), llvm::MachineInstr::mayLoad(), llvm::MachineInstr::mayStore(), llvm::MachineInstr::memoperands_begin(), llvm::MachineInstr::memoperands_end(), llvm::A64CC::MI, llvm::MachineOperand::MO_FrameIndex, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_Register, llvm::MachineOperand::MO_RegisterMask, llvm::next(), llvm::MCInstrDesc::OpInfo, llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_end(), llvm::LiveRange::Query(), llvm::MachineOperand::readsReg(), llvm::LiveInterval::reg, llvm::MachineRegisterInfo::reg_nodbg_empty(), llvm::SmallVectorImpl< T >::resize(), S, llvm::set_subtract(), llvm::set_union(), llvm::SmallPtrSetImpl::size(), llvm::ExceptionHandling::SjLj, llvm::LiveRange::Segment::start, llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_end(), llvm::MachineBasicBlock::succ_size(), llvm::SparseBitVector< ElementSize >::test(), llvm::MCOI::TIED_TO, llvm::MachineRegisterInfo::tracksLiveness(), llvm::LiveRange::Segment::valno, llvm::LiveQueryResult::valueIn(), llvm::TargetInstrInfo::verifyInstruction(), llvm::LiveRange::vni_begin(), and llvm::LiveRange::vni_end().