LLVM: MachineBlockPlacement.cpp File Reference
LLVM API Documentation
MachineBlockPlacement.cpp File Reference
#include "llvm/CodeGen/Passes.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineBlockFrequencyInfo.h"
#include "llvm/CodeGen/MachineBranchProbabilityInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetLowering.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "block-placement2"
Functions
STATISTIC (NumCondBranches,"Number of conditional branches")
STATISTIC (NumUncondBranches,"Number of uncondittional branches")
STATISTIC (CondBranchTakenFreq,"Potential frequency of taking conditional branches")
STATISTIC (UncondBranchTakenFreq,"Potential frequency of taking unconditional branches")
INITIALIZE_PASS_BEGIN (MachineBlockPlacement,"block-placement2","Branch Probability Basic Block Placement", false, false) INITIALIZE_PASS_END(MachineBlockPlacement
block Branch Probability Basic Block static false std::string getBlockName (MachineBasicBlock *BB)
Helper to print the name of a MBB.
static std::string getBlockNum (MachineBasicBlock *BB)
Helper to print the number of a MBB.
INITIALIZE_PASS_BEGIN (MachineBlockPlacementStats,"block-placement-stats","Basic Block Placement Stats", false, false) INITIALIZE_PASS_END(MachineBlockPlacementStats
Variables
static cl::opt< unsigned > AlignAllBlock ("align-all-blocks", cl::desc("Force the alignment of all ""blocks in the function."), cl::init(0), cl::Hidden)
block placement2
block Branch Probability Basic Block Placement
block Branch Probability Basic Block false
block placement stats
block placement Basic Block Placement Stats
Macro Definition Documentation
#define DEBUG_TYPE "block-placement2"
Definition at line 28 of file MachineBlockPlacement.cpp.
Function Documentation
block Branch Probability Basic Block static false std::string getBlockName (MachineBasicBlock * BB) static
Helper to print the name of a MBB.
Only used by debug logging.
Definition at line 258 of file MachineBlockPlacement.cpp.
References llvm::raw_ostream::flush(), llvm::MachineBasicBlock::getName(), and llvm::MachineBasicBlock::getNumber().
Referenced by getBlockNum(), and llvm::BlockFrequencyImpl< llvm::BasicBlock, llvm::Function, llvm::BranchProbabilityInfo >::print().
static std::string getBlockNum (MachineBasicBlock * BB) static
Helper to print the number of a MBB.
Only used by debug logging.
Definition at line 270 of file MachineBlockPlacement.cpp.
References llvm::AnalysisUsage::addRequired(), Align, AlignAllBlock, llvm::HexagonInstrInfo::AnalyzeBranch(), llvm::MachineFunction::back(), BB, llvm::SmallVectorTemplateCommon< T >::begin(), llvm::LoopBase< BlockT, LoopT >::begin(), llvm::MachineFunction::begin(), llvm::LoopBase< BlockT, LoopT >::block_begin(), llvm::LoopBase< BlockT, LoopT >::block_end(), llvm::SmallVectorImpl< T >::clear(), llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::dbgs(), DEBUG, llvm::SmallVectorBase::empty(), llvm::SmallPtrSetImpl::empty(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::LoopBase< BlockT, LoopT >::end(), llvm::MachineFunction::end(), llvm::SmallVectorImpl< T >::erase(), F(), llvm::raw_ostream::flush(), for, llvm::MachineFunction::front(), llvm::MachineFunctionPass::getAnalysisUsage(), llvm::Function::getAttributes(), getBlockName(), llvm::BranchProbability::getCompl(), llvm::MachineFunction::getFunction(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::TargetMachine::getInstrInfo(), llvm::MachineBasicBlock::getNumber(), llvm::LoopBase< BlockT, LoopT >::getNumBlocks(), llvm::MachineBasicBlock::getParent(), llvm::PassRegistry::getPassRegistry(), llvm::MachineFunction::getTarget(), llvm::TargetMachine::getTargetLowering(), I, llvm::initializeMachineBlockPlacementStatsPass(), llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::HexagonInstrInfo::InsertBranch(), llvm::MachineBasicBlock::isLayoutSuccessor(), llvm::MachineBasicBlock::isSuccessor(), llvm::A64CC::LE, llvm::next(), llvm::Attribute::OptimizeForSize, llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_end(), llvm::MachineBasicBlock::pred_size(), llvm::prior(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::HexagonInstrInfo::RemoveBranch(), llvm::HexagonInstrInfo::ReverseBranchCondition(), rotate, llvm::AnalysisUsage::setPreservesAll(), llvm::MachineFunction::splice(), llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_end(), llvm::MachineBasicBlock::succ_size(), TII, and llvm::MachineBasicBlock::updateTerminator().
Referenced by llvm::MachineTraceMetrics::Trace::getInstrSlack(), llvm::MachineTraceMetrics::Trace::getPHIDepth(), llvm::MachineTraceMetrics::Trace::getResourceDepth(), and llvm::MachineTraceMetrics::Trace::getResourceLength().
INITIALIZE_PASS_BEGIN (MachineBlockPlacement , "block-placement2" , "Branch Probability Basic Block Placement" , false , false)
INITIALIZE_PASS_BEGIN (MachineBlockPlacementStats , "block-placement-stats" , "Basic Block Placement Stats" , false , false)
STATISTIC (NumCondBranches , "Number of conditional branches")
STATISTIC (NumUncondBranches , "Number of uncondittional branches")
STATISTIC (CondBranchTakenFreq , "Potential frequency of taking conditional branches")
STATISTIC (UncondBranchTakenFreq , "Potential frequency of taking unconditional branches")
Variable Documentation
cl::opt<unsigned> AlignAllBlock("align-all-blocks", cl::desc("Force the alignment of all ""blocks in the function."), cl::init(0), cl::Hidden) static
Referenced by getBlockNum().
block placement Basic Block Placement false
Definition at line 251 of file MachineBlockPlacement.cpp.
block Branch Probability Basic Block Placement
Definition at line 251 of file MachineBlockPlacement.cpp.
block placement2
Definition at line 251 of file MachineBlockPlacement.cpp.
block placement stats
Definition at line 1169 of file MachineBlockPlacement.cpp.
block placement Basic Block Placement Stats
Definition at line 1169 of file MachineBlockPlacement.cpp.
Referenced by llvm::PrintStatistics().