LLVM: MachineSink.cpp File Reference
LLVM API Documentation
MachineSink.cpp File Reference
#include "llvm/CodeGen/Passes.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetRegisterInfo.h"
Macros
#define DEBUG_TYPE "machine-sink"
Functions
STATISTIC (NumSunk,"Number of machine instructions sunk")
STATISTIC (NumSplit,"Number of critical edges split")
STATISTIC (NumCoalesces,"Number of copies coalesced")
INITIALIZE_PASS_BEGIN (MachineSinking,"machine-sink","Machine code sinking", false, false) INITIALIZE_PASS_END(MachineSinking
static bool AvoidsSinking (MachineInstr *MI, MachineRegisterInfo *MRI)
static void collectDebugValues (MachineInstr *MI, SmallVectorImpl< MachineInstr * > &DbgValues)
static bool isPostDominatedBy (MachineBasicBlock *A, MachineBasicBlock *B)
isPostDominatedBy - Return true if A is post dominated by B.
Variables
static cl::opt< bool > SplitEdges ("machine-sink-split", cl::desc("Split critical edges during machine sinking"), cl::init(true), cl::Hidden)
machine sink
machine Machine code sinking
machine Machine code false
Macro Definition Documentation
#define DEBUG_TYPE "machine-sink"
Definition at line 19 of file MachineSink.cpp.
Function Documentation
static bool AvoidsSinking (MachineInstr * MI, MachineRegisterInfo * MRI) static
Definition at line 407 of file MachineSink.cpp.
References llvm::MachineInstr::isInsertSubreg(), llvm::MachineInstr::isRegSequence(), and llvm::MachineInstr::isSubregToReg().
Referenced by isPostDominatedBy().
static void collectDebugValues (MachineInstr * MI, SmallVectorImpl< MachineInstr * > & DbgValues) static
collectDebgValues - Scan instructions following MI and collect any matching DBG_VALUEs.
Definition at line 413 of file MachineSink.cpp.
References llvm::SmallVectorImpl< T >::clear(), llvm::X86II::DE, llvm::MachineBasicBlock::end(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineOperand::isReg(), llvm::A64CC::MI, and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by isPostDominatedBy().
INITIALIZE_PASS_BEGIN (MachineSinking , "machine-sink" , "Machine code sinking" , false , false)
static bool isPostDominatedBy (MachineBasicBlock * A, MachineBasicBlock * B) static
isPostDominatedBy - Return true if A is post dominated by B.
Definition at line 431 of file MachineSink.cpp.
References AvoidsSinking(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::MachineBasicBlock::begin(), llvm::MachineInstr::clearKillInfo(), collectDebugValues(), llvm::dbgs(), DEBUG, llvm::MachineDominatorTree::dominates(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getNumber(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), i, I, llvm::MachineRegisterInfo::isConstantPhysReg(), llvm::MachineOperand::isDead(), llvm::MachineBasicBlock::isLandingPad(), llvm::MachineBasicBlock::isLiveIn(), llvm::MachineLoopInfo::isLoopHeader(), llvm::MachineInstr::isPHI(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::MachineOperand::isReg(), llvm::MachineInstr::isSafeToMove(), llvm::TargetInstrInfo::isSafeToMoveRegClassDefs(), llvm::MachineOperand::isUse(), llvm::MachineBasicBlock::pred_size(), llvm::MachineBasicBlock::splice(), llvm::SplitCriticalEdge(), store, llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_end(), llvm::MachineBasicBlock::succ_size(), llvm::MachineRegisterInfo::use_nodbg_begin(), and llvm::MachineRegisterInfo::use_nodbg_end().
STATISTIC (NumSunk , "Number of machine instructions sunk")
STATISTIC (NumSplit , "Number of critical edges split")
STATISTIC (NumCoalesces , "Number of copies coalesced")
Variable Documentation
machine Machine code false
Definition at line 120 of file MachineSink.cpp.
void LICM::sink
sink - When an instruction is found to only be used outside of the loop, this function moves it to the exit blocks and patches up SSA form as needed. This method is guaranteed to remove the original instruction from its position, and may either delete it or move it to outside of the loop.
Definition at line 120 of file MachineSink.cpp.
Referenced by llvm::createLICMPass().
machine Machine code sinking
Definition at line 120 of file MachineSink.cpp.
cl::opt<bool> SplitEdges("machine-sink-split", cl::desc("Split critical edges during machine sinking"), cl::init(true), cl::Hidden) static