LLVM: MachineTraceMetrics.cpp File Reference
LLVM API Documentation
MachineTraceMetrics.cpp File Reference
#include "llvm/CodeGen/MachineTraceMetrics.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/SparseSet.h"
#include "llvm/CodeGen/MachineBasicBlock.h"
#include "llvm/CodeGen/MachineBranchProbabilityInfo.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include "llvm/Target/TargetSubtargetInfo.h"
Classes
class llvm::po_iterator_storage< LoopBounds, true >
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "machine-trace-metrics"
Typedefs
typedef DenseMap< const MachineInstr *, unsigned > MIHeightMap
Functions
INITIALIZE_PASS_BEGIN (MachineTraceMetrics,"machine-trace-metrics","Machine Trace Metrics", false, true) INITIALIZE_PASS_END(MachineTraceMetrics
static bool isExitingLoop (const MachineLoop *From, const MachineLoop *To)
static bool getDataDeps (const MachineInstr *UseMI, SmallVectorImpl< DataDep > &Deps, const MachineRegisterInfo *MRI)
static void getPHIDeps (const MachineInstr *UseMI, SmallVectorImpl< DataDep > &Deps, const MachineBasicBlock *Pred, const MachineRegisterInfo *MRI)
static void updatePhysDepsDownwards (const MachineInstr *UseMI, SmallVectorImpl< DataDep > &Deps, SparseSet< LiveRegUnit > &RegUnits, const TargetRegisterInfo *TRI)
static unsigned updatePhysDepsUpwards (const MachineInstr *MI, unsigned Height, SparseSet< LiveRegUnit > &RegUnits, const TargetSchedModel &SchedModel, const TargetInstrInfo *TII, const TargetRegisterInfo *TRI)
static bool pushDepHeight (const DataDep &Dep, const MachineInstr *UseMI, unsigned UseHeight, MIHeightMap &Heights, const TargetSchedModel &SchedModel, const TargetInstrInfo *TII)
Variables
machine trace metrics
machine trace Machine Trace Metrics
machine trace Machine Trace false
Macro Definition Documentation
#define DEBUG_TYPE "machine-trace-metrics"
Definition at line 10 of file MachineTraceMetrics.cpp.
Typedef Documentation
typedef DenseMap<const MachineInstr *, unsigned> MIHeightMap
Definition at line 930 of file MachineTraceMetrics.cpp.
Function Documentation
static bool getDataDeps (const MachineInstr * UseMI, SmallVectorImpl< DataDep > & Deps, const MachineRegisterInfo * MRI) static
Definition at line 639 of file MachineTraceMetrics.cpp.
References llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::MachineOperandIteratorBase::isValid(), and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by pushDepHeight(), and updatePhysDepsDownwards().
static void getPHIDeps (const MachineInstr * UseMI, SmallVectorImpl< DataDep > & Deps, const MachineBasicBlock * Pred, const MachineRegisterInfo * MRI) static
Definition at line 663 of file MachineTraceMetrics.cpp.
References llvm::MachineOperand::getMBB(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), i, llvm::MachineInstr::isPHI(), llvm::A64CC::MI, and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by llvm::MachineTraceMetrics::Trace::getPHIDepth(), pushDepHeight(), and updatePhysDepsDownwards().
INITIALIZE_PASS_BEGIN (MachineTraceMetrics , "machine-trace-metrics" , "Machine Trace Metrics" , false , true)
static bool isExitingLoop (const MachineLoop * From, const MachineLoop * To) static
Definition at line 297 of file MachineTraceMetrics.cpp.
References llvm::LoopBase< BlockT, LoopT >::contains(), llvm::MachineTraceMetrics::Ensemble, llvm::MachineTraceMetrics::Ensemble::getDepthResources(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::MachineTraceMetrics::Ensemble::getHeightResources(), llvm::MachineTraceMetrics::Ensemble::getLoopFor(), llvm::MachineTraceMetrics::Ensemble::getName(), llvm::MachineTraceMetrics::getResources(), I, llvm::MachineTraceMetrics::FixedBlockInfo::InstrCount, llvm::MachineTraceMetrics::TraceBlockInfo::InstrDepth, llvm::MachineTraceMetrics::TraceBlockInfo::InstrHeight, llvm::MachineTraceMetrics::Ensemble::MTM, llvm::MachineTraceMetrics::Ensemble::pickTracePred(), llvm::MachineTraceMetrics::Ensemble::pickTraceSucc(), llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_empty(), llvm::MachineBasicBlock::pred_end(), llvm::MachineBasicBlock::succ_begin(), and llvm::MachineBasicBlock::succ_end().
Referenced by llvm::po_iterator_storage< LoopBounds, true >::insertEdge().
static bool pushDepHeight (const DataDep & Dep, const MachineInstr * UseMI, unsigned UseHeight, MIHeightMap & Heights, const TargetSchedModel & SchedModel, const TargetInstrInfo * TII) static
Definition at line 934 of file MachineTraceMetrics.cpp.
References llvm::SmallVectorTemplateCommon< T >::back(), BB, llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::begin(), llvm::MachineBasicBlock::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::TargetSchedModel::computeOperandLatency(), llvm::dbgs(), DEBUG, llvm::SmallVectorBase::empty(), llvm::ArrayRef< T >::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::end(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::end(), llvm::MachineBasicBlock::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::erase(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::find(), llvm::format(), llvm::SmallVectorTemplateCommon< T >::front(), getDataDeps(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::MachineTraceMetrics::Ensemble::getLoopFor(), llvm::MachineBasicBlock::getNumber(), llvm::MCRegisterInfo::getNumRegUnits(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), getPHIDeps(), llvm::TargetSchedModel::getProcResource(), llvm::MachineTraceMetrics::Ensemble::getProcResourceHeights(), llvm::MachineOperand::getReg(), llvm::TargetSchedModel::getResourceFactor(), llvm::MachineRegisterInfo::getVRegDef(), i, I, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::insert(), llvm::MachineInstr::isPHI(), llvm::MachineBasicBlock::isSuccessor(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::lookup(), llvm::A64CC::MI, llvm::MachineTraceMetrics::Ensemble::MTM, llvm::MCProcResourceDesc::Name, llvm::TargetOpcode::PHI, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::pop_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::setUniverse(), llvm::ArrayRef< T >::size(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::tie(), and updatePhysDepsUpwards().
static void updatePhysDepsDownwards (const MachineInstr * UseMI, SmallVectorImpl< DataDep > & Deps, SparseSet< LiveRegUnit > & RegUnits, const TargetRegisterInfo * TRI) static
Definition at line 699 of file MachineTraceMetrics.cpp.
References llvm::MachineBasicBlock::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::TargetSchedModel::computeOperandLatency(), llvm::dbgs(), DEBUG, llvm::SmallVectorBase::empty(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::end(), llvm::MachineBasicBlock::end(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::erase(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::find(), llvm::format(), getDataDeps(), llvm::MachineBasicBlock::getNumber(), llvm::MCRegisterInfo::getNumRegUnits(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), getPHIDeps(), llvm::TargetSchedModel::getProcResource(), llvm::MachineTraceMetrics::Ensemble::getProcResourceDepths(), llvm::MachineOperand::getReg(), llvm::TargetSchedModel::getResourceFactor(), llvm::MachineRegisterInfo::getVRegDef(), i, I, llvm::MachineInstr::isPHI(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::MachineOperandIteratorBase::isValid(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::MachineTraceMetrics::Ensemble::MTM, llvm::MCProcResourceDesc::Name, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::setUniverse(), llvm::ArrayRef< T >::size(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::SmallVectorTemplateCommon< T >::size().
static unsigned updatePhysDepsUpwards (const MachineInstr * MI, unsigned Height, SparseSet< LiveRegUnit > & RegUnits, const TargetSchedModel & SchedModel, const TargetInstrInfo * TII, const TargetRegisterInfo * TRI) static
Definition at line 877 of file MachineTraceMetrics.cpp.
References llvm::TargetSchedModel::computeOperandLatency(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::end(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::erase(), llvm::SparseSet< ValueT, KeyFunctorT, SparseT >::find(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), i, I, llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::MachineInstr::isTransient(), llvm::MachineOperandIteratorBase::isValid(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::A64CC::MI, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by pushDepHeight().
Variable Documentation
machine trace Machine Trace false
Definition at line 37 of file MachineTraceMetrics.cpp.
machine trace metrics
Definition at line 37 of file MachineTraceMetrics.cpp.
machine trace Machine Trace Metrics
Definition at line 37 of file MachineTraceMetrics.cpp.
Referenced by ApproximateLoopSize(), and shouldSpeculateInstrs().