LLVM: MachOUniversal.cpp File Reference
LLVM API Documentation
MachOUniversal.cpp File Reference
#include "llvm/Object/MachOUniversal.h"
#include "llvm/Object/MachO.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Support/Casting.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/MemoryBuffer.h"
Functions
template<typename T >
static void SwapValue (T &Value)
template<typename T >
static void SwapStruct (T &Value)
template<>
void SwapStruct (MachO::fat_header &H)
template<>
void SwapStruct (MachO::fat_arch &H)
template<typename T >
static T getUniversalBinaryStruct (const char *Ptr)
static bool getCTMForArch (Triple::ArchType Arch, MachO::CPUType &CTM)
Function Documentation
static bool getCTMForArch (Triple::ArchType Arch, MachO::CPUType & CTM) static
Definition at line 116 of file MachOUniversal.cpp.
References llvm::Triple::arm, llvm::MachO::CPU_TYPE_ARM, llvm::MachO::CPU_TYPE_I386, llvm::MachO::CPU_TYPE_POWERPC, llvm::MachO::CPU_TYPE_POWERPC64, llvm::MachO::CPU_TYPE_SPARC, llvm::MachO::CPU_TYPE_X86_64, llvm::Triple::ppc, llvm::Triple::ppc64, llvm::Triple::sparc, llvm::Triple::x86, and llvm::Triple::x86_64.
Referenced by llvm::object::MachOUniversalBinary::getObjectForArch().
template<typename T > static T getUniversalBinaryStruct (const char * Ptr) static
Definition at line 49 of file MachOUniversal.cpp.
References llvm::sys::IsLittleEndianHost, llvm::Intrinsic::memcpy, and llvm::object::SwapStruct().
template<typename T > static void SwapStruct (T & Value) static
template<> void SwapStruct (MachO::fat_header & H)
Definition at line 34 of file MachOUniversal.cpp.
References llvm::MachO::fat_header::magic, llvm::MachO::fat_header::nfat_arch, and llvm::object::SwapValue().
template<> void SwapStruct (MachO::fat_arch & H)
Definition at line 40 of file MachOUniversal.cpp.
References llvm::MachO::fat_arch::align, llvm::MachO::fat_arch::cpusubtype, llvm::MachO::fat_arch::cputype, llvm::MachO::fat_arch::offset, llvm::MachO::fat_arch::size, and llvm::object::SwapValue().
template<typename T > static void SwapValue (T & Value) static
Definition at line 26 of file MachOUniversal.cpp.
References llvm::sys::SwapByteOrder(), and llvm::object::SwapStruct().