LLVM: MachineCopyPropagation.cpp File Reference
LLVM API Documentation
MachineCopyPropagation.cpp File Reference
#include "llvm/CodeGen/Passes.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/Pass.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetRegisterInfo.h"
Macros
#define DEBUG_TYPE "codegen-cp"
Functions
STATISTIC (NumDeletes,"Number of dead copies deleted")
INITIALIZE_PASS (MachineCopyPropagation,"machine-cp","Machine Copy Propagation Pass", false, false) void MachineCopyPropagation
static bool NoInterveningSideEffect (const MachineInstr *CopyMI, const MachineInstr *MI)
static bool isNopCopy (MachineInstr *CopyMI, unsigned Def, unsigned Src, const TargetRegisterInfo *TRI)
Macro Definition Documentation
#define DEBUG_TYPE "codegen-cp"
Definition at line 14 of file MachineCopyPropagation.cpp.
Function Documentation
INITIALIZE_PASS (MachineCopyPropagation , "machine-cp" , "Machine Copy Propagation Pass" , false , false)
Definition at line 61 of file MachineCopyPropagation.cpp.
References I, llvm::MCRegisterInfo::DiffListIterator::isValid(), and llvm::MCRegAliasIterator::isValid().
static bool isNopCopy (MachineInstr * CopyMI, unsigned Def, unsigned Src, const TargetRegisterInfo * TRI) static
isNopCopy - Return true if the specified copy is really a nop. That is if the source of the copy is the same of the definition of the copy that supplied the source. If the source of the copy is a sub-register than it must check the sub-indices match. e.g. ecx = mov eax al = mov cl But not ecx = mov eax al = mov ch
Definition at line 113 of file MachineCopyPropagation.cpp.
References llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::begin(), llvm::sys::path::begin(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::clear(), llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::clear(), llvm::MachineOperand::clobbersPhysReg(), llvm::X86II::DE, llvm::tgtok::Def, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::end(), llvm::sys::path::end(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::erase(), llvm::MachineInstr::eraseFromParent(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::find(), llvm::TargetMachine::getInstrInfo(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::TargetMachine::getRegisterInfo(), llvm::MCRegisterInfo::getSubRegIndex(), llvm::MachineFunction::getTarget(), i, I, llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::insert(), llvm::MachineInstr::isCopy(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRegMask(), llvm::MCRegisterInfo::isSubRegister(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::MCRegAliasIterator::isValid(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::TargetOpcode::KILL, llvm::A64CC::MI, MRI, NoInterveningSideEffect(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::remove(), llvm::report_fatal_error(), llvm::MachineInstr::setDesc(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::MachineBasicBlock::succ_empty(), and TII.
static bool NoInterveningSideEffect (const MachineInstr * CopyMI, const MachineInstr * MI) static
Definition at line 85 of file MachineCopyPropagation.cpp.
References llvm::MachineBasicBlock::end(), llvm::MachineInstr::getParent(), I, and llvm::A64CC::MI.
Referenced by isNopCopy().
STATISTIC (NumDeletes , "Number of dead copies deleted")