LLVM: MachineLICM.cpp File Reference
LLVM API Documentation
MachineLICM.cpp File Reference
#include "llvm/CodeGen/Passes.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/PseudoSourceValue.h"
#include "llvm/MC/MCInstrItineraries.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetRegisterInfo.h"
Macros
#define DEBUG_TYPE "machine-licm"
Functions
STATISTIC (NumHoisted,"Number of machine instructions hoisted out of loops")
STATISTIC (NumLowRP,"Number of instructions hoisted in low reg pressure situation")
STATISTIC (NumHighLatency,"Number of high latency instructions hoisted")
STATISTIC (NumCSEed,"Number of hoisted machine instructions CSEed")
STATISTIC (NumPostRAHoisted,"Number of machine instructions hoisted out of loops post regalloc")
INITIALIZE_PASS_BEGIN (MachineLICM,"machinelicm","Machine Loop Invariant Code Motion", false, false) INITIALIZE_PASS_END(MachineLICM
Machine Loop Invariant Code static false bool LoopIsOuterMostWithPredecessor (MachineLoop *CurLoop)
static bool InstructionStoresToFI (const MachineInstr *MI, int FI)
static bool isOperandKill (const MachineOperand &MO, MachineRegisterInfo *MRI)
static bool isLoadFromGOTOrConstantPool (MachineInstr &MI)
Variables
static cl::opt< bool > AvoidSpeculation ("avoid-speculation", cl::desc("MachineLICM should avoid speculation"), cl::init(true), cl::Hidden)
machinelicm
Machine Loop Invariant Code Motion
Machine Loop Invariant Code false
Macro Definition Documentation
#define DEBUG_TYPE "machine-licm"
Definition at line 23 of file MachineLICM.cpp.
Function Documentation
INITIALIZE_PASS_BEGIN (MachineLICM , "machinelicm" , "Machine Loop Invariant Code Motion" , false , false)
static bool InstructionStoresToFI (const MachineInstr * MI, int FI) static
InstructionStoresToFI - Return true if instruction stores to the specified frame.
Definition at line 387 of file MachineLICM.cpp.
References llvm::MachineBasicBlock::addLiveIn(), BB, llvm::MachineBasicBlock::begin(), llvm::SmallSet< T, N, C >::clear(), llvm::SmallVectorImpl< T >::clear(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::SmallSet< T, N, C >::count(), llvm::dbgs(), DEBUG, llvm::tgtok::Def, llvm::MachineDominatorTree::dominates(), llvm::SmallVectorBase::empty(), llvm::MachineBasicBlock::end(), llvm::DomTreeNodeBase< NodeT >::getBlock(), llvm::LoopBase< BlockT, LoopT >::getBlocks(), llvm::DomTreeNodeBase< NodeT >::getChildren(), llvm::LoopBase< BlockT, LoopT >::getExitingBlocks(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::MachineOperand::getIndex(), llvm::MachineLoopInfo::getLoopFor(), llvm::MachineBasicBlock::getName(), llvm::MachineBasicBlock::getNumber(), llvm::MachineInstr::getNumOperands(), llvm::MCRegisterInfo::getNumRegs(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getRegMask(), i, I, llvm::SmallSet< T, N, C >::insert(), llvm::MachineOperand::isDead(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isFI(), llvm::MachineOperand::isImplicit(), llvm::MachineBasicBlock::isLandingPad(), llvm::MachineBasicBlock::isLiveIn(), llvm::TargetInstrInfo::isLoadFromStackSlot(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRegMask(), llvm::MachineFrameInfo::isSpillSlotObjectIndex(), llvm::MCRegisterInfo::isSuperRegister(), llvm::MCRegAliasIterator::isValid(), j(), llvm::MachineBasicBlock::livein_begin(), llvm::MachineBasicBlock::livein_end(), llvm::MachineInstr::memoperands_begin(), llvm::MachineInstr::memoperands_end(), llvm::A64CC::MI, MII, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::pop_back(), llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::BitVector::set(), llvm::BitVector::setBitsNotInMask(), llvm::MachineOperand::setIsKill(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::MachineBasicBlock::splice(), llvm::MachineBasicBlock::succ_size(), and llvm::BitVector::test().
static bool isLoadFromGOTOrConstantPool (MachineInstr & MI) static
isLoadFromGOTOrConstantPool - Return true if this machine instruction loads from global offset table or constant pool.
Definition at line 878 of file MachineLICM.cpp.
References AvoidSpeculation, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::begin(), llvm::MachineBasicBlock::begin(), llvm::MachineInstr::canFoldAsLoad(), llvm::MachineRegisterInfo::clearKillFlags(), llvm::MachineRegisterInfo::constrainRegClass(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::dbgs(), DEBUG, llvm::SmallVectorBase::empty(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::end(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::find(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::find(), llvm::MCInstrInfo::get(), llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineInstr::getDesc(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::LoopBase< BlockT, LoopT >::getLoopPredecessor(), llvm::LoopBase< BlockT, LoopT >::getLoopPreheader(), llvm::MachineBasicBlock::getName(), llvm::MCInstrDesc::getNumDefs(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::TargetInstrInfo::getOpcodeAfterMemoryUnfold(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::TargetInstrInfo::getRegClass(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineRegisterInfo::getVRegDef(), llvm::TargetInstrInfo::hasHighOperandLatency(), llvm::TargetInstrInfo::hasLowDefLatency(), i, I, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::insert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::insert(), llvm::MachineInstr::isAsCheapAsAMove(), llvm::MachineRegisterInfo::isConstantPhysReg(), llvm::MachineInstr::isCopy(), llvm::MachineInstr::isCopyLike(), llvm::MachineOperand::isDead(), llvm::MachineOperand::isDef(), llvm::InstrItineraryData::isEmpty(), isExitBlock(), llvm::MachineOperand::isImplicit(), llvm::MachineInstr::isImplicitDef(), llvm::MachineInstr::isInvariantLoad(), llvm::MachineBasicBlock::isLiveIn(), isOperandKill(), llvm::MachineInstr::isPHI(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::MachineOperand::isReg(), llvm::MachineInstr::isSafeToMove(), llvm::TargetInstrInfo::isTriviallyReMaterializable(), llvm::MachineOperand::isUse(), llvm::MachineOperandIteratorBase::isValid(), llvm::TargetRegisterInfo::isVirtualRegister(), j(), llvm::MachineInstr::mayLoad(), llvm::MachineInstr::memoperands_begin(), llvm::MachineInstr::memoperands_end(), llvm::A64CC::MI, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::TargetInstrInfo::produceSameValue(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::MachineRegisterInfo::replaceRegWith(), llvm::NVPTX::PTXCvtMode::RP, llvm::MachineRegisterInfo::setRegClass(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::MachineBasicBlock::splice(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::TargetInstrInfo::unfoldMemoryOperand(), llvm::MachineRegisterInfo::use_begin(), llvm::MachineRegisterInfo::use_end(), llvm::MachineRegisterInfo::use_nodbg_begin(), llvm::MachineRegisterInfo::use_nodbg_empty(), and llvm::MachineRegisterInfo::use_nodbg_end().
static bool isOperandKill (const MachineOperand & MO, MachineRegisterInfo * MRI) static
Definition at line 772 of file MachineLICM.cpp.
References llvm::TargetInstrInfo::AnalyzeBranch(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::MachineBasicBlock::begin(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::getDesc(), llvm::TargetRegisterClass::getID(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::TargetLoweringBase::getRepRegClassCostFor(), llvm::TargetLoweringBase::getRepRegClassFor(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), i, llvm::SmallSet< T, N, C >::insert(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isImplicit(), llvm::MachineInstr::isImplicitDef(), llvm::MachineOperand::isKill(), llvm::MachineOperand::isReg(), llvm::TargetRegisterInfo::isVirtualRegister(), MII, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_size(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::MVT::Untyped, and llvm::TargetRegisterClass::vt_begin().
Referenced by isLoadFromGOTOrConstantPool().
Machine Loop Invariant Code static false bool LoopIsOuterMostWithPredecessor (MachineLoop * CurLoop) static
LoopIsOuterMostWithPredecessor - Test if the given loop is the outer-most loop that has a unique predecessor.
Definition at line 309 of file MachineLICM.cpp.
References llvm::MachineLoopInfo::begin(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::LoopBase< BlockT, LoopT >::begin(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::clear(), llvm::SmallVectorImpl< T >::clear(), llvm::dbgs(), DEBUG, llvm::MachineLoopInfo::end(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::LoopBase< BlockT, LoopT >::end(), llvm::LoopBase< BlockT, LoopT >::getExitBlocks(), llvm::MachineFunction::getFrameInfo(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::TargetMachine::getInstrInfo(), llvm::TargetMachine::getInstrItineraryData(), llvm::MachineFunction::getName(), llvm::TargetRegisterInfo::getNumRegClasses(), llvm::LoopBase< BlockT, LoopT >::getParentLoop(), llvm::MachineFunction::getRegInfo(), llvm::TargetMachine::getRegisterInfo(), llvm::TargetRegisterInfo::getRegPressureLimit(), llvm::MachineFunction::getTarget(), llvm::TargetMachine::getTargetLowering(), I, llvm::MachineRegisterInfo::isSSA(), N, llvm::TargetRegisterInfo::regclass_begin(), llvm::TargetRegisterInfo::regclass_end(), and llvm::SmallVectorImpl< T >::resize().
STATISTIC (NumHoisted , "Number of machine instructions hoisted out of loops")
STATISTIC (NumLowRP , "Number of instructions hoisted in low reg pressure situation")
STATISTIC (NumHighLatency , "Number of high latency instructions hoisted")
STATISTIC (NumCSEed , "Number of hoisted machine instructions CSEed")
STATISTIC (NumPostRAHoisted , "Number of machine instructions hoisted out of loops post regalloc")
Variable Documentation
cl::opt<bool> AvoidSpeculation("avoid-speculation", cl::desc("MachineLICM should avoid speculation"), cl::init(true), cl::Hidden) static
Referenced by isLoadFromGOTOrConstantPool().
Machine Loop Invariant Code false
Definition at line 304 of file MachineLICM.cpp.
machinelicm
Definition at line 304 of file MachineLICM.cpp.
Machine Loop Invariant Code Motion
Definition at line 304 of file MachineLICM.cpp.