LLVM: MachineInstrBundle.cpp File Reference
LLVM API Documentation
MachineInstrBundle.cpp File Reference
#include "llvm/CodeGen/MachineInstrBundle.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetRegisterInfo.h"
Functions
INITIALIZE_PASS (UnpackMachineBundles,"unpack-mi-bundles","Unpack machine instruction bundles", false, false) bool UnpackMachineBundles
INITIALIZE_PASS (FinalizeMachineBundles,"finalize-mi-bundles","Finalize machine instruction bundles", false, false) bool FinalizeMachineBundles
Function Documentation
INITIALIZE_PASS (UnpackMachineBundles , "unpack-mi-bundles" , "Unpack machine instruction bundles" , false , false)
Definition at line 35 of file MachineInstrBundle.cpp.
References llvm::MachineInstr::eraseFromParent(), llvm::PassRegistry::getPassRegistry(), i, I, llvm::initializeFinalizeMachineBundlesPass(), llvm::MachineBasicBlock::instr_begin(), llvm::MachineBasicBlock::instr_end(), llvm::MachineInstr::isBundle(), llvm::MachineOperand::isInternalRead(), llvm::MachineOperand::isReg(), llvm::A64CC::MI, MII, and llvm::MachineOperand::setIsInternalRead().
INITIALIZE_PASS (FinalizeMachineBundles , "finalize-mi-bundles" , "Finalize machine instruction bundles" , false , false)
Definition at line 86 of file MachineInstrBundle.cpp.
References llvm::finalizeBundles().