LLVM: Mangler.cpp File Reference
LLVM API Documentation
Mangler.cpp File Reference
#include "llvm/Target/Mangler.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/Twine.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Support/raw_ostream.h"
Functions
static void AddFastCallStdCallSuffix (SmallVectorImpl< char > &OutName, const Function *F, const DataLayout &TD)
Function Documentation
static void AddFastCallStdCallSuffix (SmallVectorImpl< char > & OutName, const Function * F, const DataLayout & TD) static
AddFastCallStdCallSuffix - Microsoft fastcall and stdcall functions require a suffix on their name indicating the number of words of arguments they take.
Definition at line 69 of file Mangler.cpp.
References llvm::Function::arg_begin(), llvm::Function::arg_end(), and llvm::DataLayout::getTypeAllocSize().
Referenced by llvm::Mangler::getNameWithPrefix().