LLVM: MCAsmStreamer.cpp File Reference
LLVM API Documentation
MCAsmStreamer.cpp File Reference
#include "llvm/MC/MCStreamer.h"
#include "llvm/ADT/OwningPtr.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/Twine.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixupKindInfo.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstPrinter.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSectionCOFF.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Format.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/Path.h"
#include <cctype>
Functions
static int64_t truncateToSize (int64_t Value, unsigned Bytes)
static char toOctal (int X)
static void PrintQuotedString (StringRef Data, raw_ostream &OS)
static const MCSection * getWin64EHTableSection (StringRef suffix, MCContext &context)
Function Documentation
static const MCSection* getWin64EHTableSection (StringRef suffix, MCContext & context) static
this duplicate code in MCWin64EH.cpp.
Definition at line 1142 of file MCAsmStreamer.cpp.
References llvm::StringRef::back(), llvm::tgtok::Bit, llvm::tgtok::Code, llvm::MCInst::dump_pretty(), llvm::MCDwarfFileTable::Emit(), llvm::MCGenDwarfInfo::Emit(), llvm::MCStreamer::EmitWin64EHAllocStack(), llvm::MCStreamer::EmitWin64EHEndProlog(), llvm::MCStreamer::EmitWin64EHHandlerData(), llvm::MCStreamer::EmitWin64EHPushFrame(), llvm::MCStreamer::EmitWin64EHPushReg(), llvm::MCStreamer::EmitWin64EHSaveReg(), llvm::MCStreamer::EmitWin64EHSaveXMM(), llvm::MCStreamer::EmitWin64EHSetFrame(), llvm::StringRef::empty(), llvm::MCCodeEmitter::EncodeInstruction(), F(), llvm::raw_ostream::flush(), llvm::format(), llvm::MCWin64EHUnwindInfo::Function, llvm::OwningPtr< T >::get(), llvm::MCContext::getCOFFSection(), llvm::SectionKind::getDataRel(), llvm::MCAsmBackend::getFixupKindInfo(), llvm::MCFixup::getKind(), llvm::MCContext::getObjectFileInfo(), llvm::MCFixup::getOffset(), llvm::MCWin64EHUnwindEmitter::GetSectionSuffix(), llvm::MCFixup::getValue(), llvm::getWin64EHTableSection(), llvm::MCObjectFileInfo::getXDataSection(), i, llvm::MCAsmInfo::isLittleEndian(), j(), llvm::MCFixupKindInfo::Name, llvm::MCInst::print(), llvm::MCInstPrinter::printInst(), Register, llvm::SmallVectorImpl< T >::resize(), llvm::StringRef::size(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::tgtok::String, llvm::StringRef::substr(), llvm::MCFixupKindInfo::TargetOffset, and llvm::MCFixupKindInfo::TargetSize.
static void PrintQuotedString (StringRef Data, raw_ostream & OS) static
Definition at line 600 of file MCAsmStreamer.cpp.
References llvm::sys::path::append(), llvm::StringRef::back(), llvm::LCOMM::ByteAlignment, llvm::MCConstantExpr::Create(), Debug, DWARF2_FLAG_BASIC_BLOCK, DWARF2_FLAG_EPILOGUE_BEGIN, DWARF2_FLAG_IS_STMT, DWARF2_FLAG_PROLOGUE_END, llvm::MCStreamer::EmitCFIAdjustCfaOffset(), llvm::MCStreamer::EmitCFIDefCfa(), llvm::MCStreamer::EmitCFIDefCfaOffset(), llvm::MCStreamer::EmitCFIDefCfaRegister(), llvm::MCStreamer::EmitCFILsda(), llvm::MCStreamer::EmitCFIOffset(), llvm::MCStreamer::EmitCFIPersonality(), llvm::MCStreamer::EmitCFIRegister(), llvm::MCStreamer::EmitCFIRelOffset(), llvm::MCStreamer::EmitCFIRememberState(), llvm::MCStreamer::EmitCFIRestoreState(), llvm::MCStreamer::EmitCFISameValue(), llvm::MCStreamer::EmitCFISections(), llvm::MCStreamer::EmitCFISignalFrame(), llvm::MCStreamer::EmitCFIUndefined(), llvm::MCStreamer::EmitCFIWindowSave(), llvm::MCStreamer::EmitDwarfFileDirective(), llvm::MCStreamer::EmitDwarfLocDirective(), llvm::MCStreamer::EmitFill(), llvm::MCStreamer::EmitWin64EHEndChained(), llvm::MCStreamer::EmitWin64EHEndProc(), llvm::MCStreamer::EmitWin64EHHandler(), llvm::MCStreamer::EmitWin64EHStartChained(), llvm::MCStreamer::EmitWin64EHStartProc(), llvm::StringRef::empty(), llvm::MCDwarfFrameInfo::End, llvm::MCAsmInfo::getAlignDirective(), llvm::MCAsmInfo::getAlignmentIsInBytes(), llvm::MCAsmInfo::getAsciiDirective(), llvm::MCAsmInfo::getAscizDirective(), llvm::MCAsmInfo::getCommentColumn(), llvm::MCAsmInfo::getCommentString(), llvm::MCAsmInfo::getData16bitsDirective(), llvm::MCAsmInfo::getData32bitsDirective(), llvm::MCAsmInfo::getData64bitsDirective(), llvm::MCAsmInfo::getData8bitsDirective(), llvm::MCAsmInfo::getGPRel32Directive(), llvm::MCAsmInfo::getGPRel64Directive(), llvm::MCRegisterInfo::getLLVMRegNum(), llvm::MCAsmInfo::getTextAlignFillValue(), llvm::MCAsmInfo::getZeroDirective(), llvm::MCAsmInfo::hasIdentDirective(), llvm::MCAsmInfo::hasLEB128(), llvm::MCAsmInfo::hasSingleParameterDotFile(), i, int, llvm::sys::path::is_absolute(), llvm::MCAsmInfo::isLittleEndian(), llvm::isPowerOf2_32(), llvm_unreachable, llvm::Log2_32(), MRI, llvm::formatted_raw_ostream::PadToColumn(), llvm::MCInstPrinter::printRegName(), Register, llvm::report_fatal_error(), llvm::StringRef::size(), llvm::StringRef::substr(), llvm::ARMBuildAttrs::Symbol, truncateToSize(), llvm::MCAsmInfo::useDwarfRegNumForCFI(), and llvm::raw_ostream::write_hex().
static char toOctal (int X) inline static
Definition at line 598 of file MCAsmStreamer.cpp.
static int64_t truncateToSize (int64_t Value, unsigned Bytes) inline static
Definition at line 308 of file MCAsmStreamer.cpp.
References llvm::LCOMM::ByteAlignment, llvm::MCAsmInfo::doesSupportDataRegionDirectives(), llvm::dwarf::DW_CFA_advance_loc4, llvm::MCStreamer::EmitDebugLabel(), llvm::MCStreamer::EmitLabel(), llvm::ArrayRef< T >::empty(), llvm::MCAsmInfo::getCode16Directive(), llvm::MCAsmInfo::getCode32Directive(), llvm::MCAsmInfo::getCode64Directive(), llvm::MCAsmInfo::getCOMMDirectiveAlignmentIsInBytes(), llvm::MCAsmInfo::getCommentString(), llvm::MCAsmInfo::getDebugLabelSuffix(), llvm::MCAsmInfo::getGlobalDirective(), llvm::MCAsmInfo::getLabelSuffix(), llvm::MCAsmInfo::getLCOMMDirectiveAlignmentType(), llvm::MCSectionMachO::getSectionName(), llvm::MCSectionMachO::getSegmentName(), llvm::MCAsmInfo::getWeakRefDirective(), llvm::MCAsmInfo::hasDotTypeDotSizeDirective(), llvm::MCAsmInfo::hasSubsectionsViaSymbols(), llvm::isPowerOf2_32(), llvm::MCSymbol::isUndefined(), it, llvm_unreachable, llvm::Log2_32(), llvm::LCOMM::Log2Alignment, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::lookup(), llvm::MCAF_Code16, llvm::MCAF_Code32, llvm::MCAF_Code64, llvm::MCAF_SubsectionsViaSymbols, llvm::MCAF_SyntaxUnified, llvm::MCDR_DataRegion, llvm::MCDR_DataRegionEnd, llvm::MCDR_DataRegionJT16, llvm::MCDR_DataRegionJT32, llvm::MCDR_DataRegionJT8, llvm::MCSA_ELF_TypeCommon, llvm::MCSA_ELF_TypeFunction, llvm::MCSA_ELF_TypeGnuUniqueObject, llvm::MCSA_ELF_TypeIndFunction, llvm::MCSA_ELF_TypeNoType, llvm::MCSA_ELF_TypeObject, llvm::MCSA_ELF_TypeTLS, llvm::MCSA_Global, llvm::MCSA_Hidden, llvm::MCSA_IndirectSymbol, llvm::MCSA_Internal, llvm::MCSA_Invalid, llvm::MCSA_LazyReference, llvm::MCSA_Local, llvm::MCSA_NoDeadStrip, llvm::MCSA_PrivateExtern, llvm::MCSA_Protected, llvm::MCSA_Reference, llvm::MCSA_SymbolResolver, llvm::MCSA_Weak, llvm::MCSA_WeakDefAutoPrivate, llvm::MCSA_WeakDefinition, llvm::MCSA_WeakReference, llvm::LCOMM::NoAlignment, llvm::MCSection::PrintSwitchToSection(), llvm::ARMBuildAttrs::Section, llvm::MCSymbol::setVariableValue(), StorageClass, and llvm::ARMBuildAttrs::Symbol.
Referenced by PrintQuotedString().