LLVM: MCModule.cpp File Reference
LLVM API Documentation
MCModule.cpp File Reference
#include "llvm/MC/MCModule.h"
#include "llvm/MC/MCAtom.h"
#include "llvm/MC/MCFunction.h"
#include <algorithm>
Functions
static bool AtomComp (const MCAtom *L, uint64_t Addr)
static bool AtomCompInv (uint64_t Addr, const MCAtom *R)
static bool CompBBToAtom (MCBasicBlock *BB, const MCTextAtom *Atom)
Function Documentation
static bool AtomComp (const MCAtom * L, uint64_t Addr) static
Definition at line 17 of file MCModule.cpp.
References llvm::MCAtom::getEndAddr().
Referenced by AtomCompInv(), llvm::MCModule::createDataAtom(), and llvm::MCModule::findAtomContaining().
static bool AtomCompInv (uint64_t Addr, const MCAtom * R) static
Definition at line 21 of file MCModule.cpp.
References llvm::MCModule::atom_begin(), llvm::MCModule::atom_end(), AtomComp(), llvm::MCAtom::Begin, llvm::MCAtom::End, llvm::MCAtom::getEndAddr(), and I.
Referenced by llvm::MCModule::findFirstAtomAfter().
static bool CompBBToAtom (MCBasicBlock * BB, const MCTextAtom * Atom) static
Definition at line 106 of file MCModule.cpp.
References BB, llvm::MCFunction::createBlock(), llvm::MCBasicBlock::getInsts(), llvm::MCBasicBlock::getParent(), I, llvm::MCBasicBlock::splitBasicBlock(), and llvm::X86II::TA.