LLVM: MCObjectDisassembler.cpp File Reference
LLVM API Documentation
MCObjectDisassembler.cpp File Reference
#include "llvm/MC/MCObjectDisassembler.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/MC/MCAtom.h"
#include "llvm/MC/MCDisassembler.h"
#include "llvm/MC/MCFunction.h"
#include "llvm/MC/MCInstrAnalysis.h"
#include "llvm/MC/MCModule.h"
#include "llvm/MC/MCObjectSymbolizer.h"
#include "llvm/Object/MachO.h"
#include "llvm/Object/ObjectFile.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/MachO.h"
#include "llvm/Support/MemoryObject.h"
#include "llvm/Support/StringRefMemoryObject.h"
#include "llvm/Support/raw_ostream.h"
#include <map>
Functions
static void RemoveDupsFromAddressVector (MCObjectDisassembler::AddressSetTy &V)
Function Documentation
static void RemoveDupsFromAddressVector (MCObjectDisassembler::AddressSetTy & V) static
Definition at line 176 of file MCObjectDisassembler.cpp.
References llvm::ARM_PROC::A, llvm::MCTextAtom::addInst(), llvm::MCBasicBlock::addPredecessor(), llvm::MCDecodedInst::Address, llvm::MCBasicBlock::addSuccessor(), llvm::MCModule::atom_begin(), llvm::MCModule::atom_end(), llvm::MCTextAtom::back(), BB, llvm::MCTextAtom::begin(), llvm::object::ObjectFile::begin_symbols(), llvm::c_str(), llvm::MCFunction::createBlock(), llvm::MCModule::createFunction(), llvm::MCModule::createTextAtom(), llvm::MCObjectDisassembler::Dis, llvm::dyn_cast(), llvm::StringRef::empty(), llvm::MCTextAtom::end(), llvm::object::ObjectFile::end_symbols(), llvm::MCInstrAnalysis::evaluateBranch(), llvm::MCFunction::find(), llvm::StringRef::find_last_of(), llvm::MCModule::findAtomContaining(), llvm::MCObjectSymbolizer::findExternalFunctionAt(), llvm::MCModule::findFirstAtomAfter(), llvm::MCModule::func_begin(), llvm::MCModule::func_end(), llvm::MemoryObject::getBase(), llvm::MCAtom::getBeginAddr(), llvm::MCObjectDisassembler::getEffectiveLoadAddr(), llvm::MCAtom::getEndAddr(), llvm::MemoryObject::getExtent(), llvm::MCDisassembler::getInstruction(), llvm::MCAtom::getName(), llvm::MCObjectDisassembler::getOriginalLoadAddr(), llvm::MCObjectDisassembler::getRegionFor(), llvm::ARM_PROC::IE, llvm::object::content_iterator< content_type >::increment(), llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::insert(), llvm::SetVector< T, Vector, Set >::insert(), llvm::MCDecodedInst::Inst, llvm::MCInstrAnalysis::isBranch(), llvm::MCInstrAnalysis::isCall(), llvm::MCInstrAnalysis::isConditionalBranch(), llvm::MCInstrAnalysis::isTerminator(), llvm_unreachable, llvm::MCObjectDisassembler::MIA, llvm::MCObjectDisassembler::MOS, llvm::nulls(), llvm::MCObjectDisassembler::Obj, llvm::MCAtom::setName(), llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::size(), llvm::MCDecodedInst::Size, llvm::MCTextAtom::split(), llvm::object::SymbolRef::ST_Function, llvm::StringRef::substr(), llvm::X86II::TA, llvm::utohexstr(), and llvm::utostr().