LLVM: MCObjectSymbolizer.cpp File Reference
LLVM API Documentation
MCObjectSymbolizer.cpp File Reference
#include "llvm/MC/MCObjectSymbolizer.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCRelocationInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Object/MachO.h"
#include "llvm/Object/ELFObjectFile.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
Functions
static bool SectionStartsBefore (const SectionRef &S, uint64_t Addr)
Function Documentation
static bool SectionStartsBefore (const SectionRef & S, uint64_t Addr) static
Definition at line 209 of file MCObjectSymbolizer.cpp.
References llvm::object::SectionRef::getAddress().
Referenced by llvm::MCObjectSymbolizer::findRelocationAt(), and llvm::MCObjectSymbolizer::findSectionContaining().