LLVM: MemorySanitizer.cpp File Reference
LLVM API Documentation
MemorySanitizer.cpp File Reference
#include "llvm/Transforms/Instrumentation.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Triple.h"
#include "llvm/ADT/ValueMap.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/MDBuilder.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/InstVisitor.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/ModuleUtils.h"
#include "llvm/Transforms/Utils/SpecialCaseList.h"
#include "llvm/IR/Intrinsics.gen"
Macros
#define DEBUG_TYPE "msan"
#define GET_INTRINSIC_MODREF_BEHAVIOR
#define ModRefBehavior IntrinsicKind
Functions
INITIALIZE_PASS (MemorySanitizer,"msan","MemorySanitizer: detects uninitialized reads.", false, false) FunctionPass *llvm
static GlobalVariable * createPrivateNonConstGlobalForString (Module &M, StringRef Str)
Create a non-const global initialized with the given string.
Variables
static const uint64_t kShadowMask32 = 1ULL << 31
static const uint64_t kShadowMask64 = 1ULL << 46
static const uint64_t kOriginOffset32 = 1ULL << 30
static const uint64_t kOriginOffset64 = 1ULL << 45
static const unsigned kMinOriginAlignment = 4
static const unsigned kShadowTLSAlignment = 8
static cl::opt< bool > ClTrackOrigins ("msan-track-origins", cl::desc("Track origins (allocation sites) of poisoned memory"), cl::Hidden, cl::init(false))
Track origins of uninitialized values.
static cl::opt< bool > ClKeepGoing ("msan-keep-going", cl::desc("keep going after reporting a UMR"), cl::Hidden, cl::init(false))
static cl::opt< bool > ClPoisonStack ("msan-poison-stack", cl::desc("poison uninitialized stack variables"), cl::Hidden, cl::init(true))
static cl::opt< bool > ClPoisonStackWithCall ("msan-poison-stack-with-call", cl::desc("poison uninitialized stack variables with a call"), cl::Hidden, cl::init(false))
static cl::opt< int > ClPoisonStackPattern ("msan-poison-stack-pattern", cl::desc("poison uninitialized stack variables with the given patter"), cl::Hidden, cl::init(0xff))
static cl::opt< bool > ClPoisonUndef ("msan-poison-undef", cl::desc("poison undef temps"), cl::Hidden, cl::init(true))
static cl::opt< bool > ClHandleICmp ("msan-handle-icmp", cl::desc("propagate shadow through ICmpEQ and ICmpNE"), cl::Hidden, cl::init(true))
static cl::opt< bool > ClHandleICmpExact ("msan-handle-icmp-exact", cl::desc("exact handling of relational integer ICmp"), cl::Hidden, cl::init(false))
static cl::opt< bool > ClStoreCleanOrigin ("msan-store-clean-origin", cl::desc("store origin for clean (fully initialized) values"), cl::Hidden, cl::init(false))
static cl::opt< bool > ClCheckAccessAddress ("msan-check-access-address", cl::desc("report accesses through a pointer which has poisoned shadow"), cl::Hidden, cl::init(true))
static cl::opt< bool > ClDumpStrictInstructions ("msan-dump-strict-instructions", cl::desc("print out instructions with default strict semantics"), cl::Hidden, cl::init(false))
static cl::opt< std::string > ClBlacklistFile ("msan-blacklist", cl::desc("File containing the list of functions where MemorySanitizer ""should not report bugs"), cl::Hidden)
static cl::opt< std::string > ClWrapIndirectCalls ("msan-wrap-indirect-calls", cl::desc("Wrap indirect calls with a given function"), cl::Hidden)
static cl::opt< bool > ClWrapIndirectCallsFast ("msan-wrap-indirect-calls-fast", cl::desc("Do not wrap indirect calls with target in the same module"), cl::Hidden, cl::init(true))
Detailed Description
This file is a part of MemorySanitizer, a detector of uninitialized reads.
Status: early prototype.
The algorithm of the tool is similar to Memcheck (http://goo.gl/QKbem). We associate a few shadow bits with every byte of the application memory, poison the shadow of the malloc-ed or alloca-ed memory, load the shadow bits on every memory read, propagate the shadow bits through some of the arithmetic instruction (including MOV), store the shadow bits on every memory write, report a bug on some other instructions (e.g. JMP) if the associated shadow is poisoned.
But there are differences too. The first and the major one: compiler instrumentation instead of binary instrumentation. This gives us much better register allocation, possible compiler optimizations and a fast start-up. But this brings the major issue as well: msan needs to see all program events, including system calls and reads/writes in system libraries, so we either need to compile everything with msan or use a binary translation component (e.g. DynamoRIO) to instrument pre-built libraries. Another difference from Memcheck is that we use 8 shadow bits per byte of application memory and use a direct shadow mapping. This greatly simplifies the instrumentation code and avoids races on shadow updates (Memcheck is single-threaded so races are not a concern there. Memcheck uses 2 shadow bits per byte with a slow path storage that uses 8 bits per byte).
The default value of shadow is 0, which means "clean" (not poisoned).
Every module initializer should call __msan_init to ensure that the shadow memory is ready. On error, __msan_warning is called. Since parameters and return values may be passed via registers, we have a specialized thread-local shadow for return values (__msan_retval_tls) and parameters (__msan_param_tls).
                      Origin tracking.
MemorySanitizer can track origins (allocation points) of all uninitialized values. This behavior is controlled with a flag (msan-track-origins) and is disabled by default.
Origins are 4-byte values created and interpreted by the runtime library. They are stored in a second shadow mapping, one 4-byte value for 4 bytes of application memory. Propagation of origins is basically a bunch of "select" instructions that pick the origin of a dirty argument, if an instruction has one.
Every 4 aligned, consecutive bytes of application memory have one origin value associated with them. If these bytes contain uninitialized data coming from 2 different allocations, the last store wins. Because of this, MemorySanitizer reports can show unrelated origins, but this is unlikely in practice.
Origins are meaningless for fully initialized values, so MemorySanitizer avoids storing origin to memory when a fully initialized value is stored. This way it avoids needless overwritting origin of the 4-byte region on a short (i.e. 1 byte) clean store, and it is also good for performance.
                       Atomic handling.
Ideally, every atomic store of application value should update the corresponding shadow location in an atomic way. Unfortunately, atomic store of two disjoint locations can not be done without severe slowdown.
Therefore, we implement an approximation that may err on the safe side. In this implementation, every atomically accessed location in the program may only change from (partially) uninitialized to fully initialized, but not the other way around. We load the shadow after the application load, and we store the shadow before the app store. Also, we always store clean shadow (if the application store is atomic). This way, if the store-load pair constitutes a happens-before arc, shadow store and load are correctly ordered such that the load will get either the value that was stored, or some later value (which is always clean).
This does not work very well with Compare-And-Swap (CAS) and Read-Modify-Write (RMW) operations. To follow the above logic, CAS and RMW must store the new shadow before the app operation, and load the shadow after the app operation. Computers don't work this way. Current implementation ignores the load aspect of CAS/RMW, always returning a clean value. It implements the store part as a simple atomic store by storing a clean shadow.
Definition in file MemorySanitizer.cpp.
Macro Definition Documentation
#define DEBUG_TYPE "msan"
Definition at line 96 of file MemorySanitizer.cpp.
#define GET_INTRINSIC_MODREF_BEHAVIOR
#define ModRefBehavior IntrinsicKind
Referenced by llvm::createBasicAliasAnalysisPass(), llvm::createGlobalsModRefPass(), isStructPathTBAA(), and notDifferentParent().
Function Documentation
static GlobalVariable* createPrivateNonConstGlobalForString (Module & M, StringRef Str) static
Create a non-const global initialized with the given string.
Creates a writable global for Str so that we can pass it to the run-time lib. Runtime uses first 4 bytes of the string to store the frame ID, so the string needs to be mutable.
Definition at line 305 of file MemorySanitizer.cpp.
References llvm::ARM_PROC::A, llvm::Acquire, llvm::AcquireRelease, llvm::AttrBuilder::addAttribute(), llvm::PHINode::addIncoming(), llvm::appendToGlobalCtors(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_begin(), llvm::Function::arg_begin(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_end(), llvm::Function::arg_end(), B, BB, llvm::XCoreISD::BL, llvm::Intrinsic::bswap, llvm::Attribute::ByVal, llvm::Call, ClCheckAccessAddress, ClDumpStrictInstructions, ClHandleICmp, ClHandleICmpExact, ClKeepGoing, ClPoisonStack, ClPoisonStackPattern, ClPoisonStackWithCall, ClPoisonUndef, ClStoreCleanOrigin, ClWrapIndirectCalls, ClWrapIndirectCallsFast, llvm::ValueMap< KeyT, ValueT, Config >::count(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateAdd(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateAlignedLoad(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateAlignedStore(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateAlloca(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateAnd(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateBinOp(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateBitCast(), llvm::MDBuilder::createBranchWeights(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateCall(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateCall2(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateCall3(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateCall4(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateConstGEP1_32(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateExtractElement(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateExtractValue(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmp(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmpEQ(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmpNE(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmpSLT(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmpUGE(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmpULT(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateInsertElement(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateInsertValue(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateIntCast(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateIntToPtr(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateLoad(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateLShr(), llvm::IRBuilderBase::CreateMemCpy(), llvm::IRBuilderBase::CreateMemSet(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateNot(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateOr(), llvm::SpecialCaseList::createOrDie(), llvm::IRBuilder< preserveNames, T, Inserter >::CreatePHI(), llvm::IRBuilder< preserveNames, T, Inserter >::CreatePointerCast(), llvm::IRBuilder< preserveNames, T, Inserter >::CreatePtrToInt(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateSelect(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateSExt(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateShl(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateStore(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateTrunc(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateXor(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateZExt(), llvm::dbgs(), llvm::X86II::DE, DEBUG, llvm::df_begin(), llvm::df_end(), llvm::dumpInst(), llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::Instruction::eraseFromParent(), llvm::errs(), llvm::GlobalValue::ExternalLinkage, F(), llvm::IntegerType::get(), llvm::InlineAsm::get(), llvm::ConstantInt::get(), llvm::FunctionType::get(), llvm::StructType::get(), llvm::ArrayType::get(), llvm::VectorType::get(), llvm::ConstantStruct::get(), llvm::PointerType::get(), llvm::ExtractValueInst::getAggregateOperand(), llvm::InsertValueInst::getAggregateOperand(), llvm::AllocaInst::getAlignment(), llvm::LoadInst::getAlignment(), llvm::StoreInst::getAlignment(), llvm::AllocaInst::getAllocatedType(), llvm::Constant::getAllOnesValue(), llvm::CallInst::getArgOperand(), llvm::Function::getAttributes(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledFunction(), llvm::CallInst::getCalledFunction(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledValue(), llvm::SelectInst::getCondition(), llvm::Type::getContainedType(), llvm::Function::getContext(), llvm::Module::getContext(), llvm::Instruction::getDebugLoc(), llvm::Intrinsic::getDeclaration(), llvm::StructType::getElementType(), llvm::Function::getEntryBlock(), llvm::SelectInst::getFalseValue(), llvm::BasicBlock::getFirstInsertionPt(), llvm::BasicBlock::getFirstNonPHI(), llvm::PHINode::getIncomingBlock(), llvm::ExtractValueInst::getIndices(), llvm::InsertValueInst::getIndices(), llvm::InsertValueInst::getInsertedValueOperand(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getInstruction(), llvm::IRBuilderBase::getInt32(), llvm::IRBuilderBase::getInt32Ty(), llvm::Type::getInt64PtrTy(), llvm::IRBuilderBase::getInt64Ty(), llvm::IRBuilderBase::getInt8(), llvm::IRBuilderBase::getInt8PtrTy(), llvm::Type::getInt8PtrTy(), llvm::IRBuilderBase::getInt8Ty(), llvm::Type::getInt8Ty(), llvm::Type::getIntNTy(), llvm::IRBuilderBase::getIntPtrTy(), llvm::IntrinsicInst::getIntrinsicID(), llvm::Value::getName(), llvm::ilist_node< NodeTy >::getNextNode(), llvm::Constant::getNullValue(), llvm::CallInst::getNumArgOperands(), llvm::StructType::getNumElements(), llvm::PHINode::getNumIncomingValues(), llvm::User::getNumOperands(), llvm::BinaryOperator::getOpcode(), llvm::Instruction::getOpcodeName(), llvm::User::getOperand(), llvm::LoadInst::getOrdering(), llvm::StoreInst::getOrdering(), llvm::AtomicCmpXchgInst::getOrdering(), llvm::AtomicRMWInst::getOrdering(), llvm::Module::getOrInsertFunction(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getParamAlignment(), llvm::Instruction::getParent(), llvm::GlobalValue::getParent(), getParent(), llvm::Type::getPointerElementType(), llvm::LoadInst::getPointerOperand(), llvm::StoreInst::getPointerOperand(), llvm::CmpInst::getPredicate(), llvm::Type::getPrimitiveSizeInBits(), llvm::ReturnInst::getReturnValue(), llvm::Type::getScalarSizeInBits(), llvm::Type::getScalarType(), llvm::BasicBlock::getSinglePredecessor(), llvm::ConstantDataArray::getString(), llvm::Module::getTargetTriple(), llvm::SelectInst::getTrueValue(), llvm::Value::getType(), llvm::PointerType::getUnqual(), llvm::StoreInst::getValueOperand(), llvm::Type::getVectorElementType(), llvm::Type::getVectorNumElements(), llvm::IRBuilderBase::getVoidTy(), llvm::AttributeSet::hasAttribute(), llvm::GlobalValue::HiddenVisibility, i, I, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::GlobalVariable::InitialExecTLSModel, llvm::Type::isAggregateType(), llvm::LoadInst::isAtomic(), llvm::StoreInst::isAtomic(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isCall(), llvm::ICmpInst::isEquality(), llvm::Type::isFPOrFPVectorTy(), llvm::CallInst::isInlineAsm(), llvm::Type::isIntegerTy(), llvm::Type::isIntOrIntVectorTy(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isInvoke(), llvm::Constant::isNullValue(), llvm::Type::isPointerTy(), llvm::ICmpInst::isRelational(), llvm::CmpInst::isSigned(), llvm::Type::isSized(), llvm::CallInst::isTailCall(), llvm::CmpInst::isUnsigned(), llvm::FunctionType::isVarArg(), llvm::Type::isVectorTy(), llvm::Type::isVoidTy(), llvm::Type::isX86_MMXTy(), IT, kMinOriginAlignment, kOriginOffset32, kOriginOffset64, kShadowMask32, kShadowMask64, kShadowTLSAlignment, llvm_unreachable, M, llvm::Monotonic, n, llvm::NotAtomic, llvm::SystemZISD::OC, llvm::User::op_begin(), llvm::User::op_end(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::paramHasAttr(), llvm::GlobalValue::PrivateLinkage, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::Attribute::ReadNone, llvm::Attribute::ReadOnly, llvm::Release, llvm::Function::removeAttributes(), llvm::removeUnreachableBlocks(), llvm::report_fatal_error(), llvm::DataLayout::RoundUpAlignment(), S, llvm::Attribute::SanitizeMemory, llvm::PPCISD::SC, llvm::SequentiallyConsistent, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::setCalledFunction(), llvm::Instruction::setDebugLoc(), llvm::IRBuilderBase::SetInsertPoint(), llvm::Value::setName(), llvm::LoadInst::setOrdering(), llvm::StoreInst::setOrdering(), llvm::AtomicCmpXchgInst::setOrdering(), llvm::AtomicRMWInst::setOrdering(), llvm::CallInst::setTailCall(), llvm::GlobalValue::setVisibility(), Shift, llvm::NVPTX::PTXLdStInstCode::Signed, llvm::SmallVectorTemplateCommon< T >::size(), llvm::SplitBlockAndInsertIfThen(), llvm::A64DB::ST, llvm::SPII::Store, llvm::raw_svector_ostream::str(), llvm::Unordered, llvm::NVPTX::PTXLdStInstCode::V2, llvm::GlobalValue::WeakODRLinkage, llvm::Triple::x86_64, llvm::Intrinsic::x86_avx512_cvtsd2usi, llvm::Intrinsic::x86_avx512_cvtsd2usi64, llvm::Intrinsic::x86_avx512_cvtss2usi, llvm::Intrinsic::x86_avx512_cvtss2usi64, llvm::Intrinsic::x86_avx512_cvttsd2usi, llvm::Intrinsic::x86_avx512_cvttsd2usi64, llvm::Intrinsic::x86_avx512_cvttss2usi, llvm::Intrinsic::x86_avx512_cvttss2usi64, llvm::Intrinsic::x86_avx512_cvtusi2sd, llvm::Intrinsic::x86_avx512_cvtusi2ss, llvm::Intrinsic::x86_avx512_cvtusi642sd, llvm::Intrinsic::x86_avx512_cvtusi642ss, llvm::Intrinsic::x86_sse2_cvtdq2pd, llvm::Intrinsic::x86_sse2_cvtps2pd, llvm::Intrinsic::x86_sse2_cvtsd2si, llvm::Intrinsic::x86_sse2_cvtsd2si64, llvm::Intrinsic::x86_sse2_cvtsd2ss, llvm::Intrinsic::x86_sse2_cvtsi2sd, llvm::Intrinsic::x86_sse2_cvtsi642sd, llvm::Intrinsic::x86_sse2_cvtss2sd, llvm::Intrinsic::x86_sse2_cvttsd2si, llvm::Intrinsic::x86_sse2_cvttsd2si64, llvm::Intrinsic::x86_sse_cvtps2pi, llvm::Intrinsic::x86_sse_cvtsi2ss, llvm::Intrinsic::x86_sse_cvtsi642ss, llvm::Intrinsic::x86_sse_cvtss2si, llvm::Intrinsic::x86_sse_cvtss2si64, llvm::Intrinsic::x86_sse_cvttps2pi, llvm::Intrinsic::x86_sse_cvttss2si, and llvm::Intrinsic::x86_sse_cvttss2si64.
INITIALIZE_PASS (MemorySanitizer , "msan" , "MemorySanitizer: detects uninitialized reads." , false , false)
Definition at line 291 of file MemorySanitizer.cpp.
Variable Documentation
cl::opt<std::string> ClBlacklistFile("msan-blacklist", cl::desc("File containing the list of functions where MemorySanitizer ""should not report bugs"), cl::Hidden) static
cl::opt<bool> ClCheckAccessAddress("msan-check-access-address", cl::desc("report accesses through a pointer which has poisoned shadow"), cl::Hidden, cl::init(true)) static
Referenced by createPrivateNonConstGlobalForString().
cl::opt<bool> ClDumpStrictInstructions("msan-dump-strict-instructions", cl::desc("print out instructions with default strict semantics"), cl::Hidden, cl::init(false)) static
Referenced by createPrivateNonConstGlobalForString().
cl::opt<bool> ClHandleICmp("msan-handle-icmp", cl::desc("propagate shadow through ICmpEQ and ICmpNE"), cl::Hidden, cl::init(true)) static
Referenced by createPrivateNonConstGlobalForString().
cl::opt<bool> ClHandleICmpExact("msan-handle-icmp-exact", cl::desc("exact handling of relational integer ICmp"), cl::Hidden, cl::init(false)) static
Referenced by createPrivateNonConstGlobalForString().
cl::opt<bool> ClKeepGoing("msan-keep-going", cl::desc("keep going after reporting a UMR"), cl::Hidden, cl::init(false)) static
Referenced by createPrivateNonConstGlobalForString().
cl::opt<bool> ClPoisonStack("msan-poison-stack", cl::desc("poison uninitialized stack variables"), cl::Hidden, cl::init(true)) static
Referenced by createPrivateNonConstGlobalForString().
cl::opt<int> ClPoisonStackPattern("msan-poison-stack-pattern", cl::desc("poison uninitialized stack variables with the given patter"), cl::Hidden, cl::init(0xff)) static
Referenced by createPrivateNonConstGlobalForString().
cl::opt<bool> ClPoisonStackWithCall("msan-poison-stack-with-call", cl::desc("poison uninitialized stack variables with a call"), cl::Hidden, cl::init(false)) static
Referenced by createPrivateNonConstGlobalForString().
cl::opt<bool> ClPoisonUndef("msan-poison-undef", cl::desc("poison undef temps"), cl::Hidden, cl::init(true)) static
Referenced by createPrivateNonConstGlobalForString().
cl::opt<bool> ClStoreCleanOrigin("msan-store-clean-origin", cl::desc("store origin for clean (fully initialized) values"), cl::Hidden, cl::init(false)) static
Referenced by createPrivateNonConstGlobalForString().
cl::opt<bool> ClTrackOrigins("msan-track-origins", cl::desc("Track origins (allocation sites) of poisoned memory"), cl::Hidden, cl::init(false)) static
Track origins of uninitialized values.
Adds a section to MemorySanitizer report that points to the allocation (stack or heap) the uninitialized bits came from originally.
cl::opt<std::string> ClWrapIndirectCalls("msan-wrap-indirect-calls", cl::desc("Wrap indirect calls with a given function"), cl::Hidden) static
Referenced by createPrivateNonConstGlobalForString().
cl::opt<bool> ClWrapIndirectCallsFast("msan-wrap-indirect-calls-fast", cl::desc("Do not wrap indirect calls with target in the same module"), cl::Hidden, cl::init(true)) static
Referenced by createPrivateNonConstGlobalForString().
const unsigned kMinOriginAlignment = 4 static
Definition at line 129 of file MemorySanitizer.cpp.
Referenced by createPrivateNonConstGlobalForString().
const uint64_t kOriginOffset32 = 1ULL << 30 static
Definition at line 127 of file MemorySanitizer.cpp.
Referenced by createPrivateNonConstGlobalForString().
const uint64_t kOriginOffset64 = 1ULL << 45 static
Definition at line 128 of file MemorySanitizer.cpp.
Referenced by createPrivateNonConstGlobalForString().
const uint64_t kShadowMask32 = 1ULL << 31 static
Definition at line 125 of file MemorySanitizer.cpp.
Referenced by createPrivateNonConstGlobalForString().
const uint64_t kShadowMask64 = 1ULL << 46 static
Definition at line 126 of file MemorySanitizer.cpp.
Referenced by createPrivateNonConstGlobalForString().
const unsigned kShadowTLSAlignment = 8 static
Definition at line 130 of file MemorySanitizer.cpp.
Referenced by createPrivateNonConstGlobalForString().