LLVM: Metadata.cpp File Reference
LLVM API Documentation
Metadata.cpp File Reference
#include "llvm/IR/Metadata.h"
#include "LLVMContextImpl.h"
#include "SymbolTableListTraitsImpl.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/IR/Instruction.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/ConstantRange.h"
#include "llvm/Support/LeakDetector.h"
#include "llvm/Support/ValueHandle.h"
Classes
class llvm::MDNodeOperand
Namespaces
llvm
List of target independent CodeGen pass IDs.
Functions
static MDNodeOperand * getOperandPtr (MDNode *N, unsigned Op)
static const Function * getFunctionForValue (Value *V)
static const Function * assertLocalFunction (const MDNode *N)
static bool isFunctionLocalValue (Value *V)
static bool isContiguous (const ConstantRange &A, const ConstantRange &B)
static bool canBeMerged (const ConstantRange &A, const ConstantRange &B)
static bool tryMergeRange (SmallVectorImpl< Value * > &EndPoints, ConstantInt *Low, ConstantInt *High)
static void addRange (SmallVectorImpl< Value * > &EndPoints, ConstantInt *Low, ConstantInt *High)
static SmallVector< TrackingVH< MDNode >, 4 > & getNMDOps (void *Operands)
Function Documentation
static void addRange (SmallVectorImpl< Value * > & EndPoints, ConstantInt * Low, ConstantInt * High) static
Definition at line 444 of file Metadata.cpp.
References llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), and tryMergeRange().
Referenced by llvm::MDNode::getMostGenericRange(), and IsPointerOffset().
static const Function* assertLocalFunction (const MDNode * N) static
Definition at line 165 of file Metadata.cpp.
References F(), getFunctionForValue(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), i, and llvm::MDNode::isFunctionLocal().
Referenced by llvm::MDNode::getFunction().
static bool canBeMerged (const ConstantRange & A, const ConstantRange & B) static
Definition at line 423 of file Metadata.cpp.
References llvm::ConstantRange::intersectWith(), isContiguous(), and llvm::ConstantRange::isEmptySet().
Referenced by tryMergeRange().
static const Function* getFunctionForValue (Value * V) static
Definition at line 149 of file Metadata.cpp.
References llvm::ARM_PROC::A, BB, llvm::BasicBlock::getParent(), and I.
Referenced by assertLocalFunction(), llvm::MDNode::getFunction(), and llvm::MDNode::Profile().
static SmallVector<TrackingVH<MDNode>, 4>& getNMDOps (void * Operands) static
Definition at line 525 of file Metadata.cpp.
References N, and llvm::Twine::str().
Referenced by llvm::NamedMDNode::addOperand(), llvm::NamedMDNode::dropAllReferences(), llvm::NamedMDNode::getNumOperands(), llvm::NamedMDNode::getOperand(), and llvm::NamedMDNode::~NamedMDNode().
static MDNodeOperand* getOperandPtr (MDNode * N, unsigned Op) static
getOperandPtr - Helper function to get the MDNodeOperand's coallocated on the end of the MDNode.
Definition at line 102 of file Metadata.cpp.
Referenced by llvm::MDNode::getOperand(), and llvm::MDNode::replaceOperandWith().
static bool isContiguous (const ConstantRange & A, const ConstantRange & B) static
Definition at line 419 of file Metadata.cpp.
References llvm::ConstantRange::getLower(), and llvm::ConstantRange::getUpper().
Referenced by canBeMerged().
static bool isFunctionLocalValue (Value * V) static
isFunctionLocalValue - Return true if this is a value that would require a function-local MDNode.
Definition at line 212 of file Metadata.cpp.
References llvm::FoldingSetNodeID::AddPointer(), llvm::FoldingSetNodeID::ComputeHash(), i, llvm::LibFunc::malloc, llvm::LLVMContextImpl::MDNodeSet, N, llvm::LLVMContext::pImpl, and llvm::ArrayRef< T >::size().
Referenced by llvm::MDNode::Profile().
static bool tryMergeRange (SmallVectorImpl< Value * > & EndPoints, ConstantInt * Low, ConstantInt * High) static
Definition at line 427 of file Metadata.cpp.
References canBeMerged(), llvm::ConstantInt::get(), llvm::ConstantRange::getLower(), llvm::ConstantInt::getType(), llvm::ConstantRange::getUpper(), llvm::ConstantInt::getValue(), llvm::A64CC::LE, llvm::SmallVectorTemplateCommon< T >::size(), and llvm::ConstantRange::unionWith().
Referenced by addRange(), and llvm::MDNode::getMostGenericRange().