LLVM: MipsSERegisterInfo.cpp File Reference
LLVM API Documentation
MipsSERegisterInfo.cpp File Reference
#include "MipsSERegisterInfo.h"
#include "Mips.h"
#include "MipsAnalyzeImmediate.h"
#include "MipsMachineFunction.h"
#include "MipsSEInstrInfo.h"
#include "MipsSubtarget.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/DebugInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetFrameLowering.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
Functions
static bool isMSALoadOrStore (const unsigned Opcode)
Function Documentation
static bool isMSALoadOrStore (const unsigned Opcode) inline static
Determine whether a given opcode is an MSA load/store (supporting 10-bit offsets) or a non-MSA load/store (supporting 16-bit offsets).
Definition at line 67 of file MipsSERegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::MachineRegisterInfo::createVirtualRegister(), DEBUG, llvm::errs(), llvm::ISD::FrameIndex, llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), llvm::MipsRegisterInfo::getFrameRegister(), llvm::MachineOperand::getImm(), llvm::MachineFunction::getInfo(), llvm::TargetMachine::getInstrInfo(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getTarget(), llvm::MipsSubtarget::isABI_N64(), llvm::MachineInstr::isDebugValue(), llvm::MipsFunctionInfo::isEhDataRegFI(), llvm::isInt< 16 >(), llvm::RegState::Kill, llvm::MipsSEInstrInfo::loadImmediate(), llvm::A64CC::MI, llvm::MipsRegisterInfo::Subtarget, and TII.