LLVM: MipsAsmBackend.cpp File Reference
LLVM API Documentation
MipsAsmBackend.cpp File Reference
#include "MipsFixupKinds.h"
#include "MCTargetDesc/MipsMCTargetDesc.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCDirectives.h"
#include "llvm/MC/MCELFObjectWriter.h"
#include "llvm/MC/MCFixupKindInfo.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
Functions
static unsigned adjustFixupValue (unsigned Kind, uint64_t Value)
Function Documentation
static unsigned adjustFixupValue (unsigned Kind, uint64_t Value) static
Definition at line 30 of file MipsAsmBackend.cpp.
References llvm::createMipsELFObjectWriter(), llvm::X86II::DF, llvm::FirstTargetFixupKind, llvm::Mips::fixup_MICROMIPS_26_S1, llvm::Mips::fixup_MICROMIPS_GOT_DISP, llvm::Mips::fixup_MICROMIPS_GOT_OFST, llvm::Mips::fixup_MICROMIPS_GOT_PAGE, llvm::Mips::fixup_MICROMIPS_HI16, llvm::Mips::fixup_MICROMIPS_LO16, llvm::Mips::fixup_MICROMIPS_PC16_S1, llvm::Mips::fixup_Mips_16, llvm::Mips::fixup_Mips_26, llvm::Mips::fixup_Mips_64, llvm::Mips::fixup_Mips_CALL_HI16, llvm::Mips::fixup_Mips_CALL_LO16, llvm::Mips::fixup_Mips_GOT_DISP, llvm::Mips::fixup_Mips_GOT_HI16, llvm::Mips::fixup_Mips_GOT_LO16, llvm::Mips::fixup_Mips_GOT_Local, llvm::Mips::fixup_Mips_GOT_OFST, llvm::Mips::fixup_Mips_GOT_PAGE, llvm::Mips::fixup_Mips_GPOFF_HI, llvm::Mips::fixup_Mips_GPOFF_LO, llvm::Mips::fixup_Mips_GPREL16, llvm::Mips::fixup_Mips_HI16, llvm::Mips::fixup_Mips_HIGHER, llvm::Mips::fixup_Mips_HIGHEST, llvm::Mips::fixup_Mips_LO16, llvm::Mips::fixup_Mips_PC16, llvm::FK_Data_4, llvm::FK_Data_8, llvm::FK_GPRel_4, llvm::MCFixupKindInfo::FKF_IsPCRel, llvm::MCAsmBackend::getFixupKindInfo(), llvm::MCFixup::getKind(), llvm::MCFixup::getOffset(), llvm::MCELFObjectTargetWriter::getOSABI(), i, llvm::Mips::NumTargetFixupKinds, and llvm::MCObjectWriter::Write32().