LLVM: MipsLongBranch.cpp File Reference
LLVM API Documentation
MipsLongBranch.cpp File Reference
#include "Mips.h"
#include "MCTargetDesc/MipsBaseInfo.h"
#include "MipsTargetMachine.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetRegisterInfo.h"
Macros
#define DEBUG_TYPE "mips-long-branch"
Functions
STATISTIC (LongBranches,"Number of long branches.")
static MachineBasicBlock * getTargetMBB (const MachineInstr &Br)
static ReverseIter getNonDebugInstr (ReverseIter B, ReverseIter E)
static void emitGPDisp (MachineFunction &F, const MipsInstrInfo *TII)
Variables
static cl::opt< bool > SkipLongBranch ("skip-mips-long-branch", cl::init(false), cl::desc("MIPS: Skip long branch pass."), cl::Hidden)
static cl::opt< bool > ForceLongBranch ("force-mips-long-branch", cl::init(false), cl::desc("MIPS: Expand all branches to long format."), cl::Hidden)
Macro Definition Documentation
#define DEBUG_TYPE "mips-long-branch"
Definition at line 19 of file MipsLongBranch.cpp.
Function Documentation
static void emitGPDisp (MachineFunction & F, const MipsInstrInfo * TII) static
Definition at line 400 of file MipsLongBranch.cpp.
References llvm::MachineInstrBuilder::addExternalSymbol(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), F(), llvm::MachineBasicBlock::findDebugLoc(), ForceLongBranch, llvm::MachineFunction::front(), llvm::MachineFunction::getInfo(), I, llvm::MipsSubtarget::inMips16Mode(), llvm::MipsSubtarget::isABI_O32(), llvm::isInt< 16 >(), llvm::MipsII::MO_ABS_HI, llvm::MipsII::MO_ABS_LO, llvm::Reloc::PIC_, llvm::MachineBasicBlock::removeLiveIn(), SkipLongBranch, TII, and llvm::SystemZISD::TM.
static ReverseIter getNonDebugInstr (ReverseIter B, ReverseIter E) static
Definition at line 119 of file MipsLongBranch.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), llvm::sys::path::append(), llvm::MIBundleBuilder::append(), B, base, BB, llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineOperand::CreateMBB(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::getBasicBlock(), llvm::MipsInstrInfo::GetInstSizeInBytes(), llvm::MachineBasicBlock::getNumber(), llvm::MipsInstrInfo::getOppositeBranchOpc(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), getTargetMBB(), llvm::HexagonISD::Hi, I, llvm::MachineBasicBlock::insert(), llvm::MachineBasicBlock::instr_begin(), llvm::MachineBasicBlock::instr_end(), llvm::MachineOperand::isMBB(), llvm::MachineOperand::isReg(), llvm::A64DB::LD, llvm::HexagonISD::Lo, llvm::A64CC::MI, N, llvm::MipsSubtarget::N64, llvm::next(), llvm::Reloc::PIC_, llvm::MachineBasicBlock::rbegin(), llvm::MachineBasicBlock::removeSuccessor(), llvm::MachineBasicBlock::rend(), llvm::MachineBasicBlock::size(), TII, and llvm::SystemZISD::TM.
static MachineBasicBlock* getTargetMBB (const MachineInstr & Br) static
Iterate over list of Br's operands and search for a MachineBasicBlock operand.
Definition at line 105 of file MipsLongBranch.cpp.
References llvm::MachineInstr::getDesc(), llvm::MachineOperand::getMBB(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getOperand(), I, and llvm::MachineOperand::isMBB().
Referenced by getNonDebugInstr().
STATISTIC (LongBranches , "Number of long branches.")
Variable Documentation
cl::opt<bool> ForceLongBranch("force-mips-long-branch", cl::init(false), cl::desc("MIPS: Expand all branches to long format."), cl::Hidden) static
Referenced by emitGPDisp().
cl::opt<bool> SkipLongBranch("skip-mips-long-branch", cl::init(false), cl::desc("MIPS: Skip long branch pass."), cl::Hidden) static
Referenced by emitGPDisp().