LLVM: MipsInstPrinter.cpp File Reference
LLVM API Documentation
MipsInstPrinter.cpp File Reference
#include "MipsInstPrinter.h"
#include "MipsInstrInfo.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "MipsGenAsmWriter.inc"
Macros
#define DEBUG_TYPE "asm-printer"
#define PRINT_ALIAS_INSTR
Functions
template<unsigned R>
static bool isReg (const MCInst &MI, unsigned OpNo)
static void printExpr (const MCExpr *Expr, raw_ostream &OS)
Macro Definition Documentation
#define DEBUG_TYPE "asm-printer"
Definition at line 14 of file MipsInstPrinter.cpp.
#define PRINT_ALIAS_INSTR
Definition at line 26 of file MipsInstPrinter.cpp.
Function Documentation
template<unsigned R> static bool isReg (const MCInst & MI, unsigned OpNo) static
Definition at line 30 of file MipsInstPrinter.cpp.
References llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), and llvm::MCOperand::isReg().
Referenced by llvm::MipsInstrInfo::AnalyzeBranch(), doesIgnoreDataTypeSuffix(), EvaluateAsPCRel(), getDRegFromQReg(), isImmSExti64i32Value(), llvm::PatchPointOpers::PatchPointOpers(), and llvm::HexagonInstrInfo::PredicateInstruction().
static void printExpr (const MCExpr * Expr, raw_ostream & OS) static
Definition at line 102 of file MipsInstPrinter.cpp.
References llvm::dyn_cast(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCSymbolRefExpr::getKind(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm_unreachable, llvm::A64CC::MI, llvm::Mips::MipsFCCToString(), OR, llvm::MipsInstPrinter::printRegName(), llvm::MCSymbolRefExpr::VK_Mips_ABS_HI, llvm::MCSymbolRefExpr::VK_Mips_ABS_LO, llvm::MCSymbolRefExpr::VK_Mips_CALL_HI16, llvm::MCSymbolRefExpr::VK_Mips_CALL_LO16, llvm::MCSymbolRefExpr::VK_Mips_DTPREL_HI, llvm::MCSymbolRefExpr::VK_Mips_DTPREL_LO, llvm::MCSymbolRefExpr::VK_Mips_GOT, llvm::MCSymbolRefExpr::VK_Mips_GOT16, llvm::MCSymbolRefExpr::VK_Mips_GOT_CALL, llvm::MCSymbolRefExpr::VK_Mips_GOT_DISP, llvm::MCSymbolRefExpr::VK_Mips_GOT_HI16, llvm::MCSymbolRefExpr::VK_Mips_GOT_LO16, llvm::MCSymbolRefExpr::VK_Mips_GOT_OFST, llvm::MCSymbolRefExpr::VK_Mips_GOT_PAGE, llvm::MCSymbolRefExpr::VK_Mips_GOTTPREL, llvm::MCSymbolRefExpr::VK_Mips_GPOFF_HI, llvm::MCSymbolRefExpr::VK_Mips_GPOFF_LO, llvm::MCSymbolRefExpr::VK_Mips_GPREL, llvm::MCSymbolRefExpr::VK_Mips_HIGHER, llvm::MCSymbolRefExpr::VK_Mips_HIGHEST, llvm::MCSymbolRefExpr::VK_Mips_TLSGD, llvm::MCSymbolRefExpr::VK_Mips_TLSLDM, llvm::MCSymbolRefExpr::VK_Mips_TPREL_HI, llvm::MCSymbolRefExpr::VK_Mips_TPREL_LO, and llvm::MCSymbolRefExpr::VK_None.