LLVM: MipsJITInfo.cpp File Reference
LLVM API Documentation
MipsJITInfo.cpp File Reference
#include "MipsJITInfo.h"
#include "MipsInstrInfo.h"
#include "MipsRelocations.h"
#include "MipsSubtarget.h"
#include "llvm/CodeGen/JITCodeEmitter.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Memory.h"
#include "llvm/Support/raw_ostream.h"
#include <cstdlib>
Macros
#define DEBUG_TYPE "jit"
#define __USER_LABEL_PREFIX__
#define GETASMPREFIX2(X) #X
#define GETASMPREFIX(X) GETASMPREFIX2(X)
#define ASMPREFIX GETASMPREFIX(__USER_LABEL_PREFIX__)
Functions
void MipsCompilationCallback ()
void MipsCompilationCallbackC (intptr_t StubAddr)
Variables
static TargetJITInfo::JITCompilerFn JITCompilerFunction
Macro Definition Documentation
#define __USER_LABEL_PREFIX__
Definition at line 84 of file MipsJITInfo.cpp.
#define ASMPREFIX GETASMPREFIX(__USER_LABEL_PREFIX__)
Definition at line 88 of file MipsJITInfo.cpp.
#define DEBUG_TYPE "jit"
Definition at line 14 of file MipsJITInfo.cpp.
#define GETASMPREFIX (X) GETASMPREFIX2(X)
Definition at line 87 of file MipsJITInfo.cpp.
#define GETASMPREFIX2 (X) #X
Definition at line 86 of file MipsJITInfo.cpp.
Function Documentation
void MipsCompilationCallback ()
Definition at line 153 of file MipsJITInfo.cpp.
References llvm_unreachable.
Referenced by llvm::MipsJITInfo::emitFunctionStub(), and llvm::MipsJITInfo::getLazyResolverFunction().
void MipsCompilationCallbackC (intptr_t StubAddr)
MipsCompilationCallbackC - This is the target-specific function invoked by the function stub when we did not know the real target of a call. This function must locate the start of the stub or call site and pass it into the JIT compiler function.
Definition at line 164 of file MipsJITInfo.cpp.
References llvm::HexagonISD::Hi, int, llvm::sys::Memory::InvalidateInstructionCache(), JITCompilerFunction, and llvm::HexagonISD::Lo.
Variable Documentation
TargetJITInfo::JITCompilerFn JITCompilerFunction static
JITCompilerFunction - This contains the address of the JIT function used to compile a function lazily.
Definition at line 80 of file MipsJITInfo.cpp.
Referenced by llvm::MipsJITInfo::getLazyResolverFunction(), and MipsCompilationCallbackC().