LLVM: MipsELFObjectWriter.cpp File Reference
LLVM API Documentation
MipsELFObjectWriter.cpp File Reference
#include "MCTargetDesc/MipsBaseInfo.h"
#include "MCTargetDesc/MipsFixupKinds.h"
#include "MCTargetDesc/MipsMCTargetDesc.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCELFObjectWriter.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/ErrorHandling.h"
#include <list>
Functions
static bool NeedsMatchingLo (const MCAssembler &Asm, const RelEntry &R)
static bool HasMatchingLo (const MCAssembler &Asm, RelLsIter I, RelLsIter Last)
static bool HasSameSymbol (const RelEntry &R0, const RelEntry &R1)
static int CompareOffset (const RelEntry &R0, const RelEntry &R1)
Function Documentation
static int CompareOffset (const RelEntry & R0, const RelEntry & R1) static
Definition at line 254 of file MipsELFObjectWriter.cpp.
References llvm::MCAssembler::end(), HasMatchingLo(), HasSameSymbol(), I, llvm::MipsGetSymAndOffset(), NeedsMatchingLo(), P, and llvm::ELF::R_MIPS_LO16.
static bool HasMatchingLo (const MCAssembler & Asm, RelLsIter I, RelLsIter Last) static
Definition at line 240 of file MipsELFObjectWriter.cpp.
References llvm::HexagonISD::Hi, and llvm::ELF::R_MIPS_LO16.
Referenced by CompareOffset().
static bool HasSameSymbol (const RelEntry & R0, const RelEntry & R1) static
Definition at line 250 of file MipsELFObjectWriter.cpp.
Referenced by CompareOffset().
static bool NeedsMatchingLo (const MCAssembler & Asm, const RelEntry & R) static
Definition at line 230 of file MipsELFObjectWriter.cpp.
References llvm::MCAssembler::getSymbolData(), llvm::MCSymbolData::isExternal(), llvm::ELF::R_MIPS_GOT16, and llvm::ELF::R_MIPS_HI16.
Referenced by CompareOffset().