LLVM: MipsAsmPrinter.cpp File Reference
LLVM API Documentation
MipsAsmPrinter.cpp File Reference
#include "InstPrinter/MipsInstPrinter.h"
#include "MCTargetDesc/MipsBaseInfo.h"
#include "Mips.h"
#include "MipsAsmPrinter.h"
#include "MipsInstrInfo.h"
#include "MipsMCInstLower.h"
#include "MipsTargetStreamer.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/Twine.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/IR/BasicBlock.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/Instructions.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCELFStreamer.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/ELF.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/Mangler.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetOptions.h"
#include "MipsGenMCPseudoLowering.inc"
Macros
#define DEBUG_TYPE "mips-asm-printer"
Functions
static void emitELFHeaderFlagsCG (MipsTargetStreamer &TargetStreamer, const MipsSubtarget &Subtarget)
void LLVMInitializeMipsAsmPrinter ()
Macro Definition Documentation
#define DEBUG_TYPE "mips-asm-printer"
Definition at line 15 of file MipsAsmPrinter.cpp.
Function Documentation
static void emitELFHeaderFlagsCG (MipsTargetStreamer & TargetStreamer, const MipsSubtarget & Subtarget) static
Definition at line 647 of file MipsAsmPrinter.cpp.
References llvm::Reloc::Default, llvm::MipsTargetStreamer::emitMipsHackELFFlags(), llvm::MipsSubtarget::getRelocationModel(), llvm::MipsSubtarget::hasMips32r2(), llvm::MipsSubtarget::hasMips64(), llvm::MipsSubtarget::hasMips64r2(), llvm::MipsSubtarget::inMicroMipsMode(), llvm::MipsSubtarget::inMips16Mode(), llvm::MipsSubtarget::isABI_O32(), llvm_unreachable, llvm::Reloc::PIC_, llvm::NVPTX::PTXCvtMode::RM, and llvm::Reloc::Static.
Referenced by llvm::MipsAsmPrinter::EmitEndOfAsmFile().
void LLVMInitializeMipsAsmPrinter ()
Definition at line 703 of file MipsAsmPrinter.cpp.
References llvm::ARM_PROC::A, B, llvm::TheMips64elTarget, llvm::TheMips64Target, llvm::TheMipselTarget, llvm::TheMipsTarget, llvm::X, and Y.