LLVM: MipsSEISelLowering.cpp File Reference
LLVM API Documentation
MipsSEISelLowering.cpp File Reference
#include "MipsSEISelLowering.h"
#include "MipsRegisterInfo.h"
#include "MipsTargetMachine.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
Macros
#define DEBUG_TYPE "mips-isel"
Functions
static bool selectMADD (SDNode *ADDENode, SelectionDAG *CurDAG)
static bool selectMSUB (SDNode *SUBENode, SelectionDAG *CurDAG)
static SDValue performADDECombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const MipsSubtarget *Subtarget)
static SDValue performANDCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const MipsSubtarget *Subtarget)
static bool isVSplat (SDValue N, APInt &Imm, bool IsLittleEndian)
static bool isVectorAllOnes (SDValue N)
static bool isBitwiseInverse (SDValue N, SDValue OfNode)
static SDValue performORCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const MipsSubtarget *Subtarget)
static SDValue performSUBECombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const MipsSubtarget *Subtarget)
static SDValue genConstMult (SDValue X, uint64_t C, SDLoc DL, EVT VT, EVT ShiftTy, SelectionDAG &DAG)
static SDValue performMULCombine (SDNode *N, SelectionDAG &DAG, const TargetLowering::DAGCombinerInfo &DCI, const MipsSETargetLowering *TL)
static SDValue performDSPShiftCombine (unsigned Opc, SDNode *N, EVT Ty, SelectionDAG &DAG, const MipsSubtarget *Subtarget)
static SDValue performSHLCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const MipsSubtarget *Subtarget)
static SDValue performSRACombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const MipsSubtarget *Subtarget)
static SDValue performSRLCombine (SDNode *N, SelectionDAG &DAG, TargetLowering::DAGCombinerInfo &DCI, const MipsSubtarget *Subtarget)
static bool isLegalDSPCondCode (EVT Ty, ISD::CondCode CC)
static SDValue performSETCCCombine (SDNode *N, SelectionDAG &DAG)
static SDValue performVSELECTCombine (SDNode *N, SelectionDAG &DAG)
static SDValue performXORCombine (SDNode *N, SelectionDAG &DAG, const MipsSubtarget *Subtarget)
static SDValue initAccumulator (SDValue In, SDLoc DL, SelectionDAG &DAG)
static SDValue extractLOHI (SDValue Op, SDLoc DL, SelectionDAG &DAG)
static SDValue lowerDSPIntr (SDValue Op, SelectionDAG &DAG, unsigned Opc)
static SDValue lowerMSACopyIntr (SDValue Op, SelectionDAG &DAG, unsigned Opc)
static SDValue lowerMSASplatZExt (SDValue Op, unsigned OpNr, SelectionDAG &DAG)
static SDValue lowerMSASplatImm (SDValue Op, unsigned ImmOp, SelectionDAG &DAG)
static SDValue getBuildVectorSplat (EVT VecTy, SDValue SplatValue, bool BigEndian, SelectionDAG &DAG)
static SDValue lowerMSABinaryBitImmIntr (SDValue Op, SelectionDAG &DAG, unsigned Opc, SDValue Imm, bool BigEndian)
static SDValue lowerMSABitClear (SDValue Op, SelectionDAG &DAG)
static SDValue lowerMSABitClearImm (SDValue Op, SelectionDAG &DAG)
static SDValue lowerMSALoadIntr (SDValue Op, SelectionDAG &DAG, unsigned Intr)
static SDValue lowerMSAStoreIntr (SDValue Op, SelectionDAG &DAG, unsigned Intr)
static bool isSplatVector (const BuildVectorSDNode *N)
Check if the given BuildVectorSDNode is a splat. This method currently relies on DAG nodes being reused when equivalent, so it's possible for this to return false even when isConstantSplat returns true.
static bool isConstantOrUndef (const SDValue Op)
static bool isConstantOrUndefBUILD_VECTOR (const BuildVectorSDNode *Op)
static SDValue lowerVECTOR_SHUFFLE_SHF (SDValue Op, EVT ResTy, SmallVector< int, 16 > Indices, SelectionDAG &DAG)
static SDValue lowerVECTOR_SHUFFLE_ILVEV (SDValue Op, EVT ResTy, SmallVector< int, 16 > Indices, SelectionDAG &DAG)
static SDValue lowerVECTOR_SHUFFLE_ILVOD (SDValue Op, EVT ResTy, SmallVector< int, 16 > Indices, SelectionDAG &DAG)
static SDValue lowerVECTOR_SHUFFLE_ILVL (SDValue Op, EVT ResTy, SmallVector< int, 16 > Indices, SelectionDAG &DAG)
static SDValue lowerVECTOR_SHUFFLE_ILVR (SDValue Op, EVT ResTy, SmallVector< int, 16 > Indices, SelectionDAG &DAG)
static SDValue lowerVECTOR_SHUFFLE_PCKEV (SDValue Op, EVT ResTy, SmallVector< int, 16 > Indices, SelectionDAG &DAG)
static SDValue lowerVECTOR_SHUFFLE_PCKOD (SDValue Op, EVT ResTy, SmallVector< int, 16 > Indices, SelectionDAG &DAG)
static SDValue lowerVECTOR_SHUFFLE_VSHF (SDValue Op, EVT ResTy, SmallVector< int, 16 > Indices, SelectionDAG &DAG)
Variables
static cl::opt< bool > EnableMipsTailCalls ("enable-mips-tail-calls", cl::Hidden, cl::desc("MIPS: Enable tail calls."), cl::init(false))
static cl::opt< bool > NoDPLoadStore ("mno-ldc1-sdc1", cl::init(false), cl::desc("Expand double precision loads and ""stores to their single precision ""counterparts"))
Macro Definition Documentation
#define DEBUG_TYPE "mips-isel"
Definition at line 13 of file MipsSEISelLowering.cpp.
Function Documentation
static SDValue extractLOHI (SDValue Op, SDLoc DL, SelectionDAG & DAG) static
Definition at line 1184 of file MipsSEISelLowering.cpp.
References llvm::ISD::BUILD_PAIR, llvm::SelectionDAG::getNode(), llvm::HexagonISD::Hi, llvm::MVT::i32, llvm::MVT::i64, llvm::HexagonISD::Lo, llvm::MipsISD::MFHI, and llvm::MipsISD::MFLO.
Referenced by lowerDSPIntr().
static SDValue genConstMult (SDValue X, uint64_t C, SDLoc DL, EVT VT, EVT ShiftTy, SelectionDAG & DAG) static
Definition at line 697 of file MipsSEISelLowering.cpp.
References llvm::ISD::ADD, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::EVT::getSizeInBits(), llvm::isPowerOf2_64(), llvm::Log2_64(), llvm::Log2_64_Ceil(), llvm::ISD::SHL, llvm::ISD::SUB, and llvm::X.
Referenced by performMULCombine().
static SDValue getBuildVectorSplat (EVT VecTy, SDValue SplatValue, bool BigEndian, SelectionDAG & DAG) static
Definition at line 1297 of file MipsSEISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::EVT::getVectorNumElements(), llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::SRL, std::swap(), llvm::ISD::TRUNCATE, llvm::MVT::v2i64, and llvm::MVT::v4i32.
Referenced by lowerMSABinaryBitImmIntr().
static SDValue initAccumulator (SDValue In, SDLoc DL, SelectionDAG & DAG) static
Definition at line 1176 of file MipsSEISelLowering.cpp.
References llvm::ISD::EXTRACT_ELEMENT, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::i32, llvm::MipsISD::MTLOHI, and llvm::MVT::Untyped.
Referenced by lowerDSPIntr().
static bool isBitwiseInverse (SDValue N, SDValue OfNode) static
Definition at line 545 of file MipsSEISelLowering.cpp.
References llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), isVectorAllOnes(), and llvm::ISD::XOR.
Referenced by performORCombine().
static bool isConstantOrUndef (const SDValue Op) static
Definition at line 2162 of file MipsSEISelLowering.cpp.
References llvm::SDNode::getOpcode(), and llvm::ISD::UNDEF.
Referenced by isConstantOrUndefBUILD_VECTOR().
static bool isConstantOrUndefBUILD_VECTOR (const BuildVectorSDNode * Op) static
Definition at line 2172 of file MipsSEISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getUNDEF(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::MipsSubtarget::hasMSA(), i, llvm::MVT::i32, llvm::ISD::INSERT_VECTOR_ELT, isConstantOrUndef(), llvm::BuildVectorSDNode::isConstantSplat(), llvm::MipsSubtarget::isLittle(), llvm::APInt::isSignedIntN(), isSplatVector(), llvm::EVT::isVector(), llvm::MipsTargetLowering::Subtarget, llvm::MVT::v16i8, llvm::MVT::v4i32, and llvm::MVT::v8i16.
static bool isLegalDSPCondCode (EVT Ty, ISD::CondCode CC) static
Definition at line 852 of file MipsSEISelLowering.cpp.
References llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, and llvm::MVT::v2i16.
Referenced by performSETCCCombine().
static bool isSplatVector (const BuildVectorSDNode * N) static
Check if the given BuildVectorSDNode is a splat. This method currently relies on DAG nodes being reused when equivalent, so it's possible for this to return false even when isConstantSplat returns true.
Definition at line 2121 of file MipsSEISelLowering.cpp.
References llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), i, llvm::EVT::is128BitVector(), llvm::EVT::isInteger(), and llvm::MipsISD::VEXTRACT_SEXT_ELT.
Referenced by isConstantOrUndefBUILD_VECTOR().
static bool isVectorAllOnes (SDValue N) static
Definition at line 521 of file MipsSEISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::dyn_cast(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::APInt::isAllOnesValue(), llvm::BuildVectorSDNode::isConstantSplat(), and N.
Referenced by isBitwiseInverse().
static bool isVSplat (SDValue N, APInt & Imm, bool IsLittleEndian) static
Definition at line 501 of file MipsSEISelLowering.cpp.
References llvm::dyn_cast(), llvm::SDValue::getNode(), and llvm::BuildVectorSDNode::isConstantSplat().
Referenced by performORCombine().
static SDValue lowerDSPIntr (SDValue Op, SelectionDAG & DAG, unsigned Opc) static
Definition at line 1202 of file MipsSEISelLowering.cpp.
References extractLOHI(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), I, llvm::MVT::i64, initAccumulator(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::ISD::TargetConstant, llvm::MVT::Untyped, llvm::SDNode::value_begin(), and llvm::SDNode::value_end().
Referenced by lowerMSABitClearImm(), and lowerMSALoadIntr().
static SDValue lowerMSABinaryBitImmIntr (SDValue Op, SelectionDAG & DAG, unsigned Opc, SDValue Imm, bool BigEndian) static
Definition at line 1333 of file MipsSEISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, getBuildVectorSplat(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::MVT::i32, llvm::MVT::i64, llvm::APInt::lshr(), llvm::ISD::SHL, std::swap(), llvm::APInt::trunc(), llvm::MVT::v2i64, llvm::MVT::v4i32, and llvm::ISD::ZERO_EXTEND.
Referenced by lowerMSABitClearImm().
static SDValue lowerMSABitClear (SDValue Op, SelectionDAG & DAG) static
Definition at line 1376 of file MipsSEISelLowering.cpp.
References llvm::ISD::AND, llvm::tgtok::Bit, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNOT(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), and llvm::ISD::SHL.
Referenced by lowerMSABitClearImm().
static SDValue lowerMSABitClearImm (SDValue Op, SelectionDAG & DAG) static
Definition at line 1386 of file MipsSEISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::ISD::BUILD_VECTOR, llvm::ISD::CTLZ, llvm::ISD::CTPOP, llvm::MipsISD::DPA_W_PH, llvm::MipsISD::DPAU_H_QBL, llvm::MipsISD::DPAU_H_QBR, llvm::MipsISD::DPAX_W_PH, llvm::MipsISD::DPS_W_PH, llvm::MipsISD::DPSU_H_QBL, llvm::MipsISD::DPSU_H_QBR, llvm::MipsISD::DPSX_W_PH, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::ISD::FADD, llvm::ISD::FDIV, llvm::ISD::FEXP2, llvm::ISD::FLOG2, llvm::ISD::FMA, llvm::ISD::FMUL, llvm::ISD::FP_TO_SINT, llvm::ISD::FP_TO_UINT, llvm::ISD::FRINT, llvm::ISD::FSQRT, llvm::ISD::FSUB, llvm::SelectionDAG::getConstant(), llvm::SDNode::getConstantOperandVal(), llvm::APInt::getHighBitsSet(), llvm::APInt::getLowBitsSet(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNOT(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getSetCC(), llvm::EVT::getSizeInBits(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), i, llvm::MipsISD::ILVEV, llvm::MipsISD::ILVL, llvm::MipsISD::ILVOD, llvm::MipsISD::ILVR, llvm::ISD::INSERT_VECTOR_ELT, llvm::MipsSubtarget::isLittle(), lowerDSPIntr(), lowerMSABinaryBitImmIntr(), lowerMSABitClear(), lowerMSACopyIntr(), lowerMSASplatImm(), lowerMSASplatZExt(), llvm::MipsISD::MAdd, llvm::MipsISD::MAddu, llvm::Intrinsic::mips_addv_b, llvm::Intrinsic::mips_addv_d, llvm::Intrinsic::mips_addv_h, llvm::Intrinsic::mips_addv_w, llvm::Intrinsic::mips_addvi_b, llvm::Intrinsic::mips_addvi_d, llvm::Intrinsic::mips_addvi_h, llvm::Intrinsic::mips_addvi_w, llvm::Intrinsic::mips_and_v, llvm::Intrinsic::mips_andi_b, llvm::Intrinsic::mips_bclr_b, llvm::Intrinsic::mips_bclr_d, llvm::Intrinsic::mips_bclr_h, llvm::Intrinsic::mips_bclr_w, llvm::Intrinsic::mips_bclri_b, llvm::Intrinsic::mips_bclri_d, llvm::Intrinsic::mips_bclri_h, llvm::Intrinsic::mips_bclri_w, llvm::Intrinsic::mips_binsli_b, llvm::Intrinsic::mips_binsli_d, llvm::Intrinsic::mips_binsli_h, llvm::Intrinsic::mips_binsli_w, llvm::Intrinsic::mips_binsri_b, llvm::Intrinsic::mips_binsri_d, llvm::Intrinsic::mips_binsri_h, llvm::Intrinsic::mips_binsri_w, llvm::Intrinsic::mips_bmnz_v, llvm::Intrinsic::mips_bmnzi_b, llvm::Intrinsic::mips_bmz_v, llvm::Intrinsic::mips_bmzi_b, llvm::Intrinsic::mips_bneg_b, llvm::Intrinsic::mips_bneg_d, llvm::Intrinsic::mips_bneg_h, llvm::Intrinsic::mips_bneg_w, llvm::Intrinsic::mips_bnegi_b, llvm::Intrinsic::mips_bnegi_d, llvm::Intrinsic::mips_bnegi_h, llvm::Intrinsic::mips_bnegi_w, llvm::Intrinsic::mips_bnz_b, llvm::Intrinsic::mips_bnz_d, llvm::Intrinsic::mips_bnz_h, llvm::Intrinsic::mips_bnz_v, llvm::Intrinsic::mips_bnz_w, llvm::Intrinsic::mips_bsel_v, llvm::Intrinsic::mips_bseli_b, llvm::Intrinsic::mips_bset_b, llvm::Intrinsic::mips_bset_d, llvm::Intrinsic::mips_bset_h, llvm::Intrinsic::mips_bset_w, llvm::Intrinsic::mips_bseti_b, llvm::Intrinsic::mips_bseti_d, llvm::Intrinsic::mips_bseti_h, llvm::Intrinsic::mips_bseti_w, llvm::Intrinsic::mips_bz_b, llvm::Intrinsic::mips_bz_d, llvm::Intrinsic::mips_bz_h, llvm::Intrinsic::mips_bz_v, llvm::Intrinsic::mips_bz_w, llvm::Intrinsic::mips_ceq_b, llvm::Intrinsic::mips_ceq_d, llvm::Intrinsic::mips_ceq_h, llvm::Intrinsic::mips_ceq_w, llvm::Intrinsic::mips_ceqi_b, llvm::Intrinsic::mips_ceqi_d, llvm::Intrinsic::mips_ceqi_h, llvm::Intrinsic::mips_ceqi_w, llvm::Intrinsic::mips_cle_s_b, llvm::Intrinsic::mips_cle_s_d, llvm::Intrinsic::mips_cle_s_h, llvm::Intrinsic::mips_cle_s_w, llvm::Intrinsic::mips_cle_u_b, llvm::Intrinsic::mips_cle_u_d, llvm::Intrinsic::mips_cle_u_h, llvm::Intrinsic::mips_cle_u_w, llvm::Intrinsic::mips_clei_s_b, llvm::Intrinsic::mips_clei_s_d, llvm::Intrinsic::mips_clei_s_h, llvm::Intrinsic::mips_clei_s_w, llvm::Intrinsic::mips_clei_u_b, llvm::Intrinsic::mips_clei_u_d, llvm::Intrinsic::mips_clei_u_h, llvm::Intrinsic::mips_clei_u_w, llvm::Intrinsic::mips_clt_s_b, llvm::Intrinsic::mips_clt_s_d, llvm::Intrinsic::mips_clt_s_h, llvm::Intrinsic::mips_clt_s_w, llvm::Intrinsic::mips_clt_u_b, llvm::Intrinsic::mips_clt_u_d, llvm::Intrinsic::mips_clt_u_h, llvm::Intrinsic::mips_clt_u_w, llvm::Intrinsic::mips_clti_s_b, llvm::Intrinsic::mips_clti_s_d, llvm::Intrinsic::mips_clti_s_h, llvm::Intrinsic::mips_clti_s_w, llvm::Intrinsic::mips_clti_u_b, llvm::Intrinsic::mips_clti_u_d, llvm::Intrinsic::mips_clti_u_h, llvm::Intrinsic::mips_clti_u_w, llvm::Intrinsic::mips_copy_s_b, llvm::Intrinsic::mips_copy_s_d, llvm::Intrinsic::mips_copy_s_h, llvm::Intrinsic::mips_copy_s_w, llvm::Intrinsic::mips_copy_u_b, llvm::Intrinsic::mips_copy_u_d, llvm::Intrinsic::mips_copy_u_h, llvm::Intrinsic::mips_copy_u_w, llvm::Intrinsic::mips_div_s_b, llvm::Intrinsic::mips_div_s_d, llvm::Intrinsic::mips_div_s_h, llvm::Intrinsic::mips_div_s_w, llvm::Intrinsic::mips_div_u_b, llvm::Intrinsic::mips_div_u_d, llvm::Intrinsic::mips_div_u_h, llvm::Intrinsic::mips_div_u_w, llvm::Intrinsic::mips_dpa_w_ph, llvm::Intrinsic::mips_dpau_h_qbl, llvm::Intrinsic::mips_dpau_h_qbr, llvm::Intrinsic::mips_dpax_w_ph, llvm::Intrinsic::mips_dps_w_ph, llvm::Intrinsic::mips_dpsu_h_qbl, llvm::Intrinsic::mips_dpsu_h_qbr, llvm::Intrinsic::mips_dpsx_w_ph, llvm::Intrinsic::mips_fadd_d, llvm::Intrinsic::mips_fadd_w, llvm::Intrinsic::mips_fceq_d, llvm::Intrinsic::mips_fceq_w, llvm::Intrinsic::mips_fcle_d, llvm::Intrinsic::mips_fcle_w, llvm::Intrinsic::mips_fclt_d, llvm::Intrinsic::mips_fclt_w, llvm::Intrinsic::mips_fcne_d, llvm::Intrinsic::mips_fcne_w, llvm::Intrinsic::mips_fcor_d, llvm::Intrinsic::mips_fcor_w, llvm::Intrinsic::mips_fcueq_d, llvm::Intrinsic::mips_fcueq_w, llvm::Intrinsic::mips_fcule_d, llvm::Intrinsic::mips_fcule_w, llvm::Intrinsic::mips_fcult_d, llvm::Intrinsic::mips_fcult_w, llvm::Intrinsic::mips_fcun_d, llvm::Intrinsic::mips_fcun_w, llvm::Intrinsic::mips_fcune_d, llvm::Intrinsic::mips_fcune_w, llvm::Intrinsic::mips_fdiv_d, llvm::Intrinsic::mips_fdiv_w, llvm::Intrinsic::mips_fexp2_d, llvm::Intrinsic::mips_fexp2_w, llvm::Intrinsic::mips_ffint_s_d, llvm::Intrinsic::mips_ffint_s_w, llvm::Intrinsic::mips_ffint_u_d, llvm::Intrinsic::mips_ffint_u_w, llvm::Intrinsic::mips_fill_b, llvm::Intrinsic::mips_fill_d, llvm::Intrinsic::mips_fill_h, llvm::Intrinsic::mips_fill_w, llvm::Intrinsic::mips_flog2_d, llvm::Intrinsic::mips_flog2_w, llvm::Intrinsic::mips_fmadd_d, llvm::Intrinsic::mips_fmadd_w, llvm::Intrinsic::mips_fmsub_d, llvm::Intrinsic::mips_fmsub_w, llvm::Intrinsic::mips_fmul_d, llvm::Intrinsic::mips_fmul_w, llvm::Intrinsic::mips_frint_d, llvm::Intrinsic::mips_frint_w, llvm::Intrinsic::mips_fsqrt_d, llvm::Intrinsic::mips_fsqrt_w, llvm::Intrinsic::mips_fsub_d, llvm::Intrinsic::mips_fsub_w, llvm::Intrinsic::mips_ftrunc_s_d, llvm::Intrinsic::mips_ftrunc_s_w, llvm::Intrinsic::mips_ftrunc_u_d, llvm::Intrinsic::mips_ftrunc_u_w, llvm::Intrinsic::mips_ilvev_b, llvm::Intrinsic::mips_ilvev_d, llvm::Intrinsic::mips_ilvev_h, llvm::Intrinsic::mips_ilvev_w, llvm::Intrinsic::mips_ilvl_b, llvm::Intrinsic::mips_ilvl_d, llvm::Intrinsic::mips_ilvl_h, llvm::Intrinsic::mips_ilvl_w, llvm::Intrinsic::mips_ilvod_b, llvm::Intrinsic::mips_ilvod_d, llvm::Intrinsic::mips_ilvod_h, llvm::Intrinsic::mips_ilvod_w, llvm::Intrinsic::mips_ilvr_b, llvm::Intrinsic::mips_ilvr_d, llvm::Intrinsic::mips_ilvr_h, llvm::Intrinsic::mips_ilvr_w, llvm::Intrinsic::mips_insert_b, llvm::Intrinsic::mips_insert_d, llvm::Intrinsic::mips_insert_h, llvm::Intrinsic::mips_insert_w, llvm::Intrinsic::mips_ldi_b, llvm::Intrinsic::mips_ldi_d, llvm::Intrinsic::mips_ldi_h, llvm::Intrinsic::mips_ldi_w, llvm::Intrinsic::mips_lsa, llvm::Intrinsic::mips_madd, llvm::Intrinsic::mips_maddu, llvm::Intrinsic::mips_maddv_b, llvm::Intrinsic::mips_maddv_d, llvm::Intrinsic::mips_maddv_h, llvm::Intrinsic::mips_maddv_w, llvm::Intrinsic::mips_max_s_b, llvm::Intrinsic::mips_max_s_d, llvm::Intrinsic::mips_max_s_h, llvm::Intrinsic::mips_max_s_w, llvm::Intrinsic::mips_max_u_b, llvm::Intrinsic::mips_max_u_d, llvm::Intrinsic::mips_max_u_h, llvm::Intrinsic::mips_max_u_w, llvm::Intrinsic::mips_maxi_s_b, llvm::Intrinsic::mips_maxi_s_d, llvm::Intrinsic::mips_maxi_s_h, llvm::Intrinsic::mips_maxi_s_w, llvm::Intrinsic::mips_maxi_u_b, llvm::Intrinsic::mips_maxi_u_d, llvm::Intrinsic::mips_maxi_u_h, llvm::Intrinsic::mips_maxi_u_w, llvm::Intrinsic::mips_min_s_b, llvm::Intrinsic::mips_min_s_d, llvm::Intrinsic::mips_min_s_h, llvm::Intrinsic::mips_min_s_w, llvm::Intrinsic::mips_min_u_b, llvm::Intrinsic::mips_min_u_d, llvm::Intrinsic::mips_min_u_h, llvm::Intrinsic::mips_min_u_w, llvm::Intrinsic::mips_mini_s_b, llvm::Intrinsic::mips_mini_s_d, llvm::Intrinsic::mips_mini_s_h, llvm::Intrinsic::mips_mini_s_w, llvm::Intrinsic::mips_mini_u_b, llvm::Intrinsic::mips_mini_u_d, llvm::Intrinsic::mips_mini_u_h, llvm::Intrinsic::mips_mini_u_w, llvm::Intrinsic::mips_mod_s_b, llvm::Intrinsic::mips_mod_s_d, llvm::Intrinsic::mips_mod_s_h, llvm::Intrinsic::mips_mod_s_w, llvm::Intrinsic::mips_mod_u_b, llvm::Intrinsic::mips_mod_u_d, llvm::Intrinsic::mips_mod_u_h, llvm::Intrinsic::mips_mod_u_w, llvm::Intrinsic::mips_msub, llvm::Intrinsic::mips_msubu, llvm::Intrinsic::mips_msubv_b, llvm::Intrinsic::mips_msubv_d, llvm::Intrinsic::mips_msubv_h, llvm::Intrinsic::mips_msubv_w, llvm::Intrinsic::mips_mulsa_w_ph, llvm::Intrinsic::mips_mult, llvm::Intrinsic::mips_multu, llvm::Intrinsic::mips_mulv_b, llvm::Intrinsic::mips_mulv_d, llvm::Intrinsic::mips_mulv_h, llvm::Intrinsic::mips_mulv_w, llvm::Intrinsic::mips_nlzc_b, llvm::Intrinsic::mips_nlzc_d, llvm::Intrinsic::mips_nlzc_h, llvm::Intrinsic::mips_nlzc_w, llvm::Intrinsic::mips_nor_v, llvm::Intrinsic::mips_nori_b, llvm::Intrinsic::mips_or_v, llvm::Intrinsic::mips_ori_b, llvm::Intrinsic::mips_pckev_b, llvm::Intrinsic::mips_pckev_d, llvm::Intrinsic::mips_pckev_h, llvm::Intrinsic::mips_pckev_w, llvm::Intrinsic::mips_pckod_b, llvm::Intrinsic::mips_pckod_d, llvm::Intrinsic::mips_pckod_h, llvm::Intrinsic::mips_pckod_w, llvm::Intrinsic::mips_pcnt_b, llvm::Intrinsic::mips_pcnt_d, llvm::Intrinsic::mips_pcnt_h, llvm::Intrinsic::mips_pcnt_w, llvm::Intrinsic::mips_shf_b, llvm::Intrinsic::mips_shf_h, llvm::Intrinsic::mips_shf_w, llvm::Intrinsic::mips_shilo, llvm::Intrinsic::mips_sll_b, llvm::Intrinsic::mips_sll_d, llvm::Intrinsic::mips_sll_h, llvm::Intrinsic::mips_sll_w, llvm::Intrinsic::mips_slli_b, llvm::Intrinsic::mips_slli_d, llvm::Intrinsic::mips_slli_h, llvm::Intrinsic::mips_slli_w, llvm::Intrinsic::mips_splat_b, llvm::Intrinsic::mips_splat_d, llvm::Intrinsic::mips_splat_h, llvm::Intrinsic::mips_splat_w, llvm::Intrinsic::mips_splati_b, llvm::Intrinsic::mips_splati_d, llvm::Intrinsic::mips_splati_h, llvm::Intrinsic::mips_splati_w, llvm::Intrinsic::mips_sra_b, llvm::Intrinsic::mips_sra_d, llvm::Intrinsic::mips_sra_h, llvm::Intrinsic::mips_sra_w, llvm::Intrinsic::mips_srai_b, llvm::Intrinsic::mips_srai_d, llvm::Intrinsic::mips_srai_h, llvm::Intrinsic::mips_srai_w, llvm::Intrinsic::mips_srl_b, llvm::Intrinsic::mips_srl_d, llvm::Intrinsic::mips_srl_h, llvm::Intrinsic::mips_srl_w, llvm::Intrinsic::mips_srli_b, llvm::Intrinsic::mips_srli_d, llvm::Intrinsic::mips_srli_h, llvm::Intrinsic::mips_srli_w, llvm::Intrinsic::mips_subv_b, llvm::Intrinsic::mips_subv_d, llvm::Intrinsic::mips_subv_h, llvm::Intrinsic::mips_subv_w, llvm::Intrinsic::mips_subvi_b, llvm::Intrinsic::mips_subvi_d, llvm::Intrinsic::mips_subvi_h, llvm::Intrinsic::mips_subvi_w, llvm::Intrinsic::mips_vshf_b, llvm::Intrinsic::mips_vshf_d, llvm::Intrinsic::mips_vshf_h, llvm::Intrinsic::mips_vshf_w, llvm::Intrinsic::mips_xor_v, llvm::Intrinsic::mips_xori_b, llvm::MipsISD::MSub, llvm::MipsISD::MSubu, llvm::ISD::MUL, llvm::MipsISD::MULSA_W_PH, llvm::MipsISD::Mult, llvm::MipsISD::Multu, llvm::ISD::OR, llvm::MipsISD::PCKEV, llvm::MipsISD::PCKOD, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::ISD::SDIV, llvm::ISD::SETEQ, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETUEQ, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, llvm::ISD::SETUO, llvm::MipsISD::SHF, llvm::MipsISD::SHILO, llvm::ISD::SHL, llvm::ISD::SINT_TO_FP, llvm::SmallVectorTemplateCommon< T >::size(), llvm::ISD::SRA, llvm::ISD::SREM, llvm::ISD::SRL, llvm::ISD::SUB, llvm::MipsTargetLowering::Subtarget, llvm::ISD::UDIV, llvm::ISD::UINT_TO_FP, llvm::ISD::UREM, llvm::MipsISD::VALL_NONZERO, llvm::MipsISD::VALL_ZERO, llvm::MipsISD::VANY_NONZERO, llvm::MipsISD::VANY_ZERO, llvm::MipsISD::VEXTRACT_SEXT_ELT, llvm::MipsISD::VEXTRACT_ZEXT_ELT, llvm::ISD::VSELECT, llvm::MipsISD::VSHF, llvm::MipsISD::VSMAX, llvm::MipsISD::VSMIN, llvm::MipsISD::VUMAX, llvm::MipsISD::VUMIN, and llvm::ISD::XOR.
static SDValue lowerMSACopyIntr (SDValue Op, SelectionDAG & DAG, unsigned Opc) static
Definition at line 1251 of file MipsSEISelLowering.cpp.
References llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getValueType(), llvm::SDNode::getValueType(), and llvm::EVT::getVectorElementType().
Referenced by lowerMSABitClearImm().
static SDValue lowerMSALoadIntr (SDValue Op, SelectionDAG & DAG, unsigned Intr) static
Definition at line 2021 of file MipsSEISelLowering.cpp.
References llvm::ISD::ADD, llvm::MipsISD::DPAQ_S_W_PH, llvm::MipsISD::DPAQ_SA_L_W, llvm::MipsISD::DPAQX_S_W_PH, llvm::MipsISD::DPAQX_SA_W_PH, llvm::MipsISD::DPSQ_S_W_PH, llvm::MipsISD::DPSQ_SA_L_W, llvm::MipsISD::DPSQX_S_W_PH, llvm::MipsISD::DPSQX_SA_W_PH, llvm::MipsISD::EXTP, llvm::MipsISD::EXTPDP, llvm::MipsISD::EXTR_R_W, llvm::MipsISD::EXTR_RS_W, llvm::MipsISD::EXTR_S_H, llvm::MipsISD::EXTR_W, llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), lowerDSPIntr(), llvm::MipsISD::MAQ_S_W_PHL, llvm::MipsISD::MAQ_S_W_PHR, llvm::MipsISD::MAQ_SA_W_PHL, llvm::MipsISD::MAQ_SA_W_PHR, llvm::Intrinsic::mips_dpaq_s_w_ph, llvm::Intrinsic::mips_dpaq_sa_l_w, llvm::Intrinsic::mips_dpaqx_s_w_ph, llvm::Intrinsic::mips_dpaqx_sa_w_ph, llvm::Intrinsic::mips_dpsq_s_w_ph, llvm::Intrinsic::mips_dpsq_sa_l_w, llvm::Intrinsic::mips_dpsqx_s_w_ph, llvm::Intrinsic::mips_dpsqx_sa_w_ph, llvm::Intrinsic::mips_extp, llvm::Intrinsic::mips_extpdp, llvm::Intrinsic::mips_extr_r_w, llvm::Intrinsic::mips_extr_rs_w, llvm::Intrinsic::mips_extr_s_h, llvm::Intrinsic::mips_extr_w, llvm::Intrinsic::mips_ld_b, llvm::Intrinsic::mips_ld_d, llvm::Intrinsic::mips_ld_h, llvm::Intrinsic::mips_ld_w, llvm::Intrinsic::mips_maq_s_w_phl, llvm::Intrinsic::mips_maq_s_w_phr, llvm::Intrinsic::mips_maq_sa_w_phl, llvm::Intrinsic::mips_maq_sa_w_phr, llvm::Intrinsic::mips_mthlip, llvm::Intrinsic::mips_mulsaq_s_w_ph, llvm::MipsISD::MTHLIP, and llvm::MipsISD::MULSAQ_S_W_PH.
static SDValue lowerMSASplatImm (SDValue Op, unsigned ImmOp, SelectionDAG & DAG) static
Definition at line 1293 of file MipsSEISelLowering.cpp.
References llvm::SelectionDAG::getConstant(), llvm::SDNode::getConstantOperandVal(), and llvm::SDNode::getValueType().
Referenced by lowerMSABitClearImm().
static SDValue lowerMSASplatZExt (SDValue Op, unsigned OpNr, SelectionDAG & DAG) static
Definition at line 1264 of file MipsSEISelLowering.cpp.
References llvm::ISD::BITCAST, llvm::ISD::BUILD_VECTOR, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::EVT::getVectorNumElements(), llvm::MVT::i32, llvm::MVT::v2i64, and llvm::MVT::v4i32.
Referenced by lowerMSABitClearImm().
static SDValue lowerMSAStoreIntr (SDValue Op, SelectionDAG & DAG, unsigned Intr) static
Definition at line 2089 of file MipsSEISelLowering.cpp.
References llvm::ISD::ADD, llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getStore(), llvm::SDNode::getValueType(), llvm::Intrinsic::mips_st_b, llvm::Intrinsic::mips_st_d, llvm::Intrinsic::mips_st_h, and llvm::Intrinsic::mips_st_w.
static SDValue lowerVECTOR_SHUFFLE_ILVEV (SDValue Op, EVT ResTy, SmallVector< int, 16 > Indices, SelectionDAG & DAG) static
Definition at line 2345 of file MipsSEISelLowering.cpp.
References llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::EVT::getVectorNumElements(), i, llvm::MipsISD::ILVEV, and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by lowerVECTOR_SHUFFLE_VSHF().
static SDValue lowerVECTOR_SHUFFLE_ILVL (SDValue Op, EVT ResTy, SmallVector< int, 16 > Indices, SelectionDAG & DAG) static
Definition at line 2405 of file MipsSEISelLowering.cpp.
References llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::EVT::getVectorNumElements(), i, llvm::MipsISD::ILVL, and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by lowerVECTOR_SHUFFLE_VSHF().
static SDValue lowerVECTOR_SHUFFLE_ILVOD (SDValue Op, EVT ResTy, SmallVector< int, 16 > Indices, SelectionDAG & DAG) static
Definition at line 2375 of file MipsSEISelLowering.cpp.
References llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::EVT::getVectorNumElements(), i, llvm::MipsISD::ILVOD, and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by lowerVECTOR_SHUFFLE_VSHF().
static SDValue lowerVECTOR_SHUFFLE_ILVR (SDValue Op, EVT ResTy, SmallVector< int, 16 > Indices, SelectionDAG & DAG) static
Definition at line 2435 of file MipsSEISelLowering.cpp.
References llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::EVT::getVectorNumElements(), i, llvm::MipsISD::ILVR, and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by lowerVECTOR_SHUFFLE_VSHF().
static SDValue lowerVECTOR_SHUFFLE_PCKEV (SDValue Op, EVT ResTy, SmallVector< int, 16 > Indices, SelectionDAG & DAG) static
Definition at line 2466 of file MipsSEISelLowering.cpp.
References llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), i, llvm::MipsISD::PCKEV, and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by lowerVECTOR_SHUFFLE_VSHF().
static SDValue lowerVECTOR_SHUFFLE_PCKOD (SDValue Op, EVT ResTy, SmallVector< int, 16 > Indices, SelectionDAG & DAG) static
Definition at line 2492 of file MipsSEISelLowering.cpp.
References llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), i, llvm::MipsISD::PCKOD, and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by lowerVECTOR_SHUFFLE_VSHF().
static SDValue lowerVECTOR_SHUFFLE_SHF (SDValue Op, EVT ResTy, SmallVector< int, 16 > Indices, SelectionDAG & DAG) static
Definition at line 2287 of file MipsSEISelLowering.cpp.
References llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), i, llvm::MVT::i32, j(), llvm::MipsISD::SHF, and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by lowerVECTOR_SHUFFLE_VSHF().
static SDValue lowerVECTOR_SHUFFLE_VSHF (SDValue Op, EVT ResTy, SmallVector< int, 16 > Indices, SelectionDAG & DAG) static
Definition at line 2516 of file MipsSEISelLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), B, BB, llvm::SmallVectorTemplateCommon< T >::begin(), llvm::MachineBasicBlock::begin(), llvm::ISD::BUILD_VECTOR, llvm::BuildMI(), llvm::EVT::changeVectorElementTypeToInteger(), llvm::TargetOpcode::COPY, llvm::MachineFunction::CreateMachineBasicBlock(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), F(), llvm::MCInstrInfo::get(), llvm::DebugLoc::get(), llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::TargetMachine::getInstrInfo(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::MachineInstr::getOperand(), llvm::SDNode::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::SelectionDAG::getTargetConstant(), llvm::TargetLoweringBase::getTargetMachine(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), i, I, llvm::TargetOpcode::IMPLICIT_DEF, llvm::MachineFunction::insert(), llvm::TargetOpcode::INSERT_SUBREG, llvm::MipsSubtarget::isFP64bit(), llvm_unreachable, lowerVECTOR_SHUFFLE_ILVEV(), lowerVECTOR_SHUFFLE_ILVL(), lowerVECTOR_SHUFFLE_ILVOD(), lowerVECTOR_SHUFFLE_ILVR(), lowerVECTOR_SHUFFLE_PCKEV(), lowerVECTOR_SHUFFLE_PCKOD(), lowerVECTOR_SHUFFLE_SHF(), llvm::A64CC::MI, llvm::next(), llvm::TargetOpcode::PHI, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::cl::Sink, llvm::SmallVectorTemplateCommon< T >::size(), llvm::MachineBasicBlock::splice(), llvm::TargetOpcode::SUBREG_TO_REG, llvm::MipsTargetLowering::Subtarget, TII, llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs(), and llvm::MipsISD::VSHF.
static SDValue performADDECombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const MipsSubtarget * Subtarget) static
Definition at line 429 of file MipsSEISelLowering.cpp.
References llvm::SDNode::getValueType(), llvm::MipsSubtarget::hasMips32(), llvm::MVT::i32, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), and selectMADD().
Referenced by llvm::MipsSETargetLowering::PerformDAGCombine().
static SDValue performANDCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const MipsSubtarget * Subtarget) static
Definition at line 449 of file MipsSEISelLowering.cpp.
References llvm::dyn_cast(), llvm::ConstantSDNode::getAPIntValue(), llvm::SDValue::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDNode::getVTList(), llvm::MipsSubtarget::hasMSA(), llvm::SelectionDAG::MorphNodeTo(), llvm::MipsISD::VEXTRACT_SEXT_ELT, and llvm::MipsISD::VEXTRACT_ZEXT_ELT.
Referenced by llvm::MipsSETargetLowering::PerformDAGCombine().
static SDValue performDSPShiftCombine (unsigned Opc, SDNode * N, EVT Ty, SelectionDAG & DAG, const MipsSubtarget * Subtarget) static
Definition at line 748 of file MipsSEISelLowering.cpp.
References llvm::dyn_cast(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::EVT::getVectorElementType(), llvm::APInt::getZExtValue(), llvm::MipsSubtarget::hasDSP(), llvm::MVT::i32, llvm::BuildVectorSDNode::isConstantSplat(), and llvm::MipsSubtarget::isLittle().
Referenced by performSHLCombine(), performSRACombine(), and performSRLCombine().
static SDValue performMULCombine (SDNode * N, SelectionDAG & DAG, const TargetLowering::DAGCombinerInfo & DCI, const MipsSETargetLowering * TL) static
Definition at line 735 of file MipsSEISelLowering.cpp.
References genConstMult(), llvm::SDNode::getOperand(), llvm::MipsTargetLowering::getScalarShiftAmountTy(), llvm::SDNode::getValueType(), and llvm::EVT::isVector().
Referenced by llvm::MipsSETargetLowering::PerformDAGCombine().
static SDValue performORCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const MipsSubtarget * Subtarget) static
Definition at line 564 of file MipsSEISelLowering.cpp.
References llvm::ISD::AND, llvm::APInt::getBitWidth(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::MipsSubtarget::hasMSA(), llvm::EVT::is128BitVector(), llvm::APInt::isAllOnesValue(), isBitwiseInverse(), llvm::MipsSubtarget::isLittle(), isVSplat(), and llvm::ISD::VSELECT.
Referenced by llvm::MipsSETargetLowering::PerformDAGCombine().
static SDValue performSETCCCombine (SDNode * N, SelectionDAG & DAG) static
Definition at line 870 of file MipsSEISelLowering.cpp.
References llvm::SelectionDAG::getNode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), isLegalDSPCondCode(), llvm::MipsISD::SETCC_DSP, llvm::MVT::v2i16, and llvm::MVT::v4i8.
Referenced by llvm::MipsSETargetLowering::PerformDAGCombine().
static SDValue performSHLCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const MipsSubtarget * Subtarget) static
Definition at line 772 of file MipsSEISelLowering.cpp.
References llvm::SDNode::getValueType(), performDSPShiftCombine(), llvm::MipsISD::SHLL_DSP, llvm::MVT::v2i16, and llvm::MVT::v4i8.
Referenced by llvm::MipsSETargetLowering::PerformDAGCombine().
static SDValue performSRACombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const MipsSubtarget * Subtarget) static
Definition at line 795 of file MipsSEISelLowering.cpp.
References llvm::dyn_cast(), llvm::SDValue::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDNode::getValueType(), llvm::SDNode::getVTList(), llvm::ConstantSDNode::getZExtValue(), llvm::MipsSubtarget::hasDSPR2(), llvm::MipsSubtarget::hasMSA(), llvm::SelectionDAG::MorphNodeTo(), performDSPShiftCombine(), llvm::ISD::SHL, llvm::MipsISD::SHRA_DSP, llvm::MVT::v2i16, llvm::MVT::v4i8, llvm::MipsISD::VEXTRACT_SEXT_ELT, and llvm::MipsISD::VEXTRACT_ZEXT_ELT.
Referenced by llvm::MipsSETargetLowering::PerformDAGCombine().
static SDValue performSRLCombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const MipsSubtarget * Subtarget) static
Definition at line 841 of file MipsSEISelLowering.cpp.
References llvm::SDNode::getValueType(), llvm::MipsSubtarget::hasDSPR2(), performDSPShiftCombine(), llvm::MipsISD::SHRL_DSP, llvm::MVT::v2i16, and llvm::MVT::v4i8.
Referenced by llvm::MipsSETargetLowering::PerformDAGCombine().
static SDValue performSUBECombine (SDNode * N, SelectionDAG & DAG, TargetLowering::DAGCombinerInfo & DCI, const MipsSubtarget * Subtarget) static
Definition at line 684 of file MipsSEISelLowering.cpp.
References llvm::SDNode::getValueType(), llvm::MipsSubtarget::hasMips32(), llvm::MVT::i32, llvm::TargetLowering::DAGCombinerInfo::isBeforeLegalize(), and selectMSUB().
Referenced by llvm::MipsSETargetLowering::PerformDAGCombine().
static SDValue performVSELECTCombine (SDNode * N, SelectionDAG & DAG) static
Definition at line 883 of file MipsSEISelLowering.cpp.
References llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::EVT::is128BitVector(), llvm::EVT::isInteger(), llvm::MipsISD::SELECT_CC_DSP, llvm::ISD::SETCC, llvm::MipsISD::SETCC_DSP, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::NVPTX::PTXLdStInstCode::Signed, llvm::MVT::v2i16, llvm::MVT::v4i8, llvm::MipsISD::VSMAX, llvm::MipsISD::VSMIN, llvm::MipsISD::VUMAX, and llvm::MipsISD::VUMIN.
Referenced by llvm::MipsSETargetLowering::PerformDAGCombine().
static SDValue performXORCombine (SDNode * N, SelectionDAG & DAG, const MipsSubtarget * Subtarget) static
Definition at line 939 of file MipsSEISelLowering.cpp.
References llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::MipsSubtarget::hasMSA(), llvm::EVT::is128BitVector(), llvm::ISD::isBuildVectorAllOnes(), llvm::EVT::isInteger(), llvm::ISD::OR, and llvm::MipsISD::VNOR.
Referenced by llvm::MipsSETargetLowering::PerformDAGCombine().
static bool selectMADD (SDNode * ADDENode, SelectionDAG * CurDAG) static
Definition at line 293 of file MipsSEISelLowering.cpp.
References llvm::ISD::ADDC, llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getResNo(), llvm::SDValue::hasOneUse(), llvm::MVT::i32, llvm::MipsISD::MAdd, llvm::MipsISD::MAddu, llvm::MipsISD::MFHI, llvm::MipsISD::MFLO, llvm::MipsISD::MTLOHI, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ISD::SMUL_LOHI, llvm::ISD::UMUL_LOHI, llvm::MVT::Untyped, and llvm::SDValue::use_empty().
Referenced by performADDECombine().
static bool selectMSUB (SDNode * SUBENode, SelectionDAG * CurDAG) static
Definition at line 365 of file MipsSEISelLowering.cpp.
References llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SDValue::getResNo(), llvm::MVT::Glue, llvm::SDValue::hasOneUse(), llvm::MVT::i32, llvm::MipsISD::MFHI, llvm::MipsISD::MFLO, llvm::MipsISD::MSub, llvm::MipsISD::MSubu, llvm::MipsISD::MTLOHI, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::ISD::SMUL_LOHI, llvm::ISD::SUBC, llvm::ISD::UMUL_LOHI, llvm::MVT::Untyped, and llvm::SDValue::use_empty().
Referenced by performSUBECombine().
Variable Documentation
cl::opt<bool> EnableMipsTailCalls("enable-mips-tail-calls", cl::Hidden, cl::desc("MIPS: Enable tail calls."), cl::init(false)) static
Referenced by llvm::MipsSETargetLowering::EmitInstrWithCustomInserter().
cl::opt<bool> NoDPLoadStore("mno-ldc1-sdc1", cl::init(false), cl::desc("Expand double precision loads and ""stores to their single precision ""counterparts")) static
Referenced by llvm::MipsSETargetLowering::EmitInstrWithCustomInserter(), and llvm::MipsSETargetLowering::MipsSETargetLowering().