LLVM: MLxExpansionPass.cpp File Reference
LLVM API Documentation
MLxExpansionPass.cpp File Reference
#include "ARM.h"
#include "ARMBaseInstrInfo.h"
#include "ARMSubtarget.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetRegisterInfo.h"
Macros
#define DEBUG_TYPE "mlx-expansion"
Functions
STATISTIC (NumExpand,"Number of fp MLA / MLS instructions expanded")
static bool isFpMulInstruction (unsigned Opcode)
Variables
static cl::opt< bool > ForceExapnd ("expand-all-fp-mlx", cl::init(false), cl::Hidden)
static cl::opt< unsigned > ExpandLimit ("expand-limit", cl::init(~0U), cl::Hidden)
Macro Definition Documentation
#define DEBUG_TYPE "mlx-expansion"
Definition at line 15 of file MLxExpansionPass.cpp.
Function Documentation
static bool isFpMulInstruction (unsigned Opcode) static
Definition at line 198 of file MLxExpansionPass.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::MachineFunction::begin(), llvm::BuildMI(), llvm::dbgs(), DEBUG, llvm::ARMII::DomainGeneral, llvm::ARMII::DomainMask, llvm::MachineFunction::end(), llvm::MachineInstr::eraseFromParent(), ExpandLimit, ForceExapnd, llvm::getDeadRegState(), llvm::MachineInstr::getDebugLoc(), llvm::getDefRegState(), llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::TargetMachine::getInstrInfo(), llvm::getKillRegState(), llvm::MCInstrDesc::getOpcode(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::TargetMachine::getRegisterInfo(), llvm::TargetMachine::getSubtarget(), llvm::MachineFunction::getTarget(), hasRAWHazard(), i, int, llvm::MachineInstr::isBarrier(), llvm::MachineInstr::isCopy(), llvm::MachineOperand::isDead(), llvm::MachineInstr::isImplicitDef(), llvm::MachineOperand::isKill(), llvm::MachineInstr::isLabel(), llvm::ARMSubtarget::isLikeA9(), llvm::ARMSubtarget::isSwift(), llvm::A64CC::MI, MII, MRI, llvm::prior(), llvm::MachineBasicBlock::rbegin(), llvm::MachineBasicBlock::rend(), TII, and llvm::MCInstrDesc::TSFlags.
STATISTIC (NumExpand , "Number of fp MLA / MLS instructions expanded")
Variable Documentation
cl::opt<unsigned> ExpandLimit("expand-limit", cl::init(~0U), cl::Hidden) static
Referenced by isFpMulInstruction().
cl::opt<bool> ForceExapnd("expand-all-fp-mlx", cl::init(false), cl::Hidden) static
Referenced by isFpMulInstruction().