LLVM: ModuleDebugInfoPrinter.cpp File Reference
LLVM API Documentation
ModuleDebugInfoPrinter.cpp File Reference
#include "llvm/Analysis/Passes.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Assembly/Writer.h"
#include "llvm/DebugInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/Pass.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
Functions
INITIALIZE_PASS (ModuleDebugInfoPrinter,"module-debuginfo","Decodes module-level debug info", false, true) ModulePass *llvm
Function Documentation
INITIALIZE_PASS (ModuleDebugInfoPrinter , "module-debuginfo" , "Decodes module-level debug info" , false , true)
Definition at line 47 of file ModuleDebugInfoPrinter.cpp.
References llvm::DebugInfoFinder::compile_unit_begin(), llvm::DebugInfoFinder::compile_unit_end(), llvm::DebugInfoFinder::global_variable_begin(), llvm::DebugInfoFinder::global_variable_end(), I, M, llvm::DIDescriptor::print(), llvm::DebugInfoFinder::processModule(), llvm::DebugInfoFinder::subprogram_begin(), llvm::DebugInfoFinder::subprogram_end(), llvm::DebugInfoFinder::type_begin(), and llvm::DebugInfoFinder::type_end().