LLVM: MSP430ISelDAGToDAG.cpp File Reference
LLVM API Documentation
MSP430ISelDAGToDAG.cpp File Reference
#include "MSP430.h"
#include "MSP430TargetMachine.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetLowering.h"
#include "MSP430GenDAGISel.inc"
Functions
static bool isValidIndexedLoad (const LoadSDNode *LD)
Function Documentation
static bool isValidIndexedLoad (const LoadSDNode * LD) static
Definition at line 303 of file MSP430ISelDAGToDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, DEBUG, llvm::SDNode::dump(), llvm::errs(), llvm::ISD::FrameIndex, llvm::LSBaseSDNode::getAddressingMode(), llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::LoadSDNode::getExtensionType(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::LoadSDNode::getOffset(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::EVT::getSimpleVT(), llvm::SDNode::getValueType(), llvm::SDValue::hasOneUse(), llvm::SDNode::hasOneUse(), llvm::MVT::i16, llvm::MVT::i8, llvm::SDNode::isMachineOpcode(), llvm::A64DB::LD, llvm::ISD::LOAD, N, llvm::ISD::NON_EXTLOAD, llvm::ISD::OR, llvm::MVT::Other, llvm::ISD::POST_INC, llvm::MCID::Select, llvm::SDNode::setNodeId(), llvm::MVT::SimpleTy, llvm::ISD::SUB, and llvm::ISD::XOR.