LLVM: llvm::APIntOps Namespace Reference
LLVM API Documentation
llvm::APIntOps Namespace Reference
Functions
APInt smin (const APInt &A, const APInt &B)
Determine the smaller of two APInts considered to be signed.
APInt smax (const APInt &A, const APInt &B)
Determine the larger of two APInts considered to be signed.
APInt umin (const APInt &A, const APInt &B)
Determine the smaller of two APInts considered to be signed.
APInt umax (const APInt &A, const APInt &B)
Determine the larger of two APInts considered to be unsigned.
bool isIntN (unsigned N, const APInt &APIVal)
Check if the specified APInt has a N-bits unsigned integer value.
bool isSignedIntN (unsigned N, const APInt &APIVal)
Check if the specified APInt has a N-bits signed integer value.
bool isMask (unsigned numBits, const APInt &APIVal)
bool isShiftedMask (unsigned numBits, const APInt &APIVal)
Return true if the argument APInt value contains a sequence of ones with the remainder zero.
APInt byteSwap (const APInt &APIVal)
Returns a byte-swapped representation of the specified APInt Value.
unsigned logBase2 (const APInt &APIVal)
Returns the floor log base 2 of the specified APInt value.
APInt GreatestCommonDivisor (const APInt &Val1, const APInt &Val2)
Compute GCD of two APInt values.
double RoundAPIntToDouble (const APInt &APIVal)
Converts the given APInt to a double value.
double RoundSignedAPIntToDouble (const APInt &APIVal)
Converts the given APInt to a double value.
float RoundAPIntToFloat (const APInt &APIVal)
Converts the given APInt to a float vlalue.
float RoundSignedAPIntToFloat (const APInt &APIVal)
Converts the given APInt to a float value.
APInt RoundDoubleToAPInt (double Double, unsigned width)
Converts the given double value into a APInt.
APInt RoundFloatToAPInt (float Float, unsigned width)
Converts a float value into a APInt.
APInt ashr (const APInt &LHS, unsigned shiftAmt)
Arithmetic right-shift function.
APInt lshr (const APInt &LHS, unsigned shiftAmt)
Logical right-shift function.
APInt shl (const APInt &LHS, unsigned shiftAmt)
Left-shift function.
APInt sdiv (const APInt &LHS, const APInt &RHS)
Signed division function for APInt.
APInt udiv (const APInt &LHS, const APInt &RHS)
Unsigned division function for APInt.
APInt srem (const APInt &LHS, const APInt &RHS)
Function for signed remainder operation.
APInt urem (const APInt &LHS, const APInt &RHS)
Function for unsigned remainder operation.
APInt mul (const APInt &LHS, const APInt &RHS)
Function for multiplication operation.
APInt add (const APInt &LHS, const APInt &RHS)
Function for addition operation.
APInt sub (const APInt &LHS, const APInt &RHS)
Function for subtraction operation.
APInt And (const APInt &LHS, const APInt &RHS)
Bitwise AND function for APInt.
APInt Or (const APInt &LHS, const APInt &RHS)
Bitwise OR function for APInt.
APInt Xor (const APInt &LHS, const APInt &RHS)
Bitwise XOR function for APInt.
APInt Not (const APInt &APIVal)
Bitwise complement function.
Function Documentation
APInt llvm::APIntOps::add (const APInt & LHS, const APInt & RHS) inline
Function for addition operation.
Performs addition on APInt values.
Definition at line 1829 of file APInt.h.
Referenced by llvm::APInt::abs().
APInt llvm::APIntOps::And (const APInt & LHS, const APInt & RHS) inline
Bitwise AND function for APInt.
Performs bitwise AND operation on APInt LHS and APInt RHS.
Definition at line 1840 of file APInt.h.
Referenced by areAllUsesIn(), buildMultiplyTree(), BuildNew(), CanEvaluateSExtd(), CanEvaluateShifted(), CanEvaluateShuffled(), CanEvaluateTruncated(), CanEvaluateZExtd(), CollectBSwapParts(), collectFailStats(), llvm::ComputeMaskedBits(), llvm::ComputeNumSignBits(), ComputeSpeculationCost(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCompareInstOperands(), ConvertAtomicSynchScope(), llvm::SystemZInstrInfo::convertToThreeAddress(), llvm::MCBinaryExpr::CreateAnd(), createReplacementInstr(), cse(), DecomposeSimpleLinearExpr(), deleteIfDeadInstruction(), ExtendUsesToFormExtLoad(), ExtractConstantBytes(), FindLIVLoopCondition(), llvm::SelectionDAGBuilder::FindMergedConditions(), llvm::FoldBranchToCommonDest(), llvm::InstCombiner::FoldICmpShrCst(), FoldMaskAndShiftToExtract(), FoldMaskAndShiftToScale(), llvm::InstCombiner::FoldOrOfICmps(), llvm::InstCombiner::FoldShiftByConstant(), llvm::ScalarEvolution::forgetValue(), ftostr(), GatherConstantCompares(), llvm::ConstantExpr::get(), llvm::ConstantExpr::getAnd(), llvm::ConstantExpr::getBinOpAbsorber(), llvm::ConstantExpr::getBinOpIdentity(), llvm::ExecutionEngine::getConstantValue(), GetDecodedBinaryOpcode(), GetEncodedBinaryOpcode(), getFCmpValue(), llvm::LLLexer::getFilename(), llvm::objcarc::GetInstructionClass(), getKnownConstant(), llvm::Instruction::getOpcodeName(), getReductionBinOp(), GetSelectFoldableConstant(), GetSelectFoldableOperands(), GetShiftedValue(), llvm::ScalarEvolution::getSignedRange(), llvm::BinaryOperator::init(), InstructionDereferencesPointer(), llvm::TargetLoweringBase::InstructionOpcodeToISD(), isAllOnes(), llvm::Instruction::isAssociative(), llvm::Instruction::isCommutative(), llvm::DenseMapInfo< Expression >::isEqual(), llvm::Instruction::isIdempotent(), llvm::X86TargetLowering::isIntegerTypeFTOL(), isLikelyComplexAddressComputation(), isLoopInvariant(), isRunOfOnes(), isTruncateOf(), LeftDistributesOverRight(), nvptx::LowerConstant(), lowerConstant(), LowerZERO_EXTEND(), matchVectorSplittingReduction(), OptimizeAndOrXor(), PrintOps(), llvm::FastISel::SelectOperator(), llvm::SelectionDAGBuilder::ShouldEmitAsBranches(), shouldSpeculateInstrs(), ShrinkDemandedConstant(), SimplifyAndInst(), SimplifyBinOp(), SimplifyBranchOnICmpChain(), llvm::SimplifyInstruction(), SimplifyOrInst(), llvm::TargetLowering::SimplifySetCC(), SimplifyXorInst(), SymbolicallyEvaluateBinop(), useSinCos(), llvm::Interpreter::visitBinaryOperator(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::Interpreter::visitInsertValueInst(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitSelectInstWithICmp(), llvm::InstCombiner::visitXor(), llvm::InstCombiner::visitZExt(), and MarkPendingLoopPredicate::~MarkPendingLoopPredicate().
APInt llvm::APIntOps::ashr (const APInt & LHS, unsigned shiftAmt) inline
Arithmetic right-shift function.
Arithmetic right-shift the APInt by shiftAmt.
Definition at line 1783 of file APInt.h.
References llvm::APInt::ashr().
Referenced by llvm::LLLexer::getFilename(), and llvm::ScalarEvolution::getSignedRange().
APInt llvm::APIntOps::byteSwap (const APInt & APIVal) inline
Returns a byte-swapped representation of the specified APInt Value.
Definition at line 1729 of file APInt.h.
References llvm::APInt::byteSwap().
APInt llvm::APIntOps::GreatestCommonDivisor (const APInt & Val1, const APInt & Val2)
Compute GCD of two APInt values.
This function returns the greatest common divisor of the two APInt values using Euclid's algorithm.
Returns
the greatest common divisor of Val1 and Val2
Definition at line 804 of file APInt.cpp.
References llvm::ARM_PROC::A, B, T, and urem().
Referenced by gcd(), getConstantPart(), and logBase2().
bool llvm::APIntOps::isIntN (unsigned N, const APInt & APIVal) inline
Check if the specified APInt has a N-bits unsigned integer value.
Definition at line 1708 of file APInt.h.
References llvm::APInt::isIntN().
bool llvm::APIntOps::isMask (unsigned numBits, const APInt & APIVal) inline
Returns
true if the argument APInt value is a sequence of ones starting at the least significant bit with the remainder zero.
Definition at line 1717 of file APInt.h.
References llvm::APInt::getBitWidth(), and llvm::APInt::getLowBitsSet().
Referenced by llvm::ScalarEvolution::getSignedRange(), isConstantSplatVector(), and isShiftedMask().
bool llvm::APIntOps::isShiftedMask (unsigned numBits, const APInt & APIVal) inline
Return true if the argument APInt value contains a sequence of ones with the remainder zero.
Definition at line 1724 of file APInt.h.
References llvm::APInt::APInt(), and isMask().
Referenced by isRunOfOnes().
bool llvm::APIntOps::isSignedIntN (unsigned N, const APInt & APIVal) inline
Check if the specified APInt has a N-bits signed integer value.
Definition at line 1711 of file APInt.h.
References llvm::APInt::isSignedIntN().
unsigned llvm::APIntOps::logBase2 (const APInt & APIVal) inline
Returns the floor log base 2 of the specified APInt value.
Definition at line 1732 of file APInt.h.
References GreatestCommonDivisor(), and llvm::APInt::logBase2().
Referenced by isConstantSplatVector().
APInt llvm::APIntOps::lshr (const APInt & LHS, unsigned shiftAmt) inline
Logical right-shift function.
Logical right-shift the APInt by shiftAmt.
Definition at line 1790 of file APInt.h.
References llvm::APInt::lshr().
Referenced by llvm::ComputeMaskedBits(), llvm::LLLexer::getFilename(), llvm::APInt::getHiBits(), llvm::APInt::getLoBits(), llvm::ScalarEvolution::getUnsignedRange(), MatchRotateHalf(), ShrinkDemandedConstant(), and ShrinkLoadReplaceStoreWithStore().
APInt llvm::APIntOps::mul (const APInt & LHS, const APInt & RHS) inline
Function for multiplication operation.
Performs multiplication on APInt values.
Definition at line 1824 of file APInt.h.
APInt llvm::APIntOps::Not (const APInt & APIVal) inline
Bitwise complement function.
Performs a bitwise complement operation on APInt.
Definition at line 1855 of file APInt.h.
References llvm::APInt::hash_value.
Referenced by llvm::MCUnaryExpr::CreateNot(), GatherConstantCompares(), lowerFABS64(), llvm::InstCombiner::visitICmpInst(), and llvm::InstCombiner::visitOr().
APInt llvm::APIntOps::Or (const APInt & LHS, const APInt & RHS) inline
Bitwise OR function for APInt.
Performs bitwise OR operation on APInt LHS and APInt RHS.
Definition at line 1845 of file APInt.h.
Referenced by areAllUsesIn(), llvm::X86TargetLowering::BuildFILD(), buildMultiplyTree(), BuildNew(), CanEvaluateSExtd(), CanEvaluateShifted(), CanEvaluateShuffled(), CanEvaluateTruncated(), CanEvaluateZExtd(), CollectBSwapParts(), collectFailStats(), CollectInsertionElements(), llvm::ComputeMaskedBits(), llvm::ComputeNumSignBits(), ComputeSpeculationCost(), llvm::ConstantFoldBinaryInstruction(), llvm::ConstantFoldCompareInstOperands(), ConvertAtomicSynchScope(), llvm::MCBinaryExpr::CreateOr(), createReplacementInstr(), cse(), DecomposeSimpleLinearExpr(), ExtractConstantBytes(), FindLIVLoopCondition(), llvm::SelectionDAGBuilder::FindMergedConditions(), llvm::FoldBranchToCommonDest(), llvm::InstCombiner::FoldShiftByConstant(), llvm::ScalarEvolution::forgetValue(), ftostr(), GatherConstantCompares(), llvm::ConstantExpr::get(), llvm::ConstantExpr::getBinOpAbsorber(), llvm::ConstantExpr::getBinOpIdentity(), getComparePred(), llvm::ExecutionEngine::getConstantValue(), GetDecodedBinaryOpcode(), GetEncodedBinaryOpcode(), getFCmpValue(), llvm::LLLexer::getFilename(), llvm::objcarc::GetInstructionClass(), getKnownConstant(), GetLinearExpression(), llvm::Instruction::getOpcodeName(), llvm::ConstantExpr::getOr(), getReductionBinOp(), GetSelectFoldableConstant(), GetSelectFoldableOperands(), GetShiftedValue(), llvm::ScalarEvolution::getSignedRange(), llvm::BinaryOperator::init(), INITIALIZE_PASS(), InstructionDereferencesPointer(), llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::Instruction::isAssociative(), llvm::Instruction::isCommutative(), llvm::DenseMapInfo< Expression >::isEqual(), llvm::Instruction::isIdempotent(), isLikelyComplexAddressComputation(), isLoopInvariant(), isRunOfOnes(), LeftDistributesOverRight(), nvptx::LowerConstant(), lowerConstant(), lowerFABS64(), lowerFCOPYSIGN64(), maskMatters(), matchVectorSplittingReduction(), OptimizeAndOrXor(), PrintOps(), llvm::X86TargetLowering::ReplaceNodeResults(), llvm::FastISel::SelectOperator(), llvm::SelectionDAGBuilder::ShouldEmitAsBranches(), shouldSpeculateInstrs(), ShrinkDemandedConstant(), SimplifyAndInst(), SimplifyBinOp(), SimplifyBranchOnICmpChain(), llvm::SimplifyInstruction(), SimplifyOrInst(), useSinCos(), llvm::InstCombiner::visitAnd(), llvm::Interpreter::visitBinaryOperator(), llvm::SelectionDAGBuilder::visitBitTestCase(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::Interpreter::visitInsertValueInst(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitXor(), llvm::InstCombiner::visitZExt(), and MarkPendingLoopPredicate::~MarkPendingLoopPredicate().
double llvm::APIntOps::RoundAPIntToDouble (const APInt & APIVal) inline
Converts the given APInt to a double value.
Treats the APInt as an unsigned value for conversion purposes.
Definition at line 1745 of file APInt.h.
References llvm::APInt::roundToDouble().
Referenced by RoundAPIntToFloat(), and llvm::Interpreter::visitAShr().
float llvm::APIntOps::RoundAPIntToFloat (const APInt & APIVal) inline
Converts the given APInt to a float vlalue.
Definition at line 1757 of file APInt.h.
References RoundAPIntToDouble().
Referenced by llvm::Interpreter::visitAShr().
APInt llvm::APIntOps::RoundDoubleToAPInt (double Double, unsigned width)
Converts the given double value into a APInt.
This function convert a double value to an APInt value.
Definition at line 815 of file APInt.cpp.
References llvm::APInt::APInt(), llvm::Intrinsic::exp, I, llvm::APInt::shl(), and T.
Referenced by llvm::ExecutionEngine::getConstantValue(), RoundFloatToAPInt(), RoundSignedAPIntToFloat(), and llvm::Interpreter::visitAShr().
APInt llvm::APIntOps::RoundFloatToAPInt (float Float, unsigned width) inline
Converts a float value into a APInt.
Converts a float value into an APInt value.
Definition at line 1776 of file APInt.h.
References RoundDoubleToAPInt().
Referenced by llvm::ExecutionEngine::getConstantValue(), and llvm::Interpreter::visitAShr().
double llvm::APIntOps::RoundSignedAPIntToDouble (const APInt & APIVal) inline
Converts the given APInt to a double value.
Treats the APInt as a signed value for conversion purposes.
Definition at line 1752 of file APInt.h.
References llvm::APInt::signedRoundToDouble().
Referenced by llvm::Interpreter::visitAShr().
float llvm::APIntOps::RoundSignedAPIntToFloat (const APInt & APIVal) inline
Converts the given APInt to a float value.
Treast the APInt as a signed value for conversion purposes.
Definition at line 1764 of file APInt.h.
References RoundDoubleToAPInt(), and llvm::APInt::signedRoundToDouble().
Referenced by llvm::Interpreter::visitAShr().
APInt llvm::APIntOps::sdiv (const APInt & LHS, const APInt & RHS) inline
Signed division function for APInt.
Signed divide APInt LHS by APInt RHS.
Definition at line 1804 of file APInt.h.
References llvm::APInt::sdiv().
Referenced by sdiv().
APInt llvm::APIntOps::shl (const APInt & LHS, unsigned shiftAmt) inline
Left-shift function.
Left-shift the APInt by shiftAmt.
Definition at line 1797 of file APInt.h.
References llvm::APInt::shl().
Referenced by llvm::LLLexer::getFilename(), llvm::APInt::getLoBits(), llvm::ScalarEvolution::getSignedRange(), llvm::ScalarEvolution::getUnsignedRange(), insertInteger(), and This().
APInt llvm::APIntOps::smax (const APInt & A, const APInt & B) inline
Determine the larger of two APInts considered to be signed.
Definition at line 1699 of file APInt.h.
References B, and llvm::APInt::sgt().
Referenced by llvm::ScalarEvolution::getSignedRange(), llvm::ScalarEvolution::getSMaxExpr(), llvm::ConstantRange::smax(), and MarkPendingLoopPredicate::~MarkPendingLoopPredicate().
APInt llvm::APIntOps::smin (const APInt & A, const APInt & B) inline
Determine the smaller of two APInts considered to be signed.
Definition at line 1696 of file APInt.h.
References B, and llvm::APInt::slt().
Referenced by llvm::ScalarEvolution::getSignedRange(), and MarkPendingLoopPredicate::~MarkPendingLoopPredicate().
APInt llvm::APIntOps::srem (const APInt & LHS, const APInt & RHS) inline
Function for signed remainder operation.
Signed remainder operation on APInt.
Definition at line 1814 of file APInt.h.
References llvm::APInt::srem().
Referenced by srem().
APInt llvm::APIntOps::sub (const APInt & LHS, const APInt & RHS) inline
Function for subtraction operation.
Performs subtraction on APInt values.
Definition at line 1834 of file APInt.h.
APInt llvm::APIntOps::udiv (const APInt & LHS, const APInt & RHS) inline
Unsigned division function for APInt.
Unsigned divide APInt LHS by APInt RHS.
Definition at line 1809 of file APInt.h.
References llvm::APInt::udiv().
Referenced by llvm::LLLexer::getFilename(), llvm::SCEVAddRecExpr::getNumIterationsInRange(), and llvm::Interpreter::visitBinaryOperator().
APInt llvm::APIntOps::umax (const APInt & A, const APInt & B) inline
Determine the larger of two APInts considered to be unsigned.
Definition at line 1705 of file APInt.h.
References B, and llvm::APInt::ugt().
Referenced by llvm::ConstantRange::binaryOr(), llvm::LLLexer::getFilename(), llvm::ScalarEvolution::getUMaxExpr(), llvm::ScalarEvolution::getUnsignedRange(), llvm::ConstantRange::umax(), and MarkPendingLoopPredicate::~MarkPendingLoopPredicate().
APInt llvm::APIntOps::umin (const APInt & A, const APInt & B) inline
Determine the smaller of two APInts considered to be signed.
Definition at line 1702 of file APInt.h.
References B, and llvm::APInt::ult().
Referenced by llvm::ConstantRange::binaryAnd(), llvm::LLLexer::getFilename(), llvm::ScalarEvolution::getUnsignedRange(), and MarkPendingLoopPredicate::~MarkPendingLoopPredicate().
APInt llvm::APIntOps::urem (const APInt & LHS, const APInt & RHS) inline
Function for unsigned remainder operation.
Unsigned remainder operation on APInt.
Definition at line 1819 of file APInt.h.
References llvm::APInt::urem().
Referenced by llvm::LLLexer::getFilename(), GreatestCommonDivisor(), SolveLinEquationWithOverflow(), and llvm::Interpreter::visitBinaryOperator().
APInt llvm::APIntOps::Xor (const APInt & LHS, const APInt & RHS) inline
Bitwise XOR function for APInt.
Performs bitwise XOR operation on APInt.
Definition at line 1850 of file APInt.h.
Referenced by areAllUsesIn(), buildMultiplyTree(), BuildNew(), CanEvaluateSExtd(), CanEvaluateShifted(), CanEvaluateShuffled(), CanEvaluateTruncated(), CanEvaluateZExtd(), collectFailStats(), llvm::ComputeMaskedBits(), llvm::ComputeNumSignBits(), ComputeSpeculationCost(), llvm::ConstantFoldBinaryInstruction(), ConvertAtomicSynchScope(), createAndInstr(), llvm::BinaryOperator::CreateNot(), createReplacementInstr(), llvm::MCBinaryExpr::CreateXor(), cse(), DecomposeSimpleLinearExpr(), llvm::InstCombiner::FoldOrOfICmps(), llvm::InstCombiner::FoldOrWithConstants(), llvm::InstCombiner::FoldShiftByConstant(), ftostr(), llvm::ConstantExpr::get(), llvm::ConstantExpr::getBinOpIdentity(), llvm::ExecutionEngine::getConstantValue(), GetDecodedBinaryOpcode(), GetEncodedBinaryOpcode(), getFCmpValue(), llvm::LLLexer::getFilename(), llvm::objcarc::GetInstructionClass(), getKnownConstant(), llvm::ConstantExpr::getNot(), llvm::Instruction::getOpcodeName(), getReductionBinOp(), GetSelectFoldableConstant(), GetSelectFoldableOperands(), GetShiftedValue(), llvm::ScalarEvolution::getSignedRange(), llvm::ConstantExpr::getXor(), hasAddressTakenAndUsed(), llvm::BinaryOperator::init(), llvm::TargetLoweringBase::InstructionOpcodeToISD(), llvm::Instruction::isAssociative(), llvm::Instruction::isCommutative(), llvm::DenseMapInfo< Expression >::isEqual(), isLikelyComplexAddressComputation(), isLoopInvariant(), llvm::Instruction::isNilpotent(), llvm::BinaryOperator::isNot(), isOpcWithIntImmediate(), isRunOfOnes(), LeftDistributesOverRight(), nvptx::LowerConstant(), lowerConstant(), llvm::PatternMatch::not_match< LHS_t >::match(), matchVectorSplittingReduction(), OptimizeAndOrXor(), llvm::FastISel::SelectOperator(), shouldSpeculateInstrs(), ShrinkDemandedConstant(), SimplifyAndInst(), SimplifyBinOp(), llvm::SimplifyInstruction(), SimplifyXorInst(), llvm::InstCombiner::visitAnd(), llvm::Interpreter::visitBinaryOperator(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitICmpInstWithInstAndIntCst(), llvm::Interpreter::visitInsertValueInst(), llvm::InstCombiner::visitOr(), llvm::InstCombiner::visitXor(), and llvm::InstCombiner::visitZExt().