LLVM: llvm::sys::path Namespace Reference
LLVM API Documentation
llvm::sys::path Namespace Reference
Classes
class const_iterator
Path iterator.
Functions
Lexical Modifiers
void remove_filename (SmallVectorImpl< char > &path)
Remove the last component from path unless it is the root dir.
void replace_extension (SmallVectorImpl< char > &path, const Twine &extension)
Replace the file extension of path with extension.
void append (SmallVectorImpl< char > &path, const Twine &a, const Twine &b="", const Twine &c="", const Twine &d="")
Append to path.
void append (SmallVectorImpl< char > &path, const_iterator begin, const_iterator end)
Append to path.
Transforms (or some other better name)
void native (const Twine &path, SmallVectorImpl< char > &result)
void native (SmallVectorImpl< char > &path)
Lexical Observers
const StringRef root_name (StringRef path)
Get root name.
const StringRef root_directory (StringRef path)
Get root directory.
const StringRef root_path (StringRef path)
Get root path.
const StringRef relative_path (StringRef path)
Get relative path.
const StringRef parent_path (StringRef path)
Get parent path.
const StringRef filename (StringRef path)
Get filename.
const StringRef stem (StringRef path)
Get stem.
const StringRef extension (StringRef path)
Get extension.
bool is_separator (char value)
Check whether the given char is a path separator on the host OS.
void system_temp_directory (bool erasedOnReboot, SmallVectorImpl< char > &result)
Get the typical temporary directory for the system, e.g., "/var/tmp" or "C:/TEMP".
bool has_root_name (const Twine &path)
Has root name?
bool has_root_directory (const Twine &path)
Has root directory?
bool has_root_path (const Twine &path)
Has root path?
bool has_relative_path (const Twine &path)
Has relative path?
bool has_parent_path (const Twine &path)
Has parent path?
bool has_filename (const Twine &path)
Has filename?
bool has_stem (const Twine &path)
Has stem?
bool has_extension (const Twine &path)
Has extension?
bool is_absolute (const Twine &path)
Is path absolute?
bool is_relative (const Twine &path)
Is path relative?
Lexical Component Iterator
typedef std::reverse_iterator< const_iterator > reverse_iterator
const_iterator begin (StringRef path)
Get begin iterator over path.
const_iterator end (StringRef path)
Get end iterator over path.
reverse_iterator rbegin (StringRef path)
Get reverse begin iterator over path.
reverse_iterator rend (StringRef path)
Get reverse end iterator over path.
Typedef Documentation
typedef std::reverse_iterator<const_iterator> llvm::sys::path::reverse_iterator
Definition at line 79 of file Path.h.
Function Documentation
void llvm::sys::path::append (SmallVectorImpl< char > & path, const Twine & a, const Twine & b = "", const Twine & c = "", const Twine & d = "")
Append to path.
/foo  + bar/f => /foo/bar/f
/foo/ + bar/f => /foo/bar/f
foo   + bar/f => foo/bar/f
Parameters
path Set to path + component.
a The component to be appended to path.
Definition at line 372 of file Path.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::StringRef::begin(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::SmallVectorBase::empty(), llvm::StringRef::end(), llvm::SmallVectorTemplateCommon< T >::end(), has_root_name(), i, is_separator(), llvm::Twine::isTriviallyEmpty(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::Twine::toStringRef().
Referenced by llvm::opt::DerivedArgList::AddFlagArg(), llvm::opt::DerivedArgList::AddJoinedArg(), llvm::opt::DerivedArgList::AddPositionalArg(), llvm::opt::DerivedArgList::AddSeparateArg(), llvm::APFloat::APFloat(), append(), llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc(), getCopyToPartsVector(), llvm::DWARFUnit::getDWOId(), llvm::DWARFDebugLine::LineTable::getFileNameByIndex(), getFileNameForCompileUnit(), llvm::jitprofiling::FilenameCache::getFullPath(), getFunctionName(), getNonDebugInstr(), llvm::SmallVectorImpl< std::pair< int, int64_t > >::insert(), llvm::sys::fs::make_absolute(), PrintQuotedString(), rend(), llvm::sys::fs::directory_entry::replace_filename(), llvm::SmallVector< llvm::cl::parser::OptionInfo, 8 >::SmallVector(), llvm::APFloat::toString(), and useFuncSeen().
void llvm::sys::path::append (SmallVectorImpl< char > & path, const_iterator begin, const_iterator end)
Append to path.
/foo  + [bar,f] => /foo/bar/f
/foo/ + [bar,f] => /foo/bar/f
foo   + [bar,f] => foo/bar/f
Parameters
path Set to path + [begin, end).
begin Start of components to append.
end One past the end of components to append.
Definition at line 413 of file Path.cpp.
References append(), llvm::sys::path::const_iterator::begin, and llvm::sys::path::const_iterator::end.
const_iterator llvm::sys::path::begin (StringRef path)
Get begin iterator over path.
Parameters
path Input path.
Returns
Iterator initialized with the first component of path.
Definition at line 173 of file Path.cpp.
References i.
Referenced by llvm::MachineBasicBlock::addLiveIn(), llvm::PressureDiff::addPressureChange(), llvm::SmallVectorImpl< std::pair< int, int64_t > >::assign(), llvm::ilist< SparseBitVectorElement< ElementSize > >::assign(), llvm::AttributeSet::begin(), llvm::ScheduleDAGMI::bottom(), canBeHidden(), llvm::SmallVectorTemplateCommon< std::pair< int, int64_t > >::capacity(), llvm::opt::ArgList::ClaimAllArgs(), llvm::SmallVectorImpl< std::pair< int, int64_t > >::clear(), llvm::iplist< Argument >::clear(), CloneLoop(), CollectSubexprs(), llvm::DomTreeNodeBase< llvm::MachineBasicBlock >::compare(), llvm::ImmutableList< T >::contains(), llvm::APFloat::convertFromZeroExtendedInteger(), llvm::createFunctionAttrsPass(), llvm::createGlobalsModRefPass(), llvm::SmallVectorTemplateCommon< std::pair< int, int64_t > >::data(), llvm::Function::dropAllReferences(), llvm::ScheduleDAGMI::dumpSchedule(), llvm::DwarfUnits::emitAddresses(), EmitCamlGlobal(), llvm::EmitUnwindCode(), llvm::MachineInstrSpan::empty(), llvm::AttributeSetNode::end(), llvm::ScheduleDAGInstrs::end(), llvm::SparseSet< unsigned, llvm::VirtReg2IndexFunctor >::erase(), llvm::SmallVectorImpl< std::pair< int, int64_t > >::erase(), llvm::iplist< Argument >::erase(), llvm::iplist< Argument >::erase_if(), llvm::opt::ArgList::eraseArg(), llvm::CodeExtractor::extractCodeRegion(), llvm::DwarfAccelTable::FinalizeTable(), llvm::MCFunction::find(), llvm::DWARFDebugAranges::findAddress(), llvm::SparseSet< unsigned, llvm::VirtReg2IndexFunctor >::findIndex(), llvm::UnOpInit::Fold(), llvm::SmallVectorTemplateCommon< std::pair< int, int64_t > >::front(), llvm::AttributeSetNode::getAlignment(), llvm::RecordKeeper::getAllDerivedDefinitions(), llvm::AttributeSetNode::getAsString(), llvm::AttributeSetNode::getAttribute(), llvm::MCObjectStreamer::getCurrentFragment(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::ExecutionEngine::getGlobalValueAtAddress(), llvm::opt::ArgList::getLastArg(), llvm::R600RegisterInfo::getReservedRegs(), llvm::PPCRegisterInfo::getReservedRegs(), llvm::MipsRegisterInfo::getReservedRegs(), llvm::AttributeSetNode::getStackAlignment(), llvm::SmallVectorTemplateBase< T, isPodLike >::grow(), llvm::AttributeSetNode::hasAttribute(), llvm::ilist< SparseBitVectorElement< ElementSize > >::ilist(), llvm::Registry< T, U >::listener::init(), INITIALIZE_PASS(), llvm::SmallVectorImpl< std::pair< int, int64_t > >::insert(), llvm::iplist< Argument >::insertAfter(), isAlwaysFoldable(), isIdentifierChar(), isNopCopy(), IsPointerOffset(), isSimpleLoadStore(), isStridedPtr(), llvm::PPCSubtarget::isSVR4ABI(), llvm::LiveRange::isZeroLength(), llvm::linkErlangGCPrinter(), llvm::iplist< Argument >::merge(), llvm::GraphTraits< RegionInfo * >::nodes_begin(), llvm::PooledStringPtr::operator*(), llvm::TargetRegistry::iterator::operator->(), llvm::SmallVectorImpl< std::pair< int, int64_t > >::operator<(), llvm::SmallVectorImpl< T >::operator=(), llvm::SmallVectorImpl< std::pair< int, int64_t > >::operator==(), llvm::SmallVectorTemplateCommon< std::pair< int, int64_t > >::operator[](), llvm::iplist< Argument >::pop_front(), llvm::MIBundleBuilder::prepend(), llvm::DominanceFrontierBase::print(), llvm::DwarfAccelTable::print(), llvm::LoopBase< BlockT, LoopT >::print(), llvm::opt::OptTable::PrintHelp(), llvm::AttributeSetNode::Profile(), ProfitableToMerge(), llvm::iplist< Argument >::push_front(), llvm::ilist< SparseBitVectorElement< ElementSize > >::push_front(), readExponent(), llvm::PMDataManager::removeNotPreservedAnalysis(), llvm::SmallVectorTemplateCommon< std::pair< int, int64_t > >::rend(), llvm::iplist< Argument >::rend(), llvm::SmallVectorImpl< std::pair< int, int64_t > >::resize(), llvm::ilist< SparseBitVectorElement< ElementSize > >::resize(), llvm::BitsInit::resolveReferences(), llvm::ScheduleDAGMI::schedule(), llvm::SmallVectorImpl< std::pair< int, int64_t > >::set_size(), llvm::SmallVectorTemplateCommon< std::pair< int, int64_t > >::size(), llvm::iplist< Argument >::size(), skipLeadingZeroesAndAnyDot(), AllocaSlices::SliceBuilder::SliceBuilder(), sortOpts(), llvm::SmallVectorImpl< T >::swap(), llvm::iplist< Argument >::unique(), llvm::UnrollLoop(), llvm::UnrollRuntimeLoopProlog(), llvm::LoopBase< BlockT, LoopT >::verifyLoop(), llvm::LoopBase< BlockT, LoopT >::verifyLoopNest(), llvm::AntiDepBreaker::~AntiDepBreaker(), and llvm::SmallVectorImpl< std::pair< int, int64_t > >::~SmallVectorImpl().
const_iterator llvm::sys::path::end (StringRef path)
Get end iterator over path.
Parameters
path Input path.
Returns
Iterator initialized to the end of path.
Definition at line 181 of file Path.cpp.
References i, and llvm::StringRef::size().
Referenced by llvm::MachineBasicBlock::addLiveIn(), llvm::JIT::addPointerToBasicBlock(), llvm::PressureDiff::addPressureChange(), llvm::LiveRange::advanceTo(), llvm::SmallVectorImpl< std::pair< int, int64_t > >::append(), llvm::MIBundleBuilder::append(), llvm::SmallVectorImpl< std::pair< int, int64_t > >::assign(), llvm::ilist< SparseBitVectorElement< ElementSize > >::assign(), llvm::SmallVectorTemplateCommon< std::pair< int, int64_t > >::back(), llvm::ScopedHashTable< K, V, KInfo, AllocatorTy >::begin(), llvm::ScheduleDAGMI::bottom(), llvm::PBQPBuilderWithCoalescing::build(), canBeFeederToNewValueJump(), canBeHidden(), canCompareBeNewValueJump(), llvm::yaml::Output::canElideEmptySequence(), llvm::MachineBasicBlock::canFallThrough(), llvm::LiveIntervals::checkRegMaskInterference(), llvm::opt::ArgList::ClaimAllArgs(), llvm::SmallVectorImpl< std::pair< int, int64_t > >::clear(), llvm::iplist< Argument >::clear(), CollectSubexprs(), llvm::DomTreeNodeBase< llvm::MachineBasicBlock >::compare(), llvm::ImmutableList< T >::contains(), llvm::LiveRange::Segment::contains(), llvm::LiveRange::Segment::containsInterval(), llvm::APFloat::convertFromZeroExtendedInteger(), llvm::SparseSet< unsigned, llvm::VirtReg2IndexFunctor >::count(), llvm::StringMap< std::pair< llvm::Type *, llvm::SMLoc > >::count(), llvm::createFunctionAttrsPass(), llvm::createGlobalsModRefPass(), llvm::JIT::createJIT(), llvm::Function::dropAllReferences(), llvm::DWARFDebugArangeSet::dump(), llvm::DWARFDebugLine::LineTable::dump(), llvm::ScheduleDAGMI::dumpSchedule(), llvm::DwarfUnits::emitAddresses(), EmitCamlGlobal(), llvm::MachineInstrSpan::empty(), llvm::encode_leb128(), llvm::ScheduleDAGInstrs::end(), llvm::AttributeSet::end(), llvm::SparseSet< unsigned, llvm::VirtReg2IndexFunctor >::erase(), llvm::StringMap< std::pair< llvm::Type *, llvm::SMLoc > >::erase(), llvm::SmallVectorImpl< std::pair< int, int64_t > >::erase(), llvm::iplist< Argument >::erase(), llvm::iplist< Argument >::erase_if(), llvm::opt::ArgList::eraseArg(), llvm::UnwindOpcodeAssembler::Finalize(), llvm::MCFunction::find(), llvm::StringMap< std::pair< llvm::Type *, llvm::SMLoc > >::find(), llvm::DWARFDebugAranges::findAddress(), llvm::SparseSet< unsigned, llvm::VirtReg2IndexFunctor >::findIndex(), llvm::LiveRange::FindSegmentContaining(), llvm::UnOpInit::Fold(), foo(), llvm::DWARFAbbreviationDeclarationSet::getAbbreviationDeclaration(), llvm::DWARFDebugAbbrev::getAbbreviationDeclarationSet(), llvm::AttributeSetNode::getAlignment(), llvm::RecordKeeper::getAllDerivedDefinitions(), llvm::AttributeSetNode::getAsString(), llvm::AttributeSetNode::getAttribute(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::ExecutionEngine::getGlobalValueAtAddress(), llvm::opt::ArgList::getLastArg(), llvm::MachineBasicBlock::getLastNonDebugInstr(), llvm::object::ArchiveMemberHeader::getName(), getNewValueJumpOpcode(), llvm::JIT::getPointerToBasicBlock(), llvm::R600RegisterInfo::getReservedRegs(), llvm::MipsRegisterInfo::getReservedRegs(), llvm::LiveRange::getSegmentContaining(), llvm::AttributeSetNode::getStackAlignment(), llvm::DenseMapInfo< CallValue >::getTombstoneKey(), getUs(), llvm::LiveRange::getVNInfoAt(), llvm::LiveRange::getVNInfoBefore(), llvm::SmallVectorTemplateBase< T, isPodLike >::grow(), llvm::AttributeSetNode::hasAttribute(), llvm::Registry< T, U >::listener::init(), INITIALIZE_PASS(), llvm::SparseSet< unsigned, llvm::VirtReg2IndexFunctor >::insert(), llvm::SmallVectorImpl< std::pair< int, int64_t > >::insert(), interpretDecimal(), isAlwaysFoldable(), isIdentifierChar(), isNopCopy(), llvm::SplitAnalysis::isOriginalEndpoint(), IsPointerOffset(), isSimpleLoadStore(), isStridedPtr(), llvm::PPCSubtarget::isSVR4ABI(), llvm::LiveRange::isZeroLength(), llvm::linkErlangGCPrinter(), llvm::LiveRange::liveAt(), llvm::StringMap< std::pair< llvm::Type *, llvm::SMLoc > >::lookup(), MarkBlocksLiveIn(), llvm::iplist< Argument >::merge(), llvm::GraphTraits< RegionInfo * >::nodes_end(), llvm::SmallVectorImpl< std::pair< int, int64_t > >::operator<(), llvm::SmallVectorImpl< T >::operator=(), llvm::SmallVectorImpl< std::pair< int, int64_t > >::operator==(), llvm::SmallVectorTemplateCommon< std::pair< int, int64_t > >::operator[](), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::pop_back(), llvm::SmallVectorTemplateBase< T, true >::pop_back(), llvm::iplist< Argument >::pop_back(), llvm::DominanceFrontierBase::print(), llvm::LoopBase< BlockT, LoopT >::print(), llvm::RuntimeDyldELF::processRelocationRef(), llvm::AttributeSetNode::Profile(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateBase< T, true >::push_back(), llvm::iplist< Argument >::push_back(), llvm::ilist< SparseBitVectorElement< ElementSize > >::push_back(), llvm::LiveRange::Query(), llvm::SmallVectorTemplateCommon< std::pair< int, int64_t > >::rbegin(), llvm::iplist< Argument >::rbegin(), readExponent(), llvm::iplist< Argument >::remove(), PBQP::Graph::removeNode(), llvm::PMDataManager::removeNotPreservedAnalysis(), llvm::SmallVectorImpl< std::pair< int, int64_t > >::resize(), llvm::ilist< SparseBitVectorElement< ElementSize > >::resize(), llvm::BitsInit::resolveReferences(), llvm::NVPTXAllocaHoisting::runOnFunction(), llvm::SmallVectorTemplateCommon< std::pair< int, int64_t > >::size(), llvm::iplist< Argument >::size(), skipLeadingZeroesAndAnyDot(), llvm::MachineBasicBlock::SkipPHIsAndLabels(), AllocaSlices::SliceBuilder::SliceBuilder(), sortOpts(), llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::Regex::sub(), llvm::SmallVectorImpl< T >::swap(), totalExponent(), llvm::iplist< Argument >::unique(), llvm::LoopBase< BlockT, LoopT >::verifyLoop(), llvm::LoopBase< BlockT, LoopT >::verifyLoopNest(), llvm::AntiDepBreaker::~AntiDepBreaker(), llvm::MCJIT::~MCJIT(), and llvm::SmallVectorImpl< std::pair< int, int64_t > >::~SmallVectorImpl().
const StringRef llvm::sys::path::extension (StringRef path)
Get extension.
If filename contains a dot but not solely one or two dots, result is the substring of filename starting at (and including) the last dot, and ending at the end of path. Otherwise "".
/foo/bar.txt => .txt
/foo/bar     => <empty>
/foo/.txt    => .txt
Parameters
path Input path.
Returns
The extension of path.
Definition at line 484 of file Path.cpp.
References filename(), llvm::StringRef::find_last_of(), llvm::StringRef::npos, llvm::StringRef::size(), and llvm::StringRef::substr().
Referenced by has_extension(), and rend().
const StringRef llvm::sys::path::filename (StringRef path)
Get filename.
/foo.txt    => foo.txt
.          => .
..         => ..
/          => /
Parameters
path Input path.
Returns
The filename part of path. This is defined as the last component of path.
Definition at line 467 of file Path.cpp.
References llvm::sys::path::const_iterator::end.
Referenced by llvm::sys::fs::directory_entry::assign(), extension(), llvm::sys::DynamicLibrary::getAddressOfSymbol(), llvm::MCContext::GetDwarfFile(), getFunctionName(), has_filename(), llvm::sys::DynamicLibrary::isValid(), llvm::LineReader::LineReader(), LLVMInitializeNVPTXBackendAsmPrinter(), llvm::cl::ParseCommandLineOptions(), rend(), and stem().
bool llvm::sys::path::has_extension (const Twine & path)
Has extension?
extension != ""
Parameters
path Input path.
Returns
True if the path has a extension, false otherwise.
Definition at line 607 of file Path.cpp.
References llvm::StringRef::empty(), extension(), p, and llvm::Twine::toStringRef().
Referenced by rend().
bool llvm::sys::path::has_filename (const Twine & path)
Has filename?
filename != ""
Parameters
path Input path.
Returns
True if the path has a filename, false otherwise.
Definition at line 586 of file Path.cpp.
References llvm::StringRef::empty(), filename(), p, and llvm::Twine::toStringRef().
Referenced by rend().
bool llvm::sys::path::has_parent_path (const Twine & path)
Has parent path?
parent_path != ""
Parameters
path Input path.
Returns
True if the path has a parent path, false otherwise.
Definition at line 593 of file Path.cpp.
References llvm::StringRef::empty(), p, parent_path(), and llvm::Twine::toStringRef().
Referenced by rend().
bool llvm::sys::path::has_relative_path (const Twine & path)
Has relative path?
relative_path != ""
Parameters
path Input path.
Returns
True if the path has a relative path, false otherwise.
Definition at line 579 of file Path.cpp.
References llvm::StringRef::empty(), p, relative_path(), and llvm::Twine::toStringRef().
Referenced by rend().
bool llvm::sys::path::has_root_directory (const Twine & path)
Has root directory?
root_directory != ""
Parameters
path Input path.
Returns
True if the path has a root directory, false otherwise.
Definition at line 565 of file Path.cpp.
References llvm::StringRef::empty(), p, root_directory(), and llvm::Twine::toStringRef().
Referenced by is_absolute(), llvm::sys::fs::make_absolute(), and rend().
bool llvm::sys::path::has_root_name (const Twine & path)
Has root name?
root_name != ""
Parameters
path Input path.
Returns
True if the path has a root name, false otherwise.
Definition at line 558 of file Path.cpp.
References llvm::StringRef::empty(), p, root_name(), and llvm::Twine::toStringRef().
Referenced by append(), is_absolute(), llvm::sys::fs::make_absolute(), and rend().
bool llvm::sys::path::has_root_path (const Twine & path)
Has root path?
root_path != ""
Parameters
path Input path.
Returns
True if the path has a root path, false otherwise.
Definition at line 572 of file Path.cpp.
References llvm::StringRef::empty(), p, root_path(), and llvm::Twine::toStringRef().
Referenced by rend().
bool llvm::sys::path::has_stem (const Twine & path)
Has stem?
stem != ""
Parameters
path Input path.
Returns
True if the path has a stem, false otherwise.
Definition at line 600 of file Path.cpp.
References llvm::StringRef::empty(), p, stem(), and llvm::Twine::toStringRef().
Referenced by rend().
bool llvm::sys::path::is_absolute (const Twine & path)
Is path absolute?
Parameters
path Input path.
Returns
True if the path is absolute, false if it is not.
Definition at line 614 of file Path.cpp.
References has_root_directory(), has_root_name(), p, and llvm::Twine::toStringRef().
Referenced by llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc(), llvm::DWARFDebugLine::LineTable::getFileNameByIndex(), is_relative(), PrintQuotedString(), rend(), and useFuncSeen().
bool llvm::sys::path::is_relative (const Twine & path)
Is path relative?
Parameters
path Input path.
Returns
True if the path is relative, false if it is not.
Definition at line 628 of file Path.cpp.
References is_absolute().
Referenced by llvm::DWARFUnit::getDWOId(), getFileNameForCompileUnit(), and rend().
bool llvm::sys::path::is_separator (char value)
Check whether the given char is a path separator on the host OS.
Parameters
value a character
Returns
true if value is a path separator character on the host OS
Definition at line 497 of file Path.cpp.
Referenced by append(), llvm::sys::path::const_iterator::operator++(), llvm::sys::path::const_iterator::operator--(), rend(), root_directory(), root_name(), and root_path().
void llvm::sys::path::native (const Twine & path, SmallVectorImpl< char > & result)
Convert path to the native form. This is used to give paths to users and operating system calls in the platform's normal way. For example, on Windows all '/' are converted to '\'.
Parameters
path A path that is transformed to native format.
result Holds the result of the transformation.
Definition at line 451 of file Path.cpp.
References llvm::SmallVectorImpl< T >::clear(), llvm::StringRef::data(), llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::Twine::getSingleStringRef(), llvm::Twine::isSingleStringRef(), and llvm::Twine::toVector().
Referenced by rend().
void llvm::sys::path::native (SmallVectorImpl< char > & path)
Convert path to the native form in place. This is used to give paths to users and operating system calls in the platform's normal way. For example, on Windows all '/' are converted to '\'.
Parameters
path A path that is transformed to native format.
Definition at line 461 of file Path.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), and llvm::SmallVectorTemplateCommon< T, typename >::end().
const StringRef llvm::sys::path::parent_path (StringRef path)
Get parent path.
/          => <empty>
/foo       => /
foo/../bar => foo/..
Parameters
path Input path.
Returns
The parent path of path if one exists, otherwise "".
Definition at line 419 of file Path.cpp.
References llvm::StringRef::npos, and llvm::StringRef::substr().
Referenced by llvm::sys::fs::create_directories(), llvm::MCContext::GetDwarfFile(), has_parent_path(), and rend().
reverse_iterator llvm::sys::path::rbegin (StringRef path) inline
Get reverse begin iterator over path.
Parameters
path Input path.
Returns
Iterator initialized with the first reverse component of path.
Definition at line 94 of file Path.h.
References llvm::sys::path::const_iterator::end.
Referenced by llvm::opt::ArgList::getLastArgNoClaim().
const StringRef llvm::sys::path::relative_path (StringRef path)
Get relative path.
C:\hello\world => hello\world
foo/bar        => foo/bar
/foo/bar       => foo/bar
Parameters
path Input path.
Returns
The path starting after root_path if one exists, otherwise "".
Definition at line 367 of file Path.cpp.
References root_path(), llvm::StringRef::size(), and llvm::StringRef::substr().
Referenced by has_relative_path(), llvm::sys::fs::make_absolute(), and rend().
void llvm::sys::path::remove_filename (SmallVectorImpl< char > & path)
Remove the last component from path unless it is the root dir.
directory/filename.cpp => directory/
directory/             => directory
filename.cpp           => <empty>
/                      => /
Parameters
path A path that is modified to not have a file component.
Definition at line 427 of file Path.cpp.
References llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::StringRef::npos, llvm::SmallVectorImpl< T >::set_size(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by rend(), and llvm::sys::fs::directory_entry::replace_filename().
reverse_iterator llvm::sys::path::rend (StringRef path) inline
Get reverse end iterator over path.
Parameters
path Input path.
Returns
Iterator initialized to the reverse end of path.
Definition at line 101 of file Path.h.
References append(), b, llvm::sys::path::const_iterator::begin, c, d, llvm::sys::path::const_iterator::end, extension(), filename(), has_extension(), has_filename(), has_parent_path(), has_relative_path(), has_root_directory(), has_root_name(), has_root_path(), has_stem(), is_absolute(), is_relative(), is_separator(), native(), parent_path(), relative_path(), remove_filename(), replace_extension(), result, root_directory(), root_name(), root_path(), stem(), and system_temp_directory().
Referenced by llvm::MultiClass::dump(), and llvm::opt::ArgList::getLastArgNoClaim().
void llvm::sys::path::replace_extension (SmallVectorImpl< char > & path, const Twine & extension)
Replace the file extension of path with extension.
./filename.cpp => ./filename.extension
./filename     => ./filename.extension
./             => ./.extension
Parameters
path A path that has its extension replaced with extension.
extension The extension to be added. It may be empty. It may also optionally start with a '.', if it does not, one will be prepended.
Definition at line 433 of file Path.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::StringRef::begin(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::StringRef::end(), llvm::StringRef::npos, p, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorImpl< T >::set_size(), llvm::StringRef::size(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::Twine::toStringRef().
Referenced by getFunctionName(), and rend().
const StringRef llvm::sys::path::root_directory (StringRef path)
Get root directory.
/goo/hello => /
c:/hello   => /
d/file.txt => <empty>
Parameters
path Input path.
Returns
The root directory of path if it has one, otherwise "".
Definition at line 338 of file Path.cpp.
References b, llvm::sys::path::const_iterator::begin, llvm::sys::path::const_iterator::end, llvm::StringRef::endswith(), is_separator(), and llvm::StringRef::size().
Referenced by has_root_directory(), llvm::sys::fs::make_absolute(), and rend().
const StringRef llvm::sys::path::root_name (StringRef path)
Get root name.
//net/hello => //net
c:/hello    => c: (on Windows, on other platforms nothing)
/hello      => <empty>
Parameters
path Input path.
Returns
The root name of path if it has one, otherwise "".
Definition at line 316 of file Path.cpp.
References b, llvm::sys::path::const_iterator::begin, llvm::sys::path::const_iterator::end, llvm::StringRef::endswith(), is_separator(), and llvm::StringRef::size().
Referenced by has_root_name(), llvm::sys::fs::make_absolute(), and rend().
const StringRef llvm::sys::path::root_path (StringRef path)
Get root path.
Equivalent to root_name + root_directory.
Parameters
path Input path.
Returns
The root path of path if it has one, otherwise "".
Definition at line 284 of file Path.cpp.
References b, llvm::sys::path::const_iterator::begin, llvm::sys::path::const_iterator::end, llvm::StringRef::endswith(), is_separator(), llvm::StringRef::size(), and llvm::StringRef::substr().
Referenced by has_root_path(), relative_path(), and rend().
const StringRef llvm::sys::path::stem (StringRef path)
Get stem.
If filename contains a dot but not solely one or two dots, result is the substring of filename ending at (but not including) the last dot. Otherwise it is filename.
/foo/bar.txt => bar
/foo/bar     => bar
/foo/.txt    => <empty>
/foo/.       => .
/foo/..      => ..
Parameters
path Input path.
Returns
The stem of path.
Definition at line 471 of file Path.cpp.
References filename(), llvm::StringRef::find_last_of(), llvm::StringRef::npos, llvm::StringRef::size(), and llvm::StringRef::substr().
Referenced by has_stem(), and rend().
void llvm::sys::path::system_temp_directory (bool erasedOnReboot, SmallVectorImpl< char > & result)
Get the typical temporary directory for the system, e.g., "/var/tmp" or "C:/TEMP".
Parameters
erasedOnReboot Whether to favor a path that is erased on reboot rather than one that potentially persists longer. This parameter will be ignored if the user or system has set the typical environment variable (e.g., TEMP on Windows, TMPDIR on *nix) to specify a temporary directory.
result Holds the resulting path name.
Definition at line 507 of file Path.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorImpl< T >::clear(), llvm::SmallVectorTemplateCommon< T, typename >::data(), llvm::LibFunc::getenv, llvm::SmallVectorTemplateBase< T, isPodLike >::pop_back(), llvm::SmallVectorImpl< T >::resize(), llvm::SmallVectorTemplateCommon< T, typename >::size(), and llvm::LibFunc::strlen.
Referenced by rend().