LLVM: llvm::A64Imms Namespace Reference
LLVM API Documentation
llvm::A64Imms Namespace Reference
Functions
bool isFPImm (const APFloat &Val, uint32_t &Imm8Bits)
bool isFPImm (const APFloat &Val)
bool isLogicalImm (unsigned RegWidth, uint64_t Imm, uint32_t &Bits)
bool isLogicalImmBits (unsigned RegWidth, uint32_t Bits, uint64_t &Imm)
bool isMOVZImm (int RegWidth, uint64_t Value, int &UImm16, int &Shift)
bool isMOVNImm (int RegWidth, uint64_t Value, int &UImm16, int &Shift)
bool isOnlyMOVNImm (int RegWidth, uint64_t Value, int &UImm16, int &Shift)
uint64_t decodeNeonModImm (unsigned Val, unsigned OpCmode, unsigned &EltBits)
bool decodeNeonModShiftImm (unsigned OpCmode, unsigned &ShiftImm, unsigned &ShiftOnesIn)
Function Documentation
uint64_t llvm::A64Imms::decodeNeonModImm (unsigned Val, unsigned OpCmode, unsigned & EltBits)
Definition at line 1144 of file AArch64BaseInfo.cpp.
References llvm_unreachable.
Referenced by isFPImm().
bool llvm::A64Imms::decodeNeonModShiftImm (unsigned OpCmode, unsigned & ShiftImm, unsigned & ShiftOnesIn)
Definition at line 1112 of file AArch64BaseInfo.cpp.
References llvm_unreachable.
Referenced by isFPImm().
bool llvm::A64Imms::isFPImm (const APFloat & Val, uint32_t & Imm8Bits)
Definition at line 872 of file AArch64BaseInfo.cpp.
References llvm::APFloat::bitcastToAPInt(), llvm::tgtok::Bits, llvm::APInt::getLimitedValue(), llvm::APFloat::getSemantics(), llvm::APFloat::isNegative(), llvm_unreachable, and llvm::APFloat::semanticsPrecision().
Referenced by getVLDSTRegisterUpdateOpcode(), and llvm::AArch64TargetLowering::LowerBUILD_VECTOR().
bool llvm::A64Imms::isFPImm (const APFloat & Val) inline
Definition at line 1116 of file AArch64BaseInfo.h.
References llvm::tgtok::Bits, decodeNeonModImm(), decodeNeonModShiftImm(), llvm::X86II::Imm8, isLogicalImm(), isLogicalImmBits(), isMOVNImm(), isMOVZImm(), isOnlyMOVNImm(), and Shift.
bool llvm::A64Imms::isLogicalImm (unsigned RegWidth, uint64_t Imm, uint32_t & Bits)
Definition at line 946 of file AArch64BaseInfo.cpp.
References llvm::CountLeadingOnes_32(), llvm::CountLeadingOnes_64(), llvm::CountTrailingOnes_64(), llvm::countTrailingZeros(), i, llvm::isMask_64(), and N.
Referenced by isFPImm(), and llvm::AArch64TargetLowering::LowerAsmOperandForConstraint().
bool llvm::A64Imms::isLogicalImmBits (unsigned RegWidth, uint32_t Bits, uint64_t & Imm)
Definition at line 1021 of file AArch64BaseInfo.cpp.
References i, and N.
Referenced by DecodeLogicalImmOperand(), isFPImm(), and llvm::AArch64InstPrinter::printLogicalImmOperand().
bool llvm::A64Imms::isMOVNImm (int RegWidth, uint64_t Value, int & UImm16, int & Shift)
Definition at line 1087 of file AArch64BaseInfo.cpp.
References isMOVZImm().
Referenced by isFPImm(), and isOnlyMOVNImm().
bool llvm::A64Imms::isMOVZImm (int RegWidth, uint64_t Value, int & UImm16, int & Shift)
Definition at line 1070 of file AArch64BaseInfo.cpp.
References i.
Referenced by isFPImm(), isMOVNImm(), and isOnlyMOVNImm().
bool llvm::A64Imms::isOnlyMOVNImm (int RegWidth, uint64_t Value, int & UImm16, int & Shift)
Definition at line 1101 of file AArch64BaseInfo.cpp.
References isMOVNImm(), and isMOVZImm().
Referenced by isFPImm().