LLVM: llvm::X86_MC Namespace Reference
LLVM API Documentation
llvm::X86_MC Namespace Reference
Functions
std::string ParseX86Triple (StringRef TT)
bool GetCpuIDAndInfo (unsigned value, unsigned *rEAX, unsigned *rEBX, unsigned *rECX, unsigned *rEDX)
bool GetCpuIDAndInfoEx (unsigned value, unsigned subleaf, unsigned *rEAX, unsigned *rEBX, unsigned *rECX, unsigned *rEDX)
void DetectFamilyModel (unsigned EAX, unsigned &Family, unsigned &Model)
unsigned getDwarfRegFlavour (StringRef TT, bool isEH)
void InitLLVM2SEHRegisterMapping (MCRegisterInfo *MRI)
MCSubtargetInfo * createX86MCSubtargetInfo (StringRef TT, StringRef CPU, StringRef FS)
Function Documentation
MCSubtargetInfo * llvm::X86_MC::createX86MCSubtargetInfo (StringRef TT, StringRef CPU, StringRef FS)
createX86MCSubtargetInfo - Create a X86 MCSubtargetInfo instance. This is exposed so Asm parser, etc. do not need to go through TargetRegistry.
Definition at line 220 of file X86MCTargetDesc.cpp.
References llvm::StringRef::empty(), llvm::X86II::FS, llvm::sys::getHostCPUName(), ParseX86Triple(), llvm::StringRef::str(), and llvm::X.
Referenced by LLVMInitializeX86TargetMC().
void llvm::X86_MC::DetectFamilyModel (unsigned EAX, unsigned & Family, unsigned & Model)
Definition at line 185 of file X86MCTargetDesc.cpp.
Referenced by llvm::X86Subtarget::AutoDetectSubtargetFeatures().
bool llvm::X86_MC::GetCpuIDAndInfo (unsigned value, unsigned * rEAX, unsigned * rEBX, unsigned * rECX, unsigned * rEDX)
GetCpuIDAndInfo - Execute the specified cpuid and return the 4 values in the specified arguments. If we can't run cpuid on the host, return true.
Definition at line 58 of file X86MCTargetDesc.cpp.
References eax, ebx, ecx, esi, mov, and registers.
Referenced by llvm::X86Subtarget::AutoDetectSubtargetFeatures().
bool llvm::X86_MC::GetCpuIDAndInfoEx (unsigned value, unsigned subleaf, unsigned * rEAX, unsigned * rEBX, unsigned * rECX, unsigned * rEDX)
GetCpuIDAndInfoEx - Execute the specified cpuid with subleaf and return the 4 values in the specified arguments. If we can't run cpuid on the host, return true.
Definition at line 119 of file X86MCTargetDesc.cpp.
References eax, ebx, ecx, esi, mov, and registers.
Referenced by llvm::X86Subtarget::AutoDetectSubtargetFeatures().
unsigned llvm::X86_MC::getDwarfRegFlavour (StringRef TT, bool isEH)
Definition at line 198 of file X86MCTargetDesc.cpp.
References llvm::Triple::Cygwin, llvm::Triple::getArch(), llvm::Triple::getOS(), llvm::Triple::isOSDarwin(), llvm::Triple::MinGW32, llvm::DWARFFlavour::X86_32_DarwinEH, llvm::DWARFFlavour::X86_32_Generic, llvm::DWARFFlavour::X86_64, and llvm::Triple::x86_64.
Referenced by createX86MCRegisterInfo().
void llvm::X86_MC::InitLLVM2SEHRegisterMapping (MCRegisterInfo * MRI)
Definition at line 212 of file X86MCTargetDesc.cpp.
References llvm::MCRegisterInfo::getEncodingValue(), and llvm::MCRegisterInfo::mapLLVMRegToSEHReg().
Referenced by createX86MCRegisterInfo(), and llvm::X86RegisterInfo::X86RegisterInfo().
std::string llvm::X86_MC::ParseX86Triple (StringRef TT)
Definition at line 46 of file X86MCTargetDesc.cpp.
References llvm::X86II::FS, llvm::Triple::getArch(), and llvm::Triple::x86_64.
Referenced by createX86MCSubtargetInfo().