LLVM: nvptx Namespace Reference
LLVM API Documentation
nvptx Namespace Reference
Functions
const llvm::MCExpr * LowerConstant (const llvm::Constant *CV, llvm::AsmPrinter &AP)
Function Documentation
const MCExpr * nvptx::LowerConstant (const llvm::Constant * CV, llvm::AsmPrinter & AP)
Definition at line 119 of file NVPTXAsmPrinter.cpp.
References llvm::APIntOps::And(), llvm::ConstantFoldConstantExpression(), llvm::MCConstantExpr::Create(), llvm::MCSymbolRefExpr::Create(), llvm::MCBinaryExpr::CreateAdd(), llvm::MCBinaryExpr::CreateAnd(), llvm::MCBinaryExpr::CreateDiv(), llvm::MCBinaryExpr::CreateMod(), llvm::MCBinaryExpr::CreateMul(), llvm::MCBinaryExpr::CreateOr(), llvm::MCBinaryExpr::CreateShl(), llvm::MCBinaryExpr::CreateSub(), llvm::MCBinaryExpr::CreateXor(), llvm::dyn_cast(), llvm::AsmPrinter::GetBlockAddressSymbol(), llvm::Value::getContext(), llvm::TargetMachine::getDataLayout(), llvm::MachineFunction::getFunction(), llvm::ConstantExpr::getIntegerCast(), llvm::DataLayout::getIntPtrType(), llvm::ConstantExpr::getOpcode(), llvm::User::getOperand(), llvm::GlobalValue::getParent(), llvm::DataLayout::getPointerSizeInBits(), llvm::AsmPrinter::getSymbol(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::DataLayout::getTypeAllocSizeInBits(), llvm::Constant::isNullValue(), llvm_unreachable, llvm::AsmPrinter::MF, llvm::APIntOps::Or(), llvm::AsmPrinter::OutContext, llvm::report_fatal_error(), S, llvm::raw_string_ostream::str(), llvm::AsmPrinter::TM, llvm::WriteAsOperand(), and llvm::APIntOps::Xor().
Referenced by getOpenCLAlignment().