LLVM: llvm::zlib Namespace Reference
LLVM API Documentation
llvm::zlib Namespace Reference
Enumerations
enum CompressionLevel { NoCompression, DefaultCompression, BestSpeedCompression, BestSizeCompression }
enum Status {
StatusOK, StatusUnsupported, StatusOutOfMemory, StatusBufferTooShort,
StatusInvalidArg, StatusInvalidData
}
Functions
bool isAvailable ()
Status compress (StringRef InputBuffer, OwningPtr< MemoryBuffer > &CompressedBuffer, CompressionLevel Level=DefaultCompression)
Status uncompress (StringRef InputBuffer, OwningPtr< MemoryBuffer > &UncompressedBuffer, size_t UncompressedSize)
uint32_t crc32 (StringRef Buffer)
Enumeration Type Documentation
enum llvm::zlib::CompressionLevel
Enumerator
NoCompression
DefaultCompression
BestSpeedCompression
BestSizeCompression
Definition at line 27 of file Compression.h.
enum llvm::zlib::Status
Enumerator
StatusOK
StatusUnsupported
StatusOutOfMemory
StatusBufferTooShort
StatusInvalidArg
StatusInvalidData
Definition at line 34 of file Compression.h.
Function Documentation
zlib::Status llvm::zlib::compress (StringRef InputBuffer, OwningPtr< MemoryBuffer > & CompressedBuffer, CompressionLevel Level = DefaultCompression)
Definition at line 50 of file Compression.cpp.
References __msan_unpoison, llvm::StringRef::data(), encodeZlibCompressionLevel(), encodeZlibReturnValue(), llvm::MemoryBuffer::getBufferStart(), llvm::MemoryBuffer::getMemBufferCopy(), llvm::OwningPtr< T >::reset(), llvm::StringRef::size(), and StatusOK.
Referenced by crc32().
uint32_t llvm::zlib::crc32 (StringRef Buffer)
Definition at line 84 of file Compression.cpp.
References compress(), llvm::StringRef::data(), isAvailable(), llvm_unreachable, llvm::StringRef::size(), StatusUnsupported, and uncompress().
bool llvm::zlib::isAvailable ()
Definition at line 49 of file Compression.cpp.
Referenced by CheckForLiveRegDef(), crc32(), llvm::DWARFContextInMemory::DWARFContextInMemory(), FindCallSeqStart(), and INITIALIZE_PASS().
zlib::Status llvm::zlib::uncompress (StringRef InputBuffer, OwningPtr< MemoryBuffer > & UncompressedBuffer, size_t UncompressedSize)
Definition at line 68 of file Compression.cpp.
References __msan_unpoison, llvm::StringRef::data(), encodeZlibReturnValue(), llvm::OwningArrayPtr< T >::get(), llvm::MemoryBuffer::getBufferStart(), llvm::MemoryBuffer::getMemBufferCopy(), llvm::OwningPtr< T >::reset(), llvm::StringRef::size(), and StatusOK.
Referenced by crc32(), and llvm::DWARFContextInMemory::DWARFContextInMemory().