LLVM: llvm::ARM_PROC Namespace Reference
LLVM API Documentation
llvm::ARM_PROC Namespace Reference
Enumerations
enum IMod { IE = 2, ID = 3 }
enum IFlags { F = 1, I = 2, A = 4 }
Functions
static const char * IFlagsToString (unsigned val)
static const char * IModToString (unsigned val)
Enumeration Type Documentation
enum llvm::ARM_PROC::IFlags
Enumerator
F
I
A
Definition at line 95 of file ARMBaseInfo.h.
enum llvm::ARM_PROC::IMod
Enumerator
IE
ID
Definition at line 90 of file ARMBaseInfo.h.
Function Documentation
static const char* llvm::ARM_PROC::IFlagsToString (unsigned val) inline static
Definition at line 101 of file ARMBaseInfo.h.
References A, F(), I, and llvm_unreachable.
Referenced by llvm::ARMInstPrinter::printCPSIFlag().
static const char* llvm::ARM_PROC::IModToString (unsigned val) inline static
Definition at line 110 of file ARMBaseInfo.h.
References ID, IE, and llvm_unreachable.
Referenced by llvm::ARMInstPrinter::printCPSIMod().