LLVM: llvm::yaml Namespace Reference
LLVM API Documentation
llvm::yaml Namespace Reference
Classes
class AliasNode
Represents an alias to a Node with an anchor.
class basic_collection_iterator
This is an iterator abstraction over YAML collections shared by both sequences and maps.
class Document
A YAML Stream is a sequence of Documents. A document contains a root node.
class document_iterator
Iterator abstraction for Documents over a Stream.
struct DocumentListTraits
struct has_DocumentListTraits
class has_FlowTraits
struct has_FlowTraits< T, true >
struct has_MappingTraits
struct has_ScalarBitSetTraits
struct has_ScalarEnumerationTraits
struct has_ScalarTraits
struct has_SequenceMethodTraits
struct has_SequenceTraits
class Input
class IO
class KeyValueNode
A key and value pair. While not technically a Node under the YAML representation graph, it is easier to treat them this way.
class MappingNode
Represents a YAML map created from either a block map for a flow map.
struct MappingNormalization
struct MappingNormalizationHeap
struct MappingTraits
struct MappingTraits< COFF::header >
struct MappingTraits< COFFYAML::Object >
struct MappingTraits< COFFYAML::Relocation >
struct MappingTraits< COFFYAML::Section >
struct MappingTraits< COFFYAML::Symbol >
struct MappingTraits< ELFYAML::FileHeader >
struct MappingTraits< ELFYAML::LocalGlobalWeakSymbols >
struct MappingTraits< ELFYAML::Object >
struct MappingTraits< ELFYAML::Section >
struct MappingTraits< ELFYAML::Symbol >
struct MappingTraits< MCModuleYAML::Atom >
struct MappingTraits< MCModuleYAML::BasicBlock >
struct MappingTraits< MCModuleYAML::Function >
struct MappingTraits< MCModuleYAML::Inst >
struct MappingTraits< MCModuleYAML::Module >
struct MissingTrait
struct missingTraits
class Node
Abstract base class for all Nodes.
class NullNode
A null value.
class Output
struct SameType
struct ScalarBitSetTraits
struct ScalarBitSetTraits< COFF::Characteristics >
struct ScalarBitSetTraits< COFF::SectionCharacteristics >
struct ScalarBitSetTraits< ELFYAML::ELF_SHF >
struct ScalarEnumerationTraits
struct ScalarEnumerationTraits< COFF::MachineTypes >
struct ScalarEnumerationTraits< COFF::RelocationTypeX86 >
struct ScalarEnumerationTraits< COFF::SymbolBaseType >
struct ScalarEnumerationTraits< COFF::SymbolComplexType >
struct ScalarEnumerationTraits< COFF::SymbolStorageClass >
struct ScalarEnumerationTraits< ELFYAML::ELF_ELFCLASS >
struct ScalarEnumerationTraits< ELFYAML::ELF_ELFDATA >
struct ScalarEnumerationTraits< ELFYAML::ELF_ELFOSABI >
struct ScalarEnumerationTraits< ELFYAML::ELF_EM >
struct ScalarEnumerationTraits< ELFYAML::ELF_ET >
struct ScalarEnumerationTraits< ELFYAML::ELF_SHT >
struct ScalarEnumerationTraits< ELFYAML::ELF_STT >
struct ScalarEnumerationTraits< MCAtom::AtomKind >
class ScalarNode
A scalar node is an opaque datum that can be presented as a series of zero or more Unicode scalar values.
struct ScalarTraits
struct ScalarTraits< bool >
struct ScalarTraits< double >
struct ScalarTraits< float >
struct ScalarTraits< Hex16 >
struct ScalarTraits< Hex32 >
struct ScalarTraits< Hex64 >
struct ScalarTraits< Hex8 >
struct ScalarTraits< int16_t >
struct ScalarTraits< int32_t >
struct ScalarTraits< int64_t >
struct ScalarTraits< int8_t >
struct ScalarTraits< MCModuleYAML::OpcodeEnum >
struct ScalarTraits< MCModuleYAML::Operand >
struct ScalarTraits< object::yaml::BinaryRef >
struct ScalarTraits< StringRef >
struct ScalarTraits< uint16_t >
struct ScalarTraits< uint32_t >
struct ScalarTraits< uint64_t >
struct ScalarTraits< uint8_t >
class Scanner
Scans YAML tokens from a MemoryBuffer.
class SequenceNode
Represents a YAML sequence created from either a block sequence for a flow sequence.
struct SequenceTraits
class Stream
This class represents a YAML stream potentially containing multiple documents.
struct Token
Token - A single YAML token.
Functions
bool dumpTokens (StringRef Input, raw_ostream &)
Dump all the tokens in this stream to OS.
bool scanTokens (StringRef Input)
Scans all tokens in input without outputting anything. This is used for benchmarking the tokenizer.
std::string escape (StringRef Input)
Escape Input for a double quoted scalar.
template<class CollectionType >
CollectionType::iterator begin (CollectionType &C)
template<class CollectionType >
void skip (CollectionType &C)
template<typename T >
llvm::enable_if_c< has_ScalarEnumerationTraits< T >::value, void >::type yamlize (IO &io, T &Val, bool)
template<typename T >
llvm::enable_if_c< has_ScalarBitSetTraits< T >::value, void >::type yamlize (IO &io, T &Val, bool)
template<typename T >
llvm::enable_if_c< has_ScalarTraits< T >::value, void >::type yamlize (IO &io, T &Val, bool)
template<typename T >
llvm::enable_if_c< has_MappingTraits< T >::value, void >::type yamlize (IO &io, T &Val, bool)
template<typename T >
llvm::enable_if_c< missingTraits< T >::value, void >::type yamlize (IO &io, T &Val, bool)
template<typename T >
llvm::enable_if_c< has_SequenceTraits< T >::value, void >::type yamlize (IO &io, T &Seq, bool)
template<typename T >
llvm::enable_if_c< has_DocumentListTraits< T >::value, Input & >::type operator>> (Input &yin, T &docList)
template<typename T >
llvm::enable_if_c< has_MappingTraits< T >::value, Input & >::type operator>> (Input &yin, T &docMap)
template<typename T >
llvm::enable_if_c< has_SequenceTraits< T >::value, Input & >::type operator>> (Input &yin, T &docSeq)
template<typename T >
llvm::enable_if_c< missingTraits< T >::value, Input & >::type operator>> (Input &yin, T &docSeq)
template<typename T >
llvm::enable_if_c< has_DocumentListTraits< T >::value, Output & >::type operator<< (Output &yout, T &docList)
template<typename T >
llvm::enable_if_c< has_MappingTraits< T >::value, Output & >::type operator<< (Output &yout, T &map)
template<typename T >
llvm::enable_if_c< has_SequenceTraits< T >::value, Output & >::type operator<< (Output &yout, T &seq)
template<typename T >
llvm::enable_if_c< missingTraits< T >::value, Output & >::type operator<< (Output &yout, T &seq)
Function Documentation
template<class CollectionType > CollectionType::iterator llvm::yaml::begin (CollectionType & C)
Definition at line 323 of file YAMLParser.h.
References ret().
Referenced by llvm::yaml::MappingNode::begin(), and llvm::yaml::SequenceNode::begin().
bool llvm::yaml::dumpTokens (StringRef Input, raw_ostream & OS)
Dump all the tokens in this stream to OS.
Returns
true if there was an error, false otherwise.
Definition at line 548 of file YAMLParser.cpp.
References llvm::yaml::Scanner::getNext(), llvm::yaml::Token::Kind, llvm::yaml::Token::Range, llvm::yaml::Token::TK_Alias, llvm::yaml::Token::TK_Anchor, llvm::yaml::Token::TK_BlockEnd, llvm::yaml::Token::TK_BlockEntry, llvm::yaml::Token::TK_BlockMappingStart, llvm::yaml::Token::TK_BlockSequenceStart, llvm::yaml::Token::TK_DocumentEnd, llvm::yaml::Token::TK_DocumentStart, llvm::yaml::Token::TK_Error, llvm::yaml::Token::TK_FlowEntry, llvm::yaml::Token::TK_FlowMappingEnd, llvm::yaml::Token::TK_FlowMappingStart, llvm::yaml::Token::TK_FlowSequenceEnd, llvm::yaml::Token::TK_FlowSequenceStart, llvm::yaml::Token::TK_Key, llvm::yaml::Token::TK_Scalar, llvm::yaml::Token::TK_StreamEnd, llvm::yaml::Token::TK_StreamStart, llvm::yaml::Token::TK_Tag, llvm::yaml::Token::TK_TagDirective, llvm::yaml::Token::TK_Value, and llvm::yaml::Token::TK_VersionDirective.
std::string llvm::yaml::escape (StringRef Input)
Escape Input for a double quoted scalar.
Definition at line 642 of file YAMLParser.cpp.
References llvm::StringRef::begin(), llvm::SmallVectorTemplateCommon< T >::begin(), decodeUTF8(), encodeUTF8(), llvm::StringRef::end(), llvm::SmallVectorTemplateCommon< T >::end(), i, and llvm::utohexstr().
template<typename T > llvm::enable_if_c<has_DocumentListTraits<T>::value,Output &>::type llvm::yaml::operator<< (Output & yout, T & docList) inline
Definition at line 993 of file YAMLTraits.h.
References llvm::yaml::Output::beginDocuments(), llvm::yaml::Output::endDocuments(), i, llvm::yaml::Output::postflightDocument(), llvm::yaml::Output::preflightDocument(), size, type, and yamlize().
template<typename T > llvm::enable_if_c<has_MappingTraits<T>::value,Output &>::type llvm::yaml::operator<< (Output & yout, T & map) inline
Definition at line 1010 of file YAMLTraits.h.
References llvm::yaml::Output::beginDocuments(), llvm::yaml::Output::endDocuments(), llvm::yaml::Output::postflightDocument(), llvm::yaml::Output::preflightDocument(), type, and yamlize().
template<typename T > llvm::enable_if_c<has_SequenceTraits<T>::value,Output &>::type llvm::yaml::operator<< (Output & yout, T & seq) inline
Definition at line 1024 of file YAMLTraits.h.
References llvm::yaml::Output::beginDocuments(), llvm::yaml::Output::endDocuments(), llvm::yaml::Output::postflightDocument(), llvm::yaml::Output::preflightDocument(), type, and yamlize().
template<typename T > llvm::enable_if_c<missingTraits<T>::value,Output &>::type llvm::yaml::operator<< (Output & yout, T & seq) inline
Definition at line 1038 of file YAMLTraits.h.
template<typename T > llvm::enable_if_c<has_DocumentListTraits<T>::value,Input &>::type llvm::yaml::operator>> (Input & yin, T & docList) inline
Definition at line 946 of file YAMLTraits.h.
References llvm::yaml::Input::error(), i, llvm::yaml::Input::nextDocument(), llvm::yaml::Input::setCurrentDocument(), type, and yamlize().
template<typename T > llvm::enable_if_c<has_MappingTraits<T>::value,Input &>::type llvm::yaml::operator>> (Input & yin, T & docMap) inline
Definition at line 962 of file YAMLTraits.h.
References llvm::yaml::Input::setCurrentDocument(), type, and yamlize().
template<typename T > llvm::enable_if_c<has_SequenceTraits<T>::value,Input &>::type llvm::yaml::operator>> (Input & yin, T & docSeq) inline
Definition at line 973 of file YAMLTraits.h.
References llvm::yaml::Input::setCurrentDocument(), type, and yamlize().
template<typename T > llvm::enable_if_c<missingTraits<T>::value,Input &>::type llvm::yaml::operator>> (Input & yin, T & docSeq) inline
Definition at line 983 of file YAMLTraits.h.
References type.
bool llvm::yaml::scanTokens (StringRef Input)
Scans all tokens in input without outputting anything. This is used for benchmarking the tokenizer.
Returns
true if there was an error, false otherwise.
Definition at line 629 of file YAMLParser.cpp.
References llvm::yaml::Scanner::getNext(), llvm::yaml::Token::Kind, llvm::yaml::Token::TK_Error, and llvm::yaml::Token::TK_StreamEnd.
template<class CollectionType > void llvm::yaml::skip (CollectionType & C)
Definition at line 332 of file YAMLParser.h.
References llvm::yaml::Stream::begin(), and i.
Referenced by llvm::yaml::Scanner::failed(), llvm::yaml::MappingNode::skip(), and llvm::yaml::SequenceNode::skip().
template<typename T > llvm::enable_if_c<has_ScalarEnumerationTraits<T>::value,void>::type llvm::yaml::yamlize (IO & io, T & Val, bool)
Definition at line 446 of file YAMLTraits.h.
References llvm::yaml::IO::beginEnumScalar(), llvm::yaml::IO::endEnumScalar(), and type.
Referenced by llvm::yaml::IO::mapOptional(), operator<<(), operator>>(), and yamlize().
template<typename T > llvm::enable_if_c<has_ScalarBitSetTraits<T>::value,void>::type llvm::yaml::yamlize (IO & io, T & Val, bool)
Definition at line 454 of file YAMLTraits.h.
References llvm::yaml::IO::beginBitSetScalar(), llvm::yaml::IO::endBitSetScalar(), and type.
template<typename T > llvm::enable_if_c<has_ScalarTraits<T>::value,void>::type llvm::yaml::yamlize (IO & io, T & Val, bool)
Definition at line 467 of file YAMLTraits.h.
References llvm::StringRef::empty(), llvm::yaml::IO::getContext(), input, output, llvm::yaml::IO::outputting(), llvm::yaml::IO::scalarString(), llvm::yaml::IO::setError(), llvm::raw_string_ostream::str(), and type.
template<typename T > llvm::enable_if_c<has_MappingTraits<T>::value, void>::type llvm::yaml::yamlize (IO & io, T & Val, bool)
Definition at line 488 of file YAMLTraits.h.
References llvm::yaml::IO::beginMapping(), llvm::yaml::IO::endMapping(), and type.
template<typename T > llvm::enable_if_c<missingTraits<T>::value, void>::type llvm::yaml::yamlize (IO & io, T & Val, bool)
Definition at line 496 of file YAMLTraits.h.
References type.
template<typename T > llvm::enable_if_c<has_SequenceTraits<T>::value,void>::type llvm::yaml::yamlize (IO & io, T & Seq, bool)
Definition at line 502 of file YAMLTraits.h.
References llvm::yaml::IO::beginFlowSequence(), llvm::yaml::IO::beginSequence(), llvm::yaml::IO::endFlowSequence(), llvm::yaml::IO::endSequence(), i, llvm::yaml::IO::outputting(), llvm::yaml::IO::postflightElement(), llvm::yaml::IO::postflightFlowElement(), llvm::yaml::IO::preflightElement(), llvm::yaml::IO::preflightFlowElement(), size, and yamlize().