LLVM: llvm::dwarf Namespace Reference
LLVM API Documentation
llvm::dwarf Namespace Reference
Classes
struct PubIndexEntryDescriptor
Enumerations
enum LocationAtom {
DW_OP_addr = 0x03, DW_OP_deref = 0x06, DW_OP_const1u = 0x08, DW_OP_const1s = 0x09,
DW_OP_const2u = 0x0a, DW_OP_const2s = 0x0b, DW_OP_const4u = 0x0c, DW_OP_const4s = 0x0d,
DW_OP_const8u = 0x0e, DW_OP_const8s = 0x0f, DW_OP_constu = 0x10, DW_OP_consts = 0x11,
DW_OP_dup = 0x12, DW_OP_drop = 0x13, DW_OP_over = 0x14, DW_OP_pick = 0x15,
DW_OP_swap = 0x16, DW_OP_rot = 0x17, DW_OP_xderef = 0x18, DW_OP_abs = 0x19,
DW_OP_and = 0x1a, DW_OP_div = 0x1b, DW_OP_minus = 0x1c, DW_OP_mod = 0x1d,
DW_OP_mul = 0x1e, DW_OP_neg = 0x1f, DW_OP_not = 0x20, DW_OP_or = 0x21,
DW_OP_plus = 0x22, DW_OP_plus_uconst = 0x23, DW_OP_shl = 0x24, DW_OP_shr = 0x25,
DW_OP_shra = 0x26, DW_OP_xor = 0x27, DW_OP_skip = 0x2f, DW_OP_bra = 0x28,
DW_OP_eq = 0x29, DW_OP_ge = 0x2a, DW_OP_gt = 0x2b, DW_OP_le = 0x2c,
DW_OP_lt = 0x2d, DW_OP_ne = 0x2e, DW_OP_lit0 = 0x30, DW_OP_lit1 = 0x31,
DW_OP_lit2 = 0x32, DW_OP_lit3 = 0x33, DW_OP_lit4 = 0x34, DW_OP_lit5 = 0x35,
DW_OP_lit6 = 0x36, DW_OP_lit7 = 0x37, DW_OP_lit8 = 0x38, DW_OP_lit9 = 0x39,
DW_OP_lit10 = 0x3a, DW_OP_lit11 = 0x3b, DW_OP_lit12 = 0x3c, DW_OP_lit13 = 0x3d,
DW_OP_lit14 = 0x3e, DW_OP_lit15 = 0x3f, DW_OP_lit16 = 0x40, DW_OP_lit17 = 0x41,
DW_OP_lit18 = 0x42, DW_OP_lit19 = 0x43, DW_OP_lit20 = 0x44, DW_OP_lit21 = 0x45,
DW_OP_lit22 = 0x46, DW_OP_lit23 = 0x47, DW_OP_lit24 = 0x48, DW_OP_lit25 = 0x49,
DW_OP_lit26 = 0x4a, DW_OP_lit27 = 0x4b, DW_OP_lit28 = 0x4c, DW_OP_lit29 = 0x4d,
DW_OP_lit30 = 0x4e, DW_OP_lit31 = 0x4f, DW_OP_reg0 = 0x50, DW_OP_reg1 = 0x51,
DW_OP_reg2 = 0x52, DW_OP_reg3 = 0x53, DW_OP_reg4 = 0x54, DW_OP_reg5 = 0x55,
DW_OP_reg6 = 0x56, DW_OP_reg7 = 0x57, DW_OP_reg8 = 0x58, DW_OP_reg9 = 0x59,
DW_OP_reg10 = 0x5a, DW_OP_reg11 = 0x5b, DW_OP_reg12 = 0x5c, DW_OP_reg13 = 0x5d,
DW_OP_reg14 = 0x5e, DW_OP_reg15 = 0x5f, DW_OP_reg16 = 0x60, DW_OP_reg17 = 0x61,
DW_OP_reg18 = 0x62, DW_OP_reg19 = 0x63, DW_OP_reg20 = 0x64, DW_OP_reg21 = 0x65,
DW_OP_reg22 = 0x66, DW_OP_reg23 = 0x67, DW_OP_reg24 = 0x68, DW_OP_reg25 = 0x69,
DW_OP_reg26 = 0x6a, DW_OP_reg27 = 0x6b, DW_OP_reg28 = 0x6c, DW_OP_reg29 = 0x6d,
DW_OP_reg30 = 0x6e, DW_OP_reg31 = 0x6f, DW_OP_breg0 = 0x70, DW_OP_breg1 = 0x71,
DW_OP_breg2 = 0x72, DW_OP_breg3 = 0x73, DW_OP_breg4 = 0x74, DW_OP_breg5 = 0x75,
DW_OP_breg6 = 0x76, DW_OP_breg7 = 0x77, DW_OP_breg8 = 0x78, DW_OP_breg9 = 0x79,
DW_OP_breg10 = 0x7a, DW_OP_breg11 = 0x7b, DW_OP_breg12 = 0x7c, DW_OP_breg13 = 0x7d,
DW_OP_breg14 = 0x7e, DW_OP_breg15 = 0x7f, DW_OP_breg16 = 0x80, DW_OP_breg17 = 0x81,
DW_OP_breg18 = 0x82, DW_OP_breg19 = 0x83, DW_OP_breg20 = 0x84, DW_OP_breg21 = 0x85,
DW_OP_breg22 = 0x86, DW_OP_breg23 = 0x87, DW_OP_breg24 = 0x88, DW_OP_breg25 = 0x89,
DW_OP_breg26 = 0x8a, DW_OP_breg27 = 0x8b, DW_OP_breg28 = 0x8c, DW_OP_breg29 = 0x8d,
DW_OP_breg30 = 0x8e, DW_OP_breg31 = 0x8f, DW_OP_regx = 0x90, DW_OP_fbreg = 0x91,
DW_OP_bregx = 0x92, DW_OP_piece = 0x93, DW_OP_deref_size = 0x94, DW_OP_xderef_size = 0x95,
DW_OP_nop = 0x96, DW_OP_push_object_address = 0x97, DW_OP_call2 = 0x98, DW_OP_call4 = 0x99,
DW_OP_call_ref = 0x9a, DW_OP_form_tls_address = 0x9b, DW_OP_call_frame_cfa = 0x9c, DW_OP_bit_piece = 0x9d,
DW_OP_implicit_value = 0x9e, DW_OP_stack_value = 0x9f, DW_OP_lo_user = 0xe0, DW_OP_hi_user = 0xff,
DW_OP_GNU_push_tls_address = 0xe0, DW_OP_GNU_addr_index = 0xfb, DW_OP_GNU_const_index = 0xfc
}
enum TypeKind {
DW_ATE_address = 0x01, DW_ATE_boolean = 0x02, DW_ATE_complex_float = 0x03, DW_ATE_float = 0x04,
DW_ATE_signed = 0x05, DW_ATE_signed_char = 0x06, DW_ATE_unsigned = 0x07, DW_ATE_unsigned_char = 0x08,
DW_ATE_imaginary_float = 0x09, DW_ATE_packed_decimal = 0x0a, DW_ATE_numeric_string = 0x0b, DW_ATE_edited = 0x0c,
DW_ATE_signed_fixed = 0x0d, DW_ATE_unsigned_fixed = 0x0e, DW_ATE_decimal_float = 0x0f, DW_ATE_UTF = 0x10,
DW_ATE_lo_user = 0x80, DW_ATE_hi_user = 0xff
}
enum DecimalSignEncoding {
DW_DS_unsigned = 0x01, DW_DS_leading_overpunch = 0x02, DW_DS_trailing_overpunch = 0x03, DW_DS_leading_separate = 0x04,
DW_DS_trailing_separate = 0x05
}
enum EndianityEncoding {
DW_END_default = 0x00, DW_END_big = 0x01, DW_END_little = 0x02, DW_END_lo_user = 0x40,
DW_END_hi_user = 0xff
}
enum AccessAttribute { DW_ACCESS_public = 0x01, DW_ACCESS_protected = 0x02, DW_ACCESS_private = 0x03 }
enum VisibilityAttribute { DW_VIS_local = 0x01, DW_VIS_exported = 0x02, DW_VIS_qualified = 0x03 }
enum VirtualityAttribute { DW_VIRTUALITY_none = 0x00, DW_VIRTUALITY_virtual = 0x01, DW_VIRTUALITY_pure_virtual = 0x02 }
enum SourceLanguage {
DW_LANG_C89 = 0x0001, DW_LANG_C = 0x0002, DW_LANG_Ada83 = 0x0003, DW_LANG_C_plus_plus = 0x0004,
DW_LANG_Cobol74 = 0x0005, DW_LANG_Cobol85 = 0x0006, DW_LANG_Fortran77 = 0x0007, DW_LANG_Fortran90 = 0x0008,
DW_LANG_Pascal83 = 0x0009, DW_LANG_Modula2 = 0x000a, DW_LANG_Java = 0x000b, DW_LANG_C99 = 0x000c,
DW_LANG_Ada95 = 0x000d, DW_LANG_Fortran95 = 0x000e, DW_LANG_PLI = 0x000f, DW_LANG_ObjC = 0x0010,
DW_LANG_ObjC_plus_plus = 0x0011, DW_LANG_UPC = 0x0012, DW_LANG_D = 0x0013, DW_LANG_Python = 0x0014,
DW_LANG_lo_user = 0x8000, DW_LANG_Mips_Assembler = 0x8001, DW_LANG_hi_user = 0xffff
}
enum CaseSensitivity { DW_ID_case_sensitive = 0x00, DW_ID_up_case = 0x01, DW_ID_down_case = 0x02, DW_ID_case_insensitive = 0x03 }
enum CallingConvention {
DW_CC_normal = 0x01, DW_CC_program = 0x02, DW_CC_nocall = 0x03, DW_CC_lo_user = 0x40,
DW_CC_hi_user = 0xff
}
enum InlineAttribute { DW_INL_not_inlined = 0x00, DW_INL_inlined = 0x01, DW_INL_declared_not_inlined = 0x02, DW_INL_declared_inlined = 0x03 }
enum ArrayDimensionOrdering { DW_ORD_row_major = 0x00, DW_ORD_col_major = 0x01 }
enum DiscriminantList { DW_DSC_label = 0x00, DW_DSC_range = 0x01 }
enum LineNumberOps {
DW_LNS_extended_op = 0x00, DW_LNS_copy = 0x01, DW_LNS_advance_pc = 0x02, DW_LNS_advance_line = 0x03,
DW_LNS_set_file = 0x04, DW_LNS_set_column = 0x05, DW_LNS_negate_stmt = 0x06, DW_LNS_set_basic_block = 0x07,
DW_LNS_const_add_pc = 0x08, DW_LNS_fixed_advance_pc = 0x09, DW_LNS_set_prologue_end = 0x0a, DW_LNS_set_epilogue_begin = 0x0b,
DW_LNS_set_isa = 0x0c
}
enum LineNumberExtendedOps {
DW_LNE_end_sequence = 0x01, DW_LNE_set_address = 0x02, DW_LNE_define_file = 0x03, DW_LNE_set_discriminator = 0x04,
DW_LNE_lo_user = 0x80, DW_LNE_hi_user = 0xff
}
enum MacinfoRecordType {
DW_MACINFO_define = 0x01, DW_MACINFO_undef = 0x02, DW_MACINFO_start_file = 0x03, DW_MACINFO_end_file = 0x04,
DW_MACINFO_vendor_ext = 0xff
}
enum CallFrameInfo {
DW_CFA_extended = 0x00, DW_CFA_nop = 0x00, DW_CFA_advance_loc = 0x40, DW_CFA_offset = 0x80,
DW_CFA_restore = 0xc0, DW_CFA_set_loc = 0x01, DW_CFA_advance_loc1 = 0x02, DW_CFA_advance_loc2 = 0x03,
DW_CFA_advance_loc4 = 0x04, DW_CFA_offset_extended = 0x05, DW_CFA_restore_extended = 0x06, DW_CFA_undefined = 0x07,
DW_CFA_same_value = 0x08, DW_CFA_register = 0x09, DW_CFA_remember_state = 0x0a, DW_CFA_restore_state = 0x0b,
DW_CFA_def_cfa = 0x0c, DW_CFA_def_cfa_register = 0x0d, DW_CFA_def_cfa_offset = 0x0e, DW_CFA_def_cfa_expression = 0x0f,
DW_CFA_expression = 0x10, DW_CFA_offset_extended_sf = 0x11, DW_CFA_def_cfa_sf = 0x12, DW_CFA_def_cfa_offset_sf = 0x13,
DW_CFA_val_offset = 0x14, DW_CFA_val_offset_sf = 0x15, DW_CFA_val_expression = 0x16, DW_CFA_MIPS_advance_loc8 = 0x1d,
DW_CFA_GNU_window_save = 0x2d, DW_CFA_GNU_args_size = 0x2e, DW_CFA_lo_user = 0x1c, DW_CFA_hi_user = 0x3f
}
enum Constants {
DW_CHILDREN_no = 0x00, DW_CHILDREN_yes = 0x01, DW_EH_PE_absptr = 0x00, DW_EH_PE_omit = 0xff,
DW_EH_PE_uleb128 = 0x01, DW_EH_PE_udata2 = 0x02, DW_EH_PE_udata4 = 0x03, DW_EH_PE_udata8 = 0x04,
DW_EH_PE_sleb128 = 0x09, DW_EH_PE_sdata2 = 0x0A, DW_EH_PE_sdata4 = 0x0B, DW_EH_PE_sdata8 = 0x0C,
DW_EH_PE_signed = 0x08, DW_EH_PE_pcrel = 0x10, DW_EH_PE_textrel = 0x20, DW_EH_PE_datarel = 0x30,
DW_EH_PE_funcrel = 0x40, DW_EH_PE_aligned = 0x50, DW_EH_PE_indirect = 0x80
}
enum ApplePropertyAttributes {
DW_APPLE_PROPERTY_readonly = 0x01, DW_APPLE_PROPERTY_readwrite = 0x02, DW_APPLE_PROPERTY_assign = 0x04, DW_APPLE_PROPERTY_retain = 0x08,
DW_APPLE_PROPERTY_copy = 0x10, DW_APPLE_PROPERTY_nonatomic = 0x20
}
enum AcceleratorTable {
DW_ATOM_null = 0u, DW_ATOM_die_offset = 1u, DW_ATOM_cu_offset = 2u, DW_ATOM_die_tag = 3u,
DW_ATOM_type_flags = 4u, DW_FLAG_type_implementation = 2u, DW_hash_function_djb = 0u
}
enum GDBIndexEntryKind {
GIEK_NONE, GIEK_TYPE, GIEK_VARIABLE, GIEK_FUNCTION,
GIEK_OTHER, GIEK_UNUSED5, GIEK_UNUSED6, GIEK_UNUSED7
}
enum GDBIndexEntryLinkage { GIEL_EXTERNAL, GIEL_STATIC }
Functions
enum LLVMConstants LLVM_ENUM_INT_TYPE (uint32_t)
enum Tag LLVM_ENUM_INT_TYPE (uint16_t)
bool isType (Tag T)
const char * TagString (unsigned Tag)
const char * ChildrenString (unsigned Children)
const char * AttributeString (unsigned Attribute)
const char * FormEncodingString (unsigned Encoding)
const char * OperationEncodingString (unsigned Encoding)
const char * AttributeEncodingString (unsigned Encoding)
const char * DecimalSignString (unsigned Sign)
const char * EndianityString (unsigned Endian)
const char * AccessibilityString (unsigned Access)
const char * VisibilityString (unsigned Visibility)
const char * VirtualityString (unsigned Virtuality)
const char * LanguageString (unsigned Language)
const char * CaseString (unsigned Case)
const char * ConventionString (unsigned Convention)
const char * InlineCodeString (unsigned Code)
const char * ArrayOrderString (unsigned Order)
const char * DiscriminantString (unsigned Discriminant)
const char * LNStandardString (unsigned Standard)
const char * LNExtendedString (unsigned Encoding)
const char * MacinfoString (unsigned Encoding)
const char * CallFrameString (unsigned Encoding)
const char * AtomTypeString (unsigned Atom)
AtomTypeString - Return the string for the specified Atom type.
const char * GDBIndexEntryKindString (GDBIndexEntryKind Kind)
const char * GDBIndexEntryLinkageString (GDBIndexEntryLinkage Linkage)
Variables
const uint32_t DW_CIE_ID = UINT32_MAX
const uint64_t DW64_CIE_ID = UINT64_MAX
Enumeration Type Documentation
enum llvm::dwarf::AcceleratorTable
Enumerator
DW_ATOM_null
DW_ATOM_die_offset
DW_ATOM_cu_offset
DW_ATOM_die_tag
DW_ATOM_type_flags
DW_FLAG_type_implementation
DW_hash_function_djb
Definition at line 842 of file Dwarf.h.
enum llvm::dwarf::AccessAttribute
Enumerator
DW_ACCESS_public
DW_ACCESS_protected
DW_ACCESS_private
Definition at line 566 of file Dwarf.h.
enum llvm::dwarf::ApplePropertyAttributes
Enumerator
DW_APPLE_PROPERTY_readonly
DW_APPLE_PROPERTY_readwrite
DW_APPLE_PROPERTY_assign
DW_APPLE_PROPERTY_retain
DW_APPLE_PROPERTY_copy
DW_APPLE_PROPERTY_nonatomic
Definition at line 747 of file Dwarf.h.
enum llvm::dwarf::ArrayDimensionOrdering
Enumerator
DW_ORD_row_major
DW_ORD_col_major
Definition at line 639 of file Dwarf.h.
enum llvm::dwarf::CallFrameInfo
Enumerator
DW_CFA_extended
DW_CFA_nop
DW_CFA_advance_loc
DW_CFA_offset
DW_CFA_restore
DW_CFA_set_loc
DW_CFA_advance_loc1
DW_CFA_advance_loc2
DW_CFA_advance_loc4
DW_CFA_offset_extended
DW_CFA_restore_extended
DW_CFA_undefined
DW_CFA_same_value
DW_CFA_register
DW_CFA_remember_state
DW_CFA_restore_state
DW_CFA_def_cfa
DW_CFA_def_cfa_register
DW_CFA_def_cfa_offset
DW_CFA_def_cfa_expression
DW_CFA_expression
DW_CFA_offset_extended_sf
DW_CFA_def_cfa_sf
DW_CFA_def_cfa_offset_sf
DW_CFA_val_offset
DW_CFA_val_offset_sf
DW_CFA_val_expression
DW_CFA_MIPS_advance_loc8
DW_CFA_GNU_window_save
DW_CFA_GNU_args_size
DW_CFA_lo_user
DW_CFA_hi_user
Definition at line 687 of file Dwarf.h.
enum llvm::dwarf::CallingConvention
Enumerator
DW_CC_normal
DW_CC_program
DW_CC_nocall
DW_CC_lo_user
DW_CC_hi_user
Definition at line 622 of file Dwarf.h.
enum llvm::dwarf::CaseSensitivity
Enumerator
DW_ID_case_sensitive
DW_ID_up_case
DW_ID_down_case
DW_ID_case_insensitive
Definition at line 614 of file Dwarf.h.
enum llvm::dwarf::Constants
Enumerator
DW_CHILDREN_no
DW_CHILDREN_yes
DW_EH_PE_absptr
DW_EH_PE_omit
DW_EH_PE_uleb128
DW_EH_PE_udata2
DW_EH_PE_udata4
DW_EH_PE_udata8
DW_EH_PE_sleb128
DW_EH_PE_sdata2
DW_EH_PE_sdata4
DW_EH_PE_sdata8
DW_EH_PE_signed
DW_EH_PE_pcrel
DW_EH_PE_textrel
DW_EH_PE_datarel
DW_EH_PE_funcrel
DW_EH_PE_aligned
DW_EH_PE_indirect
Definition at line 723 of file Dwarf.h.
enum llvm::dwarf::DecimalSignEncoding
Enumerator
DW_DS_unsigned
DW_DS_leading_overpunch
DW_DS_trailing_overpunch
DW_DS_leading_separate
DW_DS_trailing_separate
Definition at line 548 of file Dwarf.h.
enum llvm::dwarf::DiscriminantList
Enumerator
DW_DSC_label
DW_DSC_range
Definition at line 645 of file Dwarf.h.
enum llvm::dwarf::EndianityEncoding
Enumerator
DW_END_default
DW_END_big
DW_END_little
DW_END_lo_user
DW_END_hi_user
Definition at line 557 of file Dwarf.h.
enum llvm::dwarf::GDBIndexEntryKind
Enumerator
GIEK_NONE
GIEK_TYPE
GIEK_VARIABLE
GIEK_FUNCTION
GIEK_OTHER
GIEK_UNUSED5
GIEK_UNUSED6
GIEK_UNUSED7
Definition at line 867 of file Dwarf.h.
enum llvm::dwarf::GDBIndexEntryLinkage
Enumerator
GIEL_EXTERNAL
GIEL_STATIC
Definition at line 880 of file Dwarf.h.
enum llvm::dwarf::InlineAttribute
Enumerator
DW_INL_not_inlined
DW_INL_inlined
DW_INL_declared_not_inlined
DW_INL_declared_inlined
Definition at line 631 of file Dwarf.h.
enum llvm::dwarf::LineNumberExtendedOps
Enumerator
DW_LNE_end_sequence
DW_LNE_set_address
DW_LNE_define_file
DW_LNE_set_discriminator
DW_LNE_lo_user
DW_LNE_hi_user
Definition at line 668 of file Dwarf.h.
enum llvm::dwarf::LineNumberOps
Enumerator
DW_LNS_extended_op
DW_LNS_copy
DW_LNS_advance_pc
DW_LNS_advance_line
DW_LNS_set_file
DW_LNS_set_column
DW_LNS_negate_stmt
DW_LNS_set_basic_block
DW_LNS_const_add_pc
DW_LNS_fixed_advance_pc
DW_LNS_set_prologue_end
DW_LNS_set_epilogue_begin
DW_LNS_set_isa
Definition at line 651 of file Dwarf.h.
enum llvm::dwarf::LocationAtom
Enumerator
DW_OP_addr
DW_OP_deref
DW_OP_const1u
DW_OP_const1s
DW_OP_const2u
DW_OP_const2s
DW_OP_const4u
DW_OP_const4s
DW_OP_const8u
DW_OP_const8s
DW_OP_constu
DW_OP_consts
DW_OP_dup
DW_OP_drop
DW_OP_over
DW_OP_pick
DW_OP_swap
DW_OP_rot
DW_OP_xderef
DW_OP_abs
DW_OP_and
DW_OP_div
DW_OP_minus
DW_OP_mod
DW_OP_mul
DW_OP_neg
DW_OP_not
DW_OP_or
DW_OP_plus
DW_OP_plus_uconst
DW_OP_shl
DW_OP_shr
DW_OP_shra
DW_OP_xor
DW_OP_skip
DW_OP_bra
DW_OP_eq
DW_OP_ge
DW_OP_gt
DW_OP_le
DW_OP_lt
DW_OP_ne
DW_OP_lit0
DW_OP_lit1
DW_OP_lit2
DW_OP_lit3
DW_OP_lit4
DW_OP_lit5
DW_OP_lit6
DW_OP_lit7
DW_OP_lit8
DW_OP_lit9
DW_OP_lit10
DW_OP_lit11
DW_OP_lit12
DW_OP_lit13
DW_OP_lit14
DW_OP_lit15
DW_OP_lit16
DW_OP_lit17
DW_OP_lit18
DW_OP_lit19
DW_OP_lit20
DW_OP_lit21
DW_OP_lit22
DW_OP_lit23
DW_OP_lit24
DW_OP_lit25
DW_OP_lit26
DW_OP_lit27
DW_OP_lit28
DW_OP_lit29
DW_OP_lit30
DW_OP_lit31
DW_OP_reg0
DW_OP_reg1
DW_OP_reg2
DW_OP_reg3
DW_OP_reg4
DW_OP_reg5
DW_OP_reg6
DW_OP_reg7
DW_OP_reg8
DW_OP_reg9
DW_OP_reg10
DW_OP_reg11
DW_OP_reg12
DW_OP_reg13
DW_OP_reg14
DW_OP_reg15
DW_OP_reg16
DW_OP_reg17
DW_OP_reg18
DW_OP_reg19
DW_OP_reg20
DW_OP_reg21
DW_OP_reg22
DW_OP_reg23
DW_OP_reg24
DW_OP_reg25
DW_OP_reg26
DW_OP_reg27
DW_OP_reg28
DW_OP_reg29
DW_OP_reg30
DW_OP_reg31
DW_OP_breg0
DW_OP_breg1
DW_OP_breg2
DW_OP_breg3
DW_OP_breg4
DW_OP_breg5
DW_OP_breg6
DW_OP_breg7
DW_OP_breg8
DW_OP_breg9
DW_OP_breg10
DW_OP_breg11
DW_OP_breg12
DW_OP_breg13
DW_OP_breg14
DW_OP_breg15
DW_OP_breg16
DW_OP_breg17
DW_OP_breg18
DW_OP_breg19
DW_OP_breg20
DW_OP_breg21
DW_OP_breg22
DW_OP_breg23
DW_OP_breg24
DW_OP_breg25
DW_OP_breg26
DW_OP_breg27
DW_OP_breg28
DW_OP_breg29
DW_OP_breg30
DW_OP_breg31
DW_OP_regx
DW_OP_fbreg
DW_OP_bregx
DW_OP_piece
DW_OP_deref_size
DW_OP_xderef_size
DW_OP_nop
DW_OP_push_object_address
DW_OP_call2
DW_OP_call4
DW_OP_call_ref
DW_OP_form_tls_address
DW_OP_call_frame_cfa
DW_OP_bit_piece
DW_OP_implicit_value
DW_OP_stack_value
DW_OP_lo_user
DW_OP_hi_user
DW_OP_GNU_push_tls_address
DW_OP_GNU_addr_index
DW_OP_GNU_const_index
Definition at line 359 of file Dwarf.h.
enum llvm::dwarf::MacinfoRecordType
Enumerator
DW_MACINFO_define
DW_MACINFO_undef
DW_MACINFO_start_file
DW_MACINFO_end_file
DW_MACINFO_vendor_ext
Definition at line 678 of file Dwarf.h.
enum llvm::dwarf::SourceLanguage
Enumerator
DW_LANG_C89
DW_LANG_C
DW_LANG_Ada83
DW_LANG_C_plus_plus
DW_LANG_Cobol74
DW_LANG_Cobol85
DW_LANG_Fortran77
DW_LANG_Fortran90
DW_LANG_Pascal83
DW_LANG_Modula2
DW_LANG_Java
DW_LANG_C99
DW_LANG_Ada95
DW_LANG_Fortran95
DW_LANG_PLI
DW_LANG_ObjC
DW_LANG_ObjC_plus_plus
DW_LANG_UPC
DW_LANG_D
DW_LANG_Python
DW_LANG_lo_user
DW_LANG_Mips_Assembler
DW_LANG_hi_user
Definition at line 587 of file Dwarf.h.
enum llvm::dwarf::TypeKind
Enumerator
DW_ATE_address
DW_ATE_boolean
DW_ATE_complex_float
DW_ATE_float
DW_ATE_signed
DW_ATE_signed_char
DW_ATE_unsigned
DW_ATE_unsigned_char
DW_ATE_imaginary_float
DW_ATE_packed_decimal
DW_ATE_numeric_string
DW_ATE_edited
DW_ATE_signed_fixed
DW_ATE_unsigned_fixed
DW_ATE_decimal_float
DW_ATE_UTF
DW_ATE_lo_user
DW_ATE_hi_user
Definition at line 526 of file Dwarf.h.
enum llvm::dwarf::VirtualityAttribute
Enumerator
DW_VIRTUALITY_none
DW_VIRTUALITY_virtual
DW_VIRTUALITY_pure_virtual
Definition at line 580 of file Dwarf.h.
enum llvm::dwarf::VisibilityAttribute
Enumerator
DW_VIS_local
DW_VIS_exported
DW_VIS_qualified
Definition at line 573 of file Dwarf.h.
Function Documentation
const char * llvm::dwarf::AccessibilityString (unsigned Access)
AccessibilityString - Return the string for the specified accessibility.
Definition at line 524 of file Dwarf.cpp.
References DW_ACCESS_private, DW_ACCESS_protected, and DW_ACCESS_public.
Referenced by llvm::DwarfDebug::emitDIE().
const char * llvm::dwarf::ArrayOrderString (unsigned Order)
ArrayOrderString - Return the string for the specified array order.
Definition at line 624 of file Dwarf.cpp.
References DW_ORD_col_major, and DW_ORD_row_major.
const char * llvm::dwarf::AtomTypeString (unsigned Atom)
AtomTypeString - Return the string for the specified Atom type.
Definition at line 730 of file Dwarf.cpp.
References DW_ATOM_cu_offset, DW_ATOM_die_offset, DW_ATOM_die_tag, DW_ATOM_null, and DW_ATOM_type_flags.
Referenced by llvm::DwarfAccelTable::FinalizeTable(), and llvm::DwarfAccelTable::Atom::print().
const char * llvm::dwarf::AttributeEncodingString (unsigned Encoding)
AttributeEncodingString - Return the string for the specified attribute encoding.
Definition at line 472 of file Dwarf.cpp.
References DW_ATE_address, DW_ATE_boolean, DW_ATE_complex_float, DW_ATE_decimal_float, DW_ATE_edited, DW_ATE_float, DW_ATE_hi_user, DW_ATE_imaginary_float, DW_ATE_lo_user, DW_ATE_numeric_string, DW_ATE_packed_decimal, DW_ATE_signed, DW_ATE_signed_char, DW_ATE_signed_fixed, DW_ATE_unsigned, DW_ATE_unsigned_char, DW_ATE_unsigned_fixed, and DW_ATE_UTF.
Referenced by llvm::DIType::printInternal().
const char * llvm::dwarf::AttributeString (unsigned Attribute)
AttributeString - Return the string for the specified attribute.
Definition at line 115 of file Dwarf.cpp.
Referenced by llvm::DWARFAbbreviationDeclaration::dump(), llvm::DWARFDebugInfoEntryMinimal::dumpAttribute(), llvm::DIEAbbrev::Emit(), llvm::DwarfDebug::emitDIE(), getDIEStringAttr(), llvm::DIEAbbrev::print(), and llvm::DIE::print().
const char * llvm::dwarf::CallFrameString (unsigned Encoding)
CallFrameString - Return the string for the specified call frame instruction encodings.
Definition at line 693 of file Dwarf.cpp.
References DW_CFA_advance_loc, DW_CFA_advance_loc1, DW_CFA_advance_loc2, DW_CFA_advance_loc4, DW_CFA_def_cfa, DW_CFA_def_cfa_expression, DW_CFA_def_cfa_offset, DW_CFA_def_cfa_offset_sf, DW_CFA_def_cfa_register, DW_CFA_def_cfa_sf, DW_CFA_expression, DW_CFA_GNU_args_size, DW_CFA_GNU_window_save, DW_CFA_hi_user, DW_CFA_lo_user, DW_CFA_MIPS_advance_loc8, DW_CFA_nop, DW_CFA_offset, DW_CFA_offset_extended, DW_CFA_offset_extended_sf, DW_CFA_register, DW_CFA_remember_state, DW_CFA_restore, DW_CFA_restore_extended, DW_CFA_restore_state, DW_CFA_same_value, DW_CFA_set_loc, DW_CFA_undefined, DW_CFA_val_expression, DW_CFA_val_offset, and DW_CFA_val_offset_sf.
Referenced by llvm::FrameEntry::dumpInstructions(), and llvm::AsmPrinter::EmitCFAByte().
const char * llvm::dwarf::CaseString (unsigned Case)
CaseString - Return the string for the specified identifier case.
Definition at line 587 of file Dwarf.cpp.
References DW_ID_case_insensitive, DW_ID_case_sensitive, DW_ID_down_case, and DW_ID_up_case.
const char * llvm::dwarf::ChildrenString (unsigned Children)
ChildrenString - Return the string for the specified children flag.
Definition at line 105 of file Dwarf.cpp.
References DW_CHILDREN_no, and DW_CHILDREN_yes.
Referenced by llvm::DIEAbbrev::Emit(), llvm::DIEAbbrev::print(), and llvm::DIE::print().
const char * llvm::dwarf::ConventionString (unsigned Convention)
ConventionString - Return the string for the specified calling convention.
Definition at line 599 of file Dwarf.cpp.
References DW_CC_hi_user, DW_CC_lo_user, DW_CC_nocall, DW_CC_normal, and DW_CC_program.
const char * llvm::dwarf::DecimalSignString (unsigned Sign)
DecimalSignString - Return the string for the specified decimal sign attribute.
Definition at line 498 of file Dwarf.cpp.
References DW_DS_leading_overpunch, DW_DS_leading_separate, DW_DS_trailing_overpunch, DW_DS_trailing_separate, and DW_DS_unsigned.
const char * llvm::dwarf::DiscriminantString (unsigned Discriminant)
DiscriminantString - Return the string for the specified discriminant descriptor.
Definition at line 634 of file Dwarf.cpp.
References DW_DSC_label, and DW_DSC_range.
const char * llvm::dwarf::EndianityString (unsigned Endian)
EndianityString - Return the string for the specified endianity.
Definition at line 511 of file Dwarf.cpp.
References DW_END_big, DW_END_default, DW_END_hi_user, DW_END_little, and DW_END_lo_user.
const char * llvm::dwarf::FormEncodingString (unsigned Encoding)
FormEncodingString - Return the string for the specified form encoding.
Definition at line 266 of file Dwarf.cpp.
Referenced by llvm::DWARFAbbreviationDeclaration::dump(), llvm::DWARFDebugInfoEntryMinimal::dumpAttribute(), llvm::DIEAbbrev::Emit(), llvm::DwarfAccelTable::FinalizeTable(), llvm::DIEAbbrev::print(), llvm::DwarfAccelTable::Atom::print(), and llvm::DIE::print().
const char * llvm::dwarf::GDBIndexEntryKindString (GDBIndexEntryKind Kind)
Definition at line 746 of file Dwarf.cpp.
References GIEK_FUNCTION, GIEK_NONE, GIEK_OTHER, GIEK_TYPE, GIEK_UNUSED5, GIEK_UNUSED6, GIEK_UNUSED7, GIEK_VARIABLE, and llvm_unreachable.
Referenced by computeIndexValue(), and dumpPubSection().
const char * llvm::dwarf::GDBIndexEntryLinkageString (GDBIndexEntryLinkage Linkage)
Definition at line 768 of file Dwarf.cpp.
References GIEL_EXTERNAL, GIEL_STATIC, and llvm_unreachable.
Referenced by computeIndexValue(), and dumpPubSection().
const char * llvm::dwarf::InlineCodeString (unsigned Code)
InlineCodeString - Return the string for the specified inline code.
Definition at line 612 of file Dwarf.cpp.
References DW_INL_declared_inlined, DW_INL_declared_not_inlined, DW_INL_inlined, and DW_INL_not_inlined.
bool llvm::dwarf::isType (Tag T) inline
Definition at line 144 of file Dwarf.h.
References LLVM_ENUM_INT_TYPE().
Referenced by llvm::CompileUnit::constructVariableDIE(), llvm::DIScope::getContext(), getDIEStringAttr(), llvm::DIScope::getName(), llvm::DIDescriptor::isScope(), and llvm::DIType::Verify().
const char * llvm::dwarf::LanguageString (unsigned Language)
LanguageString - Return the string for the specified language.
Definition at line 558 of file Dwarf.cpp.
References DW_LANG_Ada83, DW_LANG_Ada95, DW_LANG_C, DW_LANG_C89, DW_LANG_C99, DW_LANG_C_plus_plus, DW_LANG_Cobol74, DW_LANG_Cobol85, DW_LANG_D, DW_LANG_Fortran77, DW_LANG_Fortran90, DW_LANG_Fortran95, DW_LANG_hi_user, DW_LANG_Java, DW_LANG_lo_user, DW_LANG_Modula2, DW_LANG_ObjC, DW_LANG_ObjC_plus_plus, DW_LANG_Pascal83, DW_LANG_PLI, and DW_LANG_UPC.
Referenced by llvm::DIScope::printInternal().
enum Form llvm::dwarf::LLVM_ENUM_INT_TYPE (uint16_t)
Definition at line 71 of file Dwarf.h.
enum LLVMConstants llvm::dwarf::LLVM_ENUM_INT_TYPE (uint32_t)
Definition at line 50 of file Dwarf.h.
Referenced by isType().
const char * llvm::dwarf::LNExtendedString (unsigned Encoding)
LNExtendedString - Return the string for the specified line number extended opcode encodings.
Definition at line 664 of file Dwarf.cpp.
References DW_LNE_define_file, DW_LNE_end_sequence, DW_LNE_hi_user, DW_LNE_lo_user, DW_LNE_set_address, and DW_LNE_set_discriminator.
const char * llvm::dwarf::LNStandardString (unsigned Standard)
LNStandardString - Return the string for the specified line number standard.
Definition at line 644 of file Dwarf.cpp.
References DW_LNS_advance_line, DW_LNS_advance_pc, DW_LNS_const_add_pc, DW_LNS_copy, DW_LNS_fixed_advance_pc, DW_LNS_negate_stmt, DW_LNS_set_basic_block, DW_LNS_set_column, DW_LNS_set_epilogue_begin, DW_LNS_set_file, DW_LNS_set_isa, and DW_LNS_set_prologue_end.
Referenced by llvm::DWARFDebugLine::Prologue::dump().
const char * llvm::dwarf::MacinfoString (unsigned Encoding)
MacinfoString - Return the string for the specified macinfo type encodings.
Definition at line 679 of file Dwarf.cpp.
References DW_MACINFO_define, DW_MACINFO_end_file, DW_MACINFO_start_file, DW_MACINFO_undef, and DW_MACINFO_vendor_ext.
const char * llvm::dwarf::OperationEncodingString (unsigned Encoding)
OperationEncodingString - Return the string for the specified operation encoding.
Definition at line 303 of file Dwarf.cpp.
References DW_OP_abs, DW_OP_addr, DW_OP_and, DW_OP_bit_piece, DW_OP_bra, DW_OP_breg0, DW_OP_breg1, DW_OP_breg10, DW_OP_breg11, DW_OP_breg12, DW_OP_breg13, DW_OP_breg14, DW_OP_breg15, DW_OP_breg16, DW_OP_breg17, DW_OP_breg18, DW_OP_breg19, DW_OP_breg2, DW_OP_breg20, DW_OP_breg21, DW_OP_breg22, DW_OP_breg23, DW_OP_breg24, DW_OP_breg25, DW_OP_breg26, DW_OP_breg27, DW_OP_breg28, DW_OP_breg29, DW_OP_breg3, DW_OP_breg30, DW_OP_breg31, DW_OP_breg4, DW_OP_breg5, DW_OP_breg6, DW_OP_breg7, DW_OP_breg8, DW_OP_breg9, DW_OP_bregx, DW_OP_call2, DW_OP_call4, DW_OP_call_frame_cfa, DW_OP_call_ref, DW_OP_const1s, DW_OP_const1u, DW_OP_const2s, DW_OP_const2u, DW_OP_const4s, DW_OP_const4u, DW_OP_const8s, DW_OP_const8u, DW_OP_consts, DW_OP_constu, DW_OP_deref, DW_OP_deref_size, DW_OP_div, DW_OP_drop, DW_OP_dup, DW_OP_eq, DW_OP_fbreg, DW_OP_form_tls_address, DW_OP_ge, DW_OP_GNU_addr_index, DW_OP_GNU_const_index, DW_OP_GNU_push_tls_address, DW_OP_gt, DW_OP_implicit_value, DW_OP_le, DW_OP_lit0, DW_OP_lit1, DW_OP_lit10, DW_OP_lit11, DW_OP_lit12, DW_OP_lit13, DW_OP_lit14, DW_OP_lit15, DW_OP_lit16, DW_OP_lit17, DW_OP_lit18, DW_OP_lit19, DW_OP_lit2, DW_OP_lit20, DW_OP_lit21, DW_OP_lit22, DW_OP_lit23, DW_OP_lit24, DW_OP_lit25, DW_OP_lit26, DW_OP_lit27, DW_OP_lit28, DW_OP_lit29, DW_OP_lit3, DW_OP_lit30, DW_OP_lit31, DW_OP_lit4, DW_OP_lit5, DW_OP_lit6, DW_OP_lit7, DW_OP_lit8, DW_OP_lit9, DW_OP_lt, DW_OP_minus, DW_OP_mod, DW_OP_mul, DW_OP_ne, DW_OP_neg, DW_OP_nop, DW_OP_not, DW_OP_or, DW_OP_over, DW_OP_pick, DW_OP_piece, DW_OP_plus, DW_OP_plus_uconst, DW_OP_push_object_address, DW_OP_reg0, DW_OP_reg1, DW_OP_reg10, DW_OP_reg11, DW_OP_reg12, DW_OP_reg13, DW_OP_reg14, DW_OP_reg15, DW_OP_reg16, DW_OP_reg17, DW_OP_reg18, DW_OP_reg19, DW_OP_reg2, DW_OP_reg20, DW_OP_reg21, DW_OP_reg22, DW_OP_reg23, DW_OP_reg24, DW_OP_reg25, DW_OP_reg26, DW_OP_reg27, DW_OP_reg28, DW_OP_reg29, DW_OP_reg3, DW_OP_reg30, DW_OP_reg31, DW_OP_reg4, DW_OP_reg5, DW_OP_reg6, DW_OP_reg7, DW_OP_reg8, DW_OP_reg9, DW_OP_regx, DW_OP_rot, DW_OP_shl, DW_OP_shr, DW_OP_shra, DW_OP_skip, DW_OP_stack_value, DW_OP_swap, DW_OP_xderef, DW_OP_xderef_size, and DW_OP_xor.
Referenced by llvm::AsmPrinter::EmitDwarfRegOp().
const char * llvm::dwarf::TagString (unsigned Tag)
TagString - Return the string for the specified tag.
Definition at line 22 of file Dwarf.cpp.
Referenced by llvm::DWARFDebugInfoEntryMinimal::dump(), llvm::DWARFAbbreviationDeclaration::dump(), llvm::DIEAbbrev::Emit(), llvm::DwarfDebug::emitDIE(), llvm::DIEAbbrev::print(), llvm::DIDescriptor::print(), llvm::DwarfAccelTable::HashDataContents::print(), llvm::DIE::print(), and llvm::WriteMDNodeComment().
const char * llvm::dwarf::VirtualityString (unsigned Virtuality)
VirtualityString - Return the string for the specified virtuality.
Definition at line 547 of file Dwarf.cpp.
References DW_VIRTUALITY_none, DW_VIRTUALITY_pure_virtual, and DW_VIRTUALITY_virtual.
const char * llvm::dwarf::VisibilityString (unsigned Visibility)
VisibilityString - Return the string for the specified visibility.
Definition at line 536 of file Dwarf.cpp.
References DW_VIS_exported, DW_VIS_local, and DW_VIS_qualified.
Variable Documentation
const uint64_t llvm::dwarf::DW64_CIE_ID = UINT64_MAX
Definition at line 69 of file Dwarf.h.
Referenced by llvm::DWARFDebugFrame::parse().
const uint32_t llvm::dwarf::DW_CIE_ID = UINT32_MAX
Definition at line 68 of file Dwarf.h.
Referenced by llvm::FrameEntry::dumpInstructions(), and llvm::DWARFDebugFrame::parse().