LLVM: llvm::MachO Namespace Reference
LLVM API Documentation
llvm::MachO Namespace Reference
Classes
struct any_relocation_info
struct data_in_code_entry
struct dyld_info_command
struct dylib
struct dylib_command
struct dylib_module
struct dylib_module_64
struct dylib_reference
struct dylib_table_of_contents
struct dylinker_command
struct dysymtab_command
struct encryption_info_command
struct entry_point_command
struct fat_arch
struct fat_header
struct fvmfile_command
struct fvmlib
struct fvmlib_command
struct ident_command
struct linkedit_data_command
struct linker_options_command
struct load_command
struct mach_header
struct mach_header_64
struct nlist
struct nlist_64
struct prebind_cksum_command
struct prebound_dylib_command
struct relocation_info
struct routines_command
struct routines_command_64
struct rpath_command
struct scattered_relocation_info
struct section
struct section_64
struct segment_command
struct segment_command_64
struct source_version_command
struct sub_client_command
struct sub_framework_command
struct sub_library_command
struct sub_umbrella_command
struct symseg_command
struct symtab_command
struct thread_command
struct tlv_descriptor
struct tlv_descriptor_32
struct tlv_descriptor_64
struct twolevel_hint
struct twolevel_hints_command
struct uuid_command
struct version_min_command
Enumerations
enum HeaderFileType {
MH_OBJECT = 0x1u, MH_EXECUTE = 0x2u, MH_FVMLIB = 0x3u, MH_CORE = 0x4u,
MH_PRELOAD = 0x5u, MH_DYLIB = 0x6u, MH_DYLINKER = 0x7u, MH_BUNDLE = 0x8u,
MH_DYLIB_STUB = 0x9u, MH_DSYM = 0xAu, MH_KEXT_BUNDLE = 0xBu
}
enum {
MH_NOUNDEFS = 0x00000001u, MH_INCRLINK = 0x00000002u, MH_DYLDLINK = 0x00000004u, MH_BINDATLOAD = 0x00000008u,
MH_PREBOUND = 0x00000010u, MH_SPLIT_SEGS = 0x00000020u, MH_LAZY_INIT = 0x00000040u, MH_TWOLEVEL = 0x00000080u,
MH_FORCE_FLAT = 0x00000100u, MH_NOMULTIDEFS = 0x00000200u, MH_NOFIXPREBINDING = 0x00000400u, MH_PREBINDABLE = 0x00000800u,
MH_ALLMODSBOUND = 0x00001000u, MH_SUBSECTIONS_VIA_SYMBOLS = 0x00002000u, MH_CANONICAL = 0x00004000u, MH_WEAK_DEFINES = 0x00008000u,
MH_BINDS_TO_WEAK = 0x00010000u, MH_ALLOW_STACK_EXECUTION = 0x00020000u, MH_ROOT_SAFE = 0x00040000u, MH_SETUID_SAFE = 0x00080000u,
MH_NO_REEXPORTED_DYLIBS = 0x00100000u, MH_PIE = 0x00200000u, MH_DEAD_STRIPPABLE_DYLIB = 0x00400000u
}
enum SectionType {
S_REGULAR = 0x00u, S_ZEROFILL = 0x01u, S_CSTRING_LITERALS = 0x02u, S_4BYTE_LITERALS = 0x03u,
S_8BYTE_LITERALS = 0x04u, S_LITERAL_POINTERS = 0x05u, S_NON_LAZY_SYMBOL_POINTERS = 0x06u, S_LAZY_SYMBOL_POINTERS = 0x07u,
S_SYMBOL_STUBS = 0x08u, S_MOD_INIT_FUNC_POINTERS = 0x09u, S_MOD_TERM_FUNC_POINTERS = 0x0au, S_COALESCED = 0x0bu,
S_GB_ZEROFILL = 0x0cu, S_INTERPOSING = 0x0du, S_16BYTE_LITERALS = 0x0eu, S_DTRACE_DOF = 0x0fu,
S_LAZY_DYLIB_SYMBOL_POINTERS = 0x10u, S_THREAD_LOCAL_REGULAR = 0x11u, S_THREAD_LOCAL_ZEROFILL = 0x12u, S_THREAD_LOCAL_VARIABLES = 0x13u,
S_THREAD_LOCAL_VARIABLE_POINTERS = 0x14u, S_THREAD_LOCAL_INIT_FUNCTION_POINTERS = 0x15u
}
enum DataRegionType {
DICE_KIND_DATA = 1u, DICE_KIND_JUMP_TABLE8 = 2u, DICE_KIND_JUMP_TABLE16 = 3u, DICE_KIND_JUMP_TABLE32 = 4u,
DICE_KIND_ABS_JUMP_TABLE32 = 5u
}
enum RebaseType { REBASE_TYPE_POINTER = 1u, REBASE_TYPE_TEXT_ABSOLUTE32 = 2u, REBASE_TYPE_TEXT_PCREL32 = 3u }
enum { REBASE_OPCODE_MASK = 0xF0u, REBASE_IMMEDIATE_MASK = 0x0Fu }
enum RebaseOpcode {
REBASE_OPCODE_DONE = 0x00u, REBASE_OPCODE_SET_TYPE_IMM = 0x10u, REBASE_OPCODE_SET_SEGMENT_AND_OFFSET_ULEB = 0x20u, REBASE_OPCODE_ADD_ADDR_ULEB = 0x30u,
REBASE_OPCODE_ADD_ADDR_IMM_SCALED = 0x40u, REBASE_OPCODE_DO_REBASE_IMM_TIMES = 0x50u, REBASE_OPCODE_DO_REBASE_ULEB_TIMES = 0x60u, REBASE_OPCODE_DO_REBASE_ADD_ADDR_ULEB = 0x70u,
REBASE_OPCODE_DO_REBASE_ULEB_TIMES_SKIPPING_ULEB = 0x80u
}
enum BindType { BIND_TYPE_POINTER = 1u, BIND_TYPE_TEXT_ABSOLUTE32 = 2u, BIND_TYPE_TEXT_PCREL32 = 3u }
enum BindSpecialDylib { BIND_SPECIAL_DYLIB_SELF = 0, BIND_SPECIAL_DYLIB_MAIN_EXECUTABLE = -1, BIND_SPECIAL_DYLIB_FLAT_LOOKUP = -2 }
enum { BIND_SYMBOL_FLAGS_WEAK_IMPORT = 0x1u, BIND_SYMBOL_FLAGS_NON_WEAK_DEFINITION = 0x8u, BIND_OPCODE_MASK = 0xF0u, BIND_IMMEDIATE_MASK = 0x0Fu }
enum BindOpcode {
BIND_OPCODE_DONE = 0x00u, BIND_OPCODE_SET_DYLIB_ORDINAL_IMM = 0x10u, BIND_OPCODE_SET_DYLIB_ORDINAL_ULEB = 0x20u, BIND_OPCODE_SET_DYLIB_SPECIAL_IMM = 0x30u,
BIND_OPCODE_SET_SYMBOL_TRAILING_FLAGS_IMM = 0x40u, BIND_OPCODE_SET_TYPE_IMM = 0x50u, BIND_OPCODE_SET_ADDEND_SLEB = 0x60u, BIND_OPCODE_SET_SEGMENT_AND_OFFSET_ULEB = 0x70u,
BIND_OPCODE_ADD_ADDR_ULEB = 0x80u, BIND_OPCODE_DO_BIND = 0x90u, BIND_OPCODE_DO_BIND_ADD_ADDR_ULEB = 0xA0u, BIND_OPCODE_DO_BIND_ADD_ADDR_IMM_SCALED = 0xB0u,
BIND_OPCODE_DO_BIND_ULEB_TIMES_SKIPPING_ULEB = 0xC0u
}
enum { EXPORT_SYMBOL_FLAGS_KIND_MASK = 0x03u, EXPORT_SYMBOL_FLAGS_WEAK_DEFINITION = 0x04u, EXPORT_SYMBOL_FLAGS_REEXPORT = 0x08u, EXPORT_SYMBOL_FLAGS_STUB_AND_RESOLVER = 0x10u }
enum ExportSymbolKind { EXPORT_SYMBOL_FLAGS_KIND_REGULAR = 0x00u, EXPORT_SYMBOL_FLAGS_KIND_THREAD_LOCAL = 0x01u }
enum { N_STAB = 0xe0, N_PEXT = 0x10, N_TYPE = 0x0e, N_EXT = 0x01 }
enum NListType {
N_UNDF = 0x0u, N_ABS = 0x2u, N_SECT = 0xeu, N_PBUD = 0xcu,
N_INDR = 0xau
}
enum SectionOrdinal { NO_SECT = 0u, MAX_SECT = 0xffu }
enum {
N_ARM_THUMB_DEF = 0x0008u, N_NO_DEAD_STRIP = 0x0020u, N_WEAK_REF = 0x0040u, N_WEAK_DEF = 0x0080u,
N_SYMBOL_RESOLVER = 0x0100u
}
enum StabType {
N_GSYM = 0x20u, N_FNAME = 0x22u, N_FUN = 0x24u, N_STSYM = 0x26u,
N_LCSYM = 0x28u, N_BNSYM = 0x2Eu, N_OPT = 0x3Cu, N_RSYM = 0x40u,
N_SLINE = 0x44u, N_ENSYM = 0x4Eu, N_SSYM = 0x60u, N_SO = 0x64u,
N_OSO = 0x66u, N_LSYM = 0x80u, N_BINCL = 0x82u, N_SOL = 0x84u,
N_PARAMS = 0x86u, N_VERSION = 0x88u, N_OLEVEL = 0x8Au, N_PSYM = 0xA0u,
N_EINCL = 0xA2u, N_ENTRY = 0xA4u, N_LBRAC = 0xC0u, N_EXCL = 0xC2u,
N_RBRAC = 0xE0u, N_BCOMM = 0xE2u, N_ECOMM = 0xE4u, N_ECOML = 0xE8u,
N_LENG = 0xFEu
}
enum RelocationInfoType {
GENERIC_RELOC_VANILLA = 0, GENERIC_RELOC_PAIR = 1, GENERIC_RELOC_SECTDIFF = 2, GENERIC_RELOC_PB_LA_PTR = 3,
GENERIC_RELOC_LOCAL_SECTDIFF = 4, GENERIC_RELOC_TLV = 5, PPC_RELOC_VANILLA = GENERIC_RELOC_VANILLA, PPC_RELOC_PAIR = GENERIC_RELOC_PAIR,
PPC_RELOC_BR14 = 2, PPC_RELOC_BR24 = 3, PPC_RELOC_HI16 = 4, PPC_RELOC_LO16 = 5,
PPC_RELOC_HA16 = 6, PPC_RELOC_LO14 = 7, PPC_RELOC_SECTDIFF = 8, PPC_RELOC_PB_LA_PTR = 9,
PPC_RELOC_HI16_SECTDIFF = 10, PPC_RELOC_LO16_SECTDIFF = 11, PPC_RELOC_HA16_SECTDIFF = 12, PPC_RELOC_JBSR = 13,
PPC_RELOC_LO14_SECTDIFF = 14, PPC_RELOC_LOCAL_SECTDIFF = 15, ARM_RELOC_VANILLA = GENERIC_RELOC_VANILLA, ARM_RELOC_PAIR = GENERIC_RELOC_PAIR,
ARM_RELOC_SECTDIFF = GENERIC_RELOC_SECTDIFF, ARM_RELOC_LOCAL_SECTDIFF = 3, ARM_RELOC_PB_LA_PTR = 4, ARM_RELOC_BR24 = 5,
ARM_THUMB_RELOC_BR22 = 6, ARM_THUMB_32BIT_BRANCH = 7, ARM_RELOC_HALF = 8, ARM_RELOC_HALF_SECTDIFF = 9,
X86_64_RELOC_UNSIGNED = 0, X86_64_RELOC_SIGNED = 1, X86_64_RELOC_BRANCH = 2, X86_64_RELOC_GOT_LOAD = 3,
X86_64_RELOC_GOT = 4, X86_64_RELOC_SUBTRACTOR = 5, X86_64_RELOC_SIGNED_1 = 6, X86_64_RELOC_SIGNED_2 = 7,
X86_64_RELOC_SIGNED_4 = 8, X86_64_RELOC_TLV = 9
}
enum { VM_PROT_READ = 0x1, VM_PROT_WRITE = 0x2, VM_PROT_EXECUTE = 0x4 }
enum CPUType {
CPU_TYPE_ANY = -1, CPU_TYPE_X86 = 7, CPU_TYPE_I386 = CPU_TYPE_X86, CPU_TYPE_X86_64 = CPU_TYPE_X86 | CPU_ARCH_ABI64,
CPU_TYPE_MC98000 = 10, CPU_TYPE_ARM = 12, CPU_TYPE_SPARC = 14, CPU_TYPE_POWERPC = 18,
CPU_TYPE_POWERPC64 = CPU_TYPE_POWERPC | CPU_ARCH_ABI64
}
enum CPUSubTypeX86 {
CPU_SUBTYPE_I386_ALL = 3, CPU_SUBTYPE_386 = 3, CPU_SUBTYPE_486 = 4, CPU_SUBTYPE_486SX = 0x84,
CPU_SUBTYPE_586 = 5, CPU_SUBTYPE_PENT = CPU_SUBTYPE_586, CPU_SUBTYPE_PENTPRO = 0x16, CPU_SUBTYPE_PENTII_M3 = 0x36,
CPU_SUBTYPE_PENTII_M5 = 0x56, CPU_SUBTYPE_CELERON = 0x67, CPU_SUBTYPE_CELERON_MOBILE = 0x77, CPU_SUBTYPE_PENTIUM_3 = 0x08,
CPU_SUBTYPE_PENTIUM_3_M = 0x18, CPU_SUBTYPE_PENTIUM_3_XEON = 0x28, CPU_SUBTYPE_PENTIUM_M = 0x09, CPU_SUBTYPE_PENTIUM_4 = 0x0a,
CPU_SUBTYPE_PENTIUM_4_M = 0x1a, CPU_SUBTYPE_ITANIUM = 0x0b, CPU_SUBTYPE_ITANIUM_2 = 0x1b, CPU_SUBTYPE_XEON = 0x0c,
CPU_SUBTYPE_XEON_MP = 0x1c, CPU_SUBTYPE_X86_ALL = 3, CPU_SUBTYPE_X86_64_ALL = 3, CPU_SUBTYPE_X86_ARCH1 = 4,
CPU_SUBTYPE_X86_64_H = 8
}
enum { CPU_SUBTYPE_INTEL_FAMILY_MAX = 15, CPU_SUBTYPE_INTEL_MODEL_ALL = 0 }
enum CPUSubTypeARM {
CPU_SUBTYPE_ARM_ALL = 0, CPU_SUBTYPE_ARM_V4T = 5, CPU_SUBTYPE_ARM_V6 = 6, CPU_SUBTYPE_ARM_V5 = 7,
CPU_SUBTYPE_ARM_V5TEJ = 7, CPU_SUBTYPE_ARM_XSCALE = 8, CPU_SUBTYPE_ARM_V7 = 9, CPU_SUBTYPE_ARM_V7F = 10,
CPU_SUBTYPE_ARM_V7S = 11, CPU_SUBTYPE_ARM_V7K = 12, CPU_SUBTYPE_ARM_V6M = 14, CPU_SUBTYPE_ARM_V7M = 15,
CPU_SUBTYPE_ARM_V7EM = 16
}
enum CPUSubTypeSPARC { CPU_SUBTYPE_SPARC_ALL = 0 }
enum CPUSubTypePowerPC {
CPU_SUBTYPE_POWERPC_ALL = 0, CPU_SUBTYPE_POWERPC_601 = 1, CPU_SUBTYPE_POWERPC_602 = 2, CPU_SUBTYPE_POWERPC_603 = 3,
CPU_SUBTYPE_POWERPC_603e = 4, CPU_SUBTYPE_POWERPC_603ev = 5, CPU_SUBTYPE_POWERPC_604 = 6, CPU_SUBTYPE_POWERPC_604e = 7,
CPU_SUBTYPE_POWERPC_620 = 8, CPU_SUBTYPE_POWERPC_750 = 9, CPU_SUBTYPE_POWERPC_7400 = 10, CPU_SUBTYPE_POWERPC_7450 = 11,
CPU_SUBTYPE_POWERPC_970 = 100, CPU_SUBTYPE_MC980000_ALL = CPU_SUBTYPE_POWERPC_ALL, CPU_SUBTYPE_MC98601 = CPU_SUBTYPE_POWERPC_601
}
Functions
enum LLVM_ENUM_INT_TYPE (uint32_t)
static uint16_t GET_LIBRARY_ORDINAL (uint16_t n_desc)
static void SET_LIBRARY_ORDINAL (uint16_t &n_desc, uint8_t ordinal)
static uint8_t GET_COMM_ALIGN (uint16_t n_desc)
static void SET_COMM_ALIGN (uint16_t &n_desc, uint8_t align)
static int CPU_SUBTYPE_INTEL (int Family, int Model)
static int CPU_SUBTYPE_INTEL_FAMILY (CPUSubTypeX86 ST)
static int CPU_SUBTYPE_INTEL_MODEL (CPUSubTypeX86 ST)
Enumeration Type Documentation
anonymous enum
Enumerator
MH_NOUNDEFS
MH_INCRLINK
MH_DYLDLINK
MH_BINDATLOAD
MH_PREBOUND
MH_SPLIT_SEGS
MH_LAZY_INIT
MH_TWOLEVEL
MH_FORCE_FLAT
MH_NOMULTIDEFS
MH_NOFIXPREBINDING
MH_PREBINDABLE
MH_ALLMODSBOUND
MH_SUBSECTIONS_VIA_SYMBOLS
MH_CANONICAL
MH_WEAK_DEFINES
MH_BINDS_TO_WEAK
MH_ALLOW_STACK_EXECUTION
MH_ROOT_SAFE
MH_SETUID_SAFE
MH_NO_REEXPORTED_DYLIBS
MH_PIE
MH_DEAD_STRIPPABLE_DYLIB
Definition at line 51 of file Support/MachO.h.
anonymous enum
Enumerator
REBASE_OPCODE_MASK
REBASE_IMMEDIATE_MASK
Definition at line 215 of file Support/MachO.h.
anonymous enum
Enumerator
BIND_SYMBOL_FLAGS_WEAK_IMPORT
BIND_SYMBOL_FLAGS_NON_WEAK_DEFINITION
BIND_OPCODE_MASK
BIND_IMMEDIATE_MASK
Definition at line 244 of file Support/MachO.h.
anonymous enum
Enumerator
EXPORT_SYMBOL_FLAGS_KIND_MASK
EXPORT_SYMBOL_FLAGS_WEAK_DEFINITION
EXPORT_SYMBOL_FLAGS_REEXPORT
EXPORT_SYMBOL_FLAGS_STUB_AND_RESOLVER
Definition at line 268 of file Support/MachO.h.
anonymous enum
Enumerator
N_STAB
N_PEXT
N_TYPE
N_EXT
Definition at line 281 of file Support/MachO.h.
anonymous enum
Enumerator
N_ARM_THUMB_DEF
N_NO_DEAD_STRIP
N_WEAK_REF
N_WEAK_DEF
N_SYMBOL_RESOLVER
Definition at line 307 of file Support/MachO.h.
anonymous enum
Enumerator
VM_PROT_READ
VM_PROT_WRITE
VM_PROT_EXECUTE
Definition at line 423 of file Support/MachO.h.
anonymous enum
Enumerator
CPU_SUBTYPE_INTEL_FAMILY_MAX
CPU_SUBTYPE_INTEL_MODEL_ALL
Definition at line 963 of file Support/MachO.h.
enum llvm::MachO::BindOpcode
Enumerator
BIND_OPCODE_DONE
BIND_OPCODE_SET_DYLIB_ORDINAL_IMM
BIND_OPCODE_SET_DYLIB_ORDINAL_ULEB
BIND_OPCODE_SET_DYLIB_SPECIAL_IMM
BIND_OPCODE_SET_SYMBOL_TRAILING_FLAGS_IMM
BIND_OPCODE_SET_TYPE_IMM
BIND_OPCODE_SET_ADDEND_SLEB
BIND_OPCODE_SET_SEGMENT_AND_OFFSET_ULEB
BIND_OPCODE_ADD_ADDR_ULEB
BIND_OPCODE_DO_BIND
BIND_OPCODE_DO_BIND_ADD_ADDR_ULEB
BIND_OPCODE_DO_BIND_ADD_ADDR_IMM_SCALED
BIND_OPCODE_DO_BIND_ULEB_TIMES_SKIPPING_ULEB
Definition at line 252 of file Support/MachO.h.
enum llvm::MachO::BindSpecialDylib
Enumerator
BIND_SPECIAL_DYLIB_SELF
BIND_SPECIAL_DYLIB_MAIN_EXECUTABLE
BIND_SPECIAL_DYLIB_FLAT_LOOKUP
Definition at line 238 of file Support/MachO.h.
enum llvm::MachO::BindType
Enumerator
BIND_TYPE_POINTER
BIND_TYPE_TEXT_ABSOLUTE32
BIND_TYPE_TEXT_PCREL32
Definition at line 232 of file Support/MachO.h.
enum llvm::MachO::CPUSubTypeARM
Enumerator
CPU_SUBTYPE_ARM_ALL
CPU_SUBTYPE_ARM_V4T
CPU_SUBTYPE_ARM_V6
CPU_SUBTYPE_ARM_V5
CPU_SUBTYPE_ARM_V5TEJ
CPU_SUBTYPE_ARM_XSCALE
CPU_SUBTYPE_ARM_V7
CPU_SUBTYPE_ARM_V7F
CPU_SUBTYPE_ARM_V7S
CPU_SUBTYPE_ARM_V7K
CPU_SUBTYPE_ARM_V6M
CPU_SUBTYPE_ARM_V7M
CPU_SUBTYPE_ARM_V7EM
Definition at line 968 of file Support/MachO.h.
enum llvm::MachO::CPUSubTypePowerPC
Enumerator
CPU_SUBTYPE_POWERPC_ALL
CPU_SUBTYPE_POWERPC_601
CPU_SUBTYPE_POWERPC_602
CPU_SUBTYPE_POWERPC_603
CPU_SUBTYPE_POWERPC_603e
CPU_SUBTYPE_POWERPC_603ev
CPU_SUBTYPE_POWERPC_604
CPU_SUBTYPE_POWERPC_604e
CPU_SUBTYPE_POWERPC_620
CPU_SUBTYPE_POWERPC_750
CPU_SUBTYPE_POWERPC_7400
CPU_SUBTYPE_POWERPC_7450
CPU_SUBTYPE_POWERPC_970
CPU_SUBTYPE_MC980000_ALL
CPU_SUBTYPE_MC98601
Definition at line 988 of file Support/MachO.h.
enum llvm::MachO::CPUSubTypeSPARC
Enumerator
CPU_SUBTYPE_SPARC_ALL
Definition at line 984 of file Support/MachO.h.
enum llvm::MachO::CPUSubTypeX86
Enumerator
CPU_SUBTYPE_I386_ALL
CPU_SUBTYPE_386
CPU_SUBTYPE_486
CPU_SUBTYPE_486SX
CPU_SUBTYPE_586
CPU_SUBTYPE_PENT
CPU_SUBTYPE_PENTPRO
CPU_SUBTYPE_PENTII_M3
CPU_SUBTYPE_PENTII_M5
CPU_SUBTYPE_CELERON
CPU_SUBTYPE_CELERON_MOBILE
CPU_SUBTYPE_PENTIUM_3
CPU_SUBTYPE_PENTIUM_3_M
CPU_SUBTYPE_PENTIUM_3_XEON
CPU_SUBTYPE_PENTIUM_M
CPU_SUBTYPE_PENTIUM_4
CPU_SUBTYPE_PENTIUM_4_M
CPU_SUBTYPE_ITANIUM
CPU_SUBTYPE_ITANIUM_2
CPU_SUBTYPE_XEON
CPU_SUBTYPE_XEON_MP
CPU_SUBTYPE_X86_ALL
CPU_SUBTYPE_X86_64_ALL
CPU_SUBTYPE_X86_ARCH1
CPU_SUBTYPE_X86_64_H
Definition at line 926 of file Support/MachO.h.
enum llvm::MachO::CPUType
Enumerator
CPU_TYPE_ANY
CPU_TYPE_X86
CPU_TYPE_I386
CPU_TYPE_X86_64
CPU_TYPE_MC98000
CPU_TYPE_ARM
CPU_TYPE_SPARC
CPU_TYPE_POWERPC
CPU_TYPE_POWERPC64
Definition at line 903 of file Support/MachO.h.
enum llvm::MachO::DataRegionType
Enumerator
DICE_KIND_DATA
DICE_KIND_JUMP_TABLE8
DICE_KIND_JUMP_TABLE16
DICE_KIND_JUMP_TABLE32
DICE_KIND_ABS_JUMP_TABLE32
Definition at line 200 of file Support/MachO.h.
enum llvm::MachO::ExportSymbolKind
Enumerator
EXPORT_SYMBOL_FLAGS_KIND_REGULAR
EXPORT_SYMBOL_FLAGS_KIND_THREAD_LOCAL
Definition at line 275 of file Support/MachO.h.
enum llvm::MachO::HeaderFileType
Enumerator
MH_OBJECT
MH_EXECUTE
MH_FVMLIB
MH_CORE
MH_PRELOAD
MH_DYLIB
MH_DYLINKER
MH_BUNDLE
MH_DYLIB_STUB
MH_DSYM
MH_KEXT_BUNDLE
Definition at line 35 of file Support/MachO.h.
enum llvm::MachO::NListType
Enumerator
N_UNDF
N_ABS
N_SECT
N_PBUD
N_INDR
Definition at line 290 of file Support/MachO.h.
enum llvm::MachO::RebaseOpcode
Enumerator
REBASE_OPCODE_DONE
REBASE_OPCODE_SET_TYPE_IMM
REBASE_OPCODE_SET_SEGMENT_AND_OFFSET_ULEB
REBASE_OPCODE_ADD_ADDR_ULEB
REBASE_OPCODE_ADD_ADDR_IMM_SCALED
REBASE_OPCODE_DO_REBASE_IMM_TIMES
REBASE_OPCODE_DO_REBASE_ULEB_TIMES
REBASE_OPCODE_DO_REBASE_ADD_ADDR_ULEB
REBASE_OPCODE_DO_REBASE_ULEB_TIMES_SKIPPING_ULEB
Definition at line 220 of file Support/MachO.h.
enum llvm::MachO::RebaseType
Enumerator
REBASE_TYPE_POINTER
REBASE_TYPE_TEXT_ABSOLUTE32
REBASE_TYPE_TEXT_PCREL32
Definition at line 209 of file Support/MachO.h.
enum llvm::MachO::RelocationInfoType
Enumerator
GENERIC_RELOC_VANILLA
GENERIC_RELOC_PAIR
GENERIC_RELOC_SECTDIFF
GENERIC_RELOC_PB_LA_PTR
GENERIC_RELOC_LOCAL_SECTDIFF
GENERIC_RELOC_TLV
PPC_RELOC_VANILLA
PPC_RELOC_PAIR
PPC_RELOC_BR14
PPC_RELOC_BR24
PPC_RELOC_HI16
PPC_RELOC_LO16
PPC_RELOC_HA16
PPC_RELOC_LO14
PPC_RELOC_SECTDIFF
PPC_RELOC_PB_LA_PTR
PPC_RELOC_HI16_SECTDIFF
PPC_RELOC_LO16_SECTDIFF
PPC_RELOC_HA16_SECTDIFF
PPC_RELOC_JBSR
PPC_RELOC_LO14_SECTDIFF
PPC_RELOC_LOCAL_SECTDIFF
ARM_RELOC_VANILLA
ARM_RELOC_PAIR
ARM_RELOC_SECTDIFF
ARM_RELOC_LOCAL_SECTDIFF
ARM_RELOC_PB_LA_PTR
ARM_RELOC_BR24
ARM_THUMB_RELOC_BR22
ARM_THUMB_32BIT_BRANCH
ARM_RELOC_HALF
ARM_RELOC_HALF_SECTDIFF
X86_64_RELOC_UNSIGNED
X86_64_RELOC_SIGNED
X86_64_RELOC_BRANCH
X86_64_RELOC_GOT_LOAD
X86_64_RELOC_GOT
X86_64_RELOC_SUBTRACTOR
X86_64_RELOC_SIGNED_1
X86_64_RELOC_SIGNED_2
X86_64_RELOC_SIGNED_4
X86_64_RELOC_TLV
Definition at line 361 of file Support/MachO.h.
enum llvm::MachO::SectionOrdinal
Enumerator
NO_SECT
MAX_SECT
Definition at line 300 of file Support/MachO.h.
enum llvm::MachO::SectionType
Enumerator
S_REGULAR
S_ZEROFILL
S_CSTRING_LITERALS
S_4BYTE_LITERALS
S_8BYTE_LITERALS
S_LITERAL_POINTERS
S_NON_LAZY_SYMBOL_POINTERS
S_LAZY_SYMBOL_POINTERS
S_SYMBOL_STUBS
S_MOD_INIT_FUNC_POINTERS
S_MOD_TERM_FUNC_POINTERS
S_COALESCED
S_GB_ZEROFILL
S_INTERPOSING
S_16BYTE_LITERALS
S_DTRACE_DOF
S_LAZY_DYLIB_SYMBOL_POINTERS
S_THREAD_LOCAL_REGULAR
S_THREAD_LOCAL_ZEROFILL
S_THREAD_LOCAL_VARIABLES
S_THREAD_LOCAL_VARIABLE_POINTERS
S_THREAD_LOCAL_INIT_FUNCTION_POINTERS
Definition at line 150 of file Support/MachO.h.
enum llvm::MachO::StabType
Enumerator
N_GSYM
N_FNAME
N_FUN
N_STSYM
N_LCSYM
N_BNSYM
N_OPT
N_RSYM
N_SLINE
N_ENSYM
N_SSYM
N_SO
N_OSO
N_LSYM
N_BINCL
N_SOL
N_PARAMS
N_VERSION
N_OLEVEL
N_PSYM
N_EINCL
N_ENTRY
N_LBRAC
N_EXCL
N_RBRAC
N_BCOMM
N_ECOMM
N_ECOML
N_LENG
Definition at line 317 of file Support/MachO.h.
Function Documentation
static int llvm::MachO::CPU_SUBTYPE_INTEL (int Family, int Model) inline static
Definition at line 954 of file Support/MachO.h.
static int llvm::MachO::CPU_SUBTYPE_INTEL_FAMILY (CPUSubTypeX86 ST) inline static
Definition at line 957 of file Support/MachO.h.
static int llvm::MachO::CPU_SUBTYPE_INTEL_MODEL (CPUSubTypeX86 ST) inline static
Definition at line 960 of file Support/MachO.h.
static uint8_t llvm::MachO::GET_COMM_ALIGN (uint16_t n_desc) inline static
Definition at line 887 of file Support/MachO.h.
Referenced by llvm::object::MachOObjectFile::getSymbolAlignment().
static uint16_t llvm::MachO::GET_LIBRARY_ORDINAL (uint16_t n_desc) inline static
Definition at line 879 of file Support/MachO.h.
enum llvm::MachO::LLVM_ENUM_INT_TYPE (uint32_t)
Definition at line 24 of file Support/MachO.h.
Referenced by SET_COMM_ALIGN().
static void llvm::MachO::SET_COMM_ALIGN (uint16_t & n_desc, uint8_t align) inline static
Definition at line 891 of file Support/MachO.h.
References LLVM_ENUM_INT_TYPE().
static void llvm::MachO::SET_LIBRARY_ORDINAL (uint16_t & n_desc, uint8_t ordinal) inline static
Definition at line 883 of file Support/MachO.h.