LLVM: PBQP Namespace Reference
LLVM API Documentation
PBQP Namespace Reference
Namespaces
Heuristics
Classes
class Graph
class HeuristicBase
Abstract base class for heuristic implementations.
class HeuristicSolver
PBQP heuristic solver class.
class HeuristicSolverImpl
Heuristic PBQP solver implementation.
class Matrix
PBQP Matrix class.
class Solution
Represents a solution to a PBQP problem.
class Vector
PBQP Vector class.
Typedefs
typedef float PBQPNum
Functions
template<typename OStream >
OStream & operator<< (OStream &os, const Vector &v)
Output a textual representation of the given vector on the given output stream.
template<typename OStream >
OStream & operator<< (OStream &os, const Matrix &m)
Output a textual representation of the given matrix on the given output stream.
Typedef Documentation
typedef float PBQP::PBQPNum
Definition at line 19 of file Math.h.
Function Documentation
template<typename OStream > OStream& PBQP::operator<< (OStream & os, const Vector & v)
Output a textual representation of the given vector on the given output stream.
Definition at line 98 of file Math.h.
References PBQP::Vector::getLength(), and i.
template<typename OStream > OStream& PBQP::operator<< (OStream & os, const Matrix & m)
Output a textual representation of the given matrix on the given output stream.
Definition at line 275 of file Math.h.
References PBQP::Matrix::getRowAsVector(), PBQP::Matrix::getRows(), and i.