var namespacellvm_1_1PatternMatch =
[
    [ "api_pred_ty", "structllvm_1_1PatternMatch_1_1api__pred__ty.html", "structllvm_1_1PatternMatch_1_1api__pred__ty" ],
    [ "apint_match", "structllvm_1_1PatternMatch_1_1apint__match.html", "structllvm_1_1PatternMatch_1_1apint__match" ],
    [ "Argument_match", "structllvm_1_1PatternMatch_1_1Argument__match.html", "structllvm_1_1PatternMatch_1_1Argument__match" ],
    [ "BinaryOp_match", "structllvm_1_1PatternMatch_1_1BinaryOp__match.html", "structllvm_1_1PatternMatch_1_1BinaryOp__match" ],
    [ "bind_const_intval_ty", "structllvm_1_1PatternMatch_1_1bind__const__intval__ty.html", "structllvm_1_1PatternMatch_1_1bind__const__intval__ty" ],
    [ "bind_ty", "structllvm_1_1PatternMatch_1_1bind__ty.html", "structllvm_1_1PatternMatch_1_1bind__ty" ],
    [ "BinOp2_match", "structllvm_1_1PatternMatch_1_1BinOp2__match.html", "structllvm_1_1PatternMatch_1_1BinOp2__match" ],
    [ "br_match", "structllvm_1_1PatternMatch_1_1br__match.html", "structllvm_1_1PatternMatch_1_1br__match" ],
    [ "brc_match", "structllvm_1_1PatternMatch_1_1brc__match.html", "structllvm_1_1PatternMatch_1_1brc__match" ],
    [ "CastClass_match", "structllvm_1_1PatternMatch_1_1CastClass__match.html", "structllvm_1_1PatternMatch_1_1CastClass__match" ],
    [ "class_match", "structllvm_1_1PatternMatch_1_1class__match.html", "structllvm_1_1PatternMatch_1_1class__match" ],
    [ "CmpClass_match", "structllvm_1_1PatternMatch_1_1CmpClass__match.html", "structllvm_1_1PatternMatch_1_1CmpClass__match" ],
    [ "constantint_match", "structllvm_1_1PatternMatch_1_1constantint__match.html", "structllvm_1_1PatternMatch_1_1constantint__match" ],
    [ "cst_pred_ty", "structllvm_1_1PatternMatch_1_1cst__pred__ty.html", "structllvm_1_1PatternMatch_1_1cst__pred__ty" ],
    [ "Exact_match", "structllvm_1_1PatternMatch_1_1Exact__match.html", "structllvm_1_1PatternMatch_1_1Exact__match" ],
    [ "fneg_match", "structllvm_1_1PatternMatch_1_1fneg__match.html", "structllvm_1_1PatternMatch_1_1fneg__match" ],
    [ "IntrinsicID_match", "structllvm_1_1PatternMatch_1_1IntrinsicID__match.html", "structllvm_1_1PatternMatch_1_1IntrinsicID__match" ],
    [ "is_all_ones", "structllvm_1_1PatternMatch_1_1is__all__ones.html", "structllvm_1_1PatternMatch_1_1is__all__ones" ],
    [ "is_one", "structllvm_1_1PatternMatch_1_1is__one.html", "structllvm_1_1PatternMatch_1_1is__one" ],
    [ "is_power2", "structllvm_1_1PatternMatch_1_1is__power2.html", "structllvm_1_1PatternMatch_1_1is__power2" ],
    [ "is_sign_bit", "structllvm_1_1PatternMatch_1_1is__sign__bit.html", "structllvm_1_1PatternMatch_1_1is__sign__bit" ],
    [ "m_Intrinsic_Ty", "structllvm_1_1PatternMatch_1_1m__Intrinsic__Ty.html", null ],
    [ "m_Intrinsic_Ty< T0 >", "structllvm_1_1PatternMatch_1_1m__Intrinsic__Ty_3_01T0_01_4.html", "structllvm_1_1PatternMatch_1_1m__Intrinsic__Ty_3_01T0_01_4" ],
    [ "m_Intrinsic_Ty< T0, T1 >", "structllvm_1_1PatternMatch_1_1m__Intrinsic__Ty_3_01T0_00_01T1_01_4.html", "structllvm_1_1PatternMatch_1_1m__Intrinsic__Ty_3_01T0_00_01T1_01_4" ],
    [ "m_Intrinsic_Ty< T0, T1, T2 >", "structllvm_1_1PatternMatch_1_1m__Intrinsic__Ty_3_01T0_00_01T1_00_01T2_01_4.html", "structllvm_1_1PatternMatch_1_1m__Intrinsic__Ty_3_01T0_00_01T1_00_01T2_01_4" ],
    [ "m_Intrinsic_Ty< T0, T1, T2, T3 >", "structllvm_1_1PatternMatch_1_1m__Intrinsic__Ty_3_01T0_00_01T1_00_01T2_00_01T3_01_4.html", "structllvm_1_1PatternMatch_1_1m__Intrinsic__Ty_3_01T0_00_01T1_00_01T2_00_01T3_01_4" ],
    [ "match_combine_and", "structllvm_1_1PatternMatch_1_1match__combine__and.html", "structllvm_1_1PatternMatch_1_1match__combine__and" ],
    [ "match_combine_or", "structllvm_1_1PatternMatch_1_1match__combine__or.html", "structllvm_1_1PatternMatch_1_1match__combine__or" ],
    [ "match_neg_zero", "structllvm_1_1PatternMatch_1_1match__neg__zero.html", "structllvm_1_1PatternMatch_1_1match__neg__zero" ],
    [ "match_zero", "structllvm_1_1PatternMatch_1_1match__zero.html", "structllvm_1_1PatternMatch_1_1match__zero" ],
    [ "MaxMin_match", "structllvm_1_1PatternMatch_1_1MaxMin__match.html", "structllvm_1_1PatternMatch_1_1MaxMin__match" ],
    [ "neg_match", "structllvm_1_1PatternMatch_1_1neg__match.html", "structllvm_1_1PatternMatch_1_1neg__match" ],
    [ "not_match", "structllvm_1_1PatternMatch_1_1not__match.html", "structllvm_1_1PatternMatch_1_1not__match" ],
    [ "ofmax_pred_ty", "structllvm_1_1PatternMatch_1_1ofmax__pred__ty.html", "structllvm_1_1PatternMatch_1_1ofmax__pred__ty" ],
    [ "ofmin_pred_ty", "structllvm_1_1PatternMatch_1_1ofmin__pred__ty.html", "structllvm_1_1PatternMatch_1_1ofmin__pred__ty" ],
    [ "OneUse_match", "structllvm_1_1PatternMatch_1_1OneUse__match.html", "structllvm_1_1PatternMatch_1_1OneUse__match" ],
    [ "SelectClass_match", "structllvm_1_1PatternMatch_1_1SelectClass__match.html", "structllvm_1_1PatternMatch_1_1SelectClass__match" ],
    [ "smax_pred_ty", "structllvm_1_1PatternMatch_1_1smax__pred__ty.html", "structllvm_1_1PatternMatch_1_1smax__pred__ty" ],
    [ "smin_pred_ty", "structllvm_1_1PatternMatch_1_1smin__pred__ty.html", "structllvm_1_1PatternMatch_1_1smin__pred__ty" ],
    [ "specific_fpval", "structllvm_1_1PatternMatch_1_1specific__fpval.html", "structllvm_1_1PatternMatch_1_1specific__fpval" ],
    [ "specificval_ty", "structllvm_1_1PatternMatch_1_1specificval__ty.html", "structllvm_1_1PatternMatch_1_1specificval__ty" ],
    [ "ufmax_pred_ty", "structllvm_1_1PatternMatch_1_1ufmax__pred__ty.html", "structllvm_1_1PatternMatch_1_1ufmax__pred__ty" ],
    [ "ufmin_pred_ty", "structllvm_1_1PatternMatch_1_1ufmin__pred__ty.html", "structllvm_1_1PatternMatch_1_1ufmin__pred__ty" ],
    [ "umax_pred_ty", "structllvm_1_1PatternMatch_1_1umax__pred__ty.html", "structllvm_1_1PatternMatch_1_1umax__pred__ty" ],
    [ "umin_pred_ty", "structllvm_1_1PatternMatch_1_1umin__pred__ty.html", "structllvm_1_1PatternMatch_1_1umin__pred__ty" ]
];