LLVM: llvm::object Namespace Reference
LLVM API Documentation
llvm::object Namespace Reference
Namespaces
yaml
Classes
class Archive
struct ArchiveMemberHeader
class Binary
struct coff_aux_section_definition
struct coff_aux_weak_external
struct coff_file_header
struct coff_relocation
struct coff_section
struct coff_symbol
class COFFObjectFile
class content_iterator
struct data_directory
union DataRefImpl
class DiceRef
struct dos_header
The DOS compatible header at the front of all PE/COFF executables.
struct Elf_Dyn_Base
struct Elf_Dyn_Base< ELFType< TargetEndianness, MaxAlign, false > >
struct Elf_Dyn_Base< ELFType< TargetEndianness, MaxAlign, true > >
struct Elf_Dyn_Impl
Elf_Dyn_Impl: This inherits from Elf_Dyn_Base, adding getters and setters.
struct Elf_Ehdr_Impl
struct Elf_Phdr_Impl
struct Elf_Phdr_Impl< ELFType< TargetEndianness, MaxAlign, false > >
struct Elf_Phdr_Impl< ELFType< TargetEndianness, MaxAlign, true > >
struct Elf_Rel_Base
struct Elf_Rel_Base< ELFType< TargetEndianness, MaxAlign, false >, false >
struct Elf_Rel_Base< ELFType< TargetEndianness, MaxAlign, false >, true >
struct Elf_Rel_Base< ELFType< TargetEndianness, MaxAlign, true >, false >
struct Elf_Rel_Base< ELFType< TargetEndianness, MaxAlign, true >, true >
struct Elf_Rel_Impl
struct Elf_Rel_Impl< ELFType< TargetEndianness, MaxAlign, false >, isRela >
struct Elf_Rel_Impl< ELFType< TargetEndianness, MaxAlign, true >, isRela >
struct Elf_Shdr_Base
struct Elf_Shdr_Base< ELFType< TargetEndianness, MaxAlign, false > >
struct Elf_Shdr_Base< ELFType< TargetEndianness, MaxAlign, true > >
struct Elf_Shdr_Impl
struct Elf_Sym_Base
struct Elf_Sym_Base< ELFType< TargetEndianness, MaxAlign, false > >
struct Elf_Sym_Base< ELFType< TargetEndianness, MaxAlign, true > >
struct Elf_Sym_Impl
struct Elf_Verdaux_Impl
struct Elf_Verdef_Impl
struct Elf_Vernaux_Impl
struct Elf_Verneed_Impl
struct Elf_Versym_Impl
struct ELFDataTypeTypedefHelper
struct ELFDataTypeTypedefHelper< ELFType< TargetEndianness, MaxAlign, false > >
ELF 32bit types.
struct ELFDataTypeTypedefHelper< ELFType< TargetEndianness, MaxAlign, true > >
ELF 64bit types.
struct ELFDataTypeTypedefHelperCommon
class ELFFile
class ELFObjectFile
struct ELFType
struct import_directory_table_entry
struct import_lookup_table_entry32
class ImportDirectoryEntryRef
class LibraryRef
class MachOObjectFile
class MachOUniversalBinary
struct MaximumAlignment
struct nlist_base
struct object_error
class ObjectFile
struct pe32_header
The 32-bit PE header that follows the COFF header.
struct pe32plus_header
The 64-bit PE header that follows the COFF header.
class RelocationRef
struct RelocToApply
class RelocVisitor
Base class for object file relocation visitors.
struct section_base
class SectionRef
class SymbolRef
Typedefs
typedef content_iterator< ImportDirectoryEntryRef > import_directory_iterator
typedef ELFFile< ELFType< support::little, 2, false > > ELF32LEFile
typedef ELFFile< ELFType< support::little, 2, true > > ELF64LEFile
typedef ELFFile< ELFType< support::big, 2, false > > ELF32BEFile
typedef ELFFile< ELFType< support::big, 2, true > > ELF64BEFile
typedef ELFObjectFile< ELFType< support::little, 2, false > > ELF32LEObjectFile
typedef ELFObjectFile< ELFType< support::little, 2, true > > ELF64LEObjectFile
typedef ELFObjectFile< ELFType< support::big, 2, false > > ELF32BEObjectFile
typedef ELFObjectFile< ELFType< support::big, 2, true > > ELF64BEObjectFile
typedef content_iterator< DiceRef > dice_iterator
typedef content_iterator< SymbolRef > symbol_iterator
typedef content_iterator< RelocationRef > relocation_iterator
typedef content_iterator< SectionRef > section_iterator
typedef content_iterator< LibraryRef > library_iterator
Functions
error_code createBinary (MemoryBuffer *Source, OwningPtr< Binary > &Result)
Create a Binary from Source, autodetecting the file type.
error_code createBinary (StringRef Path, OwningPtr< Binary > &Result)
StringRef getELFRelocationTypeName (uint32_t Machine, uint32_t Type)
std::pair< unsigned char, unsigned char > getElfArchType (MemoryBuffer *Object)
static unsigned elf_hash (StringRef &symbolName)
static error_code getELFRelocationAddend (const RelocationRef R, int64_t &Addend)
static error_code GetELFSymbolVersion (const ObjectFile *Obj, const SymbolRef &Sym, StringRef &Version, bool &IsDefault)
const error_category & object_category ()
error_code make_error_code (object_error e)
bool operator== (const DataRefImpl &a, const DataRefImpl &b)
bool operator< (const DataRefImpl &a, const DataRefImpl &b)
template<typename T >
static void SwapValue (T &Value)
template<typename T >
static void SwapStruct (T &Value)
template<>
void SwapStruct (MachO::any_relocation_info &H)
template<>
void SwapStruct (MachO::load_command &L)
template<>
void SwapStruct (nlist_base &S)
template<>
void SwapStruct (MachO::section &S)
template<>
void SwapStruct (MachO::section_64 &S)
template<>
void SwapStruct (MachO::nlist &S)
template<>
void SwapStruct (MachO::nlist_64 &S)
template<>
void SwapStruct (MachO::mach_header &H)
template<>
void SwapStruct (MachO::mach_header_64 &H)
template<>
void SwapStruct (MachO::symtab_command &C)
template<>
void SwapStruct (MachO::dysymtab_command &C)
template<>
void SwapStruct (MachO::linkedit_data_command &C)
template<>
void SwapStruct (MachO::segment_command &C)
template<>
void SwapStruct (MachO::segment_command_64 &C)
template<>
void SwapStruct (uint32_t &C)
template<>
void SwapStruct (MachO::linker_options_command &C)
template<>
void SwapStruct (MachO::data_in_code_entry &C)
template<typename T >
T getStruct (const MachOObjectFile *O, const char *P)
static uint32_t getSegmentLoadCommandNumSections (const MachOObjectFile *O, const MachOObjectFile::LoadCommandInfo &L)
static const char * getSectionPtr (const MachOObjectFile *O, MachOObjectFile::LoadCommandInfo L, unsigned Sec)
static const char * getPtr (const MachOObjectFile *O, size_t Offset)
static nlist_base getSymbolTableEntryBase (const MachOObjectFile *O, DataRefImpl DRI)
static StringRef parseSegmentOrSectionName (const char *P)
template<class T >
static error_code advance (T &it, size_t Val)
template<class T >
static void advanceTo (T &it, size_t Val)
static unsigned getCPUType (const MachOObjectFile *O)
static void printRelocationTargetName (const MachOObjectFile *O, const MachO::any_relocation_info &RE, raw_string_ostream &fmt)
static uint32_t getPlainRelocationAddress (const MachO::any_relocation_info &RE)
static unsigned getScatteredRelocationAddress (const MachO::any_relocation_info &RE)
static bool getPlainRelocationPCRel (const MachOObjectFile *O, const MachO::any_relocation_info &RE)
static bool getScatteredRelocationPCRel (const MachOObjectFile *O, const MachO::any_relocation_info &RE)
static unsigned getPlainRelocationLength (const MachOObjectFile *O, const MachO::any_relocation_info &RE)
static unsigned getScatteredRelocationLength (const MachO::any_relocation_info &RE)
static unsigned getPlainRelocationType (const MachOObjectFile *O, const MachO::any_relocation_info &RE)
static unsigned getScatteredRelocationType (const MachO::any_relocation_info &RE)
static uint32_t getSectionFlags (const MachOObjectFile *O, DataRefImpl Sec)
Variables
const uint64_t UnknownAddressOrSize = ~0ULL
Typedef Documentation
typedef content_iterator<DiceRef> llvm::object::dice_iterator
Definition at line 50 of file Object/MachO.h.
typedef ELFFile<ELFType<support::big, 2, false> > llvm::object::ELF32BEFile
Definition at line 416 of file Object/ELF.h.
typedef ELFObjectFile<ELFType<support::big, 2, false> > llvm::object::ELF32BEObjectFile
Definition at line 207 of file ELFObjectFile.h.
typedef ELFFile<ELFType<support::little, 2, false> > llvm::object::ELF32LEFile
Definition at line 414 of file Object/ELF.h.
typedef ELFObjectFile<ELFType<support::little, 2, false> > llvm::object::ELF32LEObjectFile
Definition at line 205 of file ELFObjectFile.h.
typedef ELFFile<ELFType<support::big, 2, true> > llvm::object::ELF64BEFile
Definition at line 417 of file Object/ELF.h.
typedef ELFObjectFile<ELFType<support::big, 2, true> > llvm::object::ELF64BEObjectFile
Definition at line 208 of file ELFObjectFile.h.
typedef ELFFile<ELFType<support::little, 2, true> > llvm::object::ELF64LEFile
Definition at line 415 of file Object/ELF.h.
typedef ELFObjectFile<ELFType<support::little, 2, true> > llvm::object::ELF64LEObjectFile
Definition at line 206 of file ELFObjectFile.h.
typedef content_iterator<ImportDirectoryEntryRef> llvm::object::import_directory_iterator
Definition at line 26 of file Object/COFF.h.
typedef content_iterator<LibraryRef> llvm::object::library_iterator
Definition at line 259 of file ObjectFile.h.
typedef content_iterator<RelocationRef> llvm::object::relocation_iterator
Definition at line 129 of file ObjectFile.h.
typedef content_iterator<SectionRef> llvm::object::section_iterator
Definition at line 133 of file ObjectFile.h.
typedef content_iterator<SymbolRef> llvm::object::symbol_iterator
Definition at line 87 of file ObjectFile.h.
Function Documentation
template<class T > static error_code llvm::object::advance (T & it, size_t Val) static
Definition at line 278 of file MachOObjectFile.cpp.
Referenced by llvm::SchedDFSImpl::addConnection(), llvm::BitstreamCursor::advanceSkippingSubblocks(), advanceTo(), llvm::IntervalMapOverlaps< MapA, MapB >::advanceTo(), llvm::MipsTargetLowering::MipsCC::analyzeFormalArguments(), CalculateStackSlotSize(), FindPhiPredForUseInBlock(), llvm::DOTGraphTraits< SelectionDAG * >::getEdgeTarget(), getGEPInductionOperand(), llvm::MipsTargetLowering::getOpndList(), INITIALIZE_PASS(), llvm::IntervalMapOverlaps< MapA, MapB >::IntervalMapOverlaps(), LowerVASTART(), MarkIndicesSafe(), llvm::MCRegUnitIterator::MCRegUnitIterator(), llvm::next(), llvm::MCRegisterInfo::DiffListIterator::operator++(), llvm::MCRegAliasIterator::operator++(), llvm::FoldingSetIterator< T >::operator++(), llvm::FoldingSetBucketIterator< T >::operator++(), llvm::prior(), llvm::RegPressureTracker::setPos(), llvm::IntervalMapOverlaps< MapA, MapB >::skipA(), and llvm::IntervalMapOverlaps< MapA, MapB >::skipB().
template<class T > static void llvm::object::advanceTo (T & it, size_t Val) static
Definition at line 287 of file MachOObjectFile.cpp.
References advance(), and llvm::report_fatal_error().
Referenced by printRelocationTargetName().
error_code llvm::object::createBinary (MemoryBuffer * Source, OwningPtr< Binary > & Result)
Create a Binary from Source, autodetecting the file type.
Parameters
Source The data to create the Binary from. Ownership is transferred to Result if successful. If an error is returned, Source is destroyed by createBinary before returning.
Result A pointer to the resulting Binary if no error occured.
Definition at line 45 of file Binary.cpp.
References llvm::sys::fs::file_magic::archive, llvm::sys::fs::file_magic::bitcode, llvm::sys::fs::file_magic::coff_import_library, llvm::sys::fs::file_magic::coff_object, llvm::object::ObjectFile::createCOFFObjectFile(), llvm::object::ObjectFile::createELFObjectFile(), llvm::object::ObjectFile::createMachOObjectFile(), llvm::sys::fs::file_magic::elf_core, llvm::sys::fs::file_magic::elf_executable, llvm::sys::fs::file_magic::elf_relocatable, llvm::sys::fs::file_magic::elf_shared_object, llvm::MemoryBuffer::getBuffer(), llvm::sys::fs::identify_magic(), llvm::errc::invalid_argument, llvm::object::object_error::invalid_file_type, llvm_unreachable, llvm::sys::fs::file_magic::macho_bundle, llvm::sys::fs::file_magic::macho_core, llvm::sys::fs::file_magic::macho_dsym_companion, llvm::sys::fs::file_magic::macho_dynamic_linker, llvm::sys::fs::file_magic::macho_dynamically_linked_shared_lib, llvm::sys::fs::file_magic::macho_dynamically_linked_shared_lib_stub, llvm::sys::fs::file_magic::macho_executable, llvm::sys::fs::file_magic::macho_fixed_virtual_memory_shared_lib, llvm::sys::fs::file_magic::macho_object, llvm::sys::fs::file_magic::macho_preload_executable, llvm::sys::fs::file_magic::macho_universal_binary, make_error_code(), llvm::sys::fs::file_magic::pecoff_executable, ret(), llvm::object::object_error::success, llvm::OwningPtr< T >::swap(), llvm::OwningPtr< T >::take(), type, llvm::sys::fs::file_magic::unknown, and llvm::sys::fs::file_magic::windows_resource.
Referenced by createBinary(), llvm::object::Archive::Child::getAsBinary(), and llvm::object::Binary::isLittleEndian().
error_code llvm::object::createBinary (StringRef Path, OwningPtr< Binary > & Result)
Definition at line 113 of file Binary.cpp.
References createBinary(), llvm::ARMBuildAttrs::File, llvm::MemoryBuffer::getFileOrSTDIN(), and llvm::OwningPtr< T >::take().
static unsigned llvm::object::elf_hash (StringRef & symbolName) inline static
This function returns the hash value for a symbol in the .dynsym section Name of the API remains consistent as specified in the libelf REF : http://www.sco.com/developers/gabi/latest/ch5.dynamic.html#hash
Definition at line 991 of file Object/ELF.h.
References g, h, i, j(), and llvm::StringRef::size().
static unsigned llvm::object::getCPUType (const MachOObjectFile * O) static
Definition at line 292 of file MachOObjectFile.cpp.
References llvm::MachO::mach_header::cputype, and llvm::object::MachOObjectFile::getHeader().
Referenced by llvm::object::MachOObjectFile::getArch(), llvm::object::MachOObjectFile::getFileFormatName(), and llvm::object::MachOObjectFile::isRelocationScattered().
std::pair<unsigned char, unsigned char> llvm::object::getElfArchType (MemoryBuffer * Object) inline
Definition at line 43 of file Object/ELF.h.
References llvm::ELF::EI_CLASS, llvm::ELF::EI_DATA, llvm::ELF::EI_NIDENT, llvm::ELF::ELFCLASSNONE, llvm::ELF::ELFDATANONE, llvm::MemoryBuffer::getBufferSize(), and llvm::MemoryBuffer::getBufferStart().
Referenced by llvm::object::ObjectFile::createELFObjectFile().
static error_code llvm::object::getELFRelocationAddend (const RelocationRef R, int64_t & Addend) inline static
FIXME: Maybe we should have a base ElfObjectFile that is not a template and make these member functions?
Definition at line 977 of file ELFObjectFile.h.
References llvm::object::RelocationRef::getObjectFile(), llvm::object::RelocationRef::getRawDataRefImpl(), and llvm_unreachable.
Referenced by llvm::object::RelocVisitor::error(), llvm::RuntimeDyldELF::processRelocationRef(), and llvm::RuntimeDyldELF::~RuntimeDyldELF().
StringRef llvm::object::getELFRelocationTypeName (uint32_t Machine, uint32_t Type)
Definition at line 19 of file ELF.cpp.
References llvm::ELF::EM_386, llvm::ELF::EM_AARCH64, llvm::ELF::EM_ARM, llvm::ELF::EM_HEXAGON, llvm::ELF::EM_MIPS, llvm::ELF::EM_PPC, llvm::ELF::EM_PPC64, llvm::ELF::EM_S390, llvm::ELF::EM_X86_64, LLVM_ELF_SWITCH_RELOC_TYPE_NAME, llvm::ELF::R_386_16, llvm::ELF::R_386_32, llvm::ELF::R_386_32PLT, llvm::ELF::R_386_8, llvm::ELF::R_386_COPY, llvm::ELF::R_386_GLOB_DAT, llvm::ELF::R_386_GOT32, llvm::ELF::R_386_GOTOFF, llvm::ELF::R_386_GOTPC, llvm::ELF::R_386_IRELATIVE, llvm::ELF::R_386_JUMP_SLOT, llvm::ELF::R_386_NONE, llvm::ELF::R_386_PC16, llvm::ELF::R_386_PC32, llvm::ELF::R_386_PC8, llvm::ELF::R_386_PLT32, llvm::ELF::R_386_RELATIVE, llvm::ELF::R_386_TLS_DESC, llvm::ELF::R_386_TLS_DESC_CALL, llvm::ELF::R_386_TLS_DTPMOD32, llvm::ELF::R_386_TLS_DTPOFF32, llvm::ELF::R_386_TLS_GD, llvm::ELF::R_386_TLS_GD_32, llvm::ELF::R_386_TLS_GD_CALL, llvm::ELF::R_386_TLS_GD_POP, llvm::ELF::R_386_TLS_GD_PUSH, llvm::ELF::R_386_TLS_GOTDESC, llvm::ELF::R_386_TLS_GOTIE, llvm::ELF::R_386_TLS_IE, llvm::ELF::R_386_TLS_IE_32, llvm::ELF::R_386_TLS_LDM, llvm::ELF::R_386_TLS_LDM_32, llvm::ELF::R_386_TLS_LDM_CALL, llvm::ELF::R_386_TLS_LDM_POP, llvm::ELF::R_386_TLS_LDM_PUSH, llvm::ELF::R_386_TLS_LDO_32, llvm::ELF::R_386_TLS_LE, llvm::ELF::R_386_TLS_LE_32, llvm::ELF::R_386_TLS_TPOFF, llvm::ELF::R_386_TLS_TPOFF32, llvm::ELF::R_390_12, llvm::ELF::R_390_16, llvm::ELF::R_390_20, llvm::ELF::R_390_32, llvm::ELF::R_390_64, llvm::ELF::R_390_8, llvm::ELF::R_390_COPY, llvm::ELF::R_390_GLOB_DAT, llvm::ELF::R_390_GOT12, llvm::ELF::R_390_GOT16, llvm::ELF::R_390_GOT20, llvm::ELF::R_390_GOT32, llvm::ELF::R_390_GOT64, llvm::ELF::R_390_GOTENT, llvm::ELF::R_390_GOTOFF, llvm::ELF::R_390_GOTOFF16, llvm::ELF::R_390_GOTOFF64, llvm::ELF::R_390_GOTPC, llvm::ELF::R_390_GOTPCDBL, llvm::ELF::R_390_GOTPLT12, llvm::ELF::R_390_GOTPLT16, llvm::ELF::R_390_GOTPLT20, llvm::ELF::R_390_GOTPLT32, llvm::ELF::R_390_GOTPLT64, llvm::ELF::R_390_GOTPLTENT, llvm::ELF::R_390_IRELATIVE, llvm::ELF::R_390_JMP_SLOT, llvm::ELF::R_390_NONE, llvm::ELF::R_390_PC16, llvm::ELF::R_390_PC16DBL, llvm::ELF::R_390_PC32, llvm::ELF::R_390_PC32DBL, llvm::ELF::R_390_PC64, llvm::ELF::R_390_PLT16DBL, llvm::ELF::R_390_PLT32, llvm::ELF::R_390_PLT32DBL, llvm::ELF::R_390_PLT64, llvm::ELF::R_390_PLTOFF16, llvm::ELF::R_390_PLTOFF32, llvm::ELF::R_390_PLTOFF64, llvm::ELF::R_390_RELATIVE, llvm::ELF::R_390_TLS_DTPMOD, llvm::ELF::R_390_TLS_DTPOFF, llvm::ELF::R_390_TLS_GD32, llvm::ELF::R_390_TLS_GD64, llvm::ELF::R_390_TLS_GDCALL, llvm::ELF::R_390_TLS_GOTIE12, llvm::ELF::R_390_TLS_GOTIE20, llvm::ELF::R_390_TLS_GOTIE32, llvm::ELF::R_390_TLS_GOTIE64, llvm::ELF::R_390_TLS_IE32, llvm::ELF::R_390_TLS_IE64, llvm::ELF::R_390_TLS_IEENT, llvm::ELF::R_390_TLS_LDCALL, llvm::ELF::R_390_TLS_LDM32, llvm::ELF::R_390_TLS_LDM64, llvm::ELF::R_390_TLS_LDO32, llvm::ELF::R_390_TLS_LDO64, llvm::ELF::R_390_TLS_LE32, llvm::ELF::R_390_TLS_LE64, llvm::ELF::R_390_TLS_LOAD, llvm::ELF::R_390_TLS_TPOFF, llvm::ELF::R_AARCH64_ABS16, llvm::ELF::R_AARCH64_ABS32, llvm::ELF::R_AARCH64_ABS64, llvm::ELF::R_AARCH64_ADD_ABS_LO12_NC, llvm::ELF::R_AARCH64_ADR_GOT_PAGE, llvm::ELF::R_AARCH64_ADR_PREL_LO21, llvm::ELF::R_AARCH64_ADR_PREL_PG_HI21, llvm::ELF::R_AARCH64_CALL26, llvm::ELF::R_AARCH64_CONDBR19, llvm::ELF::R_AARCH64_JUMP26, llvm::ELF::R_AARCH64_LD64_GOT_LO12_NC, llvm::ELF::R_AARCH64_LD_PREL_LO19, llvm::ELF::R_AARCH64_LDST128_ABS_LO12_NC, llvm::ELF::R_AARCH64_LDST16_ABS_LO12_NC, llvm::ELF::R_AARCH64_LDST32_ABS_LO12_NC, llvm::ELF::R_AARCH64_LDST64_ABS_LO12_NC, llvm::ELF::R_AARCH64_LDST8_ABS_LO12_NC, llvm::ELF::R_AARCH64_MOVW_SABS_G0, llvm::ELF::R_AARCH64_MOVW_SABS_G1, llvm::ELF::R_AARCH64_MOVW_SABS_G2, llvm::ELF::R_AARCH64_MOVW_UABS_G0, llvm::ELF::R_AARCH64_MOVW_UABS_G0_NC, llvm::ELF::R_AARCH64_MOVW_UABS_G1, llvm::ELF::R_AARCH64_MOVW_UABS_G1_NC, llvm::ELF::R_AARCH64_MOVW_UABS_G2, llvm::ELF::R_AARCH64_MOVW_UABS_G2_NC, llvm::ELF::R_AARCH64_MOVW_UABS_G3, llvm::ELF::R_AARCH64_NONE, llvm::ELF::R_AARCH64_PREL16, llvm::ELF::R_AARCH64_PREL32, llvm::ELF::R_AARCH64_PREL64, llvm::ELF::R_AARCH64_TLSDESC_ADD_LO12_NC, llvm::ELF::R_AARCH64_TLSDESC_ADR_PAGE, llvm::ELF::R_AARCH64_TLSDESC_CALL, llvm::ELF::R_AARCH64_TLSDESC_LD64_LO12_NC, llvm::ELF::R_AARCH64_TLSIE_ADR_GOTTPREL_PAGE21, llvm::ELF::R_AARCH64_TLSIE_LD64_GOTTPREL_LO12_NC, llvm::ELF::R_AARCH64_TLSIE_LD_GOTTPREL_PREL19, llvm::ELF::R_AARCH64_TLSIE_MOVW_GOTTPREL_G0_NC, llvm::ELF::R_AARCH64_TLSIE_MOVW_GOTTPREL_G1, llvm::ELF::R_AARCH64_TLSLD_ADD_DTPREL_HI12, llvm::ELF::R_AARCH64_TLSLD_ADD_DTPREL_LO12, llvm::ELF::R_AARCH64_TLSLD_ADD_DTPREL_LO12_NC, llvm::ELF::R_AARCH64_TLSLD_LDST16_DTPREL_LO12, llvm::ELF::R_AARCH64_TLSLD_LDST16_DTPREL_LO12_NC, llvm::ELF::R_AARCH64_TLSLD_LDST32_DTPREL_LO12, llvm::ELF::R_AARCH64_TLSLD_LDST32_DTPREL_LO12_NC, llvm::ELF::R_AARCH64_TLSLD_LDST64_DTPREL_LO12, llvm::ELF::R_AARCH64_TLSLD_LDST64_DTPREL_LO12_NC, llvm::ELF::R_AARCH64_TLSLD_LDST8_DTPREL_LO12, llvm::ELF::R_AARCH64_TLSLD_LDST8_DTPREL_LO12_NC, llvm::ELF::R_AARCH64_TLSLD_MOVW_DTPREL_G0, llvm::ELF::R_AARCH64_TLSLD_MOVW_DTPREL_G0_NC, llvm::ELF::R_AARCH64_TLSLD_MOVW_DTPREL_G1, llvm::ELF::R_AARCH64_TLSLD_MOVW_DTPREL_G1_NC, llvm::ELF::R_AARCH64_TLSLD_MOVW_DTPREL_G2, llvm::ELF::R_AARCH64_TLSLE_ADD_TPREL_HI12, llvm::ELF::R_AARCH64_TLSLE_ADD_TPREL_LO12, llvm::ELF::R_AARCH64_TLSLE_ADD_TPREL_LO12_NC, llvm::ELF::R_AARCH64_TLSLE_LDST16_TPREL_LO12, llvm::ELF::R_AARCH64_TLSLE_LDST16_TPREL_LO12_NC, llvm::ELF::R_AARCH64_TLSLE_LDST32_TPREL_LO12, llvm::ELF::R_AARCH64_TLSLE_LDST32_TPREL_LO12_NC, llvm::ELF::R_AARCH64_TLSLE_LDST64_TPREL_LO12, llvm::ELF::R_AARCH64_TLSLE_LDST64_TPREL_LO12_NC, llvm::ELF::R_AARCH64_TLSLE_LDST8_TPREL_LO12, llvm::ELF::R_AARCH64_TLSLE_LDST8_TPREL_LO12_NC, llvm::ELF::R_AARCH64_TLSLE_MOVW_TPREL_G0, llvm::ELF::R_AARCH64_TLSLE_MOVW_TPREL_G0_NC, llvm::ELF::R_AARCH64_TLSLE_MOVW_TPREL_G1, llvm::ELF::R_AARCH64_TLSLE_MOVW_TPREL_G1_NC, llvm::ELF::R_AARCH64_TLSLE_MOVW_TPREL_G2, llvm::ELF::R_AARCH64_TSTBR14, llvm::ELF::R_ARM_ABS12, llvm::ELF::R_ARM_ABS16, llvm::ELF::R_ARM_ABS32, llvm::ELF::R_ARM_ABS32_NOI, llvm::ELF::R_ARM_ABS8, llvm::ELF::R_ARM_ALU_PC_G0, llvm::ELF::R_ARM_ALU_PC_G0_NC, llvm::ELF::R_ARM_ALU_PC_G1, llvm::ELF::R_ARM_ALU_PC_G1_NC, llvm::ELF::R_ARM_ALU_PC_G2, llvm::ELF::R_ARM_ALU_PCREL_15_8, llvm::ELF::R_ARM_ALU_PCREL_23_15, llvm::ELF::R_ARM_ALU_PCREL_7_0, llvm::ELF::R_ARM_ALU_SB_G0, llvm::ELF::R_ARM_ALU_SB_G0_NC, llvm::ELF::R_ARM_ALU_SB_G1, llvm::ELF::R_ARM_ALU_SB_G1_NC, llvm::ELF::R_ARM_ALU_SB_G2, llvm::ELF::R_ARM_ALU_SBREL_19_12_NC, llvm::ELF::R_ARM_ALU_SBREL_27_20_CK, llvm::ELF::R_ARM_BASE_ABS, llvm::ELF::R_ARM_BASE_PREL, llvm::ELF::R_ARM_BREL_ADJ, llvm::ELF::R_ARM_CALL, llvm::ELF::R_ARM_COPY, llvm::ELF::R_ARM_GLOB_DAT, llvm::ELF::R_ARM_GNU_VTENTRY, llvm::ELF::R_ARM_GNU_VTINHERIT, llvm::ELF::R_ARM_GOT_ABS, llvm::ELF::R_ARM_GOT_BREL, llvm::ELF::R_ARM_GOT_BREL12, llvm::ELF::R_ARM_GOT_PREL, llvm::ELF::R_ARM_GOTOFF12, llvm::ELF::R_ARM_GOTOFF32, llvm::ELF::R_ARM_GOTRELAX, llvm::ELF::R_ARM_JUMP24, llvm::ELF::R_ARM_JUMP_SLOT, llvm::ELF::R_ARM_LDC_PC_G0, llvm::ELF::R_ARM_LDC_PC_G1, llvm::ELF::R_ARM_LDC_PC_G2, llvm::ELF::R_ARM_LDC_SB_G0, llvm::ELF::R_ARM_LDC_SB_G1, llvm::ELF::R_ARM_LDC_SB_G2, llvm::ELF::R_ARM_LDR_PC_G0, llvm::ELF::R_ARM_LDR_PC_G1, llvm::ELF::R_ARM_LDR_PC_G2, llvm::ELF::R_ARM_LDR_SB_G0, llvm::ELF::R_ARM_LDR_SB_G1, llvm::ELF::R_ARM_LDR_SB_G2, llvm::ELF::R_ARM_LDR_SBREL_11_0_NC, llvm::ELF::R_ARM_LDRS_PC_G0, llvm::ELF::R_ARM_LDRS_PC_G1, llvm::ELF::R_ARM_LDRS_PC_G2, llvm::ELF::R_ARM_LDRS_SB_G0, llvm::ELF::R_ARM_LDRS_SB_G1, llvm::ELF::R_ARM_LDRS_SB_G2, llvm::ELF::R_ARM_ME_TOO, llvm::ELF::R_ARM_MOVT_ABS, llvm::ELF::R_ARM_MOVT_BREL, llvm::ELF::R_ARM_MOVT_PREL, llvm::ELF::R_ARM_MOVW_ABS_NC, llvm::ELF::R_ARM_MOVW_BREL, llvm::ELF::R_ARM_MOVW_BREL_NC, llvm::ELF::R_ARM_MOVW_PREL_NC, llvm::ELF::R_ARM_NONE, llvm::ELF::R_ARM_PC24, llvm::ELF::R_ARM_PLT32, llvm::ELF::R_ARM_PLT32_ABS, llvm::ELF::R_ARM_PREL31, llvm::ELF::R_ARM_PRIVATE_0, llvm::ELF::R_ARM_PRIVATE_1, llvm::ELF::R_ARM_PRIVATE_10, llvm::ELF::R_ARM_PRIVATE_11, llvm::ELF::R_ARM_PRIVATE_12, llvm::ELF::R_ARM_PRIVATE_13, llvm::ELF::R_ARM_PRIVATE_14, llvm::ELF::R_ARM_PRIVATE_15, llvm::ELF::R_ARM_PRIVATE_2, llvm::ELF::R_ARM_PRIVATE_3, llvm::ELF::R_ARM_PRIVATE_4, llvm::ELF::R_ARM_PRIVATE_5, llvm::ELF::R_ARM_PRIVATE_6, llvm::ELF::R_ARM_PRIVATE_7, llvm::ELF::R_ARM_PRIVATE_8, llvm::ELF::R_ARM_PRIVATE_9, llvm::ELF::R_ARM_REL32, llvm::ELF::R_ARM_REL32_NOI, llvm::ELF::R_ARM_RELATIVE, llvm::ELF::R_ARM_SBREL31, llvm::ELF::R_ARM_SBREL32, llvm::ELF::R_ARM_TARGET1, llvm::ELF::R_ARM_TARGET2, llvm::ELF::R_ARM_THM_ABS5, llvm::ELF::R_ARM_THM_ALU_PREL_11_0, llvm::ELF::R_ARM_THM_CALL, llvm::ELF::R_ARM_THM_JUMP11, llvm::ELF::R_ARM_THM_JUMP19, llvm::ELF::R_ARM_THM_JUMP24, llvm::ELF::R_ARM_THM_JUMP6, llvm::ELF::R_ARM_THM_JUMP8, llvm::ELF::R_ARM_THM_MOVT_ABS, llvm::ELF::R_ARM_THM_MOVT_BREL, llvm::ELF::R_ARM_THM_MOVT_PREL, llvm::ELF::R_ARM_THM_MOVW_ABS_NC, llvm::ELF::R_ARM_THM_MOVW_BREL, llvm::ELF::R_ARM_THM_MOVW_BREL_NC, llvm::ELF::R_ARM_THM_MOVW_PREL_NC, llvm::ELF::R_ARM_THM_PC12, llvm::ELF::R_ARM_THM_PC8, llvm::ELF::R_ARM_THM_SWI8, llvm::ELF::R_ARM_THM_TLS_CALL, llvm::ELF::R_ARM_THM_TLS_DESCSEQ16, llvm::ELF::R_ARM_THM_TLS_DESCSEQ32, llvm::ELF::R_ARM_THM_XPC22, llvm::ELF::R_ARM_TLS_CALL, llvm::ELF::R_ARM_TLS_DESC, llvm::ELF::R_ARM_TLS_DESCSEQ, llvm::ELF::R_ARM_TLS_DTPMOD32, llvm::ELF::R_ARM_TLS_DTPOFF32, llvm::ELF::R_ARM_TLS_GD32, llvm::ELF::R_ARM_TLS_GOTDESC, llvm::ELF::R_ARM_TLS_IE12GP, llvm::ELF::R_ARM_TLS_IE32, llvm::ELF::R_ARM_TLS_LDM32, llvm::ELF::R_ARM_TLS_LDO12, llvm::ELF::R_ARM_TLS_LDO32, llvm::ELF::R_ARM_TLS_LE12, llvm::ELF::R_ARM_TLS_LE32, llvm::ELF::R_ARM_TLS_TPOFF32, llvm::ELF::R_ARM_V4BX, llvm::ELF::R_ARM_XPC25, llvm::ELF::R_HEX_10_X, llvm::ELF::R_HEX_11_X, llvm::ELF::R_HEX_12_X, llvm::ELF::R_HEX_16, llvm::ELF::R_HEX_16_X, llvm::ELF::R_HEX_32, llvm::ELF::R_HEX_32_6_X, llvm::ELF::R_HEX_32_PCREL, llvm::ELF::R_HEX_6_PCREL_X, llvm::ELF::R_HEX_6_X, llvm::ELF::R_HEX_7_X, llvm::ELF::R_HEX_8, llvm::ELF::R_HEX_8_X, llvm::ELF::R_HEX_9_X, llvm::ELF::R_HEX_B13_PCREL, llvm::ELF::R_HEX_B13_PCREL_X, llvm::ELF::R_HEX_B15_PCREL, llvm::ELF::R_HEX_B15_PCREL_X, llvm::ELF::R_HEX_B22_PCREL, llvm::ELF::R_HEX_B22_PCREL_X, llvm::ELF::R_HEX_B32_PCREL_X, llvm::ELF::R_HEX_B7_PCREL, llvm::ELF::R_HEX_B7_PCREL_X, llvm::ELF::R_HEX_B9_PCREL, llvm::ELF::R_HEX_B9_PCREL_X, llvm::ELF::R_HEX_COPY, llvm::ELF::R_HEX_DTPMOD_32, llvm::ELF::R_HEX_DTPREL_11_X, llvm::ELF::R_HEX_DTPREL_16, llvm::ELF::R_HEX_DTPREL_16_X, llvm::ELF::R_HEX_DTPREL_32, llvm::ELF::R_HEX_DTPREL_32_6_X, llvm::ELF::R_HEX_DTPREL_HI16, llvm::ELF::R_HEX_DTPREL_LO16, llvm::ELF::R_HEX_GD_GOT_11_X, llvm::ELF::R_HEX_GD_GOT_16, llvm::ELF::R_HEX_GD_GOT_16_X, llvm::ELF::R_HEX_GD_GOT_32, llvm::ELF::R_HEX_GD_GOT_32_6_X, llvm::ELF::R_HEX_GD_GOT_HI16, llvm::ELF::R_HEX_GD_GOT_LO16, llvm::ELF::R_HEX_GD_PLT_B22_PCREL, llvm::ELF::R_HEX_GLOB_DAT, llvm::ELF::R_HEX_GOT_11_X, llvm::ELF::R_HEX_GOT_16, llvm::ELF::R_HEX_GOT_16_X, llvm::ELF::R_HEX_GOT_32, llvm::ELF::R_HEX_GOT_32_6_X, llvm::ELF::R_HEX_GOT_HI16, llvm::ELF::R_HEX_GOT_LO16, llvm::ELF::R_HEX_GOTREL_11_X, llvm::ELF::R_HEX_GOTREL_16_X, llvm::ELF::R_HEX_GOTREL_32, llvm::ELF::R_HEX_GOTREL_32_6_X, llvm::ELF::R_HEX_GOTREL_HI16, llvm::ELF::R_HEX_GOTREL_LO16, llvm::ELF::R_HEX_GPREL16_0, llvm::ELF::R_HEX_GPREL16_1, llvm::ELF::R_HEX_GPREL16_2, llvm::ELF::R_HEX_GPREL16_3, llvm::ELF::R_HEX_HI16, llvm::ELF::R_HEX_HL16, llvm::ELF::R_HEX_IE_16_X, llvm::ELF::R_HEX_IE_32, llvm::ELF::R_HEX_IE_32_6_X, llvm::ELF::R_HEX_IE_GOT_11_X, llvm::ELF::R_HEX_IE_GOT_16, llvm::ELF::R_HEX_IE_GOT_16_X, llvm::ELF::R_HEX_IE_GOT_32, llvm::ELF::R_HEX_IE_GOT_32_6_X, llvm::ELF::R_HEX_IE_GOT_HI16, llvm::ELF::R_HEX_IE_GOT_LO16, llvm::ELF::R_HEX_IE_HI16, llvm::ELF::R_HEX_IE_LO16, llvm::ELF::R_HEX_JMP_SLOT, llvm::ELF::R_HEX_LO16, llvm::ELF::R_HEX_NONE, llvm::ELF::R_HEX_PLT_B22_PCREL, llvm::ELF::R_HEX_RELATIVE, llvm::ELF::R_HEX_TPREL_11_X, llvm::ELF::R_HEX_TPREL_16, llvm::ELF::R_HEX_TPREL_16_X, llvm::ELF::R_HEX_TPREL_32, llvm::ELF::R_HEX_TPREL_32_6_X, llvm::ELF::R_HEX_TPREL_HI16, llvm::ELF::R_HEX_TPREL_LO16, llvm::ELF::R_MICROMIPS_26_S1, llvm::ELF::R_MICROMIPS_CALL16, llvm::ELF::R_MICROMIPS_GOT16, llvm::ELF::R_MICROMIPS_GOT_DISP, llvm::ELF::R_MICROMIPS_GOT_OFST, llvm::ELF::R_MICROMIPS_GOT_PAGE, llvm::ELF::R_MICROMIPS_HI16, llvm::ELF::R_MICROMIPS_LO16, llvm::ELF::R_MICROMIPS_PC16_S1, llvm::ELF::R_MICROMIPS_TLS_DTPREL_HI16, llvm::ELF::R_MICROMIPS_TLS_DTPREL_LO16, llvm::ELF::R_MICROMIPS_TLS_TPREL_HI16, llvm::ELF::R_MICROMIPS_TLS_TPREL_LO16, llvm::ELF::R_MIPS_16, llvm::ELF::R_MIPS_26, llvm::ELF::R_MIPS_32, llvm::ELF::R_MIPS_64, llvm::ELF::R_MIPS_ADD_IMMEDIATE, llvm::ELF::R_MIPS_CALL16, llvm::ELF::R_MIPS_CALL_HI16, llvm::ELF::R_MIPS_CALL_LO16, llvm::ELF::R_MIPS_COPY, llvm::ELF::R_MIPS_DELETE, llvm::ELF::R_MIPS_GLOB_DAT, llvm::ELF::R_MIPS_GOT16, llvm::ELF::R_MIPS_GOT_DISP, llvm::ELF::R_MIPS_GOT_HI16, llvm::ELF::R_MIPS_GOT_LO16, llvm::ELF::R_MIPS_GOT_OFST, llvm::ELF::R_MIPS_GOT_PAGE, llvm::ELF::R_MIPS_GPREL16, llvm::ELF::R_MIPS_GPREL32, llvm::ELF::R_MIPS_HI16, llvm::ELF::R_MIPS_HIGHER, llvm::ELF::R_MIPS_HIGHEST, llvm::ELF::R_MIPS_INSERT_A, llvm::ELF::R_MIPS_INSERT_B, llvm::ELF::R_MIPS_JALR, llvm::ELF::R_MIPS_JUMP_SLOT, llvm::ELF::R_MIPS_LITERAL, llvm::ELF::R_MIPS_LO16, llvm::ELF::R_MIPS_NONE, llvm::ELF::R_MIPS_NUM, llvm::ELF::R_MIPS_PC16, llvm::ELF::R_MIPS_PJUMP, llvm::ELF::R_MIPS_REL16, llvm::ELF::R_MIPS_REL32, llvm::ELF::R_MIPS_RELGOT, llvm::ELF::R_MIPS_SCN_DISP, llvm::ELF::R_MIPS_SHIFT5, llvm::ELF::R_MIPS_SHIFT6, llvm::ELF::R_MIPS_SUB, llvm::ELF::R_MIPS_TLS_DTPMOD32, llvm::ELF::R_MIPS_TLS_DTPMOD64, llvm::ELF::R_MIPS_TLS_DTPREL32, llvm::ELF::R_MIPS_TLS_DTPREL64, llvm::ELF::R_MIPS_TLS_DTPREL_HI16, llvm::ELF::R_MIPS_TLS_DTPREL_LO16, llvm::ELF::R_MIPS_TLS_GD, llvm::ELF::R_MIPS_TLS_GOTTPREL, llvm::ELF::R_MIPS_TLS_LDM, llvm::ELF::R_MIPS_TLS_TPREL32, llvm::ELF::R_MIPS_TLS_TPREL64, llvm::ELF::R_MIPS_TLS_TPREL_HI16, llvm::ELF::R_MIPS_TLS_TPREL_LO16, llvm::ELF::R_PPC64_ADDR14, llvm::ELF::R_PPC64_ADDR14_BRNTAKEN, llvm::ELF::R_PPC64_ADDR14_BRTAKEN, llvm::ELF::R_PPC64_ADDR16, llvm::ELF::R_PPC64_ADDR16_DS, llvm::ELF::R_PPC64_ADDR16_HA, llvm::ELF::R_PPC64_ADDR16_HI, llvm::ELF::R_PPC64_ADDR16_HIGHER, llvm::ELF::R_PPC64_ADDR16_HIGHERA, llvm::ELF::R_PPC64_ADDR16_HIGHEST, llvm::ELF::R_PPC64_ADDR16_HIGHESTA, llvm::ELF::R_PPC64_ADDR16_LO, llvm::ELF::R_PPC64_ADDR16_LO_DS, llvm::ELF::R_PPC64_ADDR24, llvm::ELF::R_PPC64_ADDR32, llvm::ELF::R_PPC64_ADDR64, llvm::ELF::R_PPC64_DTPMOD64, llvm::ELF::R_PPC64_DTPREL16, llvm::ELF::R_PPC64_DTPREL16_DS, llvm::ELF::R_PPC64_DTPREL16_HA, llvm::ELF::R_PPC64_DTPREL16_HI, llvm::ELF::R_PPC64_DTPREL16_HIGHER, llvm::ELF::R_PPC64_DTPREL16_HIGHERA, llvm::ELF::R_PPC64_DTPREL16_HIGHEST, llvm::ELF::R_PPC64_DTPREL16_HIGHESTA, llvm::ELF::R_PPC64_DTPREL16_LO, llvm::ELF::R_PPC64_DTPREL16_LO_DS, llvm::ELF::R_PPC64_DTPREL64, llvm::ELF::R_PPC64_GOT16, llvm::ELF::R_PPC64_GOT16_DS, llvm::ELF::R_PPC64_GOT16_HA, llvm::ELF::R_PPC64_GOT16_HI, llvm::ELF::R_PPC64_GOT16_LO, llvm::ELF::R_PPC64_GOT16_LO_DS, llvm::ELF::R_PPC64_GOT_DTPREL16_DS, llvm::ELF::R_PPC64_GOT_DTPREL16_HA, llvm::ELF::R_PPC64_GOT_DTPREL16_HI, llvm::ELF::R_PPC64_GOT_DTPREL16_LO_DS, llvm::ELF::R_PPC64_GOT_TLSGD16, llvm::ELF::R_PPC64_GOT_TLSGD16_HA, llvm::ELF::R_PPC64_GOT_TLSGD16_HI, llvm::ELF::R_PPC64_GOT_TLSGD16_LO, llvm::ELF::R_PPC64_GOT_TLSLD16, llvm::ELF::R_PPC64_GOT_TLSLD16_HA, llvm::ELF::R_PPC64_GOT_TLSLD16_HI, llvm::ELF::R_PPC64_GOT_TLSLD16_LO, llvm::ELF::R_PPC64_GOT_TPREL16_DS, llvm::ELF::R_PPC64_GOT_TPREL16_HA, llvm::ELF::R_PPC64_GOT_TPREL16_HI, llvm::ELF::R_PPC64_GOT_TPREL16_LO_DS, llvm::ELF::R_PPC64_NONE, llvm::ELF::R_PPC64_REL14, llvm::ELF::R_PPC64_REL14_BRNTAKEN, llvm::ELF::R_PPC64_REL14_BRTAKEN, llvm::ELF::R_PPC64_REL16, llvm::ELF::R_PPC64_REL16_HA, llvm::ELF::R_PPC64_REL16_HI, llvm::ELF::R_PPC64_REL16_LO, llvm::ELF::R_PPC64_REL24, llvm::ELF::R_PPC64_REL32, llvm::ELF::R_PPC64_REL64, llvm::ELF::R_PPC64_TLS, llvm::ELF::R_PPC64_TLSGD, llvm::ELF::R_PPC64_TLSLD, llvm::ELF::R_PPC64_TOC, llvm::ELF::R_PPC64_TOC16, llvm::ELF::R_PPC64_TOC16_DS, llvm::ELF::R_PPC64_TOC16_HA, llvm::ELF::R_PPC64_TOC16_HI, llvm::ELF::R_PPC64_TOC16_LO, llvm::ELF::R_PPC64_TOC16_LO_DS, llvm::ELF::R_PPC64_TPREL16, llvm::ELF::R_PPC64_TPREL16_DS, llvm::ELF::R_PPC64_TPREL16_HA, llvm::ELF::R_PPC64_TPREL16_HI, llvm::ELF::R_PPC64_TPREL16_HIGHER, llvm::ELF::R_PPC64_TPREL16_HIGHERA, llvm::ELF::R_PPC64_TPREL16_HIGHEST, llvm::ELF::R_PPC64_TPREL16_HIGHESTA, llvm::ELF::R_PPC64_TPREL16_LO, llvm::ELF::R_PPC64_TPREL16_LO_DS, llvm::ELF::R_PPC64_TPREL64, llvm::ELF::R_PPC_ADDR14, llvm::ELF::R_PPC_ADDR14_BRNTAKEN, llvm::ELF::R_PPC_ADDR14_BRTAKEN, llvm::ELF::R_PPC_ADDR16, llvm::ELF::R_PPC_ADDR16_HA, llvm::ELF::R_PPC_ADDR16_HI, llvm::ELF::R_PPC_ADDR16_LO, llvm::ELF::R_PPC_ADDR24, llvm::ELF::R_PPC_ADDR32, llvm::ELF::R_PPC_DTPMOD32, llvm::ELF::R_PPC_DTPREL16, llvm::ELF::R_PPC_DTPREL16_HA, llvm::ELF::R_PPC_DTPREL16_HI, llvm::ELF::R_PPC_DTPREL16_LO, llvm::ELF::R_PPC_DTPREL32, llvm::ELF::R_PPC_GOT16, llvm::ELF::R_PPC_GOT16_HA, llvm::ELF::R_PPC_GOT16_HI, llvm::ELF::R_PPC_GOT16_LO, llvm::ELF::R_PPC_GOT_DTPREL16, llvm::ELF::R_PPC_GOT_DTPREL16_HA, llvm::ELF::R_PPC_GOT_DTPREL16_HI, llvm::ELF::R_PPC_GOT_DTPREL16_LO, llvm::ELF::R_PPC_GOT_TLSGD16, llvm::ELF::R_PPC_GOT_TLSGD16_HA, llvm::ELF::R_PPC_GOT_TLSGD16_HI, llvm::ELF::R_PPC_GOT_TLSGD16_LO, llvm::ELF::R_PPC_GOT_TLSLD16, llvm::ELF::R_PPC_GOT_TLSLD16_HA, llvm::ELF::R_PPC_GOT_TLSLD16_HI, llvm::ELF::R_PPC_GOT_TLSLD16_LO, llvm::ELF::R_PPC_GOT_TPREL16, llvm::ELF::R_PPC_GOT_TPREL16_HA, llvm::ELF::R_PPC_GOT_TPREL16_HI, llvm::ELF::R_PPC_GOT_TPREL16_LO, llvm::ELF::R_PPC_NONE, llvm::ELF::R_PPC_REL14, llvm::ELF::R_PPC_REL14_BRNTAKEN, llvm::ELF::R_PPC_REL14_BRTAKEN, llvm::ELF::R_PPC_REL16, llvm::ELF::R_PPC_REL16_HA, llvm::ELF::R_PPC_REL16_HI, llvm::ELF::R_PPC_REL16_LO, llvm::ELF::R_PPC_REL24, llvm::ELF::R_PPC_REL32, llvm::ELF::R_PPC_TLS, llvm::ELF::R_PPC_TLSGD, llvm::ELF::R_PPC_TLSLD, llvm::ELF::R_PPC_TPREL16, llvm::ELF::R_PPC_TPREL16_HA, llvm::ELF::R_PPC_TPREL16_HI, llvm::ELF::R_PPC_TPREL16_LO, llvm::ELF::R_PPC_TPREL32, llvm::ELF::R_X86_64_16, llvm::ELF::R_X86_64_32, llvm::ELF::R_X86_64_32S, llvm::ELF::R_X86_64_64, llvm::ELF::R_X86_64_8, llvm::ELF::R_X86_64_COPY, llvm::ELF::R_X86_64_DTPMOD64, llvm::ELF::R_X86_64_DTPOFF32, llvm::ELF::R_X86_64_DTPOFF64, llvm::ELF::R_X86_64_GLOB_DAT, llvm::ELF::R_X86_64_GOT32, llvm::ELF::R_X86_64_GOT64, llvm::ELF::R_X86_64_GOTOFF64, llvm::ELF::R_X86_64_GOTPC32, llvm::ELF::R_X86_64_GOTPC32_TLSDESC, llvm::ELF::R_X86_64_GOTPC64, llvm::ELF::R_X86_64_GOTPCREL, llvm::ELF::R_X86_64_GOTPCREL64, llvm::ELF::R_X86_64_GOTPLT64, llvm::ELF::R_X86_64_GOTTPOFF, llvm::ELF::R_X86_64_IRELATIVE, llvm::ELF::R_X86_64_JUMP_SLOT, llvm::ELF::R_X86_64_NONE, llvm::ELF::R_X86_64_PC16, llvm::ELF::R_X86_64_PC32, llvm::ELF::R_X86_64_PC64, llvm::ELF::R_X86_64_PC8, llvm::ELF::R_X86_64_PLT32, llvm::ELF::R_X86_64_PLTOFF64, llvm::ELF::R_X86_64_RELATIVE, llvm::ELF::R_X86_64_SIZE32, llvm::ELF::R_X86_64_SIZE64, llvm::ELF::R_X86_64_TLSDESC, llvm::ELF::R_X86_64_TLSDESC_CALL, llvm::ELF::R_X86_64_TLSGD, llvm::ELF::R_X86_64_TLSLD, llvm::ELF::R_X86_64_TPOFF32, and llvm::ELF::R_X86_64_TPOFF64.
Referenced by llvm::object::ELFObjectFile< ELFT >::getRelocationTypeName(), and llvm::object::ELFFile< ELFT >::getRelocationTypeName().
static error_code llvm::object::GetELFSymbolVersion (const ObjectFile * Obj, const SymbolRef & Sym, StringRef & Version, bool & IsDefault) inline static
This is a generic interface for retrieving GNU symbol version information from an ELFObjectFile.
Definition at line 1002 of file ELFObjectFile.h.
References llvm_unreachable.
static uint32_t llvm::object::getPlainRelocationAddress (const MachO::any_relocation_info & RE) static
Definition at line 366 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word0.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationAddress(), and llvm::object::MachOObjectFile::isRelocationScattered().
static unsigned llvm::object::getPlainRelocationLength (const MachOObjectFile * O, const MachO::any_relocation_info & RE) static
Definition at line 388 of file MachOObjectFile.cpp.
References llvm::object::Binary::isLittleEndian(), and llvm::MachO::any_relocation_info::r_word1.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationLength().
static bool llvm::object::getPlainRelocationPCRel (const MachOObjectFile * O, const MachO::any_relocation_info & RE) static
Definition at line 375 of file MachOObjectFile.cpp.
References llvm::object::Binary::isLittleEndian(), and llvm::MachO::any_relocation_info::r_word1.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationPCRel().
static unsigned llvm::object::getPlainRelocationType (const MachOObjectFile * O, const MachO::any_relocation_info & RE) static
Definition at line 400 of file MachOObjectFile.cpp.
References llvm::object::Binary::isLittleEndian(), and llvm::MachO::any_relocation_info::r_word1.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationType().
static const char* llvm::object::getPtr (const MachOObjectFile * O, size_t Offset) static
Definition at line 258 of file MachOObjectFile.cpp.
References llvm::StringRef::data(), llvm::object::Binary::getData(), and llvm::StringRef::substr().
Referenced by llvm::object::MachOObjectFile::begin_dices(), llvm::object::MachOObjectFile::begin_symbols(), llvm::object::MachOObjectFile::end_dices(), llvm::object::MachOObjectFile::end_symbols(), llvm::object::MachOObjectFile::getDataInCodeTableEntry(), llvm::object::MachOObjectFile::getFirstLoadCommandInfo(), llvm::object::MachOObjectFile::getHeader(), llvm::object::MachOObjectFile::getHeader64(), llvm::object::MachOObjectFile::getIndirectSymbolTableEntry(), llvm::object::MachOObjectFile::getRelocationSymbol(), llvm::object::MachOObjectFile::section_rel_begin(), and llvm::object::MachOObjectFile::section_rel_end().
static unsigned llvm::object::getScatteredRelocationAddress (const MachO::any_relocation_info & RE) static
Definition at line 371 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word0.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationAddress().
static unsigned llvm::object::getScatteredRelocationLength (const MachO::any_relocation_info & RE) static
Definition at line 396 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word0.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationLength().
static bool llvm::object::getScatteredRelocationPCRel (const MachOObjectFile * O, const MachO::any_relocation_info & RE) static
Definition at line 383 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word0.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationPCRel().
static unsigned llvm::object::getScatteredRelocationType (const MachO::any_relocation_info & RE) static
Definition at line 408 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word0.
Referenced by llvm::object::MachOObjectFile::getAnyRelocationType().
static uint32_t llvm::object::getSectionFlags (const MachOObjectFile * O, DataRefImpl Sec) static
Definition at line 412 of file MachOObjectFile.cpp.
References llvm::MachO::section::flags, llvm::MachO::section_64::flags, llvm::object::MachOObjectFile::getSection(), llvm::object::MachOObjectFile::getSection64(), and llvm::object::MachOObjectFile::is64Bit().
Referenced by llvm::object::MachOObjectFile::isSectionText(), and llvm::object::MachOObjectFile::isSectionZeroInit().
static const char* llvm::object::getSectionPtr (const MachOObjectFile * O, MachOObjectFile::LoadCommandInfo L, unsigned Sec) static
Definition at line 244 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::is64Bit(), llvm::object::MachOObjectFile::LoadCommandInfo::Ptr, and llvm::COFF::SectionSize.
Referenced by llvm::object::MachOObjectFile::getSection(), llvm::object::MachOObjectFile::getSection64(), and llvm::object::MachOObjectFile::MachOObjectFile().
static uint32_t llvm::object::getSegmentLoadCommandNumSections (const MachOObjectFile * O, const MachOObjectFile::LoadCommandInfo & L) static
Definition at line 233 of file MachOObjectFile.cpp.
References llvm::object::MachOObjectFile::getSegment64LoadCommand(), llvm::object::MachOObjectFile::getSegmentLoadCommand(), llvm::object::MachOObjectFile::is64Bit(), llvm::MachO::segment_command::nsects, llvm::MachO::segment_command_64::nsects, and S.
Referenced by llvm::object::MachOObjectFile::MachOObjectFile().
template<typename T > T llvm::object::getStruct (const MachOObjectFile * O, const char * P)
Definition at line 224 of file MachOObjectFile.cpp.
References llvm::object::Binary::isLittleEndian(), llvm::sys::IsLittleEndianHost, llvm::Intrinsic::memcpy, and SwapStruct().
static nlist_base llvm::object::getSymbolTableEntryBase (const MachOObjectFile * O, DataRefImpl DRI) static
Definition at line 263 of file MachOObjectFile.cpp.
References llvm::object::DataRefImpl::p, and P.
Referenced by llvm::object::MachOObjectFile::getSymbolAlignment(), llvm::object::MachOObjectFile::getSymbolFileOffset(), llvm::object::MachOObjectFile::getSymbolFlags(), llvm::object::MachOObjectFile::getSymbolName(), llvm::object::MachOObjectFile::getSymbolSection(), llvm::object::MachOObjectFile::getSymbolSize(), and llvm::object::MachOObjectFile::getSymbolType().
error_code llvm::object::make_error_code (object_error e) inline
Definition at line 38 of file Object/Error.h.
References object_category().
Referenced by createBinary().
const error_category & llvm::object::object_category ()
Definition at line 56 of file Object/Error.cpp.
Referenced by make_error_code().
bool llvm::object::operator< (const DataRefImpl & a, const DataRefImpl & b) inline
Definition at line 81 of file ObjectFile.h.
References llvm::LibFunc::memcmp.
Referenced by llvm::object::LibraryRef::LibraryRef(), llvm::object::SymbolRef::LLVM_ENUM_INT_TYPE(), and llvm::object::SectionRef::SectionRef().
bool llvm::object::operator== (const DataRefImpl & a, const DataRefImpl & b) inline
Definition at line 75 of file ObjectFile.h.
References llvm::LibFunc::memcmp.
Referenced by llvm::object::ImportDirectoryEntryRef::ImportDirectoryEntryRef(), llvm::object::LibraryRef::LibraryRef(), llvm::object::SymbolRef::LLVM_ENUM_INT_TYPE(), llvm::object::RelocationRef::RelocationRef(), and llvm::object::SectionRef::SectionRef().
static StringRef llvm::object::parseSegmentOrSectionName (const char * P) static
Definition at line 268 of file MachOObjectFile.cpp.
References P.
Referenced by llvm::object::MachOObjectFile::getSectionFinalSegmentName(), and llvm::object::MachOObjectFile::getSectionName().
static void llvm::object::printRelocationTargetName (const MachOObjectFile * O, const MachO::any_relocation_info & RE, raw_string_ostream & fmt) static
Definition at line 296 of file MachOObjectFile.cpp.
References advanceTo(), llvm::object::MachOObjectFile::begin_sections(), llvm::object::MachOObjectFile::begin_symbols(), llvm::object::MachOObjectFile::end_sections(), llvm::object::MachOObjectFile::end_symbols(), llvm::format(), llvm::object::MachOObjectFile::getPlainRelocationExternal(), llvm::object::MachOObjectFile::getPlainRelocationSymbolNum(), llvm::object::content_iterator< content_type >::increment(), llvm::object::MachOObjectFile::isRelocationScattered(), llvm::error_code::message(), llvm::report_fatal_error(), and S.
Referenced by llvm::object::MachOObjectFile::getRelocationValueString().
template<typename T > static void llvm::object::SwapStruct (T & Value) static
Referenced by getStruct(), getUniversalBinaryStruct(), SwapValue(), and SwapValue().
template<> void llvm::object::SwapStruct (MachO::any_relocation_info & H)
Definition at line 53 of file MachOObjectFile.cpp.
References llvm::MachO::any_relocation_info::r_word0, llvm::MachO::any_relocation_info::r_word1, and SwapValue().
template<> void llvm::object::SwapStruct (MachO::load_command & L)
Definition at line 59 of file MachOObjectFile.cpp.
References llvm::MachO::load_command::cmd, llvm::MachO::load_command::cmdsize, and SwapValue().
template<> void llvm::object::SwapStruct (nlist_base & S)
Definition at line 65 of file MachOObjectFile.cpp.
References llvm::object::nlist_base::n_desc, llvm::object::nlist_base::n_strx, and SwapValue().
template<> void llvm::object::SwapStruct (MachO::section & S)
Definition at line 71 of file MachOObjectFile.cpp.
References llvm::MachO::section::addr, llvm::MachO::section::align, llvm::MachO::section::flags, llvm::MachO::section::nreloc, llvm::MachO::section::offset, llvm::MachO::section::reloff, llvm::MachO::section::reserved1, llvm::MachO::section::reserved2, llvm::MachO::section::size, and SwapValue().
template<> void llvm::object::SwapStruct (MachO::section_64 & S)
Definition at line 84 of file MachOObjectFile.cpp.
References llvm::MachO::section_64::addr, llvm::MachO::section_64::align, llvm::MachO::section_64::flags, llvm::MachO::section_64::nreloc, llvm::MachO::section_64::offset, llvm::MachO::section_64::reloff, llvm::MachO::section_64::reserved1, llvm::MachO::section_64::reserved2, llvm::MachO::section_64::reserved3, llvm::MachO::section_64::size, and SwapValue().
template<> void llvm::object::SwapStruct (MachO::nlist & S)
Definition at line 98 of file MachOObjectFile.cpp.
References llvm::MachO::nlist::n_desc, llvm::MachO::nlist::n_strx, llvm::MachO::nlist::n_value, and SwapValue().
template<> void llvm::object::SwapStruct (MachO::nlist_64 & S)
Definition at line 105 of file MachOObjectFile.cpp.
References llvm::MachO::nlist_64::n_desc, llvm::MachO::nlist_64::n_strx, llvm::MachO::nlist_64::n_value, and SwapValue().
template<> void llvm::object::SwapStruct (MachO::mach_header & H)
Definition at line 112 of file MachOObjectFile.cpp.
References llvm::MachO::mach_header::cpusubtype, llvm::MachO::mach_header::cputype, llvm::MachO::mach_header::filetype, llvm::MachO::mach_header::flags, llvm::MachO::mach_header::magic, llvm::MachO::mach_header::ncmds, llvm::MachO::mach_header::sizeofcmds, and SwapValue().
template<> void llvm::object::SwapStruct (MachO::mach_header_64 & H)
Definition at line 123 of file MachOObjectFile.cpp.
References llvm::MachO::mach_header_64::cpusubtype, llvm::MachO::mach_header_64::cputype, llvm::MachO::mach_header_64::filetype, llvm::MachO::mach_header_64::flags, llvm::MachO::mach_header_64::magic, llvm::MachO::mach_header_64::ncmds, llvm::MachO::mach_header_64::reserved, llvm::MachO::mach_header_64::sizeofcmds, and SwapValue().
template<> void llvm::object::SwapStruct (MachO::symtab_command & C)
Definition at line 135 of file MachOObjectFile.cpp.
References llvm::MachO::symtab_command::cmd, llvm::MachO::symtab_command::cmdsize, llvm::MachO::symtab_command::nsyms, llvm::MachO::symtab_command::stroff, llvm::MachO::symtab_command::strsize, SwapValue(), and llvm::MachO::symtab_command::symoff.
template<> void llvm::object::SwapStruct (MachO::dysymtab_command & C)
Definition at line 145 of file MachOObjectFile.cpp.
References llvm::MachO::dysymtab_command::cmd, llvm::MachO::dysymtab_command::cmdsize, llvm::MachO::dysymtab_command::extrefsymoff, llvm::MachO::dysymtab_command::extreloff, llvm::MachO::dysymtab_command::iextdefsym, llvm::MachO::dysymtab_command::ilocalsym, llvm::MachO::dysymtab_command::indirectsymoff, llvm::MachO::dysymtab_command::iundefsym, llvm::MachO::dysymtab_command::locreloff, llvm::MachO::dysymtab_command::modtaboff, llvm::MachO::dysymtab_command::nextdefsym, llvm::MachO::dysymtab_command::nextrefsyms, llvm::MachO::dysymtab_command::nextrel, llvm::MachO::dysymtab_command::nindirectsyms, llvm::MachO::dysymtab_command::nlocalsym, llvm::MachO::dysymtab_command::nlocrel, llvm::MachO::dysymtab_command::nmodtab, llvm::MachO::dysymtab_command::ntoc, llvm::MachO::dysymtab_command::nundefsym, SwapValue(), and llvm::MachO::dysymtab_command::tocoff.
template<> void llvm::object::SwapStruct (MachO::linkedit_data_command & C)
Definition at line 169 of file MachOObjectFile.cpp.
References llvm::MachO::linkedit_data_command::cmd, llvm::MachO::linkedit_data_command::cmdsize, llvm::MachO::linkedit_data_command::dataoff, llvm::MachO::linkedit_data_command::datasize, and SwapValue().
template<> void llvm::object::SwapStruct (MachO::segment_command & C)
Definition at line 177 of file MachOObjectFile.cpp.
References llvm::MachO::segment_command::cmd, llvm::MachO::segment_command::cmdsize, llvm::MachO::segment_command::fileoff, llvm::MachO::segment_command::filesize, llvm::MachO::segment_command::flags, llvm::MachO::segment_command::initprot, llvm::MachO::segment_command::maxprot, llvm::MachO::segment_command::nsects, SwapValue(), llvm::MachO::segment_command::vmaddr, and llvm::MachO::segment_command::vmsize.
template<> void llvm::object::SwapStruct (MachO::segment_command_64 & C)
Definition at line 191 of file MachOObjectFile.cpp.
References llvm::MachO::segment_command_64::cmd, llvm::MachO::segment_command_64::cmdsize, llvm::MachO::segment_command_64::fileoff, llvm::MachO::segment_command_64::filesize, llvm::MachO::segment_command_64::flags, llvm::MachO::segment_command_64::initprot, llvm::MachO::segment_command_64::maxprot, llvm::MachO::segment_command_64::nsects, SwapValue(), llvm::MachO::segment_command_64::vmaddr, and llvm::MachO::segment_command_64::vmsize.
template<> void llvm::object::SwapStruct (uint32_t & C)
Definition at line 205 of file MachOObjectFile.cpp.
References SwapValue().
template<> void llvm::object::SwapStruct (MachO::linker_options_command & C)
Definition at line 210 of file MachOObjectFile.cpp.
References llvm::MachO::linker_options_command::cmd, llvm::MachO::linker_options_command::cmdsize, llvm::MachO::linker_options_command::count, and SwapValue().
template<> void llvm::object::SwapStruct (MachO::data_in_code_entry & C)
Definition at line 217 of file MachOObjectFile.cpp.
References llvm::MachO::data_in_code_entry::kind, llvm::MachO::data_in_code_entry::length, llvm::MachO::data_in_code_entry::offset, and SwapValue().
template<typename T > static void llvm::object::SwapValue (T & Value) static
Definition at line 45 of file MachOObjectFile.cpp.
References llvm::sys::SwapByteOrder(), and SwapStruct().
Referenced by SwapStruct(), and SwapStruct().
Variable Documentation
const uint64_t llvm::object::UnknownAddressOrSize = ~0ULL
Definition at line 261 of file ObjectFile.h.
Referenced by llvm::MCObjectDisassembler::buildModule(), llvm::object::ELFObjectFile< ELFT >::getSymbolAddress(), llvm::object::COFFObjectFile::getSymbolAddress(), llvm::object::ELFObjectFile< ELFT >::getSymbolFileOffset(), llvm::object::COFFObjectFile::getSymbolFileOffset(), llvm::object::MachOObjectFile::getSymbolSize(), llvm::object::COFFObjectFile::getSymbolSize(), and llvm::MCObjectSymbolizer::tryAddingSymbolicOperand().