LLVM: NVPTXAsmPrinter.cpp File Reference
LLVM API Documentation
NVPTXAsmPrinter.cpp File Reference
#include "NVPTXAsmPrinter.h"
#include "MCTargetDesc/NVPTXMCAsmInfo.h"
#include "NVPTX.h"
#include "NVPTXInstrInfo.h"
#include "NVPTXMCExpr.h"
#include "NVPTXRegisterInfo.h"
#include "NVPTXTargetMachine.h"
#include "NVPTXUtilities.h"
#include "InstPrinter/NVPTXInstPrinter.h"
#include "cl_common_defines.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Assembly/Writer.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/DebugInfo.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/Path.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/TimeValue.h"
#include "llvm/Target/Mangler.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include <sstream>
Macros
#define DEPOTNAME "__local_depot"
Functions
static bool usedInGlobalVarDef (const Constant *C)
static bool usedInOneFunc (const User *U, Function const *&oneFunc)
static bool canDemoteGlobalVar (const GlobalVariable *gv, Function const *&f)
static bool useFuncSeen (const Constant *C, llvm::DenseMap< const Function *, bool > &seenMap)
static unsigned int getOpenCLAlignment (const DataLayout *TD, Type *Ty)
void LLVMInitializeNVPTXBackendAsmPrinter ()
void LLVMInitializeNVPTXAsmPrinter ()
Variables
static cl::opt< bool > EmitLineNumbers ("nvptx-emit-line-numbers", cl::Hidden, cl::desc("NVPTX Specific: Emit Line numbers even without -G"), cl::init(true))
static cl::opt< bool > InterleaveSrc ("nvptx-emit-src", cl::ZeroOrMore, cl::Hidden, cl::desc("NVPTX Specific: Emit source line in ptx file"), cl::init(false))
Macro Definition Documentation
#define DEPOTNAME "__local_depot"
Definition at line 51 of file NVPTXAsmPrinter.cpp.
Referenced by getOpenCLAlignment(), and llvm::NVPTXAsmPrinter::ignoreLoc().
Function Documentation
static bool canDemoteGlobalVar (const GlobalVariable * gv, Function const *& f) static
Definition at line 749 of file NVPTXAsmPrinter.cpp.
References llvm::ADDRESS_SPACE_SHARED, llvm::PointerType::getAddressSpace(), llvm::GlobalValue::getType(), llvm::GlobalValue::hasInternalLinkage(), and usedInOneFunc().
Referenced by llvm::NVPTXAsmPrinter::doFinalization().
static unsigned int getOpenCLAlignment (const DataLayout * TD, Type * Ty) static
Definition at line 1412 of file NVPTXAsmPrinter.cpp.
References llvm::ADDRESS_SPACE_CONST, llvm::ADDRESS_SPACE_GLOBAL, llvm::ADDRESS_SPACE_SHARED, align, llvm::lltok::APFloat, llvm::Function::arg_begin(), llvm::Function::arg_end(), llvm::Type::ArrayTyID, llvm::APFloat::bitcastToAPInt(), llvm::Attribute::ByVal, c, llvm::ComputeValueVTs(), llvm::ConstantFoldConstantExpression(), llvm::APFloat::convert(), llvm::APFloat::convertToDouble(), llvm::APFloat::convertToFloat(), llvm::NVPTX::CUDA, DEPOTNAME, llvm::Type::DoubleTyID, llvm::dyn_cast(), llvm::Type::FloatTyID, llvm::DataLayout::getABITypeAlignment(), llvm::PointerType::getAddressSpace(), llvm::Function::getAttributes(), getBitWidth(), llvm::Value::getContext(), llvm::Type::getDoubleTy(), llvm::StructLayout::getElementOffset(), llvm::StructType::getElementType(), llvm::SequentialType::getElementType(), llvm::Type::getFloatTy(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::Type::getInt16Ty(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::Type::getInt8Ty(), llvm::MachineFrameInfo::getMaxAlignment(), llvm::StructType::getNumElements(), llvm::User::getNumOperands(), llvm::TargetRegisterInfo::getNumRegClasses(), llvm::getNVPTXRegClassName(), llvm::getNVPTXRegClassStr(), llvm::User::getOperand(), llvm::AttributeSet::getParamAlignment(), llvm::DataLayout::getPointerPrefAlignment(), llvm::TargetLoweringBase::getPointerTy(), llvm::DataLayout::getPrefTypeAlignment(), llvm::Type::getPrimitiveSizeInBits(), llvm::MCRegisterInfo::getRegClass(), llvm::TargetRegisterInfo::getRegClass(), llvm::TargetMachine::getRegisterInfo(), llvm::MVT::getSizeInBits(), llvm::EVT::getSizeInBits(), llvm::MachineFrameInfo::getStackSize(), llvm::DataLayout::getStructLayout(), llvm::MachineFunction::getTarget(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::Type::getTypeID(), llvm::ConstantFP::getValueAPF(), llvm::APInt::getZExtValue(), llvm::AttributeSet::hasAttribute(), i, I, llvm::APFloat::IEEEdouble, llvm::APFloat::IEEEsingle, llvm::TargetRegisterInfo::index2VirtReg(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::insert(), int, int64, llvm::Type::IntegerTyID, llvm::isImage(), llvm::isImageWriteOnly(), llvm::EVT::isInteger(), llvm::Type::isIntegerTy(), llvm::isKernelFunction(), llvm::Constant::isNullValue(), llvm::Type::isPrimitiveType(), llvm::isSampler(), llvm::Type::isVectorTy(), j(), llvm_unreachable, nvptx::LowerConstant(), MRI, n, llvm::NVPTX::NVCL, p, llvm::Type::PointerTyID, llvm::APFloat::rmNearestTiesToEven, s, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::size(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::A64DB::ST, llvm::raw_svector_ostream::str(), llvm::Value::stripPointerCasts(), llvm::Type::StructTyID, llvm::SystemZISD::TM, llvm::utohexstr(), and llvm::Type::VectorTyID.
void LLVMInitializeNVPTXAsmPrinter ()
Definition at line 2176 of file NVPTXAsmPrinter.cpp.
References llvm::TheNVPTXTarget32, llvm::TheNVPTXTarget64, llvm::X, and Y.
void LLVMInitializeNVPTXBackendAsmPrinter ()
Definition at line 2132 of file NVPTXAsmPrinter.cpp.
References llvm::sys::path::filename(), llvm::LineReader::readLine(), llvm::StringRef::str(), llvm::TheNVPTXTarget32, llvm::TheNVPTXTarget64, llvm::X, and Y.
static bool usedInGlobalVarDef (const Constant * C) static
Definition at line 693 of file NVPTXAsmPrinter.cpp.
References llvm::dyn_cast(), llvm::Value::getName(), llvm::StringRef::str(), llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by useFuncSeen().
static bool usedInOneFunc (const User * U, Function const *& oneFunc) static
Definition at line 712 of file NVPTXAsmPrinter.cpp.
References llvm::GlobalValue::getParent(), llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by canDemoteGlobalVar().
static bool useFuncSeen (const Constant * C, llvm::DenseMap< const Function *, bool > & seenMap) static
Definition at line 767 of file NVPTXAsmPrinter.cpp.
References llvm::sys::path::append(), bb, llvm::Module::begin(), caller(), llvm::DebugInfoFinder::compile_unit_begin(), llvm::DebugInfoFinder::compile_unit_end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), llvm::Module::end(), F(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::find(), llvm::DIScope::getDirectory(), llvm::DIScope::getFilename(), llvm::Function::getIntrinsicID(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), i, I, llvm::sys::path::is_absolute(), llvm::GlobalValue::isDeclaration(), M, llvm::DebugInfoFinder::processModule(), llvm::DebugInfoFinder::subprogram_begin(), llvm::DebugInfoFinder::subprogram_end(), llvm::Value::use_begin(), llvm::Value::use_empty(), llvm::Value::use_end(), and usedInGlobalVarDef().
Variable Documentation
cl::opt<bool> EmitLineNumbers("nvptx-emit-line-numbers", cl::Hidden, cl::desc("NVPTX Specific: Emit Line numbers even without -G"), cl::init(true)) static
Referenced by llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc().
cl::opt<bool> InterleaveSrc("nvptx-emit-src", cl::ZeroOrMore, cl::Hidden, cl::desc("NVPTX Specific: Emit source line in ptx file"), cl::init(false)) static
Referenced by llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc().