LLVM: NVPTXPrologEpilogPass.cpp File Reference
LLVM API Documentation
NVPTXPrologEpilogPass.cpp File Reference
#include "NVPTX.h"
#include "llvm/Pass.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/Target/TargetFrameLowering.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Functions
static void AdjustStackOffset (MachineFrameInfo *MFI, int FrameIdx, bool StackGrowsDown, int64_t &Offset, unsigned &MaxAlign)
AdjustStackOffset - Helper function used to adjust the stack frame offset.
Function Documentation
static void AdjustStackOffset (MachineFrameInfo * MFI, int FrameIdx, bool StackGrowsDown, int64_t & Offset, unsigned & MaxAlign) inline static
AdjustStackOffset - Helper function used to adjust the stack frame offset.
Definition at line 81 of file NVPTXPrologEpilogPass.cpp.
References llvm::MachineFrameInfo::adjustsStack(), Align, llvm::dbgs(), DEBUG, llvm::MachineFunction::getFrameInfo(), llvm::TargetMachine::getFrameLowering(), llvm::MachineFrameInfo::getLocalFrameMaxAlign(), llvm::MachineFrameInfo::getLocalFrameObjectCount(), llvm::MachineFrameInfo::getLocalFrameObjectMap(), llvm::MachineFrameInfo::getLocalFrameSize(), llvm::MachineFrameInfo::getMaxAlignment(), llvm::MachineFrameInfo::getMaxCallFrameSize(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectIndexBegin(), llvm::MachineFrameInfo::getObjectIndexEnd(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getObjectSize(), llvm::TargetFrameLowering::getOffsetOfLocalArea(), llvm::TargetMachine::getRegisterInfo(), llvm::TargetFrameLowering::getStackAlignment(), llvm::TargetFrameLowering::getStackGrowthDirection(), llvm::MachineFunction::getTarget(), llvm::TargetFrameLowering::getTransientStackAlignment(), llvm::MachineFrameInfo::getUseLocalStackAllocationBlock(), llvm::TargetFrameLowering::hasReservedCallFrame(), llvm::MachineFrameInfo::hasVarSizedObjects(), i, llvm::MachineFrameInfo::isDeadObjectIndex(), llvm::MachineFrameInfo::isObjectPreAllocated(), llvm::TargetRegisterInfo::needsStackRealignment(), llvm::MachineFrameInfo::setObjectOffset(), llvm::MachineFrameInfo::setStackSize(), llvm::TargetFrameLowering::StackGrowsDown, and llvm::TargetFrameLowering::targetHandlesStackFrameRounding().