LLVM: NVPTXGenericToNVVM.cpp File Reference
LLVM API Documentation
NVPTXGenericToNVVM.cpp File Reference
#include "NVPTX.h"
#include "NVPTXUtilities.h"
#include "MCTargetDesc/NVPTXBaseInfo.h"
#include "llvm/PassManager.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/ADT/ValueMap.h"
#include "llvm/CodeGen/MachineFunctionAnalysis.h"
#include "llvm/CodeGen/ValueTypes.h"
#include "llvm/IR/IRBuilder.h"
Namespaces
llvm
List of target independent CodeGen pass IDs.
Functions
void llvm::initializeGenericToNVVMPass (PassRegistry &)
INITIALIZE_PASS (GenericToNVVM,"generic-to-nvvm","Ensure that the global variables are in the global address space", false, false) bool GenericToNVVM
Function Documentation
INITIALIZE_PASS (GenericToNVVM , "generic-to-nvvm" , "Ensure that the global variables are in the global address space" , false , false)
Definition at line 73 of file NVPTXGenericToNVVM.cpp.
References llvm::NamedMDNode::addOperand(), llvm::ADDRESS_SPACE_GENERIC, llvm::ADDRESS_SPACE_GLOBAL, llvm::SmallVectorTemplateCommon< T >::begin(), llvm::GlobalVariable::copyAttributesFrom(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateBinOp(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateBitCast(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateCall(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateCast(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateExtractElement(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateExtractValue(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateGEP(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateICmp(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateInBoundsGEP(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateInsertElement(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateInsertValue(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateSelect(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateShuffleVector(), llvm::NamedMDNode::dropAllReferences(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::GlobalVariable::eraseFromParent(), ExtractElement(), F(), llvm::ConstantInt::get(), llvm::MDNode::get(), llvm::PointerType::get(), llvm::UndefValue::get(), llvm::PointerType::getAddressSpace(), llvm::Module::getContext(), llvm::Intrinsic::getDeclaration(), llvm::SequentialType::getElementType(), llvm::EVT::getEVT(), llvm::ConstantExpr::getIndices(), llvm::GlobalVariable::getInitializer(), llvm::Type::getInt32Ty(), llvm::Type::getInt8Ty(), llvm::GlobalValue::getLinkage(), llvm::Value::getName(), llvm::User::getNumOperands(), llvm::MDNode::getNumOperands(), llvm::NamedMDNode::getNumOperands(), llvm::ConstantExpr::getOpcode(), llvm::User::getOperand(), llvm::MDNode::getOperand(), llvm::NamedMDNode::getOperand(), llvm::ConstantExpr::getPointerCast(), llvm::ConstantExpr::getPredicate(), llvm::GlobalVariable::getThreadLocalMode(), llvm::GlobalValue::getType(), llvm::Value::getType(), llvm::GlobalVariable::hasInitializer(), i, I, llvm::ARM_PROC::IE, llvm::Instruction::isBinaryOp(), llvm::Instruction::isCast(), llvm::GlobalVariable::isConstant(), llvm::EVT::isFloatingPoint(), llvm::EVT::isInteger(), llvm::isSurface(), llvm::isTexture(), M, llvm::makeArrayRef(), N, llvm::Intrinsic::nvvm_ptr_global_to_gen, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::Constant::removeDeadConstantUsers(), llvm::MCID::Select, llvm::Use::set(), llvm::Value::setName(), llvm::StringRef::startswith(), llvm::Value::use_begin(), and llvm::Value::use_end().