LLVM: NVPTXISelDAGToDAG.cpp File Reference
LLVM API Documentation
NVPTXISelDAGToDAG.cpp File Reference
#include "NVPTXISelDAGToDAG.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/Instructions.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetIntrinsicInfo.h"
Macros
#define DEBUG_TYPE "nvptx-isel"
Functions
static unsigned int getCodeAddrSpace (MemSDNode *N, const NVPTXSubtarget &Subtarget)
Variables
static cl::opt< int > FMAContractLevel ("nvptx-fma-level", cl::ZeroOrMore, cl::Hidden, cl::desc("NVPTX Specific: FMA contraction (0: don't do it"" 1: do it 2: do it aggressively"), cl::init(2))
static cl::opt< int > UsePrecDivF32 ("nvptx-prec-divf32", cl::ZeroOrMore, cl::Hidden, cl::desc("NVPTX Specifies: 0 use div.approx, 1 use div.full, 2 use"" IEEE Compliant F32 div.rnd if avaiable."), cl::init(2))
static cl::opt< bool > UsePrecSqrtF32 ("nvptx-prec-sqrtf32", cl::Hidden, cl::desc("NVPTX Specific: 0 use sqrt.approx, 1 use sqrt.rn."), cl::init(true))
static cl::opt< bool > FtzEnabled ("nvptx-f32ftz", cl::ZeroOrMore, cl::Hidden, cl::desc("NVPTX Specific: Flush f32 subnormals to sign-preserving zero."), cl::init(false))
Macro Definition Documentation
#define DEBUG_TYPE "nvptx-isel"
Definition at line 24 of file NVPTXISelDAGToDAG.cpp.
Function Documentation
static unsigned int getCodeAddrSpace (MemSDNode * N, const NVPTXSubtarget & Subtarget) static
Definition at line 173 of file NVPTXISelDAGToDAG.cpp.
References llvm::ISD::ADD, llvm::ADDRESS_SPACE_CONST, llvm::ADDRESS_SPACE_GENERIC, llvm::ADDRESS_SPACE_GLOBAL, llvm::ADDRESS_SPACE_LOCAL, llvm::ADDRESS_SPACE_PARAM, llvm::ADDRESS_SPACE_SHARED, base, llvm::ISD::Constant, llvm::NVPTX::PTXLdStInstCode::CONSTANT, EVTs, llvm::MVT::f32, llvm::MVT::f64, llvm::NVPTX::PTXLdStInstCode::Float, llvm::NVPTX::PTXLdStInstCode::GENERIC, llvm::LoadSDNode::getExtensionType(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SDNode::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MVT::getScalarType(), llvm::SDNode::getSimpleValueType(), llvm::EVT::getSimpleVT(), llvm::MVT::getSizeInBits(), llvm::MemSDNode::getSrcValue(), llvm::Value::getType(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::SDNode::getVTList(), llvm::ConstantSDNode::getZExtValue(), llvm::NVPTX::PTXLdStInstCode::GLOBAL, llvm::MVT::Glue, i, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::MVT::isFloatingPoint(), llvm::LSBaseSDNode::isIndexed(), llvm::MVT::isVector(), llvm::MemSDNode::isVolatile(), llvm::A64DB::LD, llvm::NVPTXISD::LDGV2, llvm::NVPTXISD::LDGV4, llvm::NVPTXISD::LDUV2, llvm::NVPTXISD::LDUV4, llvm::NVPTXISD::LoadParam, llvm::NVPTXISD::LoadParamV2, llvm::NVPTXISD::LoadParamV4, llvm::NVPTXISD::LoadV2, llvm::NVPTXISD::LoadV4, llvm::NVPTX::PTXLdStInstCode::LOCAL, llvm::NVPTXISD::MoveParam, N, llvm::NVPTX::PTXCvtMode::NONE, llvm::Intrinsic::nvvm_ptr_gen_to_param, llvm::MVT::Other, llvm::NVPTX::PTXLdStInstCode::PARAM, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::report_fatal_error(), llvm::AArch64ISD::Ret, llvm::NVPTX::PTXLdStInstCode::Scalar, llvm::ISD::SEXTLOAD, llvm::NVPTX::PTXLdStInstCode::SHARED, llvm::NVPTX::PTXLdStInstCode::Signed, llvm::MVT::SimpleTy, llvm::A64DB::ST, llvm::NVPTXISD::StoreParam, llvm::NVPTXISD::StoreParamS32, llvm::NVPTXISD::StoreParamU32, llvm::NVPTXISD::StoreParamV2, llvm::NVPTXISD::StoreParamV4, llvm::NVPTXISD::StoreRetval, llvm::NVPTXISD::StoreRetvalV2, llvm::NVPTXISD::StoreRetvalV4, llvm::NVPTXISD::StoreV2, llvm::NVPTXISD::StoreV4, llvm::ISD::TargetExternalSymbol, llvm::ISD::TargetGlobalAddress, llvm::ISD::UNDEF, llvm::NVPTX::PTXLdStInstCode::Unsigned, llvm::NVPTX::PTXLdStInstCode::V2, llvm::NVPTX::PTXLdStInstCode::V4, and llvm::NVPTXISD::Wrapper.
Variable Documentation
cl::opt<int> FMAContractLevel("nvptx-fma-level", cl::ZeroOrMore, cl::Hidden, cl::desc("NVPTX Specific: FMA contraction (0: don't do it"" 1: do it 2: do it aggressively"), cl::init(2)) static
Referenced by llvm::createNVPTXISelDag().
cl::opt<bool> FtzEnabled("nvptx-f32ftz", cl::ZeroOrMore, cl::Hidden, cl::desc("NVPTX Specific: Flush f32 subnormals to sign-preserving zero."), cl::init(false)) static
Referenced by llvm::createNVPTXISelDag().
cl::opt<int> UsePrecDivF32("nvptx-prec-divf32", cl::ZeroOrMore, cl::Hidden, cl::desc("NVPTX Specifies: 0 use div.approx, 1 use div.full, 2 use"" IEEE Compliant F32 div.rnd if avaiable."), cl::init(2)) static
Referenced by llvm::createNVPTXISelDag().
cl::opt<bool> UsePrecSqrtF32("nvptx-prec-sqrtf32", cl::Hidden, cl::desc("NVPTX Specific: 0 use sqrt.approx, 1 use sqrt.rn."), cl::init(true)) static
Referenced by llvm::createNVPTXISelDag().