LLVM: ObjCARCAPElim.cpp File Reference
LLVM API Documentation
ObjCARCAPElim.cpp File Reference
#include "ObjCARC.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/IR/Constants.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "objc-arc-ap-elim"
Functions
INITIALIZE_PASS (ObjCARCAPElim,"objc-arc-apelim","ObjC ARC autorelease pool elimination", false, false) Pass *llvm
Detailed Description
This file defines ObjC ARC optimizations. ARC stands for Automatic Reference Counting and is a system for managing reference counts for objects in Objective C.
This specific file implements optimizations which remove extraneous autorelease pools.
WARNING: This file knows about certain library functions. It recognizes them by name, and hardwires knowledge of their semantics.
WARNING: This file knows about how certain Objective-C library functions are used. Naive LLVM IR transformations which would otherwise be behavior-preserving may break these assumptions.
Definition in file ObjCARCAPElim.cpp.
Macro Definition Documentation
#define DEBUG_TYPE "objc-arc-ap-elim"
Definition at line 27 of file ObjCARCAPElim.cpp.
Function Documentation
INITIALIZE_PASS (ObjCARCAPElim , "objc-arc-apelim" , "ObjC ARC autorelease pool elimination" , false , false)
Definition at line 55 of file ObjCARCAPElim.cpp.
References BB, llvm::BasicBlock::begin(), llvm::Function::begin(), llvm::dbgs(), DEBUG, llvm::dyn_cast(), llvm::objcarc::EnableARCOpts, llvm::BasicBlock::end(), llvm::Function::end(), llvm::Instruction::eraseFromParent(), F(), llvm::objcarc::GetBasicInstructionClass(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledFunction(), llvm::Module::getGlobalVariable(), llvm::GlobalVariable::getInitializer(), llvm::GlobalVariable::hasDefinitiveInitializer(), I, llvm::objcarc::IC_AutoreleasepoolPop, llvm::objcarc::IC_AutoreleasepoolPush, llvm::objcarc::IC_CallOrUser, llvm::GlobalValue::isDeclaration(), M, llvm::objcarc::ModuleHasARC(), llvm::next(), llvm::User::op_begin(), llvm::User::op_end(), and llvm::AnalysisUsage::setPreservesCFG().