LLVM: ObjCARCAliasAnalysis.cpp File Reference
LLVM API Documentation
ObjCARCAliasAnalysis.cpp File Reference
#include "ObjCARC.h"
#include "ObjCARCAliasAnalysis.h"
#include "llvm/IR/Instruction.h"
#include "llvm/InitializePasses.h"
#include "llvm/PassAnalysisSupport.h"
#include "llvm/PassSupport.h"
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "objc-arc-aa"
Functions
INITIALIZE_AG_PASS (ObjCARCAliasAnalysis, AliasAnalysis,"objc-arc-aa","ObjC-ARC-Based Alias Analysis", false, true, false) ImmutablePass *llvm
Detailed Description
This file defines a simple ARC-aware AliasAnalysis using special knowledge of Objective C to enhance other optimization passes which rely on the Alias Analysis infrastructure.
WARNING: This file knows about certain library functions. It recognizes them by name, and hardwires knowledge of their semantics.
WARNING: This file knows about how certain Objective-C library functions are used. Naive LLVM IR transformations which would otherwise be behavior-preserving may break these assumptions.
Definition in file ObjCARCAliasAnalysis.cpp.
Macro Definition Documentation
#define DEBUG_TYPE "objc-arc-aa"
Definition at line 23 of file ObjCARCAliasAnalysis.cpp.
Function Documentation
INITIALIZE_AG_PASS (ObjCARCAliasAnalysis , AliasAnalysis , "objc-arc-aa" , "ObjC-ARC-Based Alias Analysis" , false , true , false)
Definition at line 41 of file ObjCARCAliasAnalysis.cpp.
References llvm::AliasAnalysis::alias(), llvm::AliasAnalysis::DoesNotAccessMemory, llvm::objcarc::EnableARCOpts, F(), llvm::AliasAnalysis::getAnalysisUsage(), llvm::objcarc::GetBasicInstructionClass(), llvm::objcarc::GetFunctionClass(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getInstruction(), llvm::AliasAnalysis::getModRefBehavior(), llvm::AliasAnalysis::getModRefInfo(), llvm::objcarc::GetUnderlyingObjCPtr(), llvm::objcarc::IC_Autorelease, llvm::objcarc::IC_AutoreleasepoolPush, llvm::objcarc::IC_AutoreleaseRV, llvm::objcarc::IC_FusedRetainAutorelease, llvm::objcarc::IC_FusedRetainAutoreleaseRV, llvm::objcarc::IC_NoopCast, llvm::objcarc::IC_Retain, llvm::objcarc::IC_RetainRV, llvm::AliasAnalysis::MayAlias, llvm::AliasAnalysis::NoAlias, llvm::AliasAnalysis::NoModRef, llvm::AliasAnalysis::pointsToConstantMemory(), S, llvm::AnalysisUsage::setPreservesAll(), and llvm::objcarc::StripPointerCastsAndObjCCalls().