LLVM: OcamlGCPrinter.cpp File Reference
LLVM API Documentation
OcamlGCPrinter.cpp File Reference
#include "llvm/CodeGen/GCs.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/GCMetadataPrinter.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Target/Mangler.h"
#include "llvm/Target/TargetLoweringObjectFile.h"
#include "llvm/Target/TargetMachine.h"
#include <cctype>
Functions
static void EmitCamlGlobal (const Module &M, AsmPrinter &AP, const char *Id)
Variables
static GCMetadataPrinterRegistry::Add< OcamlGCMetadataPrinter > Y ("ocaml","ocaml 3.10-compatible collector")
Function Documentation
static void EmitCamlGlobal (const Module & M, AsmPrinter & AP, const char * Id) static
Definition at line 47 of file OcamlGCPrinter.cpp.
References llvm::MCStreamer::AddBlankLine(), llvm::MCStreamer::AddComment(), llvm::sys::path::begin(), llvm::GCFunctionInfo::begin(), llvm::AsmPrinter::EmitAlignment(), llvm::AsmPrinter::EmitInt16(), llvm::MCStreamer::EmitIntValue(), llvm::MCStreamer::EmitLabel(), llvm::MCStreamer::EmitSymbolAttribute(), llvm::MCStreamer::EmitSymbolValue(), llvm::sys::path::end(), llvm::GCFunctionInfo::end(), llvm::TargetMachine::getDataLayout(), llvm::MCObjectFileInfo::getDataSection(), llvm::GCFunctionInfo::getFrameSize(), llvm::GCFunctionInfo::getFunction(), llvm::Module::getModuleIdentifier(), llvm::Value::getName(), llvm::Mangler::getNameWithPrefix(), llvm::AsmPrinter::getObjFileLowering(), llvm::MCContext::GetOrCreateSymbol(), llvm::DataLayout::getPointerSize(), llvm::MCObjectFileInfo::getTextSection(), I, llvm::tgtok::Id, llvm::ARM_PROC::IE, llvm::GCFunctionInfo::live_begin(), llvm::GCFunctionInfo::live_end(), llvm::GCFunctionInfo::live_size(), llvm::AsmPrinter::Mang, llvm::MCSA_Global, llvm::AsmPrinter::OutContext, llvm::AsmPrinter::OutStreamer, llvm::report_fatal_error(), llvm::MCStreamer::SwitchSection(), and llvm::AsmPrinter::TM.
Variable Documentation
GCMetadataPrinterRegistry::Add<OcamlGCMetadataPrinter> Y("ocaml","ocaml 3.10-compatible collector") static
Referenced by llvm::cast(), foldSelectICmpAndOr(), getPointerOperand(), llvm::ScalarEvolution::getSignedRange(), llvm::ScalarEvolution::getUnsignedRange(), llvm::isa(), isConstantSplatVector(), llvm::isKnownNonZero(), llvm::isKnownToBeAPowerOfTwo(), isRemainderZero(), llvm::FullDependence::isSplitable(), isTruncWithZeroHighBitsInput(), LLVMInitializeARMAsmParser(), LLVMInitializeARMAsmPrinter(), LLVMInitializeARMTarget(), LLVMInitializeARMTargetInfo(), LLVMInitializeMipsAsmParser(), LLVMInitializeMipsAsmPrinter(), LLVMInitializeMipsTarget(), LLVMInitializeMipsTargetInfo(), LLVMInitializeMipsTargetMC(), LLVMInitializeNVPTXAsmPrinter(), LLVMInitializeNVPTXBackendAsmPrinter(), LLVMInitializeNVPTXTarget(), LLVMInitializeNVPTXTargetInfo(), LLVMInitializeNVPTXTargetMC(), LLVMInitializePowerPCTargetInfo(), LLVMInitializeR600TargetMC(), LLVMInitializeSparcAsmPrinter(), LLVMInitializeSparcTarget(), LLVMInitializeSparcTargetInfo(), LLVMInitializeSparcTargetMC(), LLVMInitializeX86AsmParser(), LLVMInitializeX86AsmPrinter(), LLVMInitializeX86Target(), LLVMInitializeX86TargetInfo(), load(), lowerFCOPYSIGN32(), lowerFCOPYSIGN64(), LowerSDIV_v4i8(), minAPInt(), PerformOrCombine(), llvm::HexagonMCInst::setPacketEnd(), llvm::HexagonMCInst::setPacketStart(), SimplifyAddInst(), SimplifyDiv(), SimplifyICmpInst(), SimplifySubInst(), llvm::opt::StrCmpOptionNameIgnoreCase(), llvm::InstCombiner::visitAdd(), llvm::InstCombiner::visitBranchInst(), llvm::InstCombiner::visitFCmpInst(), llvm::InstCombiner::visitFDiv(), llvm::InstCombiner::visitFMul(), llvm::InstCombiner::visitICmpInst(), llvm::InstCombiner::visitMul(), llvm::InstCombiner::visitOr(), and llvm::InstCombiner::visitSub().