LLVM: OptimizePHIs.cpp File Reference
LLVM API Documentation
OptimizePHIs.cpp File Reference
#include "llvm/CodeGen/Passes.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/Target/TargetInstrInfo.h"
Macros
#define DEBUG_TYPE "phi-opt"
Functions
STATISTIC (NumPHICycles,"Number of PHI cycles replaced")
STATISTIC (NumDeadPHICycles,"Number of dead PHI cycles")
INITIALIZE_PASS (OptimizePHIs,"opt-phis","Optimize machine instruction PHIs", false, false) bool OptimizePHIs
Macro Definition Documentation
#define DEBUG_TYPE "phi-opt"
Definition at line 15 of file OptimizePHIs.cpp.
Function Documentation
INITIALIZE_PASS (OptimizePHIs , "opt-phis" , "Optimize machine instruction PHIs" , false , false)
Definition at line 60 of file OptimizePHIs.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineRegisterInfo::constrainRegClass(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineOperand::getSubReg(), llvm::MachineRegisterInfo::getVRegDef(), i, I, llvm::MachineInstr::isCopy(), llvm::MachineInstr::isPHI(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::A64CC::MI, MII, llvm::MachineRegisterInfo::replaceRegWith(), llvm::MachineRegisterInfo::use_begin(), and llvm::MachineRegisterInfo::use_end().
STATISTIC (NumPHICycles , "Number of PHI cycles replaced")
STATISTIC (NumDeadPHICycles , "Number of dead PHI cycles")