LLVM: PartialInlining.cpp File Reference
LLVM API Documentation
PartialInlining.cpp File Reference
#include "llvm/Transforms/IPO.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/Dominators.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include "llvm/Support/CFG.h"
#include "llvm/Transforms/Utils/Cloning.h"
#include "llvm/Transforms/Utils/CodeExtractor.h"
Macros
#define DEBUG_TYPE "partialinlining"
Functions
STATISTIC (NumPartialInlined,"Number of functions partially inlined")
INITIALIZE_PASS (PartialInliner,"partial-inliner","Partial Inliner", false, false) ModulePass *llvm
Macro Definition Documentation
#define DEBUG_TYPE "partialinlining"
Definition at line 15 of file PartialInlining.cpp.
Function Documentation
INITIALIZE_PASS (PartialInliner , "partial-inliner" , "Partial Inliner" , false , false)
Definition at line 45 of file PartialInlining.cpp.
References llvm::PHINode::addIncoming(), llvm::Function::back(), llvm::BasicBlock::begin(), llvm::Function::begin(), llvm::Module::begin(), llvm::ISD::BR, llvm::CloneFunction(), llvm::PHINode::Create(), llvm::dyn_cast(), llvm::BasicBlock::end(), llvm::Function::end(), llvm::Module::end(), llvm::Function::eraseFromParent(), llvm::CodeExtractor::extractCodeRegion(), F(), llvm::Module::getFunctionList(), llvm::PHINode::getIncomingValueForBlock(), llvm::GlobalValue::getParent(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), I, llvm::InlineFunction(), llvm::MipsISD::Ins, llvm::GlobalValue::InternalLinkage, llvm::BranchInst::isUnconditional(), M, llvm::iplist< NodeTy, Traits >::push_back(), llvm::PHINode::removeIncomingValue(), llvm::Value::replaceAllUsesWith(), llvm::User::replaceUsesOfWith(), llvm::DominatorTree::runOnFunction(), llvm::GlobalValue::setLinkage(), llvm::Module::size(), llvm::BasicBlock::splitBasicBlock(), llvm::succ_begin(), llvm::succ_end(), llvm::Value::use_begin(), llvm::Value::use_empty(), llvm::Value::use_end(), and Users.
STATISTIC (NumPartialInlined , "Number of functions partially inlined")