LLVM: PassManagerBuilder.cpp File Reference
LLVM API Documentation
PassManagerBuilder.cpp File Reference
#include "llvm/Transforms/IPO/PassManagerBuilder.h"
#include "llvm-c/Transforms/PassManagerBuilder.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/Analysis/Passes.h"
#include "llvm/Analysis/Verifier.h"
#include "llvm/PassManager.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Target/TargetLibraryInfo.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Vectorize.h"
Functions
PassManagerBuilder * unwrap (LLVMPassManagerBuilderRef P)
LLVMPassManagerBuilderRef wrap (PassManagerBuilder *P)
LLVMPassManagerBuilderRef LLVMPassManagerBuilderCreate ()
void LLVMPassManagerBuilderDispose (LLVMPassManagerBuilderRef PMB)
void LLVMPassManagerBuilderSetOptLevel (LLVMPassManagerBuilderRef PMB, unsigned OptLevel)
void LLVMPassManagerBuilderSetSizeLevel (LLVMPassManagerBuilderRef PMB, unsigned SizeLevel)
void LLVMPassManagerBuilderSetDisableUnitAtATime (LLVMPassManagerBuilderRef PMB, LLVMBool Value)
void LLVMPassManagerBuilderSetDisableUnrollLoops (LLVMPassManagerBuilderRef PMB, LLVMBool Value)
void LLVMPassManagerBuilderSetDisableSimplifyLibCalls (LLVMPassManagerBuilderRef PMB, LLVMBool Value)
void LLVMPassManagerBuilderUseInlinerWithThreshold (LLVMPassManagerBuilderRef PMB, unsigned Threshold)
void LLVMPassManagerBuilderPopulateFunctionPassManager (LLVMPassManagerBuilderRef PMB, LLVMPassManagerRef PM)
void LLVMPassManagerBuilderPopulateModulePassManager (LLVMPassManagerBuilderRef PMB, LLVMPassManagerRef PM)
void LLVMPassManagerBuilderPopulateLTOPassManager (LLVMPassManagerBuilderRef PMB, LLVMPassManagerRef PM, LLVMBool Internalize, LLVMBool RunInliner)
Variables
static cl::opt< bool > RunLoopVectorization ("vectorize-loops", cl::Hidden, cl::desc("Run the Loop vectorization passes"))
static cl::opt< bool > LateVectorization ("late-vectorize", cl::init(true), cl::Hidden, cl::desc("Run the vectorization pasess late in the pass ""pipeline (after the inliner)"))
static cl::opt< bool > RunSLPVectorization ("vectorize-slp", cl::Hidden, cl::desc("Run the SLP vectorization passes"))
static cl::opt< bool > RunBBVectorization ("vectorize-slp-aggressive", cl::Hidden, cl::desc("Run the BB vectorization passes"))
static cl::opt< bool > UseGVNAfterVectorization ("use-gvn-after-vectorization", cl::init(false), cl::Hidden, cl::desc("Run GVN instead of Early CSE after vectorization passes"))
static cl::opt< bool > UseNewSROA ("use-new-sroa", cl::init(true), cl::Hidden, cl::desc("Enable the new, experimental SROA pass"))
static cl::opt< bool > RunLoopRerolling ("reroll-loops", cl::Hidden, cl::desc("Run the loop rerolling pass"))
static ManagedStatic< SmallVector< std::pair< PassManagerBuilder::ExtensionPointTy, PassManagerBuilder::ExtensionFn >, 8 > > GlobalExtensions
Set of global extensions, automatically added as part of the standard set.
Function Documentation
PassManagerBuilder* unwrap (LLVMPassManagerBuilderRef P) inline
Definition at line 358 of file PassManagerBuilder.cpp.
References P.
LLVMPassManagerBuilderRef wrap (PassManagerBuilder * P) inline
Definition at line 362 of file PassManagerBuilder.cpp.
References P.
Variable Documentation
ManagedStatic<SmallVector<std::pair<PassManagerBuilder::ExtensionPointTy, PassManagerBuilder::ExtensionFn>, 8> > GlobalExtensions static
Set of global extensions, automatically added as part of the standard set.
Definition at line 82 of file PassManagerBuilder.cpp.
cl::opt<bool> LateVectorization("late-vectorize", cl::init(true), cl::Hidden, cl::desc("Run the vectorization pasess late in the pass ""pipeline (after the inliner)")) static
Referenced by llvm::PassManagerBuilder::PassManagerBuilder().
cl::opt<bool> RunBBVectorization("vectorize-slp-aggressive", cl::Hidden, cl::desc("Run the BB vectorization passes")) static
Referenced by llvm::PassManagerBuilder::PassManagerBuilder().
cl::opt<bool> RunLoopRerolling("reroll-loops", cl::Hidden, cl::desc("Run the loop rerolling pass")) static
Referenced by llvm::PassManagerBuilder::PassManagerBuilder().
cl::opt<bool> RunLoopVectorization("vectorize-loops", cl::Hidden, cl::desc("Run the Loop vectorization passes")) static
Referenced by llvm::PassManagerBuilder::PassManagerBuilder().
cl::opt<bool> RunSLPVectorization("vectorize-slp", cl::Hidden, cl::desc("Run the SLP vectorization passes")) static
Referenced by llvm::PassManagerBuilder::PassManagerBuilder().
cl::opt<bool> UseGVNAfterVectorization("use-gvn-after-vectorization", cl::init(false), cl::Hidden, cl::desc("Run GVN instead of Early CSE after vectorization passes")) static
Referenced by llvm::PassManagerBuilder::populateModulePassManager().
cl::opt<bool> UseNewSROA("use-new-sroa", cl::init(true), cl::Hidden, cl::desc("Enable the new, experimental SROA pass")) static
Referenced by llvm::PassManagerBuilder::populateFunctionPassManager(), llvm::PassManagerBuilder::populateLTOPassManager(), and llvm::PassManagerBuilder::populateModulePassManager().