LLVM: PeepholeOptimizer.cpp File Reference
LLVM API Documentation
PeepholeOptimizer.cpp File Reference
#include "llvm/CodeGen/Passes.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetRegisterInfo.h"
Macros
#define DEBUG_TYPE "peephole-opt"
Functions
STATISTIC (NumReuse,"Number of extension results reused")
STATISTIC (NumCmps,"Number of compares eliminated")
STATISTIC (NumImmFold,"Number of move immediate folded")
STATISTIC (NumLoadFold,"Number of loads folded")
STATISTIC (NumSelects,"Number of selects optimized")
STATISTIC (NumCopiesBitcasts,"Number of copies/bitcasts optimized")
INITIALIZE_PASS_BEGIN (PeepholeOptimizer,"peephole-opts","Peephole Optimizations", false, false) INITIALIZE_PASS_END(PeepholeOptimizer
static bool shareSameRegisterFile (const TargetRegisterInfo &TRI, const TargetRegisterClass *DefRC, unsigned DefSubReg, const TargetRegisterClass *SrcRC, unsigned SrcSubReg)
Check if the registers defined by the pair (RegisterClass, SubReg) share the same register file.
static bool getCopyOrBitcastDefUseIdx (const MachineInstr &Copy, unsigned &DefIdx, unsigned &SrcIdx)
Get the index of the definition and source for Copy instruction.
Variables
static cl::opt< bool > Aggressive ("aggressive-ext-opt", cl::Hidden, cl::desc("Aggressive extension optimization"))
static cl::opt< bool > DisablePeephole ("disable-peephole", cl::Hidden, cl::init(false), cl::desc("Disable the peephole optimizer"))
peephole opts
peephole Peephole Optimizations
peephole Peephole false
Macro Definition Documentation
#define DEBUG_TYPE "peephole-opt"
Definition at line 69 of file PeepholeOptimizer.cpp.
Function Documentation
static bool getCopyOrBitcastDefUseIdx (const MachineInstr & Copy, unsigned & DefIdx, unsigned & SrcIdx) static
Get the index of the definition and source for Copy instruction.
Precondition
Copy.isCopy() or Copy.isBitcast().
Returns
True if the Copy instruction has only one register source and one register definition. Otherwise, DefIdx and SrcIdx are invalid.
Definition at line 388 of file PeepholeOptimizer.cpp.
References Aggressive, llvm::MachineFunction::begin(), llvm::BuildMI(), llvm::MachineInstr::canFoldAsLoad(), llvm::SmallPtrSetImpl::clear(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::clear(), llvm::SmallSet< T, N, C >::clear(), llvm::MachineRegisterInfo::clearKillFlags(), llvm::TargetOpcode::COPY, llvm::SmallSet< T, N, C >::count(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::dbgs(), DEBUG, llvm::tgtok::Def, DisablePeephole, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), llvm::MachineFunction::end(), llvm::SmallPtrSet< PtrType, SmallSize >::erase(), llvm::MachineInstr::eraseFromParent(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::find(), llvm::TargetInstrInfo::FoldImmediate(), llvm::MCInstrInfo::get(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getDesc(), llvm::TargetMachine::getInstrInfo(), llvm::MachineFunction::getName(), llvm::MCInstrDesc::getNumDefs(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::TargetMachine::getRegisterInfo(), llvm::MachineOperand::getSubReg(), llvm::MachineFunction::getTarget(), llvm::MachineRegisterInfo::getVRegDef(), llvm::MachineRegisterInfo::hasOneUse(), llvm::MachineInstr::hasUnmodeledSideEffects(), i, I, llvm::SmallSet< T, N, C >::insert(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::insert(), llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::MachineInstr::isBitcast(), llvm::MachineInstr::isCall(), llvm::MachineInstr::isCompare(), llvm::MachineInstr::isCopy(), llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isDef(), llvm::MachineInstr::isImplicitDef(), llvm::MachineInstr::isInlineAsm(), llvm::MachineInstr::isKill(), llvm::MachineInstr::isLabel(), llvm::MachineInstr::isMoveImmediate(), llvm::MachineInstr::isPHI(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::MachineOperand::isReg(), llvm::MachineInstr::isSelect(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::MachineInstr::mayLoad(), llvm::MachineInstr::mayStore(), llvm::A64CC::MI, MII, llvm::TargetInstrInfo::optimizeLoadInstr(), llvm::MachineRegisterInfo::replaceRegWith(), llvm::MachineOperand::setSubReg(), and shareSameRegisterFile().
INITIALIZE_PASS_BEGIN (PeepholeOptimizer , "peephole-opts" , "Peephole Optimizations" , false , false)
static bool shareSameRegisterFile (const TargetRegisterInfo & TRI, const TargetRegisterClass * DefRC, unsigned DefSubReg, const TargetRegisterClass * SrcRC, unsigned SrcSubReg) static
Check if the registers defined by the pair (RegisterClass, SubReg) share the same register file.
Definition at line 354 of file PeepholeOptimizer.cpp.
References llvm::TargetRegisterInfo::getCommonSubClass(), llvm::TargetRegisterInfo::getCommonSuperRegClass(), llvm::TargetRegisterInfo::getMatchingSuperRegClass(), and std::swap().
Referenced by getCopyOrBitcastDefUseIdx().
STATISTIC (NumReuse , "Number of extension results reused")
STATISTIC (NumCmps , "Number of compares eliminated")
STATISTIC (NumImmFold , "Number of move immediate folded")
STATISTIC (NumLoadFold , "Number of loads folded")
STATISTIC (NumSelects , "Number of selects optimized")
STATISTIC (NumCopiesBitcasts , "Number of copies/bitcasts optimized")
Variable Documentation
cl::opt<bool> Aggressive("aggressive-ext-opt", cl::Hidden, cl::desc("Aggressive extension optimization")) static
Referenced by LTOCodeGenerator::compile(), and getCopyOrBitcastDefUseIdx().
cl::opt<bool> DisablePeephole("disable-peephole", cl::Hidden, cl::init(false), cl::desc("Disable the peephole optimizer")) static
Referenced by getCopyOrBitcastDefUseIdx().
peephole Peephole false
Definition at line 145 of file PeepholeOptimizer.cpp.
peephole Peephole Optimizations
Definition at line 145 of file PeepholeOptimizer.cpp.
peephole opts
Definition at line 145 of file PeepholeOptimizer.cpp.
Referenced by LTOCodeGenerator::addMustPreserveSymbol().