LLVM: PHIElimination.cpp File Reference
LLVM API Documentation
PHIElimination.cpp File Reference
#include "llvm/CodeGen/Passes.h"
#include "PHIEliminationUtils.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/LiveIntervalAnalysis.h"
#include "llvm/CodeGen/LiveVariables.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetMachine.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "phielim"
Functions
STATISTIC (NumLowered,"Number of phis lowered")
STATISTIC (NumCriticalEdgesSplit,"Number of critical edges split")
STATISTIC (NumReused,"Number of reused lowered phis")
INITIALIZE_PASS_BEGIN (PHIElimination,"phi-node-elimination","Eliminate PHI nodes for register allocation", false, false) INITIALIZE_PASS_END(PHIElimination
static bool isImplicitlyDefined (unsigned VirtReg, const MachineRegisterInfo *MRI)
static bool isSourceDefinedByImplicitDef (const MachineInstr *MPhi, const MachineRegisterInfo *MRI)
Variables
static cl::opt< bool > DisableEdgeSplitting ("disable-phi-elim-edge-splitting", cl::init(false), cl::Hidden, cl::desc("Disable critical edge splitting ""during PHI elimination"))
static cl::opt< bool > SplitAllCriticalEdges ("phi-elim-split-all-critical-edges", cl::init(false), cl::Hidden, cl::desc("Split all critical edges during ""PHI elimination"))
phi node elimination
phi node Eliminate PHI nodes for register allocation
phi node Eliminate PHI nodes for register false
Macro Definition Documentation
#define DEBUG_TYPE "phielim"
Definition at line 16 of file PHIElimination.cpp.
Function Documentation
INITIALIZE_PASS_BEGIN (PHIElimination , "phi-node-elimination" , "Eliminate PHI nodes for register allocation" , false , false)
static bool isImplicitlyDefined (unsigned VirtReg, const MachineRegisterInfo * MRI) static
isImplicitlyDefined - Return true if all defs of VirtReg are implicit-defs. This includes registers with no defs.
Definition at line 199 of file PHIElimination.cpp.
References llvm::X86II::DE, llvm::MachineRegisterInfo::def_begin(), and llvm::MachineRegisterInfo::def_end().
Referenced by isSourceDefinedByImplicitDef().
static bool isSourceDefinedByImplicitDef (const MachineInstr * MPhi, const MachineRegisterInfo * MRI) static
isSourceDefinedByImplicitDef - Return true if all sources of the phi node are implicit_def's.
Definition at line 210 of file PHIElimination.cpp.
References llvm::LiveRange::addSegment(), llvm::LiveRange::begin(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::BuildMI(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::TargetOpcode::COPY, llvm::LiveRange::createDeadDef(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::dbgs(), DEBUG, llvm::VNInfo::def, llvm::MachineFunction::DeleteMachineInstr(), llvm::MachineBasicBlock::dump(), llvm::MachineBasicBlock::empty(), llvm::LiveRange::end(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::LiveRange::endIndex(), llvm::LiveVariables::VarInfo::findKill(), llvm::findPHICopyInsertPoint(), llvm::MachineBasicBlock::front(), llvm::MCInstrInfo::get(), llvm::SlotIndex::getDeadSlot(), llvm::MachineInstr::getDebugLoc(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::TargetMachine::getInstrInfo(), llvm::MachineLoopInfo::getLoopFor(), llvm::MachineOperand::getMBB(), llvm::LiveRange::getNextValue(), llvm::MachineBasicBlock::getNumber(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::SlotIndex::getRegSlot(), llvm::MachineOperand::getSubReg(), llvm::MachineFunction::getTarget(), llvm::LiveRange::getVNInfoAt(), i, I, llvm::TargetOpcode::IMPLICIT_DEF, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::SlotIndex::isDead(), llvm::MachineOperand::isDead(), isImplicitlyDefined(), llvm::MachineBasicBlock::isLandingPad(), llvm::MachineInstr::isPHI(), llvm::MachineOperand::isUndef(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::LiveRange::liveAt(), MRI, llvm::next(), llvm::prior(), llvm::MachineBasicBlock::remove(), llvm::LiveRange::removeSegment(), llvm::LiveRange::removeValNo(), SplitAllCriticalEdges, llvm::MachineBasicBlock::SplitCriticalEdge(), llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_end(), llvm::MachineBasicBlock::succ_size(), and TII.
STATISTIC (NumLowered , "Number of phis lowered")
STATISTIC (NumCriticalEdgesSplit , "Number of critical edges split")
STATISTIC (NumReused , "Number of reused lowered phis")
Variable Documentation
phi node Eliminate PHI nodes for register allocation
Definition at line 114 of file PHIElimination.cpp.
cl::opt<bool> DisableEdgeSplitting("disable-phi-elim-edge-splitting", cl::init(false), cl::Hidden, cl::desc("Disable critical edge splitting ""during PHI elimination")) static
phi node elimination
Definition at line 114 of file PHIElimination.cpp.
phi node Eliminate PHI nodes for register false
Definition at line 114 of file PHIElimination.cpp.
cl::opt<bool> SplitAllCriticalEdges("phi-elim-split-all-critical-edges", cl::init(false), cl::Hidden, cl::desc("Split all critical edges during ""PHI elimination")) static
Referenced by isSourceDefinedByImplicitDef().