LLVM: PostRASchedulerList.cpp File Reference
LLVM API Documentation
PostRASchedulerList.cpp File Reference
#include "llvm/CodeGen/Passes.h"
#include "AggressiveAntiDepBreaker.h"
#include "AntiDepBreaker.h"
#include "CriticalAntiDepBreaker.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/CodeGen/LatencyPriorityQueue.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterClassInfo.h"
#include "llvm/CodeGen/ScheduleDAGInstrs.h"
#include "llvm/CodeGen/ScheduleHazardRecognizer.h"
#include "llvm/CodeGen/SchedulerRegistry.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include "llvm/Target/TargetSubtargetInfo.h"
Macros
#define DEBUG_TYPE "post-RA-sched"
Functions
STATISTIC (NumNoops,"Number of noops inserted")
STATISTIC (NumStalls,"Number of pipeline stalls")
STATISTIC (NumFixedAnti,"Number of fixed anti-dependencies")
INITIALIZE_PASS (PostRAScheduler,"post-RA-sched","Post RA top-down list latency scheduler", false, false) SchedulePostRATDList
Variables
static cl::opt< bool > EnablePostRAScheduler ("post-RA-scheduler", cl::desc("Enable scheduling after register allocation"), cl::init(false), cl::Hidden)
static cl::opt< std::string > EnableAntiDepBreaking ("break-anti-dependencies", cl::desc("Break post-RA scheduling anti-dependencies: ""\"critical\", \"all\", or \"none\""), cl::init("none"), cl::Hidden)
static cl::opt< int > DebugDiv ("postra-sched-debugdiv", cl::desc("Debug control MBBs that are scheduled"), cl::init(0), cl::Hidden)
static cl::opt< int > DebugMod ("postra-sched-debugmod", cl::desc("Debug control MBBs that are scheduled"), cl::init(0), cl::Hidden)
Macro Definition Documentation
#define DEBUG_TYPE "post-RA-sched"
Definition at line 21 of file PostRASchedulerList.cpp.
Function Documentation
INITIALIZE_PASS (PostRAScheduler , "post-RA-sched" , "Post RA top-down list latency scheduler" , false , false)
Definition at line 200 of file PostRASchedulerList.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::TargetSubtargetInfo::ANTIDEP_ALL, llvm::TargetSubtargetInfo::ANTIDEP_CRITICAL, llvm::TargetSubtargetInfo::ANTIDEP_NONE, BB, bb, llvm::sys::path::begin(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::ScheduleDAG::clearDAG(), llvm::TargetInstrInfo::CreateTargetPostRAHazardRecognizer(), llvm::dbgs(), llvm::X86II::DE, DEBUG, DebugDiv, DebugMod, llvm::SUnit::dump(), llvm::MachineInstr::dump(), EnableAntiDepBreaking, EnablePostRAScheduler, llvm::TargetSubtargetInfo::enablePostRAScheduler(), llvm::sys::path::end(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::ScheduleDAGInstrs::enterRegion(), llvm::ScheduleDAGInstrs::exitRegion(), llvm::ScheduleDAGInstrs::finishBlock(), llvm::MachineInstr::getBundleSize(), llvm::SUnit::getDepth(), llvm::SUnit::getInstr(), llvm::TargetMachine::getInstrInfo(), llvm::TargetMachine::getInstrItineraryData(), llvm::MachineFunction::getName(), llvm::MachineBasicBlock::getNumber(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getRegMask(), llvm::TargetMachine::getSubtarget(), llvm::SDep::getSUnit(), llvm::MachineFunction::getTarget(), i, I, llvm::RegState::ImplicitDefine, llvm::zlib::isAvailable(), llvm::MachineInstr::isBundle(), llvm::MachineInstr::isCall(), llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isKill(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRegMask(), llvm::MachineInstr::isRegTiedToUseOperand(), llvm::SUnit::isScheduled, llvm::HexagonInstrInfo::isSchedulingBoundary(), llvm::MachineOperand::isUndef(), llvm::MachineOperand::isUse(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::SDep::isWeak(), llvm_unreachable, llvm::A64CC::MI, MRI, llvm::ScheduleHazardRecognizer::NoHazard, llvm::ScheduleHazardRecognizer::NoopHazard, llvm::SUnit::NumPredsLeft, P, llvm::prior(), Scheduler, llvm::SUnit::setDepthToAtLeast(), llvm::MachineOperand::setIsKill(), llvm::MachineBasicBlock::size(), llvm::MachineBasicBlock::splice(), llvm::A64DB::ST, llvm::ScheduleDAGInstrs::startBlock(), llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_end(), llvm::SUnit::Succs, TII, llvm::SystemZISD::TM, and llvm::SUnit::WeakPredsLeft.
STATISTIC (NumNoops , "Number of noops inserted")
STATISTIC (NumStalls , "Number of pipeline stalls")
STATISTIC (NumFixedAnti , "Number of fixed anti-dependencies")
Variable Documentation
cl::opt<int> DebugDiv("postra-sched-debugdiv", cl::desc("Debug control MBBs that are scheduled"), cl::init(0), cl::Hidden) static
Referenced by INITIALIZE_PASS().
cl::opt<int> DebugMod("postra-sched-debugmod", cl::desc("Debug control MBBs that are scheduled"), cl::init(0), cl::Hidden) static
Referenced by INITIALIZE_PASS().
cl::opt<std::string> EnableAntiDepBreaking("break-anti-dependencies", cl::desc("Break post-RA scheduling anti-dependencies: ""\"critical\", \"all\", or \"none\""), cl::init("none"), cl::Hidden) static
Referenced by INITIALIZE_PASS().
cl::opt<bool> EnablePostRAScheduler("post-RA-scheduler", cl::desc("Enable scheduling after register allocation"), cl::init(false), cl::Hidden) static
Referenced by INITIALIZE_PASS().