LLVM: PPCAsmPrinter.cpp File Reference
LLVM API Documentation
PPCAsmPrinter.cpp File Reference
#include "PPC.h"
#include "InstPrinter/PPCInstPrinter.h"
#include "MCTargetDesc/PPCPredicates.h"
#include "MCTargetDesc/PPCMCExpr.h"
#include "PPCSubtarget.h"
#include "PPCTargetMachine.h"
#include "PPCTargetStreamer.h"
#include "llvm/ADT/MapVector.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Assembly/Writer.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/DebugInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstBuilder.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ELF.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/Mangler.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/Target/TargetRegisterInfo.h"
Macros
#define DEBUG_TYPE "asmprinter"
Functions
static const char * stripRegisterPrefix (const char *RegName)
static MCSymbol * GetLazyPtr (MCSymbol *Sym, MCContext &Ctx)
static MCSymbol * GetAnonSym (MCSymbol *Sym, MCContext &Ctx)
static AsmPrinter * createPPCAsmPrinterPass (TargetMachine &tm, MCStreamer &Streamer)
void LLVMInitializePowerPCAsmPrinter ()
Macro Definition Documentation
#define DEBUG_TYPE "asmprinter"
Definition at line 19 of file PPCAsmPrinter.cpp.
Function Documentation
static AsmPrinter* createPPCAsmPrinterPass (TargetMachine & tm, MCStreamer & Streamer) static
createPPCAsmPrinterPass - Returns a pass that prints the PPC assembly code for a MachineFunction to the given output stream, in a format that the Darwin assembler can deal with.
Definition at line 1137 of file PPCAsmPrinter.cpp.
References llvm::TargetMachine::getSubtarget(), and llvm::PPCSubtarget::isDarwin().
Referenced by LLVMInitializePowerPCAsmPrinter().
static MCSymbol* GetAnonSym (MCSymbol * Sym, MCContext & Ctx) static
Definition at line 899 of file PPCAsmPrinter.cpp.
References llvm::MCSymbolRefExpr::Create(), llvm::PPCMCExpr::CreateHa(), llvm::PPCMCExpr::CreateLo(), llvm::MCBinaryExpr::CreateSub(), llvm::AsmPrinter::doFinalization(), llvm::MachineModuleInfoMachO::GetFnStubList(), llvm::MachineModuleInfoMachO::getGVStubEntry(), llvm::MachineModuleInfoMachO::GetGVStubList(), llvm::MachineModuleInfoMachO::GetHiddenGVStubList(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getInt(), GetLazyPtr(), llvm::MCObjectFileInfo::getLazySymbolPointerSection(), llvm::MCSymbol::getName(), llvm::MCObjectFileInfo::getNonLazySymbolPointerSection(), llvm::MCContext::GetOrCreateSymbol(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer(), llvm::SectionKind::getText(), i, I, llvm::MCAF_SubsectionsViaSymbols, llvm::MCSA_IndirectSymbol, llvm::PPCISD::MTCTR, llvm::Reloc::PIC_, llvm::MachO::S_SYMBOL_STUBS, and llvm::SystemZISD::TM.
static MCSymbol* GetLazyPtr (MCSymbol * Sym, MCContext & Ctx) static
Definition at line 893 of file PPCAsmPrinter.cpp.
References llvm::MCSymbol::getName(), llvm::MCContext::GetOrCreateSymbol(), llvm::StringRef::size(), and llvm::StringRef::substr().
Referenced by GetAnonSym().
void LLVMInitializePowerPCAsmPrinter ()
Definition at line 1147 of file PPCAsmPrinter.cpp.
References createPPCAsmPrinterPass(), llvm::TargetRegistry::RegisterAsmPrinter(), llvm::ThePPC32Target, and llvm::ThePPC64Target.
static const char* stripRegisterPrefix (const char * RegName) static
stripRegisterPrefix - This method strips the character prefix from a register name so that only the number is left. Used by for linux asm.
Definition at line 129 of file PPCAsmPrinter.cpp.
References llvm::MCInstBuilder::addExpr(), llvm::array_lengthof(), llvm::XCoreISD::BL, llvm::MCSymbolRefExpr::Create(), llvm::MCOperand::CreateExpr(), llvm::TargetOpcode::DBG_VALUE, llvm::PPC::DIR_64, llvm::PPC::DIR_7400, llvm::PPC::DIR_970, llvm::AsmPrinter::doFinalization(), llvm::dyn_cast(), llvm::Reloc::DynamicNoPIC, llvm::AsmPrinter::EmitFunctionEntryLabel(), llvm::PPCTargetStreamer::emitTCEntry(), llvm::GlobalValue::getAlignment(), llvm::MachineOperand::getBlockAddress(), llvm::MachineOperand::getGlobal(), llvm::MachineModuleInfoELF::GetGVStubList(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getNumOperands(), llvm::MachineOperand::getOffset(), llvm::MachineInstr::getOpcode(), llvm::MCInst::getOperand(), llvm::MachineInstr::getOperand(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer(), llvm::DataLayout::getPointerSizeInBits(), llvm::SectionKind::getReadOnly(), llvm::MachineOperand::getReg(), llvm::PPCInstPrinter::getRegisterName(), llvm::MachineBasicBlock::getSymbol(), llvm::MachineOperand::getSymbolName(), llvm::SectionKind::getText(), llvm::MCObjectFileInfo::getTextCoalSection(), llvm::MachineOperand::getType(), llvm::GlobalValue::hasAvailableExternallyLinkage(), llvm::GlobalValue::hasCommonLinkage(), llvm::GlobalValue::hasHiddenVisibility(), llvm::GlobalVariable::hasInitializer(), llvm::GlobalValue::hasInternalLinkage(), i, I, llvm::MachineOperand::isCPI(), llvm::GlobalValue::isDeclaration(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isJTI(), llvm::MachineOperand::isReg(), llvm::GlobalValue::isWeakForLinker(), llvm::CodeModel::Large, llvm::A64DB::LD, llvm_unreachable, llvm::LowerPPCMachineInstrToMCInst(), M, llvm::PPCISD::MFOCRF, llvm::A64CC::MI, llvm::MachineOperand::MO_BlockAddress, llvm::MachineOperand::MO_ConstantPoolIndex, llvm::MachineOperand::MO_ExternalSymbol, llvm::MachineOperand::MO_GlobalAddress, llvm::MachineOperand::MO_Immediate, llvm::MachineOperand::MO_JumpTableIndex, llvm::MachineOperand::MO_MachineBasicBlock, llvm::MachineOperand::MO_Register, llvm::Reloc::PIC_, llvm::AsmPrinter::PrintAsmOperand(), llvm::GlobalAlias::resolveAliasedGlobal(), S, llvm::MachO::S_SYMBOL_STUBS, llvm::ARMBuildAttrs::Section, llvm::MCInst::setOpcode(), llvm::Reloc::Static, llvm::SystemZISD::TM, llvm::MCSymbolRefExpr::VK_None, llvm::MCSymbolRefExpr::VK_PPC_DTPREL_HA, llvm::MCSymbolRefExpr::VK_PPC_DTPREL_LO, llvm::MCSymbolRefExpr::VK_PPC_GOT_TLSGD_HA, llvm::MCSymbolRefExpr::VK_PPC_GOT_TLSGD_LO, llvm::MCSymbolRefExpr::VK_PPC_GOT_TLSLD_HA, llvm::MCSymbolRefExpr::VK_PPC_GOT_TLSLD_LO, llvm::MCSymbolRefExpr::VK_PPC_GOT_TPREL_HA, llvm::MCSymbolRefExpr::VK_PPC_GOT_TPREL_LO, llvm::MCSymbolRefExpr::VK_PPC_TLSGD, llvm::MCSymbolRefExpr::VK_PPC_TLSLD, llvm::MCSymbolRefExpr::VK_PPC_TOC, llvm::MCSymbolRefExpr::VK_PPC_TOC_HA, llvm::MCSymbolRefExpr::VK_PPC_TOC_LO, and llvm::MCSymbolRefExpr::VK_PPC_TOCBASE.