LLVM: PPCBranchSelector.cpp File Reference
LLVM API Documentation
PPCBranchSelector.cpp File Reference
#include "PPC.h"
#include "MCTargetDesc/PPCPredicates.h"
#include "PPCInstrBuilder.h"
#include "PPCInstrInfo.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Target/TargetMachine.h"
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "ppc-branch-select"
Functions
STATISTIC (NumExpanded,"Number of branches expanded to long format")
void llvm::initializePPCBSelPass (PassRegistry &)
INITIALIZE_PASS (PPCBSel,"ppc-branch-select","PowerPC Branch Selector", false, false) FunctionPass *llvm
Macro Definition Documentation
#define DEBUG_TYPE "ppc-branch-select"
Definition at line 18 of file PPCBranchSelector.cpp.
Function Documentation
INITIALIZE_PASS (PPCBSel , "ppc-branch-select" , "PowerPC Branch Selector" , false , false)
createPPCBranchSelectionPass - returns an instance of the Branch Selection Pass
Definition at line 54 of file PPCBranchSelector.cpp.
References llvm::MachineInstrBuilder::addImm(), B, llvm::PPCISD::BDNZ, llvm::PPCISD::BDZ, llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::BuildMI(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getDebugLoc(), llvm::TargetMachine::getInstrInfo(), llvm::PPCInstrInfo::GetInstSizeInBytes(), llvm::MachineBasicBlock::getNumber(), llvm::MachineFunction::getNumBlockIDs(), llvm::MachineFunction::getTarget(), i, I, llvm::PPC::InvertPredicate(), llvm::isInt< 16 >(), llvm_unreachable, llvm::MachineFunction::RenumberBlocks(), and TII.
STATISTIC (NumExpanded , "Number of branches expanded to long format")