LLVM: PPCFastISel.cpp File Reference
LLVM API Documentation
PPCFastISel.cpp File Reference
#include "PPC.h"
#include "PPCISelLowering.h"
#include "PPCSubtarget.h"
#include "PPCTargetMachine.h"
#include "MCTargetDesc/PPCPredicates.h"
#include "llvm/ADT/Optional.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/FastISel.h"
#include "llvm/CodeGen/FunctionLoweringInfo.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Operator.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/GetElementPtrTypeIterator.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetMachine.h"
#include "PPCGenFastISel.inc"
#include "PPCGenCallingConv.inc"
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "ppcfastisel"
Functions
static Optional< PPC::Predicate > getComparePred (CmpInst::Predicate Pred)
Macro Definition Documentation
#define DEBUG_TYPE "ppcfastisel"
Definition at line 16 of file PPCFastISel.cpp.
Function Documentation
static Optional<PPC::Predicate> getComparePred (CmpInst::Predicate Pred) static
Definition at line 204 of file PPCFastISel.cpp.
References llvm::ISD::ADD, llvm::MachineInstrBuilder::addConstantPoolIndex(), llvm::MachineInstrBuilder::addFrameIndex(), llvm::MachineInstrBuilder::addGlobalAddress(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addMemOperand(), llvm::MachineInstrBuilder::addReg(), llvm::MachineInstrBuilder::addRegMask(), llvm::CCValAssign::AExt, Align, llvm::CCState::AnalyzeCallOperands(), llvm::CCState::AnalyzeCallResult(), llvm::CCState::AnalyzeReturn(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_begin(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_end(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_size(), llvm::CCValAssign::BCvt, llvm::BuildMI(), llvm::Attribute::ByVal, llvm::Call, CC, llvm::ISD::Constant, llvm::TargetOpcode::COPY, llvm::TargetOpcode::COPY_TO_REGCLASS, llvm::dyn_cast(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), llvm::MachineInstr::eraseFromParent(), F(), llvm::MVT::f32, llvm::MVT::f64, llvm::FastISel::FastEmitInst_r(), llvm::FastISel::FastEmitInst_ri(), llvm::FastISel::FastEmitInst_rr(), llvm::PPCISD::FCFID, llvm::PPCISD::FCFIDS, llvm::PPCISD::FCFIDU, llvm::PPCISD::FCFIDUS, llvm::CmpInst::FCMP_FALSE, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_TRUE, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, llvm::PPCISD::FCTIDUZ, llvm::PPCISD::FCTIDZ, llvm::PPCISD::FCTIWUZ, llvm::PPCISD::FCTIWZ, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::find(), llvm::CCValAssign::Full, llvm::gep_type_begin(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledValue(), llvm::CallInst::getCalledValue(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCallingConv(), llvm::BranchInst::getCondition(), llvm::MachinePointerInfo::getConstantPool(), llvm::StructLayout::getElementOffset(), llvm::SequentialType::getElementType(), llvm::MachinePointerInfo::getFixedStack(), llvm::MachineOperand::getImm(), llvm::generic_gep_type_iterator< ItTy >::getIndexedType(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::CCState::getNextStackOffset(), llvm::User::getNumOperands(), llvm::Instruction::getOpcode(), llvm::MachineInstr::getOpcode(), llvm::User::getOperand(), llvm::MachineInstr::getOperand(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MCRegisterInfo::getRegClass(), llvm::GetReturnInfo(), llvm::ConstantInt::getSExtValue(), llvm::APInt::getSExtValue(), llvm::ConstantInt::getSigned(), llvm::EVT::getSimpleVT(), llvm::MVT::getSizeInBits(), llvm::BranchInst::getSuccessor(), llvm::AllocaInst::getType(), llvm::Value::getType(), llvm::CCValAssign::getValNo(), llvm::Optional< T >::getValue(), llvm::CCValAssign::getValVT(), llvm::ConstantInt::getZExtValue(), llvm::APInt::getZExtValue(), llvm::GlobalValue::hasAvailableExternallyLinkage(), llvm::GlobalValue::hasCommonLinkage(), llvm::GlobalVariable::hasInitializer(), llvm::TargetRegisterClass::hasSuperClassEq(), llvm::HexagonISD::Hi, i, I, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::ARM_PROC::IE, llvm::RegState::Implicit, llvm::Attribute::InReg, int, llvm::PPC::InvertPredicate(), isAtomic(), llvm::isInt< 16 >(), llvm::isInt< 32 >(), llvm::CCValAssign::isRegLoc(), llvm::EVT::isSimple(), llvm::CallInst::isTailCall(), llvm::GlobalVariable::isThreadLocal(), llvm::isUInt< 16 >(), llvm::FunctionType::isVarArg(), llvm::MVT::isVector(), llvm::MVT::isVoid, llvm::Type::isVoidTy(), llvm::CodeModel::JITDefault, llvm::CodeModel::Large, llvm::A64DB::LD, llvm::PPCISD::LFIWAX, llvm::PPCISD::LFIWZX, llvm_unreachable, llvm::HexagonISD::Lo, llvm::SPII::Load, llvm::A64CC::MI, llvm::PPCII::MO_TOC_LO, llvm::MachineMemOperand::MOLoad, llvm::MachineMemOperand::MOStore, MRI, llvm::CCValAssign::needsCustom(), llvm::Attribute::Nest, llvm::User::op_begin(), llvm::User::op_end(), llvm::ISD::OR, OR, llvm::APIntOps::Or(), llvm::MVT::Other, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::paramHasAttr(), llvm::PPC::PRED_EQ, llvm::PPC::PRED_GE, llvm::PPC::PRED_GT, llvm::PPC::PRED_LE, llvm::PPC::PRED_LT, llvm::PPC::PRED_NE, llvm::PPC::PRED_NU, llvm::PPC::PRED_UN, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorImpl< T >::reserve(), llvm::AArch64ISD::Ret, S, llvm::ISD::ArgFlagsTy::setOrigAlign(), llvm::ISD::ArgFlagsTy::setSExt(), llvm::ISD::ArgFlagsTy::setZExt(), llvm::CCValAssign::SExt, llvm::Attribute::SExt, Shift, llvm::MVT::SimpleTy, llvm::SmallVectorTemplateCommon< T >::size(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::CodeModel::Small, llvm::SPII::Store, llvm::Attribute::StructRet, llvm::ISD::SUB, std::swap(), TII, llvm::SystemZISD::TM, llvm::CCValAssign::ZExt, and llvm::Attribute::ZExt.