LLVM: PPCISelDAGToDAG.cpp File Reference
LLVM API Documentation
PPCISelDAGToDAG.cpp File Reference
#include "PPC.h"
#include "MCTargetDesc/PPCPredicates.h"
#include "PPCTargetMachine.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetOptions.h"
#include "PPCGenDAGISel.inc"
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "ppc-codegen"
Functions
void llvm::initializePPCDAGToDAGISelPass (PassRegistry &)
static bool isIntS16Immediate (SDNode *N, short &Imm)
static bool isIntS16Immediate (SDValue Op, short &Imm)
static bool isInt32Immediate (SDNode *N, unsigned &Imm)
static bool isInt64Immediate (SDNode *N, uint64_t &Imm)
static bool isInt32Immediate (SDValue N, unsigned &Imm)
static bool isOpcWithIntImmediate (SDNode *N, unsigned Opc, unsigned &Imm)
static PPC::Predicate getPredicateForSetCC (ISD::CondCode CC)
static unsigned getCRIdxForSetCC (ISD::CondCode CC, bool &Invert)
static unsigned int getVCmpInst (MVT::SimpleValueType VecVT, ISD::CondCode CC)
static unsigned int getVCmpEQInst (MVT::SimpleValueType VecVT)
static void initializePassOnce (PassRegistry &Registry)
Macro Definition Documentation
#define DEBUG_TYPE "ppc-codegen"
Definition at line 15 of file PPCISelDAGToDAG.cpp.
Function Documentation
static unsigned getCRIdxForSetCC (ISD::CondCode CC, bool & Invert) static
getCRIdxForSetCC - Return the index of the condition register field associated with the SetCC condition, and whether or not the field is treated as inverted. That is, lt = 0; ge = 0 inverted.
Definition at line 600 of file PPCISelDAGToDAG.cpp.
References llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, and llvm::ISD::SETUO.
Referenced by getVCmpEQInst().
static PPC::Predicate getPredicateForSetCC (ISD::CondCode CC) static
Definition at line 569 of file PPCISelDAGToDAG.cpp.
References llvm_unreachable, llvm::PPC::PRED_EQ, llvm::PPC::PRED_GE, llvm::PPC::PRED_GT, llvm::PPC::PRED_LE, llvm::PPC::PRED_LT, llvm::PPC::PRED_NE, llvm::PPC::PRED_NU, llvm::PPC::PRED_UN, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETO, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, and llvm::ISD::SETUO.
Referenced by getVCmpEQInst().
static unsigned int getVCmpEQInst (MVT::SimpleValueType VecVT) static
Definition at line 695 of file PPCISelDAGToDAG.cpp.
References llvm::ISD::AND, AND, llvm::PPCISD::BDNZ, llvm::PPCISD::BDZ, llvm::ISD::BR_CC, llvm::ISD::BRIND, CC, llvm::PPCISD::COND_BRANCH, llvm::ISD::Constant, llvm::CountTrailingOnes_64(), llvm::dbgs(), DEBUG, llvm::SDNode::dump(), llvm::dyn_cast(), llvm::MVT::f32, llvm::MVT::f64, llvm::ISD::FrameIndex, G, llvm::LSBaseSDNode::getAddressingMode(), llvm::GlobalValue::getAlignment(), llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SDValue::getConstantOperandVal(), llvm::SDNode::getConstantOperandVal(), getCRIdxForSetCC(), llvm::LoadSDNode::getExtensionType(), llvm::SDValue::getMachineOpcode(), llvm::SDNode::getMachineOpcode(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::LoadSDNode::getOffset(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), getPredicateForSetCC(), llvm::EVT::getSimpleVT(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), getVCmpInst(), llvm::PPCISD::GlobalBaseReg, llvm::MVT::Glue, llvm::GlobalVariable::hasInitializer(), llvm::SDNode::hasOneUse(), llvm::HexagonISD::Hi, I, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::X86II::Imm64, llvm::MVT::isFloatingPoint(), isInt32Immediate(), isInt64Immediate(), llvm::isInt< 16 >(), llvm::isInt< 32 >(), llvm::SDValue::isMachineOpcode(), llvm::SDNode::isMachineOpcode(), llvm::isMask_64(), isOpcWithIntImmediate(), llvm::isPowerOf2_32(), isRunOfOnes(), llvm::EVT::isVector(), llvm::CodeModel::Large, llvm::A64DB::LD, llvm_unreachable, llvm::HexagonISD::Lo, llvm::ISD::LOAD, llvm::Log2_32(), llvm::CodeModel::Medium, llvm::PPCISD::MFOCRF, llvm::PPCII::MO_DTPREL_LO, llvm::PPCII::MO_TLSLD_LO, llvm::PPCII::MO_TOC_LO, llvm::PPCISD::MTCTR, N, llvm::CodeGenOpt::None, llvm::ISD::OR, llvm::MVT::Other, llvm::ISD::PRE_INC, llvm::GlobalAlias::resolveAliasedGlobal(), llvm::ISD::ROTL, llvm::ISD::SDIV, llvm::MCID::Select, llvm::ISD::SELECT_CC, llvm::ISD::SETCC, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::SDNode::setNodeId(), llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETONE, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, llvm::ISD::SEXTLOAD, Shift, llvm::ISD::SHL, llvm::MVT::SimpleTy, llvm::ISD::SRL, T, llvm::ISD::TargetConstant, llvm::ISD::TargetGlobalAddress, llvm::SystemZISD::TM, llvm::PPCISD::TOC_ENTRY, llvm::SDNode::use_empty(), llvm::MVT::v16i8, llvm::MVT::v4f32, llvm::MVT::v4i32, llvm::MVT::v8i16, llvm::PPCISD::VADD_SPLAT, and llvm::MipsISD::VNOR.
static unsigned int getVCmpInst (MVT::SimpleValueType VecVT, ISD::CondCode CC) static
Definition at line 632 of file PPCISelDAGToDAG.cpp.
References llvm_unreachable, llvm::ISD::SETEQ, llvm::ISD::SETGE, llvm::ISD::SETGT, llvm::ISD::SETLE, llvm::ISD::SETLT, llvm::ISD::SETNE, llvm::ISD::SETOEQ, llvm::ISD::SETOGE, llvm::ISD::SETOGT, llvm::ISD::SETOLE, llvm::ISD::SETOLT, llvm::ISD::SETUEQ, llvm::ISD::SETUGE, llvm::ISD::SETUGT, llvm::ISD::SETULE, llvm::ISD::SETULT, llvm::ISD::SETUNE, llvm::MVT::v16i8, llvm::MVT::v4f32, llvm::MVT::v4i32, and llvm::MVT::v8i16.
Referenced by getVCmpEQInst().
static void initializePassOnce (PassRegistry & Registry) static
Definition at line 1550 of file PPCISelDAGToDAG.cpp.
References llvm::SelectionDAGISel::ID, and llvm::PassRegistry::registerPass().
Referenced by llvm::initializePPCDAGToDAGISelPass().
static bool isInt32Immediate (SDNode * N, unsigned & Imm) static
isInt32Immediate - This method tests to see if the node is a 32-bit constant operand. If so Imm will receive the 32-bit value.
Definition at line 299 of file PPCISelDAGToDAG.cpp.
References llvm::ISD::Constant, llvm::SDNode::getOpcode(), llvm::SDNode::getValueType(), llvm::MVT::i32, and N.
Referenced by getVCmpEQInst(), isInt32Immediate(), and isOpcWithIntImmediate().
static bool isInt32Immediate (SDValue N, unsigned & Imm) static
Definition at line 319 of file PPCISelDAGToDAG.cpp.
References llvm::SDValue::getNode(), and isInt32Immediate().
static bool isInt64Immediate (SDNode * N, uint64_t & Imm) static
isInt64Immediate - This method tests to see if the node is a 64-bit constant operand. If so Imm will receive the 64-bit value.
Definition at line 309 of file PPCISelDAGToDAG.cpp.
References llvm::ISD::Constant, llvm::SDNode::getOpcode(), llvm::SDNode::getValueType(), llvm::MVT::i64, and N.
Referenced by getVCmpEQInst(), and isOpcWithIntImmediate().
static bool isIntS16Immediate (SDNode * N, short & Imm) static
isIntS16Immediate - This method tests to see if the node is either a 32-bit or 64-bit immediate, and if the value can be accurately represented as a sign extension from a 16-bit value. If so, this returns true and the immediate.
Definition at line 281 of file PPCISelDAGToDAG.cpp.
References llvm::ISD::Constant, llvm::SDNode::getOpcode(), llvm::SDNode::getValueType(), llvm::MVT::i32, and N.
Referenced by isIntS16Immediate(), and isOpcWithIntImmediate().
static bool isIntS16Immediate (SDValue Op, short & Imm) static
Definition at line 292 of file PPCISelDAGToDAG.cpp.
References llvm::SDValue::getNode(), and isIntS16Immediate().
static bool isOpcWithIntImmediate (SDNode * N, unsigned Opc, unsigned & Imm) static
Definition at line 327 of file PPCISelDAGToDAG.cpp.
References llvm::ISD::AND, CC, llvm::countLeadingZeros(), llvm::MVT::f32, llvm::MVT::f64, llvm::SDValue::getNode(), llvm::SDNode::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::APInt::getZExtValue(), llvm::MVT::i32, llvm::MVT::i64, isInt32Immediate(), isInt64Immediate(), llvm::isInt< 16 >(), isIntS16Immediate(), isRunOfOnes(), llvm::isShiftedMask_32(), llvm::isUInt< 16 >(), llvm::isUInt< 32 >(), llvm::ISD::isUnsignedIntSetCC(), N, llvm::ISD::ROTL, llvm::ISD::SETEQ, llvm::ISD::SETNE, Shift, llvm::ISD::SHL, llvm::ISD::SRL, std::swap(), and llvm::APIntOps::Xor().
Referenced by getVCmpEQInst().