LLVM: PPCInstrInfo.cpp File Reference
LLVM API Documentation
PPCInstrInfo.cpp File Reference
#include "PPCInstrInfo.h"
#include "MCTargetDesc/PPCPredicates.h"
#include "PPC.h"
#include "PPCHazardRecognizers.h"
#include "PPCInstrBuilder.h"
#include "PPCMachineFunctionInfo.h"
#include "PPCTargetMachine.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineMemOperand.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/PseudoSourceValue.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include "PPCGenInstrInfo.inc"
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define GET_INSTRMAP_INFO
#define GET_INSTRINFO_CTOR_DTOR
#define DEBUG_TYPE "ppc-early-ret"
Functions
static bool MBBDefinesCTR (MachineBasicBlock &MBB)
STATISTIC (NumBCLR,"Number of early conditional returns")
STATISTIC (NumBLR,"Number of early returns")
void llvm::initializePPCEarlyReturnPass (PassRegistry &)
Variables
static cl::opt< bool > DisableCTRLoopAnal ("disable-ppc-ctrloop-analysis", cl::Hidden, cl::desc("Disable analysis for CTR loops"))
static cl::opt< bool > DisableCmpOpt ("disable-ppc-cmp-opt", cl::desc("Disable compare instruction optimization"), cl::Hidden)
Macro Definition Documentation
#define DEBUG_TYPE "ppc-early-ret"
Definition at line 1386 of file PPCInstrInfo.cpp.
#define GET_INSTRINFO_CTOR_DTOR
Definition at line 36 of file PPCInstrInfo.cpp.
#define GET_INSTRMAP_INFO
Definition at line 35 of file PPCInstrInfo.cpp.
Function Documentation
static bool MBBDefinesCTR (MachineBasicBlock & MBB) static
Definition at line 881 of file PPCInstrInfo.cpp.
References llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::end(), I, and llvm::ARM_PROC::IE.
Referenced by llvm::PPCInstrInfo::isProfitableToIfCvt().
STATISTIC (NumBCLR , "Number of early conditional returns")
STATISTIC (NumBLR , "Number of early returns")
Variable Documentation
cl::opt<bool> DisableCmpOpt("disable-ppc-cmp-opt", cl::desc("Disable compare instruction optimization"), cl::Hidden) static
Referenced by llvm::PPCInstrInfo::optimizeCompareInstr().
cl:: opt<bool> DisableCTRLoopAnal("disable-ppc-ctrloop-analysis", cl::Hidden, cl::desc("Disable analysis for CTR loops")) static
Referenced by llvm::PPCInstrInfo::AnalyzeBranch().