LLVM: PPCMCExpr.cpp File Reference
LLVM API Documentation
PPCMCExpr.cpp File Reference
#include "PPCMCExpr.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCAsmInfo.h"
Macros
#define DEBUG_TYPE "ppcmcexpr"
Functions
static void AddValueSymbols_ (const MCExpr *Value, MCAssembler *Asm)
Macro Definition Documentation
#define DEBUG_TYPE "ppcmcexpr"
Definition at line 10 of file PPCMCExpr.cpp.
Function Documentation
static void AddValueSymbols_ (const MCExpr * Value, MCAssembler * Asm) static
Definition at line 128 of file PPCMCExpr.cpp.
References llvm::HexStyle::Asm, llvm::MCExpr::Binary, llvm::MCExpr::Constant, llvm::MCExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCAssembler::getOrCreateSymbolData(), llvm::MCBinaryExpr::getRHS(), llvm::PPCMCExpr::getSubExpr(), llvm_unreachable, llvm::MCExpr::SymbolRef, llvm::MCExpr::Target, and llvm::MCExpr::Unary.
Referenced by llvm::PPCMCExpr::AddValueSymbols().