LLVM: PPCMCTargetDesc.cpp File Reference
LLVM API Documentation
PPCMCTargetDesc.cpp File Reference
#include "PPCMCTargetDesc.h"
#include "InstPrinter/PPCInstPrinter.h"
#include "PPCMCAsmInfo.h"
#include "PPCTargetStreamer.h"
#include "llvm/MC/MCCodeGenInfo.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MachineLocation.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Support/TargetRegistry.h"
#include "PPCGenInstrInfo.inc"
#include "PPCGenSubtargetInfo.inc"
#include "PPCGenRegisterInfo.inc"
Macros
#define GET_INSTRINFO_MC_DESC
#define GET_SUBTARGETINFO_MC_DESC
#define GET_REGINFO_MC_DESC
Functions
static MCInstrInfo * createPPCMCInstrInfo ()
static MCRegisterInfo * createPPCMCRegisterInfo (StringRef TT)
static MCSubtargetInfo * createPPCMCSubtargetInfo (StringRef TT, StringRef CPU, StringRef FS)
static MCAsmInfo * createPPCMCAsmInfo (const MCRegisterInfo &MRI, StringRef TT)
static MCCodeGenInfo * createPPCMCCodeGenInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL)
static MCStreamer * createMCStreamer (const Target &T, StringRef TT, MCContext &Ctx, MCAsmBackend &MAB, raw_ostream &OS, MCCodeEmitter *Emitter, bool RelaxAll, bool NoExecStack)
static MCStreamer * createMCAsmStreamer (MCContext &Ctx, formatted_raw_ostream &OS, bool isVerboseAsm, bool useLoc, bool useCFI, bool useDwarfDirectory, MCInstPrinter *InstPrint, MCCodeEmitter *CE, MCAsmBackend *TAB, bool ShowInst)
static MCInstPrinter * createPPCMCInstPrinter (const Target &T, unsigned SyntaxVariant, const MCAsmInfo &MAI, const MCInstrInfo &MII, const MCRegisterInfo &MRI, const MCSubtargetInfo &STI)
void LLVMInitializePowerPCTargetMC ()
Macro Definition Documentation
#define GET_INSTRINFO_MC_DESC
Definition at line 29 of file PPCMCTargetDesc.cpp.
#define GET_REGINFO_MC_DESC
Definition at line 35 of file PPCMCTargetDesc.cpp.
#define GET_SUBTARGETINFO_MC_DESC
Definition at line 32 of file PPCMCTargetDesc.cpp.
Function Documentation
static MCStreamer* createMCAsmStreamer (MCContext & Ctx, formatted_raw_ostream & OS, bool isVerboseAsm, bool useLoc, bool useCFI, bool useDwarfDirectory, MCInstPrinter * InstPrint, MCCodeEmitter * CE, MCAsmBackend * TAB, bool ShowInst) static
Definition at line 148 of file PPCMCTargetDesc.cpp.
References llvm::createAsmStreamer(), and S.
static MCStreamer* createMCStreamer (const Target & T, StringRef TT, MCContext & Ctx, MCAsmBackend & MAB, raw_ostream & OS, MCCodeEmitter * Emitter, bool RelaxAll, bool NoExecStack) static
Definition at line 134 of file PPCMCTargetDesc.cpp.
References llvm::createELFStreamer(), llvm::createMachOStreamer(), and S.
Referenced by LLVMInitializePowerPCTargetMC().
static MCAsmInfo* createPPCMCAsmInfo (const MCRegisterInfo & MRI, StringRef TT) static
Definition at line 68 of file PPCMCTargetDesc.cpp.
References llvm::MCAsmInfo::addInitialFrameState(), llvm::MCCFIInstruction::createDefCfa(), llvm::Triple::getArch(), llvm::MCRegisterInfo::getDwarfRegNum(), llvm::Triple::isOSDarwin(), llvm::Triple::ppc64, and llvm::Triple::ppc64le.
Referenced by LLVMInitializePowerPCTargetMC().
static MCCodeGenInfo* createPPCMCCodeGenInfo (StringRef TT, Reloc::Model RM, CodeModel::Model CM, CodeGenOpt::Level OL) static
Definition at line 88 of file PPCMCTargetDesc.cpp.
References llvm::Reloc::Default, llvm::CodeModel::Default, llvm::Reloc::DynamicNoPIC, llvm::MCStreamer::EmitSymbolValue(), llvm::PPCTargetStreamer::emitTCEntry(), llvm::Triple::getArch(), llvm::MCSymbol::getName(), llvm::MCCodeGenInfo::InitMCCodeGenInfo(), llvm::Triple::isOSDarwin(), llvm::CodeModel::Medium, llvm::Triple::ppc64, llvm::Triple::ppc64le, S, llvm::Reloc::Static, llvm::MCTargetStreamer::Streamer, T, and llvm::X.
Referenced by LLVMInitializePowerPCTargetMC().
static MCInstPrinter* createPPCMCInstPrinter (const Target & T, unsigned SyntaxVariant, const MCAsmInfo & MAI, const MCInstrInfo & MII, const MCRegisterInfo & MRI, const MCSubtargetInfo & STI) static
Definition at line 159 of file PPCMCTargetDesc.cpp.
References llvm::MCSubtargetInfo::getTargetTriple().
Referenced by LLVMInitializePowerPCTargetMC().
static MCInstrInfo* createPPCMCInstrInfo () static
Definition at line 43 of file PPCMCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializePowerPCTargetMC().
static MCRegisterInfo* createPPCMCRegisterInfo (StringRef TT) static
Definition at line 49 of file PPCMCTargetDesc.cpp.
References llvm::Triple::getArch(), llvm::Triple::ppc64, llvm::Triple::ppc64le, and llvm::X.
Referenced by LLVMInitializePowerPCTargetMC().
static MCSubtargetInfo* createPPCMCSubtargetInfo (StringRef TT, StringRef CPU, StringRef FS) static
Definition at line 61 of file PPCMCTargetDesc.cpp.
References llvm::X.
Referenced by LLVMInitializePowerPCTargetMC().
void LLVMInitializePowerPCTargetMC ()
Definition at line 169 of file PPCMCTargetDesc.cpp.
References llvm::createMCAsmStreamer(), createMCStreamer(), llvm::createPPCAsmBackend(), createPPCMCAsmInfo(), llvm::createPPCMCCodeEmitter(), createPPCMCCodeGenInfo(), createPPCMCInstPrinter(), createPPCMCInstrInfo(), createPPCMCRegisterInfo(), createPPCMCSubtargetInfo(), llvm::TargetRegistry::RegisterAsmStreamer(), llvm::TargetRegistry::RegisterMCAsmBackend(), llvm::TargetRegistry::RegisterMCCodeEmitter(), llvm::TargetRegistry::RegisterMCCodeGenInfo(), llvm::TargetRegistry::RegisterMCInstPrinter(), llvm::TargetRegistry::RegisterMCInstrInfo(), llvm::TargetRegistry::RegisterMCObjectStreamer(), llvm::TargetRegistry::RegisterMCRegInfo(), llvm::TargetRegistry::RegisterMCSubtargetInfo(), llvm::ThePPC32Target, llvm::ThePPC64LETarget, and llvm::ThePPC64Target.