LLVM: PPCSubtarget.cpp File Reference
LLVM API Documentation
PPCSubtarget.cpp File Reference
#include "PPCSubtarget.h"
#include "PPC.h"
#include "PPCRegisterInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineScheduler.h"
#include "llvm/IR/Attributes.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/Host.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Target/TargetMachine.h"
#include <cstdlib>
#include "PPCGenSubtargetInfo.inc"
Macros
#define GET_SUBTARGETINFO_TARGET_DESC
#define GET_SUBTARGETINFO_CTOR
Functions
static bool needsAggressiveScheduling (unsigned Directive)
Macro Definition Documentation
#define GET_SUBTARGETINFO_CTOR
Definition at line 28 of file PPCSubtarget.cpp.
#define GET_SUBTARGETINFO_TARGET_DESC
Definition at line 27 of file PPCSubtarget.cpp.
Function Documentation
static bool needsAggressiveScheduling (unsigned Directive) static
Definition at line 183 of file PPCSubtarget.cpp.
References llvm::PPC::DIR_440, llvm::PPC::DIR_A2, llvm::PPC::DIR_E500mc, and llvm::PPC::DIR_E5500.
Referenced by llvm::PPCSubtarget::enableMachineScheduler(), llvm::PPCSubtarget::overrideSchedPolicy(), and llvm::PPCSubtarget::useAA().