LLVM: PrologEpilogInserter.cpp File Reference
LLVM API Documentation
PrologEpilogInserter.cpp File Reference
#include "PrologEpilogInserter.h"
#include "llvm/ADT/IndexedMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetFrameLowering.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include <climits>
Macros
#define DEBUG_TYPE "pei"
Functions
INITIALIZE_PASS_BEGIN (PEI,"prologepilog","Prologue/Epilogue Insertion", false, false) INITIALIZE_PASS_END(PEI
Prologue Epilogue Insertion &Frame false STATISTIC (NumScavengedRegs,"Number of frame index regs scavenged")
STATISTIC (NumBytesStackSpace,"Number of bytes used for stack in all functions")
static void AdjustStackOffset (MachineFrameInfo *MFI, int FrameIdx, bool StackGrowsDown, int64_t &Offset, unsigned &MaxAlign)
AdjustStackOffset - Helper function used to adjust the stack frame offset.
Variables
static cl::opt< unsigned > WarnStackSize ("warn-stack-size", cl::Hidden, cl::init((unsigned)-1), cl::desc("Warn for stack size bigger than the given"" number"))
prologepilog
Prologue Epilogue Insertion &Frame Finalization
Prologue Epilogue Insertion &Frame false
Macro Definition Documentation
#define DEBUG_TYPE "pei"
Definition at line 19 of file PrologEpilogInserter.cpp.
Function Documentation
static void AdjustStackOffset (MachineFrameInfo * MFI, int FrameIdx, bool StackGrowsDown, int64_t & Offset, unsigned & MaxAlign) inline static
AdjustStackOffset - Helper function used to adjust the stack frame offset.
Definition at line 386 of file PrologEpilogInserter.cpp.
References llvm::TargetFrameLowering::adjustForHiPEPrologue(), llvm::TargetFrameLowering::adjustForSegmentedStacks(), llvm::MachineFrameInfo::adjustsStack(), Align, BB, llvm::SmallVectorTemplateCommon< T >::begin(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::MachineOperand::ChangeToRegister(), llvm::SmallSet< T, N, C >::count(), llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::dbgs(), DEBUG, llvm::df_ext_begin(), llvm::df_ext_end(), llvm::TargetFrameLowering::eliminateCallFramePseudoInstr(), llvm::TargetRegisterInfo::eliminateFrameIndex(), llvm::TargetFrameLowering::emitEpilogue(), llvm::TargetFrameLowering::emitPrologue(), llvm::TargetOptions::EnableSegmentedStacks, llvm::SmallVectorTemplateCommon< T >::end(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::RegScavenger::enterBasicBlock(), llvm::RegScavenger::forward(), llvm::Function::getCallingConv(), llvm::RegScavenger::getCurrentPosition(), llvm::TargetFrameLowering::getFrameIndexReference(), llvm::MachineFunction::getFrameInfo(), llvm::TargetMachine::getFrameLowering(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::TargetMachine::getInstrInfo(), llvm::MachineFrameInfo::getLocalFrameMaxAlign(), llvm::MachineFrameInfo::getLocalFrameObjectCount(), llvm::MachineFrameInfo::getLocalFrameObjectMap(), llvm::MachineFrameInfo::getLocalFrameSize(), llvm::MachineFrameInfo::getMaxAlignment(), llvm::MachineFrameInfo::getMaxCallFrameSize(), llvm::MachineBasicBlock::getNumber(), llvm::MachineFunction::getNumBlockIDs(), llvm::MachineInstr::getNumOperands(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectIndexBegin(), llvm::MachineFrameInfo::getObjectIndexEnd(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineFrameInfo::getObjectSize(), llvm::TargetFrameLowering::getOffsetOfLocalArea(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::TargetMachine::getRegisterInfo(), llvm::RegScavenger::getScavengingFrameIndices(), llvm::TargetFrameLowering::getStackAlignment(), llvm::TargetFrameLowering::getStackGrowthDirection(), llvm::MachineFrameInfo::getStackProtectorIndex(), llvm::MachineFunction::getTarget(), llvm::TargetFrameLowering::getTransientStackAlignment(), llvm::MachineFrameInfo::getUseLocalStackAllocationBlock(), llvm::TargetFrameLowering::hasFP(), llvm::TargetFrameLowering::hasReservedCallFrame(), llvm::MachineFrameInfo::hasStackObjects(), llvm::MachineFrameInfo::hasVarSizedObjects(), llvm::CallingConv::HiPE, i, I, llvm::ARM_PROC::IE, llvm::SmallSet< T, N, C >::insert(), int, llvm::MachineFrameInfo::isDeadObjectIndex(), llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isFI(), llvm::TargetFrameLowering::isFPCloseToIncomingSP(), llvm::MachineFrameInfo::isObjectPreAllocated(), llvm::MachineOperand::isReg(), llvm::RegScavenger::isScavengingFrameIndex(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::MachineFrameInfo::MayNeedStackProtector(), llvm::A64CC::MI, llvm::TargetRegisterInfo::needsStackRealignment(), llvm::next(), llvm::TargetMachine::Options, P, llvm::prior(), llvm::MachineRegisterInfo::replaceRegWith(), llvm::SmallVectorImpl< T >::resize(), llvm::RegScavenger::scavengeRegister(), llvm::MachineOperand::setImm(), llvm::MachineFrameInfo::setObjectOffset(), llvm::MachineFrameInfo::setStackSize(), llvm::RegScavenger::setUsed(), llvm::MachineBasicBlock::splice(), llvm::TargetFrameLowering::StackGrowsDown, llvm::TargetFrameLowering::targetHandlesStackFrameRounding(), TII, llvm::SystemZISD::TM, llvm::RegScavenger::unprocess(), and llvm::TargetRegisterInfo::useFPForScavengingIndex().
Referenced by INITIALIZE_PASS().
INITIALIZE_PASS_BEGIN (PEI , "prologepilog" , "Prologue/Epilogue Insertion" , false , false)
Prologue Epilogue Insertion& Frame false STATISTIC (NumScavengedRegs , "Number of frame index regs scavenged")
STATISTIC (NumBytesStackSpace , "Number of bytes used for stack in all functions")
Variable Documentation
Prologue Epilogue Insertion& Frame false
Definition at line 58 of file PrologEpilogInserter.cpp.
Prologue Epilogue Insertion& Frame Finalization
Definition at line 58 of file PrologEpilogInserter.cpp.
prologepilog
Definition at line 58 of file PrologEpilogInserter.cpp.
cl::opt<unsigned> WarnStackSize("warn-stack-size", cl::Hidden, cl::init((unsigned)-1), cl::desc("Warn for stack size bigger than the given"" number")) static
Referenced by llvm::PEI::runOnMachineFunction().