LLVM: PromoteMemoryToRegister.cpp File Reference
LLVM API Documentation
PromoteMemoryToRegister.cpp File Reference
#include "llvm/Transforms/Utils/PromoteMemToReg.h"
#include "llvm/ADT/ArrayRef.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasSetTracker.h"
#include "llvm/Analysis/Dominators.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/DIBuilder.h"
#include "llvm/DebugInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Metadata.h"
#include "llvm/Support/CFG.h"
#include "llvm/Transforms/Utils/Local.h"
#include <algorithm>
#include <queue>
Macros
#define DEBUG_TYPE "mem2reg"
Functions
STATISTIC (NumLocalPromoted,"Number of alloca's promoted within one block")
STATISTIC (NumSingleStore,"Number of alloca's promoted with a single store")
STATISTIC (NumDeadAlloca,"Number of dead alloca's removed")
STATISTIC (NumPHIInsert,"Number of PHI nodes inserted")
static void removeLifetimeIntrinsicUsers (AllocaInst *AI)
static bool rewriteSingleStoreAlloca (AllocaInst *AI, AllocaInfo &Info, LargeBlockInfo &LBI, DominatorTree &DT, AliasSetTracker *AST)
Rewrite as many loads as possible given a single store.
static void promoteSingleBlockAlloca (AllocaInst *AI, const AllocaInfo &Info, LargeBlockInfo &LBI, AliasSetTracker *AST)
Macro Definition Documentation
#define DEBUG_TYPE "mem2reg"
Definition at line 28 of file PromoteMemoryToRegister.cpp.
Function Documentation
static void promoteSingleBlockAlloca (AllocaInst * AI, const AllocaInfo & Info, LargeBlockInfo & LBI, AliasSetTracker * AST) static
Many allocas are only used within a single basic block. If this is the case, avoid traversing the CFG and inserting a lot of potentially useless PHI nodes by just performing a single linear pass over the basic block using the Alloca.
If we cannot promote this alloca (because it is read before it is written), return true. This is necessary in cases where, due to control flow, the alloca is potentially undefined on some control flow paths. e.g. code like this is potentially correct:
for (...) { if (c) { A = undef; undef = B; } }
... so long as A is not used before undef is set.
Definition at line 447 of file PromoteMemoryToRegister.cpp.
References llvm::ARM_PROC::A, llvm::PHINode::addIncoming(), BB, llvm::DomTreeNodeBase< NodeT >::begin(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::BasicBlock::begin(), llvm::SmallPtrSet< PtrType, SmallSize >::begin(), llvm::Function::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::ConvertDebugDeclareToDebugValue(), llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::PHINode::Create(), llvm::AliasSetTracker::deleteValue(), llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), llvm::DomTreeNodeBase< NodeT >::end(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::SmallPtrSet< PtrType, SmallSize >::end(), llvm::Function::end(), llvm::iplist< NodeTy, Traits >::erase(), llvm::SmallVectorImpl< T >::erase(), llvm::Instruction::eraseFromParent(), F(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::find(), llvm::BasicBlock::front(), llvm::UndefValue::get(), llvm::DomTreeNodeBase< NodeT >::getBlock(), llvm::DomTreeNodeBase< NodeT >::getIDom(), llvm::PHINode::getIncomingBlock(), llvm::BasicBlock::getInstList(), llvm::Intrinsic::getName(), llvm::PHINode::getNumIncomingValues(), llvm::User::getNumOperands(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Value::getType(), i, I, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::isAllocaPromotable(), llvm::Type::isPointerTy(), P, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::pred_begin(), llvm::pred_end(), llvm::prior(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), removeLifetimeIntrinsicUsers(), llvm::Value::replaceAllUsesWith(), rewriteSingleStoreAlloca(), llvm::SimplifyInstruction(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::succ_begin(), llvm::succ_end(), llvm::Instruction::use_back(), llvm::Value::use_begin(), llvm::Value::use_empty(), and llvm::Value::use_end().
static void removeLifetimeIntrinsicUsers (AllocaInst * AI) static
Definition at line 316 of file PromoteMemoryToRegister.cpp.
References llvm::Instruction::eraseFromParent(), llvm::Value::getType(), I, llvm::Type::isVoidTy(), llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by promoteSingleBlockAlloca().
static bool rewriteSingleStoreAlloca (AllocaInst * AI, AllocaInfo & Info, LargeBlockInfo & LBI, DominatorTree & DT, AliasSetTracker * AST) static
Rewrite as many loads as possible given a single store.
When there is only a single store, we can use the domtree to trivially replace all of the dominated loads with the stored value. Do so, and return true if this has successfully promoted the alloca entirely. If this returns false there were some loads which were not dominated by the single store and thus must be phi-ed with undef. We fall back to the standard alloca promotion algorithm in that case.
Definition at line 350 of file PromoteMemoryToRegister.cpp.
References llvm::ConvertDebugDeclareToDebugValue(), llvm::AliasSetTracker::deleteValue(), llvm::DominatorTree::dominates(), llvm::Instruction::eraseFromParent(), llvm::UndefValue::get(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::Value::getType(), llvm::Type::isPointerTy(), llvm::Value::replaceAllUsesWith(), llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by promoteSingleBlockAlloca().
STATISTIC (NumLocalPromoted , "Number of alloca's promoted within one block")
STATISTIC (NumSingleStore , "Number of alloca's promoted with a single store")
STATISTIC (NumDeadAlloca , "Number of dead alloca's removed")
STATISTIC (NumPHIInsert , "Number of PHI nodes inserted")