LLVM: R600ISelLowering.cpp File Reference
LLVM API Documentation
R600ISelLowering.cpp File Reference
Custom DAG lowering for R600.
#include "R600ISelLowering.h"
#include "R600Defines.h"
#include "R600InstrInfo.h"
#include "R600MachineFunctionInfo.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/IR/Argument.h"
#include "llvm/IR/Function.h"
Functions
static int ConstantAddressBlock (unsigned AddressSpace)
static SDValue CompactSwizzlableVector (SelectionDAG &DAG, SDValue VectorEntry, DenseMap< unsigned, unsigned > &RemapSwizzle)
static SDValue ReorganizeVector (SelectionDAG &DAG, SDValue VectorEntry, DenseMap< unsigned, unsigned > &RemapSwizzle)
static bool FoldOperand (SDNode *ParentNode, unsigned SrcIdx, SDValue &Src, SDValue &Neg, SDValue &Abs, SDValue &Sel, SDValue &Imm, SelectionDAG &DAG)
Detailed Description
Custom DAG lowering for R600.
Definition in file R600ISelLowering.cpp.
Function Documentation
static SDValue CompactSwizzlableVector (SelectionDAG & DAG, SDValue VectorEntry, DenseMap< unsigned, unsigned > & RemapSwizzle) static
Definition at line 1392 of file R600ISelLowering.cpp.
References llvm::ISD::BUILD_VECTOR, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::empty(), llvm::MVT::f32, llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::TargetLoweringBase::getValueType(), i, j(), and llvm::ISD::UNDEF.
Referenced by ReorganizeVector().
static int ConstantAddressBlock (unsigned AddressSpace) static
Definition at line 1159 of file R600ISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::BUILD_VECTOR, llvm::AMDGPUISD::CONST_ADDRESS, AMDGPUAS::CONSTANT_BUFFER_0, AMDGPUAS::CONSTANT_BUFFER_1, AMDGPUAS::CONSTANT_BUFFER_10, AMDGPUAS::CONSTANT_BUFFER_11, AMDGPUAS::CONSTANT_BUFFER_12, AMDGPUAS::CONSTANT_BUFFER_13, AMDGPUAS::CONSTANT_BUFFER_14, AMDGPUAS::CONSTANT_BUFFER_15, AMDGPUAS::CONSTANT_BUFFER_2, AMDGPUAS::CONSTANT_BUFFER_3, AMDGPUAS::CONSTANT_BUFFER_4, AMDGPUAS::CONSTANT_BUFFER_5, AMDGPUAS::CONSTANT_BUFFER_6, AMDGPUAS::CONSTANT_BUFFER_7, AMDGPUAS::CONSTANT_BUFFER_8, AMDGPUAS::CONSTANT_BUFFER_9, llvm::ISD::EXTLOAD, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MemSDNode::getAddressSpace(), llvm::MemSDNode::getAlignment(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::LoadSDNode::getExtensionType(), llvm::SelectionDAG::getExtLoad(), llvm::TargetMachine::getFrameLowering(), llvm::SelectionDAG::getMachineFunction(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getMergeValues(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOperand(), llvm::MemSDNode::getPointerInfo(), llvm::EVT::getSizeInBits(), llvm::MemSDNode::getSrcValue(), llvm::AMDGPUFrameLowering::getStackWidth(), llvm::SelectionDAG::getTargetConstant(), llvm::TargetLoweringBase::getTargetMachine(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::EVT::getVectorNumElements(), llvm::EVT::getVectorVT(), i, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::MemSDNode::isNonTemporal(), llvm::EVT::isVector(), llvm::MemSDNode::isVolatile(), AMDGPUAS::LOCAL_ADDRESS, llvm::ISD::NON_EXTLOAD, AMDGPUAS::PRIVATE_ADDRESS, llvm::AMDGPUISD::REGISTER_LOAD, llvm::ISD::SEXTLOAD, llvm::ISD::SHL, llvm::AMDGPUTargetLowering::SplitVectorLoad(), llvm::ISD::SRA, llvm::ISD::SRL, llvm::MVT::v4i32, and llvm::ISD::ZEXTLOAD.
static bool FoldOperand (SDNode * ParentNode, unsigned SrcIdx, SDValue & Src, SDValue & Neg, SDValue & Abs, SDValue & Sel, SDValue & Imm, SelectionDAG & DAG) static
Definition at line 1714 of file R600ISelLowering.cpp.
References llvm::Abs, llvm::APFloat::bitcastToAPInt(), llvm::APFloat::convertToFloat(), llvm::dyn_cast(), llvm::MVT::f32, llvm::R600InstrInfo::fitsConstReadLimitations(), llvm::TargetMachine::getInstrInfo(), llvm::SelectionDAG::getMachineNode(), llvm::SDValue::getMachineOpcode(), llvm::SDNode::getMachineOpcode(), llvm::SDValue::getNode(), llvm::SDValue::getNumOperands(), llvm::SDNode::getNumOperands(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::R600InstrInfo::getOperandIdx(), llvm::SelectionDAG::getRegister(), llvm::R600InstrInfo::getSelIdx(), llvm::SelectionDAG::getTarget(), llvm::SelectionDAG::getTargetConstant(), llvm::ConstantFPSDNode::getValueAPF(), llvm::SDNode::getValueType(), llvm::SDNode::getVTList(), llvm::ConstantSDNode::getZExtValue(), llvm::APInt::getZExtValue(), llvm::R600InstrInfo::hasInstrModifiers(), i, I, llvm::MVT::i32, llvm::SDValue::isMachineOpcode(), llvm::SDNode::isMachineOpcode(), llvm::EVT::isVector(), llvm::SDNode::op_begin(), llvm::SDNode::op_end(), llvm::TargetOpcode::REG_SEQUENCE, and TII.
static SDValue ReorganizeVector (SelectionDAG & DAG, SDValue VectorEntry, DenseMap< unsigned, unsigned > & RemapSwizzle) static
Definition at line 1434 of file R600ISelLowering.cpp.
References llvm::ISD::BUILD_VECTOR, CompactSwizzlableVector(), llvm::dyn_cast(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::empty(), llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getValueType(), i, llvm::MVT::i32, and std::swap().