LLVM: README_ALTIVEC.txt File Reference
LLVM API Documentation
README_ALTIVEC.txt File Reference
#include <string.h>
#include <altivec.h>
Typedefs
using C = (vector float) vec_cmpeq(*A,*B)
Functions
Implement PPCInstrInfo::isLoadFromStackSlot isStoreToStackSlot for vector to generate better spill code The first should be a single lvx from the constant the second should be a xor bar (x)
void foo (void)
if (!vec_any_eq(*A,*B))*B
float space text globl _test align oris r3 lis ha16 (LCPI1_0) addi r4
float space text globl _test align oris r3 lis stfs r1 addi lfs lo16() LCPI1_0 (r3) stfs f0
float space text globl _test align oris r3 lis stfs r1 addi lfs lo16() r1 lvx r4 lvx r5 vmrghw v2 vspltw vmrghw v3 r2 blr int foo (vector float *x, vector float *y)
if (vec_all_ge(a, b)) aa|=0x1
if (vec_any_ge(a, b)) aa|=0x2
vector float f (vector float a, vector float b)
Variables
Implement PPCInstrInfo::isLoadFromStackSlot isStoreToStackSlot for vector registers
Implement PPCInstrInfo::isLoadFromStackSlot isStoreToStackSlot for vector to generate better spill code The first should be a single lvx from the constant pool
Implement PPCInstrInfo::isLoadFromStackSlot isStoreToStackSlot for vector to generate better spill code The first should be a single lvx from the constant the second should be a xor stvx
Altivec __pad1__
Altivec not
Altivec we can use Consider this
v4f32 Vector2 = { Vector.X, Vector.X, Vector.X, Vector.X }
Since we know that Vector is byte aligned and we know the element offset of X
Since we know that Vector is byte aligned and we know the element offset of we should change the load into a lve *x instruction
Since we know that Vector is byte aligned and we know the element offset of we should change the load into a lve *x instead of doing a load store lve *x sequence For functions that use altivec AND have calls
Since we know that Vector is byte aligned and we know the element offset of we should change the load into a lve *x instead of doing a load store lve *x sequence For functions that use altivec AND have we are VRSAVE ing all call clobbered regs Implement passing vectors by value into calls and receiving them as arguments GCC apparently tries to codegen
Since we know that Vector is byte aligned and we know the element offset of we should change the load into a lve *x instead of doing a load store lve *x sequence For functions that use altivec AND have we are VRSAVE ing all call clobbered regs Implement passing vectors by value into calls and receiving them as arguments GCC apparently tries to then a load and vperm of Variable We need a way to teach tblgen that some operands of an intrinsic are required to be constants The verifier should enforce this constraint We currently codegen SCALAR_TO_VECTOR as a store of the scalar to a byte aligned stack slot
Since we know that Vector is byte aligned and we know the element offset of we should change the load into a lve *x instead of doing a load store lve *x sequence For functions that use altivec AND have we are VRSAVE ing all call clobbered regs Implement passing vectors by value into calls and receiving them as arguments GCC apparently tries to then a load and vperm of Variable We need a way to teach tblgen that some operands of an intrinsic are required to be constants The verifier should enforce this constraint We currently codegen SCALAR_TO_VECTOR as a store of the scalar to a byte aligned stack followed by a load vperm We should probably just store it to a scalar stack then use lvsl vperm to load it If the value is already in memory this is a big win extract_vector_elt of an arbitrary constant vector can be done with the following instructions
Since we know that Vector is byte aligned and we know the element offset of we should change the load into a lve *x instead of doing a load store lve *x sequence For functions that use altivec AND have we are VRSAVE ing all call clobbered regs Implement passing vectors by value into calls and receiving them as arguments GCC apparently tries to then a load and vperm of Variable We need a way to teach tblgen that some operands of an intrinsic are required to be constants The verifier should enforce this constraint We currently codegen SCALAR_TO_VECTOR as a store of the scalar to a byte aligned stack followed by a load vperm We should probably just store it to a scalar stack then use lvsl vperm to load it If the value is already in memory this is a big win extract_vector_elt of an arbitrary constant vector can be done with the following vec_ste & destloc
* A = C
we get the following basic block
we get the following basic r4 lvx v3
we get the following basic r4 lvx r3 vcmpeqfp v4
we get the following basic r4 lvx r3 vcmpeqfp v2 vcmpeqfp v2
we get the following basic r4 lvx r3 vcmpeqfp v2 vcmpeqfp v2 bne cr6
we get the following basic r4 lvx r3 vcmpeqfp v2 vcmpeqfp v2 bne LBB1_2
cond_next The vcmpeqfp vcmpeqfp instructions currently cannot be merged when the vcmpeqfp result is used by a branch This can be improved The code generated for this is truly aweful
cond_next The vcmpeqfp vcmpeqfp instructions currently cannot be merged when the vcmpeqfp result is used by a branch This can be improved The code generated for this is truly float b
LCPI1_0 __pad2__
float space text globl _test align _test
float space text globl _test align oris r3
float space text globl _test align oris r2
float space text globl _test align oris mtspr
float space text globl _test align oris r3 lis r1
float space text globl _test align oris r3 lis stfs f1
float space text globl _test align oris r3 lis stfs r1 addi r5
float space text globl _test align oris r3 lis stfs r1 addi lfs f0
A predicate compare being used in a select_cc should have the same peephole applied to it as a predicate compare used by a br_cc There should be no mfcr here
A predicate compare being used in a select_cc should have the same peephole applied to it as a predicate compare used by a br_cc There should be no mfcr oris r5 li li r6
A predicate compare being used in a select_cc should have the same peephole applied to it as a predicate compare used by a br_cc There should be no mfcr oris r5 li li lvx r4 lvx r3 vcmpeqfp v2 mfcr rlwinm cmpwi cr0
entry LBB1_1
entry mr r6 r2 blr CodeGen PowerPC vec_constants ll has an and operation that should be codegen d to andc The issue is that the all ones build vector is SelectNodeTo d a VSPLTISB instruction node before the and xor is selected which prevents the vnot pattern from matching An alternative to the store store load approach for illegal insert element lowering would be
splat index
vcmpeq to generate a select mask lvsl slot x
vperm to rotate result into correct slot vsel result together Should codegen branches on vec_any vec_all to avoid mfcr Two examples
return aa
Typedef Documentation
using C = (vector float)vec_cmpeq(*A, *B)
Definition at line 91 of file README_ALTIVEC.txt.
Function Documentation
Implement PPCInstrInfo::isLoadFromStackSlot isStoreToStackSlot for vector to generate better spill code The first should be a single lvx from the constant the second should be a xor bar (x)
Referenced by foo().
vector float f (vector float a, vector float b)
Definition at line 205 of file README_ALTIVEC.txt.
Referenced by accumulateAndSortLibcalls(), CollectSubexprs(), llvm::createGreedyRegisterAllocator(), llvm::createHexagonHardwareLoops(), llvm::NVPTXAsmPrinter::doFinalization(), expandPow(), llvm::IntervalMap< SlotIndex, unsigned >::find(), llvm::FloatToBits(), llvm::ScalarEvolution::getAddExpr(), LTOModule::getAsmUndefinedRefs(), getBuildPairElt(), llvm::LLParser::getContext(), llvm::GetReturnInfo(), llvm::SelectionDAGBuilder::getValueImpl(), isDeclaration(), llvm::lintFunction(), lookupCandidateBaseReg(), LTOModule::makeLTOModule(), llvm::MachineJumpTableInfo::print(), llvm::AMDGPUInstPrinter::printInst(), llvm::MachineFunction::removeFromMBBNumbering(), llvm::R600TargetLowering::ReplaceNodeResults(), llvm::X86TargetLowering::resetOperationActions(), llvm::tie(), llvm::ImutAVLTree< ImutInfo >::validateTree(), llvm::verifyFunction(), and llvm::InstCombiner::visitLandingPadInst().
void foo (void)
Definition at line 17 of file README_ALTIVEC.txt.
References llvm::support::aligned, bar(), and llvm::Intrinsic::memset.
float space text globl _test align oris r3 lis stfs r1 addi lfs lo16() r1 lvx r4 lvx r5 vmrghw v2 vspltw vmrghw v3 r2 blr int foo (vector float * x, vector float * y)
Definition at line 142 of file README_ALTIVEC.txt.
References _foo, as, be, here, it, to, and used.
float space text globl _test align oris r3 lis ha16 (LCPI1_0)
if (!vec_any_eq *,* B)
if (vec_all_ge(a, b)) pure virtual
if (vec_any_ge(a, b)) pure virtual
float space text globl _test align oris r3 lis stfs r1 addi lfs lo16() LCPI1_0 (r3)
Variable Documentation
Altivec __pad1__
Definition at line 25 of file README_ALTIVEC.txt.
LCPI1_0 __pad2__
Definition at line 117 of file README_ALTIVEC.txt.
float space text globl _test align _test
Definition at line 123 of file README_ALTIVEC.txt.
* A = C
Definition at line 94 of file README_ALTIVEC.txt.
return aa
Definition at line 202 of file README_ALTIVEC.txt.
cond_next The vcmpeqfp vcmpeqfp instructions currently cannot be merged when the vcmpeqfp result is used by a branch This can be improved The code generated for this is truly aweful
Definition at line 113 of file README_ALTIVEC.txt.
vperm to rotate result into correct slot vsel result together Should codegen branches on vec_any vec_all to avoid mfcr Two vector float b
Initial value:
{
 return (vector float){ 0.0, a, 0.0, 0.0}
Definition at line 113 of file README_ALTIVEC.txt.
entry mr r6 r2 blr CodeGen PowerPC vec_constants ll has an and operation that should be codegen d to andc The issue is that the all ones build vector is SelectNodeTo d a VSPLTISB instruction node before the and xor is selected which prevents the vnot pattern from matching An alternative to the store store load approach for illegal insert element lowering would be
Definition at line 167 of file README_ALTIVEC.txt.
Referenced by foo().
we get the following basic block
Definition at line 100 of file README_ALTIVEC.txt.
Since we know that Vector is byte aligned and we know the element offset of we should change the load into a lve* x instead of doing a load store lve* x sequence For functions that use altivec AND have calls
Definition at line 37 of file README_ALTIVEC.txt.
Since we know that Vector is byte aligned and we know the element offset of we should change the load into a lve* x instead of doing a load store lve* x sequence For functions that use altivec AND have we are VRSAVE ing all call clobbered regs Implement passing vectors by value into calls and receiving them as arguments GCC apparently tries to codegen
Initial value:
{ C1, C2, Variable, C3 } as a constant pool load
of C1/C2/C3
Definition at line 51 of file README_ALTIVEC.txt.
A predicate compare being used in a select_cc should have the same peephole applied to it as a predicate compare used by a br_cc There should be no mfcr oris r5 li li lvx r4 lvx r3 vcmpeqfp v2 mfcr rlwinm cmpwi bne cr0
Definition at line 152 of file README_ALTIVEC.txt.
we get the following basic r4 lvx r3 vcmpeqfp v2 vcmpeqfp v2 bne cr6
Definition at line 100 of file README_ALTIVEC.txt.
Since we know that Vector is byte aligned and we know the element offset of we should change the load into a lve* x instead of doing a load store lve* x sequence For functions that use altivec AND have we are VRSAVE ing all call clobbered regs Implement passing vectors by value into calls and receiving them as arguments GCC apparently tries to then a load and vperm of Variable We need a way to teach tblgen that some operands of an intrinsic are required to be constants The verifier should enforce this constraint We currently codegen SCALAR_TO_VECTOR as a store of the scalar to a byte aligned stack followed by a load vperm We should probably just store it to a scalar stack then use lvsl vperm to load it If the value is already in memory this is a big win extract_vector_elt of an arbitrary constant vector can be done with the following vec_ste& destloc
Definition at line 72 of file README_ALTIVEC.txt.
vperm to rotate result into correct slot vsel result together Should codegen branches on vec_any vec_all to avoid mfcr Two examples
Definition at line 195 of file README_ALTIVEC.txt.
float space text globl _test align oris r3 lis stfs r1 addi lfs f0
Definition at line 127 of file README_ALTIVEC.txt.
float space text globl _test align oris r3 lis stfs f1
Definition at line 127 of file README_ALTIVEC.txt.
A predicate compare being used in a select_cc should have the same peephole applied to it as a predicate compare used by a br_cc There should be no mfcr here
Definition at line 152 of file README_ALTIVEC.txt.
Referenced by foo().
splat index
Definition at line 186 of file README_ALTIVEC.txt.
Referenced by llvm::yaml::Input::classof(), llvm::MachineBasicBlock::CorrectExtraCFGEdges(), DecodeVLD1LN(), DecodeVLD2LN(), DecodeVLD3LN(), DecodeVLD4LN(), DecodeVST1LN(), DecodeVST2LN(), DecodeVST3LN(), DecodeVST4LN(), llvm::DwarfUnits::emitAddresses(), llvm::MCStreamer::EmitIntValue(), llvm::DwarfAccelTable::FinalizeTable(), ftostr(), llvm::getAlign(), llvm::DWARFContext::getCompileUnitAtIndex(), llvm::object::COFFObjectFile::getDataDirectory(), llvm::DWARFContext::getDWOCompileUnitAtIndex(), llvm::object::ELFFile< ELFT >::getHeader(), llvm::object::COFFObjectFile::getSymbol(), llvm::object::MachOObjectFile::getSymbolSection(), llvm::DWARFContext::getTypeUnitAtIndex(), getUnconditionalBrDisp(), llvm::SelectionDAG::getVTList(), llvm::NVPTXAsmPrinter::ignoreLoc(), INITIALIZE_PASS(), llvm::ScheduleDAGTopologicalSort::IsReachable(), IsSingleInstrConstant(), llvm::LiveRange::liveAt(), LLVMAddInstrAttribute(), LLVMRemoveInstrAttribute(), LLVMSetInstrParamAlignment(), llvm::DWARFDebugLine::LineTable::lookupAddress(), LowerVASTART(), llvm::yaml::Input::nextDocument(), PBQP::Vector::operator[](), readOperands(), readSIB(), llvm::SlotIndexes::renumberIndexes(), llvm::SlotIndexes::runOnMachineFunction(), llvm::InlineAsm::ConstraintInfo::selectAlternative(), and translateInstruction().
Since we know that Vector is byte aligned and we know the element offset of we should change the load into a lve* x instruction
Definition at line 37 of file README_ALTIVEC.txt.
Since we know that Vector is byte aligned and we know the element offset of we should change the load into a lve* x instead of doing a load store lve* x sequence For functions that use altivec AND have we are VRSAVE ing all call clobbered regs Implement passing vectors by value into calls and receiving them as arguments GCC apparently tries to then a load and vperm of Variable We need a way to teach tblgen that some operands of an intrinsic are required to be constants The verifier should enforce this constraint We currently codegen SCALAR_TO_VECTOR as a store of the scalar to a byte aligned stack followed by a load vperm We should probably just store it to a scalar stack then use lvsl vperm to load it If the value is already in memory this is a big win extract_vector_elt of an arbitrary constant vector can be done with the following instructions
Definition at line 51 of file README_ALTIVEC.txt.
entry LBB1_1
Definition at line 164 of file README_ALTIVEC.txt.
entry mr r5 LBB1_2
Definition at line 100 of file README_ALTIVEC.txt.
entry mr r6 mtspr
Definition at line 123 of file README_ALTIVEC.txt.
Altivec not
Definition at line 25 of file README_ALTIVEC.txt.
Implement PPCInstrInfo::isLoadFromStackSlot isStoreToStackSlot for vector to generate better spill code The first should be a single lvx from the constant pool
Definition at line 4 of file README_ALTIVEC.txt.
float space text globl _test align oris r3 lis stfs r1 addi r1
Definition at line 127 of file README_ALTIVEC.txt.
A predicate compare being used in a select_cc should have the same peephole applied to it as a predicate compare used by a br_cc There should be no mfcr oris r2
Definition at line 123 of file README_ALTIVEC.txt.
entry mr r3
Definition at line 123 of file README_ALTIVEC.txt.
A predicate compare being used in a select_cc should have the same peephole applied to it as a predicate compare used by a br_cc There should be no mfcr oris r5 li r5
Definition at line 127 of file README_ALTIVEC.txt.
entry mr r6
Definition at line 152 of file README_ALTIVEC.txt.
Implement PPCInstrInfo::isLoadFromStackSlot isStoreToStackSlot for vector registers
Definition at line 4 of file README_ALTIVEC.txt.
Referenced by llvm::X86_MC::GetCpuIDAndInfo(), and llvm::X86_MC::GetCpuIDAndInfoEx().
Since we know that Vector is byte aligned and we know the element offset of we should change the load into a lve *x instead of doing a load store lve *x sequence For functions that use altivec AND have we are VRSAVE ing all call clobbered regs Implement passing vectors by value into calls and receiving them as arguments GCC apparently tries to then a load and vperm of Variable We need a way to teach tblgen that some operands of an intrinsic are required to be constants The verifier should enforce this constraint We currently codegen SCALAR_TO_VECTOR as a store of the scalar to a byte aligned stack followed by a load vperm We should probably just store it to a scalar stack slot
Definition at line 51 of file README_ALTIVEC.txt.
Referenced by caller(), llvm::createSparcDelaySlotFillerPass(), and llvm::R600TargetLowering::LowerOperation().
Implement PPCInstrInfo::isLoadFromStackSlot isStoreToStackSlot for vector to generate better spill code The first should be a single lvx from the constant the second should be a xor stvx
Definition at line 4 of file README_ALTIVEC.txt.
Altivec we can use Consider this
Definition at line 25 of file README_ALTIVEC.txt.
A predicate compare being used in a select_cc should have the same peephole applied to it as a predicate compare used by a br_cc There should be no mfcr oris r5 li li lvx r4 lvx r3 vcmpeqfp v2
Definition at line 100 of file README_ALTIVEC.txt.
A predicate compare being used in a select_cc should have the same peephole applied to it as a predicate compare used by a br_cc There should be no mfcr oris r5 li li lvx r4 lvx r3 vcmpeqfp v3
Definition at line 100 of file README_ALTIVEC.txt.
we get the following basic r4 lvx r3 vcmpeqfp v4
Definition at line 100 of file README_ALTIVEC.txt.
v4f32 Vector2 = { Vector.X, Vector.X, Vector.X, Vector.X }
Definition at line 34 of file README_ALTIVEC.txt.
Instead of the following for memset char edx edx edx It might be better to generate eax movl edx movl edx movw edx when we can spare a register It reduces code size Evaluate what the best way to codegen sdiv C is For X
Definition at line 37 of file README_ALTIVEC.txt.
Referenced by llvm::SaveOr::SaveOr(), and llvm::SaveOr::~SaveOr().
vcmpeq to generate a select mask lvsl slot x
Definition at line 187 of file README_ALTIVEC.txt.