LLVM: RegionPass.cpp File Reference
LLVM API Documentation
RegionPass.cpp File Reference
#include "llvm/Analysis/RegionPass.h"
#include "llvm/Analysis/RegionIterator.h"
#include "llvm/Support/Timer.h"
#include "llvm/Support/Debug.h"
Macros
#define DEBUG_TYPE "regionpassmgr"
Functions
static void addRegionIntoQueue (Region *R, std::deque< Region * > &RQ)
Macro Definition Documentation
#define DEBUG_TYPE "regionpassmgr"
Definition at line 20 of file RegionPass.cpp.
Function Documentation
static void addRegionIntoQueue (Region * R, std::deque< Region * > & RQ) static
Definition at line 39 of file RegionPass.cpp.
References llvm::Region::begin(), llvm::Region::end(), and I.
Referenced by llvm::RGPassManager::runOnFunction().