LLVM: RegionInfo.cpp File Reference
LLVM API Documentation
RegionInfo.cpp File Reference
#include "llvm/Analysis/RegionInfo.h"
#include "llvm/ADT/PostOrderIterator.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/RegionIterator.h"
#include "llvm/Assembly/Writer.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Debug.h"
#include <algorithm>
#include <set>
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "region"
Functions
STATISTIC (numRegions,"The # of regions")
STATISTIC (numSimpleRegions,"The # of simple regions")
INITIALIZE_PASS_BEGIN (RegionInfo,"regions","Detect single entry single exit regions", true, true) INITIALIZE_PASS_END(RegionInfo
FunctionPass * llvm::createRegionInfoPass ()
Variables
static bool VerifyRegionInfo = false
static cl::opt< bool, true > VerifyRegionInfoX ("verify-region-info", cl::location(VerifyRegionInfo), cl::desc("Verify region info (time consuming)"))
static cl::opt< enum Region::PrintStyle > printStyle ("print-region-style", cl::Hidden, cl::desc("style of printing regions"), cl::values(clEnumValN(Region::PrintNone,"none","print no details"), clEnumValN(Region::PrintBB,"bb","print regions in detail with block_iterator"), clEnumValN(Region::PrintRN,"rn","print regions in detail with element_iterator"), clEnumValEnd))
regions
Detect single entry single exit true
Macro Definition Documentation
#define DEBUG_TYPE "region"
Definition at line 12 of file RegionInfo.cpp.
Function Documentation
INITIALIZE_PASS_BEGIN (RegionInfo , "regions" , "Detect single entry single exit regions" , true , true)
Referenced by llvm::RegionInfo::splitBlock().
STATISTIC (numRegions , "The # of regions")
STATISTIC (numSimpleRegions , "The # of simple regions")
Variable Documentation
cl::opt<enum Region::PrintStyle> printStyle("print-region-style", cl::Hidden, cl::desc("style of printing regions"), cl::values(clEnumValN(Region::PrintNone,"none","print no details"),clEnumValN(Region::PrintBB,"bb","print regions in detail with block_iterator"),clEnumValN(Region::PrintRN,"rn","print regions in detail with element_iterator"),clEnumValEnd)) static
Referenced by llvm::Region::dump(), and llvm::RegionInfo::print().
Detect single entry single exit regions
Definition at line 853 of file RegionInfo.cpp.
Detect single entry single exit true
Definition at line 853 of file RegionInfo.cpp.
bool VerifyRegionInfo = false static
Definition at line 31 of file RegionInfo.cpp.
Referenced by llvm::RegionInfo::verifyAnalysis(), and llvm::Region::verifyRegion().
cl::opt<bool,true> VerifyRegionInfoX("verify-region-info", cl::location(VerifyRegionInfo), cl::desc("Verify region info (time consuming)")) static