LLVM: ScalarEvolutionNormalization.cpp File Reference
LLVM API Documentation
ScalarEvolutionNormalization.cpp File Reference
#include "llvm/Analysis/Dominators.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/ScalarEvolutionExpressions.h"
#include "llvm/Analysis/ScalarEvolutionNormalization.h"
Functions
static bool IVUseShouldUsePostIncValue (Instruction *User, Value *Operand, const Loop *L, DominatorTree *DT)
Function Documentation
static bool IVUseShouldUsePostIncValue (Instruction * User, Value * Operand, const Loop * L, DominatorTree * DT) static
IVUseShouldUsePostIncValue - We have discovered a "User" of an IV expression and now we need to decide whether the user should use the preinc or post-inc value. If this user should use the post-inc version of the IV, return true.
Choosing wrong here can break dominance properties (if we choose to use the post-inc value when we cannot) or it can end up adding extra live-ranges to the loop, resulting in reg-reg copies (if we use the pre-inc value when we should use the post-inc value).
Definition at line 29 of file ScalarEvolutionNormalization.cpp.
References llvm::BasicBlock::begin(), llvm::LoopBase< BlockT, LoopT >::contains(), llvm::Denormalize, llvm::DominatorTree::dominates(), llvm::dyn_cast(), llvm::SCEV::FlagAnyWrap, llvm::LoopBase< BlockT, LoopT >::getHeader(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::LoopBase< BlockT, LoopT >::getLoopLatch(), llvm::PHINode::getNumIncomingValues(), llvm::Instruction::getParent(), llvm::SCEV::getSCEVType(), llvm::SCEV::getType(), i, I, llvm_unreachable, LO, loops, Loops, N, llvm::Normalize, llvm::NormalizeAutodetect, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::NVPTX::PTXCvtMode::RN, S, llvm::scAddExpr, llvm::scMulExpr, llvm::scSignExtend, llvm::scSMaxExpr, llvm::scTruncate, llvm::scUMaxExpr, llvm::scZeroExtend, and llvm::X.