LLVM: SCCP.cpp File Reference
LLVM API Documentation
SCCP.cpp File Reference
#include "llvm/Transforms/Scalar.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/PointerIntPair.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Instructions.h"
#include "llvm/InstVisitor.h"
#include "llvm/Pass.h"
#include "llvm/Support/CallSite.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetLibraryInfo.h"
#include "llvm/Transforms/IPO.h"
#include "llvm/Transforms/Utils/Local.h"
#include <algorithm>
Macros
#define DEBUG_TYPE "sccp"
Functions
STATISTIC (NumInstRemoved,"Number of instructions removed")
STATISTIC (NumDeadBlocks,"Number of basic blocks unreachable")
STATISTIC (IPNumInstRemoved,"Number of instructions removed by IPSCCP")
STATISTIC (IPNumArgsElimed,"Number of arguments constant propagated by IPSCCP")
STATISTIC (IPNumGlobalConst,"Number of globals found to be constant by IPSCCP")
INITIALIZE_PASS (SCCP,"sccp","Sparse Conditional Constant Propagation", false, false) FunctionPass *llvm
static void DeleteInstructionInBlock (BasicBlock *BB)
INITIALIZE_PASS_BEGIN (IPSCCP,"ipsccp","Interprocedural Sparse Conditional Constant Propagation", false, false) INITIALIZE_PASS_END(IPSCCP
static bool AddressIsTaken (const GlobalValue *GV)
Variables
ipsccp
Interprocedural Sparse Conditional Constant Propagation
Interprocedural Sparse Conditional Constant false
Macro Definition Documentation
#define DEBUG_TYPE "sccp"
Definition at line 20 of file SCCP.cpp.
Function Documentation
static bool AddressIsTaken (const GlobalValue * GV) static
Definition at line 1657 of file SCCP.cpp.
References llvm::Function::arg_begin(), llvm::Function::arg_end(), BB, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::begin(), llvm::BasicBlock::begin(), llvm::Function::begin(), llvm::Module::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::ConstantFoldTerminator(), llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::BranchInst::Create(), llvm::dbgs(), DEBUG, DeleteInstructionInBlock(), llvm::dyn_cast(), llvm::BasicBlock::empty(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), llvm::BasicBlock::end(), llvm::Function::end(), llvm::Module::end(), llvm::iplist< NodeTy, Traits >::erase(), llvm::Instruction::eraseFromParent(), F(), llvm::Function::front(), G, llvm::UndefValue::get(), llvm::Function::getBasicBlockList(), llvm::Module::getContext(), llvm::Module::getGlobalList(), llvm::Value::getName(), llvm::TerminatorInst::getNumSuccessors(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::Function::getReturnType(), llvm::TerminatorInst::getSuccessor(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::Module::global_begin(), llvm::Module::global_end(), llvm::GlobalValue::hasLocalLinkage(), i, I, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::isCallee(), llvm::GlobalValue::isDeclaration(), llvm::Type::isStructTy(), llvm::Type::isVoidTy(), llvm::StoreInst::isVolatile(), llvm_unreachable, M, llvm::GlobalValue::mayBeOverridden(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::Constant::removeDeadConstantUsers(), llvm::BasicBlock::removePredecessor(), llvm::Value::replaceAllUsesWith(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::Value::use_back(), llvm::Value::use_begin(), llvm::Value::use_empty(), and llvm::Value::use_end().
static void DeleteInstructionInBlock (BasicBlock * BB) static
Definition at line 1526 of file SCCP.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::Function::arg_begin(), llvm::Function::arg_end(), BB, llvm::BasicBlock::begin(), llvm::Function::begin(), llvm::dbgs(), DEBUG, llvm::BasicBlock::end(), llvm::Function::end(), llvm::iplist< NodeTy, Traits >::erase(), llvm::Instruction::eraseFromParent(), llvm::UndefValue::get(), llvm::BasicBlock::getInstList(), llvm::Value::getName(), llvm::PassRegistry::getPassRegistry(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), I, INITIALIZE_PASS_BEGIN(), INITIALIZE_PASS_DEPENDENCY, llvm::initializeIPSCCPPass(), llvm::Type::isStructTy(), llvm::Type::isVoidTy(), M, llvm::Value::replaceAllUsesWith(), and llvm::Value::use_empty().
Referenced by AddressIsTaken().
INITIALIZE_PASS (SCCP , "sccp" , "Sparse Conditional Constant Propagation" , false , false)
Definition at line 1518 of file SCCP.cpp.
INITIALIZE_PASS_BEGIN (IPSCCP , "ipsccp" , "Interprocedural Sparse Conditional Constant Propagation" , false , false)
Referenced by DeleteInstructionInBlock().
STATISTIC (NumInstRemoved , "Number of instructions removed")
STATISTIC (NumDeadBlocks , "Number of basic blocks unreachable")
STATISTIC (IPNumInstRemoved , "Number of instructions removed by IPSCCP")
STATISTIC (IPNumArgsElimed , "Number of arguments constant propagated by IPSCCP")
STATISTIC (IPNumGlobalConst , "Number of globals found to be constant by IPSCCP")
Variable Documentation
Interprocedural Sparse Conditional Constant false
Definition at line 1647 of file SCCP.cpp.
ipsccp
Definition at line 1647 of file SCCP.cpp.
Interprocedural Sparse Conditional Constant Propagation
Definition at line 1647 of file SCCP.cpp.