LLVM: ScheduleDAGSDNodes.cpp File Reference
LLVM API Documentation
ScheduleDAGSDNodes.cpp File Reference
#include "ScheduleDAGSDNodes.h"
#include "InstrEmitter.h"
#include "SDNodeDbgValue.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/MC/MCInstrItineraries.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include "llvm/Target/TargetSubtargetInfo.h"
Macros
#define DEBUG_TYPE "pre-RA-sched"
Functions
STATISTIC (LoadsClustered,"Number of loads clustered together")
static void CheckForPhysRegDependency (SDNode *Def, SDNode *User, unsigned Op, const TargetRegisterInfo *TRI, const TargetInstrInfo *TII, unsigned &PhysReg, int &Cost)
static void CloneNodeWithValues (SDNode *N, SelectionDAG *DAG, SmallVectorImpl< EVT > &VTs, SDValue ExtraOper=SDValue())
static bool AddGlue (SDNode *N, SDValue Glue, bool AddGlue, SelectionDAG *DAG)
static void RemoveUnusedGlue (SDNode *N, SelectionDAG *DAG)
static void ProcessSDDbgValues (SDNode *N, SelectionDAG *DAG, InstrEmitter &Emitter, SmallVectorImpl< std::pair< unsigned, MachineInstr * > > &Orders, DenseMap< SDValue, unsigned > &VRBaseMap, unsigned Order)
ProcessSDDbgValues - Process SDDbgValues associated with this node.
static void ProcessSourceNode (SDNode *N, SelectionDAG *DAG, InstrEmitter &Emitter, DenseMap< SDValue, unsigned > &VRBaseMap, SmallVectorImpl< std::pair< unsigned, MachineInstr * > > &Orders, SmallSet< unsigned, 8 > &Seen)
Variables
static cl::opt< int > HighLatencyCycles ("sched-high-latency-cycles", cl::Hidden, cl::init(10), cl::desc("Roughly estimate the number of cycles that 'long latency'""instructions take for targets with no itinerary"))
Macro Definition Documentation
#define DEBUG_TYPE "pre-RA-sched"
Definition at line 15 of file ScheduleDAGSDNodes.cpp.
Function Documentation
static bool AddGlue (SDNode * N, SDValue Glue, bool AddGlue, SelectionDAG * DAG) static
Definition at line 162 of file ScheduleDAGSDNodes.cpp.
References CloneNodeWithValues(), llvm::SDValue::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getNumValues(), llvm::SDNode::getOperand(), llvm::SDNode::getValueType(), llvm::MVT::Glue, I, and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
Referenced by RemoveUnusedGlue().
static void CheckForPhysRegDependency (SDNode * Def, SDNode * User, unsigned Op, const TargetRegisterInfo * TRI, const TargetInstrInfo * TII, unsigned & PhysReg, int & Cost) static
CheckForPhysRegDependency - Check if the dependency between def and use of a specified operand is a physical register dependency. If so, returns the register and the cost of copying the register.
Definition at line 110 of file ScheduleDAGSDNodes.cpp.
References llvm::ISD::CopyToReg, llvm::MCInstrInfo::get(), llvm::TargetRegisterClass::getCopyCost(), llvm::SDNode::getMachineOpcode(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::MCInstrDesc::getNumDefs(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), getReg(), llvm::SDValue::getResNo(), llvm::SDNode::getValueType(), llvm::MCInstrDesc::ImplicitDefs, llvm::SDNode::isMachineOpcode(), and llvm::TargetRegisterInfo::isVirtualRegister().
Referenced by RemoveUnusedGlue().
static void CloneNodeWithValues (SDNode * N, SelectionDAG * DAG, SmallVectorImpl< EVT > & VTs, SDValue ExtraOper = SDValue()) static
Definition at line 135 of file ScheduleDAGSDNodes.cpp.
References llvm::dyn_cast(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getVTList(), I, llvm::MachineSDNode::memoperands_begin(), llvm::MachineSDNode::memoperands_end(), llvm::SelectionDAG::MorphNodeTo(), N, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::MachineSDNode::setMemRefs(), and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by AddGlue(), and RemoveUnusedGlue().
static void ProcessSDDbgValues (SDNode * N, SelectionDAG * DAG, InstrEmitter & Emitter, SmallVectorImpl< std::pair< unsigned, MachineInstr * > > & Orders, DenseMap< SDValue, unsigned > & VRBaseMap, unsigned Order) static
ProcessSDDbgValues - Process SDDbgValues associated with this node.
Definition at line 695 of file ScheduleDAGSDNodes.cpp.
References llvm::ScheduleDAGSDNodes::BB, llvm::InstrEmitter::EmitDbgValue(), llvm::InstrEmitter::getBlock(), llvm::SelectionDAG::GetDbgValues(), llvm::SDNode::getHasDebugValue(), llvm::InstrEmitter::getInsertPos(), i, llvm::MachineBasicBlock::insert(), and llvm::ArrayRef< T >::size().
Referenced by ProcessSourceNode().
static void ProcessSourceNode (SDNode * N, SelectionDAG * DAG, InstrEmitter & Emitter, DenseMap< SDValue, unsigned > & VRBaseMap, SmallVectorImpl< std::pair< unsigned, MachineInstr * > > & Orders, SmallSet< unsigned, 8 > & Seen) static
Definition at line 725 of file ScheduleDAGSDNodes.cpp.
References llvm::MachineBasicBlock::back(), llvm::ScheduleDAGSDNodes::BB, llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::TargetOpcode::COPY, llvm::SUnit::CopyDstRC, llvm::MachineRegisterInfo::createVirtualRegister(), llvm::ScheduleDAGSDNodes::EmitSchedule(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::find(), llvm::MCInstrInfo::get(), llvm::InstrEmitter::getBlock(), llvm::InstrEmitter::getInsertPos(), llvm::SDNode::getIROrder(), I, llvm::SmallSet< T, N, C >::insert(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::insert(), llvm::MachineInstr::isPHI(), llvm::ScheduleDAG::MRI, llvm::SUnit::Preds, llvm::prior(), ProcessSDDbgValues(), llvm::MachineBasicBlock::push_back(), llvm::SUnit::Succs, and llvm::ScheduleDAG::TII.
Referenced by llvm::ScheduleDAGSDNodes::EmitSchedule().
static void RemoveUnusedGlue (SDNode * N, SelectionDAG * DAG) static
Definition at line 190 of file ScheduleDAGSDNodes.cpp.
References AddGlue(), llvm::SUnit::addPred(), llvm::TargetSubtargetInfo::adjustSchedDependency(), llvm::SelectionDAG::allnodes_begin(), llvm::SelectionDAG::allnodes_end(), llvm::TargetInstrInfo::areLoadsFromSameBasePtr(), llvm::SDep::Barrier, llvm::SmallVectorTemplateCommon< T >::begin(), CheckForPhysRegDependency(), CloneNodeWithValues(), llvm::ScheduleDAGSDNodes::computeLatency(), llvm::ScheduleDAGSDNodes::computeOperandLatency(), llvm::ISD::CopyToReg, llvm::InstrEmitter::CountResults(), llvm::ScheduleDAGSDNodes::DAG, llvm::SDep::Data, llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::ScheduleDAGSDNodes::forceUnitLatencies(), llvm::MCInstrInfo::get(), llvm::SDNode::getGluedNode(), llvm::SDNode::getMachineOpcode(), llvm::SDValue::getNode(), llvm::SUnit::getNode(), llvm::SDNode::getNodeId(), llvm::MCInstrDesc::getNumOperands(), llvm::SDNode::getNumOperands(), llvm::SDNode::getNumValues(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), llvm::MCInstrDesc::getOperandConstraint(), llvm::SelectionDAG::getRoot(), llvm::TargetMachine::getSubtarget(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::MVT::Glue, llvm::SDNode::hasAnyUseOfValue(), llvm::SUnit::hasPhysRegClobbers, llvm::SUnit::hasPhysRegDefs, i, I, llvm::ScheduleDAGSDNodes::InitNumRegDefsLeft(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::insert(), llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::SUnit::isCall, llvm::SUnit::isCallOp, llvm::SUnit::isCommutable, llvm::MCInstrDesc::isCommutable(), llvm::SDep::isCtrl(), llvm::SDNode::isMachineOpcode(), llvm::ScheduleDAGSDNodes::isPassiveNode(), llvm::SUnit::isScheduleLow, llvm::SUnit::isTwoAddress, llvm::SUnit::Latency, llvm::SPII::Load, llvm::MCInstrDesc::mayLoad(), N, llvm::ScheduleDAGSDNodes::newSUnit(), llvm::SUnit::NodeNum, llvm::SUnit::NumRegDefsLeft, llvm::MVT::Other, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SDep::setLatency(), llvm::SUnit::setNode(), llvm::SDNode::setNodeId(), llvm::TargetInstrInfo::shouldScheduleLoadsNear(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::A64DB::ST, llvm::ScheduleDAG::StressSched, llvm::ScheduleDAG::SUnits, llvm::MCOI::TIED_TO, llvm::ScheduleDAG::TII, llvm::ScheduleDAG::TM, llvm::ISD::TokenFactor, llvm::ScheduleDAG::TRI, llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
STATISTIC (LoadsClustered , "Number of loads clustered together")
Variable Documentation
cl::opt<int> HighLatencyCycles("sched-high-latency-cycles", cl::Hidden, cl::init(10), cl::desc("Roughly estimate the number of cycles that 'long latency'""instructions take for targets with no itinerary")) static
Referenced by llvm::ScheduleDAGSDNodes::computeLatency().