LLVM: ScheduleDAGFast.cpp File Reference
LLVM API Documentation
ScheduleDAGFast.cpp File Reference
#include "llvm/CodeGen/SchedulerRegistry.h"
#include "InstrEmitter.h"
#include "ScheduleDAGSDNodes.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetRegisterInfo.h"
Macros
#define DEBUG_TYPE "pre-RA-sched"
Functions
STATISTIC (NumUnfolds,"Number of nodes unfolded")
STATISTIC (NumDups,"Number of duplicated nodes")
STATISTIC (NumPRCopies,"Number of physical copies")
static EVT getPhysicalRegisterVT (SDNode *N, unsigned Reg, const TargetInstrInfo *TII)
static bool CheckForLiveRegDef (SUnit *SU, unsigned Reg, std::vector< SUnit * > &LiveRegDefs, SmallSet< unsigned, 4 > &RegAdded, SmallVectorImpl< unsigned > &LRegs, const TargetRegisterInfo *TRI)
static SDNode * findGluedUser (SDNode *N)
Variables
static RegisterScheduler fastDAGScheduler ("fast","Fast suboptimal list scheduling", createFastDAGScheduler)
static RegisterScheduler linearizeDAGScheduler ("linearize","Linearize DAG, no scheduling", createDAGLinearizer)
Macro Definition Documentation
#define DEBUG_TYPE "pre-RA-sched"
Definition at line 14 of file ScheduleDAGFast.cpp.
Function Documentation
static bool CheckForLiveRegDef (SUnit * SU, unsigned Reg, std::vector< SUnit * > & LiveRegDefs, SmallSet< unsigned, 4 > & RegAdded, SmallVectorImpl< unsigned > & LRegs, const TargetRegisterInfo * TRI) static
CheckForLiveRegDef - Return true and update live register vector if the specified register def of the specified SUnit clobbers any "live" registers.
Definition at line 448 of file ScheduleDAGFast.cpp.
References llvm::SDep::Artificial, llvm::SmallVectorTemplateCommon< T >::back(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::clear(), llvm::SmallVectorImpl< T >::clear(), llvm::dbgs(), DEBUG, llvm::SDNode::dump(), llvm::SmallVectorBase::empty(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), llvm::ISD::EntryToken, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::find(), llvm::SmallVectorTemplateCommon< T >::front(), llvm::SDNode::getGluedNode(), llvm::MCInstrDesc::getImplicitDefs(), llvm::SDValue::getNode(), llvm::SUnit::getNode(), llvm::SDNode::getNodeId(), llvm::InlineAsm::getNumOperandRegisters(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOpcode(), llvm::SDNode::getOperand(), getPhysicalRegisterVT(), getReg(), llvm::SDValue::getValueType(), llvm::MVT::Glue, i, I, llvm::MCInstrDesc::ImplicitDefs, llvm::ISD::INLINEASM, llvm::SmallSet< T, N, C >::insert(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::insert(), llvm::zlib::isAvailable(), llvm::SUnit::isAvailable, llvm::InlineAsm::isClobberKind(), llvm::SDNode::isMachineOpcode(), llvm::SUnit::isPending, llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::InlineAsm::isRegDefEarlyClobberKind(), llvm::InlineAsm::isRegDefKind(), llvm::MCRegAliasIterator::isValid(), llvm_unreachable, N, llvm::SUnit::NodeNum, llvm::SUnit::Preds, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::report_fatal_error(), llvm::SDNode::setNodeId(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::SUnit::Succs, and TII.
static SDNode* findGluedUser (SDNode * N) static
findGluedUser - Find the representative use of a glue value by walking the use chain.
Definition at line 710 of file ScheduleDAGFast.cpp.
References BB, llvm::dbgs(), DEBUG, llvm::SDNode::dump(), llvm::InstrEmitter::EmitNode(), llvm::ISD::EntryToken, llvm::InstrEmitter::getBlock(), llvm::SDNode::getGluedUser(), llvm::InstrEmitter::getInsertPos(), llvm::SDNode::getNodeId(), llvm::SDNode::getNumValues(), llvm::SDNode::getOpcode(), llvm::SDNode::getValueType(), llvm::MVT::Glue, llvm::SDNode::hasAnyUseOfValue(), i, I, llvm::SDNode::isMachineOpcode(), N, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SDNode::setNodeId(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::SDNode::use_begin(), llvm::SDNode::use_end(), and llvm::SDNode::use_size().
static EVT getPhysicalRegisterVT (SDNode * N, unsigned Reg, const TargetInstrInfo * TII) static
getPhysicalRegisterVT - Returns the ValueType of the physical register definition of the specified node. FIXME: Move to SelectionDAG?
Definition at line 433 of file ScheduleDAGFast.cpp.
References llvm::MCInstrInfo::get(), llvm::MCInstrDesc::getImplicitDefs(), llvm::SDNode::getMachineOpcode(), llvm::MCInstrDesc::getNumDefs(), llvm::SDNode::getValueType(), and llvm::MCInstrDesc::ImplicitDefs.
Referenced by CheckForLiveRegDef().
STATISTIC (NumUnfolds , "Number of nodes unfolded")
STATISTIC (NumDups , "Number of duplicated nodes")
STATISTIC (NumPRCopies , "Number of physical copies")
Variable Documentation
RegisterScheduler fastDAGScheduler("fast","Fast suboptimal list scheduling", createFastDAGScheduler) static
RegisterScheduler linearizeDAGScheduler("linearize","Linearize DAG, no scheduling", createDAGLinearizer) static