LLVM: SelectionDAGBuilder.cpp File Reference
LLVM API Documentation
SelectionDAGBuilder.cpp File Reference
#include "SelectionDAGBuilder.h"
#include "SDNodeDbgValue.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/Optional.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/BranchProbabilityInfo.h"
#include "llvm/Analysis/ConstantFolding.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/FastISel.h"
#include "llvm/CodeGen/FunctionLoweringInfo.h"
#include "llvm/CodeGen/GCMetadata.h"
#include "llvm/CodeGen/GCStrategy.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineJumpTableInfo.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/CodeGen/StackMaps.h"
#include "llvm/DebugInfo.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetFrameLowering.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetIntrinsicInfo.h"
#include "llvm/Target/TargetLibraryInfo.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Target/TargetOptions.h"
#include "llvm/Target/TargetSelectionDAGInfo.h"
#include <algorithm>
#include "llvm/IR/Instruction.def"
#include "llvm/CodeGen/SelectionDAGISel.h"
Macros
#define DEBUG_TYPE "isel"
#define HANDLE_INST(NUM, OPCODE, CLASS) case Instruction::OPCODE: visit##OPCODE((const CLASS&)I); break;
Functions
static SDValue getCopyFromPartsVector (SelectionDAG &DAG, SDLoc DL, const SDValue *Parts, unsigned NumParts, MVT PartVT, EVT ValueVT, const Value *V)
static SDValue getCopyFromParts (SelectionDAG &DAG, SDLoc DL, const SDValue *Parts, unsigned NumParts, MVT PartVT, EVT ValueVT, const Value *V, ISD::NodeType AssertOp=ISD::DELETED_NODE)
static void getCopyToPartsVector (SelectionDAG &DAG, SDLoc dl, SDValue Val, SDValue *Parts, unsigned NumParts, MVT PartVT, const Value *V)
static void getCopyToParts (SelectionDAG &DAG, SDLoc DL, SDValue Val, SDValue *Parts, unsigned NumParts, MVT PartVT, const Value *V, ISD::NodeType ExtendKind=ISD::ANY_EXTEND)
static bool InBlock (const Value *V, const BasicBlock *BB)
static bool areJTsAllowed (const TargetLowering &TLI)
static APInt ComputeRange (const APInt &First, const APInt &Last)
static bool isSequentialInRange (const SmallVectorImpl< int > &Mask, unsigned Pos, unsigned Size, int Low)
static SDValue InsertFenceForAtomic (SDValue Chain, AtomicOrdering Order, SynchronizationScope Scope, bool Before, SDLoc dl, SelectionDAG &DAG, const TargetLowering &TLI)
static SDValue GetSignificand (SelectionDAG &DAG, SDValue Op, SDLoc dl)
static SDValue GetExponent (SelectionDAG &DAG, SDValue Op, const TargetLowering &TLI, SDLoc dl)
static SDValue getF32Constant (SelectionDAG &DAG, unsigned Flt)
getF32Constant - Get 32-bit floating point constant.
static SDValue expandExp (SDLoc dl, SDValue Op, SelectionDAG &DAG, const TargetLowering &TLI)
static SDValue expandLog (SDLoc dl, SDValue Op, SelectionDAG &DAG, const TargetLowering &TLI)
static SDValue expandLog2 (SDLoc dl, SDValue Op, SelectionDAG &DAG, const TargetLowering &TLI)
static SDValue expandLog10 (SDLoc dl, SDValue Op, SelectionDAG &DAG, const TargetLowering &TLI)
static SDValue expandExp2 (SDLoc dl, SDValue Op, SelectionDAG &DAG, const TargetLowering &TLI)
static SDValue expandPow (SDLoc dl, SDValue LHS, SDValue RHS, SelectionDAG &DAG, const TargetLowering &TLI)
static SDValue ExpandPowI (SDLoc DL, SDValue LHS, SDValue RHS, SelectionDAG &DAG)
ExpandPowI - Expand a llvm.powi intrinsic.
static unsigned getTruncatedArgReg (const SDValue &N)
static bool IsOnlyUsedInZeroEqualityComparison (const Value *V)
static SDValue getMemCmpLoad (const Value *PtrVal, MVT LoadVT, Type *LoadTy, SelectionDAGBuilder &Builder)
static void GetRegistersForValue (SelectionDAG &DAG, const TargetLowering &TLI, SDLoc DL, SDISelAsmOperandInfo &OpInfo)
static bool isOnlyUsedInEntryBlock (const Argument *A, bool FastISel)
Variables
static unsigned LimitFloatPrecision
static cl::opt< unsigned, true > LimitFPPrecision ("limit-float-precision", cl::desc("Generate low-precision inline sequences ""for some float libcalls"), cl::location(LimitFloatPrecision), cl::init(0))
static const unsigned MaxParallelChains = 64
Macro Definition Documentation
#define DEBUG_TYPE "isel"
Definition at line 14 of file SelectionDAGBuilder.cpp.
#define HANDLE_INST (NUM, OPCODE, CLASS) case Instruction::OPCODE: visit##OPCODE((const CLASS&)I); break;
Function Documentation
static bool areJTsAllowed (const TargetLowering & TLI) inline static
Definition at line 2175 of file SelectionDAGBuilder.cpp.
References llvm::ISD::BR_JT, llvm::ISD::BRIND, llvm::TargetLoweringBase::isOperationLegalOrCustom(), llvm::MVT::Other, and llvm::TargetLoweringBase::supportJumpTables().
Referenced by ComputeRange().
static APInt ComputeRange (const APInt & First, const APInt & Last) static
Definition at line 2181 of file SelectionDAGBuilder.cpp.
References areJTsAllowed(), BB, llvm::tgtok::Bits, llvm::FunctionLoweringInfo::BPI, llvm::SwitchInst::case_begin(), llvm::SwitchInst::case_end(), llvm::MachineJumpTableInfo::createJumpTableIndex(), llvm::MachineFunction::CreateMachineBasicBlock(), llvm::dbgs(), DEBUG, double, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::find(), First, llvm::APInt::getBitWidth(), llvm::BranchProbabilityInfo::getEdgeWeight(), llvm::TargetLowering::getJumpTableEncoding(), llvm::APInt::getLimitedValue(), llvm::TargetLoweringBase::getMinimumJumpTableEntries(), llvm::APInt::getNullValue(), llvm::MachineFunction::getOrCreateJumpTableInfo(), llvm::Instruction::getParent(), llvm::TargetLoweringBase::getPointerTy(), llvm::EVT::getSizeInBits(), i, I, llvm::SmallSet< T, N, C >::insert(), llvm::MachineFunction::insert(), llvm::TargetLoweringBase::isOperationLegal(), j(), llvm::ISD::JumpTable, llvm::APInt::logBase2(), llvm::FunctionLoweringInfo::MBBMap, llvm::FunctionLoweringInfo::MF, llvm::next(), llvm::MVT::Other, llvm::APInt::roundToDouble(), llvm::ISD::SETLT, llvm::APInt::sext(), llvm::ISD::SHL, llvm::SmallSet< T, N, C >::size(), llvm::APInt::sle(), llvm::APInt::slt(), llvm::SystemZISD::TM, and llvm::APInt::uge().
static SDValue expandExp (SDLoc dl, SDValue Op, SelectionDAG & DAG, const TargetLowering & TLI) static
expandExp - Lower an exp intrinsic. Handles the special sequences for limited-precision mode.
Definition at line 3813 of file SelectionDAGBuilder.cpp.
References llvm::ISD::ADD, llvm::ISD::BITCAST, llvm::MVT::f32, llvm::ISD::FADD, llvm::ISD::FEXP, llvm::ISD::FMUL, llvm::ISD::FP_TO_SINT, llvm::ISD::FSUB, llvm::SelectionDAG::getConstant(), getF32Constant(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SDValue::getValueType(), llvm::MVT::i32, LimitFloatPrecision, llvm::ISD::SHL, llvm::ISD::SINT_TO_FP, t1(), and llvm::X.
Referenced by getTruncatedArgReg().
static SDValue expandExp2 (SDLoc dl, SDValue Op, SelectionDAG & DAG, const TargetLowering & TLI) static
expandExp2 - Lower an exp2 intrinsic. Handles the special sequences for limited-precision mode.
Definition at line 4195 of file SelectionDAGBuilder.cpp.
References llvm::ISD::ADD, llvm::ISD::BITCAST, llvm::MVT::f32, llvm::ISD::FADD, llvm::ISD::FEXP2, llvm::ISD::FMUL, llvm::ISD::FP_TO_SINT, llvm::ISD::FSUB, llvm::SelectionDAG::getConstant(), getF32Constant(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SDValue::getValueType(), llvm::MVT::i32, LimitFloatPrecision, llvm::ISD::SHL, llvm::ISD::SINT_TO_FP, t1(), and llvm::X.
Referenced by getTruncatedArgReg().
static SDValue expandLog (SDLoc dl, SDValue Op, SelectionDAG & DAG, const TargetLowering & TLI) static
expandLog - Lower a log intrinsic. Handles the special sequences for limited-precision mode.
Definition at line 3916 of file SelectionDAGBuilder.cpp.
References llvm::ISD::BITCAST, llvm::MVT::f32, llvm::ISD::FADD, llvm::ISD::FLOG, llvm::ISD::FMUL, llvm::ISD::FSUB, GetExponent(), getF32Constant(), llvm::SelectionDAG::getNode(), GetSignificand(), llvm::SDValue::getValueType(), llvm::MVT::i32, LimitFloatPrecision, t1(), and llvm::X.
Referenced by getTruncatedArgReg().
static SDValue expandLog10 (SDLoc dl, SDValue Op, SelectionDAG & DAG, const TargetLowering & TLI) static
expandLog10 - Lower a log10 intrinsic. Handles the special sequences for limited-precision mode.
Definition at line 4107 of file SelectionDAGBuilder.cpp.
References llvm::ISD::BITCAST, llvm::MVT::f32, llvm::ISD::FADD, llvm::ISD::FLOG10, llvm::ISD::FMUL, llvm::ISD::FSUB, GetExponent(), getF32Constant(), llvm::SelectionDAG::getNode(), GetSignificand(), llvm::SDValue::getValueType(), llvm::MVT::i32, LimitFloatPrecision, t1(), and llvm::X.
Referenced by getTruncatedArgReg().
static SDValue expandLog2 (SDLoc dl, SDValue Op, SelectionDAG & DAG, const TargetLowering & TLI) static
expandLog2 - Lower a log2 intrinsic. Handles the special sequences for limited-precision mode.
Definition at line 4012 of file SelectionDAGBuilder.cpp.
References llvm::ISD::BITCAST, llvm::MVT::f32, llvm::ISD::FADD, llvm::ISD::FLOG2, llvm::ISD::FMUL, llvm::ISD::FSUB, GetExponent(), getF32Constant(), llvm::SelectionDAG::getNode(), GetSignificand(), llvm::SDValue::getValueType(), llvm::MVT::i32, LimitFloatPrecision, t1(), and llvm::X.
Referenced by getTruncatedArgReg().
static SDValue expandPow (SDLoc dl, SDValue LHS, SDValue RHS, SelectionDAG & DAG, const TargetLowering & TLI) static
visitPow - Lower a pow intrinsic. Handles the special sequences for limited-precision mode with x == 10.0f.
Definition at line 4290 of file SelectionDAGBuilder.cpp.
References llvm::ISD::ADD, llvm::ISD::BITCAST, f(), llvm::MVT::f32, llvm::ISD::FADD, llvm::ISD::FMUL, llvm::ISD::FP_TO_SINT, llvm::ISD::FPOW, llvm::ISD::FSUB, llvm::SelectionDAG::getConstant(), getF32Constant(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::SDValue::getValueType(), llvm::MVT::i32, LimitFloatPrecision, llvm::ISD::SHL, llvm::ISD::SINT_TO_FP, t1(), and llvm::X.
Referenced by getTruncatedArgReg().
static SDValue ExpandPowI (SDLoc DL, SDValue LHS, SDValue RHS, SelectionDAG & DAG) static
ExpandPowI - Expand a llvm.powi intrinsic.
Definition at line 4398 of file SelectionDAGBuilder.cpp.
References llvm::CountPopulation_32(), F(), llvm::ISD::FDIV, llvm::ISD::FMUL, llvm::ISD::FPOWI, llvm::Function::getAttributes(), llvm::SelectionDAG::getConstantFP(), llvm::MachineFunction::getFunction(), llvm::SelectionDAG::getMachineFunction(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValueType(), llvm::AttributeSet::hasAttribute(), llvm::Log2_32(), and llvm::Attribute::OptimizeForSize.
Referenced by getTruncatedArgReg().
static SDValue getCopyFromParts (SelectionDAG & DAG, SDLoc DL, const SDValue * Parts, unsigned NumParts, MVT PartVT, EVT ValueVT, const Value * V, ISD::NodeType AssertOp = ISD::DELETED_NODE) static
getCopyFromParts - Create a value that contains the specified legal parts combined into the value they represent. If the parts combine to a type larger then ValueVT then AssertOp can be used to specify whether the extra bits are known to be zero (ISD::AssertZext) or sign extended from ValueVT (ISD::AssertSext).
Definition at line 101 of file SelectionDAGBuilder.cpp.
References llvm::ISD::ANY_EXTEND, llvm::ISD::BITCAST, llvm::EVT::bitsLT(), llvm::ISD::BUILD_PAIR, llvm::ISD::DELETED_NODE, llvm::MVT::f64, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), getCopyFromPartsVector(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::MVT::getSizeInBits(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::HexagonISD::Hi, llvm::TargetLoweringBase::isBigEndian(), llvm::MVT::isFloatingPoint(), llvm::EVT::isFloatingPoint(), llvm::MVT::isInteger(), llvm::EVT::isInteger(), llvm::MVT::isVector(), llvm::EVT::isVector(), llvm_unreachable, llvm::HexagonISD::Lo, llvm::Log2_32(), llvm::ISD::OR, llvm::MVT::ppcf128, llvm::ISD::SHL, std::swap(), llvm::ISD::TRUNCATE, and llvm::ISD::ZERO_EXTEND.
Referenced by getCopyFromPartsVector(), getCopyToPartsVector(), isOnlyUsedInEntryBlock(), and llvm::TargetLowering::LowerCallTo().
static SDValue getCopyFromPartsVector (SelectionDAG & DAG, SDLoc DL, const SDValue * Parts, unsigned NumParts, MVT PartVT, EVT ValueVT, const Value * V) static
getCopyFromPartsVector - Create a value that contains the specified legal parts combined into the value they represent. If the parts combine to a type larger then ValueVT then AssertOp can be used to specify whether the extra bits are known to be zero (ISD::AssertZext) or sign extended from ValueVT (ISD::AssertSext).
Definition at line 222 of file SelectionDAGBuilder.cpp.
References llvm::ISD::ANY_EXTEND, llvm::ISD::BITCAST, llvm::EVT::bitsLE(), llvm::ISD::BUILD_VECTOR, llvm::ISD::CONCAT_VECTORS, llvm::LLVMContext::emitError(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), getCopyFromParts(), getCopyToPartsVector(), llvm::SelectionDAG::getNode(), llvm::EVT::getScalarType(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValueType(), llvm::EVT::getVectorElementType(), llvm::TargetLoweringBase::getVectorIdxTy(), llvm::EVT::getVectorNumElements(), llvm::TargetLoweringBase::getVectorTypeBreakdown(), i, I, llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), and llvm::ISD::TRUNCATE.
Referenced by getCopyFromParts().
static void getCopyToParts (SelectionDAG & DAG, SDLoc DL, SDValue Val, SDValue * Parts, unsigned NumParts, MVT PartVT, const Value * V, ISD::NodeType ExtendKind = ISD::ANY_EXTEND) static
getCopyToParts - Create a series of nodes that contain the specified value split into legal parts. If the parts contain more bits than Val, then, for integers, ExtendKind can be used to specify how to generate the extra bits.
Definition at line 339 of file SelectionDAGBuilder.cpp.
References llvm::ISD::BITCAST, llvm::LLVMContext::emitError(), llvm::ISD::EXTRACT_ELEMENT, llvm::ISD::FP_EXTEND, llvm::SelectionDAG::getContext(), getCopyToPartsVector(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::getSizeInBits(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SDValue::getValueType(), i, I, llvm::TargetLoweringBase::isBigEndian(), llvm::MVT::isFloatingPoint(), llvm::EVT::isFloatingPoint(), llvm::MVT::isInteger(), llvm::EVT::isInteger(), llvm::TargetLoweringBase::isTypeLegal(), llvm::EVT::isVector(), llvm::Log2_32(), llvm::ISD::SRL, llvm::ISD::TRUNCATE, and llvm::MVT::x86mmx.
Referenced by getCopyToPartsVector(), llvm::SelectionDAGBuilder::getValueImpl(), and llvm::TargetLowering::LowerCallTo().
static void getCopyToPartsVector (SelectionDAG & DAG, SDLoc DL, SDValue Val, SDValue * Parts, unsigned NumParts, MVT PartVT, const Value * V) static
getCopyToPartsVector - Create a series of nodes that contain the specified value split into legal parts.
Definition at line 471 of file SelectionDAGBuilder.cpp.
References llvm::ISD::ANY_EXTEND, llvm::sys::path::append(), llvm::SmallVectorImpl< T >::append(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::SmallVectorTemplateCommon< T >::begin(), llvm::ISD::BITCAST, llvm::EVT::bitsGE(), llvm::EVT::bitsLE(), llvm::ISD::BUILD_VECTOR, llvm::SmallVectorImpl< T >::clear(), llvm::tgtok::Code, llvm::ComputeValueVTs(), llvm::APInt::countLeadingOnes(), llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), getCopyFromParts(), llvm::SelectionDAG::getCopyFromReg(), getCopyToParts(), llvm::SelectionDAG::getCopyToReg(), llvm::InlineAsm::getFlagWord(), llvm::InlineAsm::getFlagWordForMatchingOp(), llvm::InlineAsm::getFlagWordForRegClass(), llvm::TargetRegisterClass::getID(), llvm::FunctionLoweringInfo::GetLiveOutRegInfo(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getNumRegisters(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::SelectionDAG::getRegister(), llvm::TargetLoweringBase::getRegisterType(), llvm::SDValue::getResNo(), llvm::MVT::getSizeInBits(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetLoweringInfo(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::MVT::getVectorElementType(), llvm::EVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVTList(), i, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i8, llvm::MVT::isInteger(), llvm::TargetLoweringBase::isTypeLegal(), llvm::MVT::isVector(), llvm::EVT::isVector(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::TargetLoweringBase::isZExtFree(), llvm::FunctionLoweringInfo::LiveOutInfo::KnownZero, llvm::ISD::MERGE_VALUES, MRI, llvm::FunctionLoweringInfo::LiveOutInfo::NumSignBits, llvm::MVT::Other, P, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorImpl< T >::resize(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::ISD::TokenFactor, llvm::ISD::TRUNCATE, and llvm::ISD::ZERO_EXTEND.
Referenced by getCopyFromPartsVector(), and getCopyToParts().
static SDValue GetExponent (SelectionDAG & DAG, SDValue Op, const TargetLowering & TLI, SDLoc dl) static
GetExponent - Get the exponent:
(float)(int)(((Op & 0x7f800000) >> 23) - 127);
where Op is the hexadecimal representation of floating point value.
Definition at line 3793 of file SelectionDAGBuilder.cpp.
References llvm::ISD::AND, llvm::MVT::f32, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getPointerTy(), llvm::MVT::i32, llvm::ISD::SINT_TO_FP, llvm::ISD::SRL, llvm::ISD::SUB, and t1().
Referenced by expandLog(), expandLog10(), and expandLog2().
static SDValue getF32Constant (SelectionDAG & DAG, unsigned Flt) static
getF32Constant - Get 32-bit floating point constant.
Definition at line 3806 of file SelectionDAGBuilder.cpp.
References llvm::lltok::APFloat, llvm::MVT::f32, llvm::SelectionDAG::getConstantFP(), and llvm::APFloat::IEEEsingle.
Referenced by expandExp(), expandExp2(), expandLog(), expandLog10(), expandLog2(), and expandPow().
static SDValue getMemCmpLoad (const Value * PtrVal, MVT LoadVT, Type * LoadTy, SelectionDAGBuilder & Builder) static
Definition at line 5524 of file SelectionDAGBuilder.cpp.
References llvm::SelectionDAGBuilder::AA, llvm::TargetLoweringBase::allowsUnalignedMemoryAccesses(), llvm::LibFunc::ceil, llvm::LibFunc::ceilf, llvm::LibFunc::ceill, llvm::ComputeUsesVAFloatArgument(), llvm::ConstantFoldLoadFromConstPtr(), llvm::LibFunc::copysign, llvm::LibFunc::copysignf, llvm::LibFunc::copysignl, llvm::LibFunc::cos, llvm::LibFunc::cosf, llvm::LibFunc::cosl, llvm::SelectionDAGBuilder::DAG, llvm::dyn_cast(), llvm::TargetSelectionDAGInfo::EmitTargetCodeForMemchr(), llvm::TargetSelectionDAGInfo::EmitTargetCodeForMemcmp(), llvm::TargetSelectionDAGInfo::EmitTargetCodeForStrcmp(), llvm::TargetSelectionDAGInfo::EmitTargetCodeForStrcpy(), llvm::TargetSelectionDAGInfo::EmitTargetCodeForStrlen(), llvm::TargetSelectionDAGInfo::EmitTargetCodeForStrnlen(), llvm::LibFunc::exp2, llvm::LibFunc::exp2f, llvm::LibFunc::exp2l, F(), llvm::LibFunc::fabs, llvm::ISD::FABS, llvm::LibFunc::fabsf, llvm::LibFunc::fabsl, llvm::ISD::FCEIL, llvm::ISD::FCOPYSIGN, llvm::ISD::FCOS, llvm::ISD::FEXP2, llvm::ISD::FFLOOR, llvm::ISD::FLOG2, llvm::LibFunc::floor, llvm::LibFunc::floorf, llvm::LibFunc::floorl, llvm::ISD::FNEARBYINT, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::ISD::FSIN, llvm::ISD::FSQRT, llvm::ISD::FTRUNC, llvm::IntegerType::get(), llvm::CallInst::getArgOperand(), llvm::ConstantExpr::getBitCast(), llvm::CallInst::getCalledFunction(), llvm::CallInst::getCalledValue(), llvm::SelectionDAG::getConstant(), llvm::Value::getContext(), llvm::SelectionDAGBuilder::getCurSDLoc(), llvm::SequentialType::getElementType(), llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getExternalSymbol(), llvm::Type::getInt16Ty(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMachineFunction(), llvm::MachineFunction::getMMI(), llvm::SelectionDAG::getNode(), llvm::CallInst::getNumArgOperands(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRoot(), llvm::SelectionDAG::getSelectionDAGInfo(), llvm::SelectionDAG::getSetCC(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::Value::getType(), llvm::DataLayout::getTypeSizeInBits(), llvm::PointerType::getUnqual(), llvm::SDValue::getValue(), llvm::SelectionDAGBuilder::getValue(), llvm::SDValue::getValueType(), llvm::TargetLoweringBase::getValueType(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::ConstantInt::getZExtValue(), llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, info, llvm::Type::isFloatingPointTy(), llvm::Type::isIntegerTy(), IsOnlyUsedInZeroEqualityComparison(), llvm::Type::isPointerTy(), llvm::Type::isSingleValueType(), llvm::Type::isSized(), llvm::CallInst::isTailCall(), llvm::TargetLoweringBase::isTypeLegal(), llvm::LibFunc::log2, llvm::LibFunc::log2f, llvm::LibFunc::log2l, llvm::LibFunc::memchr, llvm::LibFunc::memcmp, llvm::LibFunc::nearbyint, llvm::LibFunc::nearbyintf, llvm::LibFunc::nearbyintl, llvm::CallInst::onlyReadsMemory(), llvm::MVT::Other, llvm::SelectionDAGBuilder::PendingLoads, llvm::AliasAnalysis::pointsToConstantMemory(), llvm::report_fatal_error(), llvm::LibFunc::rint, llvm::LibFunc::rintf, llvm::LibFunc::rintl, llvm::LibFunc::round, llvm::LibFunc::roundf, llvm::LibFunc::roundl, llvm::ISD::SETNE, llvm::SelectionDAG::setRoot(), llvm::LibFunc::sin, llvm::LibFunc::sinf, llvm::LibFunc::sinl, llvm::LibFunc::sqrt, llvm::LibFunc::sqrt_finite, llvm::LibFunc::sqrtf, llvm::LibFunc::sqrtf_finite, llvm::LibFunc::sqrtl, llvm::LibFunc::sqrtl_finite, llvm::LibFunc::stpcpy, llvm::LibFunc::strcmp, llvm::LibFunc::strcpy, llvm::LibFunc::strlen, llvm::LibFunc::strnlen, llvm::SelectionDAGBuilder::TD, llvm::SystemZISD::TM, llvm::LibFunc::trunc, llvm::LibFunc::truncf, and llvm::LibFunc::truncl.
static void GetRegistersForValue (SelectionDAG & DAG, const TargetLowering & TLI, SDLoc DL, SDISelAsmOperandInfo & OpInfo) static
GetRegistersForValue - Assign registers (virtual or physical) for the specified operand. We prefer to assign virtual registers, to allow the register allocator to handle the assignment process. However, if the asm uses features that we can't model on machineinstrs, we have SDISel do the allocation. This produces generally horrible, but correct, code.
OpInfo describes the operand.
Definition at line 6085 of file SelectionDAGBuilder.cpp.
References Align, BB, llvm::TargetRegisterClass::begin(), llvm::ISD::BITCAST, llvm::TargetLowering::C_Memory, llvm::TargetLowering::C_Other, llvm::TargetLowering::C_Register, llvm::TargetLowering::C_RegisterClass, llvm::TargetLowering::ComputeConstraintToUse(), llvm::TargetLowering::AsmOperandInfo::ConstraintType, llvm::MachineFrameInfo::CreateStackObject(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::LLVMContext::emitError(), llvm::SmallVectorBase::empty(), llvm::TargetRegisterClass::end(), llvm::DataLayout::getABITypeAlignment(), llvm::CallInst::getArgOperand(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getArgument(), llvm::InlineAsm::getAsmString(), llvm::SelectionDAG::getBasicBlock(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledValue(), llvm::SelectionDAG::getConstantPool(), llvm::TargetLowering::getConstraintType(), llvm::SelectionDAG::getContext(), llvm::TargetLoweringBase::getDataLayout(), llvm::InlineAsm::getDialect(), llvm::MachinePointerInfo::getFixedStack(), llvm::InlineAsm::getFlagWord(), llvm::InlineAsm::getFlagWordForMatchingOp(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getInstruction(), llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMDNode(), llvm::Instruction::getMetadata(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::InlineAsm::getNumOperandRegisters(), llvm::TargetLoweringBase::getNumRegisters(), llvm::User::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::DataLayout::getPrefTypeAlignment(), llvm::TargetLoweringBase::getRegClassFor(), llvm::TargetLowering::getRegForInlineAsmConstraint(), llvm::MachineFunction::getRegInfo(), llvm::SelectionDAG::getRoot(), llvm::TargetLoweringBase::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::SelectionDAG::getSrcValue(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetExternalSymbol(), llvm::Value::getType(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::SelectionDAG::getVAArg(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::TargetLoweringBase::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::InlineAsm::hasSideEffects(), i, I, llvm::ISD::INLINEASM, llvm::InlineAsm::isAlignStack(), llvm::InlineAsm::isClobber, llvm::InlineAsm::isInput, llvm::MVT::isInteger(), llvm::EVT::isInteger(), llvm::InlineAsm::isMemKind(), llvm::InlineAsm::isOutput, llvm::InlineAsm::isRegDefEarlyClobberKind(), llvm::InlineAsm::isRegDefKind(), llvm::Type::isSingleValueType(), llvm::Type::isSized(), llvm::EVT::isVector(), llvm::Type::isVoidTy(), j(), llvm::TargetLowering::LowerAsmOperandForConstraint(), llvm::FunctionLoweringInfo::MBBMap, llvm::MVT::Other, llvm::TargetLowering::ParseConstraints(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::report_fatal_error(), llvm::SelectionDAG::setRoot(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::SystemZISD::TM, llvm::ISD::TokenFactor, llvm::ISD::TRUNCATE, llvm::InlineAsm::ConstraintInfo::Type, llvm::ISD::VACOPY, llvm::ISD::VAEND, llvm::ISD::VASTART, and llvm::TargetRegisterClass::vt_begin().
static SDValue GetSignificand (SelectionDAG & DAG, SDValue Op, SDLoc dl) static
GetSignificand - Get the significand and build it into a floating-point number with exponent of 1:
Op = (Op & 0x007fffff) | 0x3f800000;
where Op is the hexadecimal representation of floating point value.
Definition at line 3779 of file SelectionDAGBuilder.cpp.
References llvm::ISD::AND, llvm::ISD::BITCAST, llvm::MVT::f32, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::i32, llvm::ISD::OR, and t1().
Referenced by expandLog(), expandLog10(), and expandLog2().
static unsigned getTruncatedArgReg (const SDValue & N) static
Definition at line 4452 of file SelectionDAGBuilder.cpp.
References llvm::ISD::ADD, llvm::SelectionDAG::AddDbgValue(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMetadata(), llvm::Intrinsic::adjust_trampoline, llvm::ISD::ADJUST_TRAMPOLINE, Align, llvm::Intrinsic::annotation, llvm::FunctionLoweringInfo::ArgDbgValues, llvm::ISD::AssertSext, llvm::ISD::AssertZext, BB, llvm::SmallVectorTemplateCommon< T >::begin(), llvm::ISD::BITCAST, llvm::ISD::BSWAP, llvm::Intrinsic::bswap, llvm::ISD::BUILD_VECTOR, llvm::BuildMI(), llvm::CallingConv::C, llvm::Intrinsic::ceil, llvm::Intrinsic::convert_from_fp16, llvm::Intrinsic::convert_to_fp16, llvm::Intrinsic::convertff, llvm::Intrinsic::convertfsi, llvm::Intrinsic::convertfui, llvm::Intrinsic::convertsif, llvm::Intrinsic::convertss, llvm::Intrinsic::convertsu, llvm::Intrinsic::convertuif, llvm::Intrinsic::convertus, llvm::Intrinsic::convertuu, llvm::ISD::CopyFromReg, llvm::Intrinsic::copysign, llvm::Intrinsic::cos, llvm::MachineOperand::CreateFI(), llvm::MachineOperand::CreateReg(), llvm::ISD::CTLZ, llvm::Intrinsic::ctlz, llvm::ISD::CTLZ_ZERO_UNDEF, llvm::ISD::CTPOP, llvm::Intrinsic::ctpop, llvm::ISD::CTTZ, llvm::Intrinsic::cttz, llvm::ISD::CTTZ_ZERO_UNDEF, llvm::ISD::CVT_FF, llvm::ISD::CVT_FS, llvm::ISD::CVT_FU, llvm::ISD::CVT_INVALID, llvm::ISD::CVT_SF, llvm::ISD::CVT_SS, llvm::ISD::CVT_SU, llvm::ISD::CVT_UF, llvm::ISD::CVT_US, llvm::ISD::CVT_UU, llvm::StringRef::data(), llvm::Intrinsic::dbg_declare, llvm::TargetOpcode::DBG_VALUE, llvm::Intrinsic::dbg_value, llvm::dbgs(), DEBUG, llvm::Intrinsic::debugtrap, llvm::ISD::DEBUGTRAP, llvm::Intrinsic::donothing, llvm::Value::dump(), llvm::dyn_cast(), llvm::Intrinsic::eh_dwarf_cfa, llvm::ISD::EH_RETURN, llvm::Intrinsic::eh_return_i32, llvm::Intrinsic::eh_return_i64, llvm::Intrinsic::eh_sjlj_callsite, llvm::Intrinsic::eh_sjlj_functioncontext, llvm::ISD::EH_SJLJ_LONGJMP, llvm::Intrinsic::eh_sjlj_longjmp, llvm::ISD::EH_SJLJ_SETJMP, llvm::Intrinsic::eh_sjlj_setjmp, llvm::Intrinsic::eh_typeid_for, llvm::Intrinsic::eh_unwind_init, llvm::StringRef::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::end(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::Intrinsic::exp, llvm::Intrinsic::exp2, expandExp(), expandExp2(), expandLog(), expandLog10(), expandLog2(), expandPow(), ExpandPowI(), llvm::Intrinsic::expect, llvm::Intrinsic::experimental_patchpoint_i64, llvm::Intrinsic::experimental_patchpoint_void, llvm::Intrinsic::experimental_stackmap, llvm::MipsISD::Ext, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ExtractTypeInfo(), F(), llvm::MVT::f32, llvm::Intrinsic::fabs, llvm::ISD::FABS, llvm::ISD::FADD, llvm::ISD::FCEIL, llvm::ISD::FCOPYSIGN, llvm::ISD::FCOS, llvm::ISD::FFLOOR, llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::find(), llvm::Intrinsic::floor, llvm::Intrinsic::flt_rounds, llvm::ISD::FLT_ROUNDS_, llvm::ISD::FMA, llvm::Intrinsic::fma, llvm::ISD::FMUL, llvm::Intrinsic::fmuladd, llvm::ISD::FNEARBYINT, llvm::ISD::FP16_TO_FP32, llvm::ISD::FP32_TO_FP16, llvm::ISD::FRAME_TO_ARGS_OFFSET, llvm::ISD::FRAMEADDR, llvm::Intrinsic::frameaddress, llvm::ISD::FRINT, llvm::ISD::FROUND, llvm::ISD::FSIN, llvm::ISD::FSQRT, llvm::ISD::FTRUNC, llvm::Intrinsic::gcread, llvm::Intrinsic::gcroot, llvm::Intrinsic::gcwrite, llvm::MCInstrInfo::get(), llvm::DbgDeclareInst::getAddress(), llvm::CallInst::getArgOperand(), llvm::FunctionLoweringInfo::getArgumentFrameIndex(), llvm::CallInst::getCalledValue(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConvertRndSat(), llvm::MachineModuleInfo::getCurrentCallSite(), llvm::SelectionDAG::getDbgValue(), llvm::Instruction::getDebugLoc(), llvm::SelectionDAG::getExternalSymbol(), llvm::MachinePointerInfo::getFixedStack(), llvm::SelectionDAG::getFrameIndex(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getFunction(), llvm::FrameIndexSDNode::getIndex(), llvm::TargetMachine::getInstrInfo(), llvm::EVT::getIntegerVT(), llvm::MachineRegisterInfo::getLiveInPhysReg(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SelectionDAG::getMemmove(), llvm::SelectionDAG::getMemset(), llvm::MachineFunction::getMMI(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::DbgValueInst::getOffset(), llvm::SDValue::getOpcode(), llvm::User::getOperand(), llvm::SDValue::getOperand(), llvm::Instruction::getParent(), llvm::TargetLoweringBase::getPointerTy(), llvm::MachineOperand::getReg(), getReg(), llvm::MachineFunction::getRegInfo(), llvm::SDValue::getResNo(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::SelectionDAG::getSrcValue(), llvm::SelectionDAG::getStore(), llvm::DIDescriptor::getTag(), llvm::SelectionDAG::getTarget(), llvm::Value::getType(), llvm::MachineModuleInfo::getTypeIDFor(), llvm::SelectionDAG::getUNDEF(), llvm::GetUnderlyingObjects(), llvm::DbgValueInst::getValue(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getValueType(), llvm::TargetLoweringBase::getValueType(), llvm::DbgDeclareInst::getVariable(), llvm::DbgValueInst::getVariable(), llvm::TargetLoweringBase::getVectorIdxTy(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVTList(), llvm::ConstantInt::getZExtValue(), llvm::MachineModuleInfo::hasDebugInfo(), I, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::INIT_TRAMPOLINE, llvm::Intrinsic::init_trampoline, llvm::ISD::INSERT_SUBVECTOR, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::Intrinsic::invariant_end, llvm::Intrinsic::invariant_start, llvm::TargetLoweringBase::isFMAFasterThanFMulAndFAdd(), llvm::DIVariable::isInlinedFnArgument(), llvm::MachineOperand::isReg(), llvm::DebugLoc::isUnknown(), llvm::DIDescriptor::isVariable(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::ConstantInt::isZero(), llvm::ISD::LIFETIME_END, llvm::Intrinsic::lifetime_end, llvm::ISD::LIFETIME_START, llvm::Intrinsic::lifetime_start, llvm_unreachable, llvm::Intrinsic::log, llvm::Intrinsic::log10, llvm::Intrinsic::log2, llvm::Intrinsic::longjmp, llvm::TargetLowering::LowerCallTo(), llvm::FunctionLoweringInfo::MBBMap, llvm::Intrinsic::memcpy, llvm::Intrinsic::memmove, llvm::Intrinsic::memset, N, llvm::Intrinsic::nearbyint, llvm::CodeGenOpt::None, llvm::Intrinsic::objectsize, llvm::MVT::Other, llvm::ISD::PCMARKER, llvm::Intrinsic::pcmarker, llvm::Intrinsic::pow, llvm::Intrinsic::powi, llvm::ISD::PREFETCH, llvm::Intrinsic::prefetch, llvm::Intrinsic::ptr_annotation, llvm::ISD::READCYCLECOUNTER, llvm::Intrinsic::readcyclecounter, llvm::ISD::RETURNADDR, llvm::Intrinsic::returnaddress, llvm::Intrinsic::rint, llvm::Intrinsic::round, llvm::Intrinsic::sadd_with_overflow, llvm::ISD::SADDO, llvm::MachineModuleInfo::setCallsEHReturn(), llvm::MachineModuleInfo::setCallsUnwindInit(), llvm::MachineModuleInfo::setCurrentCallSite(), llvm::MachineFrameInfo::setFunctionContextIndex(), llvm::Intrinsic::setjmp, llvm::SelectionDAG::setRoot(), llvm::MachineFrameInfo::setStackProtectorIndex(), llvm::MachineModuleInfo::setVariableDbgInfo(), llvm::Intrinsic::sin, llvm::Intrinsic::smul_with_overflow, llvm::ISD::SMULO, llvm::Intrinsic::sqrt, llvm::Intrinsic::ssub_with_overflow, llvm::ISD::SSUBO, llvm::Intrinsic::stackprotector, llvm::Intrinsic::stackprotectorcheck, llvm::ISD::STACKRESTORE, llvm::Intrinsic::stackrestore, llvm::ISD::STACKSAVE, llvm::Intrinsic::stacksave, llvm::FunctionLoweringInfo::StaticAllocaMap, llvm::FPOpFusion::Strict, llvm::Value::stripPointerCasts(), TII, llvm::SystemZISD::TM, llvm::ISD::TRAP, llvm::Intrinsic::trap, TrapFuncName(), llvm::Intrinsic::trunc, llvm::ISD::TRUNCATE, llvm::Intrinsic::uadd_with_overflow, llvm::ISD::UADDO, llvm::Intrinsic::umul_with_overflow, llvm::ISD::UMULO, llvm::Value::use_empty(), llvm::TargetLoweringBase::usesUnderscoreLongJmp(), llvm::TargetLoweringBase::usesUnderscoreSetJmp(), llvm::Intrinsic::usub_with_overflow, llvm::ISD::USUBO, llvm::MVT::v2i32, llvm::Intrinsic::vacopy, llvm::Intrinsic::vaend, llvm::FunctionLoweringInfo::ValueMap, llvm::Intrinsic::var_annotation, llvm::Intrinsic::vastart, llvm::Intrinsic::x86_avx2_vextracti128, llvm::Intrinsic::x86_avx2_vinserti128, llvm::Intrinsic::x86_avx_vextractf128_pd_256, llvm::Intrinsic::x86_avx_vextractf128_ps_256, llvm::Intrinsic::x86_avx_vextractf128_si_256, llvm::Intrinsic::x86_avx_vinsertf128_pd_256, llvm::Intrinsic::x86_avx_vinsertf128_ps_256, llvm::Intrinsic::x86_avx_vinsertf128_si_256, llvm::Intrinsic::x86_mmx_psll_d, llvm::Intrinsic::x86_mmx_psll_q, llvm::Intrinsic::x86_mmx_psll_w, llvm::Intrinsic::x86_mmx_pslli_d, llvm::Intrinsic::x86_mmx_pslli_q, llvm::Intrinsic::x86_mmx_pslli_w, llvm::Intrinsic::x86_mmx_psra_d, llvm::Intrinsic::x86_mmx_psra_w, llvm::Intrinsic::x86_mmx_psrai_d, llvm::Intrinsic::x86_mmx_psrai_w, llvm::Intrinsic::x86_mmx_psrl_d, llvm::Intrinsic::x86_mmx_psrl_q, llvm::Intrinsic::x86_mmx_psrl_w, llvm::Intrinsic::x86_mmx_psrli_d, llvm::Intrinsic::x86_mmx_psrli_q, and llvm::Intrinsic::x86_mmx_psrli_w.
static bool InBlock (const Value * V, const BasicBlock * BB) static
Definition at line 1372 of file SelectionDAGBuilder.cpp.
References BB, and llvm::Instruction::getParent().
Referenced by llvm::SelectionDAGBuilder::FindMergedConditions(), and getEdgeValueLocal().
static SDValue InsertFenceForAtomic (SDValue Chain, AtomicOrdering Order, SynchronizationScope Scope, bool Before, SDLoc dl, SelectionDAG & DAG, const TargetLowering & TLI) static
Definition at line 3513 of file SelectionDAGBuilder.cpp.
References llvm::Acquire, llvm::AcquireRelease, llvm::AtomicRMWInst::Add, llvm::AtomicRMWInst::And, llvm::ISD::ATOMIC_CMP_SWAP, llvm::ISD::ATOMIC_FENCE, llvm::ISD::ATOMIC_LOAD, llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_MAX, llvm::ISD::ATOMIC_LOAD_MIN, llvm::ISD::ATOMIC_LOAD_NAND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_SUB, llvm::ISD::ATOMIC_LOAD_UMAX, llvm::ISD::ATOMIC_LOAD_UMIN, llvm::ISD::ATOMIC_LOAD_XOR, llvm::ISD::ATOMIC_STORE, llvm::ISD::ATOMIC_SWAP, llvm::ISD::BITCAST, llvm::ComputeValueVTs(), llvm::SmallVectorTemplateCommon< T >::data(), llvm::CallInst::doesNotAccessMemory(), llvm::LoadInst::getAlignment(), llvm::StoreInst::getAlignment(), llvm::CallInst::getArgOperand(), llvm::SelectionDAG::getAtomic(), llvm::AtomicCmpXchgInst::getCompareOperand(), llvm::SelectionDAG::getConstant(), llvm::TargetLoweringBase::getInsertFencesForAtomic(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::AtomicCmpXchgInst::getNewValOperand(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::CallInst::getNumArgOperands(), llvm::SDNode::getNumValues(), llvm::AtomicRMWInst::getOperation(), llvm::LoadInst::getOrdering(), llvm::StoreInst::getOrdering(), llvm::FenceInst::getOrdering(), llvm::AtomicCmpXchgInst::getOrdering(), llvm::AtomicRMWInst::getOrdering(), llvm::LoadInst::getPointerOperand(), llvm::StoreInst::getPointerOperand(), llvm::AtomicCmpXchgInst::getPointerOperand(), llvm::AtomicRMWInst::getPointerOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SelectionDAG::getRoot(), llvm::EVT::getSizeInBits(), llvm::LoadInst::getSynchScope(), llvm::StoreInst::getSynchScope(), llvm::FenceInst::getSynchScope(), llvm::AtomicCmpXchgInst::getSynchScope(), llvm::AtomicRMWInst::getSynchScope(), llvm::SelectionDAG::getTargetConstant(), llvm::TargetLoweringBase::getTgtMemIntrinsic(), llvm::Value::getType(), llvm::AtomicRMWInst::getValOperand(), llvm::SDValue::getValue(), llvm::StoreInst::getValueOperand(), llvm::TargetLoweringBase::getValueType(), llvm::SelectionDAG::getVTList(), i, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::ISD::INTRINSIC_WO_CHAIN, llvm::Type::isVoidTy(), llvm_unreachable, llvm::AtomicRMWInst::Max, llvm::AtomicRMWInst::Min, llvm::Monotonic, llvm::AtomicRMWInst::Nand, llvm::CallInst::onlyReadsMemory(), llvm::AtomicRMWInst::Or, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::Release, llvm::report_fatal_error(), llvm::SequentiallyConsistent, llvm::SelectionDAG::setRoot(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::AtomicRMWInst::Sub, llvm::SystemZISD::TM, llvm::AtomicRMWInst::UMax, llvm::AtomicRMWInst::UMin, llvm::AtomicRMWInst::Xchg, and llvm::AtomicRMWInst::Xor.
static bool isOnlyUsedInEntryBlock (const Argument * A, bool FastISel) static
isOnlyUsedInEntryBlock - If the specified argument is only used in the entry block, return true. This includes arguments used by switches, since the switch may expand into multiple basic blocks.
Definition at line 7198 of file SelectionDAGBuilder.cpp.
References llvm::MachineBasicBlock::addSuccessor(), llvm::Function::arg_begin(), llvm::Function::arg_end(), llvm::ISD::AssertSext, llvm::ISD::AssertZext, BB, llvm::BasicBlock::begin(), llvm::MachineBasicBlock::begin(), llvm::Function::begin(), llvm::ISD::BUILD_PAIR, llvm::Attribute::ByVal, llvm::FunctionLoweringInfo::CanLowerReturn, llvm::ComputeValueVTs(), llvm::ISD::CopyFromReg, llvm::MachineFunction::CreateMachineBasicBlock(), llvm::FunctionLoweringInfo::CreateRegs(), llvm::MachineRegisterInfo::createVirtualRegister(), DEBUG, llvm::ISD::DELETED_NODE, llvm::FunctionLoweringInfo::DemoteRegister, llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::end(), F(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::find(), llvm::ISD::InputArg::Flags, llvm::DataLayout::getABITypeAlignment(), llvm::Function::getAttributes(), llvm::TargetLoweringBase::getByValTypeAlignment(), llvm::Function::getCallingConv(), llvm::SelectionDAG::getContext(), getCopyFromParts(), llvm::TargetLoweringBase::getDataLayout(), llvm::SequentialType::getElementType(), llvm::PHINode::getIncomingValueForBlock(), llvm::SDValue::getNode(), llvm::TargetLoweringBase::getNumRegisters(), llvm::TerminatorInst::getNumSuccessors(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::Function::getParamAlignment(), llvm::Argument::getParent(), llvm::MachineBasicBlock::getParent(), getReg(), llvm::TargetLoweringBase::getRegClassFor(), llvm::MachineFunction::getRegInfo(), llvm::TargetLoweringBase::getRegisterType(), llvm::Function::getReturnType(), llvm::SelectionDAG::getRoot(), llvm::MVT::getStoreSize(), llvm::EVT::getStoreSize(), llvm::TerminatorInst::getSuccessor(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::EVT::getTypeForEVT(), llvm::PointerType::getUnqual(), llvm::SDValue::getValueType(), llvm::AttributeSet::hasAttribute(), i, I, llvm::FunctionLoweringInfo::InitializeRegForValue(), llvm::Attribute::InReg, llvm::MipsISD::Ins, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::MachineFunction::insert(), llvm::Type::isEmptyTy(), llvm::Function::isVarArg(), llvm::TargetRegisterInfo::isVirtualRegister(), llvm::TargetLowering::LowerFormalArguments(), llvm::FunctionLoweringInfo::MBBMap, llvm::Attribute::Nest, llvm::MVT::Other, llvm::FunctionLoweringInfo::PHINodesToUpdate, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::FunctionLoweringInfo::setArgumentFrameIndex(), llvm::ISD::ArgFlagsTy::setByVal(), llvm::ISD::ArgFlagsTy::setByValAlign(), llvm::ISD::ArgFlagsTy::setByValSize(), llvm::ISD::ArgFlagsTy::setInReg(), llvm::ISD::ArgFlagsTy::setNest(), llvm::ISD::ArgFlagsTy::setOrigAlign(), llvm::ISD::ArgFlagsTy::setSExt(), llvm::ISD::ArgFlagsTy::setSplit(), llvm::ISD::ArgFlagsTy::setSRet(), llvm::ISD::ArgFlagsTy::setZExt(), llvm::Attribute::SExt, llvm::SmallVectorTemplateCommon< T >::size(), llvm::FunctionLoweringInfo::StaticAllocaMap, llvm::Attribute::StructRet, llvm::SystemZISD::TM, llvm::Value::use_begin(), llvm::Value::use_empty(), llvm::Value::use_end(), llvm::FunctionLoweringInfo::ValueMap, and llvm::Attribute::ZExt.
static bool IsOnlyUsedInZeroEqualityComparison (const Value * V) static
IsOnlyUsedInZeroEqualityComparison - Return true if it only matters that the value is equal or not-equal to zero.
Definition at line 5510 of file SelectionDAGBuilder.cpp.
References llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by getMemCmpLoad().
static bool isSequentialInRange (const SmallVectorImpl< int > & Mask, unsigned Pos, unsigned Size, int Low) static
Definition at line 2982 of file SelectionDAGBuilder.cpp.
References llvm::ARM_PROC::A, llvm::ISD::ADD, Align, llvm::ISD::AND, llvm::ISD::BUILD_VECTOR, llvm::ComputeLinearIndex(), llvm::ComputeValueVTs(), llvm::ISD::CONCAT_VECTORS, llvm::MachineFrameInfo::CreateVariableSizedObject(), llvm::ISD::DYNAMIC_STACKALLOC, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::tgtok::Field, llvm::AllocaInst::getAlignment(), llvm::LoadInst::getAlignment(), llvm::StoreInst::getAlignment(), llvm::AllocaInst::getAllocatedType(), llvm::AllocaInst::getArraySize(), llvm::SelectionDAG::getConstant(), llvm::TargetLoweringBase::getDataLayout(), llvm::SelectionDAG::getEntryNode(), llvm::MachineFunction::getFrameInfo(), llvm::ExtractValueInst::getIndices(), llvm::InsertValueInst::getIndices(), llvm::SelectionDAG::getIntPtrConstant(), llvm::SelectionDAG::getLoad(), llvm::Instruction::getMetadata(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::User::getOperand(), llvm::Type::getPointerAddressSpace(), llvm::TargetLoweringBase::getPointerSizeInBits(), llvm::TargetLoweringBase::getPointerTy(), llvm::DataLayout::getPrefTypeAlignment(), llvm::SDValue::getResNo(), llvm::SelectionDAG::getRoot(), llvm::Type::getScalarType(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::ShuffleVectorInst::getShuffleMask(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getStore(), llvm::Value::getType(), llvm::DataLayout::getTypeAllocSize(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::TargetLoweringBase::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::TargetLoweringBase::getVectorIdxTy(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::SelectionDAG::getVTList(), llvm::SelectionDAG::getZExtOrTrunc(), i, llvm::MVT::i64, int, llvm::LoadInst::isAtomic(), llvm::StoreInst::isAtomic(), llvm::APInt::isPowerOf2(), llvm::LoadInst::isVolatile(), llvm::StoreInst::isVolatile(), llvm::APInt::logBase2(), MaxParallelChains, llvm::LLVMContext::MD_range, llvm::LLVMContext::MD_tbaa, llvm::ISD::MERGE_VALUES, llvm::FunctionLoweringInfo::MF, llvm::ISD::MUL, N, llvm::User::op_begin(), llvm::User::op_end(), llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SelectionDAG::setRoot(), llvm::ISD::SHL, llvm::SmallVectorTemplateCommon< T >::size(), llvm::FunctionLoweringInfo::StaticAllocaMap, llvm::SystemZISD::TM, llvm::ISD::TokenFactor, llvm::ISD::TRUNCATE, and llvm::ISD::UNDEF.
Variable Documentation
unsigned LimitFloatPrecision static
LimitFloatPrecision - Generate low-precision inline sequences for some float libcalls (6, 8 or 12 bits).
Definition at line 67 of file SelectionDAGBuilder.cpp.
Referenced by expandExp(), expandExp2(), expandLog(), expandLog10(), expandLog2(), and expandPow().
cl::opt<unsigned, true> LimitFPPrecision("limit-float-precision", cl::desc("Generate low-precision inline sequences ""for some float libcalls"), cl::location(LimitFloatPrecision), cl::init(0)) static
const unsigned MaxParallelChains = 64 static
Definition at line 90 of file SelectionDAGBuilder.cpp.
Referenced by isSequentialInRange().