var SelectionDAGNodes_8h =
[
    [ "DenseMapInfo", "structllvm_1_1DenseMapInfo.html", null ],
    [ "simplify_type", "structllvm_1_1simplify__type.html", "structllvm_1_1simplify__type" ],
    [ "ilist_traits", "structllvm_1_1ilist__traits.html", null ],
    [ "SDVTList", "structllvm_1_1SDVTList.html", "structllvm_1_1SDVTList" ],
    [ "SDValue", "classllvm_1_1SDValue.html", "classllvm_1_1SDValue" ],
    [ "DenseMapInfo< SDValue >", "structllvm_1_1DenseMapInfo_3_01SDValue_01_4.html", "structllvm_1_1DenseMapInfo_3_01SDValue_01_4" ],
    [ "isPodLike< SDValue >", "structllvm_1_1isPodLike_3_01SDValue_01_4.html", "structllvm_1_1isPodLike_3_01SDValue_01_4" ],
    [ "simplify_type< SDValue >", "structllvm_1_1simplify__type_3_01SDValue_01_4.html", "structllvm_1_1simplify__type_3_01SDValue_01_4" ],
    [ "simplify_type< const SDValue >", "structllvm_1_1simplify__type_3_01const_01SDValue_01_4.html", "structllvm_1_1simplify__type_3_01const_01SDValue_01_4" ],
    [ "SDUse", "classllvm_1_1SDUse.html", "classllvm_1_1SDUse" ],
    [ "simplify_type< SDUse >", "structllvm_1_1simplify__type_3_01SDUse_01_4.html", "structllvm_1_1simplify__type_3_01SDUse_01_4" ],
    [ "SDNode", "classllvm_1_1SDNode.html", "classllvm_1_1SDNode" ],
    [ "use_iterator", "classllvm_1_1SDNode_1_1use__iterator.html", "classllvm_1_1SDNode_1_1use__iterator" ],
    [ "SDLoc", "classllvm_1_1SDLoc.html", "classllvm_1_1SDLoc" ],
    [ "UnarySDNode", "classllvm_1_1UnarySDNode.html", "classllvm_1_1UnarySDNode" ],
    [ "BinarySDNode", "classllvm_1_1BinarySDNode.html", "classllvm_1_1BinarySDNode" ],
    [ "TernarySDNode", "classllvm_1_1TernarySDNode.html", "classllvm_1_1TernarySDNode" ],
    [ "HandleSDNode", "classllvm_1_1HandleSDNode.html", "classllvm_1_1HandleSDNode" ],
    [ "AddrSpaceCastSDNode", "classllvm_1_1AddrSpaceCastSDNode.html", "classllvm_1_1AddrSpaceCastSDNode" ],
    [ "MemSDNode", "classllvm_1_1MemSDNode.html", "classllvm_1_1MemSDNode" ],
    [ "AtomicSDNode", "classllvm_1_1AtomicSDNode.html", "classllvm_1_1AtomicSDNode" ],
    [ "MemIntrinsicSDNode", "classllvm_1_1MemIntrinsicSDNode.html", "classllvm_1_1MemIntrinsicSDNode" ],
    [ "ShuffleVectorSDNode", "classllvm_1_1ShuffleVectorSDNode.html", "classllvm_1_1ShuffleVectorSDNode" ],
    [ "ConstantSDNode", "classllvm_1_1ConstantSDNode.html", "classllvm_1_1ConstantSDNode" ],
    [ "ConstantFPSDNode", "classllvm_1_1ConstantFPSDNode.html", "classllvm_1_1ConstantFPSDNode" ],
    [ "GlobalAddressSDNode", "classllvm_1_1GlobalAddressSDNode.html", "classllvm_1_1GlobalAddressSDNode" ],
    [ "FrameIndexSDNode", "classllvm_1_1FrameIndexSDNode.html", "classllvm_1_1FrameIndexSDNode" ],
    [ "JumpTableSDNode", "classllvm_1_1JumpTableSDNode.html", "classllvm_1_1JumpTableSDNode" ],
    [ "ConstantPoolSDNode", "classllvm_1_1ConstantPoolSDNode.html", "classllvm_1_1ConstantPoolSDNode" ],
    [ "TargetIndexSDNode", "classllvm_1_1TargetIndexSDNode.html", "classllvm_1_1TargetIndexSDNode" ],
    [ "BasicBlockSDNode", "classllvm_1_1BasicBlockSDNode.html", "classllvm_1_1BasicBlockSDNode" ],
    [ "BuildVectorSDNode", "classllvm_1_1BuildVectorSDNode.html", "classllvm_1_1BuildVectorSDNode" ],
    [ "SrcValueSDNode", "classllvm_1_1SrcValueSDNode.html", "classllvm_1_1SrcValueSDNode" ],
    [ "MDNodeSDNode", "classllvm_1_1MDNodeSDNode.html", "classllvm_1_1MDNodeSDNode" ],
    [ "RegisterSDNode", "classllvm_1_1RegisterSDNode.html", "classllvm_1_1RegisterSDNode" ],
    [ "RegisterMaskSDNode", "classllvm_1_1RegisterMaskSDNode.html", "classllvm_1_1RegisterMaskSDNode" ],
    [ "BlockAddressSDNode", "classllvm_1_1BlockAddressSDNode.html", "classllvm_1_1BlockAddressSDNode" ],
    [ "EHLabelSDNode", "classllvm_1_1EHLabelSDNode.html", "classllvm_1_1EHLabelSDNode" ],
    [ "ExternalSymbolSDNode", "classllvm_1_1ExternalSymbolSDNode.html", "classllvm_1_1ExternalSymbolSDNode" ],
    [ "CondCodeSDNode", "classllvm_1_1CondCodeSDNode.html", "classllvm_1_1CondCodeSDNode" ],
    [ "CvtRndSatSDNode", "classllvm_1_1CvtRndSatSDNode.html", "classllvm_1_1CvtRndSatSDNode" ],
    [ "VTSDNode", "classllvm_1_1VTSDNode.html", "classllvm_1_1VTSDNode" ],
    [ "LSBaseSDNode", "classllvm_1_1LSBaseSDNode.html", "classllvm_1_1LSBaseSDNode" ],
    [ "LoadSDNode", "classllvm_1_1LoadSDNode.html", "classllvm_1_1LoadSDNode" ],
    [ "StoreSDNode", "classllvm_1_1StoreSDNode.html", "classllvm_1_1StoreSDNode" ],
    [ "MachineSDNode", "classllvm_1_1MachineSDNode.html", "classllvm_1_1MachineSDNode" ],
    [ "SDNodeIterator", "classllvm_1_1SDNodeIterator.html", "classllvm_1_1SDNodeIterator" ],
    [ "GraphTraits< SDNode * >", "structllvm_1_1GraphTraits_3_01SDNode_01_5_01_4.html", "structllvm_1_1GraphTraits_3_01SDNode_01_5_01_4" ],
    [ "LargestSDNode", "SelectionDAGNodes_8h.html#ad6a91d9d2bd48edc23163a2e8bbb5da4", null ],
    [ "MostAlignedSDNode", "SelectionDAGNodes_8h.html#aba53e296f00955814837731c1d1cff83", null ],
    [ "allOperandsUndef", "SelectionDAGNodes_8h.html#a933d79e63e855d7c90bf161355c008ec", null ],
    [ "checkForCycles", "SelectionDAGNodes_8h.html#a307acd65e0b4952229acdbe8bec2bb7d", null ],
    [ "isBuildVectorAllOnes", "SelectionDAGNodes_8h.html#ac78d4df51ca05e4fb1630a01e07de434", null ],
    [ "isBuildVectorAllZeros", "SelectionDAGNodes_8h.html#aaac3e239cbdfe15a8e9bad4f8e1e3a95", null ],
    [ "isEXTLoad", "SelectionDAGNodes_8h.html#a910795e8d77c1545da0683c0e1cb81ee", null ],
    [ "isNON_EXTLoad", "SelectionDAGNodes_8h.html#a15623094a1ed0cd7163dc786e44c87c9", null ],
    [ "isNON_TRUNCStore", "SelectionDAGNodes_8h.html#abfb4d7af9b241a75a155d468678c4fc1", null ],
    [ "isNormalLoad", "SelectionDAGNodes_8h.html#afaaeadcd82b42fc0d385a6247bf7bb52", null ],
    [ "isNormalStore", "SelectionDAGNodes_8h.html#a308088c2d65f8f3955f5fb0f6aca7ccc", null ],
    [ "isScalarToVector", "SelectionDAGNodes_8h.html#a0a31c08480b7e1029f824c35671f96b4", null ],
    [ "isSEXTLoad", "SelectionDAGNodes_8h.html#ac174dc465cbe0e04a0f5e41c0a422124", null ],
    [ "isTRUNCStore", "SelectionDAGNodes_8h.html#ac0304e470f9c07d4e04ee1c7b8c682a5", null ],
    [ "isUNINDEXEDLoad", "SelectionDAGNodes_8h.html#a7da84980dd2ee06405d74303cfb90485", null ],
    [ "isUNINDEXEDStore", "SelectionDAGNodes_8h.html#ab5c74add1b228292dae9d97d63b6f27b", null ],
    [ "isZEXTLoad", "SelectionDAGNodes_8h.html#a35edacef22fcaed7a8681fa573476131", null ]
];