LLVM: SelectionDAGDumper.cpp File Reference
LLVM API Documentation
SelectionDAGDumper.cpp File Reference
#include "llvm/CodeGen/SelectionDAG.h"
#include "ScheduleDAGSDNodes.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Assembly/Writer.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/DebugInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/GraphWriter.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetIntrinsicInfo.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetRegisterInfo.h"
Typedefs
typedef SmallPtrSet< const SDNode *, 128 > VisitedSDNodeSet
Functions
static void DumpNodes (const SDNode *N, unsigned indent, const SelectionDAG *G)
static void DumpNodesr (raw_ostream &OS, const SDNode *N, unsigned indent, const SelectionDAG *G, VisitedSDNodeSet &once)
static void printrWithDepthHelper (raw_ostream &OS, const SDNode *N, const SelectionDAG *G, unsigned depth, unsigned indent)
Typedef Documentation
typedef SmallPtrSet<const SDNode *, 128> VisitedSDNodeSet
Definition at line 554 of file SelectionDAGDumper.cpp.
Function Documentation
static void DumpNodes (const SDNode * N, unsigned indent, const SelectionDAG * G) static
Definition at line 522 of file SelectionDAGDumper.cpp.
References llvm::dbgs(), llvm::SDNode::dump(), G, llvm::SDValue::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOperand(), llvm::SDNode::hasOneUse(), i, and llvm::raw_ostream::indent().
Referenced by llvm::SelectionDAG::dump().
static void DumpNodesr (raw_ostream & OS, const SDNode * N, unsigned indent, const SelectionDAG * G, VisitedSDNodeSet & once) static
Definition at line 555 of file SelectionDAGDumper.cpp.
References llvm::SDValue::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOperand(), llvm::SDValue::getResNo(), i, llvm::raw_ostream::indent(), llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::SDNode::printr(), and llvm::NVPTX::PTXCvtMode::RN.
Referenced by llvm::SDNode::dumpr().
static void printrWithDepthHelper (raw_ostream & OS, const SDNode * N, const SelectionDAG * G, unsigned depth, unsigned indent) static
Definition at line 601 of file SelectionDAGDumper.cpp.
References G, llvm::SDValue::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOperand(), llvm::SDValue::getValueType(), i, llvm::raw_ostream::indent(), llvm::MVT::Other, and llvm::SDNode::print().
Referenced by llvm::SDNode::printrWithDepth().