LLVM: SIISelLowering.cpp File Reference
LLVM API Documentation
SIISelLowering.cpp File Reference
Custom DAG lowering for SI.
#include "SIISelLowering.h"
#include "AMDGPU.h"
#include "AMDILIntrinsicInfo.h"
#include "SIInstrInfo.h"
#include "SIMachineFunctionInfo.h"
#include "SIRegisterInfo.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAG.h"
#include "llvm/IR/Function.h"
Functions
static SDNode * findUser (SDValue Value, unsigned Opcode)
Helper function for LowerBRCOND.
static bool isVSrc (unsigned RegClass)
Test if RegClass is one of the VSrc classes.
static bool isSSrc (unsigned RegClass)
Test if RegClass is one of the SSrc classes.
static bool isNodeChanged (const SDNode *Node, const std::vector< SDValue > &Ops)
static unsigned SubIdx2Lane (unsigned Idx)
Helper function for adjustWritemask.
Variables
const uint64_t RSRC_DATA_FORMAT = 0xf00000000000LL
Detailed Description
Custom DAG lowering for SI.
Definition in file SIISelLowering.cpp.
Function Documentation
static SDNode* findUser (SDValue Value, unsigned Opcode) static
Helper function for LowerBRCOND.
Definition at line 607 of file SIISelLowering.cpp.
References llvm::ISD::ADD, llvm::ISD::BR, llvm::ISD::BRCOND, llvm::ISD::BUILD_PAIR, CC, llvm::ISD::CopyToReg, llvm::SmallVectorTemplateCommon< T >::data(), llvm::ISD::EXTRACT_ELEMENT, llvm::MemSDNode::getAddressSpace(), llvm::LoadSDNode::getBasePtr(), llvm::StoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SDNode::getConstantOperandVal(), llvm::SelectionDAG::getCopyToReg(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getNumValues(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getTargetConstant(), llvm::StoreSDNode::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::SelectionDAG::getVTList(), llvm::SDNode::getVTList(), llvm::SelectionDAG::getZExtOrTrunc(), llvm::HexagonISD::Hi, i, I, llvm::MVT::i1, llvm::MVT::i128, llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, j(), llvm::SPII::Load, llvm::AMDGPUTargetLowering::LowerMinMax(), llvm::AMDGPUTargetLowering::LowerSTORE(), llvm::SelectionDAG::MorphNodeTo(), llvm::MVT::Other, AMDGPUAS::PRIVATE_ADDRESS, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::AMDGPUISD::REGISTER_LOAD, llvm::AMDGPUISD::REGISTER_STORE, llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::AArch64ISD::Ret, llvm::ISD::SELECT, llvm::ISD::SETCC, llvm::ISD::SETNE, llvm::SmallVectorTemplateCommon< T >::size(), llvm::AMDGPUTargetLowering::SplitVectorStore(), llvm::ISD::SRA, llvm::ISD::SRL, llvm::SPII::Store, llvm::ISD::UNDEF, llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
static bool isNodeChanged (const SDNode * Node, const std::vector< SDValue > & Ops) static
Returns
true if Node's operands are different from the SDValue list Ops
Definition at line 1070 of file SIISelLowering.cpp.
References llvm::SITargetLowering::analyzeImmediate(), llvm::SIInstrInfo::commuteOpcode(), llvm::TargetMachine::getInstrInfo(), llvm::SelectionDAG::getMachineNode(), llvm::SDNode::getMachineOpcode(), llvm::SDValue::getNode(), llvm::MCInstrDesc::getNumDefs(), llvm::MCInstrDesc::getNumOperands(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOperand(), llvm::MCInstrDesc::getSize(), llvm::SelectionDAG::getTargetConstant(), llvm::TargetLoweringBase::getTargetMachine(), llvm::AMDGPU::getVOPe64(), llvm::SDNode::getVTList(), i, llvm::MVT::i32, llvm::MCInstrDesc::isCommutable(), isSSrc(), isVSrc(), llvm::MCInstrDesc::Opcode, llvm::MCInstrDesc::OpInfo, llvm::MCOperandInfo::RegClass, and TII.
static bool isSSrc (unsigned RegClass) static
Test if RegClass is one of the SSrc classes.
Definition at line 900 of file SIISelLowering.cpp.
Referenced by isNodeChanged().
static bool isVSrc (unsigned RegClass) static
Test if RegClass is one of the VSrc classes.
Definition at line 894 of file SIISelLowering.cpp.
Referenced by isNodeChanged().
static unsigned SubIdx2Lane (unsigned Idx) static
Helper function for adjustWritemask.
Definition at line 1224 of file SIISelLowering.cpp.
References llvm::TargetOpcode::COPY_TO_REGCLASS, llvm::countTrailingZeros(), llvm::TargetOpcode::EXTRACT_SUBREG, llvm::SDNode::getConstantOperandVal(), llvm::SelectionDAG::getMachineNode(), llvm::SDNode::getNumOperands(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getTargetConstant(), llvm::TargetLoweringBase::getValueType(), i, I, llvm::MVT::i32, llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::SelectionDAG::UpdateNodeOperands(), llvm::SDNode::use_begin(), llvm::SDNode::use_end(), and Users.
Variable Documentation
const uint64_t RSRC_DATA_FORMAT = 0xf00000000000LL
Definition at line 27 of file SIISelLowering.cpp.
Referenced by llvm::SITargetLowering::EmitInstrWithCustomInserter().