LLVM: Sink.cpp File Reference
LLVM API Documentation
Sink.cpp File Reference
#include "llvm/Transforms/Scalar.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/Analysis/Dominators.h"
#include "llvm/Analysis/LoopInfo.h"
#include "llvm/Analysis/ValueTracking.h"
#include "llvm/Assembly/Writer.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/Support/CFG.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "sink"
Functions
STATISTIC (NumSunk,"Number of instructions sunk")
STATISTIC (NumSinkIter,"Number of sinking iterations")
static bool isSafeToMove (Instruction *Inst, AliasAnalysis *AA, SmallPtrSet< Instruction *, 8 > &Stores)
Macro Definition Documentation
#define DEBUG_TYPE "sink"
Definition at line 15 of file Sink.cpp.
Function Documentation
static bool isSafeToMove (Instruction * Inst, AliasAnalysis * AA, SmallPtrSet< Instruction *, 8 > & Stores) static
Definition at line 156 of file Sink.cpp.
References llvm::DomTreeNodeBase< NodeT >::begin(), llvm::SmallPtrSet< PtrType, SmallSize >::begin(), llvm::dbgs(), DEBUG, llvm::DominatorTree::dominates(), llvm::DomTreeNodeBase< NodeT >::end(), llvm::SmallPtrSet< PtrType, SmallSize >::end(), llvm::AliasAnalysis::getLocation(), llvm::LoopInfo::getLoopFor(), llvm::AliasAnalysis::getModRefInfo(), llvm::DominatorTree::getNode(), llvm::Instruction::getParent(), llvm::BasicBlock::getUniquePredecessor(), I, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::isSafeToSpeculativelyExecute(), llvm::Instruction::mayWriteToMemory(), llvm::AliasAnalysis::Mod, llvm::Instruction::moveBefore(), llvm::succ_begin(), llvm::succ_end(), and llvm::WriteAsOperand().
STATISTIC (NumSunk , "Number of instructions sunk")
STATISTIC (NumSinkIter , "Number of sinking iterations")