LLVM: SjLjEHPrepare.cpp File Reference
LLVM API Documentation
SjLjEHPrepare.cpp File Reference
#include "llvm/CodeGen/Passes.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetLowering.h"
#include "llvm/Transforms/Scalar.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Local.h"
#include <set>
Macros
#define DEBUG_TYPE "sjljehprepare"
Functions
STATISTIC (NumInvokes,"Number of invokes replaced")
STATISTIC (NumSpilled,"Number of registers live across unwind edges")
static void MarkBlocksLiveIn (BasicBlock *BB, SmallPtrSet< BasicBlock *, 64 > &LiveBBs)
Macro Definition Documentation
#define DEBUG_TYPE "sjljehprepare"
Definition at line 15 of file SjLjEHPrepare.cpp.
Function Documentation
static void MarkBlocksLiveIn (BasicBlock * BB, SmallPtrSet< BasicBlock *, 64 > & LiveBBs) static
MarkBlocksLiveIn - Insert BB and all of its predescessors into LiveBBs until we reach blocks we've already seen.
Definition at line 139 of file SjLjEHPrepare.cpp.
References Align, llvm::Function::arg_begin(), llvm::Function::arg_end(), llvm::SmallVectorTemplateCommon< T >::back(), BB, llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::begin(), llvm::BasicBlock::begin(), llvm::SmallPtrSet< PtrType, SmallSize >::begin(), llvm::Function::begin(), llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::CallInst::Create(), llvm::ExtractValueInst::Create(), llvm::InsertValueInst::Create(), llvm::BranchInst::Create(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateInsertValue(), llvm::dbgs(), DEBUG, llvm::DemotePHIToStack(), llvm::DemoteRegToStack(), llvm::Intrinsic::donothing, llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::SmallPtrSetImpl::empty(), llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::end(), llvm::sys::path::end(), llvm::SmallPtrSet< PtrType, SmallSize >::end(), llvm::Function::end(), llvm::Instruction::eraseFromParent(), F(), llvm::ConstantInt::get(), llvm::UndefValue::get(), llvm::Function::getContext(), llvm::TargetLoweringBase::getDataLayout(), llvm::BasicBlock::getFirstInsertionPt(), llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::Type::getInt32Ty(), llvm::IRBuilderBase::getInt8PtrTy(), llvm::BasicBlock::getLandingPadInst(), llvm::Value::getName(), llvm::PHINode::getNumIncomingValues(), llvm::ExtractValueInst::getNumIndices(), llvm::Value::getNumUses(), llvm::Instruction::getParent(), getParent(), llvm::DataLayout::getPrefTypeAlignment(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::Value::hasOneUse(), i, I, llvm::ExtractValueInst::idx_begin(), llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::insert(), llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::Instruction::insertAfter(), llvm::makeArrayRef(), llvm::Instruction::moveBefore(), NC, llvm::next(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::pop_back(), llvm::pred_begin(), llvm::pred_end(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), Register, llvm::Value::replaceAllUsesWith(), llvm::CallInst::setDoesNotThrow(), llvm::User::setOperand(), llvm::ArrayRef< T >::size(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::SystemZISD::TM, llvm::Instruction::use_back(), llvm::Value::use_begin(), llvm::Value::use_empty(), llvm::Value::use_end(), and Users.
STATISTIC (NumInvokes , "Number of invokes replaced")
STATISTIC (NumSpilled , "Number of registers live across unwind edges")