LLVM: SourceMgr.cpp File Reference
LLVM API Documentation
SourceMgr.cpp File Reference
#include "llvm/Support/SourceMgr.h"
#include "llvm/ADT/OwningPtr.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/Twine.h"
#include "llvm/Support/Locale.h"
#include "llvm/Support/MemoryBuffer.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Support/system_error.h"
Functions
static LineNoCacheTy * getCache (void *Ptr)
static void buildFixItLine (std::string &CaretLine, std::string &FixItLine, ArrayRef< SMFixIt > FixIts, ArrayRef< char > SourceLine)
static void printSourceLine (raw_ostream &S, StringRef LineContents)
static bool isNonASCII (char c)
Variables
static const size_t TabStop = 8
Function Documentation
static void buildFixItLine (std::string & CaretLine, std::string & FixItLine, ArrayRef< SMFixIt > FixIts, ArrayRef< char > SourceLine) static
Definition at line 256 of file SourceMgr.cpp.
References llvm::ArrayRef< T >::begin(), llvm::sys::locale::columnWidth(), llvm::ArrayRef< T >::empty(), llvm::SMRange::End, llvm::ArrayRef< T >::end(), llvm::SMLoc::getPointer(), I, llvm::StringRef::npos, and llvm::SMRange::Start.
Referenced by llvm::SMDiagnostic::print().
static LineNoCacheTy* getCache (void * Ptr) static
Definition at line 36 of file SourceMgr.cpp.
Referenced by llvm::SourceMgr::getLineAndColumn(), and llvm::SourceMgr::~SourceMgr().
static bool isNonASCII (char c) static
Definition at line 344 of file SourceMgr.cpp.
Referenced by llvm::SMDiagnostic::print().
static void printSourceLine (raw_ostream & S, StringRef LineContents) static
Definition at line 326 of file SourceMgr.cpp.
References i, llvm::StringRef::size(), and TabStop.
Referenced by llvm::SMDiagnostic::print().
Variable Documentation
const size_t TabStop = 8 static
Definition at line 26 of file SourceMgr.cpp.
Referenced by llvm::SMDiagnostic::print(), and printSourceLine().