LLVM: SparcFrameLowering.cpp File Reference
LLVM API Documentation
SparcFrameLowering.cpp File Reference
#include "SparcFrameLowering.h"
#include "SparcInstrInfo.h"
#include "SparcMachineFunctionInfo.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Target/TargetOptions.h"
Functions
static bool LLVM_ATTRIBUTE_UNUSED verifyLeafProcRegUse (MachineRegisterInfo *MRI)
Variables
static cl::opt< bool > DisableLeafProc ("disable-sparc-leaf-proc", cl::init(false), cl::desc("Disable Sparc leaf procedure optimization."), cl::Hidden)
Function Documentation
static bool LLVM_ATTRIBUTE_UNUSED verifyLeafProcRegUse (MachineRegisterInfo * MRI) static
Definition at line 181 of file SparcFrameLowering.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::MachineFunction::begin(), llvm::MachineFunction::end(), llvm::MachineFunction::getFrameInfo(), llvm::MachineFunction::getRegInfo(), llvm::MachineFrameInfo::hasCalls(), llvm::SparcFrameLowering::hasFP(), llvm::MachineBasicBlock::isLiveIn(), llvm::MachineRegisterInfo::isPhysRegUsed(), L7, MRI, llvm::SparcFrameLowering::processFunctionBeforeCalleeSavedScan(), llvm::MachineBasicBlock::removeLiveIn(), llvm::MachineRegisterInfo::replaceRegWith(), llvm::MachineRegisterInfo::setPhysRegUnused(), and llvm::MachineFunction::verify().
Variable Documentation
cl::opt<bool> DisableLeafProc("disable-sparc-leaf-proc", cl::init(false), cl::desc("Disable Sparc leaf procedure optimization."), cl::Hidden) static
Referenced by llvm::SparcFrameLowering::processFunctionBeforeCalleeSavedScan().