LLVM: SSAUpdater.cpp File Reference
LLVM API Documentation
SSAUpdater.cpp File Reference
#include "llvm/Transforms/Utils/SSAUpdater.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/TinyPtrVector.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/Support/AlignOf.h"
#include "llvm/Support/Allocator.h"
#include "llvm/Support/CFG.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Local.h"
#include "llvm/Transforms/Utils/SSAUpdaterImpl.h"
Classes
class llvm::SSAUpdaterTraits< SSAUpdater >
class llvm::SSAUpdaterTraits< SSAUpdater >::PHI_iterator
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "ssaupdater"
Typedefs
typedef DenseMap< BasicBlock *, Value * > AvailableValsTy
Functions
static AvailableValsTy & getAvailableVals (void *AV)
static bool IsEquivalentPHI (PHINode *PHI, SmallDenseMap< BasicBlock *, Value *, 8 > &ValueMapping)
Macro Definition Documentation
#define DEBUG_TYPE "ssaupdater"
Definition at line 14 of file SSAUpdater.cpp.
Typedef Documentation
typedef DenseMap<BasicBlock*, Value*> AvailableValsTy
Definition at line 33 of file SSAUpdater.cpp.
Function Documentation
static AvailableValsTy& getAvailableVals (void * AV) static
Definition at line 34 of file SSAUpdater.cpp.
Referenced by llvm::SSAUpdater::AddAvailableValue(), llvm::SSAUpdaterTraits< SSAUpdater >::GetPHIValue(), llvm::SSAUpdater::HasValueForBlock(), and llvm::SSAUpdater::Initialize().
static bool IsEquivalentPHI (PHINode * PHI, SmallDenseMap< BasicBlock *, Value *, 8 > & ValueMapping) static
Definition at line 65 of file SSAUpdater.cpp.
References llvm::PHINode::getIncomingBlock(), llvm::PHINode::getIncomingValue(), llvm::PHINode::getNumIncomingValues(), i, and llvm::DenseMapBase< SmallDenseMap< KeyT, ValueT, InlineBuckets, KeyInfoT >, KeyT, ValueT, KeyInfoT >::size().
Referenced by llvm::SSAUpdater::GetValueInMiddleOfBlock().