LLVM: StackMaps.cpp File Reference
LLVM API Documentation
StackMaps.cpp File Reference
#include "llvm/CodeGen/StackMaps.h"
#include "llvm/CodeGen/AsmPrinter.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCObjectFileInfo.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetOpcodes.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetRegisterInfo.h"
#include <iterator>
Macros
#define DEBUG_TYPE "stackmaps"
Functions
static MachineInstr::const_mop_iterator getStackMapEndMOP (MachineInstr::const_mop_iterator MOI, MachineInstr::const_mop_iterator MOE)
Macro Definition Documentation
#define DEBUG_TYPE "stackmaps"
Definition at line 10 of file StackMaps.cpp.
Function Documentation
static MachineInstr::const_mop_iterator getStackMapEndMOP (MachineInstr::const_mop_iterator MOI, MachineInstr::const_mop_iterator MOE) static
Definition at line 114 of file StackMaps.cpp.
References llvm::MachineOperand::isImplicit(), llvm::MachineOperand::isReg(), and llvm::MachineOperand::isRegMask().
Referenced by llvm::StackMaps::recordPatchPoint(), and llvm::StackMaps::recordStackMap().