LLVM: StripSymbols.cpp File Reference
LLVM API Documentation
StripSymbols.cpp File Reference
#include "llvm/Transforms/IPO.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/DebugInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/TypeFinder.h"
#include "llvm/IR/ValueSymbolTable.h"
#include "llvm/Pass.h"
#include "llvm/Transforms/Utils/Local.h"
Functions
INITIALIZE_PASS (StripSymbols,"strip","Strip all symbols from a module", false, false) ModulePass *llvm
INITIALIZE_PASS (StripNonDebugSymbols,"strip-nondebug","Strip all symbols, except dbg symbols, from a module", false, false) ModulePass *llvm
INITIALIZE_PASS (StripDebugDeclare,"strip-debug-declare","Strip all llvm.dbg.declare intrinsics", false, false) ModulePass *llvm
INITIALIZE_PASS (StripDeadDebugInfo,"strip-dead-debug-info","Strip debug info for unused symbols", false, false) ModulePass *llvm
static bool OnlyUsedBy (Value *V, Value *Usr)
OnlyUsedBy - Return true if V is only used by Usr.
static void RemoveDeadConstant (Constant *C)
static void StripSymtab (ValueSymbolTable &ST, bool PreserveDbgInfo)
static void StripTypeNames (Module &M, bool PreserveDbgInfo)
static void findUsedValues (GlobalVariable *LLVMUsed, SmallPtrSet< const GlobalValue *, 8 > &UsedValues)
Find values that are marked as llvm.used.
static bool StripSymbolNames (Module &M, bool PreserveDbgInfo)
StripSymbolNames - Strip symbol names.
Function Documentation
static void findUsedValues (GlobalVariable * LLVMUsed, SmallPtrSet< const GlobalValue *, 8 > & UsedValues) static
Find values that are marked as llvm.used.
Definition at line 194 of file StripSymbols.cpp.
References llvm::GlobalVariable::getInitializer(), llvm::User::getNumOperands(), llvm::User::getOperand(), i, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), and llvm::Value::stripPointerCasts().
Referenced by StripSymbolNames().
INITIALIZE_PASS (StripSymbols , "strip" , "Strip all symbols from a module" , false , false)
Definition at line 101 of file StripSymbols.cpp.
INITIALIZE_PASS (StripNonDebugSymbols , "strip-nondebug" , "Strip all symbols, except dbg symbols, from a module" , false , false)
Definition at line 109 of file StripSymbols.cpp.
INITIALIZE_PASS (StripDebugDeclare , "strip-debug-declare" , "Strip all llvm.dbg.declare intrinsics" , false , false)
Definition at line 118 of file StripSymbols.cpp.
INITIALIZE_PASS (StripDeadDebugInfo , "strip-dead-debug-info" , "Strip debug info for unused symbols" , false , false)
Definition at line 126 of file StripSymbols.cpp.
static bool OnlyUsedBy (Value * V, Value * Usr) static
OnlyUsedBy - Return true if V is only used by Usr.
Definition at line 134 of file StripSymbols.cpp.
References I, llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by RemoveDeadConstant().
static void RemoveDeadConstant (Constant * C) static
Definition at line 143 of file StripSymbols.cpp.
References llvm::Constant::destroyConstant(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Value::getType(), i, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), OnlyUsedBy(), and llvm::Value::use_empty().
Referenced by StripSymbolNames().
static bool StripSymbolNames (Module & M, bool PreserveDbgInfo) static
StripSymbolNames - Strip symbol names.
Definition at line 208 of file StripSymbols.cpp.
References llvm::Module::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::DebugInfoFinder::compile_unit_begin(), llvm::DebugInfoFinder::compile_unit_end(), llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::Module::end(), llvm::Instruction::eraseFromParent(), llvm::Function::eraseFromParent(), F(), findUsedValues(), llvm::MDNode::get(), llvm::CallInst::getArgOperand(), llvm::Module::getContext(), llvm::DIArray::getElement(), llvm::Module::getFunction(), llvm::Module::getGlobalVariable(), llvm::DICompileUnit::getGlobalVariables(), llvm::DIArray::getNumElements(), llvm::DICompileUnit::getSubprograms(), llvm::Module::global_begin(), llvm::Module::global_end(), i, I, llvm::DenseSet< ValueT, ValueInfoT >::insert(), M, llvm::DebugInfoFinder::processModule(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::RecursivelyDeleteTriviallyDeadInstructions(), RemoveDeadConstant(), llvm::StripDebugInfo(), StripSymtab(), StripTypeNames(), llvm::Value::use_back(), llvm::Value::use_empty(), and llvm::DICompileUnit::Verify().
static void StripSymtab (ValueSymbolTable & ST, bool PreserveDbgInfo) static
Definition at line 165 of file StripSymbols.cpp.
References llvm::ValueSymbolTable::begin(), llvm::ValueSymbolTable::end(), llvm::Value::getName(), llvm::Value::setName(), and llvm::StringRef::startswith().
Referenced by StripSymbolNames().
static void StripTypeNames (Module & M, bool PreserveDbgInfo) static
Definition at line 178 of file StripSymbols.cpp.
References llvm::StringRef::empty(), llvm::StructType::getName(), i, llvm::StructType::isLiteral(), llvm::TypeFinder::run(), llvm::StructType::setName(), llvm::TypeFinder::size(), and llvm::StringRef::startswith().
Referenced by StripSymbolNames().