LLVM: StringRef.cpp File Reference
LLVM API Documentation
StringRef.cpp File Reference
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/APInt.h"
#include "llvm/ADT/Hashing.h"
#include "llvm/ADT/OwningPtr.h"
#include "llvm/ADT/edit_distance.h"
#include <bitset>
Functions
static char ascii_tolower (char x)
static char ascii_toupper (char x)
static bool ascii_isdigit (char x)
static int ascii_strncasecmp (const char *LHS, const char *RHS, size_t Length)
static unsigned GetAutoSenseRadix (StringRef &Str)
Function Documentation
static bool ascii_isdigit (char x) static
Definition at line 36 of file StringRef.cpp.
Referenced by llvm::StringRef::compare_numeric(), and llvm::LessRecordRegister::RecordParts::RecordParts().
static int ascii_strncasecmp (const char * LHS, const char * RHS, size_t Length) static
Definition at line 42 of file StringRef.cpp.
References ascii_tolower(), and I.
Referenced by llvm::StringRef::compare_lower(), llvm::StringRef::endswith_lower(), and llvm::StringRef::startswith_lower().
static char ascii_tolower (char x) static
Definition at line 24 of file StringRef.cpp.
Referenced by ascii_strncasecmp(), and llvm::StringRef::lower().
static char ascii_toupper (char x) static
Definition at line 30 of file StringRef.cpp.
Referenced by llvm::StringRef::upper().
static unsigned GetAutoSenseRadix (StringRef & Str) static
Definition at line 315 of file StringRef.cpp.
References llvm::StringRef::startswith(), and llvm::StringRef::substr().
Referenced by llvm::StringRef::getAsInteger(), and llvm::getAsUnsignedInteger().