LLVM: llvm::yaml::ScalarTraits< MCModuleYAML::OpcodeEnum > Struct Template Reference
LLVM API Documentation
llvm::yaml::ScalarTraits< MCModuleYAML::OpcodeEnum > Struct Template Reference
Static Public Member Functions
static void output (const MCModuleYAML::OpcodeEnum &, void *, llvm::raw_ostream &)
static StringRef input (StringRef, void *, MCModuleYAML::OpcodeEnum &)
Detailed Description
template<>
struct llvm::yaml::ScalarTraits< MCModuleYAML::OpcodeEnum >
Definition at line 167 of file MCModuleYAML.cpp.
Member Function Documentation
StringRef llvm::yaml::ScalarTraits< MCModuleYAML::OpcodeEnum >::input (StringRef Scalar, void * Ctx, MCModuleYAML::OpcodeEnum & Val) static
Definition at line 261 of file MCModuleYAML.cpp.
References llvm::ARM_PROC::A, llvm::MCDataAtom::addData(), llvm::MCTextAtom::addInst(), llvm::MCInst::addOperand(), llvm::MCBasicBlock::addPredecessor(), llvm::MCModuleYAML::BasicBlock::Address, llvm::MCBasicBlock::addSuccessor(), llvm::MCModule::atom_begin(), llvm::MCModule::atom_end(), llvm::MCModuleYAML::Module::Atoms, llvm::MCModuleYAML::Function::BasicBlocks, BB, llvm::MCFunction::begin(), llvm::MCFunction::createBlock(), llvm::MCModule::createDataAtom(), llvm::MCModule::createFunction(), llvm::MCModule::createTextAtom(), llvm::X86II::DA, llvm::MCModuleYAML::Atom::Data, llvm::MCAtom::DataAtom, llvm::MCFunction::end(), F(), llvm::MCFunction::find(), llvm::raw_ostream::flush(), llvm::MCModule::func_begin(), llvm::MCModule::func_end(), llvm::MCModuleYAML::Module::Functions, llvm::MCAtom::getBeginAddr(), llvm::MCAtom::getEndAddr(), llvm::MCBasicBlock::getInsts(), llvm::MCAtom::getKind(), llvm::MCFunction::getName(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), i, llvm::ARM_PROC::IE, llvm::MCDecodedInst::Inst, llvm::MCModuleYAML::Atom::Insts, llvm_unreachable, llvm::A64CC::MI, llvm::MCModuleYAML::Function::Name, llvm::MCBasicBlock::pred_begin(), llvm::MCBasicBlock::pred_end(), llvm::MCModuleYAML::BasicBlock::Preds, llvm::MCInst::setOpcode(), llvm::MCModuleYAML::Atom::Size, llvm::MCDecodedInst::Size, llvm::SmallVectorTemplateCommon< T >::size(), llvm::MCModuleYAML::Atom::StartAddress, llvm::MCBasicBlock::succ_begin(), llvm::MCBasicBlock::succ_end(), llvm::MCModuleYAML::BasicBlock::Succs, llvm::X86II::TA, llvm::MCAtom::TextAtom, and llvm::MCModuleYAML::Atom::Type.
void llvm::yaml::ScalarTraits< MCModuleYAML::OpcodeEnum >::output (const MCModuleYAML::OpcodeEnum & Val, void * Ctx, llvm::raw_ostream & Out) static
Definition at line 254 of file MCModuleYAML.cpp.
The documentation for this struct was generated from the following file:
MCModuleYAML.cpp