LLVM: llvm::PostDominatorTree Struct Reference
LLVM API Documentation
llvm::PostDominatorTree Struct Reference
#include <PostDominators.h>
Public Member Functions
PostDominatorTree ()
~PostDominatorTree ()
virtual bool runOnFunction (Function &F)
virtual void getAnalysisUsage (AnalysisUsage &AU) const
const std::vector< BasicBlock * > & getRoots () const
DomTreeNode * getRootNode () const
DomTreeNode * operator[] (BasicBlock *BB) const
DomTreeNode * getNode (BasicBlock *BB) const
bool dominates (DomTreeNode *A, DomTreeNode *B) const
bool dominates (const BasicBlock *A, const BasicBlock *B) const
bool properlyDominates (const DomTreeNode *A, DomTreeNode *B) const
bool properlyDominates (BasicBlock *A, BasicBlock *B) const
BasicBlock * findNearestCommonDominator (BasicBlock *A, BasicBlock *B)
const BasicBlock * findNearestCommonDominator (const BasicBlock *A, const BasicBlock *B)
virtual void releaseMemory ()
virtual void print (raw_ostream &OS, const Module *) const
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const
createPrinterPass - Get a function printer pass.
virtual void assignPassManager (PMStack &PMS, PassManagerType T)
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Public Attributes
DominatorTreeBase< BasicBlock > * DT
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Detailed Description
PostDominatorTree Class - Concrete subclass of DominatorTree that is used to compute the a post-dominator tree.
Definition at line 24 of file PostDominators.h.
Constructor & Destructor Documentation
llvm::PostDominatorTree::PostDominatorTree () inline
Definition at line 28 of file PostDominators.h.
References F(), llvm::PassRegistry::getPassRegistry(), llvm::initializePostDominatorTreePass(), runOnFunction(), and ~PostDominatorTree().
Referenced by llvm::createPostDomTree().
PostDominatorTree::~PostDominatorTree ()
Definition at line 39 of file PostDominators.cpp.
References DT.
Referenced by PostDominatorTree().
Member Function Documentation
bool llvm::PostDominatorTree::dominates (DomTreeNode * A, DomTreeNode * B) const inline
Definition at line 57 of file PostDominators.h.
References llvm::DominatorTreeBase< NodeT >::dominates().
bool llvm::PostDominatorTree::dominates (const BasicBlock * A, const BasicBlock * B) const inline
Definition at line 61 of file PostDominators.h.
References llvm::DominatorTreeBase< NodeT >::dominates().
BasicBlock* llvm::PostDominatorTree::findNearestCommonDominator (BasicBlock * A, BasicBlock * B) inline
Definition at line 73 of file PostDominators.h.
References llvm::DominatorTreeBase< NodeT >::findNearestCommonDominator().
const BasicBlock* llvm::PostDominatorTree::findNearestCommonDominator (const BasicBlock * A, const BasicBlock * B) inline
Definition at line 77 of file PostDominators.h.
References llvm::DominatorTreeBase< NodeT >::findNearestCommonDominator().
virtual void llvm::PostDominatorTree::getAnalysisUsage (AnalysisUsage &) const inline virtual
getAnalysisUsage - This function should be overriden by passes that need analysis information to do their job. If a pass specifies that it uses a particular analysis result to this function, it can then use the getAnalysis<AnalysisType>() function, below.
Reimplemented from llvm::Pass.
Definition at line 37 of file PostDominators.h.
References llvm::AnalysisUsage::setPreservesAll().
DomTreeNode* llvm::PostDominatorTree::getNode (BasicBlock * BB) const inline
Definition at line 53 of file PostDominators.h.
References llvm::DominatorTreeBase< NodeT >::getNode().
DomTreeNode* llvm::PostDominatorTree::getRootNode () const inline
Definition at line 45 of file PostDominators.h.
References llvm::DominatorTreeBase< NodeT >::getRootNode().
Referenced by llvm::GraphTraits< PostDominatorTree * >::getEntryNode(), and llvm::DOTGraphTraits< PostDominatorTree * >::getNodeLabel().
const std::vector<BasicBlock*>& llvm::PostDominatorTree::getRoots () const inline
Definition at line 41 of file PostDominators.h.
References llvm::DominatorBase< NodeT >::getRoots().
DomTreeNode* llvm::PostDominatorTree::operator[] (BasicBlock * BB) const inline
Definition at line 49 of file PostDominators.h.
References llvm::DominatorTreeBase< NodeT >::getNode().
void PostDominatorTree::print (raw_ostream & O, const Module * M) const virtual
print - Print out the internal state of the pass. This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 43 of file PostDominators.cpp.
References DT.
Referenced by releaseMemory().
bool llvm::PostDominatorTree::properlyDominates (const DomTreeNode * A, DomTreeNode * B) const inline
Definition at line 65 of file PostDominators.h.
References llvm::DominatorTreeBase< NodeT >::properlyDominates().
bool llvm::PostDominatorTree::properlyDominates (BasicBlock * A, BasicBlock * B) const inline
Definition at line 69 of file PostDominators.h.
References llvm::DominatorTreeBase< NodeT >::properlyDominates().
virtual void llvm::PostDominatorTree::releaseMemory () inline virtual
releaseMemory() - This member can be implemented by a pass if it wants to be able to release its memory when it is no longer needed. The default behavior of passes is to hold onto memory for the entire duration of their lifetime (which is the entire compile time). For pipelined passes, this is not a big deal because that memory gets recycled every time the pass is invoked on another program unit. For IP passes, it is more important to free memory when it is unused.
Optionally implement this function to release pass memory when it is no longer used.
Reimplemented from llvm::Pass.
Definition at line 82 of file PostDominators.h.
References llvm::createPostDomTree(), print(), and llvm::DominatorTreeBase< NodeT >::releaseMemory().
virtual bool llvm::PostDominatorTree::runOnFunction (Function & F) virtual
runOnFunction - Virtual method overriden by subclasses to do the per-function processing of the pass.
Implements llvm::FunctionPass.
Referenced by PostDominatorTree().
Member Data Documentation
DominatorTreeBase<BasicBlock>* llvm::PostDominatorTree::DT
Definition at line 26 of file PostDominators.h.
Referenced by print(), and ~PostDominatorTree().
char PostDominatorTree::ID = 0 static
Definition at line 25 of file PostDominators.h.
The documentation for this struct was generated from the following files:
PostDominators.h
PostDominators.cpp