LLVM: LTOCodeGenerator Struct Reference
LLVM API Documentation
LTOCodeGenerator Struct Reference
#include <LTOCodeGenerator.h>
Public Member Functions
LTOCodeGenerator ()
~LTOCodeGenerator ()
bool addModule (struct LTOModule *, std::string &errMsg)
void setTargetOptions (llvm::TargetOptions options)
void setDebugInfo (lto_debug_model)
void setCodePICModel (lto_codegen_model)
void setCpu (const char *mCpu)
void addMustPreserveSymbol (const char *sym)
void setCodeGenDebugOptions (const char *opts)
void parseCodeGenDebugOptions ()
bool writeMergedModules (const char *path, std::string &errMsg)
bool compile_to_file (const char **name, bool disableOpt, bool disableInline, bool disableGVNLoadPRE, std::string &errMsg)
const void * compile (size_t *length, bool disableOpt, bool disableInline, bool disableGVNLoadPRE, std::string &errMsg)
Static Public Member Functions
static const char * getVersionString ()
Detailed Description
LTOCodeGenerator - C++ class which implements the opaque lto_code_gen_t type.
Definition at line 61 of file LTOCodeGenerator.h.
Constructor & Destructor Documentation
LTOCodeGenerator::LTOCodeGenerator ()
Definition at line 62 of file LTOCodeGenerator.cpp.
LTOCodeGenerator::~LTOCodeGenerator ()
Definition at line 69 of file LTOCodeGenerator.cpp.
References llvm::Linker::deleteModule(), llvm::LibFunc::free, I, llvm::initializeArgPromotionPass(), llvm::initializeCFGSimplifyPassPass(), llvm::initializeConstantMergePass(), llvm::initializeDAHPass(), llvm::initializeDCEPass(), llvm::initializeFunctionAttrsPass(), llvm::initializeGlobalDCEPass(), llvm::initializeGlobalOptPass(), llvm::initializeGlobalsModRefPass(), llvm::initializeGVNPass(), llvm::initializeInstCombinerPass(), llvm::initializeInternalizePassPass(), llvm::initializeIPSCCPPass(), llvm::initializeJumpThreadingPass(), llvm::initializeLICMPass(), llvm::initializeMemCpyOptPass(), llvm::initializePruneEHPass(), llvm::initializeSimpleInlinerPass(), llvm::initializeSROA_DTPass(), llvm::initializeSROA_SSAUpPass(), and llvm::initializeSROAPass().
Member Function Documentation
bool LTOCodeGenerator::addModule (struct LTOModule * mod, std::string & errMsg)
Definition at line 113 of file LTOCodeGenerator.cpp.
References LTOModule::getAsmUndefinedRefs(), LTOModule::getLLVVMModule(), i, llvm::Linker::linkInModule(), and ret().
void LTOCodeGenerator::addMustPreserveSymbol (const char * sym) inline
Definition at line 76 of file LTOCodeGenerator.h.
References compile, and opts.
const void * LTOCodeGenerator::compile (size_t * length, bool disableOpt, bool disableInline, bool disableGVNLoadPRE, std::string & errMsg)
Definition at line 237 of file LTOCodeGenerator.cpp.
References Aggressive, llvm::ArrayRef< T >::begin(), compile_to_file(), llvm::StringMap< ValueTy, AllocatorTy >::count(), llvm::Target::createTargetMachine(), llvm::StringRef::data(), llvm::Reloc::Default, llvm::Reloc::DynamicNoPIC, llvm::ArrayRef< T >::end(), llvm::Triple::getArch(), llvm::MemoryBuffer::getBufferSize(), llvm::MemoryBuffer::getBufferStart(), llvm::SubtargetFeatures::getDefaultSubtargetFeatures(), llvm::sys::getDefaultTargetTriple(), llvm::Linker::getModule(), llvm::Value::getName(), llvm::Mangler::getNameWithPrefix(), llvm::SubtargetFeatures::getString(), llvm::Module::getTargetTriple(), llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::GlobalValue::isDeclaration(), llvm::Triple::isOSDarwin(), LTO_CODEGEN_PIC_MODEL_DYNAMIC, LTO_CODEGEN_PIC_MODEL_DYNAMIC_NO_PIC, LTO_CODEGEN_PIC_MODEL_STATIC, llvm::Reloc::PIC_, RelocModel(), llvm::LibFunc::remove, llvm::Reloc::Static, llvm::OwningPtr< T >::take(), llvm::Triple::x86, and llvm::Triple::x86_64.
bool LTOCodeGenerator::compile_to_file (const char ** name, bool disableOpt, bool disableInline, bool disableGVNLoadPRE, std::string & errMsg)
Definition at line 200 of file LTOCodeGenerator.cpp.
References llvm::SmallString< InternalLen >::c_str(), llvm::sys::fs::createTemporaryFile(), llvm::error_code::message(), and llvm::LibFunc::remove.
Referenced by compile().
const char * LTOCodeGenerator::getVersionString () static
Definition at line 54 of file LTOCodeGenerator.cpp.
void LTOCodeGenerator::parseCodeGenDebugOptions ()
Definition at line 516 of file LTOCodeGenerator.cpp.
References llvm::cl::ParseCommandLineOptions().
void LTOCodeGenerator::setCodeGenDebugOptions (const char * options)
setCodeGenDebugOptions - Set codegen debugging options to aid in debugging LTO problems.
Definition at line 505 of file LTOCodeGenerator.cpp.
References llvm::getToken(), and llvm::LibFunc::strdup.
void LTOCodeGenerator::setCodePICModel (lto_codegen_model model)
Definition at line 157 of file LTOCodeGenerator.cpp.
References llvm_unreachable, LTO_CODEGEN_PIC_MODEL_DYNAMIC, LTO_CODEGEN_PIC_MODEL_DYNAMIC_NO_PIC, LTO_CODEGEN_PIC_MODEL_STATIC, and model.
void LTOCodeGenerator::setCpu (const char * mCpu) inline
Definition at line 74 of file LTOCodeGenerator.h.
void LTOCodeGenerator::setDebugInfo (lto_debug_model debug)
Definition at line 144 of file LTOCodeGenerator.cpp.
References llvm_unreachable, LTO_DEBUG_MODEL_DWARF, and LTO_DEBUG_MODEL_NONE.
void LTOCodeGenerator::setTargetOptions (llvm::TargetOptions options)
Definition at line 123 of file LTOCodeGenerator.cpp.
References llvm::TargetOptions::AllowFPOpFusion, llvm::TargetOptions::DisableTailCalls, llvm::TargetOptions::EnableSegmentedStacks, llvm::TargetOptions::FloatABIType, llvm::TargetOptions::GuaranteedTailCallOpt, llvm::TargetOptions::HonorSignDependentRoundingFPMathOption, llvm::TargetOptions::LessPreciseFPMADOption, llvm::TargetOptions::NoFramePointerElim, llvm::TargetOptions::NoInfsFPMath, llvm::TargetOptions::NoNaNsFPMath, llvm::TargetOptions::NoZerosInBSS, llvm::TargetOptions::PositionIndependentExecutable, llvm::TargetOptions::StackAlignmentOverride, llvm::TargetOptions::TrapFuncName, llvm::TargetOptions::UnsafeFPMath, llvm::TargetOptions::UseInitArray, and llvm::TargetOptions::UseSoftFloat.
bool LTOCodeGenerator::writeMergedModules (const char * path, std::string & errMsg)
Definition at line 168 of file LTOCodeGenerator.cpp.
References llvm::raw_fd_ostream::clear_error(), llvm::raw_fd_ostream::close(), llvm::sys::fs::F_Binary, llvm::Linker::getModule(), llvm::raw_fd_ostream::has_error(), llvm::tool_output_file::keep(), llvm::tool_output_file::os(), and llvm::WriteBitcodeToFile().
The documentation for this struct was generated from the following files:
LTOCodeGenerator.h
LTOCodeGenerator.cpp