LLVM: llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t > Struct Template Reference
LLVM API Documentation
llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t > Struct Template Reference
#include <PatternMatch.h>
Public Member Functions
MaxMin_match (const LHS_t &LHS, const RHS_t &RHS)
template<typename OpTy >
bool match (OpTy *V)
Public Attributes
LHS_t L
RHS_t R
Detailed Description
template<typename CmpInst_t, typename LHS_t, typename RHS_t, typename Pred_t>
struct llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t >
Definition at line 847 of file PatternMatch.h.
Constructor & Destructor Documentation
template<typename CmpInst_t, typename LHS_t, typename RHS_t, typename Pred_t> llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t >::MaxMin_match (const LHS_t & LHS, const RHS_t & RHS) inline
Definition at line 851 of file PatternMatch.h.
Member Function Documentation
template<typename CmpInst_t, typename LHS_t, typename RHS_t, typename Pred_t> template<typename OpTy > bool llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t >::match (OpTy * V) inline
Definition at line 855 of file PatternMatch.h.
References llvm::dyn_cast(), llvm::SelectInst::getCondition(), llvm::SelectInst::getFalseValue(), llvm::SelectInst::getTrueValue(), and llvm::PatternMatch::match().
Member Data Documentation
template<typename CmpInst_t, typename LHS_t, typename RHS_t, typename Pred_t> LHS_t llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t >::L
Definition at line 848 of file PatternMatch.h.
template<typename CmpInst_t, typename LHS_t, typename RHS_t, typename Pred_t> RHS_t llvm::PatternMatch::MaxMin_match< CmpInst_t, LHS_t, RHS_t, Pred_t >::R
Definition at line 849 of file PatternMatch.h.
The documentation for this struct was generated from the following file:
PatternMatch.h