LLVM: llvm::R600RegisterInfo Struct Reference
LLVM API Documentation
llvm::R600RegisterInfo Struct Reference
#include <R600RegisterInfo.h>
Public Member Functions
R600RegisterInfo (AMDGPUTargetMachine &tm)
virtual BitVector getReservedRegs (const MachineFunction &MF) const
virtual const TargetRegisterClass * getISARegClass (const TargetRegisterClass *RC) const
unsigned getHWRegChan (unsigned reg) const
get the HW encoding for a register's channel.
virtual unsigned getHWRegIndex (unsigned Reg) const
virtual const TargetRegisterClass * getCFGStructurizerRegClass (MVT VT) const
get the register class of the specified type to use in the CFGStructurizer
virtual const RegClassWeight & getRegClassWeight (const TargetRegisterClass *RC) const
virtual bool isPhysRegLiveAcrossClauses (unsigned Reg) const
Public Member Functions inherited from llvm::AMDGPURegisterInfo
AMDGPURegisterInfo (TargetMachine &tm)
unsigned getSubRegFromChannel (unsigned Channel) const
const uint16_t * getCalleeSavedRegs (const MachineFunction *MF) const
void eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS) const
unsigned getFrameRegister (const MachineFunction &MF) const
unsigned getIndirectSubReg (unsigned IndirectIndex) const
Public Attributes
AMDGPUTargetMachine & TM
RegClassWeight RCW
Public Attributes inherited from llvm::AMDGPURegisterInfo
TargetMachine & TM
Additional Inherited Members
Static Public Attributes inherited from llvm::AMDGPURegisterInfo
static const uint16_t CalleeSavedReg = AMDGPU::NoRegister
Detailed Description
Definition at line 25 of file R600RegisterInfo.h.
Constructor & Destructor Documentation
R600RegisterInfo::R600RegisterInfo (AMDGPUTargetMachine & tm)
Definition at line 23 of file R600RegisterInfo.cpp.
References RCW, llvm::RegClassWeight::RegWeight, and llvm::RegClassWeight::WeightLimit.
Member Function Documentation
const TargetRegisterClass * R600RegisterInfo::getCFGStructurizerRegClass (MVT VT) const virtual
get the register class of the specified type to use in the CFGStructurizer
Reimplemented from llvm::AMDGPURegisterInfo.
Definition at line 76 of file R600RegisterInfo.cpp.
References llvm::MVT::i32, and llvm::MVT::SimpleTy.
unsigned R600RegisterInfo::getHWRegChan (unsigned reg) const
get the HW encoding for a register's channel.
Definition at line 68 of file R600RegisterInfo.cpp.
References HW_CHAN_SHIFT.
Referenced by llvm::createR600ExpandSpecialInstrsPass(), llvm::R600InstrInfo::fitsConstReadLimitations(), and llvm::R600InstrInfo::getSrcs().
unsigned R600RegisterInfo::getHWRegIndex (unsigned Reg) const virtual
Reimplemented from llvm::AMDGPURegisterInfo.
Definition at line 72 of file R600RegisterInfo.cpp.
References GET_REG_INDEX.
const TargetRegisterClass * R600RegisterInfo::getISARegClass (const TargetRegisterClass * RC) const virtual
Parameters
RC is an AMDIL reg class.
Returns
the R600 reg class that is equivalent to RC.
Reimplemented from llvm::AMDGPURegisterInfo.
Definition at line 59 of file R600RegisterInfo.cpp.
References llvm::TargetRegisterClass::getID().
const RegClassWeight & R600RegisterInfo::getRegClassWeight (const TargetRegisterClass * RC) const virtual
Definition at line 84 of file R600RegisterInfo.cpp.
References RCW.
BitVector R600RegisterInfo::getReservedRegs (const MachineFunction & MF) const virtual
Reimplemented from llvm::AMDGPURegisterInfo.
Definition at line 28 of file R600RegisterInfo.cpp.
References llvm::sys::path::begin(), llvm::sys::path::end(), llvm::AMDGPUTargetMachine::getInstrInfo(), I, llvm::R600InstrInfo::reserveIndirectRegisters(), llvm::BitVector::set(), TII, and TM.
bool R600RegisterInfo::isPhysRegLiveAcrossClauses (unsigned Reg) const virtual
Definition at line 89 of file R600RegisterInfo.cpp.
References llvm::TargetRegisterInfo::isVirtualRegister().
Referenced by llvm::R600InstrInfo::isLegalToSplitMBBAt().
Member Data Documentation
RegClassWeight llvm::R600RegisterInfo::RCW
Definition at line 27 of file R600RegisterInfo.h.
Referenced by getRegClassWeight(), and R600RegisterInfo().
AMDGPUTargetMachine& llvm::R600RegisterInfo::TM
Definition at line 26 of file R600RegisterInfo.h.
Referenced by getReservedRegs().
The documentation for this struct was generated from the following files:
R600RegisterInfo.h
R600RegisterInfo.cpp