LLVM: llvm::DwarfAccelTable::HashDataContents Struct Reference
LLVM API Documentation
llvm::DwarfAccelTable::HashDataContents Struct Reference
#include <DwarfAccelTable.h>
Public Member Functions
HashDataContents (DIE *D, char Flags)
void print (raw_ostream &O) const
Public Attributes
DIE * Die
char Flags
Detailed Description
Definition at line 167 of file DwarfAccelTable.h.
Constructor & Destructor Documentation
llvm::DwarfAccelTable::HashDataContents::HashDataContents (DIE * D, char Flags) inline
Definition at line 171 of file DwarfAccelTable.h.
Member Function Documentation
void llvm::DwarfAccelTable::HashDataContents::print (raw_ostream & O) const inline
Definition at line 173 of file DwarfAccelTable.h.
References llvm::DwarfAccelTable::AddName(), llvm::dbgs(), llvm::DwarfAccelTable::dump(), llvm::DwarfAccelTable::Emit(), llvm::DwarfAccelTable::FinalizeTable(), llvm::format(), llvm::DIE::getOffset(), llvm::DIE::getTag(), i, LLVM_DELETED_FUNCTION, llvm::MCSymbol::print(), llvm::DwarfAccelTable::print(), S, llvm::ArrayRef< T >::size(), llvm::dwarf::TagString(), and llvm::DwarfAccelTable::~DwarfAccelTable().
Member Data Documentation
DIE* llvm::DwarfAccelTable::HashDataContents::Die
Definition at line 168 of file DwarfAccelTable.h.
Referenced by compareDIEs().
char llvm::DwarfAccelTable::HashDataContents::Flags
Definition at line 169 of file DwarfAccelTable.h.
The documentation for this struct was generated from the following file:
DwarfAccelTable.h