LLVM: llvm::ilist_traits< Argument > Struct Template Reference
LLVM API Documentation
llvm::ilist_traits< Argument > Struct Template Reference
#include <Function.h>
Public Member Functions
Argument * createSentinel () const
Argument * provideInitialHead () const
Argument * ensureHead (Argument *) const
Public Member Functions inherited from llvm::SymbolTableListTraits< Argument, Function >
SymbolTableListTraits ()
Function * getListOwner ()
void addNodeToList (Argument *V)
void removeNodeFromList (Argument *V)
void transferNodesFromList (ilist_traits< Argument > &L2, ilist_iterator< Argument > first, ilist_iterator< Argument > last)
void setSymTabObject (TPtr *, TPtr)
Public Member Functions inherited from llvm::ilist_node_traits< NodeTy >
void addNodeToList (NodeTy *)
void removeNodeFromList (NodeTy *)
void transferNodesFromList (ilist_node_traits &, ilist_iterator< NodeTy >, ilist_iterator< NodeTy >)
Static Public Member Functions
static void destroySentinel (Argument *)
static void noteHead (Argument *, Argument *)
static ValueSymbolTable * getSymTab (Function *ItemParent)
Static Public Member Functions inherited from llvm::SymbolTableListTraits< Argument, Function >
static iplist< Argument > & getList (Function *Par)
static ValueSymbolTable * getSymTab (Function *Par)
static ValueSymbolTable * toPtr (ValueSymbolTable *P)
static ValueSymbolTable * toPtr (ValueSymbolTable &R)
Static Public Member Functions inherited from llvm::ilist_nextprev_traits< NodeTy >
static NodeTy * getPrev (NodeTy *N)
static NodeTy * getNext (NodeTy *N)
static const NodeTy * getPrev (const NodeTy *N)
static const NodeTy * getNext (const NodeTy *N)
static void setPrev (NodeTy *N, NodeTy *Prev)
static void setNext (NodeTy *N, NodeTy *Next)
Static Public Member Functions inherited from llvm::ilist_sentinel_traits< NodeTy >
static NodeTy * createSentinel ()
createSentinel - create the dynamic sentinel
static void destroySentinel (NodeTy *N)
destroySentinel - deallocate the dynamic sentinel
static NodeTy * provideInitialHead ()
static NodeTy * ensureHead (NodeTy *&Head)
static void noteHead (NodeTy *NewHead, NodeTy *Sentinel)
noteHead - stash the sentinel into its default location
Static Public Member Functions inherited from llvm::ilist_node_traits< NodeTy >
static NodeTy * createNode (const NodeTy &V)
static void deleteNode (NodeTy *V)
Detailed Description
template<>
struct llvm::ilist_traits< Argument >
Definition at line 53 of file Function.h.
Member Function Documentation
Argument* llvm::ilist_traits< Argument >::createSentinel () const inline
Definition at line 56 of file Function.h.
static void llvm::ilist_traits< Argument >::destroySentinel (Argument *) inline static
Definition at line 59 of file Function.h.
Argument* llvm::ilist_traits< Argument >::ensureHead (Argument *) const inline
Definition at line 62 of file Function.h.
References llvm::ilist_sentinel_traits< NodeTy >::createSentinel().
ValueSymbolTable * llvm::ilist_traits< Argument >::getSymTab (Function * ItemParent) inline static
Definition at line 501 of file Function.h.
References llvm::Function::getValueSymbolTable().
static void llvm::ilist_traits< Argument >::noteHead (Argument * , Argument *) inline static
Definition at line 63 of file Function.h.
References getSymTab().
Argument* llvm::ilist_traits< Argument >::provideInitialHead () const inline
Definition at line 61 of file Function.h.
References llvm::ilist_sentinel_traits< NodeTy >::createSentinel().
The documentation for this struct was generated from the following file:
Function.h