LLVM: llvm::ilist< NodeTy > Struct Template Reference
LLVM API Documentation
llvm::ilist< NodeTy > Struct Template Reference
#include <ilist.h>
Public Types
typedef iplist< NodeTy >::size_type size_type
typedef iplist< NodeTy >::iterator iterator
Public Types inherited from llvm::iplist< NodeTy >
typedef NodeTy * pointer
typedef const NodeTy * const_pointer
typedef NodeTy & reference
typedef const NodeTy & const_reference
typedef NodeTy value_type
typedef ilist_iterator< NodeTy > iterator
typedef ilist_iterator< const NodeTy > const_iterator
typedef size_t size_type
typedef ptrdiff_t difference_type
typedef std::reverse_iterator< const_iterator > const_reverse_iterator
typedef std::reverse_iterator< iterator > reverse_iterator
Public Member Functions
ilist ()
ilist (const ilist &right)
ilist (size_type count)
ilist (size_type count, const NodeTy &val)
template<class InIt >
ilist (InIt first, InIt last)
iterator insert (iterator where, const NodeTy &val)
void push_front (const NodeTy &val)
void push_back (const NodeTy &val)
void insert (iterator where, size_type count, const NodeTy &val)
void assign (size_type count, const NodeTy &val)
template<class InIt >
void assign (InIt first1, InIt last1)
void resize (size_type newsize, NodeTy val)
void resize (size_type newsize)
Public Member Functions inherited from llvm::iplist< NodeTy >
iplist ()
~iplist ()
iterator begin ()
const_iterator begin () const
iterator end ()
const_iterator end () const
reverse_iterator rbegin ()
const_reverse_iterator rbegin () const
reverse_iterator rend ()
const_reverse_iterator rend () const
size_type max_size () const
bool LLVM_ATTRIBUTE_UNUSED_RESULT empty () const
reference front ()
const_reference front () const
reference back ()
const_reference back () const
void swap (iplist &RHS)
iterator insert (iterator where, NodeTy *New)
void insert (iterator where, InIt first, InIt last)
iterator insertAfter (iterator where, NodeTy *New)
NodeTy * remove (iterator &IT)
NodeTy * remove (const iterator &IT)
iterator erase (iterator where)
iterator erase (iterator first, iterator last)
void erase (const NodeTy &val)
void clearAndLeakNodesUnsafely ()
size_type LLVM_ATTRIBUTE_UNUSED_RESULT size () const
void clear ()
void push_front (NodeTy *val)
void push_back (NodeTy *val)
void pop_front ()
void pop_back ()
void splice (iterator where, iplist &L2)
void splice (iterator where, iplist &L2, iterator first)
void splice (iterator where, iplist &L2, iterator first, iterator last)
void erase_if (Pr1 pred)
void unique (Pr2 pred)
void unique ()
void merge (iplist &right, Pr3 pred)
void merge (iplist &right)
void sort (Pr3 pred)
void sort ()
Public Member Functions inherited from llvm::ilist_node_traits< NodeTy >
void addNodeToList (NodeTy *)
void removeNodeFromList (NodeTy *)
void transferNodesFromList (ilist_node_traits &, ilist_iterator< NodeTy >, ilist_iterator< NodeTy >)
Additional Inherited Members
Static Public Member Functions inherited from llvm::ilist_nextprev_traits< NodeTy >
static NodeTy * getPrev (NodeTy *N)
static NodeTy * getNext (NodeTy *N)
static const NodeTy * getPrev (const NodeTy *N)
static const NodeTy * getNext (const NodeTy *N)
static void setPrev (NodeTy *N, NodeTy *Prev)
static void setNext (NodeTy *N, NodeTy *Next)
Static Public Member Functions inherited from llvm::ilist_sentinel_traits< NodeTy >
static NodeTy * createSentinel ()
createSentinel - create the dynamic sentinel
static void destroySentinel (NodeTy *N)
destroySentinel - deallocate the dynamic sentinel
static NodeTy * provideInitialHead ()
static NodeTy * ensureHead (NodeTy *&Head)
static void noteHead (NodeTy *NewHead, NodeTy *Sentinel)
noteHead - stash the sentinel into its default location
Static Public Member Functions inherited from llvm::ilist_node_traits< NodeTy >
static NodeTy * createNode (const NodeTy &V)
static void deleteNode (NodeTy *V)
Detailed Description
template<typename NodeTy>
struct llvm::ilist< NodeTy >
Definition at line 640 of file ilist.h.
Member Typedef Documentation
template<typename NodeTy> typedef iplist<NodeTy>::iterator llvm::ilist< NodeTy >::iterator
Definition at line 642 of file ilist.h.
template<typename NodeTy> typedef iplist<NodeTy>::size_type llvm::ilist< NodeTy >::size_type
Definition at line 641 of file ilist.h.
Constructor & Destructor Documentation
template<typename NodeTy> llvm::ilist< NodeTy >::ilist () inline
Definition at line 644 of file ilist.h.
template<typename NodeTy> llvm::ilist< NodeTy >::ilist (const ilist< NodeTy > & right) inline
Definition at line 645 of file ilist.h.
template<typename NodeTy> llvm::ilist< NodeTy >::ilist (size_type count) inline explicit
Definition at line 648 of file ilist.h.
template<typename NodeTy> llvm::ilist< NodeTy >::ilist (size_type count, const NodeTy & val) inline
Definition at line 651 of file ilist.h.
template<typename NodeTy> template<class InIt > llvm::ilist< NodeTy >::ilist (InIt first, InIt last) inline
Definition at line 654 of file ilist.h.
Member Function Documentation
template<typename NodeTy> void llvm::ilist< NodeTy >::assign (size_type count, const NodeTy & val) inline
Definition at line 678 of file ilist.h.
template<typename NodeTy> template<class InIt > void llvm::ilist< NodeTy >::assign (InIt first1, InIt last1) inline
Definition at line 687 of file ilist.h.
template<typename NodeTy> iterator llvm::ilist< NodeTy >::insert (iterator where, const NodeTy & val) inline
Definition at line 664 of file ilist.h.
Referenced by llvm::MachineFunction::insert(), llvm::MachineBasicBlock::insert(), llvm::SlotIndexes::insertMachineInstrInMaps(), llvm::SlotIndexes::insertMBBInMaps(), is_ns_word_char(), llvm::SparseBitVector< ElementSize >::operator|=(), llvm::SelectionDAG::RepositionNode(), and llvm::SparseBitVector< ElementSize >::set().
template<typename NodeTy> void llvm::ilist< NodeTy >::insert (iterator where, size_type count, const NodeTy & val) inline
Definition at line 673 of file ilist.h.
template<typename NodeTy> void llvm::ilist< NodeTy >::push_back (const NodeTy & val) inline
Definition at line 671 of file ilist.h.
Referenced by llvm::SlotIndexes::eraseIndex(), llvm::Module::getOrInsertNamedMetadata(), llvm::SparseBitVector< ElementSize >::intersectWithComplement(), is_ns_word_char(), llvm::SparseBitVector< ElementSize >::operator=(), llvm::yaml::Scanner::peekNext(), llvm::MachineFunction::push_back(), llvm::MachineBasicBlock::push_back(), llvm::SlotIndexes::runOnMachineFunction(), llvm::SparseBitVector< ElementSize >::SparseBitVector(), and wasEscaped().
template<typename NodeTy> void llvm::ilist< NodeTy >::push_front (const NodeTy & val) inline
Definition at line 670 of file ilist.h.
Referenced by llvm::MachineFunction::push_front().
template<typename NodeTy> void llvm::ilist< NodeTy >::resize (size_type newsize, NodeTy val) inline
Definition at line 699 of file ilist.h.
template<typename NodeTy> void llvm::ilist< NodeTy >::resize (size_type newsize) inline
Definition at line 709 of file ilist.h.
Referenced by llvm::ilist< SparseBitVectorElement< ElementSize > >::resize().
The documentation for this struct was generated from the following file:
ilist.h