LLVM: llvm::MSP430RegisterInfo Struct Reference
LLVM API Documentation
llvm::MSP430RegisterInfo Struct Reference
#include <MSP430RegisterInfo.h>
Public Member Functions
MSP430RegisterInfo (MSP430TargetMachine &tm)
const uint16_t * getCalleeSavedRegs (const MachineFunction *MF=0) const
Code Generation virtual methods...
BitVector getReservedRegs (const MachineFunction &MF) const
const TargetRegisterClass * getPointerRegClass (const MachineFunction &MF, unsigned Kind=0) const
void eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=NULL) const
unsigned getFrameRegister (const MachineFunction &MF) const
Detailed Description
Definition at line 27 of file MSP430RegisterInfo.h.
Constructor & Destructor Documentation
MSP430RegisterInfo::MSP430RegisterInfo (MSP430TargetMachine & tm)
Definition at line 35 of file MSP430RegisterInfo.cpp.
References llvm::SystemZISD::TM.
Member Function Documentation
void MSP430RegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = NULL) const
Definition at line 104 of file MSP430RegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::BuildMI(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::ISD::FrameIndex, llvm::MCInstrInfo::get(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFrameInfo(), llvm::TargetMachine::getFrameLowering(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::TargetMachine::getInstrInfo(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getTarget(), llvm::TargetFrameLowering::hasFP(), llvm::A64CC::MI, llvm::next(), llvm::MachineInstr::setDesc(), and TII.
const uint16_t * MSP430RegisterInfo::getCalleeSavedRegs (const MachineFunction * MF = 0) const
Code Generation virtual methods...
Definition at line 41 of file MSP430RegisterInfo.cpp.
References F(), llvm::Function::getCallingConv(), llvm::TargetMachine::getFrameLowering(), llvm::MachineFunction::getFunction(), llvm::MachineFunction::getTarget(), llvm::TargetFrameLowering::hasFP(), and llvm::CallingConv::MSP430_INTR.
unsigned MSP430RegisterInfo::getFrameRegister (const MachineFunction & MF) const
Definition at line 158 of file MSP430RegisterInfo.cpp.
References llvm::TargetMachine::getFrameLowering(), llvm::MachineFunction::getTarget(), and llvm::TargetFrameLowering::hasFP().
const TargetRegisterClass * MSP430RegisterInfo::getPointerRegClass (const MachineFunction & MF, unsigned Kind = 0) const
Definition at line 98 of file MSP430RegisterInfo.cpp.
BitVector MSP430RegisterInfo::getReservedRegs (const MachineFunction & MF) const
Definition at line 76 of file MSP430RegisterInfo.cpp.
References llvm::TargetMachine::getFrameLowering(), llvm::MachineFunction::getTarget(), llvm::TargetFrameLowering::hasFP(), and llvm::BitVector::set().
The documentation for this struct was generated from the following files:
MSP430RegisterInfo.h
MSP430RegisterInfo.cpp