LLVM: llvm::DenseMapInfo< Expression > Struct Template Reference
LLVM API Documentation
llvm::DenseMapInfo< Expression > Struct Template Reference
Static Public Member Functions
static Expression getEmptyKey ()
static Expression getTombstoneKey ()
static unsigned getHashValue (const Expression e)
static bool isEqual (const Expression &LHS, const Expression &RHS)
Detailed Description
template<>
struct llvm::DenseMapInfo< Expression >
Definition at line 139 of file GVN.cpp.
Member Function Documentation
static Expression llvm::DenseMapInfo< Expression >::getEmptyKey () inline static
Definition at line 140 of file GVN.cpp.
static unsigned llvm::DenseMapInfo< Expression >::getHashValue (const Expression e) inline static
Definition at line 148 of file GVN.cpp.
References llvm::hash_value().
static Expression llvm::DenseMapInfo< Expression >::getTombstoneKey () inline static
Definition at line 144 of file GVN.cpp.
static bool llvm::DenseMapInfo< Expression >::isEqual (const Expression & LHS, const Expression & RHS) inline static
Definition at line 152 of file GVN.cpp.
References llvm::ARM_AM::add, llvm::AnalysisUsage::addPreserved(), llvm::AnalysisUsage::addRequired(), llvm::BumpPtrAllocator::Allocate(), llvm::APIntOps::And(), BB, llvm::Call, d, llvm::dump(), llvm::dyn_cast(), llvm::Intrinsic::exp, ExtractElement(), F(), llvm::ExtractValueInst::getAggregateOperand(), llvm::CallInst::getArgOperand(), llvm::NonLocalDepEntry::getBB(), llvm::MemDepResult::getInst(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getInt(), llvm::IntrinsicInst::getIntrinsicID(), llvm::CallInst::getNumArgOperands(), llvm::ExtractValueInst::getNumIndices(), llvm::User::getNumOperands(), llvm::Instruction::getOpcode(), llvm::Instruction::getParent(), llvm::PassRegistry::getPassRegistry(), llvm::PointerIntPair< PointerTy, IntBits, IntType, PtrTraits >::getPointer(), llvm::NonLocalDepEntry::getResult(), llvm::CmpInst::getSwappedPredicate(), llvm::Value::getType(), i, I, llvm::ExtractValueInst::idx_begin(), llvm::ExtractValueInst::idx_end(), llvm::ARM_PROC::IE, if(), llvm::initializeGVNPass(), llvm::Instruction::isCommutative(), llvm::MemDepResult::isDef(), llvm::MemDepResult::isNonLocal(), lookup(), llvm::CmpInst::makeCmpResultType(), llvm::A64CC::MI, N, llvm::User::op_begin(), llvm::User::op_end(), llvm::APIntOps::Or(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::Intrinsic::sadd_with_overflow, llvm::MCID::Select, llvm::Intrinsic::smul_with_overflow, llvm::Intrinsic::ssub_with_overflow, std::swap(), llvm::Intrinsic::uadd_with_overflow, llvm::Intrinsic::umul_with_overflow, llvm::Intrinsic::usub_with_overflow, and llvm::APIntOps::Xor().
The documentation for this struct was generated from the following file:
GVN.cpp