LLVM: llvm::DenseMapAPIntKeyInfo Struct Reference
LLVM API Documentation
llvm::DenseMapAPIntKeyInfo Struct Reference
#include <LLVMContextImpl.h>
Classes
struct KeyTy
Static Public Member Functions
static KeyTy getEmptyKey ()
static KeyTy getTombstoneKey ()
static unsigned getHashValue (const KeyTy &Key)
static bool isEqual (const KeyTy &LHS, const KeyTy &RHS)
Detailed Description
Definition at line 44 of file LLVMContextImpl.h.
Member Function Documentation
static KeyTy llvm::DenseMapAPIntKeyInfo::getEmptyKey () inline static
Definition at line 59 of file LLVMContextImpl.h.
References llvm::DenseMapAPIntKeyInfo::KeyTy::KeyTy().
Referenced by llvm::AnonStructTypeKeyInfo::isEqual(), and llvm::FunctionTypeKeyInfo::isEqual().
static unsigned llvm::DenseMapAPIntKeyInfo::getHashValue (const KeyTy & Key) inline static
Definition at line 61 of file LLVMContextImpl.h.
References llvm::DenseMapAPIntKeyInfo::KeyTy::hash_value.
Referenced by llvm::AnonStructTypeKeyInfo::getHashValue(), and llvm::FunctionTypeKeyInfo::getHashValue().
static KeyTy llvm::DenseMapAPIntKeyInfo::getTombstoneKey () inline static
Definition at line 60 of file LLVMContextImpl.h.
References llvm::DenseMapAPIntKeyInfo::KeyTy::KeyTy().
Referenced by llvm::AnonStructTypeKeyInfo::isEqual(), and llvm::FunctionTypeKeyInfo::isEqual().
static bool llvm::DenseMapAPIntKeyInfo::isEqual (const KeyTy & LHS, const KeyTy & RHS) inline static
Definition at line 64 of file LLVMContextImpl.h.
The documentation for this struct was generated from the following file:
LLVMContextImpl.h