LLVM: llvm::GraphTraits< const CallGraph * > Struct Template Reference
LLVM API Documentation
llvm::GraphTraits< const CallGraph * > Struct Template Reference
#include <CallGraph.h>
Public Types
typedef CallGraph::const_iterator nodes_iterator
Public Types inherited from llvm::GraphTraits< const CallGraphNode * >
typedef const CallGraphNode NodeType
typedef NodeType::const_iterator ChildIteratorType
Static Public Member Functions
static NodeType * getEntryNode (const CallGraph *CGN)
static nodes_iterator nodes_begin (const CallGraph *CG)
static nodes_iterator nodes_end (const CallGraph *CG)
Static Public Member Functions inherited from llvm::GraphTraits< const CallGraphNode * >
static NodeType * getEntryNode (const CallGraphNode *CGN)
static ChildIteratorType child_begin (NodeType *N)
static ChildIteratorType child_end (NodeType *N)
Detailed Description
template<>
struct llvm::GraphTraits< const CallGraph * >
Definition at line 363 of file CallGraph.h.
Member Typedef Documentation
typedef CallGraph::const_iterator llvm::GraphTraits< const CallGraph * >::nodes_iterator
Definition at line 369 of file CallGraph.h.
Member Function Documentation
static NodeType* llvm::GraphTraits< const CallGraph * >::getEntryNode (const CallGraph * CGN) inline static
Definition at line 365 of file CallGraph.h.
References llvm::CallGraph::getExternalCallingNode().
static nodes_iterator llvm::GraphTraits< const CallGraph * >::nodes_begin (const CallGraph * CG) inline static
Definition at line 370 of file CallGraph.h.
References llvm::CallGraph::begin().
static nodes_iterator llvm::GraphTraits< const CallGraph * >::nodes_end (const CallGraph * CG) inline static
Definition at line 371 of file CallGraph.h.
References llvm::CallGraph::end(), and FORCE_DEFINING_FILE_TO_BE_LINKED.
The documentation for this struct was generated from the following file:
CallGraph.h