LLVM: llvm::DOTGraphTraits< const MachineFunction * > Struct Template Reference
LLVM API Documentation
llvm::DOTGraphTraits< const MachineFunction * > Struct Template Reference
Public Member Functions
DOTGraphTraits (bool isSimple=false)
std::string getNodeLabel (const MachineBasicBlock *Node, const MachineFunction *Graph)
Public Member Functions inherited from llvm::DefaultDOTGraphTraits
DefaultDOTGraphTraits (bool simple=false)
template<typename GraphType >
std::string getNodeLabel (const void *, const GraphType &)
Static Public Member Functions
static std::string getGraphName (const MachineFunction *F)
Static Public Member Functions inherited from llvm::DefaultDOTGraphTraits
template<typename GraphType >
static std::string getGraphName (const GraphType &)
template<typename GraphType >
static std::string getGraphProperties (const GraphType &)
static bool renderGraphFromBottomUp ()
static bool isNodeHidden (const void *)
template<typename GraphType >
static bool hasNodeAddressLabel (const void *, const GraphType &)
template<typename GraphType >
static std::string getNodeDescription (const void *, const GraphType &)
template<typename GraphType >
static std::string getNodeAttributes (const void *, const GraphType &)
template<typename EdgeIter , typename GraphType >
static std::string getEdgeAttributes (const void *, EdgeIter, const GraphType &)
template<typename EdgeIter >
static std::string getEdgeSourceLabel (const void *, EdgeIter)
template<typename EdgeIter >
static bool edgeTargetsEdgeSource (const void *, EdgeIter)
template<typename EdgeIter >
static EdgeIter getEdgeTarget (const void *, EdgeIter I)
static bool hasEdgeDestLabels ()
static unsigned numEdgeDestLabels (const void *)
static std::string getEdgeDestLabel (const void *, unsigned)
template<typename GraphType , typename GraphWriter >
static void addCustomGraphFeatures (const GraphType &, GraphWriter &)
Additional Inherited Members
Protected Member Functions inherited from llvm::DefaultDOTGraphTraits
bool isSimple ()
Detailed Description
template<>
struct llvm::DOTGraphTraits< const MachineFunction * >
Definition at line 366 of file MachineFunction.cpp.
Constructor & Destructor Documentation
llvm::DOTGraphTraits< const MachineFunction * >::DOTGraphTraits (bool isSimple = false) inline
Definition at line 368 of file MachineFunction.cpp.
Member Function Documentation
static std::string llvm::DOTGraphTraits< const MachineFunction * >::getGraphName (const MachineFunction * F) inline static
Definition at line 370 of file MachineFunction.cpp.
References llvm::MachineFunction::getName(), and llvm::StringRef::str().
std::string llvm::DOTGraphTraits< const MachineFunction * >::getNodeLabel (const MachineBasicBlock * Node, const MachineFunction * Graph) inline
Definition at line 374 of file MachineFunction.cpp.
References BB, llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineBasicBlock::getNumber(), i, and llvm::MachineBasicBlock::print().
The documentation for this struct was generated from the following file:
MachineFunction.cpp