LLVM: llvm::MachinePointerInfo Struct Reference
LLVM API Documentation
llvm::MachinePointerInfo Struct Reference
#include <MachineMemOperand.h>
Public Member Functions
MachinePointerInfo (const Value *v=0, int64_t offset=0)
MachinePointerInfo getWithOffset (int64_t O) const
unsigned getAddrSpace () const
Static Public Member Functions
static MachinePointerInfo getConstantPool ()
static MachinePointerInfo getFixedStack (int FI, int64_t offset=0)
static MachinePointerInfo getJumpTable ()
static MachinePointerInfo getGOT ()
static MachinePointerInfo getStack (int64_t Offset)
getStack - stack pointer relative access.
Public Attributes
const Value * V
int64_t Offset
Offset - This is an offset from the base Value*.
Detailed Description
MachinePointerInfo - This class contains a discriminated union of information about pointers in memory operands, relating them back to LLVM IR or to virtual locations (such as frame indices) that are exposed during codegen.
Definition at line 32 of file MachineMemOperand.h.
Constructor & Destructor Documentation
llvm::MachinePointerInfo::MachinePointerInfo (const Value * v = 0, int64_t offset = 0) inline explicit
Definition at line 41 of file MachineMemOperand.h.
Referenced by getWithOffset().
Member Function Documentation
unsigned MachinePointerInfo::getAddrSpace () const
getAddrSpace - Return the LLVM IR address space number that this pointer points into.
Definition at line 391 of file MachineInstr.cpp.
Referenced by AddNodeIDCustom(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SelectionDAG::getAtomic(), llvm::SelectionDAG::getIndexedStore(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTruncStore(), getWithOffset(), isDispSafeForFrameIndex(), partitionShuffleOfConcats(), and ShrinkLoadReplaceStoreWithStore().
MachinePointerInfo MachinePointerInfo::getConstantPool () static
getConstantPool - Return a MachinePointerInfo record that refers to the constant pool.
Definition at line 398 of file MachineInstr.cpp.
Referenced by llvm::X86TargetLowering::BuildFILD(), llvm::createXCoreISelDag(), ExpandUnalignedLoad(), FPCCToARMCC(), getComparePred(), llvm::ARMTargetLowering::getJumpTableEncoding(), getWithOffset(), LowerFP_EXTEND(), llvm::AArch64TargetLowering::LowerGlobalAddressELFSmall(), lowerGR128Binary(), LowerSIGN_EXTEND_AVX512(), LowerVectorBroadcast(), LowerZERO_EXTEND(), LowerZERO_EXTEND_AVX512(), partitionShuffleOfConcats(), llvm::ARMTargetLowering::ReplaceNodeResults(), and useSinCos().
MachinePointerInfo MachinePointerInfo::getFixedStack (int FI, int64_t offset = 0) static
getFixedStack - Return a MachinePointerInfo record that refers to the the specified FrameIndex.
Definition at line 404 of file MachineInstr.cpp.
Referenced by llvm::addFrameReference(), AnalyzeReturnValues(), llvm::X86TargetLowering::BuildFILD(), llvm::AArch64FrameLowering::emitFrameMemOps(), EmitMonitor(), EmitTailCallStoreFPAndRetAddr(), EmitTailCallStoreRetAddr(), ExpandUnalignedLoad(), llvm::TargetInstrInfo::foldMemoryOperand(), FuncIsMadeTailCallSafe(), getComparePred(), llvm::MipsInstrInfo::GetMemOperand(), llvm::MipsTargetLowering::getOpndList(), GetRegistersForValue(), getTruncatedArgReg(), getWithOffset(), InferPointerInfo(), isADDADDMUL(), isLocalCall(), llvm::AArch64InstrInfo::loadRegFromStackSlot(), llvm::Thumb1InstrInfo::loadRegFromStackSlot(), llvm::Thumb2InstrInfo::loadRegFromStackSlot(), llvm::MSP430InstrInfo::loadRegFromStackSlot(), llvm::SparcInstrInfo::loadRegFromStackSlot(), llvm::ARMBaseInstrInfo::loadRegFromStackSlot(), llvm::PPCInstrInfo::loadRegFromStackSlot(), LowerADJUST_TRAMPOLINE(), llvm::AArch64TargetLowering::LowerCall(), llvm::SystemZTargetLowering::LowerCall(), llvm::SelectionDAGBuilder::LowerCallTo(), llvm::AArch64TargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::SparcTargetLowering::LowerFormalArguments_64(), LowerToTLSExecModel(), LowerVASTART(), llvm::ARMTargetLowering::ReplaceNodeResults(), llvm::AArch64InstrInfo::storeRegToStackSlot(), llvm::Thumb1InstrInfo::storeRegToStackSlot(), llvm::Thumb2InstrInfo::storeRegToStackSlot(), llvm::MSP430InstrInfo::storeRegToStackSlot(), llvm::SparcInstrInfo::storeRegToStackSlot(), llvm::ARMBaseInstrInfo::storeRegToStackSlot(), llvm::PPCInstrInfo::storeRegToStackSlot(), StoreTailCallArgumentsToStackSlot(), and llvm::SelectionDAGBuilder::visitSPDescriptorParent().
MachinePointerInfo MachinePointerInfo::getGOT () static
getGOT - Return a MachinePointerInfo record that refers to a GOT entry.
Definition at line 412 of file MachineInstr.cpp.
Referenced by llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), EmitTailCallStoreRetAddr(), llvm::MipsTargetLowering::getAddrLocal(), llvm::ARMTargetLowering::getJumpTableEncoding(), getWithOffset(), lowerGR128Binary(), LowerINSERT_SUBVECTOR(), LowerToTLSExecModel(), and llvm::SparcTargetLowering::makeAddress().
MachinePointerInfo MachinePointerInfo::getJumpTable () static
getJumpTable - Return a MachinePointerInfo record that refers to a jump table entry.
Definition at line 408 of file MachineInstr.cpp.
Referenced by llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), expandf64Toi32(), getWithOffset(), llvm::ARMTargetLowering::ReplaceNodeResults(), and useSinCos().
MachinePointerInfo MachinePointerInfo::getStack (int64_t Offset) static
getStack - stack pointer relative access.
Definition at line 416 of file MachineInstr.cpp.
Referenced by FPCCToARMCC(), FuncIsMadeTailCallSafe(), getWithOffset(), llvm::AArch64TargetLowering::LowerCall(), and llvm::AArch64TargetLowering::SaveVarArgRegisters().
MachinePointerInfo llvm::MachinePointerInfo::getWithOffset (int64_t O) const inline
Definition at line 44 of file MachineMemOperand.h.
References getAddrSpace(), getConstantPool(), getFixedStack(), getGOT(), getJumpTable(), getStack(), and MachinePointerInfo().
Referenced by BuildVectorFromScalar(), canFoldInAddressingMode(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset(), ExpandUnalignedLoad(), ExpandUnalignedStore(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), isTruncateOf(), isWordAligned(), ConsecutiveMemoryChainSorter::operator()(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformSTORECombine(), ShrinkLoadReplaceStoreWithStore(), and llvm::TargetLowering::SimplifySetCC().
Member Data Documentation
int64_t llvm::MachinePointerInfo::Offset
Offset - This is an offset from the base Value*.
Definition at line 39 of file MachineMemOperand.h.
Referenced by llvm::MachineMemOperand::getOffset(), and llvm::MachineMemOperand::setOffset().
const Value* llvm::MachinePointerInfo::V
V - This is the IR pointer value for the access, or it is null if unknown. If this is null, then the access is to a pointer in the default address space.
Definition at line 36 of file MachineMemOperand.h.
Referenced by llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTruncStore(), llvm::MachineMemOperand::getValue(), and llvm::MachineMemOperand::setValue().
The documentation for this struct was generated from the following files:
MachineMemOperand.h
MachineInstr.cpp