LLVM: llvm::DwarfAccelTable::Atom Struct Reference
LLVM API Documentation
llvm::DwarfAccelTable::Atom Struct Reference
#include <DwarfAccelTable.h>
Public Member Functions
Atom (uint16_t type, uint16_t form)
void print (raw_ostream &O)
void dump ()
Public Attributes
uint16_t type
uint16_t form
Detailed Description
Definition at line 126 of file DwarfAccelTable.h.
Constructor & Destructor Documentation
llvm::DwarfAccelTable::Atom::Atom (uint16_t type, uint16_t form) inline
Definition at line 130 of file DwarfAccelTable.h.
Member Function Documentation
void llvm::DwarfAccelTable::Atom::dump () inline
Definition at line 136 of file DwarfAccelTable.h.
References llvm::ArrayRef< T >::begin(), llvm::dbgs(), llvm::DwarfAccelTable::dump(), llvm::ArrayRef< T >::end(), i, llvm::DwarfAccelTable::print(), and llvm::SmallVectorTemplateCommon< T >::size().
void llvm::DwarfAccelTable::Atom::print (raw_ostream & O) inline
Definition at line 132 of file DwarfAccelTable.h.
References llvm::dwarf::AtomTypeString(), and llvm::dwarf::FormEncodingString().
Member Data Documentation
uint16_t llvm::DwarfAccelTable::Atom::form
Definition at line 128 of file DwarfAccelTable.h.
Referenced by llvm::DwarfAccelTable::FinalizeTable().
uint16_t llvm::DwarfAccelTable::Atom::type
Definition at line 127 of file DwarfAccelTable.h.
Referenced by llvm::DwarfAccelTable::FinalizeTable().
The documentation for this struct was generated from the following file:
DwarfAccelTable.h