LLVM: llvm::DWARFDebugLine::DumpingState Struct Reference
LLVM API Documentation
llvm::DWARFDebugLine::DumpingState Struct Reference
#include <DWARFDebugLine.h>
Public Member Functions
DumpingState (raw_ostream &OS)
virtual ~DumpingState ()
virtual void finalize ()
Public Member Functions inherited from llvm::DWARFDebugLine::State
State ()
virtual ~State ()
virtual void appendRowToMatrix (uint32_t offset)
virtual void reset ()
Public Member Functions inherited from llvm::DWARFDebugLine::Row
Row (bool default_is_stmt=false)
void postAppend ()
Called after a row is appended to the matrix.
void reset (bool default_is_stmt)
void dump (raw_ostream &OS) const
Public Member Functions inherited from llvm::DWARFDebugLine::Sequence
Sequence ()
void reset ()
bool isValid () const
bool containsPC (uint64_t pc) const
Public Member Functions inherited from llvm::DWARFDebugLine::LineTable
void appendRow (const DWARFDebugLine::Row &state)
void appendSequence (const DWARFDebugLine::Sequence &sequence)
void clear ()
uint32_t lookupAddress (uint64_t address) const
bool lookupAddressRange (uint64_t address, uint64_t size, std::vector< uint32_t > &result) const
bool getFileNameByIndex (uint64_t FileIndex, bool NeedsAbsoluteFilePath, std::string &Result) const
void dump (raw_ostream &OS) const
Additional Inherited Members
Public Types inherited from llvm::DWARFDebugLine::State
enum { StartParsingLineTable = 0, DoneParsingLineTable = -1 }
Public Types inherited from llvm::DWARFDebugLine::LineTable
typedef std::vector< Row > RowVector
typedef RowVector::const_iterator RowIter
typedef std::vector< Sequence > SequenceVector
typedef SequenceVector::const_iterator SequenceIter
Static Public Member Functions inherited from llvm::DWARFDebugLine::Row
static bool orderByAddress (const Row &LHS, const Row &RHS)
Static Public Member Functions inherited from llvm::DWARFDebugLine::Sequence
static bool orderByLowPC (const Sequence &LHS, const Sequence &RHS)
Public Attributes inherited from llvm::DWARFDebugLine::State
unsigned row
Public Attributes inherited from llvm::DWARFDebugLine::Row
uint64_t Address
uint32_t Line
uint16_t Column
uint16_t File
uint8_t Isa
uint8_t IsStmt:1
uint8_t BasicBlock:1
uint8_t EndSequence:1
uint8_t PrologueEnd:1
uint8_t EpilogueBegin:1
Public Attributes inherited from llvm::DWARFDebugLine::Sequence
uint64_t LowPC
uint64_t HighPC
unsigned FirstRowIndex
unsigned LastRowIndex
bool Empty
Public Attributes inherited from llvm::DWARFDebugLine::LineTable
struct Prologue Prologue
RowVector Rows
SequenceVector Sequences
Detailed Description
Definition at line 224 of file DWARFDebugLine.h.
Constructor & Destructor Documentation
llvm::DWARFDebugLine::DumpingState::DumpingState (raw_ostream & OS) inline
Definition at line 225 of file DWARFDebugLine.h.
References llvm::DWARFDebugLine::getLineTable(), llvm::DWARFDebugLine::getOrParseLineTable(), llvm::DWARFDebugLine::parsePrologue(), and llvm::DWARFDebugLine::parseStatementTable().
DWARFDebugLine::DumpingState::~DumpingState () virtual
Definition at line 136 of file DWARFDebugLine.cpp.
Member Function Documentation
void DWARFDebugLine::DumpingState::finalize () virtual
Reimplemented from llvm::DWARFDebugLine::State.
Definition at line 138 of file DWARFDebugLine.cpp.
References llvm::dump().
The documentation for this struct was generated from the following files:
DWARFDebugLine.h
DWARFDebugLine.cpp