LLVM: llvm::ilist_traits< MachineInstr > Struct Template Reference
LLVM API Documentation
llvm::ilist_traits< MachineInstr > Struct Template Reference
#include <MachineBasicBlock.h>
Public Member Functions
MachineInstr * createSentinel () const
void destroySentinel (MachineInstr *) const
MachineInstr * provideInitialHead () const
MachineInstr * ensureHead (MachineInstr *) const
void addNodeToList (MachineInstr *N)
void removeNodeFromList (MachineInstr *N)
void transferNodesFromList (ilist_traits &SrcTraits, ilist_iterator< MachineInstr > first, ilist_iterator< MachineInstr > last)
void deleteNode (MachineInstr *N)
Public Member Functions inherited from llvm::ilist_node_traits< MachineInstr >
void addNodeToList (MachineInstr *)
void removeNodeFromList (MachineInstr *)
void transferNodesFromList (ilist_node_traits &, ilist_iterator< MachineInstr >, ilist_iterator< MachineInstr >)
Static Public Member Functions
static void noteHead (MachineInstr *, MachineInstr *)
Static Public Member Functions inherited from llvm::ilist_nextprev_traits< MachineInstr >
static MachineInstr * getPrev (MachineInstr *N)
static const MachineInstr * getPrev (const MachineInstr *N)
static MachineInstr * getNext (MachineInstr *N)
static const MachineInstr * getNext (const MachineInstr *N)
static void setPrev (MachineInstr *N, MachineInstr *Prev)
static void setNext (MachineInstr *N, MachineInstr *Next)
Static Public Member Functions inherited from llvm::ilist_sentinel_traits< MachineInstr >
static MachineInstr * createSentinel ()
createSentinel - create the dynamic sentinel
static void destroySentinel (MachineInstr *N)
destroySentinel - deallocate the dynamic sentinel
static MachineInstr * provideInitialHead ()
static MachineInstr * ensureHead (MachineInstr *&Head)
static void noteHead (MachineInstr *NewHead, MachineInstr *Sentinel)
noteHead - stash the sentinel into its default location
Static Public Member Functions inherited from llvm::ilist_node_traits< MachineInstr >
static MachineInstr * createNode (const MachineInstr &V)
static void deleteNode (MachineInstr *V)
Friends
class MachineBasicBlock
Detailed Description
template<>
struct llvm::ilist_traits< MachineInstr >
Definition at line 34 of file MachineBasicBlock.h.
Member Function Documentation
void llvm::ilist_traits< MachineInstr >::addNodeToList (MachineInstr * N)
MachineInstr* llvm::ilist_traits< MachineInstr >::createSentinel () const inline
Definition at line 43 of file MachineBasicBlock.h.
void llvm::ilist_traits< MachineInstr >::deleteNode (MachineInstr * N)
void llvm::ilist_traits< MachineInstr >::destroySentinel (MachineInstr *) const inline
Definition at line 46 of file MachineBasicBlock.h.
MachineInstr* llvm::ilist_traits< MachineInstr >::ensureHead (MachineInstr *) const inline
Definition at line 49 of file MachineBasicBlock.h.
References llvm::ilist_sentinel_traits< NodeTy >::createSentinel().
static void llvm::ilist_traits< MachineInstr >::noteHead (MachineInstr * , MachineInstr *) inline static
Definition at line 50 of file MachineBasicBlock.h.
References llvm::ilist_node_traits< NodeTy >::addNodeToList(), llvm::ilist_node_traits< NodeTy >::createNode(), llvm::ilist_node_traits< NodeTy >::deleteNode(), N, llvm::ilist_node_traits< NodeTy >::removeNodeFromList(), and llvm::ilist_node_traits< NodeTy >::transferNodesFromList().
MachineInstr* llvm::ilist_traits< MachineInstr >::provideInitialHead () const inline
Definition at line 48 of file MachineBasicBlock.h.
References llvm::ilist_sentinel_traits< NodeTy >::createSentinel().
void llvm::ilist_traits< MachineInstr >::removeNodeFromList (MachineInstr * N)
void llvm::ilist_traits< MachineInstr >::transferNodesFromList (ilist_traits< MachineInstr > & SrcTraits, ilist_iterator< MachineInstr > first, ilist_iterator< MachineInstr > last)
Friends And Related Function Documentation
friend class MachineBasicBlock friend
Definition at line 39 of file MachineBasicBlock.h.
The documentation for this struct was generated from the following file:
MachineBasicBlock.h