LLVM: llvm::EVT Struct Reference
LLVM API Documentation
llvm::EVT Struct Reference
#include <ValueTypes.h>
Classes
struct compareRawBits
Public Member Functions
EVT ()
EVT (MVT::SimpleValueType SVT)
EVT (MVT S)
bool operator== (EVT VT) const
bool operator!= (EVT VT) const
EVT changeVectorElementTypeToInteger () const
bool isSimple () const
bool isExtended () const
bool isFloatingPoint () const
isFloatingPoint - Return true if this is a FP, or a vector FP type.
bool isInteger () const
isInteger - Return true if this is an integer, or a vector integer type.
bool isVector () const
isVector - Return true if this is a vector value type.
bool is16BitVector () const
is16BitVector - Return true if this is a 16-bit vector type.
bool is32BitVector () const
is32BitVector - Return true if this is a 32-bit vector type.
bool is64BitVector () const
is64BitVector - Return true if this is a 64-bit vector type.
bool is128BitVector () const
is128BitVector - Return true if this is a 128-bit vector type.
bool is256BitVector () const
is256BitVector - Return true if this is a 256-bit vector type.
bool is512BitVector () const
is512BitVector - Return true if this is a 512-bit vector type.
bool is1024BitVector () const
is1024BitVector - Return true if this is a 1024-bit vector type.
bool isOverloaded () const
isOverloaded - Return true if this is an overloaded type for TableGen.
bool isByteSized () const
isByteSized - Return true if the bit size is a multiple of 8.
bool isRound () const
isRound - Return true if the size is a power-of-two number of bytes.
bool bitsEq (EVT VT) const
bitsEq - Return true if this has the same number of bits as VT.
bool bitsGT (EVT VT) const
bitsGT - Return true if this has more bits than VT.
bool bitsGE (EVT VT) const
bitsGE - Return true if this has no less bits than VT.
bool bitsLT (EVT VT) const
bitsLT - Return true if this has less bits than VT.
bool bitsLE (EVT VT) const
bitsLE - Return true if this has no more bits than VT.
MVT getSimpleVT () const
EVT getScalarType () const
EVT getVectorElementType () const
unsigned getVectorNumElements () const
unsigned getSizeInBits () const
getSizeInBits - Return the size of the specified value type in bits.
unsigned getStoreSize () const
unsigned getStoreSizeInBits () const
EVT getRoundIntegerType (LLVMContext &Context) const
EVT getHalfSizedIntegerVT (LLVMContext &Context) const
bool isPow2VectorType () const
isPow2VectorType - Returns true if the given vector is a power of 2.
EVT getPow2VectorType (LLVMContext &Context) const
std::string getEVTString () const
getEVTString - This function returns value type as a string, e.g. "i32".
Type * getTypeForEVT (LLVMContext &Context) const
intptr_t getRawBits () const
Static Public Member Functions
static EVT getFloatingPointVT (unsigned BitWidth)
static EVT getIntegerVT (LLVMContext &Context, unsigned BitWidth)
static EVT getVectorVT (LLVMContext &Context, EVT VT, unsigned NumElements)
static EVT getEVT (Type *Ty, bool HandleUnknown=false)
Detailed Description
EVT - Extended Value Type. Capable of holding value types which are not native for any processor (such as the i12345 type), as well as the types a MVT can represent.
Definition at line 576 of file ValueTypes.h.
Constructor & Destructor Documentation
llvm::EVT::EVT () inline
Definition at line 582 of file ValueTypes.h.
llvm::EVT::EVT (MVT::SimpleValueType SVT) inline
Definition at line 584 of file ValueTypes.h.
llvm::EVT::EVT (MVT S) inline
Definition at line 585 of file ValueTypes.h.
Member Function Documentation
bool llvm::EVT::bitsEq (EVT VT) const inline
bitsEq - Return true if this has the same number of bits as VT.
Definition at line 717 of file ValueTypes.h.
References llvm::MVT::getSizeInBits(), and getSizeInBits().
Referenced by llvm::createAMDGPUISelDag(), ConsecutiveMemoryChainSorter::operator()(), and useSinCos().
bool llvm::EVT::bitsGE (EVT VT) const inline
bitsGE - Return true if this has no less bits than VT.
Definition at line 729 of file ValueTypes.h.
References llvm::MVT::getSizeInBits(), and getSizeInBits().
Referenced by ExpandUnalignedLoad(), getCopyToPartsVector(), GetFPLibCall(), getMemcpyLoadsAndStores(), partitionShuffleOfConcats(), and llvm::R600TargetLowering::ReplaceNodeResults().
bool llvm::EVT::bitsGT (EVT VT) const inline
bitsGT - Return true if this has more bits than VT.
Definition at line 723 of file ValueTypes.h.
References llvm::MVT::getSizeInBits(), and getSizeInBits().
Referenced by llvm::SITargetLowering::allowsUnalignedMemoryAccesses(), llvm::X86TargetLowering::BuildFILD(), computeBytesPoppedByCallee(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), llvm::ARMSelectionDAGInfo::EmitTargetCodeForMemset(), ExpandUnalignedLoad(), FindOptimalMemOpLowering(), llvm::SelectionDAG::getAnyExtOrTrunc(), llvm::SelectionDAG::getMemset(), llvm::SelectionDAG::getNode(), llvm::FastISel::getRegForGEPIndex(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::SelectionDAG::getShiftAmountOperand(), llvm::SelectionDAG::getZExtOrTrunc(), isTruncateOf(), LowerScalarVariableShift(), ConsecutiveMemoryChainSorter::operator()(), partitionShuffleOfConcats(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::FastISel::SelectOperator(), llvm::TargetLowering::SimplifySetCC(), and useSinCos().
bool llvm::EVT::bitsLE (EVT VT) const inline
bitsLE - Return true if this has no more bits than VT.
Definition at line 741 of file ValueTypes.h.
References llvm::MVT::getSizeInBits(), and getSizeInBits().
Referenced by getCopyFromPartsVector(), getCopyToPartsVector(), GetFPLibCall(), llvm::SelectionDAG::getNode(), llvm::R600TargetLowering::ReplaceNodeResults(), llvm::SITargetLowering::shouldSplitVectorElementType(), and llvm::TargetLowering::SimplifySetCC().
bool llvm::EVT::bitsLT (EVT VT) const inline
bitsLT - Return true if this has less bits than VT.
Definition at line 735 of file ValueTypes.h.
References llvm::MVT::getSizeInBits(), and getSizeInBits().
Referenced by llvm::X86TargetLowering::BuildFILD(), BuildVectorFromScalar(), computeBytesPoppedByCallee(), llvm::createAMDGPUISelDag(), ExpandUnalignedLoad(), getCopyFromParts(), llvm::SelectionDAG::getLoad(), getMemsetStores(), llvm::SelectionDAG::getNode(), llvm::FastISel::getRegForGEPIndex(), llvm::GetReturnInfo(), llvm::SelectionDAG::getTruncStore(), isTruncateOf(), LowerLabelRef(), LowerScalarVariableShift(), ConsecutiveMemoryChainSorter::operator()(), OptimizeNoopCopyExpression(), partitionShuffleOfConcats(), llvm::FastISel::SelectOperator(), llvm::TargetLowering::SimplifySetCC(), and useSinCos().
EVT llvm::EVT::changeVectorElementTypeToInteger () const inline
changeVectorElementTypeToInteger - Return a vector with the same number of elements as this vector, but with the element type converted to an integer type with the same bitwidth.
Definition at line 626 of file ValueTypes.h.
References llvm::MVT::getIntegerVT(), llvm::MVT::getSizeInBits(), llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), llvm::MVT::getVectorVT(), and llvm::MVT::SimpleTy.
Referenced by ExtendUsesToFormExtLoad(), llvm::R600TargetLowering::getSetCCResultType(), llvm::SparcTargetLowering::getSetCCResultType(), llvm::SystemZTargetLowering::getSetCCResultType(), llvm::MipsTargetLowering::getSetCCResultType(), llvm::ARMTargetLowering::getSetCCResultType(), llvm::AArch64TargetLowering::getSetCCResultType(), llvm::PPCTargetLowering::getSetCCResultType(), llvm::X86TargetLowering::getSetCCResultType(), and lowerVECTOR_SHUFFLE_VSHF().
EVT EVT::getEVT (Type * Ty, bool HandleUnknown = false) static
getEVT - Return the value type corresponding to the specified type. This returns all pointers as iPTR. If HandleUnknown is true, unknown types are returned as Other, otherwise they are invalid.
getEVT - Return the value type corresponding to the specified type. This returns all pointers as MVT::iPTR. If HandleUnknown is true, unknown types are returned as Other, otherwise they are invalid.
Definition at line 275 of file ValueTypes.cpp.
References getBitWidth(), llvm::Type::getContext(), llvm::SequentialType::getElementType(), getIntegerVT(), llvm::VectorType::getNumElements(), llvm::Type::getTypeID(), getVectorVT(), llvm::MVT::getVT(), llvm::Type::IntegerTyID, and llvm::Type::VectorTyID.
Referenced by llvm::ARMTargetLowering::allowTruncateForTailCall(), llvm::X86TargetLowering::allowTruncateForTailCall(), llvm::Intrinsic::getName(), llvm::FastISel::getRegForGEPIndex(), llvm::TargetLoweringBase::getValueType(), INITIALIZE_PASS(), isNoopBitcast(), llvm::HexagonTargetLowering::isTruncateFree(), and llvm::FastISel::leaveLocalValueArea().
std::string EVT::getEVTString () const
getEVTString - This function returns value type as a string, e.g. "i32".
getEVTString - This function returns value type as a string, e.g. "i32".
Definition at line 106 of file ValueTypes.cpp.
References llvm::MVT::f128, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, getEVTString(), getSizeInBits(), getVectorElementType(), getVectorNumElements(), llvm::MVT::Glue, llvm::MVT::i1, llvm::MVT::i128, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, isInteger(), isVector(), llvm::MVT::isVoid, llvm_unreachable, llvm::MVT::Metadata, llvm::MVT::Other, llvm::MVT::ppcf128, llvm::MVT::SimpleTy, llvm::MVT::Untyped, llvm::utostr(), llvm::MVT::v16f32, llvm::MVT::v16i1, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i64, llvm::MVT::v16i8, llvm::MVT::v1f32, llvm::MVT::v1f64, llvm::MVT::v1i16, llvm::MVT::v1i32, llvm::MVT::v1i64, llvm::MVT::v1i8, llvm::MVT::v2f16, llvm::MVT::v2f32, llvm::MVT::v2f64, llvm::MVT::v2i1, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v2i8, llvm::MVT::v32i1, llvm::MVT::v32i16, llvm::MVT::v32i8, llvm::MVT::v4f16, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i1, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v4i8, llvm::MVT::v64i1, llvm::MVT::v64i8, llvm::MVT::v8f16, llvm::MVT::v8f32, llvm::MVT::v8f64, llvm::MVT::v8i1, llvm::MVT::v8i16, llvm::MVT::v8i32, llvm::MVT::v8i64, llvm::MVT::v8i8, and llvm::MVT::x86mmx.
Referenced by llvm::Hexagon_CCState::AnalyzeCallOperands(), llvm::CCState::AnalyzeCallOperands(), llvm::MipsTargetLowering::MipsCC::analyzeCallOperands(), llvm::Hexagon_CCState::AnalyzeCallResult(), llvm::CCState::AnalyzeCallResult(), llvm::Hexagon_CCState::AnalyzeFormalArguments(), llvm::CCState::AnalyzeFormalArguments(), llvm::MipsTargetLowering::MipsCC::analyzeFormalArguments(), llvm::Hexagon_CCState::AnalyzeReturn(), llvm::CCState::AnalyzeReturn(), getEVTString(), llvm::Intrinsic::getName(), isLocalCall(), and llvm::SDNode::print_types().
static EVT llvm::EVT::getFloatingPointVT (unsigned BitWidth) inline static
getFloatingPointVT - Returns the EVT that represents a floating point type with the given number of bits. There are two floating point types with 128 bits - this returns f128 rather than ppcf128.
Definition at line 601 of file ValueTypes.h.
References llvm::MVT::getFloatingPointVT().
Referenced by IsSingleInstrConstant(), lowerFP_TO_SINT_STORE(), llvm::MipsTargetLowering::lowerSTORE(), and LowerVECTOR_SHUFFLE().
EVT llvm::EVT::getHalfSizedIntegerVT (LLVMContext & Context) const inline
getHalfSizedIntegerVT - Finds the smallest simple value type that is greater than or equal to half the width of this EVT. If no simple value type can be found, an extended integer value type of half the size (rounded up) is returned.
Definition at line 812 of file ValueTypes.h.
References llvm::MVT::FIRST_INTEGER_VALUETYPE, llvm::MVT::getIntegerVT(), llvm::MVT::getSizeInBits(), getSizeInBits(), llvm::MVT::isInteger(), llvm::MVT::isVector(), and llvm::MVT::LAST_INTEGER_VALUETYPE.
Referenced by ExpandUnalignedStore().
static EVT llvm::EVT::getIntegerVT (LLVMContext & Context, unsigned BitWidth) inline static
getIntegerVT - Returns the EVT that represents an integer with the given number of bits.
Definition at line 607 of file ValueTypes.h.
References llvm::MVT::getIntegerVT(), M, and llvm::MVT::SimpleTy.
Referenced by canFoldInAddressingMode(), llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), ExpandUnalignedLoad(), ExpandUnalignedStore(), llvm::FastISel::FastEmitBranch(), getBuildPairElt(), getCopyFromParts(), getCopyToParts(), getEVT(), getTruncatedArgReg(), llvm::TargetLoweringBase::getTypeConversion(), llvm::MVT::getVT(), isConstantSplatVector(), isTruncateOf(), MatchRotateHalf(), ConsecutiveMemoryChainSorter::operator()(), llvm::DAGTypeLegalizer::run(), llvm::TargetLowering::TargetLoweringOpt::ShrinkDemandedOp(), ShrinkLoadReplaceStoreWithStore(), llvm::TargetLowering::SimplifySetCC(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), and useSinCos().
EVT llvm::EVT::getPow2VectorType (LLVMContext & Context) const inline
getPow2VectorType - Widens the length of the given vector EVT up to the nearest power of 2 and returns that type.
Definition at line 832 of file ValueTypes.h.
References llvm::MVT::getVectorElementType(), llvm::MVT::getVectorNumElements(), getVectorVT(), llvm::MVT::isPow2VectorType(), and llvm::Log2_32_Ceil().
Referenced by llvm::TargetLoweringBase::getTypeConversion().
intptr_t llvm::EVT::getRawBits () const inline
Definition at line 857 of file ValueTypes.h.
References llvm::MVT::SimpleTy.
Referenced by AddNodeIDCustom(), llvm::SelectionDAG::getAtomic(), llvm::SelectionDAG::getIndexedStore(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getTruncStore(), and llvm::SelectionDAG::getVTList().
EVT llvm::EVT::getRoundIntegerType (LLVMContext & Context) const inline
getRoundIntegerType - Rounds the bit-width of the given integer EVT up to the nearest power of two (and at least to eight), and returns the integer EVT with that number of bits.
Definition at line 800 of file ValueTypes.h.
References llvm::MVT::getIntegerVT(), llvm::MVT::getSizeInBits(), llvm::MVT::i8, llvm::MVT::isInteger(), llvm::MVT::isVector(), and llvm::Log2_32_Ceil().
Referenced by llvm::TargetLoweringBase::getTypeConversion().
EVT llvm::EVT::getScalarType () const inline
getScalarType - If this is a vector type, return the element type, otherwise return this.
Definition at line 756 of file ValueTypes.h.
References llvm::MVT::getVectorElementType(), and llvm::MVT::isVector().
Referenced by llvm::SelectionDAG::ComputeMaskedBits(), llvm::AMDGPUTargetLowering::computeMaskedBitsForTargetNode(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::X86TargetLowering::ComputeNumSignBitsForTargetNode(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), llvm::SelectionDAG::EVTToAPFloatSemantics(), ExpandUnalignedLoad(), ExtendUsesToFormExtLoad(), llvm::SelectionDAG::FoldConstantArithmetic(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), getCopyFromPartsVector(), llvm::DAGTypeLegalizer::getDAG(), llvm::SelectionDAG::getLoad(), getMemsetValue(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNOT(), llvm::SelectionDAG::getTruncStore(), getVLDSTRegisterUpdateOpcode(), llvm::SelectionDAG::getZeroExtendInReg(), isConstantSplatVector(), llvm::SITargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::SystemZTargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::AArch64TargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::PPCTargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::X86TargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::AMDGPUTargetLowering::isFPImmLegal(), llvm::AMDGPUTargetLowering::isLoadBitCastBeneficial(), isTruncateOf(), LowerIntVSETCC_AVX512(), LowerXALUO(), LowerZERO_EXTEND_AVX512(), MatchRotateHalf(), ConsecutiveMemoryChainSorter::operator()(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformFMACombine(), PerformLOADCombine(), PerformSELECTCombine(), PerformSTORECombine(), llvm::AMDGPUTargetLowering::ShouldShrinkFPConstant(), llvm::SelectionDAG::SignBitIsZero(), llvm::TargetLowering::SimplifyDemandedBits(), SplitVSETCC(), useSinCos(), ValueHasExactlyOneBitSet(), and WidenMaskArithmetic().
MVT llvm::EVT::getSimpleVT () const inline
getSimpleVT - Return the SimpleValueType held in the specified simple EVT.
Definition at line 749 of file ValueTypes.h.
Referenced by AddCombineToVPADDL(), llvm::MipsSETargetLowering::allowsUnalignedMemoryAccesses(), llvm::ARMTargetLowering::allowsUnalignedMemoryAccesses(), llvm::PPCTargetLowering::allowsUnalignedMemoryAccesses(), AnalyzeReturnValues(), llvm::X86TargetLowering::BuildFILD(), CalculateStackSlotSize(), canFoldInAddressingMode(), computeBytesPoppedByCallee(), llvm::SelectionDAG::DeleteNode(), llvm::SelectionDAG::EVTToAPFloatSemantics(), ExpandUnalignedLoad(), llvm::FastISel::FastEmitBranch(), FindOptimalMemOpLowering(), llvm::SelectionDAG::FoldSetCC(), getAL(), getCmpXChgOpcode(), getCodeAddrSpace(), getComparePred(), getExtensionTo64Bits(), GetFPLibCall(), getLoadOpcode(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getNumRegisters(), llvm::TargetLoweringBase::getOperationAction(), getPseudoCMOVOpc(), llvm::FastISel::getRegForGEPIndex(), llvm::FastISel::getRegForValue(), llvm::TargetLoweringBase::getRegisterType(), llvm::SDValue::getSimpleValueType(), getTargetVShiftNode(), llvm::TargetLoweringBase::getTypeConversion(), llvm::TargetLoweringBase::getTypeLegalizationCost(), llvm::SelectionDAGBuilder::getValueImpl(), llvm::SelectionDAG::getValueType(), getVCmpEQInst(), llvm::TargetLoweringBase::getVectorTypeBreakdown(), getVLDSTRegisterUpdateOpcode(), llvm::Hexagon_CCState::HandleByVal(), llvm::ISD::InputArg::InputArg(), is32Bit(), isADDADDMUL(), isConstantSplatVector(), llvm::SITargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::SystemZTargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::AArch64TargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::PPCTargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::X86TargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::AMDGPUTargetLowering::isFPImmLegal(), llvm::TargetLoweringBase::isIndexedLoadLegal(), llvm::TargetLoweringBase::isIndexedStoreLegal(), isLegalAddressImmediate(), llvm::ARMTargetLowering::isLegalAddressingMode(), isLegalT1AddressImmediate(), isLegalT2AddressImmediate(), llvm::ARMTargetLowering::isLegalT2ScaledAddressingMode(), llvm::TargetLoweringBase::isLoadExtLegal(), llvm::X86TargetLowering::isShuffleMaskLegal(), llvm::HexagonTargetLowering::isTruncateFree(), llvm::TargetLoweringBase::isTruncStoreLegal(), llvm::TargetLoweringBase::isTypeLegal(), isValidIndexedLoad(), llvm::X86TargetLowering::isVectorClearMaskLegal(), llvm::XCoreTargetLowering::isZExtFree(), llvm::ARMTargetLowering::isZExtFree(), llvm::X86TargetLowering::isZExtFree(), llvm::FastISel::leaveLocalValueArea(), Lower256IntArith(), llvm::ARMTargetLowering::LowerAsmOperandForConstraint(), LowerCMP_SWAP(), llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerOperation(), LowerScalarVariableShift(), LowerShift(), LowerToTLSExecModel(), LowerXALUO(), LowerZERO_EXTEND_AVX512(), matchIntegerMINMAX(), llvm::ISD::OutputArg::OutputArg(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::R600TargetLowering::ReplaceNodeResults(), llvm::X86InstrInfo::shouldScheduleLoadsNear(), llvm::AMDGPUTargetLowering::ShouldShrinkFPConstant(), llvm::TargetLowering::SimplifySetCC(), useSinCos(), llvm::SelectionDAGBuilder::visitBitTestHeader(), X86ChooseCmpImmediateOpcode(), X86ChooseCmpOpcode(), and XFormVExtractWithShuffleIntoLoad().
unsigned llvm::EVT::getSizeInBits () const inline
getSizeInBits - Return the size of the specified value type in bits.
Definition at line 779 of file ValueTypes.h.
References llvm::MVT::getSizeInBits().
Referenced by AddRequiredExtensionForVMULL(), adjustForTestUnderMask(), bitsEq(), bitsGE(), bitsGT(), bitsLE(), bitsLT(), llvm::X86TargetLowering::BuildFILD(), llvm::TargetLowering::BuildSDIV(), BuildVectorFromScalar(), CalculateStackSlotSize(), CalculateTailCallArgDest(), CombineBaseUpdate(), computeBytesPoppedByCallee(), llvm::SelectionDAG::ComputeMaskedBits(), llvm::AMDGPUTargetLowering::computeMaskedBitsForTargetNode(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::X86TargetLowering::ComputeNumSignBitsForTargetNode(), llvm::FunctionLoweringInfo::ComputePHILiveOutRegInfo(), ComputeRange(), ConstantAddressBlock(), EltsFromConsecutiveLoads(), llvm::MipsTargetLowering::EmitInstrWithCustomInserter(), llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc(), llvm::X86SelectionDAGInfo::EmitTargetCodeForMemset(), ExpandUnalignedLoad(), ExpandUnalignedStore(), ExtendUsesToFormExtLoad(), ExtractSubVector(), llvm::FastISel::FastEmitBranch(), FindBaseOffset(), findMaskedBFI(), FindMemType(), FindOptimalMemOpLowering(), FuncIsMadeTailCallSafe(), genConstMult(), GeneratePerfectShuffle(), getBuildPairElt(), llvm::SelectionDAG::getConstant(), getCopyFromParts(), getCopyFromPartsVector(), getCopyToParts(), getCopyToPartsVector(), getEVTString(), getExtensionTo64Bits(), GetFPLibCall(), getHalfSizedIntegerVT(), getMemcpyLoadsAndStores(), getMemmoveLoadsAndStores(), getMemsetStores(), getMemsetStringVal(), getMemsetValue(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getNOT(), llvm::TargetLoweringBase::getNumRegisters(), getOpenCLAlignment(), llvm::MipsTargetLowering::getOpndList(), llvm::HexagonTargetLowering::getPostIndexedAddressParts(), llvm::NVPTXTargetLowering::getPrototype(), llvm::FastISel::getRegForValue(), getTargetVShiftByConstNode(), llvm::TargetLoweringBase::getTypeConversion(), llvm::SDValue::getValueSizeInBits(), llvm::TargetLoweringBase::getVectorTypeBreakdown(), getVLDSTRegisterUpdateOpcode(), llvm::SelectionDAG::getZeroExtendInReg(), getZeroVector(), insertDAGNode(), InsertFenceForAtomic(), InsertSubVector(), isADDADDMUL(), isBSwapHWordElement(), llvm::ISD::isBuildVectorAllOnes(), isConditionalZeroOrAllOnes(), llvm::SelectionDAG::isConsecutiveLoad(), isConsecutiveLS(), llvm::BuildVectorSDNode::isConstantSplat(), isConstantSplatVector(), isExtendedBUILD_VECTOR(), llvm::AMDGPUTargetLowering::isLoadBitCastBeneficial(), isLocalCall(), isMOVLMask(), isREVMask(), isScaledConstantInRange(), isSequentialInRange(), llvm::ARMTargetLowering::isShuffleMaskLegal(), llvm::X86TargetLowering::isShuffleMaskLegal(), isSimpleShift(), IsSingleInstrConstant(), llvm::MSP430TargetLowering::isTruncateFree(), llvm::SystemZTargetLowering::isTruncateFree(), llvm::X86TargetLowering::isTruncateFree(), isTruncateOf(), isVREVMask(), isVShiftLImm(), isVShiftRImm(), isVTRN_v_undef_Mask(), isVTRNMask(), isVUZP_v_undef_Mask(), isVUZPMask(), isVZIP_v_undef_Mask(), isVZIPMask(), LowerADJUST_TRAMPOLINE(), llvm::AArch64TargetLowering::LowerBUILD_VECTOR(), llvm::NVPTXTargetLowering::LowerCall(), llvm::TargetLowering::LowerCallTo(), LowerCTLZ(), LowerCTLZ_ZERO_UNDEF(), LowerCTTZ(), LowerEXTRACT_VECTOR_ELT(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::SystemZTargetLowering::LowerFormalArguments(), LowerIntVSETCC_AVX512(), LowerLabelRef(), lowerMSABitClearImm(), llvm::SITargetLowering::LowerOperation(), llvm::NVPTXTargetLowering::LowerOperation(), llvm::NVPTXTargetLowering::LowerReturn(), LowerSDIV(), LowerToTLSExecModel(), LowerVAARG(), llvm::AArch64TargetLowering::LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE(), LowerVectorBroadcast(), LowerVSETCC(), LowerXALUO(), maskMatters(), MatchingStackOffset(), MatchRotateHalf(), ConsecutiveMemoryChainSorter::operator()(), partitionShuffleOfConcats(), performANDCombine(), PerformANDCombine(), PerformAndCombine(), PerformARMBUILD_VECTORCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), performDSPShiftCombine(), PerformEXTRACT_VECTOR_ELTCombine(), performIntegerAbsCombine(), PerformIntrinsicCombine(), PerformLOADCombine(), performORCombine(), PerformOrCombine(), PerformSELECTCombine(), PerformSExtCombine(), performShiftToAllZeros(), PerformSIGN_EXTEND_INREGCombine(), performSRACombine(), PerformSRACombine(), PerformSTORECombine(), PerformVDUPLANECombine(), PerformVZEXT_MOVLCombine(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::DAGTypeLegalizer::run(), llvm::SelectionDAGISel::SelectCodeCommon(), llvm::SITargetLowering::shouldSplitVectorElementType(), llvm::SelectionDAG::SignBitIsZero(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifySetCC(), SkipExtensionForVMULL(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), SplitVSETCC(), tryCombineToBFI(), tryCombineToEXTR(), tryCombineToLargerBFI(), useSinCos(), ValueHasExactlyOneBitSet(), VerifyNodeCommon(), llvm::SelectionDAGBuilder::visitBitTestHeader(), and WidenMaskArithmetic().
unsigned llvm::EVT::getStoreSize () const inline
getStoreSize - Return the number of bytes overwritten by a store of the specified value type.
Definition at line 787 of file ValueTypes.h.
References llvm::MVT::getSizeInBits().
Referenced by ComputePTXValueVTs(), llvm::SelectionDAG::CreateStackTemporary(), findConsecutiveLoad(), llvm::SelectionDAG::getAtomic(), llvm::SelectionDAG::getLoad(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTruncStore(), isConstantSplatVector(), isOnlyUsedInEntryBlock(), LowerADDC_ADDE_SUBC_SUBE(), maskMatters(), llvm::MemSDNode::MemSDNode(), llvm::PPCTargetLowering::PerformDAGCombine(), and ShrinkLoadReplaceStoreWithStore().
unsigned llvm::EVT::getStoreSizeInBits () const inline
getStoreSizeInBits - Return the number of bits overwritten by a store of the specified value type.
Definition at line 793 of file ValueTypes.h.
References llvm::MVT::getStoreSize().
Referenced by adjustSubwordCmp(), llvm::SelectionDAG::CreateStackTemporary(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), ExpandUnalignedLoad(), isTruncateOf(), and llvm::NVPTXTargetLowering::LowerCall().
Type * EVT::getTypeForEVT (LLVMContext & Context) const
getTypeForEVT - This method returns an LLVM type corresponding to the specified EVT. For integer types, this returns an unsigned type. Note that this will abort for types that cannot be represented.
Definition at line 180 of file ValueTypes.cpp.
References llvm::MVT::f128, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, llvm::IntegerType::get(), llvm::VectorType::get(), llvm::Type::getDoubleTy(), llvm::Type::getFloatTy(), llvm::Type::getFP128Ty(), llvm::Type::getHalfTy(), llvm::Type::getInt16Ty(), llvm::Type::getInt1Ty(), llvm::Type::getInt32Ty(), llvm::Type::getInt64Ty(), llvm::Type::getInt8Ty(), llvm::Type::getMetadataTy(), llvm::Type::getPPC_FP128Ty(), llvm::Type::getVoidTy(), llvm::Type::getX86_FP80Ty(), llvm::Type::getX86_MMXTy(), llvm::MVT::i1, llvm::MVT::i128, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, isExtended(), llvm::MVT::isVoid, llvm::MVT::Metadata, llvm::MVT::ppcf128, llvm::MVT::SimpleTy, llvm::MVT::v16f32, llvm::MVT::v16i1, llvm::MVT::v16i16, llvm::MVT::v16i32, llvm::MVT::v16i64, llvm::MVT::v16i8, llvm::MVT::v1f32, llvm::MVT::v1f64, llvm::MVT::v1i16, llvm::MVT::v1i32, llvm::MVT::v1i64, llvm::MVT::v1i8, llvm::MVT::v2f16, llvm::MVT::v2f32, llvm::MVT::v2f64, llvm::MVT::v2i1, llvm::MVT::v2i16, llvm::MVT::v2i32, llvm::MVT::v2i64, llvm::MVT::v2i8, llvm::MVT::v32i1, llvm::MVT::v32i16, llvm::MVT::v32i8, llvm::MVT::v4f16, llvm::MVT::v4f32, llvm::MVT::v4f64, llvm::MVT::v4i1, llvm::MVT::v4i16, llvm::MVT::v4i32, llvm::MVT::v4i64, llvm::MVT::v4i8, llvm::MVT::v64i1, llvm::MVT::v64i8, llvm::MVT::v8f16, llvm::MVT::v8f32, llvm::MVT::v8f64, llvm::MVT::v8i1, llvm::MVT::v8i16, llvm::MVT::v8i32, llvm::MVT::v8i64, llvm::MVT::v8i8, and llvm::MVT::x86mmx.
Referenced by canFoldInAddressingMode(), llvm::SelectionDAG::CreateStackTemporary(), llvm::XCoreTargetLowering::EmitInstrWithCustomInserter(), ExpandUnalignedLoad(), getBuildPairElt(), getMemsetStringVal(), llvm::TargetLoweringBase::getValueType(), isOnlyUsedInEntryBlock(), isWordAligned(), isXor1OfSetCC(), LowerADDC_ADDE_SUBC_SUBE(), llvm::ARMTargetLowering::LowerAsmOperandForConstraint(), llvm::NVPTXTargetLowering::LowerCall(), llvm::TargetLowering::LowerCallTo(), llvm::SparcTargetLowering::LowerF128_LibCallArg(), llvm::SparcTargetLowering::LowerF128Op(), llvm::AArch64TargetLowering::LowerF128ToCall(), llvm::R600TargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerFormalArguments(), LowerFSINCOS(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::TargetLowering::makeLibCall(), ConsecutiveMemoryChainSorter::operator()(), llvm::PPCTargetLowering::PerformDAGCombine(), llvm::R600TargetLowering::ReplaceNodeResults(), llvm::DAGTypeLegalizer::run(), llvm::SITargetLowering::shouldSplitVectorElementType(), ShrinkLoadReplaceStoreWithStore(), useDivRem(), useSinCos(), VerifyMachineNode(), and XFormVExtractWithShuffleIntoLoad().
EVT llvm::EVT::getVectorElementType () const inline
getVectorElementType - Given a vector type, return the type of each element.
Definition at line 762 of file ValueTypes.h.
References llvm::MVT::getVectorElementType(), and llvm::MVT::isVector().
Referenced by AddCombineToVPADDL(), BuildVectorFromScalar(), ComputePTXValueVTs(), ConstantAddressBlock(), llvm::createAMDGPUISelDag(), EltsFromConsecutiveLoads(), ExpandUnalignedLoad(), ExtractSubVector(), FindMemType(), GeneratePerfectShuffle(), getBuildPairElt(), getCodeAddrSpace(), getCopyFromPartsVector(), getCopyToPartsVector(), getEVTString(), GetFPLibCall(), getMemsetStringVal(), llvm::SelectionDAG::getNode(), getShuffleScalarElt(), llvm::SelectionDAG::GetSplitDestVTs(), getTargetVShiftByConstNode(), getTargetVShiftNode(), llvm::TargetLoweringBase::getTypeConversion(), llvm::TargetLoweringBase::getVectorTypeBreakdown(), getVLDSTRegisterUpdateOpcode(), InsertSubVector(), llvm::ISD::isBuildVectorAllOnes(), llvm::BuildVectorSDNode::isConstantSplat(), isConstantSplatVector(), isExtendedBUILD_VECTOR(), isMOVLMask(), isREVMask(), isSequentialInRange(), llvm::ARMTargetLowering::isShuffleMaskLegal(), IsSingleInstrConstant(), isSplatVector(), isTruncateOf(), isVREVMask(), isVShiftLImm(), isVShiftRImm(), isVTRN_v_undef_Mask(), isVTRNMask(), isVUZP_v_undef_Mask(), isVUZPMask(), isVZIP_v_undef_Mask(), isVZIPMask(), Lower256IntArith(), llvm::AArch64TargetLowering::LowerBUILD_VECTOR(), llvm::NVPTXTargetLowering::LowerCall(), LowerCTPOP(), LowerEXTRACT_VECTOR_ELT(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), LowerIntVSETCC_AVX512(), lowerMSABitClearImm(), lowerMSACopyIntr(), llvm::NVPTXTargetLowering::LowerOperation(), llvm::NVPTXTargetLowering::LowerReturn(), LowerScalarVariableShift(), LowerSDIV(), LowerShift(), llvm::AArch64TargetLowering::LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE_VSHF(), LowerVectorFP_TO_INT(), LowerVectorINT_TO_FP(), LowerVSETCC(), LowerXALUO(), ConsecutiveMemoryChainSorter::operator()(), partitionShuffleOfConcats(), PerformARMBUILD_VECTORCombine(), PerformBUILD_VECTORCombine(), performDSPShiftCombine(), PerformEXTRACT_VECTOR_ELTCombine(), PerformInsertEltCombine(), PerformIntrinsicCombine(), PerformLOADCombine(), PerformOrCombine(), PerformSELECTCombine(), performShiftToAllZeros(), PerformShuffleCombine(), PerformSTORECombine(), PerformVDUPLANECombine(), PerformVZEXT_MOVLCombine(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::R600TargetLowering::ReplaceNodeResults(), llvm::DAGTypeLegalizer::run(), SkipExtensionForVMULL(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), llvm::AMDGPUTargetLowering::SplitVectorStore(), llvm::SelectionDAG::UnrollVectorOp(), useSinCos(), and VerifyNodeCommon().
unsigned llvm::EVT::getVectorNumElements () const inline
getVectorNumElements - Given a vector type, return the number of elements it contains.
Definition at line 771 of file ValueTypes.h.
References llvm::MVT::getVectorNumElements(), and llvm::MVT::isVector().
Referenced by AddCombineToVPADDL(), AddNodeIDCustom(), llvm::X86TargetLowering::BuildFILD(), BuildSplatI(), BuildVectorFromScalar(), CombineBaseUpdate(), llvm::AMDGPUTargetLowering::computeMaskedBitsForTargetNode(), ComputePTXValueVTs(), ConstantAddressBlock(), llvm::createAMDGPUISelDag(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), ExpandUnalignedLoad(), ExtractSubVector(), getBuildPairElt(), getBuildVectorSplat(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), getCopyFromPartsVector(), getCopyToPartsVector(), getEVTString(), getGatherNode(), llvm::SelectionDAG::getLoad(), llvm::ShuffleVectorSDNode::getMask(), getMemsetStringVal(), getMGatherNode(), getMOVL(), getMScatterNode(), llvm::SelectionDAG::getNode(), getScatterNode(), llvm::SITargetLowering::getSetCCResultType(), llvm::NVPTXTargetLowering::getSetCCResultType(), llvm::HexagonTargetLowering::getSetCCResultType(), llvm::X86TargetLowering::getSetCCResultType(), getShuffleScalarElt(), llvm::ShuffleVectorSDNode::getSplatIndex(), llvm::SelectionDAG::GetSplitDestVTs(), getTruncatedArgReg(), llvm::SelectionDAG::getTruncStore(), llvm::TargetLoweringBase::getTypeConversion(), llvm::SelectionDAG::getVectorShuffle(), llvm::TargetLoweringBase::getVectorTypeBreakdown(), getVLDSTRegisterUpdateOpcode(), hasNormalLoadOperand(), isConstantOrUndefBUILD_VECTOR(), isConstantSplatVector(), isConstVecPow2(), llvm::AArch64TargetLowering::isKnownShuffleVector(), isMOVLMask(), isPermuteMask(), isReverseMask(), isREVMask(), isSequentialInRange(), isShuffleHigh128VectorInsertLow(), isShuffleLow128VectorInsertHigh(), llvm::ARMTargetLowering::isShuffleMaskLegal(), IsSingleInstrConstant(), isSingletonVEXTMask(), llvm::ShuffleVectorSDNode::isSplatMask(), isTruncateOf(), isVEXTMask(), isVREVMask(), isVTRN_v_undef_Mask(), isVTRNMask(), isVUZP_v_undef_Mask(), isVUZPMask(), isVZIP_v_undef_Mask(), isVZIPMask(), isZeroShuffle(), Lower256IntArith(), llvm::AArch64TargetLowering::LowerBUILD_VECTOR(), llvm::NVPTXTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::AMDGPUTargetLowering::LowerGlobalAddress(), lowerMSABitClearImm(), lowerMSASplatZExt(), llvm::NVPTXTargetLowering::LowerOperation(), llvm::NVPTXTargetLowering::LowerReturn(), LowerScalarImmediateShift(), LowerScalarVariableShift(), LowerSDIV(), LowerShift(), llvm::AArch64TargetLowering::LowerVECTOR_SHUFFLE(), LowerVECTOR_SHUFFLE(), lowerVECTOR_SHUFFLE_ILVEV(), lowerVECTOR_SHUFFLE_ILVL(), lowerVECTOR_SHUFFLE_ILVOD(), lowerVECTOR_SHUFFLE_ILVR(), lowerVECTOR_SHUFFLE_VSHF(), LowerVectorAllZeroTest(), LowerXALUO(), MatchRotateHalf(), ConsecutiveMemoryChainSorter::operator()(), partitionShuffleOfConcats(), PerformARMBUILD_VECTORCombine(), PerformBUILD_VECTORCombine(), llvm::R600TargetLowering::PerformDAGCombine(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformInsertEltCombine(), PerformSELECTCombine(), PerformShuffleCombine(), PerformShuffleCombine256(), PerformSTORECombine(), PerformVCVTCombine(), PerformVDIVCombine(), PerformVECTOR_SHUFFLECombine(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::R600TargetLowering::ReplaceNodeResults(), llvm::DAGTypeLegalizer::run(), llvm::SelectionDAG::SplitVector(), llvm::AMDGPUTargetLowering::SplitVectorLoad(), llvm::AMDGPUTargetLowering::SplitVectorStore(), useSinCos(), VerifyNodeCommon(), WidenMaskArithmetic(), and XFormVExtractWithShuffleIntoLoad().
static EVT llvm::EVT::getVectorVT (LLVMContext & Context, EVT VT, unsigned NumElements) inline static
getVectorVT - Returns the EVT that represents a vector NumElements in length, where each element is of type VT.
Definition at line 616 of file ValueTypes.h.
References llvm::MVT::getVectorVT(), M, and llvm::MVT::SimpleTy.
Referenced by llvm::X86TargetLowering::BuildFILD(), buildFromShuffleMostly(), BuildVectorFromScalar(), ConstantAddressBlock(), ExtractSubVector(), getBuildPairElt(), llvm::SelectionDAG::getConstant(), getEVT(), getMemsetStringVal(), getPow2VectorType(), llvm::HexagonTargetLowering::getSetCCResultType(), llvm::SelectionDAG::GetSplitDestVTs(), llvm::AArch64TargetLowering::getTgtMemIntrinsic(), llvm::ARMTargetLowering::getTgtMemIntrinsic(), llvm::TargetLoweringBase::getTypeConversion(), llvm::TargetLoweringBase::getValueType(), llvm::TargetLoweringBase::getVectorTypeBreakdown(), getVLDSTRegisterUpdateOpcode(), llvm::MVT::getVT(), IsSingleInstrConstant(), isTruncateOf(), LowerAsSplatVectorLoad(), llvm::NVPTXTargetLowering::LowerCall(), llvm::NVPTXTargetLowering::LowerFormalArguments(), llvm::NVPTXTargetLowering::LowerReturn(), LowerVECTOR_SHUFFLE(), LowerXALUO(), LowerZERO_EXTEND(), MatchRotateHalf(), ConsecutiveMemoryChainSorter::operator()(), PerformARMBUILD_VECTORCombine(), PerformBUILD_VECTORCombine(), PerformInsertEltCombine(), PerformLOADCombine(), PerformSTORECombine(), llvm::DAGTypeLegalizer::run(), llvm::SelectionDAG::UnrollVectorOp(), and useSinCos().
bool llvm::EVT::is1024BitVector () const inline
is1024BitVector - Return true if this is a 1024-bit vector type.
Definition at line 696 of file ValueTypes.h.
References llvm::MVT::is1024BitVector().
bool llvm::EVT::is128BitVector () const inline
is128BitVector - Return true if this is a 128-bit vector type.
Definition at line 681 of file ValueTypes.h.
References llvm::MVT::is128BitVector().
Referenced by AddRequiredExtensionForVMULL(), EmitTailCallStoreRetAddr(), FuncIsMadeTailCallSafe(), getVLDSTRegisterUpdateOpcode(), getVShift(), getZeroVector(), Insert128BitVector(), isMOVLMask(), llvm::ARMTargetLowering::isShuffleMaskLegal(), IsSingleInstrConstant(), isSplatVector(), llvm::AArch64TargetLowering::LowerBUILD_VECTOR(), LowerCONCAT_VECTORS(), LowerMUL(), LowerVectorAllZeroTest(), PerformANDCombine(), PerformMULCombine(), performORCombine(), PerformORCombine(), PerformSELECTCombine(), PerformShuffleCombine(), performVSELECTCombine(), performXORCombine(), and WidenMaskArithmetic().
bool llvm::EVT::is16BitVector () const inline
is16BitVector - Return true if this is a 16-bit vector type.
Definition at line 666 of file ValueTypes.h.
References llvm::MVT::is16BitVector().
bool llvm::EVT::is256BitVector () const inline
is256BitVector - Return true if this is a 256-bit vector type.
Definition at line 686 of file ValueTypes.h.
References llvm::MVT::is256BitVector().
Referenced by CanFoldXORWithAllOnes(), Extract128BitVector(), FuncIsMadeTailCallSafe(), getZeroVector(), Insert256BitVector(), Lower256IntArith(), LowerADD(), LowerMUL(), LowerShift(), LowerSUB(), LowerVectorAllZeroTest(), PerformSELECTCombine(), PerformShuffleCombine(), PerformZExtCombine(), and WidenMaskArithmetic().
bool llvm::EVT::is32BitVector () const inline
is32BitVector - Return true if this is a 32-bit vector type.
Definition at line 671 of file ValueTypes.h.
References llvm::MVT::is32BitVector().
bool llvm::EVT::is512BitVector () const inline
is512BitVector - Return true if this is a 512-bit vector type.
Definition at line 691 of file ValueTypes.h.
References llvm::MVT::is512BitVector().
Referenced by Extract128BitVector(), Extract256BitVector(), FuncIsMadeTailCallSafe(), getZeroVector(), and LowerVSETCC().
bool llvm::EVT::is64BitVector () const inline
is64BitVector - Return true if this is a 64-bit vector type.
Definition at line 676 of file ValueTypes.h.
References llvm::MVT::is64BitVector().
Referenced by CombineVLDDUP(), getCTPOP16BitCounts(), getVLDSTRegisterUpdateOpcode(), llvm::ARMTargetLowering::isShuffleMaskLegal(), isVUZP_v_undef_Mask(), isVUZPMask(), isVZIP_v_undef_Mask(), isVZIPMask(), lowerCTPOP16BitElements(), lowerCTPOP32BitElements(), LowerMUL(), and PerformMULCombine().
bool llvm::EVT::isByteSized () const inline
isByteSized - Return true if the bit size is a multiple of 8.
Definition at line 706 of file ValueTypes.h.
References llvm::MVT::getSizeInBits().
Referenced by ExpandUnalignedLoad(), GetFPLibCall(), and isOneUseSetCC().
bool llvm::EVT::isExtended () const inline
isExtended - Test if the given EVT is extended (as opposed to being simple).
Definition at line 646 of file ValueTypes.h.
Referenced by canFoldInAddressingMode(), llvm::SelectionDAG::DeleteNode(), llvm::TargetLoweringBase::getOperationAction(), getTypeForEVT(), llvm::SelectionDAG::getValueType(), and isTruncateOf().
bool llvm::EVT::isFloatingPoint () const inline
isFloatingPoint - Return true if this is a FP, or a vector FP type.
Definition at line 651 of file ValueTypes.h.
References llvm::MVT::isFloatingPoint().
Referenced by buildFromShuffleMostly(), createFPCmp(), EmitCMP(), emitCmp(), ExpandUnalignedLoad(), ExpandUnalignedStore(), FindOptimalMemOpLowering(), getBuildPairElt(), llvm::SelectionDAG::getConstantFP(), getCopyFromParts(), getCopyToParts(), llvm::SelectionDAG::getNode(), llvm::ARMTargetLowering::getSchedulingPreference(), llvm::SelectionDAGBuilder::getValueImpl(), INITIALIZE_PASS(), llvm::AMDGPUTargetLowering::isFAbsFree(), llvm::TargetLoweringBase::isFAbsFree(), llvm::AMDGPUTargetLowering::isFNegFree(), llvm::TargetLoweringBase::isFNegFree(), isLocalCall(), IsSingleInstrConstant(), llvm::ConstantFPSDNode::isValueValidForType(), isXor1OfSetCC(), LowerLabelRef(), llvm::AArch64TargetLowering::LowerVECTOR_SHUFFLE(), LowerVectorAllZeroTest(), LowerVSETCC(), llvm::X86TargetLowering::LowerXConstraint(), llvm::TargetLowering::LowerXConstraint(), ConsecutiveMemoryChainSorter::operator()(), PerformARMBUILD_VECTORCombine(), PerformSELECTCombine(), llvm::TargetLowering::SimplifyDemandedBits(), useSinCos(), and VerifyNodeCommon().
bool llvm::EVT::isInteger () const inline
isInteger - Return true if this is an integer, or a vector integer type.
Definition at line 656 of file ValueTypes.h.
References llvm::MVT::isInteger().
Referenced by AddCombineToVPADDL(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::NVPTXAsmPrinter::emitLineNumberAsDotLoc(), ExpandUnalignedLoad(), ExpandUnalignedStore(), llvm::SelectionDAG::FoldSetCC(), getBuildPairElt(), llvm::SelectionDAG::getConstant(), getCopyFromParts(), getCopyToParts(), llvm::DAGTypeLegalizer::getDAG(), getEVTString(), llvm::SelectionDAG::getLoad(), getMemcpyLoadsAndStores(), getMemsetStringVal(), getMemsetValue(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getNumRegisters(), getOpenCLAlignment(), llvm::NVPTXTargetLowering::getPrototype(), GetRegistersForValue(), llvm::TargetLoweringBase::getRegisterType(), llvm::GetReturnInfo(), llvm::TargetLoweringBase::getShiftAmountTy(), llvm::SelectionDAG::getTruncStore(), llvm::TargetLoweringBase::getTypeConversion(), llvm::SelectionDAGBuilder::getValueImpl(), INITIALIZE_PASS(), isBSwapHWordElement(), isConstantSplatVector(), isOneUseSetCC(), isSlicingProfitable(), isSplatVector(), llvm::MSP430TargetLowering::isTruncateFree(), llvm::SystemZTargetLowering::isTruncateFree(), llvm::X86TargetLowering::isTruncateFree(), isXor1OfSetCC(), llvm::XCoreTargetLowering::isZExtFree(), llvm::ARMTargetLowering::isZExtFree(), llvm::X86TargetLowering::isZExtFree(), Lower256IntArith(), LowerADD(), llvm::AArch64TargetLowering::LowerBR_CC(), LowerBR_CC(), llvm::NVPTXTargetLowering::LowerCall(), LowerLabelRef(), LowerMUL(), llvm::AArch64TargetLowering::LowerSELECT_CC(), LowerSELECT_CC(), llvm::AArch64TargetLowering::LowerSETCC(), LowerSUB(), LowerVectorBroadcast(), LowerVectorSETCC(), llvm::TargetLowering::LowerXConstraint(), MatchRotateHalf(), ConsecutiveMemoryChainSorter::operator()(), OptimizeConditionalInDecrement(), OptimizeNoopCopyExpression(), partitionShuffleOfConcats(), llvm::R600TargetLowering::PerformDAGCombine(), performIntegerAbsCombine(), performSELECTCombine(), PerformSELECTCombine(), performVSELECTCombine(), performXORCombine(), llvm::R600TargetLowering::ReplaceNodeResults(), llvm::SelectionDAGISel::runOnMachineFunction(), llvm::TargetLowering::SimplifySetCC(), useSinCos(), and VerifyNodeCommon().
bool llvm::EVT::isOverloaded () const inline
isOverloaded - Return true if this is an overloaded type for TableGen.
Definition at line 701 of file ValueTypes.h.
References llvm::MVT::fAny, llvm::MVT::iAny, llvm::MVT::iPTRAny, and llvm::MVT::vAny.
bool llvm::EVT::isPow2VectorType () const inline
isPow2VectorType - Returns true if the given vector is a power of 2.
Definition at line 825 of file ValueTypes.h.
References llvm::MVT::getVectorNumElements().
Referenced by llvm::TargetLoweringBase::getTypeConversion().
bool llvm::EVT::isRound () const inline
isRound - Return true if the size is a power-of-two number of bytes.
Definition at line 711 of file ValueTypes.h.
References llvm::MVT::getSizeInBits().
Referenced by isConstantSplatVector(), isTruncateOf(), and llvm::TargetLowering::SimplifySetCC().
bool llvm::EVT::isSimple () const inline
isSimple - Test if the given EVT is simple (as opposed to being extended).
Definition at line 640 of file ValueTypes.h.
References llvm::MVT::SimpleTy.
Referenced by llvm::SITargetLowering::allowsUnalignedMemoryAccesses(), llvm::PPCTargetLowering::allowsUnalignedMemoryAccesses(), llvm::AMDGPUTargetLowering::computeMaskedBitsForTargetNode(), llvm::FastISel::FastEmitBranch(), getComparePred(), getExtensionTo64Bits(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getNumRegisters(), llvm::FastISel::getRegForValue(), llvm::TargetLoweringBase::getRegisterType(), llvm::TargetLoweringBase::getTypeConversion(), llvm::SelectionDAG::getValueType(), isConstantSplatVector(), llvm::SITargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::SystemZTargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::AArch64TargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::PPCTargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::X86TargetLowering::isFMAFasterThanFMulAndFAdd(), llvm::TargetLoweringBase::isIndexedLoadLegal(), llvm::TargetLoweringBase::isIndexedStoreLegal(), isLegalAddressImmediate(), llvm::ARMTargetLowering::isLegalAddressingMode(), llvm::TargetLoweringBase::isLoadExtLegal(), llvm::X86TargetLowering::isShuffleMaskLegal(), llvm::HexagonTargetLowering::isTruncateFree(), llvm::TargetLoweringBase::isTruncStoreLegal(), llvm::TargetLoweringBase::isTypeLegal(), llvm::X86TargetLowering::isVectorClearMaskLegal(), llvm::XCoreTargetLowering::isZExtFree(), llvm::ARMTargetLowering::isZExtFree(), llvm::X86TargetLowering::isZExtFree(), llvm::FastISel::leaveLocalValueArea(), llvm::NVPTXTargetLowering::LowerOperation(), ConsecutiveMemoryChainSorter::operator()(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::TargetLowering::SimplifyDemandedBits(), and X86ChooseCmpImmediateOpcode().
bool llvm::EVT::isVector () const inline
isVector - Return true if this is a vector value type.
Definition at line 661 of file ValueTypes.h.
References llvm::MVT::isVector().
Referenced by llvm::X86TargetLowering::BuildFILD(), BuildVectorFromScalar(), llvm::SelectionDAG::ComputeMaskedBits(), llvm::AMDGPUTargetLowering::computeMaskedBitsForTargetNode(), llvm::SelectionDAG::ComputeNumSignBits(), ComputePTXValueVTs(), ConstantAddressBlock(), llvm::PPCTargetLowering::EmitInstrWithCustomInserter(), ExpandUnalignedLoad(), ExpandUnalignedStore(), ExtendUsesToFormExtLoad(), FindOptimalMemOpLowering(), FoldOperand(), llvm::SelectionDAG::FoldSetCC(), FuncIsMadeTailCallSafe(), getBuildPairElt(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getConstantFP(), getCopyFromParts(), getCopyFromPartsVector(), getCopyToParts(), getCopyToPartsVector(), llvm::DAGTypeLegalizer::getDAG(), getEVTString(), llvm::SelectionDAG::getLoad(), getMemcpyLoadsAndStores(), getMemsetStores(), getMemsetStringVal(), llvm::SelectionDAG::getNode(), llvm::TargetLoweringBase::getNumRegisters(), llvm::AMDGPUTargetLowering::getOriginalFunctionArgs(), llvm::PPCTargetLowering::getPreIndexedAddressParts(), GetRegistersForValue(), llvm::TargetLoweringBase::getRegisterType(), llvm::ARMTargetLowering::getSchedulingPreference(), llvm::SelectionDAG::getSelect(), llvm::SelectionDAG::getSetCC(), llvm::R600TargetLowering::getSetCCResultType(), llvm::SITargetLowering::getSetCCResultType(), llvm::SparcTargetLowering::getSetCCResultType(), llvm::NVPTXTargetLowering::getSetCCResultType(), llvm::HexagonTargetLowering::getSetCCResultType(), llvm::SystemZTargetLowering::getSetCCResultType(), llvm::TargetLoweringBase::getSetCCResultType(), llvm::MipsTargetLowering::getSetCCResultType(), llvm::ARMTargetLowering::getSetCCResultType(), llvm::AArch64TargetLowering::getSetCCResultType(), llvm::PPCTargetLowering::getSetCCResultType(), llvm::X86TargetLowering::getSetCCResultType(), llvm::SelectionDAG::getShiftAmountOperand(), llvm::TargetLoweringBase::getShiftAmountTy(), getShuffleScalarElt(), llvm::SelectionDAG::GetSplitDestVTs(), llvm::SelectionDAG::getTruncStore(), llvm::TargetLoweringBase::getTypeConversion(), llvm::TargetLoweringBase::getTypeToExpandTo(), getVCmpEQInst(), llvm::SelectionDAG::getZeroExtendInReg(), getZeroVector(), isBSwapHWordElement(), isConstantOrUndefBUILD_VECTOR(), llvm::BuildVectorSDNode::isConstantSplat(), isConstantSplatVector(), isOneUseSetCC(), isTruncateOf(), isVShiftLImm(), isVShiftRImm(), llvm::TargetLowering::LowerCallTo(), LowerFP_TO_INT(), LowerINT_TO_FP(), llvm::SITargetLowering::LowerOperation(), llvm::NVPTXTargetLowering::LowerOperation(), llvm::NVPTXTargetLowering::LowerReturn(), llvm::AArch64TargetLowering::LowerSETCC(), LowerShift(), llvm::AMDGPUTargetLowering::LowerSTORE(), LowerToTLSExecModel(), LowerVectorBroadcast(), LowerXALUO(), matchIntegerMINMAX(), ConsecutiveMemoryChainSorter::operator()(), partitionShuffleOfConcats(), llvm::PPCTargetLowering::PerformDAGCombine(), PerformLOADCombine(), performMULCombine(), PerformORCombine(), PerformSELECTCombine(), PerformSExtCombine(), PerformSHLCombine(), PerformSIGN_EXTEND_INREGCombine(), PerformSINT_TO_FPCombine(), PerformSTORECombine(), PerformVCVTCombine(), PerformVDIVCombine(), ReplaceINTRINSIC_W_CHAIN(), ReplaceLoadVector(), llvm::R600TargetLowering::ReplaceNodeResults(), llvm::DAGTypeLegalizer::run(), llvm::SelectionDAGISel::runOnMachineFunction(), ShrinkLoadReplaceStoreWithStore(), llvm::SelectionDAG::SignBitIsZero(), llvm::TargetLowering::SimplifyDemandedBits(), llvm::TargetLowering::SimplifySetCC(), tryFoldToZero(), llvm::SelectionDAG::UnrollVectorOp(), llvm::SelectionDAGBuilder::UpdateSplitBlock(), useSinCos(), and VerifyNodeCommon().
bool llvm::EVT::operator!= (EVT VT) const inline
Definition at line 590 of file ValueTypes.h.
References llvm::MVT::SimpleTy.
bool llvm::EVT::operator== (EVT VT) const inline
Definition at line 587 of file ValueTypes.h.
The documentation for this struct was generated from the following files:
ValueTypes.h
ValueTypes.cpp