LLVM: LTOModule Struct Reference
LLVM API Documentation
LTOModule Struct Reference
#include <LTOModule.h>
Public Member Functions
const char * getTargetTriple ()
getTargetTriple - Return the Module's target triple.
void setTargetTriple (const char *triple)
setTargetTriple - Set the Module's target triple.
uint32_t getSymbolCount ()
getSymbolCount - Get the number of symbols
lto_symbol_attributes getSymbolAttributes (uint32_t index)
const char * getSymbolName (uint32_t index)
getSymbolName - Get the name of the symbol at the specified index.
llvm::Module * getLLVVMModule ()
getLLVVMModule - Return the Module.
const std::vector< const char * > & getAsmUndefinedRefs ()
getAsmUndefinedRefs -
Static Public Member Functions
static bool isBitcodeFile (const void *mem, size_t length)
static bool isBitcodeFile (const char *path)
static bool isBitcodeFileForTarget (const void *mem, size_t length, const char *triplePrefix)
static bool isBitcodeFileForTarget (const char *path, const char *triplePrefix)
static LTOModule * makeLTOModule (const char *path, llvm::TargetOptions options, std::string &errMsg)
static LTOModule * makeLTOModule (int fd, const char *path, size_t size, llvm::TargetOptions options, std::string &errMsg)
static LTOModule * makeLTOModule (int fd, const char *path, size_t map_size, off_t offset, llvm::TargetOptions options, std::string &errMsg)
static LTOModule * makeLTOModule (const void *mem, size_t length, llvm::TargetOptions options, std::string &errMsg)
Detailed Description
LTOModule - C++ class which implements the opaque lto_module_t type.
Definition at line 39 of file LTOModule.h.
Member Function Documentation
const std::vector<const char*>& LTOModule::getAsmUndefinedRefs () inline
getAsmUndefinedRefs -
Definition at line 134 of file LTOModule.h.
References c, and f().
Referenced by LTOCodeGenerator::addModule().
llvm::Module* LTOModule::getLLVVMModule () inline
getLLVVMModule - Return the Module.
Definition at line 131 of file LTOModule.h.
References llvm::OwningPtr< T >::get().
Referenced by LTOCodeGenerator::addModule().
lto_symbol_attributes LTOModule::getSymbolAttributes (uint32_t index) inline
getSymbolAttributes - Get the attributes for a symbol at the specified index.
Definition at line 117 of file LTOModule.h.
References attributes.
uint32_t LTOModule::getSymbolCount () inline
getSymbolCount - Get the number of symbols
Definition at line 111 of file LTOModule.h.
const char* LTOModule::getSymbolName (uint32_t index) inline
getSymbolName - Get the name of the symbol at the specified index.
Definition at line 124 of file LTOModule.h.
const char* LTOModule::getTargetTriple () inline
getTargetTriple - Return the Module's target triple.
Definition at line 101 of file LTOModule.h.
References llvm::Module::getTargetTriple().
bool LTOModule::isBitcodeFile (const void * mem, size_t length) static
isBitcodeFile - Returns 'true' if the file or memory contents is LLVM bitcode.
isBitcodeFile - Returns 'true' if the file (or memory contents) is LLVM bitcode.
Definition at line 51 of file LTOModule.cpp.
References llvm::sys::fs::identify_magic().
bool LTOModule::isBitcodeFile (const char * path) static
Definition at line 56 of file LTOModule.cpp.
References llvm::sys::fs::identify_magic(), and type.
bool LTOModule::isBitcodeFileForTarget (const void * mem, size_t length, const char * triplePrefix) static
isBitcodeFileForTarget - Returns 'true' if the file or memory contents is LLVM bitcode for the specified triple.
isBitcodeFileForTarget - Returns 'true' if the file (or memory contents) is LLVM bitcode for the specified triple.
Definition at line 65 of file LTOModule.cpp.
bool LTOModule::isBitcodeFileForTarget (const char * path, const char * triplePrefix) static
Definition at line 73 of file LTOModule.cpp.
References llvm::getBitcodeTargetTriple(), llvm::getGlobalContext(), llvm::LibFunc::strlen, llvm::LibFunc::strncmp, and llvm::OwningPtr< T >::take().
LTOModule * LTOModule::makeLTOModule (const char * path, llvm::TargetOptions options, std::string & errMsg) static
makeLTOModule - Create an LTOModule. N.B. These methods take ownership of the buffer. The caller must have initialized the Targets, the TargetMCs, the AsmPrinters, and the AsmParsers by calling:
InitializeAllTargets(); InitializeAllTargetMCs(); InitializeAllAsmPrinters(); InitializeAllAsmParsers();
makeLTOModule - Create an LTOModule. N.B. These methods take ownership of the buffer.
Definition at line 91 of file LTOModule.cpp.
References llvm::OwningPtr< T >::take().
Referenced by makeLTOModule().
LTOModule * LTOModule::makeLTOModule (int fd, const char * path, size_t size, llvm::TargetOptions options, std::string & errMsg) static
Definition at line 101 of file LTOModule.cpp.
LTOModule * LTOModule::makeLTOModule (int fd, const char * path, size_t map_size, off_t offset, llvm::TargetOptions options, std::string & errMsg) static
Definition at line 107 of file LTOModule.cpp.
References llvm::OwningPtr< T >::take().
LTOModule * LTOModule::makeLTOModule (const void * mem, size_t length, llvm::TargetOptions options, std::string & errMsg) static
Definition at line 121 of file LTOModule.cpp.
References c, llvm::Target::createTargetMachine(), llvm::StringRef::data(), llvm::dyn_cast(), f(), llvm::Triple::getArch(), llvm::SubtargetFeatures::getDefaultSubtargetFeatures(), llvm::sys::getDefaultTargetTriple(), llvm::getGlobalContext(), llvm::GlobalVariable::getInitializer(), llvm::StringMapEntry< ValueTy >::getKey(), llvm::getLazyBitcodeModule(), llvm::User::getOperand(), llvm::StringMap< ValueTy, AllocatorTy >::GetOrCreateValue(), llvm::GlobalValue::getSection(), llvm::SubtargetFeatures::getString(), llvm::Module::getTargetTriple(), llvm::GlobalValue::hasSection(), info, llvm::Triple::isOSDarwin(), LTO_SYMBOL_DEFINITION_REGULAR, LTO_SYMBOL_DEFINITION_UNDEFINED, LTO_SYMBOL_PERMISSIONS_DATA, LTO_SYMBOL_SCOPE_DEFAULT, makeLTOModule(), llvm::Module::MaterializeAllPermanently(), llvm::AArch64ISD::Ret, llvm::StringMapEntry< ValueTy >::setValue(), llvm::OwningPtr< T >::take(), target, llvm::Triple::x86, and llvm::Triple::x86_64.
void LTOModule::setTargetTriple (const char * triple) inline
setTargetTriple - Set the Module's target triple.
Definition at line 106 of file LTOModule.h.
References llvm::Module::setTargetTriple().
The documentation for this struct was generated from the following files:
LTOModule.h
LTOModule.cpp