LLVM: llvm::SCEVParameterRewriter Struct Reference
LLVM API Documentation
llvm::SCEVParameterRewriter Struct Reference
#include <ScalarEvolutionExpressions.h>
Public Member Functions
SCEVParameterRewriter (ScalarEvolution &S, ValueToValueMap &M)
const SCEV * visitConstant (const SCEVConstant *Constant)
const SCEV * visitTruncateExpr (const SCEVTruncateExpr *Expr)
const SCEV * visitZeroExtendExpr (const SCEVZeroExtendExpr *Expr)
const SCEV * visitSignExtendExpr (const SCEVSignExtendExpr *Expr)
const SCEV * visitAddExpr (const SCEVAddExpr *Expr)
const SCEV * visitMulExpr (const SCEVMulExpr *Expr)
const SCEV * visitUDivExpr (const SCEVUDivExpr *Expr)
const SCEV * visitAddRecExpr (const SCEVAddRecExpr *Expr)
const SCEV * visitSMaxExpr (const SCEVSMaxExpr *Expr)
const SCEV * visitUMaxExpr (const SCEVUMaxExpr *Expr)
const SCEV * visitUnknown (const SCEVUnknown *Expr)
const SCEV * visitCouldNotCompute (const SCEVCouldNotCompute *Expr)
Public Member Functions inherited from llvm::SCEVVisitor< SCEVParameterRewriter, const SCEV * >
const SCEV * visit (const SCEV *S)
const SCEV * visitCouldNotCompute (const SCEVCouldNotCompute *S)
Static Public Member Functions
static const SCEV * rewrite (const SCEV *Scev, ScalarEvolution &SE, ValueToValueMap &Map)
Detailed Description
The SCEVParameterRewriter takes a scalar evolution expression and updates the SCEVUnknown components following the Map (Value -> Value).
Definition at line 562 of file ScalarEvolutionExpressions.h.
Constructor & Destructor Documentation
llvm::SCEVParameterRewriter::SCEVParameterRewriter (ScalarEvolution & S, ValueToValueMap & M) inline
Definition at line 571 of file ScalarEvolutionExpressions.h.
Member Function Documentation
static const SCEV* llvm::SCEVParameterRewriter::rewrite (const SCEV * Scev, ScalarEvolution & SE, ValueToValueMap & Map) inline static
Definition at line 565 of file ScalarEvolutionExpressions.h.
References Rewriter, and llvm::SCEVVisitor< SC, RetVal >::visit().
const SCEV* llvm::SCEVParameterRewriter::visitAddExpr (const SCEVAddExpr * Expr) inline
Definition at line 593 of file ScalarEvolutionExpressions.h.
References llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVNAryExpr::getOperand(), i, and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
const SCEV* llvm::SCEVParameterRewriter::visitAddRecExpr (const SCEVAddRecExpr * Expr) inline
Definition at line 611 of file ScalarEvolutionExpressions.h.
References llvm::SCEVAddRecExpr::getLoop(), llvm::SCEVNAryExpr::getNoWrapFlags(), llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVNAryExpr::getOperand(), i, and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
const SCEV* llvm::SCEVParameterRewriter::visitConstant (const SCEVConstant * Constant) inline
Definition at line 574 of file ScalarEvolutionExpressions.h.
References llvm::ISD::Constant.
const SCEV* llvm::SCEVParameterRewriter::visitCouldNotCompute (const SCEVCouldNotCompute * Expr) inline
Definition at line 640 of file ScalarEvolutionExpressions.h.
const SCEV* llvm::SCEVParameterRewriter::visitMulExpr (const SCEVMulExpr * Expr) inline
Definition at line 600 of file ScalarEvolutionExpressions.h.
References llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVNAryExpr::getOperand(), i, and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
const SCEV* llvm::SCEVParameterRewriter::visitSignExtendExpr (const SCEVSignExtendExpr * Expr) inline
Definition at line 588 of file ScalarEvolutionExpressions.h.
References llvm::SCEVCastExpr::getOperand(), and llvm::SCEVCastExpr::getType().
const SCEV* llvm::SCEVParameterRewriter::visitSMaxExpr (const SCEVSMaxExpr * Expr) inline
Definition at line 619 of file ScalarEvolutionExpressions.h.
References llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVNAryExpr::getOperand(), i, and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
const SCEV* llvm::SCEVParameterRewriter::visitTruncateExpr (const SCEVTruncateExpr * Expr) inline
Definition at line 578 of file ScalarEvolutionExpressions.h.
References llvm::SCEVCastExpr::getOperand(), and llvm::SCEVCastExpr::getType().
const SCEV* llvm::SCEVParameterRewriter::visitUDivExpr (const SCEVUDivExpr * Expr) inline
Definition at line 607 of file ScalarEvolutionExpressions.h.
References llvm::SCEVUDivExpr::getLHS(), and llvm::SCEVUDivExpr::getRHS().
const SCEV* llvm::SCEVParameterRewriter::visitUMaxExpr (const SCEVUMaxExpr * Expr) inline
Definition at line 626 of file ScalarEvolutionExpressions.h.
References llvm::SCEVNAryExpr::getNumOperands(), llvm::SCEVNAryExpr::getOperand(), i, and llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back().
const SCEV* llvm::SCEVParameterRewriter::visitUnknown (const SCEVUnknown * Expr) inline
Definition at line 633 of file ScalarEvolutionExpressions.h.
References llvm::SCEVUnknown::getValue().
const SCEV* llvm::SCEVParameterRewriter::visitZeroExtendExpr (const SCEVZeroExtendExpr * Expr) inline
Definition at line 583 of file ScalarEvolutionExpressions.h.
References llvm::SCEVCastExpr::getOperand(), and llvm::SCEVCastExpr::getType().
The documentation for this struct was generated from the following file:
ScalarEvolutionExpressions.h