LLVM: llvm::MCAsmParserSemaCallback::InlineAsmIdentifierInfo Struct Reference
LLVM API Documentation
llvm::MCAsmParserSemaCallback::InlineAsmIdentifierInfo Struct Reference
#include <MCAsmParser.h>
Public Member Functions
void clear ()
Public Attributes
void * OpDecl
bool IsVarDecl
unsigned Length
unsigned Size
unsigned Type
Detailed Description
Definition at line 36 of file MCAsmParser.h.
Member Function Documentation
void llvm::MCAsmParserSemaCallback::InlineAsmIdentifierInfo::clear () inline
Definition at line 41 of file MCAsmParser.h.
References llvm::MCAsmParserSemaCallback::LookupInlineAsmField(), llvm::MCAsmParserSemaCallback::LookupInlineAsmIdentifier(), and llvm::MCAsmParserSemaCallback::~MCAsmParserSemaCallback().
Member Data Documentation
bool llvm::MCAsmParserSemaCallback::InlineAsmIdentifierInfo::IsVarDecl
Definition at line 38 of file MCAsmParser.h.
Referenced by getIntelMemOperandSize().
unsigned llvm::MCAsmParserSemaCallback::InlineAsmIdentifierInfo::Length
Definition at line 39 of file MCAsmParser.h.
void* llvm::MCAsmParserSemaCallback::InlineAsmIdentifierInfo::OpDecl
Definition at line 37 of file MCAsmParser.h.
Referenced by getIntelMemOperandSize(), and RewriteIntelBracExpression().
unsigned llvm::MCAsmParserSemaCallback::InlineAsmIdentifierInfo::Size
Definition at line 39 of file MCAsmParser.h.
unsigned llvm::MCAsmParserSemaCallback::InlineAsmIdentifierInfo::Type
Definition at line 39 of file MCAsmParser.h.
Referenced by getIntelMemOperandSize().
The documentation for this struct was generated from the following file:
MCAsmParser.h