LLVM: llvm::DOTGraphTraits< RegionInfo * > Struct Template Reference
LLVM API Documentation
llvm::DOTGraphTraits< RegionInfo * > Struct Template Reference
Public Member Functions
DOTGraphTraits (bool isSimple=false)
std::string getNodeLabel (RegionNode *Node, RegionInfo *G)
std::string getEdgeAttributes (RegionNode *srcNode, GraphTraits< RegionInfo * >::ChildIteratorType CI, RegionInfo *RI)
Public Member Functions inherited from llvm::DOTGraphTraits< RegionNode * >
DOTGraphTraits (bool isSimple=false)
std::string getNodeLabel (RegionNode *Node, RegionNode *Graph)
Public Member Functions inherited from llvm::DefaultDOTGraphTraits
DefaultDOTGraphTraits (bool simple=false)
template<typename GraphType >
std::string getNodeLabel (const void *, const GraphType &)
Static Public Member Functions
static std::string getGraphName (RegionInfo *DT)
static void printRegionCluster (const Region *R, GraphWriter< RegionInfo * > &GW, unsigned depth=0)
static void addCustomGraphFeatures (const RegionInfo *RI, GraphWriter< RegionInfo * > &GW)
Static Public Member Functions inherited from llvm::DefaultDOTGraphTraits
template<typename GraphType >
static std::string getGraphName (const GraphType &)
template<typename GraphType >
static std::string getGraphProperties (const GraphType &)
static bool renderGraphFromBottomUp ()
static bool isNodeHidden (const void *)
template<typename GraphType >
static bool hasNodeAddressLabel (const void *, const GraphType &)
template<typename GraphType >
static std::string getNodeDescription (const void *, const GraphType &)
template<typename GraphType >
static std::string getNodeAttributes (const void *, const GraphType &)
template<typename EdgeIter , typename GraphType >
static std::string getEdgeAttributes (const void *, EdgeIter, const GraphType &)
template<typename EdgeIter >
static std::string getEdgeSourceLabel (const void *, EdgeIter)
template<typename EdgeIter >
static bool edgeTargetsEdgeSource (const void *, EdgeIter)
template<typename EdgeIter >
static EdgeIter getEdgeTarget (const void *, EdgeIter I)
static bool hasEdgeDestLabels ()
static unsigned numEdgeDestLabels (const void *)
static std::string getEdgeDestLabel (const void *, unsigned)
template<typename GraphType , typename GraphWriter >
static void addCustomGraphFeatures (const GraphType &, GraphWriter &)
Additional Inherited Members
Protected Member Functions inherited from llvm::DefaultDOTGraphTraits
bool isSimple ()
Detailed Description
template<>
struct llvm::DOTGraphTraits< RegionInfo * >
Definition at line 59 of file RegionPrinter.cpp.
Constructor & Destructor Documentation
llvm::DOTGraphTraits< RegionInfo * >::DOTGraphTraits (bool isSimple = false) inline
Definition at line 61 of file RegionPrinter.cpp.
Member Function Documentation
static void llvm::DOTGraphTraits< RegionInfo * >::addCustomGraphFeatures (const RegionInfo * RI, GraphWriter< RegionInfo * > & GW) inline static
Definition at line 134 of file RegionPrinter.cpp.
References llvm::GraphWriter< GraphType >::getOStream(), llvm::PassRegistry::getPassRegistry(), llvm::RegionInfo::getTopLevelRegion(), INITIALIZE_PASS(), llvm::initializeRegionOnlyViewerPass(), llvm::initializeRegionPrinterPass(), and llvm::initializeRegionViewerPass().
std::string llvm::DOTGraphTraits< RegionInfo * >::getEdgeAttributes (RegionNode * srcNode, GraphTraits< RegionInfo * >::ChildIteratorType CI, RegionInfo * RI) inline
Definition at line 73 of file RegionPrinter.cpp.
References llvm::RegionNode::getNodeAs(), llvm::Region::getParent(), llvm::RegionInfo::getRegionFor(), and llvm::RegionNode::isSubRegion().
static std::string llvm::DOTGraphTraits< RegionInfo * >::getGraphName (RegionInfo * DT) inline static
Definition at line 64 of file RegionPrinter.cpp.
std::string llvm::DOTGraphTraits< RegionInfo * >::getNodeLabel (RegionNode * Node, RegionInfo * G) inline
Definition at line 68 of file RegionPrinter.cpp.
References llvm::DefaultDOTGraphTraits::getNodeLabel(), and llvm::RegionInfo::getTopLevelRegion().
static void llvm::DOTGraphTraits< RegionInfo * >::printRegionCluster (const Region * R, GraphWriter< RegionInfo * > & GW, unsigned depth = 0) inline static
Definition at line 101 of file RegionPrinter.cpp.
References llvm::Region::begin(), llvm::Region::block_begin(), llvm::Region::block_end(), llvm::Region::end(), llvm::Region::getBBNode(), llvm::Region::getDepth(), llvm::GraphWriter< GraphType >::getOStream(), llvm::RegionInfo::getRegionFor(), llvm::Region::getRegionInfo(), llvm::RegionInfo::getTopLevelRegion(), llvm::raw_ostream::indent(), llvm::Region::isSimple(), and onlySimpleRegions.
The documentation for this struct was generated from the following file:
RegionPrinter.cpp