LLVM: llvm::XCoreRegisterInfo Struct Reference
LLVM API Documentation
llvm::XCoreRegisterInfo Struct Reference
#include <XCoreRegisterInfo.h>
Public Member Functions
XCoreRegisterInfo ()
const uint16_t * getCalleeSavedRegs (const MachineFunction *MF=0) const
Code Generation virtual methods...
BitVector getReservedRegs (const MachineFunction &MF) const
bool requiresRegisterScavenging (const MachineFunction &MF) const
bool trackLivenessAfterRegAlloc (const MachineFunction &MF) const
bool useFPForScavengingIndex (const MachineFunction &MF) const
void eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *RS=NULL) const
unsigned getFrameRegister (const MachineFunction &MF) const
Static Public Member Functions
static bool needsFrameMoves (const MachineFunction &MF)
Return whether to emit frame moves.
Detailed Description
Definition at line 26 of file XCoreRegisterInfo.h.
Constructor & Destructor Documentation
XCoreRegisterInfo::XCoreRegisterInfo ()
Definition at line 40 of file XCoreRegisterInfo.cpp.
Member Function Documentation
void XCoreRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger * RS = NULL) const
Definition at line 105 of file XCoreRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), DEBUG, llvm::MachineBasicBlock::erase(), llvm::errs(), llvm::ISD::FrameIndex, llvm::MCInstrInfo::get(), llvm::MachineInstr::getDebugLoc(), llvm::MachineFunction::getFrameInfo(), llvm::TargetMachine::getFrameLowering(), getFrameRegister(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::TargetMachine::getInstrInfo(), llvm::getKillRegState(), llvm::MachineFunction::getName(), llvm::MachineFrameInfo::getObjectOffset(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFrameInfo::getStackSize(), llvm::MachineFunction::getTarget(), llvm::TargetFrameLowering::hasFP(), I, llvm::MachineInstr::isDebugValue(), isImmU16(), isImmU6(), isImmUs(), llvm::MachineOperand::isKill(), llvm::RegState::Kill, llvm_unreachable, llvm::A64CC::MI, llvm::MachineInstr::print(), llvm::report_fatal_error(), llvm::RegScavenger::scavengeRegister(), and TII.
const uint16_t * XCoreRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF = 0) const
Code Generation virtual methods...
Definition at line 62 of file XCoreRegisterInfo.cpp.
References R4, and R6.
unsigned XCoreRegisterInfo::getFrameRegister (const MachineFunction & MF) const
Definition at line 257 of file XCoreRegisterInfo.cpp.
References llvm::TargetMachine::getFrameLowering(), llvm::MachineFunction::getTarget(), and llvm::TargetFrameLowering::hasFP().
Referenced by eliminateFrameIndex().
BitVector XCoreRegisterInfo::getReservedRegs (const MachineFunction & MF) const
Definition at line 72 of file XCoreRegisterInfo.cpp.
References llvm::TargetMachine::getFrameLowering(), llvm::MachineFunction::getTarget(), llvm::TargetFrameLowering::hasFP(), and llvm::BitVector::set().
bool XCoreRegisterInfo::needsFrameMoves (const MachineFunction & MF) static
Return whether to emit frame moves.
Definition at line 57 of file XCoreRegisterInfo.cpp.
References llvm::MachineFunction::getFunction(), llvm::MachineFunction::getMMI(), llvm::MachineModuleInfo::hasDebugInfo(), and llvm::Function::needsUnwindTableEntry().
Referenced by llvm::XCoreFrameLowering::emitPrologue(), and llvm::XCoreFrameLowering::spillCalleeSavedRegisters().
bool XCoreRegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const
Definition at line 87 of file XCoreRegisterInfo.cpp.
References llvm::TargetMachine::getFrameLowering(), llvm::MachineFunction::getTarget(), and llvm::TargetFrameLowering::hasFP().
Referenced by trackLivenessAfterRegAlloc().
bool XCoreRegisterInfo::trackLivenessAfterRegAlloc (const MachineFunction & MF) const
Definition at line 95 of file XCoreRegisterInfo.cpp.
References requiresRegisterScavenging().
bool XCoreRegisterInfo::useFPForScavengingIndex (const MachineFunction & MF) const
Definition at line 100 of file XCoreRegisterInfo.cpp.
The documentation for this struct was generated from the following files:
XCoreRegisterInfo.h
XCoreRegisterInfo.cpp