LLVM: llvm::GraphTraits< const Function * > Struct Template Reference
LLVM API Documentation
llvm::GraphTraits< const Function * > Struct Template Reference
#include <CFG.h>
Public Types
typedef Function::const_iterator nodes_iterator
Public Types inherited from llvm::GraphTraits< const BasicBlock * >
typedef const BasicBlock NodeType
typedef succ_const_iterator ChildIteratorType
Static Public Member Functions
static NodeType * getEntryNode (const Function *F)
static nodes_iterator nodes_begin (const Function *F)
static nodes_iterator nodes_end (const Function *F)
static size_t size (const Function *F)
Static Public Member Functions inherited from llvm::GraphTraits< const BasicBlock * >
static NodeType * getEntryNode (const BasicBlock *BB)
static ChildIteratorType child_begin (NodeType *N)
static ChildIteratorType child_end (NodeType *N)
Detailed Description
template<>
struct llvm::GraphTraits< const Function * >
Definition at line 333 of file Support/CFG.h.
Member Typedef Documentation
typedef Function::const_iterator llvm::GraphTraits< const Function * >::nodes_iterator
Definition at line 338 of file Support/CFG.h.
Member Function Documentation
static NodeType* llvm::GraphTraits< const Function * >::getEntryNode (const Function * F) inline static
Definition at line 335 of file Support/CFG.h.
References llvm::Function::getEntryBlock().
static nodes_iterator llvm::GraphTraits< const Function * >::nodes_begin (const Function * F) inline static
Definition at line 339 of file Support/CFG.h.
References llvm::Function::begin().
static nodes_iterator llvm::GraphTraits< const Function * >::nodes_end (const Function * F) inline static
Definition at line 340 of file Support/CFG.h.
References llvm::Function::end().
static size_t llvm::GraphTraits< const Function * >::size (const Function * F) inline static
Definition at line 341 of file Support/CFG.h.
References llvm::Function::size().
The documentation for this struct was generated from the following file:
Support/CFG.h