LLVM: llvm::ImutIntervalInfo< T > Struct Template Reference
LLVM API Documentation
llvm::ImutIntervalInfo< T > Struct Template Reference
#include <ImmutableIntervalMap.h>
Public Types
typedef const std::pair< Interval, T > value_type
typedef const value_type & value_type_ref
typedef const Interval key_type
typedef const Interval & key_type_ref
typedef const T data_type
typedef const T & data_type_ref
Static Public Member Functions
static key_type_ref KeyOfValue (value_type_ref V)
static data_type_ref DataOfValue (value_type_ref V)
static bool isEqual (key_type_ref L, key_type_ref R)
static bool isDataEqual (data_type_ref L, data_type_ref R)
static bool isLess (key_type_ref L, key_type_ref R)
static bool isContainedIn (key_type_ref K, key_type_ref L)
static void Profile (FoldingSetNodeID &ID, value_type_ref V)
Detailed Description
template<typename T>
struct llvm::ImutIntervalInfo< T >
Definition at line 34 of file ImmutableIntervalMap.h.
Member Typedef Documentation
template<typename T> typedef const T llvm::ImutIntervalInfo< T >::data_type
Definition at line 39 of file ImmutableIntervalMap.h.
template<typename T> typedef const T& llvm::ImutIntervalInfo< T >::data_type_ref
Definition at line 40 of file ImmutableIntervalMap.h.
template<typename T> typedef const Interval llvm::ImutIntervalInfo< T >::key_type
Definition at line 37 of file ImmutableIntervalMap.h.
template<typename T> typedef const Interval& llvm::ImutIntervalInfo< T >::key_type_ref
Definition at line 38 of file ImmutableIntervalMap.h.
template<typename T> typedef const std::pair<Interval, T> llvm::ImutIntervalInfo< T >::value_type
Definition at line 35 of file ImmutableIntervalMap.h.
template<typename T> typedef const value_type& llvm::ImutIntervalInfo< T >::value_type_ref
Definition at line 36 of file ImmutableIntervalMap.h.
Member Function Documentation
template<typename T> static data_type_ref llvm::ImutIntervalInfo< T >::DataOfValue (value_type_ref V) inline static
Definition at line 46 of file ImmutableIntervalMap.h.
template<typename T> static bool llvm::ImutIntervalInfo< T >::isContainedIn (key_type_ref K, key_type_ref L) inline static
Definition at line 72 of file ImmutableIntervalMap.h.
References llvm::Interval::getEnd(), and llvm::Interval::getStart().
template<typename T> static bool llvm::ImutIntervalInfo< T >::isDataEqual (data_type_ref L, data_type_ref R) inline static
Definition at line 54 of file ImmutableIntervalMap.h.
References llvm::ImutContainerInfo< T >::isEqual().
template<typename T> static bool llvm::ImutIntervalInfo< T >::isEqual (key_type_ref L, key_type_ref R) inline static
Definition at line 50 of file ImmutableIntervalMap.h.
References llvm::Interval::getEnd(), and llvm::Interval::getStart().
template<typename T> static bool llvm::ImutIntervalInfo< T >::isLess (key_type_ref L, key_type_ref R) inline static
Definition at line 58 of file ImmutableIntervalMap.h.
References llvm::Interval::getEnd(), and llvm::Interval::getStart().
template<typename T> static key_type_ref llvm::ImutIntervalInfo< T >::KeyOfValue (value_type_ref V) inline static
Definition at line 42 of file ImmutableIntervalMap.h.
template<typename T> static void llvm::ImutIntervalInfo< T >::Profile (FoldingSetNodeID & ID, value_type_ref V) inline static
Definition at line 79 of file ImmutableIntervalMap.h.
References llvm::FoldingSetNodeID::AddInteger(), and llvm::ImutProfileInfo< T >::Profile().
The documentation for this struct was generated from the following file:
ImmutableIntervalMap.h