LLVM: llvm::MachinePostDominatorTree Struct Reference
LLVM API Documentation
llvm::MachinePostDominatorTree Struct Reference
#include <MachinePostDominators.h>
Public Member Functions
MachinePostDominatorTree ()
~MachinePostDominatorTree ()
FunctionPass * createMachinePostDominatorTreePass ()
const std::vector< MachineBasicBlock * > & getRoots () const
MachineDomTreeNode * getRootNode () const
MachineDomTreeNode * operator[] (MachineBasicBlock *BB) const
MachineDomTreeNode * getNode (MachineBasicBlock *BB) const
bool dominates (const MachineDomTreeNode *A, const MachineDomTreeNode *B) const
bool dominates (const MachineBasicBlock *A, const MachineBasicBlock *B) const
bool properlyDominates (const MachineDomTreeNode *A, const MachineDomTreeNode *B) const
bool properlyDominates (const MachineBasicBlock *A, const MachineBasicBlock *B) const
MachineBasicBlock * findNearestCommonDominator (MachineBasicBlock *A, MachineBasicBlock *B)
virtual bool runOnMachineFunction (MachineFunction &MF)
virtual void getAnalysisUsage (AnalysisUsage &AU) const
virtual void print (llvm::raw_ostream &OS, const Module *M=0) const
Public Member Functions inherited from llvm::FunctionPass
FunctionPass (char &pid)
Pass * createPrinterPass (raw_ostream &O, const std::string &Banner) const
createPrinterPass - Get a function printer pass.
virtual void assignPassManager (PMStack &PMS, PassManagerType T)
virtual PassManagerType getPotentialPassManagerType () const
Return what kind of Pass Manager can manage this pass.
Public Member Functions inherited from llvm::Pass
Pass (PassKind K, char &pid)
virtual ~Pass ()
PassKind getPassKind () const
virtual const char * getPassName () const
AnalysisID getPassID () const
getPassID - Return the PassID number that corresponds to this pass.
virtual bool doInitialization (Module &)
virtual bool doFinalization (Module &)
void dump () const
virtual void preparePassManager (PMStack &)
Check if available pass managers are suitable for this pass or not.
void setResolver (AnalysisResolver *AR)
AnalysisResolver * getResolver () const
virtual void releaseMemory ()
virtual void * getAdjustedAnalysisPointer (AnalysisID ID)
virtual ImmutablePass * getAsImmutablePass ()
virtual PMDataManager * getAsPMDataManager ()
virtual void verifyAnalysis () const
virtual void dumpPassStructure (unsigned Offset=0)
template<typename AnalysisType >
AnalysisType * getAnalysisIfAvailable () const
bool mustPreserveAnalysisID (char &AID) const
template<typename AnalysisType >
AnalysisType & getAnalysis () const
template<typename AnalysisType >
AnalysisType & getAnalysis (Function &F)
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI) const
template<typename AnalysisType >
AnalysisType & getAnalysisID (AnalysisID PI, Function &F)
Static Public Attributes
static char ID = 0
Additional Inherited Members
Static Public Member Functions inherited from llvm::Pass
static const PassInfo * lookupPassInfo (const void *TI)
static const PassInfo * lookupPassInfo (StringRef Arg)
static Pass * createPass (AnalysisID ID)
Protected Member Functions inherited from llvm::MachineFunctionPass
MachineFunctionPass (char &ID)
Detailed Description
PostDominatorTree Class - Concrete subclass of DominatorTree that is used to compute the a post-dominator tree.
Definition at line 28 of file MachinePostDominators.h.
Constructor & Destructor Documentation
llvm::MachinePostDominatorTree::MachinePostDominatorTree ()
Referenced by createMachinePostDominatorTreePass().
MachinePostDominatorTree::~MachinePostDominatorTree ()
Definition at line 42 of file MachinePostDominators.cpp.
Member Function Documentation
FunctionPass * MachinePostDominatorTree::createMachinePostDominatorTreePass ()
Definition at line 32 of file MachinePostDominators.cpp.
References MachinePostDominatorTree().
bool llvm::MachinePostDominatorTree::dominates (const MachineDomTreeNode * A, const MachineDomTreeNode * B) const inline
Definition at line 57 of file MachinePostDominators.h.
References llvm::DominatorTreeBase< NodeT >::dominates().
bool llvm::MachinePostDominatorTree::dominates (const MachineBasicBlock * A, const MachineBasicBlock * B) const inline
Definition at line 62 of file MachinePostDominators.h.
References llvm::DominatorTreeBase< NodeT >::dominates().
MachineBasicBlock* llvm::MachinePostDominatorTree::findNearestCommonDominator (MachineBasicBlock * A, MachineBasicBlock * B) inline
Definition at line 76 of file MachinePostDominators.h.
References llvm::DominatorTreeBase< NodeT >::findNearestCommonDominator(), getAnalysisUsage(), M, print(), and runOnMachineFunction().
void MachinePostDominatorTree::getAnalysisUsage (AnalysisUsage & AU) const virtual
getAnalysisUsage - Subclasses that override getAnalysisUsage must call this.
For MachineFunctionPasses, calling AU.preservesCFG() indicates that the pass does not modify the MachineBasicBlock CFG.
Reimplemented from llvm::MachineFunctionPass.
Definition at line 47 of file MachinePostDominators.cpp.
References llvm::MachineFunctionPass::getAnalysisUsage(), and llvm::AnalysisUsage::setPreservesAll().
Referenced by findNearestCommonDominator().
MachineDomTreeNode* llvm::MachinePostDominatorTree::getNode (MachineBasicBlock * BB) const inline
Definition at line 53 of file MachinePostDominators.h.
References llvm::DominatorTreeBase< NodeT >::getNode().
MachineDomTreeNode* llvm::MachinePostDominatorTree::getRootNode () const inline
Definition at line 45 of file MachinePostDominators.h.
References llvm::DominatorTreeBase< NodeT >::getRootNode().
const std::vector<MachineBasicBlock *>& llvm::MachinePostDominatorTree::getRoots () const inline
Definition at line 41 of file MachinePostDominators.h.
References llvm::DominatorBase< NodeT >::getRoots().
MachineDomTreeNode* llvm::MachinePostDominatorTree::operator[] (MachineBasicBlock * BB) const inline
Definition at line 49 of file MachinePostDominators.h.
References llvm::DominatorTreeBase< NodeT >::getNode().
void MachinePostDominatorTree::print (llvm::raw_ostream & O, const Module * M = 0) const virtual
print - Print out the internal state of the pass. This is called by Analyze to print out the contents of an analysis. Otherwise it is not necessary to implement this method. Beware that the module pointer MAY be null. This automatically forwards to a virtual function that does not provide the Module* in case the analysis doesn't need it it can just be ignored.
Reimplemented from llvm::Pass.
Definition at line 53 of file MachinePostDominators.cpp.
Referenced by findNearestCommonDominator().
bool llvm::MachinePostDominatorTree::properlyDominates (const MachineDomTreeNode * A, const MachineDomTreeNode * B) const inline
Definition at line 66 of file MachinePostDominators.h.
References llvm::DominatorTreeBase< NodeT >::properlyDominates().
bool llvm::MachinePostDominatorTree::properlyDominates (const MachineBasicBlock * A, const MachineBasicBlock * B) const inline
Definition at line 71 of file MachinePostDominators.h.
References llvm::DominatorTreeBase< NodeT >::properlyDominates().
bool MachinePostDominatorTree::runOnMachineFunction (MachineFunction & MF) virtual
runOnMachineFunction - This method must be overloaded to perform the desired machine code transformation or analysis.
Implements llvm::MachineFunctionPass.
Definition at line 37 of file MachinePostDominators.cpp.
Referenced by findNearestCommonDominator().
Member Data Documentation
char MachinePostDominatorTree::ID = 0 static
Definition at line 33 of file MachinePostDominators.h.
The documentation for this struct was generated from the following files:
MachinePostDominators.h
MachinePostDominators.cpp