LLVM: llvm::ImutProfileInfo< T > Struct Template Reference
LLVM API Documentation
llvm::ImutProfileInfo< T > Struct Template Reference
#include <ImmutableSet.h>
Public Types
typedef const T value_type
typedef const T & value_type_ref
Static Public Member Functions
static void Profile (FoldingSetNodeID &ID, value_type_ref X)
Detailed Description
template<typename T>
struct llvm::ImutProfileInfo< T >
Generic profile template. The default behavior is to invoke the profile method of an object. Specializations for primitive integers and generic handling of pointers is done below.
Definition at line 818 of file ImmutableSet.h.
Member Typedef Documentation
template<typename T> typedef const T llvm::ImutProfileInfo< T >::value_type
Definition at line 819 of file ImmutableSet.h.
template<typename T> typedef const T& llvm::ImutProfileInfo< T >::value_type_ref
Definition at line 820 of file ImmutableSet.h.
Member Function Documentation
template<typename T> static void llvm::ImutProfileInfo< T >::Profile (FoldingSetNodeID & ID, value_type_ref X) inline static
Definition at line 822 of file ImmutableSet.h.
References llvm::DefaultFoldingSetTrait< T >::Profile().
Referenced by llvm::ImutKeyValueInfo< T, S >::Profile(), and llvm::ImutIntervalInfo< T >::Profile().
The documentation for this struct was generated from the following file:
ImmutableSet.h