LLVM: llvm::ilist_node_traits< NodeTy > Struct Template Reference
LLVM API Documentation
llvm::ilist_node_traits< NodeTy > Struct Template Reference
#include <ilist.h>
Public Member Functions
void addNodeToList (NodeTy *)
void removeNodeFromList (NodeTy *)
void transferNodesFromList (ilist_node_traits &, ilist_iterator< NodeTy >, ilist_iterator< NodeTy >)
Static Public Member Functions
static NodeTy * createNode (const NodeTy &V)
static void deleteNode (NodeTy *V)
Detailed Description
template<typename NodeTy>
struct llvm::ilist_node_traits< NodeTy >
ilist_node_traits - A fragment for template traits for intrusive list that provides default node related operations.
Definition at line 111 of file ilist.h.
Member Function Documentation
template<typename NodeTy> void llvm::ilist_node_traits< NodeTy >::addNodeToList (NodeTy *) inline
Definition at line 115 of file ilist.h.
Referenced by llvm::ilist_traits< MachineInstr >::noteHead(), and llvm::ilist_traits< MachineBasicBlock >::noteHead().
template<typename NodeTy> static NodeTy* llvm::ilist_node_traits< NodeTy >::createNode (const NodeTy & V) inline static
Definition at line 112 of file ilist.h.
Referenced by llvm::ilist_traits< MachineInstr >::noteHead(), and llvm::ilist_traits< MachineBasicBlock >::noteHead().
template<typename NodeTy> static void llvm::ilist_node_traits< NodeTy >::deleteNode (NodeTy * V) inline static
Definition at line 113 of file ilist.h.
Referenced by llvm::ilist_traits< MachineInstr >::noteHead(), llvm::ilist_traits< MachineBasicBlock >::noteHead(), and llvm::MachineFunctionInfo::~MachineFunctionInfo().
template<typename NodeTy> void llvm::ilist_node_traits< NodeTy >::removeNodeFromList (NodeTy *) inline
Definition at line 116 of file ilist.h.
Referenced by llvm::ilist_traits< MachineInstr >::noteHead(), and llvm::ilist_traits< MachineBasicBlock >::noteHead().
template<typename NodeTy> void llvm::ilist_node_traits< NodeTy >::transferNodesFromList (ilist_node_traits< NodeTy > & , ilist_iterator< NodeTy > , ilist_iterator< NodeTy >) inline
Definition at line 117 of file ilist.h.
Referenced by llvm::ilist_traits< MachineInstr >::noteHead().
The documentation for this struct was generated from the following file:
ilist.h