LLVM: llvm::DenseMapAPIntKeyInfo::KeyTy Struct Reference
LLVM API Documentation
llvm::DenseMapAPIntKeyInfo::KeyTy Struct Reference
#include <LLVMContextImpl.h>
Public Member Functions
KeyTy (const APInt &V, Type *Ty)
bool operator== (const KeyTy &that) const
bool operator!= (const KeyTy &that) const
Public Attributes
APInt val
Type * type
Friends
hash_code hash_value (const KeyTy &Key)
Detailed Description
Definition at line 45 of file LLVMContextImpl.h.
Constructor & Destructor Documentation
llvm::DenseMapAPIntKeyInfo::KeyTy::KeyTy (const APInt & V, Type * Ty) inline
Definition at line 48 of file LLVMContextImpl.h.
Referenced by llvm::DenseMapAPIntKeyInfo::getEmptyKey(), llvm::DenseMapAPFloatKeyInfo::getEmptyKey(), llvm::AnonStructTypeKeyInfo::getHashValue(), llvm::FunctionTypeKeyInfo::getHashValue(), llvm::DenseMapAPIntKeyInfo::getTombstoneKey(), llvm::DenseMapAPFloatKeyInfo::getTombstoneKey(), llvm::AnonStructTypeKeyInfo::isEqual(), and llvm::FunctionTypeKeyInfo::isEqual().
Member Function Documentation
bool llvm::DenseMapAPIntKeyInfo::KeyTy::operator!= (const KeyTy & that) const inline
Definition at line 52 of file LLVMContextImpl.h.
References operator==().
bool llvm::DenseMapAPIntKeyInfo::KeyTy::operator== (const KeyTy & that) const inline
Definition at line 49 of file LLVMContextImpl.h.
References type, and val.
Referenced by operator!=(), llvm::DenseMapAPFloatKeyInfo::KeyTy::operator!=(), llvm::AnonStructTypeKeyInfo::KeyTy::operator!=(), and llvm::FunctionTypeKeyInfo::KeyTy::operator!=().
Friends And Related Function Documentation
hash_code hash_value (const KeyTy & Key) friend
Definition at line 55 of file LLVMContextImpl.h.
Referenced by llvm::DenseMapAPIntKeyInfo::getHashValue(), and llvm::DenseMapAPFloatKeyInfo::getHashValue().
Member Data Documentation
Type* llvm::DenseMapAPIntKeyInfo::KeyTy::type
Definition at line 47 of file LLVMContextImpl.h.
Referenced by operator==().
APInt llvm::DenseMapAPIntKeyInfo::KeyTy::val
Definition at line 46 of file LLVMContextImpl.h.
Referenced by operator==().
The documentation for this struct was generated from the following file:
LLVMContextImpl.h