LLVM: llvm::detail::PassConcept< T > Struct Template Reference
LLVM API Documentation
llvm::detail::PassConcept< T > Struct Template Reference abstract
Template for the abstract base class used to dispatch polymorphically over pass objects.
#include <PassManager.h>
Public Member Functions
virtual ~PassConcept ()
virtual PassConcept * clone ()=0
virtual bool run (T Arg)=0
The polymorphic API which runs the pass over a given IR entity.
Detailed Description
template<typename T>
struct llvm::detail::PassConcept< T >
Template for the abstract base class used to dispatch polymorphically over pass objects.
Definition at line 56 of file IR/PassManager.h.
Constructor & Destructor Documentation
template<typename T> virtual llvm::detail::PassConcept< T >::~PassConcept () inline virtual
Definition at line 58 of file IR/PassManager.h.
Member Function Documentation
template<typename T> virtual PassConcept* llvm::detail::PassConcept< T >::clone () pure virtual
Implemented in llvm::detail::PassModel< T, PassT >, llvm::detail::PassModel< Function *, PassT >, and llvm::detail::PassModel< Module *, PassT >.
Referenced by llvm::AnalysisManager::invalidate(), and llvm::detail::PassConcept< Module * >::~PassConcept().
template<typename T> virtual bool llvm::detail::PassConcept< T >::run (T Arg) pure virtual
The polymorphic API which runs the pass over a given IR entity.
Implemented in llvm::detail::PassModel< T, PassT >, llvm::detail::PassModel< Function *, PassT >, and llvm::detail::PassModel< Module *, PassT >.
Referenced by llvm::ModulePassManager::addPass(), llvm::FunctionPassManager::addPass(), llvm::AnalysisManager::invalidate(), and llvm::detail::PassConcept< Module * >::~PassConcept().
The documentation for this struct was generated from the following file:
IR/PassManager.h