LLVM: llvm::A64SysReg::SysRegMapper Struct Reference
LLVM API Documentation
llvm::A64SysReg::SysRegMapper Struct Reference
#include <AArch64BaseInfo.h>
Public Member Functions
SysRegMapper ()
uint32_t fromString (StringRef Name, bool &Valid) const
std::string toString (uint32_t Bits, bool &Valid) const
Public Attributes
const NamedImmMapper::Mapping * InstPairs
size_t NumInstPairs
Static Public Attributes
static const NamedImmMapper::Mapping SysRegPairs []
Detailed Description
Definition at line 970 of file AArch64BaseInfo.h.
Constructor & Destructor Documentation
llvm::A64SysReg::SysRegMapper::SysRegMapper () inline
Definition at line 976 of file AArch64BaseInfo.h.
References llvm::tgtok::Bits.
Member Function Documentation
uint32_t A64SysReg::SysRegMapper::fromString (StringRef Name, bool & Valid) const
Definition at line 757 of file AArch64BaseInfo.cpp.
References llvm::array_lengthof(), llvm::tgtok::Bits, i, llvm::StringRef::lower(), and llvm::Regex::match().
std::string A64SysReg::SysRegMapper::toString (uint32_t Bits, bool & Valid) const
Definition at line 799 of file AArch64BaseInfo.cpp.
References llvm::A64TLBI::ALLE1, llvm::A64TLBI::ALLE1IS, llvm::A64TLBI::ALLE2, llvm::A64TLBI::ALLE2IS, llvm::A64TLBI::ALLE3, llvm::A64TLBI::ALLE3IS, llvm::array_lengthof(), llvm::A64TLBI::ASIDE1, llvm::A64TLBI::ASIDE1IS, i, llvm::A64TLBI::IPAS2E1, llvm::A64TLBI::IPAS2E1IS, llvm::A64TLBI::IPAS2LE1, llvm::A64TLBI::IPAS2LE1IS, llvm::A64TLBI::TLBIMapper::TLBIPairs, llvm::utostr(), llvm::A64TLBI::VAAE1, llvm::A64TLBI::VAAE1IS, llvm::A64TLBI::VAALE1, llvm::A64TLBI::VAALE1IS, llvm::A64TLBI::VAE1, llvm::A64TLBI::VAE1IS, llvm::A64TLBI::VAE2, llvm::A64TLBI::VAE2IS, llvm::A64TLBI::VAE3, llvm::A64TLBI::VAE3IS, llvm::A64TLBI::VALE1, llvm::A64TLBI::VALE1IS, llvm::A64TLBI::VALE2, llvm::A64TLBI::VALE2IS, llvm::A64TLBI::VALE3, llvm::A64TLBI::VALE3IS, llvm::A64TLBI::VMALLE1, llvm::A64TLBI::VMALLE1IS, llvm::A64TLBI::VMALLS12E1, llvm::A64TLBI::VMALLS12E1IS, and x3.
Referenced by DecodeSysRegOperand(), and llvm::AArch64InstPrinter::printSysRegOperand().
Member Data Documentation
const NamedImmMapper::Mapping* llvm::A64SysReg::SysRegMapper::InstPairs
Definition at line 973 of file AArch64BaseInfo.h.
size_t llvm::A64SysReg::SysRegMapper::NumInstPairs
Definition at line 974 of file AArch64BaseInfo.h.
const NamedImmMapper::Mapping A64SysReg::SysRegMapper::SysRegPairs static
Definition at line 971 of file AArch64BaseInfo.h.
Referenced by llvm::A64SysReg::MSRMapper::MSRMapper().
The documentation for this struct was generated from the following files:
AArch64BaseInfo.h
AArch64BaseInfo.cpp