LLVM: llvm::DenseMapInfo< ComparableFunction > Struct Template Reference
LLVM API Documentation
llvm::DenseMapInfo< ComparableFunction > Struct Template Reference
Static Public Member Functions
static ComparableFunction getEmptyKey ()
static ComparableFunction getTombstoneKey ()
static unsigned getHashValue (const ComparableFunction &CF)
static bool isEqual (const ComparableFunction &LHS, const ComparableFunction &RHS)
Detailed Description
template<>
struct llvm::DenseMapInfo< ComparableFunction >
Definition at line 144 of file MergeFunctions.cpp.
Member Function Documentation
static ComparableFunction llvm::DenseMapInfo< ComparableFunction >::getEmptyKey () inline static
Definition at line 145 of file MergeFunctions.cpp.
static unsigned llvm::DenseMapInfo< ComparableFunction >::getHashValue (const ComparableFunction & CF) inline static
Definition at line 151 of file MergeFunctions.cpp.
References llvm::GEPOperator::accumulateConstantOffset(), llvm::Type::ArrayTyID, llvm::BasicBlock::begin(), C1, llvm::Type::DoubleTyID, llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::BasicBlock::end(), F(), llvm::Type::FloatTyID, llvm::Type::FP128TyID, llvm::Type::FunctionTyID, G, llvm::PointerType::getAddressSpace(), llvm::Intrinsic::getAttributes(), llvm::ConstantExpr::getBitCast(), llvm::StructType::getElementType(), llvm::SequentialType::getElementType(), llvm::StructType::getNumElements(), llvm::ArrayType::getNumElements(), llvm::User::getNumOperands(), llvm::FunctionType::getNumParams(), llvm::TerminatorInst::getNumSuccessors(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::FunctionType::getParamType(), llvm::PassRegistry::getPassRegistry(), llvm::GEPOperator::getPointerAddressSpace(), llvm::GEPOperator::getPointerOperand(), llvm::GetElementPtrInst::getPointerOperand(), llvm::FunctionType::getReturnType(), llvm::TerminatorInst::getSuccessor(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), llvm::Type::getTypeID(), llvm::Value::getValueID(), llvm::Value::hasSameSubclassOptionalData(), i, INITIALIZE_PASS, llvm::initializeMergeFunctionsPass(), llvm::SmallSet< T, N, C >::insert(), llvm::Type::IntegerTyID, llvm::Constant::isNullValue(), llvm::StructType::isPacked(), llvm::FunctionType::isVarArg(), llvm::Type::LabelTyID, llvm_unreachable, M, llvm::Type::MetadataTyID, llvm::Type::PointerTyID, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::Type::PPC_FP128TyID, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::Type::StructTyID, llvm::NVPTX::PTXLdStInstCode::V2, llvm::Type::VectorTyID, llvm::Type::VoidTyID, and llvm::Type::X86_FP80TyID.
static ComparableFunction llvm::DenseMapInfo< ComparableFunction >::getTombstoneKey () inline static
Definition at line 148 of file MergeFunctions.cpp.
static bool llvm::DenseMapInfo< ComparableFunction >::isEqual (const ComparableFunction & LHS, const ComparableFunction & RHS) static
The documentation for this struct was generated from the following file:
MergeFunctions.cpp