LLVM: llvm::AArch64RegisterInfo Struct Reference
LLVM API Documentation
llvm::AArch64RegisterInfo Struct Reference
#include <AArch64RegisterInfo.h>
Public Member Functions
AArch64RegisterInfo ()
const uint16_t * getCalleeSavedRegs (const MachineFunction *MF=0) const
const uint32_t * getCallPreservedMask (CallingConv::ID) const
const uint32_t * getTLSDescCallPreservedMask () const
BitVector getReservedRegs (const MachineFunction &MF) const
unsigned getFrameRegister (const MachineFunction &MF) const
void eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger *Rs=NULL) const
const TargetRegisterClass * getCrossCopyRegClass (const TargetRegisterClass *RC) const
const TargetRegisterClass * getLargestLegalSuperClass (const TargetRegisterClass *RC) const
bool requiresRegisterScavenging (const MachineFunction &MF) const
bool requiresFrameIndexScavenging (const MachineFunction &MF) const
bool useFPForScavengingIndex (const MachineFunction &MF) const
Detailed Description
Definition at line 27 of file AArch64RegisterInfo.h.
Constructor & Destructor Documentation
AArch64RegisterInfo::AArch64RegisterInfo ()
Definition at line 32 of file AArch64RegisterInfo.cpp.
Member Function Documentation
void AArch64RegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator II, int SPAdj, unsigned FIOperandNum, RegScavenger * Rs = NULL) const
Definition at line 80 of file AArch64RegisterInfo.cpp.
References llvm::MachineOperand::ChangeToImmediate(), llvm::MachineOperand::ChangeToRegister(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::emitRegUpdate(), llvm::ISD::FrameIndex, llvm::AArch64InstrInfo::getAddressConstraints(), llvm::MachineFrameInfo::getCalleeSavedInfo(), llvm::MachineFunction::getFrameInfo(), llvm::TargetMachine::getFrameLowering(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::TargetMachine::getInstrInfo(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getTarget(), llvm::MachineInstr::isDebugValue(), llvm::A64CC::MI, llvm::AArch64FrameLowering::resolveFrameIndexReference(), and TII.
const uint16_t * AArch64RegisterInfo::getCalleeSavedRegs (const MachineFunction * MF = 0) const
Definition at line 37 of file AArch64RegisterInfo.cpp.
Referenced by llvm::AArch64FrameLowering::processFunctionBeforeCalleeSavedScan().
const uint32_t * AArch64RegisterInfo::getCallPreservedMask (CallingConv::ID) const
Definition at line 42 of file AArch64RegisterInfo.cpp.
const TargetRegisterClass * AArch64RegisterInfo::getCrossCopyRegClass (const TargetRegisterClass * RC) const
getCrossCopyRegClass - Returns a legal register class to copy a register in the specified class to or from. Returns original class if it is possible to copy between a two registers of the specified class.
Definition at line 51 of file AArch64RegisterInfo.cpp.
unsigned AArch64RegisterInfo::getFrameRegister (const MachineFunction & MF) const
Definition at line 157 of file AArch64RegisterInfo.cpp.
References llvm::TargetMachine::getFrameLowering(), llvm::MachineFunction::getTarget(), and llvm::TargetFrameLowering::hasFP().
const TargetRegisterClass* llvm::AArch64RegisterInfo::getLargestLegalSuperClass (const TargetRegisterClass * RC) const inline
getLargestLegalSuperClass - Returns the largest super class of RC that is legal to use in the current sub-target and has the same spill size.
Definition at line 51 of file AArch64RegisterInfo.h.
BitVector AArch64RegisterInfo::getReservedRegs (const MachineFunction & MF) const
Definition at line 61 of file AArch64RegisterInfo.cpp.
References llvm::TargetMachine::getFrameLowering(), llvm::MachineFunction::getTarget(), llvm::TargetFrameLowering::hasFP(), and llvm::BitVector::set().
const uint32_t * AArch64RegisterInfo::getTLSDescCallPreservedMask () const
Definition at line 46 of file AArch64RegisterInfo.cpp.
Referenced by llvm::AArch64TargetLowering::LowerTLSDescCall().
bool llvm::AArch64RegisterInfo::requiresFrameIndexScavenging (const MachineFunction & MF) const inline
Definition at line 62 of file AArch64RegisterInfo.h.
References useFPForScavengingIndex().
bool llvm::AArch64RegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const inline
Definition at line 58 of file AArch64RegisterInfo.h.
bool AArch64RegisterInfo::useFPForScavengingIndex (const MachineFunction & MF) const
Definition at line 167 of file AArch64RegisterInfo.cpp.
References llvm::TargetMachine::getFrameLowering(), llvm::MachineFunction::getTarget(), and llvm::AArch64FrameLowering::useFPForAddressing().
Referenced by requiresFrameIndexScavenging().
The documentation for this struct was generated from the following files:
AArch64RegisterInfo.h
AArch64RegisterInfo.cpp