LLVM: llvm::GraphTraits< BlockFrequencyInfo * > Struct Template Reference
LLVM API Documentation
llvm::GraphTraits< BlockFrequencyInfo * > Struct Template Reference
Public Types
typedef const BasicBlock NodeType
typedef succ_const_iterator ChildIteratorType
typedef Function::const_iterator nodes_iterator
Static Public Member Functions
static const NodeType * getEntryNode (const BlockFrequencyInfo *G)
static ChildIteratorType child_begin (const NodeType *N)
static ChildIteratorType child_end (const NodeType *N)
static nodes_iterator nodes_begin (const BlockFrequencyInfo *G)
static nodes_iterator nodes_end (const BlockFrequencyInfo *G)
Detailed Description
template<>
struct llvm::GraphTraits< BlockFrequencyInfo * >
Definition at line 50 of file BlockFrequencyInfo.cpp.
Member Typedef Documentation
typedef succ_const_iterator llvm::GraphTraits< BlockFrequencyInfo * >::ChildIteratorType
Definition at line 52 of file BlockFrequencyInfo.cpp.
typedef Function::const_iterator llvm::GraphTraits< BlockFrequencyInfo * >::nodes_iterator
Definition at line 53 of file BlockFrequencyInfo.cpp.
typedef const BasicBlock llvm::GraphTraits< BlockFrequencyInfo * >::NodeType
Definition at line 51 of file BlockFrequencyInfo.cpp.
Member Function Documentation
static ChildIteratorType llvm::GraphTraits< BlockFrequencyInfo * >::child_begin (const NodeType * N) inline static
Definition at line 58 of file BlockFrequencyInfo.cpp.
References llvm::succ_begin().
static ChildIteratorType llvm::GraphTraits< BlockFrequencyInfo * >::child_end (const NodeType * N) inline static
Definition at line 61 of file BlockFrequencyInfo.cpp.
References llvm::succ_end().
static const NodeType* llvm::GraphTraits< BlockFrequencyInfo * >::getEntryNode (const BlockFrequencyInfo * G) inline static
Definition at line 55 of file BlockFrequencyInfo.cpp.
References llvm::Function::begin(), and llvm::BlockFrequencyInfo::getFunction().
static nodes_iterator llvm::GraphTraits< BlockFrequencyInfo * >::nodes_begin (const BlockFrequencyInfo * G) inline static
Definition at line 64 of file BlockFrequencyInfo.cpp.
References llvm::Function::begin(), and llvm::BlockFrequencyInfo::getFunction().
static nodes_iterator llvm::GraphTraits< BlockFrequencyInfo * >::nodes_end (const BlockFrequencyInfo * G) inline static
Definition at line 67 of file BlockFrequencyInfo.cpp.
References llvm::Function::end(), and llvm::BlockFrequencyInfo::getFunction().
The documentation for this struct was generated from the following file:
BlockFrequencyInfo.cpp