LLVM: llvm::GraphTraits< MachineFunction * > Struct Template Reference
LLVM API Documentation
llvm::GraphTraits< MachineFunction * > Struct Template Reference
#include <MachineFunction.h>
Public Types
typedef MachineFunction::iterator nodes_iterator
Public Types inherited from llvm::GraphTraits< MachineBasicBlock * >
typedef MachineBasicBlock NodeType
typedef MachineBasicBlock::succ_iterator ChildIteratorType
Static Public Member Functions
static NodeType * getEntryNode (MachineFunction *F)
static nodes_iterator nodes_begin (MachineFunction *F)
static nodes_iterator nodes_end (MachineFunction *F)
static unsigned size (MachineFunction *F)
Static Public Member Functions inherited from llvm::GraphTraits< MachineBasicBlock * >
static NodeType * getEntryNode (MachineBasicBlock *BB)
static ChildIteratorType child_begin (NodeType *N)
static ChildIteratorType child_end (NodeType *N)
Detailed Description
template<>
struct llvm::GraphTraits< MachineFunction * >
Definition at line 472 of file MachineFunction.h.
Member Typedef Documentation
typedef MachineFunction::iterator llvm::GraphTraits< MachineFunction * >::nodes_iterator
Definition at line 479 of file MachineFunction.h.
Member Function Documentation
static NodeType* llvm::GraphTraits< MachineFunction * >::getEntryNode (MachineFunction * F) inline static
Definition at line 474 of file MachineFunction.h.
References llvm::MachineFunction::front().
static nodes_iterator llvm::GraphTraits< MachineFunction * >::nodes_begin (MachineFunction * F) inline static
Definition at line 480 of file MachineFunction.h.
References llvm::MachineFunction::begin().
static nodes_iterator llvm::GraphTraits< MachineFunction * >::nodes_end (MachineFunction * F) inline static
Definition at line 481 of file MachineFunction.h.
References llvm::MachineFunction::end().
static unsigned llvm::GraphTraits< MachineFunction * >::size (MachineFunction * F) inline static
Definition at line 482 of file MachineFunction.h.
References llvm::MachineFunction::size().
The documentation for this struct was generated from the following file:
MachineFunction.h