LLVM: llvm::ilist_traits< MachineBasicBlock > Struct Template Reference
LLVM API Documentation
llvm::ilist_traits< MachineBasicBlock > Struct Template Reference
#include <MachineFunction.h>
Public Member Functions
MachineBasicBlock * createSentinel () const
void destroySentinel (MachineBasicBlock *) const
MachineBasicBlock * provideInitialHead () const
MachineBasicBlock * ensureHead (MachineBasicBlock *) const
void addNodeToList (MachineBasicBlock *MBB)
void removeNodeFromList (MachineBasicBlock *MBB)
void deleteNode (MachineBasicBlock *MBB)
Public Member Functions inherited from llvm::ilist_node_traits< MachineBasicBlock >
void addNodeToList (MachineBasicBlock *)
void removeNodeFromList (MachineBasicBlock *)
void transferNodesFromList (ilist_node_traits &, ilist_iterator< MachineBasicBlock >, ilist_iterator< MachineBasicBlock >)
Static Public Member Functions
static void noteHead (MachineBasicBlock *, MachineBasicBlock *)
Static Public Member Functions inherited from llvm::ilist_nextprev_traits< MachineBasicBlock >
static MachineBasicBlock * getPrev (MachineBasicBlock *N)
static const MachineBasicBlock * getPrev (const MachineBasicBlock *N)
static MachineBasicBlock * getNext (MachineBasicBlock *N)
static const MachineBasicBlock * getNext (const MachineBasicBlock *N)
static void setPrev (MachineBasicBlock *N, MachineBasicBlock *Prev)
static void setNext (MachineBasicBlock *N, MachineBasicBlock *Next)
Static Public Member Functions inherited from llvm::ilist_sentinel_traits< MachineBasicBlock >
static MachineBasicBlock * createSentinel ()
createSentinel - create the dynamic sentinel
static void destroySentinel (MachineBasicBlock *N)
destroySentinel - deallocate the dynamic sentinel
static MachineBasicBlock * provideInitialHead ()
static MachineBasicBlock * ensureHead (MachineBasicBlock *&Head)
static void noteHead (MachineBasicBlock *NewHead, MachineBasicBlock *Sentinel)
noteHead - stash the sentinel into its default location
Static Public Member Functions inherited from llvm::ilist_node_traits< MachineBasicBlock >
static MachineBasicBlock * createNode (const MachineBasicBlock &V)
static void deleteNode (MachineBasicBlock *V)
Public Attributes
ilist_half_node< MachineBasicBlock > Sentinel
Detailed Description
template<>
struct llvm::ilist_traits< MachineBasicBlock >
Definition at line 45 of file MachineFunction.h.
Member Function Documentation
void llvm::ilist_traits< MachineBasicBlock >::addNodeToList (MachineBasicBlock * MBB)
MachineBasicBlock* llvm::ilist_traits< MachineBasicBlock >::createSentinel () const inline
Definition at line 49 of file MachineFunction.h.
void llvm::ilist_traits< MachineBasicBlock >::deleteNode (MachineBasicBlock * MBB)
void llvm::ilist_traits< MachineBasicBlock >::destroySentinel (MachineBasicBlock *) const inline
Definition at line 52 of file MachineFunction.h.
MachineBasicBlock* llvm::ilist_traits< MachineBasicBlock >::ensureHead (MachineBasicBlock *) const inline
Definition at line 55 of file MachineFunction.h.
References llvm::ilist_sentinel_traits< NodeTy >::createSentinel().
static void llvm::ilist_traits< MachineBasicBlock >::noteHead (MachineBasicBlock * , MachineBasicBlock *) inline static
Definition at line 58 of file MachineFunction.h.
References llvm::ilist_node_traits< NodeTy >::addNodeToList(), llvm::ilist_node_traits< NodeTy >::createNode(), llvm::ilist_node_traits< NodeTy >::deleteNode(), and llvm::ilist_node_traits< NodeTy >::removeNodeFromList().
MachineBasicBlock* llvm::ilist_traits< MachineBasicBlock >::provideInitialHead () const inline
Definition at line 54 of file MachineFunction.h.
References llvm::ilist_sentinel_traits< NodeTy >::createSentinel().
void llvm::ilist_traits< MachineBasicBlock >::removeNodeFromList (MachineBasicBlock * MBB)
Member Data Documentation
ilist_half_node<MachineBasicBlock> llvm::ilist_traits< MachineBasicBlock >::Sentinel mutable
Definition at line 47 of file MachineFunction.h.
The documentation for this struct was generated from the following file:
MachineFunction.h