LLVM: false::IntervalSorter Struct Reference
LLVM API Documentation
false::IntervalSorter Struct Reference
Public Member Functions
bool operator() (LiveInterval *LHS, LiveInterval *RHS) const
Detailed Description
Definition at line 129 of file StackSlotColoring.cpp.
Member Function Documentation
bool false::IntervalSorter::operator() (LiveInterval * LHS, LiveInterval * RHS) const inline
Definition at line 130 of file StackSlotColoring.cpp.
References Align, llvm::LiveStacks::begin(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::BitVector::clear(), llvm::SmallVectorImpl< T >::clear(), llvm::dbgs(), DCELimit, DEBUG, DisableSharing, llvm::LiveInterval::dump(), llvm::dump(), llvm::LiveStacks::end(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::MachineFunction::exposesReturnsTwice(), llvm::BitVector::find_first(), llvm::BitVector::find_next(), llvm::MachineBlockFrequencyInfo::getBlockFreq(), llvm::PseudoSourceValue::getFixedStack(), llvm::MachineFunction::getFrameInfo(), llvm::MachineOperand::getIndex(), llvm::TargetMachine::getInstrInfo(), llvm::LiveStacks::getInterval(), llvm::MachineFunction::getName(), llvm::LiveStacks::getNumIntervals(), llvm::MachineInstr::getNumOperands(), llvm::MachineFrameInfo::getObjectAlignment(), llvm::MachineFrameInfo::getObjectIndexEnd(), llvm::MachineFrameInfo::getObjectSize(), llvm::MachineInstr::getOperand(), llvm::LiveIntervals::getSpillWeight(), llvm::MachineFunction::getTarget(), llvm::MachineMemOperand::getValue(), llvm::LiveStacks::hasInterval(), i, I, llvm::MachineFrameInfo::isDeadObjectIndex(), llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isFI(), llvm::TargetInstrInfo::isLoadFromStackSlot(), llvm::TargetInstrInfo::isStackSlotCopy(), llvm::TargetInstrInfo::isStoreToStackSlot(), llvm::MachineInstr::memoperands_begin(), llvm::MachineInstr::memoperands_end(), llvm::A64CC::MI, MII, llvm::next(), llvm::LiveRange::overlaps(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::LiveInterval::reg, llvm::MachineFrameInfo::RemoveStackObject(), llvm::BitVector::resize(), llvm::SmallVectorImpl< T >::resize(), llvm::BitVector::set(), llvm::MachineOperand::setIndex(), llvm::MachineFrameInfo::setObjectAlignment(), llvm::MachineFrameInfo::setObjectSize(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::TargetRegisterInfo::stackSlot2Index(), and llvm::LiveInterval::weight.
The documentation for this struct was generated from the following file:
StackSlotColoring.cpp