LLVM: llvm::AliasAnalysis::Location Struct Reference
LLVM API Documentation
llvm::AliasAnalysis::Location Struct Reference
Location - A description of a memory location.
#include <AliasAnalysis.h>
Public Member Functions
Location (const Value *P=0, uint64_t S=UnknownSize, const MDNode *N=0)
Location getWithNewPtr (const Value *NewPtr) const
Location getWithNewSize (uint64_t NewSize) const
Location getWithoutTBAATag () const
Public Attributes
const Value * Ptr
Ptr - The address of the start of the location.
uint64_t Size
const MDNode * TBAATag
Detailed Description
Location - A description of a memory location.
Alias Queries...
Definition at line 106 of file AliasAnalysis.h.
Constructor & Destructor Documentation
llvm::AliasAnalysis::Location::Location (const Value * P = 0, uint64_t S = UnknownSize, const MDNode * N = 0) inline explicit
Definition at line 119 of file AliasAnalysis.h.
Referenced by llvm::AliasAnalysis::alias(), llvm::AliasAnalysis::callCapturesBefore(), llvm::AliasAnalysis::canBasicBlockModify(), llvm::AliasAnalysis::canInstructionRangeModify(), llvm::AliasAnalysis::getModRefInfo(), llvm::AliasAnalysis::isNoAlias(), and llvm::AliasAnalysis::pointsToConstantMemory().
Member Function Documentation
Location llvm::AliasAnalysis::Location::getWithNewPtr (const Value * NewPtr) const inline
Definition at line 123 of file AliasAnalysis.h.
References Ptr.
Referenced by SortNonLocalDepInfoCache().
Location llvm::AliasAnalysis::Location::getWithNewSize (uint64_t NewSize) const inline
Definition at line 129 of file AliasAnalysis.h.
References Size.
Referenced by SortNonLocalDepInfoCache().
Location llvm::AliasAnalysis::Location::getWithoutTBAATag () const inline
Definition at line 135 of file AliasAnalysis.h.
References llvm::AliasAnalysis::getLocation(), llvm::AliasAnalysis::getLocationForDest(), llvm::AliasAnalysis::getLocationForSource(), llvm::A64CC::MI, and TBAATag.
Referenced by SortNonLocalDepInfoCache().
Member Data Documentation
const Value* llvm::AliasAnalysis::Location::Ptr
Ptr - The address of the start of the location.
Definition at line 108 of file AliasAnalysis.h.
Referenced by llvm::AliasAnalysis::callCapturesBefore(), llvm::createObjCARCContractPass(), FindUnconditionalPreds(), llvm::MemoryDependenceAnalysis::getDependency(), llvm::DenseMapInfo< AliasAnalysis::Location >::getHashValue(), GetLocation(), llvm::MemoryDependenceAnalysis::getNonLocalPointerDependency(), llvm::MemoryDependenceAnalysis::getPointerDependencyFrom(), getWithNewPtr(), llvm::DenseMapInfo< AliasAnalysis::Location >::isEqual(), isLoadLoadClobberIfExtendedToFullWidth(), isOverwrite(), and isPossibleSelfRead().
uint64_t llvm::AliasAnalysis::Location::Size
Size - The maximum size of the location, in address-units, or UnknownSize if the size is not known. Note that an unknown size does not mean the pointer aliases the entire virtual address space, because there are restrictions on stepping out of one object and into another. See http://llvm.org/docs/LangRef.html#pointeraliasing
Definition at line 114 of file AliasAnalysis.h.
Referenced by llvm::DenseMapInfo< AliasAnalysis::Location >::getHashValue(), getLocForWrite(), getWithNewSize(), llvm::DenseMapInfo< AliasAnalysis::Location >::isEqual(), isLoadLoadClobberIfExtendedToFullWidth(), isOverwrite(), isPossibleSelfRead(), and SortNonLocalDepInfoCache().
const MDNode* llvm::AliasAnalysis::Location::TBAATag
TBAATag - The metadata node which describes the TBAA type of the location, or null if there is no known unique tag.
Definition at line 117 of file AliasAnalysis.h.
Referenced by llvm::DenseMapInfo< AliasAnalysis::Location >::getHashValue(), getWithoutTBAATag(), llvm::DenseMapInfo< AliasAnalysis::Location >::isEqual(), and SortNonLocalDepInfoCache().
The documentation for this struct was generated from the following file:
AliasAnalysis.h