LLVM: llvm::AMDGPURegisterInfo Struct Reference
LLVM API Documentation
llvm::AMDGPURegisterInfo Struct Reference
#include <AMDGPURegisterInfo.h>
Public Member Functions
AMDGPURegisterInfo (TargetMachine &tm)
virtual BitVector getReservedRegs (const MachineFunction &MF) const
virtual const TargetRegisterClass * getISARegClass (const TargetRegisterClass *RC) const
virtual const TargetRegisterClass * getCFGStructurizerRegClass (MVT VT) const
virtual unsigned getHWRegIndex (unsigned Reg) const
unsigned getSubRegFromChannel (unsigned Channel) const
const uint16_t * getCalleeSavedRegs (const MachineFunction *MF) const
void eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS) const
unsigned getFrameRegister (const MachineFunction &MF) const
unsigned getIndirectSubReg (unsigned IndirectIndex) const
Public Attributes
TargetMachine & TM
Static Public Attributes
static const uint16_t CalleeSavedReg = AMDGPU::NoRegister
Detailed Description
Definition at line 31 of file AMDGPURegisterInfo.h.
Constructor & Destructor Documentation
AMDGPURegisterInfo::AMDGPURegisterInfo (TargetMachine & tm)
Definition at line 20 of file AMDGPURegisterInfo.cpp.
References CalleeSavedReg.
Member Function Documentation
void AMDGPURegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS) const
Definition at line 37 of file AMDGPURegisterInfo.cpp.
Referenced by getHWRegIndex().
const uint16_t * AMDGPURegisterInfo::getCalleeSavedRegs (const MachineFunction * MF) const
Definition at line 32 of file AMDGPURegisterInfo.cpp.
References CalleeSavedReg.
Referenced by getHWRegIndex().
virtual const TargetRegisterClass* llvm::AMDGPURegisterInfo::getCFGStructurizerRegClass (MVT VT) const inline virtual
Reimplemented in llvm::R600RegisterInfo, and llvm::SIRegisterInfo.
Definition at line 49 of file AMDGPURegisterInfo.h.
unsigned AMDGPURegisterInfo::getFrameRegister (const MachineFunction & MF) const
Definition at line 44 of file AMDGPURegisterInfo.cpp.
Referenced by getHWRegIndex().
virtual unsigned llvm::AMDGPURegisterInfo::getHWRegIndex (unsigned Reg) const inline virtual
Reimplemented in llvm::SIRegisterInfo, and llvm::R600RegisterInfo.
Definition at line 53 of file AMDGPURegisterInfo.h.
References eliminateFrameIndex(), getCalleeSavedRegs(), getFrameRegister(), getIndirectSubReg(), getSubRegFromChannel(), and llvm::A64CC::MI.
unsigned AMDGPURegisterInfo::getIndirectSubReg (unsigned IndirectIndex) const
Definition at line 61 of file AMDGPURegisterInfo.cpp.
References getSubRegFromChannel().
Referenced by getHWRegIndex().
virtual const TargetRegisterClass* llvm::AMDGPURegisterInfo::getISARegClass (const TargetRegisterClass * RC) const inline virtual
Parameters
RC is an AMDIL reg class.
Returns
The ISA reg class that is equivalent to RC.
Reimplemented in llvm::SIRegisterInfo, and llvm::R600RegisterInfo.
Definition at line 44 of file AMDGPURegisterInfo.h.
Referenced by llvm::AMDGPUInstrInfo::convertToISA().
virtual BitVector llvm::AMDGPURegisterInfo::getReservedRegs (const MachineFunction & MF) const inline virtual
Reimplemented in llvm::R600RegisterInfo, and llvm::SIRegisterInfo.
Definition at line 37 of file AMDGPURegisterInfo.h.
unsigned AMDGPURegisterInfo::getSubRegFromChannel (unsigned Channel) const
Returns
the sub reg enum value for the given Channel (e.g. getSubRegFromChannel(0) -> AMDGPU::sub0)
Definition at line 49 of file AMDGPURegisterInfo.cpp.
References llvm::array_lengthof().
Referenced by llvm::R600InstrInfo::copyPhysReg(), llvm::createR600ExpandSpecialInstrsPass(), getHWRegIndex(), getIndirectSubReg(), and llvm::R600TargetLowering::LowerOperation().
Member Data Documentation
const uint16_t AMDGPURegisterInfo::CalleeSavedReg = AMDGPU::NoRegister static
Definition at line 33 of file AMDGPURegisterInfo.h.
Referenced by AMDGPURegisterInfo(), and getCalleeSavedRegs().
TargetMachine& llvm::AMDGPURegisterInfo::TM
Definition at line 32 of file AMDGPURegisterInfo.h.
The documentation for this struct was generated from the following files:
AMDGPURegisterInfo.h
AMDGPURegisterInfo.cpp