LLVM: llvm::SystemZRegisterInfo Struct Reference
LLVM API Documentation
llvm::SystemZRegisterInfo Struct Reference
#include <SystemZRegisterInfo.h>
Public Member Functions
SystemZRegisterInfo (SystemZTargetMachine &tm)
virtual bool requiresRegisterScavenging (const MachineFunction &MF) const LLVM_OVERRIDE
virtual bool requiresFrameIndexScavenging (const MachineFunction &MF) const LLVM_OVERRIDE
virtual bool trackLivenessAfterRegAlloc (const MachineFunction &MF) const LLVM_OVERRIDE
virtual const uint16_t * getCalleeSavedRegs (const MachineFunction *MF=0) const LLVM_OVERRIDE
virtual BitVector getReservedRegs (const MachineFunction &MF) const LLVM_OVERRIDE
virtual void eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger *RS) const LLVM_OVERRIDE
virtual unsigned getFrameRegister (const MachineFunction &MF) const LLVM_OVERRIDE
Detailed Description
Definition at line 35 of file SystemZRegisterInfo.h.
Constructor & Destructor Documentation
SystemZRegisterInfo::SystemZRegisterInfo (SystemZTargetMachine & tm)
Definition at line 20 of file SystemZRegisterInfo.cpp.
Member Function Documentation
void SystemZRegisterInfo::eliminateFrameIndex (MachineBasicBlock::iterator MI, int SPAdj, unsigned FIOperandNum, RegScavenger * RS) const virtual
Definition at line 59 of file SystemZRegisterInfo.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::BuildMI(), llvm::MachineOperand::ChangeToRegister(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::ISD::FrameIndex, llvm::TargetFrameLowering::getFrameIndexOffset(), llvm::TargetMachine::getFrameLowering(), getFrameRegister(), llvm::SystemZTargetMachine::getInstrInfo(), llvm::SystemZInstrInfo::getOpcodeForOffset(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getTarget(), llvm::SystemZII::HasIndex, llvm::RegState::Kill, llvm::SystemZInstrInfo::loadImmediate(), and TII.
const uint16_t * SystemZRegisterInfo::getCalleeSavedRegs (const MachineFunction * MF = 0) const virtual
Definition at line 24 of file SystemZRegisterInfo.cpp.
unsigned SystemZRegisterInfo::getFrameRegister (const MachineFunction & MF) const virtual
Definition at line 138 of file SystemZRegisterInfo.cpp.
References llvm::TargetMachine::getFrameLowering(), llvm::MachineFunction::getTarget(), and llvm::TargetFrameLowering::hasFP().
Referenced by eliminateFrameIndex().
BitVector SystemZRegisterInfo::getReservedRegs (const MachineFunction & MF) const virtual
Definition at line 38 of file SystemZRegisterInfo.cpp.
References llvm::TargetMachine::getFrameLowering(), llvm::MachineFunction::getTarget(), llvm::TargetFrameLowering::hasFP(), and llvm::BitVector::set().
virtual bool llvm::SystemZRegisterInfo::requiresFrameIndexScavenging (const MachineFunction & MF) const inline virtual
Definition at line 47 of file SystemZRegisterInfo.h.
virtual bool llvm::SystemZRegisterInfo::requiresRegisterScavenging (const MachineFunction & MF) const inline virtual
Definition at line 43 of file SystemZRegisterInfo.h.
virtual bool llvm::SystemZRegisterInfo::trackLivenessAfterRegAlloc (const MachineFunction & MF) const inline virtual
Definition at line 51 of file SystemZRegisterInfo.h.
References LLVM_OVERRIDE, and llvm::A64CC::MI.
The documentation for this struct was generated from the following files:
SystemZRegisterInfo.h
SystemZRegisterInfo.cpp