LLVM: llvm::DenseMapInfo< CallValue > Struct Template Reference
LLVM API Documentation
llvm::DenseMapInfo< CallValue > Struct Template Reference
Static Public Member Functions
static CallValue getEmptyKey ()
static CallValue getTombstoneKey ()
static unsigned getHashValue (CallValue Val)
static bool isEqual (CallValue LHS, CallValue RHS)
Detailed Description
template<>
struct llvm::DenseMapInfo< CallValue >
Definition at line 218 of file EarlyCSE.cpp.
Member Function Documentation
static CallValue llvm::DenseMapInfo< CallValue >::getEmptyKey () inline static
Definition at line 219 of file EarlyCSE.cpp.
static unsigned llvm::DenseMapInfo< CallValue >::getHashValue (CallValue Val) static
static CallValue llvm::DenseMapInfo< CallValue >::getTombstoneKey () inline static
Definition at line 222 of file EarlyCSE.cpp.
References llvm::AnalysisUsage::addRequired(), llvm::sys::path::end(), F(), generation, getHash(), llvm::User::getNumOperands(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::PassRegistry::getPassRegistry(), llvm::Value::getType(), i, llvm::initializeEarlyCSEPass(), llvm::Instruction::isIdenticalTo(), llvm::Type::isMetadataTy(), LLVM_DELETED_FUNCTION, n, node, and llvm::AnalysisUsage::setPreservesCFG().
static bool llvm::DenseMapInfo< CallValue >::isEqual (CallValue LHS, CallValue RHS) static
The documentation for this struct was generated from the following file:
EarlyCSE.cpp