LLVM: llvm::GraphTraits< DomTreeNode * > Struct Template Reference
LLVM API Documentation
llvm::GraphTraits< DomTreeNode * > Struct Template Reference
#include <Dominators.h>
Public Types
typedef DomTreeNode NodeType
typedef NodeType::iterator ChildIteratorType
typedef df_iterator< DomTreeNode * > nodes_iterator
Static Public Member Functions
static NodeType * getEntryNode (NodeType *N)
static ChildIteratorType child_begin (NodeType *N)
static ChildIteratorType child_end (NodeType *N)
static nodes_iterator nodes_begin (DomTreeNode *N)
static nodes_iterator nodes_end (DomTreeNode *N)
Detailed Description
template<>
struct llvm::GraphTraits< DomTreeNode * >
DominatorTree GraphTraits specialization so the DominatorTree can be iterable by generic graph iterators.
Definition at line 897 of file Dominators.h.
Member Typedef Documentation
typedef NodeType::iterator llvm::GraphTraits< DomTreeNode * >::ChildIteratorType
Definition at line 899 of file Dominators.h.
typedef df_iterator<DomTreeNode*> llvm::GraphTraits< DomTreeNode * >::nodes_iterator
Definition at line 911 of file Dominators.h.
typedef DomTreeNode llvm::GraphTraits< DomTreeNode * >::NodeType
Definition at line 898 of file Dominators.h.
Member Function Documentation
static ChildIteratorType llvm::GraphTraits< DomTreeNode * >::child_begin (NodeType * N) inline static
Definition at line 904 of file Dominators.h.
References llvm::DomTreeNodeBase< NodeT >::begin().
static ChildIteratorType llvm::GraphTraits< DomTreeNode * >::child_end (NodeType * N) inline static
Definition at line 907 of file Dominators.h.
References llvm::DomTreeNodeBase< NodeT >::end().
static NodeType* llvm::GraphTraits< DomTreeNode * >::getEntryNode (NodeType * N) inline static
Definition at line 901 of file Dominators.h.
References N.
static nodes_iterator llvm::GraphTraits< DomTreeNode * >::nodes_begin (DomTreeNode * N) inline static
Definition at line 913 of file Dominators.h.
References llvm::df_begin().
static nodes_iterator llvm::GraphTraits< DomTreeNode * >::nodes_end (DomTreeNode * N) inline static
Definition at line 917 of file Dominators.h.
References llvm::df_end().
The documentation for this struct was generated from the following file:
Dominators.h