LLVM: llvm::MachineTraceMetrics::FixedBlockInfo Struct Reference
LLVM API Documentation
llvm::MachineTraceMetrics::FixedBlockInfo Struct Reference
#include <MachineTraceMetrics.h>
Public Member Functions
FixedBlockInfo ()
bool hasResources () const
Returns true when resource information for this block has been computed.
void invalidate ()
Invalidate resource information.
Public Attributes
unsigned InstrCount
bool HasCalls
True when the block contains calls.
Detailed Description
Per-basic block information that doesn't depend on the trace through the block.
Definition at line 90 of file MachineTraceMetrics.h.
Constructor & Destructor Documentation
llvm::MachineTraceMetrics::FixedBlockInfo::FixedBlockInfo () inline
Definition at line 98 of file MachineTraceMetrics.h.
Member Function Documentation
bool llvm::MachineTraceMetrics::FixedBlockInfo::hasResources () const inline
Returns true when resource information for this block has been computed.
Definition at line 101 of file MachineTraceMetrics.h.
Referenced by llvm::MachineTraceMetrics::getResources().
void llvm::MachineTraceMetrics::FixedBlockInfo::invalidate () inline
Invalidate resource information.
Definition at line 104 of file MachineTraceMetrics.h.
References llvm::MachineTraceMetrics::getProcResourceCycles(), and llvm::MachineTraceMetrics::getResources().
Member Data Documentation
bool llvm::MachineTraceMetrics::FixedBlockInfo::HasCalls
True when the block contains calls.
Definition at line 96 of file MachineTraceMetrics.h.
Referenced by llvm::MachineTraceMetrics::getResources().
unsigned llvm::MachineTraceMetrics::FixedBlockInfo::InstrCount
The number of non-trivial instructions in the block. Doesn't count PHI and COPY instructions that are likely to be removed.
Definition at line 93 of file MachineTraceMetrics.h.
Referenced by llvm::MachineTraceMetrics::Ensemble::getLoopFor(), llvm::MachineTraceMetrics::getResources(), and isExitingLoop().
The documentation for this struct was generated from the following file:
MachineTraceMetrics.h