LLVM: llvm::DenseMapInfo< SimpleValue > Struct Template Reference
LLVM API Documentation
llvm::DenseMapInfo< SimpleValue > Struct Template Reference
Static Public Member Functions
static SimpleValue getEmptyKey ()
static SimpleValue getTombstoneKey ()
static unsigned getHashValue (SimpleValue Val)
static bool isEqual (SimpleValue LHS, SimpleValue RHS)
Detailed Description
template<>
struct llvm::DenseMapInfo< SimpleValue >
Definition at line 75 of file EarlyCSE.cpp.
Member Function Documentation
static SimpleValue llvm::DenseMapInfo< SimpleValue >::getEmptyKey () inline static
Definition at line 76 of file EarlyCSE.cpp.
static unsigned llvm::DenseMapInfo< SimpleValue >::getHashValue (SimpleValue Val) static
static SimpleValue llvm::DenseMapInfo< SimpleValue >::getTombstoneKey () inline static
Definition at line 79 of file EarlyCSE.cpp.
References llvm::dyn_cast(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::CmpInst::getPredicate(), llvm::Value::getType(), llvm::hash_combine(), llvm::hash_combine_range(), llvm::BinaryOperator::hasNoSignedWrap(), llvm::BinaryOperator::hasNoUnsignedWrap(), I, llvm::Instruction::isIdenticalTo(), llvm::Type::isVoidTy(), llvm::OverflowingBinaryOperator::NoSignedWrap, llvm::OverflowingBinaryOperator::NoUnsignedWrap, llvm::CallInst::onlyReadsMemory(), std::swap(), llvm::User::value_op_begin(), and llvm::User::value_op_end().
static bool llvm::DenseMapInfo< SimpleValue >::isEqual (SimpleValue LHS, SimpleValue RHS) static
The documentation for this struct was generated from the following file:
EarlyCSE.cpp