LLVM: ConsecutiveMemoryChainSorter Struct Reference
LLVM API Documentation
ConsecutiveMemoryChainSorter Struct Reference
Sorts store nodes in a link according to their offset from a shared.
Public Member Functions
bool operator() (MemOpLink LHS, MemOpLink RHS)
Detailed Description
Sorts store nodes in a link according to their offset from a shared.
Definition at line 8548 of file DAGCombiner.cpp.
Member Function Documentation
bool ConsecutiveMemoryChainSorter::operator() (MemOpLink LHS, MemOpLink RHS) inline
Definition at line 8549 of file DAGCombiner.cpp.
References llvm::ISD::ADD, llvm::AfterLegalizeTypes, llvm::AfterLegalizeVectorOps, Align, llvm::ISD::allOperandsUndef(), llvm::ISD::ANY_EXTEND, llvm::SmallVectorImpl< T >::append(), BaseIndexOffset::Base, llvm::SmallVectorTemplateCommon< T >::begin(), llvm::ISD::BITCAST, llvm::EVT::bitsEq(), llvm::EVT::bitsGT(), llvm::EVT::bitsLT(), llvm::ISD::BUILD_VECTOR, llvm::ISD::CONCAT_VECTORS, llvm::ISD::DELETED_NODE, llvm::SelectionDAG::DeleteNode(), llvm::dyn_cast(), llvm::SmallVectorTemplateCommon< T >::end(), BaseIndexOffset::equalBaseIndex(), llvm::ISD::EXTLOAD, llvm::ISD::EXTRACT_SUBVECTOR, llvm::ISD::EXTRACT_VECTOR_ELT, llvm::MVT::f128, llvm::MVT::f16, llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, llvm::ISD::FP_ROUND, llvm::DataLayout::getABITypeAlignment(), llvm::MemSDNode::getAlignment(), llvm::Function::getAttributes(), llvm::MemSDNode::getBasePtr(), llvm::LoadSDNode::getBasePtr(), llvm::StoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getContext(), llvm::TargetLoweringBase::getDataLayout(), llvm::SelectionDAG::getExtLoad(), llvm::MachineFunction::getFunction(), llvm::EVT::getIntegerVT(), llvm::SelectionDAG::getLoad(), llvm::APInt::getLowBitsSet(), llvm::SelectionDAG::getMachineFunction(), llvm::ShuffleVectorSDNode::getMaskElt(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MemSDNode::getPointerInfo(), llvm::EVT::getScalarType(), llvm::SelectionDAG::getSExtOrTrunc(), llvm::EVT::getSizeInBits(), llvm::SelectionDAG::getStore(), llvm::TargetMachine::getSubtarget(), llvm::TargetLoweringBase::getTargetMachine(), llvm::MemSDNode::getTBAAInfo(), llvm::SelectionDAG::getTruncStore(), llvm::TargetLoweringBase::getTypeAction(), llvm::EVT::getTypeForEVT(), llvm::TargetLoweringBase::getTypeToTransformTo(), llvm::SelectionDAG::getUNDEF(), llvm::SDValue::getValue(), llvm::StoreSDNode::getValue(), llvm::SDValue::getValueType(), llvm::SDNode::getValueType(), llvm::EVT::getVectorElementType(), llvm::TargetLoweringBase::getVectorIdxTy(), llvm::EVT::getVectorNumElements(), llvm::SelectionDAG::getVectorShuffle(), llvm::EVT::getVectorVT(), llvm::MachinePointerInfo::getWithOffset(), llvm::ConstantSDNode::getZExtValue(), llvm::SDNode::hasNUsesOfValue(), llvm::SDValue::hasOneUse(), llvm::SDNode::hasOneUse(), llvm::HexagonISD::Hi, i, llvm::MVT::i32, llvm::MVT::i64, llvm::tgtok::In, llvm::SelectionDAG::InferPtrAlignment(), llvm::ISD::INSERT_SUBVECTOR, int, llvm::TargetLoweringBase::isBigEndian(), llvm::EVT::isFloatingPoint(), llvm::LSBaseSDNode::isIndexed(), llvm::EVT::isInteger(), llvm::MemSDNode::isInvariant(), llvm::TargetLoweringBase::isLittleEndian(), llvm::TargetLoweringBase::isLoadExtLegal(), llvm::MemSDNode::isNonTemporal(), llvm::ISD::isNormalLoad(), llvm::TargetLoweringBase::isOperationLegal(), llvm::TargetLoweringBase::isOperationLegalOrCustom(), llvm::isPowerOf2_32(), llvm::EVT::isSimple(), llvm::TargetLoweringBase::isTruncateFree(), llvm::StoreSDNode::isTruncatingStore(), llvm::TargetLoweringBase::isTruncStoreLegal(), llvm::TargetLoweringBase::isTypeLegal(), llvm::LSBaseSDNode::isUnindexed(), llvm::EVT::isVector(), llvm::MemSDNode::isVolatile(), llvm_unreachable, llvm::HexagonISD::Lo, llvm::SPII::Load, llvm::ISD::LOAD, BaseIndexOffset::match(), llvm::MinAlign(), N, llvm::Attribute::NoImplicitFloat, llvm::ISD::NON_EXTLOAD, llvm::CodeGenOpt::None, BaseIndexOffset::Offset, MemOpLink::OffsetFromBase, llvm::SDNode::op_begin(), llvm::SDNode::op_end(), llvm::MVT::Other, llvm::MVT::ppcf128, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SelectionDAG::ReplaceAllUsesOfValuesWith(), llvm::SelectionDAG::ReplaceAllUsesOfValueWith(), llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::NVPTX::PTXLdStInstCode::Scalar, llvm::ISD::SCALAR_TO_VECTOR, llvm::ISD::SEXTLOAD, llvm::ISD::SINT_TO_FP, llvm::SmallVectorTemplateCommon< T >::size(), llvm::A64DB::ST, llvm::ISD::STORE, std::swap(), llvm::ISD::TargetConstantFP, llvm::ISD::TokenFactor, llvm::ISD::TRUNCATE, llvm::TargetLoweringBase::TypePromoteInteger, llvm::ISD::UINT_TO_FP, llvm::ISD::UNDEF, llvm::SDNode::use_begin(), llvm::SDNode::use_empty(), llvm::ISD::VECTOR_SHUFFLE, llvm::ISD::ZERO_EXTEND, llvm::APInt::zext(), and llvm::ISD::ZEXTLOAD.
The documentation for this struct was generated from the following file:
DAGCombiner.cpp