LLVM: llvm::DenseMapInfo< AliasAnalysis::Location > Struct Template Reference
LLVM API Documentation
llvm::DenseMapInfo< AliasAnalysis::Location > Struct Template Reference
#include <AliasAnalysis.h>
Static Public Member Functions
static AliasAnalysis::Location getEmptyKey ()
static AliasAnalysis::Location getTombstoneKey ()
static unsigned getHashValue (const AliasAnalysis::Location &Val)
static bool isEqual (const AliasAnalysis::Location &LHS, const AliasAnalysis::Location &RHS)
Detailed Description
template<>
struct llvm::DenseMapInfo< AliasAnalysis::Location >
Definition at line 559 of file AliasAnalysis.h.
Member Function Documentation
static AliasAnalysis::Location llvm::DenseMapInfo< AliasAnalysis::Location >::getEmptyKey () inline static
Definition at line 560 of file AliasAnalysis.h.
static unsigned llvm::DenseMapInfo< AliasAnalysis::Location >::getHashValue (const AliasAnalysis::Location & Val) inline static
Definition at line 570 of file AliasAnalysis.h.
References llvm::AliasAnalysis::Location::Ptr, llvm::AliasAnalysis::Location::Size, and llvm::AliasAnalysis::Location::TBAATag.
static AliasAnalysis::Location llvm::DenseMapInfo< AliasAnalysis::Location >::getTombstoneKey () inline static
Definition at line 565 of file AliasAnalysis.h.
static bool llvm::DenseMapInfo< AliasAnalysis::Location >::isEqual (const AliasAnalysis::Location & LHS, const AliasAnalysis::Location & RHS) inline static
Definition at line 575 of file AliasAnalysis.h.
References llvm::isIdentifiedObject(), llvm::isNoAliasArgument(), llvm::isNoAliasCall(), llvm::AliasAnalysis::Location::Ptr, llvm::AliasAnalysis::Location::Size, and llvm::AliasAnalysis::Location::TBAATag.
The documentation for this struct was generated from the following file:
AliasAnalysis.h