LLVM: llvm::SubMultiClassReference Struct Reference
LLVM API Documentation
llvm::SubMultiClassReference Struct Reference
Public Member Functions
SubMultiClassReference ()
bool isInvalid () const
void dump () const
Public Attributes
SMRange RefRange
MultiClass * MC
std::vector< Init * > TemplateArgs
Detailed Description
Definition at line 37 of file TGParser.cpp.
Constructor & Destructor Documentation
llvm::SubMultiClassReference::SubMultiClassReference () inline
Definition at line 41 of file TGParser.cpp.
Member Function Documentation
void llvm::SubMultiClassReference::dump () const
Definition at line 47 of file TGParser.cpp.
References llvm::Record::addSuperClass(), llvm::Record::addValue(), llvm::tgtok::Bit, llvm::Init::convertInitializerTo(), llvm::tgtok::Def, llvm::MultiClass::DefPrototypes, llvm::dyn_cast(), llvm::lltok::Error, llvm::errs(), llvm::BitsRecTy::get(), llvm::BitsInit::get(), llvm::RecTy::getAsString(), llvm::Init::getAsString(), llvm::Init::getAsUnquotedString(), llvm::BitsInit::getBit(), llvm::VarInit::getName(), llvm::RecordVal::getName(), llvm::Record::getName(), llvm::RecordVal::getNameInit(), llvm::Record::getNameInitAsString(), llvm::BitsInit::getNumBits(), llvm::ListInit::getSize(), llvm::Record::getSuperClasses(), llvm::Record::getSuperClassRanges(), llvm::Record::getTemplateArgs(), llvm::TypedInit::getType(), llvm::RecordVal::getType(), llvm::RecordVal::getValue(), llvm::Record::getValue(), llvm::Record::getValues(), i, llvm::Init::isComplete(), llvm::Record::isSubClassOf(), j(), llvm::tgtok::List, Loops, MC, llvm::SubClassReference::Rec, llvm::MultiClass::Rec, llvm::SubClassReference::RefRange, RefRange, llvm::Record::removeValue(), llvm::ListInit::resolveListElementReference(), llvm::Record::resolveReferences(), llvm::Record::resolveReferencesTo(), llvm::PPCISD::SC, SetValue(), llvm::RecordVal::setValue(), llvm::SMRange::Start, llvm::SubClassReference::TemplateArgs, TemplateArgs, and llvm::utostr().
bool llvm::SubMultiClassReference::isInvalid () const inline
Definition at line 43 of file TGParser.cpp.
References llvm::dump().
Member Data Documentation
MultiClass* llvm::SubMultiClassReference::MC
Definition at line 39 of file TGParser.cpp.
Referenced by dump(), and GetNewAnonymousName().
SMRange llvm::SubMultiClassReference::RefRange
Definition at line 38 of file TGParser.cpp.
Referenced by dump(), and GetNewAnonymousName().
std::vector<Init*> llvm::SubMultiClassReference::TemplateArgs
Definition at line 40 of file TGParser.cpp.
Referenced by dump(), and GetNewAnonymousName().
The documentation for this struct was generated from the following file:
TGParser.cpp