LLVM: llvm::ClonedCodeInfo Struct Reference
LLVM API Documentation
llvm::ClonedCodeInfo Struct Reference
#include <Cloning.h>
Public Member Functions
ClonedCodeInfo ()
Public Attributes
bool ContainsCalls
bool ContainsDynamicAllocas
Detailed Description
ClonedCodeInfo - This struct can be used to capture information about code being cloned, while it is being cloned.
Definition at line 54 of file Cloning.h.
Constructor & Destructor Documentation
llvm::ClonedCodeInfo::ClonedCodeInfo () inline
Definition at line 65 of file Cloning.h.
References BB, llvm::CloneAndPruneFunctionInto(), llvm::CloneBasicBlock(), llvm::CloneFunction(), llvm::CloneFunctionInto(), and F().
Member Data Documentation
bool llvm::ClonedCodeInfo::ContainsCalls
ContainsCalls - This is set to true if the cloned code contains a normal call instruction.
Definition at line 57 of file Cloning.h.
Referenced by llvm::CloneBasicBlock(), HandleInlinedInvoke(), and llvm::InlineFunction().
bool llvm::ClonedCodeInfo::ContainsDynamicAllocas
ContainsDynamicAllocas - This is set to true if the cloned code contains a 'dynamic' alloca. Dynamic allocas are allocas that are either not in the entry block or they are in the entry block but are not a constant size.
Definition at line 63 of file Cloning.h.
Referenced by llvm::CloneBasicBlock(), and llvm::InlineFunction().
The documentation for this struct was generated from the following file:
Cloning.h