LLVM: llvm::ISD::ArgFlagsTy Struct Reference
LLVM API Documentation
llvm::ISD::ArgFlagsTy Struct Reference
#include <TargetCallingConv.h>
Public Member Functions
ArgFlagsTy ()
bool isZExt () const
void setZExt ()
bool isSExt () const
void setSExt ()
bool isInReg () const
void setInReg ()
bool isSRet () const
void setSRet ()
bool isByVal () const
void setByVal ()
bool isNest () const
void setNest ()
bool isReturned () const
void setReturned ()
unsigned getByValAlign () const
void setByValAlign (unsigned A)
bool isSplit () const
void setSplit ()
unsigned getOrigAlign () const
void setOrigAlign (unsigned A)
unsigned getByValSize () const
void setByValSize (unsigned S)
uint64_t getRawBits () const
getRawBits - Represent the flags as a bunch of bits.
Detailed Description
Definition at line 24 of file TargetCallingConv.h.
Constructor & Destructor Documentation
llvm::ISD::ArgFlagsTy::ArgFlagsTy () inline
Definition at line 54 of file TargetCallingConv.h.
Member Function Documentation
unsigned llvm::ISD::ArgFlagsTy::getByValAlign () const inline
Definition at line 77 of file TargetCallingConv.h.
Referenced by llvm::MipsTargetLowering::MipsCC::analyzeReturn(), AnalyzeReturnValues(), CalculateStackSlotSize(), CreateCopyOfByValArgument(), FPCCToARMCC(), llvm::Hexagon_CCState::HandleByVal(), llvm::CCState::HandleByVal(), llvm::MipsTargetLowering::MipsCC::intArgRegs(), isLocalCall(), llvm::AArch64TargetLowering::LowerCall(), and llvm::SparcTargetLowering::LowerCall_32().
unsigned llvm::ISD::ArgFlagsTy::getByValSize () const inline
Definition at line 98 of file TargetCallingConv.h.
Referenced by llvm::MipsTargetLowering::MipsCC::analyzeReturn(), AnalyzeReturnValues(), CalculateStackSlotSize(), CC_Hexagon(), CC_Hexagon_VarArg(), computeBytesPoppedByCallee(), CreateCopyOfByValArgument(), FPCCToARMCC(), FuncIsMadeTailCallSafe(), llvm::MipsTargetLowering::getOpndList(), llvm::Hexagon_CCState::HandleByVal(), llvm::CCState::HandleByVal(), llvm::MipsTargetLowering::MipsCC::intArgRegs(), isLocalCall(), llvm::AArch64TargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::AArch64TargetLowering::LowerFormalArguments(), LowerVASTART(), and MatchingStackOffset().
unsigned llvm::ISD::ArgFlagsTy::getOrigAlign () const inline
Definition at line 89 of file TargetCallingConv.h.
Referenced by allocateStack(), and CC_MipsO32().
uint64_t llvm::ISD::ArgFlagsTy::getRawBits () const inline
getRawBits - Represent the flags as a bunch of bits.
Definition at line 106 of file TargetCallingConv.h.
bool llvm::ISD::ArgFlagsTy::isByVal () const inline
Definition at line 68 of file TargetCallingConv.h.
Referenced by AnalyzeArguments(), llvm::MipsTargetLowering::MipsCC::analyzeCallOperands(), llvm::MipsTargetLowering::MipsCC::analyzeFormalArguments(), AnalyzeReturnValues(), CalculateStackSlotSize(), CalculateTailCallSPDiff(), CC_Hexagon(), CC_Hexagon_VarArg(), CC_MipsO32(), computeBytesPoppedByCallee(), EmitTailCallStoreRetAddr(), FPCCToARMCC(), FuncIsMadeTailCallSafe(), llvm::MipsTargetLowering::getOpndList(), isLocalCall(), llvm::HexagonTargetLowering::LowerCall(), llvm::AArch64TargetLowering::LowerCall(), llvm::SparcTargetLowering::LowerCall_32(), llvm::SITargetLowering::LowerFormalArguments(), llvm::HexagonTargetLowering::LowerFormalArguments(), llvm::AArch64TargetLowering::LowerFormalArguments(), LowerVASTART(), and MatchingStackOffset().
bool llvm::ISD::ArgFlagsTy::isInReg () const inline
Definition at line 62 of file TargetCallingConv.h.
Referenced by argsAreStructReturn(), callIsStructReturn(), and llvm::SITargetLowering::LowerFormalArguments().
bool llvm::ISD::ArgFlagsTy::isNest () const inline
Definition at line 71 of file TargetCallingConv.h.
bool llvm::ISD::ArgFlagsTy::isReturned () const inline
Definition at line 74 of file TargetCallingConv.h.
Referenced by FPCCToARMCC().
bool llvm::ISD::ArgFlagsTy::isSExt () const inline
Definition at line 59 of file TargetCallingConv.h.
Referenced by AnalyzeArguments(), CalculateStackSlotSize(), CC_Hexagon(), CC_Hexagon_VarArg(), CC_MipsO32(), computeBytesPoppedByCallee(), isLocalCall(), and RetCC_Hexagon().
bool llvm::ISD::ArgFlagsTy::isSplit () const inline
Definition at line 86 of file TargetCallingConv.h.
bool llvm::ISD::ArgFlagsTy::isSRet () const inline
Definition at line 65 of file TargetCallingConv.h.
Referenced by argsAreStructReturn(), callIsStructReturn(), CC_Sparc_Assign_SRet(), FPCCToARMCC(), and llvm::SparcTargetLowering::LowerCall_32().
bool llvm::ISD::ArgFlagsTy::isZExt () const inline
Definition at line 56 of file TargetCallingConv.h.
Referenced by AnalyzeArguments(), CalculateStackSlotSize(), CC_Hexagon(), CC_Hexagon_VarArg(), CC_MipsO32(), and RetCC_Hexagon().
void llvm::ISD::ArgFlagsTy::setByVal () inline
Definition at line 69 of file TargetCallingConv.h.
Referenced by computeBytesPoppedByCallee(), and isOnlyUsedInEntryBlock().
void llvm::ISD::ArgFlagsTy::setByValAlign (unsigned A) inline
Definition at line 81 of file TargetCallingConv.h.
References llvm::Log2_32().
Referenced by computeBytesPoppedByCallee(), and isOnlyUsedInEntryBlock().
void llvm::ISD::ArgFlagsTy::setByValSize (unsigned S) inline
Definition at line 101 of file TargetCallingConv.h.
Referenced by computeBytesPoppedByCallee(), and isOnlyUsedInEntryBlock().
void llvm::ISD::ArgFlagsTy::setInReg () inline
Definition at line 63 of file TargetCallingConv.h.
Referenced by computeBytesPoppedByCallee(), llvm::GetReturnInfo(), llvm::SelectionDAGBuilder::getValueImpl(), isOnlyUsedInEntryBlock(), and llvm::TargetLowering::LowerCallTo().
void llvm::ISD::ArgFlagsTy::setNest () inline
Definition at line 72 of file TargetCallingConv.h.
Referenced by computeBytesPoppedByCallee(), and isOnlyUsedInEntryBlock().
void llvm::ISD::ArgFlagsTy::setOrigAlign (unsigned A) inline
Definition at line 93 of file TargetCallingConv.h.
References llvm::Log2_32().
Referenced by computeBytesPoppedByCallee(), getComparePred(), and isOnlyUsedInEntryBlock().
void llvm::ISD::ArgFlagsTy::setReturned () inline
Definition at line 75 of file TargetCallingConv.h.
void llvm::ISD::ArgFlagsTy::setSExt () inline
Definition at line 60 of file TargetCallingConv.h.
Referenced by computeBytesPoppedByCallee(), getComparePred(), llvm::GetReturnInfo(), llvm::SelectionDAGBuilder::getValueImpl(), isOnlyUsedInEntryBlock(), and llvm::TargetLowering::LowerCallTo().
void llvm::ISD::ArgFlagsTy::setSplit () inline
Definition at line 87 of file TargetCallingConv.h.
Referenced by isOnlyUsedInEntryBlock(), llvm::TargetLowering::LowerCallTo(), and llvm::SITargetLowering::LowerFormalArguments().
void llvm::ISD::ArgFlagsTy::setSRet () inline
Definition at line 66 of file TargetCallingConv.h.
Referenced by isOnlyUsedInEntryBlock().
void llvm::ISD::ArgFlagsTy::setZExt () inline
Definition at line 57 of file TargetCallingConv.h.
Referenced by computeBytesPoppedByCallee(), getComparePred(), llvm::GetReturnInfo(), llvm::SelectionDAGBuilder::getValueImpl(), isOnlyUsedInEntryBlock(), and llvm::TargetLowering::LowerCallTo().
The documentation for this struct was generated from the following file:
TargetCallingConv.h