LLVM: llvm::MipsAnalyzeImmediate::Inst Struct Reference
LLVM API Documentation
llvm::MipsAnalyzeImmediate::Inst Struct Reference
#include <MipsAnalyzeImmediate.h>
Public Member Functions
Inst (unsigned Opc, unsigned ImmOpnd)
Public Attributes
unsigned Opc
unsigned ImmOpnd
Detailed Description
Definition at line 19 of file MipsAnalyzeImmediate.h.
Constructor & Destructor Documentation
MipsAnalyzeImmediate::Inst::Inst (unsigned Opc, unsigned ImmOpnd)
Definition at line 15 of file MipsAnalyzeImmediate.cpp.
References llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::SmallVectorImpl< T >::clear(), llvm::countTrailingZeros(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::SmallVectorImpl< T >::erase(), I, ImmOpnd, llvm::SmallVectorImpl< T >::insert(), llvm::isInt< 16 >(), Opc, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), S, and llvm::SmallVectorTemplateCommon< T, typename >::size().
Member Data Documentation
unsigned llvm::MipsAnalyzeImmediate::Inst::ImmOpnd
Definition at line 20 of file MipsAnalyzeImmediate.h.
Referenced by Inst().
unsigned llvm::MipsAnalyzeImmediate::Inst::Opc
Definition at line 20 of file MipsAnalyzeImmediate.h.
Referenced by Inst().
The documentation for this struct was generated from the following files:
MipsAnalyzeImmediate.h
MipsAnalyzeImmediate.cpp