LLVM: llvm::DWARFDebugLine::Sequence Struct Reference
LLVM API Documentation
llvm::DWARFDebugLine::Sequence Struct Reference
#include <DWARFDebugLine.h>
Public Member Functions
Sequence ()
void reset ()
bool isValid () const
bool containsPC (uint64_t pc) const
Static Public Member Functions
static bool orderByLowPC (const Sequence &LHS, const Sequence &RHS)
Public Attributes
uint64_t LowPC
uint64_t HighPC
unsigned FirstRowIndex
unsigned LastRowIndex
bool Empty
Detailed Description
Definition at line 138 of file DWARFDebugLine.h.
Constructor & Destructor Documentation
llvm::DWARFDebugLine::Sequence::Sequence () inline
Definition at line 147 of file DWARFDebugLine.h.
Member Function Documentation
bool llvm::DWARFDebugLine::Sequence::containsPC (uint64_t pc) const inline
Definition at line 161 of file DWARFDebugLine.h.
Referenced by llvm::DWARFDebugLine::LineTable::lookupAddress().
bool llvm::DWARFDebugLine::Sequence::isValid () const inline
Definition at line 158 of file DWARFDebugLine.h.
static bool llvm::DWARFDebugLine::Sequence::orderByLowPC (const Sequence & LHS, const Sequence & RHS) inline static
Definition at line 155 of file DWARFDebugLine.h.
References LowPC.
Referenced by llvm::DWARFDebugLine::LineTable::lookupAddress(), and llvm::DWARFDebugLine::LineTable::lookupAddressRange().
void llvm::DWARFDebugLine::Sequence::reset () inline
Definition at line 148 of file DWARFDebugLine.h.
Referenced by llvm::DWARFDebugLine::State::reset().
Member Data Documentation
bool llvm::DWARFDebugLine::Sequence::Empty
Definition at line 145 of file DWARFDebugLine.h.
unsigned llvm::DWARFDebugLine::Sequence::FirstRowIndex
Definition at line 143 of file DWARFDebugLine.h.
Referenced by llvm::DWARFDebugLine::LineTable::lookupAddress(), and llvm::DWARFDebugLine::LineTable::lookupAddressRange().
uint64_t llvm::DWARFDebugLine::Sequence::HighPC
Definition at line 142 of file DWARFDebugLine.h.
Referenced by llvm::DWARFDebugLine::LineTable::lookupAddressRange().
unsigned llvm::DWARFDebugLine::Sequence::LastRowIndex
Definition at line 144 of file DWARFDebugLine.h.
Referenced by llvm::DWARFDebugLine::LineTable::lookupAddress(), and llvm::DWARFDebugLine::LineTable::lookupAddressRange().
uint64_t llvm::DWARFDebugLine::Sequence::LowPC
Definition at line 141 of file DWARFDebugLine.h.
Referenced by llvm::DWARFDebugLine::LineTable::lookupAddress(), llvm::DWARFDebugLine::LineTable::lookupAddressRange(), and orderByLowPC().
The documentation for this struct was generated from the following file:
DWARFDebugLine.h