LLVM: llvm::DOTGraphTraits< CallGraph * > Struct Template Reference
LLVM API Documentation
llvm::DOTGraphTraits< CallGraph * > Struct Template Reference
Public Member Functions
DOTGraphTraits (bool isSimple=false)
std::string getNodeLabel (CallGraphNode *Node, CallGraph *Graph)
Public Member Functions inherited from llvm::DefaultDOTGraphTraits
DefaultDOTGraphTraits (bool simple=false)
template<typename GraphType >
std::string getNodeLabel (const void *, const GraphType &)
Static Public Member Functions
static std::string getGraphName (CallGraph *Graph)
Static Public Member Functions inherited from llvm::DefaultDOTGraphTraits
template<typename GraphType >
static std::string getGraphName (const GraphType &)
template<typename GraphType >
static std::string getGraphProperties (const GraphType &)
static bool renderGraphFromBottomUp ()
static bool isNodeHidden (const void *)
template<typename GraphType >
static bool hasNodeAddressLabel (const void *, const GraphType &)
template<typename GraphType >
static std::string getNodeDescription (const void *, const GraphType &)
template<typename GraphType >
static std::string getNodeAttributes (const void *, const GraphType &)
template<typename EdgeIter , typename GraphType >
static std::string getEdgeAttributes (const void *, EdgeIter, const GraphType &)
template<typename EdgeIter >
static std::string getEdgeSourceLabel (const void *, EdgeIter)
template<typename EdgeIter >
static bool edgeTargetsEdgeSource (const void *, EdgeIter)
template<typename EdgeIter >
static EdgeIter getEdgeTarget (const void *, EdgeIter I)
static bool hasEdgeDestLabels ()
static unsigned numEdgeDestLabels (const void *)
static std::string getEdgeDestLabel (const void *, unsigned)
template<typename GraphType , typename GraphWriter >
static void addCustomGraphFeatures (const GraphType &, GraphWriter &)
Additional Inherited Members
Protected Member Functions inherited from llvm::DefaultDOTGraphTraits
bool isSimple ()
Detailed Description
template<>
struct llvm::DOTGraphTraits< CallGraph * >
Definition at line 26 of file CallPrinter.cpp.
Constructor & Destructor Documentation
llvm::DOTGraphTraits< CallGraph * >::DOTGraphTraits (bool isSimple = false) inline
Definition at line 27 of file CallPrinter.cpp.
Member Function Documentation
static std::string llvm::DOTGraphTraits< CallGraph * >::getGraphName (CallGraph * Graph) inline static
Definition at line 29 of file CallPrinter.cpp.
std::string llvm::DOTGraphTraits< CallGraph * >::getNodeLabel (CallGraphNode * Node, CallGraph * Graph) inline
Definition at line 33 of file CallPrinter.cpp.
References llvm::CallGraphNode::getFunction(), llvm::PassRegistry::getPassRegistry(), INITIALIZE_PASS(), llvm::initializeCallGraphPrinterPass(), and llvm::initializeCallGraphViewerPass().
The documentation for this struct was generated from the following file:
CallPrinter.cpp