LLVM: llvm::GraphTraits< Function * > Struct Template Reference
LLVM API Documentation
llvm::GraphTraits< Function * > Struct Template Reference
#include <CFG.h>
Public Types
typedef Function::iterator nodes_iterator
Public Types inherited from llvm::GraphTraits< BasicBlock * >
typedef BasicBlock NodeType
typedef succ_iterator ChildIteratorType
Static Public Member Functions
static NodeType * getEntryNode (Function *F)
static nodes_iterator nodes_begin (Function *F)
static nodes_iterator nodes_end (Function *F)
static size_t size (Function *F)
Static Public Member Functions inherited from llvm::GraphTraits< BasicBlock * >
static NodeType * getEntryNode (BasicBlock *BB)
static ChildIteratorType child_begin (NodeType *N)
static ChildIteratorType child_end (NodeType *N)
Detailed Description
template<>
struct llvm::GraphTraits< Function * >
Definition at line 324 of file Support/CFG.h.
Member Typedef Documentation
typedef Function::iterator llvm::GraphTraits< Function * >::nodes_iterator
Definition at line 328 of file Support/CFG.h.
Member Function Documentation
static NodeType* llvm::GraphTraits< Function * >::getEntryNode (Function * F) inline static
Definition at line 325 of file Support/CFG.h.
References llvm::Function::getEntryBlock().
static nodes_iterator llvm::GraphTraits< Function * >::nodes_begin (Function * F) inline static
Definition at line 329 of file Support/CFG.h.
References llvm::Function::begin().
static nodes_iterator llvm::GraphTraits< Function * >::nodes_end (Function * F) inline static
Definition at line 330 of file Support/CFG.h.
References llvm::Function::end().
static size_t llvm::GraphTraits< Function * >::size (Function * F) inline static
Definition at line 331 of file Support/CFG.h.
References llvm::Function::size().
The documentation for this struct was generated from the following file:
Support/CFG.h