LLVM: llvm::yaml::ScalarTraits< MCModuleYAML::Operand > Struct Template Reference
LLVM API Documentation
llvm::yaml::ScalarTraits< MCModuleYAML::Operand > Struct Template Reference
Static Public Member Functions
static void output (const MCModuleYAML::Operand &, void *, llvm::raw_ostream &)
static StringRef input (StringRef, void *, MCModuleYAML::Operand &)
Detailed Description
template<>
struct llvm::yaml::ScalarTraits< MCModuleYAML::Operand >
Definition at line 161 of file MCModuleYAML.cpp.
Member Function Documentation
StringRef llvm::yaml::ScalarTraits< MCModuleYAML::Operand >::input (StringRef Scalar, void * Ctx, MCModuleYAML::Operand & Val) static
Definition at line 230 of file MCModuleYAML.cpp.
References llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), llvm::StringRef::front(), llvm::StringRef::getAsInteger(), llvm::MCModuleYAML::Operand::MCOp, llvm::StringRef::size(), and llvm::StringRef::substr().
void llvm::yaml::ScalarTraits< MCModuleYAML::Operand >::output (const MCModuleYAML::Operand & Val, void * Ctx, llvm::raw_ostream & Out) static
Definition at line 216 of file MCModuleYAML.cpp.
References llvm::MCOperand::getImm(), llvm::MCOperand::getReg(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm_unreachable, and llvm::MCModuleYAML::Operand::MCOp.
The documentation for this struct was generated from the following file:
MCModuleYAML.cpp