LLVM: MarkPendingLoopPredicate Struct Reference
LLVM API Documentation
MarkPendingLoopPredicate Struct Reference
Public Member Functions
MarkPendingLoopPredicate (Value *C, DenseSet< Value * > &LP)
~MarkPendingLoopPredicate ()
Public Attributes
Value * Cond
DenseSet< Value * > & LoopPreds
bool Pending
Detailed Description
RAII wrapper to prevent recursive application of isImpliedCond. ScalarEvolution's PendingLoopPredicates set must be empty unless we are currently evaluating isImpliedCond.
Definition at line 6156 of file ScalarEvolution.cpp.
Constructor & Destructor Documentation
MarkPendingLoopPredicate::MarkPendingLoopPredicate (Value * C, DenseSet< Value * > & LP) inline
Definition at line 6161 of file ScalarEvolution.cpp.
References llvm::DenseSet< ValueT, ValueInfoT >::insert().
MarkPendingLoopPredicate::~MarkPendingLoopPredicate () inline
Definition at line 6165 of file ScalarEvolution.cpp.
References llvm::APIntOps::And(), llvm::dyn_cast(), llvm::DenseSet< ValueT, ValueInfoT >::erase(), llvm::SCEV::FlagNSW, llvm::SCEV::FlagNUW, llvm::SCEVAddRecExpr::getLoop(), llvm::APInt::getMaxValue(), llvm::APInt::getMinValue(), llvm::SCEVNAryExpr::getNoWrapFlags(), llvm::APInt::getSignedMaxValue(), llvm::APInt::getSignedMinValue(), llvm::SCEVAddRecExpr::getStart(), llvm::SCEVAddRecExpr::getStepRecurrence(), llvm::CmpInst::getSwappedPredicate(), llvm::SCEV::getType(), HasSameValue(), llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::SCEVAddRecExpr::isAffine(), llvm::CmpInst::isFalseWhenEqual(), isLoopInvariant(), llvm::SCEV::isOne(), llvm::CmpInst::isSigned(), llvm::CmpInst::isTrueWhenEqual(), llvm_unreachable, llvm::APIntOps::Or(), Pending, llvm::APInt::sgt(), llvm::APInt::slt(), llvm::APIntOps::smax(), llvm::APIntOps::smin(), std::swap(), llvm::APInt::ugt(), llvm::APInt::ult(), llvm::APIntOps::umax(), and llvm::APIntOps::umin().
Member Data Documentation
Value* MarkPendingLoopPredicate::Cond
Definition at line 6157 of file ScalarEvolution.cpp.
DenseSet<Value*>& MarkPendingLoopPredicate::LoopPreds
Definition at line 6158 of file ScalarEvolution.cpp.
bool MarkPendingLoopPredicate::Pending
Definition at line 6159 of file ScalarEvolution.cpp.
Referenced by ~MarkPendingLoopPredicate().
The documentation for this struct was generated from the following file:
ScalarEvolution.cpp