LLVM: SystemZMCObjectWriter.cpp File Reference
LLVM API Documentation
SystemZMCObjectWriter.cpp File Reference
#include "MCTargetDesc/SystemZMCTargetDesc.h"
#include "MCTargetDesc/SystemZMCFixups.h"
#include "llvm/MC/MCELFObjectWriter.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCValue.h"
Functions
static unsigned getAbsoluteReloc (unsigned Kind)
static unsigned getPCRelReloc (unsigned Kind)
static unsigned getTLSLEReloc (unsigned Kind)
static unsigned getPLTReloc (unsigned Kind)
Function Documentation
static unsigned getAbsoluteReloc (unsigned Kind) static
Definition at line 46 of file SystemZMCObjectWriter.cpp.
References llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm_unreachable, llvm::ELF::R_390_16, llvm::ELF::R_390_32, llvm::ELF::R_390_64, and llvm::ELF::R_390_8.
Referenced by getPLTReloc().
static unsigned getPCRelReloc (unsigned Kind) static
Definition at line 57 of file SystemZMCObjectWriter.cpp.
References llvm::SystemZ::FK_390_PC16DBL, llvm::SystemZ::FK_390_PC32DBL, llvm::SystemZ::FK_390_PLT16DBL, llvm::SystemZ::FK_390_PLT32DBL, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm_unreachable, llvm::ELF::R_390_PC16, llvm::ELF::R_390_PC16DBL, llvm::ELF::R_390_PC32, llvm::ELF::R_390_PC32DBL, llvm::ELF::R_390_PC64, llvm::ELF::R_390_PLT16DBL, and llvm::ELF::R_390_PLT32DBL.
Referenced by getPLTReloc().
static unsigned getPLTReloc (unsigned Kind) static
Definition at line 80 of file SystemZMCObjectWriter.cpp.
References llvm::MCSymbol::AliasedSymbol(), llvm::HexStyle::Asm, F(), llvm::SystemZ::FK_390_PC16DBL, llvm::SystemZ::FK_390_PC32DBL, getAbsoluteReloc(), llvm::MCFixup::getKind(), llvm::MCSymbolRefExpr::getKind(), getPCRelReloc(), llvm::MCValue::getSymA(), llvm::MCSymbolRefExpr::getSymbol(), getTLSLEReloc(), llvm::MCValue::isAbsolute(), llvm_unreachable, llvm::ELF::R_390_GOTENT, llvm::ELF::R_390_PLT16DBL, llvm::ELF::R_390_PLT32DBL, llvm::MCSymbolRefExpr::VK_GOT, llvm::MCSymbolRefExpr::VK_None, llvm::MCSymbolRefExpr::VK_NTPOFF, and llvm::MCSymbolRefExpr::VK_PLT.
static unsigned getTLSLEReloc (unsigned Kind) static
Definition at line 71 of file SystemZMCObjectWriter.cpp.
References llvm::FK_Data_4, llvm::FK_Data_8, llvm_unreachable, llvm::ELF::R_390_TLS_LE32, and llvm::ELF::R_390_TLS_LE64.
Referenced by getPLTReloc().