LLVM: SystemZElimCompare.cpp File Reference
LLVM API Documentation
SystemZElimCompare.cpp File Reference
#include "SystemZTargetMachine.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetRegisterInfo.h"
Macros
#define DEBUG_TYPE "systemz-elim-compare"
Functions
STATISTIC (BranchOnCounts,"Number of branch-on-count instructions")
STATISTIC (EliminatedComparisons,"Number of eliminated comparisons")
STATISTIC (FusedComparisons,"Number of fused compare-and-branch instructions")
static bool isCCLiveOut (MachineBasicBlock *MBB)
static bool resultTests (MachineInstr *MI, unsigned Reg, unsigned SubReg)
static bool isCompareZero (MachineInstr *Compare)
Macro Definition Documentation
#define DEBUG_TYPE "systemz-elim-compare"
Definition at line 16 of file SystemZElimCompare.cpp.
Function Documentation
static bool isCCLiveOut (MachineBasicBlock * MBB) static
Definition at line 100 of file SystemZElimCompare.cpp.
References CC, llvm::MachineBasicBlock::succ_begin(), and llvm::MachineBasicBlock::succ_end().
Referenced by isCompareZero().
static bool isCompareZero (MachineInstr * Compare) static
Definition at line 304 of file SystemZElimCompare.cpp.
References llvm::MachineInstrBuilder::addOperand(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::MCID::Branch, CC, llvm::SystemZ::CCMASK_ICMP, llvm::SmallVectorImpl< T >::clear(), llvm::MCID::Compare, llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), F(), llvm::MachineOperand::getImm(), llvm::TargetMachine::getInstrInfo(), llvm::MachineInstr::getNumExplicitOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::HexagonInstrInfo::getRegisterInfo(), llvm::MachineOperand::getSubReg(), llvm::MachineFunction::getTarget(), llvm::RegState::ImplicitDefine, isCCLiveOut(), llvm::MachineInstr::isCompare(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isReg(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::MachineInstr::removeFromParent(), llvm::MachineInstr::RemoveOperand(), resultTests(), llvm::MachineInstr::setDesc(), llvm::SmallVectorTemplateCommon< T >::size(), and TII.
static bool resultTests (MachineInstr * MI, unsigned Reg, unsigned SubReg) static
Definition at line 110 of file SystemZElimCompare.cpp.
References llvm::MachineInstrBuilder::addReg(), llvm::MCID::Branch, CC, llvm::SystemZ::CCMASK_CMP_EQ, llvm::SystemZ::CCMASK_CMP_NE, llvm::SystemZ::CCMASK_ICMP, llvm::SystemZII::CCMaskFirst, llvm::SystemZII::CCMaskLast, llvm::MCID::Compare, llvm::MachineInstr::findRegisterDefOperandIdx(), llvm::SystemZII::getCCValues(), llvm::SystemZII::getCompareZeroCCMask(), llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getNumExplicitOperands(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineOperand::getSubReg(), I, llvm::RegState::ImplicitDefine, llvm::MachineOperand::isDef(), llvm::SystemZII::IsLogical, llvm::MachineOperand::isReg(), llvm::MachineOperand::isUse(), llvm::MipsISD::LDR, llvm::A64CC::MI, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::MachineInstr::removeFromParent(), llvm::MachineInstr::RemoveOperand(), llvm::MachineInstr::setDesc(), llvm::MachineOperand::setIsDead(), llvm::SmallVectorTemplateCommon< T >::size(), TII, and llvm::MCInstrDesc::TSFlags.
Referenced by isCompareZero().
STATISTIC (BranchOnCounts , "Number of branch-on-count instructions")
STATISTIC (EliminatedComparisons , "Number of eliminated comparisons")
STATISTIC (FusedComparisons , "Number of fused compare-and-branch instructions")