LLVM: SystemZSelectionDAGInfo.cpp File Reference
LLVM API Documentation
SystemZSelectionDAGInfo.cpp File Reference
#include "SystemZTargetMachine.h"
#include "llvm/CodeGen/SelectionDAG.h"
Macros
#define DEBUG_TYPE "systemz-selectiondag-info"
Functions
static SDValue emitMemMem (SelectionDAG &DAG, SDLoc DL, unsigned Sequence, unsigned Loop, SDValue Chain, SDValue Dst, SDValue Src, uint64_t Size)
static SDValue memsetStore (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Dst, uint64_t ByteVal, uint64_t Size, unsigned Align, MachinePointerInfo DstPtrInfo)
static SDValue emitCLC (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Src1, SDValue Src2, uint64_t Size)
static SDValue addIPMSequence (SDLoc DL, SDValue Glue, SelectionDAG &DAG)
static std::pair< SDValue, SDValue > getBoundedStrlen (SelectionDAG &DAG, SDLoc DL, SDValue Chain, SDValue Src, SDValue Limit)
Macro Definition Documentation
#define DEBUG_TYPE "systemz-selectiondag-info"
Definition at line 14 of file SystemZSelectionDAGInfo.cpp.
Function Documentation
static SDValue addIPMSequence (SDLoc DL, SDValue Glue, SelectionDAG & DAG) static
Definition at line 183 of file SystemZSelectionDAGInfo.cpp.
References llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemcmp(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::i32, llvm::SystemZISD::IPM, llvm::SystemZ::IPM_CC, llvm::ISD::ROTL, and llvm::ISD::SRL.
Referenced by llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemcmp(), and llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrcmp().
static SDValue emitCLC (SelectionDAG & DAG, SDLoc DL, SDValue Chain, SDValue Src1, SDValue Src2, uint64_t Size) static
Definition at line 159 of file SystemZSelectionDAGInfo.cpp.
References llvm::SystemZISD::CLC, llvm::SystemZISD::CLC_LOOP, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, and llvm::MVT::Other.
Referenced by llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemcmp().
static SDValue emitMemMem (SelectionDAG & DAG, SDLoc DL, unsigned Sequence, unsigned Loop, SDValue Chain, SDValue Dst, SDValue Src, uint64_t Size) static
Definition at line 33 of file SystemZSelectionDAGInfo.cpp.
References llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemcpy(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValueType(), and llvm::MVT::Other.
Referenced by llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemcpy(), and llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset().
static std::pair<SDValue, SDValue> getBoundedStrlen (SelectionDAG & DAG, SDLoc DL, SDValue Chain, SDValue Src, SDValue Limit) static
Definition at line 266 of file SystemZSelectionDAGInfo.cpp.
References llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrlen(), llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SelectionDAG::getVTList(), llvm::MVT::Glue, llvm::MVT::i32, llvm::MVT::Other, llvm::SystemZISD::SEARCH_STRING, and llvm::ISD::SUB.
Referenced by llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrlen(), and llvm::SystemZSelectionDAGInfo::EmitTargetCodeForStrnlen().
static SDValue memsetStore (SelectionDAG & DAG, SDLoc DL, SDValue Chain, SDValue Dst, uint64_t ByteVal, uint64_t Size, unsigned Align, MachinePointerInfo DstPtrInfo) static
Definition at line 74 of file SystemZSelectionDAGInfo.cpp.
References Align, llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset(), llvm::SelectionDAG::getConstant(), llvm::MVT::getIntegerVT(), llvm::SelectionDAG::getStore(), and I.
Referenced by llvm::SystemZSelectionDAGInfo::EmitTargetCodeForMemset().