LLVM: SystemZISelLowering.cpp File Reference
LLVM API Documentation
SystemZISelLowering.cpp File Reference
#include "SystemZISelLowering.h"
#include "SystemZCallingConv.h"
#include "SystemZConstantPoolValue.h"
#include "SystemZMachineFunctionInfo.h"
#include "SystemZTargetMachine.h"
#include "llvm/CodeGen/CallingConvLower.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include <cctype>
#include "SystemZGenCallingConv.inc"
Macros
#define DEBUG_TYPE "systemz-lower"
#define CONV(X)
#define OPCODE(NAME) case SystemZISD::NAME: return "SystemZISD::" #NAME
Functions
static bool is32Bit (EVT VT)
static MachineOperand earlyUseOperand (MachineOperand Op)
static std::pair< unsigned, const TargetRegisterClass * > parseRegisterNumber (const std::string &Constraint, const TargetRegisterClass *RC, const unsigned *Map)
static SDValue convertLocVTToValVT (SelectionDAG &DAG, SDLoc DL, CCValAssign &VA, SDValue Chain, SDValue Value)
static SDValue convertValVTToLocVT (SelectionDAG &DAG, SDLoc DL, CCValAssign &VA, SDValue Value)
static bool canUseSiblingCall (CCState ArgCCInfo, SmallVectorImpl< CCValAssign > &ArgLocs)
static unsigned CCMaskForCondCode (ISD::CondCode CC)
static IPMConversion getIPMConversion (unsigned CCValid, unsigned CCMask)
static void adjustZeroCmp (SelectionDAG &DAG, bool &IsUnsigned, SDValue &CmpOp0, SDValue &CmpOp1, unsigned &CCMask)
static void adjustSubwordCmp (SelectionDAG &DAG, bool &IsUnsigned, SDValue &CmpOp0, SDValue &CmpOp1, unsigned &CCMask)
static bool isNaturalMemoryOperand (SDValue Op, unsigned ICmpType)
static bool shouldSwapCmpOperands (SDValue Op0, SDValue Op1, unsigned ICmpType)
static bool isSimpleShift (SDValue N, unsigned &ShiftVal)
static unsigned getTestUnderMaskCond (unsigned BitSize, unsigned CCMask, uint64_t Mask, uint64_t CmpVal, unsigned ICmpType)
static void adjustForTestUnderMask (SelectionDAG &DAG, unsigned &Opcode, SDValue &CmpOp0, SDValue &CmpOp1, unsigned &CCValid, unsigned &CCMask, unsigned &ICmpType)
static SDValue emitCmp (const SystemZTargetMachine &TM, SelectionDAG &DAG, SDLoc DL, SDValue CmpOp0, SDValue CmpOp1, ISD::CondCode Cond, unsigned &CCValid, unsigned &CCMask)
static void lowerMUL_LOHI32 (SelectionDAG &DAG, SDLoc DL, unsigned Extend, SDValue Op0, SDValue Op1, SDValue &Hi, SDValue &Lo)
static void lowerGR128Binary (SelectionDAG &DAG, SDLoc DL, EVT VT, unsigned Extend, unsigned Opcode, SDValue Op0, SDValue Op1, SDValue &Even, SDValue &Odd)
static MachineBasicBlock * emitBlockAfter (MachineBasicBlock *MBB)
static MachineBasicBlock * splitBlockAfter (MachineInstr *MI, MachineBasicBlock *MBB)
static MachineBasicBlock * splitBlockBefore (MachineInstr *MI, MachineBasicBlock *MBB)
static unsigned forceReg (MachineInstr *MI, MachineOperand &Base, const SystemZInstrInfo *TII)
Macro Definition Documentation
#define CONV (X)
Value:
case ISD::SET##X: return SystemZ::CCMASK_CMP_##X; \
  case ISD::SETO##X: return SystemZ::CCMASK_CMP_##X; \
  case ISD::SETU##X: return SystemZ::CCMASK_CMP_UO | SystemZ::CCMASK_CMP_##X
Referenced by CCMaskForCondCode().
#define DEBUG_TYPE "systemz-lower"
Definition at line 14 of file SystemZISelLowering.cpp.
#define OPCODE (NAME) case SystemZISD::NAME: return "SystemZISD::" #NAME
Referenced by llvm::SystemZTargetLowering::getTargetNodeName().
Function Documentation
static void adjustForTestUnderMask (SelectionDAG & DAG, unsigned & Opcode, SDValue & CmpOp0, SDValue & CmpOp1, unsigned & CCValid, unsigned & CCMask, unsigned & ICmpType) static
Definition at line 1348 of file SystemZISelLowering.cpp.
References llvm::ISD::AND, llvm::SystemZICMP::Any, llvm::SystemZ::CCMASK_TM, llvm::SystemZ::CCMASK_TM_MIXED_MSB_0, llvm::SystemZ::CCMASK_TM_MIXED_MSB_1, llvm::dyn_cast(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::EVT::getSizeInBits(), getTestUnderMaskCond(), llvm::SDValue::getValueType(), llvm::ConstantSDNode::getZExtValue(), isSimpleShift(), llvm::ISD::SHL, llvm::SystemZICMP::SignedOnly, llvm::ISD::SRL, llvm::SystemZISD::TM, and llvm::SystemZICMP::UnsignedOnly.
Referenced by emitCmp().
static void adjustSubwordCmp (SelectionDAG & DAG, bool & IsUnsigned, SDValue & CmpOp0, SDValue & CmpOp1, unsigned & CCMask) static
Definition at line 1093 of file SystemZISelLowering.cpp.
References llvm::SystemZ::CCMASK_CMP_EQ, llvm::SystemZ::CCMASK_CMP_GE, llvm::SystemZ::CCMASK_CMP_GT, llvm::SystemZ::CCMASK_CMP_LT, llvm::SystemZ::CCMASK_CMP_NE, llvm::ISD::Constant, llvm::MemSDNode::getAlignment(), llvm::LoadSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::SelectionDAG::getConstant(), llvm::LoadSDNode::getExtensionType(), llvm::SelectionDAG::getExtLoad(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getOpcode(), llvm::MemSDNode::getPointerInfo(), llvm::ConstantSDNode::getSExtValue(), llvm::EVT::getStoreSizeInBits(), llvm::SDValue::getValueType(), llvm::ConstantSDNode::getZExtValue(), llvm::SDValue::hasOneUse(), llvm::MVT::i32, llvm::MemSDNode::isNonTemporal(), llvm::MemSDNode::isVolatile(), llvm::SPII::Load, llvm::ISD::LOAD, llvm::ISD::SEXTLOAD, and llvm::ISD::ZEXTLOAD.
Referenced by emitCmp().
static void adjustZeroCmp (SelectionDAG & DAG, bool & IsUnsigned, SDValue & CmpOp0, SDValue & CmpOp1, unsigned & CCMask) static
Definition at line 1071 of file SystemZISelLowering.cpp.
References llvm::SystemZ::CCMASK_CMP_EQ, llvm::SystemZ::CCMASK_CMP_GE, llvm::SystemZ::CCMASK_CMP_GT, llvm::SystemZ::CCMASK_CMP_LE, llvm::SystemZ::CCMASK_CMP_LT, llvm::dyn_cast(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getNode(), llvm::ConstantSDNode::getSExtValue(), and llvm::SDValue::getValueType().
Referenced by emitCmp().
static bool canUseSiblingCall (CCState ArgCCInfo, SmallVectorImpl< CCValAssign > & ArgLocs) static
Definition at line 753 of file SystemZISelLowering.cpp.
References llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocReg(), I, llvm::CCValAssign::Indirect, llvm::CCValAssign::isRegLoc(), and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by llvm::SystemZTargetLowering::LowerCall().
static unsigned CCMaskForCondCode (ISD::CondCode CC) static
Definition at line 978 of file SystemZISelLowering.cpp.
References llvm::SystemZ::CCMASK_CMP_O, llvm::SystemZ::CCMASK_CMP_UO, CONV, EQ, llvm::A64CC::GE, llvm::A64CC::GT, llvm::A64CC::LE, llvm_unreachable, llvm::A64CC::LT, llvm::A64CC::NE, llvm::ISD::SETO, and llvm::ISD::SETUO.
Referenced by emitCmp().
static SDValue convertLocVTToValVT (SelectionDAG & DAG, SDLoc DL, CCValAssign & VA, SDValue Chain, SDValue Value) static
Definition at line 594 of file SystemZISelLowering.cpp.
References llvm::ISD::AssertSext, llvm::ISD::AssertZext, llvm::CCValAssign::Full, llvm::SelectionDAG::getLoad(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getNode(), llvm::SelectionDAG::getValueType(), llvm::CCValAssign::getValVT(), llvm::CCValAssign::Indirect, llvm::CCValAssign::isExtInLoc(), llvm::CCValAssign::SExt, llvm::ISD::TRUNCATE, and llvm::CCValAssign::ZExt.
Referenced by llvm::SystemZTargetLowering::LowerCall(), and llvm::SystemZTargetLowering::LowerFormalArguments().
static SDValue convertValVTToLocVT (SelectionDAG & DAG, SDLoc DL, CCValAssign & VA, SDValue Value) static
Definition at line 619 of file SystemZISelLowering.cpp.
References llvm::CCValAssign::AExt, llvm::ISD::ANY_EXTEND, llvm::CCValAssign::Full, llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocVT(), llvm::SelectionDAG::getNode(), llvm_unreachable, llvm::SystemZTargetLowering::LowerFormalArguments(), llvm::CCValAssign::SExt, llvm::ISD::SIGN_EXTEND, llvm::ISD::ZERO_EXTEND, and llvm::CCValAssign::ZExt.
Referenced by llvm::SystemZTargetLowering::LowerCall(), and llvm::SystemZTargetLowering::LowerReturn().
static MachineOperand earlyUseOperand (MachineOperand Op) static
Definition at line 57 of file SystemZISelLowering.cpp.
References llvm::MachineOperand::isReg(), and llvm::MachineOperand::setIsKill().
Referenced by forceReg().
static MachineBasicBlock* emitBlockAfter (MachineBasicBlock * MBB) static
Definition at line 2236 of file SystemZISelLowering.cpp.
References llvm::MachineFunction::CreateMachineBasicBlock(), llvm::MachineBasicBlock::getBasicBlock(), llvm::MachineBasicBlock::getParent(), llvm::MachineFunction::insert(), and llvm::next().
Referenced by forceReg(), splitBlockAfter(), and splitBlockBefore().
static SDValue emitCmp (const SystemZTargetMachine & TM, SelectionDAG & DAG, SDLoc DL, SDValue CmpOp0, SDValue CmpOp1, ISD::CondCode Cond, unsigned & CCValid, unsigned & CCMask) static
Definition at line 1410 of file SystemZISelLowering.cpp.
References adjustForTestUnderMask(), adjustSubwordCmp(), adjustZeroCmp(), llvm::SystemZICMP::Any, llvm::SystemZ::CCMASK_CMP_EQ, llvm::SystemZ::CCMASK_CMP_GT, llvm::SystemZ::CCMASK_CMP_LT, llvm::SystemZ::CCMASK_CMP_NE, llvm::SystemZ::CCMASK_CMP_UO, llvm::SystemZ::CCMASK_FCMP, llvm::SystemZ::CCMASK_ICMP, CCMaskForCondCode(), llvm::SystemZISD::FCMP, llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::SDValue::getValueType(), llvm::MVT::Glue, llvm::MVT::i32, llvm::SystemZISD::ICMP, llvm::EVT::isFloatingPoint(), shouldSwapCmpOperands(), llvm::SelectionDAG::SignBitIsZero(), llvm::SystemZICMP::SignedOnly, std::swap(), llvm::SystemZISD::TM, and llvm::SystemZICMP::UnsignedOnly.
Referenced by lowerGR128Binary().
static unsigned forceReg (MachineInstr * MI, MachineOperand & Base, const SystemZInstrInfo * TII) static
Definition at line 2265 of file SystemZISelLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineBasicBlock::addLiveIn(), llvm::MachineInstrBuilder::addMBB(), llvm::MachineInstrBuilder::addOperand(), llvm::MachineInstrBuilder::addReg(), llvm::MachineBasicBlock::addSuccessor(), llvm::BuildMI(), CC, llvm::SystemZ::CCMASK_3, llvm::SystemZ::CCMASK_ANY, llvm::SystemZ::CCMASK_CMP_NE, llvm::SystemZ::CCMASK_CS, llvm::SystemZ::CCMASK_CS_NE, llvm::SystemZ::CCMASK_ICMP, llvm::SystemZISD::CLC, llvm::TargetOpcode::COPY, llvm::MachineOperand::CreateReg(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::RegState::Define, earlyUseOperand(), emitBlockAfter(), llvm::SystemZTargetLowering::EmitInstrWithCustomInserter(), llvm::MachineInstr::eraseFromParent(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getImm(), llvm::SystemZTargetMachine::getInstrInfo(), llvm::MachineInstr::getNumExplicitOperands(), llvm::SystemZInstrInfo::getOpcodeForOffset(), llvm::MachineInstr::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineBasicBlock::getParent(), llvm::MachineOperand::getReg(), llvm::MachineFunction::getRegInfo(), llvm::SystemZTargetMachine::getSubtargetImpl(), llvm::SystemZSubtarget::hasLoadStoreOnCond(), llvm::TargetOpcode::IMPLICIT_DEF, llvm::TargetOpcode::INSERT_SUBREG, llvm::MachineOperand::isIdenticalTo(), llvm::MachineOperand::isReg(), llvm::A64CC::MI, MRI, MVC, llvm::SystemZ::PFD_WRITE, llvm::TargetOpcode::PHI, splitBlockAfter(), splitBlockBefore(), and TII.
static IPMConversion getIPMConversion (unsigned CCValid, unsigned CCMask) static
Definition at line 1004 of file SystemZISelLowering.cpp.
References llvm::SystemZ::CCMASK_0, llvm::SystemZ::CCMASK_1, llvm::SystemZ::CCMASK_2, llvm::SystemZ::CCMASK_3, llvm::SystemZ::IPM_CC, and llvm_unreachable.
Referenced by lowerGR128Binary().
static unsigned getTestUnderMaskCond (unsigned BitSize, unsigned CCMask, uint64_t Mask, uint64_t CmpVal, unsigned ICmpType) static
Definition at line 1254 of file SystemZISelLowering.cpp.
References llvm::SystemZ::CCMASK_ANY, llvm::SystemZ::CCMASK_CMP_EQ, llvm::SystemZ::CCMASK_CMP_GE, llvm::SystemZ::CCMASK_CMP_GT, llvm::SystemZ::CCMASK_CMP_LE, llvm::SystemZ::CCMASK_CMP_LT, llvm::SystemZ::CCMASK_CMP_NE, llvm::SystemZ::CCMASK_TM_ALL_0, llvm::SystemZ::CCMASK_TM_ALL_1, llvm::SystemZ::CCMASK_TM_MIXED_MSB_0, llvm::SystemZ::CCMASK_TM_MIXED_MSB_1, llvm::SystemZ::CCMASK_TM_MSB_0, llvm::SystemZ::CCMASK_TM_MSB_1, llvm::SystemZ::CCMASK_TM_SOME_0, llvm::SystemZ::CCMASK_TM_SOME_1, llvm::countLeadingZeros(), llvm::countTrailingZeros(), llvm::SystemZ::isImmHH(), llvm::SystemZ::isImmHL(), llvm::SystemZ::isImmLH(), llvm::SystemZ::isImmLL(), and llvm::SystemZICMP::SignedOnly.
Referenced by adjustForTestUnderMask().
static bool is32Bit (EVT VT) static
Definition at line 44 of file SystemZISelLowering.cpp.
References llvm::EVT::getSimpleVT(), llvm::MVT::i32, llvm::MVT::i64, llvm_unreachable, and llvm::MVT::SimpleTy.
Referenced by lowerGR128Binary(), and X86ChooseCmpImmediateOpcode().
static bool isNaturalMemoryOperand (SDValue Op, unsigned ICmpType) static
Definition at line 1169 of file SystemZISelLowering.cpp.
References llvm::dyn_cast(), llvm::LoadSDNode::getExtensionType(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::MVT::i8, llvm::SPII::Load, llvm::ISD::NON_EXTLOAD, llvm::ISD::SEXTLOAD, llvm::SystemZICMP::SignedOnly, llvm::SystemZICMP::UnsignedOnly, and llvm::ISD::ZEXTLOAD.
Referenced by shouldSwapCmpOperands().
static bool isSimpleShift (SDValue N, unsigned & ShiftVal) static
Definition at line 1235 of file SystemZISelLowering.cpp.
References llvm::dyn_cast(), llvm::SDValue::getOperand(), llvm::EVT::getSizeInBits(), llvm::SDValue::getValueType(), llvm::ConstantSDNode::getZExtValue(), and Shift.
Referenced by adjustForTestUnderMask().
static void lowerGR128Binary (SelectionDAG & DAG, SDLoc DL, EVT VT, unsigned Extend, unsigned Opcode, SDValue Op0, SDValue Op1, SDValue & Even, SDValue & Odd) static
Definition at line 1477 of file SystemZISelLowering.cpp.
References llvm::ISD::ADD, llvm::SystemZISD::ADJDYNALLOC, llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::array_lengthof(), llvm::SystemZISD::ATOMIC_CMP_SWAPW, llvm::SystemZISD::ATOMIC_LOADW_ADD, llvm::SystemZISD::ATOMIC_LOADW_AND, llvm::SystemZISD::ATOMIC_LOADW_NAND, llvm::SystemZISD::ATOMIC_LOADW_SUB, llvm::SystemZISD::ATOMIC_SWAPW, llvm::ISD::BITCAST, llvm::SystemZISD::BR_CCMASK, CC, llvm::tgtok::Code, llvm::SelectionDAG::ComputeMaskedBits(), llvm::SelectionDAG::ComputeNumSignBits(), llvm::ISD::Constant, llvm::SystemZConstantPoolValue::Create(), emitCmp(), llvm::SystemZ::even128(), llvm::SystemZISD::EXTRACT_ACCESS, llvm::MVT::f32, llvm::MVT::f64, llvm::ConstantPoolSDNode::getAlignment(), llvm::AtomicSDNode::getBasePtr(), llvm::BlockAddressSDNode::getBlockAddress(), llvm::MemSDNode::getChain(), llvm::TargetMachine::getCodeModel(), llvm::SelectionDAG::getConstant(), llvm::MachinePointerInfo::getConstantPool(), llvm::SelectionDAG::getConstantPool(), llvm::ConstantPoolSDNode::getConstVal(), llvm::SelectionDAG::getCopyFromReg(), llvm::SelectionDAG::getCopyToReg(), llvm::SelectionDAG::getEntryNode(), llvm::SelectionDAG::getFrameIndex(), llvm::GlobalAddressSDNode::getGlobal(), llvm::MachinePointerInfo::getGOT(), llvm::JumpTableSDNode::getIndex(), llvm::MachineFunction::getInfo(), llvm::SelectionDAG::getIntPtrConstant(), getIPMConversion(), llvm::SelectionDAG::getLoad(), llvm::ConstantPoolSDNode::getMachineCPVal(), llvm::SelectionDAG::getMachineFunction(), llvm::SelectionDAG::getMachineNode(), llvm::SelectionDAG::getMemcpy(), llvm::SelectionDAG::getMemIntrinsicNode(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SelectionDAG::getMergeValues(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::GlobalAddressSDNode::getOffset(), llvm::ConstantPoolSDNode::getOffset(), llvm::BlockAddressSDNode::getOffset(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::TargetLoweringBase::getPointerTy(), llvm::SystemZMachineFunctionInfo::getRegSaveFrameIndex(), llvm::TargetMachine::getRelocationModel(), llvm::TargetLoweringBase::getStackPointerRegisterToSaveRestore(), llvm::SelectionDAG::getStore(), llvm::SelectionDAG::getTargetBlockAddress(), llvm::SelectionDAG::getTargetConstantPool(), llvm::SelectionDAG::getTargetExtractSubreg(), llvm::SelectionDAG::getTargetGlobalAddress(), llvm::SelectionDAG::getTargetInsertSubreg(), llvm::SelectionDAG::getTargetJumpTable(), llvm::TargetMachine::getTLSModel(), llvm::AtomicSDNode::getVal(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::SystemZMachineFunctionInfo::getVarArgsFirstFPR(), llvm::SystemZMachineFunctionInfo::getVarArgsFirstGPR(), llvm::SystemZMachineFunctionInfo::getVarArgsFrameIndex(), llvm::SelectionDAG::getVTList(), llvm::SDNode::getVTList(), llvm::APInt::getZExtValue(), llvm::MVT::Glue, llvm::SystemZSubtarget::hasHighWord(), I, llvm::MVT::i32, llvm::MVT::i64, llvm::TargetOpcode::IMPLICIT_DEF, llvm::tgtok::In, llvm::SystemZISD::IPM, is32Bit(), llvm::isInt< 16 >(), llvm::ConstantPoolSDNode::isMachineConstantPoolEntry(), llvm::SystemZSubtarget::isPC32DBLSymbol(), llvm_unreachable, llvm::TLSModel::LocalExec, lowerMUL_LOHI32(), llvm::SelectionDAG::MaskedValueIsZero(), llvm::SystemZII::MO_GOT, model, llvm::SystemZCP::NTPOFF, llvm::SystemZ::odd128(), llvm::ISD::OR, llvm::MVT::Other, llvm::SystemZISD::PCREL_OFFSET, llvm::SystemZISD::PCREL_WRAPPER, llvm::SystemZ::PFD_READ, llvm::SystemZ::PFD_WRITE, llvm::SystemZISD::PREFETCH, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::NVPTX::PTXCvtMode::RM, llvm::ISD::ROTL, llvm::SystemZISD::SDIVREM32, llvm::SystemZISD::SDIVREM64, llvm::SystemZISD::SELECT_CCMASK, Shift, llvm::ISD::SHL, llvm::ISD::SIGN_EXTEND, llvm::SmallVectorTemplateCommon< T >::size(), llvm::ISD::SRA, llvm::ISD::SRL, llvm::ISD::SUB, llvm::ISD::TokenFactor, llvm::ISD::TRUNCATE, U64, llvm::SystemZISD::UDIVREM32, llvm::SystemZISD::UDIVREM64, llvm::SystemZISD::UMUL_LOHI64, llvm::MVT::Untyped, llvm::ISD::XOR, and llvm::ISD::ZERO_EXTEND.
static void lowerMUL_LOHI32 (SelectionDAG & DAG, SDLoc DL, unsigned Extend, SDValue Op0, SDValue Op1, SDValue & Hi, SDValue & Lo) static
Definition at line 1461 of file SystemZISelLowering.cpp.
References llvm::SelectionDAG::getConstant(), llvm::SelectionDAG::getNode(), llvm::MVT::i32, llvm::MVT::i64, llvm::ISD::MUL, llvm::ISD::SRL, and llvm::ISD::TRUNCATE.
Referenced by lowerGR128Binary().
static std::pair<unsigned, const TargetRegisterClass *> parseRegisterNumber (const std::string & Constraint, const TargetRegisterClass * RC, const unsigned * Map) static
Definition at line 455 of file SystemZISelLowering.cpp.
References llvm::LibFunc::atoi, llvm::SystemZTargetLowering::getRegForInlineAsmConstraint(), and llvm::LibFunc::isdigit.
Referenced by llvm::SystemZTargetLowering::getRegForInlineAsmConstraint().
static bool shouldSwapCmpOperands (SDValue Op0, SDValue Op1, unsigned ICmpType) static
Definition at line 1192 of file SystemZISelLowering.cpp.
References llvm::dyn_cast(), llvm::MVT::f128, llvm::ConstantSDNode::getSExtValue(), llvm::SDValue::getValueType(), llvm::ConstantSDNode::getZExtValue(), llvm::SDValue::hasOneUse(), llvm::isInt< 16 >(), isNaturalMemoryOperand(), llvm::isUInt< 16 >(), llvm::SystemZICMP::SignedOnly, and llvm::SystemZICMP::UnsignedOnly.
Referenced by emitCmp().
static MachineBasicBlock* splitBlockAfter (MachineInstr * MI, MachineBasicBlock * MBB) static
Definition at line 2245 of file SystemZISelLowering.cpp.
References llvm::MachineBasicBlock::begin(), emitBlockAfter(), llvm::MachineBasicBlock::end(), llvm::next(), llvm::MachineBasicBlock::splice(), and llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs().
Referenced by forceReg().
static MachineBasicBlock* splitBlockBefore (MachineInstr * MI, MachineBasicBlock * MBB) static
Definition at line 2256 of file SystemZISelLowering.cpp.
References llvm::MachineBasicBlock::begin(), emitBlockAfter(), llvm::MachineBasicBlock::end(), llvm::A64CC::MI, llvm::MachineBasicBlock::splice(), and llvm::MachineBasicBlock::transferSuccessorsAndUpdatePHIs().
Referenced by forceReg().