LLVM: TailDuplication.cpp File Reference
LLVM API Documentation
TailDuplication.cpp File Reference
#include "llvm/CodeGen/Passes.h"
#include "llvm/ADT/DenseSet.h"
#include "llvm/ADT/OwningPtr.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/MachineSSAUpdater.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetRegisterInfo.h"
Macros
#define DEBUG_TYPE "tailduplication"
Typedefs
typedef std::vector< std::pair< MachineBasicBlock *, unsigned > > AvailableValsTy
Functions
STATISTIC (NumTails,"Number of tails duplicated")
STATISTIC (NumTailDups,"Number of tail duplicated blocks")
STATISTIC (NumInstrDups,"Additional instructions due to tail duplication")
STATISTIC (NumDeadBlocks,"Number of dead blocks removed")
STATISTIC (NumAddedPHIs,"Number of phis added")
INITIALIZE_PASS (TailDuplicatePass,"tailduplication","Tail Duplication", false, false) bool TailDuplicatePass
static void VerifyPHIs (MachineFunction &MF, bool CheckExtra)
static bool isDefLiveOut (unsigned Reg, MachineBasicBlock *BB, const MachineRegisterInfo *MRI)
static unsigned getPHISrcRegOpIdx (MachineInstr *MI, MachineBasicBlock *SrcBB)
static void getRegsUsedByPHIs (const MachineBasicBlock &BB, DenseSet< unsigned > *UsedByPhi)
static bool bothUsedInPHI (const MachineBasicBlock &A, SmallPtrSet< MachineBasicBlock *, 8 > SuccsB)
Variables
static cl::opt< unsigned > TailDuplicateSize ("tail-dup-size", cl::desc("Maximum instructions to consider tail duplicating"), cl::init(2), cl::Hidden)
static cl::opt< bool > TailDupVerify ("tail-dup-verify", cl::desc("Verify sanity of PHI instructions during taildup"), cl::init(false), cl::Hidden)
static cl::opt< unsigned > TailDupLimit ("tail-dup-limit", cl::init(~0U), cl::Hidden)
Macro Definition Documentation
#define DEBUG_TYPE "tailduplication"
Definition at line 15 of file TailDuplication.cpp.
Typedef Documentation
typedef std::vector<std::pair<MachineBasicBlock*,unsigned> > AvailableValsTy
Definition at line 57 of file TailDuplication.cpp.
Function Documentation
static bool bothUsedInPHI (const MachineBasicBlock & A, SmallPtrSet< MachineBasicBlock *, 8 > SuccsB) static
Definition at line 627 of file TailDuplication.cpp.
References llvm::MachineBasicBlock::addLiveIn(), llvm::MachineBasicBlock::addSuccessor(), llvm::HexagonInstrInfo::AnalyzeBranch(), llvm::SetVector< T, Vector, Set >::begin(), llvm::SmallVectorTemplateCommon< T >::begin(), llvm::MachineBasicBlock::begin(), llvm::BuildMI(), llvm::MachineBasicBlock::canFallThrough(), llvm::SmallVectorImpl< T >::clear(), llvm::TargetOpcode::COPY, llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::dbgs(), DEBUG, llvm::SmallVectorBase::empty(), llvm::MachineBasicBlock::empty(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::MachineBasicBlock::end(), llvm::MachineBasicBlock::eraseFromParent(), llvm::MachineInstr::eraseFromParent(), llvm::MachineBasicBlock::getFirstTerminator(), llvm::MachineBasicBlock::getLandingPadSuccessor(), llvm::MachineBasicBlock::getNumber(), llvm::MachineInstr::getParent(), getRegsUsedByPHIs(), llvm::MachineBasicBlock::hasAddressTaken(), i, I, llvm::HexagonInstrInfo::InsertBranch(), llvm::MachineBasicBlock::instr_begin(), llvm::MachineBasicBlock::instr_end(), llvm::MachineInstr::isBundle(), llvm::MachineBasicBlock::isLayoutSuccessor(), llvm::MachineInstr::isPHI(), llvm::MachineBasicBlock::livein_begin(), llvm::MachineBasicBlock::livein_empty(), llvm::MachineBasicBlock::livein_end(), llvm::next(), llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_empty(), llvm::MachineBasicBlock::pred_end(), llvm::MachineBasicBlock::pred_size(), llvm::prior(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::HexagonInstrInfo::RemoveBranch(), llvm::MachineBasicBlock::removeSuccessor(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::MachineBasicBlock::size(), llvm::MachineBasicBlock::splice(), llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_empty(), llvm::MachineBasicBlock::succ_end(), llvm::MachineBasicBlock::succ_size(), TII, and llvm::MachineBasicBlock::transferSuccessors().
static unsigned getPHISrcRegOpIdx (MachineInstr * MI, MachineBasicBlock * SrcBB) static
Definition at line 342 of file TailDuplication.cpp.
References llvm::MachineOperand::getMBB(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), and i.
Referenced by getRegsUsedByPHIs().
static void getRegsUsedByPHIs (const MachineBasicBlock & BB, DenseSet< unsigned > * UsedByPhi) static
Definition at line 353 of file TailDuplication.cpp.
References llvm::MachineBasicBlock::back(), BB, llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::begin(), llvm::MachineBasicBlock::begin(), llvm::MachineBasicBlock::canFallThrough(), llvm::DenseSet< ValueT, ValueInfoT >::count(), llvm::MachineBasicBlock::empty(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::end(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), llvm::SetVector< T, SmallVector< T, N >, SmallSet< T, N > >::end(), llvm::MachineBasicBlock::end(), llvm::MachineInstr::eraseFromParent(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::find(), llvm::Function::getAttributes(), llvm::MachineFunction::getFunction(), llvm::MachineOperand::getMBB(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineBasicBlock::getParent(), getPHISrcRegOpIdx(), llvm::MachineOperand::getReg(), llvm::MCRegisterInfo::getRegClass(), i, I, llvm::DenseSet< ValueT, ValueInfoT >::insert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::insert(), llvm::MachineBasicBlock::insert(), llvm::MachineBasicBlock::instr_end(), llvm::MachineOperand::isDef(), isDefLiveOut(), llvm::MachineInstr::isIndirectBranch(), llvm::MachineInstr::isPHI(), llvm::MachineOperand::isReg(), llvm::MachineBasicBlock::isSuccessor(), llvm::TargetRegisterInfo::isVirtualRegister(), j(), llvm::A64CC::MI, MRI, llvm::Attribute::OptimizeForSize, llvm::MachineBasicBlock::pred_empty(), llvm::MachineInstr::RemoveOperand(), llvm::MachineOperand::setReg(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::size(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::MachineBasicBlock::succ_size(), TailDuplicateSize, and TII.
Referenced by bothUsedInPHI().
INITIALIZE_PASS (TailDuplicatePass , "tailduplication" , "Tail Duplication" , false , false)
Definition at line 127 of file TailDuplication.cpp.
References llvm::HexagonInstrInfo::getRegisterInfo(), MRI, and TII.
static bool isDefLiveOut (unsigned Reg, MachineBasicBlock * BB, const MachineRegisterInfo * MRI) static
Definition at line 329 of file TailDuplication.cpp.
References BB, llvm::MachineInstr::getParent(), llvm::MachineInstr::isDebugValue(), llvm::MachineRegisterInfo::use_begin(), and llvm::MachineRegisterInfo::use_end().
Referenced by getRegsUsedByPHIs().
STATISTIC (NumTails , "Number of tails duplicated")
STATISTIC (NumTailDups , "Number of tail duplicated blocks")
STATISTIC (NumInstrDups , "Additional instructions due to tail duplication")
STATISTIC (NumDeadBlocks , "Number of dead blocks removed")
STATISTIC (NumAddedPHIs , "Number of phis added")
static void VerifyPHIs (MachineFunction & MF, bool CheckExtra) static
Definition at line 147 of file TailDuplication.cpp.
References llvm::MachineSSAUpdater::AddAvailableValue(), llvm::SetVector< T, Vector, Set >::begin(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::dbgs(), DEBUG, llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::MachineInstr::eraseFromParent(), llvm::MachineBasicBlock::getNumber(), llvm::MachineInstr::getOperand(), llvm::MachineRegisterInfo::defusechain_iterator< ReturnUses, ReturnDefs, SkipDebug >::getOperand(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), llvm::MCRegisterInfo::getRegClass(), llvm::MachineBasicBlock::hasAddressTaken(), i, I, llvm::MachineSSAUpdater::Initialize(), llvm::MachineInstr::isCopy(), llvm::MachineInstr::isDebugValue(), llvm::MachineInstr::isPHI(), j(), llvm_unreachable, llvm::A64CC::MI, MRI, llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_empty(), llvm::MachineBasicBlock::pred_end(), llvm::MachineSSAUpdater::RewriteUse(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::size(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::MachineBasicBlock::size(), llvm::MachineBasicBlock::succ_begin(), llvm::MachineBasicBlock::succ_end(), TailDupLimit, and TailDupVerify.
Variable Documentation
cl::opt<unsigned> TailDuplicateSize("tail-dup-size", cl::desc("Maximum instructions to consider tail duplicating"), cl::init(2), cl::Hidden) static
Referenced by getRegsUsedByPHIs().
cl::opt<unsigned> TailDupLimit("tail-dup-limit", cl::init(~0U), cl::Hidden) static
Referenced by VerifyPHIs().
cl::opt<bool> TailDupVerify("tail-dup-verify", cl::desc("Verify sanity of PHI instructions during taildup"), cl::init(false), cl::Hidden) static
Referenced by VerifyPHIs().