LLVM: TailRecursionElimination.cpp File Reference
LLVM API Documentation
TailRecursionElimination.cpp File Reference
#include "llvm/Transforms/Scalar.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/CaptureTracking.h"
#include "llvm/Analysis/InlineCost.h"
#include "llvm/Analysis/InstructionSimplify.h"
#include "llvm/Analysis/Loads.h"
#include "llvm/Analysis/TargetTransformInfo.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include "llvm/Support/CFG.h"
#include "llvm/Support/CallSite.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ValueHandle.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/Local.h"
Macros
#define DEBUG_TYPE "tailcallelim"
Functions
STATISTIC (NumEliminated,"Number of tail calls removed")
STATISTIC (NumRetDuped,"Number of return duplicated")
STATISTIC (NumAccumAdded,"Number of accumulators introduced")
INITIALIZE_PASS_BEGIN (TailCallElim,"tailcallelim","Tail Call Elimination", false, false) INITIALIZE_PASS_END(TailCallElim
static bool CanTRE (AllocaInst *AI)
static bool isDynamicConstant (Value *V, CallInst *CI, ReturnInst *RI)
static Value * getCommonReturnValue (ReturnInst *IgnoreRI, CallInst *CI)
static Instruction * FirstNonDbg (BasicBlock::iterator I)
Variables
tailcallelim
Tail Call Elimination
Tail Call false
Macro Definition Documentation
#define DEBUG_TYPE "tailcallelim"
Definition at line 53 of file TailRecursionElimination.cpp.
Function Documentation
static bool CanTRE (AllocaInst * AI) static
CanTRE - Scan the specified basic block for alloca instructions. If it contains any that are variable-sized or not in the entry block, returns false.
Definition at line 137 of file TailRecursionElimination.cpp.
References BB, llvm::Function::begin(), llvm::Function::callsFunctionThatReturnsTwice(), llvm::SmallVectorBase::empty(), llvm::Function::end(), llvm::Instruction::eraseFromParent(), F(), llvm::AllocaInst::getArraySize(), llvm::Function::getEntryBlock(), llvm::Function::getFunctionType(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), i, I, llvm::isSafeToLoadUnconditionally(), llvm::FunctionType::isVarArg(), LLVM_OVERRIDE, llvm::Instruction::mayHaveSideEffects(), llvm::Instruction::mayWriteToMemory(), llvm::PointerMayBeCaptured(), llvm::Value::replaceAllUsesWith(), llvm::AArch64ISD::Ret, llvm::SimplifyInstruction(), and llvm::SmallVectorTemplateCommon< T >::size().
static Instruction* FirstNonDbg (BasicBlock::iterator I) static
Definition at line 389 of file TailRecursionElimination.cpp.
References llvm::PHINode::addIncoming(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_begin(), llvm::Function::arg_begin(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_end(), llvm::Function::arg_end(), BB, llvm::BasicBlock::begin(), llvm::Function::begin(), llvm::BasicBlock::Create(), llvm::PHINode::Create(), llvm::BranchInst::Create(), llvm::dbgs(), DEBUG, llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::BasicBlock::end(), llvm::Function::end(), llvm::iplist< NodeTy, Traits >::erase(), F(), llvm::FoldReturnIntoUncondBranch(), llvm::BasicBlock::front(), llvm::CallInst::getArgOperand(), llvm::CallInst::getCalledFunction(), getCommonReturnValue(), llvm::Function::getContext(), llvm::Instruction::getDebugLoc(), llvm::Function::getEntryBlock(), llvm::BasicBlock::getInstList(), llvm::Value::getName(), llvm::CallInst::getNumArgOperands(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::ReturnInst::getReturnValue(), llvm::BasicBlock::getTerminator(), llvm::Value::getType(), i, I, isDynamicConstant(), llvm::CallInst::isTailCall(), llvm::next(), P, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::pred_begin(), llvm::pred_end(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::Value::replaceAllUsesWith(), llvm::AArch64ISD::Ret, llvm::Instruction::setDebugLoc(), llvm::Value::setName(), llvm::User::setOperand(), and llvm::Value::takeName().
static Value* getCommonReturnValue (ReturnInst * IgnoreRI, CallInst * CI) static
Definition at line 341 of file TailRecursionElimination.cpp.
References llvm::Function::begin(), llvm::dyn_cast(), llvm::Function::end(), llvm::User::getNumOperands(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::Value::hasOneUse(), llvm::Instruction::isAssociative(), llvm::Instruction::isCommutative(), isDynamicConstant(), and llvm::Instruction::use_back().
Referenced by FirstNonDbg().
INITIALIZE_PASS_BEGIN (TailCallElim , "tailcallelim" , "Tail Call Elimination" , false , false)
static bool isDynamicConstant (Value * V, CallInst * CI, ReturnInst * RI) static
Definition at line 306 of file TailRecursionElimination.cpp.
References llvm::Function::arg_begin(), llvm::CallInst::getArgOperand(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), and llvm::BasicBlock::getUniquePredecessor().
Referenced by FirstNonDbg(), and getCommonReturnValue().
STATISTIC (NumEliminated , "Number of tail calls removed")
STATISTIC (NumRetDuped , "Number of return duplicated")
STATISTIC (NumAccumAdded , "Number of accumulators introduced")
Variable Documentation
Tail Call Elimination
Definition at line 122 of file TailRecursionElimination.cpp.
Tail Call false
Definition at line 122 of file TailRecursionElimination.cpp.
tailcallelim
Definition at line 122 of file TailRecursionElimination.cpp.