LLVM: TargetMachine.cpp File Reference
LLVM API Documentation
TargetMachine.cpp File Reference
#include "llvm/Target/TargetMachine.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalValue.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCCodeGenInfo.h"
#include "llvm/Support/CommandLine.h"
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define RESET_OPTION(X, Y)
Functions
bool llvm::AsmVerbosityDefault (false)
static TLSModel::Model getSelectedTLSModel (const GlobalVariable *Var)
Get the IR-specified TLS model for Var.
Variables
bool llvm::HasDivModLibcall
static cl::opt< bool > DataSections ("fdata-sections", cl::desc("Emit data into separate sections"), cl::init(false))
static cl::opt< bool > FunctionSections ("ffunction-sections", cl::desc("Emit functions into separate sections"), cl::init(false))
Macro Definition Documentation
#define RESET_OPTION (X, Y)
Value:
do {                                                                  \
    if (F->hasFnAttribute(Y))                                           \
      TO.X =                                                            \
        (F->getAttributes().                                            \
           getAttribute(AttributeSet::FunctionIndex,                    \
                        Y).getValueAsString() == "true");               \
  } while (0)
Referenced by llvm::TargetMachine::resetTargetOptions().
Function Documentation
static TLSModel::Model getSelectedTLSModel (const GlobalVariable * Var) static
Get the IR-specified TLS model for Var.
Definition at line 106 of file TargetMachine.cpp.
References llvm::TLSModel::GeneralDynamic, llvm::GlobalVariable::GeneralDynamicTLSModel, llvm::GlobalVariable::getThreadLocalMode(), llvm::TLSModel::InitialExec, llvm::GlobalVariable::InitialExecTLSModel, llvm_unreachable, llvm::TLSModel::LocalDynamic, llvm::GlobalVariable::LocalDynamicTLSModel, llvm::TLSModel::LocalExec, llvm::GlobalVariable::LocalExecTLSModel, and llvm::GlobalVariable::NotThreadLocal.
Referenced by llvm::TargetMachine::getTLSModel().
Variable Documentation
cl::opt<bool> DataSections("fdata-sections", cl::desc("Emit data into separate sections"), cl::init(false)) static
Referenced by llvm::TargetMachine::getDataSections(), and llvm::TargetMachine::setDataSections().
cl::opt<bool> FunctionSections("ffunction-sections", cl::desc("Emit functions into separate sections"), cl::init(false)) static
Referenced by llvm::TargetMachine::getFunctionSections(), and llvm::TargetMachine::setFunctionSections().