LLVM: TargetLoweringObjectFileImpl.cpp File Reference
LLVM API Documentation
TargetLoweringObjectFileImpl.cpp File Reference
#include "llvm/CodeGen/TargetLoweringObjectFileImpl.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/Triple.h"
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Module.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCSectionCOFF.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/Dwarf.h"
#include "llvm/Support/ELF.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/Mangler.h"
#include "llvm/Target/TargetMachine.h"
Functions
static SectionKind getELFKindForNamedSection (StringRef Name, SectionKind K)
static unsigned getELFSectionType (StringRef Name, SectionKind K)
static unsigned getELFSectionFlags (SectionKind K)
static const char * getSectionPrefixForGlobal (SectionKind Kind)
static unsigned getCOFFSectionFlags (SectionKind K)
static const char * getCOFFSectionPrefixForUniqueGlobal (SectionKind Kind)
Function Documentation
static unsigned getCOFFSectionFlags (SectionKind K) static
Definition at line 687 of file TargetLoweringObjectFileImpl.cpp.
References llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), llvm::SectionKind::isBSS(), llvm::SectionKind::isMetadata(), llvm::SectionKind::isReadOnly(), llvm::SectionKind::isText(), llvm::SectionKind::isThreadLocal(), and llvm::SectionKind::isWriteable().
Referenced by llvm::TargetLoweringObjectFileCOFF::getExplicitSectionGlobal(), and llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal().
static const char* getCOFFSectionPrefixForUniqueGlobal (SectionKind Kind) static
Definition at line 740 of file TargetLoweringObjectFileImpl.cpp.
References llvm::SectionKind::isBSS(), llvm::SectionKind::isText(), llvm::SectionKind::isThreadLocal(), llvm::SectionKind::isWriteable(), and llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal().
Referenced by llvm::TargetLoweringObjectFileCOFF::SelectSectionForGlobal().
static SectionKind getELFKindForNamedSection (StringRef Name, SectionKind K) static
Definition at line 121 of file TargetLoweringObjectFileImpl.cpp.
References llvm::StringRef::empty(), llvm::SectionKind::getBSS(), llvm::SectionKind::getThreadBSS(), llvm::SectionKind::getThreadData(), and llvm::StringRef::startswith().
Referenced by llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal().
static unsigned getELFSectionFlags (SectionKind K) static
Definition at line 176 of file TargetLoweringObjectFileImpl.cpp.
References llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), llvm::SectionKind::isMergeableConst16(), llvm::SectionKind::isMergeableConst4(), llvm::SectionKind::isMergeableConst8(), llvm::SectionKind::isMergeableCString(), llvm::SectionKind::isMetadata(), llvm::SectionKind::isText(), llvm::SectionKind::isThreadLocal(), and llvm::SectionKind::isWriteable().
Referenced by llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), and llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal().
static unsigned getELFSectionType (StringRef Name, SectionKind K) static
Definition at line 157 of file TargetLoweringObjectFileImpl.cpp.
References llvm::SectionKind::isBSS(), and llvm::SectionKind::isThreadBSS().
Referenced by llvm::TargetLoweringObjectFileELF::getExplicitSectionGlobal(), and llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal().
static const char* getSectionPrefixForGlobal (SectionKind Kind) static
getSectionPrefixForGlobal - Return the section prefix name used by options FunctionsSections and DataSections.
Definition at line 218 of file TargetLoweringObjectFileImpl.cpp.
References llvm::SectionKind::isBSS(), llvm::SectionKind::isDataNoRel(), llvm::SectionKind::isDataRel(), llvm::SectionKind::isDataRelLocal(), llvm::SectionKind::isReadOnly(), llvm::SectionKind::isReadOnlyWithRel(), llvm::SectionKind::isReadOnlyWithRelLocal(), llvm::SectionKind::isText(), llvm::SectionKind::isThreadBSS(), llvm::SectionKind::isThreadData(), and llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal().
Referenced by llvm::TargetLoweringObjectFileELF::SelectSectionForGlobal().