LLVM: README.txt File Reference
LLVM API Documentation
README.txt File Reference
Functions
To do *Keep the address of the constant pool in a register instead of forming its address all of the time *We can fold small constant offsets into the hi lo references to constant pool addresses as well *When in V9 register allocate icc *[0-3] Add support for isel ing UMUL_LOHI instead of marking it as Expand *Emit the Branch on Integer Register with Prediction instructions It s not clear how to write a pattern for this int o6 subcc l0 bne LBBt1_2!F nop l0 st g0 retl nop should be replaced with a brz in V9 mode *Same as but emit conditional move on register zero (p192) in V9 mode.Testcase
Variables
To do *Keep the address of the constant pool in a register instead of forming its address all of the time *We can fold small constant offsets into the hi lo references to constant pool addresses as well *When in V9 mode
To do *Keep the address of the constant pool in a register instead of forming its address all of the time *We can fold small constant offsets into the hi lo references to constant pool addresses as well *When in V9 register allocate icc *[0-3] Add support for isel ing UMUL_LOHI instead of marking it as Expand *Emit the Branch on Integer Register with Prediction instructions It s not clear how to write a pattern for this though
To do *Keep the address of the constant pool in a register instead of forming its address all of the time *We can fold small constant offsets into the hi lo references to constant pool addresses as well *When in V9 register allocate icc *[0-3] Add support for isel ing UMUL_LOHI instead of marking it as Expand *Emit the Branch on Integer Register with Prediction instructions It s not clear how to write a pattern for this int * p
To do *Keep the address of the constant pool in a register instead of forming its address all of the time *We can fold small constant offsets into the hi lo references to constant pool addresses as well *When in V9 register allocate icc *[0-3] Add support for isel ing UMUL_LOHI instead of marking it as Expand *Emit the Branch on Integer Register with Prediction instructions It s not clear how to write a pattern for this int o6
To do *Keep the address of the constant pool in a register instead of forming its address all of the time *We can fold small constant offsets into the hi lo references to constant pool addresses as well *When in V9 register allocate icc *[0-3] Add support for isel ing UMUL_LOHI instead of marking it as Expand *Emit the Branch on Integer Register with Prediction instructions It s not clear how to write a pattern for this int o6 subcc i0
To do *Keep the address of the constant pool in a register instead of forming its address all of the time *We can fold small constant offsets into the hi lo references to constant pool addresses as well *When in V9 register allocate icc *[0-3] Add support for isel ing UMUL_LOHI instead of marking it as Expand *Emit the Branch on Integer Register with Prediction instructions It s not clear how to write a pattern for this int o6 subcc l0 bne LBBt1_2!F nop LBBt1_1
To do *Keep the address of the constant pool in a register instead of forming its address all of the time *We can fold small constant offsets into the hi lo references to constant pool addresses as well *When in V9 register allocate icc *[0-3] Add support for isel ing UMUL_LOHI instead of marking it as Expand *Emit the Branch on Integer Register with Prediction instructions It s not clear how to write a pattern for this int o6 subcc l0 bne LBBt1_2!F nop l0 st l0
To do *Keep the address of the constant pool in a register instead of forming its address all of the time *We can fold small constant offsets into the hi lo references to constant pool addresses as well *When in V9 register allocate icc *[0-3] Add support for isel ing UMUL_LOHI instead of marking it as Expand *Emit the Branch on Integer Register with Prediction instructions It s not clear how to write a pattern for this int o6 subcc l0 bne LBBt1_2!F nop l0 st LBBt1_2
To do *Keep the address of the constant pool in a register instead of forming its address all of the time *We can fold small constant offsets into the hi lo references to constant pool addresses as well *When in V9 register allocate icc *[0-3] Add support for isel ing UMUL_LOHI instead of marking it as Expand *Emit the Branch on Integer Register with Prediction instructions It s not clear how to write a pattern for this int o6 subcc l0 bne LBBt1_2!F nop l0 st g0
To do *Keep the address of the constant pool in a register instead of forming its address all of the time *We can fold small constant offsets into the hi lo references to constant pool addresses as well *When in V9 register allocate icc *[0-3] Add support for isel ing UMUL_LOHI instead of marking it as Expand *Emit the Branch on Integer Register with Prediction instructions It s not clear how to write a pattern for this int o6 subcc l0 bne LBBt1_2!F nop l0 st g0 retl nop should be replaced with a brz in V9 mode *Same as above
*Emit MULX[SU] DIVX instructions in V9 mode instead of fiddling with the Y register
Function Documentation
To do* Keep the address of the constant pool in a register instead of forming its address all of the time* We can fold small constant offsets into the hi lo references to constant pool addresses as well* When in V9 register allocate icc* [0-3] Add support for isel ing UMUL_LOHI instead of marking it as Expand* Emit the Branch on Integer Register with Prediction instructions It s not clear how to write a pattern for this int o6 subcc l0 bne LBBt1_2 ! F nop l0 st g0 retl nop should be replaced with a brz in V9 mode* Same as but emit conditional move on register zero (p192)
Definition at line 41 of file Target/Sparc/README.txt.
References instructions, mode, of, ret(), and select().
Referenced by llvm::BinaryOperator::CreateFNeg(), llvm::IRBuilder< true, TargetFolder >::CreateGlobalStringPtr(), llvm::BinaryOperator::CreateNeg(), llvm::BinaryOperator::CreateNSWNeg(), llvm::BinaryOperator::CreateNUWNeg(), and foldLogOpOfMaskedICmps().
Variable Documentation
To do* Keep the address of the constant pool in a register instead of forming its address all of the time* We can fold small constant offsets into the hi lo references to constant pool addresses as well* When in V9 register allocate icc* [0-3] Add support for isel ing UMUL_LOHI instead of marking it as Expand* Emit the Branch on Integer Register with Prediction instructions It s not clear how to write a pattern for this int o6 subcc l0 bne LBBt1_2 ! F nop l0 st g0 retl nop should be replaced with a brz in V9 mode* Same as above
Definition at line 14 of file Target/Sparc/README.txt.
Referenced by foo().
To do* Keep the address of the constant pool in a register instead of forming its address all of the time* We can fold small constant offsets into the hi lo references to constant pool addresses as well* When in V9 register allocate icc* [0-3] Add support for isel ing UMUL_LOHI instead of marking it as Expand* Emit the Branch on Integer Register with Prediction instructions It s not clear how to write a pattern for this int o6 subcc l0 bne LBBt1_2 ! F nop l0 st g0
Definition at line 14 of file Target/Sparc/README.txt.
To do* Keep the address of the constant pool in a register instead of forming its address all of the time* We can fold small constant offsets into the hi lo references to constant pool addresses as well* When in V9 register allocate icc* [0-3] Add support for isel ing UMUL_LOHI instead of marking it as Expand* Emit the Branch on Integer Register with Prediction instructions It s not clear how to write a pattern for this int o6 subcc i0
Definition at line 14 of file Target/Sparc/README.txt.
To do* Keep the address of the constant pool in a register instead of forming its address all of the time* We can fold small constant offsets into the hi lo references to constant pool addresses as well* When in V9 register allocate icc* [0-3] Add support for isel ing UMUL_LOHI instead of marking it as Expand* Emit the Branch on Integer Register with Prediction instructions It s not clear how to write a pattern for this int o6 subcc l0 bne LBBt1_2 ! F nop l0 st l0
Definition at line 14 of file Target/Sparc/README.txt.
To do* Keep the address of the constant pool in a register instead of forming its address all of the time* We can fold small constant offsets into the hi lo references to constant pool addresses as well* When in V9 register allocate icc* [0-3] Add support for isel ing UMUL_LOHI instead of marking it as Expand* Emit the Branch on Integer Register with Prediction instructions It s not clear how to write a pattern for this int o6 subcc l0 bne LBBt1_2 ! F nop LBBt1_1
Definition at line 14 of file Target/Sparc/README.txt.
To do* Keep the address of the constant pool in a register instead of forming its address all of the time* We can fold small constant offsets into the hi lo references to constant pool addresses as well* When in V9 register allocate icc* [0-3] Add support for isel ing UMUL_LOHI instead of marking it as Expand* Emit the Branch on Integer Register with Prediction instructions It s not clear how to write a pattern for this int o6 subcc l0 bne LBBt1_2 ! F nop l0 st LBBt1_2
Definition at line 14 of file Target/Sparc/README.txt.
To do* Keep the address of the constant pool in a register instead of forming its address all of the time* We can fold small constant offsets into the hi lo references to constant pool addresses as well* When in V9 mode
Definition at line 9 of file Target/Sparc/README.txt.
Referenced by zero().
To do* Keep the address of the constant pool in a register instead of forming its address all of the time* We can fold small constant offsets into the hi lo references to constant pool addresses as well* When in V9 register allocate icc* [0-3] Add support for isel ing UMUL_LOHI instead of marking it as Expand* Emit the Branch on Integer Register with Prediction instructions It s not clear how to write a pattern for this int o6
Definition at line 14 of file Target/Sparc/README.txt.
To do* Keep the address of the constant pool in a register instead of forming its address all of the time* We can fold small constant offsets into the hi lo references to constant pool addresses as well* When in V9 register allocate icc* [0-3] Add support for isel ing UMUL_LOHI instead of marking it as Expand* Emit the Branch on Integer Register with Prediction instructions It s not clear how to write a pattern for this int* p
Initial value:
{
        %C = seteq int %a, 0
        br bool %C, label %T, label %F
T:
        store int 123, int* %p
        br label %F
F:
        ret float undef
}
codegens to this:
t1:
        save -96
Definition at line 14 of file Target/Sparc/README.txt.
* Emit MULX [SU] DIVX instructions in V9 mode instead of fiddling with the Y register
Definition at line 51 of file Target/Sparc/README.txt.
To do* Keep the address of the constant pool in a register instead of forming its address all of the time* We can fold small constant offsets into the hi lo references to constant pool addresses as well* When in V9 register allocate icc* [0-3] Add support for isel ing UMUL_LOHI instead of marking it as Expand* Emit the Branch on Integer Register with Prediction instructions It s not clear how to write a pattern for this though
Definition at line 9 of file Target/Sparc/README.txt.