LLVM: TGParser.cpp File Reference
LLVM API Documentation
TGParser.cpp File Reference
#include "TGParser.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/TableGen/Record.h"
#include <algorithm>
#include <sstream>
Classes
struct llvm::SubClassReference
struct llvm::SubMultiClassReference
Namespaces
llvm
List of target independent CodeGen pass IDs.
Functions
static bool isObjectStart (tgtok::TokKind K)
isObjectStart - Return true if this is a valid first token for an Object.
static std::string GetNewAnonymousName ()
Function Documentation
static std::string GetNewAnonymousName () static
Definition at line 383 of file TGParser.cpp.
References llvm::BinOpInit::ADD, llvm::Record::addTemplateArg(), llvm::Record::addValue(), llvm::SmallVectorImpl< T >::append(), llvm::SmallVectorTemplateCommon< T >::back(), llvm::tgtok::Bit, llvm::tgtok::Bits, llvm::UnOpInit::CAST, llvm::tgtok::Class, llvm::tgtok::Code, llvm::tgtok::CodeFragment, llvm::tgtok::colon, llvm::tgtok::comma, llvm::BinOpInit::CONCAT, llvm::Init::convertInitializerBitRange(), llvm::Init::convertInitListSlice(), llvm::tgtok::Dag, llvm::tgtok::Def, llvm::tgtok::Defm, llvm::MultiClass::DefPrototypes, llvm::dyn_cast(), llvm::UnOpInit::EMPTY, llvm::SMRange::End, llvm::tgtok::Eof, llvm::BinOpInit::EQ, llvm::tgtok::equal, llvm::lltok::Error, llvm::errs(), llvm::tgtok::Field, llvm::BinOpInit::Fold(), llvm::tgtok::Foreach, llvm::TernOpInit::FOREACH, llvm::BitRecTy::get(), llvm::BitsRecTy::get(), llvm::IntRecTy::get(), llvm::StringRecTy::get(), llvm::ListRecTy::get(), llvm::DagRecTy::get(), llvm::RecordRecTy::get(), llvm::UnsetInit::get(), llvm::BitsInit::get(), llvm::IntInit::get(), llvm::StringInit::get(), llvm::ListInit::get(), llvm::UnOpInit::get(), llvm::BinOpInit::get(), llvm::TernOpInit::get(), llvm::VarInit::get(), llvm::DefInit::get(), llvm::FieldInit::get(), llvm::DagInit::get(), llvm::RecTy::getAsString(), llvm::Init::getAsString(), llvm::Init::getAsUnquotedString(), llvm::ListInit::getElement(), llvm::ListRecTy::getElementType(), llvm::Init::getFieldType(), llvm::Record::getLoc(), llvm::VarInit::getName(), llvm::Record::getName(), llvm::Record::getNameInit(), llvm::Record::getNameInitAsString(), llvm::ListInit::getSize(), llvm::Record::getSuperClasses(), llvm::Record::getTemplateArgs(), llvm::TypedInit::getType(), llvm::RecordVal::getType(), llvm::RecordVal::getValue(), llvm::Record::getValue(), llvm::Record::getValues(), llvm::tgtok::greater, llvm::UnOpInit::HEAD, i, llvm::tgtok::Id, llvm::TernOpInit::IF, llvm::tgtok::In, llvm::tgtok::Int, llvm::tgtok::IntVal, llvm::Init::isComplete(), isObjectStart(), llvm::Record::isTemplateArg(), j(), llvm::tgtok::l_brace, llvm::tgtok::l_paren, llvm::tgtok::l_square, llvm::tgtok::less, llvm::tgtok::Let, llvm::tgtok::List, llvm_unreachable, Loops, llvm::SubMultiClassReference::MC, llvm::tgtok::minus, llvm::tgtok::MultiClass, llvm::TGParser::ParseFile(), llvm::tgtok::paste, llvm::tgtok::period, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::QualifyName(), llvm::tgtok::question, llvm::tgtok::r_brace, llvm::tgtok::r_paren, llvm::tgtok::r_square, llvm::SubClassReference::Rec, llvm::MultiClass::Rec, llvm::SubClassReference::RefRange, llvm::SubMultiClassReference::RefRange, llvm::Record::removeValue(), llvm::Record::resolveReferences(), llvm::Record::resolveReferencesTo(), llvm::resolveTypes(), s, llvm::tgtok::semi, SetValue(), llvm::BinOpInit::SHL, llvm::SmallVectorTemplateCommon< T >::size(), size, llvm::BinOpInit::SRA, llvm::BinOpInit::SRL, llvm::SMRange::Start, llvm::raw_string_ostream::str(), llvm::BinOpInit::STRCONCAT, llvm::tgtok::String, llvm::tgtok::StrVal, llvm::TernOpInit::SUBST, llvm::X86II::TA, llvm::UnOpInit::TAIL, llvm::SubClassReference::TemplateArgs, llvm::SubMultiClassReference::TemplateArgs, Type, llvm::RecTy::typeIsConvertibleTo(), llvm::utostr(), llvm::tgtok::VarName, llvm::tgtok::XADD, llvm::tgtok::XCast, llvm::tgtok::XConcat, llvm::tgtok::XEmpty, llvm::tgtok::XEq, llvm::tgtok::XForEach, llvm::tgtok::XHead, llvm::tgtok::XIf, llvm::tgtok::XSHL, llvm::tgtok::XSRA, llvm::tgtok::XSRL, llvm::tgtok::XStrConcat, llvm::tgtok::XSubst, and llvm::tgtok::XTail.
static bool isObjectStart (tgtok::TokKind K) static
isObjectStart - Return true if this is a valid first token for an Object.
Definition at line 377 of file TGParser.cpp.
References llvm::tgtok::Class, llvm::tgtok::Def, llvm::tgtok::Defm, llvm::tgtok::Foreach, llvm::tgtok::Let, and llvm::tgtok::MultiClass.
Referenced by GetNewAnonymousName().