LLVM: ThreadSanitizer.cpp File Reference
LLVM API Documentation
ThreadSanitizer.cpp File Reference
#include "llvm/Transforms/Instrumentation.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
#include "llvm/Transforms/Utils/ModuleUtils.h"
#include "llvm/Transforms/Utils/SpecialCaseList.h"
Macros
#define DEBUG_TYPE "tsan"
Functions
STATISTIC (NumInstrumentedReads,"Number of instrumented reads")
STATISTIC (NumInstrumentedWrites,"Number of instrumented writes")
STATISTIC (NumOmittedReadsBeforeWrite,"Number of reads ignored due to following writes")
STATISTIC (NumAccessesWithBadSize,"Number of accesses with bad size")
STATISTIC (NumInstrumentedVtableWrites,"Number of vtable ptr writes")
STATISTIC (NumInstrumentedVtableReads,"Number of vtable ptr reads")
STATISTIC (NumOmittedReadsFromConstantGlobals,"Number of reads from constant globals")
STATISTIC (NumOmittedReadsFromVtable,"Number of vtable reads")
INITIALIZE_PASS (ThreadSanitizer,"tsan","ThreadSanitizer: detects data races.", false, false) const char *ThreadSanitizer
static Function * checkInterfaceFunction (Constant *FuncOrBitcast)
static bool isVtableAccess (Instruction *I)
static bool isAtomic (Instruction *I)
static ConstantInt * createOrdering (IRBuilder<> *IRB, AtomicOrdering ord)
static ConstantInt * createFailOrdering (IRBuilder<> *IRB, AtomicOrdering ord)
Variables
static cl::opt< std::string > ClBlacklistFile ("tsan-blacklist", cl::desc("Blacklist file"), cl::Hidden)
static cl::opt< bool > ClInstrumentMemoryAccesses ("tsan-instrument-memory-accesses", cl::init(true), cl::desc("Instrument memory accesses"), cl::Hidden)
static cl::opt< bool > ClInstrumentFuncEntryExit ("tsan-instrument-func-entry-exit", cl::init(true), cl::desc("Instrument function entry and exit"), cl::Hidden)
static cl::opt< bool > ClInstrumentAtomics ("tsan-instrument-atomics", cl::init(true), cl::desc("Instrument atomics"), cl::Hidden)
static cl::opt< bool > ClInstrumentMemIntrinsics ("tsan-instrument-memintrinsics", cl::init(true), cl::desc("Instrument memintrinsics (memset/memcpy/memmove)"), cl::Hidden)
Macro Definition Documentation
#define DEBUG_TYPE "tsan"
Definition at line 22 of file ThreadSanitizer.cpp.
Function Documentation
static Function* checkInterfaceFunction (Constant * FuncOrBitcast) static
Definition at line 136 of file ThreadSanitizer.cpp.
References llvm::AtomicRMWInst::Add, llvm::AtomicRMWInst::And, llvm::appendToGlobalCtors(), llvm::XCoreISD::BL, llvm::SpecialCaseList::createOrDie(), llvm::Value::dump(), F(), llvm::AtomicRMWInst::FIRST_BINOP, llvm::Module::getContext(), llvm::Type::getIntNTy(), llvm::IRBuilderBase::getIntPtrTy(), llvm::Module::getOrInsertFunction(), llvm::Type::getPointerTo(), i, llvm::itostr(), kNumberOfAccessSizes, llvm::AtomicRMWInst::LAST_BINOP, M, llvm::AtomicRMWInst::Nand, llvm::AtomicRMWInst::Or, llvm::report_fatal_error(), llvm::AtomicRMWInst::Sub, llvm::AtomicRMWInst::Xchg, and llvm::AtomicRMWInst::Xor.
static ConstantInt* createFailOrdering (IRBuilder<> * IRB, AtomicOrdering ord) static
Definition at line 443 of file ThreadSanitizer.cpp.
References llvm::Acquire, llvm::AcquireRelease, llvm::countTrailingZeros(), llvm::CallInst::Create(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateCall3(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateIntCast(), createOrdering(), llvm::IRBuilder< preserveNames, T, Inserter >::CreatePointerCast(), llvm::Instruction::eraseFromParent(), llvm::IRBuilderBase::getContext(), llvm::IRBuilderBase::getInt32(), llvm::IRBuilderBase::getInt32Ty(), llvm::IRBuilderBase::getInt8PtrTy(), llvm::Type::getIntNTy(), llvm::Type::getPointerTo(), llvm::Value::getType(), llvm::Type::isSized(), kNumberOfAccessSizes, llvm::Monotonic, llvm::NotAtomic, llvm::Release, llvm::ReplaceInstWithInst(), llvm::SequentiallyConsistent, llvm::SingleThread, and llvm::Unordered.
static ConstantInt* createOrdering (IRBuilder<> * IRB, AtomicOrdering ord) static
Definition at line 428 of file ThreadSanitizer.cpp.
References llvm::Acquire, llvm::AcquireRelease, llvm::IRBuilderBase::getInt32(), llvm::Monotonic, llvm::NotAtomic, llvm::Release, llvm::SequentiallyConsistent, and llvm::Unordered.
Referenced by createFailOrdering().
INITIALIZE_PASS (ThreadSanitizer , "tsan" , "ThreadSanitizer: detects data races." , false , false) const
Definition at line 124 of file ThreadSanitizer.cpp.
References llvm::createThreadSanitizerPass().
static bool isAtomic (Instruction * I) static
Definition at line 308 of file ThreadSanitizer.cpp.
References BB, llvm::BasicBlock::begin(), llvm::Function::begin(), llvm::XCoreISD::BL, ClInstrumentAtomics, ClInstrumentFuncEntryExit, ClInstrumentMemIntrinsics, ClInstrumentMemoryAccesses, llvm::IRBuilder< preserveNames, T, Inserter >::CreateCall(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateCall2(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateIntToPtr(), llvm::IRBuilder< preserveNames, T, Inserter >::CreatePointerCast(), llvm::CrossThread, llvm::dbgs(), DEBUG, llvm::BasicBlock::end(), llvm::Function::end(), F(), llvm::Intrinsic::getDeclaration(), llvm::Function::getEntryBlock(), llvm::BasicBlock::getFirstNonPHI(), llvm::IRBuilderBase::getInt8PtrTy(), llvm::GlobalValue::getParent(), getPointerOperand(), llvm::Value::getType(), llvm::Function::hasFnAttribute(), i, I, isVtableAccess(), n, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::Intrinsic::returnaddress, llvm::Attribute::SanitizeThread, and llvm::SmallVectorTemplateCommon< T >::size().
Referenced by FunctionNumber(), getComparePred(), llvm::LLParser::getContext(), llvm::LoadInst::isSimple(), llvm::StoreInst::isSimple(), llvm::AllocaInst::isStaticAlloca(), llvm::AssemblyWriter::printInstruction(), and WriteInstruction().
static bool isVtableAccess (Instruction * I) static
Definition at line 242 of file ThreadSanitizer.cpp.
References llvm::SmallVectorImpl< T >::clear(), llvm::SmallSet< T, N, C >::count(), llvm::Instruction::getMetadata(), llvm::LoadInst::getPointerOperand(), I, llvm::SmallSet< T, N, C >::insert(), llvm::SPII::Load, llvm::LLVMContext::MD_tbaa, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateCommon< T >::rbegin(), llvm::SmallVectorTemplateCommon< T >::rend(), and llvm::SPII::Store.
Referenced by isAtomic().
STATISTIC (NumInstrumentedReads , "Number of instrumented reads")
STATISTIC (NumInstrumentedWrites , "Number of instrumented writes")
STATISTIC (NumOmittedReadsBeforeWrite , "Number of reads ignored due to following writes")
STATISTIC (NumAccessesWithBadSize , "Number of accesses with bad size")
STATISTIC (NumInstrumentedVtableWrites , "Number of vtable ptr writes")
STATISTIC (NumInstrumentedVtableReads , "Number of vtable ptr reads")
STATISTIC (NumOmittedReadsFromConstantGlobals , "Number of reads from constant globals")
STATISTIC (NumOmittedReadsFromVtable , "Number of vtable reads")
Variable Documentation
cl::opt<std::string> ClBlacklistFile("tsan-blacklist", cl::desc("Blacklist file"), cl::Hidden) static
cl::opt<bool> ClInstrumentAtomics("tsan-instrument-atomics", cl::init(true), cl::desc("Instrument atomics"), cl::Hidden) static
Referenced by isAtomic().
cl::opt<bool> ClInstrumentFuncEntryExit("tsan-instrument-func-entry-exit", cl::init(true), cl::desc("Instrument function entry and exit"), cl::Hidden) static
Referenced by isAtomic().
cl::opt<bool> ClInstrumentMemIntrinsics("tsan-instrument-memintrinsics", cl::init(true), cl::desc("Instrument memintrinsics (memset/memcpy/memmove)"), cl::Hidden) static
Referenced by isAtomic().
cl::opt<bool> ClInstrumentMemoryAccesses("tsan-instrument-memory-accesses", cl::init(true), cl::desc("Instrument memory accesses"), cl::Hidden) static
Referenced by isAtomic().