LLVM: Thumb2ITBlockPass.cpp File Reference
LLVM API Documentation
Thumb2ITBlockPass.cpp File Reference
#include "ARM.h"
#include "ARMMachineFunctionInfo.h"
#include "Thumb2InstrInfo.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineInstrBundle.h"
Macros
#define DEBUG_TYPE "thumb2-it"
Functions
STATISTIC (NumITs,"Number of IT blocks inserted")
STATISTIC (NumMovedInsts,"Number of predicated instructions moved")
static void TrackDefUses (MachineInstr *MI, SmallSet< unsigned, 4 > &Defs, SmallSet< unsigned, 4 > &Uses, const TargetRegisterInfo *TRI)
static bool isCopy (MachineInstr *MI)
Macro Definition Documentation
#define DEBUG_TYPE "thumb2-it"
Definition at line 10 of file Thumb2ITBlockPass.cpp.
Function Documentation
static bool isCopy (MachineInstr * MI) static
Definition at line 92 of file Thumb2ITBlockPass.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::MachineInstr::addOperand(), llvm::ARMCC::AL, llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::BuildMI(), CC, llvm::SmallSet< T, N, C >::clear(), llvm::SmallSet< T, N, C >::count(), llvm::MachineOperand::CreateReg(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::finalizeBundle(), llvm::MachineInstr::findRegisterUseOperand(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getDesc(), llvm::MachineFunction::getInfo(), llvm::TargetMachine::getInstrInfo(), llvm::getITInstrPredicate(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::ARMCC::getOppositeCondition(), llvm::MachineInstr::getParent(), llvm::MachineOperand::getReg(), getReg(), llvm::TargetMachine::getRegisterInfo(), llvm::MachineOperand::getSubReg(), llvm::TargetMachine::getSubtarget(), llvm::MachineFunction::getTarget(), llvm::MachineInstr::hasOptionalDef(), I, llvm::MachineBasicBlock::insert(), llvm::MachineInstr::isBranch(), llvm::MachineInstr::isReturn(), llvm::A64CC::MI, llvm::next(), llvm::MachineBasicBlock::remove(), llvm::MachineOperand::setIsKill(), TII, llvm::SystemZISD::TM, and TrackDefUses().
STATISTIC (NumITs , "Number of IT blocks inserted")
STATISTIC (NumMovedInsts , "Number of predicated instructions moved")
static void TrackDefUses (MachineInstr * MI, SmallSet< unsigned, 4 > & Defs, SmallSet< unsigned, 4 > & Uses, const TargetRegisterInfo * TRI) static
TrackDefUses - Tracking what registers are being defined and used by instructions in the IT block. This also tracks "dependencies", i.e. uses in the IT block that are defined before the IT instruction.
Definition at line 55 of file Thumb2ITBlockPass.cpp.
References llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), i, llvm::SmallSet< T, N, C >::insert(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isUse(), llvm::MCRegisterInfo::DiffListIterator::isValid(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), and llvm::SmallVectorTemplateCommon< T, typename >::size().
Referenced by isCopy().