LLVM: TwoAddressInstructionPass.cpp File Reference
LLVM API Documentation
TwoAddressInstructionPass.cpp File Reference
#include "llvm/CodeGen/Passes.h"
#include "llvm/ADT/BitVector.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallSet.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/CodeGen/LiveIntervalAnalysis.h"
#include "llvm/CodeGen/LiveVariables.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/Function.h"
#include "llvm/MC/MCInstrItineraries.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Target/TargetInstrInfo.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetRegisterInfo.h"
Macros
#define DEBUG_TYPE "twoaddrinstr"
Functions
STATISTIC (NumTwoAddressInstrs,"Number of two-address instructions")
STATISTIC (NumCommuted,"Number of instructions commuted to coalesce")
STATISTIC (NumAggrCommuted,"Number of instructions aggressively commuted")
STATISTIC (NumConvertedTo3Addr,"Number of instructions promoted to 3-address")
STATISTIC (Num3AddrSunk,"Number of 3-address instructions sunk")
STATISTIC (NumReSchedUps,"Number of instructions re-scheduled up")
STATISTIC (NumReSchedDowns,"Number of instructions re-scheduled down")
INITIALIZE_PASS_BEGIN (TwoAddressInstructionPass,"twoaddressinstruction","Two-Address instruction pass", false, false) INITIALIZE_PASS_END(TwoAddressInstructionPass
static bool isPlainlyKilled (MachineInstr *MI, unsigned Reg, LiveIntervals *LIS)
isPLainlyKilled - Test if the given register value, which is used by the
static bool isCopyToReg (MachineInstr &MI, const TargetInstrInfo *TII, unsigned &SrcReg, unsigned &DstReg, bool &IsSrcPhys, bool &IsDstPhys)
static bool isKilled (MachineInstr &MI, unsigned Reg, const MachineRegisterInfo *MRI, const TargetInstrInfo *TII, LiveIntervals *LIS, bool allowFalsePositives)
static bool isTwoAddrUse (MachineInstr &MI, unsigned Reg, unsigned &DstReg)
static MachineInstr * findOnlyInterestingUse (unsigned Reg, MachineBasicBlock *MBB, MachineRegisterInfo *MRI, const TargetInstrInfo *TII, bool &IsCopy, unsigned &DstReg, bool &IsDstPhys)
static unsigned getMappedReg (unsigned Reg, DenseMap< unsigned, unsigned > &RegMap)
static bool regsAreCompatible (unsigned RegA, unsigned RegB, const TargetRegisterInfo *TRI)
Variables
static cl::opt< bool > EnableRescheduling ("twoaddr-reschedule", cl::desc("Coalesce copies by rescheduling (default=true)"), cl::init(true), cl::Hidden)
twoaddressinstruction
Two Address instruction pass
Two Address instruction false
Macro Definition Documentation
#define DEBUG_TYPE "twoaddrinstr"
Definition at line 30 of file TwoAddressInstructionPass.cpp.
Function Documentation
static MachineInstr* findOnlyInterestingUse (unsigned Reg, MachineBasicBlock * MBB, MachineRegisterInfo * MRI, const TargetInstrInfo * TII, bool & IsCopy, unsigned & DstReg, bool & IsDstPhys) static
findOnlyInterestingUse - Given a register, if has a single in-basic block use, return the use instruction if it's a copy or a two-address use.
Definition at line 452 of file TwoAddressInstructionPass.cpp.
References llvm::MachineInstr::getParent(), llvm::MachineRegisterInfo::hasOneNonDBGUse(), isCopyToReg(), llvm::TargetRegisterInfo::isPhysicalRegister(), isTwoAddrUse(), and llvm::MachineRegisterInfo::use_nodbg_begin().
Referenced by regsAreCompatible().
static unsigned getMappedReg (unsigned Reg, DenseMap< unsigned, unsigned > & RegMap) static
getMappedReg - Return the physical register the specified virtual register might be mapped to.
Definition at line 480 of file TwoAddressInstructionPass.cpp.
References llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::end(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::find(), llvm::TargetRegisterInfo::isPhysicalRegister(), and llvm::TargetRegisterInfo::isVirtualRegister().
Referenced by regsAreCompatible().
INITIALIZE_PASS_BEGIN (TwoAddressInstructionPass , "twoaddressinstruction" , "Two-Address instruction pass" , false , false)
static bool isCopyToReg (MachineInstr & MI, const TargetInstrInfo * TII, unsigned & SrcReg, unsigned & DstReg, bool & IsSrcPhys, bool & IsDstPhys) static
isCopyToReg - Return true if the specified MI is a copy instruction or a extract_subreg instruction. It also returns the source and destination registers and whether they are physical registers by reference.
Definition at line 339 of file TwoAddressInstructionPass.cpp.
References llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::MachineInstr::isCopy(), llvm::MachineInstr::isInsertSubreg(), llvm::TargetRegisterInfo::isPhysicalRegister(), and llvm::MachineInstr::isSubregToReg().
Referenced by findOnlyInterestingUse(), isKilled(), and regsAreCompatible().
static bool isKilled (MachineInstr & MI, unsigned Reg, const MachineRegisterInfo * MRI, const TargetInstrInfo * TII, LiveIntervals * LIS, bool allowFalsePositives) static
isKilled - Test if the given register value, which is used by the given instruction, is killed by the given instruction. This looks through coalescable copies to see if the original value is potentially not killed.
For example, in this code:
reg1034 = copy reg1024 reg1035 = copy reg1025<kill> reg1036 = add reg1034<kill>, reg1035<kill>
reg1034 is not considered to be killed, since it is copied from a register which is not killed. Treating it as not killed lets the normal heuristics commute the (two-address) add, which lets coalescing eliminate the extra copy.
If allowFalsePositives is true then likely kills are treated as kills even if it can't be proven that they are kills.
Definition at line 402 of file TwoAddressInstructionPass.cpp.
References llvm::MachineRegisterInfo::def_begin(), llvm::MachineRegisterInfo::def_end(), llvm::MachineRegisterInfo::hasOneUse(), isCopyToReg(), llvm::TargetRegisterInfo::isPhysicalRegister(), isPlainlyKilled(), llvm::A64CC::MI, and llvm::next().
Referenced by regsAreCompatible().
static bool isPlainlyKilled (MachineInstr * MI, unsigned Reg, LiveIntervals * LIS) static
isPLainlyKilled - Test if the given register value, which is used by the
Definition at line 360 of file TwoAddressInstructionPass.cpp.
References llvm::LiveRange::end(), llvm::LiveRange::find(), llvm::LiveIntervals::getInstructionIndex(), llvm::LiveIntervals::getInterval(), llvm::LiveRange::hasAtLeastOneValue(), I, llvm::LiveIntervals::isNotInMIMap(), llvm::SlotIndex::isSameInstr(), llvm::TargetRegisterInfo::isVirtualRegister(), and llvm::MachineInstr::killsRegister().
Referenced by isKilled(), and regsAreCompatible().
static bool isTwoAddrUse (MachineInstr & MI, unsigned Reg, unsigned & DstReg) static
isTwoAddrUse - Return true if the specified MI uses the specified register as a two-address use. If so, return the destination register by reference.
Definition at line 435 of file TwoAddressInstructionPass.cpp.
References llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), i, llvm::MachineOperand::isReg(), llvm::MachineInstr::isRegTiedToDefOperand(), and llvm::MachineOperand::isUse().
Referenced by findOnlyInterestingUse(), and regsAreCompatible().
static bool regsAreCompatible (unsigned RegA, unsigned RegB, const TargetRegisterInfo * TRI) static
regsAreCompatible - Return true if the two registers are equal or aliased.
Definition at line 495 of file TwoAddressInstructionPass.cpp.
References llvm::MachineInstrBuilder::addOperand(), llvm::LiveRange::addSegment(), llvm::LiveVariables::addVirtualRegisterDead(), llvm::LiveVariables::addVirtualRegisterKilled(), llvm::SmallVectorTemplateCommon< T, typename >::back(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::LiveRange::begin(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::BuildMI(), llvm::SmallPtrSetImpl::clear(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::clear(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::clear(), llvm::SmallVectorImpl< T >::clear(), llvm::TargetInstrInfo::commuteInstruction(), llvm::MachineRegisterInfo::constrainRegClass(), llvm::TargetInstrInfo::convertToThreeAddress(), llvm::TargetOpcode::COPY, llvm::SmallSet< T, N, C >::count(), llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::MachineRegisterInfo::createVirtualRegister(), llvm::dbgs(), llvm::X86II::DE, DEBUG, llvm::MachineRegisterInfo::def_begin(), llvm::MachineRegisterInfo::def_end(), llvm::RegState::Define, llvm::SmallVectorBase::empty(), EnableRescheduling, llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::end(), llvm::LiveRange::end(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::SmallSet< T, N, C >::erase(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::erase(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::erase(), llvm::MachineBasicBlock::erase(), llvm::MachineInstr::eraseFromParent(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::find(), llvm::LiveRange::find(), llvm::TargetInstrInfo::findCommutedOpIndices(), llvm::LiveVariables::VarInfo::findKill(), findOnlyInterestingUse(), llvm::MachineInstr::findRegisterUseOperand(), llvm::MCInstrInfo::get(), llvm::TargetRegisterInfo::getAllocatableClass(), llvm::MachineInstr::getDebugLoc(), llvm::MachineInstr::getDesc(), llvm::MachineOperand::getImm(), llvm::TargetMachine::getInstrInfo(), llvm::TargetMachine::getInstrItineraryData(), llvm::TargetInstrInfo::getInstrLatency(), llvm::LiveIntervals::getInstructionFromIndex(), llvm::LiveIntervals::getInstructionIndex(), llvm::LiveIntervals::getInterval(), getMappedReg(), llvm::LiveIntervals::getMBBEndIdx(), llvm::MachineFunction::getName(), llvm::LiveRange::getNextValue(), llvm::MCInstrDesc::getNumDefs(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOpcode(), llvm::TargetInstrInfo::getOpcodeAfterMemoryUnfold(), llvm::MachineInstr::getOperand(), llvm::TargetMachine::getOptLevel(), llvm::MachineInstr::getParent(), llvm::SlotIndex::getPrevSlot(), llvm::MachineOperand::getReg(), llvm::TargetInstrInfo::getRegClass(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), llvm::TargetMachine::getRegisterInfo(), llvm::SlotIndex::getRegSlot(), llvm::MachineOperand::getSubReg(), llvm::MachineFunction::getTarget(), llvm::LiveVariables::getVarInfo(), llvm::LiveIntervals::getVNInfoAllocator(), llvm::LiveIntervals::handleMove(), llvm::MachineInstr::hasUnmodeledSideEffects(), i, I, llvm::TargetOpcode::IMPLICIT_DEF, llvm::SmallSet< T, N, C >::insert(), llvm::DenseMapBase< DerivedT, KeyT, ValueT, KeyInfoT >::insert(), llvm::DenseMapBase< DenseMap< KeyT, ValueT, KeyInfoT >, KeyT, ValueT, KeyInfoT >::insert(), llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::MachineBasicBlock::insert(), llvm::LiveIntervals::InsertMachineInstrInMaps(), llvm::MachineInstr::isBranch(), llvm::MachineInstr::isCall(), llvm::MachineInstr::isCommutable(), llvm::MachineInstr::isConvertibleTo3Addr(), llvm::MachineInstr::isCopy(), llvm::MachineInstr::isCopyLike(), isCopyToReg(), llvm::MachineOperand::isDead(), llvm::MachineInstr::isDebugValue(), llvm::MachineOperand::isDef(), llvm::MachineOperand::isEarlyClobber(), llvm::MachineOperand::isKill(), isKilled(), llvm::TargetRegisterInfo::isPhysicalRegister(), isPlainlyKilled(), llvm::MachineOperand::isReg(), llvm::MachineInstr::isRegTiedToDefOperand(), llvm::MachineInstr::isSafeToMove(), llvm::MachineInstr::isTerminator(), isTwoAddrUse(), llvm::MachineOperand::isUndef(), llvm::MachineOperand::isUse(), llvm::TargetRegisterInfo::isVirtualRegister(), j(), llvm::MachineRegisterInfo::leaveSSA(), llvm_unreachable, llvm::MachineInstr::mayLoad(), llvm::A64CC::MI, llvm::next(), llvm::CodeGenOpt::None, llvm::MachineInstr::operands_begin(), llvm::MachineInstr::operands_end(), llvm::SmallVectorTemplateBase< T, isPodLike >::pop_back(), llvm::prior(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::TargetRegisterInfo::regsOverlap(), llvm::LiveVariables::VarInfo::removeKill(), llvm::MachineInstr::RemoveOperand(), llvm::LiveRange::removeSegment(), llvm::LiveVariables::removeVirtualRegisterDead(), llvm::LiveVariables::removeVirtualRegisterKilled(), llvm::LiveIntervals::repairIntervalsInRange(), llvm::LiveVariables::replaceKillInstruction(), llvm::LiveIntervals::ReplaceMachineInstrInMaps(), llvm::MachineInstr::setDesc(), llvm::MachineOperand::setIsKill(), llvm::MachineOperand::setIsUndef(), llvm::MachineOperand::setReg(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::MachineBasicBlock::splice(), llvm::SystemZISD::TM, llvm::TargetInstrInfo::unfoldMemoryOperand(), and llvm::MachineFunction::verify().
STATISTIC (NumTwoAddressInstrs , "Number of two-address instructions")
STATISTIC (NumCommuted , "Number of instructions commuted to coalesce")
STATISTIC (NumAggrCommuted , "Number of instructions aggressively commuted")
STATISTIC (NumConvertedTo3Addr , "Number of instructions promoted to 3-address")
STATISTIC (Num3AddrSunk , "Number of 3-address instructions sunk")
STATISTIC (NumReSchedUps , "Number of instructions re-scheduled up")
STATISTIC (NumReSchedDowns , "Number of instructions re-scheduled down")
Variable Documentation
cl::opt<bool> EnableRescheduling("twoaddr-reschedule", cl::desc("Coalesce copies by rescheduling (default=true)"), cl::init(true), cl::Hidden) static
Referenced by regsAreCompatible().
Two Address instruction false
Definition at line 167 of file TwoAddressInstructionPass.cpp.
Two Address instruction pass
Definition at line 167 of file TwoAddressInstructionPass.cpp.
Referenced by LLVMTargetMachineEmit(), and llvm::Spiller::~Spiller().
twoaddressinstruction
Definition at line 167 of file TwoAddressInstructionPass.cpp.