LLVM: TypeBasedAliasAnalysis.cpp File Reference
LLVM API Documentation
TypeBasedAliasAnalysis.cpp File Reference
#include "llvm/Analysis/Passes.h"
#include "llvm/Analysis/AliasAnalysis.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
Functions
INITIALIZE_AG_PASS (TypeBasedAliasAnalysis, AliasAnalysis,"tbaa","Type-Based Alias Analysis", false, true, false) ImmutablePass *llvm
static bool isStructPathTBAA (const MDNode *MD)
Variables
static cl::opt< bool > EnableTBAA ("enable-tbaa", cl::init(true))
Function Documentation
INITIALIZE_AG_PASS (TypeBasedAliasAnalysis , AliasAnalysis , "tbaa" , "Type-Based Alias Analysis" , false , true , false)
Definition at line 316 of file TypeBasedAliasAnalysis.cpp.
References llvm::AliasAnalysis::getAnalysisUsage(), and llvm::AnalysisUsage::setPreservesAll().
static bool isStructPathTBAA (const MDNode * MD) static
Check the first operand of the tbaa tag node, if it is a MDNode, we treat it as struct-path aware TBAA format, otherwise, we treat it as scalar TBAA format.
Definition at line 332 of file TypeBasedAliasAnalysis.cpp.
References llvm::ARM_PROC::A, llvm::AliasAnalysis::alias(), B, EnableTBAA, F(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getInstruction(), llvm::Instruction::getMetadata(), llvm::AliasAnalysis::getModRefBehavior(), llvm::AliasAnalysis::getModRefInfo(), llvm::MDNode::getNumOperands(), llvm::MDNode::getOperand(), M, llvm::LLVMContext::MD_tbaa, ModRefBehavior, llvm::AliasAnalysis::pointsToConstantMemory(), and T.
Referenced by llvm::MDNode::getMostGenericTBAA(), and llvm::MDNode::isTBAAVtableAccess().
Variable Documentation
cl::opt<bool> EnableTBAA("enable-tbaa", cl::init(true)) static
Referenced by isStructPathTBAA().