LLVM: UnreachableBlockElim.cpp File Reference
LLVM API Documentation
UnreachableBlockElim.cpp File Reference
#include "llvm/CodeGen/Passes.h"
#include "llvm/ADT/DepthFirstIterator.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/Analysis/Dominators.h"
#include "llvm/CodeGen/MachineDominators.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineLoopInfo.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Function.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Type.h"
#include "llvm/Pass.h"
#include "llvm/Support/CFG.h"
#include "llvm/Target/TargetInstrInfo.h"
Functions
INITIALIZE_PASS (UnreachableBlockElim,"unreachableblockelim","Remove unreachable blocks from the CFG", false, false) FunctionPass *llvm
Function Documentation
INITIALIZE_PASS (UnreachableBlockElim , "unreachableblockelim" , "Remove unreachable blocks from the CFG" , false , false)
Definition at line 56 of file UnreachableBlockElim.cpp.
References llvm::AnalysisUsage::addPreserved(), BB, llvm::BasicBlock::begin(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::Function::begin(), llvm::MachineRegisterInfo::constrainRegClass(), llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::df_ext_begin(), llvm::df_ext_end(), llvm::BasicBlock::dropAllReferences(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::Function::end(), llvm::MachineInstr::eraseFromParent(), F(), llvm::MachineFunctionPass::getAnalysisUsage(), llvm::BasicBlock::getInstList(), llvm::Constant::getNullValue(), llvm::MachineRegisterInfo::getRegClass(), llvm::MachineFunction::getRegInfo(), i, I, MRI, llvm::iplist< NodeTy, Traits >::pop_front(), llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_end(), preds, llvm::MachineBasicBlock::removeSuccessor(), llvm::MachineFunction::RenumberBlocks(), llvm::MachineRegisterInfo::replaceRegWith(), llvm::succ_begin(), llvm::MachineBasicBlock::succ_begin(), llvm::succ_end(), llvm::MachineBasicBlock::succ_end(), and llvm::UnreachableMachineBlockElimID.