LLVM: Value.cpp File Reference
LLVM API Documentation
Value.cpp File Reference
#include "llvm/IR/Value.h"
#include "LLVMContextImpl.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/IR/Constant.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/InstrTypes.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/Operator.h"
#include "llvm/IR/ValueSymbolTable.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/GetElementPtrTypeIterator.h"
#include "llvm/Support/LeakDetector.h"
#include "llvm/Support/ManagedStatic.h"
#include "llvm/Support/ValueHandle.h"
#include <algorithm>
Enumerations
enum PointerStripKind
Functions
static Type * checkType (Type *Ty)
static bool getSymTab (Value *V, ValueSymbolTable *&ST)
static bool isDereferenceablePointer (const Value *V, SmallPtrSet< const Value *, 32 > &Visited)
Enumeration Type Documentation
enum PointerStripKind
Definition at line 333 of file Value.cpp.
Function Documentation
static Type* checkType (Type * Ty) inline static
Definition at line 39 of file Value.cpp.
Referenced by llvm::createAMDGPUISelDag().
static bool getSymTab (Value * V, ValueSymbolTable *& ST) static
Definition at line 143 of file Value.cpp.
References llvm::ARM_PROC::A, BB, I, and P.
Referenced by llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::addNodeToList(), llvm::ilist_traits< BasicBlock >::noteHead(), llvm::ilist_traits< Argument >::noteHead(), llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::removeNodeFromList(), llvm::Value::setName(), llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::setSymTabObject(), llvm::Value::takeName(), and llvm::SymbolTableListTraits< ValueSubClass, ItemParentClass >::transferNodesFromList().
static bool isDereferenceablePointer (const Value * V, SmallPtrSet< const Value *, 32 > & Visited) static
isDereferenceablePointer - Test if this value is always a pointer to allocated and suitably aligned memory for a simple load or store.
Definition at line 439 of file Value.cpp.
References llvm::ARM_PROC::A, llvm::dyn_cast(), llvm::gep_type_begin(), llvm::APInt::getActiveBits(), llvm::ArrayType::getNumElements(), llvm::ConstantInt::getValue(), llvm::ConstantInt::getZExtValue(), I, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::Value::isDereferenceablePointer(), and llvm::ConstantInt::isZero().
Referenced by llvm::Value::isDereferenceablePointer().