LLVM: ValueEnumerator.cpp File Reference
LLVM API Documentation
ValueEnumerator.cpp File Reference
#include "ValueEnumerator.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Module.h"
#include "llvm/IR/ValueSymbolTable.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
Functions
static bool isIntOrIntVectorValue (const std::pair< const Value *, unsigned > &V)
static void IncorporateFunctionInfoGlobalBBIDs (const Function *F, DenseMap< const BasicBlock *, unsigned > &IDMap)
Function Documentation
static void IncorporateFunctionInfoGlobalBBIDs (const Function * F, DenseMap< const BasicBlock *, unsigned > & IDMap) static
Definition at line 527 of file ValueEnumerator.cpp.
References BB, llvm::Function::begin(), and llvm::Function::end().
Referenced by llvm::ValueEnumerator::getGlobalBasicBlockID().
static bool isIntOrIntVectorValue (const std::pair< const Value *, unsigned > & V) static
Definition at line 27 of file ValueEnumerator.cpp.
Referenced by llvm::ValueEnumerator::print().