LLVM: Verifier.cpp File Reference
LLVM API Documentation
Verifier.cpp File Reference
#include "llvm/Analysis/Verifier.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SetVector.h"
#include "llvm/ADT/SmallPtrSet.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/Analysis/Dominators.h"
#include "llvm/Assembly/Writer.h"
#include "llvm/DebugInfo.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/InlineAsm.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/IR/Metadata.h"
#include "llvm/IR/Module.h"
#include "llvm/InstVisitor.h"
#include "llvm/Pass.h"
#include "llvm/PassManager.h"
#include "llvm/Support/CFG.h"
#include "llvm/Support/CallSite.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ConstantRange.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include <algorithm>
#include <cstdarg>
Macros
#define Assert(C, M) do { if (!(C)) { CheckFailed(M); return; } } while (0)
#define Assert1(C, M, V1) do { if (!(C)) { CheckFailed(M, V1); return; } } while (0)
#define Assert2(C, M, V1, V2) do { if (!(C)) { CheckFailed(M, V1, V2); return; } } while (0)
#define Assert3(C, M, V1, V2, V3) do { if (!(C)) { CheckFailed(M, V1, V2, V3); return; } } while (0)
#define Assert4(C, M, V1, V2, V3, V4) do { if (!(C)) { CheckFailed(M, V1, V2, V3, V4); return; } } while (0)
Functions
INITIALIZE_PASS (PreVerifier,"preverify","Preliminary module verification", false, false) static char &PreVerifyID
static bool isContiguous (const ConstantRange &A, const ConstantRange &B)
Variables
static cl::opt< bool > DisableDebugInfoVerifier ("disable-debug-info-verifier", cl::init(true))
Macro Definition Documentation
#define Assert (C, M) do { if (!(C)) { CheckFailed(M); return; } } while (0)
Definition at line 403 of file Verifier.cpp.
#define Assert1 (C, M, V1) do { if (!(C)) { CheckFailed(M, V1); return; } } while (0)
Definition at line 405 of file Verifier.cpp.
Referenced by isContiguous().
#define Assert2 (C, M, V1, V2) do { if (!(C)) { CheckFailed(M, V1, V2); return; } } while (0)
Definition at line 407 of file Verifier.cpp.
Referenced by isContiguous().
#define Assert3 (C, M, V1, V2, V3) do { if (!(C)) { CheckFailed(M, V1, V2, V3); return; } } while (0)
Definition at line 409 of file Verifier.cpp.
#define Assert4 (C, M, V1, V2, V3, V4) do { if (!(C)) { CheckFailed(M, V1, V2, V3, V4); return; } } while (0)
Definition at line 411 of file Verifier.cpp.
Function Documentation
INITIALIZE_PASS (PreVerifier , "preverify" , "Preliminary module verification" , false , false)
static bool isContiguous (const ConstantRange & A, const ConstantRange & B) static
Definition at line 1757 of file Verifier.cpp.
References llvm::Acquire, llvm::AcquireRelease, Assert1, Assert2, BB, llvm::DebugInfoFinder::compile_unit_begin(), llvm::DebugInfoFinder::compile_unit_end(), llvm::SmallPtrSet< PtrType, SmallSize >::count(), llvm::CrossThread, llvm::Intrinsic::ctlz, llvm::Intrinsic::cttz, llvm::Intrinsic::dbg_declare, llvm::Intrinsic::dbg_value, DisableDebugInfoVerifier, llvm::DominatorTree::dominates(), llvm::Intrinsic::donothing, llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::ArrayRef< T >::empty(), llvm::AtomicRMWInst::FIRST_BINOP, llvm::NVPTX::PTXLdStInstCode::Float, llvm::ArrayRef< T >::front(), llvm::Intrinsic::gcread, llvm::Intrinsic::gcroot, llvm::Intrinsic::gcwrite, llvm::PointerType::getAddressSpace(), llvm::ExtractValueInst::getAggregateOperand(), llvm::InsertValueInst::getAggregateOperand(), llvm::LoadInst::getAlignment(), llvm::StoreInst::getAlignment(), llvm::CallInst::getArgOperand(), llvm::AllocaInst::getArraySize(), llvm::CallInst::getCalledFunction(), llvm::LandingPadInst::getClause(), llvm::StructType::getElementType(), llvm::SequentialType::getElementType(), llvm::VectorType::getExtendedElementVectorType(), llvm::Function::getFunctionType(), llvm::ExtractValueInst::getIndexedType(), llvm::ExtractValueInst::getIndices(), llvm::InsertValueInst::getIndices(), llvm::Function::getIntrinsicID(), llvm::Intrinsic::getIntrinsicInfoTableEntries(), llvm::BasicBlock::getLandingPadInst(), llvm::ConstantRange::getLower(), llvm::Instruction::getMetadata(), llvm::Intrinsic::getName(), llvm::Value::getName(), llvm::InvokeInst::getNormalDest(), llvm::CallInst::getNumArgOperands(), llvm::LandingPadInst::getNumClauses(), llvm::StructType::getNumElements(), llvm::VectorType::getNumElements(), llvm::User::getNumOperands(), llvm::MDNode::getNumOperands(), llvm::User::getOperand(), llvm::MDNode::getOperand(), llvm::User::getOperandUse(), llvm::AtomicRMWInst::getOperation(), llvm::LoadInst::getOrdering(), llvm::StoreInst::getOrdering(), llvm::FenceInst::getOrdering(), llvm::AtomicCmpXchgInst::getOrdering(), llvm::AtomicRMWInst::getOrdering(), llvm::Instruction::getParent(), llvm::BasicBlock::getParent(), llvm::GlobalValue::getParent(), llvm::LandingPadInst::getPersonalityFn(), llvm::Type::getPrimitiveSizeInBits(), llvm::LoadInst::getSynchScope(), llvm::StoreInst::getSynchScope(), llvm::VectorType::getTruncatedElementVectorType(), llvm::AllocaInst::getType(), llvm::Value::getType(), llvm::ConstantInt::getType(), llvm::InvokeInst::getUnwindDest(), llvm::ConstantRange::getUpper(), llvm::ConstantInt::getValue(), llvm::DebugInfoFinder::global_variable_begin(), llvm::DebugInfoFinder::global_variable_end(), llvm::Function::hasGC(), llvm::Value::hasName(), i, I, llvm::Intrinsic::init_trampoline, llvm::SmallPtrSet< PtrType, SmallSize >::insert(), llvm::ConstantRange::intersectWith(), llvm::Intrinsic::invariant_end, llvm::Intrinsic::invariant_start, llvm::LoadInst::isAtomic(), llvm::StoreInst::isAtomic(), llvm::LandingPadInst::isCatch(), llvm::LandingPadInst::isCleanup(), llvm::GlobalValue::isDeclaration(), llvm::Type::isDoubleTy(), llvm::ConstantRange::isEmptySet(), llvm::LandingPadInst::isFilter(), llvm::APFloat::isFiniteNonZero(), llvm::Type::isFirstClassType(), llvm::Type::isFloatTy(), llvm::Type::isFPOrFPVectorTy(), llvm::ConstantRange::isFullSet(), llvm::Type::isHalfTy(), llvm::Type::isIntegerTy(), llvm::Type::isIntOrIntVectorTy(), llvm::Function::isIntrinsic(), llvm::Type::isMetadataTy(), llvm::APFloat::isNegative(), llvm::Type::isPointerTy(), llvm::Type::isPtrOrPtrVectorTy(), llvm::DominatorTree::isReachableFromEntry(), llvm::Type::isSized(), llvm::FunctionType::isVarArg(), llvm::Type::isVoidTy(), llvm::Type::isX86_MMXTy(), llvm::AtomicRMWInst::LAST_BINOP, llvm::Intrinsic::lifetime_end, llvm::Intrinsic::lifetime_start, llvm_unreachable, llvm::LLVMContext::MD_dbg, llvm::LLVMContext::MD_fpmath, llvm::LLVMContext::MD_range, llvm::Intrinsic::memcpy, llvm::Intrinsic::memmove, llvm::Intrinsic::memset, N, llvm::NotAtomic, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::pred_begin(), llvm::pred_end(), llvm::Intrinsic::prefetch, llvm::DebugInfoFinder::processDeclare(), llvm::DebugInfoFinder::processLocation(), llvm::DebugInfoFinder::processValue(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::Release, llvm::DebugInfoFinder::scope_begin(), llvm::DebugInfoFinder::scope_end(), llvm::SequentiallyConsistent, llvm::APInt::sgt(), llvm::ArrayRef< T >::size(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::ArrayRef< T >::slice(), llvm::A64DB::ST, llvm::Intrinsic::stackprotector, llvm::Value::stripPointerCasts(), llvm::DebugInfoFinder::subprogram_begin(), llvm::DebugInfoFinder::subprogram_end(), llvm::DebugInfoFinder::type_begin(), llvm::DebugInfoFinder::type_end(), llvm::Unordered, llvm::Value::use_begin(), llvm::Value::use_end(), llvm::DIDescriptor::Verify(), llvm::DIType::Verify(), llvm::DICompileUnit::Verify(), llvm::DISubprogram::Verify(), and llvm::DIGlobalVariable::Verify().
Variable Documentation
cl::opt<bool> DisableDebugInfoVerifier("disable-debug-info-verifier", cl::init(true)) static
Referenced by isContiguous().