LLVM: WinCOFFObjectWriter.cpp File Reference
LLVM API Documentation
WinCOFFObjectWriter.cpp File Reference
#include "llvm/MC/MCWinCOFFObjectWriter.h"
#include "llvm/ADT/DenseMap.h"
#include "llvm/ADT/OwningPtr.h"
#include "llvm/ADT/StringMap.h"
#include "llvm/ADT/StringRef.h"
#include "llvm/ADT/Twine.h"
#include "llvm/MC/MCAsmLayout.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSection.h"
#include "llvm/MC/MCSectionCOFF.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCValue.h"
#include "llvm/Support/COFF.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/TimeValue.h"
#include <cstdio>
Namespaces
llvm
List of target independent CodeGen pass IDs.
Macros
#define DEBUG_TYPE "WinCOFFObjectWriter"
Enumerations
enum AuxiliaryType
Functions
static void write_uint32_le (void *Data, uint32_t const &Value)
MCObjectWriter * llvm::createWinCOFFObjectWriter (MCWinCOFFObjectTargetWriter *MOTW, raw_ostream &OS)
Construct a new Win COFF writer instance.
Macro Definition Documentation
#define DEBUG_TYPE "WinCOFFObjectWriter"
Definition at line 14 of file WinCOFFObjectWriter.cpp.
Enumeration Type Documentation
enum AuxiliaryType
Definition at line 42 of file WinCOFFObjectWriter.cpp.
Function Documentation
static void write_uint32_le (void * Data, uint32_t const & Value) inline static
Definition at line 184 of file WinCOFFObjectWriter.cpp.
References llvm::ARM_PROC::A, llvm::MCSymbol::AliasedSymbol(), llvm::HexStyle::Asm, b, B, llvm::StringRef::begin(), llvm::SmallVectorTemplateCommon< T, typename >::begin(), llvm::MCAssembler::begin(), llvm::COFF::header::Characteristics, Characteristics, llvm::COFF::section::Characteristics, llvm::dyn_cast(), llvm::StringRef::end(), llvm::SmallVectorTemplateCommon< T, typename >::end(), llvm::MCAssembler::end(), llvm::MCSymbolData::Fragment, llvm::MCSectionData::getAlignment(), llvm::MCSectionCOFF::getAssocSection(), llvm::MCValue::getConstant(), llvm::MCSymbolData::getFlags(), llvm::MCAsmLayout::getFragmentOffset(), llvm::MCSymbol::getName(), llvm::MCFixup::getOffset(), llvm::MCFragment::getParent(), llvm::MCSymbol::getSection(), llvm::MCSectionData::getSection(), llvm::MCAsmLayout::getSectionAddressSize(), llvm::MCSectionCOFF::getSectionName(), llvm::MCValue::getSymA(), llvm::MCValue::getSymB(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCSymbolData::getSymbol(), llvm::MCAssembler::getSymbolData(), llvm::MCAsmLayout::getSymbolOffset(), llvm::MCSymbol::getVariableValue(), llvm::MCSection::getVariant(), llvm::COFF::HeaderSize, i, I, if(), llvm::COFF::IMAGE_COMDAT_SELECT_ASSOCIATIVE, llvm::COFF::IMAGE_REL_AMD64_REL32, llvm::COFF::IMAGE_REL_I386_REL32, llvm::COFF::IMAGE_SYM_ABSOLUTE, llvm::COFF::IMAGE_SYM_CLASS_EXTERNAL, llvm::COFF::IMAGE_SYM_CLASS_STATIC, llvm::COFF::IMAGE_SYM_CLASS_WEAK_EXTERNAL, llvm::COFF::IMAGE_WEAK_EXTERN_SEARCH_LIBRARY, llvm::MCSymbol::isAbsolute(), llvm::MCSymbolData::isExternal(), llvm::MCSymbol::isVariable(), j(), llvm::tgtok::List, llvm_unreachable, llvm::COFF::header::Machine, llvm::Intrinsic::memcpy, llvm::Intrinsic::memset, llvm::COFF::section::Name, llvm::COFF::NameSize, llvm::sys::TimeValue::now(), llvm::COFF::section::NumberOfLineNumbers, llvm::COFF::section::NumberOfRelocations, llvm::COFF::header::NumberOfSections, llvm::COFF::header::NumberOfSymbols, llvm::MCSymbolData::Offset, llvm::COFF::section::PointerToLineNumbers, llvm::COFF::section::PointerToRawData, llvm::COFF::section::PointerToRelocations, llvm::COFF::header::PointerToSymbolTable, llvm::COFF::RelocationSize, llvm::report_fatal_error(), S, llvm::ARMBuildAttrs::Section, llvm::COFF::SectionSize, llvm::COFF::SF_WeakExternal, size, llvm::COFF::header::SizeOfOptionalHeader, llvm::COFF::section::SizeOfRawData, llvm::LibFunc::sprintf, llvm::StringRef::str(), llvm::tgtok::String, llvm::MCSection::SV_COFF, llvm::ARMBuildAttrs::Symbol, llvm::MCAssembler::symbol_begin(), llvm::MCAssembler::symbol_end(), llvm::COFF::SymbolSize, llvm::COFF::relocation::SymbolTableIndex, llvm::raw_ostream::tell(), llvm::COFF::header::TimeDateStamp, llvm::sys::TimeValue::toEpochTime(), llvm::COFF::relocation::Type, llvm::COFF::section::VirtualAddress, llvm::COFF::relocation::VirtualAddress, llvm::COFF::section::VirtualSize, llvm::raw_ostream::write(), and llvm::MCAssembler::writeSectionData().