LLVM: X86AsmBackend.cpp File Reference
LLVM API Documentation
X86AsmBackend.cpp File Reference
#include "MCTargetDesc/X86BaseInfo.h"
#include "MCTargetDesc/X86FixupKinds.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/MC/MCAsmBackend.h"
#include "llvm/MC/MCAssembler.h"
#include "llvm/MC/MCELFObjectWriter.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCFixupKindInfo.h"
#include "llvm/MC/MCMachObjectWriter.h"
#include "llvm/MC/MCObjectWriter.h"
#include "llvm/MC/MCSectionCOFF.h"
#include "llvm/MC/MCSectionELF.h"
#include "llvm/MC/MCSectionMachO.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/ELF.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MachO.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
Namespaces
CU
Enumerations
enum CompactUnwindEncodings
Compact unwind encoding values.
Functions
static unsigned getFixupKindLog2Size (unsigned Kind)
static unsigned getRelaxedOpcodeBranch (unsigned Op)
static unsigned getRelaxedOpcodeArith (unsigned Op)
static unsigned getRelaxedOpcode (unsigned Op)
Variables
static cl::opt< bool > MCDisableArithRelaxation ("mc-x86-disable-arith-relaxation", cl::desc("Disable relaxation of arithmetic instruction for X86"))
Enumeration Type Documentation
enum CompactUnwindEncodings
Compact unwind encoding values.
Definition at line 397 of file X86AsmBackend.cpp.
Function Documentation
static unsigned getFixupKindLog2Size (unsigned Kind) static
Definition at line 38 of file X86AsmBackend.cpp.
References llvm::X86II::DF, llvm::FirstTargetFixupKind, llvm::FK_Data_1, llvm::FK_Data_2, llvm::FK_Data_4, llvm::FK_Data_8, llvm::FK_PCRel_1, llvm::FK_PCRel_2, llvm::FK_PCRel_4, llvm::FK_PCRel_8, llvm::FK_SecRel_1, llvm::FK_SecRel_2, llvm::FK_SecRel_4, llvm::FK_SecRel_8, llvm::MCFixupKindInfo::FKF_IsPCRel, llvm::MCAsmBackend::getFixupKindInfo(), llvm::MCFixup::getKind(), llvm::MCFixup::getOffset(), i, llvm::isIntN(), llvm_unreachable, llvm::X86::NumTargetFixupKinds, llvm::X86::reloc_global_offset_table, llvm::X86::reloc_riprel_4byte, llvm::X86::reloc_riprel_4byte_movq_load, and llvm::X86::reloc_signed_4byte.
static unsigned getRelaxedOpcode (unsigned Op) static
Definition at line 227 of file X86AsmBackend.cpp.
References llvm::createX86ELFObjectWriter(), llvm::createX86WinCOFFObjectWriter(), llvm::X86II::DF, llvm::MCInst::dump_pretty(), llvm::ELF::EM_386, llvm::ELF::EM_X86_64, llvm::MCSectionELF::getFlags(), llvm::MCInst::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), getRelaxedOpcodeArith(), getRelaxedOpcodeBranch(), i, llvm::MCOperand::isExpr(), llvm::MCOperand::isReg(), MCDisableArithRelaxation, llvm::report_fatal_error(), llvm::ARMBuildAttrs::Section, llvm::MCInst::setOpcode(), llvm::raw_svector_ostream::str(), and llvm::MCObjectWriter::Write8().
static unsigned getRelaxedOpcodeArith (unsigned Op) static
Definition at line 158 of file X86AsmBackend.cpp.
Referenced by getRelaxedOpcode().
static unsigned getRelaxedOpcodeBranch (unsigned Op) static
Definition at line 133 of file X86AsmBackend.cpp.
Referenced by getRelaxedOpcode().
Variable Documentation
cl::opt<bool> MCDisableArithRelaxation("mc-x86-disable-arith-relaxation", cl::desc("Disable relaxation of arithmetic instruction for X86")) static
Referenced by getRelaxedOpcode().