LLVM: X86AsmParser.cpp File Reference
LLVM API Documentation
X86AsmParser.cpp File Reference
#include "MCTargetDesc/X86BaseInfo.h"
#include "llvm/ADT/APFloat.h"
#include "llvm/ADT/STLExtras.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/SmallVector.h"
#include "llvm/ADT/StringSwitch.h"
#include "llvm/ADT/Twine.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCParser/MCAsmLexer.h"
#include "llvm/MC/MCParser/MCAsmParser.h"
#include "llvm/MC/MCParser/MCParsedAsmOperand.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/MC/MCTargetAsmParser.h"
#include "llvm/Support/SourceMgr.h"
#include "llvm/Support/TargetRegistry.h"
#include "llvm/Support/raw_ostream.h"
#include "X86GenAsmMatcher.inc"
Macros
Auto-generated Matcher Functions
{
#define GET_ASSEMBLER_HEADER
Auto-generated Match Functions
{
#define GET_REGISTER_MATCHER
#define GET_MATCHER_IMPLEMENTATION
#define GET_SUBTARGET_FEATURE_NAME
enum IntelOperatorKind { IOK_LENGTH, IOK_SIZE, IOK_TYPE }
static unsigned MatchRegisterName (StringRef Name)
static bool isImmSExti16i8Value (uint64_t Value)
}
static bool isImmSExti32i8Value (uint64_t Value)
static bool isImmZExtu32u8Value (uint64_t Value)
static bool isImmSExti64i8Value (uint64_t Value)
static bool isImmSExti64i32Value (uint64_t Value)
static unsigned getIntelMemOperandSize (StringRef OpStr)
getIntelMemOperandSize - Return intel memory operand size.
static void RewriteIntelBracExpression (SmallVectorImpl< AsmRewrite > *AsmRewrites, StringRef SymName, int64_t ImmDisp, int64_t FinalImmDisp, SMLoc &BracLoc, SMLoc &StartInBrac, SMLoc &End)
static bool convertToSExti8 (MCInst &Inst, unsigned Opcode, unsigned Reg, bool isCmp)
static bool convert16i16to16ri8 (MCInst &Inst, unsigned Opcode, bool isCmp=false)
static bool convert32i32to32ri8 (MCInst &Inst, unsigned Opcode, bool isCmp=false)
static bool convert64i32to64ri8 (MCInst &Inst, unsigned Opcode, bool isCmp=false)
static const char * getSubtargetFeatureName (unsigned Val)
void LLVMInitializeX86AsmParser ()
Macro Definition Documentation
#define GET_ASSEMBLER_HEADER
Definition at line 553 of file X86AsmParser.cpp.
#define GET_MATCHER_IMPLEMENTATION
Definition at line 2682 of file X86AsmParser.cpp.
#define GET_REGISTER_MATCHER
Definition at line 2681 of file X86AsmParser.cpp.
#define GET_SUBTARGET_FEATURE_NAME
Definition at line 2683 of file X86AsmParser.cpp.
Enumeration Type Documentation
enum IntelOperatorKind
Enumerator
IOK_LENGTH
IOK_SIZE
IOK_TYPE
Definition at line 1591 of file X86AsmParser.cpp.
Function Documentation
static bool convert16i16to16ri8 (MCInst & Inst, unsigned Opcode, bool isCmp = false) static
Definition at line 2256 of file X86AsmParser.cpp.
References convertToSExti8(), llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isImm(), and isImmSExti16i8Value().
Referenced by convert64i32to64ri8().
static bool convert32i32to32ri8 (MCInst & Inst, unsigned Opcode, bool isCmp = false) static
Definition at line 2265 of file X86AsmParser.cpp.
References convertToSExti8(), EAX, llvm::MCOperand::getImm(), llvm::MCInst::getOperand(), llvm::MCOperand::isImm(), and isImmSExti32i8Value().
Referenced by convert64i32to64ri8().
static bool convert64i32to64ri8 (MCInst & Inst, unsigned Opcode, bool isCmp = false) static
Definition at line 2274 of file X86AsmParser.cpp.
References llvm::StringSwitch< T, R >::Case(), llvm::AsmToken::Comma, convert16i16to16ri8(), convert32i32to32ri8(), convertToSExti8(), llvm::StringSwitch< T, R >::Default(), llvm::MCStreamer::EmitInstruction(), llvm::SmallVectorBase::empty(), llvm::AsmToken::EndOfStatement, llvm::lltok::Error, llvm::AsmToken::getIdentifier(), llvm::MCOperand::getImm(), llvm::AsmToken::getLoc(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::AsmToken::getString(), getSubtargetFeatureName(), llvm::MCAsmParser::getTok(), i, is, llvm::MCOperand::isImm(), isImmSExti64i8Value(), llvm::X86II::isX86_64ExtendedReg(), llvm::MCAsmParser::Lex(), llvm_unreachable, llvm::MCAF_Code32, llvm::MCAF_Code64, llvm::None, llvm::MCInst::setLoc(), llvm::MCInst::setOpcode(), llvm::StringRef::size(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::StringRef::startswith(), llvm::SmallString< InternalLen >::str(), and llvm::raw_svector_ostream::str().
static bool convertToSExti8 (MCInst & Inst, unsigned Opcode, unsigned Reg, bool isCmp) static
Definition at line 2244 of file X86AsmParser.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateReg(), llvm::MCInst::getOperand(), and llvm::MCInst::setOpcode().
Referenced by convert16i16to16ri8(), convert32i32to32ri8(), and convert64i32to64ri8().
static unsigned getIntelMemOperandSize (StringRef OpStr) static
getIntelMemOperandSize - Return intel memory operand size.
Definition at line 1165 of file X86AsmParser.cpp.
References llvm::AOK_SizeDirective, llvm::ParseInstructionInfo::AsmRewrites, llvm::StringSwitch< T, R >::Cases(), llvm::StringSwitch< T, R >::Default(), EBX, llvm::MCAsmParserSemaCallback::InlineAsmIdentifierInfo::IsVarDecl, llvm::MCAsmParserSemaCallback::InlineAsmIdentifierInfo::OpDecl, and llvm::MCAsmParserSemaCallback::InlineAsmIdentifierInfo::Type.
static const char* getSubtargetFeatureName (unsigned Val) static
Referenced by convert64i32to64ri8().
static bool isImmSExti16i8Value (uint64_t Value) static
}
Definition at line 583 of file X86AsmParser.cpp.
Referenced by convert16i16to16ri8(), and isImmSExti64i32Value().
static bool isImmSExti32i8Value (uint64_t Value) static
Definition at line 589 of file X86AsmParser.cpp.
Referenced by convert32i32to32ri8(), and isImmSExti64i32Value().
static bool isImmSExti64i32Value (uint64_t Value) static
Definition at line 604 of file X86AsmParser.cpp.
References llvm::MCInst::addOperand(), llvm::MCOperand::CreateExpr(), llvm::MCOperand::CreateImm(), llvm::MCOperand::CreateReg(), llvm::StringRef::data(), llvm::dyn_cast(), EAX, llvm::N86::EBP, EBX, llvm::N86::ECX, EDI, EDX, llvm::lltok::Error, ESI, llvm::N86::ESP, llvm::AsmToken::getEndLoc(), llvm::SMLoc::getFromPointer(), llvm::AsmToken::getIntVal(), llvm::AsmToken::getLoc(), llvm::SMLoc::getPointer(), getReg(), llvm::AsmToken::getString(), llvm::MCAsmParser::getTok(), llvm::getToken(), llvm::MCConstantExpr::getValue(), llvm::AsmToken::Identifier, llvm::AsmToken::Integer, llvm::AsmToken::is(), isImmSExti16i8Value(), isImmSExti32i8Value(), isImmSExti64i8Value(), isImmZExtu32u8Value(), llvm::isMem(), llvm::AsmToken::isNot(), isReg(), llvm::X86II::isX86_64ExtendedReg(), llvm::X86II::isX86_64NonExtLowByteReg(), llvm::MCAsmParser::Lex(), llvm_unreachable, llvm::StringRef::lower(), llvm::AsmToken::LParen, MatchRegisterName(), N, llvm::AsmToken::Percent, Register, llvm::AsmToken::RParen, llvm::StringRef::size(), llvm::StringRef::startswith(), and XMM0.
static bool isImmSExti64i8Value (uint64_t Value) static
Definition at line 599 of file X86AsmParser.cpp.
Referenced by convert64i32to64ri8(), and isImmSExti64i32Value().
static bool isImmZExtu32u8Value (uint64_t Value) static
Definition at line 595 of file X86AsmParser.cpp.
Referenced by isImmSExti64i32Value().
void LLVMInitializeX86AsmParser ()
Definition at line 2676 of file X86AsmParser.cpp.
References llvm::TheX86_32Target, llvm::TheX86_64Target, llvm::X, and Y.
static unsigned MatchRegisterName (StringRef Name) static
Referenced by isImmSExti64i32Value().
static void RewriteIntelBracExpression (SmallVectorImpl< AsmRewrite > * AsmRewrites, StringRef SymName, int64_t ImmDisp, int64_t FinalImmDisp, SMLoc & BracLoc, SMLoc & StartInBrac, SMLoc & End) static
Definition at line 1211 of file X86AsmParser.cpp.
References llvm::AOK_Delete, llvm::AOK_DotOperator, llvm::AOK_Imm, llvm::AOK_ImmPrefix, llvm::AOK_Skip, llvm::ParseInstructionInfo::AsmRewrites, llvm::SmallVectorTemplateCommon< T >::begin(), llvm::AsmToken::Colon, llvm::MCConstantExpr::Create(), llvm::MCSymbolRefExpr::Create(), llvm::StringRef::data(), llvm::StringRef::drop_front(), EBX, llvm::SmallVectorTemplateCommon< T >::end(), llvm::AsmToken::EndOfStatement, llvm::lltok::Error, llvm::AsmToken::getEndLoc(), llvm::SMLoc::getFromPointer(), llvm::AsmToken::getIntVal(), llvm::AsmToken::getLoc(), llvm::SMLoc::getPointer(), llvm::AsmToken::getString(), llvm::MCAsmParser::getTok(), llvm::APInt::getZExtValue(), I, llvm::AsmToken::Identifier, llvm::AsmToken::Integer, llvm::AsmToken::is(), is, llvm::AsmToken::isNot(), llvm::AsmToken::LBrac, llvm::MCAsmParser::Lex(), llvm::AsmToken::LParen, llvm::AsmToken::Minus, llvm::MCAsmParserSemaCallback::InlineAsmIdentifierInfo::OpDecl, llvm::AsmToken::Plus, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::AsmToken::RBrac, llvm::AsmToken::Real, llvm::AsmToken::RParen, llvm::StringRef::size(), llvm::AsmToken::Slash, llvm::AsmToken::Star, llvm::StringRef::startswith(), and llvm::MCSymbolRefExpr::VK_None.