LLVM: X86CodeEmitter.cpp File Reference
LLVM API Documentation
X86CodeEmitter.cpp File Reference
#include "X86.h"
#include "X86InstrInfo.h"
#include "X86JITInfo.h"
#include "X86Relocations.h"
#include "X86Subtarget.h"
#include "X86TargetMachine.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/JITCodeEmitter.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstr.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/IR/LLVMContext.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/PassManager.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetOptions.h"
Macros
#define DEBUG_TYPE "x86-emitter"
Functions
STATISTIC (NumEmitted,"Number of machine instructions emitted")
static unsigned determineREX (const MachineInstr &MI)
static unsigned char ModRMByte (unsigned Mod, unsigned RegOpcode, unsigned RM)
static bool isDisp8 (int Value)
static bool gvNeedsNonLazyPtr (const MachineOperand &GVOp, const TargetMachine &TM)
static const MCInstrDesc * UpdateOp (MachineInstr &MI, const X86InstrInfo *II, unsigned Opcode)
static bool Is16BitMemOperand (const MachineInstr &MI, unsigned Op)
static bool Is32BitMemOperand (const MachineInstr &MI, unsigned Op)
static bool Is64BitMemOperand (const MachineInstr &MI, unsigned Op)
Macro Definition Documentation
#define DEBUG_TYPE "x86-emitter"
Definition at line 15 of file X86CodeEmitter.cpp.
Function Documentation
static unsigned determineREX (const MachineInstr & MI) static
determineREX - Determine if the MachineInstr has to be encoded with a X86-64 REX prefix which specifies 1) 64-bit instructions, 2) non-default operand size, and 3) use of X86-64 extended registers.
Definition at line 162 of file X86CodeEmitter.cpp.
References llvm::X86::AddrNumOperands, llvm::tgtok::Bit, llvm::X86II::FormMask, llvm::MachineRelocation::getBB(), llvm::MachineRelocation::getConstPool(), llvm::MachineInstr::getDesc(), llvm::MachineRelocation::getExtSym(), llvm::MachineRelocation::getGV(), llvm::MachineRelocation::getIndirectSymbol(), llvm::MachineRelocation::getJumpTable(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MCInstrDesc::getOperandConstraint(), llvm::MachineOperand::getReg(), i, llvm::MachineOperand::isReg(), llvm::X86InstrInfo::isX86_64ExtendedReg(), llvm::X86II::isX86_64NonExtLowByteReg(), llvm::X86II::MRM0m, llvm::X86II::MRM1m, llvm::X86II::MRM2m, llvm::X86II::MRM3m, llvm::X86II::MRM4m, llvm::X86II::MRM5m, llvm::X86II::MRM6m, llvm::X86II::MRM7m, llvm::X86II::MRMDestMem, llvm::X86II::MRMInitReg, llvm::X86II::MRMSrcMem, llvm::X86II::MRMSrcReg, llvm::X86II::Pseudo, llvm::X86::reloc_absolute_dword, llvm::X86::reloc_pcrel_word, llvm::X86::reloc_picrel_word, llvm::X86II::REX_W, llvm::MCOI::TIED_TO, and llvm::MCInstrDesc::TSFlags.
Referenced by Is64BitMemOperand().
static bool gvNeedsNonLazyPtr (const MachineOperand & GVOp, const TargetMachine & TM) static
Definition at line 400 of file X86CodeEmitter.cpp.
References llvm::N86::EBP, llvm::N86::ESP, llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::MachineOperand::getOffset(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), llvm::TargetMachine::getSubtarget(), llvm::MachineOperand::getSymbolName(), llvm::MachineOperand::getTargetFlags(), llvm::X86Subtarget::is64Bit(), llvm::MachineOperand::isCPI(), isDisp8(), llvm::MachineOperand::isGlobal(), llvm::isGlobalStubReference(), llvm::MachineOperand::isJTI(), llvm::MachineOperand::isSymbol(), llvm::A64CC::MI, ModRMByte(), llvm::X86::reloc_absolute_word, llvm::X86::reloc_absolute_word_sext, llvm::X86::reloc_pcrel_word, and llvm::X86::reloc_picrel_word.
Referenced by Is64BitMemOperand().
static bool Is16BitMemOperand (const MachineInstr & MI, unsigned Op) static
Is16BitMemOperand - Return true if the specified instruction has a 16-bit memory operand. Op specifies the operand # of the memoperand.
Definition at line 614 of file X86CodeEmitter.cpp.
References llvm::X86::AddrBaseReg, llvm::X86::AddrIndexReg, llvm::MachineInstr::getOperand(), and llvm::MachineOperand::getReg().
Referenced by Is64BitMemOperand().
static bool Is32BitMemOperand (const MachineInstr & MI, unsigned Op) static
Is32BitMemOperand - Return true if the specified instruction has a 32-bit memory operand. Op specifies the operand # of the memoperand.
Definition at line 628 of file X86CodeEmitter.cpp.
References llvm::X86::AddrBaseReg, llvm::X86::AddrIndexReg, llvm::MachineInstr::getOperand(), and llvm::MachineOperand::getReg().
Referenced by Is64BitMemOperand().
static bool Is64BitMemOperand (const MachineInstr & MI, unsigned Op) static
Is64BitMemOperand - Return true if the specified instruction has a 64-bit memory operand. Op specifies the operand # of the memoperand.
Definition at line 643 of file X86CodeEmitter.cpp.
References llvm::X86II::A6, llvm::X86II::A7, llvm::X86::AddrBaseReg, llvm::X86II::AddRegFrm, llvm::X86::AddrIndexReg, llvm::X86::AddrNumOperands, llvm::X86::AddrSegmentReg, llvm::X86II::AdSize, llvm::X86II::D8, llvm::X86II::D9, llvm::X86II::DA, llvm::X86II::DB, llvm::dbgs(), llvm::X86II::DC, llvm::X86II::DD, llvm::X86II::DE, DEBUG, determineREX(), llvm::X86II::DF, llvm::TargetOpcode::EH_LABEL, llvm::X86II::FormMask, llvm::X86II::FS, llvm::TargetOpcode::GC_LABEL, llvm::X86II::getBaseOpcodeFor(), llvm::MachineInstr::getDebugLoc(), llvm::MachineOperand::getGlobal(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::X86TargetMachine::getJITInfo(), llvm::MachineOperand::getMBB(), llvm::MachineOperand::getMCSymbol(), llvm::X86II::getMemoryOperandNo(), llvm::MCInstrDesc::getNumOperands(), llvm::MachineOperand::getOffset(), llvm::MCInstrDesc::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MCInstrDesc::getOperandConstraint(), llvm::MachineOperand::getReg(), llvm::X86II::getSizeOfImm(), llvm::MachineOperand::getSymbolName(), llvm::X86II::GS, gvNeedsNonLazyPtr(), llvm::TargetOpcode::IMPLICIT_DEF, llvm::TargetOpcode::INLINEASM, Is16BitMemOperand(), Is32BitMemOperand(), llvm::MachineOperand::isCPI(), llvm::MachineOperand::isGlobal(), llvm::MachineOperand::isImm(), llvm::MachineOperand::isJTI(), llvm::MachineOperand::isMBB(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isSymbol(), llvm::MachineInstr::isVariadic(), llvm::X86II::isX86_64ExtendedReg(), llvm::TargetOpcode::KILL, llvm_unreachable, llvm::X86II::LOCK, llvm::X86II::MemOp4, llvm::X86II::MRM0m, llvm::X86II::MRM0r, llvm::X86II::MRM1m, llvm::X86II::MRM1r, llvm::X86II::MRM2m, llvm::X86II::MRM2r, llvm::X86II::MRM3m, llvm::X86II::MRM3r, llvm::X86II::MRM4m, llvm::X86II::MRM4r, llvm::X86II::MRM5m, llvm::X86II::MRM5r, llvm::X86II::MRM6m, llvm::X86II::MRM6r, llvm::X86II::MRM7m, llvm::X86II::MRM7r, llvm::X86II::MRM_C1, llvm::X86II::MRM_C8, llvm::X86II::MRM_C9, llvm::X86II::MRM_CA, llvm::X86II::MRM_CB, llvm::X86II::MRM_E8, llvm::X86II::MRM_F0, llvm::X86II::MRMDestMem, llvm::X86II::MRMDestReg, llvm::X86II::MRMInitReg, llvm::X86II::MRMSrcMem, llvm::X86II::MRMSrcReg, llvm::X86II::Op0Mask, llvm::X86II::Op0Shift, llvm::MCInstrDesc::Opcode, llvm::X86II::OpSize, llvm::TargetOpcode::PROLOG_LABEL, llvm::X86II::Pseudo, llvm::X86II::RawFrm, llvm::X86::reloc_absolute_dword, llvm::X86::reloc_absolute_word, llvm::X86::reloc_absolute_word_sext, llvm::X86::reloc_pcrel_word, llvm::X86::reloc_picrel_word, llvm::X86II::REP, llvm::report_fatal_error(), llvm::X86II::SegOvrMask, llvm::X86JITInfo::setPICBase(), llvm::X86II::T8, llvm::X86II::T8XD, llvm::X86II::T8XS, llvm::X86II::TA, llvm::X86II::TAXD, llvm::X86II::TB, llvm::MCOI::TIED_TO, llvm::MCInstrDesc::TSFlags, UpdateOp(), llvm::X86II::VEX, llvm::X86II::VEX_4V, llvm::X86II::VEX_4VOp3, llvm::X86II::VEX_I8IMM, llvm::X86II::VEX_L, llvm::X86II::VEX_W, llvm::X86II::VEXShift, llvm::X86II::XD, llvm::X86II::XOP, llvm::X86II::XOP8, llvm::X86II::XOP9, llvm::X86II::XOPA, and llvm::X86II::XS.
static bool isDisp8 (int Value) static
isDisp8 - Return true if this signed displacement fits in a 8-bit sign-extended field.
Definition at line 396 of file X86CodeEmitter.cpp.
Referenced by gvNeedsNonLazyPtr().
static unsigned char ModRMByte (unsigned Mod, unsigned RegOpcode, unsigned RM) inline static
Definition at line 360 of file X86CodeEmitter.cpp.
References i.
Referenced by gvNeedsNonLazyPtr(), and HasSecRelSymbolRef().
STATISTIC (NumEmitted , "Number of machine instructions emitted")
static const MCInstrDesc* UpdateOp (MachineInstr & MI, const X86InstrInfo * II, unsigned Opcode) static
Definition at line 605 of file X86CodeEmitter.cpp.
References llvm::MachineInstr::setDesc().
Referenced by Is64BitMemOperand().