LLVM: X86FastISel.cpp File Reference
LLVM API Documentation
X86FastISel.cpp File Reference
#include "X86.h"
#include "X86CallingConv.h"
#include "X86ISelLowering.h"
#include "X86InstrBuilder.h"
#include "X86RegisterInfo.h"
#include "X86Subtarget.h"
#include "X86TargetMachine.h"
#include "llvm/CodeGen/Analysis.h"
#include "llvm/CodeGen/FastISel.h"
#include "llvm/CodeGen/FunctionLoweringInfo.h"
#include "llvm/CodeGen/MachineConstantPool.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/IR/CallingConv.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/GlobalAlias.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/IntrinsicInst.h"
#include "llvm/IR/Operator.h"
#include "llvm/Support/CallSite.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/GetElementPtrTypeIterator.h"
#include "llvm/Target/TargetOptions.h"
#include "X86GenFastISel.inc"
#include "X86GenCallingConv.inc"
Namespaces
llvm
List of target independent CodeGen pass IDs.
Functions
static unsigned X86ChooseCmpOpcode (EVT VT, const X86Subtarget *Subtarget)
static unsigned X86ChooseCmpImmediateOpcode (EVT VT, const ConstantInt *RHSC)
static unsigned computeBytesPoppedByCallee (const X86Subtarget &Subtarget, const ImmutableCallSite &CS)
Function Documentation
static unsigned computeBytesPoppedByCallee (const X86Subtarget & Subtarget, const ImmutableCallSite & CS) static
Definition at line 1862 of file X86FastISel.cpp.
References llvm::addConstantPoolReference(), llvm::MachineInstrBuilder::addExternalSymbol(), llvm::addFrameReference(), llvm::addFullAddress(), llvm::MachineInstrBuilder::addGlobalAddress(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addReg(), llvm::MachineInstrBuilder::addRegMask(), llvm::CCValAssign::AExt, llvm::A64CC::AL, Align, llvm::CCState::AllocateStack(), llvm::CCState::AnalyzeCallResult(), llvm::ISD::AND, llvm::ISD::ANY_EXTEND, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_begin(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_end(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::arg_size(), llvm::X86AddressMode::Base, llvm::X86AddressMode::BaseType, llvm::CCValAssign::BCvt, llvm::ISD::BITCAST, llvm::EVT::bitsGT(), llvm::EVT::bitsLT(), llvm::BuildMI(), llvm::Attribute::ByVal, llvm::CallingConv::C, llvm::Call, llvm::ComputeValueVTs(), llvm::TargetOpcode::COPY, llvm::X86AddressMode::Disp, EBX, llvm::MachineInstr::eraseFromParent(), llvm::MVT::f32, llvm::MVT::f64, llvm::MVT::f80, llvm::CallingConv::Fast, llvm::ISD::InputArg::Flags, llvm::X86InstrInfo::foldMemoryOperandImpl(), llvm::CCValAssign::Full, llvm::LoadInst::getAlignment(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getAttributes(), llvm::ISD::ArgFlagsTy::getByValSize(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCalledValue(), llvm::CallInst::getCalledValue(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getCallingConv(), llvm::BasicBlock::getContext(), llvm::Value::getContext(), llvm::SequentialType::getElementType(), llvm::X86AddressMode::getFullAddress(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getInstruction(), llvm::Type::getInt32Ty(), llvm::CCValAssign::getLocInfo(), llvm::CCValAssign::getLocMemOffset(), llvm::CCValAssign::getLocReg(), llvm::CCValAssign::getLocVT(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::getParamAlignment(), llvm::Instruction::getParent(), llvm::GetReturnInfo(), llvm::ConstantExpr::getSExt(), llvm::EVT::getSimpleVT(), llvm::EVT::getSizeInBits(), llvm::X86RegisterInfo::getStackRegister(), llvm::X86Subtarget::getTargetTriple(), llvm::Value::getType(), llvm::CCValAssign::getValNo(), llvm::ConstantExpr::getZExt(), llvm::CallingConv::GHC, llvm::X86AddressMode::GV, llvm::X86Subtarget::hasAVX(), llvm::GlobalValue::hasDefaultVisibility(), llvm::GlobalValue::hasLocalLinkage(), llvm::Value::hasOneUse(), i, I, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::RegState::Implicit, llvm::X86AddressMode::IndexReg, llvm::CCValAssign::Indirect, llvm::Attribute::InReg, llvm::MipsISD::Ins, llvm::X86Subtarget::is64Bit(), llvm::ISD::ArgFlagsTy::isByVal(), llvm::X86::isCalleePop(), llvm::X86Subtarget::isCallingConvWin64(), llvm::GlobalValue::isDeclaration(), llvm::MVT::isInteger(), llvm::Type::isIntegerTy(), llvm::Triple::isMacOSX(), llvm::Triple::isMacOSXVersionLT(), llvm::X86Subtarget::isPICStyleGOT(), llvm::X86Subtarget::isPICStyleRIPRel(), llvm::X86Subtarget::isPICStyleStubAny(), llvm::X86Subtarget::isPICStyleStubPIC(), llvm::CCValAssign::isRegLoc(), llvm::ISD::ArgFlagsTy::isSExt(), llvm::X86Subtarget::isTargetELF(), llvm::X86Subtarget::isTargetWindows(), llvm::FunctionType::isVarArg(), llvm::MVT::isVector(), llvm::GlobalValue::isWeakForLinker(), j(), llvm::SPII::Load, llvm::A64CC::MI, llvm::X86II::MO_DARWIN_STUB, llvm::X86II::MO_GOTOFF, llvm::X86II::MO_PIC_BASE_OFFSET, llvm::X86II::MO_PLT, llvm::Attribute::Nest, llvm::CallSiteBase< FunTy, ValTy, UserTy, InstrTy, CallTy, InvokeTy, IterTy >::paramHasAttr(), llvm::Reloc::PIC_, llvm::SmallVectorTemplateBase< T, isPodLike >::push_back(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::X86AddressMode::Reg, llvm::X86AddressMode::RegBase, llvm::SmallVectorImpl< T >::reserve(), llvm::AArch64ISD::Ret, llvm::MCID::Select, llvm::ISD::ArgFlagsTy::setByVal(), llvm::ISD::ArgFlagsTy::setByValAlign(), llvm::ISD::ArgFlagsTy::setByValSize(), llvm::ISD::ArgFlagsTy::setInReg(), llvm::ISD::ArgFlagsTy::setNest(), llvm::ISD::ArgFlagsTy::setOrigAlign(), llvm::ISD::ArgFlagsTy::setSExt(), llvm::ISD::ArgFlagsTy::setZExt(), llvm::CCValAssign::SExt, llvm::Attribute::SExt, llvm::ISD::SIGN_EXTEND, llvm::MVT::SimpleTy, llvm::SmallVectorTemplateCommon< T, typename >::size(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::CodeModel::Small, llvm::SPII::Store, llvm::Attribute::StructRet, TII, llvm::SystemZISD::TM, llvm::Value::use_empty(), llvm::ISD::InputArg::Used, llvm::CCValAssign::VExt, llvm::ISD::InputArg::VT, llvm::CallingConv::X86_64_SysV, llvm::CallingConv::X86_64_Win64, llvm::CallingConv::X86_FastCall, llvm::MVT::x86mmx, XMM0, XMM1, XMM2, XMM3, llvm::ISD::ZERO_EXTEND, llvm::CCValAssign::ZExt, and llvm::Attribute::ZExt.
static unsigned X86ChooseCmpImmediateOpcode (EVT VT, const ConstantInt * RHSC) static
X86ChooseCmpImmediateOpcode - If we have a comparison with RHS as the RHS of the comparison, return an opcode that works for the compare (e.g. CMP32ri) otherwise return 0.
Definition at line 941 of file X86FastISel.cpp.
References llvm::addFullAddress(), llvm::MachineInstrBuilder::addImm(), llvm::MachineInstrBuilder::addMetadata(), llvm::MachineInstrBuilder::addReg(), AH, llvm::A64CC::AL, llvm::Function::arg_begin(), llvm::Function::arg_end(), llvm::BuildMI(), llvm::Attribute::ByVal, llvm::CallingConv::C, llvm::TargetOpcode::COPY, llvm::Intrinsic::dbg_declare, llvm::TargetOpcode::DBG_VALUE, llvm::X86AddressMode::Disp, EAX, llvm::N86::ECX, EDI, EDX, ESI, llvm::CmpInst::FCMP_OEQ, llvm::CmpInst::FCMP_OGE, llvm::CmpInst::FCMP_OGT, llvm::CmpInst::FCMP_OLE, llvm::CmpInst::FCMP_OLT, llvm::CmpInst::FCMP_ONE, llvm::CmpInst::FCMP_ORD, llvm::CmpInst::FCMP_UEQ, llvm::CmpInst::FCMP_UGE, llvm::CmpInst::FCMP_UGT, llvm::CmpInst::FCMP_ULE, llvm::CmpInst::FCMP_ULT, llvm::CmpInst::FCMP_UNE, llvm::CmpInst::FCMP_UNO, llvm::DbgDeclareInst::getAddress(), llvm::CallInst::getArgOperand(), llvm::Function::getAttributes(), llvm::CallInst::getCalledFunction(), llvm::CallInst::getCalledValue(), llvm::Function::getCallingConv(), llvm::BranchInst::getCondition(), llvm::Value::getContext(), llvm::MemIntrinsic::getDestAddressSpace(), llvm::IntrinsicInst::getIntrinsicID(), llvm::CmpInst::getInversePredicate(), llvm::getKillRegState(), llvm::MemIntrinsic::getLength(), llvm::Constant::getNullValue(), llvm::Instruction::getOpcode(), llvm::User::getOperand(), llvm::Instruction::getParent(), llvm::CmpInst::getPredicate(), llvm::MemIntrinsic::getRawDest(), llvm::MemTransferInst::getRawSource(), llvm::Function::getReturnType(), llvm::ConstantInt::getSExtValue(), llvm::EVT::getSimpleVT(), llvm::MVT::getSizeInBits(), llvm::MemTransferInst::getSourceAddressSpace(), llvm::BranchInst::getSuccessor(), llvm::Value::getType(), llvm::DbgDeclareInst::getVariable(), llvm::AttributeSet::hasAttribute(), llvm::X86Subtarget::hasCMov(), llvm::Value::hasOneUse(), I, llvm::MVT::i1, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::CmpInst::ICMP_EQ, llvm::CmpInst::ICMP_NE, llvm::CmpInst::ICMP_SGE, llvm::CmpInst::ICMP_SGT, llvm::CmpInst::ICMP_SLE, llvm::CmpInst::ICMP_SLT, llvm::CmpInst::ICMP_UGE, llvm::CmpInst::ICMP_UGT, llvm::CmpInst::ICMP_ULE, llvm::CmpInst::ICMP_ULT, llvm::Attribute::InReg, is32Bit(), llvm::X86Subtarget::is64Bit(), llvm::Type::isArrayTy(), llvm::X86Subtarget::isCallingConvWin64(), llvm::Type::isDoubleTy(), llvm::Type::isFloatTy(), llvm::Type::isIntegerTy(), llvm::EVT::isSimple(), llvm::Type::isStructTy(), llvm::Function::isVarArg(), llvm::Type::isVectorTy(), llvm::MemIntrinsic::isVolatile(), llvm::RegState::Kill, llvm::TargetOpcode::KILL, llvm_unreachable, llvm::Intrinsic::memcpy, llvm::Intrinsic::memset, llvm::Attribute::Nest, llvm::Intrinsic::sadd_with_overflow, llvm::MVT::SimpleTy, llvm::Intrinsic::stackprotector, llvm::Attribute::StructRet, llvm::TargetOpcode::SUBREG_TO_REG, std::swap(), TII, llvm::ISD::TRAP, llvm::Intrinsic::trap, llvm::Intrinsic::uadd_with_overflow, X86ChooseCmpOpcode(), and llvm::ISD::ZERO_EXTEND.
static unsigned X86ChooseCmpOpcode (EVT VT, const X86Subtarget * Subtarget) static
Definition at line 920 of file X86FastISel.cpp.
References llvm::MVT::f32, llvm::MVT::f64, llvm::EVT::getSimpleVT(), llvm::X86Subtarget::hasAVX(), llvm::X86Subtarget::hasSSE1(), llvm::X86Subtarget::hasSSE2(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, and llvm::MVT::SimpleTy.
Referenced by X86ChooseCmpImmediateOpcode().