LLVM: X86FixupLEAs.cpp File Reference
LLVM API Documentation
X86FixupLEAs.cpp File Reference
#include "X86.h"
#include "X86InstrInfo.h"
#include "X86Subtarget.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/LiveVariables.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
Macros
#define DEBUG_TYPE "x86-fixup-LEAs"
Functions
STATISTIC (NumLEAs,"Number of LEA instructions created")
static bool getPreviousInstr (MachineBasicBlock::iterator &I, MachineFunction::iterator MFI)
Macro Definition Documentation
#define DEBUG_TYPE "x86-fixup-LEAs"
Definition at line 16 of file X86FixupLEAs.cpp.
Function Documentation
static bool getPreviousInstr (MachineBasicBlock::iterator & I, MachineFunction::iterator MFI) inline static
getPreviousInstr - Given a reference to an instruction in a basic block, return a reference to the previous instruction in the block, wrapping around to the last instruction of the block if the block branches to itself.
Definition at line 179 of file X86FixupLEAs.cpp.
References llvm::X86::AddrBaseReg, llvm::X86::AddrIndexReg, llvm::dbgs(), DEBUG, llvm::MachineInstr::dump(), llvm::N86::ESP, llvm::MachineInstr::getDesc(), llvm::X86II::getMemoryOperandNo(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::X86II::getOperandBias(), llvm::MachineOperand::getReg(), I, llvm::MachineOperand::isReg(), TII, llvm::SystemZISD::TM, and llvm::MCInstrDesc::TSFlags.
STATISTIC (NumLEAs , "Number of LEA instructions created")