LLVM: X86ISelDAGToDAG.cpp File Reference
LLVM API Documentation
X86ISelDAGToDAG.cpp File Reference
#include "X86.h"
#include "X86InstrBuilder.h"
#include "X86MachineFunctionInfo.h"
#include "X86RegisterInfo.h"
#include "X86Subtarget.h"
#include "X86TargetMachine.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/SelectionDAGISel.h"
#include "llvm/IR/Instructions.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/Type.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/MathExtras.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetMachine.h"
#include "llvm/Target/TargetOptions.h"
#include "X86GenDAGISel.inc"
Macros
#define DEBUG_TYPE "x86-isel"
Enumerations
enum AtomicOpc {
ADD, SUB, INC, DEC,
OR, AND, XOR, AtomicOpcEnd
}
enum AtomicSz {
ConstantI8, I8, SextConstantI16, ConstantI16,
I16, SextConstantI32, ConstantI32, I32,
SextConstantI64, ConstantI64, I64, AtomicSzEnd
}
Functions
STATISTIC (NumLoadMoved,"Number of loads moved below TokenFactor")
static void MoveBelowOrigChain (SelectionDAG *CurDAG, SDValue Load, SDValue Call, SDValue OrigChain)
static bool isCalleeLoad (SDValue Callee, SDValue &Chain, bool HasCallSeq)
static bool isDispSafeForFrameIndex (int64_t Val)
static void InsertDAGNode (SelectionDAG &DAG, SDValue Pos, SDValue N)
static bool FoldMaskAndShiftToExtract (SelectionDAG &DAG, SDValue N, uint64_t Mask, SDValue Shift, SDValue X, X86ISelAddressMode &AM)
static bool FoldMaskedShiftToScaledMask (SelectionDAG &DAG, SDValue N, uint64_t Mask, SDValue Shift, SDValue X, X86ISelAddressMode &AM)
static bool FoldMaskAndShiftToScale (SelectionDAG &DAG, SDValue N, uint64_t Mask, SDValue Shift, SDValue X, X86ISelAddressMode &AM)
static SDValue getAtomicLoadArithTargetConstant (SelectionDAG *CurDAG, SDLoc dl, enum AtomicOpc &Op, MVT NVT, SDValue Val)
static bool HasNoSignedComparisonUses (SDNode *N)
static bool isLoadIncOrDecStore (StoreSDNode *StoreNode, unsigned Opc, SDValue StoredVal, SelectionDAG *CurDAG, LoadSDNode *&LoadNode, SDValue &InputChain)
static unsigned getFusedLdStOpcode (EVT &LdVT, unsigned Opc)
Variables
static const uint16_t AtomicOpcTbl [AtomicOpcEnd][AtomicSzEnd]
Macro Definition Documentation
#define DEBUG_TYPE "x86-isel"
Definition at line 15 of file X86ISelDAGToDAG.cpp.
Enumeration Type Documentation
enum AtomicOpc
Atomic opcode table
Enumerator
ADD
SUB
INC
DEC
OR
AND
XOR
AtomicOpcEnd
Definition at line 1582 of file X86ISelDAGToDAG.cpp.
enum AtomicSz
Enumerator
ConstantI8
I8
SextConstantI16
ConstantI16
I16
SextConstantI32
ConstantI32
I32
SextConstantI64
ConstantI64
I64
AtomicSzEnd
Definition at line 1593 of file X86ISelDAGToDAG.cpp.
Function Documentation
static bool FoldMaskAndShiftToExtract (SelectionDAG & DAG, SDValue N, uint64_t Mask, SDValue Shift, SDValue X, X86ISelAddressMode & AM) static
Definition at line 773 of file X86ISelDAGToDAG.cpp.
References llvm::ISD::AND, llvm::APIntOps::And(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandVal(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SDValue::hasOneUse(), llvm::MVT::i8, InsertDAGNode(), llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::ISD::SHL, and llvm::ISD::SRL.
Referenced by FoldMaskAndShiftToScale().
static bool FoldMaskAndShiftToScale (SelectionDAG & DAG, SDValue N, uint64_t Mask, SDValue Shift, SDValue X, X86ISelAddressMode & AM) static
Definition at line 883 of file X86ISelDAGToDAG.cpp.
References llvm::ISD::ADD, llvm::ISD::AND, llvm::APIntOps::And(), llvm::ISD::ANY_EXTEND, llvm::SelectionDAG::ComputeMaskedBits(), llvm::ISD::Constant, llvm::ISD::CopyFromReg, llvm::countLeadingZeros(), llvm::CountTrailingOnes_64(), llvm::countTrailingZeros(), llvm::dbgs(), DEBUG, llvm::dyn_cast(), EBX, llvm::X86ISD::EH_SJLJ_LONGJMP, llvm::X86ISD::EH_SJLJ_SETJMP, FoldMaskAndShiftToExtract(), FoldMaskedShiftToScaledMask(), llvm::ISD::FrameIndex, llvm::X86II::FS, llvm::LoadSDNode::getBasePtr(), llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandVal(), llvm::APInt::getHighBitsSet(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::RegisterSDNode::getReg(), llvm::SDValue::getResNo(), llvm::ConstantSDNode::getSExtValue(), llvm::SDValue::getSimpleValueType(), llvm::MVT::getSizeInBits(), llvm::HandleSDNode::getValue(), llvm::SDValue::getValueType(), llvm::PPCISD::GlobalBaseReg, llvm::X86II::GS, llvm::SDValue::hasOneUse(), llvm::SDNode::hasOneUse(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, InsertDAGNode(), llvm::ISD::INTRINSIC_VOID, llvm::ISD::INTRINSIC_W_CHAIN, llvm::X86Subtarget::is64Bit(), isDispSafeForFrameIndex(), llvm::ISD::isNON_EXTLoad(), llvm::A64DB::LD, llvm::ISD::LOAD, llvm::ISD::MUL, llvm::X86ISD::MUL_IMM, N, llvm::ISD::OR, llvm::MVT::Other, P, llvm::SelectionDAG::ReplaceAllUsesWith(), llvm::NVPTX::PTXCvtMode::RN, llvm::ISD::SCALAR_TO_VECTOR, Shift, llvm::ISD::SHL, llvm::CodeModel::Small, llvm::ISD::SMUL_LOHI, llvm::ISD::SRL, llvm::ISD::SUB, llvm::TargetOpcode::SUBREG_TO_REG, T, llvm::ISD::TargetBlockAddress, llvm::ISD::TargetConstantPool, llvm::ISD::TargetExternalSymbol, llvm::ISD::TargetGlobalAddress, llvm::ISD::TargetGlobalTLSAddress, llvm::ISD::TargetJumpTable, llvm::X86ISD::TLSCALL, llvm::SystemZISD::TM, llvm::ISD::TRUNCATE, llvm::ISD::UMUL_LOHI, llvm::X86ISD::VZEXT_MOVL, llvm::X86ISD::Wrapper, llvm::X86ISD::WrapperRIP, llvm::X, and llvm::ISD::ZERO_EXTEND.
static bool FoldMaskedShiftToScaledMask (SelectionDAG & DAG, SDValue N, uint64_t Mask, SDValue Shift, SDValue X, X86ISelAddressMode & AM) static
Definition at line 816 of file X86ISelDAGToDAG.cpp.
References llvm::ISD::AND, llvm::SelectionDAG::getConstant(), llvm::SDValue::getConstantOperandVal(), llvm::SelectionDAG::getNode(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SDValue::hasOneUse(), InsertDAGNode(), llvm::SelectionDAG::ReplaceAllUsesWith(), and llvm::ISD::SHL.
Referenced by FoldMaskAndShiftToScale().
static SDValue getAtomicLoadArithTargetConstant (SelectionDAG * CurDAG, SDLoc dl, enum AtomicOpc & Op, MVT NVT, SDValue Val) static
Definition at line 1708 of file X86ISelDAGToDAG.cpp.
References ADD, AND, llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_XOR, ConstantI16, ConstantI32, ConstantI64, ConstantI8, DEC, llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SelectionDAG::getTargetConstant(), llvm::SelectionDAG::getTargetExtractSubreg(), llvm::SDNode::hasAnyUseOfValue(), llvm::SDValue::hasOneUse(), llvm::MVT::i16, I16, llvm::MVT::i32, I32, llvm::MVT::i64, I64, llvm::MVT::i8, I8, llvm::TargetOpcode::IMPLICIT_DEF, INC, llvm::X86::isZeroNode(), OR, llvm::MVT::Other, llvm::AArch64ISD::Ret, SextConstantI16, SextConstantI32, SextConstantI64, llvm::MVT::SimpleTy, llvm::ISD::SUB, SUB, llvm::ISD::TargetConstant, llvm::ISD::TRUNCATE, llvm::RegState::Undef, and XOR.
static unsigned getFusedLdStOpcode (EVT & LdVT, unsigned Opc) static
getFusedLdStOpcode - Get the appropriate X86 opcode for an in memory increment or decrement. Opc should be X86ISD::DEC or X86ISD::INC.
Definition at line 2003 of file X86ISelDAGToDAG.cpp.
References AH, llvm::A64CC::AL, llvm::X86ISD::AND, llvm::ISD::AND, llvm::X86ISD::ATOMADD64_DAG, llvm::X86ISD::ATOMAND64_DAG, llvm::ISD::ATOMIC_LOAD_ADD, llvm::ISD::ATOMIC_LOAD_AND, llvm::ISD::ATOMIC_LOAD_OR, llvm::ISD::ATOMIC_LOAD_XOR, llvm::X86ISD::ATOMMAX64_DAG, llvm::X86ISD::ATOMMIN64_DAG, llvm::X86ISD::ATOMNAND64_DAG, llvm::X86ISD::ATOMOR64_DAG, llvm::X86ISD::ATOMSUB64_DAG, llvm::X86ISD::ATOMSWAP64_DAG, llvm::X86ISD::ATOMUMAX64_DAG, llvm::X86ISD::ATOMUMIN64_DAG, llvm::X86ISD::ATOMXOR64_DAG, llvm::X86ISD::CMP, llvm::TargetOpcode::COPY_TO_REGCLASS, llvm::dbgs(), DEBUG, llvm::X86ISD::DEC, llvm::SDNode::dump(), llvm::dyn_cast(), EAX, EDX, llvm::TargetOpcode::EXTRACT_SUBREG, llvm::LoadSDNode::getBasePtr(), llvm::TargetRegisterClass::getID(), llvm::MemSDNode::getMemOperand(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getResNo(), llvm::ConstantSDNode::getSExtValue(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::SDValue::getValue(), llvm::SDValue::getValueType(), llvm::ConstantSDNode::getZExtValue(), llvm::X86ISD::GlobalBaseReg, llvm::MVT::Glue, llvm::SDNode::hasAnyUseOfValue(), llvm::X86Subtarget::hasAVX2(), llvm::X86Subtarget::hasBMI2(), HasNoSignedComparisonUses(), llvm::SDValue::hasOneUse(), llvm::SDNode::hasOneUse(), llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::X86ISD::INC, llvm::ISD::INTRINSIC_W_CHAIN, llvm::X86Subtarget::is64Bit(), llvm::isInt< 32 >(), llvm::isInt< 8 >(), isLoadIncOrDecStore(), llvm::SDNode::isMachineOpcode(), llvm::X86::isZeroNode(), llvm_unreachable, llvm::ISD::OR, llvm::MVT::Other, llvm::ISD::SDIVREM, llvm::MCID::Select, llvm::MachineSDNode::setMemRefs(), llvm::SDNode::setNodeId(), llvm::ISD::SHL, llvm::MVT::SimpleTy, llvm::ISD::SMUL_LOHI, llvm::ISD::STORE, llvm::X86ISD::SUB, llvm::TargetOpcode::SUBREG_TO_REG, std::swap(), llvm::ISD::TRUNCATE, llvm::ISD::UDIVREM, llvm::X86ISD::UMUL, llvm::ISD::UMUL_LOHI, llvm::SDValue::use_empty(), llvm::Intrinsic::x86_avx2_gather_d_d, llvm::Intrinsic::x86_avx2_gather_d_d_256, llvm::Intrinsic::x86_avx2_gather_d_pd, llvm::Intrinsic::x86_avx2_gather_d_pd_256, llvm::Intrinsic::x86_avx2_gather_d_ps, llvm::Intrinsic::x86_avx2_gather_d_ps_256, llvm::Intrinsic::x86_avx2_gather_d_q, llvm::Intrinsic::x86_avx2_gather_d_q_256, llvm::Intrinsic::x86_avx2_gather_q_d, llvm::Intrinsic::x86_avx2_gather_q_d_256, llvm::Intrinsic::x86_avx2_gather_q_pd, llvm::Intrinsic::x86_avx2_gather_q_pd_256, llvm::Intrinsic::x86_avx2_gather_q_ps, llvm::Intrinsic::x86_avx2_gather_q_ps_256, llvm::Intrinsic::x86_avx2_gather_q_q, llvm::Intrinsic::x86_avx2_gather_q_q_256, and llvm::ISD::XOR.
static bool HasNoSignedComparisonUses (SDNode * N) static
HasNoSignedComparisonUses - Test whether the given X86ISD::CMP node has any uses which require the SF or OF bits to be accurate.
Definition at line 1855 of file X86ISelDAGToDAG.cpp.
References llvm::ISD::CopyToReg, getReg(), llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
Referenced by getFusedLdStOpcode().
static void InsertDAGNode (SelectionDAG & DAG, SDValue Pos, SDValue N) static
Definition at line 762 of file X86ISelDAGToDAG.cpp.
References llvm::SDValue::getNode(), llvm::SDNode::getNodeId(), llvm::SelectionDAG::RepositionNode(), and llvm::SDNode::setNodeId().
Referenced by FoldMaskAndShiftToExtract(), FoldMaskAndShiftToScale(), and FoldMaskedShiftToScaledMask().
static bool isCalleeLoad (SDValue Callee, SDValue & Chain, bool HasCallSeq) static
isCalleeLoad - Return true if call address is a load and it can be moved below CALLSEQ_START and the chains leading up to the call. Return the CALLSEQ_START by reference as a second output. In the case of a tail call, there isn't a callseq node between the call chain and the load.
Definition at line 401 of file X86ISelDAGToDAG.cpp.
References BB, llvm::BuildMI(), llvm::X86ISD::CALL, llvm::X86Subtarget::callRegIndirect(), llvm::ISD::CALLSEQ_START, llvm::dyn_cast(), llvm::ISD::EXTLOAD, llvm::ISD::FP_EXTEND, llvm::ISD::FP_ROUND, llvm::MCInstrInfo::get(), llvm::LSBaseSDNode::getAddressingMode(), llvm::SDNode::getConstantOperandVal(), llvm::LoadSDNode::getExtensionType(), llvm::SDValue::getNode(), llvm::SDValue::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDNode::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getSimpleValueType(), llvm::SDNode::getSimpleValueType(), llvm::SDValue::getValue(), llvm::SDValue::hasOneUse(), I, llvm::X86Subtarget::is64Bit(), llvm::SDValue::isOperandOf(), llvm::X86TargetLowering::isScalarFPTypeInSSEReg(), llvm::X86Subtarget::isTargetCygMing(), llvm::MVT::isVector(), llvm::MemSDNode::isVolatile(), llvm::A64DB::LD, llvm::SPII::Load, MoveBelowOrigChain(), llvm::ISD::NON_EXTLOAD, llvm::CodeGenOpt::None, llvm::Attribute::OptimizeForSize, llvm::Reloc::PIC_, llvm::SPII::Store, llvm::X86ISD::TC_RETURN, TII, llvm::SystemZISD::TM, llvm::ISD::TokenFactor, and llvm::ISD::UNINDEXED.
static bool isDispSafeForFrameIndex (int64_t Val) static
Definition at line 576 of file X86ISelDAGToDAG.cpp.
References llvm::X86II::FS, G, llvm::MachinePointerInfo::getAddrSpace(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::MemSDNode::getPointerInfo(), llvm::X86II::GS, llvm::MVT::i16, llvm::MVT::i64, llvm::X86Subtarget::is64Bit(), llvm::X86::isOffsetSuitableForCodeModel(), llvm::X86Subtarget::isTargetLinux(), llvm::CodeModel::Kernel, llvm_unreachable, M, llvm::X86II::MO_NO_FLAG, S, llvm::CodeModel::Small, llvm::SystemZISD::TM, and llvm::X86ISD::WrapperRIP.
Referenced by FoldMaskAndShiftToScale().
static bool isLoadIncOrDecStore (StoreSDNode * StoreNode, unsigned Opc, SDValue StoredVal, SelectionDAG * CurDAG, LoadSDNode *& LoadNode, SDValue & InputChain) static
isLoadIncOrDecStore - Check whether or not the chain ending in StoreNode is suitable for doing the {load; increment or decrement; store} to modify transformation.
Definition at line 1918 of file X86ISelDAGToDAG.cpp.
References llvm::X86ISD::DEC, llvm::LoadSDNode::getBasePtr(), llvm::StoreSDNode::getBasePtr(), llvm::MemSDNode::getChain(), llvm::MemSDNode::getMemoryVT(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDNode::getNodeId(), llvm::SDValue::getNumOperands(), llvm::LoadSDNode::getOffset(), llvm::StoreSDNode::getOffset(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), llvm::SDNode::getOperand(), llvm::SDValue::getResNo(), llvm::SDValue::getValue(), llvm::SDNode::hasNUsesOfValue(), llvm::SDValue::hasOneUse(), i, llvm::MVT::i16, llvm::MVT::i32, llvm::MVT::i64, llvm::MVT::i8, llvm::X86ISD::INC, llvm::MemSDNode::isNonTemporal(), llvm::ISD::isNormalLoad(), llvm::ISD::isNormalStore(), llvm::SPII::Load, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::ISD::TokenFactor, llvm::SDNode::use_begin(), and llvm::SDNode::use_end().
Referenced by getFusedLdStOpcode().
static void MoveBelowOrigChain (SelectionDAG * CurDAG, SDValue Load, SDValue Call, SDValue OrigChain) static
MoveBelowCallOrigChain - Replace the original chain operand of the call with load's chain operand and move load below the call's chain operand.
Definition at line 362 of file X86ISelDAGToDAG.cpp.
References llvm::SmallVectorImpl< T >::clear(), llvm::SDValue::getNode(), llvm::SelectionDAG::getNode(), llvm::SDValue::getNumOperands(), llvm::SDNode::getNumOperands(), llvm::SDValue::getOpcode(), llvm::SDValue::getOperand(), i, llvm::MVT::Other, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::ISD::TokenFactor, and llvm::SelectionDAG::UpdateNodeOperands().
Referenced by isCalleeLoad().
STATISTIC (NumLoadMoved , "Number of loads moved below TokenFactor")
Variable Documentation
const uint16_t AtomicOpcTbl[AtomicOpcEnd][AtomicSzEnd] static
Definition at line 1608 of file X86ISelDAGToDAG.cpp.