LLVM: X86JITInfo.cpp File Reference
LLVM API Documentation
X86JITInfo.cpp File Reference
#include "X86JITInfo.h"
#include "X86Relocations.h"
#include "X86Subtarget.h"
#include "X86TargetMachine.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/Compiler.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/Valgrind.h"
#include <cstdlib>
#include <cstring>
Macros
#define DEBUG_TYPE "jit"
#define __USER_LABEL_PREFIX__
#define GETASMPREFIX2(X) #X
#define GETASMPREFIX(X) GETASMPREFIX2(X)
#define ASMPREFIX GETASMPREFIX(__USER_LABEL_PREFIX__)
#define SIZE(sym)
#define TYPE_FUNCTION(sym)
#define CFI(x)
Functions
void X86CompilationCallback ()
LLVM_ATTRIBUTE_USED LLVM_LIBRARY_VISIBILITY void LLVMX86CompilationCallback2 (intptr_t *StackPtr, intptr_t RetAddr)
template<typename T >
static void addUnaligned (void *Pos, T Delta)
Variables
static TargetJITInfo::JITCompilerFn JITCompilerFunction
Macro Definition Documentation
#define __USER_LABEL_PREFIX__
Definition at line 54 of file X86JITInfo.cpp.
#define ASMPREFIX GETASMPREFIX(__USER_LABEL_PREFIX__)
Definition at line 58 of file X86JITInfo.cpp.
#define CFI (x)
Definition at line 79 of file X86JITInfo.cpp.
Referenced by llvm::SystemZInstrInfo::expandPostRAPseudo().
#define DEBUG_TYPE "jit"
Definition at line 14 of file X86JITInfo.cpp.
#define GETASMPREFIX (X) GETASMPREFIX2(X)
Definition at line 57 of file X86JITInfo.cpp.
#define GETASMPREFIX2 (X) #X
Definition at line 56 of file X86JITInfo.cpp.
#define SIZE (sym)
Definition at line 66 of file X86JITInfo.cpp.
#define TYPE_FUNCTION (sym)
Definition at line 67 of file X86JITInfo.cpp.
Function Documentation
template<typename T > static void addUnaligned (void * Pos, T Delta) static
Definition at line 530 of file X86JITInfo.cpp.
References llvm::Intrinsic::memcpy.
LLVM_ATTRIBUTE_USED LLVM_LIBRARY_VISIBILITY void LLVMX86CompilationCallback2 (intptr_t * StackPtr, intptr_t RetAddr)
This is the target-specific function invoked by the function stub when we did not know the real target of a call. This function must locate the start of the stub or call site and pass it into the JIT compiler function.
Definition at line 343 of file X86JITInfo.cpp.
References __msan_unpoison, llvm::dbgs(), DEBUG, JITCompilerFunction, and llvm::sys::ValgrindDiscardTranslations().
void X86CompilationCallback ()
Definition at line 331 of file X86JITInfo.cpp.
References LLVM_ATTRIBUTE_USED, and llvm_unreachable.
Referenced by llvm::X86JITInfo::emitFunctionStub(), and llvm::X86JITInfo::getLazyResolverFunction().
Variable Documentation
TargetJITInfo::JITCompilerFn JITCompilerFunction static
JITCompilerFunction - This contains the address of the JIT function used to compile a function lazily.
Definition at line 50 of file X86JITInfo.cpp.
Referenced by llvm::X86JITInfo::getLazyResolverFunction(), and LLVMX86CompilationCallback2().