LLVM: X86MCInstLower.cpp File Reference
LLVM API Documentation
X86MCInstLower.cpp File Reference
#include "X86AsmPrinter.h"
#include "InstPrinter/X86ATTInstPrinter.h"
#include "X86COFFMachineModuleInfo.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/CodeGen/MachineModuleInfoImpls.h"
#include "llvm/CodeGen/StackMaps.h"
#include "llvm/IR/Type.h"
#include "llvm/MC/MCAsmInfo.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstBuilder.h"
#include "llvm/MC/MCStreamer.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/FormattedStream.h"
#include "llvm/Target/Mangler.h"
Functions
static void LowerUnaryToTwoAddr (MCInst &OutMI, unsigned NewOpc)
LowerUnaryToTwoAddr - R = setb -> R = sbb R, R.
static void SimplifyShortImmForm (MCInst &Inst, unsigned Opcode)
Simplify FOO $imm, %{al,ax,eax,rax} to FOO $imm, for instruction with a short fixed-register form.
static void SimplifyMOVSX (MCInst &Inst)
If a movsx instruction has a shorter encoding for the used register simplify the instruction to use it instead.
static void SimplifyShortMoveForm (X86AsmPrinter &Printer, MCInst &Inst, unsigned Opcode)
Simplify things like MOV32rm to MOV32o32a.
static void LowerTlsAddr (MCStreamer &OutStreamer, X86MCInstLower &MCInstLowering, const MachineInstr &MI)
static std::pair< StackMaps::Location, MachineInstr::const_mop_iterator > parseMemoryOperand (StackMaps::Location::LocationType LocTy, unsigned Size, MachineInstr::const_mop_iterator MOI, MachineInstr::const_mop_iterator MOE)
static void LowerSTACKMAP (MCStreamer &OutStreamer, StackMaps &SM, const MachineInstr &MI)
static void LowerPATCHPOINT (MCStreamer &OutStreamer, StackMaps &SM, const MachineInstr &MI)
Function Documentation
static void LowerPATCHPOINT (MCStreamer & OutStreamer, StackMaps & SM, const MachineInstr & MI) static
Definition at line 780 of file X86MCInstLower.cpp.
References llvm::MCStreamer::EmitInstruction(), llvm::MachineOperand::getImm(), llvm::PatchPointOpers::getMetaOper(), llvm::PatchPointOpers::getNextScratchIdx(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), i, llvm::PatchPointOpers::NBytesPos, llvm::StackMaps::recordPatchPoint(), and llvm::PatchPointOpers::TargetPos.
Referenced by llvm::X86AsmPrinter::EmitInstruction().
static void LowerSTACKMAP (MCStreamer & OutStreamer, StackMaps & SM, const MachineInstr & MI) static
Definition at line 764 of file X86MCInstLower.cpp.
References llvm::MCStreamer::EmitInstruction(), llvm::MachineOperand::getImm(), llvm::MachineInstr::getOperand(), i, and llvm::StackMaps::recordStackMap().
Referenced by llvm::X86AsmPrinter::EmitInstruction().
static void LowerTlsAddr (MCStreamer & OutStreamer, X86MCInstLower & MCInstLowering, const MachineInstr & MI) static
Definition at line 599 of file X86MCInstLower.cpp.
References llvm::MCInst::addOperand(), EAX, EBX, llvm::MCStreamer::EmitInstruction(), llvm::MCStreamer::getContext(), llvm::MachineInstr::getOpcode(), llvm::MachineInstr::getOperand(), llvm::MCContext::GetOrCreateSymbol(), llvm_unreachable, and llvm::MCInst::setOpcode().
Referenced by llvm::X86AsmPrinter::EmitInstruction().
static void LowerUnaryToTwoAddr (MCInst & OutMI, unsigned NewOpc) static
LowerUnaryToTwoAddr - R = setb -> R = sbb R, R.
Definition at line 231 of file X86MCInstLower.cpp.
References llvm::MCInst::addOperand(), llvm::MCInst::getOperand(), and llvm::MCInst::setOpcode().
Referenced by SimplifyShortMoveForm().
static std::pair<StackMaps::Location, MachineInstr::const_mop_iterator> parseMemoryOperand (StackMaps::Location::LocationType LocTy, unsigned Size, MachineInstr::const_mop_iterator MOI, MachineInstr::const_mop_iterator MOE) static
Definition at line 679 of file X86MCInstLower.cpp.
References llvm::ISD::Constant, llvm::StackMaps::ConstantOp, llvm::StackMaps::Location::Direct, llvm::StackMaps::DirectMemRefOp, llvm::TargetMachine::getDataLayout(), llvm::MachineOperand::getImm(), llvm::TargetRegisterInfo::getMinimalPhysRegClass(), llvm::DataLayout::getPointerSizeInBits(), llvm::MachineOperand::getReg(), llvm::TargetMachine::getRegisterInfo(), llvm::TargetRegisterClass::getSize(), llvm::MachineOperand::getSubReg(), llvm::StackMaps::Location::Indirect, llvm::StackMaps::IndirectMemRefOp, llvm::MachineOperand::isImm(), llvm::MachineOperand::isImplicit(), llvm::TargetRegisterInfo::isPhysicalRegister(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRegMask(), llvm_unreachable, llvm::next(), Register, and llvm::SystemZISD::TM.
static void SimplifyMOVSX (MCInst & Inst) static
If a movsx instruction has a shorter encoding for the used register simplify the instruction to use it instead.
Definition at line 261 of file X86MCInstLower.cpp.
References llvm::A64CC::AL, EAX, llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm_unreachable, and llvm::MCInst::setOpcode().
Referenced by SimplifyShortMoveForm().
static void SimplifyShortImmForm (MCInst & Inst, unsigned Opcode) static
Simplify FOO $imm, %{al,ax,eax,rax} to FOO $imm, for instruction with a short fixed-register form.
Definition at line 239 of file X86MCInstLower.cpp.
References llvm::MCInst::addOperand(), llvm::A64CC::AL, EAX, llvm::MCInst::getNumOperands(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), and llvm::MCInst::setOpcode().
Referenced by SimplifyShortMoveForm().
static void SimplifyShortMoveForm (X86AsmPrinter & Printer, MCInst & Inst, unsigned Opcode) static
Simplify things like MOV32rm to MOV32o32a.
Definition at line 288 of file X86MCInstLower.cpp.
References llvm::HexagonII::Absolute, llvm::MCInst::addOperand(), llvm::X86::AddrNumOperands, llvm::X86::AddrSegmentReg, llvm::A64CC::AL, llvm::MachineInstr::dump(), EAX, llvm::ISD::EH_RETURN, llvm::MachineOperand::getBlockAddress(), llvm::AsmPrinter::GetBlockAddressSymbol(), llvm::AsmPrinter::GetCPISymbol(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MachineOperand::getImm(), llvm::MachineOperand::getIndex(), llvm::AsmPrinter::GetJTISymbol(), llvm::MCInst::getNumOperands(), llvm::MachineInstr::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MachineInstr::getOpcode(), llvm::MCInst::getOperand(), llvm::MachineInstr::getOperand(), llvm::MCOperand::getReg(), llvm::MachineOperand::getReg(), llvm::X86AsmPrinter::getSubtarget(), GetSymbolFromOperand(), llvm::MachineOperand::getType(), i, llvm::X86Subtarget::is64Bit(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MachineOperand::isImplicit(), llvm::MCOperand::isReg(), llvm::X86II::isX86_64ExtendedReg(), llvm_unreachable, LowerUnaryToTwoAddr(), llvm::A64CC::MI, llvm::MCInst::setOpcode(), SimplifyMOVSX(), and SimplifyShortImmForm().