LLVM: X86MCCodeEmitter.cpp File Reference
LLVM API Documentation
X86MCCodeEmitter.cpp File Reference
#include "MCTargetDesc/X86MCTargetDesc.h"
#include "MCTargetDesc/X86BaseInfo.h"
#include "MCTargetDesc/X86FixupKinds.h"
#include "llvm/MC/MCCodeEmitter.h"
#include "llvm/MC/MCContext.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCRegisterInfo.h"
#include "llvm/MC/MCSubtargetInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/raw_ostream.h"
Macros
#define DEBUG_TYPE "mccodeemitter"
Enumerations
enum GlobalOffsetTableExprKind { GOT_None, GOT_Normal, GOT_SymDiff }
Functions
static bool isDisp8 (int Value)
static bool isCDisp8 (uint64_t TSFlags, int Value, int &CValue)
static MCFixupKind getImmFixupKind (uint64_t TSFlags)
static bool Is32BitMemOperand (const MCInst &MI, unsigned Op)
static bool Is64BitMemOperand (const MCInst &MI, unsigned Op)
static bool Is16BitMemOperand (const MCInst &MI, unsigned Op)
static GlobalOffsetTableExprKind StartsWithGlobalOffsetTable (const MCExpr *Expr)
static bool HasSecRelSymbolRef (const MCExpr *Expr)
static unsigned DetermineREXPrefix (const MCInst &MI, uint64_t TSFlags, const MCInstrDesc &Desc)
Macro Definition Documentation
#define DEBUG_TYPE "mccodeemitter"
Definition at line 14 of file X86MCCodeEmitter.cpp.
Enumeration Type Documentation
enum GlobalOffsetTableExprKind
StartsWithGlobalOffsetTable - Check if this expression starts with GLOBAL_OFFSET_TABLE and if it is of the form GLOBAL_OFFSET_TABLE-symbol. This is needed to support PIC on ELF i386 as GLOBAL_OFFSET_TABLE is magical. We check only simple case that are know to be used: GLOBAL_OFFSET_TABLE by itself or at the start of a binary expression.
Enumerator
GOT_None
GOT_Normal
GOT_SymDiff
Definition at line 268 of file X86MCCodeEmitter.cpp.
Function Documentation
static unsigned DetermineREXPrefix (const MCInst & MI, uint64_t TSFlags, const MCInstrDesc & Desc) static
DetermineREXPrefix - Determine if the MCInst has to be encoded with a X86-64 REX prefix which specifies 1) 64-bit instructions, 2) non-default operand size, and 3) use of X86-64 extended registers.
Definition at line 950 of file X86MCCodeEmitter.cpp.
References llvm::X86II::A6, llvm::X86II::A7, abort(), llvm::X86II::AddRegFrm, llvm::X86::AddrNumOperands, llvm::X86::AddrSegmentReg, llvm::X86II::AdSize, llvm::tgtok::Bit, llvm::MCOperand::CreateImm(), llvm::X86II::D8, llvm::X86II::D9, llvm::X86II::DA, llvm::X86II::DB, llvm::X86II::DC, llvm::X86II::DD, llvm::X86II::DE, llvm::X86II::DF, llvm::MCInst::dump(), llvm::errs(), llvm::X86II::EVEX, llvm::X86II::EVEX_K, llvm::FK_Data_1, llvm::FK_Data_2, llvm::X86II::FormMask, llvm::X86II::FS, llvm::X86II::getBaseOpcodeFor(), llvm::MCOperand::getImm(), getImmFixupKind(), llvm::MCInst::getLoc(), llvm::X86II::getMemoryOperandNo(), llvm::MCInst::getNumOperands(), llvm::MCInstrDesc::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::X86II::getOperandBias(), llvm::MCInstrDesc::getOperandConstraint(), llvm::MCOperand::getReg(), llvm::X86II::getSizeOfImm(), llvm::X86II::GS, llvm::X86II::Has3DNow0F0FOpcode, i, Is16BitMemOperand(), Is32BitMemOperand(), Is64BitMemOperand(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::X86II::isX86_64ExtendedReg(), llvm::X86II::isX86_64NonExtLowByteReg(), llvm_unreachable, llvm::X86II::LOCK, llvm::X86II::MemOp4, llvm::X86II::MRM0m, llvm::X86II::MRM0r, llvm::X86II::MRM1m, llvm::X86II::MRM1r, llvm::X86II::MRM2m, llvm::X86II::MRM2r, llvm::X86II::MRM3m, llvm::X86II::MRM3r, llvm::X86II::MRM4m, llvm::X86II::MRM4r, llvm::X86II::MRM5m, llvm::X86II::MRM5r, llvm::X86II::MRM6m, llvm::X86II::MRM6r, llvm::X86II::MRM7m, llvm::X86II::MRM7r, llvm::X86II::MRM_C1, llvm::X86II::MRM_C2, llvm::X86II::MRM_C3, llvm::X86II::MRM_C4, llvm::X86II::MRM_C8, llvm::X86II::MRM_C9, llvm::X86II::MRM_CA, llvm::X86II::MRM_CB, llvm::X86II::MRM_D0, llvm::X86II::MRM_D1, llvm::X86II::MRM_D4, llvm::X86II::MRM_D5, llvm::X86II::MRM_D6, llvm::X86II::MRM_D8, llvm::X86II::MRM_D9, llvm::X86II::MRM_DA, llvm::X86II::MRM_DB, llvm::X86II::MRM_DC, llvm::X86II::MRM_DD, llvm::X86II::MRM_DE, llvm::X86II::MRM_DF, llvm::X86II::MRM_E8, llvm::X86II::MRM_F0, llvm::X86II::MRM_F8, llvm::X86II::MRM_F9, llvm::X86II::MRMDestMem, llvm::X86II::MRMDestReg, llvm::X86II::MRMInitReg, llvm::X86II::MRMSrcMem, llvm::X86II::MRMSrcReg, llvm::X86II::Op0Mask, llvm::X86II::OpSize, llvm::X86II::Pseudo, llvm::X86II::RawFrm, llvm::X86II::RawFrmImm16, llvm::X86II::RawFrmImm8, llvm::X86::reloc_signed_4byte, llvm::X86II::REP, llvm::X86II::REX_W, llvm::X86II::SegOvrMask, llvm::X86II::T8, llvm::X86II::T8XD, llvm::X86II::T8XS, llvm::X86II::TA, llvm::X86II::TAXD, llvm::X86II::TB, llvm::MCOI::TIED_TO, llvm::MCInstrDesc::TSFlags, llvm::X86II::VEX, llvm::X86II::VEX_4V, llvm::X86II::VEX_4VOp3, llvm::X86II::VEX_I8IMM, llvm::X86II::VEXShift, llvm::X86II::XD, and llvm::X86II::XS.
static MCFixupKind getImmFixupKind (uint64_t TSFlags) static
getImmFixupKind - Return the appropriate fixup kind to use for an immediate in an instruction with the specified TSFlags.
Definition at line 211 of file X86MCCodeEmitter.cpp.
References llvm::MCFixup::getKindForSize(), llvm::X86II::getSizeOfImm(), and llvm::X86II::isImmPCRel().
Referenced by DetermineREXPrefix().
static bool HasSecRelSymbolRef (const MCExpr * Expr) static
Definition at line 294 of file X86MCCodeEmitter.cpp.
References llvm::X86::AddrBaseReg, llvm::X86::AddrDisp, llvm::X86::AddrIndexReg, llvm::X86::AddrNumOperands, llvm::X86::AddrScaleAmt, llvm::MCExpr::Binary, llvm::MCFixup::Create(), llvm::MCConstantExpr::Create(), llvm::MCBinaryExpr::CreateAdd(), llvm::N86::EBP, llvm::N86::ESP, llvm::X86II::EVEX, llvm::X86II::EVEX_B, llvm::X86II::EVEX_K, llvm::X86II::EVEX_L2, llvm::X86II::EVEX_Z, llvm::FK_Data_1, llvm::FK_Data_4, llvm::FK_Data_8, llvm::FK_PCRel_1, llvm::FK_PCRel_2, llvm::FK_PCRel_4, llvm::FK_SecRel_4, llvm::X86II::FormMask, llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCExpr::getKind(), llvm::MCSymbolRefExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCInst::getLoc(), llvm::MCInstrDesc::getNumOperands(), llvm::MCInst::getOpcode(), llvm::MCInst::getOperand(), llvm::MCInstrDesc::getOperandConstraint(), llvm::MCOperand::getReg(), llvm::MCBinaryExpr::getRHS(), llvm::X86II::getSizeOfImm(), GOT_None, GOT_Normal, llvm::X86II::hasImm(), llvm::X86II::is32ExtendedReg(), isCDisp8(), isDisp8(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::X86II::isX86_64ExtendedReg(), llvm_unreachable, llvm::X86II::MemOp4, llvm::A64CC::MI, ModRMByte(), llvm::X86II::MRM0m, llvm::X86II::MRM0r, llvm::X86II::MRM1m, llvm::X86II::MRM1r, llvm::X86II::MRM2m, llvm::X86II::MRM2r, llvm::X86II::MRM3m, llvm::X86II::MRM3r, llvm::X86II::MRM4m, llvm::X86II::MRM4r, llvm::X86II::MRM5m, llvm::X86II::MRM5r, llvm::X86II::MRM6m, llvm::X86II::MRM6r, llvm::X86II::MRM7m, llvm::X86II::MRM7r, llvm::X86II::MRMDestMem, llvm::X86II::MRMDestReg, llvm::X86II::MRMInitReg, llvm::X86II::MRMSrcMem, llvm::X86II::MRMSrcReg, llvm::X86II::Op0Mask, llvm::X86II::OpSize, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::X86::reloc_global_offset_table, llvm::X86::reloc_riprel_4byte, llvm::X86::reloc_riprel_4byte_movq_load, llvm::X86::reloc_signed_4byte, StartsWithGlobalOffsetTable(), llvm::MCExpr::SymbolRef, llvm::X86II::T8, llvm::X86II::T8XD, llvm::X86II::T8XS, llvm::X86II::TA, llvm::X86II::TAXD, llvm::X86II::TB, llvm::MCOI::TIED_TO, llvm::X86II::VEX_4V, llvm::X86II::VEX_4VOp3, llvm::X86II::VEX_L, llvm::X86II::VEX_W, llvm::X86II::VEXShift, llvm::MCSymbolRefExpr::VK_SECREL, x3, llvm::X86II::XD, llvm::X86II::XOP, llvm::X86II::XOP8, llvm::X86II::XOP9, llvm::X86II::XOPA, and llvm::X86II::XS.
static bool Is16BitMemOperand (const MCInst & MI, unsigned Op) static
Is16BitMemOperand - Return true if the specified instruction has a 16-bit memory operand. Op specifies the operand # of the memoperand.
Definition at line 250 of file X86MCCodeEmitter.cpp.
References llvm::X86::AddrBaseReg, llvm::X86::AddrIndexReg, llvm::MCInst::getOperand(), and llvm::MCOperand::getReg().
Referenced by DetermineREXPrefix().
static bool Is32BitMemOperand (const MCInst & MI, unsigned Op) static
Is32BitMemOperand - Return true if the specified instruction has a 32-bit memory operand. Op specifies the operand # of the memoperand.
Definition at line 220 of file X86MCCodeEmitter.cpp.
References llvm::X86::AddrBaseReg, llvm::X86::AddrIndexReg, llvm::MCInst::getOperand(), and llvm::MCOperand::getReg().
Referenced by DetermineREXPrefix().
static bool Is64BitMemOperand (const MCInst & MI, unsigned Op) static
Is64BitMemOperand - Return true if the specified instruction has a 64-bit memory operand. Op specifies the operand # of the memoperand.
Definition at line 235 of file X86MCCodeEmitter.cpp.
References llvm::X86::AddrBaseReg, llvm::X86::AddrIndexReg, llvm::MCInst::getOperand(), and llvm::MCOperand::getReg().
Referenced by DetermineREXPrefix().
static bool isCDisp8 (uint64_t TSFlags, int Value, int & CValue) static
isCDisp8 - Return true if this signed displacement fits in a 8-bit compressed dispacement field.
Definition at line 165 of file X86MCCodeEmitter.cpp.
References llvm::X86II::EVEX, llvm::X86II::EVEX_B, llvm::X86II::EVEX_CD8EMask, llvm::X86II::EVEX_CD8EShift, llvm::X86II::EVEX_CD8VMask, llvm::X86II::EVEX_CD8VShift, llvm::X86II::EVEX_L2, isDisp8(), llvm::AArch64ISD::Ret, llvm::X86II::VEX_L, and llvm::X86II::VEXShift.
Referenced by HasSecRelSymbolRef().
static bool isDisp8 (int Value) static
isDisp8 - Return true if this signed displacement fits in a 8-bit sign-extended field.
Definition at line 159 of file X86MCCodeEmitter.cpp.
Referenced by HasSecRelSymbolRef(), and isCDisp8().
static GlobalOffsetTableExprKind StartsWithGlobalOffsetTable (const MCExpr * Expr) static
Definition at line 274 of file X86MCCodeEmitter.cpp.
References llvm::MCExpr::Binary, llvm::MCExpr::getKind(), llvm::MCBinaryExpr::getLHS(), llvm::MCSymbol::getName(), llvm::MCBinaryExpr::getRHS(), llvm::MCSymbolRefExpr::getSymbol(), GOT_None, GOT_Normal, GOT_SymDiff, S, and llvm::MCExpr::SymbolRef.
Referenced by HasSecRelSymbolRef().