LLVM: X86VZeroUpper.cpp File Reference
LLVM API Documentation
X86VZeroUpper.cpp File Reference
#include "X86.h"
#include "X86InstrInfo.h"
#include "llvm/ADT/Statistic.h"
#include "llvm/CodeGen/MachineFunctionPass.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/Passes.h"
#include "llvm/Support/Debug.h"
#include "llvm/Support/raw_ostream.h"
#include "llvm/Target/TargetInstrInfo.h"
Macros
#define DEBUG_TYPE "x86-vzeroupper"
Functions
STATISTIC (NumVZU,"Number of vzeroupper instructions inserted")
static bool isYmmReg (unsigned Reg)
static bool isZmmReg (unsigned Reg)
static bool checkFnHasLiveInYmm (MachineRegisterInfo &MRI)
static bool clobbersAllYmmRegs (const MachineOperand &MO)
static bool hasYmmReg (MachineInstr *MI)
static bool clobbersAnyYmmReg (MachineInstr *MI)
Macro Definition Documentation
#define DEBUG_TYPE "x86-vzeroupper"
Definition at line 17 of file X86VZeroUpper.cpp.
Function Documentation
static bool checkFnHasLiveInYmm (MachineRegisterInfo & MRI) static
Definition at line 115 of file X86VZeroUpper.cpp.
References I, isYmmReg(), isZmmReg(), llvm::MachineRegisterInfo::livein_begin(), and llvm::MachineRegisterInfo::livein_end().
Referenced by clobbersAnyYmmReg().
static bool clobbersAllYmmRegs (const MachineOperand & MO) static
Definition at line 124 of file X86VZeroUpper.cpp.
References llvm::MachineOperand::clobbersPhysReg().
Referenced by hasYmmReg().
static bool clobbersAnyYmmReg (MachineInstr * MI) static
clobbersAnyYmmReg() - Check if any YMM register will be clobbered by this instruction.
Definition at line 153 of file X86VZeroUpper.cpp.
References BB, llvm::TargetRegisterClass::begin(), llvm::MachineBasicBlock::begin(), llvm::MachineFunction::begin(), llvm::BuildMI(), checkFnHasLiveInYmm(), llvm::BitVector::clear(), llvm::SmallVectorImpl< T >::clear(), llvm::MachineOperand::clobbersPhysReg(), llvm::dbgs(), DEBUG, llvm::SmallVectorBase::empty(), llvm::TargetRegisterClass::end(), llvm::MachineBasicBlock::end(), llvm::MachineFunction::end(), llvm::MCInstrInfo::get(), llvm::TargetMachine::getInstrInfo(), llvm::MachineBasicBlock::getNumber(), llvm::MachineFunction::getNumBlockIDs(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineFunction::getRegInfo(), llvm::MachineFunction::getTarget(), hasYmmReg(), i, I, llvm::MachineInstr::isCall(), llvm::MachineOperand::isRegMask(), llvm::MachineInstr::isReturn(), llvm::A64CC::MI, MRI, llvm::MachineBasicBlock::pred_begin(), llvm::MachineBasicBlock::pred_end(), llvm::MachineRegisterInfo::reg_nodbg_empty(), llvm::BitVector::resize(), and llvm::SmallVectorImpl< T >::resize().
static bool hasYmmReg (MachineInstr * MI) static
Definition at line 136 of file X86VZeroUpper.cpp.
References clobbersAllYmmRegs(), llvm::MachineInstr::getNumOperands(), llvm::MachineInstr::getOperand(), llvm::MachineOperand::getReg(), i, llvm::MachineInstr::isCall(), llvm::MachineOperand::isDebug(), llvm::MachineOperand::isReg(), llvm::MachineOperand::isRegMask(), and isYmmReg().
Referenced by clobbersAnyYmmReg().
static bool isYmmReg (unsigned Reg) static
Definition at line 107 of file X86VZeroUpper.cpp.
Referenced by checkFnHasLiveInYmm(), and hasYmmReg().
static bool isZmmReg (unsigned Reg) static
Definition at line 111 of file X86VZeroUpper.cpp.
Referenced by checkFnHasLiveInYmm().
STATISTIC (NumVZU , "Number of vzeroupper instructions inserted")