LLVM: XCoreLowerThreadLocal.cpp File Reference
LLVM API Documentation
XCoreLowerThreadLocal.cpp File Reference
This file contains a pass that lowers thread local variables on the XCore.
#include "XCore.h"
#include "llvm/IR/Constants.h"
#include "llvm/IR/DerivedTypes.h"
#include "llvm/IR/GlobalVariable.h"
#include "llvm/IR/Intrinsics.h"
#include "llvm/IR/IRBuilder.h"
#include "llvm/IR/Module.h"
#include "llvm/Pass.h"
#include "llvm/Support/CommandLine.h"
#include "llvm/Support/NoFolder.h"
#include "llvm/Support/ValueHandle.h"
#include "llvm/Transforms/Utils/BasicBlockUtils.h"
Macros
#define DEBUG_TYPE "xcore-lower-thread-local"
Functions
INITIALIZE_PASS (XCoreLowerThreadLocal,"xcore-lower-thread-local","Lower thread local variables", false, false) ModulePass *llvm
static ArrayType * createLoweredType (Type *OriginalType)
static Constant * createLoweredInitializer (ArrayType *NewType, Constant *OriginalInitializer)
static Instruction * createReplacementInstr (ConstantExpr *CE, Instruction *Instr)
static bool replaceConstantExprOp (ConstantExpr *CE, Pass *P)
static bool rewriteNonInstructionUses (GlobalVariable *GV, Pass *P)
static bool isZeroLengthArray (Type *Ty)
Variables
static cl::opt< unsigned > MaxThreads ("xcore-max-threads", cl::Optional, cl::desc("Maximum number of threads (for emulation thread-local storage)"), cl::Hidden, cl::value_desc("number"), cl::init(8))
Detailed Description
This file contains a pass that lowers thread local variables on the XCore.
Definition in file XCoreLowerThreadLocal.cpp.
Macro Definition Documentation
#define DEBUG_TYPE "xcore-lower-thread-local"
Definition at line 29 of file XCoreLowerThreadLocal.cpp.
Function Documentation
static Constant* createLoweredInitializer (ArrayType * NewType, Constant * OriginalInitializer) static
Definition at line 69 of file XCoreLowerThreadLocal.cpp.
References llvm::ConstantArray::get(), i, and MaxThreads.
Referenced by isZeroLengthArray().
static ArrayType* createLoweredType (Type * OriginalType) static
Definition at line 64 of file XCoreLowerThreadLocal.cpp.
References llvm::ArrayType::get(), and MaxThreads.
Referenced by isZeroLengthArray().
static Instruction* createReplacementInstr (ConstantExpr * CE, Instruction * Instr) static
Definition at line 78 of file XCoreLowerThreadLocal.cpp.
References llvm::APIntOps::And(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateBinOp(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateCast(), llvm::IRBuilder< preserveNames, T, Inserter >::CreateInBoundsGEP(), llvm::dyn_cast(), llvm::Value::getName(), llvm::ConstantExpr::getOpcode(), llvm::User::getOperand(), llvm::Value::getType(), llvm_unreachable, llvm::User::op_begin(), llvm::User::op_end(), llvm::APIntOps::Or(), and llvm::APIntOps::Xor().
Referenced by replaceConstantExprOp().
INITIALIZE_PASS (XCoreLowerThreadLocal , "xcore-lower-thread-local" , "Lower thread local variables" , false , false)
Definition at line 57 of file XCoreLowerThreadLocal.cpp.
static bool isZeroLengthArray (Type * Ty) static
Definition at line 177 of file XCoreLowerThreadLocal.cpp.
References createLoweredInitializer(), createLoweredType(), llvm::dyn_cast(), llvm::GlobalVariable::eraseFromParent(), llvm::PointerType::getAddressSpace(), llvm::Module::getContext(), llvm::Intrinsic::getDeclaration(), llvm::SequentialType::getElementType(), llvm::GlobalVariable::getInitializer(), llvm::Type::getInt64Ty(), llvm::GlobalValue::getLinkage(), llvm::Constant::getNullValue(), llvm::ArrayType::getNumElements(), llvm::GlobalValue::getParent(), llvm::GlobalValue::getType(), llvm::Module::global_begin(), llvm::Module::global_end(), llvm::GlobalVariable::hasInitializer(), I, llvm::GlobalVariable::isConstant(), llvm::GlobalVariable::isExternallyInitialized(), llvm::Type::isSized(), llvm::GlobalVariable::isThreadLocal(), M, llvm::GlobalVariable::NotThreadLocal, llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::User::replaceUsesOfWith(), rewriteNonInstructionUses(), llvm::SmallVectorTemplateCommon< T >::size(), llvm::Value::takeName(), llvm::Value::use_begin(), llvm::Value::use_end(), Users, and llvm::Intrinsic::xcore_getid.
static bool replaceConstantExprOp (ConstantExpr * CE, Pass * P) static
Definition at line 128 of file XCoreLowerThreadLocal.cpp.
References llvm::SmallVectorTemplateCommon< T >::begin(), createReplacementInstr(), llvm::ConstantExpr::destroyConstant(), llvm::dyn_cast(), llvm::SmallVectorBase::empty(), llvm::SmallVectorTemplateCommon< T >::end(), llvm::SmallVectorImpl< T >::erase(), llvm::TerminatorInst::getNumSuccessors(), llvm::BasicBlock::getParent(), llvm::BasicBlock::getTerminator(), llvm::Value::hasNUsesOrMore(), I, P, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), llvm::SplitEdge(), llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by rewriteNonInstructionUses().
static bool rewriteNonInstructionUses (GlobalVariable * GV, Pass * P) static
Definition at line 163 of file XCoreLowerThreadLocal.cpp.
References llvm::dyn_cast(), llvm::SmallVectorBase::empty(), I, llvm::SmallVectorImpl< T >::pop_back_val(), llvm::SmallVectorTemplateBase< T, isPodLike< T >::value >::push_back(), replaceConstantExprOp(), llvm::Value::use_begin(), and llvm::Value::use_end().
Referenced by isZeroLengthArray().
Variable Documentation
cl::opt<unsigned> MaxThreads("xcore-max-threads", cl::Optional, cl::desc("Maximum number of threads (for emulation thread-local storage)"), cl::Hidden, cl::value_desc("number"), cl::init(8)) static
Referenced by createLoweredInitializer(), and createLoweredType().