LLVM: XCoreFrameLowering.cpp File Reference
LLVM API Documentation
XCoreFrameLowering.cpp File Reference
#include "XCoreFrameLowering.h"
#include "XCore.h"
#include "XCoreInstrInfo.h"
#include "XCoreMachineFunctionInfo.h"
#include "llvm/CodeGen/MachineFrameInfo.h"
#include "llvm/CodeGen/MachineFunction.h"
#include "llvm/CodeGen/MachineInstrBuilder.h"
#include "llvm/CodeGen/MachineModuleInfo.h"
#include "llvm/CodeGen/MachineRegisterInfo.h"
#include "llvm/CodeGen/RegisterScavenging.h"
#include "llvm/IR/DataLayout.h"
#include "llvm/IR/Function.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Target/TargetOptions.h"
Functions
static bool isImmU6 (unsigned val)
static bool isImmU16 (unsigned val)
static void loadFromStack (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, unsigned DstReg, int Offset, DebugLoc dl, const TargetInstrInfo &TII)
static void storeToStack (MachineBasicBlock &MBB, MachineBasicBlock::iterator I, unsigned SrcReg, int Offset, DebugLoc dl, const TargetInstrInfo &TII)
Function Documentation
static bool isImmU16 (unsigned val) inline static
Definition at line 37 of file XCoreFrameLowering.cpp.
Referenced by llvm::XCoreFrameLowering::eliminateCallFramePseudoInstr(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitPrologue(), loadFromStack(), and storeToStack().
static bool isImmU6 (unsigned val) inline static
Definition at line 33 of file XCoreFrameLowering.cpp.
Referenced by llvm::XCoreFrameLowering::eliminateCallFramePseudoInstr(), llvm::XCoreFrameLowering::emitEpilogue(), llvm::XCoreFrameLowering::emitPrologue(), loadFromStack(), and storeToStack().
static void loadFromStack (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, unsigned DstReg, int Offset, DebugLoc dl, const TargetInstrInfo & TII) static
Definition at line 41 of file XCoreFrameLowering.cpp.
References llvm::BuildMI(), llvm::MCInstrInfo::get(), isImmU16(), isImmU6(), and llvm::report_fatal_error().
Referenced by llvm::XCoreFrameLowering::emitEpilogue(), and llvm::XCoreFrameLowering::emitPrologue().
static void storeToStack (MachineBasicBlock & MBB, MachineBasicBlock::iterator I, unsigned SrcReg, int Offset, DebugLoc dl, const TargetInstrInfo & TII) static
Definition at line 56 of file XCoreFrameLowering.cpp.
References llvm::MachineInstrBuilder::addImm(), llvm::BuildMI(), llvm::MCInstrInfo::get(), isImmU16(), isImmU6(), and llvm::report_fatal_error().
Referenced by llvm::XCoreFrameLowering::emitPrologue().