LLVM: XCoreInstPrinter.cpp File Reference
LLVM API Documentation
XCoreInstPrinter.cpp File Reference
#include "XCoreInstPrinter.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/MC/MCExpr.h"
#include "llvm/MC/MCInst.h"
#include "llvm/MC/MCInstrInfo.h"
#include "llvm/MC/MCSymbol.h"
#include "llvm/Support/ErrorHandling.h"
#include "llvm/Support/raw_ostream.h"
#include "XCoreGenAsmWriter.inc"
Macros
#define DEBUG_TYPE "asm-printer"
Functions
static void printExpr (const MCExpr *Expr, raw_ostream &OS)
Macro Definition Documentation
#define DEBUG_TYPE "asm-printer"
Definition at line 14 of file XCoreInstPrinter.cpp.
Function Documentation
static void printExpr (const MCExpr * Expr, raw_ostream & OS) static
Definition at line 47 of file XCoreInstPrinter.cpp.
References llvm::dyn_cast(), llvm::MCOperand::getExpr(), llvm::MCOperand::getImm(), llvm::MCSymbolRefExpr::getKind(), llvm::MCInst::getOperand(), llvm::MCOperand::getReg(), llvm::MCSymbolRefExpr::getSymbol(), llvm::MCOperand::isExpr(), llvm::MCOperand::isImm(), llvm::MCOperand::isReg(), llvm::XCoreInstPrinter::printRegName(), and llvm::MCSymbolRefExpr::VK_None.