var searchData=
[
  ['callbackvh',['CallbackVH',['../classllvm_1_1CallbackVH.html',1,'llvm']]],
  ['calleesavedinfo',['CalleeSavedInfo',['../classllvm_1_1CalleeSavedInfo.html',1,'llvm']]],
  ['callgraph',['CallGraph',['../classllvm_1_1CallGraph.html',1,'llvm']]],
  ['callgraphnode',['CallGraphNode',['../classllvm_1_1CallGraphNode.html',1,'llvm']]],
  ['callgraphscc',['CallGraphSCC',['../classllvm_1_1CallGraphSCC.html',1,'llvm']]],
  ['callgraphsccpass',['CallGraphSCCPass',['../classllvm_1_1CallGraphSCCPass.html',1,'llvm']]],
  ['callinst',['CallInst',['../classllvm_1_1CallInst.html',1,'llvm']]],
  ['callloweringinfo',['CallLoweringInfo',['../structllvm_1_1TargetLowering_1_1CallLoweringInfo.html',1,'llvm::TargetLowering']]],
  ['callsite',['CallSite',['../classllvm_1_1CallSite.html',1,'llvm']]],
  ['callsitebase',['CallSiteBase',['../classllvm_1_1CallSiteBase.html',1,'llvm']]],
  ['callsitebase_3c_20function_2c_20value_2c_20user_2c_20instruction_2c_20callinst_2c_20invokeinst_2c_20user_3a_3aop_5fiterator_20_3e',['CallSiteBase&lt; Function, Value, User, Instruction, CallInst, InvokeInst, User::op_iterator &gt;',['../classllvm_1_1CallSiteBase.html',1,'llvm']]],
  ['callsitebase_3c_3e',['CallSiteBase&lt;&gt;',['../classllvm_1_1CallSiteBase.html',1,'llvm']]],
  ['callsiteentry',['CallSiteEntry',['../structllvm_1_1DwarfException_1_1CallSiteEntry.html',1,'llvm::DwarfException']]],
  ['capacity',['Capacity',['../classllvm_1_1ArrayRecycler_1_1Capacity.html',1,'llvm::ArrayRecycler']]],
  ['capturetracker',['CaptureTracker',['../structllvm_1_1CaptureTracker.html',1,'llvm']]],
  ['caseit',['CaseIt',['../classllvm_1_1SwitchInst_1_1CaseIt.html',1,'llvm::SwitchInst']]],
  ['caseiteratort',['CaseIteratorT',['../classllvm_1_1SwitchInst_1_1CaseIteratorT.html',1,'llvm::SwitchInst']]],
  ['caseiteratort_3c_20switchinst_2c_20constantint_2c_20basicblock_20_3e',['CaseIteratorT&lt; SwitchInst, ConstantInt, BasicBlock &gt;',['../classllvm_1_1SwitchInst_1_1CaseIteratorT.html',1,'llvm::SwitchInst']]],
  ['cast_5fconvert_5fval',['cast_convert_val',['../structllvm_1_1cast__convert__val.html',1,'llvm']]],
  ['cast_5fconvert_5fval_3c_20to_2c_20fromty_2c_20fromty_20_3e',['cast_convert_val&lt; To, FromTy, FromTy &gt;',['../structllvm_1_1cast__convert__val_3_01To_00_01FromTy_00_01FromTy_01_4.html',1,'llvm']]],
  ['cast_5fretty',['cast_retty',['../structllvm_1_1cast__retty.html',1,'llvm']]],
  ['cast_5fretty_5fimpl',['cast_retty_impl',['../structllvm_1_1cast__retty__impl.html',1,'llvm']]],
  ['cast_5fretty_5fimpl_3c_20to_2c_20const_20from_20_2a_20_3e',['cast_retty_impl&lt; To, const From * &gt;',['../structllvm_1_1cast__retty__impl_3_01To_00_01const_01From_01_5_01_4.html',1,'llvm']]],
  ['cast_5fretty_5fimpl_3c_20to_2c_20const_20from_20_2aconst_20_20_3e',['cast_retty_impl&lt; To, const From *const  &gt;',['../structllvm_1_1cast__retty__impl_3_01To_00_01const_01From_01_5const_01_01_4.html',1,'llvm']]],
  ['cast_5fretty_5fimpl_3c_20to_2c_20const_20from_20_3e',['cast_retty_impl&lt; To, const From &gt;',['../structllvm_1_1cast__retty__impl_3_01To_00_01const_01From_01_4.html',1,'llvm']]],
  ['cast_5fretty_5fimpl_3c_20to_2c_20from_20_2a_20_3e',['cast_retty_impl&lt; To, From * &gt;',['../structllvm_1_1cast__retty__impl_3_01To_00_01From_01_5_01_4.html',1,'llvm']]],
  ['cast_5fretty_5fwrap',['cast_retty_wrap',['../structllvm_1_1cast__retty__wrap.html',1,'llvm']]],
  ['cast_5fretty_5fwrap_3c_20to_2c_20fromty_2c_20fromty_20_3e',['cast_retty_wrap&lt; To, FromTy, FromTy &gt;',['../structllvm_1_1cast__retty__wrap_3_01To_00_01FromTy_00_01FromTy_01_4.html',1,'llvm']]],
  ['castclass_5fmatch',['CastClass_match',['../structllvm_1_1PatternMatch_1_1CastClass__match.html',1,'llvm::PatternMatch']]],
  ['castinst',['CastInst',['../classllvm_1_1CastInst.html',1,'llvm']]],
  ['cat',['cat',['../structllvm_1_1cl_1_1cat.html',1,'llvm::cl']]],
  ['cclass',['cclass',['../structcclass.html',1,'']]],
  ['ccstate',['CCState',['../classllvm_1_1CCState.html',1,'llvm']]],
  ['ccvalassign',['CCValAssign',['../classllvm_1_1CCValAssign.html',1,'llvm']]],
  ['child',['Child',['../classllvm_1_1object_1_1Archive_1_1Child.html',1,'llvm::object::Archive']]],
  ['child_5fiterator',['child_iterator',['../classllvm_1_1object_1_1Archive_1_1child__iterator.html',1,'llvm::object::Archive']]],
  ['circular_5fraw_5fostream',['circular_raw_ostream',['../classllvm_1_1circular__raw__ostream.html',1,'llvm']]],
  ['class_5fmatch',['class_match',['../structllvm_1_1PatternMatch_1_1class__match.html',1,'llvm::PatternMatch']]],
  ['clonedcodeinfo',['ClonedCodeInfo',['../structllvm_1_1ClonedCodeInfo.html',1,'llvm']]],
  ['cmpclass_5fmatch',['CmpClass_match',['../structllvm_1_1PatternMatch_1_1CmpClass__match.html',1,'llvm::PatternMatch']]],
  ['cmpinst',['CmpInst',['../classllvm_1_1CmpInst.html',1,'llvm']]],
  ['cname',['cname',['../structcname.html',1,'']]],
  ['coalescerpair',['CoalescerPair',['../classllvm_1_1CoalescerPair.html',1,'llvm']]],
  ['codeextractor',['CodeExtractor',['../classllvm_1_1CodeExtractor.html',1,'llvm']]],
  ['codemetrics',['CodeMetrics',['../structllvm_1_1CodeMetrics.html',1,'llvm']]],
  ['coff_5faux_5fsection_5fdefinition',['coff_aux_section_definition',['../structllvm_1_1object_1_1coff__aux__section__definition.html',1,'llvm::object']]],
  ['coff_5faux_5fweak_5fexternal',['coff_aux_weak_external',['../structllvm_1_1object_1_1coff__aux__weak__external.html',1,'llvm::object']]],
  ['coff_5ffile_5fheader',['coff_file_header',['../structllvm_1_1object_1_1coff__file__header.html',1,'llvm::object']]],
  ['coff_5frelocation',['coff_relocation',['../structllvm_1_1object_1_1coff__relocation.html',1,'llvm::object']]],
  ['coff_5fsection',['coff_section',['../structllvm_1_1object_1_1coff__section.html',1,'llvm::object']]],
  ['coff_5fsymbol',['coff_symbol',['../structllvm_1_1object_1_1coff__symbol.html',1,'llvm::object']]],
  ['coffobjectfile',['COFFObjectFile',['../classllvm_1_1object_1_1COFFObjectFile.html',1,'llvm::object']]],
  ['commonhandletraits',['CommonHandleTraits',['../structCommonHandleTraits.html',1,'']]],
  ['compareconstantexpr',['CompareConstantExpr',['../classllvm_1_1CompareConstantExpr.html',1,'llvm']]],
  ['comparerawbits',['compareRawBits',['../structllvm_1_1EVT_1_1compareRawBits.html',1,'llvm::EVT']]],
  ['compileunit',['CompileUnit',['../classllvm_1_1CompileUnit.html',1,'llvm']]],
  ['compositetype',['CompositeType',['../classllvm_1_1CompositeType.html',1,'llvm']]],
  ['concreteoperator',['ConcreteOperator',['../classllvm_1_1ConcreteOperator.html',1,'llvm']]],
  ['concreteoperator_3c_20operator_2c_20instruction_3a_3agetelementptr_20_3e',['ConcreteOperator&lt; Operator, Instruction::GetElementPtr &gt;',['../classllvm_1_1ConcreteOperator.html',1,'llvm']]],
  ['concreteoperator_3c_20overflowingbinaryoperator_2c_20instruction_3a_3aadd_20_3e',['ConcreteOperator&lt; OverflowingBinaryOperator, Instruction::Add &gt;',['../classllvm_1_1ConcreteOperator.html',1,'llvm']]],
  ['concreteoperator_3c_20overflowingbinaryoperator_2c_20instruction_3a_3amul_20_3e',['ConcreteOperator&lt; OverflowingBinaryOperator, Instruction::Mul &gt;',['../classllvm_1_1ConcreteOperator.html',1,'llvm']]],
  ['concreteoperator_3c_20overflowingbinaryoperator_2c_20instruction_3a_3ashl_20_3e',['ConcreteOperator&lt; OverflowingBinaryOperator, Instruction::Shl &gt;',['../classllvm_1_1ConcreteOperator.html',1,'llvm']]],
  ['concreteoperator_3c_20overflowingbinaryoperator_2c_20instruction_3a_3asub_20_3e',['ConcreteOperator&lt; OverflowingBinaryOperator, Instruction::Sub &gt;',['../classllvm_1_1ConcreteOperator.html',1,'llvm']]],
  ['concreteoperator_3c_20possiblyexactoperator_2c_20instruction_3a_3aashr_20_3e',['ConcreteOperator&lt; PossiblyExactOperator, Instruction::AShr &gt;',['../classllvm_1_1ConcreteOperator.html',1,'llvm']]],
  ['concreteoperator_3c_20possiblyexactoperator_2c_20instruction_3a_3alshr_20_3e',['ConcreteOperator&lt; PossiblyExactOperator, Instruction::LShr &gt;',['../classllvm_1_1ConcreteOperator.html',1,'llvm']]],
  ['concreteoperator_3c_20possiblyexactoperator_2c_20instruction_3a_3asdiv_20_3e',['ConcreteOperator&lt; PossiblyExactOperator, Instruction::SDiv &gt;',['../classllvm_1_1ConcreteOperator.html',1,'llvm']]],
  ['concreteoperator_3c_20possiblyexactoperator_2c_20instruction_3a_3audiv_20_3e',['ConcreteOperator&lt; PossiblyExactOperator, Instruction::UDiv &gt;',['../classllvm_1_1ConcreteOperator.html',1,'llvm']]],
  ['condcodesdnode',['CondCodeSDNode',['../classllvm_1_1CondCodeSDNode.html',1,'llvm']]],
  ['conditional',['conditional',['../structllvm_1_1conditional.html',1,'llvm']]],
  ['conditional_3c_20elft_3a_3ais64bits_2c_20uint64_5ft_2c_20uint32_5ft_20_3e',['conditional&lt; ELFT::Is64Bits, uint64_t, uint32_t &gt;',['../structllvm_1_1conditional.html',1,'llvm']]],
  ['conditional_3c_20false_2c_20t_2c_20f_20_3e',['conditional&lt; false, T, F &gt;',['../structllvm_1_1conditional_3_01false_00_01T_00_01F_01_4.html',1,'llvm']]],
  ['connectedvninfoeqclasses',['ConnectedVNInfoEqClasses',['../classllvm_1_1ConnectedVNInfoEqClasses.html',1,'llvm']]],
  ['consecutivememorychainsorter',['ConsecutiveMemoryChainSorter',['../structConsecutiveMemoryChainSorter.html',1,'']]],
  ['const_5fiterator',['const_iterator',['../classllvm_1_1sys_1_1path_1_1const__iterator.html',1,'llvm::sys::path']]],
  ['const_5fiterator',['const_iterator',['../classllvm_1_1IntervalMap_1_1const__iterator.html',1,'llvm::IntervalMap']]],
  ['constant',['Constant',['../classllvm_1_1Constant.html',1,'llvm']]],
  ['constant_5fiterator',['constant_iterator',['../classllvm_1_1constant__iterator.html',1,'llvm']]],
  ['constantaggregatezero',['ConstantAggregateZero',['../classllvm_1_1ConstantAggregateZero.html',1,'llvm']]],
  ['constantaggruniquemap',['ConstantAggrUniqueMap',['../classllvm_1_1ConstantAggrUniqueMap.html',1,'llvm']]],
  ['constantaggruniquemap_3c_20arraytype_2c_20constantarray_20_3e',['ConstantAggrUniqueMap&lt; ArrayType, ConstantArray &gt;',['../classllvm_1_1ConstantAggrUniqueMap.html',1,'llvm']]],
  ['constantaggruniquemap_3c_20structtype_2c_20constantstruct_20_3e',['ConstantAggrUniqueMap&lt; StructType, ConstantStruct &gt;',['../classllvm_1_1ConstantAggrUniqueMap.html',1,'llvm']]],
  ['constantaggruniquemap_3c_20vectortype_2c_20constantvector_20_3e',['ConstantAggrUniqueMap&lt; VectorType, ConstantVector &gt;',['../classllvm_1_1ConstantAggrUniqueMap.html',1,'llvm']]],
  ['constantarray',['ConstantArray',['../classllvm_1_1ConstantArray.html',1,'llvm']]],
  ['constantarraycreator',['ConstantArrayCreator',['../structllvm_1_1ConstantArrayCreator.html',1,'llvm']]],
  ['constantcreator',['ConstantCreator',['../structllvm_1_1ConstantCreator.html',1,'llvm']]],
  ['constantcreator_3c_20constantexpr_2c_20type_2c_20exprmapkeytype_20_3e',['ConstantCreator&lt; ConstantExpr, Type, ExprMapKeyType &gt;',['../structllvm_1_1ConstantCreator_3_01ConstantExpr_00_01Type_00_01ExprMapKeyType_01_4.html',1,'llvm']]],
  ['constantcreator_3c_20inlineasm_2c_20pointertype_2c_20inlineasmkeytype_20_3e',['ConstantCreator&lt; InlineAsm, PointerType, InlineAsmKeyType &gt;',['../structllvm_1_1ConstantCreator_3_01InlineAsm_00_01PointerType_00_01InlineAsmKeyType_01_4.html',1,'llvm']]],
  ['constantdataarray',['ConstantDataArray',['../classllvm_1_1ConstantDataArray.html',1,'llvm']]],
  ['constantdatasequential',['ConstantDataSequential',['../classllvm_1_1ConstantDataSequential.html',1,'llvm']]],
  ['constantdatavector',['ConstantDataVector',['../classllvm_1_1ConstantDataVector.html',1,'llvm']]],
  ['constantexpr',['ConstantExpr',['../classllvm_1_1ConstantExpr.html',1,'llvm']]],
  ['constantfolder',['ConstantFolder',['../classllvm_1_1ConstantFolder.html',1,'llvm']]],
  ['constantfp',['ConstantFP',['../classllvm_1_1ConstantFP.html',1,'llvm']]],
  ['constantfpsdnode',['ConstantFPSDNode',['../classllvm_1_1ConstantFPSDNode.html',1,'llvm']]],
  ['constantint',['ConstantInt',['../classllvm_1_1ConstantInt.html',1,'llvm']]],
  ['constantint_5fmatch',['constantint_match',['../structllvm_1_1PatternMatch_1_1constantint__match.html',1,'llvm::PatternMatch']]],
  ['constantkeydata',['ConstantKeyData',['../structllvm_1_1ConstantKeyData.html',1,'llvm']]],
  ['constantkeydata_3c_20constantexpr_20_3e',['ConstantKeyData&lt; ConstantExpr &gt;',['../structllvm_1_1ConstantKeyData_3_01ConstantExpr_01_4.html',1,'llvm']]],
  ['constantkeydata_3c_20inlineasm_20_3e',['ConstantKeyData&lt; InlineAsm &gt;',['../structllvm_1_1ConstantKeyData_3_01InlineAsm_01_4.html',1,'llvm']]],
  ['constantpointernull',['ConstantPointerNull',['../classllvm_1_1ConstantPointerNull.html',1,'llvm']]],
  ['constantpoolsdnode',['ConstantPoolSDNode',['../classllvm_1_1ConstantPoolSDNode.html',1,'llvm']]],
  ['constantrange',['ConstantRange',['../classllvm_1_1ConstantRange.html',1,'llvm']]],
  ['constantsdnode',['ConstantSDNode',['../classllvm_1_1ConstantSDNode.html',1,'llvm']]],
  ['constantstruct',['ConstantStruct',['../classllvm_1_1ConstantStruct.html',1,'llvm']]],
  ['constanttraits',['ConstantTraits',['../structllvm_1_1ConstantTraits.html',1,'llvm']]],
  ['constanttraits_3c_20constant_20_2a_20_3e',['ConstantTraits&lt; Constant * &gt;',['../structllvm_1_1ConstantTraits_3_01Constant_01_5_01_4.html',1,'llvm']]],
  ['constanttraits_3c_20std_3a_3avector_3c_20t_2c_20alloc_20_3e_20_3e',['ConstantTraits&lt; std::vector&lt; T, Alloc &gt; &gt;',['../structllvm_1_1ConstantTraits_3_01std_1_1vector_3_01T_00_01Alloc_01_4_01_4.html',1,'llvm']]],
  ['constantuniquemap',['ConstantUniqueMap',['../classllvm_1_1ConstantUniqueMap.html',1,'llvm']]],
  ['constantuniquemap_3c_20llvm_3a_3aexprmapkeytype_2c_20const_20llvm_3a_3aexprmapkeytype_20_26_2c_20llvm_3a_3atype_2c_20llvm_3a_3aconstantexpr_20_3e',['ConstantUniqueMap&lt; llvm::ExprMapKeyType, const llvm::ExprMapKeyType &amp;, llvm::Type, llvm::ConstantExpr &gt;',['../classllvm_1_1ConstantUniqueMap.html',1,'llvm']]],
  ['constantuniquemap_3c_20llvm_3a_3ainlineasmkeytype_2c_20const_20llvm_3a_3ainlineasmkeytype_20_26_2c_20llvm_3a_3apointertype_2c_20llvm_3a_3ainlineasm_20_3e',['ConstantUniqueMap&lt; llvm::InlineAsmKeyType, const llvm::InlineAsmKeyType &amp;, llvm::PointerType, llvm::InlineAsm &gt;',['../classllvm_1_1ConstantUniqueMap.html',1,'llvm']]],
  ['constantvector',['ConstantVector',['../classllvm_1_1ConstantVector.html',1,'llvm']]],
  ['constiterator',['ConstIterator',['../classllvm_1_1DenseSet_1_1ConstIterator.html',1,'llvm::DenseSet']]],
  ['constmibundleoperands',['ConstMIBundleOperands',['../classllvm_1_1ConstMIBundleOperands.html',1,'llvm']]],
  ['constmioperands',['ConstMIOperands',['../classllvm_1_1ConstMIOperands.html',1,'llvm']]],
  ['constraintinfo',['ConstraintInfo',['../structllvm_1_1InlineAsm_1_1ConstraintInfo.html',1,'llvm::InlineAsm']]],
  ['content_5fiterator',['content_iterator',['../classllvm_1_1object_1_1content__iterator.html',1,'llvm::object']]],
  ['contextdecision',['ContextDecision',['../structContextDecision.html',1,'']]],
  ['contextualfoldingset',['ContextualFoldingSet',['../classllvm_1_1ContextualFoldingSet.html',1,'llvm']]],
  ['contextualfoldingsettrait',['ContextualFoldingSetTrait',['../structllvm_1_1ContextualFoldingSetTrait.html',1,'llvm']]],
  ['convergingvliwscheduler',['ConvergingVLIWScheduler',['../classllvm_1_1ConvergingVLIWScheduler.html',1,'llvm']]],
  ['convertconstanttype',['ConvertConstantType',['../structllvm_1_1ConvertConstantType.html',1,'llvm']]],
  ['costtblentry',['CostTblEntry',['../structllvm_1_1CostTblEntry.html',1,'llvm']]],
  ['cpptargetmachine',['CPPTargetMachine',['../structllvm_1_1CPPTargetMachine.html',1,'llvm']]],
  ['crashrecoverycontext',['CrashRecoveryContext',['../classllvm_1_1CrashRecoveryContext.html',1,'llvm']]],
  ['crashrecoverycontextcleanup',['CrashRecoveryContextCleanup',['../classllvm_1_1CrashRecoveryContextCleanup.html',1,'llvm']]],
  ['crashrecoverycontextcleanupbase',['CrashRecoveryContextCleanupBase',['../classllvm_1_1CrashRecoveryContextCleanupBase.html',1,'llvm']]],
  ['crashrecoverycontextcleanupbase_3c_20crashrecoverycontextdeletecleanup_3c_20t_20_3e_2c_20t_20_3e',['CrashRecoveryContextCleanupBase&lt; CrashRecoveryContextDeleteCleanup&lt; T &gt;, T &gt;',['../classllvm_1_1CrashRecoveryContextCleanupBase.html',1,'llvm']]],
  ['crashrecoverycontextcleanupbase_3c_20crashrecoverycontextdestructorcleanup_3c_20t_20_3e_2c_20t_20_3e',['CrashRecoveryContextCleanupBase&lt; CrashRecoveryContextDestructorCleanup&lt; T &gt;, T &gt;',['../classllvm_1_1CrashRecoveryContextCleanupBase.html',1,'llvm']]],
  ['crashrecoverycontextcleanupbase_3c_20crashrecoverycontextreleaserefcleanup_3c_20t_20_3e_2c_20t_20_3e',['CrashRecoveryContextCleanupBase&lt; CrashRecoveryContextReleaseRefCleanup&lt; T &gt;, T &gt;',['../classllvm_1_1CrashRecoveryContextCleanupBase.html',1,'llvm']]],
  ['crashrecoverycontextcleanupregistrar',['CrashRecoveryContextCleanupRegistrar',['../classllvm_1_1CrashRecoveryContextCleanupRegistrar.html',1,'llvm']]],
  ['crashrecoverycontextdeletecleanup',['CrashRecoveryContextDeleteCleanup',['../classllvm_1_1CrashRecoveryContextDeleteCleanup.html',1,'llvm']]],
  ['crashrecoverycontextdestructorcleanup',['CrashRecoveryContextDestructorCleanup',['../classllvm_1_1CrashRecoveryContextDestructorCleanup.html',1,'llvm']]],
  ['crashrecoverycontextreleaserefcleanup',['CrashRecoveryContextReleaseRefCleanup',['../classllvm_1_1CrashRecoveryContextReleaseRefCleanup.html',1,'llvm']]],
  ['criticalantidepbreaker',['CriticalAntiDepBreaker',['../classllvm_1_1CriticalAntiDepBreaker.html',1,'llvm']]],
  ['cryptcontexttraits',['CryptContextTraits',['../structCryptContextTraits.html',1,'']]],
  ['cset',['cset',['../structcset.html',1,'']]],
  ['cst_5fpred_5fty',['cst_pred_ty',['../structllvm_1_1PatternMatch_1_1cst__pred__ty.html',1,'llvm::PatternMatch']]],
  ['cursor',['Cursor',['../classllvm_1_1InterferenceCache_1_1Cursor.html',1,'llvm::InterferenceCache']]],
  ['cvtrndsatsdnode',['CvtRndSatSDNode',['../classllvm_1_1CvtRndSatSDNode.html',1,'llvm']]]
];
