var searchData=
[
  ['objcarcaliasanalysis',['ObjCARCAliasAnalysis',['../classllvm_1_1objcarc_1_1ObjCARCAliasAnalysis.html',1,'llvm::objcarc']]],
  ['object',['Object',['../structllvm_1_1ELFYAML_1_1Object.html',1,'llvm::ELFYAML']]],
  ['object',['Object',['../structllvm_1_1COFFYAML_1_1Object.html',1,'llvm::COFFYAML']]],
  ['object_5fdeleter',['object_deleter',['../structllvm_1_1object__deleter.html',1,'llvm']]],
  ['object_5fdeleter_3c_20t_5bn_5d_3e',['object_deleter&lt; T[N]&gt;',['../structllvm_1_1object__deleter_3_01T[N]_4.html',1,'llvm']]],
  ['object_5ferror',['object_error',['../structllvm_1_1object_1_1object__error.html',1,'llvm::object']]],
  ['object_5fiterator',['object_iterator',['../classllvm_1_1object_1_1MachOUniversalBinary_1_1object__iterator.html',1,'llvm::object::MachOUniversalBinary']]],
  ['objectbuffer',['ObjectBuffer',['../classllvm_1_1ObjectBuffer.html',1,'llvm']]],
  ['objectbufferstream',['ObjectBufferStream',['../classllvm_1_1ObjectBufferStream.html',1,'llvm']]],
  ['objectcache',['ObjectCache',['../classllvm_1_1ObjectCache.html',1,'llvm']]],
  ['objectfile',['ObjectFile',['../classllvm_1_1object_1_1ObjectFile.html',1,'llvm::object']]],
  ['objectforarch',['ObjectForArch',['../classllvm_1_1object_1_1MachOUniversalBinary_1_1ObjectForArch.html',1,'llvm::object::MachOUniversalBinary']]],
  ['objectimage',['ObjectImage',['../classllvm_1_1ObjectImage.html',1,'llvm']]],
  ['objectimagecommon',['ObjectImageCommon',['../classllvm_1_1ObjectImageCommon.html',1,'llvm']]],
  ['objectsizeoffsetevaluator',['ObjectSizeOffsetEvaluator',['../classllvm_1_1ObjectSizeOffsetEvaluator.html',1,'llvm']]],
  ['objectsizeoffsetvisitor',['ObjectSizeOffsetVisitor',['../classllvm_1_1ObjectSizeOffsetVisitor.html',1,'llvm']]],
  ['ofmax_5fpred_5fty',['ofmax_pred_ty',['../structllvm_1_1PatternMatch_1_1ofmax__pred__ty.html',1,'llvm::PatternMatch']]],
  ['ofmin_5fpred_5fty',['ofmin_pred_ty',['../structllvm_1_1PatternMatch_1_1ofmin__pred__ty.html',1,'llvm::PatternMatch']]],
  ['oneuse_5fmatch',['OneUse_match',['../structllvm_1_1PatternMatch_1_1OneUse__match.html',1,'llvm::PatternMatch']]],
  ['opcodedecision',['OpcodeDecision',['../structOpcodeDecision.html',1,'']]],
  ['operand',['Operand',['../structllvm_1_1MCModuleYAML_1_1Operand.html',1,'llvm::MCModuleYAML']]],
  ['operandspecifier',['OperandSpecifier',['../structOperandSpecifier.html',1,'']]],
  ['operandtraits',['OperandTraits',['../structllvm_1_1OperandTraits.html',1,'llvm']]],
  ['operandtraits_3c_20atomiccmpxchginst_20_3e',['OperandTraits&lt; AtomicCmpXchgInst &gt;',['../structllvm_1_1OperandTraits_3_01AtomicCmpXchgInst_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20atomicrmwinst_20_3e',['OperandTraits&lt; AtomicRMWInst &gt;',['../structllvm_1_1OperandTraits_3_01AtomicRMWInst_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20binaryconstantexpr_20_3e',['OperandTraits&lt; BinaryConstantExpr &gt;',['../structllvm_1_1OperandTraits_3_01BinaryConstantExpr_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20binaryoperator_20_3e',['OperandTraits&lt; BinaryOperator &gt;',['../structllvm_1_1OperandTraits_3_01BinaryOperator_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20blockaddress_20_3e',['OperandTraits&lt; BlockAddress &gt;',['../structllvm_1_1OperandTraits_3_01BlockAddress_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20branchinst_20_3e',['OperandTraits&lt; BranchInst &gt;',['../structllvm_1_1OperandTraits_3_01BranchInst_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20callinst_20_3e',['OperandTraits&lt; CallInst &gt;',['../structllvm_1_1OperandTraits_3_01CallInst_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20cmpinst_20_3e',['OperandTraits&lt; CmpInst &gt;',['../structllvm_1_1OperandTraits_3_01CmpInst_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20compareconstantexpr_20_3e',['OperandTraits&lt; CompareConstantExpr &gt;',['../structllvm_1_1OperandTraits_3_01CompareConstantExpr_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20constantarray_20_3e',['OperandTraits&lt; ConstantArray &gt;',['../structllvm_1_1OperandTraits_3_01ConstantArray_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20constantexpr_20_3e',['OperandTraits&lt; ConstantExpr &gt;',['../structllvm_1_1OperandTraits_3_01ConstantExpr_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20constantplaceholder_20_3e',['OperandTraits&lt; ConstantPlaceHolder &gt;',['../structllvm_1_1OperandTraits_3_01ConstantPlaceHolder_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20constantstruct_20_3e',['OperandTraits&lt; ConstantStruct &gt;',['../structllvm_1_1OperandTraits_3_01ConstantStruct_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20constantvector_20_3e',['OperandTraits&lt; ConstantVector &gt;',['../structllvm_1_1OperandTraits_3_01ConstantVector_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20extractelementconstantexpr_20_3e',['OperandTraits&lt; ExtractElementConstantExpr &gt;',['../structllvm_1_1OperandTraits_3_01ExtractElementConstantExpr_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20extractelementinst_20_3e',['OperandTraits&lt; ExtractElementInst &gt;',['../structllvm_1_1OperandTraits_3_01ExtractElementInst_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20extractvalueconstantexpr_20_3e',['OperandTraits&lt; ExtractValueConstantExpr &gt;',['../structllvm_1_1OperandTraits_3_01ExtractValueConstantExpr_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20getelementptrconstantexpr_20_3e',['OperandTraits&lt; GetElementPtrConstantExpr &gt;',['../structllvm_1_1OperandTraits_3_01GetElementPtrConstantExpr_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20getelementptrinst_20_3e',['OperandTraits&lt; GetElementPtrInst &gt;',['../structllvm_1_1OperandTraits_3_01GetElementPtrInst_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20globalalias_20_3e',['OperandTraits&lt; GlobalAlias &gt;',['../structllvm_1_1OperandTraits_3_01GlobalAlias_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20globalvariable_20_3e',['OperandTraits&lt; GlobalVariable &gt;',['../structllvm_1_1OperandTraits_3_01GlobalVariable_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20indirectbrinst_20_3e',['OperandTraits&lt; IndirectBrInst &gt;',['../structllvm_1_1OperandTraits_3_01IndirectBrInst_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20insertelementconstantexpr_20_3e',['OperandTraits&lt; InsertElementConstantExpr &gt;',['../structllvm_1_1OperandTraits_3_01InsertElementConstantExpr_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20insertelementinst_20_3e',['OperandTraits&lt; InsertElementInst &gt;',['../structllvm_1_1OperandTraits_3_01InsertElementInst_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20insertvalueconstantexpr_20_3e',['OperandTraits&lt; InsertValueConstantExpr &gt;',['../structllvm_1_1OperandTraits_3_01InsertValueConstantExpr_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20insertvalueinst_20_3e',['OperandTraits&lt; InsertValueInst &gt;',['../structllvm_1_1OperandTraits_3_01InsertValueInst_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20invokeinst_20_3e',['OperandTraits&lt; InvokeInst &gt;',['../structllvm_1_1OperandTraits_3_01InvokeInst_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20landingpadinst_20_3e',['OperandTraits&lt; LandingPadInst &gt;',['../structllvm_1_1OperandTraits_3_01LandingPadInst_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20phinode_20_3e',['OperandTraits&lt; PHINode &gt;',['../structllvm_1_1OperandTraits_3_01PHINode_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20resumeinst_20_3e',['OperandTraits&lt; ResumeInst &gt;',['../structllvm_1_1OperandTraits_3_01ResumeInst_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20returninst_20_3e',['OperandTraits&lt; ReturnInst &gt;',['../structllvm_1_1OperandTraits_3_01ReturnInst_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20selectconstantexpr_20_3e',['OperandTraits&lt; SelectConstantExpr &gt;',['../structllvm_1_1OperandTraits_3_01SelectConstantExpr_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20selectinst_20_3e',['OperandTraits&lt; SelectInst &gt;',['../structllvm_1_1OperandTraits_3_01SelectInst_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20shufflevectorconstantexpr_20_3e',['OperandTraits&lt; ShuffleVectorConstantExpr &gt;',['../structllvm_1_1OperandTraits_3_01ShuffleVectorConstantExpr_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20shufflevectorinst_20_3e',['OperandTraits&lt; ShuffleVectorInst &gt;',['../structllvm_1_1OperandTraits_3_01ShuffleVectorInst_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20storeinst_20_3e',['OperandTraits&lt; StoreInst &gt;',['../structllvm_1_1OperandTraits_3_01StoreInst_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20switchinst_20_3e',['OperandTraits&lt; SwitchInst &gt;',['../structllvm_1_1OperandTraits_3_01SwitchInst_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20unaryconstantexpr_20_3e',['OperandTraits&lt; UnaryConstantExpr &gt;',['../structllvm_1_1OperandTraits_3_01UnaryConstantExpr_01_4.html',1,'llvm']]],
  ['operandtraits_3c_20unaryinstruction_20_3e',['OperandTraits&lt; UnaryInstruction &gt;',['../structllvm_1_1OperandTraits_3_01UnaryInstruction_01_4.html',1,'llvm']]],
  ['operator',['Operator',['../classllvm_1_1Operator.html',1,'llvm']]],
  ['opinit',['OpInit',['../classllvm_1_1OpInit.html',1,'llvm']]],
  ['oprofilewrapper',['OProfileWrapper',['../classllvm_1_1OProfileWrapper.html',1,'llvm']]],
  ['opt',['opt',['../classllvm_1_1cl_1_1opt.html',1,'llvm::cl']]],
  ['opt_5fstorage',['opt_storage',['../classllvm_1_1cl_1_1opt__storage.html',1,'llvm::cl']]],
  ['opt_5fstorage_3c_20datatype_2c_20externalstorage_2c_20is_5fclass_3c_20datatype_20_3e_3a_3avalue_20_3e',['opt_storage&lt; DataType, ExternalStorage, is_class&lt; DataType &gt;::value &gt;',['../classllvm_1_1cl_1_1opt__storage.html',1,'llvm::cl']]],
  ['opt_5fstorage_3c_20datatype_2c_20false_2c_20false_20_3e',['opt_storage&lt; DataType, false, false &gt;',['../classllvm_1_1cl_1_1opt__storage_3_01DataType_00_01false_00_01false_01_4.html',1,'llvm::cl']]],
  ['opt_5fstorage_3c_20datatype_2c_20false_2c_20true_20_3e',['opt_storage&lt; DataType, false, true &gt;',['../classllvm_1_1cl_1_1opt__storage_3_01DataType_00_01false_00_01true_01_4.html',1,'llvm::cl']]],
  ['option',['Option',['../classllvm_1_1opt_1_1Option.html',1,'llvm::opt']]],
  ['option',['Option',['../classllvm_1_1cl_1_1Option.html',1,'llvm::cl']]],
  ['optional',['Optional',['../classllvm_1_1Optional.html',1,'llvm']]],
  ['optional_3c_20llvm_3a_3aerror_5fcode_20_3e',['Optional&lt; llvm::error_code &gt;',['../classllvm_1_1Optional.html',1,'llvm']]],
  ['optional_3c_20std_3a_3apair_3c_20std_3a_3astring_2c_20int_20_3e_20_3e',['Optional&lt; std::pair&lt; std::string, int &gt; &gt;',['../classllvm_1_1Optional.html',1,'llvm']]],
  ['optionaloperandtraits',['OptionalOperandTraits',['../structllvm_1_1OptionalOperandTraits.html',1,'llvm']]],
  ['optionaloperandtraits_3c_20globalvariable_20_3e',['OptionalOperandTraits&lt; GlobalVariable &gt;',['../structllvm_1_1OptionalOperandTraits.html',1,'llvm']]],
  ['optioncategory',['OptionCategory',['../classllvm_1_1cl_1_1OptionCategory.html',1,'llvm::cl']]],
  ['optiondiffprinter',['OptionDiffPrinter',['../structllvm_1_1cl_1_1OptionDiffPrinter.html',1,'llvm::cl']]],
  ['optiondiffprinter_3c_20dt_2c_20dt_20_3e',['OptionDiffPrinter&lt; DT, DT &gt;',['../structllvm_1_1cl_1_1OptionDiffPrinter_3_01DT_00_01DT_01_4.html',1,'llvm::cl']]],
  ['optioninfo',['OptionInfo',['../classllvm_1_1cl_1_1parser_1_1OptionInfo.html',1,'llvm::cl::parser']]],
  ['optionvalue',['OptionValue',['../structllvm_1_1cl_1_1OptionValue.html',1,'llvm::cl']]],
  ['optionvalue_3c_20cl_3a_3aboolordefault_20_3e',['OptionValue&lt; cl::boolOrDefault &gt;',['../structllvm_1_1cl_1_1OptionValue_3_01cl_1_1boolOrDefault_01_4.html',1,'llvm::cl']]],
  ['optionvalue_3c_20std_3a_3astring_20_3e',['OptionValue&lt; std::string &gt;',['../structllvm_1_1cl_1_1OptionValue_3_01std_1_1string_01_4.html',1,'llvm::cl']]],
  ['optionvaluebase',['OptionValueBase',['../structllvm_1_1cl_1_1OptionValueBase.html',1,'llvm::cl']]],
  ['optionvaluebase_3c_20datatype_2c_20false_20_3e',['OptionValueBase&lt; DataType, false &gt;',['../structllvm_1_1cl_1_1OptionValueBase_3_01DataType_00_01false_01_4.html',1,'llvm::cl']]],
  ['optionvaluebase_3c_20datatype_2c_20is_5fclass_3c_20datatype_20_3e_3a_3avalue_20_3e',['OptionValueBase&lt; DataType, is_class&lt; DataType &gt;::value &gt;',['../structllvm_1_1cl_1_1OptionValueBase.html',1,'llvm::cl']]],
  ['optionvaluecopy',['OptionValueCopy',['../classllvm_1_1cl_1_1OptionValueCopy.html',1,'llvm::cl']]],
  ['optionvaluecopy_3c_20cl_3a_3aboolordefault_20_3e',['OptionValueCopy&lt; cl::boolOrDefault &gt;',['../classllvm_1_1cl_1_1OptionValueCopy.html',1,'llvm::cl']]],
  ['optionvaluecopy_3c_20std_3a_3astring_20_3e',['OptionValueCopy&lt; std::string &gt;',['../classllvm_1_1cl_1_1OptionValueCopy.html',1,'llvm::cl']]],
  ['optlevelchanger',['OptLevelChanger',['../classllvm_1_1OptLevelChanger.html',1,'llvm']]],
  ['optspecifier',['OptSpecifier',['../classllvm_1_1opt_1_1OptSpecifier.html',1,'llvm::opt']]],
  ['opttable',['OptTable',['../classllvm_1_1opt_1_1OptTable.html',1,'llvm::opt']]],
  ['output',['Output',['../classllvm_1_1yaml_1_1Output.html',1,'llvm::yaml']]],
  ['outputarg',['OutputArg',['../structllvm_1_1ISD_1_1OutputArg.html',1,'llvm::ISD']]],
  ['outputbuffer',['OutputBuffer',['../classllvm_1_1OutputBuffer.html',1,'llvm']]],
  ['overflowingbinaryoperator',['OverflowingBinaryOperator',['../classllvm_1_1OverflowingBinaryOperator.html',1,'llvm']]],
  ['owningarrayptr',['OwningArrayPtr',['../classllvm_1_1OwningArrayPtr.html',1,'llvm']]],
  ['owningarrayptr_3c_20llvm_3a_3aliveintervalunion_3a_3aquery_20_3e',['OwningArrayPtr&lt; llvm::LiveIntervalUnion::Query &gt;',['../classllvm_1_1OwningArrayPtr.html',1,'llvm']]],
  ['owningarrayptr_3c_20mcphysreg_20_3e',['OwningArrayPtr&lt; MCPhysReg &gt;',['../classllvm_1_1OwningArrayPtr.html',1,'llvm']]],
  ['owningarrayptr_3c_20rcinfo_20_3e',['OwningArrayPtr&lt; RCInfo &gt;',['../classllvm_1_1OwningArrayPtr.html',1,'llvm']]],
  ['owningarrayptr_3c_20unsigned_20_3e',['OwningArrayPtr&lt; unsigned &gt;',['../classllvm_1_1OwningArrayPtr.html',1,'llvm']]],
  ['owningptr',['OwningPtr',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20const_20llvm_3a_3allvm_3a_3amcasminfo_20_3e',['OwningPtr&lt; const llvm::llvm::MCAsmInfo &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20const_20llvm_3a_3allvm_3a_3amccontext_20_3e',['OwningPtr&lt; const llvm::llvm::MCContext &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20const_20llvm_3a_3allvm_3a_3amcdisassembler_20_3e',['OwningPtr&lt; const llvm::llvm::MCDisassembler &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20const_20llvm_3a_3allvm_3a_3amcinstrinfo_20_3e',['OwningPtr&lt; const llvm::llvm::MCInstrInfo &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20const_20llvm_3a_3allvm_3a_3amcregisterinfo_20_3e',['OwningPtr&lt; const llvm::llvm::MCRegisterInfo &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20const_20llvm_3a_3allvm_3a_3amcsubtargetinfo_20_3e',['OwningPtr&lt; const llvm::llvm::MCSubtargetInfo &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20const_20llvm_3a_3amipsframelowering_20_3e',['OwningPtr&lt; const llvm::MipsFrameLowering &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20const_20llvm_3a_3amipsinstrinfo_20_3e',['OwningPtr&lt; const llvm::MipsInstrInfo &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20const_20llvm_3a_3amipstargetlowering_20_3e',['OwningPtr&lt; const llvm::MipsTargetLowering &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20dwoholder_20_3e',['OwningPtr&lt; DWOHolder &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20hnode_20_3e',['OwningPtr&lt; HNode &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3aamdgpuinstrinfo_20_3e',['OwningPtr&lt; llvm::AMDGPUInstrInfo &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3aamdgputargetlowering_20_3e',['OwningPtr&lt; llvm::AMDGPUTargetLowering &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3aarmbaseinstrinfo_20_3e',['OwningPtr&lt; llvm::ARMBaseInstrInfo &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3aarmframelowering_20_3e',['OwningPtr&lt; llvm::ARMFrameLowering &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3abitstreamreader_20_3e',['OwningPtr&lt; llvm::BitstreamReader &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3adatastreamer_20_3e',['OwningPtr&lt; llvm::DataStreamer &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3adie_20_3e',['OwningPtr&lt; llvm::DIE &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3adwarfcontext_20_3e',['OwningPtr&lt; llvm::DWARFContext &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3adwarfdebugabbrev_20_3e',['OwningPtr&lt; llvm::DWARFDebugAbbrev &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3adwarfdebugaranges_20_3e',['OwningPtr&lt; llvm::DWARFDebugAranges &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3adwarfdebugframe_20_3e',['OwningPtr&lt; llvm::DWARFDebugFrame &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3adwarfdebugline_20_3e',['OwningPtr&lt; llvm::DWARFDebugLine &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3adwarfdebugloc_20_3e',['OwningPtr&lt; llvm::DWARFDebugLoc &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3agvmaterializer_20_3e',['OwningPtr&lt; llvm::GVMaterializer &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3allvm_3a_3amcinstprinter_20_3e',['OwningPtr&lt; llvm::llvm::MCInstPrinter &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3amcmachobjecttargetwriter_20_3e',['OwningPtr&lt; llvm::MCMachObjectTargetWriter &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3amcrelocationinfo_20_3e',['OwningPtr&lt; llvm::MCRelocationInfo &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3amcsymbolizer_20_3e',['OwningPtr&lt; llvm::MCSymbolizer &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3amctargetstreamer_20_3e',['OwningPtr&lt; llvm::MCTargetStreamer &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3amemorybuffer_20_3e',['OwningPtr&lt; llvm::MemoryBuffer &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3amemoryobject_20_3e',['OwningPtr&lt; llvm::MemoryObject &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3amodule_20_3e',['OwningPtr&lt; llvm::Module &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3aobjectbuffer_20_3e',['OwningPtr&lt; llvm::ObjectBuffer &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3aprediteratorcache_20_3e',['OwningPtr&lt; llvm::PredIteratorCache &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3artdyldmemorymanager_20_3e',['OwningPtr&lt; llvm::RTDyldMemoryManager &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3aslottracker_20_3e',['OwningPtr&lt; llvm::SlotTracker &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3astreamablememoryobject_20_3e',['OwningPtr&lt; llvm::StreamableMemoryObject &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3asys_3a_3afs_3a_3amapped_5ffile_5fregion_20_3e',['OwningPtr&lt; llvm::sys::fs::mapped_file_region &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3atargetmachine_20_3e',['OwningPtr&lt; llvm::TargetMachine &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3ayaml_3a_3adocument_20_3e',['OwningPtr&lt; llvm::yaml::Document &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3ayaml_3a_3allvm_3a_3ayaml_3a_3astream_20_3e',['OwningPtr&lt; llvm::yaml::llvm::yaml::Stream &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20llvm_3a_3ayaml_3a_3ascanner_20_3e',['OwningPtr&lt; llvm::yaml::Scanner &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]],
  ['owningptr_3c_20object_3a_3allvm_3a_3aobject_3a_3aobjectfile_20_3e',['OwningPtr&lt; object::llvm::object::ObjectFile &gt;',['../classllvm_1_1OwningPtr.html',1,'llvm']]]
];
