var searchData=
[
  ['r600instrinfo',['R600InstrInfo',['../classllvm_1_1R600InstrInfo.html',1,'llvm']]],
  ['r600machinefunctioninfo',['R600MachineFunctionInfo',['../classllvm_1_1R600MachineFunctionInfo.html',1,'llvm']]],
  ['r600registerinfo',['R600RegisterInfo',['../structllvm_1_1R600RegisterInfo.html',1,'llvm']]],
  ['r600schedstrategy',['R600SchedStrategy',['../classllvm_1_1R600SchedStrategy.html',1,'llvm']]],
  ['r600targetlowering',['R600TargetLowering',['../classllvm_1_1R600TargetLowering.html',1,'llvm']]],
  ['rangelistentry',['RangeListEntry',['../structllvm_1_1DWARFDebugRangeList_1_1RangeListEntry.html',1,'llvm::DWARFDebugRangeList']]],
  ['raw_5ffd_5fostream',['raw_fd_ostream',['../classllvm_1_1raw__fd__ostream.html',1,'llvm']]],
  ['raw_5fnull_5fostream',['raw_null_ostream',['../classllvm_1_1raw__null__ostream.html',1,'llvm']]],
  ['raw_5fos_5fostream',['raw_os_ostream',['../classllvm_1_1raw__os__ostream.html',1,'llvm']]],
  ['raw_5fostream',['raw_ostream',['../classllvm_1_1raw__ostream.html',1,'llvm']]],
  ['raw_5fstring_5fostream',['raw_string_ostream',['../classllvm_1_1raw__string__ostream.html',1,'llvm']]],
  ['raw_5fsvector_5fostream',['raw_svector_ostream',['../classllvm_1_1raw__svector__ostream.html',1,'llvm']]],
  ['re_5fguts',['re_guts',['../structre__guts.html',1,'']]],
  ['readyqueue',['ReadyQueue',['../classllvm_1_1ReadyQueue.html',1,'llvm']]],
  ['recdiriterstate',['RecDirIterState',['../structllvm_1_1sys_1_1fs_1_1detail_1_1RecDirIterState.html',1,'llvm::sys::fs::detail']]],
  ['record',['Record',['../classllvm_1_1Record.html',1,'llvm']]],
  ['recordkeeper',['RecordKeeper',['../classllvm_1_1RecordKeeper.html',1,'llvm']]],
  ['recordparts',['RecordParts',['../structllvm_1_1LessRecordRegister_1_1RecordParts.html',1,'llvm::LessRecordRegister']]],
  ['recordrecty',['RecordRecTy',['../classllvm_1_1RecordRecTy.html',1,'llvm']]],
  ['recordval',['RecordVal',['../classllvm_1_1RecordVal.html',1,'llvm']]],
  ['recty',['RecTy',['../classllvm_1_1RecTy.html',1,'llvm']]],
  ['recursive_5fdirectory_5fiterator',['recursive_directory_iterator',['../classllvm_1_1sys_1_1fs_1_1recursive__directory__iterator.html',1,'llvm::sys::fs']]],
  ['recycler',['Recycler',['../classllvm_1_1Recycler.html',1,'llvm']]],
  ['recycler_3c_20llvm_3a_3amachinebasicblock_20_3e',['Recycler&lt; llvm::MachineBasicBlock &gt;',['../classllvm_1_1Recycler.html',1,'llvm']]],
  ['recycler_3c_20llvm_3a_3amachineinstr_20_3e',['Recycler&lt; llvm::MachineInstr &gt;',['../classllvm_1_1Recycler.html',1,'llvm']]],
  ['recycler_3c_20sdnode_2c_20size_2c_20align_20_3e',['Recycler&lt; SDNode, Size, Align &gt;',['../classllvm_1_1Recycler.html',1,'llvm']]],
  ['recyclerstruct',['RecyclerStruct',['../structllvm_1_1RecyclerStruct.html',1,'llvm']]],
  ['recyclingallocator',['RecyclingAllocator',['../classllvm_1_1RecyclingAllocator.html',1,'llvm']]],
  ['recyclingallocator_3c_20bumpptrallocator_2c_20sdnode_2c_20sizeof_28largestsdnode_29_2c_20alignof_3c_20mostalignedsdnode_20_3e_3a_3aalignment_20_3e',['RecyclingAllocator&lt; BumpPtrAllocator, SDNode, sizeof(LargestSDNode), AlignOf&lt; MostAlignedSDNode &gt;::Alignment &gt;',['../classllvm_1_1RecyclingAllocator.html',1,'llvm']]],
  ['refcountedbase',['RefCountedBase',['../classllvm_1_1RefCountedBase.html',1,'llvm']]],
  ['refcountedbase_3c_20diriterstate_20_3e',['RefCountedBase&lt; DirIterState &gt;',['../classllvm_1_1RefCountedBase.html',1,'llvm']]],
  ['refcountedbase_3c_20recdiriterstate_20_3e',['RefCountedBase&lt; RecDirIterState &gt;',['../classllvm_1_1RefCountedBase.html',1,'llvm']]],
  ['refcountedbasevptr',['RefCountedBaseVPTR',['../classllvm_1_1RefCountedBaseVPTR.html',1,'llvm']]],
  ['reference',['reference',['../classllvm_1_1PackedVector_1_1reference.html',1,'llvm::PackedVector']]],
  ['reference',['reference',['../classllvm_1_1SmallBitVector_1_1reference.html',1,'llvm::SmallBitVector']]],
  ['reference',['reference',['../classllvm_1_1BitVector_1_1reference.html',1,'llvm::BitVector']]],
  ['referenceadder',['ReferenceAdder',['../structllvm_1_1ReferenceAdder.html',1,'llvm']]],
  ['referenceadder_3c_20t_20_26_20_3e',['ReferenceAdder&lt; T &amp; &gt;',['../structllvm_1_1ReferenceAdder_3_01T_01_6_01_4.html',1,'llvm']]],
  ['referencestorage',['ReferenceStorage',['../classllvm_1_1ReferenceStorage.html',1,'llvm']]],
  ['regallocbase',['RegAllocBase',['../classllvm_1_1RegAllocBase.html',1,'llvm']]],
  ['regclassweight',['RegClassWeight',['../structllvm_1_1RegClassWeight.html',1,'llvm']]],
  ['regdefiter',['RegDefIter',['../classllvm_1_1ScheduleDAGSDNodes_1_1RegDefIter.html',1,'llvm::ScheduleDAGSDNodes']]],
  ['regex',['Regex',['../classllvm_1_1Regex.html',1,'llvm']]],
  ['region',['Region',['../classllvm_1_1Region.html',1,'llvm']]],
  ['regioninfo',['RegionInfo',['../classllvm_1_1RegionInfo.html',1,'llvm']]],
  ['regionnode',['RegionNode',['../classllvm_1_1RegionNode.html',1,'llvm']]],
  ['regionpass',['RegionPass',['../classllvm_1_1RegionPass.html',1,'llvm']]],
  ['regionpressure',['RegionPressure',['../structllvm_1_1RegionPressure.html',1,'llvm']]],
  ['registeragbase',['RegisterAGBase',['../classllvm_1_1RegisterAGBase.html',1,'llvm']]],
  ['registeranalysisgroup',['RegisterAnalysisGroup',['../structllvm_1_1RegisterAnalysisGroup.html',1,'llvm']]],
  ['registerasmprinter',['RegisterAsmPrinter',['../structllvm_1_1RegisterAsmPrinter.html',1,'llvm']]],
  ['registerclassinfo',['RegisterClassInfo',['../classllvm_1_1RegisterClassInfo.html',1,'llvm']]],
  ['registermasksdnode',['RegisterMaskSDNode',['../classllvm_1_1RegisterMaskSDNode.html',1,'llvm']]],
  ['registermcasmbackend',['RegisterMCAsmBackend',['../structllvm_1_1RegisterMCAsmBackend.html',1,'llvm']]],
  ['registermcasminfo',['RegisterMCAsmInfo',['../structllvm_1_1RegisterMCAsmInfo.html',1,'llvm']]],
  ['registermcasminfofn',['RegisterMCAsmInfoFn',['../structllvm_1_1RegisterMCAsmInfoFn.html',1,'llvm']]],
  ['registermcasmparser',['RegisterMCAsmParser',['../structllvm_1_1RegisterMCAsmParser.html',1,'llvm']]],
  ['registermccodeemitter',['RegisterMCCodeEmitter',['../structllvm_1_1RegisterMCCodeEmitter.html',1,'llvm']]],
  ['registermccodegeninfo',['RegisterMCCodeGenInfo',['../structllvm_1_1RegisterMCCodeGenInfo.html',1,'llvm']]],
  ['registermccodegeninfofn',['RegisterMCCodeGenInfoFn',['../structllvm_1_1RegisterMCCodeGenInfoFn.html',1,'llvm']]],
  ['registermcinstranalysis',['RegisterMCInstrAnalysis',['../structllvm_1_1RegisterMCInstrAnalysis.html',1,'llvm']]],
  ['registermcinstranalysisfn',['RegisterMCInstrAnalysisFn',['../structllvm_1_1RegisterMCInstrAnalysisFn.html',1,'llvm']]],
  ['registermcinstrinfo',['RegisterMCInstrInfo',['../structllvm_1_1RegisterMCInstrInfo.html',1,'llvm']]],
  ['registermcinstrinfofn',['RegisterMCInstrInfoFn',['../structllvm_1_1RegisterMCInstrInfoFn.html',1,'llvm']]],
  ['registermcreginfo',['RegisterMCRegInfo',['../structllvm_1_1RegisterMCRegInfo.html',1,'llvm']]],
  ['registermcreginfofn',['RegisterMCRegInfoFn',['../structllvm_1_1RegisterMCRegInfoFn.html',1,'llvm']]],
  ['registermcsubtargetinfo',['RegisterMCSubtargetInfo',['../structllvm_1_1RegisterMCSubtargetInfo.html',1,'llvm']]],
  ['registermcsubtargetinfofn',['RegisterMCSubtargetInfoFn',['../structllvm_1_1RegisterMCSubtargetInfoFn.html',1,'llvm']]],
  ['registeroperands',['RegisterOperands',['../classRegisterOperands.html',1,'']]],
  ['registerpass',['RegisterPass',['../structllvm_1_1RegisterPass.html',1,'llvm']]],
  ['registerpassparser',['RegisterPassParser',['../classllvm_1_1RegisterPassParser.html',1,'llvm']]],
  ['registerpressure',['RegisterPressure',['../structllvm_1_1RegisterPressure.html',1,'llvm']]],
  ['registerreference',['RegisterReference',['../structllvm_1_1AggressiveAntiDepState_1_1RegisterReference.html',1,'llvm::AggressiveAntiDepState']]],
  ['registerregalloc',['RegisterRegAlloc',['../classllvm_1_1RegisterRegAlloc.html',1,'llvm']]],
  ['registerscheduler',['RegisterScheduler',['../classllvm_1_1RegisterScheduler.html',1,'llvm']]],
  ['registersdnode',['RegisterSDNode',['../classllvm_1_1RegisterSDNode.html',1,'llvm']]],
  ['registerstandardpasses',['RegisterStandardPasses',['../structllvm_1_1RegisterStandardPasses.html',1,'llvm']]],
  ['registertarget',['RegisterTarget',['../structllvm_1_1RegisterTarget.html',1,'llvm']]],
  ['registertargetmachine',['RegisterTargetMachine',['../structllvm_1_1RegisterTargetMachine.html',1,'llvm']]],
  ['registry',['Registry',['../classllvm_1_1Registry.html',1,'llvm']]],
  ['registryparser',['RegistryParser',['../classllvm_1_1RegistryParser.html',1,'llvm']]],
  ['registrytraits',['RegistryTraits',['../classllvm_1_1RegistryTraits.html',1,'llvm']]],
  ['regpressuredelta',['RegPressureDelta',['../structllvm_1_1RegPressureDelta.html',1,'llvm']]],
  ['regpressuretracker',['RegPressureTracker',['../classllvm_1_1RegPressureTracker.html',1,'llvm']]],
  ['regscavenger',['RegScavenger',['../classllvm_1_1RegScavenger.html',1,'llvm']]],
  ['relocation',['Relocation',['../structllvm_1_1COFFYAML_1_1Relocation.html',1,'llvm::COFFYAML']]],
  ['relocation',['relocation',['../structllvm_1_1COFF_1_1relocation.html',1,'llvm::COFF']]],
  ['relocation_5finfo',['relocation_info',['../structllvm_1_1MachO_1_1relocation__info.html',1,'llvm::MachO']]],
  ['relocationentry',['RelocationEntry',['../classllvm_1_1RelocationEntry.html',1,'llvm']]],
  ['relocationref',['RelocationRef',['../classllvm_1_1object_1_1RelocationRef.html',1,'llvm::object']]],
  ['relocationvalueref',['RelocationValueRef',['../classllvm_1_1RelocationValueRef.html',1,'llvm']]],
  ['reloctoapply',['RelocToApply',['../structllvm_1_1object_1_1RelocToApply.html',1,'llvm::object']]],
  ['relocvisitor',['RelocVisitor',['../classllvm_1_1object_1_1RelocVisitor.html',1,'llvm::object']]],
  ['remat',['Remat',['../structllvm_1_1LiveRangeEdit_1_1Remat.html',1,'llvm::LiveRangeEdit']]],
  ['remove_5fconst',['remove_const',['../structllvm_1_1remove__const.html',1,'llvm']]],
  ['remove_5fconst_3c_20const_20t_20_3e',['remove_const&lt; const T &gt;',['../structllvm_1_1remove__const_3_01const_01T_01_4.html',1,'llvm']]],
  ['remove_5fcv',['remove_cv',['../structllvm_1_1remove__cv.html',1,'llvm']]],
  ['remove_5fpointer',['remove_pointer',['../structllvm_1_1remove__pointer.html',1,'llvm']]],
  ['remove_5fpointer_3c_20t_20_2a_20_3e',['remove_pointer&lt; T * &gt;',['../structllvm_1_1remove__pointer_3_01T_01_5_01_4.html',1,'llvm']]],
  ['remove_5fpointer_3c_20t_20_2aconst_20_20_3e',['remove_pointer&lt; T *const  &gt;',['../structllvm_1_1remove__pointer_3_01T_01_5const_01_01_4.html',1,'llvm']]],
  ['remove_5fpointer_3c_20t_20_2aconst_20volatile_20_3e',['remove_pointer&lt; T *const volatile &gt;',['../structllvm_1_1remove__pointer_3_01T_01_5const_01volatile_01_4.html',1,'llvm']]],
  ['remove_5fpointer_3c_20t_20_2avolatile_20_3e',['remove_pointer&lt; T *volatile &gt;',['../structllvm_1_1remove__pointer_3_01T_01_5volatile_01_4.html',1,'llvm']]],
  ['remove_5freference',['remove_reference',['../structllvm_1_1remove__reference.html',1,'llvm']]],
  ['remove_5freference_3c_20t_20_26_20_3e',['remove_reference&lt; T &amp; &gt;',['../structllvm_1_1remove__reference_3_01T_01_6_01_4.html',1,'llvm']]],
  ['remove_5fvolatile',['remove_volatile',['../structllvm_1_1remove__volatile.html',1,'llvm']]],
  ['remove_5fvolatile_3c_20volatile_20t_20_3e',['remove_volatile&lt; volatile T &gt;',['../structllvm_1_1remove__volatile_3_01volatile_01T_01_4.html',1,'llvm']]],
  ['rerr',['rerr',['../structrerr.html',1,'']]],
  ['resource_5fsort',['resource_sort',['../structllvm_1_1resource__sort.html',1,'llvm']]],
  ['resourcepriorityqueue',['ResourcePriorityQueue',['../classllvm_1_1ResourcePriorityQueue.html',1,'llvm']]],
  ['resumeinst',['ResumeInst',['../classllvm_1_1ResumeInst.html',1,'llvm']]],
  ['returninst',['ReturnInst',['../classllvm_1_1ReturnInst.html',1,'llvm']]],
  ['reversepostordertraversal',['ReversePostOrderTraversal',['../classllvm_1_1ReversePostOrderTraversal.html',1,'llvm']]],
  ['rgpassmanager',['RGPassManager',['../classllvm_1_1RGPassManager.html',1,'llvm']]],
  ['rnsucciterator',['RNSuccIterator',['../classllvm_1_1RNSuccIterator.html',1,'llvm']]],
  ['rnsucciterator_3c_20flatit_3c_20nodetype_20_3e_20_3e',['RNSuccIterator&lt; FlatIt&lt; NodeType &gt; &gt;',['../classllvm_1_1RNSuccIterator_3_01FlatIt_3_01NodeType_01_4_01_4.html',1,'llvm']]],
  ['rounduptopoweroftwo',['RoundUpToPowerOfTwo',['../structllvm_1_1RoundUpToPowerOfTwo.html',1,'llvm']]],
  ['rounduptopoweroftwoh',['RoundUpToPowerOfTwoH',['../structllvm_1_1RoundUpToPowerOfTwoH.html',1,'llvm']]],
  ['rounduptopoweroftwoh_3c_20n_2c_20false_20_3e',['RoundUpToPowerOfTwoH&lt; N, false &gt;',['../structllvm_1_1RoundUpToPowerOfTwoH_3_01N_00_01false_01_4.html',1,'llvm']]],
  ['routines_5fcommand',['routines_command',['../structllvm_1_1MachO_1_1routines__command.html',1,'llvm::MachO']]],
  ['routines_5fcommand_5f64',['routines_command_64',['../structllvm_1_1MachO_1_1routines__command__64.html',1,'llvm::MachO']]],
  ['row',['Row',['../structllvm_1_1DWARFDebugLine_1_1Row.html',1,'llvm::DWARFDebugLine']]],
  ['rpath_5fcommand',['rpath_command',['../structllvm_1_1MachO_1_1rpath__command.html',1,'llvm::MachO']]],
  ['rtdyldmemorymanager',['RTDyldMemoryManager',['../classllvm_1_1RTDyldMemoryManager.html',1,'llvm']]],
  ['runtimedyld',['RuntimeDyld',['../classllvm_1_1RuntimeDyld.html',1,'llvm']]],
  ['runtimedyldelf',['RuntimeDyldELF',['../classllvm_1_1RuntimeDyldELF.html',1,'llvm']]],
  ['runtimedyldimpl',['RuntimeDyldImpl',['../classllvm_1_1RuntimeDyldImpl.html',1,'llvm']]],
  ['runtimedyldmacho',['RuntimeDyldMachO',['../classllvm_1_1RuntimeDyldMachO.html',1,'llvm']]],
  ['runtimefunction',['RuntimeFunction',['../structllvm_1_1Win64EH_1_1RuntimeFunction.html',1,'llvm::Win64EH']]],
  ['rwmuteximpl',['RWMutexImpl',['../classllvm_1_1sys_1_1RWMutexImpl.html',1,'llvm::sys']]]
];
