var searchData=
[
  ['vaarginst',['VAArgInst',['../classllvm_1_1VAArgInst.html',1,'llvm']]],
  ['vacopyinst',['VACopyInst',['../classllvm_1_1VACopyInst.html',1,'llvm']]],
  ['vaendinst',['VAEndInst',['../classllvm_1_1VAEndInst.html',1,'llvm']]],
  ['valid',['ValID',['../structllvm_1_1ValID.html',1,'llvm']]],
  ['value',['Value',['../classllvm_1_1Value.html',1,'llvm']]],
  ['value_5fdesc',['value_desc',['../structllvm_1_1cl_1_1value__desc.html',1,'llvm::cl']]],
  ['value_5fop_5fiterator',['value_op_iterator',['../classllvm_1_1User_1_1value__op__iterator.html',1,'llvm::User']]],
  ['value_5fuse_5fiterator',['value_use_iterator',['../classllvm_1_1value__use__iterator.html',1,'llvm']]],
  ['valueenumerator',['ValueEnumerator',['../classllvm_1_1ValueEnumerator.html',1,'llvm']]],
  ['valuehandlebase',['ValueHandleBase',['../classllvm_1_1ValueHandleBase.html',1,'llvm']]],
  ['valuemap',['ValueMap',['../classllvm_1_1ValueMap.html',1,'llvm']]],
  ['valuemap_3c_20const_20allocainst_20_2a_2c_20ssplayoutkind_20_3e',['ValueMap&lt; const AllocaInst *, SSPLayoutKind &gt;',['../classllvm_1_1ValueMap.html',1,'llvm']]],
  ['valuemap_3c_20const_20basicblock_20_2a_2c_20void_20_2a_20_3e',['ValueMap&lt; const BasicBlock *, void * &gt;',['../classllvm_1_1ValueMap.html',1,'llvm']]],
  ['valuemap_3c_20const_20globalvalue_20_2a_2c_20void_20_2a_2c_20addressmapconfig_20_3e',['ValueMap&lt; const GlobalValue *, void *, AddressMapConfig &gt;',['../classllvm_1_1ValueMap.html',1,'llvm']]],
  ['valuemap_3c_20const_20llvm_3a_3aglobalvalue_20_2a_2c_20const_20llvm_3a_3amipscallentry_20_2a_20_3e',['ValueMap&lt; const llvm::GlobalValue *, const llvm::MipsCallEntry * &gt;',['../classllvm_1_1ValueMap.html',1,'llvm']]],
  ['valuemapcallbackvh',['ValueMapCallbackVH',['../classllvm_1_1ValueMapCallbackVH.html',1,'llvm']]],
  ['valuemapconfig',['ValueMapConfig',['../structllvm_1_1ValueMapConfig.html',1,'llvm']]],
  ['valuemapconfig_3c_20const_20allocainst_20_2a_20_3e',['ValueMapConfig&lt; const AllocaInst * &gt;',['../structllvm_1_1ValueMapConfig.html',1,'llvm']]],
  ['valuemapconfig_3c_20const_20basicblock_20_2a_20_3e',['ValueMapConfig&lt; const BasicBlock * &gt;',['../structllvm_1_1ValueMapConfig.html',1,'llvm']]],
  ['valuemapconfig_3c_20const_20globalvalue_20_2a_20_3e',['ValueMapConfig&lt; const GlobalValue * &gt;',['../structllvm_1_1ValueMapConfig.html',1,'llvm']]],
  ['valuemapconfig_3c_20const_20llvm_3a_3aglobalvalue_20_2a_20_3e',['ValueMapConfig&lt; const llvm::GlobalValue * &gt;',['../structllvm_1_1ValueMapConfig.html',1,'llvm']]],
  ['valuemapconstiterator',['ValueMapConstIterator',['../classllvm_1_1ValueMapConstIterator.html',1,'llvm']]],
  ['valuemapiterator',['ValueMapIterator',['../classllvm_1_1ValueMapIterator.html',1,'llvm']]],
  ['valuemaptyperemapper',['ValueMapTypeRemapper',['../classllvm_1_1ValueMapTypeRemapper.html',1,'llvm']]],
  ['valuematerializer',['ValueMaterializer',['../classllvm_1_1ValueMaterializer.html',1,'llvm']]],
  ['valuesclass',['ValuesClass',['../classllvm_1_1cl_1_1ValuesClass.html',1,'llvm::cl']]],
  ['valuesymboltable',['ValueSymbolTable',['../classllvm_1_1ValueSymbolTable.html',1,'llvm']]],
  ['valuetypeactionimpl',['ValueTypeActionImpl',['../classllvm_1_1TargetLoweringBase_1_1ValueTypeActionImpl.html',1,'llvm::TargetLoweringBase']]],
  ['valuetypeproxy',['ValueTypeProxy',['../structllvm_1_1ValueMapIterator_1_1ValueTypeProxy.html',1,'llvm::ValueMapIterator']]],
  ['valuetypeproxy',['ValueTypeProxy',['../structllvm_1_1ValueMapConstIterator_1_1ValueTypeProxy.html',1,'llvm::ValueMapConstIterator']]],
  ['varbitinit',['VarBitInit',['../classllvm_1_1VarBitInit.html',1,'llvm']]],
  ['variadicfunction',['VariadicFunction',['../structllvm_1_1VariadicFunction.html',1,'llvm']]],
  ['variadicfunction1',['VariadicFunction1',['../structllvm_1_1VariadicFunction1.html',1,'llvm']]],
  ['variadicfunction2',['VariadicFunction2',['../structllvm_1_1VariadicFunction2.html',1,'llvm']]],
  ['variadicfunction3',['VariadicFunction3',['../structllvm_1_1VariadicFunction3.html',1,'llvm']]],
  ['variadicoperandtraits',['VariadicOperandTraits',['../structllvm_1_1VariadicOperandTraits.html',1,'llvm']]],
  ['variadicoperandtraits_3c_20branchinst_2c_201_20_3e',['VariadicOperandTraits&lt; BranchInst, 1 &gt;',['../structllvm_1_1VariadicOperandTraits.html',1,'llvm']]],
  ['variadicoperandtraits_3c_20callinst_2c_201_20_3e',['VariadicOperandTraits&lt; CallInst, 1 &gt;',['../structllvm_1_1VariadicOperandTraits.html',1,'llvm']]],
  ['variadicoperandtraits_3c_20constantarray_20_3e',['VariadicOperandTraits&lt; ConstantArray &gt;',['../structllvm_1_1VariadicOperandTraits.html',1,'llvm']]],
  ['variadicoperandtraits_3c_20constantexpr_2c_201_20_3e',['VariadicOperandTraits&lt; ConstantExpr, 1 &gt;',['../structllvm_1_1VariadicOperandTraits.html',1,'llvm']]],
  ['variadicoperandtraits_3c_20constantstruct_20_3e',['VariadicOperandTraits&lt; ConstantStruct &gt;',['../structllvm_1_1VariadicOperandTraits.html',1,'llvm']]],
  ['variadicoperandtraits_3c_20constantvector_20_3e',['VariadicOperandTraits&lt; ConstantVector &gt;',['../structllvm_1_1VariadicOperandTraits.html',1,'llvm']]],
  ['variadicoperandtraits_3c_20getelementptrconstantexpr_2c_201_20_3e',['VariadicOperandTraits&lt; GetElementPtrConstantExpr, 1 &gt;',['../structllvm_1_1VariadicOperandTraits.html',1,'llvm']]],
  ['variadicoperandtraits_3c_20getelementptrinst_2c_201_20_3e',['VariadicOperandTraits&lt; GetElementPtrInst, 1 &gt;',['../structllvm_1_1VariadicOperandTraits.html',1,'llvm']]],
  ['variadicoperandtraits_3c_20invokeinst_2c_203_20_3e',['VariadicOperandTraits&lt; InvokeInst, 3 &gt;',['../structllvm_1_1VariadicOperandTraits.html',1,'llvm']]],
  ['variadicoperandtraits_3c_20returninst_20_3e',['VariadicOperandTraits&lt; ReturnInst &gt;',['../structllvm_1_1VariadicOperandTraits.html',1,'llvm']]],
  ['varinfo',['VarInfo',['../structllvm_1_1LiveVariables_1_1VarInfo.html',1,'llvm::LiveVariables']]],
  ['varinit',['VarInit',['../classllvm_1_1VarInit.html',1,'llvm']]],
  ['varlistelementinit',['VarListElementInit',['../classllvm_1_1VarListElementInit.html',1,'llvm']]],
  ['vastartinst',['VAStartInst',['../classllvm_1_1VAStartInst.html',1,'llvm']]],
  ['vector',['Vector',['../classPBQP_1_1Vector.html',1,'PBQP']]],
  ['vectorizeconfig',['VectorizeConfig',['../structllvm_1_1VectorizeConfig.html',1,'llvm']]],
  ['vectortype',['VectorType',['../classllvm_1_1VectorType.html',1,'llvm']]],
  ['version_5fmin_5fcommand',['version_min_command',['../structllvm_1_1MachO_1_1version__min__command.html',1,'llvm::MachO']]],
  ['virtreg2indexfunctor',['VirtReg2IndexFunctor',['../structllvm_1_1VirtReg2IndexFunctor.html',1,'llvm']]],
  ['virtregauxinfo',['VirtRegAuxInfo',['../classllvm_1_1VirtRegAuxInfo.html',1,'llvm']]],
  ['virtreginfo',['VirtRegInfo',['../structllvm_1_1MachineOperandIteratorBase_1_1VirtRegInfo.html',1,'llvm::MachineOperandIteratorBase']]],
  ['virtregmap',['VirtRegMap',['../classllvm_1_1VirtRegMap.html',1,'llvm']]],
  ['vliwmachinescheduler',['VLIWMachineScheduler',['../classllvm_1_1VLIWMachineScheduler.html',1,'llvm']]],
  ['vliwpacketizerlist',['VLIWPacketizerList',['../classllvm_1_1VLIWPacketizerList.html',1,'llvm']]],
  ['vliwresourcemodel',['VLIWResourceModel',['../classllvm_1_1VLIWResourceModel.html',1,'llvm']]],
  ['vninfo',['VNInfo',['../classllvm_1_1VNInfo.html',1,'llvm']]],
  ['vreg2sunit',['VReg2SUnit',['../structllvm_1_1VReg2SUnit.html',1,'llvm']]],
  ['vtsdnode',['VTSDNode',['../classllvm_1_1VTSDNode.html',1,'llvm']]]
];
