var searchData=
[
  ['dagcombinerinfo',['DAGCombinerInfo',['../structllvm_1_1TargetLowering_1_1DAGCombinerInfo.html',1,'llvm::TargetLowering']]],
  ['dagdeltaalgorithm',['DAGDeltaAlgorithm',['../classllvm_1_1DAGDeltaAlgorithm.html',1,'llvm']]],
  ['daginit',['DagInit',['../classllvm_1_1DagInit.html',1,'llvm']]],
  ['dagrecty',['DagRecTy',['../classllvm_1_1DagRecTy.html',1,'llvm']]],
  ['dagtypelegalizer',['DAGTypeLegalizer',['../classllvm_1_1DAGTypeLegalizer.html',1,'llvm']]],
  ['dagupdatelistener',['DAGUpdateListener',['../structllvm_1_1SelectionDAG_1_1DAGUpdateListener.html',1,'llvm::SelectionDAG']]],
  ['data_5fdirectory',['data_directory',['../structllvm_1_1object_1_1data__directory.html',1,'llvm::object']]],
  ['data_5fin_5fcode_5fentry',['data_in_code_entry',['../structllvm_1_1MachO_1_1data__in__code__entry.html',1,'llvm::MachO']]],
  ['datadirectory',['DataDirectory',['../structllvm_1_1COFF_1_1DataDirectory.html',1,'llvm::COFF']]],
  ['dataextractor',['DataExtractor',['../classllvm_1_1DataExtractor.html',1,'llvm']]],
  ['datalayout',['DataLayout',['../classllvm_1_1DataLayout.html',1,'llvm']]],
  ['datarefimpl',['DataRefImpl',['../unionllvm_1_1object_1_1DataRefImpl.html',1,'llvm::object']]],
  ['dataregiondata',['DataRegionData',['../structllvm_1_1DataRegionData.html',1,'llvm']]],
  ['datastreamer',['DataStreamer',['../classllvm_1_1DataStreamer.html',1,'llvm']]],
  ['datatype',['DataType',['../classDataType.html',1,'']]],
  ['dbarriermapper',['DBarrierMapper',['../structllvm_1_1A64DB_1_1DBarrierMapper.html',1,'llvm::A64DB']]],
  ['dbgdeclareinst',['DbgDeclareInst',['../classllvm_1_1DbgDeclareInst.html',1,'llvm']]],
  ['dbginfointrinsic',['DbgInfoIntrinsic',['../classllvm_1_1DbgInfoIntrinsic.html',1,'llvm']]],
  ['dbgvalueinst',['DbgValueInst',['../classllvm_1_1DbgValueInst.html',1,'llvm']]],
  ['dbgvariable',['DbgVariable',['../classllvm_1_1DbgVariable.html',1,'llvm']]],
  ['dcmapper',['DCMapper',['../structllvm_1_1A64DC_1_1DCMapper.html',1,'llvm::A64DC']]],
  ['debuginfofinder',['DebugInfoFinder',['../classllvm_1_1DebugInfoFinder.html',1,'llvm']]],
  ['debugir',['DebugIR',['../classllvm_1_1DebugIR.html',1,'llvm']]],
  ['debugloc',['DebugLoc',['../classllvm_1_1DebugLoc.html',1,'llvm']]],
  ['debugrecvh',['DebugRecVH',['../classllvm_1_1DebugRecVH.html',1,'llvm']]],
  ['decimalinfo',['decimalInfo',['../structdecimalInfo.html',1,'']]],
  ['defaultcontextualfoldingsettrait',['DefaultContextualFoldingSetTrait',['../structllvm_1_1DefaultContextualFoldingSetTrait.html',1,'llvm']]],
  ['defaultdotgraphtraits',['DefaultDOTGraphTraits',['../structllvm_1_1DefaultDOTGraphTraits.html',1,'llvm']]],
  ['defaultfoldingsettrait',['DefaultFoldingSetTrait',['../structllvm_1_1DefaultFoldingSetTrait.html',1,'llvm']]],
  ['defaultfoldingsettrait_3c_20mdnode_20_3e',['DefaultFoldingSetTrait&lt; MDNode &gt;',['../structllvm_1_1DefaultFoldingSetTrait.html',1,'llvm']]],
  ['defaultfoldingsettrait_3c_20scev_20_3e',['DefaultFoldingSetTrait&lt; SCEV &gt;',['../structllvm_1_1DefaultFoldingSetTrait.html',1,'llvm']]],
  ['defaultfoldingsettrait_3c_20sdvtlistnode_20_3e',['DefaultFoldingSetTrait&lt; SDVTListNode &gt;',['../structllvm_1_1DefaultFoldingSetTrait.html',1,'llvm']]],
  ['defaultvliwscheduler',['DefaultVLIWScheduler',['../classllvm_1_1DefaultVLIWScheduler.html',1,'llvm']]],
  ['definit',['DefInit',['../classllvm_1_1DefInit.html',1,'llvm']]],
  ['defusechain_5fiterator',['defusechain_iterator',['../classllvm_1_1MachineRegisterInfo_1_1defusechain__iterator.html',1,'llvm::MachineRegisterInfo']]],
  ['delegate',['Delegate',['../classllvm_1_1MachineRegisterInfo_1_1Delegate.html',1,'llvm::MachineRegisterInfo']]],
  ['delegate',['Delegate',['../classllvm_1_1LiveRangeEdit_1_1Delegate.html',1,'llvm::LiveRangeEdit']]],
  ['deltaalgorithm',['DeltaAlgorithm',['../classllvm_1_1DeltaAlgorithm.html',1,'llvm']]],
  ['densemap',['DenseMap',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20analysisid_2c_20llvm_3a_3aidentifyingpassptr_20_3e',['DenseMap&lt; AnalysisID, llvm::IdentifyingPassPtr &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20analysisid_2c_20llvm_3a_3apass_20_2a_20_3e',['DenseMap&lt; AnalysisID, llvm::Pass * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20astcallbackvh_2c_20aliasset_3a_3apointerrec_20_2a_2c_20astcallbackvhdensemapinfo_20_3e',['DenseMap&lt; ASTCallbackVH, AliasSet::PointerRec *, ASTCallbackVHDenseMapInfo &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20attributeset_2c_20unsigned_20_3e',['DenseMap&lt; AttributeSet, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20basicblock_20_2a_2c_20region_20_2a_20_3e',['DenseMap&lt; BasicBlock *, Region * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20blkt_20_2a_2c_20bbinfo_20_2a_20_3e',['DenseMap&lt; BlkT *, BBInfo * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20blockt_20_2a_2c_20branchprobability_20_3e',['DenseMap&lt; BlockT *, BranchProbability &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20blockt_20_2a_2c_20loopt_20_2a_20_3e',['DenseMap&lt; BlockT *, LoopT * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20blockt_20_2a_2c_20unsigned_20_3e',['DenseMap&lt; BlockT *, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20blockt_20_2a_2c_20llvm_3a_3ablockfrequency_20_3e',['DenseMap&lt; const BlockT *, llvm::BlockFrequency &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20function_20_2a_2c_20gcfunctioninfo_20_2a_20_3e',['DenseMap&lt; const Function *, GCFunctionInfo * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20function_20_2a_2c_20returninst_20_2a_20_3e',['DenseMap&lt; const Function *, ReturnInst * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20function_20_2a_2c_20unsigned_20_3e',['DenseMap&lt; const Function *, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20instruction_20_2a_2c_20unsigned_20_3e',['DenseMap&lt; const Instruction *, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3aallocainst_20_2a_2c_20int_20_3e',['DenseMap&lt; const llvm::AllocaInst *, int &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3aargument_20_2a_2c_20int_20_3e',['DenseMap&lt; const llvm::Argument *, int &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3abasicblock_20_2a_2c_20llvm_3a_3ablockfrequency_20_3e',['DenseMap&lt; const llvm::BasicBlock *, llvm::BlockFrequency &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3abasicblock_20_2a_2c_20llvm_3a_3amachinebasicblock_20_2a_20_3e',['DenseMap&lt; const llvm::BasicBlock *, llvm::MachineBasicBlock * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3abasicblock_20_2a_2c_20unsigned_20_3e',['DenseMap&lt; const llvm::BasicBlock *, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3aconstant_20_2a_2c_20unsigned_20_3e',['DenseMap&lt; const llvm::Constant *, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3adie_20_2a_2c_20llvm_3a_3acompileunit_20_2a_20_3e',['DenseMap&lt; const llvm::DIE *, llvm::CompileUnit * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3adie_20_2a_2c_20unsigned_20_3e',['DenseMap&lt; const llvm::DIE *, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3aglobalvalue_20_2a_2c_20unsigned_20_3e',['DenseMap&lt; const llvm::GlobalValue *, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3ainstruction_20_2a_2c_20llvm_3a_3asmallvector_20_3e',['DenseMap&lt; const llvm::Instruction *, llvm::SmallVector &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3aloop_20_2a_2c_20backedgetakeninfo_20_3e',['DenseMap&lt; const llvm::Loop *, BackedgeTakenInfo &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3amachinebasicblock_20_2a_2c_20llvm_3a_3ablockfrequency_20_3e',['DenseMap&lt; const llvm::MachineBasicBlock *, llvm::BlockFrequency &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3amachineinstr_20_2a_2c_20llvm_3a_3amachinetracemetrics_3a_3ainstrcycles_20_3e',['DenseMap&lt; const llvm::MachineInstr *, llvm::MachineTraceMetrics::InstrCycles &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3amachineinstr_20_2a_2c_20llvm_3a_3amcsymbol_20_2a_20_3e',['DenseMap&lt; const llvm::MachineInstr *, llvm::MCSymbol * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3amcsection_20_2a_2c_20llvm_3a_3amclinesection_20_2a_20_3e',['DenseMap&lt; const llvm::MCSection *, llvm::MCLineSection * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3amcsection_20_2a_2c_20llvm_3a_3amcsectiondata_20_2a_20_3e',['DenseMap&lt; const llvm::MCSection *, llvm::MCSectionData * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3amcsectiondata_20_2a_2c_20llvm_3a_3amcfragment_20_2a_20_3e',['DenseMap&lt; const llvm::MCSectionData *, llvm::MCFragment * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3amcsectiondata_20_2a_2c_20std_3a_3avector_3c_20macho_3a_3aany_5frelocation_5finfo_20_3e_20_3e',['DenseMap&lt; const llvm::MCSectionData *, std::vector&lt; MachO::any_relocation_info &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3amcsectiondata_20_2a_2c_20unsigned_20_3e',['DenseMap&lt; const llvm::MCSectionData *, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3amcsymbol_20_2a_2c_20llvm_3a_3amcsymboldata_20_2a_20_3e',['DenseMap&lt; const llvm::MCSymbol *, llvm::MCSymbolData * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3amcsymbol_20_2a_2c_20uint64_5ft_20_3e',['DenseMap&lt; const llvm::MCSymbol *, uint64_t &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3amcsymbol_20_2a_2c_20unsigned_20_3e',['DenseMap&lt; const llvm::MCSymbol *, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3amdnode_20_2a_2c_20llvm_3a_3acompileunit_20_2a_20_3e',['DenseMap&lt; const llvm::MDNode *, llvm::CompileUnit * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3amdnode_20_2a_2c_20llvm_3a_3adbgvariable_20_2a_20_3e',['DenseMap&lt; const llvm::MDNode *, llvm::DbgVariable * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3amdnode_20_2a_2c_20llvm_3a_3adie_20_2a_20_3e',['DenseMap&lt; const llvm::MDNode *, llvm::DIE * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3amdnode_20_2a_2c_20llvm_3a_3adieentry_20_2a_20_3e',['DenseMap&lt; const llvm::MDNode *, llvm::DIEEntry * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3amdnode_20_2a_2c_20llvm_3a_3alexicalscope_20_2a_20_3e',['DenseMap&lt; const llvm::MDNode *, llvm::LexicalScope * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3amdnode_20_2a_2c_20unsigned_20_3e',['DenseMap&lt; const llvm::MDNode *, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3aobject_3a_3aelf_5fsym_5fimpl_20_2a_2c_20elf_3a_3aelf64_5fword_20_3e',['DenseMap&lt; const llvm::object::Elf_Sym_Impl *, ELF::Elf64_Word &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3ascev_20_2a_2c_20const_20llvm_3a_3aloop_20_2a_20_3e',['DenseMap&lt; const llvm::SCEV *, const llvm::Loop * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3ascev_20_2a_2c_20llvm_3a_3aconstantrange_20_3e',['DenseMap&lt; const llvm::SCEV *, llvm::ConstantRange &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3ascev_20_2a_2c_20llvm_3a_3asmallvector_3c_20std_3a_3apair_3c_20const_20llvm_3a_3abasicblock_20_2a_2c_20blockdisposition_20_3e_2c_202_20_3e_20_3e',['DenseMap&lt; const llvm::SCEV *, llvm::SmallVector&lt; std::pair&lt; const llvm::BasicBlock *, BlockDisposition &gt;, 2 &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3ascev_20_2a_2c_20llvm_3a_3asmallvector_3c_20std_3a_3apair_3c_20const_20llvm_3a_3aloop_20_2a_2c_20const_20llvm_3a_3ascev_20_2a_20_3e_2c_202_20_3e_20_3e',['DenseMap&lt; const llvm::SCEV *, llvm::SmallVector&lt; std::pair&lt; const llvm::Loop *, const llvm::SCEV * &gt;, 2 &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3ascev_20_2a_2c_20llvm_3a_3asmallvector_3c_20std_3a_3apair_3c_20const_20llvm_3a_3aloop_20_2a_2c_20loopdisposition_20_3e_2c_202_20_3e_20_3e',['DenseMap&lt; const llvm::SCEV *, llvm::SmallVector&lt; std::pair&lt; const llvm::Loop *, LoopDisposition &gt;, 2 &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3avalue_20_2a_2c_20char_2c_20densemapinfo_3c_20const_20llvm_3a_3avalue_20_2a_20_3e_20_3e',['DenseMap&lt; const llvm::Value *, char, DenseMapInfo&lt; const llvm::Value * &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3avalue_20_2a_2c_20danglingdebuginfo_20_3e',['DenseMap&lt; const llvm::Value *, DanglingDebugInfo &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3avalue_20_2a_2c_20llvm_3a_3asdvalue_20_3e',['DenseMap&lt; const llvm::Value *, llvm::SDValue &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20llvm_3a_3avalue_20_2a_2c_20unsigned_20_3e',['DenseMap&lt; const llvm::Value *, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20machineinstr_20_2a_2c_20slotindex_20_3e',['DenseMap&lt; const MachineInstr *, SlotIndex &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20mcexpr_20_2a_2c_20unsigned_20_3e',['DenseMap&lt; const MCExpr *, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20mcsection_20_2a_2c_20smallvector_3c_20symbolcu_2c_208_20_3e_20_3e',['DenseMap&lt; const MCSection *, SmallVector&lt; SymbolCU, 8 &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20mcsectiondata_20_2a_2c_20uint64_5ft_20_3e',['DenseMap&lt; const MCSectionData *, uint64_t &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20mdnode_20_2a_2c_20smallvector_3c_20const_20machineinstr_20_2a_2c_204_20_3e_20_3e',['DenseMap&lt; const MDNode *, SmallVector&lt; const MachineInstr *, 4 &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20mdstring_20_2a_2c_20mdnode_20_2a_20_3e',['DenseMap&lt; const MDString *, MDNode * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20sdnode_20_2a_2c_20smallvector_3c_20sddbgvalue_20_2a_2c_202_20_3e_20_3e',['DenseMap&lt; const SDNode *, SmallVector&lt; SDDbgValue *, 2 &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20targetregisterclass_20_2a_2c_20vregmap_20_3e',['DenseMap&lt; const TargetRegisterClass *, VRegMap &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20value_20_2a_2c_20unsigned_20_3e',['DenseMap&lt; const Value *, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20const_20value_20_2a_2c_20weakevaltype_20_3e',['DenseMap&lt; const Value *, WeakEvalType &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20constantarray_20_2a_2c_20char_2c_20mapinfo_20_3e',['DenseMap&lt; ConstantArray *, char, MapInfo &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20constantclass_20_2a_2c_20char_2c_20mapinfo_20_3e',['DenseMap&lt; ConstantClass *, char, MapInfo &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20constantstruct_20_2a_2c_20char_2c_20mapinfo_20_3e',['DenseMap&lt; ConstantStruct *, char, MapInfo &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20constantvector_20_2a_2c_20char_2c_20mapinfo_20_3e',['DenseMap&lt; ConstantVector *, char, MapInfo &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20densemapapfloatkeyinfo_3a_3akeyty_2c_20constantfp_20_2a_2c_20densemapapfloatkeyinfo_20_3e',['DenseMap&lt; DenseMapAPFloatKeyInfo::KeyTy, ConstantFP *, DenseMapAPFloatKeyInfo &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20densemapapintkeyinfo_3a_3akeyty_2c_20constantint_20_2a_2c_20densemapapintkeyinfo_20_3e',['DenseMap&lt; DenseMapAPIntKeyInfo::KeyTy, ConstantInt *, DenseMapAPIntKeyInfo &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20edge_2c_20uint32_5ft_20_3e',['DenseMap&lt; Edge, uint32_t &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20function_20_2a_2c_20functionanalysisresultlistt_20_3e',['DenseMap&lt; Function *, FunctionAnalysisResultListT &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20functiontype_20_2a_2c_20bool_2c_20functiontypekeyinfo_20_3e',['DenseMap&lt; FunctionType *, bool, FunctionTypeKeyInfo &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20instruction_20_2a_2c_20memdepresult_20_3e',['DenseMap&lt; Instruction *, MemDepResult &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20instruction_20_2a_2c_20perinstnlinfo_20_3e',['DenseMap&lt; Instruction *, PerInstNLInfo &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20instruction_20_2a_2c_20smallptrset_3c_20instruction_20_2a_2c_204_20_3e_20_3e',['DenseMap&lt; Instruction *, SmallPtrSet&lt; Instruction *, 4 &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20instruction_20_2a_2c_20smallptrset_3c_20valueisloadpair_2c_204_20_3e_20_3e',['DenseMap&lt; Instruction *, SmallPtrSet&lt; ValueIsLoadPair, 4 &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20k_2c_20llvm_3a_3ascopedhashtableval_20_2a_2c_20kinfo_20_3e',['DenseMap&lt; K, llvm::ScopedHashTableVal *, KInfo &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20lexicalscope_20_2a_2c_20smallvector_3c_20dbgvariable_20_2a_2c_208_20_3e_20_3e',['DenseMap&lt; LexicalScope *, SmallVector&lt; DbgVariable *, 8 &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3aassertingvh_3c_20llvm_3a_3abasicblock_20_3e_2c_20addrlabelsymentry_20_3e',['DenseMap&lt; llvm::AssertingVH&lt; llvm::BasicBlock &gt;, AddrLabelSymEntry &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3aassertingvh_3c_20llvm_3a_3afunction_20_3e_2c_20std_3a_3avector_3c_20llvm_3a_3amcsymbol_20_2a_20_3e_20_3e',['DenseMap&lt; llvm::AssertingVH&lt; llvm::Function &gt;, std::vector&lt; llvm::MCSymbol * &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3aassertingvh_3c_20llvm_3a_3amdnode_20_3e_2c_20std_3a_3astring_20_3e',['DenseMap&lt; llvm::AssertingVH&lt; llvm::MDNode &gt;, std::string &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3aattributeset_2c_20unsigned_20_3e',['DenseMap&lt; llvm::AttributeSet, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3abasicblock_20_2a_2c_20branchprobability_20_3e',['DenseMap&lt; llvm::BasicBlock *, BranchProbability &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3abasicblock_20_2a_2c_20domtreenodebase_3c_20llvm_3a_3abasicblock_20_3e_20_2a_20_3e',['DenseMap&lt; llvm::BasicBlock *, DomTreeNodeBase&lt; llvm::BasicBlock &gt; * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3abasicblock_20_2a_2c_20llvm_3a_3abasicblock_20_2a_20_3e',['DenseMap&lt; llvm::BasicBlock *, llvm::BasicBlock * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3abasicblock_20_2a_2c_20llvm_3a_3abasicblock_20_2a_2a_20_3e',['DenseMap&lt; llvm::BasicBlock *, llvm::BasicBlock ** &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3abasicblock_20_2a_2c_20llvm_3a_3adominatortreebase_3a_3ainforec_20_3e',['DenseMap&lt; llvm::BasicBlock *, llvm::DominatorTreeBase::InfoRec &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3abasicblock_20_2a_2c_20llvm_3a_3aloop_20_2a_20_3e',['DenseMap&lt; llvm::BasicBlock *, llvm::Loop * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3abasicblock_20_2a_2c_20unsigned_20_3e',['DenseMap&lt; llvm::BasicBlock *, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3adebugloc_2c_20llvm_3a_3alexicalscope_20_2a_20_3e',['DenseMap&lt; llvm::DebugLoc, llvm::LexicalScope * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3adie_20_2a_2c_20const_20llvm_3a_3amdnode_20_2a_20_3e',['DenseMap&lt; llvm::DIE *, const llvm::MDNode * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3afunction_20_2a_2c_20std_3a_3avector_3c_20blockaddrrefty_20_3e_20_3e',['DenseMap&lt; llvm::Function *, std::vector&lt; BlockAddrRefTy &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3afunction_20_2a_2c_20uint64_5ft_20_3e',['DenseMap&lt; llvm::Function *, uint64_t &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3ainstruction_20_2a_2c_20std_3a_3avector_3c_20mdref_20_3e_20_3e',['DenseMap&lt; llvm::Instruction *, std::vector&lt; MDRef &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3ainstruction_20_2a_2c_20unsigned_20_3e',['DenseMap&lt; llvm::Instruction *, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3amachinebasicblock_20_2a_2c_20branchprobability_20_3e',['DenseMap&lt; llvm::MachineBasicBlock *, BranchProbability &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3amachinebasicblock_20_2a_2c_20domtreenodebase_3c_20llvm_3a_3amachinebasicblock_20_3e_20_2a_20_3e',['DenseMap&lt; llvm::MachineBasicBlock *, DomTreeNodeBase&lt; llvm::MachineBasicBlock &gt; * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3amachinebasicblock_20_2a_2c_20llvm_3a_3adominatortreebase_3a_3ainforec_20_3e',['DenseMap&lt; llvm::MachineBasicBlock *, llvm::DominatorTreeBase::InfoRec &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3amachinebasicblock_20_2a_2c_20llvm_3a_3amachinebasicblock_20_2a_20_3e',['DenseMap&lt; llvm::MachineBasicBlock *, llvm::MachineBasicBlock * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3amachinebasicblock_20_2a_2c_20llvm_3a_3amachineloop_20_2a_20_3e',['DenseMap&lt; llvm::MachineBasicBlock *, llvm::MachineLoop * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3amachinebasicblock_20_2a_2c_20llvm_3a_3asmallvector_3c_20unsigned_2c_204_20_3e_20_3e',['DenseMap&lt; llvm::MachineBasicBlock *, llvm::SmallVector&lt; unsigned, 4 &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3amachinebasicblock_20_2a_2c_20unsigned_20_3e',['DenseMap&lt; llvm::MachineBasicBlock *, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3amachineconstantpoolvalue_20_2a_2c_20char_2c_20densemapinfo_3c_20llvm_3a_3amachineconstantpoolvalue_20_2a_20_3e_20_3e',['DenseMap&lt; llvm::MachineConstantPoolValue *, char, DenseMapInfo&lt; llvm::MachineConstantPoolValue * &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3amachineinstr_20_2a_2c_20llvm_3a_3asunit_20_2a_20_3e',['DenseMap&lt; llvm::MachineInstr *, llvm::SUnit * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3amachineinstr_20_2a_2c_20unsigned_20_3e',['DenseMap&lt; llvm::MachineInstr *, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3amcsymbol_20_2a_2c_20llvm_3a_3asmallvector_3c_20unsigned_2c_204_20_3e_20_3e',['DenseMap&lt; llvm::MCSymbol *, llvm::SmallVector&lt; unsigned, 4 &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3amcsymbol_20_2a_2c_20stubvaluety_20_3e',['DenseMap&lt; llvm::MCSymbol *, StubValueTy &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3amcsymbol_20_2a_2c_20unsigned_20_3e',['DenseMap&lt; llvm::MCSymbol *, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3amcsymbol_20const_20_2a_2c_20char_2c_20densemapinfo_3c_20llvm_3a_3amcsymbol_20const_20_2a_20_3e_20_3e',['DenseMap&lt; llvm::MCSymbol const *, char, DenseMapInfo&lt; llvm::MCSymbol const * &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3amdnode_20_2a_2c_20int_20_3e',['DenseMap&lt; llvm::MDNode *, int &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3apass_20_2a_2c_20llvm_3a_3aanalysisusage_20_2a_20_3e',['DenseMap&lt; llvm::Pass *, llvm::AnalysisUsage * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3apass_20_2a_2c_20llvm_3a_3apass_20_2a_20_3e',['DenseMap&lt; llvm::Pass *, llvm::Pass * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3apass_20_2a_2c_20llvm_3a_3asmallptrset_3c_20llvm_3a_3apass_20_2a_2c_208_20_3e_20_3e',['DenseMap&lt; llvm::Pass *, llvm::SmallPtrSet&lt; llvm::Pass *, 8 &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3aphinode_20_2a_2c_20llvm_3a_3aconstant_20_2a_20_3e',['DenseMap&lt; llvm::PHINode *, llvm::Constant * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3apointertype_20_2a_2c_20llvm_3a_3aconstantpointernull_20_2a_20_3e',['DenseMap&lt; llvm::PointerType *, llvm::ConstantPointerNull * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3astructtype_20_2a_2c_20unsigned_20_3e',['DenseMap&lt; llvm::StructType *, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3atype_20_2a_2c_20char_2c_20densemapinfo_3c_20llvm_3a_3atype_20_2a_20_3e_20_3e',['DenseMap&lt; llvm::Type *, char, DenseMapInfo&lt; llvm::Type * &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3atype_20_2a_2c_20llvm_3a_3aconstantaggregatezero_20_2a_20_3e',['DenseMap&lt; llvm::Type *, llvm::ConstantAggregateZero * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3atype_20_2a_2c_20llvm_3a_3apointertype_20_2a_20_3e',['DenseMap&lt; llvm::Type *, llvm::PointerType * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3atype_20_2a_2c_20llvm_3a_3aundefvalue_20_2a_20_3e',['DenseMap&lt; llvm::Type *, llvm::UndefValue * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3avalue_20_2a_2c_20char_2c_20densemapinfo_3c_20llvm_3a_3avalue_20_2a_20_3e_20_3e',['DenseMap&lt; llvm::Value *, char, DenseMapInfo&lt; llvm::Value * &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20llvm_3a_3avalue_20_2a_2c_20latticeval_20_3e',['DenseMap&lt; llvm::Value *, LatticeVal &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20module_20_2a_2c_20objectimage_20_2a_20_3e',['DenseMap&lt; Module *, ObjectImage * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20nodet_20_2a_2c_20domtreenodebase_3c_20nodet_20_3e_20_2a_20_3e',['DenseMap&lt; NodeT *, DomTreeNodeBase&lt; NodeT &gt; * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20nodet_20_2a_2c_20llvm_3a_3adominatortreebase_3a_3ainforec_20_3e',['DenseMap&lt; NodeT *, llvm::DominatorTreeBase::InfoRec &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20nodet_20_2a_2c_20nodet_20_2a_20_3e',['DenseMap&lt; NodeT *, NodeT * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20nodetype_20_2a_2c_20unsigned_20_3e',['DenseMap&lt; NodeType *, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20scevcallbackvh_2c_20const_20scev_20_2a_2c_20densemapinfo_3c_20value_20_2a_20_3e_20_3e',['DenseMap&lt; SCEVCallbackVH, const SCEV *, DenseMapInfo&lt; Value * &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20std_3a_3apair_3c_20llvm_3a_3afunction_20_2a_2c_20llvm_3a_3abasicblock_20_2a_20_3e_2c_20llvm_3a_3ablockaddress_20_2a_20_3e',['DenseMap&lt; std::pair&lt; llvm::Function *, llvm::BasicBlock * &gt;, llvm::BlockAddress * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20std_3a_3apair_3c_20llvm_3a_3amdnode_20_2a_2c_20llvm_3a_3amdnode_20_2a_20_3e_2c_20int_20_3e',['DenseMap&lt; std::pair&lt; llvm::MDNode *, llvm::MDNode * &gt;, int &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20std_3a_3apair_3c_20llvm_3a_3atype_20_2a_2c_20uint64_5ft_20_3e_2c_20llvm_3a_3aarraytype_20_2a_20_3e',['DenseMap&lt; std::pair&lt; llvm::Type *, uint64_t &gt;, llvm::ArrayType * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20std_3a_3apair_3c_20llvm_3a_3atype_20_2a_2c_20unsigned_20_3e_2c_20llvm_3a_3apointertype_20_2a_20_3e',['DenseMap&lt; std::pair&lt; llvm::Type *, unsigned &gt;, llvm::PointerType * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20std_3a_3apair_3c_20llvm_3a_3atype_20_2a_2c_20unsigned_20_3e_2c_20llvm_3a_3avectortype_20_2a_20_3e',['DenseMap&lt; std::pair&lt; llvm::Type *, unsigned &gt;, llvm::VectorType * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20std_3a_3apair_3c_20unsigned_2c_20unsigned_20_3e_2c_20valueforcepair_20_3e',['DenseMap&lt; std::pair&lt; unsigned, unsigned &gt;, ValueForcePair &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20std_3a_3apair_3c_20void_20_2a_2c_20function_20_2a_20_3e_2c_20functionanalysisresultlistt_3a_3aiterator_20_3e',['DenseMap&lt; std::pair&lt; void *, Function * &gt;, FunctionAnalysisResultListT::iterator &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20structtype_20_2a_2c_20bool_2c_20anonstructtypekeyinfo_20_3e',['DenseMap&lt; StructType *, bool, AnonStructTypeKeyInfo &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20type_20_2a_2c_20unsigned_20_3e',['DenseMap&lt; Type *, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20uint32_5ft_2c_20char_2c_20densemapinfo_3c_20uint32_5ft_20_3e_20_3e',['DenseMap&lt; uint32_t, char, DenseMapInfo&lt; uint32_t &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20uint64_5ft_2c_20object_3a_3arelocationref_20_3e',['DenseMap&lt; uint64_t, object::RelocationRef &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20uint64_5ft_2c_20std_3a_3apair_3c_20uint8_5ft_2c_20int64_5ft_20_3e_20_3e',['DenseMap&lt; uint64_t, std::pair&lt; uint8_t, int64_t &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20unsigned_20int_2c_20unsigned_20int_20_3e',['DenseMap&lt; unsigned int, unsigned int &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20unsigned_2c_20allowedset_20_3e',['DenseMap&lt; unsigned, AllowedSet &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20unsigned_2c_20float_20_3e',['DenseMap&lt; unsigned, float &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20unsigned_2c_20int_20_3e',['DenseMap&lt; unsigned, int &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20unsigned_2c_20intptr_5ft_20_3e',['DenseMap&lt; unsigned, intptr_t &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20unsigned_2c_20llvm_3a_3aintegertype_20_2a_20_3e',['DenseMap&lt; unsigned, llvm::IntegerType * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20unsigned_2c_20llvm_3a_3amclabel_20_2a_20_3e',['DenseMap&lt; unsigned, llvm::MCLabel * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20unsigned_2c_20llvm_3a_3amcsymbol_20_2a_20_3e',['DenseMap&lt; unsigned, llvm::MCSymbol * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20unsigned_2c_20llvm_3a_3apointeralignelem_20_3e',['DenseMap&lt; unsigned, llvm::PointerAlignElem &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20unsigned_2c_20llvm_3a_3asmallvector_20_3e',['DenseMap&lt; unsigned, llvm::SmallVector &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20unsigned_2c_20pbqp_3a_3agraph_3a_3anodeid_20_3e',['DenseMap&lt; unsigned, PBQP::Graph::NodeId &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20unsigned_2c_20std_3a_3apair_3c_20unsigned_2c_20unsigned_20_3e_20_3e',['DenseMap&lt; unsigned, std::pair&lt; unsigned, unsigned &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20unsigned_2c_20std_3a_3astring_20_3e',['DenseMap&lt; unsigned, std::string &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20unsigned_2c_20treety_20_2a_20_3e',['DenseMap&lt; unsigned, TreeTy * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20unsigned_2c_20unsigned_20_3e',['DenseMap&lt; unsigned, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20unsignpair_2c_20unsigned_20_3e',['DenseMap&lt; UnsignPair, unsigned &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20value_20_2a_2c_20char_2c_20densemapinfo_3c_20value_20_2a_20_3e_20_3e',['DenseMap&lt; Value *, char, DenseMapInfo&lt; Value * &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20value_20_2a_2c_20valuehandlebase_20_2a_20_3e',['DenseMap&lt; Value *, ValueHandleBase * &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20valueisloadpair_2c_20nonlocalpointerinfo_20_3e',['DenseMap&lt; ValueIsLoadPair, NonLocalPointerInfo &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20valuemapcvh_2c_20const_20llvm_3a_3amipscallentry_20_2a_2c_20densemapinfo_3c_20valuemapcvh_20_3e_20_3e',['DenseMap&lt; ValueMapCVH, const llvm::MipsCallEntry *, DenseMapInfo&lt; ValueMapCVH &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20valuemapcvh_2c_20ssplayoutkind_2c_20densemapinfo_3c_20valuemapcvh_20_3e_20_3e',['DenseMap&lt; ValueMapCVH, SSPLayoutKind, DenseMapInfo&lt; ValueMapCVH &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20valuemapcvh_2c_20valuet_2c_20densemapinfo_3c_20valuemapcvh_20_3e_20_3e',['DenseMap&lt; ValueMapCVH, ValueT, DenseMapInfo&lt; ValueMapCVH &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20valuemapcvh_2c_20void_20_2a_2c_20densemapinfo_3c_20valuemapcvh_20_3e_20_3e',['DenseMap&lt; ValueMapCVH, void *, DenseMapInfo&lt; ValueMapCVH &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20valuepairty_2c_20bool_20_3e',['DenseMap&lt; ValuePairTy, bool &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20valuet_2c_20char_2c_20valueinfot_20_3e',['DenseMap&lt; ValueT, char, ValueInfoT &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20void_20_2a_2c_20intptr_5ft_20_3e',['DenseMap&lt; void *, intptr_t &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20void_20_2a_2c_20polymorphic_5fptr_3c_20analysispassconcept_3c_20function_20_3e_20_3e_20_3e',['DenseMap&lt; void *, polymorphic_ptr&lt; AnalysisPassConcept&lt; Function &gt; &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20void_20_2a_2c_20polymorphic_5fptr_3c_20analysispassconcept_3c_20module_20_3e_20_3e_20_3e',['DenseMap&lt; void *, polymorphic_ptr&lt; AnalysisPassConcept&lt; Module &gt; &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemap_3c_20void_20_2a_2c_20polymorphic_5fptr_3c_20analysisresultconcept_3c_20module_20_3e_20_3e_20_3e',['DenseMap&lt; void *, polymorphic_ptr&lt; AnalysisResultConcept&lt; Module &gt; &gt; &gt;',['../classllvm_1_1DenseMap.html',1,'llvm']]],
  ['densemapapfloatkeyinfo',['DenseMapAPFloatKeyInfo',['../structllvm_1_1DenseMapAPFloatKeyInfo.html',1,'llvm']]],
  ['densemapapintkeyinfo',['DenseMapAPIntKeyInfo',['../structllvm_1_1DenseMapAPIntKeyInfo.html',1,'llvm']]],
  ['densemapbase',['DenseMapBase',['../classllvm_1_1DenseMapBase.html',1,'llvm']]],
  ['densemapbase_3c_20densemap_3c_20keyt_2c_20valuet_2c_20keyinfot_20_3e_2c_20keyt_2c_20valuet_2c_20keyinfot_20_3e',['DenseMapBase&lt; DenseMap&lt; KeyT, ValueT, KeyInfoT &gt;, KeyT, ValueT, KeyInfoT &gt;',['../classllvm_1_1DenseMapBase.html',1,'llvm']]],
  ['densemapbase_3c_20smalldensemap_3c_20instruction_20_2a_2c_20uint64_5ft_2c_204_2c_20densemapinfo_3c_20instruction_20_2a_20_3e_20_3e_2c_20instruction_20_2a_2c_20uint64_5ft_2c_20densemapinfo_3c_20instruction_20_2a_20_3e_20_3e',['DenseMapBase&lt; SmallDenseMap&lt; Instruction *, uint64_t, 4, DenseMapInfo&lt; Instruction * &gt; &gt;, Instruction *, uint64_t, DenseMapInfo&lt; Instruction * &gt; &gt;',['../classllvm_1_1DenseMapBase.html',1,'llvm']]],
  ['densemapbase_3c_20smalldensemap_3c_20instruction_20_2a_2c_20unsigned_2c_204_2c_20densemapinfo_3c_20instruction_20_2a_20_3e_20_3e_2c_20instruction_20_2a_2c_20unsigned_2c_20densemapinfo_3c_20instruction_20_2a_20_3e_20_3e',['DenseMapBase&lt; SmallDenseMap&lt; Instruction *, unsigned, 4, DenseMapInfo&lt; Instruction * &gt; &gt;, Instruction *, unsigned, DenseMapInfo&lt; Instruction * &gt; &gt;',['../classllvm_1_1DenseMapBase.html',1,'llvm']]],
  ['densemapbase_3c_20smalldensemap_3c_20keyt_2c_20valuet_2c_20inlinebuckets_2c_20keyinfot_20_3e_2c_20keyt_2c_20valuet_2c_20keyinfot_20_3e',['DenseMapBase&lt; SmallDenseMap&lt; KeyT, ValueT, InlineBuckets, KeyInfoT &gt;, KeyT, ValueT, KeyInfoT &gt;',['../classllvm_1_1DenseMapBase.html',1,'llvm']]],
  ['densemapbase_3c_20smalldensemap_3c_20llvm_3a_3asdvalue_2c_20llvm_3a_3asdvalue_2c_20inlinebuckets_2c_20densemapinfo_3c_20llvm_3a_3asdvalue_20_3e_20_3e_2c_20llvm_3a_3asdvalue_2c_20llvm_3a_3asdvalue_2c_20densemapinfo_3c_20llvm_3a_3asdvalue_20_3e_20_3e',['DenseMapBase&lt; SmallDenseMap&lt; llvm::SDValue, llvm::SDValue, InlineBuckets, DenseMapInfo&lt; llvm::SDValue &gt; &gt;, llvm::SDValue, llvm::SDValue, DenseMapInfo&lt; llvm::SDValue &gt; &gt;',['../classllvm_1_1DenseMapBase.html',1,'llvm']]],
  ['densemapbase_3c_20smalldensemap_3c_20llvm_3a_3asdvalue_2c_20std_3a_3apair_3c_20llvm_3a_3asdvalue_2c_20llvm_3a_3asdvalue_20_3e_2c_20inlinebuckets_2c_20densemapinfo_3c_20llvm_3a_3asdvalue_20_3e_20_3e_2c_20llvm_3a_3asdvalue_2c_20std_3a_3apair_3c_20llvm_3a_3asdvalue_2c_20llvm_3a_3asdvalue_20_3e_2c_20densemapinfo_3c_20llvm_3a_3asdvalue_20_3e_20_3e',['DenseMapBase&lt; SmallDenseMap&lt; llvm::SDValue, std::pair&lt; llvm::SDValue, llvm::SDValue &gt;, InlineBuckets, DenseMapInfo&lt; llvm::SDValue &gt; &gt;, llvm::SDValue, std::pair&lt; llvm::SDValue, llvm::SDValue &gt;, DenseMapInfo&lt; llvm::SDValue &gt; &gt;',['../classllvm_1_1DenseMapBase.html',1,'llvm']]],
  ['densemapinfo',['DenseMapInfo',['../structllvm_1_1DenseMapInfo.html',1,'llvm']]],
  ['densemapinfo_3c_20aliasanalysis_3a_3alocation_20_3e',['DenseMapInfo&lt; AliasAnalysis::Location &gt;',['../structllvm_1_1DenseMapInfo_3_01AliasAnalysis_1_1Location_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20assertingvh_3c_20t_20_3e_20_3e',['DenseMapInfo&lt; AssertingVH&lt; T &gt; &gt;',['../structllvm_1_1DenseMapInfo_3_01AssertingVH_3_01T_01_4_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20attributeset_20_3e',['DenseMapInfo&lt; AttributeSet &gt;',['../structllvm_1_1DenseMapInfo_3_01AttributeSet_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20callvalue_20_3e',['DenseMapInfo&lt; CallValue &gt;',['../structllvm_1_1DenseMapInfo_3_01CallValue_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20char_20_3e',['DenseMapInfo&lt; char &gt;',['../structllvm_1_1DenseMapInfo_3_01char_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20ciekey_20_3e',['DenseMapInfo&lt; CIEKey &gt;',['../structllvm_1_1DenseMapInfo_3_01CIEKey_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20comparablefunction_20_3e',['DenseMapInfo&lt; ComparableFunction &gt;',['../structllvm_1_1DenseMapInfo_3_01ComparableFunction_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20debugloc_20_3e',['DenseMapInfo&lt; DebugLoc &gt;',['../structllvm_1_1DenseMapInfo_3_01DebugLoc_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20divopinfo_20_3e',['DenseMapInfo&lt; DivOpInfo &gt;',['../structllvm_1_1DenseMapInfo_3_01DivOpInfo_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20expression_20_3e',['DenseMapInfo&lt; Expression &gt;',['../structllvm_1_1DenseMapInfo_3_01Expression_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20immutablelist_3c_20t_20_3e_20_3e',['DenseMapInfo&lt; ImmutableList&lt; T &gt; &gt;',['../structllvm_1_1DenseMapInfo_3_01ImmutableList_3_01T_01_4_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20int_20_3e',['DenseMapInfo&lt; int &gt;',['../structllvm_1_1DenseMapInfo_3_01int_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20long_20_3e',['DenseMapInfo&lt; long &gt;',['../structllvm_1_1DenseMapInfo_3_01long_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20long_20long_20_3e',['DenseMapInfo&lt; long long &gt;',['../structllvm_1_1DenseMapInfo_3_01long_01long_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20loweredphirecord_20_3e',['DenseMapInfo&lt; LoweredPHIRecord &gt;',['../structllvm_1_1DenseMapInfo_3_01LoweredPHIRecord_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20machineinstr_20_2a_20_3e',['DenseMapInfo&lt; MachineInstr * &gt;',['../structllvm_1_1DenseMapInfo.html',1,'llvm']]],
  ['densemapinfo_3c_20pointerintpair_3c_20pointerty_2c_20intbits_2c_20inttype_20_3e_20_3e',['DenseMapInfo&lt; PointerIntPair&lt; PointerTy, IntBits, IntType &gt; &gt;',['../structllvm_1_1DenseMapInfo_3_01PointerIntPair_3_01PointerTy_00_01IntBits_00_01IntType_01_4_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20sdvalue_20_3e',['DenseMapInfo&lt; SDValue &gt;',['../structllvm_1_1DenseMapInfo_3_01SDValue_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20simplevalue_20_3e',['DenseMapInfo&lt; SimpleValue &gt;',['../structllvm_1_1DenseMapInfo_3_01SimpleValue_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20std_3a_3apair_3c_20t_2c_20u_20_3e_20_3e',['DenseMapInfo&lt; std::pair&lt; T, U &gt; &gt;',['../structllvm_1_1DenseMapInfo_3_01std_1_1pair_3_01T_00_01U_01_4_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20t_20_2a_20_3e',['DenseMapInfo&lt; T * &gt;',['../structllvm_1_1DenseMapInfo_3_01T_01_5_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20tablegenstringkey_20_3e',['DenseMapInfo&lt; TableGenStringKey &gt;',['../structllvm_1_1DenseMapInfo_3_01TableGenStringKey_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20unsigned_20_3e',['DenseMapInfo&lt; unsigned &gt;',['../structllvm_1_1DenseMapInfo_3_01unsigned_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20unsigned_20long_20_3e',['DenseMapInfo&lt; unsigned long &gt;',['../structllvm_1_1DenseMapInfo_3_01unsigned_01long_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20unsigned_20long_20long_20_3e',['DenseMapInfo&lt; unsigned long long &gt;',['../structllvm_1_1DenseMapInfo_3_01unsigned_01long_01long_01_4.html',1,'llvm']]],
  ['densemapinfo_3c_20value_20_2a_20_3e',['DenseMapInfo&lt; Value * &gt;',['../structllvm_1_1DenseMapInfo.html',1,'llvm']]],
  ['densemapinfo_3c_20valuemapcallbackvh_3c_20keyt_2c_20valuet_2c_20config_20_3e_20_3e',['DenseMapInfo&lt; ValueMapCallbackVH&lt; KeyT, ValueT, Config &gt; &gt;',['../structllvm_1_1DenseMapInfo_3_01ValueMapCallbackVH_3_01KeyT_00_01ValueT_00_01Config_01_4_01_4.html',1,'llvm']]],
  ['densemapiterator',['DenseMapIterator',['../classllvm_1_1DenseMapIterator.html',1,'llvm']]],
  ['denseset',['DenseSet',['../classllvm_1_1DenseSet.html',1,'llvm']]],
  ['denseset_3c_20const_20llvm_3a_3avalue_20_2a_20_3e',['DenseSet&lt; const llvm::Value * &gt;',['../classllvm_1_1DenseSet.html',1,'llvm']]],
  ['denseset_3c_20llvm_3a_3amachineconstantpoolvalue_20_2a_20_3e',['DenseSet&lt; llvm::MachineConstantPoolValue * &gt;',['../classllvm_1_1DenseSet.html',1,'llvm']]],
  ['denseset_3c_20llvm_3a_3amcsymbol_20const_20_2a_20_3e',['DenseSet&lt; llvm::MCSymbol const * &gt;',['../classllvm_1_1DenseSet.html',1,'llvm']]],
  ['denseset_3c_20llvm_3a_3atype_20_2a_20_3e',['DenseSet&lt; llvm::Type * &gt;',['../classllvm_1_1DenseSet.html',1,'llvm']]],
  ['denseset_3c_20llvm_3a_3avalue_20_2a_20_3e',['DenseSet&lt; llvm::Value * &gt;',['../classllvm_1_1DenseSet.html',1,'llvm']]],
  ['denseset_3c_20uint32_5ft_20_3e',['DenseSet&lt; uint32_t &gt;',['../classllvm_1_1DenseSet.html',1,'llvm']]],
  ['denseset_3c_20value_20_2a_20_3e',['DenseSet&lt; Value * &gt;',['../classllvm_1_1DenseSet.html',1,'llvm']]],
  ['dependence',['Dependence',['../classllvm_1_1Dependence.html',1,'llvm']]],
  ['dependenceanalysis',['DependenceAnalysis',['../classllvm_1_1DependenceAnalysis.html',1,'llvm']]],
  ['derived',['Derived',['../structllvm_1_1yaml_1_1has__FlowTraits_3_01T_00_01true_01_4_1_1Derived.html',1,'llvm::yaml::has_FlowTraits&lt; T, true &gt;']]],
  ['derivedarglist',['DerivedArgList',['../classllvm_1_1opt_1_1DerivedArgList.html',1,'llvm::opt']]],
  ['desc',['desc',['../structllvm_1_1cl_1_1desc.html',1,'llvm::cl']]],
  ['descriptor',['Descriptor',['../structllvm_1_1DWARFDebugArangeSet_1_1Descriptor.html',1,'llvm::DWARFDebugArangeSet']]],
  ['df_5fext_5fiterator',['df_ext_iterator',['../structllvm_1_1df__ext__iterator.html',1,'llvm']]],
  ['df_5fiterator',['df_iterator',['../classllvm_1_1df__iterator.html',1,'llvm']]],
  ['df_5fiterator_3c_20conditional_3c_20isconst_2c_20const_20basicblock_2c_20basicblock_20_3e_3a_3atype_20_2a_20_3e',['df_iterator&lt; conditional&lt; IsConst, const BasicBlock, BasicBlock &gt;::type * &gt;',['../classllvm_1_1df__iterator.html',1,'llvm']]],
  ['df_5fiterator_3c_20inverse_3c_20t_20_3e_2c_20setty_2c_20external_20_3e',['df_iterator&lt; Inverse&lt; T &gt;, SetTy, External &gt;',['../classllvm_1_1df__iterator.html',1,'llvm']]],
  ['df_5fiterator_3c_20t_2c_20setty_2c_20true_20_3e',['df_iterator&lt; T, SetTy, true &gt;',['../classllvm_1_1df__iterator.html',1,'llvm']]],
  ['df_5fiterator_5fstorage',['df_iterator_storage',['../classllvm_1_1df__iterator__storage.html',1,'llvm']]],
  ['df_5fiterator_5fstorage_3c_20llvm_3a_3asmallptrset_3c_20typename_20graphtraits_3c_20conditional_3c_20isconst_2c_20const_20basicblock_2c_20basicblock_20_3e_3a_3atype_20_2a_20_3e_3a_3anodetype_20_2a_2c_208_20_3e_2c_20false_20_3e',['df_iterator_storage&lt; llvm::SmallPtrSet&lt; typename GraphTraits&lt; conditional&lt; IsConst, const BasicBlock, BasicBlock &gt;::type * &gt;::NodeType *, 8 &gt;, false &gt;',['../classllvm_1_1df__iterator__storage.html',1,'llvm']]],
  ['df_5fiterator_5fstorage_3c_20setty_2c_20extstorage_20_3e',['df_iterator_storage&lt; SetTy, ExtStorage &gt;',['../classllvm_1_1df__iterator__storage.html',1,'llvm']]],
  ['df_5fiterator_5fstorage_3c_20settype_2c_20extstorage_20_3e',['df_iterator_storage&lt; SetType, ExtStorage &gt;',['../classllvm_1_1df__iterator__storage.html',1,'llvm']]],
  ['df_5fiterator_5fstorage_3c_20settype_2c_20true_20_3e',['df_iterator_storage&lt; SetType, true &gt;',['../classllvm_1_1df__iterator__storage_3_01SetType_00_01true_01_4.html',1,'llvm']]],
  ['dfapacketizer',['DFAPacketizer',['../classllvm_1_1DFAPacketizer.html',1,'llvm']]],
  ['dfcalculateworkobject',['DFCalculateWorkObject',['../classtrue_1_1DFCalculateWorkObject.html',1,'true']]],
  ['diarray',['DIArray',['../classllvm_1_1DIArray.html',1,'llvm']]],
  ['dibasictype',['DIBasicType',['../classllvm_1_1DIBasicType.html',1,'llvm']]],
  ['dibuilder',['DIBuilder',['../classllvm_1_1DIBuilder.html',1,'llvm']]],
  ['diceref',['DiceRef',['../classllvm_1_1object_1_1DiceRef.html',1,'llvm::object']]],
  ['dicompileunit',['DICompileUnit',['../classllvm_1_1DICompileUnit.html',1,'llvm']]],
  ['dicompositetype',['DICompositeType',['../classllvm_1_1DICompositeType.html',1,'llvm']]],
  ['dicontext',['DIContext',['../classllvm_1_1DIContext.html',1,'llvm']]],
  ['diderivedtype',['DIDerivedType',['../classllvm_1_1DIDerivedType.html',1,'llvm']]],
  ['didescriptor',['DIDescriptor',['../classllvm_1_1DIDescriptor.html',1,'llvm']]],
  ['die',['DIE',['../classllvm_1_1DIE.html',1,'llvm']]],
  ['dieabbrev',['DIEAbbrev',['../classllvm_1_1DIEAbbrev.html',1,'llvm']]],
  ['dieabbrevdata',['DIEAbbrevData',['../classllvm_1_1DIEAbbrevData.html',1,'llvm']]],
  ['dieblock',['DIEBlock',['../classllvm_1_1DIEBlock.html',1,'llvm']]],
  ['diedelta',['DIEDelta',['../classllvm_1_1DIEDelta.html',1,'llvm']]],
  ['dieentry',['DIEEntry',['../classllvm_1_1DIEEntry.html',1,'llvm']]],
  ['dieexpr',['DIEExpr',['../classllvm_1_1DIEExpr.html',1,'llvm']]],
  ['diehash',['DIEHash',['../classllvm_1_1DIEHash.html',1,'llvm']]],
  ['dieinteger',['DIEInteger',['../classllvm_1_1DIEInteger.html',1,'llvm']]],
  ['dielabel',['DIELabel',['../classllvm_1_1DIELabel.html',1,'llvm']]],
  ['dienumerator',['DIEnumerator',['../classllvm_1_1DIEnumerator.html',1,'llvm']]],
  ['diestring',['DIEString',['../classllvm_1_1DIEString.html',1,'llvm']]],
  ['dievalue',['DIEValue',['../classllvm_1_1DIEValue.html',1,'llvm']]],
  ['difflistiterator',['DiffListIterator',['../classllvm_1_1MCRegisterInfo_1_1DiffListIterator.html',1,'llvm::MCRegisterInfo']]],
  ['difile',['DIFile',['../classllvm_1_1DIFile.html',1,'llvm']]],
  ['diglobalvariable',['DIGlobalVariable',['../classllvm_1_1DIGlobalVariable.html',1,'llvm']]],
  ['diimportedentity',['DIImportedEntity',['../classllvm_1_1DIImportedEntity.html',1,'llvm']]],
  ['diinlininginfo',['DIInliningInfo',['../classllvm_1_1DIInliningInfo.html',1,'llvm']]],
  ['dilexicalblock',['DILexicalBlock',['../classllvm_1_1DILexicalBlock.html',1,'llvm']]],
  ['dilexicalblockfile',['DILexicalBlockFile',['../classllvm_1_1DILexicalBlockFile.html',1,'llvm']]],
  ['dilineinfo',['DILineInfo',['../classllvm_1_1DILineInfo.html',1,'llvm']]],
  ['dilineinfospecifier',['DILineInfoSpecifier',['../classllvm_1_1DILineInfoSpecifier.html',1,'llvm']]],
  ['dilocation',['DILocation',['../classllvm_1_1DILocation.html',1,'llvm']]],
  ['dinamespace',['DINameSpace',['../classllvm_1_1DINameSpace.html',1,'llvm']]],
  ['diobjcproperty',['DIObjCProperty',['../classllvm_1_1DIObjCProperty.html',1,'llvm']]],
  ['directory_5fentry',['directory_entry',['../classllvm_1_1sys_1_1fs_1_1directory__entry.html',1,'llvm::sys::fs']]],
  ['directory_5fiterator',['directory_iterator',['../classllvm_1_1sys_1_1fs_1_1directory__iterator.html',1,'llvm::sys::fs']]],
  ['diref',['DIRef',['../classllvm_1_1DIRef.html',1,'llvm']]],
  ['diriterstate',['DirIterState',['../structllvm_1_1sys_1_1fs_1_1detail_1_1DirIterState.html',1,'llvm::sys::fs::detail']]],
  ['discope',['DIScope',['../classllvm_1_1DIScope.html',1,'llvm']]],
  ['disubprogram',['DISubprogram',['../classllvm_1_1DISubprogram.html',1,'llvm']]],
  ['disubrange',['DISubrange',['../classllvm_1_1DISubrange.html',1,'llvm']]],
  ['ditemplatetypeparameter',['DITemplateTypeParameter',['../classllvm_1_1DITemplateTypeParameter.html',1,'llvm']]],
  ['ditemplatevalueparameter',['DITemplateValueParameter',['../classllvm_1_1DITemplateValueParameter.html',1,'llvm']]],
  ['ditype',['DIType',['../classllvm_1_1DIType.html',1,'llvm']]],
  ['divariable',['DIVariable',['../classllvm_1_1DIVariable.html',1,'llvm']]],
  ['document',['Document',['../classllvm_1_1yaml_1_1Document.html',1,'llvm::yaml']]],
  ['document_5fiterator',['document_iterator',['../classllvm_1_1yaml_1_1document__iterator.html',1,'llvm::yaml']]],
  ['documentlisttraits',['DocumentListTraits',['../structllvm_1_1yaml_1_1DocumentListTraits.html',1,'llvm::yaml']]],
  ['dominancefrontier',['DominanceFrontier',['../classllvm_1_1DominanceFrontier.html',1,'llvm']]],
  ['dominancefrontierbase',['DominanceFrontierBase',['../classllvm_1_1DominanceFrontierBase.html',1,'llvm']]],
  ['dominatorbase',['DominatorBase',['../classllvm_1_1DominatorBase.html',1,'llvm']]],
  ['dominatorbase_3c_20llvm_3a_3abasicblock_20_3e',['DominatorBase&lt; llvm::BasicBlock &gt;',['../classllvm_1_1DominatorBase.html',1,'llvm']]],
  ['dominatorbase_3c_20llvm_3a_3amachinebasicblock_20_3e',['DominatorBase&lt; llvm::MachineBasicBlock &gt;',['../classllvm_1_1DominatorBase.html',1,'llvm']]],
  ['dominatortree',['DominatorTree',['../classllvm_1_1DominatorTree.html',1,'llvm']]],
  ['dominatortreebase',['DominatorTreeBase',['../classllvm_1_1DominatorTreeBase.html',1,'llvm']]],
  ['dominatortreebase_3c_20llvm_3a_3abasicblock_20_3e',['DominatorTreeBase&lt; llvm::BasicBlock &gt;',['../classllvm_1_1DominatorTreeBase.html',1,'llvm']]],
  ['dominatortreebase_3c_20llvm_3a_3amachinebasicblock_20_3e',['DominatorTreeBase&lt; llvm::MachineBasicBlock &gt;',['../classllvm_1_1DominatorTreeBase.html',1,'llvm']]],
  ['domtreenodebase',['DomTreeNodeBase',['../classllvm_1_1DomTreeNodeBase.html',1,'llvm']]],
  ['domtreenodebase_3c_20llvm_3a_3abasicblock_20_3e',['DomTreeNodeBase&lt; llvm::BasicBlock &gt;',['../classllvm_1_1DomTreeNodeBase.html',1,'llvm']]],
  ['domtreenodebase_3c_20llvm_3a_3amachinebasicblock_20_3e',['DomTreeNodeBase&lt; llvm::MachineBasicBlock &gt;',['../classllvm_1_1DomTreeNodeBase.html',1,'llvm']]],
  ['dos_5fheader',['dos_header',['../structllvm_1_1object_1_1dos__header.html',1,'llvm::object']]],
  ['dosheader',['DOSHeader',['../structllvm_1_1COFF_1_1DOSHeader.html',1,'llvm::COFF']]],
  ['dotdebuglocentry',['DotDebugLocEntry',['../classllvm_1_1DotDebugLocEntry.html',1,'llvm']]],
  ['dotgraphtraits',['DOTGraphTraits',['../structllvm_1_1DOTGraphTraits.html',1,'llvm']]],
  ['dotgraphtraits_3c_20blockfrequencyinfo_20_2a_20_3e',['DOTGraphTraits&lt; BlockFrequencyInfo * &gt;',['../structllvm_1_1DOTGraphTraits_3_01BlockFrequencyInfo_01_5_01_4.html',1,'llvm']]],
  ['dotgraphtraits_3c_20callgraph_20_2a_20_3e',['DOTGraphTraits&lt; CallGraph * &gt;',['../structllvm_1_1DOTGraphTraits_3_01CallGraph_01_5_01_4.html',1,'llvm']]],
  ['dotgraphtraits_3c_20const_20function_20_2a_20_3e',['DOTGraphTraits&lt; const Function * &gt;',['../structllvm_1_1DOTGraphTraits_3_01const_01Function_01_5_01_4.html',1,'llvm']]],
  ['dotgraphtraits_3c_20const_20machinefunction_20_2a_20_3e',['DOTGraphTraits&lt; const MachineFunction * &gt;',['../structllvm_1_1DOTGraphTraits_3_01const_01MachineFunction_01_5_01_4.html',1,'llvm']]],
  ['dotgraphtraits_3c_20dominatortree_20_2a_20_3e',['DOTGraphTraits&lt; DominatorTree * &gt;',['../structllvm_1_1DOTGraphTraits_3_01DominatorTree_01_5_01_4.html',1,'llvm']]],
  ['dotgraphtraits_3c_20domtreenode_20_2a_20_3e',['DOTGraphTraits&lt; DomTreeNode * &gt;',['../structllvm_1_1DOTGraphTraits_3_01DomTreeNode_01_5_01_4.html',1,'llvm']]],
  ['dotgraphtraits_3c_20graphtype_20_3e',['DOTGraphTraits&lt; GraphType &gt;',['../structllvm_1_1DOTGraphTraits.html',1,'llvm']]],
  ['dotgraphtraits_3c_20postdominatortree_20_2a_20_3e',['DOTGraphTraits&lt; PostDominatorTree * &gt;',['../structllvm_1_1DOTGraphTraits_3_01PostDominatorTree_01_5_01_4.html',1,'llvm']]],
  ['dotgraphtraits_3c_20regioninfo_20_2a_20_3e',['DOTGraphTraits&lt; RegionInfo * &gt;',['../structllvm_1_1DOTGraphTraits_3_01RegionInfo_01_5_01_4.html',1,'llvm']]],
  ['dotgraphtraits_3c_20regionnode_20_2a_20_3e',['DOTGraphTraits&lt; RegionNode * &gt;',['../structllvm_1_1DOTGraphTraits_3_01RegionNode_01_5_01_4.html',1,'llvm']]],
  ['dotgraphtraits_3c_20scheduledag_20_2a_20_3e',['DOTGraphTraits&lt; ScheduleDAG * &gt;',['../structllvm_1_1DOTGraphTraits_3_01ScheduleDAG_01_5_01_4.html',1,'llvm']]],
  ['dotgraphtraits_3c_20scheduledagmi_20_2a_20_3e',['DOTGraphTraits&lt; ScheduleDAGMI * &gt;',['../structllvm_1_1DOTGraphTraits_3_01ScheduleDAGMI_01_5_01_4.html',1,'llvm']]],
  ['dotgraphtraits_3c_20selectiondag_20_2a_20_3e',['DOTGraphTraits&lt; SelectionDAG * &gt;',['../structllvm_1_1DOTGraphTraits_3_01SelectionDAG_01_5_01_4.html',1,'llvm']]],
  ['dotgraphtraitsmoduleprinter',['DOTGraphTraitsModulePrinter',['../classllvm_1_1DOTGraphTraitsModulePrinter.html',1,'llvm']]],
  ['dotgraphtraitsmoduleviewer',['DOTGraphTraitsModuleViewer',['../classllvm_1_1DOTGraphTraitsModuleViewer.html',1,'llvm']]],
  ['dotgraphtraitsprinter',['DOTGraphTraitsPrinter',['../classllvm_1_1DOTGraphTraitsPrinter.html',1,'llvm']]],
  ['dotgraphtraitsviewer',['DOTGraphTraitsViewer',['../classllvm_1_1DOTGraphTraitsViewer.html',1,'llvm']]],
  ['dumpingstate',['DumpingState',['../structllvm_1_1DWARFDebugLine_1_1DumpingState.html',1,'llvm::DWARFDebugLine']]],
  ['dventry',['DVEntry',['../structllvm_1_1Dependence_1_1DVEntry.html',1,'llvm::Dependence']]],
  ['dwarfabbreviationdeclaration',['DWARFAbbreviationDeclaration',['../classllvm_1_1DWARFAbbreviationDeclaration.html',1,'llvm']]],
  ['dwarfabbreviationdeclarationset',['DWARFAbbreviationDeclarationSet',['../classllvm_1_1DWARFAbbreviationDeclarationSet.html',1,'llvm']]],
  ['dwarfacceltable',['DwarfAccelTable',['../classllvm_1_1DwarfAccelTable.html',1,'llvm']]],
  ['dwarfcfiexception',['DwarfCFIException',['../classllvm_1_1DwarfCFIException.html',1,'llvm']]],
  ['dwarfcompileunit',['DWARFCompileUnit',['../classllvm_1_1DWARFCompileUnit.html',1,'llvm']]],
  ['dwarfcontext',['DWARFContext',['../classllvm_1_1DWARFContext.html',1,'llvm']]],
  ['dwarfcontextinmemory',['DWARFContextInMemory',['../classllvm_1_1DWARFContextInMemory.html',1,'llvm']]],
  ['dwarfdebug',['DwarfDebug',['../classllvm_1_1DwarfDebug.html',1,'llvm']]],
  ['dwarfdebugabbrev',['DWARFDebugAbbrev',['../classllvm_1_1DWARFDebugAbbrev.html',1,'llvm']]],
  ['dwarfdebugaranges',['DWARFDebugAranges',['../classllvm_1_1DWARFDebugAranges.html',1,'llvm']]],
  ['dwarfdebugarangeset',['DWARFDebugArangeSet',['../classllvm_1_1DWARFDebugArangeSet.html',1,'llvm']]],
  ['dwarfdebugframe',['DWARFDebugFrame',['../classllvm_1_1DWARFDebugFrame.html',1,'llvm']]],
  ['dwarfdebuginfoentryinlinedchain',['DWARFDebugInfoEntryInlinedChain',['../structllvm_1_1DWARFDebugInfoEntryInlinedChain.html',1,'llvm']]],
  ['dwarfdebuginfoentryminimal',['DWARFDebugInfoEntryMinimal',['../classllvm_1_1DWARFDebugInfoEntryMinimal.html',1,'llvm']]],
  ['dwarfdebugline',['DWARFDebugLine',['../classllvm_1_1DWARFDebugLine.html',1,'llvm']]],
  ['dwarfdebugloc',['DWARFDebugLoc',['../classllvm_1_1DWARFDebugLoc.html',1,'llvm']]],
  ['dwarfdebugrangelist',['DWARFDebugRangeList',['../classllvm_1_1DWARFDebugRangeList.html',1,'llvm']]],
  ['dwarfexception',['DwarfException',['../classllvm_1_1DwarfException.html',1,'llvm']]],
  ['dwarfformvalue',['DWARFFormValue',['../classllvm_1_1DWARFFormValue.html',1,'llvm']]],
  ['dwarfllvmregpair',['DwarfLLVMRegPair',['../structllvm_1_1MCRegisterInfo_1_1DwarfLLVMRegPair.html',1,'llvm::MCRegisterInfo']]],
  ['dwarftypeunit',['DWARFTypeUnit',['../classllvm_1_1DWARFTypeUnit.html',1,'llvm']]],
  ['dwarfunit',['DWARFUnit',['../classllvm_1_1DWARFUnit.html',1,'llvm']]],
  ['dwarfunits',['DwarfUnits',['../classllvm_1_1DwarfUnits.html',1,'llvm']]],
  ['dyld_5finfo_5fcommand',['dyld_info_command',['../structllvm_1_1MachO_1_1dyld__info__command.html',1,'llvm::MachO']]],
  ['dylib',['dylib',['../structllvm_1_1MachO_1_1dylib.html',1,'llvm::MachO']]],
  ['dylib_5fcommand',['dylib_command',['../structllvm_1_1MachO_1_1dylib__command.html',1,'llvm::MachO']]],
  ['dylib_5fmodule',['dylib_module',['../structllvm_1_1MachO_1_1dylib__module.html',1,'llvm::MachO']]],
  ['dylib_5fmodule_5f64',['dylib_module_64',['../structllvm_1_1MachO_1_1dylib__module__64.html',1,'llvm::MachO']]],
  ['dylib_5freference',['dylib_reference',['../structllvm_1_1MachO_1_1dylib__reference.html',1,'llvm::MachO']]],
  ['dylib_5ftable_5fof_5fcontents',['dylib_table_of_contents',['../structllvm_1_1MachO_1_1dylib__table__of__contents.html',1,'llvm::MachO']]],
  ['dylinker_5fcommand',['dylinker_command',['../structllvm_1_1MachO_1_1dylinker__command.html',1,'llvm::MachO']]],
  ['dynamiclibrary',['DynamicLibrary',['../classllvm_1_1sys_1_1DynamicLibrary.html',1,'llvm::sys']]],
  ['dysymtab_5fcommand',['dysymtab_command',['../structllvm_1_1MachO_1_1dysymtab__command.html',1,'llvm::MachO']]]
];
