var searchData=
[
  ['i',['i',['../classllvm_1_1types_1_1i.html',1,'llvm::types']]],
  ['icmapper',['ICMapper',['../structllvm_1_1A64IC_1_1ICMapper.html',1,'llvm::A64IC']]],
  ['icmpinst',['ICmpInst',['../classllvm_1_1ICmpInst.html',1,'llvm']]],
  ['ident_5fcommand',['ident_command',['../structllvm_1_1MachO_1_1ident__command.html',1,'llvm::MachO']]],
  ['identifyingpassptr',['IdentifyingPassPtr',['../classllvm_1_1IdentifyingPassPtr.html',1,'llvm']]],
  ['identity',['identity',['../structllvm_1_1identity.html',1,'llvm']]],
  ['identity_3c_20unsigned_20_3e',['identity&lt; unsigned &gt;',['../structllvm_1_1identity.html',1,'llvm']]],
  ['idf_5fext_5fiterator',['idf_ext_iterator',['../structllvm_1_1idf__ext__iterator.html',1,'llvm']]],
  ['idf_5fiterator',['idf_iterator',['../structllvm_1_1idf__iterator.html',1,'llvm']]],
  ['idf_5fiterator_3c_20t_2c_20setty_2c_20true_20_3e',['idf_iterator&lt; T, SetTy, true &gt;',['../structllvm_1_1idf__iterator.html',1,'llvm']]],
  ['idx2mbbcompare',['Idx2MBBCompare',['../structllvm_1_1Idx2MBBCompare.html',1,'llvm']]],
  ['ieee_5fdouble',['ieee_double',['../classllvm_1_1types_1_1ieee__double.html',1,'llvm::types']]],
  ['ieee_5ffloat',['ieee_float',['../classllvm_1_1types_1_1ieee__float.html',1,'llvm::types']]],
  ['iitdescriptor',['IITDescriptor',['../structllvm_1_1Intrinsic_1_1IITDescriptor.html',1,'llvm::Intrinsic']]],
  ['ilist',['ilist',['../structllvm_1_1ilist.html',1,'llvm']]],
  ['ilist_3c_20indexlistentry_20_3e',['ilist&lt; IndexListEntry &gt;',['../structllvm_1_1ilist.html',1,'llvm']]],
  ['ilist_3c_20llvm_3a_3aaliasset_20_3e',['ilist&lt; llvm::AliasSet &gt;',['../structllvm_1_1ilist.html',1,'llvm']]],
  ['ilist_3c_20llvm_3a_3aivstrideuse_20_3e',['ilist&lt; llvm::IVStrideUse &gt;',['../structllvm_1_1ilist.html',1,'llvm']]],
  ['ilist_3c_20llvm_3a_3asdnode_20_3e',['ilist&lt; llvm::SDNode &gt;',['../structllvm_1_1ilist.html',1,'llvm']]],
  ['ilist_3c_20machinebasicblock_20_3e',['ilist&lt; MachineBasicBlock &gt;',['../structllvm_1_1ilist.html',1,'llvm']]],
  ['ilist_3c_20machineinstr_20_3e',['ilist&lt; MachineInstr &gt;',['../structllvm_1_1ilist.html',1,'llvm']]],
  ['ilist_3c_20namedmdnode_20_3e',['ilist&lt; NamedMDNode &gt;',['../structllvm_1_1ilist.html',1,'llvm']]],
  ['ilist_3c_20sparsebitvectorelement_3c_20elementsize_20_3e_20_3e',['ilist&lt; SparseBitVectorElement&lt; ElementSize &gt; &gt;',['../structllvm_1_1ilist.html',1,'llvm']]],
  ['ilist_3c_20token_20_3e',['ilist&lt; Token &gt;',['../structllvm_1_1ilist.html',1,'llvm']]],
  ['ilist_5fdefault_5ftraits',['ilist_default_traits',['../structllvm_1_1ilist__default__traits.html',1,'llvm']]],
  ['ilist_5fdefault_5ftraits_3c_20indexlistentry_20_3e',['ilist_default_traits&lt; IndexListEntry &gt;',['../structllvm_1_1ilist__default__traits.html',1,'llvm']]],
  ['ilist_5fdefault_5ftraits_3c_20ivstrideuse_20_3e',['ilist_default_traits&lt; IVStrideUse &gt;',['../structllvm_1_1ilist__default__traits.html',1,'llvm']]],
  ['ilist_5fdefault_5ftraits_3c_20machinebasicblock_20_3e',['ilist_default_traits&lt; MachineBasicBlock &gt;',['../structllvm_1_1ilist__default__traits.html',1,'llvm']]],
  ['ilist_5fdefault_5ftraits_3c_20machineinstr_20_3e',['ilist_default_traits&lt; MachineInstr &gt;',['../structllvm_1_1ilist__default__traits.html',1,'llvm']]],
  ['ilist_5fdefault_5ftraits_3c_20namedmdnode_20_3e',['ilist_default_traits&lt; NamedMDNode &gt;',['../structllvm_1_1ilist__default__traits.html',1,'llvm']]],
  ['ilist_5fdefault_5ftraits_3c_20recyclerstruct_20_3e',['ilist_default_traits&lt; RecyclerStruct &gt;',['../structllvm_1_1ilist__default__traits.html',1,'llvm']]],
  ['ilist_5fdefault_5ftraits_3c_20sdnode_20_3e',['ilist_default_traits&lt; SDNode &gt;',['../structllvm_1_1ilist__default__traits.html',1,'llvm']]],
  ['ilist_5fdefault_5ftraits_3c_20sparsebitvectorelement_3c_20elementsize_20_3e_20_3e',['ilist_default_traits&lt; SparseBitVectorElement&lt; ElementSize &gt; &gt;',['../structllvm_1_1ilist__default__traits.html',1,'llvm']]],
  ['ilist_5fdefault_5ftraits_3c_20valuesubclass_20_3e',['ilist_default_traits&lt; ValueSubClass &gt;',['../structllvm_1_1ilist__default__traits.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode',['ilist_half_node',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20aliasset_20_3e',['ilist_half_node&lt; AliasSet &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20argument_20_3e',['ilist_half_node&lt; Argument &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20basicblock_20_3e',['ilist_half_node&lt; BasicBlock &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20function_20_3e',['ilist_half_node&lt; Function &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20globalalias_20_3e',['ilist_half_node&lt; GlobalAlias &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20globalvariable_20_3e',['ilist_half_node&lt; GlobalVariable &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20indexlistentry_20_3e',['ilist_half_node&lt; IndexListEntry &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20instruction_20_3e',['ilist_half_node&lt; Instruction &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20ivstrideuse_20_3e',['ilist_half_node&lt; IVStrideUse &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3aargument_20_3e',['ilist_half_node&lt; llvm::Argument &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3abasicblock_20_3e',['ilist_half_node&lt; llvm::BasicBlock &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3afunction_20_3e',['ilist_half_node&lt; llvm::Function &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3aglobalalias_20_3e',['ilist_half_node&lt; llvm::GlobalAlias &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3aglobalvariable_20_3e',['ilist_half_node&lt; llvm::GlobalVariable &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3aindexlistentry_20_3e',['ilist_half_node&lt; llvm::IndexListEntry &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3ainstruction_20_3e',['ilist_half_node&lt; llvm::Instruction &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3aivstrideuse_20_3e',['ilist_half_node&lt; llvm::IVStrideUse &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3amachinebasicblock_20_3e',['ilist_half_node&lt; llvm::MachineBasicBlock &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3amachineinstr_20_3e',['ilist_half_node&lt; llvm::MachineInstr &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3anamedmdnode_20_3e',['ilist_half_node&lt; llvm::NamedMDNode &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3asdnode_20_3e',['ilist_half_node&lt; llvm::SDNode &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20llvm_3a_3asparsebitvectorelement_20_3e',['ilist_half_node&lt; llvm::SparseBitVectorElement &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20machinebasicblock_20_3e',['ilist_half_node&lt; MachineBasicBlock &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20machineinstr_20_3e',['ilist_half_node&lt; MachineInstr &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20mcfragment_20_3e',['ilist_half_node&lt; MCFragment &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20mcsectiondata_20_3e',['ilist_half_node&lt; MCSectionData &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20mcsymboldata_20_3e',['ilist_half_node&lt; MCSymbolData &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20namedmdnode_20_3e',['ilist_half_node&lt; NamedMDNode &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20sdnode_20_3e',['ilist_half_node&lt; SDNode &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20sparsebitvectorelement_3c_20elementsize_20_3e_20_3e',['ilist_half_node&lt; SparseBitVectorElement&lt; ElementSize &gt; &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fhalf_5fnode_3c_20token_20_3e',['ilist_half_node&lt; Token &gt;',['../classllvm_1_1ilist__half__node.html',1,'llvm']]],
  ['ilist_5fiterator',['ilist_iterator',['../classllvm_1_1ilist__iterator.html',1,'llvm']]],
  ['ilist_5fnextprev_5ftraits',['ilist_nextprev_traits',['../structllvm_1_1ilist__nextprev__traits.html',1,'llvm']]],
  ['ilist_5fnextprev_5ftraits_3c_20indexlistentry_20_3e',['ilist_nextprev_traits&lt; IndexListEntry &gt;',['../structllvm_1_1ilist__nextprev__traits.html',1,'llvm']]],
  ['ilist_5fnextprev_5ftraits_3c_20ivstrideuse_20_3e',['ilist_nextprev_traits&lt; IVStrideUse &gt;',['../structllvm_1_1ilist__nextprev__traits.html',1,'llvm']]],
  ['ilist_5fnextprev_5ftraits_3c_20machinebasicblock_20_3e',['ilist_nextprev_traits&lt; MachineBasicBlock &gt;',['../structllvm_1_1ilist__nextprev__traits.html',1,'llvm']]],
  ['ilist_5fnextprev_5ftraits_3c_20machineinstr_20_3e',['ilist_nextprev_traits&lt; MachineInstr &gt;',['../structllvm_1_1ilist__nextprev__traits.html',1,'llvm']]],
  ['ilist_5fnextprev_5ftraits_3c_20namedmdnode_20_3e',['ilist_nextprev_traits&lt; NamedMDNode &gt;',['../structllvm_1_1ilist__nextprev__traits.html',1,'llvm']]],
  ['ilist_5fnextprev_5ftraits_3c_20recyclerstruct_20_3e',['ilist_nextprev_traits&lt; RecyclerStruct &gt;',['../structllvm_1_1ilist__nextprev__traits.html',1,'llvm']]],
  ['ilist_5fnextprev_5ftraits_3c_20sdnode_20_3e',['ilist_nextprev_traits&lt; SDNode &gt;',['../structllvm_1_1ilist__nextprev__traits.html',1,'llvm']]],
  ['ilist_5fnextprev_5ftraits_3c_20sparsebitvectorelement_3c_20elementsize_20_3e_20_3e',['ilist_nextprev_traits&lt; SparseBitVectorElement&lt; ElementSize &gt; &gt;',['../structllvm_1_1ilist__nextprev__traits.html',1,'llvm']]],
  ['ilist_5fnextprev_5ftraits_3c_20valuesubclass_20_3e',['ilist_nextprev_traits&lt; ValueSubClass &gt;',['../structllvm_1_1ilist__nextprev__traits.html',1,'llvm']]],
  ['ilist_5fnode',['ilist_node',['../classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20aliasset_20_3e',['ilist_node&lt; AliasSet &gt;',['../classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20argument_20_3e',['ilist_node&lt; Argument &gt;',['../classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20basicblock_20_3e',['ilist_node&lt; BasicBlock &gt;',['../classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20function_20_3e',['ilist_node&lt; Function &gt;',['../classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20globalalias_20_3e',['ilist_node&lt; GlobalAlias &gt;',['../classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20globalvariable_20_3e',['ilist_node&lt; GlobalVariable &gt;',['../classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20indexlistentry_20_3e',['ilist_node&lt; IndexListEntry &gt;',['../classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20instruction_20_3e',['ilist_node&lt; Instruction &gt;',['../classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20ivstrideuse_20_3e',['ilist_node&lt; IVStrideUse &gt;',['../classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20llvm_3a_3afunction_20_3e',['ilist_node&lt; llvm::Function &gt;',['../classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20llvm_3a_3aglobalalias_20_3e',['ilist_node&lt; llvm::GlobalAlias &gt;',['../classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20llvm_3a_3aglobalvariable_20_3e',['ilist_node&lt; llvm::GlobalVariable &gt;',['../classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20llvm_3a_3aivstrideuse_20_3e',['ilist_node&lt; llvm::IVStrideUse &gt;',['../classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20llvm_3a_3anamedmdnode_20_3e',['ilist_node&lt; llvm::NamedMDNode &gt;',['../classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20machinebasicblock_20_3e',['ilist_node&lt; MachineBasicBlock &gt;',['../classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20machineinstr_20_3e',['ilist_node&lt; MachineInstr &gt;',['../classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20mcfragment_20_3e',['ilist_node&lt; MCFragment &gt;',['../classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20mcsectiondata_20_3e',['ilist_node&lt; MCSectionData &gt;',['../classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20mcsymboldata_20_3e',['ilist_node&lt; MCSymbolData &gt;',['../classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20namedmdnode_20_3e',['ilist_node&lt; NamedMDNode &gt;',['../classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20sdnode_20_3e',['ilist_node&lt; SDNode &gt;',['../classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20sparsebitvectorelement_3c_20elementsize_20_3e_20_3e',['ilist_node&lt; SparseBitVectorElement&lt; ElementSize &gt; &gt;',['../classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_3c_20token_20_3e',['ilist_node&lt; Token &gt;',['../classllvm_1_1ilist__node.html',1,'llvm']]],
  ['ilist_5fnode_5ftraits',['ilist_node_traits',['../structllvm_1_1ilist__node__traits.html',1,'llvm']]],
  ['ilist_5fnode_5ftraits_3c_20indexlistentry_20_3e',['ilist_node_traits&lt; IndexListEntry &gt;',['../structllvm_1_1ilist__node__traits.html',1,'llvm']]],
  ['ilist_5fnode_5ftraits_3c_20ivstrideuse_20_3e',['ilist_node_traits&lt; IVStrideUse &gt;',['../structllvm_1_1ilist__node__traits.html',1,'llvm']]],
  ['ilist_5fnode_5ftraits_3c_20machinebasicblock_20_3e',['ilist_node_traits&lt; MachineBasicBlock &gt;',['../structllvm_1_1ilist__node__traits.html',1,'llvm']]],
  ['ilist_5fnode_5ftraits_3c_20machineinstr_20_3e',['ilist_node_traits&lt; MachineInstr &gt;',['../structllvm_1_1ilist__node__traits.html',1,'llvm']]],
  ['ilist_5fnode_5ftraits_3c_20namedmdnode_20_3e',['ilist_node_traits&lt; NamedMDNode &gt;',['../structllvm_1_1ilist__node__traits.html',1,'llvm']]],
  ['ilist_5fnode_5ftraits_3c_20recyclerstruct_20_3e',['ilist_node_traits&lt; RecyclerStruct &gt;',['../structllvm_1_1ilist__node__traits.html',1,'llvm']]],
  ['ilist_5fnode_5ftraits_3c_20sdnode_20_3e',['ilist_node_traits&lt; SDNode &gt;',['../structllvm_1_1ilist__node__traits.html',1,'llvm']]],
  ['ilist_5fnode_5ftraits_3c_20sparsebitvectorelement_3c_20elementsize_20_3e_20_3e',['ilist_node_traits&lt; SparseBitVectorElement&lt; ElementSize &gt; &gt;',['../structllvm_1_1ilist__node__traits.html',1,'llvm']]],
  ['ilist_5fnode_5ftraits_3c_20token_20_3e',['ilist_node_traits&lt; Token &gt;',['../structllvm_1_1ilist__node__traits_3_01Token_01_4.html',1,'llvm']]],
  ['ilist_5fnode_5ftraits_3c_20valuesubclass_20_3e',['ilist_node_traits&lt; ValueSubClass &gt;',['../structllvm_1_1ilist__node__traits.html',1,'llvm']]],
  ['ilist_5fsentinel_5ftraits',['ilist_sentinel_traits',['../structllvm_1_1ilist__sentinel__traits.html',1,'llvm']]],
  ['ilist_5fsentinel_5ftraits_3c_20indexlistentry_20_3e',['ilist_sentinel_traits&lt; IndexListEntry &gt;',['../structllvm_1_1ilist__sentinel__traits.html',1,'llvm']]],
  ['ilist_5fsentinel_5ftraits_3c_20ivstrideuse_20_3e',['ilist_sentinel_traits&lt; IVStrideUse &gt;',['../structllvm_1_1ilist__sentinel__traits.html',1,'llvm']]],
  ['ilist_5fsentinel_5ftraits_3c_20machinebasicblock_20_3e',['ilist_sentinel_traits&lt; MachineBasicBlock &gt;',['../structllvm_1_1ilist__sentinel__traits.html',1,'llvm']]],
  ['ilist_5fsentinel_5ftraits_3c_20machineinstr_20_3e',['ilist_sentinel_traits&lt; MachineInstr &gt;',['../structllvm_1_1ilist__sentinel__traits.html',1,'llvm']]],
  ['ilist_5fsentinel_5ftraits_3c_20namedmdnode_20_3e',['ilist_sentinel_traits&lt; NamedMDNode &gt;',['../structllvm_1_1ilist__sentinel__traits.html',1,'llvm']]],
  ['ilist_5fsentinel_5ftraits_3c_20recyclerstruct_20_3e',['ilist_sentinel_traits&lt; RecyclerStruct &gt;',['../structllvm_1_1ilist__sentinel__traits.html',1,'llvm']]],
  ['ilist_5fsentinel_5ftraits_3c_20sdnode_20_3e',['ilist_sentinel_traits&lt; SDNode &gt;',['../structllvm_1_1ilist__sentinel__traits.html',1,'llvm']]],
  ['ilist_5fsentinel_5ftraits_3c_20sparsebitvectorelement_3c_20elementsize_20_3e_20_3e',['ilist_sentinel_traits&lt; SparseBitVectorElement&lt; ElementSize &gt; &gt;',['../structllvm_1_1ilist__sentinel__traits.html',1,'llvm']]],
  ['ilist_5fsentinel_5ftraits_3c_20token_20_3e',['ilist_sentinel_traits&lt; Token &gt;',['../structllvm_1_1ilist__sentinel__traits_3_01Token_01_4.html',1,'llvm']]],
  ['ilist_5fsentinel_5ftraits_3c_20valuesubclass_20_3e',['ilist_sentinel_traits&lt; ValueSubClass &gt;',['../structllvm_1_1ilist__sentinel__traits.html',1,'llvm']]],
  ['ilist_5ftraits',['ilist_traits',['../structllvm_1_1ilist__traits.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20argument_20_3e',['ilist_traits&lt; Argument &gt;',['../structllvm_1_1ilist__traits_3_01Argument_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20basicblock_20_3e',['ilist_traits&lt; BasicBlock &gt;',['../structllvm_1_1ilist__traits_3_01BasicBlock_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20const_20ty_20_3e',['ilist_traits&lt; const Ty &gt;',['../structllvm_1_1ilist__traits_3_01const_01Ty_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20function_20_3e',['ilist_traits&lt; Function &gt;',['../structllvm_1_1ilist__traits_3_01Function_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20globalalias_20_3e',['ilist_traits&lt; GlobalAlias &gt;',['../structllvm_1_1ilist__traits_3_01GlobalAlias_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20globalvariable_20_3e',['ilist_traits&lt; GlobalVariable &gt;',['../structllvm_1_1ilist__traits_3_01GlobalVariable_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20indexlistentry_20_3e',['ilist_traits&lt; IndexListEntry &gt;',['../structllvm_1_1ilist__traits_3_01IndexListEntry_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20instruction_20_3e',['ilist_traits&lt; Instruction &gt;',['../structllvm_1_1ilist__traits_3_01Instruction_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20ivstrideuse_20_3e',['ilist_traits&lt; IVStrideUse &gt;',['../structllvm_1_1ilist__traits_3_01IVStrideUse_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20machinebasicblock_20_3e',['ilist_traits&lt; MachineBasicBlock &gt;',['../structllvm_1_1ilist__traits_3_01MachineBasicBlock_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20machineinstr_20_3e',['ilist_traits&lt; MachineInstr &gt;',['../structllvm_1_1ilist__traits_3_01MachineInstr_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20namedmdnode_20_3e',['ilist_traits&lt; NamedMDNode &gt;',['../structllvm_1_1ilist__traits_3_01NamedMDNode_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20recyclerstruct_20_3e',['ilist_traits&lt; RecyclerStruct &gt;',['../structllvm_1_1ilist__traits_3_01RecyclerStruct_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20sdnode_20_3e',['ilist_traits&lt; SDNode &gt;',['../structllvm_1_1ilist__traits_3_01SDNode_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20sparsebitvectorelement_3c_20elementsize_20_3e_20_3e',['ilist_traits&lt; SparseBitVectorElement&lt; ElementSize &gt; &gt;',['../structllvm_1_1ilist__traits_3_01SparseBitVectorElement_3_01ElementSize_01_4_01_4.html',1,'llvm']]],
  ['ilist_5ftraits_3c_20ty_20_3e',['ilist_traits&lt; Ty &gt;',['../structllvm_1_1ilist__traits.html',1,'llvm']]],
  ['ilpvalue',['ILPValue',['../structllvm_1_1ILPValue.html',1,'llvm']]],
  ['immutablecallsite',['ImmutableCallSite',['../classllvm_1_1ImmutableCallSite.html',1,'llvm']]],
  ['immutableintervalmap',['ImmutableIntervalMap',['../classllvm_1_1ImmutableIntervalMap.html',1,'llvm']]],
  ['immutablelist',['ImmutableList',['../classllvm_1_1ImmutableList.html',1,'llvm']]],
  ['immutablelistfactory',['ImmutableListFactory',['../classllvm_1_1ImmutableListFactory.html',1,'llvm']]],
  ['immutablelistimpl',['ImmutableListImpl',['../classllvm_1_1ImmutableListImpl.html',1,'llvm']]],
  ['immutablemap',['ImmutableMap',['../classllvm_1_1ImmutableMap.html',1,'llvm']]],
  ['immutablemap_3c_20interval_2c_20valt_2c_20imutintervalinfo_3c_20valt_20_3e_20_3e',['ImmutableMap&lt; Interval, ValT, ImutIntervalInfo&lt; ValT &gt; &gt;',['../classllvm_1_1ImmutableMap.html',1,'llvm']]],
  ['immutablemapref',['ImmutableMapRef',['../classllvm_1_1ImmutableMapRef.html',1,'llvm']]],
  ['immutablepass',['ImmutablePass',['../classllvm_1_1ImmutablePass.html',1,'llvm']]],
  ['immutableset',['ImmutableSet',['../classllvm_1_1ImmutableSet.html',1,'llvm']]],
  ['immutablesetref',['ImmutableSetRef',['../classllvm_1_1ImmutableSetRef.html',1,'llvm']]],
  ['import_5fdirectory_5ftable_5fentry',['import_directory_table_entry',['../structllvm_1_1object_1_1import__directory__table__entry.html',1,'llvm::object']]],
  ['import_5flookup_5ftable_5fentry32',['import_lookup_table_entry32',['../structllvm_1_1object_1_1import__lookup__table__entry32.html',1,'llvm::object']]],
  ['importdirectoryentryref',['ImportDirectoryEntryRef',['../classllvm_1_1object_1_1ImportDirectoryEntryRef.html',1,'llvm::object']]],
  ['importdirectorytableentry',['ImportDirectoryTableEntry',['../structllvm_1_1COFF_1_1ImportDirectoryTableEntry.html',1,'llvm::COFF']]],
  ['importheader',['ImportHeader',['../structllvm_1_1COFF_1_1ImportHeader.html',1,'llvm::COFF']]],
  ['importlookuptableentry32',['ImportLookupTableEntry32',['../structllvm_1_1COFF_1_1ImportLookupTableEntry32.html',1,'llvm::COFF']]],
  ['imutavlfactory',['ImutAVLFactory',['../classllvm_1_1ImutAVLFactory.html',1,'llvm']]],
  ['imutavltree',['ImutAVLTree',['../classllvm_1_1ImutAVLTree.html',1,'llvm']]],
  ['imutavltreegenericiterator',['ImutAVLTreeGenericIterator',['../classllvm_1_1ImutAVLTreeGenericIterator.html',1,'llvm']]],
  ['imutavltreeinorderiterator',['ImutAVLTreeInOrderIterator',['../classllvm_1_1ImutAVLTreeInOrderIterator.html',1,'llvm']]],
  ['imutcontainerinfo',['ImutContainerInfo',['../structllvm_1_1ImutContainerInfo.html',1,'llvm']]],
  ['imutcontainerinfo_3c_20t_20_2a_20_3e',['ImutContainerInfo&lt; T * &gt;',['../structllvm_1_1ImutContainerInfo_3_01T_01_5_01_4.html',1,'llvm']]],
  ['imutintervalavlfactory',['ImutIntervalAVLFactory',['../classllvm_1_1ImutIntervalAVLFactory.html',1,'llvm']]],
  ['imutintervalavlfactory_3c_20llvm_3a_3aimutintervalinfo_3c_20valt_20_3e_20_3e',['ImutIntervalAVLFactory&lt; llvm::ImutIntervalInfo&lt; ValT &gt; &gt;',['../classllvm_1_1ImutIntervalAVLFactory.html',1,'llvm']]],
  ['imutintervalinfo',['ImutIntervalInfo',['../structllvm_1_1ImutIntervalInfo.html',1,'llvm']]],
  ['imutkeyvalueinfo',['ImutKeyValueInfo',['../structllvm_1_1ImutKeyValueInfo.html',1,'llvm']]],
  ['imutprofileinfo',['ImutProfileInfo',['../structllvm_1_1ImutProfileInfo.html',1,'llvm']]],
  ['imutprofileinfo_3c_20bool_20_3e',['ImutProfileInfo&lt; bool &gt;',['../structllvm_1_1ImutProfileInfo_3_01bool_01_4.html',1,'llvm']]],
  ['imutprofileinfo_3c_20t_20_2a_20_3e',['ImutProfileInfo&lt; T * &gt;',['../structllvm_1_1ImutProfileInfo_3_01T_01_5_01_4.html',1,'llvm']]],
  ['imutprofileinteger',['ImutProfileInteger',['../structllvm_1_1ImutProfileInteger.html',1,'llvm']]],
  ['includefile',['IncludeFile',['../structllvm_1_1IncludeFile.html',1,'llvm']]],
  ['indexedmap',['IndexedMap',['../classllvm_1_1IndexedMap.html',1,'llvm']]],
  ['indexedmap_3c_20int_2c_20llvm_3a_3avirtreg2indexfunctor_20_3e',['IndexedMap&lt; int, llvm::VirtReg2IndexFunctor &gt;',['../classllvm_1_1IndexedMap.html',1,'llvm']]],
  ['indexedmap_3c_20liveoutpair_2c_20mbb2numberfunctor_20_3e',['IndexedMap&lt; LiveOutPair, MBB2NumberFunctor &gt;',['../classllvm_1_1IndexedMap.html',1,'llvm']]],
  ['indexedmap_3c_20llvm_3a_3afunctionloweringinfo_3a_3aliveoutinfo_2c_20llvm_3a_3avirtreg2indexfunctor_20_3e',['IndexedMap&lt; llvm::FunctionLoweringInfo::LiveOutInfo, llvm::VirtReg2IndexFunctor &gt;',['../classllvm_1_1IndexedMap.html',1,'llvm']]],
  ['indexedmap_3c_20llvm_3a_3aliveinterval_20_2a_2c_20llvm_3a_3avirtreg2indexfunctor_20_3e',['IndexedMap&lt; llvm::LiveInterval *, llvm::VirtReg2IndexFunctor &gt;',['../classllvm_1_1IndexedMap.html',1,'llvm']]],
  ['indexedmap_3c_20llvm_3a_3alivevariables_3a_3avarinfo_2c_20llvm_3a_3avirtreg2indexfunctor_20_3e',['IndexedMap&lt; llvm::LiveVariables::VarInfo, llvm::VirtReg2IndexFunctor &gt;',['../classllvm_1_1IndexedMap.html',1,'llvm']]],
  ['indexedmap_3c_20std_3a_3apair_3c_20const_20llvm_3a_3atargetregisterclass_20_2a_2c_20llvm_3a_3amachineoperand_20_2a_20_3e_2c_20llvm_3a_3avirtreg2indexfunctor_20_3e',['IndexedMap&lt; std::pair&lt; const llvm::TargetRegisterClass *, llvm::MachineOperand * &gt;, llvm::VirtReg2IndexFunctor &gt;',['../classllvm_1_1IndexedMap.html',1,'llvm']]],
  ['indexedmap_3c_20std_3a_3apair_3c_20unsigned_2c_20unsigned_20_3e_2c_20llvm_3a_3avirtreg2indexfunctor_20_3e',['IndexedMap&lt; std::pair&lt; unsigned, unsigned &gt;, llvm::VirtReg2IndexFunctor &gt;',['../classllvm_1_1IndexedMap.html',1,'llvm']]],
  ['indexedmap_3c_20unsigned_20_3e',['IndexedMap&lt; unsigned &gt;',['../classllvm_1_1IndexedMap.html',1,'llvm']]],
  ['indexedmap_3c_20unsigned_2c_20llvm_3a_3avirtreg2indexfunctor_20_3e',['IndexedMap&lt; unsigned, llvm::VirtReg2IndexFunctor &gt;',['../classllvm_1_1IndexedMap.html',1,'llvm']]],
  ['indexlistentry',['IndexListEntry',['../classllvm_1_1IndexListEntry.html',1,'llvm']]],
  ['indirectbrinst',['IndirectBrInst',['../classllvm_1_1IndirectBrInst.html',1,'llvm']]],
  ['indirectsymboldata',['IndirectSymbolData',['../structllvm_1_1IndirectSymbolData.html',1,'llvm']]],
  ['info',['Info',['../structllvm_1_1opt_1_1OptTable_1_1Info.html',1,'llvm::opt::OptTable']]],
  ['inforec',['InfoRec',['../structllvm_1_1DominatorTreeBase_1_1InfoRec.html',1,'llvm::DominatorTreeBase']]],
  ['init',['Init',['../classllvm_1_1Init.html',1,'llvm']]],
  ['initializer',['initializer',['../structllvm_1_1cl_1_1initializer.html',1,'llvm::cl']]],
  ['inlineasm',['InlineAsm',['../classllvm_1_1InlineAsm.html',1,'llvm']]],
  ['inlineasmidentifierinfo',['InlineAsmIdentifierInfo',['../structllvm_1_1MCAsmParserSemaCallback_1_1InlineAsmIdentifierInfo.html',1,'llvm::MCAsmParserSemaCallback']]],
  ['inlineasmkeytype',['InlineAsmKeyType',['../structllvm_1_1InlineAsmKeyType.html',1,'llvm']]],
  ['inlinecost',['InlineCost',['../classllvm_1_1InlineCost.html',1,'llvm']]],
  ['inlinecostanalysis',['InlineCostAnalysis',['../classllvm_1_1InlineCostAnalysis.html',1,'llvm']]],
  ['inlinefunctioninfo',['InlineFunctionInfo',['../classllvm_1_1InlineFunctionInfo.html',1,'llvm']]],
  ['inliner',['Inliner',['../structllvm_1_1Inliner.html',1,'llvm']]],
  ['input',['Input',['../classllvm_1_1yaml_1_1Input.html',1,'llvm::yaml']]],
  ['inputarg',['InputArg',['../structllvm_1_1ISD_1_1InputArg.html',1,'llvm::ISD']]],
  ['inputarglist',['InputArgList',['../classllvm_1_1opt_1_1InputArgList.html',1,'llvm::opt']]],
  ['insertelementconstantexpr',['InsertElementConstantExpr',['../classllvm_1_1InsertElementConstantExpr.html',1,'llvm']]],
  ['insertelementinst',['InsertElementInst',['../classllvm_1_1InsertElementInst.html',1,'llvm']]],
  ['insertpoint',['InsertPoint',['../classllvm_1_1IRBuilderBase_1_1InsertPoint.html',1,'llvm::IRBuilderBase']]],
  ['insertpointguard',['InsertPointGuard',['../classllvm_1_1IRBuilderBase_1_1InsertPointGuard.html',1,'llvm::IRBuilderBase']]],
  ['insertvalueconstantexpr',['InsertValueConstantExpr',['../classllvm_1_1InsertValueConstantExpr.html',1,'llvm']]],
  ['insertvalueinst',['InsertValueInst',['../classllvm_1_1InsertValueInst.html',1,'llvm']]],
  ['inst',['Inst',['../structllvm_1_1MCModuleYAML_1_1Inst.html',1,'llvm::MCModuleYAML']]],
  ['inst',['Inst',['../structllvm_1_1MipsAnalyzeImmediate_1_1Inst.html',1,'llvm::MipsAnalyzeImmediate']]],
  ['instcombineirinserter',['InstCombineIRInserter',['../classllvm_1_1InstCombineIRInserter.html',1,'llvm']]],
  ['instcombiner',['InstCombiner',['../classllvm_1_1InstCombiner.html',1,'llvm']]],
  ['instcombineworklist',['InstCombineWorklist',['../classllvm_1_1InstCombineWorklist.html',1,'llvm']]],
  ['institerator',['InstIterator',['../classllvm_1_1InstIterator.html',1,'llvm']]],
  ['institerator_3c_20const_20iplist_3c_20basicblock_20_3e_2c_20function_3a_3aconst_5fiterator_2c_20basicblock_3a_3aconst_5fiterator_2c_20const_20instruction_20_3e',['InstIterator&lt; const iplist&lt; BasicBlock &gt;, Function::const_iterator, BasicBlock::const_iterator, const Instruction &gt;',['../classllvm_1_1InstIterator.html',1,'llvm']]],
  ['instrcycles',['InstrCycles',['../structllvm_1_1MachineTraceMetrics_1_1InstrCycles.html',1,'llvm::MachineTraceMetrics']]],
  ['instremitter',['InstrEmitter',['../classllvm_1_1InstrEmitter.html',1,'llvm']]],
  ['instritinerary',['InstrItinerary',['../structllvm_1_1InstrItinerary.html',1,'llvm']]],
  ['instritinerarydata',['InstrItineraryData',['../classllvm_1_1InstrItineraryData.html',1,'llvm']]],
  ['instrstage',['InstrStage',['../structllvm_1_1InstrStage.html',1,'llvm']]],
  ['instruction',['Instruction',['../structllvm_1_1FrameEntry_1_1Instruction.html',1,'llvm::FrameEntry']]],
  ['instruction',['Instruction',['../classllvm_1_1Instruction.html',1,'llvm']]],
  ['instructionspecifier',['InstructionSpecifier',['../structInstructionSpecifier.html',1,'']]],
  ['instvisitor',['InstVisitor',['../classllvm_1_1InstVisitor.html',1,'llvm']]],
  ['instvisitor_3c_20derivedt_20_3e',['InstVisitor&lt; DerivedT &gt;',['../classllvm_1_1InstVisitor.html',1,'llvm']]],
  ['instvisitor_3c_20instcombiner_2c_20instruction_20_2a_20_3e',['InstVisitor&lt; InstCombiner, Instruction * &gt;',['../classllvm_1_1InstVisitor.html',1,'llvm']]],
  ['instvisitor_3c_20interpreter_20_3e',['InstVisitor&lt; Interpreter &gt;',['../classllvm_1_1InstVisitor.html',1,'llvm']]],
  ['instvisitor_3c_20objectsizeoffsetevaluator_2c_20sizeoffsetevaltype_20_3e',['InstVisitor&lt; ObjectSizeOffsetEvaluator, SizeOffsetEvalType &gt;',['../classllvm_1_1InstVisitor.html',1,'llvm']]],
  ['instvisitor_3c_20objectsizeoffsetvisitor_2c_20sizeoffsettype_20_3e',['InstVisitor&lt; ObjectSizeOffsetVisitor, SizeOffsetType &gt;',['../classllvm_1_1InstVisitor.html',1,'llvm']]],
  ['instvisitor_3c_20slicebuilder_20_3e',['InstVisitor&lt; SliceBuilder &gt;',['../classllvm_1_1InstVisitor.html',1,'llvm']]],
  ['integertype',['IntegerType',['../classllvm_1_1IntegerType.html',1,'llvm']]],
  ['integral_5fconstant',['integral_constant',['../structllvm_1_1integral__constant.html',1,'llvm']]],
  ['integral_5fconstant_3c_20bool_2c_20has_5fsequencemethodtraits_3c_20t_20_3e_3a_3avalue_20_3e',['integral_constant&lt; bool, has_SequenceMethodTraits&lt; T &gt;::value &gt;',['../structllvm_1_1integral__constant.html',1,'llvm']]],
  ['integral_5fconstant_3c_20bool_2c_21has_5fscalarenumerationtraits_3c_20t_20_3e_3a_3avalue_20_26_26_21has_5fscalarbitsettraits_3c_20t_20_3e_3a_3avalue_20_26_26_21has_5fscalartraits_3c_20t_20_3e_3a_3avalue_20_26_26_21has_5fmappingtraits_3c_20t_20_3e_3a_3avalue_20_26_26_21has_5fsequencetraits_3c_20t_20_3e_3a_3avalue_20_26_26_21has_5fdocumentlisttraits_3c_20t_20_3e_3a_3avalue_20_3e',['integral_constant&lt; bool,!has_ScalarEnumerationTraits&lt; T &gt;::value &amp;&amp;!has_ScalarBitSetTraits&lt; T &gt;::value &amp;&amp;!has_ScalarTraits&lt; T &gt;::value &amp;&amp;!has_MappingTraits&lt; T &gt;::value &amp;&amp;!has_SequenceTraits&lt; T &gt;::value &amp;&amp;!has_DocumentListTraits&lt; T &gt;::value &gt;',['../structllvm_1_1integral__constant.html',1,'llvm']]],
  ['integral_5fconstant_3c_20bool_2c_28_28is_5fintegral_5for_5fenum_3c_20t_20_3e_3a_3avalue_7c_7cis_5fpointer_3c_20t_20_3e_3a_3avalue_29_26_2664_25sizeof_28t_29_3d_3d0_29_3e',['integral_constant&lt; bool,((is_integral_or_enum&lt; T &gt;::value||is_pointer&lt; T &gt;::value)&amp;&amp;64%sizeof(T)==0)&gt;',['../structllvm_1_1integral__constant.html',1,'llvm']]],
  ['integral_5fconstant_3c_20bool_2c_28is_5fhashable_5fdata_3c_20t_20_3e_3a_3avalue_20_26_26is_5fhashable_5fdata_3c_20u_20_3e_3a_3avalue_20_26_26_28sizeof_28t_29_2bsizeof_28u_29_29_3d_3dsizeof_28std_3a_3apair_3c_20t_2c_20u_20_3e_29_29_3e',['integral_constant&lt; bool,(is_hashable_data&lt; T &gt;::value &amp;&amp;is_hashable_data&lt; U &gt;::value &amp;&amp;(sizeof(T)+sizeof(U))==sizeof(std::pair&lt; T, U &gt;))&gt;',['../structllvm_1_1integral__constant.html',1,'llvm']]],
  ['inteljiteventswrapper',['IntelJITEventsWrapper',['../classllvm_1_1IntelJITEventsWrapper.html',1,'llvm']]],
  ['inteqclasses',['IntEqClasses',['../classllvm_1_1IntEqClasses.html',1,'llvm']]],
  ['interferencecache',['InterferenceCache',['../classllvm_1_1InterferenceCache.html',1,'llvm']]],
  ['internalinstruction',['InternalInstruction',['../structInternalInstruction.html',1,'']]],
  ['interpreter',['Interpreter',['../classllvm_1_1Interpreter.html',1,'llvm']]],
  ['interval',['Interval',['../classllvm_1_1Interval.html',1,'llvm']]],
  ['intervaliterator',['IntervalIterator',['../classllvm_1_1IntervalIterator.html',1,'llvm']]],
  ['intervalmap',['IntervalMap',['../classllvm_1_1IntervalMap.html',1,'llvm']]],
  ['intervalmap_3c_20slotindex_2c_20liveinterval_20_2a_20_3e',['IntervalMap&lt; SlotIndex, LiveInterval * &gt;',['../classllvm_1_1IntervalMap.html',1,'llvm']]],
  ['intervalmap_3c_20slotindex_2c_20unsigned_20_3e',['IntervalMap&lt; SlotIndex, unsigned &gt;',['../classllvm_1_1IntervalMap.html',1,'llvm']]],
  ['intervalmaphalfopeninfo',['IntervalMapHalfOpenInfo',['../structllvm_1_1IntervalMapHalfOpenInfo.html',1,'llvm']]],
  ['intervalmaphalfopeninfo_3c_20slotindex_20_3e',['IntervalMapHalfOpenInfo&lt; SlotIndex &gt;',['../structllvm_1_1IntervalMapHalfOpenInfo.html',1,'llvm']]],
  ['intervalmapinfo',['IntervalMapInfo',['../structllvm_1_1IntervalMapInfo.html',1,'llvm']]],
  ['intervalmapinfo_3c_20slotindex_20_3e',['IntervalMapInfo&lt; SlotIndex &gt;',['../structllvm_1_1IntervalMapInfo_3_01SlotIndex_01_4.html',1,'llvm']]],
  ['intervalmapoverlaps',['IntervalMapOverlaps',['../classllvm_1_1IntervalMapOverlaps.html',1,'llvm']]],
  ['intervalpartition',['IntervalPartition',['../classllvm_1_1IntervalPartition.html',1,'llvm']]],
  ['intervalpressure',['IntervalPressure',['../structllvm_1_1IntervalPressure.html',1,'llvm']]],
  ['intervalsorter',['IntervalSorter',['../structfalse_1_1IntervalSorter.html',1,'false']]],
  ['intinit',['IntInit',['../classllvm_1_1IntInit.html',1,'llvm']]],
  ['intpair',['IntPair',['../structllvm_1_1GenericValue_1_1IntPair.html',1,'llvm::GenericValue']]],
  ['intrecty',['IntRecTy',['../classllvm_1_1IntRecTy.html',1,'llvm']]],
  ['intrinsicid_5fmatch',['IntrinsicID_match',['../structllvm_1_1PatternMatch_1_1IntrinsicID__match.html',1,'llvm::PatternMatch']]],
  ['intrinsicinfo',['IntrinsicInfo',['../structllvm_1_1TargetLoweringBase_1_1IntrinsicInfo.html',1,'llvm::TargetLoweringBase']]],
  ['intrinsicinst',['IntrinsicInst',['../classllvm_1_1IntrinsicInst.html',1,'llvm']]],
  ['intrinsiclowering',['IntrinsicLowering',['../classllvm_1_1IntrinsicLowering.html',1,'llvm']]],
  ['intrusiverefcntptr',['IntrusiveRefCntPtr',['../classllvm_1_1IntrusiveRefCntPtr.html',1,'llvm']]],
  ['intrusiverefcntptr_3c_20detail_3a_3adiriterstate_20_3e',['IntrusiveRefCntPtr&lt; detail::DirIterState &gt;',['../classllvm_1_1IntrusiveRefCntPtr.html',1,'llvm']]],
  ['intrusiverefcntptr_3c_20detail_3a_3arecdiriterstate_20_3e',['IntrusiveRefCntPtr&lt; detail::RecDirIterState &gt;',['../classllvm_1_1IntrusiveRefCntPtr.html',1,'llvm']]],
  ['intrusiverefcntptrinfo',['IntrusiveRefCntPtrInfo',['../structllvm_1_1IntrusiveRefCntPtrInfo.html',1,'llvm']]],
  ['inttoptrinst',['IntToPtrInst',['../classllvm_1_1IntToPtrInst.html',1,'llvm']]],
  ['inverse',['Inverse',['../structllvm_1_1Inverse.html',1,'llvm']]],
  ['invokeinst',['InvokeInst',['../classllvm_1_1InvokeInst.html',1,'llvm']]],
  ['io',['IO',['../classllvm_1_1yaml_1_1IO.html',1,'llvm::yaml']]],
  ['iplist',['iplist',['../classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20argument_20_3e',['iplist&lt; Argument &gt;',['../classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20basicblock_20_3e',['iplist&lt; BasicBlock &gt;',['../classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20function_20_3e',['iplist&lt; Function &gt;',['../classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20globalalias_20_3e',['iplist&lt; GlobalAlias &gt;',['../classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20globalvariable_20_3e',['iplist&lt; GlobalVariable &gt;',['../classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20indexlistentry_20_3e',['iplist&lt; IndexListEntry &gt;',['../classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20instruction_20_3e',['iplist&lt; Instruction &gt;',['../classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20llvm_3a_3aaliasset_20_3e',['iplist&lt; llvm::AliasSet &gt;',['../classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20llvm_3a_3aivstrideuse_20_3e',['iplist&lt; llvm::IVStrideUse &gt;',['../classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20llvm_3a_3amcsectiondata_20_3e',['iplist&lt; llvm::MCSectionData &gt;',['../classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20llvm_3a_3amcsymboldata_20_3e',['iplist&lt; llvm::MCSymbolData &gt;',['../classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20llvm_3a_3arecyclerstruct_20_3e',['iplist&lt; llvm::RecyclerStruct &gt;',['../classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20llvm_3a_3asdnode_20_3e',['iplist&lt; llvm::SDNode &gt;',['../classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20machinebasicblock_20_3e',['iplist&lt; MachineBasicBlock &gt;',['../classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20machineinstr_20_3e',['iplist&lt; MachineInstr &gt;',['../classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20mcfragment_20_3e',['iplist&lt; MCFragment &gt;',['../classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20namedmdnode_20_3e',['iplist&lt; NamedMDNode &gt;',['../classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20nodety_20_3e',['iplist&lt; NodeTy &gt;',['../classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20sparsebitvectorelement_3c_20elementsize_20_3e_20_3e',['iplist&lt; SparseBitVectorElement&lt; ElementSize &gt; &gt;',['../classllvm_1_1iplist.html',1,'llvm']]],
  ['iplist_3c_20token_20_3e',['iplist&lt; Token &gt;',['../classllvm_1_1iplist.html',1,'llvm']]],
  ['ipo_5fext_5fiterator',['ipo_ext_iterator',['../structllvm_1_1ipo__ext__iterator.html',1,'llvm']]],
  ['ipo_5fiterator',['ipo_iterator',['../structllvm_1_1ipo__iterator.html',1,'llvm']]],
  ['ipo_5fiterator_3c_20t_2c_20settype_2c_20true_20_3e',['ipo_iterator&lt; T, SetType, true &gt;',['../structllvm_1_1ipo__iterator.html',1,'llvm']]],
  ['irbuilder',['IRBuilder',['../classllvm_1_1IRBuilder.html',1,'llvm']]],
  ['irbuilder_3c_20true_2c_20targetfolder_20_3e',['IRBuilder&lt; true, TargetFolder &gt;',['../classllvm_1_1IRBuilder.html',1,'llvm']]],
  ['irbuilderbase',['IRBuilderBase',['../classllvm_1_1IRBuilderBase.html',1,'llvm']]],
  ['irbuilderdefaultinserter',['IRBuilderDefaultInserter',['../classllvm_1_1IRBuilderDefaultInserter.html',1,'llvm']]],
  ['irbuilderdefaultinserter_3c_20true_20_3e',['IRBuilderDefaultInserter&lt; true &gt;',['../classllvm_1_1IRBuilderDefaultInserter.html',1,'llvm']]],
  ['is_5fall_5fones',['is_all_ones',['../structllvm_1_1PatternMatch_1_1is__all__ones.html',1,'llvm::PatternMatch']]],
  ['is_5fbase_5fof',['is_base_of',['../structllvm_1_1is__base__of.html',1,'llvm']]],
  ['is_5fclass',['is_class',['../structllvm_1_1is__class.html',1,'llvm']]],
  ['is_5ferror_5fcode_5fenum',['is_error_code_enum',['../structllvm_1_1is__error__code__enum.html',1,'llvm']]],
  ['is_5ferror_5fcode_5fenum_3c_20object_3a_3aobject_5ferror_20_3e',['is_error_code_enum&lt; object::object_error &gt;',['../structllvm_1_1is__error__code__enum_3_01object_1_1object__error_01_4.html',1,'llvm']]],
  ['is_5ferror_5fcode_5fenum_3c_20object_3a_3aobject_5ferror_3a_3aimpl_20_3e',['is_error_code_enum&lt; object::object_error::Impl &gt;',['../structllvm_1_1is__error__code__enum_3_01object_1_1object__error_1_1Impl_01_4.html',1,'llvm']]],
  ['is_5ferror_5fcode_5fenum_3c_20windows_5ferror_20_3e',['is_error_code_enum&lt; windows_error &gt;',['../structllvm_1_1is__error__code__enum_3_01windows__error_01_4.html',1,'llvm']]],
  ['is_5ferror_5fcode_5fenum_3c_20windows_5ferror_3a_3a_5f_20_3e',['is_error_code_enum&lt; windows_error::_ &gt;',['../structllvm_1_1is__error__code__enum_3_01windows__error_1_1___01_4.html',1,'llvm']]],
  ['is_5ferror_5fcondition_5fenum',['is_error_condition_enum',['../structllvm_1_1is__error__condition__enum.html',1,'llvm']]],
  ['is_5ferror_5fcondition_5fenum_3c_20errc_20_3e',['is_error_condition_enum&lt; errc &gt;',['../structllvm_1_1is__error__condition__enum_3_01errc_01_4.html',1,'llvm']]],
  ['is_5ferror_5fcondition_5fenum_3c_20errc_3a_3a_5f_20_3e',['is_error_condition_enum&lt; errc::_ &gt;',['../structllvm_1_1is__error__condition__enum_3_01errc_1_1___01_4.html',1,'llvm']]],
  ['is_5fhashable_5fdata',['is_hashable_data',['../structllvm_1_1hashing_1_1detail_1_1is__hashable__data.html',1,'llvm::hashing::detail']]],
  ['is_5fhashable_5fdata_3c_20std_3a_3apair_3c_20t_2c_20u_20_3e_20_3e',['is_hashable_data&lt; std::pair&lt; T, U &gt; &gt;',['../structllvm_1_1hashing_1_1detail_1_1is__hashable__data_3_01std_1_1pair_3_01T_00_01U_01_4_01_4.html',1,'llvm::hashing::detail']]],
  ['is_5fintegral',['is_integral',['../structllvm_1_1is__integral.html',1,'llvm']]],
  ['is_5fintegral_5fimpl',['is_integral_impl',['../structllvm_1_1is__integral__impl.html',1,'llvm']]],
  ['is_5fintegral_5fimpl_3c_20bool_20_3e',['is_integral_impl&lt; bool &gt;',['../structllvm_1_1is__integral__impl_3_01bool_01_4.html',1,'llvm']]],
  ['is_5fintegral_5fimpl_3c_20char_20_3e',['is_integral_impl&lt; char &gt;',['../structllvm_1_1is__integral__impl_3_01char_01_4.html',1,'llvm']]],
  ['is_5fintegral_5fimpl_3c_20int_20_3e',['is_integral_impl&lt; int &gt;',['../structllvm_1_1is__integral__impl_3_01int_01_4.html',1,'llvm']]],
  ['is_5fintegral_5fimpl_3c_20long_20_3e',['is_integral_impl&lt; long &gt;',['../structllvm_1_1is__integral__impl_3_01long_01_4.html',1,'llvm']]],
  ['is_5fintegral_5fimpl_3c_20long_20long_20_3e',['is_integral_impl&lt; long long &gt;',['../structllvm_1_1is__integral__impl_3_01long_01long_01_4.html',1,'llvm']]],
  ['is_5fintegral_5fimpl_3c_20short_20_3e',['is_integral_impl&lt; short &gt;',['../structllvm_1_1is__integral__impl_3_01short_01_4.html',1,'llvm']]],
  ['is_5fintegral_5fimpl_3c_20signed_20char_20_3e',['is_integral_impl&lt; signed char &gt;',['../structllvm_1_1is__integral__impl_3_01signed_01char_01_4.html',1,'llvm']]],
  ['is_5fintegral_5fimpl_3c_20unsigned_20char_20_3e',['is_integral_impl&lt; unsigned char &gt;',['../structllvm_1_1is__integral__impl_3_01unsigned_01char_01_4.html',1,'llvm']]],
  ['is_5fintegral_5fimpl_3c_20unsigned_20int_20_3e',['is_integral_impl&lt; unsigned int &gt;',['../structllvm_1_1is__integral__impl_3_01unsigned_01int_01_4.html',1,'llvm']]],
  ['is_5fintegral_5fimpl_3c_20unsigned_20long_20_3e',['is_integral_impl&lt; unsigned long &gt;',['../structllvm_1_1is__integral__impl_3_01unsigned_01long_01_4.html',1,'llvm']]],
  ['is_5fintegral_5fimpl_3c_20unsigned_20long_20long_20_3e',['is_integral_impl&lt; unsigned long long &gt;',['../structllvm_1_1is__integral__impl_3_01unsigned_01long_01long_01_4.html',1,'llvm']]],
  ['is_5fintegral_5fimpl_3c_20unsigned_20short_20_3e',['is_integral_impl&lt; unsigned short &gt;',['../structllvm_1_1is__integral__impl_3_01unsigned_01short_01_4.html',1,'llvm']]],
  ['is_5fintegral_5fimpl_3c_20wchar_5ft_20_3e',['is_integral_impl&lt; wchar_t &gt;',['../structllvm_1_1is__integral__impl_3_01wchar__t_01_4.html',1,'llvm']]],
  ['is_5fintegral_5for_5fenum',['is_integral_or_enum',['../classllvm_1_1is__integral__or__enum.html',1,'llvm']]],
  ['is_5fone',['is_one',['../structllvm_1_1PatternMatch_1_1is__one.html',1,'llvm::PatternMatch']]],
  ['is_5fpointer',['is_pointer',['../structllvm_1_1is__pointer.html',1,'llvm']]],
  ['is_5fpointer_3c_20t_20_2a_20_3e',['is_pointer&lt; T * &gt;',['../structllvm_1_1is__pointer_3_01T_01_5_01_4.html',1,'llvm']]],
  ['is_5fpointer_3c_20t_20_2aconst_20_20_3e',['is_pointer&lt; T *const  &gt;',['../structllvm_1_1is__pointer_3_01T_01_5const_01_01_4.html',1,'llvm']]],
  ['is_5fpointer_3c_20t_20_2aconst_20volatile_20_3e',['is_pointer&lt; T *const volatile &gt;',['../structllvm_1_1is__pointer_3_01T_01_5const_01volatile_01_4.html',1,'llvm']]],
  ['is_5fpointer_3c_20t_20_2avolatile_20_3e',['is_pointer&lt; T *volatile &gt;',['../structllvm_1_1is__pointer_3_01T_01_5volatile_01_4.html',1,'llvm']]],
  ['is_5fpower2',['is_power2',['../structllvm_1_1PatternMatch_1_1is__power2.html',1,'llvm::PatternMatch']]],
  ['is_5freference',['is_reference',['../structllvm_1_1is__reference.html',1,'llvm']]],
  ['is_5freference_3c_20t_20_26_20_3e',['is_reference&lt; T &amp; &gt;',['../structllvm_1_1is__reference_3_01T_01_6_01_4.html',1,'llvm']]],
  ['is_5fsame',['is_same',['../structllvm_1_1is__same.html',1,'llvm']]],
  ['is_5fsame_3c_20t_2c_20t_20_3e',['is_same&lt; T, T &gt;',['../structllvm_1_1is__same_3_01T_00_01T_01_4.html',1,'llvm']]],
  ['is_5fsign_5fbit',['is_sign_bit',['../structllvm_1_1PatternMatch_1_1is__sign__bit.html',1,'llvm::PatternMatch']]],
  ['is_5fsimple_5ftype',['is_simple_type',['../structllvm_1_1is__simple__type.html',1,'llvm']]],
  ['isa_5fimpl',['isa_impl',['../structllvm_1_1isa__impl.html',1,'llvm']]],
  ['isa_5fimpl_3c_20argument_2c_20value_20_3e',['isa_impl&lt; Argument, Value &gt;',['../structllvm_1_1isa__impl_3_01Argument_00_01Value_01_4.html',1,'llvm']]],
  ['isa_5fimpl_3c_20basicblock_2c_20value_20_3e',['isa_impl&lt; BasicBlock, Value &gt;',['../structllvm_1_1isa__impl_3_01BasicBlock_00_01Value_01_4.html',1,'llvm']]],
  ['isa_5fimpl_3c_20constant_2c_20value_20_3e',['isa_impl&lt; Constant, Value &gt;',['../structllvm_1_1isa__impl_3_01Constant_00_01Value_01_4.html',1,'llvm']]],
  ['isa_5fimpl_3c_20function_2c_20value_20_3e',['isa_impl&lt; Function, Value &gt;',['../structllvm_1_1isa__impl_3_01Function_00_01Value_01_4.html',1,'llvm']]],
  ['isa_5fimpl_3c_20globalalias_2c_20value_20_3e',['isa_impl&lt; GlobalAlias, Value &gt;',['../structllvm_1_1isa__impl_3_01GlobalAlias_00_01Value_01_4.html',1,'llvm']]],
  ['isa_5fimpl_3c_20globalvalue_2c_20value_20_3e',['isa_impl&lt; GlobalValue, Value &gt;',['../structllvm_1_1isa__impl_3_01GlobalValue_00_01Value_01_4.html',1,'llvm']]],
  ['isa_5fimpl_3c_20globalvariable_2c_20value_20_3e',['isa_impl&lt; GlobalVariable, Value &gt;',['../structllvm_1_1isa__impl_3_01GlobalVariable_00_01Value_01_4.html',1,'llvm']]],
  ['isa_5fimpl_3c_20inlineasm_2c_20value_20_3e',['isa_impl&lt; InlineAsm, Value &gt;',['../structllvm_1_1isa__impl_3_01InlineAsm_00_01Value_01_4.html',1,'llvm']]],
  ['isa_5fimpl_3c_20instruction_2c_20value_20_3e',['isa_impl&lt; Instruction, Value &gt;',['../structllvm_1_1isa__impl_3_01Instruction_00_01Value_01_4.html',1,'llvm']]],
  ['isa_5fimpl_3c_20mdnode_2c_20value_20_3e',['isa_impl&lt; MDNode, Value &gt;',['../structllvm_1_1isa__impl_3_01MDNode_00_01Value_01_4.html',1,'llvm']]],
  ['isa_5fimpl_3c_20pointertype_2c_20type_20_3e',['isa_impl&lt; PointerType, Type &gt;',['../structllvm_1_1isa__impl_3_01PointerType_00_01Type_01_4.html',1,'llvm']]],
  ['isa_5fimpl_3c_20to_2c_20from_2c_20typename_20enable_5fif_3c_20llvm_3a_3ais_5fbase_5fof_3c_20to_2c_20from_20_3e_20_3e_3a_3atype_20_3e',['isa_impl&lt; To, From, typename enable_if&lt; llvm::is_base_of&lt; To, From &gt; &gt;::type &gt;',['../structllvm_1_1isa__impl_3_01To_00_01From_00_01typename_01enable__if_3_01llvm_1_1is__base__of_3_06e21f0991a390749f4bfacbee861f807.html',1,'llvm']]],
  ['isa_5fimpl_5fcl',['isa_impl_cl',['../structllvm_1_1isa__impl__cl.html',1,'llvm']]],
  ['isa_5fimpl_5fcl_3c_20to_2c_20const_20from_20_2a_20_3e',['isa_impl_cl&lt; To, const From * &gt;',['../structllvm_1_1isa__impl__cl_3_01To_00_01const_01From_01_5_01_4.html',1,'llvm']]],
  ['isa_5fimpl_5fcl_3c_20to_2c_20const_20from_20_2aconst_20_20_3e',['isa_impl_cl&lt; To, const From *const  &gt;',['../structllvm_1_1isa__impl__cl_3_01To_00_01const_01From_01_5const_01_01_4.html',1,'llvm']]],
  ['isa_5fimpl_5fcl_3c_20to_2c_20const_20from_20_3e',['isa_impl_cl&lt; To, const From &gt;',['../structllvm_1_1isa__impl__cl_3_01To_00_01const_01From_01_4.html',1,'llvm']]],
  ['isa_5fimpl_5fcl_3c_20to_2c_20from_20_2a_20_3e',['isa_impl_cl&lt; To, From * &gt;',['../structllvm_1_1isa__impl__cl_3_01To_00_01From_01_5_01_4.html',1,'llvm']]],
  ['isa_5fimpl_5fcl_3c_20to_2c_20from_20_2aconst_20_20_3e',['isa_impl_cl&lt; To, From *const  &gt;',['../structllvm_1_1isa__impl__cl_3_01To_00_01From_01_5const_01_01_4.html',1,'llvm']]],
  ['isa_5fimpl_5fwrap',['isa_impl_wrap',['../structllvm_1_1isa__impl__wrap.html',1,'llvm']]],
  ['isa_5fimpl_5fwrap_3c_20to_2c_20fromty_2c_20fromty_20_3e',['isa_impl_wrap&lt; To, FromTy, FromTy &gt;',['../structllvm_1_1isa__impl__wrap_3_01To_00_01FromTy_00_01FromTy_01_4.html',1,'llvm']]],
  ['isbmapper',['ISBMapper',['../structllvm_1_1A64ISB_1_1ISBMapper.html',1,'llvm::A64ISB']]],
  ['ispodlike',['isPodLike',['../structllvm_1_1isPodLike.html',1,'llvm']]],
  ['ispodlike_3c_20arrayref_3c_20t_20_3e_20_3e',['isPodLike&lt; ArrayRef&lt; T &gt; &gt;',['../structllvm_1_1isPodLike_3_01ArrayRef_3_01T_01_4_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20assertingvh_3c_20t_20_3e_20_3e',['isPodLike&lt; AssertingVH&lt; T &gt; &gt;',['../structllvm_1_1isPodLike_3_01AssertingVH_3_01T_01_4_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20bitcodeabbrevop_20_3e',['isPodLike&lt; BitCodeAbbrevOp &gt;',['../structllvm_1_1isPodLike_3_01BitCodeAbbrevOp_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20identifyingpassptr_20_3e',['isPodLike&lt; IdentifyingPassPtr &gt;',['../structllvm_1_1isPodLike_3_01IdentifyingPassPtr_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20immutablelist_3c_20t_20_3e_20_3e',['isPodLike&lt; ImmutableList&lt; T &gt; &gt;',['../structllvm_1_1isPodLike_3_01ImmutableList_3_01T_01_4_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20mcoperand_20_3e',['isPodLike&lt; MCOperand &gt;',['../structllvm_1_1isPodLike_3_01MCOperand_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20optional_3c_20t_20_3e_20_3e',['isPodLike&lt; Optional&lt; T &gt; &gt;',['../structllvm_1_1isPodLike_3_01Optional_3_01T_01_4_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20pointerintpair_3c_20pointerty_2c_20intbits_2c_20inttype_20_3e_20_3e',['isPodLike&lt; PointerIntPair&lt; PointerTy, IntBits, IntType &gt; &gt;',['../structllvm_1_1isPodLike_3_01PointerIntPair_3_01PointerTy_00_01IntBits_00_01IntType_01_4_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20pressurechange_20_3e',['isPodLike&lt; PressureChange &gt;',['../structllvm_1_1isPodLike_3_01PressureChange_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20sdep_20_3e',['isPodLike&lt; SDep &gt;',['../structllvm_1_1isPodLike_3_01SDep_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20sdvalue_20_3e',['isPodLike&lt; SDValue &gt;',['../structllvm_1_1isPodLike_3_01SDValue_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20slice_20_3e',['isPodLike&lt; Slice &gt;',['../structllvm_1_1isPodLike_3_01Slice_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20slotindex_20_3e',['isPodLike&lt; SlotIndex &gt;',['../structllvm_1_1isPodLike_3_01SlotIndex_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20std_3a_3apair_3c_20t_2c_20u_20_3e_20_3e',['isPodLike&lt; std::pair&lt; T, U &gt; &gt;',['../structllvm_1_1isPodLike_3_01std_1_1pair_3_01T_00_01U_01_4_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20stringref_20_3e',['isPodLike&lt; StringRef &gt;',['../structllvm_1_1isPodLike_3_01StringRef_01_4.html',1,'llvm']]],
  ['ispodlike_3c_20succiterator_3c_20t_2c_20u_20_3e_20_3e',['isPodLike&lt; SuccIterator&lt; T, U &gt; &gt;',['../structllvm_1_1isPodLike_3_01SuccIterator_3_01T_00_01U_01_4_01_4.html',1,'llvm']]],
  ['iterator',['Iterator',['../classllvm_1_1DenseSet_1_1Iterator.html',1,'llvm::DenseSet']]],
  ['iterator',['iterator',['../classllvm_1_1Registry_1_1iterator.html',1,'llvm::Registry']]],
  ['iterator',['iterator',['../classllvm_1_1ImmutableSetRef_1_1iterator.html',1,'llvm::ImmutableSetRef']]],
  ['iterator',['iterator',['../classllvm_1_1ImmutableList_1_1iterator.html',1,'llvm::ImmutableList']]],
  ['iterator',['iterator',['../classllvm_1_1ImmutableMapRef_1_1iterator.html',1,'llvm::ImmutableMapRef']]],
  ['iterator',['iterator',['../classllvm_1_1ImmutableMap_1_1iterator.html',1,'llvm::ImmutableMap']]],
  ['iterator',['iterator',['../classllvm_1_1TargetRegistry_1_1iterator.html',1,'llvm::TargetRegistry']]],
  ['iterator',['iterator',['../classllvm_1_1ImmutableSet_1_1iterator.html',1,'llvm::ImmutableSet']]],
  ['iterator',['iterator',['../classllvm_1_1IntervalMap_1_1iterator.html',1,'llvm::IntervalMap']]],
  ['iterator',['iterator',['../classllvm_1_1AliasSet_1_1iterator.html',1,'llvm::AliasSet']]],
  ['iterator_5fbase',['iterator_base',['../classllvm_1_1SparseMultiSet_1_1iterator__base.html',1,'llvm::SparseMultiSet']]],
  ['ivstrideuse',['IVStrideUse',['../classllvm_1_1IVStrideUse.html',1,'llvm']]],
  ['ivusers',['IVUsers',['../classllvm_1_1IVUsers.html',1,'llvm']]],
  ['ivvisitor',['IVVisitor',['../classllvm_1_1IVVisitor.html',1,'llvm']]]
];
