var searchData=
[
  ['factory',['Factory',['../classllvm_1_1ImmutableIntervalMap_1_1Factory.html',1,'llvm::ImmutableIntervalMap']]],
  ['factory',['Factory',['../classllvm_1_1ImmutableMap_1_1Factory.html',1,'llvm::ImmutableMap']]],
  ['factory',['Factory',['../classllvm_1_1ImmutableSet_1_1Factory.html',1,'llvm::ImmutableSet']]],
  ['fallback',['Fallback',['../structllvm_1_1yaml_1_1has__FlowTraits_3_01T_00_01true_01_4_1_1Fallback.html',1,'llvm::yaml::has_FlowTraits&lt; T, true &gt;']]],
  ['fastfoldingsetnode',['FastFoldingSetNode',['../classllvm_1_1FastFoldingSetNode.html',1,'llvm']]],
  ['fastisel',['FastISel',['../classllvm_1_1FastISel.html',1,'llvm']]],
  ['fastmathflagguard',['FastMathFlagGuard',['../classllvm_1_1IRBuilderBase_1_1FastMathFlagGuard.html',1,'llvm::IRBuilderBase']]],
  ['fastmathflags',['FastMathFlags',['../classllvm_1_1FastMathFlags.html',1,'llvm']]],
  ['fat_5farch',['fat_arch',['../structllvm_1_1MachO_1_1fat__arch.html',1,'llvm::MachO']]],
  ['fat_5fheader',['fat_header',['../structllvm_1_1MachO_1_1fat__header.html',1,'llvm::MachO']]],
  ['fcmpinst',['FCmpInst',['../classllvm_1_1FCmpInst.html',1,'llvm']]],
  ['fenceinst',['FenceInst',['../classllvm_1_1FenceInst.html',1,'llvm']]],
  ['fieldinit',['FieldInit',['../classllvm_1_1FieldInit.html',1,'llvm']]],
  ['file_5fmagic',['file_magic',['../structllvm_1_1sys_1_1fs_1_1file__magic.html',1,'llvm::sys::fs']]],
  ['file_5fstatus',['file_status',['../classllvm_1_1sys_1_1fs_1_1file__status.html',1,'llvm::sys::fs']]],
  ['file_5ftype',['file_type',['../structllvm_1_1sys_1_1fs_1_1file__type.html',1,'llvm::sys::fs']]],
  ['filehandletraits',['FileHandleTraits',['../structFileHandleTraits.html',1,'']]],
  ['fileheader',['FileHeader',['../structllvm_1_1ELFYAML_1_1FileHeader.html',1,'llvm::ELFYAML']]],
  ['fileinfo',['FileInfo',['../classllvm_1_1FileInfo.html',1,'llvm']]],
  ['filenamecache',['FilenameCache',['../classllvm_1_1jitprofiling_1_1FilenameCache.html',1,'llvm::jitprofiling']]],
  ['filenameentry',['FileNameEntry',['../structllvm_1_1DWARFDebugLine_1_1FileNameEntry.html',1,'llvm::DWARFDebugLine']]],
  ['fileoutputbuffer',['FileOutputBuffer',['../classllvm_1_1FileOutputBuffer.html',1,'llvm']]],
  ['fileremover',['FileRemover',['../classllvm_1_1FileRemover.html',1,'llvm']]],
  ['filteredpassnameparser',['FilteredPassNameParser',['../classllvm_1_1FilteredPassNameParser.html',1,'llvm']]],
  ['findhandletraits',['FindHandleTraits',['../structFindHandleTraits.html',1,'']]],
  ['findusedtypes',['FindUsedTypes',['../classllvm_1_1FindUsedTypes.html',1,'llvm']]],
  ['fixedblockinfo',['FixedBlockInfo',['../structllvm_1_1MachineTraceMetrics_1_1FixedBlockInfo.html',1,'llvm::MachineTraceMetrics']]],
  ['fixednumoperandtraits',['FixedNumOperandTraits',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20atomiccmpxchginst_2c_203_20_3e',['FixedNumOperandTraits&lt; AtomicCmpXchgInst, 3 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20atomicrmwinst_2c_202_20_3e',['FixedNumOperandTraits&lt; AtomicRMWInst, 2 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20binaryconstantexpr_2c_202_20_3e',['FixedNumOperandTraits&lt; BinaryConstantExpr, 2 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20binaryoperator_2c_202_20_3e',['FixedNumOperandTraits&lt; BinaryOperator, 2 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20blockaddress_2c_202_20_3e',['FixedNumOperandTraits&lt; BlockAddress, 2 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20cmpinst_2c_202_20_3e',['FixedNumOperandTraits&lt; CmpInst, 2 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20compareconstantexpr_2c_202_20_3e',['FixedNumOperandTraits&lt; CompareConstantExpr, 2 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20constantplaceholder_2c_201_20_3e',['FixedNumOperandTraits&lt; ConstantPlaceHolder, 1 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20extractelementconstantexpr_2c_202_20_3e',['FixedNumOperandTraits&lt; ExtractElementConstantExpr, 2 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20extractelementinst_2c_202_20_3e',['FixedNumOperandTraits&lt; ExtractElementInst, 2 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20extractvalueconstantexpr_2c_201_20_3e',['FixedNumOperandTraits&lt; ExtractValueConstantExpr, 1 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20globalalias_2c_201_20_3e',['FixedNumOperandTraits&lt; GlobalAlias, 1 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20globalvariable_2c_201_20_3e',['FixedNumOperandTraits&lt; GlobalVariable, 1 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20insertelementconstantexpr_2c_203_20_3e',['FixedNumOperandTraits&lt; InsertElementConstantExpr, 3 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20insertelementinst_2c_203_20_3e',['FixedNumOperandTraits&lt; InsertElementInst, 3 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20insertvalueconstantexpr_2c_202_20_3e',['FixedNumOperandTraits&lt; InsertValueConstantExpr, 2 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20insertvalueinst_2c_202_20_3e',['FixedNumOperandTraits&lt; InsertValueInst, 2 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20resumeinst_2c_201_20_3e',['FixedNumOperandTraits&lt; ResumeInst, 1 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20selectconstantexpr_2c_203_20_3e',['FixedNumOperandTraits&lt; SelectConstantExpr, 3 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20selectinst_2c_203_20_3e',['FixedNumOperandTraits&lt; SelectInst, 3 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20shufflevectorconstantexpr_2c_203_20_3e',['FixedNumOperandTraits&lt; ShuffleVectorConstantExpr, 3 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20shufflevectorinst_2c_203_20_3e',['FixedNumOperandTraits&lt; ShuffleVectorInst, 3 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20storeinst_2c_202_20_3e',['FixedNumOperandTraits&lt; StoreInst, 2 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20unaryconstantexpr_2c_201_20_3e',['FixedNumOperandTraits&lt; UnaryConstantExpr, 1 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixednumoperandtraits_3c_20unaryinstruction_2c_201_20_3e',['FixedNumOperandTraits&lt; UnaryInstruction, 1 &gt;',['../structllvm_1_1FixedNumOperandTraits.html',1,'llvm']]],
  ['fixedstackpseudosourcevalue',['FixedStackPseudoSourceValue',['../classllvm_1_1FixedStackPseudoSourceValue.html',1,'llvm']]],
  ['flatit',['FlatIt',['../classllvm_1_1FlatIt.html',1,'llvm']]],
  ['fltsemantics',['fltSemantics',['../structllvm_1_1fltSemantics.html',1,'llvm']]],
  ['fneg_5fmatch',['fneg_match',['../structllvm_1_1PatternMatch_1_1fneg__match.html',1,'llvm::PatternMatch']]],
  ['foldingset',['FoldingSet',['../classllvm_1_1FoldingSet.html',1,'llvm']]],
  ['foldingset_3c_20listty_20_3e',['FoldingSet&lt; ListTy &gt;',['../classllvm_1_1FoldingSet.html',1,'llvm']]],
  ['foldingset_3c_20llvm_3a_3aattributeimpl_20_3e',['FoldingSet&lt; llvm::AttributeImpl &gt;',['../classllvm_1_1FoldingSet.html',1,'llvm']]],
  ['foldingset_3c_20llvm_3a_3aattributesetimpl_20_3e',['FoldingSet&lt; llvm::AttributeSetImpl &gt;',['../classllvm_1_1FoldingSet.html',1,'llvm']]],
  ['foldingset_3c_20llvm_3a_3aattributesetnode_20_3e',['FoldingSet&lt; llvm::AttributeSetNode &gt;',['../classllvm_1_1FoldingSet.html',1,'llvm']]],
  ['foldingset_3c_20llvm_3a_3adieabbrev_20_3e',['FoldingSet&lt; llvm::DIEAbbrev &gt;',['../classllvm_1_1FoldingSet.html',1,'llvm']]],
  ['foldingset_3c_20llvm_3a_3amdnode_20_3e',['FoldingSet&lt; llvm::MDNode &gt;',['../classllvm_1_1FoldingSet.html',1,'llvm']]],
  ['foldingset_3c_20llvm_3a_3ascev_20_3e',['FoldingSet&lt; llvm::SCEV &gt;',['../classllvm_1_1FoldingSet.html',1,'llvm']]],
  ['foldingset_3c_20llvm_3a_3asdnode_20_3e',['FoldingSet&lt; llvm::SDNode &gt;',['../classllvm_1_1FoldingSet.html',1,'llvm']]],
  ['foldingset_3c_20llvm_3a_3asdvtlistnode_20_3e',['FoldingSet&lt; llvm::SDVTListNode &gt;',['../classllvm_1_1FoldingSet.html',1,'llvm']]],
  ['foldingsetbucketiterator',['FoldingSetBucketIterator',['../classllvm_1_1FoldingSetBucketIterator.html',1,'llvm']]],
  ['foldingsetbucketiteratorimpl',['FoldingSetBucketIteratorImpl',['../classllvm_1_1FoldingSetBucketIteratorImpl.html',1,'llvm']]],
  ['foldingsetimpl',['FoldingSetImpl',['../classllvm_1_1FoldingSetImpl.html',1,'llvm']]],
  ['foldingsetiterator',['FoldingSetIterator',['../classllvm_1_1FoldingSetIterator.html',1,'llvm']]],
  ['foldingsetiteratorimpl',['FoldingSetIteratorImpl',['../classllvm_1_1FoldingSetIteratorImpl.html',1,'llvm']]],
  ['foldingsetnodeid',['FoldingSetNodeID',['../classllvm_1_1FoldingSetNodeID.html',1,'llvm']]],
  ['foldingsetnodeidref',['FoldingSetNodeIDRef',['../classllvm_1_1FoldingSetNodeIDRef.html',1,'llvm']]],
  ['foldingsetnodewrapper',['FoldingSetNodeWrapper',['../classllvm_1_1FoldingSetNodeWrapper.html',1,'llvm']]],
  ['foldingsettrait',['FoldingSetTrait',['../structllvm_1_1FoldingSetTrait.html',1,'llvm']]],
  ['foldingsettrait_3c_20mdnode_20_3e',['FoldingSetTrait&lt; MDNode &gt;',['../structllvm_1_1FoldingSetTrait_3_01MDNode_01_4.html',1,'llvm']]],
  ['foldingsettrait_3c_20scev_20_3e',['FoldingSetTrait&lt; SCEV &gt;',['../structllvm_1_1FoldingSetTrait_3_01SCEV_01_4.html',1,'llvm']]],
  ['foldingsettrait_3c_20sdvtlistnode_20_3e',['FoldingSetTrait&lt; SDVTListNode &gt;',['../structllvm_1_1FoldingSetTrait_3_01SDVTListNode_01_4.html',1,'llvm']]],
  ['foldingsettrait_3c_20t_20_2a_20_3e',['FoldingSetTrait&lt; T * &gt;',['../structllvm_1_1FoldingSetTrait_3_01T_01_5_01_4.html',1,'llvm']]],
  ['foldingsetvector',['FoldingSetVector',['../classllvm_1_1FoldingSetVector.html',1,'llvm']]],
  ['foldingsetvectoriterator',['FoldingSetVectorIterator',['../classllvm_1_1FoldingSetVectorIterator.html',1,'llvm']]],
  ['foreachloop',['ForeachLoop',['../structllvm_1_1ForeachLoop.html',1,'llvm']]],
  ['format_5fobject1',['format_object1',['../classllvm_1_1format__object1.html',1,'llvm']]],
  ['format_5fobject2',['format_object2',['../classllvm_1_1format__object2.html',1,'llvm']]],
  ['format_5fobject3',['format_object3',['../classllvm_1_1format__object3.html',1,'llvm']]],
  ['format_5fobject4',['format_object4',['../classllvm_1_1format__object4.html',1,'llvm']]],
  ['format_5fobject5',['format_object5',['../classllvm_1_1format__object5.html',1,'llvm']]],
  ['format_5fobject_5fbase',['format_object_base',['../classllvm_1_1format__object__base.html',1,'llvm']]],
  ['formatted_5fraw_5fostream',['formatted_raw_ostream',['../classllvm_1_1formatted__raw__ostream.html',1,'llvm']]],
  ['fp128',['fp128',['../classllvm_1_1types_1_1fp128.html',1,'llvm::types']]],
  ['fpextinst',['FPExtInst',['../classllvm_1_1FPExtInst.html',1,'llvm']]],
  ['fpmathoperator',['FPMathOperator',['../classllvm_1_1FPMathOperator.html',1,'llvm']]],
  ['fppassmanager',['FPPassManager',['../classllvm_1_1FPPassManager.html',1,'llvm']]],
  ['fptosiinst',['FPToSIInst',['../classllvm_1_1FPToSIInst.html',1,'llvm']]],
  ['fptouiinst',['FPToUIInst',['../classllvm_1_1FPToUIInst.html',1,'llvm']]],
  ['fptruncinst',['FPTruncInst',['../classllvm_1_1FPTruncInst.html',1,'llvm']]],
  ['frameentry',['FrameEntry',['../classllvm_1_1FrameEntry.html',1,'llvm']]],
  ['frameindexsdnode',['FrameIndexSDNode',['../classllvm_1_1FrameIndexSDNode.html',1,'llvm']]],
  ['fulldependence',['FullDependence',['../classllvm_1_1FullDependence.html',1,'llvm']]],
  ['function',['Function',['../structllvm_1_1MCModuleYAML_1_1Function.html',1,'llvm::MCModuleYAML']]],
  ['function',['Function',['../classllvm_1_1Function.html',1,'llvm']]],
  ['functionloweringinfo',['FunctionLoweringInfo',['../classllvm_1_1FunctionLoweringInfo.html',1,'llvm']]],
  ['functionpass',['FunctionPass',['../classllvm_1_1FunctionPass.html',1,'llvm']]],
  ['functionpassmanager',['FunctionPassManager',['../classllvm_1_1FunctionPassManager.html',1,'llvm']]],
  ['functionpassmanager',['FunctionPassManager',['../classllvm_1_1legacy_1_1FunctionPassManager.html',1,'llvm::legacy']]],
  ['functionpassmanagerimpl',['FunctionPassManagerImpl',['../classllvm_1_1legacy_1_1FunctionPassManagerImpl.html',1,'llvm::legacy']]],
  ['functiontype',['FunctionType',['../classllvm_1_1FunctionType.html',1,'llvm']]],
  ['functiontypekeyinfo',['FunctionTypeKeyInfo',['../structllvm_1_1FunctionTypeKeyInfo.html',1,'llvm']]],
  ['fvmfile_5fcommand',['fvmfile_command',['../structllvm_1_1MachO_1_1fvmfile__command.html',1,'llvm::MachO']]],
  ['fvmlib',['fvmlib',['../structllvm_1_1MachO_1_1fvmlib.html',1,'llvm::MachO']]],
  ['fvmlib_5fcommand',['fvmlib_command',['../structllvm_1_1MachO_1_1fvmlib__command.html',1,'llvm::MachO']]]
];
