var searchData=
[
  ['baseindexoffset',['BaseIndexOffset',['../structBaseIndexOffset.html',1,'']]],
  ['basic_5fcollection_5fiterator',['basic_collection_iterator',['../classllvm_1_1yaml_1_1basic__collection__iterator.html',1,'llvm::yaml']]],
  ['basic_5fparser',['basic_parser',['../classllvm_1_1cl_1_1basic__parser.html',1,'llvm::cl']]],
  ['basic_5fparser_3c_20bool_20_3e',['basic_parser&lt; bool &gt;',['../classllvm_1_1cl_1_1basic__parser.html',1,'llvm::cl']]],
  ['basic_5fparser_3c_20boolordefault_20_3e',['basic_parser&lt; boolOrDefault &gt;',['../classllvm_1_1cl_1_1basic__parser.html',1,'llvm::cl']]],
  ['basic_5fparser_3c_20char_20_3e',['basic_parser&lt; char &gt;',['../classllvm_1_1cl_1_1basic__parser.html',1,'llvm::cl']]],
  ['basic_5fparser_3c_20double_20_3e',['basic_parser&lt; double &gt;',['../classllvm_1_1cl_1_1basic__parser.html',1,'llvm::cl']]],
  ['basic_5fparser_3c_20float_20_3e',['basic_parser&lt; float &gt;',['../classllvm_1_1cl_1_1basic__parser.html',1,'llvm::cl']]],
  ['basic_5fparser_3c_20int_20_3e',['basic_parser&lt; int &gt;',['../classllvm_1_1cl_1_1basic__parser.html',1,'llvm::cl']]],
  ['basic_5fparser_3c_20std_3a_3astring_20_3e',['basic_parser&lt; std::string &gt;',['../classllvm_1_1cl_1_1basic__parser.html',1,'llvm::cl']]],
  ['basic_5fparser_3c_20unsigned_20_3e',['basic_parser&lt; unsigned &gt;',['../classllvm_1_1cl_1_1basic__parser.html',1,'llvm::cl']]],
  ['basic_5fparser_3c_20unsigned_20long_20long_20_3e',['basic_parser&lt; unsigned long long &gt;',['../classllvm_1_1cl_1_1basic__parser.html',1,'llvm::cl']]],
  ['basic_5fparser_5fimpl',['basic_parser_impl',['../classllvm_1_1cl_1_1basic__parser__impl.html',1,'llvm::cl']]],
  ['basicblock',['BasicBlock',['../structllvm_1_1MCModuleYAML_1_1BasicBlock.html',1,'llvm::MCModuleYAML']]],
  ['basicblock',['BasicBlock',['../classllvm_1_1BasicBlock.html',1,'llvm']]],
  ['basicblockedge',['BasicBlockEdge',['../classllvm_1_1BasicBlockEdge.html',1,'llvm']]],
  ['basicblockpass',['BasicBlockPass',['../classllvm_1_1BasicBlockPass.html',1,'llvm']]],
  ['basicblocksdnode',['BasicBlockSDNode',['../classllvm_1_1BasicBlockSDNode.html',1,'llvm']]],
  ['binary',['Binary',['../classllvm_1_1object_1_1Binary.html',1,'llvm::object']]],
  ['binaryconstantexpr',['BinaryConstantExpr',['../classllvm_1_1BinaryConstantExpr.html',1,'llvm']]],
  ['binaryop_5fmatch',['BinaryOp_match',['../structllvm_1_1PatternMatch_1_1BinaryOp__match.html',1,'llvm::PatternMatch']]],
  ['binaryoperator',['BinaryOperator',['../classllvm_1_1BinaryOperator.html',1,'llvm']]],
  ['binaryref',['BinaryRef',['../classllvm_1_1object_1_1yaml_1_1BinaryRef.html',1,'llvm::object::yaml']]],
  ['binarysdnode',['BinarySDNode',['../classllvm_1_1BinarySDNode.html',1,'llvm']]],
  ['bind_5fconst_5fintval_5fty',['bind_const_intval_ty',['../structllvm_1_1PatternMatch_1_1bind__const__intval__ty.html',1,'llvm::PatternMatch']]],
  ['bind_5fty',['bind_ty',['../structllvm_1_1PatternMatch_1_1bind__ty.html',1,'llvm::PatternMatch']]],
  ['binop2_5fmatch',['BinOp2_match',['../structllvm_1_1PatternMatch_1_1BinOp2__match.html',1,'llvm::PatternMatch']]],
  ['binopinit',['BinOpInit',['../classllvm_1_1BinOpInit.html',1,'llvm']]],
  ['bitcastinst',['BitCastInst',['../classllvm_1_1BitCastInst.html',1,'llvm']]],
  ['bitcodeabbrev',['BitCodeAbbrev',['../classllvm_1_1BitCodeAbbrev.html',1,'llvm']]],
  ['bitcodeabbrevop',['BitCodeAbbrevOp',['../classllvm_1_1BitCodeAbbrevOp.html',1,'llvm']]],
  ['bitcodereader',['BitcodeReader',['../classllvm_1_1BitcodeReader.html',1,'llvm']]],
  ['bitcodereadermdvaluelist',['BitcodeReaderMDValueList',['../classllvm_1_1BitcodeReaderMDValueList.html',1,'llvm']]],
  ['bitcodereadervaluelist',['BitcodeReaderValueList',['../classllvm_1_1BitcodeReaderValueList.html',1,'llvm']]],
  ['bitinit',['BitInit',['../classllvm_1_1BitInit.html',1,'llvm']]],
  ['bitrecty',['BitRecTy',['../classllvm_1_1BitRecTy.html',1,'llvm']]],
  ['bits',['bits',['../classllvm_1_1cl_1_1bits.html',1,'llvm::cl']]],
  ['bits_5fstorage',['bits_storage',['../classllvm_1_1cl_1_1bits__storage.html',1,'llvm::cl']]],
  ['bits_5fstorage_3c_20datatype_2c_20bool_20_3e',['bits_storage&lt; DataType, bool &gt;',['../classllvm_1_1cl_1_1bits__storage_3_01DataType_00_01bool_01_4.html',1,'llvm::cl']]],
  ['bits_5fstorage_3c_20datatype_2c_20storage_20_3e',['bits_storage&lt; DataType, Storage &gt;',['../classllvm_1_1cl_1_1bits__storage.html',1,'llvm::cl']]],
  ['bitsinit',['BitsInit',['../classllvm_1_1BitsInit.html',1,'llvm']]],
  ['bitsrecty',['BitsRecTy',['../classllvm_1_1BitsRecTy.html',1,'llvm']]],
  ['bitstreamcursor',['BitstreamCursor',['../classllvm_1_1BitstreamCursor.html',1,'llvm']]],
  ['bitstreamentry',['BitstreamEntry',['../structllvm_1_1BitstreamEntry.html',1,'llvm']]],
  ['bitstreamreader',['BitstreamReader',['../classllvm_1_1BitstreamReader.html',1,'llvm']]],
  ['bitstreamwriter',['BitstreamWriter',['../classllvm_1_1BitstreamWriter.html',1,'llvm']]],
  ['bitvector',['BitVector',['../classllvm_1_1BitVector.html',1,'llvm']]],
  ['block_5fiterator_5fwrapper',['block_iterator_wrapper',['../classllvm_1_1Region_1_1block__iterator__wrapper.html',1,'llvm::Region']]],
  ['blockaddress',['BlockAddress',['../classllvm_1_1BlockAddress.html',1,'llvm']]],
  ['blockaddresssdnode',['BlockAddressSDNode',['../classllvm_1_1BlockAddressSDNode.html',1,'llvm']]],
  ['blockconstraint',['BlockConstraint',['../structllvm_1_1SpillPlacement_1_1BlockConstraint.html',1,'llvm::SpillPlacement']]],
  ['blockfrequency',['BlockFrequency',['../classllvm_1_1BlockFrequency.html',1,'llvm']]],
  ['blockfrequencyimpl',['BlockFrequencyImpl',['../classllvm_1_1BlockFrequencyImpl.html',1,'llvm']]],
  ['blockfrequencyimpl_3c_20llvm_3a_3abasicblock_2c_20llvm_3a_3afunction_2c_20llvm_3a_3abranchprobabilityinfo_20_3e',['BlockFrequencyImpl&lt; llvm::BasicBlock, llvm::Function, llvm::BranchProbabilityInfo &gt;',['../classllvm_1_1BlockFrequencyImpl.html',1,'llvm']]],
  ['blockfrequencyimpl_3c_20llvm_3a_3amachinebasicblock_2c_20llvm_3a_3amachinefunction_2c_20llvm_3a_3amachinebranchprobabilityinfo_20_3e',['BlockFrequencyImpl&lt; llvm::MachineBasicBlock, llvm::MachineFunction, llvm::MachineBranchProbabilityInfo &gt;',['../classllvm_1_1BlockFrequencyImpl.html',1,'llvm']]],
  ['blockfrequencyinfo',['BlockFrequencyInfo',['../classllvm_1_1BlockFrequencyInfo.html',1,'llvm']]],
  ['blockinfo',['BlockInfo',['../structllvm_1_1SplitAnalysis_1_1BlockInfo.html',1,'llvm::SplitAnalysis']]],
  ['blockinfo',['BlockInfo',['../structllvm_1_1BitstreamReader_1_1BlockInfo.html',1,'llvm::BitstreamReader']]],
  ['br_5fmatch',['br_match',['../structllvm_1_1PatternMatch_1_1br__match.html',1,'llvm::PatternMatch']]],
  ['branch',['Branch',['../structllvm_1_1SystemZII_1_1Branch.html',1,'llvm::SystemZII']]],
  ['branchfolder',['BranchFolder',['../classllvm_1_1BranchFolder.html',1,'llvm']]],
  ['branchinst',['BranchInst',['../classllvm_1_1BranchInst.html',1,'llvm']]],
  ['branchnode',['BranchNode',['../classllvm_1_1IntervalMapImpl_1_1BranchNode.html',1,'llvm::IntervalMapImpl']]],
  ['branchnode_3c_20keyt_2c_20valt_2c_20rootbranchcap_2c_20traits_20_3e',['BranchNode&lt; KeyT, ValT, RootBranchCap, Traits &gt;',['../classllvm_1_1IntervalMapImpl_1_1BranchNode.html',1,'llvm::IntervalMapImpl']]],
  ['branchprobability',['BranchProbability',['../classllvm_1_1BranchProbability.html',1,'llvm']]],
  ['branchprobabilityinfo',['BranchProbabilityInfo',['../classllvm_1_1BranchProbabilityInfo.html',1,'llvm']]],
  ['brc_5fmatch',['brc_match',['../structllvm_1_1PatternMatch_1_1brc__match.html',1,'llvm::PatternMatch']]],
  ['briggs',['Briggs',['../classPBQP_1_1Heuristics_1_1Briggs.html',1,'PBQP::Heuristics']]],
  ['buildvectorsdnode',['BuildVectorSDNode',['../classllvm_1_1BuildVectorSDNode.html',1,'llvm']]],
  ['bumpptrallocator',['BumpPtrAllocator',['../classllvm_1_1BumpPtrAllocator.html',1,'llvm']]],
  ['bundle_5fiterator',['bundle_iterator',['../classllvm_1_1MachineBasicBlock_1_1bundle__iterator.html',1,'llvm::MachineBasicBlock']]],
  ['byvalarginfo',['ByValArgInfo',['../structllvm_1_1MipsTargetLowering_1_1ByValArgInfo.html',1,'llvm::MipsTargetLowering']]]
];
